### ISSUE TITLE
[Bug]: DN Panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10003]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1253" alt="image" src="https://github.com/matrixorigin/matrixone/assets/2995754/99c8488f-4c2a-4063-a4ca-e174b213711a">

### Steps to Reproduce

```Markdown
run bvt ci
```

### Additional information

https://github.com/matrixorigin/matrixone/actions/runs/5244734419?pr=10001

**Comment by aressu1985** [comment]
偶现问题，先降级成s0跟踪

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
确认了alloc preparets的时候没有回退。增加了debug日志。过滤了replay的txn。还要继续等复现

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
还没有进展

**Comment by jiangxinmeng1** [comment]
一直没有复现。#10761过滤了replay txn，修好了。
