### ISSUE TITLE
[Bug]: Current way of detecting a connection in active txn is not robust

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

#10000 

The current way of detecting a connection in Txn is not robust.    For example, the regular expression wont match something with comment like
```
begin /* this is my toy txn */;
```

See the discussion in the PR.

### Expected Behavior

The we we detect active transaction is not robust enough. Is there anything more reliable from the protocol level? For example, when we plan to migrate a connection, can we issue a command to server to check if current connection is in transaction?

Assume connection migration is rare, and probably you HAVE TO migrate no matter what (due to CN crash/congestion etc), why don't we just simply abort current transaction and migrate?

**Comment by volgariver6** [comment]
fixed by #10486 

Now proxy gets txn status from OK packet or EOF packet which is received from server.
