### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: unique index do not lock 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10024]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c1e25e07ab82168ffd33ffc4f6e0c561ea472335
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo：
<img width="1069" alt="企业微信截图_276882b4-03c0-47a3-9999-c0bf7762d5a0" src="https://github.com/matrixorigin/matrixone/assets/113406637/512d6420-3ede-4cdd-bc34-1389c9008720">
<img width="1138" alt="企业微信截图_e6e15417-9b94-489f-a274-37d3ee9b16d3" src="https://github.com/matrixorigin/matrixone/assets/113406637/400c202b-890d-4719-8ba7-6840f1b7eac7">

mysql lock unique index：
<img width="1124" alt="企业微信截图_7249b612-7be7-49a9-97eb-947ec8397d8f" src="https://github.com/matrixorigin/matrixone/assets/113406637/a112ddbd-9fe1-439c-9964-95ef723fd0aa">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d4a34250-75c2-4ba0-bcfd-a14b2bd533df)

### Steps to Reproduce

```Markdown
drop table if exists employees;
CREATE TABLE employees (
	emp_no INT NOT NULL,
	fname VARCHAR(30),
	lname VARCHAR(30),
	hired DATE NOT NULL DEFAULT '1970-01-01',
	separated DATE NOT NULL DEFAULT '9999-12-31',
	job_code INT,
	store_id INT,
	unique key(emp_no)
);


begin;
INSERT INTO employees VALUES (10001, 'Georgi', 'Facello', '1953-09-02','1986-06-26',120, 1);
-- @session:id=2&user=sys:dump&password=111
INSERT INTO employees VALUES (10001, 'Georgisdfs', 'Facelloxxx', '1953-10-02','1986-04-26',120, 1);  
-- @session
commit;
```

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm this issue

**Comment by zhangxu19830126** [comment]
请潇哥确认下，悲观事务对于唯一索引的行为

**Comment by domingozhang** [comment]
唯一键存在时，锁行为可以概括为：
对未提交的新唯一键值键上锁，其他事物不可使用该唯一键
对已存在的唯一键值发生修改且未提交时，对应的行加锁


例如：
set autocommit=1;
create table t1(a int unique key,b int);
insert into t1 values(0);

session 1:
begin;
insert into t1 values(1);   -----对1对应值加锁
update t1 set a=2 where a=0; ------对0所在的行加锁

session 2:
insert into t1 values(1); -----1存在未提交值，等待
insert into t1 values(0); -----0所在行有锁，等待

复合唯一键同样遵循改规则：
create table t1(a int ,b int, unique(a,b));
insert into t1 values(1,2);
insert into t1 values(3,4);

session 1:
begin;
insert into t1 values(1,1);    -----对(1,1)所对应值加锁
update t1 set a=3 where b=2;   ------对(1,2)所对应的行加锁

session 2:
insert into t1 values(1,1); -----(1,1)组合有锁，等待
update t set a=4 where b=2; -----(1,2)所在行存在未提交，等待
update t set a=5 where b=4;-----(3,4)所在行不存在未提交，成功更新

**Comment by zhangxu19830126** [comment]
@ouyuanning 看一下，唯一键等这些约束，是否集成lock算子

**Comment by ouyuanning** [comment]
待pr合并

**Comment by heni02** [comment]
confirm,closed
commit id:a65a505f3549160c83057125303e5f8f442a8a1b
<img width="1035" alt="企业微信截图_764c2166-307f-4130-9844-af371940764a" src="https://github.com/matrixorigin/matrixone/assets/113406637/db764361-eefc-4830-9eca-13ba0f984dac">
<img width="1119" alt="企业微信截图_6f5ba71d-a4c6-4dd6-a883-afd5d7153227" src="https://github.com/matrixorigin/matrixone/assets/113406637/cd2415b0-da8b-4ec1-a390-73f1a12a7409">
