### ISSUE TITLE
[Bug]: ERROR 20443 (HY000): no configure: save query result

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#10038]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bb9a3373a1e2b1b86a3325fad3dbde5e686076e4
- Hardware parameters:
- OS type:MACOS
- Others:
```

### Actual Behavior

1. create database test;
2. use test;
3. create table t1(
                   clo1 tinyint,
                   clo2 smallint,
                   clo3 int,
                   clo4 bigint,
                   clo5 tinyint unsigned,
                   clo6 smallint unsigned,
                   clo7 int unsigned,
                   clo8 bigint unsigned,
                   col9 float,
                   col10 double,
                   col11 varchar(255),
                   col12 Date,
                   col13 DateTime,
                   col14 timestamp,
                   col15 bool,
                   col16 decimal(5,2),
                   col17 text,
                   col18 json,
                   col19 blob,
                   col20 binary(255),
                   col21 varbinary(255)
);
4. insert into t1 (clo1, clo2, clo3, clo4, clo5, clo6, clo7, clo8, col9, col10, col11, col12, col13, col14, col15, col16, col17, col18, col19, col20, col21) VALUES
                                                                                                                                                              (1, 100, 1000, 10000, 1, 100, 1000, 10000, 1.23, 1.2345, 'Text 1', '2023-05-29', '2023-05-29 12:34:56', '2023-05-29 12:34:56', TRUE, 1.23, 'Text 1', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (2, 200, 2000, 20000, 2, 200, 2000, 20000, 2.34, 2.3456, 'Text 2', '2023-05-30', '2023-05-30 12:34:56', '2023-05-30 12:34:56', FALSE, 2.34, 'Text 2', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (3, 300, 3000, 30000, 3, 300, 3000, 30000, 3.45, 3.4567, 'Text 3', '2023-05-31', '2023-05-31 12:34:56', '2023-05-31 12:34:56', TRUE, 3.45, 'Text 3', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (4, 400, 4000, 40000, 4, 400, 4000, 40000, 4.56, 4.5678, 'Text 4', '2023-06-01', '2023-06-01 12:34:56', '2023-06-01 12:34:56', FALSE, 4.56, 'Text 4', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (5, 500, 5000, 50000, 5, 500, 5000, 50000, 5.67, 5.6789, 'Text 5', '2023-06-02', '2023-06-02 12:34:56', '2023-06-02 12:34:56', TRUE, 5.67, 'Text 5', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (6, 600, 6000, 60000, 6, 600, 6000, 60000, 6.78, 6.7890, 'Text 6', '2023-06-03', '2023-06-03 12:34:56', '2023-06-03 12:34:56', FALSE, 6.78, 'Text 6', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data');

5. select * from test.t1;
6. /* cloud_nonuser */ select * from result_scan(last_query_id()) as t limit 0,1000;

ERROR 20443 (HY000): no configure: save query result

### Expected Behavior

get all results as select * from test.t1;

### Steps to Reproduce

```Markdown
as actual behavior
```

### Additional information
MO Cloud use the SQL to Query Exec Result.

_No response_

**Comment by sukki37** [comment]
This issue seems to be caused by the following configuration not taking effect:
```
[cn.frontend]
saveQueryResult = "on"
```

@daviszhen pls help on this issue, thank you.

**Comment by daviszhen** [comment]
@xiaoshuwei @sukki37 这个不是bug。
1，`save_query_result` 系统变量。默认值就是off的。不保存查询结果。此时执行result_scan 会报"no configure: save query result"错误。

2，`save_query_result` 开启方式。
- 配置文件
[cn.frontend]
saveQueryResult = "on"

- set global save_query_result = on;

**Comment by DanielZhangQD** [comment]
> @xiaoshuwei @sukki37 这个不是bug。 1，`save_query_result` 系统变量。默认值就是off的。不保存查询结果。此时执行result_scan 会报"no configure: save query result"错误。
> 
> 2，`save_query_result` 开启方式。
> 
> * 配置文件。全局打开。所有session，默认打开。
>   [cn.frontend]
>   saveQueryResult = "on"
> * `set global save_query_result = on; `。只打开session内部。
>   用法见set global save_query_result = on;

@daviszhen 配置文件配置了：
```
[cn.frontend]
proxy-enabled = true
queryResultTimeout = 72
saveQueryResult = "on"
```

**Comment by xiaoshuwei** [comment]
## 补充版本信息
AWS: nightly-d84b7b0
ALIYun: nightly-84b8491c

**Comment by domingozhang** [comment]
If one configuration item in cn config file is different from the catalog table, the value in table will be effected.
I suggest modify the value in cli with set global statement.

**Comment by YANGGMM** [comment]
still on working

**Comment by YANGGMM** [comment]
still on working

**Comment by YANGGMM** [comment]
still on working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
have opened  a pr

**Comment by YANGGMM** [comment]
plz test it @xiaoshuwei

**Comment by YANGGMM** [comment]
waitting test
