### ISSUE TITLE
[Bug]: mo crash by panic: runtime error: invalid memory address or nil pointer dereference during stability test on standlone

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10036]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):62e42fa1022b3a3326967c270bf22726a7777b5e
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

during stability test on standlone, the mo panic : 
2023/06/13 21:57:50.333152 +0800 INFO frontend/util.go:533 time of Exec.Build : 19.56453529s connectionId 2391|127.0.0.1:55800|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 247503|58c3111f-09c8-11ee-a77a-525400777c3a
2023/06/13 21:57:50.333190 +0800 INFO frontend/util.go:533 time of Exec.Build : 3.915654786s connectionId 2374|127.0.0.1:55764|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 245405|585a8d63-09c8-11ee-a77a-525400777c3a
2023/06/13 21:57:50.333305 +0800 INFO frontend/util.go:533 time of Exec.Build : 12.619865579s connectionId 2350|127.0.0.1:55708|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 242209|5779a3f0-09c8-11ee-a77a-525400777c3a
2023/06/13 21:57:50.333470 +0800 INFO frontend/util.go:533 time of Exec.Build : 12.754083826s connectionId 2351|127.0.0.1:55710|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 242461|57878350-09c8-11ee-a77a-525400777c3a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1e90a75]

goroutine 73636064 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).newMergeReader(0xc2b12b0fc0, {0x2da38b8, 0xc352636210}, 0x1, 0xc713680690)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/txn_table.go:1331 +0x55
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).NewReader(0xc7132611c0?, {0x2da38b8, 0xc352636210}, 0x1, 0xe?, {0xc71e302a50, 0x2, 0x2})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/txn_table.go:1305 +0x12c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc712999c70, 0xc33dd85200, 0x0)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:304 +0x511
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc712999c70, 0xc33dd85200)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:188 +0xa5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0x2540be400?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:122 +0x2f
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:121 +0x1f8

mo log:
[service.log.tar.gz](https://github.com/matrixorigin/matrixone/files/11741300/service.log.tar.gz)

### Steps to Reproduce

```Markdown
run a mo tester on stanlone and run the following test
1. bvt loop
   git clone mo-tester
   ./run.sh -n -g -p  xxxxx/matrixone/test/distributed/cases -e ddl -t 100

2. tpch loop 
   git clone mo-tpch, laod tpch 10G data
   ./run.sh -q all -s 10 -t 50000

3. sysbench mixed
   git clone mo-load, and init 10-talbes-100000-per-table 
   ./start.sh -m SYSBENCH -n 10 -s 100000
   ./start.sh -c cases/sysbench/mixed_10_100000/ -d 5000 -g

4. tpcc 10-10 long run
   git clone mo-tpcc, and load tpcc 10 warehouse data, and modify runMins to 5000 in props.mo
   ./runBenchmark.sh props.mo
```

**Comment by m-schen** [comment]
可能是cn0与cn1持有的log tail时间戳不一致导致的。不肯定。只是猜测。

**Comment by m-schen** [comment]
> 可能是cn0与cn1持有的log tail时间戳不一致导致的。不肯定。只是猜测。

搞错了 standalone 请无视

**Comment by m-schen** [comment]
猜测可能是memory table被重连清空了，需要从日志验证一下，晚点回复。

**Comment by m-schen** [comment]
解决方案：
1. add a flag into txn framework to indicate if cn engine can support server or not.
2. if try to reconnect or first time connect to dn, set flag = false
3. get running txn list, set all to be aborted.
4. clean memory table
5. if reconnect succeed, set flag = true
6. if try to get data from memory table, should check txn status first, if aborted, return error.

**Comment by m-schen** [comment]
https://github.com/m-schen/matrixone/tree/fix-10036 还没改完 需要自测

**Comment by m-schen** [comment]
要等一下main分支处理ci问题，现在合不进去。

**Comment by m-schen** [comment]
刚提交pr

**Comment by m-schen** [comment]
今天pr应该可以合并进去。

**Comment by aressu1985** [comment]
fixed
