### ISSUE TITLE
[Bug]: mo hung on standlone after running some loading data test on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10046]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):cb1e8113c785aaf763a69901e20a533cf052da68
- Hardware parameters:64C 256G
- OS type:
- Others:
```

### Actual Behavior

on standlone mode, during some loading data test( executing ctrl+c for serval times ), the mo was hung.
<img width="714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/723103ce-ed5a-442f-a918-4049d3da6193">

the mo log:
[server.log](https://github.com/matrixorigin/matrixone/files/11743578/server.log)

profile:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/11743581/profile.tar.gz)

### Steps to Reproduce

```Markdown
It is occasional.
```

**Comment by LeftHandCold** [comment]
<img width="1025" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/e735b877-8869-44e7-83ff-f05d42f36a69">
@zhangxu19830126

**Comment by zhangxu19830126** [comment]
fixed
