### ISSUE TITLE
[Bug]: The result of window function is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10043]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:89f1e1a44cfff4eb6b385318503d07c75dabac1f
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/108530700/33f1959e-c57c-4aab-b0df-77a26719dd95)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/4c0ac9c8-e539-4a69-97d7-6faa3420f778)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/87a48822-57dd-4b7a-aff5-dd5fa7e73f61)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/e14e631f-5ded-4dec-906c-5beb891ecb7e)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/ba2efe43-8438-4837-8d15-8b9f8859f273)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/c4208d22-9c1c-44ed-9efa-e4b7d0a41a87)

### Expected Behavior

![image](https://github.com/matrixorigin/matrixone/assets/108530700/1fc29adc-3210-479c-b571-ab3b6ff92a73)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/57ec7627-2f2d-43ed-b849-e1e11f357e73)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/1d5c98f2-3817-47ee-89fd-5260ce7fcac1)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/676e65a1-529a-4656-8e5b-681e37a9f3ef)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/19c395d8-cf88-4907-87ce-350596c0af28)
![image](https://github.com/matrixorigin/matrixone/assets/108530700/1f147c8e-0eb7-4134-a2a2-35d0abbd40fe)

### Steps to Reproduce

```Markdown
drop table if exists row01;
create table row01(i int,j int);
insert into row01 values(1,1);
insert into row01 values(1,4);
insert into row01 values(1,2);
insert into row01 values(1,4);
select * from row01;
select i, j, sum(i+j) over (order by j rows between 2 preceding and 1 preceding) foo from row01 order by foo desc;
select i, j, sum(i+j) over (order by j rows between 2 following and 1 following) foo from row01 order by foo desc;


drop table if exists test01;
create table test01(i int, j int);
insert into test01 values (1,null);
insert into test01 values (1,null);
insert into test01 values (1,1);
insert into test01 values (1,null);
insert into test01 values (1,2);
insert into test01 values (2,1);
insert into test01 values (2,2);
insert into test01 values (2,null);
insert into test01 values (2,null);
select * from test01;
select i, j, min(j) over (partition by i order by j rows unbounded preceding) from test01;


drop table if exists double01;
create table double01(d double);
insert into double01 values (2);
insert into double01 values (2);
insert into double01 values (3);
insert into double01 values (1);
insert into double01 values (1);
insert into double01 values (1.2);
insert into double01 values (null);
insert into double01 values (null);
select * from double01;
select d, sum(d) over (partition by d order by d), avg(d) over (order by d rows between 1 preceding and 1 following) from double01;
select d, sum(d) over (partition by d order by d), avg(d) over (order by d rows between 2 preceding and 1 following) from double01;


drop table if exists wf01;
create table wf01(d float);
insert into wf01 values (10);
insert into wf01 values (1);
insert into wf01 values (2);
insert into wf01 values (3);
insert into wf01 values (4);
insert into wf01 values (5);
insert into wf01 values (6);
insert into wf01 values (7);
insert into wf01 values (8);
insert into wf01 values (9);
select * from wf01;
select d, sum(d) over (order by d range between current row and 2 following), 
    avg(d) over (order by d range between current row and 2 following) from wf01;
select d, sum(d) over (order by d range between 2 preceding and 2 following),
	avg(d) over (order by d range between current row and 2 following) from wf01;



drop table if exists decimal01;
create table decimal01(d decimal(38,3));
insert into decimal01 values (28888888888888888888888888888888888.1234);
insert into decimal01 values (99999999999999999999999999999999999.83293323);
insert into decimal01 values (0);
insert into decimal01 values (-7841512312154312313158786541.342152121242143);
insert into decimal01 values (-7841512312154312313158786541.342152121242143);
insert into decimal01 values (99999999999999999999999999999999999.83293323);
insert into decimal01 values (null);
insert into decimal01 values (null);
select * from decimal01;
select sum(d) over (partition by d order by d rows between 1 preceding and 1 following) from decimal01;



drop table if exists dense_rank01;
create table dense_rank01 (id integer, sex char(1));
insert into dense_rank01 values (1, 'm');
insert into dense_rank01 values (2, 'f');
insert into dense_rank01 values (3, 'f');
insert into dense_rank01 values (4, 'f');
insert into dense_rank01 values (5, 'm');
select * from dense_rank01;
select sex, id, rank() over (partition by sex order by id desc) from dense_rank01;
select sex, id, dense_rank() over (partition by sex order by id desc) from dense_rank01;

```

**Comment by iamlinjunhong** [comment]
mysql bug: select i, j, min(j) over (partition by i order by j rows unbounded preceding) from test01;
pg result:
<img width="1088" alt="截屏2023-06-20 下午2 41 01" src="https://github.com/matrixorigin/matrixone/assets/49111204/a02d6c9f-9dbb-4839-bd24-8005d258e5f4">

**Comment by iamlinjunhong** [comment]
mo decimal out of range: select sum(d) over (partition by d order by d rows between 1 preceding and 1 following) from decimal01;
<img width="1429" alt="截屏2023-06-20 下午2 47 01" src="https://github.com/matrixorigin/matrixone/assets/49111204/0b0b4343-7f12-4db7-92e0-21cc7187a784">
mysql result:
<img width="1377" alt="截屏2023-06-20 下午2 47 24" src="https://github.com/matrixorigin/matrixone/assets/49111204/8019da4a-872c-48cc-ab72-d30108d0268a">

**Comment by Ariznawlll** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/108530700/59e917bc-93fe-4c2d-9c91-9d76092dc787)

mysql's result is incorrect, the correct result is the same as pgsql.
![image](https://github.com/matrixorigin/matrixone/assets/108530700/64c79b0b-4864-4e5b-a74e-8b9a2498308d)

![image](https://github.com/matrixorigin/matrixone/assets/108530700/d75c2144-4603-44ba-ab2f-a2143d054a64)

If decimal is involved in the calculation, an error will be reported when the number of bits overflows:
<img width="568" alt="企业微信截图_275ab485-ea9c-49bb-95cb-d3f4adeef580" src="https://github.com/matrixorigin/matrixone/assets/108530700/bbb36198-077f-4235-9bcc-1e31bc646084">

![image](https://github.com/matrixorigin/matrixone/assets/108530700/700fb443-b67f-4e01-8648-9f23be9474ed)


test done!
