### ISSUE TITLE
[Bug]: fileservice throw error "service SHARED not found"

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10047]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bb9a3373a1e2b1b86a3325fad3dbde5e686076e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the file exists. but fileservice reports "service SHARED not found".

![image](https://github.com/matrixorigin/matrixone/assets/60595215/43ab591f-e2e3-47d6-829e-14aa05ec2314)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/265cc9f9-94cf-4af5-a179-c0918cee0ea5)

### Expected Behavior

get the file normally.

### Steps to Reproduce

```Markdown
create table t(a int);
insert into t values (1);
set global save_query_result = on;
select * from t;
select last_query_id();
-- you will get the uuid in the output.
select * from result_scan('uuid in the output');
```

**Comment by reusee** [comment]
This is not a file service issue.

**Comment by reusee** [comment]
Either change to use ETL to store query result, or add new colexec package to access the SHARED fs. As the name suggested, external col exec is for accessing external fs only, not for SHARED

**Comment by iamlinjunhong** [comment]
wrong sql
<img width="1203" alt="截屏2023-06-19 下午3 15 53" src="https://github.com/matrixorigin/matrixone/assets/49111204/7851f115-2351-48e0-bf44-98a97d75a673">

**Comment by daviszhen** [comment]
用错
