### ISSUE TITLE
[Feature Request]: table function missing "apply" semantics.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10060]
### Is there an existing issue for the same feature request?

- [x] I have checked the existing issues.

### Describe the feature you'd like

consider the following,
```
mysql> select * from t;
+------+------------------------+
| id   | j                      |
+------+------------------------+
|    1 | {"bar": 2, "foo": 1}   |
|    2 | {"bar": 22, "foo": 11} |
+------+------------------------+
2 rows in set (0.01 sec)

mysql> select * from t, unnest(t.j, '$');
ERROR 1149 (HY000): SQL syntax error: Every table function must have an alias
mysql> select * from t, unnest(t.j, '$') tmp;
+------+------------------------+------+------+------+-------+-------+-------+------------------------+
| id   | j                      | col  | seq  | key  | path  | index | value | this                   |
+------+------------------------+------+------+------+-------+-------+-------+------------------------+
|    1 | {"bar": 2, "foo": 1}   | t.j  |    0 | bar  | $.bar |  NULL | 2     | {"bar": 2, "foo": 1}   |
|    1 | {"bar": 2, "foo": 1}   | t.j  |    1 | foo  | $.foo |  NULL | 1     | {"bar": 2, "foo": 1}   |
|    1 | {"bar": 2, "foo": 1}   | t.j  |    0 | bar  | $.bar |  NULL | 22    | {"bar": 22, "foo": 11} |
|    1 | {"bar": 2, "foo": 1}   | t.j  |    1 | foo  | $.foo |  NULL | 11    | {"bar": 22, "foo": 11} |
|    2 | {"bar": 22, "foo": 11} | t.j  |    0 | bar  | $.bar |  NULL | 2     | {"bar": 2, "foo": 1}   |
|    2 | {"bar": 22, "foo": 11} | t.j  |    1 | foo  | $.foo |  NULL | 1     | {"bar": 2, "foo": 1}   |
|    2 | {"bar": 22, "foo": 11} | t.j  |    0 | bar  | $.bar |  NULL | 22    | {"bar": 22, "foo": 11} |
|    2 | {"bar": 22, "foo": 11} | t.j  |    1 | foo  | $.foo |  NULL | 11    | {"bar": 22, "foo": 11} |
+------+------------------------+------+------+------+-------+-------+-------+------------------------+
8 rows in set (0.01 sec)

mysql> select * from unnest(t.j, '$') tmp;
ERROR 20301 (HY000): invalid input: missing FROM-clause entry for table 't'
mysql>
```

Note that `select * from unnest(t.j, '$') tmp;` will fail because we do not know how to bind t.    The only way is to write it out a join.    Unfortunately this turns the join to a cross product.    Each row will unnest to two rows, instead of 4 rows (which most people want), we computed 8 rows.

There need to be a 'CROSS APPLY' semmantics.   

### Describe implementation you've considered

Snowflake syntax.
```
SELECT id as "ID",
   f.value AS "Contact",
   f1.value:type AS "Type",
   f1.value:content AS "Details"
 FROM persons p,
   lateral flatten(input => p.c, path => 'contact') f,
   lateral flatten(input => f.value:business) f1;
```

SQLServer has CROSS APPLY

PartiQL . operator syntax
```
SELECT e.name AS employeeName, p.name AS projectName
FROM hr.employeesNest AS e, e.projects AS p
WHERE p.name LIKE '%security%'
```

Either CROSS APPLY or LATERAL works.

**Comment by dengn** [comment]
A detailed syntax and use case is required for documentation job.

**Comment by domingozhang** [comment]
select * from unnest(t.j, '$') tmp;
without source table ,this can be passed

**Comment by fengttt** [comment]
```mysql> explain select * from tj, unnest(tj.a, '$') u;
+----------------------------------------+
| TP QURERY PLAN                         |
+----------------------------------------+
| Project                                |
|   ->  Join                             |
|         Join Type: INNER               |
|         ->  Table Scan on foo.tj       |
|         ->  Table Function on unnest   |
|               ->  Table Scan on foo.tj |
+----------------------------------------+
6 rows in set (0.01 sec)

mysql>
```

If you look at the plan, all we need to do is not generate the join operator.

select t.*, u.* from tj t CROSS APPLY unnest(tj.a, '$') u;
Just make sure the table function this time, include columns from both t and u.

**Comment by fengttt** [comment]
Syntax, I think we should take the SQL Server cross apply approach.[SQL Server Cross Apply](https://learn.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16#using-apply

**Comment by fengttt** [comment]
Let's consider the following, 
```
select T.*, tmpt.* from T CROSS/OUTER APPLY TVF(t.c1, t.c2) tempt
```

Let's assume, `CROSS/OUTER APPLY` always apply from a table (in general sense, which can be a subquery for example) to a table value function.    TVF arguments can refer to columns in T.   Output should include all columns from T and TVF, of course, we can project them.   It is exactly the same as project expo list of join.

Note that the other side of cross apply does not really need to be a TVF.   For example, correlated subqueries can be evaluated this way.   But let's hold that off for now and do it later, maybe ...

**Comment by zengyan1** [comment]
Completed, need test, @aressu1985 thanks.

**Comment by heni02** [comment]
挪到2.0.1测试

**Comment by tom-csf** [comment]
验证cross apply 和 outer apply 完成

**Comment by aressu1985** [comment]
TEST DONE
