### ISSUE TITLE
[Bug]: partition: mo DECIMAL64/float/double is not allowed in partition ,mysql support

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10064]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1a2c60ebfcdc4519a33886ba8054824bddbb9da6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f54b9161-4eb0-4ba9-b128-72e9f4746ba5)
mysql> create table p_table_18(col1 bigint,col2 varchar(25),col3 decimal(6,4))partition by key(col3)partitions 2;
ERROR 1149 (HY000): SQL syntax error: column col3 type DECIMAL64 is not allowed in partition clause
same as double ,float type
create table p_table_18(col1 bigint,col2 varchar(25),col3 float)partition by key(col3)partitions 2;
SQL syntax error: column col3 type FLOAT is not allowed in partition clause
create table p_table_18(col1 bigint,col2 varchar(25),col3 double)partition by key(col3)partitions 2;
SQL syntax error: column col3 type DOUBLE is not allowed in partition clause

### Steps to Reproduce

```Markdown
create table p_table_18(col1 bigint,col2 varchar(25),col3 decimal(6,4))partition by key(col3)partitions 2;
create table p_table_18(col1 bigint,col2 varchar(25),col3 float)partition by key(col3)partitions 2;
create table p_table_18(col1 bigint,col2 varchar(25),col3 double)partition by key(col3)partitions 2;
```

**Comment by heni02** [comment]
@qingxinhome plz confirm this issue

**Comment by qingxinhome** [comment]
Received message

**Comment by qingxinhome** [comment]
The issue has been resolved, please confirm and test @heni02 @daviszhen

**Comment by heni02** [comment]
confirm,closed
commit id:6c14bc30b09ef54c53f0fb7e992fb1343ecd0c76
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ce0c5e7a-03b8-4e9c-8997-258ac7d91166)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7cd646c7-a95d-42fb-9053-b3c620333801)
