### ISSUE TITLE
[Bug]: no such table load_data.t7 during bvt test

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#10078]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b1543cf47
- Hardware parameters:
- OS type:macs
- Others:
```

### Actual Behavior

<img width="972" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/30c32e19-5083-4cc2-827d-91329060f14c">

Context of error related statements：https://github.com/matrixorigin/matrixone/blob/146bf9db9d98b731588d9bde3b06333be1a4f3af/test/distributed/cases/load_data/load_data.sql#L184

```sql

create table t7(
col1 int,
col2 int,
col3 int
);
load data infile '$resources/load_data/auto_increment_2.csv' into table t7 parallel 'true';
select * from t7 order by col1;
drop table t7;
```

### Additional information

found in this [pr](https://github.com/matrixorigin/matrixone/pull/10074) , all but pass except from this [one](https://github.com/matrixorigin/matrixone/actions/runs/5277308071/jobs/9545173131?pr=10074).

**Comment by sukki37** [comment]
could you take the first action on this issue?

**Comment by jensenojs** [comment]
sure

**Comment by jensenojs** [comment]
Since the log information is too little, I compared the logs of these two sql, t7 and t8，there should have similar log

```sql
// t7
create table t7(
col1 int,
col2 int,
col3 int
);
load data infile '$resources/load_data/auto_increment_2.csv' into table t7 parallel 'true';
select * from t7 order by col1;
drop table t7;

// t8
create table t8(a int, b int);
load data infile '$resources/load_data/auto_increment_20.csv' into table t7 set col2=nullif(col2, '1');
```

for log of cn-0, has some strange error from  cn-backend that other sql have not.
<img width="1956" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/2c8c746a-b22c-4691-86f5-6f5db773b9fa">

for cn-1.log, it shows no such table load_data.t7 in preinsert
<img width="1041" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/e5c80380-4c1c-4f87-b3aa-d1b489bf1871">

Will continue to investigate the problem

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
目前类似的issue已经有#10220，#10170 了

以这个场景为例，cn0上做了create table 和load。但cn1上还没有消费到create table的logtail，而load的任务已经派发到cn1上了，所以cn1就报错了。

根本原因是多个cn之间没法保证外部一致性。

（实际上行不通的）权宜之计是把create table 和  insert / load 做在一个事务里面，（#10220 和本issue都是load时出现的问题，#10170 是insert出的问题）这样

行不通的原因是auto_increment现在是在单独的事务里面的，所以用begin ... commit包起来也没用。可能得请潇哥看一下咋办。@domingozhang

**Comment by domingozhang** [comment]
请@zhangxu19830126 帮忙看一下，有没有解决思路

**Comment by jensenojs** [comment]
no press

**Comment by jensenojs** [comment]
10078是一个session，不存在外部一致性。
