### ISSUE TITLE
[Bug]: partition by hash(ceil(decimal)) reported type DECIMAL64 not allowed in partition clause

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10077]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1a2c60ebfcdc4519a33886ba8054824bddbb9da6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
create table p_hash_table_08(col1 tinyint,col2 varchar(30),col3 decimal(6,3))partition by hash(ceil(col3)) partitions 2;
SQL syntax error: type DECIMAL64 not allowed in partition clause

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/59e081c2-274c-4c2d-860d-331b6f131e6f)

### Steps to Reproduce

```Markdown
create table p_hash_table_08(col1 tinyint,col2 varchar(30),col3 decimal(6,3))partition by hash(ceil(col3)) partitions 2;
```

**Comment by heni02** [comment]
@qingxinhome plz confirm this issue

**Comment by qingxinhome** [comment]
The issue has been resolved and is now undergoing testing. Please confirm @heni02 @daviszhen

**Comment by heni02** [comment]
commit id: 6c14bc30b09ef54c53f0fb7e992fb1343ecd0c76
create table p_hash_table_08(col1 tinyint,col2 varchar(30),col3 decimal(6,3))partition by hash(ceil(col3)) partitions 2;
Field 'ceil(col3)' is of a not allowed type for this type of partitioning
@qingxinhome plz confirm this behavior
