### ISSUE TITLE
[Bug]: logservice cannot start after upgrade

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#10089]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1304" alt="企业微信截图_2a1a1bf1-d423-463a-a025-534ea0795d36" src="https://github.com/matrixorigin/matrixone/assets/18366608/9108ea5c-aa9d-4f68-aa6f-b1dbfa526b12">

[log0.log](https://github.com/matrixorigin/matrixone/files/11765717/log0.log)

[log1.log](https://github.com/matrixorigin/matrixone/files/11765718/log1.log)

[log2.log](https://github.com/matrixorigin/matrixone/files/11765719/log2.log)

### Expected Behavior

logservice could start after upgrade

**Comment by DanielZhangQD** [comment]
Upgrade from `nightly-9de3c465` to `nightly-9207b269`

**Comment by DanielZhangQD** [comment]
Hit again when failover occurs:
```
test1-dn-0          1/1     Running            2 (4h58m ago)    4h59m
test1-log-1         0/1     CrashLoopBackOff   57 (4m ago)      4h59m
test1-log-2         0/1     CrashLoopBackOff   57 (2m14s ago)   4h59m
test1-log-3         1/1     Running            1 (36m ago)      159m
test1-tp-cn-njw96   1/1     Running            0                12h
```

```
{"level":"ERROR","time":"2023/06/20 01:06:09.036806 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:510","msg":"read loop stopped","remote":"test1-log-discovery.default.svc:32001","backend-id":"bb83d572-4c7b-4cab-8e16-594e3f01dd55"}
panic: inconsistent replicas

goroutine 330 [running]:
github.com/matrixorigin/matrixone/pkg/pb/logservice.(*LogState).updateShards(0xc000e30210, {{0xc015344f90, 0x24}, {0xc015344fc0, 0x30}, {0xc015344ff0, 0x30}, {0xc015345020, 0x30}, {0xc0153462a0, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/pb/logservice/logservice.go:168 +0x2b0
github.com/matrixorigin/matrixone/pkg/pb/logservice.(*LogState).Update(0xc000e30210, {{0xc015344f90, 0x24}, {0xc015344fc0, 0x30}, {0xc015344ff0, 0x30}, {0xc015345020, 0x30}, {0xc0153462a0, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/pb/logservice/logservice.go:136 +0x2c5
github.com/matrixorigin/matrixone/pkg/hakeeper.(*stateMachine).handleLogHeartbeat(0xc000e30180, {0xc01421f001?, 0x0?, 0x0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/hakeeper/rsm.go:338 +0xe5
github.com/matrixorigin/matrixone/pkg/hakeeper.(*stateMachine).Update(0xc000e30180, {0x651c88, {0xc01421f001, 0x1f3, 0x1ff}, {0x0, {0x0, 0x0, 0x0}}})
	/go/src/github.com/matrixorigin/matrixone/pkg/hakeeper/rsm.go:522 +0xe5
github.com/lni/dragonboat/v4/internal/rsm.(*InMemStateMachine).Update(0xc0014634f0?, {0xc000170500?, 0x1, 0x1})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/rsm/adapter.go:79 +0xbd
github.com/lni/dragonboat/v4/internal/rsm.(*NativeSM).Update(0xc001335040, {0x651c88, {0xc01421f001, 0x1f3, 0x1ff}, {0x0, {0x0, 0x0, 0x0}}})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/rsm/managed.go:184 +0xc2
github.com/lni/dragonboat/v4/internal/rsm.(*StateMachine).update(0xc000532100, {0x16, 0x651c88, 0x2, 0x203078b21582c0c6, 0xfd31b76dff792c03, 0x0, 0x0, {0xc01421f000, 0x1f4, ...}})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230426084722-d189534f8004/internal/rsm/statemachine.go:1094 +0x378
github.com/lni/dragonboat/v4/internal/rsm.(*StateMachine).handleEntry(0xc000532100, {0x16, 0x651c88, 0x2, 0x203078b21582c0c6, 0xfd31b76dff792c03, 0x0, 0x0, {0xc01421f000, 0x1f4, ...}}, ...)
```

**Comment by aylei** [comment]
same issue encountered without upgrading, simply rolling-update logset Pods with the same image may reproduce this issue:

```
diff -Naupr log-0.yaml log-1.yaml
--- log-0.yaml	2023-06-20 14:58:21
+++ log-1.yaml	2023-06-20 14:58:48
@@ -105,19 +105,19 @@ data:
           name: gossip
         - configMap:
             defaultMode: 420
-            name: default-log-config-7f43152
+            name: default-log-config-e0d183f
           name: config
```

The rolling update simply changes the configmap, with no significant config change.

And the log service pod crashes after rolling-update:


```
kg po -n freetier-02
NAME                            READY   STATUS             RESTARTS         AGE
default-cn-495n2                0/1     CrashLoopBackOff   10 (86s ago)     33m
default-cn-gdp66                0/1     CrashLoopBackOff   10 (79s ago)     33m
default-dn-0                    1/1     Running            3 (28m ago)      33m
default-log-0                   0/1     CrashLoopBackOff   10 (2m52s ago)   32m
default-log-1                   0/1     CrashLoopBackOff   10 (4m2s ago)    32m
default-log-2                   0/1     CrashLoopBackOff   10 (3m19s ago)   33m
```

log:
[log.txt](https://github.com/matrixorigin/matrixone/files/11796958/log.txt)

@volgariver6 PTAL

**Comment by aylei** [comment]
> same issue encountered without upgrading, simply rolling-update logset Pods with the same image may reproduce this issue:
> 
> ```
> diff -Naupr log-0.yaml log-1.yaml
> --- log-0.yaml	2023-06-20 14:58:21
> +++ log-1.yaml	2023-06-20 14:58:48
> @@ -105,19 +105,19 @@ data:
>            name: gossip
>          - configMap:
>              defaultMode: 420
> -            name: default-log-config-7f43152
> +            name: default-log-config-e0d183f
>            name: config
> ```
> 
> The rolling update simply changes the configmap, with no significant config change.
> 
> And the log service pod crashes after rolling-update:
> 
> ```
> kg po -n freetier-02
> NAME                            READY   STATUS             RESTARTS         AGE
> default-cn-495n2                0/1     CrashLoopBackOff   10 (86s ago)     33m
> default-cn-gdp66                0/1     CrashLoopBackOff   10 (79s ago)     33m
> default-dn-0                    1/1     Running            3 (28m ago)      33m
> default-log-0                   0/1     CrashLoopBackOff   10 (2m52s ago)   32m
> default-log-1                   0/1     CrashLoopBackOff   10 (4m2s ago)    32m
> default-log-2                   0/1     CrashLoopBackOff   10 (3m19s ago)   33m
> ```
> 
> log: [log.txt](https://github.com/matrixorigin/matrixone/files/11796958/log.txt)
> 
> @volgariver6 PTAL

```
data-dir = "/var/lib/matrixone/data"
service-type = "LOG"

[[fileservice]]
backend = "DISK"
data-dir = "/var/lib/matrixone/data"
name = "LOCAL"

[[fileservice]]
backend = "S3"
name = "S3"

[fileservice.s3]
bucket = "mocloud-dev-ap-southeast-1"
endpoint = "s3.ap-southeast-1.amazonaws.com"
key-prefix = "freetier-02-85dX/data"

[[fileservice]]
backend = "S3"
name = "ETL"

[fileservice.s3]
bucket = "mocloud-dev-ap-southeast-1"
endpoint = "s3.ap-southeast-1.amazonaws.com"
key-prefix = "freetier-02-85dX/etl"

[hakeeper-client]
discovery-address = "default-log-discovery.freetier-02.svc:32001"

[logservice]

gossip-seed-addresses = ["default-log-0.default-log-headless.freetier-02.svc:32002", "default-log-1.default-log-headless.freetier-02.svc:32002", "default-log-2.default-log-headless.freetier-02.svc:32002"]
uuid = "00000000-0000-0000-0000-000000000000"
raft-address = "default-log-0.default-log-headless.freetier-02.svc:32000"
logservice-address = "default-log-0.default-log-headless.freetier-02.svc:32001"
gossip-address = "10.0.130.147:32002"
gossip-address-v2 = "default-log-0.default-log-headless.freetier-02.svc:32002"
deployment-id = 7316764745592933963
logservice-listen-address = "0.0.0.0:32001"


[logservice.BootstrapConfig]
bootstrap-cluster = true
init-hakeeper-members = ["131072:00000000-0000-0000-0000-000000000000", "131073:00000000-0000-0000-0000-000000000001", "131074:00000000-0000-0000-0000-000000000002"]
num-of-dn-shards = 1
num-of-log-shard-replicas = 3
num-of-log-shards = 1
```

@gouhongshen config-file of logservice

**Comment by gouhongshen** [comment]
according to the logs, `inconsistent replicas err` all happened at the last phase of replaying logs (in the middle of replaying the final batch log）.

**Comment by volgariver6** [comment]
很难复现，等云环境再复现一次看panic详细信息

**Comment by volgariver6** [comment]
本地无法复现，没有进展

**Comment by volgariver6** [comment]
set to s1 because cannot repro for long time. If it occurs again, set it back to s0.

**Comment by aylei** [comment]
[Uploading log.txt…]()

@volgariver6 reproduced in eks env

**Comment by aylei** [comment]
```
{"level":"INFO","time":"2023/07/08 03:04:23.073918 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:291","msg":"adding schedule command to hakeeper rsm: D/CreateTask 363233"}
panic: inconsistent replicas, recorded: {ShardID:1 Replicas:map[262145:00000000-0000-0000-0000-000000000002 262323:00000000-0000-0000-0000-000000000000 285504:00000000-0000-0000-0000-000000000001] Epoch:322623 LeaderID:262145 Term:7 XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}, incoming: {LogShardInfo:{ShardID:1 Replicas:map[262145:00000000-0000-0000-0000-000000000002 262323:00000000-0000-0000-0000-000000000000] Epoch:322623 LeaderID:262145 Term:7 XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0} ReplicaID:285504 XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

All logservice pods report the log-1 rpelica is missed in the incoming replicas

**Comment by aylei** [comment]
The data of logservices are collected for later analysis

**Comment by volgariver6** [comment]
change to s0 to fix as soon as possible

**Comment by gouhongshen** [comment]
从日志来看，副本 285504 经历了 `L/Add` 和 `L/Start` 两个步骤。根据 HAKeeper 的逻辑，一旦向一个新加入的副本发出 `Start Replica` 命令，意味着该副本已经成功加入到了集群中，即 `ConfigChange` 已经被 applied 了，并且已经将最新的副本情况通过心跳同步给了 HAKeeper。

然而，心跳信息中，这个新副本 285504 的 `membership` 却没有包含自己。

初始时，新副本的 `membership` 为空，只会在收到 leader 发送的 `InstallSnapshotMsg` 时完成更新，所以猜测 leader 发送 `InstallSnapshotMsg` 时，它的 `membership` 信息已经被错误地覆盖了。

这种情况是可能的。 log service 关闭了 dragonboat  内部的 snapshot 机制，而是通过额外的 goroutine 完成 snapshot 的导入导出。

向 dragonboat 导入之前创建的 snapshot 时，会先通过 `linearizableRead` 读出最新的 `membership`，更新 snapshot 之后才会导入该快照。

但是，可能存在这样一种情况。假设 leader 的 entries 列表如下：
`x, x, x, x, configChange, x, readIndex, x, x, ...` 

向 leader 导入 snapshot 时，通过线性读出了旧的 `membership`，而随后，`configChange` 被应用，并通过心跳同步给 HAKeeper，再然后，导入 snapshot，覆盖了新的 `membership`，最后将该 `membership` 通过 `InstallSnapshotMsg` 复制给了副本 285504.

这样，就会在 HAKeeper 处产生不一致的错误。

**Comment by volgariver6** [comment]
> 从日志来看，副本 285504 经历了 `L/Add` 和 `L/Start` 两个步骤。根据 HAKeeper 的逻辑，一旦向一个新加入的副本发出 `Start Replica` 命令，意味着该副本已经成功加入到了集群中，即 `ConfigChange` 已经被 applied 了，并且已经将最新的副本情况通过心跳同步给了 HAKeeper。
> 
> 然而，心跳信息中，这个新副本 285504 的 `membership` 却没有包含自己。
> 
> 初始时，新副本的 `membership` 为空，只会在收到 leader 发送的 `InstallSnapshotMsg` 时完成更新，所以猜测 leader 发送 `InstallSnapshotMsg` 时，它的 `membership` 信息已经被错误地覆盖了。
> 
> 这种情况是可能的。 log service 关闭了 dragonboat 内部的 snapshot 机制，而是通过额外的 goroutine 完成 snapshot 的导入导出。
> 
> 向 dragonboat 导入之前创建的 snapshot 时，会先通过 `linearizableRead` 读出最新的 `membership`，更新 snapshot 之后才会导入该快照。
> 
> 但是，可能存在这样一种情况。假设 leader 的 entries 列表如下： `x, x, x, x, configChange, x, readIndex, x, x, ...`
> 
> 向 leader 导入 snapshot 时，通过线性读出了旧的 `membership`，而随后，`configChange` 被应用，并通过心跳同步给 HAKeeper，再然后，导入 snapshot，覆盖了新的 `membership`，最后将该 `membership` 通过 `InstallSnapshotMsg` 复制给了副本 285504.
> 
> 这样，就会在 HAKeeper 处产生不一致的错误。
目前HAKeeper是没有snapshot的，所以应该不是这里的问题。

**Comment by volgariver6** [comment]
> 从日志来看，副本 285504 经历了 `L/Add` 和 `L/Start` 两个步骤。根据 HAKeeper 的逻辑，一旦向一个新加入的副本发出 `Start Replica` 命令，意味着该副本已经成功加入到了集群中，即 `ConfigChange` 已经被 applied 了，并且已经将最新的副本情况通过心跳同步给了 HAKeeper。
> 
> 然而，心跳信息中，这个新副本 285504 的 `membership` 却没有包含自己。
> 
> 初始时，新副本的 `membership` 为空，只会在收到 leader 发送的 `InstallSnapshotMsg` 时完成更新，所以猜测 leader 发送 `InstallSnapshotMsg` 时，它的 `membership` 信息已经被错误地覆盖了。
> 
> 这种情况是可能的。 log service 关闭了 dragonboat 内部的 snapshot 机制，而是通过额外的 goroutine 完成 snapshot 的导入导出。
> 
> 向 dragonboat 导入之前创建的 snapshot 时，会先通过 `linearizableRead` 读出最新的 `membership`，更新 snapshot 之后才会导入该快照。
> 
> 但是，可能存在这样一种情况。假设 leader 的 entries 列表如下： `x, x, x, x, configChange, x, readIndex, x, x, ...`
> 
> 向 leader 导入 snapshot 时，通过线性读出了旧的 `membership`，而随后，`configChange` 被应用，并通过心跳同步给 HAKeeper，再然后，导入 snapshot，覆盖了新的 `membership`，最后将该 `membership` 通过 `InstallSnapshotMsg` 复制给了副本 285504.
> 
> 这样，就会在 HAKeeper 处产生不一致的错误。

目前HAKeeper是没有snapshot的，所以应该不是这里的问题。

**Comment by volgariver6** [comment]
还在分析中

**Comment by volgariver6** [comment]
无法本地复现

**Comment by volgariver6** [comment]
does not happend for long time, close it first.
