### ISSUE TITLE
[Bug]: create temporary table include key partition success

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10081]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1a2c60ebfcdc4519a33886ba8054824bddbb9da6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create temporary table include key partition success, but select partition not exists, should reported not support 
mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/726c5285-fa0d-460d-bb49-45d6dea1acf2)

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/cd725d8f-15df-4a2b-a377-a135a950a4dc)

### Steps to Reproduce

```Markdown
create temporary table p_table_non(col1 int,col2 varchar(25))partition by key(col2)partitions 4;
```

**Comment by heni02** [comment]
@qingxinhome plz confirm this issue

**Comment by qingxinhome** [comment]
Confirmed, the issue is a bug @heni02 @daviszhen

**Comment by qingxinhome** [comment]
The issue has been resolved and is now undergoing testing. Please confirm @heni02 @daviszhen

**Comment by heni02** [comment]
confirm,closed
commit id: 6c14bc30b09ef54c53f0fb7e992fb1343ecd0c76
![image](https://github.com/matrixorigin/matrixone/assets/113406637/9b096845-e84b-4fa9-8aeb-3d9aa941c69b)
