### ISSUE TITLE
[Bug]: hash partition key is year function which not date type, mo not reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10080]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1a2c60ebfcdc4519a33886ba8054824bddbb9da6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/05dd76b2-b318-495c-bdc2-a15730f018e2)

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/130167fe-ea4b-41dc-97a1-6bb916a8c934)

### Steps to Reproduce

```Markdown
create table p_hash_table_03(col1 bigint ,col2 date default '1970-01-01',col3 varchar(30))partition by hash(year(col3)) partitions 8;
```

**Comment by heni02** [comment]
@qingxinhome plz confirm this issue

**Comment by qingxinhome** [comment]
Confirmed, the issue is a bug @heni02 @daviszhen

**Comment by qingxinhome** [comment]
The issue has been resolved and is now undergoing testing. Please confirm @heni02 @daviszhen

**Comment by heni02** [comment]
confirm,closed
commit id:6c14bc30b09ef54c53f0fb7e992fb1343ecd0c76
![image](https://github.com/matrixorigin/matrixone/assets/113406637/07c6b15d-467e-4592-a9ee-6cf79cde27dc)
