### ISSUE TITLE
[Feature Request]: mo-dump supports dumping multiple databases and/or tables

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#10094]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Currently there are some constraints of mo-dump tool,
1. mo-dump only supports exporting the backup of a single database, if you have several databases to backup, you need to manually run mo-dump for several times.
2. -tbl [table name]: Optional parameter. If the parameter is empty, the whole database will be exported. If you want to take the backup specific tables, then you can specify multiple -tbl and table names in the command.
```

### Describe the feature you'd like

mo-dump supports dumping multiple databases and/or tables if it's specified by a user.

### Describe implementation you've considered

1. For databases:
  - Support multiple databases by specifying them in a list, sperated by `,`
  - Support all databases by sepecifiying them using `all`. However, it should be discussed first whether internal databases should also be exported, or only user databases should be exported. @domingozhang  @jianwan0214 
```bash
mo-dump -u dump -p xxx -h 127.0.0.1 -P 6001 -db db1,db2,db3 > /tm/db1-db2-db3.sql
mo-dump -u dump -p xxx -h 127.0.0.1 -P 6001 -db all > /tm/all-dbs.sql
```
2. For tables: 
Support multiple tables when dumping one specific database by specifiying them in only one `-tbl` option, instead of multiple
```bash
mo-dump -u dump -p xxx -h 127.0.0.1 -P 6001 -db db1 -tbl tbl1,tbl2,tbl3 > /tm/all-dbs.sql
```

but not like this, because it will be very annoying to write so many `-tbl` options when dumping multiple tables,
```bash
mo-dump -u dump -p xxx -h 127.0.0.1 -P 6001 -db db1 -tbl tbl1 -tbl tbl2 -tbl tbl3 > /tm/all-dbs.sql
```

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
https://docs.matrixorigin.cn/en/0.7.0/MatrixOne/Develop/export-data/modump/#syntax
```

### Additional information

<img width="818" alt="企业微信截图_35a4bad5-0bce-4524-9e99-cba21ddf193c" src="https://github.com/matrixorigin/matrixone/assets/46433151/2a77e7ac-7bbc-4ba4-9fb7-6c94a54d7f38">

**Comment by aronchanisme** [comment]
Test date: 2023/10/30
Commit id: 
```bash
root@test0:/data/mo/20231030_1050/matrixone# mo_ctl get_cid 
2023-10-30 16:13:26.890 UTC+0800    [INFO]    Try get mo commit id
commit 0175397c3d933aff66b3fa950f85d92fc05cab2c
Author: LiuBo <g.user.lb@gmail.com>
Date:   Mon Oct 30 10:22:47 2023 +0800

    [bug] util: fix a user case in address manager. (#12273)
    
2023-10-30 16:13:26.939 UTC+0800    [INFO]    Get commit id succeeded
```

For modump with multiple tables,

Senario 1. Dump multiple tables with no data, already tested as stated here https://github.com/matrixorigin/matrixone/issues/10091#issuecomment-1784429118

Senario 2. Dump multiple tables with data,

1 Test case 1
```bash
mo_ctl connect
create database dump_tables_test;
use dump_tables_test;
create table t1(id int)
insert into t1 values (1),(2),(3);
select * from t1;
create table t2(name varchar(25));
insert into t2 values ('A'),('B'),('C');
select * from t2;
exit
./mo-dump -h 127.0.0.1 -u dump -p 111 -P 6001 -db dump_tables_test -tbl t1,t2  > /data/mo_backup/20231030_1605/test_1.sql
cat /data/mo_backup/20231030_1605/test_1.sql
mo_ctl sql 'drop database if exists dump_tables_test;'
mo_ctl sql "show databases like '%dump_tables_test%';"
sed -i '1iuse dump_tables_test;' /data/mo_backup/20231030_1605/test_1.sql
sed -i '1icreate database if not exists dump_tables_test;' /data/mo_backup/20231030_1605/test_1.sql
cat /data/mo_backup/20231030_1605/test_1.sql
mo_ctl sql /data/mo_backup/20231030_1605/test_1.sql
mo_ctl sql "show databases like '%dump_tables_test%';show tables in dump_tables_test;select * from dump_tables_test.t1; select * from dump_tables_test.t2;"

```
<img width="847" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/3cee840c-e705-460b-9cbf-dda7033f773b">
<img width="857" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/7b65424b-aa1e-4f58-be7a-c926d363c7b4">
<img width="827" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/56211a11-ad78-4bd6-af7e-82cb66363db2">
<img width="844" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/6deb13bf-88b2-4ad7-9bad-836e585ac1df">



2 Test case 2: table `nation` and `region` in database `tpch_10g`
```bash
./mo-dump -h 127.0.0.1 -u dump -p 111 -P 6001 -db tpch_10g -tbl nation,region  > /data/mo_backup/20231030_1605/test_2.sql
cat /data/mo_backup/20231030_1605/test_2.sql
```
<img width="842" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/c555b9fd-18d7-42c9-8600-2e3ea356b127">
<img width="850" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/9b4477eb-e0bd-41fe-8987-84c9e1cbc5b0">

**Comment by aronchanisme** [comment]
Dump multiple databases with and without data, failed on both scenarios, since only one database is dumped when two are specified.

```bash
./mo-dump -h 127.0.0.1 -P 6001 -p 111 -u dump -db tpch_1g,ssb_1g > xxx.sql
./mo-dump -h 127.0.0.1 -P 6001 -p 111 -u dump -db tpch_1g,ssb_1g --no-data  > xxx.sql
```

commit id:
```bash
root@test0:/data/mo_br_test/mo_dump/mo_dump# mo_ctl get_cid
2023-11-22 15:38:14.898 UTC+0800    [INFO]    Try get mo commit id
commit 19e9f498d322034a0d29fab2a39daedfb8a9ba5c
Author: triump2020 <63033222+triump2020@users.noreply.github.com>
Date:   Mon Nov 20 15:29:14 2023 +0800

    Reuse object stats (#12828)
    
2023-11-22 15:38:14.961 UTC+0800    [INFO]    Get commit id succeeded
```

![企业微信截图_1700638275172](https://github.com/matrixorigin/matrixone/assets/46433151/62fcf44e-575a-4c10-9cdb-811a83924a82)
![企业微信截图_1700638284501](https://github.com/matrixorigin/matrixone/assets/46433151/d355c067-6e01-494e-aee0-f16a6237b6d1)
![企业微信截图_17006385693948](https://github.com/matrixorigin/matrixone/assets/46433151/5417380b-9d5d-4ca1-bb3e-d38e9aeaff70)

**Comment by aronchanisme** [comment]
Create 2 empty database and try dumping them, this is ok though. Something must be wrong. Please kindly help take a look. Thanks. @YANGGMM 
![企业微信截图_17006390724549](https://github.com/matrixorigin/matrixone/assets/46433151/52abd903-0f75-4573-baeb-250a1afc2033)

**Comment by xmh1011** [comment]
> Create 2 empty databases and try dumping them, this is ok though. Something must be wrong. Please kindly help take a look. Thanks. @YANGGMM ![企业微信截图_17006390724549](https://user-images.githubusercontent.com/46433151/284827069-52abd903-0f75-4573-baeb-250a1afc2033.png)

fixed by: https://github.com/matrixorigin/mo_dump/pull/3

**Comment by aronchanisme** [comment]
With data, ok
![企业微信截图_17006455667283](https://github.com/matrixorigin/matrixone/assets/46433151/1c182a0f-8cff-4d48-b2c2-bf631e8cca84)
![企业微信截图_17006456566348](https://github.com/matrixorigin/matrixone/assets/46433151/0d2daa17-2002-46d3-9e04-cc9a35b0bef9)


With no data, ok
![企业微信截图_17006434421166](https://github.com/matrixorigin/matrixone/assets/46433151/72528dd8-a5ee-4490-9d13-b49eefc8fdde)
