### ISSUE TITLE
[Feature Request]: mo-dump supports dumping database and table definitions only without data

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#10091]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Currently mo-dump supports 2 ways of dumping. One is dumping data with ddl and insert statements, and the other is dumping data with ddl and load statements along with csv data files. However mo-dump does not yet support dumping the definitions of database and/or tables only, without any data.
```

### Describe the feature you'd like

mo-dump supports dumping database and table definitions only without data

### Describe implementation you've considered

Support statement like this, with a `--nodata` option which indicates export database/table structure only.
```bash
mo-dump -u dump -p xxx -h 127.0.0.1 -P 6001 -db testdb --no-data > /tm/testdb.sql
mo-dump -u dump -p xxx -h 127.0.0.1 -P 6001 -db testdb --tbl testtable --no-data > /tm/testdb-testtable.sql
```

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
https://docs.matrixorigin.cn/en/0.7.0/MatrixOne/Develop/export-data/modump/#constraints
```

### Additional information

<img width="1153" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/4b003193-2308-4f84-9407-f45397e7e71b">

**Comment by xmh1011** [comment]
What is the data format supposed to be exported? Like `SHOW TABLES` and `SHOW COLUMNS` ?

**Comment by xmh1011** [comment]
I think this issue can be closed now.

**Comment by aronchanisme** [comment]
**1** Test date: 2023/10/30

**2** MO commit id:
```bash
root@test0:/data/mo/20231030_1050/matrixone# mo_ctl get_cid 
2023-10-30 11:04:35.405 UTC+0800    [INFO]    Try get mo commit id
commit 0175397c3d933aff66b3fa950f85d92fc05cab2c
Author: LiuBo <g.user.lb@gmail.com>
Date:   Mon Oct 30 10:22:47 2023 +0800

    [bug] util: fix a user case in address manager. (#12273)
    
2023-10-30 11:04:35.482 UTC+0800    [INFO]    Get commit id succeeded
```
**3** Test process and result: 

**3.1** Test case 1 : tpch_1g

**3.1.1** Step 1. Load tpch 1g data into a newly installed mo with latest commit id
**3.1.2** Step 2. Execute below command to export the whole database with all tables
command:
```bash
mkdir -p /data/mo-backup/20231030_1058
cd /data/mo/20231030_1050/matrixone
./mo-dump  -h 127.0.0.1 -P 6001 -p 111 -u dump  -db tpch_1g --no-data > /data/mo-backup/20231030_1058/tpch_1g_nodata_test.sql
ls -lth /data/mo-backup/20231030_1058/tpch_1g_nodata_test.sql
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test.sql
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test.sql | grep -i 'create table'
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test.sql | grep -i 'create table' | wc -l 
mo_ctl sql 'show tables in tpch_1g;'
```
results:
8 tables are exported with tpch_1g database definition, which meets our expectation.
<img width="1420" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/46173c1b-be88-4d07-9461-d6ff67ba67cd">

**3.1.3** Step 3. Execute below command to export a few table within tpch_1g
command:
```bash
mkdir -p /data/mo-backup/20231030_1058
cd /data/mo/20231030_1050/matrixone
./mo-dump  -h 127.0.0.1 -P 6001 -p 111 -u dump  -db tpch_1g -tbl nation,part,customer --no-data > /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
ls -lth /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql | grep -i 'create table'
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql | grep -i 'create table' | wc -l 
mo_ctl sql 'show tables in tpch_1g;'
```
results:
3 tables are exported with no database definition, which meets our expectation.
<img width="1707" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/09564a3f-c605-4c86-aa3d-08cd51a36efa">
<img width="1709" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/4a9ee944-2a8f-4591-ab80-f5c28a4ac20b">

**3.1.4** Step 4. Restore the database using the backups with no-data
command:
```bash
mo_ctl sql 'drop database tpch_1g;'
mo_ctl sql 'show databases;'
mo_ctl sql /data/mo-backup/20231030_1058/tpch_1g_nodata_test.sql
mo_ctl sql 'show databases;'
mo_ctl sql 'show tables in tpch_1g;'
mo_ctl sql  "select 'nation' as table_name, count(*) from tpch_1g.nation union select 'region' as table_name, count(*) from tpch_1g.region union select 'part' as table_name, count(*) from tpch_1g.part union select 'supplier' as table_name, count(*) from tpch_1g.supplier union select 'partsupp' as table_name, count(*) from tpch_1g.partsupp union select 'customer' as table_name, count(*) from tpch_1g.customer union select 'orders' as table_name, count(*) from tpch_1g.orders union select 'lineitem' as table_name, count(*) from tpch_1g.lineitem;"

results:
`tpch_1g` database is created with all 8 tables in it and no data are loaded into any of these tables, which meets our expectation.
<img width="1717" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/1e0124fb-f658-4623-a4d9-57f8ccc759d5">
<img width="1715" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/ae399ee2-5667-4742-8a5e-1ac14984cf04">
<img width="1708" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/1be68f6f-d5b9-4e90-887a-086df4c633e7">
<img width="1717" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/aaa1b1b3-541c-49a7-b5aa-498572ecea8f">
<img width="1716" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/ccfdb68a-2dd3-409f-a0de-4d1cda250a51">

**3.1.4** Step 4. Restore the tables using the backups with no-data
command:
```bash
# add database definition to the backup files
sed -i '1iuse test;'  /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
sed -i '1icreate database if not exists test;' /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
cat /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
mo_ctl sql 'show databases'
mo_ctl sql /data/mo-backup/20231030_1058/tpch_1g_nodata_test_2.sql
mo_ctl sql 'show databases; show tables in test;'
mo_ctl sql "select 'nation' as table_name, count(*) as count from test.nation union select 'part' as table_name, count(*) as count from test.part union select 'customer' as table_name, count(*) as count from test.customer;"
```

result:
<img width="1714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/83a6d807-b4f5-45f6-9ca8-0060b650f291">
<img width="1712" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/f027cb74-eec8-4790-8e7f-bcb45fe37887">
<img width="1717" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/f36e10cd-7acf-4adf-a8de-c613c176d802">
<img width="1724" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/bb779671-a814-4973-a490-9e29b6e83aa1">

3 tables `nation`, `part` and `customer` are created in `test` database with no data, which meets our expectation.

**3.2 ** Test case 2: create some sample data
Steps are similar, with data defined as below, which can be used as bvt case

**3.2.1** prepare data
```sql
-- test_data.sql
create database if not exists `modump_nodata_test`;
use `modump_nodata_test`;
create table `t1` (id int);
insert into `t1` values (1),(2),(3);
select * from `t1`;
create table `t2` (name varchar(10));
insert into `t2` values ('A'),('B'),('C');
select * from `t2`;
```

mo_ctl sql 'test_data.sql'

**3.2.2** backup test:
```bash
BK_PATH=/data/mo-backup/20231030_1058
MO_PATH=/data/mo/20231030_1050/matrixone
cd ${MO_PATH}
./mo-dump -h 127.0.0.1 -P 6001 -u dump -p 111 -db modump_nodata_test --no-data > ${BK_PATH}/test_1.sql
./mo-dump -h 127.0.0.1 -P 6001 -u dump -p 111 -db modump_nodata_test --tbl t1,t2 --no-data > ${BK_PATH}/test_2.sql
cat ${BK_PATH}/test_1.sql
cat ${BK_PATH}/test_2.sql
```

3.2.3 restore test
```bash
mo_ctl sql 'drop database if exists `modump_nodata_test`;'
mo_ctl sql 'show databases;'
mo_ctl sql "${BK_PATH}/test_1.sql"
mo_ctl sql "show databases; show tables in modump_nodata_test; select 't1' as table_name, count(*) from modump_nodata_test.t1 union select 't2' as table_name, count(*) from modump_nodata_test.t2;"


mo_ctl sql 'show databases;'
sed -i '1iuse modump_nodata_test_2;'  ${BK_PATH}/test_2.sql
sed -i '1icreate database if not exists modump_nodata_test_2;' ${BK_PATH}/test_2.sql
cat ${BK_PATH}/test_2.sql
mo_ctl sql 'show databases;'
mo_ctl sql "${BK_PATH}/test_2.sql"
mo_ctl sql "show databases; show tables in modump_nodata_test; select 't1' as table_name, count(*) from modump_nodata_test.t1 union select 't2' as table_name, count(*) from modump_nodata_test.t2;"
```

Results: the result meets our expectation
<img width="1714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/2bb307a6-4aaa-482e-b1b1-ac5b264f2d0c">
<img width="1712" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/f5129abe-e390-465e-bd52-8830e610649b">
<img width="1717" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/6bda3f78-7616-44c9-9a34-3c2ce868d68d">
<img width="1713" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/98f3a9cc-abbe-4a96-ba65-b722679f1c73">
<img width="1720" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/721119be-c7ba-4c46-a741-f5861f222ad8">
<img width="1717" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/c1f3e972-6c3d-46df-974b-33dd6a7786e3">
<img width="1715" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/2d48c80c-cee2-4fdc-b4d0-af3010105479">
<img width="1714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/cf092e34-ddc3-4655-82dc-3f358f9c8030">
<img width="1713" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/d41598a6-a49f-4ed2-9da1-687e665ba754">
<img width="1721" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/f3cb41b6-0a21-417b-a992-5a685b2427f0">

**Comment by aronchanisme** [comment]
PS: Since mo-tested does not yet support executing external commands like mo-dump but not sql statement , bvt case is not added as of now. Will cover the test case in MO release test workflow in the future.
https://github.com/matrixorigin/mo-nightly-regression/actions/workflows/mo-release-test-standalone.yml
