### ISSUE TITLE
[Bug]: cannot replay with checkpoint after altering table

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10118]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

It cannot replay with checkpoint after altering table.

**Comment by aptend** [comment]
writing unit test for this case

**Comment by aptend** [comment]
fix pr merged
