### ISSUE TITLE
[Subtask]: discuss agg stmt's Running Record

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#10120]
### Parent Issue

#8196 

### Detail of Subtask

> as difinded in [【企微文档】【PRD】 查询历史合并](https://doc.weixin.qq.com/doc/w3_AZUAugYIAOcKdTPxcOmSoSBADCVSM?scode=AJsA6gc3AA8LVUkmrJAZUAugYIAOc)
> let's discuss `agg stmt record` and `Running Record` relationship.
> - _Originally posted by @xzxiong in https://github.com/matrixorigin/matrixone/pull/10061#pullrequestreview-1485371851_

first things first: what sql should be aggregated ?
-  it should be DML and DQL with short execution time, they leads to high QPS.

secondly, how to deal with those aggregated stmts' Running entities.
- it should be skip with simple rule, like agg time threshold.

**Comment by gavinyue** [comment]
Not working on this yet.  Still work on the aggr

**Comment by gavinyue** [comment]
Pending.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Still pending

**Comment by gavinyue** [comment]
Pending.

**Comment by gavinyue** [comment]
Discussed yesterday

**Comment by gavinyue** [comment]
Discussed last week.  Have not scheduled the work.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
这个之前讨论过了，准备assign 回给author

**Comment by xzxiong** [comment]
stale situation
