### ISSUE TITLE
[Bug]: sometimes cn and dn will disconnnect and lead some queries error  in sysbench oltp update/delete test on eks

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10138]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-70cd870
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 16G
- OS type:
- Others:
  DISKCACHE: 16C 64G
  MEMCACHE: 12G
```

### Actual Behavior

During sysbench oltp update/delete test on daily regression on eks, there are always some errors, like:
<img width="1422" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6be591b1-35de-498a-8bec-ab7cc03570f5">

the mo log can be get in loki, and namespace is : mo-nightly-regression

### Expected Behavior

there should be no errors during sysbench oltp test.

### Steps to Reproduce

```Markdown
1. run a mo cluster on eks with 3*cn using the same config
2. run sysbench oltp update(10 tables, 100000 datas per tables, and 100 terminals ) test for serval times.
```

**Comment by m-schen** [comment]
这个需要加日志确定具体问题，今天还没搞。

**Comment by aressu1985** [comment]
repro in these job link:
https://github.com/matrixorigin/matrixone/actions/runs/5387225346/jobs/9778527194
<img width="1694" alt="企业微信截图_3c399132-7cc3-412b-b4e2-7c0818a201a3" src="https://github.com/matrixorigin/matrixone/assets/47846308/f6a4a78e-aa8c-424d-a3cf-42c8abab3b53">


https://github.com/matrixorigin/matrixone/actions/runs/5387454165/jobs/9779010754
{"level":"ERROR","time":"2023/06/27 09:22:39.991843 +0000","caller":"disttae/txn_database.go:161","msg":"error: SQL parser error: table \"bmsql_history\" does not exist","span":{"trace_id":"29a915e4-14cc-11ee-8ad9-6aa61272d15d","kind":"statement"}}

**Comment by aressu1985** [comment]
repro in job:
https://github.com/matrixorigin/matrixone/actions/runs/5398336184/jobs/9804216043

**Comment by m-schen** [comment]
经确认，确实存在消费端的buffer占满导致链接断开的问题。
目前暂时加大了buffer的长度，从256个log tail提高到了8192个log tail, 当超过90%时会开始打日志记录。
（限制了日志次数，当超过了90%后，下次打日志最少需要达到90%+1）

**Comment by m-schen** [comment]
明天确认一下最近是否还有出现该问题。

**Comment by m-schen** [comment]
目前存在消费buffer没有达到阈值，但是依旧发生了流断开（dn无法写入，但cn的接收数据端并没有卡死，暂时无法确定是否是当前正在消费的logtail时间过长导致）。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/pull/10536
该pr合入后可能已经解决了该问题。

**Comment by m-schen** [comment]
@aressu1985 我先转回去啦。如果10536解决了这个问题的话，就是rpc使用的上下文没有及时关闭导致协程数太多，消费协程的调度时间增长，间接导致消费速度变慢，最后发生重连。

**Comment by aressu1985** [comment]
tracking

**Comment by aressu1985** [comment]
fixed
