### ISSUE TITLE
[Enhancement]: promote ut coverage for added functions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10139]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
db54baed6034602aa0d69d10ec9df82d07a05638
```

### Why is this needed ?

newly added functions  need ut

### Additional information

promote ut coverage to at least 50%.

isRoleGrantedToUserWGO
checkRoleWhetherTableOwner
checkRoleWhetherDatabaseOwner
getSqlForCheckRoleHasPrivilegeWGODependsOnPrivType
doAlterDatabaseConfig
doAlterAccountConfig
insertRecordToMoMysqlCompatibilityMode
deleteRecordToMoMysqlCompatbilityMode
GetVersionCompatibility

**Comment by YANGGMM** [comment]
have finished it, plz confirm

**Comment by sukki37** [comment]
For the commitid fca43b6d485786e5fc22644f959e490e646de87c, the unit test coverage for pkg/frontend is 53%, meeting the requirements of this issue.
