### ISSUE TITLE
[Bug]: ci failed: select from statement_info error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10159]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):efae85594cf735284f2c0ee997c68ba873d30462
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
job: https://github.com/matrixorigin/matrixone/actions/runs/5322198054
1. select statement, result_count from statement_info where account="bvt_result_count" and statement not like '%mo_ctl%' and length(trim(statement)) > 0 and status != 'Running' order by request_at desc limit 70;
2. select statement,query_type,sql_source_type from  system.statement_info where account="bvt_query_type" and sql_source_type="external_sql" and status != "Running" and statement not like '%mo_ctl%' order by request_at desc limit 112;
![image](https://github.com/matrixorigin/matrixone/assets/113406637/be6bee78-59be-403b-aa49-bb0c6eb0148a)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/a22bc5ce-cc83-422d-8cf1-3f58ae57cfdd)

### Steps to Reproduce

```Markdown

```

**Comment by xzxiong** [comment]
@gavinyue https://github.com/matrixorigin/matrixone/pull/10061 has been revert by https://github.com/matrixorigin/matrixone/pull/10157.
pls fix this bvt together

**Comment by gavinyue** [comment]
Pending for the pr merge.

**Comment by gavinyue** [comment]
Pending for the stmt_aggr pr merge. Stuck on dn oom

**Comment by gavinyue** [comment]
This should be fixed. Please check. @heni02

**Comment by gouhongshen** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9286182986/job/25552368825?pr=16482

**Comment by gouhongshen** [comment]
pr: 
https://github.com/matrixorigin/matrixone/pull/16474
