### ISSUE TITLE
[Bug]: The open/suspend field in the create account should take effect. 

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#10166]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The standard syntax for the 【create account】command should be as follows:
```
> CREATE ACCOUNT [IF NOT EXISTS]
account auth_option
[COMMENT 'comment_string']

auth_option: {
    ADMIN_NAME [=] 'admin_name'
    IDENTIFIED BY 'auth_string'
}

status_option: {
OPEN
| SUSPEND
}
```

Please note that the OPEN/SUSPEND status option must be enacted for the command to take effect.

mysql> create account tenant_test admin_name = 'admin' identified by '111' comment '345';
Query OK, 0 rows affected (0.42 sec)

mysql> show accounts;
+--------------+------------+---------------------+--------+----------------+----------+-------------+-----------+----------+----------------+
| account_name | admin_name | created             | status | suspended_time | db_count | table_count | row_count | size     | comment        |
+--------------+------------+---------------------+--------+----------------+----------+-------------+-----------+----------+----------------+
| tenant_test  | admin      | 2023-06-19 03:38:44 | open   | NULL           |        5 |          38 |       880 |    0.036 | 345            |
| sys          | root       | 2023-06-09 04:00:00 | open   | NULL           |       12 |         219 |  18710483 | 1928.759 | system account |
| tenant1      | admin      | 2023-06-19 02:08:25 | open   | NULL           |        5 |          38 |       880 |    0.013 | tenant1        |
+--------------+------------+---------------------+--------+----------------+----------+-------------+-----------+----------+----------------+
3 rows in set (0.09 sec)

mysql> create account tenant2 admin_name = 'admin' identified by '111' close comment '121';
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 69 near " close comment '121'";
mysql> create account tenant3 admin_name = 'admin' identified by '111' suspend comment 'XXX';
Query OK, 0 rows affected (0.40 sec)

mysql> desc accounts;
ERROR 1146 (HY000): no such table .accounts
mysql> show accounts;
+--------------+------------+---------------------+--------+----------------+----------+-------------+-----------+----------+----------------+
| account_name | admin_name | created             | status | suspended_time | db_count | table_count | row_count | size     | comment        |
+--------------+------------+---------------------+--------+----------------+----------+-------------+-----------+----------+----------------+
| tenant_test  | admin      | 2023-06-19 03:38:44 | open   | NULL           |        5 |          38 |       880 |    0.036 | 345            |
| tenant3      | admin      | 2023-06-19 03:40:46 | open   | NULL           |        5 |          38 |       880 |    0.036 | XXX            |
| sys          | root       | 2023-06-09 04:00:00 | open   | NULL           |       12 |         219 |  18712196 | 1928.384 | system account |
| tenant1      | admin      | 2023-06-19 02:08:25 | open   | NULL           |        5 |          38 |       880 |    0.013 | tenant1        |
+--------------+------------+---------------------+--------+----------------+----------+-------------+-----------+----------+----------------+
4 rows in set (0.04 sec)

**Comment by YANGGMM** [comment]
have fixed it

**Comment by sukki37** [comment]
Verified in https://github.com/matrixorigin/matrixone/commit/fca43b6d485786e5fc22644f959e490e646de87c.The issue has been resolved. Closing this issue now. If anyone encounters any related problems, please reopen or comment.
