### ISSUE TITLE
[Enhancement]: Provide a funciton to delete log tables

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10173]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
function_name: delete_log(table_list, date)
table_list: names of target tables
date: the target date of records. all records before thist date will be deleted.
return value: deleted records in this action

select delete_log('raw_log,statement_info', '2023-06-21');
Then all records before 2023-06-21 will be purged in system.raw_log

The all records in this table will be purged at once.
```

### Why is this needed ?

Currently, the tables under system cannot be truncated or delted by SQL because of privielge control.
User needs a function to delete log tables manually.

**Comment by xzxiong** [comment]
implement function `mo_purge_log`
> PS: only `sys` account can call it.
- sys account
```
mysql> select date(collecttime), count(1) from system_metrics.metric group by date(collecttime);
+-------------------+----------+
| date(collecttime) | count(1) |
+-------------------+----------+
| 2023-06-29        |     4583 |
| 2023-06-27        |    25520 |
+-------------------+----------+
2 rows in set (0.02 sec)

mysql> select mo_purge_log('rawlog,statement_info,metric', '2023-06-28');
+--------------------------------------------------------+
| mo_purge_log(rawlog,statement_info,metric, 2023-06-28) |
+--------------------------------------------------------+
|                                                      0 |
+--------------------------------------------------------+
1 row in set (0.17 sec)

mysql> select date(collecttime), count(1) from system_metrics.metric group by date(collecttime);
+-------------------+----------+
| date(collecttime) | count(1) |
+-------------------+----------+
| 2023-06-29        |     4583 |
+-------------------+----------+
1 row in set (0.03 sec)
```

- generanl account
```
mysql> select mo_purge_log('statement_info', '2023-06-28');
ERROR 20105 (HY000): not supported: only support sys account
```

**Comment by xzxiong** [comment]
implement buildin  function `purge_log(table_name, date)` @domingozhang ptal

**Comment by heni02** [comment]
test done
statement_info table:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/37230cfe-99c5-4ba3-b973-8a5c99564cd1)
rawlog table:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/cb90ad31-1e77-4122-92a4-a93e8f0e6e62)
metric table:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c6edd680-8bc2-456d-9938-c51234c2aae7)

non system table:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c5865b62-9e72-4592-9c77-0ea89d72f93b)
