### ISSUE TITLE
[Bug]: BVT failed: no such table ssb.test_table

### ISSUE THREAD

**Issue by jiangxinmeng1** [matrixorigin/matrixone#10170]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/51114574/50383ed6-664c-48cf-849a-7be74a6db9a5)

https://github.com/matrixorigin/matrixone/actions/runs/5329704110/jobs/9655649577?pr=10168

**Comment by xzxiong** [comment]
@jianwan0214 ptal

**Comment by xzxiong** [comment]
It need repro's env.

the missing table is just created before load. The summary of the CI action is lost, caused by CI has been rerun.

bvt script:
![image](https://github.com/matrixorigin/matrixone/assets/3927687/6b84d0ae-56b2-47d8-8ed5-eb562ca651aa)

**Comment by xzxiong** [comment]
like https://github.com/matrixorigin/matrixone/issues/10078
