### ISSUE TITLE
[Bug]: cn crash during sysbench oltp prepared test on eks with 3*cn 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10183]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): bc3e166
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

<img width="1238" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/dada5212-a41a-47ae-8ba0-fac498bed3d9">

the memory used was in a very high level:
<img width="1379" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ec8bb748-2ef1-4d8f-9cff-e2a3e7feb3ec">

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5347746368

the mo can be get from loki , namespace: mo-nightly-regression

**Comment by XuPeng-SH** [comment]
@nnsgmsone please confirm this issue

**Comment by nnsgmsone** [comment]
pr #10203合入后，prepare的内存开销已经很低了，不过在开启trace的情况下，trace的一些流程内存占用还是很大，需要等gavin的pr合入后，应该就没问题了

**Comment by nnsgmsone** [comment]
prepare应该不存在内存问题了 @aressu1985

**Comment by aressu1985** [comment]
fixed
