### ISSUE TITLE
[Bug]: loading data was hung on eks with 3*cn on daily regression(occasional)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10192]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bf23f2a999702b465669249f95a9c4bf8bf37322
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

on daily regression 23 Jun, the loading data was hung.

<img width="1401" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/81f9d161-5044-4e39-86e7-d1493b6d6755">

but when trying reproducing, it did not happen again.

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5347746368/jobs/9699327123

the mo log can be get from loki  by ns: mo-nightly-regression and the time that the loading data was hung.

**Comment by XuPeng-SH** [comment]
@jianwan0214

**Comment by aressu1985** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/5368078768/jobs/9738749085

this merge run has reproed again

**Comment by aressu1985** [comment]
未定位出原因，也没有在复现过，先降级处理

**Comment by daviszhen** [comment]
> repro from job： https://github.com/matrixorigin/matrixone/actions/runs/5441445915/jobs/9895548735

从日志看。是create table 卡住。

<img width="1030" alt="企业微信截图_fa384873-1e0c-43a7-b50d-b187b0b0d088" src="https://github.com/matrixorigin/matrixone/assets/60595215/d335f15e-0f51-4363-aa54-1a77fbdb169e">

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by aressu1985** [comment]
downgrade to s1

**Comment by sukki37** [comment]
This issue has been inactive for a while. To help keep our backlog clear, I'm going to close this. If you feel this is still relevant, please comment or reopen.
