### ISSUE TITLE
[Bug]: cn painc by internal error: panic runtime error: invalid memory address or nil pointer dereference on daily regression on eks with 3*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10193]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bf23f2a999702b465669249f95a9c4bf8bf37322
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

<img width="1402" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e6b5412e-fb2d-4f4a-9b76-df5ee0fd1fb9">

<img width="1396" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d2e5f0e7-91a0-4892-849e-bf65729e4863">

the daily regression action is:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5347746368/jobs/9699327123

the mo log can be get from loki by ns: mo-nightly-regression and the time :
<img width="1241" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/f36cae9e-374b-4ed1-8647-cf4a262a4a5d">

**Comment by triump2020** [comment]
txn.deletedBlocks  may be set to  nil  , when call engine.delTransaction ?   need to reproduce to confirm it.

**Comment by triump2020** [comment]
Maybe the front call txn.rollback  before the pipelines completely finished.

**Comment by triump2020** [comment]
It's hard to repro.

**Comment by cnutshell** [comment]
The log indicates that the panic was caused by nil `tbl.db.txn.deletedBlocks`.
```go
1126 // CN Block Compaction
1127 func (tbl *txnTable) compaction() error {
1128     mp := make(map[int][]int64)
1129     s3writer := &colexec.S3Writer{}
1130     batchNums := 0
1131     name, err := s3writer.GenerateWriter(tbl.db.txn.proc)
1132     if err != nil {
1133         return err
1134     }
1135     var deletedIDs []*types.Blockid
1136     defer func() {
1137         tbl.db.txn.deletedBlocks.removeBlockDeletedInfos(deletedIDs)
1138     }()
1139     tbl.db.txn.deletedBlocks.iter(func(id *types.Blockid, deleteOffsets []int64) bool {
```
<img width="793" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/c4d4589b-648d-4c6e-9879-e52e2b8c81dc">

**Comment by cnutshell** [comment]
- [ ] delete the added log of PR #10193 after issue #10193 resolved

**Comment by cnutshell** [comment]
Investigating mo-service's running log.

**Comment by cnutshell** [comment]
Under commit `bf23f2a999702b465669249f95a9c4bf8bf37322 `, a typical handling for a mysql session would be:
- frontend goroutine [initializes Transaction](https://github.com/matrixorigin/matrixone/blob/6b629ccc708143aca0c014d054ba30ea4e60bb5b/pkg/vm/engine/disttae/engine.go#L350)
- frontend goroutine [forks child goroutines](https://github.com/matrixorigin/matrixone/blob/bf23f2a999702b465669249f95a9c4bf8bf37322/pkg/sql/compile/compile.go#L320)
- frontend goroutine [waits all child goroutines](https://github.com/matrixorigin/matrixone/blob/bf23f2a999702b465669249f95a9c4bf8bf37322/pkg/sql/compile/compile.go#L327)
- frontend goroutine [clean transaction](https://github.com/matrixorigin/matrixone/blob/bf23f2a999702b465669249f95a9c4bf8bf37322/pkg/vm/engine/disttae/engine.go#L518)

The frontend goroutine and child gorouines would access the same `Transaction`. The fact that frontend goroutine would sync with child goroutines could guarantee that it shouldn't be a race condition.

We haven't reproduce this cn panic locally, neither in regression test environment.
And the implementation of [*Compile.Run](https://github.com/matrixorigin/matrixone/blob/ecbb568f8d2437ed7569bd9666f77ad25ea633c5/pkg/sql/compile/compile.go#L312) has changed a lot. I think we should downgrade this issue.

@aressu1985 PTAL

**Comment by cnutshell** [comment]
@aressu1985 would downgrade this issue to a proper level.

**Comment by aressu1985** [comment]
tracking
