### ISSUE TITLE
[Bug]: dn panic by  no codec found for: IOEntry[1055,24] during oltp sysbench update test on  daily regression on eks with 3*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10194]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bf23f2a999702b465669249f95a9c4bf8bf37322
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

on daily regression 23 Jun, the dn crashed during oltp sysbench update test.
<img width="1395" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/9eab528b-38ce-4af8-ad3a-f2b3e23f24c5">

the panic stack is:

panic: no codec found for: IOEntry[1055,24]
goroutine 250 [running]:
github.com/matrixorigin/matrixone/pkg/objectio.GetIOEntryCodec({0x5450?, 0x0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/codecs.go:100 +0x119
github.com/matrixorigin/matrixone/pkg/objectio.Decode({0xc24c33ca00, 0x5450, 0x5500})
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/constructors.go:61 +0x47
github.com/matrixorigin/matrixone/pkg/objectio.ReadBloomFilter({0x2dc4718?, 0xc4d5d76e10?}, {0xc3a2511f20?, 0xc49bf7c828?}, 0x2dde710?, 0x70?, {0x2dde710?, 0xc00016a070?})
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/funcs.go:74 +0x4f
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadAllBF(0xc4289edc40, {0x2dc4718, 0xc4d5d76e10})
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/reader.go:208 +0x95

the regression job is :
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5347746368/jobs/9699327123

the mo log can be get from loki by ns: mo-nightly-regression and the time:
<img width="1225" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b60716ce-4722-455f-9c8f-60ce25418fd4">

**Comment by LeftHandCold** [comment]
It has not been reproduced yet, and the old data of etl has been deleted, and no error is reported.

**Comment by LeftHandCold** [comment]
testing

**Comment by LeftHandCold** [comment]
testing

**Comment by LeftHandCold** [comment]
After deleting the old data, it doesn't  report again, I think it can be closed

**Comment by aressu1985** [comment]
After deleting the old data, it doesn't report again,this can be closed
