### ISSUE TITLE
[Bug]: __mo_index_unique_XXX in information_schema 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10200]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In MO, information_schema.tables get a lot of unique key tables, which is inconsistent with MySQL.

MO:
<img width="1039" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/c583ed4a-f3d9-4519-9b62-e5b33a37485d">

MySQL:
<img width="1024" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/e57d54d2-3bf7-462b-8242-40471ec6b57f">

**Comment by qingxinhome** [comment]
This issue has been resolved, please test and confirm @dengn @daviszhen @domingozhang

**Comment by dengn** [comment]
fixed.
