### ISSUE TITLE
[Bug]: pessimistic rc mode: concurrent 100 update set with non primary key to one table reported some errors

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ad1daec18abe07002111dc28fe6abedc37e178ed
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Concurrent 100 update set with non primary key reported some errors, unexpected in pessimistic rc mode：
<img width="327" alt="企业微信截图_27fe3b15-0255-448c-9d21-8740e9491f7b" src="https://github.com/matrixorigin/matrixone/assets/113406637/59411339-8348-453f-a9c9-9a5652d4230a">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f288f055-21b9-4ad3-922b-836b57513a35)

1.
Statement : UPDATE sbtest1 SET k=k+100 WHERE id = 33200;
ErrorCode : 20619
ErrorMessage : w-w conflict
Expected : false
2.
Statement : UPDATE sbtest1 SET k=k+100 WHERE id = 52120;
ErrorCode : 20628
ErrorMessage : txn need retry in rc mode
Expected : false
3.
Statement : UPDATE sbtest1 SET k=k+100 WHERE id = 84419;
ErrorCode : 1062
ErrorMessage : Duplicate entry '84419' for key 'id'
Expected : false

sql： UPDATE sbtest1 SET k=k+100 WHERE id = ？，id is primary key ,k is non primary key
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c3fc0f55-5ba2-4e28-a379-095f76e70e7d)

report log:
[update_pk_10_100000.txt](https://github.com/matrixorigin/matrixone/files/11858561/update_pk_10_100000.txt)

### Steps to Reproduce
1. git clone mo-load.git
2.alter file:cases/sysbench/simple_insert_10_100000/run.yml
<img width="797" alt="企业微信截图_40c35db9-3ef7-43c2-9edd-67e18871059d" src="https://github.com/matrixorigin/matrixone/assets/113406637/24a8d478-2249-4b98-a711-d9e8cb1903a8">

3.alter file:cases/sysbench/update_pk_10_100000/run.yml
![image](https://github.com/matrixorigin/matrixone/assets/113406637/aee85d8f-7914-4850-a09a-10119bbab0a4)

4.login mo :create database sbtest

5. create table: sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_common.lua --mysql-db=sbtest --tables=1 --table_size=100000 --threads=1 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off prepare
6. ./start.sh -c cases/sysbench/simple_insert_10_100000

7. ./start.sh -c cases/sysbench/update_pk_10_100000

8. error path file: mo-load/reported

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm this issue

**Comment by volgariver6** [comment]
I will check this one.

**Comment by volgariver6** [comment]
还没处理

**Comment by volgariver6** [comment]
正在开发cn缩容的proxy支持

**Comment by volgariver6** [comment]
正在开发cn缩容的proxy支持

**Comment by volgariver6** [comment]
正在开发cn缩容的proxy支持

**Comment by volgariver6** [comment]
这两天验证一下这个问题

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
this issue has been fixed.

**Comment by heni02** [comment]
confirm, the latest version does not have this issue, it may have been resolved ，closed
commit id :1c70e2f03c6577ce75bfe2119b09be7180f55ab5
<img width="1226" alt="企业微信截图_e28f37f0-2601-4098-a2f3-23cb20931fd0" src="https://github.com/matrixorigin/matrixone/assets/113406637/d62b4974-a800-4ca8-b75a-f44ed5cfc1e2">
