### ISSUE TITLE
[Bug]: select count(*) error after loading data on eks with 3*cn(occasional)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10213]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6c14bc3
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

on daily regression on eks JUN 25th, there was a error that result of select count(*) is 0 after loading tpch 100G lineitem data.

<img width="1391" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6695fa31-d0ac-42fa-84e2-3691103f09b9">

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5367083303/jobs/9737259242

the mo log can be get from loki by  ns: mo-nightly-regression and the time nearly at : 2023-06-25 02:17:51 

### Expected Behavior

result of select count(*) should be equal to the real count of table

### Steps to Reproduce

```Markdown
It is very hard to repro.
```

**Comment by xzxiong** [comment]
@jianwan0214 ptal

**Comment by aressu1985** [comment]
repro again in this job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5370645833/jobs/9743466828

<img width="1339" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/402219cd-0302-4179-8314-b2ccf4b32ee0">


log can be get from loki by ns:mo-nightly-regression-20230625

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
@aressu1985 这个问题最近有复现吗?

**Comment by daviszhen** [comment]
与@aressu1985 沟通后，先走给他

**Comment by heni02** [comment]
It no longer exists, confirm closed
commit id:8af14455f059e657890f4249ca63699476bb7f63
date 8.9 eks regression job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5811389178/job/15755992500
<img width="1536" alt="企业微信截图_8ff5f0b3-ea46-47ba-acba-5b8ee95ececb" src="https://github.com/matrixorigin/matrixone/assets/113406637/79fb4ba4-3b59-4e6c-b0d9-3128e3a21d7f">

**Comment by Ariznawlll** [comment]
Load data on eks with 4*cn：
<img width="1026" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/33c90101-bec1-4738-9cff-2cb49474c896">
job url：https://github.com/matrixorigin/mo-auto-test/actions/runs/6032290632/job/16367409706
log：http://abb38738d9c5441738d2e8e3854fe740-1814584411.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-tpch%5C%22,%20pod%3D%5C%22mo-tpch-tp-cn-7qnhb%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by Ariznawlll** [comment]
Load 1T data on eks with 3CN：
<img width="1081" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/24560805-8dbb-467c-9584-57fcf35a5a83">
job：https://github.com/matrixorigin/mo-auto-test/actions/runs/6140373265/job/16660058495

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看
