### ISSUE TITLE
[Bug]: mo report no such table sbtest.sbtest3 when batch inserting sysbench table data on daily regression on eks with 3*cn(ocassional)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10220]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-6c14bc3
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 16C  64G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

when batch inserting sysbench table data on daily regression on eks with 3*cn, sometimes it can not be succeeded, and the error is as following:
{"level":"ERROR","time":"2023/06/25 05:09:29.963467 +0000","caller":"frontend/util.go:525","msg":"query trace status","connection_id":12226,"statement":"INSERT INTO sbtest3 VALUES(1,4849,'57087440723-44690093228-53162317066-15402608062-70691089634-12566508470-62273050079-87125757972-12363164544-97602500902','10505350556-25983677161-35074134021-70259913885-51065354859'),(2,5301,'22449222904-29042133797-63701313343-37655478980-36059629470-60541251116-57383275595-71925608775-71747808183-29228452037','42129654153-37825617647-66309384655-72048732570-94263680498'),(3,8363,'09727539643-15985235481-08471473012-83194827288-33819561209-70143904784-26738422032-73417026526-44153750481-60392564527','43057824045-53463397690-62644700374-81313323081-59070645917'),...........(1021,9584,'26156446520-31875131041-57273412642-11295978515-11768588543-04115889998-47109089564-55932901260-87953700303-67895598238','21446064762-11711775986-22247371159-99564457542-60400611095'),(1022,9450,'94812069440-31013854914-48355352210-72481544034-64075399795-42155847221-17617289748-40957721348-40367663064-65349455345','74314717035-78312723453-09719011765-29476399004-07966013451'),(1023,2080,'51543169648-27288379283-37982541425-24258500027-09186548393-26256070555-83179205686-41532906032-33135939343-81495166267','45743373838-51211394462-51624140015-05096962297-24380495607'),(1024,7357,'48276696648-36111903844-37529854665-18713688624-30397102550-58896327581-39849915398-66744384907-87681612767-78214072978','88771442442-52116283876-45891748501-88298488113-96032552720'),(1025,8408,'28714754894-30649954187-17395837827-54453144938-37288198302-49167618008-38249673290-94567577219-27336742195-26483703591','41075561051-70541741144-66551370890-49273865520-53547102594'),(1026,3132,'78905934760-99280848344-04856128203-24705858444-73813661294-52060868987-13746954967-35922474121-28937479381-36437535526','10750117769-29362716606-12037281460-56615305290...","status":"fail","error":"no such table sbtest.sbtest3","span":{"trace_id":"76db8b71-1316-11ee-92cb-2ab29f3bb8fe","kind":"statement"},"session_info":"connectionId 12226|10.0.108.169:47436|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 68549795|74c6f8f0-1316-11ee-92cb-2ab29f3bb8fe"}

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5367083303/jobs/9738154247

the whole log can be get from loki by ns:mo-nightly-regression and time 2023/06/25 05:09:29

### Expected Behavior

the batch inserting data should be succeeded.

### Steps to Reproduce

```Markdown
It is very hard to repro.
```

**Comment by xzxiong** [comment]
dup as https://github.com/matrixorigin/matrixone/issues/10170

**Comment by jensenojs** [comment]
similar as https://github.com/matrixorigin/matrixone/issues/10078

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
和https://github.com/matrixorigin/matrixone/issues/10078 不像是同一个问题，10078是一个session，不存在外部一致性。

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by aressu1985** [comment]
dup with #11917, this closed
