### ISSUE TITLE
[Bug]: tps of sysbench oltp decreased more than 25% percentage for daily regression on standlone

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ca8f93c34
- Hardware parameters: 16C 256G
- OS type:
- Others:
```

### Actual Behavior

For daily regression on standlone mode on JUN 26th, the tps of sysbench oltp decreased more than 25% percentage.
[sysbench oltp]
INFO:root:The qps for [point_select_10_100000, vuser=100] is not 25.0% lower than the last one.
**INFO:root:This time: qps = 227[46], and datetime = 2023-06-26 00:06:02
INFO:root:Last two times[0]: qps = 29523, and datetime = 2023-06-25 00:22:51
INFO:root:Last two times[1]: qps = 29489, and datetime = 2023-06-24 08:41:53**

INFO:root:The qps for [update_pk_10_100000, vuser=100] is equal to or more than the last one.
INFO:root:This time: qps = 5779, and datetime = 2023-06-26 00:22:16
INFO:root:Last two times[0]: qps = [47], and datetime = 2023-06-25 00:39:12
INFO:root:Last two times[1]: qps = 5474, and datetime = 2023-06-24 08:58:17
INFO:root:The qps for [simple_insert_10_100000, vuser=100] is not 25.0% lower than the last one.
INFO:root:This time: qps = 10885, and datetime = 2023-06-26 00:39:29
INFO:root:Last two times[0]: qps = 10440, and datetime = 2023-06-25 00:58
INFO:root:Last two times[1]: qps = 10918, and datetime = 2023-06-24 09:15:14

**ERROR:root:The qps for [delete_pk_10_100000, vuser=100] is 25.0% lower than the last one.
ERROR:root:This time: qps = 8761, and datetime = 2023-06-26 00:56:00
ERROR:root:Last time: qps = 11868, and datetime = 2023-06-24 09:32:05**

[sysbench oltp prepare]
**ERROR:root:The qps for [point_select_10_100000_prepare, vuser=100] is 25.0% lower than the last one.
ERROR:root:This time: qps = 23166, and datetime = 2023-06-26 03:16:49
ERROR:root:Last time: qps = 31337, and datetime = 2023-06-25 01:39:11**

INFO:root:The qps for [update_pk_10_100000_prepare, vuser=100] is not 25.0% lower than the last one.
INFO:root:This time: qps = 5059, and datetime = 2023-06-26 03:33:16
INFO:root:Last two times[0]: qps = 5009, and datetime = 2023-06-25 01:55:51
INFO:root:Last two times[1]: qps = 5877, and datetime = 2023-06-24 07:41:19

INFO:root:The qps for [simple_insert_10_100000_prepare, vuser=100] is not 25.0% lower than the last one.
INFO:root:This time: qps = 11300, and datetime = 2023-06-26 03:50:02
INFO:root:Last two times[0]: qps = 11431, and datetime = 2023-06-25 02:12:43
INFO:root:Last two times[1]: qps = 11346, and datetime = 2023-06-24 07:58:57

INFO:root:The qps for [delete_pk_10_100000_prepare, vuser=100] is not 25.0% lower than the last one.
**INFO:root:This time: qps = 8789, and datetime = 2023-06-26 04:06:49
INFO:root:Last two times[0]: qps = 11248, and datetime = 2023-06-25 02:29:41
INFO:root:Last two times[1]: qps = 11541, and datetime = 2023-06-24 08:15:38**

INFO:root:The qps for [simple_insert_10_100000_auto, vuser=100] is not 25.0% lower than the last one.
**INFO:root:This time: qps = 9933, and datetime = 2023-06-26 04:23:31
INFO:root:Last two times[0]: qps = 10768, and datetime = 2023-06-26 01:12:22
INFO:root:Last two times[1]: qps = 10055, and datetime = 2023-06-25 02:46:31**

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5370639211/jobs/9742889460

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/issues/10236#issuecomment-1606569881

**Comment by ouyuanning** [comment]
same as #10236

**Comment by aressu1985** [comment]
fixed
