### ISSUE TITLE
[Bug]: Duplicate primary keys can be inserted

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10235]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1725" alt="image" src="https://github.com/matrixorigin/matrixone/assets/2995754/aade2fb1-e08b-4028-a176-fe5584bb388e">

<img width="1002" alt="image" src="https://github.com/matrixorigin/matrixone/assets/2995754/aee3c452-1579-4b64-b13e-584a98d71c41">

### Steps to Reproduce

```Markdown
1. use branch: https://github.com/zhangxu19830126/matrixone/tree/fix_tpcc_rc
2. run sysbench: ./start.sh -c cases/sysbench/update_pk_10_100000 -t 100 -d 5
```

**Comment by daviszhen** [comment]
@cnutshell  xu-peng 建议你先看下。

**Comment by cnutshell** [comment]
After running `./start.sh -c cases/sysbench/update_pk_10_100000 -t 100 -d 5` several times locally, it didn't report `Duplicate entry` error.

<img width="1055" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/f418edd1-5a9d-48a1-aa55-fddfb575f9d2">

**Comment by cnutshell** [comment]
PR #10251 is about `primary key de-duplication`, maybe it's related with this issue.

**Comment by cnutshell** [comment]
Attention, according to @zhangxu19830126, branch [zhangxu/fix_tpcc_rc](https://github.com/zhangxu19830126/matrixone/tree/fix_tpcc_rc) now takes `Incremental Deduplication` as default, but the duplicated error was reported under `Full deduplication` configuration.

So if one want to reproduce the duplication error, it is suggested that:
- turn on `Full deduplication` for dn
- trun off deduplication for cn
- test it under multi-cn environment

**Comment by cnutshell** [comment]
Wait for issue #10271.

**Comment by triump2020** [comment]
fixed by the [PR](https://github.com/matrixorigin/matrixone/pull/10311)

**Comment by XuPeng-SH** [comment]
@triump2020 is fixing a bug replaying logtail #10311, which may report duplicate pk

**Comment by triump2020** [comment]
@aressu1985  Pls  test , it shoud be fixed.

**Comment by aressu1985** [comment]
fixed
