### ISSUE TITLE
[Bug]: Multilayer foreign keys： load partsupp table more than 1h30min+ not succeed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10244]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6c14bc30b09ef54c53f0fb7e992fb1343ecd0c76
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

load tpch 10G data which ddl include foreign key ,partsupp.tbl which 8000000 rows , load into  partsupp table more than 1h30min+ not succeed
<img width="1118" alt="企业微信截图_5853cd6d-f8e1-4340-879b-5cfefd30df3a" src="https://github.com/matrixorigin/matrixone/assets/113406637/b67e8fcf-f71d-4ce1-8de6-4656e4b9220c">
<img width="468" alt="企业微信截图_71ca44bc-a598-4003-a785-fd1ecee616d3" src="https://github.com/matrixorigin/matrixone/assets/113406637/fe8085d2-2180-4512-9f11-4eae6524b4ff">

and test load tpch 1G data which ddl include foreign key, all table can load successfully, and lineitem table are 6000000+rows  ，load cost 17sec+
<img width="1405" alt="企业微信截图_b790338e-2dca-4ae2-8dbc-497eaf4c47fd" src="https://github.com/matrixorigin/matrixone/assets/113406637/e99b75d6-1714-40b8-9129-fefe34a2954f">

so  above tests  that this table may be stuck or have performance issues. plz refer to the foreign key relationship diagram
![image](https://github.com/matrixorigin/matrixone/assets/113406637/9cf10bc4-3bbe-4161-880c-1b969940406f)

mo log:
[log.txt](https://github.com/matrixorigin/matrixone/files/11865240/log.txt)

### Steps to Reproduce
ddl:
CREATE TABLE part_fk(
P_PARTKEY     INTEGER NOT NULL,
P_NAME        VARCHAR(55) NOT NULL,
P_MFGR        CHAR(25) NOT NULL,
P_BRAND       CHAR(10) NOT NULL,
P_TYPE        VARCHAR(25) NOT NULL,
P_SIZE        INTEGER NOT NULL,
P_CONTAINER   CHAR(10) NOT NULL,
P_RETAILPRICE DECIMAL(15,2) NOT NULL,
P_COMMENT     VARCHAR(23) NOT NULL,
PRIMARY KEY (P_PARTKEY)
);

CREATE TABLE region_fk(
R_REGIONKEY  INTEGER NOT NULL,
R_NAME       CHAR(25) NOT NULL,
R_COMMENT    VARCHAR(152),
PRIMARY KEY (R_REGIONKEY)
);

CREATE TABLE NATION_fk(
N_NATIONKEY  INTEGER NOT NULL,
N_NAME       CHAR(25) NOT NULL,
N_REGIONKEY  INTEGER NOT NULL,
N_COMMENT    VARCHAR(152),
PRIMARY KEY (N_NATIONKEY),constraint fk_n foreign key(N_REGIONKEY) REFERENCES region_fk(R_REGIONKEY)on delete CASCADE on update CASCADE
);

CREATE TABLE supplier_fk(
S_SUPPKEY     INTEGER NOT NULL,
S_NAME        CHAR(25) NOT NULL,
S_ADDRESS     VARCHAR(40) NOT NULL,
S_NATIONKEY   INTEGER NOT NULL,
S_PHONE       CHAR(15) NOT NULL,
S_ACCTBAL     DECIMAL(15,2) NOT NULL,
S_COMMENT     VARCHAR(101) NOT NULL,
PRIMARY KEY (S_SUPPKEY),constraint fk_s foreign key(S_NATIONKEY) REFERENCES nation_fk(N_NATIONKEY)on delete CASCADE on update CASCADE
);

CREATE TABLE PARTSUPP_fk(
PS_PARTKEY     INTEGER NOT NULL,
PS_SUPPKEY     INTEGER NOT NULL,
PS_AVAILQTY    INTEGER NOT NULL,
PS_SUPPLYCOST  DECIMAL(15,2)  NOT NULL,
PS_COMMENT     VARCHAR(199) NOT NULL,
PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),constraint fk_p1 foreign key(PS_PARTKEY) REFERENCES part_fk(P_PARTKEY)on delete CASCADE on update CASCADE,constraint fk_p2 foreign key(PS_SUPPKEY) REFERENCES supplier_fk(S_SUPPKEY) on delete CASCADE on update CASCADE
);

CREATE TABLE customer_fk(
C_CUSTKEY     INTEGER NOT NULL,
C_NAME        VARCHAR(25) NOT NULL,
C_ADDRESS     VARCHAR(40) NOT NULL,
C_NATIONKEY   INTEGER NOT NULL,
C_PHONE       CHAR(15) NOT NULL,
C_ACCTBAL     DECIMAL(15,2)   NOT NULL,
C_MKTSEGMENT  CHAR(10) NOT NULL,
C_COMMENT     VARCHAR(117) NOT NULL,
PRIMARY KEY (C_CUSTKEY),constraint fk_c foreign key(C_NATIONKEY) REFERENCES nation_fk(N_NATIONKEY) on delete CASCADE on update CASCADE
);

CREATE TABLE orders_fk(
O_ORDERKEY       BIGINT NOT NULL,
O_CUSTKEY        INTEGER NOT NULL,
O_ORDERSTATUS    CHAR(1) NOT NULL,
O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
O_ORDERDATE      DATE NOT NULL,
O_ORDERPRIORITY  CHAR(15) NOT NULL,
O_CLERK          CHAR(15) NOT NULL,
O_SHIPPRIORITY   INTEGER NOT NULL,
O_COMMENT        VARCHAR(79) NOT NULL,
PRIMARY KEY (O_ORDERKEY),constraint fk_o foreign key(O_CUSTKEY) REFERENCES customer_fk(C_CUSTKEY) on delete CASCADE on update CASCADE);

CREATE TABLE lineitem_fk(
L_ORDERKEY    BIGINT NOT NULL,
L_PARTKEY     INTEGER NOT NULL,
L_SUPPKEY     INTEGER NOT NULL,
L_LINENUMBER  INTEGER NOT NULL,
L_QUANTITY    DECIMAL(15,2) NOT NULL,
L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
L_DISCOUNT    DECIMAL(15,2) NOT NULL,
L_TAX         DECIMAL(15,2) NOT NULL,
L_RETURNFLAG  VARCHAR(1) NOT NULL,
L_LINESTATUS  VARCHAR(1) NOT NULL,
L_SHIPDATE    DATE NOT NULL,
L_COMMITDATE  DATE NOT NULL,
L_RECEIPTDATE DATE NOT NULL,
L_SHIPINSTRUCT CHAR(25) NOT NULL,
L_SHIPMODE     CHAR(10) NOT NULL,
L_COMMENT      VARCHAR(44) NOT NULL,
PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),constraint fk_l1 foreign key(L_ORDERKEY) REFERENCES ORDERS_fk(o_orderkey)on delete CASCADE on update CASCADE,constraint fk_l2 foreign key(L_PARTKEY,L_SUPPKEY) REFERENCES PARTSUPP_fk(PS_PARTKEY,PS_SUPPKEY) on delete CASCADE on update CASCADE);

load tpch 10G data:
load data infile '/Users/heni/mo-tpch/data/10/part.tbl' into table part_fk  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' parallel 'true';

load data infile '/Users/heni/mo-tpch/data/10/region.tbl' into table region_fk  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' parallel 'true';

load data infile '/Users/heni/mo-tpch/data/10/nation.tbl' into table nation_fk  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' parallel 'true';

load data infile '/Users/heni/mo-tpch/data/10/supplier.tbl' into table supplier_fk  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' parallel 'true';

load data infile '/Users/heni/mo-tpch/data/10/partsupp.tbl' into table partsupp_fk  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' parallel 'true';

**Comment by heni02** [comment]
@ouyuanning plz confirm this issue

**Comment by ouyuanning** [comment]
有2个原因
1、主要是外键检查，目前外键检查是普通left join，没有加runtime filter。不过加了估计也还是会慢

2、另外如果有设置了cn去重的话，load本来应该强制不做cn去重的，但是目前跟现有数据的去重没有强制去掉。这部分子然有提了PR处理了。

我看处理一下1的部分吧

**Comment by ouyuanning** [comment]
之前测试有开CN去重，本来load是强制不做CN去重的，之前有bug，也有打开了。
https://github.com/matrixorigin/matrixone/pull/10261
这个PR修复了这个问题。
目前main分支测试，导入800W数据大概11秒 - 13秒左右。

**Comment by ouyuanning** [comment]
试了一下
1、从left join转right join的话。load大数据量会报错（mpool申请内存超过1g)
2、增加了runtime filter会卡主。不知道是否增加有问题。
这个issue先这样吧。后面如果要继续优化的话，可以另外开性能优化的issue

**Comment by heni02** [comment]
confirm,closed
commit id:1f7f26148d7d03827e208589c132db46379dae01
![image](https://github.com/matrixorigin/matrixone/assets/113406637/20949c83-c796-464f-b4bf-477108f0edde)
