### ISSUE TITLE
[Bug]: perf of tpcc and sysbench oltp decreased more than 25% percentage on daily regression on eks

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10248]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ca8f93c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For daily regression on standlone mode on JUN 26th, perf of tpcc and sysbench decreased more than 25% percentage.

for commit: ca8f93c
**[sysbench oltp]**
INFO:root:The qps for [point_select_10_100000, vuser=100] is equal to or more than the last one.
INFO:root:This time: qps = 39770, and datetime = 2023-06-25 20:26:19
INFO:root:Last two times[0]: qps = 36782, and datetime = 2023-06-25 04:17:23
INFO:root:Last two times[1]: qps = 38201, and datetime = 2023-06-23 18:56:39
**ERROR:root:The qps for [update_pk_10_100000, vuser=100] is 25.0% lower than the last one.
ERROR:root:This time: qps = 1873, and datetime = 2023-06-25 20:43:32
ERROR:root:Last time: qps = 2961, and datetime = 2023-06-25 04:34:32
ERROR:root:The qps for [simple_insert_10_100000, vuser=100] is 25.0% lower than the last one.
ERROR:root:This time: qps = 2235, and datetime = 2023-06-25 21:01:27
ERROR:root:Last time: qps = 3271, and datetime = 2023-06-25 04:52:02
ERROR:root:The qps for [delete_pk_10_100000, vuser=100] is 25.0% lower than the last one.
ERROR:root:This time: qps = 3186, and datetime = 2023-06-25 21:19:29
ERROR:root:Last time: qps = 4969, and datetime = 2023-06-23 19:50:41**

**[tpcc]**
**ERROR:root:The tpmC for [warehouse=1, teminals=1] is 25.0% lower than the last one.
ERROR:root:This time: tpmC = 256.34, and datetime = 2023-06-25 18:51:22
ERROR:root:Last time: tpmC = 352.00, and datetime = 2023-06-23 17:40:52
ERROR:root:The tpmC for [warehouse=1, teminals=5] is 25.0% lower than the last one.
ERROR:root:This time: tpmC = 903.09, and datetime = 2023-06-25 18:56:38
ERROR:root:Last time: tpmC = 1243.81, and datetime = 2023-06-23 17:45:58**
INFO:root:The tpmC for [warehouse=1, teminals=10] is not 25.0% lower than the last one.
INFO:root:This time: tpmC = 1490.36, and datetime = 2023-06-25 19:01:52
INFO:root:Last two times[0]: tpmC = 1446.79, and datetime = 2023-06-25 03:10:05
INFO:root:Last two times[1]: tpmC = 1660.96, and datetime = 2023-06-23 17:51:01
**ERROR:root:The tpmC for [warehouse=10, teminals=10] is 25.0% lower than the last one.
ERROR:root:This time: tpmC = 1975.78, and datetime = 2023-06-25 19:06:58
ERROR:root:Last time: tpmC = 2793.54, and datetime = 2023-06-23 17:56:07
ERROR:root:The tpmC for [warehouse=10, teminals=50] is 25.0% lower than the last one.
ERROR:root:This time: tpmC = 3940.31, and datetime = 2023-06-25 19:12:22
ERROR:root:Last time: tpmC = 5329.83, and datetime = 2023-06-25 03:20:20**
INFO:root:The tpmC for [warehouse=10, teminals=100] is not 25.0% lower than the last one.
INFO:root:This time: tpmC = 3230.29, and datetime = 2023-06-25 19:17:32
INFO:root:Last two times[0]: tpmC = 2641.59, and datetime = 2023-06-25 03:25:29
INFO:root:Last two times[1]: tpmC = 3857.04, and datetime = 2023-06-23 18:06:20

the job link is : 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5370645833/jobs/9743862769

the compared commit is : 
6c14bc3
e5090ed

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/issues/10236#issuecomment-1606569881

**Comment by nnsgmsone** [comment]
> [#10236 (comment)](https://github.com/matrixorigin/matrixone/issues/10236#issuecomment-1606569881)

这个问题和10236应该是不一样，10236是因为不小心改坏了func(col) = 1这种过滤表达式才导致的，而tp都是col = 1这种场景

**Comment by ouyuanning** [comment]
tpcc的部分，本地环境测试暂未复现变慢的问题

**Comment by aressu1985** [comment]
fixed
