### ISSUE TITLE
Memory not freed after query is finished

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#1025]
#### Can be reproduced ?

Yes

#### Steps:

step1 and step2 refer to issue #953

> During loading, we can see the usage of memory is increasing, and the peak value is around 11G. After data load has been finished,  the memory is not freed to the system.

3. execute query `drop table`
> 11G of memory is still occupied by mo-server.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information: 005a89b69e6bee6932352b9717a707b8c5c3f495

**Comment by fengttt** [comment]
@sukki37 what do you mean memory is not freed?   How did you tell?

**Comment by fengttt** [comment]
Checked, that the "not freed" is reported by top.   This is perfectly fine, idle process does not necessary release anything back to OS.
