### ISSUE TITLE
[Bug]: mo was hung after running point select test with more than 60000+ tps for serveral minutes on eks with 3 CN

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10265]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9084cc4
- Hardware parameters: EC2 m6gd.4xlarge
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 800G
```

### Actual Behavior

after running point select test with more than 60000+ tps for serveral minutes, the mo was hung and can not be connected again.

<img width="1393" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/4af92ee6-a8ea-4f0d-b32e-e2c61f0cd3f2">

job link:
https://github.com/matrixorigin/mo-auto-test/actions/runs/5386934897/jobs/9777818741

<img width="720" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/926ed9c3-37d9-4a42-b421-b59da35fa457">

the cn has lots of such error logs:
: -- 0:0:0}|goRoutineId 110206|33d7fdd0-14bd-11ee-b064-221d95195edc"}
{"level":"ERROR","time":"2023/06/27 07:35:38.978876 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000030331s"}
{"level":"ERROR","time":"2023/06/27 07:35:39.124936 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000114861s"}
{"level":"ERROR","time":"2023/06/27 07:35:39.262949 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000030971s"}
{"level":"ERROR","time":"2023/06/27 07:35:39.402858 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000008349s"}
{"level":"ERROR","time":"2023/06/27 07:35:39.689101 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000012s"}
{"level":"ERROR","time":"2023/06/27 07:35:39.809539 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000086898s"}
{"level":"ERROR","time":"2023/06/27 07:35:39.931559 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000261686s"}
{"level":"ERROR","time":"2023/06/27 07:35:40.062527 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.000059648s"}
{"level":"ERROR","time":"2023/06/27 07:35:40.163472 +0000","caller":"etl/sql.go:72","msg":"sqlWriter WriteRowRecords failed","cnt":0,"error":"context deadline exceeded","time":"3.00034341s"}

the cn/dn/logservice log is:
[log.log](https://github.com/matrixorigin/matrixone/files/11879355/log.log)
[dn.log](https://github.com/matrixorigin/matrixone/files/11879358/dn.log)
[cn.log](https://github.com/matrixorigin/matrixone/files/11879359/cn.log)

the cn profile:

[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/11879356/profile.tar.gz)

**Comment by daviszhen** [comment]
抓到了卡住时的trace。

[trace_19_26-2.out.zip](https://github.com/matrixorigin/matrixone/files/11881805/trace_19_26-2.out.zip)

验证租户、用户、密码时，卡在了某些地方。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/f7b5aa2f-31d5-4403-b354-ac000bb85264)

**Comment by daviszhen** [comment]
复现步骤。

shell_1:
 kubectl -n mo-perf port-forward mo-perf-tp-cn-7tmbk 6001:6001

shell_2:
kubectl -n mo-perf exec -it mo-perf-tp-cn-7tmbk -- sh
//先开始抓trace文件。然后到shell_3上，用mysql client登录。
curl -o trace.out http://127.0.0.1:6060/debug/pprof/trace?seconds=30


shell_3:
mysql -h 127.0.0.1 -P6001 -udump -p111


shell_i：
导出trace文件。
kubectl -n mo-perf cp mo-perf-tp-cn-7tmbk:/trace.out ./trace.out
go tool trace trace.out

**Comment by xzxiong** [comment]
@aressu1985

**Comment by xzxiong** [comment]
> 直接原因1：MOCollector queue 满了 
> 
> 直接原因2：sqlWriter 写的太慢
> 
> 根本原因：....


@aressu1985 
针对直接原因，请使用新版本 e2c59f02d `Stmt aggr (#10256)`
这个issue 使用的版本，许多 TP 都没有被聚合，输出的 statement_info 非常多。
![image](https://github.com/matrixorigin/matrixone/assets/3927687/bc165640-5835-4a86-acd7-77e65c4f08de)

**Comment by xzxiong** [comment]
> 直接原因1：...
> 
> 直接原因2: ...
> 
> 根本原因：死锁 from [profile.tar.gz](https://github.com/matrixorigin/matrixone/files/11879356/profile.tar.gz), you will find this stack it trigger this call-chain cycle:
> 
> ```
> client -> export.(*MOCollector).Collect -> ... -> export.(*MOCollector).doExport 
>                             ^                       |
>                             | <-- logutil.Error <---
> ```
> 
> * stack info
> ...


针对 根本原因，我设想是 sqlWriter 打印的日志需要加个标记，能够识别并 丢弃。
@gavinyue 你怎么看？

**Comment by xzxiong** [comment]
wait pr merge

**Comment by xzxiong** [comment]
@aressu1985 #10331 pr merged, hung should be fixed. ptal
