### ISSUE TITLE
[Bug]:  SET FOREIGN_KEY_CHECKS = 1 internal error: the system variable does not exist

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10277]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

User works with Navicat to do data transfer, MatrixOne stops with an error in the middle with sentence of 
"SET FOREIGN_KEY_CHECKS".

```
mysql> SET FOREIGN_KEY_CHECKS = 1;
ERROR 20101 (HY000): internal error: the system variable does not exist
```

**Comment by daviszhen** [comment]
新发现 FOREIGN_KEY_CHECKS

**Comment by dengn** [comment]
customer test rely on this fix.

**Comment by daviszhen** [comment]
需要增加

**Comment by YANGGMM** [comment]
have fixed it

**Comment by dengn** [comment]
fixed
