### ISSUE TITLE
[Bug]: Config off 2PC PreCommit Write

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10272]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

We have a 2PC precommit write phase, which is pure overhead.   Should config it off, skip the code path.    
Or should remove the code path altogether.

**Comment by triump2020** [comment]
@fengttt  Done!
