### ISSUE TITLE
[Bug]: design table in navicat doesn't work

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10281]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In navicat, users usually use design table to modify table structures.

<img width="1433" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/114a22ad-925d-4efd-b05b-938894f0888b">

But this has two issues:
1. we get an error of partitition doesn't exist issue. The cause is this SQL doesn't work.
```
SELECT TABLE_NAME, PARTITION_NAME, SUBPARTITION_NAME, PARTITION_METHOD, SUBPARTITION_METHOD, PARTITION_EXPRESSION, SUBPARTITION_EXPRESSION, PARTITION_DESCRIPTION, PARTITION_COMMENT, NODEGROUP, TABLESPACE_NAME FROM information_schema.PARTITIONS WHERE NOT ISNULL(PARTITION_NAME) AND TABLE_SCHEMA LIKE 'eladmin' AND TABLE_NAME LIKE 'sys_job' ORDER BY TABLE_NAME, PARTITION_NAME, PARTITION_ORDINAL_POSITION, SUBPARTITION_ORDINAL_POSITION
```
2. any operation is blocked afterwards.
we cann't click on any column and do anything on it. 
<img width="1337" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/4d7b72f7-14a0-466a-ba6a-164be10f9b1b">

This is blocking usage of any alter table function.

**Comment by domingozhang** [comment]
will be fixed in next release

**Comment by daviszhen** [comment]
0.8来不及了。

**Comment by daviszhen** [comment]
下一个迭代

**Comment by dengn** [comment]
customer test replied on this fix.

**Comment by qingxinhome** [comment]
The issue has been confirmed

**Comment by qingxinhome** [comment]
Processing

**Comment by dengn** [comment]
@lacrimosaprinz This fix will affect information_schema, please refer to this PR https://github.com/matrixorigin/matrixone/pull/10330 for more details.

**Comment by qingxinhome** [comment]
In MySQL, the syntax for indexing is:
ADD {INDEX | KEY} [index_name]
     [index_type] (key_part,...) [index_option] ...
ADD [CONSTRAINT [symbol]] UNIQUE [INDEX | KEY]
        [index_name] [index_type] (key_part,...)
        [index_option] ...
		
	key_part: {col_name [(length)] | (expr)} [ASC | DESC]	

At present, our Mo index does not support the use of the expression expr as the index key or the sorting of the index. Therefore, when encountering this syntax, we will temporarily use error handling and no longer report panic. I have already submitted the PR, and if we need to support the use of expressions as index keys in the future,
Relevant development and design need to be done separately @dengn

**Comment by qingxinhome** [comment]
Code review in progress

**Comment by qingxinhome** [comment]
Code review in progress

**Comment by qingxinhome** [comment]
In research and design

**Comment by qingxinhome** [comment]
In research and design

**Comment by qingxinhome** [comment]
Code review in progress

**Comment by qingxinhome** [comment]
To begin

**Comment by qingxinhome** [comment]
I haven't started yet

**Comment by qingxinhome** [comment]
I haven't started yet

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
The partition table system view function has been implemented, please verify and test it @dengn @domingozhang @daviszhen

**Comment by dengn** [comment]
fixed.
