### ISSUE TITLE
[Bug]: select for update: insert into values mo not wait lock ,but mysql wait lock release

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84df60c4081376ddcf184a2596121487911696f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/de310a3c-e5e2-4cb7-b7f8-d178270bfcfa)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/34b3d7a8-7ff0-46b8-87ec-2f616921ccee)

mo：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/68e186fa-cb2b-4e2d-a0a2-8d6e836e64b7)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/393ffb33-3c3e-49a2-891e-2526dfc1c359)

### Steps to Reproduce

```Markdown
create table su_01_1(c1 int not null,c2 varchar(25),c3 int,primary key(c1));
insert into su_01_1 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);

start transaction;
select * from su_01_1 where c1>1 and c3<70 for update;
-- @session:id=1{
use select_for_update;
insert into su_01_1 values (10,'full',100);
select * from su_01_1;
-- @session}
rollback;
```

**Comment by heni02** [comment]
same as：
create table su_02(c1 int not null,c2 varchar(25),c3 int,unique index u1(c3));
insert into su_02 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);

begin;
select * from su_02 where c3>35 for update;
-- @session:id=1{
use select_for_update;
select * from su_02 where c3>35;
insert into su_02 values (8,'results',100);
select * from su_02;
-- @session}
commit;

**Comment by heni02** [comment]
same as：
create table su_03(c1 int not null,c2 varchar(25),c3 int,primary key(c1),key u1(c3));
insert into su_03 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);
-- secondary index , more rows lock, lock and unlock row update/delete/insert/truncate/alter/drop
begin;
select * from su_03 where c3 in(50,70) for update;
-- @session:id=1{
use select_for_update;
select * from su_03 where c3>35;
insert into su_03 values (8,'results',100);
-- @session}
commit；

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm issue

**Comment by zhangxu19830126** [comment]
select for update with expression is not supported now. Wait @domingozhang confirm mysql's behavior

**Comment by domingozhang** [comment]
in progress

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
This is the behavior of mysql rr isolation level. After setting rc  isolation level, there is no such issue here
![image](https://github.com/matrixorigin/matrixone/assets/113406637/019447e8-44e4-436e-afe8-7161945da42d)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/860e24b2-af03-4bd3-85ca-9d7077df1e2f)
