### ISSUE TITLE
[Bug]: select for update: update no waiting lock

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10305]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84df60c4081376ddcf184a2596121487911696f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/adec10ce-e38a-4835-b763-47017ef05301)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/86afa31b-f39e-4671-9103-dd679458a8e5)

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/a407b300-d0ed-45e0-95ee-bd29c4ed073c)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/dfad5f22-4507-4545-b33d-4bea9a58f85b)

### Steps to Reproduce

```Markdown
create table su_01_1(c1 int not null,c2 varchar(25),c3 int,primary key(c1));
insert into su_01_1 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);

start transaction ;
select * from su_01_1 where c1>1 and c3<70 for update;
-- @session:id=1{
use select_for_update;
update su_01_1 set c3=c3+10 where c3=70;
-- @session}
commit;
```

**Comment by heni02** [comment]
same as :
start transaction;
select * from su_01_1 where c1>1 and c3<70 for update;
-- @session:id=1{
begin;
update su_01_1 set c3=101 where c1=3;
rollback ;
-- @session}
rollback;

**Comment by heni02** [comment]
delete from su_01_1 where c1=1; execute succeed

**Comment by heni02** [comment]
same as：
create table su_02_2(c1 int not null,c2 varchar(25),c3 int,unique index u1(c3));
insert into su_02_2 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);

begin;
select * from su_02_2 where c3>55 and c3<65 for update;
-- @session:id=1{
use select_for_update;
update su_02_2 set c1=30 where c2 like 'yell%';
select * from su_02_2;
-- @session}
commit;

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm issue

**Comment by zhangxu19830126** [comment]
select for update with expression is not supported now. Wait @domingozhang confirm mysql's behavior

**Comment by domingozhang** [comment]
in progress

**Comment by domingozhang** [comment]
Gap lock in range only effects on RR level.
In these cases, lock only exists the result rows of select for update. 

For example:
select * from su_01_1 where c1>1 and c3<70 for update;
+----+-------+------+
| c1 | c2    | c3   |
+----+-------+------+
|  2 | plo   |   50 |
|  3 | kelly |   60 |
+----+-------+------+
2 rows in set (0.00 sec)

Only these rows are locked and user can insert/update/delete other non-related values.

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
This is the behavior of mysql rc isolation level. After setting rc, verify that there is no such issue here
mysql rc isolation
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e178944c-2b07-4fee-b3f4-0803530f8d62)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4d1a51ba-f89b-45ee-81c7-1624207b58cc)
