### ISSUE TITLE
unexpect cluster id after modify dir-data

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1030]
#### Can be reproduced ?
Yes

#### Steps:
1. Start database service
2. Stop service
3. Modify dir-data
4. Start database service but notified "unexpect cluster id"

5. Delete the old directory of dir-data and then start database service normally.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 142b680daadcff3ea8bf701a405d91adc4a833ba
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by LeftHandCold** [comment]
I can't reproduce according to the steps
