### ISSUE TITLE
[Bug]: select for update: prepare stmt not wait lock

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10318]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84df60c4081376ddcf184a2596121487911696f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f3553b5c-96ee-4c95-be4f-24403a499f5b)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d2b70151-2fb3-44b4-9b7f-df2686986e0b)

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7500a273-c431-49f9-ae72-5d44bc8547cb)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d49b4b17-009b-4044-bc19-1e5935a1c1b0)

### Steps to Reproduce

```Markdown
create table su_06(c1 int not null,c2 varchar(25),c3 int,primary key(c1),key u1(c3));
insert into su_06 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);
start transaction;
select * from su_06 where c1>=2 for update;
-- @session:id=1{
use select_for_update;
prepare stmt1 from 'update su_06 set c3=c3+1.09 where c1=?';
set @var = 2;
execute stmt1 using @var;
select * from su_06;
-- @session}
commit;
```

**Comment by zhangxu19830126** [comment]
prepare 没有上锁

**Comment by ouyuanning** [comment]
好像最新的main分支这样就可以复现
create table t1 (a int auto_increment primary key, b int);
insert into t1(b) values (1),(2);

begin;
select * from t1 where a=2 for update;
-- @session:id=1{
update t1 set b = 3 where a = 2;  //这里应该等待，但是实际会执行成功
-- @session}


看着跟prepare关系没有关系

**Comment by heni02** [comment]
confirm,closed
commit id: 48a289863740d954b9e48fbc889fc100a1f85198
![image](https://github.com/matrixorigin/matrixone/assets/113406637/274d58e4-1c8c-4f95-9c15-cd1d333ced93)
