### ISSUE TITLE
[Bug]: select for update: delete no waiting lock

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10312]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84df60c4081376ddcf184a2596121487911696f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/82feec55-646d-40d4-b966-9695579b88ef)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b4f8d8f7-abd3-4dae-99a6-162341c6834e)

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4a543503-48cd-47f1-bbb6-da0482901134)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/9c0f718f-3daf-4602-becb-e54e1fc8a979)

### Steps to Reproduce

```Markdown
create table su_03(c1 int not null,c2 varchar(25),c3 int,primary key(c1),key u1(c3));
insert into su_03 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);

begin;
select * from su_03 where c3 in(50,70) for update;
-- @session:id=1{
delete from su_03 where c3 between 10 and 70;
-- @session}
commit;
```

**Comment by heni02** [comment]
same as:
create table su_04(c1 int not null,c2 varchar(25),c3 int);
insert into su_04 values(1,'results',20),(2,'plo',50),(3,'kelly',60),(4,'yellow',70);

begin;
select * from su_04 where c2='kelly' for update;
-- @session:id=1{
use select_for_update;
delete from su_04 where c1=4;
select * from su_04;
-- @session}
commit;

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm issue

**Comment by ouyuanning** [comment]
似乎是跟 #10318 一样的问题。

**Comment by heni02** [comment]
comfirm,closed
commit id:48a289863740d954b9e48fbc889fc100a1f85198
![image](https://github.com/matrixorigin/matrixone/assets/113406637/3b5c4414-5a68-4d82-854b-11c803d5c2d8)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/5ddbe56f-5cf7-41dd-bbca-3438d34ad535)
