### ISSUE TITLE
[Bug]: select for update table which include partition reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10314]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84df60c4081376ddcf184a2596121487911696f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e4fde6ca-7fd7-4755-bc44-21ac0011189d)

mysql> select * from su_05 where c1>3 for update;
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is []types.Decimal64, not []int32:
runtime.panicdottypeE
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/tools.go:42
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.fetchFixedRowsWithCompare[...]
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/fetch.go:701
github.com/matrixorigin/matrixone

session 2 :update sql also reported panic
![image](https://github.com/matrixorigin/matrixone/assets/113406637/45fbf384-3af7-496f-b834-16eab657de68)
mysql>  update su_05 set c3=c3-1 where c1>2;
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is []types.Rowid, not []int32:
runtime.panicdottypeE
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/tools.go:42
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/lock_op.go:198
github.com/matrixorigin/matrixone/pkg/sql/colexec/lock

### Steps to Reproduce

```Markdown
create table su_05(c1 int not null primary key,c2 varchar(25),c3 decimal(6,2))partition by key(c1)partitions 4;;
insert into  su_05 values (1,'mod',78.9),(2,'proto',0.34),(3,'mod',6.5),(4,'mode',9.0),(5,'make',662.9),(6,'io',88.92);
select * from `%!%p0%!%su_05`;
select * from `%!%p1%!%su_05`;
select * from `%!%p2%!%su_05`;
select * from `%!%p3%!%su_05`;
begin;
select * from su_05 where c1>3 for update;
```

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm issue

**Comment by qingxinhome** [comment]
The issue has been confirmed

**Comment by qingxinhome** [comment]
This issue should have been fixed, and the latest code does not report any errors，please confirm @zhangxu19830126 @heni02 @daviszhen

**Comment by qingxinhome** [comment]
Processing

**Comment by qingxinhome** [comment]
The issue has been resolved, please test and verify @heni02

**Comment by heni02** [comment]
confirm,closed
commit id:48a289863740d954b9e48fbc889fc100a1f85198
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7a0635e3-814a-46d8-909f-fae63672dad3)
