### ISSUE TITLE
[Bug]: task service not schedule StorageUsage task

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#10310]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e2c59f0
- Hardware parameters:
- OS type: eks （Cloud dev)
- Others:
```

### Actual Behavior

StorageUsage 运行在 CN `39316630-6539-3839-3235-383333306665` 上
从 goroutine的信息来看，没有  StorageUsage 运行的堆栈（代码位置 `pkg/util/metric/cron_task.go`）

```
mysql> select * from mo_task.sys_async_task where task_status = 1\G
*************************** 1. row ***************************
               task_id: 4
      task_metadata_id: StorageUsage:1
task_metadata_executor: 3
 task_metadata_context: 0x
  task_metadata_option: {"Concurrency":1}
        task_parent_id: StorageUsage
           task_status: 1
           task_runner: 39316630-6539-3839-3235-383333306665
            task_epoch: 3
        last_heartbeat: 1687921876877
           result_code: 0
             error_msg:
             create_at: 1687859040053
                end_at: 0
1 row in set (0.16 sec)

mysql> show backend servers;
+--------------------------------------+-------------------+-----------------------------------------------+
| UUID                                 | Address           | Labels                                        |
+--------------------------------------+-------------------+-----------------------------------------------+
| 39303339-3464-6532-6537-326164396438 | 10.0.159.187:6001 |                                               |
| 39626335-3035-3938-6665-323538383364 | 10.0.128.7:6001   | account:bb9406f9_95f3_48af_a5c8_524ec75cf38e; |
| 61646236-3338-6366-6231-393564623564 | 10.0.158.203:6001 |                                               |
| 39316630-6539-3839-3235-383333306665 | 10.0.133.134:6001 | account:3ed5ba28_2a3e_4eb0_bc24_ebabb515cd99; |
+--------------------------------------+-------------------+-----------------------------------------------+
4 rows in set (0.05 sec)

```

通过 CN 的 address ip 找到对应 pod
```
$ kubectl get pod -A -owide | grep 10.0.133.134
3ed5ba28-2a3e-4eb0-bc24-ebabb515cd99   normal-cn-fb4kb                                               1/1     Running   0               29h     10.0.133.134   ip-10-0-153-229.ap-southeast-1.compute.internal   <none>           2/2

$ kubectl get pod -n 3ed5ba28-2a3e-4eb0-bc24-ebabb515cd99 -owide
NAME              READY   STATUS    RESTARTS   AGE   IP             NODE                                              NOMINATED NODE   READINESS GATES
normal-cn-fb4kb   1/1     Running   0          8h    10.0.133.134   ip-10-0-153-229.ap-southeast-1.compute.internal   <none>           2/2
```
- normal-cn-fb4kb 的 goroutine, lsof, 和运行日志。
[goroutine.normal-cn-fb4kb.txt](https://github.com/matrixorigin/matrixone/files/11892912/goroutine.normal-cn-fb4kb.txt)
[lsof.normal-cn-fb4kb.txt](https://github.com/matrixorigin/matrixone/files/11892913/lsof.normal-cn-fb4kb.txt)
[normal-cn-fb4kb.log](https://github.com/matrixorigin/matrixone/files/11892914/normal-cn-fb4kb.log)

**Comment by xzxiong** [comment]
@w-zr ptal

**Comment by w-zr** [comment]
Should be fixed in #10339

**Comment by xzxiong** [comment]
update task error exist info.
```
select timestamp, logger_name, caller, message, extra, json_unquote(json_extract(extra, '$.error')) from system.log_info where trace_id = '101982c8-b6c0-148e-7181-9b45564419c6' and logger_name != 'cn-service.ETLMerge' and message != 'internalExecutor new session' order by timestamp\G
```
![企业微信截图_911ecf62-27e7-4096-8970-757583d78f14](https://github.com/matrixorigin/matrixone/assets/3927687/9b6e8dec-cc5a-4de7-8eba-e285d895ef2c)

**Comment by w-zr** [comment]
> after task error exist, task running ok.
> 
> * mysql -h freetier-02.ap-southeast-1.cluster.dev.matrixone.tech -P 6001 -udump -p*** --ssl-mode=DISABLED -A
> 
> ```
> mysql> select * from mo_task.sys_async_task where task_status= 1;
> +---------+-------------------+------------------------+----------------------------------------------+----------------------+----------------+-------------+--------------------------------------+------------+----------------+-------------+-----------+---------------+--------+
> | task_id | task_metadata_id  | task_metadata_executor | task_metadata_context                        | task_metadata_option | task_parent_id | task_status | task_runner                          | task_epoch | last_heartbeat | result_code | error_msg | create_at     | end_at |
> +---------+-------------------+------------------------+----------------------------------------------+----------------------+----------------+-------------+--------------------------------------+------------+----------------+-------------+-----------+---------------+--------+
> |   10082 | ETL_merge_task:83 |                      2 | 0x                                           | {"Concurrency":1}    | ETL_merge_task |           1 | 35396332-6363-6138-6433-666366303836 |        441 |  1688622181430 |           0 |           | 1688616900107 |      0 |
> |       4 | StorageUsage:1    |                      3 | 0x                                           | {"Concurrency":1}    | StorageUsage   |           1 | 35396332-6363-6138-6433-666366303836 |        465 |  1688622184413 |           0 |           | 1688542860068 |      0 |
> +---------+-------------------+------------------------+----------------------------------------------+----------------------+----------------+-------------+--------------------------------------+------------+----------------+-------------+-----------+---------------+--------+
> 2 rows in set (0.21 sec)
> 
> mysql> show backend servers;
> +--------------------------------------+-------------------+--------+
> | UUID                                 | Address           | Labels |
> +--------------------------------------+-------------------+--------+
> | 35396332-6363-6138-6433-666366303836 | 10.0.147.117:6001 |        |
> +--------------------------------------+-------------------+--------+
> 1 row in set (0.42 sec)
> ```
> 
> * last time error exist info.
> 
> ```
> select timestamp, logger_name, caller, message, extra, json_unquote(json_extract(extra, '$.error')) from system.log_info where trace_id = '101982c8-b6c0-148e-7181-9b45564419c6' and logger_name != 'cn-service.ETLMerge' and message != 'internalExecutor new session' order by timestamp\G
> ```
> 
> ![企业微信截图_911ecf62-27e7-4096-8970-757583d78f14](https://user-images.githubusercontent.com/3927687/251354761-9b6e8dec-cc5a-4de7-8eba-e285d895ef2c.png)

Please track this issue in https://github.com/matrixorigin/matrixone/issues/10459

**Comment by xzxiong** [comment]
checked, run ok now

**Comment by xzxiong** [comment]
@w-zr ptal new case in https://github.com/matrixorigin/MO-Cloud/issues/1079

**Comment by w-zr** [comment]
Please test this issue again @xzxiong

**Comment by w-zr** [comment]
task runner cannot fetch rescheduled tasks with old task id. since the taskID will not not change after rescheduled.
![image](https://github.com/matrixorigin/matrixone/assets/28624654/83a9318a-eed1-447c-83fa-cd944b1bcf73)

**Comment by xzxiong** [comment]
@aressu1985  ptal

**Comment by aressu1985** [comment]
not working on it

**Comment by aressu1985** [comment]
fixed
分别测试了重启单CN，多CN的情况，任务均可以重新调度
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/2c76f011-042b-4ebd-9fc3-3e22177f6ea6">
