### ISSUE TITLE
[Bug]: pessmistic rc mode : after select table truncate not wait lock release

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10316]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84df60c4081376ddcf184a2596121487911696f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e750670c-7248-4b02-a326-4479c37b890e)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0c0aeb0c-4554-4c81-839a-0ace9449c0d9)

mysql:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0c56f2c2-7d30-4a1c-8bea-2db9e21af535)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e8afbd1a-852e-41b4-980e-a98bd729920a)

### Steps to Reproduce

```Markdown
create table su_05_1(c1 int auto_increment primary key,c2 varchar(25),c3 decimal(6,2))partition by key(c1)partitions 4;;
insert into  su_05_1(c2,c3) values ('mod',78.9),('proto',0.34),('mod',6.5),('mode',9.0),('make',662.9),('io',88.92);
set autocommit=0;
select * from su_05_1 where c1=3;
-- @session:id=1{
truncate table su_05_1;
select * from su_05_1;
-- @session}
commit;
```

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm issue

**Comment by zhangxu19830126** [comment]
遗漏上锁

**Comment by ouyuanning** [comment]
在begin 中，无for update，纯粹的select语句我们是不会上锁的。目前我们是不会上锁的。
但是MySQL会。这个待和产品同学确认后再看如何修改

**Comment by ouyuanning** [comment]
待产品同学确认

**Comment by ouyuanning** [comment]
待产品同学确认

**Comment by ouyuanning** [comment]
确认这是MySQL的RR隔离级别的行为。

**Comment by heni02** [comment]
mysql rc isolation：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/24fae0a7-c200-4e0b-857c-80fa3de09ec7)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b1f3c6da-5f8f-4ba8-b4ae-b31d3b26ee67)

**Comment by ouyuanning** [comment]
刚会上了解。当begin之后。所有select到的表都上了类似表锁的锁，但是不影响update/delete，影响drop/truncate

可能需要确认
1、我们的表锁好像是影响 update/delete 的？
2、所有select语句都锁所有的表吗？（select a from t1 join t2 on xx=xx where a in (select c from t3) 类似这样，锁3个表？）
3、Update类语句，是否锁查询到的表。比如  （update t1.a = xx from t1 join t2 on xx=xx where t2.xx=xx ，这个语句更新t1，但是查询了t1,t2）

**Comment by ouyuanning** [comment]
待讨论

**Comment by ouyuanning** [comment]
建议先降低优先级。转为需求

**Comment by jensenojs** [comment]
<img width="1590" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/91a9a809-03b6-4c3f-ace7-8eb2f3b459a0">

类似于show table xxx的上锁逻辑似乎实际上没有执行

**Comment by jensenojs** [comment]
经讨论, 这个就是我们的产品行为. @heni02 贺妮姐看看要不把它关掉吧, 后续bvt有些case的行为可能也需要改一下

<img width="817" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/2e81840f-eb73-428c-9caf-65a51c79cc30">

**Comment by ouyuanning** [comment]
@heni02 如果DQL不锁的话，可能对应bvt tag下的用例要修改或删除

**Comment by heni02** [comment]
待修改bvt case

**Comment by heni02** [comment]
closed

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
