### ISSUE TITLE
[Bug]: Latest main commit  pessimisc and rc mode mo startup failure

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10332]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1f7f26148d7d03827e208589c132db46379dae01
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

start: ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml >log.txt 
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6477e7e1-fb13-4c10-bed4-db27139ba931)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4139015d-1310-46b9-9706-58f83b8ce09e)

**Comment by zhangxu19830126** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
commit id:d14c80ecb98762ef039d726d63fb0dd5b418ceab
1cn：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/aa8b7f47-f64c-4f5c-a101-9df14d86fb48)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/3c413644-8845-475a-99c5-b2e6db521db3)

2cn:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/bd4e3e0e-e475-4fd5-88e9-1ed9a623f7e5)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e035ae4a-f9f9-4ea8-b287-b13d58824fce)
