### ISSUE TITLE
[Feature Request]: add metrics to monitor dn system 

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10337]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

We'll define and implement metrics in TAE to monitor the DN system, which includes but is not limited to:

1. Checkpoint metrics
2. WAL metrics
3. Data read and write metrics
4. Pool metrics
5. Logtail metrics
6. GC metrics

**Comment by dengn** [comment]
1. Does this affect the current tracing schema?
2. is there anything worthy for users to pay attention?

**Comment by dengn** [comment]
> 1. Does this affect the current tracing schema?
> 2. is there anything worthy for users to pay attention?

Nothing for users to pay attention. No impact for user experience.

**Comment by fengttt** [comment]
Need to convert all moctl spans to 
1. ordinary spans, and/or
2. metrics
