### ISSUE TITLE
Reference to the inappropriate port

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#1034]
#### Can be reproduced ?

yes

#### Steps:

the rpc in computation engine will reference to the inappropriate port in the multi-nodes environment.

The initial port:
https://github.com/matrixorigin/matrixone/blob/f11105329d5c8daf6f73041dde47624dd408aa82/cmd/db-server/main.go#L262

The port referenced:

https://github.com/matrixorigin/matrixone/blob/f11105329d5c8daf6f73041dde47624dd408aa82/pkg/sql/compile/scope.go#L141

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f11105329d5c8daf6f73041dde47624dd408aa82
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by m-schen** [comment]
this issue has been solved.
rpc server will use port cubePort+100.
