### ISSUE TITLE
[Bug]: for an entry in error_info or log_info, how can I relate it back to the record in statement_info?  

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10351]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This is all very nice but my question is, i need to pull out all log recrods, info and error, of one query that I am interested, who can I do that?    What is the sql query for that?

There does not seem to have a reasonable query to answer this.    Probably this means we did not collect enough or correct information.

Due to this is after 0.8 and we target 1.0, please take care of upgrade.

**Comment by fengttt** [comment]
Related, need to relate all logs to its session and node.   I think node id is always there, but we need either session or query id.

**Comment by fengttt** [comment]
Note that we must track every worker CN for the statement as well.     And if query has multi steps.

**Comment by dengn** [comment]
Yeah. I wanted this for so long..current debugging from error_info back to statement_info is painful.

**Comment by gavinyue** [comment]
Still under design.

**Comment by gavinyue** [comment]
Work on design today.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Under design

**Comment by gavinyue** [comment]
Still working.

**Comment by gavinyue** [comment]
Merged one pr and one pending.

**Comment by gavinyue** [comment]
Doc: https://doc.weixin.qq.com/doc/w3_AS0AvwapAOkN6NyZPzZScif4PbH9s?scode=AJsA6gc3AA8trbvnlnAS0AvwapAOk

Refactor the PR now

**Comment by gavinyue** [comment]
Had a meeting. The left work is multi tenant table upgrade.

**Comment by gavinyue** [comment]
Still working on multi tenant upgrade

**Comment by gavinyue** [comment]
Still refactor to solve multitenant tables.

**Comment by gavinyue** [comment]
Under dev

**Comment by gavinyue** [comment]
Could not pass Bvt. Still working.

**Comment by gavinyue** [comment]
The current pr does not solve multi tenant table upgrades. Will solve it in next.

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/10620
This PR has added two columns to rawlog that could associate the log back to stmt. 

However, this PR is pending due to another bug found here: https://github.com/matrixorigin/matrixone/issues/10959

**Comment by gavinyue** [comment]
The blocker pr has been resolved. The pr needs to be reviewed

**Comment by gavinyue** [comment]
under review
