### ISSUE TITLE
[Bug]: show create table session crash and gets error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10353]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create database abc;
Query OK, 1 row affected (0.02 sec)

mysql> use abc;
Database changed
mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)
mysql> alter table t2 add index ((a * 40) DESC);
Query OK, 0 rows affected (0.00 sec)
mysql> show create table t2;
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/sql/plan.setEmptyIndexName
        /data/mo/202306271211/matrixone/pkg/sql/plan/build_ddl.go:969
github.com/matrixorigin/matrixone/pkg/sql/plan.buildAlterTable
        /data/mo/202306271211/matrixone/pkg/sql/plan/build_ddl.go:1784
github.com/matrixorigin/matrixone/pkg/sql/plan.
No connection. Trying to reconnect...
Connection id:    44017
Current database: abc

+-------+------------------------------------------------------------------------+
| Table | Create Table                                                           |
+-------+------------------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (
`a` INT DEFAULT NULL
) COMMENT='New table comment' |
+-------+------------------------------------------------------------------------+
1 row in set (0.02 sec)

**Comment by qingxinhome** [comment]
The issue has been confirmed

**Comment by qingxinhome** [comment]
In MySQL, the syntax for indexing is:
ADD {INDEX | KEY} [index_name]
     [index_type] (key_part,...) [index_option] ...
ADD [CONSTRAINT [symbol]] UNIQUE [INDEX | KEY]
        [index_name] [index_type] (key_part,...)
        [index_option] ...
		
	key_part: {col_name [(length)] | (expr)} [ASC | DESC]	

At present, our Mo index does not support the use of the expression expr as the index key or the sorting of the index. Therefore, when encountering this syntax, we will temporarily use error handling and no longer report panic. I have already submitted the PR, and if we need to support the use of expressions as index keys in the future,
Relevant development and design need to be done separately @dengn

**Comment by dengn** [comment]
fixed.
