### ISSUE TITLE
[Bug]: group by alias problem

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10356]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In MySQL:

```
CREATE TABLE `a1` (
  `a` int DEFAULT NULL
);
mysql> select abs(a) as abs_a from a1 group by abs_a order by abs_a desc;
+-------+
| abs_a |
+-------+
|     1 |
+-------+
1 row in set (0.02 sec)

```

In MO:
```
mysql>  select abs(a) as abs_a from a1 group by abs_a order by abs_a desc;
ERROR 20301 (HY000): invalid input: column abs_a does not exist
```

**Comment by aunjgr** [comment]
MO only allows aliases in ORDER BY clause.

**Comment by dengn** [comment]
After discussion, we will implement this syntax. 
If will affect:
-The syntax for select
-mysql compatibility, behavior same as mysql after implementation

**Comment by aunjgr** [comment]
To comply to the behavior of mysql/postgresql, unresolved names in GROUP BY and HAVING should first try to bind to table columns, then fallback to SELECT aliases.

I.E., we should report error for t(a int, b int), `select a as b from t group by b`, because the `b` in GROUP BY is bound to `t`'s column, and `a` is not in GROUP BY list.

**Comment by aunjgr** [comment]
I will work on this next week.

**Comment by lacrimosaprinz** [comment]
Related documentation:
@dengn pls review and check 👇🏻

[mysql compatibility]: modify and delete the description of the `group by` not supporting the alias
[select]: modify and delete the description of the `group by` not supporting the alias

**Comment by aunjgr** [comment]
Some notes for the behavior:

1. An alias can't be referenced by another alias.
2. In GROUP BY/HAVING, first search for column then search for alias as a fallback, which is opposite to the case in ORDER BY. It's strange but both mysql and postgresql behave like this.

**Comment by aunjgr** [comment]
There is one case that MySQL has different behavior than PostgreSQL:

```sql
create table t1(a int, b int);
create table t2(a int, c int);
insert into t1 values(1, 0), (2, 0);
insert into t2 values(3, 1), (4, 2);

select b as a from t1 join t2 on t1.a = t2.c group by a;
```

MySQL returns 1 row valued 0, which is actually `t1.b`. PostgreSQL reports an error `column reference "a" is ambiguous`. According to Rule 2, we will adopt PostgreSQL's behavior.

**Comment by aunjgr** [comment]
The whole logic of binding an unresolved name in GROUP BY/HAVING clause will be:

```
if NAME is found in some table:
  if NAME is found in more than 1 table:
    report ambiguous column reference
  else:
    bind to the table
else if NAME is found in select aliases:
  replace NAME with aliased expression
else:
  report NAME not found
```

**Comment by aunjgr** [comment]
PR is merged.

**Comment by lacrimosaprinz** [comment]
docs edit:https://github.com/matrixorigin/matrixorigin.io/pull/467

**Comment by dengn** [comment]
> docs edit: [matrixorigin/matrixorigin.io#467](https://github.com/matrixorigin/matrixorigin.io/pull/467) [matrixorigin/matrixorigin.io.cn#615](https://github.com/matrixorigin/matrixorigin.io.cn/pull/615)

We needs to document the three above notes for group by, and also update MySQL compatibility. @lacrimosaprinz

**Comment by dengn** [comment]
issue fixed.
