### ISSUE TITLE
[Feature Request]: SHOW PROCESSLIST

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10359]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Use this statement to find all process status in current cluster.
Details can be found in internal docs

**Comment by dengn** [comment]
Unclear about this feature:
1. what's the point of implementing this? what kind of benefit do users get?
2. what's the format of the output, does it comply with MySQL syntax or it has something special?
3. how does it make a difference for standalone and distributed version?

**Comment by xzxiong** [comment]
@domingozhang @volgariver6 ptal
MOCloud needs:  `select * from processlist where ...` do the filter query and get some columns result to show the running status query.
details:
1. support `select` filter query
2. show more columns like:
    - query_id
    - transaction_id
    - session_id
    - statement_type
    - query_type
    - sql_source_type
    - duration
    - query start_time

**Comment by volgariver6** [comment]
done by #10782

**Comment by lacrimosaprinz** [comment]
doc pr：https://github.com/matrixorigin/matrixorigin.io.cn/pull/621

**Comment by dengn** [comment]
> doc pr： [matrixorigin/matrixorigin.io.cn#621](https://github.com/matrixorigin/matrixorigin.io.cn/pull/621) [matrixorigin/matrixorigin.io#472](https://github.com/matrixorigin/matrixorigin.io/pull/472)

There is some little difference between standalone and distributed version, especially on node id information. Please update doc to reveal that. @lacrimosaprinz

**Comment by Ariznawlll** [comment]
test done！
