### ISSUE TITLE
[Feature Request]: Tidy configuration files items

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10365]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In current configuration file, there are many items which only have one value or no need to place in configuration files.
Need tidy these items

**Comment by fengttt** [comment]
I am not sure if I understand the issue.    A config has only one possible value means some dev want to keep it "future proof", this is a valid use and there is no need to set that in config file, therefore not a burden.

I do agree too many of these is a hygiene problem.

**Comment by dengn** [comment]
For doc side, we need to keep up whatever parameters cn,dn,log toml files provide, and explain about the important parameters for users. 
There might be some parameters which are supposed to be in the config files for users to modify but actually not, we file a bug.

**Comment by dengn** [comment]
For those parameters who actually exist and may be useful for users, but don't exist in the default config files, please refer to  https://github.com/matrixorigin/MO-Cloud/issues/963 @fengttt @sukki37

**Comment by sukki37** [comment]
in progress

**Comment by sukki37** [comment]
only a p1 subtask is left, this issue can be downgraded. @domingozhang

**Comment by domingozhang** [comment]
downgraded to p1

**Comment by lacrimosaprinz** [comment]
docs edited:
https://github.com/matrixorigin/matrixorigin.io/pull/507
https://github.com/matrixorigin/matrixorigin.io.cn/pull/665
