### ISSUE TITLE
[Feature Request]: Tidy log output items

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10363]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Current log output items are complicated and messy.
Need tidy output items and remove uneccessy ones.

**Comment by dengn** [comment]
Unclear about what might be changed for doc side. If any real modification happens, please update it here. Doc will keep up.

**Comment by fengttt** [comment]
Not actionable.
