### ISSUE TITLE
[Bug]: data race in merge run

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10376]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/39627130/c619b7a6-5630-4303-acfc-38e596ad7cab)

### Steps to Reproduce

```Markdown
make debug
run bvt cases
```

**Comment by m-schen** [comment]
zs的pr合并后我来改这个，现在冲突有点多。

**Comment by m-schen** [comment]
已经验证过，目前不会有该race问题。
