### ISSUE TITLE
[Bug]: data race in cnservice

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10379]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1137" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/fda21ea7-a034-4f5e-a9ee-14439660d642">

### Steps to Reproduce

```Markdown
Latest commit: 6200380f435c5dd6b7e211f0ed80247a3a861085
make debug
start mo
```

**Comment by m-schen** [comment]
今天开始处理该issue。

**Comment by m-schen** [comment]
已修复，在本地启动验证已没有该race.
