### ISSUE TITLE
[Feature Request]: support partitioned table phase II

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10388]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support COLUMN and RANGE partition:

PARTITION BY RANGE [COLUMNS]
PARTITION BY LIST [COLUMNS]

**Comment by qingxinhome** [comment]
The requirement has been confirmed

**Comment by dengn** [comment]
Please specify the details of this feature:
1. is it a syntax-only implementation or a full implementation?
2. can the other two partition(key and hash) serve for real performance improvement?

**Comment by qingxinhome** [comment]
没开始

**Comment by domingozhang** [comment]
performance improvement is out of scope in 1.0.0

**Comment by qingxinhome** [comment]
performance improvement is out of scope in 1.0.0

**Comment by domingozhang** [comment]
1.0 Scope：
PARTITION BY RANGE [COLUMNS]
PARTITION BY LIST [COLUMNS]

Performance improvement will not be implemented.

**Comment by lacrimosaprinz** [comment]
https://github.com/matrixorigin/matrixorigin.io/pull/483
https://github.com/matrixorigin/matrixorigin.io.cn/pull/635

**Comment by qingxinhome** [comment]
matrixone分区表使用说明文档：
https://github.com/matrixorigin/docs/blob/main/design/mo_partition_instructions.md

**Comment by qingxinhome** [comment]
This function has been implemented, and now we propose to test it. @dengn @sukki37 @domingozhang @heni02 @aressu1985 @daviszhen

**Comment by florashi181** [comment]
will track with #12927 in V1.2
