### ISSUE TITLE
[Bug]: 0.8.0 release version is incorrect

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10389]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Checked.on https://github.com/matrixorigin/matrixone/releases/download/v0.8.0/mo-v0.8.0-darwin-arm64.zip

After connection, it shows:

```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 11
Server version: 8.0.30-MatrixOne-v94000 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

version number is not correct.

**Comment by LeftHandCold** [comment]
@daviszhen

**Comment by volgariver6** [comment]
fixed by #10413, but it only takes affect for the future versions.

**Comment by dengn** [comment]
Please update this to the 0.8.0 release binary. @guguducken

**Comment by guguducken** [comment]
upgrade, please kindly check @dengn https://github.com/matrixorigin/matrixone/releases/download/v0.8.0/mo-v0.8.0-darwin-arm64.zip

**Comment by dengn** [comment]
fixed.
