### ISSUE TITLE
[Bug]: Window function performance issues

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10381]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:d19e2b0a2b35d217c64d72e7bd1d07a00890b55a
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/108530700/c63f66a8-0f16-48cc-91aa-be490d3aa31f)

### Expected Behavior

return correct result.

### Steps to Reproduce

```Markdown
drop table if exists td;
create table td(d int);

insert into td(d) values (10),(1),(2),(3),(4),(5),(6),(7),(8),(9);
insert into td(d) select d+10 from td;
insert into td(d) select d+20 from td;
insert into td(d) select d+30 from td;
insert into td(d) select d+40 from td;
insert into td(d) select d+50 from td;
insert into td(d) select d+60 from td;
insert into td(d) select d+70 from td;
insert into td(d) select d+80 from td;
insert into td(d) select d+90 from td;

insert into td(d) select d+100 from td;
insert into td(d) select d+200 from td;
insert into td(d) select d+300 from td;
insert into td(d) select d+400 from td;
insert into td(d) select d+500 from td;
insert into td(d) select d+600 from td;
insert into td(d) select d+700 from td;
insert into td(d) select d+800 from td;
insert into td(d) select d+900 from td;

insert into td(d) select d+1000 from td;
insert into td(d) select d+2000 from td;
insert into td(d) select d+3000 from td;
select count(*) from td;

select sum(d) over (order by d rows between 10 preceding and 10 following) from td limit 10;
select avg(d) over (order by d range between 2 preceding and 2 following) from td limit 10;
select d,min(d) over (partition by d%7 order by d rows  between 2 preceding and 1 following) from td limit 10;
drop table td;
```

**Comment by sukki37** [comment]
Another case:

- 4000w rows

`select vehicle_id from real_time_position group by vehicle_id;` cost 7.3s

`select vehicle_id, longitude as lastLongitude, latitude as lastLatitude from (
        select vehicle_id,longitude,latitude,ROW_NUMBER() OVER (PARTITION BY vehicle_id ORDER BY time_stamp DESC) as
        time_rank
        from real_time_position
        ) tmp where time_rank = 1;` cost 82s

- 800w rows

`select vehicle_id from real_time_position group by vehicle_id;` cost 0.088s

`select vehicle_id, longitude as lastLongitude, latitude as lastLatitude from (
        select vehicle_id,longitude,latitude,ROW_NUMBER() OVER (PARTITION BY vehicle_id ORDER BY time_stamp DESC) as
        time_rank
        from real_time_position
        ) tmp where time_rank = 1;` cost 8s


DDL:
```
CREATE TABLE `real_time_position` (
`location_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '位置id',
`vehicle_id` VARCHAR(255) DEFAULT null COMMENT '车辆id',
`longitude` VARCHAR(64) DEFAULT null COMMENT '经度',
`latitude` VARCHAR(64) DEFAULT null COMMENT '纬度',
`time_stamp` BIGINT DEFAULT null COMMENT '记录位置信息的时间戳',
`distance` DOUBLE DEFAULT null COMMENT '距离',
`area` VARCHAR(64) DEFAULT null COMMENT '省份',
UNIQUE KEY `location_id` (`location_id`)
) COMMENT='车辆实时位置表';
```

If you need some real data, pls feel free to contact @aronchanisme or me.

**Comment by iamlinjunhong** [comment]
开发 #11565 中

**Comment by iamlinjunhong** [comment]
开发 https://github.com/matrixorigin/matrixone/issues/11565 中

**Comment by iamlinjunhong** [comment]
开发 https://github.com/matrixorigin/matrixone/issues/11565 中

**Comment by iamlinjunhong** [comment]
开发 https://github.com/matrixorigin/matrixone/issues/11565 中

**Comment by iamlinjunhong** [comment]
开发 https://github.com/matrixorigin/matrixone/issues/11565 中

**Comment by iamlinjunhong** [comment]
开发 https://github.com/matrixorigin/matrixone/issues/11565 中

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
处理中

**Comment by iamlinjunhong** [comment]
处理中

**Comment by iamlinjunhong** [comment]
处理中

**Comment by iamlinjunhong** [comment]
bvt case：select avg(d) over (order by d range between 2 preceding and 2 following) from td limit 10; 与mysql 相比
<img width="1384" alt="截屏2023-11-21 15 15 14" src="https://github.com/matrixorigin/matrixone/assets/49111204/28c110b6-8907-4092-828d-1ce26ac8f5d9">

**Comment by iamlinjunhong** [comment]
左边mo， 右边mysql
<img width="2787" alt="截屏2023-11-21 15 21 26" src="https://github.com/matrixorigin/matrixone/assets/49111204/32983947-3c37-4c98-9783-085a6e1c6127">

**Comment by iamlinjunhong** [comment]
对 frame 有 range 的窗口函数。mo 很慢，因为现在调用的是聚合框架，sql：select avg(d) over (order by d range between 2 preceding and 2 following) from td limit 10; mo需要几个小时，mysql 需要三十几秒。在下个版本中优化，建议建个新的issue

**Comment by iamlinjunhong** [comment]
sql：select vehicle_id, longitude as lastLongitude, latitude as lastLatitude from ( select vehicle_id,longitude,latitude,ROW_NUMBER() OVER (PARTITION BY vehicle_id ORDER BY time_stamp DESC) as time_rank from real_time_position ) tmp where time_rank = 1;  数据量：2000w （左边mo， 右边mysql）

<img width="2112" alt="截屏2023-11-21 15 37 10" src="https://github.com/matrixorigin/matrixone/assets/49111204/6efff286-23b0-4eb6-b168-2000dbf54dc6">
