### ISSUE TITLE
[Bug]: data race in catalog cache

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10386]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This data race may crash the mo server. It only happens during the replay of logtail after reconnecting.

<img width="1352" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/4a5a811d-dc39-497c-8b98-af9c8f2ad02e">

### Steps to Reproduce

```Markdown
Latest commit id: 6200380f435c5dd6b7e211f0ed80247a3a861085

Mock 1/1000 logtail push failure rate:
In: pkg/vm/engine/tae/logtail/service/session.go

func (s *morpcStream) write(
    ctx context.Context, response *LogtailResponse,
) error {
    if rand.Intn(10000) > 9990 {
        return moerr.NewInternalErrorNoCtx(fmt.Sprintf("random error for test"))
    }



make debug
run tpcc 10-50
```

**Comment by Morranto** [comment]
working on #10656  and group_concat

**Comment by Morranto** [comment]
need to discuss with  @m-schen  and make something clear

**Comment by Morranto** [comment]
已提pr
