### ISSUE TITLE
[Bug]: data race in jsonPlanHandler

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10382]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1087" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/87f617f9-360f-4720-a0f9-54e3d448cdff">

### Steps to Reproduce

```Markdown
Latest commit: 6200380f435c5dd6b7e211f0ed80247a3a861085
make debug
run tpcc 10-10 at local
```

**Comment by gavinyue** [comment]
Taking a look.

**Comment by gavinyue** [comment]
用这个issue 统一track:
https://github.com/matrixorigin/matrixone/issues/12432
然后这个PR已经解决： https://github.com/matrixorigin/matrixone/pull/12619
