### ISSUE TITLE
[Feature Request]: support snapshot-read and snapshots management

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10397]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Support snapshot-read and snapshots management
```

### Describe the feature you'd like

1. We need to support snapshot read
2. How to manage snapshots:
    1) Store 2) GC 3) Access

**Comment by lacrimosaprinz** [comment]
Related documentation:
@dengn pls review and check 👇🏻
- [Transactions/common-transaction-overview/]: add the concept explanation of snapshot-read
- [Transactions/matrixone-transaction-overview/isolation-level/]: add the content of snapshot-read, include an overview of snapshot-read and examples
- [Transactions/matrixone-transaction-overview/how-to-use/]: add the content of how to use the snapshot-read with the optimistic transactions or pessimistic transactions.
- Releasenote: add new feature of snapshot-read

**Comment by dengn** [comment]
not quite sure about the user behavior about this feature. 
1. Is it a feature for users? If yes, how is it going to be used?
2. Is it used for users to read older version of data?

**Comment by dengn** [comment]
> not quite sure about the user behavior about this feature.
> 
> 1. Is it a feature for users? If yes, how is it going to be used?
> 2. Is it used for users to read older version of data?

This is not a feature for users. Doc has nothing to edit.

**Comment by florashi181** [comment]
this is a sub task of https://github.com/matrixorigin/matrixone/issues/11492

**Comment by triump2020** [comment]
doc :  https://github.com/triump2020/MO-Docs/blob/main/20240103-lofi-snapshot_read.md
