### ISSUE TITLE
[Enhancement]: optmize checkpoint implementation

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10395]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Refactor checkpoint implementation
```

### Why is this needed ?

1. Memory usage optimization
2. Change the Read/Write implementation
3. Change the checkpoint storage layout

**Comment by sukki37** [comment]
The PR related to this issue has been merged. Could you please confirm whether the issue has been resolved?  @XuPeng-SH
