### ISSUE TITLE
[Bug]: cnclient panic

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10410]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6c5113756fbb04982cffc8d2b7d0697c9d6ffdf7 (main branch)
- Hardware parameters:amd
- OS type:ubuntu
- Others:
```

### Actual Behavior

pengzhen@pengzhen:~/Documents/matrixone$ ./mo-service -debug-http 127.0.0.1:8123 -launch etc/launch-tae-CN-tae-DN/launch.toml > log.txt 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x202ce1c]

goroutine 1418 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice/cnclient.IsCNClientReady()
	/home/pengzhen/Documents/matrixone/pkg/cnservice/cnclient/client.go:50 +0x3c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc005449040, 0xc003db0900)
	/home/pengzhen/Documents/matrixone/pkg/sql/compile/scope.go:186 +0x49
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0xc000654fb0?)
	/home/pengzhen/Documents/matrixone/pkg/sql/compile/scope.go:122 +0x2f
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/home/pengzhen/Documents/matrixone/pkg/sql/compile/scope.go:121 +0x1f8

### Expected Behavior

boot success

### Additional information

reproduce easily

**Comment by daviszhen** [comment]
这个版本上就启动不了

**Comment by daviszhen** [comment]
我在这个版本上 https://github.com/matrixorigin/matrixone/issues/10212#issuecomment-1622048610
也启动不了。

<img width="1181" alt="企业微信截图_cb0356e6-766b-4235-bd47-59bf90f716ef" src="https://github.com/matrixorigin/matrixone/assets/60595215/679dd68c-2040-4e42-a686-7e35fb7a3f9d">

**Comment by reusee** [comment]
这个bug已经在这个commit修复：https://github.com/matrixorigin/matrixone/commit/5ef2f145466e77291a0d068c6907efacb4c1e7e4

不知道为啥，在这个commit里，又被改回去了：https://github.com/matrixorigin/matrixone/commit/52fc64d7fcbc4ef62b322fc88f33b10e1a22a0d2#diff-c50401342b213f7d7d76804f2d6fee4879435e86ca055d350e530276cde49fde

如果大的重构一步步来，或者严谨一点，代码有冲突好好解决，就不会出现这种事情。

**Comment by jensenojs** [comment]
> 这个bug已经在这个commit修复：[5ef2f14](https://github.com/matrixorigin/matrixone/commit/5ef2f145466e77291a0d068c6907efacb4c1e7e4)
> 
> 不知道为啥，在这个commit里，又被改回去了：[52fc64d#diff-c50401342b213f7d7d76804f2d6fee4879435e86ca055d350e530276cde49fde](https://github.com/matrixorigin/matrixone/commit/52fc64d7fcbc4ef62b322fc88f33b10e1a22a0d2#diff-c50401342b213f7d7d76804f2d6fee4879435e86ca055d350e530276cde49fde)
> 
> 如果大的重构一步步来，或者严谨一点，代码有冲突好好解决，就不会出现这种事情。

远宁哥把它改成用Lock的方式保护了，所以也不好说就是岳声哥修复的data race的问题

**Comment by reusee** [comment]
atomic.Pointer 的修正，会判断是不是 nil，不会出现 nil pointer deref 问题。用 lock 的修正的问题是那个结构没有初始化，就调用了 Lock 方法，就出现了 nil pointer deref.

**Comment by jensenojs** [comment]
啊这，那我搞一下（

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/matrixone/pull/10688

**Comment by daviszhen** [comment]
it was fixed.
