### ISSUE TITLE
[Bug]: SYSBENCH OLTP perf decrease(insert/delte) more than 25% on eks and Standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10416]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 218775ced
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SYSBENCH OLTP perf decrease(insert/delte) on eks and Standlone mode. 
for commit : 615ea47cd

the sysbennch prepared insert tps is:
<img width="1268" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/0f4ec566-8722-436f-a64b-d7559ae287c8">

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5431885832/jobs/9885000975

but for the commit: 218775ced
the sysbennch prepared insert tps is:
<img width="1315" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/4390263f-decf-423e-ad7a-6157eb158c00">

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5446468275/jobs/9907435233

and in the meanwhile, for commit : 218775ced on the eks, the delete and insert with autoincremental pk, the tps also  decreased more than 25%:
<img width="1362" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d8f971b5-f6a4-48df-adff-d0f46942fe33">

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5431885832/jobs/9885000975

**Comment by LeftHandCold** [comment]
This bug has nothing to do with mo code. The root cause is：https://github.com/matrixorigin/mo-load/commit/5a95f8c185a1a44830266d837d1925a2de37cceb

**Comment by aressu1985** [comment]
close
