### ISSUE TITLE
[Feature Request]: LOAD DATA from Aliyun with both OSS and ARN

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10429]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support LOAD DATA from Aliyun with OSS and ARN.
The syntax stays the same from S3 and parallel load needs to be implemented.
s3option including the autherization string of Aliyun.

https://doc.weixin.qq.com/doc/w3_AZUAugYIAOcZjIB6zykTrK9Sv4hLb?scode=AJsA6gc3AA8E0qSOfUAZUAugYIAOc

**Comment by lacrimosaprinz** [comment]
Related documentation:
@dengn pls review and check 👇🏻
- feature list: add new content of [data import and export]
- bulk-load/load-s3/：add new content about the authorization string of Aliyun.

**Comment by dengn** [comment]
Not very clear about why this is needed? and how is it used? is it a MO-cloud only or general feature?

**Comment by reusee** [comment]
云平台需要的rrsa验证方式，aws sdk不支持
计划直接实现原生sdk和接口支持阿里云，所以当前迭代只支持key id/key secret方式的验证

**Comment by daviszhen** [comment]
跟 @jianwan0214 讨论过。可以转测试了。

**Comment by lacrimosaprinz** [comment]
docs edited:
https://github.com/matrixorigin/matrixorigin.io.cn/pull/622
https://github.com/matrixorigin/matrixorigin.io/pull/473

**Comment by dengn** [comment]
> docs edited: [matrixorigin/matrixorigin.io.cn#622](https://github.com/matrixorigin/matrixorigin.io.cn/pull/622) [matrixorigin/matrixorigin.io#473](https://github.com/matrixorigin/matrixorigin.io/pull/473)

I think it's not clear at all to edit doc. 
We actually already supported Load from aliyun OSS longtime ago. 

-So what on earth does this feature implement? 
-I can see there is an ARN thing, is it only about that? 
-if it's the case, is it a general for AWS, aliyun, tencent cloud? or only aliyun has been implemented?

**Comment by florashi181** [comment]
@LiSong0214 @domingozhang let's verify the adjusted scope of this issue is ok to meet expectations before testing.

**Comment by LiSong0214** [comment]
该 issue 的功能范围是实现在阿里云上通过 ARN 的方式访问用户自己的 OSS 数据，请问转测试前有自测通过吗？据我了解应该还卡在实现 阿里云 sdk 的 feature （https://github.com/matrixorigin/MO-Cloud/issues/706）上，我建议以使用角度来鉴别该 issue 的完成程度，而不是代码角度

**Comment by daviszhen** [comment]
需要这两个issue做完之后，继续验证。才能确认完成。
https://github.com/matrixorigin/matrixone/issues/10661
https://github.com/matrixorigin/MO-Cloud/issues/706

**Comment by domingozhang** [comment]
ARN will be supported by @reusee next release

**Comment by daviszhen** [comment]
需要关联： https://github.com/matrixorigin/matrixone/issues/10661

**Comment by reusee** [comment]
阿里云sdk已集成，支持role-arn身份验证

**Comment by florashi181** [comment]
waiting for #10661

**Comment by reusee** [comment]
#10661 was done last week.

**Comment by Ariznawlll** [comment]
If the parameters are correct, the result is correct.
<img width="1736" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cf1d28ec-8bda-4706-b26c-1c539530b51e">

If the parameters are incorrect, it will cause panic.
issue:https://github.com/matrixorigin/matrixone/issues/12194
<img width="1730" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/bca204bf-2c03-4e2a-a886-64107987786e">


test done!

**Comment by reusee** [comment]
fixes for OIDC credentials merged: https://github.com/matrixorigin/matrixone/commit/0c57272dcbe0ae712cbe19abe5fb72e3f0a6439e

**Comment by reusee** [comment]
rrsa/oidc 似乎并不能和 external id 共存，需要看看如何解决

**Comment by aressu1985** [comment]
https://github.com/matrixorigin/matrixone/issues/13906
存在这个问题，特性不可用，以这个issue来跟踪吧
