### ISSUE TITLE
[Bug]: 0.8.0 linux binary package doesn't work

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10420]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.8.0 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

I'm using a 2c4g Debian11.1 machine, linux kernel version "Linux version 5.10.0-19-amd64"

1. download linux binary release file in https://github.com/matrixorigin/matrixone/releases/download/v0.8.0/mo-v0.8.0-linux-amd64.zip
2. unzip the file.
3. start MO by `./mo-service --daemon --launch ./etc/launch-tae-CN-tae-DN/launch.toml &> test.log &`
4. it failed to start with the log
```
./mo-service: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./mo-service)
./mo-service: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./mo-service)
```

**Comment by guguducken** [comment]
Test Pass, please check again https://github.com/matrixorigin/matrixone/releases/download/v0.8.0/mo-v0.8.0-linux-amd64.zip @dengn

**Comment by dengn** [comment]
fixed.
