### ISSUE TITLE
[Bug]: time consume 、memory、IOInput、IOOutput is 0 in system.statement_info.

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#10437]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9168da8a5d27d331b5af3e343deb864c926fd015
- Hardware parameters:
- OS type:MAC OS
- Others:
```

### Actual Behavior

1. /* cloud_user */select * from system.statement_info;
2. select last_query_id();
3. select * from system.statement_info where statement_id='$last_query_id';
the stats is [1,0,0,0,0].

### Expected Behavior

the results of stats shouldn't be all 0.

### Steps to Reproduce

```Markdown
as Actual Behavior
```

**Comment by xzxiong** [comment]
1. 返回了 `[1,0,0,0,0]` 是因为 聚合后的数据 应 ExecPlan为空，丢失了
2. 返回了 `[1,234234,0,0,0]` 其中的 memorySize为空，是因为计算时，duration 没有被赋值导致的。

**Comment by fengttt** [comment]
If it is aggregated, you should not be able to read stats out.   However it is tagged /* cloud user */ therefore it should not have been aggregated.

**Comment by xzxiong** [comment]
> If it is aggregated, you should not be able to read stats out. However it is tagged /* cloud user */ therefore it should not have been aggregated.

as PRD defined in https://github.com/matrixorigin/MO-Cloud/issues/891, 
After aggregation, valid `stats` are still required for CU calculation.

**Comment by xzxiong** [comment]
@heni02 这里是 stats 相关的bug issue. 麻烦一起验证一下吧~

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
stats value is  [1,21999,6463.278,0,0] ,not [1,0,0,0,0]
confirm,closed
commit id:1c70e2f03c6577ce75bfe2119b09be7180f55ab5
![image](https://github.com/matrixorigin/matrixone/assets/113406637/896d7d48-b35f-4bb5-b292-c1fb446273c5)
