### ISSUE TITLE
[Bug]: Panic when using group-by on metadata scan result

### ISSUE THREAD

**Issue by dongdongyang33** [matrixorigin/matrixone#10431]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): `ba2675160b90f574e7eb9f3936202d4ba305bbd6`
- Hardware parameters:
- OS type:
- Others:
```

execute SQL like: 
`select col_name, sum(compress_size) from metadata_scan('tpch_1g.lineitem', '*') m group by col_name;`

### Actual Behavior

2023/07/05 16:23:40.129608 +0800 ERROR vm/vm.go:57 error: internal error: panic runtime error: slice bounds out of range [:1280] with capacity 1152:
runtime.goPanicSliceAcap
        /usr/local/go/src/runtime/panic.go:139
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).UnionBatch
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/container/vector/vector.go:2247
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).batchFill
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/sql/colexec/group/group.go:487
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).processHStr
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/sql/colexec/group/group.go:406
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).processWithGroup
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/sql/colexec/group/group.go:340
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.Call
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/sql/colexec/group/group.go:121
github.com/matrixorigin/matrixone/pkg/vm.Run
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/vm/pipeline/pipeline.go:125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/sql/compile/scope.go:81
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /Users/qinxuanwu/repo/myrepo/matrixone/pkg/sql/compile/scope.go:114
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1172 {"span": {"trace_id": "3f0a99e6-1b0d-11ee-ac44-26dd28356ef3", "kind": "statement"}}

### Expected Behavior

show the result normally

**Comment by dongdongyang33** [comment]
in process

**Comment by dongdongyang33** [comment]
waiting pr merge

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
<img width="700" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b61b54ef-5529-479c-a63f-5049eede3d17">

Verified!
