### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode：autocommit isolation error.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10444]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:3dc4f433e986d3227959b6e3c0ecaaf195d13b7e
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

[error.txt](https://github.com/matrixorigin/matrixone/files/11957196/error.txt)

### Steps to Reproduce

```Markdown
start mo；
in mo-tester：./run.sh -n -g -p /Users/ariznawl/matrixone/test/distributed/cases/pessimistic_transaction/autocommit_isolation.sql
```

### Additional information

开启悲观事务：
[cn.txn]
mode = "Pessimistic"
isolation = "RC"

开启cn去重
[cn]
primary-key-check = true

开启DN增量去重
[dn.Txn]
incremental-dedup = true

**Comment by zhangxu19830126** [comment]
fixed by #10423

**Comment by Ariznawlll** [comment]
testing.

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
Verified!
