### ISSUE TITLE
[Feature Request]: Skip dup check with update 

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10447]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
In case of an update that is NOT modifying any of the primary key columns, we do not need to check primary key conflict.   This should be the majority of update statement.
```

### Describe the feature you'd like

Check, skip the step in plan.

**Comment by w-zr** [comment]
@ouyuanning is now working on this issue.
