### ISSUE TITLE
[Bug]: dn out of memory on daily regression on eks with 3*cn during systench oltp test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10440]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ba88fe7
- Hardware parameters:
3*CN: EC2 m6gd.4xl 16C 64G
1*DN: EC2 m6gd.4xl 16C 64G
3*LOG: EC2 m5.xlarge 4C 16G
- OS type:
- Others:
CN MEMCAHCE: 12G 
CN DISKCACHE: 800G
SSD
```

### Actual Behavior

n daily regression on eks with 3*cn during sysbench oltp test, the mem of DN node is basically depleted.
<img width="1903" alt="WeChatWorkScreenshot_11f79262-42d9-44b3-994f-9025671f1113" src="https://github.com/matrixorigin/matrixone/assets/47846308/0ec312e3-aacd-46d7-b82d-bb34d0e6fbe3">

<img width="1920" alt="WeChatWorkScreenshot_61a02652-d2d0-4a60-bd7a-03734412964c" src="https://github.com/matrixorigin/matrixone/assets/47846308/e49dfacb-9f9a-4122-bcfe-00b8d55dd8e8">

and it cost the dn node crashed.
<img width="703" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/2bedc5b2-2ef8-4b9a-bf66-b02cfe4e23b0">

the job link is:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5456889306/jobs/9933171479

**Comment by aressu1985** [comment]
the profile will be uploaded soon

**Comment by aressu1985** [comment]
[dn-profile-10.0.189.79.zip](https://github.com/matrixorigin/matrixone/files/11957051/dn-profile-10.0.189.79.zip)

**Comment by LeftHandCold** [comment]
testing #10469

**Comment by LeftHandCold** [comment]
fixed, let's wait and see for a few days.

**Comment by aressu1985** [comment]
fixed
