### ISSUE TITLE
[Bug]: invalid memory address or nil pointer dereference in GetTableMeta

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#10459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-ba88fe74
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/28624654/57c629e2-dfa2-4cc3-a6bd-ae306fd86206)

When `StorageUsage` task runs `SHOW ACCOUNTS;`, panic occurred.
See https://github.com/matrixorigin/matrixone/blob/main/pkg/util/metric/cron_task.go#L138

**Comment by xzxiong** [comment]
@LeftHandCold  version: nightly-ba88fe74

**Comment by LeftHandCold** [comment]
checkpoint 已经重构了。
