### ISSUE TITLE
[Enhancement]: support dump trace info with system go routine

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#10453]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
support dump trace info with system go routine.
```

**Comment by xzxiong** [comment]
what it needs is pprof/trace info
result as `curl -o trace.out http://127.0.0.1:6060/debug/pprof/trace?seconds=10`

**Comment by fengttt** [comment]
I guess the ask is to dump that from inside go code -- I believe we can do that already?   When span is too long and context timeout.   Correct?

**Comment by xzxiong** [comment]
> I guess the ask is to dump that from inside go code -- I believe we can do that already? When span is too long and context timeout. Correct?

the missing part is dumping pporf/trace info, 
right now, we already support  dumping goroutine, heap, cpu pprof.

**Comment by xzxiong** [comment]
@jianwan0214 merged, pls check
