### ISSUE TITLE
Default value of max-entry-bytes is too small

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1045]
#### Can be reproduced ?
Yes

#### Steps:
1. Make build and start database service.
2. Import data but failed. Notified "raft entry is too large"
3. Modify  max-entry-byte from 1MB to a larger one and then worked.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by daviszhen** [comment]
max-size-per-msg = "" 
max-entry-bytes = "300MB"
