### ISSUE TITLE
[Bug]: select for update: delete wait lock  more than 2 hours, after the lock is released delete reported ExpectedEOB

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10463]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):48a289863740d954b9e48fbc889fc100a1f85198
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

delete wait lock  more than 2 hours, after the lock is released delete reported ExpectedEOB
![image](https://github.com/matrixorigin/matrixone/assets/113406637/edd944de-4380-4f3b-afc7-1f08140cb700)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/2540b40d-ed45-4a54-9671-3d46a3c33a65)

### Steps to Reproduce

```Markdown
session1:
begin;
select * from su_03 where c3 in(50,70) for update;
session2:
delete from su_03 where c3 between 10 and 70;
then wait for more than 2hours
session1:
commit；
```

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
昨天测了一次等1个多小时的。这个48a289863740d954b9e48fbc889fc100a1f85198 有发现有w-w错误。但是没有重现 ExpectedEOB

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
今天用最新的main测试。没有复现 ExpectedEOB 的错误。
但是会报 r-w 冲突。明天继续看一下

**Comment by ouyuanning** [comment]
as confirm with @triump2020 
root cause should be : the txn  timeout, then some page cache missed.

**Comment by triump2020** [comment]
root cause :  transferHashPage is gced .

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
Low priority

**Comment by triump2020** [comment]
progress on

**Comment by triump2020** [comment]
@sukki37 @heni02   After communicating with @XuPeng-SH ,  this issue  will be addressed  in next release, pls lower the prioritiy.

**Comment by heni02** [comment]
This issue does not affect the basic function of select for update, and can be downgraded to s1

**Comment by sukki37** [comment]
tracked by https://github.com/matrixorigin/matrixone/issues/11815
