### ISSUE TITLE
[Subtask]: support alter column type & primary key

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#10466]
### Parent Issue

#10380

### Detail of Subtask

support more alter operation like alter column type & primary key

**Comment by domingozhang** [comment]
1. alter column type, and order
2. add/drop primary key

**Comment by Ariznawlll** [comment]
alter table modify column
alter table change column
alter table rename column
alter table add/drop primary key
test done!

**Comment by domingozhang** [comment]
@aressu1985 please help to close it
