### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: Duplicate primary key rather than inserted successfully.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10472]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c444a3e202e8155ca9ec54fb90137c563d8305f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
<img width="1168" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9fbedea3-3b25-4eae-b464-3cd5bab2e5c7">
mysql:
<img width="1154" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/eac9c572-00ca-4b23-a222-47ddc77bbe1b">

**配置**
开启悲观事务：
[cn.txn]
enable-sacrificing-freshness = true
enable-cn-based-consistency = false
mode = "Pessimistic"
isolation = "RC"

开启cn去重
[cn]
primary-key-check = true

开启DN增量去重
[dn.Txn]
incremental-dedup = true

### Steps to Reproduce
Scenario 1：
```Markdown
drop table if exists test_11;
create table test_11 (c int primary key,d int);
Insert into test_11 values(1,1);
Insert into test_11 values(2,2);

set @@autocommit=0;
select * from test_11;
-- @session:id=1{
select * from test_11;
Insert into test_11 values(50,50);
select * from test_11;
-- @session}

Insert into test_11 values(50,50);
select * from test_11;
commit;
set @@autocommit=1;
-- @session:id=1{
select * from test_11;
-- @session}
select * from test_11;
```
Scenario 2:
```
create table ct_07(a int,b varchar(25),c date, d double,primary key(a,c));
insert into ct_07 values (1,'901','2011-09-29',0.01),(2,'187','2011-09-29',1.31),(3,'90','2111-02-09',10.01);
begin;
insert into ct_07 values (3,'90','2111-02-09',10.01);
insert into ct_07 values (4,'11','2011-09-29',7.00),(2,'567','2011-09-29',1.31),(4,'90','2011-09-29',89.3);
select * from ct_07;
commit;
select * from ct_07;
```

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by Ariznawlll** [comment]
<img width="1205" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d2eb725d-02e8-426e-bd94-f6e09272354f">
Verified!
