### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: create table  already exists rather waiting for lock.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10471]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:1c444a3e202e8155ca9ec54fb90137c563d8305f
```

### Actual Behavior

mo:
<img width="1162" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a6ec6b15-8129-4980-87c9-1b223dbbbfc8">
mysql:
<img width="1181" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e1824f6a-ca5f-48a7-9178-0d10b1ff581a">

**配置**
开启悲观事务：
[cn.txn]
enable-sacrificing-freshness = true
enable-cn-based-consistency = false
mode = "Pessimistic"
isolation = "RC"

开启cn去重
[cn]
primary-key-check = true

开启DN增量去重
[dn.Txn]
incremental-dedup = true

### Steps to Reproduce

```Markdown
start transaction;
create table test_12(col1 int primary key,col2 varchar(25));
insert into test_12 values(1,'a'),(2,'b');
-- @session:id=2&user=sys:dump&password=111
select * from test_12;
use atomicity;
create table test_12(col1 int,col2 varchar(25));
insert into test_12 values (90,'tt');
-- @session
select * from test_12;
show create table test_12;
commit;
show create table test_12;
select * from test_12;
drop table test_12;
```

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by domingozhang** [comment]
because ddl behavior is different from mysql, this is not a bug and can be closed
