### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: MO does not return result in 120000 ms when insert into table with a foreign key column.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10489]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c444a3e202e8155ca9ec54fb90137c563d8305f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo：
<img width="1180" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e9d854fb-b944-4506-a3f4-e291ae5ac76e">

mysql：
<img width="1162" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/bb612274-2fb1-4857-b82a-0e0881ad5680">

**配置**
开启悲观事务：
[cn.txn]
enable-sacrificing-freshness = true
enable-cn-based-consistency = false
mode = "Pessimistic"
isolation = "RC"

开启cn去重
[cn]
primary-key-check = true

开启DN增量去重
[dn.Txn]
incremental-dedup = true

### Steps to Reproduce

```Markdown
drop table if exists atomic_table_12_2;
drop table if exists atomic_table_13;
create table atomic_table_12_2(c1 int primary key,c2 varchar(25));
insert into atomic_table_12_2 values (3,"a"),(4,"b"),(5,"c");
create table atomic_table_13(c1 int primary key,c2 varchar(25));
insert into atomic_table_13 values (3,"d"),(4,"e"),(5,"f");
begin;
alter table atomic_table_13 add constraint ffa foreign key f_a(c1) references atomic_table_12_2(c1);
-- @session:id=2&user=sys:dump&password=111
show create table atomic_table_12_2;
insert into atomic_table_13 values (8,"h");
select * from atomic_table_13;
-- @session
insert into atomic_table_13 values (6,"h");
commit;
show create table atomic_table_13;
```

**Comment by domingozhang** [comment]
ALTER TABLE in a transaction will make table lock in mo, not autocommit instead.
so that this can be accepted.
