### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: prompt duplicate entry for key at commit time.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10485]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c444a3e202e8155ca9ec54fb90137c563d8305f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
<img width="589" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0594d281-8492-42c0-a221-a48fd40f85ed">

mysql:
<img width="544" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/979a7bed-1804-492a-a29c-1248b7903a55">

**配置**
开启悲观事务：
[cn.txn]
enable-sacrificing-freshness = true
enable-cn-based-consistency = false
mode = "Pessimistic"
isolation = "RC"

开启cn去重
[cn]
primary-key-check = true

开启DN增量去重
[dn.Txn]
incremental-dedup = true

### Expected Behavior

Should prompt duplicate entry for key at insert time, not at commit time.

### Steps to Reproduce

```Markdown
create table ct_06(a bigint,b varchar(25),c int, d varchar(25),primary key(a),unique index c(c),key b(b),key d(d));
start transaction ;
insert into ct_06 select 5678,'high',487,'comment test';
-- @bvt:issue#6949
insert into ct_06 select 5679,'lower',487,'define';
-- @bvt:issue
insert into ct_06 values (897,'number',908,'run tools'),(898,'string',908,'ffff'),(899,'string',918,'while'),(900,'string',948,'word file'),(901,'string',902,'oooo'),(902,'string',87,'dddd'),(903,'string',87,'eeee');
select * from ct_06;
commit;
select * from ct_06;

begin;
insert into ct_06 values (500,'number1',908,'ooooffff');
-- @session:id=1{
start transaction ;
-- @wait:0:commit
insert into ct_06 values (501,'number2',908,'zzzztttt');
commit;
select * from ct_06;
-- @session}
commit;
select * from ct_06;
```

**Comment by fengttt** [comment]
What should be the right value for these two?
```
enable-sacrificing-freshness = true
enable-cn-based-consistency = false
```

@zhangxu19830126 please review https://github.com/matrixorigin/matrixone/pull/10480 and we merge this ASAP, so people should not tweak these params any more.

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
> What should be the right value for these two?
> 
> ```
> enable-sacrificing-freshness = true
> enable-cn-based-consistency = false
> ```
> 
> @zhangxu19830126 please review #10480 and we merge this ASAP, so people should not tweak these params any more.

default value should be "false", support extenal consistency. it means all transaction will start with `now` snapshotTS

**Comment by ouyuanning** [comment]
not repro. need confirm

**Comment by Ariznawlll** [comment]
<img width="1175" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8912fec2-60c5-443d-b8a3-7ed2e005e46b">

Verified!
