### ISSUE TITLE
[Feature Request]: mo_table_col_max和mo_table_col_min目前已经不报错了，但是希望统计数据的时间可以缩短到2分钟以内

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#10484]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
https://github.com/matrixorigin/matrixone/issues/9817
```

### Describe the feature you'd like

目前MOC对表的统计数据需要使用mo_table_col_max和mo_table_col_min，但对于新建表，统计数据的出现时间不能确定，目前MOC希望能把这个时间缩短到2分钟以内。

**Comment by daviszhen** [comment]
先搞清楚细节。

**Comment by sukki37** [comment]
trace by https://github.com/matrixorigin/matrixone/issues/10484
