### ISSUE TITLE
[Bug]: Insert in pessimistic mode is very slow.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10498]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/mojo/tree/main/go just run
```
!repro moc-956
```

This bug is from moc-956.   Except this time only repros on pessimistic mode.

**Comment by nnsgmsone** [comment]
正在处理中

**Comment by nnsgmsone** [comment]
还未处理，在处理悲观事务重复主键的问题

**Comment by nnsgmsone** [comment]
发现约束的filter没有下推，修改plan解决这个问题。

**Comment by nnsgmsone** [comment]
pr已经合入，等待验证

**Comment by nnsgmsone** [comment]
下推过滤条件后，sysbench 100w的insert性能已经达到了1.1w，乐观是1.4w。。造成这个的差距应该是dn用的bloomfilter过滤，cn是点查。对于cn而言，因为构建bloomfilter需要读取s3的数据，会导致消费速度变慢，我暂时没有很好的办法。。田博士有啥想法吗 @fengttt

**Comment by fengttt** [comment]
In main is still extremely slow.    I don't think the PR (which PR anyway?) fixed anything.    My rerpo still takes 15s to insert 1000 rows.

**Comment by fengttt** [comment]
// Fix txn mode various config, simply override
	if txn.GetTxnMode(c.Txn.Mode) == txn.TxnMode_Pessimistic {
		c.Txn.EnableSacrificingFreshness = true
		c.Txn.EnableCNBasedConsistency = true
		c.Txn.EnableRefreshExpression = false
	}

Even with these, insert 1000 rows is still 11s.   Which is about 50-100x times slower.

**Comment by nnsgmsone** [comment]
这个场景没有做主键冲突的，下面的是执行计划：
```
| QUERY PLAN                                            |
+-------------------------------------------------------+
| Insert on repro.tbl_0                                 |
|   ->  Lock                                            |
|         ->  PreInsert on repro.tbl_0                  |
|               ->  Project                             |
|                     ->  Project                       |
|                           ->  Values Scan "*VALUES*"  |
+-------------------------------------------------------+

```
不过确实非常慢，应该存在其他的问题，我来定位处理一下。

**Comment by nnsgmsone** [comment]
经过定位，应该是lock的延迟太大了，继续定位中:
```
![截图 2023-07-15 16-25-31](https://github.com/matrixorigin/matrixone/assets/31609524/4f455cb3-ed14-4f58-8d9d-11204de6e7d7)

```

**Comment by nnsgmsone** [comment]
虽然这个场景的lock应该是可以删除的(自增列），不过lock的开销有点大，确实需要处理一下。

**Comment by nnsgmsone** [comment]
经过分析，目前存在两个问题，第一个问题也是最严重的问题就是lockop在没有冲突的情况下，需要等待logtail达到lockTs才可以，然后因为这个表本质上没有任何修改，所以都需要等待一个心跳的时间，这个会导致每次操作的延迟居高。。具体的代码位置为: https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/lockop/lock_op.go#L418。我觉得这个场景需要好好讨论一下。 @fengttt ，这不是一个单纯的bug，这应该是一个协议设计的问题。。

**Comment by nnsgmsone** [comment]
第二个问题还在定位具体的原因，只知道也是延迟很大，延迟的本质继续调研中。

**Comment by nnsgmsone** [comment]
![截图 2023-07-17 16-48-48](https://github.com/matrixorigin/matrixone/assets/31609524/fa395749-c97e-41d7-9e80-f1d2714f1356)

**Comment by nnsgmsone** [comment]
另外的开销本质都是https://github.com/matrixorigin/matrixone/blob/main/pkg/txn/client/operator.go#L281引起的，本质也是在等logtail。。

**Comment by nnsgmsone** [comment]
fixed by #10730
