### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: insert into table shows internal error: temporary engine not init yet.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10491]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c444a3e202e8155ca9ec54fb90137c563d8305f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]   
[SCRIPT   FILE]: /Users/ariznawl/code/matrixone/test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
[ROW    NUMBER]: 52
[SQL STATEMENT]: insert into atomic_table_11 values (6,"a");
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
internal error: temporary engine not init yet.

[error.txt](https://github.com/matrixorigin/matrixone/files/11974389/error.txt)
[run.log](https://github.com/matrixorigin/matrixone/files/12013269/run.log)

**配置**
开启悲观事务：
[cn.txn]
enable-sacrificing-freshness = true
enable-cn-based-consistency = false
mode = "Pessimistic"
isolation = "RC"

开启cn去重
[cn]
primary-key-check = true

开启DN增量去重
[dn.Txn]
incremental-dedup = true

### Steps to Reproduce
in mo-tester
./run.sh -n -g -p /matrixone/test/distributed/cases/pessimistic_transaction

**Comment by Ariznawlll** [comment]
<img width="1188" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/387501e0-e2ab-4bf7-9616-198beec557da">
verified

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by ouyuanning** [comment]
reviewing

**Comment by Ariznawlll** [comment]
Verified!
