### ISSUE TITLE
[Subtask]: LOAD DATA from Aliyun with both OSS and ARN

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#10496]
### Parent Issue

#10429

### Detail of Subtask

please refer to parent issue.

**Comment by reusee** [comment]
S3 compatible interface of Aliyu already supported
RRSA and other credential providers are not supported by AWS SDK.
Further Aliyun support will be done in https://github.com/matrixorigin/matrixone/issues/10661 , not targeting the 1.0 milestone.
I don't think I can do anything at this moment.
