### ISSUE TITLE
[Bug]: W-W conflict in pessimistic mode

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 w-w conflict in pessimistic mode

### Steps to Reproduce

```Markdown
run tpcc in pessimistic mode
```

**Comment by fengttt** [comment]
I think this is is dup of #10502

**Comment by fengttt** [comment]
Not necessarily dup #10502.   Even if it is garbage, it is still locked garbage so it should not have w-w.    Need more investigation.

**Comment by zhangxu19830126** [comment]
maybe fixed

**Comment by zhangxu19830126** [comment]
还没有修复

**Comment by zhangxu19830126** [comment]
还没有修复

**Comment by Ariznawlll** [comment]
run bvt under pessimistic mode in ci today, there also occurs w-w conflict.
<img width="1426" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/bfaf54fa-e792-440a-b801-d1ffc223e643">
[cn-0.log](https://github.com/matrixorigin/matrixone/files/12078137/cn-0.log)
[cn-1.log](https://github.com/matrixorigin/matrixone/files/12078138/cn-1.log)
[dn.log](https://github.com/matrixorigin/matrixone/files/12078139/dn.log)

**Comment by zhangxu19830126** [comment]
ROWID相关的问题，需要继续修复

**Comment by zhangxu19830126** [comment]
fixed by #10859

**Comment by sukki37** [comment]
Hello @zhangxu19830126. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by Ariznawlll** [comment]
local test and ci-test has passed！
