### ISSUE TITLE
[Bug]: CN panic with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10500]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x20486b8]

goroutine 46977290 [running]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.(*Argument).Free(0xc1ddc877a0, 0x2ebb8c0?, 0x1)
        /opt/source/matrixone/pkg/sql/colexec/dispatch/types.go:104 +0x38
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).cleanup(0xc10cac5f38, 0xc1ebb7c280, 0x1)
        /opt/source/matrixone/pkg/vm/pipeline/types.go:101 +0x9d
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc10cac5f38, 0xc1ebb7c280)
        /opt/source/matrixone/pkg/vm/pipeline/pipeline.go:147 +0xec
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc026616dd0, 0xc0e0e72480)
        /opt/source/matrixone/pkg/sql/compile/scope.go:146 +0x6f4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
        /opt/source/matrixone/pkg/sql/compile/scope.go:117 +0x2f
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /opt/source/matrixone/pkg/sql/compile/scope.go:116 +0x3d8

### Steps to Reproduce

```Markdown
run tpcc in pessimistic mode
```

**Comment by sukki37** [comment]
@m-schen Could you kindly look at this one?

**Comment by dongdongyang33** [comment]
A parameter that needs to be initialized in the prepare() phase is used during cleanup() so we get panic
