### ISSUE TITLE
[Bug]: exec `select 1>0;` got 0x74727565 result

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#10507]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8870ea87a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

except val in (0, 1) or (false, true), mysql return val in (0, 1).

- situation 1
```
mysql> select 1 > 0;
+--------------+
| 1 > 0        |
+--------------+
| 0x74727565   |
+--------------+
1 row in set (0.00 sec)

mysql> select 0 > 1;
+--------------+
| 0 > 1        |
+--------------+
| 0x66616C7365 |
+--------------+
1 row in set (0.00 sec)
```
- situation 2
```
mysql> set @stats="[1,118334200,2911386337083,0,0]";
Query OK, 0 rows affected (0.00 sec)

mysql> select @stats, JSON_UNQUOTE(JSON_EXTRACT(@stats, '$[0]')) ver, JSON_UNQUOTE(JSON_EXTRACT(@stats, '$[0]')) > 0 gt_0;
+---------------------------------+------+------------+
| @stats                          | ver  | gt_0       |
+---------------------------------+------+------------+
| [1,118334200,2911386337083,0,0] |    1 | 0x74727565 |
+---------------------------------+------+------------+
1 row in set (0.00 sec)
```

**Comment by nnsgmsone** [comment]
赛赛帮忙处理一下把

**Comment by jensenojs** [comment]
<img width="1764" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ec95adfa-1365-4a4c-9afe-7c2649258d81">

在plan的阶段会把表达式的计算结果算完存储起来，这个结果是正确的，接着找

**Comment by jensenojs** [comment]
<img width="1278" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ab7a2b2f-fe1e-49b1-ab41-94a32be24d92">

图中ap.Func()是调用前端的回调函数将结果返回，可以看到在回调函数执行完后output算子内的bat仍然保存着正确的结果（顺便吐槽一下proc.PutBatch的命名）

接着追踪回调函数，发现了一个有点奇怪的问题，extractRowFromEveryVector也正确地把值给取出来了。
<img width="1482" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/2560ced4-1a5a-4675-92d1-a5a731f46052">

但是getDataFromPipeline并没有使用这个值，导致select 1 > 0 返回了无法理解的东西
<img width="1465" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/3307394f-0619-41dc-95f1-55c349726745">

**Comment by jensenojs** [comment]
剑哥帮忙跟踪了一下，是这个[pr](https://github.com/matrixorigin/matrixone/pull/10245)引入的，后面麻烦远宁哥帮忙看看

**Comment by xzxiong** [comment]
verified.
