### ISSUE TITLE
[Bug]: Fail to create table with ascending index

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#10515]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-7a45858e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [mo_cloud]> CREATE TABLE `operation` (`id` varchar(128) NOT NULL,`created_at` datetime(3) NULL,`statement_id` varchar(128) NOT NULL,`connection_id` bigint unsigned NOT NULL,`db` varchar(128) NOT NULL,`run_status` varchar(64) NOT NULL,`err_msg` text NOT NULL,`rows_affected` bigint,PRIMARY KEY (`id`),INDEX `idx_operation_created_at` (`created_at` asc));
ERROR 20101 (HY000): internal error: the index keypart does not support sorting
```

### Expected Behavior

The table is created successfully

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

### Additional information

It works in the previous commits.

**Comment by daviszhen** [comment]
次级索引不支持。“INDEX `idx_operation_created_at` (`created_at` asc)” 目前支持不了。

**Comment by qingxinhome** [comment]
The Mo indexing method can support sorting without reporting errors to be compatible with MySQL, but the internal function of Mo does not have a so-called sorting function @DanielZhangQD @daviszhen @tianyahui-python @heni02

**Comment by qingxinhome** [comment]
The issue has been resolved, please test and verify @DanielZhangQD @tianyahui-python @heni02 @LiSong0214

**Comment by DanielZhangQD** [comment]
Verified and passed with commit 56c7ccf60
