### ISSUE TITLE
[Bug]: mo will be very slow or lost connection after recover from some anomalies

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10514]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO will be very slow or lose connection after recovering from some anomalies.

The TPCC TPS will be very very low:
<img width="1250" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/73cbd140-b7bb-4833-8e46-ac66b0cdd670">

Also even without any workload, all CPUs are working at full capacity all the time.
<img width="1770" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/4f991a19-8819-4473-a574-f1d2bfdfad8e">

### Expected Behavior

MO should work fine after recovering from some anomalies

1. Add some random fault. For example: 
  <img width="852" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/96db20e1-a86d-4d22-9d56-2c55a7de18b1">

2. compile and run MO
3. Run TPCC

**Comment by XuPeng-SH** [comment]
@aptend will do some investigation into this issue

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/10536 is merged
