### ISSUE TITLE
[Bug]: Aggregate logging : disableStmtAggregation = true query aggregate 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10511]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dad0e2cb083156805a29ac9287a837537637e710
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo 1cn  mode
config disableStmtAggregation = true, but select from statement_info about insert sql aggregated
<img width="520" alt="企业微信截图_0ae7a455-c347-43c6-ab89-9b38b1cf5fbb" src="https://github.com/matrixorigin/matrixone/assets/113406637/7ab4adf6-fa1c-4059-bc1f-a663a0a965f7">
<img width="1428" alt="企业微信截图_4da54c9c-0c2f-49a7-9ca0-2986c7d82147" src="https://github.com/matrixorigin/matrixone/assets/113406637/5b6adb8d-afb4-4ddf-994b-ac994dfd51c6">

### Steps to Reproduce

```Markdown
Concurrent 100 insert into r1 values xxxx；
select * from statement_info where aggr_count>1 limit 5;
```

**Comment by heni02** [comment]
@gavinyue plz check this issue

**Comment by heni02** [comment]
another problems:
1cn，statement_info count(*) is 0 rows
cn and log config:
<img width="460" alt="企业微信截图_438a7b81-a8f3-4385-a1ba-92a40dbcf45e" src="https://github.com/matrixorigin/matrixone/assets/113406637/05c4fe0c-8b00-497f-b24a-b95208d42f85">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b745f70c-40d6-48bf-be71-76f56eeb5c77)
<img width="637" alt="企业微信截图_d70b2bb2-c2c4-407c-a3b4-20254cc01ccf" src="https://github.com/matrixorigin/matrixone/assets/113406637/e2f941d4-ffc7-44e6-a0d2-e4d3ac063f1e">

**Comment by gavinyue** [comment]
Should have fixed. Please verify.

**Comment by heni02** [comment]
commit id:acb4a28e0132f8bd477c4c7d4e7a4e31d9146830
2cn  always has this problem
cn1.toml and cn2.toml config：
<img width="694" alt="企业微信截图_558910d5-c753-4c5a-a403-b20750a56d25" src="https://github.com/matrixorigin/matrixone/assets/113406637/649286b2-1921-490d-946f-70aa1d9f2c5c">
disableStmtAggregation = true
skipRunningStmt = true
aggregationWindow = "5s"         # 5 秒
selectAggrThreshold = "200ms"    # 200 ms
enableStmtMerge = true
aggr_count>0
<img width="1346" alt="企业微信截图_d1686b60-c245-4b0b-83af-407f21b1ed1f" src="https://github.com/matrixorigin/matrixone/assets/113406637/450cb238-0181-42de-9ac7-fd3afdbf9807">
