### ISSUE TITLE
[Bug]: two date time expressions not equal to int value reported panic interface conversion

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10535]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b28a372bf1a798b3826d2fd791501c3945ed92f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

!=5 reported panic
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e9728b20-2f6a-4cc7-97c2-d2490d0606de)
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is []int64, not []types.Datetime:
runtime.panicdottypeE
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/tools.go:43
github.com/matrixorigin/matrixone/pkg/container/vector.GenerateFunctionFixedTypeParameter[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/functionTools.go:64
github.com/matrixorigi

and =5, >5,<5  executed succeed
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d4a9663c-9663-4a75-9b27-6b5a4390dfe8)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/8c287ab3-845b-4800-b1ff-c18cb057fff9)

### Steps to Reproduce

```Markdown
select response_at-request_at from statement_info where aggr_count>1 and response_at-request_at!=5;
```

**Comment by sukki37** [comment]
@aunjgr Could you kindly look at this one?

**Comment by aunjgr** [comment]
Will work on it after finish "GROUP BY alias"

**Comment by aunjgr** [comment]
working on pessimistic issues

**Comment by aunjgr** [comment]
will work on this tomorrow

**Comment by aunjgr** [comment]
#10818 fixes this

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm,closed
commit id:1c70e2f03c6577ce75bfe2119b09be7180f55ab5
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d3737802-888e-4350-8159-8cefc3c0587c)
