### ISSUE TITLE
[Bug]: MO doesn't recognize localhost

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10545]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8870ea87a96828862413e88f380c5bf5159fa5ad
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

it happened before, it was once fixed and it happens again https://github.com/matrixorigin/matrixone/issues/6152

```

nandeng-macbookpro:logs nandeng$ mysql -h127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8721
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
nandeng-macbookpro:logs nandeng$ mysql -hlocalhost -P6001 -uroot -p111       
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by ouyuanning** [comment]
mysql -h localhost -P 6001 -udump -p111 --ssl-mode=DISABLED

will also get err:
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'dump'@'localhost' (using password: YES)

that seem we do not add auth  xxx@localhost  to meta tables in init.

**Comment by daviszhen** [comment]
还没做。

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/0005d06f-40e5-4c0d-85e8-299f4553bb22)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/d14d4d88-723d-41ef-9556-b43d8ddc3bb6)

**Comment by dengn** [comment]
It looks like a OS related thing. 

In debian 11.4, it doesn't work by default setting with 'localhost'. 

```
root@VM-134-6-debian:~# mysql -h localhost -P6001 -uroot -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

We need to set this sock file path to cn.toml

```
[cn.frontend]
unix-socket ="/var/run/mysqld/mysqld.sock"
```

restart MO，and we are able to connect by localhost
```
root@VM-134-6-debian:~# mysql -h localhost -P6001 -uroot -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 110
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

If this path is not set, MatrixOne will use a generated sock file in /tmp/mysql.sock. 

In macbook, it looks like a different issue.

**Comment by dengn** [comment]
Currently the best practice is to inform users not to use localhost, but stays with 127.0.0.1 in documentation.
