### ISSUE TITLE
[Bug]: The calculation result of hash partition function is unstable

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#10541]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select CAST((abs(hash_value(0)) % 2) AS INT);
+---------------------------------------+
| cast((abs(hash_value(0)) % 2) as int) |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> select CAST((abs(hash_value(1)) % 2) AS INT);
+---------------------------------------+
| cast((abs(hash_value(1)) % 2) as int) |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
1 row in set (0.01 sec)

mysql> select CAST((abs(hash_value(2)) % 2) AS INT);
+---------------------------------------+
| cast((abs(hash_value(2)) % 2) as int) |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> select CAST((abs(hash_value(3)) % 2) AS INT);
+---------------------------------------+
| cast((abs(hash_value(3)) % 2) as int) |
+---------------------------------------+
|                                     0 |
+---------------------------------------+
1 row in set (0.01 sec)
/

CREATE TABLE t1 (
a INT DEFAULT NULL,
b INT DEFAULT NULL
)

insert into t1 values (0,0),(1,1),(2,2),(3,3);

insert into t1 select a, b from t1;
insert into t1 select a, b from t1;
insert into t1 select a, b from t1;
insert into t1 select a, b from t1;
insert into t1 select a, b from t1;
insert into t1 select a, b from t1;
insert into t1 select a, b from t1;   
insert into t1 select a, b from t1; 

mysql> select a,abs(hash_value(a)) % 2, hash_value(a)  from t1 group by a;
+------+-------------------------+----------------------------+
| a        | abs(hash_value(a)) % 2 |    hash_value(a)                 |
+------+-------------------------+----------------------------+
|        0 |                                   1 |  6278886786517455977   |
|        1 |                                   1 | -3055030011349820079   |
|        2 |                                   1 |   165638774618195171    |
|        3 |                                   0 |  4436699096334981006   |
+------+-------------------------+----------------------------+

but ，executing the query separately, it was found that the hash partition function calculation results were unstable
mysql> select a,abs(hash_value(a)) % 2, hash_value(a)  from t1;
+------+------------------------+-------------------------+
|   a       | abs(hash_value(a)) % 2 |     hash_value(a)           |
+------+------------------------+-------------------------+
            ~~~~~~~~~~~~~~~~~~
|    0     |                      0            |  7957051763296839874 |
|    1     |                      0            |  5964062825198471698 |
|    2     |                      0            | -1062676934078380908 |
|    3     |                      0            | -7649848060062019562 |
|    0     |                      0            |  7957051763296839874 |
|    1     |                      0            |  5964062825198471698 |
|    2     |                      0            | -1062676934078380908 |
|    3     |                      0            | -7649848060062019562 |
|    0     |                      0            |  7957051763296839874 |
|    1     |                      0            |  5964062825198471698 |
|    2     |                      0            | -1062676934078380908 |
            ~~~~~~~~~~~~~~~~~~
|    3     |                      0            | -7649848060062019562 |
|    3     |                      0            | -7649848060062019562 |
+------+------------------------+--------------------------+

**Comment by m-schen** [comment]
函数本身的实现对哈希表的使用有问题，同一批次256个得出来key值不相同。

**Comment by m-schen** [comment]
已修复该问题，可以进行验证。
@qingxinhome

**Comment by qingxinhome** [comment]
> 已修复该问题，可以进行验证。 @qingxinhome

OK， thank you!
