### ISSUE TITLE
[Bug]:  user field in the statement_info have empty string value

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10542]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b28a372bf1a798b3826d2fd791501c3945ed92f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
1cn default configuration startup
sys dump user login mo ，select statement_info user filed has null value
<img width="1914" alt="企业微信截图_5be8dbf6-ec32-49a6-b99b-a3c1717a0279" src="https://github.com/matrixorigin/matrixone/assets/113406637/fac93ea5-6be9-422f-8c3c-0ef1bd5954d0">
<img width="1034" alt="企业微信截图_237e9485-3d52-4069-9ced-8930a627c22d" src="https://github.com/matrixorigin/matrixone/assets/113406637/ab670564-6e99-4585-aeca-21eb86bc9282">

I found the db involved in finding empty data is these two ，and source type include external_sql and internal_sql
<img width="993" alt="企业微信截图_f780738d-5a7f-4e1f-9526-b262b7e4cfe3" src="https://github.com/matrixorigin/matrixone/assets/113406637/5088be7d-b98c-45e5-b0d1-08c3873b97e4">
<img width="1020" alt="企业微信截图_02ca9d66-6893-4829-9bff-f27f276d516f" src="https://github.com/matrixorigin/matrixone/assets/113406637/e6b7c69e-3845-4035-8fbc-3507e93948e6">

select count(1),account, user, aggr_count from system.statement_info where user = '' group by account, user, aggr_count;
<img width="1360" alt="企业微信截图_ac98578f-5647-49f0-94af-2640dbd6f385" src="https://github.com/matrixorigin/matrixone/assets/113406637/779fbe92-28f8-4630-9db5-3b797553bf2d">

### Steps to Reproduce

```Markdown
Concurrent 100 inserts, run for 10 minutes, and select statement，
Concurrent 100 inserts use mo-load tool:
1.git clone https://github.com/matrixorigin/mo-load.git
2.config case insert run.yaml, path:cases/ddl/run.yaml
vuser: 100 
- sql: "insert into r1 values ({tbx});"
3.login mysql ,create database db; use db; create table r1(c1 int);
4. ./start.sh -c cases/ddl/
```

**Comment by heni02** [comment]
@xzxiong plz confirm issue

**Comment by xzxiong** [comment]
@heni02 what etc is used to startup ?

**Comment by xzxiong** [comment]
> @heni02 what etc is used to startup ?

confirm: startup with etc/launch-tae-CN-tae-DN (nothing modified)

**Comment by xzxiong** [comment]
statement_info 中的 account，User，host 等都是从 frontend 中获取的，不会进行额外的处理。
所以，这里会从2个点去分析：1）frontend 本身是否存在确实；2）statemetn_info在 aggr的时候是否处理的有问题。

**Comment by gouhongshen** [comment]
user 为空的问题同 #9326，应该是一样的原因

**Comment by heni02** [comment]
测试了在普通租户下查询statement_info，也有user空值情况：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b344d200-dff4-4f24-bd3d-f82804b6e337)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/bf54e32a-fc43-4e64-8ef4-d421956425e2)

**Comment by xzxiong** [comment]
not repro, commit id: `8b1d0cf14`

**Comment by xzxiong** [comment]
not repro

**Comment by xzxiong** [comment]
not repro in my dev

**Comment by xzxiong** [comment]
@heni02 ptal

**Comment by heni02** [comment]
from Steps to Reproduce can repro :
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0a28c666-93d3-40d7-8793-ec4a1ea3729a)

**Comment by xzxiong** [comment]
the key step to repro is: connect mysql without cmdline-arg `-A` or 同语义的 option参数。

**Comment by xzxiong** [comment]
@heni02 ptal, fix了。
是历史的bugfix导致的，原issue https://github.com/matrixorigin/matrixone/issues/8165
目前根据要求进行修复：**仅** 将 `__++__internal_cmd_field_list ...` 相关的query的 user置空。

**Comment by heni02** [comment]
confirm ,closed
commit id: b0dac488e6c92f28ad1b5cb61238efc24a3f18ac
![image](https://github.com/matrixorigin/matrixone/assets/113406637/cadebd60-e18b-4264-9236-dca12f360b43)
<img width="1088" alt="企业微信截图_9ffabfd6-593c-43ba-9bbf-162a94017025" src="https://github.com/matrixorigin/matrixone/assets/113406637/aa4914e7-4782-4734-9b2f-96c141f966e7">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e6205e2d-a63a-40fa-b0dc-3d8f9e0760b6)
