### ISSUE TITLE
[Bug]: host and transaction_id  etc fields in statement_info have empty string value

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10548]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b28a372bf1a798b3826d2fd791501c3945ed92f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

host , transaction_id and database  field in statement_id which aggr_count equal and greater than 0 have null values
host:
<img width="1740" alt="企业微信截图_df247c4c-200f-414f-bdb4-4c4b295b7ffc" src="https://github.com/matrixorigin/matrixone/assets/113406637/85d0f24a-dff2-48f3-b082-42e0c97a42eb">
<img width="1244" alt="企业微信截图_ba9caa4c-a728-4384-ac04-71e1af7c8913" src="https://github.com/matrixorigin/matrixone/assets/113406637/7cd6c65a-8c10-4892-aef9-6e077dd2a9f6">
<img width="794" alt="企业微信截图_185bc159-5d75-4af3-b6ca-4e7529fa4824" src="https://github.com/matrixorigin/matrixone/assets/113406637/1f40f013-2a39-4549-83ad-c8d8a5e6d04e">

transaction_id:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/92538f37-03f9-40ee-8970-cb44137cbb03)

database:
<img width="1734" alt="企业微信截图_9e40bcda-e799-4b92-9e67-196dd51ab37f" src="https://github.com/matrixorigin/matrixone/assets/113406637/b3c0f954-bae1-4023-9818-42607940100b">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/24901ffb-538b-4bfe-b23d-10ae9fab5b90)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/96330f03-a7d9-4e3a-98dc-1189e6b2ffcf)

**Comment by m-schen** [comment]
这个应该是个空字符串，不是null值，null值打印出来应该是Null。

**Comment by m-schen** [comment]
@xzxiong 麻烦确认一下这个是空值 还是 ""。

**Comment by xzxiong** [comment]
- [x] host empty, fixing.
- [ ] transaction_id empty, checked
- [ ] user empty, not repro

**Comment by xzxiong** [comment]
@heni02 ptal

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm,commit id: 1c70e2f03c6577ce75bfe2119b09be7180f55ab5
host is not empty:
<img width="799" alt="企业微信截图_70e19e2d-7c2b-4846-a603-67f44a396d94" src="https://github.com/matrixorigin/matrixone/assets/113406637/43683083-7f18-4463-95d7-0d9ea12a8f6c">
transaction_id aggr_count=0 or 1 has empty, is this problem?
<img width="959" alt="企业微信截图_0d952a73-c9f4-4bf9-a6e5-e84f68249e04" src="https://github.com/matrixorigin/matrixone/assets/113406637/6c6edf06-593e-4384-8396-bf62db7f47d0">

**Comment by xzxiong** [comment]
> confirm,commit id: [1c70e2f](https://github.com/matrixorigin/matrixone/commit/1c70e2f03c6577ce75bfe2119b09be7180f55ab5) host is not empty: <img alt="企业微信截图_70e19e2d-7c2b-4846-a603-67f44a396d94" width="799" src="https://user-images.githubusercontent.com/113406637/257764780-43683083-7f18-4463-95d7-0d9ea12a8f6c.png"> transaction_id aggr_count=0 or 1 has empty, is this problem? <img alt="企业微信截图_0d952a73-c9f4-4bf9-a6e5-e84f68249e04" width="959" src="https://user-images.githubusercontent.com/113406637/257765792-6c6edf06-593e-4384-8396-bf62db7f47d0.png">

case 1) aggr_count =0
有些语句是没有事务的，所以会为空。例如：`use {database}`

case 2) aggr_count > 0
会被置为 空，正常。

**Comment by heni02** [comment]
confirm, closed
