### ISSUE TITLE
[Bug]: Aggregate logging :statement in statement_info have empty string value

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10551]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b28a372bf1a798b3826d2fd791501c3945ed92f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

aggr_count>0  have empty string value, but aggr_count=0 not
<img width="1730" alt="企业微信截图_bb0ca926-96a4-49d5-9fcc-5490dafbbd28" src="https://github.com/matrixorigin/matrixone/assets/113406637/1c5a3f58-ac10-4d0e-ac7f-f15211a8f811">
<img width="884" alt="企业微信截图_9de29411-8a64-4929-a7c8-aa110034b5ff" src="https://github.com/matrixorigin/matrixone/assets/113406637/a1faf1ec-cc38-4ac6-aa02-9fc4aa3df273">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/820922df-afb3-4974-9a0d-75a1225c225b)

### Steps to Reproduce

```Markdown
Concurrent 100 inserts, run for 10 minutes, and select statement，
Concurrent 100 inserts use mo-load tool:
1.git clone https://github.com/matrixorigin/mo-load.git
2.config case insert run.yaml, path:cases/ddl/run.yaml
vuser: 100 
- sql: "insert into r1 values ({tbx});"
3.login mysql ,create database db; use db; create table r1(c1 int);
4. ./start.sh -c cases/ddl/
```

**Comment by m-schen** [comment]
@xzxiong @gavinyue 
我不是很清楚这个bug的描述，包括aggr_count的含义，是statement的字符统计吗。出现的情况是statement_info表的statement列的值为空？
麻烦确认一下该情况是否符合预期以及bug的归属。

**Comment by heni02** [comment]
@m-schen 这个bug主要是statement_info表里有statement为空值这个情况，如果是为空是预期的，是什么情况，如果不是预期，这是个bug，需要修复

**Comment by xzxiong** [comment]
> @m-schen 这个bug主要是statement_info表里有statement为空值这个情况，如果是为空是预期的，是什么情况，如果不是预期，这是个bug，需要修复

@gavinyue ptal, 当 aggr_count > 0 时，statement这个字段应该是什么值。

**Comment by gavinyue** [comment]
> 
理论上是第一个statementinfo的statement。 我看一下吧

**Comment by gavinyue** [comment]
Work on the fix now.  Bascially it is caused by stringbuilder in the aggr.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Find the problem. Ready to fix.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
正在解决这个问题

**Comment by gavinyue** [comment]
Keep looking into it tomorrow.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
pending

**Comment by gavinyue** [comment]
pending

**Comment by gavinyue** [comment]
Looking

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
正在和其他写入异常的issue 一起研究

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by heni02** [comment]
明天测试验证

**Comment by heni02** [comment]
confirm,closed
commit id:3140d2e3eda1d4318645f07dcdbd21296ac1e956
默认聚合功能打开，普通租户下并发500 insert持续跑3个小时，插入2亿多条sql，statement_info共4千6百多万行，没有出现statement为空的情况
<img width="829" alt="企业微信截图_40e503a2-4b4b-424c-af49-46132d4367ac" src="https://github.com/matrixorigin/matrixone/assets/113406637/b9deeb08-96de-49f3-abd5-0cbcb331fea3">
