### ISSUE TITLE
[Bug]: Aggregate logging :statement_type is commit aggregated

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10559]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b28a372bf1a798b3826d2fd791501c3945ed92f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

statement_type is commit aggregated, inconsistent with requirements
<img width="1147" alt="企业微信截图_39133347-052d-4f2c-af64-c022454ac8b5" src="https://github.com/matrixorigin/matrixone/assets/113406637/4f686d41-8fb5-4a29-a8c1-c907c0e34311">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/a915515a-7d98-4faa-9ebd-a6d3c3b2a85b)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/79296357-386c-485f-9b9c-f76258f08713)

**Comment by heni02** [comment]
@gavinyue plz confirm this issue

**Comment by m-schen** [comment]
statement_type的值 与 文档中不符合。
文档中只有update 与 delete，实际执行情况为commit

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/10573

**Comment by gavinyue** [comment]
Merged. Please verify.

**Comment by heni02** [comment]
confirm,closed
commit id: 03d848d9d0eaedb44d3538cf7523968914a6ec1a
![image](https://github.com/matrixorigin/matrixone/assets/113406637/3fdc07e3-63db-444c-bc91-ea30db791a17)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/03614147-b9b0-4b73-9d8a-29c7d5e228ac)
