### ISSUE TITLE
[Bug]: sql select * from system.statement_info where  duration='' which duration is bigint unsigned reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10554]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b28a372bf1a798b3826d2fd791501c3945ed92f4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/113406637/b047b56b-025a-46dc-a3d9-6eda28a35e3a)
mysql> select * from system.statement_info where  duration='' ;
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:260
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/sql/plan.increaseRefCnt
	/Users/heni/test-envir/matrixone/pkg/sql/plan/utils.go:812
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).remapAllColRefs
	/Users/heni/test-envir/matrixone/pkg/sql/plan/quer

I found create new table without this problem：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/17ade2f2-60e4-48d6-a7c6-2c1bfdda5fa0)

### Steps to Reproduce
select * from system.statement_info where  duration='' ;

**Comment by m-schen** [comment]
对系统构建描述中的sql语句时，计划过程中出现panic。

如果是正常创建的表可以通过计划生成阶段，并在执行阶段报错无法将空字符串转换成uint64.

**Comment by ouyuanning** [comment]
未复现。可能谁的PR修复了？

**Comment by ouyuanning** [comment]
drop database if exists db1;
create database db1;
use db1;
create table t1 (a int primary key, b int);
insert into t1 values (1,1);
select mo_ctl('dn', 'flush', 'db1.t1');
select a from t1 where a = '';

可以这样复现

**Comment by heni02** [comment]
confirm,closed
commit id:2c971b7b115e4cacff8b755d1f236537c63e8d04
![image](https://github.com/matrixorigin/matrixone/assets/113406637/5b1881c9-9e8d-413a-879c-568d189d7930)
