### ISSUE TITLE
[Feature Request]:  Use arena to allocate all fractional memory allocations for pipeline

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#10574]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

在一个session中，执行一个查询，内存分配的数目应该是可控的

**Comment by dongdongyang33** [comment]
Arena does not support concurrent operations

**Comment by jensenojs** [comment]
我今天先试着在compile中实验一下

**Comment by dongdongyang33** [comment]
编译执行计划部分的内存分配较多的数据结构使用 arena 完成。

完成了把 arena 绑定在 compile 的部分测试。
现在把它的绑定移到 session 级别在测试中

**Comment by dongdongyang33** [comment]
移到 session 级别的过程中遇到一些问题：
1. mo-arena 分配的 cap/len 不正确问题，会导致使用有一些意外情况发生
2. 由 mo-arena 分配的数据小部分数据会出现被改写的情况，使用 tpch 10g 测试，只在 q18/q2 的时候会遇到

1 已修复
2 在排查问题中。使用 go 本身的 new 来替换无法复现，但是是 mo-arena 的问题还是其他现存代码的 race 还在定位中

**Comment by ouyuanning** [comment]
finished by https://github.com/matrixorigin/matrixone/pull/11845
