### ISSUE TITLE
[Feature Request]: 后台任务内存情况调查

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#10579]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

分析各种后台程序的内存分配，占用是否合理，修复不合理的情况

**Comment by jensenojs** [comment]
# TLDR

红框圈出的后台任务值得重点关注

<img width="1585" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/3bc5e984-5353-4e8a-9ac8-31024f969f5f">

# 实验记录

1. 10:28:44通过`./mo-service -debug-http :9876 -launch ./etc/launch-tae-CN-tae-DN/launch.toml > mo-service.log 2>&1mo`启动mo，commitId 为 `d8e84ac`。

2. 不断调用`curl http://localhost:9876/debug/pprof/heap`进行记录，其创建时间如下：

| heap_pprof | 采集时间 | 时间间隔    |
| ---------- | -------- | ----------- |
| mem1       | 10:40    | 0           |
| mem2       | 10:43    | 3分钟       |
| mem3       | 10:56    | 16分钟      |
| mem4       | 11:48    | 1小时8分钟  |
| mem5       | 11:56    | 1小时16分钟 |
| mem6       | 14:17    | 3小时37分钟 |
| mem7       | 14:49    | 4小时9分钟  |
| mem8       | 15:05    | 4小时25分钟 |
| mem9       | 15:14    | 4小时34分钟 |
| mem10      | 15:24    | 4小时44分钟 |
| mem11      | 15:35    | 4小时55分钟 |
| mem12      | 16:14    | 5小时34分钟  |
|mem 13     | 17:12     | 6 小时 32 分钟   |

3. 利用`go tool pprof -http=:8000 -diff_base mem1 memx`进行对比，在下一小节探索哪一部份的内存逐渐攀升。

# 探索

本小节分为两个部分，第一部份通过火焰图的对比展现直观比较，第二部分进行数据的验证，若无特殊说明，下面的数据均为`inuse_space`

## first-step：火焰图

mem1-mem2的调用栈什么的和往后的mem1-memX都不一样，无法对比，所以从mem3开始对比

### mem1-mem3

<img width="1562" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b1abbe8f-2a67-4ba1-a3ae-52d7fd812f69">

### mem1-mem12

<img width="1521" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/cd9a823a-0c6f-4701-b090-38fd589b58d2">

这个对比也许暗示了一些问题。

## second-step

### 表格对比
下面这个表格列举了从mem3到mem13的一些后台任务占用内存的情况，我摘取了一些占比比较高的任务放入该表格中，其中第一列是对比的heap_pprof，第二列是距离mem1的时间间隔，第三列是inuse_space占用的内存和相比mem1的增长百分比，从第四列开始是具体的细分，需要注意的是`tasks. (*Job). Run`是位于`Ants. (*goWorker). run. func 1`之下的，也就是说它比其他的目录都低一级，但由于它值得重点关注，所以我就把它加进来了。

这个表格不用太详细看，下面有折线图。

<img width="1760" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/13acb511-0686-43c5-a2b1-1ad0d3b431b7">

|heap_pprof|时间间隔|Inuse space (Precent)|Ants. (*goWorker). run. func 1|tasks. (*Job). Run|doRunCancelableTask. func 1|sm. (*safeQueue). Start. func 1|runWorker. func 1|
|---|---|---|---|---|---|---|---|
|mem 1|0|0|0||0|0|0|
|mem 2|3 分钟|-|-||-|-|-|
|mem 3|16 分钟|14.6%(19.51 MB)|9.1%(12.08 MB)|0.8%(1.07 MB)|3%(4.04 MB)|3%(4 MB)|1.3%(1.79 MB)|
|mem 4|1 小时 8 分钟|46.4%(61.86 MB)|31.7%(42.23 MB)|7.1%(9.48 MB)|6.5%(8.66 MB)|6.8%(9.09 MB)|2.4%(3.23 MB)|
|mem 5|1 小时 16 分钟|47.8%(63.64 MB)|32.5%(43.36 MB)|7.1%(9.48 MB)|6.5%(8.66 MB)|5.7%(7.57 MB)|3.7%(4.88 MB)|
|mem 6|3 小时 37 分钟|94.2%(0.12 GB)|62.6%(83.38 MB)|14.6%(19.46 MB)|8.9%(11.83 MB)|13.6%(18.11 MB)|8.9%(11.91 MB)|
|mem 7|4 小时 9 分钟|99.5%(0.13 GB)|65.6%(87.35 MB)|15.8%(21.06 MB)|9.5%(12.7 MB)|15.1%(20.09 MB)|9%(12.03 MB)|
|mem 8|4 小时 25 分钟|105.4%(0.14 GB)|70.7%(94.13 MB)|17.8%(23.65 MB)|9.2%(12.2 MB)|14.3%(19.06 MB)|11.2%(14.98 MB)|
|mem 9|4 小时 34 分钟|112.2%(0.15 GB)|75.2%(0.1 GB)|20.2%(26.85 MB)|8.8%(11.7 MB)|15.5%(20.63 MB)|10.8%(14.34 MB)|
|mem 10|4 小时 44 分钟|114.1%(0.15 GB)|75.2%(0.1 GB)|20.2%(26.85 MB)|10.6%(14.11 MB)|13.6%(18.06 MB)|12.7%(16.96 MB)|
|mem 11|4 小时 55 分钟|118.3%(0.15 GB)|79.4%(0.1 GB)|22.5%(29.98 MB)|10.2%(13.61 MB)|13.9%(18.56 MB)|11.6%(15.39 MB)|
|mem 12|5 小时 34 分|131.6%(0.17 GB)|87.9%(0.11 GB)|26.6%(35.38 MB)|11%(14.62 MB)|14.3%(19.07 MB)|14.8%(19.76 MB)|
|mem 13|6 小时 32 分|144.5%(0.19 GB)|99.3%(0.13 GB)|30.5%(40.69 MB)|9.8%(13.12 MB)|14.7%(19.57 MB)|19.3%(25.68 MB)|

### 折线图对比

<img width="1011" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/4b7878f9-1196-4660-8e7b-c1a99587ae25">

可以看到`tasks.(*Job).Run`和`Ants.(*goWorker).run.func 1`的内存在空转下随着时间推移增长得很明显，前者的增长的主要原因应该就是来自于后者，`Ants.(*goWorker).run.func 1`值得后续重点研究。

其实其他的后台任务也有类似的问题，但相比之下并不突出。

## 初步结论

关注`Ants.(*goWorker).run.func 1`的问题。

**Comment by jensenojs** [comment]
晚上用自动任务每隔两小时采集一次，整理后以折线图的方式展示结果，可视化效果应该更好一些

<img width="1107" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/a5d61429-0d83-41e2-ad53-bfe062d92a46">

**Comment by jensenojs** [comment]
由于还要改其他的pr，后台空转的Mo我就停了，我保留了所有的pprof，有需要的可以找我。

从变化趋势看，下图红框圈出来的两个后台任务的增长幅度是最显眼的，`tasks.(*Job).Run`在之前的对比中对内存的占用是小于`tasks.(*poolHandler).doHandle.func1.1`的，`runWorker.func1`在之前也是小于`sm.(*safeQueue).Start.func1`和`
doRunCancelableTask.func1`的。

<img width="1447" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/49f5c50d-dea8-4ed5-8672-1dd771464a87">

**Comment by jensenojs** [comment]
修改了cn，dn，log中与memory相关的cache大小，然后再重新起定时任务采集一天试试看，之前的测试没有设置好，不太有用...

<img width="1141" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ffd6ec98-9daa-48f3-9786-483aab6132b3">

**Comment by jensenojs** [comment]
在本地docker上起了一个Mo，采集一段时间看看先
