### ISSUE TITLE
[Bug]: No correct number of bits is reserved for the datetime type in mo-tester.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10571]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="482" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c2f447e8-b72e-49e0-8dd3-564ff95f7365">

### Expected Behavior

col1
2020-01-13 12:20:59.123
2023-04-17 01:01:45.000

### Steps to Reproduce

```Markdown
drop table if exists test01;
create table test01(col1 datetime(3));
insert into test01 values('2020-01-13 12:20:59.12343243');
insert into test01 values('2023-04-17 01:01:45');
insert into test01 values(NULL);
select * from test01;
```

**Comment by aressu1985** [comment]
no working on it

**Comment by aressu1985** [comment]
no working on it

**Comment by aressu1985** [comment]
no working on it

**Comment by aressu1985** [comment]
The scale of datetime in resultSet from jdbc is not correct, there is may something wrong about this. so if resolving this problem , the mo need to correct this scale and tracked by #10793

**Comment by aressu1985** [comment]
tracking by this issue #10904 
this can closed
