### ISSUE TITLE
[Bug]: Aggregate logging：cloud_ nonuser_ sql source type sql do not have aggregation

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10583]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):90a0a5f481067beee514a4439ccebd262c7b2253
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cloud_ nonuser_ sql source type sql do not have aggregation，duration<5s
<img width="1338" alt="企业微信截图_544e40e2-92c1-4369-972b-f1bf8d878b13" src="https://github.com/matrixorigin/matrixone/assets/113406637/7b148979-1d20-4f75-a850-bc03a20b3242">
<img width="1345" alt="企业微信截图_b5f349a3-4a36-4fb0-b1be-66c7a1106f78" src="https://github.com/matrixorigin/matrixone/assets/113406637/fb3e3734-1000-4e56-950c-fb39751c3891">
<img width="794" alt="企业微信截图_7b4225e4-e14f-43cb-9be0-cc5e93c2ded4" src="https://github.com/matrixorigin/matrixone/assets/113406637/62e18e3d-b223-4f06-aba6-82d6a6fa6293">

### Steps to Reproduce

```Markdown
/* cloud_nonuser_sql */insert into r1 values (4);
```

**Comment by heni02** [comment]
@gavinyue plz confirm this issue

**Comment by m-schen** [comment]
没看懂，是不符合文档说明？

**Comment by gavinyue** [comment]
Should have been fixed in https://github.com/gavinyue/matrixone/commit/cadfd654039ae2d75eb35468a378c1fcbfeb1326


Please test.  Thanks.

**Comment by heni02** [comment]
commit id:8af14455f059e657890f4249ca63699476bb7f63
Latest commit, cloud_ nonuser_sql type  sql_ source_ type has become external_ sql
<img width="1655" alt="企业微信截图_202a295c-bc17-4cbe-acc0-31e4adea6e57" src="https://github.com/matrixorigin/matrixone/assets/113406637/9b53e048-51f9-48af-8d5c-6629f3acb284">
previously is cloud_ nonuser_ sql:
<img width="804" alt="企业微信截图_b6cacd0b-afe6-4625-9dc1-71124c4bf6d3" src="https://github.com/matrixorigin/matrixone/assets/113406637/94e2594f-f145-4c87-8dfd-8d958a957652">

**Comment by gavinyue** [comment]
Assign back to test after discussion

**Comment by heni02** [comment]
The above hint was written incorrectly,right hint is /* cloud_nonuser */, I verify again cloud_nonuser_sql type is aggregated, closed
commit id:6828ed04cefb5e2b306120f655ab34c16c56aa1a
<img width="1466" alt="企业微信截图_a5c30e49-8f5c-4afb-8597-e9a18c78abf1" src="https://github.com/matrixorigin/matrixone/assets/113406637/c997ec1d-eca2-45a8-a572-2335d605c23a">
