### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: the result of select count(*) is not correct.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10587]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bb16e64182a7c6b4e1e430818bdbd0311b34e35c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="703" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a539fedf-34ca-4937-b891-2cfca13488cd">

[log.txt](https://github.com/matrixorigin/matrixone/files/12014632/log.txt)

### Expected Behavior

the correct of select(*) from t is 262144.

**Comment by zhangxu19830126** [comment]
fixed

**Comment by Ariznawlll** [comment]
<img width="1773" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/13aede35-21d5-4ee3-be6b-1a3b3d6633bb">
the result of count(*) is still abnormal.

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
already fixed. but this bvt case can not run in pessimistic mode. many case is wrong

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
<img width="1416" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/57ca5d79-6d1d-45e8-b481-ce4b526b0a81">

Verified!

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
In optimistic mode,CN does not remove duplicates, DN removes duplicates completely, in pessimistic mode, CN fully remove duplicates, DN incrementally remove duplicates. Therefore, in pessimistic mode, the conflict is reported at the time of execution. We modified the paths of some cases to support the optimism test and the pessimism test.

Verified!

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
