### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: update table set does not return result in 120000ms.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10585]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): bb16e64182a7c6b4e1e430818bdbd0311b34e35c 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1403" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c2e4b2b2-b070-4cf5-bb35-c3bc86306d80">
[run.log](https://github.com/matrixorigin/matrixone/files/12013024/run.log)

### Steps to Reproduce

```Markdown
in mo-tester
./run.sh -n -g -p /matrixone/test/distributed/cases/pessimistic_transaction
```

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by ouyuanning** [comment]
need confirm with @domingozhang

**Comment by ouyuanning** [comment]
seems waiting lock.

**Comment by Ariznawlll** [comment]
the sql is incorrect, we have already modified.
