### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: internal error: panic runtime error while select * from table.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10606]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):416bd0537a8726e7cd72ac2f7af6b59639a8d4f3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1077" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ddea1ec5-e84c-4857-a900-f93227124069">
[log.txt](https://github.com/matrixorigin/matrixone/files/12024473/log.txt)

### Steps to Reproduce

```Markdown
in mo-tester:
 ./run.sh -n -g -p /Users/ariznawl/code/matrixone/test/distributed/cases/pessimistic_transaction -m run
```

**Comment by ouyuanning** [comment]
具体出错的SQL语句，和报错信息记得贴一下

**Comment by Ariznawlll** [comment]
Invalid issue
