### ISSUE TITLE
[Performance]: Improve load in Pessmitic mode

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10602]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

Improve load in Pessmitic mode:
1.  Lock table before load
2. disable pk dedup in load
3. end of load run a query select count(*) group by primarykey having count(*) > 1 to check pk dup

**Comment by ouyuanning** [comment]
same as #10655
