### ISSUE TITLE
[Subtask]: support mod symbol in partition expression

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#10610]
### Parent Issue

#4374

### Detail of Subtask

CREATE TABLE `w_videos_partition_2` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `plt` int(11) DEFAULT '0' COMMENT '平台id',
  `device_id` varchar(32) DEFAULT '' COMMENT '设备id',
  `user_id` int(11) DEFAULT '0' COMMENT '用户id',
  `home_id` int(11) DEFAULT '0' COMMENT '家庭id',
  `type` varchar(32) DEFAULT '' COMMENT '视频类型 CRY, MOVE, VOICE, STATE, LOW_BATTERY',
  `video_image` varchar(500) DEFAULT '' COMMENT '封面链接',
  `video_url` varchar(1024) DEFAULT '' COMMENT '视频链接',
  `video_start` char(12) NOT NULL DEFAULT '' COMMENT '视频开始时间戳',
  `video_end` char(12) NOT NULL DEFAULT '' COMMENT '视频结束时间戳',
  `status` tinyint(4) DEFAULT '0' COMMENT '0未读1已读',
  `visible` tinyint(4) NOT NULL DEFAULT '0' COMMENT '未购买套餐不可见 0不可见1可见',
  `create_time` char(12) NOT NULL DEFAULT '' COMMENT '创建时间戳',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `content` text,
  `event_start` char(12) NOT NULL DEFAULT '' COMMENT '事件开始时间戳',
  `event_end` char(12) NOT NULL DEFAULT '' COMMENT '事件结束时间戳',
  `msg_id` varchar(32) NOT NULL DEFAULT '',
  `event_id` varchar(32) NOT NULL DEFAULT '',
  `accept` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`,`created_at`) USING BTREE,
  KEY `device_id` (`device_id`) USING BTREE,
  KEY `userId` (`user_id`) USING BTREE,
  KEY `createTime` (`create_time`) USING BTREE,
  KEY `plt_dev_user_sv_ctime` (`plt`,`status`,`visible`) USING BTREE,
  KEY `created` (`created_at`) USING BTREE,
  KEY `index_0` (`user_id`,`status`,`create_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2122298806 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='视频'
/*!50100 PARTITION BY LIST ((TO_DAYS(created_at)*24 + HOUR(created_at)) % (7*24))
(PARTITION hour0 VALUES IN (0) ENGINE = InnoDB,
 PARTITION hour1 VALUES IN (1) ENGINE = InnoDB,
 PARTITION hour2 VALUES IN (2) ENGINE = InnoDB) */;

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @jianwan0214 @domingozhang
