### ISSUE TITLE
[Feature Request]: saving query result requires async execution

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#10612]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
A sql execution plan contains the action of saving the result, which will increase the query delay, especially for small queries.
```

### Describe the feature you'd like

saving query result requires async execution

**Comment by daviszhen** [comment]
问下张潇 和 李松 的业务细节。
