### ISSUE TITLE
[Feature Request]: Simplify and Clean Up Path-Related Configurations  Description:

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#10621]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

This is a proposed enhancement to our current path-related configurations. It would be much more streamlined and user-friendly if we could allow users to only configure a single data directory.
<img width="613" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/b6ff5f2d-b2b5-44cd-a7ec-cebfcc504fdd">

The idea is to automate the generation of all other necessary directories under this root directory, eliminating the need for multiple complex configuration items.

By adopting this approach, we can reduce the complexity of our configuration, improving the user experience and making our system easier to manage.

**Comment by sukki37** [comment]
related to #10365

**Comment by reusee** [comment]
PR sent.
All fileservice configurations have defaults. A minimal config file can omit all fileservice configs.
