### ISSUE TITLE
[Subtask]:Optimize Default Values for Internal and Advanced User Configurations

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#10623]
### Parent Issue

#10365

### Detail of Subtask

We need to take a closer look at the default values set for both our internal configurations and parameters that are not exposed to our ordinary users, for example:
```
[cn.txn]
mode = "Pessimistic"
[observability]
longQueryTime = 0.0
[dn.Txn]
incremental-dedup = "false"

[dn.Ckp]
flush-interval = "60s"
min-count = 100
scan-interval = "5s"
incremental-interval = "180s"
global-min-count = 60
[dn.LogtailServer]
listen-address = "0.0.0.0:32003"
service-address = "127.0.0.1:32003"
rpc-max-message-size = "16KiB"
rpc-payload-copy-buffer-size = "16KiB"
rpc-enable-checksum = true
logtail-collect-interval = "2ms"
logtail-response-send-timeout = "10s"
max-logtail-fetch-failure = 5
[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8
```
We need to ensure these default values are sensible and provide optimal performance out of the box.

The focus should be on creating a seamless user experience even with the most minimalist configuration of our system. This would allow for better usability for beginners, while still offering advanced users the flexibility they require.

**Comment by reusee** [comment]
the file service part is done. un-assigning myself.

**Comment by xzxiong** [comment]
Is that default value ok for observability ? @sukki37 
```
[observability]
disableTrace = false
disableMetric = false
longQueryTime = 1.0
```
