### ISSUE TITLE
[Subtask]: Remove Unused Configuration Items to Keep Codebase Clean

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#10626]
### Parent Issue

#10365 

### Detail of Subtask

During my use and review of our system, I've noticed there are several configuration items that appear to be unused. These redundant configurations not only clutter the codebase but can also lead to confusion for both our developers and users.

<img width="741" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/119c3afe-8fa6-48d9-849f-a89753eebef3">

I propose we conduct a thorough review of our existing configuration items to identify and remove any that are no longer in use. This will help to keep our codebase clean, improve readability, and reduce the potential for confusion.

**Comment by reusee** [comment]
file service-related done.

**Comment by xzxiong** [comment]
trace and metric related done. see #10715
