### ISSUE TITLE
[Feature Request]: Simple functions on vector type

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10633]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Simple functions, distance, add, inner product, io, etc etc.
```

### Describe the feature you'd like

Based on vector in #10632 ,  all basic functions.

**Comment by arjunsk** [comment]
The pending subtask -  https://github.com/matrixorigin/matrixone/issues/11446 is now merged into the master. Transferring this to @aressu1985 . The documentation required is already covered in this PR: https://github.com/matrixorigin/matrixone/issues/11534#issuecomment-1758149036

**Comment by aressu1985** [comment]
test done

**Comment by arjunsk** [comment]
Attaching the document for future reference: https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkCBCZtJYTR7ubEFzlWl?scode=AJsA6gc3AA8WZVsoG5AawAhAZmAIk
