### ISSUE TITLE
[Feature Request]: Vector type index

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10634]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
create index, and use index to accelerate query.
```

### Describe the feature you'd like

This one is much more trickier, compared to type and function.    Need design doc.

**Comment by fengttt** [comment]
@arjunsk @XuPeng-SH knows a lot of things about how to index the vector type.   Please include him for design/doc review

**Comment by flying-x** [comment]
I don't know much about vector indexing but a use case is to do set operations with similarity in mind.

set1 = select * from vectors where query=q1
set2 = select * from vectors where query=q2

intersection = select p, q from set1, set2 where p == q

obviously, p == q can't be exactly equal, it needs to be some kind of vector equal function.

**Comment by arjunsk** [comment]
Currently getting OOM for a table with 1 million rows of VECF32[1024]. We need to optimize the `window` strategy.

Current Mapping SQL looks like below:

```sql
	SELECT `__mo_index_entries_tbl`.`__mo_index_centroid_version_fk`,
		`__mo_index_entries_tbl`.`__mo_index_centroid_id_fk`,
		`__mo_index_entries_tbl`.`__mo_index_table_pk` FROM
		(
		SELECT
		centroids.`__mo_index_centroid_version` as __mo_index_centroid_version_fk,
		centroids.`__mo_index_centroid_id` as __mo_index_centroid_id_fk,
		tbl.id as __mo_index_table_pk,
		ROW_NUMBER() OVER (PARTITION BY tbl.id ORDER BY l2_distance(centroids.__mo_index_centroid, normalize_l2(tbl.embedding) ) ) as `__mo_index_rn`
		FROM tbl
		CROSS JOIN
		(select * from `__mo_index_secondary_ff6b099e-9b2f-11ee-9b85-723e89f7b974` where `__mo_index_centroid_version` = (select CAST(`__mo_index_val` as BIGINT) from `__mo_index_secondary_ff6b0890-9b2f-11ee-9b85-723e89f7b974` where `__mo_index_key` = 'version')) as centroids
		)`__mo_index_entries_tbl` WHERE `__mo_index_entries_tbl`.`__mo_index_rn` = 1;
```


Also getting another error

```log
SQL Error [20101] [HY000]: internal error: message body 262014371 is too large, max is 104857600
```

@nnsgmsone suggested to reduce the window size.

**Comment by arjunsk** [comment]
Blocked by 2 OOM issues

https://github.com/matrixorigin/MO-Cloud/issues/2276

https://github.com/matrixorigin/MO-Cloud/issues/2277

**Comment by arjunsk** [comment]
Progress:

1. With the workaround, I was able to index a table with 
 - 1million rows of vecf32(148)
 - 1million rows of vecf32(1024)

2. Doing some more analysis on cluster skews in datasets (random dataset vs GPT dataset)

**Comment by arjunsk** [comment]
Update

1. The correctness of the Vector Index has been validated. I need to redo some retesting before posting the official results. Unofficial details are here: 
- https://github.com/matrixorigin/docs/pull/269
- https://github.com/matrixorigin/docs/pull/264

2. The insert performance issue has just now been unblocked. Will continue with the testing.

**Comment by arjunsk** [comment]
The vector index is almost ready for testing.

Waiting for this PR to be merged: https://github.com/matrixorigin/matrixone/pull/14402

The document: 
【企微文档】Vector Index Document
https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkZ9vRK0hiQVykQx3tTi?scode=AJsA6gc3AA86DSyJdmAawAhAZmAIk

CC: @yangj1211

**Comment by arjunsk** [comment]
The PR is merged. It is ready for testing.

**Comment by arjunsk** [comment]
Updated the document with latest changes to KNN query.

https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkZ9vRK0hiQVykQx3tTi?scode=AJsA6gc3AA86DSyJdmAawAhAZmAIk

**Comment by heni02** [comment]
test done，performance issue：#15191

**Comment by arjunsk** [comment]
Minor document update: https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkZ9vRK0hiQVykQx3tTi?scode=AJsA6gc3AA86DSyJdmAawAhAZmAIk

Added 

![image](https://github.com/matrixorigin/matrixone/assets/9638314/47b0d134-4996-4d75-99fe-a2e3501c9b49)

**Comment by heni02** [comment]
after performance improvment test again done

**Comment by heni02** [comment]
1.2 vector index benchmark 只测试了128dim和960dim 100万数据的性能，时间原因其他dim的性能可以再下一版本再测试

**Comment by aressu1985** [comment]
done
