### ISSUE TITLE
[Subtask]: support more create view grammar

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#10648]
### Parent Issue

#4374

### Detail of Subtask

/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`%` SQL SECURITY DEFINER */
/*!50001 VIEW `ces0020` AS select `a`.`QUERYID` AS `QUERYID`,floor(`a`.`ORGANIZATION_ID`) AS `ORGANIZATION_ID`,floor(`a`.`WAREHOUSE_ID`) AS `WAREHOUSE_ID`,`d`.`WAREHOUSE_CODE` AS `WAREHOUSE_CODE`,`d`.`WAREHOUSE_NAME` AS `WAREHOUSE_NAME`,`d`.`WAREHOUSE_PID` AS `WAREHOUSE_PID`,`h`.`WAREHOUSE_NAME` AS `WAREHOUSE_PNAME`,floor(`a`.`ITEM_ID`) AS `ITEM_ID`,`b`.`ITEM_CLASS3` AS `ITEM_CLASS3`,`b`.`ITEM_CODE` AS `ITNBR`,`b`.`ITEM_NAME` AS `ITDSC`,`a`.`COLORNUMBER` AS `COLORNUMBER`,`a`.`BASE_LEVEL_ID` AS `BASE_LEVEL_ID`,`e`.`LEVELNAME` AS `LEVELNAME`,`a`.`WIDTH` AS `PRDWID`,`a`.`LENGTH` AS `PRDLNG`,floor(`a`.`BASE_PADDR_ID`) AS `BASE_PADDR_ID`,`f`.`BASE_PADDR` AS `BASE_PADDR`,floor(`a`.`ASSISTANT_UOM_ID`) AS `ASSISTANT_UOM_ID`,floor(`c`.`UOM_ID`) AS `UOM_ID`,`c`.`UOM_NAME` AS `UOM_NAME`,floor(`a`.`INV_BATCH_ID`) AS `INV_BATCH_ID`,`a`.`QTY_CANDRAFIT` AS `QTY_CANDRAFIT`,`a`.`QTY_SUBSISTENCE` AS `QTY_SUBSISTENCE`,`a`.`QTY_PRESHIP` AS `QTY_PRESHIP`,`a`.`QTY_FREEZE` AS `QTY_FREEZE`,`a`.`QTY_ONHAND` AS `QTY_ONHAND`,`a`.`QTY_ONHAND2` AS `QTY_ONHAND2`,`a`.`INV_ITEM_ID` AS `INV_ITEM_ID`,`a`.`IS_PALLET` AS `IS_PALLET`,`a`.`INV_BATCH_CODE` AS `INV_BATCH_CODE`,`a`.`CUSTOMER_ID` AS `CUSTOMER_ID`,`a`.`CUSTOMER_CODE` AS `CUSTOMER_CODE`,`a`.`CUSTOMER_NAME` AS `CUSTOMER_NAME`,(`a`.`QTY_CANDRAFIT` - ifnull(`g`.`LOCKQTY`,0)) AS `USEFULQTY`,ifnull(`g`.`LOCKQTY`,0) AS `LOCKQTY`,`a`.`KULINGDAY` AS `KULINGDAY` from (((((((`skim`.`ces0020m` `a` join `skim`.`kaf_item` `b`) join `skim`.`kaf_uom` `c`) join `skim`.`kaf_warehouse` `d`) join `skim`.`kaf_base_level` `e`) left join `skim`.`kaf_base_paddr` `f` on((`a`.`BASE_PADDR_ID` = `f`.`BASE_PADDR_ID`))) left join (select sum(`skim`.`ces0021`.`LOCKQTY`) AS `LOCKQTY`,`skim`.`ces0021`.`ITNBR` AS `itnbr`,`skim`.`ces0021`.`WAREHOUSE_ID` AS `WAREHOUSE_ID`,`skim`.`ces0021`.`UOMID` AS `UOMID`,`skim`.`ces0021`.`COLORNUMBER` AS `COLORNUMBER`,`skim`.`ces0021`.`BASE_LEVEL_ID` AS `base_level_id`,`skim`.`ces0021`.`LENGTH` AS `LENGTH`,`skim`.`ces0021`.`WIDTH` AS `WIDTH`,`skim`.`ces0021`.`IS_PALLET` AS `IS_PALLET` from `skim`.`ces0021` where ((`skim`.`ces0021`.`VALIDYN` = 'Y') and (`skim`.`ces0021`.`LOCKTYPE` = '1')) group by `skim`.`ces0021`.`ITNBR`,`skim`.`ces0021`.`WAREHOUSE_ID`,`skim`.`ces0021`.`UOMID`,`skim`.`ces0021`.`COLORNUMBER`,`skim`.`ces0021`.`BASE_LEVEL_ID`,`skim`.`ces0021`.`LENGTH`,`skim`.`ces0021`.`WIDTH`,`skim`.`ces0021`.`IS_PALLET`) `g` on(((`b`.`ITEM_CODE` = `g`.`itnbr`) and (`a`.`WAREHOUSE_ID` = `g`.`WAREHOUSE_ID`) and (`a`.`ASSISTANT_UOM_ID` = `g`.`UOMID`) and (`a`.`COLORNUMBER` = `g`.`COLORNUMBER`) and (`a`.`BASE_LEVEL_ID` = `g`.`base_level_id`) and (`a`.`LENGTH` = `g`.`LENGTH`) and (`a`.`WIDTH` = `g`.`WIDTH`) and (`a`.`IS_PALLET` = `g`.`IS_PALLET`)))) left join `skim`.`kaf_warehouse` `h` on(((`d`.`WAREHOUSE_PID` = `h`.`WAREHOUSE_ID`) and (`d`.`ORGANIZATION_ID` = `h`.`ORGANIZATION_ID`)))) where ((`a`.`ITEM_ID` = `b`.`ITEM_ID`) and (`a`.`ASSISTANT_UOM_ID` = `c`.`UOM_ID`) and (`a`.`WAREHOUSE_ID` = `d`.`WAREHOUSE_ID`) and (`a`.`BASE_LEVEL_ID` = `e`.`BASE_LEVEL_ID`) and (`d`.`ACCOUNT_FLAG` = '1')) */;

**Comment by lacrimosaprinz** [comment]
support which syntax of alter table grammar?
