### ISSUE TITLE
[Bug]: 3c4.5g Resource Execution tpcc  causes CN OOM.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#10659]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
pod resource:
requests: 3 cpu 4.5g memory
limits: 3 cpu 4.5g memory

test case:
tpcc 10 warehouse 10 thread

cn.log：
[cn.log](https://github.com/matrixorigin/matrixone/files/12046867/cn.log)

**Comment by m-schen** [comment]
日志文件看不出来有利于分发bug的信息。

**Comment by m-schen** [comment]
@tianyahui-python 
标题是4c8g，描述里是3g4.5g，具体是什么情况呢。

以及麻烦需要提供一下该环境上发生oom时的profile文件。最好是内存的heap情况。

**Comment by tianyahui-python** [comment]
[heap.log](https://github.com/matrixorigin/matrixone/files/12049372/heap.log)

**Comment by m-schen** [comment]
简单讨论后目前的可疑点两个：
1. 首先是10并发的查询不应该超过4.5g的内存限制，这个占用过大了。（不过heap显示的占用为1.33g)
2. 内存限制为4.5g，超内存时不应该直接oom，应放慢执行速度。

**Comment by tianyahui-python** [comment]
> 首先是10并发的查询不应该超过4.5g的内存限制，这个占用过大了。（不过heap显示的占用为1.33g)

针对这个点, 应该是没有抓到oom的时候的内存信息, 这个有没有什么建议, 怎么能准确的抓取导致oom那一时刻的profile 信息

**Comment by m-schen** [comment]
> 

可能需要间隔一段时间抓一次。这个间隔应该也不用很短，如果不是很快oom的话，以分钟级（如5分钟）我感觉就可以了。另外就是heap（go tool pprof /debug/pprof/heap 类似的命令，具体细节我有点忘了）抓出来的应该是个压缩包格式，貌似不是.log。log貌似丢了些细节。

**Comment by m-schen** [comment]
> > 首先是10并发的查询不应该超过4.5g的内存限制，这个占用过大了。（不过heap显示的占用为1.33g)
> 
> 针对这个点, 应该是没有抓到oom的时候的内存信息, 这个有没有什么建议, 怎么能准确的抓取导致oom那一时刻的profile 信息

可能需要间隔一段时间抓一次。这个间隔应该也不用很短，如果不是很快oom的话，以分钟级（如5分钟）我感觉就可以了。另外就是heap（go tool pprof /debug/pprof/heap 类似的命令，具体细节我有点忘了）抓出来的应该是个压缩包格式，貌似不是.log。log貌似丢了些细节。

**Comment by nnsgmsone** [comment]
@tianyahui-python  cache的内存配置是多少呢

**Comment by nnsgmsone** [comment]
先修改cache的配置，目前cache的占用超过3Gb了。cache的大小控制在512MB左右后再看

**Comment by nnsgmsone** [comment]
![截图 2023-07-19 16-01-21](https://github.com/matrixorigin/matrixone/assets/31609524/bb888a1f-ef6c-4422-b3d9-ca401f96bd09)

**Comment by nnsgmsone** [comment]
fileservice cache只有512MB，此处应该存在一些内存上的泄露。。。继续定位

**Comment by nnsgmsone** [comment]
最大的内存泄露应该是由于fileservice cache的异步策略引起的。先fix这个

**Comment by nnsgmsone** [comment]
pr @10780修复了这个问题，不过cache的内存占用大小还是要比实际设置的要大一些。大约在1到2倍之间的一个范围

**Comment by nnsgmsone** [comment]
自测没问题，等待 @tianyahui-python 验证

**Comment by tianyahui-python** [comment]
`坚持了16分钟, pod oom了, 截图如下`: 
<img width="1318" alt="截屏2023-07-20 16 28 02" src="https://github.com/matrixorigin/matrixone/assets/39303074/4a1a1a8e-909a-4aa0-85cb-c2178eb5b016">
<img width="1239" alt="截屏2023-07-20 16 28 10" src="https://github.com/matrixorigin/matrixone/assets/39303074/719fd753-9890-45f5-8f72-39fde90fa29a">

**Comment by nnsgmsone** [comment]
测试的commit，pr尚未合入的。。应该验证错commit了。。。

**Comment by tianyahui-python** [comment]
已更新到最新版本, 正在测试中 ....

**Comment by tianyahui-python** [comment]
跑了差不多35min, pod 又挂了

<img width="1296" alt="截屏2023-07-20 20 28 56" src="https://github.com/matrixorigin/matrixone/assets/39303074/b7666c42-44b8-4fab-8dcf-38ba2c12dc00">


<img width="1134" alt="截屏2023-07-20 20 45 12" src="https://github.com/matrixorigin/matrixone/assets/39303074/13c0b9d4-286f-4f80-9eae-a9f134f68a6f">

cn.log
```
/mo-service -cfg /tmp/tmp.vckDIyxAZq -debug-http=:6060
{"level":"INFO","time":"2023/07/20 12:26:40.358989 +0000","caller":"logutil/internal.go:37","msg":"MO logger init, level=, log file=, stackLevel=panic"}
{"level":"INFO","time":"2023/07/20 12:26:40.359146 +0000","caller":"fileservice/local_fs.go:134","msg":"fileservice: memory cache initialized","fs-name":"LOCAL","config":{"MemoryCapacity":536870912,"DiskPath":"/var/lib/matrixone/data/local-cache","DiskCapacity":8589934592,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
{"level":"INFO","time":"2023/07/20 12:26:41.774059 +0000","caller":"fileservice/s3_fs.go:146","msg":"fileservice: memory cache initialized","fs-name":"SHARED","capacity":5905580032}
{"level":"INFO","time":"2023/07/20 12:26:41.774105 +0000","caller":"fileservice/s3_fs.go:166","msg":"fileservice: disk cache initialized","fs-name":"SHARED","config":{"MemoryCapacity":5905580032,"DiskPath":"/var/lib/matrixone/disk-cache","DiskCapacity":9663676416,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
{"level":"INFO","time":"2023/07/20 12:26:42.043528 +0000","caller":"fileservice/s3_fs.go:146","msg":"fileservice: memory cache initialized","fs-name":"ETL","capacity":5905580032}
{"level":"INFO","time":"2023/07/20 12:26:42.043576 +0000","caller":"fileservice/s3_fs.go:166","msg":"fileservice: disk cache initialized","fs-name":"ETL","config":{"MemoryCapacity":5905580032,"DiskPath":"/var/lib/matrixone/etl-cache","DiskCapacity":9663676416,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
{"level":"INFO","time":"2023/07/20 12:26:42.044400 +0000","caller":"motrace/trace.go:138","msg":"init GlobalBatchProcessor"}
{"level":"INFO","time":"2023/07/20 12:26:42.044447 +0000","caller":"export/batch_processor.go:365","msg":"MOCollector Start"}
{"level":"INFO","time":"2023/07/20 12:26:42.044579 +0000","caller":"motrace/trace.go:143","msg":"init trace span processor"}
{"level":"INFO","time":"2023/07/20 12:26:42.053301 +0000","caller":"logservice/hakeeper_client.go:559","msg":"isHAKeeper: true, err: <nil>"}
{"level":"ERROR","time":"2023/07/20 12:26:57.054409 +0000","name":"cn-service.etl/db_holder","caller":"db/db_holder.go:161","msg":"sqlWriter db init failed","uuid":"33396563-3439-6332-3961-663432373635","MODiscardable":true,"error":"invalid state SQL writer's DB conn not ready"}
{"level":"ERROR","time":"2023/07/20 12:27:11.943757 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:515","msg":"read from backend failed","remote":"default-log-2.default-log-headless.freetier-01.svc:32001","backend-id":"b8d95331-a385-4b84-aab0-23e007098afb","error":"illegal state"}
{"level":"ERROR","time":"2023/07/20 12:27:11.943846 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:519","msg":"read loop stopped","remote":"default-log-2.default-log-headless.freetier-01.svc:32001","backend-id":"b8d95331-a385-4b84-aab0-23e007098afb"}
{"level":"ERROR","time":"2023/07/20 12:27:11.948888 +0000","name":"hakeeper-client-backend","caller":"v2@v2.0.0-20230628075727-26c9a2fd5fb8/session.go:515","msg":"close conneciton failed","remote":"default-log-2.default-log-headless.freetier-01.svc:32001","backend-id":"b8d95331-a385-4b84-aab0-23e007098afb","session-id":0,"error":"close tcp4 172.25.161.144:60992->172.25.173.203:32001: use of closed network connection"}
{"level":"ERROR","time":"2023/07/20 12:27:11.954040 +0000","name":"rpc-client[hakeeper-client([connectToHAKeeper])]","caller":"morpc/client.go:368","msg":"gc inactive backends task stopped"}
panic: timeout

goroutine 1 [running]:
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:98 +0x3ff

```

**Comment by nnsgmsone** [comment]
@m-schen 帮忙继续跟一下这个问题，这个问题是因为多轮tpcc导致的，单论tpcc时间就算很长也不会oom

**Comment by m-schen** [comment]
但是今天并没有进展，很尴尬。

**Comment by fengttt** [comment]
Please update assignee if you want to hand over, @nnsgmsone @m-schen

**Comment by m-schen** [comment]
暂时排除与session退出时没有正确清理proc属性以及session本身的resultBatch的原因。
<img width="1433" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/afbbbc54-6652-44e8-b489-e8150cf73a3f">
图为最新的main分支本地单cn，服务刚启动时的内存占用，与分别跑6轮 1分钟的单仓单并发tpcc （保证他们是6个session) 后的内存占用。

**Comment by m-schen** [comment]
相关分支：
https://github.com/m-schen/matrixone/tree/fix-10659

在本地测试似乎内存不会涨了，还需要进一步确定。

**Comment by m-schen** [comment]
这个等测试回来帮忙验证一下试试。

**Comment by m-schen** [comment]
与内存泄漏无关。

暂时确定为跑该测试时，给fileservice以及metadata的cache设置得太大导致4.5g被cache占满了导致的。需要多跑个一两天看看情况。

**Comment by m-schen** [comment]
多跑两天，没问题的话就可以关掉或者降级了。

**Comment by nnsgmsone** [comment]
cache改小后并不会出再oom，不过存在短时间内存会激增一下的情况。。正在排查。

**Comment by nnsgmsone** [comment]
目前plan的大小过于庞大，对于一个tpcc的sql而言，plan的大小约为7.6MB。。。有点恐怖

**Comment by tianyahui-python** [comment]
> cache改小后并不会出再oom，不过存在短时间内存会激增一下的情况。。正在排查。

由于目前修改cache 后不再出现oom现象, 仅存在短时间内 内存会激增的情况, 故bug级别调整为s1

**Comment by sukki37** [comment]
Outdated issue, temporarily closed for now. A specific test for minor code changes will be conducted soon. If there are any problems, please raise the issue again.
