### ISSUE TITLE
[Bug]: eks oltp-insert daily regression performance drops a lot

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#10654]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1650" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/6ef6a66f-977c-47df-beb2-b5ed8458c22a">

http://grafana.matrixorigin.cn:31080/d/dAUW-wJ4z/oltp_eks_summary?orgId=1

**Comment by zengyan1** [comment]
正在定位问题中

**Comment by zengyan1** [comment]
经复测，上图的结果为dailyrun的正常误差，7月8日至7月14日区间oltp-insert性能没有较大变化
