### ISSUE TITLE
[Tech Request]: improve check pk dup in some case

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#10655]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
1、insert into t1(pk_col, other_col) values (1,1),(2,2),(3,3)。 
   now plan will use a join to do check pk dup.
   we can change to table_scan with filter like  pk_col in (1,2,3) to do that.

2. update t1 set pk = 10 where xx = xx
   now plan will use a join to do check pk dup.
   we can change to table_scan with filter like  pk = 10 to do that

3. have t1 (a int auto_increment primary key, b int, c int);
   insert  into t1(b, c) values (1,1),(2,2).    do not need check pk dup  (need add this logic)
   insert into t1(a,b,c) values (10,1,1)  need check pk dup

4. because getConstanValue do not support uuid type(root cause is we have no expr_const type for uuid），
    so if we have pk in uuid type. we can not use pk=xx to improve performance in checking pk dup

5. normal case, not check pk dup.
    when insert table which have no primary key.  we do not need lock the rows.
    update/delete 还是要lock rows

6、系统租户比一般租户快的bug

7、增加一个session的flag，用户如果确认不需做去重的话，那么跳过

8、load的时候，lock table，不做去重。等insert结束后，跑一个检测语句
   （select count(pk) as ttl from tbl group by pk having ttl >  1？待讨论) 如果有值，说明有重复。则报错

9、当悲观事务都ok的时候，DN的去重应该可以都去掉

10、降低S3延时对TP读写的性能影响

```

**Comment by ouyuanning** [comment]
1、insert into t1(pk_col, other_col) values (1,1),(2,2),(3,3)。 
   now plan will use a join to do check pk dup.
   we can change to table_scan with filter like  pk_col in (1,2,3) to do that.
==> done

2. update t1 set pk = 10 where xx = xx
   now plan will use a join to do check pk dup.
   we can change to table_scan with filter like  pk = 10 to do that
==> 由于update没法像insert那样直接用table scan+ filter来简单检测重复。似乎没有多少优化空间。先暂停，还要再想想

3. have t1 (a int auto_increment primary key, b int, c int);
   insert  into t1(b, c) values (1,1),(2,2).    do not need check pk dup  (need add this logic)
   insert into t1(a,b,c) values (10,1,1)  need check pk dup
==> done

4. because getConstanValue do not support uuid type(root cause is we have no expr_const type for uuid），
    so if we have pk in uuid type. we can not use pk=xx to improve performance in checking pk dup
==> done

5. normal case, not check pk dup.
    when insert table which have no primary key.  we do not need lock the rows.
    update/delete 还是要lock rows
==> done

**Comment by jensenojs** [comment]
在实现8，并进一步用布隆过滤器来取代insert的去重的时候，的时候遇到一些cases的特判，一方面是正确性保证的需求要讨论这个问题，另一方面也是优化，所以mark一下，原本的一些分类需要被重新讨论。

——诸如`checkInsertPkDup`和`CNPrimaryCheck`的区分。

1. 
说回来现在对于`update`类型的insert有一些细分的cases
```sql
create table t1 (
a tinyint not null,
primary key (a));
insert into t1 (a) values (1),(2),(3);
update t1 set a=a+1 where 3 > 2;
```
对于主键的修改（即`updatePkCol`为true的情况下，类似a=a+1）这种表达式在 where的条件始终为`true`的时候是不需要进行去重检测的。但是当`where`的条件不能保证一直为`true`的时候，需要进行去重检测。

目前在实现上遇到了一些问题，导致上面的`update t1 set a=a+1 where 3 > 2;`无法通过，还在看怎么fix

2. 
包含`on duplicate update`的SQL如果在`runOnce`的阶段执行成功了，就没有必要 && 不应该再去起后台SQL去检验有没有重复的key，因为如果有，on duplicate update会处理，处理成功的话事情就完了，处理失败的话直接返回对应的error即可。这个已经做了。

**Comment by jensenojs** [comment]
话说`update t1 set a=a+1 where 3 > 2;` 这个SQL，sql server，Oracle都支持，mo支持也很合理，虽然也有挺多db不支持的。
<img width="359" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/3b49a2b8-3105-4eae-bf89-ea51d5f8106a">

目前的方案`8`在plan上大概就是下图这个流程。
<img width="830" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/02d205a8-4fe8-4523-84ff-9f026846efca">

所以`update t1 set a=a+1 where 3 > 2;` 会把`(1, 2, 3)`和`(2,3,4)`都送到布隆过滤器，然后就报错了，猜想`mysql`, `duckdb`， `pg`等可能也是类似实现。

要想让`fuzzy filter`下对于这个`update`进行支持，我的理解似乎得保证**update后的数据库跟没有被修改的数据之间交集为空**，但如果这样的话`plan`似乎得小重构一下，我不是太确定工作量。

以及我不知道mo是怎么把这个`update`的语法给支持了的，所以我上面的理解应该漏了些东西

**Comment by jensenojs** [comment]
关于 fuzzyFilter的优化
#12846

**Comment by jensenojs** [comment]
# pk filter pprof

这个comment讨论在开发fuzzy filter的时候遇到pk filter的性能问题

背景是pk filter理论上效果应该比runtime filter要好, 但现在并不是, 解析pk filter时的常量折叠解析在某些场景下的耗时很大, 使用客户数据集dml_001在调高`maxRowThenUnusePkFilterExpr`的上限之后即可复现, dml_001中的表比较多但都比较小, 主键类型基本上是varchar (复合主键也是varchar, 但不确定复合主键有没有其他特殊的地方.?), insert的batchsize大概在两千到三千. 对照组是shuanghe_001, 它的大表主键类型是BIGINT, insert的batchsize大概在一万四左右.

## 对比

### BIGINT as primary key
<img width="1546" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/593ed721-0546-46e1-ac5e-076757476e6d">

### varchar as primary key

<img width="1546" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/e67e99e2-77b1-4d5c-b37d-e903274853ef">

其中最耗时的操作是`IsConstant`中的`GetFunctionByIdWithoutError`.
<img width="1546" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ab5d5164-84ad-4d17-a40e-e104f4ecc87e">

**Comment by ouyuanning** [comment]
去重优化暂时先做到这里吧。以后还有需要优化的地方另外开issue
