### ISSUE TITLE
[Bug]: cn panic because of "interface conversion: vm.InstructionArgument is *dispatch.Argument, not *connector.Argument"

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#10657]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-8911e24d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"ERROR","time":"2023/07/14 02:42:03.809762 +0000","name":"cn-service","caller":"v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:345","msg":"handle session failed","uuid":"37353333-3735-6435-3132-303763653436","name":"cn-server","listen-addresses":"[0.0.0.0:6002]","error":"read tcp4 172.25.167.30:6002->172.25.174.222:34690: read: connection reset by peer"}
panic: interface conversion: vm.InstructionArgument is *dispatch.Argument, not *connector.Argument

goroutine 541247 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).remoteRun(0xc11b16f930, 0xc0144ba480)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scopeRemoteRun.go:283 +0x445
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc11b16f930, 0xc0144ba480)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:195 +0x2d4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0xc014ad1470?)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:122 +0x2f
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:121 +0x1f8
```

### Additional information

there is two cn in mo cluster, maybe this is because of multi cn communication？

full cn log:
[default-cn-0.log](https://github.com/matrixorigin/matrixone/files/12045931/default-cn-0.log)

full dn log:
[dn.log](https://github.com/matrixorigin/matrixone/files/12045992/dn.log)

**Comment by m-schen** [comment]
remote run原先是默认最后一个算子是connector时才发往其他cn进行执行。这是最初的设计。

后续加入dispatch后可能也会产生这种情况吧。两个算子都是负责分发的。
这边改成不要直接做断言就好。

**Comment by jensenojs** [comment]
wait for merge

**Comment by jensenojs** [comment]
waitting for merge

**Comment by jensenojs** [comment]
还有些问题，明天看一下

**Comment by sukki37** [comment]
#10669 has been reverted.

**Comment by jensenojs** [comment]
初步怀疑是原先代码中dispatch中对bat.Cnt的操作哪里有问题。
<img width="1259" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/1c9d8498-5eec-4fea-943e-610132bde673">

但是目前在dispatch中加的日志都没有被触发，还需要继续排查。
https://github.com/jensenojs/matrixone/commit/827aa9d4da41db1ef1cca986bbfd0997499e8b6f

**Comment by jensenojs** [comment]
进一步在connector, dispatch，receive_operator中打印更多关于bat.Cnt的log，发现有大量的bat.Cnt == 0的情况，需要确认这种情况是不是UB

<img width="1312" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b1e47e1d-6765-4d85-b928-bad95697407c">

**Comment by jensenojs** [comment]
找到了一个问题，还待校验一下

**Comment by jensenojs** [comment]
这个pr会被卡住的原因是悲观事务下的bvt过不了。
但同时我在本地用upstream main 跑了一轮悲观事务的模拟的multi-CN的bvt，就是会有fail的cases，偶发，报错的sql不稳定，但并不罕见。

昨天跟沁璇姐讨论了一下之前pr会导致bat读取数据不对的root cause，原来把该用Scope.Process的地方用成了Compile.Process，这肯定是不对的，混用了Scope在算子间传递batch的数据成员，会造成UB。

但是目前，算子都是用自己的 scope 的 Proc 去传递 inputBatch的，在这个背景下Compile的process还能传递Batch这个事情只会让人困惑，如果真的让算子的scope的proc去传递batch的话，那原本的写法为什么能有正常通过的时候也会很奇怪。这个地方的代码写的很乱，需要重构。举例：像[NewWithAnalyze](https://github.com/jensenojs/matrixone/blob/main/pkg/vm/process/process.go#L66)这种函数真正有用的部分实际上只有针对scope赋值自己的MergeReceivers的时候有意义，为了这个事情process的所有数据成员都要额外做一遍复制黏贴的操作，这是很奇怪的。

重构的一个思路是把像`MergeReceivers`这样的东西从`Process`中拿出来，放到比如说`Scope`中，这样Compile到Run的阶段就不需要再创建新的Process。

讨论的结果需要与莫尘确认。
1. 有谁还在用Compile.Process传递Batch
2. 上述重构思路是否合理

对于Process的重构可能作为Pipeline重构的子任务进行

**Comment by jensenojs** [comment]
今天找莫尘讨论一下

**Comment by jensenojs** [comment]
周一

**Comment by jensenojs** [comment]
<img width="1518" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/672f2d2a-6786-4729-9c0b-a75d241e8735">

还是有新的问题。。

**Comment by jensenojs** [comment]
<img width="1944" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/c97799c9-7510-4c6d-942f-574ff4c5b027">

https://github.com/jensenojs/matrixone/actions/runs/5722023346/job/15504466189

应该是新的bug
