### ISSUE TITLE
[Bug]: organize pessimistic MySQL behavior

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10667]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There is currently no global understanding of pessimistic behavior. It is only through testing that unclear situations are discovered. It is necessary to organize all behaviors under MySQL pessimistic RC，plz@domingozhang

**Comment by domingozhang** [comment]
https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUfig5dvIwR1eglf01BV?scode=AJsA6gc3AA83zTN1GhALQAjwY-ACU
Please check

**Comment by heni02** [comment]
closed
