### ISSUE TITLE
[Bug]: performance: concurrent 500 ,under statements_info directory CSV data over 700 GB

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10663]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):be18792d6a284ef47084003e15be036c937760dd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

disableStmtAggregation = true ，under non sys account  concurrent 500 insert into values sqls ,mo run 1hours+, etl statements_info directory csv data over 700GB，occupying a large amount of storage space,this is first problem
mo config ： disableStmtAggregation = true
<img width="1339" alt="企业微信截图_fa29679c-48eb-4fc3-b39e-af1b772133b0" src="https://github.com/matrixorigin/matrixone/assets/113406637/72ff8685-a8ba-48fb-a8f5-c1dc858413f1">

and second problem is： mo does not execute any SQL, csv data 700G+  insert into statement_info performance  is very slow, with 250G data cost 1 hour and 20 minutes
![image](https://github.com/matrixorigin/matrixone/assets/113406637/48f064ee-e776-48a0-8113-165a91c6fc9c)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/869cc299-65ce-4fcf-a7aa-9d133ec6397f)

### Steps to Reproduce

```Markdown
start mo: 2cn
Concurrent 100 inserts, run for 80 minutes, and select statement，
Concurrent 100 inserts use mo-load tool:
1.git clone https://github.com/matrixorigin/mo-load.git
2.config case insert run.yaml, path:cases/ddl/run.yaml
vuser: 500 
- sql: "insert into r1 values ({tbx});"
3.login mysql ,create database db; use db; create table r1(c1 int);
4. ./start.sh -c cases/ddl/
```

**Comment by heni02** [comment]
@xzxiong @gavinyue plz confirm this issue

**Comment by xzxiong** [comment]
first of all, this case really need to run with mo config `disableStmtAggregation = false`
secondly, `250G data cost 1 hour and 20 minutes` that because of running only with one task in one goroutine. this speed seems ok. 
the key problem: when it will be downgraded to write csv files

**Comment by gavinyue** [comment]
Known issue. But do not have a good solution here.

**Comment by heni02** [comment]
disableStmtAggregation = false ，under non sys account concurrent 500 insert into values sqls 
more than 2hours15min+， etl statements_info directory csv data over 300GB
<img width="914" alt="企业微信截图_1808c65a-c49c-4e4d-8f0a-c441a46f03ac" src="https://github.com/matrixorigin/matrixone/assets/113406637/f0aaba20-ebee-49f2-b456-569f71c350dd">

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Still pending. Not easy one.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
这个还没好的处理办法

**Comment by gavinyue** [comment]
性能问题，  来不及修复了， 推迟一下

**Comment by gavinyue** [comment]
这个还没来得及看

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Should be solved. Will talk with heni

**Comment by gavinyue** [comment]
在处理

**Comment by gavinyue** [comment]
wait for load to merge

**Comment by gavinyue** [comment]
PR merged. Will talk with heni

**Comment by gavinyue** [comment]
Same here. Using Load should have boosted performance

**Comment by heni02** [comment]
@gavinyue 请关联解决的pr再转测试回归验证

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/12115

**Comment by gavinyue** [comment]
请测试麻烦看一下

**Comment by heni02** [comment]
confirm,closed
默认聚合功能打开，普通租户下并发500 insert持续跑3个小时，插入2亿多条sql，statement_info共4千6百多万行
<img width="1044" alt="企业微信截图_d6f8c478-39e2-4b70-a615-f7adcc4d7668" src="https://github.com/matrixorigin/matrixone/assets/113406637/c4c21b3b-c5c1-4908-8861-f05c75900fd4">
<img width="510" alt="企业微信截图_5891174a-0221-4d5a-948c-a14596ffbf19" src="https://github.com/matrixorigin/matrixone/assets/113406637/b6f811f6-6bf8-4ad2-a1f2-2f19bbbf5cf9">

etl大小只有几十k：
<img width="446" alt="企业微信截图_7c2880dc-edf9-4d2e-b54e-de1210f72185" src="https://github.com/matrixorigin/matrixone/assets/113406637/2a153c86-83c5-4da9-8175-d01c931ae97f">
