### ISSUE TITLE
No OS information in Readme installation charpter

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1067]
#### Steps:
One external user install matrixone in linux with vmware, however his OS is Mac OS. He gave me the feedback that no OS information can be found in installation charpter. So that he didn't know matrixone can run in Mac directly.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by anitajjx** [comment]
README has been updated with information about the supported OS.
