### ISSUE TITLE
[Bug]: database cannot restart if change a few configs

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10674]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[cn.txn]
mode = "Pessimistic"
[dn.txn]
mode = "Pessimistic"
Start launch 2cn, pessimistic mode.    run a few tests, shutdown database.

Now, change the following to true in cn.toml,
[cn.txn]
mode = "Pessimistic"
enable-sacrificing-freshness = true
enable-cn-based-consistency = true

launch cannot start, with some r-w conflicts error.

### Expected Behavior

The fix, may simply be that we get rid of all these parameters.   
@zhangxu19830126 

On the other hand I think we should try switch from Optimistic to Pessimistic and see if it can restart.

**Comment by triump2020** [comment]
cannot repro  change config from optimistic to pessmistic : 
    1.  run optimistic mode for a few minutes
    2. then change config to pessmistic ,restart.

**Comment by triump2020** [comment]
being repro

**Comment by triump2020** [comment]
haven't repro yet , @fengttt  pls downgrade or close it.

**Comment by triump2020** [comment]
@fengttt pls close it

**Comment by fengttt** [comment]
close as not repro, and those params are retired anyway.
