### ISSUE TITLE
[Subtask]: Support aggregate function in engine.Reader

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#10687]
### Parent Issue

#7263

### Detail of Subtask

Add some new interfaces to engine.Reader, in order to quickly get aggregate result without reading block data.

For dirty blocks which has some rows deleted or updated, read the exact data. For clean intact blocks, use metadata as a shortcut.

**Comment by zengyan1** [comment]
pr已合入，测试将由
https://github.com/matrixorigin/MO-Cloud/issues/248
跟进
