### ISSUE TITLE
[Subtask]: Save query result with cloud user hint

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10691]
### Parent Issue

#8836 

### Detail of Subtask

In MO Cloud, user's query result can be automatically saved with parameter on for save_query_result.

Examlple :
select /* cloud_user */  c1,c2 from t1;  
Then this result will be saved.

**Comment by LiSong0214** [comment]
有几个问题：
1、/* cloud_user */  固定开头就行；
2、开放一个其他的方式触发开关生效（因为cloud_user看起来更加定制化，不适合开放给私有化用户），例如 /* save_result */
3、/* save_result */和 /* cloud_user */ 都是在save_query_result开关打开后才能生效。

**Comment by domingozhang** [comment]
set save_query_result=on
/* cloud_user */ select * from t1;  ---- save query result
/\* other_words */ select * from t1;  ---- do not save query result
/\* save_query */ select * from t1;  ---- save query result


set save_query_result=off
/\* cloud_user */ select * from t1;  ---- do not save query result
/\* other_words */ select * from t1;  ---- do not save query result
/\* save_query */ select * from t1;  ---- do not save query result

**Comment by YANGGMM** [comment]
finished， plz test

**Comment by heni02** [comment]
一.set global save_query_result = on 测试
1./* save_result */是否生效，测试结果保存结果，符合预期
<img width="674" alt="企业微信截图_fc3c5272-d946-4835-829d-bca27a505ffc" src="https://github.com/matrixorigin/matrixone/assets/113406637/6a166da0-3d54-4a81-9f37-6b9558c3db92">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f7ed2934-0422-4c49-aa10-e623549ca725)
2./* cloud_user */是否生效，测试结果保存结果，符合预期
<img width="895" alt="企业微信截图_9e248dad-f254-43e2-91eb-d2c8a796e328" src="https://github.com/matrixorigin/matrixone/assets/113406637/9fc0cf2b-abb5-4947-a207-80543fd8bac2">
3.其他hint是否生效，测试结果不保存结果，符合预期，但报错信息建议可读性好一些
<img width="1159" alt="企业微信截图_c22a09cb-1e13-4e29-a2ff-a5a96ddd0bf6" src="https://github.com/matrixorigin/matrixone/assets/113406637/ad44e38b-695a-4801-8091-e0a1b60d7df2">


二. set global save_query_result = off 测试
1./* save_result */,* cloud_user */是否生效，测试结果不保存结果，符合预期
<img width="682" alt="企业微信截图_256e7715-3de6-46c0-b2b9-c4e2c62dde69" src="https://github.com/matrixorigin/matrixone/assets/113406637/f5f126fb-0e2c-4cff-ba4d-1c376afe0b11">
<img width="679" alt="企业微信截图_e2633fc2-89c2-48f8-9efb-04c22ccf675e" src="https://github.com/matrixorigin/matrixone/assets/113406637/355298cf-063e-4813-bc8c-bfc565c63845">

**Comment by heni02** [comment]
test done

**Comment by tianyahui-python** [comment]
需要测试更多的场景: 比如show 语法、explain 语法、各种join聚合语法 等, 之前发现过类似上述bug

**Comment by heni02** [comment]
补充测试：
set global save_query_result = on ，/* cloud_user */测试
1.show 命令：
/* cloud_user */show variables like 'tx_isolation';
<img width="1109" alt="企业微信截图_56c5eaee-cc67-4a38-bf20-7d5d722fbe62" src="https://github.com/matrixorigin/matrixone/assets/113406637/d6a1961e-164f-4e4f-a111-d3cf758c8ab7">
 /* cloud_user */show databases;
select * from result_scan(last_query_id()) as u;
<img width="690" alt="企业微信截图_efdff603-a5e0-45dc-ba08-d06da1d52214" src="https://github.com/matrixorigin/matrixone/assets/113406637/508b719a-b598-4ea7-92b5-977e6e89e69c">
/* cloud_user */show columns from t1;
<img width="678" alt="企业微信截图_d667782b-7289-4d75-a141-e0c15c55c2c9" src="https://github.com/matrixorigin/matrixone/assets/113406637/af2a10d0-c609-44d8-95de-b244b35ce685">
/* cloud_user */show grants;
<img width="677" alt="企业微信截图_5e631915-eabc-4cbb-afa4-379933b8b8cd" src="https://github.com/matrixorigin/matrixone/assets/113406637/a4663eda-dedd-40ec-9c12-710309c56dc4">
/* cloud_user */show create table t1;
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ae634889-a74b-4020-8c65-f4a4f5c16d8e)


5.create table t1(
a int,
b varchar(10)
);
insert into t1 values (111, 'a'),(110, 'a'),(100, 'a'),(000, 'b'),(001, 'b'),(011,'b');
/* cloud_user */select distinct b from t1;
<img width="986" alt="企业微信截图_857a6335-64d9-42e0-84ed-7db7fd1b1894" src="https://github.com/matrixorigin/matrixone/assets/113406637/dee6f772-b106-4eb0-ac5e-2bc1fe8ed700">

**Comment by heni02** [comment]
test done

**Comment by LiSong0214** [comment]
@aressu1985 这个issue 可以关了，但我没权限，你来吧
