### ISSUE TITLE
[Bug]: SSB and Load failed in Pessimistic Mode

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10708]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5560025425

**Comment by ouyuanning** [comment]
提了个PR把lock table提前。并且优化了下external scan的内存。
不确定是否就是failed的原因

**Comment by ouyuanning** [comment]
无进展。等10721合并后的daily run结果再看看

**Comment by ouyuanning** [comment]
估计是之前LoadTag被不小心注释掉导致的
