### ISSUE TITLE
[Feature Request]: Shared Lock in Pessimistic Mode

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10701]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

A kind of lock that allows other transactions to read the locked object, and to also acquire other shared locks on it, but not to write to it. The opposite of exclusive lock.

- A shared lock for a table can be acquired by multiple sessions at the same time. In addition, other sessions can shared data from the table without acquiring the lock.
- The session that holds the shared lock can only shared data from the table, but cannot write. And other sessions cannot write data to the table until the shared lock is released. The write operations from another session will be put into the waiting states until the shared lock is released.
- If the session is terminated, either normally or abnormally, MySQL will release all the locks implicitly. This feature is also relevant for the WRITE lock.

**Comment by zhangxu19830126** [comment]
We implement shared locks and exclusive locks by #11649  and #11657

**Comment by domingozhang** [comment]
LOCK TABLE
UNLOCK TABLES
these will be implemented in 1.1
https://github.com/matrixorigin/matrixone/issues/4971

**Comment by zhangxu19830126** [comment]
lockservice shared lock support done

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.
