### ISSUE TITLE
[Bug]: log service can not start after upgrading commit to d8e84ac from 81a695b

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10706]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d8e84ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

og service can not restart after upgrading commit to d8e84ac from 81a695b, and the error is:
/mo-service -cfg /tmp/tmp.aAWMm2Uj4Z -debug-http=:6060
{"level":"INFO","time":"2023/07/17 02:32:32.635761 +0000","caller":"logutil/internal.go:37","msg":"MO logger init, level=info, log file=, stackLevel=panic"}
{"level":"INFO","time":"2023/07/17 02:32:32.636010 +0000","caller":"fileservice/local_fs.go:133","msg":"fileservice: memory cache initialized","fs-name":"LOCAL","config":{"MemoryCapacity":536870912,"DiskPath":"/var/lib/matrixone/data/local-cache","DiskCapacity":8589934592,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
{"level":"INFO","time":"2023/07/17 02:32:32.719312 +0000","caller":"fileservice/s3_fs.go:146","msg":"fileservice: memory cache initialized","fs-name":"SHARED","capacity":536870912}
{"level":"INFO","time":"2023/07/17 02:32:32.719395 +0000","caller":"fileservice/s3_fs.go:166","msg":"fileservice: disk cache initialized","fs-name":"SHARED","config":{"MemoryCapacity":536870912,"DiskPath":"/var/lib/matrixone/data/s3-cache","DiskCapacity":8589934592,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
{"level":"INFO","time":"2023/07/17 02:32:32.752091 +0000","caller":"fileservice/s3_fs.go:146","msg":"fileservice: memory cache initialized","fs-name":"ETL","capacity":536870912}
{"level":"INFO","time":"2023/07/17 02:32:32.752159 +0000","caller":"fileservice/s3_fs.go:166","msg":"fileservice: disk cache initialized","fs-name":"ETL","config":{"MemoryCapacity":536870912,"DiskPath":"/var/lib/matrixone/data/etl-cache","DiskCapacity":8589934592,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
{"level":"INFO","time":"2023/07/17 02:32:32.752343 +0000","caller":"fileservice/local_fs.go:133","msg":"fileservice: memory cache initialized","fs-name":"SHARED","config":{"MemoryCapacity":536870912,"DiskPath":null,"DiskCapacity":8589934592,"DiskMinEvictInterval":"7m0s","DiskEvictTarget":0.8}}
panic: Duplicate Family Name LOG 00000000-0000-0000-0000-000000000000 SHARED

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/util/metric/stats.(*Registry).Register(0x400013e700, {0x400104a5d0, 0x2f}, {0x4001059918, 0x1, 0x0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/util/metric/stats/registry.go:39 +0x198
github.com/matrixorigin/matrixone/pkg/util/metric/stats.Register(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/metric/stats/registry.go:97
main.(*Config).createFileService(0x4001260000, {0x2b22388, 0x400011e000}, {0x26dc4f3, 0x5}, 0x4000fb3c00, 0x1221e78?, {0x4000055230, 0x24})
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/config.go:272 +0x66c
main.startService({0x2b22388, 0x400011e000}, 0x25c1de0?, 0x4001260000?, 0x400007c6c8?)
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:140 +0xb0
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:97 +0x278

### Expected Behavior

the log service should start normally

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/pull/10700

**Comment by aressu1985** [comment]
fixed
