### ISSUE TITLE
Database service cannot be restarted after modifying max-replicas

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1071]
#### Can be reproduced ?
Yes

#### Steps:
Modify max-replicas from 1 to 0 or 2 and database service cannot be restarted normally.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 693ab24c885ee26df6fe5ad467dd46c7cbdbe950
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by domingozhang** [comment]
2021/11/11 17:51:36.550791 [info] prophet: prophet logger set
2021/11/11 17:51:36.551628 +0800 INFO db-server/main.go:147 Load config error:update parameter maxReplicas failed.error:setMaxReplicas,the value 2 is not in the range [1,1]

**Comment by sukki37** [comment]
maxReplicas is limited to 1 in  `pkg/config/system_vars.go `, pls check following lines:

- https://github.com/matrixorigin/matrixone/blob/main/pkg/config/system_vars.go#L1308
- https://github.com/matrixorigin/matrixone/blob/main/pkg/config/system_vars.go#L2516

@daviszhen

**Comment by daviszhen** [comment]
It is not a issue.

It is simple for us to change the configuration:

1. change `maxReplicas` in `cmd/generate-config/system_vars_def.toml`
The `values[0]` means the value we want.
The `values[1]` means the minimum.
The `values[2]` means the maximum. 
So, In the case, we can change the values like `values = ["2", "1", "2"]`.

```
[[parameter]]
name = "maxReplicas"
scope = ["global"]
access = ["file"]
type = "int64"
domain-type = "range"
values = ["2", "1", "2"]
comment = "the number of replicas for each resource"
update-mode = "dynamic"
```

2. `make config ; make build`
