### ISSUE TITLE
[Bug]: create view in pessimistic mode wait for lock.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10712]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d8e84ac965d2d7451add3045e798ae93a23132d5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1891" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/dfe13baa-8f8f-40cd-8137-9ef666674def">

[log.txt](https://github.com/matrixorigin/matrixone/files/12065971/log.txt)

It can't be reproduced locally.

### Steps to Reproduce

```Markdown
in mo-tester:
./run.sh -n -g -p /matrixone/test/distributed/cases/view/view-subquery-with-in.sql -m run
```

**Comment by Ariznawlll** [comment]
Same behavior as before.
<img width="1880" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8ded87b4-6d32-43a5-b70f-416f831ba14b">

**Comment by ouyuanning** [comment]
就是当ddl语句执行，在commit失败后，需要执行unlock操作的问题。

**Comment by Ariznawlll** [comment]
<img width="1901" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8d322b5d-292a-450c-a0b1-c12046be4782">

Verified!
