### ISSUE TITLE
[Bug]: create database failed by ExpectedDup  in bvt test on storage compatibility test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10734]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 05ab962
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

from commit: f1c9a05 to commit: 05ab962, just upgrading images and all the data including logtail and mo-data retained, and  running bvt test, there are some errors:

2023-07-17 17:17:02 INFO  Executor:241 - The script file[/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/dml/delete/delete_multiple_table.sql] has been executed, and cost: 0.878s, total:91, success:89, failed:0, ignored:2, abnoraml:0
2023-07-17 17:17:02 INFO  Executor:33 - Start to execute the script file[/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/dml/insert/insert.test] now, and it will take a few moment,pleas wait......
**2023-07-17 17:17:02 ERROR Executor:580 - create database insert is failed.cause: ExpectedDup**
2023-07-17 17:17:02 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/dml/insert/insert.test][row:7][create table names(id int PRIMARY KEY,name VARCHAR(255),age int);] was executed failed, con[id=0, user=dump, ***
2023-07-17 17:17:02 ERROR Executor:223 - [EXPECT RESULT]:
null
2023-07-17 17:17:02 ERROR Executor:224 - [ACTUAL RESULT]:
not connect to a database
2023-07-17 17:17:02 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/dml/insert/insert.test][row:8][insert into names(id, name, age) values(1,"Abby", 24);] was executed failed, con[id=0, user=dump, ***
2023-07-17 17:17:02 ERROR Executor:223 - [EXPECT RESULT]:
null
2023-07-17 17:17:02 ERROR Executor:224 - [ACTUAL RESULT]:
no such table .names

the mo log:
{"level":"ERROR","time":"2023/07/17 17:17:02.598652 +0000","caller":"frontend/util.go:522","msg":"query trace status","connection_id":2004,"statement":"create database IF NOT EXISTS `insert`","status":"fail","error":"ExpectedDup","span":{"trace_id":"bef4de4c-24c5-11ee-9b08-aa5644c2397e","kind":"statement"},"session_info":"connectionId 2004|10.0.104.152:46768|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 5431|78e94236-24c5-11ee-9b08-aa5644c2397e"}

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5578488619/jobs/10193004458

mo log:
http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cpt%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

### Expected Behavior

all the bvt test should be succeeded for this cases

### Steps to Reproduce

```Markdown
1.run mo cluster with commit: f1c9a05
2.run bvt test
3.delete the mo cluster with commit: f1c9a05, and run a new mo cluster with commit:05ab962 with old data
4.run bvt test again
```

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/b0b22ebd-9bea-4cf6-8b13-d31adca4e1f9)
Cannot reproduce this issue on my machine.

**Comment by m-schen** [comment]
CreateDatabase等ddl流程，在判断是否已经存在该database, table的流程可能有点问题。目前是拿err == nil来判断database不存在的。not sure.

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/3010196c-9826-48c5-9bda-0b1aacf08159)
![image](https://github.com/matrixorigin/matrixone/assets/28624654/a9aeaec1-c786-4bf4-8bf0-f2bf9e1e9d5a)

It seems that CN did not return error at `pkg/sql/compile/ddl.go#L53` while DN found duplication at `pkg/vm/engine/tae/catalog/catalog.go#L1115`.

**Comment by w-zr** [comment]
http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cpt%5C%22%7D%20%7C%3D%20%602023%2F07%2F17%2017:17:%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221689613623233%22,%22to%22:%221689614223233%22%7D%7D

**Comment by aptend** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/49832303/85b904aa-3d44-4d64-af5a-be7a49b12326)

重复的表id 331497，从图里可以看到，启动的时候hakeeper是全新的，下一个id是272384，但是checkpoint有老数据，这部分已经包含一个 表id 331497 表名 0-q14 的表。所以17分的重复也因为在10分重启，再次读到了这个表的信息。

所以是启动的时候 logservice 数据和 ckp 数据不一致导致的 @aressu1985

**Comment by triump2020** [comment]
@aressu1985  这个问题如 @aptend 分析， 就是在第一次运行mo 集群的时候，没有把 checkpoint data 与 logservice 数据全部清空导致的，并不是bug.

**Comment by aressu1985** [comment]
fixed
