### ISSUE TITLE
[Bug]: lots of txn timeout in a minutes in tpcc 10w test on eks with pessimistic mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10731]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-05ab962
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

lots of txn timeout in a minutes in tpcc 10w test on eks with pessimistic mode.
<img width="1407" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/62437655-9697-4c05-a804-660f8e28ebc9">

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5578470207/jobs/10195018766

the mo log can be get from loki:
http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-rc%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by zhangxu19830126** [comment]
还没有分析这个问题

**Comment by zhangxu19830126** [comment]
找到几个地方，不确定是否能修复。

**Comment by zhangxu19830126** [comment]
myabe fixed by #10816

**Comment by aressu1985** [comment]
tracking

**Comment by aressu1985** [comment]
fixed
