### ISSUE TITLE
[Enhancement]: Adjust connect privilege

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#10749]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Add show databases privilege to connect.
Then user with connect role can view all databases and use them.
```

**Comment by domingozhang** [comment]
to adjust behavior of https://github.com/matrixorigin/matrixone/issues/10553

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
