### ISSUE TITLE
[Bug]: when  kubectl apply -f mo.yaml  mo-dn-0 pod  CrashLoopBackOff

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixone#10747]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.8.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The logs of  mo-dn-0 pod are as follows： 
/mo-service -cfg /tmp/tmp.hMqEOfVieY -debug-http=:6060
panic: failed to parse config from /tmp/tmp.hMqEOfVieY, error: invalid suffix: 'mi'

goroutine 1 [running]:
main.main()
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:96 +0x4c5

**Comment by w-zr** [comment]
Please attach file `/tmp/tmp.hMqEOfVieY`. or check whether it was modified.

**Comment by sukki37** [comment]
@loveRhythm1990 Any updates on this issue? It's been a while since the last comment.

**Comment by loveRhythm1990** [comment]
> @loveRhythm1990 Any updates on this issue? It's been a while since the last comment.

 In a word: no progress.

The main reason maybe the configuration file format error, I deploy a MO cluster according to document: https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Deploy/deploy-MatrixOne-cluster/#matrixone, It works all right. so I think we need the original configuration file which triggers this problem.

**Comment by loveRhythm1990** [comment]
@xuanyiLee  please paste  your `mo.yaml`  here if you see this comment, we think it most likely that you have a misconfigured file.
