### ISSUE TITLE
[Bug]: run bvt case in pessimistic mode on ci occurs ExpectedEOB.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10742]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ded28181d681b776d8ce7299a545aa6befe5a6f9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1547" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/57f028fa-013d-4189-8624-9c026816f974">

### Steps to Reproduce

```Markdown
https://github.com/heni02/matrixone/tree/add_pt_cases
https://github.com/heni02/matrixone/blob/add_pt_cases/test/distributed/cases/pessimistic_transaction/isolation_2.sql

row:165
```

**Comment by zhangxu19830126** [comment]
还没有分析这个问题

**Comment by zhangxu19830126** [comment]
already fixed, cannot repo

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
Verified！

**Comment by sukki37** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by Ariznawlll** [comment]
already merged！
