### ISSUE TITLE
[Bug]: A disabled test check

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10753]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In PR https://github.com/matrixorigin/matrixone/commit/69b070ad3433a403521bd747636b21e7ed1a19f9
related to #10729

pkg/sql/compile/compile_test.go line 125, a check is disabled because I cannot figure out why.    

Should have fixed code instead of commenting out check.

**Comment by m-schen** [comment]
ok 我来检查这个测试发生了什么并适配。

**Comment by m-schen** [comment]
very strange that, I just reopen and it can run succeed...

**Comment by m-schen** [comment]
@fengttt 感觉可以关掉它了？
