### ISSUE TITLE
[Bug]: cost of SSB 10G queries increased continuously on eks with 3*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10754]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): cf20de2
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 16G
  DISKCACHE: 100G
```

### Actual Behavior

<img width="642" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b579dadd-d729-4cf5-a7d3-9f4a121f8a46">

It is mainly causted by code query, and need to be optimized.

**Comment by badboynt1** [comment]
总体来说还在正常的波动范围内。 有一些可优化的空间，但是优先级并不高。

**Comment by badboynt1** [comment]
![企业微信截图_16905393128216](https://github.com/matrixorigin/matrixone/assets/112734932/5f9d49e4-5830-4f38-9495-54de6a259b7e)

看最近三个月的性能变化，其实主要是访问eks带来了一些波动，性能变化实质不大

**Comment by aressu1985** [comment]
need to be confirm

**Comment by aressu1985** [comment]
need to be confirm

**Comment by Ariznawlll** [comment]
<img width="938" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d133e71f-32cb-4b00-8b2f-ccc0a34afbea">
need to be confirm!

**Comment by heni02** [comment]
confirm, date 8.8 8.9 performace data  ssb 10G 100G normal 
![image](https://github.com/matrixorigin/matrixone/assets/113406637/30b83b4c-83cf-48d7-a324-c38e640d7cbc)
