### ISSUE TITLE
[Bug]: MO failed to startup occasionally

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#10750]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bce2dbdd2594dcb6c8819886ffd84e30b64f8257
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO failed to startup occasionally.
<img width="1127" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/da83c999-1763-454d-a050-ca5dbdf86ff4">
[mo-service.log](https://github.com/matrixorigin/matrixone/files/12080317/mo-service.log)

### Expected Behavior

MO should startup successfully every time.

**Comment by w-zr** [comment]
Need DEBUG level log.

**Comment by volgariver6** [comment]
[mo-service.log](https://github.com/matrixorigin/matrixone/files/12096218/mo-service.log)

https://github.com/matrixorigin/matrixone/actions/runs/5598835310/jobs/10239017651?pr=10770

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/5628434718/job/15252297760?pr=10814

**Comment by gouhongshen** [comment]
Hit again: https://github.com/matrixorigin/matrixone/actions/runs/5737343793/job/15548798207

**Comment by w-zr** [comment]
[mo-service.log](https://github.com/matrixorigin/matrixone/files/12258777/mo-service.log)

**Comment by xzxiong** [comment]
update, repro in https://github.com/matrixorigin/matrixone/actions/runs/5950103299/job/16137208093?pr=11371
```
2023/08/23 10:28:07.045414 +0000 ERROR incrservice/service.go:252 error: no such table .272389
2023/08/23 10:28:07.045494 +0000 ERROR preinsert/preinsert.go:117 error: no such table mo_task.sys_async_task
2023/08/23 10:28:07.045548 +0000 ERROR colexec/receiver_operator.go:118 children pipeline closed unexpectedly
2023/08/23 10:28:07.045630 +0000 ERROR compile/sql_executor.go:104 internal sql executor error: no such table mo_task.sys_async_task
2023/08/23 10:28:07.045773 +0000 ERROR log-service bootstrap/bootstrap.go:175 bootstrap mo step 2 failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "no such table mo_task.sys_async_task"}
panic: no such table mo_task.sys_async_task

goroutine 729 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).bootstrap.func1({0x2fc0478, 0xc004b81290})
    /home/runner/work/matrixone/matrixone/head/pkg/cnservice/server.go:675 +0x285
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
    /home/runner/work/matrixone/matrixone/head/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
    /home/runner/work/matrixone/matrixone/head/pkg/common/stopper/stopper.go:254 +0xe5
```

**Comment by w-zr** [comment]
Still working on this issue

**Comment by w-zr** [comment]
it should be fixed in #11588

**Comment by gouhongshen** [comment]
hit again: https://github.com/matrixorigin/matrixone/actions/runs/6099039379/job/16550258174?pr=11680

**Comment by w-zr** [comment]
It seems that this bug is about auto-increment service.

**Comment by w-zr** [comment]
reassign to @volgariver6

**Comment by volgariver6** [comment]
pr已经提交，但是跑ci还有些问题，需要再看一下

**Comment by volgariver6** [comment]
还没有看pr的问题

**Comment by volgariver6** [comment]
pr merged
