### ISSUE TITLE
[Bug]: 阿里云上查询历史SQL时，偶现Error 20405 (HY000): file local-test20/data/eb575fd2-252f-11ee-91e4-1a5f33c77f72_00045 is not found错误

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#10763]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ac56ec384ac6093e19be34d542f5ed20b76ebc1b
- Hardware parameters:
- OS type:
- Others: aliyun  ack multi-cn
```

### Actual Behavior

/* cloud_nonuser */ 
SELECT * FROM (
    select `statement`,system.statement_info.statement_id,
    IF(`status`='Running', TIMESTAMPDIFF(MICROSECOND,`request_at`,now())*1000, `duration`) AS `duration`,
    `status`,`query_type`,`request_at`,system.statement_info.response_at,`user`,`database`,`transaction_id`,`session_id`,`rows_read`,`bytes_scan`,`result_count`
    from system.statement_info left join mo_catalog.statement_cu ON system.statement_info.statement_id = mo_catalog.statement_cu.statement_id where 1=1 
    AND `request_at` >= '2023-07-19 05:09:59' AND system.statement_info.account = 'd4d103c4_4088_4674_9591_5dddb48de490' AND sql_source_type IN ('cloud_user_sql','external_sql') 
    )t ORDER BY request_at DESC LIMIT 20;
报错：Error 20405 (HY000): file local-test20/data/eb575fd2-252f-11ee-91e4-1a5f33c77f72_00045 is not found

### Expected Behavior

查询出结果。

### Steps to Reproduce

```Markdown
As Actual Behavior
```

### Additional information

偶现问题，有时会频繁出现，有时保持正常。
目前在阿里云上发现。

**Comment by reusee** [comment]
我判断不是 file service 问题

re-assigning to @xzxiong

**Comment by xzxiong** [comment]
> 我判断不是 file service 问题 如果是 file service 问题，那所有文件 io 都会有问题，不会只是这个场景
> 
> re-assigning to @xzxiong

跟我不相关，请联系DN的同学分析~

**Comment by xzxiong** [comment]
the original error stack is lost, try repo

**Comment by xzxiong** [comment]
从当前的 aliyun MO 集群上查看 (部署时间 `2023-07-19 11:21:34 +0000`)
1. not found 有很多，filepath 前缀有 cnservice，dnservice，local-test11/data/query_result_meta 三大类
2. **暂未复现** issue 中的相关报错

```
mysql> select error from system.error_info where error like '%not found' limit 10;
+-------------------------------------------------------------------------------------------------------------------------------------+
| error                                                                                                                               |
+-------------------------------------------------------------------------------------------------------------------------------------+
| file local-test11/data/query_result_meta/2c9c93aa_32b5_437b_aba2_63be6a1a90d9_5b372fc5-27bd-11ee-aa0b-968bc25d7ec7.blk is not found |
| result file query_result_meta/2c9c93aa_32b5_437b_aba2_63be6a1a90d9_5b372fc5-27bd-11ee-aa0b-968bc25d7ec7.blk not found               |
| file local-test11/data/query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_7779971e-26e4-11ee-a2ba-b2bc5eadcb62.blk is not found |
| result file query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_7779971e-26e4-11ee-a2ba-b2bc5eadcb62.blk not found               |
| result file query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_7779971e-26e4-11ee-a2ba-b2bc5eadcb62.blk not found               |
| file local-test11/data/query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_7779971e-26e4-11ee-a2ba-b2bc5eadcb62.blk is not found |
| file local-test11/data/query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_79801b31-26e4-11ee-a2ba-b2bc5eadcb62.blk is not found |
| result file query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_79801b31-26e4-11ee-a2ba-b2bc5eadcb62.blk not found               |
| file local-test11/data/query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_79801b31-26e4-11ee-a2ba-b2bc5eadcb62.blk is not found |
| result file query_result_meta/d6a25882_9272_4101_b0d9_03242790112b_79801b31-26e4-11ee-a2ba-b2bc5eadcb62.blk not found               |
+-------------------------------------------------------------------------------------------------------------------------------------+
10 rows in set (0.29 sec)

mysql> select left(error, 20) from system.error_info where error like '%not found' group by left(error, 20) limit 20;
+----------------------+
| left(error, 20)      |
+----------------------+
| file local-test11/da |
| result file query_re |
| file cnservice/33396 |
| file dnservice/33376 |
| file cnservice/33663 |
| file cnservice/37353 |
| not found            |
+----------------------+
7 rows in set (0.39 sec)
```

**Comment by xzxiong** [comment]
尝试访问老MO 集群信息，bucket `ack-test-bucket/local-test20`
但因为没有 dump 的密码，无法登录。

restart old MO Cloud aliyun 配置如下
[mo.ack.yaml.txt](https://github.com/matrixorigin/matrixone/files/12206301/mo.ack.yaml.txt)

相关脚本
```
# 启动mo
kubectl -n xiezexiong apply -f mo.ack.yaml
# 删除mo
kubectl -n xiezexiong delete -f mo.ack.yaml
```

**Comment by xzxiong** [comment]
使用 hack dev 版本，绕过 dump账号 鉴权。

**Comment by xzxiong** [comment]
在 aliyun上申请了一台虚拟机，通过 ossutil 下载了整个数据目录（过滤掉 query_result 下所有的 blk后缀的文件，这种文件数量大，文件小约 500B），再启动standalone模式。
1. 下载oss文件
 `ossutil64 sync oss://ack-test-bucket/local-test20/data ./local-test20 --backup-dir backup --exclude *.blk` 
2. 修改CN/DN/LogService配置文件，MO可读取
```diff
 [[fileservice]]
 name = "SHARED"
-backend = "DISK"
+backend = "DISK-ETL"
 data-dir = "mo-data/s3"
```
3. 创建软连接
```
cd .../matrixone
mkdir mo-data
ln -s ....../local-test20   ./mo-data/s3
```
4. 正常启动MO
```
./mo-service -debug-http :6060  -launch ./etc/launch-tae-CN-tae-DN/launch.toml
```

**Comment by xzxiong** [comment]
query sql: found eb575fd2-252f-11ee-91e4-1a5f33c77f72_00033 has been deleted at `2023-07-18 17:44:37.393895`
```
select * from log_info where timestamp between '2023-07-18 14:09:00'  and '2023-07-19 07:11:00' and message like '[DB GC] files to delete%' and message like '%eb575fd2%' \G
```


![image](https://github.com/matrixorigin/matrixone/assets/3927687/e65dbd24-e574-4ac6-ab15-3e68bc514e6e)

**Comment by xzxiong** [comment]
mo数据打包至aliyun 上海region的 `oss://ack-test-bucket/local-test20/local-test20.data.tgz`
下载
`ossutil cp oss://ack-test-bucket/local-test20/local-test20.data.tgz  ./local-test20.data.tgz `
本地启动 
https://github.com/matrixorigin/matrixone/issues/10763#issuecomment-1657371687 bypass dump账号
https://github.com/matrixorigin/matrixone/issues/10763#issuecomment-1659664098 本地启动mo

**Comment by xzxiong** [comment]
@LeftHandCold ptal

**Comment by LeftHandCold** [comment]
还做object meta和ckp的重构工作，没来的急分析

**Comment by LeftHandCold** [comment]
还做object meta和ckp的重构工作，没来的急分析

**Comment by LeftHandCold** [comment]
还没来得及分析

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
复现观察中

**Comment by LeftHandCold** [comment]
这个一直没有复现过

**Comment by aressu1985** [comment]
稳定性也没有在出现过
