### ISSUE TITLE
[Bug]: mergeRun runs bvt case shows internal error: table 'blob_05' in prepare statement 'stmt2' does not exist anymore.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10778]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1043" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fe3d630d-213e-42ca-a141-cf6ce305f04c">

log in: https://github.com/matrixorigin/ci-test/actions/runs/5600626852

### Steps to Reproduce

```Markdown
in ci-test repo：
mergeRun_test.yaml-View runs-Run workflow-git Repo(heni02/matrixone)-branch(add_pt_cases)-trigger
```

**Comment by ouyuanning** [comment]
用main里的测试用例验证一下。

**Comment by Ariznawlll** [comment]
Verified！
