### ISSUE TITLE
Unable to use comparison operators in select list

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#1077]
#### Can be reproduced ?
Yes

#### Steps:
CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

select spID=1 as a, spID>1 as b, spID<1 as c, spID>=1 as d, spID<=1 as e, spID<>1 as f, spID != 1 as g from t1  limit 2;

#### Expected behavior:
mysql> select spID=1 as a, spID>1 as b, spID<1 as c, spID>=1 as d, spID<=1 as e, spID<>1 as f, spID != 1 as g from t1 limit 2;
+------+------+------+------+------+------+------+
| a    | b    | c    | d    | e    | f    | g    |
+------+------+------+------+------+------+------+
|    1 |    0 |    0 |    1 |    1 |    0 |    0 |
|    0 |    1 |    0 |    1 |    0 |    1 |    1 |
+------+------+------+------+------+------+------+
2 rows in set (0.00 sec)

#### Actual behavior:
mysql> select spID=1 as a, spID>1 as b, spID<1 as c, spID>=1 as d, spID<=1 as e, spID<>1 as f, spID != 1 as g from t1;
ERROR 1105 (HY000): unknown error:RunWhileSend : unsupported type 200 

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 693ab24c885ee26df6fe5ad467dd46c7cbdbe950
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by JinHai-CN** [comment]
Won't support in v0.2.0.

**Comment by m-schen** [comment]
can be supported after we have boolean type.

**Comment by daviszhen** [comment]
it was fixed
