### ISSUE TITLE
Comparison operators: Incorrect result when one operand is (1+ the maximum boundary value) 

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#1078]
#### Can be reproduced ?
Yes.

#### Steps:
CREATE TABLE t1
(pk INTEGER PRIMARY KEY,
 i1 TINYINT,
 u1 TINYINT UNSIGNED,
 i2 SMALLINT,
 u2 SMALLINT UNSIGNED,
 i4 INTEGER,
 u4 INTEGER UNSIGNED,
 i8 BIGINT,
 u8 BIGINT UNSIGNED);

INSERT INTO t1 VALUES
(0, -128, 0, -32768, 0,  -2147483648, 0, -9223372036854775808, 0),
(1, -1, 0, -1, 0,  -1, 0, -1, 0),
(2, 0, 0, 0, 0,  0, 0, 0, 0),
(3, 1, 1, 1, 1,  1, 1, 1, 1),
(4, 127, 255, 32767, 65535,  2147483647, 4294967295,
 9223372036854775807, 18446744073709551615);

select * from t1 where i1=128;
select * from t1 where i1>128;
select * from t1 where i1<128;
select * from t1 where i1<>128;
select * from t1 where i8=9223372036854775808;
select * from t1 where i8>9223372036854775808;
select * from t1 where i8<9223372036854775808;

#### Expected behavior:
mysql> select * from t1 where i1=128;
Empty set (0.00 sec)

mysql> select * from t1 where i1>128;
Empty set (0.00 sec)

mysql> select * from t1 where i1<128;
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
| pk | i1   | u1   | i2     | u2    | i4          | u4         | i8                   | u8                   |
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
|  0 | -128 |    0 | -32768 |     0 | -2147483648 |          0 | -9223372036854775808 |                    0 |
|  1 |   -1 |    0 |     -1 |     0 |          -1 |          0 |                   -1 |                    0 |
|  2 |    0 |    0 |      0 |     0 |           0 |          0 |                    0 |                    0 |
|  3 |    1 |    1 |      1 |     1 |           1 |          1 |                    1 |                    1 |
|  4 |  127 |  255 |  32767 | 65535 |  2147483647 | 4294967295 |  9223372036854775807 | 18446744073709551615 |
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
5 rows in set (0.00 sec)

mysql> select * from t1 where i1<>128;
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
| pk   | i1   | u1   | i2    | u2    | i4         | u4         | i8                  | u8                   |
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
|    1 |   -1 |    0 |    -1 |     0 |         -1 |          0 |                  -1 |                    0 |
|    2 |    0 |    0 |     0 |     0 |          0 |          0 |                   0 |                    0 |
|    3 |    1 |    1 |     1 |     1 |          1 |          1 |                   1 |                    1 |
|    4 |  127 |  255 | 32767 | 65535 | 2147483647 | 4294967295 | 9223372036854775807 | 18446744073709551615 |
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
4 rows in set (0.01 sec)

mysql> select * from t1 where i8=9223372036854775808;
Empty set (0.00 sec)

mysql> select * from t1 where i8>9223372036854775808;
Empty set (0.00 sec)

mysql> select * from t1 where i8<9223372036854775808;
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
| pk | i1   | u1   | i2     | u2    | i4          | u4         | i8                   | u8                   |
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
|  0 | -128 |    0 | -32768 |     0 | -2147483648 |          0 | -9223372036854775808 |                    0 |
|  1 |   -1 |    0 |     -1 |     0 |          -1 |          0 |                   -1 |                    0 |
|  2 |    0 |    0 |      0 |     0 |           0 |          0 |                    0 |                    0 |
|  3 |    1 |    1 |      1 |     1 |           1 |          1 |                    1 |                    1 |
|  4 |  127 |  255 |  32767 | 65535 |  2147483647 | 4294967295 |  9223372036854775807 | 18446744073709551615 |
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
5 rows in set (0.00 sec)

#### Actual behavior:
mysql> select * from t1 where i1=128;
+------+------+------+--------+------+-------------+------+----------------------+------+
| pk   | i1   | u1   | i2     | u2   | i4          | u4   | i8                   | u8   |
+------+------+------+--------+------+-------------+------+----------------------+------+
|    0 | -128 |    0 | -32768 |    0 | -2147483648 |    0 | -9223372036854775808 |    0 |
+------+------+------+--------+------+-------------+------+----------------------+------+
1 row in set (0.01 sec)

mysql> select * from t1 where i1>128;
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
| pk   | i1   | u1   | i2    | u2    | i4         | u4         | i8                  | u8                   |
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
|    1 |   -1 |    0 |    -1 |     0 |         -1 |          0 |                  -1 |                    0 |
|    2 |    0 |    0 |     0 |     0 |          0 |          0 |                   0 |                    0 |
|    3 |    1 |    1 |     1 |     1 |          1 |          1 |                   1 |                    1 |
|    4 |  127 |  255 | 32767 | 65535 | 2147483647 | 4294967295 | 9223372036854775807 | 18446744073709551615 |
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
4 rows in set (0.00 sec)

mysql> select * from t1 where i1<128;
Empty set (0.01 sec)

mysql> select * from t1 where i8=9223372036854775808;
+------+------+------+--------+------+-------------+------+----------------------+------+
| pk   | i1   | u1   | i2     | u2   | i4          | u4   | i8                   | u8   |
+------+------+------+--------+------+-------------+------+----------------------+------+
|    0 | -128 |    0 | -32768 |    0 | -2147483648 |    0 | -9223372036854775808 |    0 |
+------+------+------+--------+------+-------------+------+----------------------+------+
1 row in set (0.00 sec)

mysql>  select * from t1 where i1<>128;
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
| pk | i1   | u1   | i2     | u2    | i4          | u4         | i8                   | u8                   |
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
|  0 | -128 |    0 | -32768 |     0 | -2147483648 |          0 | -9223372036854775808 |                    0 |
|  1 |   -1 |    0 |     -1 |     0 |          -1 |          0 |                   -1 |                    0 |
|  2 |    0 |    0 |      0 |     0 |           0 |          0 |                    0 |                    0 |
|  3 |    1 |    1 |      1 |     1 |           1 |          1 |                    1 |                    1 |
|  4 |  127 |  255 |  32767 | 65535 |  2147483647 | 4294967295 |  9223372036854775807 | 18446744073709551615 |
+----+------+------+--------+-------+-------------+------------+----------------------+----------------------+
5 rows in set (0.00 sec)

mysql> select * from t1 where i8>9223372036854775808;
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
| pk   | i1   | u1   | i2    | u2    | i4         | u4         | i8                  | u8                   |
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
|    1 |   -1 |    0 |    -1 |     0 |         -1 |          0 |                  -1 |                    0 |
|    2 |    0 |    0 |     0 |     0 |          0 |          0 |                   0 |                    0 |
|    3 |    1 |    1 |     1 |     1 |          1 |          1 |                   1 |                    1 |
|    4 |  127 |  255 | 32767 | 65535 | 2147483647 | 4294967295 | 9223372036854775807 | 18446744073709551615 |
+------+------+------+-------+-------+------------+------------+---------------------+----------------------+
4 rows in set (0.01 sec)

mysql> select * from t1 where i8<9223372036854775808;
Empty set (0.01 sec)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 693ab24c885ee26df6fe5ad467dd46c7cbdbe950 
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by JinHai-CN** [comment]
Support two modes in the future.
- Standard mode: Not check the overflow.
- Compatible mode: Check the overflow.

Currently, matrixone only support standard mode.

**Comment by fengttt** [comment]
Verified unit will check overflow for const.
