### ISSUE TITLE
[Bug]: mo crashed by Key Range not found for removal in MemCache_LRU during sysbench oltp hight concurrecncy test on standlone mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10794]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): f571de3a4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5613244904/job/15209175507

During running sysbench oltp select / delete test, the mo crashed by panic Key Range not found for removal in MemCache_LRU, the error log :

2023/07/21 02:20:35.951564 +0800 INFO jobs/compactblk.go:342 [Done] {"txn-start-ts": "1689877235823518136-0", "operation": "[2236]compact", "compacted": "[A]BLK[<272444-272445-191baaa1-272a-11ee-b2ec-b07b25f8b524-19-0>]", "created": "BLK<272444-272445-191baaa1-272a-11ee-b2ec-b07b25f8b524-26-0>", "compactedRows": 8192, "TotalChanges": 0, "createdRows": 8192, "duration": "128.001234ms"}
2023/07/21 02:20:36.396706 +0800 ERROR interval/overlap.go:65 error: internal error: Key Range not found for removal in MemCache_LRU
2023/07/21 02:20:36.396908 [ants]: worker exits from panic: internal error: Key Range not found for removal in MemCache_LRU
goroutine 74098 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x89
panic({0x28b8940, 0xc11a1667b0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/matrixorigin/matrixone/pkg/fileservice.WithLRU.func1.1({0x2875000?, 0xc0af4d3560?}, {0xc08be3dc50?, 0xc08be3dbb0?, 0x28?}, 0x28cc420?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/mem_cache.go:56 +0x6d
github.com/matrixorigin/matrixone/pkg/fileservice/objcache/lruobjcache.(*LRU).evict(0xc003d06780)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/objcache/lruobjcache/lru.go:104 +0x15f
github.com/matrixorigin/matrixone/pkg/fileservice/objcache/lruobjcache.(*LRU).Set(0xc003d06780, {0x2875000, 0xc09274ff20}, {0xc20d1d0000, 0x30026, 0x30026}, 0x30026, 0x0)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/objcache/lruobjcache/lru.go:81 +0x565
github.com/matrixorigin/matrixone/pkg/fileservice.(*MemCache).Update(0xc0013bdf40, {0x0?, 0x0?}, 0xc0c991f2c0, 0x0?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/mem_cache.go:168 +0x203
github.com/matrixorigin/matrixone/pkg/fileservice.(*LocalFS).Read.func1()
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/local_fs.go:312 +0x45

[mo-sysbench.log](https://github.com/matrixorigin/matrixone/files/12115552/mo-sysbench.log)

### Expected Behavior

the mo should never crash

### Steps to Reproduce

```Markdown
run sysbench oltp test on standlone mode
```

**Comment by aunjgr** [comment]
@reusee please take a look

**Comment by reusee** [comment]
re-assigning to @arjunsk

**Comment by arjunsk** [comment]
The issue is due to this code block

https://github.com/matrixorigin/matrixone/blob/625493f6ca55c550bb3761a032e33c67449ede13/pkg/fileservice/mem_cache.go#L168C2-L176C2

The `Overlap Checker` and `ObjectCache` update should be atomic.
Scenario:
LRU set Key1
LRU evict Key1
Overlap Checker Remove Key1 -- Panic()
Overlap Checker Insert Key1

We could solve this issue by adding a lock for this block. But it might have a performance impact. Overall there will be 3 locks. ObjectCache, Overlap Checker, and the new lock for Synchronising Overlap Checker and Object Cache).

We could ignore this error, but if the entry is not properly removed from Overlap checker, the Keys get accumulated and can cause OOM exception.

**Comment by arjunsk** [comment]
PR raised for resolving this issue: https://github.com/matrixorigin/matrixone/pull/10813

Waiting for approval.

**Comment by arjunsk** [comment]
The fix is pushed to the master branch.

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
