### ISSUE TITLE
[Bug]: bvt test failed for a query from statement_info

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ea6c050
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

on a merge trigger job , one of bvt case failed.

2023-07-20 11:09:22 INFO  Executor:609 - select mo_ctl('cn','synccommit','') successfully.
2023-07-20 11:09:37 ERROR RSRow:65 - The value of [row:98,column:0] does not equal with each other,one is [SET character_set_results = utf8],but the other is [SET sql_mode='NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES']
2023-07-20 11:09:37 ERROR Executor:159 - [/runner/_work/matrixone/matrixone/matrixone/test/distributed/cases/statement_query_type/statement_query_type.sql][row:165][select statement,query_type,sql_source_type from  system.statement_info where account="bvt_query_type" and sql_source_type="external_sql" and status != "Running" and statement not like '%mo_ctl%' and aggr_count <1 order by request_at desc limit 99;] was executed failed, con[id=0, user=dump, ***
2023-07-20 11:09:37 ERROR Executor:161 - [EXPECT RESULT]:
statement    query_type    sql_source_type
select sleep(1)    DQL    external_sql
use system    Other    external_sql
rollback    TCL    external_sql
deallocate prepare s1    Other    external_sql
set @a=2    Other    external_sql
prepare s1 from select * from test_table where col1=?    Other    external_sql
drop database db2    DDL    external_sql
drop table table_2    DDL    external_sql
drop view view_2    DDL    external_sql
drop index index_table_2 on table_2    DDL    external_sql
create index index_table_2 on table_2(col1)    DDL    external_sql
create view view_2 as select * from table_2    DDL    external_sql
create table table_2(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
create database db2    DDL    external_sql
drop database db1    DDL    external_sql
drop account test_account    DCL    external_sql
drop role test_role    DCL    external_sql
drop user user_name    DCL    external_sql
revoke test_role from user_name    DCL    external_sql
grant create table,drop table on database *.* to test_role    DCL    external_sql
create database if not exists db1    DDL    external_sql
create user user_name identified by '******'    DCL    external_sql
create role test_role    DCL    external_sql
create account test_account admin_name = 'test_name' identified by '******' open comment 'tenant_test'    DCL    external_sql
values row(1,1), row(2,2), row(3,3) order by column_0 desc    DQL    external_sql
show index from test_table    Other    external_sql
show tables    Other    external_sql
show processlist    Other    external_sql
show privileges    Other    external_sql
show profiles    Other    external_sql
show plugins    Other    external_sql
show events    Other    external_sql
show config    Other    external_sql
show procedure status    Other    external_sql
show triggers    Other    external_sql
show create table test_table    Other    external_sql
show create database test_db    Other    external_sql
create view test_view as select * from test_table    DDL    external_sql
create table test_table(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
use test_db    Other    external_sql
begin    TCL    external_sql
create database test_db    DDL    external_sql
use statement_query_type    Other    external_sql
drop database test_db    DDL    external_sql
drop table test_01    DDL    external_sql
truncate table test_01    DDL    external_sql
explain select * from test_01    Other    external_sql
show create table test_01    Other    external_sql
create table test_01(a int, b varchar)    DDL    external_sql
drop table if exists test_01    DDL    external_sql
deallocate prepare s1    Other    external_sql
set @a=2    Other    external_sql
prepare s1 from select * from test_table where col1=?    Other    external_sql
drop database db2    DDL    external_sql
drop table table_2    DDL    external_sql
drop view view_2    DDL    external_sql
drop index index_table_2 on table_2    DDL    external_sql
create index index_table_2 on table_2(col1)    DDL    external_sql
create view view_2 as select * from table_2    DDL    external_sql
create table table_2(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
create database db2    DDL    external_sql
drop database db1    DDL    external_sql
drop account test_account    DCL    external_sql
drop role test_role    DCL    external_sql
drop user user_name    DCL    external_sql
revoke test_role from user_name    DCL    external_sql
grant create table,drop table on database *.* to test_role    DCL    external_sql
create database if not exists db1    DDL    external_sql
create user user_name identified by '******'    DCL    external_sql
create role test_role    DCL    external_sql
create account test_account admin_name = 'test_name' identified by '******' open comment 'tenant_test'    DCL    external_sql
values row(1,1), row(2,2), row(3,3) order by column_0 desc    DQL    external_sql
show index from test_table    Other    external_sql
show collation like '%'    Other    external_sql
show collation    Other    external_sql
show tables    Other    external_sql
show processlist    Other    external_sql
show privileges    Other    external_sql
show profiles    Other    external_sql
show plugins    Other    external_sql
show events    Other    external_sql
show config    Other    external_sql
show procedure status    Other    external_sql
show triggers    Other    external_sql
show create view test_view    Other    external_sql
show create table test_table    Other    external_sql
show create database test_db    Other    external_sql
create view test_view as select * from test_table    DDL    external_sql
create table test_table(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
drop table if exists test_table    DDL    external_sql
use test_db    Other    external_sql
create database test_db    DDL    external_sql
drop database if exists test_db    DDL    external_sql
rollback    TCL    external_sql
start transaction    TCL    external_sql
commit    TCL    external_sql
begin    TCL    external_sql
create database statement_query_type    DDL    external_sql
SET character_set_results = utf8    Other    external_sql
2023-07-20 11:09:37 ERROR Executor:162 - [ACTUAL RESULT]:
statement    query_type    sql_source_type
select sleep(1)    DQL    external_sql
use system    Other    external_sql
rollback    TCL    external_sql
deallocate prepare s1    Other    external_sql
set @a=2    Other    external_sql
prepare s1 from select * from test_table where col1=?    Other    external_sql
drop database db2    DDL    external_sql
drop table table_2    DDL    external_sql
drop view view_2    DDL    external_sql
drop index index_table_2 on table_2    DDL    external_sql
create index index_table_2 on table_2(col1)    DDL    external_sql
create view view_2 as select * from table_2    DDL    external_sql
create table table_2(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
create database db2    DDL    external_sql
drop database db1    DDL    external_sql
drop account test_account    DCL    external_sql
drop role test_role    DCL    external_sql
drop user user_name    DCL    external_sql
revoke test_role from user_name    DCL    external_sql
grant create table,drop table on database *.* to test_role    DCL    external_sql
create database if not exists db1    DDL    external_sql
create user user_name identified by '******'    DCL    external_sql
create role test_role    DCL    external_sql
create account test_account admin_name = 'test_name' identified by '******' open comment 'tenant_test'    DCL    external_sql
values row(1,1), row(2,2), row(3,3) order by column_0 desc    DQL    external_sql
show index from test_table    Other    external_sql
show tables    Other    external_sql
show processlist    Other    external_sql
show privileges    Other    external_sql
show profiles    Other    external_sql
show plugins    Other    external_sql
show events    Other    external_sql
show config    Other    external_sql
show procedure status    Other    external_sql
show triggers    Other    external_sql
show create table test_table    Other    external_sql
show create database test_db    Other    external_sql
create view test_view as select * from test_table    DDL    external_sql
create table test_table(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
use test_db    Other    external_sql
begin    TCL    external_sql
create database test_db    DDL    external_sql
use statement_query_type    Other    external_sql
drop database test_db    DDL    external_sql
drop table test_01    DDL    external_sql
truncate table test_01    DDL    external_sql
explain select * from test_01    Other    external_sql
show create table test_01    Other    external_sql
create table test_01(a int, b varchar)    DDL    external_sql
drop table if exists test_01    DDL    external_sql
deallocate prepare s1    Other    external_sql
set @a=2    Other    external_sql
prepare s1 from select * from test_table where col1=?    Other    external_sql
drop database db2    DDL    external_sql
drop table table_2    DDL    external_sql
drop view view_2    DDL    external_sql
drop index index_table_2 on table_2    DDL    external_sql
create index index_table_2 on table_2(col1)    DDL    external_sql
create view view_2 as select * from table_2    DDL    external_sql
create table table_2(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
create database db2    DDL    external_sql
drop database db1    DDL    external_sql
drop account test_account    DCL    external_sql
drop role test_role    DCL    external_sql
drop user user_name    DCL    external_sql
revoke test_role from user_name    DCL    external_sql
grant create table,drop table on database *.* to test_role    DCL    external_sql
create database if not exists db1    DDL    external_sql
create user user_name identified by '******'    DCL    external_sql
create role test_role    DCL    external_sql
create account test_account admin_name = 'test_name' identified by '******' open comment 'tenant_test'    DCL    external_sql
values row(1,1), row(2,2), row(3,3) order by column_0 desc    DQL    external_sql
show index from test_table    Other    external_sql
show collation like '%'    Other    external_sql
show collation    Other    external_sql
show tables    Other    external_sql
show processlist    Other    external_sql
show privileges    Other    external_sql
show profiles    Other    external_sql
show plugins    Other    external_sql
show events    Other    external_sql
show config    Other    external_sql
show procedure status    Other    external_sql
show triggers    Other    external_sql
show create view test_view    Other    external_sql
show create table test_table    Other    external_sql
show create database test_db    Other    external_sql
create view test_view as select * from test_table    DDL    external_sql
create table test_table(\ncol1 int,\ncol2 varchar\n)    DDL    external_sql
drop table if exists test_table    DDL    external_sql
use test_db    Other    external_sql
create database test_db    DDL    external_sql
drop database if exists test_db    DDL    external_sql
rollback    TCL    external_sql
start transaction    TCL    external_sql
commit    TCL    external_sql
begin    TCL    external_sql
create database statement_query_type    DDL    external_sql
SET sql_mode='NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES'    Other    external_sql
2023-07-20 11:09:39 INFO  Executor:111 - Connection id had been turned from 0 to 1

the job link:
https://github.com/matrixorigin/matrixone/actions/runs/5609987732/jobs/10264614674

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/e173f8a1-961d-4fb4-b5a6-3079f06900a7)
The last line is the only diff.

**Comment by gavinyue** [comment]
First pr merged. Will test.

**Comment by gavinyue** [comment]
Ask the owner to test.

**Comment by aressu1985** [comment]
fixed
