### ISSUE TITLE
[Subtask]: update incrStatement for pr https://github.com/matrixorigin/matrixone/pull/10689

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10804]
### Parent Issue

https://github.com/matrixorigin/matrixone/pull/10689

### Detail of Subtask

让pr https://github.com/matrixorigin/matrixone/pull/10689 能通过bvt。

**Comment by daviszhen** [comment]
还在做。还有一些bvt 没过掉。

**Comment by sukki37** [comment]
#10689 has been merged
