### ISSUE TITLE
[Bug]: CPU time and mem value statistics problem

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10837]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):03d848d9d0eaedb44d3538cf7523968914a6ec1a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

为了对statement_info stats字段cpu时间和mem数值正确性验证，测试了4个场景，发现cpu时间和mem数值统计结果有不符合预期情况，测试结果分别如下：

测试场景1：tpch10G运行多次，运行15分钟左右（886s）并发1
测试结果：cpu值实际值没有超过ps工具统计值，这个符合预期，但值小了一倍，相差这么大是否合理需要确认；mem实际值比工具统计出来的值相差幅度不大（确认是否合理范围内？）
具体测试值如下：
1.stats中cpu字段验证：
cpu时间在该时间段内耗时6781.5s
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[1]')) as float))/1000000000 as cpu from statement_info where request_at >'2023-07-22 14:41:20' and request_at< '2023-07-22 14:56:06';
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7e1efa7d-bbc4-4020-bbe1-dbe741fef7e7)

ps工具统计cpu核数平均值14.49, 总耗时14.49*886=12838.14s
![image](https://github.com/matrixorigin/matrixone/assets/113406637/222ebd63-468d-4b93-99fa-0b532e8dd03d)
数值：
[ps-pcpu.txt](https://github.com/matrixorigin/mo-nightly-regression/files/12135935/ps-pcpu.txt)

2.stats中mem字段验证：
mem在该时间段内耗时6315.76GB，平均每秒占用内存7.12GB
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[2]')) as float))/1024/1024/1024 as mem from statement_info where request_at >'2023-07-22 14:41:20' and request_at< '2023-07-22 14:56:06';
![image](https://github.com/matrixorigin/matrixone/assets/113406637/cddaa105-f3a6-431d-96d2-bf5be3ac841e)

工具统计mem 平均每秒占用内存5.76G

测试场景2：并发100 insert values 运行15min+
测试结果：cpu时间和mem两个数据和工具统计相差太大，都比ps工具统计时间小几个数量级，从cpu时间统计比执行15min+少来看，这个应该是有问题的
具体测试值如下：
1.stats中cpu时间验证：
cpu时间在该时间段内耗时518s
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7f0c607c-670e-485e-a020-7b5b20dfe6b0)
工具统计值5.43*1033=5609.19s
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6caa298b-89f9-4a12-9146-abd708f50223)
[ps-load-pcpu.txt](https://github.com/matrixorigin/mo-nightly-regression/files/12136088/ps-load-pcpu.txt)

2.stats中mem字段验证：
该时间段总耗794KB
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f6f0c37d-7e76-4550-b037-18903559b084)
工具统计值总耗22536GB
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d26e624b-00a8-4333-8165-e78ae3975a6b)

测试场景3: tpcc 10仓100并发 运行20min
测试结果：和测试场景2相同的结果
具体测试值如下：
1.stats中cpu时间验证：
cpu时间在该时间段内耗时953s，比实际20min（1200s）还要小
![image](https://github.com/matrixorigin/matrixone/assets/113406637/5d84e4df-e5d6-4883-b558-b5d7706d5739)
工具统计的cpu时间：5.85*1200=7020s
![image](https://github.com/matrixorigin/matrixone/assets/113406637/fce22548-48b0-4bf2-99f1-09bcd41394ac)

2.stats中mem验证：
mo 该时间段内mem总值10.92G，平均每秒占用9.3MB
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7eb4a888-179f-4c3e-b87d-b16e5a805a1d)
工具统计的mem总值13552G，平均每秒占用11.29G（13552/1200=11.29）
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7321b2cf-8a02-449f-addb-68542461d284)

测试场景4: load data大数量100列4千万，1亿等表（./load.sh -c cases/100_columns -m） 并发1，运行16min（960s）
测试结果：cpu时间比ps统计值大很多，不预期，mem值没有超过ps统计值，但相差比较大，需判断是否预期？
具体测试值如下：
1.stats中cpu时间验证：
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[1]')) as float))/1000000000 as cpu from statement_info where request_at >'2023-07-24 20:20:41' and request_at< '2023-07-24 20:36:41';
cpu该时间段总耗时114533s
![image](https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/804733e4-e339-4f27-a2ad-86e6673f4858)
工具统计值9.89*960=9494s
![image](https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/40d58076-599a-477a-8a2e-144547287997)

2.stats中mem验证：
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[2]')) as float))/1024/1024/1024 as cpu from statement_info where request_at >'2023-07-24 20:20:41' and request_at< '2023-07-24 20:36:41';
mem该时间段591.7G，平均每秒1.06M
![image](https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/9fadeffa-ae5c-460c-a202-affca47c2b4d)
工具统计值：34908.76G/960s=36.2，每秒占用内存36.2G
![image](https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/9b81cb2c-796a-496f-b50a-a34d1a1f28b2)

### Steps to Reproduce

```Markdown
运行ps监控脚本，分别进行mo-tpch，mo-tpcc等测试
ps监控脚本sh：
#!/usr/bin/env bash
while true;
  do
    PID=`ps -ef | grep mo-service |grep -v grep | awk 'NR==1' | awk -F ' ' '{print $2}'`;
    time=`date +'%Y-%m-%d %H:%M:%S'`
    echo ${time} `ps -e -o 'pid,comm,args,pcpu,rsz,vsz,stime,user,uid' | grep ${PID} | grep -v 'grep' | sort -nrk5` >> resr.txt;
    sleep 1;
  done

统计cpu时间sql：
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[1]')) as float))/1000000000 as cpu from statement_info where request_at >'2023-07-22 14:41:20' and request_at< '2023-07-22 14:56:06';---request_at根据测试实际时间更改
统计mem sql：
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[2]')) as float))/1024/1024/1024 as mem from statement_info where request_at >'2023-07-22 14:41:20' and request_at< '2023-07-22 14:56:06';---request_at根据测试实际时间更改

ps监控数据生成的文件统计cpu的值
awk '{print $8}' resr-tpcc10.txt > tpcc_cpu.txt
之后计算数据平均值，总时间为平均值/100*总运行时间秒

ps监控数据生成的文件统计mem的值
awk '{print $9}' resr-tpcc10.txt > tpcc_mem.txt
之后计算数据和，单位是kb换算成GB，除以总运行时间秒为每秒占用内存大小
```

**Comment by heni02** [comment]
@dongdongyang33 plz confirm this issue

**Comment by dongdongyang33** [comment]
两者统计值的不同：
* `ps` 命令统计的是该进程在某个时段内所有消耗
* `analyze info` 统计的是某条 sql 在执行阶段的算子执行消耗的资源

单条 sql 除了算子的执行，还有 parse / build plan 等其他步骤，这部分的消耗是没有统计在 analyze info 中的，但是这部分的消耗会被 `ps` 命令观察到
除此以外，以上的测试是基于本地启动的 mo 得出的结果，本地启动的 mo 进程里除了包含 CN 部分，DN 和 logservice 也在同一个进程里，这部分的消耗也会被包含到 `ps` 结的果里。

所以 `ps` 命令观察到的结果是有可能远大于 `analyze info` 里面显示的结果的

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by LiSong0214** [comment]
不要求1.0 一定做完

**Comment by ouyuanning** [comment]
之前的issue先关闭吧。后续统计信息的部分可以在这个issue统一跟踪
https://github.com/matrixorigin/MO-Cloud/issues/1850

**Comment by heni02** [comment]
ok closed
