### ISSUE TITLE
[Bug]: mo reboot error after executing alter statement

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#10830]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The recurrence process of error reporting is shown in the following document：
[问题报错的复现流程.txt](https://github.com/matrixorigin/matrixone/files/12141604/default.txt)

**Comment by qingxinhome** [comment]
If I execute multiple alter table statements and restart mo, I will still report an error
[问题报错的复现流程更新.txt](https://github.com/matrixorigin/matrixone/files/12146447/default.txt)

**Comment by aptend** [comment]
not into this yet

**Comment by qingxinhome** [comment]
Confirm that the issue has been resolved， thanks @aptend
