### ISSUE TITLE
[Bug]: Inserts a non-int value into a auto_increment column, rounding error.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10842]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a57df9af7694ff86d1c57b0c35e653c6e28fb029
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1306" alt="企业微信截图_9937cc86-b6be-4aac-aacd-81aaae7f9d8c" src="https://github.com/matrixorigin/matrixone/assets/108530700/471f5927-1ab5-4397-a85c-c7aeac3b959a">

### Steps to Reproduce

```Markdown
Drop table if exists auto_increment09;
create table auto_increment09(col1 int auto_increment primary key)auto_increment = 10;
Insert into auto_increment09 values();
Insert into auto_increment09 values();
Select * from auto_increment09;
Insert into auto_increment09 values(16.898291);
insert into auto_increment09 values();
select last_insert_id();
Select * from auto_increment09;
Drop table auto_increment09;
```

**Comment by sukki37** [comment]
This issue seems resolved. Closing now. Reopen if needed. Thanks!

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by Ariznawlll** [comment]
**commit：c1751aa204f5e21e1c247299b2a7a1b3366a991a**
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/a71ba18f-cbe0-42fd-9779-7b67e771c13a">
没修，测试不通过

**Comment by allengaoo** [comment]
首先，这个问题产生的原因是因为用户输入了non-int 的值，对于这种情况，建议不需要严格遵守mysql 的产品行为，只要在MO 自己的文档中明确我们自己的行为即可。

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
