### ISSUE TITLE
[Subtask]: mo_br 与 operator连调

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#10846]
### Parent Issue

#6629

### Detail of Subtask

备份还原与operator连调

**Comment by aylei** [comment]
working on this

**Comment by aylei** [comment]
已经可以在 mo-operator v1.0.0-alpha.1 上测试：

文档：https://github.com/matrixorigin/matrixone-operator/blob/main/docs/getting_started.md

**Comment by aylei** [comment]
等待测试

**Comment by aylei** [comment]
等待测试

**Comment by aylei** [comment]
doc: https://github.com/matrixorigin/matrixone-operator/blob/main/docs/getting_started.md#backup-and-restore
