### ISSUE TITLE
[Feature Request]: Add sum in zonemap for numeric data

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#10856]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Add Sum in Zone map for numeric data types.   Since we have 64 bytes in zonemap, we can easily hold min/max then a sum.
```

### Describe the feature you'd like

Add sum. 

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
This field is UnUsed anyway so we do not need to do anything for migration.
```

**Comment by fengttt** [comment]
Sum can be just float64 (maybe int64 for big int).

**Comment by XuPeng-SH** [comment]
assign to @w-zr

**Comment by w-zr** [comment]
Completed by https://github.com/matrixorigin/matrixone/pull/11100.

**Comment by XuPeng-SH** [comment]
done

**Comment by w-zr** [comment]
Completed by https://github.com/matrixorigin/matrixone/pull/11690
