### ISSUE TITLE
[Tech Request]: Needs to estimate S3 count while do insert

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#10862]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
ExecPlan's AnalyzeInfo has `0` value in stats, caused by 1) input directly write log, not S3 file; 2) backgroud compaction task will cost more S3IO.

Since MOCloud dependent on the stats value collected from ExecPlan to calculate CU, then it so NO  S3 io while do insert.
```

### Describe the feature you'd like

Need algorithm can calculate the S3 io count while do insert query, and fill the value into ExecPlan's AnalyzeInfo

### Describe implementation you've considered

1. When inserting big data, CN will write s3 and count the number of these s3. (p-1)
2. When inserting small data, TN can count information, such as: rows. (p0)

### Additional information

MOC Issue: https://github.com/matrixorigin/MO-Cloud/issues/1015

**Comment by xzxiong** [comment]
@domingozhang @LeftHandCold  ptal

**Comment by xzxiong** [comment]
@LeftHandCold  ptal. Is there have any plan.

**Comment by LeftHandCold** [comment]
"small data written by TN" cannot be counted for the time being and needs to be discussed before it can be determined.

**Comment by xzxiong** [comment]
@LeftHandCold is there any update ?

**Comment by LeftHandCold** [comment]
@qingxinhome pls

**Comment by qingxinhome** [comment]
<img width="1655" alt="企业微信截图_8a8c5f2c-fa68-4980-ab7f-433e00c6a4ab" src="https://github.com/user-attachments/assets/41dc92b5-810e-44ca-b7c5-13433740fac9">

**Comment by daviszhen** [comment]
pr中

**Comment by qingxinhome** [comment]
该功能已经是实现并合并，请验证测试

**Comment by aressu1985** [comment]
以TPCH 100G customer表为例，源文件的大小为：2463490271 bytes, 但实际input size 为：3390488715
<img width="660" alt="image" src="https://github.com/user-attachments/assets/3efebfa9-a52d-4b12-be5e-a1d19b0f662d">


物理执行计划：
[statement_info.txt](https://github.com/user-attachments/files/17789624/statement_info.txt)

**Comment by qingxinhome** [comment]
> 以TPCH 100G customer表为例，源文件的大小为：2463490271 bytes, 但实际input size 为：3390488715 <img alt="image" width="660" src="https://private-user-images.githubusercontent.com/47846308/386937370-3efebfa9-a52d-4b12-be5e-a1d19b0f662d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTI1OTMsIm5iZiI6MTczMTkxMjI5MywicGF0aCI6Ii80Nzg0NjMwOC8zODY5MzczNzAtM2VmZWJmYTktYTUyZC00YjEyLWJlNWUtYTFkMTliMGY2NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA2NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMDY2NDA0ZTc0ZGQzNDA2MDQxMTkxNGY3MDQzOTg4Nzk1MGNjMjgzNTQwNjNlN2ExODA0ZWE5MTRkMWRlMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6FRg0ArFPYYRZZ9wnLUFBQKm_Md5qK-RnVcD1027ZIg">
> 
> 物理执行计划： [statement_info.txt](https://github.com/user-attachments/files/17789624/statement_info.txt)

数据文件被加载到表中后， 在内存是以batch（vectors）的方式存在， 由于数据结构的以及属性的存在，会使其大小放大

**Comment by aressu1985** [comment]
fixed

**Comment by xzxiong** [comment]
@qingxinhome 请问目前考虑 WriteRow 和 DeleteRow 两者都计入统计了么？

**Comment by qingxinhome** [comment]
> @qingxinhome 请问目前考虑 WriteRow 和 DeleteRow 两者都计入统计了么？

deleteRows 和 WrittenRows都计入估算统计了
