### ISSUE TITLE
[Bug]: pessimistic mode：pipeline hung

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10882]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): bd7286d622d9be1b84a64822e2a143dc74c4e0f3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
**can not repro locally.**

https://github.com/matrixorigin/matrixone/actions/runs/5667925051/job/15357619317?pr=10877
the wrong case path：matrixone/matrixone/test/distributed/cases/dml/update/update_index.test [row:26]

https://github.com/matrixorigin/matrixone/actions/runs/5668123547/job/15358200827?pr=10881
the wrong case path：matrixone/matrixone/test/distributed/cases/dml/delete/delete_index.test [row:117]

https://github.com/matrixorigin/matrixone/actions/runs/5688079541/job/15417430315?pr=10894 [row:312]

https://github.com/matrixorigin/matrixone/actions/runs/5717238289/job/15490561744?pr=10937 [row:156]

https://github.com/matrixorigin/matrixone/actions/runs/5725316420/job/15513581631?pr=10917
### Expected Behavior

<img width="713" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3206bd3f-b6b7-41e7-bb91-8bdb078018b6">
<img width="861" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/70db07bb-ba5c-4057-8f33-356a9a0eb04a">
<img width="954" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/afee2825-5ac0-45ea-8aaf-2c00d9cf8c1e">
<img width="1038" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c37e01df-35b6-4c89-aef6-29c56d266641">
<img width="1036" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0d468e06-3f4f-4980-bc02-84a64c4e3527">

**Comment by zhangxu19830126** [comment]
悲观事务的bvt，极大概率在ci上失败，检查都是hung在2个地方，分析过后，主要是ctx被cancel了，从channel里面取值就永远等到不到了，被卡死。

**Comment by m-schen** [comment]
还在处理其他s-1，让qx帮忙先处理一下试试。暂不用换owner.

**Comment by jensenojs** [comment]
很难说只是pipeline hung住的问题，https://github.com/jensenojs/matrixone/actions/runs/5711750669/job/15473912910

这个mo-tester侧也会显示no return result in 12000 ms.

<img width="1734" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/7a425d81-426d-4735-8e62-f4c5202e39bb">

但是这个insert的失败并没有导致后续case的连锁失败。

目前的cases集中失败在unique_index中

**Comment by dongdongyang33** [comment]
> 悲观事务的bvt，极大概率在ci上失败，检查都是hung在2个地方，分析过后，主要是ctx被cancel了，从channel里面取值就永远等到不到了，被卡死。
> 
> 1. https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/receiver_operator.go#L142
> 2. https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/receiver_operator.go#L82

卡在 (1) 的部分已经由 #10946 修复，但是偶尔还会有其他 case fail 并且出现卡在 (2) 的部分
出现在 (2) 意味着并不是因为 context done 没被捕获，而是这个 pipeline 有子节点确实没有结束，或者 pipeline 逻辑上出现了死锁

**Comment by m-schen** [comment]
(2)我来看。

**Comment by sukki37** [comment]
[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/12239830/multi-cn-e2e-push-docker-compose-log.zip)


another timeout occurred, https://github.com/matrixorigin/matrixone/actions/runs/5738031685/job/15551758793?pr=10987

<img width="1500" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/ac4dc8c9-bd3e-44a7-aec2-ecac34a9f8c3">

**Comment by sukki37** [comment]
[multi-cn-e2e-push-docker-compose-log (1).zip](https://github.com/matrixorigin/matrixone/files/12242805/multi-cn-e2e-push-docker-compose-log.1.zip)

https://github.com/matrixorigin/matrixone/actions/runs/5738031685/job/15552521550

<img width="1039" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/0e285552-7b86-4345-b9f3-39005152f5b3">

**Comment by m-schen** [comment]
虽然今天还没结束，但是很可能不会有什么进展，who knows.. sad.

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/5753095488/job/15595551106?pr=11014



<img width="1419" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/68d6873e-219f-40f6-a1a6-43c0aa5f77ac">

**Comment by m-schen** [comment]
唉 只能说明天争取定位到问题。

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/5767963802/job/15638396272?pr=11044

<img width="1065" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c807a85f-1568-4d0a-882f-83a1d5481f70">

**Comment by Ariznawlll** [comment]
<img width="1001" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1f96f71d-3ca9-4afe-9057-50caf950e206">
https://github.com/matrixorigin/matrixone/actions/runs/5769081834/job/15640741121?pr=11047

**Comment by m-schen** [comment]
2023/08/07 17:32:39.354906 +0800 ERROR lockop/lock_op.go:268 error: txn need retry in rc mode {"span": {"trace_id": "124985b8-3505-11ee-be66-46f6e41a5fe4", "kind": "statement"}}

2023/08/07 17:32:39.355233 +0800 ERROR types/tuple.go:709 error: internal error: unable to decode tuple element with unknown typecode 35

2023/08/07 17:32:39.355275 +0800 ERROR function/list_builtIn.go:4846 error: Duplicate entry '50' for key 'c' {"span": {"trace_id": "124985b8-3505-11ee-be66-46f6e41a5fe4", "kind": "statement"}}

2023/08/07 17:32:39.355318 +0800 ERROR frontend/util.go:552 Duplicate entry '50' for key 'c' {"session_info": "connectionId 116|127.0.0.1:53902|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 48869|123923e4-3505-11ee-be66-46f6e41a5fe4", "session_id": "116", "statement_id": "\u0012I\ufffd\ufffd5\u0005\u0011\ufffd\ufffdfF\ufffd\ufffd\u001a_\ufffd"}

2023/08/07 17:32:39.355386 +0800 ERROR frontend/util.go:552 query trace status {"connection_id": 116, "statement": "Insert into test_11 values(50,50)", "status": "fail", "error": "Duplicate entry '50' for key 'c'", "span": {"trace_id": "124985b8-3505-11ee-be66-46f6e41a5fe4", "kind": "statement"}, "session_info": "connectionId 116|127.0.0.1:53902|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 48869|123923e4-3505-11ee-be66-46f6e41a5fe4", "session_id": "116", "statement_id": "\u0012I\ufffd\ufffd5\u0005\u0011\ufffd\ufffdfF\ufffd\ufffd\u001a_\ufffd"}

2023/08/07 17:32:39.355630 +0800 ERROR compile/scope.go:139 [cms] start to receive pre, sql is , p is 0x14000f23998, len(pre) = 1, len(remote) = 0

有可能是报重复键错了又retry了结果导致的卡死。不是很确定。

**Comment by m-schen** [comment]
唯一约束查重过程中对null值的处理不对导致了该问题，在pr中已修复。跑了3遍没有出现该问题。
不过还没想明白为什么经过怎样的流程会导致卡死，pr暂不合入。

**Comment by m-schen** [comment]
昨天的pr应该和这个卡住没什么关系，应该只是恰好减少了日志的数量导致复现概率降低了。
还在确认是否和日志有关系，本地复现时通过打印堆栈发现卡在了export/batch_processor.go的Collect方法，不能肯定。

**Comment by m-schen** [comment]
已修复，可验证。

pr 11099和这个没有关系，后续会单独提。

**Comment by dongdongyang33** [comment]
> 已修复，可验证。 卡住的原因是 当pipeline为 A -> B 且由B（接收方）结束了pipeline时，清理B的过程中会尝试继续从A收取数据，直到收到nil(结束的标记）。 由于A的上下文继承于B，会同步结束，导致A不一定会发出nil数据(select case done : case send走了第一个case)。因此卡死（与协程的调度有关，因此偶现）。
> 
> pr 11099和这个没有关系，后续会单独提。

应该不是这个原因？
虽然会不小心走到没有发送 nil 的路径（设计上这是出错关闭的路径）但是最终一定会关闭 channel，清理的过程是收到 nil 或者发现 channel 关闭都可以退出

**Comment by m-schen** [comment]
> > 已修复，可验证。 卡住的原因是 当pipeline为 A -> B 且由B（接收方）结束了pipeline时，清理B的过程中会尝试继续从A收取数据，直到收到nil(结束的标记）。 由于A的上下文继承于B，会同步结束，导致A不一定会发出nil数据(select case done : case send走了第一个case)。因此卡死（与协程的调度有关，因此偶现）。
> > pr 11099和这个没有关系，后续会单独提。
> 
> 应该不是这个原因？ 虽然会不小心走到没有发送 nil 的路径（设计上这是出错关闭的路径）但是最终一定会关闭 channel。清理的过程是收到 nil 或者发现 channel 关闭都可以退出，所以不应该会卡住。 不过可能会收到很多误报的 `children pipeline closed unexpectedly`

我实际定位出卡死的地方是这里。卡死时只剩下接收方在等待数据，发送方的pipeline的协程已经全部结束了。可能用close去控制漏掉了些什么东西，也可能是之前clean pipeline前没有全部的地方调用cancel去防止产生新数据导致的。这个我还不能十分肯定。用close控制逻辑上是没有问题的，感觉可能是具体代码实现上有问题。need check.

**Comment by sukki37** [comment]
> repro： https://github.com/matrixorigin/matrixone/actions/runs/5818682422/job/15775588094 <img alt="image" width="1222" src="https://user-images.githubusercontent.com/77312370/259791266-2f0cae1a-b032-426a-b94e-aa8a05f0dec7.png">
> 
> @m-schen, please continue to fix this one.

my mistake, this bug hasn't been reproduced after #11137, so this issue can be downgraded and continue to be observed for a while.
