### ISSUE TITLE
[Bug]: S3input and S3output value is smaller than AWS statistical data

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10889]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-2304a852
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

statement_info stats字段s3input和s3output数值正确性验证，发现值比aws统计值小很多，不符合预期，下面是具体测试场景和数据：
mo环境：proxy，1个资源组2cn，普通租户ap1_account测试
测试场景1:tpch10G 运行多次16min+
测试结果：s3input/output分别对比aws REST.PUT.OBJECT/REST.GET.OBJECT值，都比平台统计值小很多
1.s3input该时间段内总值：0；aws REST.PUT.OBJECT值为15176
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[3]')) as float)) as s3input from statement_info where request_at >'2023-07-26 10:16:13' and request_at< '2023-07-26 10:33:05';
<img width="1288" alt="企业微信截图_42dcc849-430c-41e7-9d84-e115aeadb1a0" src="https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/587944c8-1a3d-4b40-820a-2e3fbbafd2e6">
总时间段：
<img width="1098" alt="企业微信截图_5fb21422-6410-4086-b204-4bd12b986c7d" src="https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/4e0e501a-814f-4f69-9a6f-49c799bdcd7a">

2.s3output该时间段内总值：1413；aws REST.GET.OBJECT值为22457
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[4]')) as float)) as s3output from statement_info where request_at >'2023-07-26 10:16:13' and request_at< '2023-07-26 10:33:05';
<img width="1290" alt="企业微信截图_5ed0081d-d8cb-4963-831c-a283fc73d9d0" src="https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/c61c7282-1a3c-44d6-83b8-a48eff6792d7">

该时间段内aws统计值：
![image](https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/b70728de-3f1a-45a7-b6a6-09fad86588d0)

测试场景2:load 5990w+数据
测试结果：s3input/output分别对比aws REST.PUT.OBJECT/REST.GET.OBJECT值，都比平台统计值小
1.s3 input该时间段内总值：208；aws REST.PUT.OBJECT值999
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[3]')) as float)) as s3input from statement_info where request_at >'2023-07-26 10:53:32' and request_at< '2023-07-26 10:57:34';
<img width="1289" alt="企业微信截图_b3b833ae-62e4-4076-9d42-d8fd22be804f" src="https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/69b8a5b8-bd64-4064-9d8e-a257d03189ef">

2.s3output该段时间段内总值：208；aws REST.GET.OBJECT值734
select sum(cast(JSON_UNQUOTE(JSON_EXTRACT(stats, '$[4]')) as float)) as s3output from statement_info where request_at >'2023-07-26 10:53:32' and request_at< '2023-07-26 10:57:34';
<img width="1285" alt="企业微信截图_cdc65e26-1eb8-46c4-91cb-e42204936055" src="https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/2b259c75-b695-499e-a500-d09fe4329982">

该时间段内aws统计值：
<img width="439" alt="企业微信截图_ae27faea-ac44-4a33-bef4-003517ddd589" src="https://github.com/matrixorigin/mo-nightly-regression/assets/113406637/cc31c792-fb49-490f-bf80-adf7082dd620">

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by LiSong0214** [comment]
不要求1.0 一定做完
