### ISSUE TITLE
[Bug]: MO logservice fail to shutdown in distribute mode  caused by motrace

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#10887]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 5b30ed3ab
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

run in distribute mode, with multi cn. in  docker env.
CN / DN already shutdown
LogService failed to shutdown.

<img width="1222" alt="企业微信截图_901ea104-746e-4b9e-8482-7ad0ef82a51a" src="https://github.com/matrixorigin/matrixone/assets/3927687/6944a795-c1dc-4d85-8842-ee18ba69c92f">

**Comment by xzxiong** [comment]
try repro as standalone with 1 CN, got goroutinue

[goroutine.txt](https://github.com/matrixorigin/matrixone/files/12206323/goroutine.txt)

**Comment by gouhongshen** [comment]
the shutdown command behavior was corrected by #10671

**Comment by xzxiong** [comment]
hard to repro, wait somebody repro
- Add: expose logservice's pprof port, #10989

**Comment by xzxiong** [comment]
not repro, no clues
