### ISSUE TITLE
[Bug]: default value of autocommit is off and default value is not effective

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10898]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bdc86a4e934981340105cf051b50c5e9f36549ef
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the default value:
mysql> show variables like 'auto%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| auto_generate_certs      | off   |
| auto_increment_increment | 1     |
| auto_increment_offset    | 1     |
**| autocommit               | on    |**
| automatic_sp_privileges  | off   |
+--------------------------+-------+
5 rows in set (0.01 sec)

but when run a insert in a txn and do not commit:
mysql> create table t1(a int);
Query OK, 0 rows affected (0.08 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.08 sec)

mysql> insert into t1 values(1);
Query OK, 1 row affected (0.03 sec)

in a another txn, it can see the result:
Database changed
mysql> select * from t1;
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.01 sec)

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
@aressu1985 
autocommit 是 on呀。自动提交结果。我认为行为是对的。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/84c57f80-3375-4d20-abf5-1a6da4cb4df7)

**Comment by daviszhen** [comment]
@aressu1985  而且git log 里面没找到 commit bdc86a4e934981340105cf051b50c5e9f36549ef

**Comment by tianyahui-python** [comment]
最新代码, 复现步骤:
1.登录 sys 租户
2.创建普通租户create account test_tenant_1 admin_name 'test_account' identified by '111';
3.登录普通租户
4.mysql> show variables like '%autocommit%';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| autocommit    | off   |
+---------------+-------+
1 row in set (0.01 sec)
bug 描述: 普通租户的默认autocommit配置为关闭的, 但是在执行sql的过程中的行为还是autocommit开启的行为

**Comment by daviszhen** [comment]
变量v没有重新赋值。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/e914ec7c-d568-47fe-9959-17ab91e6cd31)

**Comment by fengttt** [comment]
bug 描述: 普通租户的默认autocommit配置为关闭的,

Why?

**Comment by daviszhen** [comment]
pr 卡在https://github.com/matrixorigin/matrixone/issues/10882 上了

**Comment by daviszhen** [comment]
it was fixed

**Comment by aronchanisme** [comment]
commitid
```bash
root@test0:/data/mo/20230802/matrixone# mo_ctl get_cid
2023-08-10 10:41:33.641 UTC+0800    [INFO]    Try get mo commit id
commit 8af14455f059e657890f4249ca63699476bb7f63
Author: XuPeng-SH <xupeng3112@163.com>
Date:   Thu Aug 10 00:01:28 2023 +0800

    dn vector wrapper supports const vector (#11133)
    
2023-08-10 10:41:33.678 UTC+0800    [INFO]    Get commit id succeeded
```

Currently it seems setting `autocommit` is set to `on` for common tenant user. And under this condition, the behavior is acting as expected.
<img width="1698" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/e7896da5-cd32-46be-a073-64ffd426a49d">

**Comment by matrix-meow** [comment]
Hello @aressu1985. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by daviszhen** [comment]
好像还有点问题。我在看下结果

**Comment by daviszhen** [comment]
已经确认了pr没问题。应该解决掉了。再转给苏动。
