### ISSUE TITLE
[Bug]: panic interface conversion: interface {} is []int64, not []bool

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#10908]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/28624654/fae8b51f-483b-49b3-9d6f-45325c0f932d)

![d8031d0bde0296c3b6081648c695be1](https://github.com/matrixorigin/matrixone/assets/28624654/059d0087-b2e2-4e9b-b2fe-0de0615ca24b)

### Steps to Reproduce

```Markdown
create table t2 (a int, b int unique key, c int, d int, primary key(c,d));
delete from t2 where b in (c in (select 1) and d in (select 1));
```
```


### Additional information

_No response_

**Comment by ouyuanning** [comment]
PR is reviewing
