### ISSUE TITLE
[Bug]:`show processlist;` sql error occurred on Aliyun Platform

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#10906]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

like issue：
https://github.com/matrixorigin/MO-Cloud/issues/1045

**Comment by volgariver6** [comment]
fixed by #10910
