### ISSUE TITLE
[Bug]: [storage compatibility] lots of show system_tables result are not correct from commit: 2257011 to 5c57d1b

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10921]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5c57d1b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5701545177/job/15458984409

2023-07-30 07:15:04 ERROR RSRow:65 - The value of [row:44,column:2] does not equal with each other,one is [NO],but the other is [YES]
2023-07-30 07:15:04 ERROR Executor:159 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/database/system_table.sql][row:16][show columns from `user`;] was executed failed, con[id=0, user=dump, ***
2023-07-30 07:15:04 ERROR Executor:161 - [EXPECT RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
host    CHAR(255)    NO    PRI    ''        
user    CHAR(32)    NO    PRI    ''        
select_priv    VARCHAR(10)    NO        'N'        
insert_priv    VARCHAR(10)    NO        'N'        
update_priv    VARCHAR(10)    NO        'N'        
delete_priv    VARCHAR(10)    NO        'N'        
create_priv    VARCHAR(10)    NO        'N'        
drop_priv    VARCHAR(10)    NO        'N'        
reload_priv    VARCHAR(10)    NO        'N'        
shutdown_priv    VARCHAR(10)    NO        'N'        
process_priv    VARCHAR(10)    NO        'N'        
file_priv    VARCHAR(10)    NO        'N'        
grant_priv    VARCHAR(10)    NO        'N'        
references_priv    VARCHAR(10)    NO        'N'        
index_priv    VARCHAR(10)    NO        'N'        
alter_priv    VARCHAR(10)    NO        'N'        
show_db_priv    VARCHAR(10)    NO        'N'        
super_priv    VARCHAR(10)    NO        'N'        
create_tmp_table_priv    VARCHAR(10)    NO        'N'        
lock_tables_priv    VARCHAR(10)    NO        'N'        
execute_priv    VARCHAR(10)    NO        'N'        
repl_slave_priv    VARCHAR(10)    NO        'N'        
repl_client_priv    VARCHAR(10)    NO        'N'        
create_view_priv    VARCHAR(10)    NO        'N'        
show_view_priv    VARCHAR(10)    NO        'N'        
create_routine_priv    VARCHAR(10)    NO        'N'        
alter_routine_priv    VARCHAR(10)    NO        'N'        
create_user_priv    VARCHAR(10)    NO        'N'        
event_priv    VARCHAR(10)    NO        'N'        
trigger_priv    VARCHAR(10)    NO        'N'        
create_tablespace_priv    VARCHAR(10)    NO        'N'        
ssl_type    VARCHAR(10)    NO        ''        
ssl_cipher    BLOB(0)    NO        null        
x509_issuer    BLOB(0)    NO        null        
x509_subject    BLOB(0)    NO        null        
max_questions    INT UNSIGNED(32)    NO        '0'        
max_updates    INT UNSIGNED(32)    NO        '0'        
max_connections    INT UNSIGNED(32)    NO        '0'        
max_user_connections    INT UNSIGNED(32)    NO        '0'        
plugin    CHAR(64)    NO        'caching_sha2_password'        
authentication_string    TEXT(0)    YES        null        
password_expired    VARCHAR(10)    NO        'N'        
password_last_changed    TIMESTAMP(0)    YES        null        
password_lifetime    SMALLINT UNSIGNED(16)    YES        null        
account_locked    VARCHAR(10)    NO        'N'        
create_role_priv    VARCHAR(10)    NO        'N'        
drop_role_priv    VARCHAR(10)    NO        'N'        
password_reuse_history    SMALLINT UNSIGNED(16)    YES        null        
password_reuse_time    SMALLINT UNSIGNED(16)    YES        null        
password_require_current    VARCHAR(10)    YES        null        
user_attributes    JSON(0)    YES        null        
[202](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5701545177/job/15458984409#step:6:203)3-07-30 07:15:04 ERROR Executor:162 - [ACTUAL RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
host    CHAR(255)    YES    PRI    ''        
user    CHAR(32)    YES    PRI    ''        
select_priv    VARCHAR(10)    YES        'N'        
insert_priv    VARCHAR(10)    YES        'N'        
update_priv    VARCHAR(10)    YES        'N'        
delete_priv    VARCHAR(10)    YES        'N'        
create_priv    VARCHAR(10)    YES        'N'        
drop_priv    VARCHAR(10)    YES        'N'        
reload_priv    VARCHAR(10)    YES        'N'        
shutdown_priv    VARCHAR(10)    YES        'N'        
process_priv    VARCHAR(10)    YES        'N'        
file_priv    VARCHAR(10)    YES        'N'        
grant_priv    VARCHAR(10)    YES        'N'        
references_priv    VARCHAR(10)    YES        'N'        
index_priv    VARCHAR(10)    YES        'N'        
alter_priv    VARCHAR(10)    YES        'N'        
show_db_priv    VARCHAR(10)    YES        'N'        
super_priv    VARCHAR(10)    YES        'N'        
create_tmp_table_priv    VARCHAR(10)    YES        'N'        
lock_tables_priv    VARCHAR(10)    YES        'N'        
execute_priv    VARCHAR(10)    YES        'N'        
repl_slave_priv    VARCHAR(10)    YES        'N'        
repl_client_priv    VARCHAR(10)    YES        'N'        
create_view_priv    VARCHAR(10)    YES        'N'        
show_view_priv    VARCHAR(10)    YES        'N'        
create_routine_priv    VARCHAR(10)    YES        'N'        
alter_routine_priv    VARCHAR(10)    YES        'N'        
create_user_priv    VARCHAR(10)    YES        'N'        
event_priv    VARCHAR(10)    YES        'N'        
trigger_priv    VARCHAR(10)    YES        'N'        
create_tablespace_priv    VARCHAR(10)    YES        'N'        
ssl_type    VARCHAR(10)    YES        ''        
ssl_cipher    BLOB(0)    YES        null        
x509_issuer    BLOB(0)    YES        null        
x509_subject    BLOB(0)    YES        null        
max_questions    INT UNSIGNED(32)    YES        '0'        
max_updates    INT UNSIGNED(32)    YES        '0'        
max_connections    INT UNSIGNED(32)    YES        '0'        
max_user_connections    INT UNSIGNED(32)    YES        '0'        
plugin    CHAR(64)    YES        'caching_sha2_password'        
authentication_string    TEXT(0)    NO        null        
password_expired    VARCHAR(10)    YES        'N'        
password_last_changed    TIMESTAMP(0)    NO        null        
password_lifetime    SMALLINT UNSIGNED(16)    NO        null        
account_locked    VARCHAR(10)    YES        'N'        
create_role_priv    VARCHAR(10)    YES        'N'        
drop_role_priv    VARCHAR(10)    YES        'N'        
password_reuse_history    SMALLINT UNSIGNED(16)    NO        null        
password_reuse_time    SMALLINT UNSIGNED(16)    NO        null        
password_require_current    VARCHAR(10)    NO        null        
user_attributes    JSON(0)    NO        null        
2023-07-30 07:15:04 ERROR RSRow:65 - The value of [row:12,column:2] does not equal with each other,one is [NO],but the other is [YES]
2023-07-30 07:15:04 ERROR Executor:159 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/database/system_table.sql][row:17][show columns from `db`;] was executed failed, con[id=0, user=dump, ***
2023-07-30 07:15:04 ERROR Executor:161 - [EXPECT RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
host    CHAR(255)    NO    PRI    ''        
db    CHAR(64)    NO    PRI    ''        
user    CHAR(32)    NO    PRI    ''        
select_priv    VARCHAR(10)    NO        'N'        
insert_priv    VARCHAR(10)    NO        'N'        
update_priv    VARCHAR(10)    NO        'N'        
delete_priv    VARCHAR(10)    NO        'N'        
create_priv    VARCHAR(10)    NO        'N'        
drop_priv    VARCHAR(10)    NO        'N'        
grant_priv    VARCHAR(10)    NO        'N'        
references_priv    VARCHAR(10)    NO        'N'        
index_priv    VARCHAR(10)    NO        'N'        
alter_priv    VARCHAR(10)    NO        'N'        
create_tmp_table_priv    VARCHAR(10)    NO        'N'        
lock_tables_priv    VARCHAR(10)    NO        'N'        
create_view_priv    VARCHAR(10)    NO        'N'        
show_view_priv    VARCHAR(10)    NO        'N'        
create_routine_priv    VARCHAR(10)    NO        'N'        
alter_routine_priv    VARCHAR(10)    NO        'N'        
execute_priv    VARCHAR(10)    NO        'N'        
event_priv    VARCHAR(10)    NO        'N'        
trigger_priv    VARCHAR(10)    NO        'N'        
2023-07-30 07:15:04 ERROR Executor:162 - [ACTUAL RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
host    CHAR(255)    YES    PRI    ''        
db    CHAR(64)    YES    PRI    ''        
user    CHAR(32)    YES    PRI    ''        
select_priv    VARCHAR(10)    YES        'N'        
insert_priv    VARCHAR(10)    YES        'N'        
update_priv    VARCHAR(10)    YES        'N'        
delete_priv    VARCHAR(10)    YES        'N'        
create_priv    VARCHAR(10)    YES        'N'        
drop_priv    VARCHAR(10)    YES        'N'        
grant_priv    VARCHAR(10)    YES        'N'        
references_priv    VARCHAR(10)    YES        'N'        
index_priv    VARCHAR(10)    YES        'N'        
alter_priv    VARCHAR(10)    YES        'N'        
create_tmp_table_priv    VARCHAR(10)    YES        'N'        
lock_tables_priv    VARCHAR(10)    YES        'N'        
create_view_priv    VARCHAR(10)    YES        'N'        
show_view_priv    VARCHAR(10)    YES        'N'        
create_routine_priv    VARCHAR(10)    YES        'N'        
alter_routine_priv    VARCHAR(10)    YES        'N'        
execute_priv    VARCHAR(10)    YES        'N'        
event_priv    VARCHAR(10)    YES        'N'        
trigger_priv    VARCHAR(10)    YES        'N'

the log can be get from loki by namespace: mo-cpt

**Comment by reusee** [comment]
It seems not quite the same as #10911 
I'm trying to reproduce it.

**Comment by aptend** [comment]
<img width="1644" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/0811fccc-d169-4773-9d75-1f99499bbaae">

related issue #10734

the env still has unmatched data between log service and dn checkpoint

**Comment by aressu1985** [comment]
fixed
