### ISSUE TITLE
[Bug]: wrong windows function result

### ISSUE THREAD

**Issue by Morranto** [matrixorigin/matrixone#10933]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7277101809c9642cf66c89d6108475572b7b6e7f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/56924967/ced13f24-9964-4c07-b60f-943a7d2e1c9b)

### Steps to Reproduce

```Markdown
CREATE TABLE t2 (
a int,
b int
);


insert into t2 values(1,1);
insert into t2 values(2,2);
insert into t2 values(3,3);
insert into t2 values(4,4);
insert into t2 values(1,1);
insert into t2 values(5,5);
insert into t2 values(6,6);


select a,min(a) over (partition by a) ,sum(a+1) over (partition by a) from t2 ;
```

**Comment by iamlinjunhong** [comment]
处理其他 s0 中

**Comment by Ariznawlll** [comment]
<img width="1248" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1155af8b-5cc3-4ef7-ba06-092aa5cfa728">

Verified!
