### ISSUE TITLE
[Bug]: run case recursive_cte on ci error.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10934]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/5711889348/job/15474301324?pr=10881

### Steps to Reproduce

```Markdown
run bvt on ci, can not be stable repro.
```

**Comment by iamlinjunhong** [comment]
暂未复线，尝试修复 https://github.com/matrixorigin/matrixone/pull/10950

**Comment by Ariznawlll** [comment]
present in ci：https://github.com/matrixorigin/matrixone/actions/runs/5737179222/job/15548290788?pr=10917

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/5738031685/job/15550818078?pr=10987
[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/12239602/multi-cn-e2e-push-docker-compose-log.zip)

**Comment by iamlinjunhong** [comment]
并发问题，正在解决

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
Verified!
