### ISSUE TITLE
[Bug]: [date 8.2]performace: tpcc warehouse 10  terminal 50 and 100 tpmc slower more than 40%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10958]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c70e2f03c6577ce75bfe2119b09be7180f55ab5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

128 regression tpcc test:
ERROR:root:The tpmC for [warehouse=10, teminals=50] is 25.0% lower than the last one.
ERROR:root:This time: tpmC = 1[50](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5729096933/job/15525219097#step:14:51)7.89, and datetime = 2023-08-02 03:49:30
ERROR:root:Last time: tpmC = 2847.37, and datetime = 2023-08-01 03:46:05
ERROR:root:The tpmC for [warehouse=10, teminals=100] is 25.0% lower than the last one.
ERROR:root:This time: tpmC = 889.61, and datetime = 2023-08-02 03:54:36
ERROR:root:Last time: tpmC = 1464.42, and datetime = 2023-08-01 03:[51](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5729096933/job/15525219097#step:14:52):12
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5729096933/job/15525219097
<img width="1228" alt="企业微信截图_bbe55983-6864-4926-bcec-2f2021401576" src="https://github.com/matrixorigin/matrixone/assets/113406637/7accabc0-1486-4fd1-9645-73a325d6236e">

mo configure and mode:
 sed -i '/.*memory-capacity = */c\memory-capacity = "32GB"' etc/launch-tae-CN-tae-DN/cn.toml
  sed -i '/.*turn-on-push-model = */c\turn-on-push-model = true' etc/launch-tae-CN-tae-DN/cn.toml
  sed -i '/.*enable-sacrificing-freshness = */c\enable-sacrificing-freshness = true' etc/launch-tae-CN-tae-DN/cn.toml
  sed -i '/.*enable-cn-based-consistency = */c\enable-cn-based-consistency = true' etc/launch-tae-CN-tae-DN/cn.toml
  ./optools/run_bvt.sh $GITHUB_WORKSPACE/head launch-tae-CN-tae-DN

**Comment by reusee** [comment]
reverted

**Comment by heni02** [comment]
date 8.4，tpcc 10 warehouse 100 terminals test on tke multi cn is more than 30% slower than date 8.3
100 warehouse 100 terminals more than 60% slower than date 8.3
<img width="899" alt="企业微信截图_e4d3e2db-4dd6-4c1a-a823-b8a383e8476d" src="https://github.com/matrixorigin/matrixone/assets/113406637/0a4b58ab-6df1-45f9-bd64-cc9c7752952f">

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by sukki37** [comment]
@heni02 Please add the commit id used for the results of these two tests

> date 8.4，tpcc 10 warehouse 100 terminals test on tke multi cn is more than 30% slower than date 8.3 100 warehouse 100 terminals more than 60% slower than date 8.3 <img alt="企业微信截图_e4d3e2db-4dd6-4c1a-a823-b8a383e8476d" width="899" src="https://user-images.githubusercontent.com/113406637/258560160-0a4b58ab-6df1-45f9-bd64-cc9c7752952f.png">

**Comment by heni02** [comment]
> more

sorry, date 8.4 commit id information can not founded, but I found yesterday date 8.7 commit id e355ec501f9472452b33078f42f1df498d7559a5 tpcc warehouse 10 terminal 100 tpmc return to the previous comparison level
<img width="731" alt="企业微信截图_6a8fecef-445e-4399-9f59-e37dfcb4fa35" src="https://github.com/matrixorigin/matrixone/assets/113406637/2113d8a9-240c-4ab8-a46f-b1481d7678cc">

So there's no need to track this issue for now

**Comment by heni02** [comment]
and date 8.7 commit id :f374196d4d49ee6fea715306343b7fd6c160615c  128 regression  tpcc warehouse 10 terminal 100 tpmc also return to the previous comparison level, So there's no need to track this issue for now
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5787309991/job/15683956716
![image](https://github.com/matrixorigin/matrixone/assets/113406637/3cf2b69e-8023-4c66-a25e-6f6e2ea999c7)

**Comment by heni02** [comment]
confrim，closed
