### ISSUE TITLE
[Bug]: Can not Alter table without use the db first

### ISSUE THREAD

**Issue by gavinyue** [matrixorigin/matrixone#10959]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Can not alter table by running following sql 

```
Create DATABASE IF NOT EXISTS sbtest;

CREATE TABLE sbtest.`test` (
`raw_item` text
);

ALTER table sbtest.test ADD COLUMN test TEXT;
```

### Expected Behavior

Should be able to alter table to add the columns

### Steps to Reproduce

```Markdown
Under current main branch, run above sql
```

**Comment by qingxinhome** [comment]
The issue has been resolved and merged. Please test and verify @gavinyue @fengttt @daviszhen @domingozhang

**Comment by gavinyue** [comment]
Fixed thank you.
