### ISSUE TITLE
[Bug]: [date 8.2]performace: tpch 100G cost time slower than 21% 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10966]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c70e2f03c6577ce75bfe2119b09be7180f55ab5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpch 100G launch-tae-CN-tae-DN performace data, date 8.2 slower than 21%
<img width="1053" alt="企业微信截图_1d7aef14-b978-4ffd-b498-6754a76e34f6" src="https://github.com/matrixorigin/matrixone/assets/113406637/eacd7a1e-a247-4ace-a437-e29dee0c5a8a">
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5729096933/job/15525219965
<img width="1885" alt="企业微信截图_1d588f2b-310b-4991-ba48-d3bb22807c80" src="https://github.com/matrixorigin/matrixone/assets/113406637/caad8704-5b77-4634-869b-c7e45ad0b7d4">

**Comment by badboynt1** [comment]
caused by https://github.com/matrixorigin/matrixone/pull/10952

**Comment by reusee** [comment]
duplicated: https://github.com/matrixorigin/matrixone/issues/10978

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
The reason identified is a decrease in performance due to missing configuration parameters, and after verification, the performance data returned to normal,the  parameter is:
[fileservice.cache]
memory-capacity = "32GB"

date 8.9 8.10 :
<img width="918" alt="企业微信截图_a61cf25c-0dd9-4c1e-a0b9-00796e97090d" src="https://github.com/matrixorigin/matrixone/assets/113406637/44c03f28-a324-4a71-8dfc-421bbdab1c52">

confirm,closed
