### ISSUE TITLE
[Bug]: TPCH 100G cost increase more than 20% percentage for commit 1c70e2f03 on standlone mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10978]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1c70e2f03
- Hardware parameters:64C 256G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5729096933/job/15525219965

<img width="1396" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/c2edbc56-0938-4154-a7e8-4ed5f38d0e4f">

INFO:root:This time: sum(cost) = **123063**, and datetime = 2023-08-02 04:24:42
INFO:root:Last two times[0]: sum(cost) = **101583**, and datetime = 2023-08-01 04:20:55
INFO:root:Last two times[1]: sum(cost) = **101933**, and datetime = 2023-07-31 21:41:19

the last commit : 60c123ae5

the last job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5716901178/job/15489594573
<img width="1407" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/145862ab-2aea-4885-99f7-a80309a439b7">

**Comment by reusee** [comment]
may be related: https://github.com/matrixorigin/matrixone/commit/1c70e2f03c6577ce75bfe2119b09be7180f55ab5
investigating.

**Comment by sukki37** [comment]
> may be related: [1c70e2f](https://github.com/matrixorigin/matrixone/commit/1c70e2f03c6577ce75bfe2119b09be7180f55ab5) investigating.

from the results of bisect, it appears that the performance degradation is a result of #10952

**Comment by reusee** [comment]
reverted

**Comment by aressu1985** [comment]
testing

**Comment by Ariznawlll** [comment]
<img width="690" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ff003970-a4fc-42ec-ba36-c06d17660ec9">


<img width="1341" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b3d7a48b-830c-40ee-ab0d-c23529377f89">

**Comment by sukki37** [comment]
The performance drop was due to changes in the memory cache configuration（32G -> 512M）. After adjusting the parameters, the performance has returned to normal levels, so this issue will be closed for now.

<img width="900" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/695901f4-f70b-426c-8429-08ee97950880">
