### ISSUE TITLE
[Bug]: index out of range [0] with length 0 in mergeblocks after 35 bvt runs

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#10981]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):73433c45b
- Hardware parameters:Ubuntu22.04
- OS type:
- Others:
```

### Actual Behavior

<img width="1653" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b52f2fd9-f767-4894-81c0-0605440f7562">

### Steps to Reproduce

```Markdown
run bvt over and over again
```

**Comment by aptend** [comment]
已定位到问题

**Comment by aptend** [comment]
#11074 已合并
