### ISSUE TITLE
[Bug]:  account restricted status authority error under 2cn

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#10993]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4a68dbd5147dfee51439c538a38c323d375116a1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

under 2cn，account restricted same permissions as in open status
https://github.com/matrixorigin/matrixone/actions/runs/5737588504/job/15549517288?pr=10985
<img width="1438" alt="企业微信截图_423c4c33-5292-490c-8ddc-db3714f7faae" src="https://github.com/matrixorigin/matrixone/assets/113406637/cc2e6b90-bd7e-4607-b56b-0bfe30c5a98e">

**Comment by heni02** [comment]
@YANGGMM plz confirm

**Comment by YANGGMM** [comment]
have solved but still in testing

**Comment by heni02** [comment]
confirm，closed
commit id：e9255b2f9f7895f2d57da09db80c7bbe6f41e019
![image](https://github.com/matrixorigin/matrixone/assets/113406637/88d5b28e-8f9c-4e21-9919-e449da5e338a)
https://github.com/matrixorigin/matrixone/actions/runs/5851584143/job/15862559292
