### ISSUE TITLE
[Bug]:  TestHandleRead FAILED

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#10990]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[logs_160293.zip](https://github.com/matrixorigin/matrixone/files/12239156/logs_160293.zip)

https://github.com/matrixorigin/matrixone/actions/runs/5737234590/job/15548458183?pr=10987

<img width="1337" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/23e4ad9c-55c8-4134-bfa0-b2e806d83a71">

**Comment by volgariver6** [comment]
fixed.

**Comment by sukki37** [comment]
> fixed.

pls mention the fix pr
