### ISSUE TITLE
[Bug]: tpcc does not support 100 warehouse and 500/1000 terminals.

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#10992]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc does not support 100 wherehouse and 500/1000 terminals in pessimistic mode. Too many 60s timeout

**Comment by zhangxu19830126** [comment]
[500.log](https://github.com/matrixorigin/matrixone/files/12239487/500.log)

**Comment by triump2020** [comment]
tae.commit takes too much time.

**Comment by triump2020** [comment]
![aea8817007c4dc46b30ecc9246681ec](https://github.com/matrixorigin/matrixone/assets/63033222/b9e08849-5f86-4e58-a894-c0fd6a013933)

**Comment by triump2020** [comment]
root cause had been located.

![af0ece1cf09ea74b350db40e3e06c8d](https://github.com/matrixorigin/matrixone/assets/63033222/b3805fbf-01a8-4817-b2c4-9a6afb8f9b05)

**Comment by triump2020** [comment]
in testing

**Comment by triump2020** [comment]
@aressu1985  Pls test !

**Comment by aressu1985** [comment]
not fixed
still lots of timeout
job link: https://github.com/matrixorigin/mo-auto-test/actions/runs/5864321985/job/15899384167

<img width="1377" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6e7bdd49-b4f8-42d0-87d8-0e42008fd1e1">

**Comment by aressu1985** [comment]
duplicated with https://github.com/matrixorigin/matrixone/issues/11237 , and this can be closed and not s-1
