### ISSUE TITLE
[Bug]: error is not correct when runing show columns in common tenant 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:5e3bedf8aadc0823e85423c49b3464917663b632
- OS type:
- Others:
```

### Actual Behavior

When run bvt test in common tenant, the result is not correct for some cases in file system_table.sql and system_variables.sql, the error are:

2023-08-03 17:11:35 ERROR RSRow:65 - The value of [row:2,column:2] does not equal with each other,one is [YES],but the other is [NO]
2023-08-03 17:11:35 ERROR Executor:159 - [/Users/sudong/Program/aressu1985/matrixone/test/distributed/cases/database/system_table.sql][row:24][show columns from `COLUMNS`;] was executed failed, con[id=0, user=test#admin, pwd=111].
2023-08-03 17:11:35 ERROR Executor:161 - [EXPECT RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
table_catalog    VARCHAR(3)    NO        null        
table_schema    VARCHAR(256)    YES        null        
table_name    VARCHAR(256)    YES        null        
column_name    VARCHAR(256)    YES        null        
ordinal_position    INT(0)    YES        null        
column_default    VARCHAR(65535)    YES        null        
is_nullable    VARCHAR(3)    YES        null        
data_type    VARCHAR(65535)    YES        null        
character_maximum_length    BIGINT(0)    YES        null        
character_octet_length    BIGINT(0)    YES        null        
numeric_precision    BIGINT(0)    YES        null        
numeric_scale    BIGINT(0)    YES        null        
datetime_precision    BIGINT(0)    YES        null        
character_set_name    VARCHAR(4)    YES        null        
collation_name    VARCHAR(8)    YES        null        
column_type    VARCHAR(65535)    YES        null        
column_key    VARCHAR(3)    YES        null        
extra    VARCHAR(14)    YES        null        
privileges    VARCHAR(31)    NO        null        
column_comment    VARCHAR(2048)    YES        null        
generation_expression    VARCHAR(500)    NO        null        
srs_id    BIGINT(0)    YES        null        
2023-08-03 17:11:35 ERROR Executor:162 - [ACTUAL RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
table_catalog    VARCHAR(3)    NO        null        
table_schema    VARCHAR(256)    YES        null        
table_name    VARCHAR(256)    NO        null        
column_name    VARCHAR(256)    YES        null        
ordinal_position    INT(0)    YES        null        
column_default    VARCHAR(65535)    YES        null        
is_nullable    VARCHAR(3)    YES        null        
data_type    VARCHAR(65535)    YES        null        
character_maximum_length    BIGINT(0)    YES        null        
character_octet_length    BIGINT(0)    YES        null        
numeric_precision    BIGINT(0)    YES        null        
numeric_scale    BIGINT(0)    YES        null        
datetime_precision    BIGINT(0)    YES        null        
character_set_name    VARCHAR(4)    YES        null        
collation_name    VARCHAR(8)    YES        null        
column_type    VARCHAR(65535)    YES        null        
column_key    VARCHAR(3)    YES        null        
extra    VARCHAR(14)    YES        null        
privileges    VARCHAR(31)    NO        null        
column_comment    VARCHAR(2048)    YES        null        
generation_expression    VARCHAR(500)    NO        null        
srs_id    BIGINT(0)    YES        null        

2023-08-03 17:11:36 ERROR RSRow:65 - The value of [row:2,column:2] does not equal with each other,one is [YES],but the other is [NO]
2023-08-03 17:11:36 ERROR Executor:159 - [/Users/sudong/Program/aressu1985/matrixone/test/distributed/cases/database/system_variables.sql][row:86][desc columns;] was executed failed, con[id=0, user=test#admin, pwd=111].
2023-08-03 17:11:36 ERROR Executor:161 - [EXPECT RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
table_catalog    VARCHAR(3)    NO        null        
table_schema    VARCHAR(256)    YES        null        
table_name    VARCHAR(256)    YES        null        
column_name    VARCHAR(256)    YES        null        
ordinal_position    INT(0)    YES        null        
column_default    VARCHAR(65535)    YES        null        
is_nullable    VARCHAR(3)    YES        null        
data_type    VARCHAR(65535)    YES        null        
character_maximum_length    BIGINT(0)    YES        null        
character_octet_length    BIGINT(0)    YES        null        
numeric_precision    BIGINT(0)    YES        null        
numeric_scale    BIGINT(0)    YES        null        
datetime_precision    BIGINT(0)    YES        null        
character_set_name    VARCHAR(4)    YES        null        
collation_name    VARCHAR(8)    YES        null        
column_type    VARCHAR(65535)    YES        null        
column_key    VARCHAR(3)    YES        null        
extra    VARCHAR(14)    YES        null        
privileges    VARCHAR(31)    NO        null        
column_comment    VARCHAR(2048)    YES        null        
generation_expression    VARCHAR(500)    NO        null        
srs_id    BIGINT(0)    YES        null        
2023-08-03 17:11:36 ERROR Executor:162 - [ACTUAL RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
table_catalog    VARCHAR(3)    NO        null        
table_schema    VARCHAR(256)    YES        null        
table_name    VARCHAR(256)    NO        null        
column_name    VARCHAR(256)    YES        null        
ordinal_position    INT(0)    YES        null        
column_default    VARCHAR(65535)    YES        null        
is_nullable    VARCHAR(3)    YES        null        
data_type    VARCHAR(65535)    YES        null        
character_maximum_length    BIGINT(0)    YES        null        
character_octet_length    BIGINT(0)    YES        null        
numeric_precision    BIGINT(0)    YES        null        
numeric_scale    BIGINT(0)    YES        null        
datetime_precision    BIGINT(0)    YES        null        
character_set_name    VARCHAR(4)    YES        null        
collation_name    VARCHAR(8)    YES        null        
column_type    VARCHAR(65535)    YES        null        
column_key    VARCHAR(3)    YES        null        
extra    VARCHAR(14)    YES        null        
privileges    VARCHAR(31)    NO        null        
column_comment    VARCHAR(2048)    YES        null        
generation_expression    VARCHAR(500)    NO        null        
srs_id    BIGINT(0)    YES        null        

### Steps to Reproduce

```Markdown
run bvt test on common tenant, just for case file system_table.sql and system_variables.sql
```

**Comment by sukki37** [comment]
when logging in with different types of tenant accounts, specifically, system tenant accounts and regular tenant accounts. The value of the `Null` column for `table_name` when executing `show columns from information_schema.COLUMNS;` is not inconsistent.

**Comment by YANGGMM** [comment]
在忙其他issue

**Comment by YANGGMM** [comment]
创建的时候系统租户和普通租户里面的内容一样，但是 select 出来的结果不一样还在看

**Comment by YANGGMM** [comment]
目前已经定位到具体的范围，原因还没有找到

**Comment by YANGGMM** [comment]
wait other pr merge

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还未看

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test. @aressu1985 @sukki37 @daviszhen

**Comment by aressu1985** [comment]
fixed
