### ISSUE TITLE
[Bug]: some [send notify msg to dispatch operator timeout] errors during tpch 100g queries for several hours on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11018]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 5e3bedf
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

When running tpch 100g  test in a common account on distributed mode for several hours, there are lots of the following error in new order txn:
2023-08-03 19:21:10 Now start to execute the query q21,please wait.....

2023-08-03 19:24:07 The query_id is: d9571e13-31ef-11ee-836c-02b911db8de3
2023-08-03 19:24:07 Now start to compare query result for [report/TPCH_100/q21.txt,golden/TPCH_100/q21.txt]
2023-08-03 19:24:07 The row count of two files does not equal to each other, [report/TPCH_100/q21.txt] and [golden/TPCH_100/q21.txt]
2023-08-03 19:24:07The real result is:
['ERROR 20101 (HY000) at line 1: internal error: send notify msg to dispatch operator timeout\n']
2023-08-03 19:24:07 The query q21  has failed to  be executed,and cost: 176750

2023-08-03 19:44:42 Now start to execute the query q21,please wait.....

2023-08-03 19:47:44 The query_id is: 22aedbe9-31f3-11ee-836d-02b911db8de3
2023-08-03 19:47:44 Now start to compare query result for [report/TPCH_100/q21.txt,golden/TPCH_100/q21.txt]
2023-08-03 19:47:44 The row count of two files does not equal to each other, [report/TPCH_100/q21.txt] and [golden/TPCH_100/q21.txt]
2023-08-03 19:47:44The real result is:
['ERROR 20101 (HY000) at line 1: internal error: send notify msg to dispatch operator timeout\n']
2023-08-03 19:47:44 The query q21  has failed to  be executed,and cost: 182265

the mo log can be get from loki by namespace:  mo-stb-20230803

http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230803%5C%22%7D%20%7C%3D%20%60send%20notify%20msg%20to%20dispatch%20operator%20timeo%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

<img width="1385" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/a6783b65-b355-469a-b615-4d327bac2f16">

### Steps to Reproduce

```Markdown
run tpch 100G queries several hours on distributed mode
```

**Comment by badboynt1** [comment]
这个问题以前出现过，https://github.com/matrixorigin/matrixone/issues/9842
当时的修复是把超时时间从60秒提升到120秒。
现在是超时超过120秒，所以问题的本质是不是tpch越跑越慢了？

**Comment by jensenojs** [comment]
@badboynt1 涛哥， 问题是mo现在本来就是越跑越慢的（在 #7601 中跟踪），所以不好说是tpch的问题

****

 #7601 的复现方式与本issue类似，不断地轮 bvt/TPCH，跑上几个小时就速度就会越来越慢，（oom的问题另有issue跟踪）

这里给一个tldr的版本汇报一下情况：

无论是TPCH还是BVT跑一轮的SQL总数是固定的，那对应到`Pipeline`的执行次数也应该是固定的。但是现在观测到`Pipeline.run`的执行次数随着BVT轮次的上升有很明显的增长趋势。虽然执行的平均时间没有明显趋势，但是次数抬高了mo就自然慢了。

![](https://user-images.githubusercontent.com/56761542/258752884-ef2645a8-058f-4831-a1cf-a0fb0bfffd71.png)

在第一次跑完bvt后用trace进行采集30s，上面的Task被捕捉到了391次，在跑到第32次的时候，这个数字变成了一千二。现在就需要找是什么东西导致的

more info pls refer：https://github.com/matrixorigin/matrixone/issues/7601#issuecomment-1667538555

**Comment by jensenojs** [comment]
hack了一下，现在可以统计后台任务的SQL种类，顺利的话明天开会之前可以找到执行得异常得多的SQL来源

**Comment by jensenojs** [comment]
<img width="1955" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/6ed005c0-cdc8-4371-a89a-e8ec01596ec6">

**Comment by jensenojs** [comment]
请教了一下子然哥，找到了`selectAsyncTask`的SQL以及它可能会被调用的两个地方，打算再进一步确认一下是哪个地方出了问题。
1. 一个是hakeeper里面的task包里面，按配置应该是每3秒会查两次
2. task_runner有一个duFetch

所以查询频率这么高应该是不符合预期的，我在关掉了`task`之后再进行`bvt`的轮番跑，发现关闭之后的trace一些相关的埋点的统计数据就大幅下降了，甚至在10s的采集期间有时候都看不到那些跟踪的任务，与之对比是开启task时跟踪的任务触发的频率大概在三位数左右。

<img width="1292" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/027fbdec-3b0c-44c3-bf92-9b435408e134">

所以找一下为什么频率会这么高就好了

**Comment by aunjgr** [comment]
still investigating taskservice

**Comment by aunjgr** [comment]
已加trace循环测试，明早看结果

**Comment by aunjgr** [comment]
测试方法：

mo使用默认配置，在我台式机上不停循环跑bvt，每跑完5次抓取一个60s的trace文件。

测试结果：

第一次bvt用时6分钟，第65次用时13分钟，变慢趋势明显。内存也不断上升，在第66次导致OOM（台式机64GB内存）。trace显示mysqlTaskStorage.Query的调用频率并不高，无论跑bvt途中还是空闲时候，始终保持在每分钟46次左右。但是pipeline.Run里的Read调用频率确实会随着时间上升，跑完第50次后，在空闲时间里也达到了每分钟9000次。同时transaction.New和transaction.Rollback也有每分钟近3000次。

需继续调查。

**Comment by ouyuanning** [comment]
在compose环境，跑bvt，用 -t 100，偶尔会出现
<img width="874" alt="企业微信截图_75a6826c-105c-427a-8d3d-4c5043e29433" src="https://github.com/matrixorigin/matrixone/assets/45346669/78a58fbd-b3fc-4733-9f3b-591ac0264272">
不知道是否一个问题

**Comment by ouyuanning** [comment]
还有这个
<img width="565" alt="企业微信截图_e48db2dd-7b69-4135-b5ce-8ed72946320e" src="https://github.com/matrixorigin/matrixone/assets/45346669/5bd34ba5-3023-4408-b1d2-73352f837bd9">

**Comment by aunjgr** [comment]
昨天第二轮测试。

测试方法：

mo使用默认配置，在台式机上不停循环跑bvt（跳过optimistic和pessimistic目录，因为这两个可能导致mo-tester挂掉），每跑完1次抓取一个30s的trace文件。抓取trace的时候没有执行查询任务，MO处于空闲状态。

测试结果：

第1次bvt用时6分钟，第73次用时17分钟，第74次OOM。结束之后，mo_task.sys_async_task这张表有186行，但是用metadata_scan看有160个block，每个block都是1~2行。然后mysqlTaskStorage每分钟执行47次，每次会读这个表和它的unique index表，导致Reader在最后一次抓取trace的30s内被调用11081次，即读取了11081个block， 其中最长的一次花了486ms（读取单个block）。

今晚我会继续测试。

**Comment by aunjgr** [comment]
超时很可能不是单一原因导致，不过我会先跟踪空闲时间读block频率异常高的问题。

**Comment by aunjgr** [comment]
启动mo后闲置16小时再跑bvt耗时6.5min，只比启动后立即跑慢了10%。（作为对照，连续跑bvt 70多次后，时间会增长到17min，重启mo后不删mo-data目录再跑bvt也会稳定在10min。）此时mo_task.sys_async_task表有164个block，并且看trace也确实在30秒内读了8000多个block，跟昨天的测试相当。说明mo_task定期任务并不能单独导致mo在长期运行后越来越慢。

尚需继续调查。

**Comment by aunjgr** [comment]
今晚继续测试

**Comment by aunjgr** [comment]
跑50轮bvt，耗时从7分钟缓慢增长到15分钟。然后关掉MO后重启，再循环跑bvt，耗时又从7分钟开始增长。

需要先排除内存一直增长的因素。 #11383 合并之后，也许能解决内存无限制持续增长问题。今晚继续测试。

**Comment by aunjgr** [comment]
无进度

**Comment by aunjgr** [comment]
无变化，内存仍然持续增长

**Comment by aunjgr** [comment]
无进度

**Comment by aunjgr** [comment]
今晚继续测试，验证是否与 #11580 相关

**Comment by aunjgr** [comment]
正在测试，明天看结果

**Comment by aunjgr** [comment]
跑完bvt之后大量被回滚的SQL语句都是自增列相关的删除操作，`delete from mo_increment_columns where table_id = ***`。日志里报的错误类似于`{"level":"ERROR","time":"2023/09/05 19:15:21.856287 +0800","caller":"compile/sql_executor.go:104","msg":"internal sql executor error: no such table mo_catalog.mo_increment_columns"}`。重启MO之后又没有了。

麻烦 @zhangxu19830126 看看？

**Comment by zhangxu19830126** [comment]
> 跑完 bvt 之后大量被回滚的 SQL 语句都是自增列相关的删除操作，`delete from mo_increment_columns where table_id = ***`。日志里报的错误类似于 `{"level":"ERROR","time":"2023/09/05 19:15:21.856287 +0800","caller":"compile/sql_executor.go:104","msg":"internal sql executor error: no such table mo_catalog.mo_increment_columns"}`。重启 MO 之后又没有了。
> 
> 麻烦 @zhangxu19830126 看看？

这个应该是事务的可见性出问题了，已经有issue在跟踪。应该是数据的可见性出了问题。需要存储的人查一下。

**Comment by zhangxu19830126** [comment]
这个no such table在 #11672 跟踪

**Comment by aunjgr** [comment]
等相关issue修掉再继续跟踪

**Comment by aunjgr** [comment]
等相关issue修复

**Comment by aunjgr** [comment]
@aressu1985 现在tpch的问题还在吗？如果不能复现的话就先关掉这个，事务问题在另外issue跟踪

**Comment by aressu1985** [comment]
这个没有再出现过了

**Comment by jensenojs** [comment]
@aressu1985  这两个issue反应的都是mo越来越慢的问题，因为最新的进展在这个issue下更新了，这两个issue也复现不出来了，麻烦动哥看看怎么处理合适？

https://github.com/matrixorigin/matrixone/issues/7601
https://github.com/matrixorigin/matrixone/issues/7462

**Comment by aunjgr** [comment]
长时间未复现，先降级

**Comment by aunjgr** [comment]
近期未复现。应该是被内存相关改进所缓解

**Comment by aunjgr** [comment]
@aressu1985 最近这个问题还有吗？

**Comment by aressu1985** [comment]
最近没有再出现了，问题先关闭，等出现了在提
