### ISSUE TITLE
[Bug]: cn crashed by panic: BUG: active dead lock check can not fail during stabiliby test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11019]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 5e3bedf
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

During stability test on distributed mode for about more than 5 hours, on cn was crashed by panic:
{"level":"INFO","time":"2023/08/03 13:09:39.170821 +0000","caller":"frontend/util.go:516","msg":"4.709109597s","session_info":"time of Exec.Run : %s","session_id":"318","statement_id":"\ufffd\ufffd9\ufffd1\ufffd\u0011\ufffd\ufffdJ\ufffdG%"}
{"level":"INFO","time":"2023/08/03 13:09:39.181271 +0000","caller":"frontend/util.go:516","msg":"4.729278199s","session_info":"time of Exec.Run : %s","session_id":"305","statement_id":"\ufffd˶\ufffd1\ufffd\u0011\ufffd\ufffdJ\ufffdG%"}
panic: BUG: active dead lock check can not fail

goroutine 945 [running]:
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).handleLockConflictLocked(0xc006f4bba0, 0x13d9a326ab20853f?, 0xc5935d22c0, {0xc80f1864f0, 0x9, 0x9}, {{0xc80f1864d0, 0x10, 0x10}, 0x9, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:369 +0x45b
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRowLockLocked(_, {{0x2f6f4f8, 0xc7591389f0}, 0xc79e82e400, {0xc8ea238498, 0x1, 0x1}, {{0x0, 0x0, 0x0, ...}, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:290 +0x4f6
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock(_, {{0x2f6f4f8, 0xc7591389f0}, 0xc79e82e400, {0xc8ea238498, 0x1, 0x1}, {{0x0, 0x0, 0x0, ...}, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:238 +0x1f8
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock(_, {{0x2f6f4f8, 0xc7591389f0}, 0xc79e82e400, {0xc8ea238498, 0x1, 0x1}, {{0x0, 0x0, 0x0, ...}, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:101 +0x138
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock(0xc006f4bba0, {0x2f6f4f8?, 0xc7591389f0?}, 0xc79e82e400, {0xc8ea238498, 0x1, 0x1}, {{0x0, 0x0, 0x0, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:83 +0x3fa
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).handleRemoteLock(0xc001aee1e0, {0x2f6f4f8?, 0xc7591389f0}, 0xc5b4b651d0, 0xc3e1d36600, 0xc3d2fb2c80, {0x2f83ea0?, 0xc001abfef0})
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service_remote.go:98 +0x390
github.com/matrixorigin/matrixone/pkg/lockservice.(*server).onMessage.func1(0xc3e1d36600)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:249 +0x10c
github.com/matrixorigin/matrixone/pkg/lockservice.(*server).onMessage(0xc001b12e70, {0x2f6f4f8?, 0xc7591389f0?}, {{0x2f6f4f8, 0xc7591389f0}, 0xc5b4b651d0, {0x2f85b98, 0xc3e1d36600}, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:252 +0xa96
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc001abc820, {0x2f9e6a0, 0xc0064b3d00}, {0x29d3b60?, 0xc759138a20}, 0xca7760)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:238 +0x6e3
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc001abc8c0, {0x2f9e6a0, 0xc0064b3d00})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:336 +0x485
[root@VM-16-17-centos ~]# 

cn log:
[cn-crash.log](https://github.com/matrixorigin/matrixone/files/12251264/cn-crash.log)

the mo log can be get from loki by namesapce: mo-stb-20230803
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230803%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

<img width="1388" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e192cc2d-27c0-4db4-9398-d3c3be435edd">

### Steps to Reproduce

```Markdown
1、RUN a mo cluster using the same config
2、Start TPCH 100G Long Running Test in a common account
3、Start TPCC 10-10 Long Running Test in a common account
4、Start Sysbench mix cases Long Running Test in a common account

for several hours
```

**Comment by zhangxu19830126** [comment]
fixed by #11061

**Comment by heni02** [comment]
commit id:97ac52bc6ede6c9e37609fd33c0e3ee952b65f96
date 8.10 stabiliby test result not exists cn crashed and actiive dead lock check panic error
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230810%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221691634672843%22,%22to%22:%221691721072843%22%7D%7D
and not appear oom：
http://139.155.148.31:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=default&var-cluster=&var-namespace=mo-stb-20230810&from=now-24h&to=now
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c352aabc-716a-4fc9-aeff-f6b485c42714)

**Comment by heni02** [comment]
Observe for another two days

**Comment by aressu1985** [comment]
fixed
