### ISSUE TITLE
[Bug]: some deadlock in tpcc delivery txn  10-10 on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11017]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 5e3bedf
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

When running tpcc 10 warehouse 10 terminals test in a common account on distributed mode for several hours, there are lots of the following error in new order txn:
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:01:21 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:01:37 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:03:14 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:03:14 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:04:19 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:04:24 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:04:29 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:04:36 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-08-03 21:04:36 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted

the mo log can be get from loki by namesapce: mo-stb-20230803
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230803%5C%22%7D%20%7C%3D%20%60deadlock%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

<img width="1385" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/2005a977-1bda-434b-bc62-ed6d3338eb44">

### Steps to Reproduce

```Markdown
run tpcc 10-10 test for several hours on distributed mode
```

**Comment by zhangxu19830126** [comment]
it's not a bug. dead lock found is excepted error.

**Comment by zhangxu19830126** [comment]
cn has too many panic

**Comment by ouyuanning** [comment]
跑了30分钟没有复现。

大概猜测的原因，由于data race或者什么原因。
1、在projection.go 78行之前。bat 被clean 了。  （于是 87行重新调用 proc.PutBatch 的时候会报错： put batch with zero cnt

2、部分情况（比如：执行prepare的时候）。对于evalExpression.go的FixProjectionResult函数来说。
718行的 sbat.GetCnt 会大于1.  于是走到 726 行。
当726行得到的 newVec 是一个空的vector （就是真的空，不是那种曾经被使用然后被回收的情况）
那么在 727 行的 GetUnionAllFunction  中。  在满足 1 中，旧的batch已经被clean了，是0行。那么就会造成

vector.go 的1383行，extend没有效果。v.col 依然是 nil。  于是 1393 就 panic 了

**Comment by ouyuanning** [comment]
用张旭的分支。修改了deadlock.go，跑了一遍10仓10线程，一遍10仓20线程没有复现。
明天请年假，要后天再继续看了

**Comment by ouyuanning** [comment]
今天请假，无进展

**Comment by ouyuanning** [comment]
今天跟张旭在129上测了一下，尚未复现。

**Comment by ouyuanning** [comment]
今天在尝试跑compose复现，还没跑起来

**Comment by ouyuanning** [comment]
compose跑最新main未复现

**Comment by ouyuanning** [comment]
not working on this

**Comment by aressu1985** [comment]
降级成s0， 非crash/正确性/回归问题

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
10-10的死锁已处理。
cloud 中 #263的部分另外跟踪

**Comment by aressu1985** [comment]
该问题可以关闭，有其他issue在跟踪
