### ISSUE TITLE
[Bug]:select for update 0 row, alter table drop index and drop table not wait for lock 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1c70e2f03c6577ce75bfe2119b09be7180f55ab5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
select for update 0 row, mo not wait for lock, mysql wait for lock
mo:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d51fb3cc-db15-47bd-badc-7452b292a324)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/8dfad72c-f290-4047-89cf-114f739f7f7b)

mysql:
<img width="989" alt="企业微信截图_1d6a974f-b45e-40c5-915c-2924f89aefc2" src="https://github.com/matrixorigin/matrixone/assets/113406637/10a58a59-9574-4c14-bf33-dba70436f099">
<img width="603" alt="企业微信截图_8b77f4c1-f0b1-40ec-baa8-65f172f9b06e" src="https://github.com/matrixorigin/matrixone/assets/113406637/a80b00cd-b70a-4a71-8936-95da306887ed">

### Steps to Reproduce
create table su_03(c1 int not null,c2 varchar(25),c3 int,primary key(c1),key u1(c3));
insert into su_03 values(1,'results',20);
begin;
select * from su_03 where c3 in(50,70) for update;
-- @session:id=1{
use select_for_update;
alter table su_03 drop index u1;(drop table su_03;)
show create table su_03;
-- @session}
commit;

**Comment by heni02** [comment]
@qingxinhome plz confirm

**Comment by domingozhang** [comment]
needs shared lock. will be implemented in future

**Comment by qingxinhome** [comment]
After verification, the issue has been resolved. Please verify and test. @sukki37 @heni02 @daviszhen @ouyuanning

**Comment by heni02** [comment]
confirm,closed
commit id:be88e8ea481a3ea824acebe52cdee454f64f1e4e
<img width="983" alt="企业微信截图_50602c94-0b1f-42ac-ab47-f9af2fc6fdeb" src="https://github.com/matrixorigin/matrixone/assets/113406637/f2acbfd7-52d2-40c8-ae61-c896a494ae05">
<img width="850" alt="企业微信截图_5150a8b3-b55e-4996-be0d-7533fc8441d0" src="https://github.com/matrixorigin/matrixone/assets/113406637/5fd201f9-83da-4fa1-bd89-6f363c1f6da2">

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
