### ISSUE TITLE
[Bug]: the result of timestamp cast to int is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11026]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3d5b525ef9e838ef649a7a2d849317f01175ad12
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1345" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8f2f1fdb-90ca-4950-a0ab-afd914fd2d2d">

### Expected Behavior

<img width="748" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/bf20abeb-3dbf-474e-9272-4c34073a0673">

### Steps to Reproduce

```Markdown
in mo:
create table alter00(col1 timestamp);
insert into alter00 values('2003-12-31 00:00:00.000000');
insert into alter00 values('1988-01-12 09:12:34.120000');
select * from alter00;
alter table alter00 modify col1 int;
select * from alter00;

in mysql:
select timestampdiff(second,'1970-01-01 00:00:00','2003-12-31 00:00:00');
select timestampdiff(second,'1970-01-01 00:00:00','1988-01-12 09:12:34');


the rule of timestamp cast to int in mo: calculate table column and ‘1970-01-01 00:00:00’ seconds difference.
can verify in mysql with sql: select timestampdiff(second,'',''));
```

**Comment by aunjgr** [comment]
It's not a bug because `timestamp` is timezone bound. If your system timezone is +8:00 and you don't change the `time_zone` variable, `cast(cast('2003-12-31 00:00:00' as timestamp) as int)` should be 1072800000. And `cast(cast('1970-01-01 00:00:00' as timestamp) as int)` is -28800. So the timestampdiff value is still 1072828800, the same as mysql.

**Comment by Ariznawlll** [comment]
Verified!
