### ISSUE TITLE
[Bug]: there are lots of Duplicate entry during sysbench mixed cases and tpcc  test on distributed mod 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11020]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 5e3bedf
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

When running sysbench mixed case in a common account on distributed mode for several hours, there are lots of the following error in new order txn:
DateTime : 2023-08-03 04:39:43
TxnName : update_pk
Statement : UPDATE sbtest10 SET k=k+100 WHERE id = 55131;
ErrorCode : 1062
ErrorMessage : Duplicate entry '55131' for key 'id'
Expected : false
DateTime : 2023-08-03 04:39:43
TxnName : update_pk
Statement : UPDATE sbtest10 SET k=k+100 WHERE id = 55131;
ErrorCode : 1062
ErrorMessage : Duplicate entry '55131' for key 'id'
Expected : false
^M
DateTime : 2023-08-03 04:48:22
TxnName : update_pk
Statement : UPDATE sbtest6 SET k=k+100 WHERE id = 97883;
ErrorCode : 1062
ErrorMessage : Duplicate entry '97883' for key 'id'
Expected : false
DateTime : 2023-08-03 04:48:22
TxnName : update_pk
Statement : UPDATE sbtest6 SET k=k+100 WHERE id = 97883;
ErrorCode : 1062
ErrorMessage : Duplicate entry '97883' for key 'id'
Expected : false
^M
DateTime : 2023-08-03 04:53:55
TxnName : update_pk
Statement : UPDATE sbtest7 SET k=k+100 WHERE id = 55560;
ErrorCode : 1062
ErrorMessage : Duplicate entry '55560' for key 'id'
Expected : false

the mo log can be get from loki by namesapce: mo-stb-20230803
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230803%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%20%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

<img width="1394" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/a6f27bd6-3133-4c88-9aef-c0739709ea94">

### Steps to Reproduce

```Markdown
1、RUN a mo cluster using the same config
2、Start Sysbench mix cases Long Running Test in a common account

for several hours
```

**Comment by aptend** [comment]
<img width="2375" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/d69a4995-847b-46a5-9152-7f4318ba81f4">

查到第一次 sbtest 中的 dup，并非在 commit 队列中做增量去重时出现的错误，而是在事务执行阶段，因此大概率是写入的数据问题，和 #11016 相同环境下出现的该问题

**Comment by aptend** [comment]
同 https://github.com/matrixorigin/matrixone/issues/11016

**Comment by aptend** [comment]
<img width="2381" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/8e30d96b-2551-455f-9182-fa634a761342">

一个现象：出现 dup 的事务 startts 和 刷盘完成时间非常非常接近。

新增了日志，打印出现 dup 时的删除插入数据以及当时的表 catalog，用于确定是否时间戳和block可见性。

**Comment by aptend** [comment]
复现中

**Comment by aptend** [comment]
已定位到 dn 报 dup 的原因

**Comment by aptend** [comment]
已定位到 dn 报 dup 的原因

**Comment by XuPeng-SH** [comment]
assign to @triump2020

**Comment by triump2020** [comment]
progress on

**Comment by aressu1985** [comment]
降级成s0，非crash/正确性/回归问题

**Comment by triump2020** [comment]
blocked by other S-1 issue

**Comment by aressu1985** [comment]
update on 8.21
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5919809938/job/16051821444

<img width="1432" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b633b5a6-b377-401e-ac44-6974b6b46b30">

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
reviewing relevant  code

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
与  #11024 类似

**Comment by triump2020** [comment]
tke 环境上取时间戳会取到大量的逻辑时钟不为 0 的值，所以时间戳我描述为 xx-y 的形式，y 是逻辑时间。dup 发生的一个路径是这样的:

1. 在 99-2 时刻，dn 完成了一次 compact，删除了 blk-1，新建了 blk-2，即该事务 commit ts 是 99-2
2. 一个 update 事务提交到 dn 来，事务的 start ts 也是 99-2。其携带的删除 rowid 来自于 blk-1，因为还处在 dn 的 workspace 阶段，没有任何 delete 的 transfer
3. 又因为该事务 start ts 也是 99-2，能看到新建 blk-2，于是插入数据行在 blk-2 上检查到了 duplicate key

**Comment by triump2020** [comment]
in testing ,  and wait for #11024 being fixed.

**Comment by triump2020** [comment]
waiting for #11024 being fixed.

**Comment by triump2020** [comment]
@aressu1985  duplicate, pls close it !

**Comment by triump2020** [comment]
duplicate
