### ISSUE TITLE
[Feature Request]: A gate for transactions

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11036]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
We need to implement a gate for transactions to prevent too many
transactions to overwhelm CN.
```

### Describe the feature you'd like

Each CN has a config, max active transactions.   4-8 x number of cores is a good default/starting number to use.

When a new txn begins, it check how many active transactions already in the system.   If reached max value, the
transaction is added to a FIFO queue.

**Comment by fengttt** [comment]
Related, #10992

**Comment by zhangxu19830126** [comment]
done

**Comment by zhangxu19830126** [comment]
done
