### ISSUE TITLE
[Bug]: mo crashed during bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11039]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1207" alt="企业微信截图_752776c2-c6f8-43da-b9bb-6b900c6786a4" src="https://github.com/matrixorigin/matrixone/assets/77312370/c5aff2da-cfde-4c4f-89f9-cfc52918d478">

https://github.com/matrixorigin/matrixone/actions/runs/5760845729/job/15617580916?pr=11014

### Expected Behavior

No Crash

**Comment by volgariver6** [comment]
fixed
