### ISSUE TITLE
[Feature Request]: Proxy should replay prepared stmt on connection migration

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#11045]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

Currently, prepared statement is not replayed on connection migration, so an error will be raised if client use the statement prepared before migration.

```
FATAL: mysql_stmt_execute() returned error 20400 (invalid state prepared statement '__mo_stmt_id_6' does not exist) for query 'SELECT c FROM sbtest6 WHERE id=?'
FATAL: `thread_run' function failed: .../Cellar/sysbench/1.0.20_4/share/sysbench/oltp_common.lua:419: SQL error, errno = 20400, state = 'HY000': invalid state prepared statement '__mo_stmt_id_6' does not exist
```

### Describe the feature you'd like

Proxy should track the prepared stmts of each session, replay them when migrate the connection to an new CN.

cc @fengttt  @domingozhang

**Comment by volgariver6** [comment]
done

**Comment by aylei** [comment]
verified, closing
