### ISSUE TITLE
[Subtask] Connector Management

### ISSUE THREAD

**Issue by gavinyue** [matrixorigin/matrixone#11046]
## Connector Management
Connector can be viewed as a pre-created pipeline. So its lifecycle management should follow the pipeline management in issue: https://github.com/matrixorigin/matrixone/issues/10975

Could consider using lib:  https://github.com/ricardo-ch/go-kafka-connect

**Comment by volgariver6** [comment]
done

**Comment by gavinyue** [comment]
already implemented as the daemon task
