### ISSUE TITLE
[Bug]: mo occasionally fails to start in ci

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11054]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/5769561465?pr=11052

<img width="1224" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/c35dbfac-2136-48f0-915b-b55d4975e2c3">

[mo-service.log](https://github.com/matrixorigin/matrixone/files/12266572/mo-service.log)

**Comment by w-zr** [comment]
Duplicate with https://github.com/matrixorigin/matrixone/issues/10750.

**Comment by w-zr** [comment]
Completed as #10750 closed.

**Comment by sukki37** [comment]
testing

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/6640600303/job/18041335258?pr=12346
[multi-cn-e2e-with-proxy-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13166367/multi-cn-e2e-with-proxy-linux-x86-reports.zip)

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/6626900331/job/18000742613?pr=12309

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/6691049557/job/18177526768?pr=12387

[multi-cn-e2e-with-proxy-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13204844/multi-cn-e2e-with-proxy-linux-x86-reports.zip)

**Comment by volgariver6** [comment]
I will take this one.
