### ISSUE TITLE
[Bug]: 'auto_increment_offset' dose not work

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#11056]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> SHOW VARIABLES LIKE 'auto_increment_offset';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| auto_increment_offset | 5     |
+-----------------------+-------+
1 row in set (0.00 sec)

mysql> show tables;
+---------------+
| Tables_in_aab |
+---------------+
| t1            |
| example_table |
| students      |
| names         |
| users         |
+---------------+
5 rows in set (0.01 sec)

mysql> drop table students;
Query OK, 0 rows affected (0.10 sec)

mysql> CREATE TABLE students (
    ->     id INT AUTO_INCREMENT PRIMARY KEY,
    ->     name VARCHAR(50) NOT NULL,
    ->     age INT
    -> );
Query OK, 0 rows affected (0.06 sec)

mysql> INSERT INTO students (name, age) VALUES ('Alice', 20);
INSERT INTO students (name, age) VALUES ('Bob', 22);
INSERT INTO students (name, age) VALUES ('Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO students (name, age) VALUES ('Bob', 22);
INSERT INTO students (name, age) VALUES ('Charlie', 19);Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO students (name, age) VALUES ('Charlie', 19);
Query OK, 1 row affected (0.00 sec)

mysql> select * from students;
+------+---------+------+
| id   | name    | age  |
+------+---------+------+
|    1 | Alice   |   20 |
|    2 | Bob     |   22 |
|    3 | Charlie |   19 |
+------+---------+------+
3 rows in set (0.01 sec)

**Comment by Ariznawlll** [comment]
Global configuration(This parameter is valid for different sessions):
<img width="872" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7b26fa37-5bf7-430c-bd2b-30be87978bfa">

Intra-session configuration(This parameter is valid only for the current session):
<img width="1036" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d5c506ff-9c6e-4d56-b067-d65eda1213da">

Test done!
