### ISSUE TITLE
[Bug]: multi cn bvt test ：cn panic

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11051]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d99bf4a13e9490f34c5516432900b0d81734f2e5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Unstable appear

<img width="1392" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e8a47cff-995b-411c-9039-e3bc4383b9b6">

https://github.com/matrixorigin/matrixone/actions/runs/5769081835/job/15640741122?pr=11047

[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/12266331/multi-cn-e2e-push-docker-compose-log.zip)

**Comment by badboynt1** [comment]
fixed

**Comment by Ariznawlll** [comment]
Verified！
