### ISSUE TITLE
[Bug]: solve network problems caused apt update to fail

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11066]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bcdafde0d4db3cb1db0460302332dc6385ec8a83
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1391" alt="企业微信截图_870c625e-acb0-49b3-8dc3-beda36ed42d6" src="https://github.com/matrixorigin/matrixone/assets/113406637/d2c6cf17-c393-494b-b83f-e50952fcaaa1">

**Comment by guguducken** [comment]
finished in https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5783064326, please check and close.

**Comment by heni02** [comment]
confirm，closed
