### ISSUE TITLE
[Bug]: new account's storage is 0.065 MiB, but after about 10 minute it downgrade to 0.022 MiB

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#11079]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-934be35f
- Hardware parameters:
- OS type:
- Others: 
```
come from https://github.com/matrixorigin/MO-Cloud/issues/1071

### Actual Behavior

as img show, new account's storage size changed from 0.065 MiB to 0.022 MiB
![image](https://github.com/matrixorigin/matrixone/assets/3927687/b0e4b382-e2da-4614-9294-5abf2cc121e2)

**Comment by Morranto** [comment]
no progress

**Comment by xzxiong** [comment]
> no progress

pls, what is the schedule? @Morranto

**Comment by Morranto** [comment]
im working on 10837 and and trying to fix some other bugs

**Comment by Morranto** [comment]
会看，但是不保证马上做，需要看 10837那边的改善情况

**Comment by Morranto** [comment]
im working on 10837

**Comment by Morranto** [comment]
分析中，应该跟后台任务有关

**Comment by Morranto** [comment]
这个行为似乎很正常，不知道这个字段原来的需求是什么，有什么差异

**Comment by xzxiong** [comment]
> 这个行为似乎很正常，不知道这个字段原来的需求是什么，有什么差异 @xzxiong

异常：新租户创建后，什么都不做，存储空间就变小了。

**Comment by Morranto** [comment]
持续了解后台行为中

**Comment by Morranto** [comment]
排查了一下，原因应该是这样的，目前取storage 的逻辑是取所有租户表的table size求和， 而table size函数是返回 memtable大小+s3存储大小（两者数据没有重叠）。

当创建新租户时，会在租户空间里创建catalog表，然后将一些数据插入，第一次查询时，此时绝大部分数据都是在内存（memtable）中， 第二次查询时，所有数据都被刷到S3上了，所以导致两次查询的结果不同

**Comment by xzxiong** [comment]
as discussed in wechat, PM accept the situation here.
