### ISSUE TITLE
"select 1 from t1" is not supported

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1108]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d3daff8d462c6c7eead4cc8e0fe85612e9094f7f
- Hardware parameters:
- OS type: linux
- Others:
```

### Actual Behavior

 select 1 from t1;
ERROR 1105 (HY000): unknown error:[42000]invalid projection '{{<nil>} 1 }'

### Expected Behavior

 select 1 from t1;
+---+
| 1 |
+---+
| 1 |
| 1 |
| 1 |
| 1 |
| 1 |
| 1 |
| 1 |
+---+

### Steps to Reproduce

```markdown
select 1 from t1;
+---+
| 1 |
+---+
| 1 |
| 1 |
| 1 |
| 1 |
| 1 |
| 1 |
| 1 |
+---+

select 1 from t1;
```

**Comment by JinHai-CN** [comment]
Won't support in v0.2.0.

**Comment by m-schen** [comment]
may be solved after plan refactoring. I will verify it after refactoring.

**Comment by daviszhen** [comment]
it was done

**Comment by domingozhang** [comment]
closed
