### ISSUE TITLE
[Bug]: Pessimistic + RC mode: tpcc 10 warehouse 50 terminal test failed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11085]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-aa83371
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1430" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/31036d7b-7a4d-44cc-9290-a7cd947fc4cc">

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5781627800/job/15668615081

**Comment by arjunsk** [comment]
Hi @triump2020 , I think this issue is related to this open  [issue](https://github.com/matrixorigin/matrixone/issues/10992). Could you kindly look into this, or reassign it to the appropriate person?

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by Ariznawlll** [comment]
[0809 nightly regression on eks test RC mode] https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5803704691/job/15733524356 
The question arose in 10 warehouses 10 terminals, 100 warehouses 100 terminals.

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by aressu1985** [comment]
duplicated with #11237 , and this can be closed and not s-1
