### ISSUE TITLE
[Enhancement]:  support mo_table_col_min for some special table

### ISSUE THREAD

**Issue by FelixSeptem** [matrixorigin/matrixone#11088]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
due to https://github.com/matrixorigin/matrixone/issues/10803#issuecomment-1659724169 mocloud hope to support these tables for `mo_table_col_min` and `mo_table_col_max` function
```

### Why is this needed ?

for mocloud display demand

**Comment by FelixSeptem** [comment]
cc @domingozhang

**Comment by YANGGMM** [comment]
mo_database mo_tables mo_columns  这三个系统表没有zonemap 来提供最大最小值的接口，无法实现这个功能
