### ISSUE TITLE
select statement failed because of column alias in group by clause

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1109]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d3daff8d462c6c7eead4cc8e0fe85612e9094f7f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 SELECT userID AS a, COUNT(*) AS cnt FROM t1 GROUP BY a;
ERROR 1105 (HY000): unknown error:[42000]unknown column 'a' in expr

### Expected Behavior

 SELECT userID AS a, COUNT(*) AS cnt FROM t1 GROUP BY a;
+------+-----+
| a    | cnt |
+------+-----+
|    1 |   3 |
|    2 |   1 |
|    3 |   1 |
|    6 |   1 |
|   11 |   1 |
+------+-----+
5 rows in set (0.01 sec)

**Comment by m-schen** [comment]
group by X, and X should check select list. But now we select column attribute, it is wrong.

**Comment by m-schen** [comment]
it has been solved now.
