### ISSUE TITLE
[Bug]: ut test TestContextDeadlineAndCancel fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#11101]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="382" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/1e651487-6d81-4ce0-a0d6-2004c803c8aa">

https://pipelines.actions.githubusercontent.com/serviceHosts/420d9c18-f10d-4e16-b77b-a3050f679cb1/_apis/pipelines/1/runs/162237/signedlogcontent/4?urlExpires=2023-08-08T10%3A43%3A14.8732843Z&urlSigningMethod=HMACV1&urlSignature=RkXYGVlQ1mmkIKvAqAjLk0XAeuM%2BnZYDQ5vW%2BE0dM2I%3D

**Comment by arjunsk** [comment]
Hi @xzxiong  Could you kindly look into this, or reassign it to the appropriate person?
