### ISSUE TITLE
[Bug]: regression on tke test: TPCH_100 performance degradation more than 25%.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11123]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 52a8f95efda02e1d7411895a6b9cd8fb107f1523
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

workflow URL：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5804224661/job/15733842906

<img width="1038" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/71a14c2d-8be9-4a29-b19c-5356cd439f02">

<img width="682" alt="企业微信截图_4aaf8461-3178-45a1-90ff-9518eb5ad368" src="https://github.com/matrixorigin/matrixone/assets/108530700/c25e9f3d-6f21-4433-86b4-a005105d1387">

**Comment by aunjgr** [comment]
@badboynt1 先确认一下

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/9f7ee8a9-be3d-42ec-89a6-28d686626c0b)

性能回复正常

**Comment by Ariznawlll** [comment]
Normal performance value.
