### ISSUE TITLE
[Bug]: merge run: cn CrashLoopBackOff 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11122]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):30ab6f6b7e8a92646139b9eed628b5acbd87839a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/matrixone/actions/runs/5795578525/job/15708741100
<img width="1351" alt="企业微信截图_95cd645e-ff18-40cc-bbbd-ab67e5d77c32" src="https://github.com/matrixorigin/matrixone/assets/113406637/e1ad20b7-361c-40b8-a85c-3f98cf9e28ed">

log:
http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-11094%5C%22,%20pod%3D%5C%22mo-checkin-regression-tp-cn-fh95r%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221691319527106%22,%22to%22:%221691492327106%22%7D%7D
<img width="1401" alt="企业微信截图_3010f85b-ea69-4ebf-9b64-b4a17ce1963e" src="https://github.com/matrixorigin/matrixone/assets/113406637/2ded70cc-5433-478a-82bf-330204f48656">

<img width="1408" alt="企业微信截图_3b712080-aee1-486b-bf8c-0b1952138e0c" src="https://github.com/matrixorigin/matrixone/assets/113406637/36a479e3-c85d-431d-954f-517f1181b44a">

**Comment by aunjgr** [comment]
@m-schen 你先看看？或者分给适合的人

**Comment by m-schen** [comment]
@gavinyue 这边看到是8月8号新增的功能，我不是很清楚这块的逻辑。麻烦检查一下，谢谢了。

**Comment by aressu1985** [comment]
fixed，merge run is ok
