### ISSUE TITLE
[Bug]: SQL failed when Expression in CREATE TABLE with DEFAULT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1112]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d3daff8d462c6c7eead4cc8e0fe85612e9094f7f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t_default_expr (
    i INT DEFAULT (1+2),
    c CHAR(4) DEFAULT 'ab',
    v VARCHAR(10) DEFAULT (CONCAT('(', c, ')')),
    f FLOAT DEFAULT (RAND() * RAND()),
    b BINARY(16) DEFAULT (UUID_TO_BIN(UUID()))
    );
ERROR 1105 (HY000): unknown error:[42611]Invalid default value for 'i'

### Expected Behavior

create table successfully in MYSQL

**Comment by iamlinjunhong** [comment]
Now support: default <binary expression>
eg:
CREATE TABLE t1 (i INT DEFAULT (1+2));

Not support: default <function call>
eg:
CREATE TABLE t2 (v VARCHAR(10) DEFAULT (CONCAT('(', c, ')'))

Fixed default <binary expression> for this issue.

**Comment by iamlinjunhong** [comment]
Now support: default \<binary expression\>
eg:
CREATE TABLE t1 (i INT DEFAULT (1+2));

Not support: default \<function call\>
eg:
CREATE TABLE t2 (v VARCHAR(10) DEFAULT (CONCAT('(', c, ')'))

Fixed default for this issue.

**Comment by iamlinjunhong** [comment]
Now support: default \<binary expression\>
eg:
CREATE TABLE t1 (i INT DEFAULT (1+2));

Not support: default \<function call\>
eg:
CREATE TABLE t2 (v VARCHAR(10) DEFAULT (CONCAT('(', c, ')'))

Fixed default \<binary expression\> for this issue.
