### ISSUE TITLE
[Bug]: point select query in tpch1t on eks 5 cn hang

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#11126]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

load tpch1t data on eks 5cn.
run sql: select count(*) from lineitem where l_orderkey=1;
it will hang for more than one hour.

find a suspicious goroutine:

goroutine 75034 [select]:
net/http.(*persistConn).roundTrip(0x424c6e0120, 0x4076048b00)
	/usr/local/go/src/net/http/transport.go:2638 +0x7d4
net/http.(*Transport).roundTrip(0x4000001cc0, 0x401b33c100)
	/usr/local/go/src/net/http/transport.go:603 +0x6b0
net/http.(*Transport).RoundTrip(0x6f7b78?, 0x2b93ba0?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x1c
net/http.send(0x401b33c100, {0x2b93ba0, 0x4000001cc0}, {0x69d84c?, 0x8?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x4d8
net/http.(*Client).send(0x4000f59e60, 0x401b33c100, {0x401f986360?, 0x10?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x98
net/http.(*Client).do(0x4000f59e60, 0x401b33c100)
	/usr/local/go/src/net/http/client.go:716 +0x6dc
net/http.(*Client).Do(0x0?, 0x0?)
	/usr/local/go/src/net/http/client.go:582 +0x1c
github.com/aws/smithy-go/transport/http.ClientHandler.Handle({{0xffff864b9a18?, 0x4000f59e60?}}, {0x2bb5d18, 0x418bafe060}, {0x27139c0?, 0x418a6ebe60?})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/transport/http/client.go:55 +0xa0
github.com/aws/smithy-go/middleware.deserializeWrapHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:190
github.com/aws/smithy-go/transport/http.(*RequestResponseLogger).HandleDeserialize(0x401b46c1b0, {0x2bb5d18, 0x418bafe060}, {{0x27139c0, 0x418a6ebe60}}, {0x2b94d20, 0x4025982680})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/transport/http/middleware_http_logging.go:58 +0x260
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/aws-sdk-go-v2/service/internal/checksum.(*validateOutputPayloadChecksum).HandleDeserialize(0x4023f1f2a0, {0x2bb5d18, 0x418bafe060}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f700?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.28/middleware_validate_output.go:64 +0x4c
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/aws-sdk-go-v2/aws/middleware.RecordResponseTiming.HandleDeserialize({}, {0x2bb5d18, 0x418bafe060}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f720?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/middleware/middleware.go:57 +0x58
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/aws-sdk-go-v2/service/s3.(*awsRestxml_deserializeOpGetObject).HandleDeserialize(0x401a8fe750?, {0x2bb5d18?, 0x418bafe060?}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f740?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/deserializers.go:5175 +0x44
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/aws-sdk-go-v2/service/internal/s3shared.(*metadataRetriever).HandleDeserialize(0x401a8fe750?, {0x2bb5d18?, 0x418bafe060?}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f760?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.14.2/metadata_retriever.go:31 +0x44
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/aws-sdk-go-v2/service/internal/s3shared.(*errorWrapper).HandleDeserialize(0x0?, {0x2bb5d18?, 0x418bafe060?}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f780?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.14.2/response_error_middleware.go:30 +0x40
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/smithy-go/transport/http.(*errorCloseResponseBodyMiddleware).HandleDeserialize(0x401a34a870?, {0x2bb5d18?, 0x418bafe060?}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f7a0?})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/transport/http/middleware_close_response_body.go:29 +0x40
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/aws-sdk-go-v2/aws/middleware.addRawResponse.HandleDeserialize({}, {0x2bb5d18?, 0x418bafe060?}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94c80?, 0x4023f1f7c0?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/middleware/middleware.go:154 +0x50
github.com/aws/smithy-go/middleware.decoratedDeserializeHandler.HandleDeserialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:206
github.com/aws/smithy-go/middleware.(*DeserializeStep).HandleMiddleware(0x404e432168?, {0x2bb5d18, 0x418bafe060}, {0x27139c0, 0x418a6ebe60}, {0x2b94da0, 0x4025982450})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_deserialize.go:120 +0x1c4
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.finalizeWrapHandler.HandleFinalize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_finalize.go:184
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*SignHTTPRequestMiddleware).HandleFinalize(0x418a6ebf50, {0x2bb5d18, 0x418a6ebf20}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94d40, 0x4025982570})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/signer/v4/middleware.go:315 +0x618
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*SignHTTPRequestMiddleware).HandleFinalize(0x413f4d18c0, {0x2bb5d18, 0x418a6ebf20}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94d40, 0x4025982570})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/internal/customizations/signer_wrapper.go:106 +0x278
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_finalize.go:200
github.com/aws/aws-sdk-go-v2/aws/retry.MetricsHeader.HandleFinalize({}, {0x2bb5d18, 0x418a6ebf20}, {{0x27139c0?, 0x418a6ebe60?}}, {0x2b94ca0, 0x4023f1f5e0})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/retry/middleware.go:283 +0x494
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_finalize.go:200
github.com/aws/aws-sdk-go-v2/aws/retry.(*Attempt).handleAttempt(0x4023f1f240, {0x2bb5d18, 0x418a6ebf20}, {{0x27139c0?, 0x418a6ebe60?}}, 0x285e420, {0x2b94ca0, 0x4023f1f620})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/retry/middleware.go:165 +0x484
github.com/aws/aws-sdk-go-v2/aws/retry.(*Attempt).HandleFinalize(0x4023f1f240, {0x2bb5d18, 0x418a6ebe30}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94ca0, 0x4023f1f620})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/retry/middleware.go:89 +0x1bc
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_finalize.go:200
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding.(*DisableGzip).HandleFinalize(0x404e432be8, {0x2bb5d18, 0x418a6ebe30}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94ca0, 0x4023f1f640})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.11/accept_encoding_gzip.go:67 +0x124
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_finalize.go:200
github.com/aws/smithy-go/middleware.(*FinalizeStep).HandleMiddleware(0x404e432d18?, {0x2bb5d18, 0x418a6ebe30}, {0x27139c0, 0x418a6ebb30}, {0x2b94cc0, 0x4023f1f300})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_finalize.go:114 +0x1c4
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.buildWrapHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:184
github.com/aws/aws-sdk-go-v2/aws/middleware.(*RecursionDetection).HandleBuild(0x404e432e01?, {0x2bb5d18, 0x418a6ebe30}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94c40, 0x4025982520})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/middleware/recursion_detection.go:46 +0x1ec
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.(*requestUserAgent).HandleBuild(0x4025982550?, {0x2bb5d18, 0x418a6ebe30}, {{0x27139c0, 0x418a6ebb30}}, {0x2b94c60, 0x4023f1f520})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/middleware/user_agent.go:219 +0x224
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*contentSHA256Header).HandleBuild(0x404e433008?, {0x2bb5d18, 0x418a6ebe30}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94c60, 0x4023f1f540})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/signer/v4/middleware.go:249 +0x190
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/signer/v4.(*computePayloadSHA256).HandleBuild(0x30?, {0x2bb5d18, 0x418a6ebce0}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94c60, 0x4023f1f560})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/signer/v4/middleware.go:200 +0x3f8
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:200
github.com/aws/smithy-go/transport/http.(*ComputeContentLength).HandleBuild(0x5c40936c8e8a8701?, {0x2bb5d18, 0x418a6ebce0}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94c60, 0x4023f1f580})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/transport/http/middleware_content_length.go:49 +0x118
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.ClientRequestID.HandleBuild({}, {0x2bb5d18, 0x418a6ebce0}, {{0x27139c0?, 0x418a6ebb30?}}, {0x2b94c60, 0x4023f1f5a0})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/middleware/middleware.go:42 +0x1a8
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:200
github.com/aws/smithy-go/middleware.(*BuildStep).HandleMiddleware(0x401ae31680?, {0x2bb5d18, 0x418a6ebce0}, {0x27139c0, 0x418a6ebb30}, {0x2b94cc0, 0x4023f1f320})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_build.go:114 +0x1c4
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.serializeWrapHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:192
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*removeBucketFromPathMiddleware).HandleSerialize(0x60?, {0x2bb5d18, 0x418a6ebce0}, {{0x23495e0?, 0x401a6529c0?}, {0x27139c0?, 0x418a6ebb30?}}, {0x2b94d80, 0x40259824c0})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/internal/customizations/remove_bucket_middleware.go:27 +0x154
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*updateEndpoint).HandleSerialize(0x4019a1d6e0, {0x2bb5d18, 0x418a6ebce0}, {{0x23495e0?, 0x401a6529c0?}, {0x27139c0?, 0x418a6ebb30?}}, {0x2b94d00, 0x4023f1f440})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/internal/customizations/update_endpoint.go:183 +0x2d0
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3.(*awsRestxml_serializeOpGetObject).HandleSerialize(0x1?, {0x2bb5d18, 0x418a6ebce0}, {{0x23495e0?, 0x401a6529c0?}, {0x27139c0?, 0x418a6ebb30?}}, {0x2b94d00, 0x4023f1f460})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/serializers.go:3318 +0x448
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*s3ObjectLambdaEndpoint).HandleSerialize(0x426556c380?, {0x2bb5d18?, 0x418a6ebce0?}, {{0x23495e0?, 0x401a6529c0?}, {0x27139c0?, 0x418a6ebb30?}}, {0x2b94d00?, 0x4023f1f480?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/internal/customizations/s3_object_lambda.go:34 +0x544
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations.(*processARNResource).HandleSerialize(0x401ba7c120, {0x2bb5d18, 0x418a6ebce0}, {{0x23495e0?, 0x401a6529c0?}, {0x27139c0?, 0x418a6ebb30?}}, {0x2b94d00, 0x4023f1f4a0})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/internal/customizations/process_arn_resource.go:56 +0xd48
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/s3.(*ResolveEndpoint).HandleSerialize(0x401b627270, {0x2bb5d18, 0x418a6ebb00}, {{0x23495e0?, 0x401a6529c0?}, {0x27139c0?, 0x418a6ebb30?}}, {0x2b94d00, 0x4023f1f4c0})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/endpoints.go:116 +0x44c
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:208
github.com/aws/smithy-go/middleware.(*SerializeStep).HandleMiddleware(0x40259823e0, {0x2bb5d18, 0x418a6ebb00}, {0x23495e0, 0x401a6529c0}, {0x2b94cc0, 0x4023f1f340})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_serialize.go:122 +0x1ec
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.initializeWrapHandler.HandleInitialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:184
github.com/aws/aws-sdk-go-v2/service/s3.(*validateOpGetObject).HandleInitialize(0x30?, {0x2bb5d18, 0x418a6ebb00}, {{0x23495e0?, 0x401a6529c0?}}, {0x2b94d60, 0x4025982470})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/validators.go:910 +0xb8
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*setLogger).HandleInitialize(0x404e434888?, {0x2bb5d18?, 0x418a6ebad0?}, {{0x23495e0?, 0x401a6529c0?}}, {0x2b94ce0, 0x4023f1f3a0})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/logging.go:45 +0x8c
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.RegisterServiceMetadata.HandleInitialize({{0x2b7d24a, 0x2}, {0x275b2bc, 0x2}, {0x40004bfe80, 0x9}, {0x2761ab9, 0x9}}, {0x2bb5d18?, 0x418a6eb770?}, ...)
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.18.0/aws/middleware/metadata.go:40 +0x1e0
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/service/internal/checksum.(*setupOutputContext).HandleInitialize(0x0?, {0x2bb5d18?, 0x418a6eb770?}, {{0x23495e0?, 0x401a6529c0?}}, {0x2b94ce0?, 0x4023f1f3e0?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.28/middleware_setup_context.go:95 +0xd0
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/service/internal/s3shared.(*ARNLookup).HandleInitialize(0x404e434c18?, {0x2bb5d18, 0x418a6eb770}, {{0x23495e0?, 0x401a6529c0?}}, {0x2b94ce0, 0x4023f1f400})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.14.2/arn_lookup.go:39 +0x1c0
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*InitializeStep).HandleMiddleware(0x404e434d28?, {0x2bb5d18, 0x418a6eb770}, {0x23495e0, 0x401a6529c0}, {0x2b94cc0, 0x4023f1f360})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/step_initialize.go:114 +0x1c4
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.(*Stack).HandleMiddleware(0x404e434e28?, {0x2bb5d18, 0x418a6eb770}, {0x23495e0, 0x401a6529c0}, {0x2b94da0?, 0x4025982450?})
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/stack.go:109 +0x130
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/go/pkg/mod/github.com/aws/smithy-go@v1.13.5/middleware/middleware.go:57
github.com/aws/aws-sdk-go-v2/service/s3.(*Client).invokeOperation(0x40000e6840, {0x2bb5d18?, 0x418a6eb710?}, {0x2761ab9, 0x9}, {0x23495e0, 0x401a6529c0}, {0x0, 0x0, 0x421648?}, ...)
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/api_client.go:237 +0x4cc
github.com/aws/aws-sdk-go-v2/service/s3.(*Client).GetObject(0x2000?, {0x2bb5d18?, 0x418a6eb710?}, 0x421648?, {0x0?, 0x40269ff9e0?, 0x404e4356f8?})
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/s3@v1.33.1/api_op_GetObject.go:114 +0xc0
github.com/matrixorigin/matrixone/pkg/fileservice.(*S3FS).s3GetObject.func3.1()
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/s3_fs.go:1160 +0x3c
github.com/matrixorigin/matrixone/pkg/fileservice.doWithRetry[...]({0x2769c09?, 0xd}, 0x404e435918, 0x2, 0x285fd60?)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/retry.go:30 +0x54
github.com/matrixorigin/matrixone/pkg/fileservice.(*S3FS).s3GetObject.func3(0x404e435998?)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/s3_fs.go:1157 +0x204
github.com/matrixorigin/matrixone/pkg/fileservice.newRetryableReader(0x401b627090, 0x12a4090, 0x285fd60)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/retryable_reader.go:33 +0x34
github.com/matrixorigin/matrixone/pkg/fileservice.(*S3FS).s3GetObject(0x4000f0eee0, {0x2bb5d18?, 0x418a6eb710}, 0x40000a4070?, 0x12a6ea9, 0x401a6529c0, {0x0, 0x0, 0x0})
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/s3_fs.go:1148 +0x174
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230628075727-26c9a2fd5fb8/application.go:336 +0x35c

cancel this query, will get this error in log:
{"level":"ERROR","time":"2023/08/09 07:38:43.513617 +0000","caller":"frontend/util.go:552","msg":"query trace status","connection_id":122,"statement":"select count(*) from lineitem where l_orderkey=1","status":"fail","error":"operation error S3: GetObject, https response error StatusCode: 0, RequestID: , HostID: , canceled, context canceled","span":{"trace_id":"cc584059-3683-11ee-82d0-ba3e2b1336f8","kind":"statement"},"session_info":"connectionId 122|127.0.0.1:52696|{account sys::moadmin -- 0:1:0}|goRoutineId 75034|77ca4ea4-3683-11ee-82d0-ba3e2b1336f8","session_id":"122","statement_id":"\ufffdX@Y6\ufffd\u0011\ufffd\ufffdк>+\u00136\ufffd"}

it seems that this query hangs on accessing s3 objects.

**Comment by badboynt1** [comment]
when metadata cache size set to 4g, this query will not hang. need to fix this.

**Comment by w-zr** [comment]
Will work on this after #10750

**Comment by aressu1985** [comment]
@aressu1985 先测试一下看看还存不存在

**Comment by aressu1985** [comment]
fixed
