### ISSUE TITLE
[Bug]: regression on tke：oltp test delete performance degradation more than 25%.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11136]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 333367ff6ea786177a8058770ee6dc71469441ef
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5807886217/job/15758239129

<img width="916" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2f02b343-b0eb-4277-96ba-a7f89e1eac3d">

<img width="633" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/005580f9-b0e1-4465-bea8-a7b9753d4f0c">

**Comment by DanielZhangQD** [comment]
@ouyuanning Please help check this issue.

**Comment by ouyuanning** [comment]
根据QA提供的两个commit id。在本地未复现。
本地来看，新的commit id性能反而会稍好一些

**Comment by ouyuanning** [comment]
daily run也没有复现。估计是抖动问题

**Comment by ouyuanning** [comment]
daily run也没有复现，建议可关闭。待复现再打开

**Comment by aressu1985** [comment]
track by issue #11237 ,this closed
