### ISSUE TITLE
[Bug]: 最新MO执行TPCH过慢

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#11130]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):aliyun: nightly-2304a852 , AWS: nightly-dea31688
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

云环境执行TPCH过慢，有些语句打到了十几秒。
1. 复制TPCH语句，使用TPCH10，执行TPCH测试语句。
2. 结果如下
ALIYUN：
<img width="1573" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/8ca76c29-504c-4fbd-8006-36169b4dff12">
AWS：
<img width="1583" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/84655823-7980-4887-8890-8f0f15dc5e6c">

### Expected Behavior

之前上海阿里云执行结果如下：
![image](https://github.com/matrixorigin/matrixone/assets/130344965/64a02976-7017-4f22-8deb-1cbc8d34a3bc)

### Steps to Reproduce

```Markdown
As Actual
```

**Comment by aunjgr** [comment]
dup to #11123

**Comment by DanielZhangQD** [comment]
@badboynt1 Please also help investigate this issue, it seems a different issue with #11123 since it's for TPCH_10 and the performance drop is much larger.

**Comment by badboynt1** [comment]
issue里给的commitid太老了，麻烦用最新的mo测试一下

**Comment by xiaoshuwei** [comment]
Processon

**Comment by xiaoshuwei** [comment]
目前速度仍然不及预期
<img width="1582" alt="企业微信截图_96c005f6-6da1-40a0-8b44-a6f3afba3f11" src="https://github.com/matrixorigin/matrixone/assets/130344965/ee9f1d1d-f1c1-4bb9-a3f0-5de01e6df6d5">

**Comment by sukki37** [comment]
> 目前速度仍然不及预期 <img alt="企业微信截图_96c005f6-6da1-40a0-8b44-a6f3afba3f11" width="1582" src="https://user-images.githubusercontent.com/130344965/261212864-ee9f1d1d-f1c1-4bb9-a3f0-5de01e6df6d5.png">

麻烦补充commitid，集群节点配置

**Comment by badboynt1** [comment]
目前怀疑是现在的核数和以前的核数不一样。 以前跑tpch10g q21能跑到440ms，至少是给了64核左右。 现在只有12核左右。 希望能明确一下以前的配置

**Comment by badboynt1** [comment]
目前的性能符合预期。 以前的性能可能是错误load了1g数据，或者给的核数特别多。
