### ISSUE TITLE
[Bug]: load data on eks regression test performance degradation more than 25%.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11140]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8af14455f059e657890f4249ca63699476bb7f63
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="446" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b81563bd-d97e-472d-acde-85a49b311371">

<img width="831" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ab77a3c7-5969-48d8-abf9-d5361ec58528">

**Comment by Ariznawlll** [comment]
binary search：
<img width="221" alt="企业微信截图_32c36e4e-bdf9-4fb2-b1e2-460548c33126" src="https://github.com/matrixorigin/matrixone/assets/108530700/994123b2-9515-4f2a-9fce-0065d2e31f70">

commitId：c17cd63e417f2c01681acde5851dc26d03112dae

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by aressu1985** [comment]
related to issue #11310 , and this can be closed
