### ISSUE TITLE
[Bug]: Storage Compatibility regression：lost connection during loading ssb data.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11151]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8af14455f059e657890f4249ca63699476bb7f63
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**MO Storage Compatibility regression test on eks: cn crashed**
job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5804293192/job/15734041256
<img width="684" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/de092ec5-88ba-49a4-8376-8e9fc397dc5b">
Load TPCH 10G失败，根据时间推断与cn重启有关
<img width="1029" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/639f8815-7f58-491b-b517-c3d02f7f3a5f">
Sysbench测试失败，根据时间推断与cn重启有关
<img width="1030" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9f58fbc7-2a18-4712-9797-0fb6751151b7">

<img width="1315" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c4a6b52d-5365-4339-acbe-6545b832f6ac">

log:http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cpt%5C%22,%20pod%3D%5C%22cpt-tp-cn-s2xqn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D

memory use：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1691549524308&to=1691551524238&var-datasource=Prometheus&var-cluster=&var-namespace=mo-cpt

初步定位与cn重启有关，具体原因还需进一步定位。

**Comment by Ariznawlll** [comment]
0811:Storage Compatibility regression：
<img width="1011" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8c429ecd-211d-4e32-ad06-b0e726566153">

**Comment by aunjgr** [comment]
现在还能复现吗？

**Comment by aunjgr** [comment]
未复现

**Comment by aunjgr** [comment]
未复现
