### ISSUE TITLE
[Bug]:  some panic errors  not expected

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11158]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):97ac52b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

stabiliby regression test which include tpcc/tpch/sysbench long time running, and founded mo log more panic error, it is not expected. 
panic error log:http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230810%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221691634672843%22,%22to%22:%221691721072843%22%7D%7D
<img width="1182" alt="企业微信截图_e68ac0fc-240f-491d-b52f-720c462e0cc0" src="https://github.com/matrixorigin/matrixone/assets/113406637/c9150379-fcdf-4c3b-8d01-7d5f14f46cc3">
<img width="1323" alt="企业微信截图_c972d902-f0c5-45c7-bc2b-7c0777fab11e" src="https://github.com/matrixorigin/matrixone/assets/113406637/d1ae5fe3-e151-4e1d-b391-b0f1f286f4d8">
<img width="1306" alt="企业微信截图_c9b4cca2-1214-418c-81c7-f17c18632284" src="https://github.com/matrixorigin/matrixone/assets/113406637/acac2ee8-c26b-4e9c-93c7-c3ca2178d6e3">
<img width="1309" alt="企业微信截图_df487389-85c1-4136-97d1-c92cbf8fc332" src="https://github.com/matrixorigin/matrixone/assets/113406637/6f5bd206-975a-436e-b2af-46df711ccf6c">

**Comment by heni02** [comment]
@nnsgmsone plz confirm ,thank you

**Comment by nnsgmsone** [comment]
我会负责分析并且建立具体的issue

**Comment by nnsgmsone** [comment]
我会负责分析并且建立具体的issue

**Comment by nnsgmsone** [comment]
@ouyuanning 远宁大哥帮忙弄个同事定位一下把。。

**Comment by nnsgmsone** [comment]
处理ddail run的问题中，还未处理.

**Comment by nnsgmsone** [comment]
编写pipeline重构文档中，还未处理。

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
尚未处理

**Comment by nnsgmsone** [comment]
这个问题是这样，目前mo会捕获所有的异常，并不会挂掉。然后捕获的异常都是error日志，error日志，mo的日志就是会打印堆栈。。那个越界的问题应该是没了。。不过这个行为目前是这样的，如果需要修改对于异常处理的问题，可能需要讨论。 @heni02

**Comment by heni02** [comment]
如果是预期，暂时不影响其他功能，先关闭
