### ISSUE TITLE
[Feature Request]: Move kill session action to CN when dropping an account

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#11152]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

bvt 120000ms not return

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/5820567122/job/15781192997
```

**Comment by sukki37** [comment]
All hung issues happened in proxy mode, @volgariver6 please assist in identifying the issue. Thank you!

**Comment by sukki37** [comment]
Other repros:

https://github.com/matrixorigin/matrixone/actions/runs/5819496725/job/15778005704 https://github.com/matrixorigin/matrixone/actions/runs/5822133750/job/15786094628

**Comment by sukki37** [comment]
@volgariver6 will fix it in two days. And considering the low probability of encountering the problem associated with this issue in real-world scenarios, and the availability of a workaround through configuration file adjustments, as discussed with @domingozhang it is reasonable to downgrade it to priority level S0.

**Comment by domingozhang** [comment]
transfer to p0 as a featrue

**Comment by volgariver6** [comment]
PR merged, and it is OK to test.

**Comment by heni02** [comment]
proxy mode test /Users/heni/matrixone/test/distributed/cases/database/config.sql
run 20 times all succeed,no connection timeout occurred
<img width="980" alt="WeChatWorkScreenshot_7be005e1-bbbc-486a-a50e-81a914d0c720" src="https://github.com/matrixorigin/matrixone/assets/113406637/325288db-2a53-499a-a1b8-2e557b113c4b">
