### ISSUE TITLE
[Bug]: eks rc：lock table not found on remote lock service.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11160]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6631a987b38374e7c1c5e5ad3922c41dc7a6c2e3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1042" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fcabb0dc-b918-48ac-9239-e7c4579752cd">

job ：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5823984229/job/15796499663

<img width="972" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/563bebfb-6960-4d53-9ad9-2258dc8e66f2">

log：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

根据时间判断与cn重启无关，需要进一步定位

**Comment by zhangxu19830126** [comment]
it's not a bug. Because in tpcc 100-100, cn oom killed. So this error is right.

**Comment by Ariznawlll** [comment]
Migrate to tke.
