### ISSUE TITLE
[Bug]:  eks regression：Communications link failure in sysbench oltp delete 500 thread.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11167]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3b1b43e5aa56dce79bed8a9d9413b386dc9d9636
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5823409982/job/15794619976
<img width="1389" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c4355fdd-be82-4957-ab7f-0bf4a36c3ae5">

<img width="974" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/44b2233a-af35-471c-b9a7-7746b0d03bc0">

<img width="969" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/76f20d7f-75a1-4328-be8e-4a8823c7c81b">

log：http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D

无法根据pod重启时间以及发生communication link failure时间确定原因，需要进一步定位。

**Comment by daviszhen** [comment]
从后面的推断。cn pod重启的时间点为18:00。与上图中的19:36 不一致。因此，不是pod重启导致的。

<img width="1616" alt="企业微信截图_cf89d2e4-6814-4872-8572-877521b26fe2" src="https://github.com/matrixorigin/matrixone/assets/60595215/65e7269a-52e1-4b8e-b6d6-24e75345d34d">

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/487a27bc-c76f-414a-a3e3-260b6b5b39ff)

**Comment by daviszhen** [comment]
从报错的情况看。网络拥塞的可能性比较大。
1，收到语句后，执行了。也响应了。但是客户端超时没收到结果。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/06832efb-87fb-4de2-8baa-2a26406f7c84)



![image](https://github.com/matrixorigin/matrixone/assets/60595215/6834bc5a-d798-4e68-a30b-b7fb2853ea3e)

2， 有些报错无法确定mo是否收到。

现在INFO不打印接受到的sql语句了。无法判断。

```
2023-08-10 19:36:12 ERROR TransExecutor:247 - DateTime : 2023-08-10 07:36:12
TxnName : delete_pk_10_100000
Statement : delete from sbtest4 where id = 39305;
ErrorCode : 0
ErrorMessage : Communications link failure
```

**Comment by daviszhen** [comment]
看能不能复现了。

或者延长测试工具的超时时间。

**Comment by aronchanisme** [comment]
As per discussed, this might be due to client side timeout, and it does not show up in recent regresstion test. Need some observerations to see if it comes up again. Please kindly help take a look. @aressu1985

**Comment by aressu1985** [comment]
this can be close, and tracked by another issue #11237
