### ISSUE TITLE
[Bug]: tke rc：TPCH_100 load data failed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11187]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e67b7b4d88a7f2e15b127441e7c6d9466e5e932d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5837395888/job/15833304161
<img width="993" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6f6710bf-fc35-4ef7-8abc-59684b9faf56">

<img width="879" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d88340f9-dbaf-4bba-b200-214b43aaa67c">

根据convert error判断，不是mo内部报错，具体原因需要进一步分析。

log:http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-rc-20230811%5C%22%7D%20%7C%3D%20%60into%20table%20tpch_100g.part%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

**Comment by daviszhen** [comment]
@YANGGMM 协助看下

**Comment by aressu1985** [comment]
add another case:
job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5848298567/job/15862506115

<img width="1372" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/798b81ee-05d8-414c-9d1e-049de6d1c69e">

**Comment by gavinyue** [comment]
Looking into it tomorrow.

**Comment by YANGGMM** [comment]
not working

**Comment by aressu1985** [comment]
update on 8.21
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5919809938/job/16050681125

<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/64a7f0a2-2430-44fb-ae8b-13f9849bb70f">

**Comment by YANGGMM** [comment]
still working on it

**Comment by daviszhen** [comment]
还没改完

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by aressu1985** [comment]
没有在复现，暂时关闭，等出现了在重新定位
