### ISSUE TITLE
 Fix escaped char for <like expression>

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#1118]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Expected Behavior

In parser:
select * from t where a like '\\\\%';

parse result:
select * from t where a like '\\%';

**Comment by m-schen** [comment]
it is done.
