### ISSUE TITLE
[Bug]: internal error: cn service is not ready, retry later

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#11180]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/112734932/db19b8ac-fbf2-4fe2-b2f6-a9c55ae66791)

running tpch1t for a long time, and then failed with errors.

it's not oom, mo process is still there. some errors in log:

{"level":"INFO","time":"2023/08/12 10:16:56.370511 +0800","name":"log-service.txn","caller":"client/client.go:454","msg":"txn client status changed to paused","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"INFO","time":"2023/08/12 10:16:56.370539 +0800","caller":"disttae/logtailPushModel.go:362","msg":"[log-tail-push-client] clean finished, start to reconnect to dn log tail service"}
{"level":"ERROR","time":"2023/08/12 10:16:56.370648 +0800","caller":"client/client.go:401","msg":"error: internal error: cn service is not ready, retry later"}
{"level":"ERROR","time":"2023/08/12 10:16:56.370688 +0800","caller":"frontend/util.go:552","msg":"Failed to get transaction","error":"internal error: cn service is not ready, retry later","session_info":"connectionId 7689|127.0.0.1:42950|{account sys:7707b025-4af6-4eda-b433-a5163dd677f1:moadmin -- 0:4294967295:0}|goRoutineId 282897|39c3fc50-38b6-11ee-822f-b07b25f84010","session_id":"9\ufffd\ufffdP8\ufffd\u0011\ufffd\ufffd/\ufffd{%\ufffd@\u0010"}
{"level":"ERROR","time":"2023/08/12 10:16:56.370713 +0800","caller":"frontend/util.go:552","msg":"internal error: cn service is not ready, retry later","session_info":"connectionId 7689|127.0.0.1:42950|{account sys:7707b025-4af6-4eda-b433-a5163dd677f1:moadmin -- 0:4294967295:0}|goRoutineId 282897|39c3fc50-38b6-11ee-822f-b07b25f84010","session_id":"9\ufffd\ufffdP8\ufffd\u0011\ufffd\ufffd/\ufffd{%\ufffd@\u0010"}

**Comment by badboynt1** [comment]
[error.log](https://github.com/matrixorigin/matrixone/files/12326290/error.log)

full log here

**Comment by DanielZhangQD** [comment]
<img width="1504" alt="企业微信截图_64988c5a-542f-4005-913d-c3527bb1efc1" src="https://github.com/matrixorigin/matrixone/assets/36026334/147bce6d-3888-4bcc-8231-07c93a097f68">
@volgariver6 PTAL this issue first, thanks!

**Comment by volgariver6** [comment]
close it for now util we get anthoer hit.
