### ISSUE TITLE
[Bug]: dn	 panic: runtime error: index out of range [0] with length 0 during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11197]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6a5db18
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

When running stability test in a common account on distributed mode for several hours, dn panic by :
panic: runtime error: index out of range [0] with length 0
<img width="1393" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7c1b5e93-9e81-4783-8ab9-d7a8bec730d3">

the mo log from loki:
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stb-20230813%5C%22,%20pod%3D%5C%22nightly-regression-dis-dn-0%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221691904467928%22,%22to%22:%221691904470163%22%7D%7D

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5845444575

### Steps to Reproduce

```Markdown
1、RUN a mo cluster using the same config
2、Start Sysbench mix cases Long Running Test in a common account
3、Start TPCH 100G Long Running Test in a common account
4、Start TPCC 100-100 Long Running Test in a common account
for several hours
```

**Comment by triump2020** [comment]
Root cause is that  the batch passed by CN  has no `attrs` .

**Comment by nnsgmsone** [comment]
那个attribute name是没有的，只有列值。。那个名字有需要吗。。pipeline用的只是col_pos。 @triump2020

**Comment by triump2020** [comment]
@aressu1985  Pls test.

**Comment by aressu1985** [comment]
fixed
