### ISSUE TITLE
[Bug]: convert to the system variable type failed, bad value 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11190]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2023/08/10 19:36:45.936527 +0000","caller":"frontend/session.go:1149","msg":"error: internal error: convert to the system variable type failed, bad value %!s(int64=0)","span":{"trace_id":"bc6f46a6-cca0-9fd4-997b-d95e20d246ae","span_id":"31fcb36d528e95f8"}}
{"level":"ERROR","time":"2023/08/10 19:36:45.936507 +0000","caller":"frontend/session.go:1149","msg":"error: internal error: convert to the system variable type failed, bad value %!s(int64=0)"}
{"level":"ERROR","time":"2023/08/10 19:36:45.936412 +0000","caller":"frontend/session.go:1148","msg":"error: internal error: convert to the system variable int type failed","span":{"trace_id":"bc6f46a6-cca0-9fd4-997b-d95e20d246ae","span_id":"31fcb36d528e95f8"}}
{"level":"ERROR","time":"2023/08/10 19:36:44.583984 +0000","caller":"frontend/util.go:549","msg":"query trace status","connection_id":7035,"statement":"delete from sbtest4 where id = 38826","status":"fail","error":"w-w conflict","span":{"trace_id":"edf711cf-37b4-11ee-8939-ee6a4f0747d5","kind":"statement"},"session_info":"connectionId 7035|10.0.102.236:46916|

### Steps to Reproduce

```Markdown
http://a58ec25c4c81b42b4bc11f9a4eb1f54e-1422586515.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22b08c0b34-9dfc-47c9-ac7b-b1dd15d38191%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D
```

**Comment by YANGGMM** [comment]
have solved in https://github.com/matrixorigin/matrixone/pull/11170

**Comment by daviszhen** [comment]
it was fixed.
