### ISSUE TITLE
[Bug]: the result of alter table modify primary column is incorrent.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b6665f22c520234118df26776c60d4f9f3b4cdc9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1372" alt="企业微信截图_f379401a-bd95-4803-97af-bee58773e84c" src="https://github.com/matrixorigin/matrixone/assets/108530700/94d45b2c-dd71-4e1c-b074-b4d118b75acc">

### Steps to Reproduce

```Markdown
drop table if exists primary04;
create table primary04(col1 int primary key ,col2 varbinary(20));
insert into primary04 values (1, 'qfreqvreq');
insert into primary04 values (2, '324543##');
alter table primary04 modify col1 float;
show create table primary04;
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @aronchanisme @daviszhen
