### ISSUE TITLE
[Bug]: bvt failed in some authentication cases sometimes

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11219]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/5858672165/job/15883085200

[multi-cn-e2e-with-proxy-linux-x86-reports (1).zip](https://github.com/matrixorigin/matrixone/files/12340688/multi-cn-e2e-with-proxy-linux-x86-reports.1.zip)

<img width="1015" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/3c4e73e3-461a-41bd-9ee4-84551b3719e5">

**Comment by sukki37** [comment]
maybe related to configurations, bvt passed after I modified launch-with-proxy.

before:

**Comment by YANGGMM** [comment]
wait pr merge
