### ISSUE TITLE
[Bug]: Pessimistic mode：drop primary key,  then commit,  insert into table failed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11213]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3194798c98fd5775a5f2b3b66457757bea9595db
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

not wait for lock

### Steps to Reproduce

```Markdown
drop table if exists alter01;
create table alter01(col1 int not null ,col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");
begin;
alter table alter01 modify col1 float;
-- @session:id=1{
-- @wait:0:commit
use transaction_enhance;
insert into alter01 values (8,"h");
select * from alter01;
-- @session
insert into alter01 values (6,"h");
commit;
select * from alter01;
```

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
same as https://github.com/matrixorigin/matrixone/issues/11217

**Comment by Ariznawlll** [comment]
drop table if exists rename01;
create table rename01 (c int primary key,d int);
insert into rename01 values(1,1);
insert into rename01 values(2,2);
begin;
insert into rename01 values(3,1);
insert into rename01 values(4,2);
alter table rename01 rename column c to `newCCCC`;
select * from rename01;
-- @session:id=1{
use isolation;
-- @wait:0:commit
insert into rename01 (c, d) values (5,7);
insert into rename01 (newCCCC, d) values (5,7);
select * from rename01;
-- @session}
select * from rename01;
drop table rename01;

**Comment by qingxinhome** [comment]
Processing

**Comment by qingxinhome** [comment]
Currently, in MO, if a table does not have a primary key defined, it is not locked in real transactions @Ariznawlll @domingozhang @ouyuanning

**Comment by qingxinhome** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
same as #11217

**Comment by ouyuanning** [comment]
待11217合并。应该是同样的问题

**Comment by ouyuanning** [comment]
待11217合并再检查看看

**Comment by Ariznawlll** [comment]
drop table if exists alter01;
create table alter01(col1 int primary key,col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");
begin;
alter table alter01 drop primary key;
-- @session:id=1{
-- @wait:0:commit
use transaction_enhance;
insert into alter01 values (5,"h");
select * from alter01;
-- @session
insert into alter01 values (6,"h");
select * from alter01;
drop table alter01;

Actual behavior:
<img width="1179" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fe8baa26-d335-41a5-bb31-6ab255e7f151">

Expect behavior:
session 1: alter table drop primary key, session 2: insert into alter01 values (5,"h"), session1: commit, session2: insert into alter01 values (5,"h") execute success!

**Comment by ouyuanning** [comment]
session 2等到session 1 free lock之后。并没有执行retry，因为去重的错误覆盖掉 retry 的错误了。于是没有进入retry流程。
下周修

**Comment by ouyuanning** [comment]
还没时间看

**Comment by jensenojs** [comment]
相关pr已合入

**Comment by Ariznawlll** [comment]
verified!
