### ISSUE TITLE
[Bug]: insert failed during running bvt against mo in pessimistic mode 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11217]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0ab56448
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1071" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/b7cc6fb4-01da-430a-bf5c-897531085548">

https://github.com/matrixorigin/matrixone/actions/runs/5857397767/job/15879175113#logs

[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12337289/1-cn-e2e-linux-x86-reports.zip)

**Comment by qingxinhome** [comment]
这个issue在本地没有复现，从代码上看，alter table操作都显式的加了lock，这个没有异议，至于为什么在表被锁住的情况下，另一个会话为什么仍然可以insert表，目前我没有头绪. @sukki37 @zhangxu19830126 @ouyuanning

**Comment by qingxinhome** [comment]
定位中

**Comment by qingxinhome** [comment]
悲观事务下表锁住之后，另一个session在访问该表时要阻塞的，但是事实上，并没有阻塞，本地多次测试是正常的，是一个非必现的错误，但是我这边不了解悲观事务锁相关的设计，这个问题可能需要交旭哥看一下 @sukki37 @zhangxu19830126

**Comment by ouyuanning** [comment]
张旭休假中。等他回来处理吧

**Comment by ouyuanning** [comment]
获取最新表结构的部分基本完成了。预计明天提PR

**Comment by ouyuanning** [comment]
PR review中

**Comment by ouyuanning** [comment]
PR 待合并

**Comment by ouyuanning** [comment]
新PR合并后。有些逻辑要修改。下周一处理

**Comment by ouyuanning** [comment]
PR已合并。辛苦QA协助验证

**Comment by ouyuanning** [comment]
PR revert了。有一些偶发的问题待定位

**Comment by ouyuanning** [comment]
明天再跟proxy这边了解一下。

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
今天主要在路上。没时间看

**Comment by ouyuanning** [comment]
not working on this today

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
今天跟莫尘、刘博讨论了一下。明天根据讨论的建议，打一些log跑一跑看看。

**Comment by ouyuanning** [comment]
从今天打的日志来看。commit的时间间隔似乎没有等了5秒。
明天再跟大家确认下。

**Comment by ouyuanning** [comment]
估计跟#11334存在类似问题

**Comment by ouyuanning** [comment]
今天没时间看

**Comment by ouyuanning** [comment]
PR待合并

**Comment by ouyuanning** [comment]
PR待合并

**Comment by ouyuanning** [comment]
PR待合并

**Comment by ouyuanning** [comment]
PR待合并

**Comment by ouyuanning** [comment]
PR已合并，辛苦 @heni02  帮忙验证

**Comment by Ariznawlll** [comment]
I have removed bvt tag, and I will continue to pay attention to ci to see if the problems occasionally occurred before will occur again.

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/pull/11777

**Comment by Ariznawlll** [comment]
This issue does not appear in pr for the time being..i'll keep watching it.

**Comment by Ariznawlll** [comment]
This issue does not appear in pr for the time being..i'll keep watching it.
