### ISSUE TITLE
[Bug]: INSERT failed when value with reference of previous columns 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1121]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 33ae31aa37c16f32cc881d6f6c214e750351b78b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 create table t2(a int,b int);
 insert into t2 values(1, a*2);
ERROR 1105 (HY000): unknown error:[42000]'' is not support now

**Comment by JinHai-CN** [comment]
Won't support this function in v0.2.0.
