### ISSUE TITLE
[Bug]: Run  tpch10 sql cn oom(aliyun)

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#11225]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

env: aliyun
cn configmap: 
[cn.md](https://github.com/matrixorigin/matrixone/files/12341922/cn.md)

test case: tpch10 22 sql

tpch log:
[mo-tpch.log](https://github.com/matrixorigin/matrixone/files/12341955/mo-tpch.log)

oom error：
<img width="1583" alt="截屏2023-08-15 14 48 03" src="https://github.com/matrixorigin/matrixone/assets/39303074/b9f32b99-990b-4bf5-9b6a-357a2483de38">

**Comment by nnsgmsone** [comment]
先设置GOMEMLIMIT和调小cache大小跑吧。。 @tianyahui-python

**Comment by sukki37** [comment]
tracked by #10945

**Comment by nnsgmsone** [comment]
经过测试eks和129都可以跑，https://github.com/matrixorigin/mo-auto-test/actions/runs/7015615926/job/19085534500。tke的stream closed在等复现，然后fix。

**Comment by aressu1985** [comment]
this issue closed
