### ISSUE TITLE
[Feature Request]: Support `insert ignore`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#11224]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
MO does not support `insert ignore` now:

mysql> INSERT IGNORE INTO `test`.`storage` (`collecttime`,`value`,`account`,`interval`) VALUES ('2023-08-15 14:19:00',4790.699000,'test1',1);
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 13 near " IGNORE INTO `test`.`storage` (`collecttime`,`value`,`account`,`interval`) VALUES ('2023-08-15 14:19:00',4790.699000,'test1',1)";
```
```


### Describe the feature you'd like

MO supports `insert ignore`

### Describe implementation you've considered

_No response_

### Documentation, Adoption, Use Case, Migration Strategy

_No response_

### Additional information

_No response_

**Comment by domingozhang** [comment]
to be implemented in next release

**Comment by ouyuanning** [comment]
you can try SQL like:

`INSERT INTO `test`.`storage` (`collecttime`,`value`,`account`,`interval`) VALUES ('2023-08-15 14:19:00',4790.699000,'test1',1) on duplicate key update account=account;`

**Comment by DanielZhangQD** [comment]
> you can try SQL like:
> 
> `INSERT INTO `test`.`storage` (`collecttime`,`value`,`account`,`interval`) VALUES ('2023-08-15 14:19:00',4790.699000,'test1',1) on duplicate key update account=account;`

@ouyuanning 试了一下可以满足我们需求，我们就用这个语句

**Comment by dengn** [comment]
Update in 1.2. For test and doc side, follow MySQL behavior, and performance should be equal to INSERT INTO.

**Comment by YANGGMM** [comment]
support insert ignore synatx in https://github.com/matrixorigin/matrixone/issues/15020

**Comment by heni02** [comment]
测试总结，目前和mysql差异：
1: null约束报错，mysql不报错
<img width="609" alt="企业微信截图_83957d89-7354-420b-b17d-f3023d0376a4" src="https://github.com/matrixorigin/matrixone/assets/113406637/36fbff71-75b2-4a4c-8764-a1b2ee4b420f">
<img width="1330" alt="企业微信截图_50f89551-2692-4e43-b636-fc713798da9e" src="https://github.com/matrixorigin/matrixone/assets/113406637/f122da05-ef7c-45b4-aa40-97df689b3464">

2.外键约束报错，mysql不报错
<img width="1103" alt="企业微信截图_51c6b1e0-5286-4230-94ad-896bd9223c23" src="https://github.com/matrixorigin/matrixone/assets/113406637/a4d9661d-e66e-4420-9853-5e9847971237">
3.超出类型值范围报错，mysql不报错
<img width="1359" alt="企业微信截图_8b145678-3969-40fb-ad09-63b84bc716be" src="https://github.com/matrixorigin/matrixone/assets/113406637/e940195f-090a-4251-b420-0e7f2b9ff91f">
4.类型不匹配也报错
<img width="992" alt="企业微信截图_c0b33fd2-9f98-4b63-9abc-c46272eaa612" src="https://github.com/matrixorigin/matrixone/assets/113406637/42c67af2-1272-4de7-acf4-bad30b7f72f8">

**Comment by heni02** [comment]
mo目前没有记录ignore的数据，mysql可以查到ingore的数据 ，@dengn cc
<img width="1015" alt="企业微信截图_1eb517ce-4633-4274-80cf-9b71f5b9acc9" src="https://github.com/matrixorigin/matrixone/assets/113406637/84cba347-6730-4257-9336-65ef2cb87643">

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/MO-Cloud/issues/2956

**Comment by ouyuanning** [comment]
@jensenojs 重新实现一下insert ignore吧。
1、应该要用另外的算子实现，不能走on duplicate key
2、应该就是类似先join一遍，检查通过的行才流入到insert算子 （这里我一时半会也想不出来要不要新增一个join类型）
3、先实现当前的语义，只是不走on duplicate key。 MySQL的语义更复杂，可以逐步来。

**Comment by jensenojs** [comment]
docs :  https://github.com/matrixorigin/docs/pull/284

**Comment by aunjgr** [comment]
insert ignore语法本身已经支持。性能问题使用 #17500 继续跟踪。
