### ISSUE TITLE
[Bug]: DN crash when upgrade from 1715a1f3 to b4fbfeed

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#11229]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b4fbfeed
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

upgrade the cluster from commit 1715a1f3 to b4fbfeed, DN crashes

```
panic: runtime error: index out of range [25] with length 25

goroutine 274 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*Batch).Append(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers/batch.go:483
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*CheckpointData).readAll(0xc001757340, {0x2fd2d58, 0xc0005dfcb0}, 0x3, {0x2ff3a90, 0xc00013f170})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/utils.go:1884 +0x334
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*CheckpointData).ReadFrom(0xc001757340, {0x2fd2d58, 0xc0005dfcb0}, 0x3, {0xc0050c51d0, 0x4f, 0x4f}, 0x88?, {0x2ff3a90, 0xc00013f170}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/utils.go:1738 +0xde
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*CheckpointEntry).Read(0xc001955d40, {0x2fd2d58, 0xc0005dfcb0}, 0xc001a0ce20, 0x2ff3a90?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/entry.go:176 +0xbc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).Replay.func2(0x0, 0x3)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/replay.go:154 +0x76e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).Replay(0xc000150780, {0x2fce160, 0xc000f96ed0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint/replay.go:189 +0xe7c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x2fd2d58, 0xc0005dfcb0}, {0xc003028410, 0x50}, 0xc000172500?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/open.go:143 +0x1070
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0x2fd2d58, 0xc0005dfcb0}, {0xc003028190, 0x4c}, 0x100?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:1038 +0x1a8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0x2fd2d58?, 0xc0005dfcb0?}, {0xc003028190?, 0x0?}, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:95 +0x49
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0x2fd2d58?, 0xc0005dfcb0}, {0xc003028190, 0x4c}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:69 +0x24f
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).newTAEStorage(0xc00019d1e0, {0x2fd2d58, 0xc0005dfcb0}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/factory.go:151 +0x25f
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).createTxnStorage(0xc00019d1e0, {0x2fd2d58, 0xc0005dfcb0}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/factory.go:73 +0x22e
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).createReplica.func1({0x2fd2d58?, 0xc001516c90?})
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store.go:286 +0x171
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

### Expected Behavior

DN should not crash after upgrading

**Comment by jiangxinmeng1** [comment]
#11232 之后，还是会报错
panic: req.Batch.Vecs length is 1, should be 2

goroutine 221 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(0xc00a679620, {0x2fd50b8, 0xc00a7b2d50}, {0x3043ed8, 0xc00af87690}, 0xc00c3ef040, 0xc018ab7b78?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:971 +0xba9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).handleRequests(0x9a1ce06d00000001?, {0x2fd50b8, 0xc00a7b2d50}, {0x3043ed8?, 0xc00af87690?}, 0xc0199c4180)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:249 +0x25f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(_, {_, _}, {{0xc00abfbfd0, 0x10, 0x10}, 0x0, {0x177b95789a1ce06d, 0x1, 0x0, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:165 +0x334
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(_, {_, _}, {{0xc00abfbfd0, 0x10, 0x10}, 0x0, {0x177b95789a1ce06d, 0x1, 0x0, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:98 +0x82
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc005c74240, {0x2fd50b8, 0xc00a7b2d50}, 0xc00591eb60, 0xc018a9e780)
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:245 +0x6a8
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc000134100?, {0x2fd50b8, 0xc00a7b2d50}, 0xc00591eb60, 0xc018a9e780)
        /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.executor.exec({{0xc12f01779241bd4d, 0xb46f2b5b, 0x442b9e0}, {0x2fd50b8, 0xc00a7b2d50}, 0xc00af87510, 0xc00591eb60, {0x2fe9d80, 0xc000134f20}, 0xc0001227b0, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:275 +0x10d
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).handleTxnRequest(0xc0001340b0, {0x2fd50b8, 0xc001a84ea0})
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:250 +0x125
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5

**Comment by aylei** [comment]
> #11232 之后，还是会报错 panic: req.Batch.Vecs length is 1, should be 2
> 
> goroutine 221 [running]: github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(0xc00a679620, {0x2fd50b8, 0xc00a7b2d50}, {0x3043ed8, 0xc00af87690}, 0xc00c3ef040, 0xc018ab7b78?) /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:971 +0xba9 github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).handleRequests(0x9a1ce06d00000001?, {0x2fd50b8, 0xc00a7b2d50}, {0x3043ed8?, 0xc00af87690?}, 0xc0199c4180) /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:249 +0x25f github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(_, {_, _}, {{0xc00abfbfd0, 0x10, 0x10}, 0x0, {0x177b95789a1ce06d, 0x1, 0x0, ...}, ...}) /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:165 +0x334 github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(_, {_, _}, {{0xc00abfbfd0, 0x10, 0x10}, 0x0, {0x177b95789a1ce06d, 0x1, 0x0, ...}, ...}) /go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:98 +0x82 github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc005c74240, {0x2fd50b8, 0xc00a7b2d50}, 0xc00591eb60, 0xc018a9e780) /go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:245 +0x6a8 github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc000134100?, {0x2fd50b8, 0xc00a7b2d50}, 0xc00591eb60, 0xc018a9e780) /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96 github.com/matrixorigin/matrixone/pkg/txn/rpc.executor.exec({{0xc12f01779241bd4d, 0xb46f2b5b, 0x442b9e0}, {0x2fd50b8, 0xc00a7b2d50}, 0xc00af87510, 0xc00591eb60, {0x2fe9d80, 0xc000134f20}, 0xc0001227b0, ...}) /go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:275 +0x10d github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).handleTxnRequest(0xc0001340b0, {0x2fd50b8, 0xc001a84ea0}) /go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:250 +0x125 github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1() /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79 created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5

这个可能和降级过有关

**Comment by aylei** [comment]
测试从  1715a1f3 升级到 ec91a30c 没有问题

**Comment by aylei** [comment]
在阿里云上测试从  1715a1f3 升级到 ec91a30c, 复现这个问题

```
panic: req.Batch.Vecs length is 1, should be 2

goroutine 292 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(0xc009b82180, {0x2fd5298, 0xc00adbb410}, {0x30440d8, 0xc008db3860}, 0xc01ea660d0, 0xc019057b78?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:971 +0xba9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).handleRequests(0x597cdf5500000001?, {0x2fd5298, 0xc00adbb410}, {0x30440d8?, 0xc008db3860?}, 0xc01ea64180)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:249 +0x25f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(_, {_, _}, {{0xc00aab6110, 0x10, 0x10}, 0x0, {0x177c6bab597cdf55, 0x1, 0x0, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:165 +0x334
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(_, {_, _}, {{0xc00aab6110, 0x10, 0x10}, 0x0, {0x177c6bab597cdf55, 0x1, 0x0, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:98 +0x82
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc0000f1320, {0x2fd5298, 0xc00adbb410}, 0xc008c50b60, 0xc019ac0600)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:245 +0x6a8
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc0014c6050?, {0x2fd5298, 0xc00adbb410}, 0xc008c50b60, 0xc019ac0600)
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.executor.exec({{0xc12fe775ef62d9e5, 0x1474ffb05, 0x442ba00}, {0x2fd5298, 0xc00adbb410}, 0xc008db3520, 0xc008c50b60, {0x2fe9f80, 0xc001add4a0}, 0xc000142ef0, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:275 +0x10d
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).handleTxnRequest(0xc0014c6000, {0x2fd5298, 0xc001593260})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:250 +0x125
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5
```

**Comment by triump2020** [comment]
Being reproducing

**Comment by triump2020** [comment]
blocked

**Comment by aylei** [comment]
> @aylei Did it reproduce in your ali-cloud env using [my branch](https://github.com/triump2020/matrixone/tree/test-commit-ec91a30) ?

not yet

**Comment by triump2020** [comment]
not been reproduced

**Comment by triump2020** [comment]
not been reproduced

**Comment by triump2020** [comment]
not been reproduced

**Comment by triump2020** [comment]
not been reproduced

**Comment by aylei** [comment]
closing, as cannot reproduced
