### ISSUE TITLE
[Bug]: CAST doesn't work properly

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1122]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 33ae31aa37c16f32cc881d6f6c214e750351b78b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

select CAST(userID AS BINARY) userid_cast from t1;
+-------------+
| userid_cast |
+-------------+
| 1           |
| 2           |
| 1           |
| 3           |
| 1           |
| 6           |
| 11          |
+-------------+

### Expected Behavior

+--------------------------+
| userid_cast              |
+--------------------------+
| 0x31                     |
| 0x32                     |
| 0x31                     |
| 0x33                     |
| 0x31                     |
| 0x36                     |
| 0x3131                   |
+--------------------------+

**Comment by yingfeng** [comment]
duplicate with #2304
