### ISSUE TITLE
[Bug]: occasional Communications link failure in TP(sysbench oltp and tpcc) test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11237]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

sometimes, there are occasional communications link failure error in TP(sysbench oltp and tpcc) test,such as:

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5823409982/job/15794619976
![image](https://github.com/matrixorigin/matrixone/assets/47846308/1db54b36-26e7-4f4e-95b9-01bd5dbc3a82)

job:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5872157105/job/15924221060
<img width="1389" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/bb66f538-2d93-4169-a39b-26d1650b05c3">

this issue will record this problem, and track if the error increased

**Comment by triump2020** [comment]
事务提交给DN前， pipeline 执行已经超过了 59 秒.

 
![1692250875181](https://github.com/matrixorigin/matrixone/assets/63033222/27016fdd-cbfb-40ce-a64c-e4908701ec87)

**Comment by triump2020** [comment]
后面可以重点关注下这个时间耗在哪里？  1.  lockop 算子的 retry  2. logtail 的 消费是不是慢

**Comment by triump2020** [comment]
blocked by other issue

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
maybe fixed by #11750

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
等查完tpcc ww/dup 问题之后.

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
no progress

**Comment by triump2020** [comment]
blocked by  objectlist feature

**Comment by triump2020** [comment]
blocked by objectlist feature

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
请假两天

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked by other S-1

**Comment by aressu1985** [comment]
@triump2020 why this assign to me?

**Comment by aressu1985** [comment]
fixed
