### ISSUE TITLE
[STMT-WHERE]: WHERE clause does't work in SHOW statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1123]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 33ae31aa37c16f32cc881d6f6c214e750351b78b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

how tables from test where tables_in_test like '%t2%';
ERROR 1046 (3D000): No database selected

use test;
+-----------+
| Table     |
+-----------+
| vc        |
| $table18  |
| t_default |
| names     |
| t2        |
| t1        |
+-----------+

### Expected Behavior

+----------------+
| Tables_in_test |
+----------------+
| t2             |
+----------------+
1 row in set (0.00 sec)

**Comment by m-schen** [comment]
it's same to issue #979

**Comment by m-schen** [comment]
can support after we have system table.

**Comment by m-schen** [comment]
0.2 will not support where for show statement.

**Comment by daviszhen** [comment]
based on the issue #2372

**Comment by daviszhen** [comment]
it maybe not be supported in 0.5. It should confirmed again.

**Comment by fengttt** [comment]
Verified, done.
