### ISSUE TITLE
[Bug]: some deadlock check is busy error in tp(sysbench & tpcc) stability long running test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

there are some deadlock check is busy error in tp(sysbench & tpcc) stability long running test on distributed mode
the sysbench tools log:
<img width="1399" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/16826f0a-ceff-48a0-acbd-0070e52d9b6f">

the tpcc tools log:
<img width="1291" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/66007838-cf24-4dc2-8cd9-25e48a31450a">

cn/dn resource usage can be get from loki:
http://139.155.148.31:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=mo-stb-20230815&from=now-24h&to=now

the cpu usage is more than 95%

**Comment by triump2020** [comment]
@ouyuanning   Thanks !

**Comment by ouyuanning** [comment]
辛苦张旭帮忙看看

**Comment by zhangxu19830126** [comment]
需要套路，可能就是正常的现象

**Comment by zhangxu19830126** [comment]
还没有处理

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
fixed by #11773

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
