### ISSUE TITLE
[Bug]: result consistency check failed for tpcc 10-50 test on pessimistic mode on TKE

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11236]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ec91a30
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5872157105/job/15924221060

<img width="1372" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/93e67c73-2e15-43f8-80cc-a9e5e113edbe">

**2023-08-15 23:16:08 ERROR ConsistencyCheck:85 - Consistency verification failed for sql : (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
2023-08-15 23:16:08 ERROR ConsistencyCheck:86 - The exceptional result are :
6	22208562.74	

2023-08-15 23:16:08 ERROR ConsistencyCheck:85 - Consistency verification failed for sql : (Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);
2023-08-15 23:16:08 ERROR ConsistencyCheck:86 - The exceptional result are :
6	22207303.63**	

the mo log can be get from loki:
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-rc-20230815%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D

### Expected Behavior

result consistency check will always be NULL

### Steps to Reproduce

```Markdown
NEED TRY FOR SOME TIMES
```

**Comment by triump2020** [comment]
@ouyuanning   Thanks!

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
no repro

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by aressu1985** [comment]
不好复现，也没有在出现过，现降级跟踪处理

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
可能跟上周11024等相关的几个问题是一样的。建议转入观察期。

**Comment by LiSong0214** [comment]
@aressu1985 貌似已经修掉了，麻烦再复现一下
