### ISSUE TITLE
[Bug]: running tpch 1T on eks 4cn memory leak

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#11242]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

running tpch 1T on eks 4cn, wait for a while after each run. the heap memory is higher and higher, and cause oom after 3 run.

it seems that memory allocated in github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc   is not released.

after first run:
1480.05MB 13.03% 86.69%  1480.05MB 13.03%  github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc
after second run:
 2613.35MB 21.47% 88.05%  2613.35MB 21.47%  github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc
after third run:
 3931.92MB 29.06% 89.85%  3931.92MB 29.06%  github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc
waiting for half an hour and do nothing:
3932.94MB 29.60% 91.23%  3932.94MB 29.60%  github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc

[tpch1T.zip](https://github.com/matrixorigin/matrixone/files/12355239/tpch1T.zip)

**Comment by aronchanisme** [comment]
Potential memory leak in `github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc`, which indicates codes from @zhangxu19830126 . As @zhangxu19830126  is taking a few days off, @ouyuanning  could you please kindly help take a look first? Thanks a lot.

**Comment by ouyuanning** [comment]
辛苦张旭看看

**Comment by zhangxu19830126** [comment]
It's possible that the threshold for the next gogc hasn't been reached yet, resulting in the gogc not being penalized. In the tpch1t scenario, a lot of data will be transferred over the network between multiple cn's, and each time a new link will be created, and after the link is closed, the allocated memory will be set to nil and given to go's gc to manage. Trouble adding gogc=10 and turn on go's gc log, next time you run it, attach the info to the issue

**Comment by badboynt1** [comment]
已确认不是gc不及时的原因，而是确实存在泄漏。 正在进一步调查

**Comment by aunjgr** [comment]
拿着引用没有释放的地方是在MO里面，不是在goetty这里。应该继续在MO里面查

**Comment by zhangxu19830126** [comment]
fixed
