### ISSUE TITLE
[Bug]: No error is reported when modifying one of the columns in the composite primary key column.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11247]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b0002bfac60998670ed15b164f51e44ada872697
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="753" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/bf9f5c82-3945-4911-9007-3b7fdedda85f">

### Expected Behavior

<img width="740" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/25302194-efd3-46bd-af7f-379b01f2d09e">

### Steps to Reproduce

```Markdown
drop table if exists primary07;
create table primary07(col1 int ,col2 float, col3 decimal, primary key (col1, col2));
insert into primary07 values (1, 213412.32143, 3214312.34243214242);
insert into primary07 values (2, -324.2342432423, -1243.42334234242);
alter table primary07 modify col1 double default null;
alter table primary07 modify col2 decimal(28,10);
show create table primary07;
drop table primary07;
```

**Comment by aronchanisme** [comment]
Verifiing if any column of a compisite primary key cannot be defined as null value from MO's product feature desgin.

**Comment by aronchanisme** [comment]
> Verifiing if any column of a compisite primary key cannot be defined as null value from MO product feature desgin's perspective.

Confirmed with product manager that no column of a composite key can be defined as null. Docs will add more illustration here. 
https://docs.matrixorigin.cn/0.8.0/MatrixOne/Develop/schema-design/data-integrity/primary-key-constraints/#_2

Thus, this issue seems to be a bug. The expected behavior should throw an error indicating the above message.  @qingxinhome  Please kindly help take a look, thanks.

**Comment by lacrimosaprinz** [comment]
doc added more information:https://github.com/matrixorigin/matrixorigin.io.cn/pull/656

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen @lacrimosaprinz

**Comment by Ariznawlll** [comment]
<img width="1887" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/770d7c89-e6de-441f-aa39-f61258442c95">

Verified！
