### ISSUE TITLE
[Bug]: table insertion error after alter table.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11245]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7930addc4dacb77c6c921c19c749386159daa35d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="748" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9f992fff-18a1-4250-913d-127f90c8f836">

### Expected Behavior

insert success!

### Steps to Reproduce

```Markdown
drop table if exists decimal01;
create table decimal01 (col1 decimal,col2 decimal(38,10));
insert into decimal01 values (23746723468723.242334243, 38208439024234.43242342423423423422342);
insert into decimal01 values (32487329847923424, -4324324324.3297932749028949373324242423424);
alter table decimal01 modify column col1 decimal(38,6);
alter table decimal01 modify col2 decimal(38,9);
show create table decimal01;
select * from decimal01;
truncate table decimal01;
alter table decimal01 add column col3 decimal(19,0) first;
show create table decimal01;
insert into decimal01 values (37298342.123, -37829342.3244234, -283794324.2342);
select * from decimal01;
drop table decimal01;
```

**Comment by aronchanisme** [comment]
The issue is raised not by the modification of `col1` or `col2`, but the addition of column `col3` and an insert command after the table is truncated. @qingxinhome Please kindly help take a look, thanks.

<img width="1382" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/8215dce9-74a5-4525-9c15-8560aba51eb2">

Steps to reproduce can be simplified as below
```bash
drop table if exists decimal01;
create table decimal01 (col1 decimal,col2 decimal(38,10));
insert into decimal01 values (23746723468723.242334243, 38208439024234.43242342423423423422342);
insert into decimal01 values (32487329847923424, -4324324324.3297932749028949373324242423424);
-- alter table decimal01 modify column col1 decimal(38,6);
-- alter table decimal01 modify col2 decimal(38,9);
show create table decimal01;
select * from decimal01;
truncate table decimal01;
alter table decimal01 add column col3 decimal(19,0) first;
show create table decimal01;
insert into decimal01 values (37298342.123, -37829342.3244234, -283794324.2342);
select * from decimal01;
drop table decimal01;
```

**Comment by zengyan1** [comment]
下面没有报错，上面报错，唯一的区别是上面在add column时加了first使这一列加在了最前面并使其它列的位置往后顺移

**Comment by qingxinhome** [comment]
Processing

**Comment by qingxinhome** [comment]
The issue has been resolved, please test and verify @aronchanisme @Ariznawlll @daviszhen

**Comment by Ariznawlll** [comment]
<img width="943" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/08394489-2b13-46e3-8e83-289faff6d816">

Verified!
