### ISSUE TITLE
[Bug]: Error message is incorrect when change table column.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11259]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3197c5a41991f2ed1db30e04584461f5ddfb57ea
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
<img width="977" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/35ad2595-f881-4ee6-8d5a-6d17b4c3e60e">

### Expected Behavior

Error modifying table， not the table does not exists.

### Steps to Reproduce

drop table if exists abnormal05;
create temporary table abnormal05 (col1 datetime, col2 blob);
insert into abnormal05 values ('1997-01-13 00:00:00', '342ewfyuehcdeiuopwu4jo3lekwdfhiu48woi3jrdnefrbwui34f');
insert into abnormal05 values ('2012-01-13 23:23:59', '63298ufh3jcweuiv4h32jhf432ouy4hu3enjwfnwje4n3bj24f34573');
select * from abnormal05;
alter table abnormal05 change col1 col1_euwhnew float;
alter table abnormal05 change col2 col2_njkwhew int;
select * from abnormal05;
show create table abnormal05;
_No response_

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen @lacrimosaprinz

**Comment by Ariznawlll** [comment]
<img width="865" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2c59d687-be9d-411f-8260-6e6a1a5b3245">

Verified！
