### ISSUE TITLE
[Bug]: mo panic by slice bounds out of range [:252] with capacity 0 during stability test on standlone mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11255]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6828ed0
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

when runing stability test on standlone mode for about 4 hours, the mo panic by:
{"level":"INFO","time":"2023/08/16 15:32:08.145516 +0800","name":"dn-service.logtail-push-service","caller":"service/server.go:375","msg":"handle subscription asynchronously","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"1d249e41-9e97-4a2d-8aa6-3791aee4db62","table":"db_id:334778 tb_id:334790 "}
{"level":"INFO","time":"2023/08/16 15:32:08.153743 +0800","name":"dn-service.logtail-push-service","caller":"service/session.go:449","msg":"send subscription response","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"1d249e41-9e97-4a2d-8aa6-3791aee4db62","stream-id":1,"remote":"127.0.0.1:35396","table":"db_id:334778 tb_id:334790 ","To":"PhysicalTime:1692171128138126295 "}
panic: runtime error: slice bounds out of range [:252] with capacity 0

goroutine 702 [running]:
github.com/matrixorigin/matrixone/pkg/container/types.(*Varlena).GetByteSlice(0x45c7b2?, {0x0?, 0x38?, 0xffffffffffffffff?})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/container/types/bytes.go:104 +0xb0
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetBytesAt(0xc36cf4f920?, 0xc493722df9?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/container/vector/vector.go:188 +0x65
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.EncodePrimaryKeyVector(0xc66f1c2000, 0xc0011d8600)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailreplay/encode.go:188 +0xbe5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).HandleRowsInsert(0xc66f1aaff0, {0x2fd5c50?, 0xc003a11c20?}, 0xc66f1aa640, 0x0, 0xc33f509af8?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:302 +0x2f3
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).HandleLogtailEntry(0xc003c9f040?, {0x2fd5c50, 0xc003a11c20}, 0xc66f1b6680, 0x3055ae0?, 0x148?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:263 +0x116

github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeEntry({0x2fd5c50, 0xc003a11c20}, 0x3055ae0?, 0xc004a0e300, 0x47bc67?, 0xc66f1b6680)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtail.go:39 +0x108
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeLogTailOfPushWithLazyLoad({0x2fd5c50, 0xc003a11c20}, 0x51bc6?, 0x0?, 0xc33f509cf0?, 0xc33f509da8)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:1019 +0x85
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartitionOfPush({0x2fd5c50, 0xc003a11c20}, 0x1?, 0xc004a0e300, 0xc33f509da8, 0x1)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:988 +0x2c5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).consumeSubscribeResponse(0x0?, {0x2fd5c50?, 0xc003a11c20?}, 0xffffffffffffffff?, 0x1?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:954 +0xf6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.cmdToConsumeSub.action({0xc33f509f78?}, {0x2fd5c50?, 0xc003a11c20?}, 0xc004a0e300, 0x2?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:922 +0x56
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.createRoutineToConsumeLogTails.func1({0x2fd5c50, 0xc003a11c20}, 0xc004060fc0?, 0xc006d299c0, 0xc004610fb0?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:883 +0xed
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.createRoutineToConsumeLogTails
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:905 +0x178
~                          

the whole mo log:
[panic.tar.gz](https://github.com/matrixorigin/matrixone/files/12357612/panic.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo on standlone mode
2. run some tests in parallel
   bvt loop
   tpch 10g loop queries
   tpcc 10-10 long running test
   sysbench mixed case long running test
```

**Comment by LeftHandCold** [comment]
还没有复现

**Comment by LeftHandCold** [comment]
same as #11430

**Comment by LeftHandCold** [comment]
not yet reproduced

**Comment by LeftHandCold** [comment]
Probably similar to #11430  for reasons

**Comment by LeftHandCold** [comment]
not yet reproduced

**Comment by LeftHandCold** [comment]
not yet reproduced

**Comment by LeftHandCold** [comment]
not yet reproduced

**Comment by LeftHandCold** [comment]
It is difficult to reproduce, temporarily change to s0, add logs and continue to reproduce and observe. @aressu1985

**Comment by LeftHandCold** [comment]
还未复现，继续观察

**Comment by LeftHandCold** [comment]
还未复现，继续观察
