### ISSUE TITLE
[Bug]:  alter table change column wait for lock after commit in pessimistic mode.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11268]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3197c5a41991f2ed1db30e04584461f5ddfb57ea
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1381" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/032f13ff-970d-444a-a89d-411d95f4af62">

### Expected Behavior

after commit, insert into alter01 values(8, "h") success!

### Steps to Reproduce

```Markdown
drop table if exists alter01;
create table alter01(col1 int primary key,col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");
begin;
alter table alter01 change col1 col1New float;
-- @session:id=1{
-- @wait:0:commit
insert into alter01 values (8,"h");
show create table alter01;
select * from alter01;
-- @session
show create table alter01;
select * from alter01;
drop table alter01;
```

**Comment by qingxinhome** [comment]
处理中

**Comment by qingxinhome** [comment]
association #11213

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen

**Comment by Ariznawlll** [comment]
<img width="1345" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0b368311-d727-499a-8f97-89d403d1133d">
Verified!
