### ISSUE TITLE
[Bug]: alter table change column name: column name does not support Chinese, space, special character with ``

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11269]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3197c5a41991f2ed1db30e04584461f5ddfb57ea
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="983" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c9a8c3bc-039d-4d77-9e6f-6c65909fa286">

### Expected Behavior

<img width="923" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/4188d7f3-db6a-46d8-8bb9-f2a4316fe6f6">

### Steps to Reproduce

```Markdown
-- column name test: with `` and chinese character
drop table if exists name01;
create table name01 (col1 int, col2 decimal);
insert into name01 values (1, 378292);
insert into name01 values (2, 3289.111111);
alter table name01 change column col1 `数据库管理系统数据库操作系统数据库系统数据库` int;
show create table name01;
drop table name01;

-- column name test: with `` and space
drop table if exists name02;
create table name02 (col1 int, col2 decimal);
insert into name02 values (1, 378292);
insert into name02 values (2, 3289.111111);
alter table name02 change column col1  `cwhueh   3u2j4kfker` int;
show create table name02;
drop table name02;

-- column name test: with `` and special character
drop table if exists name03;
create table name03 (col1 int, col2 decimal);
insert into name03 values (1, 378292);
insert into name03 values (2, 3289.111111);
alter table name03 change column col1 `RAVHJBWUIHNJCDW****&&*((()(*&^&^%^^&^*&` int;
show create table name03;
drop table name03;
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen @lacrimosaprinz

**Comment by Ariznawlll** [comment]
<img width="1759" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3f9b9aa0-9e53-405f-b07a-e2857cb9fbcd">

<img width="1641" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/99cf6ee0-ca6b-4b7c-8564-418917d19d6d">

<img width="1812" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9fce5a61-f5d6-4170-87e4-c6f5d0d6ab5b">

Verified！
