### ISSUE TITLE
[Bug]: w-w conflict in committing the txn executing prepare select

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11265]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):82141ec8bce583a54806422317c747ffd57a1572
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/b7a25571-6c00-4aaa-a677-4f034e0d858b)

[result.txt](https://github.com/matrixorigin/matrixone/files/12364699/result.txt)

### Expected Behavior

no w-w conflict.

### Steps to Reproduce

```Markdown
1, use the branch https://github.com/daviszhen/matrixone/tree/0816-debug-11948
changes different from the main:
a. fatal log level
b. close trace & metric
c. enable enable-leak-check to check txn leaker
d. add statement `show active txn`
e. print all txn commit/rollback status into stdout.
f. print txn created by the PREPARE statement

2, run tpcc 100 warehouse 1000 parallel termnials
```

### Additional information

the problem  was found in debuging the issue https://github.com/matrixorigin/matrixone/issues/10948

**Comment by daviszhen** [comment]
调试  https://github.com/matrixorigin/matrixone/issues/10948 过程中发现的。

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
看着跟  https://github.com/matrixorigin/matrixone/issues/11038 类似。应该main分支已处理了。可以确认下
