### ISSUE TITLE
[Bug]: The table column exists but prompt the table does not exist

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11260]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3197c5a41991f2ed1db30e04584461f5ddfb57ea
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="924" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5b5b9ff4-b021-425b-8360-c6297d680aa3">

### Expected Behavior

drop table if exists cluster01;
create table cluster01(col1 int, col2 decimal) cluster by col1;
insert into cluster01 values (1, 389234924);
insert into cluster01 values (2, -2893428);
alter table cluster01 change col2 col2worejnfenrororiri float;
alter table cluster01 change col1 iwijwehfndatabasectm double after col2worejnfenrororiri;
show create table cluster01;
select * from cluster01;

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen @lacrimosaprinz

**Comment by Ariznawlll** [comment]
<img width="931" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/90262e46-475d-4a94-83dd-0f0a2d9f31b2">
Verified！
