### ISSUE TITLE
[Bug]: default value doesn't work 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table names(id int default value 1,name VARCHAR(255) UNIQUE,age int);
insert into names(name, age) values("Abby", 24);
insert into names(name, age) values("Bob", 25);
insert into names(name, age) values("Carol", 23);
insert into names(name, age) values("Dora", 29);

select * from names;
+------+-------+------+
| id   | name  | age  |
+------+-------+------+
|    0 | Abby  |   24 |
|    0 | Bob   |   25 |
|    0 | Carol |   23 |
|    0 | Dora  |   29 |
+------+-------+------+

### Expected Behavior

select * from names;
+------+-------+------+
| id   | name  | age  |
+------+-------+------+
|    1 | Abby  |   24 |
|    1 | Bob   |   25 |
|    1 | Carol |   23 |
|    1 | Dora  |   29 |
+------+-------+------+

**Comment by m-schen** [comment]
has been solved at branch factor.
and you can verify it after factor merge into main.

**Comment by m-schen** [comment]
and 
`create table names(id int default value 1,name VARCHAR(255) UNIQUE,age int);`
is not a right sql, should be `id int default 1`
