### ISSUE TITLE
[Bug]: The abnormal value in filtering operation where in update statement success.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11274]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f13e4164f0ff7cc0a7d18c4405320ca175488911
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1888" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/26a4eed5-db63-4d32-8561-896dde962a7d">

### Steps to Reproduce

```Markdown
drop table if exists name02;
create table name02(col1 int, col2 int, col3 varchar(20));
insert into name02 values (1,2,'cfewquier');
insert into name02 values (2,3,'329382');
insert into name02 values (3, 10, null);
select * from name02;
alter table name02 rename column col1 to col1New;
alter table name02 rename column col3 to col3New;
show create table name01;
insert into name02 (col1, col2, col3) values (3,4,'121131312');
insert into name02 (col1New, col2, col3New) values (3,4,'121131312');
select * from name02;
update name02 set col3New = '2798u3d3frew' where col3New = 6;
drop table name02;
```

**Comment by aronchanisme** [comment]
It seems to be mo is acting as a normal behavior, while mysql is doing something I cannot understand. 
`col3` is defined as a `varchar(20)` and renamed to `col3new`. Then you try to update the value of `col3new` to `2798u3d3frew` where the value of the entries are `6`. However, there are no entries in this table where column `col3new` 's value is set to `6`. Thus, mo finds in the table but no dataset meets the conditions, and `Query OK, 0 rows affected (0.00 sec)` is retruned. It seems normal as I can see. 
As for mysql, firstly `col3new` is not defined as `DOUBLE`, so why does mysql throws an error indicating `Truncated incorrect DOUBLE value`? Also, the where clause of the update statement meets no condition from the table, then why is mysql indicating the row with `col3new`'s value `cfewquier`? This is something I failed to understand as a normal behavior.

```sql
update name02 set col3New = '2798u3d3frew' where col3New = 6;
```

1. What MO acts
![企业微信截图_16922543342752](https://github.com/matrixorigin/matrixone/assets/46433151/14c2891c-6603-435b-b24d-122d2d00739d)

2. What MySQL acts
![企业微信截图_169225456495](https://github.com/matrixorigin/matrixone/assets/46433151/b6607ad7-8ceb-4c06-888d-a25f83b2508b)

**Comment by Ariznawlll** [comment]
It is not a problem, because the actual behavior of mo is to do an implicit conversion，then compare according to the conversion results. the test case above, firstly, it will cast 6 to varchar, then compare and no match was found and 0 line was changed.

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
