### ISSUE TITLE
[Bug]: cte recursive:   recursive query which include agg etc limitation reported error  message not clear

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11276]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6828ed04cefb5e2b306120f655ab34c16c56aa1a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo error message is SQL parser error: table "cte_ab_1" does not exist, it is not clear error message
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b5d62542-72d4-4d7a-8142-f18d527fc33f)

mysql error message is：
ERROR 3575 (HY000): Recursive Common Table Expression 'cte_ab_1' can contain neither aggregation nor window functions in recursive query block
![image](https://github.com/matrixorigin/matrixone/assets/113406637/39880705-0daf-4c2f-9f76-5de1a8426d00)

recursive query include order by error message:
mysql> with recursive  cte_ab_6(productID,price) as(select p_id,price from product where price >1000.00 union select c.productID,p.price from product p join cte_ab_6 c on p.p_id = c.productID order by c.productID )select * from cte_ab_6;
ERROR 1250 (42000): Table 'c' from one of the SELECTs cannot be used in global ORDER clause
![image](https://github.com/matrixorigin/matrixone/assets/113406637/06f0404f-4ad3-4607-ae6b-69dd79da0e93)

recursive query include distinct error message:
mysql> with recursive  cte_ab_7(productID,price) as(select p_id,price from product  union select distinct c.productID,p.price from product p join cte_ab_7 c on p.p_id = c.productID )select * from cte_ab_7;
ERROR 1235 (42000): This version of MySQL doesn't yet support 'ORDER BY / LIMIT / SELECT DISTINCT in recursive query block of Common Table Expression'

### Steps to Reproduce

```Markdown
with recursive  cte_ab_1(productID,price) as(select p_id,price from product  union select c.productID,avg(p.price) from product p join cte_ab_1 c on p.p_id = c.productID group by productID )select * from cte_ab_1;
with recursive  cte_ab_2(productID,price) as(select p_id,price from product  union select c.productID,sum(p.price) from product p join cte_ab_2 c on p.p_id = c.productID group by productID  )select * from cte_ab_2;
with recursive  cte_ab_6(productID,price) as(select p_id,price from product where price >1000.00 union select c.productID,p.price from product p join cte_ab_6 c on p.p_id = c.productID order by c.productID )select * from cte_ab_6;

ddl：
create table product (id int primary key,p_id int,p_name varchar(25),price decimal(10,3));
insert into product values (001,12,"bed",3560.98),(002,13,"chair",1599.00),(005,12,"desk",2999.99),(006,13,"door",8123.09),(008,13,"mirrors",698.00),(009,8,"tv",5678);
```

**Comment by heni02** [comment]
@iamlinjunhong plz confirm

**Comment by heni02** [comment]
去掉聚集也报表不存在，确认下是什么原因
with recursive  cte_ab_1(productID,price) as(select p_id,price from product  union select c.productID,p.price from product p join cte_ab_1 c on p.p_id = c.productID  )select * from cte_ab_1;
![image](https://github.com/matrixorigin/matrixone/assets/113406637/fee80472-7013-4c33-9d67-67abf1ccb011)
mysql：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/3fd089a7-f5d9-45cf-a615-ca6f2d621144)

**Comment by iamlinjunhong** [comment]
1. 报错不和 mysql 一样是正常的
2. recursive sql 不能有聚合函数
3. initial sql 和 recursive sql 之间目前只能用 union all 连接
4. 参考文档 https://learn.microsoft.com/en-us/sql/t-sql/queries/with-common-table-expression-transact-sql?view=sql-server-ver16

**Comment by heni02** [comment]
ok ,after modifying SQL to union all, an error was reported as：
<img width="1305" alt="企业微信截图_8a80730a-6e63-4baf-be0f-7c8ff882e3d1" src="https://github.com/matrixorigin/matrixone/assets/113406637/a796b3b6-8a2d-4be4-83ff-61a56a6744fc">
The error message is not very clear, please refer to MySQL：
ERROR 3575 (HY000): Recursive Common Table Expression 'cte_ab_1' can contain neither aggregation nor window functions in recursive query block

**Comment by heni02** [comment]
tomorrow confirm other limitation report error message

**Comment by heni02** [comment]
cte include distinct ,reported not clear
[SQL STATEMENT]: with recursive cte_ab_7(id,manager_id,name) as(select p.id,p.manager_id,p.name from emp p where manager_id is null union all select distinct p.id,p.manager_id,p.name from emp p join cte_ab_7 c on p.manager_id= c.id) select * from cte_ab_7;
[EXPECT RESULT]:
This version of MySQL doesn't yet support 'ORDER BY / LIMIT / SELECT DISTINCT in recursive query block of Common Table Expression'
[ACTUAL RESULT]:
internal error: unexpected input batch for column expression

**Comment by heni02** [comment]
cte include orderby not reported error 
[SQL STATEMENT]: with recursive cte_ab_6(id,manager_id,name) as(select p.id,p.manager_id,p.name from emp p where manager_id is null union all select p.id,p.manager_id,p.name from emp p join cte_ab_6 c on p.manager_id= c.id order by c.id) select * from cte_ab_6 order by id;
[EXPECT RESULT]:
Table 'c' from one of the SELECTs cannot be used in global ORDER clause
[ACTUAL RESULT]:
id    manager_id    name
29    198    主任1
72    29    职员2
123    692    主任2
198    333    副总1
333    null    总经理
692    333    副总2
4610    29    职员1

**Comment by heni02** [comment]
cte include subquery reported not clear:
[SQL STATEMENT]: with recursive cte_ab_9(id,manager_id,name,levels) as(select p.id,p.manager_id,p.name,0 as level from emp p where manager_id is null union all select p.id,p.manager_id,p.name,levels+1 from emp p where p.manager_id in(select c.id from cte_ab_9 c)) select * from cte_ab_9;
[EXPECT RESULT]:
In recursive query block of Recursive Common Table Expression 'cte_ab_9', the recursive table must be referenced only once, and not in any subquery
[ACTUAL RESULT]:
SQL parser error: table "cte_ab_9" does not exist

**Comment by heni02** [comment]
[SQL STATEMENT]: with recursive cte_ab_10(id,manager_id,name,levels) as(select p.id,p.manager_id,p.name from emp p where manager_id is null union all select p.id,p.manager_id,p.name from emp p join cte_ab_10 c on p.manager_id= c.id ) select * from cte_ab_10 order by id;
[EXPECT RESULT]:
In definition of view, derived table or common table expression, SELECT list and column names list have different column counts
[ACTUAL RESULT]:
SQL syntax error: 11111 table "cte_ab_10" has 3 columns available but 4 columns specified

**Comment by heni02** [comment]
commit id:2f44ddf6843233883121cc92bb015d1975d8cfb5
The following four error messages are verified to be correct
1. with as update :
<img width="1376" alt="企业微信截图_1a8e920a-1d34-4376-9936-990300e4f518" src="https://github.com/matrixorigin/matrixone/assets/113406637/e98fc46c-5cd5-4118-b641-ebaf14023a90">

2.distinct cte  query:
<img width="1543" alt="企业微信截图_3299d497-569b-4c51-98c6-44c6a6c51017" src="https://github.com/matrixorigin/matrixone/assets/113406637/f5c3a0c7-87bb-42f1-b5d3-8263cb7b417d">

3.cte query order by
<img width="1544" alt="企业微信截图_cded4294-37ed-4919-b2c5-1978ac3314cb" src="https://github.com/matrixorigin/matrixone/assets/113406637/50639179-64a3-40b1-aa21-a2a1a81e74d1">

4.select list not equal cte columns
<img width="1548" alt="企业微信截图_5694a299-8afc-45e3-b6b1-f7b1ea68d8b3" src="https://github.com/matrixorigin/matrixone/assets/113406637/ed19eadb-4233-48d0-b37e-a6bc39224277">

but cte include subquery  still the previous error message
<img width="1545" alt="企业微信截图_16d8ec70-9009-4aa3-ab82-56fcd95d9ca8" src="https://github.com/matrixorigin/matrixone/assets/113406637/53d9bb9e-6cb7-4f8a-8922-977c0eb8a834">
[SQL STATEMENT]: with recursive cte_ab_9(id,manager_id,name,levels) as(select p.id,p.manager_id,p.name,0 as level from emp p where manager_id is null union all select p.id,p.manager_id,p.name,levels+1 from emp p where p.manager_id in(select c.id from cte_ab_9 c)) select * from cte_ab_9;
[EXPECT RESULT]:
In recursive query block of Recursive Common Table Expression 'cte_ab_9', the recursive table must be referenced only once, and not in any subquery
[ACTUAL RESULT]:
SQL parser error: table "cte_ab_9" does not exist

**Comment by iamlinjunhong** [comment]
提pr中

**Comment by heni02** [comment]
confirm，closed
commit id：44086eb6436ae9c63fa78cb3ef4d6a6630f4e802
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ac4e3f9a-bed2-45c2-b64e-bed4c48a085f)

**Comment by Ariznawlll** [comment]
### 测试版本

- 分支：`main`
- commit：`a2f89230085a0f6650ec7bb7017ba6b8a97c9efc`
- 部署方式：本地单节点 LOG/TN/CN，临时隔离目录
- 测试日期：2026-08-15

### 原问题验证

本 issue 讨论递归 CTE 禁止聚合/窗口函数时错误信息不清。本次在最新 main 复核了更小的两个语句：

```sql
WITH RECURSIVE q(n) AS (
    SELECT 1
    UNION ALL
    SELECT MAX(n) + 1 FROM q WHERE n < 3
)
SELECT n FROM q;
```

```sql
WITH RECURSIVE q(n) AS (
    SELECT 1
    UNION ALL
    SELECT n + ROW_NUMBER() OVER() FROM q WHERE n < 3
)
SELECT n FROM q;
```

### Happy Path 覆盖

合法递归表达式、递归 NULL 锚点、递归外层窗口、递归 CTE 子查询消费者、前置 CTE、双消费者、派生消费者、外层 LEFT JOIN、CTAS、VIEW、两种 DML WITH 放置形式和事务回滚均正常。

### Unhappy Path 覆盖

上述聚合和窗口语句各连续执行 3 次，均返回：

```text
internal error: not support aggregate function recursive cte
internal error: not support window function in recursive cte
```

递归成员只含 `GROUP BY` 的既有负例则返回普通 `SQL parser error`，说明错误分类并不一致。

### 白盒验证

`pkg/sql/plan/query_builder.go` 当前在递归成员聚合、窗口函数分支直接构造 `moerr.NewInternalError`（约 8442、8587 行），而 `GROUP BY` 等限制使用 `NewParseError`。这解释了客户端看到 `internal error` 而非 SQL 校验错误。

### 回归测试

建议在现有递归 CTE 负例中补充无 `GROUP BY` 的聚合和窗口最小语句，断言返回稳定的 SQL 不支持错误、而不是 `internal error`。该场景属于稳定公共 SQL，可放入现有递归 CTE motr/BVT 回归。

### 测试证据

完整深探针连续 3 轮均为 `pass=20 fail=0 expected_errors=3`；聚合/窗口两个错误各 3/3 重现。合法控制递归查询稳定返回 `1;2;3` 或对应正确结果。

### 测试结论

测试不通过。
