### ISSUE TITLE
[Bug]: logservice should reject unknown RPC command instead of panic

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#11282]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 2a5eca934ed63d33c1c6fe2a9113a112821105ff
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

LogService panic when a client send an unknown rpc command to HAKeeper.

### Expected Behavior

LogService should reject the unknown command (raise an error on the client-side) instead of panic.

**Comment by volgariver6** [comment]
fixed.
