### ISSUE TITLE
[Bug]: add bvt case, failed to run ut test.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#11287]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ci link: https://github.com/matrixorigin/matrixone/pull/11280

**Comment by triump2020** [comment]
@daviszhen   
![da685f2002445339e8b0c09d9451663](https://github.com/matrixorigin/matrixone/assets/63033222/a3d4b705-6f0e-4113-ac68-4fbc3334db1e)

**Comment by triump2020** [comment]
@xzxiong   Thanks!

![5db181bf4736cc5568ef23da6ef2e16](https://github.com/matrixorigin/matrixone/assets/63033222/e8ec4938-482f-41cc-b26e-21ca31bad8e9)

**Comment by xzxiong** [comment]
ci link is https://github.com/matrixorigin/matrixone/actions/runs/5890295765/job/15998561813?pr=11280

**Comment by xzxiong** [comment]
@tianyahui-python ptal, fixed pr has been merged.
