### ISSUE TITLE
The order of result in SELECT statement is different

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1128]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 57dde60d5551b2502cd04bfaf7232396c387c746
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

select * from names;
+--------+------------+
| userID | min(score) |
+--------+------------+
|     11 |         99 |
|      3 |          3 |
|      2 |          2 |
|      1 |          1 |
|      6 |         10 |
+--------+------------+

### Expected Behavior

+--------+------------+
| userID | MIN(score) |
+--------+------------+
|      1 |          1 |
|      2 |          2 |
|      3 |          3 |
|      6 |         10 |
|     11 |         99 |
+--------+------------+

**Comment by broccoliSpicy** [comment]
At the current version of MatrixOne(commit 28ff26e), the output of select * is consistent, this issue doesn't exist  any more.
