### ISSUE TITLE
[OP-LIKE]: Like statment does not support wildcard characters %

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1129]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 57dde60d5551b2502cd04bfaf7232396c387c746
- Hardware parameters: 
- OS type: MacOS
- Others:
```

### Actual Behavior

mysql> select * from t1 where a like "abc%";
Empty set (0.01 sec)

### Expected Behavior

mysql> select * from t1 where a like "abc%";
+------+
| a    |
+------+
| abc  |
| abcd |
+------+
2 rows in set (0.01 sec)

### Steps to Reproduce

```markdown
create table t1 (a varchar(10));
insert into t1 values ("a"),("abc"),("abcd"),("hello"),("test");
select * from t1 where a like "abc%";
```

**Comment by m-schen** [comment]
Solved at factor branch, will merge into main next time.

**Comment by lignay** [comment]
found the issue in commit 3f32c36753ec9578e17333d395635a349ada1bb7 again.

**Comment by m-schen** [comment]
fixed in Branch main.

**Comment by lignay** [comment]
Verified on 0ca539490e8f5b8adce6210d19ef53d0f83d8a81
