### ISSUE TITLE
[Bug]:  Aggregate logging：data loss after aggregation

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):47684bd237193bcb468dfe54c9a594eb24ff26c6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert table success 12780899 rows
[simple_insert_10_100000]
START : 2023-08-18 15:42:33
END : 2023-08-18 15:52:35
VUSER : 100
TPS : 21297
QPS : 21297
SUCCESS : 12780899
ERROR : 0
RT_MAX : 384
RT_MIN : 1
RT_AVG : 4.69
SUC_RATE : 1.0
EXP_RATE : 1.0
RESULT : SUCCEED

but select sum(aggr_count) from system.statement_info where statement like 'insert into sbtest%', results are 12780636 rows， etl/sys/logs/ dir is empty
![image](https://github.com/matrixorigin/matrixone/assets/113406637/95e91e11-e9b8-4db8-a4cc-09796ffdfbbf)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/cf0814ee-ba49-4dd1-9120-a83fe7a96004)

**Comment by heni02** [comment]
@gavinyue plz confirm

**Comment by gavinyue** [comment]
Root cause not found yet. Will continue to fix tomorrow.

**Comment by gavinyue** [comment]
Root cause not found yet. Will continue to fix tomorrow.

**Comment by gavinyue** [comment]
Here is one reason. 

For the query that is not qualified for aggr, their aggr_count is 0. So sum(aggr_count)  does not count these queries.

**Comment by heni02** [comment]
OK I get it，I need to revalidate, sum of aggr_count=0 and sum(aggr_count)

**Comment by heni02** [comment]
sum(aggr_count) are 12211012,  aggr_count =0 are 811 rows, 12211012+811 greater than 11838079 which are table r1 rows ,it is also strange @gavinyue
commit id: 
insert into table r1 rows:11838079
<img width="412" alt="企业微信截图_637ca9bc-2563-4ac6-9dde-b05ef5e6af6e" src="https://github.com/matrixorigin/matrixone/assets/113406637/c44ebc88-831e-4a7e-a2c6-1bc457adc105">

<img width="1119" alt="企业微信截图_bbfaf20f-2bdc-476a-96b6-704025d1723f" src="https://github.com/matrixorigin/matrixone/assets/113406637/87e73f74-d931-464a-9934-621143e885f4">
