### ISSUE TITLE
[Bug]: index of loading data cases are very unstable on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11310]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d7b6764
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Sometimes, index of loading data cases decreased for some cases, and maybe can be recovered.
This issue will summerize  all of this type of issues.

update on 8.19
job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5904704958/job/16019824339

<img width="1392" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/286209fe-9b95-4528-a67e-d76bc957b615">

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看
