### ISSUE TITLE
[Bug]: `show create table` case failed occasionally in bvt

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11334]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/5910548857

<img width="1459" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/69748e0e-318d-475b-89d8-5fd6568c79de">

[multi-cn-e2e-push-docker-compose-log-pessimistic.zip](https://github.com/matrixorigin/matrixone/files/12385785/multi-cn-e2e-push-docker-compose-log-pessimistic.zip)

**Comment by daviszhen** [comment]
还没看。

**Comment by sukki37** [comment]
repro:
https://github.com/matrixorigin/matrixone/actions/runs/5923118806/job/16058177643?pr=11354
https://github.com/matrixorigin/matrixone/actions/runs/5923118801/job/16058177501?pr=11354

**Comment by daviszhen** [comment]
还没看。

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/5923751419/job/16059989427?pr=11353

**Comment by daviszhen** [comment]
环境刚整好。还没细看

**Comment by daviszhen** [comment]
今天没看。

**Comment by daviszhen** [comment]
跑出来大量的cn service is not ready, retry later
<img width="1254" alt="企业微信截图_2ad66f60-3f1d-4595-b5f1-0a63a905a852" src="https://github.com/matrixorigin/matrixone/assets/60595215/3a38e216-ac25-4d78-b9ab-77b4aacff9d1">

**Comment by daviszhen** [comment]
今天没看

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/813a104a-1bf2-4333-b9dd-618f56d0b7a8)

**Comment by daviszhen** [comment]
能复现。原因还未来得及定位。

**Comment by daviszhen** [comment]
今天没做。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
复现处理来的日志。更完整的日志可以找我。

[s-2.log](https://github.com/matrixorigin/matrixone/files/12497028/s-2.log)
[s-err-2.log](https://github.com/matrixorigin/matrixone/files/12497029/s-err-2.log)

**Comment by daviszhen** [comment]
复现commit 8404a1f1d48608d10a6ed56b94f84f3c8e355e95

**Comment by daviszhen** [comment]
先把工具问题解决掉后，再测吧。 @Ariznawlll  @aressu1985

**Comment by daviszhen** [comment]
下午又复现了一次。抓包显示，alter table之后又发送了commit
![image](https://github.com/matrixorigin/matrixone/assets/60595215/957cbed5-3b50-4fd4-9256-b8dd4f31f915)


![image](https://github.com/matrixorigin/matrixone/assets/60595215/a8bee0f5-a89b-4e70-a418-35d92a79ebe8)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/ec943fdc-7564-43cd-9af0-1fecb8622876)


![image](https://github.com/matrixorigin/matrixone/assets/60595215/8737081f-ac13-468d-b500-521460e8dea4)

**Comment by aressu1985** [comment]
确定是工具和测试用例导致，但是是因为其他case出现问题导致，这个问题先关闭

**Comment by matrix-meow** [comment]
Hello @sukki37. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by aressu1985** [comment]
工具问题，fixed

**Comment by matrix-meow** [comment]
Hello @sukki37. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by aressu1985** [comment]
工具问题，待提PR去除tag，先降级处理
