### ISSUE TITLE
[Bug]: alter db set mysql_compatibility_mode error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11341]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0ef31f1816a5f082efdfc49ab0c94ebda743eaa9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. sys non dump user, db owner not config succeed
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6693ebf8-496b-4b64-a945-02c22b48cf3e)

2. sys non dump user, not db owner not  interception error
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4a0957d3-46b7-41bc-b880-84f26c5ddf8e)

3.non sys admin user, db owner not config succeed
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ce188f5f-2678-47f3-b19d-9b333e8e1d7c)
<img width="849" alt="企业微信截图_1177a5aa-197c-4022-b1d5-bd646fd92f9c" src="https://github.com/matrixorigin/matrixone/assets/113406637/5053f51a-4212-4042-9125-a59e340ff9e4">

4.non sys non admin user ,db ownner not config succeed ,non db owner not  interception error
![image](https://github.com/matrixorigin/matrixone/assets/113406637/13470f5d-4ed6-4e90-8fa5-1def8d842943)
<img width="850" alt="企业微信截图_bf7bcec3-84fa-4a3b-a40d-286aaaa2c04f" src="https://github.com/matrixorigin/matrixone/assets/113406637/e26e7af5-ae2e-4648-adac-ea4b27ad2316">

![image](https://github.com/matrixorigin/matrixone/assets/113406637/f569d3da-b78a-4950-8621-dc5851041669)

### Steps to Reproduce

```Markdown
-- alter set mysql_compatibility_mode:sys account non moadmin user
create user alter_user1 identified by '123';
create role role1;
grant create database on account * to role1;
grant role1 to alter_user1;
create user alter_user2 identified by '123';
grant role1 to alter_user2;
-- @session:id=6&user=sys:alter_user1:role1&password=123
create database alter_db1;
alter database alter_db1 set mysql_compatibility_mode = '0.9.0';
select version();
-- @session
-- @session:id=7&user=sys:alter_user2:role1&password=123
alter database alter_db1 set mysql_compatibility_mode = '0.9.1';
select version();
-- @session
```

**Comment by heni02** [comment]
@YANGGMM plz confirm this issue

**Comment by heni02** [comment]
The second point above2  I found role2 to user2 not role1 to user2 ,it is correct:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/1cff1326-c0ef-46d3-9a54-861b10557738)

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
<img width="865" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/aaa3d085-e3d0-43ee-90f7-9e604fde4329">

**Comment by heni02** [comment]
case problem ,confirm, closed
https://github.com/matrixorigin/matrixone/pull/11552
