### ISSUE TITLE
[Bug]: outfile result error

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#11361]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): daaad8ea305d6454e55611f3f18af6b781f3b724
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> create table t1(a int);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t1 values(1);
Query OK, 1 row affected (0.02 sec)

mysql> select * from t1;
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.02 sec)
mysql> select * from t1 into outfile '/xxx/1.csv';
Empty set (0.00 sec)

mysql> select * from t1 into outfile '/xxx/1.csv';
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql> insert into t1 values(2);
Query OK, 1 row affected (0.03 sec)

mysql> select * from t1 into outfile '/xxx/1.csv';
+------+
| a    |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.00 sec)

csv 仅仅只有数据1 没有后面插入的数据 2
```

### Expected Behavior

```
csv 文件中包含 数据1和2
```
_No response_

**Comment by YANGGMM** [comment]
插入到同一个文件应该报错， 修改后：
mysql> select * from t1 into outfile '/Users/yangzhao/Desktop/7.csv';
Empty set (0.00 sec)

mysql> 
mysql> select * from t1 into outfile '/Users/yangzhao/Desktop/7.csv';
ERROR 1105 (HY000): open /Users/yangzhao/Desktop/7.csv: file exists
mysql> 
mysql> 
mysql> select * from t1 into outfile '/Users/yangzhao/Desktop/7.csv';
ERROR 1105 (HY000): open /Users/yangzhao/Desktop/7.csv: file exists
mysql> 
mysql> 
mysql> select * from t1 into outfile '/Users/yangzhao/Desktop/7.csv';
ERROR 1105 (HY000): open /Users/yangzhao/Desktop/7.csv: file exists

**Comment by YANGGMM** [comment]
<img width="808" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/38753d99-87eb-4f5d-8270-fef81aae886b">

**Comment by tianyahui-python** [comment]
test done
