### ISSUE TITLE
[Bug]: Occasionally xxx.blk is not found error during BVT tests causing test failures

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11379]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
maybe related to #10763, not sure.
```

### Actual Behavior

<img width="1430" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/33e33a64-e155-4f23-bd64-c9be5e2d02ef">

job link：https://github.com/matrixorigin/matrixone/actions/runs/5927458103/job/16071016431

Log： 
[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12403710/1-cn-e2e-linux-x86-reports.zip)

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/5933343830/job/16088639529?pr=11364

[1-cn-e2e-linux-x86-reports (1).zip](https://github.com/matrixorigin/matrixone/files/12404087/1-cn-e2e-linux-x86-reports.1.zip)

**Comment by aptend** [comment]
this file was not deleted by GC worker in TN

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6007038549/job/16292523489?pr=11512

**Comment by aptend** [comment]
repro with [logs added](https://github.com/aptend/matrixone/pull/43/files#diff-6d22078db63ca9c9ab2e2993404b26986918b776429dda9f1b4af83e5ff481f6) 

[mo-service.log.zip](https://github.com/matrixorigin/matrixone/files/12472212/mo-service.log.zip)

https://github.com/aptend/matrixone/actions/runs/5961168665/job/16331442041

MO wrote 147 query_result_meta/xxx.blk files and deleted none.

I still doubt that `last_query_id(-2)` fetched wrong uuid

**Comment by aptend** [comment]
> repro with [logs added](https://github.com/aptend/matrixone/pull/43/files#diff-6d22078db63ca9c9ab2e2993404b26986918b776429dda9f1b4af83e5ff481f6)
> 
> [mo-service.log.zip](https://github.com/matrixorigin/matrixone/files/12472212/mo-service.log.zip)
> 
> https://github.com/aptend/matrixone/actions/runs/5961168665/job/16331442041
> 
> MO wrote 147 query_result_meta/xxx.blk files and deleted none.
> 
> I still doubt that `last_query_id(-2)` fetched wrong uuid
```json
{"level":"ERROR","time":"2023/08/30 04:00:56.218651 +0000","caller":"fileservice/local_fs.go:338","msg":"error: file query_result_meta/sys_d8fb97e7-e30e-11ed-8d80-d6aeb943c8b4.blk is not found"}
{"level":"ERROR","time":"2023/08/30 04:00:56.218690 +0000","caller":"frontend/compiler_context.go:730","msg":"error: result file query_result_meta/sys_d8fb97e7-e30e-11ed-8d80-d6aeb943c8b4.blk not found"}
```
`d8fb97e7-e30e-11ed-8d80-d6aeb943c8b4` was never written by the frontend, but it was queried here.

https://github.com/matrixorigin/matrixone/blob/3d0803e49df251adf835e0da6a2d8803f4c31e18/pkg/sql/plan/function/func_unary.go#L893-L895

it sees that uuid is fetech from `SessionInfo.QueryId`, @daviszhen pls take a look

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/6131996346/job/16642471008?pr=11721

[multi-cn-e2e-push-docker-compose-log-pessimistic.zip](https://github.com/matrixorigin/matrixone/files/12566327/multi-cn-e2e-push-docker-compose-log-pessimistic.zip)

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by sukki37** [comment]
not repro for a long time, close
