### ISSUE TITLE
[Bug]: cte recursive: select list and column names list have different column counts not reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11374]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e4f3c5e3ed66cebb88c0e0bd2bc4070f95a7dde3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
mo : with as multi cte which select columns more than cte_8 two columns not reported error message:
<img width="1437" alt="企业微信截图_b3bbf47e-f7f7-4d8c-854b-74ea65b647a4" src="https://github.com/matrixorigin/matrixone/assets/113406637/6db44c93-e6e9-409f-856c-3661f0be0d2b">
but with as singe cte can reported :
<img width="1434" alt="企业微信截图_98a7824e-a993-4bbf-8d17-15f5c0a9db9f" src="https://github.com/matrixorigin/matrixone/assets/113406637/f8149267-bfa4-426c-abbf-c21b74e16cda">

mysql reported error message:
mysql> with non_cte_8(manager_id,name) as(SELECT a.manager_id, a.id,a.name AS job_name FROM emp a), non_cte_9(id,name) as(SELECT m.id, m.name FROM employees_mgr m WHERE m.name != "lucky") select * FROM non_cte_8 a JOIN non_cte_9 b ON a.manager_id = b.id ORDER BY  a.manager_id;
ERROR 1353 (HY000): In definition of view, derived table or common table expression, SELECT list and column names list have different column counts

### Steps to Reproduce
ddl：
CREATE TABLE emp(id INT PRIMARY KEY NOT NULL,name VARCHAR(100) NOT NULL,manager_id INT NULL,INDEX (manager_id),FOREIGN KEY (manager_id) REFERENCES employees_mgr(id));
INSERT INTO emp VALUES(333, "总经理", NULL), (198, "副总1", 333), (692, "副总2", 333),(29, "主任1", 198),(4610, "职员1", 29),(72, "职员2", 29),(123, "主任2", 692);

create table employees_mgr(id int primary key not null,name varchar(25));
insert into employees_mgr values(333,'ami'),(198,'lucky'),(29,'jack'),(692,'sammi');

 with non_cte_8(manager_id,name) as(SELECT a.manager_id, a.id,a.name AS job_name FROM emp a), non_cte_9(id,name) as(SELECT m.id, m.name FROM employees_mgr m WHERE m.name != "lucky") select * FROM non_cte_8 a JOIN non_cte_9 b ON a.manager_id = b.id ORDER BY  a.manager_id;

**Comment by heni02** [comment]
@iamlinjunhong plz confirm

**Comment by iamlinjunhong** [comment]
无进度，在看其他问题

**Comment by heni02** [comment]
confirm,closed
commit id:2f44ddf6843233883121cc92bb015d1975d8cfb5
<img width="1546" alt="企业微信截图_bd71e28e-ff33-4c84-8d0f-18c528702294" src="https://github.com/matrixorigin/matrixone/assets/113406637/9e085b58-9820-4faf-8b3a-11eb5a3bf152">

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
