### ISSUE TITLE
[Bug]: cte recursive: recursive_query limit not effective

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11375]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e4f3c5e3ed66cebb88c0e0bd2bc4070f95a7dde3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo：
<img width="1414" alt="企业微信截图_f42a2506-2c31-4fec-94b2-39840251972a" src="https://github.com/matrixorigin/matrixone/assets/113406637/24d035eb-cd33-4584-a88a-03abd7d7cb6a">

mysql：
<img width="1418" alt="企业微信截图_aff6801e-4678-428b-b72b-6b6507d0aeae" src="https://github.com/matrixorigin/matrixone/assets/113406637/11628e6c-5eed-4944-9972-ac2987734b38">

### Steps to Reproduce

```Markdown
CREATE TABLE emp(id INT PRIMARY KEY NOT NULL,name VARCHAR(100) NOT NULL,manager_id INT NULL,INDEX (manager_id),FOREIGN KEY (manager_id) REFERENCES employees_mgr(id));
INSERT INTO emp VALUES(333, "总经理", NULL), (198, "副总1", 333), (692, "副总2", 333),(29, "主任1", 198),(4610, "职员1", 29),(72, "职员2", 29),(123, "主任2", 692);

with recursive cte_ab_8(id,manager_id,name) as(select p.id,p.manager_id,p.name from emp p where manager_id is null union all select p.id,p.manager_id,p.name from emp p join cte_ab_8 c on p.manager_id= c.id limit 5) select * from cte_ab_8;
```

**Comment by heni02** [comment]
@iamlinjunhong  plz confirm this issue

**Comment by iamlinjunhong** [comment]
已提交pr

**Comment by heni02** [comment]
confirm,closed
commit id: 2f44ddf6843233883121cc92bb015d1975d8cfb5
![Uploading 企业微信截图_5bf1b6a1-4860-4772-84ea-061c46c122db.png…]()

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
