### ISSUE TITLE
[Bug]: Window function's case fails causing bvt failure

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11372]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

LOG：[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/12396632/multi-cn-e2e-push-docker-compose-log.zip)

https://github.com/matrixorigin/matrixone/actions/runs/5926738576/job/16068741789?pr=11364

<img width="1047" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/aa1d1e47-8d86-43a5-9ab6-e68cd845cf9e">

**Comment by iamlinjunhong** [comment]
已提交 pr
