### ISSUE TITLE
[STMT-SELECT]:  ERROR 1105 (HY000): unknown error:[42804]illegal expression 'a >= 2 and a <= 3 = 0'

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1138]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t1 (a int);
Query OK, 0 rows affected (0.34 sec)

mysql> insert into t1 values (0),(1),(NULL);
Query OK, 3 rows affected (0.07 sec)

mysql> select * from t1 where not a between 2 and 3;
ERROR 1105 (HY000): unknown error:[42804]illegal expression 'a >= 2 and a <= 3 = 0'

### Steps to Reproduce

```markdown
DROP TABLE IF EXISTS t1;
create table t1 (a int);
insert into t1 values (0),(1),(NULL);
select * from t1 where not a between 2 and 3;
```

**Comment by m-schen** [comment]
error happens in rewriteAST.
rewrite between Expr in a wrong way.

**Comment by m-schen** [comment]
fix it in branch main.

**Comment by lignay** [comment]
Verified on 0ca539490e8f5b8adce6210d19ef53d0f83d8a81
