### ISSUE TITLE
[Bug]: Error occurs when querying metadata table.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11392]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9a4bff2fba004aa11dd0c993350581e3f94f7a91
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="963" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a680bd2b-e23b-42e4-8ac7-49f286ab357c">

[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12405410/1-cn-e2e-linux-x86-reports.zip)
[e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12405412/e2e-linux-x86-reports.zip)
[multi-cn-e2e-with-proxy-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12405414/multi-cn-e2e-with-proxy-linux-x86-reports.zip)

### Expected Behavior

<img width="583" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3e17c436-0e38-459a-bdbc-d754694b04f0">

### Steps to Reproduce

```Markdown
case path：${path}/matrixone/test/distributed/cases/ddl/alter_table_rename_column.sql   [row:220]
```

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
Local non recurrence

**Comment by qingxinhome** [comment]
Local non recurrence

**Comment by qingxinhome** [comment]
Local non recurrence

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by qingxinhome** [comment]
not working on it
