### ISSUE TITLE
[Enhancement]: Rename DN to TN

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#11397]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
MatrixOne's data node doesn't actually represent its true function, so we decided to rename it to TN(transaction node). 
We will have quite some code and doc related to that, and needs to be updated before 1.0 release. And this update needs to be cherry picked to 1.0 branch as well.

Things might concern:

1. system configuration toml files. 
2. error code.
3. real code. 

```
<img width="1598" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/b41703e4-49d8-4a13-8a46-2b9f5d2d79c3">

**Comment by aylei** [comment]
I suggest TN accept the legacy `[dn]` configuration if `[tn]` is not set to be compatible with older version tools like mo-operator

**Comment by reusee** [comment]
pr sent.
