### ISSUE TITLE
[Bug]: changing metadata table fields causes storage compatibility tests fail.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11406]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d83d19cfad355e4184c90d453ea25685f4994df7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="988" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/799d1608-d9c5-4339-b0a5-e00407bdb3ac">

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5941864141/job/16113874360

### Expected Behavior

<img width="445" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a44cd609-c6f3-4285-86d4-c9d55769ac19">

**Comment by daviszhen** [comment]
@qingxinhome  涉及到cn、存储 兼容性相关的。

**Comment by qingxinhome** [comment]
该问题是由于在v0.8.0版本中系统视图information_schema.column的is_nullable字段值含义取反了，属于v0.8.0版本的bug，
v1.1.0中修复了该bug，也就是说v1.1.0中结果是正确的，因此不需要兼容v0.8.0版本错误结果，需要对v0.8.0版本打补丁

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen @sukki37

**Comment by aressu1985** [comment]
fixed

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
