### ISSUE TITLE
[Bug]: Result is incorrect in SELECT with order by 2

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1140]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);
select spID s, userID u from t1 order by 2 desc;
+------+------+
| s    | u    |
+------+------+
|    1 |    1 |
+------+------+

### Expected Behavior

+------+------+
| s    | u    |
+------+------+
|    5 |   11 |
|    4 |    6 |
|    3 |    3 |
|    2 |    2 |
|    1 |    1 |
|    2 |    1 |
|    1 |    1 |
+------+------+

**Comment by m-schen** [comment]
I'm not sure what does `order by 2` mean for.

**Comment by m-schen** [comment]
order by Number
Number means index of select column, and start from 1. And default sort rule is ASC.

For example:
`select a, b from tbl order by 1` means `select a, b from tbl order by 1 a asc`

**Comment by fengttt** [comment]
Verified, fixed.
