### ISSUE TITLE
[Bug]: tpcc slower and slower

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#11403]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d83d19cfad355e4184c90d453ea25685f4994df7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run tpcc 10-10 in standalone mode, we've encountered performance degrades:

1. Reduced from 12,000 to 3,000 after a few hours in 129.
2. Despite attempting a restart to resolve the problem, we've observed that the TPMC remains at a significantly low level.

**Comment by sukki37** [comment]
maybe related to #9474.

**Comment by aptend** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/9474.
