### ISSUE TITLE
[Bug]: Instance crashed in a SELECT statement with GROUP BY and ORDER BY

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1141]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

select spID , userID from t1 group by userID order by userID;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by broccoliSpicy** [comment]
mysql default mode doesn't support this,

mysql> CREATE TABLE t1 (spID int,userID int,score smallint);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (1,1,1);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (2,2,2);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (2,1,4);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (3,3,3);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (1,1,5);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (4,6,10);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (5,11,99);
Query OK, 1 row affected (0.00 sec)

mysql> select spID , userID from t1 group by userID order by userID;
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.t1.spID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
