### ISSUE TITLE
[Bug]: proxy : mysql client login mo which is user?key=values  ,show backend servers results error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11413]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e23b7116
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

label mode read login in mo ,show backend servers results include other labels information, it is not expected
<img width="1090" alt="企业微信截图_285a0745-31ec-4549-8ff5-f40ff192ca96" src="https://github.com/matrixorigin/matrixone/assets/113406637/db7a46dc-e392-4808-a272-552fa06354f5">

select node_id, host, user from information_schema.processlist results succeed
<img width="968" alt="企业微信截图_66d1cef5-eb29-42de-a0d3-cd8e666de1b3" src="https://github.com/matrixorigin/matrixone/assets/113406637/8c812105-8272-4035-ba70-35d9a52ab959">
<img width="927" alt="企业微信截图_119c5779-1eb2-4234-95b7-761f9c76b0a7" src="https://github.com/matrixorigin/matrixone/assets/113406637/e6b53c78-bf32-44a2-b2f0-d9cae5d38d6a">
<img width="1007" alt="企业微信截图_0f28c1c6-e688-4610-8268-c0e0721c44ba" src="https://github.com/matrixorigin/matrixone/assets/113406637/377a5262-c47e-47e9-ad79-a6e98290481b">

**Comment by volgariver6** [comment]
merged

**Comment by heni02** [comment]
confirm,closed
commit id :nightly-ec020463
![image](https://github.com/matrixorigin/matrixone/assets/113406637/1045d34b-8bfa-4c0c-9bd3-f9a22be0699d)
<img width="1229" alt="企业微信截图_c9117b57-5553-4641-b4cd-055e4e439dc0" src="https://github.com/matrixorigin/matrixone/assets/113406637/0c0ad81b-918a-4d92-b9c8-17cd55874e33">
