### ISSUE TITLE
[Bug]: golang连接MatrixOne时不支持limit传参，报错1149 (HY000): SQL syntax error: only int64 support in limit/offset clause

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixone#11426]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):v0.8.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "root:111@tcp(192.168.110.248:6001)/cloud_device")
	if err != nil {
		fmt.Printf("open database failed: err[%v]", err)
		return
	}

	_, err = db.Query("select * from device_info_2 limit ? offset ?", int64(100), int64(0))
	if err != nil {
		fmt.Printf("select failed: err[%v]", err)
		return
	}
}
报错如下：1149 (HY000): SQL syntax error: only int64 support in limit/offset clause

**Comment by YANGGMM** [comment]
prepare stmt1 from select * from device_info_2 limit ? offset ?;

**Comment by YANGGMM** [comment]
have fixed it, plz test
