### ISSUE TITLE
[Bug]: INSERT failed because of auto increment column

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1142]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE animals (id INT NOT NULL AUTO_INCREMENT primary key, name CHAR(30) NOT NULL);
INSERT INTO animals (name) VALUES
('dog'),('cat'),('penguin'),
 ('lax'),('whale'),('ostrich');
ERROR 1105 (HY000): unknown error:[42611]Field 'id' doesn't have a default value

### Expected Behavior

Query OK, 6 rows affected (0.02 sec)
Records: 6  Duplicates: 0  Warnings: 0

**Comment by JinHai-CN** [comment]
'AUTO INCREMENT' is not supported until matrixone supports distributed transaction.

**Comment by fengttt** [comment]
This is too old, please close.
