### ISSUE TITLE
[Bug]: foreign key is one of primary key, delete 0 row main table, select non main table error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11425]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e4f3c5e3ed66cebb88c0e0bd2bc4070f95a7dde3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

foreign key is one of pk,on delete /update SET NULL 
ddl：
create table fk_01(col1 decimal(38,3),col2 char(25),col3 int,col4 date,primary key(col1,col3,col4));
create table fk_02(col1 decimal(38,3),col2 char(25),col3 int,col4 date,constraint ck foreign key(col1) REFERENCES fk_01(col1) on delete SET NULL on update SET NULL);
insert into fk_01 values(23.10,'a',20,'2022-10-01'),(23.10,'a',21,'2022-10-01'),(23.10,'a',20,'2022-10-02');
insert into fk_02 values(23.10,'a',20,'2022-10-01'),(23.10,'a',21,'2022-10-01'),(23.10,'a',20,'2022-10-02');
insert into fk_02 values(23.10,'a',20,'2022-10-01'),(0.1,'b',22,'2022-10-01'),(23.10,'c',30,'2022-10-02');
insert into fk_02 values(0.001,'b',20,'2022-10-01'),(4.5,'a',21,'2022-10-01'),(56,'a',20,'2022-10-02');
select * from fk_01;
select * from fk_02;
update fk_02 set col3=19 where col3=20;
select * from fk_02;
delete from fk_01  where col3=20;
select * from fk_01;
select * from fk_02;

after ddelete from fk_01  where col3=20 0 rows ,select fk_02 result error
[SQL STATEMENT]: select * from fk_02;
[EXPECT RESULT]:
col1    col2    col3    col4
null    a    19    2022-10-01
null    a    21    2022-10-01
null    a    19    2022-10-02
[ACTUAL RESULT]:
col1    col2    col3    col4
null    a    21    2022-10-01
null    a    19    2022-10-01
null    a    19    2022-10-02
null    a    21    2022-10-01
null    a    19    2022-10-01
null    a    19    2022-10-02

### Steps to Reproduce

```Markdown
create table fk_01(col1 decimal(38,3),col2 char(25),col3 int,col4 date,primary key(col1,col3,col4));
create table fk_02(col1 decimal(38,3),col2 char(25),col3 int,col4 date,constraint ck foreign key(col1) REFERENCES fk_01(col1) on delete SET NULL on update SET NULL);
insert into fk_01 values(23.10,'a',20,'2022-10-01'),(23.10,'a',21,'2022-10-01'),(23.10,'a',20,'2022-10-02');
insert into fk_02 values(23.10,'a',20,'2022-10-01'),(23.10,'a',21,'2022-10-01'),(23.10,'a',20,'2022-10-02');
insert into fk_02 values(23.10,'a',20,'2022-10-01'),(0.1,'b',22,'2022-10-01'),(23.10,'c',30,'2022-10-02');
insert into fk_02 values(0.001,'b',20,'2022-10-01'),(4.5,'a',21,'2022-10-01'),(56,'a',20,'2022-10-02');
select * from fk_01;
select * from fk_02;
update fk_02 set col3=19 where col3=20;
select * from fk_02;
delete from fk_01  where col3=20;
select * from fk_01;
select * from fk_02;
```

**Comment by ouyuanning** [comment]
已复现。
当满足外键约束是多个重复行的时候。子表更新了多次。
需要在外键的join节点后面或者table_scan后面，增加一个agg节点把这些多余的行筛掉。下周处理

**Comment by heni02** [comment]
confirm,closed
commit id:2f44ddf6843233883121cc92bb015d1975d8cfb5
<img width="574" alt="企业微信截图_275a6db2-a09c-448e-b23f-8e839ab7054f" src="https://github.com/matrixorigin/matrixone/assets/113406637/b85700be-bbb2-4ca0-a289-330b955f7e53">
