### ISSUE TITLE
[Bug]:  some catalog tables can not be upgraded succeeded from 0.8 to 1.0

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11437]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1.0-rc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

after mo upgraded from 0.8 to 1.0 ,lots bvt case are failed.
2023-08-23 09:52:09 ERROR Executor:224 - [ACTUAL RESULT]:
no such table mo_catalog.mo_table_partitions
2023-08-23 09:52:09 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/ddl/hash_key_partition.sql][row:3][insert into p_table_01 values (1,'mod',78.9),(2,'proto',0.34),(3,'mod',6.5),(4,'mode',9.0),(5,'make',662.9),(6,'io',88.92);] was executed failed, con[id=0, user=dump, ***
2023-08-23 09:52:09 ERROR Executor:223 - [EXPECT RESULT]:
null
2023-08-23 09:52:09 ERROR Executor:224 - [ACTUAL RESULT]:
no such table hash_key_partition.p_table_01
2023-08-23 09:52:09 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/ddl/hash_key_partition.sql][row:4][select * from `%!%p0%!%p_table_01`;] was executed failed, con[id=0, user=dump, ***
2023-08-23 09:52:09 ERROR Executor:223 - [EXPECT RESULT]:
col1    col2    col3
5    make    662.90
2023-08-23 09:52:09 ERROR Executor:224 - [ACTUAL RESULT]:
SQL parser error: table "%!%p0%!%p_table_01" does not exist
2023-08-23 09:52:09 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/ddl/hash_key_partition.sql][row:5][select * from `%!%p1%!%p_table_01`;] was executed failed, con[id=0, user=dump, ***
2023-08-23 09:52:09 ERROR Executor:223 - [EXPECT RESULT]:
col1    col2    col3
2    proto    0.34
2023-08-23 09:52:09 ERROR Executor:224 - [ACTUAL RESULT]:
SQL parser error: table "%!%p1%!%p_table_01" does not exist
2023-08-23 09:52:09 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/ddl/hash_key_partition.sql][row:6][select * from `%!%p2%!%p_table_01`;] was executed failed, con[id=0, user=dump, ***
2023-08-23 09:52:09 ERROR Executor:223 - [EXPECT RESULT]:
col1    col2    col3
1    mod    78.90
3    mod    6.50
4    mode    9.00
2023-08-23 09:52:09 ERROR Executor:224 - [ACTUAL RESULT]:
SQL parser error: table "%!%p2%!%p_table_01" does not exist
2023-08-23 09:52:09 ERROR Executor:221 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/ddl/hash_key_partition.sql][row:7][select * from `%!%p3%!%p_table_01`;] was executed failed, con[id=0, user=dump, ***
2023-08-23 09:52:09 ERROR Executor:223 - [EXPECT RESULT]:
col1    col2    col3
6    io    88.92

this problem is caused by that the new system tables like mo_stage, mo_patition can not be created successfully , ant it is related by issue #10853

**Comment by xzxiong** [comment]
@qingxinhome  ptal,

**Comment by qingxinhome** [comment]
Local validation mo upgraded from 0.8 to 1.0, unable to start, report error ， @xzxiong @aressu1985 @domingozhang @daviszhen 
![image](https://github.com/matrixorigin/matrixone/assets/70939751/bf5e7658-cb53-40d3-8d17-151167547d65)

**Comment by xzxiong** [comment]
本地standalone，0.8.0 升级 1.0.0rc 时，upgrade 遇到报错: `not supported: alter table for cluster table`  @gavinyue 
![image](https://github.com/matrixorigin/matrixone/assets/3927687/f9d992be-3476-48bb-84af-bdd1368fbe13)

**Comment by xzxiong** [comment]
@qingxinhome 
![企业微信截图_0b1fdf98-8ac4-42fa-8f1b-87506ab985a7](https://github.com/matrixorigin/matrixone/assets/3927687/f603afe8-a039-47d1-942d-bf4c98bc125a)

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
PR submitted

**Comment by qingxinhome** [comment]
This issue has been fixed, please verify and test @xzxiong @aressu1985 @Ariznawlll @gavinyue

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
从 0.8 升级到 1.0 依然存在问题，DN启动失败：
commit id:  from daf8679 to 6c08c6a

sudong@sudongdeMacBook-Pro mo-cloud % kubectl -n mo-cpt-from-08 get pod          
NAME        READY   STATUS             RESTARTS       AGE
cpt-dn-0    0/1     CrashLoopBackOff   17 (41s ago)   63m
cpt-log-0   1/1     Running            0              64m
cpt-log-1   1/1     Running            0              64m
cpt-log-2   1/1     Running            0              64m

报错如下：
{"level":"INFO","time":"2023/08/31 02:25:51.359092 +0000","name":"rpc-client[hakeeper-client([])]","caller":"morpc/client.go:379","msg":"gc idle backends task started"}
{"level":"INFO","time":"2023/08/31 02:25:51.365718 +0000","name":"rpc-client[hakeeper-client([])]","caller":"morpc/client.go:343","msg":"print active backends task started"}
{"level":"INFO","time":"2023/08/31 02:25:51.365748 +0000","name":"rpc-client[hakeeper-client([])]","caller":"morpc/client.go:379","msg":"gc idle backends task started"}
{"level":"INFO","time":"2023/08/31 02:25:51.386915 +0000","caller":"db/open.go:148","msg":"open-tae","operation":"replay","operand":"checkpoints","cost":"12.428084ms","checkpointed":"0-0"}
{"level":"INFO","time":"2023/08/31 02:25:51.389127 +0000","caller":"logservicedriver/truncate.go:116","msg":"Logservice Driver: Get Truncate 1195024"}
{"level":"INFO","time":"2023/08/31 02:25:51.389175 +0000","caller":"logservicedriver/replay.go:62","msg":"truncated 1195024"}
panic: ExpectedEOB

goroutine 350 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).replayDelete(0x2?, 0x2?, {0x26aeae0?, 0x4000e738f0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:199 +0xf8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).replayDataCmds(0x0?, 0x7?, {0x2bc7680?, 0x4002eb8f50?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:185 +0x40
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).prepareCmd(0x4001622550, {0x2c17eb0, 0x4001886e10})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:117 +0x290
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*replayTxnStore).prepareCommit(0x4001622550, {0x2c55a18, 0x400056d180})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/replaystore.go:82 +0xc0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PrepareCommit(0x400056d180)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:323 +0x80
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreparCommit(0x16072f0?, {0x2c55a18, 0x400056d180})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:331 +0x2c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare(0x0?, 0x40014cd020, {0x0, 0x0, 0x0, 0x0, 0x19, 0x69, 0xa1, 0x8c, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:385 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare1PC(0x4002ee5860?, 0x40014cd020?, {0x0, 0x0, 0x0, 0x0, 0x19, 0x69, 0xa1, 0x8c, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:410 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).dequeuePreparing(0x4002ee5860, {0x4004798000?, 0x1, 0x3e8})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:498 +0x218
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1a4
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xf0

**Comment by aressu1985** [comment]
fixed

**Comment by daviszhen** [comment]
今天还没看。

**Comment by daviszhen** [comment]
现象是在1.0-rc中，创建带分区的表有问题。

```
mysql> use db1;
Database changed
mysql> CREATE TABLE t1 (
    -> col1 INT NOT NULL AUTO_INCREMENT,
    -> col2 DATE NOT NULL,
    -> col3 INT PRIMARY KEY
    -> )
    -> PARTITION BY KEY(col3)
    -> PARTITIONS 4;
ERROR 1146 (HY000): no such table mo_catalog.mo_table_partitions
mysql> show tables from mo_catalog;
```

**Comment by daviszhen** [comment]
找到问题的case。具体原因再查。

**Comment by daviszhen** [comment]
原因是alter table 目前不支持cluster by。

<img width="1293" alt="截屏2023-09-06 10 06 45" src="https://github.com/matrixorigin/matrixone/assets/60595215/440e7c20-0a22-451b-af81-61cb92db42ad">

**Comment by daviszhen** [comment]
找到直接原因。batch 被改了。
具体的原因还在查。

**Comment by daviszhen** [comment]
看起来是触发了某个条件。导致Write接口内部做了清理。

<img width="1827" alt="企业微信截图_abfcb813-0324-42df-b911-b96ae8f04ad0" src="https://github.com/matrixorigin/matrixone/assets/60595215/ef870dfd-addc-434e-a9c6-ac00aca522f6">

**Comment by daviszhen** [comment]
相关的日志。
```

zzzz> 0 0xc00b562580 false [__mo_rowid raw_item node_uuid node_type span_id trace_id logger_name timestamp level caller message extra err_code error stack span_name parent_span_id start_time end_time duration resource span_kind statement_id __mo_fake_pk_col __mo_cbkey_009timestamp008raw_item]
{"level":"WARN","time":"2023/09/07 10:59:21.705821 +0800","caller":"objectio/writer.go:183","msg":"object io: no block needs to be written"}
uuuu> 0xc009d53b00 [table_id col_name col_index offset step __mo_cpkey_col]
goroutine 881 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x7a
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch(0xc00af49b80, 0xc009d53b00)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/process/process.go:254 +0x1f6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).dumpBatchLocked(0xc00a310dc0, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn.go:222 +0x143c
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).dumpBatch(0xc00a310dc0, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn.go:136 +0xc5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Write(0xc00993f2c0, {0x103e5ea58, 0xc00bc12ba0}, 0xc00bc25b00)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn_table.go:1138 +0x66b
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.Call(0x6, 0xc00bbcf600, {0x1037ecea0, 0xc00bbf6ec0}, 0x1, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/colexec/insert/insert.go:166 +0x10dd
github.com/matrixorigin/matrixone/pkg/vm.fubarRun({0xc00bbd6c80, 0x4, 0x4}, 0xc00bbcf600, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/vm.go:67 +0x22c
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc00bbd6c80, 0x4, 0x4}, 0xc00bbcf600)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/vm.go:59 +0xfa
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc00bc290c0, {0x103e4c370, 0xc00bbbb2f0}, 0xc00bbcf600)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/pipeline/pipeline.go:89 +0x689
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc00bc0a410, 0xc00afea500)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:88 +0x3f8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc00bc0a410, 0xc00afea500, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:434 +0x22e7
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00bc0a410, 0xc00afea500)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:187 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc00afea500, 0xc00bc0a410)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:284 +0x285
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:434 +0x47
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf8
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85
{"level":"WARN","time":"2023/09/07 10:59:21.777763 +0800","caller":"objectio/writer.go:183","msg":"object io: no block needs to be written"}
uuuu> 0xc00b562000 [raw_item node_uuid node_type span_id trace_id logger_name timestamp level caller message extra err_code error stack span_name parent_span_id start_time end_time duration resource span_kind statement_id __mo_fake_pk_col __mo_cbkey_009timestamp008raw_item]
goroutine 881 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x7a
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch(0xc00af49b80, 0xc00b562000)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/process/process.go:254 +0x1f6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).dumpBatchLocked(0xc00a310dc0, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn.go:222 +0x143c
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).dumpBatch(0xc00a310dc0, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn.go:136 +0xc5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Write(0xc00993f2c0, {0x103e5ea58, 0xc00bc12ba0}, 0xc00bc25b00)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn_table.go:1138 +0x66b
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.Call(0x6, 0xc00bbcf600, {0x1037ecea0, 0xc00bbf6ec0}, 0x1, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/colexec/insert/insert.go:166 +0x10dd
github.com/matrixorigin/matrixone/pkg/vm.fubarRun({0xc00bbd6c80, 0x4, 0x4}, 0xc00bbcf600, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/vm.go:67 +0x22c
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc00bbd6c80, 0x4, 0x4}, 0xc00bbcf600)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/vm.go:59 +0xfa
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc00bc290c0, {0x103e4c370, 0xc00bbbb2f0}, 0xc00bbcf600)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/pipeline/pipeline.go:89 +0x689
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc00bc0a410, 0xc00afea500)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:88 +0x3f8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc00bc0a410, 0xc00afea500, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:434 +0x22e7
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00bc0a410, 0xc00afea500)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:187 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc00afea500, 0xc00bc0a410)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:284 +0x285
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:434 +0x47
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf8
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85
uuuu> 0xc00b562580 [raw_item node_uuid node_type span_id trace_id logger_name timestamp level caller message extra err_code error stack span_name parent_span_id start_time end_time duration resource span_kind statement_id __mo_fake_pk_col __mo_cbkey_009timestamp008raw_item]
goroutine 881 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x7a
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch(0xc00af49b80, 0xc00b562580)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/process/process.go:254 +0x1f6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).dumpBatchLocked(0xc00a310dc0, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn.go:222 +0x143c
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).dumpBatch(0xc00a310dc0, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn.go:136 +0xc5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Write(0xc00993f2c0, {0x103e5ea58, 0xc00bc12ba0}, 0xc00bc25b00)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/txn_table.go:1138 +0x66b
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.Call(0x6, 0xc00bbcf600, {0x1037ecea0, 0xc00bbf6ec0}, 0x1, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/colexec/insert/insert.go:166 +0x10dd
github.com/matrixorigin/matrixone/pkg/vm.fubarRun({0xc00bbd6c80, 0x4, 0x4}, 0xc00bbcf600, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/vm.go:67 +0x22c
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc00bbd6c80, 0x4, 0x4}, 0xc00bbcf600)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/vm.go:59 +0xfa
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc00bc290c0, {0x103e4c370, 0xc00bbbb2f0}, 0xc00bbcf600)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/pipeline/pipeline.go:89 +0x689
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc00bc0a410, 0xc00afea500)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:88 +0x3f8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc00bc0a410, 0xc00afea500, 0x0)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:434 +0x22e7
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00bc0a410, 0xc00afea500)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:187 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc00afea500, 0xc00bc0a410)
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:284 +0x285
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
        /Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:434 +0x47
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf8
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85
{"level":"WARN","time":"2023/09/07 10:59:21.830427 +0800","caller":"objectio/writer.go:183","msg":"object io: no block needs to be written"}
yyyy> 0xc00b562580 true [] [] 0 
{"level":"ERROR","time":"2023/09/07 10:59:21.890737 +0800","caller":"compile/scope.go:69","msg":"error: internal error: panic runtime error: index out of range [0] with length 0: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:113\ngithub.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).GetSubBatch\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/container/batch/batch.go:203\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PartitionReader).Read\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/partition_reader.go:130\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/reader.go:571\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/engine/disttae/reader.go:571\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/vm/pipeline/pipeline.go:78\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:88\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:434\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/scope.go:187\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:284\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1\n\t/Users/pengzhen/Documents/GitHub/customer/matrixone1rc/pkg/sql/compile/compile.go:434\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/Users/pengzhen/go/src/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","span":{"trace_id":"8b4e05be-4d2a-11ee-85f9-acde48001122","kind":"statement"}}

```

**Comment by triump2020** [comment]
cause had been located

**Comment by daviszhen** [comment]
上午分析发现。
writes 中batch指针复制到partition_reader中inserts。
后续writes被dumpbatch 清理了后，partitionReader中inserts依然保持中对batch的引用。
导致后续读batch时，读了一个被清理掉的batch.

**Comment by daviszhen** [comment]
等 @triump2020 的修改

**Comment by daviszhen** [comment]
等 @triump2020 的修改

**Comment by daviszhen** [comment]
等 @triump2020 的修改

**Comment by triump2020** [comment]
改好了 ，等待main 的merge

**Comment by daviszhen** [comment]
等 @triump2020 的修改

**Comment by daviszhen** [comment]
pr已经提了。

**Comment by daviszhen** [comment]
pr review中。

**Comment by daviszhen** [comment]
pr 上存在 bvt case 的疑问。 喜亮再解决。

**Comment by daviszhen** [comment]
还在调整bvt case的问题。pr依据merge了。

**Comment by daviszhen** [comment]
pr #11889 会在 0.8 上启动后，登录会卡住。
<img width="902" alt="企业微信截图_f9713b03-1257-4c38-a12f-8f7d4aeb24ea" src="https://github.com/matrixorigin/matrixone/assets/60595215/3ec38968-2c6a-48ad-b236-97f078e59359">

**Comment by daviszhen** [comment]
注意的是：
1.0rc-hotfix 在0.8的数据上启动时，
在cn，tn的配置里面加上配置项目。
```
[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"

```
