### ISSUE TITLE
[Bug]: DN OOM during sysbench oltp delete test on distributed mode on TKE

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11430]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):mo-nightly-regression-20230823
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5953739200/job/16155947051

<img width="1422" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3d2d50a1-dbd1-4d31-a264-3b1cfee455fa">

dn mem usage:
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7c11c60a-f78a-4657-9b70-c8c10f330820">

log can be get from loki by namespace: mo-nightly-regression-20230823

### Steps to Reproduce

```Markdown
trying
```

**Comment by LeftHandCold** [comment]
<img width="1498" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/72b7f6b8-06b4-4b36-9905-5a8d58b55d8c">

**Comment by LeftHandCold** [comment]
It may be caused by the backend asynchronous task pnaic, the asynchronous flashing task is stopped, and the accumulation of memory data causes oom

**Comment by LeftHandCold** [comment]
not yet reproduced

**Comment by LeftHandCold** [comment]
not yet reproduced

**Comment by aressu1985** [comment]
update on 8.27
job link:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5985712951
<img width="1401" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/29edd8a6-9894-485b-a4a2-9270c2901a06">

<img width="1336" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b4f4c5f6-1a0a-4cb6-8cdd-a0c07cd25004">

<img width="973" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d79a0a62-fb18-44af-81f8-d9c7e85da86c">

**Comment by LeftHandCold** [comment]
<img width="1393" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/303bafc5-31a7-4ee9-8b81-a1fbbb76f40f">
跟之前的flush panic不是一个问题

**Comment by LeftHandCold** [comment]
panic的问题还没有复现，第二个oom可能需要flush优化

**Comment by LeftHandCold** [comment]
在看ckp oom的问题，没有更新

**Comment by LeftHandCold** [comment]
还在修改中

**Comment by LeftHandCold** [comment]
还在修改中

**Comment by LeftHandCold** [comment]
修改测试中

**Comment by LeftHandCold** [comment]
更新load-data case后，不会再出现多个大宽表（100列，200列）需要merge，所以没有出现oom的现象了，先降级。
