### ISSUE TITLE
[Bug]: Column alias doesn't work in SELECT statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1143]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3cb4f665fd393a383123bd12a67b34f0a76ceb28
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);
select userID as spID, spID from t1;
ERROR 1105 (HY000): unknown error:[42P09]alias 'spID' is ambiguous

### Expected Behavior

select userID as spID, spID from t1;
+------+------+
| spID | spID |
+------+------+
|    1 |    1 |
|    2 |    2 |
|    1 |    2 |
|    3 |    3 |
|    1 |    1 |
|    6 |    4 |
|   11 |    5 |
+------+------+

**Comment by m-schen** [comment]
it is same to issue #930
