### ISSUE TITLE
[Bug]:optimistic mode: the value of select count(*) is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11442]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):694e0b6a43f35091745ed45c0a602a86fe6d129e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="704" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5d9f91ee-71ce-4dd3-b9d7-dec788cbd313">

### Expected Behavior

the correct value of sql 'select count(*) from s3t_copy' is 30000.

### Steps to Reproduce

```Markdown
drop table if exists s3t;
create table s3t (a int, b int, c int, primary key(a, b));
insert into s3t select result, 2, 12 from generate_series(1, 30000, 1) g;
select count(*) from s3t;

begin;
CREATE TABLE `s3t_copy` (
`a` INT NOT NULL,
`b` INT NOT NULL,
`d` INT DEFAULT null,
`c` INT DEFAULT null,
PRIMARY KEY (`a`,`b`)
);
insert into s3t_copy(a, b, c) select a, b, c from s3t;
select count(*) from s3t_copy;
commit;
```

**Comment by ouyuanning** [comment]
待定位问题

**Comment by ouyuanning** [comment]
下周看

**Comment by ouyuanning** [comment]
写s3的数据，在查询的时候没有被读取回来（txn_table的Ranges方法提前return了）。

**Comment by triump2020** [comment]
@Ariznawlll   fixed.

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by Ariznawlll** [comment]
Waiting for the developer to remove the relevant tag and then i will close it.

**Comment by Ariznawlll** [comment]
Waiting for pr merge into the main branch.
