### ISSUE TITLE
[Bug]: cn service is not ready, retry later

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11451]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8404a1f1d48608d10a6ed56b94f84f3c8e355e95
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1254" alt="企业微信截图_2ad66f60-3f1d-4595-b5f1-0a63a905a852" src="https://github.com/matrixorigin/matrixone/assets/60595215/7c0c6c01-94af-4433-8832-989cb70840f9">

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
i am not sure i can reproduce it again.

1. setup a virtual machine
2. setup docker
3. change some configs
[diff.txt](https://github.com/matrixorigin/matrixone/files/12430251/diff.txt)

4. make compose

```

**Comment by volgariver6** [comment]
cannot reproduce it, maybe we should close it first, as we dont need to start a cluster in docker compose env for now.

**Comment by daviszhen** [comment]
先关了吧
