### ISSUE TITLE
[Enhancement]: S3 object read optimization/Distributed Cache

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11476]
### Is there an existing issue for enhancement?

- [x] I have checked the existing issues.

### What would you like to be added ?

Optimize S3 read behavior.

### Why is this needed ?

Schedule work on right CN nodes, so that we take advantage of locality.

In case of a disk cache miss, consider a remote cache lookup from another CN, or, ship read work to remote CN.

Esp, there maybe an optimization that when DN flush it keep the object in its disk cache.   When compact/merge, the CN worker may also keep the merged S3 in cache.    When another CN has a disk cache miss -- if the block is "recent", it should try to read from DN/merge CN before read S3.

**Comment by reusee** [comment]
I think this belongs to @volgariver6 since he implemented the distributed cache.

**Comment by volgariver6** [comment]
wait for file service enhancement https://github.com/matrixorigin/matrixone/issues/11569

**Comment by volgariver6** [comment]
done. dup with #6953
