### ISSUE TITLE
[Enhancement]: S3 read ordering

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11477]
### Is there an existing issue for enhancement?

- [x] I have checked the existing issues.

### What would you like to be added ?

Good read ordering may improve performance significantly once we have
runtime filter.

### Why is this needed ?

Let's use an example, select * from T order by x limit 10;

If we look at zonemap, read S3 objects according to order min of x -- only a few S3 blocks with probably raise the threshold of x and we can filter most of later S3 objects at run time.

**Comment by heni02** [comment]
1.2 commit:7bc191e 
statement_info行数51万
select * from statement_info order by request_at limit 1; 耗时0.38s

mysql> select * from statement_info order by request_at limit 1;
+--------------------------------------+----------------+--------------------------------------+---------+--------------------------------------+---------------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+-----------+-----------+------------+------------------------------------+----------------+------------+---------+-----------------+------------+--------------+
| statement_id                         | transaction_id | session_id                           | account | user                                 | host                | database | statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | statement_tag | statement_fingerprint | node_uuid                            | node_type | request_at                 | response_at                | duration | status  | err_code | error | exec_plan | rows_read | bytes_scan | stats                              | statement_type | query_type | role_id | sql_source_type | aggr_count | result_count |
+--------------------------------------+----------------+--------------------------------------+---------+--------------------------------------+---------------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+-----------+-----------+------------+------------------------------------+----------------+------------+---------+-----------------+------------+--------------+
| 018f702c-b1f1-7ad6-a4b7-aa74e1607220 |                | 018f702c-b121-7266-be3e-6d405d767242 | sys     | 29079eae-efab-435e-80ca-99ecc0788e25 | 10.143.203.51:33084 |          | /* 2 queries */
select
    						task_id,
							task_metadata_id,
							task_metadata_executor,
							task_metadata_context,
							task_metadata_option,
							task_parent_id,
							task_status,
							task_runner,
							task_epoch,
							last_heartbeat,
							result_code,
							error_msg,
							create_at,
							end_at
						from mo_task.sys_async_task where 1=1 AND task_status IN (1) order by task_id;
select
    						task_id,
							task_metadata_id,
							task_metadata_executor,
							task_metadata_context,
							task_metadata_option,
							task_parent_id,
							task_status,
							task_runner,
							task_epoch,
							last_heartbeat,
							result_code,
							error_msg,
							create_at,
							end_at
						from mo_task.sys_async_task where 1=1 AND task_status IN (0) order by task_id |               |                       | 32396135-3930-3732-3866-376262636462 | CN        | 2024-05-13 04:18:45.000000 | 2024-05-13 04:18:50.000000 |  3578985 | Success | 0        |       | {}        |         0 |          0 | [4,2946808,0,0,0,1498,0,36,1.2802] | Select         | DQL        |       0 | internal_sql    |          2 |            0 |
+--------------------------------------+----------------+--------------------------------------+---------+--------------------------------------+---------------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+----------+---------+----------+-------+-----------+-----------+------------+------------------------------------+----------------+------------+---------+-----------------+------------+--------------+
1 row in set (0.38 sec)

mysql> select count(*) from statement_info;
+----------+
| count(*) |
+----------+
|   514292 |
+----------+
1 row in set (0.00 sec)
