### ISSUE TITLE
[Subtask]: SAMPLE function

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11479]
### Parent Issue

#8590 

### Detail of Subtask

Percentage sample/Reservoir sample in the context of window function.

**Comment by sukki37** [comment]
related to [#1226](https://github.com/matrixorigin/MO-Cloud/issues/1226)

**Comment by domingozhang** [comment]
syntax:
SAMPLE(column_name, interval, aggregation)
interval :
date + INTERVAL expr unit
date - INTERVAL expr unit
aggregation:
count, sum, max, min, avg

example:


-----------------------------------------
|    timecase      |   temperature   |
-----------------------------------------
| 2023-08-01 00:00:00|      25.0       |
| 2023-08-01 00:01:00|      26.0       |
| 2023-08-01 00:02:00|      24.0       |
|        ...         |      ...        |
| 2023-08-01 00:59:00|      27.0       |
| 2023-08-01 01:00:00|      28.0       |
| 2023-08-01 01:01:00|      26.5       |
| 2023-08-01 01:02:00|      27.5       |
|        ...         |      ...        |
| 2023-08-01 01:59:00|      29.0       |
| 2023-08-01 02:00:00|      30.0       |
| 2023-08-01 02:01:00|      29.5       |
| 2023-08-01 02:02:00|      28.5       |
|        ...         |      ...        |
-----------------------------------------

SELECT DATE_FORMAT(timecase, '%Y-%m-%d %H:00:00') AS hour_bucket, SAMPLE(temperature, '1 hour', avg) AS average_temperature
FROM sensor_data
WHERE timestamp >= '2023-08-01 00:00:00' AND timestamp <= '2023-08-01 02:59:59'
GROUP BY hour_bucket;

-----------------------------
|     hour_bucket      |  average_temperature |
-----------------------------
| 2023-08-01 00:00:00 |         25.5         |
| 2023-08-01 01:00:00 |         27.75        |
| 2023-08-01 02:00:00 |         29.25        |
-----------------------------

**Comment by domingozhang** [comment]
Syntax:
sample {BERNOULLI|SYSTEM} (n)
n means percentage of records, which is in (0,100]

BERNOULLI: Each row record extracted comes from a table sample using a sample percentage probability. BERNOULLI sampling scans all physical blocks of the table and skips certain rows (based on the comparison between the sample percentage and runtime random calculations).

The probability of each row record in the BERNOULLI sampling result is independent, so the time required to read the sampling table from disk does not decrease during BERNOULLI sampling. If the BERNOULLI sampling result is further processed, it may affect the overall query time.

SYSTEM: The table is divided into logical data segments, and sampling is performed at this granularity. SYSTEM sampling either queries all rows from specific data segments or skips them (based on the comparison between the sample percentage and runtime random calculations).

example:
SELECT * FROM users SAMPLE BERNOULLI (50);
SELECT * FROM users TABLESAMPLE SYSTEM (75);

**Comment by LiSong0214** [comment]
sample 子句拆出来，下个迭代做

**Comment by m-schen** [comment]
关于本subtask的描述

用法：
select col1, sample(expression list, N rows / K percent) from t where filter-condition ;

返回结果
col1, expression list

语义：
先做 filter-condition 的过滤，再根据expression list的值进行采样.
1. N rows.
当表达式数目为1个时，随机采样 n 行。该表达式为 null 值的行不会被采样。
当表达式数目为多个，  每列需采样出 n 个非null值。所有采样列都为null值的行不会被采样。

2. K percent.
符合条件的行有 k 概率被采样。符合采样规则的行与 n rows 相同。

其他说明：
1. 采样函数是非标量函数。不能与其他非标量函数（也包括另一个采样），不能与标量函数（聚合）混用。
2. 支持group by，即对每个group分别进行采样。
3. 采样单列时支持使用 as 别名。

**Comment by m-schen** [comment]
补充相关设计文档
[SAMPLE函数及子句设计文档.pdf](https://github.com/matrixorigin/matrixone/files/13390708/SAMPLE.pdf)

**Comment by m-schen** [comment]
在研发中碰到了两个已知问题，预计在1.1得到解决，详情参见 https://github.com/matrixorigin/matrixone/issues/12826

@aressu1985 然后该功能可以进行测试了。

**Comment by Ariznawlll** [comment]
**实现部分测试内容：**
个数采样：1. 正常采样，采样行数在1～100之间；2.符合采样条件的行数不足100时，返回结果小于100行；3. 采样的列中存在null值，null的值不被采样；4. 当被采样的表为null时，采样结果为empty set；5.  符合采样的行数为null时，采样结果为empty set。

概率采样：1. 0 percent；2. 100 percent； 3. 随机概率大小（如果数据量大，结果的行数约=概率*总行数）。

与group by联合使用：1. 某个group的所有行满足采样要求，返回满足要求的采样结果；2. 某个group的所有行不满足采样要求时，返回null。

异常测试：1. 多个sample函数同时使用；2. select中同时存在标量函数与非标量函数； 3. sample(col,N rows)N超过指定范围；4. sample(col,K percent)K超过指定范围；4. where子句中存在sample函数。

**Comment by Ariznawlll** [comment]
test done.
