### ISSUE TITLE
[Enhancement]: Current way of getting storage usage is not scalable.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11480]
### Is there an existing issue for enhancement?

- [x] I have checked the existing issues.

### What would you like to be added ?

Currently the cloud will loop over account, then database, then table
to get storage size of an account.   This giant loop is called every 
few minutes.

Need a much better/efficient way of supporting this cloud feature.

**Comment by sukki37** [comment]
cloud will call `show accounts` every 15 min.

**Comment by DanielZhangQD** [comment]
Requirements:
- Be able to get the current storage usage of each account
- Accuracy requirement - Strive for accuracy
- Real-time requirement - Acceptable with a 15-minute delay

**Comment by XuPeng-SH** [comment]
@gouhongshen design doc is needed in the next week

**Comment by gouhongshen** [comment]
working on design

**Comment by gouhongshen** [comment]
will finish this week.

**Comment by XuPeng-SH** [comment]
done by #12315
