### ISSUE TITLE
[Bug]: pessimistic_transaction bvt test fail sometime

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#11490]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="842" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/8b30663e-751f-49e7-a3ec-a459d4f6c01b">
<img width="892" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/a1abf3af-fc0c-4931-b95f-848fe83652a1">
<img width="849" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/659ffd9d-4924-4321-b4d1-3a55b656f843">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/5995023333/job/16260841104?pr=11482

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/5995023338/job/16260844189?pr=11482

**Comment by sukki37** [comment]
maybe related to #11418

**Comment by ouyuanning** [comment]
same as #11217
