### ISSUE TITLE
[Feature Request]: More system metrics support

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11499]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

User can get the following metrics:
lock contention, list existing lock contentions, including session id, locked table and related sql
cache usage, list current cache usage size and percent

**Comment by volgariver6** [comment]
> Lock part related to #11092

@daviszhen is working on it.

**Comment by domingozhang** [comment]
devide into two subtasks

**Comment by daviszhen** [comment]
与 
https://github.com/matrixorigin/matrixone/issues/10513
和
https://github.com/matrixorigin/matrixone/issues/11321

有关。

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/docs/blob/main/design/system_view.md

**Comment by Ariznawlll** [comment]
test done.
