### ISSUE TITLE
[Bug]: Pessimistic mode : alter table add foreign key'result is incorrect on ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11498]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 09a591bfd153a1350065890bc91336d6fe0d1ab9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cannot repro locally,  can repro on ci test.

[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12452727/1-cn-e2e-linux-x86-reports.zip)
[multi-cn-e2e-with-proxy-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12452728/multi-cn-e2e-with-proxy-linux-x86-reports.zip)
[multi-cn-e2e-push-docker-compose-log-pessimistic.zip](https://github.com/matrixorigin/matrixone/files/12452730/multi-cn-e2e-push-docker-compose-log-pessimistic.zip)

### Expected Behavior

<img width="1219" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7b303c0f-bb53-4a1f-a516-f91de46654b2">

**insert into atomic_table_13 values (8,"h");**
internal error: Cannot add or update a child row: a foreign key constraint fails
**select * from atomic_table_13;**
c1    c2
3    d
4    e
5    f

**Comment by Ariznawlll** [comment]
plz look at this at the same time：
<img width="1363" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0de03b22-432d-4c52-bc92-8b864d3a7086">

drop table if exists alter01;
create table alter01(col1 int primary key,col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");
begin;
alter table alter01 change col1 col1New float;
-- @session:id=1{
-- @wait:0:commit
use transaction_enhance;
insert into alter01 values (8,"h");
select * from alter01;
-- @session
insert into alter01 values (6,"h");
select * from alter01;

**Comment by ouyuanning** [comment]
same as #11217

**Comment by Ariznawlll** [comment]
**The case will lead to mo hung on ci:**
drop table if exists atomic_table_12_4;
drop table if exists atomic_table_13;
create table atomic_table_12_4(c1 int primary key,c2 varchar(25));
insert into atomic_table_12_4 values (3,"a"),(4,"b"),(5,"c");
create table atomic_table_13(c1 int primary key,c2 varchar(25));
insert into atomic_table_13 values (3,"d"),(4,"e"),(5,"f");
alter table atomic_table_13 add constraint ffa foreign key f_a(c1) references atomic_table_12_4(c1);
begin;
alter table atomic_table_13 drop foreign key ffa;
-- @session:id=1{
use transaction_enhance;
-- @wait:0:commit
insert into atomic_table_13 values (8,"h");
select * from atomic_table_13;
-- @session}
rollback ;
show create table atomic_table_13;

**step to repro：**
1. run &path/matrixone/test/distributed/cases/pessimistic_transaction/transaction_enhance.sql

**Comment by ouyuanning** [comment]
最近在忙重构。下周确认一下

**Comment by ouyuanning** [comment]
待莫尘那个issue解决后，去掉tag就可以了

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/issues/12015  已fixed，经测试 11498的tag已去除

**Comment by Ariznawlll** [comment]
持续观察ci结果中..

**Comment by Ariznawlll** [comment]
未出现，先关闭.
