### ISSUE TITLE
[Feature Request]: More DDL support 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11496]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

create or **replace** view name as select statement
**alter** sequence name modify_statement

**Comment by daviszhen** [comment]
@YANGGMM  尝试着做一下。

**Comment by YANGGMM** [comment]
finished it， plz test

**Comment by heni02** [comment]
create or replace view 和alter sequence 测试完毕，sequence目前有bug #12088 ，等待解决后回归

**Comment by heni02** [comment]
bug已解决
