### ISSUE TITLE
[Feature Request]: Support LATEST function

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11493]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

select latest(col) from table
Function description: Return the last not null record of the table.
Return data type: same as the applied field.
Applicable data types: all fields.

using with order by clause

**Comment by domingozhang** [comment]
example:

|       time       |   cost   |
|------------------|-----------|
| 2023-08-01 12:00 |   10.5    |
| 2023-08-02 12:00 |    null   |
| 2023-08-03 12:00 |   15.2    |
| 2023-08-04 12:00 |    null   |
| 2023-08-05 12:00 |   20.7    |

**select latest(cost) from table_name order by time;**
10.5

**select latest(cost) from table_name order by time desc;**
20.7

**Comment by ouyuanning** [comment]
dup #12957
