### ISSUE TITLE
[Bug]: bvt test auto_increment test insert fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#11501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="853" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/dcc636b2-2d80-4ef3-8b6c-0e8db84f110e">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/5997729932/job/16264683310?pr=11495

**Comment by LeftHandCold** [comment]
<img width="2560" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/0d436c05-3c2e-46ce-bbfe-cd628c53ba8f">
plz @zhangxu19830126

**Comment by LeftHandCold** [comment]
[multi-cn-e2e-with-proxy-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12453003/multi-cn-e2e-with-proxy-linux-x86-reports.zip)

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
很久没有出现了，应该fix了
