### ISSUE TITLE
[Bug]: ut test TestMOSpan_doProfile fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#11505]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="291" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/2430c9ec-6fb2-417c-aa18-28ee2b222138">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/5998038873/job/16266161830?pr=11482

**Comment by xzxiong** [comment]
ut case 逻辑正常，update:
1. 未能明确为什么会出错
2. 未能再复现
3. #11537 后添加了更多的日志信息，其他复现。

**Comment by xzxiong** [comment]
@YANGGMM not repo, ptal
