### ISSUE TITLE
[Bug]: cte recursive : update and with as cte reported error can't find column

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11503]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b0dac488e6c92f28ad1b5cb61238efc24a3f18ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

update with as cte reported :SQL parser error: can't find column [29 0] in context's map map[[1 0]:[0 0] [1 1]:[0 1] [1 2]:[0 2] [1 3]:[0 3] [1 4]:[0 4] [1 5]:[0 5]]
[SQL STATEMENT]: update cte_insert_table set c3= (WITH RECURSIVE DirectReports(ManagerID, EmployeeID, Title, EmployeeLevel) AS
(
SELECT ManagerID, EmployeeID, Title, 0 AS EmployeeLevel
FROM MyEmployees
WHERE ManagerID IS NULL
UNION ALL
SELECT e.ManagerID, e.EmployeeID, e.Title, EmployeeLevel + 1
FROM MyEmployees AS e
INNER JOIN DirectReports AS d
ON e.ManagerID = d.EmployeeID
)
select title from  DirectReports where ManagerID=16) where c2=274;
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
SQL parser error: can't find column [29 0] in context's map map[[1 0]:[0 0] [1 1]:[0 1] [1 2]:[0 2] [1 3]:[0 3] [1 4]:[0 4] [1 5]:[0 5]]

delete with as cte reported: SQL parser error: can't find column [25 0] in context's map map[[1 0]:[0 0] [1 1]:[0 1] [1 2]:[0 2] [1 3]:[0 3] [1 4]:[0 4] [1 5]:[0 5]]
[SQL STATEMENT]: delete from  cte_insert_table where  c3 = (WITH RECURSIVE DirectReports(ManagerID, EmployeeID, Title, EmployeeLevel) AS
(
SELECT ManagerID, EmployeeID, Title, 0 AS EmployeeLevel
FROM MyEmployees
WHERE ManagerID IS NULL
UNION ALL
SELECT e.ManagerID, e.EmployeeID, e.Title, EmployeeLevel + 1
FROM MyEmployees AS e
INNER JOIN DirectReports AS d
ON e.ManagerID = d.EmployeeID
)
select Title from  DirectReports where ManagerID=16);
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
SQL parser error: can't find column [25 0] in context's map map[[1 0]:[0 0] [1 1]:[0 1] [1 2]:[0 2] [1 3]:[0 3] [1 4]:[0 4] [1 5]:[0 5]]

### Steps to Reproduce

```Markdown
ddl:
CREATE TABLE MyEmployees
(
EmployeeID SMALLINT PRIMARY KEY NOT NULL,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(40) NOT NULL,
Title VARCHAR(50) NOT NULL,
DeptID SMALLINT NOT NULL,
ManagerID SMALLINT NULL
);

INSERT INTO MyEmployees VALUES
(1, 'Ken', 'Sánchez', 'Chief Executive Officer',16, NULL)
,(273, 'Brian', 'Welcker', 'Vice President of Sales', 3, 1)
,(274, 'Stephen', 'Jiang', 'North American Sales Manager', 3, 273)
,(275, 'Michael', 'Blythe', 'Sales Representative', 3, 274)
,(276, 'Linda', 'Mitchell', 'Sales Representative', 3, 274)
,(285, 'Syed', 'Abbas', 'Pacific Sales Manager', 3, 273)
,(286, 'Lynn', 'Tsoflias', 'Sales Representative', 3, 285)
,(16, 'David', 'Bradley', 'Marketing Manager', 4, 273)
,(23, 'Mary', 'Gibson', 'Marketing Specialist', 4, 16);

create table cte_insert_table (c1 int,c2 int ,c3 varchar(50),c4 int);
```

**Comment by iamlinjunhong** [comment]
提pr中

**Comment by heni02** [comment]
confirm,closed
commit id:44086eb6436ae9c63fa78cb3ef4d6a6630f4e802
<img width="1175" alt="企业微信截图_84af1354-a76c-4d0b-9c14-efb197ec9338" src="https://github.com/matrixorigin/matrixone/assets/113406637/57033c8a-22d5-4838-9e6a-78c8baea7239">
