### ISSUE TITLE
[Feature Request]: Get hotspot SQL in system_metrics

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11502]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In system_metrics, build a new view to get the hotspot SQL.
Including the running top 10 SQL which conumes most resources, such as memory and CPU every minute. 
SQL types:
INSERT/UPDATE/DELETE/SELECT/LOAD DATA

**Comment by xzxiong** [comment]
basic view: show top-N finished sql that consumed most mem, or cpu, in last few minutes.
- mem and cpu statistics data come from exec_plan statictics data.

**Comment by xzxiong** [comment]
dev est:  2 man day.

**Comment by lacrimosaprinz** [comment]
related docs:
https://github.com/matrixorigin/matrixorigin.io.cn/pull/745
https://github.com/matrixorigin/matrixorigin.io/pull/541

**Comment by xzxiong** [comment]
dev design:
- Add oridinary view in database `system`
```
mysql> show create table system.sql_statement_hotspot\G
*************************** 1. row ***************************
       View: sql_statement_hotspot
Create View: CREATE VIEW IF NOT EXISTS system.sql_statement_hotspot AS
select statement_id, statement, duration / 1e6 as timeconsumed,
cast(json_unquote(json_extract(stats, '$[2]')) / 1048576.00 as decimal(38,3)) as memorysize,
response_at as collecttime,
node_uuid as node,
account,
user,
statement_type as type
 from system.statement_info
 where response_at > date_sub(now(), interval 10 minute) and response_at < now()
and aggr_count = 0 order by duration desc limit 10;
```

- if you want to query specified account, you can query like
```
-- add filter condition 'account= ?'
mysql> select * from system.sql_statement_hotspot where account = ? 
```

- if you want to query  specified user, you can query like
```
-- add filter condition 'account= ? and user = ?'
mysql> select * from system.sql_statement_hotspot where account = ? and user = ?
```

TODO:
1. this view is missing column `role`,  after #11812

**Comment by Ariznawlll** [comment]
结论：
1.  普通租户下无法查看system.sql_statement_hotspot，系统租户下的超级用户可以查看system.sql_statement_hotspot，普通用户不可查看.
2. 创建租户，通过新创建的租户连接数据库，执行sql，系统租户下查看system.sql_statement_hotspot视图的memorysize列的值与statement_info表中的stats的第三个字段的对应关系为1memorySize=1048576 Stats；通过sql过滤出创建租户所执行的sql：
select * from system.sql_statement_hotspot where account = 'acc_idx';
    2.1  Stats值换算后保留三位小数后的值为0.000，则memorySize展示为0.000；
    2.2  Stats值换算后保留三位小数之后>0.001，正常保留三位小数展示为memorySize的值。
3. 涉及sql类型：INSERT/UPDATE/DELETE/SELECT/LOAD DATA;
4. tpcc与tpch混合场景同时测试。

test done！
