### ISSUE TITLE
[Tech Request]:  Enhance hakeeper to Save Node Resource Information

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11511]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

To optimize the performance and efficiency of our system, it's vital that our execution plans are sensitive to the real-time available resources on our nodes. Therefore, I propose an enhancement to hakeeper to achieve this:

1. In addition to node address information, hakeeper should store the following resource details about each node:
  - Maximum Available Resources: Total capacity of the node (CPU, memory, etc.).
  - Current Available Resources: Real-time statistics on currently unused CPU, memory, and other vital metrics.
2. Dynamic Execution Plan Adjustment: With this enriched dataset, when constructing execution plans, the system can:

- Prioritize nodes with more available resources for heavier tasks.
- Distribute tasks more evenly based on current resource utilization.
- Avoid overloading nodes that are near their capacity, thereby preventing potential bottlenecks and ensuring smoother operations.

3. Updates on Resource Utilization through heartbeat.

**Comment by volgariver6** [comment]
done
