### ISSUE TITLE
[Subtask]Enable the Aggregation in Stream Select

### ISSUE THREAD

**Issue by gavinyue** [matrixorigin/matrixone#11532]
## Summary 
Enable the aggr and related operations like avg/count on select statement upon Streams
目前的问题是， select from stream groupby 有错误

**Comment by LiSong0214** [comment]
@iamlinjunhong 麻烦描述一下需求和design

**Comment by gavinyue** [comment]
需要挪到1.2去完成了

**Comment by gavinyue** [comment]
select count(*) from a source stream 目前不能完成

**Comment by LiSong0214** [comment]
@gavinyue
