### ISSUE TITLE
[Feature Request]: Vector scope in 1.1

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11534]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In 1.1.0, the vector needs to be implemented as following:

**1. vector type**
vector float 32
vector float 64

example:
create table t1
(
    a int primary key,
    b vecf32(3),
    c vecf64(3)
);
insert into t1 values(1, "[1,2,3]", "[4,5,6]");

**2. vector computing**
Elementwise Binary Operators : +, -, *, /,
Comparison =,!=, >, >= , <, <=
Elementwise Unary Functions: sqrt, abs, cast
Auto casting:
vecf32 + vecf64 = vecf64
vecf32 + varchar = vecf32

**3. Builtin function**
Vector Unary Functions : summation, l1_norm, l2_norm, vector_dims
Vector Binary Functions: inner_product, cosine_similarity
Disable setting vector as Primary Key. We also don't support Unique Index on vector column.
Agg Operator count

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
https://github.com/matrixorigin/docs/blob/9874b6dead3a8778ee092c6840080023510670bc/tech-notes/sql/design/ai/vector_datatype/vector.md#operatorsfunctions-supported
```
```Markdown
https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUTA43Af1SRA2ksekSQw?scode=AJsA6gc3AA8qbxC6IOALQAjwY-ACU
```

**Comment by sukki37** [comment]
@arjunsk need documentation and transfer this issue to @aressu1985

**Comment by florashi181** [comment]
@arjunsk as the discussion, would u transfer this issue to @aressu1985 ?

**Comment by aressu1985** [comment]
需求中涉及到的两个：
1. type vecf32，vecf64及其相关计算操作均测试完毕
2. 函数 summation, l1_norm, l2_norm, vector_dims,inner_product, cosine_similarity也测试完成
3. 覆盖了亿级数据量的函数测试
