### ISSUE TITLE
[Bug]: ut test TestAppendAndGC fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#11546]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="516" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/ae790224-7222-44c6-81e3-1ea8a09bbf92">

fail link:https://github.com/YANGGMM/matrixone/actions/runs/6009850502/job/16300093446?pr=85

**Comment by sukki37** [comment]
repro https://github.com/matrixorigin/matrixone/actions/runs/6496796402/job/17644526815?pr=12096

**Comment by LeftHandCold** [comment]
not work this

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
I'm not working here, I'll analyze it over the weekend

**Comment by LeftHandCold** [comment]
本周完成重构gc

**Comment by LeftHandCold** [comment]
本周完成重构gc

**Comment by LeftHandCold** [comment]
这周完成gc重构

**Comment by LeftHandCold** [comment]
这周完成gc重构

**Comment by LeftHandCold** [comment]
这周完成gc重构

**Comment by LeftHandCold** [comment]
这周完成gc重构

**Comment by LeftHandCold** [comment]
等待完成gc重构

**Comment by LeftHandCold** [comment]
等待完成gc重构

**Comment by LeftHandCold** [comment]
等待完成gc重构
