### ISSUE TITLE
[Bug]: unexpected error : Error 1105 (HY000): operation error S3: PutObject, failed to compute payload hash: failed to seek body to start, request stream is not seekable

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11555]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b0dac488e6c92f28ad1b5cb61238efc24a3f18ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1647" alt="企业微信截图_ce149bf7-f3ad-4d5d-b83d-0d6fbc1a476b" src="https://github.com/matrixorigin/matrixone/assets/60595215/65d74921-ec25-4480-972d-c1b235b0b19b">

communicate with you offline

### Additional information

code is on mysql branch 

https://github.com/daviszhen/matrixone/tree/0828-record-size

**Comment by daviszhen** [comment]
@reusee  跟乐声沟通过了。他明天回来改掉。

**Comment by reusee** [comment]
Not reproducible on S3, will try with minio.

**Comment by daviszhen** [comment]
@reusee  物理备份依赖这个checksum。我给升到s-1了。

**Comment by daviszhen** [comment]
> Not reproducible on S3, will try with minio.

就是minio上能跑出这个问题。你如果不能复现的话，我这边能出。

**Comment by reusee** [comment]
如果非常紧急，可以用 ```checksum := md5.Sum(data)```计算，结果是一样的，也不会有额外开销。

**Comment by daviszhen** [comment]
> 如果非常紧急，可以用 `checksum := md5.Sum(data)`计算，结果是一样的，也不会有额外开销。

tae 内部的copyfile 无法用此种方法。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/7917eebd-b332-4920-829d-d7de14d38802)

**Comment by reusee** [comment]
在做其他 s-1 ,今天没看这个
之前的初步判断，用下面代码无法重现：https://github.com/reusee/matrixone/commit/ddcbfad29dd14ce464770ebf34f4d8aa80072a36

**Comment by reusee** [comment]
working on another s-1 issue.

**Comment by daviszhen** [comment]
> 在做其他 s-1 ,今天没看这个 之前的初步判断，用下面代码无法重现：[reusee@ddcbfad](https://github.com/reusee/matrixone/commit/ddcbfad29dd14ce464770ebf34f4d8aa80072a36)

可以来我的环境复现。

**Comment by daviszhen** [comment]
基于 @reusee 的建议，改为其它方法。这个issue降级。

**Comment by reusee** [comment]
Maybe the Hash field should be removed

**Comment by reusee** [comment]
pr sent https://github.com/matrixorigin/matrixone/pull/12362

**Comment by reusee** [comment]
PR merged. This will not happen since Hash was removed.
re-assigning.

**Comment by daviszhen** [comment]
it was fixed
