### ISSUE TITLE
[Bug]: mo was hung on standlone mode after running stability test for about 20 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11551]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6c08c6a45191d63f9f89e5bfef5ff37194713b5f
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

mo was hung on standlone mode after running stability test for about 20 hours, and not connected again.

<img width="1227" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/46890f92-6755-48c9-9a3e-35ca0e65974e">

profile:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/12470919/profile.tar.gz)

**Comment by sukki37** [comment]
Could you please provide the trace logs that can help us find the root cause, Thank you. @aressu1985

**Comment by daviszhen** [comment]
从trace文件中分析，卡住位置如下。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/55a8865c-dad8-43c4-ae96-ab31f7a52aa8)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/974b88e2-500f-48db-9ca2-4848603b3474)

**Comment by daviszhen** [comment]
还没看

**Comment by triump2020** [comment]
从日志看， CN 与DN 之间网络异常:
![1693405548056](https://github.com/matrixorigin/matrixone/assets/63033222/9d5c2d68-4bc6-41fa-886a-151aec96caf9)




从代码看，重连之前，会abort 掉 CN 上所有事务，但此时 pipeline 的reader 尚未结束，所以产生了datarace 导致了panic :  

![1693405757042](https://github.com/matrixorigin/matrixone/assets/63033222/4cf376c5-baad-485d-9d20-81012cc67d38)




由于大量的 goroutine panic 了，上层等不到结束信息, 产生hang 的现象.

**Comment by sukki37** [comment]
> 从日志看， CN 与DN 之间网络异常: ![1693405548056](https://user-images.githubusercontent.com/63033222/264374646-9d5c2d68-4bc6-41fa-886a-151aec96caf9.png)
> 
> 从代码看，重连之前，会abort 掉 CN 上所有事务，但此时 pipeline 的reader 尚未结束，所以产生了datarace 导致了如下panic :
> 
> ![1693405757042](https://user-images.githubusercontent.com/63033222/264375764-4cf376c5-baad-485d-9d20-81012cc67d38.png)
> 
> 由于大量的 goroutine panic 了，上层等不到结束信息, 产生hang 的现象.
> 
> 所以，可能主要原因还是：
> 
> ![1693406015971](https://user-images.githubusercontent.com/63033222/264377155-47d46280-4c97-487b-84ff-9d8b9796ad09.png)

@m-schen Please help address the issue where unhandled panic errors are causing the system to hang and become unresponsive. We should catch the panic, log the error, and ideally, recover gracefully without hanging or becoming unresponsive. This is a critical issue that affects the stability and reliability of the system, requiring urgent attention. Thank you.

**Comment by m-schen** [comment]
这个清理事务不是进行回滚，只是将事务都标记成了abort状态。这些事务目前在get block from memory以及事务提交时会检测到这个状态，然后报错。delete block的获取方法估计是逃脱了这个检测，导致了panic。

我会检查一下这部分，以及加上catch panic避免不返回。

**Comment by m-schen** [comment]
abortAllRunningTxn的语义被修改了，最初设计只是将状态设置成abort，当pipeline执行到获取block和commit阶段时会报错。现在会做真实的回滚，导致delete blocks被设置成nil了。

我需要对这块做一下检查。

**Comment by m-schen** [comment]
已经修复重连导致正在执行的查询workspace被清空的问题，以及补充了一个recovey防止因为异常错误导致pipeline卡死。可以验证。

**Comment by aressu1985** [comment]
经验证，没有在出现hung住的问题，但是MO所在机器内存爆了，此问题可以先关闭
