### ISSUE TITLE
[Feature Request]: new aggregate Functions

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11563]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like
```
**FIRST(expr)**
Function Description: Returns the first non-NULL value written in a column of a statistical table/super table.
Return Data Type: Same as the field used.
Applicable Data Types: All fields.
Applicable to: Tables and super tables.
Usage Notes:
To return the first (smallest timestamp) non-NULL value for each column, use FIRST(*).
If all values in a column of the result set are NULL, the result for that column will also be NULL.
If all columns in the result set are NULL, no result will be returned.
```
```
**LAST(expr)**
Function Description: Returns the last non-NULL value written in a column of a statistical table/super table.
Return Data Type: Same as the field used.
Applicable Data Types: All fields.
Applicable to: Tables and super tables.
Usage Notes:
To return the last (largest timestamp) non-NULL value for each column, use LAST(*).
If all values in a column of the result set are NULL, the result for that column will also be NULL.
If all columns in the result set are NULL, no result will be returned.
When used with a super table, if multiple data rows have the same maximum timestamp, the function will randomly select one of them, and it does not guarantee consistent selection of data rows across multiple executions.
```

**Comment by domingozhang** [comment]
example：

|       time       |   cost   |
|------------------|-----------|
| 2023-08-01 12:00 |   10.5    |
| 2023-08-02 12:00 |    null   |
| 2023-08-03 12:00 |   15.2    |
| 2023-08-04 12:00 |    null   |
| 2023-08-05 12:00 |   20.7    |

**SELECT first(value) FROM table_name;**
first(cost) 
10.5

It returns the first not null value of cost column order by time related column without order by clause.

**SELECT last(value) FROM table_name;**
first(cost) 
20.7

It returns the last not null value of cost column order by time related column without order by clause.

**Comment by domingozhang** [comment]
If no time related column in a table, user needs to use order by clause. If no order by ,there will be a mistake.
for example:
|       time       |   cost   |
|------------------|-----------|
| 1 |   10.5    |
| 2 |    null   |
| 2 |   15.2    |
| 3 |    null   |
| 4 |   20.7    |


**SELECT first(value) FROM table_name order by time;**
first(cost)
10.5

**SELECT last(value) FROM table_name  order by time;**
first(cost)
20.7


**SELECT last(value) FROM table_name order;**
error: no sorted column

**Comment by ouyuanning** [comment]
dup #12957
