### ISSUE TITLE
[Feature Request]: shuffle data writing support

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11566]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Shuffle data support in databases refers to the ability of a database system to efficiently handle and process shuffled or distributed data. While shuffle operations are typically performed by distributed computing frameworks or data processing systems, databases can provide features and capabilities that support the storage, retrieval, and management of shuffled data.

Need these features:
1. Asynchronous Writing: TDengine supports asynchronous writing mode where data write operations do not block the execution of users or applications. Applications can submit data to the write queue and continue with other operations without waiting for the write to complete.
2. Write Queue Management: TDengine utilizes a write queue to manage write operations. The write queue can buffer and adjust the write rate to accommodate varying write loads and data processing capabilities.

**Comment by fengttt** [comment]
These are non-features and mis-features.    There is no need for us to do anything.

**Comment by fengttt** [comment]
As discussed, async write is builtin, nothing to do.     Write Queue is not applicable.    We either read from a queue (kafka), or a sql connection.
