### ISSUE TITLE
[Feature Request]: filling query 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#11565]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like
syntax:
```
SELECT columns FROM table
INTERVAL(interval_val [, interval_offset]) [SLIDING (sliding_val)] [FILL(fill_method)];
```
```
**No filling**: NONE (default filling mode).
**Value filling**: Filling with a fixed value, where you need to specify the value to fill. For example: FILL(VALUE, 1.23). It is important to note that the final filling value depends on the type of the corresponding column. For example, if the column is of type INT, the filling value will be 1.
**Previous filling**: Filling with the previous non-NULL value. For example: FILL(PREV).
**Null filling**: Filling with NULL values. For example: FILL(NULL).
**Linear filling**: Filling with linear interpolation based on the nearest non-NULL values before and after. For example: FILL(LINEAR).
**Next filling**: Filling with the next non-NULL value. For example: FILL(NEXT).
```

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
Example:

CREATE TABLE sensor_data (
    ts TIMESTAMP,
    temperature FLOAT
);

INSERT INTO sensor_data VALUES('2023-08-01 00:00:00', 25.0);
INSERT INTO sensor_data VALUES('2023-08-01 00:05:00', 26.0);
INSERT INTO sensor_data VALUES('2023-08-01 00:15:00', 28.0);
INSERT INTO sensor_data VALUES('2023-08-01 00:20:00', 30.0);
INSERT INTO sensor_data VALUES('2023-08-01 00:25:00', 27.0);

SELECT ts, temperature FROM sensor_data where ts<'2023-08-01 00:30:00' and ts> '2023-08-01 00:00:00'
INTERVAL(5m) FILL (linear);

+---------------------+-------------+
|         ts          | temperature |
+---------------------+-------------+
| 2023-08-01 00:00:00 |    25.000   |
| 2023-08-01 00:05:00 |    26.000   |
| 2023-08-01 00:10:00 |    27.000   |
| 2023-08-01 00:15:00 |    28.000   |
| 2023-08-01 00:20:00 |    30.000   |
| 2023-08-01 00:25:00 |    27.000   |
+---------------------+-------------+
```

**Comment by fengttt** [comment]
This should be done by window function.    It is a very specific function, someone need to write down semantics carefully.
The supplied syntax is ambiguous.

Essentially the only meaningful way of writing this query is
select timestamp, fill(col, fill method, parameter) over (order by timestamp) from t;

Need design doc.

**Comment by domingozhang** [comment]
fill(column_name, [interval], [method])
参数说明：

column_name：要填充的列名。
interval：填充的时间间隔，可以是一个整数或时间间隔表达式。例如，"1m"表示填充每一分钟的缺失值。
method：填充的方法，可以是以下选项之一：
linear：线性插值，使用前后两个已知的数据点之间的线性关系来估算缺失值。
previous：使用前一个已知值来填充缺失值。
next：使用后一个已知值来填充缺失值。
value：使用指定的值来填充缺失值，需要提供额外的值参数。

**Comment by domingozhang** [comment]
SELECT fill(column_name, 1m, linear) FROM table_name WHERE time >= start_time AND time <= end_time;

**Comment by domingozhang** [comment]
examples :
CREATE TABLE meters (ts TIMESTAMP, current FLOAT, voltage INT, phase FLOAT) TAGS (location BINARY(64), groupId INT);

针对智能电表采集的数据，以 10 分钟为一个阶段，计算过去 24 小时的电流数据的平均值、最大值、电流的中位数。如果没有计算值，用前一个非 NULL 值填充。使用的查询语句如下：
SELECT _WSTART, _WEND, AVG(current), MAX(current), APERCENTILE(current, 50) FROM meters
  WHERE ts>=NOW-1d and ts<=now
  INTERVAL(10m)
  FILL(PREV);

针对d1001设备采集数据统计每小时记录数，如果某一个小时不存在数据，则返回之前一个小时的统计数据。TDengine提供前向插值(prev)、线性插值(linear)、NULL值填充(NULL)、特定值填充(value)。
select count(*) from d1001 interval(1h) fill(prev);

**Comment by domingozhang** [comment]
Table structure:

taos> desc device_total_device_1min;
             field              |         type         |   length    |   note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 value                          | DOUBLE               |           8 |          |
 org_id                         | INT                  |           4 | TAG      |
Example data:

taos> select * from total_device_1min;
           ts            |           value           |   org_id    |
====================================================================
 2023-08-17 08:49:49.574 |              10.000000000 |          10 |
 2023-06-05 07:12:01.000 |               1.000000000 |           1 |
 2023-06-09 06:31:11.000 |               2.000000000 |           1 |
 2023-08-17 09:08:50.448 |               3.000000000 |           1 |

SELECT _wstart, org_id, LAST(`value`) as val 
FROM total_device_1min 
WHERE ts > '2023-08-01 00:00:00' and ts < '2023-08-31 00:00:00' 
PARTITION BY org_id INTERVAL(1d) FILL(PREV);

**Comment by florashi181** [comment]
doc needs

**Comment by iamlinjunhong** [comment]
doc: https://github.com/iamlinjunhong/docs/blob/tw/design/time%20window.md

**Comment by Ariznawlll** [comment]
time window test done.
