### ISSUE TITLE
[Enhancement]: add cache for caching whole file

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#11569]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
we want to cache the whole file when writing, a new interface or enhancement to existed interfaces is required.
```

**Comment by fengttt** [comment]
Disk cache should simply cache whole S3 object.    At this moment all stats seems to say this is a good idea.

**Comment by reusee** [comment]
Done.
