### ISSUE TITLE
[Bug]: bvt failed due to `Decimal128 scale overflow`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11630]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/matrixorigin/matrixone/actions/runs/6069853163/job/16464880940?pr=11615
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1031" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/c546dca7-e116-4a93-8f7b-87e569cd60e8">

logs: 
[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/12513681/multi-cn-e2e-push-docker-compose-log.zip)

### Additional information

@zengyan1 please help to identify the root cause of this issue, thank you.

**Comment by zengyan1** [comment]
Done
