### ISSUE TITLE
[Bug]: Fail to alter account to reset password

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#11641]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): dad04eb6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"error": "Error 1064 (HY000): SQL parser error: table \"mo_user\" does not exist", "elapsed": "3.376908ms", "rows": 0, "sql": "alter account `23655801_9d5c_4da5_a474_52e07c651387` admin_name 'admin' identified by '123456';"}
```

### Expected Behavior

Alter account succeeds.

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Upgrade MO with the following path:
nightly-667f74e1 -> nightly-ec020463 -> nightly-c929fdf9 -> nightly-dad04eb6

**Comment by DanielZhangQD** [comment]
Here are the logs.[202309051917.tar.gz](https://github.com/matrixorigin/matrixone/files/12522759/202309051917.tar.gz)

**Comment by YANGGMM** [comment]
开始处理

**Comment by YANGGMM** [comment]
<img width="1340" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/efb71b53-9c5a-465f-ab8d-dcf0c7fea161">

**Comment by YANGGMM** [comment]
{"level":"INFO","time":"2023/09/06 01:58:05.822762 +0000","caller":"disttae/txn_database.go:165","msg":"txnDatabase.Relation table \"mo_user\"(acc 279000001 db 1) does not exist"}
{"level":"ERROR","time":"2023/09/06 01:58:05.822828 +0000","caller":"disttae/txn_database.go:166","msg":"error: SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"d1f27ec2-4c58-11ee-847f-da73fc64988a","kind":"statement"}}
{"level":"ERROR","time":"2023/09/06 01:58:05.822871 +0000","caller":"engine/entire_engine.go:57","msg":"error: internal error: temporary engine not init yet","span":{"trace_id":"d1f27ec2-4c58-11ee-847f-da73fc64988a","kind":"statement"}}
{"level":"ERROR","time":"2023/09/06 01:58:05.822881 +0000","caller":"frontend/util.go:556","msg":"Failed to get temp database","error":"internal error: temporary engine not init yet","session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|d1f2282c-4c58-11ee-847f-da73fc64988a|ecef0de6-4c57-11ee-847f-da73fc64988a","session_id":"\ufffd\ufffd(,LX\u0011\ufffd\ufffd\ufffds\ufffdd\ufffd\ufffd"}
{"level":"ERROR","time":"2023/09/06 01:58:05.822895 +0000","caller":"frontend/util.go:556","msg":"Failed to get table","tableName":"mo_user","error":"SQL parser error: table \"mo_user\" does not exist","session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|d1f2282c-4c58-11ee-847f-da73fc64988a|ecef0de6-4c57-11ee-847f-da73fc64988a","session_id":"\ufffd\ufffd(,LX\u0011\ufffd\ufffd\ufffds\ufffdd\ufffd\ufffd"}
{"level":"ERROR","time":"2023/09/06 01:58:05.822925 +0000","caller":"plan/query_builder.go:2829","msg":"error: SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"d1f27ec2-4c58-11ee-847f-da73fc64988a","kind":"statement"}}
{"level":"ERROR","time":"2023/09/06 01:58:05.822946 +0000","caller":"frontend/util.go:556","msg":"SQL parser error: table \"mo_user\" does not exist","session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|d1f2282c-4c58-11ee-847f-da73fc64988a|ecef0de6-4c57-11ee-847f-da73fc64988a","session_id":"\ufffd\ufffd(,LX\u0011\ufffd\ufffd\ufffds\ufffdd\ufffd\ufffd"}
{"level":"ERROR","time":"2023/09/06 01:58:05.822969 +0000","caller":"frontend/util.go:556","msg":"query trace status","connection_id":4294967295,"statement":"select user_id,authentication_string,default_role from mo_catalog.mo_user where user_name = \"admin\"","status":"fail","error":"SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"d1f27ec2-4c58-11ee-847f-da73fc64988a","kind":"statement"},"session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|d1f2282c-4c58-11ee-847f-da73fc64988a|ecef0de6-4c57-11ee-847f-da73fc64988a","session_id":"\ufffd\ufffd(,LX\u0011\ufffd\ufffd\ufffds\ufffdd\ufffd\ufffd"}
{"level":"ERROR","time":"2023/09/06 01:58:05.823010 +0000","caller":"frontend/util.go:556","msg":"SQL parser error: table \"mo_user\" does not exist","session_info":"connectionId 24783122|172.20.33.55:46848|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 2361491|ecef0de6-4c57-11ee-847f-da73fc64988a","session_id":"\ufffd\ufffd\r\ufffdLW\u0011\ufffd\ufffd\ufffds\ufffdd\ufffd\ufffd","statement_id":"\ufffd\ufffd\u0013\ufffdLX\u0011\ufffd\ufffd\ufffds\ufffdd\ufffd\ufffd"}
{"level":"ERROR","time":"2023/09/06 01:58:05.823023 +0000","caller":"frontend/util.go:556","msg":"query trace status","connection_id":24783122,"statement":"alter account `23655801_9d5c_4da5_a474_52e07c651387` admin_name 'admin' identified by '******'","status":"fail","error":"SQL parser error: table \"mo_user\" does not exist","span":

**Comment by YANGGMM** [comment]
log can be seen in :
[default-cn-n54gh.log](https://github.com/matrixorigin/matrixone/files/12545222/default-cn-n54gh.log)

**Comment by YANGGMM** [comment]
<img width="1301" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/8c9622c1-427a-4064-b974-e861cde25f17">

**Comment by YANGGMM** [comment]
但是 show tables 和 select * from mo_catalog.mo_user 都能找到mo_user这张表

**Comment by YANGGMM** [comment]
reproduce step:
connect to mo:mysql -h freetier-01.cn-hangzhou.cluster.aliyun-dev.matrixone.tech -P6001 -udump -pc6fOYyFj3a-C.  
if password invalid, plz @DanielZhangQD 

then input:alter account `23655801_9d5c_4da5_a474_52e07c651387` admin_name 'admin' identified by '123456';
will get the error info.

but show tables from mo_catalog;   and select * from mo_catalog.mo_user can get the result.

**Comment by YANGGMM** [comment]
log can be  acquired  in https://doc.weixin.qq.com/doc/w3_AUoAgQY-AAk3i8pzzimQJaAI4JpCb?scode=AJsA6gc3AA8AzX8cp9AVIAugbFALc

**Comment by nnsgmsone** [comment]
@DanielZhangQD 给我一个可用的密码，我链接上去看看

> reproduce step: connect to mo:mysql -h freetier-01.cn-hangzhou.cluster.aliyun-dev.matrixone.tech -P6001 -udump -pc6fOYyFj3a-C. if password invalid, plz @DanielZhangQD
> 
> then input:alter account `23655801_9d5c_4da5_a474_52e07c651387` admin_name 'admin' identified by '123456'; will get the error info.
> 
> but show tables from mo_catalog; and select * from mo_catalog.mo_user can get the result.

**Comment by DanielZhangQD** [comment]
集群重装了

**Comment by nnsgmsone** [comment]
> reproduce step: connect to mo:mysql -h freetier-01.cn-hangzhou.cluster.aliyun-dev.matrixone.tech -P6001 -udump -pc6fOYyFj3a-C. if password invalid, plz @DanielZhangQD
> 
> then input:alter account `23655801_9d5c_4da5_a474_52e07c651387` admin_name 'admin' identified by '123456'; will get the error info.
> 
> but show tables from mo_catalog; and select * from mo_catalog.mo_user can get the result.

这是必然的。。。。admin租户下的mo_user是存在的，现在的问题是租户270000003找不到这个mo_user表。

**Comment by nnsgmsone** [comment]
dn的日志观察下来并没有为租户270000003创建任何表。。。应该就是没创建

**Comment by nnsgmsone** [comment]
```
{"level":"INFO","time":"2023/09/05 09:56:09.714384 +0000","caller":"disttae/txn_database.go:165","msg":"txnDatabase.Relation table \"mo_user\"(acc 270000003 db 1) does not exist"}
```
这是报错信息，这个租户id在dn没有创建这个表。

**Comment by nnsgmsone** [comment]
整个创建租户的逻辑不是原子的，改成一个事务吧。现在看着是只创建了租户，租户对应的一些表没创建。

**Comment by daviszhen** [comment]
<img width="1142" alt="企业微信截图_72eda399-f70a-4ac1-8f57-60247cb7fea7" src="https://github.com/matrixorigin/matrixone/assets/60595215/c8bbbb6a-c046-4781-a85a-549210a7993b">

之前是由于图上的问题。
把create/drop database 放到了事务之外。创建新租户时，创建N个数据库。但是又必须先拿到新account id，才能正确的新租户的数据库。因此不得不，把创建租户的事务拆成两个事务。现在改法：一种，调整create/drop database的事务行为。把create/drop database放到事务里面。看能不能正确执行。二种：不改create/drop database的行为。在第二个事务创建数据库失败时，再把租户给删了。

**Comment by YANGGMM** [comment]
pr testing

**Comment by YANGGMM** [comment]
need fix test case

**Comment by YANGGMM** [comment]
need fix test case

**Comment by DanielZhangQD** [comment]
After upgrading to `nightly-a67e655d`, create 5 instances and this issue is not hit.

**Comment by DanielZhangQD** [comment]
This issue occurred again.
```
2023/09/18 03:32:26.174043 +0000 ERROR gin@v1.9.1/context.go:174 trace {"error": "Error 1064 (HY000): SQL parser error: table \"mo_user\" does not exist", "elapsed": "1.466001ms", "rows": 0, "sql": "alter account `b73d090f_80b1_46fb_bc0a_43fe9d49918b` admin_name 'admin' identified by 'Abc123456';"}
```

**Comment by tianyahui-python** [comment]
> <img alt="企业微信截图_72eda399-f70a-4ac1-8f57-60247cb7fea7" width="1142" src="https://user-images.githubusercontent.com/60595215/266570099-c8bbbb6a-c046-4781-a85a-549210a7993b.png">
> 之前是由于图上的问题。 把create/drop database 放到了事务之外。创建新租户时，创建N个数据库。但是又必须先拿到新account id，才能正确的新租户的数据库。因此不得不，把创建租户的事务拆成两个事务。现在改法：一种，调整create/drop database的事务行为。把create/drop database放到事务里面。看能不能正确执行。二种：不改create/drop database的行为。在第二个事务创建数据库失败时，再把租户给删了。

我们现在修复的这个pr 用的是方法1 还是方法2 @YANGGMM @daviszhen

**Comment by YANGGMM** [comment]
> > <img alt="企业微信截图_72eda399-f70a-4ac1-8f57-60247cb7fea7" width="1142" src="https://user-images.githubusercontent.com/60595215/266570099-c8bbbb6a-c046-4781-a85a-549210a7993b.png">
> > 之前是由于图上的问题。 把create/drop database 放到了事务之外。创建新租户时，创建N个数据库。但是又必须先拿到新account id，才能正确的新租户的数据库。因此不得不，把创建租户的事务拆成两个事务。现在改法：一种，调整create/drop database的事务行为。把create/drop database放到事务里面。看能不能正确执行。二种：不改create/drop database的行为。在第二个事务创建数据库失败时，再把租户给删了。
> 
> 我们现在修复的这个pr 用的是方法1 还是方法2 @YANGGMM @daviszhen

方法1

**Comment by tianyahui-python** [comment]
> > > <img alt="企业微信截图_72eda399-f70a-4ac1-8f57-60247cb7fea7" width="1142" src="https://user-images.githubusercontent.com/60595215/266570099-c8bbbb6a-c046-4781-a85a-549210a7993b.png">
> > > 之前是由于图上的问题。 把create/drop database 放到了事务之外。创建新租户时，创建N个数据库。但是又必须先拿到新account id，才能正确的新租户的数据库。因此不得不，把创建租户的事务拆成两个事务。现在改法：一种，调整create/drop database的事务行为。把create/drop database放到事务里面。看能不能正确执行。二种：不改create/drop database的行为。在第二个事务创建数据库失败时，再把租户给删了。
> > 
> > 
> > 我们现在修复的这个pr 用的是方法1 还是方法2 @YANGGMM @daviszhen
> 
> 方法1
有对应的dev design 吗, 修改后的事务行为是什么样子的  @YANGGMM

**Comment by YANGGMM** [comment]
> > > <img alt="企业微信截图_72eda399-f70a-4ac1-8f57-60247cb7fea7" width="1142" src="https://user-images.githubusercontent.com/60595215/266570099-c8bbbb6a-c046-4781-a85a-549210a7993b.png">
> > > 之前是由于图上的问题。 把create/drop database 放到了事务之外。创建新租户时，创建N个数据库。但是又必须先拿到新account id，才能正确的新租户的数据库。因此不得不，把创建租户的事务拆成两个事务。现在改法：一种，调整create/drop database的事务行为。把create/drop database放到事务里面。看能不能正确执行。二种：不改create/drop database的行为。在第二个事务创建数据库失败时，再把租户给删了。
> > 
> > 
> > 我们现在修复的这个pr 用的是方法1 还是方法2 @YANGGMM @daviszhen
> 
> 方法1 有对应的dev design 吗, 修改后的事务行为是什么样子的 @YANGGMM

没有design，现在只是允许 background 下面允许在事务里面执行create/drop database，如果显示修改改动太大

**Comment by YANGGMM** [comment]
<img width="970" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/d34bacb1-a088-4c03-bc1c-d1f1fed4f1b4">

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2023/09/20 08:18:28.500921 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:2731","msg":"SQL parser error: table \"mo_user\" does not exist","uuid":"63373230-3561-3330-3738-346363366238","session_info":"connectionId 28754174|172.20.33.26:57626|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 101510|3ae6143f-578e-11ee-b691-7adcebcb0d36","session_id":"3ae6143f-578e-11ee-b691-7adcebcb0d36","statement_id":"471b24fb-578e-11ee-b691-7adcebcb0d36"}
{"level":"ERROR","time":"2023/09/20 08:18:28.500873 +0000","name":"cn-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"63373230-3561-3330-3738-346363366238","connection_id":4294967295,"statement":"select user_id,authentication_string,default_role from mo_catalog.mo_user where user_name = \"admin\"","status":"fail","error":"SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"471b46b2-578e-11ee-b691-7adcebcb0d36","kind":"statement"},"session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|471b3786-578e-11ee-b691-7adcebcb0d36|3ae6143f-578e-11ee-b691-7adcebcb0d36","session_id":"471b3786-578e-11ee-b691-7adcebcb0d36"}
{"level":"ERROR","time":"2023/09/20 08:18:28.500848 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:2731","msg":"SQL parser error: table \"mo_user\" does not exist","uuid":"63373230-3561-3330-3738-346363366238","session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|471b3786-578e-11ee-b691-7adcebcb0d36|3ae6143f-578e-11ee-b691-7adcebcb0d36","session_id":"471b3786-578e-11ee-b691-7adcebcb0d36"}
{"level":"ERROR","time":"2023/09/20 08:18:28.500828 +0000","caller":"plan/query_builder.go:2834","msg":"error: SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"471b46b2-578e-11ee-b691-7adcebcb0d36","kind":"statement"}}
{"level":"ERROR","time":"2023/09/20 08:18:28.500800 +0000","name":"cn-service.frontend","caller":"frontend/compiler_context.go:212","msg":"Failed to get table","uuid":"63373230-3561-3330-3738-346363366238","tableName":"mo_user","error":"SQL parser error: table \"mo_user\" does not exist","session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|471b3786-578e-11ee-b691-7adcebcb0d36|3ae6143f-578e-11ee-b691-7adcebcb0d36","session_id":"471b3786-578e-11ee-b691-7adcebcb0d36"}
{"level":"ERROR","time":"2023/09/20 08:18:28.500788 +0000","name":"cn-service.frontend","caller":"frontend/compiler_context.go:232","msg":"Failed to get temp database","uuid":"63373230-3561-3330-3738-346363366238","error":"internal error: temporary engine not init yet","session_info":"connectionId 4294967295|0.0.0.0:0|{account sys:root:moadmin -- 0:0:0}|471b3786-578e-11ee-b691-7adcebcb0d36|3ae6143f-578e-11ee-b691-7adcebcb0d36","session_id":"471b3786-578e-11ee-b691-7adcebcb0d36"}
{"level":"ERROR","time":"2023/09/20 08:18:28.500776 +0000","caller":"engine/entire_engine.go:57","msg":"error: internal error: temporary engine not init yet","span":{"trace_id":"471b46b2-578e-11ee-b691-7adcebcb0d36","kind":"statement"}}
{"level":"ERROR","time":"2023/09/20 08:18:28.500740 +0000","caller":"disttae/txn_database.go:166","msg":"error: SQL parser error: table \"mo_user\" does not exist","span":{"trace_id":"471b46b2-578e-11ee-b691-7adcebcb0d36","kind":"statement"}}
{"level":"INFO","time":"2023/09/20 08:18:28.500671 +0000","caller":"disttae/txn_database.go:165","msg":"txnDatabase.Relation table \"mo_user\"(acc 150000002 db 1) does not exist"}

**Comment by YANGGMM** [comment]
not repro

**Comment by YANGGMM** [comment]
still working

**Comment by daviszhen** [comment]
今天没看。

**Comment by daviszhen** [comment]
与https://github.com/matrixorigin/matrixone/issues/11747 相似的一个问题。

等freetier-02升级到1.0rc2后。把已有的租户删了，重新建。理论上就可以了

**Comment by daviszhen** [comment]
freetier-02已经升级到1.0-dev。等继续验证。

**Comment by daviszhen** [comment]
等云平台复现

**Comment by daviszhen** [comment]
等云平台复现

**Comment by daviszhen** [comment]
修改后，等云平台复现

**Comment by daviszhen** [comment]
等云平台复现

**Comment by daviszhen** [comment]
等云平台验证

**Comment by daviszhen** [comment]
等云平台验证

**Comment by sukki37** [comment]
After the upgrade, the issue hasn't reproduced, so we've downgraded it for further observation.

**Comment by DanielZhangQD** [comment]
This issue does not occur till now after the upgrade, so close it for now.
