### ISSUE TITLE
[Tech Request]: A buffer for allocating fractional objects

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#11651]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

For each session, we need to implement a buffer that handles most of the fractional memory allocation during sql processing

```go
type Buffer struct {}

Alloc[T any](*Buffer) *T
Free[T any](*Buffer, *T)
MakeSlice[T any](*Buffer) []T
FreeSlice[T any](*Buffer, []T)
func (*Buffer) Free()
```

**Comment by florashi181** [comment]
dup
