### ISSUE TITLE
[Bug]: The storage compatibility test failed in select * from information_schema.schemata.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11655]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1.0.0-rc1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="847" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c7b6c1c6-e743-4dd8-b9c7-eea8fae02e90">

log：[run.log](https://github.com/matrixorigin/matrixone/files/12531227/run.log)

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6079234459

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by qingxinhome** [comment]
in processing

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @daviszhen @sukki37

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
