### ISSUE TITLE
[Tech Request]: mo_tables, mo_columns and mo_databases need  to be persisted

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#11650]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
The current swipe commands for these three tables are not pushed to cn via logtail, which can cause the data from these three tables to remain ungc. (Scenarios such as running bvt in a loop are oom because of this)
```

### Describe the feature you'd like

Regardless of the means used, push swipe commands or otherwise, you need to keep the size of these three tables under control.

**Comment by XuPeng-SH** [comment]
depends on #15431

**Comment by XuPeng-SH** [comment]
done
