### ISSUE TITLE
[Bug]: sometimes client can not get valid connection from mo 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11670]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 2b2e85e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/matrixone/actions/runs/6092487384/job/16530728327

<img width="1383" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ca4afd7e-8370-4c22-aad4-930b7450932b">

The mo log can be get from loki by namespace:**mo-checkin-regression-11657**
http://abb38738d9c5441738d2e8e3854fe740-1814584411.us-west-2.elb.amazonaws.com/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-11657%5C%22,%20pod%3D%5C%22mo-checkin-regression-tp-cn-82zw8%5C%22%7D%20%7C%3D%20%6004:29:00%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D

there are lots of error in cn:
<img width="1386" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/deafaf87-7e37-4604-b1de-db44a4d8d826">

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by zhangxu19830126** [comment]
还在继续分析。找得到了一些问题

**Comment by zhangxu19830126** [comment]
fixed by #11750

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
经过几天的观察，没有在出现CN不重启的情况下，在发生hung的情况，该问题可以关闭
