### ISSUE TITLE
[Bug]: inserting data error for no such table sbtest.sbtestx but table has been created succeeded.(ocassionally)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11672]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1a8dd32
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6087045352/job/16514933531

<img width="1413" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/30073dca-621b-4d59-b41c-e83bf2848e59">

log can be get from loki by namespace: **mo-nightly-regression-20230905**
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230905%5C%22%7D%20%7C%3D%20%60sbtest.sbtest10%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221693905251429%22,%22to%22:%221693991651429%22%7D%7D

**Comment by ouyuanning** [comment]
not working on it

**Comment by jensenojs** [comment]
和 https://github.com/matrixorigin/matrixone/issues/10220 会不会是同一个问题？要看看

**Comment by jensenojs** [comment]
not process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
改parser

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存

**Comment by jensenojs** [comment]
处理内存....

**Comment by jensenojs** [comment]
还在处理内存

**Comment by jensenojs** [comment]
无进展

**Comment by aressu1985** [comment]
dup with #11917, this closed
