### ISSUE TITLE
[Bug]: sql: expected 2 arguments, got 3

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixone#11687]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1.0.0-rc1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "root:111@tcp(192.168.110.224:6001)/mo_demo")
	if err != nil {
		fmt.Printf("open database failed: err[%v]", err)
		return
	}

	_, err = db.Query("INSERT INTO m_user SET m_id=?, m_name=? ON DUPLICATE KEY UPDATE m_name=?;", 111, "aaaa", "bbbb")
	if err != nil {
		fmt.Printf("select failed: err[%v]", err)
		return
	}
}

**Comment by sukki37** [comment]
@xuanyiLee could you provide the schema of `m_user`

**Comment by xuanyiLee** [comment]
> @xuanyiLee could you provide the schema of `m_user`

CREATE TABLE `m_user` (
`m_id` INT NOT NULL,
`m_name` CHAR(25) NOT NULL
);

**Comment by xuanyiLee** [comment]
> @xuanyiLee could you provide the schema of `m_user`

CREATE TABLE `m_user` (
`m_id` INT NOT NULL,
`m_name` CHAR(25) NOT NULL
)

**Comment by daviszhen** [comment]
@YANGGMM 帮看下

**Comment by fengttt** [comment]
Support prepare param is the right thing to do.   However, for this case, the m_user table does not have a primary key so what on duplicate key mean?    What is the expected behavior?   Should the statement fail at parser/algebra, with a  clear error message of no primary key, or we will simply treat the on duplicate key update as loop?

**Comment by YANGGMM** [comment]
fixed, plz confirm
