### ISSUE TITLE
[Feature Request]: Support for Slice() in VECTOR

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#11681]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

We should support `Slice(vec, startIdx, endIdx)` function.

Since MO currently doesn't support ARRAY (just like Postgres), we cannot have this syntax.
https://stackoverflow.com/questions/32793871/how-do-i-select-a-subset-of-an-array-in-postgres

```sql
=> select (array[1,2,3,4,5,6])[2:5];

   array   
-----------
 {2,3,4,5}

```

**Comment by arjunsk** [comment]
Working on this.

**Comment by arjunsk** [comment]
Document for the Fn: 

【企微文档】New Vector Functions
https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkJ6a7eBUlRxeXAFuFb3?scode=AJsA6gc3AA8jd39V6RAawAhAZmAIk

**Comment by arjunsk** [comment]
This function is merged to master. https://github.com/matrixorigin/matrixone/pull/14048

**Comment by heni02** [comment]
bvt case done，还需测试大数据量场景

**Comment by heni02** [comment]
testdone
