### ISSUE TITLE
[Bug]: tpcc 100w 500t test on 128 in daily regression hung.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11685]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1b61ec9298828e03c8de51ea71286539fe79f578
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6099510585/job/16551963651

<img width="1371" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/10ec9c9e-b049-48f7-ab59-650c3ba30053">

log： [log-3.zip](https://github.com/matrixorigin/matrixone/files/12544337/log-3.zip)

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/11024 be fixed

**Comment by ouyuanning** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/11024 be fixed

**Comment by ouyuanning** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/11024 be fixed

**Comment by ouyuanning** [comment]
等11024处理完之后再测试看看吧

**Comment by ouyuanning** [comment]
@Ariznawlll 
看有空帮忙再测看看。11024有解决了蛮多hung类的问题

**Comment by Ariznawlll** [comment]
降级观察一段时间..

**Comment by Ariznawlll** [comment]
Never appeared again.
