### ISSUE TITLE
[Subtask]: provide the interface for getting lock or txn info 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11706]
### Parent Issue

#11499 

### Detail of Subtask

from doc:

https://github.com/daviszhen/docs/blob/0907-system-view/design/system_view.md

**Comment by daviszhen** [comment]
原始的 https://github.com/matrixorigin/matrixone/issues/11499 是p-1的

**Comment by zhangxu19830126** [comment]
done

**Comment by daviszhen** [comment]
还缺一个提供事务信息的接口

**Comment by daviszhen** [comment]
用替换 #11899
