### ISSUE TITLE
[Bug]: tpcc test on nightly- regression reported 'District for W_ID  and D_ID NOT FOUND'

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11703]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 449399ba708da451d77436b690b345aadf88d1e5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1375" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/443c3cd3-7ca3-499e-83aa-9e84222dd29e">

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6112077299/job/16588979143

**Comment by ouyuanning** [comment]
same as #11024

**Comment by ouyuanning** [comment]
same as https://github.com/matrixorigin/matrixone/issues/11024

**Comment by ouyuanning** [comment]
waiting for #11024 be fixed

**Comment by ouyuanning** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/11024 be fixed

**Comment by ouyuanning** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/11024 be fixed

**Comment by ouyuanning** [comment]
waiting for #11024 be fixed

**Comment by ouyuanning** [comment]
waiting for https://github.com/matrixorigin/matrixone/issues/11024 be fixed

**Comment by zhangxu19830126** [comment]
目前前定位到是block筛选或者读数据有问题，请 @triump2020 继续跟进

**Comment by triump2020** [comment]
![1695365343185](https://github.com/matrixorigin/matrixone/assets/63033222/ad12e7a2-2906-4142-8c05-92caab4ceefe)

caused by the above code

**Comment by triump2020** [comment]
已经定位到 是由BF 引起的bug,  正在check BF 写的问题 。  @LeftHandCold

**Comment by LeftHandCold** [comment]
定位到是bf库的bug，可能需要换一个库来生成bf。

**Comment by LeftHandCold** [comment]
fixed as #11914

**Comment by Ariznawlll** [comment]
need to be confirmed by tpcc test on nightly- regression.

**Comment by Ariznawlll** [comment]
need to be confirmed by tpcc test on nightly- regression.

**Comment by Ariznawlll** [comment]
Never appeared again.
