### ISSUE TITLE
[Bug]: mo was hung on standlone mode after running tpcc 100-200 for about 6 hours

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#11701]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c4ccd3bb9e35903c922e8dc7dcdb324c11c12428
- Hardware parameters:
- OS type:ubuntu
- Others:
```

### Actual Behavior

<img width="758" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/70554816-1fe6-4c90-918d-b2221019b5a5">
<img width="1624" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/7f971143-163a-424e-8c84-24f4303fecd2">

**Comment by LeftHandCold** [comment]
[pprof.mo-service.goroutine.006.pb.gz](https://github.com/matrixorigin/matrixone/files/12555043/pprof.mo-service.goroutine.006.pb.gz)

**Comment by triump2020** [comment]
![1694143033887](https://github.com/matrixorigin/matrixone/assets/63033222/076aea18-0079-45ab-b65f-ac50b6d09f53)

![1694143112364](https://github.com/matrixorigin/matrixone/assets/63033222/8989989c-873c-4cfd-a530-225a3349e58d)


According to the panic info,  s.NodeInfo.Data  had been set to empty in some place.

**Comment by aunjgr** [comment]
not working on this today

**Comment by aunjgr** [comment]
有可能已经被 #11868 暂时修掉。看之后能否重现

**Comment by aunjgr** [comment]
@LeftHandCold 还能重现吗？
