### ISSUE TITLE
[Bug]: decimal lost the decimal point when deserializing to string

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#11705]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="857" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/a9befd54-f64f-4c1d-aae5-68ea870c2a8a">

**Comment by jensenojs** [comment]
改一下tuple的逻辑，和fuzzy filter一起修了

**Comment by jensenojs** [comment]
改tuple的结构对现有代码的改动量可能比较大。

但是在fuzzy filter做去重检测出来之后，tuple.ToSrting()或者vector.String()出来的字符串在某些特定的类型下拿出来的值是没办法放在后台SQL中用的，这在之前不是一个问题，但是在fuzzy filter可能要针对某些key做查询之后就成问题了，特别是复合key的时候，tuple在printTuple的时候对于一些类型根本就是摆烂了。

这个问题已经跟远宁哥同步了，后续要针对这个问题进行修复和编写更加详细的cases测一下，不然fuzzy filter会有问题

**Comment by ouyuanning** [comment]
@zengyan1 帮忙看一下吧

**Comment by zengyan1** [comment]
我看了下，要改确实要在tuple里面加type，但改只影响了报错的内容，我觉得意义不大，需要确认一下这个是否要做

**Comment by zengyan1** [comment]
![WX20231129-172403@2x](https://github.com/matrixorigin/matrixone/assets/93656539/98a62cb3-0859-4497-ba3a-5e683105a323)

**Comment by zengyan1** [comment]
fixed
