### ISSUE TITLE
[Feature Request]: Support arithemetic operation between Vector and Scalar operation

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#11718]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support arithmetic operation between VECTOR and SCALAR.

**Comment by arjunsk** [comment]
The main requirement for this operation was to support the normalization of a vector. That will be added in this PR: https://github.com/matrixorigin/matrixone/pull/12479

**Comment by arjunsk** [comment]
Working on this.

**Comment by arjunsk** [comment]
Document for the Fn: https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkJ6a7eBUlRxeXAFuFb3?scode=AJsA6gc3AA8hzLwXjqAawAhAZmAIk&is_external=0&commentVersion=1704753078000&doc_title=%E6%97%A0%E6%A0%87%E9%A2%98%E6%96%87%E6%A1%A3&wxworkQt=1&qt_source=Conv&qt_report_identifier=1704753080233

**Comment by arjunsk** [comment]
Document for the Fn:  [New Vector Functions.doc](https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkJ6a7eBUlRxeXAFuFb3?scode=AJsA6gc3AA8jd39V6RAawAhAZmAIk)

**Comment by arjunsk** [comment]
The changes have been merged to the master.

**Comment by heni02** [comment]
test done
