### ISSUE TITLE
[Bug]: select for update: truncate table not wait for lock 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11731]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d2167c9b4efd6e86ed37eb6b46ef5dccbfbb03d7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

truncate没有等待锁释放，需要按以下reproduce步骤才能复现
<img width="749" alt="企业微信截图_00f3f4b2-de45-4b10-892a-dc339cf4ee86" src="https://github.com/matrixorigin/matrixone/assets/113406637/57804527-5a87-4648-a010-41e2a9367c0d">
<img width="474" alt="企业微信截图_eadc2bce-3578-472f-b349-e52a757668fa" src="https://github.com/matrixorigin/matrixone/assets/113406637/2358e485-d085-4491-8d5c-ca22f6cc507e">

单独建表插入数据后truncate是等待锁的
<img width="863" alt="企业微信截图_b93e6d87-9e6d-4e25-ac6a-3f7cdfc83487" src="https://github.com/matrixorigin/matrixone/assets/113406637/bbf6601c-619e-4892-be58-bc0ee1594e72">
<img width="556" alt="企业微信截图_c00111bc-0a7b-43eb-ba16-b1bd482e8aef" src="https://github.com/matrixorigin/matrixone/assets/113406637/1907e0cd-a66f-46b6-a4de-9e8b7c397d3d">
sql：
create table su_07(c1 int not null,c2 varchar(25),c3 int,primary key(c1),unique index u1(c2));
insert into su_07 values(7,'results',20),(1,'plo',50),(3,'kelly',60),(4,'yellow',70);
begin；
select * from su_07 where c1 in(1,3,6) and c2 !='io' for update;
-- @session:id=1{
truncate table su_07;
-- @session}
commit;

### Steps to Reproduce

```Markdown
create table su_05(c1 int not null primary key,c2 varchar(25),c3 decimal(6,2))partition by key(c1)partitions 4;;
insert into  su_05 values (1,'mod',78.9),(2,'proto',0.34),(3,'mod',6.5),(4,'mode',9.0),(5,'make',662.9),(6,'io',88.92);
-- ddl partition, pk ,more rows lock
begin;
select * from su_05 where c1>3 for update;
-- @session:id=1{
use r444;
select * from su_05;
-- @wait:0:commit
update su_05 set c3=c3-1 where c1>2;
select * from su_05;
-- @session}
commit;
update su_05 set c3=c3-1 where c1>2;
select * from su_05;

begin;
select * from su_05 where c1 in(1,3,6) and c2 !='io' for update;
-- @session:id=1{
use r444;
select * from su_05;
-- @wait:0:commit
delete from su_05 where c1=1;
select * from su_05;
-- @session}
commit;

begin;
select * from su_05 where c1 in(1,3,6) and c2 !='io' for update;
-- @session:id=1{
use r444;
select * from su_05;
-- @wait:0:commit
truncate table su_05;
select * from su_05;
-- @session}
commit;
```

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm this issue

**Comment by ouyuanning** [comment]
明天看

**Comment by ouyuanning** [comment]
已复现。
是ddl语句中的lock table没有处理partition表造成的。正在处理

**Comment by heni02** [comment]
confirm,closed
commit id:75076bf8e524c58822bc1a28c56194e26e47ec1e
<img width="528" alt="企业微信截图_cb6f7d39-4acd-491a-89e8-d1f9b4690119" src="https://github.com/matrixorigin/matrixone/assets/113406637/4ee7a1a7-c4b4-4a72-be1b-35315f8b03c4">

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by heni02** [comment]
confirm tomorrow
