### ISSUE TITLE
[Feature Request]: split modump code to an independent project

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#11749]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Currently, modump code is in the main codebase, users have to build the whole MatrixOne repo source code to compile this tool.
```

### Describe the feature you'd like

Normally this kind of tool should be managed separately from the kernel code, and it has its own iteration and version control. 
And for users to use it, a simple release version should be provided from its github project. 

So we should put modump in an independent github project and strip it from the MatrixOne project.

**Comment by aronchanisme** [comment]
done

**Comment by dengn** [comment]
verified.
