### ISSUE TITLE
[Bug]: Cannot source files generated by mysqldump

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#11740]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 82d3b9dbd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Dump source files from mysql with mysqldump
```
mysqldump -h 127.0.0.1 -P23306 -u root -p mocadmin > mocadmin_meta_ali_0911.yaml
```
- Source the files to MO
```
➜ mysql -h 127.0.0.1 -P6001 -u root -p test < mocadmin_meta_ali_0911.yaml

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (HY000) at line 1: SQL parser error: Query was empty
```

### Expected Behavior

The files are sourced successfully

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

**Comment by Ariznawlll** [comment]
@daviszhen  plz help to look at this issue, thank you!

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by DanielZhangQD** [comment]
This issue blocks the migration to MO now.

**Comment by daviszhen** [comment]
周三周四开始看。

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
导出的文件中的注释。会形成一个语句发送给mo。
<img width="945" alt="image" src="https://github.com/matrixorigin/matrixone/assets/60595215/c0952225-cf3e-4a69-b2ed-f4a12c69b314">

形成的数据包。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/e9b2db03-f565-4fd0-be67-29309d2144dc)


形成的语句如下。语句被当成注释，过滤后形成了空串。报错。
现在只要搞清楚不报错时的情况，就能对比出原因。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/cc6d9e14-4308-49ff-9a18-84c299fd885f)

报错信息呢

![image](https://github.com/matrixorigin/matrixone/assets/60595215/6193f1bb-63a1-4622-a1d8-1171cf48f54d)

**Comment by daviszhen** [comment]
原因是mo对于注释的处理不同于mysql。
1，mo 的parser 将注释过滤掉后，语句本身就剩空串。此时解析不出任何语句。parser报错。
2，mysql 缺不报错。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/f9fd3e9b-853b-47cc-8a45-96a9f5892452)

**Comment by daviszhen** [comment]
pr中。

**Comment by daviszhen** [comment]
it was fixed at #11885

**Comment by DanielZhangQD** [comment]
To be verified

**Comment by DanielZhangQD** [comment]
Verified and passed with commit `6b2d02290`.
