### ISSUE TITLE
[Bug]: INSERT failed when values contain 0xFFFFF

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1175]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6b7d54b64e357f79f1b75d6fc1842a6d3ff5d990
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

rop table if exists t1;
create table t1 (a bigint unsigned not null, primary key(a));
insert into t1 values (18446744073709551615), (0xFFFFFFFFFFFFFFFE), (18446744073709551613), (18446744073709551612);
ERROR 1064 (42000): syntax error at position 66 near '0xFFFFFFFFFFFFFFFE' --- Check the SQL syntax or the manual that corresponds to your MatrixOne server version for the right syntax to use

### Expected Behavior

Query OK, 4 rows affected (0.00 sec)

**Comment by iamlinjunhong** [comment]
Not support the define of primary key(a) in main branch, but in factor branch.
Focus this issue, we just use followed cmds:

create table t1 (a bigint unsigned not null);
insert into t1 values (18446744073709551615), (0xFFFFFFFFFFFFFFFE), (18446744073709551613), (18446744073709551612);

Now behavior:

mysql> create table t1 (a bigint unsigned not null);
Query OK, 0 rows affected (0.33 sec)

mysql> insert into t1 values (18446744073709551615), (0xFFFFFFFFFFFFFFFE), (18446744073709551613), (18446744073709551612);
Query OK, 4 rows affected (0.06 sec)

mysql> select * from t1;
+----------------------+
| a                                     |
+----------------------+
| 18446744073709551615 |
| 18446744073709551614 |
| 18446744073709551613 |
| 18446744073709551612 |
+----------------------+
4 rows in set (0.00 sec)
