### ISSUE TITLE
[Bug]: Load tpcc 500w data on tke shows 'internal error: convert go error to mo error request canceled'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11754]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 82d3b9dbd0090aa94e5154b3b5ff6afa71dab24c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1541" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a9f20c4d-04b6-4c9d-9da0-ca3a2cc31324">

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6162022983/job/16724780469

log：http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230912%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

**Appears unsteadily！**

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看
