### ISSUE TITLE
[Bug]: [0914] OLTP Random_points test on 128 out of memory.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11768]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 82d3b9dbd0090aa94e5154b3b5ff6afa71dab24c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6174940103/job/16760793195

FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
FATAL: mysql_drv_query() returned error 20101 (internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1098
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/p) for query '        SELECT id, k, c, pad
          FROM sbtest1
          WHERE k IN (74502, 74498, 74501, 74505, 74499, 74502, 74505, 74500, 74498, 74504)
        '
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 20101, state = 'HY000': internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1098
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/p
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
(last message repeated 1 times)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
(last message repeated 1 times)
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: mysql_drv_query() returned error 20101 (internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1098
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/p) for query '        SELECT id, k, c, pad
          FROM sbtest1
          WHERE k IN (56502, 56500, 56500, 56505, 56498, 56498, 56503, 56500, 56499, 56504)
        '
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
(last message repeated 2 times)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
(last message repeated 1 times)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = [201](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6174940103/job/16760793195#step:18:202)01, state = 'HY000': internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1098
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/p
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
(last message repeated 1 times)
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
FATAL: mysql_store_result() returned error 3015 (error: out of memory)
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 3015, state = 'HY000': error: out of memory
Error: Process completed with exit code 1.

**Comment by m-schen** [comment]
从issue贴的日志里只能看出来空指针的panic.  `ConstantFold`方法的类型断言处空指针。

out of memory需要更详细的信息，例如内存值是否有监控，是突然暴涨还是稳步上涨最终oom。

**Comment by Ariznawlll** [comment]
128上手动执行暂未复现，暂未拿到日志，获取到日志会及时更新在这里。

**Comment by Ariznawlll** [comment]
已复现，mo日志如下：

**Comment by Ariznawlll** [comment]
已复现，日志如下：
[test.log.zip](https://github.com/matrixorigin/matrixone/files/12616325/test.log.zip)

**Comment by m-schen** [comment]
日志是有mo正在执行，启动失败的日志，需要重新复现一下。

**Comment by Ariznawlll** [comment]
内存信息log：[resr.txt](https://github.com/matrixorigin/matrixone/files/12656266/resr.txt)
mo日志：[test.txt](https://github.com/matrixorigin/matrixone/files/12656269/test.txt)

**Comment by Ariznawlll** [comment]
已复现：
内存信息：[resr.txt](https://github.com/matrixorigin/matrixone/files/12656276/resr.txt)
mo日志：[test.txt](https://github.com/matrixorigin/matrixone/files/12656282/test.txt)

**Comment by m-schen** [comment]
该oom的错误由mpool主动抛出。

(抛出条件为：当global current bytes > 1 tb时），从日志文件里的global new high watermark可以佐证这一点，current bytes基本呈线性增长，当刚好超过 1tb 时服务便报错退出。
从resr文件里可以看到从mo启动到最终报错oom, 内存峰值约为8gb。

我认为并没有真正发生了oom，而是mo关于内存从mpool中申请和释放出现了问题。
因为从mpool申请本质上是调用的make方法，而有些内存没有主动调用free方法，或者引用计数维护得不对，调用了却因为引用计数不等于1而没有被统计。因此mpool所统计的 current bytes越来越大，最终导致超过limit报错而主动退出。

**Comment by m-schen** [comment]
> 该oom的错误由mpool主动抛出。
> 
> (抛出条件为：当global current bytes > 1 tb时），从日志文件里的global new high watermark可以佐证这一点，current bytes基本呈线性增长，当刚好超过 1tb 时服务便报错退出。 从resr文件里可以看到从mo启动到最终报错oom, 内存峰值约为8gb。
> 
> 我认为并没有真正发生了oom，而是mo关于内存从mpool中申请和释放出现了问题。 因为从mpool申请本质上是调用的make方法，而有些内存没有主动调用free方法，或者引用计数维护得不对，调用了却因为引用计数不等于1而没有被统计。因此mpool所统计的 current bytes越来越大，最终导致后续查询都报超过limit的错误。
> 
> 应该是后续测试的所有语句都报错导致测试停止。上一次评论的主动退出mo是不对的。

是mo主动panic的。存储调用mpool方法拿到错误时会panic。

**Comment by m-schen** [comment]
目前存在内存没有被主动调用mpool free的地方有两个，一个是new hash map时为raw data[0]预分配的内存。
一个是通过mpool本身的grow方法所调用到的allocate。

第一个不是大头，消除后仍旧会出错。第二个正在跟踪。

**Comment by m-schen** [comment]
mpool自身统计逻辑有问题，至少存在以下两个问题：
1. 分配时统计的是传入数字的大小，而不是真正开辟的内存大小。
2. 内存重分配时，如果在原先开辟的容量以内，内存大小不会更新。

不知道有没有什么影响。需要修改这两块逻辑看一下。
目前在我的分支上新增了free的情况，已基本确定开辟的内存都会进行释放。

**Comment by m-schen** [comment]
still working on it. need more time.

**Comment by m-schen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/59043531/2ec66453-5a54-4569-b392-8482efcc950f)
与这段代码有关，但不知道为什么。mpool可能并发起来有问题。

**Comment by m-schen** [comment]
目前已知存在pool泄漏的地方有两个，一个是算子间send receive时对管道数据的漏清理，已修复未提交。
一个是prepare语法，每次会稳定泄漏prepare的batch的大小。
一个与process池子有关，暂未定位到具体情况。

**Comment by m-schen** [comment]
修复了一部分计数上的泄漏问题，但还有已知问题，后续由issue
https://github.com/matrixorigin/matrixone/issues/11928
进行追踪。

**Comment by m-schen** [comment]
main分支貌似因为查问题冻结了，今天不一定能合并进去。

**Comment by m-schen** [comment]
pr已合并，可验证或者观察几天～～

**Comment by Ariznawlll** [comment]
need to be confirmed by daily regression.

**Comment by Ariznawlll** [comment]
need to be confirmed by daily regression.

**Comment by loveRhythm1990** [comment]
I also found an `out of memory` panic today,  which causes CN restart, is this a same issue?

```
{"level":"ERROR","time":"2023/09/30 14:59:49.421504 +0000","caller":"mpool/mpool.go:545","msg":"error: error: out of memory"}
panic: error: out of memory

goroutine 1352890 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*SessionAllocator).Alloc(0xc02150dab0?, 0x0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/types.go:240 +0x45
github.com/fagongzi/goetty/v2/buf.(*ByteBuf).Grow(0xc1364b32c0, 0xc02150dae0?)
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/buf/buf.go:450 +0x85
github.com/fagongzi/goetty/v2/buf.(*ByteBuf).ReadFrom(0xc1364b32c0, {0x3557ec0, 0xc10abb3850})
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/buf/buf.go:507 +0x3f
io.copyBuffer({0x3553ee0, 0xc1364b32c0}, {0x3557ec0, 0xc10abb3850}, {0xc01b3e0000, 0x400, 0x400})
        /usr/local/go/src/io/io.go:413 +0x14b
io.CopyBuffer({0x3553ee0?, 0xc1364b32c0?}, {0x3557ec0?, 0xc10abb3850?}, {0xc01b3e0000?, 0x2?, 0xc02150dc50?})
        /usr/local/go/src/io/io.go:400 +0x3c
github.com/fagongzi/goetty/v2.(*baseIO).readFromConn(0xc0137fd200, 0xc1364b32c0?)
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/session.go:502 +0xd2
github.com/fagongzi/goetty/v2.(*baseIO).Read(0xc0137fd200, {0xc0137fd200?})
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/session.go:417 +0xba
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc00a816320, {0x35ad440, 0xc0137fd200})
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:365 +0x22f
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
        /go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20230811091418-ff72333eabdc/application.go:336 +0x485
```

following is a part of log, full log is too large(75M), and can ask me for help if necessary
[cn-out-of-mem.txt](https://github.com/matrixorigin/matrixone/files/12774986/cn-out-of-mem.txt)

**Comment by Ariznawlll** [comment]
I'll assign it to mingsong to look at it when he comes back from leave.

**Comment by daviszhen** [comment]
今天还没看

**Comment by m-schen** [comment]
今日无进度

**Comment by m-schen** [comment]
没啥进展今天

**Comment by Ariznawlll** [comment]
Verified!
