### ISSUE TITLE
[Feature Request]: proxy could identify if the connection is from internal or external network

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#11761]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Add a new config in proxy to help it identify if the connection is from internal or external network. If the source IP is internal, set flag of the connection to CN node. Otherwise, connections are external network.

**Comment by volgariver6** [comment]
done

**Comment by DanielZhangQD** [comment]
@aressu1985 To be verified

**Comment by heni02** [comment]
proxy配置网段参数
[proxy]
internal-cidrs = "192.168.0.0/24"

**Comment by heni02** [comment]
测试场景：
1.eks分布式部署，proxy配置内网 internal-cidrs = ["10.0.0.0/16"]，下发sql，验证type为1私网，符合预期
<img width="996" alt="企业微信截图_ad4bf81e-9e0f-438d-8337-1d5de12b9135" src="https://github.com/matrixorigin/matrixone/assets/113406637/13847c8d-3241-4c0c-bf8e-8e62f10e32db">
<img width="909" alt="企业微信截图_aa01129b-6e7f-4ab5-914d-25b6095532b2" src="https://github.com/matrixorigin/matrixone/assets/113406637/dc4c0dc5-ad54-4fa9-a217-23c7fc009e9e">
<img width="1417" alt="企业微信截图_3c30fbab-099a-4ced-936c-457e9b44b181" src="https://github.com/matrixorigin/matrixone/assets/113406637/c8274efc-609e-47c1-836e-d50d27d56224">

2.eks分布式部署，proxy配置内网 internal-cidrs = ["192.168.0.0/24"]，下发sql，验证type为2公网，符合预期
<img width="1058" alt="企业微信截图_192305ea-356f-436c-b70a-2f2dddd35772" src="https://github.com/matrixorigin/matrixone/assets/113406637/e3d1e682-dbaa-4801-a389-570010fb8dc2">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6b2bb840-bf14-4e4e-a565-16be3af16706)

3.eks分布式部署，proxy未配置internal-cidrs ，下发sql，验证type为2公网，符合预期？
<img width="735" alt="企业微信截图_24619190-0d30-43b2-ba1b-fea3f1fd54e8" src="https://github.com/matrixorigin/matrixone/assets/113406637/7e86d602-685a-4bd3-86b4-389736366581">
<img width="1422" alt="企业微信截图_800f65b0-ecb8-4b4e-8516-55f67daa8b35" src="https://github.com/matrixorigin/matrixone/assets/113406637/259c806a-1a45-46e4-8eb2-ceddb2c18038">

**Comment by heni02** [comment]
test done

**Comment by xzxiong** [comment]
varified
