### ISSUE TITLE
[Tech Request]: parallelism information in explain analyze

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11779]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
In explain analyze output, report pipeline parallelism.   How many pipelines is running this operator, the min/max/avg of each stats like time, number of rows, etc.
```

### Why is this needed ?

To find the non parallelable operator/bottleneck, and skew.

**Comment by badboynt1** [comment]
fixed
