### ISSUE TITLE
[Bug]: Pessimistic mode: select * from table shows internal error: panic unexpect type ANY for function vector.GetUnionOneFunction.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11774]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1bd75d8cb012cf2c01d0e3e7f6bd1e4019c9afd1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1420" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/30ab9c6e-1044-460d-a310-55dae42a7665">

### Expected Behavior

select * from table execute success!

### Steps to Reproduce

```Markdown
drop table if exists alter01;
create table alter01(col1 int primary key, col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");
begin;
alter table alter01 rename column col1 to col1New;
-- @session:id=1{
-- @wait:0:commit
use transaction_enhance;
insert into alter01 values (8,"h");
select * from alter01;
-- @session
insert into alter01 values (6,"h");
select * from alter01;
```

**Comment by m-schen** [comment]
复现步骤的更正：
session2在执行insert前需要先select * from alter01;
```
session1 : 
drop table if exists alter01;
create table alter01(col1 int primary key, col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");
begin;
alter table alter01 rename column col1 to col1New;

session2:
select * from alter01;
insert into alter01 values (8,"h");
此时会卡住，直到session1进行commit;

session1:
commit;

session2:
select * from alter01;
```

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by YANGGMM** [comment]
<img width="1207" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/83a3419f-cb4f-40cb-94d4-2eff14a8e93e">

**Comment by YANGGMM** [comment]
alter view 也会出现这样的问题
<img width="428" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/c790b597-5c26-421b-bd31-c67b641c38cd">

**Comment by YANGGMM** [comment]
【session1】 : 
drop table if exists alter01;
create table alter01(col1 int primary key, col2 varchar(25));
insert into alter01 values (3,"a"),(4,"b"),(5,"c");

【session2】:
select * from alter01;

【session1】:
alter table alter01 rename column col1 to col1New;

【session2】:
select * from alter01;
此时会报panic。

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
Verified!

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by Ariznawlll** [comment]
Verified!
