### ISSUE TITLE
[Bug]: batch management, ERROR 20101 (HY000): internal error: Invalid alloc size 1147486208

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> create table t (i int, t text);

mysql> insert into t select result, repeat('foobarzoo', result) t from generate_series(1, 1000000) t;
ERROR 20101 (HY000): internal error: Invalid alloc size 1147486208

mysql> explain select result, repeat('foobarzoo', result) t from generate_series(1, 1000000) t;
+-----------------------------------------+
| QUERY PLAN                              |
+-----------------------------------------+
| Project                                 |
|   ->  Table Function on generate_series |
|         ->  Values Scan "*VALUES*"      |
+-----------------------------------------+
3 rows in set (0.00 sec)
```

**Comment by fengttt** [comment]
Maybe the same as #11719 

This one is not join.   A simple batch management issue.

**Comment by fengttt** [comment]
Another, 
```
create table t (i int, t text);
insert into t select result, 'foo' || result from generate_series(1, 100000) t;

mysql> select * from (select * from t limit 10000) t1, (select * from t limit 10000) t2;
ERROR 20101 (HY000): internal error: Invalid alloc size 1147486208
```

Look at the code, it simply cannot handle this.   need to have #10729

**Comment by aunjgr** [comment]
This one is different from those join/cte issues. The minimal query to fail is

```sql
select result, repeat('foobarzoo', result) from generate_series(1, 15000) t limit 100;
```

That's because the last batch generated by the table function has approximately 15k * 9 * 8k = 1080M bytes, which surpasses our 1GB hard limit.

**Comment by DanielZhangQD** [comment]
Hit this issue with the following case:
In a transaction, insert 1000 records each time and may insert several times depending on the total number of the records, the record is just something like `('3ae6c912-61f4-11ee-ac82-eeab67a4d8c2','b6011b4d_75b2_4458_875c_42f6dd16d927','2023-10-03 13:53:28.319','0',9000001)`, it's weird that it succeeds some times.
It has the same behavior when I change the batch size from 1000 to 500 or 300.
It works well until 2023-10-03 13:53:00.000 UTC.

**Comment by DanielZhangQD** [comment]
> Hit this issue with the following case: In a transaction, insert 1000 records each time and may insert several times depending on the total number of the records, the record is just something like `('3ae6c912-61f4-11ee-ac82-eeab67a4d8c2','b6011b4d_75b2_4458_875c_42f6dd16d927','2023-10-03 13:53:28.319','0',9000001)`, it's weird that it succeeds some times. It has the same behavior when I change the batch size from 1000 to 500 or 300. It works well until 2023-10-03 13:53:00.000 UTC.

It seems that the size limitation is for all the records in the same transaction so that the previous `insert` seems to succeed but the final transaction fails.

**Comment by ouyuanning** [comment]
重构后要修改：
1、table_function 产生的batch要切割
2、所有阻塞类的算子，他们汇聚的数据也要切割
才能保证每次传递下去的数据是8192行的。

先等重构完成后再挨个修改吧

**Comment by ouyuanning** [comment]
等pipeline重构结束后再处理

**Comment by ouyuanning** [comment]
on duplicate key应该也存在这个问题。它也没有对batch进行切割。
但是on duplicate key需要等所有数据都探测结束后才知道结果。有可能要等龙冉的spill做完后复用对应的代码

**Comment by ouyuanning** [comment]
等重构结束后处理

**Comment by ouyuanning** [comment]
等重构结束后处理

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
deps https://github.com/matrixorigin/matrixone/issues/12121

**Comment by ouyuanning** [comment]
可能存在以下几种情况
1、table function没有做切割   
2、table function切割了。比如按8192切了，但是，这不到8192的行，还是爆了
    比如：  select result, repeat('foobarzoo', result) t from generate_series(999000, 1000000) t;
    因为repeat 函数申请的内存很多。这个batch只有1000行也会爆
3、非阻塞类的join，单次probe就爆了。
     select * from (select * from t limit 10000) t1, (select * from t limit 10000) t2;
4、阻塞类算子，会一直持有上游发过来的数据。如果数据量大就会爆。比如
      select * from big_big_table for update   【lock算子会持有这个数据，会爆掉】

1和3我会处理掉。
2的部分得仔细讨论
4的部分预计要龙冉的spill完成后，再做对应处理

**Comment by ouyuanning** [comment]
对以下的情况做了切割：
1、generate_series 是int的情况
2、product算子（select * from a,b 这类join）
基本覆盖了本issue的部分情况：
```
insert into t select result, repeat('foobarzoo', 200) t from generate_series(1, 1000000) t;  //这种已ok，切割后不会爆

insert into t select result, repeat('foobarzoo', result) t from generate_series(1, 1000000) t;  //这种没办法，因为repeat函数单列就非常大，最后的那个batch，不到1000行就爆了

create table t (i int, t text);
insert into t select result, 'foo' || result from generate_series(1, 100000) t;
select * from (select * from t limit 10000) t1, (select * from t limit 10000) t2;  //这种已ok
```


其他可能还可以切割的算子，在这里继续跟踪：
https://github.com/matrixorigin/matrixone/issues/12121
（目前看到的还有loop join类几个算子，应该可以切割。我会留给实习同学练手）

另外对于即使切割到8192行以内，内存依然爆掉的情况。建了一个issue跟踪
https://github.com/matrixorigin/matrixone/issues/12685
