### ISSUE TITLE
[Bug]: SELECT failed when column with operators

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1180]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6b7d54b64e357f79f1b75d6fc1842a6d3ff5d990
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t_bigint(id BIGINT);
INSERT INTO t_bigint VALUES (1), (2);
SELECT id, id >= 1.1 FROM t_bigint;
ERROR 1105 (HY000): unknown error:RunWhileSend : unsupported type 200

### Expected Behavior

+------+-----------+
| id   | id >= 1.1 |
+------+-----------+
|    1 |         0 |
|    2 |         1 |
+------+-----------+

**Comment by JinHai-CN** [comment]
Projection can't support logical expression, currently.

**Comment by m-schen** [comment]
it is same to #1077 
can not support logical expression likes `< > >= <= = != like` in select clause.
