### ISSUE TITLE
[Bug]: fix statement trace

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#11803]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Currently, the context of the statement is lost during execution, and it can not trace the statement correctly.

**Comment by gouhongshen** [comment]
fixed by #11932
