### ISSUE TITLE
[Bug]: ci test occurs internal error: panic interface conversion.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11813]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): branch:Lhttps://github.com/Ariznawlll/matrixone/tree/removeBvtTag
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1068" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6ce21a96-0186-40d4-aa26-39f8b44a1823">

job url：https://github.com/matrixorigin/matrixone/actions/runs/6219691010/job/16878239818?pr=11777

log：[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/12645937/multi-cn-e2e-push-docker-compose-log.zip)

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it
