### ISSUE TITLE
[Bug]: Latins cannot be displayed

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1181]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6b7d54b64e357f79f1b75d6fc1842a6d3ff5d990
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t1;
create table t1 (name char(20) not null primary key ) charset latin1;
insert into t1 values ("å");
insert into t1 values ("ä");
insert into t1 values ("ö");
select * from t1 order by name;
+------+
| name |
+------+
|      |
|      |
|      |
+------+

### Expected Behavior

+------+
| name |
+------+
| å    |
| ä    |
| ö    |
+------+

**Comment by jiangxinmeng1** [comment]
can't reproduce
