### ISSUE TITLE
[Bug]: ci bvt case failed. `Duplicate entry '(10,eeeeee)' for key '__mo_cpkey_col'`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#11814]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):780fd76740321849af4c86ec2907ddcdbaaa4405
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/aa4ba489-fc70-42d9-b9ef-c4a64788b043)

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
triggered by my pr.

https://github.com/matrixorigin/matrixone/pull/11792

mycode:
https://github.com/daviszhen/matrixone/tree/0914-mo-confis
```

**Comment by daviszhen** [comment]
在我的pr上，几乎是必现，阻碍了ci。

**Comment by daviszhen** [comment]
我的pr 就加了个table function 。不涉及存储，计算的复杂逻辑。

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/6219813165/job/16878605169?pr=11792

https://github.com/matrixorigin/matrixone/actions/runs/6219813171/job/16879251872?pr=11792

**Comment by aunjgr** [comment]
乐观事务，按理说不应该在commit之前报错？

@zhangxu19830126 帮忙先看看，多谢！

**Comment by ouyuanning** [comment]
pkg/cnservice/types.go  的SetDefaultValue 方法中
有重新设置了一遍CN端的 PK 去重的配置  plan.CNPrimaryCheck = true。 所以打开了cn端的去重。

删掉 SetDefaultValueo 中关于更新  plan.CNPrimaryCheck 的 498到502行代码。测试会没有问题。

建议同时删掉  505 到513 行代码中关于设置 frontend 的代码

**Comment by daviszhen** [comment]
错误的设置了 全局变量 plan.CNPrimaryCheck = true
