### ISSUE TITLE
[Subtask]: Improve Operator Communication in Pipeline

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11824]
### Parent Issue

#10729 

### Detail of Subtask

This issue is focused on enhancing the communication between operators, a vital aspect of the pipeline, to support both local and cross-node communication.

### Describe implementation you've considered

As mentioned in the [design doc](https://github.com/matrixorigin/docs/blob/fengttt-docs/tech-notes/sql/pipeline/pipeline2.md), the goal is to implement out-of-band messages for scenarios such as runtime filter push down, limit and early stop, and threshold update messages. One way to implement this goal is that each operator in execution should have an ID that can be used as its mailbox address. A Message struct should be used for sending data through the messaging channel. The data in the message is the serialization of a batch and can be reinterpreted as a batch. This will enable efficient communication between operators, both locally and across different nodes.

**Comment by daviszhen** [comment]
可能要降级。
