### ISSUE TITLE
[Bug]: mo hung after restart one cn or dn on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11838]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):40fd765
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when running sysbench insert cases on distributed mo, if one of cn pod was killed and ,the mo will be hung.
<img width="572" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3337b91d-3200-4196-be67-9845ac82f440">
<img width="1084" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/c5190185-91fc-4571-93aa-488893368312">

the profile(cpu,heap,gorotine,trace) is:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/12658750/profile.tar.gz)
[cn1.log](https://github.com/matrixorigin/matrixone/files/12658774/cn1.log)
[cn.log](https://github.com/matrixorigin/matrixone/files/12658776/cn.log)
.

### Steps to Reproduce

```Markdown
1. run a mo distributed mo
2. run sysbench insert 10-100000 100 threads test
3. kill cn pod for serval times
```

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
分析原因是，有2个cn，其中cn0挂了，cn1有一些rpc已经完成请求的发送，在等待响应，一直等到ctx超时，但是目前的超时时间是24小时，所以这里卡住了。

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by volgariver6** [comment]
I will take this one.

**Comment by volgariver6** [comment]
在eks环境上复现，抓了一些数据：

[goroutine-173836.log](https://github.com/matrixorigin/matrixone/files/12700013/goroutine-173836.log)

[trace-172436.txt](https://github.com/matrixorigin/matrixone/files/12700015/trace-172436.txt)

新的连接登录时卡的位置在 `pkg/txn/client/timestamp_waiter.go:180`，但是导致卡住的原因还没有找到。

**Comment by volgariver6** [comment]
现在怀疑是RPC的问题，还在加日志排查问题，目前还没有定位到准确的原因。

**Comment by volgariver6** [comment]
probably fixed by #11920

**Comment by volgariver6** [comment]
问题依然存在，继续看一下

**Comment by volgariver6** [comment]
现在重现的过程中经常会遇到别的问题，阻塞本问题的分析，尤其 “cn restart due to: BUG: StartStatement called twice”这个比较多，等 #11858 修复再继续看吧

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
等https://github.com/matrixorigin/matrixone/issues/11858修复

**Comment by volgariver6** [comment]
等待其他问题进展

**Comment by sukki37** [comment]
Not repro for a few days, downgrade for further observation.

**Comment by aressu1985** [comment]
update on 10.16 
after restart dn , the mo was hung

[Uploading hung-profile.tar.gz…]()

**Comment by volgariver6** [comment]
在 eks 上试了很多次，重启dn，没有复现

**Comment by volgariver6** [comment]
没有进展

**Comment by volgariver6** [comment]
没有进展

**Comment by volgariver6** [comment]
fixed.

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
still exists in commit: c5eba48

**Comment by volgariver6** [comment]
问题的原因应该是tn刚重启又发生重启，导致cn重连还没完成，又重连了一次，导致logtail consumer 不能正常工作。正在做logtail consmer重构来修复该问题。

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
