### ISSUE TITLE
[Bug]: Install protoc-gen-gogofaster automatically

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#11831]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

#11210 introduced protoc-gen-gogofaster, which makes `make pb` fail.

The 3rd-party tool should be installed automatically, just like previously used protoc-gen-gogofast.

**Comment by volgariver6** [comment]
fixed
