### ISSUE TITLE
[Bug]: Tke regression test: load data report error 'lock table bind changed'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11835]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6ee7721126f7799b15252cc1714e0d6fc86b5678
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6225095503/job/16905562846
<img width="1440" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/79796958-21a2-49ba-823a-6921b13948a6">

log: http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230918%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-22ftj%5C%22%7D%20%7C%3D%20%60memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

<img width="1295" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/081fcfb2-2371-48ef-a11a-1989f688b8ad">

日志中的lock table bind changed时间与load data出错时间相符，具体原因需要进一步定位。

pod status(测试期间cn有重启现象，但与报错时间不一致)：
<img width="1485" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8ae9eeda-213d-49a7-8ceb-8c30568b53ec">

**Comment by zhangxu19830126** [comment]
这个不是问题

**Comment by zhangxu19830126** [comment]
符合设计

**Comment by Ariznawlll** [comment]
to be confirmed through tke regression.
