### ISSUE TITLE
[Bug]: Executing SQL with error `lock table not found on remote lock service`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#11830]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-16d88550
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2023/09/19 06:36:03.451405 +0000 ERROR worker/controller.go:351 trace {"error": "Error 20703 (HY000): lock table not found on remote lock service\nPrevious DML conflicts with existing constraints or data format. This transaction has to be aborted", "elapsed": "2.102768ms", "rows": 0, "sql": "UPDATE `moc`.`cx_time` SET `last_time`='2023-09-14 14:22:00' WHERE cluster = 'local-endpoint.freetier-02:6001' AND `cluster` = 'local-endpoint.freetier-02:6001'"}
```

### Expected Behavior

SQL is executed successfully

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Log: http://47.97.80.230/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60lock%20table%20not%20found%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by Ariznawlll** [comment]
[0919] tke regression 'OLTP point select' has the same problem：
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6225095503/job/16906045090
<img width="1386" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/10c11008-ce61-4f7a-8d83-38620c9fbfb0">

log: http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230918%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-22ftj%5C%22%7D%20%7C%3D%20%60memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

**Comment by zhangxu19830126** [comment]
这个是lockservice的设计决定的，这个是符合设计的

**Comment by DanielZhangQD** [comment]
To be confirmed.

**Comment by DanielZhangQD** [comment]
To be confirmed.

**Comment by DanielZhangQD** [comment]
`cn 重启 hung 解决之后，rpc阻塞的问题应该就被解决了，就肯定能在10s左右发现恢复。`
