### ISSUE TITLE
[Bug]: Excessive Small Object Files Generated After Executing Delete Statement

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11856]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c6c21e0e3fc4cf99c7ad82229040a501c32b44b5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After executing the following SQLs, I observed that a large number of small object files were created(16000+, 37k each). This behavior is unexpected and could potentially lead to performance and storage management issues.

### Steps to Reproduce

```Markdown
create table t(a int);
insert into t values (1),(2);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
select count(*) from t;
delete from t where a=1;
```
```


### Additional information

_No response_

**Comment by sukki37** [comment]
Same repro steps with #11815

**Comment by sukki37** [comment]
After discussing with @LeftHandCold and @XuPeng-SH , it has been confirmed that this issue will be resolved following the optimization of the tombstone.

**Comment by triump2020** [comment]
V1.1 会Fix

**Comment by triump2020** [comment]
waitting for  V1.1 release

**Comment by triump2020** [comment]
waitting for V1.1

**Comment by XuPeng-SH** [comment]
assigned to @w-zr

**Comment by w-zr** [comment]
目前看起来是block太多，导致要写的delta_loc太多。很多文件都是delta_loc的数据，之后我会尝试把多个delta_loc写到一个文件里。

**Comment by w-zr** [comment]
可能之后需要重构一下deletion算子

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/8228db79-47e7-4ec2-9aea-8b9bf9eda57d)

在做删除时，每个block中的pk会记录成一个新的block。每个新的block在写S3时，会使用一个新的location，即图中677行所示。这会导致每个block都会写入到新的文件中。需要和罗飞沟通一下看看有没有合理的解决方法。

**Comment by w-zr** [comment]
arg.ctr.batch_size is defined as a uint32, but it was incorrectly calculated and was smaller than the actual data size. When arg.ctr.batch_size reaches a certain threshold (currently set at 32MB), the data is flushed to disk. During each flush operation, the real batch size is subtracted from `arg.ctr.batch_size`. This subtraction causes an overflow issue, causing `arg.ctr.batch_size` to become excessively large. As a result, every subsequent check to determine whether data should be flushed also triggers a flush operation, even when the actual data size is not significant. This behavior leads to the creation of a large number of small files.

**Comment by w-zr** [comment]
![企业微信截图_16986610331341](https://github.com/matrixorigin/matrixone/assets/28624654/d854c7eb-82a4-4e1f-84d4-d17842dcda32)
![企业微信截图_1698661043131](https://github.com/matrixorigin/matrixone/assets/28624654/2167ca0e-91cd-4f0c-be56-7a8a07fa4c76)

Here is the result. After deletion, there are 200+ files now.
