### ISSUE TITLE
[Bug]: CN hang during merge-run test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11851]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3ac504cdc3a0fd60493bbb35cc4dc64b0acbd498
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Due to the lack of response from the MO database, the test failed.

https://github.com/matrixorigin/matrixone/actions/runs/6245783272

some debug info： 
[mo-cluster-trace-11792.zip](https://github.com/matrixorigin/matrixone/files/12672805/mo-cluster-trace-11792.zip)

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
加了点日志，继续看

**Comment by zhangxu19830126** [comment]
dup with #11957

**Comment by zhangxu19830126** [comment]
hung in incrservice, can not read incr record.

**Comment by sukki37** [comment]
further observation in #11966
