### ISSUE TITLE
[Bug]: TKE tpch 1t test：The hot data is greater than the cold data.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#11855]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 538d92ea44e0bc9c377f6cf6f9f386744d8513b2
- Hardware parameters:
- OS type:
- Others:

- name: GOMEMLIMIT
  value: "45000MiB"

[metacache]
memory-capacity = "2GB"
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6245831468/job/16955243349

性能目标跟踪数据：https://doc.weixin.qq.com/sheet/e3_AREAuQb9AC8tOXj19g4SVOMsRCO2H?scode=AJsA6gc3AA8fVeui2vARoAIAbNAH8&tab=ep2v7i
<img width="857" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0fcc4f71-abc9-4198-bbd2-1c0dfba07ca5">

**Comment by badboynt1** [comment]
等tke环境好了再看

**Comment by badboynt1** [comment]
大概率是因为tke环境挂载的云盘吞吐量太低导致。 等tke环境重新挂载新的硬盘后再测试

**Comment by badboynt1** [comment]
等待更换机型后重新测试

**Comment by Ariznawlll** [comment]
1011:
tke test：56562ae5ec1f9638d353c35d5c48438fc9e68add
<img width="1587" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/35eb92a2-1d14-4e05-8fae-168fd7049574">
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6477240285/job/17587427090

**Comment by Ariznawlll** [comment]
**[10.11]**

tke test: 
冷数据：1538
<img width="816" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/85cc6670-3b6e-4a18-a0af-23574ff5e85c">

热数据：1235
<img width="950" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b6bf98e5-cf8b-48ec-9e00-6e42381aaa8d">

**Comment by Ariznawlll** [comment]
1012:

冷数据：
<img width="1019" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/edb8b0f4-6781-48a6-87f0-6a2d4eca1b58">

热数据：
<img width="926" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/26546891-73de-4f76-b503-2ea8f746025a">

**Comment by Ariznawlll** [comment]
Verified！
