### ISSUE TITLE
[Bug]: [date 9.20]tke regression: after dn restart, can not connect mo

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11863]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-d2a0d67
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

regression job:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6251217418/job/16982527420
<img width="1870" alt="企业微信截图_90ba3fa1-e0ce-4381-b37b-de49ba2e529c" src="https://github.com/matrixorigin/matrixone/assets/113406637/6ba3ab71-861c-4329-b0df-bd8710fa8333">
<img width="1873" alt="企业微信截图_5fe53cc5-9cd4-4bac-8539-3a8a075177ce" src="https://github.com/matrixorigin/matrixone/assets/113406637/3ffa9737-7eeb-424b-aa82-6576bfc5febc">

check tke status, cn is not restart:
<img width="880" alt="企业微信截图_5ec2bb97-1d10-413d-85b6-af0f298d7491" src="https://github.com/matrixorigin/matrixone/assets/113406637/914927d1-3c15-4a17-8749-dea79b51cb75">

mo log:(time:2023-09-21 06:14:22 )
http://139.155.148.31:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230920%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221695248040000%22,%22to%22:%221695254399000%22%7D%7D
<img width="1794" alt="企业微信截图_52d193ca-dc6d-4dff-9b8d-88c6e23174d2" src="https://github.com/matrixorigin/matrixone/assets/113406637/d6352dbd-354f-4659-b35f-4077a901d433">
found lots of internal error: cn service is not ready, retry later

**Comment by XuPeng-SH** [comment]
assigned to @LeftHandCold

**Comment by LeftHandCold** [comment]
这个问题我之前看过可以参考https://github.com/matrixorigin/matrixone/issues/11860，重启是因为dn的lockservice/rpc出现了fatal，不能链接mo是因为dn再重启钱，cn就已经异常了。

**Comment by zhangxu19830126** [comment]
dup with #11860

**Comment by heni02** [comment]
偶现问题，最近一周回归测试无出现dn重启现象，先关闭issue
