### ISSUE TITLE
[Bug]: [date 9.26]tke regression: tpch 1T test ,cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11916]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d21d7267438bfe02c1a2446274c89c748674cf39
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke regression job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6315337506/job/17163635674
![image](https://github.com/matrixorigin/matrixone/assets/113406637/8f710c24-50f7-422b-b6ba-5cf04ec95f7c)
<img width="1152" alt="企业微信截图_4bb7e9c1-f849-4f86-b235-6781c67fd1ab" src="https://github.com/matrixorigin/matrixone/assets/113406637/3066f4a8-3dce-4802-8b13-1136bee43042">

3 cn oom：
<img width="1426" alt="企业微信截图_ed9ce733-53f4-46f2-a6a9-6a1dd7de11ec" src="https://github.com/matrixorigin/matrixone/assets/113406637/91af3d6f-f9c5-40a8-91f8-413f10190d10">

from the analysis of OOM time points, it is consistent with the failure time of TPCH 1T

loki mo log：
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230926%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by badboynt1** [comment]
oom虽然在daily里第一次出现，但是问题的根源估计不在昨晚的某个提交里。在129用更早的commit也能跑出来。
可能跟这个issue有关
https://github.com/matrixorigin/matrixone/issues/11918

**Comment by badboynt1** [comment]
已经修复，麻烦验证一下

**Comment by heni02** [comment]
confirm, closed
date 10.6 regression test :https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6433917879/job/17472639996
date 10.5 regression test : 
![image](https://github.com/matrixorigin/matrixone/assets/113406637/8b8e7c6b-8acd-45e6-a6fa-7ee0086979bf)
date 10.4 regression test:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/71ddb6cc-8eb2-4aa4-b922-06cd98e0f40e)
date 10.3 regression test:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d7d3499c-da84-4ed4-83f7-51c08dce001e)

**Comment by heni02** [comment]
date 10.13 regression test had this problem again,this issue reopen
tke regression job： https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6503218565/job/17663684388
<img width="905" alt="企业微信截图_c784ca1e-03b4-418a-aa3c-f654276d1756" src="https://github.com/matrixorigin/matrixone/assets/113406637/21ac65c1-e134-4882-8474-7b09aaee171d">
<img width="1566" alt="企业微信截图_24abb2cf-f9e9-4fd5-adb6-b92080fae444" src="https://github.com/matrixorigin/matrixone/assets/113406637/39e3e3d6-2587-4805-8f45-4fe871cd85a3">
check this time cn oom(mem limit 54Gi)
<img width="1579" alt="企业微信截图_eb7616e1-ab2b-4123-9a3f-83a0f4866399" src="https://github.com/matrixorigin/matrixone/assets/113406637/d5b3a227-793f-4a7a-a9f3-df66d115c676">

profile：
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/12890211/profile.tar.gz)

**Comment by badboynt1** [comment]
修改配置后，仍然有概率出现oom。正在分析

**Comment by badboynt1** [comment]
![企业微信截图_16975134506802](https://github.com/matrixorigin/matrixone/assets/112734932/1fb54c73-580f-4252-b49a-a7b48e7107ea)

![企业微信截图_16975148451539](https://github.com/matrixorigin/matrixone/assets/112734932/1775f1ba-24f5-49be-adf4-1a264037eed5)

出现了新的内存泄漏，tpch1T 每跑一轮大概泄漏1g多内存

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/11644  这个pr也会引起内存泄漏，需要修复

**Comment by badboynt1** [comment]
内存泄漏已修复。等daily继续观察

**Comment by heni02** [comment]
date 10.18 regression not appeared：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6563039481/job/17844393781

**Comment by heni02** [comment]
date 10.23 regression not appeared:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6620835716/job/17984546390
<img width="712" alt="企业微信截图_2d66e7fa-dd74-44d1-a6ca-f4fbb3af077d" src="https://github.com/matrixorigin/matrixone/assets/113406637/d44b56a6-f021-49f6-810a-7bf190f7b5b4">
closed this issue
