### ISSUE TITLE
[Bug]: [date 9.26] tke regression: sysbench test load table success ,but reported no such table sbtest.sbtest2

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11917]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d21d7267438bfe02c1a2446274c89c748674cf39
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke regression job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6315337506/job/17158059378
<img width="1360" alt="企业微信截图_90547b10-6ee6-4dc9-927f-44209a9d5650" src="https://github.com/matrixorigin/matrixone/assets/113406637/c36ab48c-749e-4913-b4f7-78ff324d4a90">

but login mo, sbtest2 is exists
<img width="1199" alt="企业微信截图_da645a5f-73a0-4588-85ef-011b175fdfdd" src="https://github.com/matrixorigin/matrixone/assets/113406637/d31233b6-290f-42ea-b6d4-13eb771d4261">

mo log:
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230926%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by heni02** [comment]
date 10.5 regression also appear this problem
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6408584157/job/17398203833
![image](https://github.com/matrixorigin/matrixone/assets/113406637/12fac7f1-a678-45bb-b2b5-209de35b0a1a)

**Comment by nnsgmsone** [comment]
```
{"level":"ERROR","time":"2023/10/07 13:05:53.348694 +0800","name":"log-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","connection_id":7,"statement":"create table text01 (col1 text primary key , col2 mediumtext unique index, col3 longtext);","status":"fail","error":"SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 73 near \" index, col3 longtext);\";","span":{"trace_id":"7cdc119c-b483-458f-a7e0-af5179fbdbbb","kind":"statement"},"session_info":"connectionId 7|127.0.0.1:50508|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 1479|159336d4-64cf-11ee-9d24-c6612688e3ca","session_id":"159336d4-64cf-11ee-9d24-c6612688e3ca","statement_id":"7cdc119c-b483-458f-a7e0-af5179fbdbbb"}
```
如上有一些很奇怪的Log，看着是parser报错。。确认中

**Comment by heni02** [comment]
date 10.9 repo this problem：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6459081363/job/17542564093
<img width="1397" alt="企业微信截图_9b3cb799-4112-4fdb-b661-908c532d15c4" src="https://github.com/matrixorigin/matrixone/assets/113406637/42f38d71-2f5a-463e-b2f5-4542c777f127">
plz @nnsgmsone search this time（+8hours） in log：
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231009%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221696887180000%22,%22to%22:%221696887239000%22%7D%7D

**Comment by nnsgmsone** [comment]
通过日志发现三个cn都收到了同样的ddl请求？这个测试工具的行为是否不合理呢？ @heni02

**Comment by nnsgmsone** [comment]
定位问题为cn创建了建表请求。可是dn创建的表里面没有这个表。。。
cn日志:
```
{"level":"INFO","time":"2023/10/09 21:33:24.657204 +0000","name":"cn-service.pipeline","caller":"compile/ddl.go:528","msg":"createTable","uuid":"63353064-6166-6336-6563-663131663634","databaseName":"sbtest","tableName":"sbtest6"}
```
dn日志:
```


2023-10-10 05:33:24.556 | {"level":"INFO","time":"2023/10/09 21:33:24.556522 +0000","caller":"rpc/handle.go:740","msg":"[precommit] create database: AccessInfo:<AccountID:0 UserID:1 RoleID:0 > Name:\"sbtest\" CreateSql:\"create database if not exists sbtest\" DatTyp:\"\" DatabaseId:272544  txn: ctx[FC4FBEFE9E82467890C9E70F3FAE0157][1696887204555333034-1->9223372036854775807-4294967295][Active]: <nil>"} |  
-- | -- | --
  |   | 2023-10-10 05:33:24.623 | {"level":"INFO","time":"2023/10/09 21:33:24.623489 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272618-sbtest2 txn: ctx[7123785430934BDEAC919EA4D3E107F3][1696887204618778737-1->9223372036854775807-4294967295][Active]: <nil>"} |  
  |   | 2023-10-10 05:33:24.650 | {"level":"INFO","time":"2023/10/09 21:33:24.650649 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272483-sbtest4 txn: ctx[CC9743ABC9AE4F73A225C58119C877E1][1696887204623102365-1->9223372036854775807-4294967295][Active]: <nil>"} |  
  |   | 2023-10-10 05:33:24.650 | {"level":"INFO","time":"2023/10/09 21:33:24.650670 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272482-sbtest1 txn: ctx[18A24CB6756041529258F2FA8617DC4D][1696887204608923492-1->9223372036854775807-4294967295][Active]: <nil>"} |  
  |   | 2023-10-10 05:33:24.651 | {"level":"INFO","time":"2023/10/09 21:33:24.650949 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272619-sbtest5 txn: ctx[F52CE072E90F4436BBEBABA2102F7AAD][1696887204623102365-1->9223372036854775807-4294967295][Active]: <nil>"} |  
  |   | 2023-10-10 05:33:24.670 | {"level":"INFO","time":"2023/10/09 21:33:24.669937 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272685-sbtest7 txn: ctx[892CF6D6C3E642F2B8C0C7B732FF0F68][1696887204654688853-1->9223372036854775807-4294967295][Active]: <nil>"} |  
  |   | 2023-10-10 05:33:24.677 | {"level":"INFO","time":"2023/10/09 21:33:24.677678 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272620-sbtest8 txn: ctx[8284D40C426E4570888BDC0A42B0EA36][1696887204654688853-1->9223372036854775807-4294967295][Active]: <nil>"} |  
  |   | 2023-10-10 05:33:24.695 | {"level":"INFO","time":"2023/10/09 21:33:24.695517 +0000","caller":"rpc/handle.go:793","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 272544-sbtest:272686-sbtest10 txn: ctx[907E9156563C4928AB461A18D2D4D29D][1696887204686857721-1->9223372036854775807-4294967295][Active]: <nil>"}


```

**Comment by nnsgmsone** [comment]
应该存在两种可能: 1. precommit请求有问题 2 . commit请求有问题

**Comment by heni02** [comment]
date 10.13 appear invaild database:
<img width="1501" alt="企业微信截图_14404fbb-383f-4f38-aeaf-a59dd944dd69" src="https://github.com/matrixorigin/matrixone/assets/113406637/c42a88bd-4b78-410e-a967-bbaa228025c4">
job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6503218565/job/17666040371

**Comment by nnsgmsone** [comment]
这个的问题是因为有节点挂了，所以悲观锁加锁失败导致的:
```
{"level":"ERROR","time":"2023/10/13 05:15:12.695947 +0000","name":"cn-service.lockservice","caller":"lockservice/lock_table_remote.go:100","msg":"failed to lock on remote","uuid":"32653863-3330-3036-3037-333466646231","txn":"9b43e4a6887d4182b930ac1a3cb5736a()","rows":"[46013e144601747063635f31303000ff00]","opts":"Exclusive-Row-Wait","remote":"1-169716376846407729966316262-3230-6530-3863-663436363934-1","error":"lock table bind changed"} |  
  |   | 2023-10-13 13:15:12.696 | {"level":"ERROR","time":"2023/10/13 05:15:12.695994 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:2749","msg":"lock table bind changed","uuid":"32653863-3330-3036-3037-333466646231","session_info":"connectionId 2121\|10.130.6.199:36608\|{account sys:dump:moadmin -- 0:1:0}\|goRoutineId 1140890\|7c98087f-6987-11ee-9942-0ac33573af29","session_id":"7c98087f-6987-11ee-9942-0ac33573af29","statement_id":"7c98b80d-6987-11ee-9942-0ac33573af29"} |  

```
不过报错信息很诡异，有点诡异，应该报上锁失败才对。。。我再看看

**Comment by nnsgmsone** [comment]
通过cn日志查看。。。连接已经被cn强制关闭了。。。所以这个数据库找不到的错误不应该收到才对。。。下面的这个错误是不是连接了proxy或者是连接断开重联报的呢？
```
 The table [tpcc_100.bmsql_config] cant not be created. Error: ERROR 1049 (HY000) at line 1: invalid database tpcc_100
```

**Comment by aressu1985** [comment]
update on 10.17:
<img width="1385" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/91ea1fb9-d149-4666-86d3-8a21cbdb9a98">

log:
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231016%5C%22%7D%20%7C%3D%20%60sbtest.sbtest1%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by nnsgmsone** [comment]
经过分析，大致的情况如下，表确实没创建，创建的语句为create table if not exist，新增一些日志来确定这个表为啥可以查到。

**Comment by fengttt** [comment]
The error message says the table cannot be dropped because mo_account does not exist.   Why is that?

**Comment by heni02** [comment]
date 19 regression apear again : https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6563039481/job/17851637377
<img width="1421" alt="企业微信截图_197ae24c-c0a4-4664-8701-30922c638b4c" src="https://github.com/matrixorigin/matrixone/assets/113406637/e59d023b-24f8-4d9f-a4bb-f3ad59f4d046">

loki log:
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231019%5C%22%7D%20%7C%3D%20%60no%20such%20table%20sbtest.sbtest10%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221697703960000%22,%22to%22:%221697704020000%22%7D%7D

**Comment by nnsgmsone** [comment]
经过日志分析。目前的情况是这样，在create table的事务commit前，insert table的事务已经执行了。。所以发生了错误。。所以这里有问题。

**Comment by nnsgmsone** [comment]
因为已经移除了日志，等待加了日志的分支复现该问题以确定为啥会有异步commit的情况.

**Comment by nnsgmsone** [comment]
因为已经移除了日志，等待加了日志的分支复现该问题以确定为啥会有异步commit的情况.

**Comment by nnsgmsone** [comment]
优先处理12385中

**Comment by nnsgmsone** [comment]
复现中

**Comment by nnsgmsone** [comment]
复现中

**Comment by nnsgmsone** [comment]
整理内存的pr中。

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by heni02** [comment]
date 12.5 tke regression load data 也出现no such table报错
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7102214209/job/19345616735
<img width="1114" alt="企业微信截图_56b01430-e055-4361-8326-13ecb8d4468f" src="https://github.com/matrixorigin/matrixone/assets/113406637/c95097ec-0977-4421-a223-65eedd0e36ad">

**Comment by nnsgmsone** [comment]
regression的问题大致已经定位到。接下来思考如何fix

**Comment by nnsgmsone** [comment]
处理中

**Comment by nnsgmsone** [comment]
这个问题的本质应该和13302一样，因为create, drop和后续的操作都是独立的session，所以导致这个的原因是分布式情况下cn的一致性存在问题导致的。

**Comment by XuPeng-SH** [comment]
@aptend please investigate this issue

**Comment by XuPeng-SH** [comment]
http://132.232.112.34:30088/explore?panes=%7B%22EI9%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-10eb741%5C%22%7D%20%7C%3D%20%60sbtest%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702117495000%22,%22to%22:%221702117512000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aptend** [comment]
> date 12.5 tke regression load data 也出现no such table报错 现象很诡异，先drop然后报表存在，再报错表不存在，但报错一段时间前出现过cn重启的情况 job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7102214209/job/19345616735 

> http://132.232.112.34:30088/explore?panes=%7B%22EI9%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-10eb741%5C%22%7D%20%7C%3D%20%60sbtest%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702117495000%22,%22to%22:%221702117512000%22%7D%7D%7D&schemaVersion=1&orgId=1

这两个的出现逻辑目前看类似:
1. 删除表
2. 创建表时找到有同名表，如果没有加 if not exists，报 already exists，如果加了，直接返回成功
3. 插入数据是再找表，发现找不到

第二个场景属于加 if not exists 的情况，从日志可以发现sbtest 1 2 4 5 7 8 10 七张表创建时的事务时间戳和删除表的事务时间戳相等，所以看不见删除，但是随后的数据插入事务中，时间戳提升，看到了表删除，于是报表不存在

第一个场景因为报already exists时没有事务时间戳信息，暂不能确定是否和删除表时间戳相同

目前正在用脚本复现，在 eks 上复现过一次 no such table 但没有相关事务信息，无法判断。继续

**Comment by aptend** [comment]
除了时间戳问题以外，还发现事务重试可能导致创建表信息丢失，错误返回客户端完成创建。正在复现该问题

**Comment by aptend** [comment]
复现分支 https://github.com/aptend/matrixone/tree/debug-base
```bash
mysql> create database db;
Query OK, 1 row affected (0.01 sec)

mysql> use db;
Database changed

mysql> CREATE TABLE IF NOT EXISTS`sbtest9` ( `id` INT NOT NULL, `k` INT DEFAULT 0, `c` CHAR(120) DEFAULT NULL, `pad` CHAR(60) DEFAULT NULL , PRIMARY KEY (`id`) );
Query OK, 0 rows affected (0.01 sec)

mysql> select * from sbtest9;
ERROR 1064 (HY000): SQL parser error: table "sbtest9" does not exist
```

创建 sbtest 表时会额外执行向mo_indexes插入的内部sql，如果该sql重试，会导致清空workspace，但只会再执行 mo_indexes 插入语句，从而丢失了建表信息。

复现分支会对 sbtest 导致的插入 mo_indexes 的语句失败一次，触发重试，从而复现该问题。

结论是需要修改重试逻辑

**Comment by zhangxu19830126** [comment]
fixed by #13523

**Comment by zhangxu19830126** [comment]
And multi-session depends on test tool upgrade

**Comment by heni02** [comment]
最近两天回归没有再出现该错误，再观察两天看看

**Comment by heni02** [comment]
没有再出现该错误，关闭
date 12.24回归job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7315179856/job/19934627946
date 12.25回归job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7322467586

**Comment by heni02** [comment]
date 2.22 regression 又出现该错误，现象也是表创建成功，但报sbtest。sbtest2不存在，不确定和之前的原因是否一样，需定位
<img width="1426" alt="企业微信截图_f900d142-d686-4b1f-a73f-fc921c3ae7c4" src="https://github.com/matrixorigin/matrixone/assets/113406637/a575aa51-5dbf-44c5-aa54-4475046439f2">
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8006144357

log：
http://175.178.192.213:30088/explore?panes=%7B%22OEB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240222%5C%22%7D%20%7C%3D%20%60table%20%5C%5C%5C%22sbtest2%5C%5C%5C%22%20does%20not%20exist%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708642140000%22,%22to%22:%221708642259000%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1362" alt="企业微信截图_9fda098f-dd1a-4395-9fde-349e9ba6b2d4" src="https://github.com/matrixorigin/matrixone/assets/113406637/d9d4d5c3-5d39-4aa6-8063-82c4edb078f8">

**Comment by zhangxu19830126** [comment]
FATAL: mysql_drv_query() returned error 20702 (lock table bind changed) for query 'CREATE TABLE sbtest2(
  id INTEGER NOT NULL,
  k INTEGER DEFAULT 0 NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) '

create table failed

**Comment by heni02** [comment]
confirm，closed
