### ISSUE TITLE
[Feature Request]: implement bloom filter

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#11915]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Currently, we are using a third-party bloom filter library and have encountered two major problems so far. This is a very important data structure that will affect the correctness of the data. If something goes wrong, data compatibility needs to be done, which is very troublesome, so we need to develop and maintain our own bloom filter.

Requirements:
1. Zero-cost deserialization
2. High performance
3. Reasonable memory size
4. Tunable false-positive probability
5. Easy to understand

Interface:
```golang
type BloomFilter interface {
   MarshalBinary() ([]byte, error)
   UnmarshalBinary([]byte) error
   Add([]byte) BloomFilter 
   Test([]byte) bool
   Size() int
   String() string
}
```

**Comment by w-zr** [comment]
After fuzz test for over 10 hours, We dicided to use FastFilter.
