### ISSUE TITLE
[Bug]: distcache memory allocation issue

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#11918]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/112734932/5390a0a0-5129-4f21-8ed4-a26bfbf536c6)

distcache occupy too much memory. need to fix this

**Comment by volgariver6** [comment]
fixed
