### ISSUE TITLE
[Bug]: count(distinct column) doesn't work

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1191]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
NSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);
select count(distinct spID) from t1;
+-------------+
| count(spID) |
+-------------+
|           7 |
+-------------+

### Expected Behavior

select count(distinct spID) from t1;
+-------------+
| count(spID) |
+-------------+
|           5 |
+-------------+

**Comment by XuPeng-SH** [comment]
aoe issue
