### ISSUE TITLE
[Bug]: MO执行SQL有时返回时间特别长

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#11919]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-996f94ca
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

阿里云Dev环境MO跑的过程当中，时不时出现MOSQL特别慢的情况，无稳定复现路径，只是有时会有段时间特别卡。

### Expected Behavior

期望在正常时间内返回。可以看下Log中的几条SQL，都是在十秒以上。

### Additional information

Log如下：
2023/09/26 15:20:14.413316 +0000 WARN instance/instance.go:560 trace {"elapsed": "13.122797498s", "rows": 1, "sql": "select sum(cu) from mo_cloud.cu where account = 'd323055e_9b57_4d24_9d7b_8699090e0e2b' and start_time >= '2023-09-25 16:00:00' and start_time < '2023-09-26 15:20:01'"}

2023/09/26 15:20:14.396405 +0000 WARN instance/instance.go:543 trace {"elapsed": "13.47683343s", "rows": 1, "sql": "select sum(cu) from mo_cloud.cu where account = 'e321e1fc_d69a_4546_8638_236a5988e530' and start_time >= '2023-08-31 16:00:00' and start_time < '2023-09-26 15:20:00'"}

2023/09/26 15:20:03.299611 +0000 WARN instance/instance.go:543 trace {"elapsed": "37.189203984s", "rows": 1, "sql": "select sum(cu) from mo_cloud.cu where account = 'e321e1fc_d69a_4546_8638_236a5988e530' and start_time >= '2023-08-31 16:00:00' and start_time < '2023-09-26 15:19:26'"}

2023/09/26 15:20:03.298248 +0000 WARN instance/instance.go:560 trace {"elapsed": "37.20365935s", "rows": 1, "sql": "select sum(cu) from mo_cloud.cu where account = 'e321e1fc_d69a_4546_8638_236a5988e530' and start_time >= '2023-09-25 16:00:00' and start_time < '2023-09-26 15:19:26'"}

**Comment by nnsgmsone** [comment]
还未处理

**Comment by nnsgmsone** [comment]
还未处理

**Comment by badboynt1** [comment]
SELECT count(*) FROM `system`.`statement_info` WHERE 1=1 AND system.statement_info.account = '6c21a2a6_db3c_4fff_adb5_685ab
ac486c0' AND sql_source_type IN ('cloud_user_sql','external_sql');  从日志里看，这条sql比较慢。

![企业微信截图_16975146725660](https://github.com/matrixorigin/matrixone/assets/112734932/fb698fd4-e618-47e2-877d-13851d08fc15)
 需要修改一下表的ddl，clusterby应该把低ndv的列放前面，高ndv的列放后面。或者删掉第二列，只clusterby一列即可。

**Comment by badboynt1** [comment]
大概率和https://github.com/matrixorigin/MO-Cloud/issues/1501 是同一个问题

**Comment by badboynt1** [comment]
等1501这个问题解决后再观察看看

**Comment by xiaoshuwei** [comment]
@badboynt1 反馈可能是稳定性问题，最近稳定性问题解决了很多，此Issue再观察五天，没有复现则暂时先close掉。

**Comment by xiaoshuwei** [comment]
没有复现，暂时close
