### ISSUE TITLE
[Bug]: Insert data failed when table with char(0) 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1192]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 (b char(0) not null);
insert into t1 values ("");
ERROR 1105 (HY000): unknown error:[22000]Data too long for column 'b' at row 1

### Expected Behavior

Query OK, 1 row affected (0.01 sec)

**Comment by m-schen** [comment]
fixed. And can verify it after pr merge into branch main.
