### ISSUE TITLE
[Enhancement]: fix mpool memory record number leak.

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#11928]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
目前至少存在以下2种情况：
1. 
prepare导致的每次执行都会致使mpool的内存计数增长该batch的大小。
该问题可由oltp_random_point复现。


2. 在开启process的vp池子并该查询从vp取用了vector的前提下，不知道vector的哪个方法会导致该vector被free时，mpool的计数不会被改变。
```

### Why is this needed ?

vector的方法在mpool自洽。
prepare无计数上的内存泄漏。

**Comment by m-schen** [comment]
问题2与vector的方法无关，已修复。原因是partition reader没有正确释放内存。

**Comment by sukki37** [comment]
Problem 2: Fixed
Problem 1: Not tackled yet
