### ISSUE TITLE
[Bug]: [date 9.26]standalone regression performance:  sysbench insert 100 and 1000 threads performance go down 90%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11937]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d21d7267438bfe02c1a2446274c89c748674cf39
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

date 9.26 regression sysbench insert performance go down 90%，mo commi id：d21d7267438bfe02c1a2446274c89c748674cf39
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6314649714/job/17161223257
<img width="1041" alt="企业微信截图_eec3c900-1c4b-4f76-83f4-bbd0092bdb90" src="https://github.com/matrixorigin/matrixone/assets/113406637/31e42a8f-3278-44a2-8af9-10646c8be72f">
<img width="648" alt="企业微信截图_ac28a66b-7cde-4e48-98c5-00c3799882cb" src="https://github.com/matrixorigin/matrixone/assets/113406637/193f52d7-ccbc-400a-8b6b-9368adabf327">
<img width="678" alt="企业微信截图_931b9eea-e212-49d4-8e18-cc79930ed320" src="https://github.com/matrixorigin/matrixone/assets/113406637/252ae1da-1019-4830-8621-8ddcb6c9b7ae">

date 9.27 regression always  performance go down ，mo commit id：3a8fe63b46921efaea47a0e90743d4d7c558a6cb
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6327848028/job/17184796994
<img width="765" alt="企业微信截图_5e360ec5-1573-49d4-82c1-fbc807389dd4" src="https://github.com/matrixorigin/matrixone/assets/113406637/1109a2e7-3965-4343-a6e5-84a220a3bd4b">

**Comment by heni02** [comment]
date 9.25 regression did not have this performance problem：533b0d3656a905742f44b77db52b66f6954056e2

**Comment by fengttt** [comment]
@heni02 I believe you have some info on crash/disconnect etc.    Can you update?   If this can be reproed consistently, please update with info and assign to dev.    thank you

**Comment by heni02** [comment]
@fengttt  sorry ，updated now，During the testing, no connection failure or timeout errors were found
<img width="1415" alt="企业微信截图_d8a8c868-0508-428d-8130-a4992e56e974" src="https://github.com/matrixorigin/matrixone/assets/113406637/5c7427c4-8000-4850-aaab-12c00588a230">
and tke insert always had this problem
<img width="669" alt="企业微信截图_dd2bd3e3-8b27-4cc6-baf4-892dd4fb3bae" src="https://github.com/matrixorigin/matrixone/assets/113406637/ac5da938-b03a-47ea-ac31-b1514e281034">

**Comment by heni02** [comment]
confirm，date 10.2，10.7 performance is normal
<img width="689" alt="企业微信截图_cfe0761d-f5f2-4b06-8473-16472e02066f" src="https://github.com/matrixorigin/matrixone/assets/113406637/eea340fa-0815-4b9f-a50e-22d46cfa1982">
<img width="663" alt="企业微信截图_98e1c7a1-db7c-427c-80bf-8297e5779005" src="https://github.com/matrixorigin/matrixone/assets/113406637/2a259881-cd43-424b-b838-9cd0f206e745">

maybe after this pr revert
<img width="1209" alt="企业微信截图_0f612e79-c8dc-446d-a836-4a00735c6d77" src="https://github.com/matrixorigin/matrixone/assets/113406637/5053ddff-2920-4a26-84e8-fca8cf34a980">
