### ISSUE TITLE
[Bug]: [date 9.27] tke regression: sysbench delete 100 threads cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11945]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-3a8fe63
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke regression job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6328517984/job/17203629976
sysbench delete 100 threads reported connect fail
<img width="1074" alt="企业微信截图_f8d78697-84e4-485d-8188-d74626324830" src="https://github.com/matrixorigin/matrixone/assets/113406637/067fb66c-bd30-4fdc-83e8-6a7c14cdbcec">

found mo status 2 cn restart:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/14109648-12f4-49c9-bd7a-95ace4f24fc3)
found one of cn  oom ,the time of delete failure is the same as the oom time
<img width="1391" alt="企业微信截图_293389bd-f6c8-43d6-a65b-3eef19f932d1" src="https://github.com/matrixorigin/matrixone/assets/113406637/07bcd332-86d8-46a3-bff9-9eba1bc1018b">
and other cn not oom
<img width="1427" alt="企业微信截图_f77c524b-e08e-4b00-8aea-da613bc0c589" src="https://github.com/matrixorigin/matrixone/assets/113406637/39ddeb40-f7db-4455-9c14-cdf62cad6f57">

pod resources：
http://1.14.64.109:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=mo-nightly-regression-20230927&from=now-12h&to=now

oom cn pod log：
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20230927%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-qhx5s%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by nnsgmsone** [comment]
麻烦给我一下pprof文件。。 @heni02

**Comment by nnsgmsone** [comment]
没有pprof文件，还没处理。。。如果可以的话，帮我再跑一次把。。 @heni02

**Comment by aressu1985** [comment]
[profile.zip](https://github.com/matrixorigin/matrixone/files/12839671/profile.zip)

**Comment by nnsgmsone** [comment]
查看prof信息后，发现三个cn，只有一个在工作。。。另外一个cn不知道为啥跑的是dn。。。还有一个cn是空负载的。。。
![截图 2023-10-08 11-31-04](https://github.com/matrixorigin/matrixone/assets/31609524/9d27628f-83fb-483e-95dc-a2e59a599a40)
![截图 2023-10-08 11-31-53](https://github.com/matrixorigin/matrixone/assets/31609524/fb493a58-6d34-4594-b9db-af106c91db07)

![截图 2023-10-08 11-31-12](https://github.com/matrixorigin/matrixone/assets/31609524/7a0ed2de-ac98-4337-877d-f7fdcbd2649b)

**Comment by heni02** [comment]
date 10.7 regression cn oom, aressu1985 already put profile info
job:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6442161947/job/17496199015
企业微信截图_6e6b241f-6ea6-4aab-9d9a-ded8f61b42f5

**Comment by nnsgmsone** [comment]
那个prof有点问题，等下一次复现的prof。

**Comment by heni02** [comment]
date 10.13 regression 出现了oom，看oom得时间是在tpcc测试时出现
<img width="879" alt="企业微信截图_55bef844-e539-4eb6-b1e2-312f92aefd54" src="https://github.com/matrixorigin/matrixone/assets/113406637/4022b1b9-1d13-4f8d-9d27-ac5414057075">
<img width="1412" alt="企业微信截图_823713c2-9785-4eef-a553-3d74a1d224bd" src="https://github.com/matrixorigin/matrixone/assets/113406637/8e3fcce3-da9b-4aed-a635-72cfb8e2ab71">
oom时间在06:00时间左右
相关时间段profile信息：
[profile-111.tar.gz](https://github.com/matrixorigin/matrixone/files/12892526/profile-111.tar.gz)
loki log：
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231013%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221697176680000%22,%22to%22:%221697176860000%22%7D%7D

**Comment by nnsgmsone** [comment]
看着是连接太多了。。。这个是怎么连接cn的呢？ @heni02 有proxy吗

**Comment by nnsgmsone** [comment]
看着连接有泄露。。。我在看看。应该是存在一些连接泄露或者释放慢导致的一些内存清理不及时

**Comment by heni02** [comment]
相关的issue #12708 ，确认下是否oom @nnsgmsone

**Comment by ouyuanning** [comment]
> 看着连接有泄露。。。我在看看。应该是存在一些连接泄露或者释放慢导致的一些内存清理不及时

@volgariver6 看能否帮忙先看看。莫尘这边issue有点太多

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
还没看，在做logtail consumer 重构

**Comment by heni02** [comment]
date 11.6 regression cn oom
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6772821132/job/18421640701
<img width="1661" alt="企业微信截图_d8c974db-ab5b-4e34-8718-481a7b13e798" src="https://github.com/matrixorigin/matrixone/assets/113406637/ebf5468e-9471-4286-b01c-ff5a0d65d2ef">
cn oom， mem limit55G
<img width="1163" alt="企业微信截图_f7f2a8f8-de01-4606-8e64-4f745deca7a8" src="https://github.com/matrixorigin/matrixone/assets/113406637/f77499bb-7362-4620-972c-7ad93ff389bc">

profile：
[cn_oom_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13276430/cn_oom_profile.tar.gz)

**Comment by aressu1985** [comment]
update on 1108:

profile:
[cn_oom_profile_1107.tar.gz](https://github.com/matrixorigin/matrixone/files/13296119/cn_oom_profile_1107.tar.gz)

**Comment by volgariver6** [comment]
无进展

**Comment by heni02** [comment]
date 11.14 cn oom
<img width="1598" alt="企业微信截图_a1c613f0-c1e7-432e-83bc-46f44f9d8de4" src="https://github.com/matrixorigin/matrixone/assets/113406637/c4eddfe0-6be2-43f0-a687-dfa3ebf62561">
<img width="802" alt="企业微信截图_7a5d130f-1911-48b3-a88e-9091f59d7f32" src="https://github.com/matrixorigin/matrixone/assets/113406637/b1b34e97-2c67-48f5-8c0d-21ceba339b30">
<img width="1647" alt="企业微信截图_0b177682-2de6-474c-bf88-d34e9432f822" src="https://github.com/matrixorigin/matrixone/assets/113406637/5084341c-ee94-454f-808c-5a3b40ef78d6">

**Comment by volgariver6** [comment]
no progress

**Comment by aressu1985** [comment]
用最新的流程跟踪，这个关闭
