### ISSUE TITLE
[Bug]: bvt case for span_info will fail after the mo_ctl controlled span is introduced.

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#11947]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

in `test/distributed/cases/table/system_table_cases.sql`, have cases:
```sql
SELECT COUNT(*) FROM (SELECT * FROM span_info LIMIT 10) AS temp;
SELECT COUNT(0) FROM (SELECT * FROM span_info LIMIT 10) AS temp;
SELECT COUNT('') FROM (SELECT * FROM span_info LIMIT 10) AS temp;
SELECT COUNT(NULL) FROM (SELECT * FROM span_info LIMIT 10) AS temp;
```

however, we cannot ensure that span_info has been flushed more than 10 records.

**Comment by aressu1985** [comment]
@gouhongshen what is this issue ？I dont understand

**Comment by gouhongshen** [comment]
> @gouhongshen what is this issue ？I dont understand

引入 mo ctl 控制trace后，默认情况下 trace没有开启，所以 span info 表里面的记录没有以前多，就不能保证 bvt 测试中一定有十条记录，这些case就过不去。

**Comment by gouhongshen** [comment]
fixed

**Comment by matrix-meow** [comment]
Hello @gouhongshen. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by xzxiong** [comment]
656c1bad9935">

**Comment by matrix-meow** [comment]
Hello @gouhongshen. The bug issue in the BVT test code has not been removed,issues automatically open.
