### ISSUE TITLE
[Bug]:  `BUG: 'read incr record invalid'` causes the CN to crash.

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#11957]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/matrixorigin/matrixone/commit/02535ea0156d4ab38435f064175c83d78c37bc05
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[default-cn-5khbn-crash.log.zip](https://github.com/matrixorigin/matrixone/files/12751820/default-cn-5khbn-crash.log.zip)

{"level":"FATAL","time":"2023/09/28 15:22:54.049461 +0000","name":"cn-service.incrservice","caller":"incrservice/store_sql.go:115","msg":"BUG: read incr record invalid","uuid":"33383364-3261-6530-6166-613335626665","fetch-sql":"select offset, step from mo_increment_columns where table_id = 272389 and col_name = 'task_id' for update","account":0,"table":272389,"col":"task_id","rows":0,"stacktrace":"github.com/matrixorigin/matrixone/pkg/incrservice.(*sqlStore).Allocate.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/store_sql.go:115\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*sqlExecutor).ExecTxn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/sql_executor.go:105\ngithub.com/matrixorigin/matrixone/pkg/incrservice.(*sqlStore).Allocate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/store_sql.go:98\ngithub.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).doAllocate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:143\ngithub.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:130\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}

**Comment by fengttt** [comment]
May not be related, but at stopper.go #11964

**Comment by sukki37** [comment]
<img width="1295" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/09e450f9-9bff-47ce-96e6-707f36d4e261">

**Comment by sukki37** [comment]
another scenario is that there is no data in memory, but the query transaction shows 22 blocks

[Explore-logs-2023-10-02 18_32_49.txt](https://github.com/matrixorigin/matrixone/files/12782879/Explore-logs-2023-10-02.18_32_49.txt)

**Comment by LeftHandCold** [comment]
The root cause is that ctx has "deadline" before sql exec(), and exec() did not return error, so FATAL

**Comment by LeftHandCold** [comment]
Repro steps：
1: https://github.com/matrixorigin/matrixone/blob/main/pkg/incrservice/store_sql.go#L101
Add TriggerFault in front of Exec(fetchSQL), then make build & start mo
```go
                                 _, sarg, _ := fault.TriggerFault("lock_deadline")
				if sarg != "" {
					logutil.Infof("lock_deadline fault: %s, tableid: %d", sarg, tableID)
					time.Sleep(10 * time.Second)
				}
```
2. Modify autoIncrement=true in sysbench.yml and execute sysbench mixed
3.  select enable_fault_injection(); select add_fault_point('lock_deadline', ':::', 'echo', 0, 'lock_deadline');

**Comment by LeftHandCold** [comment]
Adding TriggerFault in lock_op.go/doLock can also reproduce the bug

**Comment by zhangxu19830126** [comment]
fixed

**Comment by zhangxu19830126** [comment]
还有有问题，需要继续看

**Comment by zhangxu19830126** [comment]
fixed

**Comment by sukki37** [comment]
After the upgrade, the issue hasn't reproduced, so we've downgraded it for further observation.
