### ISSUE TITLE
[Bug]: generate_series panic with 1 input param

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11967]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from generate_series(10) tmp;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [1] with length 1:

### Expected Behavior

generate_series(10) should be the same as generate_series(1, 10).    Even if we don't support this, it should error instead of panic.

**Comment by daviszhen** [comment]
@zengyan1 看下

**Comment by zengyan1** [comment]
fixed
