### ISSUE TITLE
[Bug]: mo_sessions should display idle for idle session

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11976]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from mo_catalog.mo_sessions

For those idle session -- no active query, no active transaction, we still print out a query/statement (I assume it is the previous one).   We should display it as idle.

There is no need to be accurate, meaning that if a query may become idle when the we query mo_sessions, in that case, it may or may not be displayed as idle -- this is fine.   However, for a session that has been idle for a while we should be able to tell that.

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
it was fixed.

**Comment by fengttt** [comment]
Not so fast yet, the transaction id field is still filled -- I suppose that is a closed transaction.

**Comment by fengttt** [comment]
my mistake.   seems transaction id is cleared.
