### ISSUE TITLE
[Bug]: nil pointer

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11978]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0 mo cloud a5dca0f21
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from system.error_info where timestamp > '2023-10-05 06:00:00';
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:841
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Stats
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/compiler_context.go:683
github.com/matrixorigin/matrixone/pkg/sql/plan.calcScanStats
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/stats.go:723
github.com/matrix
mysql>

**Comment by ouyuanning** [comment]
暂无法复现

**Comment by ouyuanning** [comment]
@fengttt 
当前主干未复现。好像没有找到 a5dca0f21  这个commit

**Comment by sukki37** [comment]
> @fengttt 当前主干未复现。好像没有找到 [a5dca0f](https://github.com/matrixorigin/matrixone/commit/a5dca0f210ae01b9c9a73732c9aded7509242d4b) 这个commit

https://github.com/sukki37/matrixone/commits/1.0-dev-debug this repo

**Comment by ouyuanning** [comment]
在猫猫的分支也没有复现。
不过从报错来看。原来的代码，确实没有处理 table不存在的情况。会引起这个报错。

但是从调用这个函数的代码来看，应该是能保证这个表是存在的。除非在调用期间这个表被干掉了。或者调用getRelation的时候有bug没有查到这个表。但是目前还没法复现这种情况

我先提个PR，把可能panic的逻辑fix掉吧。这样修改不会影响准确性，有可能影响优化器的优化策略

**Comment by ouyuanning** [comment]
@fengttt 由于无法复现。
目前提交了个PR，会杜绝此panic问题。但是未解决为什么会有此panic的问题。
看是否降级还是可以关闭掉此issue。
