### ISSUE TITLE
[Bug]: current_timestamp evaluation error

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11977]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0 mo-cloud
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select query_start, current_timestamp, timestampdiff(SECOND, query_start, current_timestamp), account, user from mo_catalog.mo_sessions;
+----------------------------+----------------------------+---------------------------------------------------------+--------------------------------------+-----------+
| query_start                | current_timestamp()        | timestampdiff(second, query_start, current_timestamp()) | account                              | user      |
+----------------------------+----------------------------+---------------------------------------------------------+--------------------------------------+-----------+
| 2023-10-05 05:47:32.298004 | 2023-10-05 05:47:34.126957 |                                                       1 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:33.548837 | 2023-10-05 05:47:34.126957 |                                                       0 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:47.370194 | 2023-10-05 05:47:34.126957 |                                                     106 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:47.649667 | 2023-10-05 05:47:34.126957 |                                                     106 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:47.764254 | 2023-10-05 05:47:34.126957 |                                                     106 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:48.134799 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:48.182106 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:48.610290 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:49.058620 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:28.890023 | 2023-10-05 05:47:34.126957 |                                                       5 | sys                                  | mo_logger |
| 2023-10-05 05:47:30.187944 | 2023-10-05 05:47:34.126957 |                                                       3 | sys                                  | mo_logger |
| 2023-10-05 05:47:34.078958 | 2023-10-05 05:47:34.126957 |                                                       0 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:28.063241 | 2023-10-05 05:47:34.126957 |                                                       6 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:32.181024 | 2023-10-05 05:47:34.126957 |                                                       1 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:27.248469 | 2023-10-05 05:47:34.126957 |                                                       6 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
+----------------------------+----------------------------+---------------------------------------------------------+--------------------------------------+-----------+
15 rows in set (0.68 sec)

mysql> select query_start, current_timestamp, timestampdiff(SECOND, query_start, current_timestamp), account, user from mo_catalog.mo_sessions;
+----------------------------+----------------------------+---------------------------------------------------------+--------------------------------------+-----------+
| query_start                | current_timestamp()        | timestampdiff(second, query_start, current_timestamp()) | account                              | user      |
+----------------------------+----------------------------+---------------------------------------------------------+--------------------------------------+-----------+
| 2023-10-05 05:47:52.297878 | 2023-10-05 05:47:34.126957 |                                                     -18 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:48.769848 | 2023-10-05 05:47:34.126957 |                                                     -14 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:47.370194 | 2023-10-05 05:47:34.126957 |                                                     106 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:47.649667 | 2023-10-05 05:47:34.126957 |                                                     106 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:47.764254 | 2023-10-05 05:47:34.126957 |                                                     106 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:48.134799 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:48.182106 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:48.610290 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:45:49.058620 | 2023-10-05 05:47:34.126957 |                                                     105 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:43.889825 | 2023-10-05 05:47:34.126957 |                                                      -9 | sys                                  | mo_logger |
| 2023-10-05 05:47:45.188516 | 2023-10-05 05:47:34.126957 |                                                     -11 | sys                                  | mo_logger |
| 2023-10-05 05:47:54.606445 | 2023-10-05 05:47:34.126957 |                                                     -20 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:28.063241 | 2023-10-05 05:47:34.126957 |                                                       6 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:52.180944 | 2023-10-05 05:47:34.126957 |                                                     -18 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:51.312392 | 2023-10-05 05:47:34.126957 |                                                     -17 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:54.608472 | 2023-10-05 05:47:34.126957 |                                                     -20 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
| 2023-10-05 05:47:54.500930 | 2023-10-05 05:47:34.126957 |                                                     -20 | b6011b4d_75b2_4458_875c_42f6dd16d927 | admin     |
+----------------------------+----------------------------+---------------------------------------------------------+--------------------------------------+-----------+
17 rows in set (3.76 sec)

### Expected Behavior

You can see that two execution, the current_timestamp stays the same.

**Comment by fengttt** [comment]
Esp in the second query, some timestampdiff is negative.    This means query started AFTER current timestamp.

**Comment by daviszhen** [comment]
还没看

**Comment by YANGGMM** [comment]
<img width="1716" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/e0662c0d-5451-44ab-8883-2169a6ddd1ea">

**Comment by YANGGMM** [comment]
need fix the pr

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
fixed
