### ISSUE TITLE
[Bug]: mo_account does not exist

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11970]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This is single node launch mode, started with
```
(cd $HOME/m/matrixone; ./mo-service -debug-http :9876 -launch ./etc/launch/launch.toml)
```

Fengs-MacBook-Pro:matrixone fengttt$ mocli
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user dump. SQL parser error: table "mo_account" does not exist

**Comment by fengttt** [comment]
It recovers after a short while.

**Comment by daviszhen** [comment]
mo启动的时，会有一段时间mo_account没有。通常应该“启动完成”后再对外服务。由于没有定义清楚“启动完成”指那些项目完成。没有阻拦用户登录。

**Comment by fengttt** [comment]
It is obviously still a problem.    We definitely *SHOULD* have a well defined point that mo can provide service.   But I assume this is during init and this period is short.

**Comment by daviszhen** [comment]
这个问题已经没有了。

**Comment by sukki37** [comment]
This issue seems resolved. Closing now. Reopen if needed. Thanks!
