### ISSUE TITLE
[Bug]: system.rawlog should be clustered by timestamp only

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11974]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Right now rawlog is clustered by timestamp and raw_item.    This is effectively the same as cluster by timestamp only.    Adding raw_item simply adds overhead.

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pr is pending

**Comment by gavinyue** [comment]
Need to update the upgrader to handle the cluster by alter.

**Comment by gavinyue** [comment]
should have make the initial change.  Will change upgrader now

**Comment by gavinyue** [comment]
不好处理

**Comment by heni02** [comment]
confirm
main commit id :0175397c3d933aff66b3fa950f85d92fc05cab2c
show create table rawlog：
<img width="1316" alt="企业微信截图_3c71ebfb-a5ff-4219-9dcc-777a31765feb" src="https://github.com/matrixorigin/matrixone/assets/113406637/6e07fe1c-b5b9-4f5d-89f0-5fef56e89a4a">

**Comment by aressu1985** [comment]
fxied
