### ISSUE TITLE
[Bug]: leading column of cluster by should be sorted.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#11973]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

system.rawlog table is clustered by timestamp and raw_item, the leading column of the cluster should be sorted, but metadata says not sorted.

**Comment by XuPeng-SH** [comment]
@gouhongshen  please take a look at this issue

**Comment by gouhongshen** [comment]
at the beginning of the creation of mo, metadata_scan shows `rawlog` all blocks are sorted, but after serval minutes passed, it shows, however, all blks are not sorted:

<img width="1071" alt="截屏2023-10-08 11 32 38" src="https://github.com/matrixorigin/matrixone/assets/26336316/af980f04-e15a-4714-8056-4db5c4f03882">


after several tries, I found a block that is a non-appendable blk in logs, but it's sorted is false:

<img width="660" alt="截屏2023-10-08 14 16 17" src="https://github.com/matrixorigin/matrixone/assets/26336316/51509e51-e0c0-4372-84ad-cf04d7a0a024">

<img width="649" alt="截屏2023-10-08 14 16 41" src="https://github.com/matrixorigin/matrixone/assets/26336316/9401c2d9-d11f-43be-bc71-bf8a2dc97e57">


so, this inconsistency could be made by collecting logic when `metadata_scan`.

**Comment by gouhongshen** [comment]
the above `but after serval minutes passed ` should be `after serval minutes passed, and MySQL client reconnected`.

more tests have been done, we found that every time MO reboots with checkpoint has done, the `sorted` in metadata scan all been false.

**Comment by XuPeng-SH** [comment]
fixed
