### ISSUE TITLE
[Bug]: cannot start DN server due to OOM

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#11981]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev-debug-42a457862
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DN get OOM killed every time after started for several minutes.

Heap profile:

<img width="1066" alt="WeChatWorkScreenshot_9ad00eb4-73e0-4708-89b5-3370bc3cc8b5" src="https://github.com/matrixorigin/matrixone/assets/18556593/84c4a33f-93a9-4fed-9fb2-dcdf7311569e">

Monitor:

<img width="1825" alt="WeChatWorkScreenshot_3a7d5a1d-ce51-4bc5-94ba-767c01c68893" src="https://github.com/matrixorigin/matrixone/assets/18556593/8f02e762-1f3b-4db0-a504-f7dad6c0e0a0">

Config:

```
    [[fileservice]]
    backend = "DISK"
    data-dir = "/var/lib/matrixone/data"
    name = "LOCAL"

    [[fileservice]]
    backend = "S3"
    name = "S3"

    [fileservice.cache]
    disk-capacity = "90GiB"
    disk-path = "/var/lib/matrixone/disk-cache"
    memory-capacity = "14592MiB"
```

### Expected Behavior

DN should not OOM.

### Additional information

[heap.txt](https://github.com/matrixorigin/matrixone/files/12836335/heap.txt)

**Comment by aylei** [comment]
after tune the fileservice memory cache to 1GiB, the problem is solved

**Comment by LeftHandCold** [comment]
The cause of this bug is https://github.com/matrixorigin/matrixone/issues/11983

**Comment by XuPeng-SH** [comment]
assigned to @LeftHandCold

**Comment by LeftHandCold** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/11988

**Comment by LeftHandCold** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/11988

**Comment by aylei** [comment]
closing as not reproduced for the same reason
