### ISSUE TITLE
[Bug]: [date 10.6] standalone regression: sysbench read-write and write-only reported deadlock detected error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#11985]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):621933bbc42c878c75e88d8c573f9260a838a840
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6433325990/job/17470274800
read-write:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0ff77c8c-108f-4639-9c2e-c2b7ff881e75)

write-only:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c57e7700-3a0d-411a-b4b6-a132c7b3262a)

write sql:
<img width="662" alt="企业微信截图_8dde9df7-d329-41f4-b92c-344545488b75" src="https://github.com/matrixorigin/matrixone/assets/113406637/cbecc628-81ec-4e83-8d7d-873a5e80bdf1">

mo log:
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231006%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
这个是测试工具的问题，。确实有死锁发生了：

<img width="687" alt="企业微信截图_2fa3fcce-1f0a-4c65-83ee-84d31cd806be" src="https://github.com/matrixorigin/matrixone/assets/2995754/66721778-63a8-47c3-83e8-0f25c7d235a2">

**Comment by heni02** [comment]
目前在调试工具相关参数避免这个错误

**Comment by heni02** [comment]
工具问题再调试中，该issue先关闭
