### ISSUE TITLE
[Bug]: mo hung after running stability test on standlone mode for about 7 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12003]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):175ddb232988e761dbef833dec6f193668ae24a1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After running stability test on standlone mode for about 7 hours, the mo can not login any more.
<img width="886" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/a3c555a6-ec66-419a-88f9-bc5ea1fac4b1">

mo log:
[mo-hung.tar.gz](https://github.com/matrixorigin/matrixone/files/12839749/mo-hung.tar.gz)

prof:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/12839756/profile.tar.gz)

**Comment by aressu1985** [comment]
maybe it is related to #11838, downgrade security level to s0 and track

**Comment by reusee** [comment]
Another possibly related issue is https://github.com/matrixorigin/matrixone/issues/11628

**Comment by xzxiong** [comment]
查看issue 中 profile 里面的 goroutine.log, 发现有点对不上

**Comment by reusee** [comment]
> 查看issue 中 profile 里面的 goroutine.log, 发现 代码有点对不上 L462 是个数值对比，不太可能运行 26minute ![企业微信截图_aef411d8-8db1-4913-82ec-79b967060e8f](https://user-images.githubusercontent.com/3927687/273571871-04e058f4-e948-478e-a06e-7145279d9865.png)
> 
> ![image](https://user-images.githubusercontent.com/3927687/273571829-d8fca252-9096-4bd0-a77d-2d5d5013434e.png)

profile里显示是select阻塞26mins，所以profile和代码的版本是不对应的。

**Comment by aressu1985** [comment]
这两天没有在复现，先降级，再继续跟踪
