### ISSUE TITLE
[Bug]: cn pod status is completed or ContainerStatusUnknown， then no longer to pull up the running again 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12001]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cn pod status is Completed：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d6c0a39c-f50f-45f2-a136-13be0812c897)

cn pod status is ContainerStatusUnknown：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/a4d512ca-ffe8-4a9c-9ef2-39cc5642e890)

**Comment by aylei** [comment]
@heni02 fixed by https://github.com/matrixorigin/matrixone-operator/pull/443

**Comment by heni02** [comment]
tke env no appear this problem confirm closed
<img width="778" alt="企业微信截图_e16b4727-bdc3-44df-b9d9-083601bc0b18" src="https://github.com/matrixorigin/matrixone/assets/113406637/d4788cdb-774c-4e33-9370-9f1edc352488">
