### ISSUE TITLE
[Bug]: load from aliyun report panic

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12023]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:841
github.com/matrixorigin/matrixone/pkg/fileservice.ObjectStorageArguments.credentialProviderForAliyunSDK.func1
	/Users/yangzhao/matrixone/pkg/fileservice/aliyun_sdk.go:527
github.com/matrixorigin/matrixone/pkg/fileservice.ObjectStorageArguments.credentialProviderForAliyunSDK
	/Users/yangzhao/matrixone/
No connection. Trying to reconnect...
Connection id:    4617
Current database: abc

load data url s3option {"endpoint"="oss-cn-hangzhou.aliyuncs.com", "bucket"='lr90-bucket', "filepath"='lr90-bucket/heap', "role_arn"='xxxxx', "external_id"='xxxxx', "compression"='auto'} into table t1  FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n';

执行两次会出现这个问题。

**Comment by YANGGMM** [comment]
load data url s3option {"endpoint"="oss-cn-hangzhou.aliyuncs.com", "bucket"='lr90-bucket', "filepath"='lr90-bucket/heap', "role_arn"='acs:ram::1713506034439468:role/oss-cross-test', "external_id"='de509d1e_f027_4e40_b5f3_4d520f77a729', "compression"='auto'} into table t1  FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n';

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
https://github.com/matrixorigin/matrixone/issues/12023

**Comment by reusee** [comment]
Already fixed in https://github.com/matrixorigin/matrixone/commit/0070abe134880d9b12e8b4108647a9ebd42fb7aa
