### ISSUE TITLE
[Bug]: Insert in transaction reports error `20101 (HY000): internal error: Invalid alloc size 1147486208`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#12021]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-898ac286
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Open a transaction
- In the transaction, insert 1000 records in one batch, and when it comes to the second batch, the error `20101 (HY000): internal error: Invalid alloc size 1147486208` is fired.
The schema is as below:
```
MySQL [mo_c]> desc mo_catalog.statement_cx;
+--------------+------------------+------+------+---------+-------+--------------------------------+
| Field        | Type             | Null | Key  | Default | Extra | Comment                        |
+--------------+------------------+------+------+---------+-------+--------------------------------+
| statement_id | VARCHAR(36)      | NO   | PRI  | NULL    |       |                                |
| account      | VARCHAR(300)     | NO   |      | NULL    |       |                                |
| response_at  | DATETIME(3)      | YES  |      | NULL    |       |                                |
| cx           | DECIMAL128(23)   | NO   |      | NULL    |       |                                |
| account_id   | INT UNSIGNED(32) | NO   | PRI  | NULL    |       | the account_id added by the mo |
+--------------+------------------+------+------+---------+-------+--------------------------------+
5 rows in set (0.30 sec)
```

Here is an example record:
```
('37cb68b3-61f4-11ee-ac82-eeab67a4d8c2','b6011b4d_75b2_4458_875c_42f6dd16d927','2023-10-03 13:53:23.105','0',9000001)
```

### Expected Behavior

Insert records successfully

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Log: http://47.97.80.230/explore?orgId=1&left=%7B%22datasource%22:%22P3C839627617F91E0%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-02%5C%22,%20app%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3C839627617F91E0%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

**Comment by ouyuanning** [comment]
待明天复现

**Comment by ouyuanning** [comment]
使用以下脚本，未能复现：
[12021.sql.zip](https://github.com/matrixorigin/matrixone/files/12854637/12021.sql.zip)

**Comment by DanielZhangQD** [comment]
Just check the existing log here:
http://47.97.80.230/explore?orgId=1&left=%7B%22datasource%22:%22P3C839627617F91E0%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3C839627617F91E0%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60Invalid%20alloc%20size%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221696644000000%22,%22to%22:%221696672799000%22%7D%7D

**Comment by aressu1985** [comment]
也未复现，而且DAILY REGRESSION每天都有很多次Sysbench load data的操作，行为也是batch insert，每个batch的数据量是100，每个record比这个数据量还大，也都未出现过这个问题

**Comment by ouyuanning** [comment]
从日志看不出是什么样的statement引起的。但是日志里报错都是
Invalid alloc size 1147486208

应该是相同的sql，相同的batch大小引起的。

**Comment by ouyuanning** [comment]
今天请假。明天加些log再看看吧

**Comment by DanielZhangQD** [comment]
升级到 `nightly-f5405008`，尝试 insert 几十万条，没有出现之前的在 2000 条就报 invalid alloc size 的问题，但是最终 insert 会失败，CN 会挂掉:
```
    lastState:
      terminated:
        containerID: containerd://a516cee87e3d2c58e0ddb03d63db09f56fb5950659c4f208e715c750abe89713
        exitCode: 2
        finishedAt: "2023-10-13T04:01:02Z"
        reason: Error
        startedAt: "2023-10-13T04:00:31Z"
```
原因应该是：
- Transaction 内数据量太大
- update on duplicate 占用内存太多

所以这个 bug，
- MO 侧，暂时降低优先级，和 https://github.com/matrixorigin/matrixone/issues/11793 一起改
- 应用侧，先改成不在一个 Transaction 内 insert 这么多数据，另外使用 on duplicate ignore

**Comment by ouyuanning** [comment]
目前这个报错一般由2个原因引起
1、数据量大的时候。build hash时暴了。类似 #https://github.com/matrixorigin/MO-Cloud/issues/1414
2、算子对batch没有做切分，类似 https://github.com/matrixorigin/matrixone/issues/11793

1的部分。下周要跟龙冉确认下，是否转到spill的issue上

**Comment by DanielZhangQD** [comment]
应用改成没有使用 Transaction，每次插入 1000 条后，跑了一段时间，开始没有报错，后来又报这个错误了

**Comment by nnsgmsone** [comment]
修改已经合入。。。

**Comment by DanielZhangQD** [comment]
应用暂时修改不使用 `on duplicate key update` 语句规避了这个问题

**Comment by ouyuanning** [comment]
on duplicate key 前的left join引起。
但是修改为right join的话会有正确性问题

**Comment by ouyuanning** [comment]
#12176 是误报
可以用那个方案试一试

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
等spills好了再处理

**Comment by ouyuanning** [comment]
等spills好了才能处理

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by m-schen** [comment]
没看

**Comment by m-schen** [comment]
还在做聚合。

**Comment by m-schen** [comment]
还在做聚合。

**Comment by m-schen** [comment]
休假了

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
还没搞

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
同上 请假中

**Comment by m-schen** [comment]
同上一条评论，目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
预计下周可以开始部分工作？

**Comment by m-schen** [comment]
下个版本再处理了

**Comment by m-schen** [comment]
类似问题均未开始处理。

**Comment by m-schen** [comment]
没看，在忙agg执行上下文占用内存太多的问题

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
近期会统一开始看这些allocate > 111的问题

**Comment by m-schen** [comment]
目前在处理agg结果过大的该相似问题，还没开始弄这个。
这个issue与cloud的1921比较类似。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
无投入。

**Comment by m-schen** [comment]
今天没跟踪这个问题。

**Comment by m-schen** [comment]
没投入

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
现在没空

**Comment by m-schen** [comment]
近期无法投入，在做pipeline的问题。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
还在做pipeline的spool问题。

**Comment by m-schen** [comment]
还在忙spool的事情。

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
处理其他bug中

**Comment by m-schen** [comment]
这个近期没空做。

**Comment by m-schen** [comment]
与上一个评论相同。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
暂无新进展，处理s-1和开发spill中。

**Comment by m-schen** [comment]
与上一个评论相同，正在做spill。

**Comment by m-schen** [comment]
与上一个评论相同，正在做spill。

**Comment by m-schen** [comment]
这几天都还在修关于2.0的稳定bug,要再过几天才能修和spill相关的。

**Comment by m-schen** [comment]
今天请假了

**Comment by m-schen** [comment]
Spill工作正在进行中。

**Comment by aressu1985** [comment]
现在2.0.1进行测试，看看问题是否存在

**Comment by aressu1985** [comment]
经测试，该场景不会再报nternal error: Invalid alloc size 1147486208错误，但是执行一段时间之后会，在执行就会完成hung住，该问题先关闭，新问题用issuehttps://github.com/matrixorigin/MO-Cloud/issues/4423跟踪
