### ISSUE TITLE
[Bug]: mo does not automatically prompt to rollback the transaction

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#12031]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d9cef78459e9759b1eb32282dc6c051149e861c9 (v1.0.0-rc1)
- Hardware parameters:
- OS type:
- Others: https://github.com/matrixorigin/ci-test/actions/runs/6452283753/job/17514084626
```

### Actual Behavior

<img width="997" alt="企业微信截图_12365a47-b95c-40e4-988c-f44a097cd90e" src="https://github.com/matrixorigin/matrixone/assets/22561920/edb36d9d-a2a8-485f-8924-cda0e51dab4f">

### Expected Behavior

<img width="997" alt="企业微信截图_12365a47-b95c-40e4-988c-f44a097cd90e" src="https://github.com/matrixorigin/matrixone/assets/22561920/8818ad69-c839-476a-bbdc-b77704fbf621">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/ci-test/actions/runs/6452283753/job/17514084626
```

**Comment by qingxinhome** [comment]
has Known

**Comment by qingxinhome** [comment]
The issue has been confirmed to be caused by modifications to the test case, but the test results have not been modified @guguducken
