### ISSUE TITLE
[Bug]: MO panic occurs when select proicesslist()

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#12036]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-898ac286
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
1. cloud 环境执行 tpch 1g q1 查询
2. 触发扩容逻辑, 扩容到支持的最大cn节点(可配置)
3. 执行sql, select node_id,conn_id,account,host,query_start,client_host from processlist() a where node_id='62373234-3831-3632-3630-653361303735'  order by query_start desc;
```
当前现象(不是必现):
<img width="1451" alt="截屏2023-10-09 15 23 19" src="https://github.com/matrixorigin/matrixone/assets/39303074/0e049af6-445e-4abf-a6d2-72e797cd1ec2">

**Comment by volgariver6** [comment]
please update the version of MO @tianyahui-python , thank you.

**Comment by aressu1985** [comment]
> ```
> 898ac286
> ```

898ac286

**Comment by volgariver6** [comment]
has been fixed by commit 39f11420d5c80519e25b76a2398c132d76bf63b4

**Comment by tianyahui-python** [comment]
等待cherry-pick到1.0-dev, dev cloud 升级后 验证

**Comment by tianyahui-python** [comment]
等待 dev cloud 升级后 验证
