### ISSUE TITLE
[Bug]: backup mo in standalone environment report file not found

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12049]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

./mo_br backup --host "127.0.0.1" --port 6001 --user "dump" --password "111" --backup_dir "filesystem"  --path "XXXXX"
<img width="1386" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/b9f7eda2-4a9e-4034-ad82-6a48c14b5b82">

### Steps to Reproduce

```Markdown
https://doc.weixin.qq.com/doc/w3_AfsAgAbcAMItX9eKVMJRnuYIfOPg8?scode=AJsA6gc3AA8YzDW1dxAfsAgAbcAMI&is_precreate=1&isEnterEdit=1&dver=3.0.0
```

**Comment by YANGGMM** [comment]
<img width="1397" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/ee0b7155-dc82-40e3-838d-930b3ed603fb">

**Comment by LeftHandCold** [comment]
还没有分析

**Comment by LeftHandCold** [comment]
还没有分析

**Comment by LeftHandCold** [comment]
还没有分析

**Comment by LeftHandCold** [comment]
还没有进展

**Comment by LeftHandCold** [comment]
我用main未复现，最近也在测试一直未出现。
