### ISSUE TITLE
[Bug]: load data error if there is a invalid file in the data file path

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12052]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):344f07ea5bc5a92ae12183eb96848b58a299b393
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> CREATE TABLE NATION  ( 
    -> N_NATIONKEY  INTEGER NOT NULL,
    -> N_NAME       VARCHAR(25) NOT NULL,
    -> N_REGIONKEY  INTEGER NOT NULL,
    -> N_COMMENT    VARCHAR(152),
    -> PRIMARY KEY (N_NATIONKEY)
    -> );
ERROR 1046 (HY000): not connect to a database
mysql> use test;
Database changed
mysql> CREATE TABLE NATION  ( 
    -> N_NATIONKEY  INTEGER NOT NULL,
    -> N_NAME       VARCHAR(25) NOT NULL,
    -> N_REGIONKEY  INTEGER NOT NULL,
    -> N_COMMENT    VARCHAR(152),
    -> PRIMARY KEY (N_NATIONKEY)
    -> );
Query OK, 0 rows affected (0.03 sec)

mysql> load data infile '/Users/sudong/Program/aressu1985/mo-tester/resources/data/nation.tbl' into table nation FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
ERROR 1105 (HY000): stat /Users/sudong/Program/aressu1985/bvt_case: no such file or directory

the file '/Users/sudong/Program/aressu1985/mo-tester/resources/data/nation.tbl' exists, but in the path '/Users/sudong/Program/aressu1985/'
there is a invalid soft link 'bvt_case'
<img width="924" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/93cbefe1-fb68-419b-a0bb-8aad68c14a85">

and this will cause the loading data failed.

[server1.log](https://github.com/matrixorigin/matrixone/files/12854731/server1.log)

### Additional information

DDL:
CREATE TABLE NATION  ( 
N_NATIONKEY  INTEGER NOT NULL,
N_NAME       VARCHAR(25) NOT NULL,
N_REGIONKEY  INTEGER NOT NULL,
N_COMMENT    VARCHAR(152),
PRIMARY KEY (N_NATIONKEY)
);

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
working on other issues

**Comment by reusee** [comment]
working on other issues

**Comment by reusee** [comment]
not working on this.

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
fix PR sent.

**Comment by aressu1985** [comment]
fixed
