### ISSUE TITLE
[Bug]: show account failed, error: `lz4: invalid source or destination buffer too short`

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#12051]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id (e.g. v0.1.0 or 8b23a93): matrixorigin/matrixone-dev:1.0-dev-11d43b223
- Hardware parameters:
- OS type:
- Others:

```
MatrixOne build info:
  The golang version used to build this binary: go version go1.20.5 linux/amd64
  Git branch name: 1.0-dev
  Git commit ID: 11d43b223
  Buildtime: 1696907954
  Version: v1.0.0-rc1
```

### Actual Behavior

found by https://github.com/matrixorigin/MO-Cloud/issues/1422#issuecomment-1754654859

env: aliyun dev unit
- access `mysql -h freetier-02.cn-hangzhou.cluster.aliyun-dev.matrixone.tech -P 6001 -udump -p***** --ssl-mode=DISABLED -A`

- error: `lz4: invalid source or destination buffer too short`

http://47.97.80.230/explore?orgId=1&left=%7B%22datasource%22:%22P3C839627617F91E0%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3C839627617F91E0%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60MetricStorage%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221696924800000%22,%22to%22:%221696928399000%22%7D%7D

![image](https://github.com/matrixorigin/MO-Cloud/assets/3927687/e20d4608-685d-4697-a71b-cc27d89a83ba)

**Comment by DanielZhangQD** [comment]
Hit this issue in the following case:
```
2023/10/10 08:50:56.504563 +0000 ERROR types/instance.go:51 trace {"error": "Error 1105 (HY000): lz4: invalid source or destination buffer too short", "elapsed": "36.083887ms", "rows": 0, "sql": "SELECT count(*) FROM `mo_cloud`.`mo_instance` WHERE id = 'b3a87bec-8976-43ea-a313-b62bca238be5'"}
```

**Comment by daviszhen** [comment]
@XuPeng-SH 建议给 @LeftHandCold  先看一下。

**Comment by LeftHandCold** [comment]
1.这个出问题的文件是一个global checkpoint ，并且超过了4个G，造成了我们的location越界，比如offset这些都是uint32，所以读数据的时候偏移报错。
2.经过分析这个global checkpoint后，发现有560W行（代表全量数据就有130多W个block），从9月28号这个集群运行到现在才10来天，这不太合理。

**Comment by LeftHandCold** [comment]
单个checkpoint 的size限制已经做好，自测中

**Comment by LeftHandCold** [comment]
自测中

**Comment by LeftHandCold** [comment]
fixed

**Comment by LeftHandCold** [comment]
Observe for a week before closing

**Comment by xzxiong** [comment]
at 2023-10-16, aliyun dev unit update mo as `nightly-f6885cea`
further observe is required.
If no repro on cloud next week. Do CLOSE issue.

**Comment by xzxiong** [comment]
checked, not repro.
