### ISSUE TITLE
[Bug]: panic related to logtail happens during `Prometheus ` and `mo-agent` workflow

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12065]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bf330ed804baae63c9b2fa9d472ab108ca3c97cc
- Hardware parameters:
- OS type:
- Others:


on my branch (branch from 1.0dev) https://github.com/daviszhen/matrixone/commits/1009-add-log
```

### Actual Behavior

after panic happens, the mo quit in a few minutes later.

![image](https://github.com/matrixorigin/matrixone/assets/60595215/80c8f275-61cf-411b-8861-65b096ff34c7)

### Expected Behavior

no panic, no quit

### Steps to Reproduce

```Markdown
1. boot standalone mo
2. follow setup in comment.
https://github.com/matrixorigin/matrixone/issues/11966#issuecomment-1752432325
3. run several hours.
```

**Comment by daviszhen** [comment]
完整日志有2.4G。需要找我

**Comment by volgariver6** [comment]
I will take this issue.

**Comment by volgariver6** [comment]
pr committed

**Comment by volgariver6** [comment]
pr committed, wait for merge

**Comment by volgariver6** [comment]
fixed

**Comment by daviszhen** [comment]
已解决
