### ISSUE TITLE
[Bug]: UT TestMOSpan_doProfile failed

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#12074]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6481694873/job/17599714965?pr=12072

**Comment by xzxiong** [comment]
dup. as https://github.com/matrixorigin/matrixone/issues/11864

**Comment by xzxiong** [comment]
mered pr https://github.com/matrixorigin/matrixone/pull/12094
wait for further observation.

**Comment by xzxiong** [comment]
观察中

**Comment by xzxiong** [comment]
after #11864 merged, no repro again.

**Comment by xzxiong** [comment]
@zhangxu19830126 ptal
