### ISSUE TITLE
[Bug]: performance: standalone point select performance lower than 25%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12070]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):76228f5eff5d3a74bad078f20f00bb47b4fe41ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

从性能数据来看，9月27号后点查性能开始下降了25%左右 ，到10.10号一直是低于之前数据水平
<img width="1390" alt="企业微信截图_dd1426d6-031e-4020-ac85-fc5a6dbebd01" src="https://github.com/matrixorigin/matrixone/assets/113406637/89b2db40-41eb-4971-b038-ea838038bae0">
经过二分查找，点查并发100，最后确定以下commit开始变慢，请定位
<img width="1487" alt="企业微信截图_649b7d3f-c5ea-4002-ab40-a71e3c96f612" src="https://github.com/matrixorigin/matrixone/assets/113406637/db3dd0e2-df1a-4046-97d3-5945c38ebb4b">
目前只是standalone点查变慢，tke分布式无此现象

**Comment by heni02** [comment]
@m-schen plz confirm

**Comment by m-schen** [comment]
可能与修改后每个查询单独用一个mpool后导致mpool数目激增有关。需要确认一下。

**Comment by m-schen** [comment]
每个查询单独用一个池子引起了全局map的频繁insert和delete

**Comment by m-schen** [comment]
计划解决从池子取出的内存为什么会变成free不计数的情况后再移除查询独占mpool的问题。

今天没找到为什么不能free的问题。

**Comment by heni02** [comment]
date 10.16发现tke分布式数据也下降了25%左右，（11，12号tke环境问题，性能数据不准确，忽略）
![image](https://github.com/matrixorigin/matrixone/assets/113406637/27ce8fca-ad5a-46fd-83c2-a7db11f65c58)
<img width="695" alt="企业微信截图_0597d036-3e81-48a3-89d1-46c84147f82c" src="https://github.com/matrixorigin/matrixone/assets/113406637/6f424bcc-2868-4a3b-9fbb-0f0814ccb37c">

**Comment by m-schen** [comment]
tke大概率和我这个pr没什么关系。qps的问题已修复。早晨刚合并，不急的话可以等一等晚上的daily。

**Comment by heni02** [comment]
上周排查了该commit分支，性能还是没有回到7万多，今天单独分支revert掉有问题的commit验证qps情况

**Comment by heni02** [comment]
8号的代码revert掉28号的commit，qps：59029
<img width="939" alt="企业微信截图_5d475ede-c6d6-42f6-8ff8-76ea35574c3e" src="https://github.com/matrixorigin/matrixone/assets/113406637/f1d15381-a206-4df0-9418-42140bd8f9be">

当前解决#12135 commit ，qps：48316
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4336e398-6ab0-4645-9e74-76729f3f6e3b)
<img width="695" alt="企业微信截图_d442176f-46a5-4576-b8e1-2b41b1636190" src="https://github.com/matrixorigin/matrixone/assets/113406637/4a8f0989-9a83-474f-8af1-7fbf25e9c1fd">

**Comment by heni02** [comment]
以上查找发现，8号代码revert掉明松的commit，并发500和100 qps分别和之前水平差7000和15000多，说明28和8号间代码也有pr导致下降

截止昨天的回归数据并发500的qps：65460比之前比revert掉的qps还高，回到之前7万多6万多浮动的情况
<img width="688" alt="企业微信截图_cc16436c-194e-4d08-8676-1fba6489136a" src="https://github.com/matrixorigin/matrixone/assets/113406637/2bccf893-d0b7-4a46-b3fc-55e6d2ea8ac3">

并发100截止做的回归数据来看，比2号下降的qps高了一些，但和最好的数据还是差1万多，中间这段时间波动，比较难确定是哪个pr的问题，查找工作量比较大
<img width="654" alt="企业微信截图_fb7a934f-d478-4914-b712-939edfa68e2f" src="https://github.com/matrixorigin/matrixone/assets/113406637/2383cb5c-d8c4-487d-8d23-f25897b4f160">

**Comment by heni02** [comment]
今天重新排查，锁定日期28-8号之间commit，28号到7号之间revert掉明松的pr，delete 100性能8万多，回到了之前的性能水平
<img width="1299" alt="企业微信截图_f1519b02-adae-4dff-a673-fdd99862139d" src="https://github.com/matrixorigin/matrixone/assets/113406637/fbe93da0-ca42-4a9f-bf03-6be615e4cd6b">
<img width="1345" alt="企业微信截图_a7d6b0ea-2bd6-4fbc-beae-3ee490d41873" src="https://github.com/matrixorigin/matrixone/assets/113406637/8078ff25-6db1-4b7f-afdb-ccfa150a2e77">

从8号开始排查，revert掉明松的pr后，delete并发发现这两个pr导致两次下降，昨天的回归数据是6万多，初步怀疑是这两个导致，8号之后的pr可能无影响
<img width="1088" alt="企业微信截图_2ab8b8f3-83b8-4c0f-b303-44d55b24d36f" src="https://github.com/matrixorigin/matrixone/assets/113406637/95a95672-3108-4d6e-9b7f-71fac0c65e4c">
<img width="572" alt="企业微信截图_1e218205-c189-40d7-af7f-7e91f0542bf8" src="https://github.com/matrixorigin/matrixone/assets/113406637/683ce8e4-f2c7-4317-910c-881f0dd7b060">
<img width="545" alt="企业微信截图_b480410a-0919-4f22-8f7d-ed2427566ca2" src="https://github.com/matrixorigin/matrixone/assets/113406637/32d8830b-c2b2-411d-b264-224b1ef1fa2c">

**Comment by heni02** [comment]
@nnsgmsone @gouhongshen plz confirm

**Comment by gouhongshen** [comment]
possible reason: 

this [RP](https://github.com/matrixorigin/matrixone/pull/11932/files) has added `lock` in the type check operation of span.
On the CN side, it's likely that every statement will invoke this `lock` operation.

#12316 removed these lock operations,

**Comment by gouhongshen** [comment]
the test results seem not steady. 

holding, waiting for a new test.

**Comment by gouhongshen** [comment]
waiting for a new test result.

**Comment by heni02** [comment]
分别测试了以下三个分支commit： 测试结果发现qps都是6万多，怀疑是mo本身的波动
苟红深修改pr的分支 ：git clone -b impove_trace_performence https://github.com/gouhongshen/matrixone.git
昨天最新的main分支
9.27号的commit（性能7万多之前）

**Comment by gouhongshen** [comment]
it seems to need more tests to rule out the fluctuation of mo it's self.

**Comment by heni02** [comment]
11月2号单机点查性能情况，500和1000还是和上周的性能差不多，100的性能回到了之前的水平
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c1bc6d4e-47fa-410e-a743-4d9f8c15a0d1)

**Comment by heni02** [comment]
date 11.7 500和1000还是和上周的性能差不多，100的性能回到了之前的水平
![image](https://github.com/matrixorigin/matrixone/assets/113406637/eb83b8e2-8d1a-4b5b-926a-bbffabd01e60)

**Comment by heni02** [comment]
11.15 现象和之前同步的一样，确实很奇怪，现在还不清楚下一步该怎么处理
<img width="1592" alt="企业微信截图_f80aa0f2-8c8b-4599-a691-ddac904e26fa" src="https://github.com/matrixorigin/matrixone/assets/113406637/3b32ea0b-4f34-4bd2-9761-a50bf7ddc198">

**Comment by heni02** [comment]
现在回归性能还是持续是这个水平，暂时定位为mo浮动导致，该单历史较长，先关闭，如有新的疑问再提单
