### ISSUE TITLE
[Bug]: too many small objects in rawlog

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#12075]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are too many small objects in system.rawlog. 
1. How are so many objects generated? It can't be from flush-tail or merge
2. Why merge dosen't work?

**Comment by XuPeng-SH** [comment]
#11975 #12051

**Comment by aptend** [comment]
CN 侧的 rawlog 写 object 的限制是 1 MB，压缩后 100 ~ 300 KB，是小对象的主要来源。bvt 负载下，最密集的阶段，20s 内提交了139个 object。平均一个 object 中的行数为 1000~2000 rows

**Comment by aptend** [comment]
<img width="1132" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/060b64c4-c40d-4316-9f3b-1fe474ac7a9d">
更新了 object 的原始大小打印，在相邻时间内提交的 object 大小依然没有明显超过 1Mb，怀疑 CN 侧存在大小的切分

**Comment by aptend** [comment]
影响切分的参数是 WorkspaceThreshold，目前为 1MB
名义上 TagS3SizeForMOLogger 是为 rawlog 和 statement_info 配置的，但没有实际作用
