### ISSUE TITLE
[Bug]: UT TestBackupData failed

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#12073]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6481694873/job/17599714965?pr=12072

**Comment by LeftHandCold** [comment]
还没来得及看

**Comment by LeftHandCold** [comment]
还没来得及看

**Comment by LeftHandCold** [comment]
还没来得及看

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6636375747/job/18028759268?pr=12336

**Comment by LeftHandCold** [comment]
fixed
