### ISSUE TITLE
[Bug]: [date 10.11]tke regression test: cn restart 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12078]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-e0eb00b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke status :
<img width="973" alt="企业微信截图_bb1719cf-361d-4fb3-8d20-1452e7991d9e" src="https://github.com/matrixorigin/matrixone/assets/113406637/86544aa3-c8b7-4ee6-8d86-5f3fa0bb24a4">

two cn restart , check cn pod mem resources  not oom，but maybe oom？
http://1.14.64.109:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&from=now-24h&to=now&var-datasource=default&var-cluster=&var-namespace=mo-nightly-regression-20231011
<img width="1307" alt="企业微信截图_f12df0e6-84bf-44d6-baa9-94b7b6e4e1df" src="https://github.com/matrixorigin/matrixone/assets/113406637/5176e30b-1916-4ff8-b1e3-2ecb8c14e2ba">
<img width="1356" alt="企业微信截图_0a80405f-2fcc-42e4-84c0-d49ef148ce4a" src="https://github.com/matrixorigin/matrixone/assets/113406637/188296d6-3c1f-49b3-8382-af3392ac1489">

regresson job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6477240285/job/17597937054
execute load data 100_columns/40000000_100_columns_load_data.csv start reported error： can not connect to remote backend，maybe load caused cn restart？
<img width="1406" alt="企业微信截图_8d3ad9d6-8a26-40d3-ac59-4cf337d29fef" src="https://github.com/matrixorigin/matrixone/assets/113406637/b9899c19-68a0-412d-977e-63842123df44">

check fail conection errror log，found not panic or fatal log
http://1.14.64.109:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231011%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221697020200000%22,%22to%22:%221697020439000%22%7D%7D

profile:
[prof_info.tar.gz](https://github.com/matrixorigin/matrixone/files/12876765/prof_info.tar.gz)

**Comment by sukki37** [comment]
The issue doesn't provide relevant details. We need to retest after eliminate the factors related to environmental issues. It's temporarily downgraded and assigned to @sukki37 .

**Comment by heni02** [comment]
莫尘看了profile，也不太像oom，结合load data内存使用无大幅增长，怀疑坏境问题，这个单先关闭
