### ISSUE TITLE
[Bug]: CN failed to start: panic: timeout

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12080]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DN failed to start:

```
panic: timeout

goroutine 1 [running]:
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:108 +0x436
```

raw log: 
[Explore-logs-2023-10-12 12_23_40.txt](https://github.com/matrixorigin/matrixone/files/12877091/Explore-logs-2023-10-12.12_23_40.txt)

**Comment by volgariver6** [comment]
还没有明显进展，本地和eks上都无法复现。

主要的错误是 `use of closed network connection`，这个应该是超时的panic把程序停掉时，context 机制把协程停掉，然后报的。所以根本原因还是Read读操作 hang 住了。

**Comment by volgariver6** [comment]
fixed

**Comment by aylei** [comment]
closing as no longer reproduced
