### ISSUE TITLE
[Bug]: alter sequence results incorrect 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12088]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0070abe134880d9b12e8b4108647a9ebd42fb7aa
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.
mo:
<img width="1147" alt="企业微信截图_934e1376-b2c6-4c8d-a49e-1365f81da109" src="https://github.com/matrixorigin/matrixone/assets/113406637/74d9c529-151d-4f48-8838-a5303576e0fc">
pg:
<img width="1199" alt="企业微信截图_dad4064e-4b18-4534-ad96-2afbcddee227" src="https://github.com/matrixorigin/matrixone/assets/113406637/81240969-2da3-4fde-8cd5-6c88df29fb6d">

case:
create sequence if not exists alter_seq_01 as bigint increment by 100 minvalue 20  start with 50 cycle;
select nextval('alter_seq_01'),currval('alter_seq_01');
alter sequence if exists alter_seq_01 as int increment by 200 minvalue 10 no cycle;
select nextval('alter_seq_01'),currval('alter_seq_01');

2.
mo:
<img width="855" alt="企业微信截图_2057bf73-6a66-45a3-ac37-619f7da05de5" src="https://github.com/matrixorigin/matrixone/assets/113406637/8a258c5a-beed-4e21-8136-41025e018c0f">
pg：
<img width="747" alt="企业微信截图_d57e1a68-bf53-4e25-b79d-d9f5e48c1bff" src="https://github.com/matrixorigin/matrixone/assets/113406637/f061d708-eb47-4e5f-b4db-7c4f4d681d56">

case：
create sequence alter_seq_02 increment 3;
select nextval('alter_seq_02');
select nextval('alter_seq_02'),currval('alter_seq_02');
alter sequence alter_seq_02 increment 10;
select nextval('alter_seq_02'),currval('alter_seq_02');

**Comment by heni02** [comment]
3.
mo:
<img width="699" alt="企业微信截图_d500e6d2-27ac-4924-abba-20beac567b4f" src="https://github.com/matrixorigin/matrixone/assets/113406637/579885c9-f136-415b-98f1-41beefafe8b8">
pg:
<img width="738" alt="企业微信截图_b9da43b2-81de-4c33-9b77-55228d6fca26" src="https://github.com/matrixorigin/matrixone/assets/113406637/72afb7eb-a53c-413d-b874-7401089a53e3">

case:
create sequence alter_seq_03 increment by 10;
alter sequence alter_seq_03;

**Comment by heni02** [comment]
4.
mo: 
<img width="773" alt="企业微信截图_65b9e142-84f3-4049-9d35-fe50d3b19848" src="https://github.com/matrixorigin/matrixone/assets/113406637/99ac1f7b-a68c-4407-b2fb-d826e934f521">
pg：
<img width="731" alt="企业微信截图_fba355e4-ed26-419c-87de-dea75d8c3a8c" src="https://github.com/matrixorigin/matrixone/assets/113406637/579d93f4-959d-4060-a3f3-a0077d333b2c">

**Comment by YANGGMM** [comment]
create sequence alter_seq_03 start 1000;
select nextval('alter_seq_03'),currval('alter_seq_03');
select nextval('alter_seq_03'),currval('alter_seq_03');
select nextval('alter_seq_03'),currval('alter_seq_03');
alter sequence alter_seq_03 start 1001;
select nextval('alter_seq_03'),currval('alter_seq_03');

**Comment by heni02** [comment]
case pr confirm,closed 
commit id :0e1cd2510ab056fb4f0646c14b694a4bbe5e9787
