### ISSUE TITLE
[Bug]: ut failed `TestDeadLockWith2Txn`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12086]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6492203839/job/17630721167?pr=12082

<img width="755" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/22ccf3cd-b211-4fea-97ac-0dfcd6253660">

**Comment by zhangxu19830126** [comment]
dup with #11827
