### ISSUE TITLE
[Feature Request]: refactor disttae.txnTable.GetColumMetadataScanInfo(...) by object list

### ISSUE THREAD

**Issue by triump2020** [matrixorigin/matrixone#12105]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

  refactor GetColumMetadataScanInfo() in disttae package by object list

**Comment by triump2020** [comment]
relate to #11556

**Comment by w-zr** [comment]
code in https://github.com/matrixorigin/matrixone/pull/12091
