### ISSUE TITLE
[Feature Request]: Support log2 function in SQL

### ISSUE THREAD

**Issue by xmh1011** [matrixorigin/matrixone#12111]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

like this: https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_log2

**Comment by xmh1011** [comment]
I'll support it.

**Comment by gouhongshen** [comment]
@heni02 PTAL after this merged.

**Comment by heni02** [comment]
plz confirm milestone
