### ISSUE TITLE
clarify creating and dropping index requirements 

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#1212]
The requirements of creating and dropping index operations are not clear. For example, we cannot create an index with the same "Name" with existing names. We cannot create a "NumBsi" index for a string typed column. We cannot drop an index that does not exist...

**Comment by jiangxinmeng1** [comment]
Index type: bsi
Constraints: Only numeric BSI

Index name: 
Index name should be unique for a table.

Index columns:
For an index, there should be at least one column.
The columns should exist in the table.

**Comment by zzl200012** [comment]
Here's a simple usage of the newly added index operations for AOE storage:
### Create:
For an [aoedb.DB](https://github.com/matrixorigin/matrixone/blob/45755bfae19e4bb5385b380c8547ba2fc35427ed/pkg/vm/engine/aoe/storage/aoedb/v2/db.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L28), we support table-level index creation in one operation, that is to say, if you create multiple indices for several tables at one time in catalog, you should invoke several times of this method in aoe storage. Within [CreateIndexCtx](https://github.com/matrixorigin/matrixone/blob/45755bfae19e4bb5385b380c8547ba2fc35427ed/pkg/vm/engine/aoe/storage/aoedb/v2/ctx.go#L70), the target table is needed; and **Id** field of [IndexInfo](https://github.com/matrixorigin/matrixone/blob/45755bfae19e4bb5385b380c8547ba2fc35427ed/pkg/vm/engine/aoe/storage/metadata/v1/schema.go#L33) within the [CreateIndexCtx.Indices.Indice](https://github.com/matrixorigin/matrixone/blob/45755bfae19e4bb5385b380c8547ba2fc35427ed/pkg/vm/engine/aoe/storage/metadata/v1/schema.go#L59) is not needed, others are required. It's upper layer's job to construct this ctx, and call this method. The method would return no error once the internal index metadata has been updated, and indices would be built asynchronously.
### Drop:
Drop is similar with create, it also supports table-level indices change only. The difference is that [DropIndexCtx](https://github.com/matrixorigin/matrixone/blob/45755bfae19e4bb5385b380c8547ba2fc35427ed/pkg/vm/engine/aoe/storage/aoedb/v2/ctx.go#L76) only requires the target table name and indices' names you wanna drop. Drop also works in an asynchronous way, for which you can say we have dropped successfully once it returns no error, and do not care about the underlying circumstance.

cc @LeftHandCold @jiangxinmeng1

**Comment by XuPeng-SH** [comment]
#1241
