### ISSUE TITLE
[Bug]: Unique Index with PK column, throws inconsistent error messages

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#12123]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5a52f65e7b56cd9dba95c8a3288ebf807be6eb92
```

### Actual Behavior

```sql
create table tbl(col1 int primary key, col2 float);
create unique index key1 on tbl(col1, col2);
insert into tbl values(1 , 100.00);
```

Upon reinserting the same row, I should get PK warning as expected. 

However, if I repeatedly continue doing the same operation, the output changes randomly between 2 variants. 
```sql
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '(1,100)' for key '__mo_index_idx_col'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '(1,100)' for key '__mo_index_idx_col'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '(1,100)' for key '__mo_index_idx_col'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '(1,100)' for key '__mo_index_idx_col'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
mysql> insert into tbl values(1 , 100.00);
ERROR 1062 (HY000): Duplicate entry '(1,100)' for key '__mo_index_idx_col'
```
My point is the error message switches between these 2 types, randomly.

### Expected Behavior

The expected behavior is that it should throw the same error every single time.
```
ERROR 1062 (HY000): Duplicate entry '1' for key 'col1'
```

### Additional Information

The content in the Secondary Index Table looks good.

![image](https://github.com/matrixorigin/matrixone/assets/9638314/feaa8b4a-d82d-40d3-a9b5-0ab22ee4c4d4)

**Comment by arjunsk** [comment]
I am facing the same issue for https://github.com/matrixorigin/matrixone/pull/12093

**Comment by arjunsk** [comment]
Based on the recent discussion with @ouyuanning , this is an expected behavior. 


> Such error messages are normal. Because we will perform two types of checks in parallel
> 
> 1. For the tbl table. We will check if the primary key col1 is duplicated
> 
> 2. For unique index key1 on tbl (col1, col2). We will also conduct an examination
> 
> Because these two checks are parallel, we cannot guarantee which check detects the error first, so there may be differences in error messages

To handle such things in BVT, we use this approach https://github.com/matrixorigin/matrixone/pull/12093/commits/a8988491b7c3dd6842cccacc32ed9a70ca41b7ad

**Comment by ouyuanning** [comment]
Such error messages are normal. Because we will perform two types of checks in parallel

1. For the tbl table. We will check if the primary key col1 is duplicated

2. For unique index key1 on tbl (col1, col2). We will also conduct an examination

Because these two checks are parallel, we cannot guarantee which check detects the error first, so there may be differences in error messages
