### ISSUE TITLE
[Subtask]: Count the number of CN writes to s3 while do insert

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#12128]
### Parent Issue

#10862

### Detail of Subtask

When inserting big data, cn will write s3 and count the number of these s3

**Comment by LeftHandCold** [comment]
Need to discuss implementation with @Morranto

**Comment by LeftHandCold** [comment]
Need to wait for @Morranto  design and downgrade to p0

**Comment by Morranto** [comment]
感觉这个功能原来是有的，暂时不用做这个issue
