### ISSUE TITLE
[Bug]: mysql client execute sql, error info: transaction has been committed or aborted.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#12143]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1.0-dev-a6f3e1a42
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

link issue: https://github.com/matrixorigin/MO-Cloud/issues/1482

**Comment by ouyuanning** [comment]
只要执行时间长，超过一定时间都会报这个错误。本地debug的时候，只要久一点不next就会报。
这里亚辉反馈的是 订阅（PUBLICATION）功能执行过久造成。

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by sukki37** [comment]
maybe dup with #12031

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/1a6a81a0-d96a-413c-a336-d6c35ab60168)

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/de41fe60-33f3-4d5f-a82f-c58be2a1cd8a)

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/21edbcf5-dc79-4492-96a9-ff7583237fd8)

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/a4d998e6-252f-4a42-a494-2fc4a96faef8)

**Comment by qingxinhome** [comment]
The issue is duplicated with # 12167, so it needs to be correlated and the duplicate issue needs to be closed. @tianyahui-python @sukki37 @daviszhen
