### ISSUE TITLE
[Bug]: internal error: panic runtime error: invalid memory address or nil pointer dereference when filter value is ?

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12158]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4cdded17b1dd5ed09554de8b6f7149588bba4764
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select k from sbtest1 where id = ?;
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:260
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/container/vector/vector.go:113
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).GetPrepareParamsAt
	/Users/sudong/Progr
mysql> exit

log
[service.tar.gz](https://github.com/matrixorigin/matrixone/files/12926253/service.tar.gz)

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by aressu1985** [comment]
fixed
