### ISSUE TITLE
[Bug]:  No results returned for more than 5 minutes in a bvt test with race turned on

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12169]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6532239791/job/17735043563

<img width="1164" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/d49b1360-e98e-4eb1-9d6d-6bcb1f186457">

[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12930276/multi-cn-e2e-with-race-linux-x86-reports.zip)

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6531798014/job/17733701939

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6531157446/job/17731824358

**Comment by ouyuanning** [comment]
error sql:
```
[SCRIPT   FILE]: /home/runner/work/matrixone/matrixone/head/test/distributed/cases/zz_accesscontrol/drop_account.sql
[ROW    NUMBER]: 16
[SQL STATEMENT]: create account if not exists drop_account_03 ADMIN_NAME 'root' IDENTIFIED BY '1234567890';
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
MO does not return result in 300000 ms. 
```

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
<img width="2656" alt="企业微信截图_108e6d7a-73eb-42b8-a2df-f23936ea9c05" src="https://github.com/matrixorigin/matrixone/assets/60595215/5b101a80-657c-4856-a6b8-9f5bf8c28dfe">

**Comment by daviszhen** [comment]
打开trace，跑bvt有两个现象：
1，内存消耗会增加。这是昨天虚拟机oom的原因。我今天抓heap profile 但是没看出来哪个模块内存暴涨。这块，我需要再看看。

2，我本地mac跑出来race导致mo挂掉。之后bvt全挂了。
<img width="1348" alt="企业微信截图_3d3b8bbd-c857-4fb3-aeca-ae3e39b4f69e" src="https://github.com/matrixorigin/matrixone/assets/60595215/d22c0057-b813-47ef-b069-650eecd625ab">

**Comment by daviszhen** [comment]
加了race的mo，跑bvt整体不到9G，跑race的ci 机器要至少10G。

race ci现在是4c14G。应该没什么问题了

**Comment by daviszhen** [comment]
与 @sukki37 协商后降到s1

**Comment by daviszhen** [comment]
降到s1

**Comment by sukki37** [comment]
After the update of runner resources (from 2c to 8c), the issue no longer recurs. In the scenario where the CPU is limited, the bug with race enable can temporarily be deprioritized.

**Comment by daviszhen** [comment]
未投入
