### ISSUE TITLE
[Bug]:  mo hung in a bvt test with race turned on

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12166]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): many pr
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6544656910

<img width="1848" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/a0acd90b-492b-456d-b493-e258c634f340">

<img width="1773" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/1549795c-5e61-407b-b18d-fecfc5d58d27">

And many `cn service is not ready, retry later` error messages in logs.

[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12929907/multi-cn-e2e-with-race-linux-x86-reports.zip)

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6535417090/job/17744827408

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
核心问题应该是logtail client和server端超时，然后重连没有成功

```
371364 {"level":"INFO","time":"2023/10/17 09:16:02.008051 +0000","caller":"disttae/logtailPushModel.go:363","msg":"[log-tail-push-client] clean finished, start to reconnect to tn log tail service"}
```

**Comment by volgariver6** [comment]
fixed
