### ISSUE TITLE
[Bug]: some `select` against `statement_info` failed during bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12168]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6541067487/job/17762029555

<img width="2084" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/cac7ca51-6c57-4c2c-9a3e-412add80107c">

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6548014027/job/17781709874

**Comment by gavinyue** [comment]
今天看看

**Comment by gavinyue** [comment]
试了一下这个， 就是又个select statement 没有被记录。 我需要开了race 再测试一下。

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/issues/12042

都是写入偶尔的问题。  看看使用load之后， 是不是还存在

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by sukki37** [comment]
When running MO for BVT testing with race enabled, errors related to statement_info queries occur frequently.

https://github.com/matrixorigin/matrixone/actions/runs/7036372795/job/19149429051
https://github.com/matrixorigin/matrixone/actions/runs/7043577076/job/19170458791
https://github.com/matrixorigin/matrixone/actions/runs/7040613001/job/19162186013

**Comment by gavinyue** [comment]
这个如果需要ctl cmd来flush的话，  需要很大的工作。 

1.1 恐怕完成不了

**Comment by gavinyue** [comment]
主要原因是 stmt是分散在各个cn上的。 

而且就算有了这个命令， 只是缩短了决定要写的时间， 但是真正写的时间还是不可控。

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
Pending

**Comment by gavinyue** [comment]
暂时没来及的解决

**Comment by gavinyue** [comment]
Pending

**Comment by sukki37** [comment]
repro: 
https://github.com/matrixorigin/matrixone/actions/runs/7346060546/job/20000210682?pr=13857
https://github.com/matrixorigin/matrixone/actions/runs/7396619125/job/20122259309
https://github.com/matrixorigin/matrixone/actions/runs/7397232166/job/20123977845
https://github.com/matrixorigin/matrixone/actions/runs/7396619125/job/20122259309

**Comment by gavinyue** [comment]
正在看

**Comment by xzxiong** [comment]
repro:
https://github.com/matrixorigin/matrixone/actions/runs/7404727910/job/20146654826?pr=13923
https://github.com/matrixorigin/matrixone/actions/runs/7404421431/job/20145908049?pr=13963

**Comment by gavinyue** [comment]
下载了error report

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7408832551/job/20157854807?pr=14003

**Comment by gavinyue** [comment]
问题已经找到， 和聚合没有关系，主要是在写入statementinfo的时候， 会出现失败，然后数据去了csv，  然后因为测试的case是select 然后对比结果， 所以它就会和预期结果不一样。

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13876

对老失败的地方做了一些修改。 

整体来说select from statementinfo 是个比较容易被影响的测试。

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/7435891547/attempts/1?pr=13876

基本上修复， 正在多跑几遍验证

**Comment by gavinyue** [comment]
跑了五六遍， 都没什么问题， 准备merge了

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/7435891547/attempts/1?pr=13876

等待approval 然后 merge

**Comment by gavinyue** [comment]
正在等merge

**Comment by gavinyue** [comment]
PR 已经merge,  等待修复验证

**Comment by gavinyue** [comment]
明天看Bvt 的情况 是否转会给creator

**Comment by gavinyue** [comment]
新的PR

https://github.com/matrixorigin/matrixone/pull/14235
继续修复吧

还是出现在aggr上面， 挨着的insert, select也没被聚合，  可能的原因很多

问题： https://github.com/matrixorigin/matrixone/actions/runs/7535828907/job/20512379869

**Comment by gavinyue** [comment]
正在等pr merge

**Comment by xzxiong** [comment]
note: bvt 可以考虑引入针对`最终一致性`验证的 case机制

**Comment by xzxiong** [comment]
明天整理一下需review的 pr

**Comment by xzxiong** [comment]
梳理中

**Comment by xzxiong** [comment]
workding on

**Comment by guguducken** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7723275522/job/21053995746#step:5:1595

**Comment by xzxiong** [comment]
under review

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
new repo https://github.com/matrixorigin/matrixone/actions/runs/8107402104/job/22158877969?pr=14382
need retry with newest main (target commit: 87827601c)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/214a98a8-7407-4e8d-b2c8-fd89c0962fab)

**Comment by xzxiong** [comment]
case `statement_query_type`, fixed by  https://github.com/matrixorigin/matrixone/pull/14569

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/14569
ptal @sukki37
