### ISSUE TITLE
[Bug]: `the transaction b1990f83ea73468db9f1620c00362ad6 has been committed or aborted`  in a bvt test with race turned on

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12167]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6542682065/job/17768031068

<img width="976" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/aef42b6d-e592-4306-b6e7-f625fe45c5d0">

[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12930014/multi-cn-e2e-with-race-linux-x86-reports.zip)

### Additional information

maybe related to #12166

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6532532910/job/17735895372

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6555389147/job/17803740257

**Comment by ouyuanning** [comment]
估计是时间太长造成的。本地开发，debug时候，如果太久不next，也经常会报这个错误

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6555389147/job/17803740257

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
maybe fixed

**Comment by sukki37** [comment]
Not repro for a few days, close for now.
