### ISSUE TITLE
[Bug]: DN took about 26 minutes to start logtail server

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12174]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1e94328e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
cat dn-log.txt | grep "mo-service|start logtail"
/mo-service -cfg /tmp/tmp.0MHpdRmdIB -debug-http=:6060
{"level":"INFO","time":"2023/10/18 01:49:50.906698 +0000","caller":"mo-service/launch.go:223","msg":"hakeeper not ready, retry"}
{"level":"INFO","time":"2023/10/18 01:49:53.824427 +0000","caller":"mo-service/launch.go:223","msg":"hakeeper not ready, retry"}
{"level":"INFO","time":"2023/10/18 02:16:06.149096 +0000","name":"tn-service.logtail-push-service","caller":"service/server.go:502","msg":"start logtail service","uuid":"33376565-3237-3162-3439-323631326537","server-id":"85fe6a66-3bd1-4644-af9b-7f832eab0304"}
```

DN took about 26 minutes to start logtail server

full log: [dn.txt](https://github.com/matrixorigin/matrixone/files/12974534/dn.txt)

### Expected Behavior

DN should start logtail server in reasonable time

**Comment by LeftHandCold** [comment]
<img width="1622" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/2516741d-ce01-43b8-99e1-7bd0a97cd8e2">
DN's memory cache is 1G, but a global checkpoint in the current cluster is 1.4G, so DN's replay checkpoint prefetch does not take effect. As a result, replay checkpoint takes 14 minutes.

**Comment by aylei** [comment]
> <img alt="image" width="1622" src="https://user-images.githubusercontent.com/14086886/276104877-2516741d-ce01-43b8-99e1-7bd0a97cd8e2.png"> DN's memory cache is 1G, but a global checkpoint in the current cluster is 1.4G, so DN's replay checkpoint prefetch does not take effect. As a result, replay checkpoint takes 14 minutes.

what about another 12 minutes?

**Comment by LeftHandCold** [comment]
> > <img alt="image" width="1622" src="https://user-images.githubusercontent.com/14086886/276104877-2516741d-ce01-43b8-99e1-7bd0a97cd8e2.png"> DN's memory cache is 1G, but a global checkpoint in the current cluster is 1.4G, so DN's replay checkpoint prefetch does not take effect. As a result, replay checkpoint takes 14 minutes.
> 
> what about another 12 minutes?

It is the consumption of replay WAL.
The reason is that from around 5 pm yesterday to the restart at 10 am this morning, the cluster did not perform checkpoint. So there is a lot of WAL data.

**Comment by LeftHandCold** [comment]
<img width="1710" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/d94434bf-d712-41df-9244-3b9a61e33e06">

**Comment by LeftHandCold** [comment]
<img width="2369" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/6b73b6a2-9472-4a55-9bd4-a2dd285cd276">

**Comment by sukki37** [comment]
> It is the consumption of replay WAL.
> The reason is that from around 5 pm yesterday to the restart at 10 am this morning, the cluster did not perform checkpoint. So there is a lot of WAL data.

No checkpoint has been performed for 17 hours, is this expected behavior?

**Comment by aylei** [comment]
```
k -n freetier-01 logs default-dn-0 |grep "logger init|start log"
{"level":"INFO","time":"2023/10/21 08:19:10.139548 +0000","caller":"logutil/internal.go:37","msg":"MO logger init, level=, log file=, stackLevel=panic"}
{"level":"INFO","time":"2023/10/21 08:43:06.663499 +0000","name":"tn-service.logtail-push-service","caller":"service/server.go:527","msg":"start logtail service","uuid":"33376565-3237-3162-3439-323631326537","server-id":"ab8d8de0-e69f-4e79-b174-4ccd78b75810"}
```

Another case, takes 24 minutes

full log: [dn.txt](https://github.com/matrixorigin/matrixone/files/13060311/dn.txt)

@LeftHandCold

**Comment by aylei** [comment]
closing as fixed
