### ISSUE TITLE
[Bug]: `table_func_metadata_scan` failed in a bvt test with race turned on

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12170]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6530549182/job/17730043646

<img width="1066" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/cc548d4a-17ff-4a6b-ac29-5080fb1c8a80">

[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/12930323/multi-cn-e2e-with-race-linux-x86-reports.zip)

**Comment by ouyuanning** [comment]
seems coded by @dongdongyang33 
@iamlinjunhong help to have a look

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂时未复现

**Comment by iamlinjunhong** [comment]
暂时未复现

**Comment by iamlinjunhong** [comment]
暂未复现，加了日志，@sukki37 商量降低优先级

**Comment by iamlinjunhong** [comment]
调用 ForeachVisibleDataObject 未拿到数据，请存储的同事帮忙看看
<img width="2472" alt="截屏2023-11-30 17 56 26" src="https://github.com/matrixorigin/matrixone/assets/49111204/bb609e8c-3903-4ef3-aa62-1bf4bb080fd5">

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7043838587/job/19170960482

**Comment by triump2020** [comment]
refer to #12771

**Comment by triump2020** [comment]
refer to https://github.com/matrixorigin/matrixone/issues/12771

**Comment by triump2020** [comment]
基本定位到问题： 当 两个事务在不同的session 里，MO  默认不保证 session 之间的 外部一致性，导致第二个事务的snapshot ts 小于了第一个事务的commit ts 

可以修改test case : sync commit , 这样可以保证 一个client 中 的所有session 之间的外部一致性

**Comment by triump2020** [comment]
@aressu1985   Pls  update  mo tester tool to ensure consistency between old and new sessions  in case of  network connection is broken.

**Comment by triump2020** [comment]
@sukki37   Dup with #12771  ,pls close it.
