### ISSUE TITLE
[Bug]:  show columns from `SCHEMATA` error in ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12196]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): f57c1b3616a5a5536eb74ce9ad53f20633f2bbf1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="946" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f1be7eef-123c-4ffd-a5b8-161f7d02d6f7">

log: 
[e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13038463/e2e-linux-x86-reports.zip)
[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13038477/1-cn-e2e-linux-x86-reports.zip)
[multi-cn-e2e-with-proxy-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13038478/multi-cn-e2e-with-proxy-linux-x86-reports.zip)

### Expected Behavior

<img width="1388" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/84034d3d-66e2-415e-bbf6-008d96fd9517">

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test。 @Ariznawlll @sukki37 @daviszhen

**Comment by Ariznawlll** [comment]
verified!
