### ISSUE TITLE
[Bug]: mo cloud environment cn instance occurs oom

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12193]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="692" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/920b9b7d-341c-4c1f-a13f-f2dc27a9e506">

profile can be found in http://localhost:3000/explore?panes=%7B%22_tx%22:%7B%22datasource%22:%22a9cd9c20-511b-49ea-b5c4-18d06de570b0%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%3D%5C%22default-cn-fs7fr%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22a9cd9c20-511b-49ea-b5c4-18d06de570b0%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221697680600000%22,%22to%22:%221697680650000%22%7D%7D%7D&schemaVersion=1&orgId=1
ps: you need to generate a kubeconfig to access this environment, execute `k -n pyroscope-test port-forward grafana-867d8dfb77-6cnrk  3000:3000`, and click the above link.

### Additional information

<img width="1881" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/187deb55-7c67-4eb4-bf87-bae8b5485aaf">

**Comment by nnsgmsone** [comment]
![截图 2023-10-19 14-11-44](https://github.com/matrixorigin/matrixone/assets/31609524/88e848d8-c697-49eb-80e5-4d2ca5fed544)

**Comment by ouyuanning** [comment]
@badboynt1 先帮忙看看吧

**Comment by reusee** [comment]
The prefetch was too aggressive, causing too much memory allocations.

**Comment by reusee** [comment]
> ![截图 2023-10-19 14-11-44](https://user-images.githubusercontent.com/31609524/276504935-88e848d8-c697-49eb-80e5-4d2ca5fed544.png)

从这个图看，主要是 BlockReadInner -> vector.GetUnionAllFunction 
这里有个 TODO： https://github.com/matrixorigin/matrixone/blob/3226c8b05c99b8e966fdb7d2799d2ec5dd94b92b/pkg/vm/engine/tae/blockio/read.go#L353
先转 @XuPeng-SH 优化这一块

**Comment by XuPeng-SH** [comment]
> > ![截图 2023-10-19 14-11-44](https://user-images.githubusercontent.com/31609524/276504935-88e848d8-c697-49eb-80e5-4d2ca5fed544.png)
> 
> 从这个图看，主要是 BlockReadInner -> vector.GetUnionAllFunction 这里有个 TODO：
> 
> https://github.com/matrixorigin/matrixone/blob/3226c8b05c99b8e966fdb7d2799d2ec5dd94b92b/pkg/vm/engine/tae/blockio/read.go#L353
> 
> 
> 先转 @XuPeng-SH 优化这一块

this TODO is to avoid data copy and allocation from cache. here we allocate and copy because if we passed the cached readonly vector outside, it would be modified. 

@LeftHandCold please have check whether we can pass the reasonly caches vector outside now. if not, please assign this issue to the right guy.

**Comment by ouyuanning** [comment]
根因是因为，从blockio.BlockRead 的时候，是会复制一份数据造成。
如果要去掉这个复制，要保证调用方不clean，不更改数据。
目前的调用方有2个
1、txn_table.go 的  readNewRowid  这里是临时使用，并不会更改数据
2、disttae/reader.go 的 blockReader.Read ，  这里是读取到直接返回。这里并没有办法保证返回的batch的只读性

可能可以等pipeline重构之后，如果能保证算子自己产生的batch，肯定不会被别的算子clean的前提下。
是可以避免拷贝的

**Comment by ouyuanning** [comment]
等pipeline重构结束后，跟龙冉商量处理方案和处理人

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
建了个重构的特性处理
https://github.com/matrixorigin/matrixone/issues/12505

**Comment by ouyuanning** [comment]
待agg和hash table从batch移走之后处理

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
待agg和hash table从batch移走之后，修改pipeline得内存管理模型才能处理

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
要等内存复用和mpool leak都处理完

**Comment by ouyuanning** [comment]
要等内存复用和mpool leak都处理完

**Comment by sukki37** [comment]
too many duplicated oom issues, close this one
