### ISSUE TITLE
[Bug]: Purge Log has memory bug

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#12190]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![截图 2023-10-19 11-09-33](https://github.com/matrixorigin/matrixone/assets/31609524/00e72463-bc3a-4976-8322-ea7a65cac212)
delete删除日志表占用了大量的内存，这个很不合理。。目前的实现如果数据量太大会写s3。。。大约为10MB一个文件。。。这里占用了大约5.62GB。。那么删除数据量大约为5.62/10MB。。。这个貌似太大了。。。

**Comment by nnsgmsone** [comment]
在稳定性测试中。。这个prunelog的数据量会一直增加。。关联issue #12142

**Comment by xzxiong** [comment]
据了解，CN 的代码有个bug：目前 1 MB会就会触发写文件，而不是原定的 10MB

**Comment by xzxiong** [comment]
讨论记录：
1. buildInPurgeLog 需要执行SQL `select purge_log('rawlog,...', '2023-10-10')` 才会触发，另bvt 中也会执行
2. buildInPurgeLog 时间上会转为 delete语句 `delete from system.rawlog where timestamp < '2023-10-10'`, 不存在额外的设计。
3. buildInpurgeLog 支持删除 rawlog、statement_info、metric；其中 rawlog 的数据量最大，当仅能达到 100 GiB  以内。

目前最大的猜测：在哪里存在 并发执行了 purge_log，导致内存同时使用。

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
@nnsgmsone ptal
