### ISSUE TITLE
[Bug]: ut TestRangeLockWithWaitQueue fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12203]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="444" alt="企业微信截图_ce0cdd04-9fcd-4bbb-92fa-2e1dcce5b046" src="https://github.com/matrixorigin/matrixone/assets/26563383/6f3f168c-8fb3-49d7-ac5d-6d759131b850">

https://github.com/matrixorigin/matrixone/actions/runs/6571429965/job/17850555406?pr=12201

**Comment by gouhongshen** [comment]
@zhangxu19830126 旭哥有空看下这个

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/e05318af-46f5-419a-8ad7-44200d1911b6)

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/6583108033/job/17885622796?pr=12227

**Comment by zhangxu19830126** [comment]
fixed
