### ISSUE TITLE
[Bug]: cn oom  when test create account and alter account, retry many times

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12204]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ns: pengzhen
<img width="1135" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/f28e76c9-7bd9-407b-8a79-6209dd274458">

### Steps to Reproduce

```go
package main

import (
	"database/sql"
	"flag"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"log"
	"time"
)

var testFlag = flag.String("test", "", "")

func main() {
	flag.Parse()
	if len(*testFlag) == 0 {
		panic("")
	}
	for i := 0; i < 20; i++ {
		go ExecSql(*testFlag, i)
		time.Sleep(time.Second * 1)
	}
	time.Sleep(time.Hour * 24)
}

func ExecSql(str string, acc int) {
	// 连接数据库
	db, err := sql.Open("mysql", "dump:111@tcp(127.0.0.1:6001)/abc")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	// 测试连接
	err = db.Ping()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("成功连接到MySQL数据库！")

	index := uint64(0)
	// 执行查询语句
	for {
		_, err = db.Query(fmt.Sprintf("create account acc_idx_%s_%d_%d ADMIN_NAME 'root' IDENTIFIED BY '123456';", str, acc+200, index))
		if err != nil {
			log.Fatal(err)
		}

		_, err = db.Query(fmt.Sprintf("alter account acc_idx_%s_%d_%d ADMIN_NAME 'root' IDENTIFIED BY '12345678';", str, acc+200, index))
		if err != nil {
			log.Fatal(err)
		}
		time.Sleep(time.Millisecond * 60)
		index++
	}

}

```

**Comment by YANGGMM** [comment]
> @YANGGMM could you kindly add some profile results for your case?

ok

**Comment by YANGGMM** [comment]
http://localhost:4040/?query=memory%3Ainuse_space%3Abytes%3Aspace%3Abytes%7Bservice_name%3D%22pengzhen%2Fmain%22%7D&from=1697680800&until=1697688000

**Comment by loveRhythm1990** [comment]
<img width="1554" alt="image" src="https://github.com/matrixorigin/matrixone/assets/52204121/b39c5a66-2d50-4fd8-811b-0da28d051f75">
<img width="1561" alt="image" src="https://github.com/matrixorigin/matrixone/assets/52204121/1acf8667-016a-405a-8987-edcbe5d957bb">
<img width="1556" alt="image" src="https://github.com/matrixorigin/matrixone/assets/52204121/aafea541-83c8-4459-8308-b6f33b4fe700">

nice profile tool

**Comment by sukki37** [comment]
similar to #12193

**Comment by LeftHandCold** [comment]
<img width="878" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/64561a8d-db37-4106-a250-84a5c09bba62">

**Comment by LeftHandCold** [comment]
At that time, mo had 2.8 million columns, so loading system tables required a large amount of memory.

**Comment by LeftHandCold** [comment]
<img width="854" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/597e313b-4006-4df3-af31-88aed8e2415d">

**Comment by LeftHandCold** [comment]
The load checkpoint data size is as follows:
table 2: 158M before decompression, 5.4G after decompression
table 3: 880M before decompression, 8G after decompression

**Comment by LeftHandCold** [comment]
fixed

**Comment by YANGGMM** [comment]
<img width="725" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/9c311fca-965f-4236-82a7-b1d7f40adeef">

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/issues/11650

**Comment by LeftHandCold** [comment]
<img width="2433" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/52af5807-21aa-479f-8681-b21c70eb960c">
