### ISSUE TITLE
[Bug]: `internal error: no available CN server` when connecting to MO

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#12219]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-1e94328e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql -h freetier-01.cn-hangzhou.cluster.aliyun-dev.matrixone.tech -P 6001 -u test:admin:accountadmin  -ptest
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): internal error: no available CN server
```

### Expected Behavior

Connect to MO successfully

### Steps to Reproduce

```Markdown
- Configure dedicated CN for one account
- Scale in the dedicated CN to 0
- Connect to MO with the account
```

**Comment by DanielZhangQD** [comment]
From @sukki37 "Today there were frequent cn reboots over a period of time, during which the proxy barely worked, with no problems connecting directly to the cn, and after dozens of minutes, it returned to normal. @volgariver6 @aylei Please locate the root cause, the detailed context is available in the wework chat logs"

**Comment by DanielZhangQD** [comment]
上午又出现了，现象如下：
1. 独享 CN 被缩容了，此时通过 account 去连接 MO 报上述错误
2. 多次尝试连接后，触发 CN 扩容，过了一段时间后，连接正常，即使独享 CN 还没有 Ready
```
➜  kgp -n 034348ea-9dfe-46e7-8f40-18dec1307c98
NAME              READY   STATUS              RESTARTS   AGE
normal-cn-9lxct   0/1     ContainerCreating   0          3m19s
```

**Comment by aylei** [comment]
ref: https://github.com/matrixorigin/MO-Cloud/issues/1505

**Comment by volgariver6** [comment]
pr committed https://github.com/matrixorigin/matrixone/pull/12241

**Comment by volgariver6** [comment]
fixed

**Comment by DanielZhangQD** [comment]
Close this as https://github.com/matrixorigin/MO-Cloud/issues/1505 has been closed
