### ISSUE TITLE
[Bug]: bvt failed. `txn need retry in rc mode`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

on my branch https://github.com/daviszhen/matrixone/tree/1019-fix-moc1444
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/3ce804aa-4ca0-4a91-b60f-ad0a64147807)

https://github.com/matrixorigin/matrixone/actions/runs/6572340937/job/17853281363?pr=12207

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
i am not sure we can reproduce it.
```

### Additional information

occasional failure.

my modification has nothing to do with the transaction

**Comment by gouhongshen** [comment]
similar, but not totally the same:


![image](https://github.com/matrixorigin/matrixone/assets/26336316/40e101bf-a131-4210-a635-582dc8057f28)

<img width="482" alt="截屏2023-10-19 18 14 03" src="https://github.com/matrixorigin/matrixone/assets/26336316/80c32688-2799-4921-a24c-a0ed80df6ed8">

**Comment by daviszhen** [comment]
another bvt failure.

![image](https://github.com/matrixorigin/matrixone/assets/60595215/97ead61b-88a4-4fd7-b391-b0a5d130634c)

https://github.com/matrixorigin/matrixone/actions/runs/6572292365/job/17853152563?pr=12163

**Comment by ouyuanning** [comment]
张旭和莫尘已定位了问题。待确认解决方案

**Comment by ouyuanning** [comment]
小蒋的PR已合并。可以再试一试

**Comment by daviszhen** [comment]
验证中

**Comment by daviszhen** [comment]
今天没有再复现了。

**Comment by sukki37** [comment]
repro: 
https://github.com/matrixorigin/matrixone/actions/runs/6626896674/job/18000733279

<img width="1461" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/4ad96d85-e33c-42b1-b38b-ff0e4c38b214">
[multi-cn-e2e-with-race-linux-x86-reports (1).zip](https://github.com/matrixorigin/matrixone/files/13160626/multi-cn-e2e-with-race-linux-x86-reports.1.zip)

**Comment by sukki37** [comment]
We accept it and leave it to later.    

> repro: https://github.com/matrixorigin/matrixone/actions/runs/6626896674/job/18000733279
> 
> <img alt="image" width="1461" src="https://user-images.githubusercontent.com/77312370/277853025-4ad96d85-e33c-42b1-b38b-ff0e4c38b214.png"> [multi-cn-e2e-with-race-linux-x86-reports (1).zip](https://github.com/matrixorigin/matrixone/files/13160626/multi-cn-e2e-with-race-linux-x86-reports.1.zip)
