### ISSUE TITLE
[Bug]:  SHOW CREATE TABLE information_schema.columns locally is different from ci.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12224]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): f57c1b3616a5a5536eb74ce9ad53f20633f2bbf1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1391" alt="企业微信截图_f2c0cd70-8c28-4079-b5ae-b09a0f203079" src="https://github.com/matrixorigin/matrixone/assets/108530700/27ba2f30-8c31-4d42-a0fc-90ca6992b3d5">

log:[e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13049406/e2e-linux-x86-reports.zip)

### Expected Behavior

<img width="1373" alt="企业微信截图_0729f533-9d29-44f7-99fa-4b25d0450a7d" src="https://github.com/matrixorigin/matrixone/assets/108530700/66d79c48-c310-4662-afcc-a23125085ec7">

### Steps to Reproduce

```Markdown
on ci:
./run.sh n -g test/distributed/cases/dml/show/show.test -m run
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test. @sukki37 @Ariznawlll @daviszhen

**Comment by Ariznawlll** [comment]
verified!
