### ISSUE TITLE
[Tech Request]: add logtail and checkpoint metrics

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12223]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Add logtail and cehckpoint metrics
```

### Why is this needed ?

For observability and alerting

**Comment by gouhongshen** [comment]
tracking in https://github.com/matrixorigin/matrixone/issues/10337

you can close this one @aylei

**Comment by aylei** [comment]
closing as tracked in #10337
