### ISSUE TITLE
[Bug]: bvt ut failed. `TestAppendAndGC`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12229]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

https://github.com/matrixorigin/matrixone/actions/runs/6582646289/job/17884462675?pr=12222
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/77537742-a14d-4392-ab5d-5a1b49eb52e8)

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
not sure we can reproduce it.
```

### Additional information

occasional failure

**Comment by sukki37** [comment]
dup with #11546
