### ISSUE TITLE
[Bug]: Excessive memory usage in DN

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-1e94328e @ 1.0-dev
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 Memory usage dn in cloud dev is too high, memory leaks suspected:

<img width="973" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/e8bdcab5-a4e5-4bb3-8958-f68a6f8964f4">

<img width="1897" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/dac7faba-68ea-4f10-903e-b4c7f0ec61b1">

**Comment by jiangxinmeng1** [comment]
memo.Tree占用了很多内存，应该是因为没有及时做checkpoint，没有清理内存的txn导致的

![image](https://github.com/matrixorigin/matrixone/assets/51114574/fd1191ee-5615-45a0-989e-75b2553b8951)

**Comment by sukki37** [comment]
Part of the problem maybe related to #12225

**Comment by XuPeng-SH** [comment]
same root cause as #12225

**Comment by sukki37** [comment]
> same root cause as #12225

There may still be other issues here. After the upgrade on Saturday, theoretically, the problem #12225 has been resolved. However, looking at the memory usage in the last 12 hours on freetier-01, the memory consumption of dn (data node) remains high at 60GB. 
<img width="946" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/9ce66827-744b-4d00-8d76-b9fca48cb8ad">

For reference, here's another cluster, freetier-02, which was spun up last Friday, and in this cluster, dn's memory usage remains below 10GB.
<img width="941" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/95d1513d-171e-4c22-9bd8-c8e0739206bb">

**Comment by aptend** [comment]
<img width="2453" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/29c880a4-9a73-4372-8349-c5d2f549b561">

memory consumption of dn on freetier-01 was relatively steady and expected over the past 12 hours
