### ISSUE TITLE
[Bug]: mo panic by panic: runtime error: invalid memory address or nil pointer dereference after running stability test for 2 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12264]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1be59d04f86fc812f3e8b32798de75779027bd9f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 after running stability test for about 2 hours, the mo panic by mo panic by panic: runtime error: invalid memory address or nil pointer dereferenc

error log:
{"level":"INFO","time":"2023/10/23 10:15:54.218207 +0800","caller":"disttae/txn_database.go:206","msg":"txnDatabase.Relation table \"sbtest2\"(acc 0 db 272457) in logtail"}
{"level":"ERROR","time":"2023/10/23 10:15:54.218214 +0800","caller":"jobs/flushTableTail.go:191","msg":"[DoneWithErr]","operation":"[13297]FT-280028-mo_increment_columns","error":"open mo-data/shared/.tmp/905899849.tmp: no such file or directory","phase":"1-merge ablocks"}
{"level":"INFO","time":"2023/10/23 10:15:54.218231 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest4\"(acc 0 db 272457) in cache"}
{"level":"WARN","time":"2023/10/23 10:15:54.218240 +0800","caller":"db/task.go:66","msg":"Task[13296] exec error: open mo-data/shared/.tmp/905899849.tmp: no such file or directory"}
{"level":"INFO","time":"2023/10/23 10:15:54.218238 +0800","caller":"disttae/txn_database.go:206","msg":"txnDatabase.Relation table \"sbtest3\"(acc 0 db 272457) in logtail"}
{"level":"INFO","time":"2023/10/23 10:15:54.216716 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest9\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 10:15:54.218263 +0800","caller":"catalog/table.go:437","msg":"[Catalog]","operation":"remove","operand":"[NA-S/17024/1]SEG[182ced40-714a-11ee-8ceb-525400777c3a][C@0-0,D@0-0]"}
{"level":"INFO","time":"2023/10/23 10:15:54.218270 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest4\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 10:15:54.218277 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest3\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 10:15:54.218282 +0800","caller":"catalog/segment.go:472","msg":"[Catalog]","operation":"remove","operand":"[NA]BLK"}
{"level":"INFO","time":"2023/10/23 10:15:54.217220 +0800","caller":"disttae/txn.go:668","msg":"transaction commit: 4f7c1dbc6e5a4ed5b02e53c9287b63f4/Active/S:1698027353744149181-1\n"}
{"level":"INFO","time":"2023/10/23 10:15:54.215893 +0800","caller":"disttae/txn.go:668","msg":"transaction commit: e1882e9d39d04267a0c8995f60c64d04/Active/S:1698027353744149181-1\n"}
{"level":"INFO","time":"2023/10/23 10:15:54.218299 +0800","caller":"disttae/txn.go:668","msg":"transaction commit: c05175c565114a05b19d73e4dbc82402/Active/S:1698027353744149181-1\n"}
{"level":"INFO","time":"2023/10/23 10:15:54.217228 +0800","caller":"disttae/txn.go:668","msg":"transaction commit: a75ddc68619f4ffe9196e9210535f820/Active/S:1698027353744149181-1\n"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x180cd13]

goroutine 808 [running]:
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length(...)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/container/vector/vector.go:113
github.com/matrixorigin/matrixone/pkg/objectio.(*objectWriterV1).addBlock(0xc143766f00, 0xc0d007c480, {0xc141027180, 0x0?, 0x50f}, 0xc143772800, 0xc14376b400)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/objectio/writer.go:520 +0x193
github.com/matrixorigin/matrixone/pkg/objectio.(*objectWriterV1).AddBlock(0xc143766f00, {0xc141027180, 0x50f, 0x50f}, 0xf0?, 0xe8?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/objectio/writer.go:558 +0xd7
github.com/matrixorigin/matrixone/pkg/objectio.(*objectWriterV1).Write(0xc143766f00, 0xc143772800)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/objectio/writer.go:129 +0xa5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.(*BlockWriter).WriteBatch(0xc1444100c0, 0xc143772800)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/blockio/writer.go:74 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*flushBlkTask).Execute(0xc143772200, {0x35de518, 0xc002f410b0})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/tables/jobs/flushblk.go:78 +0x15a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc144400620, {0x35de518, 0xc002f410b0})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:91 +0x88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc001109700, {0x7f4fe1c03478, 0xc143772200})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:210 +0x3d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start.func1()
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:142 +0xc2
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:134 +0xb7

log:
[mo-panic-error.tar.gz](https://github.com/matrixorigin/matrixone/files/13065554/mo-panic-error.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo server on standlone mode 
2. run bvt test loop
3. run tpch_10 test loop
4. run sysbench mixed test 
5. run tpcc 10 warehouse 10 terminal

or
1.run a mo server on standlone mode
2.git https://github.com/matrixorigin/mo-nightly-regression.git
3. ./stb_test.sh -c /bvtcasepath/

only for linux
```

**Comment by aptend** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/12341 & https://github.com/matrixorigin/matrixone/pull/12342

**Comment by aressu1985** [comment]
fixed
