### ISSUE TITLE
[Bug]: mo  panic by runtime error: slice bounds out of range [:189] with capacity 0  after running stability test for 10 hours 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12288]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1be59d04f86fc812f3e8b32798de75779027bd9f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

after running stability test for 10 hours, mo  panic by runtime error: slice bounds out of range [:189] with capacity 0

{"level":"INFO","time":"2023/10/23 19:58:31.576450 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest6\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 19:58:31.576483 +0800","caller":"disttae/txn.go:668","msg":"transaction commit: 0fb013b6ec084829933cc42493e10294/Active/S:1698062311492611494-1\n"}
{"level":"INFO","time":"2023/10/23 19:58:31.576531 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest6\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 19:58:31.576610 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest3\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 19:58:31.576091 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest2\"(acc 0 db 272457) in cache"}
{"level":"INFO","time":"2023/10/23 19:58:31.576396 +0800","caller":"disttae/txn_database.go:135","msg":"txnDatabase.Relation table \"sbtest5\"(acc 0 db 272457) in cache"}
panic: runtime error: slice bounds out of range [:189] with capacity 0

goroutine 877 [running]:
github.com/matrixorigin/matrixone/pkg/container/types.(*Varlena).GetByteSlice(0x45c7b2?, {0x0?, 0x2a121c0?, 0xc0007ef501?})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/container/types/bytes.go:104 +0xb0
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetBytesAt(0xc635ba0a80?, 0xc0683379f9?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/container/vector/vector.go:188 +0x65
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.EncodePrimaryKeyVector(0xc01e861720, 0xc0007ef5c0)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailreplay/encode.go:188 +0xbe5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).HandleRowsInsert(0xc635ba0a20, {0x35de470?, 0xc000665a90?}, 0xc540fd7b30, 0x0, 0xc2637c4a80?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:307 +0x2f3
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.(*PartitionState).HandleLogtailEntry(0xc006dc1d00?, {0x35de470, 0xc000665a90}, 0xc31b287200, 0x366aaa0?, 0x148?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailreplay/partition_state.go:268 +0x116
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeEntry({0x35de470, 0xc000665a90}, 0x366aaa0?, 0xc005722800, 0xc00ab95be8?, 0xc31b287200)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtail.go:39 +0x108
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeLogTailOfPushWithLazyLoad({0x35de470, 0xc000665a90}, 0x543f0?, 0xc00ab95cf0?, 0x175a35b?, 0xc00ab95da8)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:1067 +0x85
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartitionOfPush({0x35de470, 0xc000665a90}, 0xc00ab95e70?, 0xc005722800, 0xc00ab95da8, 0x1)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:1036 +0x2b2
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).consumeSubscribeResponse(0x0?, {0x35de470?, 0xc000665a90?}, 0xffffffffffffffff?, 0x1?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:998 +0xf6
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.cmdToConsumeSub.action({0xc00ab95f78?}, {0x35de470?, 0xc000665a90?}, 0xc005722800, 0xc0042f7b00?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:966 +0x56
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.createRoutineToConsumeLogTails.func1({0x35de470, 0xc000665a90}, 0x0?, 0xc0042f7b00, 0x0?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:927 +0xed
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.createRoutineToConsumeLogTails
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:949 +0x178

[mo-service-panic.tar.gz](https://github.com/matrixorigin/matrixone/files/13071534/mo-service-panic.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo server on standlone mode 
2. run bvt test loop
3. run tpch_10 test loop
4. run sysbench mixed test 
5. run tpcc 10 warehouse 10 terminal

or
1.run a mo server on standlone mode
2.git https://github.com/matrixorigin/mo-nightly-regression.git
3. ./stb_test.sh -c /bvtcasepath/

only for linux
```

**Comment by XuPeng-SH** [comment]
assigned to @jiangxinmeng1

**Comment by jiangxinmeng1** [comment]
正在复现

**Comment by jiangxinmeng1** [comment]
正在复现中

**Comment by jiangxinmeng1** [comment]
还没有复现

**Comment by jiangxinmeng1** [comment]
还没有复现

**Comment by jiangxinmeng1** [comment]
还没有复现

**Comment by jiangxinmeng1** [comment]
还没有复现

**Comment by aressu1985** [comment]
先close，等复现后再重新提
