### ISSUE TITLE
[Feature Request]: Support `convert_tz`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#12285]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
MO does not support `convert_tz`:

mysql> select CONVERT_TZ('2023-10-20 08:04:00.000','+00:00','+8:00');
ERROR 20105 (HY000): not supported: function or operator 'convert_tz'
```

### Describe the feature you'd like

Support `convert_tz`

### Describe implementation you've considered

NA

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
Users may need this function to convert time to different TZs.
```

**Comment by dengn** [comment]
i have tested a django application, this function is also required.

**Comment by YANGGMM** [comment]
这个需求暂时挂在我名下，然后由https://github.com/xmh1011 完成

**Comment by DanielZhangQD** [comment]
Also need to support TZ name:
<img width="681" alt="企业微信截图_ab3494fd-2387-4748-a231-64e274e02385" src="https://github.com/matrixorigin/matrixone/assets/36026334/0ac373bb-9506-4d08-9eca-bec904883cf6">

**Comment by xmh1011** [comment]
> Also need to support TZ name: <img alt="企业微信截图_ab3494fd-2387-4748-a231-64e274e02385" width="681" src="https://user-images.githubusercontent.com/36026334/280667539-0ac373bb-9506-4d08-9eca-bec904883cf6.png">

如果在docker上测试的话，确实会有这个结果。因为convert_tz函数解析时区需要用到go语言内部的库函数，而docker里面应该是没有相应的环境。我记得InfluxDB也有这个问题。

**Comment by DanielZhangQD** [comment]
Just install the tzinfo when building the image:
```
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata
```

**Comment by heni02** [comment]
convert_tz测试覆盖点：
1. convert(..., timezone name, timezone name)，convert(...,timezone, timezone), convert(...,timezone name, timezone),convert(...,timezone, timezone name)
2. convert(null)
3. convert日期后超出时间范围
4. convert无效的参数
5. convert datetime，date，timestamp类型列
6. convert_tz date相关函数(current_timestamp/FROM_UNIXTIME/to_date)

**Comment by heni02** [comment]
test done,目前问题都已解决

**Comment by heni02** [comment]
bug都已解决
