### ISSUE TITLE
[Bug]: standalone performance: delete test performance decrease  25% 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12297]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):854f07a3abb05d76ba45a2ac8a5416b0d7b1fd20
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

date 19 delete 100/500/1000 performance decrease 25%
<img width="1833" alt="企业微信截图_602054ef-4507-41e2-b261-bc48ccd0a9fb" src="https://github.com/matrixorigin/matrixone/assets/113406637/a75c036f-9dc7-42f5-9622-667a659a208a">
delete 100 test found 854f07a3 commit cause decrease，plz @nnsgmsone confirm
<img width="1403" alt="企业微信截图_9cfbcc93-cf87-4922-b455-25caa6a4b574" src="https://github.com/matrixorigin/matrixone/assets/113406637/7d1223ad-37ab-41b3-8bd6-6def43288e50">
<img width="518" alt="企业微信截图_b030989c-912a-4e5b-b794-ae7883017ed6" src="https://github.com/matrixorigin/matrixone/assets/113406637/fd36f4f5-970f-4884-98f3-b7c7afadbf35">

**Comment by heni02** [comment]
和莫尘沟通，这个pr已经修掉了，但截止昨天性能还没恢复，初步怀疑中间时间段有其他pr还会导致下降
<img width="1240" alt="企业微信截图_a70f3321-1dc5-4729-87b2-5072b08ae2e5" src="https://github.com/matrixorigin/matrixone/assets/113406637/19a2bf7c-09a5-4dbe-9f3b-46c4d1944f4c">

**Comment by heni02** [comment]
二分查找 revert掉以上pr和另外一个commit，qps在1万7千多，还不是1万3千多
<img width="1063" alt="企业微信截图_5134bf39-085d-4948-b9f3-ab78a5d626d9" src="https://github.com/matrixorigin/matrixone/assets/113406637/ffcb8d3b-e33b-4499-b3d7-b8f4104e19a9">
19号之后测试两个commit排查怀疑是以下commit导致下降
<img width="1340" alt="企业微信截图_ff3d235a-4a20-400d-8b60-ae3c7e8b46fc" src="https://github.com/matrixorigin/matrixone/assets/113406637/5c34b371-8663-4f5c-9bcc-c216554008aa">

**Comment by heni02** [comment]
@aptend plz confirm

**Comment by heni02** [comment]
修改pkg/vm/engine/tae/common/stats.go:31行 4改成2之后
delete 100并发qps：20482
<img width="519" alt="企业微信截图_1f5a104d-d878-41d6-86fe-300c0c39b9c6" src="https://github.com/matrixorigin/matrixone/assets/113406637/c2594481-4062-44f7-9548-988173fa1390">

**Comment by aptend** [comment]
> 修改pkg/vm/engine/tae/common/stats.go:31行 4改成2之后 delete 100并发qps：20482，回到delete之前的水平

修改的参数表示一次 merge 所包含最大 object 数量。pr 之间默认为2，改成 4 之后 merge 消耗的资源更多，在单机部署时，影响 CN，分布式部署则没有影响。

**Comment by heni02** [comment]
performance recover，closed
![image](https://github.com/matrixorigin/matrixone/assets/113406637/1ab892c4-9dde-4611-830b-cf0abefcad5b)
