### ISSUE TITLE
[Bug]: mo report incorrect when insert into duplicate values in table.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12305]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):75076bf8e524c58822bc1a28c56194e26e47ec1e
- Hardware parameters:
- OS type:
- Others:
```
### Actual Behavior
When insert value into tables and  the primary key column and common column have duplicate values, both primary key column and common column are reported as duplicates. Normally, only the primary key column is reported as duplicates.

job url：https://github.com/matrixorigin/matrixone/actions/runs/6621563960/job/17986677037

<img width="1425" alt="企业微信截图_e9e8478d-0b80-4ba8-9c4b-c941808576c7" src="https://github.com/matrixorigin/matrixone/assets/108530700/39b27035-9def-44be-81d6-2e4a81fefa33">

log：[1-cn-e2e-darwin-arm64-reports (1).zip](https://github.com/matrixorigin/matrixone/files/13111718/1-cn-e2e-darwin-arm64-reports.1.zip)

### Expected Behavior

Only 2 is a duplicate value for a primary key column.

### Steps to Reproduce

```Markdown
merge run test on ci.
```

**Comment by ouyuanning** [comment]
应该是bvt的正则写得不对

**Comment by ouyuanning** [comment]
我们在保存index信息的时候，是将 index 的内容和 primary key作为复合主键保存到隐藏表中。
例子中，col4这个index对应的隐藏表。是以 (col4, col1）作为隐藏表的。
在新增的时候会并行做PK去重，这个隐藏表的去重线程执行比较快，就会这样报错。

**Comment by Ariznawlll** [comment]
verified！
