### ISSUE TITLE
[Bug]: Severe Performance Issues with `logutil`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12318]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0f2305eddcaafb5c348c0ab738757c026aa747b6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Based on the results of a simple test, we have identified severe performance issues in the log module.
- Test Load: Running in a single-node launch mode with 50 concurrent threads and 1 million sysbench transactions.
- Test Groups:
    1. Default Configuration:
        - Logging Level: INFO
        - TPS: 11,000
    2. Logging Level Set to FATAL:
        - Logging Level: FATAL
        - TPS: 20,000
    3. Code Replacement with Go Built-in Log:
        - Using the Go built-in log as a replacement for logutil.
        - Logging Level: INFO
        - TPS: 22,000

Modification in Test Group 3
```
func Debug(msg string, fields ...zap.Field) {                                        
    log.Printf(msg, fields)                                                          
    //GetSkip1Logger().Debug(msg, fields...)                                          
}                                                                                     
                                                                                      
func Info(msg string, fields ...zap.Field) {                                          
    log.Printf(msg, fields)                                                           
    //GetSkip1Logger().Info(msg, fields...)                                           
}    
```

The identified performance issues in the log module are impacting system efficiency, particularly in scenarios with high concurrency.

### Expected Behavior

The performance impact caused by the log module should be investigated and addressed to improve system efficiency.

**Comment by xzxiong** [comment]
my test result:
1. normal case V.S. hard code case:  22549.07 V.S. 22263.92 ( case No.6 V.S. No.8 )
2. newest version has better perf: 37695.08 V.S. 22549.07  ( case No.1 V.S. No.6 )

two diff version:
1. f2e483806,  newest main, remove the log like `transaction commit: ...`
3. 0f2305edd,  issue_12318, this issue origin version

env: macbook pro
testcase:
 - tables: 10
 - rows: 100000
 - case: point_selects
 - threads: 10 ( this diff from this issue )

https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIhPrnjB6BTcirPX8XHF?scode=AJsA6gc3AA8TY0ccyLAW0A-gb6AOI&tab=BB08J2

![image](https://github.com/matrixorigin/matrixone/assets/3927687/0d58c324-93d9-4ee7-bb89-766dcb1645e2)

> ps: normal case is nothing changed
> ps: no_mo_log case is config with `disable-store = true`
> ps: no_log case is config with `disable-store = true` and `disable-log = true`
> ps: `go log` case is hard code as this issue do - use log.Printf.

**Comment by xzxiong** [comment]
update: 新增了些对比测试
![image](https://github.com/matrixorigin/matrixone/assets/3927687/c56ad81d-4a6a-4073-a42d-c8847aea9f10)

**Comment by xzxiong** [comment]
我目前结论是：1）日志打印过量（主要原因）；2）mo 落库和zap fsync 会有一定的次要的性能影响。

分析1）对比 go built-in log
1. 我没测试到 issue中 11,000 V.S. 22,000; 这个结果；（可能是机器环境问题)
2. 我得到的结果: noraml V.S. go log 性能差不过。对比 L6, L28, L29 见 [文档记录](https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIhPrnjB6BTcirPX8XHF?scode=AJsA6gc3AA8TY0ccyLAW0A-gb6AOI&tab=BB08J2) 

分析2）主要是日志打印过多
1. 同版本下，normal 会比 go log 好一些些。例如：No.1 v.s. No.4; No.5 v.s. No.8
2. 主要是日志量的问题，通过对比 No.1 v.s. No.5 
3. 不同 threads的影响：基本无差别。对比 L6，L28, L29 见  [文档记录](https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIhPrnjB6BTcirPX8XHF?scode=AJsA6gc3AA8TY0ccyLAW0A-gb6AOI&tab=BB08J2) 
4. 再次明确日志量的测试，通过对比：L28, L36, L40
![image](https://github.com/matrixorigin/matrixone/assets/3927687/cde6cd24-612b-4272-875e-6ff5950d881a)

**Comment by xzxiong** [comment]
> 我目前结论是：1）日志打印过量（主要原因）；2）mo 落库和zap fsync 会有一定的次要的性能影响。
> 
> 分析1）对比 go built-in log
> 
> 1. 我没测试到 issue中 11,000 V.S. 22,000; 这个结果；（可能是机器环境问题)
> 2. 我得到的结果: noraml V.S. go log 性能差不过。对比 L6, L28, L29 见 [文档记录](https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIhPrnjB6BTcirPX8XHF?scode=AJsA6gc3AA8TY0ccyLAW0A-gb6AOI&tab=BB08J2)
> 
> 分析2）主要是日志打印过多
> 
> 1. 同版本下，normal 会比 go log 好一些些。例如：No.1 v.s. No.4; No.5 v.s. No.8
> 2. 主要是日志量的问题，通过对比 No.1 v.s. No.5
> 3. 不同 threads的影响：基本无差别。对比 L6，L28, L29 见  [文档记录](https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIhPrnjB6BTcirPX8XHF?scode=AJsA6gc3AA8TY0ccyLAW0A-gb6AOI&tab=BB08J2)
> 4. 再次明确日志量的测试，通过对比：L28, L36, L40
>    ![image](https://user-images.githubusercontent.com/3927687/279017965-cde6cd24-612b-4272-875e-6ff5950d881a.png)

@sukki37  ptal

**Comment by xzxiong** [comment]
@sukki37  ptal
