### ISSUE TITLE
[Bug]: UT TestBackupData failed

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#12327]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

UT failed.  https://github.com/matrixorigin/matrixone/actions/runs/6633718883/job/18021939279?pr=12323

**Comment by sukki37** [comment]
dup with #12073
