### ISSUE TITLE
[Bug]: should not push a filter down into limit

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#12325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev d65f651f7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t (i int, j int);
mysql> insert into t select result, result + 1 from generate_series(1, 100) tmpt;
mysql> select * from t order by j desc limit 10;
+------+------+
| i    | j    |
+------+------+
|  100 |  101 |
|   99 |  100 |
|   98 |   99 |
|   97 |   98 |
|   96 |   97 |
|   95 |   96 |
|   94 |   95 |
|   93 |   94 |
|   92 |   93 |
|   91 |   92 |
+------+------+
10 rows in set (0.44 sec)

mysql> select * from (select * from t order by j desc limit 10) tmpt where j % 2 = 0;
+------+------+
| i    | j    |
+------+------+
|   99 |  100 |
|   97 |   98 |
|   95 |   96 |
|   93 |   94 |
|   91 |   92 |
|   89 |   90 |
|   87 |   88 |
|   85 |   86 |
|   83 |   84 |
|   81 |   82 |
+------+------+
10 rows in set (0.68 sec)

### Expected Behavior

In the second select query 
mysql> select * from (select * from t order by j desc limit 10) tmpt where j % 2 = 0;

It really should only return 5 rows, the j % 2 = 0 should filter AFTER limit 10.

**Comment by badboynt1** [comment]
fixed
