### ISSUE TITLE
[Bug]: CN不可用时报错1045密码错误

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#12333]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

登录CN时，报错如下：
Create db connection failed for 80e81acc_1def_45dc_b3b5_2b1696bf37bd:admin:accountadmin: Error 1045 (28000): internal error: no available CN server
报错1045密码错误，实际情况是CN不可用。

### Expected Behavior

报错错误码不是1045，应该是No CN Server相关的。

**Comment by daviszhen** [comment]
修改中

**Comment by daviszhen** [comment]
it was fixed.

**Comment by xiaoshuwei** [comment]
<img width="489" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/b0f90c71-85e7-4592-98d6-e7e2a5b81705">
验证已修改。
