### ISSUE TITLE
[Bug]: the value of vector type can be inserted with null value but can not be updated with null 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12337]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ca137083ea585f925d9ecac8bd7348bd58019428
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql execution:

mysql> drop table t1;
Query OK, 0 rows affected (0.03 sec)

mysql> CREATE TABLE t1 (
    ->     id int,
    ->     b vecf64(3)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> insert into t1 VALUES(1,NULL);
Query OK, 1 row affected (0.03 sec)

mysql> select * from t1;
+------+------+
| id   | b    |
+------+------+
|    1 | NULL |
+------+------+
1 row in set (0.02 sec)

mysql> INSERT INTO t1 (id,b) VALUES (1, '[1,2,3]'), (2, '[4,5,6]'), (3, '[2,1,1]'), (4, '[7,8,9]'), (5, '[0,0,0]'), (6, '[3,1,2]');
Query OK, 6 rows affected (0.02 sec)

**mysql> update t1 set b = NULL;
ERROR 20203 (HY000): invalid argument operator cast, bad value [TEXT VECTOR DOUBLE]**

### Steps to Reproduce

```Markdown
drop table t1;
CREATE TABLE t1 (
    id int,
    b vecf64(3)
);

insert into t1 VALUES(1,NULL);
select * from t1;
INSERT INTO t1 (id,b) VALUES (1, '[1,2,3]'), (2, '[4,5,6]'), (3, '[2,1,1]'), (4, '[7,8,9]'), (5, '[0,0,0]'), (6, '[3,1,2]');
update t1 set b = NULL;
```

**Comment by arjunsk** [comment]
This issue will be fixed once this PR is merged to master: https://github.com/matrixorigin/matrixone/pull/12339

**Comment by arjunsk** [comment]
The bug fix PR is merged on to the master. Please kindly retest and verify.

**Comment by aressu1985** [comment]
fixed
