### ISSUE TITLE
Add the using index type of BSI

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#1234]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

E.g:
create index idx1 using bsi on A (a);

**Comment by lignay** [comment]
So far only parse already supported BSI index, QA could not execute E2E testing, so postpond full testing.
