### ISSUE TITLE
[Tech Request]: Column pruning for DML

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#12358]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
We need to do column pruning for joins which are implicitly spawned by DML.
```

### Why is this needed ?

Currently DML spawned joins don't do column pruning. It causes memory issues, such as matrixorigin/MO-Cloud#1531

**Comment by daviszhen** [comment]
算到内存优化。

**Comment by daviszhen** [comment]
是按照case by case
还是设计整体方案。

**Comment by aunjgr** [comment]
will be covered by #17539
