### ISSUE TITLE
[Bug]: too many connection error messages after restart

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#12356]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 200000+ error messages after restarting

<img width="1419" alt="WeChatWorkScreenshot_305151d4-b932-49f8-bafa-e164c612bdf4" src="https://github.com/matrixorigin/matrixone/assets/39627130/8023d67d-07eb-4a66-8c76-a92590367e1b">

### Steps to Reproduce

```Markdown
Load 100w sysbench data
Restart
```

**Comment by volgariver6** [comment]
pr committed, wait for merge.

**Comment by volgariver6** [comment]
fixed
