### ISSUE TITLE
[Bug]: Slow query

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#12380]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev mo cloud, git version 0931d50bb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The following query could take 5 minutes on freetier-1.    Even if I run it the second time, which I suppose everything is cached.

```
select object_name, sum(case when col_name = 'request_at' then 1 else 0 end) blocks, sum(case when col_name = 'request_at' then rows_cnt else 0 end) xxx, sum(origin_size), sum(compress_size) from metadata_scan('system.statement_info', '*') tmpt group by object_name;
```

**Comment by sukki37** [comment]
https://github.com/matrixorigin/MO-Cloud/issues/1562

**Comment by badboynt1** [comment]
等mocloud环境更新后测试验证

**Comment by fengttt** [comment]
not repro
