### ISSUE TITLE
[Feature]: Prepare and deallocate statement should be aggregated

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#12381]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev mo-cloud 0931d50bb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

prepare and deallocate statement is always logged.    These should be aggregated as well.

And also, execute type statement from different sessions are not aggregated -- should we?     We cannot aggregate across account, but same account of different session, maybe we should.

**Comment by fengttt** [comment]
Please see MOC-1555 on why we should do this.

**Comment by DanielZhangQD** [comment]
@LiSong0214 Please help evaluate this issue. cc @gavinyue

**Comment by aressu1985** [comment]
test done

**Comment by heni02** [comment]
@sukki37 这个还没有开发？

**Comment by heni02** [comment]
挪到2.0.1

**Comment by allengaoo** [comment]
suggest delay to 2.1.0
