### ISSUE TITLE
[Bug]: mo hung on distributed mode during sysbench update/insert test 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12385]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 179582e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6656244610/job/18101031095
<img width="2513" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b76a334d-2ee1-4294-9cea-35274a212e0d">

mo 日志：
http://132.232.112.34:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231026%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

profile of 3 cns:
[profile_hung.tar.gz](https://github.com/matrixorigin/matrixone/files/13184068/profile_hung.tar.gz)

### Steps to Reproduce

```Markdown
Now can not confirm how this repro
```

**Comment by ouyuanning** [comment]
跟莫尘、苏动过了一下。
实际是在建立连接环节hung了。暂时还不确定是网络问题，还是MO无法完成login的问题。
从日志看出问题的时候，3个CN的日志都是空的。

**Comment by aressu1985** [comment]
update on 10.28
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6669097438/job/18137401508

3个CN当中，有一个CN登录不上，都有日志，其中登录不上的CN中，有些异常的LOG：
{"level":"ERROR","time":"2023/10/28 03:48:58.161663 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:49:03.741567 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:50:08.788920 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:51:08.793436 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:51:12.242367 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:52:12.247320 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:52:16.386834 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:56:19.229983 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:56:19.234182 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:56:24.913589 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:57:24.917086 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:57:29.703094 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:58:29.707582 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:58:33.092660 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 03:59:33.096720 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 03:59:36.805940 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 04:00:36.809281 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 04:03:40.314639 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 04:03:40.317273 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 04:03:45.807363 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 04:04:45.811200 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 04:04:51.144130 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 04:05:05.049325 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 04:05:51.147322 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 04:05:54.899459 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 04:06:54.904722 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}
{"level":"ERROR","time":"2023/10/28 04:06:58.136216 +0000","caller":"frontend/resultset.go:298","msg":"error: internal error: column name does not exist. created_time","span":{"trace_id":"0b9f6551-16f0-dc4b-0b28-1dc669793d81","span_id":"fa0d132f139b2338"}}
{"level":"ERROR","time":"2023/10/28 04:07:58.140975 +0000","caller":"fileservice/local_fs.go:391","msg":"error: file fbe07fb0-74dd-11ee-9420-7e3a6f31ab78_00000 is not found"}

**Comment by aressu1985** [comment]
最后一个没问题的commit: b6c645f4d679593ae0686a8ccfa6dfb1ec5ce8a6
第一次出现问题的commit: 179582e8510c1f33977f5992ac0c0e36311d108f
第二次出现问题的commit: 1ab89294f23d8d09e81236bb9febafde03be6ff5

**Comment by ouyuanning** [comment]
还在二分中。

**Comment by nnsgmsone** [comment]
阻塞的goroutine基本上都是right semi join相关的，在尝试把main的所有的semi join替换成right semi后，整个系统会无法启动。。还在定位right semi为啥会导致系统无法启动。。

**Comment by nnsgmsone** [comment]
找到right semi一些可能会导致卡住的地方，接下来会修复这些地方的代码。

**Comment by nnsgmsone** [comment]
pr已经合入，pr修复了一些可能导致的问题。。看是否还会出现

**Comment by nnsgmsone** [comment]
在观察一天

**Comment by nnsgmsone** [comment]
在观察一天。

**Comment by aressu1985** [comment]
fixed
