### ISSUE TITLE
[Bug]: perf of point select of 1.0-dev decrease 50% more than main 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12414]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f46dfc22d4bc57c7cd0c5d45c403c7edca0a5e8d
- Hardware parameters: AWS EC2
  3*CN: 16C 64G
  1*DN:  16C 64G
  3*LOG: 8C  32G
- OS type:
- Others:
```

### Actual Behavior

1.0-dev:
<img width="535" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/95ea517b-b274-44f2-95a9-b9adf684da18">

main:
<img width="390" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/10c6d337-1234-44a4-993b-80a2138547fa">

profile:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13200002/profile.tar.gz)

**Comment by sukki37** [comment]
To add to the stand-alone test results（20c64g）
case             qps
100000/10/main          32766
100000/100/main  35141
1000000/10/main         16363
1000000/100/main    15620


100000/10/dev           19015
100000/100/dev          17791
1000000/10/dev          15884 
1000000/100/dev      16312

**Comment by XuPeng-SH** [comment]
<img width="1399" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/7eaee46e-ed60-4b3b-b999-4267a86f2dc1">

<img width="625" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/c1617d6b-f0e5-4df9-8f5e-195df69b3027">

**Comment by XuPeng-SH** [comment]
assigned to @daviszhen

**Comment by daviszhen** [comment]
it was fixed.

**Comment by aressu1985** [comment]
fixed
