### ISSUE TITLE
[Bug]: `stream closed` error is returned when querying statement_info table

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#12435]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-9be61237
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [(none)]> SELECT statement_id, status, COUNT(*) as count
    -> FROM system.statement_info
    -> GROUP BY statement_id, status
    -> HAVING COUNT(*) > 1;
ERROR 20503 (HY000): stream closed
```

### Expected Behavior

The query succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

The CN restarts with the above query:
```
NAME                             READY   STATUS    RESTARTS       AGE
default-cn-84rlh                 1/1     Running   11 (78s ago)   3d16h
default-cn-jkc89                 1/1     Running   1 (36s ago)    11h
```

**Comment by nnsgmsone** [comment]
这个或许不应该查stream closed的原因。。因为cn之间连接断开。目前的报错就是这个。。这里可能应该看另外一个cn为啥会刮掉。。。

**Comment by DanielZhangQD** [comment]
> 这个或许不应该查stream closed的原因。。因为cn之间连接断开。目前的报错就是这个。。这里可能应该看另外一个cn为啥会刮掉。。。

另外一个不用看，因为跑了两次，每次在一个 CN 上，是不应该看下，这种 Query 能否做到不让 CN 挂掉。
From @fengttt "The plan is simply wrong/bad"

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
SELECT statement_id, status, COUNT(*) as count FROM system.statement_info GROUP BY statement_id, status HAVING COUNT(*) > 1;

**Comment by daviszhen** [comment]
实际是oom。
<img width="1494" alt="企业微信截图_4a3e015e-7a23-483d-8409-c0902989afe4" src="https://github.com/matrixorigin/matrixone/assets/60595215/989622b8-8270-4496-8e1c-6e7a375569a5">

<img width="1289" alt="企业微信截图_c19d3110-4120-4275-b3ae-ecd7f24f5f8f" src="https://github.com/matrixorigin/matrixone/assets/60595215/0aff63c1-a100-4c75-aa82-7d8fdd0f1f35">

<img width="931" alt="企业微信截图_afc7027b-a02e-4288-99da-3211ab380dd6" src="https://github.com/matrixorigin/matrixone/assets/60595215/6264a24a-527a-46dd-8cae-0e7a553dbd60">

<img width="1322" alt="企业微信截图_3d038aaa-1c80-425d-a44f-18576bc26ed5" src="https://github.com/matrixorigin/matrixone/assets/60595215/076f41fe-0f8b-496b-84b2-619f4dfe8d7f">

**Comment by daviszhen** [comment]
@badboynt1 oom了，辛苦看下。

**Comment by fengttt** [comment]
We cannot run this query at this moment.    We need to control hash table size.
1. Hash agg/join should have a hash table size, 
2. If out of budget, it should spill
3. Even if we don't spill now, we should gracefully exist, not OOM and bring down the CN -- please triage if we need to do something here before we have spill.

**Comment by zengyan1** [comment]
正在看

**Comment by zengyan1** [comment]
修复中

**Comment by heni02** [comment]
main回归sysbench测试最近频繁出现这个问题
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7438849318/job/20246218270
<img width="1435" alt="企业微信截图_e74c25c1-51b8-4c09-bae5-1dad04bbc1d9" src="https://github.com/matrixorigin/matrixone/assets/113406637/869001da-385e-4cb4-868b-563c29941474">

mo log：
http://175.178.192.213:30088/explore?panes=%7B%22Sty%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240107%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704689220000%22,%22to%22:%221704689352000%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1359" alt="企业微信截图_2692f443-221e-48b4-aa64-11aa4c9b814b" src="https://github.com/matrixorigin/matrixone/assets/113406637/cf3141d2-a4e4-4153-8794-3eb41962dd58">

**Comment by Ariznawlll** [comment]
**[0109] tke main 回归出现(load tpch 100g)：**
**commit id**：335ccceb5c2c4fc036399097303f141014c0250b
**job**：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448861080/job/20264149351
<img width="1344" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0ae4d85a-0534-499f-aa09-0d50bac44bac">

**mo-log:**
<img width="1343" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/746fda23-edf2-4ebd-91b5-4f11730cb7b4">
http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240108%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1


**最近这个问题出现比较频繁，改成s-1跟踪.**

**Comment by zengyan1** [comment]
<img width="552" alt="企业微信20240115-124759@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/2c1ebcc5-afbe-450e-ba0a-0d9d9719f9ca">
等待pr合入

**Comment by zengyan1** [comment]
继续观察中，目前暂未复现

**Comment by zengyan1** [comment]
未复现

**Comment by zengyan1** [comment]
未复现

**Comment by DanielZhangQD** [comment]
Cloud Dev 环境稳定复现，会导致 CN OOM：
```
MySQL [system_metrics]> SELECT statement_id, status, COUNT(*) as count      FROM system.statement_info      GROUP BY statement_id, status      HAVING COUNT(*) > 1;
Connection id:    129312394
Current database: system_metrics

ERROR 20503 (HY000): stream closed
```

```
default-cn-4cm7t                       0/1     OOMKilled   2 (78s ago)     25h
```

**Comment by DanielZhangQD** [comment]
`stream closed` 是由 CN OOM 导致的，在 https://github.com/matrixorigin/matrixone/issues/14398 跟踪
