### ISSUE TITLE
[Tech Request]: Support adding default value for [logservice.BootstrapConfig.restore] from conf log.toml in MO standalone env

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#12437]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [ ] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Support adding default value for [logservice.BootstrapConfig.restore] from conf log.toml, for example:
[logservice.BootstrapConfig.restore]
file-path = "hk_data"
```

### Why is this needed ?

Background: currently to restore mo-data in a standalone mo env using mo_br tool, we need to add conf [logservice.BootstrapConfig.restore] in conf file log.toml first before restarting mo after it is restored. However, when next time mo-service needs to be restarted, we need to remove this conf again. So this is causing inconsistency problems for operations. So a better way to avoid this, is to add the default value of conf [logservice.BootstrapConfig.restore], for example, file-path = "hk_data", and logservice will need to judge whether this file exists in the mo-data folder. If yes, read the meta data from it and start mo-service, otherwise just ignore it. 

PS: The above illustration is for mo standalone. As for mo cluster, we need further discussion.

### Additional information

https://github.com/matrixorigin/mo-backup

**Comment by aronchanisme** [comment]
For mo cluster, operator will set the conf and pass it to mo before starting the cluster. Hence, there's no need to worry about the default value in mo cluster, i.e. the same default value setting in a standalone will do.

**Comment by volgariver6** [comment]
pr is committed

**Comment by volgariver6** [comment]
merged  to main

**Comment by aronchanisme** [comment]
Test commit id:
```bash
root@test0:/data/mo_br_test/mo_br/mo-backup# mo_ctl get_cid
2023-11-22 16:39:00.057 UTC+0800    [INFO]    Try get mo commit id
commit c0094a9393054a34dd8471ef8f52da5b2b9c7d42
Author:
Date:   Wed Nov 22 15:40:27 2023 +0800

    rm unused codes (#12879)
    
2023-11-22 16:39:00.122 UTC+0800    [INFO]    Get commit id succeeded

```


1. Now no extra configuration modification is needed after a restore is performed.
2. MO can be restarted normally
3. MO backups can be craeted normally by mo_br from an MO instance whose data is restored from backup.

Please see more details on test records(chapter 6.备份还原测试（20231122）)
https://doc.weixin.qq.com/doc/w3_AfsAgAbcAMItX9eKVMJRnuYIfOPg8?scode=AJsA6gc3AA8YzDW1dxAfsAgAbcAMI
