### ISSUE TITLE
[Bug]: s3 token invalid

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#12445]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

FATAL jTPCCTerminal:235 - [UNEXPECTED][STOCK_LEVEL][EXECUTION] ErrorCode : 1105, ErrorMessage : oss: service returned error: StatusCode=403, ErrorCode=InvalidSecurityToken, ErrorMessage="The security token you provided is invalid.", RequestId=6540C534131B183033191E8A, Ec=0002-00000006

### Steps to Reproduce

```Markdown
Aliyun, run tpcc with 30 cns in long time.
```

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
fix merged: https://github.com/matrixorigin/matrixone/commit/873bae8551cf047ac94f95fd054b83fcee0099f5

I'll take another look if occur again.

**Comment by reusee** [comment]
observing.

**Comment by reusee** [comment]
observing

**Comment by reusee** [comment]
fix merged
