### ISSUE TITLE
[Bug]: create unique index success, can't see the key info in desc stmt but in show create table stmt

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12450]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="811" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/4d79ebbe-d5de-48aa-afbc-d274380a3c6e">
<img width="714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/f40a812f-3d9f-48ea-9e6b-42225d38c165">
<img width="909" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/7e9f39b7-2b4b-46b8-b1e6-5f2f0a326660">

**Comment by xmh1011** [comment]
如果新建unique key，未设置unique key的名称，此时unique key默认与列名相同，所以desc可以正常显示。但是如果设置unique key名称，并且名称与列名不符合，desc不可以正常显示。
