### ISSUE TITLE
[Bug]: mysql protocol performance issue

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#12476]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The following query, when execute, returns 4197 rows, took 4min.   When use it to insert into select, ... only 1 second.

```
4197 rows in set (4 min 58.85 sec)

mysql> create table mobug.dups (statement_id varchar(50), node_uuid varchar(50), request_at timestamp, cnt int);
Query OK, 0 rows affected (0.80 sec)

mysql> insert into mobug.dups select statement_id, node_uuid, request_at, count(*) cnt from system.statement_info where request_at > '2023-11-01 11:00:00' and request_at < '2023-11-
Query OK, 4197 rows affected (1.04 sec)

mysql> select statement_id, node_uuid, request_at, count(*) cnt from system.statement_info where request_at > '2023-11-01 11:00:00' and request_at < '2023-11-01 11:30:00' group by statement_id, node_uuid, request_at having count(*) > 1;
```

**Comment by daviszhen** [comment]
@volgariver6  帮忙看下

**Comment by daviszhen** [comment]
类似https://github.com/matrixorigin/MO-Cloud/issues/1541

**Comment by fengttt** [comment]
All the select queries are exactly the same,

select statement_id, node_uuid, request_at, count(*) cnt from system.statement_info where request_at > '2023-11-01 11:00:00' and request_at < '2023-11-01 11:30:00' group by statement_id, node_uuid, request_at having count(*) > 1;

**Comment by volgariver6** [comment]
<img width="1918" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/266ec73f-642c-4452-81e1-3c97fcaf1915">

直接 select hui会多一个shuffle，应该会更快，但是从结果上看，变慢了。

**Comment by volgariver6** [comment]
select 查询显示的时间把server发送到client网络传输的时间也算在内，所以在网络条件不好或者跨区域连接server的时候，select查询的时间会比较长；而insert into select 没有传输结果集的时间，所以很快：

<img width="1919" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/8271b735-a4c0-4438-8b85-d6455f668b41">

OutputSize越大，select的时间越长。这个是正常的。@fengttt
