### ISSUE TITLE
[Bug]: dn oom crash and restart all the times in benchmark tpcc regression on tke distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12483]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b3da04e
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6721576013/job/18267779089

during TPCC test, the DN was out of memory.
<img width="1407" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e59742c1-6c64-41f8-852a-3aaa45a77cd2">

<img width="1426" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/4f5e9a4f-bd95-4ab2-98f1-fa9e16bb9b3f">

mo-log:
http://132.232.112.34:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231101%5C%22,%20job%3D%5C%22mo-nightly-regression-20231101%2Fnightly-regression-dis-dn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

**Comment by aressu1985** [comment]
update mem heap:
[heap.tar.gz](https://github.com/matrixorigin/matrixone/files/13234228/heap.tar.gz)

没有任何负载，DN重启后，内存不停的增加，而且速度挺快，当到50%以上的时候，基本上瞬间就OOM了

**Comment by gouhongshen** [comment]
daily (TKE) 环境和 EKS 环境均未能复现

**Comment by gouhongshen** [comment]
daily 又出现了：http://132.232.112.34:30088/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231102%5C%22,%20pod%3D%5C%22nightly-regression-dis-dn-0%5C%22%7D%20%7C~%20%60HeapInuse%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221698962400000%22,%22to%22:%221698966000000%22%7D%7D

**Comment by gouhongshen** [comment]
tpcc 100w * 10t, 100w * 100t 混合：

![image](https://github.com/matrixorigin/matrixone/assets/26336316/21b0cca5-581f-4889-92c0-301c060a0dd2)


![image](https://github.com/matrixorigin/matrixone/assets/26336316/2753a523-98a8-42c3-bc46-4103872a42ad)

**Comment by aressu1985** [comment]
update on 11.06:
job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6762159226/job/18381793540
dn profile:
[dn_oom_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13261295/dn_oom_profile.tar.gz)

**Comment by XuPeng-SH** [comment]
It should be related to the refactoring of show accounts. Right now, it will load all checkpoints into the memory when creating a new global checkpoint.

<img width="1656" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/28e4e880-b667-4a54-bf3f-da5a5f40265c">

DN oom at about 22:25.

<img width="1479" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/af742ebc-347f-495a-82eb-bb5ed1249a2c">

DN was building a new global checkpoint at that time.

It didn't load checkpoints when building a new global checkpoint before the show accounts refactor.

**Comment by gouhongshen** [comment]
#12524 merged, no oom happened yesterday:

<img width="1821" alt="截屏2023-11-07 09 47 30" src="https://github.com/matrixorigin/matrixone/assets/26336316/9e4ca234-56f6-4d81-b70a-cf5dc628009b">

**Comment by aressu1985** [comment]
update on 1108:
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6780253645/job/18445829758

<img width="1367" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/fa12d51f-9f05-4308-888f-f19305cfaaf8">


profile:
[Uploading dn_oom_profile_1108.tar.gz…]()

**Comment by gouhongshen** [comment]
可能是做 ckp 时 load 太多数据，目前正在修

**Comment by gouhongshen** [comment]
正在引入 object info 优化，减少 load 内存的消耗

**Comment by XuPeng-SH** [comment]
连续两天daily dn没有oom. http://132.232.112.34:30088/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&refresh=10s&from=now-12h&to=now&var-datasource=default&var-cluster=&var-namespace=mo-nightly-regression-20231114&var-pod=nightly-regression-dis-dn-0

**Comment by XuPeng-SH** [comment]
今天daily内存正常

**Comment by aressu1985** [comment]
fixed
