### ISSUE TITLE
[Bug]: write rawlog with db_holder.go got Error `packet for query is too large.`

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#12489]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main 7ca9a35
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

log file:
[ETLMerge.h1000.log](https://github.com/matrixorigin/matrixone/files/13236532/ETLMerge.h1000.log)

- error info
```
{"level":"ERROR","time":"2023/11/02 03:35:13.399531 +0800","name":"log-service.ETLMerge","caller":"export/merge.go:393","msg":"failed to upload file to MO","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","table":"system.rawlog","path":"sys/logs/2023/11/02/rawlog/1698866704_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_130285749.csv","error":"packet for query is too large. Try adjusting the `Config.MaxAllowedPacket`","span":{"trace_id":"f69a6344-c06e-fa5c-6fd8-603899698bee","span_id":"e6033f01f6063e17"}}
```

- target csv files.
[1698866704_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_130285749.csv.tgz](https://github.com/matrixorigin/matrixone/files/13236535/1698866704_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_130285749.csv.tgz)

> file size: 20MiB
<img width="1607" alt="image" src="https://github.com/matrixorigin/matrixone/assets/3927687/a04ab3fd-8457-46c1-a995-c577049908ff">

suggestion:
- set the max_allowed_packet = 30MiB in db connet DSN

**Comment by gavinyue** [comment]
maxAllowedPacket=0
在建立链接的时候已经设置了 maxAllowedPacket 为unlimited. 
遇到这种情况只能是server端没有honor这个协议。

**Comment by gavinyue** [comment]
只能想想办法再load里 分拆了

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/12682

**Comment by gavinyue** [comment]
这个是因为MO 的server side default max_allowed_packet是16mb. 

client端怎么设置， 都会以server端为准， 所以需要再server修改。

我提了一个PR来提高server side defautl setting  to 64mb 

但是这个问题也可以通过在server端修改配置来解决。

**Comment by xzxiong** [comment]
@gavinyue 现在只能通过修改默认值，解决么？
这个参数本身就应该是 session的 variable；另外，也应该支持在go SDK中DSN中指定。

**Comment by gavinyue** [comment]
不是，这个pr只是让Mo的默认值和现在MySQL 的默认值已经gosql client的默认值保持一致。 

可以在server 端修改这个值，但是需要功过跑一个sql. 

另外client端的设定本来默认就是64mb, 但是client端的设置是不影响server的设置的, 最终以server端的设置为准。

**Comment by xzxiong** [comment]
checked
