### ISSUE TITLE
[Subtask]: Remove the reference count from the batch and use the copy method to pass batches between pipelines

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#12505]
### Parent Issue

#10729

### Detail of Subtask

Remove the reference count from the batch and use the copy method to pass batches between pipelines

**Comment by florashi181** [comment]
与内存相关 https://github.com/matrixorigin/matrixone/issues/12505

**Comment by ouyuanning** [comment]
等agg和hash table从batch移除后处理
