### ISSUE TITLE
[Subtask]: remove hash table from batch. make it an attribute of  the operator

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#12503]
### Parent Issue

#10729

### Detail of Subtask

remove hash table from batch. make it an attribute of  the operator.

**Comment by aunjgr** [comment]
Need further design

**Comment by badboynt1** [comment]
作为pipeline重构的子任务，会先做这个

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/17666  已经在这个pr中实现
