### ISSUE TITLE
[Performance]: Apply indices to accelerate particular queries

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#12517]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

Since unique/secondary indices has been implemented, we can use them to accelerate some slow queries.

### Additional information

It can be verified by matrixorigin/MO-Cloud#218, https://github.com/matrixorigin/MO-Cloud/issues/1707

**Comment by florashi181** [comment]
in v1.2, we would test these accelerate scenarios:
1. Check equivalent points
2. Random point Query (in)
3. Range query (between and)
4, non-equivalent query (<,>)
