### ISSUE TITLE
[Bug]: convert_tz (null...) reported error message, but other database results return null

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12514]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8defd1f6832280bf57b49425013752a7415436a2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql:
select convert_tz(NULL,'-05:00', '+05:30') as dtime;
select convert_tz('2023-11-06 10:28:00',NULL, '+08:00') as dtime;
select convert_tz('2023-11-06 10:28:00','+00:00', NULL) as dtime;
mo:
<img width="940" alt="企业微信截图_a0032bc5-f2d5-405e-9b1d-c37cd1b59dce" src="https://github.com/matrixorigin/matrixone/assets/113406637/867d117e-5717-4e2e-bf7f-3e1e979f2b01">

mysql:
<img width="921" alt="企业微信截图_ce10c56a-169b-4edb-9970-8986a0a46b2d" src="https://github.com/matrixorigin/matrixone/assets/113406637/2e676ee9-2266-4413-abc0-9072a4a25848">

**Comment by xmh1011** [comment]
这个issue在所有date类函数的datetime格式错误的时候都会发生，issue #12609 和这个也有关。可以讨论下是否有必要一起修正。

**Comment by heni02** [comment]
bvt case已通过，closed
