### ISSUE TITLE
[Bug]: mo does not support parsing of datetime types at the non-second level

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12530]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="942" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/bba3a834-6ddd-411b-a2d5-d9649c52dc60">

**Comment by xmh1011** [comment]
I'll try to fix it.

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/matrixone/pull/12527

**Comment by xmh1011** [comment]
fixed.
