### ISSUE TITLE
[Bug]: ut test TestReadCheckpoint fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12539]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="567" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/832e55f8-e02f-4149-bdbd-d9b46d2e9920">
fail link：https://github.com/matrixorigin/matrixone/actions/runs/6779699548/job/18427164169?pr=12527

**Comment by XuPeng-SH** [comment]
assigned to @LeftHandCold

**Comment by LeftHandCold** [comment]
未复现

**Comment by LeftHandCold** [comment]
未复现

**Comment by LeftHandCold** [comment]
未复现

**Comment by LeftHandCold** [comment]
未复现

**Comment by LeftHandCold** [comment]
并没有复现
