### ISSUE TITLE
[Bug]: bvt failed, case mo_cloud 

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#12535]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1ed7f07af
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

all query in mo-cloud op set, aim to check all query is ok. 
<img width="1389" alt="企业微信截图_f725520f-6d40-4e6a-b7a8-368c66ae9a58" src="https://github.com/matrixorigin/matrixone/assets/3927687/d72aed7f-8610-4329-b32d-771d1c575766">

- target query
```
SELECT collecttime FROM `system_metrics`.`server_storage_usage` WHERE account != 'sys' and account != 'ob' ORDER BY collecttime asc LIMIT 1;
```

**Comment by xzxiong** [comment]
背景
- 检查MO能正常覆盖cloud上需要的SQL查询

问题分析
- Q: 为什么之前能正常运行？
A: 因为 采集 server_storage_usage 指标的逻辑进行的修复，解决了对新租户采集报错的问题，所以现在采集指标更高效，详见：https://github.com/matrixorigin/matrixone/issues/12458

- Q: 需要怎么修改 ？
A: collecttime字段为采集时间，不应该作为bvt的结果验证。
    - 建议：删掉该case，因为mo_cloud已经有覆盖server_storage_usage相关的查询；

**Comment by tianyahui-python** [comment]
https://github.com/matrixorigin/matrixone/pull/12540

**Comment by tianyahui-python** [comment]
pr link: https://github.com/matrixorigin/matrixone/issues/12535

**Comment by xzxiong** [comment]
checked.
