### ISSUE TITLE
[Bug]: ut test TestWatchDirty fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12533]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="505" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/2f6481cf-de37-4ebf-b42a-0b2a729cad43">

fail link：https://github.com/matrixorigin/matrixone/actions/runs/6779300140/job/18426144240?pr=12527

**Comment by aptend** [comment]
fix pr #12709
