### ISSUE TITLE
[Bug]:  the result of time window 'count(column)' is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12549]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8defd1f6832280bf57b49425013752a7415436a2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1351" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/36b841a7-9525-4c68-9dc0-9c4624db3fb1">

### Expected Behavior

the count from '2014-01-01 00:10:00' to '2014-01-01 00:20:00' should be 9.

[time_window.csv](https://github.com/matrixorigin/matrixone/files/13277579/time_window.csv)

### Steps to Reproduce

```Markdown
drop table if exists external01;
create external table external01(ts timestamp primary key,col1 tinyint default null,col2 smallint default null,col3 int default null,col4 bigint default null,col5 tinyint unsigned default null,col6 smallint unsigned default null,col7 int unsigned default null,col8 bigint unsigned default null,col9 float default null,col10 double default null)infile{"filepath"='path/time_window.csv'} fields terminated by ',' enclosed by '\"' lines terminated by '\n';


select _wstart, _wend, count(col2), sum(col6), avg(col7) from external01 where ts >= '2014-01-01 00:01:17' and ts <= '2014-01-01 00:14:58' interval(ts, 10, minute) sliding(5,minute);
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
结果应该是对的，先过滤，后做窗口计算。
<img width="2299" alt="截屏2023-11-29 17 19 53" src="https://github.com/matrixorigin/matrixone/assets/49111204/891a09b8-9df9-4a00-8d00-03780920890c">

**Comment by Ariznawlll** [comment]
The result is correct, verified!
