### ISSUE TITLE
[Bug]: privilege violation

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12551]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:


  The golang version used to build this binary: go version go1.20.5 linux/amd64
  Git branch name: 1.0-dev
  Git commit ID: aafcfae19
  Buildtime: 1698800681
  Version: v1.0.0-rc2

```

### Actual Behavior

<img width="933" alt="企业微信截图_4978fe40-8425-4596-92cf-f9522a4c2bdc" src="https://github.com/matrixorigin/matrixone/assets/60595215/65046665-4042-465c-9e08-0f4e3fd3dba8">

### Expected Behavior

we can not operate the tables in mo_catalog except the cluster table.

**Comment by aressu1985** [comment]
@daviszhen 这个issue时候不是可以关闭了？

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/54f329c8-60cf-43e8-b21d-c181b657c7d0)

it was fixed.
