### ISSUE TITLE
[Bug]: ut test TestRunDaemonTask fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12552]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="525" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/07619f9f-e5c3-4fce-a5a8-d1a7e03e8d51">

fail link:https://github.com/YANGGMM/matrixone/actions/runs/6782621198/job/18435206608?pr=121

**Comment by xzxiong** [comment]
found again, wait pr merged
https://github.com/matrixorigin/matrixone/actions/runs/7013941108/job/19080876446

**Comment by volgariver6** [comment]
pr committed

**Comment by volgariver6** [comment]
fixed
