### ISSUE TITLE
[Bug]: CN used excessive cache space and panic on startup

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12578]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev
https://github.com/matrixorigin/matrixone/commit/d17a04928bd4486a3772eeb7bd55781b8c4ef3ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN used excessive cache space:

<img width="1902" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18556593/95291af9-b181-4fb7-a01b-0d730b0742d9">

The configured cache space is 270GiB, usage is 294GiB:

```
   [fileservice.cache]
    disk-capacity = "270GiB"
    disk-path = "/var/lib/matrixone/disk-cache"
    memory-capacity = "1GiB"
```

Looks like cache space used up won't cause CN panic, but CN will write an empty file to mark that system init has been completed in `LOCAL` fileservice, which use the same volume with cache and the failure of writing caused CN panic

```
panic: write /var/lib/matrixone/data/.tmp/1249353953.tmp: no space left on device
```

### Expected Behavior

CN should not use excessive cache space

**Comment by reusee** [comment]
pr sent

**Comment by reusee** [comment]
fixed, re-assigning

**Comment by aylei** [comment]
observing
