### ISSUE TITLE
[Bug]: ut test TestTickerForTaskSchedule fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12575]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="575" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/5259bc28-dfda-4b5d-91cc-446f3070e098">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/6793533146/job/18468526538?pr=12573

**Comment by volgariver6** [comment]
fixed

**Comment by XuPeng-SH** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/6850993094/job/18626343718?pr=12715

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
日志看不到了，先关掉吧，等下次再遇到的时候再处理
