### ISSUE TITLE
[Bug]: convert_tz DST result is different from mysql

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12593]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3954d1705f4f5301fcccb55583c17d1c5f513709
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql:
select convert_tz('2007-03-11 02:00:00','US/Eastern','US/Central')as dtime;
<img width="972" alt="企业微信截图_33d7791e-af8b-4620-9eb7-81573b46dd5e" src="https://github.com/matrixorigin/matrixone/assets/113406637/423d5de8-1f6c-4b0c-9abd-97e49fede668">
<img width="1005" alt="企业微信截图_5d3cef81-5321-4dd9-9e58-262e6495f9dd" src="https://github.com/matrixorigin/matrixone/assets/113406637/12a4e528-a386-455a-b67a-881c0cdaf5a7">

查询了下2007-03-11 02:00:00属于美国夏令时时间
![wecom-temp-56847-2c156aaef9923eed422a38d7f07b83d5](https://github.com/matrixorigin/matrixone/assets/113406637/5e930ea1-6c4d-4e5b-81b8-268621724461)

但试了冬令时，mo和mysql 结果一样
select convert_tz('2023-11-05 10:00:00','US/Eastern','US/Central')as dtime;
<img width="937" alt="企业微信截图_0eba825e-130d-4be4-a663-80892dfc1313" src="https://github.com/matrixorigin/matrixone/assets/113406637/840fad48-a5c6-41d7-8a7a-72d1bf0bca48">

**Comment by xmh1011** [comment]
<img width="1256" alt="image" src="https://github.com/matrixorigin/matrixone/assets/88817514/d92cff8b-9e86-48e1-94f4-e2fa3fa75dcb">
应该是冬令时时区更改问题。

**Comment by YANGGMM** [comment]
not a bug

**Comment by heni02** [comment]
confirm，closed

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
