### ISSUE TITLE
[Bug]: 执行SQL每次结果不一致

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#12592]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d17a04928bd4486a3772eeb7bd55781b8c4ef3ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

执行SQL如下：
```
select * from system.statement_info order by response_at desc limit 30;
```
每次结果不一致，依次如下：
<img width="1499" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/44eff8bb-4704-4345-a83d-5ef1bb4cff9e">
<img width="1487" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/594a1655-7f5d-4b71-84d3-ba9eb5b0def6">
<img width="1498" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/ec3e6b1b-109b-4bfa-b189-65bdf269335e">

### Expected Behavior

每次查询结果一致。

### Steps to Reproduce

```Markdown
as Actual
```

### Additional information

使用目前MOCloud使用的环境查询。

**Comment by xiaoshuwei** [comment]
same as https://github.com/matrixorigin/matrixone/issues/12564

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/c179b927-5ec8-4df4-9575-d68efa6540d2)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/368c39b5-20e8-489a-a606-10e15227fdac)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/77f0da21-cc23-48a7-8ce7-002cda3f53b3)
