### ISSUE TITLE
[Bug]: MO执行SQL失败，报错Error 1045 (28000): Auth failed: info: source address 103.156.184.210 is not authorized

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#12595]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d17a04928bd4486a3772eeb7bd55781b8c4ef3ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023/11/08 11:10:20.774698 +0000 ERROR user/user.go:75 trace {"error": "Error 1045 (28000): Auth failed: info: source address 103.156.184.210 is not authorized", "elapsed": "2.308604ms", "rows": -1, "sql": "/* cloud_nonuser */ select current_role() as rolename;"}
如上Log：在执行/* cloud_nonuser */ select current_role() as rolename;时报错Error 1045 (28000): Auth failed: info: source address 103.156.184.210 is not authorized。

### Expected Behavior

正常执行

### Steps to Reproduce

```Markdown
偶现，有时会成功。
```

**Comment by DanielZhangQD** [comment]
应该是 VPN 的问题，需要关掉 VPN 测试

**Comment by xiaoshuwei** [comment]
VPN问题，关掉了
