### ISSUE TITLE
[Tech Request]: Strategies for encountering swipes during transaction conflict detection

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#12613]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

在多session load时，就有概率遇到这个问题，具体的原因是存储刷盘后，cn如果不读取对应的s3文件无法确定是否发生冲突，当前的策略是直接重试。

### Describe the feature you'd like

探讨在存储刷盘后应该如何处理的问题，设计方案然后解决

**Comment by triump2020** [comment]
需要修改PrimaryKeysMayBeModified() 函数，1. 先检测partiiton state 中的 primay key index , pks 如果在[start, end] 之间发生变化, 返回true; 2. 如果这些pks 在 S3上，需要调用rangesBetween(pks,start, end), 通过zm 筛选blk, 再读取数据验证pk 是否修改.

**Comment by triump2020** [comment]
@nnsgmsone   Pls close it !
