### ISSUE TITLE
[Bug]: 执行导入时报错ERROR 20101 (HY000): internal error: panic runtime error: index out of range [9] with length 9

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixone#12617]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version: v1.0.0-RC2 & nightly-9be61237（MOC）
```

### Actual Behavior

参考MO Cloud文档导入示例：
https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/App-Develop/import-data/bulk-load/load-jsonline/#_2

执行建表语句成功：
```sql
create table t2(col1 bool,col2 int,col3 varchar, col4 date,col5 datetime,col6 timestamp,col7 decimal,col8 float);
```

执行导入语句失败：
```sql
load data local infile {'filepath'='$filepath/jsonline_array.jl','format'='jsonline','jsondata'='array'} into table t2;
```

完整报错：
```sql
mysql> load data local infile {'filepath'='/opt/jsonline_array.jl','format'='jsonline','jsondata'='array'} into table t2;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [9] with length 9: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.transJsonArray2Lines
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:834
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.transJson2Lines
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:751
github.com/matrixorigin/matrixone/pkg/sql/colexec/e
```

**Comment by WuMenglong** [comment]
> @WuMenglong jsonline_array.jl 文件的内容，不知道可否贴一下。
> 
> 因为我看文档里，给的是jsonline_object.jl 的内容。好像没有看到 jsonline_array.jl
> 
> 如果是 jsonline_object.jl 的内容的话，那么 jsondata 的值需要设置为 'object'

@ouyuanning 非常抱歉，所贴链接中的文档被我同步提交PR删除了会触发异常的示例，您可以使用MO内核文档中的示例来复现，地址如下：https://docs.matrixorigin.cn/1.0.0-rc2/MatrixOne/Develop/import-data/bulk-load/load-jsonline/#_2

**Comment by Morranto** [comment]
还没看，可能跟格式不对有关

**Comment by Morranto** [comment]
not working on it

**Comment by Morranto** [comment]
正在处理

**Comment by Morranto** [comment]
这个t2 有8列，json_array里的数据有12列，所以越界了，我的pr加了一个越界检查，同时需要清楚json_array里的数据是不能够正常导入t2里的，暂不明确 load data local infile {'filepath'='$filepath/jsonline_array.jl','format'='jsonline','jsondata'='array'} into table t2;  这个样例是在哪

**Comment by aressu1985** [comment]
@Ariznawlll 这个回归一下看看，是否需要补充BVTCASE

**Comment by Ariznawlll** [comment]
<img width="971" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/33298bd7-9162-4ba8-bd32-bcfbd4090d80">

本质是列数不匹配报的Panic，研发修完验证之后报错如上图。

**Comment by aressu1985** [comment]
fixed
