### ISSUE TITLE
[Bug]: mo killed by oom on standlone mode during running sysbench random points queries

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12629]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1e33f7b0d0efd5c61d1b2a8aa2d73fe858f9ec4f
- Hardware parameters:64C 256G
- OS type:
- Others:
```

### Actual Behavior

during running sysbench random points queries, with 10 tables 100w records-per-table, the mo was killed by oom.
<img width="922" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/4c09e3c8-f441-4158-8d46-b3ca1fb419bd">

<img width="1048" alt="企业微信截图_7b39d7bc-7433-4eef-a2a3-9cb93d8e2742" src="https://github.com/matrixorigin/matrixone/assets/47846308/9da3b5fd-c1dc-455a-9fd8-dbe64f189e5f">

PROFILE：
[oom_standlone_2.tar.gz](https://github.com/matrixorigin/matrixone/files/13306340/oom_standlone_2.tar.gz)
[oom_standlone_1.tar.gz](https://github.com/matrixorigin/matrixone/files/13306343/oom_standlone_1.tar.gz)

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/12628 has been merged

**Comment by aressu1985** [comment]
fixed
