### ISSUE TITLE
[Bug]: ut test TestDoRebalance fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12622]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="517" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/95f757af-79ad-4cb3-91b5-6336a7ad0d77">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/6808509515/job/18513078860?pr=12594

**Comment by volgariver6** [comment]
fixed
