### ISSUE TITLE
[Bug]:  CN  restart.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#12626]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1407" alt="截屏2023-11-09 16 43 47" src="https://github.com/matrixorigin/matrixone/assets/39303074/a03e946d-04ca-4256-9c3c-56afe0d69169">
<img width="1515" alt="截屏2023-11-09 16 41 58" src="https://github.com/matrixorigin/matrixone/assets/39303074/40ea14de-8eef-41bb-9548-d57bc8ab1b91">

log:
[test.log](https://github.com/matrixorigin/matrixone/files/13305946/test.log)

**Comment by nnsgmsone** [comment]
issue12626 the reason why the error is because of an illegal pipeline, this pipeline plan nodes of the number of 0, so it will panic. add some fatal log, used to capture the illegal plan corresponding to sql

**Comment by nnsgmsone** [comment]
提交了pr，接下来应该不会挂掉了。

**Comment by nnsgmsone** [comment]
观察几天看看是否已经完全修复。

**Comment by nnsgmsone** [comment]
继续观察

**Comment by nnsgmsone** [comment]
继续观察中

**Comment by nnsgmsone** [comment]
应该已经好了

**Comment by aressu1985** [comment]
issue 关闭
