### ISSUE TITLE
[Performance]: should put low ndv column first in sort columns (primary key, cluster by) 

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#12627]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

CREATE TABLE `statement_info` (
`statement_id` VARCHAR(36) NOT NULL COMMENT 'statement uniq id',
`transaction_id` VARCHAR(36) NOT NULL COMMENT 'txn uniq id',
`session_id` VARCHAR(36) NOT NULL COMMENT 'session uniq id',
`account` VARCHAR(1024) NOT NULL COMMENT 'account name',
`user` VARCHAR(1024) NOT NULL COMMENT 'user name',
`host` VARCHAR(1024) NOT NULL COMMENT 'user client ip',
`database` VARCHAR(1024) NOT NULL COMMENT 'what database current session stay in.',
`statement` TEXT NOT NULL COMMENT 'sql statement',
`statement_tag` TEXT NOT NULL COMMENT 'note tag in statement(Reserved)',
`statement_fingerprint` TEXT NOT NULL COMMENT 'note tag in statement(Reserved)',
`node_uuid` VARCHAR(36) NOT NULL COMMENT 'node uuid, which node gen this data.',
`node_type` VARCHAR(1024) NOT NULL COMMENT 'node type in MO, val in [DN, CN, LOG]',
`request_at` DATETIME NOT NULL COMMENT 'request accept datetime',
`response_at` DATETIME NOT NULL COMMENT 'response send datetime',
`duration` BIGINT UNSIGNED DEFAULT '0' COMMENT 'exec time, unit: ns',
`status` VARCHAR(1024) NOT NULL COMMENT 'sql statement running status, enum: Running, Success, Failed',
`err_code` VARCHAR(1024) DEFAULT '0' COMMENT 'error code info',
`error` TEXT NOT NULL COMMENT 'error message',
`exec_plan` TEXT DEFAULT '{}' COMMENT 'statement execution plan',
`rows_read` BIGINT DEFAULT '0' COMMENT 'rows read total',
`bytes_scan` BIGINT DEFAULT '0' COMMENT 'bytes scan total',
`stats` TEXT DEFAULT '[]' COMMENT 'global stats info in exec_plan',
`statement_type` VARCHAR(1024) NOT NULL COMMENT 'statement type, val in [Insert, Delete, Update, Drop Table, Drop User, ...]',
`query_type` VARCHAR(1024) NOT NULL COMMENT 'query type, val in [DQL, DDL, DML, DCL, TCL]',
`role_id` BIGINT DEFAULT '0' COMMENT 'role id',
`sql_source_type` TEXT NOT NULL COMMENT 'sql statement source type',
`aggr_count` BIGINT DEFAULT '0' COMMENT 'the number of statements aggregated',
`result_count` BIGINT DEFAULT '0' COMMENT 'the number of rows of sql execution results'
) CLUSTER BY (`request_at`, `account`)

这里的CLUSTER BY (`request_at`, `account`)， 第一列时间列是高ndv列，第二列account是低ndv列。原则是将低ndv列放在前面这样查询性能更好。
具体到这个例子里，要么改成cluster by request_at单列，要么改成account列在前面。

**Comment by fengttt** [comment]
We already fixed this, request_at only.    @gavinyue ?

**Comment by fengttt** [comment]
Oh upgrade.    We probably did not upgrade -- which is fine, the overhead is not too bad -- just an useless composite primary key col ...

**Comment by gavinyue** [comment]
> `request_at`, `account`)， 第一列时间列是高ndv列，第二列account是低ndv列。原则是将低ndv列放在前面这样查询性能更好。
> 具体到这个例子里，要么改成cluster by request_at单列，要么改成account列

没有， 只改了rawlog

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/12722

**Comment by badboynt1** [comment]
还有好几个系统表都有这个问题的，我只是举了一个例子

**Comment by badboynt1** [comment]
![企业微信截图_16995193939738](https://github.com/matrixorigin/matrixone/assets/112734932/5a23c9c5-c8ba-44d1-89f7-1eceebdb00d9)

例如这个。 其他更多的，我也没有逐个去检查

**Comment by LiSong0214** [comment]
按照需求的标题来做吧，当前已经做了 statement_info 这张表，如果需要更多的表，可以列出来再改。请 @badboynt1 把表补齐

**Comment by badboynt1** [comment]
![企业微信截图_17025251604149](https://github.com/matrixorigin/matrixone/assets/112734932/982f913d-d11b-4ce7-8241-b1ba692b597b)

1.1-dev的环境，升级上来之后ddl还是没有改掉

**Comment by fengttt** [comment]
Could be an upgrade issue.

@badboynt1 can you confirm that for clustered by columns, such as cluster by (col1, col2), we will not compute a hidden column of col1#col2 -- cluster by just sorts data in col1, col2 order, right?

**Comment by badboynt1** [comment]
现在clusterby也是通过隐藏列来实现的，和复合主键的逻辑完全一致，唯一区别是不用去重。
