### ISSUE TITLE
[Bug]:  the result of window function is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12639]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 15e7b49f364213b99b27a73b6a99ab4fff7bb8e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="684" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7d562cfe-6a97-4fac-9191-2d0ce26e584b">
<img width="675" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b112e7c0-c8f2-4c03-8e3c-8c5879afa8b0">
<img width="665" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5154515e-b75a-4a88-8aa4-6c0be17b471b">

### Expected Behavior

<img width="665" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c1a7b9e6-85eb-43fd-9958-e3f915158b13">
<img width="678" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3c731a81-605e-44b3-a71a-71171f27e2dd">
<img width="1440" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9302eb97-75a9-4722-888a-54a1442d1e20">

### Steps to Reproduce

```Markdown
create table window01(col1 int, col2 varchar(20));
insert into window01 values(1,'老师');
insert into window01 values(2,'医生');
insert into window01 values(3,'工人');
insert into window01 values(10,'学生');
insert into window01 values(20,'学生');
insert into window01 values(12,'学生');
insert into window01 values(21,'老师');
insert into window01 values(100,'老师');
insert into window01 values(200,'工人');

select col2, avg(col1) over (partition by col2 order by col1 desc) from window01;
select col2, col1, sum(col1) over (partition by col2 order by col1 desc) from window01;
select col2, col1, min(col1) over (partition by col2 order by col1 desc) from window01;
select col2, col1, max(col1) over (partition by col2 order by col1 desc) from window01;
select col2, col1, count(col1) over (partition by col2 order by col1 desc) from window01;
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by Ariznawlll** [comment]
<img width="1599" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/581a6ce3-a201-453c-9969-e3fa88d2f040">

<img width="1639" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/58a7c657-77f4-4665-b657-bd34644f739c">

<img width="1631" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c724ddd6-66a2-486b-8f3b-248574c43eb1">

<img width="1654" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/88073fd5-064f-4b33-ad4a-ac509b9265b8">

<img width="1650" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/73867a9b-b5ed-4903-8e4f-cd9f3b89ec1e">

Verified!
