### ISSUE TITLE
[Bug]:  mem usage is more than 80%  on standlone mode during running sysbench random points queries

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12631]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d2fe30c70f7838f72d2c7cd9aeb20a0fb7a2cd3f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

during running sysbench random points queries, with 10 tables 100w records-per-table, the mem usage is more than 80%.
<img width="1085" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/f9afbaeb-8aa5-4647-ae04-c67eb266a533">

mo profile:
[mem_large.tar.gz](https://github.com/matrixorigin/matrixone/files/13306609/mem_large.tar.gz)

**Comment by aptend** [comment]
![Image](https://github.com/matrixorigin/matrixone/assets/49832303/3ec9433b-5753-4e08-9994-87baaef4cf0f)

**Comment by nnsgmsone** [comment]
dup with #11658

**Comment by nnsgmsone** [comment]
等待内存分支处理完后合入后在测试f

**Comment by nnsgmsone** [comment]
还未处理，还在处理内存分支的超时问题中。

**Comment by nnsgmsone** [comment]
处理#13045和#13219中.

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
wait https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
wait https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
wait https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
正在和存储的同事协商https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待#12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by ouyuanning** [comment]
跟这个  https://github.com/matrixorigin/matrixone/issues/12142  是一个问题，建议关闭掉这个吧
