### ISSUE TITLE
[Bug]: pipeline client max connections is too large

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#12652]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The default maximum number of connections is 10W, this is too large. If you change it to 100, the checkin merge run tpch will fail.

**Comment by nnsgmsone** [comment]
这个问题是由于shuffle的逻辑也是采用一个桶一个链接。。对于shuffle而言，可能多个桶需要复用一个链接？ @aunjgr

**Comment by aunjgr** [comment]
理论上应该两个cn之间只保留一个连接

**Comment by aunjgr** [comment]
1.2开始后再看

**Comment by aunjgr** [comment]
等本周次级索引结束再看

**Comment by aunjgr** [comment]
下周看

**Comment by aunjgr** [comment]
等次级索引完成

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
待设计

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
在解决中移物联的issue

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
周一已经开会讨论过

**Comment by zhangxu19830126** [comment]
讨论的方案性能不行。

**Comment by zhangxu19830126** [comment]
还需要继续讨论方案

**Comment by zhangxu19830126** [comment]
按照讨论，按照田博士的设计做

**Comment by badboynt1** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
