### ISSUE TITLE
[Install]: Lacking necessary description of properties on system_vars_config.toml

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1266]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 65c9c4b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 Lacking necessary description of properties after line 331 in system_vars_config.toml,

**Comment by broccoliSpicy** [comment]
PR#1516 solved this issue
