### ISSUE TITLE
[Bug]: 查询表信息偶发超时

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#12673]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7244406e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

/* cloud_nonuser */SELECT relname AS `name`, mo_table_rows(reldatabase, relname) AS `rows`, mo_table_size(reldatabase, relname) AS `size`, if (role_name IS NULL, '-', role_name) AS `owner`, mo_tables.created_time AS created FROM mo_catalog.mo_tables LEFT JOIN mo_catalog.mo_role ON mo_catalog.mo_tables.owner=role_id WHERE relkind IN ('r','e','cluster') AND reldatabase='mo_catalog' Order by name;
日志如下：
2023/11/10 10:26:03.250719 +0000 ERROR meta/meta.go:160 trace {"error": "context canceled", "elapsed": "59.994364449s", "rows": 0, "sql": "/* cloud_nonuser */SELECT relname AS `name`, mo_table_rows(reldatabase, relname) AS `rows`, mo_table_size(reldatabase, relname) AS `size`, if (role_name IS NULL, '-', role_name) AS `owner`, mo_tables.created_time AS created FROM mo_catalog.mo_tables LEFT JOIN mo_catalog.mo_role ON mo_catalog.mo_tables.owner=role_id WHERE relkind IN ('r','e','cluster') AND reldatabase='mo_catalog' Order by name;"}
环境：Aliyun，数据面Unit环境，freetier-01

### Expected Behavior

正常返回，之前一般不需要这么久

**Comment by jensenojs** [comment]
<img width="1956" alt="企业微信截图_614f18c1-dbab-4d74-9173-6927d03b9d0f" src="https://github.com/matrixorigin/matrixone/assets/56761542/ef5b4aa3-b907-4350-a693-6a557b13d684">

**Comment by jensenojs** [comment]
我上 环境：Aliyun，数据面Unit环境，freetier-01的环境查了一下system的statement_info的表, 相应时段下就没有相应的记录 
<img width="1436" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ad796bac-7cc0-4542-8bd9-41555f729921">

**Comment by jensenojs** [comment]
<img width="1927" alt="企业微信截图_e894afc9-8b18-4f4d-a655-0240e084d0e8" src="https://github.com/matrixorigin/matrixone/assets/56761542/387fc2f0-0186-410c-bb34-d36fd332cc9e">
查询system表中statement_info的duration可以看到这个sql的耗时在mo中就比较高, 排除是cloud的问题, 请龙冉哥有空的时候帮忙看看呗 @aunjgr

**Comment by daviszhen** [comment]
mo_table_rows(reldatabase, relname) AS rows, mo_table_size 非常耗时间。

**Comment by aunjgr** [comment]
等本周次级索引结束再看

**Comment by aunjgr** [comment]
需求待确认

**Comment by aressu1985** [comment]
需要先明确ISSUE是否确实是mo_table_rows函数导致

**Comment by aunjgr** [comment]
wait for PR

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
等pr

**Comment by aunjgr** [comment]
等PR

**Comment by gouhongshen** [comment]
1.2 会优化这两个函数

**Comment by gouhongshen** [comment]
等 PR

**Comment by gouhongshen** [comment]
PR 已经 merge 了，继续观测情况。

**Comment by heni02** [comment]
1.1-dev 单表load 1亿的数据量，查询毫秒级别返回
commit: 83b8499b3727ba8fb2814c9b9900145014c7e11f
<img width="1539" alt="企业微信截图_d833b65c-38d9-404a-a82a-bd6102750f0f" src="https://github.com/matrixorigin/matrixone/assets/113406637/b3526ca8-d722-48fe-950f-7259d7dbc4e2">

**Comment by aressu1985** [comment]
内核测试未发现问题，需要云平台在观察
