### ISSUE TITLE
[Refactoring]: split the batch to fitted rows(based size of batch),  to avoid big alloc size

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#12685]
### Why do you want to refactor this code?

```Markdown
当一个batch的整体大小大于特定大小时（比如1G），那么要把batch进行切割，不一定要达到8192就要往下传。
```

### Describe the solution you'd like

需要处理的地方大概包含：
1、函数执行框架中，的 ExpressionExecutor.Eval  接口需要调整，原来它是返回一个Vector。
     可能要返回：这次处理的长度 + 对应的Vector
     
2、对于要返回的batch，它会有很多个Vector，这些Vector可能都是通过Eval拿到的，那么需要处理一下某个Vector溢出引起的重新Eval问题。比如：projection 算子，假设有4个列，前面2个列在Eval时没有溢出，第3个列Eval发生溢出，那么实际返回的行数要以第三个列的行数为准。如果第4个继续溢出？这些需要有个策略处理

3、因为一个process要承载很多次alloc。这个算子内的切割可能没有问题。但是一次执行有很多算子。
     所以切割的阈值，不能使用mpool里的那个判断的size，可能要小很多。
     或者对于一个eval来说，它有一个阈值。对于一个process来说又有另外一个阈值？

**Comment by m-schen** [comment]
目前这个接口暂时没有需要改动的需求，这部分代码感觉更适合业务代码来做，
碰到error后减少输入的长度进行retry，或甚至是一行一行计算。

感觉可以关掉。
