### ISSUE TITLE
[Bug]: free instance login reported error file mo-20231111/data/.... not found

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12692]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-5eb164b9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/113406637/ed12232d-2349-4a65-8c8f-92295945ed34)
<img width="1375" alt="企业微信截图_12173af3-71da-4925-b231-d97257a736c3" src="https://github.com/matrixorigin/matrixone/assets/113406637/069d5cc6-54ba-4c2b-acab-25d03670b147">
mysql -h freetier-01.cn-hangzhou.cluster.matrixonecloud.cn -P 6001 -u c051d682_1e09_41be_8a1d_242c3855a026:admin:accountadmin  -p
Enter password:
ERROR 20405 (HY000): file mo-20231111/data/d8ad0220-8149-11ee-a68e-4282d06c2cd9_00000 is not found

loki:
http://121.43.41.174/explore?panes=%7B%22ed_%22:%7B%22datasource%22:%22P3C839627617F91E0%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3C839627617F91E0%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by DanielZhangQD** [comment]
Another One:
mysql -h freetier-01.cn-hangzhou.cluster.aliyun-dev.matrixone.tech -P 6001 -u a91f22ef_2c0f_4242_94b2_516b15673722:admin:accountadmin  -p
ERROR 20405 (HY000): file mo-freetier-01-20231010/data/c46693eb-8149-11ee-9305-1e49cefd0a8f_00000 is not found

**Comment by LeftHandCold** [comment]
初步分析 18点54分26 后面向阿里云写入的多个文件应该是失败了，但是dn可以读（所以可以继续megre），cn读就是not found，但是返回成功。怀疑当时是写diskcache成功了，但是向oss写入失败了。

**Comment by LeftHandCold** [comment]
<img width="1544" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/0bba786e-158d-46a7-9e03-f1d5b8036724">

**Comment by reusee** [comment]
https://github.com/matrixorigin/matrixone/commit/52d9153a96f7fb9ac7faa6a006de3c55e8faf4ab
已修复。原因是阿里云的服务出问题，但mo因为写法有误，没有正确处理错误，导致文件没有实际写到阿里云却不返回错误。

**Comment by reusee** [comment]
https://github.com/matrixorigin/matrixone/pull/12698
增加从磁盘缓存修复S3文件的功能

**Comment by reusee** [comment]
all fixes merged, re-assigning.

**Comment by aressu1985** [comment]
回归测试中

**Comment by heni02** [comment]
待回归
