### ISSUE TITLE
[Bug]: go语言中，用多租户连接mo数据库时，报错了

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixone#12711]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
 mo-1.0.0-rc2
- Hardware parameters:
- OS type:centos7.9
```

### Actual Behavior

**1、在go语言中，用 租户名+用户名 的方式连接mo数据库时，报错，如下图：**
`package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	mo_addr := "192.168.110.247"
	mo_port := 6001
	mo_user := "sys:root"
	mo_password := "111"

	url := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?loc=UTC&parseTime=true", mo_user, mo_password, mo_addr, mo_port, "test1")
	db, err := sql.Open("mysql", url)
	if err != nil {
		fmt.Printf("open database failed: err[%v]\n", err)
		return
	}
	if err = db.Ping(); err != nil {
		fmt.Printf("ping database failed: err[%v]\n", err)
		return
	}

	fmt.Println("mo 连接成功!")
}`

**2、上述执行结果报错，如下图：**
![image](https://github.com/matrixorigin/matrixone/assets/91644845/f71f7484-1707-4a70-bacb-65a171726ea6)

**3、用户名中不带租户和角色时，连接正常：**
`package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	mo_addr := "192.168.110.247"
	mo_port := 6001
	mo_user := "root"
	mo_password := "111"

	url := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?loc=UTC&parseTime=true", mo_user, mo_password, mo_addr, mo_port, "test1")
	db, err := sql.Open("mysql", url)
	if err != nil {
		fmt.Printf("open database failed: err[%v]\n", err)
		return
	}
	if err = db.Ping(); err != nil {
		fmt.Printf("ping database failed: err[%v]\n", err)
		return
	}

	fmt.Println("mo 连接成功!")
}
`

**4、上面第3步中代码执行不报错：**
![image](https://github.com/matrixorigin/matrixone/assets/91644845/bf8331e9-8d53-41f3-a07c-258c13437170)

### Expected Behavior

go语言连接mo时，带不带租户名，都应该直接连接成功。

### Additional information

除非将连接用户名中的冒号通过URL编码转化为%3A，才能连接，如下：
![1699871995119](https://github.com/matrixorigin/matrixone/assets/91644845/c7c9d9a0-d21f-4693-bf86-6bee0ccf20ec)

**Comment by YANGGMM** [comment]
mysql driver的问题没办法处理，只能通过 %3A 或者 # 的方式规避 @yanghaitao5000

**Comment by aressu1985** [comment]
有规避方式，问题先关闭

**Comment by yanghaitao5000** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
