### ISSUE TITLE
[Bug]: COALESCE()函数遇到日期字段时，返回的非空值不对

### ISSUE THREAD

**Issue by yanghaitao5000** [matrixorigin/matrixone#12725]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1.0.0-rc2
- Hardware parameters:
- OS type:mo_cloud
```

### Actual Behavior

**1、 如下图， coalesce(NULL, 2022-01-01)不应该返回2020， 应该返回2022或2022-01-01**

![image](https://github.com/matrixorigin/matrixone/assets/91644845/efe1727a-02d4-43c9-ace5-c755d2977e52)

### Steps to Reproduce

```Markdown
drop table if exists t2;
create table t2(a float, b datetime);
insert into t2 values (12.345, '2022-02-20 10:10:10.999999');
insert into t2 values (3.45646, NULL);
insert into t2 values(NULL, '2023-04-03 22:10:29.999999');
insert into t2 values (NULL, NULL);
select coalesce(b, 2022-01-01) from t2;
```

**Comment by YANGGMM** [comment]
mysql:
<img width="529" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/73b38a5a-863b-4169-9183-dbaee6bf603d">

mo:
<img width="501" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/0829e184-3855-4ec0-b554-1ed99f3a2a08">


所以看起来没什么问题。

**Comment by yanghaitao5000** [comment]
**ok，没问题了，2022-01-01 这个值，我当字符串了，抱歉！**
![1699958831950](https://github.com/matrixorigin/matrixone/assets/91644845/3b5bc609-9497-4bc3-8355-e9dfbc90cd94)
