### ISSUE TITLE
[Bug]: TPCH 1t test on tke report 'internal error: get dispatch process by uuid timeout'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12723]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e9a3889a4fc8f73e637544001533c7eedb6d7861
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6852410647/job/18631713322

<img width="1866" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/faa62a38-8872-4944-99ea-3984f4535701">

log: http://132.232.112.34:30088/explore?panes=%7B%229mi%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by badboynt1** [comment]
和https://github.com/matrixorigin/matrixone/issues/12648 大概率是同一个原因导致的问题

**Comment by badboynt1** [comment]
fixed

**Comment by Ariznawlll** [comment]
Verified!
