### ISSUE TITLE
[Tech Request]: Disk cache refactor/cleanup umbrella issues

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#12739]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Several disk cache related issues.   Here is an umbrella issue that we track all of them together.
```

### Additional information

- [x] #12738 
- [x] #12506 
- [x] #9292
- [x] #12702

**Comment by fengttt** [comment]
#12702

**Comment by reusee** [comment]
All done for now.
