### ISSUE TITLE
[Tech Request]: log discache add/evict 

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#12738]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
When an S3 object is added to disk cache, we should log the object name, database/table name (available from stack), size.

When an S3 object is evicted, we should log evicted object name.
```

**Comment by reusee** [comment]
pr sent.

**Comment by reusee** [comment]
pr merged, re-assigning https://github.com/matrixorigin/matrixone/commit/ce326a5457a89ca12aecb1e03c87af0a498de558
