### ISSUE TITLE
[Bug]: TPCH 10G and 100G performance degradation.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12733]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**TPCH 10G 100G性能下降：**
<img width="961" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9a536182-efe2-47d6-8fc8-79e4e5ef6bfe">

**Binary search result:**
<img width="600" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ffe2567f-45ed-4f7c-bfa4-da6c7e3d080a">

The commit_Id that causes the performance degradation is in the range of [380e8ff8, ee84a672], but it report errors on commitId marked in red.

**Error job url：**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6861094537

<img width="1413" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/990f24a5-eeb3-438f-ac9b-5fba47e01d45">

**Comment by badboynt1** [comment]
大概率是昨天 runtime filter相关的那个pr导致的。已经在https://github.com/matrixorigin/matrixone/pull/12730 这里revert掉了。 等今晚的daily观察一下

**Comment by badboynt1** [comment]
fixed

**Comment by Ariznawlll** [comment]
10G:
<img width="819" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/4bf33ab8-d49f-4bd1-9ce8-6081546eaeed">
100G:
<img width="983" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3256e1e1-a6e5-44d4-873a-20e111b7da0f">

Verified!
