### ISSUE TITLE
[Bug]: 创建链接后短时间内出现多次invalid connection报错

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#12764]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-90dac68d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

链接应该是13:24链接上的，在13:30跑的时候执行不通过，报错invalid connection.
2023/11/15 13:24:17.995772 +0000 DEBUG gorm@v1.25.4/finisher_api.go:610 trace {"elapsed": "1.780773ms", "rows": 0, "sql": "/* cloud_user */use tpch_10g;"}
2023/11/15 13:31:23.570695 +0000 ERROR gorm@v1.25.4/finisher_api.go:610 trace {"error": "invalid connection", "elapsed": "2m56.890871101s", "rows": 0, "sql": "/* cloud_user */\ninsert into lineitem select * from mo_sample_data_tpch_sf10.lineitem;"}
2023/11/15 13:31:23.570868 +0000 ERROR gorm@v1.25.4/finisher_api.go:610 trace {"error": "driver: bad connection", "elapsed": "28.606µs", "rows": -1, "sql": "/* cloud_nonuser */ select database() as db,last_query_id() as query_id;"}
建立连接后，非常短的时间之内就链接失效导致SQL执行失败了。

### Expected Behavior

正常执行

### Steps to Reproduce

```Markdown
偶现
```

### Additional information

[logs.txt](https://github.com/matrixorigin/matrixone/files/13366376/logs.txt)

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by xiaoshuwei** [comment]
未复现，先关闭Issue，如果出现再ReOpen。
