### ISSUE TITLE
[Bug]: cn possible mpool leak and high cross mpool free

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#12776]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="447" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/1e10cfda-869c-401e-86cb-c9fc21f7c37e">

<img width="890" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/dcf83e80-a63f-4a74-b9a0-d88b2a891789">

http://132.232.112.34:30088/d/c3704953-e05a-4e81-b13c-0b9c7f00bd2f/memory-metrics?orgId=1&refresh=30s&from=now-1h&to=now&var-interval=1m&var-namespace=mo-checkin-regression-12773&var-pod=mo-checkin-regression-tp-cn-p78gt

**Comment by m-schen** [comment]
还没看。不过跨mpool释放很难被避免，因为内存传来传去的，但只要持有mpool结构的任意地方都可以释放这块内存。
如果想规避掉大部分情况的话，mpool大概率要被vector所持有，即vector有释放自己的能力（不需要额外传入mpool）。

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
