### ISSUE TITLE
[Bug]:  bvt failed when race enabled

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#12771]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2fd77b849cb7cca57ec6546a930cd66c45a13ca3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/6879399260/job/18711237923

<img width="1274" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/639e8ba0-8aaf-4856-a960-170e00247a5d">

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/6886067968/job/18731169318

**Comment by triump2020** [comment]
Being reproduce:
![1700121405535](https://github.com/matrixorigin/matrixone/assets/63033222/99153388-9a36-4880-8c9f-e3afe658dfe5)

**Comment by triump2020** [comment]
The origin size of colunm b is 197680 when normally :

![1700149255293](https://github.com/matrixorigin/matrixone/assets/63033222/8058d1e9-dda7-4ff7-9b41-e3aac7587b46)


 abnormally :
![1700149152357](https://github.com/matrixorigin/matrixone/assets/63033222/d9da883c-90cf-4bbd-8f18-621de6ee8885)

**Comment by triump2020** [comment]
Transaction had seen the appendable object , instead of the non-appendable object ,  which leads to this bug.

**Comment by triump2020** [comment]
Need to  investigate futher why txn can not see the non-appendable objects

**Comment by triump2020** [comment]
Can't reproduce until now after adding detailed log.

**Comment by triump2020** [comment]
![1701414895079](https://github.com/matrixorigin/matrixone/assets/63033222/1f9636f0-4dd0-4363-841d-3a737ca8b1c3)


From the above logs ,  txn cannot see the non-appendable object ,since  txn 's snapshot ts is less than the non-appendable object's create ts .

**Comment by triump2020** [comment]
Added detailed logs ,  being reproduce.

**Comment by triump2020** [comment]
Being work on it .

**Comment by triump2020** [comment]
![1702561356297](https://github.com/matrixorigin/matrixone/assets/63033222/95bc71e2-640b-4dd8-893e-616966c9652b)


Added log for snapshot ts , wait it to be reproduced

**Comment by triump2020** [comment]
基本定位到问题： 当 两个事务在不同的session 里，MO 默认不保证 session 之间的 外部一致性，导致第二个事务的snapshot ts 小于了第一个事务的commit ts

可以修改test case : sync commit , 这样可以保证 一个client 中 的所有session 之间的外部一致性

**Comment by triump2020** [comment]
@aressu1985 Pls update mo tester tool to ensure consistency between old and new sessions in case of network connection is broken.

**Comment by aressu1985** [comment]
ing

**Comment by aressu1985** [comment]
fixed

**Comment by sukki37** [comment]
Still repro frequently

**Comment by sukki37** [comment]
Repro frequently

https://github.com/matrixorigin/matrixone/actions/runs/7516593448/job/20462138957

**Comment by sukki37** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/7510107232/job/20448441703

**Comment by sukki37** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/7509546055/job/20447216660

**Comment by triump2020** [comment]
最近的这几次是 这里出错：

![1705481137032](https://github.com/matrixorigin/matrixone/assets/63033222/cd5805ba-c37a-45c9-b65f-efb066a6624f)


之前的是这里:
![1705481365468](https://github.com/matrixorigin/matrixone/assets/63033222/12832998-0ee9-4d59-a4ba-06e3b530b66c)
