### ISSUE TITLE
[Bug]: [date 11.16]standalone regression: sysbench 1000w write_olny 100 threads test mo oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12798]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1e52191f73e72a1a389b653a2542dec3d964e229
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6879074704/job/18729137058
<img width="1416" alt="企业微信截图_044dde42-e9d4-47ca-9b8a-f628301626ef" src="https://github.com/matrixorigin/matrixone/assets/113406637/9f8cb264-3053-4a3f-a686-05f28199feac">
这个write_only场景和之前回归不一样的是表加了次级索引，可能和索引有关？

128 mo mem killed message：
[Thu Nov 16 13:38:21 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-0.slice/session-5.scope,task=mo-service,pid=849703,uid=1035
[Thu Nov 16 13:38:21 2023] Out of memory: Killed process 849703 (mo-service) total-vm:302179256kB, anon-rss:254731772kB, file-rss:0kB, shmem-rss:0kB, UID:1035 pgtables:546188kB oom_score_adj:500
[Thu Nov 16 13:38:33 2023] oom_reaper: reaped process 849703 (mo-service), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

mem ：
<img width="1179" alt="企业微信截图_1be22e8b-9a26-45c2-8569-9ea0cc96a583" src="https://github.com/matrixorigin/matrixone/assets/113406637/586b0ee7-1c1a-4e32-9906-c6cca8d4d99d">
<img width="1220" alt="企业微信截图_22973c10-6668-4c4f-b3a1-64bede4a3b6c" src="https://github.com/matrixorigin/matrixone/assets/113406637/be299f30-0632-44d7-b071-3c7fc13dca9c">

profile lost，reproduce again and upload later

**Comment by heni02** [comment]
单独跑此场景没有复现oom，但是测试过程中内存占用涨到了80%+
![image](https://github.com/matrixorigin/matrixone/assets/113406637/81eaff13-c378-4249-8846-86bdda6b80e4)
log:
[mo.tar.gz](https://github.com/matrixorigin/matrixone/files/13377833/mo.tar.gz)

**Comment by heni02** [comment]
昨晚的回归复现了oom
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6892576686/job/18750527953
<img width="1429" alt="企业微信截图_bea22d99-72da-4bc4-ab1b-a33c64c5e512" src="https://github.com/matrixorigin/matrixone/assets/113406637/bf218f43-acfb-4d3b-a5ff-9fae5d04ba08">
mo log：
[sysbench1000w.log](https://github.com/matrixorigin/matrixone/files/13386340/sysbench1000w.log)

**Comment by heni02** [comment]
复现抓取profile，内存涨到90%+
<img width="1421" alt="企业微信截图_356f9ce7-6f23-4f39-98e7-be1053a6bfc7" src="https://github.com/matrixorigin/matrixone/assets/113406637/7de99a02-808f-461a-ae48-8be7b75c314b">
profile：
[mo_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13388918/mo_profile.tar.gz)

**Comment by nnsgmsone** [comment]
处理morpc导致的超时问题中，已经定位到一个bug。旭哥已经提交pr

**Comment by nnsgmsone** [comment]
还未处理，还在处理内存分支的问题中

**Comment by nnsgmsone** [comment]
还未处理，还在处理内存分支的超时问题中。

**Comment by nnsgmsone** [comment]
处理#13045和#13219中.

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by heni02** [comment]
date 12.17 regression还有oom情况:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7238980339/job/19720421709
<img width="1408" alt="企业微信截图_b66bfbca-8141-4840-ba11-ca3b8532b129" src="https://github.com/matrixorigin/matrixone/assets/113406637/a044f4dc-6a2b-43bd-b6a4-d1e0af55952c">
profile:
[1217profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13699241/1217profile.tar.gz)
log:
[molog (1).tar.gz](https://github.com/matrixorigin/matrixone/files/13699262/molog.1.tar.gz)

**Comment by nnsgmsone** [comment]
看内存主要还是read以及hashtable导致的，优先修正read的内存。

**Comment by nnsgmsone** [comment]
wait https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
wait https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
正在和存储的同事协商https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待#12532

**Comment by nnsgmsone** [comment]
内存问题等待#12532

**Comment by heni02** [comment]
main:e0ce614547a09a6fabbf31782bd6ea8684f18c9b
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7523352448/job/20476671257
<img width="1393" alt="企业微信截图_2effb6e9-4176-45c4-8735-7e6e9505b3f7" src="https://github.com/matrixorigin/matrixone/assets/113406637/b6e830b2-5569-4e27-8245-116729626212">
<img width="1362" alt="企业微信截图_c54122b3-30d3-4f59-853d-e14d1b3aacde" src="https://github.com/matrixorigin/matrixone/assets/113406637/dfa17c3b-0414-407c-9592-f05f8854e98f">
profile:
[profile (2).tar.gz](https://github.com/matrixorigin/matrixone/files/13944969/profile.2.tar.gz)

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
处理数据正确性问题中

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by aressu1985** [comment]
update on 3.13:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8242358431/job/22558215794

<img width="1149" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/79dafb48-8e3d-48b1-8377-0828d4f2db8c">

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
定位中

**Comment by heni02** [comment]
confirm，closed
commit：66c433efeb6320beadedb1758352e0b09dc8ebf3
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8421687498/job/23059347221
<img width="1357" alt="企业微信截图_34c6b07d-b302-4fcc-8892-666e5f8bb170" src="https://github.com/matrixorigin/matrixone/assets/113406637/962c6946-197c-45f1-9282-eb417ac88059">
