### ISSUE TITLE
[Bug]: [date 11.16]regression: sysbench 100w write_only test mo hung on standlone mode and distributed mode

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12796]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1e52191f73e72a1a389b653a2542dec3d964e229
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6879074704/job/18736893962
![image](https://github.com/matrixorigin/matrixone/assets/113406637/20b5b00d-5793-4513-8bed-8bfbd1711dc7)

from time 11.16 14:55.29 mo hung, this time profile:
[mo_hung.tar.gz](https://github.com/matrixorigin/matrixone/files/13376829/mo_hung.tar.gz)

missing mo log, reproduce again later and upload this issue

**Comment by sukki37** [comment]
maybe related to `normal_delete`, @ouyuanning please help on this issue, thank you.
```
goroutine 4573931 [select, 63 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).selectFrom1Reg(0xc4ce0c6c80)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/receiver_operator_expand.go:25 +0x91
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).selectFromAllReg(0xc4ce0c6c80)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/receiver_operator.go:164 +0x45
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).ReceiveFromAllRegs(0xc4ce0c6c80, {0x41c5e80, 0xc70a2ca1b0})
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/receiver_operator.go:95 +0x65
github.com/matrixorigin/matrixone/pkg/sql/colexec/merge.(*Argument).Call(0xc4ce0c6580, 0xcedeace000)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/merge/merge.go:48 +0x1b7
github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Argument).normal_delete(0xcd63cb9da0, 0xcedeace000)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/deletion/deletion.go:163 +0x52
github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Argument).Call(0xcd63cb9da0?, 0x41ab6c8?)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/deletion/deletion.go:72 +0x2e
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc78572d810, 0x2, 0x7fc4b7beeb38?}, 0xcedeace000)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/vm.go:77 +0x1ae
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc2ae8a7c78, 0xc9f8636550?)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:158 +0x175
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc236842780, 0xccb6281700)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:153 +0x349
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xccb6281700, 0xc236842780)
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:294 +0x825
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:495 +0x79
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x65
```

**Comment by heni02** [comment]
这个write_only场景和之前回归不一样的是加了次级索引，可能和索引有关？sysbench命令：
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=30 --report-interval=10   --db-ps-mode=disable --auto_inc=off  prepare
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable --mysql-ignore-errors=[20701] oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=300 --report-interval=10  --auto_inc=off  run

**Comment by heni02** [comment]
单独跑了这个场景没有复现，今天晚上回归继续观察看看

**Comment by heni02** [comment]
昨晚的回归没有复现该场景
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6892576686/job/18750528391
<img width="1437" alt="企业微信截图_3945700a-0792-4524-87c6-5e83871a140e" src="https://github.com/matrixorigin/matrixone/assets/113406637/0c263431-02a9-4b88-8411-8b90c6a6331b">

**Comment by heni02** [comment]
tke env also have hung problem：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4b668d3f-ef13-40a1-be5e-915618ff10ba)
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6892804366/job/18771658202
commit：0c38cbf73ed9134feb2694eda1ce0d8ed4385b8e

根据卡住的时间过滤了日志：
http://132.232.112.34:30088/explore?panes=%7B%22ipC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231116%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221700198907000%22,%22to%22:%221700200947000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile：
磁盘满导致没有获取到

**Comment by nnsgmsone** [comment]
处理morpc导致的超时问题中，已经定位到一个bug。旭哥已经提交pr

**Comment by heni02** [comment]
date 11.30 回归测试结果，2个问题：
1.sysbench 1000w write_only还是会出现hung，10w和100w没有hung住的情况了
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7047590473/job/19182004660
<img width="1395" alt="企业微信截图_b328dac5-0437-4668-9d00-e9e6e89b5ef9" src="https://github.com/matrixorigin/matrixone/assets/113406637/5b2c6c20-7a0f-491f-8537-c5ce3ac5f4ce">
测试时间是从30 Nov 2023 22:02:28开始
loki 日志：
http://132.232.112.34:30088/explore?panes=%7B%22dVe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231130%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

2. write_only sysbench 10w报错：txn need retry in rc mode, def changed
<img width="1038" alt="企业微信截图_1f3aee30-e1da-42b1-8e36-041776c1805c" src="https://github.com/matrixorigin/matrixone/assets/113406637/74927793-59f0-42b9-a067-260fc9f96b58">

@volgariver6 麻烦定位下以上两个问题

**Comment by volgariver6** [comment]
最新的一次测试，从日志中看是因为 logtail server 发送 response 花了3分41秒，所以导致logtail client重连，长时间连不上 server，加一些日志看一下原因：

```
{"level":"INFO","time":"2023/12/01 06:09:58.891351 +0800","name":"tn-service.logtail-server","caller":"service/session.go:601","msg":"send logtail too much","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"115b362c-e105-48d0-bc16-2969f1c1bb49","stream-id":1,"remote":"127.0.0.1:39766","sendRound":22973718,"duration":"3m41.183093566s"}
```

**Comment by heni02** [comment]
date 12.3 sysbench 1000w write_only mo oom
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7077349909/job/19261647948
<img width="1393" alt="企业微信截图_859e1332-0353-433c-82ff-f63e34faa673" src="https://github.com/matrixorigin/matrixone/assets/113406637/84a12e91-6b19-4c66-8e3a-8f897b0581e9">
<img width="1440" alt="企业微信截图_3686f042-36ed-4152-a42e-47a630bffa7a" src="https://github.com/matrixorigin/matrixone/assets/113406637/47cf6603-534d-4de4-a96c-69b009965562">

profile:
[moprofile.tar.gz](https://github.com/matrixorigin/matrixone/files/13541481/moprofile.tar.gz)

**Comment by heni02** [comment]
date 12.4 regression also hung
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7087727180/job/19289126190
<img width="1067" alt="企业微信截图_100b2e93-e8ed-4e9b-a5be-964f44e7b1d2" src="https://github.com/matrixorigin/matrixone/assets/113406637/c4529a3f-afe1-464a-b033-655b45de7191">
mo log:
[molog.tar.gz](https://github.com/matrixorigin/matrixone/files/13554145/molog.tar.gz)

profile:
[moprofile.tar.gz](https://github.com/matrixorigin/matrixone/files/13554184/moprofile.tar.gz)

**Comment by volgariver6** [comment]
dup with #13219 , @nnsgmsone will fix it.

**Comment by nnsgmsone** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/13259 @heni02

**Comment by heni02** [comment]
sysbench 100w write_only 没有hung的问题了
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7182582014/job/19559616115
<img width="1403" alt="企业微信截图_ad05f7b0-4777-4258-9a07-5a1c8520bd3e" src="https://github.com/matrixorigin/matrixone/assets/113406637/57bc5f5b-7c3f-413f-a678-4fa1a2aaea8f">

1000w的write_only之前有问题回归流程注释掉了，今天放开明天看下测试结果

**Comment by heni02** [comment]
1000w的write_only还是有hung住的问题
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7209968481/job/19642260223
<img width="1517" alt="企业微信截图_1b474e29-0b00-4545-b2ea-1f42697dfcaf" src="https://github.com/matrixorigin/matrixone/assets/113406637/ab978bd9-f78a-4acc-a78a-7725d7a65b48">

**Comment by nnsgmsone** [comment]
大量的txn client is in pause state, wait for it to be ready，不是查询卡住。。是整个服务不可用了。。具体原因还在分析

**Comment by nnsgmsone** [comment]
已经提交pr。。。这次卡住的问题应该修复了。。不确定还有其他的问题

**Comment by nnsgmsone** [comment]
日志看着不全。还需要再分析分析

**Comment by heni02** [comment]
最近没有出现hung的现象，但是会oom

**Comment by ouyuanning** [comment]
@heni02 如果hung已经没有了，建议这个先关吧。OOM相关的issue已经有很多现有issue了

**Comment by heni02** [comment]
今晚回归加上这两个流程验证

**Comment by heni02** [comment]
没有卡住的现象了，还是会oom，这个单先关闭
commit：b72bea5f640f6d07fbabc5437c7d64f48d020be5
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7462327885/job/20315455949
<img width="1199" alt="企业微信截图_986fa042-7677-438d-92e8-9372b3d65be6" src="https://github.com/matrixorigin/matrixone/assets/113406637/0a4f8d9f-7b2a-4530-a47d-4887608438cb">
