### ISSUE TITLE
[Bug]: cn boost failed sometimes

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12805]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:free01 yesterday
```

### Actual Behavior

<img width="552" alt="企业微信截图_e58c702a-a6b1-47eb-9222-2343c52af4cc" src="https://github.com/matrixorigin/matrixone/assets/60595215/34fd4ebb-ceef-49c1-bc6c-282052e4d36a">

`报错显示wait TN ready timeout: context deadline exceeded`

<img width="1457" alt="企业微信截图_4281c3a2-ce20-4365-8534-80fc607dc33b" src="https://github.com/matrixorigin/matrixone/assets/60595215/32949a8d-e675-40c9-8d7b-433d27768568">

http://47.97.80.230/explore?orgId=1&panes=%7B%22aG4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D,%228O6%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22,%20apps_kruise_io_cloneset_instance_id%3D%5C%22k4tx7%5C%22,%20container%3D%5C%22main%5C%22,%20controller_revision_hash%3D%5C%22default-cn-7997dc9b66%5C%22,%20job%3D%5C%22freetier-01%2Fdefault-cn%5C%22,%20lifecycle_apps_kruise_io_state%3D%5C%22Normal%5C%22,%20matrixone_cloud_cluster%3D%5C%22freetier-01%5C%22,%20matrixone_cloud_component%3D%5C%22cn%5C%22,%20matrixone_cloud_main_cluster%3D%5C%22freetier-01%5C%22,%20matrixone_cloud_profile%3D%5C%22cn.standard%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22,%20matrixorigin_io_namespace%3D%5C%22freetier-01%5C%22,%20namespace%3D%5C%22freetier-01%5C%22,%20pod%3D%5C%22default-cn-k4tx7%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22log-row-context-query-_0.4009359423871903%22,%22maxLines%22:1000,%22direction%22:%22backward%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221700108402000%22,%22to%22:%221700108404000%22%7D%7D%7D&schemaVersion=1

<img width="1458" alt="企业微信截图_02e37c55-6fa5-4880-bcd5-dc5db884eb1a" src="https://github.com/matrixorigin/matrixone/assets/60595215/1153229d-7e14-40f9-938e-8bda350622b1">

### Expected Behavior

success

MatrixOne build info:
  The golang version used to build this binary: go version go1.20.7 linux/amd64
  Git branch name: 1.0-dev
  Git commit ID: 90dac68dd
  Buildtime: 1699878627
  Version: v1.0.0-rc2

**Comment by daviszhen** [comment]
与 #11966  有关

**Comment by daviszhen** [comment]
昨天发现的

**Comment by ouyuanning** [comment]
#11966 已解决。应该已解决

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
