### ISSUE TITLE
[Bug]: updateZoneMap leads to txn leak

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12807]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:free01

MatrixOne build info:
  The golang version used to build this binary: go version go1.20.7 linux/amd64
  Git branch name: 1.0-dev
  Git commit ID: 90dac68dd
  Buildtime: 1699878627
  Version: v1.0.0-rc2
```

### Actual Behavior

txn leak , panic

////////

<img width="1402" alt="企业微信截图_22648f27-679f-4410-a2dc-cee34c782108" src="https://github.com/matrixorigin/matrixone/assets/60595215/c3b6d216-7559-4f47-90b2-833f670a1387">

<img width="1444" alt="企业微信截图_49c956e8-b93c-45d1-89d5-f6917b076925" src="https://github.com/matrixorigin/matrixone/assets/60595215/fb289f9d-9039-4ab5-ae7d-7b6e2eb9d39a">

<img width="1430" alt="企业微信截图_cca4813e-ba66-411e-a6b4-5fd45eb088fa" src="https://github.com/matrixorigin/matrixone/assets/60595215/8a3f5379-ca2c-40f3-a777-eb59814ddd6f">

<img width="1154" alt="企业微信截图_5eaf01d8-6246-494d-970e-fc5a0969af0d" src="https://github.com/matrixorigin/matrixone/assets/60595215/f5288417-7c53-43b1-8b21-e3a077aa6500">

http://47.97.80.230/explore?orgId=1&panes=%7B%22aG4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60goroutine%20160946%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D,%22aLR%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22,apps_kruise_io_cloneset_instance_id%3D%5C%22kjp5z%5C%22,container%3D%5C%22main%5C%22,controller_revision_hash%3D%5C%22default-cn-7997dc9b66%5C%22,filename%3D%5C%22%2Fvar%2Flog%2Fpods%2Ffreetier-01_default-cn-kjp5z_bd212baf-58d8-4bc3-a4a9-271aacd6d27f%2Fmain%2F9.log%5C%22,job%3D%5C%22freetier-01%2Fdefault-cn%5C%22,lifecycle_apps_kruise_io_state%3D%5C%22Normal%5C%22,matrixone_cloud_cluster%3D%5C%22freetier-01%5C%22,matrixone_cloud_component%3D%5C%22cn%5C%22,matrixone_cloud_main_cluster%3D%5C%22freetier-01%5C%22,matrixone_cloud_profile%3D%5C%22cn.standard%5C%22,matrixorigin_io_component%3D%5C%22CNSet%5C%22,matrixorigin_io_instance%3D%5C%22default%5C%22,matrixorigin_io_namespace%3D%5C%22freetier-01%5C%22,namespace%3D%5C%22freetier-01%5C%22,node_name%3D%5C%22cn-hangzhou.10.3.137.132%5C%22,pod%3D%5C%22default-cn-kjp5z%5C%22,pod_template_hash%3D%5C%227997dc9b66%5C%22,stream%3D%5C%22stderr%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22log-row-context-query-_0.9749565064064918%22,%22maxLines%22:1000,%22direction%22:%22backward%22,%22datasource%22:%7B%22uid%22:%22loki%22,%22type%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%221700018176532%22,%22to%22:%221700018177532%22%7D%7D%7D&schemaVersion=1

### Expected Behavior

success

**Comment by daviszhen** [comment]
#11966

**Comment by daviszhen** [comment]
昨天发现的

**Comment by ouyuanning** [comment]
#11966 已closed，应该已解决了
