### ISSUE TITLE
[Bug]: wrong result when shuffle join ends early

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#12835]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/MO-Cloud/issues/863

run q9 and q15 in this issue on 129 standalone. 
return empty result. expect 100 lines.

**Comment by aressu1985** [comment]
not happened in the past few days

**Comment by badboynt1** [comment]
和这个issue有关

**Comment by aressu1985** [comment]
fixed
