### ISSUE TITLE
[Tech Request]: improve fuzzyfilter performance in some case

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#12846]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
1、对于i8/u8/i16/u16/i32/u32 以及部分已这些类型为基础类型的列类型（比如Date）， 可以使用roaring bitmap直接来检查。这样当场就可以确定是否有重复，不会有假阳性的问题。

2、对于int64/uint64，可能可以：方案1：不需要多个hash，根据bitmap长度取余就可以了；方案2：用MO的针对int64的hash算法

3、可以看看把 fuzzyfilter修改为join类型的算子，去掉前面的 union all
   这样对于读取右表（也就是表的旧数据）的时候，只需要Add，不需要Test。应该对于现有数据量较大，insert数据量较小的情况下的去重会有较大提升
```

**Comment by jensenojs** [comment]
1和3都已经做了, 2我要再确认一下, 似乎也得做

**Comment by ouyuanning** [comment]
1中要增加 所有 以 这些为实际类型的 特殊类型的支持。比如date。  也就是其实只要是 []byte 的长度小于等于4的，都应该走1的分支。

2的部分可以尽快处理一下，同样的，2的部分应该覆盖到所有 []byte的长度等于8的类型。
