### ISSUE TITLE
[Bug]: Cannot build `mo_dump` as per the offical guide: /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#12842]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): Not relavant
- Hardware parameters: Not relavant
- OS type: Linux and Mac
- Others: Not relavant
```

### Actual Behavior

As per the guide here, https://github.com/matrixorigin/mo_dump, to build `mo_dump`, below steps are needed:
```bash
git clone https://github.com/matrixorigin/mo_dump.git
cd mo_dump
make modump
```

However it does not work as expected, but throws an error indicating some lib is missing
```bash
root@test0:/data/mo_br_test/mo_dump/mo_dump# make modump
CGO_CFLAGS="-I/data/mo_br_test/mo_dump/mo_dump/cgo " CGO_LDFLAGS="-L/data/mo_br_test/mo_dump/mo_dump/cgo -lmo -lm" go build  -ldflags="-X 'github.com/matrixorigin/mo_dump/pkg/version.GoVersion=go version go1.21.3 linux/amd64' -X 'github.com/matrixorigin/mo_dump/pkg/version.BranchName=main' -X 'github.com/matrixorigin/mo_dump/pkg/version.CommitID=7965d57' -X 'github.com/matrixorigin/mo_dump/pkg/version.BuildTime=1700468641' -X 'github.com/matrixorigin/mo_dump/pkg/version.Version=7965d57'" -o mo-dump ./cmd/mo-dump
# github.com/matrixorigin/mo_dump/cmd/mo-dump
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lmo
collect2: error: ld returned 1 exit status
```

This is reproducible on both Linux and Mac systems.

Also this can be reproduced when trying to build `mo_dump` from `matrixone.git`. Steps to reproduce as follows,
```bash
git clone https://github.com/matrixorigin/matrixone.git
cd matrixone
make modump
```

### Expected Behavior

A binary file of `mo_dump` is genered with not errors thrown.

### Steps to Reproduce

```Markdown
See above
```

### Additional information

See above
related feature:  https://github.com/matrixorigin/matrixone/issues/10094

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/mo_dump/pull/2

**Comment by aronchanisme** [comment]
fixed
<img width="1663" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/be50dfe1-7cb7-4e54-94a5-d2a753522d9f">
