### ISSUE TITLE
panic: tocommit(85) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost? 

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1285]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 61b8f4cbb64567175e1475ff3055a6de4fbda7dd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"panic","ts":"2021-12-04 00:19:09.988","logger":"cube.prophet.raft","caller":"etcdserver/zap_raft.go:101","msg":"tocommit(85) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost?","node":"node0"}
panic: tocommit(85) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost?

goroutine 349 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0003b20c0, {0x0, 0x0, 0x0})
        /var/lib/jenkins/go/pkg/mod/go.uber.org/zap@v1.18.1/zapcore/entry.go:234 +0x446
go.uber.org/zap.(*SugaredLogger).log(0xc00038a570, 0x4, {0x2456fbc, 0xc67567}, {0xc00038c7e0, 0x21272a0, 0xc005b00401}, {0x0, 0x0, 0x0})
        /var/lib/jenkins/go/pkg/mod/go.uber.org/zap@v1.18.1/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /var/lib/jenkins/go/pkg/mod/go.uber.org/zap@v1.18.1/sugar.go:159
go.etcd.io/etcd/server/v3/etcdserver.(*zapRaftLogger).Panicf(0xc005b1ea80, {0x2456fbc, 0xcdb765}, {0xc00038c7e0, 0x2354500, 0xc005a9a140})
        /var/lib/jenkins/go/pkg/mod/go.etcd.io/etcd/server/v3@v3.5.0/etcdserver/zap_raft.go:101 +0x49
go.etcd.io/etcd/raft/v3.(*raftLog).commitTo(0xc00017a1c0, 0x55)
        /var/lib/jenkins/go/pkg/mod/github.com/matrixorigin/etcd/raft/v3@v3.5.1-0.20210824022435-0203115049c2/log.go:237 +0xfe
go.etcd.io/etcd/raft/v3.(*raft).handleHeartbeat(_, {0x8, 0xecdb8eecb37fcf21, 0x5ae6784094d3c47, 0x4, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
        /var/lib/jenkins/go/pkg/mod/github.com/matrixorigin/etcd/raft/v3@v3.5.1-0.20210824022435-0203115049c2/raft.go:1508 +0x45
go.etcd.io/etcd/raft/v3.stepFollower(_, {0x8, 0xecdb8eecb37fcf21, 0x5ae6784094d3c47, 0x4, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
        /var/lib/jenkins/go/pkg/mod/github.com/matrixorigin/etcd/raft/v3@v3.5.1-0.20210824022435-0203115049c2/raft.go:1434 +0x385
go.etcd.io/etcd/raft/v3.(*raft).Step(_, {0x8, 0xecdb8eecb37fcf21, 0x5ae6784094d3c47, 0x4, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
        /var/lib/jenkins/go/pkg/mod/github.com/matrixorigin/etcd/raft/v3@v3.5.1-0.20210824022435-0203115049c2/raft.go:975 +0x12f6
go.etcd.io/etcd/raft/v3.(*node).run(0xc003486a80)
        /var/lib/jenkins/go/pkg/mod/github.com/matrixorigin/etcd/raft/v3@v3.5.1-0.20210824022435-0203115049c2/node.go:356 +0xaa5
created by go.etcd.io/etcd/raft/v3.StartNode
        /var/lib/jenkins/go/pkg/mod/github.com/matrixorigin/etcd/raft/v3@v3.5.1-0.20210824022435-0203115049c2/node.go:230 +0x295
```

### Steps to Reproduce

```markdown
1. build binary on jenkins server, then distrubute to db server
2. start up mo service
3. db crashed
```

**Comment by lni** [comment]
The Raft log is empty on the crashed node when the toCommit value of a Raft heartbeat message received from a leader node indicates that at least 85 committed log entries have been successfully replicated to that crashed node. Also note that the crashed code is from a pretty much unmodified etcd server running in embedded mode. 

@lignay when jenkins server updates the binary on a db server, any chance it might also remove the data directory?

**Comment by lignay** [comment]
@lni, the data directory was removed before install.

As per  discussed with dev, this issue caused by the configuration "join" in system_vars_config.toml set to emtpy string on node mod-dev1 and removed the data directory, in the meanwhile, the rest of two nodes mo-dev2 & mo-dev3 are still running. If mo-dev1 was being launched, the node received  request to join the existing cluster from the new leader, but the role of mo-dev1 is leader because of empty setting on property "join", then mo-dev1 threw panic error to kill itself.
This case will be taken care of by matrix-operator in future, so still keep this ticket open and assign to @sukki37 as tracker.

**Comment by lignay** [comment]
@lni, the data directory was removed before install.

As per  discussed with dev, this issue caused by the configuration "join" in system_vars_config.toml set to emtpy string on node mod-dev1 and removed the data directory, in the meanwhile, the rest of two nodes mo-dev2 & mo-dev3 are still running. If mo-dev1 was being launched, the node received  request to join the existing cluster from the new leader, but the role of mo-dev1 is leader because of empty setting on property "join", then mo-dev1 threw panic error to kill itself.
This case will be taken care of by matrix-operator in future, so still keep this ticket open and assign to @sukki37 as tracker.

**Comment by lignay** [comment]
@lni, the data directory was removed before install.

As per  discussed with dev, this issue caused by the configuration "join" in system_vars_config.toml set to emtpy string on node mod-dev1 and removed the data directory, in the meanwhile, the rest of two nodes mo-dev2 & mo-dev3 are still running. If mo-dev1 was being launched, the node received  request to join the existing cluster from the new leader, but now the role of mo-dev1 is leader because of setting empty string on property "join", then mo-dev1 threw panic error to kill itself.
This case will be taken care of by matrix-operator in future, so still keep this ticket open and assign to @sukki37 as tracker.
