### ISSUE TITLE
[Bug]: ut test TestKeeper fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#12850]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="455" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/29610870-011b-43ff-b629-347dcc8b9a62">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/6927357663/job/18841083126?pr=12841

**Comment by arjunsk** [comment]
Hi @zhangxu19830126 , Kindly look into this issue.

If you are not the right assignee, please reassign it to the appropriate person.

**Comment by zhangxu19830126** [comment]
fixed
