### ISSUE TITLE
[Bug]: MO Checking regression ON TKE failed: load timeout

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#12872]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): a94b364c8
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ci `MO Checkin Regression On TKE` failed on load timeout  执行时间超过 10min
https://github.com/matrixorigin/matrixone/actions/runs/6942128606/job/18885609046

![image](https://github.com/matrixorigin/matrixone/assets/3927687/045f7fc8-9f03-42b2-a412-79d08db1af74)

对比了一下正常的执行时间，
mo-checkin-regression-12862（该issue load超时任务） V.S.   mo-checkin-regression-12780 (load 耗时 6:07s)
-  主要是 第1 步，和 第 8步超时了。
https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIwjQRIHbTQa0CI2BkX2?scode=AJsA6gc3AA8GGbLozBAW0A-gb6AOI&tab=hlh7my
![image](https://github.com/matrixorigin/matrixone/assets/3927687/7e3b281e-21cd-477e-849a-a667f6fa7f11)

**Comment by xzxiong** [comment]
继续对比 mo-checkin-regression-12862， mo-checkin-regression-12780 
txn Statement duration 的 P50 取值，**有个异常点：在 执行 load前，事务执行已经去到 75 ms**

12862 （左边）
http://132.232.112.34:30088/d/c64970bc-2263-4abd-856d-608bd734f9a7/txn-metrics?orgId=1&var-interval=1m&var-namespace=mo-checkin-regression-12862&var-pod=All&from=1700563245000&to=1700564052000

12780 （右边）
http://132.232.112.34:30088/d/c64970bc-2263-4abd-856d-608bd734f9a7/txn-metrics?orgId=1&from=1700564918000&to=1700565390000&var-interval=1m&var-namespace=mo-checkin-regression-12780&var-pod=All


![企业微信截图_0469a6f3-cdad-46b2-a14c-4e236b4b6d1a](https://github.com/matrixorigin/matrixone/assets/3927687/ff5e434f-f164-435d-a51a-b0b5cf71ab8e)

**Comment by xzxiong** [comment]
对比 Logtail Metric

有个异常点：在 12862 执行 load期间，logtail的 apply-latency 和 apply-notify-latency P50 波动更大，正常应该小于 1ms 

12862 （左边）
http://132.232.112.34:30088/d/e3f7f5b6-3c94-474c-938a-f34ecbb08cff/logtail-metrics?orgId=1&from=1700563200000&to=1700564159000&var-interval=1m&var-namespace=mo-checkin-regression-12862&var-pod=All

12780 （右边）
http://132.232.112.34:30088/d/e3f7f5b6-3c94-474c-938a-f34ecbb08cff/logtail-metrics?orgId=1&from=1700564700000&to=1700565659000&var-interval=1m&var-namespace=mo-checkin-regression-12780&var-pod=All

![企业微信截图_86f63088-2d90-4c89-aca6-6a1cc0c17111](https://github.com/matrixorigin/matrixone/assets/3927687/97e361a0-9204-439e-a9ed-d261bdc26d77)

**Comment by xzxiong** [comment]
对比 FileService Metric, 没有明显异常

12862 （左边）
http://132.232.112.34:30088/d/f22bab50-c8e0-488a-9852-fa1dd50970c5/fileservice-metrics?orgId=1&from=1700563200000&to=1700564159000&var-interval=1m&var-namespace=mo-checkin-regression-12862&var-pod=All

12780 （右边）
http://132.232.112.34:30088/d/f22bab50-c8e0-488a-9852-fa1dd50970c5/fileservice-metrics?orgId=1&from=1700564700000&to=1700565659000&var-interval=1m&var-namespace=mo-checkin-regression-12780&var-pod=All

![企业微信截图_6e66ed06-1e55-4629-afc1-f515a5340794](https://github.com/matrixorigin/matrixone/assets/3927687/cc646a65-b0f1-408c-9b85-c25a8f26b8d7)

**Comment by xzxiong** [comment]
现象总结：
1. 该 #12862 为 ut fix，仅仅修改 UT的代码
2. 从 metirc 未发现明显异常
3. 从action `MO Checkin Regression On TKE` 后续任务是成功的

根因分析
1. 无结论

**Comment by xzxiong** [comment]
@daviszhen load 超时，帮忙看看下一步怎么分析？

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
not working on it

**Comment by aressu1985** [comment]
dup with #13045 ,this closed
