### ISSUE TITLE
[Performance]: tune ap cache policy

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#12876]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

目前的cache 策略有些问题，需要做一些调整。
根据scan的block数量将scan分成三类，小于100个block为small scan，大于某个阈值（待测试决定）为large scan。中间的为normal scan。
针对三种不同类型的scan，采用不同的prefetch，memcache policy

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/2df2415d-189a-437b-904b-741f6611ce61)

![image](https://github.com/matrixorigin/matrixone/assets/112734932/296d992f-714e-4a27-8663-18a28ffa48aa)

**Comment by daviszhen** [comment]
1，cn内部mem cache policy.
2，涉及filservice，存储  。
3，增加daily 截图。
4，通过revert 别人的commit，二分验证的。原因明确。
5，目标：跟之前的性能一致。顺带省内存。
