### ISSUE TITLE
[Bug]:Primary keys should not support enum types

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#12877]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Primary key detection for enum type in bvt

![image](https://github.com/matrixorigin/matrixone/assets/56761542/2b965d13-73f6-421c-9fb7-ba621629b5a3)

### Expected Behavior

This sql should fail
```sql
create table pri01 (coll enum('qy4iujd3wi4fu4h3f', '323242r34df432432', '32e3ewfdewrew') primary key);
```

### Steps to Reproduce

```Markdown
see bvt
```

**Comment by jensenojs** [comment]
@LiSong0214 please confirmed

**Comment by LiSong0214** [comment]
如交流，可以先跳过这个case

**Comment by fengttt** [comment]
Why not?    

We do not support it now, fine.   Future, why not.
