### ISSUE TITLE
[Bug]: streaming: select count(*) from steam mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12888]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0621662be6921e429596e871a807595b1075be8b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select count(*) from stream mo hung:
<img width="685" alt="企业微信截图_c8c484d6-59b6-46d2-8ea9-367b3c40e15d" src="https://github.com/matrixorigin/matrixone/assets/113406637/9560d8ee-ae32-4d30-ae6b-e405f06654e4">

json data：
{"id": 1,"c1": "abc","c2": 3.09}

ddl:
create  stream stream_a(id int,c1 varchar(25),c2 double)
with(
    "type"='kafka',
    "topic"= 'test',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)
dql:
select * from stream_a;

**Comment by heni02** [comment]
sum also has this problem

**Comment by heni02** [comment]
order by also has this problem
<img width="477" alt="企业微信截图_403d6c55-822e-486c-9584-4222c3f8e230" src="https://github.com/matrixorigin/matrixone/assets/113406637/0deb48ad-5e1e-4f35-b30e-eb8e43732c32">

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/commit/b9e354a53992e185f4e31a6d300abc78b7595eab

Assign back to test for validation

**Comment by heni02** [comment]
confirm ,closed
commit : c4b255cbd0ee319c50210706a94eaf5d6084aadf
![Uploading 企业微信截图_c13a7028-95c6-4b7b-a974-5050c6f15470.png…]()
