### ISSUE TITLE
[Bug]: mo table `mo_catalog.mo_indexes` is missing after restored by `mo_br`

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#12891]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
mo: c0094a9393054a34dd8471ef8f52da5b2b9c7d42
mo_br: ccadb1f875be1574f93604e86a3b9ce17b961c31
- Hardware parameters: 8c 16g
- OS type: debian 11
- Others: test0
```

### Actual Behavior

 mo table `mo_catalog.mo_indexes` is missing after restored by `mo_br`. This will cause sql statement like `drop database xxx;` fail due to error `ERROR 1146 (HY000): no such table mo_catalog.mo_indexes`

![企业微信截图_17006439872607](https://github.com/matrixorigin/matrixone/assets/46433151/dffe7539-c623-4f0f-8ed0-2eb92bb95b69)

### Expected Behavior

No error is thrown

### Steps to Reproduce

```Markdown
1. Deploy and start an MO instance by mo_ctl
2. Load `tpch_1g` data by mo-tpch
3. Backup mo data by mo_br
4. Stop mo-service
5. Restore mo data to an empty folder by mo_br and move it to matrixone/mo-data
6. Restart mo-service
7. Connect to mo and execute `drop database tpch_1g;`
```

### Additional information

[6629](https://github.com/matrixorigin/matrixone/issues/6629)

**Comment by LeftHandCold** [comment]
<img width="1581" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/c7461f89-6e48-4b9c-8575-c9748d823c6e">

**Comment by LeftHandCold** [comment]
原因是集群恢复后，创建schemate表时使用的tableid，占了mo_indexes的tableid，可能是ha keeper的id没有恢复成功。

**Comment by daviszhen** [comment]
初步看恢复后hkeeper分配了已经分配的tableId。tableId现在是存在hakeeper里面。

**Comment by volgariver6** [comment]
pr committed again.

**Comment by aronchanisme** [comment]
fixed

mo branch: main
mo commit id:
```bash
root@test0:/data/tools/mo_br_tool/mo-backup# mo_ctl get_cid
2023-11-29 12:02:38.427 UTC+0800    [INFO]    Try get mo commit id
commit fc1cc3b77417745cf6826bca6633175fb7ab2524
Author: YANGGMM <www.yangzhao123@gmail.com>
Date:   Wed Nov 29 11:30:47 2023 +0800

    Primary keys should not support enum types (#13041)
    
2023-11-29 12:02:38.483 UTC+0800    [INFO]    Get commit id succeeded
```

mo_br branch: main
mo_br commit id:
```bash
commit b822de269e8aa23b5829a5c1845290a4027b5420
Merge: ccadb1f 5c88035
Author: Aylei <rayingecho@gmail.com>
Date:   Tue Nov 28 16:38:08 2023 +0800

    Merge pull request #9 from matrixorigin/aylei/docker-image
    
    feat: add docker image build target
```

Steps:
1. deploy mo and start mo-service
2. load tpch 1g data
3. mo_br backup data
4. stop mo-service
5. restore backup data to an empty folder
6. mv mo-data to mo-data-bk, and mv restored data path to mo-data
7. restart mo-service
8. check mo connectivity, mo_catalog.mo_indexes table, tpch_1g data tables, create a sample database and drop this database, create sample table and insert some data

<img width="1664" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/fdbad7cd-9ec5-4371-9e96-169e08afd356">
<img width="1669" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/ff440f96-63ca-49f6-9cbb-6d1e0563204d">
<img width="1670" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/b16cadbf-afc5-491c-95de-5bc55dd9a2c1">
<img width="1669" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/dab5a1e9-453b-4dd9-86ec-1d1bf6e90f78">
<img width="1664" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/e026dc8e-82a2-4525-ad20-e0f501e653ef">
