### ISSUE TITLE
[Tech Request]: add metric to observe avg statement latency

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#12904]
### Is there an existing issue for the same tech request?

parent: https://github.com/matrixorigin/MO-Cloud/issues/2305

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
MO should support observe query latency as metric type data.
```

### Why is this needed ?

MOCloud need to show `avg_statement_latency` time-series panel. Currently, it is calculated from table system.statement_info duration column, which takes unstable query time.

Aim to speedup `avg_statement_latency` calculation, we should calculate the time-series data form metric-type data.

related to https://github.com/matrixorigin/MO-Cloud/issues/1722

**Comment by xzxiong** [comment]
@EZ4BRUCE ptal

**Comment by jyz0309** [comment]
Hello, can I try this issue? @xzxiong

**Comment by EZ4BRUCE** [comment]
> Hello, can I try this issue? @xzxiong

hi @jyz0309 , thanks for your kindness but i'm already working on this 😂 

what can i help u? if you want to try anything else or let me know what u need

**Comment by jyz0309** [comment]
Okay:-) 
Can you recommend a good first issue to me? I'm interested in the code and architecture of mo, but it seems that there hasn't been a good first issue for a long time, and all the issues have been assigned.

**Comment by EZ4BRUCE** [comment]
> Okay:-) Can you recommend a good first issue to me? I'm interested in the code and architecture of mo, but it seems that there hasn't been a good first issue for a long time, and all the issues have been assigned. Thanks a lot :) @EZ4BRUCE

okay, i will ask my colleague for that next Monday ( cuz many of them are still on vacation this week  😂 )

please wait for our msg, thanks ! @jyz0309

**Comment by EZ4BRUCE** [comment]
需要 cherrypick

**Comment by EZ4BRUCE** [comment]
todo:

- [ ] 需要补上升级后重建视图的逻辑（1.2）

**Comment by EZ4BRUCE** [comment]
should test @aressu1985

**Comment by EZ4BRUCE** [comment]
暂无进展

**Comment by aressu1985** [comment]
test done
