### ISSUE TITLE
[Tech Request]: mo-operator cluster upgrade policy

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#12902]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Some cases require specific upgrading order, e.g. new data written by DN cannot be read by CN.
```

### Describe the feature you'd like

Before this feature is implemented, user can also control upgrading process manually, for example, user can bump CN image first, wait rolling-update and then bump DN image.

**Comment by aylei** [comment]
Test: https://github.com/matrixorigin/MO-Cloud/issues/3438#issuecomment-2381186575

**Comment by aylei** [comment]
cc @TangxingZhou this feature can be tested together with https://github.com/matrixorigin/MO-Cloud/issues/3438

**Comment by aressu1985** [comment]
TEST DONE
