### ISSUE TITLE
[Bug]: Init database failed

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12914]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

free01 11-20~11-21
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/fbef0f06-2565-41fa-bec2-a7591488c3cd)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/4fc1fa2d-bb54-4041-b17e-f7484589c734)

http://47.97.80.230/explore?orgId=1&panes=%7B%22aG4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221700409600000%22,%22to%22:%221700582399000%22%7D%7D%7D&schemaVersion=1

### Expected Behavior

no error

**Comment by arjunsk** [comment]
I did not find the https://github.com/matrixone-cloud/mocloud-services repo

![image](https://github.com/matrixorigin/matrixone/assets/9638314/47eeb190-97b4-4f8d-8557-5286cddb144d)

@sukki37 where is this project located?

**Comment by arjunsk** [comment]
I think this is related to mo-service startup. @zhangxu19830126 could you kindly look into this issue or assign it to the right person?

**Comment by xzxiong** [comment]
> I did not find the https://github.com/matrixone-cloud/mocloud-services repo
> 
> ![image](https://user-images.githubusercontent.com/9638314/285275784-47eeb190-97b4-4f8d-8557-5286cddb144d.png)
> 
> @sukki37 where is this project located?
> 
> Also the IP http://47.97.80.230/ is not accessible.

This env has been recycled.

the following file show pod `default-cn-d2s5j` startup log.
[Explore-logs-2023-11-23 16_35_26.txt](https://github.com/matrixorigin/matrixone/files/13454991/Explore-logs-2023-11-23.16_35_26.txt)

**Comment by xzxiong** [comment]
> ...
> 
> the following file show pod `default-cn-d2s5j` startup log. [Explore-logs-2023-11-23 16_35_26.txt](https://github.com/matrixorigin/matrixone/files/13454991/Explore-logs-2023-11-23.16_35_26.txt)

it  seams network issue, but no further infos.

![image](https://github.com/matrixorigin/matrixone/assets/3927687/d6adf270-0e09-40e5-bc6f-11d384b7ab69)

**Comment by xzxiong** [comment]
update: 
- log show: 错误是链接被拒绝，对端的服务都没有开 ；32001 是 LogService
- NO futher info: origin k8s cluster is recycled.

能下次复现，可进一步查看：
1. LogService 有什么异常，可以从 logservice 的 metrics 和 log 尽心下一步分析

**Comment by zhangxu19830126** [comment]
等复现定位问题

**Comment by zhangxu19830126** [comment]
等复现定位问题

**Comment by volgariver6** [comment]
从日志看是网络问题，看不出来更详细的原因

**Comment by XuPeng-SH** [comment]
to next release

**Comment by daviszhen** [comment]
长久未复现。先关了。
