### ISSUE TITLE
[Bug]: panic happens in objectio

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12912]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

free01 11-21~11-23
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/ad14904f-5ae9-46fb-8aef-224a0be05785)

### Expected Behavior

no panic

### Steps to Reproduce

```Markdown
i am not sure we can reproduce it
```

### Additional information

http://47.97.80.230/explore?orgId=1&panes=%7B%22aG4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221700496000000%22,%22to%22:%221700668799000%22%7D%7D%7D&schemaVersion=1

**Comment by arjunsk** [comment]
@LeftHandCold , Could you kindly look at this and assign it to the right person?

**Comment by LeftHandCold** [comment]
fixed as https://github.com/matrixorigin/matrixone/pull/12906

**Comment by daviszhen** [comment]
it was fixed
