### ISSUE TITLE
[Bug]: getTransaction yields a panic

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12913]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

free01 11-20~11-21
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/621d9ebc-e85b-47f7-b991-473b72ddc00e)

http://47.97.80.230/explore?orgId=1&panes=%7B%22aG4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221700409600000%22,%22to%22:%221700582399000%22%7D%7D%7D&schemaVersion=1

### Expected Behavior

no panic

**Comment by arjunsk** [comment]
Duplicate of this https://github.com/matrixorigin/matrixone/issues/12810

@m-schen Kindly have a look at this issue.

**Comment by m-schen** [comment]
22号合并的pr修复过worksapce = nil的问题了，可以在新的main上验证该issue.

相关pr https://github.com/matrixorigin/matrixone/pull/12882

**Comment by daviszhen** [comment]
这周还有

**Comment by m-schen** [comment]
#13166 修复了这个问题，部分查询不能被发往远端执行。

**Comment by daviszhen** [comment]
it was fixed.
