### ISSUE TITLE
[Bug]: streaming : drop stream reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12928]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0621662be6921e429596e871a807595b1075be8b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="751" alt="企业微信截图_0d85bed9-b3da-4d14-a43c-04cf008f54bf" src="https://github.com/matrixorigin/matrixone/assets/113406637/3d75ab4b-955b-4488-b143-839994a3395a">

ddl:
create  stream stream_a(id int,c1 varchar(25),c2 double)
with(
    "type"='kafka',
    "topic"= 'test',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)
json:
{"id": 1,"c1": "abc","c2": 3.09}

select * from stream_a;
drop stream stream_a;

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/commit/87b1ce95033cbaa6bb91cf8b378e8cb49848f0ca

Please verify
