### ISSUE TITLE
[Bug]:  Execute sample function report 'internal error: panic put batch with zero cnt'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12924]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): bc7f5ec3eb50cdb21989fc93694ef2887c47f8e8
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="822" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/84f7e5ec-e674-47ae-bc30-8746d2cb56b8">

### Expected Behavior

结果为 empty set.

### Steps to Reproduce

```Markdown
create table t2(col1 int, col2 int);
insert into t2 values(1,1);
insert into t2 values(2,2);
insert into t2 values(3,3);
insert into t2 values(null,4);
insert into t2 values(null,5);
insert into t2 values(null,6);
insert into t2 values(null,7);

select sample(col1,1 rows) from t2 where col1 > 5;
```

**Comment by m-schen** [comment]
好的哥

**Comment by m-schen** [comment]
已修，可验，哥

**Comment by Ariznawlll** [comment]
<img width="538" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3f7816fc-a528-4448-a50c-5f8b2c98f71d">

Verified!
