### ISSUE TITLE
[Bug]: The result of sample function is incorrent.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12930]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): bc7f5ec3eb50cdb21989fc93694ef2887c47f8e8

- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Table definition：
<img width="812" alt="企业微信截图_17cb937a-c06c-4b2f-94c6-eb35fe6585b9" src="https://github.com/matrixorigin/matrixone/assets/108530700/8d7aa855-8ce1-4415-91ea-5654349fb914">

There are 14 values of col1=127，then execute sql ‘select col1, sample(col2, 20 rows) from t1 group by col1 order by col1;’
<img width="296" alt="企业微信截图_b45bf73e-293a-4c4f-9a93-259fbb212d7f" src="https://github.com/matrixorigin/matrixone/assets/108530700/a8de1b30-0833-42cd-b2a6-171af79b2571">

### Expected Behavior

column=127 corresponds to 14 values.

### Steps to Reproduce

```Markdown
create table t1(col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 timestamp );

load data infile '/path/4000_20_columns_load_data.csv' into table t1;

select count(col1) from t1 where col1 = 127;

select col1,sample(col2, 20 rows) from t1 group by col1 order by col1;

I have given the csv file '4000_20_columns_load_data.csv' to mingsong.
```

**Comment by m-schen** [comment]
已修，可验，哥

**Comment by Ariznawlll** [comment]
<img width="382" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d0a6984a-aff6-4984-9c09-a9c02db8a36c">

Verified!
