### ISSUE TITLE
[Bug]: streaming: streaming source datetime and timestamp type read json data result error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#12938]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0621662be6921e429596e871a807595b1075be8b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

json data：
{"c1":"2000-12-04","c2":"2000-12-04 12:01:06"}
stream ddl：
create stream stream_5(c1 datetime,c2 timestamp)with(
    "type"='kafka',
    "topic"= 'test2',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)
select stream result error：
<img width="674" alt="企业微信截图_54e81217-4b1e-49c6-95ee-7edbfdbfbc6f" src="https://github.com/matrixorigin/matrixone/assets/113406637/e3bbf306-ae7e-40c8-ba30-9235af71b9d6">

**Comment by heni02** [comment]
date type column read json data also result error:
json:
{"c1":"2000-12-04"}
ddl:
create stream stream_7(c1 date, c2 datetime,c3 timestamp)with(
    "type"='kafka',
    "topic"= 'test2',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)
<img width="428" alt="企业微信截图_77cae2d1-9209-4163-bad2-26c033db6e37" src="https://github.com/matrixorigin/matrixone/assets/113406637/ae97da09-30cd-4987-975d-f76da462708f">

**Comment by heni02** [comment]
json:{"c1":"1999-03-20"}
ddl:
create stream stream_7(c1 date, c2 datetime,c3 timestamp)with(
    "type"='kafka',
    "topic"= 'test',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)
json data is part of stream column count read is 0001-01-01, is it expect?
<img width="707" alt="企业微信截图_f16d8560-7b4c-446e-8603-cab00a5fe890" src="https://github.com/matrixorigin/matrixone/assets/113406637/b0f3080e-d8b9-4ea3-8561-9bc06f19ee55">

**Comment by LiSong0214** [comment]
datetime 精度应该是这样的 

![Image](https://github.com/matrixorigin/matrixone/assets/31049447/7c84af7e-e5b6-4cfc-895f-36426f6c93a9)

st表好像不是 dynamic table 吧？ @heni02

**Comment by heni02** [comment]
datetime(3)带精度才会有精度，否则没有精度
<img width="772" alt="企业微信截图_d2d419e7-60a9-4cc4-8ca9-5ff708afb0cb" src="https://github.com/matrixorigin/matrixone/assets/113406637/e69e2584-2953-4798-9b94-601bf9b12382">

**Comment by LiSong0214** [comment]
@gavinyue 我跟贺妮看了下 MO 和 Mysql 8.0 ，他们对于 datetime 和timestamp 的行为是一致的，关于精度方面，默认是0，如果需要存储和显示更多精度，需要在定义的时候加上 (x),例如 datetime(3)、timestamp(6)，所以source 和 dynamic table 的行为也要与之一致，

**Comment by gavinyue** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/54566980/097ca1fd-5da8-4079-a3b2-1912d5a1b068)

**Comment by gavinyue** [comment]
已经支持了timestamp 等。 

datetime精度的问题 也已经提交了pr: https://github.com/matrixorigin/matrixone/pull/13310/files

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13310/files merged

之前代码里有一个特殊处理， 忽略了datetime精度

**Comment by heni02** [comment]
confrim,closed
commit:2a761a0c8fec04129107bd03a3222f356a23f1c6
<img width="1123" alt="企业微信截图_9a680598-7eb6-4c53-83f7-74836c1ead5d" src="https://github.com/matrixorigin/matrixone/assets/113406637/deb02938-c1d1-4cf5-9352-5435316bd1b4">
