### ISSUE TITLE
[Bug]: chatbot didn't work for isolation level

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#12944]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![1700803326219](https://github.com/matrixorigin/matrixone/assets/88298673/85de81d6-1949-44fe-a99a-1c9fdacdaa65)
![1700803326231](https://github.com/matrixorigin/matrixone/assets/88298673/9bf86d65-5ccb-449b-bfae-52c0f15826f6)

### Expected Behavior

https://docs.matrixorigin.cn/1.0.0/MatrixOne/Reference/System-Parameters/distributed-configuration-settings/

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
TODO

**Comment by xiaoshuwei** [comment]
TODO

**Comment by xiaoshuwei** [comment]
TODO

**Comment by xiaoshuwei** [comment]
TODO

**Comment by xiaoshuwei** [comment]
TODO

**Comment by xiaoshuwei** [comment]
TODO
