### ISSUE TITLE
[Bug]: checkin regression timeout: lots of error message "error: internal error: can not find table by id 2"

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#12949]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ssb test timeout

link: https://github.com/matrixorigin/matrixone/actions/runs/6976797123/job/18986206352

log link: http://132.232.112.34:30088/explore?panes=%7B%22ipC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-12942%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221700801908000%22,%22to%22:%221700801924000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

test should succeed

### Steps to Reproduce

```Markdown
dont know
```

**Comment by ouyuanning** [comment]
从错误日志来看。是这个地方fatal了
{"level":"FATAL","time":"2023/11/27 06:41:43.120169 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:920","msg":"BUG: schedule reset remote connection timeout","remote":"127.0.0.1:32001","backend-id":"707cdef2-9ffe-4137-8d15-3d485039eae5","stacktrace":"github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).scheduleResetConn\n\t/home/runner/_work/matrixone/matrixone/head/pkg/common/morpc/backend.go:920\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).readLoop\n\t/home/runner/_work/matrixone/matrixone/head/pkg/common/morpc/backend.go:567\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/home/runner/_work/matrixone/matrixone/head/pkg/common/stopper/stopper.go:259"}

**Comment by ouyuanning** [comment]
错误日志：
[multi-cn-e2e-with-race-linux-x86-reports_getRelId的报错.zip](https://github.com/matrixorigin/matrixone/files/13471571/multi-cn-e2e-with-race-linux-x86-reports_getRelId.zip)

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it
