### ISSUE TITLE
[Bug]: create index on table report 'internal error: Invalid alloc size 1147486208'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#12956]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b49cc70872b55f58b368c7c4c91b33c2a6f5057b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="676" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f4edd7bb-742c-4bda-a7df-a916c89cfde5">

### Expected Behavior

create index success!

### Steps to Reproduce

```Markdown
data scale: tpch 100G
create index indexTest on partsupp(ps_availqty);
```

**Comment by qingxinhome** [comment]
这个问题和远宁沟通了，这个要彻底解决要等龙冉把 spills 做好。然后把算子都修改为
1、 一个批次不能超过8192
2、  有些地方，比如join，需要保持数据的。如果超过数据量要持久化

**Comment by ouyuanning** [comment]
这个case估计等锦赛的那个优化好了之后可能就可以验证看看。

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by m-schen** [comment]
本周没有投入相关工作，等1.1发布后才会有更多规划。

**Comment by m-schen** [comment]
请假了

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
没有投入该工作。

**Comment by m-schen** [comment]
没有进行相关工作。

**Comment by m-schen** [comment]
没有进行相关工作。

**Comment by m-schen** [comment]
没有进行相关工作。

**Comment by m-schen** [comment]
没有进行相关工作

**Comment by m-schen** [comment]
没有进行相关工作

**Comment by m-schen** [comment]
休假中

**Comment by m-schen** [comment]
无进展

**Comment by Ariznawlll** [comment]
[20260226] 大数据测试出现了这个问题；
job url（queries 1y -> write 1y test）：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8029862130/job/21947111382
<img width="1031" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b2971b0d-7e45-421d-8098-d319446fefd9">

log:http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-ead69b4%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by m-schen** [comment]
类似issue太多了，属于select语句过程因为表达式计算等原因产生了超过1个g的batch所导致的问题。

都没开始弄。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/issues/12956
https://github.com/matrixorigin/matrixone/issues/12021
https://github.com/matrixorigin/MO-Cloud/issues/1921

都是相似issue，未处理。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
类似的issue都未处理。

**Comment by m-schen** [comment]
同上 请假中

**Comment by m-schen** [comment]
同上一条评论，目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上一条评论，目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上

**Comment by ouyuanning** [comment]
锦赛确认一下，看着像是 create index的那个问题。估计已经修了

**Comment by jensenojs** [comment]
今天能确认一下还有没有再复现

**Comment by jensenojs** [comment]
等load hung住的问题fix了之后才能测

- https://github.com/matrixorigin/matrixone/pull/15609

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
需要再测一下

**Comment by jensenojs** [comment]
等下面这个pr进去之后再看是怎么回事
- https://github.com/matrixorigin/matrixone/pull/15763

**Comment by jensenojs** [comment]
待验证

**Comment by jensenojs** [comment]
赞无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
<img width="1181" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/97eb9d93-05d6-450f-bce1-4c5571d2aa7c">

**Comment by Ariznawlll** [comment]
观察一阵

**Comment by Ariznawlll** [comment]
**commit：28682fdf988e1906bef3b869b13702c6790ea6bd**
1亿数据量本地测试：
test case：
```
create table if not exists big_data_test.table_basic_for_load_100M( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));
load data url s3option {'endpoint'='******,'access_key_id'='******','secret_access_key'='******','bucket'='******', 'filepath'='mo-big-data/100000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_100M fields terminated by '|' lines terminated by '\n' parallel 'true';
```
<img width="515" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2d50cd39-c7c6-4273-9508-4b99915a32d3">

**Comment by Ariznawlll** [comment]
**commit ：97dbe43d764d7c533e2cfbfff2306edf67f8a626**
<img width="1208" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0559f14a-0b45-43e8-a457-f759dcd67779">

verified
