### ISSUE TITLE
[Bug]: ut test TestNewMOCollector_BufferCnt UNKNOWN

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#12975]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1007" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/14b14f85-31d1-4f2b-8528-63325c0ea9dd">
https://pipelinesghubeus4.actions.githubusercontent.com/6i0uluWebzzWKTJsdip1dxNGG262TgSnWdbPahnwpPRJIunOgs/_apis/pipelines/1/runs/194116/signedlogcontent/15?urlExpires=2023-11-26T09%3A13%3A45.2387978Z&urlSigningMethod=HMACV1&urlSignature=ravyTMKk%2Fw%2BrYRUANrCPp9OaZRmd52ZWIdhoyDF6eiA%3D

**Comment by xzxiong** [comment]
lost CI Action msgs. let's wait next repro @LeftHandCold
