### ISSUE TITLE
[Bug]: ut `TestNewMOCollector_BufferCnt` failed.

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#12990]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/fbb1eda2-b7c0-4720-bd8e-b2f5f32166cc)

### Expected Behavior

no error

**Comment by YANGGMM** [comment]
麻烦@xzxiong 看一下

**Comment by xzxiong** [comment]
found another case like this.
NO clue.
https://github.com/matrixorigin/matrixone/actions/runs/7006790429/job/19079018432?pr=13019

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/7029777446/job/19128072832?pr=13048

**Comment by xzxiong** [comment]
> repro：https://github.com/matrixorigin/matrixone/actions/runs/7029777446/job/19128072832?pr=13048

wait repro after cherry-pick( #13904 )

**Comment by xzxiong** [comment]
@daviszhen ptal, long time no repro.

**Comment by daviszhen** [comment]
没复现。
