### ISSUE TITLE
[Refactoring]: promote the performance for `mo_table_size` and `mo_table_rows`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#13013]
### Why do you want to refactor this code?

```Markdown
https://github.com/matrixorigin/matrixone/issues/12673

云平台的sql用了耗时mo_table_size,mo_table_rows,mo_table_col_max和mo_table_col_min

12673的问题不一定完全是mo_table_size和mo_table_rows造成的。
```

### Describe the solution you'd like

借助新show accounts的方案来改进mo_table_size和mo_table_rows。

subtasks:
1. #13210 
2. #13208

**Comment by gouhongshen** [comment]
related issue: 12673

**Comment by gouhongshen** [comment]
mo_table_size 和 mo_table_rows 的逻辑差不多，基本是下面几个步骤：
1. 收集 workspace 内部数据
2. 更新 logtail
3. 收集 logtail 中的 Row 数据
4. 使用 logtail 记录的 location 加载 object 元数据

如果是 mo_table_size 或 mo_table_rows 本身慢，时间应该主要花在了 2,4两步.

最近 TN 的一个 大的 feature 是使用 object Info 替代 blk info，待这个优化 merge 后，可以避免第 4 步。

**Comment by DanielZhangQD** [comment]
Please also fix the issue in https://github.com/matrixorigin/matrixone/issues/13154

**Comment by gouhongshen** [comment]
the promotion of `mo_table_size` and `mo_table_rows` relies on another feature, it's unlikely to be done within 1.1.0.

**Comment by heni02** [comment]
https://github.com/matrixorigin/matrixone/issues/12673 closed ,
so this feature closed
