### ISSUE TITLE
[Bug]: streaming: part of json data not match stream type,but other json data match read error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13014]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):07d71e8492cb03bf2cd24d80486b1a518c9aa8cb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

stream ddl:
create stream stream_6(c1 char,c2 varchar,c3 text,c4 tinytext,c5 mediumtext,c6 longtext )with(
    "type"='kafka',
    "topic"= 'test',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)

json data:
{"c1": "a","c2":1,"c3": "c","c4":"d","c5":"e","c6":"f"}
c2值和类型不对应，stream会读取空，但其他c3，c4，c5，c6 value值和stream类型对应，查询stream也是读取不到
<img width="932" alt="企业微信截图_f87c09bc-a9ee-4b07-8151-a9f44b1a6ed6" src="https://github.com/matrixorigin/matrixone/assets/113406637/4d6d8db7-699f-4067-a135-e037e3186b52">
尝试了下c1为无效数据1时，c2和其他列读取都是空

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/commit/87b1ce95033cbaa6bb91cf8b378e8cb49848f0ca

Please verify

**Comment by heni02** [comment]
c2类型不匹配的值查询显示乱码
<img width="1051" alt="企业微信截图_082bc4a5-ec5b-4d2f-80e3-dcb636b954a5" src="https://github.com/matrixorigin/matrixone/assets/113406637/ef203cec-54d5-4f69-a0b0-2dcd8a868170">

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13310

已经提了PR

**Comment by gavinyue** [comment]
original problem resolved. 

极值的问题 和https://github.com/matrixorigin/matrixone/issues/13074 重复。

**Comment by heni02** [comment]
不是极值问题，是类型不匹配，c2的values值是数值不是字符出现的问题

**Comment by qingxinhome** [comment]
We will handle it later

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by sukki37** [comment]
tracked by https://github.com/matrixorigin/matrixone/issues/13074
