### ISSUE TITLE
[Bug]: UT db/test/compatibility:TestAll Failed

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#13012]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

faild in [Matrixone CI / UT Test on Ubuntu/x86](https://github.com/matrixorigin/matrixone/actions/runs/7002112812/job/19045280628?pr=13002#logs)

### Expected Behavior

should pass this ut

### Additional information

log file:

[5_Unit Testing.txt](https://github.com/matrixorigin/matrixone/files/13471817/5_Unit.Testing.txt)

**Comment by gouhongshen** [comment]
can not reproduce

**Comment by gouhongshen** [comment]
cannot repro, change to s1.

**Comment by gouhongshen** [comment]
cannot repro. close now.

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8810011549/job/24181721623?pr=15677

[job-logs.txt.zip](https://github.com/matrixorigin/matrixone/files/15087279/job-logs.txt.zip)

**Comment by gouhongshen** [comment]
在忙其他 issue

**Comment by gouhongshen** [comment]
在忙其他issue

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/8987540277/job/24686283106

**Comment by gouhongshen** [comment]
fixed

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/9032992165/job/24822335199?pr=16000

[job-logs.txt](https://github.com/matrixorigin/matrixone/files/15281366/job-logs.txt)

**Comment by gouhongshen** [comment]
修复已经merge 了，再等等看

**Comment by gouhongshen** [comment]
fixed

**Comment by gouhongshen** [comment]
很久未出现，close
