### ISSUE TITLE
[Bug]: Occasional Create Account Failed in Merge Run Sysbench Testing

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13021]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7003788103/job/19051098984

<img width="1202" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/0f147dde-e225-4e34-adf3-ab85dcaea506">

Logs can be found here：
http://132.232.112.34:30088/explore?panes=%7B%22BbA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-13002%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701081834769%22,%22to%22:%221701084406198%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1799" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/13649007-a9b0-42f6-a244-a1d9734f343e">

### Expected Behavior

Taking a successful test log as a reference

<img width="1784" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/92dff4b0-20e5-4ec5-956c-7ebb8ba50b34">

http://132.232.112.34:30088/explore?panes=%7B%22BbA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-13002%5C%22%7D%20%7C%3D%20%60AccountID:3000002%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701081834769%22,%22to%22:%221701084406198%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7001596542/job/19044484443

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
bug已经fix，后续还要等添加log那个feat合进去

**Comment by aressu1985** [comment]
close
