### ISSUE TITLE
[Subtask]: ALL TPCC queries should have a parallelism of 1

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#13025]
### Parent Issue

#10729

### Detail of Subtask

TPCC queries should not need to run in parallel in many nodes (data parallelism should be 1).   
With #13024 , all TPCC queries should have one pipeline.  

Combine these two, *ALL* TPCC queries should run in exactly one pipeline, one instantiation.   In that case, TPCC queries does not need to start new go routine, just execute this one pipeline in the session goroutine.

This will resolve our pipeline number and scheduling craziness.

**Comment by ouyuanning** [comment]
等agg和hash table从batch移除后开始处理

**Comment by badboynt1** [comment]
加了日志之后，跑tpcc 1000仓1000并发，已经确认除了最后的验证语句以外，正常跑起来的全都是tp query
