### ISSUE TITLE
[Subtask]: Join/Union etc should not break pipeline

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#13024]
### Parent Issue

#10729

### Detail of Subtask

Operators with multiple children (JOIN, UNION/UNION ALL) should not break the pipeline.     In theory, shuffle is the only operator that breaks a plan to several pipelines.

**Comment by ouyuanning** [comment]
等agg和hash table从batch移除后处理

**Comment by badboynt1** [comment]
会议结论是，先不改动已有的broadcast/shuffle join，增加新的single join，语义是限定单并发。 实现树状的pipeline，没有任何打断。  依赖两个前置重构，一是将datasource从scope中移除，为此需要实现真正的table_scan,value_scan等等算子。  二是重构pipeline instructions这个数据结构，支持在compile时产生树状的pipeline。
hashmap/agg从batch中移除， 以及projection修改这些，不影响当前任务。

**Comment by badboynt1** [comment]
后续在https://github.com/matrixorigin/matrixone/issues/16542 这个issue里追踪

**Comment by badboynt1** [comment]
finished
