### ISSUE TITLE
[Bug]: streaming: json type read reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13049]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):07d71e8492cb03bf2cd24d80486b1a518c9aa8cb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"c1":'{"t1":"a"}'}
ddl:
create stream stream_17(c1 json )with(
    "type"='kafka',
    "topic"= 'test',
    "partion" = '1',
     "value"= 'json',
    "bootstrap.servers"='127.0.0.1:9092'   
)
select stream reported panic error:
<img width="948" alt="企业微信截图_92c04573-33f4-4268-812b-694f02499d5c" src="https://github.com/matrixorigin/matrixone/assets/113406637/75ca0f6c-e49a-4b1e-8506-711ce2f714d9">
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0:
runtime.goPanicIndex
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/container/bytejson.(*ByteJson).Unmarshal
	/Users/heni/test-envir/matrixone/pkg/container/bytejson/bytejson.go:91
github.com/matrixorigin/matrixone/pkg/container/types.DecodeJson
	/Users/heni/test-envir/matrixone/pkg/container/types/encoding.go:92
github.com/matrixorigin/matrixone/pkg/frontend.extractRowFromVec

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/commit/87b1ce95033cbaa6bb91cf8b378e8cb49848f0ca

Please verify

**Comment by heni02** [comment]
不再报panic错，但查询数据为NULL
commit id:c4b255cbd0ee319c50210706a94eaf5d6084aadf
<img width="630" alt="企业微信截图_54cf84a3-8d51-42e6-8fee-7c432cc8f26e" src="https://github.com/matrixorigin/matrixone/assets/113406637/6a3812f3-62da-42a2-9d58-0b6fd7cba353">

**Comment by gavinyue** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/54566980/56d4c425-7be3-426f-b1a4-0ae1466a2e3d)

这个问题是 测试数据是不对的。 

{"c1":'{"t1":"a"}'} 这个自己不是个valid json

必须用这个： {"c1": "{\"t1\":\"a\"}"}

**Comment by heni02** [comment]
confirm，closed
commit id：c4b255cbd0ee319c50210706a94eaf5d6084aadf
{"c1": "{\"t1\":\"a\"}"}
<img width="450" alt="企业微信截图_23bb212d-3294-4da9-a5d6-cfba7badf5db" src="https://github.com/matrixorigin/matrixone/assets/113406637/5cc9a562-e49d-4c4c-9b65-04c8762ade75">
