### ISSUE TITLE
[Bug]: streaming: decimal/double/float type read error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13042]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):07d71e8492cb03bf2cd24d80486b1a518c9aa8cb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

json:
{"c1":0.12,"c2":2.34,"c3":6.45,"c4":0.12,"c5":2.34,"c6":6.45}
stream ddl:
create stream stream_10(c1 decimal(10,3),c2 float(20), c3 double(53,30),c4 decimal,c5 float,c6 double)with(
 "type"='kafka',
 "topic"= 'test',
  "partion" = '1',
"value"= 'json',
  "bootstrap.servers"='127.0.0.1:9092'
 );

select stream result:
<img width="815" alt="企业微信截图_465a104d-2a4f-48a0-b9fa-7919461c190c" src="https://github.com/matrixorigin/matrixone/assets/113406637/af0b7c78-14c5-41ba-b009-dcc1a0916afe">

json :
{"c1":NULL,"c2":NULL,"c3":NULL,"c4":NULL,"c5":NULL"c6":NULL}
select stream:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/a0f7a9d3-6e98-4a70-a82c-8be52a86633d)

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/commit/87b1ce95033cbaa6bb91cf8b378e8cb49848f0ca

Please verify

**Comment by heni02** [comment]
有partition的话无法查出数据，已经新提单，无partition时数据读取正确
commit：c4b255cbd0ee319c50210706a94eaf5d6084aadf
![image](https://github.com/matrixorigin/matrixone/assets/113406637/89d453b5-1d88-4a7c-aa0e-5197c17f8c38)
