### ISSUE TITLE
[Bug]: summation(null) returns error

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#13058]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sql
mysql> select summation(null);
+-----------------+
| summation(null) |
+-----------------+
|            NULL |
+-----------------+

```

### Expected Behavior

```sql
mysql> select SUMMATION(NULL);
ERROR 20203 (HY000): invalid argument operator cast, bad value [ANY VECF32]

```

Thanks to @aressu1985  for finding this bug.

**Comment by aressu1985** [comment]
@arjunsk please check other funcs, like inner_product, l1_norm
mysql> select l1_norm(NULL);
ERROR 20203 (HY000): invalid argument operator cast, bad value [ANY VECF32]
mysql> select inner_product(NULL,NULL);
ERROR 20203 (HY000): invalid argument operator cast, bad value [ANY VECF32]

**Comment by arjunsk** [comment]
I have added BVT tests for all these cases: https://github.com/matrixorigin/matrixone/pull/13059/files#diff-7903ef5f5d698f39c723fb87d859042c3abc1d6d5a44a0ba31093419ca019c81R136

Once the PR is merged, this should work as expected.

**Comment by arjunsk** [comment]
the PR is merged to master. Kindly retest the same.

**Comment by aressu1985** [comment]
fixed
