### ISSUE TITLE
[Tech Request]: CN Upgrader versioning 

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#13066]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added?

Right now, we don't have versioning of [Upgrade changes](https://github.com/matrixorigin/matrixone/blob/138e7e8eb15421047ed1a8636daf2686d760dffe/pkg/cnservice/upgrader/upgrader.go#L158)

Everything is executed one after the other in a single thread. Though these individual upgrades are idempotent, we need to have some sort of `schema version table` to manage the version of change logs applied to mo internal tables.

### Why is this needed?

We need this to ensure
1. Idempotency
2. Smooth chaining of upgrades to avoid inconsistent database state. 1.0 -> 1.1, 1.1 -> 1.2 etc.

### Additional information

1. Need a design doc.
2. Similar to liquibase [changelog](https://docs.liquibase.com/concepts/tracking-tables/databasechangelog-table.html) table.

**Comment by zhangxu19830126** [comment]
dup with #13633

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been submitted. Please verify and test it

**Comment by arjunsk** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/9638314/65a07e35-763f-409c-a2d9-0d57b7b826f5)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/0a3c177b-410d-41f7-b4ab-8fa64364f68b)
