### ISSUE TITLE
[Bug]: internal error: panic interface conversion when executing min(SUMMATION()) and max(SUMMATION())

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13061]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3458fee439f5e44d6957a9f7fa4aa9369723e443
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select min(SUMMATION(vecf32_3)) from vtab32;
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is nil, not int64: 
runtime.panicdottypeE
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:3409
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:1844
github.com/matrixorigin/matrixone/pkg/
mysql> select max(SUMMATION(vecf32_3)) from vtab32;
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is nil, not int64: 
runtime.panicdottypeE
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:3409
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan
	/Users/sudong/Program/MatrixOrigin

mysql> select SUMMATION(vecf32_3),SUMMATION(vecf32_5) from vtab32;
+---------------------+---------------------+
| summation(vecf32_3) | summation(vecf32_5) |
+---------------------+---------------------+
|                NULL |                NULL |
|  1.9714266657829285 |                NULL |
|   33.89660960435867 |   4771.603164553642 |
|   837.3288311958313 |   9376.918968319893 |
+---------------------+---------------------+
4 rows in set (0.01 sec)

**Comment by arjunsk** [comment]
I am unable to replicate this issue for the commit: 3458fee439f5e44d6957a9f7fa4aa9369723e443

```sql
mysql> create table vtab32(id int, vecf32_3 vecf32(3), vecf32_5 vecf32(5));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into vtab32 values(1, NULL, NULL);
Query OK, 1 row affected (0.00 sec)

mysql> insert into vtab32 values(2, "[0.8166459, 0.66616553, 0.4886152]", NULL);
Query OK, 1 row affected (0.01 sec)

mysql> insert into vtab32 values(3, "[0.1726299, 3.2908857, 30.433094]", "[0.45052445, 2.1984527, 9.579752, 123.48039, 4635.894]");
Query OK, 1 row affected (0.00 sec)

mysql> insert into vtab32 values(4, "[8.560689, 6.790359, 821.9778]", "[0.46323407, 23.498016, 563.923, 56.076736, 8732.958]");
Query OK, 1 row affected (0.01 sec)

mysql> select SUMMATION(vecf32_3),SUMMATION(vecf32_5) from vtab32;
+---------------------+---------------------+
| summation(vecf32_3) | summation(vecf32_5) |
+---------------------+---------------------+
|                NULL |                NULL |
|  1.9714266657829285 |                NULL |
|   33.89660960435867 |   4771.603164553642 |
|   837.3288311958313 |   9376.918968319893 |
+---------------------+---------------------+
4 rows in set (0.00 sec)

mysql> select min(SUMMATION(vecf32_3)) from vtab32;
+--------------------------+
| min(summation(vecf32_3)) |
+--------------------------+
|       1.9714266657829285 |
+--------------------------+
1 row in set (0.00 sec)
```

Could you kindly provide me with the mo-dump of `vtab32` table? Also, do you see any difference in the SQL commands used in testing?

**Comment by arjunsk** [comment]
This issue occurs occasionally when used with aggFunction like min().

![image](https://github.com/matrixorigin/matrixone/assets/9638314/5c9f9192-95f7-4b25-bd76-a9245bb980e0)


The point of failure does seem to be related to vector operation. @zengyan1  could you kindly check this error message for the commit 3458fee439f5e44d6957a9f7fa4aa9369723e443 and see if it has already been resolved in any later PRs?

**Comment by arjunsk** [comment]
This issue occurs for AggFunction()
![image](https://github.com/matrixorigin/matrixone/assets/9638314/c851a54e-1515-46c4-81ff-f3014c647484)

**Comment by zengyan1** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
