### ISSUE TITLE
[Tech Request]: add ut test for create account in on transaction

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#13064]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
add ut test for create account in on transaction
```

**Comment by matrix-meow** [comment]
Hello @YANGGMM. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @YANGGMM. The bug issue in the BVT test code has not been removed,issues automatically open.
