### ISSUE TITLE
[Tech Request]: LockService support gracefully shutdown

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#13079]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Currently, when we are rolling upgrades, we get Lock Table changed or not found errors due to a lot of transaction failures in the locking service
```

### Describe the feature you'd like

Avoiding LockTable errors when rolling upgrades

**Comment by florashi181** [comment]
目标：升级时不再出现和locktable相关的错误，可完成。

**Comment by heni02** [comment]
@TangxingZhou 确认下mo-cloud每日update还有Lock Table changed or not found errors相关error吗？

**Comment by TangxingZhou** [comment]
v1.2.0-2842af107-2024-05-15

**Comment by LiSong0214** [comment]
我能做些什么？

**Comment by heni02** [comment]
和 @tianyahui-python 确认，目前mo-cloud升级时测试没有发现lock table相关错误，该feature关闭

**Comment by aressu1985** [comment]
done
