### ISSUE TITLE
[Bug]: streaming：select dynamic table return 0 row

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13073]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):be88e8ea481a3ea824acebe52cdee454f64f1e4e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="807" alt="企业微信截图_56d228ce-f831-43e3-b8b9-41a997a99a7d" src="https://github.com/matrixorigin/matrixone/assets/113406637/3d90fb8a-ab3e-4afd-a74c-b35d1e078262">
<img width="1487" alt="企业微信截图_7804cb55-c06b-48fb-ac39-9c972e45a7d4" src="https://github.com/matrixorigin/matrixone/assets/113406637/38d3385c-b2be-494a-a04c-e4ed4b600b2b">

json：
{"id": 200,"c1": "wear","c2": 0.1, "c3": "2024-01-01 12:08:05"}

ddl：
create  source stream_b(id int,c1 varchar(25),c2 decimal,c3 datetime)
with(
 "type"='kafka',
 "topic"= 'test',
 "value"= 'json',
"bootstrap.servers"='127.0.0.1:9092'
);
create dynamic table dt as select * from stream_b;

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/commit/87b1ce95033cbaa6bb91cf8b378e8cb49848f0ca

Please verify

**Comment by gavinyue** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/54566980/18401fe5-6fc4-424b-bf83-c486e5545246)


本地试过了， 没有问题啊

**Comment by heni02** [comment]
我试了下必须指定db名才能查到数据，需要修这个问题
<img width="854" alt="企业微信截图_65d4087c-2e75-47dc-8da7-5a831f2c58b6" src="https://github.com/matrixorigin/matrixone/assets/113406637/3db65155-8375-4761-ad15-9d92f984b874">

**Comment by gavinyue** [comment]
在dt创建的时候， 数据库名没有保存好。  

预计明天解决

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13348

**Comment by heni02** [comment]
confirm,closed
commit id:09b923d8ca3ecef29c7ec6a6b80eb2c63e17cb9d
<img width="1140" alt="企业微信截图_cbf64a2b-271b-4ba5-b318-02437c94e07d" src="https://github.com/matrixorigin/matrixone/assets/113406637/5cc72c81-3267-48c1-9c31-fe15c2a4b2f6">
<img width="758" alt="企业微信截图_6ba83c6d-8e51-4592-816c-807c4b56b158" src="https://github.com/matrixorigin/matrixone/assets/113406637/3f95ed43-3365-49e9-94c5-8326ee6cca36">
<img width="801" alt="企业微信截图_e7414be9-1705-48f8-be28-1271f30c89f4" src="https://github.com/matrixorigin/matrixone/assets/113406637/5ab14978-699f-4d72-a25d-8a6f59af565e">
