### ISSUE TITLE
[Bug]: result of cosine_similarity is not the same when the two paras are equal to each other

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13084]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3458fee439f5e44d6957a9f7fa4aa9369723e443
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select cosine_similarity(vecf32_3,vecf32_3), cosine_similarity(vecf32_5,vecf32_5) from vtab32;
+---------------------------------------+---------------------------------------+
| cosine_similarity(vecf32_3, vecf32_3) | cosine_similarity(vecf32_5, vecf32_5) |
+---------------------------------------+---------------------------------------+
|                                  NULL |                                  NULL |
|                                     1 |                                  NULL |
|                                     1 |                                     1 |
|                                     1 |                    0.9999999999999998 |
+---------------------------------------+---------------------------------------+
4 rows in set (0.00 sec)

mysql> select cosine_similarity(vecf64_3,vecf64_3), cosine_similarity(vecf64_5,vecf64_5) from vtab64;
+---------------------------------------+---------------------------------------+
| cosine_similarity(vecf64_3, vecf64_3) | cosine_similarity(vecf64_5, vecf64_5) |
+---------------------------------------+---------------------------------------+
|                                  NULL |                                  NULL |
|                    0.9999999999999999 |                                  NULL |
|                    0.9999999999999998 |                                     1 |
|                                     1 |                    0.9999999999999999 |
+---------------------------------------+---------------------------------------+
4 rows in set (0.01 sec)

### Steps to Reproduce

```Markdown
create table vtab32(id int primary key auto_increment,`vecf32_3` vecf32(3),`vecf32_5` vecf32(5));
create table vtab64(id int primary key auto_increment,`vecf64_3` vecf64(3),`vecf64_5` vecf64(5));

insert into vtab32(vecf32_3,vecf32_5) values("[0.8166459,NULL,0.4886152]",NULL);
insert into vtab32(vecf32_3,vecf32_5) values(NULL,NULL);
insert into vtab32(vecf32_3,vecf32_5) values("[0.8166459,0.66616553,0.4886152]",NULL);
insert into vtab32(vecf32_3,vecf32_5) values("0.1726299,3.29088557,30.4330937","0.1726299,3.29088557,30.4330937");
insert into vtab32(vecf32_3,vecf32_5) values ("[0.1726299,3.29088557,30.4330937]","[0.45052445,2.19845265,9.579752,123.48039162,4635.89423394]");
insert into vtab32(vecf32_3,vecf32_5) values ("[8.5606893,6.7903588,821.977768]","[0.46323407,23.49801546,563.9229458,56.07673508,8732.9583881]");
insert into vtab64(vecf64_3,vecf64_5) values("[0.8166459,NULL,0.4886152]",NULL);
insert into vtab64(vecf64_3,vecf64_5) values(NULL,NULL);
insert into vtab64(vecf64_3,vecf64_5) values("[0.8166459,0.66616553,0.4886152]",NULL);
insert into vtab64(vecf64_3,vecf64_5) values ("[8.5606893,6.7903588,821.977768]","[0.46323407,23.49801546,563.9229458,56.07673508,8732.9583881]");
insert into vtab64(vecf64_3,vecf64_5) values ("[0.9260021,0.26637346,0.06567037]","[0.45756745,65.2996871,321.623636,3.60082066,87.58445764]");
```

**Comment by arjunsk** [comment]
Will be fixed in this PR: https://github.com/matrixorigin/matrixone/pull/13101

**Comment by arjunsk** [comment]
Waiting for @aunjgr 's approval.

**Comment by arjunsk** [comment]
The pr is merged to master. Kindly retest.

**Comment by aressu1985** [comment]
fixed
mysql> select cosine_similarity(vecf32_3,vecf32_3), cosine_similarity(vecf32_5,vecf32_5) from vtab32;
+---------------------------------------+---------------------------------------+
| cosine_similarity(vecf32_3, vecf32_3) | cosine_similarity(vecf32_5, vecf32_5) |
+---------------------------------------+---------------------------------------+
|                                  NULL |                                  NULL |
|                                     1 |                                  NULL |
|                                     1 |                                     1 |
|                                     1 |                                     1 |
+---------------------------------------+---------------------------------------+
4 rows in set (0.01 sec)

mysql> select cosine_similarity(vecf64_3,vecf64_3), cosine_similarity(vecf64_5,vecf64_5) from vtab64;
+---------------------------------------+---------------------------------------+
| cosine_similarity(vecf64_3, vecf64_3) | cosine_similarity(vecf64_5, vecf64_5) |
+---------------------------------------+---------------------------------------+
|                                  NULL |                                  NULL |
|                                     1 |                                  NULL |
|                                     1 |                                     1 |
|                                     1 |                                     1 |
+---------------------------------------+---------------------------------------+
4 rows in set (0.02 sec)

**Comment by aressu1985** [comment]
fixed
