### ISSUE TITLE
[Bug]: tpch test on eks report 'use of closed network connection'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13090]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3a4dc24224ce5f24254c365c063d3773de1fd810
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1387" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ebe96d82-bedd-4455-a47a-185a773b856b">

loki: http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/explore?panes=%7B%221JX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

workflow: https://github.com/matrixorigin/mo-auto-test/actions/runs/7029026122/job/19126036458

**Comment by badboynt1** [comment]
2023-11-29 16:25:16.763        
{"level":"ERROR","time":"2023/11/29 08:25:16.763749 +0000","name":"cn-service.txn-client.txn-client","caller":"morpc/client.go:439","msg":"create backend failed","uuid":"65666637-3064-3836-3963-333437306139","backend":"mo-tpch-dn-0.mo-tpch-dn-headless.mo-tpch.svc:41010","error":"no available backend"}
2023-11-29 16:25:16.763        
{"level":"ERROR","time":"2023/11/29 08:25:16.763736 +0000","caller":"morpc/client.go:473","msg":"error: no available backend"}
2023-11-29 16:25:16.763        
{"level":"ERROR","time":"2023/11/29 08:25:16.763708 +0000","name":"cn-service.txn-client.txn-client","caller":"morpc/client.go:439","msg":"create backend failed","uuid":"65666637-3064-3836-3963-333437306139","backend":"mo-tpch-dn-0.mo-tpch-dn-headless.mo-tpch.svc:41010","error":"no available backend"}



2023-11-29 16:25:16.763        
{"level":"ERROR","time":"2023/11/29 08:25:16.763666 +0000","caller":"morpc/client.go:473","msg":"error: no available backend"}

日志里出现了一些这个错误，不知道是否与这个有关。

**Comment by nnsgmsone** [comment]
这个是因为ctx超时，导致链接被关闭，然后出现了这个错误。。。日志如下:
```
2023-11-29 15:56:24.382	
2023/11/29 07:56:24.381970 +0000 ERROR session handle failed, close this session {"name": "pipeline-server", "listen-addresses": "[0.0.0.0:6002]", "session-id": 1474, "addr": "10.0.166.12:55486", "error": "context deadline exceeded"}
```
context为啥会超时。。需要找张旭对一下

**Comment by nnsgmsone** [comment]
此处的context是直接取的sql执行的context，这里的超时时间应该不对，默认的应该是24H，不应该这么快就超时了。

**Comment by sukki37** [comment]
@daviszhen please assist in debugging this issue, thank you.

**Comment by daviszhen** [comment]
1，初步看是rpc 响应超时。原因还要继续看。

<img width="2480" alt="企业微信截图_97f3fa2b-5674-42cd-9dde-3a34b8d7981d" src="https://github.com/matrixorigin/matrixone/assets/60595215/16e96e73-ca1f-4502-b347-4128c523756f">

http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/explore?panes=%7B%221JX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-tpch%5C%22,%20pod%3D%5C%22mo-tpch-tp-cn-62jbz%5C%22%7D%20%7C%3D%20%6010.0.166.12:55486%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701244560000%22,%22to%22:%221701244619000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by loveRhythm1990** [comment]
此时间段相关 pod 监控
http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&from=1701242946000&to=1701247801000&var-datasource=default&var-cluster=&var-namespace=mo-tpch&var-pod=mo-tpch-tp-cn-62jbz

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/3cd68cd8-c42c-4ee4-8670-893e1489a6d3)

http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&from=1701243540000&to=1701244799000&var-datasource=default&var-cluster=&var-namespace=mo-tpch&var-pod=mo-tpch-tp-cn-62jbz

**Comment by daviszhen** [comment]
期间会有连接断开
![image](https://github.com/matrixorigin/matrixone/assets/60595215/4bfa474d-6380-4ab7-9161-629e056cb6a1)

http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/explore?panes=%7B%221JX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-tpch%5C%22,%20pod%3D%5C%22mo-tpch-tp-cn-62jbz%5C%22%7D%20%7C%3D%20%60session%20read%20failed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701243000000%22,%22to%22:%221701244619000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
> 此处的context是直接取的sql执行的context，这里的超时时间应该不对，默认的应该是24H，不应该这么快就超时了。

不是request的ctx超时。是发送前额外加的10s超时。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/272ee85b-fa67-401a-a599-62449b0edd1d)

现象如图。

<img width="2480" alt="企业微信截图_97f3fa2b-5674-42cd-9dde-3a34b8d7981d" src="https://github.com/matrixorigin/matrixone/assets/60595215/bcae3a06-6eb9-403f-bda5-63f1f65a481f">

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/12564
和这个issue似乎是同一个问题

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/7191199890/job/19585677096
再次复现，依然是q8
但是只有eks环境有这个问题，tke环境跑不出这个问题
![image](https://github.com/matrixorigin/matrixone/assets/112734932/008151f2-5197-4b2d-8a6b-90c21fc200b9)

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/7270317567/job/19811979135
再次复现，依然是q8

**Comment by daviszhen** [comment]
```
{"level":"ERROR","time":"2023/12/20 06:25:36.525808 +0000","name":"cn-service.frontend","caller":"frontend/util.go:510","msg":"query trace status","uuid":"34303165-3661-3461-3731-336439343935","connection_id":228,"statement":"select\n    o_year,\n    (sum(case\n        when nation = 'ARGENTINA' then volume\n        else 0\n    end) / sum(volume)) as mkt_share\nfrom\n    (\n        select\n            extract(year from o_orderdate) as o_year,\n            l_extendedprice * (1 - l_discount) as volume,\n            n2.n_name as nation\n        from\n            part,\n            supplier,\n            lineitem,\n            orders,\n            customer,\n            nation n1,\n            nation n2,\n            region\n        where\n            p_partkey = l_partkey\n            and s_suppkey = l_suppkey\n            and l_orderkey = o_orderkey\n            and o_custkey = c_custkey\n            and c_nationkey = n1.n_nationkey\n            and n1.n_regionkey = r_regionkey\n            and r_name = 'AMERICA'\n            and s_nationkey = n2.n_nationkey\n            and o_orderdate between date '1995-01-01' and date '1996-12-31'\n            and p_type = 'ECONOMY BURNISHED TIN'\n    ) as all_nations\ngroup by\n    o_year\norder by\n    o_year","status":"fail","error":"write tcp4 10.0.155.221:6002->10.0.158.186:46760: use of closed network connection","span":{"trace_id":"c56646ad-af23-05ac-dc31-68ea8809cf43","span_id":"d9bff8732972803b"},"session_info":"connectionId 228|10.0.174.62:39020|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 621318|89e39b33-9f00-11ee-aa24-ee652f059217","session_id":"89e39b33-9f00-11ee-aa24-ee652f059217","statement_id":"89e4ebe9-9f00-11ee-aa24-ee652f059217"}

```

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/6cbea9e0-81b5-48cc-b5df-1911fdf12bba)


http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/explore?panes=%7B%221JX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-tpch%5C%22%7D%20%7C%3D%20%60connectionId%20228%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703050320000%22,%22to%22:%221703055239000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
依然是写rpc 超时。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/4ff4b0ef-17d5-40dd-9925-0d7494c9122d)


http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/explore?panes=%7B%221JX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-tpch%5C%22%7D%20%7C~%20%6010.0.158.186:46760%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703050320000%22,%22to%22:%221703055239000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
http://a32e0b4d7525042c2b28e6bd8d950a40-514639438.us-west-2.elb.amazonaws.com/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-tpch&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki&from=1703050320000&to=1703055239000

**Comment by daviszhen** [comment]
分析了前天的trace问题。

有点发现 有很多cnservice的routine卡住。
<img width="1202" alt="企业微信截图_5c07863a-3a94-4383-938f-971a9608da74" src="https://github.com/matrixorigin/matrixone/assets/60595215/71867620-8078-4665-adf6-e44e795dc363">

<img width="721" alt="企业微信截图_7eec281c-d2e7-4a92-a741-b1aa714f5488" src="https://github.com/matrixorigin/matrixone/assets/60595215/63a38fde-c95e-4ebe-b01f-5f357f91e755">

<img width="1445" alt="企业微信截图_1b17e0ae-caea-4cb9-bd67-84ad95db682e" src="https://github.com/matrixorigin/matrixone/assets/60595215/d9b73958-47c9-4cdc-b5d6-7e4078a40161">

**Comment by badboynt1** [comment]
彻底解决这个问题，需要实现基于消息的控制流。在build端阻塞时，probe端不能通过tpc发送数据。
依赖https://github.com/matrixorigin/matrixone/issues/11824

**Comment by badboynt1** [comment]
现在这个问题不通过控制流来解决，而是通过重构stream，在cn之间复用tcp连接来解决。
https://github.com/matrixorigin/matrixone/pull/15448  在这个pr之后应该就没问题了
@zhangxu19830126

**Comment by zhangxu19830126** [comment]
这个应该是通过你之前的[#206](https://github.com/badboynt1/matrixone/pull/206/files) 来解决

**Comment by badboynt1** [comment]
main分支上已经实现了shuffle join的流控以及rpc复用tcp连接。应该不会再有这个问题了
