### ISSUE TITLE
[Tech Request]: Handle errors from CN Upgrader

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#13095]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added?

Right now, we are ignoring the errors thrown by CN Upgrader [here](https://github.com/arjunsk/matrixone/blob/179582e8510c1f33977f5992ac0c0e36311d108f/pkg/cnservice/server_task.go#L138) 

However, the ideal behavior should be,
1. retry 3 times in case of failure
2. if still having a failure, panic and let the user know that the upgrade is not successful.

### Why is this needed?

If we init the database without a successful Upgrade, we could end up in an inconsistent [state](https://github.com/matrixorigin/matrixone/issues/12262#issuecomment-1829483269).

**Comment by qingxinhome** [comment]
The upgrade function has been implemented and submitted. Please verify and test it

**Comment by arjunsk** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/9638314/3f7126e0-22fe-4dfb-b5c3-f3fc30d5d360)
