### ISSUE TITLE
[Bug]: error while casting NULL to FLOAT when loading data to vector type with NULL value

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13107]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3458fee439f5e44d6957a9f7fa4aa9369723e443
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> load data infile '/Users/sudong/Program/MatrixOrigin/test/resource/vector.csv' into table vtab32_1;
ERROR 20101 (HY000): internal error: error while casting NULL to FLOAT

DDL:
create table vtab32_1(id int primary key auto_increment,`vecf32_3` vecf32(3),`vecf32_5` vecf32(5));

csv file:
\N,"[0.8166459,NULL,0.4886152]",\N
\N,\N,\N
\N,"[0.8166459,0.66616553,0.4886152]",\N
\N,"[0.1726299,3.29088557,30.4330937]","[0.45052445,2.19845265,9.579752,123.48039162,4635.89423394]"
\N,"[8.5606893,6.7903588,821.977768]","[0.46323407,23.49801546,563.9229458,56.07673508,8732.9583881]"

**Comment by arjunsk** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/9638314/1321b9a4-8dd7-4e92-982c-4d23140a868b)


Hi @aressu1985 , we don't support NULL inside the vector.

"[0.8166459,NULL,0.4886152]" is invalid.

**Comment by aressu1985** [comment]
closed
