### ISSUE TITLE
[Bug]: the precision lost when loading data to table with vector type

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13108]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3458fee439f5e44d6957a9f7fa4aa9369723e443
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> load data infile '/Users/sudong/Program/MatrixOrigin/test/resource/vector.csv' into table vtab32_1;
Query OK, 2 rows affected (0.03 sec)

mysql> select * from vtab32_1;
+------+-----------------------------------+--------------------------------------------------------+
| id   | vecf32_3                          | vecf32_5                                               |
+------+-----------------------------------+--------------------------------------------------------+
|    1 | [0.1726299, 3.2908857, 30.433094] | [0.45052445, 2.1984527, 9.579752, 123.48039, 4635.894] |
|    2 | [8.560689, 6.790359, 821.9778]    | [**0.46323407, 23.498016, 563.923, 56.076736, 8732.958]**  |
+------+-----------------------------------+--------------------------------------------------------+
2 rows in set (0.03 sec)

csv file:
\N,"[0.1726299,3.29088557,30.4330937]","[0.45052445,2.19845265,9.579752,123.48039162,4635.89423394]"
\N,"[8.5606893,6.7903588,821.977768]","[**0.46323407,23.49801546,563.9229458,56.07673508,8732.9583881**]"

**Comment by arjunsk** [comment]
This is because you are inserting a double value to a float type (ie vecf32) column.

A similar example is 

```sql
create table t1(a float);
insert into t1 values(0.46323407);
insert into t1 values(23.49801546);
insert into t1 values(563.9229458);
insert into t1 values(8732.9583881);
mysql> select * from t1;
+------------+
| a          |
+------------+
| 0.46323407 |
|  23.498016 |
|    563.923 |
|   8732.958 |
+------------+

```

To maintain the precision of input data, you can use vecf64 (double)
![image](https://github.com/matrixorigin/matrixone/assets/9638314/dd083578-7a86-42c4-86e8-4d53b9659564)

**Comment by aressu1985** [comment]
closed
