### ISSUE TITLE
[Bug]: [date 11.29]standalone regression: cn service is not ready

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13115]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0b77b3d2bfb3b5c61ada48acae07c1a5a363d26b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7033694970/job/19140252853
<img width="1428" alt="企业微信截图_faa2d44e-1991-48a5-a5c8-97ce60a89dd7" src="https://github.com/matrixorigin/matrixone/assets/113406637/d27984e7-243a-4b54-a966-9978b1917aed">

从报错的时间看128内存使用情况，没有超出内存，/var/log/message也没有被kill的信息，排除oom的情况

128 mo log：
[molog.tar.gz](https://github.com/matrixorigin/matrixone/files/13508025/molog.tar.gz)

**Comment by volgariver6** [comment]
pr committed

**Comment by volgariver6** [comment]
fixed

**Comment by heni02** [comment]
最近回归没有出现该错误，先关闭
