### ISSUE TITLE
[Bug]: [date 11.29 ]tke regression: sysbench random points test reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13119]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0b77b3d2bfb3b5c61ada48acae07c1a5a363d26b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7034068727/job/19141248702
<img width="1431" alt="企业微信截图_476eec00-b7ad-489e-9ff6-e771404835d1" src="https://github.com/matrixorigin/matrixone/assets/113406637/4aed264b-bba5-4338-a4c4-fc94d74a1ced">
FATAL: mysql_drv_query() returned error 20101 (internal error: panic interface conversion: client.Workspace is nil, not *disttae.Transaction: 
runtime.panicdottypeE
	/usr/local/go/src/runtime/iface.go:262
runtime.panicdottypeI
	/usr/local/go/src/runtime/iface.go:272
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).getTransaction
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:483
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).GetRelationById
	/go/src/github.com/matrixorigin/matrixone/pkg/vm) for query 'CREATE INDEX k_9 ON sbtest9(k)'
FATAL: `sysbench.cmdline.call_command' function failed: ./oltp_common.lua:229: SQL error, errno = 20101, state = 'HY000': internal error: panic interface conversion: client.Workspace is nil, not *disttae.Transaction: 
runtime.panicdottypeE
	/usr/local/go/src/runtime/iface.go:262
runtime.panicdottypeI
	/usr/local/go/src/runtime/iface.go:272
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).getTransaction
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:483
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).GetRelationById
	/go/src/github.com/matrixorigin/matrixone/pkg/vm

mo log:
http://132.232.112.34:30088/explore?panes=%7B%22WQ7%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231129%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

sysbench 100w 1000w测试都有这个问题，应该是必现
sysbenh命令：
sysbench  --mysql-host=172.16.127.122 --mysql-port=6001 --mysql-user=dump --mysql-password=111 select_random_points.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=30 --report-interval=10  --auto_inc=off prepare
sysbench  --mysql-host=172.16.127.122 --mysql-port=6001 --mysql-user=dump --mysql-password=111  --db-ps-mode=disable  select_random_points.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=300 --report-interval=10  --auto_inc=off --range_selects=off --point_selects=1 run

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2023/11/30 01:17:17.745039 +0000","name":"cn-service.frontend","caller":"frontend/util.go:510","msg":"query trace status","uuid":"62366139-3565-6663-6334-373962366139","connection_id":49631,"statement":"CREATE INDEX k_9 ON sbtest9(k)","status":"fail","error":"internal error: panic interface conversion: client.Workspace is nil, not *disttae.Transaction: \nruntime.panicdottypeE\n\t/usr/local/go/src/runtime/iface.go:262\nruntime.panicdottypeI\n\t/usr/local/go/src/runtime/iface.go:272\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).getTransaction\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:483\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).GetRelationById\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:241\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.hasNewVersionInRange\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:774\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:453\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:207\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:116\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:88\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:36\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:77\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:91\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:88\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:131\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","span":{"trace_id":"6085230b-a93f-f4b9-30e1-eeda5c89da85","span_id":"ae31af485ccbeb75"},"session_info":"connectionId 49631|10.130.46.109:60238|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 17158389|15dfcf6e-8f1e-11ee-9785-a28a49401d13","session_id":"15dfcf6e-8f1e-11ee-9785-a28a49401d13","statement_id":"32e30d3f-8f1e-11ee-9785-a28a49401d13"}

**Comment by YANGGMM** [comment]
http://132.232.112.34:30088/explore?panes=%7B%22WQ7%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231129%5C%22%7D%20%7C%3D%20%60CREATE%20INDEX%20k_9%20ON%20sbtest9%28k%29%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701306230000%22,%22to%22:%221701309886000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by heni02** [comment]
每次在create 索引时候报panic

**Comment by YANGGMM** [comment]
hello @arjunsk , it may related to index, can you help to solve this

**Comment by arjunsk** [comment]
Duplicate of https://github.com/matrixorigin/matrixone/issues/12810

@m-schen kindly look into this.

**Comment by m-schen** [comment]
又发生该问题的话，就和重连的race没啥关系了。需要进一步确定问题。

**Comment by arjunsk** [comment]
This issue occurs in 1.1-dev resulting in unexpected behaviour.

https://github.com/matrixorigin/MO-Cloud/issues/1881#issuecomment-1833604145

**Comment by m-schen** [comment]
create index的流程有一步是通过内部执行器执行 insert into table select function(xxx) from t;
当该表数据量比较大时，该查询会被发送到远端节点执行，大概率是因为在远端跑的查询所对应的txn operator由于是通过snapshot重新构建的，但没有赋予workspace，因此导致了问题。

**Comment by m-schen** [comment]
已修复该问题。总共有两个相关pr，目前main分支上已完全合并，1.1-dev还在devops流程中。

可验证。

**Comment by heni02** [comment]
confirm，closed
commit：6370e983b1d270ff041f67f1abd5c51a245b119d
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7116706746/job/19391568966
<img width="1440" alt="企业微信截图_19db5ba2-d444-41df-af46-3d5af33e7f7c" src="https://github.com/matrixorigin/matrixone/assets/113406637/deaa2ef7-fb3e-44a0-a0dd-52ad6f5a0425">
