### ISSUE TITLE
[Bug]: `approx_count` error during bvt test with race enabled

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13133]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.1-dev, 461193d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7041645633/job/19164955745
<img width="1314" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/083f8982-ef2f-4be3-91ae-a545ca0a2f31">

[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13511067/multi-cn-e2e-with-race-linux-x86-reports.zip)

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7046745646/job/19179630428

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
本周请假

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
计划修复S-1后开始处理这个issue

**Comment by zengyan1** [comment]
修复S-1后开始处理这个issue

**Comment by zengyan1** [comment]
https://github.com/matrixorigin/matrixone/issues/12993, count(*) 优化完成后，approx_count可以直接改写为count

**Comment by zengyan1** [comment]
count(*)优化仍需修改，合入后可解决

**Comment by zengyan1** [comment]
https://github.com/matrixorigin/matrixone/pull/14774 已合入

**Comment by zengyan1** [comment]
观察中，未复现https://github.com/matrixorigin/matrixone/actions/workflows/merge-trigger-standalone.yaml

**Comment by zengyan1** [comment]
近期回归未复现
