### ISSUE TITLE
[Bug]: mo-data is not compatible between branches

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#13149]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):385fa736e36089458f38
- Hardware parameters:
- OS type:mac/ubuntu
- Others:

背景是检验 MOC#1574 的问题有无得到解决

用main导入数据
 -> 用我的分支进行验证
  -> 测完之后想再要对比验证一下main, 然后发现启动不了.

如果需要mo-data的话, 请联系我.
```

我的分支
https://github.com/jensenojs/matrixone/tree/fuzzyFilter
对应commit是`198f4e33241f4aeb5e2bbd192e04da01a817f7c2`

### Actual Behavior

<img width="1165" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/411e8c20-0a19-488a-94ff-8f8091ac0e98">

**Comment by LeftHandCold** [comment]
用main导入数据
 -> 用我的分支进行验证
  -> 测完之后想再要对比验证一下main, 然后发现启动不了.

用旧版本的 main导入（10月份的代码）数据，再用新版本的测试代码写入数据，再回到就旧版本的main，出现兼容性问题是正常的，目前旧版本代码兼容不了新版本代码产生的数据。

**Comment by jensenojs** [comment]
是我的main没更新
