### ISSUE TITLE
[Bug]: The same SQL is slower after executing several times

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13142]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-461193df
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Please check the detail in https://github.com/matrixorigin/MO-Cloud/issues/1868

### Expected Behavior

The same SQL takes approximately the same amount of time to execute

### Steps to Reproduce

```Markdown
Refer to https://github.com/matrixorigin/MO-Cloud/issues/1868
```

**Comment by zengyan1** [comment]
修复中

**Comment by zengyan1** [comment]
修复中

**Comment by zengyan1** [comment]
修复中

**Comment by zengyan1** [comment]
修复中

**Comment by zengyan1** [comment]
本周请假

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
可能被https://github.com/matrixorigin/matrixone/pull/14136  修复，还需复测

**Comment by zengyan1** [comment]
<img width="300" alt="企业微信20240122-151736@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/2f6b276f-49f9-4d86-8426-cce1d1e31908">

<img width="289" alt="企业微信20240122-151941@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/886ed99d-f7a4-4406-ab9d-25406c8f1827">

**Comment by zengyan1** [comment]
以上是本地复测结果，分别是向包含一列自增列的空表和1亿行的表中一次性插入9500行数据
