### ISSUE TITLE
[Bug]: `ERROR: ExpectedEOB` returned when executing sql

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13151]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-461193df
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
SELECT relname AS `name`, mo_table_rows(reldatabase, relname) AS `rows`, mo_table_size(reldatabase, relname) AS `size`, if (role_name IS NULL, '-', role_name) AS `owner`, mo_tables.created_time AS created FROM mo_catalog.mo_tables LEFT JOIN mo_catalog.mo_role ON mo_catalog.mo_tables.owner=role_id WHERE relkind IN ('r','e','cluster') AND reldatabase='bi_stock';
ERROR: ExpectedEOB
```

### Expected Behavior

Query succeeds

### Steps to Reproduce

```Markdown
Run the SQL with dump user in dev cluster
```

**Comment by DanielZhangQD** [comment]
Log:
http://47.96.110.240/explore?panes=%7B%22jhL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60ExpectedEOB%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by gouhongshen** [comment]
如果 `ExpectedEOB` 确实发生在 `mo_table_size` or `mo_table_size` 函数中，那么出问题的地方应该在这里：

<img width="1093" alt="截屏2023-12-01 15 52 12" src="https://github.com/matrixorigin/matrixone/assets/26336316/5deadee7-7912-4dc6-8375-c4f8ca1b962a">

|
|

<img width="1332" alt="截屏2023-12-01 15 53 28" src="https://github.com/matrixorigin/matrixone/assets/26336316/a28d37dd-91ed-45df-bdc0-5931afe829cb">

**Comment by gouhongshen** [comment]
发现一个之前的 EOB 问题，也出在这里：#12149

**Comment by gouhongshen** [comment]
一般来说，`metadata scan` 和 `mo_table_xxx` 作用于不存在的 database 的时候，会报这个错误

@DanielZhangQD 确定一下语句中 database 真的存在吗

**Comment by gouhongshen** [comment]
有部分是因为 database 不存在：
|
|
<img width="1752" alt="截屏2023-12-01 17 55 53" src="https://github.com/matrixorigin/matrixone/assets/26336316/8ae39494-032b-4cd4-9d90-e4fc887dc592">

**Comment by gouhongshen** [comment]
暂时没有思路，在修 `show  accounts` 相关的 bug

**Comment by gouhongshen** [comment]
发现在别的地方也出现了：
http://121.43.41.174/explore?panes=%7B%22P8r%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22%7D%20%7C~%20%60ExpectedEOB%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1764" alt="截屏2023-12-13 19 19 37" src="https://github.com/matrixorigin/matrixone/assets/26336316/4c186647-a9c2-4bfb-9a41-cac00bfa2d02">

**Comment by gouhongshen** [comment]
加了日志等复现

**Comment by gouhongshen** [comment]
等复现

**Comment by gouhongshen** [comment]
原因已经找到, 考虑如下的 SQL:

```
select dbName, count(*) as tblCnt, sum(tblSize) / (1024 * 1024.0) as db_size_in_mb  
from (  
         select reldatabase as dbName, mo_table_size(reldatabase, relname) as tblSize  
         from 
			mo_catalog.mo_tables  left join mo_catalog.mo_database  
         on reldatabase_id = dat_id
		 where relkind in 
			('r', 'cluster', 'e') and 
			mo_catalog.mo_tables.account_id = ( select current_account_id() as cur_acc_id)
     ) 
group by dbName
order by db_size_in_mb;
```

这条SQL尝试一次性统计该租户下各个 db 的大小和 table 数量。

当前的实现中，处理该条语句时，如果发现其中的 table 是 cluster table，就会切换成 system account 去查询相关信息，但是却在查询后忘记恢复初始的 account。这样，后续的属于该租户的，不属于 cluster table 的 table 就无法被找到，因为 account id 已经发生了变化，在查找没有匹配。

**Comment by gouhongshen** [comment]
@heni02 the PR has merged, please confirm it.

**Comment by aressu1985** [comment]
test done
