### ISSUE TITLE
[Bug]: str_to_date函数第二个参数不支持表达式

### ISSUE THREAD

**Issue by gaoy121** [matrixorigin/matrixone#13189]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

在MO整合永洪BI工具时，BI生成了如下SQL语句：
SELECT str_to_date('2008-01-01',replace(replace(replace(replace(replace(replace(replace('yyyy-MM-dd','a','%p'),'ss','%s'),'mm','%i'),'HH','%H'),'yyyy','%Y'),'dd','%d'),'MM','%m')) AS LONG_COL_0
FROM yonghong.strtdate
执行后报错，format参数不支持表达式，报错如下：
invalid argument to_date format, bad value not constant

**Comment by dengn** [comment]
fixed. @gaoy121 please close this issue.
