### ISSUE TITLE
[Bug]: 用户态查询statement_cu信息报错表不存在。

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#13186]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):842654e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

使用非dump用户查询如下语句：
/* cloud_nonuser */ SELECT attname AS name, mo_show_visible_bin(atttyp,3) AS data_type, replace(mo_table_col_max(att_database,att_relname,attname),'\\0', '') AS `maximum`,  mo_table_col_min(att_database,att_relname,attname) as minimum from mo_catalog.mo_columns where att_database='mo_catalog' and att_relname='statement_cu' and attname NOT IN  ('__mo_rowid', '__mo_cpkey_col', '__mo_fake_pk_col') ORDER BY attnum;
报错[42000][1064] SQL parser error: table "statement_cu" does not exist

### Expected Behavior

能够查询到信息

### Steps to Reproduce

```Markdown
阿里云环境，稳定复现。
```

**Comment by LiSong0214** [comment]
1.0.1 需要进

**Comment by aressu1985** [comment]
<img width="1402" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/71fa9082-3770-4a00-8c99-701444181e56">

<img width="1204" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/886f8288-7aa1-4f83-85e0-fd827222ba79">

**Comment by aressu1985** [comment]
fixed
