### ISSUE TITLE
[Bug]: statement_info的status字段和exec_plan中的执行结果不同，一个成功一个失败。

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#13197]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):461193df
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

阿里云dev环境，statement_info表中status字段和exec_plan中的执行结果不同，一个成功一个失败。
statement_id: fd3e191f-9027-11ee-a7bc-f66e4031d343
查询SQL：/* cloud_nonuser */ SELECT * FROM `system`.`statement_info` WHERE statement_id='fd3e191f-9027-11ee-a7bc-f66e4031d343' ORDER BY response_at DESC LIMIT 1;
结果：
```
fd3e191f-9027-11ee-a7bc-f66e4031d343,014b445b-d34f-4e38-a5c8-2feab569caa4,e041fc0d-9027-11ee-a7bc-f66e4031d343,ba537a2b_43e7_4a2c_a6fe_b945278ef41a,admin,172.20.6.3:44572,bi_stock,"SELECT SAMPLE(ts_code, 100 ROWS) from mixed_daily","","",32636564-6233-3363-6264-643933613966,CN,2023-12-01 08:59:52.188689000,2023-12-01 09:24:20.499794000,1468311105303,Success,0,"","{""steps"":null,""code"":1105,""message"":""internal error: Unsupported node type when plan is serialized to json"",""success"":false,""uuid"":""fd3e191f-9027-11ee-a7bc-f66e4031d343"",""NewPlanStats"":{""ParseDuration"":0,""PlanDuration"":0,""CompileDuration"":0,""ExecutionDuration"":0,""ParseStartTime"":""0001-01-01T00:00:00Z"",""PlanStartTime"":""0001-01-01T00:00:00Z"",""CompileStartTime"":""0001-01-01T00:00:00Z"",""ExecutionStartTime"":""0001-01-01T00:00:00Z"",""ExecutionEndTime"":""0001-01-01T00:00:00Z""}}
",3883500000,93204000000,"[3,11734397984553,186408038400.000,0,1,11271,2]",Select,DQL,2,cloud_user_sql,0,800

```

### Expected Behavior

两者保持一致

**Comment by ouyuanning** [comment]
看着应该是在把结果保存成exec_plan json时候的报错。
应该是新增了node type，在序列化的地方没有补充对应逻辑造成的。

**Comment by xiaoshuwei** [comment]
> 看着应该是在把结果保存成exec_plan json时候的报错。 应该是新增了node type，在序列化的地方没有补充对应逻辑造成的。

这是导致最终status和exec_plan的结果不一致的问题不？另一个问题是，是不是在任何执行情况下，exec_plan都会有值，且step不应该为空，这个对不？

**Comment by ouyuanning** [comment]
xiaoshuwei的问题已另外开群沟通。
1.1和1.0的分支等PR合并

**Comment by aressu1985** [comment]
update on 12.12:
在升级后的QA环境上，依然存在该问题
mysql> select request_at,status,exec_plan, statement from statement_info where exec_plan like '%"success":fals%' and status="Success"  limit 10;
+----------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| request_at                 | status  | exec_plan                                                                                                                          | statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+----------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023-12-12 03:00:38.825502 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a0fb05da-989a-11ee-90c7-a2217ee52004"} | deallocate prepare __mo_stmt_id_14848                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2023-12-12 03:00:38.825558 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a0fb07b4-989a-11ee-90c7-a2217ee52004"} | COMMIT                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 2023-12-12 03:00:40.000000 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a1b099ac-989a-11ee-b03e-62e5f7852ddb"} | /* 1 queries */ 
select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys" order by account_id                                                                                                                                                                                                                                                                                                                              |
| 2023-12-12 03:00:40.000000 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a1e640e8-989a-11ee-b03e-62e5f7852ddb"} | /* 1 queries */ 
select account_id,account_name,status,version,suspended_time from mo_catalog.mo_account where account_name = "sys" order by account_id                                                                                                                                                                                                                                                                                                                              |
| 2023-12-12 03:00:40.000000 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a1e6509e-989a-11ee-b03e-62e5f7852ddb"} | /* 1 queries */ 
select user_id,authentication_string,default_role from mo_catalog.mo_user where user_name = "dump" order by user_id                                                                                                                                                                                                                                                                                                                                                 |
| 2023-12-12 03:00:40.000000 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a1d70847-989a-11ee-90c7-a2217ee52004"} | /* 1 queries */ 
select 
    						task_id,
							task_metadata_id,
							task_metadata_executor,
							task_metadata_context,
							task_metadata_option,
							task_parent_id,
							task_status,
							task_runner,
							task_epoch,
							last_heartbeat,
							result_code,
							error_msg,
							create_at,
							end_at 
						from mo_task.sys_async_task where task_runner='65353135-6134-3663-6566-633631306463' AND task_status=1 order by task_id limit 3 |
| 2023-12-12 03:00:40.000000 | Success | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"a1b0b925-989a-11ee-b03e-62e5f7852ddb"} | /* 1 queries */ 
select role_name from mo_catalog.mo_role where role_id = 0

**Comment by aressu1985** [comment]
这个问题本身涉及的create account的问题已经解决了，其他还在的问题可以放到Main里面继续解决，该问题解决版本修改的Main(1.2)

**Comment by ouyuanning** [comment]
待PR合并

**Comment by heni02** [comment]
confirm，closed
moc版本：8.0.30-MatrixOne-v1.0.0
mysql> select request_at,status,exec_plan, statement from statement_info where exec_plan like '%"success":fals%' and status="Success" limit 10;
Empty set (0.25 sec)
<img width="1393" alt="企业微信截图_32cb1c20-8ff9-4e09-9e7f-d9bfb0feee81" src="https://github.com/matrixorigin/matrixone/assets/113406637/0645f960-ce89-49da-b641-56b8646de0a0">
实例下发了成功和失败的sql
<img width="1668" alt="企业微信截图_49a39efe-4bf1-484d-8290-0b8ba846f973" src="https://github.com/matrixorigin/matrixone/assets/113406637/cbd8cf64-c019-4633-a4ab-0e33fae1c32c">
