### ISSUE TITLE
[Bug]: [date 12.4] tke regression: create index reported error txn s3 writes can not retry in rc mode

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13212]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ed99cd80c27801e98a91131fae9d1d4ceb2abd63
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7088086827/job/19309180299
<img width="1422" alt="企业微信截图_3071b80f-a732-4f6b-8185-e3685217e171" src="https://github.com/matrixorigin/matrixone/assets/113406637/b4ca050c-c0d1-45e1-abf6-332ced0b0876">

mo log：
<img width="1352" alt="企业微信截图_30f20bed-9f66-4c37-ac31-103292c4c48b" src="https://github.com/matrixorigin/matrixone/assets/113406637/041e2c83-a440-4ab8-81d2-508c1590b292">
http://132.232.112.34:30088/explore?panes=%7B%22rNS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231204%5C%22%7D%20%7C%3D%20%60txn%20s3%20writes%20can%20not%20retry%20in%20rc%20mode%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

该报错之前cn有oom过，但insert table成功了
<img width="1051" alt="企业微信截图_478b374a-1825-4bb9-8e57-4763416592c9" src="https://github.com/matrixorigin/matrixone/assets/113406637/92ed3202-fb17-47f7-bed3-f099b8e40d04">

**Comment by w-zr** [comment]
http://132.232.112.34:30088/explore?panes=%7B%22rNS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231204%5C%22%7D%20%7C%3D%20%6080494d8d-99f4-1e0a-848d-dc8e887e6b08%60%20%21%3D%20%60DEBUG%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701738368499%22,%22to%22:%221701738379499%22%7D%7D%7D&schemaVersion=1&orgId=1
在报`create index reported error txn s3 writes can not retry in rc mode`之前，出现了很多`error: internal error: can not find table by id 273120`
![image](https://github.com/matrixorigin/matrixone/assets/28624654/5cef2d7c-bc09-4857-835f-1f14de04838c)

**Comment by arjunsk** [comment]
As mentioned by @zhangxu19830126 offline, 

> In RC mode, if a conflict happens, we need to retry the current statement to avoid a lost update, so we need to roll back all writes by the current statement in the Txn workspace. But if the current statement writes some data to s3, current rollback s3 writes are not supported.

So, I think the issue occurs because we can insert data into the original table, during "create index". When the create index commits the "3 SQL" transaction, there is a conflict and we try to roll back. But rollback is not possible since data is written to S3.

https://github.com/matrixorigin/matrixone/issues/13238

**Comment by qingxinhome** [comment]
> there is a conflict and we try to roll back. But rollback is not possible since data is written to S3.

This issue is also where I suspect that during transaction rollback, the index table data has not been restored to its original state

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/0589575a-fbe9-4cc1-bc48-c06ed25b15d2)

http://132.232.112.34:30088/explore?panes=%7B%22rNS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231204%5C%22%7D%20%7C%3D%20%60connectionId%2053006%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701738000000%22,%22to%22:%221701738379000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
create index 会插入到 mo_indexes表。但是为啥会写入s3。不清楚原因。

**Comment by daviszhen** [comment]
与 @ouyuanning 协商后，转给他安排处理。

**Comment by ouyuanning** [comment]
短时间无法解决，需要讨论方案后处理

**Comment by ouyuanning** [comment]
短时间无法解决，需要讨论方案后处理

**Comment by ouyuanning** [comment]
短时间无法解决，需要讨论方案后处理

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by heni02** [comment]
date 1.11 tke regression
commit：dd90efb5a7408aa0c82e54f320fc5e08eefa833b
job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7490212917/job/20406174578

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
上周抽时间跟莫尘讨论了下，还没有方案

**Comment by ouyuanning** [comment]
还没时间讨论方案

**Comment by triump2020** [comment]
1.  cn 写S3 需要支持回滚。 参考 #12354

**Comment by triump2020** [comment]
等待PR 充分验证

**Comment by triump2020** [comment]
> As mentioned by @zhangxu19830126 offline,
> 
> > In RC mode, if a conflict happens, we need to retry the current statement to avoid a lost update, so we need to roll back all writes by the current statement in the Txn workspace. But if the current statement writes some data to s3, at present S3 rollback is not supported.
> 
> So, I think the issue occurs because **we can insert** data into the original table, during "create index". When the create index commits the "3 SQL" transaction, there is a conflict and we try to roll back. But rollback is not possible since data is written to S3.
> 
> #13238
> 
> @qingxinhome could you kindly look into this?

@arjunsk   why did it produce conflicts ?

**Comment by qingxinhome** [comment]
fixing

**Comment by arjunsk** [comment]
> > As mentioned by @zhangxu19830126 offline,
> > > In RC mode, if a conflict happens, we need to retry the current statement to avoid a lost update, so we need to roll back all writes by the current statement in the Txn workspace. But if the current statement writes some data to s3, at present S3 rollback is not supported.
> > 
> > 
> > So, I think the issue occurs because **we can insert** data into the original table, during "create index". When the create index commits the "3 SQL" transaction, there is a conflict and we try to roll back. But rollback is not possible since data is written to S3.
> > #13238
> > @qingxinhome could you kindly look into this?
> 
> @arjunsk Do u know where the conflicts comes from?

@triump2020 Earlier, we missed locking the original table during index creation. So I mentioned this possibility. However, that issue has been resolved: https://github.com/matrixorigin/matrixone/issues/13238

**Comment by triump2020** [comment]
wait for PR merge.

**Comment by triump2020** [comment]
Fixed

**Comment by triump2020** [comment]
@heni02 Pls test!

**Comment by triump2020** [comment]
Fixed!

**Comment by heni02** [comment]
confirm,closed
commit:8cc73ec71
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8331064689/job/22811365832
<img width="1378" alt="企业微信截图_cbfa0598-7758-4cdc-af5c-2abddd8a126a" src="https://github.com/matrixorigin/matrixone/assets/113406637/e26cc01c-ce25-47e4-a41b-0c657abb63a8">
