### ISSUE TITLE
[Bug]: [date 12.4] tke regression: cn not oom,but drop database/create table reported lock table bind changed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13213]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ed99cd80c27801e98a91131fae9d1d4ceb2abd63
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7088086827/job/19311020717
<img width="1410" alt="企业微信截图_87633a63-9f92-4a1c-a42f-3c56e2ad483a" src="https://github.com/matrixorigin/matrixone/assets/113406637/b8c0100d-14fe-4ac3-8caf-fcffd8d312c3">
报该错之前cn oom过1次，但距离报错时间已经过了25min左右，另外该测试前其他测试执行正常，报这个错比较诡异，需定位
<img width="788" alt="企业微信截图_2e5ed4ed-d775-471a-9300-c03e8d634671" src="https://github.com/matrixorigin/matrixone/assets/113406637/7984fe5e-d389-40eb-8332-1b69ad6aeb08">

mo log：
http://132.232.112.34:30088/explore?panes=%7B%22rNS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231204%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
这个是正常的。不是bug。cn挂了一次，一定会出现一次(不管间隔多久，只有在此之前访问这个changed的table的时候，才会更新最新绑定关系)这个错误。但是第二次就会好了。这个目前设计就是这样。

**Comment by heni02** [comment]
closed
