### ISSUE TITLE
[Bug]: Error to execute `SHOW GLOBAL VARIABLES LIKE 'save_query_result'`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13224]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-842654e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2023/12/05 06:35:00.409774 +0000 ERROR result/result.go:20 trace {"error": "Error 20101 (HY000): internal error: convert from string to the system variable bool type failed", "elapsed": "1.203442ms", "rows": -1, "sql": "/* cloud_nonuser */ SHOW GLOBAL VARIABLES LIKE 'save_query_result'"}
```

### Expected Behavior

Query succeeds

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

### Additional information

QA cluster

**Comment by YANGGMM** [comment]
<img width="1430" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/339976c3-7f9d-4d2a-b0b1-c29e4c1e75b1">

**Comment by DanielZhangQD** [comment]
http://47.98.35.103/explore?panes=%7B%22RMk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
报什么错？

**Comment by DanielZhangQD** [comment]
当时 共享 CN (上面有问题的 SQL 通过共享 CN 执行) 没有重启，但是有其他付费 CN 在缩容，不确定是否有关系：
http://47.98.35.103/d/cluster-detail-cloud/cluster-detail-cloud?orgId=1&from=1701756000000&to=1701759599000

**Comment by YANGGMM** [comment]
> 当时 共享 CN (上面有问题的 SQL 通过共享 CN 执行) 没有重启，但是有其他付费 CN 在缩容，不确定是否有关系：
> http://47.98.35.103/d/cluster-detail-cloud/cluster-detail-cloud?orgId=1&from=1701756000000&to=1701759599000

加了一点日志，再看一下吧 @

**Comment by DanielZhangQD** [comment]
http://47.98.35.103/explore?panes=%7B%22RMk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60convert%20from%20string%20to%20the%20system%20variable%20bool%20type%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
后面又出现了

**Comment by YANGGMM** [comment]
需要等日志的pr合进1.1dev

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
