### ISSUE TITLE
[Bug]: ut TestReadTimeoutWithNormalMessageMissed fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#13232]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="675" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/32d44708-6074-4b17-b267-1805da1582e5">

fail link:https://github.com/matrixorigin/matrixone/actions/runs/7095168847/job/19311656699?pr=13191

**Comment by zhangxu19830126** [comment]
It hasn't appeared for a long time, it should be fixed by another pr
