### ISSUE TITLE
[Bug]: Account is created successfully from the record in statement_info but no accout in `mo_account` table

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13235]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-842654e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [mo_catalog]> select statement,status from system.statement_info where request_at > '2023-12-05 06:00:00' and statement_id='baa95450-9338-11ee-b0b5-029837cc9255';
+-------------------------------------------------------------------------------------------------------------+---------+
| statement                                                                                                   | status  |
+-------------------------------------------------------------------------------------------------------------+---------+
| CREATE ACCOUNT IF NOT EXISTS `ed171279_cdbd_48e1_a6af_5e48e32e4af9` ADMIN_NAME admin IDENTIFIED BY '******' | Success |
+-------------------------------------------------------------------------------------------------------------+---------+
1 row in set (0.01 sec)

MySQL [mo_catalog]> select * from mo_account where account_name = 'ed171279_cdbd_48e1_a6af_5e48e32e4af9';
Empty set (0.00 sec)

```

### Expected Behavior

Account is created successfully

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

### Additional information

Cloud QA cluster

**Comment by DanielZhangQD** [comment]
Log: http://47.98.35.103/explore?panes=%7B%22RMk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/e8460303-9f5d-4d92-b79e-5da26b9cd281)

**Comment by qingxinhome** [comment]
To be merged

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been submitted to various branches. Please confirm @sukki37 @DanielZhangQD @daviszhen

**Comment by DanielZhangQD** [comment]
@qingxinhome Please provide the test result that you verified this bug, thanks!

**Comment by DanielZhangQD** [comment]
It's difficult to trigger this issue, keep watching this.

**Comment by DanielZhangQD** [comment]
To be confirmed

**Comment by DanielZhangQD** [comment]
To be confirmed

**Comment by DanielZhangQD** [comment]
到 12.16 没有复现，暂时关掉
