### ISSUE TITLE
[Bug]: `read time out` during consistency check of tpcc during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13252]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5a8a41ffb59a5d28a0cebdd9808ba8b8e6f96b4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7097648587

**Comment by aressu1985** [comment]
update on 12.6:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7102214209

<img width="1269" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7788037f-1610-4e38-9268-b664a77dd47a">

SQL:
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted

mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);


ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by m-schen** [comment]
已修复。1.1-dev和main分支均可验证。

**Comment by aressu1985** [comment]
fixed
