### ISSUE TITLE
[Bug]: Creating a tenant has not been successful

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#13250]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

link issue: https://github.com/matrixorigin/MO-Cloud/issues/1935

**Comment by sukki37** [comment]
<img width="1707" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/aead2c3a-336f-48bf-a612-7ee48c9279aa">

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/75e0b5f3-cfde-426d-b2a3-c06cc3f75d84)

**Comment by qingxinhome** [comment]
mysql> select transaction_id, request_at, statement, status, error from statement_info where request_at > '2023-12-05 06:00:00' and request_at < '2023-12-05 07:28:00' and statement like '%CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071`%';
+--------------------------------------+----------------------------+-------------------------------------------------------------------------------------------------------------+---------+---------------------------------------------------------------------------------------------------------------------------+
| transaction_id                       | request_at                 | statement                                                                                                   | status  | error                                                                                                                     |
+--------------------------------------+----------------------------+-------------------------------------------------------------------------------------------------------------+---------+---------------------------------------------------------------------------------------------------------------------------+
| 19649054-43ce-4134-85bd-b329366a0b98 | 2023-12-05 06:47:16.097800 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | internal error: routine send response failed. error:write tcp4 172.20.2.131:6001->172.20.1.137:48856: write: broken pipe  |
|                                      | 2023-12-05 06:47:26.362793 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| bb390038-35cb-45e0-bd8b-bb5614d443e1 | 2023-12-05 06:47:36.638704 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:47:46.930913 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:47:57.192079 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:48:07.435381 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 11a1d851-c6e2-4a3b-b96b-b5bd8f96b46c | 2023-12-05 06:48:20.944817 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:48:34.470028 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 96995be7-e0e5-4939-b44f-61253443ad3d | 2023-12-05 06:48:51.093309 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:49:14.156678 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:49:49.985690 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 13fd2b8e-5635-43e1-98dc-efeaadb66b7d | 2023-12-05 06:50:30.217228 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:51:10.440291 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:51:50.692519 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:52:30.926374 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:53:11.320108 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:53:51.597408 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 2c5f7a47-1114-4180-89bb-950d60a8a0fc | 2023-12-05 06:54:31.855287 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:55:12.192102 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:55:52.360882 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:56:32.606528 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:57:12.841555 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 84fc3c9b-87d2-4181-8a1e-a9ac8829d4ee | 2023-12-05 06:57:53.161118 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:58:33.409120 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:59:13.717257 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 06:59:53.999240 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:00:34.375778 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| c984bd67-abed-4b6f-8a40-90006cc0d05f | 2023-12-05 07:01:14.609738 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 45410cc5-b63e-4e28-9e6e-2e5787fa20f1 | 2023-12-05 07:01:54.820321 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| e50a1ae2-0e8d-4347-bb2d-1e6e97d53113 | 2023-12-05 07:02:35.053212 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:03:15.332716 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:03:55.612720 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:04:35.858749 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:05:16.096345 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:05:56.331230 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| c2c1e62e-ca3c-4869-8da9-892834c19aba | 2023-12-05 07:06:36.585879 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 238ba681-07b6-4042-9d5a-8482238c8e6f | 2023-12-05 07:07:16.828409 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:07:59.115134 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:08:39.458359 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 6ccd86a8-e121-4db1-b9b5-23424e54f98d | 2023-12-05 07:09:19.698738 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:09:59.991046 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:10:41.494745 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:11:22.532287 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| d20bb902-3d8a-4fba-8172-dccb4269e7be | 2023-12-05 07:12:05.352367 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| b2b96385-4c3a-4891-8411-d79e2b11322a | 2023-12-05 07:12:49.519972 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:13:33.429445 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:14:13.661575 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:14:54.754848 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 2385b26d-80b1-49a3-8fca-14d7153b1a27 | 2023-12-05 07:15:35.069502 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 2b37a80e-d03c-4bb7-986c-b4603571670e | 2023-12-05 07:16:16.313604 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| f313ee23-5ad8-4ea1-b8e4-ae3d5700d94a | 2023-12-05 07:16:57.334491 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:17:47.395925 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:18:32.617509 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 3ccdd61d-19ed-4e78-b07f-368f5d8f3934 | 2023-12-05 07:19:14.498569 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:19:58.745127 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:20:40.476085 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:21:21.408229 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:22:03.143458 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:22:45.031993 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:23:27.040023 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:24:12.369702 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| fc60003f-c4dc-415a-813e-8bf3ce5fc4d9 | 2023-12-05 07:24:55.490117 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| 141c88d6-b0f5-4468-8570-3b6b1ea6e404 | 2023-12-05 07:25:39.350349 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
| cf793716-8564-46f4-89ab-a2db8540d15d | 2023-12-05 07:26:21.167492 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Failed  | Duplicate entry '3a4bf5d7_46e6_4e77_aca3_c5cd15be2071' for key '__mo_index_idx_col'                                       |
|                                      | 2023-12-05 07:27:01.440736 | CREATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******' | Success |                                                                                                                           |
+--------------------------------------+----------------------------+-------------------------------------------------------------------------------------------------------------+---------+---------------------------------------------------------------------------------------------------------------------------+


假设1：
 第一行记录虽然失败，但是create account实际成功了
但是，在数据响应给客户端时，发生 "broken pipe" 错误。
此时该租户实际上创建成功，元数据信息完整。后续再次创建同名租户时，就报唯一索引冲突了
讲不通的地方：
1.中间没有drop account，但是最后CREATE ACCOUNT IF NOT EXISTS语句一条却成功了
2.用户中间多次采用的是CREATE ACCOUNT IF NOT EXISTS执行，理应都成功才对

注："broken pipe" 错误通常表示在你的 Go 程序中，尝试写入到已经关闭的管道（pipe）时发生了错误。
这可能是因为你的程序中的某个部分试图向一个已经关闭的管道写入数据。


假设2：
第一行记录 create account失败了，事务回滚，但是mo_account表的唯一索引对应的索引表没有成功回滚，导致其残留在索引表中一条记录，后期
执行CREATE ACCOUNT IF NOT EXISTS时，往mo_account表中插入数据，发生唯一索引冲突，
讲不通的地方：
	1. 如果是这样，那么会导致一只创建失败，永远不会成功，除非手动删除索引表中非法的记录
	2. 第一行记录报的错误信息是怎么回事？
	  routine send response failed. error:write tcp4 172.20.2.131:6001->172.20.1.137:48856: write: broken pipe

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/3c6f74f4-42bc-4080-bbfe-06bbf7a851b8)
![image](https://github.com/matrixorigin/matrixone/assets/70939751/d07f69dc-ee9e-4070-bbb2-8180c212d5b4)
问题原因基本上确定：用户在第一次执行 REATE ACCOUNT IF NOT EXISTS `3a4bf5d7_46e6_4e77_aca3_c5cd15be2071` ADMIN_NAME admin IDENTIFIED BY '******'时，实际上执行成功了，但是该条SQL执行时间跨度过长，大约40分钟，但是却发生在数据响应给客户端时，发生 "broken pipe" 错误。此时该租户实际上创建成功，元数据信息完整。后续再次创建同名租户时，就报唯一索引冲突了

**Comment by qingxinhome** [comment]
<img width="1279" alt="企业微信截图_17022824111257" src="https://github.com/matrixorigin/matrixone/assets/70939751/860d9417-0bdb-4bd0-bcb7-1fd0d9b6e320">
<img width="1280" alt="企业微信截图_17022914381952" src="https://github.com/matrixorigin/matrixone/assets/70939751/33eed435-35ef-4c2b-bdfa-48bc916e70f6">

**Comment by qingxinhome** [comment]
Testing in progress, currently not replicated

**Comment by qingxinhome** [comment]
Testing in progress, currently not replicated

**Comment by qingxinhome** [comment]
Testing in progres

**Comment by daviszhen** [comment]
跟 #13944 同一个问题。pr中

**Comment by daviszhen** [comment]
已经解决

**Comment by tianyahui-python** [comment]
待测试
