### ISSUE TITLE
[Bug]: invalid state txn not found error occured duaring running tpcc 1000-1000 test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13258]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 2123768
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7095260946/job/19318904478

<img width="1087" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/326ccd7c-0ea8-47d9-a2a8-493a3264c6f7">

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22i8G%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-2123768%5C%22%7D%20%7C%3D%20%60invalid%20state%20txn%20not%20found%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701781484343%22,%22to%22:%221701785919033%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
fixed by @nnsgmsone pr

**Comment by aressu1985** [comment]
fixed

**Comment by Ariznawlll** [comment]
**[12.20]tpcc 10-10 stability test:**

**commit**：d50211bca84238c88eae7028a67fe7fb14e859c1
<img width="1321" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f95dd21e-3b08-4de5-83b3-79765db7fef9">

**log**：http://10.222.6.1/explore?panes=%7B%22hLb%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
cn crash. it's expect errors
