### ISSUE TITLE
[Bug]: [date 12.5] tke regression: cn reported panic: found leak txn

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13260]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5a8a41ffb59a5d28a0cebdd9808ba8b8e6f96b4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7102214209/job/19345616735
cn restart 
<img width="870" alt="企业微信截图_3c0aa22d-6063-459a-9818-00dd4d93d542" src="https://github.com/matrixorigin/matrixone/assets/113406637/ad4479a0-4bb2-44a2-bf1c-d31cecc534f3">
check 3 cn not oom
<img width="1410" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/7f1813ce-10b1-4687-a7e1-a880ca1a45a8">
http://132.232.112.34:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20231205&from=now-12h&to=now&refresh=10s
get 3 cn crached log:
<img width="1473" alt="企业微信截图_4343886f-d3be-4085-8911-a7be8d0168e8" src="https://github.com/matrixorigin/matrixone/assets/113406637/011d2885-cd92-4b01-92c3-592d64d522bf">
panic: found leak txn

goroutine 375 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x3?, 0x3?, {0x0?, 0x0?, 0xc6918b2600?})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc2eabd4dd0, {0xc4392f4a80, 0x3, 0x3})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Log(0xc346c70140, {0x3a54bb2, 0xe}, {{0x0, 0x0}, 0x5, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/log/logger.go:169 +0x44a
github.com/matrixorigin/matrixone/pkg/common/log.(*MOLogger).Fatal(0x3a48e31?, {0x3a54bb2?, 0xc153fcff85a30991?}, {0xc4392f4a80?, 0x5dba560?, 0x3963a20?})
	/go/src/github.com/matrixorigin/matrixone/pkg/common/log/logger.go:137 +0x4e
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).getTxnClient.func1.1({0xc0059ab5a0, 0x10, 0x5dba560?}, {0xc153fcff85a30991?, 0x102c9d768e71?, 0x5dba560?}, {0xc6ef57a9e0, 0x1d})
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:593 +0x3cb
github.com/matrixorigin/matrixone/pkg/txn/client.(*leakChecker).doCheck(0xc000a221e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/leak_checker.go:109 +0x1b7
github.com/matrixorigin/matrixone/pkg/txn/client.(*leakChecker).check(0xc000a221e0, {0x421b098, 0xc000b19da0})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/leak_checker.go:97 +0x36
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5

cn crash log:
[nightly-devops-3.zip](https://github.com/matrixorigin/matrixone/files/13575431/nightly-devops-3.zip)

mo log:
http://132.232.112.34:30088/explore?panes=%7B%22MTU%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231205%5C%22%7D%20%7C%3D%20%60panic:%20found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1435" alt="企业微信截图_eaf696c4-a078-45b1-a1fb-797fe8067d6e" src="https://github.com/matrixorigin/matrixone/assets/113406637/31dd8249-b507-4830-8d2f-8e0967dc52ff">
profile：
[cnprofile.tar.gz](https://github.com/matrixorigin/matrixone/files/13578336/cnprofile.tar.gz)

**Comment by aressu1985** [comment]
this is caused by issue#13260, this can be closed
