### ISSUE TITLE
[Bug]: Cannot see created tables in Navicat

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13272]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.1-dev 79d77b496
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/36026334/cc5f2867-710e-477d-bb0e-7b2a6e8aec58)
![image](https://github.com/matrixorigin/matrixone/assets/36026334/04604bc1-7e7c-44c0-9f19-49a122c2c025)

### Expected Behavior

All the tables are visible in navicat

### Steps to Reproduce

```Markdown
Create tables with `mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u 9bbf5111_42cb_468d_8fe0_965bab798a7d:admin:accountadmin  -p`
```

**Comment by m-schen** [comment]
if len(batches) <= relIndex || len(batches[relIndex].Vecs) <= expr.colIndex

保护性检测的判断条件写错了，第一个判断条件应该是 <

不过本质上的原因是收到了一个不合法的batch list，预期应该是取第i个，但是batch list长度不足。

**Comment by Morranto** [comment]
已排查出原因，研究怎么解决

**Comment by DanielZhangQD** [comment]
Verified and passed with commit `dev-cd0f40cb9`
