### ISSUE TITLE
[Bug]: The number of tables seen in Navicat is one more than in Mo Cloud.

### ISSUE THREAD

**Issue by friry** [matrixorigin/matrixone#13270]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):qa
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1220" alt="截屏2023-12-06 16 08 53" src="https://github.com/matrixorigin/matrixone/assets/65983408/07854516-9706-4916-943d-a86d5bd1a783">

<img width="534" alt="截屏2023-12-06 16 20 28" src="https://github.com/matrixorigin/matrixone/assets/65983408/6e67d91e-10b0-4cbd-b75c-78e648bdf850">

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**main commit：1bd5d8779**

**正常行为：在使用navicat连接mo时，mo_catalog下的mo_sessions为视图，应该出现在视图目录下：**

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/dc2c5e67-9410-42db-bd15-14e47b449912">

<img width="381" alt="image" src="https://github.com/user-attachments/assets/fb4e50e2-e58d-400f-a1a4-98f8f08139d2">

测试通过
