### ISSUE TITLE
[Bug]: internal error: panic runtime error: invalid memory address or nil pointer dereference: when CRTL +C query

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13279]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5a8a41ffb59a5d28a0cebdd9808ba8b8e6f96b4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:841
github.com/matrixorigin/matrixone/pkg/sql/colexec/minus.(*container).cleanBatch
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/minus/types.go:73
github.com/matrixorigin/matrixone/pkg/sql/colexec/minus.(*Argument).Free
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/minus/types.g

**Comment by m-schen** [comment]
已修复，可验证。1.1-dev和main都可以。

**Comment by aressu1985** [comment]
fixed
