### ISSUE TITLE
[Bug]: Navicat hangs when opening tables

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13273]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.1-dev 79d77b496
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Refer to https://github.com/matrixorigin/MO-Cloud/issues/1943

### Expected Behavior

Get the result successfully

### Steps to Reproduce

```Markdown
Refer to https://github.com/matrixorigin/MO-Cloud/issues/1943
```

**Comment by ck89119** [comment]
参见 https://github.com/matrixorigin/MO-Cloud/issues/1943

**Comment by Morranto** [comment]
需要重写group_concat，正在讨论，

**Comment by Morranto** [comment]
正在修复

**Comment by aronchanisme** [comment]
MOC issue is resolved
https://github.com/matrixorigin/MO-Cloud/issues/1943#issuecomment-1869983261

For bvt case, please kindly take a look, thanks. @heni02

**Comment by heni02** [comment]
<img width="946" alt="企业微信截图_0f3c5b6d-336f-4479-ab99-2bc15cbb5c5d" src="https://github.com/matrixorigin/matrixone/assets/113406637/019b95f4-0498-4f7f-a6e0-22ec53210098">
报错sql为：
SELECT DISTINCT ROUTINE_SCHEMA, ROUTINE_NAME, PARAMS.PARAMETER FROM information_schema.ROUTINES LEFT JOIN ( SELECT SPECIFIC_SCHEMA, SPECIFIC_NAME, GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'caokai_test' ORDER BY ROUTINE_SCHEMA;
bvt case需要构造PARAMETERS，routines两个表的数据，再增加该case

**Comment by heni02** [comment]
case add done
