### ISSUE TITLE
[Bug]: [date 12.6]tke regression: tpcc test lots of timeout and reported invalid input: only prepare statement can use ? expr

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13287]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6370e983b1d270ff041f67f1abd5c51a245b119d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7116706746/job/19381954959
<img width="1858" alt="企业微信截图_8efe9f70-c0a6-4f3e-b1ab-2863b5a868c4" src="https://github.com/matrixorigin/matrixone/assets/113406637/3137fb69-5bcd-4ec2-9e06-fa5af0bbf12d">
这个报错前也有大面积链接超时的错误，日志中发现很多stream closed的报错，不确定是否有关系
<img width="1372" alt="企业微信截图_903f7e2b-5a38-4cf1-acfe-09a007dbd490" src="https://github.com/matrixorigin/matrixone/assets/113406637/131e65dd-33d5-48ca-808f-e402a34f548c">

mo log:
<img width="1349" alt="企业微信截图_7a01b44e-002f-4fdc-ac47-524deeedffd5" 
src="https://github.com/matrixorigin/matrixone/assets/113406637/199467be-d53b-4381-acb3-f372a00457d5">
http://132.232.112.34:30088/explore?panes=%7B%22xwd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231206%5C%22%7D%20%7C%3D%20%60invalid%20input:%20only%20prepare%20statement%20can%20use%20%3F%20expr%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701890260023%22,%22to%22:%221701891037467%22%7D%7D%7D&schemaVersion=1&orgId=1

环境内存使用情况：
http://132.232.112.34:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20231206&from=1701877786744&to=1701918720537

**Comment by ouyuanning** [comment]
表达式的部分已提PR。
超时的部分没有进展

**Comment by ouyuanning** [comment]
等cherry pick的PR合并

**Comment by ouyuanning** [comment]
表达式报错的已处理。

stream close的部分，这里没有做处理。
因为已经有2个issue在跟踪。
-[]13288
-[]12746

**Comment by heni02** [comment]
等待回归跑两天观察看看是否再出现

**Comment by heni02** [comment]
最近回归没有出现该错误，先关闭
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7242571358
