### ISSUE TITLE
[Bug]: TPCH 1T Q9 Query report stream closed on Distributed mode TKE

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13288]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 9cf8c6aa1
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7116706746/job/19376692628

<img width="1398" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d2829682-df5c-44ae-842e-a39a8dfba7a8">

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22hyW%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231206%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701885308913%22,%22to%22:%221701886130791%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
加了日志，channel没有关闭，而是里面的值是空的：
```
{"level":"ERROR","time":"2023/12/07 11:29:00.338181 +0000","caller":"compile/scopeRemoteRunTypes.go:162","msg":"liubo: sender, val is nil"}
{"level":"ERROR","time":"2023/12/07 11:29:00.338286 +0000","caller":"compile/scopeRemoteRunTypes.go:163","msg":"error: stream closed","span":{"trace_id":"c0886a03-1f3d-cf48-a5fc-53556d4d     bcd3","span_id":"a060f0b42a9fa844"}}
```

**Comment by volgariver6** [comment]
<img width="783" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/89ace4ea-14f6-43e2-b8e8-5d99097525b2">

tpch 查询发送到cn1，cn1 转发pipeline request 到 cn2，但是cn2在执行过程中发生了OOM重启，cn1 就会返回 stream closed 错误。

从这个现象来看，这个错误是正常的。关键是cn 发生了OOM。

**Comment by volgariver6** [comment]
找到原因了，修改代码重新测试一下。

**Comment by volgariver6** [comment]
https://github.com/matrixorigin/matrixone/pull/13320 this revert pr fix the issue. this pr is meant to fix issue https://github.com/matrixorigin/matrixone/issues/13219.

new PRs were committed to fix issue https://github.com/matrixorigin/matrixone/issues/13219:
#13339 and #13340

**Comment by aressu1985** [comment]
fixed
