### ISSUE TITLE
[Bug]: when account name is upper letter, login mo failed 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13294]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c4b255cbd0ee319c50210706a94eaf5d6084aadf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when account name is upper letter, login mo failed ，but lower letter login success
<img width="1030" alt="企业微信截图_9964c89a-2c93-4346-83fb-263780c18ca2" src="https://github.com/matrixorigin/matrixone/assets/113406637/85bbe2d1-fc98-4b67-91d5-ada5a725e638">

ddl：
create account BIG_DATA_ACCOUNT admin_name='admin' identified by '111';
mysql -h 127.0.0.1 -uBIG_DATA_ACCOUNT:admin -P6001 -p111
mysql -h 127.0.0.1 -ubig_data_account:admin -P6001 -p111

**Comment by daviszhen** [comment]
这个不是bug。一值是这个行为。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/b4766587-d4db-4503-81b1-ae25b4792a65)

**Comment by heni02** [comment]
已确认，关闭
<img width="782" alt="企业微信截图_0b103759-a7e6-4817-963d-b7834eb0e56c" src="https://github.com/matrixorigin/matrixone/assets/113406637/cd0e9511-13d4-494a-9a02-c1afdaaff6c8">
