### ISSUE TITLE
[Bug]: [date 12.6]tke regression: load data create table reported lost connection after half hour

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13291]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6370e983b1d270ff041f67f1abd5c51a245b119d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7116706746/job/19384303508
![image](https://github.com/matrixorigin/matrixone/assets/113406637/76f77722-106a-4926-acaf-ebca301c2990)
从时间看这个时间段有cn oom，但是半个小时才返回lost connection不正常
<img width="1859" alt="截屏2023-12-07 上午11 40 04的副本" src="https://github.com/matrixorigin/matrixone/assets/113406637/6d1c2243-aeaf-4471-9a40-443d0423415f">
http://132.232.112.34:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20231206&from=1701877786744&to=1701918720537

log：
http://132.232.112.34:30088/explore?panes=%7B%22xwd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231206%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701890260000%22,%22to%22:%221701918037000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
Pending processing

**Comment by daviszhen** [comment]
1，间隔半小时响应。不是issue中截图中的异常导致的。
从时间点上看，create table语句 是发送给了nightly-regression-dis-tp-cn-zfn7g 而不是 ghcdt。

而此时create table 应该一直没有响应，可能是卡住了。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/640a7bb3-8fb5-4853-a63f-6fa51169f473)

直到zfn7g在20:24分重启。连接断开。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/1d4f5023-47d3-425a-9aaa-0c6d1ebaa651)

然后测试脚本报错。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/2fbeba37-8824-43f7-ac70-fdf419261eb2)

**Comment by daviszhen** [comment]
2，另外两个cn，9bwpf和ghcdt 没有启动的日志。说明在issue期间没有重启。这个与
监控上的cpu 利用率有出入。但是不确定谁对的。

http://132.232.112.34:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20231206&from=1701892260000&to=1701894600000

![image](https://github.com/matrixorigin/matrixone/assets/60595215/87956f6e-712c-4f5f-b231-454e9884856d)

http://132.232.112.34:30088/explore?panes=%7B%22xwd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231206%5C%22%7D%20%7C%3D%20%60mo-service%20-cfg%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701891000000%22,%22to%22:%221701894600000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
3，最后的连接所在的goroutineid

![image](https://github.com/matrixorigin/matrixone/assets/60595215/e4dbf73a-bdbd-46f0-ba18-1f95b11554e1)

**Comment by daviszhen** [comment]
出问题的时间点出了大量的 waitSendCompleted 问题。
https://github.com/matrixorigin/matrixone/issues/13471

**Comment by aylei** [comment]
> 2，另外两个cn，9bwpf和ghcdt 没有启动的日志。说明在issue期间没有重启。这个与 监控上的cpu 利用率有出入。但是不确定谁对的。
> 
> http://132.232.112.34:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20231206&from=1701892260000&to=1701894600000
> 
> ![image](https://private-user-images.githubusercontent.com/60595215/290442853-87956f6e-712c-4f5f-b231-454e9884856d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDk5OTMsIm5iZiI6MTcwMjU0OTY5MywicGF0aCI6Ii82MDU5NTIxNS8yOTA0NDI4NTMtODc5NTZmNmUtNzEyYy00ZjVmLWIyMzEtNDU0ZTk4ODQ4NTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwMjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNDkxZDg5MjlkMjcwYzFhNDI2YThkNDhhYTA5ZjVkMmZlNGRiZWJiY2I1YzI4N2Q1MmEwMTEwOGZhOWE1OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSpJsgZgee_V7y4Wwp4nvGvhgziov9Oz-yMfRgnKkAQ)
> 
> http://132.232.112.34:30088/explore?panes=%7B%22xwd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231206%5C%22%7D%20%7C%3D%20%60mo-service%20-cfg%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701891000000%22,%22to%22:%221701894600000%22%7D%7D%7D&schemaVersion=1&orgId=1

cc @xzxiong

**Comment by daviszhen** [comment]
需要环境测试

**Comment by daviszhen** [comment]
需要环境测试

**Comment by daviszhen** [comment]
需要环境测试

**Comment by daviszhen** [comment]
delay

**Comment by daviszhen** [comment]
dealy

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入
