### ISSUE TITLE
[Bug]: internal sql connection leak

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#13305]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

internal sql connection is leak.

### Additional information

cn total goroutines: 9K
internal connection goroutines: 8K

<img width="838" alt="企业微信截图_dd012305-451c-444d-99ff-2aec0c1e8f19" src="https://github.com/matrixorigin/matrixone/assets/2995754/233f92ff-75cc-4e9b-9754-85510febf3df">

cn ip: 172.20.93.3，too many local connections
[6001.txt](https://github.com/matrixorigin/matrixone/files/13607929/6001.txt)

**Comment by xzxiong** [comment]
dup as https://github.com/matrixorigin/matrixone/issues/12731
pls watch pr
https://github.com/matrixorigin/matrixone/pull/13313, https://github.com/matrixorigin/matrixone/pull/13312

**Comment by xzxiong** [comment]
@zhangxu19830126  all cherry-pick merged.
