### ISSUE TITLE
[Bug]: create table report ERROR 1049 (HY000) at line 1: invalid database test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13302]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e1e2ec6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7123640155/job/19401616920

<img width="1410" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/a8458596-ce1e-490a-9e34-62ba440b6133">

after succeeded to create database, then creating table, the query cost 5 minute, and report error:
invalid database test

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22GPo%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-e1e2ec6%5C%22%7D%20%7C%3D%20%60invalid%20database%20test%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701937084120%22,%22to%22:%221701938587836%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by nnsgmsone** [comment]
2023-12-09 11:04:08 INFO  Sysbench:108 - Now start to initialize sysbench data, db=sbtest, tableCount=10, tableSize=100000。。发生的错误。上一次这个库是在2023-12-09 18:53:37.638	
{"level":"INFO","time":"2023/12/09 10:53:37.638582 +0000","caller":"rpc/handle.go:851","msg":"[precommit] create database: AccessInfo:<AccountID:0 UserID:1 RoleID:0 > Name:\"sbtest\" CreateSql:\"create database if not exists sbtest\" DatTyp:\"\" DatabaseId:272690  txn: ctx[3A50104CE8A14F988B40D0F0BEBF28D7][1702119217637022142-1->9223372036854775807-4294967295][Active]: <nil>"}。。创建的。然后是在
	
{"level":"INFO","time":"2023/12/09 11:04:08.657747 +0000","caller":"rpc/handle.go:882","msg":"[precommit] drop database: &{Name:sbtest ID:272690} txn: ctx[AD529553827F4BD195115786E48D822C][1702119848538975927-1->9223372036854775807-4294967295][Active]: <nil>"}删除。然后下一个是在	
{"level":"INFO","time":"2023/12/09 11:04:10.272852 +0000","caller":"rpc/handle.go:851","msg":"[precommit] create database: AccessInfo:<AccountID:0 UserID:1 RoleID:0 > Name:\"sbtest\" CreateSql:\"create database if not exists sbtest\" DatTyp:\"\" DatabaseId:272694  txn: ctx[B4504C95DAF84D169A3B4FF4A679384B][1702119849583220653-1->9223372036854775807-4294967295][Active]: <nil>"}创建的。。。所以出问题的时候，这个表确实是不存在的。。

**Comment by nnsgmsone** [comment]
至于为什么会导致时序的问题。。。还需要分析。

**Comment by nnsgmsone** [comment]
因为各个操作用的不是一个session。然后又是多cn。因为mo目前的设计并不是全局一致性的，所以出现这个是可能的。。可能需要客户端修改以下策略。

**Comment by nnsgmsone** [comment]
麻烦了 @XuPeng-SH

**Comment by XuPeng-SH** [comment]
assigned @LeftHandCold

**Comment by LeftHandCold** [comment]
在相关时间点，db test并没有commit到dn来创建。

**Comment by LeftHandCold** [comment]
<img width="2441" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/55b2b9c0-8642-40cd-985c-db6b35b28725">
当时有创建db错误的返回，但是 脚本却提示成功

**Comment by LeftHandCold** [comment]
脚本的问题 @aressu1985  修改了脚本可以复现此问题.
<img width="1164" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/d5c7ef5e-4509-4bc4-b931-bfa77d11c815">

**Comment by LeftHandCold** [comment]
<img width="943" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/95c89637-ef83-49f5-a9c4-bbdffb9bfa90">

**Comment by LeftHandCold** [comment]
另补充，当时创建失败是正常的，因为当时的cn因为别的bug全部异常。

**Comment by aressu1985** [comment]
经调查，是工具问题，该问题暂时关闭
