### ISSUE TITLE
[Feature Request]: Support masking part of statements in the record of statement_info

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13327]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
NA
```

### Describe the feature you'd like

I want to mask part of the statement when recording the statement in the statement_info record, for example if I run `select col1 from table 1 left join table2....`, I want to see `select col1 from table 1 ***` in the statement_info
Refer to https://github.com/matrixorigin/MO-Cloud/issues/1970

**Comment by LiSong0214** [comment]
related to：https://github.com/matrixorigin/MO-Cloud/issues/2005

**Comment by DanielZhangQD** [comment]
> related to：[matrixorigin/MO-Cloud#2005](https://github.com/matrixorigin/MO-Cloud/issues/2005) @DanielZhangQD 2005做完，这个是不是不用了？

对，我 close 掉
