### ISSUE TITLE
[Bug]: streaming：delete or truncate source reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13328]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c4b255cbd0ee319c50210706a94eaf5d6084aadf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

it is require reporting error message, not report panic
<img width="1111" alt="企业微信截图_e1d18fa5-bc81-4a90-bef9-999e9d38ec0b" src="https://github.com/matrixorigin/matrixone/assets/113406637/d58f8307-1d0e-414d-b6bd-ddeecf07fa59">

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13348

**Comment by heni02** [comment]
commit：09b923d8ca3ecef29c7ec6a6b80eb2c63e17cb9d
delete 没有问题了，truncate还是有问题
<img width="950" alt="企业微信截图_819f6803-27a9-40fd-a6ac-458b47f9c7e9" src="https://github.com/matrixorigin/matrixone/assets/113406637/387f7242-145a-4abd-885a-7448d5c598ab">

**Comment by gavinyue** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/54566980/f6fccc8a-26e3-497c-b755-3730c28bf454)

fix in pr: https://github.com/matrixorigin/matrixone/pull/13420

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13420 merged

**Comment by heni02** [comment]
confrim,closed
commit :2a761a0c8fec04129107bd03a3222f356a23f1c6
<img width="861" alt="企业微信截图_4489b6f9-ea79-414e-bfb0-52282011f6d8" src="https://github.com/matrixorigin/matrixone/assets/113406637/6061fcb2-07d4-4a14-9a71-8aa92db67699">
