### ISSUE TITLE
[Bug]: establishing 1000 connections cost about 30 minutes on distributed mode regression TKE 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13337]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):fefad6159
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7143208229/job/19463961333

<img width="1409" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/908a1516-099f-440f-814a-a0219cc74956">

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22qHe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231208%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221702072516000%22,%22to%22:%221702074103000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ck89119** [comment]
找到了当时的监控，可以看到21：55时连接数都非常高了
<img width="1851" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/8552dd42-e492-43ec-94e3-450e06111dea">

对比一下获取正常执行的（12.16的nightly regression）
<img width="1017" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/b1b7d01e-e0d9-4239-84cf-763bc05c34e8">

可以看到开始获取连接时（12:07:34），connections数很低，然后提升到1000左右，这是符合预期的
<img width="1872" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/cb7b0d24-1ec7-4cf3-8176-0c28273d5577">

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/7261426038/job/19783883670

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/7259447300

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7396514609/job/20122748501

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8747723151/job/24007381347

**Comment by ck89119** [comment]
获取连接时间过长是因为同一时间有其它sysbench任务在跑，获取连接鉴权时需要跑几条sql，mo集群负载高的情况下执行变慢，耗时变长。

以上面这个job https://github.com/matrixorigin/matrixone/actions/runs/8747723151/job/24007381347 为例，

这是获取连接的时间
<img width="1839" alt="企业微信截图_47279174-8522-4b99-afce-9186276acbbe" src="https://github.com/matrixorigin/matrixone/assets/4971300/c52033dd-0368-4357-b40e-216e18e4c899">

与此同时，Load SSB 10G Data And Test也在跑
<img width="1857" alt="企业微信截图_f58b2408-cf97-4a24-9209-a276b1dc3712" src="https://github.com/matrixorigin/matrixone/assets/4971300/81dac928-1ce5-4a2c-b70a-a46bb1d68237">

当时的负载监控
<img width="1841" alt="企业微信截图_6bd0ca79-e594-4cda-b12b-b3d2b4108a81" src="https://github.com/matrixorigin/matrixone/assets/4971300/f67264f1-1a30-41f6-9f72-73e262648d39">

**Comment by ck89119** [comment]
规避这个问题可以把这3个任务改成串行执行
<img width="1884" alt="企业微信截图_db9cdac6-46bc-4f9a-947e-540e64829f42" src="https://github.com/matrixorigin/matrixone/assets/4971300/07a02b3e-7320-4713-98d3-f7bba5e575db">

**Comment by aressu1985** [comment]
有其他issue在跟踪
