### ISSUE TITLE
[Bug]: 1.0-dev regression test tpcc w-w

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#13333]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.0-dev regression test tpcc w-w

**Comment by aressu1985** [comment]
closed
