### ISSUE TITLE
[Bug]: lots of "illegal state" error during sysbench insert and update cases

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13336]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):fefad6159
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7143208229/job/19467635755

<img width="1418" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/37f1cd35-3a28-47d2-ad78-8685a9ede57c">

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22qHe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231208%5C%22%7D%20%7C%3D%20%60illegal%20state%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221702073356168%22,%22to%22:%221702093783671%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ouyuanning** [comment]
今天简单看了一下。这是客户端无法建立跟服务器连接的报错。
具体原因还没有找到。

**Comment by aressu1985** [comment]
经和@ouyuanning @zhangxu19830126 沟通，这个错误发生的时候，CN又重启，重启的原因是因为当时明松的一个bug导致#13252导致，该bug已经修复，这个错误在CN重启的时候，属于正常表现，该问题关闭
