### ISSUE TITLE
[Bug]: tps of point_select suddenly  descreased more than 90% on distributed mode regression TKE 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13338]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):fefad6159
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7143208229/job/19465995089

<img width="1312" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/358e26a3-a716-4894-98e4-9af90450bce2">

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22qHe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231208%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221702076596000%22,%22to%22:%221702076743000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by badboynt1** [comment]
偶发问题，最新的daily上尚未复现。 继续观察一下

**Comment by badboynt1** [comment]
最近sysbench有很多其他性能问题，这个问题暂未复现，继续观察

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/c7dca79a-bee4-4249-826c-77ed09426075)

12月10号再次复现

**Comment by badboynt1** [comment]
在研究别的问题

**Comment by badboynt1** [comment]
在研究别的问题

**Comment by ouyuanning** [comment]
辛苦锦赛帮忙先看看日志和profile啥的，看看是啥原因

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
