### ISSUE TITLE
[Bug]: streaming: json data include escape character，source result is null

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13331]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c4b255cbd0ee319c50210706a94eaf5d6084aadf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

`json:{"c1": "\"","c2":"\:","c3": "\,","c4":"\"\:\,","c5":"\{","c6":"\}"}`
<img width="525" alt="企业微信截图_7b2fc683-2e80-4fcd-9e31-42d6bef3b5c4" src="https://github.com/matrixorigin/matrixone/assets/113406637/5d9be2a4-3c12-4cd0-b068-bc293f016c5f">
ddl：
create source stream_6(c1 char(5),c2 varchar(5),c3 text,c4 tinytext,c5 mediumtext,c6 longtext )with(
 "type"='kafka',
"topic"= 'test',
"partition" = '0',
 "value"= 'json',
 "bootstrap.servers"='127.0.0.1:9092'
 );

**Comment by gavinyue** [comment]
> {"c1": "\"","c2":"\\:","c3": "\\,","c4":"\\\"\\:\\,","c5":"\\{","c6":"\\}"}

**Comment by gavinyue** [comment]
![Image](https://github.com/matrixorigin/matrixone/assets/54566980/5b7f877c-d241-47a7-8e33-0f58acb7a9a4)

**Comment by heni02** [comment]
confirm,closed
<img width="1015" alt="企业微信截图_a608f36a-37f7-4d8a-bd1e-34b1fda9a3e7" src="https://github.com/matrixorigin/matrixone/assets/113406637/081baf1f-352d-44fb-8572-2748d660c2bd">
