### ISSUE TITLE
[Bug]: TPCC Consistency verification failed after running tpcc test on distributed mode for 1.0 regression

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13342]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):661daf0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7148974910/job/19472204633

<img width="1412" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d919c168-0c11-40b6-ba25-3e03441e1542">

2023-12-09 07:31:52 ERROR ConsistencyCheck:86 - Consistency verification failed for sql : (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);
2023-12-09 07:31:52 ERROR ConsistencyCheck:87 - The exceptional result are :
7	7	3853	

2023-12-09 07:31:52 ERROR ConsistencyCheck:86 - Consistency verification failed for sql : (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);
2023-12-09 07:31:52 ERROR ConsistencyCheck:87 - The exceptional result are :
7	7	3853	

2023-12-09 07:31:52 ERROR ConsistencyCheck:86 - Consistency verification failed for sql : (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
2023-12-09 07:31:52 ERROR ConsistencyCheck:87 - The exceptional result are :
7	22742387.56	

2023-12-09 07:31:52 ERROR ConsistencyCheck:86 - Consistency verification failed for sql : (Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);
2023-12-09 07:31:52 ERROR ConsistencyCheck:87 - The exceptional result are :
7	20668895.17	

the reason is that, the count of district table must be 100, but in this case, the count is 101, the exceptional data is:
mysql> Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district where d_w_id = 7 and d_id = 7;
+--------+------+-----------------+
| d_w_id | d_id | d_next_o_id - 1 |
+--------+------+-----------------+
|      7 |    7 |            3855 |
|      7 |    7 |            3853 |
+--------+------+-----------------+
2 rows in set (0.00 sec)

mo-log:
http://132.232.112.34:30088/explore?panes=%7B%22qHe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-661daf0%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221702106536322%22,%22to%22:%221702116629295%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by gouhongshen** [comment]
maybe related: #11236, #11850

**Comment by gouhongshen** [comment]
经查，block read 返回结构证实是数据存在重复：
``` 
{"level":"INFO","time":"2023/12/10 05:44:38.644522 +0000","caller":"blockio/read.go:118","msg":"read by filter log
input deletes len: 0
deletes mask len: 0
bat.vecs[0]: [1 1 1 1 1 1 1 1 1 1  2 2 2 2 2 2 2 2 2 2  3 3 3 3 3 3 3 3 3 3  4 4 4 4 4 4 4 4 4 4  5 5 5 5 5 5 5 5 5 5  6 6 6 6 6 6 6 6 6 6  7 7 7 7 7 7 7 7 7 7 7  8 8 8 8 8 8 8 8 8 8  9 9 9 9 9 9 9 9 9 9  10 10 10 10 10 10 10 10 10 10]
bat.vecs[1]: [1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10  1 2 3 4 5 6 7 8 9 10]
filter result len: 2
"}
```

**Comment by aptend** [comment]
```json
2023-12-09 15:35:24.053	
{"level":"INFO","time":"2023/12/09 07:35:24.053587 +0000","caller":"jobs/flushTableTail.go:299","msg":"[End]","operation":"[3050]FT-272505-bmsql_district","txn-start-ts":"1702107323858546397-0","ablks-deletes":3037,"ablks-merge-rows":101,"nblks-deletes":2231,"duration":"194.854495ms","operand":{"endTs":"1702107323481759781-0","a-blks":"ee967642-23-0,ee967642-24-0,ee967642-25-0,ee967642-21-0,ee967642-22-0,","deletes-src":"c8085288-0-0,ee967642-20-0,c7c3f8b4-0-0,","to-blks":"83abcd6b-0-0,"}}

2023-12-09 15:35:24.099	
{"level":"INFO","time":"2023/12/09 07:35:24.099495 +0000","caller":"txnentries/flushTableTail.go:236","msg":"flushtabletable Update 272505-bmsql_district LastFlush 1702107323481759781-0"}
```

内存中的 5 个 ablk flush 成一个有 101 行数据的 block，大概率已经包含重复数据了。并且可以确认，这 5 个 ablk 上不存在 start-ts ~ commit-ts  之间还发生 delete 的情况。所以从 ablk 中读内存 deletes 时可能有问题，或者去重不对

**Comment by XuPeng-SH** [comment]
无论是daily run，还是手写的高并发更新程序持续运行十几个小时，都没能再复现相关的问题。

**Comment by XuPeng-SH** [comment]
无法复现。启动循环daily run流程复现中

**Comment by LeftHandCold** [comment]
添加了debug日志，然后尝试复现。
<img width="1181" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/cbe2618b-ad5c-4a05-ad22-921305e48639">
发现cn会在同一个事务里会对同一行执行两次delete的操作（precommit delete 两次某一行）。明显不合理。
<img width="2206" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/8bc3716d-171a-4fe4-856f-5a310b06d8d5">
<img width="1806" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/395b24af-10ea-4008-b141-bf394d8001c9">

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
没有复现

**Comment by XuPeng-SH** [comment]
没有复现

**Comment by XuPeng-SH** [comment]
没有复现

**Comment by XuPeng-SH** [comment]
没有复现

**Comment by XuPeng-SH** [comment]
没有复现

**Comment by XuPeng-SH** [comment]
没有再复现

**Comment by XuPeng-SH** [comment]
没有再复现

**Comment by XuPeng-SH** [comment]
没有复现过

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
无法复现

**Comment by XuPeng-SH** [comment]
没有再复现

**Comment by XuPeng-SH** [comment]
修改了gc,等新的复现

**Comment by XuPeng-SH** [comment]
修改了gc,等新的复现

**Comment by XuPeng-SH** [comment]
1.1还未复现

**Comment by XuPeng-SH** [comment]
similar with https://github.com/matrixorigin/MO-Cloud/issues/2533

**Comment by XuPeng-SH** [comment]
not repro

**Comment by XuPeng-SH** [comment]
not repro

**Comment by XuPeng-SH** [comment]
not repro

**Comment by XuPeng-SH** [comment]
should be fixed by #14758

**Comment by XuPeng-SH** [comment]
should be fixed

**Comment by aressu1985** [comment]
fixed
