### ISSUE TITLE
[Bug]: Connection hung during the log node failure.

### ISSUE THREAD

**Issue by kbfu** [matrixorigin/matrixone#13356]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Initiate the log node failure, let's say we have 2 of 3 nodes killed constantly.
Then, let's run the create database during this experiment. You may find the client connection may be hung for a while.
The [logs](http://132.232.112.34:30088/d/f16aa89f-c4f1-4548-88e5-775ee060384c/logs?orgId=1&from=1702032647000&to=1702034565000&var-namespace=chaos-qke9td04l3ejpcj6&var-pod=All) may explain itself.
Expand the **Log create-databases-with-log-pod-del-2-wv4tg** section, you will see the gaps caused by the connection hung.
This could cause some problems in some circumstances.

### Expected Behavior

The connection should be reset from the server side and return some error.

### Steps to Reproduce

1. Start a new mo-cluster on TKE.
2. Create the databases constantly when the cluster is ready.
3. Kill 2 of 3 log nodes during the database creation.

**Comment by volgariver6** [comment]
by design, the committer tries to write data to logservice, and there is a timeout for this operation. so it will hang there and wait for the write operation to return successfully. If it does not return for 3 mins, the txn node will panic.

So there is no need to do any thing for now.
