### ISSUE TITLE
[Bug]: `show accounts` returns different db counts with `show databases`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13376]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev 5640276e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> show accounts;
+--------------------------------------+------------+---------------------+--------+----------------+----------+-------------+-------------+---------+
| account_name                         | admin_name | created             | status | suspended_time | db_count | table_count | size        | comment |
+--------------------------------------+------------+---------------------+--------+----------------+----------+-------------+-------------+---------+
| d6cbaa79_e481_4854_af17_e367d783ee75 | admin      | 2023-12-08 09:43:59 | open   | NULL           |        7 |          69 | 6386.973395 |         |
+--------------------------------------+------------+---------------------+--------+----------------+----------+-------------+-------------+---------+
1 row in set (21.80 sec)

mysql> show databases;
+--------------------------+
| Database                 |
+--------------------------+
| sbtest                   |
| mo_sample_data_tpch_sf1  |
| mo_sample_data_tpch_sf10 |
| tpcc_100                 |
| system                   |
| system_metrics           |
| information_schema       |
| mysql                    |
| mo_catalog               |
+--------------------------+
9 rows in set (0.09 sec)
```

`mo_sample_data_tpch_sf1` and `mo_sample_data_tpch_sf10` are created from publications.

### Expected Behavior

The same db account is returned

### Steps to Reproduce

```Markdown
Create database from publications and then run the above two commands
```

### Additional information

Refer to https://github.com/matrixorigin/MO-Cloud/issues/1992

**Comment by gouhongshen** [comment]
这个问题可能的原因是, `show accounts` 执行前会查询 account 的信息，使用到的 sql 有一个问题：
```
	getTableStatsFormatV2 = "select " +
		"( select " +
		"        mu2.user_name as `admin_name` " +
		"  from mo_catalog.mo_user as mu2 join " +
		"      ( select " +
		"              min(user_id) as `min_user_id` " +
		"        from mo_catalog.mo_user " +
		"      ) as mu1 on mu2.user_id = mu1.min_user_id " +
		") as `admin_name`, " +
		"count(distinct mt.reldatabase) as `db_count`, " +
		"count(distinct mt.relname) as `table_count`, " +
		"cast(0 as double) as `size` " +
		"from " +
		"mo_catalog.mo_tables as mt " +
		"where mt.relkind != '%s' and mt.account_id = %d;"
```

`--`

如果一个 db 下面没有任何 table，那么查询出来的 db 数量就会偏少。

改成下面的 sql 就好了。

```
	getTableStatsFormatV2 = "select " +
		"( select " +
		"        mu2.user_name as `admin_name` " +
		"  from mo_catalog.mo_user as mu2 join " +
		"      ( select " +
		"              min(user_id) as `min_user_id` " +
		"        from mo_catalog.mo_user " +
		"      ) as mu1 on mu2.user_id = mu1.min_user_id " +
		") as `admin_name`, " +
		"count(distinct md.datname) as `db_count`, " +
		"count(distinct mt.relname) as `table_count`, " +
		"cast(0 as double) as `size` " +
		"from " +
		"mo_catalog.mo_tables as mt, mo_catalog.mo_database as md " +
		"where mt.relkind != '%s' and mt.account_id = %d;"
```

**Comment by gouhongshen** [comment]
另外，`show databases` 返回的结果与 `mo_catalog.mo_tables` 里面统计的 db 信息可能有差异，以 `show databases` 的结果为准。`show databases` 实际上是从 `mo_catalog.mo_database` 里面统计的。

**Comment by gouhongshen** [comment]
@DanielZhangQD ptal

**Comment by DanielZhangQD** [comment]
Verified and passed with commit `b90bf97fe`

**Comment by Ariznawlll** [comment]
**commit(1.1.0)**：94a772491
**show accounts命令统计到的表个数不对：**
<img width="1386" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/4fd93185-cb6d-4b6a-a1ba-78c6ba0237f9">
<img width="1350" alt="截屏2024-01-04 18 38 22" src="https://github.com/matrixorigin/matrixone/assets/108530700/d96dc395-cd7d-427c-941b-cc77e9b93abd">
mo_sample_data_tpch_sf1 and mo_sample_data_tpch_sf10 are created from publications.

**mysql客户端连接：**mysql -h freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech -P 6001 -u 7f5f4653_6b15_48cb_b95b_b3872a3c1555:admin:accountadmin  -p
(if you need password, please contact me).

**Comment by gouhongshen** [comment]
不一致的原因在于 mo_catalog.mo_tables 里面的 records 和 show tables from * 总和不一致：

切换至 dump 用户
|
![image](https://github.com/matrixorigin/matrixone/assets/26336316/c48de0a9-e4f4-4efe-b7ce-b0a7ed179da9)
|
切换回租户, `show accounts` 使用的 sql
|
![image](https://github.com/matrixorigin/matrixone/assets/26336316/16c48d26-e416-4932-a1d3-908cd091a414)
|
![image](https://github.com/matrixorigin/matrixone/assets/26336316/887f299a-ff3e-4d25-9f4c-1ee7407b1a3c)
|

**Comment by gouhongshen** [comment]
有两个原因导致不同：
1. cloud 和内核统计 table stats 使用的 SQL 不同

cloud：
```sql
SELECT
    datname AS name,
    IF(table_cnt IS NULL, 0, table_cnt) AS tables,
    role_name AS owner,
    x.created_time AS created
FROM
    (
        SELECT
            dat_id,
            datname,
            mo_database.created_time,
            IF(role_name IS NULL, '-', role_name) AS role_name
        FROM
            mo_catalog.mo_database
        LEFT JOIN mo_catalog.mo_role ON mo_database.owner = role_id
    ) AS x
LEFT JOIN
    (
        SELECT
            COUNT(*) AS table_cnt,
            reldatabase_id
        FROM
            mo_catalog.mo_tables
        WHERE
            relkind IN ('cluster, 'e', 'v', 'r')
        GROUP BY
            reldatabase_id
    ) AS y ON x.dat_id = y.reldatabase_id;
```
|
内核统计方式：
```sql
SELECT 
    (
        SELECT 
            mu2.user_name AS `admin_name` 
        FROM 
            mo_catalog.mo_user AS mu2 
        JOIN (
            SELECT 
                MIN(user_id) AS `min_user_id` 
            FROM 
                mo_catalog.mo_user
        ) AS mu1 ON mu2.user_id = mu1.min_user_id
    ) AS `admin_name`, 
    COUNT(DISTINCT md.datname) AS `db_count`, 
    COUNT(DISTINCT mt.relname) AS `table_count`, 
    CAST(0 AS DOUBLE) AS `size`
FROM 
    mo_catalog.mo_tables AS mt, mo_catalog.mo_database AS md
WHERE 
    mt.relkind != 'partition' 
    AND mt.account_id = %d;
```
|
2. 使用的 `mo_catalog.mo_tables` 统计不到  subscription，即这里的 `mo_sample_data_tpch_sf1` 和 `mo_sample_data_tpch_sf10`

**Comment by gouhongshen** [comment]
这里可能需求可能要对一下，有一下几点不明确：
1. 租户订阅另一个租户的 db 后，`show accounts` 语义上是否应该看到这些 db 和 table
2. 如果能看到，那么`show accounts` 是否应当统计这些 db 和 table 的 storage usage.

**Comment by gouhongshen** [comment]
see design doc for more detail: https://github.com/gouhongshen/mo-docs/blob/main/show_accounts_optimization.md

**Comment by gouhongshen** [comment]
按照讨论的结果，show accounts 中 db，table 可见性的总结如下：
1. 是否统计订阅的 db，table 数量和 size 信息？（暂时都不统计）
2. 是否统计隐藏表(__index_*, mo_increment_columns 的数量和 size 信息？（个数不需要，size 需要）
3. 是否只统计属于该租户的 db 和 table（是否统计 mo_database，mo_tables, mo_column 这三张表）（都统计）

上述需求已完成。

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
show accounts 中 db，table 可见性的总结如下：
<img width="218" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8e634b8c-770c-4c1c-b614-2409d82e6d8f">

1. 假设有5张系统表，以及2张订阅表的，则统计的时候不统计订阅的 db，table 数量和 size 信息
<img width="1055" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/494e8dbd-d78f-47f8-aaeb-db9c5c0609a9">

db数量=5
table_count=table数量+view数量=63

**Comment by gouhongshen** [comment]
@Ariznawlll 已经统计了这些特殊的表了，自测过了。你可以再测测。

**Comment by Ariznawlll** [comment]
show accounts 统计 size 需求待确认，暂缓测试。等有结论再测

**Comment by tianyahui-python** [comment]
重点关注下: sys/非sys 租户下, cluster table 大小的统计

**Comment by gouhongshen** [comment]
目前 show accounts 的统计逻辑：
1. 除了 mo_catalog.mo_tables, mo_catalog.mo_databases, mo_catalog.columns 和 cluster table 外，其他普通 db、tbl 的数量和 size 都统计，这些特殊的表只统计数量，不统计 size。

mo_table_size，mo_table_rows：
非 sys 租户遇到 mo_catalog.mo_tables, mo_catalog.mo_databases, mo_catalog.columns 和 cluster table 都会直接返回 0

**Comment by Ariznawlll** [comment]
**普通租户：show accounts 中 db，table 可见性的测试如下：**

1. 假设有5张系统表，以及2张订阅表，表数量以及db统计数量如下：（统计的时候不统计订阅的 db，table 数量）

     db数量=5
     表数量=table数量+view数量=64 （统计mo_catalog数据库下的mo_tables、mo_databases、mo_columns）

3. 假设有5张系统表，以及2张订阅表，size信息统计步骤如下：（统计的时候不统计订阅表、集群表的size）
     2.1 通过mo_table_size()函数得到所有db下表的实际大小（不包括mo_tables、mo_databases、mo_columns这几张表）；
     2.2 通过sql得到索引表的实际大小；
     2.3 将2.1与2.2得到的结果求和，换算成字节，即为存储的实际大小，与show accounts结果中的size字段做比较。

<img width="1241" alt="企业微信截图_f788f69d-71a9-469b-96df-219017ba6833" src="https://github.com/matrixorigin/matrixone/assets/108530700/8946c56d-53e4-4f75-8a28-cbf0292150d7">

**Comment by LiSong0214** [comment]
> @DanielZhangQD 按照讨论的结果，show accounts 中 db，table 可见性的总结如下：
> 
> 1. 是否统计订阅的 db，table 数量和 size 信息？（暂时都不统计）
> 2. 是否统计隐藏表(__index_*, mo_increment_columns 的数量和 size 信息？（个数不需要，size 需要）
> 3. 是否只统计属于该租户的 db 和 table（是否统计 mo_database，mo_tables, mo_column 这三张表）（都统计）
> 
> 上述需求已完成。

这个结论要修改一下：
1、对于订阅库，只统计db数，其他都不统计（包括db size，table数、table size）；
2、对于 mo_database，mo_tables, mo_column 这三张表，只统计 table 数，不统计table size

**Comment by Ariznawlll** [comment]
**commit:5f7242890e392facdac921778bb749613cf82286**
普通租户：show accounts 中 db，table 可见性的测试如下：
1. 有5张系统表，以及1个订阅库resub01(表table01)，额外新建db test01(db中有表table01、table02)，db以及表的统计数量如下：（统计的时候不统计订阅的 db，table 数量）

     db数量为=普通表+订阅表+系统表=7
     表数量=table数量+view数量=65 (不计算订阅库中的table数量)
     <img width="854" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/47915080-cd71-499d-89b5-4bef08322d7c">
与show accounts的统计结果对应

    如果删除订阅库
    <img width="960" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6bdca2f8-d999-4fcf-b116-bda5b9bc21ab">
show accounts的统计中去除了对订阅库的统计，结果正确

    **结论：普通租户下，show accounts统计的db与table数量测试通过**

2. 系统租户下：
     1.1. 有7张系统表，以及1个订阅库resub01(表table01)，额外新建db big_data_test(db中有表table_basic_for_alter_100m、test_results)，db test01（表table01），db以及表的统计数量如下：（统计的时候统计订阅的 db，不统计table 数量）

     db数量为=9
     表数量=table数量+view数量=101 (不计算订阅库中的table数量，统计集群表的数量)
     <img width="968" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e623c8a3-0d93-42ff-bcde-5a0eb11a691b">

     新建一个订阅库resub01，db下有表table01-table05
     <img width="1029" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/be193c49-b8d0-4084-8ae5-baa78632f83f">

**结论：系统租户下，show accounts统计的db与table数量测试通过**
