### ISSUE TITLE
[Bug]: ut TestLockTableBindChanged fail in 1.0-dev

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#13373]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

fail link:https://github.com/matrixorigin/matrixone/actions/runs/7162684371/job/19500006818?pr=13365

**Comment by zhangxu19830126** [comment]
link was expired.
