### ISSUE TITLE
[Bug]: streaming:multiple identical keys in a row of JSON data, and the source only reads one row

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13371]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):57c79f04f35ec80a2e9b95958223c11cec68e13d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

json：{"c1": 5,"c1":6}
<img width="581" alt="企业微信截图_7fa39256-1e77-420d-bfb8-fafcac01faf7" src="https://github.com/matrixorigin/matrixone/assets/113406637/7a3e5824-0238-4bb7-be74-e9742c9f1cf4">

ddl:
create source s1(c1 int primary key,c2 varchar(25) not null)with("type"='kafka',     "topic"= 'test',     "partition" = '0',      "value"= 'json',     "bootstrap.servers"='127.0.0.1:9092'    );

**Comment by gavinyue** [comment]
这个确实只能读到一行， 因为一个json, 对应了一行。

里面两个c1  对应的这一行的列。

**Comment by gavinyue** [comment]
{"c1": 5, "c1":6} 这个不是valid json,  虽然可以parse, 但是parse后的结果， 就只会保留 第二个c1


json 里面一个level的key是不能duplicate的。

**Comment by heni02** [comment]
confirm，closed
