### ISSUE TITLE
[Bug]: ut TestTaskSchedulerCanScheduleTasksToCNs  fail in 1.1-dev branch

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#13372]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

fail link:https://github.com/matrixorigin/matrixone/actions/runs/7162685013/job/19500012679?pr=13364

**Comment by volgariver6** [comment]
测试用例中的端口占用的问题现在不好改，建议先关掉吧
