### ISSUE TITLE
[Bug]: streaming:create dynamic table if not exists table which is exists reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13397]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c4b255cbd0ee319c50210706a94eaf5d6084aadf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create dynamic table if not exists table which is exists reported ERROR 20904 (HY000): the connector for table db.dt0008 already exists
<img width="884" alt="企业微信截图_238e6ccb-8169-41ea-a372-0bae2ac45cb6" src="https://github.com/matrixorigin/matrixone/assets/113406637/a52906d4-c938-4b37-8b40-6b601524cc6a">

**Comment by gavinyue** [comment]
明白了，  需要检查是不是有if not exist tag. 

https://github.com/matrixorigin/matrixone/pull/13398/files


PR比较简单

**Comment by gavinyue** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/54566980/0c8b958c-9de0-4774-a6bc-3657d5a6a52d)

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13398

已经merge

**Comment by heni02** [comment]
confirm,closed
commit :09b923d8ca3ecef29c7ec6a6b80eb2c63e17cb9d
<img width="1384" alt="企业微信截图_7c73637e-0fbb-4569-a9e4-7c163a247338" src="https://github.com/matrixorigin/matrixone/assets/113406637/c9120471-754e-4029-b12c-a0eb21683893">
