### ISSUE TITLE
[Bug]: streaming: create dynamic table failed ,show connector status is running

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13396]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):57c79f04f35ec80a2e9b95958223c11cec68e13d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="810" alt="企业微信截图_8fb79a73-1f8f-4517-b4aa-c821d0939c6e" src="https://github.com/matrixorigin/matrixone/assets/113406637/43a874be-0667-4624-ab38-0b8cea6cfa83">
<img width="1421" alt="企业微信截图_f4156cf0-5607-4b69-9cd4-d04741e67ab9" src="https://github.com/matrixorigin/matrixone/assets/113406637/046291ce-cf03-48ee-9c0d-89c26f98dca3">
这个错导致再create一次报 the connector for table db.dt008 already exists

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/13348

已经merge

**Comment by heni02** [comment]
confirm,closed
commit:09b923d8ca3ecef29c7ec6a6b80eb2c63e17cb9d
<img width="1397" alt="企业微信截图_52e59e2b-676a-481d-814a-b73dd5b1ded7" src="https://github.com/matrixorigin/matrixone/assets/113406637/b40b5f43-5f8f-4a95-ac1d-e9becd051ebe">
