### ISSUE TITLE
[Bug]: locate函数行为与mysql不一致

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/matrixone#13426]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="313" alt="企业微信截图_3d47842e-1801-4eec-8a7a-f6d87ce54396" src="https://github.com/matrixorigin/matrixone/assets/153493538/fe65d74f-dd4a-43c3-a785-22cc8ee65c99">
mo中locate函数在第二个参数里面找第一个参数的位置，与mysql行为不一致

### Expected Behavior

<img width="305" alt="企业微信截图_8a14b797-2dd2-4e56-9d32-adf6e5f3aed4" src="https://github.com/matrixorigin/matrixone/assets/153493538/29856970-a7bd-4a17-8750-0b70ad0ac7f0">
应该与mysql保持一致，在第二个参数里面找第一个参数的位置

**Comment by yangj1211** [comment]
更正：mo中locate函数是在第一个参数里面找第二个参数的位置

**Comment by daviszhen** [comment]
moc 2013 在做。

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test， @yangj1211 @daviszhen @dengn

**Comment by Ariznawlll** [comment]
test done!

**Comment by aressu1985** [comment]
问题解决，关闭
