### ISSUE TITLE
[Bug]: missing error capture leads to confusing script log

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#13456]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

现象：
日志里面mo执行create database 失败。
<img width="2947" alt="企业微信截图_cbeeff84-8838-429f-b18d-54b5e881686b" src="https://github.com/matrixorigin/matrixone/assets/60595215/7ef9b102-7021-4322-a06b-e832eba181f3">

但是regression 里面显示create database 成功
<img width="1137" alt="企业微信截图_17649e4f-9f60-40f2-882b-14ebf74595f3" src="https://github.com/matrixorigin/matrixone/assets/60595215/5b075aaa-21ee-4df5-8f99-474d9343f057">

会导致迷惑的行为。给定位mo出错日志造成不便。loki 找日志非常麻烦。

初步看是脚本错误处理没检测到mo的错误。

https://github.com/matrixorigin/mo-load-data/blob/dd8f46477ab11d0a6d06e271d9899fc400204d59/load.sh#L274

### Expected Behavior

1, regression脚本 能正常捕获mo的错误。
2，遇到错误时，脚本停止后续的执行。
3，错误日志run.log 上传。方便后续定位。
需要被重定向的error日志
<img width="1190" alt="企业微信截图_a3f195cf-5e04-466c-9e10-ff779da47b5b" src="https://github.com/matrixorigin/matrixone/assets/60595215/db4296a6-da23-47fd-952d-cb7ffaa693bd">

**Comment by aressu1985** [comment]
fixed
