### ISSUE TITLE
[Bug]: Sysbench test performance degradation. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13452]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6c44721994d3d553bae7398ccd133308ddb9fb08（branch:1.1-dev）
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
**sysbench测试 point_select、delete、update、insert性能下降.**

**回归workflow**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7181042722/job/19574409431

**二分workflow**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7190312406/job/19583612523

**二分workflow与回归workflow的区别：**
二分workflow只包含sysbench测试流程；
回归workflow包含所有的测试流程（ssb、tpcc、tpch、sysbench、load data）.

point_select测试点查结果（相同commit，二分结果与回归结果差别很大）：
<img width="485" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/52782c97-4088-4271-9a33-bcb3fe103400">
delete、update、insert与point_select现象一样。

metrics：http://132.232.112.34:30088/dashboards/f/d00aeb00-b1cf-4900-a2aa-5739560dec0b/matrixone

**Comment by Ariznawlll** [comment]
[1214] Tpcc performance degradation on tke.
<img width="1344" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/917f93c8-86db-4ca7-b425-0621b6c85f84">

tpcc 10w回归结果与二分结果(同一个commit，二分结果与回归结果差距很大)：
commit_id: 3a1356485fc2aa4d305478aaa3110899ea8c1025

回归workflow：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7196734747/job/19624254406
二分workflow：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7209398347/job/19640257187

<img width="656" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b0de7fb3-2373-46af-8def-600e163249b9">


metrics：http://132.232.112.34:30088/dashboards/f/d00aeb00-b1cf-4900-a2aa-5739560dec0b/matrixone

**Comment by guguducken** [comment]
回归sysbench测试时间为：2023-12-13 05:04:00到2023-12-13 06:16:00，故截取此段时间cn的腾讯云cvm监控

nightly-regression-dis-tp-cn-nrgf5
<img width="1632" alt="image-20231215175809430" src="https://github.com/matrixorigin/matrixone/assets/22561920/89846b04-e023-4859-8eec-b923f07517a9">

nightly-regression-dis-tp-cn-q54wm

<img width="1616" alt="image-20231218104919814" src="https://github.com/matrixorigin/matrixone/assets/22561920/a3497b6b-517e-4a97-a69f-23d290dec2d4">

**Comment by guguducken** [comment]
二分sysbench测试时间为：2023-12-13 08:49:00到2023-12-13 12:10:00，截取此段时间cn的腾讯云cvm监控

- nightly-regression-dis-tp-cn-4v29z
<img width="1622" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/d894e322-9079-489d-bbc9-b3b8db594e40">

- nightly-regression-dis-tp-cn-q54wm
<img width="1625" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/701482fb-8d8c-4429-886e-f91670fb9f9d">

- nightly-regression-dis-tp-cn-qvksz
<img width="1611" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/5691ae2b-26e7-47d0-b051-91f15343531f">

**Comment by guguducken** [comment]
回归tpcc测试时间为：2023-12-13 03:11:00到2023-12-13 07:12:00，截取此段时间cn的腾讯云cvm监控
- nightly-regression-dis-tp-cn-62nsg
<img width="1618" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/3c227ba3-55f3-48d1-8ccb-015213634037">

- nightly-regression-dis-tp-cn-v6s6n
<img width="1619" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/8ea8d532-ffde-420e-b90e-edb4b15f9e64">

- nightly-regression-dis-tp-cn-zgh7r 
<img width="1619" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/aef9dc4a-dad9-45ca-926b-e1f26e4de5af">

**Comment by guguducken** [comment]
二分tpcc测试时间为：2023-12-14 21:23:00到2023-12-14 21:37:00，截取此段时间cn的腾讯云cvm监控

- nightly-regression-dis-tp-cn-rwfr4
<img width="1621" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/19231a2b-1deb-4ba4-a1fd-6d12e5ea0688">

- nightly-regression-dis-tp-cn-xnprb
<img width="1617" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/5521f1b2-254b-4460-9128-e9b48a0ab098">

- nightly-regression-dis-tp-cn-z66mp
<img width="1626" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/40181cc1-e550-49cf-8dec-f71ae9690135">

**Comment by aunjgr** [comment]
暂无进展

**Comment by aunjgr** [comment]
明天看

**Comment by ouyuanning** [comment]
辛苦张旭在优化并发抢share锁的问题

**Comment by ouyuanning** [comment]
已经提交了PR，待合并再看看

**Comment by ouyuanning** [comment]
张旭的PR已合并。待观察效果

**Comment by ouyuanning** [comment]
目前已恢复到2.4W左右。

因为测试中很多是空行，并非都是真实delete操作。完全都是delete的操作，我自己测试的结果是回退在1%-2%左右。
后续如果要继续优化删空行的情况，可以另外再起issue吧。

**Comment by Ariznawlll** [comment]
<img width="717" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0b50cf9e-3349-4429-8322-b2246c79c246">

稳定在2.4w左右，Verified!
