### ISSUE TITLE
[Bug]: the content of ak/sk is not encrypted in mo logs

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13468]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1388" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/837b1d4d-8ae4-4923-8818-f5d1b40f351c">

**Comment by reusee** [comment]
PRs sent.

**Comment by aressu1985** [comment]
fixed
