### ISSUE TITLE
[Tech Request]: make proxy timeout configurable

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#13465]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
make proxy timeout configurable
```

### Why is this needed ?

https://github.com/matrixorigin/MO-Cloud/issues/2019

When connect/auth timeout, CN would be considered unreachable and client would not able to access CN, the timeout should be configurable so that we can tune the config according to the environment CN and Proxy deployed.

**Comment by volgariver6** [comment]
done

**Comment by aylei** [comment]
等待验证一下

**Comment by aylei** [comment]
closed via #13473
