### ISSUE TITLE
[Tech Request]: mo_logger 使用指定label的CN

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#13470]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
支持mo_logger 使用独享的CN 完成MO内部的负载任务，至少需要一下几点：

1. MO Cluster 支持 mo_logger 挑选指定 tag 的 CN
2. MO Cloud 提供指定的CN，并将按照 MO Cluster提供的方式将 tag 落入MO hakeeper
```

### Why is this needed ?

ref: https://github.com/matrixorigin/MO-Cloud/issues/1800

在目前的实现中，所有MO Node 都会连接到一个（随机挑选的）CN上完成相关的`load data inlie`写入操作；为了隔离该负载对 其他租户的影响，需考虑mo_logger 在指定的 CN中运行。

**Comment by aylei** [comment]
@xzxiong @sukki37 I suggest p-1 for this issue, since https://github.com/matrixorigin/MO-Cloud/issues/1800 is p-1 for cloud

**Comment by xzxiong** [comment]
after pr #12720 , 已经支持了 label挑选的逻辑（如下图）
但需要进一步支持 可配置label 的方式进行筛选，适应云上的使用场景 

![image](https://github.com/matrixorigin/matrixone/assets/3927687/aa4ab1ea-4d48-45be-a8b1-60384fb5b24b)

**Comment by aylei** [comment]
不需要 design review, issue 同步技术方案

**Comment by xzxiong** [comment]
wait pr merge

**Comment by xzxiong** [comment]
pr merged

**Comment by aressu1985** [comment]
test done
