### ISSUE TITLE
[Bug]: CN FATAL 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13477]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7205511780

<img width="1895" alt="企业微信截图_ad0b0538-9c49-456a-99b1-37e955412c24" src="https://github.com/matrixorigin/matrixone/assets/77312370/e199ace5-987b-4e0e-a69f-bb3ae9ca47c3">

### Additional information

cc @nnsgmsone @zhangxu19830126

**Comment by ouyuanning** [comment]
还没找到原因

**Comment by ouyuanning** [comment]
在处理 https://github.com/matrixorigin/MO-Cloud/issues/2034

**Comment by ouyuanning** [comment]
下周先加点日志吧。先确认下是 affectrows问题，还是数据正确性问题

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
已经加了日志，暂未复现

**Comment by ouyuanning** [comment]
可能跟https://github.com/matrixorigin/matrixone/issues/13911是一个问题。
如果还无法复现可以先关掉。等复现继续看吧

**Comment by ouyuanning** [comment]
在处理  Column Group的需求。还没时间处理。

**Comment by aressu1985** [comment]
先关闭，待出现在新issue跟踪吧
