### ISSUE TITLE
[Bug]: Data is committed with error `Error 1105 (HY000): context deadline exceeded`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13489]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0 nightly-90dac68d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Insert records in a transaction, and `Error 1105 (HY000): context deadline exceeded` is returned to the client, however, the data has already been inserted into MO, so when the client retries inserting the data, `Error 1062 (HY000): Duplicate entry` error is fired

### Expected Behavior

Not sure if it's the correct behavior to roll back the transaction with error `Error 1105 (HY000): context deadline exceeded`

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

### Additional information

Similar issue with https://github.com/matrixorigin/matrixone/issues/11223

**Comment by ouyuanning** [comment]
还没看

**Comment by ouyuanning** [comment]
还没看，在处理https://github.com/matrixorigin/MO-Cloud/issues/2034

**Comment by DanielZhangQD** [comment]
报错应该发生在 2023/12/15 01:03:02.895849 +0000 - 2023/12/15 01:05:39.852084 +0000
Log:
http://121.43.41.174/explore?panes=%7B%22y-p%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702602120000%22,%22to%22:%221702602359000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ouyuanning** [comment]
http://121.43.41.174/explore?panes=%7B%22y-p%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60context%20deadline%20exceeded%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702602000000%22,%22to%22:%221702602359000%22%7D%7D%7D&schemaVersion=1&orgId=1

从日志看，是commit的时候发生了超时
![image](https://github.com/matrixorigin/matrixone/assets/45346669/dccf1d42-ce76-41f0-b9a3-d1fbda2bed1d)

似乎无法杜绝commit超时的事情。可能要拉大家一起确认一下处理方案。
1、增加超时时间？那多少合适？
2、dn对于超时进行检测，然后做处理（好像很难处理？）
3、客户端碰到超时的情况，改用insert on duplicate key update

**Comment by ouyuanning** [comment]
commit超时的原因是这个
https://github.com/matrixorigin/MO-Cloud/issues/1501

但是即使1501解决了，应该也无法杜绝超时的问题。

**Comment by aptend** [comment]
flush 导致性能下降的问题已修复
