### ISSUE TITLE
[Bug]: LOAD DATA Report internal error: message body 157032805 is too large, max is 104857600

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#13485]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE `sbtest1` (
`id` INT NOT NULL,
`k` INT DEFAULT 0,
`c` CHAR(120) DEFAULT '',
`pad` CHAR(60) DEFAULT '',
PRIMARY KEY (`id`)
) partition by key algorithm = 2 (id) partitions 100 

mysql> LOAD DATA INFILE "/data2/wuxiliang/workspace/loadfile/sbtest5000w.csv" INTO TABLE sbtest1 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
ERROR 20101 (HY000): internal error: message body 157032805 is too large, max is 104857600

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/9eb07629-1d35-44cc-bec7-d755b1b22af9)

**Comment by qingxinhome** [comment]
---------------------------wuxiliang--------------------------->[174: <36cfa11a7c6446e3b7a4bbc61c454943/Active/S:1702606561923699992-1>/Commit/F-1/=><2-262146-0-127.0.0.1:19000>]
---------------------------------wuxiliang---PrintStack-----------------------------------
goroutine 1939 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/matrixorigin/matrixone/pkg/common/morpc.(*messageCodec).Valid(0xc003087020, {0x4278888, 0xc00e5604e0})
	/data2/wuxiliang/workspace/matrixone/pkg/common/morpc/codec.go:144 +0x10a
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).doSend(0xc0005471e0, 0xc00ebc77c0)
	/data2/wuxiliang/workspace/matrixone/pkg/common/morpc/backend.go:337 +0x68
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).send(0x987cf1?, {0x425e298?, 0xc001480570?}, {0x4278888?, 0xc00e5604e0?}, 0x40?)
	/data2/wuxiliang/workspace/matrixone/pkg/common/morpc/backend.go:300 +0x4b
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).Send(0xc0019fd8c0?, {0x425e298?, 0xc001480570?}, {0x4278888?, 0xc00e5604e0?})
	/data2/wuxiliang/workspace/matrixone/pkg/common/morpc/backend.go:288 +0x35
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).Send(0x2?, {0x425e298, 0xc001480570}, {0xc00fb5bad0, 0xf}, {0x4278888, 0xc00e5604e0})
	/data2/wuxiliang/workspace/matrixone/pkg/common/morpc/client.go:186 +0xd7
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*sender).doSend(_, {_, _}, {0x0, {{0xc006297d80, 0x10, 0x10}, 0x0, {0x17a0dfa5b3b61518, 0x1, ...}, ...}, ...})
	/data2/wuxiliang/workspace/matrixone/pkg/txn/rpc/sender.go:173 +0x2b5
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*sender).Send(0xc003190dc0, {0x425e298, 0xc001480570}, {0xc00e560340, 0x1, 0x1?})
	/data2/wuxiliang/workspace/matrixone/pkg/txn/rpc/sender.go:112 +0x95c
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).doSend(0xc00f5ea240, {0x425e298, 0xc001480570}, {0xc00e560340?, 0x1, 0x1}, 0x1)
	/data2/wuxiliang/workspace/matrixone/pkg/txn/client/operator.go:792 +0x1a6
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).doWrite(0xc00f5ea240, {0x425e298, 0xc001480570}, {0x0?, 0x0, 0x0}, 0x1)
	/data2/wuxiliang/workspace/matrixone/pkg/txn/client/operator.go:667 +0x931
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Commit(0xc00f5ea240, {0x425e298, 0xc001480570})
	/data2/wuxiliang/workspace/matrixone/pkg/txn/client/operator.go:472 +0x295
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CommitTxn(0xc005dd0180)
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/txn.go:354 +0x7ad
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).TxnCommitSingleStatement(0x3a7a99d?, {0x42608e0, 0xc012f9a1e0})
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/txn.go:670 +0x6a
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt.func4()
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:2827 +0xdb
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt.func5()
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:2842 +0xb9
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt.func7()
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:2877 +0x28
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt(0xc011efc840, {0x425e298, 0xc012f98630}, 0xc012880c00, {0x42608e0, 0xc012f9a1e0}, 0xc00722a600, {0x428e728?, 0xc012f9a230?}, 0x0, ...)
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:3722 +0x534a
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc011efc840, {0x425e298?, 0xc012f983f0?}, 0xc00fd8e1c0)
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:3903 +0x1708
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc011efc840, {0x425e298, 0xc012f983f0}, 0x6063190?, 0xc012f8e5b8)
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:4067 +0x848
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc005dd0100, 0xc012f8e5b8)
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/routine.go:285 +0x57b
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc005071030, {0x4294be0, 0xc0041f0000}, {0x3410400?, 0xc00d897bc0}, 0x4286df8?)
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/routine_manager.go:494 +0xce7
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc00905d400, {0x4294be0, 0xc0041f0000})
	/data2/wuxiliang/workspace/matrixone/pkg/frontend/server.go:145 +0xc5
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/data2/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/data2/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x485
------------------------------------------------------------------------------------------

**Comment by qingxinhome** [comment]
以如下commit为分界
2fd77b849cb7cca57ec6546a930cd66c45a13ca3
该commit代码相较于之前版本，在执行load data时耗时更长，产生的数据文件更大，且会发生报错
<img width="1003" alt="企业微信截图_17027869845843" src="https://github.com/matrixorigin/matrixone/assets/70939751/b07f04ee-ae88-43f9-bc8d-47a12e090f0b">

**Comment by qingxinhome** [comment]
复现该问题的测试用例：
在129机器上启动mo，并执行如下sql：

create database sysbench_db;

use sysbench_db;

CREATE TABLE `sbtest1` (
`id` INT NOT NULL,
`k` INT DEFAULT 0,
`c` CHAR(120) DEFAULT '',
`pad` CHAR(60) DEFAULT '',
PRIMARY KEY (`id`)
) partition by key algorithm = 2 (id) partitions 100;


LOAD DATA INFILE "/data2/wuxiliang/workspace/loadfile/sbtest5000w.csv" INTO TABLE sbtest1 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

**Comment by badboynt1** [comment]
fixed
