### ISSUE TITLE
[Bug]: mo_tables/mo_databses/mo_columns need a true rowid

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#13494]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

因为目前这三个表没有真实的rowid而采用tableid/dbid/colid来模拟一个rowid出来，这样会导致如果想要更新这三个表中的任意一行，无法通过delete+insert的组合来实现这个功能，目前是采用一些比较hack的方式来处理更新。
另外这三个表的主键也是不合理，目前的主键都是id，主键是通过cn端hack得到的。

### Expected Behavior

这三个表应该和所有普通的表一样，都有一个真实的rowid。另外都应该有一个真实的主键，主键的信息如下:
* mo_tables: account_id+database_id+table_name
* mo_databses: account_id + database_name
* mo_columns: account_id + database+id + table_id + column_name

**Comment by XuPeng-SH** [comment]
depends on #15431

**Comment by aressu1985** [comment]
DONE
