### ISSUE TITLE
[Bug]:  [1214] 128 sysbench 'point select' performance degradation.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13508]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="932" alt="企业微信截图_d68bfaf9-568e-443e-95d3-f7e5a749656c" src="https://github.com/matrixorigin/matrixone/assets/108530700/094f729b-0973-4faf-9def-f44391112d8a">

**Comment by Ariznawlll** [comment]
@nnsgmsone  修改完后，性能已经恢复。

**Comment by nnsgmsone** [comment]
pr已经提交，等待merge

**Comment by Ariznawlll** [comment]
<img width="1343" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/80ee4a3c-f2b5-4600-a6ed-99d737749699">

点查性能已恢复.
