### ISSUE TITLE
[Bug]: internal error: unknown data type

### ISSUE THREAD

**Issue by zengyan1** [matrixorigin/matrixone#13503]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1600" alt="企业微信20231215-150903@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/4c407459-6067-40a9-9f7c-01b3c8d0f1b8">
<img width="1611" alt="企业微信20231215-150919@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/1e63802a-b6d6-4bc1-b9e4-55e1b2c7a5da">
<img width="1618" alt="企业微信20231215-150938@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/b3fa110f-5253-4b89-a15a-4925042ea866">

### Steps to Reproduce

```Markdown
http://121.43.41.174/explore?panes=%7B%22fk-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixone_cloud_account_id%3D%5C%22ca3e7774_2e2e_4182_b43a_fd7ae6c55ade%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221701884445118%22,%22to%22:%221701886300200%22%7D%7D%7D&schemaVersion=1&orgId=1
```

**Comment by gavinyue** [comment]
已知bug. 
https://github.com/matrixorigin/matrixone/issues/12262
