### ISSUE TITLE
[Bug]:  If the field name of the table is stream or enable when creating the table, the creation will fail!

### ISSUE THREAD

**Issue by iwanlebron** [matrixorigin/matrixone#13511]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0.0
- Hardware parameters:
- OS type: linux-amd64
- Others:
```

### Actual Behavior

CREATE TABLE wvp_stream_proxy (
	id INT AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR ( 50 ),
	app VARCHAR ( 255 ),
	stream VARCHAR ( 255 ),
	url VARCHAR ( 255 ),
	src_url VARCHAR ( 255 ),
	dst_url VARCHAR ( 255 ),
	timeout_ms INT,
	ffmpeg_cmd_key VARCHAR ( 255 ),
	rtp_type VARCHAR ( 50 ),
	media_server_id VARCHAR ( 50 ),
	enable_audio BOOLEAN DEFAULT FALSE,
	enable_mp4 BOOLEAN DEFAULT FALSE,
	ENABLE BOOLEAN DEFAULT FALSE,
	STATUS BOOLEAN,
	enable_remove_none_reader BOOLEAN DEFAULT FALSE,
	create_time VARCHAR ( 50 ),
	NAME VARCHAR ( 255 ),
	update_time VARCHAR ( 50 ),
	stream_key VARCHAR ( 255 ),
	enable_disable_none_reader BOOLEAN DEFAULT FALSE,
	CONSTRAINT uk_stream_proxy_app_stream UNIQUE ( app, stream ) 
)
> 1064 - SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 5 column 8 near "
	stream VARCHAR ( 255 ),
	url VARCHAR ( 255 ),
	src_url VARCHAR ( 255 ),
	dst_url VARCHAR ( 255 ),
	timeout_ms INT,
	ffmpeg_cmd_key VARCHAR ( 255 ),
	rtp_type VARCHAR ( 50 ),
	media_server_id VARCHAR ( 50 ),
	enable_audio BOOLEAN DEFAULT FALSE,
	enable_mp4 BOOLEAN DEFAULT FALSE,
	ENABLE BOOLEAN DEFAULT FALSE,
	STATUS B
> Time: 0.005s

**Comment by daviszhen** [comment]
@YANGGMM  可能是关键字问题。

**Comment by aronchanisme** [comment]
https://github.com/matrixorigin/MO-Cloud/issues/2059

**Comment by YANGGMM** [comment]
fixed
