### ISSUE TITLE
[Subtask]: refactor blocking class operators to avoid OOM

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#13524]
### Parent Issue
#10729

筛一遍所有的阻塞类算子，避免mpool申请过多内存的问题和内存占用过多问题
目前自己预计要处理的算子包含：
1、mergeorder
2、lock_op
3、on_duplicate_key

其他join相关的算子，由龙冉通过spill那个issue处理。这里处理非join相关的阻塞类算子

### Detail of Subtask

This issue is a summary of related task issues:
- [x] #12956 
- [ ] #12021
- [ ] https://github.com/matrixorigin/MO-Cloud/issues/1921 
- [ ] https://github.com/matrixorigin/MO-Cloud/issues/496
- [ ] #14038

**Comment by ouyuanning** [comment]
可以先筛选出要改造的算子清单。
然后挨个看使用什么方案处理，看是否有可以抽象的

**Comment by florashi181** [comment]
待进一步讨论和spill issue的分工和方案 https://github.com/matrixorigin/matrixone/issues/13640

**Comment by florashi181** [comment]
与内存issue 关联 https://github.com/matrixorigin/matrixone/issues/13524

**Comment by ouyuanning** [comment]
在spill的issue跟踪，这里先关闭
