### ISSUE TITLE
[Bug]: MOC订阅同账户下其他实例发布的数据库后报错ErrServer，然后实例不可用

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixone#13542]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version: 8.0.30-MatrixOne-v1.0.0 (matrixonecloud.cn)
- Others: 在cn-dev.matrixone.tech下的moc版本中测试正常
```

### Actual Behavior

```sql
-- 在实例1中创建库表和导入测试数据
create database pub_db;
CREATE TABLE pub_db.customer (
customer_id INT,
customer_name VARCHAR(255)
);

insert into pub_db.customer values(1001,'matrixone');

-- 在实例1中将数据库pub_db发布给指定实例
create publication pub_moc  database  pub_db account `629155dd9_d454_4b02_be16_0741d94b62cc`;

-- 在实例2中对源实例发布的数据库执行订阅命令
create database sub_db from `0b6d35cc_11ab_4da5_a5c5_c4cc09917c11` publication pub_moc;
-- 执行订阅命令后，实例报错 Internal Server Error ，并弹窗：ErrServer

### Expected Behavior

_No response_

### Steps to Reproduce

_No response_

### Additional information

_No response_

**Comment by DanielZhangQD** [comment]
@WuMenglong 麻烦发一下实例1 和 实例 2 的 实例 ID 以及 SQL 的大概执行时间，谢谢

**Comment by DanielZhangQD** [comment]
创建订阅库 Account：62915dd9_d454_4b02_be16_0741d94b62cc
发布 Account：0b6d35cc_11ab_4da5_a5c5_c4cc09917c11

1. 发布订阅没有问题
2. 用户实例创建订阅库后，数据库列表无法获取，错误如下（登录 62915dd9_d454_4b02_be16_0741d94b62cc 执行），导致 issue 中的问题：
```
MySQL [(none)]> SHOW SUBSCRIPTIONS;
ERROR 1105 (HY000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 30 near " 0b6d35cc_11ab_4da5_a5c5_c4cc09917c11 publication pub_moc";
```

**Comment by tianyahui-python** [comment]
线上bug 先用s-1跟吧, 等有了具体的root cause, 再判断是否需要降级

**Comment by DanielZhangQD** [comment]
log:
http://121.43.41.174/explore?panes=%7B%22y-p%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
root cause:
发布account `0b6d35cc_11ab_4da5_a5c5_c4cc09917c11`，
订阅account `62915dd9_d454_4b02_be16_0741d94b62cc`, 订阅的时候的语句**create database sub_db from `0b6d35cc_11ab_4da5_a5c5_c4cc09917c11` publication pub_moc;**
但是在SHOW SUBSCRIPTIONS;的时候会重新获取这个stmt 然后parser获取发布库的account，但是这个时候stmt 在存储的时候已经格式化成**create database sub_db from 0b6d35cc_11ab_4da5_a5c5_c4cc09917c11 publication pub_moc;**，这个时候再去parse就会报语法错误。

**Comment by YANGGMM** [comment]
<img width="1475" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/49968e51-d3f0-42e0-9cdf-86f5f16fad2c">
这个问题最根本的原因还是parser的原因，具体的要问一下 @iamlinjunhong

**Comment by YANGGMM** [comment]
等待pr 合进去
