### ISSUE TITLE
[Bug]: 用户实例里面出现大量执行的报错

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#13551]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1406" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/13c9e55b-2544-4769-b0f3-f2a8042d08aa">

{"level":"ERROR","time":"2023/12/18 02:17:48.652876 +0000","name":"cn-service.frontend","caller":"frontend/util.go:506","msg":"query trace status","uuid":"34633564-3535-3066-3961-613739663138","connection_id":89595855,"statement":"SELECT * FROM (SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, CASE WHEN TABLE_TYPE = 'BASE TABLE' THEN CASE WHEN TABLE_SCHEMA = 'mysql' OR TABLE_SCHEMA = 'mo_catalog' THEN 'SYSTEM TABLE' ELSE 'TABLE' END WHEN TABLE_TYPE = 'TEMPORARY' THEN 'LOCAL_TEMPORARY' ELSE TABLE_TYPE END AS TABLE_TYPE, TABLE_COMMENT AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME, NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '**pub_db**'  ) AS t1 WHERE TABLE_TYPE IN ('TABLE','VIEW',null,null,null) ORDER BY TABLE_TYPE, TABLE_SCHEM, TABLE_NAME","status":"fail","error":"internal error: panic runtime error: index out of range [0] with length 0: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:113\ngithub.com/matrixorigin/matrixone/pkg/partition.bytesPartition\n\t/go/src/github.com/matrixorigin/matrixone/pkg/partition/partition.go:80\ngithub.com/matrixorigin/matrixone/pkg/partition.Partition\n\t/go/src/github.com/matrixorigin/matrixone/pkg/partition/partition.go:138\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/order.(*container).sortAndSend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:172\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/order.Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:255\ngithub.com/matrixorigin/matrixone/pkg/vm.fubarRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:69\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:104\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:89\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:457\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:199\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:135\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","span":{"trace_id":"cb8e817e-fcd2-acb4-95ee-1fa6bfd8e940","span_id":"4132d1070ead3c17"},"session_info":"connectionId 89595855|172.20.74.131:45292|{account 0b6d35cc_11ab_4da5_a5c5_c4cc09917c11:admin:accountadmin -- 219000002:2:2}|goRoutineId 14417355|99ffad36-9d4b-11ee-95a5-363f03f3fb34","session_id":"99ffad36-9d4b-11ee-95a5-363f03f3fb34","statement_id":"a3825447-9d4b-11ee-95a5-363f03f3fb34"}

{"level":"ERROR","time":"2023/12/18 02:17:48.652809 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:2775","msg":"internal error: panic runtime error: index out of range [0] with length 0: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:113\ngithub.com/matrixorigin/matrixone/pkg/partition.bytesPartition\n\t/go/src/github.com/matrixorigin/matrixone/pkg/partition/partition.go:80\ngithub.com/matrixorigin/matrixone/pkg/partition.Partition\n\t/go/src/github.com/matrixorigin/matrixone/pkg/partition/partition.go:138\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/order.(*container).sortAndSend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:172\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/order.Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:255\ngithub.com/matrixorigin/matrixone/pkg/vm.fubarRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:69\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:104\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:89\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:457\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:199\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:135\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","uuid":"34633564-3535-3066-3961-613739663138","session_info":"connectionId 89595855|172.20.74.131:45292|{account 0b6d35cc_11ab_4da5_a5c5_c4cc09917c11:admin:accountadmin -- 219000002:2:2}|goRoutineId 14417355|99ffad36-9d4b-11ee-95a5-363f03f3fb34","session_id":"99ffad36-9d4b-11ee-95a5-363f03f3fb34","statement_id":"a3825447-9d4b-11ee-95a5-363f03f3fb34"}

更多关联信息可以看：https://github.com/matrixorigin/matrixone/issues/13542

**Comment by xzxiong** [comment]
验证了一下 1.0.0 版本，应该是个老问题
```
mysql> create database test;
Query OK, 1 row affected (0.02 sec)

mysql> use test;
Database changed

mysql> create table user_info (id int, name varchar(123));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test.user_info values(1, 'xzxiong'), (2, 'jacksonxie');
Query OK, 2 rows affected (0.02 sec)

mysql> select NULL as val, u.id from test.user_info u order by val, id;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0:
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/partition.bytesPartition
	/Users/jacksonxie/go/src/github.com/matrixorigin/matrixone/pkg/partition/partition.go:80
github.com/matrixorigin/matrixone/pkg/partition.Partition
	/Users/jacksonxie/go/src/github.com/matrixorigin/matrixone/pkg/partition/partition.go:138
github.com/matrixorigin/matrixone/pkg/sql/colexec/order.(*container).sor

mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 6d1f96eb9     |   -- tag: 1.0.0, commit_id
+---------------+
1 row in set (0.00 sec)
```

**Comment by m-schen** [comment]
已修复，合并入main, 1.0, 1.1，可以进行验证。
