### ISSUE TITLE
[Bug]: after navicat connects to mo, the database tables cannot be displayed

### ISSUE THREAD

**Issue by iwanlebron** [matrixorigin/matrixone#13579]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): v1.0.1
- Hardware parameters: 
- OS type: darwin arm64 
- Others:
```

### Actual Behavior

<img width="1120" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/f9dd9e9e-1450-40ad-a441-2b51592ab434">
<img width="356" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/98b2ff0e-8bf2-4b2a-9ddc-e75847320174">

**Comment by daviszhen** [comment]
与moc 2052 ， 1942 都是类似的问题。
