### ISSUE TITLE
[Bug]: mo_ctl merge hung

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#13577]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 9f9f19644
- Hardware parameters:
- OS type: Mac
- Others:
```

### Actual Behavior

Two sessions, 
```
-- session one
create table bugt(i int not null, j int not null, k int, primary key (i, j));

select mo_ctl('dn', 'inspect', 'policy -m 0 -r 0');

insert into bugt values (1, 1, 1), (2, 2, 2);
select mo_ctl('dn', 'flush', 'repro.bugt');

insert into bugt values (3, 3, 3), (4, 4, 4);
select mo_ctl('dn', 'flush', 'repro.bugt');

begin;
update bugt set k = k+1 where i = 1 and j = 1;

select * from bugt;
+------+------+------+
| i    | j    | k    |
+------+------+------+
|    1 |    1 |    2 |
|    2 |    2 |    2 |
|    3 |    3 |    3 |
|    4 |    4 |    4 |
+------+------+------+
4 rows in set (0.00 sec)
```

At this moment, session 1 is not committed yet, but workspace sees update.   Great.

```
-- session 2

select * from metadata_scan('repro.bugt', '*') tmpt;
-- can see both objects from flush

select * from bugt;
-- cannot see update from session 1, because it is not committed yet.   great.

select mo_ctl('dn', 'inspect', 'merge -t repro.bugt -o bdac4f92-9dd5-11ee-a66a-c2ca9b054d7e_00000,a334ef7a-9dd5-11ee-a66a-c2ca9b054d7e_00000');
-- got these two object ids from metadata scan.   HUNG
```

### Expected Behavior

merge succeeds.   after than, I plan to go back to session 1 and run 
` update bugt set k = k+1 where I = 1 and j = 1`
again, to see if CN pick up the merge.

**Comment by aptend** [comment]
Besides, `select mo_ctl('dn', 'inspect', 'policy -t repro.bugt -m 1 -r 0');` is recommended to stop merging for a table

**Comment by XuPeng-SH** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
main commit: 32a05ab7000d1206a5c70aa036bf4a2d4f39e207
session1:
mysql> use repro;
Database changed
mysql> create table bugt(i int not null, j int not null, k int, primary key (i, j));
Query OK, 0 rows affected (0.03 sec)

mysql> select mo_ctl('dn', 'inspect', 'policy -m 0 -r 0');
+-------------------------------------------------------------------------------------+
| mo_ctl(dn, inspect, policy -m 0 -r 0)                                               |
+-------------------------------------------------------------------------------------+
|
msg: success. arg (*) maxMergeObjN: 0, minRowsQualified: 0, hints: [Auto]

<empty> |
+-------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into bugt values (1, 1, 1), (2, 2, 2);
Query OK, 2 rows affected (0.03 sec)

mysql> select mo_ctl('dn', 'flush', 'repro.bugt');
+---------------------------------------------------------------------------------+
| mo_ctl(dn, flush, repro.bugt)                                                   |
+---------------------------------------------------------------------------------+
| {
  "method": "Flush",
  "result": [
    {
      "returnStr": "OK"
    }
  ]
}
 |
+---------------------------------------------------------------------------------+
1 row in set (0.41 sec)

mysql> insert into bugt values (3, 3, 3), (4, 4, 4);
Query OK, 2 rows affected (0.02 sec)

mysql> select mo_ctl('dn', 'flush', 'repro.bugt');
+---------------------------------------------------------------------------------+
| mo_ctl(dn, flush, repro.bugt)                                                   |
+---------------------------------------------------------------------------------+
| {
  "method": "Flush",
  "result": [
    {
      "returnStr": "OK"
    }
  ]
}
 |
+---------------------------------------------------------------------------------+
1 row in set (0.40 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> update bugt set k = k+1 where i = 1 and j = 1;
Query OK, 1 row affected (0.01 sec)

mysql> select * from bugt;
+------+------+------+
| i    | j    | k    |
+------+------+------+
|    1 |    1 |    2 |
|    2 |    2 |    2 |
|    3 |    3 |    3 |
|    4 |    4 |    4 |
+------+------+------+
4 rows in set (0.00 sec)

session 2:
mysql> select * from metadata_scan('repro.bugt', '*') tmpt;
ERROR 20101 (HY000): internal error: get database failed in metadata scan
mysql> select * from metadata_scan('repro.bugt', '*') tmpt;
+----------+--------------------------------------------+-----------+---------------------------------------------------------------+-----------------------+-----------+----------+----------+---------------+-------------+------------+------------+------------+
| col_name | object_name                                | is_hidden | obj_loc                                                       | create_ts             | delete_ts | rows_cnt | null_cnt | compress_size | origin_size | min        | max        | sum        |
+----------+--------------------------------------------+-----------+---------------------------------------------------------------+-----------------------+-----------+----------+----------+---------------+-------------+------------+------------+------------+
| i        | 018d4470-90e7-7c8c-b1f8-6f5e5d2ef0c8_00000 | false     | 018d4470-90e7-7c8c-b1f8-6f5e5d2ef0c8_00000_1_445_335_1583_0_0 | 1706250244417421000-0 | 0-0       |        2 |        0 |             0 |           0 | NULL       | NULL       | NULL       |
| j        | 018d4470-90e7-7c8c-b1f8-6f5e5d2ef0c8_00000 | false     | 018d4470-90e7-7c8c-b1f8-6f5e5d2ef0c8_00000_1_445_335_1583_0_0 | 1706250244417421000-0 | 0-0       |        2 |        0 |             0 |           0 | NULL       | NULL       | NULL       |
| k        | 018d4470-90e7-7c8c-b1f8-6f5e5d2ef0c8_00000 | false     | 018d4470-90e7-7c8c-b1f8-6f5e5d2ef0c8_00000_1_445_335_1583_0_0 | 1706250244417421000-0 | 0-0       |        2 |        0 |             0 |           0 | NULL       | NULL       | NULL       |
| i        | 018d4470-7730-7fdc-806e-c0889bd848e2_00000 | false     | 018d4470-7730-7fdc-806e-c0889bd848e2_00000_1_448_337_1583_0_0 | 1706250237819608000-0 | 0-0       |        2 |        0 |             0 |           0 | NULL       | NULL       | NULL       |
| j        | 018d4470-7730-7fdc-806e-c0889bd848e2_00000 | false     | 018d4470-7730-7fdc-806e-c0889bd848e2_00000_1_448_337_1583_0_0 | 1706250237819608000-0 | 0-0       |        2 |        0 |             0 |           0 | NULL       | NULL       | NULL       |
| k        | 018d4470-7730-7fdc-806e-c0889bd848e2_00000 | false     | 018d4470-7730-7fdc-806e-c0889bd848e2_00000_1_448_337_1583_0_0 | 1706250237819608000-0 | 0-0       |        2 |        0 |             0 |           0 | NULL       | NULL       | NULL       |
+----------+--------------------------------------------+-----------+---------------------------------------------------------------+-----------------------+-----------+----------+----------+---------------+-------------+------------+------------+------------+
6 rows in set (0.02 sec)

mysql> select * from bugt;
+------+------+------+
| i    | j    | k    |
+------+------+------+
|    1 |    1 |    1 |
|    2 |    2 |    2 |
|    3 |    3 |    3 |
|    4 |    4 |    4 |
+------+------+------+
4 rows in set (0.01 sec)
<img width="1318" alt="企业微信截图_fd826bf1-a58b-470f-b402-f7efecebbb6e" src="https://github.com/matrixorigin/matrixone/assets/113406637/c8edf04c-d52c-4142-aace-7f128e9b2514">

1.1 commit:83b8499b3727ba8fb2814c9b9900145014c7e11f
<img width="1307" alt="企业微信截图_0a3e83b5-2ae7-4789-95aa-ecbc36fe796e" src="https://github.com/matrixorigin/matrixone/assets/113406637/fae4d8de-96f5-4546-9ae1-1448d0dbb617">
