### ISSUE TITLE
[Bug]:  阿里云Dev环境，创建账户以后，更新密码，登录时报错密码错误

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#13587]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):461193df
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

阿里云Dev环境创建实例时，创建用户并更改密码后，登录时报错密码错误。
Cloud环境的关键日志放在如下Issue：
https://github.com/matrixorigin/MO-Cloud/issues/2069

### Expected Behavior

正常登录

### Steps to Reproduce

```Markdown
目前必现
```

**Comment by xiaoshuwei** [comment]
目前Dev环境似乎所有实例都因为这个Bug登录不了了

**Comment by xiaoshuwei** [comment]
http://47.96.110.240/explore?panes=%7B%2240J%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-30m%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aylei** [comment]
@volgariver6 需求是 MO 升级需要保证兼容性，云平台可以通过先升级 MO，再升级 Proxy 来确保升级过程中没有兼容性问题

**Comment by volgariver6** [comment]
pr committed

**Comment by volgariver6** [comment]
fixed。
下次再升级时，还是需要proxy和cn同时升级，期间的业务访问还会报错误。
然后后面的升级，就可以先升级cn，后升级proxy，实现滚动升级。

**Comment by xiaoshuwei** [comment]
processon
