### ISSUE TITLE
[Bug]: [date 12.18] tke regression: the transaction xxx has been committed or aborted

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13583]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4e77834ab3364f329ef7cfa2ae6c5c213b02b826
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7249516116/job/19767126804
<img width="1413" alt="企业微信截图_248220df-bfcc-4d0f-be63-e67fb6e0d1ec" src="https://github.com/matrixorigin/matrixone/assets/113406637/7360106e-0060-4eb1-a9d8-fa374fbedc11">

mo log：
http://132.232.112.34:30088/explore?panes=%7B%22C7J%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20231218%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702951536000%22,%22to%22:%221702951596000%22%7D%7D%7D&schemaVersion=1&orgId=1

cn and dn not oom:
http://132.232.112.34:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20231218&from=1702951236000&to=1702951596000
<img width="1398" alt="企业微信截图_9a884eb1-79c2-43e6-8c28-7b6b8fb7cebc" src="https://github.com/matrixorigin/matrixone/assets/113406637/b3a34fe1-e71d-4982-9c48-a6422a51e534">

**Comment by ouyuanning** [comment]
same as https://github.com/matrixorigin/MO-Cloud/issues/2034

**Comment by ouyuanning** [comment]
暂未复现

**Comment by ouyuanning** [comment]
暂未复现

**Comment by ouyuanning** [comment]
暂未复现

**Comment by ouyuanning** [comment]
暂未复现

**Comment by heni02** [comment]
standalone also apear this problem:
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7386668892/job/20093865231
<img width="1416" alt="企业微信截图_27d9ee6d-1311-47fb-b73f-85f584390b63" src="https://github.com/matrixorigin/matrixone/assets/113406637/3e73ef6b-e5bc-4973-922a-b61add47c0ce">

mo log:
[molog (1).tar.gz](https://github.com/matrixorigin/matrixone/files/13815263/molog.1.tar.gz)

**Comment by ouyuanning** [comment]
有加日志的那个分支暂未复现

**Comment by ouyuanning** [comment]
加日志跑会OOM，今天还没空看如何更改下日志。

**Comment by ouyuanning** [comment]
在辛苦heni继续在加日志的分支跑一下

**Comment by ouyuanning** [comment]
补充了日志，继续跑

**Comment by ouyuanning** [comment]
跑了一下，还是OOM了。还要再看看如何避免OOM下复现

**Comment by ouyuanning** [comment]
加了日志的版本还没跑出来

**Comment by ouyuanning** [comment]
加了日志的版本还没跑出来。下周我本地试一试

**Comment by ouyuanning** [comment]
在这个issue https://github.com/matrixorigin/MO-Cloud/issues/2412
中的数据集，跑了3次standalone 2次多CN的  双龙数据，暂未复现。

**Comment by ouyuanning** [comment]
待素问的数据跑一下看看能否复现

**Comment by ouyuanning** [comment]
今天用素问的数据尚未复现。

**Comment by ouyuanning** [comment]
还没有在本地复现

**Comment by ouyuanning** [comment]
还没有在本地复现

**Comment by ouyuanning** [comment]
还在跑
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8015610000/job/21899345700

**Comment by ouyuanning** [comment]
统一用这个跟进吧，这个先关了吧
https://github.com/matrixorigin/MO-Cloud/issues/2412

**Comment by heni02** [comment]
confirm，closed
