### ISSUE TITLE
[Bug]: `no such table` error during several bvt tests

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13603]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d265a1d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1107" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/06cd9fcc-8865-48b6-9590-347445b684dd">

https://github.com/matrixorigin/matrixone/actions/runs/7257193766/job/19771084728

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7243302002/job/19729910265

**Comment by nnsgmsone** [comment]
经过确认是plan传的信息有问题。。。找远宁对接处理这个plan的问题中

**Comment by nnsgmsone** [comment]
fixed by #13775

**Comment by heni02** [comment]
最近没有再出现先关闭，bvt case概率出现

**Comment by aressu1985** [comment]
tracke by #13853
