### ISSUE TITLE
[Bug]: uuid type parse as identifer return SQL syntax error

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#13619]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![企业微信截图_9ecdfccf-8ecb-4088-b709-178828c3b003](https://github.com/matrixorigin/matrixone/assets/26563383/8754b1ab-e8ce-4006-a42c-a1f71062c5bb)

**Comment by sukki37** [comment]
related to https://github.com/matrixorigin/matrixone/issues/13542
