### ISSUE TITLE
[Bug]: `no available CN server` error is returned with `kill query`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13618]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.0-dev nightly-b104e664
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2023/12/19 12:00:33.968491 +0000 ERROR retry/util.go:51 trace {"error": "Error 20101 (HY000): internal error: no available CN server", "elapsed": "385.598Âµs", "rows": 0, "sql": "kill query 94051925;"}
```

### Expected Behavior

Kill query successfully

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Refer to https://github.com/matrixorigin/MO-Cloud/issues/2074

**Comment by volgariver6** [comment]
这个问题在main分支上已经没有了，commit: 21ab6c726e1667bd957371219e40245777b96e52
不过这里确实可以优化一下：如果在发送kill query的时候，这个语句已经执行完了，就不需要再发送请求了。

**Comment by volgariver6** [comment]
fixed

**Comment by volgariver6** [comment]
这个问题出现的原因是proxy上的connection id和 cn上的 connection id不一致，最新的代码统一了proxy 和cn上的connection id，在执行kill语句时就不会出现找不到cn 的错误了
