### ISSUE TITLE
[Subtask]: update logging mechanism for statement_info 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#13625]
### Parent Issue

#12390

### Detail of Subtask

@fengttt 认为目前的statement_info logging有些复杂。需要调整。

### Describe implementation you've considered

具体细节需要单独聊。

**Comment by xzxiong** [comment]
close pr #14267 and trace in https://github.com/xzxiong/matrixone/pull/new/xzx/refactorstmt

**Comment by daviszhen** [comment]
与xzx待确认

**Comment by xzxiong** [comment]
all done, ref
- https://github.com/matrixorigin/matrixone/pull/15877
- https://github.com/matrixorigin/matrixone/pull/17863
- https://github.com/matrixorigin/matrixone/pull/17863

**Comment by aressu1985** [comment]
TEST DONE
