### ISSUE TITLE
[Subtask]: cooperation with the proxy

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#13637]
### Parent Issue

#12927 

### Detail of Subtask

不同的cn处理不同的分区
proxy
    tpcc warehouse id = 20。proxy能将id = 20的请求发送的指定cn

### Additional information

@fengttt 提的需求和优先级

**Comment by sukki37** [comment]
tracked by https://github.com/matrixorigin/matrixone/issues/16438
