### ISSUE TITLE
[Tech Request]: update the Upgrade logic

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#13633]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

问题如下：
- upgrade
	- 放到boostrap 之后。
	- 要有重试
-
- 元数据表变更重试
	- 系统sys_version
	- 租户account_version
	- 升级前提
		- 当account_version != sys_version时，租户要升级
	- 方案：
		- 异步升级
			- 对每个租户创建升级任务。异步执行。
				- 说法：租户多的话，升级要很久。
		- 同步升级
			- 在异步执行还没开始时，某租户登录了。在登录时强制升级。
		- 升级步骤
			- versionX -> versionX+1
				- 单个事务
			- versionX+1-> versionX+2
				- 单个事务

- cn升级
	- 目前还定义清楚cn升级是怎么样的。后续再做。

### Why is this needed ?

在分析https://github.com/matrixorigin/MO-Cloud/issues/2062的过程中。
发现内核的upgrade功能有缺陷。田博士，对升级给了新要求。单独2062这个bug，无法完全覆盖住。
新建此需求。

**Comment by daviszhen** [comment]
@sukki37 建议给p-1

**Comment by qingxinhome** [comment]
https://github.com/matrixorigin/matrixone/issues/14415

**Comment by qingxinhome** [comment]
PR has been submitted

**Comment by qingxinhome** [comment]
Encoding

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been submitted. Please verify and test it @daviszhen @sukki37 @aressu1985
