### ISSUE TITLE
[Bug]: regexp_instr have invalid input for func REGEXP_INSTR/REGEXP_REPLACE/REGEXP_SUBSTR with column para

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13659]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):45a01657e81903b64c9a7350221a22a210f103a6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select col11 from big_data_test.table_basic_for_load_100M limit 1;
+---------------------------------------------------------+
| col11                                                   |
+---------------------------------------------------------+
| ,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy |
+---------------------------------------------------------+
1 row in set (0.31 sec)

mysql> select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', ',',1)
    -> ;
+-----------------------------------------------------------------------------+
| regexp_instr(,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy, ,, 1) |
+-----------------------------------------------------------------------------+
|                                                                           1 |
+-----------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', 'a',1)
    -> ;
+-----------------------------------------------------------------------------+
| regexp_instr(,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy, a, 1) |
+-----------------------------------------------------------------------------+
|                                                                          31 |
+-----------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select REGEXP_INSTR(col11,'a',2) from big_data_test.table_basic_for_load_100M limit 1;
ERROR 20301 (HY000): invalid input: regexp_instr have invalid input
mysql> select REGEXP_INSTR(col11,'a',1)) from big_data_test.table_basic_for_load_100M limit 1;
ERROR 20301 (HY000): invalid input: regexp_instr have invalid input
mysql> select REGEXP_INSTR(col11,','',1) from big_data_test.table_basic_for_load_100M limit 1;
ERROR 20301 (HY000): **invalid input: regexp_instr have invalid input**

**Comment by YANGGMM** [comment]
```mysql
create database abc;
use abc;
create table big_data_test(col1 varchar);
insert into big_data_test values(' ,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy');
select col1 from big_data_test;
select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', ',',1);
select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', 'a',1);
select REGEXP_INSTR(col11,','',1) from big_data_test.table_basic_for_load_100M limit 1;
```

**Comment by YANGGMM** [comment]
```mysql
create database big_data_test;
use big_data_test;
create table table_basic_for_load_100M(col1 varchar);
insert into table_basic_for_load_100M values(' ,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy');
select col1 from big_data_test;
select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', ',',1);
select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', 'a',1);
select REGEXP_INSTR(col11,',',1) from big_data_test.table_basic_for_load_100M limit 1;
```

**Comment by YANGGMM** [comment]
<img width="905" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/4cb2d549-1c37-415f-967b-6ba76f3d72aa">

**Comment by YANGGMM** [comment]
```mysql
select REGEXP_INSTR(',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy', 'a',1);
select REGEXP_INSTR(col1,',',1) from big_data_test.table_basic_for_load_100M limit 1;
```

**Comment by YANGGMM** [comment]
',GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy'
'\u00a0,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy'

**Comment by YANGGMM** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
