### ISSUE TITLE
[Bug]: Fail to get query result

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#13654]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 1.1-dev 45a01657e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [system_metrics]> SELECT `statement`, system.statement_info.statement_id, IF(`status`='Running', TIMESTAMPDIFF(MICROSECOND,`request_at`,now())*1000, `duration`) AS `duration`, `status`, `request_at`, system.statement_info.response_at, `user`, system.statement_info.account, `database`, `transaction_id`, `session_id`, `rows_read`, `bytes_scan`, `error`, `err_code`, `result_count`, cu FROM `system`.`statement_info` left join mo_catalog.statement_cu ON system.statement_info.statement_id = mo_catalog.statement_cu.statement_id WHERE request_at >= '2023-12-20 09:06:40' AND request_at <= '2023-12-20 09:07:00' AND system.statement_info.statement_id='16d160ab-9f17-11ee-ba27-f2f64da8e7e7' and system.statement_info.account='20cd04d8_3cac_4244_90f2_e53a8c5debb0' ORDER BY system.statement_info.response_at DESC LIMIT 1;
Empty set (0.04 sec)

MySQL [system_metrics]> select statement from `system`.`statement_info` WHERE request_at >= '2023-12-20 09:06:40' AND request_at <= '2023-12-20 09:07:00' AND system.statement_info.statement_id='16d160ab-9f17-11ee-ba27-f2f64da8e7e7';
+-----------------------------------+
| statement                         |
+-----------------------------------+
| /* 1 queries */
SELECT VERSION() |
+-----------------------------------+
1 row in set (0.47 sec)
```

### Expected Behavior

Get query result successfully

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Refer to https://github.com/matrixorigin/MO-Cloud/issues/2081
Cloud dev

**Comment by badboynt1** [comment]
caused by https://github.com/matrixorigin/matrixone/issues/13650

**Comment by badboynt1** [comment]
fixed

mysql>  SELECT `statement`, system.statement_info.statement_id, IF(`status`='Running', TIMESTAMPDIFF(MICROSECOND,`request_at`,now())*1000, `duration`) AS `duration`, `status`, `request_at`, system.statement_info.response_at, `user`, system.statement_info.account, `database`, `transaction_id`, `session_id`, `rows_read`, `bytes_scan`, `error`, `err_code`, `result_count`, cu FROM `system`.`statement_info` left join mo_catalog.statement_cu ON system.statement_info.statement_id = mo_catalog.statement_cu.statement_id WHERE request_at >= '2023-12-20 09:06:40' AND request_at <= '2023-12-20 09:07:00' AND system.statement_info.statement_id='16d160ab-9f17-11ee-ba27-f2f64da8e7e7' and system.statement_info.account='20cd04d8_3cac_4244_90f2_e53a8c5debb0' ORDER BY system.statement_info.response_at DESC LIMIT 1;
+-----------------------------------+--------------------------------------+----------+---------+----------------------------+----------------------------+-------+--------------------------------------+----------+--------------------------------------+--------------------------------------+-----------+------------+-------+----------+--------------+------+
| statement                         | statement_id                         | duration | status  | request_at                 | response_at                | user  | account                              | database | transaction_id                       | session_id                           | rows_read | bytes_scan | error | err_code | result_count | cu   |
+-----------------------------------+--------------------------------------+----------+---------+----------------------------+----------------------------+-------+--------------------------------------+----------+--------------------------------------+--------------------------------------+-----------+------------+-------+----------+--------------+------+
| /* 1 queries */ 
SELECT VERSION() | 16d160ab-9f17-11ee-ba27-f2f64da8e7e7 |   215691 | Success | 2023-12-20 09:06:40.000000 | 2023-12-20 09:06:45.000000 | admin | 20cd04d8_3cac_4244_90f2_e53a8c5debb0 |          | d4bbdd19-6227-4181-aadd-effe9d85ed1b | 16ca7db9-9f17-11ee-ba27-f2f64da8e7e7 |         0 |          0 |       | 0        |            1 | NULL |
+-----------------------------------+--------------------------------------+----------+---------+----------------------------+----------------------------+-------+--------------------------------------+----------+--------------------------------------+--------------------------------------+-----------+------------+-------+----------+--------------+------+
1 row in set (0.05 sec)

**Comment by DanielZhangQD** [comment]
Verified and passed with commit `1f91f1c59`
