### ISSUE TITLE
[Bug]:  txn auto rollback if stmt running error in explicit txn.

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#13678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d50211bca

### Other Environment Information

```Markdown
- Hardware parameters: macbook
- OS type: MAC OS
- Others:
```

### Actual Behavior

在显式事务中，statement 插入失败（例如：Duplicat key），会导致事务自动回滚。
错误信息
```
mysql> insert into test.t_id values(1);  -- 异常: mo 遇到这个语句会回滚事务，这是符合预期的么？
ERROR 1062 (HY000): Duplicate entry '1' for key 'id'
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
```

> autocommit = 1 或 0, 执行的结果是一样的。
> MO 1.0.1 / 1.1 有同样的问题

- autocomit = 1
![image](https://github.com/matrixorigin/matrixone/assets/3927687/77eb6993-3fd5-42e4-8b3e-17dada03ab74)

- autocommit = 0
![image](https://github.com/matrixorigin/matrixone/assets/3927687/68e43152-c6c6-4d7d-a55d-07a8da5b52e1)

### Steps to Reproduce

```Markdown
create database if not exists test;
create table if not exists test.t_id1( id int primary key );
insert into test.t_id1 values(1);  -- 插入 id: 1

set autocommit = 1;
begin; 

insert into test.t_id1 values(2);  -- 插入 id: 2
select * from test.t_id1;	   -- 查询到 id: 1, 2
insert into test.t_id1 values(1);  -- 异常: mo 遇到这个语句会回滚事务，这是符合预期的么？
select * from test.t_id1;	   -- 查询到 id: 1
```

**Comment by daviszhen** [comment]
此行为是为了改bug #4283 而改的。行为是田博士定的 https://github.com/matrixorigin/matrixone/issues/4283#issuecomment-1302962035

**Comment by daviszhen** [comment]
在做#12390的过程中，修改

**Comment by daviszhen** [comment]
在做 https://github.com/matrixorigin/matrixone/issues/12390 的过程中，修改

**Comment by daviszhen** [comment]
修改中

**Comment by daviszhen** [comment]
修改中

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
进行中

**Comment by daviszhen** [comment]
pr merge了。

**Comment by heni02** [comment]
confirm,closed
1.1-dev commit:a48f32fec2a7b45dc3ad6ba7100d98b763368b5b
<img width="862" alt="企业微信截图_4f8f603a-5d54-4085-8e85-81fc9f14c43b" src="https://github.com/matrixorigin/matrixone/assets/113406637/66b82714-6a92-4a0b-8c5d-cc800dc3e2d2">

main commit:7516f8f3502b4ca106a4b4a417d7cf114b2cd29f
<img width="739" alt="企业微信截图_94f71933-94c1-4b7a-87b1-68833ea66654" src="https://github.com/matrixorigin/matrixone/assets/113406637/56e0449e-4cc7-4afd-af33-2ef51c52942a">
