### ISSUE TITLE
[Tech Request]: optimize union statement

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#13679]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

对于select * from lineitem union select * from lineitem union xxx 这样的语句，需要做如下优化：

1、去除重复的scan。 已经在https://github.com/matrixorigin/matrixone/pull/4552 中实现。
2、 修改union节点，在优化器里转化成group节点。 这样可以使用优化器的其他优化规则，例如支持shuffle。  现在的实现方式，union是在compile阶段转换的，导致无法使用优化器规则。
3、 去除冗余的group by。 这里有一条通用的优化器规则，对于scan->group 这样的执行计划，如果groupby列包含scan table的全部主键，则可以直接移除groupby。

优化完成后这条语句可以跑的很快，占用内存很小。

**Comment by dengn** [comment]
This enhancement comes from this issue https://github.com/matrixorigin/MO-Cloud/issues/1963 , needs to be fixed in 1.1

**Comment by aressu1985** [comment]
done
