### ISSUE TITLE
[Bug]: [date 12.20] standalone: sysbench test reported syntax error about group by __mo_index_idx_col

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13672]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

146c67f31c5e2c6b626dfe0a48f534f7319feab1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7276455803/job/19827197954
<img width="1396" alt="企业微信截图_aece9a12-d0c3-4fab-9dc8-2e899e3d3ef9" src="https://github.com/matrixorigin/matrixone/assets/113406637/3af35fb1-8f12-4a20-8e9e-318032a6195d">
<img width="1431" alt="企业微信截图_c06be02c-fc4b-42d3-af93-dc8bb2ace35e" src="https://github.com/matrixorigin/matrixone/assets/113406637/3ce81a4d-96dd-461c-984d-b2b229bcde40">

mo log:
<img width="1538" alt="企业微信截图_82f310d4-25a8-4461-b839-f08322bad14e" src="https://github.com/matrixorigin/matrixone/assets/113406637/795ff5ba-7ec9-4b52-a6a4-4e3e4fb507bc">
[molog.tar.gz](https://github.com/matrixorigin/matrixone/files/13734475/molog.tar.gz)

profile磁盘满定期清理了，可以先看下日志定位，如有需要再复现抓profile

### Steps to Reproduce

```Markdown
sysbench random_points 测试
```

**Comment by jensenojs** [comment]
造成问题的sql是
```sql
insert into  sysbench_db.`__mo_index_secondary_3e3cba51-9f6e-11ee-9267-b07b25f8b524` select serial_full(k,id), id from sysbench_db.sbtest2;

```
拼装出来的后台SQL是
```sql
select __mo_index_idx_col from `sysbench_db`.`__mo_index_secondary_3e3cba51-9f6e-11ee-9267-b07b25f8b524` where __mo_index_idx_col in (':\u0017K\ufffd\ufffd:\u0017\ufffd9\ufffd', ':\u0017L\ufffd\ufffd:\u0017[\ufffdT', ':\u0017?\u001e\ufffd:\u0017u='') group by __mo_index_idx_col having count(*) > 1 limit 1;
```
可以看到 in ()里面那两个字符串，escape有点问题, 但我还没有复现成功

**Comment by jensenojs** [comment]
已merge, 跑一段时间看看先

**Comment by heni02** [comment]
confirm，closed
commit：e4ff476239d0a4a26b3a9dec155d46dec7dfd695
job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7330169526
<img width="763" alt="企业微信截图_72d27cc0-424e-4c89-94b5-134660168c31" src="https://github.com/matrixorigin/matrixone/assets/113406637/e147b464-99b5-4e09-9222-8be580ac2f62">
