### ISSUE TITLE
[Bug]: zero TableId can create repeating (tn must report error)

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#13694]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

52ba4bc12dfb0bc63576ef2d9309a3d8ca578180

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For any tableid, if it's already used, it should return an error, but for 0, it seems to be a special case.0 shouldn't have any special characteristics.

### Steps to Reproduce

```Markdown
1. hack a prefix like tt, then all the tableid for the tt is zero
2. create table tt
3. create table tt1
```

**Comment by nnsgmsone** [comment]
tableid 1 also has the bug.

**Comment by volgariver6** [comment]
fixed
