### ISSUE TITLE
[Bug]: mo crashed during booting

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#1372]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c11a85541fe3738c4149798e8a91b2518785eab3
- Hardware parameters:
- OS type:ubuntu
- Others:
```

### Actual Behavior

the mo crashed during booting

### Expected Behavior

the mo starts successfully.

### Steps to Reproduce

```markdown
`kill -9` to kill the mo process.
Then, boot the mo server
```

### Additional information

[1213.log](https://github.com/matrixorigin/matrixone/files/7708174/1213.log)

**Comment by lni** [comment]
This crash is related to MatrixCube/Raft. However, it was using a relatively old version of cube and tones of related issues have been addressed since that version. 

I'd recommend to use the latest version of cube and see whether the crash can still be reproduced.

**Comment by daviszhen** [comment]
After update the cube to the verion 20211214065946-5d0142bc6056, I do not reproduce it until now. Maybe, it disappears.
