### ISSUE TITLE
[Bug]: non reserved keyword reference

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#13728]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.0-dev, 1.1-dev

### Commit ID

cd6dae9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select reference from t1;
parse error

### Expected Behavior

select reference from t1;
parse successful

### Steps to Reproduce

```Markdown
select reference from t1;
parse error
```

**Comment by aronchanisme** [comment]
```sql
drop database if exists test;
create database test;
use test;
drop table if exists reference;
create table reference (reference int);
insert into reference values (1);
insert into reference (reference) values (2);
select reference from reference;
select * from reference;
drop database test;
```

**Comment by aronchanisme** [comment]
Tests' been validated on below 3 branches. Please kindly help add some bvt cases. Thanks. @heni02 

1. branch=`1.0-dev`, commit_id=`bc09aeac7`, result=`ok`

<img width="774" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/1574b587-dcc7-4ebf-9c0b-e30a23315f09">

2. branch=`1.1-dev`, commit_id=`94a772491`, result=`ok`
<img width="773" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/2789eb52-45c5-4fa2-8f5f-216197975c1a">

3. branch=`main`, commit_id=`25f762958`, result=`ok`
<img width="774" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/b21e71dc-531f-42ac-bb3e-411c825e670f">

**Comment by heni02** [comment]
500+关键字测试用例规划补充到日常regression中，bvt增加部分关键字case
