### ISSUE TITLE
[Bug]:  tpcc stability test report 'Duplicate entry '(1,1,7575)' for key '__mo_cpkey_col''.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13731]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.0-dev

### Commit ID

8081e0516065caf2531835c42f92e00c99f0082a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1253" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6577d291-8baa-457c-8dc9-30b989f4cbb0">

error.log:
[tpcc.log](https://github.com/matrixorigin/matrixone/files/13749063/tpcc.log)

log: http://10.222.6.1/explore?panes=%7B%22uUC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
混合场景并行跑tpcc 测试 600分钟.
```

**Comment by ouyuanning** [comment]
@Ariznawlll mo-service的日志也放一下吧。内网访问不了

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
跟莫尘一起看了一下，看不出啥问题。先想办法加点日志吧

**Comment by ouyuanning** [comment]
节后加日志确认下是检查的问题，还是数据问题

**Comment by ouyuanning** [comment]
今天还没空增加日志

**Comment by ouyuanning** [comment]
下周增加个变量，方便tpcc跑稳定性测试的时候可以抛异常

**Comment by ouyuanning** [comment]
这2天还没空看

**Comment by ouyuanning** [comment]
这2天还没空看

**Comment by ouyuanning** [comment]
不容易复现，先处理其他s0 bug

**Comment by ouyuanning** [comment]
不容易复现，先处理其他s0 bug

**Comment by ouyuanning** [comment]
不容易复现，先处理其他s0 bug

**Comment by ouyuanning** [comment]
不容易复现，先处理其他s0 bug

**Comment by ouyuanning** [comment]
不容易复现，先处理其他s0 bug

**Comment by ouyuanning** [comment]
在处理  Column Group的需求。还没时间处理。

**Comment by ouyuanning** [comment]
在处理 Column Group的需求。还没时间处理。

**Comment by ouyuanning** [comment]
在处理 Column Group的需求。还没时间处理

**Comment by ouyuanning** [comment]
等罗飞的PR合并后，应该会没这个问题了

**Comment by ouyuanning** [comment]
等罗飞的PR合并后，应该会没这个问题了

**Comment by ouyuanning** [comment]
等罗飞的PR合并后，应该会没这个问题了

**Comment by ouyuanning** [comment]
等罗飞的PR合并后，应该会没这个问题了

**Comment by ouyuanning** [comment]
罗飞的PR已合并。可以再测一下看看

**Comment by Ariznawlll** [comment]
持续观察中

**Comment by Ariznawlll** [comment]
fixed
