### ISSUE TITLE
[Bug]: tpch stability test report 'internal error: wait notify message timeout'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13739]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.0-dev

### Commit ID

8081e0516065caf2531835c42f92e00c99f0082a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1006" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cf7635c1-ecc0-451e-a586-25adf61f888c">

tpch工具log：
[tpch.log](https://github.com/matrixorigin/matrixone/files/13751344/tpch.log)

Loki：http://10.222.6.1/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-stability-regression&from=1703172334666&to=1703233744404

### Steps to Reproduce

```Markdown
混合场景并行跑
```

**Comment by m-schen** [comment]
可能被pr #13699 修复，下周再继续跟该问题。

**Comment by m-schen** [comment]
这个修复没有合并到1.0，只合并到了1.1和main ... 可能需要到1.1分支上进行验证。。

**Comment by m-schen** [comment]
1.0, 1.1 和 main 三个分支均已合并pr， 可以进行验证。

**Comment by m-schen** [comment]
经测试人员验证，昨天的稳定性测试还有问题。需要再找找问题。

**Comment by Ariznawlll** [comment]
http://10.222.6.1/explore?panes=%7B%22-xf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by m-schen** [comment]
以下是关于该bug的分析。

经过对日志的检查，发现了以下情况：
该错误的发生并不是单独发生的，一般同时也伴随着之前连续多句，或者之后连续多句出现了
1.   网络发生问题： stream closed.
2.  节点挂掉：cn - tn disconnected.
3.  不知原因的rpc报错：used closed stream.

由此可以判断出此时环境出现了通信上的问题（cn与cn之间无法有效传送数据）。

下面我先具体说一下出现该报错的原因。
当前如果存在以下情况，
`节点 A 上的 dispatch 算子需要将 某些数据 发送给 节点 B 上的 一条 pipeline K.` 【Tag 1】
由于一些历史原因（早期mo网络非流式发送无法保序），并非由A直接创建连接并将数据写给B.
而是采用了，由B向A创建一个stream connection，然后A通过该stream的write方法将数据间接写回给B. 

因此对于A节点来说，它在真正执行这样一个dispatch前，需要等待B节点创建该连接，同时这也是提醒节点A, 接收数据方已经准备好了（也就是报错信息中的notify message)。这一等待步骤发生在dispatch算子的prepare阶段，且超时时间为 45 秒 （😄不要问我为什么是这个时间，我只是a code reader without any emotion)。

等待的结束条件有3个，拿到了所需要的消息 / 超时 / 自身所在的 pipeline 的上下文已结束。
这里我们只详细说明比较特殊的第三点，
1. 由于该pipeline自身仍旧处于prepare阶段，因此它不会结束自己。同时也因为处于prepare阶段，它不会接受来自发送方的任何消息（包括代表结束信号的nil），也就是说即使其他地方感知到了网络错误，也没有办法正常停止这个等待。
2. 由于用户没有主动关闭查询，因此上下文没有被主动结束。
3. 持有父上下文的pipeline的位置在它后面（也就是作为dispatch算子的数据接受者）并没有收到正常结束，或者执行出错的情况，因此父上下文没有结束。

综上所属，在这种情况下（在有这样算子时，发生了网络错误），这个错误是一定会出现的，它本质上也是网络错误的一种表现。

故对于该bug的修复，在摆正【Tag 1】处所描述的数据发送方式以前，我会尝试将该等待步骤换到其他地方，让它跳出这个糟糕的等待，以便马上感知到网络错误。

但不修复关于为什么网络会发生波动或者错误的问题（快去请如来佛祖🙏）。

**Comment by m-schen** [comment]
当网络发生问题时，貌似无法解决这个问题。。

要把数据从a发送到b，a端需要等待b端建立链接，由于网络出了问题，等不到b端的链接，因此无法发送数据。

**Comment by m-schen** [comment]
这个等类似的pr汇总后统一交qa处理，目前的情况是无法处理的。

当网络发生波动后，由于这部分查询需要等待另一个节点的信号，所以要一段时间才能判断为发生异常，从而报错。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上一个评论。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
同上 请假中

**Comment by m-schen** [comment]
同上。

**Comment by m-schen** [comment]
同上。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
与上一个评论相同。

**Comment by m-schen** [comment]
与上一个评论相同。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
没看，在忙agg执行上下文占用内存太多的问题

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
和上上个评论一样

**Comment by m-schen** [comment]
和上一条评论相同。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
和上一个评论相同，计划明天关掉这个issue.

这个报错是符合预期的，在网络环境差的时候会报出这个issue.

**Comment by Ariznawlll** [comment]
研发的说明：
1. 节点a接收一个sql, 该sql的数据在a节点scan, 计算过程中需要用到a, b两个节点，数据的一部分需要发给b节点。

2. b节点准备好可以收数据后，会向a发一个消息说“我准备好了，我的id是xxx, 你把数据发到这里来，我就可以收到了。”

3.b挂了，a等不到这个消息，因此过了一会儿a报了个超时错误。

报错符合预期，关闭
