### ISSUE TITLE
[Bug]: tpcc stability test report 'w-w conflict'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13732]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.0-dev

### Commit ID

8081e0516065caf2531835c42f92e00c99f0082a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1262" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/49152cc4-01c0-477e-896f-664361a7556b">

Error log:
[tpcc.log](https://github.com/matrixorigin/matrixone/files/13749130/tpcc.log)

loki:http://10.222.6.1/explore?panes=%7B%22uUC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
混合场景并行跑tpcc 测试 600分钟.
```

**Comment by XuPeng-SH** [comment]
@LeftHandCold

**Comment by LeftHandCold** [comment]
<img width="875" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/40a12fd6-d127-4ea4-be66-bb56e4115604">
出现了不同事务在不同时间commit两条要delete同一行的操作。

**Comment by LeftHandCold** [comment]
还未复现

**Comment by LeftHandCold** [comment]
还未复现

**Comment by LeftHandCold** [comment]
稳定性测试已经复现，还需要排查

**Comment by LeftHandCold** [comment]
没进展，再做cache的pr

**Comment by LeftHandCold** [comment]
没进展，再做cache的pr

**Comment by LeftHandCold** [comment]
没进展，再做bakcup和gc的pr

**Comment by LeftHandCold** [comment]
没进展，再做bakcup和gc的pr

**Comment by LeftHandCold** [comment]
没进展，再做bakcup

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
在做 snapshot和gc的开发

**Comment by LeftHandCold** [comment]
在做 snapshot和gc的开发

**Comment by LeftHandCold** [comment]
在做 snapshot和gc的开发

**Comment by XuPeng-SH** [comment]
it should be fixed by https://github.com/matrixorigin/matrixone/pull/15073

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15545

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15948

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992 fixed dup/ww bug.
