### ISSUE TITLE
[Bug]: Stability test mo reported panic error: index out of range

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13741]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d50211bca84238c88eae7028a67fe7fb14e859c1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

稳定性测试是一种sysbench10万，tpcc 10仓10，tpch100G混合场景长时间的测试，该错误是在tpcc测试时出现的
ErrorMessage : internal error: panic runtime error: index out of range [288] with length 288:
runtime.goPanicIndexU
        /usr/local/go/src/runtime/panic.go:119
github.com/matrixorigin/matrixone/pkg/container/vector.(*FunctionParameterWithoutNullSpecial1[...]).GetStrValue
        /go/src/github.com/matrixorigin/matrixone/pkg/container/vector/functionTools.go:271
github.com/matrixorigin/matrixone/pkg/sql/plan/function.strToStr
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/func_cast.go:3950
github.com/matrixorigin/matrixone/pkg/sql/plan/function.strTypeToOthers
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/func_cast.go:1505
github.com/matrixorigin/matrixone/pkg/sql/plan/function.NewCast
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/func_cast.go:414
github.com/matrixorigin/matrixone/pkg/sql/plan/function.glob..func990.1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/list_operator.go:1817
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/evalExpression.go:493
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/evalExpression.go:483
github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict/restrict.go:77
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:58
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:158
github.com/matrixorigin/matrixone/pkg/sql/colexec/order.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:230
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:40
github.com/matrixorigin/matrixone/pkg/vm.Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:129
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:86
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:103
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:483
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:211
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:150
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

mo log:
http://10.222.6.1/explore?panes=%7B%2222b%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60panic%20runtime%20error:%20index%20out%20of%20range%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702971475000%22,%22to%22:%221703144275000%22%7D%7D%7D&schemaVersion=1&orgId=1

mem use：
http://10.222.6.1/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1703041729328&to=1703074206027&var-datasource=prometheus&var-cluster=&var-namespace=mo-stability-regression

### Steps to Reproduce

```Markdown
稳定性测试
```

**Comment by daviszhen** [comment]
@ouyuanning  这个时执行出错。麻烦看下

**Comment by aressu1985** [comment]
update on 12.26 :
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-12-25 22:30:36 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: index out of range [64] with length 64:
runtime.goPanicIndexU
        /usr/local/go/src/runtime/panic.go:119
github.com/matrixorigin/matrixone/pkg/container/vector.(*FunctionParameterWithoutNull[...]).GetValue
        /go/src/github.com/matrixorigin/matrixone/pkg/container/vector/functionTools.go:235
github.com/matrixorigin/matrixone/pkg/sql/plan/function.opBinaryFixedFixedToFixed[...]
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/baseTemplate.go:777
github.com/matrixorigin/matrixone/pkg/sql/plan/function.equalFn
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/func_compare.go:97
github.com/matrixorigin/matrixone/pkg/sql/plan/function.glob..func732.1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/list_operator.go:71
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/evalExpression.go:497
github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict/restrict.go:77
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:58
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:157
github.com/matrixorigin/matrixone/pkg/sql/colexec/order.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/order/order.go:230
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:40
github.com/matrixorigin/matrixone/pkg/vm.Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:129
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:86
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:88
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:467
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:196
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:135
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

**Comment by ouyuanning** [comment]
试了一下，还是无法访问内网的日志。辛苦明松帮忙看一下吧。

**Comment by m-schen** [comment]
我认为和 #13806 是一样的问题，有的地方把错误信息吞掉了导致生成了错误的数据（真实数据的行数和记录的行数不匹配的数据）。这时候系统发生了mpool oom的问题，应该是正常报错oom的。

不过具体是不是同一个地方吞掉的错误导致的，还需要看看。

**Comment by m-schen** [comment]
没有考虑mpool报错的地方太多了，包括了vector对外提供的接口本身（如
<img width="791" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/849d58b7-79c3-44e8-b687-0aaae0ff12e0">
)，需要动到的文件特别多。

考虑是否直接在mpool报错“oom”的地方直接执行
`panic "oom"`
该panic会被代码里的recover捕获，从而能够达到正常报错的目的。。

**Comment by m-schen** [comment]
没有新的进展

**Comment by aressu1985** [comment]
update on 01.04:
2024-01-04 01:00:21 FATAL jTPCCTerminal:235 - [UNEXPECTED][STOCK_LEVEL][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: index out of range [43] with length 43:
runtime.goPanicIndexU
        /usr/local/go/src/runtime/panic.go:119
github.com/matrixorigin/matrixone/pkg/container/vector.(*FunctionParameterWithoutNull[...]).GetValue
        /go/src/github.com/matrixorigin/matrixone/pkg/container/vector/functionTools.go:235
github.com/matrixorigin/matrixone/pkg/sql/plan/function.opBinaryFixedFixedToFixed[...]
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/baseTemplate.go:777
github.com/matrixorigin/matrixone/pkg/sql/plan/function.equalFn
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/func_compare.go:97
github.com/matrixorigin/matrixone/pkg/sql/plan/function.glob..func736.1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/list_operator.go:71
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/evalExpression.go:493
github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict/restrict.go:77
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:58
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:40
github.com/matrixorigin/matrixone/pkg/vm.Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:129
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:86
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:87
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:471
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:199
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:134
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

**Comment by fengttt** [comment]
> 没有新的进展

Yes, panic.

**Comment by m-schen** [comment]
这个等main上的pr合并，不知道为啥老合不进去，ci有点不稳定

**Comment by m-schen** [comment]
已在main和1.1分支合并了修复的pr，麻烦可以验证一下。

目前如果出现了mpool out of memory的错误属于已知问题，但是不应该出现各种堆栈类的报错。

**Comment by aressu1985** [comment]
fixed
