### ISSUE TITLE
[Bug]: SaveShardMetadata is failed

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#1374]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):15247b555fd738a15033960a9df75b30a57f44df
- Hardware parameters:
- OS type:mac pro
- Others: mo main branch
```

### Actual Behavior

unit test crashed.

### Expected Behavior

unit test works

### Steps to Reproduce

```markdown
checkout mo main branch;
cd matrixone/pkg/frontend;
go test -run TestEpochGC;
```

### Additional information

[1214-main.log](https://github.com/matrixorigin/matrixone/files/7708379/1214-main.log)

**Comment by daviszhen** [comment]
Maybe, it is related to the #1349

**Comment by XuPeng-SH** [comment]
It is a bug in AOE when handling concurrent **FLUSH**. Thanks to **Mac's** bad file system for exposing this problem ASAP.

**Comment by XuPeng-SH** [comment]
Duplicate issue with #1349
