### ISSUE TITLE
[Bug]: Stability test mo reported error: out of memory

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13740]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d50211bca84238c88eae7028a67fe7fb14e859c1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

稳定性测试是一种sysbench10万，tpcc 10仓10，tpch100G混合场景长时间的测试，该错误是在tpcc测试时出现的错误
mo log:
<img width="1330" alt="企业微信截图_6d3df62a-f2c8-49b5-ab53-795e0fe7b28c" src="https://github.com/matrixorigin/matrixone/assets/113406637/e45b7d2c-c2e6-4fa2-a29a-e2e62124ba46">

http://10.222.6.1/explore?panes=%7B%2222b%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60out%20of%20memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221702971475000%22,%22to%22:%221703144275000%22%7D%7D%7D&schemaVersion=1&orgId=1

mem使用情况：当时时间段没有cn oom
http://10.222.6.1/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1703041729328&to=1703074206027&var-datasource=prometheus&var-cluster=&var-namespace=mo-stability-regression

### Steps to Reproduce

```Markdown
稳定性测试流程
```

**Comment by ouyuanning** [comment]
可能的原因
1、mpool统计问题.  https://github.com/matrixorigin/matrixone/issues/11928
2、确实申请较多了. https://github.com/matrixorigin/matrixone/issues/13524

**Comment by m-schen** [comment]
要在本地跑跑tpcc看看什么语句和在哪里泄漏。

**Comment by m-schen** [comment]
今日没有进展，在分析其他issue

**Comment by m-schen** [comment]
今日无进展。

**Comment by m-schen** [comment]
没有进行相关工作。

**Comment by m-schen** [comment]
没有进行相关工作。

**Comment by m-schen** [comment]
没有进行相关工作。

**Comment by m-schen** [comment]
没有进行相关工作

**Comment by m-schen** [comment]
没有进行相关工作

**Comment by m-schen** [comment]
休假中

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
无进展。

**Comment by m-schen** [comment]
mpool统计泄漏的最近无相关工作。

**Comment by m-schen** [comment]
mpool统计泄漏的最近无相关工作。

**Comment by m-schen** [comment]
mpool统计泄漏的最近无相关工作。

**Comment by m-schen** [comment]
mpool统计泄漏的最近无相关工作。

**Comment by m-schen** [comment]
mpool统计泄漏的最近无相关工作。

**Comment by m-schen** [comment]
同上 请假中

**Comment by m-schen** [comment]
同上一条评论，目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上一条评论，目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
暂无进展。

**Comment by m-schen** [comment]
与上一个评论相同。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
没看，在忙agg执行上下文占用内存太多的问题

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
这个最近应该没空处理，先处理allocate> 1124... 的问题

**Comment by m-schen** [comment]
在做mpool allocate size > 1234567890的错误，这个issue未开展。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
在改connection reset的s-1中

**Comment by m-schen** [comment]
无投入

**Comment by m-schen** [comment]
今天没跟踪这个问题。

**Comment by m-schen** [comment]
没投入

**Comment by m-schen** [comment]
近期难以投入

**Comment by m-schen** [comment]
近期没有投入这个

**Comment by m-schen** [comment]
同上一个回复

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
