### ISSUE TITLE
[Bug]: Stability test tpcc reported error: ResultSet is from UPDATE. No Data

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13744]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d50211bca84238c88eae7028a67fe7fb14e859c1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

稳定性测试是一种sysbench10万，tpcc 10仓10终端，tpch100G混合场景长时间的测试，该错误是在tpcc测试时出现的
<img width="1879" alt="企业微信截图_ec801b2e-7379-4afd-ab52-d4d971477b50" src="https://github.com/matrixorigin/matrixone/assets/113406637/aa403a18-8e27-4a6b-91a4-919dfaf67df4">

mo log：
http://10.222.6.1/explore?panes=%7B%2222b%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703063890000%22,%22to%22:%221703063890000%22%7D%7D%7D&schemaVersion=1&orgId=1

mem use：
http://10.222.6.1/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1703041729328&to=1703074206027&var-datasource=prometheus&var-cluster=&var-namespace=mo-stability-regression

### Steps to Reproduce

```Markdown
稳定性测试
```

**Comment by reusee** [comment]
看上去是 out of memory 导致的，应该先修复内存问题

**Comment by daviszhen** [comment]
问题出现的时间点 utc 2023/12/20 09:18:10。

mpool 有oom。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/fa8d9355-f5ed-4308-b80d-d855fb1b5d5c)
同时在这个区间内 pod 有oom重启。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/a52162e7-057a-4523-82a1-3e02eead8674)

http://10.222.6.1/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&from=1703059729000&to=1703074206000&var-namespace=mo-stability-regression&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki

**Comment by daviszhen** [comment]
同时还有些 pipeline panic问题，不确定是mpool引起的。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/09424733-042f-45c6-89d4-bc1cb67cd167)

**Comment by daviszhen** [comment]
http://10.222.6.1/explore?panes=%7B%2222b%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression%5C%22%7D%20%7C%3D%20%60out%20of%20memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703063890000%22,%22to%22:%221703064010000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ouyuanning** [comment]
OOM问题，辛苦莫尘统一处理一下
@heni02 看是否合并成一个issue

**Comment by heni02** [comment]
tpcc工具日志：
[benchmarkinfo.tar.gz](https://github.com/matrixorigin/matrixone/files/13776457/benchmarkinfo.tar.gz)

**Comment by nnsgmsone** [comment]
正在和存储的同事协商https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待#12532

**Comment by nnsgmsone** [comment]
内存问题等待#12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
处理数据正确性问题中

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by aressu1985** [comment]
未在出现过，先关闭
