### ISSUE TITLE
[Bug]: Using mo-sysbench tool to insert data report 'error 20101: internal error: no available CN server.'

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13743]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

8.0.30-MatrixOne-v1.0.2

### Commit ID

8.0.30-MatrixOne-v1.0.2

### Other Environment Information

```Markdown
- Hardware parameters: 
实例id：d6e01a68-63bc-4b69-ad5f-c78f565e46ec （qa环境）
- OS type:
- Others:
```

### Actual Behavior

版本：
<img width="192" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9e854853-6c06-47f8-984a-c84389c458bd">

mysql客户端连接方式：mysql -h freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech -P 6001 -u d6e01a68_63bc_4b69_ad5f_c78f565e46ec:admin:accountadmin  -p

使用mo-sysbench工具向数据库sysbench_db建表插入数据报错（不稳定出现）：
<img width="1646" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/128ed35a-7435-4670-a3a9-4c49d46e35ac">

### Steps to Reproduce

```Markdown
129上：
cd /root/weilu/mo-sysbench

sysbench  --mysql-host=freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech --mysql-port=6001 --mysql-user=d6e01a68_63bc_4b69_ad5f_c78f565e46ec:admin:accountadmin --mysql-password=Adm in123 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off cleanup
        
sysbench  --mysql-host=freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech --mysql-port=6001 --mysql-user=d6e01a68_63bc_4b69_ad5f_c78f565e46ec:admin:accountadmin --mysql-password=Adm in123 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off prepare
```

**Comment by aressu1985** [comment]
PR 已经进了1.1,1.1稳定性在观察几天

**Comment by volgariver6** [comment]
pr merged.

**Comment by Ariznawlll** [comment]
![Uploading image.png…]()
