### ISSUE TITLE
[Bug]: Stability test report ' internal error: panic interface conversion: interface is nil, not lockservice.lockTable'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13765]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

64801dc75d4e803cd28408aab42e23ccfb7321a0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023-12-24 00:03:48 ERROR TransExecutor:129 -
ErrorTime : 2023-12-24 00:03:48
RequestTime : 2023-12-24 00:03:43.683
TxnName : insert_delete
Statement : insert into sbtest3 values(4976719,4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');
ErrorCode : 20101
ErrorMessage : internal error: panic interface conversion: interface is nil, not lockservice.lockTable:
runtime.assertE2I
        /usr/local/go/src/runtime/iface.go:451
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).handleBindChanged
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:347
github.com/matrixorigin/matrixone/pkg/lockservice.(*remoteLockTable).maybeHandleBindChanged
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_remote.go:281
github.com/matrixorigin/matrixone/pkg/lockservice.(*remoteLockTable).lock
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_remote.go:102
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:143
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:430
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:211
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:120
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:92
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.(*Argument).insert_table
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/insert/insert.go:181
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/insert/insert.go:68
github.com/matrixorigin/matrixone/pkg/vm.Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:129
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:130
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:86
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:300
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:533
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit

log: http://10.222.6.1/explore?panes=%7B%22Czq%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20231224%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
混合场景并行跑稳定性测试.
```

**Comment by zhangxu19830126** [comment]
fixed by #13798 #13799

**Comment by Ariznawlll** [comment]
fixed！
