### ISSUE TITLE
[Bug]: An error occurs when tpcc is executed during cn scaling up or scaling down

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#13778]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

8081e0516

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
d
```

### Actual Behavior

cloud qa 环境  instance id: 41780631-d9b3-48d2-9bb2-e59949e4f354 (方便查找log信息)
1. 在扩缩容场景下执行tpcc 10 仓 10 并发 业务, 出现大量statement_id not exist错误情况
<img width="1664" alt="截屏2023-12-25 15 16 32" src="https://github.com/matrixorigin/matrixone/assets/39303074/9310f247-45cb-4259-8ef7-ddafda4d68c2">

error log: 
[benchmarksql-error-10-10.log](https://github.com/matrixorigin/matrixone/files/13764868/benchmarksql-error-10-10.log)

### Steps to Reproduce

```Markdown
同上
```

**Comment by ouyuanning** [comment]
看着像是 session 的 prepareStmts 没有别复制过去造成的

**Comment by volgariver6** [comment]
<img width="1243" alt="WeChatWorkScreenshot_2d66b477-2a05-442d-bcab-767ef8101f7b" src="https://github.com/matrixorigin/matrixone/assets/18366608/90b3149f-0075-4b0b-924b-c0d7bd54ffeb">

应该是缩容导致的 prepare 语句丢失。

http://47.98.35.103/d/cluster-detail-cloud/cluster-detail-cloud?orgId=1&from=1703488200000&to=1703488859000

**Comment by volgariver6** [comment]
I will handle it.

**Comment by volgariver6** [comment]
在本地试了，构建迁移的场景，在迁移之后是可以正常执行execute语句的：
conn id为203的session，迁移之前执行：
<img width="440" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/7f8ca6b9-9a55-4981-9d74-8b2dffb7b1ce">
发生了迁移：
<img width="1102" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/91d712a0-3dff-4951-b5f9-6a8228316c8d">
迁移之后再执行：
<img width="456" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/1a2e0166-76f3-443d-8838-b30ab98a4614">

**Comment by volgariver6** [comment]
fixed

**Comment by tianyahui-python** [comment]
bug not solved

**Comment by volgariver6** [comment]
pr commited, not merged yet

**Comment by volgariver6** [comment]
merged

**Comment by tianyahui-python** [comment]
测试不通过

**Comment by tianyahui-python** [comment]
https://github.com/matrixone-cloud/mocloud-tester/actions/runs/7441261317

**Comment by volgariver6** [comment]
http://47.96.110.240/explore?panes=%7B%22JCp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01%5C%22,%20matrixorigin_io_component%3D%5C%22ProxySet%5C%22%7D%20%21%3D%20%60new%20connection%20comes%60%20%7C%3D%20%60transfer%20to%20a%20new%20CN%20server%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704668700000%22,%22to%22:%221704669059000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
> 测试不通过

应该是dev 环境的proxy没有升级导致的，最近两天的新版本proxy测试都通过了

**Comment by volgariver6** [comment]
这个问题的原因是proxy在迁移session时没有处理prepare语句，目前的修复是在prepare语句被close之前不允许迁移session。后续的版本中会完善proxy的迁移功能，将prepare语句迁移到其他的cn上面。
