### ISSUE TITLE
[Bug]: The local file data written by diskcache is incorrect.

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#13773]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.1

### Commit ID

8081e0516065caf2531835c42f92e00c99f0082a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1422" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/1c2bd2a2-d60a-45fa-a92b-953c9d4b2bd0">
<img width="1154" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/b92d44f2-a1f6-42e9-a23e-7b3fcc14d457">

### Steps to Reproduce

```Markdown
有4个租户，分别对一个cn跑 tpcc 10-10 syebnch mixed 10w-20 tpch 10G
把s3的文件下载下来分析后，没有问题，但是把diskcache的文件copy下来分析，发现内容可能是其他文件的内容。
```

**Comment by aressu1985** [comment]
这个目前黑盒测试无法优先覆盖，问题单暂关闭，后续试试choas测试如果有新问题，在issue跟踪
