### ISSUE TITLE
[Bug]: Prepare Execution Failed in Update due to `file xxxx is not found`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13788]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

8081e0516065caf2531835c42f92e00c99f0082a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="881" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/9964e050-f8b8-4890-a21d-e723ff1c7e8e">

http://121.43.41.174/explore?panes=%7B%22ahJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%2279307612-ae09-4fc0-81c3-e3f8b13a9927%5C%22%7D%20%7C%3D%20%60query%20trace%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703500260000%22,%22to%22:%221703505119000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
see https://github.com/matrixorigin/MO-Cloud/issues/2132
```

**Comment by XuPeng-SH** [comment]
duplicate with #13216

**Comment by XuPeng-SH** [comment]
没有复现，继续跟踪

**Comment by XuPeng-SH** [comment]
assigned to @triump2020

**Comment by triump2020** [comment]
try to repro

**Comment by triump2020** [comment]
no repro

**Comment by triump2020** [comment]
本地tpcc 跑不出来，明天试试eks 环境, 一直跑.

**Comment by triump2020** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/63033222/84d9d85a-ff20-4eb4-b12d-50d912f76255)


![1704380885906](https://github.com/matrixorigin/matrixone/assets/63033222/96a245c8-1b0d-466d-9ad3-aaaa6102aa00)

**Comment by triump2020** [comment]
> ![image](https://private-user-images.githubusercontent.com/63033222/294218356-84d9d85a-ff20-4eb4-b12d-50d912f76255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODE1NzYsIm5iZiI6MTcwNDM4MTI3NiwicGF0aCI6Ii82MzAzMzIyMi8yOTQyMTgzNTYtODRkOWQ4NWEtZmYyMC00ZWI0LWIxMmQtNTBkOTEyZjc2MjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTJhMTUyYTcyMzRmZmU3MWU1MDFlZjhkYmIxZjI0ZDEwNTdhMjEzMTM2OTc0NmY0NmQ4Y2VkNmZlNzJiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p5XdyzNNZb1yRP5rX-FbnaXPfJmE6v0hR8OTpQW-4r8)
> 
> ![1704380885906](https://private-user-images.githubusercontent.com/63033222/294218246-96a245c8-1b0d-466d-9ad3-aaaa6102aa00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODE1NzYsIm5iZiI6MTcwNDM4MTI3NiwicGF0aCI6Ii82MzAzMzIyMi8yOTQyMTgyNDYtOTZhMjQ1YzgtMWIwZC00NjZkLTlhZDMtYWFhYTYxMDJhYTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZWJkZDc0NjI4OWMzMjRjYzMwYTUxODMxNGRhYWFkMzEwOTMyZjU4MWUxZWZlOTg0MGJiNjBhMGM2ODQ5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJmVojpP9IG-Aq5dhULLcbJyJ4i4DLjcPaqHI3qOLbk)
> 
> 这里有两个疑问：1. 用户的事务 start ts >后台事务的 prepare ts , 为啥用户还是看到了 被后台事务删除的obj 2. 用户事务在很早之前就启动了，为啥过了很久才开始去读取obj? 这个时候obj 已经被gc 了.

用户事务的start ts >>后台事务的prepare ts(即事务的commit ts), 相差了5 个小时左右,  猜测5 个小时后后事务才启动？因为没有事务启动的日志信息， 如果假设成立，那就是问题1 导致的.

**Comment by triump2020** [comment]
@aressu1985  fixed !

**Comment by aressu1985** [comment]
fixed
