### ISSUE TITLE
[Bug]: 增加联合主键报错[HY000][20101] internal error: Invalid alloc size 1147486208

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#13781]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

15239e1641770e7c84871c63c181ee331205f3c5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

执行：
```
alter table mo_sample_data_tpch_sf10.partsupp add PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);
```
报错
```
[HY000][20101] internal error: Invalid alloc size 1147486208
```

### Expected Behavior

正常执行，加上联合主键

### Steps to Reproduce

```Markdown
如Actual Behavior
```

**Comment by xiaoshuwei** [comment]
阿里云Dev环境，mo_sample_data_tpch_sf10.partsupp就是对应的SF10的表

**Comment by jensenojs** [comment]
这个commit下还没有合并修复, 要不麻烦树伟哥再试试? @xiaoshuwei 

<img width="1465" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/1e4ce09a-5a6c-4f83-9f05-7faffb7cbe58">

**Comment by xiaoshuwei** [comment]
> 这个commit下还没有合并修复, 要不麻烦树伟哥再试试? @xiaoshuwei
> 
> <img alt="image" width="1465" src="https://private-user-images.githubusercontent.com/56761542/292746475-1e4ce09a-5a6c-4f83-9f05-7faffb7cbe58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDM3MzYsIm5iZiI6MTcwMzUwMzQzNiwicGF0aCI6Ii81Njc2MTU0Mi8yOTI3NDY0NzUtMWU0Y2UwOWEtNWE2Yy00ZjgzLTlmMDUtN2ZhZmZiN2NiZTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDExMjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNWNjMDE5YWQ4ZjFmMzNkM2RmMzAxYzE3MDY5NTg3MjNlNmM3YTQzOTMxMmIxZWVlZTk4NWRmOGY5YjQzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4o6GWtoB5IaK5-FGG7u8SuvtLj0WN7bgmTn5QI_6No">

最近代码修复了这个问题吗

**Comment by jensenojs** [comment]
> > 这个commit下还没有合并修复, 要不麻烦树伟哥再试试? @xiaoshuwei
> > <img alt="image" width="1465" src="https://private-user-images.githubusercontent.com/56761542/292746475-1e4ce09a-5a6c-4f83-9f05-7faffb7cbe58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDM3MzYsIm5iZiI6MTcwMzUwMzQzNiwicGF0aCI6Ii81Njc2MTU0Mi8yOTI3NDY0NzUtMWU0Y2UwOWEtNWE2Yy00ZjgzLTlmMDUtN2ZhZmZiN2NiZTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDExMjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNWNjMDE5YWQ4ZjFmMzNkM2RmMzAxYzE3MDY5NTg3MjNlNmM3YTQzOTMxMmIxZWVlZTk4NWRmOGY5YjQzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4o6GWtoB5IaK5-FGG7u8SuvtLj0WN7bgmTn5QI_6No">
> 
> 最近代码修复了这个问题吗

嗯, 应该要比之前好才对的, 几千万到亿的规模测过没有出问题, 之前的main是不行的. @xiaoshuwei

**Comment by ouyuanning** [comment]
刚测了一下，tpch 10g, 在 https://github.com/matrixorigin/matrixone/commit/15239e1641770e7c84871c63c181ee331205f3c5  这个commit是有报错，在最新的1.1-dev是好的，锦赛的PR应该已经解决这个问题了

**Comment by aressu1985** [comment]
fixed
mysql> alter table big_data_test.table_basic_for_alter_100M add PRIMARY KEY (col3,col4);
Query OK, 0 rows affected (3 min 6.50 sec)

mysql> 

commit：93ef9c70f3c9f02a7b6563078b775442e341418f

**Comment by xiaoshuwei** [comment]
<img width="562" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/627dd76a-fade-4a60-a02b-4aa807c4a872">
reopen了，目前Alter之后，似乎数据减少了，需要内核同学继续排查一下问题。cc @badboynt1

**Comment by aressu1985** [comment]
确实有问题，@xiaoshuwei，我把这个问题先关了，然后提一个新的
