### ISSUE TITLE
[Bug]: Plan Cache Eviction Strategy Leading to Data Errors

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13790]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1,1.0

### Commit ID

all

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When a sql plan is cached, if the schema for some tables is modified then the plan needs to be evicted from the cache, otherwise it can lead to a lot of strange problems, such as confusing tableids that can lead to unavailability of the self-incrementing service

### Steps to Reproduce

see #13603, #13756

**Comment by nnsgmsone** [comment]
fixed
