### ISSUE TITLE
[Bug]: stability test mo panic runtime error: slice bounds out of range [:8192] with capacity 1

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13806]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

4827ad4912887ab4ad9d14572e801d411cb0491e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2023/12/25 14:30:37.248275 +0000","caller":"vm/vm.go:116","msg":"panic in vm.Run: internal error: panic runtime error: slice bounds out of range [:8192] with capacity 1: \nruntime.goPanicSliceAcap\n\t/usr/local/go/src/runtime/panic.go:139\ngithub.com/matrixorigin/matrixone/pkg/container/vector.ToFixedCol[...]\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/tools.go:37\ngithub.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/tools.go:42\ngithub.com/matrixorigin/matrixone/pkg/container/vector.SetFixedAt[...]\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:355\ngithub.com/matrixorigin/matrixone/pkg/container/vector.SetBytesAt\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:373\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.getOneRowData\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:1141\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.getBatchData\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:498\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.scanCsvFile\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:592\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.scanFileData\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:751\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.(*Argument).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/external/external.go:157\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.(*Argument).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch/dispatch.go:112\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:129\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:130\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:86\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:131\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"} 
mo log：
<img width="1478" alt="企业微信截图_14adcc7b-c0f7-4089-865b-a9cbc91f51c3" src="https://github.com/matrixorigin/matrixone/assets/113406637/03b5903b-39ac-4fbc-afc8-412f9bab6090">
http://10.222.6.1/explore?panes=%7B%224Q9%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20231225%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703472956438%22,%22to%22:%221703559356438%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
stability test
```

**Comment by m-schen** [comment]
<img width="1039" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/22c94058-102a-43ef-850a-8e5b08045cc7">
我估计是这里的pre extend失败了，但这块代码没有处理这个问题。
此时系统应该发生了mpool oom的错误。

**Comment by m-schen** [comment]
在1.1分支和main分支上提交了修复代码，避免主动抛出的oom错误被忽略，从而导致生成了非法的数据（如实际行数为1，但显示长度为8192），可以验证一下是否还有该报错信息。

但是本pr并没有完全解决mpool oom的问题。

**Comment by heni02** [comment]
目前没有这个报错了，先关闭
