### ISSUE TITLE
[Bug]: 1.1-dev分支通过导入Python文件形式创建UDF时卡住

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixone#13813]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

2c5b04a

### Actual Behavior

在本地编写Python文件/opt/add_func.py，内容如下：
```
def add(a, b):
  return a + b
```

执行如下创建函数语句：

```
create or replace function py_add(a int, b int) returns int language python import 
'/opt/add_func.py' 
handler 'add';
```
执行后会一直卡住，表现如图：
![image](https://github.com/matrixorigin/matrixone/assets/90299197/b5c96ee8-efe1-428b-9c7b-b806d3d94684)

### Steps to Reproduce

```Markdown
使用https://github.com/joker-star-l/matrixone的代码打包可以正常执行。
对接开发者老师，反馈上传文件部分调用的是fileservice的代码，推测是后面fileservice侧有一些语义上的改动。
```

**Comment by aylei** [comment]
@heni02 please help verify this issue

**Comment by heni02** [comment]
confirm，closed
commit：a553f08d2
<img width="804" alt="企业微信截图_9749b4ce-fea5-4d54-b11a-907136338eaa" src="https://github.com/matrixorigin/matrixone/assets/113406637/b3d371f1-9868-4333-a46b-3534eafdf9c6">

**Comment by aressu1985** [comment]
解决关闭
