### ISSUE TITLE
[Feature Request]: encode/decode function

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#13825]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
We need to implement encode() and decode() functions for inserting hex encoding of the vector from numpy.
```

### Describe the feature you'd like

encode(data, format) and decode(data, format)

where data should be blob/float/vector/varchar, format can be 'hex' or 'base64'.

mysql> create table t2(a int, b vecf32(3));

mysql>  insert into t2 values(2, decode("7e98b23e9e10383b2f41133f", "hex"));
     
mysql> select * from t2;
+------+---------------------------------------+
| a    | b                                     |
+------+---------------------------------------+
|    1 | [0.34881967, 0.0028086076, 0.5752134] |
+------+---------------------------------------+

mysql> select encode(b, "hex") from t2;
+--------------------------+
| encode(b, hex)           |
+--------------------------+
| 7e98b23e9e10383b2f41133f |
+--------------------------+

### Describe implementation you've considered

PR at https://github.com/matrixorigin/matrixone/pull/11481.

**Comment by Ariznawlll** [comment]
测试类型：blob、float、varchar

与pgsql行为不同的地方：
1. pg中\x被转义为十六进制标识符，mo不会；
<img width="979" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5dbfd88c-fe6a-4535-8251-0f59cbab44e9">

**Comment by arjunsk** [comment]
Right now MO does not handle `\` (escape character) in strings. Hence this difference between MO and PG.

The MO Parser automatically skips the `\`. So the encode() function implementation sees `xa7`.

```sql
mysql> select encode("\xab","hex");
+------------------+
| encode(xab, hex) |
+------------------+
| 786162           |
+------------------+
1 row in set (0.00 sec)

mysql> select encode("xab","hex");
+------------------+
| encode(xab, hex) |
+------------------+
| 786162           |
+------------------+
1 row in set (0.00 sec)
```

This is applicable to other string functions as well
```sql
mysql> select substring("\abc",2);
+-------------------+
| substring(abc, 2) |
+-------------------+
| bc                |
+-------------------+
1 row in set (0.01 sec)
```

CC: @iamlinjunhong , @fengttt

**Comment by florashi181** [comment]
Haven't fully implemented, will be tracked with a new issue.
