### ISSUE TITLE
[Bug]: dup error when running sysbench update index cases

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13872]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cd0f40cb9c3b080ddd4dc74a171a9a449b138cc2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
<img width="1333" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/5ac7958e-55d2-48ed-ae2a-905793665bbd">

<img width="1333" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/15739aee-c2ac-4646-b1a4-e3eba162d006">

mo log:
http://132.232.112.34:30088/explore?panes=%7B%22O9F%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-cd0f40c%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%20%2750062%27%20for%20key%20%27id%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703651153175%22,%22to%22:%221703685022193%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
it is occasionally
```

**Comment by ouyuanning** [comment]
好像以前有碰到过类似的问题，不知道是否main和1.1没同步

**Comment by ouyuanning** [comment]
@qingxinhome 
喜亮先帮忙看看，是不是plan有点问题。这种没有更新primary key的sql，应该不会做去重检查才对。
如果plan没问题，那感觉就是dn检查出来的重复？

**Comment by qingxinhome** [comment]
Problem localization

**Comment by qingxinhome** [comment]
Dealing with other issues

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Unable to reproduce locally

**Comment by qingxinhome** [comment]
Not reproduced locally

**Comment by qingxinhome** [comment]
Not reproduced locally

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
等罗飞那边的处理

**Comment by qingxinhome** [comment]
等罗飞那边的处理

**Comment by qingxinhome** [comment]
等罗飞那边的处理

**Comment by qingxinhome** [comment]
The issue has been resolved by @triump2020   , please verify and test it @aressu1985 @ouyuanning @daviszhen

**Comment by aressu1985** [comment]
fixed
