### ISSUE TITLE
[Bug]: python UDF reported panic error when python server process not exits

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13882]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a553f08d2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select py_add(1,2);
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:260
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/udf/pythonservice.(*Client).Run
	/Users/heni/test-envir/matrixone/pkg/udf/pythonservice/client.go:86
github.com/matrixorigin/matrixone/pkg/udf.(*service).Run
	/Users/heni/test-envir/matrixone/pkg/udf/service.go:49
<img width="1259" alt="企业微信截图_d7100c33-645d-42be-9e83-af704f23c075" src="https://github.com/matrixorigin/matrixone/assets/113406637/ba652840-7f99-437e-90f3-f81f40b058e4">

<img width="1222" alt="企业微信截图_b792a8a6-daa8-4b43-aa35-c7bc4d37b0af" src="https://github.com/matrixorigin/matrixone/assets/113406637/195b6ab4-4d29-442c-bd61-fe21e9caa734">

mo log:
[nohup.log](https://github.com/matrixorigin/matrixone/files/13783014/nohup.log)

### Steps to Reproduce

```Markdown
mo start:./mo-service -launch etc/launch-with-python-udf-server/launch.toml
create or replace function py_add(a int, b int) returns int language python as 
$$
def add(a, b):
  return a + b
$$
handler 'add';
select py_add(1,2);
```

**Comment by heni02** [comment]
加了日志的分支复现日志：
[mo.log](https://github.com/matrixorigin/matrixone/files/13783916/mo.log)

**Comment by aylei** [comment]
Usually caused by mis-configuration in local env

**Comment by aylei** [comment]
修复中

**Comment by aylei** [comment]
处理优先级更高的问题中

**Comment by aylei** [comment]
@heni02 可以验证了

**Comment by heni02** [comment]
<img width="1165" alt="企业微信截图_2ce34db6-5918-4f58-8d64-c3461d1eb810" src="https://github.com/matrixorigin/matrixone/assets/113406637/b6d2e6e3-e6f0-4d7a-a21d-b96aef0cc74a">
main :32a05ab7000d1206a5c70aa036bf4a2d4f39e207 启动直接报错，启动失败
<img width="1582" alt="企业微信截图_67b4b252-634e-47cd-bf77-5b4dc12e6d21" src="https://github.com/matrixorigin/matrixone/assets/113406637/550fe063-04d2-4c5c-8bae-40fc102db8cd">

**Comment by YANGGMM** [comment]
plz test again @heni02

**Comment by heni02** [comment]
待验证

**Comment by heni02** [comment]
和@aylei沟通，在toml配置文件增加配置python版本项，用来适应机器python多版本的情况，对用户更友好，reopen这个issue

**Comment by aylei** [comment]
@heni02 PTAL

**Comment by heni02** [comment]
confirm，closed
