### ISSUE TITLE
[Bug]: fix stats for values scan

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#13887]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1044" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/f9d5a124-2a18-47c9-90df-a2af9a8de896">

In the ReCalcNodeStats function, the logic related to the statistical value of value scan is commented out, and there is no related issue tracking.

The reason why it was commented out before seems to be that the statistical information's support for prepare SQL is not complete enough, which will cause the join order of the prepare statement to be incorrect.

https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/plan/stats.go

### Expected Behavior

Turn on relevant statistical support, which fuzzy filter needs to estimate how much memory the Bloom filter needs to apply for. 

### Steps to Reproduce

```Markdown
null
```

**Comment by badboynt1** [comment]
fixed
