### ISSUE TITLE
[Bug]: LOAD DATA from Aliyun with ARN report 'ErrorMessage=Authorization header is invalid'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13906]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8.0.30-MatrixOne-v1.0.2 （qa环境）

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Conclusion:
<img width="1338" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/815c05f2-6ced-4f2e-ba7d-8b64eb4e2260">

Steps：
1. Create a role named 'TestYunPingTai' and modify trust policy： 
<img width="1237" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/74348e5b-f553-4933-98c5-69729c0386d8">
<img width="1179" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/dc3a3ae9-b324-43f7-8519-b0e6fa3bfb17">

2. Create a permission Policy：
<img width="1233" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b446a14b-53bc-46f5-9bc6-c41e538fde12">

3. Authorization operation：
<img width="877" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cb747f34-8749-460b-bfec-020b223d4f5f">

4. 使用mysql客户端连接mo：
mysql -h freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech -P 6001 -u 78f9e5f9_67fa_4089_a81e_318276be6ae1:admin:accountadmin  -pAdmin123

5. 执行sql：
  ```
 create database test;
 use test；
 create table `temporary02` (`ts` timestamp not null,`col2` double default null,`col3` double default null,`col4` float default null,primary key (`ts`));
 load data url s3option {"endpoint"='oss-cn-hangzhou.aliyuncs.com', "bucket"='ariznawl', "filepath"='temporary.csv', "role_arn"='acs:ram::1011981963396790:role/testyunpingtai',"region"='oss-cn-hangzhou',"compression"='auto',"external_id"='abcd1234'} into table temporary02 FIELDS TERMINATED BY '|';
```
 

### Steps to Reproduce

```Markdown
As above.
```

**Comment by reusee** [comment]
这里有两个问题。一个是阿里云oss的接口不带错误返回值，我们的代码里是用logutil.Error打印，没有抛出，所以实际出现了错误，但仍然使用空的验证参数去进行下一步操作，导致 authorization header invalid。这个会提pr修正，返回真正的错误到上层。

另一个问题是，云平台使用的阿里云RAM账户，可能未被赋予 [AliyunSTSAssumeRoleAccess](https://ram.console.aliyun.com/policies/AliyunSTSAssumeRoleAccess/System/content) 权限。麻烦 @aylei 确认下？

**Comment by aylei** [comment]
> 这里有两个问题。一个是阿里云oss的接口不带错误返回值，我们的代码里是用logutil.Error打印，没有抛出，所以实际出现了错误，但仍然使用空的验证参数去进行下一步操作，导致 authorization header invalid。这个会提pr修正，返回真正的错误到上层。
> 
> 另一个问题是，云平台使用的阿里云RAM账户，可能未被赋予 [AliyunSTSAssumeRoleAccess](https://ram.console.aliyun.com/policies/AliyunSTSAssumeRoleAccess/System/content) 权限。麻烦 @aylei 确认下？

目前是有 AliyunSTSAssumeRoleAccess 权限的

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
fixed

**Comment by reusee** [comment]
all fixes merged. re-assigning.

**Comment by Ariznawlll** [comment]
这个修完进了1.1-dev和main，但是因为云平台qa环境现在用的是版本1.0.2，所以需要云平台更新了之后再测试。

**Comment by Ariznawlll** [comment]
测试版本 mocloud dev环境：
<img width="218" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9dcf64f6-6f8f-4a76-97ae-e85a012a8e61">


Steps:
1. Create a role named 'Testarn' and modify trust policy：
<img width="1439" alt="企业微信截图_88982ca8-ca20-487b-a498-d77039c00de4" src="https://github.com/matrixorigin/matrixone/assets/108530700/50416c70-316e-4bd2-80d1-7e68c12eae2f">

2. Create a permission Policy
<img width="1046" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9c6f7239-2c42-4012-9f73-034bd24ef9eb">

3. Authorization operation
<img width="876" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/985db630-6213-4700-a16e-da91a3c710de">

4. 使用mysql客户端连接mo：
mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u 76ea92e3_0493_4117_a266_1134f2ec2bc1:admin:accountadmin  -p

5. create database test;
use test；
create table `temporary02` (`ts` timestamp not null,`col2` double default null,`col3` double default null,`col4` float default null,primary key (`ts`));
load data url s3option {"endpoint"='oss-cn-hangzhou.aliyuncs.com', "bucket"='ariznawl', "filepath"='temporary.csv', "role_arn"='acs:ram::1011981963396790:role/testarn',"region"='oss-cn-hangzhou',"compression"='auto',"external_id"='abcd1234'} into table temporary02 FIELDS TERMINATED BY '|';

桶中的数据路径：
<img width="1198" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b09a37cf-e940-494c-ac9d-6a83d4ff04c2">

Result：现在load语法不报错了，但是数据没有load进去
<img width="1875" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2ef86cf0-2c0f-4cbf-8f92-97fe89973295">

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/issues/14328
等这个修好再测试.

**Comment by Ariznawlll** [comment]
14328跟踪
