### ISSUE TITLE
[Bug]: python udf: function returns varchar type as python return str type reported unexpected indent (<string>, line 1)

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#13901]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a553f08d2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

python def return str type  and function define return varchar/char reported error : rpc error: code = Unknown desc = Exception iterating responses: unexpected indent (<string>, line 1)
<img width="1561" alt="企业微信截图_0144a44e-f2f2-40ac-bd51-f2b664fb1d14" src="https://github.com/matrixorigin/matrixone/assets/113406637/bc00e66b-dcdc-4847-8ef7-d29f974720c8">
<img width="1519" alt="企业微信截图_aaec936d-d7c3-4e56-b50b-70a0bfe3deae" src="https://github.com/matrixorigin/matrixone/assets/113406637/54cd5630-1280-413e-8ec0-0d12d7f6e5da">
mysql> create or replace function py_add(a int, b int) returns char language python as  $$ def add(a, b):  c=a+b  return str(c) $$ handler 'add';
Query OK, 0 rows affected (0.03 sec)

mysql> select py_add(1,10);
ERROR 1105 (HY000): rpc error: code = Unknown desc = Exception iterating responses: unexpected indent (<string>, line 1)

### Steps to Reproduce

```Markdown
mysql> create or replace function py_add(a int, b int) returns varchar(25) language python as  $$ def add(a, b):  c=a+b  return str(c) $$ handler 'add';
Query OK, 0 rows affected (0.05 sec)

mysql> select py_add(1,10);
ERROR 1105 (HY000): rpc error: code = Unknown desc = Exception iterating responses: unexpected indent (<string>, line 1)
mysql> drop function py_add(int, int);
Query OK, 0 rows affected (0.03 sec)

mysql> create or replace function py_add(a int, b int) returns varchar language python as  $$ def add(a, b):  c=a+b  return str(c) $$ handler 'add';
Query OK, 0 rows affected (0.03 sec)

mysql> select py_add(1,10);
ERROR 1105 (HY000): rpc error: code = Unknown desc = Exception iterating responses: unexpected indent (<string>, line 1)
mysql> drop function py_add(int, int);
Query OK, 0 rows affected (0.03 sec)

mysql> create or replace function py_add(a int, b int) returns char language python as  $$ def add(a, b):  c=a+b  return str(c) $$ handler 'add';
Query OK, 0 rows affected (0.03 sec)

mysql> select py_add(1,10);
ERROR 1105 (HY000): rpc error: code = Unknown desc = Exception iterating responses: unexpected indent (<string>, line 1)
mysql>
```

**Comment by aylei** [comment]
Discussed with @dengn , this would be a feature of 1.2.0

**Comment by aylei** [comment]
not a bug, documented here: https://github.com/matrixorigin/matrixone/pull/13904

**Comment by aylei** [comment]
feature request https://github.com/matrixorigin/matrixone/issues/13907

please kindly close this issue if the above feature would help

**Comment by heni02** [comment]
confirm,closed
