### ISSUE TITLE
[Bug]: ExpectedDup occurs in the table created by MergeRUN

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#13900]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

3678728524aa506bd98b1b3f63490013f2723528

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7330795784/job/19962780250
<img width="1909" alt="企业微信截图_c7c0fffc-540e-47a2-95fe-2cb0df02a0b7" src="https://github.com/matrixorigin/matrixone/assets/14086886/9d2584dd-f87a-48ca-b680-6bc68e5e73ec">
<img width="1246" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/4b9ba897-a1bd-424a-97f6-b7f5dbfb87c4">

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by LeftHandCold** [comment]
multi-cn-e2e-with-race-linux-x86-reports.zip

**Comment by LeftHandCold** [comment]
[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/13784729/multi-cn-e2e-with-race-linux-x86-reports.zip)

**Comment by m-schen** [comment]
与 #13853 应该属于类似问题。
create table 发生retry 产生了错误情况。

**Comment by zhangxu19830126** [comment]
fixed by #13912

**Comment by heni02** [comment]
main回归还是有这个问题，和不久前问题一样#13615
commit：d5c2a6402
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7432176521/job/20228316355
<img width="1409" alt="企业微信截图_399306e9-b718-4c15-ba13-a69586ba9c32" src="https://github.com/matrixorigin/matrixone/assets/113406637/84d0248d-bf3a-461c-b438-a9111364f3f6">

mo log：
http://175.178.192.213:30088/explore?panes=%7B%22Sty%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240106%5C%22%7D%20%7C%3D%20%60ExpectedDup%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704582600000%22,%22to%22:%221704582840000%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1416" alt="企业微信截图_e6fd869d-1dad-473b-8838-10c99ef5e851" src="https://github.com/matrixorigin/matrixone/assets/113406637/52b91758-6f5d-4403-b89d-719f1cae23db">

**Comment by zhangxu19830126** [comment]
Our adjust(delete and insert order) logic is wrong.

**Comment by nnsgmsone** [comment]
已经定位到问题，和14046一样的问题，具体的信息会在14046补充

**Comment by heni02** [comment]
confirm,closed
1.1-dev commit：bc6b58b212aa868bf5a37493e8484954600ae660
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7601681831/job/20701360620
<img width="313" alt="企业微信截图_d34eb93f-ac92-43ee-ba3e-8c9d11d3d033" src="https://github.com/matrixorigin/matrixone/assets/113406637/fcaae6f9-9373-43cd-bd0f-e7bc32b59fd2">

main commit:ff5e808a4650f2d21937838016eb18ae837fdf00
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7612730620/job/20730965137
