### ISSUE TITLE
[Bug]: lots of errors "internal error: can not find table by id 2" duaring stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#13911]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.1

### Commit ID

10b2ec599110a634abc051d40577b24164da9db4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2023/12/28 09:24:53.475444 +0000","caller":"disttae/engine.go:282","msg":"error: internal error: can not find table by id 2","span":{"trace_id":"a2c9b5bf-337b-9c4f-d13a-25f4f792f922","span_id":"e9de29ae4cc624d6"}}
{"level":"ERROR","time":"2023/12/28 09:24:53.484277 +0000","caller":"disttae/engine.go:282","msg":"error: internal error: can not find table by id 2","span":{"trace_id":"b1dc9664-a92f-d6ca-1595-beb42cded00e","span_id":"00f27785d9ab9816"}}
{"level":"ERROR","time":"2023/12/28 09:24:53.504242 +0000","caller":"disttae/engine.go:282","msg":"error: internal error: can not find table by id 2","span":{"trace_id":"dfaf6c19-0994-bbd9-4c0d-fc733c5e4982","span_id":"48ad8dfbf2bdb37e"}}
{"level":"ERROR","time":"2023/12/28 09:24:53.507277 +0000","caller":"disttae/engine.go:282","msg":"error: internal error: can not find table by id 2","span":{"trace_id":"c56eb165-9a8e-c81f-cf45-62626ea57479","span_id":"e60009a22dc58f9a"}}
{"level":"ERROR","time":"2023/12/28 09:24:53.510054 +0000","caller":"disttae/engine.go:282","msg":"error: internal error: can not find table by id 2","span":{"trace_id":"63c4b26f-2c82-5d0b-4ace-d126d682a5f6","span_id":"5b312ac3f3996672"}}

mo log:
http://10.222.6.1/explore?panes=%7B%22kZk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20231228%5C%22%7D%20%7C%3D%20%60can%20not%20find%20table%20by%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221703754000000%22,%22to%22:%221703761187000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by m-schen** [comment]
id 2应该是mo_tables吧，不应该存在找不到的情况。

**Comment by ouyuanning** [comment]
从日志看不出来啥。发生can not find table by id的时候，似乎都有morpc连接的报错，

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
下周跟莫尘讨论下如何增加日志

**Comment by ouyuanning** [comment]
这2天还没空看

**Comment by nnsgmsone** [comment]
构造了dump分支，正在复现

**Comment by nnsgmsone** [comment]
已经提交了core dump到main，等待复现后的core dump

**Comment by nnsgmsone** [comment]
等待复现后的core dump

**Comment by ouyuanning** [comment]
PR待合并

**Comment by aressu1985** [comment]
fixed
