### ISSUE TITLE
[Bug]: select * doesn't support date type

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#1391]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):21dd550
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t1(a date);
Query OK, 0 rows affected (0.44 sec)

mysql> insert into t1 values("2022-01-1");
Query OK, 1 row affected (0.06 sec)

mysql> select * from t1;
ERROR 1105 (HY000): unknown error:unsupport type DATE

### Expected Behavior

mysql> create table t1(a date);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values("2021-02-01");
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+------------+
| a          |
+------------+
| 2021-02-01 |
+------------+
1 row in set (0.00 sec)

**Comment by m-schen** [comment]
has been solved. will push code after factor branch merge into main.

**Comment by m-schen** [comment]
it is done.
