### ISSUE TITLE
[Feature Request]: DATALINK type

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#13914]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
This request is for a rough equivalent of the DB2 datalink type.
https://www.ibm.com/docs/en/i/7.2?topic=datalinks-working
```

### Describe the feature you'd like

I don't think we need the full datalink feature, but essentially, we want a new datatype, which can points to a file stored outside of the database.   The datalink type should contain an URL, which is either a public https/s3, or file inside one of our stage.   

This is especially useful for storing image/video and other big files.   It is a must have for AI applications.

Note that main consumer of this feature is probably UDF.   And/or content serving.

**Comment by fengttt** [comment]
Note that this is not a simple URL type -- we should allow stage syntax, and with that, all those authentication and authorization of the stage must be checked.

**Comment by arjunsk** [comment]
Waiting for the STAGE PR to be merged to master.

**Comment by aressu1985** [comment]
TEST DONE
