### ISSUE TITLE
[Bug]: Just starting without doing anything, the proportion of CPU is very high

### ISSUE THREAD

**Issue by iwanlebron** [matrixorigin/matrixone#13922]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.0

### Commit ID

v1.1.0

### Other Environment Information

```Markdown
- Hardware parameters: m1 mac 
- OS type: arm64 
- Others:
```

### Actual Behavior

<img width="591" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/0277a722-ff66-4e9e-a284-85ae68d9620d">
<img width="872" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/db2ba78c-9c57-425b-8a82-10ec158ed2b2">
<img width="1056" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/93e06a92-21ef-4ca2-997f-c7ead91d97a9">

### Steps to Reproduce

```Markdown
Just starting without doing anything, the proportion of CPU is very high
```

**Comment by m-schen** [comment]
mac系统的活动监视器， 以及linux系统下的top命令等和windows系统的任务管理器不一样，

它所显示的cpu%并不是cpu占用率。
20%指的是使用了0.2核。
@iwanlebron

**Comment by iwanlebron** [comment]
内存一直在涨
<img width="927" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/4203df9e-2da4-4339-b71b-9aa8698632c6">

**Comment by iwanlebron** [comment]
230-540了

**Comment by m-schen** [comment]
这个不是真实内存...
你使用活动监视器的话要自己右键勾选 真实内存 显示的才是对的。
@iwanlebron

**Comment by iwanlebron** [comment]
在Linux上也是这样的 我发一下截图

**Comment by iwanlebron** [comment]
<img width="406" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/9cc2aacf-2735-4300-839f-7511e04f5dc5">
实际内存也是啊

**Comment by m-schen** [comment]
那可能与go的内存回收机制有关，你可以多观察一段时间看看是否有这种情况。

go语言的gc机制并不是隔段时间回收，而是内存占用少时，需要达到上次回收点的两倍触发gc。后面内存占用大了时达到原来的 4 / 3 还是 5 / 4时回收。

**Comment by iwanlebron** [comment]
<img width="710" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/3985cb9e-2a98-414d-a6b6-a5cc6be9ff93">
内存一直在升 没有降过

**Comment by iwanlebron** [comment]
<img width="983" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/d336f07a-b60a-45c7-b12d-9dbf097c7f15">

**Comment by iwanlebron** [comment]
<img width="903" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/509c90de-e746-4cc2-9203-51ddae45548f">

**Comment by iwanlebron** [comment]
<img width="663" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/f225b2d8-9221-4cdc-bdbb-e31caf683fe6">

**Comment by iwanlebron** [comment]
<img width="696" alt="image" src="https://github.com/matrixorigin/matrixone/assets/105045937/1267289b-3b01-41eb-9ed7-993c1aef7bf9">
