### ISSUE TITLE
[Bug]: UT failed in ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13943]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll/ModifyCaseResultYear

### Commit ID

77c9f6d2aa566116b858f98cae8d5c1226a72616

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1420" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/deda7ac7-68e7-457f-8381-b0173ca503a6">

raw logs：https://pipelinesghubeus4.actions.githubusercontent.com/6i0uluWebzzWKTJsdip1dxNGG262TgSnWdbPahnwpPRJIunOgs/_apis/pipelines/1/runs/201262/signedlogcontent/11?urlExpires=2024-01-02T06%3A26%3A57.2018703Z&urlSigningMethod=HMACV1&urlSignature=VJHl7oIrFcScjD0LitYKL8Ey%2B%2B2mDDcS32uaqzv%2BCuU%3D

log：[logs_201262.zip](https://github.com/matrixorigin/matrixone/files/13807637/logs_201262.zip)

### Steps to Reproduce

```Markdown
Pull requests and run ci test.
```

**Comment by volgariver6** [comment]
fixed
