### ISSUE TITLE
[Bug]: Bvt test failed when run ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#13944]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll/ModifyCaseResultYear

### Commit ID

77c9f6d2aa566116b858f98cae8d5c1226a72616

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1013" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b310d019-cc7f-44d8-b188-e1cced7586f3">

log:[multi-cn-e2e-push-docker-compose-log-pessimistic.zip](https://github.com/matrixorigin/matrixone/files/13807656/multi-cn-e2e-push-docker-compose-log-pessimistic.zip)

### Steps to Reproduce

```Markdown
Pull request and run ci test.
```

**Comment by sukki37** [comment]
repro：
https://github.com/matrixorigin/matrixone/actions/runs/7397305491/job/20124189258
https://github.com/matrixorigin/matrixone/actions/runs/7397232166/job/20123977845
https://github.com/matrixorigin/matrixone/actions/runs/7396796034/job/20122662621

**Comment by qingxinhome** [comment]
定位中

**Comment by daviszhen** [comment]
分析中，初步找到原因。在修改。

**Comment by daviszhen** [comment]
修改中。

**Comment by daviszhen** [comment]
pr中

**Comment by daviszhen** [comment]
pr review中

**Comment by daviszhen** [comment]
pr review中

**Comment by daviszhen** [comment]
main 和 1.1-dev都merge了。

**Comment by Ariznawlll** [comment]
verified!
