### ISSUE TITLE
[Bug]: cannot run on Linux with gcc 7.3.0

### ISSUE THREAD

**Issue by iwanlebron** [matrixorigin/matrixone#13960]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.0

### Commit ID

v1.1.0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: linux-arm64
- Others:
```

### Actual Behavior

./mo-service: /usr/lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./mo-service)

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/home/abuild/rpmbuild/BUILD/gcc-7.3.0/obj-aarch64-linux-gnu/isl-install --without-cloog --enable-gnu-indirect-function --build=aarch64-linux-gnu --with-stage1-ldflags=' -Wl,-z,relro,-z,now' --with-boot-ldflags=' -Wl,-z,relro,-z,now' --with-multilib-list=lp64
Thread model: posix
gcc version 7.3.0 (GCC) 

### Steps to Reproduce

```Markdown
./mo-service: /usr/lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./mo-service)

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/home/abuild/rpmbuild/BUILD/gcc-7.3.0/obj-aarch64-linux-gnu/isl-install --without-cloog --enable-gnu-indirect-function --build=aarch64-linux-gnu --with-stage1-ldflags=' -Wl,-z,relro,-z,now' --with-boot-ldflags=' -Wl,-z,relro,-z,now' --with-multilib-list=lp64
Thread model: posix
gcc version 7.3.0 (GCC)
```

**Comment by iwanlebron** [comment]
是否可以不依赖系统环境呢

**Comment by iwanlebron** [comment]
静态打包编译

**Comment by triump2020** [comment]
@tianyahui-python pls take a look ?

**Comment by domingozhang** [comment]
same impact with gcc version 8.5.0 20210514.
./mo-service: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./mo-service)

**Comment by guguducken** [comment]
目前因为使用了非标准库CGO，基于glic无法实现完全静态编译，目前正在测试基于musl进行打包

**Comment by fengttt** [comment]
This is not a bug.    I recommend user upgrade the linux and/or gcc.

**Comment by iwanlebron** [comment]
Well, it's not a bug, but upgrading the machine system is also quite difficult. There are already many services running

**Comment by WuMenglong** [comment]
您先使用这个来测试：
https://community-shared-data-1308875761.cos.ap-beijing.myqcloud.com/glibc/mo-v1.1.0-linux-x86_64.tar.gz

**Comment by iwanlebron** [comment]
This is operational. Is there an arm64 available?

**Comment by WuMenglong** [comment]
> This is operational. Is there an arm64 available?

ARM架构和x86架构需要使用不同的包。若您ARM的服务器系统glibc版本同样较低，推荐您在相应的ARM环境中使用源代码来手动编译。社区会尽快开发出不依赖系统环境的方案。

**Comment by iwanlebron** [comment]
那这样是不是需要每台服务器都编译呢
