### ISSUE TITLE
[Bug]: Significant Performance Discrepancy Between Single Table and Multi-Table Queries in Sysbench Point Selects

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#13968]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

064c1cf

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The point select performance on a single table is significantly lower compared to multi-table operations. The difference is not marginal and suggests a potential issue in how operations are handled or optimized.

<img width="730" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/51830ae2-e4e8-4564-8dd1-32d6a14c4db6">

### Steps to Reproduce

```shell
1. start mo locally 
2. git clone https://github.com/matrixorigin/mo-load.git && cd mo-load
3. create database sbstest
# test point select performance on 10 empty tables
4. ./start.sh -m SYSBENCH -n 10 -s 0
5. ./start.sh -c cases/sysbench/point_select_10_100000 -b sbtest
# test point select performance on 1 empty tables
6. cp -r cases/sysbench/point_select_10_100000 cases/sysbench/point_select_1_100000
7. vim cases/sysbench/point_select_1_100000/replace.yml, replace it with the following content
```
```
replace:
- name: id
  type: random
  range: 1,100000
- name: i_id
  type: sequence
  start: 100001
  step: 1
- name: tbx
  type: random
  range: 1,1
```
``` shell
8. ./start.sh -m SYSBENCH -n 1 -s 0
9. ./start.sh -c cases/sysbench/point_select_1_100000 -b sbtest
```

**Comment by sukki37** [comment]
<img width="1680" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/2eae7885-20ae-4a38-94e4-343f38103aa6">

**Comment by XuPeng-SH** [comment]
dev done

**Comment by heni02** [comment]
验证以上四种情况点查并发50测试
1.1-dev验证通过 commit：3c3362b875b0d11eba023438a4fdcbff1b0700fd 
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>


  | tps/qps
-- | --
10 tables*0 row | 21907
1tables*0 row | 22858
10 tables*100000 row | 19191
1 tables*100000 row | 19370



</body>

</html>

10tables * 0rows：
<img width="1215" alt="企业微信截图_27d663c9-48b7-46cb-9d5a-8dfe0525b8d9" src="https://github.com/matrixorigin/matrixone/assets/113406637/a8b05c29-5091-43a7-8e04-fac549d9bf33">

1tables * 0rows：
<img width="1068" alt="企业微信截图_a3f5250a-103e-4d35-a082-d98ae29203e7" src="https://github.com/matrixorigin/matrixone/assets/113406637/6dec7c50-17c0-489c-80be-778fbcfaecc2">

10 tables*100000 row：
<img width="1149" alt="企业微信截图_07f011c8-2c33-4baa-b621-d7571d142db6" src="https://github.com/matrixorigin/matrixone/assets/113406637/d4596cad-2e99-4437-9f34-9c268bb76c82">

1 tables*100000 row：
<img width="1103" alt="企业微信截图_6f8cae27-fe76-4db7-bcea-e44b347ba51e" src="https://github.com/matrixorigin/matrixone/assets/113406637/efa4b908-0a6c-4808-916e-241eab781a73">

**Comment by heni02** [comment]
main  commit：b2259380fb51d68f7b45705118ee6d2a823a3279
测试结果：单个表和多个表tps性能基本相同
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>


  | tps/qps
-- | --
10 tables*0 row | 20157
1tables*0 row | 20421
10 tables*100000 row | 19008
1 tables*100000 row | 18208



</body>

</html>

测试过程：
10tables * 0rows：
<img width="1196" alt="企业微信截图_f957710b-e5a4-4457-b187-6b168208df74" src="https://github.com/matrixorigin/matrixone/assets/113406637/e8e71341-7596-4b7b-840c-f7f033df90fd">

1tables * 0rows：
<img width="1155" alt="企业微信截图_ccca0ea5-7e41-4bdc-b8c4-3e88fc7864a0" src="https://github.com/matrixorigin/matrixone/assets/113406637/5e6a4ccc-e86d-48fd-9c88-b86e976ac13b">

10 tables*100000 row
<img width="1097" alt="企业微信截图_836c284b-ebb1-4cae-8dee-031e28ac6d74" src="https://github.com/matrixorigin/matrixone/assets/113406637/18627841-6957-49fe-876f-2119a06eb8d5">

1 tables*100000 row
<img width="1162" alt="企业微信截图_114fa6ac-775c-47bf-942b-37b6b16449e5" src="https://github.com/matrixorigin/matrixone/assets/113406637/9efd8722-a4dc-4fc6-a634-9e2b9b990d56">
