### ISSUE TITLE
[Bug]: mo failed during booting

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#1397]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0afce2d9f140c0cb18a7b2c5d0c5db4f75c4b6bc
- Hardware parameters:
- OS type:mac pro
- Others: mo main branch
```

### Actual Behavior

booting failed.

### Expected Behavior

mo starts successfully

### Steps to Reproduce

```markdown
first ,boot mo successfully.
load some data.
Then, kill mo will ctrl+c.
boot mo again.
```

### Additional information

[1215-1.txt](https://github.com/matrixorigin/matrixone/files/7717043/1215-1.txt)

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/146163055-45bf8e6b-a371-4cc1-be4d-08abab438f63.png)

**Comment by LeftHandCold** [comment]
Need to execute: ulimit -n 65535
