### ISSUE TITLE
[Bug]: mo crashed during booting

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#1398]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0afce2d9f140c0cb18a7b2c5d0c5db4f75c4b6bc
- Hardware parameters:
- OS type:mac pro
- Others:main branch
```

### Actual Behavior

mo crashed

### Expected Behavior

mo starts successfully

### Steps to Reproduce

```markdown
boot mo successfully.
load some data.
ctr+c kill the mo.
boot mo.
```

### Additional information

[1512-2.txt](https://github.com/matrixorigin/matrixone/files/7717060/1512-2.txt)

**Comment by daviszhen** [comment]
Sometimes，it generates stuffs. 
==================

shard 39, peer count is 1
shard 1003, peer count is 1
shard 24, peer count is 1
shard 15, peer count is 1
shard 16, peer count is 1
shard 38, peer count is 1
shard 29, peer count is 1
shard 6, peer count is 1
shard 13, peer count is 1
shard 21, peer count is 1
shard 8, peer count is 1
shard 22, peer count is 1
ClusterStatus is ok now
2021/12/15 15:02:13 start server failed with cannot create listening socket: too many open files
panic: start server failed with cannot create listening socket: too many open files

goroutine 1 [running]:
log.Panicf({0x589f9ea, 0x3}, {0xc006379c18, 0xc006379c28, 0x2})
	/Users/pengzhen/.gvm/gos/go1.17/src/log/log.go:361 +0x67
github.com/matrixorigin/matrixone/pkg/frontend.NewMOServer({0xc00019c3c0, 0xc}, 0xc0032f6e10, 0xc0030303c0)
	/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/server.go:72 +0x346
main.createMOServer(0x5b9cd80)
	/Users/pengzhen/Documents/GitHub/matrixone/cmd/db-server/main.go:91 +0x230
main.main()
	/Users/pengzhen/Documents/GitHub/matrixone/cmd/db-server/main.go:306 +0x10ab

**Comment by LeftHandCold** [comment]
Need to execute: ulimit -n 65535
