### ISSUE TITLE
[Bug]: SCA Failed when bump go version from 1.20 to 1.21.5

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#13983]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f9a847e41b584812e91153c187396aa7054f8cda

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="654" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/7564defd-2c51-4972-bf9c-676eb801e71d">

### Expected Behavior

no lint error

### Steps to Reproduce

```Markdown
1. install go 1.21.5
2. git clone https://github.com/guguducken/matrixone.git -b upgrade_go_version
3. make install-static-check-tools
4. make static-check
```

**Comment by guguducken** [comment]
it might help: https://github.com/golang/go/issues/60048

**Comment by gouhongshen** [comment]
sca err fixed
