### ISSUE TITLE
[Bug]:  Bvt test case error Occasionally

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#13996]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d6f55638051f4200650f3fb3a379e28be567b9df

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/70939751/574031d5-12d0-4ef4-93af-a2c4ad259baf)
[ACTUAL_RESULT.txt](https://github.com/matrixorigin/matrixone/files/13825096/ACTUAL_RESULT.txt)
[EXPECT_RESULT.txt](https://github.com/matrixorigin/matrixone/files/13825097/EXPECT_RESULT.txt)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/7404421431/job/20145908049?pr=13963
```

**Comment by xzxiong** [comment]
dup as https://github.com/matrixorigin/matrixone/issues/12168
