### ISSUE TITLE
[Bug]: ci bvt reports "statement_query_type.sql" error at high frequency

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#13990]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1349" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/d992c72f-0cb4-4904-84a4-645cb162938d">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/7396619125/job/20122259309
https://github.com/matrixorigin/matrixone/actions/runs/7397232166/job/20123977845
https://github.com/matrixorigin/matrixone/actions/runs/7396619125/job/20122259309
```

**Comment by sukki37** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/12168
