### ISSUE TITLE
[Question]: Could you please help us provide SQL related to the management model

### ISSUE THREAD

**Issue by qianmoQ** [matrixorigin/matrixone#13993]
### Describe your problem

Since we want to support MatrixOne databases in datacap, we need to provide the following SQL templates for managing MatrixOne metadata in datacap and implementing Navicat-like functions.

- `SYSTEM_FOR_GET_ALL_DATABASES`
> MySQL example, please see https://github.com/devlive-community/datacap/blob/4551ef08aea8298969c6482e2e1442f8cd012c78/core/datacap-server/src/main/schema/1.15.0/schema.sql#L97

- `SYSTEM_FOR_GET_ALL_TABLES `
> MySQL example, please see https://github.com/devlive-community/datacap/blob/4551ef08aea8298969c6482e2e1442f8cd012c78/core/datacap-server/src/main/schema/1.15.0/schema.sql#L105

- `SYSTEM_FOR_GET_ALL_COLUMNS `
> https://github.com/devlive-community/datacap/blob/4551ef08aea8298969c6482e2e1442f8cd012c78/core/datacap-server/src/main/schema/1.15.0/schema.sql#L131

**Comment by dengn** [comment]
These information_schema tables are different with MySQL, we'll investigate and give a solution.

**Comment by WuMenglong** [comment]
These information_schema information are the same as those of MySQL and can be used directly.
