### ISSUE TITLE
[Bug]: ci bvt report "MO does not return result in 120000ms" error at high frequency

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#13991]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1314" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/25578055-c2c2-4d15-9884-30b5c6e14ecd">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/7397305491/job/20124189258
https://github.com/matrixorigin/matrixone/actions/runs/7397232166/job/20123977845
https://github.com/matrixorigin/matrixone/actions/runs/7396796034/job/20122662621
```

**Comment by sukki37** [comment]
dup with #13944
