### ISSUE TITLE
[Bug]: TPCC daily regression on 128 report 'internal error: unsupported command. 0x434f4d5f5345545f4f5054494f4e'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14000]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4a76c897d6e0e7f80b868c66fea8097431c39712

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7398246289/job/20127190473
<img width="1390" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9b40f24f-4908-4781-b4bf-d96e7c8254ec">

mo-tpcc-log: the log is very large, i will send it to you privately.

mo-log: [molog.tar.gz](https://github.com/matrixorigin/matrixone/files/13825335/molog.tar.gz)

profile: [prof.zip](https://github.com/matrixorigin/matrixone/files/13837256/prof.zip)

### Steps to Reproduce

```Markdown
daily regression on 128.
```

**Comment by triump2020** [comment]
![1704350985894](https://github.com/matrixorigin/matrixone/assets/63033222/540ae689-9173-4d1c-9989-3a390265ef44)

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2024/01/09 06:44:12.640139 +0800","name":"log-service.frontend","caller":"frontend/mysql_cmd_executor.go:2820","msg":"internal error: panic runtime error: invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/process.(*Process).GetPrepareParamsAt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/process/types.go:418\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*ParamExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:342\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:483\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:250\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1116\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1106\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:594\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:3487\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1993\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1062\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:901\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3916\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4124\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 401|127.0.0.1:38172|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 40981|714363d0-ae77-11ee-925f-b07b25f8b524","session_id":"714363d0-ae77-11ee-925f-b07b25f8b524","statement_id":"71aa3130-ae77-11ee-925f-b07b25f8b524","txn_id":"41d55a706c2145c8a071e4f243e2dafb/Active/S:1704753852635540672-1"}
{"level":"ERROR","time":"2024/01/09 06:44:12.640262 +0800","name":"log-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","connection_id":401,"statement":"UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?","status":"fail","error":"internal error: panic runtime error: invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/process.(*Process).GetPrepareParamsAt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/process/types.go:418\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*ParamExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:342\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:483\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:250\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1116\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1106\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:594\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:3487\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1993\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1062\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:901\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3916\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4124\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650","span":{"trace_id":"d46288b9-cb9f-349b-7f70-510f877c91a0","span_id":"a33d48bcd07115a6"},"session_info":"connectionId 401|127.0.0.1:38172|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 40981|714363d0-ae77-11ee-925f-b07b25f8b524","session_id":"714363d0-ae77-11ee-925f-b07b25f8b524","statement_id":"71aa3130-ae77-11ee-925f-b07b25f8b524"}
{"level":"ERROR","time":"2024/01/09 06:44:12.651294 +0800","caller":"compile/compile.go:225","msg":"error: internal error: panic runtime error: invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/process.(*Process).GetPrepareParamsAt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/process/types.go:418\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*ParamExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:342\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:483\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:250\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1116\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1106\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:594\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:3487\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1993\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1062\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:901\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3916\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4124\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650","span":{"trace_id":"8727bae8-665d-3a9f-f890-0a3cfc5364ae","span_id":"2386bd9bdd1e83dc"}}
{"level":"ERROR","time":"2024/01/09 06:44:12.651364 +0800","name":"log-service.pipeline","caller":"compile/compile.go:226","msg":"panic in compile","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","sql":"prepare __mo_stmt_id_36 from UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?","error":"internal error: panic runtime error: invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/process.(*Process).GetPrepareParamsAt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/process/types.go:418\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*ParamExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:342\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:483\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:250\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1116\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1106\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:594\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:3487\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1993\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1062\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:901\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3916\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4124\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
need to verify.

**Comment by Ariznawlll** [comment]
verified.
