### ISSUE TITLE
[Bug]: errorMessage "the connection between CN and TN has been disconnected" is not correct

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14007]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5f29ad3  

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the error message "the connection between CN and TN has been disconnected" means that there are something wrong of communication  between cn and tn.
But actually, sometimes TN is normal, only cns crash, mo also report this error, so the error need to be modified.

### Steps to Reproduce

```Markdown
kill on of cns during running TP load
```

**Comment by triump2020** [comment]
@volgariver6 pls take a look!

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed_
