### ISSUE TITLE
[Bug]: nternal error: vector idx out of range: 0 > 0 during stability test on distributed mode for TPCC new order tnx

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14006]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a7f4972

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed test, there are lots errors for tpcc txn, as following:
2024-01-04 00:57:52 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:05 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:09 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:13 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:15 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:23 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:29 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:55 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:58:55 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:59:01 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:59:03 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:59:05 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-01-04 00:59:06 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: vector idx out of range: 0 > 0

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by Ariznawlll** [comment]
log: http://10.222.6.1/explore?panes=%7B%22IfG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240103%5C%22%7D%20%7C%3D%20%60internal%20error:%20vector%20idx%20out%20of%20range%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704297600000%22,%22to%22:%221704315472000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by triump2020** [comment]
> vector idx out of range

@Ariznawlll  it seems that log can't be visisted?

**Comment by Ariznawlll** [comment]
> > vector idx out of range
> 
> @Ariznawlll it seems that log can't be visisted?

It can only be accessed from within the Shanghai office.

**Comment by aptend** [comment]
This issue is probably fixed by https://github.com/matrixorigin/matrixone/pull/14034

some facts:

1. these errors happened between 16:57 and 17:07, when 'out of memory' error also happened 
<img width="1679" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/2c6a96a6-4d5b-4fb1-8c78-ebf0f377ec90">

2. It is verified that local mocked out-of-memory error in `mpool.Alloc` can lead to this error, and the call stack is

```
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/matrixorigin/matrixone/pkg/container/vector.SetFixedAt[...](0x4?, 0x0?, 0xbba)
	/Users/aptend/code/matrixone/pkg/container/vector/vector.go:363 +0x7a
github.com/matrixorigin/matrixone/pkg/sql/util.SetBytesToAnyVector({0x103dac9f0?, 0xc051955e60}, {0xc005a99051, 0x4}, 0x1034c73c0?, 0x4?, 0xc03422e6e0, 0xc033ea9698?)
	/Users/aptend/code/matrixone/pkg/sql/util/eval_expr_util.go:112 +0x554
github.com/matrixorigin/matrixone/pkg/sql/compile.constructValueScanBatch({0x103dac9f0, 0xc051955e60}, 0xc0519622c0, 0x0?)
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:995 +0x7a6
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0x1?, 0x0, {0xc034228700?, 0xb, 0x10})
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:1015 +0xc6
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0x0?, 0x1, {0xc034228700?, 0xb, 0x10})
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:1052 +0x17ba
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0xe?, 0x2, {0xc034228700?, 0xb, 0x10})
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:1052 +0x17ba
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0x1?, 0x3, {0xc034228700?, 0xb, 0x10})
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:1302 +0x171a
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0x519622c0?, 0x4, {0xc034228700?, 0xb, 0x10})
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:1438 +0x1405
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0x0?, 0x5, {0xc034228700?, 0xb, 0x10})
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:1550 +0x6fd4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0xc033e23ef0)
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:889 +0x81b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope(0x103dac9f0?, {0x103dac9f0, 0xc051955e60}, 0xc034193840)
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:588 +0xec
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile(0xc0514f8680, {0x103dac9f0, 0xc051955e60}, 0xc034193840, {0x10353a380?, 0xc006c58800}, 0x1036f99f0)
	/Users/aptend/code/matrixone/pkg/sql/compile/compile.go:264 +0x48c
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0xc051964ff0, {0x103dac9f0, 0xc051955c50}, {0x0?, 0x17a84ee9588a2e10?}, 0x1036f99f0)
	/Users/aptend/code/matrixone/pkg/frontend/computation_wrapper.go:378 +0x10e8
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt(0xc033b2b380, {0x103dac9f0, 0xc051955c50}, 0xc006c58800, {0x103dad8d0, 0xc05195dcc0}, 0xc0519622c0, {0x103dda040?, 0xc051964ff0?}, 0x0, ...)
	/Users/aptend/code/matrixone/pkg/frontend/mysql_cmd_executor.go:3299 +0x32f2
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc033b2b380, {0x103dac9f0, 0xc051955920}, 0xc05195dc80)
	/Users/aptend/code/matrixone/pkg/frontend/mysql_cmd_executor.go:3899 +0x163e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc033b2b380, {0x103dac9f0, 0xc051955920}, 0x105a229a0?, 0xc00b08e6f0)
	/Users/aptend/code/matrixone/pkg/frontend/mysql_cmd_executor.go:4121 +0x11f9
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc004f05c80, 0xc00b08e6f0)
	/Users/aptend/code/matrixone/pkg/frontend/routine.go:252 +0xc43
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc006056000, {0x103de4c20, 0xc039f9b200}, {0x102ee5980?, 0xc05194c8e0}, 0xc004e17db0?)
	/Users/aptend/code/matrixone/pkg/frontend/routine_manager.go:504 +0xcb3
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc006046040, {0x103de4c20, 0xc039f9b200})
	/Users/aptend/code/matrixone/pkg/frontend/server.go:145 +0xad
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/Users/aptend/code/matrixone/vendor/github.com/fagongzi/goetty/v2/application.go:356 +0x7f
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 867
	/Users/aptend/code/matrixone/vendor/github.com/fagongzi/goetty/v2/application.go:348 +0x45a
```

**Comment by aptend** [comment]
waiting for merge https://github.com/matrixorigin/matrixone/pull/14034

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/14034 was merged

**Comment by aptend** [comment]
http://10.222.6.1/explore?panes=%7B%22IfG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240116%5C%22%7D%20%7C~%20%60%20vector%20idx%20out%20of%20range%7C:580.%2Aout%20of%20mem%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705432697868%22,%22to%22:%221705432698748%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
明天通过稳定性继续观察一天

**Comment by aressu1985** [comment]
fixed
