### ISSUE TITLE
[Bug]: internal error: panic close of nil channel: during stability test on distributed mode for  sysbench insert case

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14008]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a7f4972

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed test, there are lots errors for sysbench insert cases, as following:

2024-01-04 00:30:54 ERROR TransExecutor:129 -
ErrorTime : 2024-01-04 00:30:54
RequestTime : 2024-01-04 00:30:54.401
TxnName : insert_delete
Statement : insert into sbtest7 values(8830402,4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');
ErrorCode : 20101
ErrorMessage : internal error: panic close of nil channel:
runtime.closechan
        /usr/local/go/src/runtime/chan.go:359
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).getLockTableWithCreate.func2
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:324
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).getLockTableWithCreate
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:338
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:125
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:430
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:211
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:120
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:92
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:40
github.com/matrixorigin/matrixone/pkg/vm.Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:129
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:130
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:85
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:130
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
Expected : false

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by Ariznawlll** [comment]
log:http://10.222.6.1/explore?panes=%7B%22IfG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240103%5C%22%7D%20%7C%3D%20%60internal%20error:%20panic%20close%20of%20nil%20channel%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704297600000%22,%22to%22:%221704315472000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
