### ISSUE TITLE
[Bug]: performance: standalone point select 100 threads qps from 80000+ down to 60000+ during one and a half months

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14027]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7db9fe187d1d70a196961e3332919d92cf825ac9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

从11月20开始到1月4日qps从8万多每天持续降不超过25%到6万多，目前二分不太容易找到性能问题的pr，需要定位找出性能下降的原因
sysbench 10w 100并发tps：
<img width="696" alt="企业微信截图_6b119a2d-a3ab-4f46-83e2-d1bbeb32f4dd" src="https://github.com/matrixorigin/matrixone/assets/113406637/9ac0f063-b0ab-416b-9c3b-c1263c8366db">
sysbench 100w 100并发tps：
<img width="700" alt="企业微信截图_9271b0e3-71d2-4c27-932f-89c917738298" src="https://github.com/matrixorigin/matrixone/assets/113406637/2697243c-ee8f-44b3-95bd-332baf67095c">

其他发现1000并发性能没有出现下降
<img width="685" alt="企业微信截图_9058f459-d784-4d66-bba9-2ff400205cc1" src="https://github.com/matrixorigin/matrixone/assets/113406637/207b5da6-c790-49f7-a11b-7a5e6879bd7d">

tke环境浮动几千，没有出现大幅下降
<img width="678" alt="企业微信截图_cfd230dd-77a0-44a3-b372-9c85068693bd" src="https://github.com/matrixorigin/matrixone/assets/113406637/14022b37-9b08-4153-b2a7-6efb59da9c3e">

11月20日main commit：7c6af07c6
1月4日main commit：7db9fe187

### Steps to Reproduce

```Markdown
回归sysbench point select测试
```

**Comment by sukki37** [comment]
<img width="1428" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/f1fa97af-3bda-4559-a667-453b13364420">

**Comment by XuPeng-SH** [comment]
no clue now

**Comment by XuPeng-SH** [comment]
assigned to @gouhongshen

**Comment by gouhongshen** [comment]
will do some tests next week

**Comment by gouhongshen** [comment]
性能下降只出现在回归测试中。在其他负载完成后，再测试会出现性能下降。如果单独测试，没有明显的性能下降迹象。

单表，单机环境。

**Comment by heni02** [comment]
先降级

**Comment by heni02** [comment]
confirm，closed
sysbench100w100并发已经回到之前的性能水平
<img width="707" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/8051e299-1106-419d-9643-edd6a2af7182">

sysbench10w 100并发出现很多次浮动，根据定位原因属于正常浮动，先关闭
<img width="759" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/cc356dd3-84bf-42df-a738-771ff56f0376">
