### ISSUE TITLE
[Bug]: [0105] SSB Daily regression on tke report 'The query q4.3  has failed to  be executed'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14024]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7db9fe187d1d70a196961e3332919d92cf825ac9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url :https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7411209315/job/20165851667
<img width="1020" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b30ea4ef-ec7a-418e-965c-4b54747a9b72">

失败的时间对应的日志出现了大量的'use of network connection'.
<img width="1317" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cfdc8a26-114d-4500-8256-d97ae8756fbe">

log: http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240104%5C%22%7D%20%7C%3D%20%60failed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704409200000%22,%22to%22:%221704412799000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run daily regression on tke.
```

**Comment by triump2020** [comment]
![1704453924664](https://github.com/matrixorigin/matrixone/assets/63033222/4e046c01-a38e-471d-92d3-2bb64f1c6741)

**Comment by sukki37** [comment]
日志不对，应该是这个 http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240104%5C%22%7D%20%7C%3D%20%60query%20trace%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704382440000%22,%22to%22:%221704382619000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by Ariznawlll** [comment]
二分检查了一下，出现这个问题的commit id是：380e29e86c7bc11aae1055890f6e3e523553d076

**Comment by m-schen** [comment]
相关pr已合并于1.1和main分支，可以验证。

这个地方不应该报错的
（由于另一个问题a: 发送者在没东西要发的情况下不等待接收方信号 导致的，在正常执行流程里会出现该报错case），已去除该地方的错误检测，
后续改正问题a后会加回来。

**Comment by Ariznawlll** [comment]
verified.
