### ISSUE TITLE
[Bug]: table data count is not correct after altering table  add composite pk and failed to drop pk

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14020]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a7f4972

### Other Environment Information

```Markdown
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

after altering table add composite pk, the talbe count has been not correct.
mysql> load data url s3option {'endpoint'='cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='****', 'filepath'='mo-big-data/100000000_20_columns_load_data.csv'} into table big_data_test.table_basic_for_alter_100M fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 100000000 rows affected (1 min 45.68 sec)

mysql> select count(*) from table_basic_for_alter_100M;
+-----------+
| count(*)  |
+-----------+
| **100000000** |
+-----------+
1 row in set (0.70 sec)

mysql> alter table big_data_test.table_basic_for_alter_100M add PRIMARY KEY (col3,col4);
Query OK, 0 rows affected (14 min 23.56 sec)

mysql> select count(*) from table_basic_for_alter_100M;
+----------+
| count(*) |
+----------+
|  **3748426** |
+----------+
1 row in set (0.09 sec)

mysql> select count(*) from table_basic_for_alter_100M;
+----------+
| count(*) |
+----------+
|  3748426 |
+----------+
1 row in set (0.01 sec)

and then dropping pk, error report:
mysql> 
mysql> 
mysql> alter table big_data_test.table_basic_for_alter_100M drop PRIMARY KEY;
ERROR 1146 (HY000): no such table big_data_test.table_basic_for_alter_100m_copy_bdfcda24-aaf7-11ee-8bc9-228384ec3c6c
mysql> 
mysql> 
mysql> alter table big_data_test.table_basic_for_alter_100M drop PRIMARY KEY;
ERROR 1146 (HY000): no such table big_data_test.table_basic_for_alter_100m_copy_caf259f9-aaf7-11ee-8bc9-228384ec3c6c

### Expected Behavior

the table count should be the same as which is before altering

### Steps to Reproduce

```Markdown
1. create a table,such as tpch table without pk
2. load data into table
3. alter table add composite pk
```

**Comment by qingxinhome** [comment]
Dealing with other issues

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
PR has been raised in price, waiting for merge

**Comment by qingxinhome** [comment]
pr已经合并到1.1-dev和main，请验证测试,对于copy模式:
1亿数据，大约能在55s内返回
300万行数据，约能在15s内返回 @aressu1985 @sukki37 @daviszhen

**Comment by Ariznawlll** [comment]
<img width="1322" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e1e59b81-4293-447e-8809-3e0e38d91133">

Verified!
