### ISSUE TITLE
[Bug]: alter table add column failed by no such table xxxx.xxxxx_copy_1aeeb475-aafc-11ee-8bc9-228384ec3c6c on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14021]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a7f4972

### Other Environment Information

```Markdown
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4c 16G
- OS type:
- Others:
```

### Actual Behavior

mysql> load data url s3option {'endpoint'='cos.ap-guangzhou.myqcloud.com','access_key_id'='xxxxxxxxxxx','secret_access_key'='xxxxxxxxxx','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data.csv'} into table big_data_test.table_basic_for_alter_100M fields terminated by ',' lines terminated by '\n' parallel 'true';

Query OK, 100000000 rows affected (1 min 45.85 sec)

mysql> 
mysql> 
mysql> 
mysql> 
mysql> 
mysql> alter table big_data_test.table_basic_for_alter_100M add column ncl int after col1;

ERROR 1146 (HY000): no such table big_data_test.table_basic_for_alter_100m_copy_10a01f76-aafc-11ee-8bc9-228384ec3c6c
mysql> 
mysql> 
mysql> 
mysql> alter table big_data_test.table_basic_for_alter_100M add column ncl int after col1;
ERROR 1146 (HY000): no such table big_data_test.table_basic_for_alter_100m_copy_1aeeb475-aafc-11ee-8bc9-228384ec3c6c
mysql> alter table big_data_test.table_basic_for_alter_100M add column ncl int after col1;
ERROR 1146 (HY000): no such table big_data_test.table_basic_for_alter_100m_copy_1c5075df-aafc-11ee-8bc9-228384ec3c6c
mysql> 
mysql> 
mysql> alter table big_data_test.table_basic_for_alter_100M add column ncl int after col1;
ERROR 1146 (HY000): no such table big_data_test.table_basic_for_alter_100m_copy_2bf07dbc-aafc-11ee-8bc9-228384ec3c6c
mysql> 
mysql> alter table big_data_test.table_basic_for_load______100M add column ncl int after col1;
ERROR 1146 (HY000): no such table big_data_test.table_basic_for_load_100m_copy_03faba88-aaff-11ee-8bc9-228384ec3c6c

mo-log:
http://175.178.192.213:30088/explore?panes=%7B%22BdB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-a7f4972%5C%22%7D%20%7C%3D%20%60alter_100m_copy%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704367250747%22,%22to%22:%221704371547873%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

this operation should be successful

### Steps to Reproduce

```Markdown
1.create table 
create table  if not exists big_data_test.table_basic_for_alter_100M(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

2.load 100 million data to the table 
load data url s3option {'endpoint'='cos.ap-guangzhou.myqcloud.com','access_key_id'='**','secret_access_key'='**','bucket'='**', 'filepath'='mo-big-data/100000000_20_columns_load_data.csv'} into table big_data_test.table_basic_for_alter_100M fields terminated by ',' lines terminated by '\n' parallel 'true';

3.alter table big_data_test.table_basic_for_alter_100M add column ncl int after col1;
```

**Comment by qingxinhome** [comment]
Dealing with other issues

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
PR has been raised in price, waiting for merge

**Comment by qingxinhome** [comment]
pr已经合并，请验证测试,对于alter table 语句copy模式:
1亿数据，大约能在55s内返回
300万行数据，约能在15s内返回 @aressu1985 @sukki37 @daviszhen

**Comment by Ariznawlll** [comment]
<img width="719" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/4c52a026-a5c2-4a24-996e-935b5bff4592">

Verified!
