### ISSUE TITLE
[Bug]: [0105]Random points daily regression report 'internal error: get dispatch process by uuid failed, dispatch process has done'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14032]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7db9fe187d1d70a196961e3332919d92cf825ac9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7411209315/job/20183810372

<img width="1024" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2ad760f6-b8ed-4333-b2f2-81d7ae657036">

集群状态正常，没有oom：
<img width="879" alt="企业微信截图_53bf841f-0f82-4762-b542-437cec8edd48" src="https://github.com/matrixorigin/matrixone/assets/108530700/9c7f9d05-b074-4721-a535-560bf359bf1c">

log：http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240104%5C%22%7D%20%7C%3D%20%60get%20dispatch%20process%20by%20uuid%20failed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
daily regression on tke.
```

**Comment by m-schen** [comment]
pr已合并于main分支 / 1.1分支，可进行验证。

**Comment by Ariznawlll** [comment]
没再出现这个问题
