### ISSUE TITLE
[Bug]: insert into values duplicate key update 100threads mo crashed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14038]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4531180d4b20c179baa426cca179aaebc70cec84

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

原表数据量为1050万有主键，并发100，刚开始执行mo 挂掉了，但数据量为1050万无主键并发100测试mo正常
sql：insert into table_1000w(clo4) values({tbx}) on duplicate key update clo2=clo2/10;
<img width="1405" alt="企业微信截图_1167f74c-a532-441c-9ae2-9e015b05c4ef" src="https://github.com/matrixorigin/matrixone/assets/113406637/0de19e6f-6686-42d1-9628-457665b4764f">
<img width="797" alt="企业微信截图_9eda5e40-ee3d-4bd6-aa68-827da5cbfdac" src="https://github.com/matrixorigin/matrixone/assets/113406637/6af37446-3a49-4ca6-8480-05963459641a">

试了下创建简单的表，该sql执行成功
<img width="740" alt="企业微信截图_9b7a328c-13d4-431c-ba3a-d73f0ec08012" src="https://github.com/matrixorigin/matrixone/assets/113406637/3c73a131-846a-4f8d-9366-e50e8419d86f">

mo log：
<img width="1778" alt="企业微信截图_1306b80b-bad1-4129-a7e1-6ab99f594a36" src="https://github.com/matrixorigin/matrixone/assets/113406637/f34e0c23-0753-4191-ae0b-df0b5887a8a3">
[mo_log.tar.gz](https://github.com/matrixorigin/matrixone/files/13841278/mo_log.tar.gz)

### Steps to Reproduce

```Markdown
mo-load工具修改cases/ddl/run.yml文件下sql和vuser
sql: "insert into table_1000w(clo4) values({tbx}) on duplicate key update clo2=clo2/10;"
vuser: 100
执行./start.sh -c cases/ddl/

ddl:
create external table ex_table_1000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255))infile{"filepath"='/Users/heni/test_data/10000000_20_columns_load_data.csv'};
create table table_1000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255),primary key(clo4));
insert into table_1000w select * from ex_table_1000w;
```

**Comment by sukki37** [comment]
可能是oom

**Comment by ouyuanning** [comment]
1、似乎测试脚本有点问题。连接到MO会报这个错
```
{"level":"ERROR","time":"2024/01/03 14:52:16.668663 +0800","caller":"frontend/mysql_cmd_executor.go:315","msg":"error: SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 9 near \" $$\";","span":{"trace_id":"f33dd58e-cd53-8a52-58e4-f29d4991fc2c","span_id":"164f42c1b6b06b08"}}
```

2、但不知道为啥会引起服务器后来出错了。应该跟1关系不太大

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by ouyuanning** [comment]
才留意说的是on duplicate key 算子。
该算子会把数据一致保存在内存中，直到所有数据都被检验一遍，所以大数据量的时候很容易OOM。
得等spill完成后才不会OOM

**Comment by m-schen** [comment]
spill相关的工作均未开始

**Comment by m-schen** [comment]
休假中

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
暂无具体安排。

目前的计划是给某些算子增加process级别的mpool not enough的检测。避免crash的发生。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
与上一个评论相同。大概下礼拜会开始做这个工作。

**Comment by m-schen** [comment]
与上一个评论相同。大概下礼拜周二左右可以开始做这个工作。

**Comment by m-schen** [comment]
与上一个评论相同。目前还没法开始该工作，还在处理聚合重构对window函数的兼容。

**Comment by m-schen** [comment]
同上 请假中

**Comment by m-schen** [comment]
目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上一条评论，目前还在做聚合函数的事情中。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
刚结束其他工作，该任务暂无进度。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
未开展。

**Comment by m-schen** [comment]
还没空做这个

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
请假了

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
在改connection reset的s-1中

**Comment by m-schen** [comment]
无投入

**Comment by m-schen** [comment]
今天没跟踪这个问题。

**Comment by m-schen** [comment]
近期无法投入

**Comment by m-schen** [comment]
近期没有投入这个

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
与上一个回复相同。

**Comment by m-schen** [comment]
现在没空

**Comment by m-schen** [comment]
同上一个回复，近期无法投入。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
还在做pipeline的spool工作。

**Comment by m-schen** [comment]
还在忙spool的事情。

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
处理其他bug中

**Comment by m-schen** [comment]
spill还在做。

**Comment by m-schen** [comment]
spill还在做。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
spill还在做。

**Comment by m-schen** [comment]
与上一个评论相同，正在做spill。

**Comment by m-schen** [comment]
spill还在做，不过这几天没有进展，都在收尾2.0的bug.

**Comment by m-schen** [comment]
今天请假了

**Comment by m-schen** [comment]
等Join的spill再转送该issue。

**Comment by m-schen** [comment]
spill需要延期到2.1，2.0.1无法完成开发。

**Comment by m-schen** [comment]
no words.

**Comment by m-schen** [comment]
不确定具体是什么导致的oom, 2.1完成spill后再进行验证。

**Comment by m-schen** [comment]
同上一个评论

**Comment by m-schen** [comment]
与上一个评论相同。

**Comment by m-schen** [comment]
今天请假了

**Comment by m-schen** [comment]
在做别的事情中
