### ISSUE TITLE
[Bug]: Some of the current workspace code doesn't handle rc retry very well and needs to be fixed

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#14046]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.1-dev, 1.0-dev

### Commit ID

f66efc0f3b8228d88c9d7d884fe241adade6171c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

workspae is an implementation built on si, after adding rc retry, it needs to rollbackstatement, but there are the following cases where rollback may be problematic and need to be fixed
* The operation does not write to txn.writes   affect the rollback
* Rearrangements introduced because of insert/delete disorder have some interference with rollbacks

### Steps to Reproduce

```Markdown
1. run mo
2. try various hacks of rollbackstatement
```

**Comment by nnsgmsone** [comment]
第一个问题是由于错误的调整顺序的逻辑导致的，具体的情况大致如下：
 1. cn侧的insert/delete是乱序，然后dn无法处理乱序的输入，所以需要调整这个顺序，调整的逻辑是statement级别的
 2. cn目前存在很多内部查询的情况，一个sql可能会对应多个query(内部执行器），然后每个query都会导致这个顺序调整(这个调整是statement级别的)，这个逻辑是错的，调整应该是query级别的，每个query调整自己的即可
 3. 原先调整顺序的时候会修改statement在workspace内部的statement id和顺序，这是错误的，因为存在内部执行器的存在后，应该只需要调整顺序即可（把一个update的顺序强制规整为delete+insert)

**Comment by nnsgmsone** [comment]
第二个问题是由于cn写s3导致的，cn写s3的数据目前看代码是无法正确rollback statement的，因为各种操作并没有关联statement id，不过由于写s3的事务冲突会强制abort，所以目前不会导致问题，具体怎么改，还在看逻辑

**Comment by nnsgmsone** [comment]
已经提交pr，等待合入

**Comment by nnsgmsone** [comment]
已经提交pr，等待合入

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
