### ISSUE TITLE
[Bug]: [date 1.8] standalone regression: tpcc test reported panic  error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14068]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

335ccceb5c2c4fc036399097303f141014c0250b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263097168
<img width="1407" alt="企业微信截图_599cb79b-4cd8-4da8-a992-2ee0250b902a" src="https://github.com/matrixorigin/matrixone/assets/113406637/1b96b3f9-cfc8-43cd-9f1b-2d528a0d42aa">
2024-01-09 06:44:12 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 0, ErrorMessage : Parameter index out of bounds. 7 is not between valid values of 1 and 5
2024-01-09 06:44:12 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:861
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:135
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).GetPrepareParamsAt
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/process/types.go:418
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ParamExpressionExecutor).Eval
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:342
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*FunctionExpressionExecutor).Eval
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:483
github.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpressionOnce
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/evalExpression.go:250
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1116
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1106
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:594
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).generateNodes
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:3487
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1993
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1062
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:[90](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263249784#step:7:91)1
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3[91](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263249784#step:7:92)6
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4124
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-202311220[95](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263249784#step:7:96)211-6a25dc9[130](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263249784#step:7:131)ca/application.go:356
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650

mo log so big，plz call me

profile:
[profile (1).tar.gz](https://github.com/matrixorigin/matrixone/files/13868240/profile.1.tar.gz)

### Steps to Reproduce

```Markdown
standalone regression tpcc test
```

**Comment by heni02** [comment]
sysbench test also apear this problem
<img width="1439" alt="企业微信截图_bb310036-fd20-4833-b42a-f32e6aaa82ac" src="https://github.com/matrixorigin/matrixone/assets/113406637/3c718e29-29a1-42d4-af04-69df879fb741">

FATAL: mysql_drv_query() returned error 20101 (internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:861
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:1059
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFilters
	/data1/action-runner/_work/mo-nightly-regression/mo) for query '        SELECT count(k)
          FROM sbtest1
          WHERE k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255 OR k BETWEEN 61250 AND 61255'
FATAL: `thread_run' function failed: select_random_ranges.lua:76: SQL error, errno = 20101, state = 'HY000': internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:861
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/utils.go:[105](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263248574#step:23:106)9
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFilters
	/data1/action-runner/_work/mo-nightly-regression/mo

mo log：
[molog (2).tar.gz](https://github.com/matrixorigin/matrixone/files/13868299/molog.2.tar.gz)

profile:
[profile1.tar.gz](https://github.com/matrixorigin/matrixone/files/13868313/profile1.tar.gz)

**Comment by YANGGMM** [comment]
statement":"UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?","status":"fail","error":"internal error: panic runtime error: invalid memory address or nil pointer dereference:

**Comment by YANGGMM** [comment]
prepare __mo_stmt_id_36 from UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?","error":"internal error: panic runtime error: invalid memory address or nil pointer dereference:

**Comment by heni02** [comment]
和动哥一起定位发现，jdbc URL有rewriteBatchedStatements=true这个参数会导致这个错误，去掉后正常执行

**Comment by ouyuanning** [comment]
根本原因是：
1、jdbc先发了一个 set option的命令，以确认服务端是否支持 CLIENT_MULTI_RESULTS，  我们目前是返回支持
2、于是jdbc在 rewriteBatchedStatements=true 的情况下。针对update多笔记录进行了优化。会发送一个 prepare 语句多个statement的情况。类似这样：
```
UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;
UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;UPDATE bmsql_stock     SET s_quantity = ?, s_ytd = s_ytd + ?,         s_order_cnt = s_order_cnt + 1,         s_remote_cnt = s_remote_cnt + ?     WHERE s_w_id = ? AND s_i_id = ?;
```
多条语句放到一个 prepare 里。  而我们只支持一个prepare一个statement。 【MySQL其实也是】
于是在执行第二个statement的时候，被当做普通的update语句，而不是prepare语句，于是报错（获取prepare语句和execute语句才有的属性，而普通sql执行期是没有的，于是报空指针错误】

**Comment by ouyuanning** [comment]
main分支已经好了。我测了一下打开 rewriteBatchedStatements=true 下的10仓10线程，跑3分钟没有panic了。

如果1.1-dev也要处理的话，要先cherry pick https://github.com/matrixorigin/matrixone/pull/14047  这个PR过去，然后再cherry pick https://github.com/matrixorigin/matrixone/pull/14112  这个过去就好了。

**Comment by heni02** [comment]
confirm,closed
1.1-dev commit:5d7bb0afcc5807fd5f3d3f73d4e4d971b64e097d
tpcc跑了3分钟，没有报错
<img width="1496" alt="企业微信截图_1ffef3ac-6710-4fb9-80c7-0f494a119700" src="https://github.com/matrixorigin/matrixone/assets/113406637/e8663552-3600-4c83-8f4e-57765992aa08">

main commit：32a05ab7000d1206a5c70aa036bf4a2d4f39e207
tpcc跑了5分钟，没有报错
<img width="902" alt="企业微信截图_976c459d-a4ae-4f0e-90a3-e388663cb6d7" src="https://github.com/matrixorigin/matrixone/assets/113406637/624cf792-c950-413c-949e-19d61034dace">
