### ISSUE TITLE
[Feature Request]: select min(a, b) from t group by x

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#14064]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
It is very useful in some analytics.

select x, min(a, b) from t group by x; 

which should return a relation with 3 cols, x, a, b.   x is the group by col, and a, b is the minimum of (a, b) in dictionary order.
```

### Describe the feature you'd like

select x, min(a, b) from t group by x; 

### Describe implementation you've considered

Possibly, we can reuse the row expression.   

select x, min(row(a, b)) from t group by x;

This way min still takes one input params.   Return a row.   And we need a row deconstruct function index(row, 1) which will return a of the row.

**Comment by fengttt** [comment]
Related to #12643

**Comment by fengttt** [comment]
If we are implementing the row syntax, we can use the tuple pack/unpack function to pack and unpack row.

**Comment by arjunsk** [comment]
## From vs To
So we want to convert
```sql
SELECT `__mo_index_entries_tbl`.`__mo_index_centroid_version_fk`,
       `__mo_index_entries_tbl`.`__mo_index_centroid_id_fk`,
       `__mo_index_entries_tbl`.`__mo_index_table_pk`
FROM   (
                  SELECT     `centroids_tbl`.`__mo_index_centroid_version`                                                                                                                                                      AS `__mo_index_centroid_version_fk`,
                             `centroids_tbl`.`__mo_index_centroid_id`                                                                                                                                                           AS `__mo_index_centroid_id_fk`,
                             `7b_input_embedding_per_head`.`__mo_fake_pk_col`                                                                                                                                                   AS `__mo_index_table_pk`,
                             row_number() OVER (partition BY `7b_input_embedding_per_head`.`__mo_fake_pk_col` ORDER BY l2_distance(`centroids_tbl`.`__mo_index_centroid`, normalize_l2(7b_input_embedding_per_head.embedding))) AS `__mo_index_rn`
                  FROM       7b_input_embedding_per_head CROSS join  `centroids_tbl` 
  	   ) `__mo_index_entries_tbl` WHERE  `__mo_index_entries_tbl`.`__mo_index_rn` = 1;
```

to 

```sql
select
	centroids_tbl.`__mo_index_centroid_version`,
	unpair( min( pair(l2_distance(`centroids_tbl`.`__mo_index_centroid`, `tbl`.embedding), centroids_tbl.`__mo_index_centroid_id`)), 1),
	tbl.id
from
tbl cross join centroids_tbl
group by tbl.id;
```

## Few questions
1. comparing `tbl.embedding` is not recommended, as it can be costly to compare vectors.
2. do we already have a pair or row function? If not, will `pair` be a new type like `T_decimal64` or `T_enum`? 
3. Will the compare function be dynamically calculated based on the pair types? or we define all pair types and their cases beforehand?
4. we can have an unpair(pair, idx) to get the value in the pair_idx.

CC: @fengttt

**Comment by fengttt** [comment]
We already have tuple.    so tuple(a, b, c) ...  can just return bytes.    tuple_unpack(bytes, 'int, float, string', 1) should return a.   

We need the schema in order to unpack.     I don't think we can return multiple values from a function, if we can, it would be nice that tuple_unpack(bytes, 'int, float, string') to return a, b, c,

But if we do allow a function to return multiple values, maybe we just use agg function, min(a, b) to return a, b.

I do think tuple and tuple_unpack are very useful functions.    Even just for debugging our secondary index ...

**Comment by dengn** [comment]
Is is only for min, or do we need max too? @fengttt

**Comment by arjunsk** [comment]
Hi @dengn ,
I have a few questions regarding `min on pairs`. What is the expected output of 

1. 
```sql
mysql> select * from t2;
+-------+------+
| name  | age  |
+-------+------+
| Abby  |   24 |
| NULL  |   21 | <--
| Carol |   23 |
| Alex  |   23 |
+-------+------+

mysql> select  min( pair(name, age) ) from t1;

Is it <NULL, 21>?

```

2.
```sql
mysql> SELECT * FROM t2;
+-------+------+
| name  | age  |
+-------+------+
| Abby  |   24 |
| NULL  |   25 | <--
| Carol |   23 |
| Alex  |   23 |
+-------+------+

mysql> select  min( pair(name, age) ) from t1;
Is it <Abby,24> ?

```

**Comment by arjunsk** [comment]
> Is is only for min, or do we need max too? @fengttt

@dengn , `max` will also be supported.

**Comment by arjunsk** [comment]
The PR is merged into the master. 
https://github.com/matrixorigin/matrixone/pull/14167

Kindly test this.

**Comment by arjunsk** [comment]
Adding the document for Serial() and Serial_Full()

【企微文档】SERIAL OPS
https://doc.weixin.qq.com/doc/w3_AawAhAZmAIkC0aKXuPYRrWNPcqutE?scode=AJsA6gc3AA8YTX50SiAawAhAZmAIk


CC: @yangj1211, @Ariznawlll

**Comment by aressu1985** [comment]
DONE
