### ISSUE TITLE
[Bug]: [date 1.8] standalone regression:panic runtime error index out of range [0] with length 0

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14070]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

335ccceb5c2c4fc036399097303f141014c0250b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7448524925/job/20263248574
<img width="1396" alt="企业微信截图_6b8da132-8c1e-4560-9e99-3f353ae6444c" src="https://github.com/matrixorigin/matrixone/assets/113406637/3f144ded-6f7c-42c5-8c63-f843f951e85c">

mo log so big,plz call me
profile:
[o_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13868513/o_profile.tar.gz)

### Steps to Reproduce

```Markdown
standalone regression tpcc test
```

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2024/01/09 06:44:12.452927 +0800","caller":"compile/compile.go:225","msg":"error: internal error: panic runtime error: index out of range [0] with length 0: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:114\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.constructValueScanBatch\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1006\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1042\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1358\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:901\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3916\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4138\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650","span":{"trace_id":"8587236e-1b61-a066-dfd0-092e1b3068be","span_id":"b50288d64af939ba"}}
{"level":"ERROR","time":"2024/01/09 06:44:12.453015 +0800","name":"log-service.pipeline","caller":"compile/compile.go:226","msg":"panic in compile","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","sql":"execute __mo_stmt_id_19","error":"internal error: panic runtime error: index out of range [0] with length 0: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:114\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.constructValueScanBatch\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1006\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1042\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1080\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1358\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1498\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:1610\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:901\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:586\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:267\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/computation_wrapper.go:383\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3303\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3916\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4138\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:285\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:522\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}

**Comment by ouyuanning** [comment]
感觉类似 https://github.com/matrixorigin/matrixone/issues/14068  的问题。
杨磊可以先一起看看。

**Comment by heni02** [comment]
和动哥一起定位发现，jdbc URL有rewriteBatchedStatements=true这个参数会导致这个错误，去掉后正常执行

**Comment by ouyuanning** [comment]
main分支已经好了。我测了一下打开 rewriteBatchedStatements=true 下的10仓10线程，跑3分钟没有panic了。

如果1.1-dev也要处理的话，要先cherry pick https://github.com/matrixorigin/matrixone/pull/14047  这个PR过去，然后再cherry pick https://github.com/matrixorigin/matrixone/pull/14112  这个过去就好了。

**Comment by YANGGMM** [comment]
> main分支已经好了。我测了一下打开 rewriteBatchedStatements=true 下的10仓10线程，跑3分钟没有panic了。
> 
> 如果1.1-dev也要处理的话，要先cherry pick #14047 这个PR过去，然后再cherry pick #14112 这个过去就好了。

#14047 已经提到1.1-dev了

**Comment by heni02** [comment]
confirm,closed
1.1-dev commit:5d7bb0afcc5807fd5f3d3f73d4e4d971b64e097d
跑了3分钟，没有报错
<img width="1496" alt="企业微信截图_1ffef3ac-6710-4fb9-80c7-0f494a119700" src="https://github.com/matrixorigin/matrixone/assets/113406637/e8663552-3600-4c83-8f4e-57765992aa08">

main commit：32a05ab7000d1206a5c70aa036bf4a2d4f39e207
跑了5分钟，没有报错
<img width="902" alt="企业微信截图_976c459d-a4ae-4f0e-90a3-e388663cb6d7" src="https://github.com/matrixorigin/matrixone/assets/113406637/624cf792-c950-413c-949e-19d61034dace">
