### ISSUE TITLE
[Bug]: CN write s3 object with wrong sort index

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#14087]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

045dfa53f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

for table ssb_1.part, the sortIdx in cn s3writer should 10 (`__mo_cbkey_006p_mfgr010p_category007p_brand`) rather than 9 (`__mo_fake_pk_col`)

### Steps to Reproduce

```Markdown
git clone git@github.com:matrixorigin/mo-ssb.git

./run.sh -g -s 1 #generate data
./run.sh -c -s 1 #create table
./run.sh -l -s 1 #load data (including the part table)
```
```


### Additional information

_No response_

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
经过验证对比，该问题已经解决，请验证测试， @aptend @sukki37 @daviszhen
