### ISSUE TITLE
[Bug]: the compact-duration configuration parameter is not correctly passed to MatrixCube

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#1409]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): latest on main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the compact-duration configuration parameter is an empty value when compact-duration is set in the configuration file. 

### Expected Behavior

the value of compact-duration configuration parameter can be correctly passed to MatrixCube.

**Comment by daviszhen** [comment]
fixed in #1412
