### ISSUE TITLE
[Bug]: [date 1.9]tke regression: sysbench test panic error invalid memory address or nil pointer  apply_indices.go

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14095]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b72bea5f6

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7462446702/job/20305164032
<img width="1416" alt="企业微信截图_c96b621e-9519-48a1-bda6-d17830b68c0c" src="https://github.com/matrixorigin/matrixone/assets/113406637/d8935754-0ff8-4c5a-929e-5c01021d474a">
FATAL: mysql_drv_query() returned error 20101 (internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:861
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/utils.go:1059
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).applyIndicesForFilters
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/apply_indices.go:362
github.co) for query '        SELECT count(k)
          FROM sbtest1
          WHERE k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055 OR k BETWEEN 80050 AND 80055'

这个表结构会创建索引，怀疑和这个pr有关
<img width="1315" alt="企业微信截图_87f7166a-3dbd-4e3a-950a-ba4ec505a606" src="https://github.com/matrixorigin/matrixone/assets/113406637/220956c0-c03d-41c0-a254-add2ab6154cf">

mo log：
http://175.178.192.213:30088/explore?panes=%7B%22Sty%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240109%5C%22%7D%20%7C%3D%20%60invalid%20memory%20address%20or%20nil%20pointer%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench random range 100threads
```

**Comment by aunjgr** [comment]
PR merged

**Comment by heni02** [comment]
confirm，closed
commit：69b5272d62155ab3e1bbc5b0351b187591bbad55
job： https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7513052876/job/20459685914
<img width="1424" alt="企业微信截图_7f3c8f62-36cb-4c22-8bf2-a1be9d704799" src="https://github.com/matrixorigin/matrixone/assets/113406637/4d8bdb39-9a50-4a8e-860d-c9e6aa8144c3">
