### ISSUE TITLE
[Bug]: Inaccuracies and Data Loss in FileService Metrics

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14099]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.1-dev,1.0-dev

### Commit ID

2ab90ff

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

http://47.96.110.240/d/b1372f2d-8a6b-43a3-b117-71e2e753636a/fileservice-metrics?orgId=1&refresh=30s

<img width="1333" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/d162b1ec-1302-4849-8604-c966c0595ca5">

### Steps to Reproduce

```Markdown
open the link
```

**Comment by zhangxu19830126** [comment]
fixed by [#13385](https://github.com/matrixorigin/matrixone/pull/13385)
