### ISSUE TITLE
[Bug]: Incorrect explain in bvt with race enabled

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14108]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

e669184

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7472621706/job/20335592622
[multi-cn-e2e-with-race-linux-x86-reports (1).zip](https://github.com/matrixorigin/matrixone/files/13886205/multi-cn-e2e-with-race-linux-x86-reports.1.zip)

<img width="1424" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/c0da570a-9995-473a-8ed9-26f08ecb52ed">

### Steps to Reproduce

```Markdown
1. cd matrixone
2. make debug
3. start mo-service
4. run bvt
```

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7472232559/job/20334954636

**Comment by badboynt1** [comment]
fixed
