### ISSUE TITLE
[feature]: add config to disable default s3/aliyun credentials

### ISSUE THREAD

**Issue by xuoutput** [matrixorigin/matrixone#14113]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.0

### Commit ID

3ac9acb8d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/MO-Cloud/issues/2269

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/MO-Cloud/issues/2269
```

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
不填就用默认的，这是特性
所以改一下标题

**Comment by reusee** [comment]
pr merged

**Comment by reusee** [comment]
等合并到 1.1

**Comment by reusee** [comment]
working on other issues

**Comment by reusee** [comment]
added.

setting environment variable MO_NO_DEFAULT_CREDENTIALS to a non-empty value will disable default credentials

**Comment by Ariznawlll** [comment]
乐声哥，麻烦贴一下自测结果，谢谢啦 @reusee

**Comment by Ariznawlll** [comment]
<img width="317" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c1a160dd-769a-400d-9998-25e8857f309b">

**qa环境，commit：afb4934ae**
不完整的ak和sk:
<img width="1902" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/412f3613-3202-487c-a2f1-4c394fd96efc">

完整的ak和sk：
<img width="1904" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fc45541f-e8a7-4a33-8a04-3d8af686ecbd">

**Comment by xuoutput** [comment]
1
