### ISSUE TITLE
[Bug]: `invalid file path` occurred during sysbench/tpcc

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14114]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

https://github.com/matrixorigin/matrixone/commit/d8094c46d0633212e61bf0137a74ed64927ccbd9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

http://175.178.192.213:30088/explore?panes=%7B%22i9d%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-14090%5C%22%7D%20%7C%3D%20%60xxxx%20invlaid%20pat%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704883040058%22,%22to%22:%221704883195454%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="896" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/b93b1a2f-8203-4ee7-bcbb-e9ec55e8491e">

### Steps to Reproduce

```Markdown
run tpcc/sysbench
```

**Comment by triump2020** [comment]
@sukki37  fixed!

**Comment by aressu1985** [comment]
fixed
