### ISSUE TITLE
[Bug]:ci ut  TestNewObjectWriter report memory leak

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#14128]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

65deed0f6d88630af55da4c6e939c47fb35c429d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:


first，I found it in ci.

then I reproduced it in on mac.
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/3a608873-e129-449c-9c2f-6b9292dbc4eb)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/040fe89d-5f35-44d1-8ebc-ac12b1c11932)

### Expected Behavior

may be no memory leak under trace condition

### Steps to Reproduce
![image](https://github.com/matrixorigin/matrixone/assets/60595215/040fe89d-5f35-44d1-8ebc-ac12b1c11932)
```Markdown

```

**Comment by daviszhen** [comment]
happened with race option

**Comment by LeftHandCold** [comment]
暂时在做backup的开发

**Comment by LeftHandCold** [comment]
暂时在做backup的开发

**Comment by LeftHandCold** [comment]
暂时在做backup的开发

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
在做 snapshot和gc的开发

**Comment by LeftHandCold** [comment]
在做 snapshot和gc的开发

**Comment by LeftHandCold** [comment]
same as https://github.com/matrixorigin/matrixone/issues/14085
