### ISSUE TITLE
[Bug]: concurrent map writes

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#14138]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.0-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/2995754/5f38e211-ecbf-4967-a1ec-9e8201150583)

### Steps to Reproduce

```Markdown
1. source data
2. update news_detail set province = null where province not in ('上海市','云南省','内蒙古自治区','北京市','台湾省','吉林省','四川省','天津市','宁夏回族自治区','安徽省','山东省','山西省','广东省','广西壮族自治区','新疆维吾尔自治区','江苏省','江西省','河北省','河南省','浙江省','海南省','湖北省','湖南省','澳门特别行政区','甘肃省','福建省','西藏自治区','贵州省','辽宁省','重庆市','陕西省','青海省','香港特别行政区','黑龙江省');
```

**Comment by gouhongshen** [comment]
found another panic error when repro: #14185

**Comment by XuPeng-SH** [comment]
fixed

**Comment by aronchanisme** [comment]
https://github.com/matrixorigin/matrixone/issues/14139#issuecomment-1907480121
