### ISSUE TITLE
[Bug]: lots of error: "can not connect to remote backend" during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14148]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9d120d4

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, there lots of error "stream closed" for tpch/tpch/sysbench queries.
ErrorTime : 2024-01-12 01:30:42
RequestTime : 2024-01-12 01:30:42.015
TxnName : update_pk
Statement : UPDATE sbtest5 SET k=k+100 WHERE id = 11528;
ErrorCode : 20505
ErrorMessage : can not connect to remote backend
Expected : false

2024-01-12 01:30:42 ERROR TransExecutor:129 -
ErrorTime : 2024-01-12 01:30:42
RequestTime : 2024-01-12 01:30:42.092
TxnName : insert_delete
Statement : insert into sbtest7 values(393351,4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');
ErrorCode : 20505
ErrorMessage : can not connect to remote backend
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
Expected : false

2024-01-12 01:30:42 ERROR TransExecutor:129 -
ErrorTime : 2024-01-12 01:30:42
RequestTime : 2024-01-12 01:30:42.111
TxnName : insert_delete
Statement : insert into sbtest7 values(391195,4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');
ErrorCode : 20505
ErrorMessage : can not connect to remote backend

but there were no cns crashed in this period.

mo-log:
http://192.168.240.6:20001/explore?panes=%7B%22HqB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240112%5C%22%7D%20%7C%3D%20%60can%20not%20connect%20to%20remote%20backend%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705008707118%22,%22to%22:%221705017102527%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by XuPeng-SH** [comment]
@volgariver6 please take a look at this issue

**Comment by volgariver6** [comment]
初步定位到的原因是cn连接另一个cn的pipeline service的时候超时了，最后因为无法建立连接返回了错误。

明天继续看一下其他cn上的日志，分析原因。

**Comment by volgariver6** [comment]
### 日志异常
这段时间几乎每隔1分钟打印一次goroutine：

<img width="1294" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/b0bba93f-42b2-4eaf-aabd-276b2ea8f628">

<img width="1059" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/dbc467f3-6c4c-45df-a9dc-79417e04f364">

http://192.168.240.6:20001/explore?panes=%7B%22HqB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240112%5C%22%7D%20%21%3D%20%60can%20not%20find%20table%20by%20id%202%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221705016936683%22,%22to%22:%221705016955986%22%7D%7D%7D&schemaVersion=1&orgId=1

### 问题分析

应该是发生事务泄漏了：

http://192.168.240.6:20001/explore?panes=%7B%22HqB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240112%5C%22%7D%20%21%3D%20%60can%20not%20find%20table%20by%20id%202%60%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221705016421000%22,%22to%22:%221705017564000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="730" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/61145acc-3009-4c1b-b53e-6e1b76414cbf">

**Comment by volgariver6** [comment]
@daviszhen will help on it.

**Comment by DanielZhangQD** [comment]
目前 Cloud QA 频繁出现，参考 https://github.com/matrixorigin/MO-Cloud/issues/2362

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by volgariver6** [comment]
根本原因是检测到事务泄漏，调用profile.ProfileGoroutines() 输出所有的goroutines，此时会stw，导致整个集群都不可用了。

@daviszhen 会加一些逻辑排除某些情况再跑跑看

**Comment by volgariver6** [comment]
等待再出现

**Comment by volgariver6** [comment]
等待再出现

**Comment by volgariver6** [comment]
等待再出现

**Comment by volgariver6** [comment]
很久没有出现了，建议先关掉 @aressu1985

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展
