### ISSUE TITLE
[Bug]: "msg":"BUG: unlock a lock that is not held by the current txn" FATAL during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14146]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9d120d4

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, the can creash serval times by fatal:
{"level":"FATAL","time":"2024/01/11 23:58:12.387165 +0000","name":"cn-service.lockservice","caller":"lockservice/lock_table_local.go:218","msg":"BUG: unlock a lock that is not held by the current txn","uuid":"62373536-3264-3561-3633-643638376165","row":true,"keys-count":1,"hold-bind":"9223372045450710401-170501175128071871662373536-3264-3561-3633-643638376165-12","bind":"9223372045450710401-170501175128071871662373536-3264-3561-3633-643638376165-12","holders":"[52e69dd253ec4c1ea5c25b6a7d5e425d(170501175128071871662373536-3264-3561-3633-643638376165)]","txn":"75535e736e804ba587218a63b0bf26da()","stacktrace":"github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock.func2\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:218\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlice).iter\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/slice.go:159\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:201\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close.func1.1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/txn.go:152\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/txn.go:163\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*service).Unlock\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:179\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).unlock\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:971\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Rollback\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:503\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).RollbackTxn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:403\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Session).TxnRollbackSingleStatement\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:691\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt.func3\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2817\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt.func5\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2861\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt.func7\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2888\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3610\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3902\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4069\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:242\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:519\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356"}

mo-log:
http://192.168.240.6:20001/explore?panes=%7B%22pVW%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240112%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705001240543%22,%22to%22:%221705019458970%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
fixed

**Comment by aressu1985** [comment]
repro on qa upgrade-test-1 evn:
test load:
1. tpcc_1/tpcc_10/tpcc_100 benchmark test
2. tpch 1G/10G/100G loop queries
3. sysbench mixed case long running test

instanace: 160da4d8_0a47_4b05_aa7d_c3d2439d1e50

mo-log:
<img width="1390" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/708a9726-3eb7-4d1a-91b3-1201a8a6b9de">


loki link:
http://47.98.35.103/explore?panes=%7B%221fu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22upgrade-test-1%5C%22%7D%20%7C%3D%20%60unlock%20a%20lock%20that%20is%20not%20held%20by%20t%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706350803000%22,%22to%22:%221706351403000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aressu1985** [comment]
repro on stability distributed test 01.28:
test load:

tpcc_10benchmark test
tpch 10G loop queries
sysbench mixed case long running test

when kill 2 cns， this appeared

mo log:
http://192.168.240.6:20001/explore?panes=%7B%22xwp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240127%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706410312936%22,%22to%22:%221706410431791%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
fixed.

**Comment by aressu1985** [comment]
fixed
