### ISSUE TITLE
[Bug]: too many open files error  in stability test on distributed mode and cause very slow

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14149]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9d120d4

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, there was a error in sysbench mixed error:
ErrorMessage : operation error S3: GetObject, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "http://minio.minio-mo.svc.cluster.local/mo-stability-test/test/data/148061a1-b0d8-11ee-a589-6268868f1d6a_00000?x-id=GetObject": dial tcp: lookup minio.minio-mo.svc.cluster.local: too many open files

lsof :
[lsof.txt.zip](https://github.com/matrixorigin/matrixone/files/13910713/lsof.txt.zip)

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
