### ISSUE TITLE
[Bug]: panic update 200w records

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#14140]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.0-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR 20101 (HY000): internal error: panic no data meta:
github.com/matrixorigin/matrixone/pkg/objectio.objectMetaV3.MustDataMeta
        /home/zhangxu/matrixone/pkg/objectio/metav3.go:60
github.com/matrixorigin/matrixone/pkg/objectio.objectMetaV3.MustGetMeta
        /home/zhangxu/matrixone/pkg/objectio/metav3.go:30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.LoadColumnsData
        /home/zhangxu/matrixone/pkg/vm/engine/tae/blockio/funcs.go:43
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.LoadColumns

### Steps to Reproduce

```Markdown
1. source data
2. update news_detail set province = null where province not in ('上海市','云南省','内蒙古自治区','北京市','台湾省','吉林省','四川省','天津市','宁夏回族自治区','安徽省','山东省','山西省','广东省','广西壮族自治区','新疆维吾尔自治区','江苏省','江西省','河北省','河南省','浙江省','海南省','湖北省','湖南省','澳门特别行政区','甘肃省','福建省','西藏自治区','贵州省','辽宁省','重庆市','陕西省','青海省','香港特别行政区','黑龙江省');
```

**Comment by LeftHandCold** [comment]
暂时在做backup的开发

**Comment by LeftHandCold** [comment]
暂时在做backup的开发

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by LeftHandCold** [comment]
无进展

**Comment by XuPeng-SH** [comment]
#11471

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/issues/11471

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/issues/11471

**Comment by LeftHandCold** [comment]
load block报错，1.0的checkpoint还是以block list为准，1.1.3已经取消了blocklist，1.2的checkpoint也修改过，后期应该不会再出现这种问题了，帮忙先关掉吧 @zhangxu19830126

**Comment by zhangxu19830126** [comment]
和 @LeftHandCold  讨论，后面版本不会出现了，因为格式都不一样了，先关闭
