### ISSUE TITLE
[Bug]: [date 1.11]tke regression: dn restart ,panic error  

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14151]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dd90efb5a7408aa0c82e54f320fc5e08eefa833b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
两个问题：
1.dn panic导致restart 
2.dn restart后一段时间内（2024-01-11 18:30:32 到2024-01-11 18:53:29）出现连接超时，创建db卡住等现象
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7490212917/job/20388537885
<img width="875" alt="企业微信截图_9d9505bf-0f29-4913-b0fd-29d72fff49f4" src="https://github.com/matrixorigin/matrixone/assets/113406637/6f8af1be-d36b-491c-ab98-8b163bdc23af">
<img width="1086" alt="企业微信截图_19ea8798-5e6b-49e4-9a10-9c4353bf4b58" src="https://github.com/matrixorigin/matrixone/assets/113406637/eff239a6-f7c4-4509-94ce-d1bb7deaaa6e">
<img width="1085" alt="企业微信截图_27929c36-80ce-47bd-9d76-35cde04ef981" src="https://github.com/matrixorigin/matrixone/assets/113406637/b51d0c7b-e3c2-4354-a89e-61fd4728db31">

log:
<img width="1291" alt="企业微信截图_8390dc99-ba7f-431b-b66c-181927ab79ed" src="https://github.com/matrixorigin/matrixone/assets/113406637/03a30d7b-cee0-4555-be99-3945a37a5e14">
<img width="1260" alt="企业微信截图_6ebb2f09-e762-4fa2-8ed1-66cdeead37a6" src="https://github.com/matrixorigin/matrixone/assets/113406637/715c581b-0ff5-4fb1-a57b-ae124325a602">

http://175.178.192.213:30088/explore?panes=%7B%22qYx%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240111%5C%22,%20pod%3D%5C%22nightly-regression-dis-dn-0%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704997800000%22,%22to%22:%221704997860000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc test
```

**Comment by heni02** [comment]
@LeftHandCold 麻烦将定位信息贴一下

**Comment by LeftHandCold** [comment]
当时dn出现的段错误，类似https://github.com/matrixorigin/matrixone/issues/14100

**Comment by LeftHandCold** [comment]
<img width="1261" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/17545537-f45e-4206-b7e2-12c3257d6c9d">

**Comment by nnsgmsone** [comment]
等待复现core dump

**Comment by nnsgmsone** [comment]
等待复现的core dump

**Comment by volgariver6** [comment]
等 @heni02 复现出 core 文件

**Comment by volgariver6** [comment]
还没有进展，等待core文件

**Comment by heni02** [comment]
现在main不能复现该问题，先降级，等复现再定位

**Comment by volgariver6** [comment]
还没有复现

**Comment by volgariver6** [comment]
还是没有复现，先转回测试，复现了再解决。

**Comment by heni02** [comment]
该问题后续长时间再没复现，先关掉，再出现新提单跟踪

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8127223834/job/22213669625

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8092107745/job/22126836876

**Comment by LeftHandCold** [comment]
<img width="1347" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/606baabb-6254-48c6-932f-73c9004302b5">
<img width="1375" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/9c3ec4c5-6aa3-4bb0-85dd-c9e0f7721c5c">
在go的repo中找到了相同的issue。
看起来像unsafe 导致的问题。

**Comment by XuPeng-SH** [comment]
wait repro in stability env

**Comment by XuPeng-SH** [comment]
wait repro in stability env

**Comment by XuPeng-SH** [comment]
wait repro in stability env

**Comment by XuPeng-SH** [comment]
wait repro in stability env

**Comment by XuPeng-SH** [comment]
wait repro in stability env

**Comment by XuPeng-SH** [comment]
segmentation error in hyperloglog

**Comment by XuPeng-SH** [comment]
same with #15288

**Comment by heni02** [comment]
回归测试先观察几天看看

**Comment by heni02** [comment]
最近回归没有出现dn重启的问题，先关闭
