### ISSUE TITLE
[Bug]: [date 1.11]tke regression: cn restart, panic error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14155]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dd90efb5a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="826" alt="企业微信截图_96d7261a-e72e-48f8-b9bb-7569fe53a925" src="https://github.com/matrixorigin/matrixone/assets/113406637/1c52a395-cc2e-4bdb-a78f-e0657298f6e2">

log:
<img width="1324" alt="企业微信截图_038904ae-4be9-408b-90fb-17a895ebba30" src="https://github.com/matrixorigin/matrixone/assets/113406637/8a265bc1-dc14-495f-afc3-eff4bcec9a1c">
http://175.178.192.213:30088/explore?panes=%7B%22qYx%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240111%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-kkppt%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704992220000%22,%22to%22:%221704992280000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression
```

**Comment by iamlinjunhong** [comment]
代码上看着是 bitmap 修改问题

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm，closed
commit：ff5e808a4650f2d21937838016eb18ae837fdf00
