### ISSUE TITLE
[Bug]: tpcc stability test report 'Duplicate entry '3a15013a15033a160d66' for key '__mo_cpkey_col'' on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14160]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9d120d4

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, there some error "Duplicate entry '3a15013a15033a160d66' for key '__mo_cpkey_col'" for tpcc test.

tpcc-longrunning-test/mo-tpcc/benchmarksql-info.log:2023-12-20 14:03:33 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '3a15013a15013a161336' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/benchmarksql-info.log:2023-12-22 03:49:56 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '(1,1,7575,1)' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/benchmarksql-info.log:2023-12-22 03:49:56 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '(1,1,7575)' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/tpcc.log:2023-12-22 03:49:56 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '(1,1,7575,1)' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/tpcc.log:2023-12-22 03:49:56 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '(1,1,7575)' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/benchmarksql-error-1-10.log:2023-12-20 14:03:33 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '3a15013a15013a161336' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/benchmarksql-error-1-10.log:2023-12-22 03:49:56 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '(1,1,7575,1)' for key '__mo_cpkey_col'
tpcc-longrunning-test/mo-tpcc/benchmarksql-error-1-10.log:2023-12-22 03:49:56 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 1062, ErrorMessage : Duplicate entry '(1,1,7575)' for key '__mo_cpkey_col'

mo-log:

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by XuPeng-SH** [comment]
@nnsgmsone please take a look at this issue

**Comment by nnsgmsone** [comment]
给我一下日志 @aressu1985

**Comment by aressu1985** [comment]
mo-log:
http://10.222.6.1/explore?panes=%7B%22Aoi%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240112%5C%22%7D%20%7C%3D%20%603a15013a15033a160d66%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221704992471641%22,%22to%22:%221704998829377%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by nnsgmsone** [comment]
对于dup的情况，接下来我会制造一个埋点来强制core dump来dump整个mo的快照。具体如何dump需要稍微设计一下。。

**Comment by nnsgmsone** [comment]
还在忙生产的bug，尚未处理

**Comment by nnsgmsone** [comment]
正在设计和实现中

**Comment by nnsgmsone** [comment]
正在设计和实现中

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
处理数据正确性问题中

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by triump2020** [comment]
已经Fix 了一部分

**Comment by triump2020** [comment]
分布式稳定性测试中，还会出现dup/ww, 正在定位

**Comment by triump2020** [comment]
Blocked by snapshot read.

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15545

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15731

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15948

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992 fixed dup/ww bug.

**Comment by triump2020** [comment]
wait for @ouyuanning 's pr

**Comment by triump2020** [comment]
wait for @ouyuanning 's pr

**Comment by triump2020** [comment]
Wait for @ouyuanning ’PR

**Comment by triump2020** [comment]
In testing

**Comment by triump2020** [comment]
等 @ouyuanning ' PR 复现之后，继续查

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
正在加日志，查看 tke-dup 问题.

**Comment by triump2020** [comment]
单机的ww/dup 已定位到大致原因.

**Comment by triump2020** [comment]
It' s duplicate with #14880

**Comment by triump2020** [comment]
继续观察中

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
现在又其他问题单子跟踪，此问题单关闭
