### ISSUE TITLE
[Bug]: information_schema.columns中的table_catalog与schemata表中的catalog_name不对应

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixone#14169]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.0

### Commit ID

94a7724

### Other Environment Information

```Markdown
- OS type: CentOS 7.9
```

### Actual Behavior

在MO informaiton_schema.columns表中，table_schema为mo_catalog的库，对应的table_catalog为def。但是，在informaiton_schema.schemata中，schema_name为mo_catalog的库，对应的catalog_name为mo_catalog，如下图：

![3a9da8204ada5611beaea0ddbfaa132](https://github.com/matrixorigin/matrixone/assets/90299197/90a61135-a6eb-481c-bfc3-62c5f0c9e439)

这个问题导致在DataCab中表和列的元数据对应关系找不到，麻烦看是否方便优化。

### Steps to Reproduce

```Markdown
见上述描述。
```

**Comment by YANGGMM** [comment]
@aressu1985  麻烦测试一下

**Comment by aressu1985** [comment]
<img width="864" alt="image" src="https://github.com/user-attachments/assets/81688f49-6ff1-484b-96bb-371d32c466b0">
fixed
