### ISSUE TITLE
[Bug]:  K8s deployment matrixone cannot start

### ISSUE THREAD

**Issue by iwanlebron** [matrixorigin/matrixone#14172]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.0

### Commit ID

v1.1.0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: linux - amd64
- Others:
```

### Actual Behavior

[container-matrixone.log](https://github.com/matrixorigin/matrixone/files/13918229/container-matrixone.log)

### Steps to Reproduce

```Markdown
K8s deployment matrixone cannot start
```

**Comment by iwanlebron** [comment]
默认配置，只挂载了磁盘

**Comment by XuPeng-SH** [comment]
@aylei please take a look at this issue
