### ISSUE TITLE
[Bug]: [date 1.14]tke regression:sysbench test reported error use of closed network connection

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14187]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c6d251233

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7519815852/job/20468905639
<img width="1397" alt="企业微信截图_c5e5211e-bb2a-42b3-80a4-6ec76bde9b29" src="https://github.com/matrixorigin/matrixone/assets/113406637/033bce2c-cd34-4243-a301-1af8f6c77aa8">
tke env :
<img width="808" alt="企业微信截图_7fd7c56d-80c2-4d58-a6a7-645bf76c95fe" src="https://github.com/matrixorigin/matrixone/assets/113406637/47b7ea0f-5413-4556-89e3-2197bf5dd9ab">

loki：
日志中这个时间段大量报这个错误，是否预期，报这些错误后mo执行drop table或者creat table报错lock table bind changed
http://175.178.192.213:30088/explore?panes=%7B%22iIg%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240114%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705206284815%22,%22to%22:%221705292685815%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1344" alt="企业微信截图_a653c560-5638-4020-a514-a560833013d5" src="https://github.com/matrixorigin/matrixone/assets/113406637/cc1f46da-7861-4bda-b30c-559cfef1d65c">

### Steps to Reproduce

```Markdown
tke regression sysbench 1000w test
```

**Comment by ouyuanning** [comment]
增加了些日志，继续跑

**Comment by ouyuanning** [comment]
俊洪在这个 issue 处理中
https://github.com/matrixorigin/matrixone/issues/12708
这个先关闭吧

**Comment by heni02** [comment]
ok，closed
