### ISSUE TITLE
[Bug]: CN OOM

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14197]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

8081e0516

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN OOM, Refer to https://github.com/matrixorigin/MO-Cloud/issues/2326#issuecomment-1891615896

### Expected Behavior

No OOM occurs

### Steps to Reproduce

```Markdown
Refer to https://github.com/matrixorigin/MO-Cloud/issues/2326#issuecomment-1891615896
```

### Additional information

Log:
http://121.43.41.174/explore?panes=%7B%22y-p%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-01-sys%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705306800000%22,%22to%22:%221705307459000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by DanielZhangQD** [comment]
Profile:
http://121.43.41.174/explore?panes=%7B%22JBp%22:%7B%22datasource%22:%22d891fcb8-dfd4-479f-a1b4-2447a695b682%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%3D%5C%22normal-cn-bj2n9%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22d891fcb8-dfd4-479f-a1b4-2447a695b682%22%7D%7D%5D,%22range%22:%7B%22from%22:%221705307220000%22,%22to%22:%221705307339000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aunjgr** [comment]
json函数实现的问题。明天来详查

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
在解决中移物联的issue

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
on leave

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today
