### ISSUE TITLE
[Bug]: In explicit transactions, the result count is incorrect after insert

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#14198]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

a7f4972ddcb21e9b001c3898a31ac4d440cc9461

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table  if not exists big_data_test.table_basic_for_alter_100M( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3) );
Query OK, 0 rows affected (0.01 sec)

mysql> load data url s3option {'endpoint'='cos.ap-guangzhou.myqcloud.com','access_key_id'='xxxxxxx','secret_access_key'='xxxxxxxxx','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data.csv'} into table big_data_test.table_basic_for_alter_100M fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 100000000 rows affected (13 min 10.10 sec)

mysql> select count(*) from table_basic_for_alter_100m;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `big_data_test`.`table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30` (
    -> `col1` TINYINT ,
    -> `ncl` INT ,
    -> `col2` SMALLINT ,
    -> `col3` INT ,
    -> `col4` BIGINT ,
    -> `col5` TINYINT UNSIGNED ,
    -> `col6` SMALLINT UNSIGNED ,
    -> `col7` INT UNSIGNED ,
    -> `col8` BIGINT UNSIGNED ,
    -> `col9` FLOAT ,
    -> `col10` DOUBLE ,
    -> `col11` VARCHAR(255) ,
    -> `col12` DATE ,
    -> `col13` DATETIME ,
    -> `col14` TIMESTAMP ,
    -> `col15` BOOL ,
    -> `col16` DECIMAL(16,6) ,
    -> `col17` TEXT ,
    -> `col18` JSON ,
    -> `col19` BLOB ,
    -> `col20` BINARY(255) ,
    -> `col21` VARBINARY(255) ,
    -> `col22` VECF32(3) ,
    -> `col23` VECF32(3) ,
    -> `col24` VECF64(3) ,
    -> `col25` VECF64(3) 
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO `big_data_test`.`table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30` (`col15`, `col16`, `col17`, `col1`, `col2`, `col7`, `col12`, `col13`, `col20`, `col5`, `col18`, `col24`, `col25`, `col4`, `col10`, `col11`, `col21`, `col23`, `col19`, `col22`, `col3`, `col6`, `col8`, `col9`, `col14`) SELECT `col15`, `col16`, `col17`, `col1`, `col2`, `col7`, `col12`, `col13`, `col20`, `col5`, `col18`, `col24`, `col25`, `col4`, `col10`, `col11`, `col21`, `col23`, `col19`, `col22`, `col3`, `col6`, `col8`, `col9`, `col14` FROM `big_data_test`.`table_basic_for_alter_100m`;
Query OK, 100000000 rows affected (50.34 sec)

mysql> select count(*) from `table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30`;
+----------+
| count(*) |
+----------+
| 18874368 |
+----------+
1 row in set (0.01 sec)
 -- error: 这里返回的应该是100000000 

mysql> commit;
Query OK, 0 rows affected (0.18 sec)

mysql> select count(*) from `table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30`;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (0.13 sec)

### Expected Behavior

mysql> create table  if not exists big_data_test.table_basic_for_alter_100M( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3) );
Query OK, 0 rows affected (0.01 sec)

mysql> load data url s3option {'endpoint'='cos.ap-guangzhou.myqcloud.com','access_key_id'='xxxxxxxx','secret_access_key'='xxxxxxxxxx','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data.csv'} into table big_data_test.table_basic_for_alter_100M fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 100000000 rows affected (13 min 10.10 sec)

mysql> select count(*) from table_basic_for_alter_100m;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `big_data_test`.`table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30` (
    -> `col1` TINYINT ,
    -> `ncl` INT ,
    -> `col2` SMALLINT ,
    -> `col3` INT ,
    -> `col4` BIGINT ,
    -> `col5` TINYINT UNSIGNED ,
    -> `col6` SMALLINT UNSIGNED ,
    -> `col7` INT UNSIGNED ,
    -> `col8` BIGINT UNSIGNED ,
    -> `col9` FLOAT ,
    -> `col10` DOUBLE ,
    -> `col11` VARCHAR(255) ,
    -> `col12` DATE ,
    -> `col13` DATETIME ,
    -> `col14` TIMESTAMP ,
    -> `col15` BOOL ,
    -> `col16` DECIMAL(16,6) ,
    -> `col17` TEXT ,
    -> `col18` JSON ,
    -> `col19` BLOB ,
    -> `col20` BINARY(255) ,
    -> `col21` VARBINARY(255) ,
    -> `col22` VECF32(3) ,
    -> `col23` VECF32(3) ,
    -> `col24` VECF64(3) ,
    -> `col25` VECF64(3) 
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO `big_data_test`.`table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30` (`col15`, `col16`, `col17`, `col1`, `col2`, `col7`, `col12`, `col13`, `col20`, `col5`, `col18`, `col24`, `col25`, `col4`, `col10`, `col11`, `col21`, `col23`, `col19`, `col22`, `col3`, `col6`, `col8`, `col9`, `col14`) SELECT `col15`, `col16`, `col17`, `col1`, `col2`, `col7`, `col12`, `col13`, `col20`, `col5`, `col18`, `col24`, `col25`, `col4`, `col10`, `col11`, `col21`, `col23`, `col19`, `col22`, `col3`, `col6`, `col8`, `col9`, `col14` FROM `big_data_test`.`table_basic_for_alter_100m`;
Query OK, 100000000 rows affected (50.34 sec)

mysql> select count(*) from `table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30`;
+----------+
| count(*) |
+----------+
| 100000000 |
+----------+
1 row in set (0.01 sec)

mysql> commit;
Query OK, 0 rows affected (0.18 sec)

mysql> select count(*) from `table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30`;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (0.13 sec)

### Steps to Reproduce

```Markdown
mysql> create table  if not exists big_data_test.table_basic_for_alter_100M( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3) );
Query OK, 0 rows affected (0.01 sec)

mysql> load data url s3option {'endpoint'='cos.ap-guangzhou.myqcloud.com','access_key_id'='xxxxxxxxx','secret_access_key'='xxxxxxxxx','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data.csv'} into table big_data_test.table_basic_for_alter_100M fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 100000000 rows affected (13 min 10.10 sec)


mysql> select count(*) from table_basic_for_alter_100m;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (0.01 sec)


mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `big_data_test`.`table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30` (
    -> `col1` TINYINT ,
    -> `ncl` INT ,
    -> `col2` SMALLINT ,
    -> `col3` INT ,
    -> `col4` BIGINT ,
    -> `col5` TINYINT UNSIGNED ,
    -> `col6` SMALLINT UNSIGNED ,
    -> `col7` INT UNSIGNED ,
    -> `col8` BIGINT UNSIGNED ,
    -> `col9` FLOAT ,
    -> `col10` DOUBLE ,
    -> `col11` VARCHAR(255) ,
    -> `col12` DATE ,
    -> `col13` DATETIME ,
    -> `col14` TIMESTAMP ,
    -> `col15` BOOL ,
    -> `col16` DECIMAL(16,6) ,
    -> `col17` TEXT ,
    -> `col18` JSON ,
    -> `col19` BLOB ,
    -> `col20` BINARY(255) ,
    -> `col21` VARBINARY(255) ,
    -> `col22` VECF32(3) ,
    -> `col23` VECF32(3) ,
    -> `col24` VECF64(3) ,
    -> `col25` VECF64(3) 
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO `big_data_test`.`table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30` (`col15`, `col16`, `col17`, `col1`, `col2`, `col7`, `col12`, `col13`, `col20`, `col5`, `col18`, `col24`, `col25`, `col4`, `col10`, `col11`, `col21`, `col23`, `col19`, `col22`, `col3`, `col6`, `col8`, `col9`, `col14`) SELECT `col15`, `col16`, `col17`, `col1`, `col2`, `col7`, `col12`, `col13`, `col20`, `col5`, `col18`, `col24`, `col25`, `col4`, `col10`, `col11`, `col21`, `col23`, `col19`, `col22`, `col3`, `col6`, `col8`, `col9`, `col14` FROM `big_data_test`.`table_basic_for_alter_100m`;
Query OK, 100000000 rows affected (50.34 sec)

mysql> select count(*) from `table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30`;
+----------+
| count(*) |
+----------+
| 18874368 |
+----------+
1 row in set (0.01 sec)
 -- error: 这里返回的应该是100000000 


mysql> commit;
Query OK, 0 rows affected (0.18 sec)

mysql> select count(*) from `table_basic_for_alter_100m_copy_f011e651-b34c-11ee-b88d-000c29203f30`;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (0.13 sec)
```

**Comment by qingxinhome** [comment]
association：#14020， #14021

**Comment by LeftHandCold** [comment]
这个跟https://github.com/matrixorigin/matrixone/issues/14020 貌似一样吧，不用新建issue吧

**Comment by zengyan1** [comment]
还没看

**Comment by zengyan1** [comment]
正在看

**Comment by zengyan1** [comment]
目前定位到疑似在transaction中table scan的block有缺失

**Comment by zengyan1** [comment]
<img width="855" alt="企业微信20240129-142805@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/ccefc22c-6eac-407f-a8e9-fd67c200b386">

<img width="394" alt="企业微信20240129-142818@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/104c81ff-fb7a-42d3-a28b-e41a28619c38">

**Comment by zengyan1** [comment]
1.在一次手动事务中，将有1亿行数据的表insert到第二个表中，Query OK, 100000000 rows affected，成功写入1亿行
2.第二个表的count(*)只有250万，再将该表数据insert到第三个表中，没有发生再次丢失
3.commit后第二个表count(*)恢复正常，第三个表没有变化
猜测：在transaction中写的部分block在commit之前无法被感知到。

**Comment by zengyan1** [comment]
该问题在insert的时候还有可能引发https://github.com/matrixorigin/matrixone/issues/14282

**Comment by triump2020** [comment]
大致发现问题了，我会提个pr

**Comment by triump2020** [comment]
@qingxinhome  fixed , test pls.

**Comment by aressu1985** [comment]
测试通过，问题关闭
