### ISSUE TITLE
[Bug]: disk gc may be disturbed when loading stale object stats

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#14205]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.1-dev

### Commit ID

7d9ca8fbd14c3f8019e15661acaaa6e2570d5d70

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

disk gc may be disturbed when loading stale object stats

### Expected Behavior

1. avoid loading stale object stats
2. logging error message
3. add warning metric
4. add UT

### Steps to Reproduce

```Markdown
make some checkpoints in 1.0
upgrade to 1.1
```

**Comment by LeftHandCold** [comment]
fixed
