### ISSUE TITLE
[Bug]: 删除数据库,mo_catalog.mo_user_defined_function里面该数据库下udf的记录没有被删掉

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/matrixone#14239]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6581

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="714" alt="企业微信截图_6d8a9e8d-5601-4d64-8e8e-13ebc9177e3c" src="https://github.com/matrixorigin/matrixone/assets/153493538/25d02c74-8908-4c90-bb9c-7ef8263e37ab">

### Expected Behavior

删除数据库后，该数据库下创建的udf应该从mo_catalog.mo_user_defined_function中删除

### Steps to Reproduce

```Markdown
create database db1;
create database db2;
use db1;
create function helloworld () returns int language sql as 'select id from tbl1 limit 1';
use db2;
drop function helloworld();
show function status;
```

**Comment by YANGGMM** [comment]
fixed， plz test @yangj1211

**Comment by heni02** [comment]
bvt case已添加，closed
<img width="1420" alt="企业微信截图_226ec22e-4cb0-4e96-b855-def5c0e0da05" src="https://github.com/matrixorigin/matrixone/assets/113406637/864ca5dc-f9c5-4df6-bc4a-04faca52c63f">
