### ISSUE TITLE
[Bug]:创建函数带数据库名：" create function db.function_name xxx"，如果数据库不存在也会创建成功

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/matrixone#14240]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="808" alt="企业微信截图_3113eb75-fbf1-4a19-ad41-0f2a3afd1ba2" src="https://github.com/matrixorigin/matrixone/assets/153493538/9418eef8-6686-41e0-ab31-1debaa7ad755">

### Steps to Reproduce

```Markdown
数据库db1不存在的情况下执行：
create function db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
```

**Comment by YANGGMM** [comment]
等pr合进去

**Comment by YANGGMM** [comment]
fixed @yangj1211

**Comment by heni02** [comment]
bvt case已添加，closed
<img width="1398" alt="企业微信截图_84b0f25c-952d-4064-9291-eeb842c013b9" src="https://github.com/matrixorigin/matrixone/assets/113406637/29004af6-2d7b-4e86-b8e4-96f640c5a5ba">
