### ISSUE TITLE
[Bug]: performance: There is a huge decrease of sysbench read_only qps from 5000+ to 19

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14254]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ede2a2686

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

read_only qps 从图中看到目前性能基本降接近于0，初步发现从1.8号到1.10号qps有巨幅的下降
<img width="698" alt="企业微信截图_6444c50c-7582-4c80-bf04-b40f0a918610" src="https://github.com/matrixorigin/matrixone/assets/113406637/ff48c320-32d5-479a-bfda-19f42edd75bf">

因此先开始从这个时间段开始分析（1.8到1.10号的commit），发现这个pr开始qps开始只有个位数，同时这个pr引起过其他报错，报错修复后，但read_only qps依然只有21左右，所以这个pr导致性能下降可能性很大，请 @aunjgr 定位
<img width="1398" alt="企业微信截图_210ba2be-b405-4f23-9125-62439695bb6c" src="https://github.com/matrixorigin/matrixone/assets/113406637/94062a39-c4d0-4385-9b95-fa72bee23d0c">

commit：25911aefc911e6df98a55042636f08004df6722d
<img width="1380" alt="企业微信截图_9f1a47ed-4ddf-47f3-b772-3fb35095e3f3" src="https://github.com/matrixorigin/matrixone/assets/113406637/216ca527-6340-40a7-81d8-e978e69ccb0e">

commit：594ad8b365da45fb27f755489f6bd01093ac1a7a
<img width="1379" alt="企业微信截图_b3a01dcb-ecaa-4b05-8dc2-6a4f24ee1462" src="https://github.com/matrixorigin/matrixone/assets/113406637/8a712211-c265-4807-b9ae-3acbd3357947">

sysbench 100w和10w也有相同的性能下降现象
<img width="693" alt="企业微信截图_f0d460f2-5992-4e1f-be30-04e8aa36cc6e" src="https://github.com/matrixorigin/matrixone/assets/113406637/59077117-12dc-4b4e-b930-b93539b61be8">

### Steps to Reproduce

```Markdown
sysbench 1000w read_only test
```

**Comment by heni02** [comment]
qps从5千多到3千多，继续二分分析

**Comment by aunjgr** [comment]
PR merged

**Comment by heni02** [comment]
单机和tke read_only，random_range性能已经恢复
comfirm,closed
tke：
<img width="1536" alt="企业微信截图_a2b381f2-2cc8-4edc-805e-91585f61c523" src="https://github.com/matrixorigin/matrixone/assets/113406637/47689ec1-90d0-4084-b816-0e8289f94a93">

单机：
<img width="1544" alt="企业微信截图_fe214f76-f376-4cf1-b7d9-ec44667ebbe7" src="https://github.com/matrixorigin/matrixone/assets/113406637/6a3de15e-af89-4327-8811-9bd6df7d6344">
