### ISSUE TITLE
[Bug]: ut test failed in TestAddressManager

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#14268]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![d646b2a5e95a611e79aae923443fd89](https://github.com/matrixorigin/matrixone/assets/112734932/878f00df-bae1-4a73-9322-753fea6a064a)

https://github.com/matrixorigin/matrixone/actions/runs/7564916086/attempts/1?pr=14266

### Steps to Reproduce

```Markdown
ut挂掉了
```

**Comment by volgariver6** [comment]
fixed
