### ISSUE TITLE
[Bug]: the format of result is wired for func concat when one of para value is 0.

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14276]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

702ccc5ef7a8830b2998690f3f0a0f4332041475

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 MO:
mysql> select concat('渠道号段',FLOOR(1/100)) as '渠道号段';
+-------------------+
| 渠道号段          |
+-------------------+
| 渠道号段0E+00     |
+-------------------+
1 row in set (0.01 sec)

mysql:
mysql>  select concat('渠道号段',FLOOR(1/100)) as '渠道号段';
+---------------+
| 渠道号段      |
+---------------+
| 渠道号段0     |
+---------------+
1 row in set (0.03 sec)

### Steps to Reproduce

```Markdown
as desc
```

**Comment by zengyan1** [comment]
等待pr合入

**Comment by zengyan1** [comment]
已修复

**Comment by aressu1985** [comment]
fixed:
mysql> select concat('渠道号段',FLOOR(1/100)) as '渠道号段';
+---------------+
| 渠道号段      |
+---------------+
| 渠道号段0     |
+---------------+
1 row in set (0.01 sec)

mysql> 
b595a3555ce83794319cd3f5c67e33aa0f7df158
