### ISSUE TITLE
Go generics is not as fast as non-generics 

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#1427]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

According to some of our earlier benchmarks, Go generics is not as fast as non-generics. Golang has an open issue discussing the same topic, https://github.com/golang/go/issues/50182.  

This issue is created to track the progress on this topic. No immediate action is required on this issue.

**Comment by fengttt** [comment]
fish this out of backlog.

**Comment by sukki37** [comment]
waiting for docs by @cnutshell

**Comment by cnutshell** [comment]
I think [this comment](https://github.com/golang/go/issues/50182#issuecomment-1001258256) gives a reasonable explanation.

**Comment by cnutshell** [comment]
For detailed investigation, there will be a document.
