### ISSUE TITLE
[Bug]: [date 1.18] tke regression: cn restart causes SIGQUIT: quit

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14285]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7914e3d1fab0f78ff268a0c25a34b2494738e357

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

regression env：
<img width="787" alt="企业微信截图_092d3037-b87d-4887-9aa8-c99bb94fae3f" src="https://github.com/matrixorigin/matrixone/assets/113406637/3e17de1a-78ce-4cad-a64a-9237c5dfccea">

cn crashed log：
SIGQUIT: quit
PC=0x47a121 m=5 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	/usr/local/go/src/runtime/sys_linux_amd64.s:557 +0x21 fp=0x7fa365a6eee0 sp=0x7fa365a6eed8 pc=0x47a121
runtime.futexsleep(0xc00006af00?, 0x100000?, 0x7fa365a6ef88?)
	/usr/local/go/src/runtime/os_linux.go:69 +0x30 fp=0x7fa365a6ef30 sp=0x7fa365a6eee0 pc=0x43dc70
runtime.notesleep(0xc000100148)
	/usr/local/go/src/runtime/lock_futex.go:160 +0x87 fp=0x7fa365a6ef68 sp=0x7fa365a6ef30 pc=0x4150a7
runtime.mPark(...)
	/usr/local/go/src/runtime/proc.go:1632
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:2536 +0x8c fp=0x7fa365a6ef98 sp=0x7fa365a6ef68 pc=0x44862c
runtime.findRunnable()
	/usr/local/go/src/runtime/proc.go:3229 +0xb9c fp=0x7fa365a6f0a8 sp=0x7fa365a6ef98 pc=0x449f5c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3582 +0xb1 fp=0x7fa365a6f0e0 sp=0x7fa365a6f0a8 pc=0x44ad51
runtime.park_m(0xc000103a00?)
	/usr/local/go/src/runtime/proc.go:3745 +0x11f fp=0x7fa365a6f128 sp=0x7fa365a6f0e0 pc=0x44b25f
traceback: unexpected SPWRITE function runtime.mcall
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:458 +0x4e fp=0x7fa365a6f140 sp=0x7fa365a6f128 pc=0x47630e
rax    0xca
rbx    0x0
rcx    0x47a123
rdx    0x0
rdi    0xc000100148
rsi    0x80
rbp    0x7fa365a6ef20
rsp    0x7fa365a6eed8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xb56dc7
r13    0xc00274ed4c
r14    0xc0001021a0
r15    0x0
rip    0x47a121
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

SIGQUIT: quit
PC=0x47a121 m=3 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	/usr/local/go/src/runtime/sys_linux_amd64.s:557 +0x21 fp=0x7f076ea6ece0 sp=0x7f076ea6ecd8 pc=0x47a121
runtime.futexsleep(0xc000072000?, 0x98800?, 0x7f076ea6ed88?)
	/usr/local/go/src/runtime/os_linux.go:69 +0x30 fp=0x7f076ea6ed30 sp=0x7f076ea6ece0 pc=0x43dc70
runtime.notesleep(0xc000098948)
	/usr/local/go/src/runtime/lock_futex.go:160 +0x87 fp=0x7f076ea6ed68 sp=0x7f076ea6ed30 pc=0x4150a7
runtime.mPark(...)
	/usr/local/go/src/runtime/proc.go:1632
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:2536 +0x8c fp=0x7f076ea6ed98 sp=0x7f076ea6ed68 pc=0x44862c
runtime.gcstopm()
	/usr/local/go/src/runtime/proc.go:2835 +0xaa fp=0x7f076ea6edc0 sp=0x7f076ea6ed98 pc=0x44920a
runtime.findRunnable()
	/usr/local/go/src/runtime/proc.go:2901 +0x3f fp=0x7f076ea6eed0 sp=0x7f076ea6edc0 pc=0x4493ff
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3582 +0xb1 fp=0x7f076ea6ef08 sp=0x7f076ea6eed0 pc=0x44ad51
runtime.goschedImpl(0xc57151a4e0)
	/usr/local/go/src/runtime/proc.go:3760 +0xbf fp=0x7f076ea6ef40 sp=0x7f076ea6ef08 pc=0x44b33f
runtime.gopreempt_m(0x20?)
	/usr/local/go/src/runtime/proc.go:3788 +0x4f fp=0x7f076ea6ef80 sp=0x7f076ea6ef40 pc=0x44b60f
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1074 +0x3cb fp=0x7f076ea6f130 sp=0x7f076ea6ef80 pc=0x45bf0b
traceback: unexpected SPWRITE function runtime.morestack
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:593 +0x8f fp=0x7f076ea6f138 sp=0x7f076ea6f130 pc=0x47646f
rax    0xca
rbx    0x0
rcx    0x47a123
rdx    0x0
rdi    0xc000098948
rsi    0x80
rbp    0x7f076ea6ed20
rsp    0x7f076ea6ecd8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x6
r13    0xc000098800
r14    0xc000006ea0
r15    0x7
rip    0x47a121
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

crashed log：
[nightly-devops-2.zip](https://github.com/matrixorigin/matrixone/files/13983995/nightly-devops-2.zip)

loki：
http://175.178.192.213:30088/explore?panes=%7B%22CSG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240118%5C%22%7D%20%7C%3D%20%60SIGQUIT%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705546847000%22,%22to%22:%221705622388000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7571501638/job/20619704894
```

**Comment by nnsgmsone** [comment]
等待云修正core dump生成的问题后在根据core dump debug

**Comment by nnsgmsone** [comment]
等待云修正core dump生成的问题后在根据core dump debug

**Comment by nnsgmsone** [comment]
处理生产环境的问题中

**Comment by m-schen** [comment]
我只能说，有限的信息让我很懵逼。没有什么办法，日志中没有有效信息可以拿到。

**Comment by m-schen** [comment]
@nnsgmsone 你就是我的天使😭

**Comment by nnsgmsone** [comment]
暂时无法复现了。。等待复现后的core dump

**Comment by nnsgmsone** [comment]
暂时无法复现了。。等待复现后的core dump

**Comment by nnsgmsone** [comment]
暂时无法复现了。。等待复现后的core dump

**Comment by heni02** [comment]
main最近无法复现该问题，先降级

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by sukki37** [comment]
It hasn't been reproduced for a long time; closed.
