### ISSUE TITLE
[Bug]: select with table name will cause panic

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#1428]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
main 24bd0c4b7e32ba23cf791cb2a23aa37eaf53e360
- Hardware parameters:
- OS type:
- Others:
CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

SELECT * FROM t1 where t1.userID<6 group by t1.userID;
```

### Actual Behavior

will cause panic now.

but without alias will run success.
SELECT * FROM t1 where userID<6 group by userID;

### Expected Behavior

+------+--------+-------+
| spID | userID | score |
+------+--------+-------+
|    2 |      2 |     2 |
|    3 |      3 |     3 |
|    4 |      6 |    10 |
|    5 |     11 |    99 |
+------+--------+-------+

### Additional information

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103060c78]

goroutine 860 [running]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/overload.init.9.func3(0x0, 0x1400c4af3e0, 0x14002eeef00, 0x0, 0x1)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/overload/lt.go:174 +0x28
github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/overload.BinaryEval(0xe, 0x3, 0x3, 0x0, 0x1, 0x0, 0x1400c4af3e0, 0x14002eeef00)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/overload/binary.go:90 +0x478
github.com/matrixorigin/matrixone/pkg/sql/colexec/extend.(*BinaryExtend).Eval(0x1400c4fca20, 0x1400c7da0e0, 0x14002eeef00)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/binary.go:60 +0x12c
github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.Call(0x14002eeef00, {0x104482ae0, 0x1400c4fccf0})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict/restrict.go:115 +0x5b4
github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform.preprocess(0x14002eeef00, 0x1400c902360)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform/transform.go:334 +0x44
github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform.(*Container).processFreeVars(0x14006540960, 0x14002eeef00, 0x1400c902360)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform/transform.go:164 +0x214
github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform.Call(0x14002eeef00, {0x104483f60, 0x1400c902360})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform/transform.go:75 +0x6c
github.com/matrixorigin/matrixone/pkg/vm.Run({0x1400c857080, 0x2, 0x2}, 0x14002eeef00)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/vm.go:47 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0x14004ce1f20, {0x1047ce668, 0x1400c902060}, 0x14002eeef00)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x160
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x1400c81b200, {0x1047d58b8, 0x1400319cb30})
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:376 +0xa8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1({0x1047d58b8, 0x1400319cb30}, 0x1400c87a3d0, 0x1400c81b200)
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:389 +0x38
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/Users/chenmingsong/gopath/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:388 +0xb4

**Comment by m-schen** [comment]
as far as I'm concerned, column vector's reference may count wrong due to alias. this memory has been freed too early.

**Comment by nnsgmsone** [comment]
It wasn't the reference counting that caused it, I'll fix that bug next.

**Comment by nnsgmsone** [comment]
solved

**Comment by m-schen** [comment]
verified.
