### ISSUE TITLE
[Bug]: No statement is returned when query from statement_info at t1 and get 34 rows when query at t2

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14298]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

8081e0516

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run the following query at `2024/01/19 07:25:05.305830 +0000` and get 0 result:
```
2024/01/19 07:25:05.305830 +0000 DEBUG worker/controller.go:378 trace {"elapsed": "33.518872ms", "rows": 0, "sql": "SELECT `statement_id`,any_value(`stats`) as `stats`,any_value(`duration`) as `duration`,any_value(`sql_source_type`) as `sql_source_type`,any_value(`account`) as `account`,any_value(`response_at`) as `response_at` FROM `system`.`statement_info` WHERE status != 'Running' and account != 'sys' and account != 'mocloud_mo_ob' and response_at >= '2024-01-19 07:19:00' and response_at < '2024-01-19 07:20:00' GROUP BY `statement_id`"}
```

Run the same query now and get 34 rows.

### Expected Behavior

Get the same query result for the query at any time

### Steps to Reproduce

```Markdown
NA
```

**Comment by DanielZhangQD** [comment]
有很多 “failed to upload file to MO” 的log：
https://grafana.cn-qa.matrixone.tech/d/d95944a3-849b-4da7-b92b-c18f323cebd2/etlmerge?orgId=1&from=1705640400000&to=1705651199000

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
improve: 
1. improve load performance
2. improve observability, 需要更直观的判断是否写csv 和 回写 mo的情况
3.

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by DanielZhangQD** [comment]
最近没有出现，暂时先关掉

**Comment by Ariznawlll** [comment]
### 测试版本

- 分支：`main`
- commit：`8e616a693458652cc26b3c4be45c6602dff298d4`
- 部署方式：本地独立进程多节点，1 Log + 1 TN + 2 CN；CN1/CN2 分别监听 `16001`/`16002`，两个 CN 均开启 trace
- 测试日期：2026-08-26

### 原问题验证

在最新 `main` 上可以稳定复现 `statement_info` 先查不到、随后由 ETL merge 回写后才可见的问题，触发条件已收敛为 CN 优雅退出时 collector 仍有未 flush 的尾部数据。

复现步骤：

1. CN1 设置 `disableTrace=false`、`trace-export-interval=600`，确保本轮 100 条记录仍在 collector 缓冲区；执行前设置 `disable_agg_statement=1`。
2. 在 CN1 的同一连接连续执行 100 条带唯一 marker 的 `SELECT`，100 条客户端响应均成功且返回值正确。
3. 立即向 CN1 发送 SIGINT，CN1 正常完成优雅关闭，日志包含：

   ```text
   handle last aggr stmt
   trace.shutdown.complete
   Shutdown complete
   ```

4. 启动 CN2 并查询这 100 条 marker，结果为：

   ```text
   count(*)  count(distinct statement_id)  sum(result_count)
   0         0                             0
   ```

5. 同时在 ETL 路径中能找到完整的回退 CSV；3 轮文件中 marker 行数均为 100。等待默认 `ETLMergeTask` 执行后，记录才重新出现在 `system.statement_info`。

以上复现 3/3，三轮 marker 分别为 `stmtdeep_grace_forced1`、`stmtdeep_grace_forced2`、`stmtdeep_grace_forced3`。

### Happy Path 覆盖

1. CN 保持运行、使用默认导出周期执行 100 条唯一 marker：约 6 秒后在另一 CN 查询到 100 条，`statement_id` 100 个唯一值，`result_count` 合计 100。
2. 5000 条并发落库后再优雅关闭：达到 buffer 阈值、已在关闭前完成 SQL flush 的记录全部可查，5000 条 SQL 和 statement ID 均唯一。
3. ETL merge 回写后：此前暂不可见的 1000 条记录恢复为 1000 条，statement ID 唯一，`result_count` 合计 1000。

### Unhappy Path 覆盖

1. collector 尾部数据未达到 flush 时间/大小阈值时优雅关闭：3/3 退化到 CSV，另一 CN 无法即时查询。
2. SQL writer 当前连接指向其他存活 CN 时优雅关闭：尾部数据可直接写入，100/100 条即时可见，说明问题与关闭时 SQL writer 连接目标有关。
3. 聚合关闭后逐条验证，排除了聚合导致 marker 被合并或查询条件遗漏。

### 白盒验证

代码路径与现象一致：

1. `cmd/mo-service/main.go` 中 motrace 收到关闭信号后先等待 `serviceWG.Wait()`，即 frontend 等服务关闭完成后才执行 `motrace.Shutdown()`。
2. `pkg/util/export/etl/content.go` 中 SQL flush 失败会回退为 CSV。
3. `pkg/util/export/merge.go` 默认由 ETL merge 周期任务把 CSV 回写 MO；默认 merge cycle 为 5 分钟。

因此优雅关闭本身返回成功，但并不代表尾部 `statement_info` 已写入可查询表。

### 回归测试

暂未加入。该场景需要独立多 CN 进程、控制 CN 退出顺序并检查 ETL fallback，适合补充 motr 多进程场景或 CN shutdown chaos 用例，不适合普通单连接 BVT。

### 测试证据

关键输出：

```text
round 1: client success=100, immediate statement_info=0, fallback CSV marker rows=100
round 2: client success=100, immediate statement_info=0, fallback CSV marker rows=100
round 3: client success=100, immediate statement_info=0, fallback CSV marker rows=100
control: client success=100, statement_info=100, distinct statement_id=100, sum(result_count)=100
```

相关实现：

- https://github.com/matrixorigin/matrixone/blob/8e616a693458652cc26b3c4be45c6602dff298d4/cmd/mo-service/main.go#L688-L702
- https://github.com/matrixorigin/matrixone/blob/8e616a693458652cc26b3c4be45c6602dff298d4/pkg/util/export/etl/content.go#L135-L160
- https://github.com/matrixorigin/matrixone/blob/8e616a693458652cc26b3c4be45c6602dff298d4/pkg/config/configuration.go#L129-L130

### 测试结论

测试不通过。
