### ISSUE TITLE
[Bug]: "no available CN server" is returned when connecting to MO

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

8081e0516

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Connect to MO in Cloud QA env and get the error 'ERROR 20101 (HY000): internal error: no available CN server':
```
host:freetier-02.cn-hangzhou.cluster.cn-qa.matrixone.tech user:bfc2da56_2ed5_4eff_b3fa_6aa1af94b852:admin:accountadmin
```

### Expected Behavior

login succeeds or return suspended error if the account has been suspended

### Steps to Reproduce

```Markdown
NA
```

### Additional information

This case runs between 01.22 6:06:07 - 6:25:03 UTC+8
No Pod restart during that time:
http://47.98.35.103/d/cluster-detail-cloud/cluster-detail-cloud?orgId=1&from=1705874400000&to=1705876199000&var-cluster=freetier-02&var-account=All&var-namespace=All&var-interval=$__auto_interval_interval&var-loki=loki&var-groupBy=__name__&var-pod=All&var-node=All

```
NAME                             READY   STATUS    RESTARTS        AGE
default-cn-dwh7b                 1/1     Running   1 (4d14h ago)   4d14h
default-cn-hjgsr                 1/1     Running   1 (4d14h ago)   4d14h
default-dn-0                     1/1     Running   3 (3d23h ago)   4d14h
default-log-0                    1/1     Running   2 (4d14h ago)   4d14h
default-log-1                    1/1     Running   2 (4d14h ago)   4d14h
default-log-2                    1/1     Running   0               4d14h
local-service-7cb75b9cfd-cbs76   1/1     Running   5 (4d13h ago)   4d13h
proxy-proxy-9sdkg                2/2     Running   1 (2d18h ago)   2d18h
proxy-proxy-f52bf                2/2     Running   1 (2d18h ago)   2d18h
```

**Comment by volgariver6** [comment]
这个问题在新版本上已经修复了，pr：https://github.com/matrixorigin/matrixone/pull/13474

**Comment by aressu1985** [comment]
fixed
