### ISSUE TITLE
[Bug]: occasional error :internal error: ExpectedEOB: truncate error

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#14300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

770fe6e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

https://github.com/matrixorigin/matrixone/actions/runs/7581607145/job/20652136327?pr=14283
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/fbab62d5-9c30-4e2e-a0b2-00d55817a0b9)

### Expected Behavior

right result in bvt

### Steps to Reproduce

```Markdown
ci

https://github.com/matrixorigin/matrixone/actions/runs/7581607145/job/20652136327?pr=14283
```

**Comment by LeftHandCold** [comment]
<img width="651" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/f50dd4ab-2feb-4771-88e9-03b15678b47b">
log没有上传成功

**Comment by sukki37** [comment]
dup with #14329
