### ISSUE TITLE
[Bug]: mo hung after stabilit test on distributed mode for about 6 hours 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14310]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

bc6b58b212aa868bf5a37493e8484954600ae660

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN:16C  64G
1*DN:16C  64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

mo hung after stabilit test on distributed mode for about 6 hours：
<img width="677" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/17603a40-0f11-4290-93f2-067e0454dc10">

and there are lots of txn leak in mo log:
http://192.168.240.6:20001/explore?panes=%7B%22oX-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240120%5C%22%7D%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705901521000%22,%22to%22:%221705903321000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1405" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e35a4310-9d10-4c4b-b84a-bb0e5adab059">

### Steps to Reproduce

```Markdown
run stability test on distributed mode
```

**Comment by daviszhen** [comment]
卡在等待活跃事务waitActive

![image](https://github.com/matrixorigin/matrixone/assets/60595215/362c5ec3-99b5-48be-8ad4-183c82a25102)

**Comment by daviszhen** [comment]
[Uploading xxx.tar.gz…]()

trace 和 goroutine

**Comment by daviszhen** [comment]
在此commit容易出现。

**Comment by daviszhen** [comment]
下午在pod里面试了一次。
卡了一段时间后，又能登录了。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/f8727464-6349-42f5-b341-048ae2ab489e)

**Comment by daviszhen** [comment]
新分支debug中

**Comment by daviszhen** [comment]
加日志定位中改

**Comment by daviszhen** [comment]
加日志定位中改

**Comment by aressu1985** [comment]
pr已经被revert了，没有在出现过
