### ISSUE TITLE
[Bug]: `internal error: ExpectedEOB: truncate error` occurred during bvt test in merge-run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14329]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

bf990ab

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7620402353/job/20755596025?pr=14323

http://175.178.192.213:30088/explore?panes=%7B%229Mn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-14323%5C%22%7D%20%7C%3D%20%60internal%20error:%20ExpectedEOB%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705979383723%22,%22to%22:%221705981788998%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1065" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/14e1c2af-e894-4779-9371-24be57d1ffd6">

### Steps to Reproduce

```Markdown
run bvt on distributed mo cluster
```

**Comment by daviszhen** [comment]
同样 #14300

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/7581607145/job/20652136327?pr=14283

**Comment by aptend** [comment]
```

{"level":"INFO","time":"2024/01/23 03:28:27.112518 +0000","caller":"rpc/handle.go:909","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 278327-select_for_update:278341-su_02_1 txn: ctx[018D345CB3E57D83A5A55B933A668660][1705980507106378876-1->9223372036854775807-4294967295][Active]: <nil>"}
...
{"level":"ERROR","time":"2024/01/23 03:28:33.749332 +0000","name":"cn-service.incrservice","caller":"incrservice/service.go:96","msg":"create auto increment cache failed","uuid":"38336431-3035-6434-6665-393333633239","table-id":272505,"txn":"018d345cc580751da9bb00e6e6967c39","error":"txn need retry in rc mode"}
...
{"level":"INFO","time":"2024/01/23 03:28:33.803932 +0000","caller":"rpc/handle.go:939","msg":"[precommit] drop/truncate relation: &{IsDrop:false DatabaseID:278327 DatabaseName:select_for_update Name:su_02_1 ID:272505 NewId:272506} txn: ctx[018D345CC580751DA9BB00E6E6967C39][1705980513748968719-1->9223372036854775807-4294967295][Active]: <nil>"}
...
{"level":"ERROR","time":"2024/01/23 03:28:33.804001 +0000","caller":"txnimpl/database.go:173","msg":"error: internal error: ExpectedEOB: truncate error"}
```

the table `su_02_1` had id `278341` when created. However, CN sent id `272505` to truncate `su_02_1` after the transaction was retried.

**Comment by XuPeng-SH** [comment]
> ```
> 
> {"level":"INFO","time":"2024/01/23 03:28:27.112518 +0000","caller":"rpc/handle.go:909","msg":"[precommit] create relation: {AccountID:0 UserID:1 RoleID:0}, 278327-select_for_update:278341-su_02_1 txn: ctx[018D345CB3E57D83A5A55B933A668660][1705980507106378876-1->9223372036854775807-4294967295][Active]: <nil>"}
> ...
> {"level":"ERROR","time":"2024/01/23 03:28:33.749332 +0000","name":"cn-service.incrservice","caller":"incrservice/service.go:96","msg":"create auto increment cache failed","uuid":"38336431-3035-6434-6665-393333633239","table-id":272505,"txn":"018d345cc580751da9bb00e6e6967c39","error":"txn need retry in rc mode"}
> ...
> {"level":"INFO","time":"2024/01/23 03:28:33.803932 +0000","caller":"rpc/handle.go:939","msg":"[precommit] drop/truncate relation: &{IsDrop:false DatabaseID:278327 DatabaseName:select_for_update Name:su_02_1 ID:272505 NewId:272506} txn: ctx[018D345CC580751DA9BB00E6E6967C39][1705980513748968719-1->9223372036854775807-4294967295][Active]: <nil>"}
> ...
> {"level":"ERROR","time":"2024/01/23 03:28:33.804001 +0000","caller":"txnimpl/database.go:173","msg":"error: internal error: ExpectedEOB: truncate error"}
> ```
> 
> the table `su_02_1` had id `278341` when created. However, CN sent id `272505` to truncate `su_02_1` after the transaction was retried.

@zhangxu19830126 please help to investigate this issue. it seems a problem with retry.

**Comment by zhangxu19830126** [comment]
a readonly table cache in txn workspace, but in some space it will changed,  cause this bug.

**Comment by zhangxu19830126** [comment]
fixed

**Comment by sukki37** [comment]
not repro
