### ISSUE TITLE
[Bug]:  load data from aliyun with arn panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14328]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

8.0.30-MatrixOne-v1.1.0 （mocloud dev环境）

### Commit ID

af101ee2b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1885" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8465d5db-fcbe-4049-b20b-d1ec96b77627">

### Expected Behavior

load data success.

### Steps to Reproduce

```Markdown
mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u 76ea92e3_0493_4117_a266_1134f2ec2bc1:admin:accountadmin  -p Admin123

create database test;
use test；
create table test01(col1 char, col2 char);
load data url s3option {"endpoint"='oss-cn-hangzhou.aliyuncs.com', "bucket"='ariznawl', "filepath"='test.csv', "role_arn"='acs:ram::1011981963396790:role/testarn',"region"='oss-cn-hangzhou',"compression"='auto',"external_id"='abcd1234'} into table test01 FIELDS TERMINATED BY ',';
```

**Comment by reusee** [comment]
working on other issues

**Comment by Ariznawlll** [comment]
<img width="1383" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/35708d01-f53b-46f2-b34d-10369c923c71">

load data with arn test done .（权限策略配置的[AliyunOSSFullAccess]

**Comment by Ariznawlll** [comment]
其余遗留问题由 issue14512 跟踪.
