### ISSUE TITLE
[Bug]: CN panic when executing delete SQL

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14326]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

af101ee2b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Execute SQL `delete from mo_catalog.statement_cu where response_at >= '2024-01-23 02:06:00.000'` and CN panics with the following log:
```
{"level":"INFO","time":"2024/01/23 02:48:51.918362 +0000","caller":"disttae/logtail_consumer.go:670","msg":"[logtail-consumer] subscribe tbl[db: 1, tbl: 272500] succeed"}
{"level":"WARN","time":"2024/01/23 02:48:51.932483 +0000","caller":"compile/compile.go:4010","msg":"read table statement_cu ,workload among 2 nodes not balanced, max 1, min 0, cnlist: 172.20.29.132:6002 172.20.7.5:6002 172.20.73.132:6002 172.20.79.131:6002 172.20.81.131:6002 172.20.83.131:6002 "}
{"level":"INFO","time":"2024/01/23 02:48:51.932607 +0000","caller":"compile/compile.go:1229","msg":"delete of 'delete from mo_catalog.statement_cu where response_at >= '2024-01-23 02:06:00.000'' write s3\n"}
{"level":"FATAL","time":"2024/01/23 02:48:51.933142 +0000","name":"cn-service","caller":"cnclient/client.go:83","msg":"remote run pipeline in local","uuid":"32373037-3434-6437-3065-326135666437","local-address":"172.20.7.5:6002","remote-address":"172.20.7.5:6002","stacktrace":"github.com/matrixorigin/matrixone/pkg/cnservice/cnclient.(*CNClient).NewStream\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/cnclient/client.go:83\ngithub.com/matrixorigin/matrixone/pkg/cnservice/cnclient.GetStreamSender\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/cnclient/client.go:48\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).notifyAndReceiveFromRemote.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:845"}
{"level":"INFO","time":"2024/01/23 02:48:51.943259 +0000","caller":"motrace/syncer.go:89","msg":"Wait signal done."}
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

**Comment by DanielZhangQD** [comment]
Log:
http://47.96.110.240/explore?panes=%7B%22Auk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221705975200000%22,%22to%22:%221705978799000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by nnsgmsone** [comment]
大致定位了问题，提交分支来测试验证

**Comment by loveRhythm1990** [comment]
prod report fatal:

日志：

{"level":"FATAL","time":"2024/01/24 07:43:29.093740 +0000","name":"cn-service","caller":"cnclient/client.go:83","msg":"remote run pipeline in local","uuid":"64373534-3834-3263-6334-366261646537","local-address":"172.20.67.135:6002","remote-address":"172.20.67.135:6002","stacktrace":"github.com/matrixorigin/matrixone/pkg/cnservice/cnclient.(*CNClient).NewStream\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/cnclient/client.go:83\ngithub.com/matrixorigin/matrixone/pkg/cnservice/cnclient.GetStreamSender\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/cnclient/client.go:48\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).notifyAndReceiveFromRemote.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:819"}
`

**Comment by sukki37** [comment]
repro in prod env：http://121.43.41.174/explore?panes=%7B%22SHe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706079405659%22,%22to%22:%221706082418338%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aressu1985** [comment]
fixed:
mysql> select count(distinct(l_shipdate))  from lineitem;
+------------------------------+
| count(distinct (l_shipdate)) |
+------------------------------+
|                         2526 |
+------------------------------+
1 row in set (0.33 sec)

mysql> select l_shipdate from lineitem limit 1;
+------------+
| l_shipdate |
+------------+
| 1996-12-13 |
+------------+
1 row in set (0.17 sec)

mysql> delete from lineitem where l_shipdate = '1996-12-13';
Query OK, 24829 rows affected (11.23 sec)
