### ISSUE TITLE
[Subtask]: LogService active migrates

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#14336]
### Parent Issue

#13079

### Detail of Subtask

LogService took the initiative to migrate the ongoing transaction of locks,  so that the transactions can be elegantly migrated in the rolling restart cn.

**Comment by heni02** [comment]
和#13079一样，和 @tianyahui-python 确认，目前mo-cloud升级时测试没有发现lock table相关错误，该feature关闭
