### ISSUE TITLE
[Bug]: `ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference` is returned

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14344]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

5d7bb0afc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Execute the sql `select count(*) from mo_catalog.statement_cu where response_at >= '2024-01-23 02:06:00.000';` in dev and get the following error:
```
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:841
github.com/matrixorigin/matrixone/pkg/sql/plan/function.generateAggExecutor
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/function.go:234
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).generateAggStructures
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/col
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Log:
http://47.96.110.240/explore?panes=%7B%22Auk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60panic%20runtime%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706061507552%22,%22to%22:%221706061571889%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by DanielZhangQD** [comment]
不确定是否和查出来的数据量有关系：
```
MySQL [mo_cloud]> select count(*) from mo_catalog.statement_cu where response_at >= '2024-01-23 02:03:00.000';
+----------+
| count(*) |
+----------+
|      181 |
+----------+
1 row in set (0.07 sec)

MySQL [mo_cloud]> select count(*) from mo_catalog.statement_cu where response_at >= '2024-01-23 02:02:00.000';
+----------+
| count(*) |
+----------+
|      242 |
+----------+
1 row in set (0.00 sec)

MySQL [mo_cloud]> select count(*) from mo_catalog.statement_cu where response_at >= '2024-01-23 02:01:00.000';
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:841
github.com/matrixorigin/matrixone/pkg/sql/plan/function.generateAggExecutor
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/function/function.go:234
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).generateAggStructures
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/col
MySQL [mo_cloud]>
```

**Comment by DanielZhangQD** [comment]
连到 Proxy 查询没有问题，但是直连 cn 查询报上面的错误

**Comment by nnsgmsone** [comment]
看着大概率是因为两个cn版本不一样，在红深移除那个cn后这个问题就没了。。因为attach上去后已经无法复现这个问题了。等待红深重建那个低版本的cn后，在看这个是什么情况

**Comment by nnsgmsone** [comment]
https://github.com/matrixorigin/matrixone/pull/14334，具体原因是这个pr修改了function id，所以两个版本的cn的fid对不上，导致一个agg函数识别成了非agg函数。所以遇到了这个panic

**Comment by DanielZhangQD** [comment]
这里需要优化，因为升级过程中肯定会出现不同版本 CN 在同一个集群运行，可能的方案比如：
“CN通信的Protocol支持多版本和向后兼容” 或者 “when a CN requests workers for a query, HA keeper ONLY hands out CN with the same version.”
@ouyuanning PTAL

**Comment by ouyuanning** [comment]
待确认方案

**Comment by ouyuanning** [comment]
待确认方案

**Comment by ouyuanning** [comment]
待确认方案

**Comment by ouyuanning** [comment]
在处理  Column Group的需求。还没时间处理。

**Comment by ouyuanning** [comment]
在处理 Column Group的需求。还没时间处理

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/issues/14408

**Comment by m-schen** [comment]
不会处理。

不同节点跑不同版本的cn，这些节点不能一起处理同一个查询的，相同的function id在不同版本上对应的函数可能不一样，会发生各种panic的。

**Comment by m-schen** [comment]
没看，在忙agg执行上下文占用内存太多的问题

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
和上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
与上一个评论相同，做不了这个。

**Comment by m-schen** [comment]
请假了

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
在改connection reset的s-1中

**Comment by m-schen** [comment]
该问题是同一集群下存在多个不同版本的cn节点的问题，最近更新版本也复现了。

与issue https://github.com/matrixorigin/MO-Cloud/issues/3541 相同，后续一起关闭。

**Comment by m-schen** [comment]
等一下3541的验证

**Comment by m-schen** [comment]
没投入

**Comment by m-schen** [comment]
@DanielZhangQD 与 3541 完全相同，可放心关闭。
