### ISSUE TITLE
[Bug]: 阿里云Dev环境，执行SQL报错ERROR 20503 (HY000): stream closed

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#14359]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

5d7bb0afcc5807fd5f3d3f73d4e4d971b64e097d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
阿里云 Dev环境 dump用户
MySQL Client登录
稳定复现
```

### Actual Behavior

执行如下SQL
```
select * from (select account,max(collecttime) as max_collecttime from system_metrics.server_storage_usage where DATE_FORMAT(convert_tz(collecttime,'+00:00','+08:00'),'%Y-%m-%d') = '2024-01-24' group by account ) as t1 left join system_metrics.server_storage_usage as t2 on t1.account = t2.account and t1.max_collecttime = t2.collecttime ;
```
等待一段时间后报错ERROR 20503 (HY000): stream closed，稳定复现。

### Expected Behavior

期望正常执行

### Steps to Reproduce

```Markdown
as actual behavior
```

**Comment by badboynt1** [comment]
convert_tz函数的实现有问题，性能太差。

**Comment by xiaoshuwei** [comment]
验收未通过，目前Dev已经更新到最新版本之后，但是仍然会报这个问题。cc @badboynt1

**Comment by badboynt1** [comment]
这个问题我当时在本地，只有几万条数据也能跑出超时。 修复后在本地已经没问题了。
但是在mocloud上，数据上亿的时候仍然不行。我再看一下

**Comment by badboynt1** [comment]
首先这个执行计划仍然有进一步优化的空间。 优化后会跑的更快。
其次即使不优化，现在的执行计划应该也能跑的完，不应该报错。我看了日志，报错是似乎是cn之间网络断开
目前dev环境是3cn, 跑这条query是必现
![image](https://github.com/matrixorigin/matrixone/assets/112734932/15fe906d-0505-49fc-8806-4602149d857a)

**Comment by badboynt1** [comment]
先处理其他issue

**Comment by badboynt1** [comment]
先处理其他issue

**Comment by xiaoshuwei** [comment]
最新Dev环境已经好了，先关掉，如果有复现再看。
