### ISSUE TITLE
[Bug]: CN continually FATAL: remote run pipeline in local

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14353]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.0.2

### Commit ID

v1.0.2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

http://121.43.41.174/explore?panes=%7B%22SHe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22default-cn%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706079405659%22,%22to%22:%221706082418338%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

[ssb-tools.zip](https://github.com/matrixorigin/matrixone/files/14036073/ssb-tools.zip)
modify conf/doris-cluster.conf with your mo configuration, then follow the steps in `README.md`, step 4 will fail with `lost connection xxxx`

**Comment by sukki37** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/14326

**Comment by sukki37** [comment]
```
INSERT INTO lineorder_flat
SELECT
    LO_ORDERDATE,
    LO_ORDERKEY,
    LO_LINENUMBER,
    LO_CUSTKEY,
    LO_PARTKEY,
    LO_SUPPKEY,
    LO_ORDERPRIORITY,
    LO_SHIPPRIORITY,
    LO_QUANTITY,
    LO_EXTENDEDPRICE,
    LO_ORDTOTALPRICE,
    LO_DISCOUNT,
    LO_REVENUE,
    LO_SUPPLYCOST,
    LO_TAX,
    LO_COMMITDATE,
    LO_SHIPMODE,
    C_NAME,
    C_ADDRESS,
    C_CITY,
    C_NATION,
    C_REGION,
    C_PHONE,
    C_MKTSEGMENT,
    S_NAME,
    S_ADDRESS,
    S_CITY,
    S_NATION,
    S_REGION,
    S_PHONE,
    P_NAME,
    P_MFGR,
    P_CATEGORY,
    P_BRAND,
    P_COLOR,
    P_TYPE,
    P_SIZE,
    P_CONTAINER
FROM (
    SELECT
        lo_orderkey,
        lo_linenumber,
        lo_custkey,
        lo_partkey,
        lo_suppkey,
        lo_orderdate,
        lo_orderpriority,
        lo_shippriority,
        lo_quantity,
        lo_extendedprice,
        lo_ordtotalprice,
        lo_discount,
        lo_revenue,
        lo_supplycost,
        lo_tax,
        lo_commitdate,
        lo_shipmode
    FROM lineorder
    WHERE ${con}
) l
INNER JOIN customer c
ON (c.c_custkey = l.lo_custkey)
INNER JOIN supplier s
ON (s.s_suppkey = l.lo_suppkey)
INNER JOIN part p
ON (p.p_partkey = l.lo_partkey);
```

**Comment by nnsgmsone** [comment]
这是一个1.0特有的问题，1.1已经不会在构造类似的pipeline了。可以升级解决，先在1.0将fatal改成error并且输出上下文信息

**Comment by sukki37** [comment]
This bug doesn't exist on 1.1-dev, downgrade. 
Next steps: 

- [ ] Change 'fatal' to 'error', let the caller handle the error, and add context logging, 
- [ ] Review and refine the design specifications for this section.

**Comment by nnsgmsone** [comment]
已经提交pr

**Comment by aressu1985** [comment]
@heni02 这个补充个case到BVT，或者big_data那个流程里面吧

**Comment by heni02** [comment]
case已加入bigdata
https://github.com/matrixorigin/mo-nightly-regression/commit/63ccda39ec2dd0bfa22bf3f2ac166d4850911dd6
