### ISSUE TITLE
[Bug]: sysbench delete tps with index is much lower that without index

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14373]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

32a05ab

### Other Environment Information

```Markdown
- Hardware parameters:64C 256G
- OS type:
- Others:
```

### Actual Behavior

on standlone mode, sysbench delete tps with index is much lower that without index:
[with index]
<img width="1382" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/eb4b547a-2553-4972-91e1-f5276e17fd0c">

[no index]
<img width="1382" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/63fb4052-b00e-413b-8ed8-e352fd39bb25">

prof:
[delete_index.tar.gz](https://github.com/matrixorigin/matrixone/files/14047744/delete_index.tar.gz)
[delete_no_index.tar.gz](https://github.com/matrixorigin/matrixone/files/14047745/delete_no_index.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo standlone mode,and create two databases:sysbench_100w_no_auto_no_index,sysbench_100w_no_auto_index
2. git clone https://github.com/matrixorigin/mo-sysbench.git
3. prepare data:
sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password='111' oltp_common.lua --mysql-db=sysbench_100w_no_auto_index  --tables=10 cleanup
sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password='111' oltp_common.lua --mysql-db=sysbench_100w_no_auto_index --auto_inc=off --tables=10 --table_size=1000000 --threads=10  prepare

sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password='111' oltp_common.lua --mysql-db=sysbench_100w_no_auto_no_index --create_secondary=off  --tables=10 cleanup
sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password='111' oltp_common.lua --mysql-db=sysbench_100w_no_auto_no_index --auto_inc=off --create_secondary=off --tables=10 --table_size=1000000 --threads=10  prepare

4.run test
[no index]
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable oltp_delete.lua --mysql-db=sysbench_100w_no_auto_no_index --tables=10 --table_size=1000000  --time=60 --report-interval=2 --threads=100 run

[with index]
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable oltp_delete.lua --mysql-db=sysbench_100w_no_auto_index --tables=10 --table_size=1000000  --time=60 --report-interval=2 --threads=100 run
```

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
在解决中移物联的issue

**Comment by aunjgr** [comment]
明天来看这个

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
等存储优化完成

**Comment by aunjgr** [comment]
待重新验证

**Comment by aunjgr** [comment]
等存储优化完成

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
on leave

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
等 #17500 完成再看

**Comment by aressu1985** [comment]
目前 MAIN的sysbench 100w ，测试10s中，结果如下：
COMMIT：8415938eea7fec24ae4446591207e3cbd6428c8b

[index]
TPS：25475

[no index]
TPS: 49294

**Comment by aunjgr** [comment]
main上差两倍是正常现象，因为从删一张表变成删两张表。DML重构分支合并之后，如果没有回退，这个issue就可以关掉了。

**Comment by heni02** [comment]
main commit:4fc3976601e89599d0c0e2c2627cee9c93960406
sysbench 100w delete 100threads index tps：27475
<img width="1107" alt="企业微信截图_3304bf53-946a-493c-8a19-2d42b580e5a7" src="https://github.com/user-attachments/assets/0f1623ed-3449-496b-98b2-a1440cedd0d6">

sysbench 100w delete 100threads without index tps：47483
![image](https://github.com/user-attachments/assets/b45e8c40-ed89-45bf-8019-b4d8e616e4ba)
