### ISSUE TITLE
[Bug]: CN Crash by panic panic: context deadline exceeded after another CN was killed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14383]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

7a96a59

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16C
- OS type:
- Others:
```

### Actual Behavior

When running tpcc test on distributed mode, then killed some cns, the client sometime reconnect in 2 minutes,but sometiimes in 5 minutes
<img width="1374" alt="企业微信截图_2fa5cc8a-b79e-4f6a-b7ca-b06fd42286cf" src="https://github.com/matrixorigin/matrixone/assets/47846308/761f49e0-3ae5-4295-a879-5804b28c3c93">

and in this duration, on of cn was crashed by panic :
{"level":"ERROR","time":"2024/01/25 09:35:04.966673 +0000","caller":"service/client.go:91","msg":"logtail client: subscribe via broken morpc stream"}
{"level":"ERROR","time":"2024/01/25 09:35:04.966799 +0000","caller":"service/client.go:92","msg":"error: stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:04.966814 +0000","caller":"disttae/logtail_consumer.go:313","msg":"[logtail-consumer] 170617500293792418537356463-6338-3137-6262-333332643833: connect to tn log tail server failed, err stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:05.967318 +0000","caller":"service/client.go:91","msg":"logtail client: subscribe via broken morpc stream"}
{"level":"ERROR","time":"2024/01/25 09:35:05.967417 +0000","caller":"service/client.go:92","msg":"error: stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:05.967435 +0000","caller":"disttae/logtail_consumer.go:313","msg":"[logtail-consumer] 170617500293792418537356463-6338-3137-6262-333332643833: connect to tn log tail server failed, err stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:06.968078 +0000","caller":"service/client.go:91","msg":"logtail client: subscribe via broken morpc stream"}
{"level":"ERROR","time":"2024/01/25 09:35:06.968182 +0000","caller":"service/client.go:92","msg":"error: stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:06.968212 +0000","caller":"disttae/logtail_consumer.go:313","msg":"[logtail-consumer] 170617500293792418537356463-6338-3137-6262-333332643833: connect to tn log tail server failed, err stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:07.968984 +0000","caller":"service/client.go:91","msg":"logtail client: subscribe via broken morpc stream"}
{"level":"ERROR","time":"2024/01/25 09:35:07.969208 +0000","caller":"service/client.go:92","msg":"error: stream closed"}
{"level":"ERROR","time":"2024/01/25 09:35:07.969259 +0000","caller":"disttae/logtail_consumer.go:313","msg":"[logtail-consumer] 170617500293792418537356463-6338-3137-6262-333332643833: connect to tn log tail server failed, err stream closed"}
{"level":"INFO","time":"2024/01/25 09:35:08.577275 +0000","caller":"blockio/pipeline.go:470","msg":"SelectivityStats: BLK[0/0=0.0000] COL[0/0=0.0000] RDF[0/0=0.0000,0/0=0.0000]RDD[0s/0s/0s/0]"}
{"level":"INFO","time":"2024/01/25 09:35:08.577370 +0000","caller":"blockio/pipeline.go:476","msg":"MetaCacheWindow: 0/0 | 0/0, MetaCacheTotal: 1810/2472 | 1810/2500"}
panic: context deadline exceeded

goroutine 749 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).bootstrap.func1({0x42d4098?, 0xc0041a85d0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server.go:728 +0x9d
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0xe5

mo-log:
[cn-panic.log](https://github.com/matrixorigin/matrixone/files/14050621/cn-panic.log)

loki link:
http://192.168.240.6:20001/explore?panes=%7B%22ukw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-stability-regression-20240125%5C%22,%20pod%3D%5C%22stability-regression-dis-tp-cn-tgwxv%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706174530156%22,%22to%22:%221706176064489%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
running tpcc and kill cns
```

**Comment by volgariver6** [comment]
merged into 1.1-dev

**Comment by aressu1985** [comment]
tesing for more days

**Comment by aressu1985** [comment]
fixed
