### ISSUE TITLE
[Bug]: Loading data from cos has not been successful about 2h+.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14396]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d7db178e1c7298e2a3e4f99e7292425a7ef0ef06

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

load 10亿数据2h+还没load完：
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7652568813/job/20853174258

<img width="1014" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ff752072-94b4-4d2c-9a19-a6c9a7d3e721">

日志：http://175.178.192.213:30088/explore?panes=%7B%22kAl%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-d7db178%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706176800000%22,%22to%22:%221706180400000%22%7D%7D%7D

### Steps to Reproduce

```Markdown
table schema：
 CREATE TABLE `table_with_com_pk_index_for_load_1b` (
`id` BIGINT NOT NULL AUTO_INCREMENT,
`col1` TINYINT NOT NULL,
`col2` SMALLINT DEFAULT NULL,
`col3` INT DEFAULT NULL,
`col4` BIGINT DEFAULT NULL,
`col5` TINYINT UNSIGNED DEFAULT NULL,
`col6` SMALLINT UNSIGNED DEFAULT NULL,
`col7` INT UNSIGNED DEFAULT NULL,
`col8` BIGINT UNSIGNED DEFAULT NULL,
`col9` FLOAT DEFAULT NULL,
`col10` DOUBLE DEFAULT NULL,
`col11` VARCHAR(255) DEFAULT NULL,
`col12` DATE DEFAULT NULL,
`col13` DATETIME DEFAULT NULL,
`col14` TIMESTAMP DEFAULT NULL,
`col15` BOOL DEFAULT NULL,
`col16` DECIMAL(16,6) DEFAULT NULL,
`col17` TEXT DEFAULT NULL,
`col18` JSON DEFAULT NULL,
`col19` BLOB DEFAULT NULL,
`col20` BINARY(255) DEFAULT NULL,
`col21` VARBINARY(255) DEFAULT NULL,
`col22` VECF32(3) DEFAULT NULL,
`col23` VECF32(3) DEFAULT NULL,
`col24` VECF64(3) DEFAULT NULL,
`col25` VECF64(3) DEFAULT NULL,
PRIMARY KEY (`id`,`col1`),
UNIQUE KEY `col4` (`col4`),
KEY `col3` (`col3`,`col4`)
);

trigger workflow on tke.
```

**Comment by nnsgmsone** [comment]
分析了一下，只能看到insert-s3耗时很久，尚未定位到真实的原因

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
处理数据正确性问题中

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by sukki37** [comment]
tracked by #13045
