### ISSUE TITLE
[Bug]: Loading data from cos with the composite primary key is 7 times slower than the single primary key.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14397]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d7db178e1c7298e2a3e4f99e7292425a7ef0ef06

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

描述：单主键的表与复合主键的表load 1亿数据量，复合主键比单主键慢7倍

<img width="1055" alt="企业微信截图_864dc80e-a674-48db-9491-3cf1202473c3" src="https://github.com/matrixorigin/matrixone/assets/108530700/e7422932-668b-4a35-aed0-e1ea2315ec8c">

log：http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-d7db178%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
Load pk 100M table schema:
create table  if not exists big_data_test.table_with_pk_for_load_100M(
id bigint auto_increment primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

Load com ok index 100M table schema:
create table  if not exists big_data_test.table_with_com_pk_index_for_load_100M(
id bigint auto_increment,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3),
primary key (id, col1),
key(col3,col4),
unique key(col4)
);

trigger workflow on tke.
```

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
测试数据需要更新

**Comment by jensenojs** [comment]
测试数据需要更新

**Comment by Ariznawlll** [comment]
2024.02.26最新测试结果：
commit id：ead69b441080825781ba62c0bc886f4f4b9f9ac5
<img width="1011" alt="企业微信截图_33473067-a677-49cb-9ede-5846c3556811" src="https://github.com/matrixorigin/matrixone/assets/108530700/747d9328-12e2-4164-a614-46175a08ec83">

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/matrixone/pull/14388

看来这个pr和本issue关系不大, 后面看看

> 暂无进展, 后续远宁哥提了一个pr是优化相关问题的, 测试数据需要更新 https://github.com/ouyuanning/matrixone/tree/improve-insert-2nd-key

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
隐藏表在大规模数据量下似乎就不太行, 但还没找到根因

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
处理其他s-1

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
等测试结果

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理
- https://github.com/matrixorigin/matrixone/issues/15809

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
正在测

**Comment by jensenojs** [comment]
not working ont it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not working ont it

**Comment by jensenojs** [comment]
这两个问题实际上是一样的 : 

- https://github.com/matrixorigin/matrixone/issues/17165

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process, DML 重构后可能需要再测一下

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by Ariznawlll** [comment]
**commit：58ce75ffd119dba43e4fc3c78f853f850966f5ea**

**1亿数据量：**
<img width="1035" alt="企业微信截图_3231d916-d7cc-4921-9281-52a121959a76" src="https://github.com/user-attachments/assets/7afd098e-d917-4ba9-94c1-40c3b4127938">

**10亿数据量：**
<img width="1040" alt="企业微信截图_8ad5d08f-cb8a-4290-8880-8583efccb2e6" src="https://github.com/user-attachments/assets/710d3417-699c-45e0-8b7c-5c46dbf6685b">

现在没有这个问题了，先关掉

**Comment by jensenojs** [comment]
现在已经不存在这个问题了,  一亿数据pk index 导入耗时三分半, cpk index导入耗时四分钟. 十亿数据pk index 导入耗时34分, cpk index 导入耗时38分. 

<img width="1035" alt="企业微信截图_3231d916-d7cc-4921-9281-52a121959a76" src="https://github.com/user-attachments/assets/9ecfda16-9539-4550-8b84-a644a4d9934c">

<img width="1040" alt="企业微信截图_8ad5d08f-cb8a-4290-8880-8583efccb2e6" src="https://github.com/user-attachments/assets/eaf377ab-896a-46d2-87f0-408a8bced34a">
