### ISSUE TITLE
[Bug]: CN OOM when query from statement_info

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14398]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

83b8499b3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Execute the following sql and CN OOM:
```
SELECT statement_id, status, COUNT(*) as count      FROM system.statement_info      GROUP BY statement_id, status      HAVING COUNT(*) > 1;
```

```
MySQL [system_metrics]> SELECT statement_id, status, COUNT(*) as count      FROM system.statement_info      GROUP BY statement_id, status      HAVING COUNT(*) > 1;
Connection id:    129312394
Current database: system_metrics

ERROR 20503 (HY000): stream closed
```

```
default-cn-4cm7t                       0/1     OOMKilled   2 (78s ago)     25h
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
Run the above sql in Cloud Dev
```

**Comment by ouyuanning** [comment]
看着应该是agg的哈希基数过大造成的。辛苦龙冉帮忙看看

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
在解决中移物联的issue

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
on leave

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today
