### ISSUE TITLE
[Bug]: frequent w-w confict error in tpcc benchmark test when only upgrading cn from 1.0.2 to 1.1-dev

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14405]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

62194d91ea138bea5400f128e988b344ebbb5683

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

First running tpcc(1/10/100) test in distributed mo with 1.0.2 version, then ,upgrading cn to 1.1-dev(commit:62194d9),but TN was still in old version. 
When cns were upgrade successfully , there were w-w confict errors coming in tpcc payment and new order txn:
2024-01-27 16:43:20 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2024-01-27 16:43:28 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2024-01-27 16:43:41 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2024-01-27 16:43:45 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2024-01-27 16:44:17 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, 

but when tn had been upgraded to new version ,this error disappeared.

tool log:
[w-w.tar.gz](https://github.com/matrixorigin/matrixone/files/14071839/w-w.tar.gz)

mo-log (qa upgrade-test-1):
update soon

### Steps to Reproduce

```Markdown
as desc in actual behavior
```

**Comment by zhangxu19830126** [comment]
还在调试 trace，依赖trace

**Comment by zhangxu19830126** [comment]
还在调试 trace，依赖 trace

**Comment by zhangxu19830126** [comment]
分析出来一个dup的问题，也会引起ww。先fix了在观察。

**Comment by triump2020** [comment]
Delaying call to `ranges `leads to `Dup`

**Comment by triump2020** [comment]
Being Fix

**Comment by triump2020** [comment]
目前只在长期分布式稳定性中出现

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15235

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15545

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15731

**Comment by triump2020** [comment]
原因如下:  
 1.  txn1 在CN1 上insert 了 一条 PK, 并committed.   2.  CN2 上的txn2  还未等到 这个pk 同步到partition state 中，就开始 运行 delete pk(delete statment 的snapshot ts 应该是小于txn1 的commit ts 的, 否则CN2 会等water mark 超过txn1 的commit ts ) ， 这时pk 的rowid 查不到，delete 运行之后，affected rows =0， 相当于delete 没起效果; 然后运行 insert pk , 去重时，之前被txn1 提交的pk 同步过来了，然后在partiton state 中发现了相同的pk , 导致dup.

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15948

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992 fixed dup/ww bug.

**Comment by triump2020** [comment]
wait for @ouyuanning 's pr

**Comment by triump2020** [comment]
wait for @ouyuanning 's pr

**Comment by triump2020** [comment]
Wait for @ouyuanning ’ PR

**Comment by triump2020** [comment]
In testing

**Comment by triump2020** [comment]
需要继续查

**Comment by triump2020** [comment]
单机的ww/dup 已定位到大致原因.

**Comment by triump2020** [comment]
@aressu1985  这个可以关了，太久远了.
