### ISSUE TITLE
[Bug]:mo return  internal error: convert go error to mo error proto: wrong wireType = 0 for field Data during when upgrading cns during tpch test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14408]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

6294bce0248db539c3355372cfe98f30528dfa51

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

First running tpch loop test in mo with version(1.0.2), and then upgrade cns to 1.1-dev(commit:6294bc), duaring this period, the tpch queries return error :
2024-01-27 15:56:51The real result is:
ERROR 20101 (HY000) at line 1: internal error: convert go error to mo error proto: wrong wireType = 0 for field Data
2024-01-27 15:56:51 The query q22  has failed to  be executed,and cost: 2096

mo-log:
<img width="1341" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/de9221f3-ead1-4013-8403-fccce8fba619">

loki link:
http://47.98.35.103/explore?panes=%7B%221fu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22upgrade-test-1%5C%22%7D%20%7C%3D%20%60wrong%20wireType%20%3D%200%20for%20field%20Data%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706341803000%22,%22to%22:%221706342343000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
as desc in actual behavior
```

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
处理数据正确性问题中

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
无进展

**Comment by ouyuanning** [comment]
在处理prepare重构

**Comment by ouyuanning** [comment]
在处理prepare重构

**Comment by ouyuanning** [comment]
在处理prepare重构

**Comment by ouyuanning** [comment]
在处理prepare重构，还没时间看

**Comment by ouyuanning** [comment]
在处理prepare重构，还没时间看

**Comment by ouyuanning** [comment]
在处理prepare重构，还没时间看

**Comment by ouyuanning** [comment]
在处理prepare重构，还没时间看

**Comment by ouyuanning** [comment]
在处理prepare重构，还没时间看

**Comment by ouyuanning** [comment]
在处理w-w和prepare，还没时间处理

**Comment by ouyuanning** [comment]
在处理w-w和prepare，还没时间处理

**Comment by ouyuanning** [comment]
在处理w-w和prepare，还没时间处理

**Comment by ouyuanning** [comment]
处理其他问题，未投入

**Comment by ouyuanning** [comment]
处理其他问题，未投入

**Comment by ouyuanning** [comment]
处理其他问题，未投入

**Comment by ouyuanning** [comment]
处理其他s-1问题

**Comment by ouyuanning** [comment]
在处理其他s-1

**Comment by ouyuanning** [comment]
在处理其他s-1

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
