### ISSUE TITLE
[Bug]: tpch10g q10 q19 q11 cpu consumption stats increases much

### ISSUE THREAD

**Issue by Morranto** [matrixorigin/matrixone#14430]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

last

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cpu consumption increases much

### Steps to Reproduce

```Markdown
run tpch10g q10 q19 q20

compare 1.0.2  to  1.1.1 
```

**Comment by ouyuanning** [comment]
太久以前的了，建议关闭吧
