### ISSUE TITLE
[Bug]: many `no such table mo_catalog.mo_increment_columns` error logs printed during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14431]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b1511af

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

http://175.178.192.213:30088/explore?panes=%7B%22Fu0%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-14356%5C%22%7D%20%7C%3D%20%60no%20such%20table%20%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706487573106%22,%22to%22:%221706488375230%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
merge run
```

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process
