### ISSUE TITLE
[Bug]: Load data from cos report 'stream closed'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14438]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4170547615910e61bc5a4ae8e950fe4097703256

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:(load and insert test: load pk index 100M、load pk index 1B)
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7690791843/job/20955350330

<img width="1499" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/35123ffa-ff52-4e13-8617-825014f7cb4a">
<img width="1502" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c7dd0569-5a2b-44a4-8d4e-f5cdf684eb4b">

log：http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-4170547%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

load data seccess.

### Steps to Reproduce

```Markdown
table ddl:

create table  if not exists big_data_test.table_with_pk_index_for_load_100M(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3),
key(col3),
unique key(col4)
);

create table  if not exists big_data_test.table_with_pk_index_for_load_1B(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3),
key(col3),
unique key(col4)
);
```

**Comment by aronchanisme** [comment]
Could you please kindly help take a look? Thanks. @daviszhen

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by volgariver6** [comment]
无进展

**Comment by Ariznawlll** [comment]
最近几次没再出现了，先降级跟踪

**Comment by Ariznawlll** [comment]
【0411】

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8633046991/job/23688353616

<img width="1394" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b2a182a7-005e-4267-9ac3-5a7d78648691">

日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%224Wz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240410%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221712805561000%22,%22to%22:%221712805681000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
add some logs to help investigate.

**Comment by volgariver6** [comment]
等 https://github.com/matrixorigin/matrixone/pull/15448 合并进去

**Comment by volgariver6** [comment]
等 https://github.com/matrixorigin/matrixone/pull/15448 合并进去

**Comment by volgariver6** [comment]
等 https://github.com/matrixorigin/matrixone/pull/15448 合并进去

**Comment by volgariver6** [comment]
需要再问一下张旭为什么pr关掉了

**Comment by Ariznawlll** [comment]
**[0430]大数据测试又出现了这个问题：**
<img width="1378" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d873f779-d99a-4738-8f01-b82995e6a5d4">
**log：** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%227jw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240430%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by Ariznawlll** [comment]
[0508]
**commit:**  6b1a10d62ec53a54394120d8c6327c7886c1ce15
**job url:**  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8995012876/job/24709777906
<img width="979" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/eb2f7247-31d8-45aa-8255-b65e1b5e65c8">
**log:**  https://grafana.ci.matrixorigin.cn/explore?panes=%7B%227jw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240508%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
日志中看到logtail stream closed 信息，看日志是因为tn在31分16秒是发生了重启：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%227jw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240508%5C%22,%20matrixorigin_io_component%3D%5C%22DNSet%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221715167873000%22,%22to%22:%221715167923000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by Ariznawlll** [comment]
昨天没出现这个问题了。在跑几天看看
job url： https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9062078787/job/24928171270

**Comment by w-zr** [comment]
dn oom的问题已经被解决了，现在需要再跑几天看看会不会再出类似的问题。

**Comment by w-zr** [comment]
目前没有进展

**Comment by Ariznawlll** [comment]
观察一段时间

**Comment by Ariznawlll** [comment]
最新一次结果：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9301617718/job/25620006001
<img width="1506" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/20ad82a9-9de5-4995-9a43-f93491a65cf9">
没再出现了，关掉
