### ISSUE TITLE
[Bug]: Frequent Connection Failures During Merge Runs

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14444]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.1-dev

### Commit ID

5be5b44

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/7705638671/job/21000430123

The merge run process often fails to establish a connection, resulting in an error message indicating a connection failure.
This issue occurs randomly but frequently, making it difficult to predict when a merge run will be successful.

<img width="1867" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/3f5af02d-d2ba-47b2-b7ac-9a9d62bb51de">

Despite the frequent connection failures during merge runs, it's worth mentioning that the MO cluster does eventually initialize successfully. Moreover, when the connection issues are identified, it is possible to manually establish a connection to the cluster without any problems.

<img width="935" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/d6d4fadc-21b0-406d-85ee-e7327e17e894">

### Steps to Reproduce

```Markdown
start a merge run test
```

**Comment by sukki37** [comment]
many repro:
https://github.com/matrixorigin/matrixone/actions/runs/7698830738
https://github.com/matrixorigin/matrixone/actions/runs/7705311256
https://github.com/matrixorigin/matrixone/actions/runs/7705963876/attempts/1

https://github.com/matrixorigin/matrixone/actions/runs/7698213776
https://github.com/matrixorigin/matrixone/actions/runs/7698205359
https://github.com/matrixorigin/matrixone/actions/runs/7697665820

**Comment by sukki37** [comment]
The root cause is https://github.com/matrixorigin/MO-Cloud/issues/2448 and inappropriate method for determining cluster readiness.

**Comment by guguducken** [comment]
At present, the method of checking whether mo cluster is ready has been changed, and the bug
 of operator is followed up by issue https://github.com/matrixorigin/MO-Cloud/issues/2448. So I think this issue can be closed ~
