### ISSUE TITLE
[Bug]: select count(distinct(column)) from 10y table report 'internal error: Invalid alloc size 1233895424'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14441]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4170547615910e61bc5a4ae8e950fe4097703256

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：(Quries: Aggr 1B test)
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7690791843/job/20968567852

<img width="1489" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/78f3e587-ffef-4caa-8513-a973631723ac">

log: http://175.178.192.213:30088/explore?panes=%7B%22G3A%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-4170547%5C%22%7D%20%7C%3D%20%60Invalid%20alloc%20size%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706529600000%22,%22to%22:%221706530200000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
table ddl:
create table  if not exists big_data_test.table_basic_for_load_1B(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

ddl：
select count(distinct(col10)) from big_data_test.table_basic_for_load_1B;
```

**Comment by ouyuanning** [comment]
seems need spill finished.

**Comment by badboynt1** [comment]
现在shuffle只支持了整型数字类型和字符串类型   浮点数以及其他一些特殊类型尚未支持

**Comment by badboynt1** [comment]
这个问题比较特殊，浮点数是非精确的类型。对浮点数做distinct是否有意义是个待商榷的事情。
如果确定要支持对浮点数做distinct，那么需要让shuffle支持浮点数类型。可以解决这个问题。
但是如果要从本质上解决所有invalid alloc size的报错问题，需要改写聚合函数的实现。
因为即使支持了shuffle， 理论上也存在shuffle后每个桶的数据依然超过1g的可能性。
目前join已经改写完了，agg算子需要改写。 改写agg算子首先需要改写batch，将Aggs []agg.Agg[any] 从batch中移除。

**Comment by badboynt1** [comment]
先处理其他问题

**Comment by badboynt1** [comment]
先处理其他问题

**Comment by badboynt1** [comment]
先处理其他问题

**Comment by sukki37** [comment]
Seeking a distinct set of floating-point numbers is a rare event in itself which requires a tolerance level. This issue can be deprioritized and wait https://github.com/matrixorigin/matrixone/issues/13641.

**Comment by sukki37** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11384077358/job/31673705317
