### ISSUE TITLE
[Bug]: TestCommitS3Blocks Data race

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#14456]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

6ac99dd0be3c1ee87554084849e6bd9d94ce3036

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1035" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/423241a1-0eb1-463b-81c3-bbf8dee0656c">

### Steps to Reproduce

```Markdown
run -race TestCommitS3Blocks
```

**Comment by gouhongshen** [comment]
fixed

**Comment by gouhongshen** [comment]
use this to test.

`go test -race --count 1 -failfast  github.com/matrixorigin/matrixone/pkg/vm/engine/tae/...`

if no err happened, fixed.

**Comment by heni02** [comment]
closed
