### ISSUE TITLE
[Bug]: alter table drop primary key report 'no such table table_basic_for_alter_1b_copy_018d59db-94b3-7b7a-9ac6-0fc135cd7da7'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14453]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4170547615910e61bc5a4ae8e950fe4097703256

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url(Quries: write 1B): 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7690791843/job/20968567852

<img width="1010" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1efe6068-3e15-47c4-b74a-aa66d1c150a6">

log：http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-4170547%5C%22%7D%20%7C%3D%20%60table_basic_for_alter_1b_copy_018d5608-fd1c-7726-838b-fe6ea4f9c253%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221706544600000%22,%22to%22:%221706545800000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
数据量：1亿
原table schema:
create table  if not exists big_data_test.table_basic_for_alter_100M(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

执行下面的sql：
alter table big_data_test.table_basic_for_alter_100M add PRIMARY KEY (col4);
alter table big_data_test.table_basic_for_alter_100M drop PRIMARY KEY;
alter table big_data_test.table_basic_for_alter_100M add PRIMARY KEY (col3,col4);
alter table big_data_test.table_basic_for_alter_100M drop PRIMARY KEY;


数据量：10亿

原table schema:
create table  if not exists big_data_test.table_basic_for_alter_1B(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

执行下面的sql：
alter table big_data_test.table_basic_for_alter_1B add PRIMARY KEY (col4);
alter table big_data_test.table_basic_for_alter_1B drop PRIMARY KEY;
alter table big_data_test.table_basic_for_alter_1B add PRIMARY KEY (col3,col4);
alter table big_data_test.table_basic_for_alter_1B drop PRIMARY KEY;
```

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/42fd360a-9a25-49ca-bd49-57d296f69c74)
经过分析，该问题是由于执行insert时查询自增列表失败导致

**Comment by qingxinhome** [comment]
在main分支上最新代码验证1亿数据alter table，执行没有问题，
![image](https://github.com/matrixorigin/matrixone/assets/70939751/0e7fcb25-a1d4-44e1-a9f5-551d37d288e8)

**Comment by qingxinhome** [comment]
目前在验证10亿行数据的lalter table：
1. 10亿行数据的load data执行时间过长，超过5个小时仍未导入完成，需要想其他办法 @daviszhen @Ariznawlll @aressu1985

**Comment by qingxinhome** [comment]
The problem has been reiterated

**Comment by qingxinhome** [comment]
The problem has been reiterated

**Comment by Ariznawlll** [comment]
**[20240226] big data test on tke:**
job url: 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8029862130/job/21947111382
<img width="1006" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/82453bc0-68db-42c7-801c-d6b13cf9ea6e">

log:http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-ead69b4%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
The problem has been reiterated

**Comment by qingxinhome** [comment]
待处理

**Comment by qingxinhome** [comment]
待处理

**Comment by qingxinhome** [comment]
定位中

**Comment by qingxinhome** [comment]
定位中

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/32597e40-8421-42a1-a0dd-a9ba0bdaebb7)
定位这个issue过程，导入数据总是报错，这个问题依赖 https://github.com/matrixorigin/matrixone/issues/15120

**Comment by qingxinhome** [comment]
I have supplemented the logs and need to confirm the trigger points based on the logs

**Comment by Ariznawlll** [comment]
**[0418]大数据测试结果：(Quries 1y -> write 1y)**
**job url:**  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8720670949/job/23942821080
<img width="1369" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/664a4a43-21a2-4d98-be71-c04b73b3497e">
**log：** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22aCp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240417%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713379284000%22,%22to%22:%221713379840000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
在处理其他事情

**Comment by qingxinhome** [comment]
已补充日志，待复现

**Comment by qingxinhome** [comment]
已补充日志，待复现

**Comment by Ariznawlll** [comment]
在集群上测试ssb_100g数据的时候出现了这个问题：

<img width="810" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2b98fdda-e7dd-422b-9a96-cbd5f1babf80">

```
ddl：
create table ssb_100g.customer ( c_custkey int, c_name varchar (25), c_address varchar (25), c_city char (10), c_nation char (15), c_region char (12), c_phone char (15), c_mktsegment char (10) ) cluster by (c_region, c_nation, c_city);
```

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%224ya%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240514%5C%22%7D%20%7C%3D%20%60for%20alter%20table%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
从图中日志分析，一共有两次alter table时报错no such table，找不到复制表， 且对应两张表： `ssb_100g`.`customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b`和
`big_data_test`.`table_basic_for_alter_1b_copy_018f7a07-0da0-750b-a4aa-b5d543679cda`

并且， 该报错均发生在alter table的 insert data to copy table阶段，
先分析第一张表`ssb_100g`.`customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b`
----------------------------------------------------------------------------------------------------------------------------------------

{"level":"INFO","time":"2024/05/15 02:07:42.646113 +0000","name":"cn-service.txn","caller":"compile/alter.go:94",
"msg":"insert data to copy table for alter table",
"uuid":"39373766-6466-3861-6563-643832616666",
"databaseName":"ssb_100g",
"origin tableName":"customer",
"copy tableName":"customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b",
"InsertTmpDataSql":"INSERT INTO `ssb_100g`.`customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b` (`c_city`, `c_nation`, `c_region`, `c_phone`, `c_mktsegment`, `c_custkey`, `c_name`, `c_address`) SELECT `c_city`, `c_nation`, `c_region`, `c_phone`, `c_mktsegment`, `c_custkey`, `c_name`, `c_address` FROM `ssb_100g`.`customer`",
"error":"no such table ssb_100g.customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b",
"session_id":"018f79f2-5feb-71d7-9fe5-7d8e8ffc90fd",
"statement_id":"018f7a01-5b9b-75fc-837f-c917dd22f712",
"txn_id":"018f7a015b9d73979fa806b7b99307a5",
"span":{"trace_id":"09f1dfad-08f8-7c92-9ffa-24706ac9ec6a","span_id":"d536796300f97e7f"}}

---------------------------------------------------------------------------------------------------------------------------------
该复制表的建表语句为：
{"level":"INFO","time":"2024/05/15 02:07:40.549935 +0000","caller":"compile/sql_executor.go:355",
"msg":"sql_executor exec",
"sql":"CREATE TABLE `ssb_100g`.`customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b` (\n`new` INT ,\n`c_custkey` INT ,\n`c_name` VARCHAR(25) ,\n`c_address` VARCHAR(25) ,\n`c_city` CHAR(10) ,\n`c_nation` CHAR(15) ,\n`c_region` CHAR(12) ,\n`c_phone` CHAR(15) ,\n`c_mktsegment` CHAR(10) \n) CLUSTER BY (`c_region`, `c_nation`, `c_city`)",
"txn-id":"018f7a015b9d73979fa806b7b99307a5","duration":"100.090441ms","AffectedRows":0}
即：
CREATE TABLE `ssb_100g`.`customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b` (
`new` INT ,
`c_custkey` INT ,
`c_name` VARCHAR(25) ,
`c_address` VARCHAR(25) ,
`c_city` CHAR(10) ,
`c_nation` CHAR(15) ,
`c_region` CHAR(12) ,
`c_phone` CHAR(15) ,
`c_mktsegment` CHAR(10) 
) CLUSTER BY (`c_region`, `c_nation`, `c_city`);

从表面看，该表没有显式定义自增列，且该表没有主键，
但是，系统会为其创建一个隐藏主键，该隐藏主键为自增列

---------------------------------------------------------------------------------------------------------------------------------



{"level":"ERROR","time":"2024/05/15 02:07:41.077253 +0000","caller":"preinsert/preinsert.go:128",
"msg":"insert auto increment column failed",
"error":"no such table .Cannot find tableID 272892 in table mo_increment_columns, accountid 10001, txn: 018f7a015dea78d5832a5ab25707ca5f/Active/S:1715738861022407870-1
col_name: user_id, table_id: 272793\n
col_name: role_id, table_id: 272795\n
col_name: function_id, table_id: 272800\n
col_name: configuration_id, table_id: 272802\n
col_name: proc_id, table_id: 272806\n
col_name: stage_id, table_id: 272808\n
col_name: configuration_id, table_id: 272813\n
col_name: __mo_fake_pk_col, table_id: 272816\n
col_name: __mo_fake_pk_col, table_id: 272817\n
col_name: __mo_fake_pk_col, table_id: 272818\n
col_name: __mo_fake_pk_col, table_id: 272826\n
col_name: __mo_fake_pk_col, table_id: 272828\n
col_name: __mo_fake_pk_col, table_id: 272830\n
col_name: __mo_fake_pk_col, table_id: 272832\n
col_name: __mo_fake_pk_col, table_id: 272833\n
col_name: __mo_fake_pk_col, table_id: 272839\n
col_name: __mo_fake_pk_col, table_id: 272840\n
col_name: __mo_fake_pk_col, table_id: 272841\n
col_name: __mo_fake_pk_col, table_id: 272842\n
col_name: __mo_fake_pk_col, table_id: 272843\n
col_name: __mo_fake_pk_col, table_id: 272844\n
col_name: __mo_fake_pk_col, table_id: 272845\n
col_name: __mo_fake_pk_col, table_id: 272846\n
col_name: __mo_fake_pk_col, table_id: 272847\n
col_name: __mo_fake_pk_col, table_id: 272848\n
col_name: __mo_fake_pk_col, table_id: 272859\n
col_name: __mo_fake_pk_col, table_id: 272860\n
col_name: __mo_fake_pk_col, table_id: 272886\n
col_name: __mo_fake_pk_col, table_id: 272887\n
col_name: __mo_fake_pk_col, table_id: 272888\n
col_name: __mo_fake_pk_col, table_id: 272891\n"}


{"level":"ERROR","time":"2024/05/15 02:07:41.077330 +0000","caller":"preinsert/preinsert.go:129",
"msg":"error: no such table ssb_100g.customer_copy_018f7a01-5b9d-74a7-b687-3587d442c08b"}

**Comment by qingxinhome** [comment]
问题已经确认是自增列服务导致表id找不到导致，张旭建议打开txntrace追踪

**Comment by qingxinhome** [comment]
问题已经确认是自增列服务导致表id找不到导致，张旭建议打开txntrace追踪

**Comment by qingxinhome** [comment]
问题已经确认是自增列服务导致表id找不到导致，张旭建议打开txntrace追踪

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by Ariznawlll** [comment]
这两天跑main已经没有这个问题了，今晚跑下1.2-dev

**Comment by Ariznawlll** [comment]
1.2-dev也没有这个问题了
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9837401694/job/27190387587

已修复，测试通过
