### ISSUE TITLE
[Bug]: Loading data from cos, bigint as primary key column report "'internal error: malformed vector input: \x00[2.1227, 17.384, 1.5781]\x00')".

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14470]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5078085cd5049fa721752637eb402902e48b2656

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url(Load and insert test)：**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7709943518/job/21012656398

<img width="1495" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ef768133-0de0-4350-a2de-61da32d46a3c">

<img width="1499" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/370b5bc9-fa2b-4c16-ba4f-65be14713d63">

log：
http://175.178.192.213:30088/explore?panes=%7B%22G3A%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-5078085%5C%22%7D%20%7C%3D%20%60the%20input%20value%20%27id%27%20is%20not%20int64%20type%20for%20column%200%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1亿表schema：
create table  if not exists big_data_test.table_with_pk_for_load_100M(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

10亿表schema：
create table  if not exists big_data_test.table_with_pk_for_load_1B(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);
```

**Comment by Ariznawlll** [comment]
another problem，load data from cos，vector列报错：
<img width="1501" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a9afaf1b-0a6f-49fb-b00c-b591661c224e">
本地单独摘出这条数据，可以插入成功：
<img width="1404" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/822e92e8-0ee3-4939-bdd4-da8f9a4b9f38">

**Comment by heni02** [comment]
定位发现mo select oufile导出时指定封闭符是空enclosed by ''，数据文件中有Unicode字符\u0000，导致再load失败
mysql> select * from table_with_pk_for_load_100M into outfile '/Users/heni/test_data/vetest_out.csv' fields terminated by '|' enclosed by '';
Query OK, 6 rows affected (0.01 sec)
<img width="1400" alt="企业微信截图_a86892ad-9198-41a4-bec1-cfd428993bc7" src="https://github.com/matrixorigin/matrixone/assets/113406637/322100c5-3569-480b-aea0-18d27992465c">

mo select oufile导出时指定封闭符默认是“，再load到mo是成功的
<img width="1412" alt="企业微信截图_7dfcca2f-f95d-4b48-ae0b-59d4810d1e88" src="https://github.com/matrixorigin/matrixone/assets/113406637/c8ce6710-672a-413d-a0bb-95e3d246e7eb">

**Comment by noorall** [comment]
mo_dump在处理enclosed by ''时有问题，enclosed by ''会被处理成byte(0)，导致导出时出现空白符。

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
verified.
