### ISSUE TITLE
[Subtask]: Better/simpler ranges API

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#14473]
### Parent Issue

#14469

### Detail of Subtask

Right now "ranges" is doing too much.   It support a rather complicated, feature rich expression evaluation.   We want to simplify this API to the point that, ranges can only take
0. A simple expression, or
1. An "and" list of simple expressions, or
2. An "or" list of simple expressions,

Each simple expression is a (colid, op, values) triplet.   Colid is the physical column id, mapping col name/position to column id used by ranges should be carried out by compile.

Limited op kind, here is what in my mind,
= a value
IN a list of values
>, >=, <, <=,  a value
between, 2 values
is/isnot null

All value, or values, are constant.    Constant already folded by compile/optimizer.
Ranges should not check/use tabledef, eval expo, etc etc.

This task involves work in compiler side that essentially, perform what the "ranges" do and save the result in those so called vm.Instruction

**Comment by fengttt** [comment]
For composite primary, secondary key, etc, compiler/optmizer should serialize the columns and ranges should just deal with const value.

**Comment by fengttt** [comment]
At most, ranges and blockio should handle a conjunctive or disjunctive normal form.

**Comment by XuPeng-SH** [comment]
done by related pr:
https://github.com/matrixorigin/matrixone/pull/15008
