### ISSUE TITLE
[Bug]: The result of count(split_part(column,str,num)) is not correct.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14479]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5078085cd5049fa721752637eb402902e48b2656

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="760" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2ccde42e-34a2-4033-b337-218b534bb15d">

### Expected Behavior

<img width="706" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a93d30a1-6cc7-4c59-80d6-1aec0d62da0d">

### Steps to Reproduce

```Markdown
ddl:
create table if not exists big_data_test.table_basic_for_load_100M(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_100M fields terminated by '|' lines terminated by '\n' parallel 'true';

select count(split_part(col11,'a',2)) from big_data_test.table_basic_for_load_100M;
select count(split_part(col17,'a',2)) from big_data_test.table_basic_for_load_100M;
```

**Comment by aronchanisme** [comment]
Could you please kindly help take a look? Thanks.

**Comment by zengyan1** [comment]
无进展

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
commit id：ead69b441080825781ba62c0bc886f4f4b9f9ac5
测试结果：
<img width="714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8c6673c7-f16c-4cfa-9200-3807f82ea88e">

**Comment by zengyan1** [comment]
等待合入

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
fixed.
