### ISSUE TITLE
[Bug]: load data infile which is gzip compression reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14485]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

32a05ab7000d1206a5c70aa036bf4a2d4f39e207

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

使用tar -czf 压缩的gzip文件：10000000_200_columns_load_data.tar.gz加载报错ERROR 1690 (HY000): data out of range: data type int8, value '10000000_200_columns_load_data.csv，但使用gzip命令压缩的文件10000000_200_columns_load_data.csv.gz加载是成功的
<img width="1373" alt="企业微信截图_1c2ad6d7-e454-4f5c-9d57-70c2e39a6e94" src="https://github.com/matrixorigin/matrixone/assets/113406637/fbf93b4d-fddf-4737-8e71-f849b32b8192">

<img width="804" alt="企业微信截图_58f17e6a-5a24-4fa2-ab72-82819422174e" src="https://github.com/matrixorigin/matrixone/assets/113406637/b66bbf54-085d-4ce4-9da6-298a350890e8">

如果两种压缩没有区别的话，预期结果都应该load成功，否则报错不支持该类型压缩格式

### Steps to Reproduce

```Markdown
使用tar -czf xxx.tar.gz filename压缩文件，然后load
```

**Comment by heni02** [comment]
<img width="873" alt="企业微信截图_37632e15-3f38-47f3-bd75-5496c6672e01" src="https://github.com/matrixorigin/matrixone/assets/113406637/d4191500-378e-463d-8f60-835e85326c4d">
两个压缩方式应该没有区别？

**Comment by noorall** [comment]
tar.*类型的文件会先创建归档，然后根据所选的算法进行压缩。目前mo暂未处理所有.tar.*类型的压缩文件。

**Comment by noorall** [comment]
@heni02 辛苦确认一下压缩文件报错的问题是否解决，tar.*类型的文件麻烦确认一下是否要加这个feature

**Comment by heni02** [comment]
@LiSong0214 tar.*这个压缩格式比较普遍，QA建议支持，麻烦确认下是否要支持

**Comment by LiSong0214** [comment]
我觉得 tar.gzip 确实比较常用，可以开 feature 支持

**Comment by heni02** [comment]
明天验证

**Comment by noorall** [comment]
辛苦@heni02 确认一下

**Comment by heni02** [comment]
main支持了，1.1-dev还没支持 @noorall 
main commit：
mysql> create table table_20_columns_tar(
    -> clo1 tinyint,
    -> clo2 smallint,
    -> clo3 int,
    -> clo4 bigint,
    -> clo5 tinyint unsigned,
    -> clo6 smallint unsigned,
    -> clo7 int unsigned,
    -> clo8 bigint unsigned,
    -> col9 float,
    -> col10 double,
    -> col11 varchar(255),
    -> col12 Date,
    -> col13 DateTime,
    -> col14 timestamp,
    -> col15 bool,
    -> col16 decimal(5,2),
    -> col17 text,
    -> col18 varchar(255),
    -> col19 varchar(255),
    -> col20 varchar(255)
    -> );
Query OK, 0 rows affected (0.03 sec)
mysql> load data infile{"filepath"='/Users/heni/test_data/100w20col.tar.gz','compression'='tar.gz'} into table table_20_columns_tar fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 1050000 rows affected (6.12 sec)
mysql> select * from table_20_columns_tar limit 1;
+------+-------+-------------+----------------------+------+-------+------------+----------------------+--------+--------+--------------------------------------------------------------------+------------+---------------------+---------------------+-------+--------+------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+---------------------------------------------------+
| clo1 | clo2  | clo3        | clo4                 | clo5 | clo6  | clo7       | clo8                 | col9   | col10  | col11                                                              | col12      | col13               | col14               | col15 | col16  | col17                                          | col18                                                  | col19                                                 | col20                                             |
+------+-------+-------------+----------------------+------+-------+------------+----------------------+--------+--------+--------------------------------------------------------------------+------------+---------------------+---------------------+-------+--------+------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+---------------------------------------------------+
|  -88 | -7762 |  -438184221 |  5947829073829997523 |  211 | 55466 |  422147889 | 10173758652700397581 | 6.4599 | 4.5171 | DEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnop                  | 8308-12-23 | 1262-08-23 23:59:59 | 1981-06-15 23:59:59 | true  | 237.98 | ,G;KL/MN?OPQR.STU-_+=VWXYZabcdefg              | =VWXYZabcdef                                           | +=VWXYZabcdefghigklmnop                               | R.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345678 |


1.1-dev commit: 8f340f7c94194033ba7362f584cdd7b1bb43e1c1
mysql> load data infile{"filepath"='/Users/heni/test_data/100w20col.tar.bz','compression'='tar.bz2'} into table table_20_columns_tar fields terminated by ',' lines terminated by '\n' parallel 'true';
ERROR 20101 (HY000): internal error: the compress type 'tar.bz2' is not support now

**Comment by ouyuanning** [comment]
暂定不合到1.1-dev了，看是否先关闭吧

**Comment by heni02** [comment]
closed
