### ISSUE TITLE
[Bug]: Backup Command Fails with is_minio Parameter When Targeting Tencent Cloud COS

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14492]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9426e1c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2024/02/01 00:50:44.660353 +0800","name":"log-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","connection_id":8107,"statement":"backup '2024-02-01 00:27:51' s3option{\"endpoint\"='cos.ap-guangzhou.myqcloud.com',\"region\"='ap-guangzhou',\"access_key_id\"='******',\"secret_access_key\"='******',\"bucket\"='mo-backup-test-1308875761',\"filepath\"='backup/',\"compression\"='',\"role_arn\"='',\"is_minio\"='false'}","status":"fail","error":"internal error: bad s3 config: operation error S3: HeadBucket, https response error StatusCode: 403, RequestID: NjViYTdhNjRfNDQxMTdlMWVfMTZlNGRfNTRlNjZlYg==, HostID: , api error Forbidden: Forbidden","span":{"trace_id":"c39093dd-03e5-a732-2fba-cdbd673aa616","span_id":"da1d32cf2fd146fd"},"session_info":"connectionId 8107|127.0.0.1:54701|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 1017|018d606e-058c-70c9-a0ae-f85c0ec6b4cd","session_id":"018d606e-058c-70c9-a0ae-f85c0ec6b4cd","statement_id":"018d606e-0596-7a96-8039-1df6a930a8b8"}

<img width="1469" alt="WeChatWorkScreenshot_1a7f87d6-dd49-4436-a6ec-e4668e944bff" src="https://github.com/matrixorigin/matrixone/assets/77312370/626667cc-3cf6-4728-9eeb-62313ede7b30">

Upon inspecting the logs, it became evident that the backup command execution with the is_minio parameter led the process into the logic branch where MINIO is True, which in turn caused the failure. Interestingly, when the is_minio parameter is removed from the command, the backup operation to Tencent Cloud COS executes successfully without any issues. 

### Steps to Reproduce

```Markdown
start mo locally

execute: `backup '2024-02-01 00:27:51' s3option{\"endpoint\"='cos.ap-guangzhou.myqcloud.com',\"region\"='',\"access_key_id\"='******',\"secret_access_key\"='******',\"bucket\"='mo-backup-test-1308875761',\"filepath\"='backup/',\"compression\"='',\"role_arn\"='',\"is_minio\"='false'}`
```

**Comment by YANGGMM** [comment]
https://github.com/LeftHandCold/matrixone/pull/52
需要测试一下

**Comment by aronchanisme** [comment]
待复测
