### ISSUE TITLE
[Bug]: Performance of GetUnionallFunction, BuildVarlenaFromVarlena,

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#14505]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

060f904

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For varlena type, this function will copy one by one.   During this process, we keep on extend the area that holds the varlena data.    This is extremely slow.

Extend the area by one shot.

### Expected Behavior

Extend area by one shot.    Eliminate everything under vector. GetUnionAllFunction.func22
<img width="1606" alt="Screenshot 2024-02-01 at 9 10 51 AM" src="https://github.com/matrixorigin/matrixone/assets/169294/4e0ad749-299d-4d8c-a7a8-d947fc629459">

### Steps to Reproduce

```Markdown
profiling a simple select query with a varchar(200) column
```

**Comment by fengttt** [comment]
A Quick Look at the code seems to say we just do one allocation, extends.    So this may not be a problem of the UnionAll function.   It is inherent in the data copy cost.    Therefore must be addressed by #14507

**Comment by XuPeng-SH** [comment]
it just does one allocation in the GetUnionallFunction.

**Comment by fengttt** [comment]
So it is data copy cost, not allocation.   Close.
