### ISSUE TITLE
[Subtask]: Assemble value of composite index in query optimizer, just pass simple condition to ranges.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#14515]
### Parent Issue

#14469

### Detail of Subtask

For the case T(a, b, c), index on T(a, b).     select * from T where a=? and b=?.

Query optimizer should call serial(a, b), and pass ranges with one filter expr,   '_hidden_serial_col = const value of serial(a, b)'
Ranges and table reader should never worry about serial.

Note that in prepared statement, const folding need to fold serial(?, ?)

**Comment by aunjgr** [comment]
Feature is implemented.
