### ISSUE TITLE
[Subtask]: blockio.Reader fast path

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#14518]
### Parent Issue

#14469

### Detail of Subtask

Reader should fast path simple expression conditions.   The predicate should really be exactly the same as those get fast pathed in ranges.   #14517 

Esp, for a query like select * from T(a, b) where b = ?,   even if b is not primary key, it must copy AS LITTLE AS possible.

**Comment by fengttt** [comment]
As fast as possible, cannot call getTableDef etc in fast path.

**Comment by XuPeng-SH** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/18650
