### ISSUE TITLE
[Bug]: load data bzip compression file  reported unexpected EOF error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14520]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

32a05ab7000d1206a5c70aa036bf4a2d4f39e207

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

100000000_100_columns_load_data.csv.bz2 size 4.2G, before compression origin csv file is 317G
<img width="525" alt="企业微信截图_38223181-d5c3-4fb4-b605-1b13b4f07f72" src="https://github.com/matrixorigin/matrixone/assets/113406637/ea482d69-8754-4883-b790-80cc0b73ca40">
load data infile 100000000_100_columns_load_data.csv.bz2 error:
<img width="1598" alt="企业微信截图_d207fc3b-17f1-4a33-a447-54e068011839" src="https://github.com/matrixorigin/matrixone/assets/113406637/20856d19-e618-46fd-b61f-bc0c55bbd0b6">

confirm uncompression 100000000_100_columns_load_data.csv.bz2  to csv line is correct
<img width="721" alt="企业微信截图_e4da5d58-e8d7-4474-8089-70d4b4811c0c" src="https://github.com/matrixorigin/matrixone/assets/113406637/e007afbf-3392-47c4-82d9-28291d0f4c0c">

### Steps to Reproduce

```Markdown
create table table_100_columns_bz2( clo1 tinyint, clo2 smallint, clo3 int, clo4 bigint, clo5 tinyint unsigned, clo6 smallint unsigned, clo7 int unsigned, clo8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(5,2), col17 text, col18 varchar(255), col19 varchar(255), col20 varchar(255), col21 varchar(255), col22 varchar(255), col23 varchar(255), col24 varchar(255), col25 varchar(255), col26 varchar(255), col27 varchar(255), col28 varchar(255), col29 varchar(255), col30 varchar(255), col31 varchar(255), col32 varchar(255), col33 varchar(255), col34 varchar(255), col35 varchar(255), col36 varchar(255), col37 varchar(255), col38 varchar(255), col39 varchar(255), col40 varchar(255), col41 varchar(255), col42 varchar(255), col43 varchar(255), col44 varchar(255), col45 varchar(255), col46 varchar(255), col47 varchar(255), col48 varchar(255), col49 varchar(255), col50 varchar(255), col51 varchar(255), col52 varchar(255), col53 varchar(255), col54 varchar(255), col55 varchar(255), col56 varchar(255), col57 varchar(255), col58 varchar(255), col59 varchar(255), col60 varchar(255), col61 varchar(255), col62 varchar(255), col63 varchar(255), col64 varchar(255), col65 varchar(255), col66 varchar(255), col67 varchar(255), col68 varchar(255), col69 varchar(255), col70 varchar(255), col71 varchar(255), col72 varchar(255), col73 varchar(255), col74 varchar(255), col75 varchar(255), col76 varchar(255), col77 varchar(255), col78 varchar(255), col79 varchar(255), col80 varchar(255), col81 varchar(255), col82 varchar(255), col83 varchar(255), col84 varchar(255), col85 varchar(255), col86 varchar(255), col87 varchar(255), col88 varchar(255), col89 varchar(255), col90 varchar(255), col91 varchar(255), col92 varchar(255), col93 varchar(255), col94 varchar(255), col95 varchar(255), col96 varchar(255), col97 varchar(255), col98 varchar(255), col99 varchar(255), col100 varchar(255) ); 

insert sql plz connect me
```

**Comment by noorall** [comment]
定位发现该错误由bzip2的Reader抛出，原因是在读取改文件的bzip2FinalMagic时出错

**Comment by noorall** [comment]
复测文件无法解压，是压缩文件本身的问题。
<img width="1073" alt="image" src="https://github.com/matrixorigin/matrixone/assets/30954408/9cc0c7e3-1ac2-4acc-8b62-fd2b6a2f17e1">

**Comment by heni02** [comment]
等待验证

**Comment by heni02** [comment]
该文件较大，复现耗时，试了小的文件，load成功
mysql> create table table_bzip2(char_1 char(20),char_2 varchar(10),date_1 date,date_2 datetime,date_3 timestamp);
Query OK, 0 rows affected (0.04 sec)
mysql> load data infile '/Users/heni/test_data/ex_table_bzip.bz2' into table table_bzip2 fields terminated by ',' enclosed by '\"' lines terminated by '\n';
Query OK, 3 rows affected (0.03 sec)

mysql> select * from table_bzip2;
+--------------+---------------+------------+---------------------+---------------------+
| char_1       | char_2        | date_1     | date_2              | date_3              |
+--------------+---------------+------------+---------------------+---------------------+
| cat          | yellow 芝士   | 2020-10-09 | 0001-01-01 00:00:00 | 1970-01-01 00:00:01 |
| 123木头人    | zt@126.com    | 1000-01-01 | 9999-12-31 00:00:00 | 2038-01-19 03:14:08 |
| abc$%*()#$   | ttttt         | 9999-12-31 | 2019-10-23 23:00:09 | 2030-01-01 03:14:08 |
+--------------+---------------+------------+---------------------+---------------------+
3 rows in set (0.02 sec)
