### ISSUE TITLE
[Bug]: file xxx is not found after killing mo and restart on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14529]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b009d8d4369075f6088f89588f9f62e0044e13ce

### Other Environment Information

```Markdown
- Hardware parameters: 64C  256G
- OS type:
- Others:
```

### Actual Behavior

after kill -9 mo, and restart, the mo can not login successfully, and report error:
[sudong@mo-srv-129 main]$ mysql -h 127.0.0.1 -u dump -p111 -P6001
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 20405 (HY000): file 018d71e6-733b-7744-a953-13589b8d01e4_00000 is not found

and serveral minutes later, the mo crashed by :
{"level":"INFO","time":"2024/02/04 11:01:12.159587 +0800","name":"cn-service","caller":"logutil/action.go:52","msg":"async task exited","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","action":"run-async-task","async-task":"cnservice/wait-system-init-task","cost":"5m0.708387326s"}
panic: wait system init timeout

goroutine 1295 [running]:
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).waitSystemInitCompleted(0xc018cf4000, {0x4502ff0, 0xc00b075c50})
        /data1/sudong/matrixone-1.2/matrixone/pkg/cnservice/server_task.go:287 +0x565
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /data1/sudong/matrixone-1.2/matrixone/pkg/common/stopper/stopper.go:263 +0x6e
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 850
        /data1/sudong/matrixone-1.2/matrixone/pkg/common/stopper/stopper.go:258 +0xd6

mo-log:
[mo-service.log](https://github.com/matrixorigin/matrixone/files/14155302/mo-service.log)

### Steps to Reproduce

```Markdown
1. run mo server on standlone mode 
2. load some data
3. kill -9 mo service
4. restart mo service
```

**Comment by triump2020** [comment]
no repro

**Comment by triump2020** [comment]
no repro

**Comment by triump2020** [comment]
@aressu1985  Pls downgrade it to S1

**Comment by triump2020** [comment]
no repro

**Comment by XuPeng-SH** [comment]
@LeftHandCold

**Comment by LeftHandCold** [comment]
这个没有什么有价值的分析信息，1.2的GC逻辑已经全部修改了，观察不出现是否可以关闭 @aressu1985

**Comment by aressu1985** [comment]
关闭，以后遇到，重新提
