### ISSUE TITLE
[Bug]: Load1 billion rows of data from S3 has not been completed for more than 5 hours

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#14536]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2e36b32e2c3a39a560a1db73e670ccd98bf7a3d7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

数据量：10亿
原table schema:
create table  if not exists big_data_test.table_basic_for_alter_1B(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

mysql>load data url s3option {'endpoint'='******','access_key_id'='******','secret_access_key'='******','bucket'='******', 'filepath'='mo-big-data/1000000000_20_columns_load_data_new.csv','region'='ap-guangzhou'} into table big_data_test.table_basic_for_alter_1B fields terminated by '|' lines terminated by '\n' ignore 1 lines parallel 'true';

### Steps to Reproduce

```Markdown
数据量：10亿
原table schema:
create table  if not exists big_data_test.table_basic_for_alter_1B(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);


load data url s3option {'endpoint'='******','access_key_id'='******','secret_access_key'='******','bucket'='******', 'filepath'='mo-big-data/1000000000_20_columns_load_data_new.csv','region'='ap-guangzhou'} into table big_data_test.table_basic_for_alter_1B fields terminated by '|' lines terminated by '\n' ignore 1 lines parallel 'true';
```

**Comment by xzxiong** [comment]
@ouyuanning 麻烦看看

**Comment by noorall** [comment]
在129做了一次导入测试，时间为：

**Comment by noorall** [comment]
在129服务器闲置的情况下再次进行复测，导入时间仅为1小时20分钟左右，与1.1分支的测试结果接近。超过五小时

<img width="1332" alt="image" src="https://github.com/matrixorigin/matrixone/assets/30954408/42a2f132-68d4-4faa-8fe7-9f649bbe3015">

**Comment by noorall** [comment]
麻烦确认一下。 @qingxinhome

**Comment by qingxinhome** [comment]
Understood, to be verified

**Comment by qingxinhome** [comment]
Understood, to be verified

**Comment by qingxinhome** [comment]
Understood, to be verified
