### ISSUE TITLE
[Bug]: [DAILY REGRESSION]Duplicate entry '50464' for key 'id' during sysbench write_only  cases on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14548]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

713c7c24fc3351b952aa9aae0e4e63d50d2d841c

### Other Environment Information

```Markdown
- Hardware parameters: 64C 256G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7774712562/job/21199875947

when running sysbench write_only  cases on standlone mode, the mo return errors:
<img width="1326" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/dca929b7-d8e0-4460-a3e1-ec1b31e4f53d">

but for write_only_case, there should nerver be dup, the txn is:
begin;
UPDATE sbtest%u SET k=k+1 WHERE id=?
UPDATE sbtest%u SET c=? WHERE id=?

--value of id in delete and insert is the same
DELETE FROM sbtest%u WHERE id=?
INSERT INTO sbtest%u (id, k, c, pad) VALUES (?, ?, ?, ?)
comimt;

mo-log:

[dup.tar.gz](https://github.com/matrixorigin/matrixone/files/14160253/dup.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo on standlone mode
2. create database sysbench_db
3. git clone https://github.com/matrixorigin/mo-sysbench.git
4. prepare data
   sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10   --auto_inc=off prepare
5. run write_only test
   sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable --mysql-ignore-errors=20701 oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=300 --report-interval=10   --auto_inc=off  --range_selects=off --point_selects=1 run
```

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
等罗飞那边的处理

**Comment by qingxinhome** [comment]
等罗飞那边的处理

**Comment by qingxinhome** [comment]
等罗飞那边的处理

**Comment by qingxinhome** [comment]
The issue has been resolved by @triump2020 , please verify and test it @aressu1985 @ouyuanning @daviszhen

**Comment by aressu1985** [comment]
fixed

**Comment by heni02** [comment]
date 4.28 standalone regression repro this issue
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8868258585/job/24347682361
<img width="1228" alt="企业微信截图_e802ce54-4986-4231-9703-ebe9f2cc7e3f" src="https://github.com/matrixorigin/matrixone/assets/113406637/b2c01b3b-cbbb-4e91-82a7-63c2e419ed7e">

log:
文件较大，私发开发定位

**Comment by triump2020** [comment]
原因如下:  
  1.  txn1 在CN1 上insert 了 一条 PK, 并committed.   2.  CN2 上的txn2  还未等到 这个pk 同步到partition state 中，就开始 运行 delete pk(delete statment 的snapshot ts 应该是小于txn1 的commit ts 的, 否则CN2 会等water mark 超过txn1 的commit ts ) ， 这时pk 的rowid 查不到，delete 运行之后，affected rows =0， 相当于delete 没起效果; 然后运行 insert pk , 去重时，之前被txn1 提交的pk 同步过来了，然后在partiton state 中发现了相同的pk , 导致dup.

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15948

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992 fixed dup/ww bug.

**Comment by triump2020** [comment]
wait for @ouyuanning 's pr

**Comment by triump2020** [comment]
继续观察

**Comment by triump2020** [comment]
单机Dup WW 应该没有了，继续观察中

**Comment by triump2020** [comment]
@aressu1985  单机没发现 dup /ww 了 ，可以关了?

**Comment by aressu1985** [comment]
fixed
