### ISSUE TITLE
[Bug]: [regression 2.7] internal error: send notify msg to dispatch operator timeout during tpch 1T queries and TPCH cost increaseed more than 25%

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14559]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4b2ee6c34

### Other Environment Information

```Markdown
- Hardware parameters: 
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7801301851/job/21277520634

error:

<img width="1261" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/96bb9ea2-44ea-4104-a485-6b742ca8bb2e">

queries cost increased:
<img width="1341" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b3e3064b-9653-4c71-bd36-078e043b95b6">

mo-log:
http://175.178.192.213:30088/explore?panes=%7B%22YK6%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240206%5C%22%7D%20%7C%3D%20%60internal%20error:%20send%20notify%20msg%20to%20dispatch%20operator%20timeout%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221707237052769%22,%22to%22:%221707271626517%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run TPCH 1T queries
```

**Comment by badboynt1** [comment]
fixed

**Comment by aressu1985** [comment]
fixed

**Comment by heni02** [comment]
date 2.22 regression reproduce 
<img width="1208" alt="企业微信截图_3ca0f80b-05c5-44cd-a85b-6d69741807c2" src="https://github.com/matrixorigin/matrixone/assets/113406637/34f3c8a3-b9c3-4e8c-af1e-766c6853ed57">
<img width="1409" alt="企业微信截图_6031a4f7-0157-47d3-bfd8-64c342828eb3" src="https://github.com/matrixorigin/matrixone/assets/113406637/181b6e0a-7434-436a-a82b-311433b8a0b2">
mo log：
http://175.178.192.213:30088/explore?panes=%7B%22Owe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240221%5C%22%7D%20%7C%3D%20%60send%20notify%20msg%20to%20dispatch%20operator%20timeout%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708536451000%22,%22to%22:%221708597372000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by badboynt1** [comment]
等待二分结果

**Comment by badboynt1** [comment]
已经定位到原因是90ee28372adef5f8dbc49aba8400d55473ca5b5c 这个commit。  具体原因正在分析中。

**Comment by badboynt1** [comment]
已经找到具体原因 一个字段修改错了。麻烦改一下   @volgariver6

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
testing
