### ISSUE TITLE
[Bug]: [regression 2.6] w-w confict during tpcc 100warehouse test(occasionally) on standlone mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14562]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

955845b2990f859a56dd1e9e5c7c875f140c0b38

### Other Environment Information

```Markdown
- Hardware parameters: 64C 256G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7785960736/job/21229834266
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/7801187475/job/21275854681

<img width="1349" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ebd65b77-5d8e-4bd1-8fd4-3a417dbd5b4a">

<img width="1345" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/218b37f4-a928-4cb4-ac8c-7a1da8fd516d">

mo-log:
[tpcc-w-w.tar.gz](https://github.com/matrixorigin/matrixone/files/14188359/tpcc-w-w.tar.gz)

### Steps to Reproduce

```Markdown
1.run tpcc 100-1000 warehouse test, maybe can repros this
```

**Comment by triump2020** [comment]
blocked by vacation

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
Delaying call to `ranges`  leads to `Dup`

**Comment by triump2020** [comment]
Latest main branch reprodeced again, being fix.

**Comment by triump2020** [comment]
目前只在长期分布式稳定性中出现

**Comment by heni02** [comment]
date 4.11 standalone regression sysbench 1000w也出现该错误
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8648370711/job/23712181777
<img width="1136" alt="企业微信截图_5911a8b2-b98a-4dd8-90ca-50de0914b535" src="https://github.com/matrixorigin/matrixone/assets/113406637/8334345c-1cad-4d23-abed-8b186f46e9bf">

mo log 已经发给 @triump2020 定位

**Comment by triump2020** [comment]
![企业微信截图_17128905426643](https://github.com/matrixorigin/matrixone/assets/63033222/934dbf49-5e64-406a-9232-87b0c892be44)

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15545

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15731

**Comment by triump2020** [comment]
原因如下:  1.  txn1 在CN1 上insert 了 一条 PK, 并committed.   2.  CN2 上的txn2  还未等到 这个pk 同步到partition state 中，就开始 运行 delete pk(delete statment 的snapshot ts 应该是小于txn1 的commit ts 的, 否则CN2 会等water mark 超过txn1 的commit ts ) ， 这时pk 的rowid 查不到，delete 运行之后，affected rows =0， 相当于delete 没起效果; 然后运行 insert pk , 去重时，之前被txn1 提交的pk 同步过来了，然后在partiton state 中发现了相同的pk , 导致dup.

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992 fixed dup/ww bug.

**Comment by triump2020** [comment]
wait for @ouyuanning 's pr

**Comment by triump2020** [comment]
Dup and WW are unexpected now on standalone,  maintaining Observation.

**Comment by triump2020** [comment]
单机Dup WW 应该都没有了，继续观察

**Comment by triump2020** [comment]
@aressu1985   单机没发现有WW 了 ，关了?
