### ISSUE TITLE
[Bug]: DATA RACE detected in bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14573]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

608b970

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="984" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/0cde58d1-3bc6-4979-b0ff-39805a04f3cc">
https://github.com/matrixorigin/matrixone/actions/runs/7796998586/job/21263180818?pr=14545

[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/14231376/multi-cn-e2e-with-race-linux-x86-reports.zip)

### Steps to Reproduce

```Markdown
run bvt with race enabled
```

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/7955951041/job/21716568548

**Comment by sukki37** [comment]
repro in 1.1: https://github.com/matrixorigin/matrixone/actions/runs/7967197503

**Comment by Morranto** [comment]
分析代码中

**Comment by Morranto** [comment]
已提pr

**Comment by heni02** [comment]
confirm，closed
https://github.com/matrixorigin/matrixone/actions/runs/8058865404/job/22012916523
