### ISSUE TITLE
[Bug]: dn crash by segmentation violation during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14576]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

da6ff0a

### Other Environment Information

```Markdown
- Hardware parameters: 
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, the dn crash by :
{"level":"ERROR","time":"2024/02/14 07:57:44.376320 +0000","caller":"jobs/flushTableTail.go:198","msg":"[DoneWithErr]","operation":"[14495]FT-272535-metric","error":"operation error S3: PutObject, https response error StatusCode: 400, RequestID: 17B3ABAF988E28A0, HostID: d4396cded8af24d6a78f8e9368e2947a48b5d4e31060107fc9a7daf084aa726d, api error XMinioAdminBucketQuotaExceeded: Bucket quota exceeded","phase":"1-merge ablocks"}
{"level":"WARN","time":"2024/02/14 07:57:44.376467 +0000","caller":"db/task.go:66","msg":"Task[14493] exec error: operation error S3: PutObject, https response error StatusCode: 400, RequestID: 17B3ABAF988E28A0, HostID: d4396cded8af24d6a78f8e9368e2947a48b5d4e31060107fc9a7daf084aa726d, api error XMinioAdminBucketQuotaExceeded: Bucket quota exceeded"}
{"level":"INFO","time":"2024/02/14 07:57:45.318714 +0000","caller":"checkpoint/runner.go:933","msg":"[flushtabletail] statement_info(2.09GB) 68.25KB dels  FlushCountDown 4m30.510894938s"}
{"level":"INFO","time":"2024/02/14 07:57:45.318800 +0000","caller":"checkpoint/runner.go:941","msg":"[flushtabletail] force flush statement_info"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1ae79ed]

goroutine 880 [running]:
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Length(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:135
github.com/matrixorigin/matrixone/pkg/objectio.(*objectWriterV1).addBlock(0xc68df33b00, 0xc0a3e8c660, {0xc1fe9be000, 0x0?, 0x683}, 0xc5c3c9a200, 0xc29734a540)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/writer.go:597 +0x1ad
github.com/matrixorigin/matrixone/pkg/objectio.(*objectWriterV1).AddBlock(0xc68df33b00, {0xc1fe9be000, 0x683, 0x683}, 0x5?, 0xc646053c50?)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/writer.go:636 +0xd7
github.com/matrixorigin/matrixone/pkg/objectio.(*objectWriterV1).Write(0xc68df33b00, 0xc5c3c9a200)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/writer.go:181 +0xa5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.(*BlockWriter).WriteBatch(0xc887bc2cc0, 0xc5c3c9a200)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio/writer.go:91 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*flushBlkTask).Execute(0xc1737ccc40, {0x42ee1d8, 0xc001caf050})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs/flushblk.go:94 +0x27a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc08bfe1180, {0x42ee1d8, 0xc001caf050})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:103 +0x88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc001a95e80, {0x7f517c167fa8, 0xc1737ccc40})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:210 +0x3d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:142 +0xc2
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:134 +0xb7

mo-log:
[dn-crash-segmentation.log](https://github.com/matrixorigin/matrixone/files/14276817/dn-crash-segmentation.log)

### Steps to Reproduce

```Markdown
1. run the folloing test load on disributed mo:
   tpch 10G loop quries in a tannet 
   tpcc 100-100 longrunning test in a tannet
   two sysbencn mixed case longrunning tests in in two tannets
```

**Comment by LeftHandCold** [comment]
operation error S3: PutObject, https response error StatusCode: 400, RequestID: 17B437B56F47529B, HostID: ac6d709dce9d2454a5c6f21ab2276d9a595853c642914681d9333c462cec63c2, api error XMinioAdminBucketQuotaExceeded: Bucket quota exceeded

**Comment by aptend** [comment]
修改中

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
