### ISSUE TITLE
[Bug]: txn dumpBatchLocked use 0 as marker for full dump.  0 is a valid value, should use -1.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#14587]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

HEAD

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Use -1, or better a constant or something, maybe even two functions.
 

### Steps to Reproduce

```Markdown
reading code.
```

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by aressu1985** [comment]
fixed
