### ISSUE TITLE
[Bug]: select outfile json type include " which enclosed by ''  

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14601]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a6e7ae3b1b03946fa04ba4679bda3951cc0b830d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select outfile 指定封闭符为空enclosed by ''，导出文件中json类型封闭符还是"，虽然该文件再次导入mo可以成功，但导入其他数据库数据显示错误，故预期json类型导出文件需去掉"。
<img width="1730" alt="企业微信截图_2e28109e-c24f-4459-b728-503003080169" src="https://github.com/matrixorigin/matrixone/assets/113406637/45f0eaac-d187-4b9d-893b-58cdd3167239">

该导出文件再导入mo可成功
<img width="1743" alt="企业微信截图_90e1c4cf-f7db-4a62-9892-c2270eaa6f06" src="https://github.com/matrixorigin/matrixone/assets/113406637/0787f167-7049-49b6-ba3e-d66dcb93bf49">

但导入其他数据库，比如doris，导入成功数据显示有误
<img width="1733" alt="企业微信截图_8ccccb04-3af1-495d-ab61-9eff3f5b4c4e" src="https://github.com/matrixorigin/matrixone/assets/113406637/faa32e9a-9e49-47ce-a103-b860fb1223dc">
文件中去掉" ，doris load成功
<img width="1712" alt="企业微信截图_468f1cbd-a849-4a82-9237-3650f885c384" src="https://github.com/matrixorigin/matrixone/assets/113406637/1ca19e42-7daa-4b75-9a8e-ccedb9a84170">
<img width="1739" alt="企业微信截图_ff2da71f-1e9e-4864-a977-c92718d6a097" src="https://github.com/matrixorigin/matrixone/assets/113406637/94d09a7e-bb5b-44cb-8837-60adfd9cf92f">

### Steps to Reproduce

```Markdown
select * from table_with_pk_for_load_100m into outfile '/test/1000000000_20_columns_load_data_pk.csv'  fields terminated by '|' enclosed by '';
```

**Comment by aronchanisme** [comment]
related issue: https://github.com/matrixorigin/MO-Cloud/issues/2532

**Comment by noorall** [comment]
与这一更改关联的历史issue：https://github.com/matrixorigin/matrixone/pull/10838

**Comment by heni02** [comment]
confirm,closed
commit:0c35ffc6a974badbbccfd7f20d6494ba27e69819
mysql> create table temp(c1 int,c2 json);
Query OK, 0 rows affected (0.05 sec)
mysql> insert into temp values(1,'{"a":"23"}'),(2,'{"b":"45"}'),(3,'{"c":"66"}');
Query OK, 3 rows affected (0.03 sec)
mysql> select * from temp;
+------+-------------+
| c1   | c2          |
+------+-------------+
|    2 | {"b": "45"} |
|    3 | {"c": "66"} |
|    1 | {"a": "23"} |
+------+-------------+
3 rows in set (0.00 sec)
mysql> select * from temp into outfile '/Users/heni/test_data/temp.csv' fields terminated by '|' enclosed by '';
Query OK, 3 rows affected (0.01 sec)
temp.csv:
<img width="282" alt="企业微信截图_1af57ded-5071-4a5b-8131-28d1f1eada7f" src="https://github.com/matrixorigin/matrixone/assets/113406637/d5d4dbd1-b218-47d1-ae28-751053dbec4f">
