### ISSUE TITLE
[Bug]: The expression for pk filter can be wrong in some scenarios

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#14600]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e613f9588

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1066" alt="企业微信截图_132690c0-88c5-4d52-a873-117244cff56a" src="https://github.com/matrixorigin/matrixone/assets/56761542/45e524d1-9d56-4be0-8d6d-7445733b6e4e">

### Expected Behavior

insert values的属性无论是否有序, pkfilter的表达式应该等价

### Steps to Reproduce

```Markdown
insert values的时候逆序插入
```

**Comment by jensenojs** [comment]
在重构insert相关代码中解决

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
upstream/main : 

<img width="1205" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/1968c1dd-6328-4d69-ac01-13c9d7d4cac0">

本commit : 
<img width="1299" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/1d3da6f8-3350-4c46-a946-f6e7770a9e4a">

**Comment by jensenojs** [comment]
相关pr已经合并, 辛苦QA @Ariznawlll  验证一下

关于bvt增加insert test的补充建议, 后续我或者是测试可以再加点

```sql
create table t (a, b, c, d, primary key(c, d, a));
insert into t(d, b, a, c) values (4, 2, 1, 3);
```
有三个顺序需要关注
- tableDef中的Cols的顺序 : a, b, c, d
- primary key的定义顺序 : c, d, a
- insert values 的属性顺序 : d, b, a, c

这几个顺序没有相互依赖, 并且彼此的顺序完全可能是乱的, 目前测试没有覆盖到上面的场景.

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**修之前在乱序的情况下，过滤条件是错的，会导致有的块没读上来。修之后，会根据过滤条件把实际上要读上来做重复检测的块读出来。**
table schema：
<img width="456" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0ebaa21b-0f0a-4871-880b-5139ba52cc61">

<img width="531" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5b8670e9-ec63-4361-8702-bd73db64d851">
