### ISSUE TITLE
[Bug]: memory leak detected during bvt test with race enabled

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14608]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6e6302c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1412" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/658fb010-8992-40ec-b629-eeecf8f266d7">

https://github.com/matrixorigin/matrixone/actions/runs/7947806310/job/21697442017

### Steps to Reproduce

```Markdown
1. make debug
2. start mo
3. run bvt
```

**Comment by gouhongshen** [comment]
same as https://github.com/matrixorigin/matrixone/issues/14085
