### ISSUE TITLE
[Bug]: A strange output after inserting '\r\n' into string

### ISSUE THREAD

**Issue by zengyan1** [matrixorigin/matrixone#14619]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

30a7e7a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="395" alt="企业微信20240221-145616@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/0c730467-dddf-446c-b5fe-3046298f1be2">

### Expected Behavior

a        b
0        \r
1        
2        \n

### Steps to Reproduce

```Markdown
create table t(a int ,b varchar(8));
insert into t values(0,'\r');
insert into t values(1,'');
insert into t values(2,'\n');
select * from t;
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by sukki37** [comment]
<img width="645" alt="image" src="https://github.com/user-attachments/assets/486e072c-d8c9-4f7d-825f-a7e892274469">

The behavior of `mo` is consistent with `MySQL`. This issue seems inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
