### ISSUE TITLE
[Bug]: after insert transaction, truncate table not wait lock release

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14633]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

90ee28372adef5f8dbc49aba8400d55473ca5b5c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo ：
<img width="621" alt="企业微信截图_aa76d4e0-d578-41a7-9de9-451d05ecdee3" src="https://github.com/matrixorigin/matrixone/assets/113406637/a16471bd-8b67-4e3c-822d-81f772a82e32">
<img width="846" alt="企业微信截图_f2f2c901-b591-42a7-898f-7474c1c1463a" src="https://github.com/matrixorigin/matrixone/assets/113406637/fb15cadd-bd4f-42ee-8e27-a8866711e260">

but mysql rr and rc isolation ，truncate table wait lock release 
<img width="521" alt="企业微信截图_88fc32dc-786c-43a9-8548-5f938f56e3cc" src="https://github.com/matrixorigin/matrixone/assets/113406637/96a3dbcc-b48f-4beb-98d9-8281c293540e">
<img width="645" alt="企业微信截图_243ce9dc-7ee8-4480-9b7f-fba95661cdb1" src="https://github.com/matrixorigin/matrixone/assets/113406637/438f628d-aa49-4d6f-b2cd-1bf75dd10e09">
<img width="827" alt="企业微信截图_90c4e98a-cd8c-498b-9929-b0100b0a07d6" src="https://github.com/matrixorigin/matrixone/assets/113406637/27188a0b-cf4a-4b63-805f-74e26e8ff027">

### Steps to Reproduce

```Markdown
create table t1(a int);
begin;
insert into t1 values (1);
select * from t1;
-- @session:id=1{
use drop_table_truncate;
truncate table t1;
select * from t1;
-- @session}
select * from t1;
commit;
```

**Comment by ouyuanning** [comment]
create table t1(a int);     // table without pk,  can not lock
create table t1(a int primary key);  // table with pk, that will be fine

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by iamlinjunhong** [comment]
暂无进度

**Comment by aressu1985** [comment]
@iamlinjunhong 这个目前什么进展？

**Comment by iamlinjunhong** [comment]
已知问题，正在处理

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
符合预期， 事务隔离级别为 rc，事务 a insert 1，实际上在 事务a 提交之前 事务b是看不到的，所以 truncate 不需要等待。

**Comment by ouyuanning** [comment]
感觉这个本质是 truncate 是否是DDL类语句的问题。
也就是 truncate是 delete from t1还是  drop table t1, create table t1的问题。

如果是 delete from t1的语义，那么新insert的本来就看不到，不需要所。
如果是drop table t1... 的话，那么要上排它锁也无可厚非。

感觉可以让田博士和高老师看看

**Comment by heni02** [comment]
需确实是否修改该行为

**Comment by xzxiong** [comment]
note: 当做 drop table 等同加锁。

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
把 truncate 做ddl后，bvt 有先问题，正在处理

**Comment by iamlinjunhong** [comment]
{"level":"WARN","time":"2024/11/14 02:59:41.181529 +0000","name":"cn-service.lockservice","caller":"lockservice/waiter_events.go:252","msg":"wait too long","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","wait":"1m5.949435816s","key":"46013e14460164726f705f7461626c655f7472756e6361746500ff46016469735f7461626c655f303300ff00","bind":"0-6478595177531242911(6478595177531242911)-1731552640979909784dd1dccb4-4d3c-41f8-b482-5251dc7a41bf-1731552636953302736","lock":"Shared(row): holder(70f70f4866a9b62a1807b5f3ebac0a38), waiters(70f70f4866a9b62a1807b5f3ebac0a42-0xc02f94e370(4))","txn":"70f70f4866a9b62a1807b5f3ebac0a42"}



2024/11/14 03:00:40.985726 +0000 ERROR cn-service found leak txn {"uuid": "", "txn-id": "70f70f4866a9b62a1807b5f3ebac0a38", "create-at": "2024/11/14 02:58:35.220910 +0000", "options": "Features:1 CN:\"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf\" SessionID:\"01932894-9283-76c2-ac51-48ac8cbf3141\" ConnectionID:5 UserName:\"dump\" counter:\"commit: enter:0, exit:0 rollback: enter:0, exit:0 runSql: enter:2, exit:2 incrStmt: enter:2, exit:2 rollbackStmt: enter:1, exit:1 footPrints: [0: enter:4, exit:5] [1: enter:4, exit:5] [2: enter:2, exit:3] [4: enter:2, exit:3] [6: enter:2, exit:2] [7: enter:2, exit:2] [8: enter:2, exit:2] [11: enter:2, exit:3] [12: enter:2, exit:3] [13: enter:2, exit:2] [14: enter:2, exit:2] [15: enter:2, exit:2] [16: enter:2, exit:2] [84: enter:1, exit:1] [85: enter:2, exit:2] [86: enter:3, exit:3] [87: enter:2, exit:2] [92: enter:12, exit:12] [93: enter:11, exit:11] [94: enter:1, exit:1] [95: enter:11, exit:11] [99: enter:1, exit:1] [101: enter:1, exit:1] [102: enter:1, exit:1] [107: enter:1, exit:1] [110: enter:1, exit:1] [115: enter:11, exit:11] \" sessionInfo:\"connectionId 5|127.0.0.1:36152|account sys:dump|goRoutineId 1967|migrate-goRoutineId 0|01932894-9283-76c2-ac51-48ac8cbf3141\" byBegin:true autocommit:true ", "profile": "ETL:/profile/CN_dd1dccb4-4d3c-41f8-b482-5251dc7a41bf_leakcheck_routine_0193289d-a799-79b4-952a-b180a863415d.gz"}

**Comment by iamlinjunhong** [comment]
70f70f4866a9b62a1807b5f3ebac0a42 在等 70f70f4866a9b62a1807b5f3ebac0a38 ， 70f70f4866a9b62a1807b5f3ebac0a38 事务泄漏导致超时
<img width="2318" alt="截屏2024-11-14 12 09 00" src="https://github.com/user-attachments/assets/95131ef1-07f7-4cf2-845a-468488b3420a">

**Comment by heni02** [comment]
2.0-dev commit:167a50052b31926989e326ad0c37b90e57438dbf 符合预期
<img width="664" alt="企业微信截图_c6018b3e-179d-4339-b3b0-d06051efa784" src="https://github.com/user-attachments/assets/5687f30c-8a9d-428f-a756-4babc88e51b3">
<img width="789" alt="企业微信截图_ea5420ed-616d-4abe-bfa9-f63e153e79d1" src="https://github.com/user-attachments/assets/e6dedbac-f8c5-414d-af7e-4ca066e5af3b">
<img width="811" alt="企业微信截图_3f1e9c5c-f768-4c91-8aa1-9e3216608878" src="https://github.com/user-attachments/assets/81126320-cb50-4a84-b94e-dd3ab5d3e109">

等待pr合入main验证
