### ISSUE TITLE
[Bug]: [date 2.22]tke regression: sysbench test reported error invalid state txn not found 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14646]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2e670085ae827cae7c590a795fe4fbb9bddcd3fa

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8006144357/job/21886440171
<img width="1400" alt="企业微信截图_a5d74da8-8564-4e41-bf85-405661e8ab9a" src="https://github.com/matrixorigin/matrixone/assets/113406637/320ba669-c114-40c5-bbfc-1a09c8eb09d2">

排除了这个时间点cn crash的因素，所有节点都没有重启过，还需定位下具体原因
log：
http://175.178.192.213:30088/explore?panes=%7B%22OEB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240222%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708644254287%22,%22to%22:%221708644255287%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1389" alt="企业微信截图_abd6649a-59d7-45b7-aa19-2349f6c4d53b" src="https://github.com/matrixorigin/matrixone/assets/113406637/70a7dd75-5ec2-4d77-b3e7-c32799feed45">

### Steps to Reproduce

```Markdown
regression test
```

**Comment by iamlinjunhong** [comment]
因为网络环境原因，remote cn 和 local cn 心跳超时，导致出现孤儿事务，local cn 会清理掉孤儿事务，最终报错 invalid state txn not found。现在超时时间设置为 10s，已经是比较长的时间，不建议设置更大的超时时间，如果这种情况不是经常发生

**Comment by heni02** [comment]
confirm，closed
