### ISSUE TITLE
[Bug]: [date 2.22]standalone regression: mo panic: internal error: driver info: retry time out

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14647]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2e670085ae827cae7c590a795fe4fbb9bddcd3fa

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8006038127/job/21866983369
<img width="1370" alt="企业微信截图_af71f982-4bc4-4e66-8cf5-aacc3e3da7f3" src="https://github.com/matrixorigin/matrixone/assets/113406637/6531c273-4541-421a-a3c8-5f019a4167d0">

log:
{"level":"ERROR","time":"2024/02/23 02:30:37.320814 +0800","name":"log-service","caller":"logservice/store.go:373","msg":"shardID 1 already truncated to index 16184448","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"ERROR","time":"2024/02/23 02:30:37.320947 +0800","caller":"logservice/store.go:374","msg":"error: invalid truncate lsn, shard 1 already truncated to 16184448"}
{"level":"ERROR","time":"2024/02/23 02:30:37.322622 +0800","caller":"logservice/errors.go:91","msg":"error: invalid truncate lsn, shard 0 already truncated to 0"}
{"level":"ERROR","time":"2024/02/23 02:30:37.322791 +0800","name":"hakeeper-client-backend","caller":"morpc/backend.go:568","msg":"read loop stopped","remote":"127.0.0.1:32001","backend-id":"018dd215-7170-71e1-92f5-376886256ab8"}
{"level":"ERROR","time":"2024/02/23 02:30:37.330389 +0800","name":"hakeeper-client-backend","caller":"v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:515","msg":"close conneciton failed","remote":"127.0.0.1:32001","backend-id":"018dd215-7170-71e1-92f5-376886256ab8","session-id":0,"error":"close tcp4 127.0.0.1:60152->127.0.0.1:32001: use of closed network connection"}
{"level":"ERROR","time":"2024/02/23 02:30:37.337166 +0800","name":"logservice-client","caller":"morpc/client.go:397","msg":"gc inactive backends task stopped"}
{"level":"ERROR","time":"2024/02/23 02:30:37.337238 +0800","name":"logservice-client","caller":"morpc/client.go:374","msg":"gc idle backends task stopped"}
{"level":"INFO","time":"2024/02/23 02:30:37.352265 +0800","caller":"logservicedriver/truncate.go:80","msg":"LogService Driver: retry truncate, err is invalid truncate lsn, shard 0 already truncated to 0"}
{"level":"INFO","time":"2024/02/23 02:30:37.352890 +0800","name":"logservice-client","caller":"morpc/client.go:365","msg":"gc idle backends task started"}
{"level":"ERROR","time":"2024/02/23 02:30:37.437529 +0800","name":"log-service","caller":"logservice/store.go:373","msg":"shardID 1 already truncated to index 16184448","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"ERROR","time":"2024/02/23 02:30:37.437672 +0800","caller":"logservice/store.go:374","msg":"error: invalid truncate lsn, shard 1 already truncated to 16184448"}
{"level":"ERROR","time":"2024/02/23 02:30:37.464280 +0800","caller":"logservice/errors.go:91","msg":"error: invalid truncate lsn, shard 0 already truncated to 0"}
{"level":"ERROR","time":"2024/02/23 02:30:37.464478 +0800","name":"hakeeper-client-backend","caller":"morpc/backend.go:568","msg":"read loop stopped","remote":"127.0.0.1:32001","backend-id":"018dd215-7228-7ebb-ad11-3a7780041e60"}
{"level":"ERROR","time":"2024/02/23 02:30:37.472415 +0800","name":"hakeeper-client-backend","caller":"v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:515","msg":"close conneciton failed","remote":"127.0.0.1:32001","backend-id":"018dd215-7228-7ebb-ad11-3a7780041e60","session-id":0,"error":"close tcp4 127.0.0.1:60166->127.0.0.1:32001: use of closed network connection"}
{"level":"ERROR","time":"2024/02/23 02:30:37.482160 +0800","name":"logservice-client","caller":"morpc/client.go:397","msg":"gc inactive backends task stopped"}
{"level":"ERROR","time":"2024/02/23 02:30:37.482256 +0800","name":"logservice-client","caller":"morpc/client.go:374","msg":"gc idle backends task stopped"}
panic: internal error: driver info: retry time out

goroutine 1592 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*LogServiceDriver).truncateLogservice(0xc003f7e370, 0xf6f480)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go:87 +0x23a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*LogServiceDriver).doTruncate(0xc003f7e370)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go:61 +0xbf
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*LogServiceDriver).onTruncate(...)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go:42
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1e5
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 1510
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xe5

log file plz contact to me

### Steps to Reproduce

```Markdown
standalone regression
```

**Comment by volgariver6** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/12221

**Comment by volgariver6** [comment]
close it as it is duplicated with #12221.

**Comment by heni02** [comment]
confirm,closed
