### ISSUE TITLE
[Bug]: [0222] TP performance degradation on 128 and tke regression test. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14649]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

90ee28372adef5f8dbc49aba8400d55473ca5b5c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TP性能下降：
128
<img width="1388" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3477aabf-10ee-40d1-8281-4536bb68f20c">
除了点查，delete、random ranges、read_only、update等均有下降，具体可参考dashboard性能趋势变化图.
url: http://grafana.matrixorigin.cn:31080/d/tTgeED4Ik/sysbench_10w?orgId=1
tke:
<img width="1383" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/47e93e14-79f6-4697-8ef2-bf5156b3a9d4">
除了点查，delete、random ranges、read_only、update等均有下降，具体可参考dashboard性能趋势变化图.
url: http://grafana.matrixorigin.cn:31080/d/tTgeED4Ik12/sysbench_10w?orgId=1

在128上测试了单机sysbench 10w 点查100 threads的结果，二分结果如下：
![wecom-temp-83417-e0ad8b09e88521779855e5b084902e07](https://github.com/matrixorigin/matrixone/assets/108530700/221f1574-3b88-4677-b257-e3f0d52e1bfa)

### Steps to Reproduce

```Markdown
trigger daily regression on 128 and tke.
```

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**2024.02.26
commit id：94f70f2b9b1da4fc83578eac2ba51a4058d4146d
点查10w 100thread以及1000 threads测试结果：**
<img width="1018" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6bce7fb1-1cf3-445e-971d-84ed893402f8">
<img width="1016" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fb2ffbb2-3f5a-4f80-b671-2bd549581f2e">
<img width="1374" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6584e1a6-1f6d-40f6-8aff-796ab9ae012d">

**Comment by Ariznawlll** [comment]
**用博哥修改后的分支在128上跑的点查100 1000的结果**：

repo: volgariver6/matrixone
commit: 3c5fc55bc00ee24cf93a39d4adcb9ab4992dd76b

<img width="1011" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8bf75493-fa9b-435e-b127-d7046796b860">
<img width="1014" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f94110a8-efcf-4a8d-87ce-8d7c77c4b758">

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
128性能：
<img width="1379" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3fa13b39-09fe-405f-9e7d-fe9e984aa28f">

tke性能：
<img width="1363" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9388f3b5-7410-4ee1-ab6f-936f67310bbc">
