### ISSUE TITLE
[Bug]: panic: invalid lsn 181953, current lsn 0 when restart mo on Standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14652]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d8b2f448408ecc5427ca3d8ed364a6893477b429

### Other Environment Information

```Markdown
- Hardware parameters:64C 256G
- OS type:
- Others:
```

### Actual Behavior

when restart mo after kill -9 xxx, the mo can not be restarted successfully.error:
panic: invalid lsn 181953, current lsn 0

goroutine 1310 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).checkLSN(0xc013af8500, 0x7f3777bd63c8?)
        /data2/zywl/matrixone/pkg/vm/engine/tae/db/replay.go:157 +0xca
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayEntry(0xc013af8500, 0xb?, 0x2c6c1, {0xc003d3c063, 0x210d, 0x249d}, 0x63c8?, {0x70?, 0xc003d15800?})
        /data2/zywl/matrixone/pkg/vm/engine/tae/db/replay.go:110 +0x9a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).Replay.(*walDriver).replayhandle.func1(0x36ec900?, 0xc00f136900?, {0xc003d3c063?, 0x4d294e?, 0x180000003d00?}, 0x3400?, {0xc013420f20?, 0x49dbe8?})
        /data2/zywl/matrixone/pkg/vm/engine/tae/wal/driver.go:82 +0x23
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).replayEntry(0xc00f14c160, 0xc013420f48?, 0xc00d9443f0)
        /data2/zywl/matrixone/pkg/vm/engine/tae/logstore/store/replay.go:81 +0x263
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*StoreImpl).Replay.func1(0x153a0d0000001800?)
        /data2/zywl/matrixone/pkg/vm/engine/tae/logstore/store/replay.go:23 +0x25
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*replayer).replayRecords(0xc002780160)
        /data2/zywl/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go:146 +0x83
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*replayer).replay in goroutine 635
        /data2/zywl/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go:81 +0x6e

mo-log:
[mo-service.log](https://github.com/matrixorigin/matrixone/files/14381893/mo-service.log)

### Steps to Reproduce

```Markdown
1.kill -9 mo
2.modify cn,tn,log configuration,
  [fileservice.cache]
   memory-capacity = "8GB"
   disk-capacity = "8GB"
3. restart mo
```

**Comment by jiangxinmeng1** [comment]
<img width="590" alt="企业微信截图_17086664776665" src="https://github.com/matrixorigin/matrixone/assets/51114574/8b126efd-8fbf-4a15-9285-5e513cb5dd84">

看起来是没有读到ckp文件，可能配错目录了
