### ISSUE TITLE
[Bug]:  When the " select col, count(*) group by col" is executed, the data of the extra column is read.

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#1466]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bc3226116380d7ed03f96b45d01e1881a97cf539
- Hardware parameters:
- OS type:CentOS
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/14086886/146889511-37c45659-5cc7-4c6a-bee6-9ce0eff6a54d.png)
The two SQLs in the figure are executed after the pagecache is cleared

**Comment by nnsgmsone** [comment]
sloved
