### ISSUE TITLE
[Bug]: lots of error "ERROR 20600 (HY000) at line 23: the transaction xx has been committed or aborted" during stability test on standlone mode(TP&AP)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14664]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

ba86e9ca56e232305fc07cfaf4727d8480ed54aa

### Other Environment Information

```Markdown
- Hardware parameters: 16C 64G
- OS type:
- Others:
```

### Actual Behavior

During stability test on standlone, there lots of the following error in TP and AP load:
ErrorMessage : the transaction 018ddda51cad701cab147803865bf7d1 has been committed or aborted
ErrorMessage : the transaction 018ddda51c9c7210868de35d7deee45a has been committed or aborted
ErrorMessage : the transaction 018ddda51cb37f23b20f9d1a56122f1d has been committed or aborted
ErrorMessage : the transaction 018ddda51cb478b09262c2d3e6395546 has been committed or aborted
ErrorMessage : the transaction 018ddda51cb27465a78c6215a3137a19 has been committed or aborted
ErrorMessage : the transaction 018ddda51cac7c2abc65f52a73673a9a has been committed or aborted
ErrorMessage : the transaction 018ddda51ca17d0e82727a2b8145f841 has been committed or aborted
ErrorMessage : the transaction 018ddda51cac7f89af857e0f2e5c39b7 has been committed or aborted
ErrorMessage : the transaction 018ddda51ca570219284a4492a121b46 has been committed or aborted
ErrorMessage : the transaction 018ddda51ca87143be44689b32718964 has been committed or aborted
ErrorMessage : the transaction 018ddda51cb37fdf8f25ec50f7bd40ee has been committed or aborted
ErrorMessage : the transaction 018ddda51cac7947b3194ecb735327c6 has been committed or aborted
ErrorMessage : the transaction 018ddda51ca57723b212d6134e6e438b has been committed or aborted
ErrorMessage : the transaction 018ddda51cb376b3bb2ed0953fef0a5c has been committed or aborted
ErrorMessage : the transaction 018ddda51c9e7295bce43337e1db0581 has been committed or aborted
ErrorMessage : the transaction 018ddda51cb3713d955129812c10c604 has been committed or aborted

2024-02-25 08:23:22 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20600, ErrorMessage : the transaction 018ddda50edc7e96ae98acc11ecb1813 has been committed or aborted
2024-02-25 08:23:22 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20600, ErrorMessage : the transaction 018ddda51511775bbe6fc168f6250f8d has been committed or aborted
2024-02-25 08:23:22 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20600, ErrorMessage : the transaction 018ddda5119d770c853b7d449db6bef6 has been committed or aborted
2024-02-25 08:23:22 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20600, ErrorMessage : the transaction 018ddda5106a79c3aba97adf838426ad has been committed or aborted

log is more than 1G, if wanted, contanct me offline

### Steps to Reproduce

```Markdown
run stability test on standlone mode
1. tpch 10G loop queries
2. sysbench mixed cases with 30 threads
3. tpcc 10-10 terminals
```

**Comment by ouyuanning** [comment]
dup： https://github.com/matrixorigin/matrixone/issues/13583

**Comment by jensenojs** [comment]
辛苦远宁哥和 #13583 一起跟踪

**Comment by ouyuanning** [comment]
统一用这个跟进吧，这个优先级最高，也相对可以稳定复现
https://github.com/matrixorigin/MO-Cloud/issues/2412

**Comment by aressu1985** [comment]
OK
