### ISSUE TITLE
[Bug]: Insert into select report 'Lost connection to MySQL server during query' when running big_data test on tke.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14665]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ead69b441080825781ba62c0bc886f4f4b9f9ac5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:(Load and insert test -> insert into select) 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8029862130/job/21936797207

<img width="1029" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d27d10d3-b5e5-4de3-a6f9-f4fb4e3f4d1e">

**oom(2024-02-24 20:03:03)**：
<img width="1026" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/07794842-158d-4ee6-90cc-941bc6f25419">
<img width="1399" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a5b04b0f-9b1f-402a-b0a0-010f1871b31a">
url: http://175.178.192.213:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=branch-big-data-nightly-ead69b4&from=1708801200000&to=1708809600000

**2024-02-24 20:03:03**：
<img width="1026" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/18f2b725-9c12-4a69-acae-1056f2580e21">
<img width="1402" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a55c7e7a-7459-474c-bdba-ea60328dad61">
url:http://175.178.192.213:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=branch-big-data-nightly-ead69b4&from=1708815600000&to=1708819140000

**2024-02-24 23:27:16**：
<img width="1058" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/95fe6010-9da7-4d54-b9bb-b6115326d4ce">
<img width="1402" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a3b54849-038a-44ff-a8bc-51c97dad8a7b">
url:http://175.178.192.213:30088/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=branch-big-data-nightly-ead69b4&from=1708819200000&to=1708826400000

log:http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-ead69b4%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
Trigger big data test on tke.
If you need some test details, please contact me.
```

**Comment by ouyuanning** [comment]
dup : https://github.com/matrixorigin/MO-Cloud/issues/1574

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
没时间看

**Comment by jensenojs** [comment]
本质问题是mo的gc压力太大了, 这个问题短期没法根治, 只能一步一步来, 根治方式是下面这一堆issue的内存复用都做掉

<img width="896" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/193cd176-6d2b-4ba9-aeba-d4f3501eff19">

相关issue : https://github.com/matrixorigin/MO-Cloud/issues/384

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
休假中

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
休假中

**Comment by jensenojs** [comment]
处理其他s-1

**Comment by Ariznawlll** [comment]
[0506]没出现oom的问题了，出现了新的问题，如下：
<img width="994" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a75a642d-1547-4e4e-85f2-6424b9a5f643">

已经有新的issue在跟踪了 #15834

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8964781212/job/24618719749
