### ISSUE TITLE
[Bug]: [Bug]: lots of error “waiter is paused” in sysbench mixed test during stability test on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14667]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

ba86e9ca56e232305fc07cfaf4727d8480ed54aa

### Other Environment Information

```Markdown
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

During stability test on standlone, there lots of the following error in sysbench mixed cases:
 [tpcc]
2024-02-25 08:23:22 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20633, ErrorMessage : waiter is paused
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-25 08:23:22 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20633, ErrorMessage : waiter is paused
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-25 08:23:22 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20633, ErrorMessage : waiter is paused

[sysbench]
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused
ErrorMessage : waiter is paused

log is more than 1G, if wanted, contanct me offline,the part is :

{"level":"WARN","time":"2024/02/25 08:23:22.066943 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd27a45864ff9035680e2bc"}
{"level":"WARN","time":"2024/02/25 08:23:22.068245 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd475e1921c7111cbc50543"}
{"level":"WARN","time":"2024/02/25 08:23:22.068463 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd47b71a5da3b8d29c264a1"}
{"level":"INFO","time":"2024/02/25 08:23:22.068524 +0800","name":"dragonboat","caller":"v4@v4.0.0-20230426084722-d189534f8004/node.go:775","msg":"[00001:62145] saved <00001:62145:10180498>, term 2, file count 0"}
{"level":"WARN","time":"2024/02/25 08:23:22.069256 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd570fbbd477de906fd5b8b"}
{"level":"WARN","time":"2024/02/25 08:23:22.069398 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd5721d8c103f193187de6a"}
{"level":"WARN","time":"2024/02/25 08:23:22.069580 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd5735b8ae428f9c43a8638"}
{"level":"WARN","time":"2024/02/25 08:23:22.070083 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd67dccb2e8f320290bed54"}
{"level":"WARN","time":"2024/02/25 08:23:22.073659 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cd9763da18348af07625e80"}
{"level":"WARN","time":"2024/02/25 08:23:22.074689 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cda73aa96af196abee8774a"}
{"level":"WARN","time":"2024/02/25 08:23:22.074815 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cda72998658480fa65da0a4"}
{"level":"WARN","time":"2024/02/25 08:23:22.078980 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51cde7f65b419fce2a8b10c77"}
{"level":"WARN","time":"2024/02/25 08:23:22.087767 +0800","name":"log-service.txn","caller":"client/client.go:448","msg":"txn client is in pause state, wait for it to be ready","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn ID":"018ddda51ce7747f9a1846f2803f7c04"}
{"level":"INFO","time":"2024/02/25 08:23:22.088031 +0800","caller":"disttae/logtail_consumer.go:527","msg":"[logtail-consumer] 1708746016182506732dd1dccb4-4d3c-41f8-b482-5251dc7a41bf: client init finished"}
{"level":"INFO","time":"2024/02/25 08:23:22.088654 +0800","name":"log-service.txn","caller":"client/timestamp_waiter.go:98","msg":"timestamp waiter canceled","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089367 +0800","caller":"client/timestamp_waiter.go:249","msg":"error: waiter is paused"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089401 +0800","name":"log-service.txn","caller":"client/operator.go:974","msg":"txn wait committed log applied failed in rc mode","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn":"018ddda5154f7f6b9249323dbeae2b9c/Committed/S:1708820600129552911-1/C:1708820600180589802-0","error":"waiter is paused"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089410 +0800","caller":"client/timestamp_waiter.go:249","msg":"error: waiter is paused"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089461 +0800","name":"log-service.txn","caller":"client/operator.go:974","msg":"txn wait committed log applied failed in rc mode","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn":"018ddda515577a1882ec7f90b992e02e/Committed/S:1708820600129552911-1/C:1708820600405928368-0","error":"waiter is paused"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089501 +0800","caller":"client/timestamp_waiter.go:249","msg":"error: waiter is paused"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089536 +0800","name":"log-service.txn","caller":"client/operator.go:974","msg":"txn wait committed log applied failed in rc mode","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","txn":"018ddda5155779329e2b1ab9c0fa8211/Committed/S:1708820600129552911-1/C:1708820600194809413-0","error":"waiter is paused"}
{"level":"ERROR","time":"2024/02/25 08:23:22.089540 +0800","caller":"client/timestamp_waiter.go:249","msg":"error: waiter is paused"}

### Steps to Reproduce

```Markdown
run stability test on standlone mode
1. tpch 10G loop queries
2. sysbench mixed cases with 30 threads
   insert and delte
   point select
   update by pk
3. tpcc 10-10 terminals
```

**Comment by volgariver6** [comment]
logtail 发生了重连，原因是往chan里发送数据的时候超时了：
<img width="869" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/478fd9cf-1a26-415a-add5-6c8d70b9dffa">

但是日志中的信息是：
```
{"level":"ERROR","time":"2024/02/25 08:23:22.047257 +0800","name":"tn-service.logtail-server","caller":"service/session.go:565","msg":"poision morpc client session detected, close it","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"018dd932-fe01-70fc-a690-12c7978c05e4","stream-id":1,"remote":"127.0.0.1:52350","buffer-capacity":26214,"buffer-length":0}
```

说明`ss.sendChan`的长度是0，但还是发生了超时，唯一的解释就是cpu负载过高，所以修复办法是增加超时时间，将其保留为配置项。

**Comment by volgariver6** [comment]
pr committed

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
