### ISSUE TITLE
[Bug]: [2.24]tke regression: sysbench test reported panic error  plan.isExpr_Expr is *plan.Expr_Lit, not *plan.Expr_Vec

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14669]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ead69b441

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8031232174/job/21943928284
<img width="1394" alt="企业微信截图_2b0f3e64-4303-4fcc-b16c-c5f709d51307" src="https://github.com/matrixorigin/matrixone/assets/113406637/479b46b9-ea87-4e0b-a2a8-484fed454d24">

FATAL: mysql_drv_query() returned error 20101 (internal error: panic interface conversion: plan.isExpr_Expr is *plan.Expr_Lit, not *plan.Expr_Vec: 
runtime.panicdottypeE
	/usr/local/go/src/runtime/iface.go:263
runtime.panicdottypeI
	/usr/local/go/src/runtime/iface.go:273
github.com/matrixorigin/matrixone/pkg/sql/plan.estimateExprSelectivity
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/stats.go:456
github.com/matrixorigin/matrixone/pkg/sql/plan.calcScanStats
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/stats.go:949
github.com/matri) for query '        SELECT id, k, c, pad
          FROM sbtest1
          WHERE k IN (17650, 17646, 17660, 17650, 17650, 17650, 17650, 17635, 17650, 17650)
        '
FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 20101, state = 'HY000': internal error: panic interface conversion: plan.isExpr_Expr is *plan.Expr_Lit, not *plan.Expr_Vec: 
runtime.panicdottypeE
	/usr/local/go/src/runtime/iface.go:263
runtime.panicdottypeI
	/usr/local/go/src/runtime/iface.go:273
github.com/matrixorigin/matrixone/pkg/sql/plan.estimateExprSelectivity
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/stats.go:456
github.com/matrixorigin/matrixone/pkg/sql/plan.calcScanStats
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/stats.go:949
github.com/matri

该commit不是必现panic，同一个commit，这个job回归没有报panic错
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8020716837/job/21911617464
<img width="1429" alt="企业微信截图_85ce8575-4684-419b-a1d8-e8a720917dc0" src="https://github.com/matrixorigin/matrixone/assets/113406637/220a72f6-dfd9-408f-bc2f-4a40b586c8c4">

### Steps to Reproduce

```Markdown
tke regression sysbench10w test
```

**Comment by jensenojs** [comment]
@aunjgr 麻烦龙冉哥先看看

**Comment by aunjgr** [comment]
已找到原因

**Comment by heni02** [comment]
1.1也出现了相同的问题，麻烦也同步到1.1

**Comment by heni02** [comment]
confirm，closed
main commit：5b7f38d6b
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8082055967/job/22103475365
<img width="1391" alt="企业微信截图_a71c2928-5316-4d32-86f1-47a5a58eaed8" src="https://github.com/matrixorigin/matrixone/assets/113406637/e276973a-2b3d-4ac9-8a31-386bb0a82b6b">

**Comment by aressu1985** [comment]
fixed
