### ISSUE TITLE
[Bug]: lots of error “context deadline exceeded” in sysbench mixed test during stability test on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14668]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

ba86e9ca56e232305fc07cfaf4727d8480ed54aa

### Other Environment Information

```Markdown
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

During stability test on standlone, there lots of the following error in tpcc:
2024-02-26 08:23:43 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:23:50 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:24:00 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:24:00 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:24:09 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:24:22 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:24:37 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:24:54 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2024-02-26 08:25:19 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 1105, ErrorMessage : context deadline exceeded

log is more than 1G, if wanted, contanct me offline,the part is :
{"level":"INFO","time":"2024/02/26 08:23:42.155017 +0800","name":"log-service","caller":"task/task_scheduler.go:71","msg":"task schedule query tasks","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","created":0,"expired":0}
{"level":"ERROR","time":"2024/02/26 08:23:42.233393 +0800","caller":"frontend/mysql_cmd_executor.go:4351","msg":"error: internal error: !!!COM_QUIT!!!","span":{"trace_id":"af073eb9-9338-b8ec-b29f-e97d14c45c15","span_id":"e3598cf2b79cdfe7"}}
{"level":"ERROR","time":"2024/02/26 08:23:42.233478 +0800","name":"log-service.frontend","caller":"frontend/routine.go:241","msg":"Failed to execute request","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"internal error: !!!COM_QUIT!!!","session_info":"connectionId 82298|127.0.0.1:43572|{account sys:3976e6da-ff80-41f1-8fe5-b82843743abd:moadmin -- 0:4294967295:0}|goRoutineId 23096735|018de2cb-c6c9-7101-9001-44ef659dd2d3","session_id":"018de2cb-c6c9-7101-9001-44ef659dd2d3"}
{"level":"ERROR","time":"2024/02/26 08:23:42.233508 +0800","name":"log-service.frontend","caller":"frontend/routine_manager.go:521","msg":"Error occurred","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"internal error: !!!COM_QUIT!!!","session_info":"connectionId 82298|127.0.0.1:43572|{account sys:3976e6da-ff80-41f1-8fe5-b82843743abd:moadmin -- 0:4294967295:0}|goRoutineId 23096735|018de2cb-c6c9-7101-9001-44ef659dd2d3","session_id":"018de2cb-c6c9-7101-9001-44ef659dd2d3"}
{"level":"INFO","time":"2024/02/26 08:23:42.233594 +0800","caller":"frontend/routine.go:301","msg":"set query status on the connection 82298"}
{"level":"ERROR","time":"2024/02/26 08:23:43.101084 +0800","name":"log-service.frontend","caller":"frontend/mysql_cmd_executor.go:3071","msg":"context deadline exceeded","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 146|127.0.0.1:56910|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 7515|018dd936-860e-758a-97d4-10adae07ded3","session_id":"018dd936-860e-758a-97d4-10adae07ded3","statement_id":"018ddda5-7499-7517-bee2-f442df45d32c","txn_id":"018ddda56efb7e7d9515584f30feaca5/Active/S:1708820624501322753-1"}
{"level":"INFO","time":"2024/02/26 08:23:43.102131 +0800","name":"log-service.frontend","caller":"frontend/mysql_cmd_executor.go:3892","msg":"time of Exec.Run : 23h59m57.114953344s","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 150|127.0.0.1:56920|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 6912|018dd936-8737-7297-aa87-048174ce1c40","session_id":"018dd936-8737-7297-aa87-048174ce1c40","statement_id":"018ddda5-7a42-770e-b628-e2333a030763","txn_id":"018ddda57a187ef5a5bd2e48d9e30131/Active/S:1708820625918716439-1"}
{"level":"INFO","time":"2024/02/26 08:23:43.108814 +0800","name":"tn-service.logtail-server","caller":"service/server.go:403","msg":"handle subscription asynchronously","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"018dd932-fe01-70fc-a690-12c7978c05e4","table":"db_id:272492 tb_id:272499 "}
{"level":"ERROR","time":"2024/02/26 08:23:43.134657 +0800","name":"log-service.frontend","caller":"frontend/util.go:511","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","connection_id":146,"statement":"execute __mo_stmt_id_30 // prepare __mo_stmt_id_30 from UPDATE bmsql_order_line     SET ol_delivery_d = ?     WHERE ol_w_id = ? AND ol_d_id = ? AND ol_o_id = ? ; 2024-02-25 08:23:43.096000 ; 3 ; 7 ; 5629","status":"fail","error":"context deadline exceeded","span":{"trace_id":"6cf2b839-9632-9fc1-f39a-8e97195fe361","span_id":"64b5ef4dab8273e5"},"session_info":"connectionId 146|127.0.0.1:56910|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 7515|018dd936-860e-758a-97d4-10adae07ded3","session_id":"018dd936-860e-758a-97d4-10adae07ded3","statement_id":"018ddda5-7499-7517-bee2-f442df45d32c"}
{"level":"INFO","time":"2024/02/26 08:23:43.293619 +0800","name":"tn-service.logtail-server","caller":"service/session.go:505","msg":"send subscription response","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"018dd932-fe01-70fc-a690-12c7978c05e4","stream-id":1,"remote":"127.0.0.1:44760","table":"db_id:272492 tb_id:272499 ","To":"PhysicalTime:1708907023094625252 "}
{"level":"INFO","time":"2024/02/26 08:23:43.303267 +0800","name":"tn-service.logtail-server","caller":"service/server.go:403","msg":"handle subscription asynchronously","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"018dd932-fe01-70fc-a690-12c7978c05e4","table":"db_id:272492 tb_id:272495 "}
{"level":"INFO","time":"2024/02/26 08:23:43.312544 +0800","caller":"disttae/logtail_consumer.go:694","msg":"[logtail-consumer] subscribe tbl[db: 272492, tbl: 272499] succeed"}

### Steps to Reproduce

```Markdown
run stability test on standlone mode
1. tpch 10G loop queries
2. sysbench mixed cases with 30 threads
   insert and delte
   point select
   update by pk
3. tpcc 10-10 terminals
```

**Comment by jensenojs** [comment]
本地试了一下, 没复现成功

**Comment by jensenojs** [comment]
@volgariver6  那辛苦博哥一起跟踪一下吧, 看了一下 #13762 感觉也不是一时半会能解决的.

> dup #13762

**Comment by volgariver6** [comment]
no process

**Comment by volgariver6** [comment]
no process

**Comment by volgariver6** [comment]
no process

**Comment by volgariver6** [comment]
no process

**Comment by volgariver6** [comment]
no process

**Comment by volgariver6** [comment]
这个问题的本质是cpu负载过高导致的，在单机环境下出现的概率更高

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
无进展

**Comment by sukki37** [comment]
tracked by https://github.com/matrixorigin/matrixone/issues/13762
