### ISSUE TITLE
[Bug]: The result of count(distinct(column)) is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14675]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ead69b441080825781ba62c0bc886f4f4b9f9ac5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**select count(distinct(col24)) from big_data_test.table_basic_for_load_100M:**
<img width="701" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/67d6b47b-0fe5-497f-8a4b-23572f14e5df">
<img width="685" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1959026a-9022-4f22-a615-38dd2dc1a56b">

**select count(distinct(col9)) from big_data_test.table_basic_for_load_100M:**
<img width="692" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c5f7cd72-300d-4df8-955e-35c0b76286f4">
<img width="669" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/92fd3a35-5c41-462e-9adf-df02026af9e4">

### Steps to Reproduce

```Markdown
1. create table:
create table if not exists big_data_test.table_basic_for_load_100M(
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);
2. load data into table:
load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_100M fields terminated by '|' lines terminated by '\n' parallel 'true';
3. execute sql:
select sum(tan(col9)) from big_data_test.table_basic_for_load_100M;
select sum(sin(col9)) from big_data_test.table_basic_for_load_100M;
select sum(cos(col9)) from big_data_test.table_basic_for_load_100M;
```

**Comment by Ariznawlll** [comment]
**The result of select max(column), min(column) is incorrect.**
<img width="492" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/17a49bd8-3375-4a38-9aca-b18ed8148940">
<img width="890" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c8cc24d1-8e38-4325-a5cc-dcb8da9a111d">

 select max(col9) from big_data_test.table_basic_for_load_100M;
 select min(col9) from big_data_test.table_basic_for_load_100M;

**Comment by zengyan1** [comment]
<img width="746" alt="企业微信20240227-160731@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/510b3c60-60cb-413d-abd4-e0c75d91a807">

float32有1位符号位，8位指数位，23位小数位，共32位，其中23位小数位在十进制下最多有效7位。
Golang自动对float32超出7位的部分做十进制下的四舍五入

**Comment by zengyan1** [comment]
<img width="711" alt="企业微信20240227-175300@2x" src="https://github.com/matrixorigin/matrixone/assets/93656539/b0cab4d1-f700-4a59-b5f2-fe713f3d9b91">
对vecf类型处理有问题

**Comment by zengyan1** [comment]
等待合入

**Comment by zengyan1** [comment]
已合入

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
<img width="643" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/cdc0cc25-3018-41d8-b50e-358d4f435ad8">

**Comment by Ariznawlll** [comment]
**commit：2f86fead29f6f49e719b437b47337de4bf9aef6c**

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/8903c67b-e322-4eaa-b4b2-7e754f2c51b6">

**Comment by fengttt** [comment]
This bug is fixed but trigger an invalid alloc bug.   @m-schen please link your pr and resolve this one.

**Comment by m-schen** [comment]
这个和其他那几个issue不太一样。

其他的issue是group数太多，导致最终result超过1g报错。

这个语句并没有group by，也就是说结果只有一行。并不会碰到该问题，是处理 count(distinct column)的distinct会构建一个哈希表，哈希表太大的问题。

**Comment by m-schen** [comment]
不过哈希表我记得内部自带了超过1g会分块的逻辑，
不是很明确这个bug分配单块大内存的地方。

也许这个查询被自动转换成了 
select count(column) from (select column from t group by column) t; 

如果是这种情况的话，与其他的几个bug大概率是一样的问题。
