### ISSUE TITLE
[Bug]: Loading data from cos with primary key and unique index is 7 times slower than the single primary key.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14670]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ead69b441080825781ba62c0bc886f4f4b9f9ac5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8029862130/job/21936797207

<img width="1037" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7f806f41-2ee1-4c11-b144-f69058ea579a">

log:http://175.178.192.213:30088/explore?panes=%7B%22AAL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-ead69b4%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
Trigger big data test on tke.

table schema：
有主键1亿数据量 table schema：
create table  if not exists big_data_test.table_with_pk_for_load_100M(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

主键+unique index 1亿数据量table schema：
create table  if not exists big_data_test.table_with_pk_index_for_load_100M(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3),
key(col3),
unique key(col4)
);

有主键10亿数据量 table schema：
create table  if not exists big_data_test.table_with_pk_for_load_1B(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3)
);

主键+unique index 10亿数据量table schema：
create table  if not exists big_data_test.table_with_pk_index_for_load_1B(
id bigint primary key,
col1 tinyint,
col2 smallint,
col3 int,
col4 bigint,
col5 tinyint unsigned,
col6 smallint unsigned,
col7 int unsigned,
col8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(16,6),
col17 text,
col18 json,
col19 blob,
col20 binary(255),
col21 varbinary(255),
col22 vecf32(3),
col23 vecf32(3),
col24 vecf64(3),
col25 vecf64(3),
key(col3),
unique key(col4)
);

If you need to load data, please ask me for 'load sql'.
```

**Comment by jensenojs** [comment]
等 https://github.com/matrixorigin/matrixone/pull/14743 合并之后对unique key 启动该优化

> unique key的性能下降是已知问题, 等后续我重构完成之后它应该会好一些

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
may dup with : https://github.com/matrixorigin/MO-Cloud/issues/2389

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
在本地做了一个简单的对比, 使用下表, 然后在其基础上添加一个主键, 然后再再有主键的基础上添加一个唯一索引, 统计空表情况下`insert into select`的耗时.

```sql
create table t0(a int, b int, c int, d int);
insert into t0 select result, result, result, result from generate_series ...g;
```

<img width="1369" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/0b9c3b3a-e348-4143-891c-66014390ac5d">

小节一下上表中能看到的数据
- 没有索引
  - 每增加一千万, 耗时增加大约1秒多
  - 每增加一亿, 耗时大约增加15秒
- 一个主键
  - 每增加一千万, 耗时增加大约2秒多
  - 每增加一亿, 耗时大约增加一分钟多一些
- 主键唯一
  - 每增加一千万, 耗时增大大约5秒多
  - 每增加一亿, 耗时上一个台阶, 看不出明显规律.

***

下面这个issue的ddl只有主键, 十亿规模, 二十来列, 但耗时干到了八十分钟, 需要后续继续观察

-  #14692

***

只有主键的情况下, 插入四亿行的explain anlayze结果如下
![image](https://github.com/matrixorigin/matrixone/assets/56761542/0217eac9-017e-4107-9663-6f4033dc0142)


有主键, 唯一索引的情况下, 插入三亿行的explain anlayze结果如下
<img width="1956" alt="Pasted Graphic 27" src="https://github.com/matrixorigin/matrixone/assets/56761542/c079fbb5-043d-4620-89c6-4cd136becfba">
<img width="1956" alt="Pasted Graphic 28" src="https://github.com/matrixorigin/matrixone/assets/56761542/14dfe18a-21e9-4e96-874c-559cb813dc81">

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
处理其他s-1

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
目前无这个问题, 辛苦QA再看看, @Ariznawlll 
<img width="1020" alt="企业微信截图_4e312c49-5ba7-4bd0-9a95-4cdb154e2e56" src="https://github.com/matrixorigin/matrixone/assets/56761542/bcac60f4-28f9-4b2e-b908-ae8146c1ded2">

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
<img width="990" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d70db6d5-10a4-4c7c-9b2f-c90796cf8e8b">
相关问题还是存在

**Comment by jensenojs** [comment]
还没有看, 但需要检查一下TN会不会有去重的逻辑

**Comment by jensenojs** [comment]
没看
