### ISSUE TITLE
[Bug]: [date2.23]tke regression:tpcc 500 and 1000 warehouse many connection timed out and r-w confict

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14672]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ead69b441

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc出现大量连接超时，还有r-w confict。该问题必现
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8031232174/job/21941301741
<img width="1475" alt="企业微信截图_c9e7d774-700a-4da7-964e-1f0726ab5a7a" src="https://github.com/matrixorigin/matrixone/assets/113406637/0ffd5459-a6df-414d-9fbd-1e5d895ea4d9">

log：
http://175.178.192.213:30088/explore?panes=%7B%22OEB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240224%5C%22%7D%20%7C%3D%20%60r-w%20conflict%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708806000000%22,%22to%22:%221708809659000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc test
```

**Comment by jensenojs** [comment]
@zhangxu19830126  劳驾旭哥帮忙看看谁看一下这个问题合适?

**Comment by XuPeng-SH** [comment]
@gouhongshen please help to investigate this issue

**Comment by heni02** [comment]
二分排除找到有问题的pr，cc @volgariver6 
<img width="1378" alt="企业微信截图_f99c3a3d-3ea5-4d9a-8082-e7e41d177edb" src="https://github.com/matrixorigin/matrixone/assets/113406637/2dc6374a-5291-45fa-aebb-4e0f49a5cbeb">

**Comment by volgariver6** [comment]
main分支上已经没有这个问题了

**Comment by heni02** [comment]
没有找到原因，现有的main分支回归也没有再出现该问题，先关闭
