### ISSUE TITLE
[Bug]: [date 2.26] tke regression: tpch 1T query caused cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14700]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bbf99e1d9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8050556301/job/21987841021
<img width="1384" alt="企业微信截图_7f51771b-412a-42c2-983a-50c7a95c8c7f" src="https://github.com/matrixorigin/matrixone/assets/113406637/fc4e72bb-d85e-4ae6-932c-9e86c6c62af2">

stream_closed报错原因是cn oom被kill了
<img width="1400" alt="企业微信截图_ac33d99d-981d-4c37-b214-3c22a049960f" src="https://github.com/matrixorigin/matrixone/assets/113406637/059435de-fe7a-4d8f-a42e-21ae68058e16">
http://175.178.192.213:30088/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-nightly-regression-20240226&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki

loki log：
http://175.178.192.213:30088/explore?panes=%7B%22igz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240226%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708967400000%22,%22to%22:%221708967579000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpch1T test
```

**Comment by heni02** [comment]
复现，抓取的profle如下：
<img width="1392" alt="企业微信截图_3b477b0b-f606-4671-8410-d20b6795f8eb" src="https://github.com/matrixorigin/matrixone/assets/113406637/e27e9607-7f8d-42b9-b38a-0f24a206d687">

[mo_prof.tar.gz](https://github.com/matrixorigin/matrixone/files/14417323/mo_prof.tar.gz)

**Comment by badboynt1** [comment]
从profile里没看出来有什么问题。 q18本来就是最耗内存的一条query，tpch 1T 跑q18是很接近oom边缘的。内存占用大概四十多G是比较合理的。
于此同时eks上跑了3cn 1T就没有oom。
所以要么是某个pr导致内存占用提升了一点点，刚好达到oom触发线。要么就是tke环境发生了某种变化，更容易触发oom了

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/cf24495a-e4ae-4d44-b5a2-fd2c748addb9)

![image](https://github.com/matrixorigin/matrixone/assets/112734932/527d327d-b27f-40ec-ba65-ae96d8d404df)

**Comment by heni02** [comment]
date 2.29 128单机tpch1T也出现了oom的情况（新加的流程，第一次跑）commit:a9e9f2f4699bba03fb59958d5a9a81c90ec45cb4
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8097578526/job/22129082442
<img width="1102" alt="企业微信截图_d939ef4c-a7b3-4dc7-84c0-49e1139c7775" src="https://github.com/matrixorigin/matrixone/assets/113406637/002451d4-375b-4f6f-b8e6-03ac5c8b7da8">
<img width="1278" alt="企业微信截图_f5bba1ec-fd0c-4d00-a902-9f60449a0520" src="https://github.com/matrixorigin/matrixone/assets/113406637/5cef9084-2f8d-4848-9198-f7163aa6bda4">

**Comment by badboynt1** [comment]
在128单机上oom，看了profile里heap占用情况，memcache占用了72g，然而只设置了32g。 这是可能导致oom的一个影响因素。
@nnsgmsone 麻烦看一下这个内存占用是为啥？

![企业微信截图_17096048008536](https://github.com/matrixorigin/matrixone/assets/112734932/ab6e95c6-fcbc-406b-9a72-3b0d514f5460)

**Comment by badboynt1** [comment]
在128单机上，将tn的memcache配置改成默认配置后再尝试一次

**Comment by nnsgmsone** [comment]
no process

**Comment by badboynt1** [comment]
128单机上，修改dn的memcache后不再oom
tke 3cn上，暂时没法修改memcache。 没有什么思路

**Comment by nnsgmsone** [comment]
这个就算cache重构也有概率oom，应该是查询本身内存占用过大导致的。

**Comment by badboynt1** [comment]
等待agg重构 或者spill来解决问题

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/15669
这个issue完成后，tpch q18的内存分配会下降很多

**Comment by heni02** [comment]
date 5.13 regression又出现了oom，commit：b88a2b8e1
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9064806413/job/24936147501
<img width="1080" alt="企业微信截图_5296c756-7bf2-4636-b5ef-8f8f3d6ea252" src="https://github.com/matrixorigin/matrixone/assets/113406637/a383c520-3b46-4687-ab21-703eea77a925">
<img width="944" alt="企业微信截图_b659e9cd-0924-44d0-b4a1-7cfeb3766fff" src="https://github.com/matrixorigin/matrixone/assets/113406637/c330026f-a398-401a-9493-b40078817309">
<img width="1417" alt="企业微信截图_508836ba-0f32-4685-a801-06e1120445b1" src="https://github.com/matrixorigin/matrixone/assets/113406637/a30f8132-a8f0-44ff-8441-99c2f6bb81cb">
同时tpch1T的性能也下降了
<img width="1399" alt="企业微信截图_c92cfec1-4d70-4f41-94c5-33cbd967bbe5" src="https://github.com/matrixorigin/matrixone/assets/113406637/6d552751-da63-4cf0-9dc6-772a6b33f1d3">

14号回归也出现了oom，nitao在手动抓取profile中
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9081256748

最后一次没有oom的commit：82d0eaa17
oom的commit：b88a2b8e1

**Comment by heni02** [comment]
date 5.16，5.17也出现Q18 oom，必现
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9129933033/job/25124440112
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4cb551fa-5474-403d-b089-64920aa7217d)
<img width="1408" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/eed22387-de5b-4434-ba85-e1ad54b91405">

**Comment by badboynt1** [comment]
从daily测试里来看，3cn跑tpch1T也不会oom了，内存峰值回到了1.1版本的水平。
至于在tpcc和sysbench之后再跑4cn oom，是有内存没有释放导致的，放在其他issue里跟踪。

**Comment by heni02** [comment]
confirm，closed
commit:cda0e9073
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9329068377
<img width="1408" alt="企业微信截图_cc2dc0b3-d662-44da-8e59-64a0a4a520ed" src="https://github.com/matrixorigin/matrixone/assets/113406637/13aa4803-b5e3-4cf3-a68e-c40a2c9939e8">
