### ISSUE TITLE
[Bug]: [date 2.26]tke regression： tpcc reported ErrorMessage : Stock for S_W_ID = 81 and S_I_ID = 57658 not found

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14701]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bbf99e1d9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc 100W 100terminals reported many ErrorMessage : Stock for S_W_ID = 81 and S_I_ID = 57658 not found
ErrorMessage : District for W_ID = 4 and D_ID = 1 not found
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8050556301/job/21995372178
<img width="1422" alt="企业微信截图_6ee4ccf9-8973-4288-a4cc-4877a39c2da7" src="https://github.com/matrixorigin/matrixone/assets/113406637/18cbe85d-ce41-45b9-95ec-974f2c6ff2fd">
初步定位，该时间段没有节点重启情况，也无panic，fatal报错

loki ：
http://175.178.192.213:30088/explore?panes=%7B%22igz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240226%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708971420000%22,%22to%22:%221708972859000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc 100W 100terminals test
```

**Comment by heni02** [comment]
正在二分查找

**Comment by heni02** [comment]
二分找到的pr
<img width="1367" alt="企业微信截图_ae50e593-28aa-4680-976c-1fc966bc47e0" src="https://github.com/matrixorigin/matrixone/assets/113406637/39e2672e-2215-42c3-be41-6c742435b246">
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8062343394/job/22022300645

**Comment by heni02** [comment]
二分重新跑了commit：dafdef0，也出现了该错误，@badboynt1 看下这个问题
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8063101425/job/22024686637
commit：dafdef0
<img width="1451" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/31b00c0d-059b-4030-adc9-d80e015af854">

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
revert掉后依然出现该错误
commit：bdfd2157b9ce5cac08dafc42c62d4865d5de170a
<img width="1145" alt="企业微信截图_4bd4e684-5650-40fd-bdd8-33fec3edbdd8" src="https://github.com/matrixorigin/matrixone/assets/113406637/68304281-7b0b-4af3-b111-062aa5705a8e">

**Comment by heni02** [comment]
二分没有找到具体的pr，暂时最新的commit无复现，先降级

**Comment by aressu1985** [comment]
fixed
