### ISSUE TITLE
[Bug]: [date 2.26]standalone regression: tpcc test reported panic find no transfer mapping for row

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14702]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bbf99e1d949f200a3dd56957d9ac39865984070a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8050440413/job/21986205017
<img width="1388" alt="企业微信截图_d414aebe-c630-4415-b952-550d1e0dc5a7" src="https://github.com/matrixorigin/matrixone/assets/113406637/c0516055-a656-4c82-a1cb-bb69eb454012">

log:
{"level":"INFO","time":"2024/02/27 05:38:19.247364 +0800","caller":"rpc/handle.go:1042","msg":"op2 1708983499182880592-1 (24,10) 018de75a-8ebd-7724-816e-17206c02d876-0-0-4262"}
panic: 018de75a-8ebd-7724-816e-17206c02d876-0-0 find no transfer mapping for row 5282

goroutine 1651 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/txnentries.(*flushTableTailEntry).PrepareCommit(0xd8a55daea0)
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/txnentries/flushTableTail.go:149 +0xaa5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PrepareCommit(0xc8f1f2c990)
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnimpl/table.go:1549 +0xad
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PrepareCommit(0xd4d7e011a0)
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnimpl/txndb.go:526 +0xf2
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PrepareCommit(0xd4c6237e40?)
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnimpl/store.go:802 +0x1bb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PrepareCommit(0xd4cc4fefc0)
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnbase/txn.go:327 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreparCommit(0xc000230460?, {0x460ef00, 0xd4cc4fefc0})
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:319 +0x24
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare(0xc017bc9d28?, 0xd8abfc5e30, {0x0, 0x0, 0x0, 0x0, 0x3d, 0xca, 0x80, 0x1e, ...})
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:373 +0x2c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrepare1PC(0xc000230460?, 0xd8abfc5e30?, {0x0, 0x0, 0x0, 0x0, 0x3d, 0xca, 0x80, 0x1e, ...})
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:398 +0x45
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).dequeuePreparing(0xc000230460, {0xc0044d6000, 0x4f, 0x3e8})
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:492 +0x2b5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1e5
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 1380
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xe5

log plz connect me

### Steps to Reproduce

```Markdown
standalone regression tpcc 100w 1000terminals test
```

**Comment by heni02** [comment]
commit :94f70f2b9b1da4fc83578eac2ba51a4058d4146d tpcc测试是通过的，正在二分

**Comment by Ariznawlll** [comment]
二分结果：
<img width="989" alt="企业微信截图_b0454842-7959-4353-ad2b-970a0de39e96" src="https://github.com/matrixorigin/matrixone/assets/108530700/0d359308-bc1e-4e94-ad11-11bcfac90e27">

**Comment by aptend** [comment]
dafdef02fa7e15dc7ae670fc3e34c1ef5de243c7 出现了 w-w conflict 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8062518272/job/22022539932

产生的原因是做 transfer 过程中找不到对应行
```
{"level":"WARN","time":"2024/02/27 17:43:49.234537 +0800","caller":"txnimpl/table.go:243","msg":"[ts=1709027029217193007-1]TransferDeleteNode: table-272493 blk-[1 141 233 241 119 167 120 73 160 224 26 225 13 81 201 228 0 0 0 0] delete row-5358 depth-0"}
```

如果在做 flush 时也做 transfer，找不到对应行则表现为 panic，所以两者在这一层可以看做是相同的问题

目前更早的分支暂未出现类似错误

**Comment by aptend** [comment]
确认 143dacad30b9fb236caaf0456c57bc456bcdb2b4 也存在 panic 错误
job https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8076106189/job/22065323098

**Comment by aptend** [comment]
revert https://github.com/matrixorigin/matrixone/commit/143dacad30b9fb236caaf0456c57bc456bcdb2b4 后运行共计 16 次 tpcc-100-1000，问题未复现

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/14728 修复

**Comment by aptend** [comment]
已确认原因，https://github.com/matrixorigin/matrixone/commit/143dacad30b9fb236caaf0456c57bc456bcdb2b4 中使用了最大committs 作为 flush 的 startts，可能会漏掉正在 commit 的 append 数据，导致数据缺失
```
2024/03/04 17:06:28.311824 +0800 INFO line 2678: pk is 3-10, cmmit is 1709534925282916442-0
2024/03/04 17:06:28.311832 +0800 INFO line 2679: pk is 12-8, cmmit is 1709534925283404430-0 <- ablk ROWS = 2679
                                                                       1709534925283553790-0 <- flush start time
2024/03/04 17:06:28.311838 +0800 INFO line 2680: pk is 52-2, cmmit is 1709534925283726085-0
2024/03/04 17:06:28.311845 +0800 INFO line 2681: pk is 63-9, cmmit is 1709534925308961704-0 <- panic not found 
```

**Comment by aptend** [comment]
修改中

**Comment by aptend** [comment]
验证 https://github.com/matrixorigin/matrixone/pull/14839

**Comment by aptend** [comment]
验证中问题复现，找到原因后做了新的修改，已 approved，正在合入

**Comment by aptend** [comment]
修复已合入5天，暂未出现

**Comment by aptend** [comment]
未出现

**Comment by heni02** [comment]
confirm,closed
commit:6e2ff3c8c4e142151f089e37167a4e79d115638a
目前回归没有再出现
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8437645403/job/23108095066
