### ISSUE TITLE
[Bug]: [date 2.26]tke regression: sysbench test reported panic  index out of range [0] with length 0:  runtime.goPanicIndex

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14703]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bbf99e1d9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

reported two panic error:
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8050556301/job/22009515462
<img width="1396" alt="企业微信截图_bcce2649-35e1-41b2-beee-9c2146503a31" src="https://github.com/matrixorigin/matrixone/assets/113406637/a4711542-80d4-460e-ae3c-824455d371c1">

FATAL: `thread_run' function failed: select_random_points.lua:71: SQL error, errno = 20101, state = 'HY000': internal error: panic there must be runtime filter in index build!: 
github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild.(*container).handleRuntimeFilter
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild/build.go:126
github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild.(*Argument).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild/build.go:66
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
	/go/src/github.com/matrixor
[ 20s ] thds: 997 tps: 2798.16 qps: 2798.16 (r/w/o: 2798.16/0.00/0.00) lat (ms,95%): 253.35 err/s: 1.70 reconn/s: 0.00
FATAL: mysql_store_result() returned error 20101 (internal error: panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild.(*container).collectBuildBatches
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild/build.go:108
github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild.(*container).build
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/indexbuild/build.go:117
github.com/matrixorigin/matrixone/)

loki:
http://175.178.192.213:30088/explore?panes=%7B%22igz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240226%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221708999200000%22,%22to%22:%221708999439000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench sysbench 100w random_points test
```

**Comment by heni02** [comment]
@badboynt1 panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex 这个panic麻烦定位下
@aunjgr internal error: panic there must be runtime filter in index build! 这个panic麻烦定位下

**Comment by aunjgr** [comment]
等PR合入

**Comment by aunjgr** [comment]
等index join重新提PR，以及 #14704 合并

**Comment by aunjgr** [comment]
等PR合并

**Comment by aunjgr** [comment]
等pr合并

**Comment by aunjgr** [comment]
等PR合并

**Comment by aunjgr** [comment]
#14753 已包含相关修改。麻烦验证。 @heni02
