### ISSUE TITLE
[Bug]: mo hung after stability test on standlone mode about 8 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14721]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

002e1a46838181a6d033fc445362f3a0d4b83cc4

### Other Environment Information

```Markdown
- Hardware parameters: 16C 64G
- OS type:
- Others:
```

### Actual Behavior

After running stability test on standlone mode for about 8 hours, the mo was hung:
<img width="753" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6df080ac-14a9-4f0c-b6fa-7c55357401d1">

profile:
[
[mo-hung.tar.gz](https://github.com/matrixorigin/matrixone/files/14428501/mo-hung.tar.gz)
](url)

### Steps to Reproduce

```Markdown
1. run a mo on standlone mode
2. run stability test
   tpch 10 loop queries
   tpcc 10-10 longrunning test
   sysbench mixed test longrunning test
```

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/eb6f8b99-15ae-406d-b0d7-6acbff75ca4d)

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/b2c71567-2a9f-4b7d-a828-432a4214c8c1)

**Comment by volgariver6** [comment]
我来看一下

**Comment by volgariver6** [comment]
出现问题的最开始的原因是logtail发生了重连，重连的原因与#16447相同。

但是重连之后一直没有恢复，导致了mo hang的问题。日志中的信息：

```
{"level":"INFO","time":"2024/02/27 18:21:26.366115 +0800","caller":"disttae/logtail_consumer.go:402","msg":"[logtail-consumer] logtail receiver resumed"}
{"level":"INFO","time":"2024/02/27 18:21:26.366277 +0800","name":"tn-service.logtail-server","caller":"service/session.go:278","msg":"initialize new session for morpc stream","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","server-id":"018de875-fe6e-7832-8d99-473a4054c958","stream-id":1,"remote":"127.0.0.1:55430"}
```
在这两条日志之后没有订阅系统表的信息了，代码如下：
<img width="852" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/d07a7258-4470-4fe8-83fb-c682edc8a958">

第263行起开新的session，打印"initialize new session for morpc stream"，下面应该直接走到290行，然后打印出“handle subscription asynchronously”，但是没有该日志。

所以提交的PR解决了重连的问题，正常来说应该不会在出现重连了。如果还是发生了重连，并且hang住，再根据新加的日志分析问题。

**Comment by volgariver6** [comment]
pr committed.

**Comment by volgariver6** [comment]
pr committed.

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
