### ISSUE TITLE
[Bug]: incorrect stats after stats refactoring

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#14749]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select count(*) from zywl.ecbase_card_g1;
+----------+
| count(*) |
+----------+
| 49000000 |
+----------+
1 row in set (0.02 sec)

mysql> explain verbose select count(*) from zywl.ecbase_card_g1;
+-----------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                |
+-----------------------------------------------------------------------------------------------------------+
| Project (cost=1.00 outcnt=1.00 selectivity=1.0000 blockNum=1)                                             |
|   Output: count(*)                                                                                        |
|   ->  Aggregate (cost=1000.00 outcnt=1.00 selectivity=1.0000 blockNum=1 hashmapSize=1.00)                 |
|         Output: count(*)                                                                                  |
|         Aggregate Functions: starcount(1)                                                                 |
|         ->  Table Scan on zywl.ecbase_card_g1 (cost=1000.00 outcnt=1000.00 selectivity=1.0000 blockNum=1) |
|               Output: ecbase_card_g1.id                                                                   |
|               Table: 'ecbase_card_g1' (0:'id')                                                            |
|               Aggregate Functions: starcount(1)                                                           |
+-----------------------------------------------------------------------------------------------------------+
9 rows in set (0.00 sec)

### Steps to Reproduce

```Markdown
on 129 environment
```

**Comment by volgariver6** [comment]
fixed, need keep eyes on it for some time
