### ISSUE TITLE
[Bug]: [date 3.4]standalone regression: sysbench 1000w Read_only caused mo oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14779]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2196ac25be1f7f1b483916cdb16140e78f50c509

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8141776947/job/22249996419
<img width="1395" alt="企业微信截图_858f73bd-96aa-4bcb-8e2f-58ad4a029ac9" src="https://github.com/matrixorigin/matrixone/assets/113406637/8a4de554-295f-4ec8-b5b8-0cf4af201200">
<img width="1320" alt="企业微信截图_849fa190-f329-4d88-9bff-43a0fbe70206" src="https://github.com/matrixorigin/matrixone/assets/113406637/aa10b381-3650-4ec8-9168-f3a44228ee01">

这个时间段开始内存使用已经很高了
<img width="1104" alt="企业微信截图_8ea01256-82f3-4f38-a7ad-2dc138be1c72" src="https://github.com/matrixorigin/matrixone/assets/113406637/5025f95f-a4f2-4019-9c85-dbbbec1862e6">
<img width="1117" alt="企业微信截图_231902db-658d-43fa-a233-7f0d38084308" src="https://github.com/matrixorigin/matrixone/assets/113406637/4909ef96-f3fa-4a53-b101-2473eb6c4c3c">

profile：
[read_olny_oom.tar.gz](https://github.com/matrixorigin/matrixone/files/14489506/read_olny_oom.tar.gz)

mo log plz connect to me

### Steps to Reproduce

```Markdown
sysbench 1000w Read_only  regression test
```

**Comment by reusee** [comment]
从heap profile看，是高负载下内存缓存占用内存过高的问题，莫尘已经提了相关 pr：https://github.com/matrixorigin/matrixone/pull/14641

**Comment by nnsgmsone** [comment]
等待pr和入

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
等待pr和入后测试

**Comment by nnsgmsone** [comment]
测试验证中

**Comment by heni02** [comment]
confirm，closed
commit：66c433efeb6320beadedb1758352e0b09dc8ebf3
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8421687498/job/23059347221
<img width="1357" alt="企业微信截图_34c6b07d-b302-4fcc-8892-666e5f8bb170" src="https://github.com/matrixorigin/matrixone/assets/113406637/962c6946-197c-45f1-9282-eb417ac88059">
