### ISSUE TITLE
[Bug]: the connection between CN and TN has been disconnected

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#14789]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

48b79f1e5d443012e44b7fbd95b8310f8bf3ed1d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

http://175.178.192.213:30088/explore?panes=%7B%223rG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-14660%5C%22%7D%20%7C%3D%20%60disconnected%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
```

### Actual Behavior

<img width="1628" alt="企业微信截图_3e7113b4-4395-4cc4-bf1a-050a77bf8425" src="https://github.com/matrixorigin/matrixone/assets/60595215/124578c0-319b-41f7-806a-b0a23063559d">

### Expected Behavior

no

### Steps to Reproduce

```Markdown
occurs in the regression ci.
```

**Comment by zhangxu19830126** [comment]
Cn down, so the dis connection is expect
