### ISSUE TITLE
[Bug]: dn can not restart when cpu core is more than 100

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14780]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

all commit

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2024/02/28 08:03:11.451827 +0000","name":"logservice-client","caller":"morpc/client.go:365","msg":"gc idle backends task started"}
gc 7 @1.255s 0%: 0.24+11+0.19 ms clock, 30+7.2/310/192+25 ms cpu, 117->121->112 MB, 131 MB goal, 1 MB stacks, 0 MB globals, 128 P
{"level":"INFO","time":"2024/02/28 08:03:11.466084 +0000","caller":"db/open.go:63","msg":"open-tae","operation":"End","operand":"open","cost":"56.345537ms","err":null}
panic: bad param: 128 io workers

goroutine 798 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.newTaskScheduler(0x4507d90?, 0xc006a6cd50?, 0xc004849680?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/scheduler.go:43 +0x865
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x4507d90?, 0xc006a6cd50}, {0xc00005ca50, 0x50}, 0xc00485c400?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/open.go:92 +0x813
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0x4507d90, 0xc006a6cd50}, {0xc0049614f0, 0x4c}, 0x100?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:1222 +0x1a6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0x4507d90?, 0xc006a6cd50?}, {0xc0049614f0?, 0x5?}, 0xc0062a3b30?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:91 +0x45
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0x4507d90?, 0xc006a6cd50}, {0xc0049614f0, 0x4c}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:72 +0x255
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).newTAEStorage(0xc006a1eea0, {0x4507d90, 0xc006a6cd50}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/tnservice/factory.go:158 +0x2b2
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createTxnStorage(0xc006a1eea0, {0x4507d90, 0xc006a6cd50}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/tnservice/factory.go:73 +0x2d8
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createReplica.func1({0x4507d90, 0xc006a6cd50})
	/go/src/github.com/matrixorigin/matrixone/pkg/tnservice/store.go:305 +0x13c
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:263 +0x6e
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 770
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:258 +0xd6

### Steps to Reproduce

```Markdown
NA
```

**Comment by XuPeng-SH** [comment]
fixed in main

**Comment by aressu1985** [comment]
fixed
