### ISSUE TITLE
[Bug]: panic in tke regression ci

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#14788]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

48b79f1e5d443012e44b7fbd95b8310f8bf3ed1d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

http://175.178.192.213:30088/explore?panes=%7B%223rG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-14660%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
```

### Actual Behavior

<img width="2922" alt="企业微信截图_1b3b0903-a6cc-4403-acd1-e631a1ad2ddc" src="https://github.com/matrixorigin/matrixone/assets/60595215/36e05744-38c2-4165-8ef5-df16a01c1f25">

### Expected Behavior

no panic

### Steps to Reproduce

```Markdown
regression ci.
I am no sure that it can be reproduced again.
```

**Comment by arjunsk** [comment]
So there seem to be 3 types of panic in Grafana logs

1. Join

![image](https://github.com/matrixorigin/matrixone/assets/9638314/87078686-2fc0-4da9-a291-60cba7a951fb)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/63dae3d6-2272-4759-b899-e676bc807b79)

Most likely the Operator before JOIN failed to generate a batch. 

2. Restrict (line 54, 130)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/550a9ec5-d6c5-4799-b355-1deab8d1f2d0)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/bab218a4-19eb-438f-af0a-ce18dcf27ad3)


3. Binary Operator panic
![image](https://github.com/matrixorigin/matrixone/assets/9638314/335a848f-2b42-4e83-b771-6a700a9ac36d)


### Observation

I think https://github.com/matrixorigin/matrixone/pull/14544 PR could be a possible reason for this panic. I am not sure though.

@triump2020 Could you kindly look into this or assign it to the right person? Thank you!

**Comment by triump2020** [comment]
@arjunsk `48b79f1e5d443012e44b7fbd95b8310f8bf3ed1d  `  had been reverted by `0af79833bd9efeb27d30ce043c4e9acc4388a21d`

**Comment by triump2020** [comment]
@daviszhen  pls close it !
