### ISSUE TITLE
[Bug]: query_version test case of bvt failed: The row count does not equal with each other, one is 1, the other is 0

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#14836]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

43c9b234c6cfe3128228aa30803c67833e390905

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="2032" alt="企业微信截图_61c682e3-3630-439d-ab39-a891f29bb310" src="https://github.com/matrixorigin/matrixone/assets/49832303/37b03a53-86b4-41db-9fc3-0c29deeceb3e">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/8172053626/job/22341596477?pr=14689
```

**Comment by xzxiong** [comment]
next week.

**Comment by xzxiong** [comment]
no clue

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/8844969726/job/24287931201?pr=15738
再次重现了

**Comment by xzxiong** [comment]
case: 
- https://github.com/matrixorigin/matrixone/issues/15694#issuecomment-2074387431
- https://github.com/matrixorigin/matrixone/issues/15694#issue-2260671148

**Comment by xzxiong** [comment]
case 
- [x] log/query_version.sql
- [x] sql_source_type/sql_source_type.sql
- [ ] result_count/result_count.sql

**Comment by xzxiong** [comment]
no new case recently.

**Comment by xzxiong** [comment]
> case
> 
> * [x]  log/query_version.sql
> * [x]  sql_source_type/sql_source_type.sql
> * [ ]  result_count/result_count.sql
> * [x]  log/query_tae_table.sql (rename as log/query_stmt.sql)

fix result_count in #16474

**Comment by xzxiong** [comment]
new case:
- result_count, https://github.com/matrixorigin/matrixone/issues/14836

**Comment by xzxiong** [comment]
all done.

**Comment by xzxiong** [comment]
no repro
