### ISSUE TITLE
[Bug]: Default Precision of Time

### ISSUE THREAD

**Issue by zengyan1** [matrixorigin/matrixone#14840]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

194fbf7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When we use the data type 'time', we can write like 'time(precision)'.
'precision' is an integer, which means the number of fractional digits in the 'second' field of the time.
If there is no 'precision', it will be a default value.

mysql:
The default value is 0. The max value is 6.

PostgreSQL:
The default value is 6. The max value is 6.
In any case, all suffix zero in fractional digits will be truncated.

Snowflake:
The default value is 9. The max value is 9.

Mo:
The default value is 6. The max value is 6.

### Steps to Reproduce

```Markdown
create table t(a time,b time(2));
insert into t values('00:00:00','00:00:00');
insert into t values('00:00:00.0001','00:00:00.0001');
select * from t;
```

**Comment by fengttt** [comment]
Result of select * from t;
```
my:dump@127/mysql=> select * from t;
    a     |      b
----------+-------------
 00:00:00 | 00:00:00.00
 00:00:00 | 00:00:00.00
(2 rows)
```

This seems to be correct so I will resolve this as already fixed.
