### ISSUE TITLE
[Bug]: metric in mpool.Alloc and mpool.Free takes too much cpu resource

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#14843]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.1-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1780" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/37596bf5-3427-4eec-9b05-14ded469af23">

<img width="1792" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/fdf386ec-bca3-4d69-b374-bd2b1ffd4b10">

### Steps to Reproduce

```Markdown
Alloc and Free are in the very performance-critical path. There is no io or lock here and I think we need to remove the metric to save some CPU resources.
```

**Comment by arjunsk** [comment]
Hi @nnsgmsone , could you kindly assign it to someone appropriate? Thank you!

**Comment by gouhongshen** [comment]
ZYWL-insert benchmarking on 129 shows that nearly 30%/100% CPU usage is spent on metrics within `MPool.Free`

<img width="1594" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/54335e7f-96c4-4c48-8aca-463eed419b0e">
