### ISSUE TITLE
[Bug]: sysbench 1000W auto_increment index delete  100threads test oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14849]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

3d2f8b383a28930945a894401097331f20b882f4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8197851328/job/22420511799
<img width="1105" alt="企业微信截图_47184436-6b87-4dca-92f3-e6ec7c2c884b" src="https://github.com/matrixorigin/matrixone/assets/113406637/050627c7-1336-491d-9a5c-c659aaef6715">
<img width="1428" alt="企业微信截图_282b157a-a46f-4533-8c20-03e443c73ecc" src="https://github.com/matrixorigin/matrixone/assets/113406637/6b8b197f-6e16-48fd-92fd-7f5cb03836cd">

sbtest schema:
CREATE TABLE `sbtest1` (`id` INT NOT NULL AUTO_INCREMENT,`k` INT DEFAULT 0,`c` CHAR(120) DEFAULT "",`pad` CHAR(60) DEFAULT "",PRIMARY KEY (`id`),KEY `k_1` (`k`));

profile:
[delete_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/14532930/delete_profile.tar.gz)

### Steps to Reproduce

```Markdown
sysbench1000w delete 100threads test
```

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
定位中

**Comment by nnsgmsone** [comment]
测试验证中

**Comment by heni02** [comment]
confirm，closed
commit：66c433efeb6320beadedb1758352e0b09dc8ebf3
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8421687498/job/23059347221
<img width="1357" alt="企业微信截图_34c6b07d-b302-4fcc-8892-666e5f8bb170" src="https://github.com/matrixorigin/matrixone/assets/113406637/962c6946-197c-45f1-9282-eb417ac88059">
