### ISSUE TITLE
[Bug]: lock table bind changed during sysbench read write case and loading data on daily regression

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#14879]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2dac54173e815966b616548b88570e6c29b64246

### Other Environment Information

```Markdown
- Hardware parameters: 
  Standlone: 64C 256G
  Distributed: 3*CN 64C 256G. 1*DN 64C 256G. 3*LOG 4C 16G
- OS type:
- Others:
```

### Actual Behavior

job link(standlone):
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8215188255/job/22468424763
<img width="1333" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d039e84f-7971-4db4-8796-1c77824a12e2">

job link(distributed):
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8204761695/job/22447393197
<img width="1341" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ce0053c1-bea1-429d-bd34-cf041bb6ad09">

mo log:
[lock_table_changed_error.tar.gz](https://github.com/matrixorigin/matrixone/files/14548276/lock_table_changed_error.tar.gz)
http://175.178.192.213:30088/explore?panes=%7B%22h5y%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240308%5C%22%7D%20%7C%3D%20%60lock%20table%20bind%20changed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221709909791840%22,%22to%22:%221709928595335%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
非必现
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
fix pr : https://github.com/matrixorigin/matrixone/pull/15311

**Comment by Ariznawlll** [comment]
先观察几天

**Comment by Ariznawlll** [comment]
持续观察中。。

**Comment by Ariznawlll** [comment]
最近的regression没出现这个问题。
