### ISSUE TITLE
[Bug]: 隐式事务在CREATE/DROP DATABASE时未能强制提交

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/matrixone#14878]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

≥v1.0.1

### Commit ID

b104e66

### Actual Behavior

**问题描述：**
在官网**1.0.0-rc1及后续版本**文档[隐式事务规则](https://docs.matrixorigin.cn/1.0.0-rc1/MatrixOne/Develop/Transactions/matrixone-transaction-overview/implicit-transaction/)章节中，提到：
```text
若在 AUTOCOMMIT=0 的状态下出现 CREATE/DROP DATABASE 或 CREATE/DROP SEQUENCE 操作，则会强制提交之前未提交的所有内容。
同时，CREATE/DROP DATABASE 操作将会立即作为一个独立的事务进行提交。
```
实际测试发现在1.0.0-rc1、1.0.0-rc2和1.0.0版本功能符合描述，自1.0.1版本开始，执行drop database语句，不会强制提交事务。

### Steps to Reproduce

**复现步骤：**

1）创建两个测试库
```mysql
create database star;
create database test;
```

2）查看session变量并将autocommit设为0
```mysql
show variables like '%commit%';
set autocommit=0;
```

3）创建表并插入测试数据
```mysql
use star;
CREATE TABLE `nation` (
 `n_nationkey` INT NOT NULL,
 `n_name` CHAR(25) NOT NULL,
 `n_regionkey` INT NOT NULL,
 `n_comment` VARCHAR(152) DEFAULT NULL,
 PRIMARY KEY (`n_nationkey`)
 );

insert into nation values (1,'2',3,'4');
```

4）执行drop database语句
```sql
drop database test;
```

5）在其他连接中观察star库下nation表和数据是否存在，以此来判断事务是否被强制提交。
测试发现1.0.0及其rc版本可以强制提交，但≥1.0.1的MatrixOne未能强制提交。

**Comment by daviszhen** [comment]
需要先看下

**Comment by daviszhen** [comment]
the pr https://github.com/matrixorigin/matrixone/pull/14899
aslo has some problems below.

```sql

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mo_catalog         |
| mo_debug           |
| mo_task            |
| mysql              |
| system             |
| system_metrics     |
| test               |
+--------------------+
8 rows in set (0.00 sec)

mysql> set autocommit = 0;
Query OK, 0 rows affected (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mo_catalog         |
| mo_debug           |
| mo_task            |
| mysql              |
| system             |
| system_metrics     |
| test               |
+--------------------+
8 rows in set (0.00 sec)

mysql> drop database test;
Query OK, 1 row affected (3.66 sec)

mysql> drop database test;
Query OK, 1 row affected (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mo_catalog         |
| mo_debug           |
| mo_task            |
| mysql              |
| system             |
| system_metrics     |
| test               |
+--------------------+
8 rows in set (3.27 sec)



```

**Comment by heni02** [comment]
confirm，closed
1.1-dev commit：afb4934ae327b7f0b10add4413301524be2221a6
<img width="415" alt="企业微信截图_55972e34-ae9c-4ba7-aab3-79c1598ea57f" src="https://github.com/matrixorigin/matrixone/assets/113406637/159abf1e-fc68-4153-a21c-10324f6b42b8">
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_catalog         |
| mo_task            |
| information_schema |
| mysql              |
| system_metrics     |
| system             |
| db                 |
| db1                |
+--------------------+
8 rows in set (0.00 sec)
mysql> drop database db1;
Query OK, 1 row affected (0.01 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_catalog         |
| mo_task            |
| information_schema |
| mysql              |
| system_metrics     |
| system             |
| db                 |
+--------------------+
7 rows in set (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.03 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_catalog         |
| mo_task            |
| information_schema |
| mysql              |
| system_metrics     |
| system             |
| db                 |
+--------------------+
7 rows in set (0.00 sec)
