### ISSUE TITLE
[Bug]: sysbench bulk insert 1000threads test reported Duplicate entry for pk

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14890]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

15af2cf1a39ed25b808ef52bb5c864a816521e9d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8222669843/job/22484468726
<img width="1100" alt="企业微信截图_a84b93a0-1f5a-4d5f-9a24-15b9a323fce6" src="https://github.com/matrixorigin/matrixone/assets/113406637/cb655548-2573-4499-a32a-c131a9673cb6">

bulk_insert 1000threads报这个错,bulk_insert 100threads没有报错
sysbench bulk1000threads测试含义是创建1000个表，并发批量加载，每个表schema的ddl为：
<img width="687" alt="企业微信截图_3df95a66-1231-4195-a9d3-2afdf604b83e" src="https://github.com/matrixorigin/matrixone/assets/113406637/72f8c3cc-a180-45ba-9edc-0f7b3fcdb08c">
CREATE TABLE `sbtest1` (
`id` INT NOT NULL,
`k` INT DEFAULT '0',
PRIMARY KEY (`id`)
)

执行命令：sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 bulk_insert.lua --mysql-db=sysbench_db --tables=10 --table_size=10000000 --threads=1000 --time=300 --report-interval=10  run

尝试去掉AUTO_INCREMENT，增加--auto_inc=off ，测试没有报 Duplicate entry 的错误,执行命令：
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 bulk_insert.lua --mysql-db=sysbench_db --tables=10 --table_size=10000000 --threads=1000 --time=300 --auto_inc=off --report-interval=10  run

### Steps to Reproduce

```Markdown
sysbench bulk_insert 1000threads
```

**Comment by ouyuanning** [comment]
等罗飞那边的ww和dup的那个问题都处理后再看看吧。

**Comment by jensenojs** [comment]
无进展

**Comment by ouyuanning** [comment]
罗飞的PR合并后应该没有了，后续还有可转罗飞继续处理

**Comment by heni02** [comment]
confirm，closed
commit：6e2ff3c8c4e142151f089e37167a4e79d115638a
![image](https://github.com/matrixorigin/matrixone/assets/113406637/bbfbb4ef-45c8-43f6-8de2-40a919e88167)

**Comment by heni02** [comment]
tke 分布式还是会出现，reopen
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8453493408/job/23172016164
<img width="1078" alt="企业微信截图_14ac0e68-5db3-4e20-9699-ae750ee41e2b" src="https://github.com/matrixorigin/matrixone/assets/113406637/c6f82c4f-bf62-40b3-8538-735c1896c129">

**Comment by ouyuanning** [comment]
辛苦@triump2020 统一处理吧

**Comment by triump2020** [comment]
目前只在长期分布式稳定性中出现

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15235

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15545

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15731

**Comment by triump2020** [comment]
已经定位: 原因如下:
 1.  txn1 在CN1 上insert 了 一条 PK, 并committed.   2.  CN2 上的txn2  还未等到 这个pk 同步到partition state 中，就开始 运行 delete pk(delete statment 的snapshot ts 应该是小于txn1 的commit ts 的, 否则CN2 会等water mark 超过txn1 的commit ts ) ， 这时pk 的rowid 查不到，delete 运行之后，affected rows =0， 相当于delete 没起效果; 然后运行 insert pk , 去重时，之前被txn1 提交的pk 同步过来了，然后在partiton state 中发现了相同的pk , 导致dup.

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15948

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992 fixed dup/ww bug.

**Comment by triump2020** [comment]
Wait for @ouyuanning PR

**Comment by triump2020** [comment]
In testing

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
正在加日志 ，查看tke-dup 问题

**Comment by triump2020** [comment]
单机的ww/dup 已定位到大致原因.

**Comment by triump2020** [comment]
@heni02  duplicate with #17354 .

**Comment by triump2020** [comment]
@heni02   It's duplicate with #17354, pls close it.
.

**Comment by heni02** [comment]
confirm,closed
<img width="1041" alt="企业微信截图_fb51cd91-5864-4fde-b080-e53ce1104bc1" src="https://github.com/user-attachments/assets/747e07eb-4d6e-4f3c-b8db-b674c3059a1b">
