### ISSUE TITLE
[Tech Request]: refactor logtail replay in CN

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#14908]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
refactor the logtail replay codes to eliminate copy-on-write btree.
```

**Comment by reusee** [comment]
will continue after the TAE team has done their refactorings.

**Comment by reusee** [comment]
1. the logtail protocol should be stable before major logtailreplay package refactors, otherwise we can't ensure the semantic correctness during the refactor about changing from copy-on-write to multi-version implementation.
2. I doubt whether the bottleneck is really at logtail replaying. I'll do some executing tracer works to measure it.
3. Implementing a concurrent btree will not be done in the short term.
4. The logtailreplay package needs unit tests to ensure semantic correctness and performance measuring.

**Comment by reusee** [comment]
re-assigning to @triump2020 

related PR: https://github.com/matrixorigin/matrixone/pull/16228

**Comment by XuPeng-SH** [comment]
done
