### ISSUE TITLE
[Feature Request]: adding `admin_name` field to `mo_catalog.mo_account`

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#14918]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
https://github.com/matrixorigin/MO-Cloud/issues/2564
```

### Describe the feature you'd like

see the design doc for details: https://github.com/gouhongshen/mo-docs/blob/main/show_accounts_optimization.md

**Comment by qingxinhome** [comment]
pr已提交

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been merged. Please verify and test @sukki37 @gouhongshen @daviszhen @ck89119 @aressu1985

**Comment by aressu1985** [comment]
1、表字段添加已经OK
<img width="980" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7b7ab53c-5d71-4559-a036-bde11f5c7e71">

2、升级后，以后租户的初始化，需要进一步测试

**Comment by aressu1985** [comment]
升级后，测试也通过
测试结束
