### ISSUE TITLE
[Bug]:  Login to MO hang via mysql cli

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#14935]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

v1.1.2-pre-3f1ef26f0-2024-03-12

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Login to MO hangs:
➜  ~ mysql -h xxxx.cluster.cn-dev.matrixone.tech -P6001 -uxxx -p
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.

### Expected Behavior

Login successfully

### Steps to Reproduce

```Markdown
Just login with mysql cli
```

### Additional information

Goroutine profile
[default-localpv-cn-kbg6m.zip](https://github.com/matrixorigin/matrixone/files/14581175/default-localpv-cn-kbg6m.zip)

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
@ck89119 帮忙看下

**Comment by ck89119** [comment]
暂时未复现，等之后复现再看
