### ISSUE TITLE
[Bug]: [date 3.12]standalone regression: tpcc 100warehouse 1000threads reported many connection timed out

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14939]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7164ded60b563e2d5f3cc4cd411bd892816e2a93

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8250543191/job/22565428905
<img width="1106" alt="企业微信截图_bf75fa59-c7e3-486b-bd7e-74c46edf567d" src="https://github.com/matrixorigin/matrixone/assets/113406637/d2c85cfe-9ed4-405b-8d24-540e5d7ef179">
<img width="1046" alt="企业微信截图_f078f11d-1412-4a40-a989-5507f72d0f60" src="https://github.com/matrixorigin/matrixone/assets/113406637/5cc7df26-b539-4d17-9c53-ce9380a51511">

log：
报超时时间是2024-03-13 07:28:10，2024/03/13 07:30:12报panic错误，期间日志里有大量的read tcp4 127.0.0.1:36974->127.0.0.1:32001: i/o timeout"错误
<img width="1268" alt="企业微信截图_b5c2aa1c-a5fc-4d25-b5b3-e2d0c7cd16d5" src="https://github.com/matrixorigin/matrixone/assets/113406637/9ce6aad6-b903-4f81-a530-a745dd6fb7c2">
<img width="1267" alt="企业微信截图_fc481f21-929b-4e21-a686-e8b0a5ebfbdf" src="https://github.com/matrixorigin/matrixone/assets/113406637/40b6759e-730d-4849-8fb1-cc253de42483">
 whole logs plz contact to me

### Steps to Reproduce

```Markdown
tpcc 100 warehouse 1000threads test
```

**Comment by nnsgmsone** [comment]
看着是前端空指针，麻烦看一下

**Comment by daviszhen** [comment]
@ck89119 help to find something.

**Comment by ck89119** [comment]
并发场景可能会出现同时deleteRoutine的情况，需要先判断rt是否为nil

**Comment by ck89119** [comment]
panic问题已修复，出现timeout的原因没看出来，不确定是不是panic影响导致的，先继续观察，再次出现timeout的时候再分析。

**Comment by heni02** [comment]
@ck89119 现在回归没有此问题，超时问题加一些日志？下次复现可以直接定位

**Comment by heni02** [comment]
先关闭
