### ISSUE TITLE
[Bug]: index filter panic in bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#14938]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8258447909/job/22590707829?pr=14913

[1-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/14581580/1-cn-e2e-linux-x86-reports.zip)

<img width="1026" alt="WeChatWorkScreenshot_f81300cd-f224-4bd2-babf-0eacf5e9ee9d" src="https://github.com/matrixorigin/matrixone/assets/77312370/1b22b80f-2a74-490b-af1f-56a5bf123955">

### Steps to Reproduce

```Markdown
run bvt test
```

**Comment by triump2020** [comment]
Fixed.

**Comment by guguducken** [comment]
Testing
