### ISSUE TITLE
[Bug]: [date 3.12]standalone regression: sysbench read_write reported error not connect to a database

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14946]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7164ded60b563e2d5f3cc4cd411bd892816e2a93

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8250543191/job/22565604820
<img width="1142" alt="企业微信截图_553f1133-975c-4f2f-bb83-ccfedb79cdb1" src="https://github.com/matrixorigin/matrixone/assets/113406637/0cc1aaf4-620f-4c78-9696-f190d6cdb104">
log plz contact me:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ba93c0eb-e807-4303-89e4-c0d470804084)

### Steps to Reproduce

```Markdown
sysbench 1000w read-write test
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by aressu1985** [comment]
先关闭，等出现在提issue处理
