### ISSUE TITLE
[Bug]: alias are case insensitive in create table as select.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14955]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1e530c4286d1ea371e7edda46cb830efcb3ba7a4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1440" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/13ff31ac-6a6d-469f-a0b1-07fe1c4c39f9">

要与mysql保持一致.

### Steps to Reproduce

```Markdown
drop table if exists alias01;
create table alias01 (col1 int, col2 decimal);
insert into alias01 values (1,2);
insert into alias01 values (2,3);
drop table if exists alias02;
create table alias02 (NewCol int) as select * from alias01;
show create table alias02;
select * from alias02;
drop table alias01;
```

**Comment by ck89119** [comment]
有个global var: lower_case_table_names控制parse时是否把表/列名改成小写，当前默认值为1，即默认全部改成小写。
<img width="431" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/5f73e936-a1ca-4ff9-8e7d-3564ccfc1e04">

改成0以后就和mysql一致了
<img width="786" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/26273cb8-b84a-4f25-bf28-66bff71b1487">

至于默认值为什么为1，我也不清楚当时的场景和考量。

**Comment by ck89119** [comment]
@dengn 你看下呢

**Comment by dengn** [comment]
ok. @yangj1211 pay attention for case sensitivity when you edit docs for CTS.

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
