### ISSUE TITLE
[Bug]: vector index: lists not optional

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14950]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ee4b53f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

missing list reported error
<img width="1032" alt="企业微信截图_379b571d-cce0-47dc-a83c-57c64215e702" src="https://github.com/matrixorigin/matrixone/assets/113406637/c03e3362-0e42-4d65-9aa1-7448ffe28670">

### Steps to Reproduce

```Markdown
sql：
create table vector_index_07(a int primary key, b vecf32(128),c int,key c_k(c));
create index idx01 using ivfflat on vector_index_07(b) op_type "vector_l2_ops";
```

**Comment by arjunsk** [comment]
Raised a PR: https://github.com/matrixorigin/matrixone/pull/15016

**Comment by arjunsk** [comment]
PR Merged.

**Comment by heni02** [comment]
confirm,closed
commit:35cb5aa0385310aadaa3177a8c4b843b482783b7
<img width="1079" alt="企业微信截图_e1eec303-0901-4cb0-8628-0c081516b514" src="https://github.com/matrixorigin/matrixone/assets/113406637/a6d85037-679b-40ec-af27-ee366a19eff1">
