### ISSUE TITLE
[Bug]: [date 3.13]tke regression: sysbench 100w update-non-index reported context deadline exceeded

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#14962]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f61a0f210adcb429e3528245bc60f4b0115c5bdf

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8266410811/job/22631470720
<img width="1115" alt="企业微信截图_402af222-e3a9-4348-93f4-3db32839de2c" src="https://github.com/matrixorigin/matrixone/assets/113406637/f6ccd860-ee1b-47b1-a6d8-5c3a0b566659">

log 发现报错前有i/o timeout，确认下报错是否符合预期
<img width="1381" alt="企业微信截图_e8d50d04-0a9f-44a3-81bc-ef0be1793297" src="https://github.com/matrixorigin/matrixone/assets/113406637/b34c6f4c-7a2f-4b7d-93c7-b36ae67c9018">
http://175.178.192.213:30088/explore?panes=%7B%227iC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240313%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221710367402000%22,%22to%22:%221710367404000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke sysbench 100w update-non-index test
```

**Comment by iamlinjunhong** [comment]
fix pr : https://github.com/matrixorigin/matrixone/pull/15633

**Comment by heni02** [comment]
confirm，closed
commit：6e9451389
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8959013124/job/24608352904
