### ISSUE TITLE
[Bug]: create table as select report 'invalid argument operator cast, bad value [VARCHAR ENUM]'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#14970]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

868980a8664bcac9f8d268e0467a720cc810070b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1428" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5ada2050-b329-4734-9ad4-b848676fff4c">

### Steps to Reproduce

```Markdown
drop table if exists table01;
create table table01 (
    id int auto_increment primary key,
    col1 varchar(255) not null ,
    col2 int,
    col3 decimal(10, 2),
    col4 date,
    col5 boolean,
    col6 enum('apple', 'banana', 'orange'),
    col7 text,
    col8 timestamp,
    col9 blob,
    col10 char,
    unique index(col8, col10)
);
insert into table01 (col1, col2, col3, col4, col5, col6, col7, col8, col9, col10) values
('Value2', 456, 78.90, '2023-10-24', false, 'banana', 'Another text', '2022-01-01 01:01:01.000', 'More binary data', 'D'),
('Value3', 789, 12.34, '2023-10-25', true, 'orange', 'Yet another text', '1979-01-01 01:01:01.123', 'Even more binary data', 'E');
create table table02 as select * from table01;
```

**Comment by YANGGMM** [comment]
have fixed in https://github.com/matrixorigin/matrixone/pull/14902, plz test again @Ariznawlll

**Comment by Ariznawlll** [comment]
commit：a79f1282bd6e1b9235dc78593311919c16427a3d

<img width="1430" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/230ceeb0-3e52-404b-b7b4-cddab7c81e71">

drop table if exists table01;
create table table01 (
    id int auto_increment primary key,
    col1 varchar(255) not null ,
    col2 int,
    col3 decimal(10, 2),
    col4 date,
    col5 boolean,
    col6 enum('apple', 'banana', 'orange'),
    col7 text,
    col8 timestamp,
    col9 blob,
    col10 char,
    unique index(col8, col10)
);
insert into table01 (col1, col2, col3, col4, col5, col6, col7, col8, col9, col10) values
('Value2', 456, 78.90, '2023-10-24', false, 'banana', 'Another text', '2022-01-01 01:01:01.000', 'More binary data', 'D'),
('Value3', 789, 12.34, '2023-10-25', true, 'orange', 'Yet another text', '1979-01-01 01:01:01.123', 'Even more binary data', 'E');
create table table02 as select * from table01;
insert into table02 values (12, 'Value1', 123, 45.67, '2023-10-23', TRUE, 'apple', 'This is a text', '2019-01-01 01:01:01.000', 'Some binary data', 'C');
select * from table02;
update table02 set col1 = 'newvalue' where col2 = 456;

**Comment by YANGGMM** [comment]
```mysql
drop table if exists table01;
create table table01 (
id int auto_increment primary key,
col1 varchar(255) not null ,
col2 int,
col3 decimal(10, 2),
col4 date,
col5 boolean,
col6 enum('apple', 'banana', 'orange'),
col7 text,
col8 timestamp,
col9 blob,
col10 char,
unique index(col8, col10)
);
insert into table01 (col1, col2, col3, col4, col5, col6, col7, col8, col9, col10) values
('Value2', 456, 78.90, '2023-10-24', false, 'banana', 'Another text', '2022-01-01 01:01:01.000', 'More binary data', 'D'),
('Value3', 789, 12.34, '2023-10-25', true, 'orange', 'Yet another text', '1979-01-01 01:01:01.123', 'Even more binary data', 'E');
create table table02 as select * from table01;
insert into table02 values (12, 'Value1', 123, 45.67, '2023-10-23', TRUE, 'apple', 'This is a text', '2019-01-01 01:01:01.000', 'Some binary data', 'C');
select * from table02;
update table02 set col1 = 'newvalue' where col2 = 456;
```

**Comment by YANGGMM** [comment]
fixed plz test

**Comment by Ariznawlll** [comment]
<img width="955" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a1036df1-385a-4d60-9369-b57997fd0663">

verified
