### ISSUE TITLE
[Bug]: Instance crashed for join queries when some tables are empty

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1499]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): cfd62852d57d0cbbb560595151512c2a56d13ef
- Hardware parameters: 
- OS type:
- Others:
```

### Actual Behavior

select sum(lo_revenue) as lo_revenue, d_year, p_brand
from lineorder
join dates on lo_orderdate = d_datekey
join part on lo_partkey = p_partkey
join supplier on lo_suppkey = s_suppkey
group by d_year, p_brand
order by d_year, p_brand;
ERROR 2013 (HY000): Lost connection to MySQL server during query

Log：
goroutine 1079 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.constructViews({0xc010e28000, 0x1, 0x9}, {0xc010f3f340, 0x3, 0x0})
	/matrixone/matrixone/pkg/sql/compile/view.go:31 +0xa5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RunCAQ(0xc010ad2d00, {0x27cd2c0, 0xc00475a088})
	/matrixone/matrixone/pkg/sql/compile/scope.go:797 +0xf58
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc0036d0420, {0x27cd2c0, 0xc00475a088})
	/matrixone/matrixone/pkg/sql/compile/scope.go:534 +0x6e
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc010ad2d00, {0x27cd2c0, 0xc00475a088})
	/matrixone/matrixone/pkg/sql/compile/scope.go:463 +0x705
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0xc0036d07b8)
	/matrixone/matrixone/pkg/sql/compile/scope.go:440 +0x2a
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/matrixone/matrixone/pkg/sql/compile/scope.go:439 +0x425

**Comment by nnsgmsone** [comment]
fix by 1506
