### ISSUE TITLE
[Bug]: mo crash by panic invalid memory address or nil pointer dereference after stability test for about 36 hours on standlone mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15001]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

25192e16dc754091cb4b22b2c4a676e598d98d06

### Other Environment Information

```Markdown
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

 after stability test for about 36 hours on standlone mode ,the mo crash by：
-e8fe-77f6-bb19-367c8e4fe2c5","statement_id":"018e4d0f-3067-7124-8af7-773712f91c1e","txn_id":"018e4d0f306777038afdd64fef85e862/Active/S:1710689824804507934-1"}
{"level":"INFO","time":"2024/03/17 23:37:06.395886 +0800","name":"log-service","caller":"task/task_scheduler.go:72","msg":"task schedule query tasks","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","created":0,"expired":0}
{"level":"INFO","time":"2024/03/17 23:37:06.871249 +0800","name":"log-service.frontend","caller":"frontend/mysql_cmd_executor.go:3909","msg":"time of Exec.Run : 1.261975919s","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 140|127.0.0.1:35906|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 7804|018e45e8-d122-7a47-b96a-592c331a54a2","session_id":"018e45e8-d122-7a47-b96a-592c331a54a2","statement_id":"018e4d0f-3339-75d0-a290-7df8ff979d4b","txn_id":"018e4d0f2c6f7ceb87e73242f9abe4c5/Active/S:1710689825316503878-1"}
{"level":"ERROR","time":"2024/03/17 23:37:07.309201 +0800","name":"log-service.frontend","caller":"frontend/routine_manager.go:297","msg":"Failed to handshake with server, quitting routine...","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"write tcp4 172.27.16.14:6001->124.160.64.91:35723: write: connection reset by peer","session_info":"connectionId 62013|124.160.64.91:35723","session_id":"018e4d0f-39ed-7ec9-afe9-8653b78b8f12"}
{"level":"INFO","time":"2024/03/17 23:37:07.348610 +0800","caller":"dbutils/mem.go:105","msg":"HeapInfo:Alloc:37879MB TotalAlloc:328102909MB Sys:47616MB HeapAlloc:37879MB HeapSys:46165MB HeapIdle:6670MB HeapReleased:2616MB HeapInuse:39495MB"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x2b4a032]

goroutine 16761234 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getProtocol(0xc28afb9ce8?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/frontend/routine.go:146 +0x32
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getConnectionID(0x3529080?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/frontend/routine.go:158 +0x13
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).deleteRoutine(0xc0069c11f0, {0x42bab80, 0xc46b2e5100})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/frontend/routine_manager.go:205 +0xaf
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed(0xc0069c11f0, {0x42bab80, 0xc46b2e5100})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/frontend/routine_manager.go:316 +0x13d
github.com/fagongzi/goetty/v2.(*baseIO).Close(0xc46b2e5100)
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:398 +0x17c
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1.1()
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:351 +0x58
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:359 +0x1b7
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 1047
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x45a

mo-log:
[mo-service-panic.tar.gz](https://github.com/matrixorigin/matrixone/files/14630460/mo-service-panic.tar.gz)

### Steps to Reproduce

```Markdown
1. run tpch 10g loop 
2. run tpcc 10-10 longruuning test
3. run sysbench mixed longrunning test
```

**Comment by daviszhen** [comment]
pr ....

**Comment by aressu1985** [comment]
update on 3.19 分布式测试
commit id: afb4934ae327b7f0b10add4413301524be2221a6
{"level":"ERROR","time":"2024/03/19 01:26:34.269135 +0000","caller":"v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:357","msg":"handle session failed","listen-addresses":"[0.0.0.0:6001,/tmp/mysql.sock]","error":"internal error: routine does not exist"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x442675c]

goroutine 7596474 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getProtocol(0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:146 +0x3c
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getConnectionID(0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:158 +0x2b
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).deleteRoutine(0xc0002fe8c0, {0x5bd5ea0, 0xc5acd07b00})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:205 +0x18e
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed(0xc0002fe8c0, {0x5bd5ea0, 0xc5acd07b00})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:316 +0x20c
github.com/fagongzi/goetty/v2.(*baseIO).Close(0xc5acd07b00)
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:398 +0x21b
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:351 +0x6d
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:359 +0x277
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x705

mo-log:
[cn1.log](https://github.com/matrixorigin/matrixone/files/14644471/cn1.log)
[cn2.log](https://github.com/matrixorigin/matrixone/files/14644472/cn2.log)

**Comment by daviszhen** [comment]
it was fixed.

**Comment by aressu1985** [comment]
fixed
