### ISSUE TITLE
[Bug]: For large size tables, select clause can only output 160,000 rows

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#1501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select count(d1) from ssb_t2;
+-----------+
| count(d1) |
+-----------+
|   6001171 |
+-----------+
1 row in set (0.02 sec)

mysql> select * from sub_t2;
........
| 159331 |    1 | 18080 | 152790 |  288 | 1996-02-22 | 2-HIGH          |    0 |   29 |  5344091 | 29227819 |    0 |  5344091 | 110567 |    3 | 1996-05-01 | RAIL    |
+--------+------+-------+--------+------+------------+-----------------+------+------+----------+----------+------+----------+--------+------+------------+---------+
160000 rows in set (0.30 sec)

**Comment by m-schen** [comment]
fixed. 
due to splice.go's call function only range mergeReciver one time, will lost some batch.

**Comment by m-schen** [comment]
I am not sure if 6 millions may cause out of memory or not,
 you can verify it with a table which contains more than 160000 rows.

**Comment by broccoliSpicy** [comment]
verified , this issue has been resolved
