### ISSUE TITLE
[Bug]: cn crash by panic invalid memory address or nil pointer dereference during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15022]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

afb4934ae327b7f0b10add4413301524be2221a6

### Other Environment Information

```Markdown
- Hardware parameters:
  3*CN: 16C  64G
  1*DN: 16C  64G
  3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed mode, one of cns was crashed by panic:
133-6430-633631376434-1","error":"lock table not found on remote lock service"}
{"level":"INFO","time":"2024/03/18 17:24:18.570171 +0000","name":"cn-service.lockservice","caller":"lockservice/service.go:348","msg":"bind created","uuid":"38383065-3065-3262-6539-353232393339","service":"171074603819645945938383065-3065-3262-6539-353232393339","remote":false,"bind":"272387-171074603819645945938383065-3065-3262-6539-353232393339-2"}
{"level":"INFO","time":"2024/03/18 17:24:18.570474 +0000","name":"cn-service.lockservice","caller":"lockservice/lock_table_remote.go:247","msg":"bind closed","uuid":"38383065-3065-3262-6539-353232393339","remote":true,"bind":"272387-171074603738826558364616335-3839-6133-6430-633631376434-1"}
{"level":"INFO","time":"2024/03/18 17:24:18.570555 +0000","name":"cn-service.lockservice","caller":"lockservice/service.go:584","msg":"bind changed","uuid":"38383065-3065-3262-6539-353232393339","service":"171074603819645945938383065-3065-3262-6539-353232393339","old":"272387-171074603738826558364616335-3839-6133-6430-633631376434-1","new":"272387-171074603819645945938383065-3065-3262-6539-353232393339-2"}
{"level":"ERROR","time":"2024/03/18 17:24:18.571185 +0000","caller":"compile/sql_executor.go:116","msg":"internal sql executor error: lock table not found on remote lock service"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x294879c]

goroutine 880 [running]:
github.com/matrixorigin/matrixone/pkg/incrservice.(*sqlStore).Allocate(0xc003d7ba20, {0x5ba41f8, 0xc40e43a060}, 0x428ae, {0x543e0f1, 0x10}, 0x2dc6c0, {0x0, 0x0})
        /go/src/github.com/matrixorigin/matrixone/pkg/incrservice/store_sql.go:176 +0x69c
github.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).doAllocate(0xc004124b10, {{0x0, 0x0}, 0x0, 0x0, 0x428ae, {0x543e0f1, 0x10}, 0x2dc6c0, 0x0, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:164 +0x195
github.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).run(0xc004124b10, {0x5ba4230, 0xc004124b40})
        /go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:151 +0x1d8
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0xd3
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0x111

mo-log:
[
[cn3.log](https://github.com/matrixorigin/matrixone/files/14644562/cn3.log)
](url)

### Steps to Reproduce

```Markdown
1. run a cluster mo
2. run tpch 10G loog queries
3. run tpcc 10-10 longrunnig test
4. run sysbench mixed cases longrunning test
```

**Comment by zhangxu19830126** [comment]
fixed
