### ISSUE TITLE
[Bug]: incompatible syntax with mysql for insert ignore

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#15020]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

all

### Commit ID

all

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO has a strange syntax for "INSERT IGNORE" as "insert on duplicate key ingore". 

Actually MySQL's INSERT IGNORE is doing exactly the same. No need to invent a new syntax. MO needs to follow MySQL syntax. 

MO's syntax and behavior:

```sql

mysql> CREATE TABLE products (
    ->     product_id INT PRIMARY KEY,
    ->     name VARCHAR(50),
    ->     price DECIMAL(10, 2)
    -> );
Query OK, 0 rows affected (0.16 sec)

mysql> INSERT INTO products (product_id, name, price) VALUES
    -> (1, 'Laptop', 999.99),
    -> (2, 'Smartphone', 499.99),
    -> (3, 'Tablet', 299.99);
Query OK, 3 rows affected (0.03 sec)

mysql> select * from products
    -> ;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
+------------+------------+--------+
3 rows in set (0.02 sec)

mysql> INSERT IGNORE INTO products (product_id, name, price) VALUES
    -> (4, 'Headphones', 99.99),
    -> (1, 'External Hard Drive', 199.99);
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 13 near " IGNORE INTO products (product_id, name, price) VALUES
(4, 'Headphones', 99.99),
(1, 'External Hard Drive', 199.99)";

mysql> INSERT INTO products (product_id, name, price) VALUES (4, 'Headphones', 99.99), (1, 'External Hard Drive', 199.99) on duplicate key ignore;
Query OK, 0 rows affected (0.03 sec)

mysql> select * from products    -> ;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
|          4 | Headphones |  99.99 |
+------------+------------+--------+
4 rows in set (0.02 sec)


```

Below is MySQL syntax and behavior:

```sql
mysql> CREATE TABLE products (
    ->     product_id INT PRIMARY KEY,
    ->     name VARCHAR(50),
    ->     price DECIMAL(10, 2)
    -> );
Query OK, 0 rows affected (0.06 sec)

mysql> 
mysql> INSERT INTO products (product_id, name, price) VALUES
    -> (1, 'Laptop', 999.99),
    -> (2, 'Smartphone', 499.99),
    -> (3, 'Tablet', 299.99);
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from products;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
+------------+------------+--------+
3 rows in set (0.00 sec)

mysql> INSERT IGNORE INTO products (product_id, name, price) VALUES
    -> (4, 'Headphones', 99.99),
    -> (1, 'External Hard Drive', 199.99);
Query OK, 1 row affected, 1 warning (0.01 sec)
Records: 2  Duplicates: 1  Warnings: 1

mysql> select * from products;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
|          4 | Headphones |  99.99 |
+------------+------------+--------+
4 rows in set (0.00 sec)

```

### Steps to Reproduce

```Markdown
INSERT IGNORE INTO products (product_id, name, price) VALUES
    -> (4, 'Headphones', 99.99),
    -> (1, 'External Hard Drive', 199.99);
```

**Comment by heni02** [comment]
confirm,closed
1.1-dev commit:bf48c0d02f61a39d79cb8e4c1b3034bae55c896b
mysql> CREATE TABLE products ( product_id INT PRIMARY KEY,name VARCHAR(50),price DECIMAL(10, 2));
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO products (product_id, name, price) VALUES(1, 'Laptop', 999.99),(2, 'Smartphone', 499.99),(3, 'Tablet', 299.99);
Query OK, 3 rows affected (0.03 sec)

mysql> select * from products;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
+------------+------------+--------+
3 rows in set (0.00 sec)

mysql> INSERT IGNORE INTO products (product_id, name, price) VALUES (4, 'Headphones', 99.99),(1, 'External Hard Drive', 199.99);
Query OK, 0 rows affected (0.05 sec)

mysql> select * from products ;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
|          4 | Headphones |  99.99 |
+------------+------------+--------+
4 rows in set (0.01 sec)

mysql> INSERT IGNORE INTO products (product_id, name, price) VALUES (4, 'Headphones', 99.99),(1, 'External Hard Drive', 199.99);
Query OK, 0 rows affected (0.01 sec)

mysql> select * from products ;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
|          4 | Headphones |  99.99 |
+------------+------------+--------+
4 rows in set (0.00 sec)

**Comment by heni02** [comment]
confirm,closed
main commit：f0a0ba5a77531397b7f13577e7ea1e75ed8d6409
mysql> CREATE TABLE products ( product_id INT PRIMARY KEY,name VARCHAR(50),price DECIMAL(10, 2));
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO products (product_id, name, price) VALUES(1, 'Laptop', 999.99),(2, 'Smartphone', 499.99),(3, 'Tablet', 299.99);
Query OK, 3 rows affected (0.03 sec)

mysql> INSERT IGNORE INTO products (product_id, name, price) VALUES (4, 'Headphones', 99.99),(1, 'External Hard Drive', 199.99);
Query OK, 0 rows affected (0.02 sec)

mysql>  INSERT IGNORE INTO products (product_id, name, price) VALUES (4, 'Headphones', 99.99),(1, 'External Hard Drive', 199.99);
Query OK, 0 rows affected (0.00 sec)

mysql> select * from products ;
+------------+------------+--------+
| product_id | name       | price  |
+------------+------------+--------+
|          1 | Laptop     | 999.99 |
|          2 | Smartphone | 499.99 |
|          3 | Tablet     | 299.99 |
|          4 | Headphones |  99.99 |
+------------+------------+--------+
4 rows in set (0.00 sec)
