### ISSUE TITLE
[Feature Request]: Implement MySQL Encode()/Decode() function

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#15027]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

We've implemented encode/decode functions as PostgreSQL syntax: https://github.com/matrixorigin/matrixone/issues/13825

The key application for these two functions are hex and base64 encoding, which are independent functions in MO. 

MO needs to be compatible with MySQL, encode/decode functions has different purposes in MySQL.

### Describe the feature you'd like

So we need to refactor encode/decode function to MySQL behavior. 

Follow https://www.w3resource.com/mysql/encryption-and-compression-functions/encode().php
https://www.w3resource.com/mysql/encryption-and-compression-functions/decode().php

**Comment by arjunsk** [comment]
Not started.

**Comment by arjunsk** [comment]
We have not implemented UNHEX() to repace DECODE("XX", "hex"). Created a new issue for the same: https://github.com/matrixorigin/matrixone/issues/15261

**Comment by arjunsk** [comment]
current encode/decode will be removed by this PR: https://github.com/matrixorigin/matrixone/pull/15480

**Comment by arjunsk** [comment]
@charleschile has implemented this feature.

**Comment by charleschile** [comment]
I have implemented the Encode and Decode function

**Comment by arjunsk** [comment]
This issue is ready for testing.

**Comment by Ariznawlll** [comment]
test done
