### ISSUE TITLE
[Bug]:  merge run failed by `table not found`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15049]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7516f8f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8340216568

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22RKB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-15033%5C%22%7D%20%7C%3D%20%60invalid%20memory%20address%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221710836892329%22,%22to%22:%221710843063758%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1898" alt="企业微信截图_7324ce4a-1a51-4e97-b26d-a6dbbc7e43f3" src="https://github.com/matrixorigin/matrixone/assets/77312370/b819088f-be2d-4b3d-9260-556898e654ac">

### Steps to Reproduce

```Markdown
merge run
```

**Comment by sukki37** [comment]
repro： https://github.com/matrixorigin/matrixone/actions/runs/8347304215/job/22848842625

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22RKB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-15012%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221710871743000%22,%22to%22:%221710871747000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1373" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/7cad3bf2-b6a2-4b1c-9f6d-65c27cadc5bf">

**Comment by nnsgmsone** [comment]
表是存在的，应该是account id对不上导致的。。

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8358606829

**Comment by nnsgmsone** [comment]
fixed by #15082和#15122
