### ISSUE TITLE
[Bug]:set lower_case_table_names = 0, alter table then show create table, the result of show create table is not case sensitive.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15046]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f6200c30982981b3e7bcf63321b10b7aed4c155b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="479" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d807bbc1-2b6b-40c9-b285-4880ee113bbf">

### Steps to Reproduce

```Markdown
drop table if exists test01;
create table test01 (col1 int, col2 decimal, col3 varchar(50));
insert into test01 values (1, 3242434.423, '3224332r32r');
insert into test01 values (2, 39304.3424, '343234343213124');
insert into test01 values (3, 372.324, '00');

alter table test01 rename column col1 to newCol;
show create table test01;
```

**Comment by sukki37** [comment]
fixed. 0a5786af3da2735110732c94427e15221d365fe6

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/ae7a881d-d572-4630-ae76-60ae32baad03">
