### ISSUE TITLE
[Tech Request]: fileservice: reduce open calls in disk cache

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#15058]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
we can reuse some opened files when dealing with multiple IOEntry.
```

**Comment by sukki37** [comment]
From the profile of querying large datasets, it is observed that when the memory cache size is insufficient and switches to disk cache, the current implementation generates one IO for each IO entry. In scenarios with very large or wide tables, this can result in a very high IOPS. After communicating with @reusee, there is room for optimization in non-metadata paths to reduce the number of disk IOs.
<img width="1460" alt="WeChatWorkScreenshot_476ad527-abda-4c74-ae30-20d9ae8fb0ab" src="https://github.com/matrixorigin/matrixone/assets/77312370/36cc28c0-a91f-4541-9b6c-7d8ff9a31811">

<img width="1462" alt="WeChatWorkScreenshot_180b1ebd-8132-4bf9-973a-4f50a1dab04d" src="https://github.com/matrixorigin/matrixone/assets/77312370/18f573e4-75e1-4b72-bf86-9f1988c2699e">

**Comment by reusee** [comment]
done
