### ISSUE TITLE
[Bug]:  ci test report 'lock table bind changed'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15060]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll:rm14970

### Commit ID

eb0df61b29634cdb7c49639797d22045044b9f29

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
url: https://github.com/matrixorigin/matrixone/actions/runs/8353140706/job/22864388798?pr=15055

<img width="1378" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5497a48f-5e42-403d-9b97-3c74d25054fc">

log:
[multi-cn-e2e-with-proxy-linux-x86-reports (1) 2.zip](https://github.com/matrixorigin/matrixone/files/14661807/multi-cn-e2e-with-proxy-linux-x86-reports.1.2.zip)

### Steps to Reproduce

```Markdown
trigger ci test
```

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by Ariznawlll** [comment]
又出现了一次：
url：https://github.com/matrixorigin/matrixone/actions/runs/8430220230/job/23085741227?pr=15151
<img width="983" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/189006d8-ff99-4f73-9e2a-9b6c88cc34a0">
[Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports.zip](https://github.com/matrixorigin/matrixone/files/14753330/Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64.LAUNCH.PROXY.-reports.zip)

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by Ariznawlll** [comment]
verified.
