### ISSUE TITLE
[Feature Request]: Keep result set column name as user specified in SQL

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#15076]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
create table tt(aa int, bb int, cc int);

insert into tt values (1, 1, 1);


mysql> select * from tt;
+------+------+------+
| aa   | bb   | cc   |
+------+------+------+
|    1 |    1 |    1 |
+------+------+------+
1 row in set (0.00 sec)

mysql> select aA from tt;
+------+
| aa   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql>

mysql> select aa as aA from tt;
+------+
| aA   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)
```

### Describe the feature you'd like

Note that `select aA from tt` will return a result set that the column name is all lower case `aa`

We want a config, 
`
set keep_user_target_list_in_result = 1;
-- when this option is on, we want select aA behaves as if it is select aA as aA
`

Note that this feature is related to, by not the same as the option lower_case_table_names.   lower_case_table_names is about compile/resolve columns.   This is about return result set.

### Describe implementation you've considered

We have already correctly implemented select aA as aA, all we need is the add the option and turn select aA into select aA as aA in parser.   However, I am not sure how to get this info.

**Comment by aronchanisme** [comment]
1. test case: 
```sql
select @@keep_user_target_list_in_result; -- default is 0
set global keep_user_target_list_in_result =1 ;
exit
-- re-login
select @@lower_case_table_names; -- make sure it's set to 1
select @@keep_user_target_list_in_result; -- make sure it's set to 1
create database if not exists test;
use test;
drop table if exists t1;
create table t1(aa int, bb int, cc int, AbC varchar(25), A_BC_d double);
insert into t1 values (1,2,3,'A',10.9);
select * from t1; 
select Aa from t1; -- expected: column displays as 'Aa'
select BB from t1; -- expected: column displays as 'BB'
select aA, bB, CC, abc, a_Bc_D from t1; -- expected: columns display as 'aA', 'bB', 'CC', 'abc', 'a_Bc_D'
```


2. Test result: main-`74464bab5`
```bash
mysql> select @@keep_user_target_list_in_result;
+-----------------------------------+
| @@keep_user_target_list_in_result |
+-----------------------------------+
| 0                                 |
+-----------------------------------+
1 row in set (0.00 sec)

mysql> set global keep_user_target_list_in_result =1 ;
Query OK, 0 rows affected (0.01 sec)

mysql> exit
Bye
2024-04-02 11:53:57.589 UTC+0800    [INFO]    Connect succeeded and finished. Bye
aronchen@momac mo % mo_ctl connect
2024-04-02 11:53:58.776 UTC+0800    [INFO]    Checking connectivity
2024-04-02 11:53:58.826 UTC+0800    [INFO]    Ok, connecting for user ... 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 266
Server version: 8.0.30-MatrixOne-v1.1.2 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@lower_case_table_names; -- make sure it's set to 1
+--------------------------+
| @@lower_case_table_names |
+--------------------------+
| 1                        |
+--------------------------+
1 row in set (0.00 sec)

mysql> select @@keep_user_target_list_in_result; -- make sure it's set to 1
+-----------------------------------+
| @@keep_user_target_list_in_result |
+-----------------------------------+
| 1                                 |
+-----------------------------------+
1 row in set (0.00 sec)

mysql> create database if not exists test;
Query OK, 1 row affected (0.01 sec)

mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> drop table if exists t1;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t1(aa int, bb int, cc int, AbC varchar(25), A_BC_d double);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1,2,3,'A',10.9);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1; 
+------+------+------+------+--------+
| aa   | bb   | cc   | abc  | a_bc_d |
+------+------+------+------+--------+
|    1 |    2 |    3 | A    |   10.9 |
+------+------+------+------+--------+
1 row in set (0.00 sec)

mysql> select Aa from t1; -- expected: column displays as 'Aa'
+------+
| Aa   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql> select BB from t1; -- expected: column displays as 'BB'
+------+
| BB   |
+------+
|    2 |
+------+
1 row in set (0.00 sec)

mysql> select aA, bB, CC, abc, a_Bc_D from t1; -- expected: columns display as 'aA', 'bB', 'CC', 'abc', 'a_Bc_D'
+------+------+------+------+--------+
| aA   | bB   | CC   | abc  | a_Bc_D |
+------+------+------+------+--------+
|    1 |    2 |    3 | A    |   10.9 |
+------+------+------+------+--------+
1 row in set (0.00 sec)

mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 74464bab5     |
+---------------+
1 row in set (0.01 sec)

mysql> exit
Bye
2024-04-02 11:54:35.301 UTC+0800    [INFO]    Connect succeeded and finished. Bye
aronchen@momac mo % mo_ctl get_cid 
2024-04-02 11:54:37.376 UTC+0800    [INFO]    Try get mo commit id
commit 74464bab51abe652c7cf77eb70ab45d66f437abb
Author: YANGGMM <www.yangzhao123@gmail.com>
Date:   Tue Apr 2 11:32:36 2024 +0800

    support create table like stmt (#15232)
    
    support create table like stmt
    
    Approved by: @iamlinjunhong, @ouyuanning, @heni02
2024-04-02 11:54:37.444 UTC+0800    [INFO]    Get commit id succeeded
aronchen@momac mo % mo_ctl get_branch
2024-04-02 11:54:40.220 UTC+0800    [INFO]    Try get mo branch
2024-04-02 11:54:40.268 UTC+0800    [INFO]    Get branch succeeded, current branch: main
```

**Comment by aronchanisme** [comment]
> 1. test case:
> 
> ```sql
> select @@keep_user_target_list_in_result; -- default is 0
> set global keep_user_target_list_in_result =1 ;
> exit
> -- re-login
> select @@lower_case_table_names; -- make sure it's set to 1
> select @@keep_user_target_list_in_result; -- make sure it's set to 1
> create database if not exists test;
> use test;
> drop table if exists t1;
> create table t1(aa int, bb int, cc int, AbC varchar(25), A_BC_d double);
> insert into t1 values (1,2,3,'A',10.9);
> select * from t1; 
> select Aa from t1; -- expected: column displays as 'Aa'
> select BB from t1; -- expected: column displays as 'BB'
> select aA, bB, CC, abc, a_Bc_D from t1; -- expected: columns display as 'aA', 'bB', 'CC', 'abc', 'a_Bc_D'
> ```
> 
> 2. Test result: main-`74464bab5`
> 
> ```shell
> mysql> select @@keep_user_target_list_in_result;
> +-----------------------------------+
> | @@keep_user_target_list_in_result |
> +-----------------------------------+
> | 0                                 |
> +-----------------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> set global keep_user_target_list_in_result =1 ;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> exit
> Bye
> 2024-04-02 11:53:57.589 UTC+0800    [INFO]    Connect succeeded and finished. Bye
> aronchen@momac mo % mo_ctl connect
> 2024-04-02 11:53:58.776 UTC+0800    [INFO]    Checking connectivity
> 2024-04-02 11:53:58.826 UTC+0800    [INFO]    Ok, connecting for user ... 
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 266
> Server version: 8.0.30-MatrixOne-v1.1.2 MatrixOne
> 
> Copyright (c) 2000, 2023, Oracle and/or its affiliates.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql> select @@lower_case_table_names; -- make sure it's set to 1
> +--------------------------+
> | @@lower_case_table_names |
> +--------------------------+
> | 1                        |
> +--------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> select @@keep_user_target_list_in_result; -- make sure it's set to 1
> +-----------------------------------+
> | @@keep_user_target_list_in_result |
> +-----------------------------------+
> | 1                                 |
> +-----------------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> create database if not exists test;
> Query OK, 1 row affected (0.01 sec)
> 
> mysql> use test;
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Database changed
> mysql> drop table if exists t1;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> create table t1(aa int, bb int, cc int, AbC varchar(25), A_BC_d double);
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> insert into t1 values (1,2,3,'A',10.9);
> Query OK, 1 row affected (0.00 sec)
> 
> mysql> select * from t1; 
> +------+------+------+------+--------+
> | aa   | bb   | cc   | abc  | a_bc_d |
> +------+------+------+------+--------+
> |    1 |    2 |    3 | A    |   10.9 |
> +------+------+------+------+--------+
> 1 row in set (0.00 sec)
> 
> mysql> select Aa from t1; -- expected: column displays as 'Aa'
> +------+
> | Aa   |
> +------+
> |    1 |
> +------+
> 1 row in set (0.00 sec)
> 
> mysql> select BB from t1; -- expected: column displays as 'BB'
> +------+
> | BB   |
> +------+
> |    2 |
> +------+
> 1 row in set (0.00 sec)
> 
> mysql> select aA, bB, CC, abc, a_Bc_D from t1; -- expected: columns display as 'aA', 'bB', 'CC', 'abc', 'a_Bc_D'
> +------+------+------+------+--------+
> | aA   | bB   | CC   | abc  | a_Bc_D |
> +------+------+------+------+--------+
> |    1 |    2 |    3 | A    |   10.9 |
> +------+------+------+------+--------+
> 1 row in set (0.00 sec)
> 
> mysql> select git_version();
> +---------------+
> | git_version() |
> +---------------+
> | 74464bab5     |
> +---------------+
> 1 row in set (0.01 sec)
> 
> mysql> exit
> Bye
> 2024-04-02 11:54:35.301 UTC+0800    [INFO]    Connect succeeded and finished. Bye
> aronchen@momac mo % mo_ctl get_cid 
> 2024-04-02 11:54:37.376 UTC+0800    [INFO]    Try get mo commit id
> commit 74464bab51abe652c7cf77eb70ab45d66f437abb
> Author: YANGGMM <www.yangzhao123@gmail.com>
> Date:   Tue Apr 2 11:32:36 2024 +0800
> 
>     support create table like stmt (#15232)
>     
>     support create table like stmt
>     
>     Approved by: @iamlinjunhong, @ouyuanning, @heni02
> 2024-04-02 11:54:37.444 UTC+0800    [INFO]    Get commit id succeeded
> aronchen@momac mo % mo_ctl get_branch
> 2024-04-02 11:54:40.220 UTC+0800    [INFO]    Try get mo branch
> 2024-04-02 11:54:40.268 UTC+0800    [INFO]    Get branch succeeded, current branch: main
> ```

@Ariznawlll  Hi, could you please kindly help add some bvt cases? Thanks a lot.

**Comment by dengn** [comment]
Please set keep_user_target_list_in_result's default value to 1. @YANGGMM

**Comment by aronchanisme** [comment]
mysql 8.0.35 by default acts the same as what mo does when the value of mo's variable `keep_user_target_list_in_result` is set to `1`. 
```bash
mysql> select @@keep_user_target_list_in_result;
ERROR 1193 (HY000): Unknown system variable 'keep_user_target_list_in_result'
mysql> create database test;
Query OK, 1 row affected (0.03 sec)

mysql> use test;
Database changed
mysql> create table t1(aa int, bb int, cc int, AbC varchar(25), A_BC_d double);
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t1 values (1,2,3,'A',10.9);
Query OK, 1 row affected (0.01 sec)

mysql> select * from t1; 
+------+------+------+------+--------+
| aa   | bb   | cc   | AbC  | A_BC_d |
+------+------+------+------+--------+
|    1 |    2 |    3 | A    |   10.9 |
+------+------+------+------+--------+
1 row in set (0.00 sec)

mysql> select Aa from t1; -- expected: column displays as 'Aa'
+------+
| Aa   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql> select BB from t1; -- expected: column displays as 'BB'
+------+
| BB   |
+------+
|    2 |
+------+
1 row in set (0.01 sec)

mysql> select aA, bB, CC, abc, a_Bc_D from t1; -- expected: columns display as 'aA', 'bB', 'CC', 'abc', 'a_Bc_D'
+------+------+------+------+--------+
| aA   | bB   | CC   | abc  | a_Bc_D |
+------+------+------+------+--------+
|    1 |    2 |    3 | A    |   10.9 |
+------+------+------+------+--------+
1 row in set (0.01 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.35    |
+-----------+
1 row in set (0.00 sec)
```

**Comment by Ariznawlll** [comment]
test done.
