### ISSUE TITLE
[Bug]: TPCH Q1报错lost connection

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#15086]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9cfc95e37b3b109df6283df2b75ad5cd95594927

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
云平台，实例ID: 018e5fde-2f57-7c73-9ca9-4ec15e45a063
```

### Actual Behavior

1. 创建standard实例，命令链接，执行TPCH Q1
2. 报错 lost connection
3. 具体详见 https://github.com/matrixorigin/MO-Cloud/issues/2743

### Expected Behavior

正常执行

### Steps to Reproduce

```Markdown
如上
```

**Comment by triump2020** [comment]
@qingxinhome  Pls take a look.

**Comment by DanielZhangQD** [comment]
@xiaoshuwei 确认下是否测试使用的小机型导致 CN OOM

**Comment by xiaoshuwei** [comment]
目前重新测了原先出问题的实例，问题又消失了，先关掉，如果复现再进一步观察。
