### ISSUE TITLE
[Bug]: performance：sysbench delete test which include auto_increment and index 80% lower performance than non auto_increment index

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15085]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bc9bb21a0028b5fefdd13fe48b3bcd35d2f4a8b1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.目前回归delete性能下降问题，使用3.10号回归的commit：3347a4c分别测试有自增列索引和无自增列索引情况，可以排除版本原因导致delete的性能下降，是有自增列和索引导致的性能下降
<img width="1261" alt="企业微信截图_93c2e6ab-2d83-4f45-87a3-9103a811b350" src="https://github.com/matrixorigin/matrixone/assets/113406637/7dc4fbaf-ffe7-4ff2-b51c-0996247127a5">

sysbench delete 有自增列和索引情况下tps：5527
<img width="1221" alt="企业微信截图_3ee27619-a743-4cfd-a750-8fb30e41ae1f" src="https://github.com/matrixorigin/matrixone/assets/113406637/0375fa70-2c46-4604-8b33-c84590d6296f">
测试命令：
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable  oltp_delete.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=300 --report-interval=10 --range_selects=off --point_selects=1 run

sysbench delete 无自增列和索引情况下tps：31786
<img width="1237" alt="企业微信截图_9b7c31d7-eb75-418e-bacb-8356bd308e14" src="https://github.com/matrixorigin/matrixone/assets/113406637/a171cf3d-bf35-4950-a79e-01633ebb6ddf">
测试命令：
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable  oltp_delete.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=300 --report-interval=10 --create_secondary=off  --auto_inc=off  --range_selects=off --point_selects=1 run

2. sysbench update test as well
<img width="1350" alt="企业微信截图_4edbc267-d704-48cc-a267-a82da7cba518" src="https://github.com/matrixorigin/matrixone/assets/113406637/9fa4d987-aed1-4fe8-959e-3fea392000ff">

### Steps to Reproduce

```Markdown
sysbench 100w delete 100threads
```

**Comment by arjunsk** [comment]
@w-zr / @heni02  Is this related to auto-increment performance degradation?

**Comment by heni02** [comment]
tke sysbench 1000w delete tps only 5
<img width="1064" alt="企业微信截图_4feef7b7-d796-4dbd-9cdc-25895d3186ae" src="https://github.com/matrixorigin/matrixone/assets/113406637/1345ac36-a2d1-4e1a-9019-f0cd8185ba59">

**Comment by aunjgr** [comment]
@jensenojs 能否先看看？谢谢

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
使用 `--table_size=1000000 --threads=100 --time=300 `在如下几种情况做对比
- 无次级索引, 无auto-incr : 8034.07 per sec
- 有次级索引, 无auto-incr : 4176.81  per sec
- 无次级索引, 有auto-incr : 8040.19 per sec
- 有次级索引, 有auto-incr : 4132.40 per sec

推测是次级索引的问题, 对比如下两个table的delete计划
```sql
create table t   (a int);
create table ts (a int key(a));
```

<img width="1505" alt="Pasted Graphic" src="https://github.com/matrixorigin/matrixone/assets/56761542/db999f22-c044-4cb1-9c99-e891314666b6">

其结果如上显示.

addition info :

之前动哥提过一个类似的问题, 当时是用如下两个issue来跟踪的. 不过没什么后续和进展

- https://github.com/matrixorigin/matrixone/issues/14996
- https://github.com/matrixorigin/matrixone/issues/14969

**Comment by jensenojs** [comment]
这里也有一点历史遗留问题没有做干净

- https://github.com/matrixorigin/matrixone/issues/13000

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理
- https://github.com/matrixorigin/matrixone/issues/15809

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working ont it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
update : 

```
commit ec0a791e6fe0ecb1cc2ba3c233289164f55574c0
Author: nitao <badboynt@126.com>
Date:   Sat Oct 19 15:13:43 2024 +0800

    optimize shrink batch in filter operator (#19450)

    optimize shrink batch in filter operator

    Approved by: @m-schen

```

深圳pc基于这个分支, 100并发, 跑两分钟, 对比有索引无自增列和有索引有自增的情况

- 有索引无自增列
<img width="1553" alt="Pasted Graphic 9" src="https://github.com/user-attachments/assets/769d71f7-318c-4712-b218-635fdef069b7">

- 有索引有自增
<img width="1601" alt="Pasted Graphic 10" src="https://github.com/user-attachments/assets/d601d74a-4a85-441c-8e56-57c34f9bb8bb">

**Comment by heni02** [comment]
commit:5bc27a6fa0a6767f2a3d6a1146a4943a550c731e
128单机回归验证
sysbench delete 有自增列有索引tps：22830
sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable oltp_delete.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=300 --report-interval=10 --range_selects=off --point_selects=1 run
<img width="772" alt="企业微信截图_9c5a5bb7-5fb4-4ed4-a269-d2bc0b3ee9f8" src="https://github.com/user-attachments/assets/9a76249a-f7ff-469d-9ce0-9e7f037ede81">

sysbench delete 无自增列和索引情况下tps：35611
<img width="807" alt="企业微信截图_b3b16aee-5d77-4e21-8b7a-5c9213a997f0" src="https://github.com/user-attachments/assets/5e419466-5d09-4ab1-8eed-ab7e06589a42">
 
两种性能情况相差较小了，没有80%以上的情况，closed
