### ISSUE TITLE
[Bug]: load data report 'unterminated quoted field'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15084]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2e5d3ba8375a2c44fe4bb4f890f99fd936e05e03

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
情景一：
<img width="1428" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c7dc5d24-50d2-4dda-a3d4-9e0ec461b74e">

[test_escaped_by01.csv](https://github.com/matrixorigin/matrixone/files/14687140/test_escaped_by01.csv)

### Steps to Reproduce

```Markdown
情景1:
create table t5 (col1 varchar(20), col2 varchar(60));

load data local infile '/path/test_escaped_by01.csv' into table t5
fields terminated by ',' enclosed by '"' escaped by '\\' lines terminated by '\n';

```

**Comment by noorall** [comment]
报错类型不对的问题已经修复

**Comment by Ariznawlll** [comment]
commit:f0a0ba5a77531397b7f13577e7ea1e75ed8d6409
<img width="1179" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0316f91d-fafe-4599-85b9-36a5f70b214d">

Verified.

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
