### ISSUE TITLE
[Bug]: [0321] sysbench update non-index test on tke report 'Lost connection to MySQL server during query'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15089]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

71f3515c9270840cc040b276878c6c91993ceae2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8363373798/job/22913372584 
(sysbench oltp test 100w->update-non-index 100 theads)

<img width="1022" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b4aa4cc9-c09a-4ca4-b734-d7df68c8fdb1">

查看了出错(Lost connection to MySQL server during query)期间的内存使用情况，非oom：
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20240320&from=1710991969000&to=1710992209000

pod状态：
<img width="580" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/96c59132-1c36-4709-84e2-f6f71f6cb1ea">
<img width="766" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/005f71a8-fa37-44df-8976-35b82b4cb8a0">

mo日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22mvG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240320%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger daily regression on tke.
```

**Comment by w-zr** [comment]
![Image](https://github.com/matrixorigin/matrixone/assets/28624654/f6cf5738-1e1f-4f70-8d10-764fbf47419c)

**Comment by gouhongshen** [comment]
加了 log, 等待复现

**Comment by gouhongshen** [comment]
等复现

**Comment by gouhongshen** [comment]
等复现

**Comment by gouhongshen** [comment]
等复现

**Comment by gouhongshen** [comment]
未复现

**Comment by gouhongshen** [comment]
长时间未复现，要不要先 close 一下 @Ariznawlll

**Comment by aressu1985** [comment]
先关闭，等复现了再重新提issue跟踪
