### ISSUE TITLE
[Feature Request]: MD5 and SHA1

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#15096]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
While MD5 and SHA1 are considered obsolete/broken, they are commonly used in many applications.
```

### Describe the feature you'd like

Implement these functions.

**Comment by xxxuuu** [comment]
I'd like to work on this issue

**Comment by YANGGMM** [comment]
supported, plz test!

**Comment by heni02** [comment]
test done
