### ISSUE TITLE
[Bug]:Error on load data.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15110]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d65a9e33ef2faba5d52991054009319084bd9bd7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**情景一：**
<img width="1657" alt="image" src="https://github.com/user-attachments/assets/646529d9-978d-43c1-82f1-4f634f25c038">
数据：
[test_enclosed_by01.csv](https://github.com/matrixorigin/matrixone/files/14716605/test_enclosed_by01.csv)

情景二：
<img width="1653" alt="image" src="https://github.com/user-attachments/assets/518c2837-8f10-4609-b108-b7bde9080824">
数据：
[test_escaped_by03.csv](https://github.com/matrixorigin/matrixone/files/14718080/test_escaped_by03.csv)

### Steps to Reproduce

```Markdown
情景一：
create table t7(col1 varchar(20), col2 varchar(20));
load data infile '/pathl/test_enclosed_by01.csv' into table t7 fields terminated by ',' enclosed by '"' lines terminated by '\n';

情景二：
create table t9 (col1 varchar(20), col2 varchar(20), col3 varchar(20));
load data local infile '/path/test_escaped_by03.csv' into table t9 fields terminated by ',' enclosed by '"' escaped by '\\' lines terminated by '\n';
```

**Comment by allengaoo** [comment]
按照以下mysql文档的描述，其场景1，2 的返回结果是符合预期的，建议 MO 兼容MySQL 的行为，
https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-field-line-handling

**Comment by Ariznawlll** [comment]
情景一：
<img width="1593" alt="image" src="https://github.com/user-attachments/assets/d52ec0df-380d-47f6-b696-9388e2780619">

情景二：
<img width="1686" alt="image" src="https://github.com/user-attachments/assets/5b2e55af-1359-4e96-8e38-a523944df1b3">

测试通过
