### ISSUE TITLE
[Bug]: Vector and tinyint type arithemetic operation are not supported

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15115]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

eb19440b2803aaf024b8041918e59227de9abdae

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

c2 is vector and c3 is tinyint type，c2+c3 not support，but int and bigint is support
mysql> select c2+c3 from vector_exp_01;
ERROR 20203 (HY000): invalid argument operator +, bad value [VECF32 TINYINT]

tinyint unsigned ,smallint,smallint unsigned,int unsigned not support as well 
mysql> select c2+c1 from vector_exp_01;
ERROR 20203 (HY000): invalid argument operator +, bad value [VECF32 INT UNSIGNED]

### Steps to Reproduce

```Markdown
create table vector_exp_01(c1 int,c2 vecf32(5),c3 tinyint unsigned,c4 bigint,c5 decimal(4,2),c6 float,c7 double);
insert into vector_exp_01 values(10 ,"[1, 0, 1, 6, 6]",3,10,7.1,0.36,2.10),(60,"[6, 0, 8, 10,129]",2,5,3.26,4.89,1.26),(20,"[ 9, 18, 1, 4, 132]",6,1,9.36,6.9,5.6);
select c2+c3 from vector_exp_01;
```

**Comment by arjunsk** [comment]
Will start working after https://github.com/matrixorigin/matrixone/issues/14610

**Comment by arjunsk** [comment]
No progress.

**Comment by arjunsk** [comment]
Merged to master

**Comment by heni02** [comment]
confirm.closed
commit:652cc255d9075ad1cf683f88bcd66d132fe98dcc
mysql> create table vector_exp_01(c1 int,c2 vecf32(5),c3 tinyint unsigned,c4 bigint,c5 decimal(4,2),c6 float,c7 double);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into vector_exp_01 values(10 ,"[1, 0, 1, 6, 6]",3,10,7.1,0.36,2.10),(60,"[6, 0, 8, 10,129]",2,5,3.26,4.89,1.26),(20,"[ 9, 18, 1, 4, 132]",6,1,9.36,6.9,5.6);
Query OK, 3 rows affected (0.02 sec)

mysql> select c2+c3 from vector_exp_01;
+----------------------+
| c2 + c3              |
+----------------------+
| [4, 3, 4, 9, 9]      |
| [8, 2, 10, 12, 131]  |
| [15, 24, 7, 10, 138] |
+----------------------+
3 rows in set (0.01 sec)
