### ISSUE TITLE
[Bug]: Panic in BinaryFuse Filter Unmarshall

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#15118]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bf6976783ced1da0dc93c6911cbedbfb3300aabe

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sql
SELECT a FROM t3 ORDER BY l2_distance(b,'[1.0,3.0,11.0,110.0,62.0,22.0,4.0,0.0,43.0,21.0,22.0,18.0,6.0,28.0,64.0,9.0,11.0,1.0,0.0,0.0,1.0,40.0,101.0,21.0,20.0,2.0,4.0,2.0,2.0,9.0,18.0,35.0,1.0,1.0,7.0,25.0,108.0,116.0,63.0,2.0,0.0,0.0,11.0,74.0,40.0,101.0,116.0,3.0,33.0,1.0,1.0,11.0,14.0,18.0,116.0,116.0,68.0,12.0,5.0,4.0,2.0,2.0,9.0,102.0,17.0,3.0,10.0,18.0,8.0,15.0,67.0,63.0,15.0,0.0,14.0,116.0,80.0,0.0,2.0,22.0,96.0,37.0,28.0,88.0,43.0,1.0,4.0,18.0,116.0,51.0,5.0,11.0,32.0,14.0,8.0,23.0,44.0,17.0,12.0,9.0,0.0,0.0,19.0,37.0,85.0,18.0,16.0,104.0,22.0,6.0,2.0,26.0,12.0,58.0,67.0,82.0,25.0,12.0,2.0,2.0,25.0,18.0,8.0,2.0,19.0,42.0,48.0,11.0]') ASC LIMIT 100;

Hangs.
```

### Expected Behavior

Should return 100 rows

### Steps to Reproduce

1. Build [this](https://github.com/arjunsk/matrixone/tree/bug/perf_vec_index) branch.
2. Download the SQL import file from [S3](https://s3.console.aws.amazon.com/s3/object/vector-test-data?region=us-east-2&bucketType=general&prefix=sift128_no_index.sql.zip).
3. Import using the below query
```sql
source /Users/arjunsunilkumar/GolandProjects/mo_dump/sift128_no_index.sql
```
4. Once the table is imported, run
```sql
mysql> create index idx3 using ivfflat on t3(b) lists=500 op_type "vector_l2_ops";
Query OK, 0 rows affected (6 min 8.79 sec)
```
5. Run the query
```sql
SELECT a FROM t3 ORDER BY l2_distance(b,'[1.0,3.0,11.0,110.0,62.0,22.0,4.0,0.0,43.0,21.0,22.0,18.0,6.0,28.0,64.0,9.0,11.0,1.0,0.0,0.0,1.0,40.0,101.0,21.0,20.0,2.0,4.0,2.0,2.0,9.0,18.0,35.0,1.0,1.0,7.0,25.0,108.0,116.0,63.0,2.0,0.0,0.0,11.0,74.0,40.0,101.0,116.0,3.0,33.0,1.0,1.0,11.0,14.0,18.0,116.0,116.0,68.0,12.0,5.0,4.0,2.0,2.0,9.0,102.0,17.0,3.0,10.0,18.0,8.0,15.0,67.0,63.0,15.0,0.0,14.0,116.0,80.0,0.0,2.0,22.0,96.0,37.0,28.0,88.0,43.0,1.0,4.0,18.0,116.0,51.0,5.0,11.0,32.0,14.0,8.0,23.0,44.0,17.0,12.0,9.0,0.0,0.0,19.0,37.0,85.0,18.0,16.0,104.0,22.0,6.0,2.0,26.0,12.0,58.0,67.0,82.0,25.0,12.0,2.0,2.0,25.0,18.0,8.0,2.0,19.0,42.0,48.0,11.0]') ASC LIMIT 100;
```

**Comment by arjunsk** [comment]
This issue occurs in my branch when I am replacing `INNER JOIN` with `INDEX JOIN` for vector index.
Based on the discussion with @badboynt1 , the issue occurs due to "it's a bug in bloom filter in fastranges."

![企业微信截图_17111018623158](https://github.com/matrixorigin/matrixone/assets/9638314/2ea03b17-67de-419f-b856-108d8d278b4a)

![企业微信截图_17111018799683](https://github.com/matrixorigin/matrixone/assets/9638314/868adbd6-13ab-4e0d-938a-e14fcc09c6cf)

it actually panic here.

**Comment by XuPeng-SH** [comment]
Hi @arjunsk,
It will only load bloom filters if the "=" or "IN" filter applied to the primary key is pushdown. There have been some similar issues before, caused by using the wrong column, since only the primary key column had a bloom filter.
<img width="986" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/97a4ada5-e4ac-4b3f-8c0d-4bbfb4f1ea59">

Hi@gouhongshen , please help to investigate the cause of the problem with this branch

**Comment by gouhongshen** [comment]
```sql
SELECT a FROM t3 ORDER BY l2_distance(b,'[1.0,3.0,11.0,110.0,62.0,22.0,4.0,0.0,43.0,21.0,22.0,18.0,6.0,28.0,64.0,9.0,11.0,1.0,0.0,0.0,1.0,40.0,101.0,21.0,20.0,2.0,4.0,2.0,2.0,9.0,18.0,35.0,1.0,1.0,7.0,25.0,108.0,116.0,63.0,2.0,0.0,0.0,11.0,74.0,40.0,101.0,116.0,3.0,33.0,1.0,1.0,11.0,14.0,18.0,116.0,116.0,68.0,12.0,5.0,4.0,2.0,2.0,9.0,102.0,17.0,3.0,10.0,18.0,8.0,15.0,67.0,63.0,15.0,0.0,14.0,116.0,80.0,0.0,2.0,22.0,96.0,37.0,28.0,88.0,43.0,1.0,4.0,18.0,116.0,51.0,5.0,11.0,32.0,14.0,8.0,23.0,44.0,17.0,12.0,9.0,0.0,0.0,19.0,37.0,85.0,18.0,16.0,104.0,22.0,6.0,2.0,26.0,12.0,58.0,67.0,82.0,25.0,12.0,2.0,2.0,25.0,18.0,8.0,2.0,19.0,42.0,48.0,11.0]') ASC LIMIT 100;
```

this SQL will use the `fake_pk_col` to retrieve the column `a`, causing a decoding of the bloom filter on `fake_pk_col`, but there isn't a bloom filter on the fake PK column, so panic.


this can be repro simply :
```sql
drop database if exists testdb;
create database testdb;
use testdb;
create table hhh (a int, b int, index(`b`));
insert into hhh select *,* from generate_series(1, 81920)g;
select a from hhh where b = 999;
```

**Comment by arjunsk** [comment]
Fixed
