### ISSUE TITLE
[Bug]: the performance of point select on pk will have halved over times.

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#15116]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.1-dev

### Commit ID

main eb6d613581d013c3bdbd9503bf82ccf9de254ac7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

#

### Expected Behavior

point select on pk of a small/empty table benchmarking on the 129-machine with 256 terminals.

the first minutes: 
<img width="1335" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/2b50e0ef-b797-4f2a-8c2e-e0adfce2fbc3">

<img width="1123" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/451c156b-1922-4458-8c49-5f33145d96e3">

|

<br>

and the performance decreased:

<img width="1329" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/50ce006e-fdb3-447f-b927-97d3d81329fd">

<img width="1240" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/4575355c-7c4f-48a0-99f5-3e1af417c6d1">

|

why has the performance decreased?
we can see along with the performance halved, the running threads also stay very low.

<img width="1530" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/4874ac62-3a48-4a90-8df1-c1387fa60c95">

|

comparing the traces of them, found that the latter blocked on a chan:

<img width="1256" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/00477ab1-4a97-4dca-a03e-9c914c42ab51">
 
that's why the running threads decreased, 

the source code is located:

```go
const defaultQueueSize = 1310720 // queue mem cost = 10MB

//...

awakeCollect:   make(chan batchpipe.HasName, defaultQueueSize),

//...

// Collect item in chan, if collector is stopped then return error
func (c *MOCollector) Collect(ctx context.Context, item batchpipe.HasName) error {
	select {
	case <-c.stopCh:
		ctx = errutil.ContextWithNoReport(ctx, true)
		return moerr.NewInternalError(ctx, "MOCollector stopped")
	case c.awakeCollect <- item:
		return nil
	}
}
```

the tps can last longer by augmenting the `defaultQueueSize`.

### Steps to Reproduce

```Markdown
mo-load

`./start.sh -n 1 -s 100000 -m SYSBENCH -g -b sbtest`

`./start.sh -c cases/sysbench/point_select_1_10W_prepare/ -d 15 -t 256 -g -b sbtest`
```

**Comment by xzxiong** [comment]
129: 64c128g

**Comment by xzxiong** [comment]
No plan yet

**Comment by xzxiong** [comment]
No plan yet

**Comment by xzxiong** [comment]
No plan yet

**Comment by xzxiong** [comment]
No plan yet

**Comment by xzxiong** [comment]
No plan yet

**Comment by xzxiong** [comment]
No plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
need regression test, after https://github.com/matrixorigin/matrixone/pull/17863 merged.

**Comment by gouhongshen** [comment]
```yaml
replace:
- name: id
  type: random
  range: 1,100000
- name: i_id
  type: sequence
  start: 100001
  step: 1
- name: tbx
  type: random
  range: 1,1
```

point_select_10_100000_prepare/replace.yaml 内容换成上面的就行

**Comment by xzxiong** [comment]
regression
env:
- dev: szdev
- cpu: 16 c
- memory: 32 g

case: point_select_1_10W_prepare

two obj:
1. base: commit id: `dcb07ac9e`
2. refactor: commit id: `bca6edc16`

test result:
1. refactor version 更稳定，基本在  29992 ~ 31444 之间波动
2. base version 性能更差，波动更大，测试开始1min, tps 区间29000 ~ 31421， 测试后续 10min，tps 区间 17487~21736 波动

[result.15116.tgz](https://github.com/user-attachments/files/16508032/result.15116.tgz)

```diff
- [point_select_1_10W_prepare]
- START : 2024-08-06 16:08:12
- END : 2024-08-06 16:23:24
- VUSER : 256
- TPS : 21452
- QPS : 21452
- SUCCESS : 19330279
- ERROR : 0
- RT_MAX : 1759
- RT_MIN : 0
- RT_AVG : 11.93
- SUC_RATE : 1.0
- EXP_RATE : 1.0
- RESULT : SUCCEED
+ point_select_1_10W_prepare]
+ TART : 2024-08-06 16:31:57
+ ND : 2024-08-06 16:47:09
+ USER : 256
+ PS : 30393
+ PS : 30393
+ UCCESS : 27358263
+ RROR : 0
+ T_MAX : 275
+ T_MIN : 0
+ T_AVG : 8.42
+ UC_RATE : 1.0
+ XP_RATE : 1.0
+ ESULT : SUCCEED
```

**Comment by gouhongshen** [comment]
后续在 129 上面测一下

**Comment by aressu1985** [comment]
FIXED
