### ISSUE TITLE
[Bug]: stream closed error during sysbench write_only case 1000w data after oom on distributed mode benchamrk regression test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

9407263

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8406974229/job/23030301205

<img width="1148" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/660cf8a4-eb7d-4de2-8c8a-5df19b37ee45">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22x03%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-9407263%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711308554941%22,%22to%22:%221711314794941%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run sysbench write_only 1000w base data
```

**Comment by heni02** [comment]
stream closed报错后3个cn都重启了，定位后发现mem使用没有超出55G，日志里也没出现panic和fatal错误，需定位下stream closed和cn重启的原因
<img width="1387" alt="企业微信截图_36998d79-2973-4c3a-80d1-0337aee4ddb3" src="https://github.com/matrixorigin/matrixone/assets/113406637/f468d02d-840d-455f-937e-56019a1eab07">

https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&from=now-24h&to=now&var-datasource=prometheus&var-cluster=&var-namespace=branch-reg-9407263

**Comment by aylei** [comment]
<img width="1920" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18556593/2d192806-1002-47fd-b6f0-63a72db34983">

是因为 OOM 了

**Comment by nnsgmsone** [comment]
stream close的问题旭哥已经修复，不过为啥会阻塞这么久还没查明。

**Comment by nnsgmsone** [comment]
还未处理

**Comment by nnsgmsone** [comment]
处理https://github.com/matrixorigin/matrixone/issues/15381中

**Comment by nnsgmsone** [comment]
no process

**Comment by heni02** [comment]
main分支目前有位解决问题，待解决后验证

**Comment by heni02** [comment]
main分支目前有位解决问题，无法回归，待解决后验证

**Comment by Ariznawlll** [comment]
stream closed问题还在
1.1-dev commit: a6e45fcd791c9852a6041c8981cb0b9b0bda04cf
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8864165377/job/24347551096

<img width="934" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2905e925-d179-492e-8a0e-922b3607b5c6">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22aL1%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-reg-a6e45fc%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ouyuanning** [comment]
蛮多PR没有合并到1.1-dev的。
建议在main上再观察一下

**Comment by Ariznawlll** [comment]
观察中

**Comment by Ariznawlll** [comment]
最近没出现了
