### ISSUE TITLE
[Refactoring]:  Fix TestParseExecuteData in mysql_protocol_test.go

### ISSUE THREAD

**Issue by forsaken628** [matrixorigin/matrixone#15125]
### Why do you want to refactor this code?

https://github.com/matrixorigin/matrixone/blob/c79dd3958971a915fdedbdb51f54e8957dbc72fc/pkg/frontend/mysql_protocol_test.go#L2204

### Describe the solution you'd like

fix test

### Additional information

https://github.com/matrixorigin/matrixone/pull/10203/commits/ae950f639091575bf0dc1452ca43cfc6bab6eaee#diff-e6b33be301283d85ec5e07d87fa0d6d826a68d7810019b613d315659f329ebacR2224

https://github.com/matrixorigin/matrixone/pull/10203/commits/77541ad1f7b3fe6ce43a866aa6db7ad9d78530e2#diff-df9bbc34115212918609e47ad31cf72bf7b2be07d21c34c045074def608d0462R546

https://github.com/matrixorigin/matrixone/pull/10203/commits/cb18683f150311f7b084cf5b6323e0691b834a09#diff-e6b33be301283d85ec5e07d87fa0d6d826a68d7810019b613d315659f329ebacR2191

**Comment by YANGGMM** [comment]
thanks for your conbribution @forsaken628
