### ISSUE TITLE
[Bug]: Vector and Scalar arithemetic operation results is [+Inf, +Inf]

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15121]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

eb19440

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

arithemetic operation result out of float or double type, the result is [+Inf, +Inf], this is not expected
select cast("[76875768584509877574546435800000005,8955885757767774774774774456466]" as vecf32(2)) *623585864455;
cast([76875768584509877574546435800000005,8955885757767774774774774456466] as vecf32(2)) * 623585864455
[+Inf, +Inf]

and insert [+Inf, +Inf] into vector type is successfully, this is not expected as well
<img width="672" alt="企业微信截图_ba94ff41-ccb7-48c7-a9b1-decb04a24192" src="https://github.com/matrixorigin/matrixone/assets/113406637/4922a35a-5387-4f87-8343-3bd6fedef2a4">

### Steps to Reproduce

```Markdown
select cast("[76875768584509877574546435800000005,8955885757767774774774774456466]" as vecf32(2)) *623585864455;
```

**Comment by arjunsk** [comment]
Will start working after https://github.com/matrixorigin/matrixone/issues/14610

**Comment by arjunsk** [comment]
PR merged.

**Comment by heni02** [comment]
confirm,closed 
commit:652cc255d9075ad1cf683f88bcd66d132fe98dcc
mysql> select cast("[76875768584509877574546435800000005,8955885757767774774774774456466]" as vecf32(2)) *623585864455;
ERROR 20101 (HY000): internal error: vector contains infinity values
