### ISSUE TITLE
[Bug]: wrong user name but still could login

### ISSUE THREAD

**Issue by EZ4BRUCE** [matrixorigin/matrixone#15135]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

8.0.30-MatrixOne-v1.1.2

### Commit ID

9407263e2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u' 018e59d1_e4e9_7d6d_bef2_a0639d30e18e:admin:accountadmin' -p
```

的 username 前面有空格，但是输入正确密码后仍然可以正常登陆

### Expected Behavior

应该不能登录才对

### Steps to Reproduce

```Markdown
mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u' 018e59d1_e4e9_7d6d_bef2_a0639d30e18e:admin:accountadmin' -p
```

**Comment by XuPeng-SH** [comment]
@daviszhen please help to look into this bug

**Comment by daviszhen** [comment]
未投入

**Comment by forsaken628** [comment]
https://github.com/matrixorigin/matrixone/blob/9407263e261fbb5badc4cccc7b890f7443435df9/pkg/frontend/authenticate.go#L254
https://github.com/matrixorigin/matrixone/blob/9407263e261fbb5badc4cccc7b890f7443435df9/pkg/frontend/authenticate_test.go#L65

Is this?

**Comment by daviszhen** [comment]
@ck89119  帮看下。

**Comment by ck89119** [comment]
当前mo会对tenant（类似还有user，role）做trimSpace
<img width="1075" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/86205180-9dec-4d48-884b-55ae707b3ea5">

测试了下mysql，加空格会报错
<img width="748" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/848d69b5-6da4-4413-8e2d-0c33344392b6">

**Comment by LiSong0214** [comment]
首先，这个行为与 mysql 是一致的，因为 -u ' root' 我们也会报错；
其次，这个思维与 mysql 不一致，所以我们需要把空格当作有效字符，无论空格在 account_name、database_name 或 role_name 前，都报错。

**Comment by EZ4BRUCE** [comment]
close as fixed
