### ISSUE TITLE
[Bug]: [date 3.23]tke regression: sysbench test after reported Duplicate entry error not exit ，always hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15140]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2674995df

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8403426531/job/23017476777
<img width="1031" alt="企业微信截图_c562055a-fb0d-4393-9172-e52e56d25847" src="https://github.com/matrixorigin/matrixone/assets/113406637/1bf63f7d-07b4-4ebc-a564-73ff35fc1196">

之前也出现过Duplicate entry错误，测试会直接退出不再继续运行，但最近几天报了该错误后无法退出一直hung，怀疑很多session没有closed，需要定位

log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22WhO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240323%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711238284000%22,%22to%22:%221711238338000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
sysbench 10w read_write test
```

**Comment by daviszhen** [comment]
@ck89119 帮忙看下。

**Comment by heni02** [comment]
date 5.3 tke regression 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8940629660/job/24569679599
<img width="1288" alt="企业微信截图_d082730a-f102-4801-b42f-5a7ab21b7917" src="https://github.com/matrixorigin/matrixone/assets/113406637/87180ee7-9e17-40e7-85fa-6ba3ba13e22d">
mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Qq4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240503%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714768123000%22,%22to%22:%221714771808000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by heni02** [comment]
date 5.16 regression 复现，报了dup后现象mo hung
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9114235510/job/25069419376
<img width="1340" alt="企业微信截图_6b401982-a913-4c3f-b7d7-ef1581f816e3" src="https://github.com/matrixorigin/matrixone/assets/113406637/bdad8d1a-68f4-4c08-baf0-c6a6bb884c2f">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22C5l%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240516%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715890350000%22,%22to%22:%221715892044000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile already transfered to  location

**Comment by daviszhen** [comment]
![Selection_014](https://github.com/matrixorigin/matrixone/assets/60595215/82f752cb-fe43-462b-b976-36285459b58e)
![Selection_015](https://github.com/matrixorigin/matrixone/assets/60595215/e3b40d0f-900a-4dde-87e7-69435e58f30e)

**Comment by daviszhen** [comment]
leak 今天会把FOOTPRINT加上。

**Comment by zhangxu19830126** [comment]
https://grafana.ci.matrixorigin.cn/goto/z4ewk7PIR?orgId=1

**Comment by zhangxu19830126** [comment]
@daviszhen 上面这个是卡住在等锁的线程，在等待的事务，所有等待的事务都是leak的那个事务。是leak引起的

**Comment by sukki37** [comment]
txn leak：018f8309b98a701784181859b15fb371

20:13:27 sql failed, but txn is still active

@daviszhen please help to resolve this issue

<img width="1792" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/ed0b23bf-678b-4e5e-8329-f68fa6c9946b">


https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22C5l%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240516%5C%22%7D%20%7C%3D%20%60018f8309b98a701784181859b15fb371%60%20%21%3D%20%60wait%20too%20long%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715890350000%22,%22to%22:%221715893184000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ouyuanning** [comment]
duplicate的问题，可能跟 #15843 是一个事情

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入
