### ISSUE TITLE
[Bug]: return 'Database 'canal_manager_cache' does not exist' while query information_schema.TABLES  

### ISSUE THREAD

**Issue by EZ4BRUCE** [matrixorigin/matrixone#15189]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

8.0.30-MatrixOne-v1.1.2

### Commit ID

c66ab12ea

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

return error in select query:

<img width="959" alt="image" src="https://github.com/matrixorigin/matrixone/assets/69068661/ec79a501-f202-4b14-8206-dbeeb9f325fb">

<img width="878" alt="image" src="https://github.com/matrixorigin/matrixone/assets/69068661/6405d1de-4177-4f55-aa85-d1e8b6ccd43f">

### Steps to Reproduce

```Markdown
select * from information_schema.tables limit 1;
```
```


### Additional information

_No response_

**Comment by YANGGMM** [comment]
It seems to be an upgrade issue, after removing mo-data and rebooting it worked fine! @qingxinhome

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/d3bb65fe-a58f-4606-8e78-18e15455c61e)

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @EZ4BRUCE @sukki37 @aressu1985 @daviszhen

**Comment by EZ4BRUCE** [comment]
close as fixed
