### ISSUE TITLE
[Bug]: [date 3.26]standalone regression: tpch 100g test mo reported fatal error: out of memory

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15180]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6e2ff3c8c4e142151f089e37167a4e79d115638a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8437645403/job/23108095462
mo log：
{"level":"INFO","time":"2024/03/27 08:01:01.541458 +0800","name":"log-service","caller":"task/task_scheduler.go:72","msg":"task schedule query tasks","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","created":0,"expired":0}
fatal error: out of memory
fatal error: out of memory
fatal error: out of memory
fatal error: out of memory
fatal error: out of memory
fatal error: out of memory

goroutine 46702 [running]:
runtime.throw({0x3f18ed8?, 0x535b?})
        /usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc0624ad390 sp=0xc0624ad360 pc=0x4cfa5c
github.com/nnsgmsone/mmap.Alloc(0x8046)
        /home/github/go/pkg/mod/github.com/nnsgmsone/mmap@v0.0.0-20240320065159-dbdd196c4459/mmap.go:24 +0x70 fp=0xc0624ad3e0 sp=0xc0624ad390 pc=0x11988d0
github.com/matrixorigin/matrixone/pkg/common/malloc.Alloc(...)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/malloc/malloc.go:25
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.newData(0x0?, 0x12ec420?)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/memorycache/data_alloc_free.go:34 +0x29 fp=0xc0624ad400 sp=0xc0624ad3e0 pc=0x1199349
github.com/matrixorigin/matrixone/pkg/fileservice/memorycache.(*Cache).Alloc(...)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/memorycache/cache.go:67
github.com/matrixorigin/matrixone/pkg/fileservice.(*MemCache).Alloc(0xc05ce90990?, 0x30?)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/mem_cache.go:95 +0x25 fp=0xc0624ad438 sp=0xc0624ad400 pc=0x12d68a5
github.com/matrixorigin/matrixone/pkg/objectio.constructorFactory.func1({0x47b5f60?, 0xc05ce90990?}, {0xc07e358a00?, 0xc01dc80498?, 0xc07e358a00?}, {0x47b6000?, 0xc007692460?})
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/objectio/constructors.go:46 +0x112 fp=0xc0624ad4c8 sp=0xc0624ad438 pc=0x1befeb2
github.com/matrixorigin/matrixone/pkg/fileservice.(*IOEntry).setCachedData(0xc01efefdd0)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/io_entry.go:35 +0x10b fp=0xc0624ad528 sp=0xc0624ad4c8 pc=0x12c84cb
github.com/matrixorigin/matrixone/pkg/fileservice.(*LocalFS).read(0xc0028dc9a0, {0x47f4f20?, 0x6cc9dc0}, 0xc0254dca80, 0xc26badd178)

[mo-tpch.log](https://github.com/matrixorigin/matrixone/files/14767038/mo-tpch.log)

profile：
[profile0327.tar.gz](https://github.com/matrixorigin/matrixone/files/14767063/profile0327.tar.gz)

### Steps to Reproduce

```Markdown
tpch 100g test
```

**Comment by nnsgmsone** [comment]
sysctl -w vm.max_map_count = 262144即可

**Comment by heni02** [comment]
confirm，closed
之前配置参数值为65530
<img width="713" alt="企业微信截图_bf3144ff-9649-4b22-980d-872572ae7d51" src="https://github.com/matrixorigin/matrixone/assets/113406637/92cb9ae8-32f6-4361-8f69-ffb524e23a04">
系统配置该参数后，tpch100g测试没有这个问题了
<img width="713" alt="企业微信截图_bf3144ff-9649-4b22-980d-872572ae7d51" src="https://github.com/matrixorigin/matrixone/assets/113406637/3f7ce590-dfa8-4099-9d9b-b296f2b19d11">
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8491390465
<img width="1406" alt="企业微信截图_9b2ca203-8d86-4037-b7ec-2eba8bee06fa" src="https://github.com/matrixorigin/matrixone/assets/113406637/ab092deb-8d68-403d-8d3c-c1df8483e29c">
