### ISSUE TITLE
[Bug]: [date 3.26]standalone test: mo  panic runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15182]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6e2ff3c8c4e142151f089e37167a4e79d115638a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8437645403/job/23108093248
<img width="1364" alt="企业微信截图_9a74e7ad-2510-412c-a45a-f9b68c9bae3c" src="https://github.com/matrixorigin/matrixone/assets/113406637/168e4e11-6498-4639-8d98-e14612799d83">
FATAL: error 20101: internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:861
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges.func1
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:570
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Ranges
	/data1/runners/action

### Steps to Reproduce

```Markdown
sysbench read_write test
```

**Comment by gouhongshen** [comment]
@heni02 fixed, plz confirm that

**Comment by heni02** [comment]
confirm,closed
commit:47b7ee82f41fa63573e8025bc947e9d7c479129b
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8524292804
