### ISSUE TITLE
[Bug]: cn crash by panic: runtime error: invalid memory address or nil pointer dereference during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15206]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

eae974aade21e4bba6e3afba2ac74668c814a2bc

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
1*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, cns was crashed by panic:

{"level":"INFO","time":"2024/03/27 20:02:44.970093 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:3922","msg":"time of Exec.Run : 10.098766174s","uuid":"30393765-6464-3130-3235-623232303363","session_info":"connectionId 934|10.10.3.0:48987|{account sysbench_test1:admin:accountadmin -- 2:2:2}|goRoutineId 83915|018e80b8-795b-765d-9f28-7de47dca3ac4","session_id":"018e80b8-795b-765d-9f28-7de47dca3ac4","statement_id":"018e8181-daf5-733e-9315-d1ba23bafcaf","txn_id":"018e8181daf57a69b3bbc95a86b80281/Active/S:1711569754806564251-1"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x446b88b]

goroutine 2857415 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).StatusSession(0xc29a886c00)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2357 +0x1eb
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).processList(0xc0016d8240, {0x0, 0x0}, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:234 +0x1c7
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleShowProcessList(0xc0016d8240, {0x5bcbbd0, 0xc227c29dd0}, 0xc5bd8805b0, 0xc5b9f047e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:177 +0xe5
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x5ba4ca0, {0x5bcbbd0, 0xc227c29dd0}, 0xc5bd8805b0, 0xc5b9f047e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:65 +0x83
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:180 +0x3c5
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage(0x5c196a0, {0x5bcbbd0, 0xc227c29dd0}, {{0x5bcbbd0, 0xc227c29dd0}, 0xc35fbed7b0, {0x5be55a8, 0xc5bd8805b0}, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:189 +0x7fb
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc000676370, {0x5bfd840, 0xc0e8184200}, {0x52e4700, 0xc5bd8a7270}, 0x112)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:259 +0x13d8
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc000676420, {0x5bfd840, 0xc0e8184200})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:393 +0x748
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0xf8
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x705

mo-log:
https://shanghai-idc.1matrix.org:30088/explore?panes=%7B%228ot%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-eae974a-20240327%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711554018705%22,%22to%22:%221711573862746%22%7D%7D%7D&schemaVersion=1&orgId=1

the last valid commit:
0a1b2fccfd74e7409ea7e82c0371cabe01c0b8f6

### Steps to Reproduce

```Markdown
1. run a cluster mo
2. run tpch 10G loop test
3. run tpcc 10-10 longrunning test
4. run sysbench mixed case longrunning test
```

**Comment by ck89119** [comment]
并发问题，如果操作顺序如下图，获取所有session之后removeSession，然后对removedSession进行StatusSession方法调用，就会出现空指针问题。
<img width="1528" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/c0ea249c-e726-441b-9c36-71382f494458">

之前为什么没问题？因为昨天修复session泄露的时候，在session的close方法中，把rm置为nil了，就是说之前即使session已经close，还是能访问它的rm。
<img width="480" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/78ffc202-f7ec-404e-a930-5f28924367de">

解决办法：对processList整个方法加锁

**Comment by ck89119** [comment]
补充一下，报错行数
<img width="955" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/07ac8bcd-d415-4da3-ac30-17c66209a384">

**Comment by aressu1985** [comment]
fixed
