### ISSUE TITLE
[Bug]: [date 3.27]tke regerssion: cn restart reported  empty range of file and panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15208]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

469a78136

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://grafana.ci.matrixorigin.cn/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-nightly-regression-20240327&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki
<img width="1378" alt="企业微信截图_48e718d3-d901-4191-81cb-35cfdb088399" src="https://github.com/matrixorigin/matrixone/assets/113406637/fa7ea128-c483-45fd-965f-d3d08125d870">

mo log:
<img width="1299" alt="企业微信截图_87916c87-933e-4fb4-bac7-92c61a180337" src="https://github.com/matrixorigin/matrixone/assets/113406637/d5551097-4970-471d-b760-e3112dd8cd27">
{"level":"INFO","time":"2024/03/27 23:05:21.777921 +0000","name":"cn-service.lockservice","caller":"lockservice/service.go:548","msg":"bind created","uuid":"36393263-3230-3062-3236-663031326635","service":"171158070673904566836393263-3230-3062-3236-663031326635","remote":true,"bind":"4557455885355732384-171155079480247716361616363-6135-6564-3765-366665353731-1"} |  

/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c |  
 created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 409 |  
 /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8d |  
 github.com/panjf2000/ants/v2.(*goWorker).run.func1() |  
 /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/job.go:122 +0xb7 |  
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc013d31b00) |  
 /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio/pipeline.go:209 +0x77 |  
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchMetaJob.func1({0x27afff01f312f0?, 0x481bb3?}) 
/go/src/github.com/matrixorigin/matrixone/pkg/objectio/cache.go:223 +0x99 |  
github.com/matrixorigin/matrixone/pkg/objectio.FastLoadObjectMeta({0x47634e0?, 0x6a1fd20?}, 0x10444a7b8?, 0x0?, {0x47ac300?, 0xc0005d0be0?}) |  
 /go/src/github.com/matrixorigin/matrixone/pkg/objectio/cache.go:154 +0x19e |  
github.com/matrixorigin/matrixone/pkg/objectio.LoadObjectMetaByExtent({0x47634e0, 0x6a1fd20}, 0xc01454be78, 0x7fb684901698?, 0x98?, 0x20?, {0x47ac300, 0xc0005d0be0}) |  
/go/src/github.com/matrixorigin/matrixone/pkg/objectio/funcs.go:62 +0x23e |  
github.com/matrixorigin/matrixone/pkg/objectio.ReadExtent({0x47634e0, 0x6a1fd20}, {0xc0141c70e0, 0x2a}, 0xc01454be90, 0x13, {0x47ac300, 0xc0005d0be0}, 0x4053d88) |  
/usr/local/go/src/runtime/panic.go:914 +0x21f |  
panic({0x381bfc0?, 0x68a8310?}) |  
 /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85 |  
 github.com/panjf2000/ants/v2.(*goWorker).run.func1.1() |  
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e |  
runtime/debug.Stack() |  
goroutine 1146 [running]: |  
2024/03/27 23:05:21.758656 [ants]: worker exits from panic: runtime error: invalid memory address or nil pointer dereference |  
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c |  
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 409 |  
 {"level":"INFO","time":"2024/03/27 23:05:21.758754 +0000","caller":"blockio/pipeline.go:482","msg":"job is Job[LoadJob]-[018e8200-84e3-70fc-8942-31edff9376f1_00000-758006764]"} |  
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8d |  
 github.com/panjf2000/ants/v2.(*goWorker).run.func1() |  
 /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/job.go:122 +0xb7 |  
 github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc00257ba00) |  
 /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio/pipeline.go:209 +0x77 |  github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchMetaJob.func1({0x27afff020e0d7a?, 0x481bb3?}) |  
 {"level":"WARN","time":"2024/03/27 23:05:21.758711 +0000","caller":"blockio/pipeline.go:487","msg":"Prefetch 018e81dd-976d-78cd-8aa5-3a4139511cdb_00000-757934155 err: empty range of file 018e81dd-976d-78cd-8aa5-3a4139511cdb_00000"} |  
 /go/src/github.com/matrixorigin/matrixone/pkg/objectio/cache.go:223 +0x99 |  
github.com/matrixorigin/matrixone/pkg/objectio.FastLoadObjectMeta({0x47634e0?, 0x6a1fd20?}, 0x0?, 0x0?, {0x47ac300?, 0xc0005d0be0?}) |  
/go/src/github.com/matrixorigin/matrixone/pkg/objectio/cache.go:154 +0x19e |  
github.com/matrixorigin/matrixone/pkg/objectio.LoadObjectMetaByExtent({0x47634e0, 0x6a1fd20}, 0xc01504de78, 0x7fb6d8607cb0?, 0x48?, 0x20?, {0x47ac300, 0xc0005d0be0}) |  
{"level":"WARN","time":"2024/03/27 23:05:21.758624 +0000","caller":"blockio/pipeline.go:487","msg":"Prefetch 018e81d9-d7f3-76e4-bcd3-851b317b714a_00000-757919184 err: empty range of file 018e81d9-d7f3-76e4-bcd3-851b317b714a_00000"} |  
/go/src/github.com/matrixorigin/matrixone/pkg/objectio/funcs.go:62 +0x23e |  
ithub.com/matrixorigin/matrixone/pkg/objectio.ReadExtent({0x47634e0, 0x6a1fd20}, {0xc002857c20, 0x2a}, 0xc01504de90, 0x13, {0x47ac300, 0xc0005d0be0}, 0x4053d88) |  
 /usr/local/go/src/runtime/panic.go:914 +0x21f |  
panic({0x381bfc0?, 0x68a8310?}) |  
/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85 |  
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1() |  
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e |  
runtime/debug.Stack()

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Jgu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240327%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711580720000%22,%22to%22:%221711580722000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench 1000w read_only 1000threads
```

**Comment by LeftHandCold** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Jgu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240327%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-l76sq%5C%22%7D%20%7C%3D%20%60SIGSEGV%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711580390000%22,%22to%22:%221711580398000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by LeftHandCold** [comment]
重启是因为 段错误

**Comment by LeftHandCold** [comment]
prefetch error和empty range是remove block的pr带来的bug，但是不会引起节点重启。

**Comment by jiangxinmeng1** [comment]
prefetch error和empty range #15235 里修掉了

**Comment by heni02** [comment]
confirm,closed
