### ISSUE TITLE
[Bug]: big data test report panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15207]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f87ec703eddbef6e7098576195558799a36187c4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8448975968/job/23168223658
(Quries 1Y-Write 1Y test)

<img width="977" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f8cf3406-c2e6-4954-ac2c-be2a837fab83">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%228tM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-big-data-nightly-f87ec70%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711566910000%22,%22to%22:%221711566970000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big data test on tke.
```

**Comment by zhangxu19830126** [comment]
By default we can only add up to 1M locks to a transaction, and this case exceeds that limit. We need to modify the configuration.

**Comment by zhangxu19830126** [comment]
[cn.lockservice]
max-fixed-slice-size = "100m"

**Comment by Ariznawlll** [comment]
我今天先根据旭哥的comment验证一下

**Comment by Ariznawlll** [comment]
改了配置之后今天没出现这个问题，还要再观察几天

**Comment by Ariznawlll** [comment]
没出现，先关掉
