### ISSUE TITLE
[Bug]: tpch q10 runs too long

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#15226]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

c66ab12ea

### Other Environment Information

```Markdown
- Hardware parameters:MO Cloud QA Env
- OS type:
- Others:
```

### Actual Behavior

详细可查看：https://github.com/matrixorigin/MO-Cloud/issues/2777
TPCH 100GB 数据量，跑了几遍 22 条查询，发现只有 q10 会有性能波动，还很大。初步定位是 Page Cache 在读数据消费时间，但这合理吗？为什么只有q10 存在这个问题

### Expected Behavior

q10 可以稳定在一个性能

### Steps to Reproduce

```Markdown
run tpch-sf100 query 10 多次
```

**Comment by badboynt1** [comment]
当时由于这个现象不稳定复现，所以准备留待观察。
这几天李松请假了，等他回来后看看这个现象现在是否还有

**Comment by sukki37** [comment]
We requested more information about this issue but haven't received a response. Therefore, we are closing this issue. If you have more information or need help, please reopen this issue or create a new one with the requested details.

Thank you for your cooperation!
