### ISSUE TITLE
[Bug]:  `lock table bind changed` occurred during bvt test without nodes failure

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15236]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

910deae

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8476879162/job/23227269394

<img width="1127" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/43169a8d-265d-4b03-8533-ccc997dbd91b">

log link: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22F7x%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-15204%5C%22%7D%20%7C%3D%20%60lock%20table%20bind%20changed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711685088174%22,%22to%22:%221711686712055%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
run bvt
```

### Additional information

https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-checkin-regression-15204&from=1711684547055&to=1711688784255

The period during which the error occurred was characterized by a very low CPU usage rate.

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/15311

**Comment by Ariznawlll** [comment]
先观察几天回归里的bvt测试.

**Comment by Ariznawlll** [comment]
观察了几天，ci没出现这个问题
