### ISSUE TITLE
[Bug]: [date 3.28]tke regression: sysbench 1000w delete test mo hung 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1da858a6f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8468904490/job/23229856487
sysbench 1000w delete test 预期执行时间是300s，但一直没有结束测试，跑了5h+
<img width="1053" alt="企业微信截图_0faf116b-41e7-4f75-b37c-686aee346f0d" src="https://github.com/matrixorigin/matrixone/assets/113406637/70800da2-0ce6-4a82-8012-a1c5fcedafbb">
<img width="1033" alt="企业微信截图_e226adf5-3a01-4cfc-93ea-4b33a0e55dca" src="https://github.com/matrixorigin/matrixone/assets/113406637/f00a9d93-8ce5-4882-8bc4-c9727e536a11">

怀疑mo hung或者和这个issue：https://github.com/matrixorigin/matrixone/issues/15140连接没有断开有关？麻烦定位
mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gHU%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240328%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711672097000%22,%22to%22:%221711672130000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench 1000w delete 100threads test
```

**Comment by heni02** [comment]
配置enable-leak-check = 1，再次测试复现
job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8534777344/job/23389601343
<img width="1168" alt="企业微信截图_2db4246b-5aa5-4575-bc19-1efbbbedd9ef" src="https://github.com/matrixorigin/matrixone/assets/113406637/961c6039-0562-4efb-9b26-352efef03567">

日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Wxz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240403%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221712131374620%22,%22to%22:%221712152974620%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ck89119** [comment]
logs上看到有卡住的txn
<img width="1834" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/14d493c2-679d-48ed-8262-51bb02f8c6ef">

active txn数量是100
<img width="520" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/ae537a54-8199-45b3-947b-7e1023db55be">

初步判断是mo侧txn执行卡住了，但是自检打log的txn只有3个，另外97个在做什么操作还不知道，需要进一步抓profile确定。

**Comment by ck89119** [comment]
join执行算子handleRuntimeFilter方法获取receiver时，走到了非预期的分支中。

<img width="1015" alt="企业微信截图_4c05a9b2-d90b-4372-b4fd-2aeeaa03625e" src="https://github.com/matrixorigin/matrixone/assets/4971300/2218cb8b-ac83-47ad-a6e0-2e35a5101d65">

<img width="1600" alt="企业微信截图_9847d460-eef6-416a-9762-1a1c6994646e" src="https://github.com/matrixorigin/matrixone/assets/4971300/fa44d2c3-1706-4d89-af53-d85b2f1a520a">

**Comment by ck89119** [comment]
> join执行算子handleRuntimeFilter方法获取receiver时，走到了非预期的分支中。
> 
> <img alt="企业微信截图_4c05a9b2-d90b-4372-b4fd-2aeeaa03625e" width="1015" src="https://private-user-images.githubusercontent.com/4971300/321490516-2218cb8b-ac83-47ad-a6e0-2e35a5101d65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjEzODcsIm5iZiI6MTcxNTE2MTA4NywicGF0aCI6Ii80OTcxMzAwLzMyMTQ5MDUxNi0yMjE4Y2I4Yi1hYzgzLTQ3YWQtYTZlMC0yZTM1YTUxMDFkNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDkzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUwNDIxZTdiMjhmZmZiNjZiNjQ0NTgwZTQzMjQ4ZDM2NTEzYzc4M2EwNjZlNzIwMTEzM2I3MjBkYWZkZTBkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Yg10m55xXaukvd_FaiJWjWWKydBa66s0xWPCuIdvcxE"> <img alt="企业微信截图_9847d460-eef6-416a-9762-1a1c6994646e" width="1600" src="https://private-user-images.githubusercontent.com/4971300/321490557-fa44d2c3-1706-4d89-af53-d85b2f1a520a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjEzODcsIm5iZiI6MTcxNTE2MTA4NywicGF0aCI6Ii80OTcxMzAwLzMyMTQ5MDU1Ny1mYTQ0ZDJjMy0xNzA2LTRkODktYWY1My1kODViMmYxYTUyMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDkzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk3NmVhNmNmOTYxY2Y0MTUwNDZhMWI2YzIzYTgyMDA5OTFkNDRiMTNhYmY2NzNkNTNhNmE4YTZkMjU3Y2ZlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OtwnlT1ot13k35SRgafiY3_VKqnSwppfMtaPwmIm_b4">

这个问题已经解决 https://github.com/matrixorigin/matrixone/pull/15106

但是暴露出来了新的问题，目前还没时间去看
![企业微信截图_17129055207848](https://github.com/matrixorigin/matrixone/assets/4971300/148a3de5-367e-4a39-8d60-f99f8bab73f3)

**Comment by ouyuanning** [comment]
明松有空的时候帮忙看看吧

**Comment by m-schen** [comment]
> > join执行算子handleRuntimeFilter方法获取receiver时，走到了非预期的分支中。
> > <img alt="企业微信截图_4c05a9b2-d90b-4372-b4fd-2aeeaa03625e" width="1015" src="https://private-user-images.githubusercontent.com/4971300/321490516-2218cb8b-ac83-47ad-a6e0-2e35a5101d65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjEzODcsIm5iZiI6MTcxNTE2MTA4NywicGF0aCI6Ii80OTcxMzAwLzMyMTQ5MDUxNi0yMjE4Y2I4Yi1hYzgzLTQ3YWQtYTZlMC0yZTM1YTUxMDFkNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDkzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUwNDIxZTdiMjhmZmZiNjZiNjQ0NTgwZTQzMjQ4ZDM2NTEzYzc4M2EwNjZlNzIwMTEzM2I3MjBkYWZkZTBkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Yg10m55xXaukvd_FaiJWjWWKydBa66s0xWPCuIdvcxE"> <img alt="企业微信截图_9847d460-eef6-416a-9762-1a1c6994646e" width="1600" src="https://private-user-images.githubusercontent.com/4971300/321490557-fa44d2c3-1706-4d89-af53-d85b2f1a520a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjEzODcsIm5iZiI6MTcxNTE2MTA4NywicGF0aCI6Ii80OTcxMzAwLzMyMTQ5MDU1Ny1mYTQ0ZDJjMy0xNzA2LTRkODktYWY1My1kODViMmYxYTUyMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDkzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk3NmVhNmNmOTYxY2Y0MTUwNDZhMWI2YzIzYTgyMDA5OTFkNDRiMTNhYmY2NzNkNTNhNmE4YTZkMjU3Y2ZlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OtwnlT1ot13k35SRgafiY3_VKqnSwppfMtaPwmIm_b4">
> 
> 这个问题已经解决 #15106
> 
> 但是暴露出来了新的问题，目前还没时间去看 ![企业微信截图_17129055207848](https://private-user-images.githubusercontent.com/4971300/328839258-148a3de5-367e-4a39-8d60-f99f8bab73f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDUyMTksIm5iZiI6MTcxNjIwNDkxOSwicGF0aCI6Ii80OTcxMzAwLzMyODgzOTI1OC0xNDhhM2RlNS0zNjdlLTRhMzktOGQ2MC1mOTlmOGJhYjczZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTEzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Y5ZDkyY2M2MTYzYzI3NWJhODhiN2YzZmY1Y2ZlMTk5MTkzZjhjMjkxM2Q3NTk0YWZiOTkwYjU3ZTE4NTNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NjDCE_SO1RckePZnrAEIbVweW0LSS3cA4bNW0-RE9AY)

图片挂了好像

**Comment by m-schen** [comment]
同上，且今天在处理hung住的s-1的问题。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/pull/16452

这个pr提交后应该由原来的hung住变成了可以抛出真正的错误。
转成下面这个issue。
https://github.com/matrixorigin/matrixone/issues/16502

**Comment by heni02** [comment]
delete测试没有再hung的现象
confirm，closed
commit：0081545b5
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9304399145/job/25629611843
<img width="1119" alt="企业微信截图_d7f68a9f-230a-41b6-ad33-618edf23c841" src="https://github.com/matrixorigin/matrixone/assets/113406637/73a9c106-3f42-4b74-9ac6-14c33d670198">
