### ISSUE TITLE
[Bug]: [date 3.31]tke regression: tpcc 100 warehouse 1000threads reported losts of connection communications link failure

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15249]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b9157621b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8498892181/job/23279226970
<img width="1051" alt="企业微信截图_e8b6598e-766b-4a9e-aa7e-cd03b0bacbac" src="https://github.com/matrixorigin/matrixone/assets/113406637/5bed6b81-5710-4c28-9419-b800e7a988aa">
<img width="1016" alt="企业微信截图_19d5d012-9469-4094-9aa1-7fac4a118d9f" src="https://github.com/matrixorigin/matrixone/assets/113406637/732f0fad-3258-46e1-8ec4-c495e8896c0e">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22a2J%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240331%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221711905386038%22,%22to%22:%221711905398038%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc 100 warehouse 1000threads test
```

**Comment by nnsgmsone** [comment]
通过日志分析是超时了:
```
2024-03-31 17:15:34.130	
{"level":"INFO","time":"2024/03/31 17:15:34.130842 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:3796","msg":"time of Exec.Build : 1.777334594s","uuid":"37646166-3932-6466-3833-383037623530","session_info":"connectionId 4291|10.143.102.163:36314|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 412407|018e956e-a6a1-77d5-af0a-56e3db444e45","session_id":"018e956e-a6a1-77d5-af0a-56e3db444e45","statement_id":"018e9582-5c81-7714-bdc1-d6e836dce3a1","txn_id":"018e95825c8176e8907515e26ea327c6/Active/S:1711905332329357905-1"}
2024-03-31 17:16:46.473	
{"level":"INFO","time":"2024/03/31 17:16:46.473861 +0000","name":"cn-service.frontend","caller":"frontend/mysql_cmd_executor.go:4087","msg":"time of Exec.Run : 1m12.337438289s","uuid":"37646166-3932-6466-3833-383037623530","session_info":"connectionId 4291|10.143.102.163:36314|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 412407|018e956e-a6a1-77d5-af0a-56e3db444e45","session_id":"018e956e-a6a1-77d5-af0a-56e3db444e45","statement_id":"018e9582-6378-751d-81be-e5ccbd42e17a","txn_id":"018e95825c8176e8907515e26ea327c6/Active/S:1711905406460972330-1"}
```
至于为什么超时，原因还不明

**Comment by nnsgmsone** [comment]
![截图 2024-04-02 10-57-22](https://github.com/matrixorigin/matrixone/assets/31609524/f3951804-ca49-47fb-9546-1d1605c5eea1)
看着存在build耗时很久的情况，不过这个本质可能是因为tn commit耗时过久导致的:
![截图 2024-04-02 11-00-47](https://github.com/matrixorigin/matrixone/assets/31609524/2ca701e1-5287-434d-bde9-bc3fb0980fc5)

**Comment by nnsgmsone** [comment]
麻烦看一下这个commit为啥这么久 @XuPeng-SH

**Comment by aptend** [comment]
正在修复 merge two-phase transfer

**Comment by aptend** [comment]
近期若干修复后未见

**Comment by nnsgmsone** [comment]
no process
