### ISSUE TITLE
[Bug]: 偶现，查询result_scan为空

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#15267]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

8.0.30-MatrixOne-v1.1.2

### Commit ID

bf48c0d02

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

订阅Sample数据，q1查询sf1结果为空，查询sf10正常有结果。save_query_result为on。只有第一次有问题，后续正常。偶现
SQL：
```
select
  l_returnflag,
  l_linestatus,
  sum(l_quantity) as sum_qty,
  sum(l_extendedprice) as sum_base_price,
  sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
  sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
  avg(l_quantity) as avg_qty,
  avg(l_extendedprice) as avg_price,
  avg(l_discount) as avg_disc,
  count(*) as count_order
from
  lineitem
where
  l_shipdate <= date '1998-12-01' - interval '112' day
group by
  l_returnflag,
  l_linestatus
order by
  l_returnflag,
  l_linestatus;
```

目前保留了Dev环境的一条无结果查询的statement_id
018e9931-6966-7f7f-96c9-9809ec23bf6d
用户为：
018e98b8_5c83_7b7b_a89e_f0c97edd0dd4

### Expected Behavior

正常查询有结果

### Steps to Reproduce

```Markdown
如上
```

**Comment by xiaoshuwei** [comment]
连接串：
https://github.com/matrixorigin/MO-Cloud/issues/2687#issuecomment-2029602099

**Comment by daviszhen** [comment]
pr https://github.com/matrixorigin/matrixone/pull/15270 已经进了1.1.2

**Comment by aressu1985** [comment]
done
