### ISSUE TITLE
[Feature Request]: Implement UNHEX() to replace DECODE("xxx", "hex")

### ISSUE THREAD

**Issue by arjunsk** [matrixorigin/matrixone#15261]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

We had previously implemented the HEX() function https://github.com/matrixorigin/matrixone/issues/4773. However, we did not implement the UNHEX() function. When we are refactoring https://github.com/matrixorigin/matrixone/issues/15027 to its MYSQL API, we need to replace the existing decode("xx", "hex") with UNHEX("xx") for Vector Binary Insert.

### Describe the feature you'd like

Implement UNHEX function from this spec: https://www.w3resource.com/mysql/string-functions/mysql-unhex-function.php

**Comment by xxxuuu** [comment]
Hi @arjunsk, have you already been working on this issue? I'd like to give it a try.

**Comment by arjunsk** [comment]
Thank you @xxxuuu .

The logic is mostly implemented here

https://github.com/matrixorigin/matrixone/blob/0960f0fb59acb0392603ca7add19332d04250593/pkg/sql/plan/function/func_binary.go#L2246-L2251

You just need to define a new `function_id` for the `UNHEX` and port this logic there.

The return type is BLOB (because this function will be used for inserting VECTOR values as BLOB)

```go
	// function `decode`
	{
		functionId: DECODE,
		class:      plan.Function_STRICT,
		layout:     STANDARD_FUNCTION,
		checkFn:    fixedTypeMatch,

		Overloads: []overload{
			{
				overloadId: 0,
				args:       []types.T{types.T_varchar, types.T_varchar},
				retType: func(parameters []types.Type) types.Type {
					return types.T_blob.ToType()
				},
				newOp: func() executeLogicOfOverload {
					return Decode
				},
			},
		},
	},

```

**Comment by arjunsk** [comment]
Hi @xxxuuu , this is a quick example of how NULL is returned (without  using opUnaryBytesToBytes)

![image](https://github.com/matrixorigin/matrixone/assets/9638314/13720412-4bfe-4107-b3a1-5bf5fb53af6a)

**Comment by arjunsk** [comment]
Thank you for your contribution @xxxuuu

**Comment by arjunsk** [comment]
Pending changes

1. Update BVT to use UNHEX instead of DECODE("...", "HEX") -- done
2. Update Decode("...", "hex") to use UNHEX in the documentation -- pending
3. Run benchmark using UNHEX (330 seconds to insert SIFT128) -- done

**Comment by arjunsk** [comment]
Document for UNHEX

https://doc.weixin.qq.com/doc/w3_AawAhAZmAIku2NYoOi3S802xrQKST?scode=AJsA6gc3AA8eG0NzsiAawAhAZmAIk&is_external=0&commentVersion=1712873541000&doc_title=Untitled%20Doc&wxworkQt=1&qt_source=Conv&qt_report_identifier=1712873544158

CC: @yangj1211

**Comment by arjunsk** [comment]
This issue is ready for testing.

**Comment by Ariznawlll** [comment]
hex() and unhex() test done
