### ISSUE TITLE
[Bug]: CI failed frequently

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15272]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f0a0ba5a77531397b7f13577e7ea1e75ed8d6409

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8505722939/job/23295948234?pr=15262

### Steps to Reproduce

```Markdown
run bvt
```

### Additional information

It is highly likely caused by this #15102.

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/8508414154/job/23303116589

<img width="1370" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/2d22a6e0-1f3d-4737-85a9-f60d63d87a89">

revert 这个pr之后`grant`相关的SQL依然失败,
