### ISSUE TITLE
[Bug]: TPCH Q1同实例第三次结果耗时陡增，其他次结果耗时正常

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#15291]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.2

### Commit ID

bf48c0d02

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
QA环境
```

### Actual Behavior

导入sf1和sf10，执行Q1 SQL，偶现第三次SQL的耗时大于第二次。

### Expected Behavior

出现Q1SQL 耗时逐次下降或稳定

### Steps to Reproduce

```Markdown
创建MO实例，导入Sample数据后多次执行，偶现。
```

### Additional information

<img width="986" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/b1c57df1-f872-42f3-aaa9-5029acb724db">

**Comment by nnsgmsone** [comment]
可能是cache被置换出去导致的。。。可以看看是不是这样，或者其他情况 @badboynt1

**Comment by xiaoshuwei** [comment]
复现失败，先关掉，等复现再开。
