### ISSUE TITLE
[Bug]: Load data failed with `i/o timeout`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#15307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1.2

### Commit ID

v1.1.2-1519f8e5c-2024-04-02

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2024/04/02 13:35:41.239819 +0000 ERROR gorm@v1.25.5/finisher_api.go:610 trace {"error": "Error 1105 (HY000): read tcp 172.20.117.4:36998->47.110.178.61:443: i/o timeout", "elapsed": "13m5.771911567s", "rows": 0, "sql": "/* cloud_user */\nLOAD DATA URL s3option{\"endpoint\"='oss-cn-hangzhou.aliyuncs.com', \"access_key_id\"='x', \"secret_access_key\"='y', \"bucket\"='z', \"filepath\"='tpch-sf100/lineitem.tbl', \"compression\"='none'} into table lineitem FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\\n' PARALLEL 'TRUE';"}
```

### Expected Behavior

Load data successfully

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Log: https://grafana.matrixonecloud.cn/goto/jU-lY-xIg?orgId=1

**Comment by sukki37** [comment]
s3 read timeout

https://grafana.matrixonecloud.cn/explore?panes=%7B%226Zk%22:%7B%22datasource%22:%22fe9f0f46-57bd-4343-8755-8d67d0429b65%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22normal-cn-54szd%5C%22%7D%20%7C%3D%20%6047.110.178.61%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22fe9f0f46-57bd-4343-8755-8d67d0429b65%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221712064897394%22,%22to%22:%221712065018884%22%7D%7D%7D&schemaVersion=1&orgId=1



![Image](https://github.com/matrixorigin/matrixone/assets/77312370/bc66d731-75a7-4244-bc08-f060fa09f039)

**Comment by reusee** [comment]
not working on this issue.

**Comment by reusee** [comment]
not working on this issue.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
现在的读重试，最多 128 次，所以是有可能出现超时的，不会一直重试

**Comment by reusee** [comment]
如上

**Comment by reusee** [comment]
如上

**Comment by reusee** [comment]
working on other issues

**Comment by reusee** [comment]
working as expected, re-assigning.

**Comment by DanielZhangQD** [comment]
> 现在的读重试，最多 128 次，所以是有可能出现超时的，不会一直重试

@aressu1985 帮忙确认下，这个行为是否可以接受

**Comment by reusee** [comment]
pr sent

**Comment by reusee** [comment]
已加入重试

**Comment by aressu1985** [comment]
fixed
