### ISSUE TITLE
Should support select data from an empty table.

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#1530]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> CREATE TABLE t2 (int_col INTEGER, string_col VARCHAR(255));
Query OK, 0 rows affected (0.51 sec)

mysql> select * from t2;
ERROR 1105 (HY000): unknown error:[0A000]not support select from empty table now
mysql>

**Comment by m-schen** [comment]
fixed.

**Comment by domingozhang** [comment]
fixed
