### ISSUE TITLE
[Bug]: ut failed in ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15324]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1e0305497236ff1dfb042d123aaadffe4c6fc816

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

url:https://github.com/matrixorigin/matrixone/actions/runs/8534554289/job/23379272441?pr=15318

<img width="1424" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/306dee27-33c0-40e4-8d2d-b495e6696972">

log:
[logs_22367705934.zip](https://github.com/matrixorigin/matrixone/files/14849379/logs_22367705934.zip)

### Steps to Reproduce

```Markdown
trigger ci test.
```

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
verified
