### ISSUE TITLE
[Bug]: insert ignore select from table which 100000 rows reported ExpectedEOB

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15349]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

85734e607d12a7a34ac31f8cdc91e72d9eaf98e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

env：mo standalone mode，default toml configuration
insert_ignore_06 is 100000rows，insert ignore insert_ignore_07 select from insert_ignore_06 reported ExpectedEOB
<img width="1015" alt="企业微信截图_14b4adfe-6b29-4611-8bde-371322c5ad45" src="https://github.com/matrixorigin/matrixone/assets/113406637/93dd5a1a-9d6f-4614-9665-8800dc6e0985">

### Steps to Reproduce

```Markdown
create table insert_ignore_06(c1 int primary key auto_increment, c2 int);
insert into insert_ignore_06(c2) select result from generate_series(1,100000) g;
create table insert_ignore_07(c1 int primary key, c2 int);
insert into insert_ignore_07 values(20,45),(21,55),(1,45),(6,22),(5,1),(1000,222),(99999,19);
insert ignore into insert_ignore_07 select * from insert_ignore_06;
```

**Comment by ouyuanning** [comment]
当前的insert ignore是改写成insert on duplicate key ignore，
目前的实现是阻塞型的，大数据量下应该会有比较多问题。行健先帮看看吧

**Comment by ouyuanning** [comment]
跟这个 https://github.com/matrixorigin/MO-Cloud/issues/2956  一起考虑如何处理吧

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理
- https://github.com/matrixorigin/matrixone/issues/15809

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
等on duplicate update的方案

**Comment by jensenojs** [comment]
等on dup的解决方案

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
#18406 上已解决

**Comment by heni02** [comment]
main commit:25327d49d67f562403b1faee37855a8a8f9b3ca1
mysql> create database test_db;
Query OK, 1 row affected (0.06 sec)

mysql> use test_db;
Database changed
mysql> create table insert_ignore_06(c1 int primary key auto_increment, c2 int);
Query OK, 0 rows affected (0.04 sec)

mysql> insert into insert_ignore_06(c2) select result from generate_series(1,100000) g;
Query OK, 100000 rows affected (0.55 sec)

mysql> create table insert_ignore_07(c1 int primary key, c2 int);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into insert_ignore_07 values(20,45),(21,55),(1,45),(6,22),(5,1),(1000,222),(99999,19);
Query OK, 7 rows affected (0.07 sec)

mysql> insert ignore into insert_ignore_07 select * from insert_ignore_06;
Query OK, 99993 rows affected (0.54 sec)
