### ISSUE TITLE
[Bug]: insert ignore into decimal type not null results error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15358]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

85734e607d12a7a34ac31f8cdc91e72d9eaf98e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert ignore into decimal type not null 按目前mo支持情况应该报null约束错误，但现在可以插入成功，且插入一行数据也是错误的
<img width="1773" alt="企业微信截图_bd59c997-3dc0-4fd6-ab36-89e0cdb30ee3" src="https://github.com/matrixorigin/matrixone/assets/113406637/4684e4e1-2ebc-427e-984c-39b00a135d33">
如果不能复现，drop表后再create表insert

### Steps to Reproduce

```Markdown
create table insert_ignore_04 (product_id INT NOT NULL AUTO_INCREMENT,product_name VARCHAR(255) NOT NULL,quantity_in_stock INT DEFAULT 0,price DECIMAL(10, 2) NOT NULL,PRIMARY KEY (product_id));
 insert ignore into insert_ignore_04(product_name, price) VALUES('Laptop', 1200.00),('Monitor', 150.00),('Keyboard', NULL),('Mouse', 15.00);
```

**Comment by ouyuanning** [comment]
需要多执行几次才比较容易复现。
行健帮看看吧

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理
- https://github.com/matrixorigin/matrixone/issues/15809

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
等重新设计方案

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
等on duplicate update的方案

**Comment by jensenojs** [comment]
等on dup的解决方案

**Comment by jensenojs** [comment]
not working on it

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by sukki37** [comment]
verified with https://github.com/matrixorigin/matrixone/commit/0a5786af3da2735110732c94427e15221d365fe6
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/e0577174-cae6-4ca0-8672-c143b5e14f6f">

@heni02 please double check and add bvt case, thank you

**Comment by heni02** [comment]
confirm，closed
commit:0a3d52f3f9b4c740744f8567e689fed784feffe5
mysql> create table insert_ignore_04 (product_id INT NOT NULL AUTO_INCREMENT,product_name VARCHAR(255) NOT NULL,quantity_in_stock INT DEFAULT 0,price DECIMAL(10, 2) NOT NULL,PRIMARY KEY (product_id));
Query OK, 0 rows affected (0.05 sec)

mysql>  insert ignore into insert_ignore_04(product_name, price) VALUES('Laptop', 1200.00),('Monitor', 150.00),('Keyboard', NULL),('Mouse', 15.00);
ERROR 3819 (HY000): constraint violation: Column 'price' cannot be null

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
