### ISSUE TITLE
[Bug]: insert ignore into range partition table reported panic error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15355]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

85734e607d12a7a34ac31f8cdc91e72d9eaf98e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert ignore panic error:
mysql> insert ignore into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [-1]:
runtime.goPanicIndex
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).AddLockTargetWithPartitionAndMode.getRowsFilter.func1
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/lock_op.go:835
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.fetchVarlenaRows
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/fetch.go:684
github.com/matrixorigin

去掉ignore也报panic：
mysql> insert into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [-1]:
runtime.goPanicIndex
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).AddLockTargetWithPartitionAndMode.getRowsFilter.func1
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/lock_op.go:835
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.fetchVarlenaRows
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/fetch.go:684
github.com/matrixorigin

去掉非partition key值'1995-06-01'，insert成功
mysql> insert into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(1, 2000.00, '1991-07-01');
Query OK, 3 rows affected (0.04 sec)

去掉非partition key值'1995-06-01'，insert ignore还是会panic报错
mysql> insert ignore into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(1, 2000.00, '1991-07-01');
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [-1]:
runtime.goPanicIndex
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).AddLockTargetWithPartitionAndMode.getRowsFilter.func1
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/lock_op.go:835
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.fetchVarlenaRows
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/lockop/fetch.go:684
github.com/matrixorigin

insert_ignore_06 ddl:
mysql> create table insert_ignore_06 (sale_id INT AUTO_INCREMENT,product_id INT,sale_amount DECIMAL(10, 2),sale_date DATE,PRIMARY KEY (sale_id, sale_date))PARTITION BY RANGE (year(sale_date)) (PARTITION p0 VALUES LESS THAN (1991),PARTITION p1 VALUES LESS THAN (1992),PARTITION p2 VALUES LESS THAN (1993),PARTITION p3 VALUES LESS THAN (1994));
Query OK, 0 rows affected (0.04 sec)

### Steps to Reproduce

```Markdown
create table insert_ignore_06 (sale_id INT AUTO_INCREMENT,product_id INT,sale_amount DECIMAL(10, 2),sale_date DATE,PRIMARY KEY (sale_id, sale_date))PARTITION BY RANGE (year(sale_date)) (PARTITION p0 VALUES LESS THAN (1991),PARTITION p1 VALUES LESS THAN (1992),PARTITION p2 VALUES LESS THAN (1993),PARTITION p3 VALUES LESS THAN (1994));
insert ignore into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
insert into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
```

**Comment by qingxinhome** [comment]
pr已提交

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been submitted. Please verify and test it。 @heni02 @sukki37 @daviszhen

**Comment by heni02** [comment]
confirm,closed
main commit:
mysql> create table insert_ignore_06 (sale_id INT AUTO_INCREMENT,product_id INT,sale_amount DECIMAL(10, 2),sale_date DATE,PRIMARY KEY (sale_id, sale_date))PARTITION BY RANGE (year(sale_date)) (PARTITION p0 VALUES LESS THAN (1991),PARTITION p1 VALUES LESS THAN (1992),PARTITION p2 VALUES LESS THAN (1993),PARTITION p3 VALUES LESS THAN (1994));
Query OK, 0 rows affected (0.02 sec)

mysql> insert ignore into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
ERROR 20301 (HY000): invalid input: Table has no partition for value from column_list
mysql> insert into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
ERROR 20301 (HY000): invalid input: Table has no partition for value from column_list

1.1-dev commit:8f340f7c94194033ba7362f584cdd7b1bb43e1c1
mysql> create table insert_ignore_06 (sale_id INT AUTO_INCREMENT,product_id INT,sale_amount DECIMAL(10, 2),sale_date DATE,PRIMARY KEY (sale_id, sale_date))PARTITION BY RANGE (year(sale_date)) (PARTITION p0 VALUES LESS THAN (1991),PARTITION p1 VALUES LESS THAN (1992),PARTITION p2 VALUES LESS THAN (1993),PARTITION p3 VALUES LESS THAN (1994));
Query OK, 0 rows affected (0.08 sec)

mysql> insert ignore into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
ERROR 20301 (HY000): invalid input: Table has no partition for value from column_list
mysql> insert into insert_ignore_06 (product_id, sale_amount, sale_date) VALUES(1, 1000.00, '1990-04-01'),(2, 1500.00, '1992-05-01'),(3, 500.00, '1995-06-01'),(1, 2000.00, '1991-07-01');
ERROR 20301 (HY000): invalid input: Table has no partition for value from column_list
