### ISSUE TITLE
[Bug]: insert ignore into non Constraint column result error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15365]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

85734e607d12a7a34ac31f8cdc91e72d9eaf98e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

EXPECT RESULT是mysql的结果，ACTUAL RESULT是mo的结果
<img width="1249" alt="企业微信截图_26451731-12bf-4cc3-8faf-f08aee431c08" src="https://github.com/matrixorigin/matrixone/assets/113406637/24ea1d9e-eb98-4aeb-9208-4ede34fbe9d8">

### Steps to Reproduce

```Markdown
create table insert_ignore_03(c1 int auto_increment primary key,c2 int,key(c2));
insert into insert_ignore_03(c2) values(2),(2),(5),(10),(12),(NULL);
insert ignore into insert_ignore_03(c2) values(7),(2),(5),(10),(12),(NULL);
select * from insert_ignore_03;
以上sql客户端执行可能不能复现，可以用mo-tester执行insert_ignore.sql
 ./run.sh -n -p  /Users/heni/matrixone/test/distributed/cases/dml/insert/insert_ignore.sql -m run
```

**Comment by heni02** [comment]
同样ignore结果错误，偶现不是必现
<img width="1136" alt="企业微信截图_dc6f4d5f-be56-4db1-a890-578000aa8e2f" src="https://github.com/matrixorigin/matrixone/assets/113406637/94175401-7bab-4ae3-8b3b-8cffebbaa72f">

create table insert_ignore_01(c1 int not null auto_increment primary key,c2 varchar(10));
insert into insert_ignore_01(c2) values("a"),("b"),("c"),("d");
insert ignore into insert_ignore_01 values(3,"e"),(6,"f"),(1,"g");
insert ignore into insert_ignore_01(c2) values("h"),("g"),("k");
insert ignore into insert_ignore_01 values(NULL,NULL);
select * from insert_ignore_01;

**Comment by ouyuanning** [comment]
辛苦锦赛先帮忙看看

**Comment by jensenojs** [comment]
重新设计insert ignore实现

**Comment by jensenojs** [comment]
正在编写文档

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
insert ignore需要重新实现

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
等重新设计方案

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
等on duplicate update的方案

**Comment by jensenojs** [comment]
等on dup的解决方案

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
PR合并进去就解决了

**Comment by heni02** [comment]
confirm,closed
commit: 
mysql> create table insert_ignore_03(c1 int auto_increment primary key,c2 int,key(c2));
Query OK, 0 rows affected (0.04 sec)

mysql> insert into insert_ignore_03(c2) values(2),(2),(5),(10),(12),(NULL);
Query OK, 6 rows affected (0.03 sec)

mysql> insert ignore into insert_ignore_03(c2) values(7),(2),(5),(10),(12),(NULL);
Query OK, 6 rows affected (0.03 sec)

mysql> select * from insert_ignore_03;
+------+------+
| c1   | c2   |
+------+------+
|    1 |    2 |
|    2 |    2 |
|    3 |    5 |
|    4 |   10 |
|    5 |   12 |
|    6 | NULL |
|    7 |    7 |
|    8 |    2 |
|    9 |    5 |
|   10 |   10 |
|   11 |   12 |
|   12 | NULL |
+------+------+
12 rows in set (0.00 sec)

mysql> create table insert_ignore_01(c1 int not null auto_increment primary key,c2 varchar(10));
Query OK, 0 rows affected (0.12 sec)

mysql> insert into insert_ignore_01(c2) values("a"),("b"),("c"),("d");
Query OK, 4 rows affected (0.05 sec)

mysql> insert ignore into insert_ignore_01 values(3,"e"),(6,"f"),(1,"g");
Query OK, 1 row affected (0.03 sec)

mysql> insert ignore into insert_ignore_01(c2) values("h"),("g"),("k");
Query OK, 3 rows affected (0.03 sec)

mysql> insert ignore into insert_ignore_01 values(NULL,NULL);
Query OK, 1 row affected (0.02 sec)

mysql> select * from insert_ignore_01;
+------+------+
| c1   | c2   |
+------+------+
|    1 | a    |
|    2 | b    |
|    3 | c    |
|    4 | d    |
|    6 | f    |
|    7 | h    |
|    8 | g    |
|    9 | k    |
|   10 | NULL |
+------+------+
9 rows in set (0.01 sec)
