### ISSUE TITLE
[Bug]: insert ignore values affected return 0 rows

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15364]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

85734e607d12a7a34ac31f8cdc91e72d9eaf98e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="879" alt="企业微信截图_4f76314e-60f0-4afc-a0be-9441d0df6277" src="https://github.com/matrixorigin/matrixone/assets/113406637/e7c72f13-58d2-479b-9663-ca6a5ee165aa">

### Steps to Reproduce

```Markdown
create table insert_ignore_03(c1 int auto_increment primary key,c2 int,key(c2));
insert into insert_ignore_03(c2) values(2),(2),(5),(10),(12),(NULL);
insert ignore into insert_ignore_03(c2) values(7),(2),(5),(10),(12);
select * from insert_ignore_03;
```

**Comment by noorall** [comment]
@heni02 辛苦确认一下。

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
处理
- https://github.com/matrixorigin/matrixone/issues/15809

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
等重新设计方案

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
等on duplicate update的方案

**Comment by jensenojs** [comment]
等on dup的解决方案

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by sukki37** [comment]
<img width="782" alt="image" src="https://github.com/user-attachments/assets/c61465ff-3c7d-4f15-bd0b-be7166229b30">

verified with 0a5786af3da2735110732c94427e15221d365fe6

**Comment by sukki37** [comment]
@heni02 please double check and add bvt case, thank you

**Comment by heni02** [comment]
confirm,closed
main commit:591164c4da15f5ad37eeadc9085c59ac2b529cda
<img width="1343" alt="企业微信截图_49ed1d1a-dd93-4567-a0bf-dd875fb978c5" src="https://github.com/user-attachments/assets/e89e9baa-6bb1-4ee6-aa47-70ba0ed984a1">
<img width="1332" alt="企业微信截图_4ea06b0b-b3bf-4900-bb3f-aebaa2545c9e" src="https://github.com/user-attachments/assets/af45c20c-eba4-4e7c-96f9-9ba58c2d8076">

**Comment by heni02** [comment]
目前bvtcase无法添加，insert返回结果都是空，后续修改mo-tester获取到insert影响行数返回
