### ISSUE TITLE
[Bug]: [date 4.7] tpcc regression test reported panic runtime error: slice bounds out of range [12:0]

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15374]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6d42483ce

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

standalone and tke all have this problem
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8589644507/job/23536979463
<img width="1078" alt="企业微信截图_1a78debc-12d6-4a3f-bee0-5599e24ea4a0" src="https://github.com/matrixorigin/matrixone/assets/113406637/16f2120b-d8b0-402e-9747-2ab0b2805a71">
2024-04-07 19:40:41 FATAL jTPCCTerminal:296 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: slice bounds out of range [12:0]: 
runtime.goPanicSliceB
	/usr/local/go/src/runtime/panic.go:154
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.getNonCompositePKSearchFuncByExpr.VarlenBinarySearchOffsetByValFactory.func41
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/search.go:95
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.getNonCompositePKSearchFuncByExpr.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/util.go:590
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).PKPersistedBetween
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:2352
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).PrimaryKeysMayBeModified
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:2391
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.hasNewVersionInRange
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:866
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:509
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:219
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:126
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:99
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:43
github.com/matrixorigin/matrixone/pkg/vm.Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:135
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:89
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:130
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:186
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%221V3%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240407%5C%22%7D%20%7C%3D%20%60internal%20error:%20panic%20runtime%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221712501575340%22,%22to%22:%221712544775340%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
regression tpcc test
```

**Comment by triump2020** [comment]
Primary keys persisted in ablk are not sorted, which maybe lead to this bug.
 https://github.com/matrixorigin/matrixone/blob/main/pkg/vm/engine/disttae/txn_table.go#L2352

**Comment by triump2020** [comment]
Fixed
