### ISSUE TITLE
[Bug]: insert ignore 100threads into non empty table reported  deadlock detected and other errors

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15393]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6d42483cee0475ac42dbd4c70bbf5e724a06b3dc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert ignore values 100threads into one table which rows 1000000+, and insert ignore into primary key overwrite conflicting and non conflicting values，then reported same errors:
1.ErrorMessage : info: constructValueScanBatch failed, node id: 018ebcf1-c6a9-7817-bd82-597e6e6085d3
2.ErrorMessage : deadlock detected
3.ErrorMessage : Communications link failure
The last packet successfully received from the server was 100,536 milliseconds ago. The last packet sent successfully to the server was 100,536 milliseconds ago.

<img width="1088" alt="企业微信截图_e847108f-33cb-417d-bcff-9783d83268f9" src="https://github.com/matrixorigin/matrixone/assets/113406637/18095414-14bc-4583-ab17-5320b84db6ad">
<img width="1513" alt="企业微信截图_e677e96f-64a9-4872-b8b2-e19f9ea1be7b" src="https://github.com/matrixorigin/matrixone/assets/113406637/0d2a7c02-e5e1-4e69-a08b-32ac4c874e61">

table ddl:
CREATE TABLE `test01` (
`c1` INT NOT NULL,
`c2` INT DEFAULT NULL,
PRIMARY KEY (`c1`)
)

and tps is very slow:
<img width="391" alt="企业微信截图_4cbeb97b-5003-444f-8c62-783f1e05bfa7" src="https://github.com/matrixorigin/matrixone/assets/113406637/6218bfc9-0a13-4f2b-8d6d-61af0ec4a20d">

test report：
[report.tar.gz](https://github.com/matrixorigin/matrixone/files/14903726/report.tar.gz)

mo log:
[mo_log (2).tar.gz](https://github.com/matrixorigin/matrixone/files/14903784/mo_log.2.tar.gz)

### Steps to Reproduce

```Markdown
1.use mo-load tool :git clone https://github.com/matrixorigin/mo-load.git
2.mysql client exec sql :create database db;create table test01(c1 int primary key,c2 int);
3.alter file :cd mo-load && vim cases/ddl/run.yml 
#stdout=console, 过程数据输出到控制台和文件
#stdout=file, 过程文件仅输出到文件
stdout: "console"
duration: 5 #所有transaction的执行时间，单位分钟
transaction:
  - name: "insert"  #transaction名称
    vuser: 100   #执行该transaction测试的并发量
    mode: 0 #执行模式，值为0表示script的中sql直接顺序执行，值为1表示把script的sql封装成一个数据库事务进行执行
    prepared: "false"   #是否需要对script的sql进行prepare
    #transaction的sql语句,可多条
    script:
    - sql: "insert into test01 values ({index},{tbx});"

4.table test01 prepare data:cd mo-load && ./start.sh -c cases/ddl/
5.alter file: cd mo-load && vim cases/ddl/replace.yml
- name: tbx
  type: random
  range: 1000000,1193320
6.alter file :cd mo-load && vim cases/ddl/run.yml 
#stdout=console, 过程数据输出到控制台和文件
#stdout=file, 过程文件仅输出到文件
stdout: "console"
duration: 5 #所有transaction的执行时间，单位分钟
transaction:
  - name: "insert"  #transaction名称
    vuser: 100   #执行该transaction测试的并发量
    mode: 0 #执行模式，值为0表示script的中sql直接顺序执行，值为1表示把script的sql封装成一个数据库事务进行执行
    prepared: "false"   #是否需要对script的sql进行prepare
    #transaction的sql语句,可多条
    script:
    - sql: "insert ignore into test01 values ({tbx},{tbx});"
7.run test:cd mo-load && ./start.sh -c cases/ddl/
8.report view: cd mo-load/report/
```

**Comment by heni02** [comment]
insert on duplicate update 100threads也有同样的问题
<img width="826" alt="企业微信截图_c00dac3b-1585-4055-bdba-c8f8a50095c0" src="https://github.com/matrixorigin/matrixone/assets/113406637/5561625c-fefd-4d19-93b9-b8f0cb0e16f2">

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/MO-Cloud/issues/2956

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
等文档评审

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
暂无进展

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理
- https://github.com/matrixorigin/matrixone/issues/15809

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
等重新设计方案

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
等on duplicate update的方案

**Comment by jensenojs** [comment]
等on dup的解决方案

**Comment by jensenojs** [comment]
not working on it

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
#17500 完成后再看

**Comment by aunjgr** [comment]
insert ignore性能已改善

**Comment by heni02** [comment]
confirm，closed
2.0-dev commit:c4030208b29db7f35e03d18c97c58cbdc5de4e63
测试场景：单表100万行数据，insert into ignore全部有重复值，并发100测试tps值：27036，运行15分钟之间tps比较稳定，没有大的波动

测试过程：mo-load工具case run.yaml sql修改为sql: "insert ignore into test01 values ({tbx},{tbx});"，tbx随机取1-10000000数值，运行15分钟
<img width="805" alt="企业微信截图_dc0d24e8-adba-4dc7-909a-38ee68b05245" src="https://github.com/user-attachments/assets/6d93ef63-944e-4a4f-b154-2eff903a4c8e">

单表数据验证正确：
<img width="605" alt="企业微信截图_494efde0-16e3-4e2c-a5aa-e659666a498c" src="https://github.com/user-attachments/assets/60896ea0-ccea-4d11-8b47-e325612a353c">
