### ISSUE TITLE
[Bug]: CN restart by FATAL runtime error: invalid memory address or nil pointer dereference during stability test on distributed test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15417]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

444d0285de80b69c21dab35f7486d13fa817f2ee

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

After stability test on distributed test for about 8 hours, two cns were creash by fatal :

{"level":"FATAL","time":"2024/04/09 10:50:28.485671 +0000","name":"cn-backend","caller":"morpc/backend.go:436","msg":"write loop failed","remote":"10.10.5.84:6002","backend-id":"018ec27a-9c84-7639-aada-cc9b58be9d00","err":"runtime error: invalid memory address or nil pointer dereference","stacktrace":"github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).writeLoop.func3\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:436\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:890\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:260\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:841\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.RPCMessage.Timeout\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/message.go:30\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).doWrite\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:506\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).writeLoop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:469\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}

<img width="632" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7790c1e4-33e1-49d4-bbbf-b9e6571ccb2c">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22v33%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-444d028-20240409%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221712659824719%22,%22to%22:%221712659908764%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster
2. run tpch 10g loop queries 
3. run tpcc 10-10 longrunning test
4. run sysbench mixed cases longrunning test
```

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
done
