### ISSUE TITLE
[Bug]: select from processlist执行报错

### ISSUE THREAD

**Issue by TangxingZhou** [matrixorigin/matrixone#15423]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

1cc551d64

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from processlist;
ERROR 1064 (HY000): SQL parser error: table "processlist" does not exist

### Steps to Reproduce

```Markdown
连接mo后执行sql:
select * from processlist;
```

**Comment by qingxinhome** [comment]
<img width="948" alt="企业微信截图_17121286942804" src="https://github.com/matrixorigin/matrixone/assets/70939751/636cf098-babb-497b-a3cd-a74fe10fb8ba">

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been submitted. Please test and verify @TangxingZhou @sukki37 @aressu1985 @daviszhen

**Comment by TangxingZhou** [comment]
<img width="833" alt="image" src="https://github.com/matrixorigin/matrixone/assets/13430648/1767cca1-103d-4f22-882a-bc68e46fdf53">
验证通过
