### ISSUE TITLE
[Bug]: stats.cost incorrect for agg&table_scan node

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#15459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

8fcd34f283adfd685b79fb4ee3717d46996c622e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="361" alt="WeChatWorkScreenshot_a2ba0ee3-5379-48d1-ab54-b908d62e8f05" src="https://github.com/matrixorigin/matrixone/assets/45346669/1d95e2b8-9568-4f78-9fa6-9ade69ca452e">
[exec.json](https://github.com/matrixorigin/matrixone/files/14942402/exec.json)

### Steps to Reproduce

```Markdown
make cost correct
```

**Comment by nnsgmsone** [comment]
this is the stats info

**Comment by badboynt1** [comment]
需要找到复现的方法，从代码里看不出什么情况下会变成负数。。。
或者有可能是序列化时出现了bug

**Comment by badboynt1** [comment]
暂无进展

**Comment by badboynt1** [comment]
麻烦帮忙一起看吧

**Comment by qingxinhome** [comment]
从代码看，blocknum，outcnt 和cost 三个属性来自于Node的Stats统计结果，在将Logic Plan Node转换为Json过程中，未对数据进行修改加工，字段数据类型匹配，没有发现问题
![image](https://github.com/user-attachments/assets/8fba6eb0-720d-454f-87ec-df0c5880c22c)

建议对Stats计算流程和公式进行检查 @badboynt1

**Comment by fengttt** [comment]
Not repro.   Let's close.
