### ISSUE TITLE
[Bug]: bvt test in purge_log fail occasionally

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#15455]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-04-11 03:54:09 ERROR RSRow:83 - The value of [row:0,column:0] does not equal with each other,one is [0],but the other is [12]
2024-04-11 03:54:09 ERROR Executor:197 - [/home/runner/work/matrixone/matrixone/test/distributed/cases/function/func_purge_log.sql][row:28][select count(1) val from system_metrics.metric where `collecttime` <  DATE_ADD( @ts, interval 1 minute);] was executed failed, con[id=0, user=dump, ***
2024-04-11 03:54:09 ERROR Executor:199 - [EXPECT RESULT]:
val
0
2024-04-11 03:54:09 ERROR Executor:200 - [ACTUAL RESULT]:
val
12

### Steps to Reproduce

```Markdown
set @ts=now();
select purge_log('statement_info,metric', DATE_ADD( @ts, interval 1 day)) a;
select count(1) val from system_metrics.metric where `collecttime` <  DATE_ADD( @ts, interval 1 minute);
```

**Comment by xzxiong** [comment]
ref 
https://github.com/matrixorigin/matrixone/actions/runs/8641322890/job/23691333297

**Comment by xzxiong** [comment]
fixed

**Comment by guguducken** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8716883855/job/23911544793
<img width="1376" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/521a63eb-196d-4888-b945-902efbe56d30">

**Comment by guguducken** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8719735887/job/23920573937
<img width="1384" alt="image" src="https://github.com/matrixorigin/matrixone/assets/22561920/a0e83578-40c2-4d41-b3a8-3bf734029556">

**Comment by xzxiong** [comment]
check root couse.

- error log
https://github.com/matrixorigin/matrixone/actions/runs/8733421065/job/23962776136
for pr https://github.com/matrixorigin/matrixone/pull/15558

![image](https://github.com/matrixorigin/matrixone/assets/3927687/bf0ffb1d-895f-4a9a-940e-78fb81c22f80)

- db data (跳板机-> nightly-devops)
port-forward
![image](https://github.com/matrixorigin/matrixone/assets/3927687/7e6a0924-29bf-45de-ade6-9095906a85d2)
login (dump: 111), min collecttime: `2024-04-18 06:59:52.312910`
![image](https://github.com/matrixorigin/matrixone/assets/3927687/cada30f9-86ea-4db1-a483-e550f9e39519)

**Comment by xzxiong** [comment]
确认：bvt case的逻辑没问题，DB的数据也没有异常。就是 date_sub 错用了date_add的问题。

**Comment by xzxiong** [comment]
repo:
Information System View Tenant Isolation-1.1-dev #1965
pr: https://github.com/matrixorigin/matrixone/pull/15416
https://github.com/matrixorigin/matrixone/actions/runs/8765708828/job/24057162905

<img width="1259" alt="企业微信截图_89f41236-b590-4ee0-8f97-12c448ec6edf" src="https://github.com/matrixorigin/matrixone/assets/3927687/c3077c96-1499-43ec-8a87-e42673b562f8">


<img width="1527" alt="企业微信截图_8367ea47-7f5a-42fe-9faf-cd20aad378fc" src="https://github.com/matrixorigin/matrixone/assets/3927687/6da2cf9b-5841-408f-805d-dddd85578306">

log [link](https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gQU%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-15416%5C%22%7D%20%7C%3D%20%60upload%20files%20success%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713571200000%22,%22to%22:%221713625199000%22%7D%7D%7D&schemaVersion=1&orgId=1)
- 74 个文件，一个 5 个node，大概 15个点 = 74 / 5，每 15秒一个点。
<img width="1661" alt="企业微信截图_d94b82ca-f1aa-4316-b7b4-00f210615080" src="https://github.com/matrixorigin/matrixone/assets/3927687/4393e415-f522-4b22-bf57-64d66225c266">

> select collecttime, node, count(1) cnt from system_metrics.metric where collecttime < '2024-04-20 14:45:09' and node = '00000000-0000-0000-0000-000000000001' group by collecttime, node order by collecttime;

<img width="1621" alt="企业微信截图_303038e9-d6c2-4f37-a857-94ca4e063346" src="https://github.com/matrixorigin/matrixone/assets/3927687/3f3771bb-fe5b-41d8-9fa6-7a1482ff10d7">

**Comment by xzxiong** [comment]
> repo: Information System View Tenant Isolation-1.1-dev #1965 pr: #15416 https://github.com/matrixorigin/matrixone/actions/runs/8765708828/job/24057162905
> ...

原因分析:  遇到 metric 数据从 csv 回写mo.

**Comment by xzxiong** [comment]
Next: 1) 停掉 task service; 2) 改写 case

**Comment by xzxiong** [comment]
> > repo: Information System View Tenant Isolation-1.1-dev #1965 pr: #15416 https://github.com/matrixorigin/matrixone/actions/runs/8765708828/job/24057162905
> > ...
> 
> 原因分析: 遇到 metric 数据从 csv 回写mo.
> 
> 从日志看出：回写了 74 个文件，仅包含 4 个node（3log+1tn）

有部分metric数据落到csv文件了，有个5分钟执行一次的task: ETLMerge将这些metric数据写回table
----
所以
1. 先是purge_log删掉数据，
2. task ETLMerge将老数据从csv回写mo，
3. 查询metric，发现还有老数据

**Comment by xzxiong** [comment]
> > repo: Information System View Tenant Isolation-1.1-dev #1965 pr: #15416 https://github.com/matrixorigin/matrixone/actions/runs/8765708828/job/24057162905
> > ...
> 
> 原因分析: 遇到 metric 数据从 csv 回写mo.
> 
> 从日志看出：回写了 74 个文件，仅包含 4 个node（3log+1tn）


修改方案 1 （否决）
---
通过begin-commit 一个事务中，对write隔离。—— 现在支持的 read-commited 所有无效。

修改方案 2 
---
通过事务隔离，阻塞 task: ETLMerge 写入：
- [x] 需要关联 purge_log 与 background sql: `delete` 的事务 —— 可以解决
- [ ] frontend 要支持 lock table语句，目前仅支持语义，但没有实际操作。

修改方案3
---
仅判断一条语句是否被删除。
```
-- prepare
set  @ts=(select max(collecttime) from system_metrics.metric);
set  @metric_name=(select metric_name from system_metrics.metric where collecttime = @ts limit 1);
set  @node=(select node from system_metrics.metric where collecttime = @ts and metric_name=@metric_name limit 1);
...
-- check
select count(1) cnt, @ts, @metric_name, @node from  system_metrics.metric where collecttime = @ts and metric_name=@metric_name and node=@node;
```

**Comment by xzxiong** [comment]
观察中

**Comment by xzxiong** [comment]
观察中
