### ISSUE TITLE
[Bug]: the value of keep_user_target_list_in_result is incorrect

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#15466]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7b1c01cb0df42a94be48c1491166da291e473b79

### Other Environment Information

```Markdown
- Hardware parameters: tke
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8641322890/job/23691333297

### Expected Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8641322890/job/23691333297

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/8641322890/job/23691333297
```

**Comment by guguducken** [comment]
repo: https://github.com/matrixorigin/matrixone/actions/runs/8643718525/job/23698210952

**Comment by YANGGMM** [comment]
fixed
