### ISSUE TITLE
[Refactoring]: Remove or replace mmap with malloc

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#15479]
### Why do you want to refactor this code?

```Markdown
Using mmap is very problematic.  
The reason for using mmap is not sound, or complete clear to me.
```

### Describe the solution you'd like

Either remove it and use malloc, or, have a config variable that we can dynamically switch during system start up.

Investigate better memory allocator than libc malloc -- such as mimalloc.

Finally, malloc has a slight "advantage" -- the memory allocated by malloc is not zeroed.  We immediately overwrite the memory therefore the mem zero is pure waste.   Not sure if this is a deal.

**Comment by reusee** [comment]
done
