### ISSUE TITLE
[Bug]: The system oom is executed when DDL is executed

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#1549]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4fefca145b51d01371f706e7fd938990e51941c0
- Hardware parameters:
- OS type:mac os,centos
- Others:
```

### Actual Behavior

When the number of copies is less than the number of nodes, the system oom is executed when DDL is executed
![image](https://user-images.githubusercontent.com/14086886/147542581-9fe58acc-4530-48ee-9b8d-afd642ba81a9.png)

**Comment by lni** [comment]
Resolved in https://github.com/matrixorigin/matrixcube/pull/632

need to update go.mod to use the latest version of MatrixCube.
