### ISSUE TITLE
[Bug]: when use newly created user to connect mo, if db is not used. deleting table doesn't report error.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15491]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

90f816f58cf50401ca70e1608eacafdf85d50239

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

如果使用新建的account连接db，此时如果不使用use db这条sql，直接删除table不报错
<img width="566" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/4feddcb8-ace3-417b-87e7-6b998f2eb907">
<img width="730" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b5ad5556-6be3-4f4f-9c93-04f62dd31531">

### Expected Behavior

如果使用新建的account连接db，此时如果不使用use db这条sql，直接删除table要报错

### Steps to Reproduce

```Markdown
drop database if exists db1;
create database db1;
use db1;
drop role if exists role_r1;
drop user if exists role_u1;
create role role_r1;
create user role_u1 identified by '111' default role role_r1;
drop table if exists t1;
create table t1(col1 int);
insert into t1 values(1);
insert into t1 values(2);
grant create database, drop database on account * to role_r1;
grant show databases on account * to role_r1;
grant connect on account * to role_r1;
grant create table, drop table on database *.* to role_r1;
grant show tables on database * to role_r1;

-- @session:id=4&user=sys:role_u1:role_r1&password=111
drop table if exists t2;          ->此处应该报错.
create table t2 as select * from t1;
```

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been submitted. Please verify and test it @Ariznawlll @sukki37 @daviszhen

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
<img width="829" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5486a10a-f56a-45f0-a4ca-a332d8a4b0da">
<img width="825" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3c249cb1-6ad9-4c77-aedb-2529f38f2798">

verified.
