### ISSUE TITLE
[Tech Request]: do not share CacheData between caches

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#15508]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Each cache should allocate their objects with their allocators.
Do not share objects.
Object may be copied, to avoid calling ToCacheData multiple times. 
This is required for reader-scoped caching.
```

**Comment by fengttt** [comment]
#16204 reverted prev two PRs.

**Comment by reusee** [comment]
done
