### ISSUE TITLE
[Feature Request]: Add metrics to file service

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#15509]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
File service code needs to be instrumented.
We are missing too many metrics and the debugging
and analyzing file service performance is 
very painful.

We need to add a lots of metrics.
```

### Describe the feature you'd like

Use the metric framework of the system.   Instrument our code.
For example, for the file read/lock, we should have metrics on, 
1. how many of the lock is called,
2. how many of them acquired the lock and do the real work
3. how much time spend holding the lock and do work.
4. for major component it the work, such as LRU, malloc, time spent.
5. how many of them waited
6. how much time spent waiting

**Comment by reusee** [comment]
为什么不是优化motrace？motrace也是一早就加入的，泽雄也花了很大功夫去实现。file service里也用了motrace。
既然都用了grafana，为什么只能用prometheus，不能用其他数据源？
prometheus这些计数器直方图，只能反映单一的指标，缺乏上下文。就算测量出io lock等待变长，怎么知道具体是什么原因导致？持有io lock时，会做很多事情。磁盘缓存，内存缓存，读磁盘/S3，单靠这些缺乏联系的数值，怎样得出瓶颈在哪里？就连瓶颈在分配器，也是off-cpu profile找出来的，火焰图一眼就看得出来。单靠计数器要花多少功夫？这些粗粒度的测量，不可能替代profile和trace。
我不反对加这些，但这些真的不够用。
加强motrace，让grafana可以看motrace的数据，这是更值得做的。

**Comment by aressu1985** [comment]
fixed
