### ISSUE TITLE
[Bug]: occasional ut failed `TestCheckTimeoutServiceTask`

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#15513]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

https://github.com/daviszhen/matrixone/tree/0410-split-code

### Commit ID

62eada6652f123044ff7e2ded6f172867cf9cac2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

https://github.com/matrixorigin/matrixone/actions/runs/8679331863/job/23797872327?pr=15497
```

### Actual Behavior

2024-04-14T10:38:12.0272917Z 
2024-04-14T10:38:12.0273027Z # FAILED CASES:
2024-04-14T10:38:12.0273236Z --- FAIL: TestCheckTimeoutServiceTask (0.04s)
2024-04-14T10:38:12.0273243Z 

### Expected Behavior

success

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/8679331863/job/23797872327?pr=15497
```

**Comment by iamlinjunhong** [comment]
fixed
