### ISSUE TITLE
[Bug]: ci w-w conflict

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#15511]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

https://github.com/daviszhen/matrixone/tree/0410-split-code

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/8670243838/job/23777988777?pr=15497
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /home/runner/work/matrixone/matrixone/head/test/distributed/cases/ddl/create_table_as_select.sql
[ROW    NUMBER]: 1340
[SQL STATEMENT]: set @@global.lower_case_table_names = 1;
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
w-w conflict

### Expected Behavior

no conflict

### Steps to Reproduce

```Markdown
occasional

https://github.com/matrixorigin/matrixone/actions/runs/8670243838/job/23777988777?pr=15497
```

**Comment by XuPeng-SH** [comment]
@volgariver6 please investigate this issue

**Comment by volgariver6** [comment]
该问题是由 https://github.com/matrixorigin/matrixone/pull/14983 导致，在乐观模式下，每个用户登录的时候都会更新 mo_catalog.mo_mysql_compatibility_mode 表，所以会报 w-w conflict 是正常的。这个pr的逻辑不正确，需要调整。

在悲观模式下不存在该问题。

**Comment by daviszhen** [comment]
it was fixed
