### ISSUE TITLE
[Bug]: mo hung during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15538]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

95801d84dc017970b404c15b7e72e4c471d84339

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C  64G
1*DN: 16C  64G
3*LOG: 4C 16G
- OS type:
- Others:
```

### Actual Behavior

After stability test on distributed mode for about 6 hours, the mo hung compleletedly:

<img width="630" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ab0ea6f8-77f4-472e-adca-4e1e1bb6ac4d">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22gF4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-95801d8-20240415%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713163770000%22,%22to%22:%221713250170000%22%7D%7D%7D&schemaVersion=1&orgId=1

mo-profile:
[prof.tar.gz](https://github.com/matrixorigin/matrixone/files/14985417/prof.tar.gz)

### Steps to Reproduce

```Markdown
1. run mo cluseter as config in this issue
2. run tpch 10G loop queries in a account with 2 concurrency
3. run tpcc 10-20 longrunnig test in a account 
4. run sysbench mixed case longrunning test with 150 threads in 2 differnt accounts
```

**Comment by zhangxu19830126** [comment]
经过分析，都卡在了等待活跃事务上。测试的压力300多并发事务，最大活跃事务数只有16C*4*4，不到300.

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
update on 04.24:
commit: d124332
1. 有大量的longrunning error在日志中
link: https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%226r0%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-d124332-20240423%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713929311853%22,%22to%22:%221713950733876%22%7D%7D%7D&schemaVersion=1&orgId=1

2. go routine

**Comment by sukki37** [comment]
Insufficient context and debug information. Closing this issue for now. Please open a new issue if it recurs.
