### ISSUE TITLE
Slow performance on `select * from tb1 limit 10`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#1553]
SQL like `select * from tb1 limit` executes slowly.  For example, I have a table that contains 3,000,000 rows, when `select * from customer limit 10; ` is executed, it will take 1~2s to get the result which is too slow.

**Comment by m-schen** [comment]
now, we get all date from aoe, and then do limit work because maybe we have order or group work needs to do.
I think for a simple query like issue says `select * from customer limit 10;`, we can push this limit condition down in next or maybe another version.

**Comment by m-schen** [comment]
fixed it. 
if the SQL only contain limit filter-condition, we will push the limit condition down. You can perform verification and comparison at Branch main.

**Comment by m-schen** [comment]
we do comparison at 24e8b43950a27afd4c63b1db7cb3322ed6da28c9
and data size is 200000
select * cost 0.28s
and limit 10 cost 0.08s
