### ISSUE TITLE
[Bug]: tpcc 10-10 performance degradation.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15540]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9b548ba179a336aa8fe05da1c0fae83ef25dcbee

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="919" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c79385b9-c716-4552-8762-760b2e42c999">

<img width="1411" alt="企业微信截图_157e5a2d-9b22-4f5a-bd2f-df0f6b840d3d" src="https://github.com/matrixorigin/matrixone/assets/108530700/b09c2e20-972b-403e-950a-2a60820e7d40">

### Steps to Reproduce

```Markdown
daily regression on tke.
```

**Comment by Ariznawlll** [comment]
<img width="1479" alt="企业微信截图_280fec2c-c3b6-414d-9923-8904534ff989" src="https://github.com/matrixorigin/matrixone/assets/108530700/8313f5b1-76ec-47aa-b497-dac66c8bd730">

469a781363b4457fc072510a39d0e4aae9575551 这个commit两次执行的差距较大，所以找的不准确

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
无进展, 不确定是哪个pr的问题

**Comment by jensenojs** [comment]
not working on it
