### ISSUE TITLE
[Bug]: cn crash by panic: internal error: mpool compile unavailable for free during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15543]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

95801d84dc017970b404c15b7e72e4c471d84339

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 16C 64G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, sometimes cn may be crashed by:
panic: internal error: mpool compile unavailable for free

goroutine 11003034 [running]:
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc2596c0a80, {0xc26f045810, 0x1, 0x4000})
	/go/src/github.com/matrixorigin/matrixone/pkg/common/mpool/mpool.go:629 +0x75e
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Free(0xc560e15f40, 0xc2596c0a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:410 +0x58
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).Clean(0xc55e0eba80, 0xc2596c0a80)
	/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:212 +0x136
github.com/matrixorigin/matrixone/pkg/sql/compile.decodeBatch(0xc2596c0a80, {0x0, 0x0}, {0xc56a4a6000, 0x977a, 0xa000})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scopeRemoteRun.go:1691 +0x345
github.com/matrixorigin/matrixone/pkg/sql/compile.receiveMsgAndForward(0xc0b294c580, 0xc356dc6ba0, 0xc4ccb1cae0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:927 +0x5a5
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).notifyAndReceiveFromRemote.func1(0xc69fd4afa0, 0xc260afed20)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:875 +0x6cc
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).notifyAndReceiveFromRemote
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:826 +0x1e9

mo-log:
https://shanghai-idc.1matrix.org:30088/explore?panes=%7B%22In6%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-95801d8-20240416%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713245555699%22,%22to%22:%221713250684688%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run mo cluseter as config in this issue
2. run tpch 10G loop queries in a account
3. run tpcc 10-10 longrunnig test in a account 
4. run sysbench mixed case longrunning test with 75 threads in 2 differnt accounts
```

**Comment by m-schen** [comment]
这个是当某个内存要被释放时，分配它的mpool已经被销毁了。

应该是mpool的销毁流程不对导致的问题，导致在判断完 in use count == 0后仍旧被使用。


<img width="724" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/d2e033f2-e904-4e5a-ae18-385bf20c91b2">

应该先修改状态到准备删除，然后进行判断，如果非0的话，则继续转换成可用状态。

**Comment by m-schen** [comment]
找到问题了，
<img width="1061" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/3d28b0a0-b15d-45bd-a5c0-20ad4abf6f6c">

图中
212行 启动n个新协程等去做 `从远端收取数据，decode，并使用`的行为
在之前的代码中也会启动 m个新协程等做一些事情。

在237行到250的循环中，获取m, n个协程的返回信息，一旦碰到错误就返回查询结果，而这个返回将会触发destory mpool的行为，由于212行启动的n个协程并不受到影响（实际上是会受到影响的，这n个协程所持有的context会结束来通知它们查询已经结束，可以退出，但如果恰好此时正在执行与mpool相关的动作，便会由于mpool被标记为不可用而导致panic）。

**Comment by m-schen** [comment]
可以在1.1分支上进行该bug的验证，main分支的pr还在跑，估计要晚些时候合并。

**Comment by m-schen** [comment]
pr revert了 后面再重新转

**Comment by m-schen** [comment]
等main分支的合并了再一起转

**Comment by m-schen** [comment]
1.1和main分支上都合并了修复的pr。

修复了当查询结束后，负责从远程收取数据的pipeline没有及时退出，导致了mpool的race的问题。

问题原因是：
由于内部执行器在查询结束后会销毁mpool，而pipeline还在使用mpool，因此产生了非法mpool的错误。（mpool已经被销毁，但仍有对象操作它进行allocate或者free的动作）

**Comment by aressu1985** [comment]
fixed
