### ISSUE TITLE
[Bug]: update table mo_catalog.mo_mysql_compatibility_mode too slow

### ISSUE THREAD

**Issue by ck89119** [matrixorigin/matrixone#15597]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.1.3

### Commit ID

95801d84d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

以100qps 获取mo连接并执行一条简单sql `select count(*) from t (t表只有一条数据)`，记录执行时间：
<img width="950" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/105730ed-c88e-4503-aa2c-2d28f3237345">

上图左边是commit: 95801d84d 的执行时间，右边是commit: 14c4496c6，执行时间差距巨大，而且左边执行时间会越来越长。

它们在代码上的区别：左边在auth的时候需要执行两条update语句 `update mo_catalog.mo_mysql_compatibility_mode set variable_value = '%s' where account_id = %d and variable_name = '%s';`，右边不执行。

这是执行时抓取的cpu profile
cpu top:
<img width="1235" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/c2938f25-e734-4546-8f0c-2542dfb6155d">

flame graph:
<img width="1905" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/7c1c4684-cbe9-46e8-8362-67ce11cb2661">

### Steps to Reproduce

```Markdown
1. 本地起mo
2. 以100qps的速度获取mo连接，执行一条简单sql
```

**Comment by aylei** [comment]
ref: https://github.com/matrixorigin/matrixone/pull/15560

**Comment by aylei** [comment]
@daviszhen PTAL and triage

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
系统变量调整后，再确认下。

**Comment by ck89119** [comment]
系统变量重构 #16551 完成后，每次登录鉴权不再会更新mo_mysql_compatibility_mode表。

在当前最新的1.2-dev分支（commit: ed9811a75)，重新跑上面的测试，执行时间已经正常了：

<img width="420" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/d5d16e57-a100-44b1-8ae6-bdc3747b7ebc">
