### ISSUE TITLE
[Bug]: the funtion of mo_table_col_max() 'result is null in subscription table.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15607]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

90f816f58cf50401ca70e1608eacafdf85d50239

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="482" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/615005fb-8e1e-484d-be30-1e50843b5d2a">

### Expected Behavior

3
1

### Steps to Reproduce

```Markdown
drop database if exists database01;
create database database01;
use database01;
create table t1(a int, b int);
insert into t1 values (1, 1), (2, 2), (3, 3);
create publication publication01 database database01;
-- @ignore:2,3
show publications;

drop account if exists test_tenant_1;
drop account if exists test_tenant_2;
create account test_tenant_1 admin_name 'test_account' identified by '111';
create account test_tenant_2 admin_name 'test_account' identified by '111';

-- @session:id=4&user=test_tenant_1:test_account&password=111
drop database if exists sub_database01;
create database sub_database01 from sys publication publication01;
-- @ignore:3,5
show subscriptions;
use sub_database01;
show tables;
select * from t1;
select mo_table_col_max('sub_database01', 't1', 'a');
select mo_table_col_min('sub_database01', 't1', 'b');
-- @session
```

**Comment by ck89119** [comment]
本地能复现，看起来像有延迟，继续排查中

<img width="728" alt="企业微信截图_09f1da7f-781d-4ae2-a955-1d849f55e1c3" src="https://github.com/matrixorigin/matrixone/assets/4971300/15c9c241-f9fe-49b3-9559-a47e3e9e3304">

**Comment by ck89119** [comment]
col_min/max调用了range函数，这个函数就是有延迟的，产品知晓这个问题。
![Uploading image.png…]()

**Comment by Ariznawlll** [comment]
In process.

**Comment by Ariznawlll** [comment]
verified
