### ISSUE TITLE
[Bug]: [date 4.18]standalone regression: tpcc  100 warehouse 100threads  internal error: panic BUG: invalid ref count

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15614]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

57def8e01aad11c56b91943ea8a2210a4ff67da9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8739677543/job/23981721332
<img width="1254" alt="企业微信截图_3b460941-1776-4b20-803c-4cdb2e3c189d" src="https://github.com/matrixorigin/matrixone/assets/113406637/8f76d0db-c250-4bb2-82e0-3fc432d068d7">

two internal panic error:
1.
2024-04-19 06:43:03 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic BUG: invalid ref count, -0xc043306700(-1): 
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).close
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/waiter.go:109
github.com/matrixorigin/matrixone/pkg/lockservice.(*sliceBasedWaiterQueue).notify
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/waiter_queue.go:[126](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8739677543/job/23981721332#step:9:127)
github.com/matrixorigin/matrixone/pkg/lockservice.Lock.closeTxn
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock.go:176
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock.func3
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_local.go:277
github.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlice).iter
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/slice.go:151
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_local.go:231
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close.(*activeTxn).close.func1.func3
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/txn.go:160
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/txn.go:176
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Unlock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/service.go:210
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).unlock.func2
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:1077
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).doCostAction
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:1203
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).unlock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:1073
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Rollback
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:572
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).RollbackTxn
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/txn.go:470
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).rollbackWholeTxn
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/txn.go:788
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).TxnRollbackSingleStatement
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/txn.go:757
github.com/matrixorigin/matrixone/pkg/frontend.rollbackTxnFunc
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/txn.go:860
github.com/matrixorigin/matrixone/pkg/frontend.finishTxnFunc
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/txn.go:906
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn.func1
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2431
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2470
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2401
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2834
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2963
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:279
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:515
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/server.go:168
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9[130](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8739677543/job/23981721332#step:9:131)ca/application.go:356
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650

2.
2024-04-19 06:43:03 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic BUG: invalid ref count: 
github.com/matrixorigin/matrixone/pkg/lockservice.acquireWaiter
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/waiter.go:45
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRangeLockLocked
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_local.go:415
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_local.go:352
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_local.go:101
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_local.go:83
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/service.go:166
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/lockop/lock_op.go:468
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/lockop/lock_op.go:226
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callBlocking
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/lockop/lock_op.go:165
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/lockop/lock_op.go:102
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:61
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:61
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/connector/connector.go:43
github.com/matrixorigin/matrixone/pkg/vm.Run
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/vm.go:135
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:156
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:215
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:194
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650

mo log:
[mo_log0419.tar.gz](https://github.com/matrixorigin/matrixone/files/15032595/mo_log0419.tar.gz)

### Steps to Reproduce

```Markdown
standalone tpcc 100 warehouse 100threads test
```

**Comment by heni02** [comment]
date 4.21 regression  
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8773410767/job/24074264039
commit：652cc255d
panic: BUG: invalid ref count, -0xc07049b680(-1)

goroutine 395 [running]:
panic({0x3d1b960?, 0xc011854300?})
        /usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc01dbd1d88 sp=0xc01dbd1cd8 pc=0x44162c
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).close(0xc0000e85a0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter.go:108 +0x74 fp=0xc01dbd1dc0 sp=0xc01dbd1d88 pc=0x12a9a94
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiterEvents).check(0xc0000e85a0, 0x12a05f200)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter_events.go:194 +0x297 fp=0xc01dbd1e98 sp=0xc01dbd1dc0 pc=0x12abb77
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiterEvents).handle(0xc0000e85a0, {0x5023f78, 0xc00266a570})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter_events.go:176 +0x1eb fp=0xc01dbd1f70 sp=0xc01dbd1e98 pc=0x12ab7eb
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiterEvents).handle-fm({0x5023f78?, 0xc00266a570?})
        <autogenerated>:1 +0x33 fp=0xc01dbd1f98 sp=0xc01dbd1f70 pc=0x12c7df3
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:277 +0x6e fp=0xc01dbd1fe0 sp=0xc01dbd1f98 pc=0xa16e2e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc01dbd1fe8 sp=0xc01dbd1fe0 pc=0x478441
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 301
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:272 +0xd6

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22G2S%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240421%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713716340000%22,%22to%22:%221713716419000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by iamlinjunhong** [comment]
fix pr : https://github.com/matrixorigin/matrixone/pull/15644
