### ISSUE TITLE
[Bug]: [date 4.18]standalone regression: tpcc 10/100 warehouse test reported deadlock detected

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15612]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

57def8e01aad11c56b91943ea8a2210a4ff67da9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc 10warehouse 100threads and 100warehouse 100/1000threads test all reported deadlock detected
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8739677543/job/23981721332
<img width="1267" alt="企业微信截图_9aea7f3d-c970-4d31-80a6-eeb7a2703808" src="https://github.com/matrixorigin/matrixone/assets/113406637/4b1a0178-5664-462a-9538-d39b68e8b164">

mo log：
[mo_log0419.tar.gz](https://github.com/matrixorigin/matrixone/files/15032505/mo_log0419.tar.gz)

### Steps to Reproduce

```Markdown
standalone tpcc 10warehouse 100threads and 100warehouse 100/1000threads test
```

**Comment by iamlinjunhong** [comment]
fix pr: https://github.com/matrixorigin/matrixone/pull/15633
