### ISSUE TITLE
[Bug]: ut failed. TestDeadLockWithIndirectDependsOn

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#15610]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0418-fix-local-local

### Commit ID

0eb9abf805e6a0620e966459dd387a7dea830e9e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

https://github.com/matrixorigin/matrixone/actions/runs/8738946303/job/23979131004
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8738946303/job/23979131004

![Screenshot from 2024-04-18 23-05-49](https://github.com/matrixorigin/matrixone/assets/60595215/57f3f843-c3b6-4ab5-aee9-93efb3a00f04)

### Expected Behavior

success

### Steps to Reproduce

```Markdown
occasional
```

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/8747811301/job/24006853596?pr=15613

log is too large to upload here, please contact me if needed

**Comment by zhangxu19830126** [comment]
fixed

**Comment by daviszhen** [comment]
it was fixed.
