### ISSUE TITLE
[Bug]: cn panic by panic: runtime error: invalid memory address or nil pointer dereference during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15620]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

5c0ae1c80a3fb8cadb696c657ae98f286687b982

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

After stability test on distributed mode for about 24 hours, on cn crashed by panic:
{"level":"ERROR","time":"2024/04/19 05:45:47.271854 +0000","name":"cn-service.frontend","caller":"frontend/util.go:512","msg":"query trace status","uuid":"33663234-6133-3339-3032-353139343664","connection_id":112844,"statement":"execute __mo_stmt_id_20 // prepare __mo_stmt_id_20 from SELECT c_id     FROM bmsql_customer     WHERE c_w_id = ? AND c_d_id = ? AND c_last = ?     ORDER BY c_first ; 6 ; 6 ; PRESBARANTI","status":"fail","error":"internal error: panic runtime error: invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:260\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:841\nsync.(*Map).loadReadOnly\n\t/usr/local/go/src/sync/map.go:111\nsync.(*Map).Load\n\t/usr/local/go/src/sync/map.go:121\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).Database\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:168\ngithub.com/matrixorigin/matrixone/pkg/vm/engine.(*EntireEngine).Database\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/entire_engine.go:60\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScanWithNode\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:2022\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1992\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1084\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1181\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compilePlanScope\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:1101\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:934\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:626\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:268\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/computation_wrapper.go:384\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3612\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4204\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:4430\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:247\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:529\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:145\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","span":{"trace_id":"08d655e4-50a2-22e0-82ec-e16722c3cb8f","span_id":"abac9471d0c27359"},"session_info":"connectionId 112844|10.10.4.241:42674|{account tpcc_test:admin:accountadmin -- 3000002:2:2}|goRoutineId 29408254|018ef4e3-9e88-72ad-89af-c20cb9738716","session_id":"018ef4e3-9e88-72ad-89af-c20cb9738716","statement_id":"018ef4e3-b3a8-7a71-947f-e4ef8efc93f1","txn_id":"018ef4e3b40472c48b7e69f15081f5b4/Active/S:1713505538373340240-1"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2662fdb]

goroutine 29409714 [running]:
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).RowCount(0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:161 +0x1b
github.com/matrixorigin/matrixone/pkg/sql/plan.getPkValueExpr(0xc3c8fd86e0, {0x5c3e208, 0xc340ae3200}, 0xc21801d980, 0xc53436cc90)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build_insert.go:302 +0x546
github.com/matrixorigin/matrixone/pkg/sql/plan.buildInsert(0xc221002fc0, {0x5c3e208, 0xc340ae3200}, 0x0, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build_insert.go:91 +0xb67
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x5c3e208, 0xc340ae3200}, {0x5bf5118, 0xc221002fc0}, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build.go:84 +0x6e5
github.com/matrixorigin/matrixone/pkg/sql/plan.getPreparePlan({0x5c3e208, 0xc340ae3200}, {0x5bf5118, 0xc221002fc0})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build_dcl.go:29 +0x185
github.com/matrixorigin/matrixone/pkg/sql/plan.buildPrepare({0x5bf53b8, 0xc326f704c0}, {0x5c3e208, 0xc340ae3200})
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build_dcl.go:65 +0x172
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x5c3e208, 0xc340ae3200}, {0x5bf53f0, 0xc326f704c0}, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build.go:178 +0x43fc
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan({0x5bf2ad0, 0xc5b01ce780}, 0xc1fb0b0400, {0x5c3e208, 0xc340ae3200}, {0x5bf53f0, 0xc326f704c0})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:1985 +0xf25
github.com/matrixorigin/matrixone/pkg/frontend.doPrepareStmt({0x5bf2ad0, 0xc5b01ce780}, 0xc1fb0b0400, 0xc326f704c0, {0xc1841e05b0, 0xcd}, {0xc454db0450, 0x12, 0x18})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:1267 +0xe5
github.com/matrixorigin/matrixone/pkg/frontend.(*prepareStmtMigration).Migrate(0xc326f70080, 0xc1fb0b0400)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2548 +0x665
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).Migrate(0xc1fb0b0400, 0xc1f7ca6930)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2566 +0x1c9
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:395 +0x48
sync.(*Once).doSlow(0xc1e22f3a60, 0xc2b43807e8)
	/usr/local/go/src/sync/once.go:74 +0x138
sync.(*Once).Do(0xc1e22f3a60, 0xc2b43807e8)
	/usr/local/go/src/sync/once.go:65 +0x45
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo(0xc1e22f39e0, 0xc1f7ca6930)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:393 +0x90
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).MigrateConnectionTo(0xc0002f29a0, 0xc1f7ca6930)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:625 +0x74
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleMigrateConnTo(0xc001700240, {0x5bf2ad0, 0xc530689aa0}, 0xc1d1d23a00, 0xc17d05fdc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:351 +0xb6
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x5bcba40, {0x5bf2ad0, 0xc530689aa0}, 0xc1d1d23a00, 0xc17d05fdc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:65 +0x83
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:180 +0x3c5
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage(0x5c406a0, {0x5bf2ad0, 0xc530689aa0}, {{0x5bf2ad0, 0xc530689aa0}, 0xc528596b10, {0x5c0c4e8, 0xc1d1d23a00}, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:189 +0x7fb
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0002efce0, {0x5c24840, 0xc1f91e0200}, {0x5308300, 0xc40e7019f0}, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:261 +0x1545
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0002efd90, {0x5c24840, 0xc1f91e0200})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:393 +0x748
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0xf8
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x705

mo log:
https://shanghai-idc.1matrix.org:30088/explore?panes=%7B%22fvR%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-5c0ae1c-20240418%5C%22%7D%20%7C%3D%20%60invalid%20memory%20address%20or%20nil%20pointer%20dereference%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713505429967%22,%22to%22:%221713505745194%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run 2 tpch 10G loop test processes in one independant tenant
3. run 2 tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run 2 sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another 2 sysbench mixed cases(insert/delete/update/select) longrunnig test processes with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
从日志上分析，应该跟 https://github.com/matrixorigin/MO-Cloud/issues/3052 一样的root cause：
在迁移时，如果超时，没有判断error，仍然做了迁移，导致迁移之后运行execute失败，之前prepare的迁移动作跟execute发生冲突，导致process变量有race，导致了空指针的panic。

已经通过pr https://github.com/matrixorigin/matrixone/pull/15625 修复。

**Comment by heni02** [comment]
main 分支也出现该错误
commit：d15494ea8
<img width="1379" alt="企业微信截图_9f1b55fd-a9b0-418c-98d9-2121370bf4a4" src="https://github.com/matrixorigin/matrixone/assets/113406637/293e9112-eb51-47c1-b572-739aa912ee5f">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22ZQu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240422%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713834333636%22,%22to%22:%221713834334636%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by heni02** [comment]
和 @volgariver6 沟通，目前main还没有合入，等待彭正pr合入

**Comment by aressu1985** [comment]
fixed
