### ISSUE TITLE
[Bug]: deadlock detected in tpcc 10 test

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#15624]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

50e4c4a66b79aea4ae15b1fd5f2a6f1bee4c8c8e

### Other Environment Information

```Markdown
- Hardware parameters: tke分布式环境
- OS type:
- Others:
```

### Actual Behavior

2024-04-19 08:34:43 FATAL jTPCCTerminal:327 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20701, ErrorMessage : deadlock detected

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/8750080159/job/24014445117
```

**Comment by guguducken** [comment]
@zhangxu19830126 please take a look

**Comment by heni02** [comment]
回归测试问题，已经解决
