### ISSUE TITLE
[Bug]:  mo hung during tpcc test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15635]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

87ea4a4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8768387040/job/24066478341

mo hung

goroutine-branch-reg-87ea4a4.tar.gz

<img width="1425" alt="企业微信截图_0ab50cd8-ffea-41f0-9299-906801f9fea6" src="https://github.com/matrixorigin/matrixone/assets/77312370/8d748860-b1c0-4092-a4c3-9ec4da251a20">

### Steps to Reproduce

```Markdown
run successfully
```

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8794462635/job/24133930307

正在跑daily测试, 目前没有跑出问题

**Comment by jensenojs** [comment]
等pr合并

**Comment by jensenojs** [comment]
准备重新测试稳定性

**Comment by jensenojs** [comment]
等daily稳定性验证

**Comment by sukki37** [comment]
closed for related prs have been reverted
