### ISSUE TITLE
[Bug]: cn painc by worker exits from panic: BUG: invalid ref count, -0xc08d299e00(-2) during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15636]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

228823d

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

One cn was crashed about 16 hours  during stability test on distributed mode, the error message is :
2024/04/21 06:11:04.293253 [ants]: worker exits from panic: BUG: invalid ref count, -0xc08d299e00(-2)
goroutine 17243230 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x7a
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0xcc
panic({0x4e8f040, 0xc543de6920})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).close(0xc08d299e00)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter.go:119 +0xae
github.com/matrixorigin/matrixone/pkg/lockservice.(*sliceBasedWaiterQueue).notify(0xc1d9d278f0, {{0x0, 0x0}, {0x17c836bc64946f3d, 0x0, 0x0, {}, {0x0, 0x0, 00
x0}, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter_queue.go:126 +0x325
github.com/matrixorigin/matrixone/pkg/lockservice.Lock.closeTxn({{0xc1814957b3d36785, 0x353c49180eb8, 0x76cf000}, 0x9, 0xc7a5dfde78, {0x5c295b8, 0xc1d9d278ff
0}}, 0xc14ce81200, {{0x0, 0x0}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock.go:174 +0x1a3
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock.func2({0xc1ef974b60, 0xa, 0xa})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:258 +0xd2c
github.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlice).iter(0xc4091aef60, 0xc0717b1dd8)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/slice.go:159 +0x93
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).unlock(0xc005163790, 0xc14ce81200, 0xc25d0546c0, {0x0, 0x0, 0x0, {}, {0x0, 0x0, 0x0}, ...
.})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_local.go:229 +0x63f
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).close.func1.1()
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/txn.go:152 +0xe5
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xf8
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x85

panic: BUG: invalid ref count, -0xc08d299e00(-3)

goroutine 816 [running]:
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiter).close(0xc08d299e00)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter.go:119 +0xae
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiterEvents).check(0xc001533400, 0x12a05f200)
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter_events.go:193 +0x1df
github.com/matrixorigin/matrixone/pkg/lockservice.(*waiterEvents).handle(0xc001533400, {0x5bf58d0, 0xc003afb320})
        /go/src/github.com/matrixorigin/matrixone/pkg/lockservice/waiter_events.go:175 +0x21b
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0xd3

mo-log:
[cn_panic.log](https://github.com/matrixorigin/matrixone/files/15051075/cn_panic.log)

https://shanghai-idc.1matrix.org:30088/explore?panes=%7B%22yS0%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-228823d-20240420%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713678976329%22,%22to%22:%221713686494562%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by zhangxu19830126** [comment]
it's lockservice's bug.

**Comment by zhangxu19830126** [comment]
fixed

**Comment by zhangxu19830126** [comment]
@jensenojs you need to take look for hung

**Comment by jensenojs** [comment]
hung住的问题已经定位到原因, 正在进行完整的验证

https://github.com/matrixorigin/matrixone/issues/15635#issuecomment-2068832309

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8794462635/job/24133930307

正在跑daily测试, 目前没有跑出问题

**Comment by jensenojs** [comment]
等daily稳定性验证

**Comment by jensenojs** [comment]
daily正在跑, 目前看还行
- https://github.com/matrixorigin/matrixone/pull/15763

**Comment by jensenojs** [comment]
相关pr已经合并, 请QA一并验证. @aressu1985

**Comment by aressu1985** [comment]
fixed
