### ISSUE TITLE
[Bug]: lots of tpcc queries timeout in 60 senconds during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15637]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

228823d

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, there were lots of  tpcc queries timeout in 60 senconds:

<img width="1431" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3e1ba97d-1365-41f0-b3de-0fbecc492961">

工具log：
[tpcc.tar.gz](https://github.com/matrixorigin/matrixone/files/15051104/tpcc.tar.gz)

and there were lots long running errors in mo logs:
<img width="1283" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/c4b94e57-2591-4172-91e4-729640a79f9f">

https://shanghai-idc.1matrix.org:30088/explore?panes=%7B%22yS0%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-228823d-20240420%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713675217212%22,%22to%22:%221713690253678%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by sukki37** [comment]
maybe dup with https://github.com/matrixorigin/matrixone/issues/15635

**Comment by jensenojs** [comment]
等pr合并

**Comment by jensenojs** [comment]
等daily稳定性验证

**Comment by jensenojs** [comment]
daily正在跑, 目前看还行
- https://github.com/matrixorigin/matrixone/pull/15763

**Comment by jensenojs** [comment]
<img width="1822" alt="企业微信截图_393397f9-f91b-414c-8edc-9fcf70aee852" src="https://github.com/matrixorigin/matrixone/assets/56761542/7e2dd4ba-692f-4f98-9240-bfa99bdc1e7c">

daily的测试结果如上所示, 后面失败的是魏璐手动把测试给停了

**Comment by aressu1985** [comment]
fixed
