### ISSUE TITLE
[Bug]:  inconsistent mysql behavior for date() function

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#15647]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1.3

### Commit ID

1.1.3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO behavior:

create table t1(a date, b datetime);
insert into t1 values('2022-01-01','2022-01-01 01:01:01');
insert into t1 values('2022-01-01','2022-01-01 01:01:01');
insert into t1 values('20220101','2022-01-01 01:01:01');
insert into t1 values('2022-01-02','2022-01-02 23:01:01');
insert into t1 values('2021-12-31','2021-12-30 23:59:59');
insert into t1 values('2022-06-30','2021-12-30 23:59:59');

Q1: select date(a),date(b) from t1; //ok
Q2: select date(a,'%Y%m%d') from t1; //execute the same as Q1
Q3: select date(a,'%Y-%m-%d') from t1; //execute the same as Q1

### Expected Behavior

In MySQL:

create table t1(a date, b datetime);
insert into t1 values('2022-01-01','2022-01-01 01:01:01');
insert into t1 values('2022-01-01','2022-01-01 01:01:01');
insert into t1 values('20220101','2022-01-01 01:01:01');
insert into t1 values('2022-01-02','2022-01-02 23:01:01');
insert into t1 values('2021-12-31','2021-12-30 23:59:59');
insert into t1 values('2022-06-30','2021-12-30 23:59:59');

Q1: select date(a),date(b) from t1; //ok
Q2: select date(a,'%Y%m%d') from t1; //syntax error
Q3: select date(a,'%Y-%m-%d') from t1; //syntax error

### Steps to Reproduce

```Markdown
Looking above
```

**Comment by aunjgr** [comment]
It's already fixed by #15662

**Comment by aressu1985** [comment]
fixed: 275af9cc9a4d113bd5ddcb5381eb9a9d15e0dd87

mysql> create table t1(a date, b datetime);
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t1 values('2022-01-01','2022-01-01 01:01:01');
Query OK, 1 row affected (0.02 sec)

mysql> insert into t1 values('2022-01-01','2022-01-01 01:01:01');
Query OK, 1 row affected (0.04 sec)

mysql> insert into t1 values('20220101','2022-01-01 01:01:01');
Query OK, 1 row affected (0.02 sec)

mysql> insert into t1 values('2022-01-02','2022-01-02 23:01:01');
Query OK, 1 row affected (0.03 sec)

mysql> insert into t1 values('2021-12-31','2021-12-30 23:59:59');
Query OK, 1 row affected (0.04 sec)

mysql> insert into t1 values('2022-06-30','2021-12-30 23:59:59');
Query OK, 1 row affected (0.02 sec)

mysql> select date(a),date(b) from t1; 
+------------+------------+
| date(a)    | date(b)    |
+------------+------------+
| 2022-01-01 | 2022-01-01 |
| 2022-01-01 | 2022-01-01 |
| 2022-01-01 | 2022-01-01 |
| 2022-01-02 | 2022-01-02 |
| 2021-12-31 | 2021-12-30 |
| 2022-06-30 | 2021-12-30 |
+------------+------------+
6 rows in set (0.01 sec)

mysql> select date(a,'%Y%m%d') from t1;
ERROR 20203 (HY000): invalid argument function date, bad value [DATE VARCHAR]
mysql> select date(a,'%Y-%m-%d') from t1; 
ERROR 20203 (HY000): invalid argument function date, bad value [DATE VARCHAR]
