### ISSUE TITLE
[Bug]: ut failed. TestGlobalCheckpoint5 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#15640]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0418-fix-local-local

### Commit ID

a374a2d7cc5e8f99289fe544982bdecfef4ef191

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

https://github.com/matrixorigin/matrixone/actions/runs/8772663557/job/24071871167?pr=15609
```

### Actual Behavior

![Screenshot from 2024-04-22 10-14-00](https://github.com/matrixorigin/matrixone/assets/60595215/63ae606f-7b93-4c4f-8d27-7c14c65f0dba)

### Expected Behavior

success

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/8772663557/job/24071871167?pr=15609
```

**Comment by jiangxinmeng1** [comment]
<img width="580" alt="image" src="https://github.com/matrixorigin/matrixone/assets/51114574/8e343dd7-28e6-42cd-a42c-f1a34a1bf5a7">
和#15684是一个问题，https://github.com/matrixorigin/matrixone/pull/15686就好

**Comment by jiangxinmeng1** [comment]
fixed by #15686

**Comment by aressu1985** [comment]
@daviszhen this is about ut test，please check this

**Comment by daviszhen** [comment]
it was fixed.
