### ISSUE TITLE
[Bug]: select interval 1 day reported panic type mismatch: []types.Varlena BIGINT

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15648]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

652cc255d9075ad1cf683f88bcd66d132fe98dcc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select interval 1 day;
ERROR 20101 (HY000): internal error: panic type mismatch: []types.Varlena BIGINT:
github.com/matrixorigin/matrixone/pkg/container/vector.ToSlice[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/vector.go:82
github.com/matrixorigin/matrixone/pkg/container/vector.ToFixedCol[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/tools.go:33
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
	/Users/heni/test-envir/matrixone/pkg/container/vector/tools.go:42

now mo not supported interval type ,but expected reported not supported error

### Steps to Reproduce

```Markdown
select interval 1 day;
```

**Comment by aunjgr** [comment]
我们没有真正的interval类型。现在的只是当初为了跑通tpch做的一个假的。

MO的interval只能出现在date/datetime + interval这样的表达式里，不能单独出现。

**Comment by heni02** [comment]
现在不支持interval，报错信息改成不支持信息比较友好 @aunjgr

**Comment by aunjgr** [comment]
not working on it today

**Comment by heni02** [comment]
confirm，closed
commit：892e8ef9b3e7a1198461309a1543e3784d8b1797
mysql>  select interval 1 day;
ERROR 20101 (HY000): internal error: not supported type INTERVAL
