### ISSUE TITLE
[Bug]: leak txn cause mo hung during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15656]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

6db61b7

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed mode, mo suddenly was hung because of lots of txn queued:
<img width="1342" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/fb7e0c7c-b96d-4c97-a02b-d108f3109120">

link:
https://shanghai.idc.matrixorigin.cn:30001/d/fbe569fd-c3ea-4e44-9295-0a5b789fc3d8/txn-metrics?orgId=1&refresh=30s&from=now-12h&to=now&var-interval=1m&var-namespace=mo-nightly-6db61b7-20240421&var-pod=All

after searching log, there was a leak txn found:
<img width="1317" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e2c43c47-22cc-49af-abc3-108d1f4abf26">
link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Ql-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-6db61b7-20240421%5C%22%7D%20%7C%3D%20%60leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

And this was a tpcc txn, if not commited or rollback, it will block all the following tpcc txn and made active txn beiing full, then block all other txns including txn related to login and cuased mo hung.

So the problems are that:
1. one tpcc queries were timeout, the tpcc tools would close the conneciton, but why the txn was not rollback after connection closed.
2. one txn which was not commited or rollback caused the whole database hung , Is it reasonable？

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by daviszhen** [comment]
现在是goroutine文件拿不到了。有另外一个方法可以尝试，定位卡住的位置。明天改代码。

**Comment by daviszhen** [comment]
在加调试代码。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入，目前是群里在解决hung住的问题。还未到leak的环节。

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by aressu1985** [comment]
已经很久没有复现过，先关闭
