### ISSUE TITLE
[Bug]: run tpch 100g on 129, report out of memory

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#15666]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2024/04/23 13:51:28.146649 +0800","caller":"mpool/mpool.go:84","msg":"MPool pipeline-018f0982-373d-7b4b-9939-5808ef5bcc08 new high watermark\n     allocations : 118963\n     frees : 110714\n     alloc bytes : 5284809892\n     free bytes : 4210809400\n     current bytes : 1074000492\n     high water mark : 1074000492\n"}
fatal error: out of memory

### Steps to Reproduce

```Markdown
run tpch 100g on 129, report out of memory
```

### Additional information

[129.log](https://github.com/matrixorigin/matrixone/files/15071987/129.log)

**Comment by volgariver6** [comment]
二分之后再分配issue

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/15180
与这个issue相同
