### ISSUE TITLE
[Bug]: load data local infile hung.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15661]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

c3a0c3e10b2dd7e604bc649e936e231c549ffd0d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="747" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0d7baa70-ac70-4042-9135-a084fb87fdfb">

### Expected Behavior

load 成功

### Steps to Reproduce

```Markdown
mysql -h 127.0.0.1 -P 6001 -udump -p111 --local-infile

create database test;
use test;
create table table01(col1 int, col2 decimal);
load data local infile 'ariznawl/test.csv' into table table01 fields terminated by '\n';
```

**Comment by ouyuanning** [comment]
锦赛看看是不是表锁那个PR的问题

**Comment by jensenojs** [comment]
<img width="1533" alt="企业微信截图_26d27c70-7502-4ab0-8f9c-4d6cdb90f9f5" src="https://github.com/matrixorigin/matrixone/assets/56761542/5b09c901-499e-4ed9-89d3-249d6e8e3c4c">

反映问题的commit之后的一个commit修复了该问题. 

<img width="1533" alt="企业微信截图_73f83166-fde2-47a5-bf0f-07062d3cce7d" src="https://github.com/matrixorigin/matrixone/assets/56761542/c09eaad5-52fc-449a-b962-f05fdb0f6a1d">

可以考虑把测试固定在bvt中, 如果预期行为是检测出文件不存在的话, 可以考虑
```sql
load data local infile 'ariznawl/test.csv' into table table01 fields terminated by '\t' enclosed by '"' lines terminated by '\n';
```

**Comment by Ariznawlll** [comment]
if file not exists:
<img width="749" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/35801ba9-8e25-40db-aea0-c0e62b64a1bf">

verified.
