### ISSUE TITLE
[Bug]: mo hung during stability test on distributed mod

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15672]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d15494ea8bf08b9ae40004008f4595bdb5fb3a92

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed mode, mo suddenly was hung :
<img width="745" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/c9d8a6d9-8f38-47f9-bcf9-58b6c3ed5885">

and there were lots of active txn:
<img width="1350" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/9cb71884-a8a0-45bb-8252-b479e56bef82">

link:
https://shanghai.idc.matrixorigin.cn:30001/d/fbe569fd-c3ea-4e44-9295-0a5b789fc3d8/txn-metrics?orgId=1&from=1713839008000&to=1713853506000

and there were lots of long running error in mo-log:
<img width="1342" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/fa928dc8-cb57-4e6b-af68-8825c98650b7">

profile of 3 cns:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/15072671/profile.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by aronchanisme** [comment]
那辛苦赛赛先帮忙看看是否 #15664 的问题

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8794462635/job/24133930307

正在跑daily测试, 目前没有跑出问题

**Comment by jensenojs** [comment]
等pr合并

**Comment by aressu1985** [comment]
update on 4.24
commit: 808ec62

1. lots of longrunning error:
link: https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22sL1%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-808ec62-20240423%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221713924132174%22,%22to%22:%221713953318599%22%7D%7D%7D&schemaVersion=1&orgId=1
2. goroutine:
[main-routine_018f0de4-7217-7a24-b35b-5180ae57f191.txt](https://github.com/matrixorigin/matrixone/files/15092425/main-routine_018f0de4-7217-7a24-b35b-5180ae57f191.txt)

**Comment by zhangxu19830126** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22hN2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-c1bf38b-20240424%5C%22%7D%20%7C%3D%20%60found%20long%20running%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
又跑出来了，但是看这个事务全部卡在了执行，他的锁就不会释放，所以其他事务就被阻塞了。
<img width="1385" alt="企业微信截图_9096707f-0c20-4742-a907-ed98ae8ed8a9" src="https://github.com/matrixorigin/matrixone/assets/2995754/153229aa-fb1e-4874-86e7-98bce5c0f487">

**Comment by zhangxu19830126** [comment]
<img width="999" alt="image" src="https://github.com/matrixorigin/matrixone/assets/2995754/40f97e4b-9b01-4cca-96be-49a508a54bd3">
这个shi事务相关的goroutine，全部卡在了执行

**Comment by zhangxu19830126** [comment]
@m-schen 和1.1的那个问题应该是同一个

**Comment by zhangxu19830126** [comment]
dup with #15538

**Comment by m-schen** [comment]
还没有具体的结论

**Comment by m-schen** [comment]
旭哥好像解决了这个问题 不过相应的分支还在测试中

**Comment by m-schen** [comment]
同上一个评论，相关分支是 https://github.com/zhangxu19830126/matrixone/tree/debug_main_hung

**Comment by m-schen** [comment]
同上一个评论

**Comment by m-schen** [comment]
与qa确认，目前long running的bug已经被修复。

原因是网络连接断开，txn被abort，间接导致的远程放锁请求被先于远程上锁请求处理。因此该表的锁永远不会被释放导致的。

相关修复pr为：
https://github.com/matrixorigin/matrixone/pull/15784

**Comment by aressu1985** [comment]
fixed
