### ISSUE TITLE
[Bug]: TestReplayDeletes panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#15676]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1466" alt="image" src="https://github.com/matrixorigin/matrixone/assets/2995754/c0ed289a-2a70-4d63-a843-7d99cbb496bf">

### Steps to Reproduce

```Markdown
ci
```

**Comment by jiangxinmeng1** [comment]
fixed by #15676

**Comment by daviszhen** [comment]
it was fixed.

**Comment by daviszhen** [comment]
@zhangxu19830126 这个问题解决了。我关不掉。
