### ISSUE TITLE
[Bug]: ut failed. TestAll

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#15684]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0423-debug-leak

### Commit ID

338d65b8c28a4254ee30d6579e9e99102b44ac69

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/8810011549/job/24181721623?pr=15677
```

### Actual Behavior

![Screenshot from 2024-04-24 11-26-42](https://github.com/matrixorigin/matrixone/assets/60595215/00e6d8f2-6296-4a46-9dfb-8b70c1185b20)

### Expected Behavior

success

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/8810011549/job/24181721623?pr=15677
```

**Comment by sukki37** [comment]
dup with #13012
