### ISSUE TITLE
[Bug]: bvt case failed, the row count of result is not equal with expected

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#15694]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

808ec623826

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8811990664/job/24186875860?pr=15664

<img width="1722" alt="Pasted Graphic 2" src="https://github.com/matrixorigin/matrixone/assets/56761542/88ddc8ab-f36e-4e97-bfe6-fbe41352f4c6">

### Steps to Reproduce

```Markdown
Matrixone Standlone CI / e2e BVT Test on Linux/x64(LAUNCH,Optimistic)
```

**Comment by jensenojs** [comment]
similar problem

<img width="1722" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/7a328db9-c0a4-432d-8a79-6c4cdf0f0ca1">

https://github.com/matrixorigin/matrixone/actions/runs/8813266629/job/24190676006?pr=15664

**Comment by xzxiong** [comment]
ref https://github.com/matrixorigin/matrixone/issues/14836
