### ISSUE TITLE
[Bug]: bvt fail in log/query_version.sql

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#15705]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1673" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/24d925cb-b429-4737-b3f9-68ccc1869da1">

https://github.com/matrixorigin/matrixone/actions/runs/8813266629/job/24193229010?pr=15664

### Steps to Reproduce

```Markdown
Matrixone Standlone CI / e2e BVT Test on Linux/x64(LAUNCH,Optimistic)
```

**Comment by xzxiong** [comment]
dup as https://github.com/matrixorigin/matrixone/issues/14836
