### ISSUE TITLE
[Feature Request]:  rename table t1 to t2

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#15712]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

We already support renaming table with "alter table":

ALTER TABLE old_table_name
RENAME TO new_table_name;

But some tools prefer using rename statements, which does the same thing. 

rename table old_table_name to new_table_name;

Like in Navicat, the table renaming is implemented with rename statement, which won't work in MO.

<img width="713" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/58bd98f8-f74b-4295-adde-4f71187f71cc">

### Describe implementation you've considered

We should just support this syntax :

rename table old_table_name to new_table_name; 

and make it equivalent to 

ALTER TABLE old_table_name
RENAME TO new_table_name;

**Comment by daviszhen** [comment]
语法糖。支持 RENAME新语法。改表名的功能是支持的。

**Comment by YANGGMM** [comment]
finished, plz test @aressu1985

**Comment by heni02** [comment]
test done
