### ISSUE TITLE
[Bug]: tpcc 100warehouses 1000terminals test Consistency verification failed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15715]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cd1ac40d49c85bd483c4a9f18c052d5d75c6011e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

使用分支https://github.com/jensenojs/matrixone/commits/revert/ commit id：7545e341de19ff3b4a47627b827a3b9fe5b747b0
跑出来tpcc数据一致性问题
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8826261589/job/24231969116
<img width="1134" alt="企业微信截图_997063ce-18ae-403d-942a-064461d72b03" src="https://github.com/matrixorigin/matrixone/assets/113406637/4e09a49c-0f16-4599-bbd4-5ad31b122aa9">
tpcc 500和1000 warehouses 也出现同样的问题

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22BkN%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22branch-search-20240425%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714021300134%22,%22to%22:%221714021339199%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tpcc 100warehouses 1000terminals test
```

**Comment by LeftHandCold** [comment]
还未复现

**Comment by LeftHandCold** [comment]
还未复现

**Comment by LeftHandCold** [comment]
还未复现

**Comment by LeftHandCold** [comment]
还未复现

**Comment by LeftHandCold** [comment]
长时间跑tpcc，期间执行几次select mo_ctl('dn','checkpoint','');然后重启mo就可以复现

**Comment by LeftHandCold** [comment]
fix

**Comment by tianyahui-python** [comment]
tpcc 还存在数据不一致问题：https://github.com/matrixone-cloud/mocloud-tester/actions/runs/9039039729/job/24841241518

**Comment by LeftHandCold** [comment]
> tpcc 还存在数据不一致问题：https://github.com/matrixone-cloud/mocloud-tester/actions/runs/9039039729/job/24841241518
> 
> 验证commi id：b5c2eaaf9

需要drop之前的table再从新load跑

**Comment by heni02** [comment]
回归再未出现，closed
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9081256748/job/24984296198
main f8cc1518b
