### ISSUE TITLE
[Bug]: BVT failed because of no available raft group. Cannot create table in way of both manual and BVT on every node

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1572]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0d21f861b2de31953b4222f92b23ddb2bd583e58
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run BVT:
./mysql-tester

Then some cases can be passed. But failed after some cases.

INFO[0003] run test [functions] ok                      
INFO[0003] create default database [insert] for testing 
Non Query: drop table if exists names;
Non Query: create table names(id int PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255) UNIQUE,age int);
Non Query: insert into names(name, age) values("Abby", 24);
Non Query: insert into names(name, age) values("Bob", 25);
Non Query: insert into names(name, age) values("Carol", 23);
Non Query: insert into names(name, age) values("Dora", 29);
Query:	 select id,name,age from names;
Non Query: drop table if exists weights;
Non Query: create table weights(a int unique);
Non Query: insert into weights values(1);
Query:	 select * from weights;
Non Query: drop table if exists test;
Non Query: create table test(id int primary key, name varchar(10), age int);
=== RUN operator:
FATA[0005] run test [insert] err: sql:create table test(id int primary key, name varchar(10), age int);: run "create table test(id int primary key, name varchar(10), age int);" at line 12 err Error 1105: unknown error:no available raft group 

mysql> create table t1(a int);
ERROR 1105 (HY000): unknown error:no available raft group

**Comment by domingozhang** [comment]
Drop matrixone/store and re-run. Still happend.

**Comment by zhangxu19830126** [comment]
some node did not join the cluster correctly
