### ISSUE TITLE
[Bug]: proxy panic by sync: negative WaitGroup counter during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15730]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c1bf38b

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed mode, sometimes proxy may craashed by:
{"level":"INFO","time":"2024/04/25 10:48:22.495036 +0000","name":"proxy-service","caller":"proxy/tunnel.go:292","msg":"set tunnel transfer intent","uuid":"35326365-6538-6138-6561-333262383933","conn ID":1008,"value":false}
{"level":"INFO","time":"2024/04/25 10:48:22.495079 +0000","name":"proxy-service","caller":"proxy/tunnel.go:315","msg":"transfer end","uuid":"35326365-6538-6138-6561-333262383933","conn ID":1008}
panic: sync: negative WaitGroup counter

goroutine 2178 [running]:
sync.(*WaitGroup).Add(0xc0028072e0, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:62 +0x16c
sync.(*WaitGroup).Done(0xc0028072e0)
	/usr/local/go/src/sync/waitgroup.go:87 +0x1f
github.com/matrixorigin/matrixone/pkg/proxy.(*pipe).handleTransferIntent(0xc002807300, {0x6d7a110, 0xc005e9d180}, 0xc0028072e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/proxy/tunnel.go:585 +0x99
github.com/matrixorigin/matrixone/pkg/proxy.(*pipe).kickoff(0xc002807300, {0x6d7a110, 0xc005e9d180}, 0xc002807280)
	/go/src/github.com/matrixorigin/matrixone/pkg/proxy/tunnel.go:556 +0x49a
github.com/matrixorigin/matrixone/pkg/proxy.(*tunnel).kickoff.func2()
	/go/src/github.com/matrixorigin/matrixone/pkg/proxy/tunnel.go:215 +0x54
created by github.com/matrixorigin/matrixone/pkg/proxy.(*tunnel).kickoff in goroutine 2153
	/go/src/github.com/matrixorigin/matrixone/pkg/proxy/tunnel.go:214 +0x1e7

mo-log:
[proxy_panic.tar.gz](https://github.com/matrixorigin/matrixone/files/15111289/proxy_panic.tar.gz)

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22hN2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-c1bf38b-20240424%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714041358891%22,%22to%22:%221714042518165%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/15682

**Comment by aressu1985** [comment]
fixed
