### ISSUE TITLE
[Tech Request]: rewrite particular DATE_FORMAT expressions to BETWEEN

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#15736]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

DATE_FORMAT(dt, '%Y%m%d') = '20240426' ==> dt BETWEEN '2024-04-26 00:00:00' AND '2024-04-26 00:00:00' + 1 day - 1 microsec
DATE_FORMAT(dt, '%Y') = '2024' ==> dt BETWEEN '2024-01-01 00:00:00' AND '2024-01-01 00:00:00' + 1 year - 1 microsec
etc.

Ideally, this rule should finally be able to handle any prefix of '%Y%m%d%H%i%s', in any permutation, with optional infixes like the commonly used "-" and ":".

### Why is this needed ?

DATE_FORMAT in its nature is not efficient to calculate, and can't leverage zonemap and index.

**Comment by aressu1985** [comment]
fixed: 275af9cc9a4d113bd5ddcb5381eb9a9d15e0dd87

mysql> explain select * from t1 where date_format(c2,'%Y-%m-%d')='2024-04-01';
+--------------------------------------------------------------------------------+
| QUERY PLAN                                                                     |
+--------------------------------------------------------------------------------+
| Project                                                                        |
|   ->  Table Scan on d1.t1                                                      |
|         Filter Cond: t1.c2 BETWEEN 2024-04-01 00:00:00 AND 2024-04-01 23:59:59 |
+--------------------------------------------------------------------------------+
3 rows in set (0.02 sec)

mysql> explain select * from t1 where date_format(c2,'%Y:%m:%d')='2024:04:01';
+----------------------------------------------------------------------+
| QUERY PLAN                                                           |
+----------------------------------------------------------------------+
| Project                                                              |
|   ->  Table Scan on d1.t1                                            |
|         Filter Cond: (date_format(t1.c2, '%Y:%m:%d') = '2024:04:01') |
+----------------------------------------------------------------------+
