### ISSUE TITLE
[Bug]: will still meet "panic too large fixed slice ..." in a corner case

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#15739]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main( after fix moc3006)

### Commit ID

c0f506fb2458fa0bf96f15269228eb2b48a2f979

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

之前的讨论确认 https://github.com/matrixorigin/MO-Cloud/issues/3006#issuecomment-2056206620, 由统计信息确认单个sql引入的行级锁数量超过某个数量之后(暂定一千万), 将行锁升级为表锁. 

但是对于如下的SQL而言, 比如说通过`source`的方式用`insert values`的方式导入数据, 之前是由于一些历史遗留的问题吧会建议把所有的`insert values`包裹在一个事务里面

```
begin;
many many insert into values ....
commit;
```

之前的解决方案是解决不了这个问题的, 因为单个`insert values`的插入数据都控制在`8192`行, 它是累积起来之后才超过内上限的, 对于每个`insert values`根据统计信息都判定不需要升级表锁.

<img width="1293" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/c692b3b2-af8c-41e3-9958-898c2a7d6feb">

### Steps to Reproduce

```Markdown
begin;
many many insert into values ....
commit;


e.g.

CREATE TABLE sensor_data ( id INT NOT NULL AUTO_INCREMENT, device_id VARCHAR(255) NOT NULL, timestamp TIMESTAMP NOT NULL, value FLOAT NOT NULL, PRIMARY KEY (id) );


load sql plz contact me
```

**Comment by zhangxu19830126** [comment]
无法在lockservice内部处理这个case。

**Comment by ouyuanning** [comment]
暂定结论
1、当stats预估有1024行的时候。就转表锁。（可以等当前PR的测试通过后先合并，再测试这种方案的可行性）@jensenojs

2、当前依然无法避免类似这种
```
begin;
insert into t1 values (1); --一次很少的行
...
...  -- 但是事务内insert了很多很多次，总有点锁爆掉的时候
```
这个部分另外再在架构组会上讨论  @zhangxu19830126

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
暂无进展

**Comment by aressu1985** [comment]
和赛赛沟通过，该issue暂时不好解决，放到1.3.0版本
