### ISSUE TITLE
[Bug]: 同一租户下对相同发布订阅两次，show subscriptions;只展示最后一个订阅

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#15741]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c3a0c3e10b2dd7e604bc649e936e231c549ffd0d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

同一租户下对相同发布订阅两次，show subscriptions;只展示最后一个订阅;

### Expected Behavior

展示两条订阅

### Steps to Reproduce

```Markdown
如上所述
```

**Comment by daviszhen** [comment]
@ck89119

**Comment by ck89119** [comment]
included in https://github.com/matrixorigin/matrixone/issues/16188
