### ISSUE TITLE
[Tech Request]: LocalFS supports idempotent when deleting a large number of files

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#15751]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
LocalFS supports idempotent when deleting a large number of files
GC module will call this function to delete files. If it involves replay, GC will delete some files that have been deleted again. LocalFS Delete needs to support idempotent
```

**Comment by reusee** [comment]
done
