### ISSUE TITLE
[Bug]: background SQL generated by revokeOwnershipFromDatabaseFormat is wrong

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#15752]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1629" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ad1de3b8-9bff-45cb-9c07-c70488228fc6">

`form`should be `from`

### Expected Behavior

no parser error

### Steps to Reproduce

```Markdown
bvt run create_table_as_select.sql, and add a breakpoint on backExec.Exec after Parse
```

**Comment by jensenojs** [comment]
相关pr都已经合并, 这个后台SQL的执行在修复之前一直是失败的, 可能需要QA帮忙看看为什么之前一直没有发现. @aressu1985

**Comment by aressu1985** [comment]
fixed
