### ISSUE TITLE
[Tech Request]: Declare the definition of system tables as global variables in mo

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#15756]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
将mo中系统表和系统视图的定义声明为全局变量，只需在代码中定义一次，然后在需要的地方直接引用，避免了在多个地方重复定义，提高了代码的可维护性和可读性。
```

**Comment by daviszhen** [comment]
1.3 整理
