### ISSUE TITLE
[Bug]: [date 4.27] tke regression: sysbench 100w random_points reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15761]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2981727b0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8860565711/job/24339848135
<img width="1263" alt="企业微信截图_f47fa405-64dd-4d66-ae5d-feb70f0d5689" src="https://github.com/matrixorigin/matrixone/assets/113406637/dc18bec0-9149-42d8-b705-b539c834b544">

mo log：
<img width="1371" alt="企业微信截图_1d114b26-4db8-4929-a7d8-23be4396e05c" src="https://github.com/matrixorigin/matrixone/assets/113406637/c5035610-5c30-44c8-801c-e9dad4e6318c">
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22BkN%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240427%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714255472301%22,%22to%22:%221714255473301%22%7D%7D%7D&schemaVersion=1&orgId=1	
panic: runtime error: invalid memory address or nil pointer dereference
2024-04-27 22:04:33.290	
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x336a7f6]
2024-04-27 22:04:33.290	

2024-04-27 22:04:33.290	
goroutine 2427056 [running]:
2024-04-27 22:04:33.290	
panic({0x3ee1400?, 0x7653350?})
2024-04-27 22:04:33.290	
	/usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc03f3a7e50 sp=0xc03f3a7da0 pc=0x44162c
2024-04-27 22:04:33.290	
runtime.panicmem(...)
2024-04-27 22:04:33.290	
	/usr/local/go/src/runtime/panic.go:261
2024-04-27 22:04:33.290	
runtime.sigpanic()
2024-04-27 22:04:33.290	
	/usr/local/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc03f3a7eb0 sp=0xc03f3a7e50 pc=0x458b98
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).GetContext(0xc500932ae0?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/compiler_context.go:136 +0x16 fp=0xc03f3a7ec8 sp=0xc03f3a7eb0 pc=0x336a7f6
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).GetContext(...)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/query_builder.go:4002
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).createQuery(0xc500932ae0)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/query_builder.go:1446 +0x29b fp=0xc03f3a8450 sp=0xc03f3a7ec8 pc=0x2cfad7b
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder(0x503bee8?, {0x50ce5b0, 0xc47a516bd0}, 0xe?, 0x0?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build.go:42 +0x1b1 fp=0xc03f3a8530 sp=0xc03f3a8450 pc=0x2c353d1
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x50ce5b0, 0xc47a516bd0}, {0x505b970?, 0xc5009329c0?}, 0x0?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build.go:88 +0x171 fp=0xc03f3a8700 sp=0xc03f3a8530 pc=0x2c35b91
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize(0xc03f3a8798, {0x505b970?, 0xc5009329c0?}, 0xc0?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/optimize.go:56 +0x3c fp=0xc03f3a8760 sp=0xc03f3a8700 pc=0x2cd1cfc
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.getPreparePlan({0x50ce5b0?, 0xc47a516bd0?}, {0x505b970?, 0xc5009329c0?})
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build_dcl.go:43 +0x19f fp=0xc03f3a87d8 sp=0xc03f3a8760 pc=0x2c5603f
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.buildPrepare({0x5063a00?, 0xc431a9bc00?}, {0x50ce5b0, 0xc47a516bd0})
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build_dcl.go:65 +0xa7 fp=0xc03f3a88d8 sp=0xc03f3a87d8 pc=0x2c561c7
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x50ce5b0, 0xc47a516bd0}, {0x505c7c8?, 0xc431a9bc00?}, 0x80?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/build.go:188 +0x1b8e fp=0xc03f3a8aa8 sp=0xc03f3a88d8 pc=0x2c375ae
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan({0x503bfd8, 0xc4e1b81080}, {0x50ebe30?, 0xc2437c3000}, {0x50ce5b0, 0xc47a516bd0}, {0x505c7c8?, 0xc431a9bc00})
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2010 +0x8ce fp=0xc03f3a8c30 sp=0xc03f3a8aa8 pc=0x3391fce
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.doPrepareStmt({0x503bfd8?, 0xc4e1b81080?}, 0xc2437c3000, 0xc431a9bc00, {0xc011bc8510, 0x83}, {0xc54c63ebb8, 0x14, 0x18})
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:1185 +0x87 fp=0xc03f3a8ca8 sp=0xc03f3a8c30 pc=0x338c7c7
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.(*prepareStmtMigration).Migrate(0xc03f3a8dc0, 0xc2437c3000)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1977 +0x1ec fp=0xc03f3a8d30 sp=0xc03f3a8ca8 pc=0x33d6f2c
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).Migrate(0xc2437c3000, 0xc1e8e68dc0)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2007 +0x306 fp=0xc03f3a8e50 sp=0xc03f3a8d30 pc=0x33d72e6
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo.func1()
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:429 +0x33 fp=0xc03f3a8e80 sp=0xc03f3a8e50 pc=0x33be6f3
2024-04-27 22:04:33.290	
sync.(*Once).doSlow(0x3e8e4c0?, 0xc0126ab0b0?)
2024-04-27 22:04:33.290	
	/usr/local/go/src/sync/once.go:74 +0xbf fp=0xc03f3a8ee0 sp=0xc03f3a8e80 pc=0x483b7f
2024-04-27 22:04:33.290	
sync.(*Once).Do(...)
2024-04-27 22:04:33.290	
	/usr/local/go/src/sync/once.go:65
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo(0xc03395f689?, 0xa?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:427 +0x57 fp=0xc03f3a8f30 sp=0xc03f3a8ee0 pc=0x33be677
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).MigrateConnectionTo(0xc012567340, 0xc1e8e68dc0)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:573 +0x34 fp=0xc03f3a8f88 sp=0xc03f3a8f30 pc=0x33c4334
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleMigrateConnTo(0xc00c3590c0?, {0x503bfd8?, 0xc2d03bdf80?}, 0xc5955b8d80, 0xc03d635110)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:419 +0x5a fp=0xc03f3a9040 sp=0xc03f3a8f88 pc=0x3481f5a
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleMigrateConnTo-fm({0x503bfd8?, 0xc2d03bdf80?}, 0x0?, 0x0?)
2024-04-27 22:04:33.290	
	<autogenerated>:1 +0x39 fp=0xc03f3a9078 sp=0xc03f3a9040 pc=0x348ab39
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x500b380?, {0x503bfd8, 0xc2d03bdf80?}, 0x41fab3?, 0x2000?)
2024-04-27 22:04:33.290	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:65 +0x4c fp=0xc03f3a9110 sp=0xc03f3a9078 pc=0x2ef5f0c
2024-04-27 22:04:33.290	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage.func1()
2024-04-27 22:04:33.291	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:196 +0x2c9 fp=0xc03f3a9270 sp=0xc03f3a9110 pc=0x2ef48c9
2024-04-27 22:04:33.291	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage(0x50cf960, {0x503bfd8, 0xc2d03bdf80?}, {{0x503bfd8, 0xc2d03bdf80}, 0xc13ab7be70, {0x505a8b0, 0xc5955b8d80}, 0x0, 0x0, ...}, ...)
2024-04-27 22:04:33.291	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:205 +0x57b fp=0xc03f3a9418 sp=0xc03f3a9270 pc=0x2ef5c7b
2024-04-27 22:04:33.291	
github.com/matrixorigin/matrixone/pkg/common/morpc.NewMessageHandler[...].func3({{0x503bfd8, 0xc2d03bdf80}, 0xc13ab7be70, {0x505a8b0, 0xc5955b8d80}, 0x0, 0x0, 0x0, 0x0, {0x0, ...}}, ...)
2024-04-27 22:04:33.291	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:136 +0xab fp=0xc03f3a94a8 sp=0xc03f3a9418 pc=0x2ef442b
2024-04-27 22:04:33.291	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0026f0210, {0x50a4d20, 0xc440865400}, {0x441d480?, 0xc1e8e68e10}, 0x1)
2024-04-27 22:04:33.291	
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:260 +0xc3e fp=0xc03f3a9c20 sp=0xc03f3a94a8 pc=0x114737e
2024-04-27 22:04:33.291	
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage-fm({0x50a4d20?, 0xc440865400?}, {0x441d480?, 0xc1e8e68e10?}, 0x0?)
2024-04-27 22:04:33.291	
	<autogenerated>:1 +0x46 fp=0xc03f3a9c60 sp=0xc03f3a9c20 pc=0x114d726
2024-04-27 22:04:33.291	
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0026f02c0, {0x50a4d20, 0xc440865400})
2024-04-27 22:04:33.291	
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:393 +0x376 fp=0xc03f3a9eb8 sp=0xc03f3a9c60 pc=0x1124ab6
2024-04-27 22:04:33.291	
github.com/fagongzi/goetty/v2.(*server).doConnection-fm({0x50a4d20?, 0xc440865400?})
2024-04-27 22:04:33.291	
	<autogenerated>:1 +0x33 fp=0xc03f3a9ee0 sp=0xc03f3a9eb8 pc=0x1129133
2024-04-27 22:04:33.291	
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
2024-04-27 22:04:33.291	
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:356 +0x7f fp=0xc03f3a9fe0 sp=0xc03f3a9ee0 pc=0x11242df
2024-04-27 22:04:33.291	
runtime.goexit()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc03f3a9fe8 sp=0xc03f3a9fe0 pc=0x478481
2024-04-27 22:04:33.291	
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 555
2024-04-27 22:04:33.291	
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x45a

2024-04-27 22:04:33.291	
goroutine 1 [select, 437 minutes]:
2024-04-27 22:04:33.291	
runtime.gopark(0xc002677d88?, 0x2?, 0x8?, 0x7c?, 0xc002677d24?)
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc009c00bb0 sp=0xc009c00b90 pc=0x44494e
2024-04-27 22:04:33.291	
runtime.selectgo(0xc009c00d88, 0xc002677d20, 0x2?, 0x0, 0x0?, 0x1)
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc009c00cd0 sp=0xc009c00bb0 pc=0x454ee5
2024-04-27 22:04:33.291	
main.waitSignalToStop(0x503beb0?, 0xc000119560)
2024-04-27 22:04:33.291	
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:126 +0x108 fp=0xc009c00e58 sp=0xc009c00cd0 pc=0x355de28
2024-04-27 22:04:33.291	
main.main()
2024-04-27 22:04:33.291	
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:117 +0x2c8 fp=0xc009c00f40 sp=0xc009c00e58 pc=0x355daa8
2024-04-27 22:04:33.291	
runtime.main()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc009c00fe0 sp=0xc009c00f40 pc=0x4444db
2024-04-27 22:04:33.291	
runtime.goexit()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc009c00fe8 sp=0xc009c00fe0 pc=0x478481
2024-04-27 22:04:33.291	

2024-04-27 22:04:33.291	
goroutine 2 [force gc (idle), 72 minutes]:
2024-04-27 22:04:33.291	
runtime.gopark(0x196642cf9c8d20?, 0x0?, 0x0?, 0x0?, 0x0?)
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc0000b4fa8 sp=0xc0000b4f88 pc=0x44494e
2024-04-27 22:04:33.291	
runtime.goparkunlock(...)
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:404
2024-04-27 22:04:33.291	
runtime.forcegchelper()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc0000b4fe0 sp=0xc0000b4fa8 pc=0x4447b3
2024-04-27 22:04:33.291	
runtime.goexit()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000b4fe8 sp=0xc0000b4fe0 pc=0x478481
2024-04-27 22:04:33.291	
created by runtime.init.6 in goroutine 1
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:310 +0x1a
2024-04-27 22:04:33.291	

2024-04-27 22:04:33.291	
goroutine 3 [runnable]:
2024-04-27 22:04:33.291	
runtime.goschedIfBusy()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/proc.go:361 +0x28 fp=0xc0000b5778 sp=0xc0000b5760 pc=0x444868
2024-04-27 22:04:33.291	
runtime.bgsweep(0x0?)
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/mgcsweep.go:305 +0x151 fp=0xc0000b57c8 sp=0xc0000b5778 pc=0x42e8f1
2024-04-27 22:04:33.291	
runtime.gcenable.func1()

2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000b57e0 sp=0xc0000b57c8 pc=0x423905
2024-04-27 22:04:33.291	
runtime.goexit()
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000b57e8 sp=0xc0000b57e0 pc=0x478481
2024-04-27 22:04:33.291	
created by runtime.gcenable in goroutine 1
2024-04-27 22:04:33.291	
	/usr/local/go/src/runtime/mgc.go:200 +0x66
2024-04-27 22:04:33.291	

### Steps to Reproduce

```Markdown
tke sysbench 100w random_points test
sysbench  --mysql-host=172.16.91.89 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=30 --report-interval=10  cleanup
sysbench  --mysql-host=172.16.91.89 --mysql-port=6001 --mysql-user=dump --mysql-password=111 select_random_points.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=30 --report-interval=10  prepare
sysbench  --mysql-host=172.16.91.89 --mysql-port=6001 --mysql-user=dump --mysql-password=111 select_random_points.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=1000 --time=300 --report-interval=10  --range_selects=off --point_selects=1 run
```

**Comment by m-schen** [comment]
不知道什么情况下会发生 TxnCompilerContext的session属性为空的情况，
看着只有session退出的Close()方法会做这件事。

**Comment by volgariver6** [comment]
fixed

**Comment by heni02** [comment]
confirm，closed
commit：6e9451389
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8959013124
