### ISSUE TITLE
[Bug]: [date 4.27] tke regression:  mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15762]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2981727b0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8860565711/job/24339848210
<img width="1285" alt="企业微信截图_b75cd7b2-5962-4b26-bbc0-3360837391ac" src="https://github.com/matrixorigin/matrixone/assets/113406637/da9a42d6-6aef-4c53-b3f3-990b7409fbcd">
试了下可以连接mo
<img width="976" alt="企业微信截图_952190a4-84d6-4800-8f49-202d802114ab" src="https://github.com/matrixorigin/matrixone/assets/113406637/c056454b-1d28-45c4-b1d7-ceffc844c800">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22BkN%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240427%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714272960000%22,%22to%22:%221714274695000%22%7D%7D%7D&schemaVersion=1&orgId=1

env:
 kubectl -n mo-nightly-regression-20240427 get pod -o wide
NAME                                 READY   STATUS    RESTARTS        AGE   IP               NODE           NOMINATED NODE   READINESS GATES
nightly-regression-dis-dn-0          1/1     Running   0               12h   10.142.78.222    10.129.0.51    <none>           2/2
nightly-regression-dis-log-0         1/1     Running   0               12h   10.142.78.221    10.129.0.132   <none>           2/2
nightly-regression-dis-log-1         1/1     Running   0               12h   10.143.172.194   10.128.0.144   <none>           2/2
nightly-regression-dis-log-2         1/1     Running   0               12h   10.142.78.220    10.129.0.36    <none>           2/2
nightly-regression-dis-proxy-98zbq   1/1     Running   0               12h   10.143.172.195   10.128.0.133   <none>           2/2
nightly-regression-dis-proxy-w6kr4   1/1     Running   0               12h   10.143.172.196   10.128.0.108   <none>           2/2
nightly-regression-dis-tp-cn-6cn65   1/1     Running   1 (3h47m ago)   12h   10.143.172.197   10.128.0.131   <none>           3/3
nightly-regression-dis-tp-cn-9kvs4   1/1     Running   1 (5h18m ago)   12h   10.142.78.224    10.129.0.99    <none>           3/3
nightly-regression-dis-tp-cn-hhznc   1/1     Running   2 (3h48m ago)   12h   10.142.78.223    10.129.0.30    <none>           3/3

profile:
[mo_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/15140668/mo_profile.tar.gz)

### Steps to Reproduce

```Markdown
tke sysbench test
```

**Comment by heni02** [comment]
date 4.28 也同样出现卡住问题
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8868322751/job/24352635422
<img width="1385" alt="企业微信截图_d6087644-edd8-42f2-8a83-01e351221f83" src="https://github.com/matrixorigin/matrixone/assets/113406637/31534162-48bc-4ffa-b9c1-bd9dc7ad2f91">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22BkN%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240428%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714340530920%22,%22to%22:%221714341354048%22%7D%7D%7D&schemaVersion=1&orgId=1

profile：
文件比较大，私发开发定位

**Comment by badboynt1** [comment]
![企业微信截图_17143581315491](https://github.com/matrixorigin/matrixone/assets/112734932/45bc57ae-6c09-4a7d-81d8-376e11dfbe9e)

从日志里看，是hang在上锁这一步，几个cn都是。大概率是出现了死锁
麻烦 @iamlinjunhong  定位一下

**Comment by iamlinjunhong** [comment]
pr ： https://github.com/matrixorigin/matrixone/pull/15784

**Comment by heni02** [comment]
目前回归已经没有锁问题导致的mo hung的问题，先降级，再观察两天回归测试结果

**Comment by heni02** [comment]
没有再出现问题，closed
commit：3ac2f912b
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9003686974/attempts/1
