### ISSUE TITLE
[Subtask]: support database operator in transactions

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#15779]
### Parent Issue

issue #13516

### Detail of Subtask

support database operator in transactions

**Comment by qingxinhome** [comment]
This function has been implemented and PR has been merged. Please verify and test it， @sukki37 @aressu1985 @heni02 @daviszhen @ck89119

**Comment by heni02** [comment]
已有的bvt case和pr新增的case覆盖了测试点，closed
