### ISSUE TITLE
[Bug]: TN panic after upgrade

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#15782]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0c3448243

### Other Environment Information

```Markdown
upgrade 1.1-dev to main
```

### Actual Behavior

TN panic: https://grafana.cn-qa.matrixone.tech/goto/VWff3EfIg?orgId=1

### Expected Behavior

TN should not panic

### Steps to Reproduce

```Markdown
see https://grafana.cn-qa.matrixone.tech/goto/VWff3EfIg?orgId=1
```

**Comment by LeftHandCold** [comment]
fixed

**Comment by TangxingZhou** [comment]
测试验证不再复现
