### ISSUE TITLE
[Tech Request]: make stats contains rows from workspace(writes & logtail)

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#15789]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
make stats contains rows from workspace(writes & logtail)
rel issue: #15739
```

**Comment by ouyuanning** [comment]
现在修改为当行锁过多时候，自动转表锁了。这个issue可以不用处理了

**Comment by volgariver6** [comment]
close it please as it is not neccesary @ouyuanning
