### ISSUE TITLE
[Bug]: select * from information_schema.columns contains partition information

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

283a189a5559869c3342020b9f2f65083a53a747

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from information_schema.columns where table_schema='sys_db1';
+---------------+--------------+-----------------+------------------+------------------+----------------+-------------+-----------------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+--------------------+------------+----------------+---------------------------------+----------------+-----------------------+--------+
| table_catalog | table_schema | table_name      | column_name      | ordinal_position | column_default | is_nullable | data_type       | character_maximum_length | character_octet_length | numeric_precision | numeric_scale | datetime_precision | character_set_name | collation_name | column_type        | column_key | extra          | privileges                      | column_comment | generation_expression | srs_id |
+---------------+--------------+-----------------+------------------+------------------+----------------+-------------+-----------------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+--------------------+------------+----------------+---------------------------------+----------------+-----------------------+--------+
| def           | sys_db1      | sys_t1          | __mo_fake_pk_col |                2 | NULL           | NO          | BIGINT UNSIGNED |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | BIGINT UNSIGNED(0) | PRI        | auto_increment | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | sys_t1          | c1               |                1 | NULL           | YES         | CHAR            |                        1 |                     24 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | CHAR(1)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test03          | birth_date       |                2 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test03          | emp_no           |                1 | NULL           | NO          | INT             |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | INT(32)            | PRI        |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test03          | first_name       |                3 | NULL           | NO          | VARCHAR         |                       14 |                    336 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(14)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test03          | gender           |                5 | NULL           | NO          | VARCHAR         |                        5 |                    120 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(5)         |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test03          | hire_date        |                6 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test03          | last_name        |                4 | NULL           | NO          | VARCHAR         |                       16 |                    384 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(16)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p01%!%test03 | birth_date       |                2 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p01%!%test03 | emp_no           |                1 | NULL           | NO          | INT             |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | INT(32)            | PRI        |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p01%!%test03 | first_name       |                3 | NULL           | NO          | VARCHAR         |                       14 |                    336 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(14)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p01%!%test03 | gender           |                5 | NULL           | NO          | VARCHAR         |                        5 |                    120 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(5)         |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p01%!%test03 | hire_date        |                6 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p01%!%test03 | last_name        |                4 | NULL           | NO          | VARCHAR         |                       16 |                    384 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(16)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p02%!%test03 | birth_date       |                2 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p02%!%test03 | emp_no           |                1 | NULL           | NO          | INT             |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | INT(32)            | PRI        |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p02%!%test03 | first_name       |                3 | NULL           | NO          | VARCHAR         |                       14 |                    336 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(14)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p02%!%test03 | gender           |                5 | NULL           | NO          | VARCHAR         |                        5 |                    120 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(5)         |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p02%!%test03 | hire_date        |                6 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p02%!%test03 | last_name        |                4 | NULL           | NO          | VARCHAR         |                       16 |                    384 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(16)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p03%!%test03 | birth_date       |                2 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p03%!%test03 | emp_no           |                1 | NULL           | NO          | INT             |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | INT(32)            | PRI        |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p03%!%test03 | first_name       |                3 | NULL           | NO          | VARCHAR         |                       14 |                    336 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(14)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p03%!%test03 | gender           |                5 | NULL           | NO          | VARCHAR         |                        5 |                    120 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(5)         |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p03%!%test03 | hire_date        |                6 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p03%!%test03 | last_name        |                4 | NULL           | NO          | VARCHAR         |                       16 |                    384 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(16)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p04%!%test03 | birth_date       |                2 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p04%!%test03 | emp_no           |                1 | NULL           | NO          | INT             |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | INT(32)            | PRI        |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p04%!%test03 | first_name       |                3 | NULL           | NO          | VARCHAR         |                       14 |                    336 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(14)        |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p04%!%test03 | gender           |                5 | NULL           | NO          | VARCHAR         |                        5 |                    120 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(5)         |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p04%!%test03 | hire_date        |                6 | NULL           | NO          | DATE            |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)            |            |                | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | %!%p04%!%test03 | last_name        |                4 | NULL           | NO          | VARCHAR         |                       16 |                    384 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(16)        |            |                | select,insert,update,references |                |                       |   NULL |
+---------------+--------------+-----------------+------------------+------------------+----------------+-------------+-----------------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+--------------------+------------+----------------+---------------------------------+----------------+-----------------------+--------+
32 rows in set (0.01 sec)

### Steps to Reproduce

```Markdown
create database sys_db1;
create table sys_db1.test01 (
emp_no      int             not null,
birth_date  date            not null,
first_name  varchar(14)     not null,
last_name   varchar(16)     not null,
gender      varchar(5)      not null,
hire_date   date            not null,
primary key (emp_no)
) partition by range columns (emp_no)(
partition p01 values less than (100001),
partition p02 values less than (200001),
partition p03 values less than (300001),
partition p04 values less than (400001)
);
select * from information_schema.columns where table_schema='sys_db1';
```

**Comment by qingxinhome** [comment]
处理中

**Comment by qingxinhome** [comment]
The issue has been resolved and PR has been merged. Please verify and test @heni02 @sukki37 @daviszhen

**Comment by heni02** [comment]
confirm,closed
commit:341c2b6e358d776186e20a723bf96849e409ccff
mysql> select * from information_schema.columns where table_schema='sys_db1';
+---------------+--------------+------------+-------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+-------------+------------+-------+---------------------------------+----------------+-----------------------+--------+
| table_catalog | table_schema | table_name | column_name | ordinal_position | column_default | is_nullable | data_type | character_maximum_length | character_octet_length | numeric_precision | numeric_scale | datetime_precision | character_set_name | collation_name | column_type | column_key | extra | privileges                      | column_comment | generation_expression | srs_id |
+---------------+--------------+------------+-------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+-------------+------------+-------+---------------------------------+----------------+-----------------------+--------+
| def           | sys_db1      | test01     | birth_date  |                2 | NULL           | NO          | DATE      |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)     |            |       | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test01     | emp_no      |                1 | NULL           | NO          | INT       |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | INT(32)     | PRI        |       | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test01     | first_name  |                3 | NULL           | NO          | VARCHAR   |                       14 |                    336 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(14) |            |       | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test01     | gender      |                5 | NULL           | NO          | VARCHAR   |                        5 |                    120 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(5)  |            |       | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test01     | hire_date   |                6 | NULL           | NO          | DATE      |                     NULL |                   NULL |              NULL |          NULL |               NULL | NULL               | NULL           | DATE(0)     |            |       | select,insert,update,references |                |                       |   NULL |
| def           | sys_db1      | test01     | last_name   |                4 | NULL           | NO          | VARCHAR   |                       16 |                    384 |              NULL |          NULL |               NULL | utf8               | utf8_bin       | VARCHAR(16) |            |       | select,insert,update,references |                |                       |   NULL |
+---------------+--------------+------------+-------------+------------------+----------------+-------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+-------------+------------+-------+---------------------------------+----------------+-----------------------+--------+
6 rows in set (0.01 sec)
