### ISSUE TITLE
[Bug]:  restore-freetier-01-113集群，show publications报错ERROR 20301 (HY000): invalid input: column update_time does not exist

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#15801]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0c3448243

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
连接串信息放在：https://github.com/matrixorigin/MO-Cloud/issues/3165
```

### Actual Behavior

show publications;
报错：
ERROR 20301 (HY000): invalid input: column update_time does not exist

### Expected Behavior

正常执行

### Steps to Reproduce

```Markdown
稳定复现，如Actual Behavior
```

**Comment by ck89119** [comment]
mo_pubs表没有update_time字段，应该是升级的问题

<img width="769" alt="image" src="https://github.com/matrixorigin/MO-Cloud/assets/4971300/6ff99615-ba52-4e01-b148-35f922f97990">

**Comment by TangxingZhou** [comment]
恢复升级测试验证通过

**Comment by TangxingZhou** [comment]
验证已解决

**Comment by aressu1985** [comment]
test done
