### ISSUE TITLE
[Tech Request]: when composite primary key has a column that is auto-incr, and this column does not specify a value, no dup check is needed

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#15809]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
create table(a int auto_incrment, b int, c int, primary key(a, b));

-- for sql like, there is no need for dup check
insert into t(b, c) values (2, 2);
```

**Comment by ouyuanning** [comment]
要基于新的DML plan和算子处理
