### ISSUE TITLE
[Bug]: load data report panic on 128 daily regression test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15800]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fa8fc41f84244d39d2329ffadf7f089231fbea01

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8880260541/job/24379900219

<img width="1363" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f6c0c938-fa80-40b2-8126-1fd75c14b084">

### Steps to Reproduce

```Markdown
trigger daily regression test on 128.
```

**Comment by badboynt1** [comment]
fixed

**Comment by Ariznawlll** [comment]
commit：42d05c25af67ba5c61d59c3fb5c9677145bcbe2e
job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8890234450

verified.
