### ISSUE TITLE
[Bug]: bvt case failed, the row count of result is not equal with expected for mo_ctl_merge.test

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#15807]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f460e5f7c7a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1569" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/49b3995e-e9cc-4194-8036-df20685cd0fb">

### Steps to Reproduce

```Markdown
Matrixone Standlone CI / e2e BVT Test on Linux/x64(LAUNCH, PESSIMISTIC) : 

https://github.com/matrixorigin/matrixone/actions/runs/8889836165/job/24408837204?pr=15806
```

**Comment by jensenojs** [comment]
repro : https://github.com/matrixorigin/matrixone/actions/runs/8890789183/job/24411465701?pr=15806

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/9b727bec-9a64-492b-80eb-0374e983b780)

2 objects are already merged into 1 object, but metadata_scan still returns 2 rows.

**Comment by fengttt** [comment]
For reasons we don't understand, seems this failure has something to do with #15723.   #15723 must be tested with both ON/OFF value on this merge test case.

**Comment by aressu1985** [comment]
和子然沟通，可以在1.2.1版本周期内解决

**Comment by w-zr** [comment]
还在复现中

**Comment by w-zr** [comment]
我在bvt中跑metadata_scan前sleep了1秒。应该能大概率减少这个bvt挂掉的风险。

**Comment by heni02** [comment]
和开发沟通，该问题是偶现，没有复现，解决方法是在bvtcase中添加了sleep 1s避免该问题出现，先关闭
