### ISSUE TITLE
[Bug]: [date 4.29]tke regression: sysbench10w  update_index 100threads test reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15814]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fa8fc41f8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8880917854/job/24393976249
<img width="1277" alt="企业微信截图_7142a64d-e963-4fed-aeec-0a59ae3ffd34" src="https://github.com/matrixorigin/matrixone/assets/113406637/82760ffc-7840-43fa-bc92-77cfcd05d7c6">

panic error:
<img width="1441" alt="企业微信截图_3d923fb0-c426-4028-b8c2-26ef338c0e7d" src="https://github.com/matrixorigin/matrixone/assets/113406637/fb56994e-56b3-4cdf-8bd8-3148bbcbde6a">
log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22y_8%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240429%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714423241658%22,%22to%22:%221714423242658%22%7D%7D%7D&schemaVersion=1&orgId=1	
panic: runtime error: invalid memory address or nil pointer dereference
2024-04-29 20:40:42.650	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x224157e]
2024-04-29 20:40:42.650	

2024-04-29 20:40:42.650	
goroutine 1564844 [running]:
2024-04-29 20:40:42.650	
{"level":"INFO","time":"2024/04/29 20:40:42.650886 +0000","caller":"compile/compile.go:1365","msg":"delete of 'execute __mo_stmt_id_6' write s3\n"}
2024-04-29 20:40:42.650	
panic({0x3efde40?, 0x7690350?})
2024-04-29 20:40:42.650	
	/usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc0116eb2d8 sp=0xc0116eb228 pc=0x44162c
2024-04-29 20:40:42.650	
runtime.panicmem(...)
2024-04-29 20:40:42.650	
	/usr/local/go/src/runtime/panic.go:261
2024-04-29 20:40:42.650	
runtime.sigpanic()
2024-04-29 20:40:42.650	
	/usr/local/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc0116eb338 sp=0xc0116eb2d8 pc=0x458b98
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/objectio.ReadExtent({0x507a530, 0xc002b9b2c0}, {0xc37e042210, 0x2a}, 0xc0116eb500, 0x13, {0x50c6140, 0xc002800900}, 0x48d10f0)
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/funcs.go:62 +0x23e fp=0xc0116eb3b8 sp=0xc0116eb338 pc=0x224157e
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/objectio.LoadObjectMetaByExtent({0x507a530, 0xc002b9b2c0}, 0xc0116eb4e8, 0x416c65?, 0xf8?, 0x41496e0?, {0x50c6140, 0xc002800900})
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/cache.go:154 +0x19e fp=0xc0116eb4a8 sp=0xc0116eb3b8 pc=0x223f79e

2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/objectio.FastLoadObjectMeta({0x507a530?, 0xc002b9b2c0?}, 0x0?, 0x0?, {0x50c6140?, 0xc002800900?})
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/cache.go:223 +0x99 fp=0xc0116eb528 sp=0xc0116eb4a8 pc=0x223ff39
2024-04-29 20:40:42.651	
{"level":"INFO","time":"2024/04/29 20:40:42.651088 +0000","caller":"disttae/txn_table.go:1805","msg":"data return by remote pipeline\n"}
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updateInfoFromZoneMap.func2({{{0x1, 0x8f, 0x2a, 0x79, 0xd0, 0xc1, 0x77, 0xf7, 0x82, 0x9, ...}, ...}})
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/stats.go:552 +0x1e5 fp=0xc0116eb8c0 sp=0xc0116eb528 pc=0x2de02c5
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.ForeachVisibleDataObject(0xc002800900?, {0x0, 0x0, 0x0, 0x0, 0x91, 0x55, 0xae, 0x14, 0xdb, ...}, ...)
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:337 +0xfe fp=0xc0116eba78 sp=0xc0116eb8c0 pc=0x2dff47e
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updateInfoFromZoneMap({0x507a530?, 0xc002b9b2c0}, 0xc0116ebeb0, 0xc0116ebc50)
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/stats.go:612 +0x21c fp=0xc0116ebba8 sp=0xc0116eba78 pc=0x2ddfffc
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.UpdateStats({0x507a530, 0xc002b9b2c0}, 0xc0116ebeb0)
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/stats.go:664 +0x285 fp=0xc0116ebd18 sp=0xc0116ebba8 pc=0x2de19c5
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*GlobalStats).updateTableStats(0xc00677c090, {0x1, 0x42803})
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/stats.go:434 +0x69c fp=0xc0116ebfb8 sp=0xc0116ebd18 pc=0x2dde41c
2024-04-29 20:40:42.651	
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*GlobalStats).updateWorker.func1()
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/stats.go:261 +0x28 fp=0xc0116ebfe0 sp=0xc0116ebfb8 pc=0x2ddd5e8
2024-04-29 20:40:42.651	
runtime.goexit()
2024-04-29 20:40:42.651	
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0116ebfe8 sp=0xc0116ebfe0 pc=0x478481
2024-04-29 20:40:42.651	
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*GlobalStats).updateWorker in goroutine 278
2024-04-29 20:40:42.651	
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/stats.go:261 +0x47
2024-04-29 20:40:42.651	

### Steps to Reproduce

```Markdown
tke sysbench10w  update_index 100threads test
sysbench  --mysql-host=172.16.35.142 --mysql-port=6001 --mysql-user=dump --mysql-*** oltp_update_index.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10  prepare
sysbench  --mysql-host=172.16.35.142 --mysql-port=6001 --mysql-user=dump --mysql-***  oltp_update_index.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=300 --report-interval=10 --range_selects=off --point_selects=1 run
```

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/blob/main/pkg/objectio/funcs.go#L62

**Comment by reusee** [comment]
revert 可能导致的 commit

**Comment by reusee** [comment]
revert

**Comment by reusee** [comment]
等待验证

**Comment by fengttt** [comment]
> 等待验证

I wonder what are we waiting.

Do we have a repro?  @reusee why not run the verification yourself?  And   HOW the revert got merged into main without a verification?

**Comment by reusee** [comment]
> > 等待验证
> 
> I wonder what are we waiting.
> 
> Do we have a repro? @reusee why not run the verification yourself? And HOW the revert got merged into main without a verification?

测试团队做回归测试时，遇到这个问题，需要快速revert以避免阻塞回归测试。一向就是这样做的，测试定位到的commit，没法快速解决时，都需要revert。

**Comment by heni02** [comment]
revert后没有这个问题了，closed
commit：6e9451389
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8959013124
