### ISSUE TITLE
[Bug]: merge should not panic with any io error

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#15829]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/39627130/9c6cfda8-39fd-4a65-9867-0b017440c9fe)

### Expected Behavior

merge should not panic with any io error

### Steps to Reproduce

```Markdown
1. run tpcc or sysbench insert
2. wait 1~2 mins
3. ctrl-c the mo-service
```

**Comment by w-zr** [comment]
pr merged.
