### ISSUE TITLE
[Bug]: [date 5.5]tke regression: tpcc 500warehouses 1000threads test cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15835]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6e9451389

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8959013124/job/24604578275
<img width="1033" alt="企业微信截图_04be56af-d4f0-4f1a-9aae-efa79674a4a0" src="https://github.com/matrixorigin/matrixone/assets/113406637/d3d2e262-354a-4d4e-b4ab-75109a5acd52">
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1714924989945&to=1714936798291&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20240505
<img width="1233" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/bd7732b4-3dcb-4c34-89e7-59342fcaac34">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22rLd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240505%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714932275187%22,%22to%22:%221714933041547%22%7D%7D%7D&schemaVersion=1&orgId=1

profile plz contact to me

### Steps to Reproduce

```Markdown
tke tpcc 500warehouses 1000threads test
```

**Comment by daviszhen** [comment]
在找oom的mem profile

**Comment by daviszhen** [comment]
https://grafana.ci.matrixorigin.cn/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-nightly-regression-20240505&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki&from=1714924989000&to=1714936798000

**Comment by daviszhen** [comment]
这个问题的mem profile 过期看不到了。

**Comment by ouyuanning** [comment]
从heap看，内存占用较多的是 2024-05-06_11:32:06 时候的 10.142.84.165 
<img width="1715" alt="image" src="https://github.com/matrixorigin/matrixone/assets/45346669/99c77cb9-6105-4d73-824f-53643f1555f0">

**Comment by badboynt1** [comment]
最近几天tpcc没有再oom了，应该和tpch的修复有关。 再观察几天

**Comment by aressu1985** [comment]
先关闭
