### ISSUE TITLE
[Bug]: big_data regression: load data and insert into select report 'file mo-benchmark-8889381173/data/018f2d73-c9da-7bfa-9e7d-b928eefcb9f1_00000 is not found''

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4139c445a7573d828781109516ad8f33ff7cb152

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8889381173/job/24407993328
（load and insert test -> load sortkey 10y）
<img width="1006" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/35d16d9e-8481-4fa7-9ffa-a43f638fd4d6">
<img width="994" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ebf57258-1db9-45f7-b2c1-46b0824094a7">
<img width="982" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f9d9b19f-6d43-4192-bbbc-8f4ab20abecb">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%227jw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240430%5C%22%7D%20%7C%3D%20%60file%20mo-benchmark-8889381173%2Fdata%2F018f2d73-c9da-7bfa-9e7d-b928eefcb9f1_00000%20is%20not%20found%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

load data success.

### Steps to Reproduce

```Markdown
trigger big data test on tke.

第一次出现问题的load场景：
create table if not exists big_data_test.table_with_sortkey_for_load_1B( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3) ) cluster by (col12);

load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/1000000000_20_columns_load_data_new.csv'} into table big_data_test.table_with_sortkey_for_load_1B fields terminated by '|' lines terminated by '\n' ignore 1 lines parallel 'true';
```

**Comment by gouhongshen** [comment]
出错的时间：

<img width="1254" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26336316/976d4049-cbe8-4a46-b5c5-742b6491e6c6">

|

文件被 GC 的时间:
`2024-04-30 08:26:00.698`

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%227jw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240430%5C%22%7D%20%7C~%20%60files%20to%20delete.%2A018f2d73-c9da-7bfa-9e7d-b928eefcb9f1_00000%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714450219761%22,%22to%22:%221714480462726%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/pull/15804 可能已经修复了这个bug

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
今天在main上验证没有这个问题了
commit：6b1a10d62ec53a54394120d8c6327c7886c1ce15

URL：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8995012876/job/24709325460

fixed
