### ISSUE TITLE
[Feature Request]: change keep_user_target_list_in_result  default to 1

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#15831]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

 change keep_user_target_list_in_result  default to 1

**Comment by YANGGMM** [comment]
finished

**Comment by heni02** [comment]
confirm,closed
main commit:52b7c7b2a6806b3d24761e03fa23d83753c5f370
<img width="634" alt="企业微信截图_589d0f90-7ef3-4477-8145-50067031d74b" src="https://github.com/matrixorigin/matrixone/assets/113406637/53d39e84-2bc8-47c9-ab91-5697e3676877">

1.2-dev commit:0850ab6fb45ffc16648f1f04c3566629dc35492d
<img width="667" alt="企业微信截图_d1c42dce-a264-4343-824a-5b2a26a90a97" src="https://github.com/matrixorigin/matrixone/assets/113406637/a1ab474b-4fe0-445d-a714-c776945b5330">
