### ISSUE TITLE
[Bug]: there are still lots of w-w during tpcc longrunning test on distributed test 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15843]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6e94513897f3a739602429e5a61d7c9127fd9a2a

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

during statbility test on distributed, there are lots of w-w and dup during tpcc benchmark test:
<img width="1412" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/1815b3db-9953-408d-98e0-6880ef563062">

<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/dbdd055f-64fc-435d-9f40-dceb088dba2d">

tpcc tool logs:
 
[tpcc-test.tar.gz](https://github.com/matrixorigin/matrixone/files/15217589/tpcc-test.tar.gz)

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%223sB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-6e94513-20240503%5C%22,%20pod%3D%5C%22stability-regression-dis-dn-0%5C%22%7D%20%7C%3D%20%60w-w%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15948

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/15992

**Comment by triump2020** [comment]
Wait for @ouyuanning ’ PR

**Comment by triump2020** [comment]
In testing validation.

**Comment by triump2020** [comment]
In testing

**Comment by ouyuanning** [comment]
今天罗飞帮忙加了日志。还没跑验证

**Comment by ouyuanning** [comment]
昨天跑还有发现，待继续加日志分析

**Comment by triump2020** [comment]
![企业微信截图_17180727009693](https://github.com/matrixorigin/matrixone/assets/63033222/2e7c367f-266f-4598-948e-07ed15088c1b)



从日志看：  运行 : DELETE FROM sbtest3 WHERE id=50005  , 没有去加锁，导致找不到pk =50005 的记录，从而没有产生deletes, 之后 事务紧跟着运行了 Insert pk=50005 导致了dup。

**Comment by ouyuanning** [comment]
待继续分析

**Comment by ouyuanning** [comment]
在处理其他s-1

**Comment by ouyuanning** [comment]
在处理其他s-1

**Comment by ouyuanning** [comment]
在处理其他s-1

**Comment by ouyuanning** [comment]
待再跑一下sysbench和regresion

**Comment by triump2020** [comment]
用这个issue 来跟踪 delete 加锁导致的  dup/ww 问题.

**Comment by ouyuanning** [comment]
regression还是会有问题。还在排查

**Comment by ouyuanning** [comment]
regression还是会有问题，待处理

**Comment by ouyuanning** [comment]
regression还是会有问题，待处理

**Comment by ouyuanning** [comment]
regression还是会有问题，待处理

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
等DML重构版本时候处理

**Comment by ouyuanning** [comment]
等DML重构版本合并后处理

**Comment by aressu1985** [comment]
fixed
