### ISSUE TITLE
[Bug]: dn crashed continuously  by panic: runtime error: index out of range [0] with length 0 after statbility test on distributed for about  40 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15842]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6e94513

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

after statbility test on distributed for about  40 hours, the dn crash continously by panic: runtime error: index out of range [0] with length 0:
{"level":"INFO","time":"2024/05/06 06:31:15.945959 +0000","caller":"gc/checkpoint.go:761","msg":"[DiskCleaner]","operation":"Consume-End","cost :":"69.358419ms","snap meta size :":0,"table meta size :":0,"operand":"account count: 5, table count: 426, object count: 0"}
panic: runtime error: index out of range [0] with length 0

goroutine 3843 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*SnapshotMeta).SaveTableInfo(0xc0e68b8100, {0xc0e77c0480, 0x39}, {0x6f23680, 0xc0015e1e00})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/snapshot.go:412 +0x785
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*checkpointCleaner).createNewInput(0xc0da563680, {0xc0eb49cc80, 0xa, 0x10})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/checkpoint.go:789 +0xb5a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*checkpointCleaner).Process(0xc0da563680)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/checkpoint.go:688 +0x2d5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc.(*DiskCleaner).process(0xc0e68b8140, {0xc0e6c9a000, 0x1, 0x3e8})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/diskcleaner.go:90 +0xc8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x423
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 580
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0x145

dn-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%223sB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-6e94513-20240503%5C%22,%20pod%3D%5C%22stability-regression-dis-dn-0%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by LeftHandCold** [comment]
存储空间满了，写入失败。报错信息不对已经修复

**Comment by aressu1985** [comment]
fixed
