### ISSUE TITLE
[Bug]: cn crashed continously by panic: interface conversion: interface {} is nil after stability test on distributed mode for about 20 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15847]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

42d05c2

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

after stability test on distributed mode for about 20 hours, cn crashed continuously by:
hChecksum.Read":38,"FileService.FileWithChecksum.UnderlyingRead":84}
{"level":"INFO","time":"2024/05/06 07:32:41.984795 +0000","name":"cn-service.StatsLog","caller":"mometric/stats_log_writer.go:121","msg":"duration: 15000000000, blk hit rate: 0/0=1.0000, entry hit rate: 0/0=1.0000, (average) blks in each reader: 0/0=1.0000","uuid":"36653162-3564-3066-6365-666661353638"}
panic: interface conversion: interface {} is nil, not func(context.Context, bool) (string, error)

goroutine 482 [running]:
github.com/matrixorigin/matrixone/pkg/util/export/etl/db.GetSQLWriterDBAddressFunc()
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/db/db_holder.go:85 +0x5a
github.com/matrixorigin/matrixone/pkg/util/export/etl/db.GetOrInitDBConn.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/db/db_holder.go:115 +0xb1
github.com/matrixorigin/matrixone/pkg/util/export/etl/db.GetOrInitDBConn(0x0, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/db/db_holder.go:145 +0x163
github.com/matrixorigin/matrixone/pkg/util/export/etl/db.WriteRowRecords({0xc0046f0000, 0x2b, 0x40}, 0x9226940, 0xb2d05e00)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/db/db_holder.go:172 +0x19d
github.com/matrixorigin/matrixone/pkg/util/export/etl.(*DefaultSqlWriter).flushBuffer(0xc005c01200, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/sql.go:67 +0x15b
github.com/matrixorigin/matrixone/pkg/util/export/etl.(*DefaultSqlWriter).FlushAndClose(0xc005c01200)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/sql.go:91 +0xa5
github.com/matrixorigin/matrixone/pkg/util/export.(*reactWriter).FlushAndClose(0xc005c01240)

<img width="860" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/a87768d0-e92a-4138-bfa1-8c7569308c2d">

cn-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%223sB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-42d05c2-20240430%5C%22,%20pod%3D%5C%22stability-regression-dis-tp-cn-v5frj%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714166459068%22,%22to%22:%221714657293068%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by xzxiong** [comment]
fix by 984dcad5f

**Comment by xzxiong** [comment]
dup as https://github.com/matrixorigin/MO-Cloud/issues/3166

**Comment by aressu1985** [comment]
fixed
