### ISSUE TITLE
[Bug]: dn crashed by panic: runtime error: invalid memory address or nil pointer dereference after stability test on distributed mode for about 20 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15848]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

42d05c2

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

after stability test on distributed mode for about 20 hours, the dn crashed by:

<img width="1206" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/80165a6f-4bcd-4780-aa04-db800e9ba765">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%223sB%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-42d05c2-20240430%5C%22,%20pod%3D%5C%22stability-regression-dis-dn-0%5C%22%7D%20%7C%3D%20%60invalid%20memory%20address%20or%20nil%20pointer%20dereference%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221714512059000%22,%22to%22:%221715002893000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by jiangxinmeng1** [comment]
加了日志，在等复现

**Comment by jiangxinmeng1** [comment]
加了日志，在等复现

**Comment by XuPeng-SH** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
