### ISSUE TITLE
[Bug]:  bvt failed occasionally during merge run "internal error: force flush failed: internal error: timeout"

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15858]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8903729513/job/24452516041

https://github.com/matrixorigin/matrixone/actions/runs/8968528500/job/24628995766

2024-05-06 12:13:04 ERROR Executor:267 - [/home/runner/_work/matrixone/matrixone/matrixone/test/distributed/cases/dml/checkpoint/checkpoint.test][row:28][select mo_ctl('dn','checkpoint','');] was executed failed, con[id=0, user=dump, ***
2024-05-06 12:13:04 ERROR Executor:269 - [EXPECT RESULT]:
mo_ctl(dn, checkpoint, )
{\n  "method": "Checkpoint",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
2024-05-06 12:13:04 ERROR Executor:270 - [ACTUAL RESULT]:
internal error: force flush failed: internal error: timeout

### Steps to Reproduce

```Markdown
start merge run
```

**Comment by aptend** [comment]
<img width="1252" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/2068beec-c5e4-4ec5-8b06-4832a7527332">

<img width="1261" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/a7bee496-2846-46e6-8426-19d9e4cd5cfb">

共计 1719 个表需要 flush，按 p50 的 81ms，async worker 为 2(宿主机CPU为8)，预计消耗 `1719 * 0.08 / 2 = 68.76s`，超过 1 分钟限制

**Comment by w-zr** [comment]
before #15905 :
![image](https://github.com/matrixorigin/matrixone/assets/28624654/ceae3943-4bd9-43ec-ab28-9cf21a4e1d43)
after:
![image](https://github.com/matrixorigin/matrixone/assets/28624654/4e01d4be-97b0-42e7-a980-0e8f71ae1488)
