### ISSUE TITLE
[Bug]: [big data regression test] after load data, the result of actual count(*) is not correct.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15855]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9e1107c34ae4606649c4465f907220f0da4618ee

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url:**  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8964781212/job/24618401446

<img width="885" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/53a70d4c-c0e0-4ade-ae8d-9b5cbc494477">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22VLd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**确认过cos的数据量是对的**
**集群还在，可以用来查原因**

### Steps to Reproduce

```Markdown
trigger big data test on tke.

kubectl -n mo-big-data-20240506 get svc

mysql -h 172.16.104.232 -P 6001 -udump -p111

use big_data_test;
select count(*) from table_basic_for_load_100m;
select count(*) from table_basic_for_load_1b;


表table_basic_for_load_100m：
create table if not exists big_data_test.table_basic_for_load_100M( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));

load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/100000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_100M fields terminated by '|' lines terminated by '\n' parallel 'true';

if you need ak and sk, please contact me.
```

**Comment by ouyuanning** [comment]
#15783 这个PR会引起算子reuse时候的状态有问题。会导致并行load的时候，部分pipeline的数据没有被写入。
该pr已revert，可以再试一试。

**Comment by Ariznawlll** [comment]
远宁哥的pr revert了，但是main上load data还有别的问题，需要修好之后重新跑.

**Comment by Ariznawlll** [comment]
**commit: 6b1a10d62ec53a54394120d8c6327c7886c1ce15**
<img width="701" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/52b8c1dd-41af-4133-99cb-cdbae0f5ec40">


fixed
