### ISSUE TITLE
[Bug]: Invalid memory address during a multi tables join query 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1586]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):65f8c50ac2d6b6e47413a8c9e2fd1491248ae7da
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Both following queries were notified. 

![37c7c0ab88afad6f3de7e2b9f4fbee3](https://user-images.githubusercontent.com/88298673/148519741-f24185bd-7b8d-4a00-b058-4fdcf7ade7db.png)

**Comment by m-schen** [comment]
table alias cause this problem.
when projection
attribute name we recorded is `alias.columnName`
but in batch, we recorded only `columnName`
so we could't find information about this column and just return a nil value.

**Comment by nnsgmsone** [comment]
The cause of this problem is the same as described above, and I will add rename graph next to solve this problem.
