### ISSUE TITLE
[Bug]: [date 5.6]tke regression: mo reported fatal error wait latest commit ts failed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15865]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1400a684f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8970898519/job/24659098329
<img width="1420" alt="企业微信截图_7aa80b8c-e950-4f36-a605-877e6cd545a5" src="https://github.com/matrixorigin/matrixone/assets/113406637/9a15b31a-4e2f-43a5-9e30-154f678559fb">

22:50 cn重启
<img width="969" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/2479bd9f-5f37-4627-b93d-0dd700b7f2a9">
<img width="1403" alt="企业微信截图_a36914d8-d6f1-4904-a760-faa6f06b5223" src="https://github.com/matrixorigin/matrixone/assets/113406637/e2196fc4-493c-45cc-b839-cd26f7f36fbe">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Qq4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240506%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715035770349%22,%22to%22:%221715036235866%22%7D%7D%7D&schemaVersion=1&orgId=1

profile plz connect to me

### Steps to Reproduce

```Markdown
tke regression load data
```

**Comment by volgariver6** [comment]
pr committed, wait for merge.

**Comment by volgariver6** [comment]
fixed

**Comment by volgariver6** [comment]
根本原因是系统负载太高，导致logtail 推送时间戳慢。这个pr把sync命令的超时时间改大，降低出现的概率。负载高的issue：https://github.com/matrixorigin/matrixone/issues/13762

**Comment by heni02** [comment]
最近两天的回归没有出现该错误，无法确定是没有复现还是已经解决，先closed，再出现定位
