### ISSUE TITLE
[Bug]: [date 5.6] tke regression: load data parallel mo hung  

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15867]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1400a684f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8970898519/job/24635995763
<img width="1117" alt="企业微信截图_f3a513ed-488c-478b-a6cd-2957827c93ae" src="https://github.com/matrixorigin/matrixone/assets/113406637/c26e67c6-1ad4-46e5-858a-2a8a97821a5d">
正常ssb load100G耗时7m+，其他load相关测试也会hung，单机也是

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Qq4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240506%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715007689784%22,%22to%22:%221715008484486%22%7D%7D%7D&schemaVersion=1&orgId=1

profile plz connect to me

### Steps to Reproduce

```Markdown
tke regression ssb100G load
```

**Comment by badboynt1** [comment]
已经定位到是https://github.com/matrixorigin/matrixone/pull/15786 这个pr导致的
没有hang住，只是性能下降太多
正在分析具体原因

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/15874

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
commit:8103bbc52
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/8987301006
