### ISSUE TITLE
[Bug]: TestDedup2 DATA RACE

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#15869]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[1.log](https://github.com/matrixorigin/matrixone/files/15229296/1.log)

### Steps to Reproduce

```Markdown
CI UT
```

**Comment by daviszhen** [comment]
![Screenshot from 2024-05-07 14-03-24](https://github.com/matrixorigin/matrixone/assets/60595215/f1e26393-9efc-43ef-b7fd-d9c5a659caf9)

**Comment by XuPeng-SH** [comment]
fixed
