### ISSUE TITLE
[Bug]: Like with '_' doesn't work properly

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1588]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a08aefcbf08fafde85d98ef10dbd26d588716cbe
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t3(
cont_nr int(11) NOT NULL auto_increment primary key,
ver_nr int(11) NOT NULL default 0,
aufnr int(11) NOT NULL default 0,
username varchar(50) NOT NULL default '',
hdl_nr int(11) NOT NULL default 0,
eintrag int NOT NULL default 00000000,
st_klasse varchar(40) NOT NULL default '',
st_wert varchar(40) NOT NULL default '',
st_zusatz varchar(40) NOT NULL default '',
st_bemerkung varchar(255) NOT NULL default '',
kunden_art varchar(40) NOT NULL default '',
mcbs_knr int(11) default NULL,
mcbs_aufnr int(11) NOT NULL default 0,
schufa_status char(1) default '?',
bemerkung varchar(10),
wirknetz varchar(10),
wf_igz int(11) NOT NULL default 0,
tarifcode varchar(80) default NULL,
recycle char(1) default NULL,
sim varchar(30) default NULL,
mcbs_tpl varchar(30) default NULL,
emp_nr int(11) NOT NULL default 0,
laufzeit int(11) default NULL,
hdl_name varchar(30) default NULL,
prov_hdl_nr int(11) NOT NULL default 0,
auto_wirknetz varchar(50) default NULL,
auto_billing varchar(50) default NULL,
touch int NOT NULL,
kategorie varchar(50) default NULL,
kundentyp varchar(20) NOT NULL default '',
sammel_rech_msisdn varchar(30) NOT NULL default '',
p_nr varchar(9) NOT NULL default '',
suffix char(3) NOT NULL default ''
);

INSERT INTO t3 VALUES (3359356,405,3359356,'Mustermann Musterfrau',52500,20000520,'workflow','Auftrag erledigt','Originalvertrag eingegangen undgeprüft','','privat',1485525,2122316,'+','','N',1909160,'MobilComSuper92000D2',NULL,NULL,'MS9ND2',3,24,'MobilCom Shop Koeln',52500,NULL,'auto',20010202,'Mobilfunk','PP','','','');
INSERT INTO t3 VALUES (3359357,468,3359357,'Mustermann Musterfrau',7001,20000520,'workflow','Auftrag erledigt','Originalvertrag eingegangen undgeprüft','','privat',1503580,2139699,'+','','P',1909171,'MobilComSuper9D1t30SFreisprech(Akquise)',NULL,NULL,'MS9NS1',327,24,'MobilCom Intern',7003,NULL,'auto',20010202,'Mobilfunk','PP','','',''); 
INSERT INTO t3 VALUES (3359358,407,3359358,'Mustermann musterfrau',7001,20000520,'workflow','Auftrag erledigt','Originalvertrag eingegangen undgeprüft','','privat',1501358,2137473,'N','','N',1909159,'MobilComSuper92000D2',NULL,NULL,'MS9ND2',325,24,'MobilCom Intern',7003,NULL,'auto',20010202,'Mobilfunk','PP','','',''); 
INSERT INTO t3 VALUES (3359359,468,3359359,'Mustermann musterfrau',7001,20000520,'workflow','Auftrag erledigt','Originalvertrag eingegangen undgeprüft','','privat',1507831,2143894,'+','','P',1909162,'MobilComSuper9D1t30SFreisprech(Akquise)',NULL,NULL,'MS9NS1',327,24,'MobilCom Intern',7003,NULL,'auto',20010202,'Mobilfunk','PP','','',''); 
INSERT INTO t3 VALUES (3359360,0,0,'Mustermann Masterfrau',29674907,20000520,'workflow','Auftrag erledigt','Originalvertrag eingegangen undgeprüft','','privat',1900169997,2414578,'+',NULL,'N',1909148,'',NULL,NULL,'RV99066_2',20,NULL,'POS',29674907,NULL,NULL,20010202,'Mobilfunk','','','97317481','007');
INSERT INTO t3 VALUES (3359361,406,3359361,'Mastermann Masterfrau',7001,20000520,'workflow','Auftrag storniert','','(7001-84):Storno, Kd. möchte nichtmehr','privat',NULL,0,'+','','P',1909150,'MobilComSuper92000D1(Akquise)',NULL,NULL,'MS9ND1',325,24,'MobilCom Intern',7003,NULL,'auto',20010202,'Mobilfunk','PP','','',''); 
INSERT INTO t3 VALUES (3359362,406,3359362,'Mustermann MusterFrau',7001,20000520,'workflow','Auftrag erledigt','Originalvertrag eingegangen undgeprüft','','privat',1509984,2145874,'+','','P',1909154,'MobilComSuper92000D1(Akquise)',NULL,NULL,'MS9ND1',327,24,'MobilCom Intern',7003,NULL,'auto',20010202,'Mobilfunk','PP','','',''); 

select username from t3 where username like '_aster%';
Empty set (0.00 sec)

### Expected Behavior

select username from t3 where username like '_aster%';
+-----------------------+
| username              |
+-----------------------+
| Mastermann Masterfrau |
+-----------------------+
1 row in set (0.00 sec)

**Comment by m-schen** [comment]
fixed. and will commit the code soon.

**Comment by m-schen** [comment]
fixed in main
