### ISSUE TITLE
[Tech Request]: remove doRevokePrivilegeImplicitly and doGrantPrivilegeImplicitly in backgound session

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#15885]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
不要在backgound session 中执行grant和revoke。
```

### Why is this needed ?

按照原先的设计background session 不执行权限类语句。保持简单

**Comment by YANGGMM** [comment]
fixed

**Comment by daviszhen** [comment]
换成了在同一个事务中执行doRevokePrivilegeImplicitly和 doGrantPrivilegeImplicitly。
