### ISSUE TITLE
[Bug]: from_base64 function some results different from mysql

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15904]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

10400a9a8af79ba815fa1ff7f092cfbaf82b7de1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.from_base64 argument is not a valid base-64 string reported error,but mysql return null
mo:
mysql> select from_base64('@#%#$^jfe12');
ERROR 1105 (HY000): illegal base64 data at input byte 0
mysql> select  from_base64(-123);
ERROR 1105 (HY000): illegal base64 data at input byte 0

mysql:
<img width="613" alt="企业微信截图_3df526d1-6be4-445d-9330-72f0d6eeeb2d" src="https://github.com/matrixorigin/matrixone/assets/113406637/8c13d6ad-8e8b-447f-baf2-5bfb3d767b50">
<img width="482" alt="企业微信截图_8b9d51e1-35c1-4a3e-92a5-09d37e32a292" src="https://github.com/matrixorigin/matrixone/assets/113406637/6e219dde-d10a-44b6-8534-d35263cef063">

2.from_base64('') result is different from mysql
mo:
mysql> select from_base64('');
+---------------+
| from_base64() |
+---------------+
|               |
+---------------+
1 row in set (0.00 sec)
mysql:
<img width="395" alt="企业微信截图_c2604093-4db1-49f0-bd85-66d8d9317b9e" src="https://github.com/matrixorigin/matrixone/assets/113406637/04f89490-0813-416b-93e6-aaf3342ebb0d">

### Steps to Reproduce

```Markdown
select from_base64('@#%#$^jfe12');
select  from_base64(-123);
select from_base64('');
```

**Comment by arjunsk** [comment]
This PR will fix this issue:
https://github.com/matrixorigin/matrixone/pull/15924

The BVT changes are attached here

![image](https://github.com/matrixorigin/matrixone/assets/9638314/0d66f848-3105-4335-b5db-88e0278d9290)

**Comment by arjunsk** [comment]
merged to master.

**Comment by heni02** [comment]
confirm, closed
