### ISSUE TITLE
[Bug]: data race occurred during TestGlobalCheckpoint2 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15916]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/8999998207/job/24723333659?pr=15900

[log.txt](https://github.com/matrixorigin/matrixone/files/15247830/log.txt)

### Steps to Reproduce

```Markdown
run ut
```

**Comment by gouhongshen** [comment]
fixed

**Comment by heni02** [comment]
closed
