### ISSUE TITLE
[Bug]: ut TestWatchDirty failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15918]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9000629984/job/24725207360?pr=15894

[log.txt](https://github.com/matrixorigin/matrixone/files/15248541/log.txt)

### Steps to Reproduce

```Markdown
run ut
```

**Comment by jensenojs** [comment]
repro : https://github.com/matrixorigin/matrixone/actions/runs/9026916852/job/24805026132?pr=15957#logs

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by aptend** [comment]
no progress yet

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9644744574/job/26597467528?pr=17126

**Comment by aptend** [comment]
Hold on

**Comment by aptend** [comment]
Hold on ：)))

**Comment by aptend** [comment]
Hold on ：)))

**Comment by aptend** [comment]
this test has been skipped for now

**Comment by aptend** [comment]
this test has been skipped for now

**Comment by aptend** [comment]
not working on this

**Comment by fengttt** [comment]
TestDedupSnapshot3 may also fail.

**Comment by aptend** [comment]
waiting for repro

**Comment by aptend** [comment]
waiting for repro

**Comment by aptend** [comment]
working on it

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/10362194915/job/28683775520?pr=18059

**Comment by aptend** [comment]
It's done, I guess

**Comment by aptend** [comment]
fixed

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/10678000327/job/29594191254?pr=18490

**Comment by ouyuanning** [comment]
好像又超时
