### ISSUE TITLE
[Bug]: pub and sub improvement  bvt test incorrect result

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#15928]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="929" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/5e3bbd8f-f831-47ad-a22a-b3e84fe5116e">

### Steps to Reproduce

```Markdown
can see the case in test/distributed/cases/publication_subscription/pub_sub_improvment.sql
```

**Comment by Ariznawlll** [comment]
in progress
