### ISSUE TITLE
[Bug]:  ut TestReLockSuccWithLockTableBindChanged  failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15921]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9000428197/job/24727172156?pr=15716

[Uploading job-logs.txt…]()

### Steps to Reproduce

```Markdown
run ut
```

**Comment by daviszhen** [comment]
又出现了。
https://github.com/matrixorigin/matrixone/actions/runs/9015985674/job/24771696686?pr=15908

**Comment by daviszhen** [comment]
![Screenshot from 2024-05-09 19-18-57](https://github.com/matrixorigin/matrixone/assets/60595215/166f0b3d-151b-4e79-bca7-2c4f2086820c)

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9016573451/job/24773445730?pr=15908

**Comment by iamlinjunhong** [comment]
死锁检测，加锁，解锁并发，导致内存泄漏，正在解决
