### ISSUE TITLE
[Bug]:  merge run failed frequently caused by 'connection closed'

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#15939]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dea366b31f593cdc7fcf890feba0b898facf0554

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9007728379

### Steps to Reproduce

```Markdown
mergerun test
```

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/MO-Cloud/issues/3217

**Comment by sukki37** [comment]
#15777 may cause a huge increase in `in-use objects` of frontend, which in turn will lead to an increase in CPU consumption by GC marking, causing the MO lockservice to be unable to obtain CPU in time, ultimately resulting in a timeout.

<img width="1875" alt="企业微信截图_89e619c5-ecf1-4f77-ad24-bbc315a74954" src="https://github.com/matrixorigin/matrixone/assets/77312370/4158ab37-9910-4faa-ab15-de50dfd9bb35">

![Uploading 企业微信截图_7c47c58f-3c2f-4cfb-aae9-241b7e193b3f.png…]()

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22M_o%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-15777%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221715201340000%22,%22to%22:%221715201400000%22%7D%7D,%22I-K%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-15910%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221715198880000%22,%22to%22:%221715198940000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
等系统变量重构完成后就可以关掉了

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
#https://github.com/matrixorigin/matrixone/pull/16551 have solved this problem

**Comment by heni02** [comment]
#15777 导致该问题的pr已经revert，之后重新提重构的pr #16551 合并后没有该问题了，关闭
