### ISSUE TITLE
[Bug]: bvt test report internal error: Invalid checkpoints for snapshot read,snapshot:1715253508110935163-0, start:0-0, end:1715253268385841979-0 in ci.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15951]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

946e23f09313480104b695391d23f5e290cdf6f3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:
https://github.com/matrixorigin/matrixone/actions/runs/9016372693/job/24772908533?pr=15949
<img width="1040" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e827903f-5c04-4333-9423-a69a283dd19b">

log：
[Standalone-e2e-BVT-Test-on-Linux-x64(LAUNCH,Optimistic)-reports.zip](https://github.com/matrixorigin/matrixone/files/15262361/Standalone-e2e-BVT-Test-on-Linux-x64.LAUNCH.Optimistic.-reports.zip)
[Compose-multi-cn-e2e-bvt-test-docker-log(Optimistic,PUSH).zip](https://github.com/matrixorigin/matrixone/files/15262376/Compose-multi-cn-e2e-bvt-test-docker-log.Optimistic.PUSH.zip)

### Steps to Reproduce

```Markdown
trigger ci test.
```

**Comment by triump2020** [comment]
Fixed

**Comment by Ariznawlll** [comment]
verified
