### ISSUE TITLE
[Bug]: cluster table restore

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15954]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

44a4d5e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="493" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/32370a8a-f029-4788-b590-4f467f65548c">

<img width="532" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e8bc15d7-388e-41fb-9627-6c1bd6e09fc4">

### Steps to Reproduce

```Markdown
场景1:
use mo_catalog;
create cluster table clu01(col1 int, col2 decimal);
insert into clu01 values(1,2,0);

drop snapshot if exists sp01;
create snapshot sp01 for account sys;
insert into clu01 values(2,3,0);

restore account sys from snapshot sp01;

select * from clu01;  -->结果不对



场景2:
create table clu01(col1 int, col2 decimal);
insert into clu01 values(1,2);

drop snapshot if exists sp01;
create snapshot sp01 for account sys;
insert into clu01 values(2,3);

restore account sys from snapshot sp01;

select * from clu01;  -->结果不对
 select count(*) from clu01;   -->结果不对
```

**Comment by YANGGMM** [comment]
现在集群表的恢复还没有结论

**Comment by YANGGMM** [comment]
场景2 跟之前几个issue场景重复https://github.com/matrixorigin/matrixone/issues/15953

**Comment by YANGGMM** [comment]
场景2:fixed by https://github.com/matrixorigin/matrixone/pull/15937

**Comment by YANGGMM** [comment]
重新提一个集群表的issue

**Comment by Ariznawlll** [comment]
commit：7922426e3effea12dbe900af0daf02a308d9f031
<img width="434" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1417eb00-be4f-4413-accf-4412b4c5c60c">
verified
