### ISSUE TITLE
[Bug]: create a table and insert data, then create a snapshot,  then insert data, the result of select * is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15953]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

44a4d5e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="796" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d91960d5-92ca-4f4b-85e6-36f2b823d473">

### Expected Behavior

第一次执行结果 ：1

### Steps to Reproduce

```Markdown
drop table if exists test01;
create table test01(col1 int, col2 char);
insert into test01 values(1,2);

drop snapshot if exists sp01;
create snapshot sp01 for account sys;
select * from test01{snapshot = 'sp01'};   -->第一次执行是null，多执行几次就正常了
```

**Comment by triump2020** [comment]
duplicate with #15907

**Comment by triump2020** [comment]
@Ariznawlll Fixed.

**Comment by Ariznawlll** [comment]
commit :4d44f7247b8f480013f21cfd5758a59abf739cd7

<img width="562" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/487eb1eb-c3ea-450f-b460-67fd56673045">

verified
