### ISSUE TITLE
[Bug]: The error information for recovering the publication table needs to be optimized.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15952]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

44a4d5e8d7fe5d6748fc0bc3da6e7161bd821b9e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="704" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/142c7eb5-24cb-4cb2-b760-cd9de9e826a8">

### Steps to Reproduce

```Markdown
drop database if exists test02;
create database test02;
use test02;
drop table if exists rs02;
create table rs02 (col1 int, col2 datetime);
insert into rs02 values (1, '2020-10-13 10:10:10');
insert into rs02 values (2, null);
insert into rs02 values (1, '2021-10-10 00:00:00')
drop account if exists test_tenant_1;
create account test_tenant_1 admin_name 'test_account' identified by '111';
create publication publication01 database test02 account test_tenant_1 comment 'publish database to account01';

drop snapshot if exists sp02;
create snapshot sp02 for account sys;
restore account sys from snapshot sp02;   -->报错的sql
```

**Comment by ck89119** [comment]
还没开始看

**Comment by ck89119** [comment]
restore account时，会先删除现在所有db，如果某个db是publishing状态，就会出现这个报错。
等待产品确认published db的恢复行为再修。

**Comment by YANGGMM** [comment]
已经在 https://github.com/matrixorigin/matrixone/pull/16448 中修掉

**Comment by Ariznawlll** [comment]
**commit: 876ce1a4d63dbe03ae3985a28eaf354bbba18679**
<img width="507" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6244c366-5dbe-4c9d-a0ea-b443675be2e8">

verified.
