### ISSUE TITLE
[Bug]: [date 5.9] tke regression: tpcc 1000warehouse 1000threads connection  timeout

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15960]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1aed8d948

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9019459807/job/24803217074
<img width="1135" alt="企业微信截图_0d41e70f-2e84-472f-a15f-005c936be999" src="https://github.com/matrixorigin/matrixone/assets/113406637/b77cd111-bf6d-4bd7-a1c6-05bfc6511e09">

The tke  environment did not restart
<img width="829" alt="企业微信截图_333a5019-cc47-477b-8e0c-4b7db32d5db7" src="https://github.com/matrixorigin/matrixone/assets/113406637/1cbe67c8-38ca-4093-8d1d-dd15372b7c24">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240509%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715283409000%22,%22to%22:%221715283420000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile：
[linktimeout_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/15269905/linktimeout_profile.tar.gz)

### Steps to Reproduce

```Markdown
tke regression tpcc 1000warehouse 1000threads test
```

**Comment by aressu1985** [comment]
update on 5.11
commit id: b5c2eaa（1.2-dev）

also in tpcc 100 warehouse 1000 terminals

<img width="1402" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/02f6bd80-fcda-4b1f-8eb4-fb1efb2eb066">

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9035308966/job/24831847809

**Comment by sukki37** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240509%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715283406618%22,%22to%22:%221715283419976%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by sukki37** [comment]
> update on 5.11 commit id: [b5c2eaa](https://github.com/matrixorigin/matrixone/commit/b5c2eaaf9209dd5209e749219a89ea3ec0503f74)（1.2-dev）
> 
> also in tpcc 100 warehouse 1000 terminals
> 
> <img alt="image" width="1402" src="https://private-user-images.githubusercontent.com/47846308/329748328-02f6bd80-fcda-4b1f-8eb4-fb1efb2eb066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTU5NDYsIm5iZiI6MTcxNTM5NTY0NiwicGF0aCI6Ii80Nzg0NjMwOC8zMjk3NDgzMjgtMDJmNmJkODAtZmNkYS00YjFmLThlYjQtZmIxZWZiMmViMDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAyNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNGNkNjRlMTZlMTJmOTJlNzZkMjYwMDA4N2Q5NzI4YTZhNzc1YzhhMTdhOTQ1OGU2Mjc0MjBhYzU0ODhlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vYVMbyVNm8gldvc_-JmldyqEm4RfXnmoXy-u2JdKcp8">
> job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9035308966/job/24831847809

@volgariver6 The issue here is also that when there's a problem, the proxy reports an error indicating a failure to write to the client.

10.143.198.17: client ip


https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-b5c2eaa%5C%22%7D%20%7C%3D%20%60ERROR%60%20%21%3D%20%60invalid%20argument%20function%20prefix_in%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715369833563%22,%22to%22:%221715369834420%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
@daviszhen will help to fix it.

**Comment by daviszhen** [comment]
it was fixed.

**Comment by aressu1985** [comment]
not  fixed

update on 5.13
commit it: 7bc191e  (1.2-dev)


<img width="1347" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/4b163bd0-3316-48a5-91ad-23b99a092cc7">


job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9052676441/job/24871224919

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22DjJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-7bc191e%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715537718000%22,%22to%22:%221715538643000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by heni02** [comment]
main commit：b88a2b8e1
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9064806413/job/24907214817
<img width="1107" alt="企业微信截图_ff01335f-1969-478f-8927-05c4f374232a" src="https://github.com/matrixorigin/matrixone/assets/113406637/c3aef214-c74d-46bb-a1d1-b4a31072aeaa">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22LTv%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240513%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715625892000%22,%22to%22:%221715625893000%22%7D%7D%7D&schemaVersion=1&orgId=1

这个时间段内内存使用情况，3个cn都没有超过50G
<img width="1429" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/048dcece-0b86-4b0b-8c78-a176482f649e">
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20240513&from=1715612144572&to=1715654454026

**Comment by daviszhen** [comment]
![Selection_001](https://github.com/matrixorigin/matrixone/assets/60595215/e543b358-b2eb-49a6-bbd3-de62c1c5d627)

**Comment by daviszhen** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22LTv%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240513%5C%22%7D%20%7C~%20%60connectionId%2023064%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715623252000%22,%22to%22:%221715626253000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22LTv%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240513%5C%22%7D%20%7C~%20%60%28%3Fi%29Failed%20to%20send%20response%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715625892000%22,%22to%22:%221715625893000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9064407826/job/24919544811
branch：1.2-dev
commitid：939743759dfad6245f30d130f186ba3c45bfcd43

metric：
https://grafana.ci.matrixorigin.cn/d/a24c5b82-0f61-407d-a318-c253de17583d/logtail-metrics?orgId=1&var-interval=1m&var-namespace=mo-branch-reg-9397437&var-pod=All&from=1715616000000&to=1715623799000

log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-9397437%5C%22%7D%20%7C%3D%20%60018f72e696007c55af33e4839af9bc6d%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715618212693%22,%22to%22:%221715622148693%22%7D%7D,%22_t3%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-9397437%5C%22%7D%20%7C%3D%20%60018f72e6798472818849f6c57607dd14%60%20%21%3D%20%60wait%20too%20long%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:10000%7D%5D,%22range%22:%7B%22from%22:%221715618212693%22,%22to%22:%221715622148693%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by reusee** [comment]
从metrics看，17:09:00 时，p99 apply-latency 是 23.9s，apply是4.66ms，说明logtail的数量很多。
17:08:00-17:08:30 的 apply queue 达到 4.81k和8.22k。
到了 17:09:00，apply queue 降到了 4，说明logtail已经消费完毕。30秒消费8.22k，平均3ms左右消费一个logtail，正常范围。
问题应是，为什么会有突发的这么多logtail。

观察到一个现象，logtail collect duration 在 17:01:30 开始波动。17:01:30 产生了一个尖峰，然后在 17:03:30 开始变成低谷，这个低谷一直持续到 17:10:00。这个时间段刚好对应上面的 cn 的 logtail 数量尖峰。
一个猜测是，dn 在这段时间内，累积了很多 logtail，然后集中发送，于是 cn 侧产生了比较长的队列。至少可以确定的是，dn 先于 cn 发生异常波动。

在 17:03:30，cn 侧的 logtail consume 累积时间达到 8.55s，这个时候的 apply queue 是 1.83k，平均是 4ms 左右消费一个logtail，消费速度正常。问题仍然是突发的logtail数量。

**Comment by aressu1985** [comment]
update on 5.20
commit : 5522522
job link:
https://github.com/matrixorigin/matrixone/issues/15960

<img width="1420" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/97c5b57e-363a-4592-bba2-e57cecb4dd74">

and there is a long running error in this period:
<img width="1366" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/42073cca-1d5c-488f-811b-d0a0d63f0309">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22rGD%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-5522522%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716169792432%22,%22to%22:%221716171770614%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by reusee** [comment]
> update on 5.20 commit : [5522522](https://github.com/matrixorigin/matrixone/commit/5522522b56e583e751d345dcc6074981c98a4ef0) job link: #15960
> 
> <img alt="image" width="1420" src="https://private-user-images.githubusercontent.com/47846308/331938364-97c5b57e-363a-4592-bba2-e57cecb4dd74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzg5NDgsIm5iZiI6MTcxNjE3ODY0OCwicGF0aCI6Ii80Nzg0NjMwOC8zMzE5MzgzNjQtOTdjNWI1N2UtMzYzYS00NTkyLWJiYTItZTU3Y2VjYjRkZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMWM3OWNmODFkMzg3ODFlNDlhZGNmYTZmMGE5NDBkOWI2MzZkY2QxMzVmNTQ5MzI0NmUxN2U4ZGQ0ZmVmMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GD0rSXpDJQuauepDeaw6JhvlNzqUmVhb2owWg2o1YVc">
> and there is a long running error in this period: <img alt="image" width="1366" src="https://private-user-images.githubusercontent.com/47846308/331938929-42073cca-1d5c-488f-811b-d0a0d63f0309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzg5NDgsIm5iZiI6MTcxNjE3ODY0OCwicGF0aCI6Ii80Nzg0NjMwOC8zMzE5Mzg5MjktNDIwNzNjY2EtMWQ1Yy00ODhmLTgxMWItZDBhMGQ2M2YwMzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ODE5MjQxMzc4NmFhNjY0YTUwYjI4YmY1MGI5NjQxN2ZkOTk2N2Y3MTUxNTZkZTM2MmU1ZGVhYTVlNjhlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGNW_G3lY7zjSWxGmaBkE50CxUqTUqFrLku2R6GtK-4">
> 
> and the txn queues status and txn creation / commit rt p99 is unnormal: <img alt="image" width="1426" src="https://private-user-images.githubusercontent.com/47846308/331939502-32c20d77-8e13-403a-b29a-c380e5b86d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzg5NDgsIm5iZiI6MTcxNjE3ODY0OCwicGF0aCI6Ii80Nzg0NjMwOC8zMzE5Mzk1MDItMzJjMjBkNzctOGUxMy00MDNhLWIyOWEtYzM4MGU1Yjg2ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZTY4ZWMyNmU5MjY0Y2Q2YzhhMDllODQyYTkzODk1OWJkNjJmZGQ1Mzg2M2VkMTRmN2I4N2M4NDc0MGZjMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t5YJyK6KBFKzyzAaj8JOnCyul-AdNLwIotwH8Jo9Vjs">
> 
> mo-log link: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22rGD%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-5522522%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716169792432%22,%22to%22:%221716171770614%22%7D%7D%7D&schemaVersion=1&orgId=1
> 
> txn dashbaord link: https://grafana.ci.matrixorigin.cn/d/b66fd46c-534a-48dd-a395-db16785e3919/txn-metrics?orgId=1&var-interval=1m&var-namespace=mo-branch-reg-5522522&var-pod=All&from=1716135763000&to=1716147043000

https://grafana.ci.matrixorigin.cn/d/b8e7b5e4-1d06-41bd-a1d0-a17eba7bee9e/logtail-metrics?orgId=1&from=1716134400000&to=1716148800000&var-interval=1m&var-namespace=mo-branch-reg-5522522&var-pod=All

这次复现的logtail状况是，大部分apply时间在几ms，偶发几次200ms到400ms的apply。7点半左右，cn收到的logtail数量暴增，但apply queue没有堆积，消费速度正常。
从apply queue的情况来看，logtail消费不是瓶颈，不是问题的根源。

**Comment by aressu1985** [comment]
long running go routine file:

[Uploading routine_018f93c1-1e9f-76b1-b13e-b52300b44cd7.txt…]()

**Comment by reusee** [comment]
not working  on this

**Comment by reusee** [comment]
not working on this

**Comment by reusee** [comment]
not working on this

**Comment by aressu1985** [comment]
fixed
