### ISSUE TITLE
[Bug]: lots of "ERROR 2003 (HY000): Can't connect to MySQL server on" in tpch queries during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#15963]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2eeef92

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed mode, there lots of "ERROR 2003 (HY000): Can't connect to MySQL server on..." in tpcc queries:
<img width="1048" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/93fa720c-0a3d-429d-bf2c-30accf14d2eb">

mo-tpch tools log:
[tpch.log](https://github.com/matrixorigin/matrixone/files/15269986/tpch.log)

but there were no proxy or cn crashed duiring test
<img width="757" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d5a23c16-fb47-4358-9486-793f4004e9b2">

And the account is `tpch_test` for tpch queries,, after searching this account name in log , there were no any error message for this account in cn:
<img width="1338" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/45814898-049b-4caa-91a7-dac6bbcc56ba">

so maybe there were something wrong in proxy.

mo-log:

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22PBJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-2eeef92-20240509232129%5C%22%7D%20%7C%3D%20%60tpch_test%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715268600000%22,%22to%22:%221715313599000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode, long conneciton
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode,short connnection
```

**Comment by volgariver6** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22PBJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-2eeef92-20240509232129%5C%22,%20matrixorigin_io_component%3D%5C%22ProxySet%5C%22%7D%20%21%3D%20%60gc%60%20%21%3D%20%60DEBUG%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221715308557000%22,%22to%22:%221715308560000%22%7D%7D%7D&schemaVersion=1&orgId=1

从日志看，在10:35:58 时间，proxy没有收到任何的请求，怀疑是网络问题导致的

**Comment by guguducken** [comment]
10:35:58时间较短，服务只有不到一秒的无法连接，或许可以看看2024-05-09 23:42:10到2024-05-09 23:42:12之间的情况。
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22DQF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-2eeef92-20240509232129%5C%22,%20matrixorigin_io_component%3D%5C%22ProxySet%5C%22%7D%20%7C%3D%20%60new%20connection%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715269330000%22,%22to%22:%221715269332000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
@guguducken please comment the conclusion and forward it back to @aressu1985

**Comment by guguducken** [comment]
**根因**：客户端 ipv4.tcp_tw_reuse 设置为2，只对本地回环地址的timewait socket进行重用，短连接激增时会导致无法创建

复现过程：
1. 启动sysbench开始短连接测试
2. 通过命令观察mo服务端口的可连通性
    ~~~bash
    while true; do mysql -h 10.222.1.132 -udump -P30015 -p111 -e 'select 1;' > /dev/null;sleep 1; done
    ~~~
3. 经过一段时间后，会产生报错
    ~~~bash
    ERROR 2003 (HY000): Can't connect to MySQL server on '10.222.1.132:30015' (99)
    ~~~

排查过程：
1. 尝试直接proxy pod，发现没有问题
2. 修改service type，使用nodePort，测试后仍然有问题
3. 修改服务端集群中节点(132,134)的内核参数，其中包括
    ~~~bash
    ulimit -n 65535
    sysctl net.ipv4.tcp_tw_reuse=1
    sysctl net.ipv4.tcp_fin_timeout=5
    ~~~
4. 在节点132，134上使用tcpdump抓包分析网络流量，检查是否是cni的问题
5. 重启节点132，134
6. 再次复现，通过`ss -s`观察到出问题是服务端timewait较少，但是客户端timewait数量激增
7. 增加对照客户端，使用复现过程中测试可连通性的脚本测试mo集群的连通性，并持续观察客户端timewait数量情况
8. 修改客户端内核参数`net.ipv4.tcp_tw_reuse=1`，并再次测试尝试复现
9. 修改内核参数后测试不再报错

**Comment by aressu1985** [comment]
fixed
