### ISSUE TITLE
necessary metadata for string BSI

### ISSUE THREAD

**Issue by zzl200012** [matrixorigin/matrixone#1596]
For string BSI, we need 1) `length` that indicates the **maximum number of characters** you want to store within a **CHAR** 2) `width` that indicates **how many bits that one character consists**, from upper layer. Please add those fields and clarify how to get them.

**Comment by XuPeng-SH** [comment]
Hi @jiangxinmeng1, do we already support the **CHAR** type?

**Comment by zzl200012** [comment]
No extra metadata needed. We use 8 bits per character temporarily.
