### ISSUE TITLE
[Bug]: create db and table ,insert data, create snapshot, drop db, select * from table{snapshot = ''} report 'ERROR 1046 (HY000): not connect to a database'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15962]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

44a4d5e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="446" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/eca15646-b4f4-4c13-88df-b510616f250a">

### Expected Behavior

db和表还在

### Steps to Reproduce

```Markdown
drop database if exists test03;
create database test03;
use test03;

create table t1(col1 int);
insert into t1 values(1),(2),(3);
select count(*) from t1;

drop snapshot if exists sp01;
create snapshot sp01 for account sys;

drop database test03;
select * from t1{snapshot = 'sp01'};    -->此处报错
```

**Comment by YANGGMM** [comment]
这不是一个bug

**Comment by Ariznawlll** [comment]
查询的时候需要带上db_name
<img width="623" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/dc36fe51-7d5b-4a07-a521-70c0652a7d0c">
