### ISSUE TITLE
[Bug]: [date 5.9]standalone regression: sysbench 1000w random_point 100threads mo oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15975]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2eeef9246a17f1dfe7265f911976caa68626defc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9019462365/job/24803638553
<img width="1103" alt="企业微信截图_8d25a2b1-3752-4932-be6d-ce2b3ddc78fc" src="https://github.com/matrixorigin/matrixone/assets/113406637/468ef8a8-51ae-43ef-ada6-ffd06c6aad49">
<img width="1302" alt="企业微信截图_2cdab3cf-6512-4d74-b411-bc28a7d868ca" src="https://github.com/matrixorigin/matrixone/assets/113406637/8240da25-3551-42f5-9a2e-138c52893c58">

查看这个时间段内存12:34已经到288G(服务器251G）
<img width="1101" alt="企业微信截图_1a4fb79b-2074-4010-be5c-ec0c027fcb26" src="https://github.com/matrixorigin/matrixone/assets/113406637/bf7748bc-6cee-4f4b-b13a-fdbb2d608bc3">

再看之前11:49内存已经到246G，发现整个sysench 1000w流程内存资源一直在上涨
<img width="1101" alt="企业微信截图_dcc34e74-9328-47e1-bcdb-8070dc2d3385" src="https://github.com/matrixorigin/matrixone/assets/113406637/1bca225e-e1cc-406c-839d-2c4b2bb0b2b6">

12:31和12:33时间的profile：
[OOM.tar.gz](https://github.com/matrixorigin/matrixone/files/15271170/OOM.tar.gz)

log plz contact me 

### Steps to Reproduce

```Markdown
standalone sysbench 1000w test
```

**Comment by qingxinhome** [comment]
我先分析一下出错的位置

**Comment by ouyuanning** [comment]
从跟喜亮看的heap来看，应该是parser内存释放问题

**Comment by ouyuanning** [comment]
估计跟#3228是一个问题

**Comment by heni02** [comment]
date 5.14 regression还是有oom情况
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9081092392/job/24954310140
<img width="1114" alt="企业微信截图_9089c5d3-7f06-4ee0-91ca-d9baf914b7d0" src="https://github.com/matrixorigin/matrixone/assets/113406637/37faea93-c27d-4709-be70-eb7e137fcc2d">
mo oom：
<img width="1738" alt="企业微信截图_7dd98a01-a471-430b-9215-68da3731bfda" src="https://github.com/matrixorigin/matrixone/assets/113406637/6464cac3-8d63-4efa-be99-9d37227109b8">

profile：
[2024-05-15_01_22_41.zip](https://github.com/matrixorigin/matrixone/files/15315837/2024-05-15_01_22_41.zip)

mo log plz contact me

**Comment by heni02** [comment]
这个pr合进去后，昨天main没有出现oom，但有连接失败，报错时间的内存占用225G
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9097455949/job/25005513964
<img width="1160" alt="企业微信截图_5ec41631-c066-4df4-bec1-dce8ed8ce542" src="https://github.com/matrixorigin/matrixone/assets/113406637/e7217a7a-c1ab-4414-b7a3-78d807f31f1a">
<img width="1104" alt="企业微信截图_4ed5021b-ef34-47e6-9101-563b9fb9d9a1" src="https://github.com/matrixorigin/matrixone/assets/113406637/2123587d-3a67-4b5a-b1af-925ca8af0743">

profile:
[main_profile_0516.tar.gz](https://github.com/matrixorigin/matrixone/files/15328959/main_profile_0516.tar.gz)

mo log plz contact me

**Comment by heni02** [comment]
oom的情况回归再观察两天

**Comment by daviszhen** [comment]
等hung问题解决后，再继续测试

**Comment by daviszhen** [comment]
等profile抓取正常后，再分析。

**Comment by heni02** [comment]
最近回归再没有出现，先降级再观察看看

**Comment by daviszhen** [comment]
disttae block reader 
vector. UnionAll

![Selection_064](https://github.com/matrixorigin/matrixone/assets/60595215/9793acb5-d5dc-4240-87ef-5079b5e15198)

**Comment by daviszhen** [comment]
一直有tpcc oom

**Comment by sukki37** [comment]
tracked by #https://github.com/matrixorigin/matrixone/issues/16617 and its subtasks
