### ISSUE TITLE
[Bug]: restore report 'panic'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#15971]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

44a4d5e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="895" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2aa1d58f-9d53-4ee7-b16b-c5c0f22b679c">

### Expected Behavior

restore success

### Steps to Reproduce

```Markdown
drop table if exists pri01;
create table pri01(
                     deptno int unsigned comment '部门编号',
                     dname varchar(15) comment '部门名称',
                     loc varchar(50)  comment '部门所在位置',
                     primary key(deptno)
) comment='部门表';

insert into pri01 values (10,'ACCOUNTING','NEW YORK');

drop table if exists aff01;
create table aff01(
                    empno int unsigned auto_increment COMMENT '雇员编号',
                    ename varchar(15) comment '雇员姓名',
                    job varchar(10) comment '雇员职位',
                    mgr int unsigned comment '雇员对应的领导的编号',
                    hiredate date comment '雇员的雇佣日期',
                    sal decimal(7,2) comment '雇员的基本工资',
                    comm decimal(7,2) comment '奖金',
                    deptno int unsigned comment '所在部门',
                    primary key(empno),
                    constraint `c1` foreign key (deptno) references pri01 (deptno)
);

select count(*) from pri01;
select count(*) from aff01;

drop snapshot if exists sp04;
create snapshot sp04 for account sys;

restore account sys from snapshot sp04;
```

**Comment by Ariznawlll** [comment]
restore to new account也报panic，看了一下报错的提示基本上是一样的

internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/panic.go:261
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/signal_unix.go:881
github.com/matrixorigin/matrixone/pkg/sql/plan.buildShowCreateTable
	/Users/ariznawl/wl_123/matrixone/pkg/sql/plan/build_show.go:332
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan
	/Users/ariznawl/wl_123/matrixone/pkg/sql/plan/build.go:140
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize
	/Users/ariznawl/wl_123/matrixone/pkg/sql/plan/optimize.go:56
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:1963
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/computation_wrapper.go:244
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtInBack
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/back_exec.go:363
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2529
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2498
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2468
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2382
github.com/matrixorigin/matrixone/pkg/frontend.doComQueryInBack
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/back_exec.go:318
github.com/matrixorigin/matrixone/pkg/frontend.(*backExec).Exec
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/back_exec.go:98
github.com/matrixorigin/matrixone/pkg/frontend.getStringColsList
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:594
github.com/matrixorigin/matrixone/pkg/frontend.getCreateTableSql
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:689
github.com/matrixorigin/matrixone/pkg/frontend.getTableInfos
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:657
github.com/matrixorigin/matrixone/pkg/frontend.restoreToDatabaseOrTable
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:394
github.com/matrixorigin/matrixone/pkg/frontend.restoreToDatabase
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:340
github.com/matrixorigin/matrixone/pkg/frontend.restoreToAccount
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:332
github.com/matrixorigin/matrixone/pkg/frontend.doRestoreSnapshot
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/snapshot.go:316
github.com/matrixorigin/matrixone/pkg/frontend.handleRestoreSnapshot
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:1263
github.com/matrixorigin/matrixone/pkg/frontend.execInFrontend
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/self_handle.go:359
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2559
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2527
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2498
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2468
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2382
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2351
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2896
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/mysql_cmd_executor.go:2970
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/Users/ariznawl/wl_123/matrixone/pkg/frontend/routine.go:285

复现过程：
1. 通过命令./run.sh -n -g -p /path/matrixone/test/distributed/cases/snapshot/sys_restore_to_newnonsys_account.sql -m genrs生成.result文件
2. 查看.result文件

**Comment by ck89119** [comment]
还没开始看

**Comment by ck89119** [comment]
issue提到的问题已修复，不过除了这个还有表重建顺序的问题，带外键的表必须在依赖表建完之后再执行重建，开发中

**Comment by ck89119** [comment]
修复已merge

**Comment by Ariznawlll** [comment]
**commit:1fc1935201698d72c1efe9b9f242d95a974d44fb**
<img width="1006" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/17c275dd-be85-4a26-9a0f-0b59a193ae6a">

verified.
