### ISSUE TITLE
[Bug]: [date 5.9]tke regression: load data reported the table column is larger than input data column

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15979]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1aed8d948

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9019459807/job/24803217771
<img width="1021" alt="企业微信截图_28dce51e-a38c-42cf-8d4e-5493a2d920fb" src="https://github.com/matrixorigin/matrixone/assets/113406637/82e27e82-ca41-46ee-b879-1537d81d9b0a">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240509%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715317956000%22,%22to%22:%221715317980000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench 1000w update-index test
```

**Comment by ouyuanning** [comment]
错误日志：
![image](https://github.com/matrixorigin/matrixone/assets/45346669/cbaeba1b-9b52-4748-ba28-874608f78d83)

报错的代码：
<img width="1096" alt="image" src="https://github.com/matrixorigin/matrixone/assets/45346669/bae805ca-801c-4d82-a76e-4dcd6f57f061">

看着比较奇怪。这里的含义是。解析到的行中，有一个列的，本来应该是datetime类型的，但是现在它的值无法转成datetime类型。
而其实际内容是 一个 报错信息。

这个报错看着不像是load sysbench文件导入的信息。sysbench的信息应该不会有那么怪异的内容。看着倒像是log信息

**Comment by ouyuanning** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/45346669/2973eec1-b0a5-47ef-95e6-9c6b33082395)

应该有2个问题
1、在load导入的时候，发生了一次报错"the table column is larger than input data column"
<img width="846" alt="image" src="https://github.com/matrixorigin/matrixone/assets/45346669/3611e775-2df1-453d-a2af-898308ed92d6">

2、这个报错信息被记录后，被日志继续导入到另外一个地方。这个时候的报错是无法解析为datetime类型
这个部分应该是对于输入的内容的切割不对

**Comment by ouyuanning** [comment]
等这个PR  https://github.com/matrixorigin/matrixone/pull/16027  合并后再验证下

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/pull/16027
这个PR能解决2的问题。

1的部分才是关键。但是拿其中一个sbtest2.csv(2G）在本地跑了几次没有复现。

**Comment by ouyuanning** [comment]
还没时间继续看

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by ouyuanning** [comment]
近期没有复现。可能我之前的那个pr也有修复了。但是不太能确定。

**Comment by jensenojs** [comment]
待逻辑检验是否休掉了

**Comment by jensenojs** [comment]
<img width="1669" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/7393be65-85ef-45cb-a69c-e2b7f7956388">

看着当时的报错是这个sql
```sql
load data url s3option {\"endpoint\"=\"http://cos.ap-guangzhou.myqcloud.com\",\"access_key_id\"=\"******\",\"secret_access_key\"=\"******\",\"bucket\"=\"mo-load-guangzhou-1308875761\", \"filepath\"=\"sysbench_1000w_auto_index/sbtest8.csv\"}  INTO TABLE sbtest8 FIELDS TERMINATED BY \",\" lines TERMINATED BY \"\\n\" parallel \"true\"
```

**Comment by ouyuanning** [comment]
datetime类型的问题有可能已经解决掉了。是后台服务load inline的时候，转义的问题。

**Comment by jensenojs** [comment]
这个pr会在1.2.1中的load 开启严格模式
- https://github.com/matrixorigin/matrixone/pull/16907

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
一直未能复现, 可能已经被修复了, pr16907在1.2.1中加了相关日志并且开启了严格模式, 在再次复现的时候能有更多信息做诊断.

**Comment by aressu1985** [comment]
该问题单先关闭，待出夏侯，在重新提新问题跟踪
