### ISSUE TITLE
[Bug]: [date 5.9]tke regression: sysbench 1000w  random_points test cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#15982]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1aed8d948

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9019459807/job/24803217771
<img width="1056" alt="企业微信截图_b6c51930-ebb6-42d1-a3ec-6097f058389c" src="https://github.com/matrixorigin/matrixone/assets/113406637/419e2a95-bee1-4212-8ea7-9578e1fc7678">
<img width="569" alt="企业微信截图_f0762452-9353-4a5c-b400-503893acad7f" src="https://github.com/matrixorigin/matrixone/assets/113406637/9cb25929-dde0-46ed-b3f2-64d90d8482bd">

<img width="1327" alt="企业微信截图_6e3789e1-fb94-4446-be61-40191f2b3cf3" src="https://github.com/matrixorigin/matrixone/assets/113406637/e306b297-00b4-4412-842f-a9f1b9ff658b">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22qVR%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240509%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715323711161%22,%22to%22:%221715323860127%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
[sysbench_oom0510.tar.gz](https://github.com/matrixorigin/matrixone/files/15272018/sysbench_oom0510.tar.gz)

### Steps to Reproduce

```Markdown
tke regression: sysbench 1000w  test
```

**Comment by qingxinhome** [comment]
我先分析一下出错的位置

**Comment by ouyuanning** [comment]
从刚才喜亮看到的heap看，应该还是parser内存占用的问题。、

**Comment by daviszhen** [comment]
等hung问题解决后，再继续测试

**Comment by daviszhen** [comment]
未投入

**Comment by heni02** [comment]
最近没有再出现，先降级观察看看是否已经解决

**Comment by aressu1985** [comment]
update on 6.3
commit id: d36f889431fc815783f78a788b4b9951f1cc0fe2

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9338509210/job/25701703551

**Comment by daviszhen** [comment]
从6月3日后就没再复现。
