### ISSUE TITLE
[Bug]: Matrixone Upgrade CI / Compatibility Test With Release fail occasionally

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#15988]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="934" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/3de8ff4a-9538-4065-bc1a-0fb7a2fb9b87">

### Steps to Reproduce

fail link：
https://github.com/matrixorigin/matrixone/actions/runs/9029822698/job/24812932682?pr=15985

**Comment by xzxiong** [comment]
ref: https://github.com/matrixorigin/matrixone/issues/14836

**Comment by xzxiong** [comment]
repo again: https://github.com/matrixorigin/matrixone/actions/runs/9043434382/job/24853229697?pr=16027
