### ISSUE TITLE
[Bug]: retry lock for CN rolling restart is too excessive

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#15996]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

 2eeef9246

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN retry 2628 times in 0.5 seconds for a txn, which is too excessive

### Steps to Reproduce

```Markdown
https://grafana.cn-dev.matrixone.tech/goto/wwbVjaYSg?orgId=1
```

**Comment by aressu1985** [comment]
fixed
