### ISSUE TITLE
[Bug]: [date 5.10]tke regression:tpcc 500warehouses test ConsistencyCheck Read timed out

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16005]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6003d8346f0fed6e1fbd0563bc7bc2b1d2287741

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9033818759/job/24827047410
<img width="1114" alt="企业微信截图_c796cff8-ad2a-401b-bf52-e30dcf26dfd7" src="https://github.com/matrixorigin/matrixone/assets/113406637/44f41254-0bb7-4844-b5ac-465b8466b471">
另外两个500仓1000并发，1000仓1000并发也有同样的问题
超时sql：select ol_w_id, ol_d_id, ol_o_id, ol_number,count(1) from bmsql_order_line group by ol_w_id, ol_d_id, ol_o_id, ol_number having count(1) > 1 limit 10

超时sql报错日志：
<img width="1440" alt="企业微信截图_dbc3a374-10f2-4ac8-9fbe-23e4d389e77e" src="https://github.com/matrixorigin/matrixone/assets/113406637/2ef5a219-36e3-4e79-8007-9bed0e1bf0c0">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hHs%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240510%5C%22%7D%20%7C%3D%20%60from%20bmsql_order_line%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715363822488%22,%22to%22:%221715368093583%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
plz contact me

### Steps to Reproduce

```Markdown
tpcc 500warehouses 500threads test
```

**Comment by ouyuanning** [comment]
看着像是agg溢出了

**Comment by m-schen** [comment]
在处理中

**Comment by m-schen** [comment]
用这个分支跟踪这个agg结果超过1g的问题：

https://github.com/m-schen/matrixone/tree/opt-agg-result

**Comment by m-schen** [comment]
还没做完，这两天都在处理hung住的问题。

**Comment by heni02** [comment]
date 6.2 regression tpcc 500仓也出现了read timed out，和之前的sql不一样
sql：(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9339030269/job/25706499669
<img width="1270" alt="企业微信截图_d8210a84-ba73-4b4c-95f2-3c34b3f6ee03" src="https://github.com/matrixorigin/matrixone/assets/113406637/9deb56f2-faa7-4717-b5ca-50656ce3d853">

**Comment by m-schen** [comment]
上一个回复搜不到相关sql的日志，但是先关联在这里吧，总之也和聚合group by有些关系。

**Comment by m-schen** [comment]
这个需要搁置几天

**Comment by aressu1985** [comment]
这个问题是新加的一致性检查出现的问题，非REGRESSION问题，DEALY到下个版本解决

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
在改connection reset的s-1中

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
今日无投入

**Comment by m-schen** [comment]
没投入

**Comment by m-schen** [comment]
如果这周能处理好context 17226的问题的话，下周末有概率可以做完这个。

**Comment by m-schen** [comment]
近期没有投入这个

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
这个问题很久没有出现了，可能被中间许多read的优化做掉了。

然后issue中提及的agg结果过大的报错问题通过 https://github.com/matrixorigin/matrixone/issues/17640 这个issue进行跟踪。

**Comment by heni02** [comment]
confirm,closed
