### ISSUE TITLE
[Bug]: TPCC Test Errors with 'invalid argument function prefix_in, bad value [VARCHAR TUPLE]'

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16009]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

b5c2ea

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1813" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/1ede2c88-c592-4a06-85fa-a75085a1bb4a">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-b5c2eaa%5C%22%7D%20%7C%3D%20%60invalid%20argument%20function%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715363311811%22,%22to%22:%221715375978032%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run tpcc
```

**Comment by m-schen** [comment]
<img width="1285" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/fc827caf-0934-4d66-b709-8143ce766a9f">
runtime_filter 处理下推条件 in 的情况会走到这里，
该函数指定了第二个参数类型为tuple类型。

如果可以被优化成prefix_in的情况下，会在GetFunctionByName报错。具体原因如下图，prefix_in函数只支持 [varchar, varchar]这种情况，且使用的 `fixedDireclyTypeMatch` 的匹配规则，不会做类型转换。
<img width="1025" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/bf9df8e5-e7a6-45dd-b6c7-1ea232d29c9d">

prefix_eq, prefix_between也有类似的问题，不过目前似乎没有用到。

**Comment by m-schen** [comment]
cn和tn两边用的过滤逻辑不一样，（dn处只会用到传下去的function name)。

修改cn部分的prefix_in函数多支持一种类型感觉也没什么用，只能让它不报错，少打这些日志。

**Comment by aunjgr** [comment]
PR merged

**Comment by aressu1985** [comment]
fixed
