### ISSUE TITLE
[Bug]: 使用mo_br工具查看快照时，同时设置beginTs和endTs参数，筛选失败

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/matrixone#16008]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="706" alt="image" src="https://github.com/matrixorigin/matrixone/assets/153493538/f16f155f-18a0-4c8c-badd-231022b94c4b">

### Expected Behavior

在设置开始时间和结束时间参数后，应该显示这个范围内的数据

<img width="519" alt="image" src="https://github.com/matrixorigin/matrixone/assets/153493538/de12ea8d-b463-4ec0-a80e-9dc7a813fc60">

### Steps to Reproduce

```Markdown
命令行执行

1、./mo_br snapshot create --host "127.0.0.1" --port 6001 --user "dump" --password "111" --level "account" --sname "snapshot_01" --account "sys"

2、./mo_br snapshot create --host "127.0.0.1" --port 6001 --user "dump" --password "111" --level "account" --sname "snapshot_02" --account "sys"

3、./mo_br snapshot show --host "127.0.0.1" --port 6001 --user "dump" --password "111" --beginTs "xxx"  --endTs "xxx"
```

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
commit：7922426e3effea12dbe900af0daf02a308d9f031
<img width="829" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/69f42708-e33b-4863-8df9-ebfb7e6db288">

verified
