### ISSUE TITLE
[Bug]: TPCC Test Errors with 'invalid state task store not ready'

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

b5c2ea

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-b5c2eaa%5C%22%7D%20%7C%3D%20%60invalid%20state%20task%20store%20not%20ready%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1799" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/0d848490-4728-4bad-896a-021d8b4dad0b">

### Steps to Reproduce

```Markdown
daily
```

**Comment by w-zr** [comment]
taskservice是通过外部链接连上mo的，这里是系统的负载太大，导致taskservice连不上mo。这里需要尝试改一下taskservice的行为，在长期连不上mo的时候减少尝试链接mo的次数。

**Comment by w-zr** [comment]
目前的报错都是和cn暂时连不上导致的，这可能是不可避免地。

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/d97ca127-1f8d-48d2-a115-2f38a3bf4a45)
现在把报错信息细化了。少了很多`invalid state task store not ready`
