### ISSUE TITLE
[Bug]: [date 5.10]tke regression: sysbench 100w  random_point 1000threads mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16013]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6003d8346f0fed6e1fbd0563bc7bc2b1d2287741

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9033818759/job/24839146601
<img width="1155" alt="企业微信截图_0779e444-df9c-4c6e-8bf7-262000fa0cb6" src="https://github.com/matrixorigin/matrixone/assets/113406637/d28ce602-39cd-45dd-ba46-5a674bba2257">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hHs%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240510%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715385600000%22,%22to%22:%221715394660000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
[2024-05-11_10_14_01.zip](https://github.com/matrixorigin/matrixone/files/15281526/2024-05-11_10_14_01.zip)

### Steps to Reproduce

```Markdown
tke regression sysbench 100w  random_point 1000threads
```

**Comment by volgariver6** [comment]
@daviszhen will help to fix it

**Comment by daviszhen** [comment]
it was fixed.

**Comment by heni02** [comment]
commit：4d44f7247 还有这个问题
job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9044408439/job/24857841681
<img width="1255" alt="企业微信截图_6b1feb56-ef0c-42d4-abc8-d51d99deb017" src="https://github.com/matrixorigin/matrixone/assets/113406637/765c061e-f807-416d-8f5f-83d29b7e7d11">

**Comment by daviszhen** [comment]
昨天回归结果不卡了。

**Comment by daviszhen** [comment]
![Selection_014](https://github.com/matrixorigin/matrixone/assets/60595215/26420963-0490-4838-b5ee-2628570e0d5d)

![Selection_015](https://github.com/matrixorigin/matrixone/assets/60595215/807797c8-04dc-462b-a3e0-fe229825e5df)

**Comment by daviszhen** [comment]
sysbench工具引起的问题。等测试同事修改。

**Comment by daviszhen** [comment]
sysbench工具引起的问题。等测试同事修改。

**Comment by daviszhen** [comment]
不改sysbench 工具和脚本，作为已知问题。

**Comment by daviszhen** [comment]
从日志看不是卡住。是执行太慢了。执行了37分钟

![image](https://github.com/matrixorigin/matrixone/assets/60595215/528506e2-c737-43f0-a75f-23f95940003a)

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-580f61a-20240702-214653.log%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719956429613%22,%22to%22:%221719959760376%22%7D%7D%7D&schemaVersion=1&orgId=1
