### ISSUE TITLE
[Bug]: So many error logs "no such table mo_catalog.mo_increment_columns" during merge run test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16022]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.2-dev

### Commit ID

60cdf18

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1817" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/0f425ec2-49c4-482b-ad56-69ca15647027">

take #16004 as example:

https://github.com/matrixorigin/matrixone/actions/runs/9041104150

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fzn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-16004%5C%22%7D%20%7C%3D%20%60no%20such%20table%20mo_catalog.mo_increment_columns%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715402579623%22,%22to%22:%221715405306593%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
merge run test
```

**Comment by guguducken** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9044267875
![Screenshot from 2024-05-13 10-59-41](https://github.com/matrixorigin/matrixone/assets/22561920/a2e86e5a-ea41-48b6-8015-627bebc6a533)

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
main分支跑ddl目录的case能复现。
初步定位的原因是：在执行自增表的操作时，对应的account id所在的mo_catalog没有这个表。

预计根本原因是，context中的account id不对。因为debug时看到的account id，在mo_account表中没有找到。
但是具体是哪个地方放入了错误的account id，需要一点一点排查。会比较耗时间。

**Comment by ouyuanning** [comment]
根本原因是：
目前当包含了自增列的表，被删除之后，其在mo_catalog.mo_increment中的数据并非立刻删除。而是先积攒着，由后台任务删除。
而有时候，该表对应的account 都已经被删除了之后，后台任务才开始执行。这个时候就会出问题。

复现方式：
1、先跑bvt中的  ddl目录（主要是里面有个 drop_if_exists.sql，里面有创建账号和删除账号）
2、当drop_if_exists.sql完成后，过一会就可以碰到。

**Comment by ouyuanning** [comment]
这个问题并不会影响正确性，辛苦波洋有空的时候熟悉一下自增这部分的代码，然后修复吧
处理的时候可以找我或者张旭

**Comment by ouyuanning** [comment]
处理时候主要是修改 sqlStore 的 delete实现，使其在一个事务内先通过系统租户来判断account id是否还存在，只有在存在的情况下，才需要执行delete from mo_catalog.mo_increment_columns的操作

**Comment by huby2358** [comment]
按照上面步骤，本地复现了，在看这部分代码

**Comment by huby2358** [comment]
这两天暂时没投入

**Comment by huby2358** [comment]
暂时没投入

**Comment by huby2358** [comment]
没投入

**Comment by aressu1985** [comment]
经测试，问题已解决，问题单关闭
