### ISSUE TITLE
[Refactoring]: remove trace condition from savequeryresult

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16028]
### Why do you want to refactor this code?

目前看trace的配置影响到了查询结果保存。确认是否有必要这样做。

https://github.com/matrixorigin/MO-Cloud/issues/3084 与此问题有关

```Markdown
func openSaveQueryResult(ctx context.Context, ses *Session) bool {
	if ses.ast == nil || ses.tStmt == nil {
		return false
	}
	if ses.tStmt.SqlSourceType == constant.InternalSql {
		return false
	}
	if ses.tStmt.StatementType == "Select" && ses.tStmt.SqlSourceType != constant.CloudUserSql {
		return false
	}
	val, err := ses.GetGlobalVar(ctx, "save_query_result")
	if err != nil {
		return false
	}
	if v, _ := val.(int8); v > 0 {
		if ses.blockIdx == 0 {
			if err = initQueryResulConfig(ctx, ses); err != nil {
				return false
			}
		}
		return true
	}
	return false
}
```

### Describe the solution you'd like

解偶和trace和查询结果保存。

**Comment by xzxiong** [comment]
fix, disable motrace will not affact query-result

**Comment by xzxiong** [comment]
```
## motrace 关闭的配置。
[observability]
disableTrace = true
```

**Comment by heni02** [comment]
confirm,closed
1.2-dev commit:4afe69e60b24c4ef8c488b0ade98ce967ebea844
单机配置cn,dn,log trace关闭时，测试bvtcase save_query_result.sql通过
[observability]
disableTrace = true
<img width="1569" alt="企业微信截图_6d3d2afa-6150-4510-ab28-f8c263fb3c3c" src="https://github.com/matrixorigin/matrixone/assets/113406637/b59c444a-d216-4574-b46f-50e6593d1925">

单机配置cn,dn,log trace打开时，测试bvtcase save_query_result.sql通过
[observability]
disableTrace = false
<img width="1566" alt="企业微信截图_e9e95452-a65c-4d0c-8e30-7c93c7e8c52c" src="https://github.com/matrixorigin/matrixone/assets/113406637/3eba70ec-6381-4b88-9016-97f878c816a8">
