### ISSUE TITLE
[Bug]: performance: load data cost time slower  than 100%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16035]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1aed8d948

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

load data多个大数据量表性能下降一倍多
<img width="1390" alt="企业微信截图_2b575403-06b4-4749-94f8-14e1f6d8a08a" src="https://github.com/matrixorigin/matrixone/assets/113406637/eae6f3f6-ae5e-4613-8ca4-ab1db1326920">
<img width="679" alt="企业微信截图_f74c4adc-58e8-4fb5-b41f-06c0de3d3cbd" src="https://github.com/matrixorigin/matrixone/assets/113406637/10196166-c0c3-4a3b-ab93-7d71782751de">

正常性能的commit：3ac2f912b
性能下降的commit：1aed8d948

回归job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9033818759/job/24834693979
<img width="1013" alt="企业微信截图_e2f78b45-3597-4617-8edc-e00b6e743d95" src="https://github.com/matrixorigin/matrixone/assets/113406637/a0e6503b-03f2-4dab-a409-38f9e2fbffe3">
这个时间段的profile：
plz contact me

### Steps to Reproduce

```Markdown
tke regression load data test
```

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/pull/15995
这个PR应该已解决这个问题。

**Comment by ouyuanning** [comment]
锦赛帮忙看看 https://github.com/matrixorigin/matrixone/pull/15995  合并后。为什么还会有回退吧。
我估计是对于s3的load，stats预估的数值不太准确。

**Comment by heni02** [comment]
单独跑main最新的commit（e46e428）load data性能没有下降
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9059902416/job/24889173067
<img width="1089" alt="企业微信截图_abfacd7a-a73d-4900-a54b-7bb208ebefa0" src="https://github.com/matrixorigin/matrixone/assets/113406637/0b7b1200-20a7-45c0-abf2-95f1f654bd1a">

之前正常性能水平：
<img width="1074" alt="企业微信截图_a014cf1a-6779-4d05-8a42-f66ef03be438" src="https://github.com/matrixorigin/matrixone/assets/113406637/bab49618-27f1-487b-a612-db5e74e5d353">

**Comment by jensenojs** [comment]
性能没有下降的话, 那就再观测一段时间好了. 如果还有问题再跟进.

**Comment by heni02** [comment]
confirm，closed
<img width="1382" alt="企业微信截图_e83fe6ad-b554-48cf-9901-9442722aa69b" src="https://github.com/matrixorigin/matrixone/assets/113406637/5ec3c0aa-812b-4733-a196-95fd5519eba4">
<img width="1380" alt="企业微信截图_d8b79651-cbc4-4e87-b1b9-50880a542e2d" src="https://github.com/matrixorigin/matrixone/assets/113406637/0eb234e3-18cc-4873-b5e0-1d04d2731c17">
