### ISSUE TITLE
[Bug]: mo_columns的创建时间是0001-01-01 00:28:35 +0000 UTC

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#16031]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.1-dev

### Commit ID

14c4496c6

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
阿里云QA&Dev都有这个问题，上述是QA的版本
```

### Actual Behavior

查询SQL：
/* cloud_nonuser */SELECT relname AS `name`, mo_table_rows(reldatabase, relname) AS `rows`, mo_table_size(reldatabase, relname) AS `size`, if (role_name IS NULL, '-', role_name) AS `owner`, mo_tables.created_time AS created FROM mo_catalog.mo_tables LEFT JOIN mo_catalog.mo_role ON mo_catalog.mo_tables.owner=role_id WHERE relkind IN ('r','e','cluster') AND reldatabase='mo_catalog' Order by name;
展示如下结果：
<img width="1355" alt="image" src="https://github.com/matrixorigin/matrixone/assets/130344965/53e4890f-9e9e-4110-91b7-afea6ff488dc">

### Expected Behavior

期望有个正常的时间

### Steps to Reproduce

```Markdown
如Actual Behavior
```

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by aressu1985** [comment]
和彭振沟通，挪到1.3.0进行解决

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
fixed in https://github.com/matrixorigin/matrixone/pull/17721

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
pr 已经合进去，main 上已经解决

**Comment by YANGGMM** [comment]
@aressu1985  plz test

**Comment by aressu1985** [comment]
fixed
<img width="543" alt="image" src="https://github.com/user-attachments/assets/ae8298e6-0fca-4112-8f3d-9f57ee75f547">
