### ISSUE TITLE
[Bug]: mo hung in sysbench random point test with 100w and 1000w base data

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16042]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

784f1a7

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9044895256/job/24858257730

<img width="1420" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/73c61896-b0f2-471a-8d4a-648b3b8b7d51">

<img width="1406" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e2fe914d-3c37-4d3e-aa26-5a1b2642a2af">

profile(heap, cpu, goroutine)
[random_point_hung.tar.gz](https://github.com/matrixorigin/matrixone/files/15286074/random_point_hung.tar.gz)

### Steps to Reproduce

```Markdown
run sysbench random point test with 100w data and 1000w data, 1000terminals
```

**Comment by daviszhen** [comment]
从cn的goroutine看不是FE和执行卡住了。应该是其它地方。

**Comment by daviszhen** [comment]
从heap profile看，parser的消耗体现出来了。

![Screenshot from 2024-05-12 21-41-19](https://github.com/matrixorigin/matrixone/assets/60595215/52b5bacf-a18b-4d02-82af-b00a9435ebfe)

**Comment by aressu1985** [comment]
update on 4.13
commit id: 7bc191e

sysbench write only was hung

<img width="1402" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/11efc487-0ba6-42ef-8cd4-d52772be0a32">

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9052676441/job/24873894646

**Comment by aressu1985** [comment]
update on 5.14
commit id : 4c5b76c
case: 执行SYSBENCH 10 write only 场景， 每次执行10s，循环执行

profile:
[write_only_hung_1.tar.gz](https://github.com/matrixorigin/matrixone/files/15306638/write_only_hung_1.tar.gz)


tools log:
[write_only.out.zip](https://github.com/matrixorigin/matrixone/files/15306655/write_only.out.zip)


mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%229Tr%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-4c5b76c%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715678997865%22,%22to%22:%221715680784347%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by zhangxu19830126** [comment]
@iamlinjunhong dn crash.  Make lockservice hung by full channel.

**Comment by zhangxu19830126** [comment]
use #16121 to trace

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
