### ISSUE TITLE
[Feature Request]: Refactor global system variable  and  session variable

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16047]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Refactor global system variable  and  session variable ref https://doc.weixin.qq.com/doc/w3_AVIAugbFALcLhtRyzyDQZqwLQ0OiE?scode=AJsA6gc3AA8uKXAHGbAVIAugbFALc

**Comment by heni02** [comment]
test done
