### ISSUE TITLE
[Bug]: snapshot read run tpcc test error

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16062]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="646" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/5fb104a6-59ba-4424-963c-ba1e34094b32">

### Steps to Reproduce

```Markdown
run tpcc
```

**Comment by YANGGMM** [comment]
tpcc 测试记录
```mysql
select count(*) from bmsql_order_line;
create snapshot sp_01 for account sys;
create snapshot sp_cluster for cluster;

--run tpcc test
select count(*) from bmsql_order_line{snapshot = 'sp_01 '};
select count(*) from bmsql_order_line{snapshot = 'sp_cluster '};

```
<img width="829" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/f904e051-db0c-40a4-ad5e-43b258282fc8">

<img width="494" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/368d13f7-e0bc-40a3-8841-5c7ae3c0fe8b">

**Comment by YANGGMM** [comment]
**重启mo之后，结果不正确了**
<img width="545" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/8121a4af-0b5a-48dd-9104-2df4b9cc75b9">

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
单机环境
commit：fae5807be9d8c1a3ba862d522498f036de6a37f2
1. 执行测试之前：
<img width="366" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b9a5647d-2c1c-4a6d-9a31-6bb239e16614">

2. 执行tpcc 10-10测试；
3. 执行测试之后：
<img width="584" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3375817d-bb75-4a5c-8ba5-b59607db722e">

重启mo：
<img width="538" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3f7ea91b-70af-4014-b99a-3aa78e349319">


单机测试通过

**Comment by Ariznawlll** [comment]
分布式环境：a1fcd682dd21085c76f4a40180eddf05a17ce6b3
1. 执行测试之前：
<img width="395" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e653949b-5092-43fc-9d7c-93c6f958d110">

2. 执行tpcc 10-10测试：

3. 执行测试之后：
<img width="530" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d5476b29-c7b3-4225-9351-a2ef912716bc">

分布式测试通过
