### ISSUE TITLE
[Bug]: [big data regression] update table oom in big data test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16083]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4257dc620db76e22495241cab066cb807c092296

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url:** (Quries 1Y-> write 1y test)
 https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9062078787/job/24927516213
**pod status:**
<img width="574" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/5a7619c7-7ca3-4f8b-a08c-4be741187132">

<img width="1506" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2d6bdb5f-3df5-4591-9fc3-38e277495952">

<img width="1890" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c6d6151b-317b-4ce1-a1da-8bdadcd256ec">

**cn ip:**
<img width="1016" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8f8a8544-a109-4946-bceb-3be2a9572c9c">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%226cY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240513%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

对应时间点附近的profile
[2024-05-14_09_53_16.zip](https://github.com/matrixorigin/matrixone/files/15301766/2024-05-14_09_53_16.zip)
[2024-05-14_09_54_02.zip](https://github.com/matrixorigin/matrixone/files/15301767/2024-05-14_09_54_02.zip)
[2024-05-14_09_55_53.zip](https://github.com/matrixorigin/matrixone/files/15301768/2024-05-14_09_55_53.zip)

### Steps to Reproduce

```Markdown
trigger big-data-test on tke
数据量： 1亿
```

**Comment by ouyuanning** [comment]
2024-05-14_09:54:02 中 10.143.205.183 的heap和profile：

<img width="1699" alt="image" src="https://github.com/matrixorigin/matrixone/assets/45346669/9cef9e1d-23b0-4314-90fe-14683b131a58">
![image](https://github.com/matrixorigin/matrixone/assets/45346669/9e560d3d-7cce-4892-85ea-62966bc9beae)

明松帮忙看看吧，是regression问题

**Comment by m-schen** [comment]
下礼拜看看

**Comment by Ariznawlll** [comment]
[0522]
job url:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9173624701/job/25241697623 (Quries 1Y-> write 1y test)
<img width="975" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b3ec08bd-8b1e-4e54-9024-cd755c592abe">
[2024-05-22_02_34_53.zip](https://github.com/matrixorigin/matrixone/files/15397310/2024-05-22_02_34_53.zip)
[2024-05-22_02_33_58.zip](https://github.com/matrixorigin/matrixone/files/15397312/2024-05-22_02_33_58.zip)

**Comment by m-schen** [comment]
预计周四周五跟踪这个问题，在追别的问题和allocate > 1g的问题。

**Comment by m-schen** [comment]
与上一个评论相同，时间还得往后延。

**Comment by m-schen** [comment]
与上一个评论相同

**Comment by m-schen** [comment]
请假了

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
在改connection reset的s-1中

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
今日无投入

**Comment by m-schen** [comment]
大概率已经解决，remote run关于这块的代码进行了重构了。（合并到了1.2分支和main分支）

但是先不转，我无法肯定这块时否已经ok，这部分代码还需要进行检查。

**Comment by m-schen** [comment]
今天没时间验证和检查。

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
近期没空看。

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
。

**Comment by m-schen** [comment]
和上一个回复相同。

**Comment by m-schen** [comment]
现在没空

**Comment by m-schen** [comment]
现在没空进行跟踪。

**Comment by m-schen** [comment]
同上

**Comment by m-schen** [comment]
现在没有空进行验证。

**Comment by m-schen** [comment]
还在忙spool的事情。

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
spool收尾中

**Comment by m-schen** [comment]
处理其他bug中

**Comment by m-schen** [comment]
在spool 相关的pr 
https://github.com/matrixorigin/matrixone/pull/18709合并后，

最上面的profile火焰图中占最大内存的那块同时只会有一个batch的存在。
除非并发的查询数很大，否则不会引起大内存的问题。

可以先关闭，后面有发现再开启或提新的问题。

**Comment by Ariznawlll** [comment]
14960跟踪
