### ISSUE TITLE
[Bug]: ctrl+c during recovery, the recovered table and data exists.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16098]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4257dc620db76e22495241cab066cb807c092296

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="754" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/af681ead-46c7-492f-ac1a-90c98c53562b">

### Expected Behavior

恢复某表的数据 建表+插入数据应该在一个事务里，如果ctrl+c，事务没结束，不应该成功，此时表恢复失败（表没建成功且表中无数据）

### Steps to Reproduce

```Markdown
集群环境：
create database big_data_test;
use big_data_test;
create table  if not exists big_data_test.table_basic_for_load_1B( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));
load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/1000000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_1B fields terminated by '|' lines terminated by '\n' parallel 'true';
(具体的ak sk如有需要，请联系我)
create snapshot sp03 for account sys;

drop database big_data_test;

restore account sys database big_data_test table table_basic_for_load_1b from snapshot sp03;
```

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
Pending processing

**Comment by aressu1985** [comment]
和松哥沟通，取消操作需要具备原子性，需要再1.2.1解决

**Comment by qingxinhome** [comment]
Pending processing

**Comment by qingxinhome** [comment]
关联：https://github.com/matrixorigin/matrixone/issues/16085

**Comment by qingxinhome** [comment]
pr已提交

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @Ariznawlll @aressu1985 @daviszhen @YANGGMM

**Comment by Ariznawlll** [comment]
**commit : 09c4d95dcdc615e1ea924239ff72af8c7863e286**
<img width="784" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6755a1bb-5ff0-4fdd-91ff-a41fc6aca66d">
verified.
