### ISSUE TITLE
[Bug]: [snapshot performance] restore is too slow.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16099]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4257dc620db76e22495241cab066cb807c092296

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

restore 一张 10亿数据量的表大约30min恢复了45539328（不到1/2）.

### Steps to Reproduce

```Markdown
集群环境：
create database big_data_test;
use big_data_test;
create table  if not exists big_data_test.table_basic_for_load_1B( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));
load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/1000000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_1B fields terminated by '|' lines terminated by '\n' parallel 'true';
(具体的ak sk如有需要，请联系我)
create snapshot sp03 for account sys;

drop database big_data_test;

restore account sys database big_data_test table table_basic_for_load_1b from snapshot sp03;
```

**Comment by YANGGMM** [comment]
**单机环境下恢复一个大约300w行的table 花费十几分钟**

<img width="655" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/2560b487-75e7-4fe0-b6e0-9e81961bab21">

**Comment by YANGGMM** [comment]
```mysql
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> drop table if exists `bmsql_order_line`;
Query OK, 0 rows affected (0.05 sec)

mysql> use tpcc;
Database changed
mysql> 
mysql> CREATE TABLE `bmsql_order_line` (
    -> `ol_w_id` INT NOT NULL,
    -> `ol_d_id` INT NOT NULL,
    -> `ol_o_id` INT NOT NULL,
    -> `ol_number` INT NOT NULL,
    -> `ol_i_id` INT NOT NULL,
    -> `ol_delivery_d` TIMESTAMP DEFAULT null,
    -> `ol_amount` DECIMAL(6,2) DEFAULT null,
    -> `ol_supply_w_id` INT DEFAULT null,
    -> `ol_quantity` INT DEFAULT null,
    -> `ol_dist_info` CHAR(24) DEFAULT null,
    -> PRIMARY KEY (`ol_w_id`,`ol_d_id`,`ol_o_id`,`ol_number`)
    -> ) partition by key algorithm = 2 (ol_w_id);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into `tpcc`.`bmsql_order_line` SELECT * FROM `tpcc`.`bmsql_order_line` {snapshot = 'sp_01'};
Query OK, 2998810 rows affected (11 min 5.11 sec)

mysql> commit;
Query OK, 0 rows affected (5.93 sec)

```

**Comment by YANGGMM** [comment]
恢复一个带主键的表insert 30w条只用1.93sec，但是insert300w行的分区表时间太慢了
```mysql
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> drop table if exists `bmsql_history`;
Query OK, 0 rows affected (0.01 sec)

mysql> use tpcc;
Database changed
mysql> 
mysql> create table `bmsql_history` (`hist_id` INT NOT NULL AUTO_INCREMENT,`h_c_id` INT DEFAULT NULL,`h_c_d_id` INT DEFAULT NULL,`h_c_w_id` INT DEFAULT NULL,`h_d_id` INT DEFAULT NULL,`h_w_id` INT DEFAULT NULL,`h_date` TIMESTAMP DEFAULT NULL,`h_amount` DECIMAL(6,2) DEFAULT NULL,`h_data` VARCHAR(24) DEFAULT NULL,PRIMARY KEY (`hist_id`));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into `tpcc`.`bmsql_history` SELECT * FROM `tpcc`.`bmsql_history` {snapshot = 'sp_01'};
Query OK, 300000 rows affected (1.93 sec)

mysql> commit;
Query OK, 0 rows affected (0.48 sec)
```

**Comment by YANGGMM** [comment]
still working

**Comment by Ariznawlll** [comment]
集群环境 
**commit：0a99a7a5fc08c9927172bc34fd5089fe8538e4ea**
系统租户向普通租户恢复数据 9w需要3min+
<img width="655" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/622a329b-98a9-4e2a-ac44-6a538d7ff86a">
详细测试步骤，请联系我

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
```mysql
mysql> create snapshot sp01 for account sys;
Query OK, 0 rows affected (0.04 sec)
```
run tpcc test

<img width="818" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/a3874eba-83a2-4a07-91d3-25f45fbde3a8">


```mysql
mysql> restore account sys database tpcc_10 table bmsql_new_order from snapshot sp01;
```

**Comment by YANGGMM** [comment]
ppof
<img width="1068" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/83ed3252-1622-4382-ae8a-fa1631e1ab48">

[cpu.pdf](https://github.com/matrixorigin/matrixone/files/15480629/cpu.pdf)

**Comment by YANGGMM** [comment]
```mysql
mysql> insert into `bmsql_new_order_new` select * from `bmsql_new_order` {snapshot = 'sp01'};
Query OK, 90000 rows affected (0.34 sec)

mysql> 
mysql> restore account sys database tpcc_10 table `bmsql_new_order` from snapshot sp01;
Query OK, 0 rows affected (1 min 47.18 sec)
```

**Comment by aressu1985** [comment]
和松哥沟通，挪到1.3.0进行解决

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
still

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
需要等这个https://github.com/matrixorigin/MO-Cloud/issues/3518解决

**Comment by YANGGMM** [comment]
```mysql
mysql> select count(*) from bmsql_oorder;
+----------+
| count(*) |
+----------+
|   306280 |
+----------+
1 row in set (0.02 sec)

CREATE TABLE `bmsql_oorder_test` (
  `o_w_id` INT NOT NULL,
  `o_d_id` INT NOT NULL,
  `o_id` INT NOT NULL,
  `o_c_id` INT DEFAULT NULL,
  `o_carrier_id` INT DEFAULT NULL,
  `o_ol_cnt` INT DEFAULT NULL,
  `o_all_local` INT DEFAULT NULL,
  `o_entry_d` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`o_w_id`,`o_d_id`,`o_id`)
);


mysql> insert into `bmsql_oorder_test` SELECT * FROM `tpcc_10`.`bmsql_oorder` {MO_TS = 1718781027351683000 };
Query OK, 306280 rows affected (3.49 sec)
```

但是 back execute

mysql> restore account sys  database tpcc_10 table `bmsql_oorder` from snapshot sp01;
Query OK, 0 rows affected (5 min 29.27 sec)

{"level":"INFO","time":"2024/06/19 15:27:20.624918 +0800","name":"log-service.frontend","caller":"frontend/snapshot.go:787","msg":"[sp01] insert select table: bmsql_oorder, insert sql: insert into `tpcc_10`.`bmsql_oorder` SELECT * FROM `tpcc_10`.`bmsql_oorder` {MO_TS = 1718781027351683000 }, cost: **5m28.657294416s**","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}

**Comment by YANGGMM** [comment]
<img width="1092" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/d479cd2d-2786-4d4a-a91e-72cdef653961">
@jensenojs  还是跟之前一样的问题

**Comment by YANGGMM** [comment]
mysql> restore account sys  database tpcc_10 table `bmsql_oorder` from snapshot sp01;
Query OK, 0 rows affected (1 min 32.10 sec)


{"level":"INFO","time":"2024/06/19 16:23:54.340143 +0800","name":"log-service.frontend","caller":"frontend/snapshot.go:787","msg":"[sp01] insert select table: bmsql_oorder, cost: 1m31.718547458s","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
mysql> restore account sys database tpcc_10 table bmsql_new_order from snapshot sp01;
Query OK, 0 rows affected (6 min 13.66 sec)


{"level":"INFO","time":"2024/06/26 15:33:11.252127 +0800","name":"log-service.frontend","caller":"frontend/snapshot.go:787","msg":"[sp01] insert select table: bmsql_new_order, cost: 6m13.329385791s","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}

**Comment by YANGGMM** [comment]
测试结果已经贴在pr中了，麻烦测试一下大数据量 @Ariznawlll

**Comment by Ariznawlll** [comment]
测试中

**Comment by Ariznawlll** [comment]
**恢复测试，数据量大小为36.37G：**
<img width="465" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2d114cde-1a79-46bc-94c4-5ceaa98dcadb">
**耗时：**
<img width="756" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7be66e96-ded0-4266-b74d-e875e32dc638">

**Comment by YANGGMM** [comment]
<img width="1429" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/f964f051-6ed0-46a5-b68b-6aef88bab079">

**Comment by YANGGMM** [comment]
测试记录
mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 5f72428       |
+---------------+
1 row in set (0.00 sec)

mysql> CREATE TABLE `table_basic_for_load_100m_new` (
    ->   `col1` TINYINT DEFAULT NULL,
    ->   `col2` SMALLINT DEFAULT NULL,
    ->   `col3` INT DEFAULT NULL,
    ->   `col4` BIGINT DEFAULT NULL,
    ->   `col5` TINYINT UNSIGNED DEFAULT NULL,
    ->   `col6` SMALLINT UNSIGNED DEFAULT NULL,
    ->   `col7` INT UNSIGNED DEFAULT NULL,
    ->   `col8` BIGINT UNSIGNED DEFAULT NULL,
    ->   `col9` FLOAT DEFAULT NULL,
    ->   `col10` DOUBLE DEFAULT NULL,
    ->   `col11` VARCHAR(255) DEFAULT NULL,
    ->   `col12` DATE DEFAULT NULL,
    ->   `col13` DATETIME DEFAULT NULL,
    ->   `col14` TIMESTAMP NULL DEFAULT NULL,
    ->   `col15` BOOL DEFAULT NULL,
    ->   `col16` DECIMAL(16,6) DEFAULT NULL,
    ->   `col17` TEXT DEFAULT NULL,
    ->   `col18` JSON DEFAULT NULL,
    ->   `col19` BLOB DEFAULT NULL,
    ->   `col20` BINARY(255) DEFAULT NULL,
    ->   `col21` VARBINARY(255) DEFAULT NULL,
    ->   `col22` VECF32(3) DEFAULT NULL,
    ->   `col23` VECF32(3) DEFAULT NULL,
    ->   `col24` VECF64(3) DEFAULT NULL,
    ->   `col25` VECF64(3) DEFAULT NULL
    -> );
Query OK, 0 rows affected (0.12 sec)

mysql> select count(*) from `table_basic_for_load_100m`;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (17.02 sec)

```

**Comment by YANGGMM** [comment]
<img width="1376" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/1e0f952a-9236-41a2-b5e1-bfe2ab426f08">

**Comment by jensenojs** [comment]
<img width="1680" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/152a3cb8-3cc2-4ad8-ab9d-8a0a343e18ce">

从cpu的结果来看, gc占用的时间是绝对的大头.

看着这个行为似乎和下面这个issue观察到的一些现象相关, @YANGGMM  钊哥辛苦对比一下测试的commit和我在那个issue下观察到的一些值得关注的commit.

- https://github.com/matrixorigin/matrixone/issues/17143

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
最新测试
```mysql
mysql> show create table table_basic_for_load_100m;
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                     | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| table_basic_for_load_100m | CREATE TABLE `table_basic_for_load_100m` (
  `col1` TINYINT DEFAULT NULL,
  `col2` SMALLINT DEFAULT NULL,
  `col3` INT DEFAULT NULL,
  `col4` BIGINT DEFAULT NULL,
  `col5` TINYINT UNSIGNED DEFAULT NULL,
  `col6` SMALLINT UNSIGNED DEFAULT NULL,
  `col7` INT UNSIGNED DEFAULT NULL,
  `col8` BIGINT UNSIGNED DEFAULT NULL,
  `col9` FLOAT DEFAULT NULL,
  `col10` DOUBLE DEFAULT NULL,
  `col11` VARCHAR(255) DEFAULT NULL,
  `col12` DATE DEFAULT NULL,
  `col13` DATETIME DEFAULT NULL,
  `col14` TIMESTAMP NULL DEFAULT NULL,
  `col15` BOOL DEFAULT NULL,
  `col16` DECIMAL(16,6) DEFAULT NULL,
  `col17` TEXT DEFAULT NULL,
  `col18` JSON DEFAULT NULL,
  `col19` BLOB DEFAULT NULL,
  `col20` BINARY(255) DEFAULT NULL,
  `col21` VARBINARY(255) DEFAULT NULL,
  `col22` VECF32(3) DEFAULT NULL,
  `col23` VECF32(3) DEFAULT NULL,
  `col24` VECF64(3) DEFAULT NULL,
  `col25` VECF64(3) DEFAULT NULL
) |
+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> CREATE TABLE `table_basic_for_load_100m_new` (
    ->   `col1` TINYINT DEFAULT NULL,
    ->   `col2` SMALLINT DEFAULT NULL,
    ->   `col3` INT DEFAULT NULL,
    ->   `col4` BIGINT DEFAULT NULL,
    ->   `col5` TINYINT UNSIGNED DEFAULT NULL,
    ->   `col6` SMALLINT UNSIGNED DEFAULT NULL,
    ->   `col7` INT UNSIGNED DEFAULT NULL,
    ->   `col8` BIGINT UNSIGNED DEFAULT NULL,
    ->   `col9` FLOAT DEFAULT NULL,
    ->   `col10` DOUBLE DEFAULT NULL,
    ->   `col11` VARCHAR(255) DEFAULT NULL,
    ->   `col12` DATE DEFAULT NULL,
    ->   `col13` DATETIME DEFAULT NULL,
    ->   `col14` TIMESTAMP NULL DEFAULT NULL,
    ->   `col15` BOOL DEFAULT NULL,
    ->   `col16` DECIMAL(16,6) DEFAULT NULL,
    ->   `col17` TEXT DEFAULT NULL,
    ->   `col18` JSON DEFAULT NULL,
    ->   `col19` BLOB DEFAULT NULL,
    ->   `col20` BINARY(255) DEFAULT NULL,
    ->   `col21` VARBINARY(255) DEFAULT NULL,
    ->   `col22` VECF32(3) DEFAULT NULL,
    ->   `col23` VECF32(3) DEFAULT NULL,
    ->   `col24` VECF64(3) DEFAULT NULL,
    ->   `col25` VECF64(3) DEFAULT NULL
    -> );
Query OK, 0 rows affected (0.07 sec)

mysql> insert into `table_basic_for_load_100m_new` select * from `table_basic_for_load_100m`;
Query OK, 100000000 rows affected (8 min 57.95 sec)

```

然后将命令写死,background 执行相同的命令
可以用https://github.com/YANGGMM/matrixone/pull/182

```mysql
mysql> restore account sys database big_data_test table `table_basic_for_load_100m` from snapshot sp01;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (61)
ERROR: 
Can't connect to the server
```
mo 执行了二十多分钟没有执行完，然后挂了

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
还没看

**Comment by jensenojs** [comment]
跟oom的issue一起抓的, cpu看着瓶颈卡在`containers.ForeachWindowBytes`中, 不过前端直接执行insert into select是不会这么慢的. 还是先找到差异在哪

https://github.com/matrixorigin/matrixone/issues/16138#issuecomment-2244847220

<img width="1767" alt="image" src="https://github.com/user-attachments/assets/bb11f8ae-f028-4095-82b7-239a9fd4b711">

**Comment by jensenojs** [comment]
在使得restore走s3之后, 快了将近一倍. 但仍然有接近4倍的差距

<img width="1549" alt="image" src="https://github.com/user-attachments/assets/58a0969a-5d2f-4cb8-8df7-3c6dd00e4d2f">

**Comment by jensenojs** [comment]
跟算子内部的并行化没有开起来有关系, 处理好之后就行了

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/1073dd25-e20f-4cf3-b647-32a6b817ee2e">

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
@Ariznawlll 辛苦QA有空的时候验证一下

**Comment by Ariznawlll** [comment]
正在测试76G数据的恢复

**Comment by Ariznawlll** [comment]
**job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10505304794/job/29105911058**

74G恢复：
系统租户恢复系统租户的数据，耗时9min39s；
<img width="991" alt="image" src="https://github.com/user-attachments/assets/b093bd67-7669-4776-9ba7-dac06091fc25">

系统租户恢复普通租户的数据到新租户，耗时16min19s；
<img width="990" alt="image" src="https://github.com/user-attachments/assets/d5c8ccb6-9990-40cf-a4c8-1b107e15b771">

普通租户恢复普通租户的数据，耗时17min6s
<img width="993" alt="image" src="https://github.com/user-attachments/assets/d06efe4d-5a0c-4a52-adc2-730a9ce109ed">

以上三点恢复成功
系统租户恢复普通租户到普通租户恢复有bug  issue:18237 跟踪

**Comment by Ariznawlll** [comment]
**1.2-dev commit: ff8d9acec2fb41d8cd85b9bd012d604d3bd3d74b**
**job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10518970679/job/29145596868**

74G恢复：
系统租户恢复系统租户的数据，耗时7min11s；
<img width="975" alt="image" src="https://github.com/user-attachments/assets/16767328-fbe9-4672-8edb-434cb5914489">

系统租户恢复普通租户的数据到新租户，13min10s；
<img width="986" alt="image" src="https://github.com/user-attachments/assets/ef50e95d-29e6-4bc6-92d2-e17887d18991">

普通租户恢复普通租户的数据，13min57s.
<img width="979" alt="image" src="https://github.com/user-attachments/assets/60215a4b-5104-48e6-ba93-36587643a704">

以上三点恢复成功
系统租户恢复普通租户到普通租户恢复有bug  issue: 18237 跟踪

**Comment by Ariznawlll** [comment]
还要再加点数据量测试一下

**Comment by Ariznawlll** [comment]
**main commit: c880770abcc2e682702c741ef5485244c814c521
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10626274378/job/29457558653**

**约110G恢复：
系统租户恢复系统租户的数据，耗时15min37s**：
<img width="973" alt="image" src="https://github.com/user-attachments/assets/29dc7d95-35ed-4027-8001-ab0b14181406">

**系统租户恢复普通租户的数据到新租户，耗时21min16s：**
<img width="975" alt="image" src="https://github.com/user-attachments/assets/b65e14d3-dbd8-4d36-aa09-24f055dc257c">

**普通租户恢复普通租户的数据，耗时23min31s**
<img width="977" alt="image" src="https://github.com/user-attachments/assets/4818d134-0a88-41a6-9b5f-d204d2590282">

**系统租户恢复普通租户的数据到普通租户，耗时16min5s**
<img width="978" alt="image" src="https://github.com/user-attachments/assets/ba2b2b44-278b-41de-a58f-866f6109b921">

以上四点均恢复成功

**Comment by Ariznawlll** [comment]
**1.2-dev commit: 3b003adb43aac30267433702734533c16c2b82a8
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10627910181/job/29462569576**

**约110G恢复：
系统租户恢复系统租户的数据，耗时13min5s**：
<img width="974" alt="image" src="https://github.com/user-attachments/assets/649b3874-f405-40f7-ba5a-76b267a5e9dc">

**系统租户恢复普通租户的数据到新租户，耗时19min11s：**
<img width="974" alt="image" src="https://github.com/user-attachments/assets/cf27c509-b63f-44bb-bdca-471ea1f894f7">

**普通租户恢复普通租户的数据，耗时23min31s**


**系统租户恢复普通租户的数据到普通租户，耗时13min51s**
<img width="973" alt="image" src="https://github.com/user-attachments/assets/cabd6f24-382c-45b0-9a37-168b3ec50269">

以上四点均恢复成功

**Comment by Ariznawlll** [comment]
以上测试，集群配置均为：

https://github.com/matrixorigin/mo-nightly-regression/blob/big_data/big-data-tke.yaml

**Comment by Ariznawlll** [comment]
测试110G数据量通过，产品认可恢复速度，先关掉
