### ISSUE TITLE
[Bug]: add CloneSnapshotOp to partition table  run tpcc test panic

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-05-15 10:40:49 INFO  jTPCC:804 - Term-00, Term-00, Running Average tpmTOTAL: 3647.19    Current tpmTOTAL: 19548    Memory Usage: 81MB / 130MB          
2024-05-15 10:40:50 FATAL jTPCCTerminal:237 - [UNEXPECTED][STOCK_LEVEL][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: slice bounds out of range [224:0]: 
runtime.goPanicSliceB
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/panic.go:154
github.com/matrixorigin/matrixone/pkg/objectio.(*BlockInfoSlice).Slice
	/Users/yangzhao/matrixone/pkg/objectio/block_info.go:124
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
	/Users/yangzhao/matrixone/pkg/sql/compile/scope.go:548
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
	/Users/yangzhao/matrixone/pkg/sql/compile/scope.go:296
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/Users/yangzhao/matrixone/pkg/sql/compile/scope.go:230
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/Users/yangzhao/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/asm_arm64.s:1197
<img width="877" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/aedc8687-c598-4aee-8123-f631cbbd7aba">

### Steps to Reproduce

```Markdown
clone pr https://github.com/matrixorigin/matrixone/pull/16091
then run tpcc test
```

**Comment by qingxinhome** [comment]
该问题，没有出现，观察中

**Comment by qingxinhome** [comment]
Got it

**Comment by qingxinhome** [comment]
该问题，没有出现，观察中
