### ISSUE TITLE
[Bug]:  restore oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16138]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

934856ce3e7006df740da76c608a532970b1d8a5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="719" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ca874220-41b6-4d23-992f-4b5dac0c6543">
<img width="1434" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/28381c3a-6309-4706-81b9-e438617c7afb">
oom：
<img width="1416" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/50522b59-3554-4401-8935-e150d1a7a599">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%228Sy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240514%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

profile：
[2024-05-15_13_01_27.zip](https://github.com/matrixorigin/matrixone/files/15316626/2024-05-15_13_01_27.zip)
[2024-05-15_13_02_48.zip](https://github.com/matrixorigin/matrixone/files/15316627/2024-05-15_13_02_48.zip)

### Steps to Reproduce

```Markdown
sys account connects mo:
create account acc01 admin_name = 'test_account' identified by '111';
create account acc02 admin_name = 'test_account' identified by '111';

acc01 connects mo:
create database ssb_100g;
use ssb_100g;
create table ssb_100g.date ( d_datekey date, d_date char (18), d_dayofweek char (9), d_month char (9), d_year int, d_yearmonthnum int, d_yearmonth char (7), d_daynuminweek varchar(12), d_daynuminmonth int, d_daynuminyear int, d_monthnuminyear int, d_weeknuminyear int, d_sellingseason varchar (12), d_lastdayinweekfl varchar (1), d_lastdayinmonthfl varchar (1), d_holidayfl varchar (1), d_weekdayfl varchar (1));
create table ssb_100g.customer ( c_custkey int, c_name varchar (25), c_address varchar (25), c_city char (10), c_nation char (15), c_region char (12), c_phone char (15), c_mktsegment char (10) ) cluster by (c_region, c_nation, c_city);
create table ssb_100g.lineorder ( lo_orderkey bigint, lo_linenumber int, lo_custkey int, lo_partkey int, lo_suppkey int, lo_orderdate date, lo_orderpriority char (15), lo_shippriority tinyint, lo_quantity double, lo_extendedprice double, lo_ordtotalprice double, lo_discount double, lo_revenue double, lo_supplycost double, lo_tax double, lo_commitdate date, lo_shipmode char (10) ) cluster by lo_orderdate;
create table ssb_100g.part ( p_partkey int, p_name varchar (22), p_mfgr char (6), p_category char (7), p_brand char (9), p_color varchar (11), p_type varchar (25), p_size int, p_container char (10) ) cluster by (p_mfgr, p_category, p_brand);
create table ssb_100g.supplier ( s_suppkey int, s_name char (25), s_address varchar (25), s_city char (10), s_nation char (15), s_region char (12), s_phone char (15) ) cluster by (s_region, s_nation, s_city);

load sql: please contact me 

sys account connects mo:
create snapshot sp01 for account acc01;
restore account acc01 database ssb_100g from snapshot sp01 to account acc02;
```

**Comment by YANGGMM** [comment]
应该是insert into select 表的数据量太大导致的oom

**Comment by YANGGMM** [comment]
应该是insert into select 表的数据量太大导致的oom

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
没有环境进行复现

**Comment by aressu1985** [comment]
和松哥沟通，挪到1.3.0进行解决

**Comment by YANGGMM** [comment]
等1.3解决

**Comment by YANGGMM** [comment]
跟这个https://github.com/matrixorigin/matrixone/issues/16650有关系

**Comment by Ariznawlll** [comment]
[0605]
tke环境手动测试：
```
create database big_data_test;
use big_data_test;
CREATE TABLE `table_basic_for_load_100m` (
  `col1` TINYINT DEFAULT NULL,
  `col2` SMALLINT DEFAULT NULL,
  `col3` INT DEFAULT NULL,
  `col4` BIGINT DEFAULT NULL,
  `col5` TINYINT UNSIGNED DEFAULT NULL,
  `col6` SMALLINT UNSIGNED DEFAULT NULL,
  `col7` INT UNSIGNED DEFAULT NULL,
  `col8` BIGINT UNSIGNED DEFAULT NULL,
  `col9` FLOAT DEFAULT NULL,
  `col10` DOUBLE DEFAULT NULL,
  `col11` VARCHAR(255) DEFAULT NULL,
  `col12` DATE DEFAULT NULL,
  `col13` DATETIME DEFAULT NULL,
  `col14` TIMESTAMP NULL DEFAULT NULL,
  `col15` BOOL DEFAULT NULL,
  `col16` DECIMAL(16,6) DEFAULT NULL,
  `col17` TEXT DEFAULT NULL,
  `col18` JSON DEFAULT NULL,
  `col19` BLOB DEFAULT NULL,
  `col20` BINARY(255) DEFAULT NULL,
  `col21` VARBINARY(255) DEFAULT NULL,
  `col22` VECF32(3) DEFAULT NULL,
  `col23` VECF32(3) DEFAULT NULL,
  `col24` VECF64(3) DEFAULT NULL,
  `col25` VECF64(3) DEFAULT NULL
);
load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='****','secret_access_key'='****','bucket'='****', 'filepath'='mo-big-data/100000000_20_columns_load_data_new.csv'} into table big_data_test.table_basic_for_load_100m fields terminated by '|' lines terminated by '\n' ignore 1 lines parallel 'true';
create snapshot sp01 for account sys;
drop table table_basic_for_load_100m;
restore account sys database big_data_test table table_basic_for_load_100m from snapshot sp01;   -->出错位置
```
<img width="845" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ce7eda2c-d69f-4e41-bb40-ad54af17f820">

**Comment by YANGGMM** [comment]
{"level":"INFO","time":"2024/06/05 05:19:37.898063 +0000","name":"cn-service.frontend","caller":"frontend/snapshot.go:750","msg":"[sp01] start to insert select table: table_basic_for_load_100m, insert sql: insert into `big_data_test`.`table_basic_for_load_100m` SELECT * FROM `big_data_test`.`table_basic_for_load_100m` {snapshot = 'sp01'}","uuid":"34383862-3730-3965-3963-363134663161"}
导致的oom
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22WAS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240604%5C%22%7D%20%7C%3D%20%60%5Bsp01%5D%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by Ariznawlll** [comment]
[0715] main commit：cccaf5e

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9936199822/job/27444584364
数据量：37g

<img width="569" alt="image" src="https://github.com/user-attachments/assets/ad3ecb6a-3005-42f9-ab03-a40c8c4ffaa6">

<img width="1416" alt="image" src="https://github.com/user-attachments/assets/3b1d75ee-538d-410a-9fa0-c8e5cec16aa3">

内存使用情况：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22aTR%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-snapshot-test-20240715%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
@jensenojs 麻烦看一下

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
用其他的大数量简单地模拟了一下, 也是oom了, 先想办法优化这个地方的问题

```sql
create database big_data_test;
use big_data_test;
create table t(a int primary key, b int);
insert into t select result, result from generate_series(1,500000000) g;
create snapshot sp01 for account sys;
drop database big_data_test;
restore account sys database big_data_test table t from snapshot sp01;
```

<img width="1767" alt="image" src="https://github.com/user-attachments/assets/b15dcd34-3b4d-4627-8034-c34e36a2de47">

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
pr合并进去之后应该就没有了

**Comment by jensenojs** [comment]
已经fix了, 等验证

**Comment by jensenojs** [comment]
同上

**Comment by Ariznawlll** [comment]
测试了恢复34G大小的数据，没有再出现，明天要再恢复一下70G大小的数据，看看结果

**Comment by Ariznawlll** [comment]
正在测试恢复76G大小的数据

**Comment by Ariznawlll** [comment]
**job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10505304794/job/29105911058**

74G恢复：
系统租户恢复系统租户的数据；
<img width="991" alt="image" src="https://github.com/user-attachments/assets/b093bd67-7669-4776-9ba7-dac06091fc25">

系统租户恢复普通租户的数据到新租户；
<img width="990" alt="image" src="https://github.com/user-attachments/assets/d5c8ccb6-9990-40cf-a4c8-1b107e15b771">

普通租户恢复普通租户的数据
<img width="993" alt="image" src="https://github.com/user-attachments/assets/d06efe4d-5a0c-4a52-adc2-730a9ce109ed">

以上三点恢复成功，未发生oom
系统租户恢复普通租户到普通租户恢复有bug  issue:18237 跟踪

**Comment by Ariznawlll** [comment]
**1.2-dev commit: ff8d9acec2fb41d8cd85b9bd012d604d3bd3d74b**
**job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10518970679/job/29145596868**

74G恢复：
系统租户恢复系统租户的数据；
<img width="975" alt="image" src="https://github.com/user-attachments/assets/16767328-fbe9-4672-8edb-434cb5914489">

系统租户恢复普通租户的数据到新租户；
<img width="986" alt="image" src="https://github.com/user-attachments/assets/ef50e95d-29e6-4bc6-92d2-e17887d18991">

普通租户恢复普通租户的数据
<img width="979" alt="image" src="https://github.com/user-attachments/assets/60215a4b-5104-48e6-ba93-36587643a704">

以上三点恢复成功，未发生oom
系统租户恢复普通租户到普通租户恢复有bug  issue: 18237 跟踪

**Comment by Ariznawlll** [comment]
还要再加点数据量测试一下

**Comment by Ariznawlll** [comment]
**main commit: c880770abcc2e682702c741ef5485244c814c521
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10626274378/job/29457558653**

**约110G恢复：
系统租户恢复系统租户的数据**：
<img width="973" alt="image" src="https://github.com/user-attachments/assets/29dc7d95-35ed-4027-8001-ab0b14181406">

系统租户恢复普通租户的数据到新租户：
<img width="975" alt="image" src="https://github.com/user-attachments/assets/b65e14d3-dbd8-4d36-aa09-24f055dc257c">

普通租户恢复普通租户的数据
<img width="977" alt="image" src="https://github.com/user-attachments/assets/4818d134-0a88-41a6-9b5f-d204d2590282">

系统租户恢复普通租户的数据到普通租户：
<img width="978" alt="image" src="https://github.com/user-attachments/assets/ba2b2b44-278b-41de-a58f-866f6109b921">

以上四点均恢复成功，未发生oom

**Comment by Ariznawlll** [comment]
**1.2-dev commit: 3b003adb43aac30267433702734533c16c2b82a8
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10627910181/job/29462569576**

**约110G恢复：
系统租户恢复系统租户的数据，耗时13min5s**：
<img width="974" alt="image" src="https://github.com/user-attachments/assets/649b3874-f405-40f7-ba5a-76b267a5e9dc">

**系统租户恢复普通租户的数据到新租户，耗时19min11s：**
<img width="974" alt="image" src="https://github.com/user-attachments/assets/cf27c509-b63f-44bb-bdca-471ea1f894f7">

**普通租户恢复普通租户的数据，耗时23min31s**


**系统租户恢复普通租户的数据到普通租户，耗时13min51s**
<img width="973" alt="image" src="https://github.com/user-attachments/assets/cabd6f24-382c-45b0-9a37-168b3ec50269">

以上四点均恢复成功，未发生oom
