### ISSUE TITLE
[Bug]: Prepared SQL returns incorrect result

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#16139]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.0-76ce4ef7e-2024-05-14

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [mo_cloud]> prepare __mo_stmt_id_23 from SELECT count(*) FROM `mo_cloud`.`workbook` WHERE account_id = ? AND sql_user = ? AND id = ? ;
Query OK, 0 rows affected (0.00 sec)

MySQL [mo_cloud]> set @account_id='018f7a6b_162b_7492_b5f0_cce7193ace7f';
Query OK, 0 rows affected (0.00 sec)

MySQL [mo_cloud]> set @user='admin';
Query OK, 0 rows affected (0.00 sec)

MySQL [mo_cloud]> set @id='f7945612-e27f-4bd8-b372-8cc596ea8eb6';
Query OK, 0 rows affected (0.00 sec)

MySQL [mo_cloud]> execute __mo_stmt_id_23 using @account_id,@user,@id;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.16 sec)

MySQL [mo_cloud]> SELECT count(*) FROM `mo_cloud`.`workbook` WHERE account_id = '018f7a6b_162b_7492_b5f0_cce7193ace7f' AND sql_user = 'admin' AND id = 'f7945612-e27f-4bd8-b372-8cc596ea8eb6';
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)
```

### Expected Behavior

Prepared SQL returns the same result with the non-prepared SQL

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud QA env

**Comment by DanielZhangQD** [comment]
Statement in the statement_info record:
```
| 018f7a6b-7a33-7917-930b-0e6ada4340a5 | /* 6 queries */
execute __mo_stmt_id_17 // prepare __mo_stmt_id_17 from SELECT count(*) FROM `mo_cloud`.`workbook` WHERE 1=1 AND account_id = ? AND sql_user = ? ; 018f7a6b_162b_7492_b5f0_cce7193ace7f ; admin;
execute __mo_stmt_id_18 // prepare __mo_stmt_id_18 from INSERT INTO `mo_cloud`.`workbook` (`id`,`account_id`,`sql_user`,`name`,`created_at`,`updated_at`) VALUES (?,?,?,?,?,?) ; f7945612-e27f-4bd8-b372-8cc596ea8eb6 ; 018f7a6b_162b_7492_b5f0_cce7193ace7f ; admin ; default ; 2024-05-15 04:03:35.166 ; 2024-05-15 04:03:35.166;
execute __mo_stmt_id_19 // prepare __mo_stmt_id_19 from SELECT * FROM `mo_cloud`.`workbook` WHERE 1=1 AND account_id = ? AND sql_user = ? ORDER BY updated_at DESC, name DESC LIMIT 100 ; 018f7a6b_162b_7492_b5f0_cce7193ace7f ; admin;
execute __mo_stmt_id_20 // prepare __mo_stmt_id_20 from SELECT count(*) FROM `mo_cloud`.`workbook` WHERE account_id = ? AND sql_user = ? AND id = ? ; 018f7a6b_162b_7492_b5f0_cce7193ace7f ; admin ; f7945612-e27f-4bd8-b372-8cc596ea8eb6;
execute __mo_stmt_id_21 // prepare __mo_stmt_id_21 from SELECT * FROM `mo_cloud`.`workbook_version` WHERE workbook_id = ? ORDER BY updated_at DESC ; f7945612-e27f-4bd8-b372-8cc596ea8eb6;
execute __mo_stmt_id_22 // prepare __mo_stmt_id_22 from SELECT count(*) FROM `mo_cloud`.`workbook_version` WHERE workbook_id = ? ; f7945612-e27f-4bd8-b372-8cc596ea8eb6 |
```

**Comment by sukki37** [comment]
table schema:
```sql
CREATE TABLE `workbook` (
`id` VARCHAR(128) NOT NULL,
`account_id` VARCHAR(128) DEFAULT NULL,
`sql_user` VARCHAR(128) DEFAULT NULL,
`name` VARCHAR(255) DEFAULT NULL,
`created_at` DATETIME DEFAULT NULL,
`updated_at` DATETIME DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `unq_account_name` (`account_id`,`sql_user`,`name`)
)
```

**Comment by ouyuanning** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/45346669/f07e53d1-05d6-4ddb-90c6-6c6c529c7395)
prepare stmt12 from SELECT count(*) FROM  `workbook` WHERE id = ? ;
execute stmt12 using  @id;
prepare stmt13 from SELECT count(*) FROM  `workbook` WHERE sql_user = ? AND id = ? ;
execute stmt13 using  @user,@id;
这两种能正确返回。
当有account_id的时候，会无法正常返回。

并且同一个commit id。我本地的plan会跟线上的不一样
![image](https://github.com/matrixorigin/matrixone/assets/45346669/c6feddc8-4205-477b-822d-990b2a476db2)
这个是我本地的。可以看到，我本地的block filter少了(workbook.account_id = cast('018f7a6b_162b_7492_b5f0_cce7193ace7f' AS VARCHAR))    这个条件。
感觉可以跟存储的同事一起看看。

1、为什么会多了这个筛选条件
2、多了这个筛选条件后，应该也能正确返回才对。

**Comment by daviszhen** [comment]
未投入

**Comment by LiSong0214** [comment]
这个bug 导致 MO Cloud 的 sql editor 无法使用，是个非常严重的回归 bug，建议尽快修复。

**Comment by daviszhen** [comment]
这个问题已经在的commit上，验证解决了。
到1.2dev的pr还没合并。

<img width="1400" alt="WeChatWorkScreenshot_471bc59c-706e-40ec-8b9f-40a68e238098" src="https://github.com/matrixorigin/matrixone/assets/60595215/4743f61f-356d-423f-9b79-a76f7a6f10b1">

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/pull/16257 已经merge 到1.2-dev

**Comment by heni02** [comment]
待验证和补充case

**Comment by heni02** [comment]
mo-cloud QA env commit:d36f88943 
confirm,closed
mysql> CREATE TABLE `workbook` (
    -> `id` VARCHAR(128) NOT NULL,
    -> `account_id` VARCHAR(128) DEFAULT NULL,
    -> `sql_user` VARCHAR(128) DEFAULT NULL,
    -> `name` VARCHAR(255) DEFAULT NULL,
    -> `created_at` DATETIME DEFAULT NULL,
    -> `updated_at` DATETIME DEFAULT NULL,
    -> PRIMARY KEY (`id`),
    -> UNIQUE KEY `unq_account_name` (`account_id`,`sql_user`,`name`)
    -> );
Query OK, 0 rows affected (0.03 sec)

mysql> insert into workbook values("f7945612-e27f-4bd8-b372-8cc596ea8eb6","018f7a6b_162b_7492_b5f0_cce7193ace7f","admin","mo","2023-09-03","2023-09-05");
Query OK, 1 row affected (0.05 sec)

mysql> prepare __mo_stmt_id_23 from SELECT count(*) FROM `mo_cloud`.`workbook` WHERE account_id = ? AND sql_user = ? AND id = ? ;
Query OK, 0 rows affected (0.01 sec)

mysql> set @account_id='018f7a6b_162b_7492_b5f0_cce7193ace7f';
Query OK, 0 rows affected (0.02 sec)

mysql> set @user='admin';
Query OK, 0 rows affected (0.01 sec)

mysql> set @id='f7945612-e27f-4bd8-b372-8cc596ea8eb6';
Query OK, 0 rows affected (0.02 sec)

mysql> execute __mo_stmt_id_23 using @account_id,@user,@id;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.07 sec)
