### ISSUE TITLE
[Bug]: insert into partition table select  too slow

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16143]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

can follow https://github.com/matrixorigin/matrixone/issues/16099

### Steps to Reproduce

```Markdown
can follow https://github.com/matrixorigin/matrixone/issues/16099
```

**Comment by jensenojs** [comment]
等正确性的问题解决了, 再来看性能问题
- https://github.com/matrixorigin/matrixone/issues/16100

**Comment by jensenojs** [comment]
同上, 还需要抓pprof看是读取snapshot慢还是其他的阶段慢

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
<img width="1024" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/a2255b9a-cb6b-4dc1-9b80-d934c2644034">

@YANGGMM 钊哥抓出的pprof, 看开销在protobuf那个地方.

**Comment by aressu1985** [comment]
和松哥沟通，挪到1.3.0进行解决

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by YANGGMM** [comment]
> @YANGGMM  这个问题还有嘛?

转给我，我关了吧，先看其他慢的问题
