### ISSUE TITLE
[Bug]:  restore cluster table，the result  is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16150]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2202e5c72981a6ee17fc7ed05f842fee866c9da8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="576" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e89f75d5-e709-43a8-9f9f-f8d33e37bdee">

### Steps to Reproduce

```Markdown
场景1:
use mo_catalog;
create cluster table clu01(col1 int, col2 decimal);
insert into clu01 values(1,2,0);

drop snapshot if exists sp01;
create snapshot sp01 for account sys;
insert into clu01 values(2,3,0);

restore account sys from snapshot sp01;

select * from clu01;  -->结果不对
```

**Comment by YANGGMM** [comment]
等待讨论的结果

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**commit：2df0f9c75aa90a3c7f1145c95f37616b15fbf566**
<img width="478" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/769335a4-c123-4cc6-bf9d-539de1f16199">

verified.
