### ISSUE TITLE
[Bug]: [date 5.15]tke regression: tpch100G q9 reported error send notify msg to dispatch operator timeout

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16169]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a9d2a5398

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9097631784/job/25007261855
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ee559337-a6a8-4445-b135-ac56e8b7e66c)
q9执行期间cn内存都大于50G：
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1715793079891&to=1715793931251&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-regression-20240515
<img width="1436" alt="企业微信截图_772d0db7-ae47-4f3d-915e-1fd4e5cf8d02" src="https://github.com/matrixorigin/matrixone/assets/113406637/9ea91e4e-a4af-4acb-ad46-b6aa784bf6f5">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22TL4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240515%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60send%20notify%20msg%20to%20dispatch%20operator%20timeout%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221715786460000%22,%22to%22:%221715786470000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile：
[tpch100g_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/15329398/tpch100g_profile.tar.gz)

### Steps to Reproduce

```Markdown
tke regression  tpch100G test
```

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9107226969/job/25036812846
又跑了一次，q9又出现了这个问题。似乎是个必现的，可以二分找一下

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/16145
这个pr里引入了一个错误，
将在https://github.com/matrixorigin/matrixone/pull/16173 这个pr里一并修复

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm，closed
commit：8f898031e
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9114235510/job/25059140520
