### ISSUE TITLE
[Bug]: The number of error rows reported for deleting data is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16168]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fe31f8ae619bebde80dcacb917307235e134ef56

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="510" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/650c3249-eae8-4d13-a3eb-3f6ab4b654d6">

### Expected Behavior

删除的正确行数

### Steps to Reproduce

```Markdown
小数据量正常

10w数据量复现步骤：
mysql -h 127.0.0.1 -P 6001 -udump -p111
create database sysbench_db;

本地 git clone https://github.com/matrixorigin/mo-sysbench.git

sysbench  --mysql-host=172.16.24.85 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10 cleanup

sysbench  --mysql-host=172.16.24.85 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10 --auto_inc=off prepare

mysql -h 127.0.0.1 -P 6001 -udump -p111
use sysbench_db;
select count(*) from sbtest1;
select count(*) from sbtest1 where id > 50000;
delete from sbtest1 where id > 50000;     -->出错位置
```

**Comment by jensenojs** [comment]
休假中

**Comment by jensenojs** [comment]
<img width="1492" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b78ad0d7-766c-42a0-85fb-c7564e62175c">

有两个merge delete, 其中一个affactRows是50000, 另一个是8192, 这里有两个`mergeDelete`的原因应该是有个隐藏表, 设置affact rows的时候以主表的值为准就可以了. 

<img width="727" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/4f60df6a-c623-42da-a028-f43820a7829d">

不过不确定要不要看一下这个8192是怎么来的..

**Comment by Ariznawlll** [comment]
**commit: 015a9755408089f7b5b8d7bbee70ea179180ccbb**
<img width="466" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/0d7f3385-5ce4-44bc-b427-784e756a8889">

verified.
