### ISSUE TITLE
[Bug]: [date 5.15]tke regression: sysbench100w random_points lost connection to mo which not service stoped

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16176]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a9d2a5398713fbfde4a511206b904692531f4c00

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9097455949/job/25005513964
<img width="1160" alt="企业微信截图_5ec41631-c066-4df4-bec1-dce8ed8ce542" src="https://github.com/matrixorigin/matrixone/assets/113406637/90ead8bc-d35f-4050-bb6b-8edd8f40dd30">

报错时间的内存占用225G
<img width="1104" alt="企业微信截图_4ed5021b-ef34-47e6-9101-563b9fb9d9a1" src="https://github.com/matrixorigin/matrixone/assets/113406637/3efb9b9d-c53e-42c8-8fdb-40f261e2b394">

profile：
[main_profile_0516.tar.gz](https://github.com/matrixorigin/matrixone/files/15330407/main_profile_0516.tar.gz)

mo log has been set to location

### Steps to Reproduce

```Markdown
sysbench100w random_points test
```

**Comment by daviszhen** [comment]
![Selection_006](https://github.com/matrixorigin/matrixone/assets/60595215/984be9dd-e24d-44f8-996e-fe165bf098ef)
![Selection_009](https://github.com/matrixorigin/matrixone/assets/60595215/ab57797e-7a0b-41be-8d78-4d0609ddcbcf)

**Comment by daviszhen** [comment]
![Selection_007](https://github.com/matrixorigin/matrixone/assets/60595215/ff134749-5ca8-4822-b95c-9a7f5e072449)
![Selection_008](https://github.com/matrixorigin/matrixone/assets/60595215/6b695b04-769a-4f07-a94e-3f7a02fdf144)

**Comment by heni02** [comment]
修改max-active-ages ='20min'复现再定位

**Comment by daviszhen** [comment]
等sysbench卡住问题解决后，再测试。

**Comment by daviszhen** [comment]
等sysbench卡住问题解决后，再测试。

**Comment by daviszhen** [comment]
现在时tpcc oom

**Comment by heni02** [comment]
先降级
