### ISSUE TITLE
[Bug]: [Sqlancer] execute the query of select failed 

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#1617]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table table_float (id_1 int, col_float_1 float(23));
insert into table_float (id_1, col_float_1) values (65535, -1.000000), (123, 1.500000), (1, 0.500000), (1, -0.100000), (65535, 0.500000), (1, -0.100000), (1, 0.100000), (123, 0.100000), (65535, -0.100000), (0, -0.100000), (1, 0.000000), (0, 1.500000), (123, 1.000000), (0, 0.500000), (1, 0.500000), (1, 0.100000), (1, 0.000000);

mysql> select table_float.id_1 as col_1, table_float.col_float_1 as col_2 from table_float where 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by iamlinjunhong** [comment]
<img width="1627" alt="截屏2022-01-17 下午3 00 57" src="https://user-images.githubusercontent.com/49111204/149722397-e54ebca0-b942-415d-84a5-faa962267a8f.png">

**Comment by m-schen** [comment]
this question is similar to #1586.

**Comment by nnsgmsone** [comment]
fixed by 1619
