### ISSUE TITLE
[Feature Request]: publish-subscribe enhancement phase 2

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#16188]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

PRD：https://doc.weixin.qq.com/doc/w3_AZUAugYIAOcKTNjDuYAT1is3i8prQ?scode=AJsA6gc3AA8k71X7lGAZUAugYIAOc

**Comment by LiSong0214** [comment]
https://github.com/matrixorigin/MO-Cloud/issues/2480

**Comment by Ariznawlll** [comment]
功能测试已完成

**Comment by ck89119** [comment]
多账号性能测试及线上数据升级测试进行中

**Comment by Ariznawlll** [comment]
多个账号发布给一个账号，show subscriptions性能：

commit: dadbdfda0

测试步骤：
1. 脚本创建acc001-acc500: acc001-acc500用于创建发布db给acc1000
[createAccount.txt](https://github.com/user-attachments/files/16782597/createAccount.txt)

2. acc001-acc500创建db，插入数据，并发布给acc1000:
[pub.txt](https://github.com/user-attachments/files/16782652/pub.txt)

3. acc1000租户中使用show subscriptions all命令查看所有有权限的发布
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/cf4ae3e1-9ad4-4577-857f-d87f67868c8d">

耗时：0.01s

**Comment by allengaoo** [comment]
already verified. @yangj1211  , please add  document for this feature.
