### ISSUE TITLE
[Bug]: tpcc benchmark performance big degradation

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16202]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8f898031e4e205d22804bcf1a914d3824feb150e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Good: a9d2a5398713fbfde4a511206b904692531f4c00
Bad: 8f898031e4e205d22804bcf1a914d3824feb150e

One commit below caused the performance degradation
<img width="1298" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/4bbb09a4-4931-4f52-925c-b3f0809a90a0">

### Steps to Reproduce

```Markdown
Run TPCC
```

**Comment by reusee** [comment]
related PR reverted
