### ISSUE TITLE
[Tech Request]: Save the record count of the query result and the real sql in the query meta

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#16210]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Refer to https://github.com/matrixorigin/matrixone/issues/14015#issuecomment-2116625328
```

### Why is this needed ?

The user can get the record count of the query result and the real SQL easily.

**Comment by daviszhen** [comment]
增加字段
更新升级逻辑

**Comment by daviszhen** [comment]
pr中

**Comment by daviszhen** [comment]
修改已经merge。

多出来两个字段：
savedRowCount ： 查询结果里面的保存的行数。
queryRowCount：查询总行数。

业务端的逻辑需要判断这两个字段是否存在，不存在用原来的逻辑，存在就设计新的逻辑。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/1ddceb37-4794-4b8d-897b-8cdde062e09c)

**Comment by heni02** [comment]
测试验证两者的值还是不相同 cc @daviszhen 
测试环境：mo-cloud commit：1.2-dev 8d3180bc7
<img width="466" alt="企业微信截图_d8be3e39-6286-453d-846e-241f490f6b97" src="https://github.com/matrixorigin/matrixone/assets/113406637/1b16b42f-5852-46f2-a90e-6a5b9fe01a9c">

测试结果：
<img width="1310" alt="企业微信截图_6169f2ce-86d2-40a5-a697-e50fb67d04ac" src="https://github.com/matrixorigin/matrixone/assets/113406637/feb122e3-698a-4be2-82f5-93055c8272da">
<img width="751" alt="企业微信截图_a0db6e2c-3e6d-4130-b08b-561170877f8c" src="https://github.com/matrixorigin/matrixone/assets/113406637/45d02e4b-f3e1-4302-ac9b-09e0c09e2267">

测试sql：
Run the SQL with TPCH 1G:

select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem;

**Comment by heni02** [comment]
测试环境：1.2-dev mo-cloud commit：8d3180bc7
<img width="418" alt="企业微信截图_c338937d-cd87-40ff-a189-6aabdd0e60ce" src="https://github.com/matrixorigin/matrixone/assets/113406637/9b88156a-fa58-4d74-8afa-a4368bc1b34c">

测试sql：
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem
union
select
  *
from
  lineitem;

测试结果：result_count和meta queryrowcount结果一致
<img width="1351" alt="企业微信截图_12c96430-0714-4b2a-8b55-37bf40a53da2" src="https://github.com/matrixorigin/matrixone/assets/113406637/9f1e337f-1b23-4756-85ef-e05cd77a03f0">
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7fc997d0-0b58-48d7-aa69-58f25349750d)

**Comment by heni02** [comment]
test done
