### ISSUE TITLE
[Bug]: misuse of unsafe vector.GetStringAt 

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16235]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.2-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

vector.GetStringAt is unsafe and it is misused in some places.

### Steps to Reproduce

```Markdown
Read code
```

**Comment by XuPeng-SH** [comment]
@jensenojs 这个实际上是很多模块owner要做的，我那个pr是把几个明显的问题先解决掉

**Comment by XuPeng-SH** [comment]
@ouyuanning please investigate this problem in your modules

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
在处理w-w和prepare，还没时间处理

**Comment by ouyuanning** [comment]
这周处理

**Comment by ouyuanning** [comment]
还没时间清理

**Comment by XuPeng-SH** [comment]
pending
