### ISSUE TITLE
[Bug]: [date 5.19]tke regression: mo reported error no such table sysbench_db.sbtest9

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16232]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fae5807be

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9148415689/job/25154937743
<img width="1072" alt="企业微信截图_885d325f-465d-4131-8508-23568b737c25" src="https://github.com/matrixorigin/matrixone/assets/113406637/1d6c7bb8-c723-438a-905e-4f78a92a35ef">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22ya3%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240519%5C%22%7D%20%7C%3D%20%60no%20such%20table%20sysbench_db.sbtest9%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716154940507%22,%22to%22:%221716155264102%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
sysbench100w write_only 1000 test
```

**Comment by jensenojs** [comment]
通过mo-log的链接, 搜索sbtest9, 扫出来的日志, 这里截取的是日志的两个片段, 

第一个片段是在执行了大量的`DELETE FROM sbtest9 xxx`之后, 在`21:44:09.640`以及随后的日志中显示这个表被删除了. 随后有一系列的报错是`table sbtest9 does not exist`的, 应该算属于预期结果内的.
<img width="1714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b624bd07-66cc-4934-8a27-c8f7c57dc057">

跟本issue相关的日志在下面, 在`21:44:10.478`重新创建了`sbtest9`之后, `21:44:11.166`往这个表里面插入数据的时候仍然显示`no such table sysbench_db.sbtest9`
<img width="1714" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/fbc89d2b-512a-4f75-858d-d4c6a696f131">

**Comment by jensenojs** [comment]
向韩枫哥请教了一下, 通过日志把问题定位得更准确了一些, 初步怀疑cn的时间戳有问题, 不知道是什么东西引起的(事务重试?), 下面是诊断的过程.

1. 从`21:44:11.478`可以看到新建的 sbtest9 的 id 是 273407
   - 于此同时在`21:44:11.239`中刷盘的是 sbtest9 是273393, 是之前drop掉的

2. 但是从后面的日志可以看出(下图第一行), cn是可以正常提交 273407 的 drop 请求的
<img width="1540" alt="企业微信截图_73d1f424-61e4-462d-9486-26ed18dee805" src="https://github.com/matrixorigin/matrixone/assets/56761542/c78b9afc-55cb-4f95-b764-eb24e9845a10">
 
因此新建的273407在tn是成功了, cn因为某种原因, 在1s中后没有看到, 4秒后却能正常的删除, 下图的第二行能反映是真的往 273407 里插入了 1392 行数据，删除了 230 行数据
![image](https://github.com/matrixorigin/matrixone/assets/56761542/7b552322-2571-4a46-862c-cbc3584f9e43)

所以cn 找不到 273407 应该是不成立的, 可能是哪里的时间戳出了wenti

**Comment by jensenojs** [comment]
在高并发事务执行期间, 没有sync commit. 不保证外部一致性.

**Comment by heni02** [comment]
confirm，closed
