### ISSUE TITLE
[Bug]: buffer busy

### ISSUE THREAD

**Issue by wanglei4687** [matrixorigin/matrixone#1624]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ba7a6917c50cad1ff795f57407767cf115bd72cf
- Hardware parameters:
- OS type:
- Others:
MatrixOne build info:
The golang version used to build this binary is: go version go1.17.3 linux/amd64
The git branch name is: main
Last git commit ID: ba7a6917c50cad1ff795f57407767cf115bd72cf
```

### Actual Behavior

mysql-tester log
<img width="701" alt="截屏2022-01-19 下午3 17 14" src="https://user-images.githubusercontent.com/74483764/150084215-a08ed03f-7cc6-487b-9e94-bd8e1ed47cff.png">

first node log 
<img width="1627" alt="截屏2022-01-19 下午3 19 49" src="https://user-images.githubusercontent.com/74483764/150084256-ded3bab4-cbc1-4b3d-b795-6c36122b30ca.png">
[matrixone_mo-0_mo.log](https://github.com/matrixorigin/matrixone/files/7895123/matrixone_mo-0_mo.log)

second node log 
[matrixone_mo-1_mo.log](https://github.com/matrixorigin/matrixone/files/7895148/matrixone_mo-1_mo.log)

third node log
[matrixone_mo-2_mo.log](https://github.com/matrixorigin/matrixone/files/7895129/matrixone_mo-2_mo.log)

next run log
<img width="1740" alt="截屏2022-01-19 下午3 27 20" src="https://user-images.githubusercontent.com/74483764/150084397-941a2077-a2de-4894-b296-ea5f5022f4c1.png">

configuration
node0
[system_vars_config.txt](https://github.com/matrixorigin/matrixone/files/7895094/system_vars_config.txt)
node1 
[system_vars_config2.txt](https://github.com/matrixorigin/matrixone/files/7895108/system_vars_config2.txt)
node2
[system_vars_config3.txt](https://github.com/matrixorigin/matrixone/files/7895114/system_vars_config3.txt)

### Expected Behavior

panic or more info about this problem

**Comment by daviszhen** [comment]
I am trying to fix it.
