### ISSUE TITLE
[Bug]: The log reports an error message "bzip2 data invalid", but the front end does not return an error.

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16250]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6ff549f54

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9154938692
<img width="1481" alt="企业微信截图_af96b052-9ab3-4a63-857a-6b3cae91c033" src="https://github.com/matrixorigin/matrixone/assets/113406637/91d57b59-7d26-4ac4-9b48-c1aa4d08210e">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240520%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716190082822%22,%22to%22:%221716193620430%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
[2024-05-20_16_00_31.zip](https://github.com/matrixorigin/matrixone/files/15374987/2024-05-20_16_00_31.zip)

### Steps to Reproduce

```Markdown
ddl:
create table table_100_columns(
clo1 tinyint,
clo2 smallint,
clo3 int,
clo4 bigint,
clo5 tinyint unsigned,
clo6 smallint unsigned,
clo7 int unsigned,
clo8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(5,2),
col17 text,
col18 varchar(255),
col19 varchar(255),
col20 varchar(255),
col21 varchar(255),
col22 varchar(255),
col23 varchar(255),
col24 varchar(255),
col25 varchar(255),
col26 varchar(255),
col27 varchar(255),
col28 varchar(255),
col29 varchar(255),
col30 varchar(255),
col31 varchar(255),
col32 varchar(255),
col33 varchar(255),
col34 varchar(255),
col35 varchar(255),
col36 varchar(255),
col37 varchar(255),
col38 varchar(255),
col39 varchar(255),
col40 varchar(255),
col41 varchar(255),
col42 varchar(255),
col43 varchar(255),
col44 varchar(255),
col45 varchar(255),
col46 varchar(255),
col47 varchar(255),
col48 varchar(255),
col49 varchar(255),
col50 varchar(255),
col51 varchar(255),
col52 varchar(255),
col53 varchar(255),
col54 varchar(255),
col55 varchar(255),
col56 varchar(255),
col57 varchar(255),
col58 varchar(255),
col59 varchar(255),
col60 varchar(255),
col61 varchar(255),
col62 varchar(255),
col63 varchar(255),
col64 varchar(255),
col65 varchar(255),
col66 varchar(255),
col67 varchar(255),
col68 varchar(255),
col69 varchar(255),
col70 varchar(255),
col71 varchar(255),
col72 varchar(255),
col73 varchar(255),
col74 varchar(255),
col75 varchar(255),
col76 varchar(255),
col77 varchar(255),
col78 varchar(255),
col79 varchar(255),
col80 varchar(255),
col81 varchar(255),
col82 varchar(255),
col83 varchar(255),
col84 varchar(255),
col85 varchar(255),
col86 varchar(255),
col87 varchar(255),
col88 varchar(255),
col89 varchar(255),
col90 varchar(255),
col91 varchar(255),
col92 varchar(255),
col93 varchar(255),
col94 varchar(255),
col95 varchar(255),
col96 varchar(255),
col97 varchar(255),
col98 varchar(255),
col99 varchar(255),
col100 varchar(255)
);
load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='compressed_file/100000000_100_columns_load_data.csv.bz2', 'compression'='bz2'} into table test.table_100_columns fields terminated by ',' lines terminated by '\n' parallel 'true';
```

**Comment by heni02** [comment]
使用bzip2命令压缩10万数据量文件，load成功
<img width="767" alt="企业微信截图_bff8cde2-3096-4592-8ae3-476e3ae90e17" src="https://github.com/matrixorigin/matrixone/assets/113406637/6c248204-5b1b-4bc0-90c1-134ecba136e5">
<img width="1393" alt="企业微信截图_ef133b3b-0f3f-41ff-80a2-eb5adf4e5778" src="https://github.com/matrixorigin/matrixone/assets/113406637/7b18aef0-4ea5-4c69-b6fe-a388633d4c7d">
估计是1亿该文件压缩问题，重新压缩再试下

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
may dup with ?
- https://github.com/matrixorigin/MO-Cloud/issues/3482

**Comment by jensenojs** [comment]
等moc3482给fix后再看看

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
proxy 与 mo 网络断开导致mo检测到的错误 发送不到proxy. 而proxy 与 client之间的链接没有断开。

![image](https://github.com/user-attachments/assets/a01c18ea-fbfa-4f3b-a6bb-eae19960db73)

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240520%5C%22%7D%20%7C%3D%20%60connectionId%2052%7C%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716190082822%22,%22to%22:%221716193620430%22%7D%7D%7D&schemaVersion=1&orgId=1


proxy 与 mo的链接信息。

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240520%5C%22%7D%20%7C%3D%20%6010.143.222.93:46084%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716190082822%22,%22to%22:%221716193620430%22%7D%7D%7D&schemaVersion=1&orgId=1

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240520%5C%22%7D%20%7C%3D%20%6010.143.222.100:47492%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716190082822%22,%22to%22:%221716193620430%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
后期没再出现

**Comment by heni02** [comment]
没有再复现，先closed，若有新问题再提issue
