### ISSUE TITLE
[Bug]: restore report table "mo_foreign_keys" does not exist.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16262]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fae5807be9d8c1a3ba862d522498f036de6a37f2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

偶现：

<img width="616" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1dea5095-4a53-49ee-be90-af926cc1415e">

log：
[wl.log](https://github.com/matrixorigin/matrixone/files/15376174/wl.log)

### Expected Behavior

restore successfully.

### Steps to Reproduce

```Markdown
1. load tpcc 10 warehouse data
2. mysql -h 127.0.0.1 -P 6001 -udump -p111
   create snapshot sp_01 for account sys;
3. 在mo-tpcc工具下跑10-10测试；
4. mysql -h 127.0.0.1 -P 6001 -udump -p111
   create snapshot sp02 for account sys;
5. 在mo-tpcc工具下跑10-10测试；
6. restore account sys from snaoshot sp_01;
```

**Comment by YANGGMM** [comment]
```mysql
mysql> create snapshot sp_01 for account sys;
Query OK, 0 rows affected (0.04 sec)
```

run tpcc test
<img width="659" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/72dd512d-c048-42db-9d7b-8d48da0eeb46">

**Comment by YANGGMM** [comment]
无法复现，等 https://github.com/matrixorigin/matrixone/issues/16100 解决之后再看

**Comment by YANGGMM** [comment]
无法复现，等 https://github.com/matrixorigin/matrixone/issues/16100 解决之后再看

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
#16100 已经解决，麻烦再测一下，@Ariznawlll

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/pull/16567

**Comment by Ariznawlll** [comment]
**commit: 09c4d95dcdc615e1ea924239ff72af8c7863e286**
```
create database tpcc;
use tpcc;
建表：https://github.com/matrixorigin/mo-tpcc/blob/main/sql/tableCreates.sql

load 数据：

创建快照：create snapshot sp01 for account sys;

本地：git clone https://github.com/matrixorigin/mo-tpcc.git
执行tpcc 10-100测试：./runBenchmark props.mo

连接mo: mysql -h 127.0.0.1 -P 6001 -udump -p111

restore account sys database tpcc from snapshot sp01;
```
<img width="549" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/1f02585e-2615-4673-b23d-406061ac76e7">

测试通过.
