### ISSUE TITLE
[Bug]: [date 5.20]tke regression: sysbench1000w read_write test mo reported panic runtime error: integer divide by zero

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16275]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

83d52f568

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9160375111/job/25203804989
<img width="1014" alt="企业微信截图_6fc147cb-35c3-48bb-a096-0297dc0569b8" src="https://github.com/matrixorigin/matrixone/assets/113406637/28fd7dc5-048e-48e4-a21e-ba05dd7a4e42">

mo log:
{"level":"ERROR","time":"2024/05/21 02:18:58.157033 +0000","caller":"vm/vm.go:121","msg":"error: internal error: panic runtime error: integer divide by zero: \nruntime.panicdivide\n\t/usr/local/go/src/runtime/panic.go:240\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.collectBatchInfo\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion/types.go:258\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Argument).SplitBatch\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion/types.go:189\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Argument).remoteDelete\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion/deletion.go:105\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Argument).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion/deletion.go:76\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:43\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:156\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:250\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:437\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:296\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:230\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650","span":{"trace_id":"d588648c-06f1-8afd-ce13-73355aa45122","span_id":"4a6ec81064d6c745","kind":"remote"}}

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240520%5C%22%7D%20%7C%3D%20%60panic%20runtime%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716257743471%22,%22to%22:%221716258627107%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
[2024-05-21_10_18_16.zip](https://github.com/matrixorigin/matrixone/files/15384033/2024-05-21_10_18_16.zip)

### Steps to Reproduce

```Markdown
tke sysbench1000w read_write 100threads
```

**Comment by ouyuanning** [comment]
感觉像是这个https://github.com/matrixorigin/matrixone/pull/16103 引入的。
deletion的 Nbucket好像有在用
![image](https://github.com/matrixorigin/matrixone/assets/45346669/b3f37d52-afa6-48bd-99f3-71afb0a1f4a7)

**Comment by badboynt1** [comment]
panic已修复

**Comment by heni02** [comment]
confirm，closed
commit：8a5f0bd44
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9256599329/job/25463438827
