### ISSUE TITLE
[Bug]: [date 5.20]tke regression: mo database exists but reported error Can't drop database 'sysbench_db'; database doesn't exist

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16273]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

83d52f568

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9160375111/job/25197813039
<img width="1056" alt="企业微信截图_5c860006-2230-4c0b-9cc9-f82fc4bacebb" src="https://github.com/matrixorigin/matrixone/assets/113406637/7c218527-6bb0-47d3-89fe-ddf7bac63cfe">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240520%5C%22%7D%20%7C%3D%20%60Can%27t%20drop%20database%20%27sysbench_db%27%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716245864817%22,%22to%22:%221716246188412%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
plz contact me
<img width="1036" alt="企业微信截图_e27de4d7-51c6-4baa-b966-54d095a9c1bd" src="https://github.com/matrixorigin/matrixone/assets/113406637/e0e62500-5f2d-4eb9-92ed-f1b87e8455ea">

### Steps to Reproduce

```Markdown
tke regression sysbench test
```

**Comment by ouyuanning** [comment]
不知道是否跟 16232 是一个事情

**Comment by Ariznawlll** [comment]
**commit**：e4c504a606585cb373a5bb7c452e804469716610
**job url**：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9211125528/job/25359635621
<img width="1361" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/444ecb37-4bc8-4bf5-8d62-d337c83e4c0c">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22JM6%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240523%5C%22%7D%20%7C%3D%20%60database%20doesn%27t%20exist%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by heni02** [comment]
date 6.2 tke regression 复现了
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9339030269/job/25715192203
<img width="1309" alt="企业微信截图_dc54bb25-82c4-4647-b25c-6ce1027fb758" src="https://github.com/matrixorigin/matrixone/assets/113406637/c443026b-c4fa-4789-b28a-93855b1e9ed2">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22_0q%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240602%5C%22%7D%20%7C%3D%20%60database%20doesn%27t%20exist%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717398475579%22,%22to%22:%221717398536015%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
报错的SQL的txn-id为`018fdced92887d0396ea99fddd0bf425`

<img width="1875" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/7c04c10d-52e1-4e20-8e67-dafce68c35a9">

而在这之前, tn这边有一个precommit的记录是删除`sysbench_db`的, 并且这个txn-id是`018fdced8de672119444840ea08421ea`, 两者不一致, 需要确认一下这个precommit的记录是不是合理的.

<img width="1951" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/927ede7d-1ac8-4ca8-aacc-a7e19506a3cb">


> date 6.2 tke regression 复现了 job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9339030269/job/25715192203 <img alt="企业微信截图_dc54bb25-82c4-4647-b25c-6ce1027fb758" width="1309" src="https://private-user-images.githubusercontent.com/113406637/336000486-c443026b-c4fa-4789-b28a-93855b1e9ed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODY2NjEsIm5iZiI6MTcxNzQ4NjM2MSwicGF0aCI6Ii8xMTM0MDY2MzcvMzM2MDAwNDg2LWM0NDMwMjZiLWM0ZmEtNDc4OS1iMjhhLTkzODU1YjFlOWVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNzMyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2QwODJjZmQyNWFkODNhOThlNmYyYmJjMTA0YTNjYmJhYjA0M2EyZThkMzk5NWUyM2IxZTA4YTAzN2U1ZjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3SCZ-JBv6jK_4nsoZvHuGNJ9FSsBN0dZZrSCPXUkNmI">
> 
> mo log： https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22_0q%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240602%5C%22%7D%20%7C%3D%20%60database%20doesn%27t%20exist%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717398475579%22,%22to%22:%221717398536015%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
关于no such table的问题, 不确定是不是同一个问题.

在`2024-06-03 06:31:07.072 `有 txn-id : `018fdccb604070c386f6183ca9369095`报错no tuch table sysbench_db.sbtest1

<img width="1952" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/40f05624-8cb3-433b-bd35-32c474f3fb51">


但是在`2024-06-03 06:31:07.299`才有txn-id : `018fdccb612176dcbf07f75ac669c8d9`进行一个删除. 
<img width="1836" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/6ed8e4ca-e163-4b60-a7c4-3e2083a3b6f2">

snapshot在日志中没有找到

**Comment by ouyuanning** [comment]
目前能了解到大概的原因是，之前有另外的一个事务已经drop 过这个database了。但是为什么还不知道。
会依赖罗飞帮忙一起处理。罗飞事情较多，风险较大。

**Comment by triump2020** [comment]
基本定位, 外部一致性导致的，需要调整 DDL 时的加锁姿势。 

出现此问题的时序： 
时序： 1.  drop database sbtest, 提交成功  2. create databse sbtest 提交 成功 , 3.  drop database sbtest(在不同的CN , 且分配了一个小的start ts , 所以看不见sbtest， 因为logtail 没过来) ;

**Comment by triump2020** [comment]
drop databse 之前 sleep 几秒，可以规避掉这个问题.

**Comment by ouyuanning** [comment]
待补充日志再定位问题

**Comment by jensenojs** [comment]
等待验证

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by heni02** [comment]
没有再出现该问题
confirm，closed
