### ISSUE TITLE
[Bug]: restore report 'r-w conflict'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16278]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

68a9d5618cd84d56c32c1d4252a8d0ed7c11b195

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

偶现
<img width="653" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/126be915-6f28-47f3-b1fd-3061475f7651">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22a0v%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240520%5C%22%7D%20%7C%3D%20%60r-w%20conflict%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

restore success.

### Steps to Reproduce

```Markdown
please contact me， i will give you a test document.
```

**Comment by YANGGMM** [comment]
```msyql
{"level":"INFO","time":"2024/05/21 03:13:12.777126 +0000","name":"cn-service.frontend","caller":"frontend/snapshot.go:419","msg":"[sp02] start to restore table: bmsql_new_order","uuid":"37633835-3166-3366-3463-363939363638"}

{"level":"ERROR","time":"2024/05/21 03:16:58.778893 +0000","name":"cn-service.frontend","caller":"frontend/util.go:493","msg":"query trace status","uuid":"37633835-3166-3366-3463-363939363638","statement":"restore account sys database tpcc_10 table bmsql_new_order from snapshot sp02","status":"fail","error":"r-w conflict","session_info":"connectionId 24734|10.128.0.124:1572|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 357501|018f98d2-100e-7e42-91e1-b45204e469fe","session_id":"018f98d2-100e-7e42-91e1-b45204e469fe","statement_id":"018f9923-8446-795d-8cb3-ed4b302d64d4","span":{"trace_id":"45ce8959-4f87-b8f5-3ed2-a080266c9a95","span_id":"d2101775fad4b05c"}}
```

**Comment by YANGGMM** [comment]
<img width="1287" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/29312f24-d6b5-4e0e-a7cb-c83202791a3a">

**Comment by triump2020** [comment]
r-w 已经有解决方案，下周开始解决

**Comment by triump2020** [comment]
@Ariznawlll   Pls test.

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**commit：3b0e6b1d83b5cb4ea78d7545d2df26f5a0d77a00**
<img width="691" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/68cb69f7-6663-48b9-b7bd-fce1eb1a10cd">
verified.
