### ISSUE TITLE
[Bug]: dn panic occasionally when restore.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16282]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

68a9d5618cd84d56c32c1d4252a8d0ed7c11b195

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

分布式环境：

<img width="739" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/58f2af6a-17f5-4504-9478-f525425cbfcf">

pod status:
<img width="559" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/16b592ff-9891-4d44-b287-e2b86f9df626">

<img width="1423" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b9599f2d-c112-4e5c-92bf-52d9fc2ad082">

log:https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Ib3%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240520%5C%22%7D%20%7C%3D%20%60panic:%20runtime%20error:%20invalid%20memory%20address%20or%20nil%20pointer%20dereference%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
please contact me， i will give you a test document.

基于以上文档，执行下面的sql：
restore account sys database tpcc_10 table bmsql_new_order from snapshot sp03;
```

**Comment by YANGGMM** [comment]
```mysql
{"level":"INFO","time":"2024/05/21 04:02:41.590287 +0000","name":"cn-service.frontend","caller":"frontend/snapshot.go:419","msg":"[sp03] start to restore table: bmsql_new_order","uuid":"37633835-3166-3366-3463-363939363638"}

{"level":"ERROR","time":"2024/05/21 04:06:27.269109 +0000","name":"cn-service.frontend","caller":"frontend/util.go:493","msg":"query trace status","uuid":"37633835-3166-3366-3463-363939363638","statement":"restore account sys database tpcc_10 table bmsql_new_order from snapshot sp03","status":"fail","error":"the connection has been disconnected","session_info":"connectionId 24734|10.128.0.124:1572|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 357501|018f98d2-100e-7e42-91e1-b45204e469fe","session_id":"018f98d2-100e-7e42-91e1-b45204e469fe","statement_id":"018f9950-d133-7bf5-9cb7-10eb65e15e49","span":{"trace_id":"45ce8959-4f87-b8f5-3ed2-a080266c9a95","span_id":"d2101775fad4b05c"}}
```

**Comment by LeftHandCold** [comment]
fixed by #16369

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**commit：593693a4d36d152b28e10facf70f5ab66f7af051**
<img width="733" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/67b91d3b-7e0a-4d08-8888-f4ad8ade1e68">
没出现

**Comment by Ariznawlll** [comment]
**commit：3b0e6b1d83b5cb4ea78d7545d2df26f5a0d77a00**
<img width="681" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6ced8167-edc6-4129-af69-22d9223d65be">

执行两次没出错，先关掉
