### ISSUE TITLE
[Bug]: restore report 'invalid database db_name'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16288]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

68a9d56

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

集群环境：db存在，但是恢复的时候报错invalid database sysbench_db（集群是昨天起的，恢复的是大概18h前的数据）

<img width="822" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/24e0bab4-57a7-4e01-bb32-f3b8a9899b3e">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Ib3%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240520%5C%22%7D%20%7C%3D%20%60invalid%20database%20sysbench_db%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

restore successfully.

### Steps to Reproduce

```Markdown
please contact me， i will give you a test document.

基于以上文档，执行下面的sql
restore account sys database sysbench_db table sbtest99 from snapshot sp04;
restore account sys database sysbench_db from snapshot sp04;
```

**Comment by YANGGMM** [comment]
```mysql
mysql> show tables;
+-----------------------+
| Tables_in_sysbench_db |
+-----------------------+
| sbtest90              |
| sbtest92              |
| sbtest93              |
| sbtest94              |
| sbtest97              |
+-----------------------+
87 rows in set (0.03 sec)

mysql> 
mysql> 
mysql> create snapshot sp05 for account sys;
Query OK, 0 rows affected (0.05 sec)

mysql> drop table sbtest90;
Query OK, 0 rows affected (0.03 sec)

mysql> drop table sbtest92;
Query OK, 0 rows affected (0.02 sec)

mysql> drop table sbtest93;
Query OK, 0 rows affected (0.02 sec)

mysql> drop table sbtest94;
Query OK, 0 rows affected (0.03 sec)

mysql> drop table sbtest97;
Query OK, 0 rows affected (0.03 sec)


mysql> restore account sys database sysbench_db from snapshot sp05;
Query OK, 0 rows affected (18.59 sec)

mysql> show tables
+-----------------------+
| Tables_in_sysbench_db |
+-----------------------+
| sbtest90              |
| sbtest92              |
| sbtest93              |
| sbtest94              |
| sbtest97              |
+-----------------------+
```

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2024/05/21 06:41:49.967643 +0000","name":"cn-service.frontend","caller":"frontend/util.go:493","msg":"query trace status","uuid":"37633835-3166-3366-3463-363939363638","statement":"show full tables from sysbench_db like sbtest99","status":"fail","error":"invalid database sysbench_db","session_info":"connectionId 24734|10.128.0.124:1572|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 357501|018f98d2-100e-7e42-91e1-b45204e469fe","background":true,"session_id":"018f99e2-838c-72bb-a9f0-3fb4be42a5ee","span":{"trace_id":"45ce8959-4f87-b8f5-3ed2-a080266c9a95","span_id":"d2101775fad4b05c"}}

**Comment by YANGGMM** [comment]
<img width="485" alt="企业微信截图_9e108ec3-1a9f-4a83-9c68-997ea7a03d9f" src="https://github.com/matrixorigin/matrixone/assets/26563383/012ce568-3d89-49bd-aaed-110ca4adea46">

**Comment by Ariznawlll** [comment]
sp04对应的db中没有表，正常，关掉
