### ISSUE TITLE
[Bug]: performance：standalone tpcc test performance down around 20%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16291]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fae5807

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

5.17号到5.18号tpcc100/500/1000仓性能有下降，大概3000-4000左右
<img width="1367" alt="企业微信截图_71dbf127-f5db-488e-90d0-8228f8b975d6" src="https://github.com/matrixorigin/matrixone/assets/113406637/71b78a4b-c133-45e9-8444-53386ee51bca">

二分后查到该pr开始有下降
<img width="1359" alt="企业微信截图_c57437ae-77e5-4763-8438-158fed5bc400" src="https://github.com/matrixorigin/matrixone/assets/113406637/3092eb96-d730-4b8e-9e95-2c28ccae8883">

### Steps to Reproduce

```Markdown
standalone tpcc test
```

**Comment by reusee** [comment]
TPCC性能降低的原因是，新的分配器会触发更多GC，使用更多cpu，导致性能降低

如果将GOGC设置成200，新分配器的TPCC性能会和旧分配器的一样，但峰值内存会更低

将GOGC设置成400，新分配器的TPCC性能会比旧分配器好，峰值内存在同一水平

因为新分配器和后续的改动，go内存分配会变少，GC触发的时机也会受影响，导致次数更多

后面的改进是，继续优化内存分配，复用更多内存，这样每次GC的开销就会降低，GC次数对cpu开销的影响就会降低

相关测试数据：
https://doc.weixin.qq.com/sheet/e3_AR8AoQYjAGQvYRvmLXwRRCj8oCjh3?scode=AJsA6gc3AA8RgBA8kUAR8AoQYjAGQ&tab=BB08J2

**Comment by heni02** [comment]
@reusee  建议回归测试参数设置为多大？

**Comment by reusee** [comment]
GOGC 设置成 200，其他不需要变

**Comment by heni02** [comment]
今天回归配置该参数，明天验证性能是否有提升

**Comment by heni02** [comment]
confirm，closed
<img width="1527" alt="企业微信截图_37d4f910-104e-4fba-a2bf-bd76c2070674" src="https://github.com/matrixorigin/matrixone/assets/113406637/1be7670e-47e2-489a-9627-12660a9c7fad">
<img width="1596" alt="企业微信截图_bcdf4ba3-9df1-4b36-a6c0-036dc7d007fd" src="https://github.com/matrixorigin/matrixone/assets/113406637/e5919abe-69d0-4da6-89a7-a334291885ca">
