### ISSUE TITLE
[Bug]:  bvt failed with inconsistent column name occasionally

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.2-dev

### Commit ID

ed279e605aa509542509f57f7810d0e3db53e2e0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1038" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/b209a9e4-d9d6-4c97-9488-1199b15ecdab">

https://github.com/matrixorigin/matrixone/actions/runs/9180238143/job/25244791668

### Steps to Reproduce

```Markdown
bvt test
```

**Comment by YANGGMM** [comment]
@qingxinhome  麻烦看一下

**Comment by qingxinhome** [comment]
pr中bvt测试用例修改补充空格与mysql对齐，不涉及大小写变动，
该问题本地不复现，建议重新跑一次 @sukki37

**Comment by aunjgr** [comment]
本地跑了100次也未复现。但是最近tke跑出来两次。会不会是分布式环境global变量设置后没有正常生效?

**Comment by qingxinhome** [comment]
该问题和大小写敏感环境变量设置有关，

**Comment by YANGGMM** [comment]
需要等大小写环境变量设置重构完成后测试

**Comment by YANGGMM** [comment]
still working

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9305908748/job/25614805498

**Comment by YANGGMM** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9316395663/job/25645506779

**Comment by ck89119** [comment]
环境变量lower_case_table_names的问题，重构中

**Comment by aressu1985** [comment]
经测试，问题已经解决
