### ISSUE TITLE
[Feature Request]: cluster active-standby feature

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#16317]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

implement the CDC feature in MO.

 implement active-standby feature for MO, mainly through raft logs

**Comment by sukki37** [comment]
related to https://github.com/matrixorigin/MO-Cloud/issues/1285

**Comment by heni02** [comment]
test done
