### ISSUE TITLE
[Feature Request]: MO support upgrade from 1.1.x to 1.2.x directly

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#16339]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

Upgrade MO from 1.1.3 to 1.2.1, MO report panic

```
panic: cannot startup a old version 1.2.0 to join cluster, current version is 1.2.1

goroutine 455 [running]:
github.com/matrixorigin/matrixone/pkg/bootstrap.(*service).doCheckUpgrade.func1({0x50e3420?, 0xc065422000})
	/go/src/github.com/matrixorigin/matrixone/pkg/bootstrap/service_upgrade.go:152 +0x121e
```

### Describe the feature you'd like

MO support upgrade from 1.1.x to 1.2.x directly.

**Comment by qingxinhome** [comment]
This function has been implemented and verified for testing @aylei @sukki37 @aressu1985 @TangxingZhou @daviszhen

**Comment by TangxingZhou** [comment]
测试验证通过
