### ISSUE TITLE
[Bug]: bvt test checkpoint fail occasionally

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16344]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="877" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/8a456881-ea7d-47b1-ab5a-214aae3b9167">

### Steps to Reproduce

```Markdown
fail link:https://github.com/matrixorigin/matrixone/actions/runs/9201376996/job/25309483023?pr=16316
```

**Comment by heni02** [comment]
最新的ci没有出现了，closed
<img width="1055" alt="企业微信截图_ec3ccf50-7b4c-4c8b-a9f1-9e6d205b3f6e" src="https://github.com/matrixorigin/matrixone/assets/113406637/22d58ff9-f390-4cfe-add7-5fd1f7a61315">
