### ISSUE TITLE
[Bug]: [date 5.22]tke regression: tpcc 100w100threads reported deadlock detected

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16343]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4574ebd71

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

配置开了trace，tpcc测试报了该错误，目前还不确定是trace影响，正在排查中
job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9193321793/job/25292619691
<img width="1030" alt="企业微信截图_52f08314-90be-4d86-b610-08763fd97441" src="https://github.com/matrixorigin/matrixone/assets/113406637/c85288cb-1f74-4abf-b29b-74b4778a4ed4">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XGF%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240522%5C%22%7D%20%7C%3D%20%60deadlock%20detected%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716388853017%22,%22to%22:%221716432053018%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc 100w100threads test
```

**Comment by heni02** [comment]
commit：4574ebd
去掉trace跑tpcc所有仓没有出现该错误
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9201286230/job/25309498952
<img width="1057" alt="企业微信截图_d1381be9-aba6-4098-9e7e-0a1495a0541f" src="https://github.com/matrixorigin/matrixone/assets/113406637/df40a878-1c53-491c-83e9-37327b33e041">

**Comment by zhangxu19830126** [comment]
trace目前分析看在性能测试环境下，不能开启。现在没办法支持，先关闭trace吧。

**Comment by heni02** [comment]
confirm，closed
commit：8a5f0bd44
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9256599329/job/25468600655
