### ISSUE TITLE
[Bug]: 在未定义列情况下建表成功

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/matrixone#16352]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

在未指定列定义情况下建表成功
<img width="353" alt="image" src="https://github.com/matrixorigin/matrixone/assets/153493538/dda22386-fdfd-4938-a828-ba0336284f53">

### Expected Behavior

应该与mysql保持一致

<img width="576" alt="image" src="https://github.com/matrixorigin/matrixone/assets/153493538/41e52f99-3163-4f89-bdf8-adddfe27e877">

### Steps to Reproduce

```Markdown
create table test;
```

**Comment by jensenojs** [comment]
<img width="1104" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/f7576f61-d351-43bd-9ee9-144b1557c7ba">

二分发现是这个commit引入的, 麻烦钊哥有空的时候看看吧, @YANGGMM

**Comment by YANGGMM** [comment]
fixed

<img width="486" alt="image" src="https://github.com/user-attachments/assets/b9ef42d2-5839-4b83-97ae-b7a1c4e4f069">

**Comment by YANGGMM** [comment]
plz test @aressu1985

**Comment by heni02** [comment]
confirm,closed
commit:0492a8113d98eae918aec8e0a0dd5d0b57888093
mysql> create database db;
Query OK, 1 row affected (0.05 sec)

mysql> use db;
Database changed
mysql> create table test;
ERROR 4028 (HY000): A table must have at least one visible column.
