### ISSUE TITLE
[Bug]: The MatrixOne version number is appeared wrong.

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1637]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): MatrixOne 0.2.0 version from dockerhub with ID: 0.2.0-20220122
- Hardware parameters: Apple M1, memory 16GB 
- OS type: Mac OS
- Others:
```

### Actual Behavior

When I use MySQL client to connect to MatrixOne, the appeared version of MatrixOne is still 0.1.0.

![image](https://user-images.githubusercontent.com/4965857/150893695-8b68bcbe-fb8d-4002-86d5-c904ae102af0.png)

### Expected Behavior

The appeared version of MatrixOne should become 0.2.0.

### Steps to Reproduce

```markdown
$ docker run -d -p 6001:6001 --name matrixone matrixorigin/matrixone:0.2.0-20220122
$ mysql -h 127.0.0.1 -P 6001 -udump -p
```

**Comment by yingfeng** [comment]
Fixed already. Docker image is required to be updated.

**Comment by m-schen** [comment]
this issue has been fixed already. Docker image is too old.
