### ISSUE TITLE
[Bug]: [tke regression] tpcc 100-1000 test oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16379]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

mian

### Commit ID

e4c504a606585cb373a5bb7c452e804469716610

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9211125528/job/25347041190
<img width="1017" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/de0710c6-955e-4676-8af5-a8277b372100">

<img width="1453" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d6c4684d-12e9-4435-91b9-710ede359799">
<img width="978" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/681b7446-87a1-40f2-b89a-5c23408ed89e">
<img width="1393" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/ed354285-453e-4342-b146-0c14a58dd84c">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22JM6%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240523%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

profile今日复现再抓

### Steps to Reproduce

```Markdown
trigger tke test
```

**Comment by Ariznawlll** [comment]
<img width="1508" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9f6d07a6-bd63-46a2-8582-edc63c6dbf1a">

已复现，但是profile太大了此处放不下，麻烦联系我，私发

**Comment by jensenojs** [comment]
看着`ReadBloomFilter`占用的内存很多, 请徐鹏大哥帮忙找人看一下吧, @XuPeng-SH 

alloc 
<img width="1545" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ab440cc0-5628-421a-aeec-59c2118f7932">

in use 
<img width="1545" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/844ac1e5-f99e-4d35-adfa-7ce5c600ea87">

**Comment by jensenojs** [comment]
由徐鹏哥确认bf的内存占用是很小的, 从heap上看不出什么特别的东西. 需要二分来找这个bug, 先暂时assign在我头上, 等找到引入的commit再交给对应的同事

**Comment by XuPeng-SH** [comment]
profile里bloom filter 数据是2g, 也就是是metadata cache的大小，预期是这样，每天的daily也一直是2G，没有变过, cn 的内存limit 是55g, 不是这个原因

**Comment by XuPeng-SH** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22JPW%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240523%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-sjxch%5C%22%7D%20%7C~%20%60gc%20.%2Aglobal%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716533233000%22,%22to%22:%221716534054000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by XuPeng-SH** [comment]
> https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22JPW%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240523%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-sjxch%5C%22%7D%20%7C~%20%60gc%20.%2Aglobal%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716533233000%22,%22to%22:%221716534054000%22%7D%7D%7D&schemaVersion=1&orgId=1

heap 在oom前的峰值在20g+, bloom filter 所在的metadata cache大小是2g. cn的内存是55g, 看起来和内存的gc有关系，需要二分查找：
<img width="1659" alt="WeChatWorkScreenshot_606ac48a-0fd1-4952-9e47-325255158d43" src="https://github.com/matrixorigin/matrixone/assets/39627130/b5d26c7b-de64-4a05-85c5-961a6ded5949">

**Comment by XuPeng-SH** [comment]
<img width="1109" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/aa8e8586-77f7-451b-95c3-a926658f3a41">
二分到5月21号的 #16292 跑tpcc也是oom的，更早之前就oom了

**Comment by jensenojs** [comment]
处理 moc#3351

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
may dup with : 
- https://github.com/matrixorigin/matrixone/issues/16741

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
#16741 之后这个问题应该已经解决了, 辛苦动哥有时间检验一下

@aressu1985

**Comment by Ariznawlll** [comment]
最近没再出现了，先关闭
