### ISSUE TITLE
[Bug]: stock_level txn timeout in 60s in tpcc 10-10 longrunning during statbility test on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16376]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev main

### Commit ID

4574ebd

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

during tpcc 10-10 longrunning test in statbility test on distributed mode, there were some stock_level timeout errors:

<img width="1407" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/1a16d16b-d961-4efc-8854-c334a10d40dc">
note: there is a bug in test tool, the tnx should be stock level, not new order

**and find the txn id in statement info:**
mysql> select transaction_id, duration, request_at, response_at from statement_info where statement like "%execute __mo_stmt_id%" and duration > 60000000000 and statement not like "%queries%" and request_at > '2024-05-23 00:25:02.528394' and request_at < '2024-05-23 00:35:02.528394' order by duration desc limit 2\G;
*************************** 1. row ***************************
transaction_id: 018fa2da2f7c7f13818ac2e0880e7547
      duration: 75397334928
    request_at: 2024-05-23 00:29:19.100816
   response_at: 2024-05-23 00:30:34.498151
1 row in set (0.55 sec)

mysql> select * from statement_info where transaction_id = '018fa2da2f7c7f13818ac2e0880e7547'\G;
*************************** 1. row ***************************
         statement_id: 018fa2da-2f7c-7d86-829a-89932f08290f
       transaction_id: 018fa2da2f7c7f13818ac2e0880e7547
           session_id: 018fa05f-2652-7ae0-b143-2a9b96536ff8
              account: tpcc_test
                 user: admin
                 host: 10.10.4.249:47080
             database: tpcc_10
            statement: execute __mo_stmt_id_24 // prepare __mo_stmt_id_24 from SELECT count(*) AS low_stock FROM (    SELECT s_w_id, s_i_id, s_quantity         FROM bmsql_stock         WHERE s_w_id = ? AND s_quantity < ? AND s_i_id IN (            SELECT ol_i_id                 FROM bmsql_district                 JOIN bmsql_order_line ON ol_w_id = d_w_id                  AND ol_d_id = d_id                  AND ol_o_id >= d_next_o_id - 20                  AND ol_o_id < d_next_o_id                 WHERE d_w_id = ? AND d_id = ?         )     ) AS L ; 3 ; 10 ; 3 ; 7
        statement_tag: 
statement_fingerprint: 
            node_uuid: 32643833-3661-6461-6631-313761333063
            node_type: CN
           request_at: 2024-05-23 00:29:19.100816
          response_at: 2024-05-23 00:30:34.498151
             duration: 75397334928
               status: Success

and then, find the trace_event_txn_action data, there were several actions in this txn which cost is more than 3 seconds
<img width="1431" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7ccd2e0a-219a-466d-bb9c-ab2faec25055">

[trace_event_txn_action.txt](https://github.com/matrixorigin/matrixone/files/15426981/trace_event_txn_action.txt)

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22wi9%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-4574ebd-20240522204819%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221716376337191%22,%22to%22:%221716452685113%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run tpcc 10-10 longrunning test
```

**Comment by aressu1985** [comment]
mysql> explain analyze SELECT s_w_id, s_i_id, s_quantity FROM bmsql_stock WHERE s_w_id = 3 AND s_quantity < 10 AND s_i_id IN ( SELECT ol_i_id FROM bmsql_district JOIN bmsql_order_line ON ol_w_id = d_w_id AND ol_d_id = d_id AND ol_o_id >= d_next_o_id - 20 AND ol_o_id < d_next_o_id WHERE d_w_id = 3 AND d_id = 7);
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Project                                                                                                                                                                                                                                                                   |
|   Analyze: timeConsumed=0ms waitTime=46ms inputRows=0 outputRows=0 InputSize=0bytes OutputSize=0bytes MemorySize=0bytes                                                                                                                                                   |
|   ->  Join                                                                                                                                                                                                                                                                |
|         Analyze: timeConsumed=0ms probe_time=[total=0ms,min=0ms,max=0ms,dop=14] build_time=[0ms] waitTime=871ms inputRows=386 outputRows=0 InputSize=1544bytes OutputSize=0bytes MemorySize=16441bytes                                                                    |
|         Join Type: RIGHT SEMI                                                                                                                                                                                                                                             |
|         Join Cond: (bmsql_order_line.ol_i_id = bmsql_stock.s_i_id)                                                                                                                                                                                                        |
|         ->  Filter                                                                                                                                                                                                                                                        |
|               Analyze: timeConsumed=9ms waitTime=0ms inputRows=42448 outputRows=193 InputSize=509376bytes OutputSize=772bytes MemorySize=42641bytes                                                                                                                       |
|               Filter Cond: (cast(bmsql_order_line.ol_o_id AS BIGINT) >= (cast(bmsql_district.d_next_o_id AS BIGINT) - 20)), (bmsql_order_line.ol_o_id < bmsql_district.d_next_o_id)                                                                                       |
|               ->  Join                                                                                                                                                                                                                                                    |
|                     Analyze: timeConsumed=23ms probe_time=[total=23ms,min=0ms,max=3ms,dop=42] build_time=[0ms,0ms,0ms] waitTime=1942ms inputRows=42451 outputRows=42448 InputSize=679204bytes OutputSize=509376bytes MemorySize=739881bytes                               |
|                     Join Type: INNER   hashOnPK                                                                                                                                                                                                                           |
|                     Join Cond: (bmsql_order_line.ol_w_id = bmsql_district.d_w_id), (bmsql_order_line.ol_d_id = bmsql_district.d_id)                                                                                                                                       |
|                     Runtime Filter Build: serial(#[-1,0], #[-1,1])                                                                                                                                                                                                        |
|                     ->  Table Scan on tpcc_10.bmsql_order_line                                                                                                                                                                                                            |
|                           Analyze: timeConsumed=165ms scan_time=[total=153ms,min=5ms,max=14ms,dop=18] filter_time=[total=12ms,min=0ms,max=2ms,dop=18] waitTime=110ms inputBlocks=254 inputRows=42448 outputRows=42448 InputSize=1mb OutputSize=679168bytes MemorySize=1mb |
|                           Filter Cond: prefix_eq(bmsql_order_line.__mo_cpkey_col, '::')                                                                                                                                                                               |
|                           Block Filter Cond: prefix_eq(bmsql_order_line.__mo_cpkey_col, '::')                                                                                                                                                                         |
|                           Runtime Filter Probe: bmsql_order_line.__mo_cpkey_col Match Prefix                                                                                                                                                                              |
|                     ->  Table Scan on tpcc_10.bmsql_district                                                                                                                                                                                                              |
|                           Analyze: timeConsumed=282ms scan_time=[total=282ms,min=16ms,max=24ms,dop=13] filter_time=[total=0ms,min=0ms,max=0ms,dop=13] waitTime=24ms inputBlocks=1 inputRows=1 outputRows=1 InputSize=36bytes OutputSize=12bytes MemorySize=37bytes        |
|                           Filter Cond: (bmsql_district.__mo_cpkey_col = '::')                                                                                                                                                                                         |
|                           Block Filter Cond: (bmsql_district.__mo_cpkey_col = '::')                                                                                                                                                                                   |
|         ->  Table Scan on tpcc_10.bmsql_stock                                                                                                                                                                                                                             |
|               Analyze: timeConsumed=541ms scan_time=[total=527ms,min=34ms,max=39ms,dop=14] filter_time=[total=13ms,min=0ms,max=1ms,dop=14] waitTime=40ms inputBlocks=352 inputRows=100000 outputRows=0 InputSize=3mb OutputSize=0bytes MemorySize=2mb                     |
|               Filter Cond: prefix_eq(bmsql_stock.__mo_cpkey_col, ':'), (bmsql_stock.s_quantity < 10)                                                                                                                                                                    |
|               Block Filter Cond: prefix_eq(bmsql_stock.__mo_cpkey_col, ':')                                                                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
27 rows in set (0.06 sec)

**Comment by badboynt1** [comment]
需要多抓一下metric
https://github.com/matrixorigin/matrixone/pull/16389
等这个pr合进去以后再跑

**Comment by badboynt1** [comment]
增加metrics的pr已经合并。 麻烦再跑一下  @aressu1985

**Comment by aressu1985** [comment]
非1.2-dev REGRESSION问题，可以delay到1.3.0解决

**Comment by aressu1985** [comment]
出现问题的信息如下，可以去查看 @badboynt1 

namespace: 
mo-nightly-0081545-20240530220339 

link:
https://shanghai.idc.matrixorigin.cn:30001/dashboards

**Comment by aressu1985** [comment]
update on 5.31
commit id: 0081545

1、超时的事务
mysql> select transaction_id, duration, request_at, response_at from statement_info where statement like "%execute __mo_stmt_id%" and duration > 60000000000 and statement not like "%queries%" and request_at > '2024-05-31 02:15:08.528394' and request_at < '2024-05-31 02:19:08.528394' order by duration desc limit 2\G;
*************************** 1. row ***************************
transaction_id: 018fcc6fc57973ba94ef3ffc1bb96286
      duration: 60516150897
    request_at: 2024-05-31 02:17:08.217079
   response_at: 2024-05-31 02:18:08.733230
1 row in set (0.05 sec)

mysql> select * from statement_info where transaction_id = '018fcc6fc57973ba94ef3ffc1bb96286'\G;
*************************** 1. row ***************************
         statement_id: 018fcc6f-c579-726f-a018-038a8ed0f94b
       transaction_id: 018fcc6fc57973ba94ef3ffc1bb96286
           session_id: 018fc9d7-4683-74cb-a343-5f3777bd99b4
              account: tpcc_test
                 user: admin
                 host: 10.10.4.41:43536
             database: tpcc_10
            statement: execute __mo_stmt_id_24 // prepare __mo_stmt_id_24 from SELECT count(*) AS low_stock FROM (    SELECT s_w_id, s_i_id, s_quantity         FROM bmsql_stock         WHERE s_w_id = ? AND s_quantity < ? AND s_i_id IN (            SELECT ol_i_id                 FROM bmsql_district                 JOIN bmsql_order_line ON ol_w_id = d_w_id                  AND ol_d_id = d_id                  AND ol_o_id >= d_next_o_id - 20                  AND ol_o_id < d_next_o_id                 WHERE d_w_id = ? AND d_id = ?         )     ) AS L ; 5 ; 12 ; 5 ; 5
        statement_tag: 
statement_fingerprint: 
            node_uuid: 65386633-6463-3036-3764-393061383538
            node_type: CN
           request_at: 2024-05-31 02:17:08.217079
          response_at: 2024-05-31 02:18:08.733230
             duration: 60516150897
               status: Success
             err_code: 0
                error: 
            exec_plan: {"steps":[{"graphData":{"nodes":[{"id":"7","name":"Project","title":"count(*)","labels":[{"name":"List of expressions","value":["count(*)"]}],"statistics":{"Time":[{"name":"Time Consumed","value":4339,"unit":"ns"},{"name":"Wait Time","value":60514033738,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":0,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":1,"unit":"count"},{"name":"Output Rows","value":1,"unit":"count"},{"name":"Input Size","value":8,"unit":"byte"},{"name":"Output Size","value":8,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":0,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":1,"cost":1,"hashmapsize":0,"rowsize":0},"totalStats":{"name":"Time spent","value":4339,"unit":"ns"}},{"id":"6","name":"Aggregate","title":"starcount(1)","labels":[{"name":"Aggregate functions","value":["starcount(1)"]}],"statistics":{"Time":[{"name":"Time Consumed","value":25382,"unit":"ns"},{"name":"Wait Time","value":60513981819,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":8,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":6,"unit":"count"},{"name":"Output Rows","value":1,"unit":"count"},{"name":"Input Size","value":24,"unit":"byte"},{"name":"Output Size","value":8,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":0,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":1,"cost":3000,"hashmapsize":1,"rowsize":0},"totalStats":{"name":"Time spent","value":25382,"unit":"ns"}},{"id":"5","name":"Join","title":"(bmsql_order_line.ol_i_id = bmsql_stock.s_i_id)","labels":[{"name":"Join type","value":"SEMI"},{"name":"Join conditions","value":["(bmsql_order_line.ol_i_id = bmsql_stock.s_i_id)"]},{"name":"Left node id","value":3},{"name":"Right node id","value":4}],"statistics":{"Time":[{"name":"Time Consumed","value":24016717,"unit":"ns"},{"name":"Wait Time","value":183453520024,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":270958,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":4554,"unit":"count"},{"name":"Output Rows","value":6,"unit":"count"},{"name":"Input Size","value":18216,"unit":"byte"},{"name":"Output Size","value":24,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":0,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":0.08965265455726242,"cost":3000,"hashmapsize":9.999769744141629,"rowsize":0},"totalStats":{"name":"Time spent","value":24016717,"unit":"ns"}},{"id":"3","name":"Filter","title":"(cast(bmsql_order_line.ol_o_id AS BIGINT) >= (cast(bmsql_district.d_next_o_id AS BIGINT) - 20)), (bmsql_order_line.ol_o_id < bmsql_district.d_next_o_id)","labels":[{"name":"Filter conditions","value":["(cast(bmsql_order_line.ol_o_id AS BIGINT) >= (cast(bmsql_district.d_next_o_id AS BIGINT) - 20))","(bmsql_order_line.ol_o_id < bmsql_district.d_next_o_id)"]}],"statistics":{"Time":[{"name":"Time Consumed","value":9104977,"unit":"ns"},{"name":"Wait Time","value":0,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":41014,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":40810,"unit":"count"},{"name":"Output Rows","value":204,"unit":"count"},{"name":"Input Size","value":489720,"unit":"byte"},{"name":"Output Size","value":816,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":0,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":50,"cost":2000,"hashmapsize":0,"rowsize":0},"totalStats":{"name":"Time spent","value":9104977,"unit":"ns"}},{"id":"2","name":"Join","title":"(bmsql_order_line.ol_w_id = bmsql_district.d_w_id), (bmsql_order_line.ol_d_id = bmsql_district.d_id)","labels":[{"name":"Join type","value":"INNER"},{"name":"Join conditions","value":["(bmsql_order_line.ol_w_id = bmsql_district.d_w_id)","(bmsql_order_line.ol_d_id = bmsql_district.d_id)"]},{"name":"Left node id","value":0},{"name":"Right node id","value":1}],"statistics":{"Time":[{"name":"Time Consumed","value":54077647,"unit":"ns"},{"name":"Wait Time","value":7361129008,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":32894,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":1,"unit":"count"},{"name":"Output Rows","value":40810,"unit":"count"},{"name":"Input Size","value":12,"unit":"byte"},{"name":"Output Size","value":489720,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":0,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":1000,"cost":2000,"hashmapsize":1000,"rowsize":0},"totalStats":{"name":"Time spent","value":54077647,"unit":"ns"}},{"id":"0","name":"Table Scan","title":"tpcc_10.bmsql_order_line","labels":[{"name":"Full table name","value":"tpcc_10.bmsql_order_line"},{"name":"Columns","value":["ol_w_id","ol_d_id","ol_o_id","ol_i_id","__mo_cpkey_col"]},{"name":"Total columns","value":12},{"name":"Scan columns","value":5},{"name":"Block Filter conditions","value":["prefix_eq(bmsql_order_line.__mo_cpkey_col, serial(cast(? AS INT), cast(? AS INT)))"]},{"name":"Filter conditions","value":["prefix_eq(bmsql_order_line.__mo_cpkey_col, serial(cast(? AS INT), cast(? AS INT)))"]}],"statistics":{"Time":[{"name":"Time Consumed","value":5195472234,"unit":"ns"},{"name":"Wait Time","value":5228312670,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":368490,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":40810,"unit":"count"},{"name":"Output Rows","value":40810,"unit":"count"},{"name":"Input Size","value":1632400,"unit":"byte"},{"name":"Output Size","value":652960,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":1632400,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":10,"cost":1000,"hashmapsize":0,"rowsize":0},"totalStats":{"name":"Time spent","value":5195472234,"unit":"ns"}},{"id":"1","name":"Table Scan","title":"tpcc_10.bmsql_district","labels":[{"name":"Full table name","value":"tpcc_10.bmsql_district"},{"name":"Columns","value":["d_w_id","d_id","d_next_o_id","__mo_cpkey_col"]},{"name":"Total columns","value":13},{"name":"Scan columns","value":4},{"name":"Filter conditions","value":["(bmsql_district.__mo_cpkey_col = serial(cast(? AS INT), cast(? AS INT)))"]}],"statistics":{"Time":[{"name":"Time Consumed","value":1234932792,"unit":"ns"},{"name":"Wait Time","value":1277225114,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":37,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":1,"unit":"count"},{"name":"Output Rows","value":1,"unit":"count"},{"name":"Input Size","value":36,"unit":"byte"},{"name":"Output Size","value":12,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":36,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":1000,"cost":1000,"hashmapsize":0,"rowsize":0},"totalStats":{"name":"Time spent","value":1234932792,"unit":"ns"}},{"id":"4","name":"Table Scan","title":"tpcc_10.bmsql_stock","labels":[{"name":"Full table name","value":"tpcc_10.bmsql_stock"},{"name":"Columns","value":["s_i_id","s_quantity","__mo_cpkey_col"]},{"name":"Total columns","value":19},{"name":"Scan columns","value":3},{"name":"Block Filter conditions","value":["prefix_eq(bmsql_stock.__mo_cpkey_col, serial(cast(? AS INT)))"]},{"name":"Filter conditions","value":["prefix_eq(bmsql_stock.__mo_cpkey_col, serial(cast(? AS INT)))","(bmsql_stock.s_quantity < cast(? AS INT))"]}],"statistics":{"Time":[{"name":"Time Consumed","value":60504212298,"unit":"ns"},{"name":"Wait Time","value":60488063630,"unit":"ns"},{"name":"Scan Time","value":0,"unit":"ns"},{"name":"Insert Time","value":0,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":385888,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":100000,"unit":"count"},{"name":"Output Rows","value":2175,"unit":"count"},{"name":"Input Size","value":3200000,"unit":"byte"},{"name":"Output Size","value":8700,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":3200000,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"stats":{"blocknum":1,"outcnt":9.999769744141629,"cost":1000,"hashmapsize":0,"rowsize":0},"totalStats":{"name":"Time spent","value":60504212298,"unit":"ns"}}],"edges":[{"id":"E6","src":"6","dst":"7","output":1,"unit":"count"},{"id":"E5","src":"5","dst":"6","output":6,"unit":"count"},{"id":"E3","src":"3","dst":"5","output":204,"unit":"count"},{"id":"E2","src":"2","dst":"3","output":40810,"unit":"count"},{"id":"E0","src":"0","dst":"2","output":40810,"unit":"count"},{"id":"E1","src":"1","dst":"2","output":1,"unit":"count"},{"id":"E4","src":"4","dst":"5","output":2175,"unit":"count"}],"labels":[],"global":{"statistics":{"Time":[{"name":"Time Consumed","value":67021846386,"unit":"ns"},{"name":"Wait Time","value":378836266003,"unit":"ns"}],"Memory":[{"name":"Memory Size","value":1099289,"unit":"byte"}],"Throughput":[{"name":"Input Rows","value":186183,"unit":"count"},{"name":"Output Rows","value":84008,"unit":"count"},{"name":"Input Size","value":5340416,"unit":"byte"},{"name":"Output Size","value":1152248,"unit":"byte"}],"IO":[{"name":"Disk IO","value":0,"unit":"byte"},{"name":"S3 IO Byte","value":4832436,"unit":"byte"},{"name":"S3 IO Input Count","value":0,"unit":"count"},{"name":"S3 IO Output Count","value":0,"unit":"count"}],"Network":[{"name":"Network","value":0,"unit":"byte"}]},"totalStats":{"name":"Time spent","value":67021846386,"unit":"ns"}}},"step":0,"description":"","state":"success","stats":{}}],"code":0,"message":"","uuid":"018fcc6f-c579-726f-a018-038a8ed0f94b","NewPlanStats":{"ParseDuration":82345,"PlanDuration":33804,"CompileDuration":603985,"ExecutionDuration":60514446023,"IOAccessTimeConsumption":2540782222,"LocalFSReadIOMergerTimeConsumption":0,"LocalFSReadCacheIOMergerTimeConsumption":0,"S3FSPrefetchFileIOMergerTimeConsumption":0,"S3FSReadIOMergerTimeConsumption":1840068008,"S3FSReadCacheIOMergerTimeConsumption":0,"ParseStartTime":"0001-01-01T00:00:00Z","PlanStartTime":"2024-05-31T02:17:08.217376349Z","CompileStartTime":"2024-05-31T02:17:08.217617022Z","ExecutionStartTime":"2024-05-31T02:17:08.218364176Z","ExecutionEndTime":"2024-05-31T02:18:08.732810209Z","WaitActive":0}}

            rows_read: 140811
           bytes_scan: 4832436
                stats: [4,62641716290,1099289.000,0,0,273,2,3,2155.8845]
       statement_type: Execute
           query_type: Other
              role_id: 2
      sql_source_type: external_sql
           aggr_count: 0
         result_count: 1
1 row in set (39.85 sec)

**Comment by badboynt1** [comment]
最新的一次，1.2-dev上没有复现。 继续观察一下

**Comment by badboynt1** [comment]
可能是因为其他issue导致这个issue没有复现。 等其他issue修复后再看

**Comment by badboynt1** [comment]
我认为主要是merge的问题  具体细节等开会讨论一下

**Comment by badboynt1** [comment]
根据开会结论，这个问题分为三个层面，分别是
1 merge没有做好导致数据在block里太分散，zonemap重叠或者delete太多之类的。
2 cache miss， memcache 12g， diskcache 800g的情况下，不应该有大量的s3访问。
3 访问s3太慢，从metric上看，一次s3请求达到了好几秒。
对1和2 分别拆出子issue

**Comment by aressu1985** [comment]
fixed
