### ISSUE TITLE
[Bug]: restore account

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16371]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0523-update-profile

### Commit ID

34a58dd4db55aec1d77b4ba3d71895c9d8c814bb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/9207040293/job/25326208049?pr=16355
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/7a33e1ca-e728-4acd-8b08-8ea4b130e0fd)

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
occasional
```

**Comment by Ariznawlll** [comment]
处理中

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/0d1f6cb8-8c8a-44f0-badd-e456af0cd29b)

**Comment by Ariznawlll** [comment]
fixed
