### ISSUE TITLE
[Bug]: restore fk table report can not find table by id in ci

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16397]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="875" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/afaa500b-10d1-4cfc-87d5-61bd148ba579">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9220714764/job/25368287909?pr=15810
```

**Comment by YANGGMM** [comment]
2024/05/24 08:19:26.069844 +0000 INFO cn-service.frontend frontend/snapshot.go:364 **[snapshot_01] start to drop fk related tables** {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf"}

2024/05/24 08:19:26.071718 +0000 INFO cn-service.frontend frontend/snapshot.go:945 [snapshot_01] start to get table info: acc_test02 {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf"}

2024/05/24 08:19:26.108334 +0000 INFO cn-service.frontend frontend/snapshot.go:945 [snapshot_01] start to get table info: acc_test02 {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf"}

2024/05/24 08:19:26.144908 +0000 INFO cn-service.frontend frontend/snapshot.go:426 **[snapshot_01] start to drop table: aff01** {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf"}

2024/05/24 08:19:26.146142 +0000 INFO compile/sql_executor.go:355 sql_executor exec {"sql": "delete from `mo_catalog`.`mo_foreign_keys` where db_name = 'acc_test02' and table_name = 'aff01'", "txn-id": "018fa9aef2f57cbca8c0a71d6e8a8b6b", "duration": "775.784µs", "AffectedRows": 1}

2024/05/24 08:19:26.146273 +0000 ERROR disttae/engine.go:532 error: **internal error: can not find table by id 284642: accountId: 65**  {"span": {"trace_id": "4ff348a5-4757-013d-023a-cbb4c9b003ec", "span_id": "bd99d095bdbca5d8"}}

2024/05/24 08:19:26.146320 +0000 ERROR cn-service.frontend frontend/txn.go:62 internal error: can not find table by id 284642: accountId: 65  {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "session_info": "connectionId 
2|127.0.0.1:60190|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 407|018fa9a5-bec9-7710-993d-90ed0df88563", "background": true, "session_id": "018fa9ae-f2f5-71ae-81fd-a41bc317289c", "span": {"trace_id": "4ff348a5-4757-013d-023a-cbb4c9b003ec", "span_id": "bd99d095bdbca5d8"}}

2024/05/24 08:19:26.146361 +0000 ERROR cn-service.frontend frontend/util.go:493 query trace status {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "statement": "drop table if exists acc_test02.aff01", "status": "fail", "error": "internal error: can not find table by id 284642: accountId: 65 ", "session_info": "connectionId 2|127.0.0.1:60190|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 407|018fa9a5-bec9-7710-993d-90ed0df88563", "background": true, "session_id": "018fa9ae-f2f5-71ae-81fd-a41bc317289c", "span": {"trace_id": "4ff348a5-4757-013d-023a-cbb4c9b003ec", "span_id": "bd99d095bdbca5d8"}}

**Comment by Ariznawlll** [comment]
最近没再出现了。
