### ISSUE TITLE
[Bug]: bvt fail in secondary_index_create 

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16427]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="936" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/be31e643-4d85-4231-b761-02600c5ee55c">

### Steps to Reproduce

```Markdown
fail link:https://github.com/matrixorigin/matrixone/actions/runs/9255709607/job/25460077660?pr=16423
```

**Comment by arjunsk** [comment]
Fix merged to master. Kindly retest.
