### ISSUE TITLE
[Bug]: Pipeline ParallelRun阶段，真正执行前发生错误会导致查询卡死。

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#16439]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.2-dev

### Commit ID

b5718f6d6792c9ceffcf88fa1a9c432a85c94b40

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ParallelRun执行到MergeRun函数前的错误信息会导致无法正常执行pipeline的CleanUp，
因此后续的pipeline无法感知到查询因为错误已经结束。

### Expected Behavior

任何阶段发生错误都应该可以让整个查询正常停止下来。

### Steps to Reproduce

```Markdown
修改ParallelRun代码让它必定出错，例如在RuntimeFilter处报错，此时pipeline未真正开始执行。
然后执行任意大一点的查询。
```

**Comment by jensenojs** [comment]
发现这个问题的场景是下面的issue

- https://github.com/matrixorigin/MO-Cloud/issues/3321

**Comment by m-schen** [comment]
相关pr都已经合并，今晚的daily如果没出问题的话，明天我会关闭这个issue.

**Comment by m-schen** [comment]
对应的issue已经解决了，可以关闭。
