### ISSUE TITLE
[Bug]: memory leak in frontend.ExecRequest

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#16442]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![企业微信截图_17168798402997](https://github.com/matrixorigin/matrixone/assets/112734932/e300ac2e-da4b-444b-abdd-6033955327c2)

daily测试，跑完所有的ssb,tpch,tpcc,sysbench之后，这里的内存降不下去。疑似有内存泄露

### Steps to Reproduce

```Markdown
daily测试
```

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
字节数组转string的地方要去掉。可能要改parser的接口。

**Comment by daviszhen** [comment]
在此pr 上修改了。
https://github.com/matrixorigin/matrixone/pull/16919
