### ISSUE TITLE
[Bug]: 404 error for several front pages

### ISSUE THREAD

**Issue by MOOS2021** [matrixorigin/matrixone#1644]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In the front page of docs.matrixorigin.io website, clicking on several links will get 404 error. 

![image](https://user-images.githubusercontent.com/87743092/151129130-42f02ea8-6452-4065-9889-6f833dbf72a5.png)

**Comment by dengn** [comment]
Bug fixed.
