### ISSUE TITLE
[Bug]: drop udf report 'function *** doesn't exist',but actually it exists.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16466]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

040e69593923579f76d945a1ef2ded39d16e1e7b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="585" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2731d8e9-9acf-4d7c-8c4f-994fe135a01c">

### Expected Behavior

drop successfully.

### Steps to Reproduce

```Markdown
drop database if exists udf_db;
create database udf_db;
use udf_db;
select name, db from mo_catalog.mo_user_defined_function;
-- function add
create function `addab`(x int, y int) returns int
language sql as
'$1 + $2';
select addab(10, 5);
select name, db from mo_catalog.mo_user_defined_function;

create function`concatenate`(str1 varchar(255), str2 varchar(255)) returns varchar(255)
language sql as
'$1 + $2';
select concatenate('Hello, ', 'World!');

drop database if exists udf_db2;
create database udf_db2;
use udf_db2;
create function `subab`(x int, y int) returns int
language sql as
'$1 - $2';
select subab(10, 5);


create function `subab`(x int, y int) returns int language sql as '$1 - $2'; ->create 同名的函数报错，行为正常

drop function udf_db.addab();   ->出错位置
drop function addab();  ->出错位置
```

**Comment by arjunsk** [comment]
Hi @aylei , Could you kindly look into this and assign it to the right person who is working on UDF? Thank you!

**Comment by YANGGMM** [comment]
创建带参数的udf，删除的时候也需要带参数
<img width="378" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/f9625801-d50a-4e96-952e-5c20d533d26e">
