### ISSUE TITLE
[Tech Request]: dynamic adjustment of memory-cache-size via RPC 

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#16476]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

An API that allows set/get `memory-cache-size` at runtime, the change should take effect before the RPC returns.

### Why is this needed ?

Similar to https://github.com/matrixorigin/matrixone/issues/16475, it allows MO to dynamic optimize the memory cache without restarting the service.

**Comment by xzxiong** [comment]
经过 #17868 的扩展，我梳理了一下 MemoryCache的使用
![image](https://github.com/user-attachments/assets/e25513f3-fbd5-45c9-b385-d29814f3ecb3)

根据我的理解，还有以下的问题 可能需要考虑：
1.  lru.shards 是根据 启动时的 #cpu 确定的 —— 是否需要动态修改？垂直伸缩初始的 #cpu 都很小 ?
2. lru 内存调整的触发时机？ —— 如何主动触发？
3. 如何看 cache 目前的大小？ —— 至少要增加 cache size 的接口
4. 怎么看 cache 变更完成？

**Comment by reusee** [comment]
fixed

**Comment by aressu1985** [comment]
TEST DONE
