### ISSUE TITLE
[Tech Request]: dynamic adjustment of disk-cache-size via RPC

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#16475]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

An API that allows set/get `disk-cache-size` at runtime, update to `disk-cache-size` should take effect before the RPC returns.

The `get` API is also a must-to-have since if we tune `disk-cache-size` dynamically, the configuration file is no longer the source of truth.

@reusee please evaluate whether we can ship this in mo 1.3, thanks!

### Why is this needed ?

The ability to dynamically adjust the disk-cache-size parameter at runtime via RPC would allow users to optimize disk cache usage based on the current workload and system performance without needing to restart the database service.

**Comment by xzxiong** [comment]
针对 #17868 的扩展，我梳理了一下 disk cache 的使用场景
![image](https://github.com/user-attachments/assets/6bcfa032-dbaf-4ad7-a36f-939f08633348)

根据我的理解，还有以下的问题 可能需要进一步完善：
1. Cache 需要支持主动 Evict —— 并且保证并发安全，特别是还在使用的事务。
2. 看看 cache 目前的大小？ —— 至少要增加 cache size 的接口
3. 怎么看 cache 变更完成？

**Comment by reusee** [comment]
done

**Comment by aressu1985** [comment]
TEST DONE
