### ISSUE TITLE
[Bug]: round() doesn't support nested use

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1648]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):20604139345271224cef083a887346b80c5c33a7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select round(a,round(b)) from t1;
ERROR 2027 (HY000): Malformed packet

### Expected Behavior

mysql> select round(a,round(b)) from t1;
+-------------------+
| round(a,round(b)) |
+-------------------+
|                 1 |
|                 2 |
|                 3 |
|                 4 |
|                 5 |
|                 6 |
|                 7 |
|                 8 |
|                10 |
|                 0 |
|                 0 |
|                 0 |
+-------------------+
12 rows in set (0.01 sec)

**Comment by m-schen** [comment]
does other functions in MO support nested call ?

**Comment by broccoliSpicy** [comment]
We apply the semantics of ClickHouse in our implementation of floor/round function, which means, the second argument of round/floor function should be a constant.
