### ISSUE TITLE
[Bug]: deletion in TPCC|SYSBENCH should not includes MergeDelete operator 

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16487]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are lots of log messages during TPCC|SYSBENCH test in TKE env:
![image](https://github.com/matrixorigin/matrixone/assets/39627130/0706d563-3f75-4395-9c82-5fcb281082d4)

Seems the cost is not correct in this scenario:
![image](https://github.com/matrixorigin/matrixone/assets/39627130/e567cbf0-f0a5-4ca9-87bf-a7b1bd9d31cd)

### Steps to Reproduce

```Markdown
TKE daily TPCC|SYSBENCH
```

**Comment by XuPeng-SH** [comment]
During TPCC daily, it starts from TPCC 500-500

**Comment by aressu1985** [comment]
main上面的问题，1.2.1版本应该也有，milestone修改到1.3.0，增加resolved/v1.2.1 label

**Comment by badboynt1** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
