### ISSUE TITLE
[Bug]: Instance crashed while order by with round() or floor

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1649]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):20604139345271224cef083a887346b80c5c33a7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select a,round(b) from t1 group by round(b) order by a;
ERROR 2013 (HY000): Lost connection to MySQL server during query

mysql> select a,floor(b) from t1 group by floor(b) order by a;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by domingozhang** [comment]
goroutine 2346 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.getDataFromPipeline({0x2320d60, 0xc0ba1489c0}, 0xc086d037a0)
	/mnt/vdb/zhangxiao/matrixone/pkg/frontend/mysql_cmd_executor.go:238 +0x7ad
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.Call(0xc082a550e0, {0x2233680, 0xc005d19da0})
	/mnt/vdb/zhangxiao/matrixone/pkg/sql/colexec/output/output.go:45 +0x15e
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc005dd06c0, 0x3, 0x18}, 0x7f6c3a744688)
	/mnt/vdb/zhangxiao/matrixone/pkg/vm/vm.go:47 +0x9c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunMerge(0xc088595880, 0xc082a550e0)
	/mnt/vdb/zhangxiao/matrixone/pkg/vm/pipeline/pipeline.go:105 +0x126
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc08859aa00, {0x2842920, 0xc0867dc680})
	/mnt/vdb/zhangxiao/matrixone/pkg/sql/compile/scope.go:455 +0x4aa
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0xc08819fd80, 0xd54af7)
	/mnt/vdb/zhangxiao/matrixone/pkg/sql/compile/exec.go:181 +0x116
github.com/matrixorigin/matrixone/pkg/frontend.(*ComputationWrapperImpl).Run(0xc082e04120, 0x2855c08)
	/mnt/vdb/zhangxiao/matrixone/pkg/frontend/mysql_cmd_executor.go:858 +0x1c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc085fbce10, {0xc0867d35c0, 0x36})
	/mnt/vdb/zhangxiao/matrixone/pkg/frontend/mysql_cmd_executor.go:1090 +0x263e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc085fbce10, 0xc0881ee2a0)
	/mnt/vdb/zhangxiao/matrixone/pkg/frontend/mysql_cmd_executor.go:1209 +0x5b3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc005616120)
	/mnt/vdb/zhangxiao/matrixone/pkg/frontend/routine.go:99 +0x2be
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/mnt/vdb/zhangxiao/matrixone/pkg/frontend/routine.go:151 +0x1e7

**Comment by m-schen** [comment]
fix it, you can verify it on branch main.
