### ISSUE TITLE
Regarding precision the result of floor and ground

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1650]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):20604139345271224cef083a887346b80c5c33a7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Currently, all the result of round or floor function is like n.0000
Howerver, in both MySQL and clickhouse, the reulst is n without .0000.
Shall we transfer it to without .0000?

**Comment by broccoliSpicy** [comment]
Currently, our frontend display setting for float numbers are fixed with four decimal digits.
