### ISSUE TITLE
[Bug]: checking regression snapshot read result wrong

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="921" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/8e6d4691-58e7-4a35-9e2d-bcaf067d2321">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9296726405/job/25585995958
```

**Comment by YANGGMM** [comment]
<img width="764" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/e3155a14-4781-4956-a64d-20de641395c9">

**Comment by YANGGMM** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%225RM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-16489%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717042261000%22,%22to%22:%221717042262000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2024/05/30 04:11:01.866304 +0000","caller":"disttae/stats.go:395","msg":"cannot get table by ID {272929 272934}"}

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/9298090739/job/25589717935

**Comment by YANGGMM** [comment]
<img width="985" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/337d7cea-11e0-4c54-aae8-2fff779da432">

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/9304921019/job/25611605575

**Comment by YANGGMM** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/9313180465/job/25635620314

**Comment by YANGGMM** [comment]
最新提的测试里面，普通读和快照读都通过了，但是测试超时https://github.com/matrixorigin/matrixone/actions/runs/9314344803/job/25638753547， 继续观察

**Comment by YANGGMM** [comment]
repo :https://github.com/matrixorigin/matrixone/actions/runs/9316395663/job/25645506779

**Comment by YANGGMM** [comment]
加入log以后repro：https://github.com/matrixorigin/matrixone/actions/runs/9321650046/job/25661862877

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9334916657

**Comment by YANGGMM** [comment]
已经提了pr

**Comment by Ariznawlll** [comment]
观察了几天，没再出现了
