### ISSUE TITLE
[Bug]: [date 5.29]tke regression: sysbench1000w update-index mo hung 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16503]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8b019d284

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9288081660/job/25582868306
<img width="1177" alt="企业微信截图_30eae3a1-fdc9-485a-a8cc-691ccb33179c" src="https://github.com/matrixorigin/matrixone/assets/113406637/64425aa4-c897-4c66-9f98-d4fd482a43a7">

profile:
[profile0530.tar.gz](https://github.com/matrixorigin/matrixone/files/15494665/profile0530.tar.gz)

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22jV9%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240529%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717044672028%22,%22to%22:%221717048272028%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench1000w update-index 1000threads test
```

**Comment by m-schen** [comment]
先看1.2.1的问题，1.3的需要先搁置

**Comment by m-schen** [comment]
在改别的s-1中

**Comment by m-schen** [comment]
在改connection reset的s-1中

**Comment by m-schen** [comment]
无进展

**Comment by m-schen** [comment]
今日无投入

**Comment by m-schen** [comment]
没投入

**Comment by m-schen** [comment]
近期没有投入这个

**Comment by m-schen** [comment]
近期没有投入这个。

有个想法和当时重连会导致孤儿事务锁不放不知道有没有关系。
如果是这个问题的话，现在的版本是会重连阶段卡死。

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
同上一个回复

**Comment by m-schen** [comment]
等17226改完

**Comment by m-schen** [comment]
等17226改完

**Comment by m-schen** [comment]
等一下17226的状态，pr已合并。跑一天看看情况先。

**Comment by m-schen** [comment]
与上一个回复相同。

**Comment by m-schen** [comment]
现在没空

**Comment by m-schen** [comment]
main分支与17226的问题应该已经稳定了，可以在main分支验证该问题。

**Comment by heni02** [comment]
目前回归没有这个问题了
confirm,closed
