### ISSUE TITLE
[Bug]: Column values cannot be referenced by round or floor

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1652]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 ( a int not null default 1, big bigint );
insert into t1 (big) values (-1),(12345678901234567),(9223372036854775807);
mysql> select * from t1;
+------+---------------------+
| a    | big                 |
+------+---------------------+
|    1 |                  -1 |
|    1 |   12345678901234567 |
|    1 | 9223372036854775807 |
+------+---------------------+

mysql> select round(big,a) from t1;
ERROR 2027 (HY000): Malformed packet

### Expected Behavior

mysql> select round(big,a) from t1;
+---------------------+
| round(big,a)        |
+---------------------+
|                  -1 |
|   12345678901234567 |
| 9223372036854775807 |
+---------------------+

**Comment by broccoliSpicy** [comment]
In MatrixOne's semantic of floor/round function, the second second argument must be a constant.
