### ISSUE TITLE
[Bug]: cn panic by runtime error: invalid memory address or nil pointer dereference during sysbench random points test in daily regression on tke

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16531]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

7d957a2

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9303942349/job/25625533653

During sysbench random points test in daily regression on tke, on cn was crashed by runtime error: invalid memory address or nil pointer dereference

<img width="1403" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3e606414-ab1e-413c-835d-3547892940f4">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22QaX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-7d957a2%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717114145175%22,%22to%22:%221717114149355%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1327" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/085b5d24-b56e-46e0-a751-438934e65797">

but this was a little strange, panic was on **"2024-05-31 00:09:06.900"**, but the cn was restarted on "2024-05-31 00:15:52.196"

### Steps to Reproduce

```Markdown
run sysbench random points on 1000w basis data on tke
```

**Comment by sukki37** [comment]
<img width="1304" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/10b5dc68-02f0-4206-9d6f-3a3d5468c5f1">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%2259G%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22nightly-regression-dis-tp-cn%5C%22,%20apps_kruise_io_cloneset_instance_id%3D%5C%22t6w27%5C%22,%20container%3D%5C%22main%5C%22,%20controller_revision_hash%3D%5C%22nightly-regression-dis-tp-cn-9b8d586c6%5C%22,%20filename%3D%5C%22%2Fvar%2Flog%2Fpods%2Fmo-branch-reg-7d957a2_nightly-regression-dis-tp-cn-t6w27_e1ea3d34-e290-4ecc-b7fb-9073d6556ec2%2Fmain%2F0.log%5C%22,%20job%3D%5C%22mo-branch-reg-7d957a2%2Fnightly-regression-dis-tp-cn%5C%22,%20lifecycle_apps_kruise_io_state%3D%5C%22Normal%5C%22,%20matrixone_cloud_cn_uuid%3D%5C%2230643636-6332-6432-3532-373265343266%5C%22,%20matrixorigin_io_cluster%3D%5C%22nightly-regression-dis%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22,%20matrixorigin_io_instance%3D%5C%22nightly-regression-dis-tp%5C%22,%20matrixorigin_io_namespace%3D%5C%22mo-branch-reg-7d957a2%5C%22,%20namespace%3D%5C%22mo-branch-reg-7d957a2%5C%22,%20node_name%3D%5C%2210.129.0.51%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-t6w27%5C%22,%20pod_template_hash%3D%5C%229b8d586c6%5C%22,%20stream%3D%5C%22stderr%5C%22%7D%20%21%3D%20%60ms%20cpu%60%22,%22queryType%22:%22range%22,%22refId%22:%22log-row-context-query-_0.27767153405580447%22,%22maxLines%22:1000,%22direction%22:%22backward%22,%22datasource%22:%7B%22uid%22:%22loki%22,%22type%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717114139908%22,%22to%22:%221717114146908%22%7D%7D%7D&schemaVersion=1&orgId=1



@daviszhen please help on this, thx

**Comment by sukki37** [comment]
panic loc： https://github.com/matrixorigin/matrixone/blob/6d9337f36529f948f9eb0d79c5528ecb5f79f587/pkg/frontend/routine_manager.go#L485


<img width="1379" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/544cf186-c5f2-471b-bac7-b6fb3fa758aa">

**Comment by daviszhen** [comment]
与16569类似。改过一个版本。等测试结果。

**Comment by daviszhen** [comment]
等复现

**Comment by aressu1985** [comment]
fixed
