### ISSUE TITLE
[Bug]: bvt/result_count failed: 2 more rows result

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#16530]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.2-dev

### Commit ID

3b0325c1c, 5085e5900

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9306467231/job/25616635121

2024-05-30 17:53:45 INFO  Executor:37 - Start to execute the script file[/home/runner/_work/matrixone/matrixone/matrixone/test/distributed/cases/zz_statement_query_type/result_count.sql] now, and it will take a few moment,pleas wait......
2024-05-30 17:53:45 ERROR RSRow:83 - The value of [row:49,column:0] does not equal with each other,one is [commit],but the other is [create database db1]
2024-05-30 17:53:45 ERROR Executor:199 - [/home/runner/_work/matrixone/matrixone/matrixone/test/distributed/cases/zz_statement_query_type/result_count.sql][row:11][select statement, result_count from statement_info where account="bvt_result_count" and statement not like '%mo_ctl%' and length(statement) > 0 and status != 'Running' and aggr_count < 1 order by request_at desc limit 50;] was executed failed, con[id=0, user=dump, ***

![企业微信截图_fb66ea9a-e80c-482d-9be0-0bac2fa715af](https://github.com/matrixorigin/matrixone/assets/3927687/8cf8dca3-2752-4546-ad6c-b6535bfd36c5)

### Steps to Reproduce

```Markdown
run MatrixOne CI
```

**Comment by xzxiong** [comment]
main repro https://github.com/matrixorigin/matrixone/actions/runs/9301220736?pr=16474

**Comment by xzxiong** [comment]
root cause: case 设计问题，多出来的 2行都是  insert 语句，按聚合逻辑是有可能被聚合，也有可能不被聚合 —— 结果不稳定。

**Comment by xzxiong** [comment]
为了保证 不被聚合，有以下几种方式：
1. 用 `/*cloud_user*/` 保证一定不会被聚合。
2. 用 bvt tag `-- @session:id=....` 隔离到不同的 session 下。

**Comment by xzxiong** [comment]
采用 hint `/*cloud_user*/` 解决问题

**Comment by xzxiong** [comment]
ref: https://github.com/matrixorigin/matrixone/issues/14836

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/9319469691/job/25654986820


![image](https://github.com/matrixorigin/matrixone/assets/60595215/661bdced-ddde-49e3-9473-adc9da6fba2e)

**Comment by xzxiong** [comment]
> https://github.com/matrixorigin/ci-test/actions/runs/9319469691/job/25654986820
> 
> <image>

我仔细看了下，整个 result_count 的case 很难控制： statement_info 聚合逻辑 V.S. 预期的query history
我准备通过一下方式解决：
1. 可能需要先屏蔽该bvt
2. 支持一个 session variable控制，当前session 是否进行聚合操作。

**Comment by xzxiong** [comment]
下个迭代

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
Not plan yet

**Comment by xzxiong** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9870656005/job/27257000560?pr=17454
![image](https://github.com/matrixorigin/matrixone/assets/3927687/cb147af4-015c-4c5a-b001-fc01f2f594b1)
```
[/home/runner/work/matrixone/matrixone/upstream/test/distributed/cases/zz_statement_query_type/statement_query_type_1.sql] SQL: select statement,query_type,sql_source_type from  system.statement_info where account="bvt_query_type_part1" and sql_source_type="external_sql" and status != "Running" and statement not like '%mo_ctl%' and aggr_count <1 order by request_at desc limit 96;
```
- root cause: L111 与 L112 + L41 +42 按预期应该会聚合，但聚合策略本来就不稳定。
- ![image](https://github.com/matrixorigin/matrixone/assets/3927687/b4c74a56-5232-45a7-ad20-44c733ec4ad9)

**Comment by xzxiong** [comment]
> > https://github.com/matrixorigin/ci-test/actions/runs/9319469691/job/25654986820
> > 
> > <image>
> 
> 我仔细看了下，整个 result_count 的case 很难控制： statement_info 聚合逻辑 V.S. 预期的query history
> 我准备通过一下方式解决：
> 1.  [x] 需要先屏蔽该bvt
> 2. [ ] 支持一个 session variable控制，当前session 是否进行聚合操作。
> 
> 在解决前，可能需要先重试该case

在 1.3.0 中，计划支持 mo_ctl 可以关闭当前 session 的 statement的聚合逻辑 ==> 保障 bvt 的验证，不用考虑聚合的行为来编辑case

**Comment by xzxiong** [comment]
总结
1. session variable `set session disable_agg_statement  = on;` (default off) 可关闭当前 session 的 statement 的aggr
2. fix bvt case
    - [x] result_count
    - [x] statement_query_type_1
