### ISSUE TITLE
[Bug]:[sqlancer] expression cause mo-server crash

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#1654]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t1 (a int, b int);
mysql> insert into t1 values (1, 2), (3, 4), (5, 6);
mysql> select * from t1 where not (not (-((not (- -1)) + (not (-0)))));

panic: interface conversion: interface {} is []int8, not []int64

goroutine 887 [running]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.Call(0xc002f56be0, {0x55fa3a0, 0xc01f200d50})
	/Users/linjunhong/workspace/matrixone/pkg/sql/colexec/restrict/restrict.go:121 +0x80d
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc01eef42a0, 0x3, 0x18}, 0x73bf878)
	/Users/linjunhong/workspace/matrixone/pkg/vm/vm.go:47 +0x9c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunMerge(0xc01e52d880, 0xc002f56be0)
	/Users/linjunhong/workspace/matrixone/pkg/vm/pipeline/pipeline.go:105 +0x126
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc01eea1b00, {0x5c03580, 0xc004667320})
	/Users/linjunhong/workspace/matrixone/pkg/sql/compile/scope.go:455 +0x4aa
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0xc01eea0800, 0x40d0217)
	/Users/linjunhong/workspace/matrixone/pkg/sql/compile/exec.go:181 +0x116
github.com/matrixorigin/matrixone/pkg/frontend.(*ComputationWrapperImpl).Run(0xc01d1246c0, 0x5c16828)
	/Users/linjunhong/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:858 +0x1c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc01aaf3ef0, {0xc01c794d40, 0x3f})
	/Users/linjunhong/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:1090 +0x263e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc01aaf3ef0, 0xc01ee9f7e8)
	/Users/linjunhong/workspace/matrixone/pkg/frontend/mysql_cmd_executor.go:1209 +0x5b3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc01d126c00)
	/Users/linjunhong/workspace/matrixone/pkg/frontend/routine.go:99 +0x2be
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/Users/linjunhong/workspace/matrixone/pkg/frontend/routine.go:151 +0x1e7

### Expected Behavior

mysql> select * from t1 where not (not (-((not (- -1)) + (not (-0)))));
+------+------+
| a    | b    |
+------+------+
|    1 |    2 |
|    3 |    4 |
|    5 |    6 |
+------+------+
3 rows in set (0.00 sec)

**Comment by m-schen** [comment]
it's due to wrong rewrite for not while rewrite AST.

**Comment by qingxinhome** [comment]
'not(...)' belongs to logical expression and returns bool type, but arithmetic operation is not supported between logical expressions,Therefore, for forms such as: '(not (- - 1)) + (not (- 0))', a semantic error should be reported.Therefore, for sql of 'select * from T1 where not (not (- (not (- - 1)) + (not (- 0));' In version 0.5 which plan2 is supported, semantic errors will be reported for the case when building plans.

**Comment by fengttt** [comment]
Not relevant any more.
