### ISSUE TITLE
[Bug]: mo crashed by panic: runtime error: invalid memory address or nil pointer dereference after 70 hours since stability test on standlone mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16569]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

1d6b2796e2d80ca82f5b66400fc434993f270aaf

### Other Environment Information

```Markdown
- Hardware parameters:
  16C 64G
- OS type:
- Others:
```

### Actual Behavior

after 70 hours since stability test started on standlone mode , the mo crashed by panic:
00e3-76ef-a108-dc8c9a3a0618","session_id":"018fbf85-00e3-76ef-a108-dc8c9a3a0618","statement_id":"018fcd78-98de-7021-bebb-1070b13a6158","txn_id":"018fcd7898de70f2b1dc92bf18c94ec5","span":{"trace_id":"3098fd85-8889-4914-eb53-352615d2ce82","span_id":"2ab4a305ed199805"}}
{"level":"ERROR","time":"2024/05/31 15:06:29.105798 +0800","name":"log-service.frontend","caller":"frontend/routine_manager.go:285","msg":"Failed to handshake with server, quitting routine...","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"write tcp4 172.27.16.14:6001->185.234.216.112:64375: write: connection reset by peer","session_info":"","session_id":"018fcd78-ad71-7bac-95e7-61addf77a3c0","span":{"trace_id":"31e7b11e-8cec-8c58-4db3-0c0f9cfa09d6","span_id":"bd6a27f5ea30ff65"}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x35093b5]

goroutine 25501703 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getSession(0x0?)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/frontend/routine.go:179 +0x35
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed(0xc018844150, {0x51d3aa0, 0xc1cb293000})
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/frontend/routine_manager.go:300 +0x4e
github.com/fagongzi/goetty/v2.(*baseIO).Close(0xc1cb293000)
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:398 +0x17c
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1.1()
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:351 +0x58
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:359 +0x1b7
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 1988
        /home/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x45a

mo-log:
[mo-stb-standone-panic.log](https://github.com/user-attachments/files/15514145/mo-stb-standone-panic.log)

### Steps to Reproduce

```Markdown
1. run a mo on standlone mode
2. run tpch 10g loop queries
3. run tpcc 10-10 longruning test
3. run sysbench mixed cases longrunnig test
```

**Comment by daviszhen** [comment]
未投入

**Comment by aressu1985** [comment]
update on 6.01
commit: 1dc13a239f0bd1ace1ea3e3be959b7d0e15284c3
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9326497774/job/25675168119

<img width="1400" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b6ce9cb0-7fb0-45b9-be9e-cbfa1cc356e5">


mo-log:
{"level":"ERROR","time":"2024/06/01 14:54:27.559178 +0800","caller":"client/operator.go:777","msg":"error: the transaction 018fd28c990e7cc0ae2948f9776b48ed has been committed or aborted"}
{"level":"ERROR","time":"2024/06/01 14:54:27.559236 +0800","caller":"client/operator.go:689","msg":"error: the transaction 018fd28c990e7cc0ae2948f9776b48ed has been committed or aborted"}
{"level":"ERROR","time":"2024/06/01 14:54:27.559270 +0800","name":"log-service.frontend","caller":"frontend/util.go:495","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"execute __mo_stmt_id_1 // prepare __mo_stmt_id_1 from         SELECT id, k, c, pad\n          FROM sbtest1\n          WHERE k IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ; 465005 ; 464996 ; 465040 ; 464979 ; 465047 ; 465002 ; 465036 ; 465007 ; 464997 ; 465048","status":"fail","error":"the transaction 018fd28c990e7cc0ae2948f9776b48ed has been committed or aborted","txn_id":"018fd28c990e7cc0ae2948f9776b48ed","session_info":"connectionId 18105|127.0.0.1:33414|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 11078859|018fd28b-ee9d-7c97-bd91-9058fc205be6","session_id":"018fd28b-ee9d-7c97-bd91-9058fc205be6","statement_id":"018fd28c-990e-7c3d-abf1-a9f4022cb7d4","span":{"trace_id":"a88d73aa-641b-0033-43bd-d05120535835","span_id":"dd22edc0b8acd81f"}}
{"level":"ERROR","time":"2024/06/01 14:54:27.559317 +0800","name":"log-service.frontend","caller":"frontend/txn.go:62","msg":"the transaction 018fd28c990e7cc0ae2948f9776b48ed has been committed or aborted","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 18105|127.0.0.1:33414|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 11078859|018fd28b-ee9d-7c97-bd91-9058fc205be6","session_id":"018fd28b-ee9d-7c97-bd91-9058fc205be6","statement_id":"018fd28c-990e-7c3d-abf1-a9f4022cb7d4","span":{"trace_id":"a88d73aa-641b-0033-43bd-d05120535835","span_id":"dd22edc0b8acd81f"}}
{"level":"ERROR","time":"2024/06/01 14:54:27.559346 +0800","name":"log-service.frontend","caller":"frontend/util.go:495","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"select sbtest1.id, sbtest1.k, sbtest1.c, sbtest1.pad from sbtest1 where sbtest1.k in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)","status":"fail","error":"the transaction 018fd28c990e7cc0ae2948f9776b48ed has been committed or aborted","txn_id":"018fd28c990e7cc0ae2948f9776b48ed","session_info":"connectionId 18105|127.0.0.1:33414|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 11078859|018fd28b-ee9d-7c97-bd91-9058fc205be6","session_id":"018fd28b-ee9d-7c97-bd91-9058fc205be6","statement_id":"018fd28c-990e-7c3d-abf1-a9f4022cb7d4","span":{"trace_id":"a88d73aa-641b-0033-43bd-d05120535835","span_id":"dd22edc0b8acd81f"}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x355c9d5]

goroutine 11079211 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getSession(0x0?)
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:179 +0x35
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed(0xc019fe0930, {0x51e3480, 0xc0f3141900})
        /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:300 +0x4e
github.com/fagongzi/goetty/v2.(*baseIO).Close(0xc0f3141900)
        /home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/session.go:398 +0x17c
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1.1()
        /home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:351 +0x58
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
        /home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:359 +0x1b7
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 2760
        /home/github/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20231122095211-6a25dc9130ca/application.go:348 +0x45a


[mo-panic-sysbench.tar.gz](https://github.com/user-attachments/files/15521238/mo-panic-sysbench.tar.gz)

**Comment by daviszhen** [comment]
与之同一个问题。 https://github.com/matrixorigin/matrixone/issues/16531

**Comment by daviszhen** [comment]
修改pr已经提了。

**Comment by daviszhen** [comment]
等复现

**Comment by daviszhen** [comment]
做了初步修改

**Comment by aressu1985** [comment]
fixed
