### ISSUE TITLE
[Bug]: cn crashed by oom during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16573]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d38e334

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

cn crashed by oom during stability test on distributed mode.
<img width="1406" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/48554f18-ade0-4a98-9d25-880f946d9462">

resources dashboard:
https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-d38e334-20240531221619&from=1717157528000&to=1717237508000

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by aressu1985** [comment]
具体prof消息还没有具体找到，待补充

**Comment by arjunsk** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/9638314/b1ae5ccc-a943-4c64-a05b-c2099c4b3570)

**Comment by arjunsk** [comment]
This could be due to mpool. m-schen, please have a look at this.

**Comment by ouyuanning** [comment]
乐声先帮忙看看，不知道跟tpcc的那个oom有没有一定关系

**Comment by reusee** [comment]
在优化分配器

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
在优化mpool

**Comment by reusee** [comment]
possible fixed commit/PRs:
https://github.com/matrixorigin/matrixone/commit/e520a422ab2d0566593d651365f73c29d62a538a
https://github.com/matrixorigin/matrixone/pull/17113

**Comment by reusee** [comment]
继续优化

**Comment by reusee** [comment]
继续优化

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
oom 应该已经修复

**Comment by reusee** [comment]
如上

**Comment by reusee** [comment]
working on other issues.

**Comment by reusee** [comment]
已知的优化都合并了

**Comment by aressu1985** [comment]
fixed
