### ISSUE TITLE
[Bug]: there were lots of error messages in mo log during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16574]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d38e334

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

mo-log loki link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22kvK%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-d38e334-20240531221619%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717194889948%22,%22to%22:%221717206017221%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1357" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6a871ff3-f1b5-4be6-994b-275f35cd1174">

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
还没处理

**Comment by volgariver6** [comment]
还没处理

**Comment by volgariver6** [comment]
还没处理

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
