### ISSUE TITLE
[Bug]: mo crashed by oom during sysbench read_only case with 1000w basis data on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16572]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

1dc13a239f0bd1ace1ea3e3be959b7d0e15284c3

### Other Environment Information

```Markdown
- Hardware parameters:
64C 256G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9326497774/job/25675168016

<img width="1393" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/a011b902-8669-42bc-a46e-a4ea55fc4b2a">

pprof:
[pprof_oom.tar.gz](https://github.com/user-attachments/files/15521206/pprof_oom.tar.gz)

### Steps to Reproduce

```Markdown
run sysbench read_only case with 1000w basis data and 100 threads on standlone mode

1. run a mo on standlone mode, and create a database `sysbench_db`
2. git clone mo-sysbench repo
    https://github.com/matrixorigin/mo-sysbench.git
3. prepare basic data
    sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_read_only.lua --mysql-db=sysbench_db --tables=10 --table_size=10000000 --threads=100 --time=30 --report-interval=10  prepare 

4. run the read_only test
   sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111    oltp_read_only.lua --mysql-db=sysbench_db --tables=10 --table_size=10000000 --threads=100 --time=300 --report-interval=10  --point_selects=1 --skip-trx=on run
```

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/ed58b9dd-94be-4154-b66d-be07393de33d)

**Comment by YANGGMM** [comment]
@ouyuanning  麻烦看一下

**Comment by aressu1985** [comment]
issue提的不合理，我关闭重新提一个
