### ISSUE TITLE
[Bug]: [date 6.1]standalone regression: sysbench 100w write_only reported dup and w-w conflict

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16577]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cda0e9073d517266c99f72b5866bba2aeedf5533

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9330973432/job/25685172230
<img width="1052" alt="企业微信截图_66d1d8de-fc3d-4e38-a96a-25d89db9afaa" src="https://github.com/matrixorigin/matrixone/assets/113406637/c2fa4fc1-0592-4ba2-a8c6-9c07639ef672">

mo log:
plz contact me

### Steps to Reproduce

```Markdown
standalone regression sysbench 100w write_only
```

**Comment by triump2020** [comment]
DN  报的，应该是最近的 PR 导致

**Comment by triump2020** [comment]
Blocked

**Comment by triump2020** [comment]
Not working on this

**Comment by triump2020** [comment]
Maybe  this pr : https://github.com/matrixorigin/matrixone/pull/16425  leads to this bug,  i 'll confirm this.

**Comment by triump2020** [comment]
单机的 ww/dup 原因已定位到大致原因

**Comment by triump2020** [comment]
@heni02  Fixed it , pls test and close.

**Comment by heni02** [comment]
最近回归没有再出现，再观察两天看看

**Comment by heni02** [comment]
regression一周都没有出现该错误，closed
