### ISSUE TITLE
[Bug]: performance：tke load data parallel performance down  around more 100%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16595]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b9d103d8d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke load data性能降低1倍多
<img width="1365" alt="企业微信截图_c6818b25-80c8-4baa-a286-e454736189c1" src="https://github.com/matrixorigin/matrixone/assets/113406637/4df45370-39cf-404f-9dcd-c3540b2c1e48">

目前正在二分中

### Steps to Reproduce

```Markdown
tke load data test
```

**Comment by heni02** [comment]
二分中
<img width="1170" alt="企业微信截图_42699d8e-336e-4da0-9f5f-e524e4d473f2" src="https://github.com/matrixorigin/matrixone/assets/113406637/c3ae4886-c336-4a6b-aa11-7594135222d4">

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
load性能恢复正常，closed
<img width="1393" alt="企业微信截图_b3eb728c-d431-472d-9f00-fea64de8e128" src="https://github.com/matrixorigin/matrixone/assets/113406637/6bb3fe62-3a17-4df5-8ae4-bc7c8b7da51f">
