### ISSUE TITLE
[Bug]: restore publish-subscribe table report 'can not drop database 'db_name' which is publishing'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16597]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2df0f9c75aa90a3c7f1145c95f37616b15fbf566

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="477" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6c534844-7dba-49d8-a1b4-eda0c2f2b196">

### Expected Behavior

restore successfully.

### Steps to Reproduce

```Markdown
drop account if exists acc02;
create account acc02 admin_name = 'test_account' identified by '111';
drop account if exists acc01;
create account acc01 admin_name = 'test_account' identified by '111';

-- @session:id=1&user=acc01:test_account&password=111
drop database if exists db09;
create database db09;
use db09;
drop table if exists index01;
create table index01(
                        col1 int not null,
                        col2 date not null,
                        col3 varchar(16) not null,
                        col4 int unsigned not null,
                        primary key (col1)
);
insert into index01 values(1, '1980-12-17','Abby', 21);
insert into index01 values(2, '1981-02-20','Bob', 22);
insert into index01 values(3, '1981-02-20','Bob', 22);
select count(*) from index01;

drop table if exists index02;
create table index02(col1 char, col2 int, col3 binary);
insert into index02 values('a', 33, 1);
insert into index02 values('c', 231, 0);
alter table index02 add key pk(col1) comment 'primary key';
select count(*) from index02;

drop database if exists db10;
create database db10;
use db10;
drop table if exists index03;
create table index03 (
                         emp_no      int             not null,
                         birth_date  date            not null,
                         first_name  varchar(14)     not null,
                         last_name   varchar(16)     not null,
                         gender      varchar(5)      not null,
                         hire_date   date            not null,
                         primary key (emp_no)
) partition by range columns (emp_no)(
    partition p01 values less than (100001),
    partition p02 values less than (200001),
    partition p03 values less than (300001),
    partition p04 values less than (400001)
);

insert into index03 values (9001,'1980-12-17', 'SMITH', 'CLERK', 'F', '2008-12-17'),
                           (9002,'1981-02-20', 'ALLEN', 'SALESMAN', 'F', '2008-02-20');

-- @session

drop snapshot if exists sp05;
create snapshot sp05 for account acc01;

-- @session:id=1&user=acc01:test_account&password=111
drop publication if exists pub05;
create publication pub05 database db09 account acc02 comment 'publish db09';
drop publication if exists pub06;
create publication pub06 database db10 account acc02 comment 'publish db10';
-- @ignore:2
show publications;
-- @session

-- @session:id=2&user=acc02:test_account&password=111
drop database if exists sub05;
create database sub05 from acc01 publication pub05;
show databases;
use sub05;
show create table index01;
select * from index02;
-- @session

restore account acc01 from snapshot sp05;  -->出错位置
```

**Comment by Ariznawlll** [comment]
drop account if exists acc03;
create account acc03 admin_name = 'test_account' identified by '111';
-- @session:id=1&user=acc01:test_account&password=111
drop database if exists test03;
create database test03;
use test03;
drop table if exists t1;
create table t1(a int primary key,b int, constraint `c1` foreign key fk1(b) references t1(a));
show tables;
show create table t1;
insert into t1 values (1,1);
insert into t1 values (2,1);
insert into t1 values (3,2);
select * from t1;
-- @session

drop snapshot if exists sp104;
create snapshot sp104 for account acc01;

-- @session:id=1&user=acc01:test_account&password=111
drop publication if exists pub09;
create publication pub09 database test03 account acc02 comment 'publish test03';
-- @session

drop snapshot if exists sp104;
create snapshot sp104 for account acc01;

-- @session:id=2&user=acc02:test_account&password=111
drop database if exists sub08;
create database sub08 from acc01 publication pub09;
show databases;
use sub08;
select * from t1;
-- @session

restore account acc01 from snapshot sp104 to account acc03;

-- @session:id=3&user=acc03:test_account&password=111
show databases;
use test03;
show tables;
select * from t1;
show publications; -->出错位置
-- @session

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
verified
