### ISSUE TITLE
[Bug]: [date 6.3]tke regression: tpcc 1000ware 1000threads reported TT_NEW_ORDER CONNECTION Communications link failure

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16616]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a37c7e579

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9352100991/job/25747773466
<img width="1026" alt="企业微信截图_1706ff25-128a-4a6f-94eb-5d735321c90b" src="https://github.com/matrixorigin/matrixone/assets/113406637/f213e6f4-7dcd-4d83-a09d-ef32af4b3a2d">
cn没有重启
<img width="797" alt="企业微信截图_b2b38d7c-c885-4f54-9f17-dd85a9b4c717" src="https://github.com/matrixorigin/matrixone/assets/113406637/e0408360-cea1-4180-9034-b98d986dc547">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22_0q%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240603%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717444641572%22,%22to%22:%221717444841264%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke tpcc 1000ware 1000threads test
```

**Comment by XuPeng-SH** [comment]
<img width="1785" alt="WeChatWorkScreenshot_092969c0-6077-4af3-bb1e-6dce05b19759" src="https://github.com/matrixorigin/matrixone/assets/39627130/6f9a75f8-5c20-40bc-b033-2e3c26987e98">

**Comment by YANGGMM** [comment]
@reusee 麻烦看一下

**Comment by reusee** [comment]
metrics里看到的时间，不只是读写s3 的时间，也包括调用端的处理时间
已经更新metrics，后面再进一步定位

**Comment by sukki37** [comment]
This issue has been inactive for a while, so we're going to close it for now. If you feel that this issue is still relevant, or you have additional information to provide, please feel free to reopen it or create a new issue.
