### ISSUE TITLE
[Bug]: the result of snapshot read is not correct on tke. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16620]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a37c7e579b2aad67bf7aa072f4fd735fe3fdb0ec

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

第一次创建了快照sp100查询的
<img width="516" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/add121e0-4b1c-450f-8590-676aaf0ee230">
执行了tpcc测试之后查询的：
<img width="511" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/9dea8991-6a31-4da4-ba59-b0560e3b6848">

log:https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Igl%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240603%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

<img width="516" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/add121e0-4b1c-450f-8590-676aaf0ee230">

### Steps to Reproduce

```Markdown
please contact me, i will give you a document
```

**Comment by triump2020** [comment]
Getting snapshot data incorrectly.

**Comment by triump2020** [comment]
@Ariznawlll Pls test!

**Comment by Ariznawlll** [comment]
**commit：3ecff3eefdcb983a1cc1fab0f0042d79b32a292f**
tke环境验证，已通过。

**Comment by Ariznawlll** [comment]
还没合到
