### ISSUE TITLE
[Bug]: ut test fail in TestReadWithSpecialshardAndPartitionPolicy

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#16625]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![企业微信截图_17174833589564](https://github.com/matrixorigin/matrixone/assets/112734932/8e0b10f0-76b2-4100-948b-f155b99b0e5c)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9362098109/job/25770236200?pr=16622
```

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9363679029/job/25775003333?pr=16634

**Comment by zhangxu19830126** [comment]
fixed
