### ISSUE TITLE
[Bug]: restore report 'panic'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16638]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b076d9c50305e2bdbafcf9669633a02f0831e70f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="620" alt="企业微信截图_c754c644-2593-479f-8978-c15cfd1945a6" src="https://github.com/matrixorigin/matrixone/assets/108530700/0ec876f9-cf69-4452-a0fd-9c04a844d176">

log: 太大了，放不下，私发

### Expected Behavior

restore successfully.

### Steps to Reproduce

```Markdown
please contact me, i will give you a test document.
```

**Comment by Ariznawlll** [comment]
{"level":"INFO","time":"2024/06/04 17:31:10.372908 +0800","name":"log-service.frontend","caller":"frontend/snapshot.go:750","msg":"[sp100] start to insert select table: lineitem, insert sql: insert into `tpch_10g`.`lineitem` SELECT * FROM `tpch_10g`.`lineitem` {snapshot = 'sp100'}","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"ERROR","time":"2024/06/04 17:37:39.324750 +0800","name":"log-service.frontend","caller":"frontend/util.go:503","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"insert into tpch_10g.lineitem select * from tpch_10g.lineitem{snapshot = sp100}","status":"fail","error":"internal error: panic too large fixed slice 33554432, max is 16777216: \ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlicePool).acquire\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/slice.go:219\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*cowSlice).append\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/slice.go:65\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).lockAdded\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/txn.go:118\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).addRowLockLocked\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:449\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRowLockLocked\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:397\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:355\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:100\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:87\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/service.go:180\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:468\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:226\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:126\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:99\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/connector/connector.go:43\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/Users/ariznawl/wl_123/matrixone/pkg/vm/vm.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/Users/ariznawl/wl_123/matrixone/pkg/vm/pipeline/pipeline.go:89\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/compile/scope.go:155\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/compile/scope.go:219\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/Users/ariznawl/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/asm_arm64.s:1222","txn_id":"018fe29694997ca69ecd8324a854ce16","session_info":"connectionId 931||{account acc01:test_account:accountadmin -- 1:2:2}|goRoutineId 38473|018fe287-bccd-792b-bcb8-6eb350258f8b","background":true,"session_id":"018fe296-9498-7c9e-8f68-5d12e90ea451","txn_id":"018fe29694997ca69ecd8324a854ce16","span":{"trace_id":"9249592d-17ed-1e59-91f3-d23a7bdf0bcb","span_id":"d8a708833af8734d"}}
{"level":"ERROR","time":"2024/06/04 17:38:13.118901 +0800","name":"log-service.frontend","caller":"frontend/util.go:503","msg":"query trace status","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"restore account acc01 database tpch_10g table lineitem from snapshot sp100","status":"fail","error":"internal error: panic too large fixed slice 33554432, max is 16777216: \ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlicePool).acquire\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/slice.go:219\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*cowSlice).append\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/slice.go:65\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).lockAdded\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/txn.go:118\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).addRowLockLocked\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:449\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).acquireRowLockLocked\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:397\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doAcquireLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:355\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).doLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:100\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).lock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/lock_table_local.go:87\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock\n\t/Users/ariznawl/wl_123/matrixone/pkg/lockservice/service.go:180\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:468\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.performLock\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:226\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.callNonBlocking\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:126\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.(*Argument).Call\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/lockop/lock_op.go:99\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Argument).Call\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/colexec/connector/connector.go:43\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/Users/ariznawl/wl_123/matrixone/pkg/vm/vm.go:135\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/Users/ariznawl/wl_123/matrixone/pkg/vm/pipeline/pipeline.go:89\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/compile/scope.go:155\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/Users/ariznawl/wl_123/matrixone/pkg/sql/compile/scope.go:219\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/Users/ariznawl/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.22.0/libexec/src/runtime/asm_arm64.s:1222","txn_id":"018fe29694987bee878a9173b7e7433e","session_info":"connectionId 931||{account acc01:test_account:accountadmin -- 1:2:2}|goRoutineId 38473|018fe287-bccd-792b-bcb8-6eb350258f8b","session_id":"018fe287-bccd-792b-bcb8-6eb350258f8b","statement_id":"018fe296-9498-7b79-8551-1619e741ba4d","span":{"trace_id":"9249592d-17ed-1e59-91f3-d23a7bdf0bcb","span_id":"d8a708833af8734d"}}

**Comment by ouyuanning** [comment]
之前应该处理过了。估计是stats有错，没有用表锁

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
stats更新的问题在这个pr中有所解决, 可以再测一下
- https://github.com/matrixorigin/matrixone/pull/16847

**Comment by jensenojs** [comment]
待测试

**Comment by jensenojs** [comment]
等snapshot数据里面传了stats之后再看, 现在应该是有bug的

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
等我把restore is too slow的问题解决了, 一并测
- https://github.com/matrixorigin/matrixone/issues/16099

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by jensenojs** [comment]
在下面这个pr合并之后, 问题应该解决了, 辛苦QA同学验证一下. 
- https://github.com/matrixorigin/matrixone/pull/17773

这个issue的校验和下面两个实际上是一个流程, 应该也都fix了, 验收完如果没有问题的话, 辛苦魏璐帮忙close一下啦
- https://github.com/matrixorigin/matrixone/issues/16099
- https://github.com/matrixorigin/matrixone/issues/16138

**Comment by Ariznawlll** [comment]
测试了恢复34G大小的数据，没有再出现，明天要再恢复一下70G大小的数据，看看结果

**Comment by Ariznawlll** [comment]
正在测试74G的恢复

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10505304794/job/29105911058

74G恢复：
系统租户恢复系统租户的数据；
系统租户恢复普通租户的数据到新租户；
普通租户恢复普通租户的数据

以上三点恢复成功，未发生panic
系统租户恢复普通租户到普通租户恢复有bug  issue:18237 跟踪

**Comment by Ariznawlll** [comment]
**1.2-dev commit: ff8d9acec2fb41d8cd85b9bd012d604d3bd3d74b**
**job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10518970679/job/29145596868**

74G恢复：
系统租户恢复系统租户的数据；
<img width="975" alt="image" src="https://github.com/user-attachments/assets/16767328-fbe9-4672-8edb-434cb5914489">

系统租户恢复普通租户的数据到新租户；
<img width="986" alt="image" src="https://github.com/user-attachments/assets/ef50e95d-29e6-4bc6-92d2-e17887d18991">

普通租户恢复普通租户的数据
<img width="979" alt="image" src="https://github.com/user-attachments/assets/60215a4b-5104-48e6-ba93-36587643a704">

以上三点恢复成功，未发生panic
系统租户恢复普通租户到普通租户恢复有bug  issue: 18237 跟踪

**Comment by Ariznawlll** [comment]
还要再加点数据量测试一下

**Comment by jensenojs** [comment]
经验是, 在bug fix之前, 数据行数达到1y就可以稳定复现这个panic

**Comment by Ariznawlll** [comment]
**main commit: c880770abcc2e682702c741ef5485244c814c521
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10626274378/job/29457558653**

**约110G恢复：
系统租户恢复系统租户的数据**：
<img width="973" alt="image" src="https://github.com/user-attachments/assets/29dc7d95-35ed-4027-8001-ab0b14181406">

系统租户恢复普通租户的数据到新租户：
<img width="975" alt="image" src="https://github.com/user-attachments/assets/b65e14d3-dbd8-4d36-aa09-24f055dc257c">

普通租户恢复普通租户的数据
<img width="977" alt="image" src="https://github.com/user-attachments/assets/4818d134-0a88-41a6-9b5f-d204d2590282">

系统租户恢复普通租户的数据到普通租户：
<img width="978" alt="image" src="https://github.com/user-attachments/assets/ba2b2b44-278b-41de-a58f-866f6109b921">

以上四点均恢复成功，未发生panic

**Comment by Ariznawlll** [comment]
**1.2-dev commit: 3b003adb43aac30267433702734533c16c2b82a8
job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10627910181/job/29462569576**

**约110G恢复：
系统租户恢复系统租户的数据，耗时13min5s**：
<img width="974" alt="image" src="https://github.com/user-attachments/assets/649b3874-f405-40f7-ba5a-76b267a5e9dc">

**系统租户恢复普通租户的数据到新租户，耗时19min11s：**
<img width="974" alt="image" src="https://github.com/user-attachments/assets/cf27c509-b63f-44bb-bdca-471ea1f894f7">

**普通租户恢复普通租户的数据，耗时23min31s**


**系统租户恢复普通租户的数据到普通租户，耗时13min51s**
<img width="973" alt="image" src="https://github.com/user-attachments/assets/cabd6f24-382c-45b0-9a37-168b3ec50269">

以上四点均恢复成功，未发生panic

**Comment by Ariznawlll** [comment]
以上测试tke配置均为：

https://github.com/matrixorigin/mo-nightly-regression/blob/big_data/big-data-tke.yaml
