### ISSUE TITLE
Support Matrixone Distributed Verison testing

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#1664]
**Is your feature request related to a problem? Please describe.**

Distribued Version BVT testing

**Describe the feature you'd like**

Testing matrixone cluster with bvt test case.

**Describe alternatives you've considered**

Maybe need jenkins or tekton for build CI/CD pipeline.

If configuration file Always change maybe should change way of gettting configuration. 

**Additional context**

**Comment by yingfeng** [comment]
duplicate with #1642
