### ISSUE TITLE
[Bug]: UT TestS3FS ci fail

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16651]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

UT TestS3FS ci fail

<img width="920" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/71886e4a-74ca-4bdd-8414-07034e88f08d">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9376821021/job/25817396064?pr=16643
```

**Comment by YANGGMM** [comment]
@reusee , 麻烦看一下

**Comment by reusee** [comment]
lookup timeout 
网络问题，重新跑即可

**Comment by gouhongshen** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9379871843/job/25825696150?pr=16674

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9377298908/job/25818646638?pr=16634

**Comment by reusee** [comment]
fixed
