### ISSUE TITLE
[Subtask]: restrict memory usage.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#16655]
### Parent Issue

#16617 Case 2 part 2.   

### Detail of Subtask

This is clearly a bug.    Question will be, 
1. Do restrict really need to use that much memory.   How much memory it is keeping.   When it releases.
2. Why restrict (later calling into table_scan, read,) does not reuse a vector from vector pool?

**Comment by XuPeng-SH** [comment]
依赖vector复用

**Comment by XuPeng-SH** [comment]
依赖vector 复用

**Comment by XuPeng-SH** [comment]
依赖vector复用，table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖vector复用，table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖vector复用，table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖table_scan上层逻辑

**Comment by XuPeng-SH** [comment]
依赖上层逻辑优化

**Comment by XuPeng-SH** [comment]
依赖上层逻辑优化

**Comment by XuPeng-SH** [comment]
依赖上层逻辑优化

**Comment by XuPeng-SH** [comment]
依赖上层逻辑优化

**Comment by XuPeng-SH** [comment]
依赖上层逻辑优化

**Comment by XuPeng-SH** [comment]
依赖上层逻辑优化

**Comment by XuPeng-SH** [comment]
table scan正在重构

**Comment by XuPeng-SH** [comment]
table scan正在重构

**Comment by XuPeng-SH** [comment]
table scan正在重构

**Comment by XuPeng-SH** [comment]
table scan正在重构

**Comment by XuPeng-SH** [comment]
done by #18325 to reuse batch in the prepared statement

**Comment by fengttt** [comment]
Done.   Working with @sukki37 To find out how to close the issue.
