### ISSUE TITLE
[Subtask]: merge sort memory usage 

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#16653]
### Parent Issue

#16617 Case 2 Part 1. 

### Detail of Subtask

Please inspect if merge sort use 8G of memory is expected.    Mergesort should use only same amount of memory as 1 run.

**Comment by w-zr** [comment]
To avoid deletion/update conflicts, it's necessary to preserve the correspondence between each line of the objects before and after the merge. Therefore, the memory consumption during merging is directly proportional to the number of lines in the objects being merged. The following graph shows the memory consumption of the daily regression process for this correspondence yesterday.
![image](https://github.com/matrixorigin/matrixone/assets/28624654/b920cc03-a178-419a-aa98-a22394b6501e)

**Comment by fengttt** [comment]
This is not OK.  As merge sort implementer you must know how much memory you can use, where to get it.  A config, or query scheduler.  One you have the number, you will sort using this number of memory.  Assume it is 8G. You must sort 8G of data in memory and, and spill if data is more than 8G.

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前正在优化手动merge操作。之后会做一些细节测试，查看内存占用。

**Comment by w-zr** [comment]
#17656 合并之后，内存有较大提升。

**Comment by w-zr** [comment]
Memory usage in merging 10M rows:
Before #17656 :
![image](https://github.com/user-attachments/assets/aae00240-0a27-456a-a788-c308225ce479)

After #17656 :
![image](https://github.com/user-attachments/assets/3ac3012d-9a98-48d7-99d0-b7ce26c0ca52)

After #17768:
![image](https://github.com/user-attachments/assets/e866fe8b-0e89-451e-ac82-776f053c88b3)

After #17768, it will be difficult to achieve significant memory optimization in the merge process.
