### ISSUE TITLE
[Bug]:  Excessive Memory Allocation in sysbench Delete Test [DupJmAuxData]

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#16659]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

1ef0439f92f5feaa2a3882a12f1bfa8cd9b54860

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Related to #16617

During the sysbench delete test, the DupJmAuxData component allocated an excessive amount of memory, reaching 670GB within two minutes. This level of memory consumption is highly unusual and indicates inefficient memory usage in the system.

[heap.zip](https://github.com/user-attachments/files/15572602/heap.zip)

<img width="1053" alt="企业微信截图_06ed85eb-b428-4f22-8aa9-e3333a648d1e" src="https://github.com/matrixorigin/matrixone/assets/77312370/9845fd27-72ae-43ef-857d-58df266d4111">

### Steps to Reproduce

```Markdown
run sysbench delete test 100 threads
```

**Comment by fengttt** [comment]
#16617 case 1

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
investigating

**Comment by aunjgr** [comment]
working on a PR

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
on leave

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by badboynt1** [comment]
working

**Comment by badboynt1** [comment]
fixed

**Comment by badboynt1** [comment]
经测试，现在没有dup hash表的内存分配开销了

[alloc_sysbench.zip](https://github.com/user-attachments/files/17502704/alloc_sysbench.zip)

**Comment by heni02** [comment]
confirm,closed
