### ISSUE TITLE
[Subtask]: Join that creates too many proc

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#16656]
### Parent Issue

#16617 Case 1, more info.

### Detail of Subtask

Also this one consumes lots of memory.   
<img width="1910" alt="企业微信截图_c53d4d14-a190-45bb-8d0e-dd1d0f859cd8" src="https://github.com/matrixorigin/matrixone/assets/169294/7917719d-a55c-45e9-a0ed-ded52861a004">

We have too many pros.    So we must answer the following questions, 
1. Are they necessary?   After we fix Join pipeline (that is, join is one single pipeline, with one proc), all these are gone, correct?
2. Should these joins run in parallel at all.    If yes, how many threads/procs.

**Comment by badboynt1** [comment]
等tp pipeline合并完成以后再观察一下

**Comment by badboynt1** [comment]
等tp pipeline合并完成以后再观察一下

**Comment by badboynt1** [comment]
pipeline重构只能减少process的数量，要从根源上解决问题，需要在这里做个proc的复用

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/2cf4b8e7-c8ea-42e4-b915-cb9d3be16b4c)

从2.4%下降到2%  还需要继续优化

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/4fc79deb-0757-485b-a5ea-c6c7e7fa1a8f)

又跑了一次，现在已经下降到0.18%
