### ISSUE TITLE
[Bug]: bvt fail in auto_increment

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16658]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="947" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/ce57d9e4-d369-4df4-a10b-832daa22e9e3">

### Steps to Reproduce

```Markdown
fail link:https://github.com/matrixorigin/matrixone/actions/runs/9377061995/job/25818010080?pr=16626
```

**Comment by YANGGMM** [comment]
@w-zr 麻烦看一下

**Comment by YANGGMM** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/9377134582/job/25818200707?pr=16605

**Comment by w-zr** [comment]
already fixed in https://github.com/matrixorigin/matrixone/pull/16551
