### ISSUE TITLE
[Bug]: [0605 big data regression] insert into select oom. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16650]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

43ebd753a8342ea4ff2d64362e1420ae96e725e9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9366247347/job/25799726334 （load and insert test-> insert into select）

<img width="1501" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/3acb9ea0-1ef6-4d72-86c2-e9657f8796ca">

<img width="1873" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/24e77543-7dfb-444a-8f8e-a8e202d00c6d">

<img width="1026" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2fcfd459-afb9-4d95-a545-013f406a5953">

log:https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22vSV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240604%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
[2024-06-04_16_56_47.zip](https://github.com/user-attachments/files/15572218/2024-06-04_16_56_47.zip)
[2024-06-04_16_55_08.zip](https://github.com/user-attachments/files/15572221/2024-06-04_16_55_08.zip)

### Steps to Reproduce

```Markdown
trigger big data test on tke.
If you need some test details, please contact me.

```

**Comment by YANGGMM** [comment]
@ouyuanning 麻烦看一下

**Comment by ouyuanning** [comment]
辛苦锦赛统一看看吧

**Comment by jensenojs** [comment]
无进展

**Comment by jensenojs** [comment]
上面issue message中的profile文件夹中没有oom节点的pprof信息, 魏璐帮忙找了一下grafana抓的几天前跑的结果, 根据
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9520234425/job/26245691714
的时间戳, 2024-06-14T22:16:32.9569289Z 2024-06-15 06:16:32,956
<img width="1691" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/e839659d-416d-412a-b6ce-52c633b4a665">

定位到grafana对应时间段的inuse memory 如下所示 : 

<img width="1700" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b8e7d104-f9f9-406f-b4ab-50a6679d7fee">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240614%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221718403392000%22,%22to%22:%221718432192000%22%7D%7D%7D&schemaVersion=1&orgId=1

向魏璐确认了一下配置是14c 55g, 不理解为什么这里的单位是TB, 以及看需要向徐鹏哥请教一下这里是怎么回事.

**Comment by jensenojs** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Bjf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240614%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-vhhfr%5C%22%7D%20%7C~%20%60gc%20.%2Aglobal%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718403317000%22,%22to%22:%221718403557000%22%7D%7D%7D&schemaVersion=1&orgId=1

从`gc .*global`的正则匹配中看到是`nightly-regression-dis-tp-cn-vhhfr`的oom, 这个阶段的`inuse`的内存占用是比较多的, 

<img width="1547" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/4d2869d5-5da0-4c2a-9f58-7f50954de56c">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240614%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-vhhfr%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221718403500000%22,%22to%22:%221718403520000%22%7D%7D%7D&schemaVersion=1&orgId=1

下面的优化做了之后可能能解决这个issue的问题
- https://github.com/matrixorigin/matrixone/issues/16375

**Comment by jensenojs** [comment]
还需要继续优化, 现在有最新的问题 : https://github.com/matrixorigin/matrixone/issues/17143#issuecomment-2188493489

**Comment by jensenojs** [comment]
等1.2-dev上的pr进去

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
等待合并

**Comment by Ariznawlll** [comment]
最近没有再出现这个问题，先关闭
