### ISSUE TITLE
[Tech Request]: support between-and filter in the reader

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16654]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Support between-and filter in the reader
```

### Why is this needed ?

For oltp-read-only test case

**Comment by gouhongshen** [comment]
working on `in mem reader filter`

**Comment by gouhongshen** [comment]
完成
