### ISSUE TITLE
[Bug]: ctrl-c mo service will panic

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16665]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1702" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/0a7a1d47-def0-4b38-aed1-4125214795f0">

### Steps to Reproduce

```Markdown
1. Start MO
2. Do some test
3. CTRL-C mo service
```

**Comment by YANGGMM** [comment]
@qingxinhome 麻烦看一下

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/bfbe397d-4fb2-478f-a70e-15859d861297)

**Comment by zhangxu19830126** [comment]
fixed

**Comment by Ariznawlll** [comment]
**commit: 09c4d95dcdc615e1ea924239ff72af8c7863e286**
<img width="693" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a933b703-e8f8-4f30-923e-40b1b39db54a">

verified.
