### ISSUE TITLE
[Bug]: show subscription all;报错

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#16662]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

9e877c5419ed2f926ed7ddb2140e0cf1056c1a84

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
aliyun dev环境
```

### Actual Behavior

show subscription all;报错
ERROR 20101 (HY000): internal error: <nil> can't convert to timestamp type

### Expected Behavior

正常执行

### Steps to Reproduce

```Markdown
必现
```

### Additional information

云实例复现链接串：
https://github.com/matrixorigin/MO-Cloud/issues/2101#issuecomment-2148801361

**Comment by heni02** [comment]
#16313一起解决了show subscription all的问题 ，bvtcase已加
confirm,closed
