### ISSUE TITLE
[Bug]: ut failed. TestCompile

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16679]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: implement me

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/memoryengine.(*CompilerContext).GetSnapshot(0x74ec00000001?)
        /home/pengzhen/Documents/matrixone/pkg/vm/engine/memoryengine/compiler_context.go:54 +0x25
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder(0x1, {0x46cdee8, 0xc002ca0500}, 0xc002c699e0, 0x0)
        /home/pengzhen/Documents/matrixone/pkg/sql/plan/build.go:38 +0x107
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x46cdee8, 0xc002ca0500}, {0x4643e50, 0xc002c699e0}, 0x0)
        /home/pengzhen/Documents/matrixone/pkg/sql/plan/build.go:95 +0x12d3
github.com/matrixorigin/matrixone/pkg/sql/compile.newTestCase({0x3d0fc2b, 0x8}, 0xc0000f91e0)
        /home/pengzhen/Documents/matrixone/pkg/sql/compile/compile_test.go:186 +0x16c
github.com/matrixorigin/matrixone/pkg/sql/compile.init.2()
        /home/pengzhen/Documents/matrixone/pkg/sql/compile/compile_test.go:62 +0x3d
exit status 2
FAIL    github.com/matrixorigin/matrixone/pkg/sql/compile       0.027s

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
always
```

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
fixed
<img width="771" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/152c20a2-6720-408f-9326-a5f0155ad68a">

<img width="1099" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/b3158822-7ef1-46e0-95a2-24229c5af0b9">
