### ISSUE TITLE
[Bug]: insert into select hung report many warning "msg":"too many collision for fuzzy filter"

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1228" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/1fb6f68d-1801-4a8a-b5fe-d4f0af8a871b">

### Steps to Reproduce

```Markdown
run tpcc and then restore  as https://github.com/matrixorigin/matrixone/issues/16099
```

**Comment by YANGGMM** [comment]
{"level":"INFO","time":"2024/06/05 16:18:55.023114 +0800","caller":"compile/compile.go:2952","msg":"xxxx emtimated stats is 1010.000000"}

**Comment by jensenojs** [comment]
dup with : 
- https://github.com/matrixorigin/MO-Cloud/issues/3462

我就在那个issue那里跟踪就好了

**Comment by jensenojs** [comment]
等待pr合并

**Comment by jensenojs** [comment]
相关pr已经合并

- https://github.com/matrixorigin/matrixone/pull/16830

<img width="1461" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/d85d75f2-8430-4464-8a5a-a92efca2ef20">


测试的方式是用insert的方式导入一个23G的数据, 然后搜一下看看有没有相关的报错, 现在看已经fix了
