### ISSUE TITLE
[Bug]: mo oom caused by gc untimely during sysbench 1000w test in daily regression on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16682]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

1ef0439f92f5feaa2a3882a12f1bfa8cd9b54860

### Other Environment Information

```Markdown
- Hardware parameters:64C 128G 
- OS type:
- Others:
```

### Actual Behavior

During sysbench 1000w test on daily regression, GC was not timely and caused mo killed by oom when running read_only cases.
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9364954572/job/25779081887

And can find that the mem usage increasing more and more as test lasting.
<img width="897" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/c592b318-4dbb-415f-909e-1484e880d8c8">

[resr_sysbench_1000w.txt]
(https://github.com/user-attachments/files/15581330/resr_sysbench_1000w.txt)

the mo gc log:
[gc.log](https://github.com/user-attachments/files/15581406/gc.log)

and the other infomation is put on 128 srv. If wanted, can get from this path[ /data/mo-nightly-regression/sysbench_1000w_no_interval ]

### Steps to Reproduce

```Markdown
run sysbench 1000w cases on standlone mode
can use this job
https://github.com/matrixorigin/mo-nightly-regression/actions/workflows/sysbench100w-regression-test-no-interval.yml
```

**Comment by YANGGMM** [comment]
@LeftHandCold  麻烦看一下

**Comment by YANGGMM** [comment]
@ouyuanning  麻烦看一下

**Comment by heni02** [comment]
main 分支也出现sysbench1000w read_only oom
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9386897563/job/25848742704
<img width="1326" alt="企业微信截图_f531a27a-4e88-4c0a-acb1-9b42c9ba7113" src="https://github.com/matrixorigin/matrixone/assets/113406637/9f7a9526-fb29-4edf-83b1-d0cacb7ebaf4">
<img width="1162" alt="企业微信截图_41e6f7ce-90a0-455e-8838-fadcfe1e79aa" src="https://github.com/matrixorigin/matrixone/assets/113406637/e7549ae3-a1a1-43a9-b399-cd17c5fc4aec">

profile:
[read_only_oom_main.zip](https://github.com/user-attachments/files/15599169/read_only_oom_main.zip)
gc log：
[gc0606.log](https://github.com/user-attachments/files/15599189/gc0606.log)

**Comment by LeftHandCold** [comment]
在测试sysbench 1000w 1000并发的read write时候发现如下：
查看alloc_space整体allocate主要消耗在 cn的parttion read中的copy batch。
<img width="2331" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/ececb6b3-d8eb-4373-b11c-ed0c334803b8">
但是有一个奇怪的现象是，当read write case跑完之后。查看inuse_space，发现在heap里parttion read中的copy batch一直是2G左右。三个分别是538M，609M，729M，此时rss是40G+
<img width="2159" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/a189bfd3-2217-429a-8c20-c5443c25e714">
大概6分钟后heap再次发生变化 三个引用不见了，此时rss是21G+
<img width="2283" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/a57ef1f8-cf1e-416c-ae08-0753dea7fffe">

**Comment by LeftHandCold** [comment]
尝试过很多次都是这种现象，我理解中在inuse_space里面，parttion read中的copy batch，应该跑完case马上释放才对，但是现在的现象是并没有，并且引用时间高达5 6分钟。最终当inuse_space中的引用看不到时候，也就是rss释放物理内存的时候。

**Comment by sukki37** [comment]
tracked by #https://github.com/matrixorigin/matrixone/issues/16617 and its subtasks
