### ISSUE TITLE
[Bug]: ut failed. TestReadWithSpecialShard

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16683]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0604-debug-txn-panic

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/4e2117bf-f9e6-4e63-8278-1423f157835e)

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9377298908/job/25829225791?pr=16634
```

**Comment by YANGGMM** [comment]
@zhangxu19830126 麻烦看一下

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理

**Comment by zhangxu19830126** [comment]
未处理
