### ISSUE TITLE
[Bug]: mo report `internal error: do not have privilege to execute the statement`

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#16708]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

30278c7c8e91e45443e558475139b3274c84afe4

### Other Environment Information

```Markdown
- Hardware parameters: tke mergerun
- OS type:
- Others:
```

### Actual Behavior

While running the test, mo-tester reported that mo returned an error `internal error: do not have privilege to execute the statement` causing the test to fail, and that mo was unavailable in its entirety afterward

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9389298565/job/25856468334
```

**Comment by YANGGMM** [comment]
@daviszhen  麻烦看一下

**Comment by daviszhen** [comment]
@YANGGMM 帮看下。

**Comment by YANGGMM** [comment]
还在看
