### ISSUE TITLE
[Bug]: cn crashed by fatal "wait latest commit ts failed" during statbility test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16716]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

e6b2868

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

During statbility test on distributed mode, cn was crashed by fatal :
{"level":"FATAL","time":"2024/06/05 22:09:44.081179 +0000","name":"cn-service.txn","caller":"client/client.go:434","msg":"wait latest commit ts failed","uuid":"65393636-3165-6662-6631-633163326338","error":"waiter is paused","stacktrace":"github.com/matrixorigin/matrixone/pkg/txn/client.(*txnClient).SyncLatestCommitTS\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/client.go:434\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*sqlExecutor).maybeWaitCommittedLogApplied\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/sql_executor.go:154\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*sqlExecutor).ExecTxn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/sql_executor.go:144\ngithub.com/matrixorigin/matrixone/pkg/incrservice.(*sqlStore).Allocate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/store_sql.go:160\ngithub.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).doAllocate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:164\ngithub.com/matrixorigin/matrixone/pkg/incrservice.(*allocator).run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/incrservice/allocator.go:151\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:277"}

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Jyy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-e6b2868-20240605224953%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717623352647%22,%22to%22:%221717626935791%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by aressu1985** [comment]
[2024-06-06 06:09:44.081 FATAL]
[06-07-2024-17-35-08_files_list.zip](https://github.com/user-attachments/files/15734605/06-07-2024-17-35-08_files_list.zip)

[2024-06-06 06:14:54 FATAL]
[06-07-2024-17-37-50_files_list.zip](https://github.com/user-attachments/files/15735061/06-07-2024-17-37-50_files_list.zip)

[2024-06-06 06:18:44 FATAL]
[Uploading 06-07-2024-17-38-47_files_list.zip…]()

**Comment by XuPeng-SH** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Jyy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-e6b2868-20240605224953%5C%22,%20matrixorigin_io_component%3D%5C%22DNSet%5C%22%7D%20%7C%3D%20%60long%20pull%20cost%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221717624521109%22,%22to%22:%221717625197109%22%7D%7D%7D&schemaVersion=1&orgId=1

pull logtail耗时一分多钟，导致commit阻塞, 可能和flush相关

**Comment by aptend** [comment]
flush 的调度等待时长和执行时长都存在消耗超过预期，复现中

**Comment by aptend** [comment]
增加日志记录秒级别的flush任务，主要观察两点：1. 任务调度延迟 2. 收集 deletes 的 io 时间

**Comment by aptend** [comment]
pr前
<img width="823" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/df6404f3-ce17-40c0-9296-2bf71395a5ad">

pr后
<img width="834" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/dc2429d9-1e08-4127-a685-ca4799e256f8">

flush时间已大幅减少

**Comment by aptend** [comment]
daily 耗时均不超过10s, pull logtail 暂未出现耗时过长的情况

**Comment by aressu1985** [comment]
未解决
6-18号晚 分布式稳定性测试再次跑出来该问题。

commit: 20f9de6


<img width="1417" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/cf64d6b7-3d42-400a-b7c5-51cbd38d875b">


mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22mY0%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-20f9de6-202406182258%5C%22%7D%20%7C%3D%20%60wait%20latest%20commit%20ts%20failed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718746773130%22,%22to%22:%221718751346870%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fxied
