### ISSUE TITLE
[Bug]: lots of longrunning queries and leak cuase mo hung during statbility test on distributed mode(1.2-dev)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16715]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

e6b2868

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

during statbility test on distributed mode, nearly 8 hourse later, there were longrunning txn comming and made mo hung at last.

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9386230210/job/25846288135

mo-log:
[long runnig]
<img width="1356" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ed907f6d-04a2-48f5-bd14-82ddf13a266a">

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Jyy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-e6b2868-20240605224953%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717627344152%22,%22to%22:%221717656182362%22%7D%7D%7D&schemaVersion=1&orgId=1

[leak]
<img width="1356" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/9f3e7e67-3863-4e8f-92ff-8768a02a989c">

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Jyy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-e6b2868-20240605224953%5C%22%7D%20%7C%3D%20%60leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717623753489%22,%22to%22:%221717645078973%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by daviszhen** [comment]
leak 时间点的日志都没有了。


https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Jyy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-e6b2868-20240605224953%5C%22%7D%20%7C%3D%20%60leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717623753489%22,%22to%22:%221717645078973%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
mo_logger 的 load语句卡住

2024/06/06 09:27:10.573516 +0000 ERROR cn-service found long running txn {"uuid": "", "txn-id": "018fecd5d5b17b98a641c58c917beede", "create-at": "2024/06/06 09:16:27.953788 +0000", "options": "Features:33 CN:\"65393636-3165-6662-6631-633163326338\" SessionID:\"018fecd5-d4e4-7c5f-9e10-9b3455826148\" ConnectionID:20378980 UserName:\"mo_logger\" counter:\"commit: enter:0, exit:0 rollback: enter:0, exit:0 runSql: enter:1, exit:0 footPrints: [0: enter:1 exit:0] [1: enter:1 exit:0] [2: enter:1 exit:0] [3: enter:1 exit:0] [4: enter:1 exit:0] [5: enter:1 exit:0] [6: enter:1 exit:0] [7: enter:1 exit:0] [8: enter:1 exit:0] [62: enter:1 exit:0] [77: enter:1 exit:1] \" sessionInfo:\"connectionId 20378980||{account sys:mo_logger:moadmin -- 0:4294967295:0}|goRoutineId 4500064|018fecd5-d4e4-7c5f-9e10-9b3455826148\" inRunSql:true autocommit:true ", "profile": "ETL:/profile/routine_018fecdf-9968-78c8-8b0c-06351d20fed0.gz"}

**Comment by daviszhen** [comment]
初步结论：

```

W-w conflict => txn trace 卡住 (自增列 套 自增列)  
	trace 关掉再看


 Logtail 卡
	commit 出错（某个错误）=>写trace 导致 卡住。
	
结论： 先关闭trace跑

```

**Comment by daviszhen** [comment]
txn trace 修复后。没复现。
