### ISSUE TITLE
[Bug]: service SHARED not found

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16714]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0604-debug-txn-panic

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/9385209892/job/25842799789
```

### Actual Behavior

2024/06/05 13:57:26.660846 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.664890 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.707273 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.739469 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.763885 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.768124 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.772906 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.777117 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.781148 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.785402 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.791212 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.795812 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.818470 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:26.828416 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.665775 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.689923 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.712923 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.772235 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.778877 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.784627 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.789590 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.793963 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.800843 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.806377 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.811803 +0000 ERROR fileservice/get.go:36 error: service SHARED not found
2024/06/05 13:57:30.816452 +0000 ERROR fileservice/get.go:36 error: service SHARED not found

### Expected Behavior

maybe no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9385209892/job/25842799789
```

**Comment by YANGGMM** [comment]
@reusee  麻烦看一下

**Comment by reusee** [comment]
调用方没传入正确的 fileservice 实例，所以找不到 SHARED。

working as expected.

**Comment by daviszhen** [comment]
正确的fileservice的实例是啥？

**Comment by reusee** [comment]
fileservice 实例，需要从 mo-service 包创建之后，一路传递到使用的地方
如果没有正确传递，就会出现 SHARED 实例找不到的错误
SHARED 实例肯定是正确初始化了的，问题在于传递

**Comment by reusee** [comment]
有很多模块都会 get shared 实例，可以参考下。这个实例可以像 cnservice / tnservice 一样，只 get 一次，放到某个字段，后续只用这个，就不需要每次都调用 Get 函数了

![Screenshot from 2024-06-06 22-37-59](https://github.com/matrixorigin/matrixone/assets/398457/9f9a443c-82e7-41a1-9421-d6fd1730fe0f)

**Comment by daviszhen** [comment]
还未找到原因。

**Comment by daviszhen** [comment]
@reusee 兼容 s3和shared 后，应该是没问题了而。
