### ISSUE TITLE
[Bug]: capital letter issue about function hex().

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16710]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d2ef6ab8c8cc8b1ccf2f6c79c8643fc7abffb2d8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1681" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d0d407c3-ffa7-4c62-996e-fadbb75ad7a1">

### Steps to Reproduce

```Markdown
select hex('abcdefghijklmnopqrstuvwxyz');
```

**Comment by arjunsk** [comment]
If this fix needs to be cherrypicked to 1.2-dev, then I need this PR to be cherry-picked to 1.2-dev as well https://github.com/matrixorigin/matrixone/pull/16711

**Comment by Ariznawlll** [comment]
```
case:
select hex('abcdefghijklmnopqrstuvwxyz');
```

<img width="1245" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/69ea7d39-afae-450b-b19d-bb559c52cd62">

**Comment by Ariznawlll** [comment]
```
case: 
select unhex("7FFFFFFFFFFFFFFF")；
select unhex('7FFFFFFF'); 
select unhex('C3716BA2'); 
```

<img width="1231" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c5ad2ba6-24ac-47f9-be0e-2451e5307878">

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
