### ISSUE TITLE
[Bug]: cn crashed by panic: interface conversion: interface {} is nil, not *config.ParameterUnit during statbility test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16724]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

e6b2868

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

during statbility test on distributed mode, one cn crashed by panic:
<img width="1345" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/426dd2b2-8fc7-4450-88d0-1b8299b578e4">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Jyy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-e6b2868-20240605224953%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717624446705%22,%22to%22:%221717626469448%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by daviszhen** [comment]
初步看，这个任务是在mo server还未初始化时，就开始执行了。此时global pu还未初始化

**Comment by xzxiong** [comment]
[link](http://localhost:3000/goto/kT2enXySR?orgId=1)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/b1ea91a5-ef07-45d3-9d23-a3528e15aa89)

**Comment by daviszhen** [comment]
以及修改了。

**Comment by aressu1985** [comment]
fixed
