### ISSUE TITLE
[Bug]: [date 6.6]1.2-dev standalone regression: sysbench1000w read_write reported lock table bind changed but mo not stoped  

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16732]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

32e1e5386f00b21935d3c0cc5a6a3e3113a12a02

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9394778277/job/25873089800
<img width="1031" alt="企业微信截图_5acc6ac2-a6ad-46e0-81d9-e026d1fe0bdf" src="https://github.com/matrixorigin/matrixone/assets/113406637/3855dccf-1766-4eb1-91f8-9e66b04bc681">

17:25:22 左右内存占用229G
<img width="1091" alt="企业微信截图_d7cf11fe-b633-430a-87b6-c72222b36803" src="https://github.com/matrixorigin/matrixone/assets/113406637/ba4df529-4627-4f89-b2be-d90e37b2da83">

17:25:22时间profile：
[locktable_profile.zip](https://github.com/user-attachments/files/15614280/locktable_profile.zip)

mo log plz contact me

### Steps to Reproduce

```Markdown
standalone sysbench1000w read_write test
```

**Comment by YANGGMM** [comment]
@iamlinjunhong  麻烦看一下

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by heni02** [comment]
confirm,closed
1.2-dev commit:613cb4912cafc1be0f63491dbfc4333b89939a19
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9590735366/job/26446620090
