### ISSUE TITLE
[Bug]: CI UT TestCompaction2 failed， Sometimes it appears

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#16740]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9d9c849b2dca43f1cd0fb13d544000c58721e2d4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tables_test.go:693: 
         	Error Trace:	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/test/tables_test.go:693
         	Error:      	Should be false
         	Test:       	TestCompaction2
 --- FAIL: TestCompaction2 (0.17s)

### Expected Behavior

UT test success

### Steps to Reproduce

```Markdown
CI testing sometimes occurs
```

**Comment by qingxinhome** [comment]
[job-logs.txt](https://github.com/user-attachments/files/15690162/job-logs.txt)

**Comment by sukki37** [comment]
dup with #15950
