### ISSUE TITLE
 Implement interface Size(string) in AOE engine

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#1674]
**Is your feature request related to a problem? Please describe.**

The interface Size(string) hasn't be implemented in AOE engine. Computation layer cannot get the size of a certain table.

**Describe the feature you'd like**

Enable computation layer to know the size of a certain table.

**Describe alternatives you've considered**

Implement the interface Size(string)  for the struct relation in AOE engine.

**Additional context**

**Comment by yingfeng** [comment]
fix by #1591
