### ISSUE TITLE
[Bug]: [date 6.6]tke regression: tpcc 500ware 1000threads test cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16741]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

288fcef20

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9402783044/job/25908076699
<img width="1039" alt="企业微信截图_6ca22dd5-b8ab-4e31-ae32-6505c890d64e" src="https://github.com/matrixorigin/matrixone/assets/113406637/0267d8a8-33f3-45d8-b7bd-a2b07b1b81e1">
<img width="1427" alt="企业微信截图_5f9f7534-656a-4165-9e37-908c3dc3e937" src="https://github.com/matrixorigin/matrixone/assets/113406637/8cf7ed75-efc7-40e7-a028-dde675dabb41">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hXV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240606%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717706820000%22,%22to%22:%221717707057000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dnH%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240606%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:alloc_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221717706817493%22,%22to%22:%221717706914132%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc 500ware 1000threads test
```

**Comment by heni02** [comment]
mo 自带的profile信息，抓取的两个时间2024-06-07 04:46:34 2024-06-07 04:47:03，oom前和oom后
[hn_download_tmp.zip](https://github.com/user-attachments/files/15703882/hn_download_tmp.zip)

**Comment by heni02** [comment]
date 6.7 regression也复现了 cc @reusee 
job：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9418697195/job/25953862790
<img width="1047" alt="企业微信截图_b2d893c8-876e-4fb4-997f-904fa79fcd28" src="https://github.com/matrixorigin/matrixone/assets/113406637/7ced567a-8e20-4152-9f1c-5e5248af0edb">

profile：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22oS6%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240607%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-9c8hq%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:alloc_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221717789930000%22,%22to%22:%221717789990000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by reusee** [comment]
https://grafana.ci.matrixorigin.cn/d/c94fd2f4-b3b5-401f-b3d3-f998584c097a/go-runtime-metrics?orgId=1&var-interval=1m&var-namespace=mo-nightly-regression-20240610&var-pod=nightly-regression-dis-tp-cn-5x5j5&from=1718029800000&to=1718118000000&viewPanel=159

从这个指标看，是 cn 的 go 堆占用很多。在达到 54.2G 之后，发生了 OOM。
估计还是 mpool 分配的内存太多的问题。

**Comment by reusee** [comment]
https://grafana.ci.matrixorigin.cn/goto/noMbrI8SR?orgId=1

从 heap profile 看，也是 go 堆占用高。最高时到了 91.9GB。次高峰是 47.2GB。这个量加上堆外的内存，是超过限额的了。

后续的优化方向，是mpool的重构。

**Comment by reusee** [comment]
mpool重构中

**Comment by reusee** [comment]
大致可以确定是goroutine泄露，具体的泄露路径，需要pyroscope开启goroutine profile，才能看到。

**Comment by reusee** [comment]
继续优化

**Comment by reusee** [comment]
继续优化

**Comment by reusee** [comment]
已优化

**Comment by heni02** [comment]
confirm，closed
commit： b01bc0969
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9859053435/job/27222735779
