### ISSUE TITLE
Implement interface rows() in AOE engine

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#1675]
**Is your feature request related to a problem? Please describe.**

The interface Rows() hasn't be implemented in AOE engine. Computation layer cannot get the number of rows of a certain table.

**Describe the feature you'd like**

Enable computation layer to know the number of rows of a certain table.

**Describe alternatives you've considered**

Implement the interface Rows() for the struct relation in AOE engine.

**Additional context**

**Comment by yingfeng** [comment]
fix by #1591
