### ISSUE TITLE
[Bug]: tpcc consistency check failed during stability test on distributed mode, but for only a while 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16764]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

c848d1c

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

tpcc consistency check failed during stability test on distributed mode, but only for a while.
2024-06-09 02:00:28 ERROR ConsistencyCheck:145 - Consistency verification failed for sql : (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);
2024-06-09 02:00:28 ERROR ConsistencyCheck:146 - The exceptional result are :
9       8       7226
10      6       7242
4       4       7251
6       6       7237
10      2       7253
9       6       7290
10      1       7200
8       9       7215
2       8       7270
3       10      7235
6       8       7282
10      3       7312
7       3       7329
7       5       7238
2       1       7196
5       10      7195
2       9       7371
7       4       7364
2       2       7146
6       7       7151
4       10      7271
8       7       7277
9       7       7320
2       3       7284
4       5       7283
5       8       7234
3       8       7287
3       6       7166
8       1       7281
8       8       7428
2       10      7305
5       1       7271
7       2       7242
8       6       7297
3       7       7197
9       4       7255
3       1       7261
3       5       7263
6       3       7288
6       1       7246
1       10      7280

...

-18
-18
-18
-18
-18
-18

2024-06-09 02:01:05 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:01:42 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:02:20 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:02:58 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:03:34 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:04:11 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:04:49 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:05:26 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:06:03 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:06:40 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:07:18 INFO  ConsistencyCheck:149 - Consistency verification successfully.
2024-06-09 02:07:54 INFO  ConsistencyCheck:149 - Consistency verification successfully.

the whole check log
[check.log](https://github.com/user-attachments/files/15751369/check.log)

mo log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22ab5%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-c848d1c-20240607223545%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221717740000000%22,%22to%22:%221717898399000%22%7D%7D%7D&schemaVersion=1&orgId=1

**The tpcc test start from [2024-06-07 22:43:20  UTC] to [2024-06-09 09:43:20  UTC]**, the mo tools log :
[tpcc.log.zip](https://github.com/user-attachments/files/15751380/tpcc.log.zip)

the mo cluster is on IDC, the namespace is : 
[github@mo-srv-128 mo-tpcc]$ kubectl -n mo-nightly-c848d1c-20240607223545 get pod
NAME                                   READY   STATUS    RESTARTS   AGE
stability-regression-dis-dn-0          1/1     Running   0          43h
stability-regression-dis-log-0         1/1     Running   0          43h
stability-regression-dis-log-1         1/1     Running   0          43h
stability-regression-dis-log-2         1/1     Running   0          43h
stability-regression-dis-proxy-48xhp   1/1     Running   0          43h
stability-regression-dis-proxy-6kfdt   1/1     Running   0          43h
stability-regression-dis-tp-cn-4tfpc   1/1     Running   0          43h
stability-regression-dis-tp-cn-7rkcp   1/1     Running   0          43h
stability-regression-dis-tp-cn-8qzwc   1/1     Running   0          43h

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by LeftHandCold** [comment]
发现当时有做gckp后然后订阅的操作，之后就出现ww和一致性问题了

**Comment by LeftHandCold** [comment]
复现步骤如下：
1：run tpcc 10-10
2: 使用客户端登陆mo，执行(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district) except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);此时正常
<img width="1214" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/b211c80f-120b-4e38-aad2-6e4abb34f9d7">
3:使用sql取消tpcc所有表的订阅。sql如下select mo_ctl('cn', 'UNSUBSCRIBE_TABLE', 'cn的uuid:db id: table id'); 例如：select mo_ctl('cn', 'UNSUBSCRIBE_TABLE', 'dd1dccb4-4d3c-41f8-b482-5251dc7a41bf:272506:272507');
此时执行(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district) except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);出现异常
<img width="1368" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/1beb3ed3-c908-461f-8e8b-566df9ae4d4a">

**Comment by triump2020** [comment]
@aressu1985  Pls test.

**Comment by triump2020** [comment]
1.2-dev 已经合并，main 分支还没有

**Comment by aressu1985** [comment]
fixed
