### ISSUE TITLE
Support for Prophet initialization cluster deployment

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#1677]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the feature you'd like**

Support for Prophet initialization cluster deployment

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by zhangxu19830126** [comment]
Duplicate with [Cube-669](https://github.com/matrixorigin/matrixcube/issues/669)
