### ISSUE TITLE
[Bug]: mo hung in ci bvt test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16795]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

addCase3302

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/matrixone/actions/runs/9461338168/job/26061871952?pr=16791

<img width="1020" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/dd3b5daa-3ccc-46a8-b09c-bbf03db8be07">

log: [Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports (2).zip](https://github.com/user-attachments/files/15784210/Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64.LAUNCH.PROXY.-reports.2.zip)

### Steps to Reproduce

```Markdown
trigger ci test.
```

**Comment by sukki37** [comment]
maybe dup with #16801

**Comment by Ariznawlll** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/9477806202/job/26113018257?pr=16811

**Comment by daviszhen** [comment]
与https://github.com/matrixorigin/matrixone/issues/16841 是同一个原因

**Comment by Ariznawlll** [comment]
没再出现了。
