### ISSUE TITLE
[Bug]: When using load data inline to import data, errors may occur if there are semicolons in the data

### ISSUE THREAD

**Issue by gaoy121** [matrixorigin/matrixone#16790]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.2.0

### Commit ID

5522522

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: Centos7
- Others:
```

### Actual Behavior

执行如下load data 语句报错（数据部分 Shanxi;XiAn 带分号）：
```sql
load data inline format='csv', data=$XXX$
zhangsan,26,Shanxi;XiAn $XXX$
into table user
fields terminated by ','
lines terminated by '\r\n'
(name,age,city)
```
报错信息如下：
![image](https://github.com/matrixorigin/matrixone/assets/55279192/7e461434-4912-43c9-844d-df036b64fb81)

### Steps to Reproduce

```Markdown
1.创建数据库
create database test;

2.创建数据表
use test;

CREATE TABLE `user` (
`name` VARCHAR(255) DEFAULT null,
`age` INT DEFAULT null,
`city` VARCHAR(255) DEFAULT null
)

3.执行load data语句
load data inline format='csv', data=$XXX$
zhangsan,26,Shanxi;XiAn $XXX$
into table user
fields terminated by ','
lines terminated by '\r\n'
(name,age,city)
```

**Comment by aronchanisme** [comment]
Solution: consider pre-processing the data by adding `enclosed character`(like `"` by default, as illustrated [here](https://docs.matrixorigin.cn/1.2.0/MatrixOne/Reference/Limitations/load-data-support/))
Currently stuck by this issue: https://github.com/matrixorigin/matrixone/issues/16794

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
处理中移物联的insert pprof

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not working ont it

**Comment by huby2358** [comment]
<img width="732" alt="image" src="https://github.com/user-attachments/assets/c08c66de-cfae-40d0-bbbd-b4401d16311b">

**Comment by huby2358** [comment]
<img width="610" alt="企业微信截图_f783f079-4170-45d8-9a95-b7cc45f2c4ac" src="https://github.com/user-attachments/assets/9f9e51ef-2783-47af-bbcc-837d25d83a1f">

**Comment by huby2358** [comment]
如上面截图所示，回退到issue的commit，按照issue中的步骤，是可以成功插入的，结果也是符合预期的，这种语法错误应该是必现的，怀疑是不是当时使用错误导致报错。

**Comment by aronchanisme** [comment]
请用linux的环境复现（最新main和1.2-dev均能复现）
szpc
<img width="1350" alt="企业微信截图_b00c9add-1e37-4de9-af4f-83cb348010d3" src="https://github.com/user-attachments/assets/b609358f-f9fc-4c47-9858-ebe5e2d3dd29">

129
<img width="905" alt="企业微信截图_3fd816d8-2198-4400-af66-bb3058db9b8e" src="https://github.com/user-attachments/assets/1cc79fbc-3ec3-4249-bf21-c31569efe5ab">

aron开发机
<img width="878" alt="企业微信截图_66a44f88-0b0d-4ae8-960e-9f9d70e3235c" src="https://github.com/user-attachments/assets/57a35836-6992-4033-bc10-9f2b2b4763bc">

**Comment by huby2358** [comment]
这个issue报错原因就是由于mysql客户端用分号作为切割，issue里面的load，会当成两条sql发到服务端，所以报语法错误。今天在8.0和8.3的mysql客户端都试了，8.3的客户端发到服务端的是一条sql，没有做切割（所以load成功，如我上面贴的load成功的图就是在8.3的客户端测试的。所以解决这个问题，建议升级到8.3看看

**Comment by huby2358** [comment]
@gaoy121用8.3.0的客户端试了，满足要求，issue关了

**Comment by aronchanisme** [comment]
closing it
