### ISSUE TITLE
[Bug]: the `colExpr.Col.ColPos` pushed down to block reader is unset

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#16807]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

ae68d55047f1313a05a396d17d4a28cf903980ad

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

see repro

### Expected Behavior

see repro

### Steps to Reproduce

```Markdown
step to repro:

反复执行下面的 SQL，该问题非必现。

create database if not exists test;
use test;
DROP TABLE IF EXISTS `t_material_board_middle`;
CREATE TABLE `t_material_board_middle` (
  `reel_id` varchar(50)   NOT NULL,
  `bar_code` varchar(255)   NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)  
)     COMMENT='唯一码单板绑定详情';

source /Users/ghs-mo/Downloads/etao_001_13507.sql;
```

[etao_001_13507.sql.tar.gz](https://github.com/user-attachments/files/15786417/etao_001_13507.sql.tar.gz)

branch: `1.2-dev`
commit id: `ae68d55047f1313a05a396d17d4a28cf903980ad`

related issue: https://github.com/matrixorigin/MO-Cloud/issues/3461

bug case :

<img width="725" alt="image" src="https://github.com/matrixorigin/MO-Cloud/assets/26336316/dadb8b16-6dfa-4761-b5e0-4808f073d609">

|

normal case:
<img width="763" alt="image" src="https://github.com/matrixorigin/MO-Cloud/assets/26336316/3f7630f8-8a8a-4020-8661-998e636afc01">
```


### Additional information

_No response_

**Comment by aunjgr** [comment]
on leave

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
现在还能重现吗？

**Comment by gouhongshen** [comment]
没有再出现过了
