### ISSUE TITLE
MatrixOne distributed deployment documentation

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#1680]
**Is your feature request related to a problem? Please describe.**

The MatrixOne 0.2.0 version documentation contains the distributed settings, but a lot of concepts and background information are missing. This creates difficulty in understanding.

**Describe the feature you'd like**

The MatrixOne user documentation should describe how our distributed setting works, architecture workflow, the related concepts, modules and technical terms. 

**Describe alternatives you've considered**

**Additional context**

**Comment by dengn** [comment]
MatrixCube Documentation Added.
