### ISSUE TITLE
[Bug]: `save_query_result` is not set for new account

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#16803]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.0-6391c3626-2024-06-09

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Create a new instance in cloud dev
- Check the query result config
```
mysql> select @@save_query_result;
+---------------------+
| @@save_query_result |
+---------------------+
| 0                   |
+---------------------+
1 row in set (0.04 sec)
```
- Check the config in the old instance that was created on 05.29:
```
mysql> select @@save_query_result;
+---------------------+
| @@save_query_result |
+---------------------+
| 1                   |
+---------------------+
1 row in set (0.03 sec)
```
- Check the config of CN:
```
[cn.frontend]
disable-select-into = true
lengthOfQueryPrinted = 10000
proxy-enabled = true
queryResultTimeout = 72
saveQueryResult = "on"
```

### Expected Behavior

`save_query_result` is enabled for newly created accounts

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud  dev env

**Comment by ck89119** [comment]
经讨论，恢复从toml配置文件读取系统变量的入口，修改中

**Comment by ck89119** [comment]
1.2-dev分支已修复，main分支因为bvt的问题还没合进去

**Comment by ck89119** [comment]
main分支已merge

**Comment by heni02** [comment]
confirm，closed
1.2-dev  commit:147c490d1089506aea6e0cfdee634f001da2d666
1. toml配置后sys和普通租户查询save_query_result的值是一致的，符合预期
toml配置：
<img width="591" alt="企业微信截图_033a7a72-53b4-4b6e-a6e8-474387aa1e13" src="https://github.com/matrixorigin/matrixone/assets/113406637/016524c3-f1b3-4d50-aa01-223165efbca6">
sys租户：
<img width="840" alt="企业微信截图_65cd607f-7bf5-43d7-b401-25b73019901f" src="https://github.com/matrixorigin/matrixone/assets/113406637/366bf248-56f6-46d5-b59d-27313c05b220">

普通租户：
<img width="851" alt="企业微信截图_f6f632b5-f36d-455e-8543-cf327e90f33a" src="https://github.com/matrixorigin/matrixone/assets/113406637/d365cdf4-ac12-46bd-b28b-59604c438fd7">

2. toml配置后普通租户set global@@save_query_result=off，测试符合预期
租户ac1:
mysql> set global save_query_result=off;
Query OK, 0 rows affected (0.03 sec)
mysql> select @@save_query_result;
+---------------------+
| @@save_query_result |
+---------------------+
| 1                   |
+---------------------+
1 row in set (0.01 sec)
mysql> select @@global.save_query_result;
+---------------------+
| @@save_query_result |
+---------------------+
| 0                   |
+---------------------+
1 row in set (0.00 sec)
新开session ac1验证：
mysql> select @@save_query_result;
+---------------------+
| @@save_query_result |
+---------------------+
| 0                   |
+---------------------+
1 row in set (0.00 sec)

sys租户：
![Uploading 企业微信截图_769ae43c-6750-4760-9d8c-365738f0275b.png…]()
