### ISSUE TITLE
Support round() function

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#1682]
**Is your feature request related to a problem? Please describe.**
The round() function is a common system function in database systems. 

**Describe the feature you'd like**
The ROUND() function rounds a number to a specified number of decimal places.

ROUND(number, decimals)
Example: Round the number to 2 decimal places:

SELECT ROUND(135.375, 2); result: 135.38

**Describe alternatives you've considered**
None.

**Comment by yingfeng** [comment]
duplicate with #1566
