### ISSUE TITLE
[Bug]: ut 'TestSerial_SingleAggFuncExecSerial' failed in ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#16825]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

rmTag16710

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/matrixone/actions/runs/9477806202/job/26114610796?pr=16811

<img width="1241" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/7fa6849d-b9e5-44d5-84fe-4eafc0bf4e53">

log: it is too large, please contact me.

### Steps to Reproduce

```Markdown
trigger ci test.
```

**Comment by ck89119** [comment]
TestSerial_CountColumnAggFuncExec, maybe the same problem, job: https://github.com/matrixorigin/matrixone/actions/runs/9479604077/job/26118517803?pr=16808
<img width="1604" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4971300/3cb351f1-102e-44fe-a863-f4d14605f534">

**Comment by daviszhen** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/60595215/b5c8cd99-bf91-43c5-a939-692a7d3e3e67)

https://github.com/matrixorigin/matrixone/actions/runs/9478015578/job/26113630937?pr=16798

**Comment by XuPeng-SH** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9481967914/job/26133125536?pr=16822

**Comment by XuPeng-SH** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9480936740/job/26122674694?pr=16772

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9481880757/job/26129514340?pr=16798

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/pull/15733

在该pr合入后开始出现问题。

**Comment by m-schen** [comment]
已修复。可在main分支进行验证。

**Comment by Ariznawlll** [comment]
观察中.

**Comment by Ariznawlll** [comment]
没再出现了.先关掉
