### ISSUE TITLE
[Bug]: `kill query $connection_id` returns ok but the query is not killed

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#16824]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.0-6391c3626-2024-06-09

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Create a new instance in cloud dev
- Load the tpch sample data
- login session 1 with MySQL cli, get the connection ID 1
  - use mo_sample_data_tpch_sf10;
  - select * from lineitem
- login session 2 with MySQL cli
  - kill query $connection_id_1, the kill SQL succeeded, but the query was not killed
```
mysql> kill query 73366871;
Query OK, 0 rows affected (0.03 sec)
```
```
mysql> select statement,status,duration from system.statement_info where statement_id = '01900b56-3885-77b1-a991-93a5ca137692' and request_at >= '2024-06-12 07:20:00';
+------------------------+---------+--------------+
| statement              | status  | duration     |
+------------------------+---------+--------------+
| select * from lineitem | Success | 346496750298 |
+------------------------+---------+--------------+
1 row in set (0.34 sec)
```

### Expected Behavior

Query is killed or error returned if it's not killed

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by daviszhen** [comment]
来不及

**Comment by aressu1985** [comment]
DELAY 1.2.2版本

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
无投入

**Comment by daviszhen** [comment]
这个要求做不到：" error returned if it's not killed"

**Comment by daviszhen** [comment]
1，issue中的例子执行时间太短了。0.34秒结束，拼手速。如果mo在执行完sql,才受到kill，实际没作用。
2，受到kill与执行sql是一种异步行为。
3，如果是34s,或者更长的时间。kill不掉，要case by case看了。大部分的sql都能kill掉。

**Comment by daviszhen** [comment]
之前一直以为pipeline的ctx 传第 有中断，导致下面的RUN的ctx 没有被cancel

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
**commit_id: a0f75f627c656d888d3af43644af6d6531c6c013**

<img width="1392" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/882d506d-8db2-47af-b6ae-b13ea589fd24">

**Comment by DanielZhangQD** [comment]
> **commit_id: [a0f75f6](https://github.com/matrixorigin/matrixone/commit/a0f75f627c656d888d3af43644af6d6531c6c013)**
> 
> <img alt="image" width="1392" src="https://private-user-images.githubusercontent.com/108530700/346497496-882d506d-8db2-47af-b6ae-b13ea589fd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzQ1NjUsIm5iZiI6MTcyMDQzNDI2NSwicGF0aCI6Ii8xMDg1MzA3MDAvMzQ2NDk3NDk2LTg4MmQ1MDZkLThkYjItNDdhZi1iNmFlLWIxM2VhNTg5ZmQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMDI0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzgyMTJlMGMyNTlkOWVkZTg0YzVkZmNhOTUxZDY0ZjJjZWE1YTRlNTNhZTMzYTExYzJhYWUwYmQwNmY5YTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETIQsheVVnV41OVq2otFgO0snpR2NnkUAjke3YhubQ4">
> 测试通过。

这里要确认 statement_info 里面的 状态，确认 SQL 是真的被 kill 了还是执行成功了。

**Comment by Ariznawlll** [comment]
> > **commit_id: [a0f75f6](https://github.com/matrixorigin/matrixone/commit/a0f75f627c656d888d3af43644af6d6531c6c013)**
> > <img alt="image" width="1392" src="https://private-user-images.githubusercontent.com/108530700/346497496-882d506d-8db2-47af-b6ae-b13ea589fd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzQ1NjUsIm5iZiI6MTcyMDQzNDI2NSwicGF0aCI6Ii8xMDg1MzA3MDAvMzQ2NDk3NDk2LTg4MmQ1MDZkLThkYjItNDdhZi1iNmFlLWIxM2VhNTg5ZmQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMDI0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzgyMTJlMGMyNTlkOWVkZTg0YzVkZmNhOTUxZDY0ZjJjZWE1YTRlNTNhZTMzYTExYzJhYWUwYmQwNmY5YTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETIQsheVVnV41OVq2otFgO0snpR2NnkUAjke3YhubQ4">
> > 测试通过。
> 
> 这里要确认 statement_info 里面的 状态，确认 SQL 是真的被 kill 了还是执行成功了。

<img width="760" alt="企业微信截图_a6a4c797-1133-4f41-9d41-e06d3938037d" src="https://github.com/matrixorigin/matrixone/assets/108530700/cd4f0255-8875-4d78-9df5-8a8a856bec7c">

以上kill成功了，但是statement_info表中关于这条sql的信息展示为success.

**Comment by Ariznawlll** [comment]
分布式环境kill后没起作用：
**commit：ea4a155**
测试步骤：
1. 首先查看connection_id();
2. 执行sql： select count(distinct(col10)) from big_data_test.table_basic_for_load_100M;（这条sql正常执行需要44s）；
3. 执行sql期间在另一个session里kill connection，观察步骤2中的sql是否会中断执行

<img width="1122" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d159f139-5f80-48b3-b14e-090a2464a5c8">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22nTt%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240708%5C%22%7D%20%7C%3D%20%60select%20count%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

分布式环境测试不通过



总结：
1. 单机环境，kill成功，但是statement_info表中的状态睡success；
2. 分布式环境，kill不成功。

**Comment by xzxiong** [comment]
> > > **commit_id: [a0f75f6](https://github.com/matrixorigin/matrixone/commit/a0f75f627c656d888d3af43644af6d6531c6c013)**
> > > <img alt="image" width="1392" src="https://private-user-images.githubusercontent.com/108530700/346497496-882d506d-8db2-47af-b6ae-b13ea589fd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzQ1NjUsIm5iZiI6MTcyMDQzNDI2NSwicGF0aCI6Ii8xMDg1MzA3MDAvMzQ2NDk3NDk2LTg4MmQ1MDZkLThkYjItNDdhZi1iNmFlLWIxM2VhNTg5ZmQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMDI0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzgyMTJlMGMyNTlkOWVkZTg0YzVkZmNhOTUxZDY0ZjJjZWE1YTRlNTNhZTMzYTExYzJhYWUwYmQwNmY5YTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETIQsheVVnV41OVq2otFgO0snpR2NnkUAjke3YhubQ4">
> > > 测试通过。
> > 
> > 
> > 这里要确认 statement_info 里面的 状态，确认 SQL 是真的被 kill 了还是执行成功了。
> 
> <img alt="企业微信截图_a6a4c797-1133-4f41-9d41-e06d3938037d" width="760" src="https://private-user-images.githubusercontent.com/108530700/346538522-cd4f0255-8875-4d78-9df5-8a8a856bec7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTAxMDEsIm5iZiI6MTcyMDQ4OTgwMSwicGF0aCI6Ii8xMDg1MzA3MDAvMzQ2NTM4NTIyLWNkNGYwMjU1LTg4NzUtNGQ3OC05ZGY1LThhOGE4NTZiZWM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwMTUwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODI4ZTU1ZTQwNDY3NWNmODZjZGU0MjEyNTNmNDQxNzc2ZTZiYjAwZmVhM2MyYTY3OTVkZTg3YTZhN2FiY2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qb0nThNe5nqUujkiRF6U3O3T20ShbfKhDkuzm7mef2s">
> 以上kill成功了，但是statement_info表中关于这条sql的信息展示为success.已经麻烦泽雄哥帮忙看了
> 
> 单机环境测试不通过。

补充一下：statement_info的 status主要依赖 frontend提供的执行结果，frontend的执行链路挺复杂的。
一行错误日志 "query trace status" ，可以直观区分出哪边出问题：1）原query的执行status结果不对；2）statement_info记录的不对。
后续验证时，可关注该日志。 @Ariznawlll

**Comment by aressu1985** [comment]
回归不通过，非重要问题，不在1.2.2解决了，DELAY到 1.3.0

**Comment by volgariver6** [comment]
多个proxy的问题，proxy之间没有共享数据，需要到cn上查数据再做转发

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
**1.2-dev 
commit：699e706837e648cbbb43a2177e712e2b0569c4a5**
**单机测试步骤：**

1. 查看connection_id();
2. 执行sql： select count(distinct(col10)) from big_data_test.table_basic_for_load_100M;（这条sql正常执行需要44s）；
3. 执行sql期间在另一个session里kill query + connection，观察步骤2中的sql是否会中断执行；
4. 确认 statement_info 里面的状态，确认 SQL 是真的被 kill 了还是执行成功了。
<img width="1385" alt="image" src="https://github.com/user-attachments/assets/468a4cb5-e871-454d-b381-91e4046930e7">




**单机环境测试结论：kill query + connection_id之后，sql会中断执行，并且查看statement_info里面sql的状态为failed。测试通过。**


**分布式测试步骤：**
1. 查看connection_id();
2. 执行sql： select count(distinct(col10)) from big_data_test.table_basic_for_load_100M;（这条sql正常执行需要44s）；
3. 执行sql期间在另一个session里kill query + connection，观察步骤2中的sql是否会中断执行；
4. 确认 statement_info 里面的状态，确认 SQL 是真的被 kill 了还是执行成功了。

**Comment by xzxiong** [comment]
@volgariver6 请问下proxy 如果发生了链接迁移，再kill 会有问题么？

**Comment by volgariver6** [comment]
> @volgariver6 请问下proxy 如果发生了链接迁移，再kill 会有问题么？

不会有问题，proxy迁移连接connection id不会变化的
