### ISSUE TITLE
[Bug]: ut TestSerial_CountStarAggFuncExec failed.

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16835]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0611-add-error-to-alloc

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/00ee9d30-a469-45bd-9685-e5597ebac894)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/e9bd1bce-e485-40f3-9212-cbbee4fefa73)

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9478015578/job/26121160359?pr=16798
```

**Comment by XuPeng-SH** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/9481967914/job/26133125536?pr=16822

**Comment by m-schen** [comment]
已修复。可在main分支进行验证。
