### ISSUE TITLE
[Bug]: CN panic: nil pointer in CalculateOutTrafficBytes

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#16844]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

d807366b2

### Other Environment Information

```Markdown
MOC Dev
```

### Actual Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xab0 pc=0x355f39f]

goroutine 619996 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).CalculateOutTrafficBytes(0xc0dba6e800, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_protocol.go:577 +0x3f
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus({0x524b1b8, 0xc0d2c7e0c0}, {0x53266d0, 0xc0dd48ec08}, {0xc0ecfb5144?, 0xc0dd48ec08?}, 0x1, {0x520b600, 0x785b470})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:495 +0x1a2
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus({0x524b1b8, 0xc0d2c7e0c0}, {0x53266d0, 0xc0dd48ec08}, {0x526d560, 0xc0df784030}, 0x1, {0x520b600, 0x785b470})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:487 +0xf3
github.com/matrixorigin/matrixone/pkg/frontend.rollbackTxnFunc({0x53266d0, 0xc0dd48ec08}, {0x520b600, 0x785b470}, 0xc0f0f05e60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:70 +0x332
github.com/matrixorigin/matrixone/pkg/frontend.finishTxnFunc({0x53266d0, 0xc0dd48ec08}, {0x520b600, 0x785b470}, 0xc0f0f05e60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:128 +0x3ee
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2249 +0x2f
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x53266d0, 0xc0dd48ec08}, 0xc0f0f05e60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2275 +0x5d2
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x53266d0, 0xc0dd48ec08}, 0xc0f0f05e60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2222 +0x10c
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc0dd48ec08, 0xc0f0f05e60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2187 +0x3f6
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc0dd48ec08, 0xc0f0f05e60, 0xc113c3ec30)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2754 +0x1e3a
github.com/matrixorigin/matrixone/pkg/frontend.(*dbMigration).Migrate(0xc133098d80, {0x524b1b8, 0xc0ac12ff50}, 0xc0dd48ec08)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1523 +0x167
github.com/matrixorigin/matrixone/pkg/frontend.Migrate(0xc0dd48ec08, 0xc113c3eaa0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1585 +0x4b5
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:453 +0x87
sync.(*Once).doSlow(0x3fd9940?, 0xc08f887f20?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).migrateConnectionTo(0x0?, {0x0?, 0x0?}, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:446 +0x5b
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).MigrateConnectionTo(0x4181a5?, {0x524b1b8, 0xc0ac12e120}, 0xc113c3eaa0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:574 +0x45
github.com/matrixorigin/matrixone/pkg/cnservice.(*service).handleMigrateConnTo(0x7aa75f3?, {0x524b1b8?, 0xc0ac12e120?}, 0xc0b98f5c80, 0xc02acd11e0)
	/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_query.go:419 +0x5a
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handleFuncCtx[...]).call(0x5221ba0?, {0x524b1b8, 0xc0ac12e120?}, 0x4181a5?, 0xc02acd11e0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:65 +0x4c
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:196 +0x2b2
github.com/matrixorigin/matrixone/pkg/common/morpc.(*handler[...]).onMessage(0x53005c0, {0x524b1b8, 0xc0ac12e120?}, {{0x524b1b8, 0xc0ac12e120}, 0xc0967b24e0, {0x5274118, 0xc0b98f5c80}, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/handler.go:205 +0x550
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0095062c0, {0x52c66a0, 0xc101e6f500}, {0x45476c0, 0xc113c3eaf0}, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:260 +0xc3e
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc009506370, {0x52c66a0, 0xc101e6f500})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:393 +0x390
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:356 +0x94
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 501
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:348 +0x3fa
```

### Expected Behavior

CN should not panic

### Steps to Reproduce

```Markdown
see: https://grafana.cn-dev.matrixone.tech/goto/-Mmvcd8IR?orgId=1
```

**Comment by xzxiong** [comment]
lead: 
- pkg/frontend/mysql_cmd_executor.go:2275 , return err 触发 defer 调用。
![image](https://github.com/matrixorigin/matrixone/assets/3927687/5b141405-a0de-42a7-93d5-2745b023c359)

**Comment by xzxiong** [comment]
正常创建的 session 的protoal 都是默认设置的，见：`pkg/frontend/routine_manager.go:Created`
![image](https://github.com/matrixorigin/matrixone/assets/3927687/601ea1c4-493a-4c26-9864-b1d7c7902ea8)

**Comment by xzxiong** [comment]
@daviszhen  ptal, 2 个问题：
1. 最大的概率就是在 Session还在执行期间，有另一个goroutine 调用了 Close 接口
2. 这里的 panic 没有被捕获。

**Comment by xzxiong** [comment]
@volgariver6 ptal, 是不是存在 Migrate 过程中，断开conn 的情况？

**Comment by xzxiong** [comment]
routinue.go:handleRequest 是可以断开连接的，如图
![image](https://github.com/matrixorigin/matrixone/assets/3927687/ff56861d-5221-49ca-8a67-92142973e963)

log 上也有相关的日志，需要确认这是不是同一个session, [link](https://grafana.cn-dev.matrixone.tech/goto/TtWd8dUIR?orgId=1)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/27913c85-4dd6-400a-a116-e79e2904b78b)

**Comment by xzxiong** [comment]
> routinue.go:handleRequest 是可以断开连接的，如图 ![image](https://private-user-images.githubusercontent.com/3927687/339219759-ff56861d-5221-49ca-8a67-92142973e963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTU3NzYsIm5iZiI6MTcxODI1NTQ3NiwicGF0aCI6Ii8zOTI3Njg3LzMzOTIxOTc1OS1mZjU2ODYxZC01MjIxLTQ5Y2EtOGE2Ny05MjE0Mjk3M2U5NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDUxMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZjOWM4ZGU0MmM3OGU0MmJhMDFiMzUzOGNhODdmM2RiZjIyZTU0OTA2ODI1NzMzNjBiYzEzOTllOTA1MzYyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hfbKyCFY1EpJwYz9w5R15oRVq1zjzYZ8yD2Cxf-jViM)
> 
> log 上也有相关的日志，需要确认这是不是同一个session, [link](https://grafana.cn-dev.matrixone.tech/goto/TtWd8dUIR?orgId=1) ![image](https://private-user-images.githubusercontent.com/3927687/339219673-27913c85-4dd6-400a-a116-e79e2904b78b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTU3NzYsIm5iZiI6MTcxODI1NTQ3NiwicGF0aCI6Ii8zOTI3Njg3LzMzOTIxOTY3My0yNzkxM2M4NS00ZGQ2LTQwMGEtYTExNi1lNzllMjkwNGI3OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDUxMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhNWFjMmI2OWM4ZGNhNmNjNDEwYjA0ODM5ZjA0ZjExZDJjZDUzMGMxYWMwNjQ2NWQ0ZTM3ZmM1NDUxOTk1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kXN98GQCQ7tyBtXk3M8BPweBGOf185Hmil8q891hVUA)

没关系，Migrate 完成前，不会处理用户的请求。

**Comment by xzxiong** [comment]
goroutine 619996 相关日志.
[link](https://grafana.cn-dev.matrixone.tech/goto/SxKnCO8IR?orgId=1)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/37d6881d-37a1-4d0a-8b46-360d555f70ca)

**Comment by xzxiong** [comment]
> goroutine 619996 相关日志. [link](https://grafana.cn-dev.matrixone.tech/goto/SxKnCO8IR?orgId=1) ![image](https://private-user-images.githubusercontent.com/3927687/339239226-37d6881d-37a1-4d0a-8b46-360d555f70ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjA4MDcsIm5iZiI6MTcxODI2MDUwNywicGF0aCI6Ii8zOTI3Njg3LzMzOTIzOTIyNi0zN2Q2ODgxZC0zN2ExLTRkMGEtOGI0Ni0zNjBkNTU1ZjcwY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDYzNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUyOTc1YWE2OTQyZWZiNGRlNzBiODY0MDE5NGEwYTdiZWFiZDY0YzVjNWFjNzc0N2QwOTAxNmFiZjkxMjc4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iWT3z8szI0aXGqeTPK55qSZKZFnctgU1QSXQ4izk1Lc)

waiter.wait(ctx) error 返回如果错误，有两种情况：1）ctx timeout or canceled； 2）直接报错 ”waiter is paused“
- 目前没有找到 ”waiter is paused“的报错信息，推断为 ctx canceled。

![image](https://github.com/matrixorigin/matrixone/assets/3927687/b94e2a62-ab02-4513-b7cf-033ab2215d4f)

**Comment by xzxiong** [comment]
txnHandler ctx 源头来自 routinue.getCancelRoutineCtx()
![image](https://github.com/matrixorigin/matrixone/assets/3927687/9daf9897-4d8a-4ee5-bd0f-b9830964e502)

**Comment by xzxiong** [comment]
总结一下，log [link](https://grafana.cn-dev.matrixone.tech/goto/qgEgeOUSR?orgId=1)
- 没有 Shutdown 的日志
- 没有 kill connection的日志
- Migrate 没有做完，但无法create 新的 txn

**Comment by xzxiong** [comment]
与 @daviszhen 对齐了，目前可能有异步 close protocal 的操作。
这里逻辑比较复杂，目前针对出错的地方进行修复；添加异常close 的日志，并后续添加相关的日志告警。

**Comment by aressu1985** [comment]
fixed
