### ISSUE TITLE
[Bug]: CI UT TestEmptyNullFlag fail

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#16845]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="875" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/59bb5b2f-efbb-4a8c-90d7-50d6534f6ef1">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9481967914/job/26133125536?pr=16822
```

**Comment by aunjgr** [comment]
@m-schen 麻烦先看一下

**Comment by m-schen** [comment]
这个应该和vector结构复用有关。

**Comment by m-schen** [comment]
哦哦。
这个issue已经解决了的，是之前加入vector指针的全局复用后，aggexec包下有个vector会调用两次free.

ci上的ut是以包为单位跑的，会有race。已经修复了。

相关pr: 
https://github.com/matrixorigin/matrixone/pull/16870

@XuPeng-SH 该issue可关闭。
