### ISSUE TITLE
[Bug]: Multi-CN BVT panic

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#16841]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

0611-add-rows-to-queryresult

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/7c5ea0eb-abd7-4d26-a089-aaeb843fb1c5)

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://productionresultssa14.blob.core.windows.net/actions-results/99088368-203c-40c6-ad28-22a7a2c43cc6/workflow-job-run-b96e6d98-285a-5faf-4bff-556c54832b6f/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-06-12T13%3A07%3A37Z&sig=Z%2BEa5gS6oSpgAm3c%2F%2FmkwMwQD2bAlbyAZfZ%2BtTqBvFU%3D&ske=2024-06-12T22%3A46%3A19Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-06-12T10%3A46%3A19Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-06-12T12%3A57%3A32Z&sv=2023-11-03
```

**Comment by ouyuanning** [comment]
复现方式：
1、用这个配置启动  "args": ["-launch", "./etc/launch-dynamic-with-proxy/launch.toml", "-with-proxy"]

2、先跑一次这个目录的bvt :  query_result   第一次不会有问题
3、再跑一次，必然hung，出错位置也跟那个地方

表面上的原因是这个时候。 s.DataSource.R 的值是nil，

**Comment by ouyuanning** [comment]
二分来看是 d9f4139de1de748d33d49bccc9c8c969a9bd3ea9 这个commit 引入的。但是看不太出来原因

**Comment by badboynt1** [comment]
fixed
