### ISSUE TITLE
[Tech Request]: find out cache miss blocks in tpcc long running test

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#16855]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
explain analyze SELECT s_w_id, s_i_id, s_quantity FROM bmsql_stock WHERE s_w_id = 3 AND s_quantity < 10 AND s_i_id IN ( SELECT ol_i_id FROM bmsql_district JOIN bmsql_order_line ON ol_w_id = d_w_id AND ol_d_id = d_id AND ol_o_id >= d_next_o_id - 20 AND ol_o_id < d_next_o_id WHERE d_w_id = 3 AND d_id = 7);

这条sql在tpcc测试里，有可能会触发60秒超时。
需要找出一共访问了哪些block，哪些是cache 命中的，哪些是cache miss的。
```

**Comment by reusee** [comment]
这是因为内存缓存放不下所有数据，导致不停置换
跑得越久，delta location对象越多，所以内存缓存放不下
后续需要tae team做delta loc的优化
