### ISSUE TITLE
[Bug]: UT failed on main branch involving vector reuse

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#16864]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f890fdbdd4710e209b6a6a039bfea5b621093c9a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

--- FAIL: TestSerial_ApproxCountVarAggFuncExec (0.00s)
panic: internal error: invalid free, mp header corruption [recovered]
        panic: internal error: invalid free, mp header corruption

TestSerial_ApproxCountVarAggFuncExec always fails, and TestGroupExec fails occasionally.

### Steps to Reproduce

```Markdown
run `go test` under `pkg/sql/colexec/aggexec`
```

### Additional information

It always fails on my local machine. And several PRs fail on this case. The earliest affected commit is f890fdbdd4710e209b6a6a039bfea5b621093c9a (#15733).

**Comment by aunjgr** [comment]
promote to s-1 since it blocks other PRs

**Comment by ouyuanning** [comment]
#16870
