### ISSUE TITLE
[Bug]: NULL is not supported in the IN operator

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1686]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4caf3d4f0015cada13ddbaa9c715e11c36b0dece
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from t2 where b in (NULL);
ERROR 1105 (HY000): unknown error:[42000]unsupport value: unknown

**Comment by broccoliSpicy** [comment]
In sql,  the comparison of the i column with Null always returns Unknown, even for those rows where i is Null. 
we don't support comparison with NULL
