### ISSUE TITLE
[Bug]: result in the IN is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1687]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4caf3d4f0015cada13ddbaa9c715e11c36b0dece
- Hardware parameters:
- OS type:
- Others:

select * from t2;
+------+------+--------+------------+---------------------+
| a    | b    | c      | d          | e                   |
+------+------+--------+------------+---------------------+
|    1 | a    | 1.0010 | 2022-02-08 | 2022-02-08 12:00:00 |
|    2 | b    | 2.0010 | 2022-02-09 | 2022-02-09 12:00:00 |
|    1 | c    | 3.0010 | 2022-02-10 | 2022-02-10 12:00:00 |
|    4 | d    | 4.0010 | 2022-02-11 | 2022-02-11 12:00:00 |
+------+------+--------+------------+---------------------+
```

### Actual Behavior

 select * from t2 where a  in (2.001,2.001);
+------+------+--------+------------+---------------------+
| a    | b    | c      | d          | e                   |
+------+------+--------+------------+---------------------+
|    2 | b    | 2.0010 | 2022-02-09 | 2022-02-09 12:00:00 |
+------+------+--------+------------+---------------------+
1 row in set (0.01 sec)

### Expected Behavior

Empty set (0.01 sec)

**Comment by broccoliSpicy** [comment]
PR#1689 fixed this issue.
