### ISSUE TITLE
[Bug]: lots of error "txn is stale: timestamp is too small" in tpch longruning test during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16883]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

d807366

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

There were lots of error "txn is stale: timestamp is too small" in tpch longruning test during stability test on distributed mode.
<img width="1347" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/0bb5c15f-8911-4e66-99f0-9817fa0f3fa0">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22hJL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-d807366-20240612223759%5C%22%7D%20%7C%3D%20%60txn%20is%20stale:%20timestamp%20is%20too%20small%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718264004658%22,%22to%22:%221718284882931%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by aressu1985** [comment]
DELAY 到后续版本持续观察

**Comment by XuPeng-SH** [comment]
再没有出现，先关闭吧@aressu1985
