### ISSUE TITLE
[Bug]: lots of error response " internal error: panic runtime error: slice bounds out of range [5927556:5925133]:" in sysbench mixed cased during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16884]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

d807366

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

 there are lots of error response " internal error: panic runtime error: slice bounds out of range [5927556:5925133]:" in sysbench mixed cased during stability test on distributed mode

<img width="1367" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ce0e37b7-73a5-43d6-a1d2-1ca068809bd9">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22hJL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-d807366-20240612223759%5C%22%7D%20%7C%3D%20%60slice%20bounds%20out%20of%20range%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718242973718%22,%22to%22:%221718246821491%22%7D%7D%7D&schemaVersion=1&orgId=1

sysbench mixed case sql:
session1:
select c from sbtest{tbx} where id = {id};

session2: 
delete from sbtest{tbx} where id = {id};
insert into sbtest{tbx} values({id},4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');

session3:
UPDATE sbtest{tbx} SET k=k+100 WHERE id = {id};

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by LeftHandCold** [comment]
出现这个问题的情况只有一个cn，而且读的文件是一个delete文件，正常dn也会读这个文件，并没有出现panic。这个cn有频繁的写s3错误，并且

**Comment by LeftHandCold** [comment]
<img width="1557" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/14936452-909b-4721-8558-bffde7cbdd1d">

**Comment by LeftHandCold** [comment]
[filelist.log](https://github.com/user-attachments/files/15823540/filelist.log)
查看当前cn diskcache内容，最早的文件也是下午2点以后了

**Comment by aressu1985** [comment]
需要进一步定位，在写cache成功后，写S3失败，之后的处理逻辑是不是有问题

**Comment by LeftHandCold** [comment]
[system1.log](https://github.com/user-attachments/files/15835095/system1.log)
这个case是系统异常引起的，出现的时候09:59正好宿主机内核出现了filemap_get_page异常，导致pagecache异常，和timer_interrupt。并且持续到10:17分第一次soft lockup。
<img width="1315" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/b25695cc-c017-4045-baf5-c3cbe9a0e5fe">
<img width="920" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/c5a16d5d-b8ef-47af-9ee9-ddcdd4de7f49">
