### ISSUE TITLE
[Bug]: mo hung (all the txn has been timeout )during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16886]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

d807366

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

During stability test on distributed mode, the mo suddenly hung at a poit:
[tpch]
<img width="870" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/cb7ebc6a-54e5-48a5-8a5f-361ef9c5895d">
[tpch.log](https://github.com/user-attachments/files/15821957/tpch.log)

[sysbench]
<img width="1391" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e1412e67-e650-44bf-a397-8eb77cb331ce">
[sysbench_1.log](https://github.com/user-attachments/files/15821959/sysbench_1.log)

[tpcc]
<img width="1388" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/30233192-668c-4b4c-9b9a-b725daa67f02">
[benchmarksql-error.log](https://github.com/user-attachments/files/15821970/benchmarksql-error.log)

but can not find any "long running" and "leak" from mo-log.
mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22J54%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-d807366-20240612223759%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718244632000%22,%22to%22:%221718247039000%22%7D%7D%7D&schemaVersion=1&orgId=1

and there lots of the following suspicious error logs:
<img width="1354" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/60f17306-107f-46f3-9507-3501eba39a41">

but there were no cns crashed.

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
从日志和监控上看，应该是dn某个地方卡住了，导致无法产生logtail：

- WAL append metric 中断了：
https://shanghai.idc.matrixorigin.cn:30001/d/a926041f-ec90-42de-bbb5-2ac3816ba19a/logtail-metrics?orgId=1&from=1718245320000&to=1718245911449&var-interval=1m&var-namespace=mo-nightly-d807366-20240612223759&var-pod=All&viewPanel=63&editPanel=63

- logtail channel blocked：
http://localhost:3000/goto/TME_rc8Sg?orgId=1

**Comment by volgariver6** [comment]
大概率是由于操作系统 soft lockup 引起的，related issue：https://github.com/matrixorigin/matrixone/issues/16884

建议关闭该issue。
