### ISSUE TITLE
[Bug]: "lock table bind changed"  and "lock table not found on remote lock service" but no cn or dn crashed in stability test(tpcc 10-10) on distriubted mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16926]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

25995d2

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

There were some "lock table bind changed"  and "lock table not found on remote lock service" but no cn or dn crashed in stability test(tpcc 10-10) on distriubted mode.

<img width="1374" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3596cd89-c1f8-4ec5-9ed8-1d0e8d29998b">

but there were no cn or dn crashed.
<img width="733" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/8776fce7-de59-40bb-aa87-f3f3a161e474">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%60lock%20table%20bind%20changed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718500725529%22,%22to%22:%221718502110144%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by iamlinjunhong** [comment]
<img width="3129" alt="截屏2024-06-16 18 30 35" src="https://github.com/matrixorigin/matrixone/assets/49111204/9f66d7e3-efd0-4ef9-87a2-ec6ad3aa7407">
dn 和 cn 网络断开，导致 lock table change ，符合预期
