### ISSUE TITLE
BVT Failed: select count(1) > 0 exist from system_metrics.metric where collecttime > date_sub(now(), interval 5 minute) and metric_name = 'server_storage_usage';

### ISSUE THREAD

**Issue by triump2020** [matrixorigin/matrixone#16924]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

dd3b6feb2ba287c5ffc9107919f8ef4ef89ec493

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: ubuntu 20.4
- Others:
```

### Actual Behavior

![b4c2d3aa60c8245bed056d338d333f1](https://github.com/matrixorigin/matrixone/assets/63033222/684a5140-5119-45a9-8db3-7332b7073f44)

### Expected Behavior

![b4c2d3aa60c8245bed056d338d333f1](https://github.com/matrixorigin/matrixone/assets/63033222/d703e3d7-a747-4092-bd46-d51e039f8a7e)

### Steps to Reproduce

```Markdown
run BVT case : cases/log/column_metric.sql
```

**Comment by xzxiong** [comment]
@triump2020 请问是怎么启动的？

**Comment by triump2020** [comment]
单机启动:  ./mo-service  /etc/lanuch/lanuch.toml

**Comment by triump2020** [comment]
commitid : 1e35ff0a9e07cca2cb96d0de89f1634b5c626177,  can't repro ,  close it .
