### ISSUE TITLE
[Bug]: dn crashed by panic: runtime error: invalid memory address or nil pointer dereference during sysbench write cases(delete/update/write_only) in daily regression on TKE

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16925]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

25995d287c9c9f0a042a0f6272a390a4343d3706

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9528612146/job/26270932623

dn crashed by panic: runtime error: invalid memory address or nil pointer dereference during sysbench write cases(delete/update/write_only) in daily regression on TKE, and It case lots of 'contexted deadline ' errors and 'lock talbe bind changed' errors:
<img width="1381" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/935e45e1-1160-4c6d-8705-013f7e5be7db">

<img width="1360" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/88ba03d6-f075-421d-b328-e5334f8ddbf6">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%221_I%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-25995d2%5C%22%7D%20%7C%3D%20%60context%20deadline%20exceeded%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718483022574%22,%22to%22:%221718509791145%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run sysbench write cases on tke
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
