### ISSUE TITLE
[Bug]: [date 6.15]tke regression:tpcc 100w100threads reported cannot commit a orphan transaction

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16932]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

321adf27a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9528926902/job/26269202859
报错时间：2024-06-15 18:33:35
<img width="1064" alt="企业微信截图_4ea00a74-8207-4beb-9bb5-54ec67d69b9b" src="https://github.com/matrixorigin/matrixone/assets/113406637/bcd4327e-dd9f-409b-8661-94667822254e">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22JRn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240615%5C%22%7D%20%7C%3D%20%60orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718476415000%22,%22to%22:%221718476454000%22%7D%7D%7D&schemaVersion=1&orgId=1

cn内存占用30G
<img width="1414" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/cd7bba65-57e1-484a-9c6a-95260a79f971">
cpu占用10core
<img width="708" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/275f0c58-5e59-4eda-8a0a-90841c4510ae">
https://grafana.ci.matrixorigin.cn/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-nightly-regression-20240615&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki&from=1718475287154&to=1718492869176

### Steps to Reproduce

```Markdown
tke tpcc 100ware 100thread test
```

**Comment by zhangxu19830126** [comment]
不是bug
