### ISSUE TITLE
[Bug]: 1.2-dev standalone: sysbench10w write_only1000threads reported Duplicate entry and w-w error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16938]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

6cfdcaf20fb7cda1a027e1b5c0b837607d4442d7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9536425137/job/26283375736
<img width="1313" alt="企业微信截图_53a17115-6bb7-44e4-89fc-200503e559d2" src="https://github.com/matrixorigin/matrixone/assets/113406637/ff824448-f046-4b3f-bcbb-59c5c348cae7">

mo log plz contact me

### Steps to Reproduce

```Markdown
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10    prepare
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 —db-ps-mode=disable --mysql-ignore-errors=20701 oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=300 --report-interval=10     --range_selects=off --point_selects=1 run
```

**Comment by triump2020** [comment]
Dup with #16577

**Comment by triump2020** [comment]
Maybe this [PR](https://github.com/matrixorigin/matrixone/pull/16477) leads to this bug,  i' ll confirm this.

**Comment by heni02** [comment]
date 6.22 回归测试复现
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9623774223/job/26546707962
w-w报错时间：
<img width="1037" alt="企业微信截图_ce8d0cb8-6ae0-4732-80df-c3a4f8ef2c5d" src="https://github.com/matrixorigin/matrixone/assets/113406637/08b991b2-e543-41a0-b3b5-54cabef499ae">

dup报错时间：
<img width="1037" alt="企业微信截图_ce8d0cb8-6ae0-4732-80df-c3a4f8ef2c5d" src="https://github.com/matrixorigin/matrixone/assets/113406637/e66d3ee2-c7ba-40c9-a31f-5d04ec87b593">

日志太大，私发定位

**Comment by triump2020** [comment]
单机的 ww/dup 原因已定位到大致原因。

**Comment by triump2020** [comment]
需要进一步定位根本原因

**Comment by triump2020** [comment]
@heni02 [PR](https://github.com/matrixorigin/matrixone/pull/17313) had fix it .

**Comment by heni02** [comment]
需要继续观察两天回归测试

**Comment by heni02** [comment]
观察两周没有再出现 
confirm，closed
