### ISSUE TITLE
[Bug]: lots of longrunning and txn leak caused mo hung during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#16931]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

25995d2

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

there were lots of longrunning and txn leak caused mo hung during stability test on distributed mode.
[sysbench mixed case]
<img width="1386" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/5614cc2a-32dc-444e-8139-60e6956b75a5">

[tpch]
<img width="879" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/71051274-dae9-4c2f-976a-9cdd2e288f63">

[tpcc]
<img width="1399" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/de6f49e2-61fa-405f-9af9-4d8fe3b9797f">

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698836%22,%22to%22:%221718536629569%22%7D%7D%7D&schemaVersion=1&orgId=1

The first longrunning go routine：
[routine_01902096-2df0-7a67-b438-8ec4b41bfe5c.gz](https://github.com/user-attachments/files/15857604/routine_01902096-2df0-7a67-b438-8ec4b41bfe5c.gz)

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by sukki37** [comment]
```
goroutine 17384975 [select]:
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).Get(0xc0b76fa5a0)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:80 +0x194
github.com/matrixorigin/matrixone/pkg/lockservice.(*client).Send(0xc00299dc50, {0x6e568d8, 0xc43d1fbb00}, 0xc0a37c4008)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:107 +0x289
github.com/matrixorigin/matrixone/pkg/lockservice.(*remoteLockTable).lock(0xc32abc6a20, {0x6e568d8, 0xc43d1fbb00}, 0xc69edb6690, {0xc2a70f9ef0, 0x1, 0x1}, {{0x0, 0x1, 0x0, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_remote.go:91 +0x5a7
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).Lock(_, {_, _}, _, {_, _, _}, {0xc042c4eea0, 0x10, 0x10}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/service.go:180 +0xdbc
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock({0x6e568d8, 0xc43d1fbb00}, {0x6ec01d8, 0xc6a8842640}, {0x6ee2538, 0xc077d58ea0}, 0x2, 0xc029325c08, 0xc0a9eef180, {0x3d, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:468 +0xbbd
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.LockRows({0x6ec01d8, 0xc6a8842640}, 0xc029325c08, {0x6ee2538, 0xc077d58ea0}, 0x2, 0xc0a9eef180, {0x3d, 0x0, 0x0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:357 +0x485
github.com/matrixorigin/matrixone/pkg/sql/compile.lockRows({0x6ec01d8, 0xc6a8842640}, 0xc029325c08, {0x6ee2538, 0xc077d58ea0}, 0xc0a9eef180, 0x1, 0x1, 0x2712)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:3156 +0x16a
github.com/matrixorigin/matrixone/pkg/sql/compile.lockMoTable(0xc350de5ba0, {0xc0af4c3b00, 0x6}, {0xc0af4c3b07, 0x7}, 0x1)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:3275 +0x4b6
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).lockMetaTables(0xc350de5ba0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:850 +0x317
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc350de5ba0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:619 +0x7b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc350de5ba0, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:514 +0xc65
github.com/matrixorigin/matrixone/pkg/frontend.executeStatusStmt(0xc0b11b6008, 0xc38b569560)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/status_stmt.go:136 +0x11b1
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt(0xc0b11b6008, 0xc38b569560)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2537 +0x19ca
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x6efdf50, 0xc0b11b6008}, 0xc38b569560)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2401 +0x485
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x6efdf50, 0xc0b11b6008}, 0xc38b569560, {0x6ee5258, 0xc0d12a4008})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2370 +0x2e5
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace({0x6efdf50, 0xc0b11b6008}, 0xc38b569560)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2330 +0x86b
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn({0x6efdf50, 0xc0b11b6008}, 0xc38b569560)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2233 +0x1d8
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse(0xc0b11b6008, 0xc38b569560)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2198 +0x691
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery(0xc0b11b6008, 0xc38b569560, 0xc30d177180)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2765 +0x2b59
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest(0xc0b11b6008, 0xc38b569560, 0xc5bf1f9a70)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2839 +0xb9b
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc36d0c9180, 0xc5bf1f9a70)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:290 +0x93c
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc006fb6c40, {0x6ebd840, 0xc340b1f800}, {0x5b87be0, 0xc17b0e1360}, 0x6)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:539 +0x12da
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc006fccb80, {0x6ebd840, 0xc340b1f800})
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:205 +0x30c
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:356 +0x103
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2 in goroutine 947
	/go/pkg/mod/github.com/matrixo
```

**Comment by aressu1985** [comment]
[routine_01902083-d0a9-7329-b9be-c795dd7aedb3.gz](https://github.com/user-attachments/files/15860808/routine_01902083-d0a9-7329-b9be-c795dd7aedb3.gz)

**Comment by sukki37** [comment]
> [routine_01902083-d0a9-7329-b9be-c795dd7aedb3.gz](https://github.com/user-attachments/files/15860808/routine_01902083-d0a9-7329-b9be-c795dd7aedb3.gz)

In the earliest long-running stack, lots of transactions was observed to be blocked at the compile stage.

```
goroutine 16508271 [semacquire, 14 minutes]:
sync.runtime_Semacquire(0xc03eb2b730?)
	/usr/local/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc03eb2b730)
	/usr/local/go/src/sync/waitgroup.go:116 +0x8b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce(0xc0c11a5520)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:657 +0x405
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run(0xc0c11a5520, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:514 +0xc65
github.com/matrixorigin/matrixone/pkg/frontend.executeStatusStmt(0xc04b6cac08, 0xc32c836c60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/status_stmt.go:136 +0x11b1
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt(0xc04b6cac08, 0xc32c836c60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2537 +0x19ca
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt({0x6efdf50, 0xc04b6cac08}, 0xc32c836c60)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2401 +0x485
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt({0x6efdf50, 0xc04b6cac08}, 0xc32c836c60, {0x6ee5258, 0xc0deb47008})
	/go/src/git
```

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531125550%22,%22to%22:%221718532557000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
第一个long running的事务，由于加锁加不上，而卡在run里面。
加锁加不上的原因是一直报“lock table bind changed“。整个持续33分钟。

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%600190207f13057177bdcfc7d081624b0b%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698836%22,%22to%22:%221718536629569%22%7D%7D%7D&schemaVersion=1&orgId=1

![image](https://github.com/matrixorigin/matrixone/assets/60595215/674cb008-a898-4536-acc5-3117f4dea104)

**Comment by daviszhen** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%6001902083190479308822a2eafb3fed96%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698836%22,%22to%22:%221718536629569%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%6001902085560c73a7803f19bb97454154%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698836%22,%22to%22:%221718536629569%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%600190208763397803b37358c040a7d4b6%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698836%22,%22to%22:%221718536629569%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%600190208b5f79724ab46edc9dc9b2a1ff%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698836%22,%22to%22:%221718536629569%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
有随机选了4个long running的事务，原因同样。都是加锁失败，不停的报下面的错误。
持续时间在30分钟左右。

```
{"level":"ERROR","time":"2024/06/16 10:33:23.835098 +0000","name":"cn-service.lockservice","caller":"lockservice/lock_table_remote.go:117","msg":"failed to lock on remote","uuid":"34396634-3531-3062-6132-316435613434","txn":"0190208b5f79724ab46edc9dc9b2a1ff()","rows":"[46013e1502460173627465737400ff46017362746573743900ff00]","opts":"Shared-Row-Wait","remote":"10389912078361545511-171846041457044810634396634-3531-3062-6132-316435613434-1","error":"lock table bind changed"}
```

**Comment by sukki37** [comment]
2024/06/16 10:01:52.310310 +0000 stability-regression-dis-tp-cn-2gc75 oom

https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1718531004583&to=1718532557000&var-datasource=prometheus&var-cluster=&var-namespace=mo-nightly-25995d2-20240615220539

**Comment by daviszhen** [comment]
sql-executor相关的leak txn。也是因为“lock table bind changed”

![image](https://github.com/matrixorigin/matrixone/assets/60595215/bd16788f-f283-4c88-ad46-0b88c0b1cabe)

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22bg_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-25995d2-20240615220539%5C%22%7D%20%7C%3D%20%600190207f24dc79819c1a51fada7d0bc7%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718531698000%22,%22to%22:%221718533029000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
剩余的leak txn 跟proxy 迁移有关。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/394d69db-34e6-4c7c-a6be-619dcff5758a)

**Comment by daviszhen** [comment]
footprints 的问题：
1,handleREQUEST 之后没有清理
2,migrate之后没有清理。
3,commit和rollback之前，要更新到txnop中去。
4,记录workspace上的footprints

**Comment by daviszhen** [comment]
从leak的日志看，txn创建时的autocommit = 0。就是迁移时，session autocommit = 0。
可能是这个原因导致txn 没被commit。迁移时，autcommit 要强制为1才行。

**Comment by daviszhen** [comment]
事务leak的pr已经修改了。

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
