### ISSUE TITLE
[Feature Request]: Support cluster restore with snapshot

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#16940]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support cluster restore with snapshot

**Comment by YANGGMM** [comment]
down, plz test it @Ariznawlll

**Comment by YANGGMM** [comment]
https://doc.weixin.qq.com/doc/w3_AZUAugYIAOcs4alj5J6TpS2c3sP2H?scode=AJsA6gc3AA8x2DA4ieAZUAugYIAOc

**Comment by Ariznawlll** [comment]
test done
