### ISSUE TITLE
[Bug]: 1.2-dev standalone: sysbench bulk_insert 100threads test mo oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16942]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

6cfdcaf20fb7cda1a027e1b5c0b837607d4442d7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9536425137/job/26283375736
<img width="1357" alt="企业微信截图_a94238ba-5139-4d79-953a-79e4179e241e" src="https://github.com/matrixorigin/matrixone/assets/113406637/67185b35-642b-471c-a4cb-c3e7d53c6081">
oom时间04:48:25
<img width="1391" alt="企业微信截图_1cdd13e0-3e15-45b2-9136-18041844e059" src="https://github.com/matrixorigin/matrixone/assets/113406637/7290d82e-09e2-4b1b-871f-bb5aab08394d">

oom前heap：
[heap_019022b9-0526-7e0a-9b0c-648731f5cf5d.gz](https://github.com/user-attachments/files/15861214/heap_019022b9-0526-7e0a-9b0c-648731f5cf5d.gz)
[heap_019022b8-9007-7bef-889d-171780b05b15.gz](https://github.com/user-attachments/files/15861216/heap_019022b8-9007-7bef-889d-171780b05b15.gz)
[heap_019022b9-ef97-7447-b429-f85a47b2af74 (1).gz](https://github.com/user-attachments/files/15861208/heap_019022b9-ef97-7447-b429-f85a47b2af74.1.gz)
[heap_019022b9-7a5f-7937-bd29-6edbb5171dad.gz](https://github.com/user-attachments/files/15861209/heap_019022b9-7a5f-7937-bd29-6edbb5171dad.gz)
<img width="889" alt="企业微信截图_9c9d4ca5-2a9c-4d8d-b10e-05b6ad673630" src="https://github.com/matrixorigin/matrixone/assets/113406637/91a15856-55b1-41f4-8e27-d7d6cd7145fd">

mo log plz contact me

### Steps to Reproduce

```Markdown
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 bulk_insert.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=30 --report-interval=10 prepare
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111  bulk_insert.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=300 --report-interval=10 --range_selects=off --point_selects=1 run
```

**Comment by gouhongshen** [comment]
129 env:

150G: 
[heap_bulk_insert (1).out.zip](https://github.com/user-attachments/files/15863194/heap_bulk_insert.1.out.zip)


200G: 
[heap_bulk_insert2 (1).out.zip](https://github.com/user-attachments/files/15863198/heap_bulk_insert2.1.out.zip)

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前没有进展

**Comment by w-zr** [comment]
目前正在优化手动merge操作。

**Comment by w-zr** [comment]
一个优化merge 内存占用的pr合进main了 我最近测一下

**Comment by w-zr** [comment]
![image](https://github.com/user-attachments/assets/9ccb2344-3ef0-4541-a0f5-4b9f1e878cdb)
最新的main上bulk insert 100没有oom

**Comment by w-zr** [comment]
![image](https://github.com/user-attachments/assets/86b691c3-68ce-4101-b469-abaf688cbe79)
最新的main上拉通跑sysbench 10w， bulk insert 1000没有OOM

**Comment by w-zr** [comment]
后续会把https://github.com/matrixorigin/matrixone/pull/17656 合并到1.2-dev上

**Comment by w-zr** [comment]
等#17734 合并了就可以了

**Comment by heni02** [comment]
confirm,closed
