### ISSUE TITLE
[Tech Request]: make sure all vector will be free correctly

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#16965]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
make sure all vector will be free correctly
```

**Comment by reusee** [comment]
working on this branch with missing free detector enabled: https://github.com/reusee/matrixone/tree/freevector

**Comment by reusee** [comment]
Recorded all Vecotr allocation paths that missed Free. 
profile file: 
[profile.pb.gz](https://github.com/user-attachments/files/16357807/profile.pb.gz)

flamegraph:
![Screenshot from 2024-07-24 14-00-43](https://github.com/user-attachments/assets/48ca6222-ce34-41e4-aac1-67da5aa55902)

**Comment by reusee** [comment]
vector会逐步切换到堆外分配，如果有未回收的，会导致OOM。等实际出现问题了，再单独提issue吧
