### ISSUE TITLE
[Bug]: which one is the correct semantic for uint64 - int64?

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#1696]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This is the original behavior of MatrixOne:
mysql> create table t1 ( a int not null default 1, big bigint unsigned);
Query OK, 0 rows affected (0.44 sec)

mysql>  insert into t1 (big) values (12345678901234567),(9223372036854775807),(18446744073709551615);
Query OK, 3 rows affected (0.06 sec)

mysql>  select min(big),max(big),max(big)-1 from t1;
+-------------------+----------------------+----------------------+
| min(big)          | max(big)             | max(big) - 1         |
+-------------------+----------------------+----------------------+
| 12345678901234567 | 18446744073709551615 | 18446744073709551614 |
+-------------------+----------------------+----------------------+
1 row in set (0.01 sec)

uint64 - int64 returns uint64 type.

However, after adjusting the prune function logic, the behavior for this sql changes, and hence failed our BVT test:
mysql> create table t1 ( a int not null default 1, big bigint unsigned);
Query OK, 0 rows affected (0.53 sec)

mysql> insert into t1 (big) values (12345678901234567),(9223372036854775807),(18446744073709551615);
Query OK, 3 rows affected (0.07 sec)

mysql> select * from t1;
+------+----------------------+
| a    | big                  |
+------+----------------------+
|    1 |    12345678901234567 |
|    1 |  9223372036854775807 |
|    1 | 18446744073709551615 |
+------+----------------------+
3 rows in set (0.01 sec)

mysql> select min(big),max(big),max(big)-1 from t1;
+-------------------+----------------------+--------------+
| min(big)          | max(big)             | max(big) - 1 |
+-------------------+----------------------+--------------+
| 12345678901234567 | 18446744073709551615 |           -2 |
+-------------------+----------------------+--------------+
1 row in set (0.01 sec)

uint64 - int64 returns int64 type and overflowed in this case.

**Comment by m-schen** [comment]
mysql's convert rule is:

**Comment by broccoliSpicy** [comment]
applying mysql's convert rule, PR#1688 changed the castRule between int, uint types of Minus, Plus, Multi operator to uint64.

**Comment by broccoliSpicy** [comment]
issue#1721 defines MatrixOne's arithmetic operation semantic
