### ISSUE TITLE
[Bug]: 1.2-dev tke regression: tpcc 100ware 1000threads cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#16983]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

20f9de6

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9567364983/job/26383608134
<img width="1702" alt="企业微信截图_195861fe-73ae-4361-9caa-57d9c39c9c9b" src="https://github.com/matrixorigin/matrixone/assets/113406637/2756fe65-b2bc-418a-8e22-ce18bc4ddfbd">
3个cn都oom
<img width="1626" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/24031dab-2bb0-4e91-b147-2ed088fb7994">
https://grafana.ci.matrixorigin.cn/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-branch-reg-20f9de6&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki&from=1718734603651&to=1718744656481

memory-inuse_space:
17:00:00 to 17:00:10
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22xwg%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-20f9de6%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-sh9cq%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221718730000000%22,%22to%22:%221718730010000%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1382" alt="企业微信截图_25f8e594-2b2b-4c70-a6f6-b42d8409b789" src="https://github.com/matrixorigin/matrixone/assets/113406637/74db8637-2982-48db-9453-2ced5c6152d1">

18:59:00 to 18:59:10
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22xwg%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-20f9de6%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-sh9cq%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221718737140000%22,%22to%22:%221718737150000%22%7D%7D%7D&schemaVersion=1&orgId=1

19:06:00 to 19:06:10
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22xwg%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-20f9de6%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-sh9cq%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221718737560000%22,%22to%22:%221718737570000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc 100ware 1000threads test
```

**Comment by heni02** [comment]
@zhangxu19830126 cc

**Comment by m-schen** [comment]
这个bug产生的原因是，
https://github.com/matrixorigin/matrixone/pull/16923 这个pr重写了remote run，导致了两个节点间的connection没有关闭（同时也不会清理），它们对应的buffer始终占着内存。

在
https://github.com/matrixorigin/matrixone/pull/17079 这个pr过后该问题已修复。中间还有很多pr也处理了这件事情，不过并没有彻底解决。

可在1.2的 d64aa152ceee6e50151c7a0fdcfbd09af16a78e9 以及之后的版本进行验证，
应该不会出现这种rpc backend占据大量内存导致oom的问题了。

**Comment by heni02** [comment]
confirm，closed
commit：967f3e7
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9681089212/job/26719735486
