### ISSUE TITLE
[Bug]: 修改新增lineitem主键仍然报错

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#16996]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

d36f88943

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
aliyun QA
```

### Actual Behavior

dump用户增加mo_sample_data_tpch_sf1.lineitem主键
```
alter table mo_sample_data_tpch_sf1.lineitem add PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);
```
报错：
```
[HY000][20101] internal error: Packages delivered by morpc is broken
```

### Expected Behavior

正常修改

### Steps to Reproduce

```Markdown
如上
```

**Comment by xiaoshuwei** [comment]
dump用户，6月19日14:30~6月19日16:30之间发生的
不稳定复现，有时会成功

**Comment by xiaoshuwei** [comment]
sf10增加主键稳定报错。

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
本地单CN环境和多CN环境测试没有复现

**Comment by xiaoshuwei** [comment]
TODO

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
ProcessOn

**Comment by xiaoshuwei** [comment]
验证无误
