### ISSUE TITLE
[Bug]: Drop table that is not referenced by snapshots will not be GC

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#16997]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

ffd38a22e3c04dda4dc14a917ee6837fadb0e6ca

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Drop table that is not referenced by snapshots。data is will not be GC

### Steps to Reproduce

```Markdown
create table1 and load data
create snapshot
create table2 and load data
drop table2
```

**Comment by LeftHandCold** [comment]
fixed

**Comment by Ariznawlll** [comment]
**测试前准备：**
单机环境在tn.toml里面加上配置：
```
[tn.Ckp]
flush-interval = "10s"
min-count = 100
scan-interval = "5s"
incremental-interval = "30s"
global-min-count = 9

[tn.GCCfg]
gc-ttl = "5m"
scan-gc-interval = "2m"
check-gc = true
```
并对应修改代码配置：（收集5min中内的过期数据）
/Users/ariznawl/matrixone/pkg/vm/engine/tae/options/types.go
<img width="514" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6055829b-5b82-4599-88be-2a71e0b714e3">
create snapshot sp01 for account sys;
<img width="769" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/09a94dd1-c84f-45f4-bb96-add0f7e946e3">

查看存储所在的block信息：
<img width="575" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/2e7b9f02-e258-4019-905c-5a7257d251f6">

删除表t1：drop table t1;

查看表t1所在的存储block：
<img width="649" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/efd883fa-ffc8-406d-8248-dcc088892aa9">
