### ISSUE TITLE
[Tech Request]: sometimes filter expr is nil in filter operator

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#16994]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
目前有些时候filter算子的 arg.E 是 nil
1、先确认一下是什么原因造成的

2、对于这种情况的处理：
   a. 如果buildplan时候就知道的话，那么应该去掉这个node
   b. 如果compile阶段造成的话，那么应该可以去掉这个算子
   c. 如果执行期才知道的话，那么优化一些filter算子的写法，当发生这种情况的时候，直接返回子节点的call的结果就可以了
```

**Comment by huby2358** [comment]
1. 目前代码里面只有在compileRestrict里面调用constructRestrict，在constructRestrict里面设置arg.E， compileRestrict里面当 len(n.FilterList) == 0 && len(n.RuntimeFilterProbeList) == 0为0会直接返回，不会生成filter operator， 也就是只有当len(n.FilterList) 为0并且len(n.RuntimeFilterProbeList)不为0的时候，在这里arg.E才为nil。此后在执行期间handleRuntimeFilter函数里面确定，这个函数有种情况会设置arg.E, 如果不设置，在filter算子执行时arg.E就为nil
2. 从1可知，需要在执行期间handleRuntimeFilter函数才会最终确认arg.E是否为nil，所以修改pr在filter的执行期prepare和call做优化。是nil的时候提前返回。
