### ISSUE TITLE
[Bug]: some  Duplicate entry error in new order txn in tpcc 10-10 test during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17006]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

20f9de6

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

There were some  Duplicate entry error in new order txn in tpcc 10-10 test during stability test on distributed mode.
<img width="1401" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/2526d1de-7da3-4464-94b9-4b117eca187e">

mo-log link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22l0z%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-20f9de6-202406182258%5C%22%7D%20%7C%3D%20%60Dup%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

one of error txn flow was:
mysql> select * from statement_info where transaction_id='01902d62f41d74c4a5c38105649e280c' order by request_at asc\G;
*************************** 1. row ***************************
         statement_id: 01902d62-f41d-7302-b6ff-9ac3e953ee01
       transaction_id: 01902d62f41d74c4a5c38105649e280c
           session_id: 01902d58-d7f4-799c-87e0-e4ab914a74fd
              account: tpcc_test
                 user: admin
                 host: 
             database: tpcc_10
            statement: execute __mo_stmt_id_2 // prepare __mo_stmt_id_2 from **SELECT d_tax, d_next_o_id     FROM bmsql_district     WHERE d_w_id = ? AND d_id = ?     FOR UPDATE ; 1 ; 4**
        statement_tag: 
statement_fingerprint: 
            node_uuid: 31396432-6633-6236-3464-363562646361
            node_type: CN
           request_at: 2024-06-18 22:06:18.141072
          response_at: 2024-06-18 22:06:27.981725
             duration: 9840652914
               status: Success
*************************** 2. row ***************************
         statement_id: 01902d63-58ab-74cb-b558-bec339849649
       transaction_id: 01902d62f41d74c4a5c38105649e280c
           session_id: 01902d58-d7f4-799c-87e0-e4ab914a74fd
              account: tpcc_test
                 user: admin
                 host: 
             database: tpcc_10
            statement: execute __mo_stmt_id_1 // prepare __mo_stmt_id_1 from SELECT c_discount, c_last, c_credit, w_tax     FROM bmsql_customer     JOIN bmsql_warehouse ON (w_id = c_w_id)     WHERE c_w_id = ? AND c_d_id = ? AND c_id = ? ; 1 ; 4 ; 1591
        statement_tag: 
statement_fingerprint: 
            node_uuid: 31396432-6633-6236-3464-363562646361
            node_type: CN
           request_at: 2024-06-18 22:06:34.352887
          response_at: 2024-06-18 22:06:43.920624
             duration: 9567736958
               status: Success
*************************** 3. row ***************************
         statement_id: 01902d63-58d8-7b62-9d47-7052053cb4f8
       transaction_id: 01902d62f41d74c4a5c38105649e280c
           session_id: 01902d58-d7f4-799c-87e0-e4ab914a74fd
              account: tpcc_test
                 user: admin
                 host: 
             database: tpcc_10
            statement: execute __mo_stmt_id_3 // prepare __mo_stmt_id_3 from **UPDATE bmsql_district     SET d_next_o_id = d_next_o_id + 1     WHERE d_w_id = ? AND d_id = ? ; 1 ; 4**
        statement_tag: 
statement_fingerprint: 
            node_uuid: 31396432-6633-6236-3464-363562646361
            node_type: CN
           request_at: 2024-06-18 22:06:43.928599
          response_at: 2024-06-18 22:07:12.339911
             duration: 28411312766
               status: Success
*************************** 4. row ***************************
         statement_id: 01902d63-c7d5-78a3-916e-0ada1a512cd9
       transaction_id: 01902d62f41d74c4a5c38105649e280c
           session_id: 01902d58-d7f4-799c-87e0-e4ab914a74fd
              account: tpcc_test
                 user: admin
                 host: 
             database: tpcc_10
            statement: execute __mo_stmt_id_4 // prepare __mo_stmt_id_4 from **INSERT INTO bmsql_oorder (    o_id, o_d_id, o_w_id, o_c_id, o_entry_d,     o_ol_cnt, o_all_local) VALUES (?, ?, ?, ?, ?, ?, ?) ; 3510 ; 4 ; 1 ; 1591 ; 2024-06-19 06:07:12.344000 ; 6 ; 1**
        statement_tag: 
statement_fingerprint: 
            node_uuid: 31396432-6633-6236-3464-363562646361
            node_type: CN
           request_at: 2024-06-18 22:07:12.341523
          response_at: 2024-06-18 22:07:12.988693
             duration: 647169624
               status: Failed
             err_code: 20307
                error: Duplicate entry '(1,4,3510)' for key '__mo_cpkey_col'
            exec_plan: {}
            rows_read: 1
           bytes_scan: 36
                stats: [4,111250706,133.000,0,18,132,2,0,125.6458]
       statement_type: Execute
           query_type: Other
              role_id: 2
      sql_source_type: external_sql
           aggr_count: 0
         result_count: 0
*************************** 5. row ***************************
         statement_id: 01902d63-ca60-7ee3-a1d5-7af6043eddd2
       transaction_id: 01902d62f41d74c4a5c38105649e280c
           session_id: 01902d58-d7f4-799c-87e0-e4ab914a74fd
              account: tpcc_test
                 user: admin
                 host: 
             database: tpcc_10
            statement: rollback
        statement_tag: 
statement_fingerprint: 
            node_uuid: 31396432-6633-6236-3464-363562646361
            node_type: CN
           request_at: 2024-06-18 22:07:12.992933
          response_at: 2024-06-18 22:07:13.023378
             duration: 30444515
               status: Success
             err_code: 0
                error: 
            exec_plan: {}
            rows_read: 0
           bytes_scan: 0
                stats: [4,0,0,0,0,210,0,3,0.1652]
       statement_type: Rollback
           query_type: TCL
              role_id: 2
      sql_source_type: external_sql
           aggr_count: 0
         result_count: 0
5 rows in set (28.20 sec)

There were maybe something wrong with [lock] in select for update。

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by triump2020** [comment]
单机的 ww/dup 原因已定位到大致原因。

**Comment by triump2020** [comment]
Wait for [PR](https://github.com/matrixorigin/matrixone/pull/17388) merge

**Comment by triump2020** [comment]
@aressu1985 已知 的 dup/ww 都已经fix 了, 请测试观察. 远宁那个 delete 加锁问题导致 的dup/ww 有对应的issue.
