### ISSUE TITLE
[Bug]: sysbench test reported error FATAL: Worker threads failed to initialize within 30 seconds!

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17001]
### Is there an existing issue for the same bug?

- [X] #17382

### Branch Name

main

### Commit ID

6a43a6e7a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9567035983/job/26400260798
<img width="1281" alt="企业微信截图_d7a65ef7-a6e7-42e3-b87e-ae6716c720ba" src="https://github.com/matrixorigin/matrixone/assets/113406637/8ebade3f-b8d1-4805-b985-1e0821b68709">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22kbI%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240618%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718774634000%22,%22to%22:%221718774664000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench1000w nopk-load and nopk-point-select test
```

**Comment by reusee** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22aaX%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_namespace%3D%5C%22mo-error-case--nightly-57a9e8776-20240624%5C%22%7D%20%7C%3D%20%60slow%20event%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

没有记录到慢的 I/O，不是 io 开销过大的问题。

**Comment by reusee** [comment]
原始错误信息
<img width="913" alt="企业微信截图_a339aa93-a068-4a68-9016-dc1be1b8adfc" src="https://github.com/matrixorigin/matrixone/assets/398457/d870d2d0-9a26-43d4-a55e-ced6ff54d7ba">

**Comment by reusee** [comment]
在 2024-06-24 04:00 左右的错误信息：https://grafana.ci.matrixorigin.cn/goto/KtEhzSQIR?orgId=1

可以看到有大量的 failed to init stats info for table 以及 connect: cannot assign requested address。后者似乎是因为fd耗尽，无法bind导致，可能是有网络连接未关闭，或者同时发起太多。

**Comment by reusee** [comment]
> ### Is there an existing issue for the same bug?
> 
>     * [x]  I have checked the existing issues.
> 
> 
> ### Branch Name
> 
> main
> ### Commit ID
> 
> [6a43a6e](https://github.com/matrixorigin/matrixone/commit/6a43a6e7a8fbb43c6ea1721f19e7190b70971afa)
> ### Other Environment Information
> 
> ```
> - Hardware parameters:
> - OS type:
> - Others:
> ```
> 
> ### Actual Behavior
> 
> job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9567035983/job/26400260798 <img alt="企业微信截图_d7a65ef7-a6e7-42e3-b87e-ae6716c720ba" width="1281" src="https://private-user-images.githubusercontent.com/113406637/341006663-8ebade3f-b8d1-4805-b985-1e0821b68709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDYxMzgsIm5iZiI6MTcxOTIwNTgzOCwicGF0aCI6Ii8xMTM0MDY2MzcvMzQxMDA2NjYzLThlYmFkZTNmLWI4ZDEtNDgwNS1iOTg1LTFlMDgyMWI2ODcwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNTEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGViOGE2ZDdjZDBkYmFhYWJhYTY1NjcwYzhhODhjNzNiNTFkNzhmMWE2YzNkZTZlZWIzMjIwYTc5MmI4N2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kyPGSxkI7oGRRbEwtfiOLol0vZb_PLLmlma3c9VyeK0">
> 
> mo log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22kbI%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-nightly-regression-20240618%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718774634000%22,%22to%22:%221718774664000%22%7D%7D%7D&schemaVersion=1&orgId=1
> ### Expected Behavior
> 
> _No response_
> ### Steps to Reproduce
> 
> ```
> tke regression sysbench1000w nopk-load and nopk-point-select test
> ```
> 
> ### Additional information
> 
> _No response_

这里又是另一个问题：https://grafana.ci.matrixorigin.cn/goto/nyU3iIQIR?orgId=1

看上去 cannot get table by ID 是主因

**Comment by reusee** [comment]
两次重现，都和 disttae 包内的 stats 相关，先转给 @volgariver6 做进一步分析

**Comment by volgariver6** [comment]
用改过之后的分支跑，还是会有问题，目前没有定位到具体原因，只是观察到在出问题的时候，创建了大量的goroutines。

**Comment by volgariver6** [comment]
尚无进展

**Comment by volgariver6** [comment]
正在测试

**Comment by volgariver6** [comment]
目前测试还是会报错，麻烦 @reusee 继续跟踪一下

**Comment by XuPeng-SH** [comment]
https://github.com/matrixorigin/mo-auto-test/actions/runs/9890430540 测试两次没有问题了

**Comment by heni02** [comment]
confirm，closed
commit：88e486e11
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9976227425

**Comment by Ariznawlll** [comment]
**commit**：081becbc9158278b3bd974075a40e3539aafa1db

**job url**：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10405469110/job/28842654264

<img width="940" alt="image" src="https://github.com/user-attachments/assets/2e7e1a31-8455-4e91-8c46-7432c818c33a">

第一次出现 FATAL的log:https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22F03%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-081becbc9-20240815%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723786939000%22,%22to%22:%221723786969000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
@Ariznawlll 这个麻烦跑一下二分吧，估计是最近的哪个pr引起

**Comment by volgariver6** [comment]
等待二分结果

**Comment by heni02** [comment]
二分查到是18100pr，cc @ouyuanning 
<img width="1355" alt="企业微信截图_95491f00-ac90-4023-b160-ddc6e6b464a3" src="https://github.com/user-attachments/assets/3c57bdd4-280f-4f29-a1ab-b0cce9b4f2f9">

job：https://github.com/matrixorigin/mo-auto-test/actions/runs/10508265514/job/29112655376
<img width="1071" alt="企业微信截图_94e9defb-bbe9-4b55-b7b7-fe958119c386" src="https://github.com/user-attachments/assets/0ae32f65-eb41-4ba0-adc8-e34221ad6916">

**Comment by triump2020** [comment]
> 二分查到是18100pr，cc @ouyuanning <img alt="企业微信截图_95491f00-ac90-4023-b160-ddc6e6b464a3" width="1355" src="https://private-user-images.githubusercontent.com/113406637/360877072-3c57bdd4-280f-4f29-a1ab-b0cce9b4f2f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDY1OTEsIm5iZiI6MTcyNDc0NjI5MSwicGF0aCI6Ii8xMTM0MDY2MzcvMzYwODc3MDcyLTNjNTdiZGQ0LTI4MGYtNGYyOS1hMWFiLWIwY2NlOWI0ZjJmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODExMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWM1YThmNDIwYWM1MTcxYmMwMjlhMTE0NDMzMWFmYmQxMGE4NmEzNWEyY2UxMDg1ZjIyYmMxN2FlMDEzN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YhTx8qlWF4VeoRh0qbHuXK6zGkONVXJsRNgurtNCEV8">
> 
> job：https://github.com/matrixorigin/mo-auto-test/actions/runs/10508265514/job/29112655376 <img alt="企业微信截图_94e9defb-bbe9-4b55-b7b7-fe958119c386" width="1071" src="https://private-user-images.githubusercontent.com/113406637/360877255-0ae32f65-eb41-4ba0-adc8-e34221ad6916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDY1OTEsIm5iZiI6MTcyNDc0NjI5MSwicGF0aCI6Ii8xMTM0MDY2MzcvMzYwODc3MjU1LTBhZTMyZjY1LWViNDEtNGJhMC1hZGM4LWUzNDIyMWFkNjkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODExMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjgxOWYxODE2YjQ0ZmU2ZWFiMjU3MDg0MThiMWViZTAwMTczMWUzOGY0NGU0NzQyNTc0ZDMxMWQ0ZGI2Yjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i5zCpFpNkYlm_6cgh0SWJt7rsnCS6luKD7BXzOcTyk4">

@heni02  确定是 18100 这个pr 么？ 这个pr 只是调用了reader.Close , reader.Close 里面啥都没干，就是把一个迭代器复位了下.

**Comment by ouyuanning** [comment]
报错跟#17793一样，
目前1.2-dev也发现类似问题。应该不是二分到的这2个PR引入的

**Comment by heni02** [comment]
更新下1.2报错信息：
1.2-dev commit:59d156b46
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10634487640/job/29503486397
<img width="1055" alt="企业微信截图_921e8c75-c715-416e-90b4-903e79e0d9db" src="https://github.com/user-attachments/assets/0866644a-94d0-4926-af70-be694a216386">
mo log：
@李乐声(Li Yue Sheng) https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22qFM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-59d156b46-20240830%5C%22%7D%20%7C%3D%20%60operation%20error%20S3:%20GetObject,%20exceeded%20maximum%20number%20of%20attempts,%203%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725083373948%22,%22to%22:%221725083702716%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by heni02** [comment]
1.2-dev commit：b0f3a5481复现了，环境已配置相关参数
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11142247340/job/30999607062
<img width="1101" alt="企业微信截图_65967e6e-195a-4ffe-bd53-b4d547c756c8" src="https://github.com/user-attachments/assets/b143e35b-188b-48cb-a71d-5f1ba21e3faf">
yaml：
https://github.com/matrixorigin/mo-nightly-regression/blob/main/mo-bench-tke.yaml

threads初始时间：09:36:09
报错时间：09:36:39
mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Wjp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-b0f3a5481-20241002%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727919369000%22,%22to%22:%221727919399000%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1334" alt="企业微信截图_0ee34a95-f430-4bd3-90db-fea1dddebe1f" src="https://github.com/user-attachments/assets/62d652a7-8397-406f-bd33-18bf3980ae32">

**Comment by heni02** [comment]
main commit:94cbcf83d
复现了该问题
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11276243006/job/31388222596
<img width="1639" alt="企业微信截图_95843a59-6a3b-4689-a815-a5dfdd2c3fdf" src="https://github.com/user-attachments/assets/8de61198-c6b9-4bbe-a307-f2b81a4b0a9e">

日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Q0w%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-94cbcf83d-20241010%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728623580000%22,%22to%22:%221728623640000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by reusee** [comment]
https://grafana.ci.matrixorigin.cn/goto/PtIcrekNg?orgId=1

从日志看，dest port 为 443 的连接数量达到两万八。

但 fileservice 内部已经限制了并发的 reader 的数量，暂时不清楚哪里导致了这个问题。

**Comment by reusee** [comment]
working on other issues.

**Comment by aressu1985** [comment]
最近2两天的REGRESSION都没有在出现过改问题，改为testing状态
