### ISSUE TITLE
[Bug]: Like with “\” doesn't work correctly

### ISSUE THREAD

**Issue by SilvaXiang** [matrixorigin/matrixone#1701]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.2.0分支Mac本地运行
- Hardware parameters:
- OS type:Macos
- Others:
```

### Actual Behavior

1.create table and insert the data
```
CREATE TABLE T(a varchar(244));
INSERT INTO T(a) VALUES ('d');
```
2.query
Query1 :`select * from T where a like '\d';`
Query2 :`select * from T where a like '\\d';`

3.result
Query1:
d

Query2:
empty set

### Expected Behavior

Query1:
d

Query2:
d

### Steps to Reproduce

```markdown
CREATE TABLE T(a varchar(244));
INSERT INTO T(a) VALUES ('d');
select * from T where a like '\d';
select * from T where a like '\\d';
```

**Comment by m-schen** [comment]
I forget to solve '\' at like operator and only consider '_' and '%'. It's a bug correctly .

these related functions at File 'pkg/vectorize/like/like.go'.
I will fix these bug at current version. And if you are interested about it, you can try to make a commit to solve these issue. @SilvaXiang

**Comment by m-schen** [comment]
I verify the Reproduce Case, our result is same to Postgresql.
