### ISSUE TITLE
[Bug]:  bvt case `show tables` in `pub_sub_improvment.sql` faild

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#17024]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/9591107690/job/26447563564?pr=17018

[Standalone-e2e-BVT-Test-on-Linux-x64(LAUNCH,PESSIMISTIC)-reports.zip](https://github.com/user-attachments/files/15909156/Standalone-e2e-BVT-Test-on-Linux-x64.LAUNCH.PESSIMISTIC.-reports.zip)

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by gouhongshen** [comment]
这个 bvt case 是为了验证租户不能修改订阅的 table 内存，通过 show table status 主要关注 rows 和 size 有没有变化，但这里的 size 可能也是不太确定的，如果恰好碰到刷盘，size就会变化。但这个 issue 的size 变化看起来不太像 刷盘的原因，暂时不知道原因，先加一些 log，下次复现的时候看一下 执行 size 的逻辑是不是有问题。

**Comment by ck89119** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/9595799857/job/26461324894?pr=17036

**Comment by gouhongshen** [comment]
> https://github.com/matrixorigin/matrixone/actions/runs/9595799857/job/26461324894?pr=17036

没有包含打印log这个 commit

**Comment by gouhongshen** [comment]
@sukki37 可以先降低优先级，等出现后分析下 log.

**Comment by gouhongshen** [comment]
之前统计 partition state 里面的 rows 时，使用的是 row.Batch 的地址昨晚去重的手段，绝大多数情况下没有问题，但一条记录也可能会重复推到 CN，不属于同一个 logtail, 自然也不属于同一个 batch，所以就做不到去重的目的。现在使用 rowid 去重。

**Comment by Ariznawlll** [comment]
没再出现了。

**Comment by Ariznawlll** [comment]
****main commit： b4b66973f010a71fc3b50d6958ad84295c5c4bd8****
使用脚本执行bvt case : pub_sub_improvment.sql 4h次。未出现。
脚本： 
<img width="1098" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/6e18c18d-ab59-4f7b-b288-de714ab185e7">
执行结果：
[command_results_1.2.txt](https://github.com/user-attachments/files/16135433/command_results_1.2.txt)

测试通过。
