### ISSUE TITLE
[Bug]: DEV环境CN一段时间连接不上CN，报错ERROR 20101 (HY000): internal error: no available CN server

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#17082]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

a4da5e955ea312d0ec5f3d30a2185b2761df41ec

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
时间0621，东八区16:36~16:54左右
报错

ERROR 20101 (HY000): internal error: no available CN server
```
```


### Actual Behavior

使用Mysql连接串链接失败，租户
```
018ebbbd_e916_74f9_8f27_399f0b7084ad
```

### Expected Behavior

正常链接

### Steps to Reproduce

```Markdown
偶现，只在那一段时间出现了
```

**Comment by volgariver6** [comment]
<img width="1390" alt="WeChatWorkScreenshot_9ccbc837-f663-4ec3-804e-9502166fba7a" src="https://github.com/matrixorigin/matrixone/assets/18366608/6ee8cf94-97d3-447a-b7a0-6b860bfe4592">

那段时间cn发生了重启，才导致的这个问题，重启的原因还不清楚。

**Comment by xiaoshuwei** [comment]
可能是认为重启导致的。先关掉了。
