### ISSUE TITLE
[Bug]: random points qps in daily regression degrade from 20000+ to 7000+

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#17093]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.2-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/39627130/d22f728a-c910-45ec-a520-ad29f9384b1e)

#17038 is 7000+
#17036 is 20000+

### Steps to Reproduce

```Markdown
sysbench 1000w random points daily regression test
```

**Comment by gouhongshen** [comment]
本地单机测下来：

![企业微信截图_171906766736](https://github.com/matrixorigin/matrixone/assets/26336316/73d0b509-562e-4abe-bb4e-3785b4cf84ef)

虽然和 nightly 值不一样，但下降的趋势是一样的。

2W+ profile:
[profile.zip](https://github.com/user-attachments/files/15937185/profile.zip)


1.6W profilt: 

[profile2.zip](https://github.com/user-attachments/files/15937186/profile2.zip)



```
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 select_random_points.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=30 --report-interval=10    prepare



sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111   select_random_points.lua --mysql-db=sysbench_db --tables=10 --table_size=1000000 --threads=100 --time=300 --report-interval=10   --range_selects=off --point_selects=1 run
```

**Comment by aressu1985** [comment]
和徐鹏沟通过，该问题影响不大，延期到后续版本解决

**Comment by heni02** [comment]
sysbench10w,100w,1000w 性能已经恢复 confirm,closed
<img width="1844" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/9432e178-2425-457d-a96b-0f5b6d58e7b2">
