### ISSUE TITLE
[Bug]: Failed to start mo-server on arm platform

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#1712]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7ba03649cc99c0c376a1d5317fb89b3e0346816e
- Hardware parameters: arm
- OS type: mac os
- Others:
```

### Actual Behavior

<img width="1586" alt="image" src="https://user-images.githubusercontent.com/14086886/154188474-e46dde50-3aa0-4d93-9d30-d988a0b53146.png">

### Steps to Reproduce

```markdown
1.clean store directory
2.make config
3.make build
4../mo-server system_vars_config.toml
```

**Comment by sukki37** [comment]
Need upgrade `github.com/shirou/gopsutil/v3` to v3.22.1 @zhangxu19830126

**Comment by sukki37** [comment]
Fixed
