### ISSUE TITLE
[Bug]: [date 6.24]tke regression: cn reported panic and fatal error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17129]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8a3f70d86899b6815b35c98e2dc9e6402515e2e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9647284363/job/26608542479
很多panic和fatal error，还有段错误
![企业微信截图_17c9b248-e7c9-4a98-9311-1aad70804b05](https://github.com/matrixorigin/matrixone/assets/113406637/b6e53fc6-af42-402a-aedd-a210fb6ea97c)
![企业微信截图_b7dc00b4-a591-4dda-8f6e-5270ad94bd2f](https://github.com/matrixorigin/matrixone/assets/113406637/00a6c063-ba05-4494-8a1a-2fe0c78d6b3e)

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hhC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-8a3f70d86-20240624%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719268966000%22,%22to%22:%221719268967000%22%7D%7D%7D&schemaVersion=1&orgId=1

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hhC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-8a3f70d86-20240624%5C%22%7D%20%7C%3D%20%60fatal%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719241322714%22,%22to%22:%221719284522714%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression tpcc test
```

**Comment by ouyuanning** [comment]
本地tpcc 100仓200线程10分钟没有复现。
但是看出错的地方，有几处都是从这里报错
![image](https://github.com/matrixorigin/matrixone/assets/45346669/1ca9c418-f72a-4ac6-a3be-ed3d2f00048d)

看着像是filter算子的E这个属性有data race。被哪里修改了

**Comment by heni02** [comment]
二分正在排查中：
tpcc 100仓可以复现
<img width="1360" alt="企业微信截图_8c81e96b-cc36-424e-a68a-d86dc16c333c" src="https://github.com/matrixorigin/matrixone/assets/113406637/2b4569ee-aeec-4cdc-9859-68d59db17c10">

**Comment by aressu1985** [comment]
@ouyuanning 
https://github.com/matrixorigin/MO-Cloud/issues/3622
和这个issue一样，这个case必现

**Comment by heni02** [comment]
confirm,closed
commit:e975b6dc9
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9681659361/job/26715767673
