### ISSUE TITLE
[Bug]: TestWatchDirty

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#17127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0624-add-metric-1.2

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/9644744574/job/26597467528?pr=17126
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/f8a774b7-abe3-4fa3-b895-9cb849601191)

### Expected Behavior

no failuare

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9644744574/job/26597467528?pr=17126
```

**Comment by sukki37** [comment]
dup with #15918
