### ISSUE TITLE
[Bug]: query `mo_tables` with `rel_id` condition will return empty result.

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#17136]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.2

### Commit ID

8a3f70d86899b6815b35c98e2dc9e6402515e2e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sql
mysql> select relname, rel_id from mo_tables order by rel_id limit 5;
+---------------------+--------+
| relname             | rel_id |
+---------------------+--------+
| mo_database         |      1 |
| mo_tables           |      2 |
| mo_columns          |      3 |
| mo_indexes          | 272385 |
| mo_table_partitions | 272386 |
+---------------------+--------+
5 rows in set (0.00 sec)

mysql> select relname, rel_id from mo_tables  where rel_id = 1;
Empty set (0.00 sec)

```

### Steps to Reproduce

```Markdown
see above.
```

**Comment by gouhongshen** [comment]
问题的原因是，这个PR修改mo_tables表的 schema 后，expr 推下来的 primary key col 和 partition state 里面的 pk col 不一致，导致 reader 匹配不到正确的值，所以返回了空。之前这三张特殊的表的 pk 没有在 schema 中体现，也不会在 reader里构造 filter，但在其他需要pk 的地方做了特殊处理，使用的联合组键。

这三张表的改造正在做，我可以先提一个 简单的 workaround，在 reader 那里特殊处理下。

**Comment by aptend** [comment]
fix pr https://github.com/matrixorigin/matrixone/pull/17892

**Comment by aptend** [comment]
fix pr https://github.com/matrixorigin/matrixone/pull/17892
