### ISSUE TITLE
[Bug]: [big-data-test] insert into select performance degradation.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17143]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9f1c2df

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
<img width="722" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f337fcc8-0142-4e52-ad35-c453b26516ba">

上周正常的job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9581145106
commit：2440b884e23da215733c181b458cefd1ccb32126
<img width="1371" alt="image"
src="https://github.com/matrixorigin/matrixone/assets/108530700/97fe45fa-9944-458d-a520-b8e9625802bc">
log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22N7w%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240619%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221718755200000%22,%22to%22:%221718927999000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile : https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22N7w%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240619%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221718816160000%22,%22to%22:%221718819174000%22%7D%7D%7D&schemaVersion=1&orgId=1

性能退化的job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9640573308
commit： 9f1c2dfa908bc08f58cbf59dcb14b4f3bdd16a1c
<img width="1361" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/086ddc56-e26b-48fb-8f9a-423837a02e15">
log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22N7w%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240624%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719229434000%22,%22to%22:%221719238361000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22N7w%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240624%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719229434000%22,%22to%22:%221719238361000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big-data-test on tke
```

**Comment by jensenojs** [comment]
性能退化的job在跑`insert into table_with_com_pk_index_for_insert_1B`的时候, 从`2024 11:43:54`开始, 到`2024 14:12:41`结束, 对应到的profile 似乎应该看下面这个链接 : 

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22N7w%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240624%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719229434000%22,%22to%22:%221719238361000%22%7D%7D%7D&schemaVersion=1&orgId=1

它的CPU截图如下所示 : 

<img width="1676" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/9845e8d6-0b70-461a-840e-be42c0a340f3">


***

作为对比, 之前的jobs的CPU截图如下所示 : 

<img width="1676" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/865d03c6-95d9-4f8a-b8c9-b51b6e95aeb7">

gc时间暴涨

**Comment by jensenojs** [comment]
```sh
9f1c2dfa9 fix delete page error and some typos (#17087)  <- report
8eb9e709b [opt] : remove output operator after fuzzy filter (#17077)
79e9e4394 Fix typos in README (#16402)
57a9e8776 fileservice: use noop retryer in aws sdk (#17095)
c88c0978c fileservice: more slow logs (#17100)
e520a422a [bug] stats: fix the leak of goroutine (#17071)
72b187e61 fix lock table move failed (#17092)
067da2e8f Fix bugs[dup/ww/data-lost] when unsubscribe table (#17005)
72d4b89e8 [bug] fix ut TestPauseResumeDaemonTask (#17028)
eaf78572f [Cherry-pick] Refactor UnresolvedName (#17040)
9d68af958 Fix memory leak   (#17069)
5a73df781 mo-service: data dir compatibility fixes (#17062)
8d1d0fb68 preallocate transfer page (#17056)
d39bec0ca [opt] : optmize duplicate check memory usage for sql like insert into t1 selct from t2 (#17020)
e36343faa fix: external free (#17074)
eb1f0f578 [enhancement] logtail: change the default send timeout, add logs (#17059)
d6a322621 [refator]move all state type variables to arg.ctr in Operator (#16951)
a014b808c adding logic for prefix_in in case vector items are not unique. (#17041)
c6fa50c4f adjust timeout for orphan transactions (#17044)
46e017801 fix stats bug for fuzzy filter (#17051)
b8ab81b9a add system busy monitor (#17049)
8dbcb5093 debug load local (#17046)
15a2c3aef fix some little bug of stats (#17035)
a19e6d696 fileservice: add event logger and log slow S3.Read (#17021)
1ac74cfb9 change all filter related "or" expr from binary function to multi function (#16992)
3dbabeec9 [enhancement] proxy: clean some logs (#17031)
1e35ff0a9 retry allocate if orphan txn (#17030)
6448ba46a objectio: copy to avoid memory leak (#17029)
9334ffea3 reduce memory allocation by NewWithAnalyze (#17019)
a7f6835f2 logservice: fix memory leak (#17023)
a40cae885 [bug] filter out the CNs with different commit ID. (#17003)
f72a8464a fix snapshot read bug (#17016)
5cba9c51f malloc: various changes and optimizations  (#16990)
8c4f92bfc dashboard: fix fileservice board (#17008)
f223c892c Fix error refers for table meta (#16999)
2440b884e bug fix: load s3 panic (#17009) <- last good
```

**Comment by Ariznawlll** [comment]
[0626] 
1.2-dev: 2545ce4c726d5c9e64f7a6b8307b5da0e6da950d
job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9660414495/job/26646571031

<img width="1377" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/04f32b09-73aa-4db4-8659-1eccaf484436">

profile: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240625%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719342869000%22,%22to%22:%221719349741000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
> [0626] 1.2-dev: [2545ce4](https://github.com/matrixorigin/matrixone/commit/2545ce4c726d5c9e64f7a6b8307b5da0e6da950d) job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9660414495/job/26646571031
> 
> <img alt="image" width="1377" src="https://private-user-images.githubusercontent.com/108530700/342988554-04f32b09-73aa-4db4-8659-1eccaf484436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzAwMzgsIm5iZiI6MTcxOTM2OTczOCwicGF0aCI6Ii8xMDg1MzA3MDAvMzQyOTg4NTU0LTA0ZjMyYjA5LTczYWEtNGRiNC04NjU5LTFlY2NhZjQ4NDQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwMjQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzI1MjJlMjA4MzJkMTdmYWQ2ZWI4N2E5NzgyOGY4ZmUzZGJkMWJlZTAyNGQ1Yzk4MWQxZDEzNTNkNzgwZmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rPh3989oTqsMxFf3sMTWARNr4bVW3UtNBNbTRYnliqs">
> profile: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240625%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719342869000%22,%22to%22:%221719349741000%22%7D%7D%7D&schemaVersion=1&orgId=1

从pprof上看和main上性能退化是类似的

<img width="1676" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/cd5ff04e-46f9-49c4-84f7-7dcdd6c02dbd">

**Comment by jensenojs** [comment]
表因是最近改了`GOLIMIT`的参数, 根因还是在insert into select 的时候内存压力太大了, 导致疯狂gc

- https://github.com/matrixorigin/mo-nightly-regression/commit/2726e7b3eab0ff8d4a5417fc063b3b5df42e5b78

继续做
- https://github.com/matrixorigin/matrixone/issues/16375

**Comment by jensenojs** [comment]
等pr合并

**Comment by jensenojs** [comment]
请魏璐帮忙跑了一下main上合并了fuzzy内存优化相关的代码, 可以看到gc的压力小了, 耗时回到了一小时以内. 


https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9698664379/job/26775565464


profile link : https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240627%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719519314000%22,%22to%22:%221719522812000%22%7D%7D%7D&schemaVersion=1&orgId=1


cpu : 
<img width="1757" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/69185cff-c1ec-47db-813e-7626be66c779">

inuse-memory : 
<img width="1757" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/78b696dc-54e9-4c33-9840-b82ce6a095d1">

**Comment by jensenojs** [comment]
<img width="1429" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/fdc787dd-f8c8-40cf-b34f-bc04006b0a85">

但其实不能确定是不是由我的优化来fix的, 毕竟gc跟object数量有关系, 但fuzzy的内存消耗是很大头的, 这个跟gc的直接关系可能不大, 除了我的优化以外, 可能有助于修复这个issue的pr有

- 4f7b02b36 reduce memory allocation by refactoring process structure (#17183)
- 8e7d832b8 malloc: optimizations (#17131)
- 588707ecc fix memory leak in flushAObjsForSnapshot (#17124)

可能需要 @ouyuanning  远宁哥评估一下

**Comment by jensenojs** [comment]
main上会继续跑big data query, 再观察一段时间

**Comment by jensenojs** [comment]
等待观察

**Comment by jensenojs** [comment]
等待1.2-dev上的pr合并

**Comment by Ariznawlll** [comment]
**1.2-dev
commit-id: 74f04ebd0334312ef17f364fb498daa61585c582**
<img width="938" alt="image" src="https://github.com/user-attachments/assets/5a1a7780-953a-439f-9646-debd37732041">

**main**
**commit-id: c1751aa204f5e21e1c247299b2a7a1b3366a991a**
<img width="940" alt="image" src="https://github.com/user-attachments/assets/774a558d-1e34-4050-b7fe-e414d2fe6e37">
性能回归正常。

**Comment by Ariznawlll** [comment]
**[0806] big data regression**

**commit: b52e7bc4e058d30bb369f813bd3619106a3d4b25**

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10250331351/job/28363600787
(INSERT INTO SELECT 10Y test)

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/049635f1-1349-47b9-97d4-015755896bc5">

性能变慢期间的profile情况（步骤：insert into table_with_com_pk_index_for_insert_1B）:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dzj%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240805%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221722886843000%22,%22to%22:%221722892843000%22%7D%7D%7D&schemaVersion=1&orgId=1

赛赛帮忙看下呀 @jensenojs 谢谢您

**Comment by jensenojs** [comment]
从pprof中看不出什么东西来, 简单地试着复现了一下也没成功, 后面再看看

**Comment by jensenojs** [comment]
QA反馈是一个稳定复现的bug, 明天找时间看看

<img width="1030" alt="企业微信截图_af582f7d-c1a0-4f79-a26e-aabd74b4634e" src="https://github.com/user-attachments/assets/831f06a6-e5e8-4be3-9239-8abc171b2c19">


https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dii%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%27mo-big-data-20240811%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221723406183000%22,%22to%22:%221723411822000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
<img width="604" alt="image" src="https://github.com/user-attachments/assets/2f772e84-5444-4519-8470-61d8baf3f2ff">

又消失了

**Comment by Ariznawlll** [comment]
**url：** https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10390075106/job/28770972278

**load data性能下降：**
<img width="935" alt="image" src="https://github.com/user-attachments/assets/d4f0cee9-4357-4524-af32-de6692f0d61a">

<img width="720" alt="image" src="https://github.com/user-attachments/assets/e40f4830-d588-437b-b185-5c3e151a3c27">
<img width="695" alt="image" src="https://github.com/user-attachments/assets/c3110439-1ddf-4951-84d9-6de39ba7e5b3">

内存使用情况：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22p_t%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%27mo-big-data-20240814%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221723651197000%22,%22to%22:%221723659061000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by Ariznawlll** [comment]
最近正常，先关掉
