### ISSUE TITLE
[Bug]: SQL报错lock table bind changed

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#17140]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

a4da5e955

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
aliyun QA
```

### Actual Behavior

SQL日志报错：
```
2024/06/24 07:23:07.257720 +0000 ERROR workbook/workbook.go:262 trace {"error": "Error 20702 (HY000): lock table bind changed", "elapsed": "52.684215ms", "rows": 0, "sql": "INSERT INTO `mo_cloud`.`workbook` (`id`,`account_id`,`sql_user`,`name`,`created_at`,`updated_at`) VALUES ('66d91d52-b052-4276-a327-4b66c9d460db','0190491f-f2d6-7611-ab1a-756515200697','admin','default','2024-06-24 07:23:07.205','2024-06-24 07:23:07.205')"}
```
发生时间为：0624 15:23:07 左右

### Expected Behavior

正常执行

### Steps to Reproduce

```Markdown
偶现
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by DanielZhangQD** [comment]
Hit in cloud dev env. Log: https://grafana.cn-dev.matrixone.tech/goto/vu4k4geIR?orgId=1

**Comment by iamlinjunhong** [comment]
cn 没有重启，但 tn 重启了，cn 与 tn 心跳没有失联，旧的 lock table bind 没有更新，导致后面报错 lock table bind changed。
正常报错。

2024-09-03 16:35:03.989 | {"level":"INFO","time":"2024/09/03 08:35:03.989283 +0000","name":"tn-service.lockservice","caller":"lockservice/lock_table_allocator.go:99","msg":"lock allocator start successfully","uuid":"33376565-3237-3162-3439-323631326537","version":1725352503989173495}



{"level":"INFO","time":"2024/09/03 14:50:23.430685 +0000","name":"cn-service.lockservice","caller":"lockservice/service.go:612","msg":"lock table bind changed, create new","uuid":"64303531-6161-6461-3264-343765396164","service":"172533401051185403964303531-6161-6461-3264-343765396164","new-bind":"0-6319305(6319305)-172531283696399131434633335-6434-3432-3232-633265376438-1725352503989173495","current":"0xc044cb25a0","new":"0xc044cb25a0"}
