### ISSUE TITLE
[Bug]: The result of mo extra column in desc table is different from mysql with auto_increment column.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17141]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8a3f70d86899b6815b35c98e2dc9e6402515e2e3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="722" alt="企业微信截图_17192998941113" src="https://github.com/matrixorigin/matrixone/assets/108530700/1233d7a3-54ec-4920-9f59-0bfdc7f1679c">

### Expected Behavior

<img width="779" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a052046b-53b1-43b0-b2ac-eea9ec574d40">

### Steps to Reproduce

```Markdown
DROP TABLE IF EXISTS emp;  
create table emp(
    empno int unsigned auto_increment COMMENT '雇员编号',
    ename varchar(15) COMMENT '雇员姓名',
    job varchar(10) COMMENT '雇员职位',
    mgr int unsigned COMMENT '雇员对应的领导的编号',
    hiredate date COMMENT '雇员的雇佣日期',
    sal decimal(7,2) COMMENT '雇员的基本工资',
    comm decimal(7,2) COMMENT '奖金',
    deptno int unsigned COMMENT '所在部门',
	primary key(empno)
) COMMENT='雇员表';
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @aressu1985 @Ariznawlll @sukki37 @daviszhen @ouyuanning

**Comment by Ariznawlll** [comment]
**commit:c1751aa204f5e21e1c247299b2a7a1b3366a991a** 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/41a1de71-434f-4931-89e6-e3812cf389f3">

验证通过
