### ISSUE TITLE
[Bug]: 对外表执行show create table报错

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#17154]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

994f3da6e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
aliyun dev和QA均有这个问题，稳定复现
```

### Actual Behavior

执行如下SQL建立外表
```
create external table extable1(n1 int)infile{"filepath"='/Users/federa/Workdir/20240624/extable.csv'} ;
```
执行如下SQL报错：
```
show create table from extable1;
```

### Steps to Reproduce

```Markdown
如上
```

### Additional information

外表文件：
[extable.csv](https://github.com/user-attachments/files/15981867/extable.csv)

**Comment by qingxinhome** [comment]
pr review中

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @xiaoshuwei @aressu1985 @sukki37 @daviszhen

**Comment by heni02** [comment]
confirm,closed
main:3d6a534dfbfe043d3b7162e6c8d4916cac29bc34
1.2-dev:061391f6038f61e78af2a1e06178c684edfc5805
mysql> create external table ex_table_15(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255))infile{"filepath"='/Users/heni/test_data/ex_table_sep_1.csv'} fields terminated by '|' enclosed by '' lines terminated by '\n';
Query OK, 0 rows affected (0.03 sec)

mysql> show create table ex_table_15;
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ex_table_15 | CREATE EXTERNAL TABLE `ex_table_15` (
  `clo1` TINYINT DEFAULT NULL,
  `clo2` SMALLINT DEFAULT NULL,
  `clo3` INT DEFAULT NULL,
  `clo4` BIGINT DEFAULT NULL,
  `clo5` TINYINT UNSIGNED DEFAULT NULL,
  `clo6` SMALLINT UNSIGNED DEFAULT NULL,
  `clo7` INT UNSIGNED DEFAULT NULL,
  `clo8` BIGINT UNSIGNED DEFAULT NULL,
  `col9` FLOAT DEFAULT NULL,
  `col10` DOUBLE DEFAULT NULL,
  `col11` VARCHAR(255) DEFAULT NULL,
  `col12` DATE DEFAULT NULL,
  `col13` DATETIME DEFAULT NULL,
  `col14` TIMESTAMP NULL DEFAULT NULL,
  `col15` BOOL DEFAULT NULL,
  `col16` DECIMAL(5,2) DEFAULT NULL,
  `col17` TEXT DEFAULT NULL,
  `col18` VARCHAR(255) DEFAULT NULL,
  `col19` VARCHAR(255) DEFAULT NULL,
  `col20` VARCHAR(255) DEFAULT NULL
) INFILE{'FILEPATH'='','COMPRESSION'='','FORMAT'='','JSONDATA'=''} FIELDS TERMINATED BY '|' ENCLOSED BY '' LINES TERMINATED BY '\n' |
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.10 sec)

mysql> select * from ex_table_15 limit 4;
+------+--------+-------------+----------------------+------+-------+------------+----------------------+--------+--------+-------------------------------------------------------+------------+---------------------+---------------------+-------+--------+------------------------------------------+-----------------------------------------------------+--------------------------------------------------+-----------------------------------------------------------+
| clo1 | clo2   | clo3        | clo4                 | clo5 | clo6  | clo7       | clo8                 | col9   | col10  | col11                                                 | col12      | col13               | col14               | col15 | col16  | col17                                    | col18                                               | col19                                            | col20                                                     |
+------+--------+-------------+----------------------+------+-------+------------+----------------------+--------+--------+-------------------------------------------------------+------------+---------------------+---------------------+-------+--------+------------------------------------------+-----------------------------------------------------+--------------------------------------------------+-----------------------------------------------------------+
|  -62 |   5807 | -1889972806 |  7769629822818484334 |  154 |  8113 | 2658450361 | 14999475422109240954 | 3.4365 |  5.559 | N?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01234567 | 4149-04-30 | 5732-08-07 00:00:00 | 1975-09-09 23:59:59 | true  | 602.53 | I|G;KL/MN?OPQR.STU-_+=VWXYZabcdefghi     | HI|G;KL/MN?OPQR.STU-_+=VWXYZa                       | +=VWXYZab                                        | G;KL/MN?OPQR.STU-_+=VWX    YZabcdefghigkl                 |
|   91 |  19514 |  -179559641 |  1234138289513302348 |  122 | 44115 |  625429347 |  6204822205090614210 | 7.2914 | 6.5836 | R.STU-_+=VWXYZabcdefghigklmno                         | 2865-02-22 | 9976-06-04 00:00:00 | 1985-01-12 23:59:59 | false | 878.09 | HI|G;KL/MN?OPQR.STU-_+=VWXYZabcd         | QR.STU-_+=VWXYZabcdefghigklmnopqrstu                | R.STU-_+=VWXYZabcdefghigklmnopqrstuvw            | -_+=VWXYZabcdefgh世界和平igklmnopqr                       |
|   33 |   4300 |  1287532466 | -3038428195984464330 |  104 |  9233 | 3258037690 | 17397115807377870895 | 1.1559 | 6.5635 | +=VWXYZabcdefghigklmnopqrstuvwxyz012                  | 6316-02-16 | 3647-01-21 23:59:59 | 2034-02-10 00:00:00 | true  | 439.95 | EF|GHI|G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh | OPQR.STU-_+=VWXYZa                                  | U-_+=VWXYZabcdefghigklmno                        | .STU-_+=VWXYZab                                           |
|  121 | -22564 |  1124555433 | -1681456935776973509 |  141 | 14546 |  849972079 |  3143191107533743301 | 4.0199 | 1.1732 | OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz           | 9948-05-08 | 6216-12-30 00:00:00 | 2011-03-10 00:00:00 | false | 428.14 | U-_+=VWXYZabcdefghigklmnopqrstuvwxy      | L/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012 | /MN?OPQR.STU-_+=VWXYZa    bcdefghigklmnopqrstuvw | ABCDEF|GHI|G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstu |
+------+--------+-------------+----------------------+------+-------+------------+----------------------+--------+--------+-------------------------------------------------------+------------+---------------------+---------------------+-------+--------+------------------------------------------+-----------------------------------------------------+--------------------------------------------------+-----------------------------------------------------------+
4 rows in set (0.03 sec)

**Comment by xiaoshuwei** [comment]
close by heni

**Comment by xiaoshuwei** [comment]
close by heni
