### ISSUE TITLE
[Bug]: [big data test]delete from a 100million table takes a long time to execute.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17152]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9f1c2dfa908bc08f58cbf59dcb14b4f3bdd16a1c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://qgithub.com/matrixorigin/mo-nightly-regression/actions/runs/9640573308/job/26607815617

执行了大约5h还没执行完，因为设置的时间是5h，所以异常退出了。
<img width="1391" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/e7b6fe5b-4ec7-449e-a9e7-acf4e9e77ca1">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22lDW%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240624%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719210171000%22,%22to%22:%221719293841000%22%7D%7D%7D&schemaVersion=1&orgId=1

对应时间点的profile：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240624%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719243802000%22,%22to%22:%221719261279000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big-data-test on tke.

测试场景（数据量1亿）：
table schema：

create table if not exists big_data_test.table_with_pk_index_for_write_100M( id bigint primary key, col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3), key(col3), unique key(col4) );

delete from big_data_test.table_with_pk_index_for_write_100M where id <= 1000000
```

**Comment by Ariznawlll** [comment]
1.2-dev： 2545ce4c726d5c9e64f7a6b8307b5da0e6da950d
job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9660414495

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%222C-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240625%5C%22%7D%20%7C%3D%20%60delete%20from%20big_data_test.table_with_pk_index_for_write_100M%20where%20id%20%3C%3D%201000000%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

profile:https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cg0%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240625%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
还没看

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/15501
@jensenojs will help on it

**Comment by jensenojs** [comment]
没看

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
重构operator

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
在最新的main的`1d70e220fe155`上测试, 如下的sql即可复现卡住的问题. 

```sql
drop database if exists jensen; 
create database jensen;
use jensen;
drop table if exists jensen;
create table jensen(a int primary key, b int);
insert into jensen select result, result from generate_series(1,3276800) g;
```

卡住的原因是
```
{"level":"ERROR","time":"2024/09/04 10:35:16.898673 +0000","caller":"logservicedriver/appender.go:97","msg":"append failed: internal error: message body 170590573 is too large, max is 104857600"}
```

<img width="1809" alt="image" src="https://github.com/user-attachments/assets/86a826d1-ef22-46d7-bf64-6d735a68208c">

在调整tn/log的rpc的limit之后可以绕开这个问题, 请存储的同事帮忙fix之后再看看这个问题吧
```toml
// log
[logservice.rpc]
max-message-size = "500M"

// tn
[tn.rpc]
max-message-size = "500M"
```

**Comment by jensenojs** [comment]
昨天的big data test 也依然有这个问题 : https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10685465952/job/29635505459

```bash
commit c03cbb087cafdf71c7ea076d082630cfb9cf830c
Author: reusee <reusee@gmail.com>
Date:   Tue Sep 3 22:49:56 2024 +0800

    fileservice: do disk cache eviction after loading and before writing files (#18394)
    
    more eviction
    
    Approved by: @fengttt
```

看pprof现在cpu并没有在跑. 

<img width="1604" alt="image" src="https://github.com/user-attachments/assets/377e5343-2fa8-436d-a0ff-0431e26c555a">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%225RM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240903%5C%22%7D%20%7C%3D%20%60logservicedriver%2Fappender%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725439733700%22,%22to%22:%221725444261766%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
验证fix了, 辛苦QA有时间再看一下
- https://github.com/matrixorigin/matrixone/pull/18541

**Comment by Ariznawlll** [comment]
再观察一下

**Comment by Ariznawlll** [comment]
**最新一次的测试结果**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10794221436/job/29955185931

**执行超过3h**
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/444d65ea-002d-4237-95f0-2ceb481dce50">

**longrunning对应的log:** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22zA-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240910%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221726028589000%22,%22to%22:%221726039389000%22%7D%7D%7D&schemaVersion=1&orgId=1

**longrunning对应的profile**
**[long-running.tar.gz](https://github.com/user-attachments/files/16960678/long-running.tar.gz)**

**Comment by jiangxinmeng1** [comment]
依赖 https://github.com/matrixorigin/matrixone/issues/18520

**Comment by jiangxinmeng1** [comment]
依赖 https://github.com/matrixorigin/matrixone/issues/18520

**Comment by jiangxinmeng1** [comment]
依赖 https://github.com/matrixorigin/matrixone/issues/18520

**Comment by jiangxinmeng1** [comment]
修好了

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
10月10日测试结果：

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/9e823882-4766-499c-9ba6-dcab96cbc90d">

测试通过✅
