### ISSUE TITLE
[Performance]: improve compound primary key insert

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#17165]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

在针对复合键的insert into select做内存优化的场景发现, 对于复合键的处理的耗时严重
- https://github.com/matrixorigin/matrixone/pull/17161

***
优化前 : 
<img width="1857" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/7ea26a5b-ccaf-40e1-b3a9-2ce055395f67">

优化后 : 
<img width="1547" alt="企业微信截图_976bc5a8-a0ee-48dc-b34b-d067b0465500" src="https://github.com/matrixorigin/matrixone/assets/56761542/0a0a0f95-158a-4072-b208-a2384d8d614d">

***

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by ouyuanning** [comment]
DML重构后，这个需求不再存在了
