### ISSUE TITLE
[Bug]: 1.2-dev standalone: tpcc 100ware 1000threads reported connection Communications link failure

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17177]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

967f3e7c7a35d6ffb490497aa20393430ec1ac47

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9681649897/job/26712910531
三个时间报错：2024-06-27 06:20:24，2024-06-27 06:21:05，2024-06-27 06:21:08
<img width="1058" alt="企业微信截图_98fea5c6-322b-488b-b6b6-3922f2bbd169" src="https://github.com/matrixorigin/matrixone/assets/113406637/89a24e5d-99d3-45c3-a96e-644618a6cc24">

06:20的profile：
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a2-e838-7d09-9c91-a47834887922.gz](https://github.com/user-attachments/files/16007116/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a2-e838-7d09-9c91-a47834887922.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a2-72ff-7236-94ec-8147009452c6.gz](https://github.com/user-attachments/files/16007118/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a2-72ff-7236-94ec-8147009452c6.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a2-ea36-7e5e-a73d-0735ced53b60.gz](https://github.com/user-attachments/files/16007119/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a2-ea36-7e5e-a73d-0735ced53b60.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a2-7515-7d7d-8ebf-9e7db8036957.gz](https://github.com/user-attachments/files/16007120/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a2-7515-7d7d-8ebf-9e7db8036957.gz)

06:21的profile：
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a3-d28e-70e7-9845-48c6494cb689.gz](https://github.com/user-attachments/files/16007150/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a3-d28e-70e7-9845-48c6494cb689.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a3-5d84-7ba2-b19c-aed658951f9b.gz](https://github.com/user-attachments/files/16007152/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_019056a3-5d84-7ba2-b19c-aed658951f9b.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a3-d471-7ef4-a0e9-49c178dc15e5.gz](https://github.com/user-attachments/files/16007153/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a3-d471-7ef4-a0e9-49c178dc15e5.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a3-5f4f-768c-89ba-de0e15fb96d1.gz](https://github.com/user-attachments/files/16007154/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_019056a3-5f4f-768c-89ba-de0e15fb96d1.gz)

mo log:
[1.2_0627.tar.gz](https://github.com/user-attachments/files/16007269/1.2_0627.tar.gz)

### Steps to Reproduce

```Markdown
stanalone regression tpcc100ware 1000threads
```

**Comment by heni02** [comment]
重跑没有出现，挪到1.2.2解决
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9681649897/job/26739515979
<img width="949" alt="企业微信截图_c295998e-9e31-4569-aaa3-25291821a656" src="https://github.com/matrixorigin/matrixone/assets/113406637/faf8040a-6ecd-40a8-a6bb-a79f3fc1c33c">

**Comment by volgariver6** [comment]
related with https://github.com/matrixorigin/matrixone/issues/17182
wait for it done

**Comment by w-zr** [comment]
这个pr已经merge了。等测试。

**Comment by XuPeng-SH** [comment]
should be fixed

**Comment by heni02** [comment]
confirm, closed
commit:2ab791abf30c0810a063b6fddcd01c820a73c5cd
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9817405994/job/27108764647
