### ISSUE TITLE
[Bug]: [date 6.26]tke regression: tpch1T 4cn some querys performance down about one time

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17185]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e975b6dc9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9681659361/job/26739599474
Q1超过60s未返回
<img width="1318" alt="企业微信截图_6387efdd-c7fa-4e97-8fae-f8c1c05e48f5" src="https://github.com/matrixorigin/matrixone/assets/113406637/7b5ce786-8132-4e48-9c9b-11054dd3bd38">
Q3，Q9，Q10基本慢了一倍
<img width="814" alt="企业微信截图_c9ed0ede-ec86-4c7c-b1f5-ac13676d86d2" src="https://github.com/matrixorigin/matrixone/assets/113406637/51b448b9-d865-4492-9711-649f0e8743cb">
<img width="819" alt="企业微信截图_0aa90d44-55b5-42ce-9d63-86f5a1e5cdf7" src="https://github.com/matrixorigin/matrixone/assets/113406637/762292bb-7478-4e43-bd46-817e17ff1e02">
<img width="818" alt="企业微信截图_a6989536-8f43-4804-a863-2d3127b792a2" src="https://github.com/matrixorigin/matrixone/assets/113406637/c0d3fcd6-359b-4d1c-86b2-f4b5165d668d">
其他query也有小幅性能下降，具体见：
http://grafana.matrixorigin.cn:31080/d/tBWw-hxIz/tpch_1000_4cn?orgId=1

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hhC%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-e975b6dc9-20240626%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719427657743%22,%22to%22:%221719470857743%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke 4cn 1T
```

**Comment by badboynt1** [comment]
最新的daily已经没有问题了

**Comment by heni02** [comment]
confirm,closed
main commit:7befc6460
<img width="1838" alt="企业微信截图_f8f96c3a-3fe3-4c02-8cf1-5809e20bbc3f" src="https://github.com/matrixorigin/matrixone/assets/113406637/cff9522c-951b-4773-919a-23165fb40c5f">
http://grafana.matrixorigin.cn:31080/d/tBWw-hxIz/tpch_1000_4cn?orgId=1
