### ISSUE TITLE
[Bug]: 1.2-dev tke regression: tpcc 500ware 1000threads cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17201]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

79cb255

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9699675135/job/26776642567
<img width="1317" alt="企业微信截图_e8446189-623a-4690-a273-533731d96f43" src="https://github.com/matrixorigin/matrixone/assets/113406637/f6a77432-6541-4b56-a48d-7ffa89e6e639">
<img width="1692" alt="image" src="https://github.com/matrixorigin/matrixone/assets/113406637/5bd1e34e-91eb-4975-a18d-4a365a95e7ca">

mem使用情况：
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-branch-reg-79cb255&from=1719506343594&to=1719537207113

profile：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22LZI%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-79cb255%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-7xdvq%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221719522189953%22,%22to%22:%221719527233066%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke tpcc 500ware 1000threads
```

**Comment by jiangxinmeng1** [comment]
依赖 https://github.com/matrixorigin/matrixone/issues/17182

**Comment by XuPeng-SH** [comment]
too many delta loc issue is done and if it still oom later, it should be a different problem.

**Comment by heni02** [comment]
confirm, closed
1.2-dev commit:a0f75f627c656d888d3af43644af6d6531c6c013
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9828780213/job/27135246854
