### ISSUE TITLE
[Bug]: MORPC Illegal State

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17223]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.2-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

always returns Illegal State error on a speciel connection

### Steps to Reproduce

```Markdown
run tpcc and restart tn.
```

**Comment by aressu1985** [comment]
fixed
