### ISSUE TITLE
[Bug]: mo hung after tn was killed for servals times during tpcc long runnig test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17226]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

226b7a6

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C  64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

during tpcc longrunning test, if tn was killed for serveral times, mo sometimes will be hung. 

the mo goroutine:
[goroutine.log](https://github.com/user-attachments/files/16047212/goroutine.log)
[goroutine_1.log](https://github.com/user-attachments/files/16047215/goroutine_1.log)

<img width="1290" alt="企业微信截图_efb8e3ea-be9b-479c-bad7-b1d8a8dbae0b" src="https://github.com/matrixorigin/matrixone/assets/47846308/e9f76cf9-0354-415c-9a46-dbd44cfef796">

### Steps to Reproduce

```Markdown
ad desc in issue
```

**Comment by aressu1985** [comment]
@m-schen has get the root caused, and will fixed this

**Comment by m-schen** [comment]
原因是

现在cn重连tn前，会通过关闭顶层上下文的方式来停止所有正在运行的pipeline，并一直等到全部都被关闭。

目前还不清楚发生了什么导致pre-insert算子所在的pipeline无法感知到context done,它的上下文似乎并不继承于顶层上下文。

不排除
https://github.com/matrixorigin/matrixone/pull/17257
该pr可以解决这个问题的可能，因为可能有某个地方用乱了context导致。

还得定位。

**Comment by m-schen** [comment]
确实有scope构建出来（run之前，compile结束）时，
其process不受query context的管理，明天应该可以定位和修改完一部分。

**Comment by m-schen** [comment]
目前定位到的，在Compile结束后
1. merge -> merge block
2. projection -> projection -> projection -> pre insert -> insert
3. merge -> output

这几种情况出现了ctx的问题。

**Comment by m-schen** [comment]
上面的分析都错了，debug代码写得有问题，下午会更新新的结论。

**Comment by m-schen** [comment]
原因阐述如下：

1. 
当前分支（1.2, main)触发cn tn之间的重连动作时，
首先会暂停所有新查询 / 新事务的开启，然后通过杀掉查询的context迫使正在跑的查询结束。
全部查询都停下后，再进行重连动作。

2.
由于当前Compile结构所提供的context和cancel方法不对应，cancel方法无法杀死这个context.
这个问题导致pipeline无法被直接停下，因此步骤1描述的停止查询动作退化成了“等待所有查询自然结束”。

3.
insert语句 与 update语句等，在存在自增列的情况下，可能会额外触发一个动作
“开启一个新事务去批量申请自增列cache”。如同步骤1所说，此时暂停了所有新事务的开启，因此这个动作被阻塞。
在这种情况下，这个insert / update语句无法正常结束。

4.
由于2和3的原因，导致重连动作hung在“等待查询结束”这一步骤。因此hung住。

**Comment by m-schen** [comment]
碰到了些逻辑上的死锁，需要考虑怎么解决。

1. 当一个查询碰到失败且retry，在过程中会生成一个新的Compile结构去rerun这个query.由于重连期间会阻止Compile的生成，因为retry会卡死在这一步，这类查询目前也无法正常退出（即使context done可以被正常感应到）。

**Comment by m-schen** [comment]
https://github.com/m-schen/matrixone/tree/fix-process-cancel

没改完，具体进度见该分支。

**Comment by m-schen** [comment]
还在改。

**Comment by m-schen** [comment]
还在改，分支能启动了，但会报各种奇怪的错误。没法正常运行。

**Comment by m-schen** [comment]
我破防了- - 改完后碰到了非常多context中找不到各种存储的值的问题。

**Comment by m-schen** [comment]
找到context中找不到值的原因了，
太早创建出query context, 
导致后面往top context中with value新增的值无法被找到。

**Comment by m-schen** [comment]
先尝试合并一部分关于process特别乱的问题，不然这个context很难改。

**Comment by m-schen** [comment]
main冻结了，等这个合进去后续继续工作。

**Comment by m-schen** [comment]
继续工作中

**Comment by m-schen** [comment]
still working.

**Comment by m-schen** [comment]
man, what Can I say. 970多个用ctx的地方要改。

**Comment by m-schen** [comment]
没改完，服务起不来了，不知道说什么，有兴趣可以看分支

**Comment by m-schen** [comment]
服务能跑了，原因是某些结构需要实现a接口，但是用a接口的地方写的any，这太难发现了。bad。如图：
<img width="461" alt="image" src="https://github.com/user-attachments/assets/4ce61d37-2ba4-488e-8c3d-be4a87e01232">
这种情况最好加上蓝框里的代码，可以直接在编译的时候报错。


希望明天可以有好的进展。

**Comment by m-schen** [comment]
进度还行。

还有点panic的问题，和autocommit以及 cases/optimistic/conflict_transation.sql有关。处理后就可以提pr了

**Comment by m-schen** [comment]
剩下几个多cn下的用例跑不过，在发到远端节点后发生了一些panic问题。

**Comment by m-schen** [comment]
等pr跑过以及明天需要测一下tpcc等，今天regression环境有问题，镜像拉不起来。

**Comment by m-schen** [comment]
等pr合并。

**Comment by m-schen** [comment]
等pr合并

**Comment by m-schen** [comment]
晚上看看daily情况，如果daily稳定没事的话，明天转测。

**Comment by m-schen** [comment]
pr有点问题，正在找问题。

**Comment by m-schen** [comment]
提了新pr 等合并 https://github.com/matrixorigin/matrixone/pull/17950

**Comment by m-schen** [comment]
已修复，可以在main分支上验证该问题。

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed

**Comment by xzxiong** [comment]
mark:
本issue 仅修复 main （version 2.0)分支，对 1.2.3+ 版本无相关修复。
