### ISSUE TITLE
[Bug]: sysbench 100000 random points has different plan between 1.2-dev and main

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#17227]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The QPS of sysbench 100000 random points in 1.2-dev is about 2000 while it is 20000+ in main.

The difference in performance comes from a different execution plan
main is using the index while the 1.2-dev is not using the index.

### Steps to Reproduce

```Markdown
1.2-dev daily:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9727754933/job/26852448485

main daily:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9732772679/job/26864556992
```

**Comment by badboynt1** [comment]
sysbench random points已经定位到存在stats没有更新导致执行计划错误的问题。
接下来需要排查为什么stats没有更新

**Comment by badboynt1** [comment]
现在定位到，sysbench insert十万行数据以后，dn没有落盘，导致stats无法更新
继而导致prepare语句的时候没有走索引。
所以要么是需要强制落盘，要么就按不走索引的执行计划来跑。跑单流程的时候，不走索引也有8000tps，但是现在有别的bug导致tps很低。

**Comment by XuPeng-SH** [comment]
prepare的场景怎么办？
