### ISSUE TITLE
[Bug]: ut failed. TestReadWithSpecialShard

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#17258]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0701-debug-3657

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
https://github.com/matrixorigin/matrixone/actions/runs/9744489230/job/26890256414?pr=17255
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/60595215/6d85bc47-c049-4dd0-94af-fbe4c33b4526)

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9744489230/job/26890256414?pr=17255
```

**Comment by Ariznawlll** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/9792640591/job/27038924761?pr=17326

**Comment by zhangxu19830126** [comment]
dup with #16683
