### ISSUE TITLE
[Bug]: 恢复快照报错

### ISSUE THREAD

**Issue by PHK-20** [matrixorigin/matrixone#17269]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

main

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:macOS
- Others:
```

### Actual Behavior

<img width="1336" alt="企业微信截图_a227d87c-7d3d-4d09-985a-27e80c548d04" src="https://github.com/matrixorigin/matrixone/assets/38491207/d9695ae4-c4dd-4a35-9cbf-8b5f2a716a62">

恢复快照报错

### Steps to Reproduce

```Markdown
1、create snapshot test_1 for account `01905e5b-88de-7ff0-90da-e95b269d00eb` 
2、restore account `01905e5b-88de-7ff0-90da-e95b269d00eb` from snapshot test_1;
```

**Comment by triump2020** [comment]
@PHK-20   Fixed.

**Comment by Ariznawlll** [comment]
**commit:**
<img width="245" alt="image" src="https://github.com/user-attachments/assets/3fccc86e-3183-42a5-82b3-2b234277cc4a">

<img width="748" alt="image" src="https://github.com/user-attachments/assets/49207c6f-5225-453f-a4ea-bad5649cdfd5">

验证通过。
