### ISSUE TITLE
[Bug]: [128 regression] tpch 1t test oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17263]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

14f4593d87c6926c7490ec7dffaacaa965840ee2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9739981415/job/26876342011

<img width="1384" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f108f0d3-1414-47cc-9b7b-3910c01cb00c">

128 oom记录：
<img width="1607" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/f8ada1d8-144a-4628-82b7-71b1c454f93c">

### Steps to Reproduce

```Markdown
trigger 128 regression.
```

**Comment by badboynt1** [comment]
这两天没有oom了 继续观察

**Comment by badboynt1** [comment]
在tpcc和sysbench之前跑的tpch1T都没有oom

**Comment by Ariznawlll** [comment]
降级观察

**Comment by Ariznawlll** [comment]
没出现了，先关掉
