### ISSUE TITLE
[Bug]: ut TestKill fail

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#17280]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="850" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/49f61d0b-c214-4100-a37a-a0e2816432ea">

<img width="932" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/3778a75c-fbfa-4a73-9a8f-abdb12c898ca">

<img width="808" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/ba833ce3-6fc3-4db4-902d-b767a750193b">

<img width="818" alt="image" src="https://github.com/matrixorigin/matrixone/assets/39627130/3ff35882-3d28-4e04-8127-6002a1bc95d8">

### Steps to Reproduce

```Markdown
https://productionresultssa16.blob.core.windows.net/actions-results/e41be863-82f7-4b38-bf5c-d5aaf35ae4c9/workflow-job-run-6170141e-b114-598b-fe26-767dc7745c7d/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-02T12%3A49%3A12Z&sig=OjSI%2FgJNUDoSjIzTwpBg%2BvvAW3zsQiA5uDHfRJEmoek%3D&ske=2024-07-02T23%3A37%3A27Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-02T11%3A37%3A27Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-02T12%3A39%3A07Z&sv=2023-11-03
```

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
it was fixed。 最新的main已经修改了TestKill的实现方法。
