### ISSUE TITLE
[Bug]: [date 7.2] standalone regression: sql execute cost 37min caused sysbench random_points executed for more than 40 minutes 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17295]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

580f61afcfd273b2e5b2326e432f125575a5b30

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9762151783/job/26944918014
<img width="1226" alt="企业微信截图_ffd4fe2a-93fa-49a8-b8a2-06137bb11e44" src="https://github.com/matrixorigin/matrixone/assets/113406637/8f53649f-4483-43e6-bd0b-604691548863">
执行时间段：05:17到05:57

mo log：
<img width="1370" alt="企业微信截图_dc79785a-5eab-489b-aeac-125a13a96b97" src="https://github.com/matrixorigin/matrixone/assets/113406637/62826b6f-f3b9-46ec-859d-b14d9ad841bd">
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-580f61a-20240702-214653.log%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719956429613%22,%22to%22:%221719959760376%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
sysbench10w random_points 1000threads test
```

**Comment by heni02** [comment]
06：56分环境清理重新启动，无法登陆环境查询statement_info表中对应的sql，只能从目前已有的日志定位了

**Comment by m-schen** [comment]
我在日志里没有找到线索，不知道怎么分配这个issue。时间：2024.07.03 15:03

**Comment by zhangxu19830126** [comment]
等下次出现，保留数据环境，导入trace数据，分析哪儿慢了

**Comment by heni02** [comment]
等待复现，先降级s1

**Comment by heni02** [comment]
很久没有复现，先关闭
