### ISSUE TITLE
[Bug]: [date 7.2]tke regression: tpch1T Q18 reported error Invalid alloc size 1679884288

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17293]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

580f61afcfd273b2e5b2326e432f125575a5b309

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9762956928/job/26947756712
<img width="1026" alt="企业微信截图_2aa10b8a-3f38-4040-9fdc-9cf83112e724" src="https://github.com/matrixorigin/matrixone/assets/113406637/119530f8-a822-41d0-9d5c-e5b054c8b6d2">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22_i2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-580f61afc-20240702%5C%22%7D%20%7C%3D%20%60Invalid%20alloc%20size%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221719938621237%22,%22to%22:%221719939012482%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke tpch1T q18
```

**Comment by heni02** [comment]
1.2分支也有相同的问题
commit：330ac12
<img width="1139" alt="企业微信截图_a4885e69-a345-43e1-b39d-a9d42adf7140" src="https://github.com/matrixorigin/matrixone/assets/113406637/7fd4f537-b4ef-4560-98ad-101226f9bae0">

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm，closed
commit：b01bc0969
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9859053435/job/27222735779
