### ISSUE TITLE
[Bug]: cluster level snapshot cannot restore acc01 to new account acc02.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

580f61afcfd273b2e5b2326e432f125575a5b309

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1377" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/abf4df55-78f3-414a-9848-85c4aa71d8de">

### Steps to Reproduce

```Markdown
drop account if exists acc01;
create account acc01 admin_name = 'test_account' identified by '111';
drop account if exists acc02;
create account acc02 admin_name = 'test_account' identified by '111';

-- @session:id=1&user=acc01:test_account&password=111
drop database if exists acc_test01;
create database acc_test01;
use acc_test01;
drop table if exists s3t;
create table s3t (col1 int, col2 int, col3 int, primary key(col1, col2));
insert into s3t select result, 2, 12 from generate_series(1, 30000, 1) g;
select count(*) from s3t;
select sum(col1) from s3t;
select avg(col1) from s3t;
select count(col3) from s3t where col1 > 1000;
alter table s3t add column col4 int after col2;
-- @session

drop snapshot if exists sp01;
create snapshot sp01 for cluster;
-- @ignore:1
show snapshots;

-- @session:id=1&user=acc01:test_account&password=111
use acc_test01;
insert into s3t values (300001, 34, 23, 1);
select count(*) from s3t;
-- @session

restore account acc01 from snapshot sp01 to account acc02;

-- @session:id=3&user=acc02:test_account&password=111
show databases; -->出错位置（应该看到恢复后的数据，现在没有）
```

**Comment by Ariznawlll** [comment]
**view的恢复也阻塞在这里，麻烦钊哥一起看一下 @YANGGMM** 
<img width="1313" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/dd633451-3c15-46df-9716-70c764503315">

drop account if exists acc01;
create account acc01 admin_name = 'test_account' identified by '111';
drop account if exists acc02;
create account acc02 admin_name = 'test_account' identified by '111';

-- @session:id=1&user=acc01:test_account&password=111
-- create simple view
drop database if exists test;
create database test;
use test;
drop table if exists table01;
create table table01 (col1 int, col2 decimal(6), col3 varchar(30));
insert into table01 values (1, null, 'database');
insert into table01 values (2, 38291.32132, 'database');
select count(*) from table01;

drop view if exists v01;
create view v01 as select * from table01;
show create view v01;
select * from v01;
-- @session

drop snapshot if exists sp100;
create snapshot sp100 for cluster;

-- @session:id=1&user=acc01:test_account&password=111
drop view v01;
-- @session

restore account acc01 from snapshot sp100 to account acc02;

-- @session:id=2&user=acc02:test_account&password=111
use test;          -->此处报错，应该恢复成功
select * from v01;         -->此处应该查找到v01的内容

**Comment by YANGGMM** [comment]
好的

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**commit: 5b822ddc5d6eeb535c45d58df4e85cae372db95e**
场景一：
<img width="1865" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fc95479d-7ab4-433c-9d6d-e7f60e8611da">

场景二：
<img width="1736" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/c11aeea6-2ee4-414a-b375-bca60f56cdd5">

测试通过
