### ISSUE TITLE
[Bug]: tpcc 500ware 500threads performance down about 30%

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17331]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ae8f052fe90c85c90463a766db2fabe3c3bbd8ba

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke tpcc 500ware 500threads performance 7.4号性能下降
<img width="1007" alt="企业微信截图_1ed7b25d-9dd3-454e-9c58-59adae066ae7" src="https://github.com/matrixorigin/matrixone/assets/113406637/c1a8a839-0cb0-4d6f-8fdc-998e03e52476">
http://grafana.matrixorigin.cn:31080/d/SFris6q4zq/tpcc?orgId=1

经过二分怀疑两个pr导致性能下降：
<img width="1299" alt="企业微信截图_04ac1ab9-60ef-440b-9af7-d14c7b35303d" src="https://github.com/matrixorigin/matrixone/assets/113406637/6b61e5f0-51a1-45cc-9441-9962e05e0e0d">

revert掉这两个pr，性能为11000+：
<img width="1225" alt="企业微信截图_bf623683-be3f-42c0-9ab0-5fc2605c2d41" src="https://github.com/matrixorigin/matrixone/assets/113406637/3921043a-21eb-4ba2-879e-8123b0090958">
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9789767752/job/27030498503

单读跑（包含这两个pr），性能9000+
<img width="714" alt="企业微信截图_f3c68908-6aaf-4894-baae-1251c7e75853" src="https://github.com/matrixorigin/matrixone/assets/113406637/1946b43f-6d99-4d00-b968-bf651ea3a5a6">
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9791794067/job/27036999282

### Steps to Reproduce

```Markdown
tke tpcc 500ware 500threads test
```

**Comment by badboynt1** [comment]
最新的main分支 跑tpcc看起来性能似乎已经恢复

**Comment by badboynt1** [comment]
应该只是波动

**Comment by heni02** [comment]
confirm,closed
commit:b01bc0969ebb98f5d831d9f79c1c0311b27b9a7a
<img width="1874" alt="企业微信截图_bc52baee-aee6-4308-b1dc-73c4c262663a" src="https://github.com/matrixorigin/matrixone/assets/113406637/c7aea04a-1b03-4296-b786-d1ee36f3f621">
