### ISSUE TITLE
[Bug]: [date 7.5] big data regression: sql 'update big_data_test.table_with_pk_index_for_write_100M set col3 = col3 + 1' report stream closed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17340]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

78e277a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9793720210/job/27058593271 (Quries 1y->1y dml test)

<img width="1380" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a9981504-1a5e-4575-8cd7-647934b734ab">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%223Wy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240704%5C%22%7D%20%7C%3D%20%60stream%20closed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

profile: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22LoJ%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240704%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221720123332000%22,%22to%22:%221720126932000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big data test on tke.

update 涉及的表数据规模： 1亿

table schema：
create table if not exists big_data_test.table_with_pk_index_for_write_100M( id bigint primary key, col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3), key(col3), unique key(col4));
```

**Comment by zhangxu19830126** [comment]
@badboynt1 麻烦看一下是不是之前和提前结束的问题

**Comment by badboynt1** [comment]
只有join才有提前结束的说法，update里面是不会提前结束的。
这个问题我看了相关的测试，所有超大数据量的dml，从来没有成功过，要么跑超时，要么oom挂掉，要么有奇怪的报错，比如这里的stream closed。  本质上还是要优化dml才行

**Comment by badboynt1** [comment]
CREATE TABLE `table_with_pk_index_for_write_100m` (
  `id` BIGINT NOT NULL,
  `col1` TINYINT DEFAULT NULL,
  `col2` SMALLINT DEFAULT NULL,
  `col3` INT DEFAULT NULL,
  `col4` BIGINT DEFAULT NULL,
  `col5` TINYINT UNSIGNED DEFAULT NULL,
  `col6` SMALLINT UNSIGNED DEFAULT NULL,
  `col7` INT UNSIGNED DEFAULT NULL,
  `col8` BIGINT UNSIGNED DEFAULT NULL,
  `col9` FLOAT DEFAULT NULL,
  `col10` DOUBLE DEFAULT NULL,
  `col11` VARCHAR(255) DEFAULT NULL,
  `col12` DATE DEFAULT NULL,
  `col13` DATETIME DEFAULT NULL,
  `col14` TIMESTAMP NULL DEFAULT NULL,
  `col15` BOOL DEFAULT NULL,
  `col16` DECIMAL(16,6) DEFAULT NULL,
  `col17` TEXT DEFAULT NULL,
  `col18` JSON DEFAULT NULL,
  `col19` BLOB DEFAULT NULL,
  `col20` BINARY(255) DEFAULT NULL,
  `col21` VARBINARY(255) DEFAULT NULL,
  `col22` VECF32(3) DEFAULT NULL,
  `col23` VECF32(3) DEFAULT NULL,
  `col24` VECF64(3) DEFAULT NULL,
  `col25` VECF64(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `col4` (`col4`),
  KEY `col3` (`col3`)
)


mysql> select count(*) from table_with_pk_index_for_write_100M ;
+-----------+
| count(*)  |
+-----------+
| 100000000 |
+-----------+


mysql> explain update big_data_test.table_with_pk_index_for_write_100M set col3 = col3 + 1;
+---------------------------------------------------------------------------------------------------+
| AP QUERY PLAN ON MULTICN(16 core)                                                                 |
+---------------------------------------------------------------------------------------------------+
| Plan 0:                                                                                           |
| Sink                                                                                              |
|   ->  Lock                                                                                        |
|         ->  Project                                                                               |
|               ->  Project                                                                         |
|                     ->  Table Scan on big_data_test.table_with_pk_index_for_write_100m            |
| Plan 1:                                                                                           |
| Sink                                                                                              |
|   ->  Join                                                                                        |
|         Join Type: INNER                                                                          |
|         Join Cond: (__mo_index_idx_col = serial_full(col3, id))                                   |
|         Runtime Filter Build: #[0,0]                                                              |
|         ->  Table Scan on big_data_test.__mo_index_secondary_01907da1-f8f3-711e-8302-56fee4095edb |
|               Runtime Filter Probe: __mo_index_idx_col                                            |
|         ->  Sink Scan                                                                             |
|               DataSource: Plan 0                                                                  |
| Plan 2:                                                                                           |
| Delete on big_data_test.__mo_index_secondary_01907da1-f8f3-711e-8302-56fee4095edb                 |
|   ->  Sink Scan                                                                                   |
|         DataSource: Plan 1                                                                        |
| Plan 3:                                                                                           |
| Insert on big_data_test.__mo_index_secondary_01907da1-f8f3-711e-8302-56fee4095edb                 |
|   ->  Project                                                                                     |
|         ->  PreInsert SecondaryKey                                                                |
|               ->  Project                                                                         |
|                     ->  Project                                                                   |
|                           ->  Sink Scan                                                           |
|                                 DataSource: Plan 1                                                |
| Plan 4:                                                                                           |
| Delete on big_data_test.table_with_pk_index_for_write_100m                                        |
|   ->  Sink Scan                                                                                   |
|         DataSource: Plan 0                                                                        |
| Plan 5:                                                                                           |
| Insert on big_data_test.table_with_pk_index_for_write_100m                                        |
|   ->  Project                                                                                     |
|         ->  PreInsert on big_data_test.table_with_pk_index_for_write_100m                         |
|               ->  Project                                                                         |
|                     ->  Sink Scan                                                                 |
|                           DataSource: Plan 0                                                      |
+---------------------------------------------------------------------------------------------------+
39 rows in set (0.08 sec)

**Comment by badboynt1** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/112734932/2708d1ec-7b08-412f-bd04-1834f241f7b6)

这里的plan1 join是不必要的，这个会导致1亿行join 1亿行，超级大的join，而且不支持shuffle，会导致性能奇差无比。
本质上来说数据都可以直接通过plan0 scan出来以后，计算后写入到索引里面。 没必要做join

@ouyuanning  麻烦看一下优化这个执行计划

**Comment by ouyuanning** [comment]
1、对于没有where子句的情况，去掉join，直接table_scan所有数据。（不知道是否能用truncate？先还是用类似delete *的处理方式吧）
     - update次级索引和update unique key都适用
2、在有join的情况，看是否能加runtime filter

**Comment by ouyuanning** [comment]
感觉优化没有where子句的update操作的终极方案可能是：
create table tmp_tbl (...)   //--一样的schema
insert into tmp_tbl select col1,col2,col3+1... from origin_tbl   //这里的select子句根据update子句来构造
drop table origin_tbl
rename tmp_tbl to origin_tbl

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
测中移性能

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
等spill

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
最新的big data test依然不能成功执行

<img width="1442" alt="image" src="https://github.com/user-attachments/assets/d9194b1c-e2ed-4252-b13b-3fb8853cf3a3">

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11431798746/job/31802807942

**Comment by ouyuanning** [comment]
用这个分支试一试
https://github.com/aunjgr/matrixone/tree/dedupjoin

**Comment by jensenojs** [comment]
最新的big data query的报错是oom, 现在看内存占用最大的是hash join这一块

[<img width="1675" alt="image" src="https://github.com/user-attachments/assets/93dbcbcf-e4d9-490b-8c05-3771e46b1bae">](https://grafana.ci.matrixorigin.cn/explore?panes=%7B%225RM%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241023%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221729682820000%22,%22to%22:%221729682880000%22%7D%7D%7D&schemaVersion=1&orgId=1)


<img width="1655" alt="image" src="https://github.com/user-attachments/assets/445de503-5ecf-4950-9f48-90e17a7c05af">

**Comment by aressu1985** [comment]
stream closed的没有在出现过，OOM是老问题，后面版本在修复

**Comment by jensenojs** [comment]
no process
