### ISSUE TITLE
[Bug]: sysbench(100w basis data) insert report "Duplicate entry"  on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17354]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

16890e4757e7ad37fe37ff0c9f6917270729ba2e

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

Job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9809916970/job/27105819235

<img width="1399" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6963cbdf-8be9-4404-bfd6-c54312a3ddd4">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Loj%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-16890e475-20240705%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%20%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221720239896672%22,%22to%22:%221720240488100%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
It is occassionally, run sysbench insert test for several times
```

**Comment by triump2020** [comment]
自增列值重复了

**Comment by jensenojs** [comment]
这里有两个bug, 第一个是这里报的dup是TN发现的, 按理说应该是CN报错, 这个问题在下面的pr中fix
- https://github.com/matrixorigin/matrixone/pull/17361

第二个问题就是incrserivice的cache没有更新的问题, 另外一个issue中讨论的fix能避免这个问题, 但不优雅. 但在fix之前还是要确认一下自增列的cache没有更新这个事情应该不应该.
https://github.com/matrixorigin/matrixone/issues/16493#issuecomment-2188217519

**Comment by zhangxu19830126** [comment]
这个无解，cn0插入了用户手动的值xxx，但是在cn1上xxx是自增列的cache。cn1就有可能插入xxx的值

**Comment by aressu1985** [comment]
fixed
