### ISSUE TITLE
[Bug]: cn hang when try to update stats

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#17365]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 1.2-dev

### Commit ID

bdcc24e538fa16a0b1d1e2949acfd34f0b1816ce

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cn hang when try to update stats

<img width="1221" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/810966ff-f5ae-4fa7-83dc-e0a7e997e7df">

### Steps to Reproduce

```Markdown
run sysbench
```

**Comment by sukki37** [comment]
maybe dup with. https://github.com/matrixorigin/matrixone/issues/17358

**Comment by volgariver6** [comment]
close it as dup with #17358
