### ISSUE TITLE
[Bug]: Result is incorrect with NULL value in group by

### ISSUE THREAD

**Issue by MOOS2021** [matrixorigin/matrixone#1737]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):91a17f0822d2caf18cfc421891317c4f280bc8e9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t1;
create table t1(a int,b varchar(5));
insert into t1 values(1,'a');
insert into t1 values(null,null);
insert into t1 values(null,'b');
insert into t1 values(1,null);
select avg(a),b from t1 group by b order by b;
+--------+------+
| avg(a) | b    |
+--------+------+
| 1.0000 |      |
| 1.0000 | NULL |
|   NULL | b    |
+--------+------+
3 rows in set (0.02 sec)

### Expected Behavior

+--------+------+
| avg(a) | b    |
+--------+------+
| 1.0000 | NULL |
| 1.0000 | a    |
|   NULL | b    |
+--------+------+

**Comment by domingozhang** [comment]
Without order by b, the record '1.000,a' is also missing.

select avg(a),b from t1 group by b;
+--------+------+
| avg(a) | b    |
+--------+------+
| 1.0000 | NULL |
| 1.0000 |      |
|   NULL | b    |
+--------+------+
