### ISSUE TITLE
[Bug]: tpcc 100-100 txn was timeout in 60s during a specific time periods during daily regression on tke

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17392]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

a0f75f6

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9833610638/job/27152401626

<img width="1414" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/56270fe0-0361-4c64-9f39-91e308ddf185">

after searching log in this period, there lots of following error:
<img width="1375" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/95981753-037f-4bb4-85e4-20410fa32fc5">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Ln_%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-reg-a0f75f6%5C%22%7D%20%7C%3D%20%60failed%20to%20send%20access%20error%20to%20client%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221720431900000%22,%22to%22:%221720432019000%22%7D%7D%7D&schemaVersion=1&orgId=1

mo metircs:
https://grafana.ci.matrixorigin.cn/d/c69513f9-b211-40f5-a35c-c7ce5100abc2/txn-metrics?orgId=1&from=1720418863133&to=1720470691513&var-interval=1m&var-namespace=mo-branch-reg-a0f75f6&var-pod=All

### Steps to Reproduce

```Markdown
This is not mandatory, it is occasional
```

**Comment by volgariver6** [comment]
可能跟delta location 问题相关，导致某一时刻io非常慢，tpcc任务失败

**Comment by guguducken** [comment]
目前，根据与腾讯云侧沟通，故障时间段内未发现内网网络问题。但是他们说对应时间内proxy内存扫描次数过高，这会导致分配内存时因内存不足卡在内存回收上

**Comment by XuPeng-SH** [comment]
> 可能跟delta location 问题相关，导致某一时刻io非常慢，tpcc任务失败

问题所在版本delta location已经修复掉了

**Comment by volgariver6** [comment]
无进展

**Comment by volgariver6** [comment]
没再出现该问题，建议先关掉，等再出现时再分析 @heni02

**Comment by heni02** [comment]
confirm，closed
