### ISSUE TITLE
[Bug]: ut TestLockWithBindNotFound and TestUnlockWithBindNotFound failed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17414]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

f4f9286

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

url: https://github.com/matrixorigin/matrixone/actions/runs/9854060240/job/27206065407?pr=17370

<img width="1424" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/633eeee0-02b1-4487-90bf-a0071a5d1826">

[logs_25788665881.zip](https://github.com/user-attachments/files/16142363/logs_25788665881.zip)

### Steps to Reproduce

```Markdown
trigger ci test
```

**Comment by aronchanisme** [comment]
@iamlinjunhong  pls kindly help take a look, thx.
<img width="1469" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/c9ed0e49-46f8-476f-9f2b-51ea1fdbef57">

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by sukki37** [comment]
repro： https://github.com/matrixorigin/matrixone/actions/runs/10348278486/job/28640222253?pr=18061

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19412
