### ISSUE TITLE
[Bug]: cn crash by panic: close of closed channel during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17419]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

711ed3e

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode , cn crashed by panic:
{"level":"ERROR","time":"2024/07/09 10:56:09.656607 +0000","name":"cn-backend.pipeline-client","caller":"runtime/panic.go:770","msg":"gc inactive backends task stopped"}
panic: close of closed channel

goroutine 985 gp=0xc0110d0e00 m=31 mp=0xc12646a008 [running]:
panic({0x5e8cde0?, 0x6ea06d0?})
        /usr/local/go/src/runtime/panic.go:779 +0x15d fp=0xc162e67ba0 sp=0xc162e67af0 pc=0x44bffd
runtime.closechan(0xc135957c20)
        /usr/local/go/src/runtime/chan.go:365 +0x22c fp=0xc162e67be0 sp=0xc162e67ba0 pc=0x411ccc
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).stopWriteLoop(0xc1982949c0)
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:756 +0x25 fp=0xc162e67c00 sp=0xc162e67be0 pc=0x192fd45
github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).Close(0xc1982949c0)
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:387 +0xfc fp=0xc162e67c60 sp=0xc162e67c00 pc=0x192b53c
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).doRemoveInactive(0xc0110d28f0, {0xc1e33e0b50, 0x10})
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:422 +0x32b fp=0xc162e67e08 sp=0xc162e67c60 pc=0x193a66b
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).gcInactiveTask(0xc0110d28f0, {0x6ef8a58, 0xc0110fa570})
        /go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:406 +0x1e9 fp=0xc162e67f18 sp=0xc162e67e08 pc=0x193a289
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).gcInactiveTask-fm({0x6ef8a58, 0xc0110fa570})
        <autogenerated>:1 +0x39 fp=0xc162e67f48 sp=0xc162e67f18 pc=0x1951db9
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:277 +0xce fp=0xc162e67fe0 sp=0xc162e67f48 pc=0xe41f4e
runtime.goexit({})

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22K5P%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-711ed3e-202407082340%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221720522500451%22,%22to%22:%221720522821099%22%7D%7D%7D&schemaVersion=1&orgId=1

[panic.log.zip](https://github.com/user-attachments/files/16143880/panic.log.zip)

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
@zhangxu19830126 will handle it.

**Comment by aressu1985** [comment]
fixed
