### ISSUE TITLE
[Bug]: using process memory usage for background task memory throttle

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#17416]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,1.2-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

currently, it use the host virtual memory as a memory throttle parameter, which is not correct in cgroup.

### Steps to Reproduce

```Markdown
docker run mo with big host machine and pod with small memory limit
```

**Comment by aptend** [comment]
done
