### ISSUE TITLE
[Bug]: panic runtime error: slice bounds out of range [:131076] with capacity 16384

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#17453]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

https://github.com/ouyuanning/matrixone/tree/lock-table-if-cannot-lock-rows-2

### Commit ID

f1888ecaa7e68b96f5b10d0576bc50bcf316918f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

FATAL: mysql_drv_query() returned error 1105 (internal error: panic runtime error: slice bounds out of range [:131076] with capacity 16384: 
runtime.goPanicSliceAcap
	/usr/local/go/src/runtime/panic.go:140
github.com/matrixorigin/matrixone/pkg/txn/trace.writer.WriteHex
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/trace/service.go:914
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:502
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).AddTx) for query 'UPDATE sbtest9 SET c='29294865527-87101919834-63391513023-27213775000-17074974887-55984209883-19322044959-14151989316-18858532688-73742550950' WHERE id=18735'
FATAL: `thread_run' function failed: ./oltp_common.lua:460: SQL error, errno = 1105, state = 'HY000': internal error: panic runtime error: slice bounds out of range [:131076] with capacity 16384: 
runtime.goPanicSliceAcap
	/usr/local/go/src/runtime/panic.go:140
github.com/matrixorigin/matrixone/pkg/txn/trace.writer.WriteHex
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/trace/service.go:914
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:502
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).AddTx
FATAL: mysql_drv_query() returned error 1105 (internal error: panic runtime error: slice bounds out of range [:131076] with capacity 16384: 
runtime.goPanicSliceAcap
	/usr/local/go/src/runtime/panic.go:140
github.com/matrixorigin/matrixone/pkg/txn/trace.writer.WriteHex
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/trace/service.go:914
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:502
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).AddTx) for query 'UPDATE sbtest7 SET k=k+1 WHERE id=20042'
FATAL: `thread_run' function failed: ./oltp_common.lua:449: SQL error, errno = 1105, state = 'HY000': internal error: panic runtime error: slice bounds out of range [:131076] with capacity 16384: 
runtime.goPanicSliceAcap
	/usr/local/go/src/runtime/panic.go:140
github.com/matrixorigin/matrixone/pkg/txn/trace.writer.WriteHex
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/trace/service.go:914
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.doLock.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop/lock_op.go:502
github.com/matrixorigin/matrixone/pkg/txn/trace.(*service).AddTx

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/mo-auto-test/actions/runs/9869971245/job/27254727509

run sysbench 10w
```

**Comment by zhangxu19830126** [comment]
看上去修掉了
