### ISSUE TITLE
[Bug]: checkin regression failed with tpch q8 report 'send notify msg to dispatch operator timeout'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17475]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6f3e6dcc94aa6aed1bac2cf34aa55334db129300

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

link: https://github.com/matrixorigin/matrixone/actions/runs/9886235447

<img width="1764" alt="企业微信截图_5bad6248-4ded-4459-98c8-2937e3a2fb7c" src="https://github.com/matrixorigin/matrixone/assets/108530700/1c1e4f31-5f2e-4717-9d0a-445f47de6bd4">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XI8%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-17444%5C%22%7D%20%7C%3D%20%60send%20notify%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221720681503000%22,%22to%22:%221720681803000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger checkin regression test.
```

**Comment by aronchanisme** [comment]
@m-schen pls kindly take a look, thx.
<img width="1693" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/c0112c73-81ab-41c6-9904-c629df53a16c">

**Comment by Ariznawlll** [comment]
revert了远宁哥的pr，已解决
