### ISSUE TITLE
[Bug]: restore 'panic'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17476]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fdd3eae

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url:** https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9887179942/job/27308741665

有重启：
<img width="596" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/d11aea9f-7026-4d49-8c33-3393547fb77a">
内存情况正常，初步排除oom：
<img width="1410" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/4050a5d8-b416-444a-b368-c42c3d4fd007">

收集的crash log里面有panic：
<img width="1432" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/fc01406f-ea77-40ff-9eb2-e3d4418da5e1">

相关时间段panic日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Sbv%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-test-20240711%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221720685196000%22,%22to%22:%221720685316000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
自动化 restore步骤：
1. Load tpcc 10warehouse data；
2. load 10million data in table big_data_test.table_basic_for_load_100M（36G）；
3. create snapshot sys_sp01 for account sys；
4. 执行tpcc测试30min；
5. drop table big_data_test.table_basic_for_load_100M；
6. restore account sys from snapshot sys_sp01；
```

**Comment by YANGGMM** [comment]
{"level":"INFO","time":"2024/07/11 08:06:35.372189 +0000","name":"cn-service.frontend","caller":"frontend/snapshot.go:872","msg":"[sys_sp01] start to insert select table: table_basic_for_load_100m, insert sql: insert into `big_data_test`.`table_basic_for_load_100m` SELECT * FROM `big_data_test`.`table_basic_for_load_100m` {MO_TS = 1720683326843825128 }","uuid":"33326236-6138-6462-6361-343130303431"}

**Comment by triump2020** [comment]
![1720703578907](https://github.com/matrixorigin/matrixone/assets/63033222/231f9b1a-7759-4f6e-b5e6-94d1ee3e47f0)


 应该是最新加的 表分区相关的代码导致的，代码哪个位置没改干净.

**Comment by triump2020** [comment]
@Ariznawlll  test pls.

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
panic的问题没了。但是测试中出现了oom的问题，已在issue中更新，由16138跟踪。
