### ISSUE TITLE
[Bug]: we need add https_proxy, http_proxy, no_proxy for mo container for mergerun

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#17492]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d15d6992680af37a66574b4f224ad397a05c8857

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: linux
- Others:
```

### Actual Behavior

mo does not read environment variables and set proxies when requesting data using http protocol

### Expected Behavior

for mergerun, we need add proxy info to mo service container

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9902451845/job/27356679539
```

**Comment by aronchanisme** [comment]
related issue: https://github.com/matrixorigin/MO-Cloud/issues/3734

**Comment by sukki37** [comment]
This issue has been inactive for a while, and it seems that it may have been resolved or is no longer relevant. As a result, we are closing it for now.
