### ISSUE TITLE
[Bug]: mo startup panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17499]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

99cecddc7afba77f1ef921d033adc0431ee2d8d3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1653" alt="企业微信截图_15a3c15e-2692-4694-814e-cc61e3ae686a" src="https://github.com/user-attachments/assets/5d975134-3381-4068-93a1-c036cf87ea86">

### Steps to Reproduce

```Markdown
start mo locally.
```

**Comment by Ariznawlll** [comment]
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/ff653a8f-f9c7-48d1-9d7d-0db5a7725273">

@CJKkkk-315

**Comment by daviszhen** [comment]
初步分析pr 在mac arm机器上有问题。在mac intel 机器上没有问题

**Comment by daviszhen** [comment]
找到原因了。
在mac arm 上 如果unix socket 为空的话，会报错。

**Comment by daviszhen** [comment]
这个不影响非arm的机器。

**Comment by Ariznawlll** [comment]
commit: c1751aa204f5e21e1c247299b2a7a1b3366a991a

```
步骤：
1.git clone https://github.com/matrixorigin/matrixone.git
2.make build
3../mo-service -launch ./etc/launch/launch.toml
4.mysql -h 127.0.0.1 -P 6001 -udump -p111
```

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/699e07f5-f8e7-4362-98e8-b375368ce68e">

测试通过。
