### ISSUE TITLE
[Bug]: `no user dump error` and many `authentication error` after bvt cluster_level_snapshot_restore_system_table_to_sys_account cases

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#17509]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

9258380b84493adf888b5e1c5919932b11ad1afb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: linux
- Others:
```

### Actual Behavior

after this, mo throw many authentication error, and `no user dump` error is thrown when create tenant
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/1fa71e2b-2715-41ff-9a6d-68dcb437de6e">

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/9904499894/job/27362886513
```

**Comment by daviszhen** [comment]
create user duplicate key

**Comment by daviszhen** [comment]
"no user dump"
是指任务挂了后。mysql 登录时，抛的错误。

**Comment by triump2020** [comment]
![企业微信截图_17207808184884](https://github.com/user-attachments/assets/222ffaeb-89f9-4c7e-8530-3b22704c8a08)

![企业微信截图_17207810862313](https://github.com/user-attachments/assets/58673814-ee7b-4406-aa1c-bcd077e2436b)


So many table report duplication error .

**Comment by triump2020** [comment]
![企业微信截图_17207816465594](https://github.com/user-attachments/assets/cf73cbe6-eac6-4226-aee4-1d242449f368)

**Comment by LeftHandCold** [comment]
{"level":"ERROR","time":"2024/07/12 08:36:58.180346 +0000","name":"cn-service.frontend","caller":"frontend/util.go:509","msg":"query trace status","uuid":"63333135-3566-3232-3463-623135373033","statement":"insert into mo_catalog.mo_user_grant (role_id, user_id, granted_time, with_grant_option) values (1, 1, 2024-07-12 08:36:58, true)","status":"fail","error":"Duplicate entry '(1,1)' for key '__mo_cpkey_col'","txn_info":"0190a6169cb77ddc85da6ade36ebc7f9:1720773418176221544-1","session_info":"connectionId 18\|\|{account sys:dump:moadmin -- 0:1:0}\|goRoutineId 1494\|migrate-goRoutineId 0\|0190a609-6d91-7030-bac3-18388f33c2dd","background":true,"session_id":"0190a616-9cb7-7da9-b126-a6a4b9263b63","txn_id":"0190a6169cb77ddc85da6ade36ebc7f9","span":{"trace_id":"7fa8fb7c-e30e-e6c4-e059-e59de767374e","span_id":"fa91b8aef0826076"}}
--

为什么创建一个用户会插入1,1?  集群启动默认就已经存在这条数据了，这个dup看起来是业务层引起的问题 @daviszhen 帮忙看一下

**Comment by LeftHandCold** [comment]
mysql> select * from mo_user_grant;
+---------+---------+---------------------+-------------------+
| role_id | user_id | granted_time        | with_grant_option |
+---------+---------+---------------------+-------------------+
|       0 |       0 | 2024-07-16 03:24:29 | false             |
|       1 |       0 | 2024-07-16 03:24:29 | false             |
|       0 |       1 | 2024-07-16 03:24:29 | false             |
|       1 |       1 | 2024-07-16 03:24:29 | false             |
+---------+---------+---------------------+-------------------+
4 rows in set (0.01 sec)

**Comment by daviszhen** [comment]
create user的userid 是从mo_user表中查出来的。userid是自增列。

create user时，是在同一个事务中做：
1,insert 一条记录到mo_user;
2,查询mo_user，拿到user_id;（自增列）
3,insert 一条记录到mo_user_grant。

mo_user表内置了两个用户：
root -》userid 0
dump -》userid 1

mo_user的自增列应该从2开始。

现在新user的userid是1,大概率自增列有问题。

**Comment by daviszhen** [comment]
zhangxu 在看。

**Comment by zhangxu19830126** [comment]
目前分析，自增列的表出问题的时候，从数据库查询出来的值就是错的。

**Comment by zhangxu19830126** [comment]
<img width="1478" alt="企业微信截图_c423079d-6231-449f-a2f1-e41611bff01d" src="https://github.com/user-attachments/assets/19d4f4ff-ad60-416c-95af-35addb87c6e3">

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
一直在跑测试没有复现

**Comment by YANGGMM** [comment]
一直在跑测试没有复现

**Comment by YANGGMM** [comment]
没有复现

**Comment by YANGGMM** [comment]
还在看

**Comment by YANGGMM** [comment]
follow by #18237

**Comment by Ariznawlll** [comment]
观察了一段时间，没有再出现
