### ISSUE TITLE
[Bug]: run tpcc 10-10, TN panic

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#17519]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6d0d59587a6dbcc162a8530191441ee6ea6e3d7e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2024/07/13 23:14:36.929129 +0800","name":"log-service","caller":"taskservice/task_service_cron.go:44","msg":"cron task scheduler started or is stopping","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"INFO","time":"2024/07/13 23:14:36.930638 +0800","name":"log-service","caller":"task/task_scheduler.go:65","msg":"task schedule query tasks","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","created":0,"expired":0}
{"level":"INFO","time":"2024/07/13 23:14:37.535345 +0800","caller":"dbutils/mem.go:107","msg":"HeapInfo:TotalAlloc:3400961MB Sys:4750MB HeapAlloc:2464MB HeapSys:4637MB HeapIdle:1634MB HeapReleased:1293MB HeapInuse:3003MB NextGC:3259MB NumGC:2623 PauseNs:410228799"}
{"level":"INFO","time":"2024/07/13 23:14:37.534959 +0800","caller":"catalog/catalog.go:136","msg":"GC Catalog 1720883254534874586-0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x267e188]

goroutine 2333 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*ObjectEntry).GetDeleteAt(...)
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/object.go:57
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*ObjectEntry).DeleteBefore(0x41e87f?, {0x0, 0x0, 0x0, 0x0, 0xda, 0x25, 0x78, 0xce, 0x33, ...})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/object.go:160 +0x8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).GCByTS.func4({0x56bd030?, 0xc0c285cff0?})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/catalog.go:164 +0x65
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*LoopProcessor).OnTombstone(0x49f6280?, {0x56bd030?, 0xc0c285cff0?})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/processor.go:86 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*TableEntry).RecurLoop(0xc0168ffe80, {0x56544f0, 0xc02637e080})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/table.go:505 +0x359
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*DBEntry).RecurLoop(0x0?, {0x56544f0, 0xc02637e080})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/database.go:555 +0xbf
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).RecurLoop(0x4adf74b?, {0x56544f0, 0xc02637e080})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/catalog.go:370 +0xc5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Catalog).GCByTS(0xc018cba360, {0xc043d2ad18?, 0x4156e5?}, {0x0, 0x0, 0x0, 0x0, 0xda, 0x25, 0x78, ...})
        /home/mo/matrixone/pkg/vm/engine/tae/catalog/catalog.go:172 +0x1de
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open.func6({0x560fb38, 0x80af480})
        /home/mo/matrixone/pkg/vm/engine/tae/db/open.go:256 +0x8e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/gc.(*Manager).process(0x410e1e?, {0xc02b3fa500, 0x1, 0x0?})
        /home/mo/matrixone/pkg/vm/engine/tae/gc/manager.go:94 +0x2e9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
        /home/mo/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1fd
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 533
        /home/mo/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xe5

### Steps to Reproduce

```Markdown
run tpcc 10-10
```

**Comment by jiangxinmeng1** [comment]
fixed by #17520

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
