### ISSUE TITLE
[Bug]: internalExector query mo_catalog.mo_accounts got empty resultset.

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#17548]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cccaf5e5d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cron_task - StrorageUsage - checkNewAccountSize query table `mo_catalog.mo_account` per minute, but got empty resultset always event without create_time filter-condition.

- debug code: remove the `create_time` filter-condition. `mometric/cron_task.go:L283`
![企业微信截图_d275aa7d-118d-486b-858a-a2dec17abb4a](https://github.com/user-attachments/assets/e608f687-5dc9-4d25-b7fe-3a6cef10ad87)

### Steps to Reproduce

```Markdown
make && ./mo-service -launch ./etc/launch/launch.toml
```

**Comment by xzxiong** [comment]
note:
这里是统计 storage metric，针对新增的租户，这里是 1min检查一次的逻辑。
- 5min一次，常规更新，正常运行。这里会全量更新
- 1min一次，仅检查新租户。目前看main分支这里没有正常工作。

**Comment by CJKkkk-315** [comment]
https://github.com/matrixorigin/matrixone/pull/17550 已修复 merge到main

**Comment by xzxiong** [comment]
checked
- case: create new account per 20s
![image](https://github.com/user-attachments/assets/e321187b-9912-4460-a8f2-15d04ae22523)
- metric show corrent account.
![image](https://github.com/user-attachments/assets/b1552798-e7c3-4015-94c5-318a6ef1994c)

**Comment by xzxiong** [comment]
```
select *  from system_metrics.server_storage_usage order by collecttime desc limit 10;
```

**Comment by xzxiong** [comment]
https://shanghai.idc.matrixorigin.cn:30001/d/de1wtrqty5reoa/trace-metrics?orgId=1&refresh=30s&viewPanel=268&from=1730949303847&to=1730951103847
