### ISSUE TITLE
[Subtask]: Clarify the life cycle of sql in metric/trace

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#17566]
### Parent Issue

#17565

### Detail of Subtask

澄清 metric/trace 对于 FE提交的sql什么时候释放。

**Comment by xzxiong** [comment]
trace 主要有 2个场景会使用到 frontend 的sql
- statement_info 历史记录的采集
- log打印，这里也会将对应的数据采集存储到  system.rawlog表。（这里的逻辑与 statement_info类似）

statement_info通过 mo_logger进行异步 批处理的持久化，目前的逻辑为：
- 会引用sql字符串？会。
    - 逻辑： statement_info持有的 sql 经过SubStringFromBegin 处理的，新建了 string对象，但是字符串是通过 unsafe.String 转的 []byte，所以内存是复用的。
   - 影响：不存在datarace，但会导致内存延迟释放。
       - 与 @CJKkkk-315 了解到，这块内存大小就是client发来的request的大小 用一块内存 由read的时候make出来的
- 持有多久？最长 15s
    - 逻辑：mo_loggger 是 15s 进行一次批处理序列化，所以对象会被引用更长时间。
    - 优化：1.3.0 有个优化，会将持有时间缩短到 1s内（正常约 50us）

**Comment by xzxiong** [comment]
plan 8月15

**Comment by xzxiong** [comment]
与 @daviszhen 对齐了一下，
后续 frontend 对sql 内存的优化：提升内存的复用效率，减少从网络读取后 对 内存的拷贝。所有还是需要解决对sql内存的异步应用。
本 issue 的优化思路：
- statement_info 需要考虑对 sql的内存进行拷贝，因为有长度限制 （默认为 1024 Byte），预计影响不大 —— 优化后，需验证。
- 内存的复用，减少动态make 内存的消耗。
- 针对 log日志打印，则需要关注 sql 字符串的数据，需要有一定的拷贝。—— 目前就一个场景，当query 执行失败时，需要打印 error 日志。

**Comment by xzxiong** [comment]
@aressu1985 已实现，请回归~

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
