### ISSUE TITLE
[Bug]: build_ddl.go, line 3286, indexs is never initialized therefore the loop is a no op.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17576]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

04eb3e8001220c65645fc9db971d76367e9ad2cc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

It is obviously a bug, from code inspection.   In fact, golang gives a warning.

The loop is a noop, which is more or less fine.   I am worried that we are missing some case that we should have build the indexs before the loop.

### Steps to Reproduce

```Markdown
Read the code
```

**Comment by qingxinhome** [comment]
The issue has been resolved

**Comment by aressu1985** [comment]
这个问题田博确认一下
