### ISSUE TITLE
[Bug]: 1.2-dev tke regression : Non-pk Auto-inc index point select 100 thread test hung in creating sbtest5.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17578]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

0a5cbc6bdb24b9e5df7391fa4aa324e4a2325fa3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9958298620/job/27512667560

<img width="977" alt="image" src="https://github.com/user-attachments/assets/a0e427a0-8c98-4eeb-a489-ef49c627ccd2">

pod 状态正常，没有oom：
<img width="433" alt="image" src="https://github.com/user-attachments/assets/b32294a9-4052-427b-a7b1-80c6f9d187af">

log in creating sbtest5：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Y07%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-0a5cbc6bd-20240716%5C%22%7D%20%7C%3D%20%60sbtest5%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721192730000%22,%22to%22:%221721197410000%22%7D%7D%7D&schemaVersion=1&orgId=1

环境还在，可定位

### Steps to Reproduce

```Markdown
regression test on tke
```

**Comment by reusee** [comment]
![Screenshot from 2024-07-17 16-07-07](https://github.com/user-attachments/assets/71f9b192-5b12-4be6-b2cd-0dcc5274f79a)

第一个错误是这个。

看上去和这个一样：https://github.com/matrixorigin/matrixone/issues/14031

@daviszhen 麻烦再看看

**Comment by daviszhen** [comment]
这里的显示create table sbtest5成功了。

{"level":"INFO","time":"2024/07/17 05:08:30.275165 +0000","name":"cn-service.txn","caller":"compile/ddl.go:888","msg":"createTable ok","uuid":"33313035-3232-6438-3261-613164376263","databaseName":"sysbench_db","tableName":"sbtest5","txnID":"0190bf178dc1700fb69537b90aa2447e/Active/S:1721192910271772185-1","session_id":"0190bf17-8daf-7b4e-a363-6aa03b032a11","statement_id":"0190bf17-8dbf-7111-9dcd-7688f458399e","txn_id":"0190bf178dc1700fb69537b90aa2447e","span":{"trace_id":"6d7960d8-efab-d1e2-418e-89720fc0dfad","span_id":"eca7169fd408da32"}}

**Comment by daviszhen** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Y07%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-0a5cbc6bd-20240716%5C%22%7D%20%7C%3D%20%600190bf178dc1700fb69537b90aa2447e%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721192730000%22,%22to%22:%221721197410000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
![image](https://github.com/user-attachments/assets/48b876af-9119-46b6-b16a-5dfb90a46d40)

**Comment by daviszhen** [comment]
实际是卡在create table 里面没有返回。

**Comment by daviszhen** [comment]
[Uploading CN_33313035-3232-6438-3261-613164376263_leakcheck_routine_0190bf32-39ff-7de0-a39d-7cc95a411319.gz…]()

**Comment by daviszhen** [comment]
[CN_33313035-3232-6438-3261-613164376263_leakcheck_routine_0190bf32-39ff-7de0-a39d-7cc95a411319.gz](https://github.com/user-attachments/files/16264560/CN_33313035-3232-6438-3261-613164376263_leakcheck_routine_0190bf32-39ff-7de0-a39d-7cc95a411319.gz)

**Comment by daviszhen** [comment]
goroutine 5152913 [select, 28 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).selectFrom1Reg(0xc2a5020d00)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/receiver_operator_expand.go:25 +0x8b
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).selectFromAllReg(0xc2a5020d00)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/receiver_operator.go:173 +0x3a
github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).ReceiveFromAllRegs(0xc2a5020d00, {0x5387698, 0xc2a5020f80})
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/receiver_operator.go:96 +0x5e
github.com/matrixorigin/matrixone/pkg/sql/colexec/merge.(*Argument).Call(0xc2fcf47570, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/merge/merge.go:55 +0x227
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call(0xc1e1719900, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:61 +0x84
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call(0xc291b82300, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:61 +0x84
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call(0xc49168c880, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:61 +0x84
github.com/matrixorigin/matrixone/pkg/sql/colexec/preinsertsecondaryindex.(*Argument).Call(0xc269069320, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go:52 +0x87
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Argument).Call(0xc1c06bb600, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:61 +0x84
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x5353870, 0xc1c06bb600}, 0xc1688c7508, {0x5387698, 0xc2a5020f40})
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:229 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.(*Argument).insert_table(0xc2fcf475e0, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/insert/insert.go:183 +0x114
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.(*Argument).Call(0xc2fcf475e0, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/insert/insert.go:72 +0xcc
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc15f40ec88, 0x7, 0x7fbf29d7de18?}, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:135 +0x122
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc0257b3d30, 0xc1688c7508)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:156 +0x185
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc19587cfc0, 0xc01fd83520)                                                                                                                                            
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:260 +0x39c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc01fd83520, 0xc19587cfc0)
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:336 +0x60d
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:644 +0x6e
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8d
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 5152910
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

**Comment by daviszhen** [comment]
runOnce卡住了

**Comment by ouyuanning** [comment]
还没看。不过这个看着跟曾言处理过的join hung的问题很像。估计main已经处理过了

**Comment by ouyuanning** [comment]
看不出啥问题，找时间二分一下吧

**Comment by ouyuanning** [comment]
从日志看不出来啥

**Comment by ouyuanning** [comment]
未投入

**Comment by Ariznawlll** [comment]
观察中。

**Comment by Ariznawlll** [comment]
最近的测试没出现这个问题，先关掉
