### ISSUE TITLE
[Bug]: The MatrixOne version number is appeared wrong

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1757]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): v0.2.0 （commit-id：8e70c998f3deab6fd806cad66c294c692b0f9cfa）
- Hardware parameters:Apple M1, memory 16GB 
- OS type: Mac os
- Others:
```

### Actual Behavior

When I use MySQL client to connect to MatrixOne, the appeared version of MatrixOne is still 0.1.0.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/97089788/155474796-c895d94e-091d-41fa-98bd-d82d0b1fd068.png">

### Expected Behavior

The appeared version of MatrixOne should become 0.2.0.

### Steps to Reproduce

```markdown
docker run -d -p 6001:6001 --name matrixone matrixorigin/matrixone:latest
mysql -h 127.0.0.1 -P 6001 -udump -p
```

**Comment by m-schen** [comment]
fixed it, you can verify it on main branch after the pull request #1764 merged
