### ISSUE TITLE
[Bug]: checkin regression  report cannot commit in an orphan transaction in tpcc test

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#17582]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/219815ac-c5a4-4eb1-90e8-71f02eea43ea">

### Steps to Reproduce

```Markdown
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22g15%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-17553%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1



```
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/1b5f253c-ba63-4846-8372-70c0ce7a0bc7">

**Comment by zhangxu19830126** [comment]
it's not bug
