### ISSUE TITLE
[Bug]: cn crash by panic runtime error: invalid memory address or nil pointer dereference during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17590]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

88e486e

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

cn crash by panic runtime error: invalid memory address or nil pointer dereference during stability test on distributed mode :
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56b2d48]

goroutine 75027 gp=0xc00f5d6380 m=31 mp=0xc029b2e808 [running]:
panic({0x6239fe0?, 0x98e7850?})
        /usr/local/go/src/runtime/panic.go:779 +0x15d fp=0xc03caa1270 sp=0xc03caa11c0 pc=0x44bffd
runtime.panicmem()
        /usr/local/go/src/runtime/panic.go:261 +0x3e fp=0xc03caa1290 sp=0xc03caa1270 pc=0x44b1fe
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:881 +0x245 fp=0xc03caa12c0 sp=0xc03caa1290 pc=0x465dc5
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getProtocol(0x0)
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:146 +0x28 fp=0xc03caa1340 sp=0xc03caa12c0 pc=0x56b2d48
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handshake(0xc007220b40, 0xc0eb9f02c0)
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:198 +0x395 fp=0xc03caa1df0 sp=0xc03caa1340 pc=0x56c59b5
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc007220b40, {0x73b6118, 0xc07b3dcc40})
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:165 +0x277 fp=0xc03caa1fa0 sp=0xc03caa1df0 pc=0x56c5097
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept.gowrap2()
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:153 +0x3c fp=0xc03caa1fe0 sp=0xc03caa1fa0 pc=0x56c4d9c
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc03caa1fe8 sp=0xc03caa1fe0 pc=0x488da1
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 1532
        /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:153 +0x3ad

[cn_panic.tar.gz](https://github.com/user-attachments/files/16277009/cn_panic.tar.gz)

mo log link:

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by reusee** [comment]
dup: https://github.com/matrixorigin/matrixone/issues/17592

**Comment by CJKkkk-315** [comment]
https://github.com/matrixorigin/matrixone/issues/17563 保留一个最早的issue跟踪，其它先关闭吧

**Comment by CJKkkk-315** [comment]
fix in https://github.com/matrixorigin/matrixone/pull/17573

**Comment by aressu1985** [comment]
fixed
