### ISSUE TITLE
[Bug]: After creating a tenant and connect to mo,  the statement_info table is null.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17605]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

88e486e11b4310336ec6d40ba86e26a400974819

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

系统租户下可以过滤到acc01对应的statement_info表中的count，但是acc01租户下查不到

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/8428cb96-1af9-430b-9682-98e6be9c8a7e">

### Expected Behavior

acc01对应的statement_info表不应该为null

### Steps to Reproduce

```Markdown
mysql -h 127.0.0.1 -P 6001 -udump -p111
use system;
select count(*) from statement_info where account = 'acc01';
create account acc01 admin_name = 'test_account' identified by '111';


mysql -h 127.0.0.1 -P 6001 -uacc01:test_account -p111
use system;
select count(*) from statement_info;
```

**Comment by xzxiong** [comment]
is this issue can repro ?

**Comment by Ariznawlll** [comment]
> is this issue can repro ?

yes，按照我提供的步骤，我本地必现

**Comment by xzxiong** [comment]
not check yet

**Comment by xzxiong** [comment]
check, repro-ed

BUG: 普通租户访问 system.statement_info, system_metrics.metric 没有数据

版本：
- main, not ok. 从https://github.com/matrixorigin/matrixone/commit/88e486e11b4310336ec6d40ba86e26a400974819 ( 2024-07-17 ) main （2024-07-30） 都还有问题
- 1.2-dev , ok. 

我看了 3处代码没修改。（普通租户 访问 system.statement_info 转到 sys的 system.statement_info）。
- ![image](https://github.com/user-attachments/assets/e420fe9c-21a9-4fa5-a5fe-223e5aadf0c7)
- ![image](https://github.com/user-attachments/assets/3169ee82-d2ee-4ff0-8435-5dad5cd2253e)
- ![image](https://github.com/user-attachments/assets/d78c16e6-cec9-405f-b689-a95903f0690c)

**Comment by xzxiong** [comment]
根据二分 main 的commit，确认有问题的 commit为: 11862bbe4

@ouyuanning  ptal

```
commit 11862bbe477457ff94cd60d2148afc8feb6b692d (HEAD)
Author: ou yuanning <45346669+ouyuanning@users.noreply.github.com>
Date:   Thu May 30 11:54:50 2024 +0800

    refactor: remove Relation from engine.Node (#16489)

    refactor: remove Relation from engine.Node


    ___

    ### **PR Type**
    Enhancement


    ___

    ### **Description**
    - Removed `Rel` field from `engine.Node` struct and its initialization across multiple functions.
    - Added `Rel` field to `DataSource` struct and updated relevant logic to use `DataSource.Rel` instead of `NodeInfo.Rel`.
    - Reorganized imports in `scope.go` for better readability.
    - Removed redundant checks and assignments related to `Rel` in `scope.go`.



    ___
```

**Comment by ouyuanning** [comment]
review中

**Comment by Ariznawlll** [comment]
**commit: c858aafbfebd63586c45302737a4230d2de9c082**

测试步骤：
1. sys租户下创建acc01:
    
    create account acc01 admin_name = 'test_account' identified by '111';

2. 登陆非系统租户：
```
  mysql -h 127.0.0.1 -P 6001 -uacc01:test_account -p111
  select * from system.statement_info;
  select count(*) from system.statement_info;
```

3. 查看：
<img width="1739" alt="image" src="https://github.com/user-attachments/assets/321c207c-3d1e-4612-bd96-64260be01320">

测试通过✅
