### ISSUE TITLE
[Bug]: Instance crashed during LOAD DATA 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1761]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8e70c998f3deab6fd806cad66c294c692b0f9cfa
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> load data infile '/matrixone/dataset/data_600m/lineorder_flat.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)
ERROR: 
Can't connect to the server

### Additional information

goroutine 309 [running]:
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).Split.func2()
	/matrixone/matrixone-0.2.0/pkg/vm/driver/aoe/storage.go:816 +0x58
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.waitExpect(0x9c4, 0xc007548ca8)
	/matrixone/matrixone-0.2.0/pkg/vm/driver/aoe/storage.go:612 +0xa7
github.com/matrixorigin/matrixone/pkg/vm/driver/aoe.(*Storage).Split(_, {0xf, 0x1c, {{0xf, {0xc0048f8a30, 0xc, 0x10}, {0xc0048f8a40, 0xc, 0x10}, ...}, ...}, ...}, ...)
	/matrixone/matrixone-0.2.0/pkg/vm/driver/aoe/storage.go:814 +0x4f1
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).doExecSplit(0xc00000cd20, 0xc00696d200)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_state_machine_exec.go:280 +0xb05
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).execAdminRequest(0xc00004019b, 0x5)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_state_machine_exec.go:43 +0x378
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).applyRequestBatch(0xc00000cd20, 0xc00696d200)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_state_machine.go:271 +0x608
github.com/matrixorigin/matrixcube/raftstore.(*stateMachine).applyCommittedEntries(0xc00000cd20, {0xc006e8d9e0, 0x1, 0xc068a9b3d8})
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_state_machine.go:190 +0x34b
github.com/matrixorigin/matrixcube/raftstore.(*replica).doApplyCommittedEntries(0xc003897000, {0xc006e8d9e0, 0x2516c72, 0x20})
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_event_raft_ready.go:346 +0x5d
github.com/matrixorigin/matrixcube/raftstore.(*replica).applyCommittedEntries(_, {0x0, {0x3, 0x13, 0x1d}, {0x0, 0x0, 0x0}, {0xc03b619350, 0x1, ...}, ...})
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_event_raft_ready.go:207 +0x1ed
github.com/matrixorigin/matrixcube/raftstore.(*replica).processReady(_, {0x0, {0x3, 0x13, 0x1d}, {0x0, 0x0, 0x0}, {0xc03b619350, 0x1, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_event_raft_ready.go:62 +0x225
github.com/matrixorigin/matrixcube/raftstore.(*replica).handleRaftReady(0xc003897000, 0xc000596000)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_event_raft_ready.go:37 +0x134
github.com/matrixorigin/matrixcube/raftstore.(*replica).handleEvent(0xc003897000, 0x0)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/replica_event_loop.go:225 +0x1c5
github.com/matrixorigin/matrixcube/raftstore.(*replicaWorker).handleEvent(0xc00053af60, {0x27b5ee8, 0xc003897000})
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/worker_pool.go:114 +0x5f
github.com/matrixorigin/matrixcube/raftstore.(*replicaWorker).workerMain(0xc00053af60)
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/worker_pool.go:91 +0xc5
github.com/matrixorigin/matrixcube/raftstore.newReplicaWorker.func1()
	/root/go/pkg/mod/github.com/matrixorigin/matrixcube@v0.0.0-20211230152817-79ca3b9ec6f1/raftstore/worker_pool.go:72 +0x1d
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1()
	/root/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79 +0xd2
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
	/root/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:74 +0xef

**Comment by zhangxu19830126** [comment]
Duplicated with #1703
