### ISSUE TITLE
[Bug]: [date 7.21]tke regression: load data test reported error the data of row 1 contained is not equal to input columns

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17639]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ca591a26f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10029129403/job/27721603316
<img width="971" alt="企业微信截图_6bd6c6fe-a943-42b5-aea9-9d8b1b962184" src="https://github.com/user-attachments/assets/c3b506c9-b94d-4c76-a77c-d6172025166b">
压缩格式文件load也是报错
<img width="965" alt="企业微信截图_592856c3-5aee-472b-8d24-9481b5482768" src="https://github.com/user-attachments/assets/1b7bafca-ea23-476a-af66-a2e1ca3bf942">

<img width="1354" alt="企业微信截图_c98ecb3a-5967-4947-a17d-908c665413dd" src="https://github.com/user-attachments/assets/1c6384a3-4ca9-4abd-9de9-0d82e02853f5">
@huby2358 cc

### Steps to Reproduce

```Markdown
tke regression load data test
```

**Comment by heni02** [comment]
ddl:
'create table table_100_columns(
clo1 tinyint,
clo2 smallint,
clo3 int,
clo4 bigint,
clo5 tinyint unsigned,
clo6 smallint unsigned,
clo7 int unsigned,
clo8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(5,2),
col17 text,
col18 varchar(255),
col19 varchar(255),
col20 varchar(255),
col21 varchar(255),
col22 varchar(255),
col23 varchar(255),
col24 varchar(255),
col25 varchar(255),
col26 varchar(255),
col27 varchar(255),
col28 varchar(255),
col29 varchar(255),
col30 varchar(255),
col31 varchar(255),
col32 varchar(255),
col33 varchar(255),
col34 varchar(255),
col35 varchar(255),
col36 varchar(255),
col37 varchar(255),
col38 varchar(255),
col39 varchar(255),
col40 varchar(255),
col41 varchar(255),
col42 varchar(255),
col43 varchar(255),
col44 varchar(255),
col45 varchar(255),
col46 varchar(255),
col47 varchar(255),
col48 varchar(255),
col49 varchar(255),
col50 varchar(255),
col51 varchar(255),
col52 varchar(255),
col53 varchar(255),
col54 varchar(255),
col55 varchar(255),
col56 varchar(255),
col57 varchar(255),
col58 varchar(255),
col59 varchar(255),
col60 varchar(255),
col61 varchar(255),
col62 varchar(255),
col63 varchar(255),
col64 varchar(255),
col65 varchar(255),
col66 varchar(255),
col67 varchar(255),
col68 varchar(255),
col69 varchar(255),
col70 varchar(255),
col71 varchar(255),
col72 varchar(255),
col73 varchar(255),
col74 varchar(255),
col75 varchar(255),
col76 varchar(255),
col77 varchar(255),
col78 varchar(255),
col79 varchar(255),
col80 varchar(255),
col81 varchar(255),
col82 varchar(255),
col83 varchar(255),
col84 varchar(255),
col85 varchar(255),
col86 varchar(255),
col87 varchar(255),
col88 varchar(255),
col89 varchar(255),
col90 varchar(255),
col91 varchar(255),
col92 varchar(255),
col93 varchar(255),
col94 varchar(255),
col95 varchar(255),
col96 varchar(255),
col97 varchar(255),
col98 varchar(255),
col99 varchar(255),
col100 varchar(255)
);'

**Comment by heni02** [comment]
报错table ddl：
create table table_100_columns(
clo1 tinyint,
clo2 smallint,
clo3 int,
clo4 bigint,
clo5 tinyint unsigned,
clo6 smallint unsigned,
clo7 int unsigned,
clo8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(5,2),
col17 text,
col18 varchar(255),
col19 varchar(255),
col20 varchar(255),
col21 varchar(255),
col22 varchar(255),
col23 varchar(255),
col24 varchar(255),
col25 varchar(255),
col26 varchar(255),
col27 varchar(255),
col28 varchar(255),
col29 varchar(255),
col30 varchar(255),
col31 varchar(255),
col32 varchar(255),
col33 varchar(255),
col34 varchar(255),
col35 varchar(255),
col36 varchar(255),
col37 varchar(255),
col38 varchar(255),
col39 varchar(255),
col40 varchar(255),
col41 varchar(255),
col42 varchar(255),
col43 varchar(255),
col44 varchar(255),
col45 varchar(255),
col46 varchar(255),
col47 varchar(255),
col48 varchar(255),
col49 varchar(255),
col50 varchar(255),
col51 varchar(255),
col52 varchar(255),
col53 varchar(255),
col54 varchar(255),
col55 varchar(255),
col56 varchar(255),
col57 varchar(255),
col58 varchar(255),
col59 varchar(255),
col60 varchar(255),
col61 varchar(255),
col62 varchar(255),
col63 varchar(255),
col64 varchar(255),
col65 varchar(255),
col66 varchar(255),
col67 varchar(255),
col68 varchar(255),
col69 varchar(255),
col70 varchar(255),
col71 varchar(255),
col72 varchar(255),
col73 varchar(255),
col74 varchar(255),
col75 varchar(255),
col76 varchar(255),
col77 varchar(255),
col78 varchar(255),
col79 varchar(255),
col80 varchar(255),
col81 varchar(255),
col82 varchar(255),
col83 varchar(255),
col84 varchar(255),
col85 varchar(255),
col86 varchar(255),
col87 varchar(255),
col88 varchar(255),
col89 varchar(255),
col90 varchar(255),
col91 varchar(255),
col92 varchar(255),
col93 varchar(255),
col94 varchar(255),
col95 varchar(255),
col96 varchar(255),
col97 varchar(255),
col98 varchar(255),
col99 varchar(255),
col100 varchar(255)
);

数据文件其中两行：
`108,-28388,67092503,2358820326938657486,120,34575,1275115305,8467509765257601238,3.4159,1.1968,"?OPQR.STU-_+=VWXYZa",5988-10-06,3715-03-10 14:32:32,2010-01-12 08:19:47,true,694.21,"?OPQR.STU-_+=VWXYZab","DEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZa","PQR.STU-_+=VWXY","BCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnop","+=VWXYZabcdefghigklmnop",BCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrst,G;KL/MN?OPQR.STU-_+=VWXYZabc,?OPQR.STU-_+=VWXYZabcdefghigklmnop,+=VWXYZabcdefghigklmnopqrstuvwxyz012345,QR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012,"G;KL/MN?OPQR.STU-_+=V","STU-_+=VWXYZabcdefghigkl","KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrs","R.STU-_+=VWXYZabcdefghigklmnopqrstuv","G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh",?OPQR.STU-_+=,_+=VWXYZabcdefghigklmnopqrstuvwxyz0,,GHI,G;KL/MN?OPQR.STU-_+=VW,CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZa,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvw,"TU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01234567","+=VWXYZabcd","CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwx","BCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123456","PQR.STU-_+=VWXYZabcdefgh",,G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh,OPQR.STU-_+=VWXYZ,_+=VWXYZabcdefghigklmnopqrs,I,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0,QR.STU-_+=VWXYZabcd,"QR.STU-_+=VWXYZabcdefgh","CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopq","EF,GHI,G;KL/MN?OPQR.STU-_+=VWX","+=VWXYZabcdefghigklmnopqr","G;KL/MN?OPQR.STU-_+=VWXY",BCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqr,I,G;KL/MN?OPQR.STU-_+=VWXYZabcdef,OPQR.STU-_+=VWXYZabcdefghigk,TU-_+=VWXYZabcdefghigklmnopqrstuv,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123456,"R.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012","HI,G;KL/MN?OPQR.STU-_+=VWXYZabcdef","PQR.STU-_+=VWXYZabcdefghig","BCDEF,GHI,G;KL/MN?OPQR.STU-_+=V","EF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigkl",-_+=VWXYZab,MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuv,R.STU-_+=VWXYZabcde,R.STU-_+=VWXYZabcdefghigklmn,N?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0,"HI,G;KL/MN?OPQR.STU-_+=VWXYZ","STU-_+=VWXYZabcdefghigklmnop","ABCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefg","=VWXYZabcdefg","I,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmno",CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcd,KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqr,HI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmn,,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh,EF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigk,".STU-_+=VWXYZabcdefg",";KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz","HI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01","=VWXYZabcde","+=VWXYZabcdefghigklmnopqrstuvwxyz012345",I,G;KL/MN?OPQR.STU-_+=VWXYZab,DEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrs,?OPQR.STU-_+=VWXYZabc,L/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz,STU-_+=VWXYZ,"L/MN?OPQR.STU-_+=VWXYZabc",".STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123456","CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcd","TU-_+=VWXYZabcde","CDEF,GHI,G;KL/MN?OPQR.STU-_+=",N?OPQR.STU-_+=VWXYZabcdefghigklmno,I,G;KL/MN?OPQR.STU-_+=,I,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrs,G;KL/MN?OPQR.STU-_+=VWXYZabcd,TU-_+=VWXYZabcdefghigklmnopqr,"F,GHI,G;KL/MN?OPQR.STU-_+=VW","MN?OPQR.STU-_+=VWXYZabcd","N?OPQR.STU-_+=VWXYZabcdefghigkl","/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01234"
-38,30280,-1318247814,7035663630373816559,231,39576,3641028343,9938266317908992345,4.0119,0.3783,"DEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnop",6367-01-22,7863-01-06 06:08:03,1994-04-12 01:15:48,false,171.15,"+=VWXYZabcdefghigklmnopqrstu","/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrs","N?OPQR.STU-_+=VWXYZabcdefghig",";KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012",".STU-_+=VWXYZabcdefghigklmnopq",,GHI,G;KL/MN?OPQR.STU-_+=VWXYZab,.STU-_+=VWXYZabcdefghigklmnopqr,;KL/MN?OPQR.STU-_+=VWXYZabcdefghigk,DEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZa,.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01234,"_+=VWXYZabc","KL/MN?OPQR.STU-_+=VWXYZabcd",";KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvw","?OPQR.STU-_+=VWXYZabcdefghigklmnopqrs","PQR.STU-_+=VWXYZabcdefghigklmnopqrstuv",N?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy,I,G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh,L/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345,,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345678,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrst,",G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy","MN?OPQR.STU-_+=V","-_+=VWXYZabcdefghigklmnopqr","_+=VWXYZabcdefghigklmnopqrst","OPQR.STU-_+=VWXYZabcde",QR.STU-_+=VWXYZabcdefghigklmnopqr,U-_+=VWXYZabcdefghigklm,HI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefg,N?OPQR.STU-_+=VWXYZabcdefghigklmnop,_+=VWXYZabcdefghigklmnopqrstuvwxyz01234,"F,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh","U-_+=VWXYZabcdefghigklmnopqrs","I,G;KL/MN?OPQR.STU-_+=VWXY","-_+=VWXYZa","TU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345678",DEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefgh,;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01234567,KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123,QR.STU-_+=VWXYZabcdefghigklmnopqr,OPQR.STU-_+=V,"?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxy","?OPQR.STU-_+=VWXYZab",",GHI,G;KL/MN?OPQR.STU-_+=VWXYZabc","EF,GHI,G;KL/MN?OPQR.STU-_+=VW","?OPQR.STU-_+=VWXYZabcdefg",ABCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz,HI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghig,KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvw,QR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01234567,,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmn,"STU-_+=VWXYZabc","U-_+=VWXYZabcdefghigklmnopqrs","-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123456","MN?OPQR.STU-_+=V","BCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrst",CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefg,PQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123,I,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0123456,,G;KL/MN?OPQR.STU-_+=VWXYZabcdef,U-_+=VWXYZabcdefghigklmnopqrstuv,"_+=VWXYZabcdefghigklmnopqrstuvwx",",GHI,G;KL/MN?OPQR.STU-_+=VWXYZa",",G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnop","STU-_+=VWXYZ","+=VWXYZabcdefghigklmnopqr",ABCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklm,EF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefg,-_+=VWXYZabcdefghigklmnop,=VWXYZabcdefghigklmnopqrstuvwxyz012,=VWXYZa,",G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrs","+=VWXYZabcde","EF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvw","+=VWXYZabcdefghigklmnopqrstuvwxy","ABCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345678",QR.STU-_+=VWXYZabcdefghigkl,QR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz0,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz01,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmn,,GHI,G;KL/MN?OPQR.STU-_+=,"R.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345678",",GHI,G;KL/MN?OPQR.STU-_+=VWXYZabc","CDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstu","BCDEF,GHI,G;KL/MN?OPQR.STU-_+=VWXYZabcdefghigklmnopqrstuvwxyz012345678"`

**Comment by huby2358** [comment]
前面与产品对齐，修改了load的column列数和load文件中列数不相等的情况下，报错，这个issue报错是因为load的数据文件列数超过了表的列数，是预期的报错，目前测试这边正和产品讨论是不是要恢复到以前不报错对于这种情况

**Comment by heni02** [comment]
和产品讨论后结果如下：
1.检测列个数和文件个数不同后报错，该行为是mysql在严格模式下STRICT_TRANS_TABLES的预期结果，在非严格模式下mysql不会报错，行为和mo之前一样
2.根据1，mo也需要调整预期行为，和mysql一致，增加严格模式和非严格模式load方式

等待 @huby2358 支持设定严格和非严格模式下load行为

**Comment by heni02** [comment]
7.24回归测试sql_mode设置为非严格模式后，非压缩文件load成功，压缩文件load失败
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10078689263/job/27880921393
<img width="1008" alt="企业微信截图_ffd6dc63-c776-4bb5-af0f-8e4dd7f7fca1" src="https://github.com/user-attachments/assets/3b23a765-76cc-4b39-b97f-e52f8cb91b0d">
<img width="1243" alt="企业微信截图_7b361fe2-6174-4ce7-ac5f-abddae95cd72" src="https://github.com/user-attachments/assets/a0d37414-9968-4b88-bf31-8a85815f9593">
<img width="1373" alt="企业微信截图_5f021bf5-c62e-4e4d-a1b4-8925e9bb60b7" src="https://github.com/user-attachments/assets/1aef842c-9a32-4986-b9a7-ae7b7fdea5f4">

**Comment by heni02** [comment]
confirm,closed
commit:bb8fc0742
<img width="1365" alt="企业微信截图_9d68de20-c2e3-484a-8f09-1036d769236d" src="https://github.com/user-attachments/assets/cd391095-7eb2-46da-94f8-84cec7c17370">
