### ISSUE TITLE
[Subtask]: refactor Stats() like Size()

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#17644]
### Parent Issue

#16438

### Detail of Subtask

Stats() 不应该在实现里处理子表，应该在上层调用传入子表信息，返回后一起处理。类似 Size()
https://github.com/matrixorigin/matrixone/blob/10b91fbe5cba8ba4d87c4b7c230b2dbc63fd9bf1/pkg/sql/plan/function/func_mo.go#L308

**Comment by badboynt1** [comment]
@volgariver6   麻烦改一下

**Comment by volgariver6** [comment]
finished
