### ISSUE TITLE
[Bug]: tpcc10000 warehouses test mo panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17646]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

88e486e11

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tke 4cn tpcc10000 warehouses test 
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/9989751236/job/27658741357
<img width="1274" alt="企业微信截图_9ab50197-34f9-4e8a-a7b2-918b036b8d5a" src="https://github.com/user-attachments/assets/6091dfda-2344-461f-a5a4-ab5e53bfe200">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22PiP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-ben-nightly-88e486e11-20240718%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721392201339%22,%22to%22:%221721392202339%22%7D%7D%7D&schemaVersion=1&orgId=1

panic: runtime error: invalid memory address or nil pointer dereference |  
  |   | 2024-07-19 12:30:02.338 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x3851bd2] |  
  |   | 2024-07-19 12:30:02.338 |   |  
  |   | 2024-07-19 12:30:02.338 | goroutine 7712538 gp=0xc2a831c700 m=25 mp=0xc014808008 [running]: |  
  |   | 2024-07-19 12:30:02.338 | panic({0x431b140?, 0x7e6b680?}) |  
  |   | 2024-07-19 12:30:02.338 | /usr/local/go/src/runtime/panic.go:779 +0x158 fp=0xc0eec9b658 sp=0xc0eec9b5a8 pc=0x4439f8 |  
  |   | 2024-07-19 12:30:02.338 | runtime.panicmem(...) |  
  |   | 2024-07-19 12:30:02.338 | /usr/local/go/src/runtime/panic.go:261 |  
  |   | 2024-07-19 12:30:02.338 | runtime.sigpanic() |  
  |   | 2024-07-19 12:30:02.338 | /usr/local/go/src/runtime/signal_unix.go:881 +0x378 fp=0xc0eec9b6b8 sp=0xc0eec9b658 pc=0x45d218 |  
  |   | 2024-07-19 12:30:02.338 | github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getProtocol(0x5620518?) |  
  |   | 2024-07-19 12:30:02.338 | /go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:146 +0x32 fp=0xc0eec9b710 sp=0xc0eec9b6b8 pc=0x3851bd2 |  
  |   | 2024-07-19 12:30:02.338 | github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handshake(0xc002e49110?, 0xc0439686e0) |  
  |   | 2024-07-19 12:30:02.338 | /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:198 +0x225 fp=0xc0eec9be58 sp=0xc0eec9b710 pc=0x385dbc5 |  
  |   | 2024-07-19 12:30:02.338 | github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc003114750, {0x566c1d8?, 0xc15294ff70?}) |  
  |   | 2024-07-19 12:30:02.338 | /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:165 +0x1e5 fp=0xc0eec9bfb8 sp=0xc0eec9be58 pc=0x385d505 |  
  |   | 2024-07-19 12:30:02.338 | github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept.gowrap2() |  
  |   | 2024-07-19 12:30:02.338 | /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:153 +0x28 fp=0xc0eec9bfe0 sp=0xc0eec9bfb8 pc=0x385d288 |  
  |   | 2024-07-19 12:30:02.338 | runtime.goexit({}) |  
  |   | 2024-07-19 12:30:02.338 | /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0eec9bfe8 sp=0xc0eec9bfe0 pc=0x47fc61 |  
  |   | 2024-07-19 12:30:02.338 | created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 851 |  
  |   | 2024-07-19 12:30:02.338 | /go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:153 +0xfd

### Steps to Reproduce

```Markdown
tke 4cn tpcc10000 warehouses test
```

**Comment by CJKkkk-315** [comment]
dup: https://github.com/matrixorigin/matrixone/issues/17592
and fix it in https://github.com/matrixorigin/matrixone/pull/17573

**Comment by heni02** [comment]
confirm,closed
