### ISSUE TITLE
[Bug]:  tke regression : sysbench 10w point-select performance degradation.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17657]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ca591a26f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1429" alt="image" src="https://github.com/user-attachments/assets/ebb1d9e8-0e16-43cb-a3b5-4ec06e2260ba">

二分结果：
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/9f85c460-12e0-4dda-b546-9de96ae54338">

@arjunsk ，please help to solve it.

### Steps to Reproduce

```Markdown
daily regression on tke.
```

**Comment by arjunsk** [comment]
Working on it.

**Comment by Ariznawlll** [comment]
**tpcc 100-100 performance degradation result：**
<img width="759" alt="image" src="https://github.com/user-attachments/assets/6bc0cd7a-63e9-4417-9a2c-94b7f7e45aa6">
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/2541616a-cb4b-4e24-b36b-e2d15bff93e7">

**Comment by arjunsk** [comment]
This PR should solve the performance issue

https://github.com/matrixorigin/matrixone/pull/17664

**Comment by arjunsk** [comment]
The PR  is now merged to master. Please retest @Ariznawlll

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**main tke regression：
commit：0d4615515**
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/69dfa292-d5e0-4102-9f04-96548012a142">

random-points性能恢复
