### ISSUE TITLE
[Bug]: `found leak txn` during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#17665]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

91a9f56

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/10043180409

https://github.com/matrixorigin/matrixone/actions/runs/10043180409

### Steps to Reproduce

```Markdown
start merge run test
```

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/10051592994
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cKV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-10051592994%5C%22%7D%20%7C%3D%20%60connectionId%60%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721703651000%22,%22to%22:%221721710251000%22%7D%7D%7D&schemaVersion=1&orgId=1
[CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dda2-61bb-712d-8e71-010818481541.gz](https://github.com/user-attachments/files/16343520/CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dda2-61bb-712d-8e71-010818481541.gz)
[CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dd90-11bd-7d15-9b10-fc01949a9e85.gz](https://github.com/user-attachments/files/16343521/CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dd90-11bd-7d15-9b10-fc01949a9e85.gz)

**Comment by guguducken** [comment]
namespace: mo-checkin-regression-10051469146
workflow run: https://github.com/matrixorigin/ci-test/actions/runs/10051469146
相应的日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cKV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-10051469146%5C%22%7D%20%7C%3D%20%60connectionId%60%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1 

抓到的goroutine： 
[CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd88-ce39-724e-9069-73469edc08a9.gz](https://github.com/user-attachments/files/16343692/CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd88-ce39-724e-9069-73469edc08a9.gz)

[CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190dd9a-feed-7af8-8e90-09176b7ebef2.gz](https://github.com/user-attachments/files/16343694/CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190dd9a-feed-7af8-8e90-09176b7ebef2.gz)
[CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190ddad-4edf-704f-8b96-fcbdc4d8a8a0.gz](https://github.com/user-attachments/files/16343695/CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190ddad-4edf-704f-8b96-fcbdc4d8a8a0.gz)
[CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190ddad-6e82-7cd2-8ff4-6b309a630af2.gz](https://github.com/user-attachments/files/16343696/CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190ddad-6e82-7cd2-8ff4-6b309a630af2.gz)
[CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd9b-1e8e-7bb7-9504-237f6279ba9b.gz](https://github.com/user-attachments/files/16343697/CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd9b-1e8e-7bb7-9504-237f6279ba9b.gz)

其中profile与goroutine的对应关系为
0190dd88-ce39-724e-9069-73469edc08a9：1623
0190dd9b-1e8e-7bb7-9504-237f6279ba9b: 1623
0190dd9a-feed-7af8-8e90-09176b7ebef2: 0
0190ddad-6e82-7cd2-8ff4-6b309a630af2: 1623
0190ddad-4edf-704f-8b96-fcbdc4d8a8a0: 0

**Comment by daviszhen** [comment]
> namespace: mo-checkin-regression-10051469146 workflow run: https://github.com/matrixorigin/ci-test/actions/runs/10051469146 相应的日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cKV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-10051469146%5C%22%7D%20%7C%3D%20%60connectionId%60%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
> 
> 抓到的goroutine： [CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd88-ce39-724e-9069-73469edc08a9.gz](https://github.com/user-attachments/files/16343692/CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd88-ce39-724e-9069-73469edc08a9.gz)
> 
> [CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190dd9a-feed-7af8-8e90-09176b7ebef2.gz](https://github.com/user-attachments/files/16343694/CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190dd9a-feed-7af8-8e90-09176b7ebef2.gz) [CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190ddad-4edf-704f-8b96-fcbdc4d8a8a0.gz](https://github.com/user-attachments/files/16343695/CN_34306530-3033-6262-3138-633936616265_leakcheck_routine_0190ddad-4edf-704f-8b96-fcbdc4d8a8a0.gz) [CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190ddad-6e82-7cd2-8ff4-6b309a630af2.gz](https://github.com/user-attachments/files/16343696/CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190ddad-6e82-7cd2-8ff4-6b309a630af2.gz) [CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd9b-1e8e-7bb7-9504-237f6279ba9b.gz](https://github.com/user-attachments/files/16343697/CN_36646164-6131-3263-3836-353239336361_leakcheck_routine_0190dd9b-1e8e-7bb7-9504-237f6279ba9b.gz)
> 
> 其中profile与goroutine的对应关系为 0190dd88-ce39-724e-9069-73469edc08a9：1623 0190dd9b-1e8e-7bb7-9504-237f6279ba9b: 1623 0190dd9a-feed-7af8-8e90-09176b7ebef2: 0 0190ddad-6e82-7cd2-8ff4-6b309a630af2: 1623 0190ddad-4edf-704f-8b96-fcbdc4d8a8a0: 0



1623 的线程的调用栈 找不到。

**Comment by daviszhen** [comment]
> https://github.com/matrixorigin/ci-test/actions/runs/10051592994
> 
> https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cKV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-10051592994%5C%22%7D%20%7C%3D%20%60connectionId%60%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721703651000%22,%22to%22:%221721710251000%22%7D%7D%7D&schemaVersion=1&orgId=1
> 
> 抓的go rountine:
> 
> [CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dda2-61bb-712d-8e71-010818481541.gz](https://github.com/user-attachments/files/16343520/CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dda2-61bb-712d-8e71-010818481541.gz)
> 
> [CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dd90-11bd-7d15-9b10-fc01949a9e85.gz](https://github.com/user-attachments/files/16343521/CN_36366263-3031-6131-6433-383633663636_leakcheck_routine_0190dd90-11bd-7d15-9b10-fc01949a9e85.gz)

1800 的线程的调用栈 找不到。

**Comment by daviszhen** [comment]
这个问题好尴尬。那不到关键gorotuine的id。从FootPrints看 大概是EndStatement卡住了，但不是没有很强的证据。

FootPrints需要再优化下。

```go
	defer func() {
		if ses.GetTxnHandler() == nil {
			panic("need txn handler 2")
		}

		txnOp = ses.GetTxnHandler().GetTxn()
		if txnOp != nil {
			ses.EnterFPrint(119)
			defer ses.ExitFPrint(119)
			setFPrints(txnOp, execCtx.ses.GetFPrints())
			//most of the cases, txnOp will not nil except that "set autocommit = 1"
			//commit the txn immediately then the txnOp is nil.
			txnOp.GetWorkspace().EndStatement()
		}
	}()
```

**Comment by sukki37** [comment]
Using a binary search, we identified that the problem was introduced by [PR 16656](https://github.com/matrixorigin/matrixone/pull/16636).

https://doc.weixin.qq.com/sheet/e3_AUMA6gbUAEcm2fmYWbkTFenHz4NX8?scode=AJsA6gc3AA8ZvaOmYMAUMA6gbUAEc&tab=BB08J2

**Comment by ck89119** [comment]
backSession获取环境变量autocommit的问题，之前backSession的autocommit值写死为true：
<img width="1569" alt="image" src="https://github.com/user-attachments/assets/b31f23ee-f98a-4ec2-a0b1-03ce63496733">
<img width="1533" alt="image" src="https://github.com/user-attachments/assets/500fdd6f-9e83-4902-a9f1-82c5ba24256b">

重构之后autocommit由父session继承而来，可能会在执行过程中被改成false，导致txn没有被commit

**Comment by aressu1985** [comment]
查看稳定性测试，没有再出现leak，问题单先关闭
