### ISSUE TITLE
[Bug]: frontend socket cannot close

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17668]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1185" alt="企业微信截图_8f0d8f78-efdc-41f0-8268-bf24bed683c7" src="https://github.com/user-attachments/assets/e1325682-f364-4269-b0ca-ae3398faa4ca">

restart cn in cluster testing.  MOServer close cannot close socket listener

### Steps to Reproduce

```Markdown
run cluster testing framework
```

**Comment by CJKkkk-315** [comment]
fixed
![image](https://github.com/user-attachments/assets/fc8d4092-4288-4126-8ece-4ed2ecb8ad4b)
