### ISSUE TITLE
[Bug]: standalone tpcc 10/100 connections Communications link failure

### ISSUE THREAD

**Issue by jiangxinmeng1** [matrixorigin/matrixone#17679]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

93043522e4b646619cfcd786ea89b00ccaa65756

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

跑15分钟后开始报The connection[75] has not been valid, caused by: Communications link failure，然后卡死连不上mysql

### Steps to Reproduce

用launch-with-proxy启动mo-service

./mo-service -launch ./etc/launch-with-proxy/launch.toml -debug-http :6060 > 1 &> store.log
```
跑tpcc 10 warehouses, 100 terminals,
大概15分钟后开始报错。
```

 
<img width="1323" alt="2f7ef3eb4c576b61b445a1c7dbe7889" src="https://github.com/user-attachments/assets/6a815ac8-6188-4cf1-96e4-64681e5c3da0">

[goroutine2.log](https://github.com/user-attachments/files/16356016/goroutine2.log)

**Comment by jiangxinmeng1** [comment]
[goroutine2.log](https://github.com/user-attachments/files/16356068/goroutine2.log)

**Comment by ouyuanning** [comment]
<img width="1323" alt="2f7ef3eb4c576b61b445a1c7dbe7889" src="https://github.com/user-attachments/assets/6a815ac8-6188-4cf1-96e4-64681e5c3da0">

[goroutine2.log](https://github.com/user-attachments/files/16356016/goroutine2.log)

**Comment by ouyuanning** [comment]
多CN，单独跑tpcc，15分钟以上

**Comment by ouyuanning** [comment]
有可能跟https://github.com/matrixorigin/matrixone/issues/17665这个有关系

**Comment by jensenojs** [comment]
repro on sysbench

https://github.com/matrixorigin/matrixone/actions/runs/10448322057/job/28929680161

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展
