### ISSUE TITLE
[Bug]: cn crash by runtime error: index out of range [0] with length 0 during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17680]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c91a773

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

cn crash by runtime error: index out of range [0] with length 0 during stability test on distributed mode:
{"level":"ERROR","time":"2024/07/23 17:55:29.785764 +0000","name":"cn-service","caller":"frontend/util.go:506","msg":"query trace status","service":"33373937-3138-3030-3233-343638316234","uuid":"33373937-3138-3030-3233-343638316234","statement":"UPDATE sbtest10 SET k=k+100 WHERE id = 96797","status":"fail","error":"internal error: panic runtime error: index out of range [0] with length 0: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:114\ngithub.com/matrixorigin/matrixone/pkg/container/types.(*Packer).putByte\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/types/tuple.go:299\ngithub.com/matrixorigin/matrixone/pkg/container/types.(*Packer).EncodeInt32\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/types/tuple.go:406\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay.EncodePrimaryKey\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailreplay/encode.go:236\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newMemPKFilter\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/pk_filter_mem.go:170\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).NewReader\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:1773\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).NewReader\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:230\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).getReaders\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:1225\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:560\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:428\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:366\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:413\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func2\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:734\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695","txn_info":"0190e0bbe97678dea1d24060b987e9ac:1721757329777712140-11","session_info":"connectionId 31413||{account sysbench_test1:admin:accountadmin -- 10001:2:2}|goRoutineId 47739|migrate-goRoutineId 0|0190dd62-3a8a-790b-85c7-18faa4335740","session_id":"0190dd62-3a8a-790b-85c7-18faa4335740","statement_id":"0190e0bb-e976-77ee-9a7a-ec138ae82832","span":{"trace_id":"60d3e1d8-aee5-70ed-d6c8-695e48795b44","span_id":"813df64c2a85a1b3"}}

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22Mgq%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-c91a773-202407231010%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721748205668%22,%22to%22:%221721757960507%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by XuPeng-SH** [comment]
depends on #16965 

The root cause is mpool out of memory.

![image](https://github.com/user-attachments/assets/2f93a63a-0862-4031-91bc-b97209e51d4d)

And in tuple.go, it ignores the out of memory error from mpool and causes `the index of range [0]` error later.

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/1534a7d2-8118-4e92-8e94-e4f8d80b69d9">

**Comment by ouyuanning** [comment]
乐声先帮忙跟Vector Free的那个问题一起看一下吧。

**Comment by reusee** [comment]
已修正

**Comment by aylei** [comment]
reproduced in moc prod:

```
panic: runtime error: index out of range [0] with length 0
```

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
