### ISSUE TITLE
[Bug]: json type does not work in prepared statement

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17707]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

07ce67c97993c99f69ce4ff4212a3d08d32367b7

### Other Environment Information

```Markdown
- Hardware parameters: MacBook Pro, M2.
- OS type: Mac OSX
- Others:
```

### Actual Behavior

Json parameter in prepared statement does not work

### Steps to Reproduce

```Markdown
create table t (I int, j json);
prepare st1 from 'insert into t values (?, ?)';
set @a = 1;
set @b = '[1,2]';
execute st1 using @a, @b;
select * from t;
```
```


### Additional information

_No response_

**Comment by heni02** [comment]
commit:f4f2dd01c464f020a19f801d2bbf30582f8a7d6d
confirm,closed
mysql> create database db;
Query OK, 1 row affected (0.05 sec)

mysql> use db;
Database changed
mysql> create table t (I int, j json);
Query OK, 0 rows affected (0.05 sec)

mysql> prepare st1 from 'insert into t values (?, ?)';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> set @b = '[1,2]';
Query OK, 0 rows affected (0.00 sec)

mysql> execute st1 using @a, @b;
Query OK, 1 row affected (0.03 sec)

mysql> select * from t;
+------+--------+
| i    | j      |
+------+--------+
|    1 | [1, 2] |
+------+--------+
1 row in set (0.00 sec)
