### ISSUE TITLE
[Bug]: Instance crashed during SSB Q4.3 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1770]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dd3e4b1445bda50bb6244c538fc4d48cd15ef03b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select year(d_datekey) as d_year, s_city, p_brand, sum(lo_revenue) - sum(lo_supplycost) as profit
    -> from lineorder
    -> join dates on lo_orderdate = d_datekey
    -> join customer on lo_custkey = c_custkey
    -> join supplier on lo_suppkey = s_suppkey
    -> join part on lo_partkey = p_partkey
    -> group by d_year, s_city, p_brand
    -> order by d_year, s_city, p_brand;
ERROR 2013 (HY000): Lost connection to MySQL server during query

### Additional information

{"level":"DEBUG","time":"2022/02/25 11:53:51.495006 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1027,"type":16}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495724 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1028,"type":4}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495759 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1029,"type":16}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495773 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1030,"type":4}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495786 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1031,"type":16}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495797 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1032,"type":4}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495807 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1033,"type":16}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495833 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1034,"type":4}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495862 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1035,"type":16}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495873 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1036,"type":4}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495885 +0800","name":"cube.prophet.client.watcher","caller":"prophet/watcher.go:150","msg":"read event","node":"node0","seq":1037,"type":16}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495926 +0800","name":"cube.store.router","caller":"raftstore/router.go:339","msg":"shard route updated","store":"node0","shard":"shard-id: 6, shard-group: 1, shard-epoch: 0/1, shard-range: [616f652d0000000000000002, 616f652d0000000000000003), replicas: [10/1/Voter], shard-state: Creating, shard-unique: 1-1-2, shard-disable-split: false, shard-labels: [LabelTable:part]","leader":10}
{"level":"INFO","time":"2022/02/25 11:53:51.495946 +0800","name":"cube.store.router","caller":"raftstore/router.go:375","msg":"shard leader updated","store":"node0","shard-id":6,"leader-replica":"10/1/Voter","address":"localhost:20000"}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495966 +0800","name":"cube.store.router","caller":"raftstore/router.go:339","msg":"shard route updated","store":"node0","shard":"shard-id: 13, shard-group: 1, shard-epoch: 0/1, shard-range: [616f652d0000000000000005, 616f652d0000000000000006), replicas: [17/1/Voter], shard-state: Creating, shard-unique: 1-1-5, shard-disable-split: false, shard-labels: [LabelTable:dates]","leader":17}
{"level":"INFO","time":"2022/02/25 11:53:51.495977 +0800","name":"cube.store.router","caller":"raftstore/router.go:375","msg":"shard leader updated","store":"node0","shard-id":13,"leader-replica":"17/1/Voter","address":"localhost:20000"}
{"level":"DEBUG","time":"2022/02/25 11:53:51.495994 +0800","name":"cube.store.router","caller":"raftstore/router.go:339","msg":"shard route updated","store":"node0","shard":"shard-id: 2, shard-group: 0, shard-epoch: 1/1, shard-range: [, ), replicas: [3/1/Voter], shard-state: Running, shard-disable-split: false","leader":3}
{"level":"INFO","time":"2022/02/25 11:53:51.496004 +0800","name":"cube.store.router","caller":"raftstore/router.go:375","msg":"shard leader updated","store":"node0","shard-id":2,"leader-replica":"3/1/Voter","address":"localhost:20000"}
{"level":"DEBUG","time":"2022/02/25 11:53:51.496019 +0800","name":"cube.store.router","caller":"raftstore/router.go:339","msg":"shard route updated","store":"node0","shard":"shard-id: 5, shard-group: 1, shard-epoch: 0/1, shard-range: [616f652d0000000000000001, 616f652d0000000000000002), replicas: [9/1/Voter], shard-state: Creating, shard-unique: 1-1-1, shard-disable-split: false, shard-labels: [LabelTable:lineorder]","leader":9}
{"level":"INFO","time":"2022/02/25 11:53:51.496031 +0800","name":"cube.store.router","caller":"raftstore/router.go:375","msg":"shard leader updated","store":"node0","shard-id":5,"leader-replica":"9/1/Voter","address":"localhost:20000"}
{"level":"DEBUG","time":"2022/02/25 11:53:51.496044 +0800","name":"cube.store.router","caller":"raftstore/router.go:339","msg":"shard route updated","store":"node0","shard":"shard-id: 7, shard-group: 1, shard-epoch: 0/1, shard-range: [616f652d0000000000000003, 616f652d0000000000000004), replicas: [11/1/Voter], shard-state: Creating, shard-unique: 1-1-3, shard-disable-split: false, shard-labels: [LabelTable:supplier]","leader":11}
{"level":"INFO","time":"2022/02/25 11:53:51.496288 +0800","name":"cube.store.router","caller":"raftstore/router.go:375","msg":"shard leader updated","store":"node0","shard-id":7,"leader-replica":"11/1/Voter","address":"localhost:20000"}
{"level":"DEBUG","time":"2022/02/25 11:53:52.456703 +0800","name":"cube.prophet","caller":"v3rpc/lease.go:118","msg":"failed to receive lease keepalive request from gRPC stream","node":"node0","error":"rpc error: code = Canceled desc = context canceled"}
{"level":"DEBUG","time":"2022/02/25 11:53:52.487984 +0800","name":"cube.store.shard-pool","caller":"raftstore/store_shards_pool.go:293","msg":"dynamic shards pool check create","store":"node0"}
{"level":"DEBUG","time":"2022/02/25 11:53:52.488061 +0800","name":"cube.store.shard-pool","caller":"raftstore/store_shards_pool.go:295","msg":"dynamic shards pool job maybeCreate completed","store":"node0"}
{"level":"DEBUG","time":"2022/02/25 11:53:53.456767 +0800","name":"cube.prophet","caller":"v3rpc/lease.go:118","msg":"failed to receive lease keepalive request from gRPC stream","node":"node0","error":"rpc error: code = Canceled desc = context canceled"}
{"level":"DEBUG","time":"2022/02/25 11:53:53.487207 +0800","name":"cube.store.shard-pool","caller":"raftstore/store_shards_pool.go:293","msg":"dynamic shards pool check create","store":"node0"}
{"level":"DEBUG","time":"2022/02/25 11:53:53.487266 +0800","name":"cube.store.shard-pool","caller":"raftstore/store_shards_pool.go:295","msg":"dynamic shards pool job maybeCreate completed","store":"node0"}
{"level":"DEBUG","time":"2022/02/25 11:53:54.457411 +0800","name":"cube.prophet","caller":"v3rpc/lease.go:118","msg":"failed to receive lease keepalive request from gRPC stream","node":"node0","error":"rpc error: code = Canceled desc = context canceled"}
{"level":"DEBUG","time":"2022/02/25 11:53:54.487244 +0800","name":"cube.store.shard-pool","caller":"raftstore/store_shards_pool.go:293","msg":"dynamic shards pool check create","store":"node0"}
{"level":"DEBUG","time":"2022/02/25 11:53:54.487302 +0800","name":"cube.store.shard-pool","caller":"raftstore/store_shards_pool.go:295","msg":"dynamic shards pool job maybeCreate completed","store":"node0"}
Killed

**Comment by JinHai-CN** [comment]
High cardinality will cause high memory consumption. Before #1750 is fixed, the OOM will happen again in this case.

**Comment by yingfeng** [comment]
This requires several improvements to be refined:

- Refined memory management for queries, this has close relationship with #1750
- Better memory management for golang, as mentioned in [golang community](https://github.com/golang/go/issues/51317)
- Spill processing logic or other similar solutions, such as remove parts of lines in hashtable if memory is not enough

**Comment by LeftHandCold** [comment]
<img width="2096" alt="image" src="https://user-images.githubusercontent.com/14086886/155919360-0b94e1cd-23fd-43a9-9c42-76f052080a76.png">
Verified version 0.2.0, repeated execution of Q4.3 Q4.2 Q4.1 can be reproduced.
