### ISSUE TITLE
[Bug]: Checkin Regression  SYSBENCH TEST failed in timed out 

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#17704]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="984" alt="image" src="https://github.com/user-attachments/assets/5f3ac018-173b-462c-bc04-d28e42653b54">

 job link：
https://github.com/matrixorigin/matrixone/actions/runs/10075532045/job/27855747649

**accoring to the log, the prepared time is to long**
2024-07-24 11:58:25 INFO MOPerfTest:109 - The test will last for 20 minutes.
2024-07-24 12:08:20 INFO MOPerfTest:202 - All the he execution threads has been prepared,and start running.......
2024-07-24 12:28:30 INFO MOPerfTest:244 - This test has been executed successfully, and can get detailed result data in ./report/

loki link
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22vGY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-17339%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721822305000%22,%22to%22:%221721822400000%22%7D%7D%7D&schemaVersion=1&orgId=1

**accoring to the Loki log, there are many warns info in log**

{"level":"WARN","time":"2024/07/24 11:59:55.865476 +0000","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3423","msg":" negative cpu (0190e49c-bda8-7eaf-8e51-c9cebef806eb) + statsInfo(27932 + 0 + 7504 - 19884577 - 4793654) = -24642795","service":"30643032-3530-6662-3537-643161306433","uuid":"30643032-3530-6662-3537-643161306433","session_info":"connectionId 696||{account tpcc_test:admin:accountadmin -- 10252:2:2}|goRoutineId 94604|migrate-goRoutineId 0|0190e498-2e96-7a6c-9be1-095e06bd4740","session_id":"0190e498-2e96-7a6c-9be1-095e06bd4740","statement_id":"0190e49c-bda8-7eaf-8e51-c9cebef806eb","txn_id":"0190e49cbbe374ba8435149e8a0e5f3e","span":{"trace_id":"fcd18d7f-1c9f-1fe4-5675-d9db524caee8","span_id":"96ce2774a5e0c7df"}}

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10075532045/job/27855747649
```

**Comment by ouyuanning** [comment]
苏动看能不能把这个限制放大一点。比如放大到32-35分钟？

**Comment by sukki37** [comment]
tracked by #17703
