### ISSUE TITLE
[Bug]: [date: 0725] main tke regression: 10w point-select 100 thread hung.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17715]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

848f27839

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10078689263/job/27881737386

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/95dfb44a-a53f-48de-b534-19b64abda359">

log : https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22JVZ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-848f27839-20240724%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221721855135000%22,%22to%22:%221721866965000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
main regression on tke
```

**Comment by daviszhen** [comment]
从nightly-devops 机器的/root/issue17715 的goroutine 看卡住不是出在cn端。

**Comment by daviszhen** [comment]
![image](https://github.com/user-attachments/assets/aca3f438-c06a-4473-aa83-c2d9c2fbc5be)

**Comment by daviszhen** [comment]
cn trace 分析结果
[cn_trace.zip](https://github.com/user-attachments/files/16373132/cn_trace.zip)



![image](https://github.com/user-attachments/assets/aca3f438-c06a-4473-aa83-c2d9c2fbc5be)

![image](https://github.com/user-attachments/assets/b881053d-8723-453a-99d1-8538fc4b4b58)

![image](https://github.com/user-attachments/assets/477ea8ae-526c-4efa-80f8-f603cd07262f)
 

![image](https://github.com/user-attachments/assets/0f1bd861-d778-4060-9456-27b88248f92f)

**Comment by daviszhen** [comment]
从上面的结果看，只能说是有block的时间长。不好说一定卡在里面了。

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
没出现了
