### ISSUE TITLE
[Feature Request]: remove strange txn usage

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#17731]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
https://github.com/matrixorigin/matrixone/issues/17665
```

### Describe the feature you'd like

删除 doDropFunction,doDropFunctionWithDB,doDropProcedure 里面嵌套事务的使用。

**Comment by YANGGMM** [comment]
finished

**Comment by daviszhen** [comment]
done
