### ISSUE TITLE
[Refactoring]: ColumnExpressonExecutor.Eval XXX must be fixed.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17749]
### Why do you want to refactor this code?

```Markdown
The XXX comment in Eval clearly indicate this is a BUG.  It cannot be hacked around.
```

### Describe the solution you'd like

Find the root cause and fix.

**Comment by m-schen** [comment]
已经移除了由于join导致的出现RelPos > length(data)的情况。
但是存在RelPos < 0的情况，这块代码我不熟悉，修改难度很大，因此创建了以下issue待解决。

https://github.com/matrixorigin/matrixone/issues/19574
