### ISSUE TITLE
[Bug]: ten_table_sharding.go line 233

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17756]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

61a9ffc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

It is obviously a bug.   golang warning is correct

### Steps to Reproduce

```Markdown
Read code.
```

**Comment by iamlinjunhong** [comment]
请假

**Comment by iamlinjunhong** [comment]
pr 中

**Comment by iamlinjunhong** [comment]
还未处理

**Comment by iamlinjunhong** [comment]
后续会有 pr 合入

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/17878 已修改
