### ISSUE TITLE
[Bug]: [date 7.28] tke regression: mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17762]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cc327fc40

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:
从这个时间开始无法连接到mo
![image](https://github.com/user-attachments/assets/e3fc6d06-875a-4bc5-b64d-dbee5d21eb4b)
登陆环境验证，也是无法登陆
![image](https://github.com/user-attachments/assets/4602f33e-14a9-430c-ae5b-51cb1ec3e3d5)
![image](https://github.com/user-attachments/assets/b00e842f-c458-4caf-b05d-a03305f4e66a)

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22iWs%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-cc327fc40-20240728%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722190500000%22,%22to%22:%221722241149000%22%7D%7D%7D&schemaVersion=1&orgId=1

RPC：
https://grafana.ci.matrixorigin.cn/d/a3f69f81-a200-4efc-b11a-9fc1536f2340/rpc-metrics?orgId=1&var-interval=1m&var-namespace=mo-main-nightly-cc327fc40-20240728&var-pod=All&from=1722155459283&to=1722241859283

### Steps to Reproduce

```Markdown
tke regression tpcc test
```

**Comment by volgariver6** [comment]
从日志看不出来问题，需要在环境中加上proxy的heap profile，麻烦 @guguducken 配置一下

**Comment by volgariver6** [comment]
大概率是 pr #17713 导致的，revert 这个pr再跑一下

**Comment by volgariver6** [comment]
revert 之后没有hang了

**Comment by heni02** [comment]
confirm,closed
