### ISSUE TITLE
[Bug]: [date 7.27]standalone: tpcc 1000warehouse 1000threads  test Consistency verification failed 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17765]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dfcc37d13f3e0e0140895836536ee26939eedbd9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10130195227/job/28011266080
<img width="1490" alt="企业微信截图_ac56d15d-3224-437e-a8c5-a9b8acff21ba" src="https://github.com/user-attachments/assets/a02d6851-118b-4a88-99da-b1adbfd26c51">

mo log：（日志时间➕8）
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-dfcc37d-20240729-034337.log%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722092195391%22,%22to%22:%221722264995391%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
standalone tpcc 1000 warehouse 1000 threads test
```

**Comment by ouyuanning** [comment]
预计这个PR合并进去之后就好了
https://github.com/matrixorigin/matrixone/pull/17764

**Comment by ouyuanning** [comment]
revert的PR已合并。再观察看看

**Comment by heni02** [comment]
confirm,closed
