### ISSUE TITLE
[Bug]: [date:0730] standalone: ssb 10g and tpch test panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17782]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ea1f0db3d5999a28e0a1db352b90caeae6b3db62

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10146177272/job/28057387248

ssb test：
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/78f6bb9e-b480-4f53-a87c-87e16f103885">

tpch test：
<img width="858" alt="image" src="https://github.com/user-attachments/assets/e12419c9-8b4e-4a1a-8adb-74a8e6c6bbd1">

### Steps to Reproduce

```Markdown
trigger 128 regression
```

**Comment by badboynt1** [comment]
引入问题的pr已经回滚

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
先降级，今晚观察一下

**Comment by Ariznawlll** [comment]
已修复
