### ISSUE TITLE
[Bug]: [date 7.30]standalone regression: sysbench 10w update-non-index reported w-w conflict error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17807]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f2257da9d1b490f6d1144e2423ea21bf9406c4bd

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10164221231/job/28109309642
<img width="1030" alt="企业微信截图_0a261886-eef6-4730-ad22-7647eea5494e" src="https://github.com/user-attachments/assets/4e9b7af0-fa24-4d35-9bfd-2b519f874517">

mo log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-f2257da-20240731-020355.log%5C%22%7D%20%7C%3D%20%60w-w%20conflict%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722327685826%22,%22to%22:%221722414085826%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_update_non_index.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10   prepare
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_update_non_index.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=300 --report-interval=10  --range_selects=off --point_selects=1 run
```

**Comment by ouyuanning** [comment]
还没看

**Comment by ouyuanning** [comment]
还不知道从哪里入手

**Comment by ouyuanning** [comment]
PR已经revert，可以再观察下

**Comment by ouyuanning** [comment]
可以再观察下

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
先处理DML重构
