### ISSUE TITLE
[Bug]: missing call table_scan.Reader.Close() during pipeline cleanup

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#17821]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

missing call table_scan.Reader.Close() during pipeline cleanup

### Expected Behavior

Reader.Close() should be called at the end of execution.

### Steps to Reproduce

```Markdown
As described.
```

**Comment by ouyuanning** [comment]
还没时间处理。印象中曾经加过这个close，好像是会有问题。待再验证

**Comment by ouyuanning** [comment]
还没时间处理

**Comment by ouyuanning** [comment]
未投入
