### ISSUE TITLE
[Bug]: show create table report 'SQL syntax error'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17822]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

22bfbf393dbd408df4bbf6e1f861690cbaef2c0b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
<img width="828" alt="image" src="https://github.com/user-attachments/assets/99f0d040-f3e7-4f42-a7ea-90262caca5bb">

### Expected Behavior

mysql:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/9df7d6d7-d71d-4cbc-858d-9ce3832cce28">

### Steps to Reproduce

```Markdown
drop table if exists math01;
create table math01 (col1 int default 0, col2 decimal, col3 float, col4 double not null);
insert into math01 values (1, 7382.4324, 432453.3243, -2930.321323);
insert into math01 values (-100, 3283.32324, 328932.0, -9392032);
insert into math01 values (22813, -241, 932342.4324, -0.1);
insert into math01 values (null, null, null, 10);

drop table if exists agg01;
create table agg01 as select avg(col1) as avgCol, sum(col2) as sumcol, count(col3) as countCol, max(col4) as maxCol, min(col4) as minCol from math01;
show create table agg01;
select * from agg01;
drop table agg01;
```

**Comment by ck89119** [comment]
double类型scale为0时，show create table会展示成 `DOUBLE(0, 0)`

**Comment by Ariznawlll** [comment]
**main-commit：d5a8adf34208a450ead2fcf9da7c56a7a6101a8a**
<img width="878" alt="image" src="https://github.com/user-attachments/assets/80909f46-f4b3-4414-bdd2-d269a13a2519">

测试通过
