### ISSUE TITLE
[Bug]: bvt failed in snapshot_restore_view

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#17825]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![企业微信截图_17224201666826](https://github.com/user-attachments/assets/ae2c3fd6-97d4-46a0-910f-a4db2171af28)

https://github.com/matrixorigin/matrixone/actions/runs/10177559448/job/28149312332?pr=17786

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by aptend** [comment]
dup with #17804
