### ISSUE TITLE
[Tech Request]: tagged read/write throughput metrics for fileservice

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#17835]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
we want to know what module was occupying the largest disk throughput to optimize it.
```

**Comment by volgariver6** [comment]
no need to do this at this time, close it please.
