### ISSUE TITLE
[Bug]:  tpcc failed with `internal error: get prepare params error, index 3 not exists` during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#17839]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9571846

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/10176252038/job/28146930082

log: https://grafana.ci.matrixorigin.cn/goto/FqBjRv9SR?orgId=1

### Steps to Reproduce

```Markdown
start merge run
```

### Additional information

repro: https://github.com/matrixorigin/matrixone/actions/runs/10191654423/job/28194199647

**Comment by ouyuanning** [comment]
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/9a590654-5987-4ba0-8cd7-e2b5f120c01b">
从日志看，对于所执行的sql，应该不存在idx=3的  param expr。估计要先加下日志，看执行错误表达式的地方是哪里

**Comment by ouyuanning** [comment]
本地跑了2轮30分钟单CN，2轮30分钟多CN，没有复现。
暂时还没有想到什么情况下，会产生这个错误的表达式

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/10219048974/job/28278378641

**Comment by xzxiong** [comment]
Repro https://github.com/matrixorigin/matrixone/actions/runs/10229023974/job/28302769629

**Comment by ouyuanning** [comment]
今日进展
1、往前二分还没有结论，目前从这个测试
https://github.com/matrixorigin/ci-test/actions/runs/10245391628
可以知道，这个PR
https://github.com/matrixorigin/matrixone/pull/17721      对应的commit是可以复现的
因为偶发性，二分并不顺利，还要继续往前推看看

2、加日志来看，
出问题的是在scope.run的时候，设置datasource的block filter的时候，拿到的expr是不对的。
有2种可能：1、被改了，   2、生成的时候就不对
目前还在加日志先确定上面2个可能是哪一种。盲看了前面的一些PR，没有看出来有哪个地方会重设这个表达式

**Comment by ouyuanning** [comment]
2的部分，目前看来是第一次拿到的 n.blocklist 的expr就不对。应该是  serial(param_2,param_1,param_0)的，现在看到的是 serial(param_3,param_2,param_1)。  再取 param_3的时候，发现3这个index不存在。

**Comment by ouyuanning** [comment]
直接原因是当retry的时候，重新构建的那个plan没有被正确的标识为prepare类的plan，所以没有正确的设置param index

但是不知道为啥最近retry的概率变大，于是能比较好的复现bug。

**Comment by ouyuanning** [comment]
已合并，辛苦QA再观察看看

**Comment by heni02** [comment]
confirm，closed
