### ISSUE TITLE
[Bug]: [date 7.31]sysbench 10w no pk auto_inc point select test reported panic runtime error: index out of range [1] with length 0:  runtime.goPanicIndex

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f050588b6

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10182211135/job/28186166818
<img width="1170" alt="企业微信截图_2eb66576-147d-4018-9f22-a2c0ce75baa4" src="https://github.com/user-attachments/assets/51c54228-2080-4daf-b80c-26addb051345">

FATAL: mysql_stmt_execute() returned error 20101 (internal error: panic runtime error: index out of range [1] with length 0: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).SetVector
	/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:175
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).ReplaceVector
	/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:376
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch
	/g) for query 'SELECT c FROM sbtest6 WHERE id=?'
FATAL: `thread_run' function failed: ./oltp_common.lua:410: SQL error, errno = 20101, state = 'HY000': internal error: panic runtime error: index out of range [1] with length 0: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).SetVector
	/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:175
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).ReplaceVector
	/go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:376
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch
	/g

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22LRm%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-f050588b6-20240731%5C%22%7D%20%7C%3D%20%60panic%20runtime%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722414817071%22,%22to%22:%221722501217071%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
sysbench  --mysql-host=172.16.7.101 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=30 --report-interval=10 --secondary=on  --create_secondary=off prepare
sysbench  --mysql-host=172.16.7.101 --mysql-port=6001 --mysql-user=dump --mysql-password=111  oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=300 --report-interval=10 --range_selects=off --point_selects=1 --secondary=on  --create_secondary=off  run
```

**Comment by gouhongshen** [comment]
```
{"level":"ERROR","time":"2024/08/01 01:29:38.750611 +0000","name":"cn-service","caller":"frontend/util.go:506","msg":"query trace status","service":"33623130-6263-3466-3766-333363333965","uuid":"33623130-6263-3466-3766-333363333965","statement":"execute __mo_stmt_id_6 // SELECT c FROM sbtest6 WHERE id=? ; 47349","status":"fail","error":"internal error: panic runtime error: index out of range [1] with length 0:
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:114
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).SetVector
        /go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:175
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).ReplaceVector
        /go/src/github.com/matrixorigin/matrixone/pkg/container/batch/batch.go:376
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/process/process2.go:36
github.com/matrixorigin/matrixone/pkg/sql/colexec/merge.(*Merge).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/merge/merge.go:53
github.com/matrixorigin/matrixone/pkg/sql/colexec/indexjoin.(*IndexJoin).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/indexjoin/join.go:59
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:63
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.(*Output).Call
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/output/output.go:45
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:107
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:84
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:328
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:455
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:377
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:416
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func2
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:743
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1695","txn_info":"01910b8e92bd7624bc7efd546c34cca7:1722475778746237882-1","session_info":"connectionId 62415||{account sys:dump:moadmin -- 0:1:0}|goRoutineId 12927160|migrate-goRoutineId 0|01910b8c-2d92-71d7-a557-8619cdddc7c4","session_id":"01910b8c-2d92-71d7-a557-8619cdddc7c4","statement_id":"01910b8e-92bd-75cd-9133-486f485b7777","span":{"trace_id":"05d9e7d4-642a-dbfd-f148-20d370beca9f","span_id":"71459690b5058e46"}}
```

**Comment by gouhongshen** [comment]
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/f0b61ef9-fb1e-4e41-bc7d-8ee4654e5606">

@badboynt1 根据 nightly 时间范围确定可能跟 17786 相关性比较大，麻烦确认下

**Comment by badboynt1** [comment]
从代码上看，这个panic根本就不应该发生，除非有data race。 但是从代码上又找不到data race发生的可能性。
可能需要再观察一下，看看这个issue是概率复现还是稳定复现。

**Comment by badboynt1** [comment]
修复的pr已经合并

**Comment by heni02** [comment]
confirm，closed
