### ISSUE TITLE
[Bug]: Internal executor reports error when executing SQL, system table does not exist

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#17852]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

d6bf4f97665142bea9eedcec2162a5f512562048

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2024/08/01 03:21:13.245131 +0000","caller":"disttae/txn_database.go:344","msg":"error: SQL parser error: table \"mo_upgrade\" does not exist","span":{"trace_id":"74a2fc22-c386-e50c-45c1-b7140db4dbb3","span_id":"47ecc972d594734b"}}
{"level":"ERROR","time":"2024/08/01 03:21:13.245215 +0000","name":"cn-service.frontend","caller":"frontend/compiler_context.go:302","msg":"Failed to get table","uuid":"33653366-3831-3337-3166-326332313235","tableName":"mo_upgrade","error":"SQL parser error: table \"mo_upgrade\" does not exist","session_info":"connectionId 343372104||{account 01910296-832b-7409-9c46-7352b1ad8b70:admin:accountadmin -- 412640006:2:2}|goRoutineId 151187|migrate-goRoutineId 0|01910bf4-9175-7e8c-9c2c-4b17e3c060c4","session_id":"01910bf4-9175-7e8c-9c2c-4b17e3c060c4","statement_id":"01910bf4-b91d-709e-8318-34514b8ddfa6","txn_id":"01910bf4b91d70d6a3e2dbe051c29c4b","span":{"trace_id":"74a2fc22-c386-e50c-45c1-b7140db4dbb3","span_id":"47ecc972d594734b"}}
{"level":"ERROR","time":"2024/08/01 03:21:13.245290 +0000","name":"cn-service.frontend","caller":"frontend/txn.go:63","msg":"SQL parser error: table \"mo_upgrade\" does not exist","uuid":"33653366-3831-3337-3166-326332313235","session_info":"connectionId 343372104||{account 01910296-832b-7409-9c46-7352b1ad8b70:admin:accountadmin -- 412640006:2:2}|goRoutineId 151187|migrate-goRoutineId 0|01910bf4-9175-7e8c-9c2c-4b17e3c060c4","session_id":"01910bf4-9175-7e8c-9c2c-4b17e3c060c4","statement_id":"01910bf4-b91d-709e-8318-34514b8ddfa6","txn_id":"01910bf4b91d70d6a3e2dbe051c29c4b","span":{"trace_id":"74a2fc22-c386-e50c-45c1-b7140db4dbb3","span_id":"47ecc972d594734b"}}

### Steps to Reproduce

```Markdown
Schema upgrade
```

### Additional information
https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22CQL%22:%7B%22datasource%22:%22aee71632-e6c2-4299-906a-cc73bb62fd3b%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_namespace%3D%5C%22freetier-01%5C%22%7D%20%7C%3D%20%60upgrade%60%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22aee71632-e6c2-4299-906a-cc73bb62fd3b%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722481200000%22,%22to%22:%221722483059000%22%7D%7D%7D&schemaVersion=1&orgId=1
_No response_

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by aressu1985** [comment]
没有定位出原因，暂时也复现不了，先降级，添加to_next_release label，跟踪

**Comment by qingxinhome** [comment]
m

**Comment by qingxinhome** [comment]
该问题没有复现，现将其关闭
