### ISSUE TITLE
[Bug]: confusing error message

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17875]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2e2f09029

### Other Environment Information

```Markdown
- Hardware parameters: MacBook Pro
- OS type: Mac OSX
- Others:
```

### Actual Behavior

```
mysql> use foo;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> create table public.author(aid bigint not null, homepage text, name text, oid bigint);
ERROR 1046 (HY000): not connect to a database
mysql> select git_version();
+-----------+
| 2e2f09029 |
+-----------+
1 row in set (0.01 sec)
```

### Expected Behavior

`ERROR 1046 (HY000): not connect to a database` is confusing.   We need to give a 
better error message such as database *public* does not exist

### Steps to Reproduce

```Markdown
See above.
```

**Comment by daviszhen** [comment]
调整为mysql的报错信息
