### ISSUE TITLE
[Bug]: optimize error message.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17889]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6a17b59e7505c3e64357f7017c8657b8b61117e8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

如果恢复的时间超过了设置的pitr的时间范围，报错信息不够明确
<img width="874" alt="image" src="https://github.com/user-attachments/assets/45418b6b-8044-4224-b347-133fd123681a">

### Steps to Reproduce

```Markdown
1. 创建pitr 
create pitr for account sys range 1 'h';
select now();

2. 1h+后
restore from pitr p01 '步骤1中的时间戳';
```

**Comment by YANGGMM** [comment]
fixed, plz test @Ariznawlll

**Comment by Ariznawlll** [comment]
**main commit：5f144a5a5160a50d40edf252cae9b0655a0ad8fb**

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/1245bc32-f251-415e-b174-36c1c9d68a18">

测试通过
