### ISSUE TITLE
[Refactoring]: add new interface to check if schema changed for Execute statement

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#17881]
### Why do you want to refactor this code?

```Markdown
目前是通过resolve接口，拿到tableDef再做比较。这样比较耗时（特别是拿tableDef还涉及到一次拷贝）
```

### Describe the solution you'd like

增加对应的接口

**Comment by jensenojs** [comment]
节省了一次`CopyTableDef`之后, 这一部份的性能大概提升了25%

https://github.com/matrixorigin/matrixone/pull/18266#issuecomment-2301536642
