### ISSUE TITLE
[Feature Request]: json_extract_string and json_extract_float64

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17897]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
json_extract returns json type.  For comparing with sql value, we need to cast 
data to json.  A much better (both semantically clearer and more efficient) way 
to handle value is just extract them.
```

### Describe the feature you'd like

Adding two functions (maybe 3), 
json_extract_string -- same as json_extract, but with exactly one path.   return string value, or null if json_extract of the path is not a string node.
json_extract_float64 -- return float64 or null if node is not a number
json_extract_int64    -- maybe this one

**Comment by YANGGMM** [comment]
@aronchanisme  麻烦测试一下

**Comment by aronchanisme** [comment]
already tested in another thread: https://github.com/matrixorigin/MO-Cloud/issues/3779

**Comment by aronchanisme** [comment]
forward to product team

**Comment by aressu1985** [comment]
TEST DONE
