### ISSUE TITLE
[Bug]: [0806] big data regression:  mo internal report 'out of memory'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#17899]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b52e7bc4e058d30bb369f813bd3619106a3d4b25

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10250331351/job/28356023486
（第一次出现out of memory报错的地方是在Quries 10Y -> Aggr 10Y test）
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/35c561b4-581d-4101-8083-f28bf5fc87d9">

pod状态正常：
<img width="720" alt="image" src="https://github.com/user-attachments/assets/eb612c0d-0d0f-480a-a7f1-52a4172b182b">

第一次出现out of memory的日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22nkO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240805%5C%22%7D%20%7C%3D%20%60out%20of%20memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722900054269%22,%22to%22:%221722900149269%22%7D%7D%7D&schemaVersion=1&orgId=1

第一次出现out of memory的内存使用：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dzj%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240805%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221722900133000%22,%22to%22:%221722900613000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big data test
```

**Comment by XuPeng-SH** [comment]
<img width="1702" alt="image" src="https://github.com/user-attachments/assets/4c486bcd-a03b-4108-b482-87457ad68f4d">

Remote run mpool leak

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/a3895e94-31f0-48e7-88b1-3634da81e1dd">

**Comment by triump2020** [comment]
@zengyan1

**Comment by zengyan1** [comment]
已修复
