### ISSUE TITLE
[Bug]: UT TestNewMOCollector failed

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#17913]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bb4f5eacb2e42c20286ba9c3b33bf6eed61df22c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-08-06T06:42:57.1531900Z === RUN   TestNewMOCollector
2024-08-06T06:42:57.1532790Z signal: segmentation fault
2024-08-06T06:42:57.1533620Z FAIL	github.com/matrixorigin/matrixone/pkg/util/export	0.576s

### Steps to Reproduce

```Markdown
run CI
```

**Comment by xzxiong** [comment]
基本情况：
Segmentation fault 出现后，CI没有保留 coredump文件，而且也不是通过 go test -c  生成可执行文件。
所以，通过CI 知道有该情况，并无额外信息帮助定位。

OnGoing:
- 找一台机器，对 ut 编译成可执行文件；再打开coredump；参试复现。
- 脚本: [run_coredump.tgz](https://github.com/user-attachments/files/16517597/run_coredump.tgz)

**Comment by xzxiong** [comment]
bug1 :
- version: bca6edc16
- dev: macbook pro 16
- data race: 
```
WARNING: DATA RACE
Read at 0x0001078558f8 by goroutine 166:
  time.Now()
      /Users/jacksonxie/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.darwin-arm64/src/time/time.go:1141 +0xc8
  time.sendTime()
      /Users/jacksonxie/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.darwin-arm64/src/time/sleep.go:145 +0x3c

Previous write at 0x0001078558f8 by main goroutine:
  github.com/matrixorigin/matrixone/pkg/util/export/table.init.0()
      /Users/jacksonxie/go/src/github.com/matrixorigin/matrixone/pkg/util/export/table/table_test.go:32 +0x40

Goroutine 166 (running) created at:
  [failed to restore the stack]
```

**Comment by xzxiong** [comment]
main 刚接触 freezen，等待 merge

**Comment by xzxiong** [comment]
checked, 近期没有复现相关ut failed
