### ISSUE TITLE
[Bug]: TestNewMOCollector failed

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17919]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TestNewMOCollector failed:

2024-08-06T13:56:31.6278432Z === RUN   TestNewMOCollector
2024-08-06T13:56:31.6278582Z signal: segmentation fault (core dumped)
2024-08-06T13:56:31.6278816Z FAIL       github.com/matrixorigin/matrixone/pkg/util/export       0.843s

[url](https://github.com/matrixorigin/matrixone/actions/runs/10267559442/job/28408404178?pr=17916)

### Steps to Reproduce

```Markdown
run ci ut.
```

**Comment by xzxiong** [comment]
dup https://github.com/matrixorigin/matrixone/issues/17913

**Comment by xzxiong** [comment]
checked, 近期没有复现相关ut failed
