### ISSUE TITLE
[Bug]:  `panic: missing free for type: *compile.Scope` during bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#17915]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

bb4f5ea

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/10261695084/job/28389913816?pr=17901

[Uploading Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports.zip…]()

panic: missing free for type: *compile.Scope, &{Magic:2 IsJoin:false IsEnd:false IsRemote:false IsLoad:false Plan:<nil> DataSource:0xc0295098c0 PreScopes:[] NodeInfo:{Mcpu:1 Id: Addr:cn1:18100 Data:<nil> NeedExpandRanges:true} TxnOffset:0 RootOp:0xc016dfd100 Proc:0xc02559fc00 Reg:<nil> RemoteReceivRegInfos:[] BuildIdx:0 ShuffleIdx:0 PartialResults:[] PartialResultTypes:[]} 
 create by: <<<>>>

goroutine 18 [running]:
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0x5709080, 0xc032079e00)
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/checker.go:133 +0x1e8
github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/sync_pool_based.go:48 +0x65

### Expected Behavior

no leak

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by ouyuanning** [comment]
锦赛帮忙看看吧。
你可以在scope里记录一下alloc和free的调用栈，确认一下是哪个地方申请的没有被正确释放。
我估计是最近优化减少pipeline数量时候弄出来的问题

**Comment by jensenojs** [comment]
本地用dynamic-proxy的配置起mo, 加上reuse的检查, 跑query_result的特定sql就可以触发. 

```sql
-- test/distributed/cases/query_result/query_result.sql#31
/* save_result */select t2.b from result_scan(last_query_id()) as u, t2 where u.c = t2.c;
```

单cn下这个sql的scope长这个样子, 是我们的预期结果.
```
Scope 1 (Magic: Merge, mcpu: 1, Receiver: [2]): [merge -> output]
  PreScopes: {
  Scope 1 (Magic: Remote, mcpu: 12, Receiver: [0, 1]): [merge -> join -> connect to MergeReceiver 2]
    PreScopes: {
    Scope 1 (Magic: Normal, mcpu: 12, Receiver: []): [external -> connect to MergeReceiver 0]
    DataSource: [],
    Scope 2 (Magic: Remote, mcpu: 1, Receiver: []): [tablescan -> dispatch to all of MergeReceiver [1].]
    DataSource: [],
  }
}
```
而多cn下长这个样子, 少了一个table Scan的Scope
```
Scope 1 (Magic: Merge, mcpu: 1, Receiver: [2]): [merge -> output]
  PreScopes: {
  Scope 1 (Magic: Remote, mcpu: 12, Receiver: [0, 1]): [merge -> join -> connect to MergeReceiver 2]
    PreScopes: {
    Scope 1 (Magic: Normal, mcpu: 12, Receiver: []): [external -> connect to MergeReceiver 0]
    DataSource: [],
  }
}
```

但是reuse的检查中能看到这个Scope是创建出来了, 可能把它优化掉了, 然后优化之后忘记手动release了.

```go
panic: missing free for type: *compile.Scope, &{Magic:2 IsJoin:false IsEnd:false IsRemote:false IsLoad:false Plan:<nil> DataSource:0x1401c4e86c0 PreScopes:[] NodeInfo:{Mcpu:1 Id: Addr:cn1:18100 Data:<nil> NeedExpandRanges:true} TxnOffset:0 RootOp:0x14041a811d0 Proc:0x14045feeec0 Reg:<nil> RemoteReceivRegInfos:[] BuildIdx:0 ShuffleIdx:0 PartialResults:[] PartialResultTypes:[]} 
 create by: <<<goroutine 7382 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).got(0x104e78580, 0x140500d0f00)
	/Users/jensen/Projects/matrixorigin/matrixone/pkg/common/reuse/checker.go:86 +0xfc
github.com/matrixorigin/matrixone/pkg/common/reuse.(*syncPoolBased[...]).Alloc(0x104e232e0)
	/Users/jensen/Projects/matrixorigin/matrixone/pkg/common/reuse/sync_pool_based.go:64 +0x54
github.com/matrixorigin/matrixone/pkg/common/reuse.Alloc[...]({0x0?, 0x0?})
	/Users/jensen/Projects/matrixorigin/matrixone/pkg/common/reuse/factory.go:105 +0xc8
github.com/matrixorigin/matrixone/pkg/sql/compile.newScope(...)
	/Users/jensen/Projects/matrixorigin/matrixone/pkg/sql/compile/scope.go:68
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScanWithNode(0x140300c7d40, 0x1401e6e4008, {0x1, {0x0, 0x0}, {0x140057155e0, 0x9}, {0x0, 0x0}, 0x1}, ...)
	/Users/jensen/Projects/matrixorigin/matrixone/pkg/sql/compile/compile.go:1783 +0x60
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileTableScan(0x140300c7d40, 0x1401e6e4008)
	/Users/jensen/Projects/matrixorigin/matrixone/pkg/sql/compile/compile.go:1769 +0x138
```

**Comment by jensenojs** [comment]
这个issue实际上是个假问题, 根因的fix你涛哥已经合并进main中了. 辛苦QA和下面这个issue一并测试就好

- https://github.com/matrixorigin/matrixone/issues/17905

**Comment by aressu1985** [comment]
fixed
