### ISSUE TITLE
[Bug]: [date 8.6]standalone regression: bvt test reported panic error runtime.sigpanic

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#17924]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c1c365c99feead9f1e021c7a2e26e707c31be04e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10268409036/job/28411571959

internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/panic.go:261
runtime.sigpanic
	/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/signal_unix.go:881
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetNulls
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:198
github.com/matrixorigin/matrixone/pkg/compare.(*compare[...]).Set
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/compare/compare.go:296
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergetop.(*container).sort
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergetop/top.go:249
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergetop.(*container).eval
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergetop/top.go:225
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergetop.(*MergeTop).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergetop/top.go:106
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:58
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).processGroupByAndAgg
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/group/group.go:172
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*Group).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/group/group.go:146
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:58
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.(*Output).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/output/output.go:48
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:107
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:84
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:302
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:335
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func2
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:497
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/asm_amd64.s:1695

mo log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-c1c365c-20240806-222550.log%5C%22%7D%20%7C%3D%20%60panic%20runtime%20error:%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722934301848%22,%22to%22:%221723020701848%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
standalone bvt test
```

**Comment by ouyuanning** [comment]
还没时间看

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展
