### ISSUE TITLE
[Bug]: There were lots of error "out of memory" during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17938]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c1c365c

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, there were lots of error "out of memeory" for tpch, tpcc ,sysbench cases.

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/c54ec658-757a-4d67-b000-ad6a9906a7c5">

mo log link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-c1c365c-202408062226%5C%22%7D%20%7C%3D%20%60out%20of%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722962441377%22,%22to%22:%221723033374710%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
优化中

**Comment by reusee** [comment]
和 https://github.com/matrixorigin/matrixone/issues/18364 一样的，已经修复
