### ISSUE TITLE
[Bug]: getCNList takes too much cpu resources in the ditribution deployment

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#17948]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1773" alt="image" src="https://github.com/user-attachments/assets/56c3f9e0-8098-40e0-b7a6-fa19f2960778">

https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22l6t%22:%7B%22datasource%22:%22faf7d6e0-45aa-4915-9ca0-512572886753%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%3D%5C%22freetier-01-localpv-6c454796bd-cn-sx8gg%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22faf7d6e0-45aa-4915-9ca0-512572886753%22%7D%7D%5D,%22range%22:%7B%22from%22:%221723087813561%22,%22to%22:%221723087829652%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
Scenarios for highly concurrent inserts of tables without the primary key
```

**Comment by volgariver6** [comment]
I will fix it

**Comment by volgariver6** [comment]
pr committed

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
等待合并

**Comment by volgariver6** [comment]
fixed
