### ISSUE TITLE
[Bug]: Error when running `select for update` with gorm

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#17946]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

ac80b84939fbc134855a23fc3d74a7357dcd8560

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Create a cluster table
- Run `select for update` with gorm, the following error is fired:
```
sql: expected 1 arguments, got 2
[2.752ms] [rows:0] SELECT * FROM `mo_catalog`.`knowledge` WHERE id = '1' ORDER BY `knowledge`.`id` LIMIT 1 FOR UPDATE
```

### Expected Behavior

No error returned

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

[minio.go.zip](https://github.com/user-attachments/files/16537013/minio.go.zip)

**Comment by ouyuanning** [comment]
根本原因是在build plan的时候。
如果select for update语句中，包含limit子句的话，lock节点的children设置错误（跳过了filter节点，将table_scan设置为自己的子节点）。优化器就会把包含了?表达式的 filter 节点给优化了。于是认为整个prepare语句没有 ? 表达式

**Comment by DanielZhangQD** [comment]
Verified and passed with 1.2-dev
