### ISSUE TITLE
[Subtask]: frontend.executeStatement still runs compile in a prepared statement

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17951]
### Parent Issue

#14469

### Detail of Subtask

Find out why we still compile and remove this code path

**Comment by ouyuanning** [comment]
得再确认下。目前DML语句还没法cache住Compile

**Comment by ouyuanning** [comment]
是因为目前DML语句还没有cache住Compile造成的

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/18255 等待这个pr合并

**Comment by badboynt1** [comment]
pr已合并。现在dml语句也可以cache compile
