### ISSUE TITLE
[Subtask]: respClientWithoutFlush flushes at least twice.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17954]
### Parent Issue

#14469

### Detail of Subtask

As function name suggests, should flush 0 time.

**Comment by daviszhen** [comment]
@CJKkkk-315 抽时间一起看下这个问题

**Comment by CJKkkk-315** [comment]
已将函数名respClientWithoutFlush改为respClient。
此函数仅执行flush 1次
profile文件中出现2个函数调用flush是由于mo-load交替执行commit和select 1，从而执行2种不同的resp type 函数
<img width="487" alt="企业微信截图_17232008647071" src="https://github.com/user-attachments/assets/211ea576-d0cc-4451-9047-f3a7e97fdc13">
