### ISSUE TITLE
[Subtask]: frontend.Session.UpdateDebugString takes too long

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17957]
### Parent Issue

#14469

### Detail of Subtask

Why -- esp for prepared statement this is not much to update.

**Comment by CJKkkk-315** [comment]
优化UpdateDebugString的频繁调用，仅在链接初始化等少部分情况调用。已不再占用CPU处理时间
![image](https://github.com/user-attachments/assets/e33fbaf0-f94c-4460-9e20-2da88ec2d6c2)
