### ISSUE TITLE
[Subtask]: Conn.Read is slow

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#17960]
### Parent Issue

#14469 

### Detail of Subtask

Overall Conn.Read is quite slow, obviously we can get rid of alloc.   Not sure if we can optimize poll.FD.Read

**Comment by CJKkkk-315** [comment]
https://github.com/matrixorigin/matrixone/pull/17846 refactors the read method, getting rid of alloc in most cases

**Comment by sukki37** [comment]
Please provide the self-assessment results and a comparison of the profile before and after the modification to demonstrate that this PR is effective. @CJKkkk-315

**Comment by CJKkkk-315** [comment]
在原先的逻辑中，Conn.Read方法为每一个Packet Alloc一块内存，直到一条Query的所有Packet收齐以后，make一块完整的内存将之前Alloc的内存进行Copy后Free。在这个逻辑下，每次read至少要进行一次alloc，free和make。由于在实际场景中，大部分的Query都以单独1个Packet的形式发送，其实没有Alloc的必要。https://github.com/matrixorigin/matrixone/pull/17846 添加了判断逻辑，在仅有单独一个Packet作为Query时，直接make最终的内存进行接收。

为了验证结果使用mo-load进行select 1的测试，对比PR合入前后CPU profile。

PR前：
![image](https://github.com/user-attachments/assets/eb1601a9-426e-476c-a4c4-42a86a053da4)

PR后：
![image](https://github.com/user-attachments/assets/483df56d-fae9-4475-88fb-b1618ba9369b)

可以看出优化后节省了30-40%的Alloc和Free的性能消耗

**Comment by Ariznawlll** [comment]
测试步骤：
1. 连接mo，创建db：
```
   mysql -h 127.0.0.1 -P 6001 -udump -p111
   drop database if exists test;
   create database test;
```

2. clone并发测试工具mo-load：
    git clone https://github.com/matrixorigin/mo-load.git

3. 使用工具执行'select 1'测试，并发数设置为10，time=3min
    测试命令：./start.sh -c prepare/select_1  -h 127.0.0.1 -P 6001  -t 10 -d 3 -b test

**修改前main commit：438a70b2f1b1f819ad2910c78bcd54407cea6ec7**
测试结果：
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/0cbae9dd-ef1a-4235-9183-5fbb6b5c5803">

<img width="1918" alt="image" src="https://github.com/user-attachments/assets/7f8d0329-de05-4fc3-9486-4433ee421d04">

**修改后main commit：438a70b2f1b1f819ad2910c78bcd54407cea6ec7**
测试结果：
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/359fca60-bddb-4772-a129-a6b020cb2c93">

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/12fcf37a-e99c-4ec8-9941-5fe6da899390">

**Comment by Ariznawlll** [comment]
测试步骤（129服务器）：
1. 连接mo，创建db：
```
   mysql -h 127.0.0.1 -P 6001 -udump -p111
   drop database if exists test;
   create database test;
```

2. clone并发测试工具mo-load：
    git clone https://github.com/matrixorigin/mo-load.git

3. 使用工具执行'select 1'测试，并发数设置为10，time=3min
    测试命令：./start.sh -c prepare/select_1  -h 127.0.0.1 -P 6001  -t 10 -d 3 -b test

**修改前main commit：73411490a73723e9dfd62c3128e0afefa84c9463**
测试结果：
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/0cbae9dd-ef1a-4235-9183-5fbb6b5c5803">

<img width="1918" alt="image" src="https://github.com/user-attachments/assets/7f8d0329-de05-4fc3-9486-4433ee421d04">

<img width="863" alt="企业微信截图_fd419a2b-5402-4c11-a168-fd5611ba1717" src="https://github.com/user-attachments/assets/d65f488f-0cf8-4f62-a55a-5233230284f2">

**修改后main commit：59d7606bfcaa42cd913f41ba8caa1239552fcf46**
测试结果：
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/359fca60-bddb-4772-a129-a6b020cb2c93">

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/12fcf37a-e99c-4ec8-9941-5fe6da899390">

<img width="812" alt="企业微信截图_f2ae615e-48cf-4eef-a58f-d673089ece5e" src="https://github.com/user-attachments/assets/1bd205d6-fe04-4bf8-ab37-de422cb1678c">
