### ISSUE TITLE
[Bug]: dispatch data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17989]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

  9952 2024-08-09T01:45:12.6924594Z WARNING: DATA RACE
  9953 2024-08-09T01:45:12.6925089Z Read at 0x00c02464d880 by goroutine 5478:
  9954 2024-08-09T01:45:12.6926318Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.sendToAllLocalFunc()
  9955 2024-08-09T01:45:12.6927995Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/dispatch/sendfunc.go:61 +0x498
  9956 2024-08-09T01:45:12.6929481Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.(*Dispatch).Call()
  9957 2024-08-09T01:45:12.6931107Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/dispatch/dispatch.go:158 +0x369
  9958 2024-08-09T01:45:12.6932479Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
  9959 2024-08-09T01:45:12.6933900Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:107 +0x214
  9960 2024-08-09T01:45:12.6935217Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun()
  9961 2024-08-09T01:45:12.6936655Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:84 +0x3d
  9962 2024-08-09T01:45:12.6937940Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun()
  9963 2024-08-09T01:45:12.6939827Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:302 +0x5c4
  9964 2024-08-09T01:45:12.6941330Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
  9965 2024-08-09T01:45:12.6942861Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262 +0x14f
  9966 2024-08-09T01:45:12.6944040Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
  9967 2024-08-09T01:45:12.6945341Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
  9968 2024-08-09T01:45:12.6946122Z
  9969 2024-08-09T01:45:12.6946446Z Previous write at 0x00c02464d880 by goroutine 5471:
  9970 2024-08-09T01:45:12.6947473Z   github.com/matrixorigin/matrixone/pkg/sql/compile.regTransplant()
  9971 2024-08-09T01:45:12.6948933Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/compile.go:3747 +0x290
  9972 2024-08-09T01:45:12.6950386Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).newJoinBuildScope()
  9973 2024-08-09T01:45:12.6951930Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/compile.go:3730 +0x1d8
  9974 2024-08-09T01:45:12.6953312Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildJoinParallelRun()
  9975 2024-08-09T01:45:12.6954809Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:470 +0x969
  9976 2024-08-09T01:45:12.6956138Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
  9977 2024-08-09T01:45:12.6957790Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:403 +0x125
  9978 2024-08-09T01:45:12.6959110Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
  9979 2024-08-09T01:45:12.6960759Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
  9980 2024-08-09T01:45:12.6962176Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
  9981 2024-08-09T01:45:12.6963666Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
  9982 2024-08-09T01:45:12.6964783Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
  9983 2024-08-09T01:45:12.6966070Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ut ci, TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by m-schen** [comment]
现在没空

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
