### ISSUE TITLE
[Bug]: filter data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17998]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 11335 2024-08-09T01:45:12.8144492Z WARNING: DATA RACE
 11336 2024-08-09T01:45:12.8144727Z Read at 0x00c024a1f708 by goroutine 5498:
 11337 2024-08-09T01:45:12.8145527Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mustColVecValueFromBinaryFuncExpr()
 11338 2024-08-09T01:45:12.8146300Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/filter.go:137 +0x66
 11339 2024-08-09T01:45:12.8146828Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.evalValue()
 11340 2024-08-09T01:45:12.8147576Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:122 +0x78
 11341 2024-08-09T01:45:12.8148149Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 11342 2024-08-09T01:45:12.8149026Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:189 +0x3b8
 11343 2024-08-09T01:45:12.8152000Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 11344 2024-08-09T01:45:12.8152903Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:54 +0x188d
 11345 2024-08-09T01:45:12.8153428Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.NewReader()
 11346 2024-08-09T01:45:12.8154201Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/reader.go:253 +0x86
 11347 2024-08-09T01:45:12.8155001Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 11348 2024-08-09T01:45:12.8155922Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1844 +0x6a8
 11349 2024-08-09T01:45:12.8156683Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 11350 2024-08-09T01:45:12.8157606Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 11351 2024-08-09T01:45:12.8158195Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 11352 2024-08-09T01:45:12.8158935Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 11353 2024-08-09T01:45:12.8159527Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 11354 2024-08-09T01:45:12.8160266Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 11355 2024-08-09T01:45:12.8160836Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 11356 2024-08-09T01:45:12.8162211Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 11357 2024-08-09T01:45:12.8162904Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 11358 2024-08-09T01:45:12.8163653Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 11359 2024-08-09T01:45:12.8164252Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 11360 2024-08-09T01:45:12.8164993Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 11361 2024-08-09T01:45:12.8165352Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 11362 2024-08-09T01:45:12.8166106Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 11363 2024-08-09T01:45:12.8166227Z
 11364 2024-08-09T01:45:12.8166531Z Previous write at 0x00c024a1f708 by goroutine 5467:
 11365 2024-08-09T01:45:12.8166996Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 11366 2024-08-09T01:45:12.8167711Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:959 +0x3ff7
 11367 2024-08-09T01:45:12.8168353Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 11368 2024-08-09T01:45:12.8169169Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:649 +0x7a4
 11369 2024-08-09T01:45:12.8169746Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 11370 2024-08-09T01:45:12.8170487Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 11371 2024-08-09T01:45:12.8171069Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 11372 2024-08-09T01:45:12.8171800Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 11373 2024-08-09T01:45:12.8172376Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 11374 2024-08-09T01:45:12.8174513Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 11375 2024-08-09T01:45:12.8175064Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 11376 2024-08-09T01:45:12.8175804Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 11377 2024-08-09T01:45:12.8176401Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 11378 2024-08-09T01:45:12.8177138Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 11379 2024-08-09T01:45:12.8177499Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 11380 2024-08-09T01:45:12.8178245Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by fengttt** [comment]
Potentially dup of #18018

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
