### ISSUE TITLE
[Bug]: reader data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17994]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 10541 2024-08-09T01:45:12.7663116Z WARNING: DATA RACE
 10542 2024-08-09T01:45:12.7663349Z Read at 0x00c042443a50 by goroutine 5498:
 10543 2024-08-09T01:45:12.7663928Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 10544 2024-08-09T01:45:12.7664794Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:50 +0x1e9
 10545 2024-08-09T01:45:12.7665878Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.NewReader()
 10546 2024-08-09T01:45:12.7666665Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/reader.go:253 +0x86
 10547 2024-08-09T01:45:12.7667325Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 10548 2024-08-09T01:45:12.7668157Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1844 +0x6a8
 10549 2024-08-09T01:45:12.7668897Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 10550 2024-08-09T01:45:12.7669815Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 10551 2024-08-09T01:45:12.7670380Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 10552 2024-08-09T01:45:12.7671106Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 10553 2024-08-09T01:45:12.7671688Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 10554 2024-08-09T01:45:12.7672393Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 10555 2024-08-09T01:45:12.7672940Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 10556 2024-08-09T01:45:12.7673792Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 10557 2024-08-09T01:45:12.7674415Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 10558 2024-08-09T01:45:12.7675130Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 10559 2024-08-09T01:45:12.7675704Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 10560 2024-08-09T01:45:12.7677118Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 10561 2024-08-09T01:45:12.7677473Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 10562 2024-08-09T01:45:12.7678218Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 10563 2024-08-09T01:45:12.7678227Z
 10564 2024-08-09T01:45:12.7678520Z Previous write at 0x00c042443a50 by goroutine 5467:
 10565 2024-08-09T01:45:12.7679006Z   github.com/matrixorigin/matrixone/pkg/sql/colexec.makeAndExpr()
 10566 2024-08-09T01:45:12.7679844Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/evalExpression.go:1548 +0x31a
 10567 2024-08-09T01:45:12.7680572Z   github.com/matrixorigin/matrixone/pkg/sql/colexec.RewriteFilterExprList()
 10568 2024-08-09T01:45:12.7681412Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/evalExpression.go:1516 +0x413
 10569 2024-08-09T01:45:12.7682054Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 10570 2024-08-09T01:45:12.7682777Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:655 +0x924
 10571 2024-08-09T01:45:12.7683329Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 10572 2024-08-09T01:45:12.7684044Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 10573 2024-08-09T01:45:12.7684708Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 10574 2024-08-09T01:45:12.7685419Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 10575 2024-08-09T01:45:12.7685961Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 10576 2024-08-09T01:45:12.7686680Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 10577 2024-08-09T01:45:12.7687737Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 10578 2024-08-09T01:45:12.7688463Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 10579 2024-08-09T01:45:12.7689050Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 10580 2024-08-09T01:45:12.7689766Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 10581 2024-08-09T01:45:12.7690106Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 10582 2024-08-09T01:45:12.7690853Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by gouhongshen** [comment]
same with #17997

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
