### ISSUE TITLE
[Bug]: runtime_filter panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17991]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 10291 2024-08-09T01:45:12.7372504Z 2024/08/09 01:37:40.319003 +0000 ERROR cn-service compile/scope.go:388 panic in scope run {"service": "2-cn-2", "uuid": "2-cn-2", "sql": "execute __mo_stmt_id_5", "error": "in       ternal error: panic runtime error: invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:261\nruntime.sigpanic\n\t/opt/hostedtool       cache/go/1.22.3/x64/src/runtime/signal_unix.go:881\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.ApplyRuntimeFilters\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/runtime_filter.go:115\ngi       thub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:696\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scop       e).buildReaders\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun\n\t/home/runner/work/matrixone/matrixone/pkg/       sql/compile/scope.go:553\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412\ngithub.com/matrixorigin/matrixone/pk       g/sql/compile.(*Scope).RemoteRun\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/home/runner/work/matri       xone/matrixone/pkg/sql/compile/scope.go:264\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/opt/hostedto       olcache/go/1.22.3/x64/src/runtime/asm_amd64.s:1695", "session_id": "019134c8-b5d7-720a-9587-e9430897cd3f", "statement_id": "019134c8-cb9b-7485-9a48-174cd9616e2d", "txn_id": "019134c8cb7d735e94113cb297da74       33"}

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by badboynt1** [comment]
还没时间处理

**Comment by badboynt1** [comment]
这个panic已经绕过，应该不会再出现。 至于根源的原因后续再查
