### ISSUE TITLE
[Bug]: dispatch data race 2

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17990]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 10028 2024-08-09T01:45:12.7018847Z WARNING: DATA RACE
 10029 2024-08-09T01:45:12.7019346Z Read at 0x00c048e20018 by goroutine 5478:
 10030 2024-08-09T01:45:12.7019988Z   sync/atomic.LoadInt64()
 10031 2024-08-09T01:45:12.7020904Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/race_amd64.s:208 +0xb
 10032 2024-08-09T01:45:12.7021783Z   sync/atomic.LoadPointer()
 10033 2024-08-09T01:45:12.7022370Z       <autogenerated>:1 +0x10
 10034 2024-08-09T01:45:12.7022926Z   context.(*cancelCtx).Done()
 10035 2024-08-09T01:45:12.7024004Z       /opt/hostedtoolcache/go/1.22.3/x64/src/context/context.go:439 +0x4f
 10036 2024-08-09T01:45:12.7025541Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.sendToAllLocalFunc()
 10037 2024-08-09T01:45:12.7027191Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/dispatch/sendfunc.go:61 +0x4ad
 10038 2024-08-09T01:45:12.7028645Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.(*Dispatch).Call()
 10039 2024-08-09T01:45:12.7030264Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/dispatch/dispatch.go:158 +0x369
 10040 2024-08-09T01:45:12.7031754Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 10041 2024-08-09T01:45:12.7033176Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:107 +0x214
 10042 2024-08-09T01:45:12.7034496Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun()
 10043 2024-08-09T01:45:12.7037052Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:84 +0x3d
 10044 2024-08-09T01:45:12.7038350Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun()
 10045 2024-08-09T01:45:12.7039758Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:302 +0x5c4
 10046 2024-08-09T01:45:12.7041075Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 10047 2024-08-09T01:45:12.7042523Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262 +0x14f
 10048 2024-08-09T01:45:12.7043607Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 10049 2024-08-09T01:45:12.7044853Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 10050 2024-08-09T01:45:12.7045608Z
 10051 2024-08-09T01:45:12.7045907Z Previous write at 0x00c048e20018 by goroutine 5471:
 10052 2024-08-09T01:45:12.7046611Z   context.withCancel()
 10053 2024-08-09T01:45:12.7047531Z       /opt/hostedtoolcache/go/1.22.3/x64/src/context/context.go:272 +0x53
 10054 2024-08-09T01:45:12.7048375Z   context.WithCancel()
 10055 2024-08-09T01:45:12.7049307Z       /opt/hostedtoolcache/go/1.22.3/x64/src/context/context.go:236 +0x26
 10056 2024-08-09T01:45:12.7050679Z   github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).BuildPipelineContext()
 10057 2024-08-09T01:45:12.7052285Z       /home/runner/work/matrixone/matrixone/pkg/vm/process/process2.go:132 +0x8d
 10058 2024-08-09T01:45:12.7053739Z   github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).NewContextChildProc()
 10059 2024-08-09T01:45:12.7055333Z       /home/runner/work/matrixone/matrixone/pkg/vm/process/process2.go:123 +0x1e5
 10060 2024-08-09T01:45:12.7056990Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).newJoinBuildScope()
 10061 2024-08-09T01:45:12.7058960Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/compile.go:3728 +0x144
 10062 2024-08-09T01:45:12.7060375Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildJoinParallelRun()
 10063 2024-08-09T01:45:12.7061881Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:470 +0x969
 10064 2024-08-09T01:45:12.7063367Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 10065 2024-08-09T01:45:12.7064972Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:403 +0x125
 10066 2024-08-09T01:45:12.7066318Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 10067 2024-08-09T01:45:12.7068942Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 10068 2024-08-09T01:45:12.7070329Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 10069 2024-08-09T01:45:12.7071846Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 10070 2024-08-09T01:45:12.7073004Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 10071 2024-08-09T01:45:12.7074342Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut. TestBaseClusterCanWorkWithNewCluster, TestMultiClusterCanWork
```

**Comment by m-schen** [comment]
现在没空

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
