### ISSUE TITLE
[Bug]: plan data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#17993]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

10368 2024-08-09T01:45:12.7487859Z ==================
 10369 2024-08-09T01:45:12.7488272Z WARNING: DATA RACE
 10370 2024-08-09T01:45:12.7488769Z Read at 0x00c027ae2b40 by goroutine 5498:
 10371 2024-08-09T01:45:12.7489658Z   github.com/matrixorigin/matrixone/pkg/sql/plan.IsFalseExpr()
 10372 2024-08-09T01:45:12.7490946Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/utils.go:2012 +0x68
 10373 2024-08-09T01:45:12.7492307Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 10374 2024-08-09T01:45:12.7493938Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1810 +0x96
 10375 2024-08-09T01:45:12.7495506Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 10376 2024-08-09T01:45:12.7497315Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 10377 2024-08-09T01:45:12.7511263Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 10378 2024-08-09T01:45:12.7513911Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 10379 2024-08-09T01:45:12.7515273Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 10380 2024-08-09T01:45:12.7516726Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 10381 2024-08-09T01:45:12.7518074Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 10382 2024-08-09T01:45:12.7519504Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 10383 2024-08-09T01:45:12.7520786Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 10384 2024-08-09T01:45:12.7522190Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 10385 2024-08-09T01:45:12.7525116Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 10386 2024-08-09T01:45:12.7526650Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 10387 2024-08-09T01:45:12.7527758Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 10388 2024-08-09T01:45:12.7529209Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 10389 2024-08-09T01:45:12.7529972Z
 10390 2024-08-09T01:45:12.7530283Z Previous write at 0x00c027ae2b40 by goroutine 5467:
 10391 2024-08-09T01:45:12.7531479Z   github.com/matrixorigin/matrixone/pkg/sql/colexec.RewriteFilterExprList()
 10392 2024-08-09T01:45:12.7533066Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/evalExpression.go:1515 +0x3d5
 10393 2024-08-09T01:45:12.7534543Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 10394 2024-08-09T01:45:12.7536759Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:655 +0x924
 10395 2024-08-09T01:45:12.7538090Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 10396 2024-08-09T01:45:12.7539682Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 10397 2024-08-09T01:45:12.7541004Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 10398 2024-08-09T01:45:12.7542451Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 10399 2024-08-09T01:45:12.7543743Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 10400 2024-08-09T01:45:12.7545295Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 10401 2024-08-09T01:45:12.7546580Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 10402 2024-08-09T01:45:12.7548609Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 10403 2024-08-09T01:45:12.7549936Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 10404 2024-08-09T01:45:12.7551388Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 10405 2024-08-09T01:45:12.7552620Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 10406 2024-08-09T01:45:12.7553882Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by ouyuanning** [comment]
还不知道从哪里入手

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
