### ISSUE TITLE
[Bug]: hashtable data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18000]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 12171 2024-08-09T01:45:12.9988017Z WARNING: DATA RACE
 12172 2024-08-09T01:45:12.9988544Z Write at 0x00c046238588 by goroutine 5496:
 12173 2024-08-09T01:45:12.9989673Z   github.com/matrixorigin/matrixone/pkg/container/hashtable.(*StringHashMap).Free()
 12174 2024-08-09T01:45:12.9991427Z       /home/runner/work/matrixone/matrixone/pkg/container/hashtable/string_hash_map.go:63 +0x18a
 12175 2024-08-09T01:45:12.9992875Z   github.com/matrixorigin/matrixone/pkg/common/hashmap.(*StrHashMap).Free()
 12176 2024-08-09T01:45:12.9994525Z       /home/runner/work/matrixone/matrixone/pkg/common/hashmap/strhashmap.go:64 +0x259
 12177 2024-08-09T01:45:12.9995958Z   github.com/matrixorigin/matrixone/pkg/vm/message.(*JoinMap).Free()
 12178 2024-08-09T01:45:12.9997377Z       /home/runner/work/matrixone/matrixone/pkg/vm/message/joinMapMsg.go:110 +0x1fb
 12179 2024-08-09T01:45:12.9998814Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*container).cleanHashMap()
 12180 2024-08-09T01:45:13.0000393Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/types.go:168 +0x3b5
 12181 2024-08-09T01:45:13.0001714Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).Free()
 12182 2024-08-09T01:45:13.0003211Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/types.go:125 +0x382
 12183 2024-08-09T01:45:13.0004617Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup.func2()
 12184 2024-08-09T01:45:13.0006116Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:105 +0x6b
 12185 2024-08-09T01:45:13.0007280Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12186 2024-08-09T01:45:13.0008571Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 12187 2024-08-09T01:45:13.0009625Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12188 2024-08-09T01:45:13.0010797Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12189 2024-08-09T01:45:13.0011857Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 12190 2024-08-09T01:45:13.0012982Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x22f
 12191 2024-08-09T01:45:13.0014140Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup()
 12192 2024-08-09T01:45:13.0015691Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:104 +0x16a
 12193 2024-08-09T01:45:13.0016960Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun()
 12194 2024-08-09T01:45:13.0018592Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:310 +0x6af
 12195 2024-08-09T01:45:13.0019957Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12196 2024-08-09T01:45:13.0021444Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262 +0x14f
 12197 2024-08-09T01:45:13.0022550Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12198 2024-08-09T01:45:13.0023825Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 12199 2024-08-09T01:45:13.0024596Z
 12200 2024-08-09T01:45:13.0024899Z Previous read at 0x00c046238588 by goroutine 5465:
 12201 2024-08-09T01:45:13.0026062Z   github.com/matrixorigin/matrixone/pkg/container/hashtable.(*StringHashMap).Size()
 12202 2024-08-09T01:45:13.0027804Z       /home/runner/work/matrixone/matrixone/pkg/container/hashtable/string_hash_map.go:344 +0x1f3
 12203 2024-08-09T01:45:13.0029288Z   github.com/matrixorigin/matrixone/pkg/common/hashmap.(*StrHashMap).Size()
 12204 2024-08-09T01:45:13.0030849Z       /home/runner/work/matrixone/matrixone/pkg/common/hashmap/strhashmap.go:88 +0x168
 12205 2024-08-09T01:45:13.0032126Z   github.com/matrixorigin/matrixone/pkg/vm/message.(*JoinMap).Size()
 12206 2024-08-09T01:45:13.0033551Z       /home/runner/work/matrixone/matrixone/pkg/vm/message/joinMapMsg.go:127 +0x12c
 12207 2024-08-09T01:45:13.0034919Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).build()
 12208 2024-08-09T01:45:13.0036422Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/join.go:149 +0x335
 12209 2024-08-09T01:45:13.0037781Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).Call()
 12210 2024-08-09T01:45:13.0039262Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/join.go:78 +0x5f2
 12211 2024-08-09T01:45:13.0040638Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call()
 12212 2024-08-09T01:45:13.0042212Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/connector/connector.go:47 +0xbb
 12213 2024-08-09T01:45:13.0380282Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 12214 2024-08-09T01:45:13.0382001Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:107 +0x214
 12215 2024-08-09T01:45:13.0383615Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun()
 12216 2024-08-09T01:45:13.0385235Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:84 +0x3d
 12217 2024-08-09T01:45:13.0386555Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun()
 12218 2024-08-09T01:45:13.0387979Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:302 +0x5c4
 12219 2024-08-09T01:45:13.0389317Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12220 2024-08-09T01:45:13.0390779Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262 +0x14f
 12221 2024-08-09T01:45:13.0391873Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12222 2024-08-09T01:45:13.0393136Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by badboynt1** [comment]
还没时间处理

**Comment by badboynt1** [comment]
fixed
