### ISSUE TITLE
[Bug]: pipeline data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18006]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 12969 2024-08-09T01:45:13.2046469Z ==================
 12970 2024-08-09T01:45:13.2046621Z WARNING: DATA RACE
 12971 2024-08-09T01:45:13.2046829Z Write at 0x00c018f3c6a0 by goroutine 5536:
 12972 2024-08-09T01:45:13.2047253Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 12973 2024-08-09T01:45:13.2047866Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:58 +0x89
 12974 2024-08-09T01:45:13.2048300Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 12975 2024-08-09T01:45:13.2048916Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 12976 2024-08-09T01:45:13.2049409Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 12977 2024-08-09T01:45:13.2050015Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 12978 2024-08-09T01:45:13.2050488Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 12979 2024-08-09T01:45:13.2051218Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 12980 2024-08-09T01:45:13.2051829Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12981 2024-08-09T01:45:13.2052450Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 12982 2024-08-09T01:45:13.2052760Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12983 2024-08-09T01:45:13.2053397Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 12984 2024-08-09T01:45:13.2053410Z
 12985 2024-08-09T01:45:13.2053677Z Previous write at 0x00c018f3c6a0 by goroutine 5490:
 12986 2024-08-09T01:45:13.2054130Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 12987 2024-08-09T01:45:13.2054708Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:58 +0x89
 12988 2024-08-09T01:45:13.2055095Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 12989 2024-08-09T01:45:13.2055662Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 12990 2024-08-09T01:45:13.2056133Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 12991 2024-08-09T01:45:13.2056980Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 12992 2024-08-09T01:45:13.2057551Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 12993 2024-08-09T01:45:13.2058224Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 12994 2024-08-09T01:45:13.2059089Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12995 2024-08-09T01:45:13.2059765Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 12996 2024-08-09T01:45:13.2060234Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12997 2024-08-09T01:45:13.2060943Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by ouyuanning** [comment]
还不知道从哪里入手

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
