### ISSUE TITLE
[Bug]: JoinMap data race 

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18002]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 12445 2024-08-09T01:45:13.1278359Z WARNING: DATA RACE
 12446 2024-08-09T01:45:13.1278961Z Write at 0x00c024687b48 by goroutine 5496:
 12447 2024-08-09T01:45:13.1279534Z   github.com/matrixorigin/matrixone/pkg/vm/message.(*JoinMap).Free()
 12448 2024-08-09T01:45:13.1280374Z       /home/runner/work/matrixone/matrixone/pkg/vm/message/joinMapMsg.go:115 +0x32b
 12449 2024-08-09T01:45:13.1281046Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*container).cleanHashMap()
 12450 2024-08-09T01:45:13.1281846Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/types.go:168 +0x3b5
 12451 2024-08-09T01:45:13.1282408Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).Free()
 12452 2024-08-09T01:45:13.1283218Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/types.go:125 +0x382
 12453 2024-08-09T01:45:13.1283846Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup.func2()
 12454 2024-08-09T01:45:13.1284589Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:105 +0x6b
 12455 2024-08-09T01:45:13.1285010Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12456 2024-08-09T01:45:13.1285652Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 12457 2024-08-09T01:45:13.1286064Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12458 2024-08-09T01:45:13.1286685Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12459 2024-08-09T01:45:13.1287114Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 12460 2024-08-09T01:45:13.1287765Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x22f
 12461 2024-08-09T01:45:13.1288343Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup()
 12462 2024-08-09T01:45:13.1289060Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:104 +0x16a
 12463 2024-08-09T01:45:13.1289596Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun()
 12464 2024-08-09T01:45:13.1290316Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:310 +0x6af
 12465 2024-08-09T01:45:13.1290912Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12466 2024-08-09T01:45:13.1291652Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262 +0x14f
 12467 2024-08-09T01:45:13.1292212Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12468 2024-08-09T01:45:13.1292991Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 12469 2024-08-09T01:45:13.1293011Z
 12470 2024-08-09T01:45:13.1293463Z Previous read at 0x00c024687b48 by goroutine 5465:
 12471 2024-08-09T01:45:13.1294042Z   github.com/matrixorigin/matrixone/pkg/vm/message.(*JoinMap).GetBatches()
 12472 2024-08-09T01:45:13.1294825Z       /home/runner/work/matrixone/matrixone/pkg/vm/message/joinMapMsg.go:57 +0x3c4
 12473 2024-08-09T01:45:13.1295425Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).build()
 12474 2024-08-09T01:45:13.1296251Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/join.go:151 +0x389
 12475 2024-08-09T01:45:13.1296897Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).Call()
 12476 2024-08-09T01:45:13.1297718Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/join.go:78 +0x5f2
 12477 2024-08-09T01:45:13.1298628Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call()
 12478 2024-08-09T01:45:13.1299578Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/connector/connector.go:47 +0xbb
 12479 2024-08-09T01:45:13.1300263Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 12480 2024-08-09T01:45:13.1301059Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:107 +0x214
 12481 2024-08-09T01:45:13.1301642Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun()
 12482 2024-08-09T01:45:13.1302401Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:84 +0x3d
 12483 2024-08-09T01:45:13.1302985Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun()
 12484 2024-08-09T01:45:13.1303884Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:302 +0x5c4
 12485 2024-08-09T01:45:13.1304534Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12486 2024-08-09T01:45:13.1305336Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262 +0x14f
 12487 2024-08-09T01:45:13.1305744Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12488 2024-08-09T01:45:13.1306557Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by badboynt1** [comment]
还没时间处理

**Comment by badboynt1** [comment]
fixed
