### ISSUE TITLE
[Bug]: table_scan data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18003]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 12626 2024-08-09T01:45:13.1543548Z ==================
 12627 2024-08-09T01:45:13.1543716Z WARNING: DATA RACE
 12628 2024-08-09T01:45:13.1543970Z Write at 0x00c018f3c690 by goroutine 5490:
 12629 2024-08-09T01:45:13.1544631Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan.(*TableScan).Prepare()
 12630 2024-08-09T01:45:13.1545499Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/table_scan/table_scan.go:42 +0x5e
 12631 2024-08-09T01:45:13.1545900Z   github.com/matrixorigin/matrixone/pkg/vm.Prepare.func1()
 12632 2024-08-09T01:45:13.1546451Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:37 +0x41
 12633 2024-08-09T01:45:13.1546856Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12634 2024-08-09T01:45:13.1547470Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 12635 2024-08-09T01:45:13.1547855Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12636 2024-08-09T01:45:13.1548468Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12637 2024-08-09T01:45:13.1548989Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12638 2024-08-09T01:45:13.1549692Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12639 2024-08-09T01:45:13.1550090Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12640 2024-08-09T01:45:13.1550698Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12641 2024-08-09T01:45:13.1551079Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 12642 2024-08-09T01:45:13.1551676Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x72
 12643 2024-08-09T01:45:13.1552029Z   github.com/matrixorigin/matrixone/pkg/vm.Prepare()
 12644 2024-08-09T01:45:13.1552576Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:36 +0x12
 12645 2024-08-09T01:45:13.1553093Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 12646 2024-08-09T01:45:13.1553825Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:98 +0x79
 12647 2024-08-09T01:45:13.1554341Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 12648 2024-08-09T01:45:13.1555075Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x1a5
 12649 2024-08-09T01:45:13.1555663Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 12650 2024-08-09T01:45:13.1556387Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 12651 2024-08-09T01:45:13.1556945Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 12652 2024-08-09T01:45:13.1557654Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 12653 2024-08-09T01:45:13.1558196Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 12654 2024-08-09T01:45:13.1558985Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 12655 2024-08-09T01:45:13.1559573Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12656 2024-08-09T01:45:13.1560282Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 12657 2024-08-09T01:45:13.1560638Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12658 2024-08-09T01:45:13.1561378Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 12659 2024-08-09T01:45:13.1561400Z
 12660 2024-08-09T01:45:13.1561696Z Previous write at 0x00c018f3c690 by goroutine 5529:
 12661 2024-08-09T01:45:13.1562337Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan.(*TableScan).Free()
 12662 2024-08-09T01:45:13.1563160Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/table_scan/types.go:94 +0x55c
 12663 2024-08-09T01:45:13.1563769Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup.func2()
 12664 2024-08-09T01:45:13.1564479Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:105 +0x6b
 12665 2024-08-09T01:45:13.1564882Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12666 2024-08-09T01:45:13.1565487Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 12667 2024-08-09T01:45:13.1565893Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12668 2024-08-09T01:45:13.1566497Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12669 2024-08-09T01:45:13.1566898Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12670 2024-08-09T01:45:13.1567502Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12671 2024-08-09T01:45:13.1567905Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 12672 2024-08-09T01:45:13.1568512Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 12673 2024-08-09T01:45:13.1568901Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 12674 2024-08-09T01:45:13.1569506Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x22f
 12675 2024-08-09T01:45:13.1570060Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup()
 12676 2024-08-09T01:45:13.1570772Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:104 +0x16a
 12677 2024-08-09T01:45:13.1571310Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run.func1()
 12678 2024-08-09T01:45:13.1572127Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:180 +0x4c4
 12679 2024-08-09T01:45:13.1572335Z   runtime.deferreturn()
 12680 2024-08-09T01:45:13.1573012Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:602 +0x5d
 12681 2024-08-09T01:45:13.1573569Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 12682 2024-08-09T01:45:13.1574289Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 12683 2024-08-09T01:45:13.1574825Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 12684 2024-08-09T01:45:13.1575532Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 12685 2024-08-09T01:45:13.1576118Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 12686 2024-08-09T01:45:13.1576837Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 12687 2024-08-09T01:45:13.1577178Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 12688 2024-08-09T01:45:13.1577920Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by ouyuanning** [comment]
还不知道从哪里入手

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
