### ISSUE TITLE
[Bug]: Instance crashed during load data

### ISSUE THREAD

**Issue by MOOS2021** [matrixorigin/matrixone#1800]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):cb23ada9a84ddeea8526fd8f12f4e7722edfb3f7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> load data infile '/matrixone/dataset/data_600m/lineorder_flat.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)
ERROR: 
Can't connect to the server

### Steps to Reproduce

```markdown
Set disable-shar-split=ture
loadDataConcurrencyCount=4
load data and then failed
```

### Additional information

{"level":"DEBUG","time":"2022/03/03 14:41:01.054152 +0800","name":"cube.prophet","caller":"etcdserver/server.go:2160","msg":"apply entry normal","node":"node0","consistent-index":193,"entry-index":194,"should-applyV3":true}
{"level":"DEBUG","time":"2022/03/03 14:41:01.054169 +0800","name":"cube.prophet","caller":"etcdserver/server.go:2187","msg":"applyEntryNormal","node":"node0","raftReq":"header:<ID:17576563420787850576 > txn:<compare:<target:VALUE key:\"/electors/leader/prophet-leader\" value:\"\\010\\354\\347\\263\\330\\346\\361\\202\\320\\337\\001\\022\\005node0\\032\\017localhost:30000\" > success:<request_put:<key:\"/prophet/custom/cluster_epoch\" value:\"\\000\\000\\000\\000\\000\\000\\000V\" > > > "}
{"level":"DEBUG","time":"2022/03/03 14:41:01.054379 +0800","name":"cube.prophet","caller":"v3rpc/interceptor.go:182","msg":"request stats","node":"node0","start time":"2022/03/03 14:41:01.053994 +0800","time spent":"356.843µs","remote":"127.0.0.1:39066","response type":"/etcdserverpb.KV/Txn","request count":0,"request size":0,"response count":0,"response size":28,"request content":"compare:<target:VALUE key:\"/electors/leader/prophet-leader\" value_size:35 > success:<request_put:<key:\"/prophet/custom/cluster_epoch\" value_size:8 >> failure:<>"}
2022/03/03 14:41:01 election: not leader

**Comment by domingozhang** [comment]
loadDataConcurrencyCount=16
still happened
