### ISSUE TITLE
[Bug]: SetAnalyzeInfo data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18014]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 13594 2024-08-09T01:45:13.2637947Z ==================
 13595 2024-08-09T01:45:13.2638214Z WARNING: DATA RACE
 13596 2024-08-09T01:45:13.2638459Z Write at 0x00c0236719a8 by goroutine 5536:
 13597 2024-08-09T01:45:13.2638948Z   github.com/matrixorigin/matrixone/pkg/vm.(*OperatorBase).SetInfo()
 13598 2024-08-09T01:45:13.2639494Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:152 +0x794
 13599 2024-08-09T01:45:13.2639887Z   github.com/matrixorigin/matrixone/pkg/vm.SetAnalyzeInfo.func2()
 13600 2024-08-09T01:45:13.2640375Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:105 +0x773
 13601 2024-08-09T01:45:13.2640717Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13602 2024-08-09T01:45:13.2641291Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 13603 2024-08-09T01:45:13.2641694Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13604 2024-08-09T01:45:13.2642297Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13605 2024-08-09T01:45:13.2642676Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 13606 2024-08-09T01:45:13.2643211Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x218
 13607 2024-08-09T01:45:13.2643566Z   github.com/matrixorigin/matrixone/pkg/vm.SetAnalyzeInfo()
 13608 2024-08-09T01:45:13.2644024Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:54 +0x173
 13609 2024-08-09T01:45:13.2644452Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 13610 2024-08-09T01:45:13.2645155Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:104 +0x164
 13611 2024-08-09T01:45:13.2645670Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 13612 2024-08-09T01:45:13.2648721Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x1a5
 13613 2024-08-09T01:45:13.2649223Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 13614 2024-08-09T01:45:13.2649948Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 13615 2024-08-09T01:45:13.2650515Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 13616 2024-08-09T01:45:13.2651237Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 13617 2024-08-09T01:45:13.2651784Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 13618 2024-08-09T01:45:13.2652490Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 13619 2024-08-09T01:45:13.2653078Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 13620 2024-08-09T01:45:13.2653907Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 13621 2024-08-09T01:45:13.2654260Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 13622 2024-08-09T01:45:13.2655076Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 13623 2024-08-09T01:45:13.2655096Z
 13624 2024-08-09T01:45:13.2655388Z Previous read at 0x00c0236719a8 by goroutine 5529:
 13625 2024-08-09T01:45:13.2655949Z   github.com/matrixorigin/matrixone/pkg/vm.(*OperatorBase).GetParallelIdx()
 13626 2024-08-09T01:45:13.2656544Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:216 +0xd3
 13627 2024-08-09T01:45:13.2657197Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Free()
 13628 2024-08-09T01:45:13.2658034Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/projection/types.go:93 +0x221
 13629 2024-08-09T01:45:13.2658818Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup.func2()
 13630 2024-08-09T01:45:13.2659528Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:105 +0x6b
 13631 2024-08-09T01:45:13.2659940Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13632 2024-08-09T01:45:13.2660667Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 13633 2024-08-09T01:45:13.2661075Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13634 2024-08-09T01:45:13.2661675Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13635 2024-08-09T01:45:13.2662067Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 13636 2024-08-09T01:45:13.2662670Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x22f
 13637 2024-08-09T01:45:13.2663221Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup()
 13638 2024-08-09T01:45:13.2664048Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:104 +0x16a
 13639 2024-08-09T01:45:13.2664588Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run.func1()
 13640 2024-08-09T01:45:13.2665291Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:180 +0x4c4
 13641 2024-08-09T01:45:13.2665505Z   runtime.deferreturn()
 13642 2024-08-09T01:45:13.2666109Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:602 +0x5d
 13643 2024-08-09T01:45:13.2666672Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 13644 2024-08-09T01:45:13.2667400Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 13645 2024-08-09T01:45:13.2667933Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 13646 2024-08-09T01:45:13.2668646Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 13647 2024-08-09T01:45:13.2669223Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 13648 2024-08-09T01:45:13.2696078Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 13649 2024-08-09T01:45:13.2696410Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 13650 2024-08-09T01:45:13.2697041Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by qingxinhome** [comment]
分析中， 目前没有结果

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
该问题倪涛的pr已经统一处理掉了，pr：https://github.com/matrixorigin/matrixone/pull/18181， 该issue可以关闭了，请确认 @zhangxu19830126 @badboynt1 @sukki37

**Comment by zhangxu19830126** [comment]
#18181 fixed

**Comment by zhangxu19830126** [comment]
@sukki37 can you close this issue
