### ISSUE TITLE
[Bug]: projection data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18013]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 13495 2024-08-09T01:45:13.2417864Z WARNING: DATA RACE
 13496 2024-08-09T01:45:13.2418088Z Write at 0x00c023671980 by goroutine 5536:
 13497 2024-08-09T01:45:13.2433380Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Prepare()
 13498 2024-08-09T01:45:13.2585255Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/projection/projection.go:47 +0x5e
 13499 2024-08-09T01:45:13.2585701Z   github.com/matrixorigin/matrixone/pkg/vm.Prepare.func1()
 13500 2024-08-09T01:45:13.2586297Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:37 +0x41
 13501 2024-08-09T01:45:13.2586712Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13502 2024-08-09T01:45:13.2587336Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 13503 2024-08-09T01:45:13.2587746Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13504 2024-08-09T01:45:13.2588339Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13505 2024-08-09T01:45:13.2588923Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 13506 2024-08-09T01:45:13.2589534Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x72
 13507 2024-08-09T01:45:13.2589891Z   github.com/matrixorigin/matrixone/pkg/vm.Prepare()
 13508 2024-08-09T01:45:13.2590467Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:36 +0x12
 13509 2024-08-09T01:45:13.2590988Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 13510 2024-08-09T01:45:13.2591745Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:98 +0x79
 13511 2024-08-09T01:45:13.2592441Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 13512 2024-08-09T01:45:13.2593182Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x1a5
 13513 2024-08-09T01:45:13.2593684Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 13514 2024-08-09T01:45:13.2595387Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 13515 2024-08-09T01:45:13.2595960Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 13516 2024-08-09T01:45:13.2596671Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 13517 2024-08-09T01:45:13.2597203Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 13518 2024-08-09T01:45:13.2597928Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 13519 2024-08-09T01:45:13.2598520Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 13520 2024-08-09T01:45:13.2599246Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 13521 2024-08-09T01:45:13.2599608Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 13522 2024-08-09T01:45:13.2600305Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 13523 2024-08-09T01:45:13.2600318Z
 13524 2024-08-09T01:45:13.2600615Z Previous write at 0x00c023671980 by goroutine 5529:
 13525 2024-08-09T01:45:13.2601236Z   github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Free()
 13526 2024-08-09T01:45:13.2602035Z       /home/runner/work/matrixone/matrixone/pkg/sql/colexec/projection/types.go:90 +0x66e
 13527 2024-08-09T01:45:13.2602620Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup.func2()
 13528 2024-08-09T01:45:13.2603286Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:105 +0x6b
 13529 2024-08-09T01:45:13.2603680Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13530 2024-08-09T01:45:13.2604286Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 13531 2024-08-09T01:45:13.2604712Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13532 2024-08-09T01:45:13.2605295Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13533 2024-08-09T01:45:13.2605670Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 13534 2024-08-09T01:45:13.2606252Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x22f
 13535 2024-08-09T01:45:13.2606964Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Cleanup()
 13536 2024-08-09T01:45:13.2607742Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/types.go:104 +0x16a
 13537 2024-08-09T01:45:13.2608255Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run.func1()
 13538 2024-08-09T01:45:13.2608946Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:180 +0x4c4
 13539 2024-08-09T01:45:13.2609175Z   runtime.deferreturn()
 13540 2024-08-09T01:45:13.2609762Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:602 +0x5d
 13541 2024-08-09T01:45:13.2610320Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 13542 2024-08-09T01:45:13.2611043Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 13543 2024-08-09T01:45:13.2611563Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 13544 2024-08-09T01:45:13.2612224Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 13545 2024-08-09T01:45:13.2612793Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 13546 2024-08-09T01:45:13.2613553Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 13547 2024-08-09T01:45:13.2613886Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 13548 2024-08-09T01:45:13.2614645Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by ouyuanning** [comment]
还不知道从哪里入手

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
