### ISSUE TITLE
[Bug]: pipeline panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 13265 2024-08-09T01:45:13.2291790Z 2024/08/09 01:37:40.378617 +0000 ERROR pipeline/pipeline.go:120 panic in pipeline: internal error: panic join receive a joinmap which has been freed!:
 13266 2024-08-09T01:45:13.2292239Z github.com/matrixorigin/matrixone/pkg/vm/message.ReceiveJoinMap
 13267 2024-08-09T01:45:13.2292791Z    /home/runner/work/matrixone/matrixone/pkg/vm/message/joinMapMsg.go:180
 13268 2024-08-09T01:45:13.2293309Z github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).build
 13269 2024-08-09T01:45:13.2293846Z    /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/join.go:147
 13270 2024-08-09T01:45:13.2294351Z github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*InnerJoin).Call
 13271 2024-08-09T01:45:13.2294873Z    /home/runner/work/matrixone/matrixone/pkg/sql/colexec/join/join.go:78
 13272 2024-08-09T01:45:13.2295435Z github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call
 13273 2024-08-09T01:45:13.2296057Z    /home/runner/work/matrixone/matrixone/pkg/sql/colexec/connector/connector.go:47
 13274 2024-08-09T01:45:13.2296513Z github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run
 13275 2024-08-09T01:45:13.2297039Z    /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:107
 13276 2024-08-09T01:45:13.2297532Z github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
 13277 2024-08-09T01:45:13.2298142Z    /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:84
 13278 2024-08-09T01:45:13.2298818Z github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
 13279 2024-08-09T01:45:13.2299401Z    /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:302
 13280 2024-08-09T01:45:13.2299885Z github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
 13281 2024-08-09T01:45:13.2300370Z    /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:262
 13282 2024-08-09T01:45:13.2300636Z github.com/panjf2000/ants/v2.(*goWorker).run.func1
 13283 2024-08-09T01:45:13.2301127Z    /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
 13284 2024-08-09T01:45:13.2301298Z runtime.goexit
 13285 2024-08-09T01:45:13.2301706Z    /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/asm_amd64.s:1695

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by badboynt1** [comment]
还没时间处理

**Comment by badboynt1** [comment]
fixed
