### ISSUE TITLE
[Bug]: plan data race 2

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18016]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 14436 2024-08-09T01:45:13.3827795Z ==================
 14437 2024-08-09T01:45:13.3827968Z WARNING: DATA RACE
 14438 2024-08-09T01:45:13.3828224Z Write at 0x00c0236b7d20 by goroutine 5514:
 14439 2024-08-09T01:45:13.3828759Z   github.com/matrixorigin/matrixone/pkg/sql/plan.AssignAuxIdForExpr()
 14440 2024-08-09T01:45:13.3829467Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/utils.go:1726 +0x37
 14441 2024-08-09T01:45:13.3830050Z   github.com/matrixorigin/matrixone/pkg/sql/compile.ApplyRuntimeFilters()
 14442 2024-08-09T01:45:13.3830888Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/runtime_filter.go:93 +0x575
 14443 2024-08-09T01:45:13.3831553Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 14444 2024-08-09T01:45:13.3832304Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:696 +0xeb7
 14445 2024-08-09T01:45:13.3833009Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 14446 2024-08-09T01:45:13.3833757Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 14447 2024-08-09T01:45:13.3834347Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 14448 2024-08-09T01:45:13.3835075Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 14449 2024-08-09T01:45:13.3835650Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 14450 2024-08-09T01:45:13.3836488Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 14451 2024-08-09T01:45:13.3837041Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 14452 2024-08-09T01:45:13.3837771Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 14453 2024-08-09T01:45:13.3838372Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 14454 2024-08-09T01:45:13.3839106Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 14455 2024-08-09T01:45:13.3839482Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 14456 2024-08-09T01:45:13.3840242Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 14457 2024-08-09T01:45:13.3840252Z
 14458 2024-08-09T01:45:13.3840571Z Previous write at 0x00c0236b7d20 by goroutine 5521:
 14459 2024-08-09T01:45:13.3841107Z   github.com/matrixorigin/matrixone/pkg/sql/plan.AssignAuxIdForExpr()
 14460 2024-08-09T01:45:13.3841807Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/utils.go:1726 +0x37
 14461 2024-08-09T01:45:13.3842392Z   github.com/matrixorigin/matrixone/pkg/sql/compile.ApplyRuntimeFilters()
 14462 2024-08-09T01:45:13.3843217Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/runtime_filter.go:93 +0x575
 14463 2024-08-09T01:45:13.3843875Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 14464 2024-08-09T01:45:13.3844604Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:696 +0xeb7
 14465 2024-08-09T01:45:13.3845185Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 14466 2024-08-09T01:45:13.3845925Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 14467 2024-08-09T01:45:13.3846507Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 14468 2024-08-09T01:45:13.3847226Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 14469 2024-08-09T01:45:13.3847801Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 14470 2024-08-09T01:45:13.3848523Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 14471 2024-08-09T01:45:13.3849083Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 14472 2024-08-09T01:45:13.3849812Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 14473 2024-08-09T01:45:13.3850412Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 14474 2024-08-09T01:45:13.3851238Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 14475 2024-08-09T01:45:13.3851682Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 14476 2024-08-09T01:45:13.3852443Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by XuPeng-SH** [comment]
@aunjgr

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
not working on it today

**Comment by aunjgr** [comment]
已经不能重现

**Comment by zhangxu19830126** [comment]
@sukki37 can you close this issue
