### ISSUE TITLE
[Bug]: SetAnalyzeInfo data race 2

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 13696 2024-08-09T01:45:13.2720862Z ==================
 13697 2024-08-09T01:45:13.2721035Z WARNING: DATA RACE
 13698 2024-08-09T01:45:13.2721275Z Read at 0x00c018f3c220 by goroutine 5544:
 13699 2024-08-09T01:45:13.2721750Z   github.com/matrixorigin/matrixone/pkg/vm.SetAnalyzeInfo.func2()
 13700 2024-08-09T01:45:13.2722308Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:57 +0xd4
 13701 2024-08-09T01:45:13.2722711Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13702 2024-08-09T01:45:13.2723331Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 13703 2024-08-09T01:45:13.2723743Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13704 2024-08-09T01:45:13.2724338Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13705 2024-08-09T01:45:13.2724739Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13706 2024-08-09T01:45:13.2725333Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13707 2024-08-09T01:45:13.2725829Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13708 2024-08-09T01:45:13.2726507Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13709 2024-08-09T01:45:13.2726891Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 13710 2024-08-09T01:45:13.2727499Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x218
 13711 2024-08-09T01:45:13.2727902Z   github.com/matrixorigin/matrixone/pkg/vm.SetAnalyzeInfo()
 13712 2024-08-09T01:45:13.2728438Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:54 +0x173
 13713 2024-08-09T01:45:13.2728939Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 13714 2024-08-09T01:45:13.2729712Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:104 +0x164
 13715 2024-08-09T01:45:13.2730201Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 13716 2024-08-09T01:45:13.2730917Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x1a5
 13717 2024-08-09T01:45:13.2731392Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 13718 2024-08-09T01:45:13.2732185Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 13719 2024-08-09T01:45:13.2732745Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 13720 2024-08-09T01:45:13.2733456Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 13721 2024-08-09T01:45:13.2733984Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 13722 2024-08-09T01:45:13.2734674Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 13723 2024-08-09T01:45:13.2735238Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 13724 2024-08-09T01:45:13.2736036Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 13725 2024-08-09T01:45:13.2736379Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 13726 2024-08-09T01:45:13.2737105Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 13727 2024-08-09T01:45:13.2737117Z
 13728 2024-08-09T01:45:13.2737409Z Previous write at 0x00c018f3c220 by goroutine 5552:
 13729 2024-08-09T01:45:13.2737910Z   github.com/matrixorigin/matrixone/pkg/vm.(*OperatorBase).SetInfo()
 13730 2024-08-09T01:45:13.2738718Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:152 +0x794
 13731 2024-08-09T01:45:13.2739197Z   github.com/matrixorigin/matrixone/pkg/vm.SetAnalyzeInfo.func2()
 13732 2024-08-09T01:45:13.2739764Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:105 +0x773
 13733 2024-08-09T01:45:13.2740176Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13734 2024-08-09T01:45:13.2740762Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:334 +0x196
 13735 2024-08-09T01:45:13.2741160Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13736 2024-08-09T01:45:13.2741743Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13737 2024-08-09T01:45:13.2742128Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13738 2024-08-09T01:45:13.2742752Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13739 2024-08-09T01:45:13.2743145Z   github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp()
 13740 2024-08-09T01:45:13.2743756Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:330 +0x144
 13741 2024-08-09T01:45:13.2744147Z   github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp()
 13742 2024-08-09T01:45:13.2744735Z       /home/runner/work/matrixone/matrixone/pkg/vm/types.go:338 +0x218
 13743 2024-08-09T01:45:13.2745122Z   github.com/matrixorigin/matrixone/pkg/vm.SetAnalyzeInfo()
 13744 2024-08-09T01:45:13.2745659Z       /home/runner/work/matrixone/matrixone/pkg/vm/vm.go:54 +0x173
 13745 2024-08-09T01:45:13.2746146Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run()
 13746 2024-08-09T01:45:13.2747093Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:104 +0x164
 13747 2024-08-09T01:45:13.2747606Z   github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run()
 13748 2024-08-09T01:45:13.2748333Z       /home/runner/work/matrixone/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x1a5
 13749 2024-08-09T01:45:13.2748917Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run()
 13750 2024-08-09T01:45:13.2749703Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:205 +0x7a7
 13751 2024-08-09T01:45:13.2750233Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 13752 2024-08-09T01:45:13.2750892Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:425 +0x1f7
 13753 2024-08-09T01:45:13.2751368Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 13754 2024-08-09T01:45:13.2751982Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 13755 2024-08-09T01:45:13.2752525Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 13756 2024-08-09T01:45:13.2753201Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 13757 2024-08-09T01:45:13.2753541Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 13758 2024-08-09T01:45:13.2754217Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by fengttt** [comment]
dup #18014
