### ISSUE TITLE
[Bug]: vector data race 2

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18019]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 19752 2024-08-09T01:45:14.3454320Z ==================
 19753 2024-08-09T01:45:14.3454476Z WARNING: DATA RACE
 19754 2024-08-09T01:45:14.3454707Z Read at 0x00c046a8fed1 by goroutine 9194:
 19755 2024-08-09T01:45:14.3455181Z   github.com/matrixorigin/matrixone/pkg/container/types.DecodeUint32()
 19756 2024-08-09T01:45:14.3455895Z       /home/runner/work/matrixone/matrixone/pkg/container/types/encoding.go:165 +0x1d1
 19757 2024-08-09T01:45:14.3456451Z   github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).UnmarshalBinary()
 19758 2024-08-09T01:45:14.3457122Z       /home/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:552 +0x180
 19759 2024-08-09T01:45:14.3457779Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeBaseFilterInKind()
 19760 2024-08-09T01:45:14.3458817Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:160 +0x368
 19761 2024-08-09T01:45:14.3459326Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeFilters()
 19762 2024-08-09T01:45:14.3460014Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:342 +0xe04
 19763 2024-08-09T01:45:14.3460532Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 19764 2024-08-09T01:45:14.3461459Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:67 +0x1ce4
 19765 2024-08-09T01:45:14.3461976Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 19766 2024-08-09T01:45:14.3462754Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:54 +0x188d
 19767 2024-08-09T01:45:14.3463204Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.NewReader()
 19768 2024-08-09T01:45:14.3463865Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/reader.go:253 +0x86
 19769 2024-08-09T01:45:14.3464424Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 19770 2024-08-09T01:45:14.3465120Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1844 +0x6a8
 19771 2024-08-09T01:45:14.3465740Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 19772 2024-08-09T01:45:14.3466508Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 19773 2024-08-09T01:45:14.3467000Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 19774 2024-08-09T01:45:14.3467640Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 19775 2024-08-09T01:45:14.3468156Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 19776 2024-08-09T01:45:14.3468765Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 19777 2024-08-09T01:45:14.3469248Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 19778 2024-08-09T01:45:14.3469849Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 19779 2024-08-09T01:45:14.3470317Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 19780 2024-08-09T01:45:14.3470938Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 19781 2024-08-09T01:45:14.3471446Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 19782 2024-08-09T01:45:14.3472089Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 19783 2024-08-09T01:45:14.3472402Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 19784 2024-08-09T01:45:14.3473048Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 19785 2024-08-09T01:45:14.3473179Z
 19786 2024-08-09T01:45:14.3473454Z Previous write at 0x00c046a8fed0 by goroutine 9187:
 19787 2024-08-09T01:45:14.3473637Z   runtime.slicecopy()
 19788 2024-08-09T01:45:14.3474240Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/slice.go:325 +0x0
 19789 2024-08-09T01:45:14.3474412Z   bytes.Clone()
 19790 2024-08-09T01:45:14.3474935Z       /opt/hostedtoolcache/go/1.22.3/x64/src/bytes/bytes.go:1346 +0x2918
 19791 2024-08-09T01:45:14.3475354Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 19792 2024-08-09T01:45:14.3476010Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:1044 +0x2869
 19793 2024-08-09T01:45:14.3476417Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 19794 2024-08-09T01:45:14.3477076Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:956 +0x3a65
 19795 2024-08-09T01:45:14.3477645Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 19796 2024-08-09T01:45:14.3478281Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:649 +0x7a4
 19797 2024-08-09T01:45:14.3478790Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 19798 2024-08-09T01:45:14.3479515Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 19799 2024-08-09T01:45:14.3480015Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 19800 2024-08-09T01:45:14.3480623Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 19801 2024-08-09T01:45:14.3481097Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 19802 2024-08-09T01:45:14.3481707Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 19803 2024-08-09T01:45:14.3482165Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 19804 2024-08-09T01:45:14.3482862Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 19805 2024-08-09T01:45:14.3483363Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 19806 2024-08-09T01:45:14.3484004Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 19807 2024-08-09T01:45:14.3484320Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 19808 2024-08-09T01:45:14.3484981Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by fengttt** [comment]
Dup #18018
