### ISSUE TITLE
[Bug]: scope panic 2

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18017]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 14522 2024-08-09T01:45:13.3896591Z 2024/08/09 01:37:40.417974 +0000 ERROR cn-service compile/scope.go:388 panic in scope run {"service": "2-cn-2", "uuid": "2-cn-2", "sql": "execute __mo_stmt_id_5", "error": "internal error: panic runtime error:        invalid memory address or nil pointer dereference: \nruntime.panicmem\n\t/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:261\nruntime.sigpanic\n\t/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/signal_unix.go:881\ngithub.com/matrixo       rigin/matrixone/pkg/sql/compile.ApplyRuntimeFilters\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/runtime_filter.go:115\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter\n\t/home/runner/work/matrixo       ne/matrixone/pkg/sql/compile/scope.go:696\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.bu       ildScanParallelRun\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412\ngithub.       com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/home/runner/work/matrixone/m       atrixone/pkg/sql/compile/scope.go:264\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/asm_amd       64.s:1695", "session_id": "019134c8-b5d7-720a-9587-e9430897cd3f", "statement_id": "019134c8-cb9b-7485-9a48-174cd9616e2d", "txn_id": "019134c8cb7d735e94113cb297da7433"}

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
