### ISSUE TITLE
[Bug]: vector data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18018]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 19653 2024-08-09T01:45:14.3404120Z WARNING: DATA RACE
 19654 2024-08-09T01:45:14.3404336Z Read at 0x00c046a8fec0 by goroutine 9194:
 19655 2024-08-09T01:45:14.3404933Z   github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).UnmarshalBinary()
 19656 2024-08-09T01:45:14.3405598Z       /home/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:544 +0x64
 19657 2024-08-09T01:45:14.3406170Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeBaseFilterInKind()
 19658 2024-08-09T01:45:14.3406890Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:160 +0x368
 19659 2024-08-09T01:45:14.3407430Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeFilters()
 19660 2024-08-09T01:45:14.3408121Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:342 +0xe04
 19661 2024-08-09T01:45:14.3408618Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 19662 2024-08-09T01:45:14.3409363Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:67 +0x1ce4
 19663 2024-08-09T01:45:14.3410214Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 19664 2024-08-09T01:45:14.3411086Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:54 +0x188d
 19665 2024-08-09T01:45:14.3411537Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.NewReader()
 19666 2024-08-09T01:45:14.3412197Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/reader.go:253 +0x86
 19667 2024-08-09T01:45:14.3412747Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 19668 2024-08-09T01:45:14.3413483Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1844 +0x6a8
 19669 2024-08-09T01:45:14.3414289Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 19670 2024-08-09T01:45:14.3415082Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 19671 2024-08-09T01:45:14.3415561Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 19672 2024-08-09T01:45:14.3416188Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 19673 2024-08-09T01:45:14.3416796Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 19674 2024-08-09T01:45:14.3417409Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 19675 2024-08-09T01:45:14.3417881Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 19676 2024-08-09T01:45:14.3418777Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 19677 2024-08-09T01:45:14.3419261Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 19678 2024-08-09T01:45:14.3419992Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 19679 2024-08-09T01:45:14.3420495Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 19680 2024-08-09T01:45:14.3421104Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 19681 2024-08-09T01:45:14.3421419Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 19682 2024-08-09T01:45:14.3422041Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 19683 2024-08-09T01:45:14.3422054Z
 19684 2024-08-09T01:45:14.3422329Z Previous write at 0x00c046a8fec0 by goroutine 9187:
 19685 2024-08-09T01:45:14.3422509Z   runtime.slicecopy()
 19686 2024-08-09T01:45:14.3423014Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/slice.go:325 +0x0
 19687 2024-08-09T01:45:14.3423173Z   bytes.Clone()
 19688 2024-08-09T01:45:14.3423690Z       /opt/hostedtoolcache/go/1.22.3/x64/src/bytes/bytes.go:1346 +0x2918
 19689 2024-08-09T01:45:14.3424089Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 19690 2024-08-09T01:45:14.3424722Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:1044 +0x2869
 19691 2024-08-09T01:45:14.3425112Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 19692 2024-08-09T01:45:14.3425723Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:956 +0x3a65
 19693 2024-08-09T01:45:14.3426266Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 19694 2024-08-09T01:45:14.3426868Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:649 +0x7a4
 19695 2024-08-09T01:45:14.3427355Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 19696 2024-08-09T01:45:14.3427959Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 19697 2024-08-09T01:45:14.3428451Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 19698 2024-08-09T01:45:14.3429039Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 19699 2024-08-09T01:45:14.3429513Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 19700 2024-08-09T01:45:14.3430116Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 19701 2024-08-09T01:45:14.3430575Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 19702 2024-08-09T01:45:14.3431171Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 19703 2024-08-09T01:45:14.3431795Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 19704 2024-08-09T01:45:14.3432398Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 19705 2024-08-09T01:45:14.3432812Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 19706 2024-08-09T01:45:14.3433442Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by fengttt** [comment]
Please sync with dist tae team to eliminate deep copy.

**Comment by ouyuanning** [comment]
倪涛的PR已fixed
