### ISSUE TITLE
[Bug]: vector data race 4

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18021]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 20058 2024-08-09T01:45:14.3625842Z ==================
 20059 2024-08-09T01:45:14.3625996Z WARNING: DATA RACE
 20060 2024-08-09T01:45:14.3626219Z Read at 0x00c046a8fed9 by goroutine 9194:
 20061 2024-08-09T01:45:14.3626787Z   github.com/matrixorigin/matrixone/pkg/container/types.(*Varlena).GetByteSlice()
 20062 2024-08-09T01:45:14.3627450Z       /home/runner/work/matrixone/matrixone/pkg/container/types/bytes.go:101 +0x36
 20063 2024-08-09T01:45:14.3628043Z   github.com/matrixorigin/matrixone/pkg/container/vector.Intersection2VectorVarlen()
 20064 2024-08-09T01:45:14.3628756Z       /home/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:4438 +0x39d
 20065 2024-08-09T01:45:14.3629327Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeBaseFilterInKind()
 20066 2024-08-09T01:45:14.3630023Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:302 +0x3351
 20067 2024-08-09T01:45:14.3630524Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeFilters()
 20068 2024-08-09T01:45:14.3631203Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:342 +0xe04
 20069 2024-08-09T01:45:14.3631714Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 20070 2024-08-09T01:45:14.3632523Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:67 +0x1ce4
 20071 2024-08-09T01:45:14.3633021Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 20072 2024-08-09T01:45:14.3633783Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:54 +0x188d
 20073 2024-08-09T01:45:14.3634240Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.NewReader()
 20074 2024-08-09T01:45:14.3634930Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/reader.go:253 +0x86
 20075 2024-08-09T01:45:14.3635522Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 20076 2024-08-09T01:45:14.3636257Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1844 +0x6a8
 20077 2024-08-09T01:45:14.3636921Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 20078 2024-08-09T01:45:14.3637922Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 20079 2024-08-09T01:45:14.3638539Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 20080 2024-08-09T01:45:14.3639199Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 20081 2024-08-09T01:45:14.3639701Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 20082 2024-08-09T01:45:14.3640322Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 20083 2024-08-09T01:45:14.3640819Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 20084 2024-08-09T01:45:14.3641474Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 20085 2024-08-09T01:45:14.3641962Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 20086 2024-08-09T01:45:14.3642565Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 20087 2024-08-09T01:45:14.3643090Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 20088 2024-08-09T01:45:14.3643812Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 20089 2024-08-09T01:45:14.3644131Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 20090 2024-08-09T01:45:14.3644776Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 20091 2024-08-09T01:45:14.3644793Z
 20092 2024-08-09T01:45:14.3645068Z Previous write at 0x00c046a8fed8 by goroutine 9187:
 20093 2024-08-09T01:45:14.3645254Z   runtime.slicecopy()
 20094 2024-08-09T01:45:14.3645773Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/slice.go:325 +0x0
 20095 2024-08-09T01:45:14.3646030Z   bytes.Clone()
 20096 2024-08-09T01:45:14.3646562Z       /opt/hostedtoolcache/go/1.22.3/x64/src/bytes/bytes.go:1346 +0x2918
 20097 2024-08-09T01:45:14.3646979Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 20098 2024-08-09T01:45:14.3647636Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:1044 +0x2869
 20099 2024-08-09T01:45:14.3648052Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 20100 2024-08-09T01:45:14.3648707Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:956 +0x3a65
 20101 2024-08-09T01:45:14.3649280Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 20102 2024-08-09T01:45:14.3649912Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:649 +0x7a4
 20103 2024-08-09T01:45:14.3650418Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 20104 2024-08-09T01:45:14.3651062Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 20105 2024-08-09T01:45:14.3651562Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 20106 2024-08-09T01:45:14.3652178Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 20107 2024-08-09T01:45:14.3652650Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 20108 2024-08-09T01:45:14.3653270Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 20109 2024-08-09T01:45:14.3653761Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 20110 2024-08-09T01:45:14.3654403Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 20111 2024-08-09T01:45:14.3654932Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 20112 2024-08-09T01:45:14.3655576Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 20113 2024-08-09T01:45:14.3655893Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 20114 2024-08-09T01:45:14.3656567Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by fengttt** [comment]
dup #18018
