### ISSUE TITLE
[Bug]: vector data. race 3

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18020]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 19956 2024-08-09T01:45:14.3557844Z ==================
 19957 2024-08-09T01:45:14.3558007Z WARNING: DATA RACE
 19958 2024-08-09T01:45:14.3558220Z Read at 0x00c046a8fef9 by goroutine 9194:
 19959 2024-08-09T01:45:14.3558659Z   github.com/matrixorigin/matrixone/pkg/container/types.DecodeBool()
 19960 2024-08-09T01:45:14.3559331Z       /home/runner/work/matrixone/matrixone/pkg/container/types/encoding.go:113 +0x6e7
 19961 2024-08-09T01:45:14.3559892Z   github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).UnmarshalBinary()
 19962 2024-08-09T01:45:14.3560552Z       /home/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:584 +0x69b
 19963 2024-08-09T01:45:14.3561099Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeBaseFilterInKind()
 19964 2024-08-09T01:45:14.3561741Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:160 +0x368
 19965 2024-08-09T01:45:14.3562214Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.mergeFilters()
 19966 2024-08-09T01:45:14.3562948Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/util.go:342 +0xe04
 19967 2024-08-09T01:45:14.3563448Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 19968 2024-08-09T01:45:14.3564195Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:67 +0x1ce4
 19969 2024-08-09T01:45:14.3564682Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.newBasePKFilter()
 19970 2024-08-09T01:45:14.3565426Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/pk_filter_base.go:54 +0x188d
 19971 2024-08-09T01:45:14.3566010Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.NewReader()
 19972 2024-08-09T01:45:14.3566673Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/reader.go:253 +0x86
 19973 2024-08-09T01:45:14.3567223Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).BuildReaders()
 19974 2024-08-09T01:45:14.3567929Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table.go:1844 +0x6a8
 19975 2024-08-09T01:45:14.3568555Z   github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTableDelegate).BuildReaders()
 19976 2024-08-09T01:45:14.3569334Z       /home/runner/work/matrixone/matrixone/pkg/vm/engine/disttae/txn_table_sharding.go:317 +0xfe
 19977 2024-08-09T01:45:14.3569831Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 19978 2024-08-09T01:45:14.3570482Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1213 +0xb04
 19979 2024-08-09T01:45:14.3570989Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 19980 2024-08-09T01:45:14.3571630Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 19981 2024-08-09T01:45:14.3572101Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 19982 2024-08-09T01:45:14.3572710Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 19983 2024-08-09T01:45:14.3573177Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 19984 2024-08-09T01:45:14.3573789Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 19985 2024-08-09T01:45:14.3574318Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 19986 2024-08-09T01:45:14.3574953Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 19987 2024-08-09T01:45:14.3575269Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 19988 2024-08-09T01:45:14.3575919Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb
 19989 2024-08-09T01:45:14.3575928Z
 19990 2024-08-09T01:45:14.3576195Z Previous write at 0x00c046a8fef8 by goroutine 9187:
 19991 2024-08-09T01:45:14.3576377Z   runtime.slicecopy()
 19992 2024-08-09T01:45:14.3576881Z       /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/slice.go:325 +0x0
 19993 2024-08-09T01:45:14.3577038Z   bytes.Clone()
 19994 2024-08-09T01:45:14.3577545Z       /opt/hostedtoolcache/go/1.22.3/x64/src/bytes/bytes.go:1346 +0x2918
 19995 2024-08-09T01:45:14.3578052Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 19996 2024-08-09T01:45:14.3578966Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:1044 +0x2869
 19997 2024-08-09T01:45:14.3579493Z   github.com/matrixorigin/matrixone/pkg/sql/plan.DeepCopyExpr()
 19998 2024-08-09T01:45:14.3580129Z       /home/runner/work/matrixone/matrixone/pkg/sql/plan/deepcopy.go:956 +0x3a65
 19999 2024-08-09T01:45:14.3580678Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).handleRuntimeFilter()
 20000 2024-08-09T01:45:14.3581330Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:649 +0x7a4
 20001 2024-08-09T01:45:14.3581841Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).buildReaders()
 20002 2024-08-09T01:45:14.3582487Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:1160 +0x59
 20003 2024-08-09T01:45:14.3583005Z   github.com/matrixorigin/matrixone/pkg/sql/compile.buildScanParallelRun()
 20004 2024-08-09T01:45:14.3583663Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:553 +0xef
 20005 2024-08-09T01:45:14.3584165Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun()
 20006 2024-08-09T01:45:14.3584947Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:412 +0x1ae
 20007 2024-08-09T01:45:14.3585440Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun()
 20008 2024-08-09T01:45:14.3586072Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:351 +0x568
 20009 2024-08-09T01:45:14.3600227Z   github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
 20010 2024-08-09T01:45:14.3601125Z       /home/runner/work/matrixone/matrixone/pkg/sql/compile/scope.go:264 +0x2b7
 20011 2024-08-09T01:45:14.3601843Z   github.com/panjf2000/ants/v2.(*goWorker).run.func1()
 20012 2024-08-09T01:45:14.3602739Z       /home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0xdb

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by fengttt** [comment]
Dup #18018
