### ISSUE TITLE
[Subtask]: optimize restore sub db

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#18023]
### Parent Issue

#17468

### Detail of Subtask

optimize restore sub db
support show create database with snapshot

**Comment by YANGGMM** [comment]
对应 prd中 
2.请注意：恢复订阅库并不能恢复该订阅库当时的数据，仅能恢复这条订阅关系，因为原始数据是在发布租户中。
3.如果恢复一个已被删除的订阅库，且该订阅库的对应发布现在已经被删除了，则不必恢复这个订阅库。
4.如果将数据恢复到新租户，则不需要恢复订阅库（因为发布方没有发布给这个新租户，无法订阅成功）
9.订阅数据恢复的粒度只能是订阅级别（或者说是数据库级别），不能单独恢复一个订阅表

还有集群级别的sub 库恢复

**Comment by YANGGMM** [comment]
@Ariznawlll  plz test

**Comment by Ariznawlll** [comment]
1. 恢复订阅库并不能恢复该订阅库当时的数据，仅能恢复这条订阅关系，因为原始数据是在发布租户中。
2. 如果恢复一个已被删除的订阅库，且该订阅库的对应发布现在已经被删除了，则不必恢复这个订阅库。
3. 如果将数据恢复到新租户，则不需要恢复订阅库（因为发布方没有发布给这个新租户，无法订阅成功）
4. 订阅数据恢复的粒度只能是订阅级别（或者说是数据库级别），不能单独恢复一个订阅表

以上已测试完成

**Comment by Ariznawlll** [comment]
1. 恢复订阅库并不能恢复该订阅库当时的数据，仅能恢复这条订阅关系，因为原始数据是在发布租户中。
2. 如果恢复一个已被删除的订阅库，且该订阅库的对应发布现在已经被删除了，则不必恢复这个订阅库。
3. 如果将数据恢复到新租户，则不需要恢复订阅库（因为发布方没有发布给这个新租户，无法订阅成功）
4. 订阅数据恢复的粒度只能是订阅级别（或者说是数据库级别），不能单独恢复一个订阅表

1.2-dev以上已测试完成
