### ISSUE TITLE
[Bug]: frontend data race

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18022]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

109034 2024-08-09T01:46:19.1700523Z ==================
109035 2024-08-09T01:46:19.1700712Z WARNING: DATA RACE
109036 2024-08-09T01:46:19.1700964Z Write at 0x00c024723eb8 by goroutine 13006:
109037 2024-08-09T01:46:19.1701548Z   github.com/matrixorigin/matrixone/pkg/frontend.(*GlobalSysVarsMgr).Get()
109038 2024-08-09T01:46:19.1702434Z       /home/runner/work/matrixone/matrixone/pkg/frontend/variables.go:969 +0x1ab
109039 2024-08-09T01:46:19.1703176Z   github.com/matrixorigin/matrixone/pkg/frontend.(*Session).InitSystemVariables()
109040 2024-08-09T01:46:19.1703909Z       /home/runner/work/matrixone/matrixone/pkg/frontend/session.go:256 +0x8b
109041 2024-08-09T01:46:19.1704576Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).authenticateUser()
109042 2024-08-09T01:46:19.1705490Z       /home/runner/work/matrixone/matrixone/pkg/frontend/mysql_protocol.go:1372 +0x4d1
109043 2024-08-09T01:46:19.1706163Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).Authenticate()
109044 2024-08-09T01:46:19.1706966Z       /home/runner/work/matrixone/matrixone/pkg/frontend/mysql_protocol.go:1470 +0x21d
109045 2024-08-09T01:46:19.1707513Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handshake()
109046 2024-08-09T01:46:19.1708231Z       /home/runner/work/matrixone/matrixone/pkg/frontend/server.go:285 +0x10d9
109047 2024-08-09T01:46:19.1708779Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn()
109048 2024-08-09T01:46:19.1709484Z       /home/runner/work/matrixone/matrixone/pkg/frontend/server.go:183 +0x487
109049 2024-08-09T01:46:19.1710124Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept.gowrap2()
109050 2024-08-09T01:46:19.1710815Z       /home/runner/work/matrixone/matrixone/pkg/frontend/server.go:153 +0x4f
109051 2024-08-09T01:46:19.1710828Z
109052 2024-08-09T01:46:19.1711129Z Previous read at 0x00c024723eb8 by goroutine 12988:
109053 2024-08-09T01:46:19.1711702Z   github.com/matrixorigin/matrixone/pkg/frontend.(*SystemVariables).Clone()
109054 2024-08-09T01:46:19.1712533Z       /home/runner/work/matrixone/matrixone/pkg/frontend/variables.go:997 +0xcf
109055 2024-08-09T01:46:19.1713164Z   github.com/matrixorigin/matrixone/pkg/frontend.(*Session).InitSystemVariables()
109056 2024-08-09T01:46:19.1713879Z       /home/runner/work/matrixone/matrixone/pkg/frontend/session.go:259 +0x124
109057 2024-08-09T01:46:19.1714580Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).authenticateUser()
109058 2024-08-09T01:46:19.1715384Z       /home/runner/work/matrixone/matrixone/pkg/frontend/mysql_protocol.go:1372 +0x4d1
109059 2024-08-09T01:46:19.1716048Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).Authenticate()
109060 2024-08-09T01:46:19.1716849Z       /home/runner/work/matrixone/matrixone/pkg/frontend/mysql_protocol.go:1470 +0x21d
109061 2024-08-09T01:46:19.1717393Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handshake()
109062 2024-08-09T01:46:19.1718111Z       /home/runner/work/matrixone/matrixone/pkg/frontend/server.go:285 +0x10d9
109063 2024-08-09T01:46:19.1718660Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn()
109064 2024-08-09T01:46:19.1719365Z       /home/runner/work/matrixone/matrixone/pkg/frontend/server.go:183 +0x487
109065 2024-08-09T01:46:19.1720004Z   github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept.gowrap2()
109066 2024-08-09T01:46:19.1720697Z       /home/runner/work/matrixone/matrixone/pkg/frontend/server.go:153 +0x4f

### Steps to Reproduce

```Markdown
run ci ut TestMultiClusterCanWork, TestBaseClusterCanWorkWithNewCluster
```

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
好像已经解决了

**Comment by ck89119** [comment]
same as #17972
