### ISSUE TITLE
[Bug]:  sql run too slow

### ISSUE THREAD

**Issue by PHK-20** [matrixorigin/matrixone#18034]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

b44e7327a

### Commit ID

b44e7327a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: dev
- Others:
```

### Actual Behavior

sql run elapsed: 4min

{"elapsed": "4m4.353421095s", "rows": 0, "sql": "SELECT `statement_id`,any_value(`stats`) as `stats`,any_value(`duration`) as `duration`,any_value(`sql_source_type`) as `sql_source_type`,any_value(`account`) as `account`,any_value(`response_at`) as `response_at` FROM `system`.`statement_info` WHERE status != 'Running' and account != 'sys' and account != 'mocloud_mo_ob' and response_at >= '2024-08-09 06:30:00' and response_at < '2024-08-09 06:31:00' GROUP BY `statement_id`"}

### Steps to Reproduce

```Markdown
execute sql:
SELECT `statement_id`,any_value(`stats`) as `stats`,any_value(`duration`) as `duration`,any_value(`sql_source_type`) as `sql_source_type`,any_value(`account`) as `account`,any_value(`response_at`) as `response_at` FROM `system`.`statement_info` WHERE status != 'Running' and account != 'sys' and account != 'mocloud_mo_ob' and response_at >= '2024-08-09 06:30:00' and response_at < '2024-08-09 06:31:00
```

**Comment by sukki37** [comment]
Need more context information to assist with locating the issue.

**Comment by PHK-20** [comment]
<img width="893" alt="image" src="https://github.com/user-attachments/assets/9368c6e3-4934-4593-bcbb-5b6e7c182ae0">

cause by shared cn cpu 100%
