### ISSUE TITLE
[Bug]: TestGlobalCheckpoint5 failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#18041]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/10316738916/job/28559590151?pr=17982

[job-logs (1).txt](https://github.com/user-attachments/files/16574071/job-logs.1.txt)

### Steps to Reproduce

```Markdown
run ut
```

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by jiangxinmeng1** [comment]
还没进展

**Comment by XuPeng-SH** [comment]
Tombstone分支后，所有的实现都完全不一样，可以先close,后续遇到再提新的issue
