### ISSUE TITLE
[Bug]: 'DATE' not support Max

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1805]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):89d2a246e4258d3d238d07cff329d243e3b33e16
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT sum(LO_REVENUE), LO_ORDERDATE, P_BRAND, toYear(LO_ORDERDATE) AS year FROM lineorder_flat GROUP BY year, P_BRAND ORDER BY year, P_BRAND;
ERROR 1105 (HY000): unknown error:'DATE' not support Max

**Comment by m-schen** [comment]
date and datetime types need to be handled in NewMax and NewMin function, try to reuse the process of int32 and int64 type or make a new process.

**Comment by broccoliSpicy** [comment]
fixed.
