### ISSUE TITLE
[Bug]: performance regression for point select with pk in zywl benchmark

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#18053]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

129上跑zywl的主键点查，tps从六七万下降到一两万。
经过二分，确定是https://github.com/matrixorigin/matrixone/pull/17823  这个pr导致的

### Steps to Reproduce

```Markdown
129跑zywl的主键点查
```

**Comment by m-schen** [comment]
已修复，是一个全局锁由于互斥锁变成channel导致的问题，channel的效率太低了。
