### ISSUE TITLE
[Bug]: [0813] big-data-regression: mo hung when running sql 'set global sql_mode = **'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18074]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

397515c08722cf54d7eda3127047401a6d4944c7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url:**  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10353329514/job/28679239807  
(Queries 10Y-> Math 10Y test)

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/0c3016c9-5171-4596-aaca-adc05fc5df06">

pod状态：oom了
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/9c993b3f-fd98-40d1-bebb-d6f71d25c54b">
<img width="688" alt="image" src="https://github.com/user-attachments/assets/2f98551d-76c2-41c1-b2c6-aa252b84bed6">

**oom 前后一分钟范围内的memory使用情况:** 
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Oox%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%27mo-big-data-20240812%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221723505555000%22,%22to%22:%221723505675000%22%7D%7D%7D&schemaVersion=1&orgId=1

**longrunning日志：**
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%228Ok%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240812%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723505615000%22,%22to%22:%221723550400000%22%7D%7D%7D&schemaVersion=1&orgId=1

**longrunning profile:** 
 [CN_31333762-3965-6339-6532-373334656533_leakcheck_routine_01914b16-01c3-7ec9-ad67-0a65b9eb29ab.gz](https://github.com/user-attachments/files/16597412/CN_31333762-3965-6339-6532-373334656533_leakcheck_routine_01914b16-01c3-7ec9-ad67-0a65b9eb29ab.gz)

### Steps to Reproduce

```Markdown
trigger big-data test.

测试配置：https://github.com/matrixorigin/mo-nightly-regression/blob/big_data/big-data-tke.yaml

数据量：10亿
```

**Comment by LeftHandCold** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Oox%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%22pod%22%5D,%22labelSelector%22:%22%7Bpod%3D%5C%22nightly-regression-dis-tp-cn-xp7rg%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22%7D%5D,%22range%22:%7B%22from%22:%221723505607697%22,%22to%22:%221723505622672%22%7D%7D%7D&schemaVersion=1&orgId=1
@ouyuanning 帮忙看一下

**Comment by ouyuanning** [comment]
看里面都是agg的内存占用，明松有空时候帮忙看看吧

**Comment by m-schen** [comment]
set全局变量怎么可能导致oom...

**Comment by m-schen** [comment]
.

**Comment by m-schen** [comment]
请假了

**Comment by m-schen** [comment]
在忙pipeline spool

**Comment by m-schen** [comment]
在忙pipeline spool

**Comment by m-schen** [comment]
还没有空看

**Comment by m-schen** [comment]
还没有空看

**Comment by m-schen** [comment]
往后放一下

**Comment by m-schen** [comment]
处理其他bug中

**Comment by m-schen** [comment]
这个还没看

**Comment by m-schen** [comment]
issue比较古老了，需要跟QA确认一下最近是否还有这个情况发生。
如果没有的话将会先关闭。

To Be Continue...

**Comment by Ariznawlll** [comment]
> issue比较古老了，需要跟QA确认一下最近是否还有这个情况发生。 如果没有的话将会先关闭。
> 
> To Be Continue...

没再出现，先关掉了
