### ISSUE TITLE
[Bug]: panic in disttae.(*blockListRelData).UnmarshalBinary

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#18077]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

found in check-in regression tests: https://github.com/matrixorigin/matrixone/pull/18043/checks 

loki log: https://grafana.ci.matrixorigin.cn/goto/lS-XrSjIg?orgId=1

ci log: https://github.com/matrixorigin/matrixone/actions/runs/10363319404/job/28687030972?pr=18043

**Comment by triump2020** [comment]
加了日志尝试复现了几次，没有复现.

**Comment by triump2020** [comment]
No repro yet.

**Comment by triump2020** [comment]
No repro yet.

**Comment by triump2020** [comment]
@reusee   [PR](https://github.com/matrixorigin/matrixone/pull/18396) should have fixed it.

**Comment by reusee** [comment]
已修复

**Comment by aressu1985** [comment]
fixed
