### ISSUE TITLE
[Bug]: [date 8.12]1.2-dev tke regression:   mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18082]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

8cb12fc05

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10354667747/job/28686612032
<img width="1504" alt="企业微信截图_f9b6e357-5369-48a7-956a-329d3bed9fe3" src="https://github.com/user-attachments/assets/19a15af2-5b35-494d-938f-95878adcd319">

long running mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22YeO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-8cb12fc05-20240812%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723528834460%22,%22to%22:%221723536034460%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression
```

**Comment by LeftHandCold** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22YeO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-8cb12fc05-20240812%5C%22%7D%20%7C%3D%20%60wait%20too%20long%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723528834000%22,%22to%22:%221723530754000%22%7D%7D%7D&schemaVersion=1&orgId=1
从06:31开始就有有大量的lock wait too long，请 @zhangxu19830126 帮忙排查一下

**Comment by zhangxu19830126** [comment]
@iamlinjunhong stop retry on context deadline error

**Comment by heni02** [comment]
leakcheck_routine文件：
[CN_33366462-3834-3161-6233-613864396465_leakcheck_routine_01914a8a-b6a0-7e43-b740-dcf78a4facb6.gz](https://github.com/user-attachments/files/16597367/CN_33366462-3834-3161-6233-613864396465_leakcheck_routine_01914a8a-b6a0-7e43-b740-dcf78a4facb6.gz)
[CN_62386232-6262-3961-3161-316165356666_leakcheck_routine_01914a8a-bc77-7b1f-a7bb-a9edd2dc46b4.gz](https://github.com/user-attachments/files/16597372/CN_62386232-6262-3961-3161-316165356666_leakcheck_routine_01914a8a-bc77-7b1f-a7bb-a9edd2dc46b4.gz)

**Comment by heni02** [comment]
1.2 commit:17faaec0d
confirm，closed
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10474398951/job/29009529833
