### ISSUE TITLE
[Bug]: create a new mo acccount, Auth failed: info: access denied for account 

### ISSUE THREAD

**Issue by PHK-20** [matrixorigin/matrixone#18107]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

9b57fc33a

### Commit ID

9b57fc33a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: dev
- Others:
```

### Actual Behavior

<img width="1244" alt="企业微信截图_f0560938-c80d-451f-a387-c8da44d1c033" src="https://github.com/user-attachments/assets/1019f1ec-3e7e-489b-a761-4270b0bea715">

dev env

create a new account by sys account, and login 

### Steps to Reproduce

```Markdown
1. local port forward  16001 to dev env 6001
2. login by sys account: mysql -h 127.0.0.1 -P 16001 -u dump -p
3. create a new account:  create account if not exists `phk_test_02` admin_name 'admin' identified by 'Test123456';
4. exit mysql client
5. mysql -h 127.0.0.1 -P 16001 -u phk_test_02:admin:accountadmin -pTest123456
```

**Comment by daviszhen** [comment]
@PHK-20 租户名带有横杠的加双引号。

**Comment by aylei** [comment]
@PHK-20 PTAL

**Comment by PHK-20** [comment]
已验证
