### ISSUE TITLE
[Docs]: the architecture picture 

### ISSUE THREAD

**Issue by akaError** [matrixorigin/matrixone#1811]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```markdown
"JIT complication" should be "JIT compilation"?
```

**Comment by dengn** [comment]
Right. It should be `JIT Compilation`. Thanks!

**Comment by dengn** [comment]
Issue fixed  https://github.com/matrixorigin/artwork/pull/7
