### ISSUE TITLE
[Bug]: Unit Test Failed

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1812]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): commit-id:a8a9da5fc07132ef5ad1b128575136d19c055682
- Hardware parameters: MacBook Pro (13-inch, M1, 2020),16GB memory
- OS type: OSX
- Others:
```

### Actual Behavior

The unit test failed when I run locally `go test ./...`.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/4965857/156724199-1b762ca3-2c1f-448b-82d2-c44029cb5b72.png">

### Expected Behavior

The unit test should not have any failure. 

### Steps to Reproduce

```markdown
Run `go test ./...`
```

**Comment by m-schen** [comment]
In picture, there is a crash while runing unit test. 
but I can't get important things from the log file. And I can not reproduce this issue.

please show us more information about panic. (sql or stack information) @dengn

**Comment by dengn** [comment]
It looks like this SQL is causing trouble.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/4965857/156741722-8953d99d-4fa4-4096-95c2-da4619f505da.png">

**Comment by m-schen** [comment]
I see your environment is M1 cpu. It's arm64.
We did some optimizations on amd64 by assembly code (simd) for `distinct`, and the optimization doesn't work on arm64.

you can check if your golang match your CPU model by using the `go version` command. 
I think you might install the go amd64 by mistake. @dengn

**Comment by dengn** [comment]
Yes, my golang version seems to be amd64. Which arm64 version do you suggest to replace?

<img width="265" alt="image" src="https://user-images.githubusercontent.com/4965857/156747941-e4fb5d5f-e185-44a7-b263-18d368341fe6.png">

**Comment by m-schen** [comment]
if you are M1 MacBook, you need to download the `go arm64`. 
And we suggest you install the lasted version, and may be 1.12 at least because we need `go module`

**Comment by dengn** [comment]
Replaced by go 1.17.8 darwin/arm64, and it works! No more failed unit test. Thanks!
