### ISSUE TITLE
[Bug]: after Tpcc 5000 and 10000 warehouses test,  mo does not free the memory.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18148]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

3ffbb8c8d0cbf9f58036ed1a3f5a96b49dec8376

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10385335902/job/28754316944

**tke环境：**
namespace：mo-ben-nightly-3ffbb8c8d-20240814

**测试结束后，内存未释放：**
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/1dec7177-289e-414e-a28e-f36c372c8835">

**grafana内存使用：**
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-ben-nightly-3ffbb8c8d-20240814&from=1723631387000&to=1723680000000

**未释放内存时间点2024-08-15 02:36:00，对应profile**
[CN_33636534-6230-3932-3036-333634363230_goroutine_0191522c-ea19-7510-92e1-96d7179b5a03.gz](https://github.com/user-attachments/files/16622557/CN_33636534-6230-3932-3036-333634363230_goroutine_0191522c-ea19-7510-92e1-96d7179b5a03.gz)

**未释放内存时间点2024-08-14 22:53:01，对应profile**	
[CN_33636534-6230-3932-3036-333634363230_goroutine_01915160-c04b-7203-9e41-269c65960574.gz](https://github.com/user-attachments/files/16622562/CN_33636534-6230-3932-3036-333634363230_goroutine_01915160-c04b-7203-9e41-269c65960574.gz)

### Steps to Reproduce

```Markdown
trigger tpcc test on tke
```

**Comment by sukki37** [comment]
config info：memoryCacheSize: 12Gi

take nightly-regression-dis-tp-cn-cns64 as example:
rss is around 23G: https://grafana.ci.matrixorigin.cn/goto/zhrBGhCSR?orgId=1
in-use heap takes around 7G: https://grafana.ci.matrixorigin.cn/goto/NnoLM2jSR?orgId=1

<img width="1415" alt="image" src="https://github.com/user-attachments/assets/bb4b9b4a-96f5-4a29-8092-559eb5896f2b">

**Comment by XuPeng-SH** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22G0m%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%3D%5C%22nightly-regression-dis-tp-cn-cns64%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221723675620000%22,%22to%22:%221723675625000%22%7D%7D%7D&schemaVersion=1&orgId=1

The metadata cache size is 2G. Looking at any time slice of the heap memory, the size of the metadata is between 2g-3g, the reason for the fluctuation would be that it's being used and hasn't had time to be released, but there's no memory leak here

<img width="1786" alt="image" src="https://github.com/user-attachments/assets/fbcfceed-5a2a-4c80-9e9c-5b8619a50de0">

**Comment by XuPeng-SH** [comment]
***2024-08-14 22:45:17-2024-08-14 22:47:17***

> Heap Allocation:

<img width="1766" alt="image" src="https://github.com/user-attachments/assets/1590ffff-4718-4747-a791-0cf858c98763">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22G0m%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%3D%5C%22nightly-regression-dis-tp-cn-cns64%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:alloc_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221723675517000%22,%22to%22:%221723675638000%22%7D%7D%7D&schemaVersion=1&orgId=1

> GC log

Start: 6147M
End: 6150M
Active: 3967M
Global: 11906M

RSS ~ Heap Global(11.9G) + Memory Cache (12G)

<img width="1602" alt="image" src="https://github.com/user-attachments/assets/249f5cd6-5086-4d42-b938-db3df2c68a69">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22-Xe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-ben-nightly-3ffbb8c8d-20240814%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-cns64%5C%22%7D%20%7C~%20%60gc%20.%2Aglobal%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723675500000%22,%22to%22:%221723675680000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by Ariznawlll** [comment]
job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10412395772/job/28838521171

tke环境：mo-ben-nightly-3ffbb8c8d-20240816

grafana 内存使用：
https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-ben-nightly-3ffbb8c8d-20240816&from=1723776061000&to=1723786162000

2024-08-16 13:49:28时间点对应heap
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_01915482-4290-7ad0-8b54-9745eb421682 (1).gz](https://github.com/user-attachments/files/16633518/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_01915482-4290-7ad0-8b54-9745eb421682.1.gz)

2024-08-16 13:53:28时间点对应heap
[CN_37336664-3637-6636-3237-303433343933_heap_019159bf-821b-7795-b53b-5e8aa16289fa (1).gz](https://github.com/user-attachments/files/16633530/CN_37336664-3637-6636-3237-303433343933_heap_019159bf-821b-7795-b53b-5e8aa16289fa.1.gz)

**Comment by reusee** [comment]
go map的内存是 52.4G：https://grafana.ci.matrixorigin.cn/d/c94fd2f4-b3b5-401f-b3d3-f998584c097a/go-runtime-metrics?orgId=1&var-interval=1m&var-namespace=mo-ben-nightly-3ffbb8c8d-20240814&var-pod=nightly-regression-dis-tp-cn-cns64&from=1723684200000&to=1723687800000&viewPanel=179

go release的内存是 42.7G：https://grafana.ci.matrixorigin.cn/d/c94fd2f4-b3b5-401f-b3d3-f998584c097a/go-runtime-metrics?orgId=1&var-interval=1m&var-namespace=mo-ben-nightly-3ffbb8c8d-20240814&var-pod=nightly-regression-dis-tp-cn-cns64&from=1723684200000&to=1723687800000&viewPanel=168

相减得到 9.7G，这部分是 rss 中，go占用的部分

堆外分配的内存是 12.9G：https://grafana.ci.matrixorigin.cn/d/bde9827b-b1ae-4e75-a23a-1cec245a57a7/memory-metrics?orgId=1&var-interval=1m&var-namespace=mo-ben-nightly-3ffbb8c8d-20240814&var-pod=nightly-regression-dis-tp-cn-cns64&from=1723684200000&to=1723687800000

堆外加上go管理的，是 9.7G + 12.9G = 22.6G，和 rss 符合。

如上，内存占用正常。

**Comment by reusee** [comment]
go对于释放的内存，不会立即返还给操作系统，所以直接用heap和缓存来计算内存期望值是不对的。

参考：https://tip.golang.org/doc/gc-guide#A_note_about_virtual_memory
