### ISSUE TITLE
[Bug]: linux 环境配置python udf 无法启动 mo

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/matrixone#18159]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/e32e2bd8-9362-43c4-aada-53686ff8e33d">

### Steps to Reproduce

```Markdown
./mo-service -launch ./etc/launch-with-python-udf-server/launch.toml
```

**Comment by aylei** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/18185

**Comment by heni02** [comment]
confirm,closed
commit:80509e68b5130621f62ce10c1f9c72904f9d4591
<img width="1126" alt="企业微信截图_2d99c274-a984-42d5-a86b-07eb9ee9e661" src="https://github.com/user-attachments/assets/3fdfe569-a519-4dca-8347-c0bf24828bed">
<img width="822" alt="企业微信截图_a7325d58-8294-431d-9ead-30a068f4a1b0" src="https://github.com/user-attachments/assets/db23d17d-0b7a-497a-8d4f-534b9b7001b2">
