### ISSUE TITLE
[Tech Request]: do not let load data infile allways write s3

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#18175]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
现在当compile的时候，只要LoadTag=true都是走写S3的逻辑。
现在logger很多都是load data inline. 而且很多时候也到不了8000行，直接走insert就可以了。
看这部分逻辑能否优化
```

### Why is this needed ?

提升性能

**Comment by huby2358** [comment]
已处理
