### ISSUE TITLE
[Tech Request]: add all s3 logs to WAL 

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#18180]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
currently, not all s3 operations, such as checkpoint, logged into WAL. We should log all s3 operations to WAL to support cluster sync from active to standby.
```

**Comment by volgariver6** [comment]
@LeftHandCold please help with this issue

**Comment by LeftHandCold** [comment]
done

**Comment by volgariver6** [comment]
done
