### ISSUE TITLE
[Bug]: ci func_wasm timeout

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#18192]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

0814-debug-3895

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:


https://github.com/matrixorigin/matrixone/actions/runs/10428781554/job/28885369692?pr=18189
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/b5dff01a-5681-48fa-a820-3ec1393b6bd7)

### Expected Behavior

no timeout

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10428781554/job/28885369692?pr=18189
```

**Comment by sukki37** [comment]
GitHub Runner Network Issue
