### ISSUE TITLE
[Feature Request]: Mathematical Built-in function pi()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1821]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Returns the Float64 value of π (pi).
```
mysql> SELECT PI();
        -> 3.141593
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by ajian2002** [comment]
Hi, I'm halfway through this feature, but I'm also having some issues
In the /pkg/builtin/multi/pi.go file, what should I do with the vector so that it doesn't take arguments?

Part of my code is as follows
```go
overload.AppendFunctionRets(builtin.Pi, []types.T{}, types.T_float64)
	overload.UnaryOps[builtin.Pi] = []*overload.UnaryOp{
		{
			//Typ:        types.T_any,
			ReturnType: types.T_float64,
			Fn: func(origVec *vector.Vector, proc *process.Process, _ bool) (*vector.Vector, error) {
				vec := vector.New(types.Type{Oid: types.T_float64, Size: 8})
				vec.Data = Float64ToBytes(math.Pi)
				nulls.Set(vec.Nsp, origVec.Nsp)
				vector.SetCol(vec, pi.GetPi)
				return vec, nil

			},
		},
	}
```

**Comment by dengn** [comment]
Already implemented. Thanks @ajian2002
