### ISSUE TITLE
[Bug]: Cannot login after creating account

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#18214]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.2-17faaec0d-2024-08-18

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- In cloud dev env, login with dump, and create an account manually
```
create account if not exists `common-user-tenant_18953252541` admin_name 'admin' identified by 'xxxx';
```
- Login
```
➜  ~ mysql -h freetier-01.cn-hangzhou.cluster.cn-dev.matrixone.tech -P6001 -ucommon-user-tenant_18953252541:admin:accountadmin -pxxxx
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1815 (HY000): Auth failed: info: access denied for account common-user-tenant_18953252541
```

### Expected Behavior

Login successfully

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by daviszhen** [comment]
与是类似的问题。 https://github.com/matrixorigin/matrixone/issues/18107

**Comment by DanielZhangQD** [comment]
Log:
https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22UrW%22:%7B%22datasource%22:%22aee71632-e6c2-4299-906a-cc73bb62fd3b%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixone_cloud_component%3D%5C%22proxy%5C%22%7D%20%7C%3D%20%60common-user-tenant%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22aee71632-e6c2-4299-906a-cc73bb62fd3b%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by DanielZhangQD** [comment]
Root cause:
In the cloud env, the proxy plugin will check the cluster CR first for the account, since the account is created manually instead of created in MO Cloud, so no cluster CR would be found, in which case, the login will be blocked.

```
{"level":"error","ts":"2024-08-19T01:18:25Z","caller":"handler/handler.go:116","msg":"get tenant cluster failed","error":"internal error: cluster not found for tenant common-user-tenant_18953252541","stacktrace":"github.com/matrixone-cloud/plugin/pkg/handler.(*Handler).handle\n\t/workspace/pkg/handler/handler.go:116\ngithub.com/matrixone-cloud/plugin/pkg/handler.(*Handler).HandleRequest.func1\n\t/workspace/pkg/handler/handler.go:103"}
```

**Comment by aylei** [comment]
@DanielZhangQD PTAL

**Comment by DanielZhangQD** [comment]
Verified and passed in cloud dev
