### ISSUE TITLE
[Bug]: [0819] 128-regression: bvt 'select count(1) >= 0 as checked from system.sql_statement_hotspot' panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18219]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b56e3111a518d009630a7659645735bf992f744d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10441395206/job/28912478713 (Build Verification test)

2024-08-19 04:03:48 ERROR Executor:269 - [/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/test/distributed/cases/log/query_sql_statement_hotspot.sql][row:10][select count(1) >= 0 as checked from system.sql_statement_hotspot;] was executed failed, con[id=0, user=dump, ***
2024-08-19 04:03:48 ERROR Executor:271 - [EXPECT RESULT]:
checked
true
2024-08-19 04:03:48 ERROR Executor:272 - [ACTUAL RESULT]:
internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/panic.go:261
runtime.sigpanic
	/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/signal_unix.go:881
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetNulls
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:198
github.com/matrixorigin/matrixone/pkg/compare.(*compare[...]).Set
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/compare/compare.go:296
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergetop.(*container).sort
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergetop/top.go:249
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergetop.(*container).eval
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergetop/top.go:225
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergetop.(*MergeTop).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergetop/top.go:106
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:67
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*container).processGroupByAndAgg
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/group/group.go:172
github.com/matrixorigin/matrixone/pkg/sql/colexec/group.(*Group).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/group/group.go:146
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:67
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/projection/projection.go:67
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.(*Output).Call
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/output/output.go:48
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:91
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:78
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:331
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:317
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func2
	/data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:476
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/runtime/asm_amd64.s:1695

log: [mo-service-b56e311-20240818-222815.log.zip](https://github.com/user-attachments/files/16655339/mo-service-b56e311-20240818-222815.log.zip)

### Steps to Reproduce

```Markdown
trigger 128 regression
```

**Comment by jensenojs** [comment]
看着是vector的double free, 迟点我跟一下

**Comment by jensenojs** [comment]
not process

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
****

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
观察一下还没有复现

**Comment by Ariznawlll** [comment]
近期未出现，先关闭
