### ISSUE TITLE
[Feature Request]: refactor restore foreign key table

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#18218]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

refactor restore foreign key table

**Comment by YANGGMM** [comment]
5.  恢复从表时，主表不存在，则跳过恢复从表。
6.  恢复时需要删除主表，如果从表此时存在，则跳过恢复主表（及删除主表）
7.  如果恢复的表，包含外键或被引用，则单独恢复这张表时，仅恢复这张表的数据，并不会对其关联表的数据进行相应恢复。

**Comment by YANGGMM** [comment]
plz test @Ariznawlll

**Comment by Ariznawlll** [comment]
1.2与main测试完成
