### ISSUE TITLE
[Feature Request]: Mathematical Built-in function log()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1823]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

returns the natural logarithm of X. If X is less than or equal to 0.0E0, the function returns NULL and a warning “Invalid argument for logarithm” is reported.
```
mysql> SELECT LOG(2);
        -> 0.69314718055995
mysql> SELECT LOG(-2);
        -> NULL
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by dengn** [comment]
@WenhaoKong2001 Please comment here to be assigned.

**Comment by WenhaoKong2001** [comment]
I have implemented this issue.
