### ISSUE TITLE
[Bug]: lots of "out of memory " error during stability test on distributed mode for about 50 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#18240]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

17faaec

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

during stability test on distributed mode, there were lots of error "out of memeory" for tpch, tpcc ,sysbench cases after test runing for about 50 hours

tool log:
[tpcc.tar.gz](https://github.com/user-attachments/files/16668474/tpcc.tar.gz)
[tpch.tar.gz](https://github.com/user-attachments/files/16668477/tpch.tar.gz)
[sysbench.tar.gz](https://github.com/user-attachments/files/16668520/sysbench.tar.gz)

resource Monitor dashborad link：
https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-17faaec-202408172206&from=1723901639323&to=1724124000334

mo log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%229tz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-17faaec-202408172206%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723903200000%22,%22to%22:%221724083199000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by jensenojs** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%229tz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-17faaec-202408172206%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221723903200000%22,%22to%22:%221724083199000%22%7D%7D%7D&schemaVersion=1&orgId=1

这个链接给出的时间段是`2024-08-17 22:00:00 - 2024-08-19 23:59:59`, 我把这段时间的时间间隔切开搜索`of memory`没有搜到结果, 辛苦动哥改一下链接?

**Comment by jensenojs** [comment]
跟动哥确认了在grafana中确实搜不到`out of memory`的日志, 但与此同时, 客户端拿到的`3015`确实又是`oom`的编码.
<img width="1018" alt="企业微信截图_0137fd74-8901-4e10-afa6-6fe07ec806a0" src="https://github.com/user-attachments/assets/27425df1-210a-410e-84f3-e2c3db8f6d13">

这个时间段，有不少PROXY gc的错误, 可能要先辛苦刘博哥看一下. @volgariver6 

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%229tz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-17faaec-202408172206%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724076000000%22,%22to%22:%221724083199000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
向博哥请教了一下
```
{"level":"ERROR","time":"2024/08/19 15:50:39.839400 +0000","name":"proxy-service.query-client.query-client.query-client","caller":"morpc/client.go:404","msg":"gc inactive backends task stopped","uuid":"31336434-3561-6636-3766-613765356437"}
这个是rpc框架打印的日志，没有影响，这条日志在main上已经删掉
```

***

与此同时, 注意到CNSet大概在2024-08-19 20:34:00 之后就没有日志信息了. 

<img width="1278" alt="企业微信截图_23ce0efa-d764-4f0b-b8af-07e6a34ad5fd" src="https://github.com/user-attachments/assets/9166323a-f47f-41dc-99cf-39fab2173909">

在2024-08-19 22:50:00前后, 也有少量的日志信息, 不过与客户端收到的报错信息来看对不上. 日志里面也未见什么异常. (其中会发现有一条ERROR级别的`lockservice/lock_table_remote.go`的日志会大量地刷屏, 这个已经向俊洪哥请教过, 后面会简化掉, 可能和现在issue反映的问题没什么关系.)

<img width="1554" alt="image" src="https://github.com/user-attachments/assets/5b3cd47c-2262-47d8-812c-a790250c92af">

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%229tz%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-17faaec-202408172206%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724079000000%22,%22to%22:%221724082779000%22%7D%7D%7D&schemaVersion=1&orgId=1


***

我的理解现在有两个问题
1. 对应时间段没有收集到日志, 这个现象是否是预期的
2. 客户端为什么会收到`out of memory`的报错信息

**Comment by volgariver6** [comment]
cn的日志都丢了，无法定位问题

**Comment by aressu1985** [comment]
repro on 8.23

mo-log:
[cn_crach_oom.tar.gz](https://github.com/user-attachments/files/16729215/cn_crach_oom.tar.gz)

**Comment by jensenojs** [comment]
```

{"level":"ERROR","time":"2024/08/22 16:32:46.949642 +0000","caller":"v2@v2.0.0-20240611082008-a4de209fff3d/application.go:357","msg":"handle session failed","listen-addresses":"[0.0.0.0:6001,/tmp/mysql.sock]","error":"writeto tcp4 10.10.6.140:6001->10.10.4.39:54340: error: out of memory"}
{"level":"INFO","time":"2024/08/22 16:32:46.949703 +0000","caller":"plan/stats.go:1053","msg":"calc scan stats for table sbtest9"}
{"level":"INFO","time":"2024/08/22 16:32:46.949974 +0000","caller":"plan/stats.go:1053","msg":"calc scan stats for table sbtest3"}
{"level":"INFO","time":"2024/08/22 16:32:46.950173 +0000","caller":"plan/stats.go:1053","msg":"calc scan stats for table sbtest8"}
{"level":"INFO","time":"2024/08/22 16:32:46.950348 +0000","caller":"plan/stats.go:1053","msg":"calc scan stats for table sbtest1"}
{"level":"INFO","time":"2024/08/22 16:32:46.950481 +0000","caller":"plan/stats.go:1053","msg":"calc scan stats for table sbtest8"}
{"level":"ERROR","time":"2024/08/22 16:32:46.950511 +0000","caller":"mpool/mpool.go:578","msg":"error: error: out of memory"}
panic: allocate buffer failed. err:error: out of memory

goroutine 1244 gp=0xc0117b4700 m=4 mp=0xc0001cf808 [running]:
panic({0x5d185c0?, 0xc0c7d90700?})
	/usr/local/go/src/runtime/panic.go:779 +0x15d fp=0xc46a7079b0 sp=0xc46a707900 pc=0x44bffd
github.com/fagongzi/goetty/v2/buf.NewByteBuf(0x400, {0xc28a94bb58, 0x2, 0x2})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/buf/buf.go:105 +0x37e fp=0xc46a707af8 sp=0xc46a7079b0 pc=0x190ddbe
github.com/fagongzi/goetty/v2.(*baseIO).initConn(0xc32aa02800)
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/session.go:533 +0x345 fp=0xc46a707c18 sp=0xc46a707af8 pc=0x191ca45
github.com/fagongzi/goetty/v2.NewIOSession({0xc36426e280, 0x7, 0x8})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/session.go:238 +0x27d fp=0xc46a707cd8 sp=0xc46a707c18 pc=0x191a49d
github.com/fagongzi/goetty/v2.(*server).doStart.func2({0x6f30740, 0xc0116975a0})
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:336 +0x593 fp=0xc46a707fa8 sp=0xc46a707cd8 pc=0x1915b73
github.com/fagongzi/goetty/v2.(*server).doStart.gowrap1()
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:365 +0x3c fp=0xc46a707fe0 sp=0xc46a707fa8 pc=0x19155bc
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc46a707fe8 sp=0xc46a707fe0 pc=0x488d81
created by github.com/fagongzi/goetty/v2.(*server).doStart in goroutine 834
	/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:365 +0x2a5

goroutine 1 gp=0xc0000081c0 m=nil [select, 3057 minutes]:
runtime.gopark(0x6841090, 0x0, 0x9, 0x3, 0x1)
	/usr/local/go/src/runtime/proc.go:402 +0xfc fp=0xc013b319b0 sp=0xc013b31980 pc=0x44f97c
runtime.selectgo(0xc013b31c40, 0xc00359fb38, 0x2?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0xa07 fp=0xc013b31af8 sp=0xc013b319b0 pc=0x461e07
main.waitSignalToStop(0xc00074c000, 0xc0001fc5a0)
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:140 +0x23d fp=0xc013b31d10 sp=0xc013b31af8 pc=0x555e25d
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:129 +0x368 fp=0xc013b31f78 sp=0xc013b31d10 pc=0x555dd48
runtime.main()
	/usr/local/go/src/runtime/proc.go:271 +0x252 fp=0xc013b31fe0 sp=0xc013b31f78 pc=0x44f4f2
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc013b31fe8 sp=0xc013b31fe0 pc=0x488d81

goroutine 2 gp=0xc000008c40 m=nil [force gc (idle), 3057 minutes]:
runtime.gopark(0x6841020, 0x95099f0, 0x11, 0xa, 0x1)
	/usr/local/go/src/runtime/proc.go:402 +0xfc fp=0xc0001c8f80 sp=0xc0001c8f50 pc=0x44f97c
runtime.goparkunlock(0x95099f0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:408 +0x25 fp=0xc0001c8fb0 sp=0xc0001c8f80 pc=0x44fa05
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:326 +0xb5 fp=0xc0001c8fe0 sp=0xc0001c8fb0 pc=0x44f795
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0001c8fe8 sp=0xc0001c8fe0 pc=0x488d81
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:314 +0x1a
```

**Comment by jensenojs** [comment]
mpool在Alloc的时候会做两个检查

1. 如果大于全局的阈值设置, 则oom, 也就是这个issue的问题
2. 如果大于该mpool设置的cap, 不会oom, 但会Alloc失败

```go
	tempSize := int64(requiredSpaceWithoutHeader + kMemHdrSz)
	gcurr := globalStats.RecordAlloc("global", tempSize)
	if gcurr > GlobalCap() {
		globalStats.RecordFree("global", tempSize)
		return nil, moerr.NewOOMNoCtx()
	}
	mycurr := mp.stats.RecordAlloc(mp.tag, tempSize)
	if mycurr > mp.Cap() {
		mp.stats.RecordFree(mp.tag, tempSize)
		globalStats.RecordFree("global", tempSize)
		return nil, moerr.NewInternalErrorNoCtx("mpool out of space, alloc %d bytes, cap %d", sz, mp.cap)
	}
```

这个issue的表象是fail在了第一道检查上, 而`defaultMemoryLimit`的默认大小是`1 << 40`, 有趣的是我们的第二道检查, 在`17faaec0d`上, 只有`reuse`使用的`mpool`的Cap设置为了MB, 前端有几个用上下面设置作为Cap的大小是顶着`defaultMemoryLimit`走的, 这应该是不合理的. 这样的mpool有三个左右, 用在`Session`, `SessionAllocator`之类的地方 

```go
	//guest mmu limitation. default: 1 << 40 = 1099511627776
	GuestMmuLimitation int64 `toml:"guestMmuLimitation"`

	//mempool maxsize. default: 1 << 40 = 1099511627776
	MempoolMaxSize int64 `toml:"mempoolMaxSize"`
```

剩下的mpool在NewMPool的时候**全部**没有指定`cap`的大小, 这样带来的后果是它们默认自带的`Cap`是PB级别的. 
```go
func (mp *MPool) Cap() int64 {
	if mp.cap == 0 {
		return PB
	}
	return mp.cap
}
```

而PB是远远大于`globalLimit`的
```python
>>> globalLimit = 1 << 40
>>> B = 1
>>> KB = 1024
>>> MB = 1024 * KB
>>> GB = 1024 * MB
>>> TB = 1024 * GB
>>> PB = 1024 * TB
>>> PB
1125899906842624
>>> globalLimit
1099511627776
>>>
```

这样, 不仅使得`globalLimit`形同虚设, 也会导致本issue的问题. 在1.2-dev上我认为是存在mpool的问题的, 要么就是miss Free, 要么就是mpool的stats统计根本不对.

**Comment by aressu1985** [comment]
testing ,and  need more test

**Comment by aressu1985** [comment]
fixed
