### ISSUE TITLE
[Feature Request]: Mathematical Built-in function ceil()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1826]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Returns the smallest integer value not less than X. For exact-value numeric arguments, the return value has an exact-value numeric type. For string or floating-point arguments, the return value has a floating-point type.
```
mysql> SELECT CEIL(1.23);
        -> 2
mysql> SELECT CEIL(-1.23);
        -> -1
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by yuxubinchen** [comment]
我可以做这个，可以分配给我吗

**Comment by yuxubinchen** [comment]
can i do this, can it be assigned to me

**Comment by dengn** [comment]
Feature implemented
