### ISSUE TITLE
[Feature Request]: String Built-in function right(), left()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1827]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

LEFT(str,len): Returns the leftmost len characters from the string str, or NULL if any argument is NULL.
```
mysql> SELECT LEFT('foobarbar', 5);
        -> 'fooba'
```

RIGHT(str,len): Returns the rightmost len characters from the string str, or NULL if any argument is NULL.
```
mysql> SELECT RIGHT('foobarbar', 4);
        -> 'rbar'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by RobertKwiatkowski** [comment]
Hello dengn,
I'm very new to the project but I would like to contribute. Could you please guide me a little bit how and where to do it? After such help I would be able to do other issues as well.

**Comment by dengn** [comment]
> Hello dengn, I'm very new to the project but I would like to contribute. Could you please guide me a little bit how and where to do it? After such help I would be able to do other issues as well.

Sure. Have you already checked on our [tutorial] (https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/)? It already explains about how to develop a built-in function and gives a solid example? You can just try following the steps and see if it works for you.

**Comment by RobertKwiatkowski** [comment]
Thank you for the nice description and all the sources. I tried to use the go-runewidth, however there is small problem about using odd numers. My function:
```
func limitStrFix(str string, maxLen int) string {
	if maxLen == 0 {
		return ""
	}
	
	if runewidth.StringWidth(str) > maxLen {
		return str[:maxLen] + "…"
	}

	return str
}
```
Example test:
```
		{
			name:     "Unicode chinese",
			input:    "直立した恐竜のような身体と、尻尾の先端に常に燃えている炎が特徴。",
			max:      3,
			expected: "直…",
		},
```
```

=== RUN   TestLimitStrFix/Unicode_chinese
    strlimitfix_test.go:83:
                Error Trace:    strlimitfix_test.go:83
                Error:          Not equal:
                                expected: "直…"
                                actual  : "\xe7\x9b…"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -直…
                                +��…
```
Do you have any idea how to solve truncation of the unicode?

I've tried to use: return str[:maxLen] + "…"
because using return str[:maxLen-1] + "…" is a little bit confusing. For example this test:
```
		{
			name:     "Shorter",
			input:    "Hello this is a really long string",
			max:      8,
			expected: "Hello t…",
		}
```
Is not really the way I would expect it. Since max is 8 why are we writing only 7 letters and adding "…"? I would expect to get output like:
"Hello th…". 
However I don't know if this way won't affect rest of your code?

**Comment by RobertKwiatkowski** [comment]
To be honest I haven't done it yet, sorry. Probably tomorrow I will have enough time to check out this tutorial and follow steps.

**Comment by dengn** [comment]
> To be honest I haven't done it yet, sorry. Probably tomorrow I will have enough time to check out this tutorial and follow steps.

That's completely all right. Take your time.

**Comment by dhruvpat3l** [comment]
I can also help if needed
