### ISSUE TITLE
[Bug]: unexpected communication failure occurred during tpcc test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#18270]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

59d7606

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1388" alt="image" src="https://github.com/user-attachments/assets/b32c5f1c-b7ab-4aaa-b750-8316edd404ea">

https://github.com/matrixorigin/matrixone/actions/runs/10486049460/job/29045488341

Take connection 3189 as an example, we can find connection close logs in the proxy's runtime logs, however, it should not be closed before the tpcc test finishes.
<img width="1845" alt="image" src="https://github.com/user-attachments/assets/e3d20026-6f1d-4421-8e7e-0449544e173e">

https://grafana.ci.matrixorigin.cn/goto/kaxperCSR?orgId=1

### Steps to Reproduce

```Markdown
merge run test
```

**Comment by volgariver6** [comment]
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/b22836c7-2bd3-4c33-a674-7f2272ba712d">

https://grafana.ci.matrixorigin.cn/goto/5p27RjjIg?orgId=1

connection 3189 的执行超过了1分钟超时了，所以失败了

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/10507195799

**Comment by ouyuanning** [comment]
还没看

**Comment by ouyuanning** [comment]
还没看

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未投入

**Comment by iamlinjunhong** [comment]
未投入

**Comment by iamlinjunhong** [comment]
未投入

**Comment by iamlinjunhong** [comment]
未投入

**Comment by iamlinjunhong** [comment]
在看

**Comment by sukki37** [comment]
tracked by #18723
