### ISSUE TITLE
[Feature Request]: String Built-in function upper() and lower()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1828]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Lower(str)
Returns the string str with all characters changed to lowercase according to the current character set mapping. 
```
mysql> SELECT LOWER('QUADRATICALLY');
        -> 'quadratically'
```
Upper(str)
Returns the string str with all characters changed to uppercase according to the current character set mapping.
```
mysql> SELECT UPPER('Hej');
        -> 'HEJ'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by WenhaoKong2001** [comment]
I could try this.

**Comment by WenhaoKong2001** [comment]
I am confused with the bytes struct in _types/types.go_.
```go
type Bytes struct {
	Data    []byte
	Offsets []uint32
	Lengths []uint32
}
```
In general, length would be an uint64. And I can't determine the meaning of Offsets.
In my own understanding, the Bytes struct contains multiple strings. Lengths represent the length of each string, and offsets represent the offset of each string in data.Is this right?

**Comment by broccoliSpicy** [comment]
Your understanding for this Bytes struct is precisely right.
```go
type Bytes struct {
	Data    []byte
	Offsets []uint32
	Lengths []uint32
}
```
suppose we have this table in MatrixOne:
```sql
mysql> select * from names;
+---------+
| name    |
+---------+
| Nobi    |
| Shizuka |
| Takeshi |
+---------+
3 rows in set (0.03 sec)

```
We store each column data in a Vector struct:

```go
type Vector struct {
	Or   bool   // true: origin
	Ref  uint64 // reference count
	Link uint64 // link count
	Data []byte // raw data
	Typ  types.Type
	Col  interface{}  
	Nsp  *nulls.Nulls // nulls list
}
```

For this particular column "name", when we use it in MatrixOne's computation layer, we type assert the interface  Vector.Col to be a *types.Bytes, which points to a types.Bytes like this:
```go
Bytes {
	Data    []byte("NobiShizukaTakeshi")
	Offsets []uint32{0, 4, 11},
	Lengths []uint32{4, 7, 7}
}
```

**Comment by broccoliSpicy** [comment]
As for the Get function:
```go
// proc: the process for this query, size: the memory allocation size  we are asking, type: the new Vector's type. 
func Get(proc *Process, size int64, typ types.Type) (*vector.Vector, error) 
```

we assign each query a process, during the computation of a query we may need to allocate more memory for it and we do it using this Get function.

**Comment by WenhaoKong2001** [comment]
> 

What is stored in Victor's Data field?

**Comment by broccoliSpicy** [comment]
I think the Vector's Data field is for the storage of the Vector's Col, but I am unfamiliar with MatrixOne's storage layer now

**Comment by dengn** [comment]
> What is stored in Victor's Data field?

maybe @zzl200012 can help with this.

**Comment by broccoliSpicy** [comment]
> Do I need to consider character encoding when implementing this function? Or simply assume that they are ASCII characters?

Well, you could, and the Golang standard library has some neat functions for dealing with various character set,[unicode package](https://pkg.go.dev/unicode), I think using utf8.DecodeRune() to decode byte slices to a rune then using unicode.ToUpper/unicode.ToLower could do the job, but there are probably a better way.

note that if you care only about ASCII character set, the performance of your function would be much faster than the omnipotent one that can Upper/Lower all character sets.
