### ISSUE TITLE
[Bug]: after restore, execute sql 'set global sql_mode=' report "Duplicate entry '10007' for key 'configuration_id'".

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18285]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

80509e68b5130621f62ce10c1f9c72904f9d4591

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10503536372/job/29099494835

<img width="1852" alt="image" src="https://github.com/user-attachments/assets/4571874c-e5e6-4716-854c-f8c696be401c">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22chk%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-test-20240822%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%20%2710007%27%20for%20key%20%27configuration_id%27%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724316398000%22,%22to%22:%221724316518000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger snapshot backup restore test on tke.

数据量72G
```

**Comment by YANGGMM** [comment]
{"level":"ERROR","time":"2024/08/22 08:46:38.654501 +0000","name":"cn-service","caller":"frontend/util.go:514","msg":"query trace status","service":"30353036-6664-3335-3334-613961636466","uuid":"30353036-6664-3335-3334-613961636466","statement":"set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'","status":"fail","error":"Duplicate entry '10007' for key 'configuration_id'","txn_info":"a309e7faf4b74e4417edfd726515a86a:1724316398650069860-1","session_info":"connectionId 4636||account acc03:test_account|goRoutineId 0|migrate-goRoutineId 0|01917944-3430-7d41-ad7a-aeb203dcf66c","role":"accountadmin","session_id":"01917944-3430-7d41-ad7a-aeb203dcf66c","statement_id":"01917944-343c-75b2-b30a-4bf16c846808","span":{"trace_id":"114ef0c3-0e19-d0c5-76b9-b23650a1e7f2","span_id":"664dfce7f8f91247"}}

{"level":"ERROR","time":"2024/08/22 08:46:38.653956 +0000","caller":"fuzzyfilter/types.go:149","msg":"error: Duplicate entry '10007' for key 'configuration_id'","span":{"trace_id":"114ef0c3-0e19-d0c5-76b9-b23650a1e7f2","span_id":"664dfce7f8f91247"}}

**Comment by YANGGMM** [comment]
restore acc02 to acc03
acc02
<img width="1360" alt="企业微信截图_cffcdc7c-8907-4c79-be3f-2e023d7d6bd5" src="https://github.com/user-attachments/assets/132b126d-ab35-4231-bf6f-583f336257d4">

恢复后
acc03
<img width="1216" alt="企业微信截图_130d2168-04e0-454c-ad4d-f14612fb929b" src="https://github.com/user-attachments/assets/167f5d60-a309-4450-ad7e-2883171fb000">


恢复的数据没有问题

**Comment by jensenojs** [comment]
报错主键重复的表的DDL, 以及相关的DML如下所示. 
```
	insertSystemVariableWithAccountFormat = `insert into mo_catalog.mo_mysql_compatibility_mode(account_id, account_name, variable_name, variable_value, system_variables) values (%d, "%s", "%s", "%s", %v);`

	updateSystemVariableValueFormat = `update mo_catalog.mo_mysql_compatibility_mode set variable_value = '%s' where account_id = %d and variable_name = '%s' and system_variables = true;`

	updateConfigurationByDbNameAndAccountNameFormat = `update mo_catalog.mo_mysql_compatibility_mode set variable_value = '%s' where account_name = '%s' and dat_name = '%s' and variable_name = '%s';`

	updateConfigurationByAccountNameFormat = `update mo_catalog.mo_mysql_compatibility_mode set variable_value = '%s' where account_name = '%s' and variable_name = '%s';`

	MoCatalogMoMysqlCompatibilityModeDDL = `create table mo_catalog.mo_mysql_compatibility_mode (
				configuration_id int auto_increment,
				account_id int,
				account_name varchar(300),
				dat_name     varchar(5000) default NULL,
				variable_name  varchar(300),
				variable_value varchar(5000),
				system_variables bool,
				primary key(configuration_id)
			)`

```

`configuration_id `的值是由`incrsevice`给出的, 没有手动赋值的情况(需要由一组同事再进行确认), 不应该出现Duplicate报错的情况

**Comment by Ariznawlll** [comment]
**1.2-dev commit: ff8d9acec2fb41d8cd85b9bd012d604d3bd3d74b**

**job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10518970679/job/29147550714**

<img width="983" alt="image" src="https://github.com/user-attachments/assets/bf191d64-a4ad-4482-9d08-28f89c0612fb">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gbA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-test-20240823%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724386188000%22,%22to%22:%221724386848000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
skip restore the table, plz test @Ariznawlll

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**main commit：b9ec860c1fc415af5e840502037ff3374ed350b1**

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10536913628/job/29198847982
测试通过

**Comment by Ariznawlll** [comment]
1.2-dev修复pr还未合入，待测试

**Comment by Ariznawlll** [comment]
**1.2-dev commit：54fc6a89b11542377908e264afa5fa0d4a4586d8**

job url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10553103573/job/29239535875

测试通过。
