### ISSUE TITLE
[Bug]: [0823] main tke regression: tpcc 1000-1000 report duplicate entry.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18298]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f56fce04cf10add3d792e6eddfaefb5382e1acda

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10510167905/job/29127370912

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/0ff242d4-8b1f-41dd-8c2c-c878236886c1">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gbA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-f56fce04c-20240822%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724357350000%22,%22to%22:%221724359207000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke regression.
```

**Comment by jensenojs** [comment]
<img width="1484" alt="image" src="https://github.com/user-attachments/assets/36e5b9d3-e310-4020-9f2f-64520dd00be6">

看着是存储报的duplicate, 辛苦徐鹏哥帮忙看一下分给哪位同事帮忙跟一下? @XuPeng-SH 

这个链接往上翻能翻到use of closed network connection的报错信息, 那个日志已经过时了, 可以直接忽略

**Comment by XuPeng-SH** [comment]
等tombstone分支进来后再看有没有

**Comment by triump2020** [comment]
> 等tombstone分支进来后再看有没有

@aressu1985  Pls close it  for now,  you can reopen it if it reproduce after `tomebstone pr `merging.

**Comment by XuPeng-SH** [comment]
#18389

**Comment by Ariznawlll** [comment]
<img width="620" alt="image" src="https://github.com/user-attachments/assets/3e4989f0-dfaa-48ba-90eb-49fa73ffe9c2">

先关掉，后续有问题再新提
