### ISSUE TITLE
[Feature Request]: Proxy  service send manually upgraded SQL broadcasts to all CNs 

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#18299]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

mo多cn系统启动时，如果执行手动升级语句，该语句需要转发给所有cn执行，让所有的cn参与升级schema

手动升级语句：
UPGRADE ACCOUNT ALL;

**Comment by volgariver6** [comment]
done

**Comment by qingxinhome** [comment]
After verification, this function has been implemented
