### ISSUE TITLE
[Feature Request]: DateTime Built-in function UTC_DATE()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1829]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Returns the current UTC date as a value in 'YYYY-MM-DD'  format.

```
mysql> SELECT UTC_DATE();
        -> '2003-08-14'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by dhruvpat3l** [comment]
Could you please assign this to me and @aashnik

**Comment by dengn** [comment]
Issue assigned. @dhruvpat3l  Don't hesitate to ask if you have questions.
