### ISSUE TITLE
[Bug]: [0823] main tke regression: tpcc 1000-1000 test panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18296]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f56fce04cf10add3d792e6eddfaefb5382e1acda

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10510167905/job/29127370912

2024-08-22 20:40:08 INFO  ConsistencyCheck:192 - user=dump
2024-08-22 20:40:08 ERROR ConsistencyCheck:108 - internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:881
github.com/matrixorigin/matrixone/pkg/container/vector.extend
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/tools.go:182
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).UnionBatch
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:2467
github.com/matrixorigin/matrixone/pkg/sql/colexec/minus.(*Minus).probeHashTable
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/minus/minus.go:201
github.com/matrixorigin/matrixone/pkg/sql/colexec/minus.(*Minus).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/minus/minus.go:85
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:67
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:259
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.(*Output).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/output/output.go:48
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:91
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:78
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:185
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:314
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:439
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:358
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:337
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func2
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:477
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1695
2024-08-22 20:40:08 ERROR ConsistencyCheck:109 - SQL: (Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gbA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-f56fce04c-20240822%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724359208000%22,%22to%22:%221724359508000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke regression on tke.
```

**Comment by jensenojs** [comment]
看着像
- #18219

**Comment by jensenojs** [comment]
测试prepare性能

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
no process

**Comment by jensenojs** [comment]
同上

**Comment by jensenojs** [comment]
向QA确认一下短期又没有再复现

**Comment by aressu1985** [comment]
问题先关闭，等复现在重新提
