### ISSUE TITLE
[Feature Request]: DateTime Built-in function now()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1830]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Function syntax

**NOW()**
Returns the current date and time as a value in 'YYYY-MM-DD hh:mm:ss'.

``` sql
mysql> SELECT NOW();
        -> '2007-12-15 23:50:26'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by ikenchina** [comment]
Can you assign this task to me?

**Comment by dengn** [comment]
> Can you assign this task to me?

@ikenchina Hi, issue assigned as asked. We've also updated the description of its behavior, we don't need the type conversion to integer any more.
