### ISSUE TITLE
[Bug]: 1.2 branch create vector index takes more than 4 times longer than main

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18308]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

ff8d9acec2fb41d8cd85b9bd012d604d3bd3d74b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.2 branch:
<img width="1255" alt="企业微信截图_149aa453-064a-4ae6-a96d-e1be92fec816" src="https://github.com/user-attachments/assets/b8b26793-222c-4dd3-bc66-e0a3d918889d">
<img width="728" alt="企业微信截图_4b167ca2-cfb5-4fd6-9cc3-1a416f6873fd" src="https://github.com/user-attachments/assets/3d2f1a44-3a1c-42aa-a995-30cb596ee8de">

main commit ce51a2ca52b3eb324066f0a746630962363a86a2:
<img width="1167" alt="企业微信截图_3ec0d606-4261-455f-9f86-7b2e028d3ddf" src="https://github.com/user-attachments/assets/816df101-4a02-47e7-ba2b-f3bd3c612726">

### Steps to Reproduce

```Markdown
source /data1/mo-benchmark-test/sift128_with_pk.sql(contact me) 
create index idx_500 using ivfflat on vector_index.vector_128dim(b) lists=500 op_type "vector_l2_ops";
```

**Comment by fengttt** [comment]
not a bug.

**Comment by fengttt** [comment]
1.2 vector index slower than main is not a bug.   The other way round is.
