### ISSUE TITLE
[Bug]: tpcc 100-100、100-1000 performance degradation.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18360]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dc0970fffb20153410fd67430bc29ed9467c1cc0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/9e7f1bfe-e571-4e73-a312-e40e5afab8f5">

### Steps to Reproduce

```Markdown
129 trigger tpcc 100-100、100-1000 test
```

**Comment by badboynt1** [comment]
fixed

**Comment by Ariznawlll** [comment]
**commit：8f02aee tpcc100-100恢复正常**

<img width="715" alt="image" src="https://github.com/user-attachments/assets/a4dc0da3-fbcd-4ed4-93fd-bd6f26b37ca2">

**Comment by Ariznawlll** [comment]
**tpcc 100-1000单跑性能正常：**
**commit：c880770abcc2e682702c741ef5485244c814c521**

<img width="981" alt="企业微信截图_60f6768e-ea51-40b4-80b3-00e27bfbf803" src="https://github.com/user-attachments/assets/9f88fb55-b2a6-4d03-b968-d5f0c750a31e">
