### ISSUE TITLE
[Bug]: [date 8.26]tke regression: sysbench read_only 100threads reported error out of memory

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18364]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d61a78d93

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10561737172/job/29258939382
<img width="1113" alt="企业微信截图_55c4b460-7451-449d-af5d-c722648ec78b" src="https://github.com/user-attachments/assets/a210d60a-bbcd-43dd-a7d6-893f28af8ac1">
这个报错必现，sysbench10/100/1000w read_only 100threads都有同样的错误

报错sql：
SELECT DISTINCT c FROM sbtest3 WHERE id BETWEEN ? AND ? ORDER BY c
SELECT c FROM sbtest3 WHERE id BETWEEN ? AND ?

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22OOY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-d61a78d93-20240826%5C%22%7D%20%7C%3D%20%60out%20of%20memory%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724711098302%22,%22to%22:%221724730291073%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression sysbench10/100/1000w read_only 100threads test
sysbench命令：
sysbench  --mysql-host=172.16.90.235 --mysql-port=6001 --mysql-user=dump --mysql-password=111  oltp_read_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=300 --report-interval=10  --point_selects=1 --skip-trx=on prepare
sysbench  --mysql-host=172.16.90.235 --mysql-port=6001 --mysql-user=dump --mysql--password=111 oltp_read_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=300 --report-interval=10  --point_selects=1 --skip-trx=on run
```

**Comment by heni02** [comment]
是否和#18240一样的原因，cc @jensenojs

**Comment by jensenojs** [comment]
是, 临时性的修复方案已经提到了1.2-dev上, 用这个issue来跟踪main上根因的fix

**Comment by jensenojs** [comment]
no process

**Comment by reusee** [comment]
用这个分支记录到mpool泄漏的路径：https://github.com/reusee/matrixone/tree/freevector

profile文件：
[profile.pb.gz](https://github.com/user-attachments/files/16832318/profile.pb.gz)

截图：
![Screenshot from 2024-09-02 12-46-18](https://github.com/user-attachments/assets/2a655211-900f-4ab3-9c4a-dea2b0002f98)
![Screenshot from 2024-09-02 12-45-47](https://github.com/user-attachments/assets/ea74b038-fc5b-4d47-9a7f-a8f50677a8d2)
![Screenshot from 2024-09-02 12-45-34](https://github.com/user-attachments/assets/692f3d3f-8ab5-449f-ab11-1428fb575fc1)

**Comment by reusee** [comment]
dn/disttae也有一些泄漏的路径
![Screenshot from 2024-09-02 12-50-45](https://github.com/user-attachments/assets/78d7c8c2-fd07-495c-9ef2-d0fd91586b4f)

**Comment by reusee** [comment]
![Screenshot from 2024-09-04 10-39-22](https://github.com/user-attachments/assets/d53b30b9-7482-427b-8663-63143022021a)

从分配量看，主要是上面的路径泄漏比较多

下面做二分找出哪个commit导致
