### ISSUE TITLE
[Feature Request]:  Mathematical Built-in function abs()

### ISSUE THREAD

**Issue by WenhaoKong2001** [matrixorigin/matrixone#1837]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Abs returns the absolute value of x.
```SQL
mysql> SELECT ABS(-1);
        -> 1
```

**Comment by dengn** [comment]
Welcome for your contribution.

**Comment by dengn** [comment]
Feature implemented.  Good job @WenhaoKong2001 👏👏
