### ISSUE TITLE
[Bug]: 需要帮忙确认SQL是否有优化空间，以及是否可以走索引

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#18387]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b44e7327a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
最好PROD环境现在可用
```

### Actual Behavior

SQL：
explain select * from (select account,max(collecttime) as max_collecttime from system_metrics.server_storage_usage where collecttime >= '2024-08-06 16:00:00' and collecttime < '2024-08-07 16:00:00'
                       group by account ) as t1 left join system_metrics.server_storage_usage as t2 on t1.account = t2.account
    and t1.max_collecttime = t2.collecttime and collecttime >= '2024-08-06 16:00:00' and collecttime < '2024-08-07 16:00:00';
希望能走collecttime索引，但目前未走成功。

### Steps to Reproduce

```Markdown
如上
```

**Comment by badboynt1** [comment]
not working on this

**Comment by badboynt1** [comment]
->  Table Scan on system_metrics.metric                                                                                                                                                                                                  |
|                     Analyze: timeConsumed=5481ms scan_time=[total=5380ms,min=323ms,max=549ms,dop=12] filter_time=[total=99ms,min=3ms,max=18ms,dop=12] waitTime=0ms inputRows=4225469 outputRows=804122 InputSize=303mb OutputSize=77mb MemorySize=16mb |
|                     Filter Cond: (metric.collecttime >= 2024-08-06 16:00:00.000000), (metric.metric_name = 'server_storage_usage'), (metric.collecttime < 2024-08-07 16:00:00.000000)                                                                  |
|                     Block Filter Cond: (metric.collecttime < 2024-08-07 16:00:00.000000), (metric.collecttime >= 2024-08-06 16:00:00.000000), (metric.metric_name = 'server_storage_usage')  

这张表全表大约4亿行，下推到zonemap过滤后，需要读出400万行， 再行过滤后仍有80万行。  80万行是肯定不能走索引的

这条query后面还有一些优化空间，但是不太大了。 热数据的话，一秒内都差不多算是预期以内

**Comment by badboynt1** [comment]
在主分支上优化了一下，让这条query可以走runtime filter，预计能稍快一些

**Comment by xiaoshuwei** [comment]
@badboynt1 意思是不走索引是正常现象吗
