### ISSUE TITLE
[Feature Request]: Support re-bind locktable API for lockservice

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18385]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
If a CN accidentally panic, the old LockTableBind that holds the CN counterpart will only be discovered when the lock operation is performed.
```

### Describe the feature you'd like

Support API to trigger re-bind lockTable. And Operator can found panic cn and trigger rebind immediately

**Comment by iamlinjunhong** [comment]
retry lock can fix this problem
https://github.com/matrixorigin/matrixone/pull/18611
