### ISSUE TITLE
[Bug]: create vector index performance slow more than 10 times

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18391]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dadbdfda0e8631938aaabbe11b19c9182481ba45

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

创建vector索引比之前慢10倍以上，二分结果#18362开始变慢 cc @badboynt1 
<img width="1226" alt="企业微信截图_97a5f8b0-1aca-49ba-8c43-f5dd3a73f19d" src="https://github.com/user-attachments/assets/58c9317a-cfbb-44d3-b08f-ab02d83d2be2">

### Steps to Reproduce

```Markdown
sql:
create database if not exists vector_index;use vector_index;create table vector_128dim(a int primary key, b vecf32(128));
source /data1/mo-benchmark-test/sift128_with_pk.sql (source文件联系我)
SET experimental_ivf_index = 1;
create index idx_500 using ivfflat on vector_index.vector_128dim(b) lists=500 op_type "vector_l2_ops";
```

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
最新commit回归后观察下数据

**Comment by heni02** [comment]
confirm,closed
commit:48304fdb79f5d6486706f9a4cc965b83781c9c01
<img width="1083" alt="企业微信截图_00c0f891-8b53-4b06-8356-af98b6cde24c" src="https://github.com/user-attachments/assets/65855ae1-aa5e-4ad2-9615-bcca32baabb6">
<img width="1071" alt="企业微信截图_a39d34d4-c43a-4ee0-913d-850ce27e999f" src="https://github.com/user-attachments/assets/924dc7e2-902e-44d7-b0bb-0ab53e1a74be">
