### ISSUE TITLE
[Bug]: [date 8.27]1.2-dev tke regression: sysbench10w read_write 1000threads  reported Duplicate entry error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18400]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2

### Commit ID

968c8f7d6

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10579993708/job/29334436462
<img width="1034" alt="企业微信截图_14eee571-1b06-4b0d-9719-af17d17260b4" src="https://github.com/user-attachments/assets/f860471b-fc75-4f56-801e-8b75dabf952f">

mo log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22xGy%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-968c8f7d6-20240827%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221724794063211%22,%22to%22:%221724807756796%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke sysbench regression
```

**Comment by triump2020** [comment]
Add log ： https://github.com/triump2020/matrixone/tree/test-dup-base-1.2-dev

**Comment by XuPeng-SH** [comment]
@aptend

**Comment by aptend** [comment]
Despite attempts to reduce the flush interval and utilize Gaussian and Pareto distributions in Sysbench, reproducing the issue remains unsuccessful.

**Comment by heni02** [comment]
罗飞分支加log测试后write_only复现了： cc @triump2020 
job:https://github.com/matrixorigin/mo-auto-test/actions/runs/10785439767/job/29914598341
![image](https://github.com/user-attachments/assets/43cab949-03da-4ddc-90d1-395caf9ca5f4)


mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22qFM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-search-nightly-68a447b55-20240910%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%20%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725934285333%22,%22to%22:%221725955885333%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by triump2020** [comment]
Wait for #17388 merging.

**Comment by triump2020** [comment]
Wait for https://github.com/matrixorigin/matrixone/pull/17388 merging.

**Comment by triump2020** [comment]
Wait for https://github.com/matrixorigin/matrixone/pull/17388 merging.

**Comment by triump2020** [comment]
Wait for https://github.com/matrixorigin/matrixone/pull/17388 merging.

**Comment by triump2020** [comment]
Wait for https://github.com/matrixorigin/matrixone/pull/17388 merging.

**Comment by triump2020** [comment]
Pls ref to : https://github.com/matrixorigin/matrixone/issues/18975

**Comment by triump2020** [comment]
Pls ref to : https://github.com/matrixorigin/matrixone/issues/18975

**Comment by triump2020** [comment]
Wait for https://github.com/matrixorigin/matrixone/pull/17388 merging.

**Comment by triump2020** [comment]
Wait for https://github.com/matrixorigin/matrixone/pull/17388 merging.

**Comment by triump2020** [comment]
Wait for @ouyuanning ’s PR

**Comment by triump2020** [comment]
Wait for @ouyuanning ’s PR

**Comment by aressu1985** [comment]
update on 11.09
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11743962543/job/32732065024

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731094493127%22,%22to%22:%221731105305113%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by triump2020** [comment]
@ouyuanning 's pr had been merged , keep testing and observing.

**Comment by triump2020** [comment]
No progress on it yet.

**Comment by triump2020** [comment]
@heni02   Pls  close it .

**Comment by heni02** [comment]
最新main和2.0-dev已加解决，相关issue#19628
confirm，closed
