### ISSUE TITLE
[Bug]: TN panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#18412]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TN panic

### Steps to Reproduce

```Markdown
ci Compatibility test
```

**Comment by zhangxu19830126** [comment]
2024/08/30 03:13:12.830728 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1660 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc005cbe030?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0037e8db2?, 0xc003649170?, 0xc00cf45d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00f0a8a20, 0x2a}, {0x7f33e0c2d678, 0xc018cc25e8}, 0xc003649110, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc01177e0a0, {0x54e5438, 0x812a480}, 0xc003649110, 0xc00cf45f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc0035a8300)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

2024/08/30 03:13:12.830729 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1665 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc006d56018?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0035e47b2?, 0xc00362d6e0?, 0xc015ca3d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00f0a89f0, 0x2a}, {0x7f33e0c2d678, 0xc0117446f0}, 0xc00362d680, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc01177e050, {0x54e5438, 0x812a480}, 0xc00362d680, 0xc015ca3f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc0035a8280)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

{"level":"INFO","time":"2024/08/30 03:13:12.830749 +0000","caller":"blockio/pipeline.go:493","msg":"job is Job[LoadJob]-[0191a134-8a5e-73b5-9f82-e7755604eba3_00000-830592773]"}
2024/08/30 03:13:12.830731 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1663 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc00d118108?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0035e21b2?, 0xc003878c00?, 0xc015d21d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00f0a8a50, 0x2a}, {0x7f33e0c2d678, 0xc0117f66d8}, 0xc003878ba0, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc01177e0f0, {0x54e5438, 0x812a480}, 0xc003878ba0, 0xc015d21f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc0035a8380)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

2024/08/30 03:13:12.830928 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1661 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc006d56060?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0037e67b2?, 0xc0038ea690?, 0xc018f15d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00f0a8ab0, 0x2a}, {0x7f33e0c2d678, 0xc011744798}, 0xc0038ea630, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc01177e190, {0x54e5438, 0x812a480}, 0xc0038ea630, 0xc018f15f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc00368a080)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

2024/08/30 03:13:12.830932 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1682 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc00d1181f8?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc0037e41b2?, 0xc003986120?, 0xc009fe7d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00f0a8b40, 0x2a}, {0x7f33e0c2d678, 0xc0117f6960}, 0xc0039860c0, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc01177e1e0, {0x54e5438, 0x812a480}, 0xc0039860c0, 0xc009fe7f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc00368a100)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

{"level":"INFO","time":"2024/08/30 03:13:12.830948 +0000","caller":"blockio/pipeline.go:493","msg":"job is Job[LoadJob]-[0191a134-ad7c-77c7-90cb-991c71d85546_00000-830810460]"}
2024/08/30 03:13:12.831115 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1664 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc006d561b0?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc00369c7b2?, 0xc00398db30?, 0xc015d25d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00d3b00c0, 0x2a}, {0x7f33e0c2d678, 0xc011744870}, 0xc00398dad0, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc004530000, {0x54e5438, 0x812a480}, 0xc00398dad0, 0xc015d25f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc00368a000)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

{"level":"INFO","time":"2024/08/30 03:13:12.831129 +0000","caller":"blockio/pipeline.go:493","msg":"job is Job[LoadJob]-[0191a13e-7f39-7c6c-a0c8-3515990721aa_00000-831047405]"}
2024/08/30 03:13:12.831268 [ants]: worker exits from panic: runtime error: slice bounds out of range [4294967292:0]
goroutine 1662 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:56 +0x85
panic({0x48d8f20?, 0xc005cbe138?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:785 +0x132
github.com/matrixorigin/matrixone/pkg/objectio.BlockIndex.BlockMetaPos(...)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:106
github.com/matrixorigin/matrixone/pkg/objectio.objectDataMetaV1.GetBlockMeta({0xc00369a1b2?, 0xc0039a55c0?, 0xc002659d78?}, 0x7f06f40?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/meta.go:68 +0x12f
github.com/matrixorigin/matrixone/pkg/objectio.ReadMultiBlocksWithMeta({0x54e5438, 0x812a480}, {0xc00a1101e0, 0x2a}, {0x7f33e0c2d678, 0xc018cc2678}, 0xc0039a5560, {0x55427c0, 0xc002158900}, 0x4e3d3f8)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/funcs.go:261 +0x245
github.com/matrixorigin/matrixone/pkg/objectio.(*objectReaderV1).ReadMultiBlocks(0xc005b1a000, {0x54e5438, 0x812a480}, 0xc0039a5560, 0xc002659f50?)
	/home/runner/work/matrixone/matrixone/head/pkg/objectio/reader.go:303 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.prefetchJob.func2({0x0?, 0x48f473?})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/blockio/pipeline.go:192 +0x76
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*Job).Run(0xc00368a180)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/tasks/job.go:122 +0xab
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 369
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

{"level":"INFO","time":"2024/08/30 03:13:12.831287 +0000","caller":"blockio/pipeline.go:493","msg":"job is Job[LoadJob]-[0191a142-dca5-7d6a-9bab-490412076f7e_00000-831222383]"}
{"level":"INFO","time":"2024/08/30 03:13:12.831511 +0000","caller":"db/open.go:79","msg":"open-tae","operation":"End","operand":"open","cost":"753.591309ms","err":null}
panic: runtime error: index out of range [0] with length 0

goroutine 462 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*CheckpointData).ReadTNMetaBatch(0xc00016cfc0, {0x54e55d8, 0xc0097520f0}, 0xc, {0xc00a0e80f0, 0x55427c0?, 0x4f}, 0xc0038774d0)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/logtail/utils.go:2237 +0x1a6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*CheckpointEntry).ReadMetaIdx(0xc00e22e000, {0x54e55d8, 0xc0097520f0}, 0xc0022239e0?, 0xc00016cfc0)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/checkpoint/entry.go:249 +0xa7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).Replay.func4(0x0, 0x24?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/checkpoint/replay.go:147 +0x299
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).Replay(0xc0001fc1e0, {0x54d9ee0, 0xc018a2e408})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/checkpoint/replay.go:181 +0x10b1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x54e55d8, 0xc0097520f0}, {0xc0035252d0, 0x70}, 0xc0021d8a00)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/db/open.go:178 +0x176c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0x54e55d8, 0xc0097520f0}, {0xc005c10a80, 0x6c}, 0xc0021d8a00)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/rpc/handle.go:90 +0x1a5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0x54e55d8?, 0xc0097520f0?}, {0xc005c10a80?, 0x32731b7?}, 0x4c3d63a?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/rpc/handle.go:110 +0x45
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0x54e55d8, 0xc0097520f0}, {0xc005c10a80, 0x6c}, 0xc0021d8a00, {{0x2, 0x1, {}, {0x0, 0x0, ...}, ...}, ...}, ...)
	/home/runner/work/matrixone/matrixone/head/pkg/txn/storage/tae/storage.go:55 +0xda
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).newTAEStorage(0xc0083b2ea0, {0x54e55d8, 0xc0097520f0}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...}, ...)
	/home/runner/work/matrixone/matrixone/head/pkg/tnservice/factory.go:203 +0x5f3
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createTxnStorage(0xc0083b2ea0, {0x54e55d8, 0xc0097520f0}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...})
	/home/runner/work/matrixone/matrixone/head/pkg/tnservice/factory.go:75 +0x2d8
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createReplica.func1({0x54e55d8, 0xc0097520f0})
	/home/runner/work/matrixone/matrixone/head/pkg/tnservice/store.go:315 +0x13c
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/home/runner/work/matrixone/matrixone/head/pkg/common/stopper/stopper.go:277 +0x5b
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 348
	/home/runner/work/matrixone/matrixone/head/pkg/common/stopper/stopper.go:272 +0xb0

**Comment by zhangxu19830126** [comment]
[mo-service.log](https://github.com/user-attachments/files/16811732/mo-service.log)

**Comment by XuPeng-SH** [comment]
#18389 不做前后commit的兼容性，之后1.2到1.3做工具兼容

**Comment by zhangxu19830126** [comment]
@sukki37 please close this issue.
