### ISSUE TITLE
[Bug]: chaos test, some tpcc error appear

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#18416]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.2.0

### Commit ID

5522522b56e583e751d345dcc6074981c98a4ef0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
  k8s cluster 3log 1cn 1dn
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/37cf400b-e4ba-4a3f-86e1-cb07932f7728)

### Steps to Reproduce

```Markdown
1、use chaos-mesh inject chaos（every 2min kill one specific log ）
2、use tpcc tool test
 The error is probability of occurrence
```

**Comment by volgariver6** [comment]
随机停掉一个log service 副本，如果停掉了leader，就会出现问题。

报错信息中的 table not exists，有相关issue，目前不好修复，可能后续版本解决：

https://github.com/matrixorigin/matrixone/issues/16966
https://github.com/matrixorigin/MO-Cloud/issues/3519
