### ISSUE TITLE
[Bug]: TPCC 100-1000 test on 129 report 'Duplicate entry '3a152d3a16af76' for key '__mo_cpkey_col''.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18413]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c880770abcc2e682702c741ef5485244c814c521

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job : https://github.com/matrixorigin/mo-auto-test/actions/runs/10626185812/job/29457442657

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/e107a9b6-9942-4c8f-bd4a-afd6fb0d8415">

log: https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-129%5C%22,%20filename%3D%5C%22%2Fdata3%2Factions-runner%2F_work%2Fmo-auto-test%2Fmo-auto-test%2Fhead%2Fmo-service-c880770-20240830-111402.log%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tpcc 100-1000 test on 129.
```

**Comment by YANGGMM** [comment]
@XuPeng-SH 麻烦看一下

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
等环境空闲

**Comment by Ariznawlll** [comment]
在128测试了一下，没出现了，先关掉

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/37acec74-60aa-4cfc-8936-93935c3d6c66">

测试通过
