### ISSUE TITLE
[Bug]: 0.001 or 0 evaluate error

### ISSUE THREAD

**Issue by SilvaXiang** [matrixorigin/matrixone#1843]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):docker latest
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t(a int);
insert into t values(1);
select 0.001 or 0 , a from t;

Result:

0.0010    1

### Expected Behavior

create table t(a int);
insert into t values(1);
select 0.001 or 0 , a from t;

Result:

1    1

### Steps to Reproduce

```markdown
create table t(a int);
insert into t values(1);
select 0.001 or 0 , a from t;
```

**Comment by m-schen** [comment]
It is a logic bug while doing prune work for AST. thanks.

**Comment by m-schen** [comment]
it will be fixed after plan refactoring.

**Comment by m-schen** [comment]
fixed it now.
