### ISSUE TITLE
[Bug]: [date 8.30]tke regression: tpcc 1000 warehouse test mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18439]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0024ffcb1eab4d2fcae1833503c39204b03a7bd3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10634489682/job/29482673943
tpcc 100warehouse测试时开始链接超时
<img width="1166" alt="企业微信截图_193f83d4-308b-4454-b922-23fb03731a71" src="https://github.com/user-attachments/assets/dc576193-325a-425d-890b-0e4418468823">
之后的测试mo开始hung住
<img width="1251" alt="企业微信截图_f78c5f3b-e144-4fb9-9a3b-2211999dd69a" src="https://github.com/user-attachments/assets/b91f0821-0fb6-4844-914e-300f302fe279">

mo log：日志中有大量long running
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22qFM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-0024ffcb1-20240830%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725047204666%22,%22to%22:%221725072546398%22%7D%7D%7D&schemaVersion=1&orgId=1

test env namespace：
[root@VM-0-124-tencentos ~]# kubectl -n mo-main-nightly-0024ffcb1-20240830 get pod
NAME                                 READY   STATUS    RESTARTS   AGE
nightly-regression-dis-dn-0          1/1     Running   0          11h
nightly-regression-dis-log-0         1/1     Running   0          11h
nightly-regression-dis-log-1         1/1     Running   0          11h
nightly-regression-dis-log-2         1/1     Running   0          11h
nightly-regression-dis-proxy-l6d5s   1/1     Running   0          11h
nightly-regression-dis-proxy-pl27j   1/1     Running   0          11h
nightly-regression-dis-tp-cn-26nk6   1/1     Running   0          11h
nightly-regression-dis-tp-cn-dnmfr   1/1     Running   0          11h
nightly-regression-dis-tp-cn-g8w8h   1/1     Running   0          11h

### Steps to Reproduce

```Markdown
tke regression tpcc test
```

**Comment by YANGGMM** [comment]
麻烦看一下 @daviszhen

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/18462  这个pr是修复root cause的

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
