### ISSUE TITLE
[Bug]: 0.1 = 0.10000000000000000000000000000000000001 evaluate error

### ISSUE THREAD

**Issue by SilvaXiang** [matrixorigin/matrixone#1844]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):docker latest
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t(a int);
insert into t values(1);
select 0.1 = 0.10000000000000000000000000000000000001, a from t;

Result : 
1 1

### Expected Behavior

create table t(a int);
insert into t values(1);
select 0.1 = 0.10000000000000000000000000000000000001, a from t;

Result : 
0 1

### Steps to Reproduce

```markdown
create table t(a int);
insert into t values(1);
select 0.1 = 0.10000000000000000000000000000000000001, a from t;
```

**Comment by m-schen** [comment]
I'm not sure if 0.10000000000000000000000000000000000001 will be convert to be 0.1 in float64 from parser ? @iamlinjunhong

**Comment by iamlinjunhong** [comment]
0.10000000000000000000000000000000000001 will be convert to be 0.1 from parser, because Numval.resFloat is the type of float64. But it will keep original value in Numval.origString. @m-schen

**Comment by broccoliSpicy** [comment]
we recognize 0.10000000000000000000000000000000000001 as a float64 number, and during the conversion from string to float64, some digits might get lost, this behavior is the same as ClickHouse

```go
asuka :) create table t(a int) engine= TinyLog();

CREATE TABLE t
(
    `a` int
)
ENGINE = TinyLog

Query id: 3563e0e5-67bf-4f6e-ac1a-5d1482d711bb

Ok.

0 rows in set. Elapsed: 0.072 sec.

asuka :) insert into t values(1);

INSERT INTO t FORMAT Values

Query id: bb86f3bb-3864-4e4f-bbb1-f8f009b5d9dd

Ok.

1 rows in set. Elapsed: 0.003 sec.

asuka :) select 0.1 = 0.10000000000000000000000000000000000001, a from t;



SELECT
    0.1 = 0.1,
    a
FROM t

Query id: 6d9cb534-ecec-4b1b-857d-0fbe73da183a

┌─equals(0.1, 0.1)─┬─a─┐
│                1 │ 1 │
└──────────────────┴───┘

1 rows in set. Elapsed: 0.003 sec.

asuka :) select 0.1 = 0.10000000000000001, a from t;

SELECT
    0.1 = 0.1,
    a
FROM t

Query id: eb60e8f1-5837-458b-ac05-3e6447ba3d1b

┌─equals(0.1, 0.1)─┬─a─┐
│                1 │ 1 │
└──────────────────┴───┘

1 rows in set. Elapsed: 0.001 sec.
asuka :) select 0.1 = 0.1000000000000001, a from t;

SELECT
    0.1 = 0.1000000000000001,
    a
FROM t

Query id: a6640c82-b639-431e-9ff1-8bfc1ac2e2d7

┌─equals(0.1, 0.1000000000000001)─┬─a─┐
│                               0 │ 1 │
└─────────────────────────────────┴───┘

1 rows in set. Elapsed: 0.001 sec.
```

I don't think we should change our original parser to recognize this string literal as something more than a float64
