### ISSUE TITLE
[Bug]: cdc should choose send full data or not by `--no-full` option

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#18444]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

0827-cdc

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cdc 没有处理

### Expected Behavior

--no-full时，不发送存量的数据

### Steps to Reproduce

```Markdown
mo_cdc task create
```

**Comment by daviszhen** [comment]
进行中

**Comment by heni02** [comment]
confirm,closed
