### ISSUE TITLE
[Bug]: Data cannot be loaded when the data header contains spaces

### ISSUE THREAD

**Issue by SilvaXiang** [matrixorigin/matrixone#1845]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):docker latest
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table table_0(primaryKey int, col_0 int, col_1 int);
load data infile '/home/table_0_0.txt' into table table_0 fields terminated by ',' lines terminated by '\r\n';

the data file is as such():

1, 3, 5
2, 4, 6

When loading 3, it stops and reports an error. 3 cannot be imported.
But isn't this kind of data with spaces in the first place very common?

### Expected Behavior

load successful

### Steps to Reproduce

```markdown
create table table_0(primaryKey int, col_0 int, col_1 int);
load data infile '/home/table_0_0.txt' into table table_0 fields terminated by ',' lines terminated by '\r\n';


the data file is as such():

1, 3, 5
2, 4, 6
```

**Comment by daviszhen** [comment]
fixed in the pr #1856
