### ISSUE TITLE
[Refactoring]: reuse ExpressionExecutor for Filter Operator

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#18454]
### Why do you want to refactor this code?

```Markdown
目前Filter算子还是每次执行使用DeepCopy表达式，然后做常量折叠的方式处理。
因为如果直接服用表达式执行器，tpcc会有10%左右性能下降。
希望在打开Compile.proc.SetBaseProcessRunningStatus(true)的情况下，直接复用 ExpressionExecutor 以便提升内存复用
```

### Describe the solution you'd like

找到tpcc性能下降的原因，复用ExpressionExecutor

**Comment by jensenojs** [comment]
性能的回退来自这个地方: 
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/4b89525e-f90e-4233-9b19-d2f49bc6474a">

main : 
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%225RM%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-10664908562%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221725271969000%22,%22to%22:%221725272357000%22%7D%7D%7D&schemaVersion=1&orgId=1


use ExpressionExecutor : 
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%225RM%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-checkin-regression-10664911642%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221725271969732%22,%22to%22:%221725272357398%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by jensenojs** [comment]
# 本地测tpcc, plan > executor

用plan.ConstantFold 比用 executor.Eval 的Fold 更快, 红框的部份是executor比plan耗时多出的部份, cpu时间多8~9秒

<img width="1653" alt="企业微信截图_b3251c6b-ce8e-4029-8ef0-25a4cb2cb5be" src="https://github.com/user-attachments/assets/22cdda65-aa8c-42cd-a3e9-e99aa4bb489f">

# filter算子中写Benchmark executor > plan

手动把表达式给构造出来去执行, executor 比 plan.ConstantFold 更严重
<img width="901" alt="Pasted Graphic 14" src="https://github.com/user-attachments/assets/27ff79db-3492-4133-a29e-031e3c46c6e4">

<img width="1584" alt="企业微信截图_186f69c5-5721-42f0-a334-31a50ac47617" src="https://github.com/user-attachments/assets/46f27c2f-0e44-4ae9-8f86-736fdcfa7487">

**Comment by jensenojs** [comment]
会产生性能下降的原因是main上的Filter把Free当Reset用了, 不过修正之后会有正确性的问题. 需要再看
