### ISSUE TITLE
[Bug]: CN GetServerStatus Panic

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#18465]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

df6cfb854931230de8c44c576000052abcdb30d1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
![image](https://github.com/user-attachments/assets/fd7f60ac-9e7a-4cf3-96f8-d3ec6d12ab95)

job:https://github.com/matrixorigin/mo-auto-test/actions/runs/10643182759/job/29506651283

### Expected Behavior

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Vbs%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-search-nightly-f5c776b99-20240831%5C%22,%20pod%3D%5C%22nightly-regression-dis-tp-cn-c24gn%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D,%22gSK%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22nightly-regression-dis-tp-cn%5C%22,apps_kruise_io_cloneset_instance_id%3D%5C%22c24gn%5C%22,container%3D%5C%22main%5C%22,controller_revision_hash%3D%5C%22nightly-regression-dis-tp-cn-865b8f7f5b%5C%22,filename%3D%5C%22%2Fvar%2Flog%2Fpods%2Fmo-search-nightly-f5c776b99-20240831_nightly-regression-dis-tp-cn-c24gn_f4257500-7ed7-4ebe-ae2e-1a7d0c858b2a%2Fmain%2F0.log%5C%22,job%3D%5C%22mo-search-nightly-f5c776b99-20240831%2Fnightly-regression-dis-tp-cn%5C%22,lifecycle_apps_kruise_io_state%3D%5C%22Normal%5C%22,matrixone_cloud_cn_uuid%3D%5C%2262323737-3065-3234-3566-363263313131%5C%22,matrixorigin_io_cluster%3D%5C%22nightly-regression-dis%5C%22,matrixorigin_io_component%3D%5C%22CNSet%5C%22,matrixorigin_io_instance%3D%5C%22nightly-regression-dis-tp%5C%22,matrixorigin_io_namespace%3D%5C%22mo-search-nightly-f5c776b99-20240831%5C%22,namespace%3D%5C%22mo-search-nightly-f5c776b99-20240831%5C%22,node_name%3D%5C%2210.128.0.191%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-c24gn%5C%22,pod_template_hash%3D%5C%22865b8f7f5b%5C%22,service_name%3D%5C%22nightly-regression-dis-tp-cn%5C%22,stream%3D%5C%22stderr%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22log-row-context-query-_0.9032606792139113%22,%22maxLines%22:1000,%22direction%22:%22backward%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%221725099373847%22,%22to%22:%221725101248882%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22log-row-context-query-_0.9032606792139113_1725101248881877018_cef61b58%22%7D%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
Run tpcc 1000-1000 on TKE
```

**Comment by CJKkkk-315** [comment]
也是DATA RACE问题

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
fixed
