### ISSUE TITLE
[Bug]: panic during bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#18487]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
{"level":"ERROR","time":"2024/09/02 16:31:55.902749 +0000","caller":"engine/entire_engine.go:58","msg":"error: internal error: temporary engine not init yet","span":{"trace_id":"af1e07dc-0a95-d435-a2c7-b1117ef97ef8","span_id":"0eea61ddee82ba68"}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x363c6d3]

goroutine 1877 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).getConnectionID(0x0?)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:153 +0x13
github.com/matrixorigin/matrixone/pkg/frontend.(*AccountRoutineManager).deleteRoutine(0xc00f35b4f0, 0x97, 0xc0dfc0ab80)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:97 +0x93
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).KillRoutineConnections(0xc0067625b0)
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:591 +0x23a
github.com/matrixorigin/matrixone/pkg/frontend.NewRoutineManager.func1()
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:645 +0x65
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutineManager in goroutine 1628
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:638 +0x22f

```

[Standalone-e2e-BVT-Test-on-Linux-x64(LAUNCH,PESSIMISTIC)-reports.zip](https://github.com/user-attachments/files/16842494/Standalone-e2e-BVT-Test-on-Linux-x64.LAUNCH.PESSIMISTIC.-reports.zip)

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by YANGGMM** [comment]
2024/09/03 15:26:47.337689 +0800 ERROR cn-service.frontend frontend/authenticate.go:4324 accountID is 0 {"uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "stack": github.com/matrixorigin/matrixone/pkg/frontend.postDropSuspendAccount\n\t/Users/yangzhao/matrixone/pkg/frontend/authenticate.go:4324\ngithub.com/matrixorigin/matrixone/pkg/frontend.doDropAccount\n\t/Users/yangzhao/matrixone/pkg/frontend/authenticate.go:4291\ngithub.com/matrixorigin/matrixone/pkg/frontend.handleDropAccount\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:1176\ngithub.com/matrixorigin/matrixone/pkg/frontend.execInFrontend\n\t/Users/yangzhao/matrixone/pkg/frontend/self_handle.go:231\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmt\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2480\ngithub.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2448\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2417\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2374\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2264\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2228\ngithub.com/matrixorigin/matrixone/pkg/frontend.doComQuery\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2826\ngithub.com/matrixorigin/matrixone/pkg/frontend.ExecRequest\n\t/Users/yangzhao/matrixone/pkg/frontend/mysql_cmd_executor.go:2901\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest\n\t/Users/yangzhao/matrixone/pkg/frontend/routine.go:291\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/Users/yangzhao/matrixone/pkg/frontend/routine_manager.go:545\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage\n\t/Users/yangzhao/matrixone/pkg/frontend/server.go:212\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/Users/yangzhao/go/pkg/mod/github.com/matrixorigin/goetty/v2@v2.0.0-20240611082008-a4de209fff3d/application.go:356

**Comment by YANGGMM** [comment]
@aressu1985  plz test

**Comment by Ariznawlll** [comment]
今天观察了一下，没出现

**Comment by Ariznawlll** [comment]
今天观察了一下，没出现
