### ISSUE TITLE
[Bug]: ut TestGetInitPort failed

### ISSUE THREAD

**Issue by Wenbin1002** [matrixorigin/matrixone#18513]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[logs_27950934264.zip](https://github.com/user-attachments/files/16861598/logs_27950934264.zip)
https://github.com/matrixorigin/matrixone/actions/runs/10694614578/job/29646666251?pr=18509

### Steps to Reproduce

```Markdown
run ut
```

**Comment by zhangxu19830126** [comment]
fixed by #18528
