### ISSUE TITLE
[Bug]: Connect failed when using `pymysql`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#1853]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 2ca5dc506a185f429adb259353b7bd279c687823
- Hardware parameters: amd64/arm64
- OS type: centos/darwin
- Others:
```

### Actual Behavior

When I want to connect MO using `pymysql`, error as follows occured:

```
Traceback (most recent call last):
  File "/Users/maomao/code/mo-analysis/python/wechat_groupchat/test.py", line 3, in <module>
    db = pymysql.connect(host='127.0.0.1',
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymysql/connections.py", line 832, in _request_authentication
    if int(self.server_version.split(".", 1)[0]) >= 5:
ValueError: invalid literal for int() with base 10: 'v0'
```

Example connection code is attached here.
```python
import pymysql

if __name__ == '__main__':
    db = pymysql.connect(host='127.0.0.1',
                         port=6001,
                         user='dump',
                         passwd='111')
    cursor = db.cursor()

    cursor.execute("show databases;")

    results = cursor.fetchall()

    print(results)
    db.close()
```

### Expected Behavior

connect successfully

### Steps to Reproduce

```markdown
1. start mo locally
2. connect to mo using the following example code
```

**Comment by daviszhen** [comment]
The cause of the error above is that the rule for encoding version is different between the MO and the Mysql. To fix the error, we should propose the encoding rule for the MO that is compatible with the mysql.

The the version of the mysql is encoded as the format '5.7.xx' or '8.0.xx'。The first number of the mysql version is always greater than and equal to the number 5.

The pymysql checks the first number of the version to ensure that the version of the mysql is 5 at least. 

But the MO defines the version as the 'v0.2.0' in its Makefile by 'git describe --abbrev=0 --tags'. The first number is 'v0' obviously. 'v0' can not be converted to the number as the error info above denotes.

**Comment by sukki37** [comment]
Have checked related source code of `pymysql` 
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/77312370/157578257-f7468c42-ed3b-4d43-aa23-ef67248aa4bc.png">

We'd change the pattern of mo version which means that we should delete non-numeric characters of the version number of mo for compatibility.

**Comment by m-schen** [comment]
fixed it. you can verify it at branch main.
