### ISSUE TITLE
[Bug]: repeat max tgt size is pure magic.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18547]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

84dbd1a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

repeat tgt max size is magic.   there is no reason that it is not the same as maxvarcharsize.

### Steps to Reproduce

```Markdown
bvt test.
```

**Comment by fengttt** [comment]
#18508

**Comment by matrix-meow** [comment]
Hello @fengttt. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by Ariznawlll** [comment]
**The result of related bvt case with tag 18547 is not consistent with mysql, please take a look on it, Thank you. @fengttt** 

**bvt case:**
```
drop table if exists repeat04;
create table repeat04(col1 float, col2 varchar(200));
insert into repeat04 values (1232.21312, 'YT^&Y*UJIJH* ( U ( HJHFDTYUIHJFYTGUHIJueiyw8uhfwjh483i2verwe4r3f2432432');
insert into repeat04 values (0.3243214, '4324213421v dsr3\\}{}{}Ew4rfebte');
insert into repeat04 values (-32.321342, '  321432fvewvegre5 g5 ');
insert into repeat04 values (null, 'jh   i w o  IIIO ejwqd');
insert into repeat04 values (0,'');
select * from repeat04;

select repeat(rpad(col2,300,'1234567890***'),col1) from repeat04;
```
**mo:**
<img width="878" alt="image" src="https://github.com/user-attachments/assets/a1df6b30-7e87-4397-910e-5f71f67e84eb">

the result of mysql is not good to show,  please to execute yourself.
