### ISSUE TITLE
[Feature Request]: Rebuild the version number of matrixone

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#1854]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
Related to https://github.com/matrixorigin/matrixone/issues/1853
```

### Describe the solution you'd like

We'd change the pattern of mo version which means that we should delete non-numeric characters of the version number of mo for compatibility.

**Comment by m-schen** [comment]
fixed it. And now version number only contains numeric and '.'

**Comment by sukki37** [comment]
it works. thx.
