### ISSUE TITLE
[Bug]: [date 9.4]tke regression: tpch 1T 4cn Q9 results incorrect

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18555]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

86dbf35af

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10703848429/job/29709297018
<img width="1511" alt="企业微信截图_da4422c2-938a-4b98-ae5e-d0c730b03720" src="https://github.com/user-attachments/assets/bd73f44b-1469-4a8e-ac8b-975ab70dfdfd">

env：
[root@VM-0-124-tencentos ~]# kubectl -n mo-main-nightly-86dbf35af-20240904 get pod
NAME                                 READY   STATUS    RESTARTS   AGE
nightly-regression-dis-dn-0          1/1     Running   0          16h
nightly-regression-dis-log-0         1/1     Running   0          16h
nightly-regression-dis-log-1         1/1     Running   0          16h
nightly-regression-dis-log-2         1/1     Running   0          16h
nightly-regression-dis-proxy-sslhq   1/1     Running   0          16h
nightly-regression-dis-proxy-z67pg   1/1     Running   0          16h
nightly-regression-dis-tp-cn-b6ph2   1/1     Running   0          16h
nightly-regression-dis-tp-cn-qlbsm   1/1     Running   0          89m
nightly-regression-dis-tp-cn-sqwcw   1/1     Running   0          16h
nightly-regression-dis-tp-cn-xxczn   1/1     Running   0          16h

q9结果不一致应该是偶现，手动登陆客户端再执行q9，返回结果和预期结果一致
mysql> select
    ->     nation,
    ->     o_year,
    ->     sum(amount) as sum_profit
    -> from
    ->     (
    ->         select
    ->             n_name as nation,
    ->             extract(year from o_orderdate) as o_year,
    ->             l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
    ->         from
    ->             part,
    ->             supplier,
    ->             lineitem,
    ->             partsupp,
    ->             orders,
    ->             nation
    ->         where
    ->             s_suppkey = l_suppkey
    ->             and ps_suppkey = l_suppkey
    ->             and ps_partkey = l_partkey
    ->             and p_partkey = l_partkey
    ->             and o_orderkey = l_orderkey
    ->             and s_nationkey = n_nationkey
    ->             and p_name like '%pink%'
    ->     ) as profit
    -> group by
    ->     nation,
    ->     o_year
    -> order by
    ->     nation,
    ->     o_year desc
    -> ;

+----------------+--------+------------------+
| nation         | o_year | sum_profit       |
+----------------+--------+------------------+
| ALGERIA        |   1998 | 27308860378.3172 |
| ALGERIA        |   1997 | 46620430046.5428 |
| ALGERIA        |   1996 | 46753748615.5549 |
| ALGERIA        |   1995 | 46663470272.4614 |
| ALGERIA        |   1994 | 46640295601.5516 |
| ALGERIA        |   1993 | 46651049609.2884 |
| ALGERIA        |   1992 | 46663923454.3312 |
| ARGENTINA      |   1998 | 27334857382.3469 |
| ARGENTINA      |   1997 | 46502923272.3845 |
| ARGENTINA      |   1996 | 46627289876.6037 |
| ARGENTINA      |   1995 | 46467707673.1049 |
| ARGENTINA      |   1994 | 46556107664.0120 |
| ARGENTINA      |   1993 | 46575939974.0570 |
| ARGENTINA      |   1992 | 46682942845.1782 |
| BRAZIL         |   1998 | 27406911648.7382 |
| BRAZIL         |   1997 | 46815247168.1900 |
| BRAZIL         |   1996 | 46816540149.0943 |
| BRAZIL         |   1995 | 46757628273.9002 |
| BRAZIL         |   1994 | 46805465749.8730 |
| BRAZIL         |   1993 | 46767592302.7412 |
| BRAZIL         |   1992 | 46939748749.3037 |
| CANADA         |   1998 | 27361371454.8604 |
| CANADA         |   1997 | 46692483289.2733 |
| CANADA         |   1996 | 46832833565.8810 |
| CANADA         |   1995 | 46723697073.8460 |
| CANADA         |   1994 | 46763917029.4786 |
| CANADA         |   1993 | 46705008389.2797 |
| CANADA         |   1992 | 46837190161.8649 |
| CHINA          |   1998 | 27421966408.2710 |
| CHINA          |   1997 | 46644560270.9761 |
| CHINA          |   1996 | 46755978869.0835 |
| CHINA          |   1995 | 46639312746.9771 |
| CHINA          |   1994 | 46658830649.3130 |
| CHINA          |   1993 | 46601979319.0262 |
| CHINA          |   1992 | 46755066782.6697 |
| EGYPT          |   1998 | 27314574056.3297 |
| EGYPT          |   1997 | 46508447686.8547 |
| EGYPT          |   1996 | 46690311537.3405 |
| EGYPT          |   1995 | 46510997784.8437 |
| EGYPT          |   1994 | 46580424269.0847 |
| EGYPT          |   1993 | 46542365846.1999 |
| EGYPT          |   1992 | 46724828058.3082 |
| ETHIOPIA       |   1998 | 27274431160.2063 |
| ETHIOPIA       |   1997 | 46593500894.9085 |
| ETHIOPIA       |   1996 | 46676851418.1443 |
| ETHIOPIA       |   1995 | 46563949926.2197 |
| ETHIOPIA       |   1994 | 46598274528.6390 |
| ETHIOPIA       |   1993 | 46562165353.6044 |
| ETHIOPIA       |   1992 | 46633197214.4451 |
| FRANCE         |   1998 | 27364545156.0157 |
| FRANCE         |   1997 | 46644908587.4628 |
| FRANCE         |   1996 | 46776042618.8349 |
| FRANCE         |   1995 | 46619725429.5537 |
| FRANCE         |   1994 | 46640062083.9793 |
| FRANCE         |   1993 | 46588787186.8213 |
| FRANCE         |   1992 | 46750777403.1767 |
| GERMANY        |   1998 | 27433863395.5308 |
| GERMANY        |   1997 | 46788129708.6970 |
| GERMANY        |   1996 | 46857587305.7980 |
| GERMANY        |   1995 | 46735061771.4682 |
| GERMANY        |   1994 | 46753698686.6553 |
| GERMANY        |   1993 | 46761415449.1980 |
| GERMANY        |   1992 | 46850611965.5057 |
| INDIA          |   1998 | 27376935245.6504 |
| INDIA          |   1997 | 46671296239.5675 |
| INDIA          |   1996 | 46701636617.4914 |
| INDIA          |   1995 | 46624659477.2160 |
| INDIA          |   1994 | 46651839798.1025 |
| INDIA          |   1993 | 46692879230.9598 |
| INDIA          |   1992 | 46747361415.5922 |
| INDONESIA      |   1998 | 27441744505.2493 |
| INDONESIA      |   1997 | 46829043449.6109 |
| INDONESIA      |   1996 | 47020297189.9484 |
| INDONESIA      |   1995 | 46870150347.7851 |
| INDONESIA      |   1994 | 46857736679.2005 |
| INDONESIA      |   1993 | 46754248849.7454 |
| INDONESIA      |   1992 | 46955834667.6646 |
| IRAN           |   1998 | 27336063132.3677 |
| IRAN           |   1997 | 46709848122.9179 |
| IRAN           |   1996 | 46783863964.4720 |
| IRAN           |   1995 | 46709138719.5905 |
| IRAN           |   1994 | 46706772764.1516 |
| IRAN           |   1993 | 46740153899.4324 |
| IRAN           |   1992 | 46883432639.3081 |
| IRAQ           |   1998 | 27395351810.8138 |
| IRAQ           |   1997 | 46776736649.9695 |
| IRAQ           |   1996 | 46738301309.3609 |
| IRAQ           |   1995 | 46676871228.6939 |
| IRAQ           |   1994 | 46708124648.8562 |
| IRAQ           |   1993 | 46603994118.2243 |
| IRAQ           |   1992 | 46764170223.7343 |
| JAPAN          |   1998 | 27271187974.0469 |
| JAPAN          |   1997 | 46581618517.5346 |
| JAPAN          |   1996 | 46687494878.4697 |
| JAPAN          |   1995 | 46483285757.6832 |
| JAPAN          |   1994 | 46496872623.9868 |
| JAPAN          |   1993 | 46529202129.3653 |
| JAPAN          |   1992 | 46689031883.6027 |
| JORDAN         |   1998 | 27293209697.7168 |
| JORDAN         |   1997 | 46578299571.4210 |
| JORDAN         |   1996 | 46682512998.3114 |
| JORDAN         |   1995 | 46555009143.9003 |
| JORDAN         |   1994 | 46673542968.0759 |
| JORDAN         |   1993 | 46607300156.4843 |
| JORDAN         |   1992 | 46753753309.8506 |
| KENYA          |   1998 | 27281504772.7471 |
| KENYA          |   1997 | 46593911919.0632 |
| KENYA          |   1996 | 46665208373.4748 |
| KENYA          |   1995 | 46569293548.4281 |
| KENYA          |   1994 | 46513269603.8079 |
| KENYA          |   1993 | 46573413532.2021 |
| KENYA          |   1992 | 46675139625.6528 |
| MOROCCO        |   1998 | 27376400349.0192 |
| MOROCCO        |   1997 | 46611557096.4126 |
| MOROCCO        |   1996 | 46810351497.0726 |
| MOROCCO        |   1995 | 46708136951.6444 |
| MOROCCO        |   1994 | 46748633362.2255 |
| MOROCCO        |   1993 | 46693617477.0706 |
| MOROCCO        |   1992 | 46783066120.7488 |
| MOZAMBIQUE     |   1998 | 27378623554.1160 |
| MOZAMBIQUE     |   1997 | 46720572989.0149 |
| MOZAMBIQUE     |   1996 | 46787905701.0318 |
| MOZAMBIQUE     |   1995 | 46633802176.0175 |
| MOZAMBIQUE     |   1994 | 46705378563.0543 |
| MOZAMBIQUE     |   1993 | 46609910455.4511 |
| MOZAMBIQUE     |   1992 | 46699289402.6361 |
| PERU           |   1998 | 27297153104.6352 |
| PERU           |   1997 | 46552024610.3310 |
| PERU           |   1996 | 46686413332.4495 |
| PERU           |   1995 | 46566188044.3415 |
| PERU           |   1994 | 46587148988.2890 |
| PERU           |   1993 | 46585982644.9568 |
| PERU           |   1992 | 46757724388.1410 |
| ROMANIA        |   1998 | 27289562535.6456 |
| ROMANIA        |   1997 | 46637951116.9111 |
| ROMANIA        |   1996 | 46741937391.1563 |
| ROMANIA        |   1995 | 46632128735.5714 |
| ROMANIA        |   1994 | 46646371174.4405 |
| ROMANIA        |   1993 | 46613516575.3731 |
| ROMANIA        |   1992 | 46761477971.3476 |
| RUSSIA         |   1998 | 27244791471.3398 |
| RUSSIA         |   1997 | 46590159232.8258 |
| RUSSIA         |   1996 | 46661715899.2187 |
| RUSSIA         |   1995 | 46608059946.8877 |
| RUSSIA         |   1994 | 46532018457.8570 |
| RUSSIA         |   1993 | 46499433625.4979 |
| RUSSIA         |   1992 | 46622219789.4768 |
| SAUDI ARABIA   |   1998 | 27376098612.4255 |
| SAUDI ARABIA   |   1997 | 46713584318.2289 |
| SAUDI ARABIA   |   1996 | 46758204924.5040 |
| SAUDI ARABIA   |   1995 | 46618821206.8951 |
| SAUDI ARABIA   |   1994 | 46546664114.6846 |
| SAUDI ARABIA   |   1993 | 46667193611.0846 |
| SAUDI ARABIA   |   1992 | 46732521817.5379 |
| UNITED KINGDOM |   1998 | 27369705666.1322 |
| UNITED KINGDOM |   1997 | 46693585553.2173 |
| UNITED KINGDOM |   1996 | 46828445097.2350 |
| UNITED KINGDOM |   1995 | 46608001951.3781 |
| UNITED KINGDOM |   1994 | 46650243971.1835 |
| UNITED KINGDOM |   1993 | 46639116456.3116 |
| UNITED KINGDOM |   1992 | 46764902857.4273 |
| UNITED STATES  |   1998 | 27431057829.4538 |
| UNITED STATES  |   1997 | 46679729172.5646 |
| UNITED STATES  |   1996 | 46781101797.5040 |
| UNITED STATES  |   1995 | 46744151253.5940 |
| UNITED STATES  |   1994 | 46702490551.6844 |
| UNITED STATES  |   1993 | 46660226630.3126 |
| UNITED STATES  |   1992 | 46800756102.0111 |
| VIETNAM        |   1998 | 27307628473.4169 |
| VIETNAM        |   1997 | 46695096595.1733 |
| VIETNAM        |   1996 | 46706761313.7791 |
| VIETNAM        |   1995 | 46572676354.0574 |
| VIETNAM        |   1994 | 46637175524.0621 |
| VIETNAM        |   1993 | 46569669418.5548 |
| VIETNAM        |   1992 | 46753230976.5035 |
+----------------+--------+------------------+
175 rows in set (1 min 44.17 sec)
预期结果：https://github.com/matrixorigin/mo-tpch/blob/main/golden/TPCH_1000/q9.txt

执行Q9当时日志业务异常ERROR：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22qFM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-86dbf35af-20240904%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725520906000%22,%22to%22:%221725521008000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke tpch 1T test
```

**Comment by badboynt1** [comment]
最近有个hang住的问题，暂未复现结果错误的问题

**Comment by badboynt1** [comment]
暂时没有再复现

**Comment by badboynt1** [comment]
暂时没有再复现

**Comment by heni02** [comment]
再没有复现，先closed，新出现再提单
