### ISSUE TITLE
[Bug]: txnimpl/table.go logs too much, CI failed.

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#18559]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

86dbf35af

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

日志打印超过阈值（1000 行/秒）

[mo-service.log.1.tgz](https://github.com/user-attachments/files/16887645/mo-service.log.1.tgz)

![image](https://github.com/user-attachments/assets/8052be44-08c1-4f4a-94ab-17643643a8ab)

附件是 2024/09/04 15:00:49 ~ 2024/09/04 15:01:48 的日志, 
主要是 txnimpl/table.go:357， txnimpl/table.go:405， txnimpl/table.go:413 在刷日志
```
$ cat mo-service.log.1  | awk '{print $4, $5}' | grep INFO  | sort | uniq -c | sort -n | tail
1577 INFO rpc/handle.go:525
1583 INFO rpc/handle.go:578
2102 INFO tn-service.lockservice.lockservice.allocator
2110 INFO cn-service.lockservice
2367 INFO tn-service.logtail-server
3555 INFO cn-service
11305 INFO compile/sql_executor.go:359
119035 INFO txnimpl/table.go:357
119035 INFO txnimpl/table.go:405
119035 INFO txnimpl/table.go:413

$ let val=119035/60; echo $val
1983
```

### Steps to Reproduce

https://github.com/matrixorigin/matrixone/actions/runs/10704212820/job/29676638690
```Markdown
```

**Comment by xzxiong** [comment]
note
```
徐鹏 9-5 18:04
transfer deletes的日志

徐鹏 9-5 18:05
这个现在的打开的，因为dup,ww需要这个

徐鹏 9-5 18:05
现在bvt里加了新的case,导致transfer变得比较频繁
```

**Comment by XuPeng-SH** [comment]
done
