### ISSUE TITLE
[Bug]: ci ut may be stuck forever

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#18583]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fbca7b3954a6d4fcb2870056b64466288ff5e6c8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ut is stuck

![image](https://github.com/user-attachments/assets/291c8896-d579-49aa-9e27-9369d0741438)

### Expected Behavior

should not be stuck

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10735387361/job/29772733368?pr=18564
```

**Comment by guguducken** [comment]
@fengttt @zhangxu19830126 please take a look

**Comment by zhangxu19830126** [comment]
Tests of cluster restarts now cause ut to go all HUNG, there are very many issues, logtail consumption panic bugs, hundreds of gorutine leaks after restarting services. Integration tests for restarts are now turned off.
