### ISSUE TITLE
[Refactoring]: do not create new go routine for TP query

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#18599]
### Why do you want to refactor this code?

```Markdown
类似select 1等单个scope的TP类语句，不要新申请go routine执行，使用当前协程即可
```

### Describe the solution you'd like

不要新申请go routine执行，使用当前协程即可

**Comment by badboynt1** [comment]
其实任意query，只要不包含connector dispatch merge这三个算子，都可以直接执行，不用起goroutine 
如果有多个scope，只要递归先跑prescope就可以了
