### ISSUE TITLE
[Performance]: improve checkTableDefChange

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#18598]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):main
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

目前 checkTableDefChange 在select 1中占比还是太高（约3.3%）
需要继续优化，方向是：
方向1：在消费logtail消息的时候。如果涉及到DDL的，cache到session中，这样就可以直接判断
方向2：提升getRelation的性能
优先方向1

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by jensenojs** [comment]
勘误 : 这里应该是select where
