### ISSUE TITLE
[Refactoring]: build Batch of value_scan in construct value_scan 

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#18605]
### Why do you want to refactor this code?

```Markdown
目前value_scan对应的batch是在value_scan的prepare构造的。
希望移到constructValueScan中。但是会有其他一些问题需要处理
```

### Describe the solution you'd like

1、目前对于prepare的execute语句，是在prepare阶段构造的原始batch。
对于非prepare的语句，是在buildplan的时候构造的原始batch
需要把这些地方构造的batch去掉，只保留对应的表达式即可

2、在constructValueScan时，初始化这个原始batch，对于可以折叠的表达式，可以提前设置好对应的值

3、在value_scan的prepare的时候，初始化一次对应表达式执行器，执行表达式拿到对应的值

注意确认是否会有性能回退

**Comment by aressu1985** [comment]
可以在2.0.1完成，只需要跑BVT和REGRESSION测试即可
