### ISSUE TITLE
[Bug]: [date 9.6]standalone regression: create gist 960dim  vector index reported internal error: wait message timeout

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18625]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0eba06817ae743e8658beb7cbe9e1f4743d550f2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10740444396/job/29788572547
sql:create index gidx_4000 using ivfflat on vector_index.vector_960dim(b) lists=4000 op_type "vector_l2_ops";
![image](https://github.com/user-attachments/assets/2b2d5242-ece4-4c44-9f80-e45e9320ab2e)

### Steps to Reproduce

```Markdown
create database if not exists vector_index;use vector_index;create table vector_960dim(a int primary key, b vecf32(960));
source /data1/mo-benchmark-test/gist960_with_pk.sql (contact me)
create index gidx_4000 using ivfflat on vector_index.vector_960dim(b) lists=4000 op_type "vector_l2_ops";
```

**Comment by heni02** [comment]
正在二分

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
commit:48304fdb79f5d6486706f9a4cc965b83781c9c01
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10903140510/job/30256594212
