### ISSUE TITLE
[Subtask]: Explain the pipeline information of SQL physical plan

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#18620]
### Parent Issue

#17421

### Detail of Subtask

explain pipeline功能， 把sql执行的pipeline和算子信息进行打印输出

**Comment by qingxinhome** [comment]
https://github.com/matrixorigin/matrixone/issues/15205

**Comment by qingxinhome** [comment]
[Uploading EXPLAIN PHYPLAN Grammar Explanation Document.md…]()

**Comment by aressu1985** [comment]
fixed
