### ISSUE TITLE
[Bug]: TestChangesHandle3 UT fail

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#18629]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

UT fail
[error.log](https://github.com/user-attachments/files/16918423/error.log)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10750724894/job/29817210641?pr=18626
```

**Comment by ouyuanning** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/10803608265/job/29967731205?pr=18698
repo
