### ISSUE TITLE
[Bug]: big-data-regression: select count(*) from table hung.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18624]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0eba06817ae743e8658beb7cbe9e1f4743d550f2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url : https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10740458366/job/29788625482 

出问题的sql：select count(*) from big_data_test.table_with_pk_index_for_write_1B
从14:36开始执行，现在17:02了，还没执行完
<img width="992" alt="image" src="https://github.com/user-attachments/assets/084d99c5-b876-4640-bbde-fff7b272508b">

goroutines(对应时间：15:13:11)
[CN_34633038-6232-6534-3932-326531373764_goroutine_0191cb54-6610-7abe-919e-54b94bdbb782.gz](https://github.com/user-attachments/files/16917177/CN_34633038-6232-6534-3932-326531373764_goroutine_0191cb54-6610-7abe-919e-54b94bdbb782.gz)

执行出问题sql开始的日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Kb4%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240906%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725690972000%22,%22to%22:%221725698172000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big data regression on tke

数据量10亿（大约330G）
表schema：
create table if not exists big_data_test.table_with_pk_index_for_write_1B( id bigint primary key, col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));

出问题的sql：select count(*) from big_data_test.table_with_pk_index_for_write_1B
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
观察了两天没再hung了，先关掉
