### ISSUE TITLE
[Refactoring]: lock op should not dup batches

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18630]
### Why do you want to refactor this code?

```Markdown
lock op should not dup batches.   It should just lock and send out batches without copying
```

### Describe the solution you'd like

lock op should not dup batches.   It should just lock and send out batches without copying.

if necessary, we should make output operator batch result.   Two cases come to mind, select * for update and if user specified result batch size for paging.

**Comment by ouyuanning** [comment]
跟 [#https://github.com/matrixorigin/matrixone/issues/18630](https://github.com/matrixorigin/matrixone/issues/18512) 应该是一个

**Comment by jensenojs** [comment]
done @fengttt
