### ISSUE TITLE
[Bug]: big-data- regressin: load data from cos executed about 3h+.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18637]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c4548ff4584f1c6a8b6dc6b2b5193fce99a8f8a0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**url：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10751753684/job/29824586674**

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/c0b1070d-fcaa-4f49-ab53-0d65dab30d6d">

**超时sql对应时间段日志：** 
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XsO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240907%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725718211000%22,%22to%22:%221725729011000%22%7D%7D%7D&schemaVersion=1&orgId=1

**goroutine：**
时间点（2024-09-07 22:26:47）
[CN_32306131-3065-6364-3038-323032313038_goroutine_0191cce1-5f76-7c35-ad66-12788939eace.gz](https://github.com/user-attachments/files/16924730/CN_32306131-3065-6364-3038-323032313038_goroutine_0191cce1-5f76-7c35-ad66-12788939eace.gz)

时间点（2024-09-08 00:26:47）
[CN_32306131-3065-6364-3038-323032313038_goroutine_0191cd4f-3c8f-714f-9454-db8f7e9f2e73.gz](https://github.com/user-attachments/files/16924741/CN_32306131-3065-6364-3038-323032313038_goroutine_0191cd4f-3c8f-714f-9454-db8f7e9f2e73.gz)

### Steps to Reproduce

```Markdown
load 10亿行（大约330G）数据进表：

第一次出问题的sql（涉及到ak sk，如有需要，请联系我）：
load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com/','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761', 'filepath'='mo-big-data/1000000000_20_columns_load_data_pk.csv'} into table big_data_test.table_with_pk_index_for_load_1b fields terminated by '|' lines terminated by '\n' ignore 1 lines parallel 'true';`
```

**Comment by sukki37** [comment]
https://grafana.ci.matrixorigin.cn/goto/UDsg_peIg?orgId=1 

The SQL in the issue finished executing at UTC time 2024-09-07 17:17:49.950, taking 190 minutes.

**Comment by Ariznawlll** [comment]
longrunnig对应的日志文件：
[longrunning2.tar.gz](https://github.com/user-attachments/files/16928773/longrunning2.tar.gz)

**Comment by Ariznawlll** [comment]
longrunning对应的日志文件：
[longrunning2.tar.gz](https://github.com/user-attachments/files/16928982/longrunning2.tar.gz)

**Comment by Ariznawlll** [comment]
**job URL：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10751753684/job/29836390801**

<img width="971" alt="image" src="https://github.com/user-attachments/assets/b02df3c4-72db-424b-ba96-fd32bd195bd7">

出错的table schema:
`create table  if not exists big_data_test.table_basic_for_alter_1B( col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));`

具体出问题的sql：
```
alter table big_data_test.table_basic_for_alter_1B add PRIMARY KEY (col4);
alter table big_data_test.table_basic_for_alter_1B add PRIMARY KEY (col3,col4); 
```

longrunning日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22zA-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240907%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725798414000%22,%22to%22:%221725809214000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by badboynt1** [comment]
fixed

**Comment by Ariznawlll** [comment]
**今天没出现，测试正常
测试job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10794221436/job/29946255125**
**main commit: 154b93bc2d451bcc5fd1c64b48722a643b7607c2**

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/e3486bc8-7bb2-4d93-a69e-1ee4a3028bb1">

测试通过

**Comment by Ariznawlll** [comment]
**今天没出现，测试正常
commit：9d664291c02c71e045ac4dc4444ae86cc5e27218**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10813562571/job/29998127988

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/6bd8a63c-8519-4234-b9e6-3b1e57417305">
测试通过
