### ISSUE TITLE
[Bug]: performance regression of loading compressed file

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#18643]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
daily run里的load data test，以前大约一个半小时
Main Nightly Regression Test / LOAD DATA TEST
succeeded 4 days ago in 1h 24m 49s

pipeline重构后，耗时增长到接近翻倍
Main Nightly Regression Test / LOAD DATA TEST
succeeded 6 hours ago in 2h 41m 24s
```

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
commit:5be19c2b1
<img width="1223" alt="企业微信截图_1af7831c-cc91-46fc-982d-08337f90580c" src="https://github.com/user-attachments/assets/da2f71a7-d1c4-452a-aaa0-90d1a0435e76">
