### ISSUE TITLE
[Bug]: kill server using ^C cause SIGSEGV

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18669]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

58b390ea

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Started server using etc/launch-multi-cn, hit ^C to quit.   Run into a sigsegv.

2024/09/09 17:26:44.433810 -0700 INFO log-service v2@v2.0.0-20240611082008-a4de209fff3d/application.go:383 session read failed {"service": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-server", "listen-addresses": "[0.0.0.0:32001]", "session-id": 19, "addr": "127.0.0.1:59656", "error": "writeto tcp4 127.0.0.1:32001->127.0.0.1:59656: read tcp4 127.0.0.1:32001->127.0.0.1:59656: use of closed network connection"}
2024/09/09 17:26:44.433810 -0700 INFO log-service v2@v2.0.0-20240611082008-a4de209fff3d/application.go:383 session read failed {"service": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-server", "listen-addresses": "[0.0.0.0:32001]", "session-id": 46, "addr": "127.0.0.1:59946", "error": "writeto tcp4 127.0.0.1:32001->127.0.0.1:59946: read tcp4 127.0.0.1:32001->127.0.0.1:59946: use of closed network connection"}
2024/09/09 17:26:44.433807 -0700 ERROR hakeeper-client-backend morpc/backend.go:583 read from backend failed {"remote": "127.0.0.1:32001", "backend-id": "0191d952-39af-7712-a7bf-e0f626c61746", "error": "EOF"}
2024/09/09 17:26:44.434820 -0700 ERROR log-service v2@v2.0.0-20240611082008-a4de209fff3d/application.go:357 handle session failed {"service": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-server", "listen-addresses": "[0.0.0.0:32001]", "error": "writeto tcp4 127.0.0.1:32001->127.0.0.1:60186: read tcp4 127.0.0.1:32001->127.0.0.1:60186: use of closed network connection"}
2024/09/09 17:26:44.434889 -0700 ERROR log-service v2@v2.0.0-20240611082008-a4de209fff3d/session.go:515 close conneciton failed {"service": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-server", "session-id": 69, "error": "close tcp4 127.0.0.1:32001->127.0.0.1:60186: use of closed network connection"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3951c12]

goroutine 3945 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).Rollback(0x0, 0xc02ad557a0)
        /home/fengttt/m/matrixone/pkg/frontend/txn.go:536 +0xd2
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest(0xc0358b9100, 0xc02ad55ba0)
        /home/fengttt/m/matrixone/pkg/frontend/routine.go:343 +0x10a5
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler(0xc0293e2c40, 0xc0353587e0, {0xc035e00000, 0x1, 0x1})                                                                      /home/fengttt/m/matrixone/pkg/frontend/routine_manager.go:383 +0x347
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest(0xc02bb20000, 0xc0353587e0)                                                                                                /home/fengttt/m/matrixone/pkg/frontend/server.go:471 +0x1eb
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage(0xc02bb20000, 0xc0353587e0)
        /home/fengttt/m/matrixone/pkg/frontend/server.go:440 +0x45
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop(0xc0293e2c40?, 0xc0353587e0?)
        /home/fengttt/m/matrixone/pkg/frontend/server.go:203 +0x1f
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn(0xc02bb20000, {0x55217f8?, 0xc02a3b67a0?})                                                                                    /home/fengttt/m/matrixone/pkg/frontend/server.go:199 +0x476
created by github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).startAccept in goroutine 2112                                                                                                 /home/fengttt/m/matrixone/pkg/frontend/server.go:167 +0xf0

### Expected Behavior

Gracefully shutdown

### Steps to Reproduce

```Markdown
Start multi-cn using launch, hit ^C.
```

**Comment by daviszhen** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
