### ISSUE TITLE
[Bug]: big-data-regression: insert into select executed about 3h+.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18663]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c4548ff4584f1c6a8b6dc6b2b5193fce99a8f8a0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**url : https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10751753684/job/29824586674**

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/3406ddf5-d7d4-4850-be3d-b028757f48ad">

**对应时间的log：（UTC时间：2024-09-07 23:09:36-2024-09-08 02:09:36）**
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XsO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240907%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221725750576000%22,%22to%22:%221725761376000%22%7D%7D%7D&schemaVersion=1&orgId=1

**goroutine:**
对应时间2024-09-08 10:56:47（utc+8）
[CN_32306131-3065-6364-3038-323032313038_goroutine_0191cf90-0500-7e9a-b1fa-7939acb67429.gz](https://github.com/user-attachments/files/16928858/CN_32306131-3065-6364-3038-323032313038_goroutine_0191cf90-0500-7e9a-b1fa-7939acb67429.gz)
对应时间2024-09-08 11:46:47（utc+8）
[CN_32306131-3065-6364-3038-323032313038_goroutine_0191cfbd-cbdb-7b62-833a-c84b2f5918c8.gz](https://github.com/user-attachments/files/16928865/CN_32306131-3065-6364-3038-323032313038_goroutine_0191cfbd-cbdb-7b62-833a-c84b2f5918c8.gz)

**longrunning日志：**
https://grafana.ci.matrixorigin.cn/goto/8ObzEpeSg?orgId=1

**longrunnig日志对应文件：**
[longrunning.tar.gz](https://github.com/user-attachments/files/16927893/longrunning.tar.gz)

### Steps to Reproduce

```Markdown
数据量：10亿行（大约330G）

出问题的sql：insert into big_data_test.table_with_pk_index_for_insert_1B(id,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25) select * from big_data_test.table_with_pk_for_load_1B where col4 != -7508478199581380391
```

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/18637  与这个可能是同一问题

**Comment by Ariznawlll** [comment]
**今天没出现，测试正常
测试job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10794221436/job/29946255125**
**main commit: 154b93bc2d451bcc5fd1c64b48722a643b7607c2**

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/8ebaf1e3-8f8a-484f-99fb-2a47d9118667">

测试通过

**Comment by Ariznawlll** [comment]
**今天没出现，测试正常
commit：9d664291c02c71e045ac4dc4444ae86cc5e27218**

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10813562571/job/30005927942

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/a125bf44-5571-40de-8686-27ebff1c8bc8">

测试通过
