### ISSUE TITLE
[Bug]: session allocator memory leaks

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#18673]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

49dd70cd56cf0dbef6753e1ce2dfcaff018f5b5c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

session memory leaks:

![Screenshot from 2024-09-10 11-09-46](https://github.com/user-attachments/assets/750648dd-f8c1-4996-89ed-3a5b8279ed23)

URL: https://grafana.ci.matrixorigin.cn/d/bde9827b-b1ae-4e75-a23a-1cec245a57a7/memory-metrics?orgId=1&var-interval=1m&var-namespace=mo-main-nightly-49dd70cd5-20240908&var-pod=All&from=1725804000000&to=1725894000000

### Steps to Reproduce

```Markdown
found in the main branch nightly regression test:
 https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10760736483
```

**Comment by fengttt** [comment]
Anyway to identify WHICH allocator, and WHERE is the leak allocated?   Does allocator has such an instrument?

**Comment by reusee** [comment]
右下角的图片就是session allocator的指标，只有前端使用。已经是细分的了。

**Comment by reusee** [comment]
9号的nightly也一样：https://grafana.ci.matrixorigin.cn/d/bde9827b-b1ae-4e75-a23a-1cec245a57a7/memory-metrics?orgId=1&refresh=30s&var-interval=1m&var-namespace=mo-main-nightly-3725be9ed-20240909&var-pod=All&from=1725853440223&to=1726026240223

**Comment by reusee** [comment]
7号的没有泄漏：https://grafana.ci.matrixorigin.cn/d/bde9827b-b1ae-4e75-a23a-1cec245a57a7/memory-metrics?orgId=1&refresh=30s&var-interval=1m&var-namespace=mo-main-nightly-3725be9ed-20240909&var-pod=All&from=1725853440223&to=1726026240223
所以应该是在7号到8号之间引入的

**Comment by daviszhen** [comment]
进行中

**Comment by daviszhen** [comment]
原因定位中。

**Comment by daviszhen** [comment]
定位中

**Comment by reusee** [comment]
https://grafana.ci.matrixorigin.cn/d/bde9827b-b1ae-4e75-a23a-1cec245a57a7/memory-metrics?orgId=1&var-interval=1m&var-namespace=mo-main-nightly-e2a5a4bac-20240918&var-pod=All&from=1726617600000&to=1726768800000
9月18日的metrics，没有观察到这个现象了：
<img width="1097" alt="截屏2024-09-21 16 24 23" src="https://github.com/user-attachments/assets/118f0fdb-9454-43e0-8ac1-6b8b10f5c02f">

**Comment by reusee** [comment]
9月17号也没有：https://grafana.ci.matrixorigin.cn/d/bde9827b-b1ae-4e75-a23a-1cec245a57a7/memory-metrics?orgId=1&var-interval=1m&var-namespace=mo-main-nightly-48304fdb7-20240917&var-pod=All&from=1726531200000&to=1726682400000
<img width="1102" alt="截屏2024-09-21 16 25 58" src="https://github.com/user-attachments/assets/f0766f46-065f-4190-80df-1b77571d0f01">

推测这个问题已经被未知的commit修正

**Comment by daviszhen** [comment]
mysql buffer的代码要再调整下

**Comment by daviszhen** [comment]
在整理网络缓冲区的代码。加leak检测逻辑。

**Comment by daviszhen** [comment]
ut中。

**Comment by daviszhen** [comment]
已经合并了一个pr。
还有一个共享全局变量的问题。解决之后就能close

**Comment by daviszhen** [comment]
pr中

**Comment by daviszhen** [comment]
fixed
