### ISSUE TITLE
[Bug]: memory leaks in the frontend package

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#18671]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

58b390eab24e014b13667f8df4cc766f119dd34b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

memory leaks:

![Screenshot from 2024-09-10 10-54-57](https://github.com/user-attachments/assets/10254fde-bb2f-478d-9220-43aa1a085e1e)

profile:
[profile.pb.gz](https://github.com/user-attachments/files/16938783/profile.pb.gz)

### Steps to Reproduce

run this test in the embed package:

```
func TestConn(t *testing.T) {
	go http.ListenAndServe(":9876", nil)
	RunBaseClusterTests(
		func(c Cluster) {
			cn0, err := c.GetCNService(0)
			require.NoError(t, err)

			dsn := fmt.Sprintf("dump:111@tcp(127.0.0.1:%d)/",
				cn0.GetServiceConfig().CN.Frontend.Port,
			)

			db, err := sql.Open("mysql", dsn)
			require.NoError(t, err)
			defer db.Close()
			db.SetMaxIdleConns(0)

			for {
				conn, err := db.Conn(context.Background())
				require.NoError(t, err)
				fmt.Printf("%v\n", conn)

				err = conn.Raw(func(driverConn any) error {
					c := driverConn.(driver.Conn)
					c.Close()
					return nil
				})
				require.NoError(t, err)
			}

		},
	)
}

```

then open the memory profile: 
```
go tool pprof -http :6060 http://localhost:9876/debug/pprof/heap

```

The above test creates new conns and then closes them, but causes memory leaks in the frontend package.

This leak may be the root cause of the OOM in the Daily Regression Test on 128 test。 The above test function tries to reproduce the leaks faster.

**Comment by daviszhen** [comment]
这个RunBaseClusterTests在同一个进程中启动了3个cn。frontend的rm全局变量会被后一个rm覆盖掉。导致connectid串到其他cn上。连接关闭时，正确的cn上的资源没有释放掉。

**Comment by daviszhen** [comment]
fixed
