### ISSUE TITLE
[Bug]: file 0191da87-8206-7802-b1be-a3e979bf7edd_00000 is not found when creating partition tables

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#18683]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b2d8e4aefb0d7b3b3d7deb19a772c6bbfa973a9f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t1 (a int,b int,c int,key(a,b))
    -> partition by range (a)
    -> partitions 3
    -> (partition x1 values less than (0),
    ->  partition x2 values less than (10),
    ->  partition x3 values less than maxvalue);
ERROR 20405 (HY000): file 0191da87-8206-7802-b1be-a3e979bf7edd_00000 is not found

but after a while, the problem gone

mysql> create table t1 (a int,b int,c int,key(a,b))
    -> partition by range (a)
    -> partitions 3
    -> (partition x1 values less than (0),
    ->  partition x2 values less than (10),
    ->  partition x3 values less than maxvalue);
Query OK, 0 rows affected (0.04 sec)

log:
[server.tar.gz](https://github.com/user-attachments/files/16942036/server.tar.gz)

### Steps to Reproduce

```Markdown
create table t1 (a int,b int,c int,key(a,b))
partition by range (a)
partitions 3
(partition x1 values less than (0),
 partition x2 values less than (10),
 partition x3 values less than maxvalue);
```

**Comment by LeftHandCold** [comment]
not found的是mo_tables的一个atombstone 在报错的2个小时前就已经soft delete并且在40分钟前被正常GC，但是create table的时候还需要load这个atombstone，所以报了not found

**Comment by LeftHandCold** [comment]
还未投入

**Comment by LeftHandCold** [comment]
我投入

**Comment by LeftHandCold** [comment]
还未投入

**Comment by LeftHandCold** [comment]
还未投入

**Comment by aressu1985** [comment]
repo on 9.29:
mysql> 
mysql> 
mysql> 
mysql> create account if not exists tpch_test admin_name = 'admin' identified by '111' comment 'for tpch test';
ERROR 20405 (HY000): file 01923bc1-5243-7cc0-96f0-9543d9286d73_00000 is not found
mysql> 

mo-log:
[mo-service.log](https://github.com/user-attachments/files/17177424/mo-service.log)

**Comment by LeftHandCold** [comment]
> repo on 9.29: mysql> mysql> mysql> mysql> create account if not exists tpch_test admin_name = 'admin' identified by '111' comment 'for tpch test'; ERROR 20405 (HY000): file 01923bc1-5243-7cc0-96f0-9543d9286d73_00000 is not found mysql>
> 
> mo-log: [mo-service.log](https://github.com/user-attachments/files/17177424/mo-service.log)

这个是环境问题

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
并没有复现

**Comment by LeftHandCold** [comment]
并没有复现
