### ISSUE TITLE
[Question]: Matrixone Upgrade CI / Compatibility Test With Target on Linux/x64(LAUNCH) Test Failed/Corrupted

### ISSUE THREAD

**Issue by cpegeric** [matrixorigin/matrixone#18686]
### Describe your problem

The issue is about the test job with link below:

[Matrixone Upgrade CI / Compatibility Test With Target on Linux/x64(LAUNCH)](https://github.com/matrixorigin/matrixone/actions/runs/10780029956/job/29895073597#logs)

The test job returned more than 1000 errors.

[SUMMARY] COST : 1275s, TOTAL :66321, SUCCESS : 48113, FAILED :1205, IGNORED :2200, ABNORAML :14803, SUCCESS RATE : 75%

Error found in the log such as 

1. invalid database sub_database01
2. not connect to a database
3. invalid input: column account_id does not exist
4. invalid answer

Looks like the test is corrupted or server is down.

**Comment by sukki37** [comment]
There's no valid information; let's close this issue for now.
