### ISSUE TITLE
[Bug]: ci bvt 'select count(1) cnt, metric_name, collecttime, `node`, role, account, type from system_metrics.metric group by metric_name, collecttime, `node`, role, account, type having cnt > 1' failed

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18687]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

3a6b745d019afeb37d44a418255502103ebd214c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/matrixone/actions/runs/10787941085/job/29917696283?pr=18681
<img width="991" alt="image" src="https://github.com/user-attachments/assets/775a5cec-06bb-4b88-bbde-92ab4b8b3fd5">

log:  [Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports.zip](https://github.com/user-attachments/files/16942151/Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64.LAUNCH.PROXY.-reports.zip)

### Steps to Reproduce

```Markdown
trigger ci test
```

**Comment by xzxiong** [comment]
@badboynt1 转给我，不合适。
根据bvt的背景，是执行sql时，没正确设置 tenant信息导致。
> 注：不能因为是我加的bvt就得我解决，这里case本身没有问题，

**Comment by xzxiong** [comment]
根据 https://github.com/matrixorigin/matrixone/actions/runs/10790951263/job/29927294175?pr=18681 
运行结果分析
- 目前有 4个时间段有 出问题的 sql （每个时段 15s )
![image](https://github.com/user-attachments/assets/1456482e-58bf-44ef-a859-7765a3b5f026)

**Comment by xzxiong** [comment]
如何寻找有问题的 query,
1. 查询 statement_info  where account = '';
    - `select * from system.statement_info where account = '' and response_at between ...`
3. 修改 `incStatementCounter(...)`, 加个panic
```diff
func incStatementCounter(tenant, queryType string) {
+      if tenant == "" {
+           panic(fmt.Errorf("tenant is nil."))
+      }
	metric.StatementCounter(tenant, queryType).Inc()
}
```

**Comment by xzxiong** [comment]
找到一个 statement 
`select database_name, table_name, retention_deadline from mo_catalog.mo_retention`
![image](https://github.com/user-attachments/assets/da935a97-1df0-478f-9452-2a42087ac0ad)

**Comment by xzxiong** [comment]
> 找到一个 statement `select database_name, table_name, retention_deadline from mo_catalog.mo_retention` ![image](https://private-user-images.githubusercontent.com/3927687/366287375-ab305545-f428-41de-9da6-d08c6d2e5bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjYxNDksIm5iZiI6MTcyNjAyNTg0OSwicGF0aCI6Ii8zOTI3Njg3LzM2NjI4NzM3NS1hYjMwNTU0NS1mNDI4LTQxZGUtOWRhNi1kMDhjNmQyZTViZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMDMzNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhlMTRhZTFlMzllZGVjMTM5YjVhZTVmZTIxZmRiZmZjNTczNDQ0OGZkZjM2ZmY2MWZkZWVhNmM4MzczNWViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CssueV9p3-i0kb1t-SQW9CBgEVYUUNXS64IY1v3CktI)

@daviszhen @Ariznawlll  ptal

**Comment by YANGGMM** [comment]
@w-zr  麻烦看一下

**Comment by w-zr** [comment]
内部执行器查询其他租户下的mo_catalog表时没有填UserID，导致没有权限。因此报错。

**Comment by w-zr** [comment]
和#18651 相同

**Comment by Ariznawlll** [comment]
fixed
