### ISSUE TITLE
[Feature Request]: 相同数据对象只能创建一个 PITR

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#18692]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1、相同数据对象只能创建一个 PITR；
2、集群管理员和租户管理员的 PITR 相对独立，即可以对相同的数据对象分别创建一个 PITR

**Comment by YANGGMM** [comment]
@Ariznawlll 麻烦测试一下

**Comment by Ariznawlll** [comment]
sys租户，创建了account级别的pitr，再次创建报错：
<img width="519" alt="image" src="https://github.com/user-attachments/assets/935a65c0-909c-4e0b-a008-cab27f98b85c">

sys租户，为table tpcc.bmsql_customer创建了table级别的pitr，再次创建报错：
<img width="742" alt="image" src="https://github.com/user-attachments/assets/4d22a3f2-fde8-4780-b470-d68f75c60e7f">

sys租户，为db创建db级别的pitr，重复创建报错：
<img width="627" alt="image" src="https://github.com/user-attachments/assets/368d32fc-d641-4323-af88-c327b4472dc1">

**Comment by Ariznawlll** [comment]
普通租户为普通租户创建account/database/table级别的pitr
普通租户，创建了account级别的pitr，重复创建报错：
<img width="513" alt="image" src="https://github.com/user-attachments/assets/cdbd45b2-125b-48b8-a16d-ebe7df22b635">

普通租户，创建db级别的pitr，重复创建报错：
<img width="562" alt="image" src="https://github.com/user-attachments/assets/807439b7-e970-4948-a967-7577a16f2bbf">

普通租户创建table级别的pitr，重复创建报错：
<img width="623" alt="image" src="https://github.com/user-attachments/assets/dd5f263e-cd7d-4bf6-b4d1-e53a6e7f3b77">

**Comment by Ariznawlll** [comment]
系统租户为普通租户创建account级别的pitr，重复创建报错：

<img width="615" alt="image" src="https://github.com/user-attachments/assets/4dfed22d-74d8-4f0e-85ce-f6b8a051955f">
