### ISSUE TITLE
[Feature request]: Prophet rewrite

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1870]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
We need to rewrite prophet in order to get rid of verbose code.
```

### Describe the solution you'd like

null

**Comment by JinHai-CN** [comment]
Plan is changed.

**Comment by florashi181** [comment]
This issue will be redefined in release 0.6.
