### ISSUE TITLE
[Bug]: `duplicate key name` error is reported when auto migrating table with gorm

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#18704]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.3-f01f07a2a-2024-09-10

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Schema:
```
CREATE TABLE `users` (
  `id` VARCHAR(128) NOT NULL,
  `username` VARCHAR(255) DEFAULT NULL,
  `password` VARCHAR(512) DEFAULT NULL,
  `user_status` TINYINT DEFAULT NULL,
  `user_role` TINYINT DEFAULT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `user_source` TINYINT DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mocadmin_users_username` (`username`)
)
```

When auto migrating the table with gorm, the following error is fired:

```
{"level":"ERROR","time":"2024/09/11 02:47:13.953512 +0000","caller":"migrator/migrator.go:74","msg":"trace","error":"Error 1061 (HY000): duplicate key name 'idx_mocadmin_users_username'","elapsed":"4.990153ms","rows":0,"sql":"CREATE UNIQUE INDEX `idx_mocadmin_users_username` ON `mocadmin`.`users`(`username`)"}
panic: InitMySQLDB failed:Error 1061 (HY000): duplicate key name 'idx_mocadmin_users_username'
```

However, when checking the data in the table, there is no duplicate user name:

```
select username from users order by username desc;
37 rows in set (0.06 sec)
select distinct username from users order by username desc;
37 rows in set (0.06 sec)
```

### Expected Behavior

Auto migration succeeds

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

### Additional information

Cloud dev

**Comment by YANGGMM** [comment]
run migrate first time:
Table created or migrated successfully.

run migrate second time:
2024/09/13 16:20:52  Error 1061 (HY000): duplicate key name 'idx_mocadmin_users_username'
[24.954ms] [rows:0] CREATE UNIQUE INDEX `idx_mocadmin_users_username` ON `users`(`username`)


貌似是之前已经迁移成功了，再迁移就会报这个错


测试一下mysql
run migrate first time:
Table created or migrated successfully.

run migrate second time
Table created or migrated successfully.

看来mo还是有问题

**Comment by YANGGMM** [comment]
查看statement_info
select statement from statement_info where `database` = 'etao' order by response_at asc;

| SET NAMES utf8mb4                                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_1 from SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE ? ORDER BY SCHEMA_NAME=? DESC,SCHEMA_NAME limit 1                                                                                                                                                                            |
| deallocate prepare __mo_stmt_id_1                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_2 from SELECT count(*) FROM information_schema.tables WHERE table_schema = ? AND table_name = ? AND table_type = ?                                                                                                                                                                                             |
| deallocate prepare __mo_stmt_id_2                                                                                                                                                                                                                                                                                                   |
| CREATE TABLE `users` (`id` varchar(128) NOT NULL,`username` varchar(255),`password` varchar(512),`user_status` tinyint,`user_role` tinyint,`created_at` datetime,`updated_at` datetime,`user_source` tinyint,PRIMARY KEY (`id`),UNIQUE INDEX `idx_mocadmin_users_username` (`username`))                                            |
+--------------------------------------------------------



| SET NAMES utf8mb4                                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_1 from SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE ? ORDER BY SCHEMA_NAME=? DESC,SCHEMA_NAME limit 1                                                                                                                                                                            |
| deallocate prepare __mo_stmt_id_1                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_2 from SELECT count(*) FROM information_schema.tables WHERE table_schema = ? AND table_name = ? AND table_type = ?                                                                                                                                                                                             |
| deallocate prepare __mo_stmt_id_2                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_3 from SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE ? ORDER BY SCHEMA_NAME=? DESC,SCHEMA_NAME limit 1                                                                                                                                                                            |
| deallocate prepare __mo_stmt_id_3                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_4 from SELECT * FROM `users` LIMIT ?                                                                                                                                                                                                                                                                           |
| deallocate prepare __mo_stmt_id_4                                                                                                                                                                                                                                                                                                   |
| prepare __mo_stmt_id_5 from SELECT column_name, column_default, is_nullable = 'YES', data_type, character_maximum_length, column_type, column_key, extra, column_comment, numeric_precision, numeric_scale , datetime_precision FROM information_schema.columns WHERE table_schema = ? AND table_name = ? ORDER BY ORDINAL_POSITION |
| deallocate prepare __mo_stmt_id_5                                                                                                                                                                                                                                                                                                   |
| CREATE UNIQUE INDEX `idx_mocadmin_users_username` ON `users`(`username`)

**Comment by YANGGMM** [comment]
SELECT column_name, column_default, is_nullable = 'YES', data_type, character_maximum_length, column_type, column_key, extra, column_comment, numeric_precision, numeric_scale , datetime_precision FROM information_schema.columns WHERE table_schema = 'etao' AND table_name = 'users' ORDER BY ORDINAL_POSITION;

<img width="709" alt="image" src="https://github.com/user-attachments/assets/64793fe8-f40d-43fd-96a5-03a16035c776">


怀疑是mo的information_schema.columns 缺少了对unique index col的定义，导致 grom 重复发送CREATE UNIQUE INDEX， 然后会报错

**Comment by YANGGMM** [comment]
fixed，plz test @aressu1985

**Comment by aressu1985** [comment]
fixed
