### ISSUE TITLE
[Feature Request]: Support timestamp datatype and timestamp functions -- now need to handle time zone 

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1871]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
The datatype of TIMESTAMP is often used for time related tables. With this datatype, CURRENT_TIMESTAMP and UNIX_TIMESTAMP are also used as supporting functions.
```

### Describe the solution you'd like

Given MO has supported DATETIME, which has wider range of TIMESTAMP, we can create a synonym of DATETIME directly.

CURRENT_TIMESTAMP()， get current timestamp from local OS and the output must be a DATETIME or TIMESTMAP datatype.

UNIX_TIMESTAMP(T TIMESTAMP)，the return value should be the gap from (1970-01-01 00:00:00 UT) to (current timestamp in local time zone). It is measured in second.

### Additional information

mysql> select current_timestamp();

+---------------------+
| current_timestamp() |
+---------------------+
| 2022-02-17 17:12:56 |
+---------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp('1970-01-01 09:00:00');
+---------------------------------------+
| unix_timestamp('1970-01-01 09:00:00') |
+---------------------------------------+
|                                  3600 |
+---------------------------------------+
1 row in set (0.00 sec)

**Comment by dengn** [comment]
The datatype timestamp requires support of time zone. We need to have time zone variables to define `system time zone` and `session time zone`. 
The overall design should follow [MySQL8.0](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html). 

Corresponding operations such as below need to be supported. 
```sql
SET GLOBAL time_zone = timezone;
SET time_zone = timezone;
SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
```

**Comment by dengn** [comment]
In the DDL operations, we need to support the `CURRENT_TIMESTAMP` usage. 

For example,
```sql
CREATE TABLE t1 (
         a INT,
         ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
       );
```

**Comment by dengn** [comment]
Timestamp needs to support fractional seconds with up to microseconds (6 digits) precision. It is explicitly specified by users as TIMESTAMP(N). 

By default, if we declare an attribute by TIMESTAMP, it gives only `YY-MM-DD HH:MM:SS` format. But if we declare an attribute by TIMESTAMP(N), it gives N fractional seconds. N should be maximum 6. 

```sql
CREATE TABLE test (`timestamp` timestamp,`datetime` datetime);
insert into test values(now(), now());
select * from test;

+---------------------+---------------------+
| timestamp           | datetime            |
+---------------------+---------------------+
| 2022-05-11 17:48:21 | 2022-05-11 17:48:21 |
+---------------------+---------------------+
 
create table tstest(a datatime, b timestamp(6));
insert into tstest(now(), now());
select * from tstest;
+---------------------+----------------------------+
| a                   | b                          |
+---------------------+----------------------------+
| 2022-05-12 10:39:08 | 2022-05-12 10:39:08.000000 |
+---------------------+----------------------------+
```

**Comment by dengn** [comment]
The range is also different from DATETIME and TIMESTAMP. 

DATETIME：from 1000-01-01 00:00:00.000000 to 9999-12-31 23:59:59.999999
TIMESTAMP：from '1970-01-01 00:00:01.000000' UTC to '2038-01-09 03:14:07.999999' UTC

**Comment by dengn** [comment]
The current_timestamp() function is a synonym of Now() function. So please consider finishing this function along with now() issue at https://github.com/matrixorigin/matrixone/issues/1830.

**Comment by broccoliSpicy** [comment]
> In the DDL operations, we need to support the `CURRENT_TIMESTAMP` usage.
> 
> For example,
> 
> ```sql
> CREATE TABLE t1 (
>          a INT,
>          ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
>        );
> ```

huh, I am not sure what's matrixone's approach to support default value, I guess I will discuss with the team and maybe draft a design proposal

**Comment by broccoliSpicy** [comment]
> The range is also different from DATETIME and TIMESTAMP.
> 
> DATETIME：from 1000-01-01 00:00:00.000000 to 9999-12-31 23:59:59.999999 TIMESTAMP：from '1970-01-01 00:00:01.000000' UTC to '2038-01-09 03:14:07.999999' UTC

the timestamp range mysql has probably came from the infamous [2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) on 32bit machine, since we use 64bit to store timestamp, this is no need for this range constraint.

**Comment by broccoliSpicy** [comment]
> > The range is also different from DATETIME and TIMESTAMP.
> > DATETIME：from 1000-01-01 00:00:00.000000 to 9999-12-31 23:59:59.999999 TIMESTAMP：from '1970-01-01 00:00:01.000000' UTC to '2038-01-09 03:14:07.999999' UTC
> 
> the timestamp range mysql has probably came from the infamous [2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) on 32bit machine, since we use 64bit to store timestamp, this is no need for this range constraint.

As we discussed off GitHub, I will keep this constraint

**Comment by broccoliSpicy** [comment]
> In the DDL operations, we need to support the `CURRENT_TIMESTAMP` usage.
> 
> For example,
> 
> ```sql
> CREATE TABLE t1 (
>          a INT,
>          ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
>        );
> ```

this usage is not supported in v0.5

**Comment by broccoliSpicy** [comment]
> > In the DDL operations, we need to support the `CURRENT_TIMESTAMP` usage.
> > For example,
> > ```sql
> > CREATE TABLE t1 (
> >          a INT,
> >          ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
> >        );
> > ```
> 
> this usage is not supported in v0.5



> The datatype timestamp requires support of time zone. We need to have time zone variables to define `system time zone` and `session time zone`. The overall design should follow [MySQL8.0](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html).
> 
> Corresponding operations such as below need to be supported.
> 
> ```sql
> SET GLOBAL time_zone = timezone;
> SET time_zone = timezone;
> SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
> ```
> 
> After time_zone setting, the stored timestamp value needs to be shown with the time zone. A brief showcase is as follows:
> 
> ```sql
> SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
> +--------------------+---------------------+
> | @@GLOBAL.time_zone | @@SESSION.time_zone |
> +--------------------+---------------------+
> | SYSTEM             | +08:00              |
> +--------------------+---------------------+
> CREATE TABLE test (`timestamp` timestamp,`datetime` datetime);
> insert into test values(now(), now());
> select * from test;
> +---------------------+---------------------+
> | timestamp           | datetime            |
> +---------------------+---------------------+
> | 2022-05-11 17:48:21 | 2022-05-11 17:48:21 |
> +---------------------+---------------------+
> 
> set time_zone = '+10:00';
> select * from test;
> +---------------------+---------------------+
> | timestamp           | datetime            |
> +---------------------+---------------------+
> | 2022-05-11 19:48:21 | 2022-05-11 17:48:21 |
> +---------------------+---------------------+
> ```

this usage is not supported in v0.5

**Comment by broccoliSpicy** [comment]
> > In the DDL operations, we need to support the `CURRENT_TIMESTAMP` usage.
> > For example,
> > ```sql
> > CREATE TABLE t1 (
> >          a INT,
> >          ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
> >        );
> > ```
> 
> this usage is not supported in v0.5

this usage will be part of v0.6 plan

**Comment by broccoliSpicy** [comment]
> > > In the DDL operations, we need to support the `CURRENT_TIMESTAMP` usage.
> > > For example,
> > > ```sql
> > > CREATE TABLE t1 (
> > >          a INT,
> > >          ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
> > >        );
> > > ```
> > 
> > 
> > this usage is not supported in v0.5
> 
> > The datatype timestamp requires support of time zone. We need to have time zone variables to define `system time zone` and `session time zone`. The overall design should follow [MySQL8.0](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html).
> > Corresponding operations such as below need to be supported.
> > ```sql
> > SET GLOBAL time_zone = timezone;
> > SET time_zone = timezone;
> > SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After time_zone setting, the stored timestamp value needs to be shown with the time zone. A brief showcase is as follows:
> > ```sql
> > SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
> > +--------------------+---------------------+
> > | @@GLOBAL.time_zone | @@SESSION.time_zone |
> > +--------------------+---------------------+
> > | SYSTEM             | +08:00              |
> > +--------------------+---------------------+
> > CREATE TABLE test (`timestamp` timestamp,`datetime` datetime);
> > insert into test values(now(), now());
> > select * from test;
> > +---------------------+---------------------+
> > | timestamp           | datetime            |
> > +---------------------+---------------------+
> > | 2022-05-11 17:48:21 | 2022-05-11 17:48:21 |
> > +---------------------+---------------------+
> > 
> > set time_zone = '+10:00';
> > select * from test;
> > +---------------------+---------------------+
> > | timestamp           | datetime            |
> > +---------------------+---------------------+
> > | 2022-05-11 19:48:21 | 2022-05-11 17:48:21 |
> > +---------------------+---------------------+
> > ```
> 
> this usage is not supported in v0.5

this usage will be part of v0.6 plan

**Comment by dengn** [comment]
time zone handling and timestamp in ddl will be in 0.6.

**Comment by aunjgr** [comment]
Both the datatype and its functions has been implemented for `timestamp`. I think this should be closed.
