### ISSUE TITLE
[Bug]: show table status不稳定，时慢时快

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#18718]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v1.2.3

### Commit ID

f01f07a2a75a4ecd5ae27130a633f13651aa1751

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
阿里云QA演练环境。
```

### Actual Behavior

show table status SQL速度不稳定。
较慢的如下：
```
2024/09/11 14:08:10.399878 +0000 [31mERROR[0m models/meta.go:229 trace {"error": "context canceled", "elapsed": "59.89071395s", "rows": 0, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `hhh`"}
2024/09/11 14:07:10.121192 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "52.858972235s", "rows": 257, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `bb`"}
2024/09/11 14:06:40.320067 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "23.057799045s", "rows": 53, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `db2`"}
2024/09/11 14:06:28.819833 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "11.557593727s", "rows": 38, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `aa`"}
2024/09/11 14:06:30.822332 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "13.560057908s", "rows": 3, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `dfd`"}
2024/09/11 14:06:32.498343 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "15.236055198s", "rows": 452, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `hhh`"}
2024/09/11 14:06:33.383802 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "16.121502087s", "rows": 386, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `all`"}
```
较快的如下：
```
2024/09/11 14:06:17.363742 +0000 [33mWARN[0m models/meta.go:229 trace {"elapsed": "101.547926ms", "rows": 8, "sql": "/* cloud_nonuser */ SHOW TABLE STATUS FROM `tpch_10g`"}
```
只有一百多毫秒。
以上日志时间均为UTC时间。

账号如下：
01907ccc_147b_7b70_a5b0_f04e292304cb
Admin123

复现较容易。

### Expected Behavior

希望可以优化

### Steps to Reproduce

```Markdown
如Actual Behavior
```

**Comment by gouhongshen** [comment]
https://grafana.cn-qa.matrixone.tech/d/matrixone_Txn_Metrics/txn-metrics?orgId=1&from=1726119022000&to=1726122622000



<img width="1603" alt="企业微信截图_fd605369-1649-4f05-9990-de5721c3d256" src="https://github.com/user-attachments/assets/3fa26090-6e62-423b-870c-34e7010f9a6c">

**Comment by gouhongshen** [comment]
在做其他的

**Comment by gouhongshen** [comment]
depend on: https://github.com/matrixorigin/matrixone/issues/15708

**Comment by gouhongshen** [comment]
对于 show table status，这个优化目前没有效果，因为 show table status 内部使用到的是 Size, Row 接口，而不是直接调用 mo_table_size, mo_table_rows. 如果要优化 show table status，需要直接使用 mo_table_size, mo_table_rows 接口。也可以直接使用 mo table stats 提供的接口: disttae.QueryTableStats. 建议使用 mo_table_size, mo_table_rows 的接口，这样就可以使用到 session variable，以及切换到以前的实现。

**Comment by aressu1985** [comment]
fixed
