### ISSUE TITLE
[Feature Request]: support substr() and substring() function

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1872]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
In certain showcases, there are some queries with substr or left in WHERE clause, which is also used widely in AP scenarios.
```

### Describe the solution you'd like

Provide function substring() and its synomym substr(), both upcases and lowcases, as following:
SUBSTRING(str,pos) ,  

SUBSTRING(str FROM pos),

SUBSTRING(str,pos,len),

SUBSTRING (str FROM pos FOR len)

**str:** Input string. Must be char or varchar datatype.

**pos:** The position of first character in substring. It should be an interger and its absolute value is less than the length of str. If pos > 0, the position of pos is from left to right. If pos < 0, the the position of pos is from right to left.

**len:** The length of subtring.  It should be an unsigned integer which less than the length of str.

**Comment by yingfeng** [comment]
duplicate with #2163
