### ISSUE TITLE
[Feature Request]: Support to_date function to make new date and datetime formats insertable

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1873]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
In actual scenarios, the formats of date datatype is various. MO only supports YYYYMMDD and YYYY-MM-DD now. We need a function to_date to make new date and datetime formats insertable.
```

### Describe the solution you'd like

to_date(date/datetime, format)

Support the formats of date as following in INSERT:

MMDDYYYY

DDMMYYYY

MM-DD-YYYY

DD-MM-YYYY

Support the new formats of datetime as following in INSERT:

HHMMSS

### Additional information

create table t1(a date);

insert into t1 values(to_date('12012022','MMDDYYYY');

insert into t1 values(to_date('01-12-2022','DD-MM-YYYY');

create table t2(a datetime);

insert into t2 values('20221202 120000','YYYYMMDD HHMMSS');

**Comment by dengn** [comment]
Is this function the [STR_TO_DATE(str,format)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_str-to-date) in MySQL? @domingozhang

**Comment by domingozhang** [comment]
its only part of features of to_date, in other databases to_date can convert integer to date as well

**Comment by broccoliSpicy** [comment]
> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Is your feature request related to a problem?
> ```gfm
> In actual scenarios, the formats of date datatype is various. MO only supports YYYYMMDD and YYYY-MM-DD now. We need a function to_date to make new date and datetime formats insertable.
> ```
> 
> ### Describe the solution you'd like
> to_date(date/datetime, format)
> 
> Support the formats of date as following in INSERT:
> 
> MMDDYYYY
> 
> DDMMYYYY
> 
> MM-DD-YYYY
> 
> DD-MM-YYYY
> 
> Support the new formats of datetime as following in INSERT:
> 
> HHMMSS
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Documentation, Adoption, Use Case, Migration Strategy
> _No response_
> 
> ### Additional information
> create table t1(a date);
> 
> insert into t1 values(to_date('12012022','MMDDYYYY');
> 
> insert into t1 values(to_date('01-12-2022','DD-MM-YYYY');
> 
> create table t2(a datetime);
> 
> insert into t2 values('20221202 120000','YYYYMMDD HHMMSS');

datetime format is not supported because I think this is not the correct semantic for to_date function, this function returns a date string

**Comment by fengttt** [comment]
@broccoliSpicy please check, if the semantics complies with our rule, clearly state that and close.   Otherwise, if the to_date conversion rule for date/datetime is not fully implemented, state what is not done yet, and set this one to 0.6.

**Comment by dengn** [comment]
date format is not supported yet. Move to 0.6.

**Comment by broccoliSpicy** [comment]
this is the bvt test case for this to_date function...
[SQL STATEMENT]: SELECT DATE_ADD(to_date('9999-12-30 23:59:00','%Y-%m-%d %H:%i:%s'), INTERVAL 1 MINUTE);

[SQL STATEMENT]: SELECT to_date('01,5,2013','%d,%m,%Y');

[SQL STATEMENT]: SELECT to_date('May 1, 2013','%M %d,%Y');

[SQL STATEMENT]: SELECT to_date('a09:30:17','a%h:%i:%s');

[SQL STATEMENT]: SELECT to_date('a09:30:17','%h:%i:%s');

[SQL STATEMENT]: SELECT to_date('09:30:17a','%h:%i:%s');

[SQL STATEMENT]: SELECT to_date('abc','abc');

[SQL STATEMENT]: SELECT to_date('9','%m');

[SQL STATEMENT]: SELECT to_date('9','%s');

[SQL STATEMENT]: SELECT to_date('00/00/0000', '%m/%d/%Y');

[SQL STATEMENT]: SELECT to_date('04/31/2004', '%m/%d/%Y');

[SQL STATEMENT]: SELECT to_date('00/00/0000', '%m/%d/%Y');

[SQL STATEMENT]: SELECT to_date('200442 Monday', '%X%V %W');

[SQL STATEMENT]: select to_date(concat_ws(' ','15-01-2001'), ' 2:59:58.999');

[SQL STATEMENT]: select concat_ws('',to_date('8:11:2.123456 03-01-02','%H:%i:%S.%f %y-%m-%d'));

[SQL STATEMENT]: select to_date('04 /30/2004', '%m /%d/%Y');

[SQL STATEMENT]: select to_date('04/30 /2004', '%m /%d /%Y');

[SQL STATEMENT]: select to_date('04/30/2004 ', '%m/%d/%Y ');

[SQL STATEMENT]: SELECT DATE_SUB(to_date('9999-12-31 00:01:00','%Y-%m-%d %H:%i:%s'), INTERVAL 1 MINUTE);

[SQL STATEMENT]: SELECT DATE_ADD(to_date('9999-12-30 23:59:00','%Y-%m-%d %H:%i:%s'), INTERVAL 1 MINUTE);

[SQL STATEMENT]: select to_date('10:00 PM', '%h:%i %p') + INTERVAL 10 MINUTE;

[SQL STATEMENT]: select to_date('2007-10-09','%Y-%m-%d') > '2007/10/01 00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d') = '2007-10-1 00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d') = '2007-10-01 x00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d %H:%i:%s') = '2007-10-01 00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d %H:%i:%s') = '2007-10-01 00:x00:00 GMT-6';

[SQL STATEMENT]: select to_date('1000-01-01','%Y-%m-%d') between NULL and NULL;

[SQL STATEMENT]: select to_date('2007-10-00','%Y-%m-%d') between '' and '2007/10/20';

[SQL STATEMENT]: select to_date('2007-10-00','%Y-%m-%d') between '2007/09/01'
and '2007/10/20';

[SQL STATEMENT]: select to_date('2007-10-09','%Y-%m-%d') between '2007/10/01 00:00:00 GMT'
and '2007/10/20 00:00:00 GMT';

[SQL STATEMENT]: SELECT to_date('09:22', '%H:%i');

[SQL STATEMENT]: SELECT to_date('09:22:23.33', '%H:%i:%s.%f');

[SQL STATEMENT]: INSERT INTO t1 select( to_date('09:22', '%H:%i') );

[SQL STATEMENT]: INSERT INTO t1 select( to_date('09:22:23.33', '%H:%i:%s.%f') );

[SQL STATEMENT]: SELECT TO_DATE(SPACE(2),'1');

**Comment by qingxinhome** [comment]
The implementation of Date() function has been reconstructed. To_DATE and STR_TO_DATE is a synonym, The second parameter of the STR_TO_DATE(str, format) function is limited to a string constant. @dengn @aressu1985 @daviszhen @domingozhang

**Comment by aressu1985** [comment]
this featrue has been tested done
