### ISSUE TITLE
[Bug]: 2nd index may not be the right access path.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18735]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

303d13d1dd760f2b722d68d458f296e537506e09

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In cases, optimizer choose to use 2nd index.   The access path may turns out to be slower than table scan.    So we observe that we created an index, but the query slow down.

### Expected Behavior

Index should never slow down query

### Steps to Reproduce

```Markdown
A 2nd index with relatively low cardinality
```

### Additional information

Also we have a real join for using 2nd index.   The truth is, once we created run time filter, the hash table is useless and later the join is also unnecessary.   We should optimize the join to an no-op.

**Comment by fengttt** [comment]
And the 2nd index access is way too slow.    We have a case that take 85s to scan ~250 blocks.    It is off by order of magnitude.

**Comment by badboynt1** [comment]
fixed
