### ISSUE TITLE
[Bug]: kill self connection  make cn crash

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#18744]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select connection_id();
No connection. Trying to reconnect...
Connection id:    2102
Current database: *** NONE ***

+-----------------+
| connection_id() |
+-----------------+
|            2102 |
+-----------------+
1 row in set (0.00 sec)

mysql> kill connection 2102;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 54
ERROR: 
Can't connect to the server

panic: send on closed channel

goroutine 1658 [running]:
github.com/matrixorigin/matrixone/pkg/proxy.sendResp(...)
	/Users/yangzhao/matrixone/pkg/proxy/event.go:76
github.com/matrixorigin/matrixone/pkg/proxy.(*serverConn).ExecStmt(0x14028599740, {0x20?, {0x140158f1ba8?, 0x14035719130?}}, 0x14036581110)
	/Users/yangzhao/matrixone/pkg/proxy/server_conn.go:182 +0x234
github.com/matrixorigin/matrixone/pkg/proxy.(*clientConn).connAndExec(0x1401fe40d80, 0x100000836?, {0x140158f1ba8, 0x14}, 0x14036581110)
	/Users/yangzhao/matrixone/pkg/proxy/client_conn.go:342 +0x1f0
github.com/matrixorigin/matrixone/pkg/proxy.(*clientConn).handleKillQuery(0x1401fe40d80, 0x140309a9c80, 0x14036581110)
	/Users/yangzhao/matrixone/pkg/proxy/client_conn.go:379 +0x364
github.com/matrixorigin/matrixone/pkg/proxy.(*clientConn).HandleEvent(0x14010e34ee0?, {0x14010e34dbc?, 0x108794600?}, {0x108ed0260?, 0x140309a9c80?}, 0x1?)
	/Users/yangzhao/matrixone/pkg/proxy/client_conn.go:300 +0x170
github.com/matrixorigin/matrixone/pkg/proxy.(*handler).handle.func5({0x108f104f8, 0x1403627bf20})
	/Users/yangzhao/matrixone/pkg/proxy/handler.go:205 +0x1b8
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/Users/yangzhao/matrixone/pkg/common/stopper/stopper.go:277 +0x64
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 1712
	/Users/yangzhao/matrixone/pkg/common/stopper/stopper.go:272 +0xb0

### Steps to Reproduce

```Markdown
create account acc1 admin_name 'root' identified by '111';


mysql -h127.0.0.1 -uacc1:root -P6009 -p111

select connection_id();

kill connection xxx;
```

**Comment by heni02** [comment]
1.2-dev commit:afc962958
tke环境：
普通租户ac1 kill connection



单机环境：测试符合预期
普通租户ac1 kill connection，符合预期
heni@henideMacBook-Pro matrixone % mysql -h 127.0.0.1 -uac1:admin -P6001 -p111
mysql>  select connection_id();
+-----------------+
| connection_id() |
+-----------------+
|              11 |
+-----------------+
1 row in set (0.00 sec)

mysql> kill connection 11;
Query OK, 0 rows affected (0.01 sec)

mysql> kill connection 11;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    15
Current database: db

ERROR 20101 (HY000): internal error: Unknown connection id 11
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| db                 |
| information_schema |
| mo_catalog         |
| mysql              |
| system             |
| system_metrics     |
+--------------------+
6 rows in set (0.00 sec)

sys租户kill connection，符合预期
heni@henideMacBook-Pro matrixone % mysql -h 127.0.0.1 -udump -P6001 -p111
mysql> select connection_id();
+-----------------+
| connection_id() |
+-----------------+
|              27 |
+-----------------+
1 row in set (0.00 sec)

mysql> kill connection 27;
Query OK, 0 rows affected (0.00 sec)

mysql> select connection_id();
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    28
Current database: *** NONE ***

+-----------------+
| connection_id() |
+-----------------+
|              28 |
+-----------------+
1 row in set (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mo_catalog         |
| mo_debug           |
| mo_task            |
| mysql              |
| system             |
| system_metrics     |
| testdb             |
+--------------------+
8 rows in set (0.00 sec)

**Comment by heni02** [comment]
main commit:2c2d52bc1
confirm,closed

tke环境普通租户ac2 kill connection，测试符合预期
[root@VM-0-124-tencentos ~]# mysql -h172.16.2.125 -uac2:admin -P6001 -p123
mysql> select connection_id();
+-----------------+
| connection_id() |
+-----------------+
|          196889 |
+-----------------+
1 row in set (0.00 sec)

mysql> kill connection 196889;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    196998
Current database: *** NONE ***

Query OK, 0 rows affected (0.44 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mo_catalog         |
| mysql              |
| system             |
| system_metrics     |
+--------------------+
5 rows in set (0.10 sec)

sys租户kill connection，测试符合测试预期
[root@VM-0-124-tencentos ~]# mysql -h172.16.2.125 -udump -P6001 -p111
mysql> select connection_id();
+-----------------+
| connection_id() |
+-----------------+
|          196907 |
+-----------------+
1 row in set (0.00 sec)

mysql> kill connection 196907;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    196874
Current database: *** NONE ***

Query OK, 0 rows affected (0.46 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mo_catalog         |
| mo_debug           |
| mo_task            |
| mysql              |
| ssb_100g           |
| ssb_10g            |
| ssb_1g             |
| sysbench_db        |
| system             |
| system_metrics     |
| test               |
| tpcc_10            |
| tpcc_100           |
| tpcc_1000          |
| tpcc_500           |
| tpch_1000g         |
| tpch_100g          |
| tpch_10g           |
| tpch_1g            |
+--------------------+
20 rows in set (0.10 sec)
