### ISSUE TITLE
[Feature Request]:  Support more date related functions

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1874]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
These functions are used widely in date related query. Given the progress of MO, we need support them as following.
```

### Describe the solution you'd like

month(D), D should be date or datetime type. Return the month of the date or datetime. Its synonym is tomonth(), which range is 1 to 12.

day(D), D should be date or datetime type. Return the day of the month. Its synonym is dayofmonth(), which range is 1 to 31.

week(D),  D should be date or datetime type. Return the the week of a year. Its synonym is toweek(), which range is 1 to 52.

### Additional information

``` sql
> select month('2022-02-20');

2

> select day('2022-02-20');

20

> select week('2022-02-20');

8
```

**Comment by fengttt** [comment]
day, month, etc not implemented yet.

**Comment by dengn** [comment]
day and month are already implemented. test cases will be added in 0.6.

**Comment by dongdongyang33** [comment]
Modify some expected results related to week() function in PR #3631
