### ISSUE TITLE
[Bug]: NewRoutineManager panic

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#18764]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/3e6730b0-dbc7-4ed8-8e61-4af0fbd3c512">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10837592828/job/30073876550?pr=18748
```

**Comment by YANGGMM** [comment]
dup: https://github.com/matrixorigin/MO-Cloud/issues/4068

**Comment by aressu1985** [comment]
fixed
