### ISSUE TITLE
[Bug]: TestMessage takes too long

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#18767]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/6923dbc3-8a2b-48c4-af1d-bc4a27ad073b)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10833574792/job/30060702362?pr=18746
```

**Comment by XuPeng-SH** [comment]
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/1463c9ef-ebb5-4db9-a969-100ae4dd0d3e">

**Comment by XuPeng-SH** [comment]
```go test --count 1 -failfast  github.com/matrixorigin/matrixone/pkg/vm/message/... ```
It takes a long time to run

**Comment by badboynt1** [comment]
这个ut不需要了，直接关闭吧
