### ISSUE TITLE
[Feature Request]: Support DELETE statement.

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1877]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

``` sql
DELETE 

FROM tbl_name [[AS] tbl_alias] 

[WHERE where_condition] 

[ORDER BY ...] 

[LIMIT row_count]
```

**Comment by JinHai-CN** [comment]
The statement is supported. Since TPE is canceled, the function will be implemented in 0.5.0 along with TAE.
