### ISSUE TITLE
[Bug]: ut TestCalculateObjectCount failed. data race happen

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#18781]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6a33c321a7d434d60823b28e5c2d3cff10e36ad1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

data race in TestCalculateObjectCount
see CI log
[job-logs (6).txt.zip](https://github.com/user-attachments/files/16991171/job-logs.6.txt.zip)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/10843439708/job/30090638330?pr=18743
```

**Comment by daviszhen** [comment]
未投入

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/10952292419/job/30410731380?pr=18642

[job-logs.txt.zip](https://github.com/user-attachments/files/17069414/job-logs.txt.zip)

**Comment by daviszhen** [comment]
it was fixed.
