### ISSUE TITLE
[Bug]: coverage test in CI is not running cmd/mo-service tests

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#18792]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

955e00b20b3fa58c92ba16dba37d3f186df85fae

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Tests in cmd/mo-service are not run causing this PR to fail: https://github.com/matrixorigin/matrixone/pull/18788

The conntrack module needs root permission to run, so it's ignored in the BVT tests:

![Screenshot from 2024-09-14 10-26-11](https://github.com/user-attachments/assets/95e809bc-0da5-4758-a620-8169dbfe55a6)

In the UT coverage tests, the cmd/mo-service package is ignored, resulting in no coverage info.

### Expected Behavior

Tests in the cmd/mo-service should be run in coverage tests in CI.
Even without root permission, the coverage should be like:
![Screenshot from 2024-09-14 10-31-29](https://github.com/user-attachments/assets/4c9a1c05-9e38-46c5-8a9e-5a1871b94cf7)

### Steps to Reproduce

```Markdown
pr CI.
```

**Comment by guguducken** [comment]
fixed: https://github.com/matrixorigin/matrixone/actions/runs/10859286757/job/30138411645
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/b0e74299-e489-45f5-b547-151d5053fcf2">
