### ISSUE TITLE
[Bug]: context deadline exceeded occurred in ci bvt test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18790]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

23e94dadfe4e24ed8296d23a69780311dc62335f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:  https://github.com/matrixorigin/matrixone/actions/runs/10850712350/job/30112810070?pr=18714

<img width="996" alt="image" src="https://github.com/user-attachments/assets/5a4fcb82-57c9-4794-ace1-d4445236ddb9">

[Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports.zip](https://github.com/user-attachments/files/17000621/Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64.LAUNCH.PROXY.-reports.zip)

### Steps to Reproduce

```Markdown
trigger ci bvt test
```

**Comment by YANGGMM** [comment]
2024/09/13 14:30:10.145420 +0000 INFO compile/sql_executor.go:359 sql_executor exec {"sql": "select offset, step from mo_increment_columns where table_id = 272509 and col_name = '__mo_fake_pk_col' for update", "txn-id": "c8977292a36b72a617f4d35efa498124", "duration": "852.158µs", "BatchSize": 1, "AffectedRows": 0}
2024/09/13 14:30:10.145472 +0000 ERROR cn-service frontend/txn.go:63 context deadline exceeded {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "session_info": "connectionId 3||account sys:dump|goRoutineId 0|migrate-goRoutineId 0|0191ebbd-c0b5-7c2d-abba-13b88b9270d1", "background": true, "session_id": "0191ebca-536c-7d6e-ae5c-bec0fb751035", "txn_id": "c8977292a36b72a617f4d35efa4980fa", "span": {"trace_id": "6568c7dc-a920-b614-6915-996c1e0c6b92", "span_id": "f81736f8f49e315b"}}
2024/09/13 14:30:10.145524 +0000 ERROR cn-service frontend/util.go:514 query trace status {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "statement": "", "status": "fail", "error": "context deadline exceeded", "txn_info": "c8977292a36b72a617f4d35efa4980fa:1726237791129182177-1", "session_info": "connectionId 3||account sys:dump|goRoutineId 0|migrate-goRoutineId 0|0191ebbd-c0b5-7c2d-abba-13b88b9270d1", "background": true, "session_id": "0191ebca-536c-7d6e-ae5c-bec0fb751035", "txn_id": "c8977292a36b72a617f4d35efa4980fa", "span": {"trace_id": "6568c7dc-a920-b614-6915-996c1e0c6b92", "span_id": "f81736f8f49e315b"}}

**Comment by YANGGMM** [comment]
2024/09/13 14:29:51.133876 +0000 INFO cn-service frontend/snapshot.go:1067 [0191ebca-536d-7da9-9a30-fa48b45db7ea_sp01_mock] **start to insert select table: rs01, insert sql: insert into `test01`.`rs01` SELECT * FROM `test01`.`rs01` {MO_TS = 1726237791063362369 }** {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf"}

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/1bc0a77e-9949-479f-b1e4-4e18fdfe6c09">

执行没有完成

2024/09/13 14:30:10.145472 +0000 ERROR cn-service frontend/txn.go:63 context deadline exceeded {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "session_info": "connectionId 3||account sys:dump|goRoutineId 0|migrate-goRoutineId 0|0191ebbd-c0b5-7c2d-abba-13b88b9270d1", "background": true, "session_id": "0191ebca-536c-7d6e-ae5c-bec0fb751035", "txn_id": "c8977292a36b72a617f4d35efa4980fa", "span": {"trace_id": "6568c7dc-a920-b614-6915-996c1e0c6b92", "span_id": "f81736f8f49e315b"}}
2024/09/13 14:30:10.145524 +0000 ERROR cn-service frontend/util.go:514 query trace status {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "statement": "", "status": "fail", "error": "context deadline exceeded", "txn_info": "c8977292a36b72a617f4d35efa4980fa:1726237791129182177-1", "session_info": "connectionId 3||account sys:dump|goRoutineId 0|migrate-goRoutineId 0|0191ebbd-c0b5-7c2d-abba-13b88b9270d1", "background": true, "session_id": "0191ebca-536c-7d6e-ae5c-bec0fb751035", "txn_id": "c8977292a36b72a617f4d35efa4980fa", "span": {"trace_id": "6568c7dc-a920-b614-6915-996c1e0c6b92", "span_id": "f81736f8f49e315b"}}

**Comment by YANGGMM** [comment]
```mysql
drop table if exists rs01;
create table rs01 (col1 int, col2 decimal(6), col3 varchar(30));
insert into rs01 values (1, null, 'database');
insert into rs01 values (2, 38291.32132, 'database');
insert into rs01 values (3, null, 'database management system');
insert into rs01 values (4, 10, null);
insert into rs01 values (1, -321.321, null);
insert into rs01 values (2, -1, null);
select count(*) from rs01;
```

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
未投入

**Comment by daviszhen** [comment]
pr中

**Comment by daviszhen** [comment]
pr中

**Comment by daviszhen** [comment]
pr中

**Comment by daviszhen** [comment]
review中

**Comment by daviszhen** [comment]
pr已经 merge. 等下次复现后再定位。

**Comment by aressu1985** [comment]
先观察，可delay 到2.0.1解决

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现。

**Comment by daviszhen** [comment]
等复现

**Comment by daviszhen** [comment]
等复现

**Comment by daviszhen** [comment]
等复现

**Comment by daviszhen** [comment]
等复现

**Comment by daviszhen** [comment]
xxxWithCause已经加上了。

**Comment by daviszhen** [comment]
xxxWithCause已经加上了。
