### ISSUE TITLE
[Performance]: pipeline connector and dispatch batch dup

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18806]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

Pipeline connector and dispatch allocated lots of memory.    See 
![memoryAllocation](https://github.com/user-attachments/assets/fbabbd21-237a-45dd-9b14-b047bcd2a6cb)

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by fengttt** [comment]
Please verify/confirm that this problem goes away after switch to spool.   Or we need to revisit.

**Comment by m-schen** [comment]
这个应该是spool应用之前抓的profile，
我确定现在的dispatch 和 connector算子都不会调用到batch.Dup()方法。

现在的逻辑是
在buffer满之前开辟内存，后续都复用之前的内存。
当前默认的buffer长度是
1发1: 最多同时容纳2个batch.
1发n: 最多同时容纳n个batch.

但整个过程都不会使用到batch.dup()方法。
因此该issue可以被关闭，后面会提一个提高复用命中率的pr，确保buffer满之前如果有空闲内存，也可以及时使用。

**Comment by m-schen** [comment]
明天找人关，这个是过时的profile，没有这个问题了。
