### ISSUE TITLE
[Performance]: s3writer sortandsync allocate too much memory

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18808]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

s3writer sortandsync allocated too much memory.
![memoryAllocation](https://github.com/user-attachments/assets/dd692b78-df6c-4db8-b6fe-5df3bb2fdf15)

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by fengttt** [comment]
Insert refactor may or may not fix this, so need to verify/validate.

**Comment by ouyuanning** [comment]
DML重构中。等重构结束后再看看

**Comment by ouyuanning** [comment]
等龙冉的分支合并后再观察

**Comment by ouyuanning** [comment]
等龙冉的分支合并后再观察

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
DML重构处理

**Comment by ouyuanning** [comment]
DML重构分支处理会优化这个部分

**Comment by ouyuanning** [comment]
在DML重构分支已处理。改分支合并后就好了

**Comment by ouyuanning** [comment]
在DML重构分支已处理。改分支合并后就好了

**Comment by ouyuanning** [comment]
等这个优化结束后验证
https://github.com/matrixorigin/matrixone/issues/19820

**Comment by ouyuanning** [comment]
从这个issue看，https://github.com/matrixorigin/MO-Cloud/issues/3982
应该已有改善

**Comment by ouyuanning** [comment]
进行中

**Comment by ouyuanning** [comment]
针对以下sql
```
drop table if exists t1;
create table t1(a int, b int, c int, d int, e int, f int,key(b),key(c),key(d),key(e));
insert into t1 select result,result,result,result,result,result from generate_series(1,10000000) g;  //这条
```
重构前：commit ： 173985a3818334e4c36c644f1b7e959838c9293f
<img width="1697" alt="image" src="https://github.com/user-attachments/assets/87f0b311-566d-47d5-84e6-a6c7cd16941e">
sortAndSync   728M，占比56%

重构后，commit：cc1b453d207bbac17bc83958cc3d25c9119e61f0
<img width="1709" alt="image" src="https://github.com/user-attachments/assets/75f13f27-89bd-4fd5-aa5a-339b51936c5e">
sortAndSync   329M，占比36%
