### ISSUE TITLE
[Performance]: scanCsvFile allocate too much memory

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18807]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

![memoryAllocation](https://github.com/user-attachments/assets/3dc55782-380c-4fad-bc33-40155a2ce2fb)

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by huby2358** [comment]
https://github.com/matrixorigin/matrixone/pull/18857，这个pr可以消掉external.getColData里面writestring申请的

**Comment by huby2358** [comment]
没看

**Comment by huby2358** [comment]
未投入

**Comment by huby2358** [comment]
未投入

**Comment by huby2358** [comment]
未投入

**Comment by huby2358** [comment]
还在继续看哪里可以优化

**Comment by huby2358** [comment]
#19422, 
<img width="944" alt="image" src="https://github.com/user-attachments/assets/10f123d4-1232-4a47-b547-deeb439563dc">

**Comment by huby2358** [comment]
#19464, 之前最多会缓存8192行到ParseLineHandler的moCsvLineArray [][]csvparser.Field字段中，然后再一次从moCsvLineArray构造到batch里面，修改为每次读一行，直接放到batch里面，这样省去8192行rows在某段时刻占用的内存改为只占用一行，缓解inuse内存压力
<img width="835" alt="image" src="https://github.com/user-attachments/assets/af24b9ff-9a8b-4b30-a7cd-7493387ef1ea">
inuse堆内内存从8.4Bil优化到6.88Bil

**Comment by jensenojs** [comment]
她在休假

**Comment by huby2358** [comment]
<img width="1684" alt="企业微信截图_a703a915-1fc6-4c0f-95a9-874d6d6cae74" src="https://github.com/user-attachments/assets/5034a255-c0b2-4ef7-8c13-311e3f81443c">

<img width="973" alt="image" src="https://github.com/user-attachments/assets/6285b5a0-3718-468f-b36f-efff3c7c44ca">
readRow方法中，白色部分占比很大，49.39G中占了46.12G，这个主要是因为readRow方法中：str := string(parser.recordBuffer) ，上面截图有显示，这里从byte数组转为string类型，存在内存分配和拷贝，由于这个str是load文件每一行处理后生成的str，也就是这里内存分配是和load文件的大小成正比的，load文件越大，这个alloc space就会越大。
这里有尝试不转为string类型在此处，但是由于后续代码很多地方要转为string类型处理，还是没法避免，改为后续转为string，反而alloc space更多，但是对跑完整个流程时间性能没有什么影响（针对load suwen-001）。

**Comment by huby2358** [comment]
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/9d321590-b26e-4fac-b3a0-9348b5617c92">

**Comment by huby2358** [comment]
<img width="1700" alt="image" src="https://github.com/user-attachments/assets/2f26b9af-a138-42e4-a2fe-bb45534aa7d4">
<img width="681" alt="企业微信截图_b5ce616d-296f-4e8b-8671-0cc55b92d9af" src="https://github.com/user-attachments/assets/d864f39d-7047-44b3-b860-9ee068a79109">
这里消耗主要在go里面提供的strings.genSplit里面

**Comment by huby2358** [comment]
暂无投入

**Comment by huby2358** [comment]
还在继续看

**Comment by huby2358** [comment]
<img width="896" alt="image" src="https://github.com/user-attachments/assets/89c7466d-4ef7-4090-aa97-32b1d690a5ee">

**Comment by huby2358** [comment]
大部分优化已完成，可以关了， 同一个测试，alloc内存从一开始60G左右优化到19G左右，优化了70%左右。

**Comment by fengttt** [comment]
这个并没有完成。  在 #19965 中继续跟踪。
