### ISSUE TITLE
[Feature Request]: Support IS operator in WHERE clause

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1880]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
IS operator is required for NULL. Currently, MO supports NULL value but IS not supported until 0.3.0.
```

### Describe the solution you'd like

IS NULL/IS NOT NULL: check the value is null or not

### Additional information

``` sql
select * from t1 where a is NULL;

select * from t1 where a is NOT NULL;
```

**Comment by m-schen** [comment]
I think we can temporarily use the IsNull function to implement it ? @nnsgmsone

**Comment by fengttt** [comment]
Done and verified.
