### ISSUE TITLE
[Feature Request]: Support subquery in WHERE clause with comparisons

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1882]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
This is the part II of where subquery for MO. It contains IN/EXISTS and comparisons.
```

### Describe the solution you'd like

**Syntax**
``` sql
SELECT select_expr 

FROM table_references

WHERE col_name comparison (subquery)

[GROUP BY {col_name | expr },

[ORDER BY {col_name | expr } [ASC | DESC]
```

Comparison is one of them:

=  >  <  >=  <=  <>  !=  <=>

### Additional information

Example:
``` sql
SELECT * FROM t1 WHERE column1 = (SELECT MAX(column2) FROM t2);
```

**Comment by florashi181** [comment]
this issue will be covered with a new one in v0.5 from source/benchmark, so this one can be closed.
