### ISSUE TITLE
[Feature Request]: Provide binary package for MO in x86_x64 Linux

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1883]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the solution you'd like

Provide binary package for x86_64 Linux.

**Comment by sukki37** [comment]
Although the instruction set of Intel and AMD's x86 architecture CPU is very different, they are still compatible with each other, so the AMD64 version(Already realized, see https://github.com/matrixorigin/matrixone/issues/1777) can be used directly.
