### ISSUE TITLE
[Bug]: big-data-regression: txn leak.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18833]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

48304fdb79f5d6486706f9a4cc965b83781c9c01

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/10905973029/job/30266173781

每次跑都有告警信息
```
【MO-OB】 • mo_logs_long_running • 告警中:1
 
2024-09-18T16:08:27+08:00
详请
当前全部告警
历史告警查询
 
🚨 触发中告警 [1]
 
告警处理人:  @sukki37(秦姝琦) 
 告警名称 : mo_logs_long_running
 告警级别 : 
 命名空间 : mo-big-data-20240917
完整 Label 
alertOwner : shuqi.qin
alertTeam : CN Team
alertname : mo_logs_long_running
alerttype : error-log
namespace : mo-big-data-20240917
node_name : 10.128.0.245
pod : nightly-regression-dis-tp-cn-pm4t7
serviceScope : mo-cluster
severity : ctitical
 告警状态 : 🚨 FIRING
 开始时间 : 2024-09-18T16:08:17+08:00
 结束时间 : Not End
 告警描述 : long running 告警: mo-big-data-20240917/nightly-regression-dis-tp-cn-pm4t7

【MO-OB】 • mo_logs_txn_leak • 告警中:1
 
2024-09-18T16:08:27+08:00
详请
当前全部告警
历史告警查询
 
🚨 触发中告警 [1]
 
告警处理人:  @sukki37(秦姝琦) 
 告警名称 : mo_logs_txn_leak
 告警级别 : 
 命名空间 : mo-big-data-20240917
完整 Label 
alertOwner : shuqi.qin
alertTeam : CN Team
alertname : mo_logs_txn_leak
alerttype : error-log
namespace : mo-big-data-20240917
node_name : 10.128.0.245
pod : nightly-regression-dis-tp-cn-pm4t7
serviceScope : mo-cluster
severity : ctitical
 告警状态 : 🚨 FIRING
 开始时间 : 2024-09-18T16:08:17+08:00
 结束时间 : Not End
 告警描述 : 事务泄漏告警: mo-big-data-20240917/nightly-regression-dis-tp-cn-pm4t7
---

```
---

最新一次测试结果中的long running txn日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Amu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20240917%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221726606157000%22,%22to%22:%221726638645000%22%7D%7D%7D&schemaVersion=1&orgId=1

longrunning对应的goroutine文件：
[big-data.gz](https://github.com/user-attachments/files/17040971/big-data.gz)

### Steps to Reproduce

```Markdown
trigger big data test on tke
```

**Comment by zhangxu19830126** [comment]
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/8151cf36-5a10-47c7-bce6-5e82438c626b">
事务就是执行了很久，事务泄漏检测是20分钟检测一次，所以不是leak

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
```
---
alertOwner : shuqi.qin
alertTeam : CN Team
alertname : mo_logs_txn_leak
alerttype : error-log
namespace : mo-big-data-20241011
node_name : 10.128.0.198
pod : nightly-regression-dis-tp-cn-2vr62
serviceScope : mo-cluster
severity : ctitical
 告警状态 : 🚨 FIRING
 开始时间 : 2024-10-12T17:40:17+08:00
 结束时间 : Not End
 告警描述 : 事务泄漏告警: mo-big-data-20241011/nightly-regression-dis-tp-cn-2vr62
---

```
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Amu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241011%5C%22%7D%20%7C%3D%20%60found%20leak%20txn%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728691200000%22,%22to%22:%221728752400000%22%7D%7D%7D&schemaVersion=1&orgId=1

@daviszhen 帮忙查一下事务泄漏

**Comment by daviszhen** [comment]
未投入

**Comment by Ariznawlll** [comment]
明天重新贴一下leak日志以及相关profile，今天的环境清掉了

**Comment by daviszhen** [comment]
初步看是 disttae panic 然后fe 开始rollback, 然后rollback 内部disttae再次panic. 导致txnoperator 没被清理掉。


![image](https://github.com/user-attachments/assets/11d3c9c9-6e3d-4e5c-99b5-d94a107dfd5c)


https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Amu%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241011%5C%22%7D%20%7C%3D%20%60connectionId%2030455%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728691200000%22,%22to%22:%221728777600000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
@XuPeng-SH 反馈已经修复。https://github.com/matrixorigin/matrixone/pull/19283

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
没再出现了
