### ISSUE TITLE
[Performance]: Memory allocation: shuffle use too much memory

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18844]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

Q18.   
<img width="1106" alt="memProfiling" src="https://github.com/user-attachments/assets/d9e40902-7b97-453c-bff9-4ee1cf48efd7">

shuffle should NOT use that much memory -- copyIntoBatches usage is at least one order of magnitude too much.

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by badboynt1** [comment]
q18的执行计划是没有shuffle join的。  这里的profile一定有问题。  等之后有空我重做个profile

**Comment by badboynt1** [comment]
q18的go堆内分配只有40g左右。 没有shuffle相关的。 之前做的profile肯定还包含了其他query的分配

[root@mo-srv-129 mo-load]# go tool pprof http://127.0.0.1:9876/debug/pprof/allocs
Fetching profile over HTTP from http://127.0.0.1:9876/debug/pprof/allocs
Saved profile in /root/pprof/pprof.mo-service.alloc_objects.alloc_space.inuse_objects.inuse_space.364.pb.gz
File: mo-service
Build ID: a5c2df688398263e0b488198e04583cdf18da116
Type: alloc_space
Time: Sep 20, 2024 at 10:24am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 40684.47MB, 95.71% of 42509.41MB total
Dropped 1424 nodes (cum <= 212.55MB)
Showing top 10 nodes out of 88
      flat  flat%   sum%        cum   cum%
37472.29MB 88.15% 88.15% 37472.29MB 88.15%  github.com/matrixorigin/matrixone/pkg/common/mpool.alloc
 1947.47MB  4.58% 92.73%  1983.44MB  4.67%  github.com/matrixorigin/matrixone/pkg/objectio.LoadObjectMetaByExtent
  519.41MB  1.22% 93.95%   519.41MB  1.22%  github.com/fagongzi/goetty/v2/buf.(*nonReusableAllocator).Alloc
  516.14MB  1.21% 95.17%   516.14MB  1.21%  github.com/lni/dragonboat/v4/raftpb.(*Entry).unmarshal
  180.56MB  0.42% 95.59%   228.06MB  0.54%  github.com/matrixorigin/matrixone/pkg/pb/logservice.(*ConfigData).Unmarshal
      27MB 0.064% 95.66%   570.64MB  1.34%  github.com/lni/dragonboat/v4/raftpb.(*Update).Unmarshal
   16.54MB 0.039% 95.70%   670.72MB  1.58%  github.com/lni/dragonboat/v4/internal/logdb.(*LogReader).entriesLocked
    2.50MB 0.0059% 95.70%   691.92MB  1.63%  github.com/lni/dragonboat/v4.(*engine).processSteps
    2.08MB 0.0049% 95.71%   232.08MB  0.55%  github.com/lni/dragonboat/v4.(*engine).applyWorkerMain
    0.50MB 0.0012% 95.71%   516.39MB  1.21%  net.genericWriteTo
(pprof)

**Comment by badboynt1** [comment]
finished
