### ISSUE TITLE
[Performance]: filter should not allocate too much memory

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#18843]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

TPCH Q18 profiling 
<img width="1106" alt="memProfiling" src="https://github.com/user-attachments/assets/ac90f42e-8491-4479-87c3-2a0e4f8ea253">
 
Significant memory allocation in filter batch.Dup.   

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by fengttt** [comment]
@badboynt1 please check and confirm if we can close this now.

**Comment by badboynt1** [comment]
现在tpch的内存分配正在逐步优化，filter算子里已经没有需要优化的内存了
