### ISSUE TITLE
[Bug]: DATA RACE in TestWWConflict

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#18853]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

afd7c53370cd67a1b21b84e2463ce60702493d06

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DATA RACE
![image](https://github.com/user-attachments/assets/aaf09d3e-4977-4353-a278-82d535f0073c)

### Steps to Reproduce

```Markdown
Run ci.
```

**Comment by daviszhen** [comment]
fixed
