### ISSUE TITLE
[Bug]: create stage which based on minio, load data infile from stage report 'serialization failed: serialization failed: input member Bucket must not be empty'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18859]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c678c5a6908fd9132443478123acc74ddc1653cb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1317" alt="image" src="https://github.com/user-attachments/assets/240a4858-8a85-4ca1-b4d6-ec404d810635">

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/9757af32-1223-4cdc-a5c4-8ddf973cd229">

日志：https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-717cb94-202409191131%5C%22%7D%20%7C%3D%20%60serialization%20failed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221726732859000%22,%22to%22:%221726736159000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Expected Behavior

load 成功

### Steps to Reproduce

```Markdown
1. 创建基于minio的stage：
create stage stage01 url = 's3://stagetest/tpch_10' credentials = {"aws_key_id"='***',"aws_secret_key"='***',"AWS_REGION"='us-east-2','PROVIDER'='minio', 'ENDPOINT'='http://10.222.6.2'};

2. 启动分布式mo（在128服务器上启动的）

3. 创建表
create database tpch_10g;
use tpch_10g;
CREATE TABLE `lineitem` (
  `L_ORDERKEY` bigint NOT NULL,
  `L_PARTKEY` int NOT NULL,
  `L_SUPPKEY` int NOT NULL,
  `L_LINENUMBER` int NOT NULL,
  `L_QUANTITY` decimal(15,2) NOT NULL,
  `L_EXTENDEDPRICE` decimal(15,2) NOT NULL,
  `L_DISCOUNT` decimal(15,2) NOT NULL,
  `L_TAX` decimal(15,2) NOT NULL,
  `L_RETURNFLAG` varchar(1) NOT NULL,
  `L_LINESTATUS` varchar(1) NOT NULL,
  `L_SHIPDATE` date NOT NULL,
  `L_COMMITDATE` date NOT NULL,
  `L_RECEIPTDATE` date NOT NULL,
  `L_SHIPINSTRUCT` char(25) NOT NULL,
  `L_SHIPMODE` char(10) NOT NULL,
  `L_COMMENT` varchar(44) NOT NULL,
  PRIMARY KEY (`L_ORDERKEY`,`L_LINENUMBER`)
);

4. 将stage中的lineitem.tbl load进表中（7.2G）
load data infile 'stage://stage01/lineitem.tbl' into table lineitem fields terminated by '|' lines terminated by '\n' parallel 'true';
```

### Additional information

注：
小数据量的load可以成功（133B）
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/3bc3a4bb-4b5e-4254-a0e5-c936eacb6ffd">

**Comment by cpegeric** [comment]
I cannot reproduce it in my local machine.  TPCH S10 lineitem completed loading with local minio.

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/1643ac25-e2b5-41e2-80dc-e86352aa0d7c">

**Comment by Ariznawlll** [comment]
**main commit: 2f86fead2**

test result：不通过

测试环境：分布式minio部署的mo

测试步骤：

```
create database tpch_10g;
use tpch_10g;
CREATE TABLE PART(
P_PARTKEY     INTEGER NOT NULL,
P_NAME        VARCHAR(55) NOT NULL,
P_MFGR        CHAR(25) NOT NULL,
P_BRAND       CHAR(10) NOT NULL,
P_TYPE        VARCHAR(25) NOT NULL,
P_SIZE        INTEGER NOT NULL,
P_CONTAINER   CHAR(10) NOT NULL,
P_RETAILPRICE DECIMAL(15,2) NOT NULL,
P_COMMENT     VARCHAR(23) NOT NULL,
PRIMARY KEY (P_PARTKEY)
);

create stage stage01 url = 's3://mo-stagetest/test_stage' credentials = {"aws_key_id"='***',"aws_secret_key"='***',"AWS_REGION"='us-east-2','PROVIDER'='minio', 'ENDPOINT'='http://10.222.6.6'};

load data infile 'stage://stage01/part1113.tbl' into table part fields terminated by '|' lines terminated by '\n' parallel 'true';  -->该步骤报错
```

<img width="945" alt="image" src="https://github.com/user-attachments/assets/f9082080-b1c0-4ba7-b0a8-af4dac8e7259">

但是同一个stage，可以成功卸载到minio（说明stage的配置没问题）
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/242ab54a-aa27-43fc-8b3e-ee999b4e07f1">

**Comment by Ariznawlll** [comment]
> I cannot reproduce it in my local machine. TPCH S10 lineitem completed loading with local minio.
> 
> <img alt="image" width="1046" src="https://private-user-images.githubusercontent.com/148623/384397403-1643ac25-e2b5-41e2-80dc-e86352aa0d7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODEwMTksIm5iZiI6MTczMTQ4MDcxOSwicGF0aCI6Ii8xNDg2MjMvMzg0Mzk3NDAzLTE2NDNhYzI1LWUyYjUtNDFlMi04MGRjLWU4NjM1MmFhMGQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwNjUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWUzNDJiYTQyYmVhMWMyN2Y2ZWFiZmI0OTBiOGI4MjNmYTM3ODk5MDgxOWEwYmMyNWFiOGUyMDhhZTExYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nmhv-c1tjSQ0MYye68x1ufV9O6ZrN2hTvdK-IXpLZh8">

local machine cannot reptro this issue

<img width="933" alt="image" src="https://github.com/user-attachments/assets/fa648bd6-67df-4c92-a40a-fd555808fcc2">

**Comment by cpegeric** [comment]
I don't know related or not but  stage01/part1113.tbl and stage02/part.tbl are different formatted CSV.  

<img width="1227" alt="image" src="https://github.com/user-attachments/assets/fff6e0ae-b87f-4221-817e-3f02a8b59369">

**Comment by Ariznawlll** [comment]
> **main commit: [2f86fea](https://github.com/matrixorigin/matrixone/commit/2f86fead29f6f49e719b437b47337de4bf9aef6c)**
> 
> 测试环境：分布式minio部署的mo
> 
> 测试步骤：
> 
> ```
> create database tpch_10g;
> use tpch_10g;
> CREATE TABLE PART(
> P_PARTKEY     INTEGER NOT NULL,
> P_NAME        VARCHAR(55) NOT NULL,
> P_MFGR        CHAR(25) NOT NULL,
> P_BRAND       CHAR(10) NOT NULL,
> P_TYPE        VARCHAR(25) NOT NULL,
> P_SIZE        INTEGER NOT NULL,
> P_CONTAINER   CHAR(10) NOT NULL,
> P_RETAILPRICE DECIMAL(15,2) NOT NULL,
> P_COMMENT     VARCHAR(23) NOT NULL,
> PRIMARY KEY (P_PARTKEY)
> );
> 
> create stage stage01 url = 's3://mo-stagetest/test_stage' credentials = {"aws_key_id"='***',"aws_secret_key"='***',"AWS_REGION"='us-east-2','PROVIDER'='minio', 'ENDPOINT'='http://10.222.6.6'};
> 
> load data infile 'stage://stage01/part1113.tbl' into table part fields terminated by '|' lines terminated by '\n' parallel 'true';  -->该步骤报错
> ```
> 
> <img alt="image" width="945" src="https://private-user-images.githubusercontent.com/108530700/385633581-f9082080-b1c0-4ba7-b0a8-af4dac8e7259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDk1MDcsIm5iZiI6MTczMTU0OTIwNywicGF0aCI6Ii8xMDg1MzA3MDAvMzg1NjMzNTgxLWY5MDgyMDgwLWIxYzAtNGJhNy1iMGE4LWFmNGRhYzhlNzI1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMTUzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjgwNjBjODI0M2Y3ZjMyNzY3M2ZhMWU4ZWU0NDBjZmI2ZjdiYjkzYjFjNzI3MGQ3ZDA2MjljNjNhYmZkYWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2pbNLiVvv-8iP4dzqMbXc8fYDFGe-lso89bmfa5degE">
> 但是同一个stage，可以成功卸载到minio（说明stage的配置没问题） <img alt="image" width="945" src="https://private-user-images.githubusercontent.com/108530700/385635629-30bbc714-3829-4d78-a595-7865580164e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDk1MDcsIm5iZiI6MTczMTU0OTIwNywicGF0aCI6Ii8xMDg1MzA3MDAvMzg1NjM1NjI5LTMwYmJjNzE0LTM4MjktNGQ3OC1hNTk1LTc4NjU1ODAxNjRlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMTUzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWE2NDc5NTExMWRiMmE4YzNiZTFkMjFhODMzMTU2ZDBlMGU1YjM2ZmYxN2U2OTk0YTFlZGI1M2FkNjBlM2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Lzc016FuJweAKxhxFKjKtNYvIgDAvZ1XgQ7Bjra-hfI">
> 
> <img alt="image" width="1179" src="https://private-user-images.githubusercontent.com/108530700/385635803-e146bf97-7cc2-45d9-86f5-19b7fdc963fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDk1MDcsIm5iZiI6MTczMTU0OTIwNywicGF0aCI6Ii8xMDg1MzA3MDAvMzg1NjM1ODAzLWUxNDZiZjk3LTdjYzItNDVkOS04NmY1LTE5YjdmZGM5NjNmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMTUzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzFkNzI3MTAzZWRmNzI0MGZmMjRhZTljNzEyYzNmNDZkYzg3M2FiNzYzNTk5NDlkZWE4ODk4ZWJmYzkwNzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z3abWgxWkO0fq3bxuFWyhOSRFXTjPjsdn5AFYpYnM3M">
> log：https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60convert%20go%20error%20to%20mo%20error%20operation%20error%20S3%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731480000000%22,%22to%22:%221731481980000%22%7D%7D%7D&schemaVersion=1&orgId=1
> 
> without stage: <img alt="image" width="726" src="https://private-user-images.githubusercontent.com/108530700/385695069-cab10123-2f81-4965-a8cc-1c6b6ae7c39a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDk1MDcsIm5iZiI6MTczMTU0OTIwNywicGF0aCI6Ii8xMDg1MzA3MDAvMzg1Njk1MDY5LWNhYjEwMTIzLTJmODEtNDk2NS1hOGNjLTFjNmI2YWU3YzM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMTUzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDRiODc0OThhOTg3YWE5YmM2MWY3Y2NlZmI2NjAxZTIyYzgwMWM1NjVjNWNmOTY4NWQxZDAxMjAxYmQwYTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fq51ZmDykcA6F5owpGg-eI7HMDHIHAwC2ymmDnLC5XE">
> 
> **测试结论：不通过**

main commit:2f86fead2

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/2ede250b-6c10-4a81-8dff-3df92e282d2d">

由于两个.tbl的格式不一样，之前的测试没有成功load，现在可以了

结论：测试通过
