### ISSUE TITLE
[Tech Request]: put encrypted related info the config file or other plan

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#18877]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
把加密相关的信息放到cn的配置文件中 或 用其他方案。
```

**Comment by heni02** [comment]
confirm,closed
commit:f9b8368
<img width="1387" alt="企业微信截图_be134c98-5d35-4bc8-9d24-2d1811b79014" src="https://github.com/user-attachments/assets/1318d99e-ed25-4338-9503-daef39d1c308">
<img width="1241" alt="企业微信截图_258c5366-1b28-4969-a4bd-5972ac6396dc" src="https://github.com/user-attachments/assets/3dbbc03c-80fe-4f06-83ce-bf4a51ece6f6">
