### ISSUE TITLE
[Feature Request]: Make MO compatible to mysqldump

### ISSUE THREAD

**Issue by wanhanbo** [matrixorigin/matrixone#1888]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
MO needs a tool for export both metadata and data in daily work.
```

### Describe the solution you'd like

Can use mysqldump to export metadata or data with mysqldump as following.
``` 
# mysqldump [options] db_name [tbl_name ...] 

# mysqldump [options] --databases db_name ... 

# mysqldump [options] --all-databases
```

More details can be followed MySQL doc.

https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

### Additional information

https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

**Comment by domingozhang** [comment]
will raise a requirement for unique tool of mo
