### ISSUE TITLE
[Bug]: mo_cdc: source_uri which is account:user:role format can not resolved

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18894]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

786f7bb50

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.source-uri is "mysql://sys:dump:accountadmin:111@10.222.6.6:6001"can not resolved
./mo_cdc task create --task-name cdc2 --source-uri="mysql://sys:dump:accountadmin:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables="testdb.customer:test_cdc_db.CUSTOMER" --level="account"  --account="sys"
Error: invalid configuration: connect mo failed: Error 20101 (HY000): internal error: there is no user sys

2.source-uri is "mysql://sys#dump#accountadmin:111@10.222.6.6:6001" also can not resolved
./mo_cdc task create --task-name cdc2 --source-uri="mysql://sys#dump#accountadmin:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables="testdb.customer:test_cdc_db.CUSTOMER" --level="account"  --account="sys"
Error: invalid configuration: connect mo failed: dial tcp: lookup sys on 10.222.0.1:53: no such host

source-uri is "mysql://dump:111@10.222.6.6:6001" is success
./mo_cdc task create --task-name cdc2 --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables="testdb.customer:test_cdc_db.CUSTOMER" --level="account"  --account="sys"
OK

### Steps to Reproduce

```Markdown
./mo_cdc task create --task-name cdc2 --source-uri="mysql://sys:dump:accountadmin:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables="testdb.customer:test_cdc_db.CUSTOMER" --level="account"  --account="sys"

./mo_cdc task create --task-name cdc2 --source-uri="mysql://sys#dump#accountadmin:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables="testdb.customer:test_cdc_db.CUSTOMER" --level="account"  --account="sys"
```

**Comment by ck89119** [comment]
case 1已修复
case 2 mo_cdc依赖的url解析库不支持#，不要这么用吧，就用冒号

**Comment by heni02** [comment]
还是报错internal error: no data key
<img width="1380" alt="企业微信截图_87376b25-c43c-49a9-a911-6be7535562d7" src="https://github.com/user-attachments/assets/3b92b769-aa1c-43e9-8ddb-758d03daa689">

**Comment by ck89119** [comment]
已知问题，#18923和#18942修复了，试下最新的main

**Comment by heni02** [comment]
confirm,closed
commit:b0855d26f
1.ac1:admin:111格式
[root@mo-srv-128 mo-backup]# ./mo_cdc task create --task-name "cdc_6yi" --source-uri="mysql://ac1:admin:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables='test_db.lineitem:back_ac1_db.LINEITEM' --level="account"  --account="ac1"
OK

2.ac1:admin:accountadmin:111
[root@mo-srv-128 mo-backup]# ./mo_cdc task create --task-name "cdc_6yi01" --source-uri="mysql://ac1:admin:accountadmin:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables='test_db.lineitem:back_ac1_db.LINEITEM' --level="account"  --account="ac1"
OK
