### ISSUE TITLE
[Bug]: cannot insert with default UUID() as primary key

### ISSUE THREAD

**Issue by cpegeric** [matrixorigin/matrixone#18895]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f9b2b2986c858c0b2efe8e62db8fb725877c82e8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: macos
- Others:
```

### Actual Behavior

mysql> CREATE TABLE namelists (
    ->     id UUID DEFAULT uuid() PRIMARY KEY, -- the id field is of UUID type, and the default value is the UUID value generated by the uuid() function as the primary key 
    ->     name VARCHAR NOT NULL -- the name field is of type VARCHAR and cannot be empty
    -> );
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO namelists (name) VALUES ('Tom'), ('Jane'), ('Bob');
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:900
github.com/matrixorigin/matrixone/pkg/sql/plan.ConstantFold
	/Users/eric/github/matrixone/pkg/sql/plan/utils.go:1109
github.com/matrixorigin/matrixone/pkg/sql/plan.getPkValueExpr
	/Users/eric/github/matrixone/pkg/sql/plan/build_insert.go:872
github.com/matrixorigin/matrixone/pkg/sql/plan.buildInsertPl

### Expected Behavior

The test case is the example from official document.  https://docs.matrixorigin.cn/en/1.1.0/MatrixOne/Reference/Data-Types/uuid-type/#examples 

-- Create a table named namelists with two fields, id and name
CREATE TABLE namelists (
    id UUID DEFAULT uuid() PRIMARY KEY, -- the id field is of UUID type, and the default value is the UUID value generated by the uuid() function as the primary key
    name VARCHAR NOT NULL -- the name field is of type VARCHAR and cannot be empty
);
INSERT INTO namelists (name) VALUES ('Tom'), ('Jane'), ('Bob');
mysql> select * from namelists;
+--------------------------------------+--------+
| id                                   | name   |
+--------------------------------------+--------+
| 61400e9c-1bbc-11ee-b512-5ad2460dea50 | Tom    |
| 61400ea6-1bbc-11ee-b512-5ad2460dea50 | Jane   |
| 61400ea6-1bbc-11ee-b513-5ad2460dea50 | Bob    |
+--------------------------------------+--------+
3 rows in set (0.00 sec)

### Steps to Reproduce

```Markdown
CREATE TABLE namelists (
    id UUID DEFAULT uuid() PRIMARY KEY, -- the id field is of UUID type, and the default value is the UUID value generated by the uuid() function as the primary key
    name VARCHAR NOT NULL -- the name field is of type VARCHAR and cannot be empty
);
INSERT INTO namelists (name) VALUES ('Tom'), ('Jane'), ('Bob');
mysql> select * from namelists;
```

**Comment by YANGGMM** [comment]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/f68ca9a9-a155-4043-a735-ed0db2a95b22">

是因为bind出来的filterExpr 为nil

**Comment by YANGGMM** [comment]
merge, plz test @aressu1985

**Comment by aressu1985** [comment]
fixed

**Comment by aressu1985** [comment]
mysql> CREATE TABLE namelists (
    ->     id UUID DEFAULT uuid() PRIMARY KEY, -- the id field is of UUID type, and the default value is the UUID value generated by the uuid() function as the primary key
    ->     name VARCHAR NOT NULL -- the name field is of type VARCHAR and cannot be empty
    -> );
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO namelists (name) VALUES ('Tom'), ('Jane'), ('Bob');
Query OK, 3 rows affected (0.04 sec)

mysql> select * from namelists;
+--------------------------------------+------+
| id                                   | name |
+--------------------------------------+------+
| 019223e8-1a4c-7e09-a224-e3be03b91d31 | Tom  |
| 019223e8-1a4c-7e0a-8b3b-a0661a3354a1 | Jane |
| 019223e8-1a4c-7e0d-b07e-b6cfc181f0a7 | Bob  |
+--------------------------------------+------+
3 rows in set (0.00 sec)

mysql> insert into namelists values(uuid(),'Jhon');
Query OK, 1 row affected (0.02 sec)

mysql> select * from namelists;
+--------------------------------------+------+
| id                                   | name |
+--------------------------------------+------+
| 019223e8-1a4c-7e09-a224-e3be03b91d31 | Tom  |
| 019223e8-1a4c-7e0a-8b3b-a0661a3354a1 | Jane |
| 019223e8-1a4c-7e0d-b07e-b6cfc181f0a7 | Bob  |
| 019223e8-9cd2-738a-b7e1-13b492c1a676 | Jhon |
+--------------------------------------+------+
4 rows in set (0.00 sec)
