### ISSUE TITLE
[Bug]: overall issue: refine error info for cdc

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#18911]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
提供更明确的cdc报错信息：
“now it is Paused 最后这句改一下，有歧义”

“status can not be changed. now it is paused”
```

**Comment by heni02** [comment]
confirm, closed
commit:f9b8368
[root@mo-srv-128 mo-backup]# ./mo_cdc task pause --task-name "cdc_6yi" --source-uri="mysql://dump:111@10.222.6.6:6001"
Error: invalid configuration: pause CDC task failed: Error 20101 (HY000): internal error: Task cdc_6yi status can not be change, now it is Paused
