### ISSUE TITLE
[Bug]: ut TestSendAny failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#18919]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

link: https://github.com/matrixorigin/matrixone/actions/runs/10971146221/job/30467123008?pr=18897

log: 
[job-logs.txt.zip](https://github.com/user-attachments/files/17084117/job-logs.txt.zip)

### Steps to Reproduce

```Markdown
make ut
```

**Comment by reusee** [comment]
fixed
