### ISSUE TITLE
[Bug]: unknown error:EOF during SSB in mo cluster 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1894]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):56fcd3ff8e4aa3b5a8b9d08c420fa90f7462c579
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In a three nodes cluster, I was notified "unknown error:EOF " during a SSB query.

![image](https://user-images.githubusercontent.com/88298673/158097989-e76b5ad2-3011-45c4-ba9c-42ce6552da53.png)

[mo.log](https://github.com/matrixorigin/matrixone/files/8241448/mo.log)

**Comment by m-schen** [comment]
maybe encode or decode bug. ？
