### ISSUE TITLE
[Bug]: Error occurs when running prepare statements

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#18957]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

v1.2.3-79a3dd59e-2024-09-23

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> prepare __mo_stmt_id_14 from INSERT INTO `billing`.`billing_time` (`instance_id`,`last_time`,`created_at`,`updated_at`) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE `updated_at`=?,`last_time`=VALUES(`last_time`) ;
Query OK, 0 rows affected (0.08 sec)

mysql> set @id='01910c93-edee-768f-a651-8c26f218593d';
Query OK, 0 rows affected (0.07 sec)

mysql> set @last_time='2024-09-11 01:00:00';
Query OK, 0 rows affected (0.09 sec)

mysql> set @created_at='2024-09-24 03:18:58.724';
Query OK, 0 rows affected (0.03 sec)

mysql> set @updated_at='2024-09-24 03:18:58.724';
Query OK, 0 rows affected (0.19 sec)

mysql> execute __mo_stmt_id_14 using @id,@last_time,@created_at,@updated_at,@updated_at;
ERROR 20101 (HY000): internal error: get prepare params error, index 5 not exists
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by heni02** [comment]
已添加bvtcase，closed

**Comment by heni02** [comment]
confirm,closed
1.2-dev commit:f89ad17352ee036cfc59fe44f308eb71108754a8
mysql> create table billing_time(`instance_id` int,`last_time` datetime,`created_at` datetime,`updated_at` datetime);
Query OK, 0 rows affected (0.04 sec)

mysql> prepare __mo_stmt_id_14 from INSERT INTO `billing_time` (`instance_id`,`last_time`,`created_at`,`updated_at`) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE `updated_at`=?,`last_time`=VALUES(`last_time`) ;
Query OK, 0 rows affected (0.00 sec)

mysql> set @instance_id='234254565';
Query OK, 0 rows affected (0.00 sec)

mysql> set @last_time='2024-09-11 01:00:00';
Query OK, 0 rows affected (0.00 sec)

mysql> set @created_at='2024-09-24 03:18:58.724';
Query OK, 0 rows affected (0.01 sec)

mysql> set @updated_at='2024-09-24 03:18:58.724';
Query OK, 0 rows affected (0.00 sec)

mysql> execute __mo_stmt_id_14 using @instance_id,@last_time,@created_at,@updated_at,@updated_at;
Query OK, 1 row affected (0.02 sec)
