### ISSUE TITLE
[Bug]:mo_cdc: Data consistency  error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18964]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a77a7350e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

测试场景：上游mo运行tpcc100仓1000并发测试15分钟，测试停止后1个小时验证下游mysql数据是否和上游数据一致
测试数据：tpcc 100仓一共10个表
测试现象：使用tpcc验证一致性的几个sql验证下游mysql数据返回结果和mo上游不一致
测试环境：上游mo minio 3cn，下游mysql单机

MO验证sql返回结果：（以下是预期结果）
<img width="1544" alt="企业微信截图_6a6532d5-00a6-4fcc-bc3d-16be48877dfd" src="https://github.com/user-attachments/assets/1abf4c54-5216-4168-a724-4b4d8ce5d888">

mysql验证sql返回结果：（预期应该返回0行）
<img width="1253" alt="企业微信截图_d6bc35de-4bc3-4ab0-bd41-65fc9cd09ada" src="https://github.com/user-attachments/assets/9c86b1c3-a524-49c0-b368-89f3276ad1f9">
<img width="1533" alt="企业微信截图_0dada306-090a-4283-8f63-0cb8066372cb" src="https://github.com/user-attachments/assets/de224a20-e288-4394-9f81-710842f08e85">
<img width="1544" alt="企业微信截图_d69773c4-a18d-4108-b2e1-5d266b57d7db" src="https://github.com/user-attachments/assets/d5ab5eb5-c211-47e7-83e2-4cba6e51dd3e">

同步任务信息：
<img width="1544" alt="企业微信截图_1c9a5c48-f5f3-4d28-8138-8394f092be73" src="https://github.com/user-attachments/assets/aa10147a-1945-4ef7-ba39-051f44170748">

mo log：
http://10.222.6.1/explore?panes=%7B%22IjV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727150587995%22,%22to%22:%221727157760260%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1.mo使用mo-load-data工具加载tpcc100仓数据
 a.修改mo-load-data/access.yml文件，更新三个参数，具体值联系我
 b.执行命令加载数据：./load.sh -h 10.222.6.6 -c cases/02_from_cos/tpcc_100 -r -m
2.创建下游数据tpcc的10个表，ddl：https://github.com/matrixorigin/mo-load-data/tree/main/ddl/tpcc_no_partition
3.创建同步任务：
./mo_cdc task create --task-name "cdc_tpcc" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables='tpcc_100.bmsql_config:test_cdc_db.bmsql_config,tpcc_100.bmsql_customer:test_cdc_db.bmsql_customer,tpcc_100.bmsql_district:test_cdc_db.bmsql_district,tpcc_100.bmsql_history:test_cdc_db.bmsql_history,tpcc_100.bmsql_item:test_cdc_db.bmsql_item,tpcc_100.bmsql_new_order:test_cdc_db.bmsql_new_order,tpcc_100.bmsql_oorder:test_cdc_db.bmsql_oorder,tpcc_100.bmsql_order_line:test_cdc_db.bmsql_order_line,tpcc_100.bmsql_stock:test_cdc_db.bmsql_stock,tpcc_100.bmsql_warehouse:test_cdc_db.bmsql_warehouse' --level="account"  --account="sys"
4.mo端使用mo-tpcc工具进行测试
a.修改mo-tpcc/props.mo里的conn，warehouses=100，terminals=1000，runMins=15值
b.执行测试：./runBenchmark.sh props.mo
5.tpcc测试结束后等待一段时间执行以下验证sql
(Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);


(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);


(Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);

(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);


(select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
```

**Comment by ck89119** [comment]
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/e45f7a34-4274-4977-b1f5-bab45d389321">

**Comment by ck89119** [comment]
加log排查，对一张只有update操作的表，发现读取某个时间段的insert和delete条数不一致

```
{"level":"ERROR","time":"2024/09/26 16:48:03.802503 +0800","caller":"cdc/reader.go:250","msg":"tableReader(bmsql_district)[1727340075084572000-1, 1727340476266060000-1] addTailEndStatistics: insert record count=4856, delete record count=4879"}
```

**Comment by ck89119** [comment]
经过与存储同事的沟通，是接收数据排序上两边不一致，修改中

**Comment by heni02** [comment]
confirm,closed
commit:48898692b
<img width="1400" alt="企业微信截图_be97befa-c55a-4676-bef3-ed2d99d3f12c" src="https://github.com/user-attachments/assets/cd44e0d4-d70e-48d9-9cbe-b56fe426f0c2">
<img width="1395" alt="企业微信截图_dd9a465e-2e88-46d8-b22d-647084d598ec" src="https://github.com/user-attachments/assets/0cf671e0-39f8-4b42-ab21-22d205b64449">
<img width="1401" alt="企业微信截图_beef5b46-3a03-4219-bfd4-86d2486ce330" src="https://github.com/user-attachments/assets/1b24c2a5-5593-4496-9de4-fc0b41224283">
