### ISSUE TITLE
[Bug]: TestLockTableBindChanged ci ut fail

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#18976]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="906" alt="image" src="https://github.com/user-attachments/assets/08157a8a-240b-4143-86e6-00a898a01702">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11010954358/job/30573995712?pr=18961
```

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
[正在处理](https://github.com/matrixorigin/matrixone/pull/19412)

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19412
