### ISSUE TITLE
[Bug]: optimize timestamp in error reported after restore.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#18977]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f263342d72048d5cb44e395dd7f9d9b594dfca1a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="854" alt="image" src="https://github.com/user-attachments/assets/eea76255-2a2d-484d-aded-28fc4ca860c7">

### Expected Behavior

展示成具体的时间戳

### Steps to Reproduce

```Markdown
1.create database test;
use test;
create table t1(col1 int, col2 int);
create pitr p01 for database test table t1 rang 1 'h';

after 1h

2. drop table t1;
3. select now();
4. restore database test table t1 from pitr p01 '步骤3中的time';
```

**Comment by YANGGMM** [comment]
finished, plz test @Ariznawlll

**Comment by Ariznawlll** [comment]
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/d4e4fbe1-7905-4cd9-a4e5-c20642c494ee">

**verified**
