### ISSUE TITLE
[Bug]: 1.2-dev standalone regression: create db.table reported error invalid database which database already exists 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#18989]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

acc56f35d3098294466a6a3abc694dfb66a9dfa

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11016035984/job/30590859362
<img width="1358" alt="企业微信截图_f6138bcc-62ac-400b-a1bb-fa6f1454152a" src="https://github.com/user-attachments/assets/d5223183-4658-43be-ad51-6a4dd0bdb569">

mo log：
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-acc56f3-20240924-223643.log%5C%22%7D%20%7C%3D%20%60invalid%20database%20tpch_1g%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727167244199%22,%22to%22:%221727253644199%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
standalone regression
```

**Comment by heni02** [comment]
相关问题 https://github.com/matrixorigin/MO-Cloud/issues/4091

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
{"level":"ERROR","time":"2024/09/30 01:41:35.168297 +0800","name":"cn-service","caller":"frontend/util.go:517","msg":"query trace status","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"create database if not exists tpch_1g","status":"fail","error":"cannot commit a orphan transaction","txn_info":"70f70f4866a9b62a17f9bd617cbc332c:1727631695164169074-1","session_info":"connectionId 27961\|\|account sys:dump\|goRoutineId 0\|migrate-goRoutineId 0\|01923edf-9d38-7053-a0d5-201ce2210c6a","role":"moadmin","session_id":"01923edf-9d38-7053-a0d5-201ce2210c6a","statement_id":"01923edf-9d3b-7b24-b648-c3c4b43da860","span":{"trace_id":"e04127f6-31d5-319b-77a7-03d06b112a63","span_id":"c90a4d43ae5a7094"}}
--


<br class="Apple-interchange-newline">

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19250

**Comment by heni02** [comment]
待测试验证

**Comment by heni02** [comment]
1.2暂时不测试先关闭，2.0和main没有再出现
