### ISSUE TITLE
[Bug]: TestPrepareClient ut fail

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#18990]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/a102b921-5807-4488-9a26-71a47f24d8f6)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11023764911/job/30617649065?pr=18961
```

**Comment by volgariver6** [comment]
fixed
