### ISSUE TITLE
[Bug]: mo_cdc: cdc status which is stopped  an hour，mo memory not released

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19009]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

326c9fb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.5亿表数据同步后，pasue同步任务状态为stopped，之后20分钟后cn内存还是一直没有释放
http://10.222.6.1/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-cdc-test&from=1727250616912&to=1727258042167
<img width="1891" alt="企业微信截图_029f3e38-54e1-47a8-b669-d3bd03abd576" src="https://github.com/user-attachments/assets/4030c679-dc42-40b1-9bc6-0f21f4ff6508">

profile：
[CN_32373539-6130-3061-3965-383366316131_heap_0192288a-4114-7b87-9687-01f8b2b3cdb9.gz](https://github.com/user-attachments/files/17128954/CN_32373539-6130-3061-3965-383366316131_heap_0192288a-4114-7b87-9687-01f8b2b3cdb9.gz)

http://10.222.6.1/explore?panes=%7B%2230B%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22,pod%3D%5C%22stability-regression-dis-tp-cn-gkc8q%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:alloc_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-30m%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1.5亿表数据同步后，pasue同步任务状态为stopped,观察上游mo内存释放情况
```

**Comment by heni02** [comment]
commit: b0855d26f
同步6亿数据，发现同步结束10个小时后内存没有释放
<img width="1219" alt="企业微信截图_a130ba80-3524-4f63-9dc5-dd9cc844abae" src="https://github.com/user-attachments/assets/35357672-fe6c-4279-801b-3fb641a68d7f">
http://10.222.6.1/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-cdc-test&from=1728358805000&to=1728455525000

**Comment by ck89119** [comment]
分析抓取的profile
<img width="980" alt="image" src="https://github.com/user-attachments/assets/ecc935cb-3e30-4de7-875a-eaa876750b0e">

发现总的占用才几百MB，cdc相关的只有64MB，是sinker预分配用于生成sql的缓冲区。

**Comment by aressu1985** [comment]
@daviszhen 需要和乐声在一起看下

**Comment by ck89119** [comment]
heap文件和机器监控的内存占用不一致可能是有堆外内存分配，分析中

**Comment by ck89119** [comment]
将cdc任务使用的mpool单独拿出来，增加metric，继续观察

**Comment by ck89119** [comment]
经与yuesheng沟通，堆外内存使用完会cache在内存中，直到达到配置的大小

机器监控cn内存使用没有下降：
<img width="1767" alt="image" src="https://github.com/user-attachments/assets/09a75def-f284-46db-b652-8d1a3d273ec2">

堆外内存cache监控：
![image](https://github.com/user-attachments/assets/e1f4f9b6-cf06-4c5c-ab5c-ed392647eea7)

**Comment by ck89119** [comment]
待测试

**Comment by heni02** [comment]
6亿行数据75G同步结束后23:32:00后内存使用状态，3个cn都没有下降的趋势，确认是否正常
<img width="449" alt="企业微信截图_2c78bb0e-d6fa-4220-9905-07f289b7a16a" src="https://github.com/user-attachments/assets/5db35694-8dfe-41ba-8b3b-b2d899ccdfc4">
<img width="1859" alt="企业微信截图_1aad31a7-0b0a-4208-b1ef-862236c150e7" src="https://github.com/user-attachments/assets/e2ea8dd6-4dae-428e-9995-fef6babf44e8">
内存监控：
https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1729799181589&to=1729825602348&var-datasource=prometheus&var-cluster=&var-namespace=mo-cdc-test

**Comment by daviszhen** [comment]
从目前的问题看，不是cdc的问题。

**Comment by heni02** [comment]
confirm，closed
