### ISSUE TITLE
[Feature Request]: snapshot_size or pitr_size in show accounts.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19000]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
数据存储空间
可以查看到所有备份（快照备份及 PITR）的数据存储大小，show accounts 中只有当前数据的  ，还需要加上因备份功能而锁住的存储空间，用于计费。列名：snapshot_size；单位：MB（与size一致）
注意：实例的总存储大小 = 当前数据大小（即 size） + 所有备份存储大小（即snapshot_size) + 未被 GC 的存储大小（还未来得及被 GC掉的数据，这部分数据是由于我们 GC 不及时导致，因此不会统计也不会纳入计费范围）
```

### Describe the feature you'd like

<img width="900" alt="企业微信截图_33a53351-0b36-4efc-ae7a-30fefd834f6a" src="https://github.com/user-attachments/assets/1e15bb1c-f1c7-4f12-a171-f54b7c440dcb">

**Comment by LeftHandCold** [comment]
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/03995331-ea56-45f6-aa83-cb03dd309a61">

**Comment by LeftHandCold** [comment]
done

**Comment by Ariznawlll** [comment]
test done
