### ISSUE TITLE
[Bug]: mo_cdc: drop cdc task error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19006]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

326c9fb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

创建一个cdc任务到下游mysql，日志报表不存在，之后drop该任务成功，再创建同名的cdc任务（表存在的），mo日志还是报之前的表不存在
<img width="1430" alt="企业微信截图_5c36ed45-774d-4081-b748-bc9c69e28cf7" src="https://github.com/user-attachments/assets/e2b082d2-ee4f-4787-a038-87b24cd07d4f">
<img width="1840" alt="企业微信截图_f60ab064-80fd-44f1-a29d-ea657f7a46c1" src="https://github.com/user-attachments/assets/4e47dd0b-928d-4960-a1a3-11d73c06e01c">
<img width="1430" alt="企业微信截图_5c36ed45-774d-4081-b748-bc9c69e28cf7" src="https://github.com/user-attachments/assets/faede072-d07e-48ad-b2be-4cbac0d0ff4c">

然后新创建的同步任务后下游有同步数据
<img width="422" alt="企业微信截图_7a30e367-6585-4f25-9807-b5d6e9ccba6b" src="https://github.com/user-attachments/assets/bacfac3b-8891-4942-97cd-450e2c39b320">

### Steps to Reproduce

```Markdown
创建下游表不存在的任务（下游表名是大写，上游表是小写）
./mo_cdc task create --task-name "cdc_orders" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables='tpch_100g.orders' --level="account"  --account="sys"

./mo_cdc task pause --task-name "cdc_orders" --source-uri="mysql://dump:111@10.222.6.6:6001"

./mo_cdc task show --task-name "cdc_orders" --source-uri="mysql://dump:111@10.222.6.6:6001"

./mo_cdc task drop --task-name "cdc_orders" --source-uri="mysql://dump:111@10.222.6.6:6001"

创建下游正确的表名同步任务：
./mo_cdc task create --task-name "cdc_orders" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables='tpch_100g.orders:tpch_100g.ORDERS' --level="account"  --account="sys"
```

**Comment by ck89119** [comment]
找到问题原因，是删除cdc任务的时候，没有停止对下游的写入，仍在不停重试。

处理中

**Comment by heni02** [comment]
confirm,closed
commit:f9b8368
<img width="1487" alt="企业微信截图_741347e0-97c4-4d15-ab91-b9205959f24d" src="https://github.com/user-attachments/assets/83cd914c-9967-4968-abf0-da202d11b602">
