### ISSUE TITLE
[Bug]: cdc txn leak

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19013]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/dd016f7e-a014-40f8-9598-2c1c575e3b10)

http://10.222.6.1/explore?panes=%7B%22IjV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60found%20leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727231285102%22,%22to%22:%221727274485102%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
http://10.222.6.1/explore?panes=%7B%22IjV%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60found%20leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727231285102%22,%22to%22:%221727274485102%22%7D%7D%7D&schemaVersion=1&orgId=1
```

**Comment by daviszhen** [comment]
[CN_39343139-3538-6134-3130-666439363864_leakcheck_routine_019228bf-5b40-72d6-9d92-fe1dbb796ae9.gz](https://github.com/user-attachments/files/17141955/CN_39343139-3538-6134-3130-666439363864_leakcheck_routine_019228bf-5b40-72d6-9d92-fe1dbb796ae9.gz)

**Comment by ck89119** [comment]
先处理其它正确性和性能问题，还没开始看

**Comment by ck89119** [comment]
pr中

**Comment by ck89119** [comment]
待验证

**Comment by daviszhen** [comment]
已经解决
