### ISSUE TITLE
[Bug]: TPMC decreased more than 25 % in daily regression 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19026]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7a04342ac26fb2392dd7259f70c1a8500427f35e

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11016020437/job/30600444014
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/227d0f88-64af-4cb9-b11c-8f0fbff15e7a">

profile:
<img width="1753" alt="WeChatWorkScreenshot_e7f91fbb-efcb-45d2-8ff1-5a74f80897eb" src="https://github.com/user-attachments/assets/b49c1bad-2680-4db3-b74d-758b2410563e">

<img width="1763" alt="WeChatWorkScreenshot_46643f53-89d7-4d25-b6f4-74db3c14f9d2" src="https://github.com/user-attachments/assets/5d0bb8f2-7587-4b1a-bda7-0ce09119fcc3">

### Steps to Reproduce

```Markdown
DAILY REGERSSION
```

**Comment by ouyuanning** [comment]
暂时没有复现
正常commit：bdc147b00ae650ba1545ea34b16c19a3bd242b27
https://github.com/matrixorigin/mo-auto-test/actions/runs/11047777822/job/30689882838
10.10：   	3218.65
100.100 ： 	18698.03
500.500：   12146.71
1000.1000:  8875.01


回退commit：7a04342ac26fb2392dd7259f70c1a8500427f35e
https://github.com/matrixorigin/mo-auto-test/actions/runs/11048820923/job/30693111932
10.10：   	3475.85
100.100 ： 	18660.14
500.500：   12192.09
1000.1000:  8846.37

**Comment by ouyuanning** [comment]
未投入

**Comment by ouyuanning** [comment]
未复现

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by aressu1985** [comment]
gc参数改回来后，问题解决，fixed
