### ISSUE TITLE
[Bug]: mo_cdc: mo vector type cdc to mysql text is Inconsistence

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19037]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

326c9fb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

上游mo vector类型数据同步到下游mysql text类型，数据不一致，两者对比数据像浮点类型精度不一样
<img width="832" alt="企业微信截图_6d9e1b80-3048-495e-a5bb-d7ae96f11b3b" src="https://github.com/user-attachments/assets/f9028e06-a4d7-4790-a8cf-4b88e1d7b79b">
ddl:
<img width="516" alt="企业微信截图_c12dd877-3756-4c50-9b08-52aaf55ff635" src="https://github.com/user-attachments/assets/1589938e-4590-41bb-b8e9-b16c86ff8538">

下游到mysql的数据：
<img width="946" alt="企业微信截图_7159a5ee-c05c-4345-bc5b-d2f67b773ff5" src="https://github.com/user-attachments/assets/4ecf4b12-0224-4d12-ba80-622b84dd59fa">
ddl:
<img width="669" alt="企业微信截图_4bb80874-c013-4be5-881b-2af29fea7b32" src="https://github.com/user-attachments/assets/6e86d316-b114-4c02-9d09-7f7d08b22c71">

### Steps to Reproduce

```Markdown
原始文件很大，写个以下简单的case看下能否复现，不行的话再联系我要原始表数据
1.上下游数据准备
mo:
create table testa(col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));
insert into testa values('[8.9398, 19.012, 0.4794]' , '[6.2387, 19.736, 3.7311]','[2.6849, 78.083, 3.9123]','[2.2176, 95.463, 2.0589]') 
);
mysql:
create table testa(col22 text, col23 text, col24 text, col25 text);

2.创建同步任务
3.查看下游mysql数据
```

**Comment by ck89119** [comment]
vector转成string的问题，pr中
