### ISSUE TITLE
[Bug]: restore nonsys from pitr report 'internal error: No valid checkpoints for snapshot read,maybe snapshot is too old'

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19033]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c827eeba53170b7fc40f0c06a9d20a68fc9719a4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="899" alt="企业微信截图_3fdbd639-0f03-40bf-be06-7c572b65426e" src="https://github.com/user-attachments/assets/259b2810-515d-46c2-b2da-0c6f26270e65">

日志：
[test.txt.gz](https://github.com/user-attachments/files/17145379/test.txt.gz)

### Steps to Reproduce

```Markdown
场景：系统租户恢复普通租户到指定的时间点

具体出错的sql：restore account acc01 from pitr p01 '2024-09-26 15:35:29';

详细步骤我写在文档里了，私发
```

**Comment by LeftHandCold** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
这两天测试没再出现
