### ISSUE TITLE
[Bug]:  cn crashed by FATAL: "vector is not empty" during tpcc and sysbench on daily regression TKE

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19049]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

49668ee

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11054477372/job/30720931583

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/efa66949-854d-4dcf-aadd-7fa4fe110fb9">

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/e72aa8a3-dc02-4180-99e3-efa89397315d">

mo-log link:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22IiS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-49668ee5d-20240926%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727375767689%22,%22to%22:%221727405841578%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1401" alt="image" src="https://github.com/user-attachments/assets/62f419bf-dbcd-4a1b-bb0b-446579093af5">

### Steps to Reproduce

```Markdown
DAILLY REGRESSION
```

**Comment by XuPeng-SH** [comment]
reverte
