### ISSUE TITLE
[Bug]: cn crashed by anic: runtime error: invalid memory address or nil pointer dereference during tpcc and sysbench on daily regression TKE 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19046]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

49668ee5dd2e89379d436bcff5921d34bacdb2de

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11054477372/job/30720931583
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/81087351-8ad1-4e92-82f2-6bc216e2e5f7">

<img width="1362" alt="image" src="https://github.com/user-attachments/assets/b53eff6b-c816-4d62-a3b0-a06e15701f6e">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22IiS%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-49668ee5d-20240926%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/1ddbe32d-ed8a-4e30-ab1b-7d5c4251e03b">

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/30e57d5f-333b-4a81-a21c-4fa7f585a177">

### Steps to Reproduce

```Markdown
DAILY REGRESSION
```

**Comment by Ariznawlll** [comment]
**128 regression
commit：ca577e56c97e464ba0ac6a89137470c62c94327f**

job url： https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11072489250/job/30767057745

mo第一次重启的地方：（对应utc+8时间为2024-09-28 04:00:56）
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/c6a85a44-0127-4245-920b-481b49d88789">

重启前的log：https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22aRY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-ca577e5-20240927-223037.log%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727449200000%22,%22to%22:%221727467800000%22%7D%7D%7D&schemaVersion=1&orgId=1

堆栈：
重启前，对应utc+8时间（2024-09-28 04:00:00）
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923511-f08e-7945-a70f-fd85f73d8158.gz](https://github.com/user-attachments/files/17172038/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923511-f08e-7945-a70f-fd85f73d8158.gz)

重启后，对应utc+8时间（2024-09-28 04:07:00）
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923518-b559-7d1a-8230-166a42bd92bc.gz](https://github.com/user-attachments/files/17172040/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923518-b559-7d1a-8230-166a42bd92bc.gz)

**Comment by xzxiong** [comment]
以下才是有效信息
https://grafana.ci.matrixorigin.cn/goto/geyLaWzNR?orgId=1
![image](https://github.com/user-attachments/assets/c2225eab-7b48-4c66-bf7a-e43600d4eedd)

**Comment by xzxiong** [comment]
> **128 regression commit：ca577e56c97e464ba0ac6a89137470c62c94327f**
> 
> job url： https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11072489250/job/30767057745
> 
> mo第一次重启的地方：（对应utc+8时间为2024-09-28 04:00:56） <img alt="image" width="1044" src="https://private-user-images.githubusercontent.com/108530700/371720804-c6a85a44-0127-4245-920b-481b49d88789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Nzk4MzAsIm5iZiI6MTcyNzY3OTUzMCwicGF0aCI6Ii8xMDg1MzA3MDAvMzcxNzIwODA0LWM2YTg1YTQ0LTAxMjctNDI0NS05MjBiLTQ4MWI0OWQ4ODc4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNjU4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGI3Zjg2MzBjOWE4MTAwZWZhZjkyNjMzOTI3OWVhZDkzYmI4NWFjNWFjMTFjYTc2ZmZjZDQyMjE3OGQwMTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5inEZoVXRSLtjS-j3X2q4F4sg2ML5PMWNjmqiX8tfrw">
> 
> 重启前的log：https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22aRY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-ca577e5-20240927-223037.log%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727449200000%22,%22to%22:%221727467800000%22%7D%7D%7D&schemaVersion=1&orgId=1
> 
> 堆栈： 重启前，对应utc+8时间（2024-09-28 04:00:00） [LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923511-f08e-7945-a70f-fd85f73d8158.gz](https://github.com/user-attachments/files/17172038/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923511-f08e-7945-a70f-fd85f73d8158.gz)
> 
> 重启后，对应utc+8时间（2024-09-28 04:07:00） [LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923518-b559-7d1a-8230-166a42bd92bc.gz](https://github.com/user-attachments/files/17172040/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01923518-b559-7d1a-8230-166a42bd92bc.gz)

待确认，目测与本issue 无关联。

**Comment by xzxiong** [comment]
woking on

**Comment by xzxiong** [comment]
woking on

**Comment by aressu1985** [comment]
fixed
