### ISSUE TITLE
[Bug]: restore from pitr report 'internal error: invalid checkpoints duration'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19066]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b93ef472b9afe0329e55b9043aef2fcdb41da4de

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1198" alt="image" src="https://github.com/user-attachments/assets/ee7b2149-7440-47bb-b461-1b91cace3ced">

创建pitr的时间是2024-09-27 15:05:05(图上是utc时间，换算成utc+8为2024-09-27 15:05:05)，range是2h，恢复的时间戳是'2024-09-27 14:59:09.953992'，恢复的时间在range的范围内

[test_01.txt.tar.gz](https://github.com/user-attachments/files/17160795/test_01.txt.tar.gz)

### Steps to Reproduce

```Markdown
单机环境，etc/launch/tn.toml中添加配置：
[tn.Ckp]
flush-interval = "10s"
min-count = 100
scan-interval = "5s"
incremental-interval = "30s"
global-min-count = 9

[tn.GCCfg]
gc-ttl = "5m"
scan-gc-interval = "2m"
check-gc = true

修改代码中的GC时间间隔
vi matrixone/pkg/vm/engine/tae/options/types.go
将DefaultGlobalVersionInterval = time.Hour 修改为 DefaultGlobalVersionInterval = 5 * time.Minute

make build后，启动mo

1. 系统租户创建租户acc01、acc02
2. acc01租户中加载数据
3. 系统租户为普通租户创建pitr 2h
4. 普通租户中删除一部分数据
5. 系统租户恢复普通租户

出错的sql：restore account acc01 from pitr p01 '2024-09-27 14:59:09.953992';
具体步骤联系我

```

**Comment by YANGGMM** [comment]
frontend/snapshot.go:1709","msg":"[p01] mock insert snapshot record sql: insert into mo_catalog.mo_snapshots(\n\t\tsnapshot_id,\n\t\tsname,\n\t\tts,\n\t\tlevel,\n\t\taccount_name,\n\t\tdatabase_name,\n\t\ttable_name,\n\t\tobj_id ) values ('01923261-4617-7714-99b0-53ffe7f16bcc', '01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock', 1727420349953992000, 'account', 'acc01', '', '', 1);

{"level":"INFO","time":"2024/09/27 15:28:08.998850 +0800","name":"cn-service","caller":"incrservice/service.go:279","msg":"auto increment cache created","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","table-id":272842,"txn":"70f70f4866a9b62a17f9069bd5802124"}
{"level":"INFO","time":"2024/09/27 15:28:08.999106 +0800","name":"cn-service","caller":"frontend/snapshot.go:1075","msg":"[01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock] start to insert select table: sbtest1, insert sql: **insert into `sysbench_db`.`sbtest1` SELECT * FROM `sysbench_db`.`sbtest1` {SNAPSHOT = '01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock'}**","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}

{"level":"INFO","time":"2024/09/27 15:28:10.641301 +0800","name":"cn-service","caller":"compile/compile2.go:273","msg":"insert into with snapshot","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","sql":"insert into `sysbench_db`.`sbtest1` SELECT * FROM `sysbench_db`.`sbtest1` {SNAPSHOT = '01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock'}","**affectRows":100000**}

{"level":"INFO","time":"2024/09/27 15:28:10.641714 +0800","name":"cn-service","caller":"frontend/snapshot.go:1079","msg":"[01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock] insert select table: sbtest1, **cost: 1.64257825s**","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}


{"level":"INFO","time":"2024/09/27 15:28:10.652252 +0800","name":"cn-service","caller":"frontend/snapshot.go:1075","msg":"[01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock] start to insert select table: sbtest10, insert sql: insert into `sysbench_db`.`sbtest10` SELECT * FROM `sysbench_db`.`sbtest10` {SNAPSHOT = '01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock'}","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}

{"level":"INFO","time":"2024/09/27 15:28:10.654034 +0800","caller":"plan/build_util.go:60","msg":"Row lock upgraded to table lock for SQL : insert into `sysbench_db`.`sbtest10` SELECT * FROM `sysbench_db`.`sbtest10` {SNAPSHOT = '01923261-4617-7714-99b0-53ffe7f16bcc_p01_mock'}"}
{"level":"INFO","time":"2024/09/27 15:28:10.654061 +0800","caller":"plan/build_util.go:61","msg":"the outcnt stats is 100000000.000000"}
{"level":"INFO","time":"2024/09/27 15:28:10.654718 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[0]: MetaFile[0][0-0->1727421086180834000-1][meta_0-0_1727421086180834000-1.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654737 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[1]: MetaFile[2][1727421086180834000-1->1727421141186754000-0][meta_1727421086180834000-1_1727421141186754000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654747 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[2]: MetaFile[3][1727421141186754000-1->1727421211203291000-0][meta_1727421141186754000-1_1727421211203291000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654756 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[3]: MetaFile[4][1727421211203291000-1->1727421281186551000-0][meta_1727421211203291000-1_1727421281186551000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654764 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[4]: MetaFile[5][1727421281186551000-1->1727421336172610000-0][meta_1727421281186551000-1_1727421336172610000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654771 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[5]: MetaFile[6][1727421336172610000-1->1727421441174267000-0][meta_1727421336172610000-1_1727421441174267000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654780 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[6]: MetaFile[7][1727421441174267000-1->1727421541175853000-0][meta_1727421441174267000-1_1727421541175853000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654790 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[7]: MetaFile[8][1727421541175853000-1->1727421666176737000-0][meta_1727421541175853000-1_1727421666176737000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654797 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[8]: MetaFile[9][1727421666176737000-1->1727421826181767000-0][meta_1727421666176737000-1_1727421826181767000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654805 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[9]: MetaFile[10][1727421826181767000-1->1727421981197651000-0][meta_1727421826181767000-1_1727421981197651000-0.ckp]"}
{"level":"INFO","time":"2024/09/27 15:28:10.654813 +0800","caller":"checkpoint/snapshot.go:103","msg":"metaFiles[10]: MetaFile[1][0-0->1727421981197651000-1][meta_0-0_1727421981197651000-1.ckp]"}
{"level":"ERROR","time":"2024/09/27 15:28:10.657918 +0800","caller":"logtailreplay/partition.go:188","msg":"error: internal error: invalid checkpoints duration"}
{"level":"INFO","time":"2024/09/27 15:28:10.657947 +0800","caller":"disttae/db.go:342","msg":"Snapshot consumeSnapCkps failed, err:internal error: invalid checkpoints duration"}

**Comment by LeftHandCold** [comment]
Fixed

**Comment by Ariznawlll** [comment]
这两天测试没再出现
