### ISSUE TITLE
[Bug]: select time(now());结果为00:00:00

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#19078]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

c0addcd9b753702e4f85559f6e250e057c46a094

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
阿里云Dev环境
```

### Actual Behavior

如标题

### Expected Behavior

期望同MySQL结果：
```
mysql> select time(now());
+-------------+
| time(now()) |
+-------------+
| 11:22:52    |
+-------------+
```

### Steps to Reproduce

```Markdown
同标题，任意租户实例
```

**Comment by YANGGMM** [comment]
@aressu1985  麻烦test一下
