### ISSUE TITLE
[Bug]: select count(*) is wrong with big update in workspace

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#19072]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="718" alt="image" src="https://github.com/user-attachments/assets/bc0b3785-d752-40b8-a2ed-756d187385f1">

### Steps to Reproduce

```Markdown
CREATE DATABASE IF NOT EXISTS `test`;
USE `test`;
DROP TABLE IF EXISTS `t1`;
CREATE TABLE t1 (
    id INT PRIMARY KEY,
    col1 INT,
    col2 INT
);
INSERT INTO t1 (SELECT *,1,1 FROM generate_series(0,1999999,1)g);
BEGIN;
UPDATE t1 SET col2 = col2 + 1 WHERE col1 = 1;
SELECT COUNT(*)
```

**Comment by triump2020** [comment]
应该是workspace 问题， 没有begin 就没有问题.

**Comment by triump2020** [comment]
Blocked by other issues
