### ISSUE TITLE
[Bug]: use mo-sysbench to create table with secondary index report panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19089]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

zhangxu19830126

### Commit ID

1fcf95d568c286a4ae3a7d58420b619f81699d99

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
用的旭哥分支：https://github.com/zhangxu19830126/matrixone/commits/fix_ctx_canceled

<img width="1375" alt="企业微信截图_7e1ec507-233d-431a-ab99-ac6a30cd4b9e" src="https://github.com/user-attachments/assets/a2cabfdd-b120-4c3e-a287-2e2d90b0b6a8">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22IdY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-shardingtest%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727599680000%22,%22to%22:%221727599920000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
git clone https://github.com/matrixorigin/matrixone.git
cd mo-sysbench

sysbench  --mysql-host=172.16.20.80 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_update_index.lua --mysql-db=sysbench_db --tables=1 --table_size=100000 --threads=100 --time=30 --report-interval=10  cleanup

prepare(prepare前需要先创建db：sysbench_db): -> 该步骤报错
sysbench  --mysql-host=172.16.20.80 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_update_index.lua --mysql-db=sysbench_db --tables=1 --table_size=100000 --threads=100 --time=30 --report-interval=10  prepare
```

**Comment by triump2020** [comment]
Working on other issues

**Comment by Ariznawlll** [comment]
**main commit：8415938**

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/913a0424-bb22-40d1-ba0d-eb883ac2f02a">

本次回归通过
