### ISSUE TITLE
[Bug]: mo-cdc: mo binary(255) do not display the last 0，but mysql display

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19084]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

07b514cd4dd45ae30ccdaeed026cd4520331a1f9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

上游mo `col20` binary(255)类型，同步到下游mysql  binary(255)类型
mo:
<img width="1389" alt="企业微信截图_0fcaca20-b5ae-45ae-8f68-8baaf99d75e3" src="https://github.com/user-attachments/assets/1e5f0b20-2153-4a95-9f67-27e12c43f723">
查看col20长度为2:
<img width="1414" alt="企业微信截图_8c294896-e431-4340-962f-1c26e09808dc" src="https://github.com/user-attachments/assets/becaf5ef-32bd-4275-b53b-de24852d0f77">

同步到mysql的数据，和mo相比多了末尾很多个0，长度是255
<img width="1413" alt="企业微信截图_6b61ee2e-3d9a-4091-a9da-240bcf040b69" src="https://github.com/user-attachments/assets/5f4a497a-fef4-4b45-bc89-9d7bb3739389">
<img width="1412" alt="企业微信截图_8216d5da-4522-4cb8-b655-bf54ee2970a7" src="https://github.com/user-attachments/assets/7108064f-f652-4a77-ab46-745817d5edfb">

### Steps to Reproduce

```Markdown
1.mo创建表
create table test(id primary key,binary(255))
insert into test values(1,'uuer');
2.mysql创建表
create table test(id primary key,binary(255))
3.创建同步任务
4.查询mysql表数据
```

**Comment by ck89119** [comment]
无法复现，查询mo得到的数据，length都和mysql一致

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/97c24ceb-8f50-460a-88fb-7eaecece1ea2">
