### ISSUE TITLE
[Bug]: mo crashed when loading data to table with key partition

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19085]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

07b514cd4dd45ae30ccdaeed026cd4520331a1f9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ddL:
create table bmsql_customer (
  c_w_id         integer        not null,
  c_d_id         integer        not null,
  c_id           integer        not null,
  c_discount     decimal(4,4),
  c_credit       char(2),
  c_last         varchar(16),
  c_first        varchar(16),
  c_credit_lim   decimal(12,2),
  c_balance      decimal(12,2),
  c_ytd_payment  decimal(12,2),
  c_payment_cnt  integer,
  c_delivery_cnt integer,
  c_street_1     varchar(20),
  c_street_2     varchar(20),
  c_city         varchar(20),
  c_state        char(2),
  c_zip          char(9),
  c_phone        char(16),
  c_since        timestamp,
  c_middle       char(2),
  c_data         varchar(500),
  primary key (c_w_id, c_d_id, c_id)
)partition by key(c_w_id) partitions 10;

mysql> use tpcc_10;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> load data infile '/mnt/datadisk0/active/mo-load-data/data/tpcc_10/customer.csv' into table tpcc_10.bmsql_customer  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' parallel
'true';
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)
ERROR: 
Can't connect to the server

mo-log:
[mo-service-crash.log](https://github.com/user-attachments/files/17178376/mo-service-crash.log)

{"level":"FATAL","time":"2024/09/29 15:28:47.407134 +0800","caller":"rpc/handle.go:784","msg":"the `CNCreated` mask not set: [OBJ(000)-(\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000)|NoExt]","stacktrace":"github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite\n\t/mnt/datadisk0/active/matrixone/pkg/vm/engine/tae/rpc/handle.go:784\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).handleRequests\n\t/mnt/datadisk0/active/matrixone/pkg/vm/engine/tae/rpc/handle.go:289\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit\n\t/mnt/datadisk0/active/matrixone/pkg/vm/engine/tae/rpc/handle.go:420\ngithub.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit\n\t/mnt/datadisk0/active/matrixone/pkg/txn/storage/tae/storage.go:87\ngithub.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit\n\t/mnt/datadisk0/active/matrixone/pkg/txn/service/service_cn_handler.go:263\ngithub.com/matrixorigin/matrixone/pkg/tnservice.(*store).handleCommit\n\t/mnt/datadisk0/active/matrixone/pkg/tnservice/store_rpc_handler.go:124\ngithub.com/matrixorigin/matrixone/pkg/txn/rpc.executor.exec\n\t/mnt/datadisk0/active/matrixone/pkg/txn/rpc/server.go:294\ngithub.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).handleTxnRequest\n\t/mnt/datadisk0/active/matrixone/pkg/txn/rpc/server.go:269\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/mnt/datadisk0/active/matrixone/pkg/common/stopper/stopper.go:277"}
{"level":"ERROR","time":"2024/09/29 15:28:47.407172 +0800","caller":"fileservice/path.go:77","msg":"error: invalid file path \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}
{"level":"WARN","time":"2024/09/29 15:28:47.407130 +0800","caller":"objectio/cache.go:130","msg":"[LoadObjectMetaByExtent]","name":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","extent":"0_0_0_0"}
{"level":"ERROR","time":"2024/09/29 15:28:47.408869 +0800","caller":"fileservice/path.go:77","msg":"error: invalid file path \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}

### Steps to Reproduce

```Markdown
AS ACTUAL BEHAVIOR
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify the test

**Comment by aressu1985** [comment]
fixed:
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/d882b0c4-fcc6-4b67-995f-21abcc164b03">
