### ISSUE TITLE
[Bug]: [ERROR] [datasync.go:643] cannot get the last entry when transfering logtail 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19094]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

07b514cd4dd45ae30ccdaeed026cd4520331a1f9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[root@VM-16-2-centos mo_ctl]# ./build/mo_ctl data-sync start --disk-data-dir=/mnt/disk1/standby/matrixone/mo-data/s3 --shard-id=1 --replica-id=262150 --logservice-address=127.0.0.1:32001 --fileservice-backend=disk --log-data-dir=/mnt/disk1/standby/novoting-log/mo-data/logservice-data/4c4dccb4-4d3c-41f8-b482-5251dc7a41bd
2024-09-29 19:19:21 [INFO] [datasync.go:772] get first index to read: 12206746

2024-09-29 19:19:21 [INFO] [datasync.go:634] begin of replaying logs, first index: 12206746, last index: 6929652

   0% |                                                                                                                                              | (0/-5277094, 0 it/hr) [0s:0s]
2024-09-29 19:19:21 [INFO] [datasync.go:639] end of replaying logs, cost 146.241µs

2024-09-29 19:19:21 [ERROR] [datasync.go:643] cannot get the last entry

active: 
MO-Stability-Testing-0 /mnt/datadisk0/active/matrixone
MO-Stability-Testing-1 /mnt/disk1/standby/novoting-log
standby:
MO-Stability-Testing-1 /mnt/disk1/standby/matrixone

### Steps to Reproduce

```Markdown
1. start a mo with standlone mode on service1
2. run a no-voting logserivce on service2
3. create 3 accounts and load tpcc, tpch, tpch and run tpcc,sysbench test for 3 hours
4. stop active mo
5. transfer no-voting logservice data to standby logservice
```

**Comment by volgariver6** [comment]
fixed by https://github.com/matrixorigin/mo_ctl/pull/84

**Comment by aressu1985** [comment]
fixed
