### ISSUE TITLE
[Bug]: [date 9.29]main standalone regression: create db.table reported error invalid database which database already exists

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19106]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

206f549087532728cba62753c430a0df5f32bdbb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11093459966
<img width="1130" alt="企业微信截图_211c8f1f-874e-459f-80b1-4ddde1eea736" src="https://github.com/user-attachments/assets/09f2f898-73e1-41b0-9dad-233ac197c6de">
<img width="1069" alt="企业微信截图_819deb9f-fde3-412a-8851-03b85308164a" src="https://github.com/user-attachments/assets/8db72511-4206-4df0-a254-8e0a01ace059">

报错日志时间：01:41:35
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-206f549-20240929-222907.log%5C%22%7D%20%7C%3D%20%60invalid%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727631694000%22,%22to%22:%221727631696000%22%7D%7D%7D&schemaVersion=1&orgId=1

该错误是在报 cannot commit a orphan transaction之后开始报错，不确定是否有关联，需定位，相关issue：https://github.com/matrixorigin/matrixone/issues/19105

### Steps to Reproduce

```Markdown
standalone regression
```

**Comment by heni02** [comment]
1.2 相关issue：https://github.com/matrixorigin/matrixone/issues/18989
https://github.com/matrixorigin/MO-Cloud/issues/4091

**Comment by iamlinjunhong** [comment]
这段时间 cn 负载高，dn 与 cn 断链

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
调整 gc 参数

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
{"level":"ERROR","time":"2024/09/30 01:41:35.168297 +0800","name":"cn-service","caller":"frontend/util.go:517","msg":"query trace status","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"create database if not exists tpch_1g","status":"fail","error":"cannot commit a orphan transaction","txn_info":"70f70f4866a9b62a17f9bd617cbc332c:1727631695164169074-1","session_info":"connectionId 27961\|\|account sys:dump\|goRoutineId 0\|migrate-goRoutineId 0\|01923edf-9d38-7053-a0d5-201ce2210c6a","role":"moadmin","session_id":"01923edf-9d38-7053-a0d5-201ce2210c6a","statement_id":"01923edf-9d3b-7b24-b648-c3c4b43da860","span":{"trace_id":"e04127f6-31d5-319b-77a7-03d06b112a63","span_id":"c90a4d43ae5a7094"}}
--


<br class="Apple-interchange-newline">

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19250

**Comment by heni02** [comment]
继续观察一周

**Comment by heni02** [comment]
回归一周没有再出现，先closed
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11462325767
