### ISSUE TITLE
[Bug]: [date 9.29]standalone regression: mo reported lots of error cannot commit a orphan transaction

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19105]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

206f549087532728cba62753c430a0df5f32bdbb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11093459966/job/30819836044
第一次开始报错时间：17:23:58（日志时间+8h）
<img width="1423" alt="企业微信截图_dcb95d32-0af3-4a22-8205-0351559df586" src="https://github.com/user-attachments/assets/7715c7c3-114c-4c06-9b49-84c3b87dbf73">
其他报错也是在create 或drop等ddl时报错
<img width="1129" alt="企业微信截图_ba2d3179-4b82-4e1b-b32e-3192d252047b" src="https://github.com/user-attachments/assets/fcd47857-6d98-4e1c-958d-64b6c4135504">

mo log：
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-206f549-20240929-222907.log%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727630630000%22,%22to%22:%221727630639000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
standalone regression
```

**Comment by iamlinjunhong** [comment]
这段时间 cn 负载高，dn 与 cn 断链

**Comment by zhangxu19830126** [comment]
https://shanghai.idc.matrixorigin.cn:30001/goto/rL9XrrzNg?orgId=1，有大量的io/timeout。

**Comment by heni02** [comment]
10.4号回归job也复现该问题
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11181772860/job/31086731767
<img width="968" alt="企业微信截图_c2cbb668-432f-4ef1-acaf-f3bc1dcc8686" src="https://github.com/user-attachments/assets/4ce16bda-1950-4669-8d85-03bc806435af">

日志：
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-b0855d2-20241004-222950.log%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728072209185%22,%22to%22:%221728075929760%22%7D%7D%7D&schemaVersion=1&orgId=1

10.9日定位结论
<img width="716" alt="企业微信截图_066465e2-f001-4bde-9890-390ffd2ae130" src="https://github.com/user-attachments/assets/adb236db-03a9-41b0-80b3-4636f4b12cfe">
<img width="758" alt="企业微信截图_3ee40579-4eaf-450a-8f5c-56bba3098729" src="https://github.com/user-attachments/assets/a2888fdc-4965-4417-886b-4289de6a111b">
<img width="746" alt="企业微信截图_b32dcf24-f862-4474-89c1-1b3d69070df3" src="https://github.com/user-attachments/assets/1f32b8a6-030e-485e-8b27-7319b8071f95">
10.9号回归也复现了该问题，抓取random_range相关的profile
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11237642466/job/31240798114
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_01926d2e-2cae-7cfd-a770-18ec42b98fd4.gz](https://github.com/user-attachments/files/17321064/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_01926d2e-2cae-7cfd-a770-18ec42b98fd4.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01926d2d-dbf8-7177-b09c-01b0cc33b63e.gz](https://github.com/user-attachments/files/17321067/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01926d2d-dbf8-7177-b09c-01b0cc33b63e.gz)

**Comment by iamlinjunhong** [comment]
调整 gc 参数

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by heni02** [comment]
pr合入后近一周无大面积报错现象，还需要继续观察，先降级s0
