### ISSUE TITLE
[Bug]: The ut test time of multi_upload package is too long

### ISSUE THREAD

**Issue by guguducken** [matrixorigin/matrixone#19104]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

206f549087532728cba62753c430a0df5f32bdbb

### Other Environment Information

```Markdown
- Hardware parameters: 
- OS type: l
- Others:
```

### Actual Behavior

<img width="971" alt="image" src="https://github.com/user-attachments/assets/8e3ebcf5-1110-4344-99b3-c2cc31a3e883">
<img width="848" alt="image" src="https://github.com/user-attachments/assets/dc665168-0a94-4ee9-b47f-e11cc2343aa3">

### Steps to Reproduce

```Markdown
make ut
```

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
先处理DML重构

**Comment by ouyuanning** [comment]
在DML重构分支已处理。等合并

**Comment by ouyuanning** [comment]
在DML重构分支已处理。等合并

**Comment by ouyuanning** [comment]
在DML重构分支已处理。改分支合并后就好了

**Comment by ouyuanning** [comment]
在DML重构分支已处理。改分支合并后就好了

**Comment by ouyuanning** [comment]
在DML重构分支已处理。改分支合并后就好了
