### ISSUE TITLE
[Bug]: active mo start failed by panic: internal error: read checkpoint CKP[G][2][ckp 341181, truncate 336181](0-0->1727597174306292063-1) failed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19116]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

07b514cd4dd45ae30ccdaeed026cd4520331a1f9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When standy mo changed as active mo after transfering logtail data， the mo started failed:
{"level":"ERROR","time":"2024/09/30 15:36:59.792138 +0800","caller":"moerr/error.go:749","msg":"error: internal error: read checkpoint CKP[G][2][ckp 341181, truncate 336181](0-0->1727597174306292063-1) failed","span":{"trace_id":"8adeb5a3-2df1-8af8-93a9-86c8e68906ef","span_id":"fa031c57e459276f"}}
{"level":"INFO","time":"2024/09/30 15:36:59.792180 +0800","caller":"db/open.go:83","msg":"open-tae","operation":"End","operand":"open","cost":"241.008999ms","err":"internal error: read checkpoint CKP[G][2][ckp 341181, truncate 336181](0-0->1727597174306292063-1) failed"}
panic: internal error: read checkpoint CKP[G][2][ckp 341181, truncate 336181](0-0->1727597174306292063-1) failed

goroutine 367 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x5649818, 0xc0065b1380}, {0xc00ebb4600, 0x5d}, 0xc009f02000)
        /mnt/disk1/standby/matrixone/pkg/vm/engine/tae/db/open.go:196 +0x2da9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0x5649818, 0xc0065b1380}, {0xc00dc7e060, 0x59}, 0xc009f02000)
        /mnt/disk1/standby/matrixone/pkg/vm/engine/tae/rpc/handle.go:92 +0x1a5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0x5649818?, 0xc0065b1380?}, {0xc00dc7e060?, 0x33b6957?}, 0x4d9a0c8?)
        /mnt/disk1/standby/matrixone/pkg/vm/engine/tae/rpc/handle.go:112 +0x45
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0x5649818, 0xc0065b1380}, {0xc00dc7e060, 0x59}, 0xc009f02000, {{0x2, 0x1, {}, {0x0, 0x0, ...}, ...}, ...}, ...)
        /mnt/disk1/standby/matrixone/pkg/txn/storage/tae/storage.go:55 +0xda
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).newTAEStorage(0xc00abaeea0, {0x5649818, 0xc0065b1380}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...}, ...)
        /mnt/disk1/standby/matrixone/pkg/tnservice/factory.go:203 +0x5f3
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createTxnStorage(0xc00abaeea0, {0x5649818, 0xc0065b1380}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, ...})
        /mnt/disk1/standby/matrixone/pkg/tnservice/factory.go:75 +0x2d8
github.com/matrixorigin/matrixone/pkg/tnservice.(*store).createReplica.func1({0x5649818, 0xc0065b1380})
        /mnt/disk1/standby/matrixone/pkg/tnservice/store.go:315 +0x13c
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /mnt/disk1/standby/matrixone/pkg/common/stopper/stopper.go:277 +0x5b
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask in goroutine 795
        /mnt/disk1/standby/matrixone/pkg/common/stopper/stopper.go:272 +0xb0

[mo-service-failed.log](https://github.com/user-attachments/files/17186285/mo-service-failed.log)

### Steps to Reproduce

```Markdown
1. start a mo with standlone mode on service1
2. run a no-voting logserivce on service2
3. create 3 accounts and load tpcc, tpch, tpch and run tpcc,sysbench test for 3 hours
4. stop active mo
5. transfer no-voting logservice data to standby logservice
6. start standby mo
```

**Comment by volgariver6** [comment]
@LeftHandCold please help investigate why checkpoint file lost?

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
