### ISSUE TITLE
[Bug]:cn transfer failed in main branch

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19124]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

30e90224c50feaccb76d08006381f275d6d95e67

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="592" alt="WeChatWorkScreenshot_8d130d84-3b88-4882-b1db-3036b998a16e" src="https://github.com/user-attachments/assets/0147ebb2-deff-447f-a179-fc8ff597f1f2">

main代码不能跑连接迁移测试

### Expected Behavior

设置一个cn 为 draining后，连接会迁移到另一个cn上。

### Steps to Reproduce

https://github.com/daviszhen/morunner?tab=readme-ov-file#pr-checklist

<img width="1010" alt="企业微信截图_f33ab842-fbd6-42b1-8cf0-f075217d7a5c" src="https://github.com/user-attachments/assets/8d82ac24-bef2-4baf-ad96-ea5099535dab">

**Comment by volgariver6** [comment]
fixed
