### ISSUE TITLE
[Bug]: DN pod restart 

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19122]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

206f549087532728cba62753c430a0df5f32bdbb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CHAOS TEST：
Every 5 minutes random kill one log service pod ,but DN restart .
<img width="840" alt="企业微信截图_36ee8227-b354-4ce4-b508-0abd9213ac08" src="https://github.com/user-attachments/assets/dc7d7d16-1281-4997-9d78-dd1d4832098e">
<img width="1309" alt="企业微信截图_eb2fb01f-60b1-4bdc-b1be-efad494efb6d" src="https://github.com/user-attachments/assets/502248ec-45c8-4a8f-8038-81ffb02e753b">
<img width="1231" alt="企业微信截图_ac41d24b-2577-46ca-bb06-44a925175ecf" src="https://github.com/user-attachments/assets/fc9ed7cf-d60c-486f-bb3f-0ab0c09f9d5d">

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%226tl%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-206f549-202409301047%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727682600000%22,%22to%22:%221727690399000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
RUN CHAOS TEST
1、Every 5 minutes random kill one log service pod and use tpcc tool to test mo.
2、Set RunMinutes 14400.

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11098450905
```

**Comment by tom-csf** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%226tl%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-206f549-202409301047%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727682600000%22,%22to%22:%221727690399000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
未处理

**Comment by volgariver6** [comment]
dn重启的原因是，长时间无法写logservice，最后超时panic了。

logservice 反复重启最后偶发的需要长时间才能提供服务，需要继续调研一下。

**Comment by volgariver6** [comment]
正在尝试复现

**Comment by tom-csf** [comment]
复现成功，大概在26号凌晨3点
<img width="1373" alt="企业微信截图_c81421f0-1be2-40f6-9cfc-272689b7cdcc" src="https://github.com/user-attachments/assets/a4eecd11-4aba-49de-b82c-4071797e46d8">

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22nUp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-ab0cdb8-202410240952%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729879200000%22,%22to%22:%221729886400000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22nUp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-ab0cdb8-202410240952%5C%22,%20matrixorigin_io_component%3D%5C%22LogSet%5C%22%7D%20%21%3D%20%60failed%20to%20get%20cluster%20details%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221729879390053%22,%22to%22:%221729879418053%22%7D%7D%7D&schemaVersion=1&orgId=1

日志文件，以防链接失效：
[Explore-logs-2024-10-28 14_17_03.txt](https://github.com/user-attachments/files/17538130/Explore-logs-2024-10-28.14_17_03.txt)

```
2024-10-26T02:03:27+08:00	{"level":"WARN","time":"2024/10/25 18:03:27.089315 +0000","name":"raft","caller":"raft/raft.go:1686","msg":"[f:32899403,l:33071913,t:77,c:33071913,a:33071913] [00001:62147] t77 rejected preVote n62145 index 33060862 term 77,logterm 76, utd false"}
2024-10-26T02:03:27+08:00	{"level":"INFO","time":"2024/10/25 18:03:27.082241 +0000","name":"hakeeper","caller":"hakeeper/rsm.go:429","msg":"adding schedule command to hakeeper rsm: L/CreateTask 00000000-0000-0000-0000-000000000000"}
2024-10-26T02:03:27+08:00	{"level":"WARN","time":"2024/10/25 18:03:27.079073 +0000","name":"raft","caller":"raft/raft.go:1686","msg":"[f:32899224,l:33071913,t:77,c:33071913,a:33071913] [00001:62146] t77 rejected preVote n62145 index 33060862 term 77,logterm 76, utd false"}
2024-10-26T02:03:27+08:00	{"level":"WARN","time":"2024/10/25 18:03:27.053584 +0000","name":"raft","caller":"raft/raft.go:1165","msg":"[f:32865107,l:33060862,t:76,c:33060862,a:33060862] [00001:62145] t76 sent RequestPreVote to n62147"}
2024-10-26T02:03:27+08:00	{"level":"WARN","time":"2024/10/25 18:03:27.053408 +0000","name":"raft","caller":"raft/raft.go:1165","msg":"[f:32865107,l:33060862,t:76,c:33060862,a:33060862] [00001:62145] t76 sent RequestPreVote to n62146"}
2024-10-26T02:03:27+08:00	{"level":"WARN","time":"2024/10/25 18:03:27.053145 +0000","name":"raft","caller":"raft/raft.go:1128","msg":"[f:32865107,l:33060862,t:76,c:33060862,a:33060862] [00001:62145] t76 received RequestPreVoteResp from n62145"}
2024-10-26T02:03:27+08:00	{"level":"WARN","time":"2024/10/25 18:03:27.052902 +0000","name":"raft","caller":"raft/raft.go:1011","msg":"[f:32865107,l:33060862,t:76,c:33060862,a:33060862] [00001:62145] t76 became PreVote candidate"}
```

从上面的日志中可以看出，log2 向log0 和 log1 发送了 preVote request，log0 和 log1 收到了请求，打印了拒绝日志，因为term不比log2的大，但是log2没有收到response，没有打印  `t76 received RequestPreVoteResp from n62146` 或者 `t76 received RequestPreVoteResp from n62147`，应该是因为log0 和log1 到log2之间的网络链路不通了，导致了后续的问题。

需要加一下日志查看错误原因。

**Comment by volgariver6** [comment]
另外还有一个问题是，为什么log重启之后，都会报错`panic: failed to lock data directory`，panic几次之后才能够正常启动？也需要调查一下

**Comment by volgariver6** [comment]
大概分析出原因：

```

{"level":"WARN","time":"2024/10/25 18:02:53.541488 +0000","name":"transport","caller":"transport/transport.go:336","msg":"mo-chaos-regression-dis-log-2.mo-chaos-regression-dis-log-headless.mo-chaos-ab0cdb8-202410240952.svc:32000 became unreachable, affected 0 nodes"}
{"level":"WARN","time":"2024/10/25 18:02:53.541445 +0000","name":"transport","caller":"transport/transport.go:433","msg":"breaker 00000000-0000-0000-0000-000000000000 to mo-chaos-regression-dis-log-2.mo-chaos-regression-dis-log-headless.mo-chaos-ab0cdb8-202410240952.svc:32000 failed, connect and process failed: dial tcp 10.10.123.28:32000: connect: connection refused"}
{"level":"ERROR","time":"2024/10/25 18:02:53.541342 +0000","name":"transport","caller":"transport/transport.go:421","msg":"Nodehost 00000000-0000-0000-0000-000000000000 failed to get a connection to mo-chaos-regression-dis-log-2.mo-chaos-regression-dis-log-headless.mo-chaos-ab0cdb8-202410240952.svc:32000, dial tcp 10.10.123.28:32000: connect: connection refused"}
```

dragonboat 中打印上面的日志，表示log2现在网络不通，在尝试了几次之后，membership 将其移除：

```
{"level":"INFO","time":"2024/10/25 18:03:08.218193 +0000","name":"gossip","caller":"registry/gossip_logger.go:41","msg":"memberlist: Marking 00000000-0000-0000-0000-000000000002 as failed, suspect timeout reached (0 peer confirmations)"}
```

移除之后log0和log1就再也找不到log2了。如果后面再进行 chaos 测试，肯定就会出问题了。

所以根源还是 log 服务启动之后，为什么会经历很多次的 panic: failed to lock data directory，导致网络长时间不通，最后才引发了后续的问题。

**Comment by volgariver6** [comment]
不好复现，正在搭建本地环境

**Comment by volgariver6** [comment]
没有进展

**Comment by volgariver6** [comment]
没有进展

**Comment by loveRhythm1990** [comment]
该环境的 K8s版本为 v1.28.4，从 v1.28.4 的代码来看，K8s永远不会立即发送 SIGKILL给容器，总是至少设置 2s 的 grace timeout。
代码：https://github.com/kubernetes/kubernetes/blob/bae2c62678db2b5053817bc97181fcc2e8388103/pkg/kubelet/kuberuntime/kuberuntime_container.go#L740
```go
	// always give containers a minimal shutdown window to avoid unnecessary SIGKILLs
	if gracePeriod < minimumGracePeriodInSeconds {
		gracePeriod = minimumGracePeriodInSeconds
	}
```
从 K8s issue [kubectl delete pod" doesn't kill pod's process immediately when specifying --grace-period=0 #120449](https://github.com/kubernetes/kubernetes/issues/120449#issuecomment-1874547396)的 comments 也能验证这个问题。

<img width="981" alt="image" src="https://github.com/user-attachments/assets/f50b2a2a-76fd-41dd-a383-fb61f1caa1d1">

这个 issue 提到的 logservice 的问题，大概率是强制删除触发的，在实际运维过程中，我们极少强制删除 pod。强制删除会立即从 etcd中把 pod删除（把原数据删除，进程不会立即删掉），并启动一个新的 pod。导致两个进程抢文件锁。

**Comment by loveRhythm1990** [comment]
已验证 gracePeriod 为 0 会立即删除 pod，需要调整 gracePeriod 之后再测试一下

**Comment by tom-csf** [comment]
之前测试过调整 gracePeriod 到30 测试没有复现之前的问题

**Comment by tom-csf** [comment]
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/7cacc886-2133-4c6c-ba51-03d6423212d1">
