### ISSUE TITLE
[Bug]: mo_ctl_policy error in ci

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19123]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

daviszhen:0925-clean-code

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/a926c30a-b59a-43dd-8eba-f0de10d92368)

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11101629009/job/30839696498?pr=19095
```

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11255791247/job/31296167963?pr=19174

**Comment by w-zr** [comment]
![image](https://github.com/user-attachments/assets/4789f1ba-9339-4513-bea7-e3dde59c2c5c)

drop mo_ctl_policy failed.

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11309986879/job/31454506259?pr=19209

**Comment by w-zr** [comment]
暂无进展。

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11434524749/job/31808258158?pr=19481

**Comment by ck89119** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11475908480/job/31934781265?pr=19544

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11513173609/job/32049403495?pr=19541

**Comment by XuPeng-SH** [comment]
workaround by #19607

**Comment by aressu1985** [comment]
fixed
