### ISSUE TITLE
[Bug]: [date 9.29]tke regression: mo reported lots of cannot commit a orphan transaction and sysbench test cannot stopped

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19130]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

206f549087532728cba62753c430a0df5f32bdbb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11093493322
<img width="1547" alt="企业微信截图_255026af-56aa-4ab5-9e6a-9acdaa0034a0" src="https://github.com/user-attachments/assets/a2c26d89-25bb-4667-9493-6c30a20b9ca9">

报错时的日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22FCf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-206f54908-20240929%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727667623857%22,%22to%22:%221727667815857%22%7D%7D%7D&schemaVersion=1&orgId=1 

### Steps to Reproduce

```Markdown
tke regression sysbench test
```

**Comment by heni02** [comment]
定位到的信息：
<img width="1443" alt="企业微信截图_c4c7e2b9-339c-483d-be5e-3cde696c72f4" src="https://github.com/user-attachments/assets/c414c614-16e8-4129-827e-600b46c0cd98">
<img width="559" alt="企业微信截图_1338bf5c-91b1-4813-8fcc-c1c14bdfcad3" src="https://github.com/user-attachments/assets/65f2cdc4-d74f-45d7-9aa5-a6ada6cdeb11">

**Comment by heni02** [comment]
date9.30 regression也出现该问题，还有为什么sysbench无法断开链接也需要定位原因（环境可以登陆不是hung）
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11108340207/job/30890151720
<img width="1083" alt="企业微信截图_2c70e083-756a-4163-8622-4e1c8bf01c84" src="https://github.com/user-attachments/assets/bb53c3d6-6a3a-4b78-94e3-ea244110f41a">

mo最新时的日志都是报大量孤儿事务错误：
<img width="1331" alt="企业微信截图_16a7196e-9065-45a3-95ac-efe00c0a0c0c" src="https://github.com/user-attachments/assets/4869523e-020a-497e-9f0c-b9e5c8e350b6">
最早开始报错时间：11:31:30

**Comment by heni02** [comment]
date 10.1 
1.tpch 1T load时间报错
<img width="1046" alt="企业微信截图_d5e2cfda-41d3-4a44-81b1-c7f0731337c0" src="https://github.com/user-attachments/assets/484d1751-da62-4a0d-9422-5943df8da1e5">

查看内存没有占满
<img width="712" alt="image" src="https://github.com/user-attachments/assets/9c47af3d-d243-4f9d-9363-8cfb7d80672d">

2.sysbench也和昨天一样报错
<img width="1082" alt="企业微信截图_7b366c6f-417a-491d-9081-5b243126a437" src="https://github.com/user-attachments/assets/96095b9d-39c4-4712-b028-f1d87c88c42c">
<img width="714" alt="image" src="https://github.com/user-attachments/assets/c3a96de3-9202-4963-88e7-006be1a42d0f">

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Wjp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-601796480-20241001%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727776615562%22,%22to%22:%221727863015562%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by volgariver6** [comment]
> date 10.1 job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11123634459/job/30943462783 1.tpch 1T load时间报错 <img alt="企业微信截图_d5e2cfda-41d3-4a44-81b1-c7f0731337c0" width="1046" src="https://private-user-images.githubusercontent.com/113406637/372722954-484d1751-da62-4a0d-9422-5943df8da1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg3MjAsIm5iZiI6MTcyODM3ODQyMCwicGF0aCI6Ii8xMTM0MDY2MzcvMzcyNzIyOTU0LTQ4NGQxNzUxLWRhNjItNGEwZC05NDIyLTU5NDNkZjhkYTFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2NlNmMyNjk5MjU5YmFhYjgwNzdjYmQ0MzNmNTAyY2QxOTQ5NmE3NjJjOGJjNjNjMTM1YWM2OTk0ZTA4MWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-2FA4PNcExm8OptQaH5c5ius4yy4MRyeJX1NK6TaLgE">
> 
> 查看内存没有占满 <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/113406637/372722829-9c47af3d-d243-4f9d-9363-8cfb7d80672d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg3MjAsIm5iZiI6MTcyODM3ODQyMCwicGF0aCI6Ii8xMTM0MDY2MzcvMzcyNzIyODI5LTljNDdhZjNkLWQyNDMtNGY5ZC05MzYzLThjZmI3ZDgwNjcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjMzZDA4ZDlkMjQ0NzI5ODc5ZTE4NWUzZDg3MzVmYTEyYzk1MmIwN2FmYzJiNTkyZDY4NDYwY2ZhNGEyNTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iBQ1WnxFh7QxjZbKpMO6O36etz5u75jh2G20K8sRIis">
> 
> 2.sysbench也和昨天一样报错 <img alt="企业微信截图_7b366c6f-417a-491d-9081-5b243126a437" width="1082" src="https://private-user-images.githubusercontent.com/113406637/372723337-96095b9d-39c4-4712-b028-f1d87c88c42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg3MjAsIm5iZiI6MTcyODM3ODQyMCwicGF0aCI6Ii8xMTM0MDY2MzcvMzcyNzIzMzM3LTk2MDk1YjlkLTM5YzQtNDcxMi1iMDI4LWYxZDg3Yzg4YzQyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjQ5MmViMmYwN2YwZWM4MzJiMWUyY2I2MGUyNmZiNTVhMjljNzc5NjYyN2Y2NWY0Mjk0YjcyY2FlYTdlN2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AWnDzKiEtqHhmG5KnEvpyvJ1Dbs1k0ci2xbQZlSAhYQ"> <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/113406637/372723261-c3a96de3-9202-4963-88e7-006be1a42d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg3MjAsIm5iZiI6MTcyODM3ODQyMCwicGF0aCI6Ii8xMTM0MDY2MzcvMzcyNzIzMjYxLWMzYTk2ZGUzLTkyMDItNDk2My04OGU3LTAwNmJlMWE0MmQwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2UzZjdlYWU0ZDNiNWJhMWFjMjdlYzRiYTMzZDVjYTAzNWE5ZmNmNjAxYzZkN2QzZjBhZmY5YmM3MGQwZDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CQlflOQC_U6WPb20svX3F39tuNYbV1hs4jHNDlzDKGA">
> 
> mo log： https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Wjp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-601796480-20241001%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727776615562%22,%22to%22:%221727863015562%22%7D%7D%7D&schemaVersion=1&orgId=1

这个job的日志中找不到联系不到cn导致的问题，应该是别的原因导致的。麻烦 @iamlinjunhong 分析一下，如果是因为cn心跳的问题导致的，再转给我

**Comment by zhangxu19830126** [comment]
https://grafana.ci.matrixorigin.cn/goto/SF0RjrzHR?orgId=1 ，这里，通信的时候，在hakeeperl 里面找不到cn的地址了。

**Comment by zhangxu19830126** [comment]
所以认为这个cn不在了，就会不让提交

**Comment by tom-csf** [comment]
我在测试pitr也发现类似问题 感觉和负载没有关系
头天晚上做完pitr 测试 环境正常 第二天早上进入创建create db 报错， 连续2天都遇到
![Uploading 企业微信截图_a3815395-4c70-4268-965f-9e0ddd0ed633.png…]()

**Comment by tom-csf** [comment]
今天下午又遇到此类场景 从log 判断是dn 内存使用过大，但是系统一直都是空运行的。我后面重启dn 发现dn的内存一直在缓慢的增长 并没有下降的情况 是否存在dn 内存泄露的可能性

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19250

**Comment by heni02** [comment]
该单较久先关闭，同类问题使用这个问题单跟踪##19479
