### ISSUE TITLE
[Bug]: [date 10.2]1.2-dev tke regression: create table or drop database reported cannot commit a orphan transaction

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19138]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

b0f3a5481

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11142247340/job/30999607062
<img width="1105" alt="企业微信截图_de937d97-8f28-406b-af0b-5ce95c92a3a1" src="https://github.com/user-attachments/assets/91ce256b-ce3b-4248-a009-7d439637e925">
<img width="1039" alt="企业微信截图_96065f72-f703-4a75-b908-37bf27df999d" src="https://github.com/user-attachments/assets/74098f30-8363-485e-859c-1324871f24c8">

log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Wjp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-b0f3a5481-20241002%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221727920080000%22,%22to%22:%221727921410000%22%7D%7D%7D&schemaVersion=1&orgId=1

这个时间段内存cn使用最高34G
https://grafana.ci.matrixorigin.cn/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-branch-nightly-b0f3a5481-20241002&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki&from=1727920020000&to=1727921428000
<img width="693" alt="image" src="https://github.com/user-attachments/assets/62b91d74-ba5b-4609-a764-8528f79a1f69">

### Steps to Reproduce

```Markdown
tke regression sysbench1000w
```

**Comment by iamlinjunhong** [comment]
正在处理

**Comment by iamlinjunhong** [comment]
调整 gc 参数

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/matrixone/pull/19250

**Comment by heni02** [comment]
该单较久先关闭，同类问题使用这个问题单跟踪#19479
