### ISSUE TITLE
[Bug]: [date 10.1]tke regression: 3cn tpch1T Q18 cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19136]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

601796480

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11123634459/job/30908995881
第一次oom：
<img width="1089" alt="企业微信截图_14e1f432-5f65-4d4f-a70e-d1b100e79c91" src="https://github.com/user-attachments/assets/af4dbd10-3b7f-4968-aa01-d29b37924cb5">

第二次oom：
<img width="1076" alt="企业微信截图_c543bfe9-7502-49f0-91cf-50d141a77f39" src="https://github.com/user-attachments/assets/b3dbd4d6-5bb5-4726-892f-bd949c956a3b">

两个cn oom：
<img width="1394" alt="企业微信截图_c4b1c983-7315-40a5-9d9d-55b3c428e6e3" src="https://github.com/user-attachments/assets/db1d3085-5f9a-4ca0-8890-7353ba33011a">

21:14:35和21:15:05的profile文件：
[hn_download_tmp.zip](https://github.com/user-attachments/files/17219459/hn_download_tmp.zip)

### Steps to Reproduce

```Markdown
tke 3cn tpch1T test
```

**Comment by badboynt1** [comment]
已经修复了

**Comment by heni02** [comment]
confirm，closed
commit：nightly-e1acf0abe
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11442477628/job/31839588042
