### ISSUE TITLE
[Bug]: proxy crashed by oom during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19140]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fdf95b4ffcc06f953922b7274a87e9b974ccf163

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

proxy crashed by oom during stability test on distributed mode 

<img width="586" alt="image" src="https://github.com/user-attachments/assets/b62f947f-f826-4d75-902b-ee43cbc043b7">

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/0619fb96-69a6-4822-842c-2dd0b3d47c47">

dashborad link:
https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-b0855d2-202410052005&from=1728184224031&to=1728191220118

profile:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22wGl%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%20%3D%20%27stability-regression-dis-proxy-htlrz%27%7D%22,%22profileTypeId%22:%22memory:alloc_space:bytes:space:bytes%22,%22queryType%22:%22both%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221728184224000%22,%22to%22:%221728191220000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
@a re-profile-interval

**Comment by volgariver6** [comment]
@aressu1985 麻烦动哥加一下proxy的启动参数 -profile-interval ，然后再跑一下

**Comment by aressu1985** [comment]
malloc profile:
[10-08-2024-10-28-01_files_list.zip](https://github.com/user-attachments/files/17286551/10-08-2024-10-28-01_files_list.zip)

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
