### ISSUE TITLE
[Bug]: Instance crash during a query with PI() in WHERE clause

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1914]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a double,b float);
insert into t1 values(3.14,3.14159);
insert into t1 values(3.141593,3.14159);
select * from t1 where a<pi();
ERROR 2013 (HY000): Lost connection to MySQL server during query

### Additional information

panic: runtime error: index out of range [1] with length 1

goroutine 24510 [running]:
github.com/matrixorigin/matrixone/pkg/vectorize/lt.float64Lt({0xc0125a2014, 0x10, 0x0}, {0xc00a42cfd0, 0xc000443b28, 0xcb0e8a}, {0xc00a42cff0, 0x2347360, 0x3988201})
	/root/matrixone/pkg/vectorize/lt/lt.go:1271 +0x89
github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/overload.initLt.func10(0xc009642cc0, 0xc014f29020, 0xc000501290, 0x90, 0x12)
	/root/matrixone/pkg/sql/colexec/extend/overload/lt.go:694 +0x706
github.com/matrixorigin/matrixone/pkg/sql/colexec/extend/overload.BinaryEval(0xc009a43540, 0xd, 0xd, 0xca, 0x0, 0xc009642cc0, 0xc014f29020, 0xc00a85ab01)
	/root/matrixone/pkg/sql/colexec/extend/overload/binary.go:59 +0x3f4
github.com/matrixorigin/matrixone/pkg/sql/colexec/extend.(*BinaryExtend).Eval(0xc015d019b0, 0x15838e13c83ece, 0xc0008d95b0)
	/root/matrixone/pkg/sql/colexec/extend/binary.go:60 +0xde
github.com/matrixorigin/matrixone/pkg/sql/colexec/restrict.Call(0xc000501290, {0x22c03c0, 0xc015d01bc0})
	/root/matrixone/pkg/sql/colexec/restrict/restrict.go:115 +0x5ec
github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform.preprocess(0xc0852f240fab4dd2, 0xc00ac1a1e0)
	/root/matrixone/pkg/sql/viewexec/transform/transform.go:319 +0x3b
github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform.(*Container).processBare(...)
	/root/matrixone/pkg/sql/viewexec/transform/transform.go:83
github.com/matrixorigin/matrixone/pkg/sql/viewexec/transform.Call(0x1fc700a, {0x22c18c0, 0xc00ac1a1e0})
	/root/matrixone/pkg/sql/viewexec/transform/transform.go:72 +0xa9
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0003281b0, 0x2, 0x2}, 0x2)
	/root/matrixone/pkg/vm/vm.go:48 +0x9c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc000443f40, {0x28de6f0, 0xc00a836aa0}, 0xc000501290)
	/root/matrixone/pkg/vm/pipeline/pipeline.go:84 +0x1db
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x191692e, {0xc00325e440, 0x28fac28})
	/root/matrixone/pkg/sql/compile/scope.go:436 +0xb7
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0xc0008d97b8)
	/root/matrixone/pkg/sql/compile/scope.go:450 +0x2a
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/root/matrixone/pkg/sql/compile/scope.go:449 +0x175

**Comment by domingozhang** [comment]
ln() and log() have the same issue

mysql> select * from t1 where a=ln(1);
ERROR 2013 (HY000): Lost connection to MySQL server during query


mysql> select * from t1 where a=log(1);
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by domingozhang** [comment]
Also happend with exp()

mysql> select * from t1 where a>exp(1);
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by yingfeng** [comment]
@broccoliSpicy could check it at first and reassign it to author of PR

**Comment by m-schen** [comment]
This is not a problem with the implementation of the function itself.
PI() or exp() or some other functions will return a constant value, their result cannot be recognized as a constant now.
Maybe we can add an extra check logic while evaluating binary expression (at the front of Eval function of binary expression.)
likes
`if len(left_vector) == 1 then left is const.`.
but this may cause a repeated type check.
