### ISSUE TITLE
[Bug]: sysbench 100w  random ranges perf decreased from 1800 to 60 on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19141]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b0855d26f155a182bda6340025c00005584c58b7

### Other Environment Information

```Markdown
- Hardware parameters: 64C 256G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11193969177/job/31119944496

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/1a45eb58-a46d-411d-b21a-70e2dcb25254">

cpu profile:
[cpu.tar.gz](https://github.com/user-attachments/files/17268491/cpu.tar.gz)

### Steps to Reproduce

```Markdown
run sysbench 100w random ranges 100 threads test
```

**Comment by badboynt1** [comment]
需要优化between谓词的实现，支持多个range作为参数
另外还可以做个优化，对多个range进行合并，对tpch q19有优化效果

**Comment by aressu1985** [comment]
fixed
