### ISSUE TITLE
[Bug]: restore from pitr panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19157]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b0855d26f155a182bda6340025c00005584c58b7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/a695f725-748a-4bab-aae8-53e2fac75b42">
出错对应的时间戳（2024-10-08 16:20:01.560166）可以读到数据：
<img width="678" alt="image" src="https://github.com/user-attachments/assets/815847d5-c545-4253-b914-74a72c81c978">

log：
[test.txt.tar.gz](https://github.com/user-attachments/files/17290867/test.txt.tar.gz)

### Steps to Reproduce

```Markdown
测试步骤文档 私发

panic的sql：restore account acc01 from pitr p01 '2024-10-08 16:20:01.560166';

注：测试前修改代码，设置GC间隔时间
<img width="705" alt="企业微信截图_d54a6fc9-0ab2-440d-9dd2-3399c9d49f4d" src="https://github.com/user-attachments/assets/2e08abbf-4c07-4e33-a060-b272283316fc">

etc/launch/tn.toml中添加配置
[tn.Ckp]
flush-interval = "10s"
min-count = 100
scan-interval = "5s"
incremental-interval = "30s"
global-min-count = 9

[tn.GCCfg]
gc-ttl = "5m"
scan-gc-interval = "2m"
check-gc = true
```

**Comment by triump2020** [comment]
Wait for pr ,  the cause had been found.

**Comment by triump2020** [comment]
Wait for pr merge.

**Comment by triump2020** [comment]
Pr is merging.

**Comment by triump2020** [comment]
@Ariznawlll  Pls test.

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
这两天测试没再出现
