### ISSUE TITLE
[Bug]: Performance: Stand-alone Sysbench_1000w performance dropped by about 200%

### ISSUE THREAD

**Issue by x030911** [matrixorigin/matrixone#19154]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f494c0d47674f223339778fb2790ea6daadf9734

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

单机性能下降
![image](https://github.com/user-attachments/assets/24d188fb-9464-470d-9c9d-3db520a631cb)
![image](https://github.com/user-attachments/assets/5e33a575-e14b-4af7-8c8d-4b2db75c0005)

### Expected Behavior

No response

### Steps to Reproduce

```Markdown
单机128 Sysbench_1000w test
```

**Comment by x030911** [comment]
二分结果，下面记录Sysbench_1000w.point_select_100数据 @badboynt1 cc
![image](https://github.com/user-attachments/assets/9c2b2887-889b-4628-ad60-d2fc4c8a26d6)

**Comment by badboynt1** [comment]
fixed
