### ISSUE TITLE
[Bug]: bvt fail in retention

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#19161]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="995" alt="image" src="https://github.com/user-attachments/assets/7696b9ea-2e6d-4bb8-b2e9-636c2560d813">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11232503267/job/31224254599?pr=19158
```

**Comment by Ariznawlll** [comment]
@w-zr 麻烦帮忙看下

**Comment by badboynt1** [comment]
repro in https://github.com/matrixorigin/matrixone/actions/runs/11338513865/job/31531860899?pr=19164

**Comment by w-zr** [comment]
> repro in https://github.com/matrixorigin/matrixone/actions/runs/11338513865/job/31531860899?pr=19164

This is not the same issue.
![image](https://github.com/user-attachments/assets/9ee808f6-91c3-4ced-887b-f2cd0dab1522)

**Comment by w-zr** [comment]
duplicate with #19128, #18886
