### ISSUE TITLE
[Bug]: optimize create_time and modified_time to local time in show pitr.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19187]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

44b636721

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/cc9c9045-e375-40c3-aa05-8e55f2690bc0">

这个时间现在展示的是utc时间，改成utc+8会方便观看.

### Steps to Reproduce

```Markdown
create pitr p01 range 4 'h';
show pitr;
```

**Comment by YANGGMM** [comment]
mysql> select * from mo_catalog.mo_pitr;
+--------------------------------------+-----------+----------------+---------------------+---------------------+---------+------------+--------------+---------------+------------+--------+-------------+-----------+
| pitr_id                              | pitr_name | create_account | create_time         | modified_time       | level   | account_id | account_name | database_name | table_name | obj_id | pitr_length | pitr_unit |
+--------------------------------------+-----------+----------------+---------------------+---------------------+---------+------------+--------------+---------------+------------+--------+-------------+-----------+
| 01927441-b7dd-70fd-8772-505aea023c73 | p01       |              0 | 2024-10-10 02:28:36 | 2024-10-10 02:28:36 | account |          0 | sys          |               |            |      0 |           1 | h         |
+--------------------------------------+-----------+----------------+---------------------+---------------------+---------+------------+--------------+---------------+------------+--------+-------------+-----------+
1 row in set (0.00 sec)

mysql> show pitr;
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
| PITR_NAME | CREATED_TIME        | MODIFIED_TIME       | PITR_LEVEL | ACCOUNT_NAME | DATABASE_NAME | TABLE_NAME | PITR_LENGTH | PITR_UNIT |
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
| p01       | 2024-10-10 10:28:36 | 2024-10-10 10:28:36 | account    | sys          | *             | *          |           1 | h         |
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
1 row in set (0.01 sec)

**Comment by Ariznawlll** [comment]
```
mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 65d60e530     |
+---------------+
1 row in set (0.00 sec)
```

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/893f9a02-36bc-41b1-ad3b-102fad7747d0">

测试通过✅
