### ISSUE TITLE
[Tech Request]: memory leak in malloc profiler

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#19188]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Same call stacks may have different PCs, causing memory leaks in the profiler.
```

**Comment by sukki37** [comment]
https://grafana.matrixonecloud.cn/goto/OndWoXzHg?orgId=1

<img width="1871" alt="image" src="https://github.com/user-attachments/assets/cd4ade13-6936-4b79-938d-e8e3cd9b9701">

**Comment by reusee** [comment]
fixed
