### ISSUE TITLE
[Bug]: mo_cdc: drop mo table when cdc task status is running,  there are no errors reported in the log 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19184]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

256ebd81809b57a737c3f3f851ce60bcd3a9566e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

同步任务状态为running，下游已经同步到了数据
<img width="455" alt="企业微信截图_3b4ab6e4-f4e2-4287-9950-91443ae71e5f" src="https://github.com/user-attachments/assets/24b35a40-c26f-47cf-9331-1c383181e106">
此时drop上游mo的表，show task显示如下
<img width="1239" alt="企业微信截图_2f84899b-54f6-4591-b666-b315077b5e69" src="https://github.com/user-attachments/assets/a2c369f1-081b-471d-ba21-5de97904ed71">
查看相关日志没有上游表不存在的日志
http://10.222.6.1/explore?panes=%7B%22VCp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728464760479%22,%22to%22:%221728464930653%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
见Actual Behavior
```

**Comment by ck89119** [comment]
err log是能找到的
<img width="1839" alt="image" src="https://github.com/user-attachments/assets/37863355-a2e0-484a-be80-284bd817d2de">

但是state确实还是running，与产品确认当前先保持现状

**Comment by heni02** [comment]
confirm,closed
