### ISSUE TITLE
[Bug]: mo didn't parse 1eX correctly, causing sql execution to get stuck.

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#19186]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
drop database if exists test; create database test; use test;
create table test (id int);
insert into test select result from generate_series(1,1e2) g; 
```

<img width="1647" alt="image" src="https://github.com/user-attachments/assets/6d9eb93a-1ac7-4571-a39b-14a9995efea1">

mo-service.log的表现看到不断地尝试申请更大的incr-service的cache. 已经远远大于1e2的范畴. 

### Steps to Reproduce

```Markdown
drop database if exists test; create database test; use test;
create table test (id int);
insert into test select result from generate_series(1,1e2) g; 
```

**Comment by jensenojs** [comment]
<img width="938" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/a32eadee-aa15-4f7c-a480-294b20b540d3">

调试跟进去, 发现是把1e2对应的浮点数直接当int64去解析了

**Comment by jensenojs** [comment]
补充一个问题
```shell
mysql> drop database if exists test; create database test; use test;
Query OK, 1 row affected (0.04 sec)

create table test (id int);
insert into test select result from generate_series(1,100.0) g; Query OK, 1 row affected (0.02 sec)

Database changed
mysql> create table test (id int);
Query OK, 0 rows affected (0.01 sec)

insert into test select result from generate_series(1,100.0) g; mysql> insert into test select result from generate_series(1,100.0) g;
Query OK, 1000 rows affected (0.01 sec)

mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| test           |
+----------------+
1 row in set (0.00 sec)

mysql> select count(*) from test;
+----------+
| count(*) |
+----------+
|     1000 |
+----------+
1 row in set (0.01 sec)

mysql>
```

**Comment by aressu1985** [comment]
mysql> create database test;
Query OK, 1 row affected (0.07 sec)

mysql> use test;
Database changed
mysql> ll
    -> ;
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 2 near "ll";
mysql> 
mysql> 
mysql> drop database if exists test; create database test; use test;
Query OK, 1 row affected (0.09 sec)

Query OK, 1 row affected (0.06 sec)

Database changed
mysql> create table test (id int);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into test select result from generate_series(1,1e2) g; 
ERROR 20301 (HY000): invalid input: generate_series end must be int32 or int64
mysql>
