### ISSUE TITLE
[Bug]: active mo start failed by panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19190]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

936bfb8506ed9ee8877818c9699e06b5db9ab857

### Other Environment Information

```Markdown
- Hardware parameters: 
- OS type:
- Others:
```

### Actual Behavior

When standy mo changed as active mo after transfering logtail data， the mo started failed:
{"level":"INFO","time":"2024/10/09 20:25:00.730862 +0800","caller":"v2/checkpoint.go:565","msg":"[MergeCheckpoint]","operation":"GC checkpoint","operand":"CKP[I][2][ckp 516, truncate 0](1728459553592880294-1->1728459803593793186-0)"}
{"level":"INFO","time":"2024/10/09 20:25:00.731575 +0800","caller":"v2/checkpoint.go:565","msg":"[MergeCheckpoint]","operation":"GC checkpoint","operand":"CKP[I][2][ckp 366, truncate 0](1728459273593609168-1->1728459553592880294-0)"}
{"level":"INFO","time":"2024/10/09 20:25:00.732647 +0800","caller":"v2/checkpoint.go:565","msg":"[MergeCheckpoint]","operation":"GC checkpoint","operand":"CKP[I][2][ckp 103, truncate 0](0-0->1728459273593609168-0)"}
panic: runtime error: index out of range [0] with length 0

goroutine 3435 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).GetInputs(0x84ea920?)
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:365 +0xb7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).mergeCheckpointFiles(0xc0c3523400, {0x1, 0x0, 0x0, 0x0, 0x76, 0xdd, 0x2c, 0x5d, 0x1c, ...}, ...)
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:651 +0xb68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).tryGC(0xc0c3523400, 0xc0419d8540, 0xc01816ef20)
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:747 +0x29b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).TryGC(0xc0c3523400)
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:706 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*DiskCleaner).process(0xc0cb3bb200, {0xc0cd0e8008?, 0x1, 0xc047782600?})
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/db/gc/v2/diskcleaner.go:84 +0x7c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1ea
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 866
	/mnt/disk1/standby/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xe5

[mo-service.log](https://github.com/user-attachments/files/17308192/mo-service.log)

### Steps to Reproduce

```Markdown
1. start a mo with standlone mode on service1
2. run a no-voting logserivce on service2
3. create 3 accounts and load tpcc, tpch, tpch and run tpcc,sysbench test for 3 hours
4. stop active mo
5. transfer no-voting logservice data to standby logservice
6. start standby mo
```

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
