### ISSUE TITLE
[Bug]: TN panic: fake primary key not existed

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#19192]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e08947032

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2024-10-10T09:58:49+08:00	panic: fake primary key not existed
2024-10-10T09:58:49+08:00	
2024-10-10T09:58:49+08:00	goroutine 4545 [running]:
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Schema).getFakePrimaryKey(...)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog/schema.go:321
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*Schema).GetPrimaryKey(...)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog/schema.go:331
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.HandleSyncLogTailReq({0x55cf160, 0xc02c913650}, {0x7fd50fb5d3b0, 0xc003f021e0}, 0xc007144300, 0xc0063489c0, {0xc02c919d40, 0xc02c919d70, 0xc02c9136c0, {}, ...}, ...)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/handle.go:141 +0x13d8
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*LogtailerImpl).TableLogtail(_, {_, _}, {0x477de, 0x477fc, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...}, ...)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/logtailer.go:91 +0x245
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).getSubLogtailPhase.func2()
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service/server.go:516 +0x10a
2024-10-10T09:58:49+08:00	runtime/trace.WithRegion({0x55cf0b8?, 0xc0177ee5a0?}, {0x4d6096b, 0x19}, 0xc02c5bfc08)
2024-10-10T09:58:49+08:00		/usr/local/go/src/runtime/trace/annotation.go:141 +0xd1
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/common/moprobe.WithArgAndFn({0x55cf0b8, 0xc0177ee5a0}, 0x5, 0x0, 0x0, 0xc02c5bfc08)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/common/moprobe/probe.go:99 +0x85
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/common/moprobe.WithRegion(...)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/common/moprobe/probe.go:88
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).getSubLogtailPhase(0xc016924000, {0x55cf0b8, 0xc0177ee5a0}, {0x4e948f70b229, {0xc02c90d580, 0xd}, 0xc02c919cb0, 0xc0176c8c00}, {0x0, 0x0, ...}, ...)
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service/server.go:515 +0x31a
2024-10-10T09:58:49+08:00	github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).pullLogtailsPhase1(0xc016924000, {0x55cf0b8, 0xc0177ee5a0}, {0x4e948f70b229, {0xc02c90d580, 0xd}, 0xc02c919cb0, 0xc0176c8c00})
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service/server.go:417 +0x329
2024-10-10T09:58:49+08:00	created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailServer).logtailPullWorker in goroutine 1798
2024-10-10T09:58:49+08:00		/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service/server.go:400 +0x57
```

log: 
[tn.log.txt](https://github.com/user-attachments/files/17320745/tn.log.txt)

### Expected Behavior

TN should not panic

### Steps to Reproduce

```Markdown
checkout https://grafana.cn-dev.matrixone.tech/goto/p-XX_rkHg?orgId=1
```

**Comment by aylei** [comment]
{"level":"INFO","time":"2024/10/10 02:04:46.840455 +0000","name":"tn-service.logtail-server","caller":"service/server.go:411","msg":"handle subscription asynchronously","service":"36323365-3530-6635-6534-383637336132","uuid":"36323365-3530-6635-6534-383637336132","server-id":"0192742b-e466-7e5b-bdce-18fb7742b69c","table":"db_id:292431 tb_id:292470 "}

**Comment by jiangxinmeng1** [comment]
误订阅了view。view没有pk导致panic
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/04eb067a-ea86-42d1-80e0-f3a59360b10e">

**Comment by YANGGMM** [comment]
<img width="1333" alt="企业微信截图_0757d5d8-4190-4e58-ab1f-0fbcfa95fecc" src="https://github.com/user-attachments/assets/4b77a161-722f-490a-82a2-9879c06b717d">

**Comment by YANGGMM** [comment]
mysql> select statement from statement_info where request_at >= '2024-10-10 01:58:40' and request_at <= '2024-10-10 01:58:50' and statement like '%sql_statement_total%';
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| /* QPS */ SELECT `stat_ts`, SUM(`value`)/60 as value FROM(SELECT concat(DATE_FORMAT(date_add(`collecttime`,Interval 1 MINUTE),'%Y-%m-%d %H'),':',LPAD(CAST(1 * floor(minute(date_add(`collecttime`,Interval 1 MINUTE)) / 1) as int),2,0),':00') AS stat_ts, sum(`value`) AS value, `node` FROM sql_statement_total WHERE `collecttime` >= '2024-10-10 01:28:00' AND `collecttime` <= '2024-10-10 01:58:00'   AND account = '01927426-1a92-7a0d-a2ad-b1dea9ddbb54' GROUP BY `node`, concat(DATE_FORMAT(date_add(`collecttime`,Interval 1 MINUTE),'%Y-%m-%d %H'),':',LPAD(CAST(1 * floor(minute(date_add(`collecttime`,Interval 1 MINUTE)) / 1) as int),2,0),':00')  ORDER BY concat(DATE_FORMAT(date_add(`collecttime`,Interval 1 MINUTE),'%Y-%m-%d %H'),':',LPAD(CAST(1 * floor(minute(date_add(`collecttime`,Interval 1 MINUTE)) / 1) as int),2,0),':00') LIMIT 100000)t GROUP BY `stat_ts` |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.02 sec)



但是手动执行不会报错
mysql> SELECT `stat_ts`, SUM(`value`)/60 as value FROM(SELECT concat(DATE_FORMAT(date_add(`collecttime`,Interval 1 MINUTE),'%Y-%m-%d %H'),':',LPAD(CAST(1 * floor(minute(date_add(`collecttime`,Interval 1 MINUTE)) / 1) as int),2,0),':00') AS stat_ts, sum(`value`) AS value, `node` FROM sql_statement_total WHERE `collecttime` >= '2024-10-10 05:40:00' AND `collecttime` <= '2024-10-10 06:10:00'   AND account = '019271ee-0018-75f3-968d-60a0a452b83d' GROUP BY `node`, concat(DATE_FORMAT(date_add(`collecttime`,Interval 1 MINUTE),'%Y-%m-%d %H'),':',LPAD(CAST(1 * floor(minute(date_add(`collecttime`,Interval 1 MINUTE)) / 1) as int),2,0),':00')  ORDER BY concat(DATE_FORMAT(date_add(`collecttime`,Interval 1 MINUTE),'%Y-%m-%d %H'),':',LPAD(CAST(1 * floor(minute(date_add(`collecttime`,Interval 1 MINUTE)) / 1) as int),2,0),':00') LIMIT 100000)t GROUP BY `stat_ts`;
+---------------------+-------+
| stat_ts             | value |
+---------------------+-------+
| 2024-10-10 05:41:00 |     0 |
| 2024-10-10 05:42:00 |     0 |
| 2024-10-10 05:43:00 |     0 |
| 2024-10-10 05:44:00 |     0 |
| 2024-10-10 05:45:00 |     0 |
| 2024-10-10 05:46:00 |     0 |
| 2024-10-10 05:47:00 |     0 |
| 2024-10-10 05:48:00 |     0 |
| 2024-10-10 05:49:00 |     0 |
| 2024-10-10 05:50:00 |     0 |
| 2024-10-10 05:51:00 |     0 |
| 2024-10-10 05:52:00 |     0 |
| 2024-10-10 05:53:00 |     0 |
| 2024-10-10 05:54:00 |     0 |
| 2024-10-10 05:55:00 |     0 |
| 2024-10-10 05:56:00 |     0 |
| 2024-10-10 05:57:00 |     0 |
| 2024-10-10 05:58:00 |     0 |
| 2024-10-10 05:59:00 |     0 |
| 2024-10-10 06:00:00 |     0 |
| 2024-10-10 06:01:00 |     0 |
| 2024-10-10 06:02:00 |     0 |
| 2024-10-10 06:03:00 |     0 |
| 2024-10-10 06:04:00 |     0 |
| 2024-10-10 06:05:00 |     0 |
| 2024-10-10 06:06:00 |     0 |
| 2024-10-10 06:07:00 |     0 |
| 2024-10-10 06:08:00 |     0 |
| 2024-10-10 06:09:00 |     0 |
| 2024-10-10 06:10:00 |     0 |
+---------------------+-------+
30 rows in set (0.06 sec)

**Comment by YANGGMM** [comment]
<img width="687" alt="image" src="https://github.com/user-attachments/assets/f7949016-0816-403b-b6f4-f0c1e7516d35">

<img width="659" alt="image" src="https://github.com/user-attachments/assets/c41de9fa-4b59-4ecc-9674-87bef5ecc3c3">

**Comment by aylei** [comment]
repro: execute ` SELECT reldatabase, sum(mo_table_size (reldatabase, relname)) AS size FROM `mo_catalog`.`mo_tables` WHERE relkind in ('cluster', 'v') AND reldatabase in ('mo_catalog', 'system', 'system_metrics') GROUP BY `reldatabase`; `

**Comment by gouhongshen** [comment]
该问题是因为 cn 订阅了 view，tn 处理 view 时出现了 panic， rootcase 还不清楚。

因为用户可能会使用 mo_table_size, mo_table_rows, mo_table_max_col, mo_table_min_col 订阅 view，所以先在这几个函数里面跳过 view 的计算。

**Comment by gouhongshen** [comment]
已经找到 root case。

整理下几个问题：
1. 为什么以前没有出现，最近出现了？
> main 里面合进去了一部分逻辑，tn 会在处理订阅时获取 table 的 primary key  seqnum，view 不存在 fake pk/pk，所以 panic了。

2. 有没有必有订阅 view，获取 logtail
> 不能在 view 上面 insert/update/delete 数据，所以 它 的 logtail 必然为空，所有涉及到 view 的 select 都会转换成 实体表 + condition。所以也就没有必要订阅 view

3. 跟 mo_table_size, rows, col_max, col_min 有什么关系？
> 目前发现了这几个函数会触发 订阅 view 的操作，可能还有其他地方会订阅。

4. 如何 fix
> 不订阅 view 即可。

**Comment by gouhongshen** [comment]
复现步骤， 单机即可：
```
在 fix 前后分别执行下面的代码

select rel_id, relkind, reldatabase, relname, mo_table_size(reldatabase, relname) from (select reldatabase, relname, rel_id, relkind, account_id from mo_catalog.mo_tables where relkind in ('r', 'v', 'e', 'cluster') and account_id = 0 order by relkind);


fix 前会panic，fix  后不会
```

**Comment by aressu1985** [comment]
fix 前：
<img width="752" alt="image" src="https://github.com/user-attachments/assets/d00b36f8-5d9f-4dc6-a935-e9b48e7eb101">

fix 后：
<img width="988" alt="image" src="https://github.com/user-attachments/assets/e9fd1f37-d617-434e-b395-4cf745ea3c1d">
