### ISSUE TITLE
[Bug]: WHERE clause doesn't work properly 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#1919]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c473412af2842cd3c5e5fad6ea0626c7bbd095d3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select year(d_datekey) as d_year, s_city, p_brand, sum(lo_revenue) - sum(lo_supplycost) as profit,c_region , s_nation, p_category
    -> from lineorder
    -> join dates on lo_orderdate = d_datekey
    -> join customer on lo_custkey = c_custkey
    -> join supplier on lo_suppkey = s_suppkey
    -> join part on lo_partkey = p_partkey
    -> where
    -> (year(d_datekey) = 1997 or year(d_datekey) = 1998)
    -> and p_category = 'MFGR#14'
    -> group by d_year, s_city, p_brand
    -> order by d_year, s_city, p_brand;
Empty set (2.91 sec)

Actually, MFG#14 exists in p_category column

![image](https://user-images.githubusercontent.com/88298673/159204344-0b2baac8-5096-4c0e-9259-565f19d7b95a.png)

Then I  modified the WHERE clause. Replace another column which value without #. Then I worked.

select year(d_datekey) as d_year, s_city, p_brand, sum(lo_revenue) - sum(lo_supplycost) as profit,c_region , s_nation, p_category
    -> from lineorder
    -> join dates on lo_orderdate = d_datekey
    -> join customer on lo_custkey = c_custkey
    -> join supplier on lo_suppkey = s_suppkey
    -> join part on lo_partkey = p_partkey
    -> where
    -> (year(d_datekey) = 1997 or year(d_datekey) = 1998)
    -> and s_nation='ALGERIA'
    -> group by d_year, s_city, p_brand
    -> order by d_year, s_city, p_brand
    -> limit 1000;

![image](https://user-images.githubusercontent.com/88298673/159204427-d47d66bd-aa30-4032-a0f6-3da98c2e543d.png)

**Comment by m-schen** [comment]
Separate where conditions can correctly handle data with # like `select * from t1 where a = 'a#b';`
It may be a hash table or grouping that is causing the problem
