### ISSUE TITLE
[Bug]: `SQL parser error: table \"__mo_index_unique_0192748f-6868-7182-a6de-2e457c2975c6\" does not exist` error is returned when running SQL

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#19206]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

v2.0.0-e08947032-2024-10-09

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The SQL is executed in account `01927400-16b3-7d3a-b47b-7e405633af0f` but returns the following error:
```
"error":"Error 1064 (HY000): SQL parser error: table \"__mo_index_unique_0192748c-a33a-756d-a04a-92998a6be15d\" does not exist","elapsed":"30.138120565s","rows":0,"sql":"ALTER TABLE `billing_records` MODIFY COLUMN `account_period` varchar(32)"
```

The application log: https://grafana.cn-dev.matrixone.tech/goto/J7QXHCkNg?orgId=1
The MO log: https://grafana.cn-dev.matrixone.tech/goto/oURjNCkHR?orgId=1

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by qingxinhome** [comment]
got it

**Comment by DanielZhangQD** [comment]
The same error is reported continuously in cloud env https://grafana.cn-dev.matrixone.tech/goto/xsuCkxiHg?orgId=1

**Comment by qingxinhome** [comment]
未复现，本地测试gorm程序能够成功

**Comment by qingxinhome** [comment]
等待韩枫侧对Relation()接口进行优化

**Comment by qingxinhome** [comment]
等待韩枫侧对Relation()接口进行优化

**Comment by daviszhen** [comment]
等hf优化后，再调整代码。2.0.1来不及

**Comment by aptend** [comment]
处理其它bug中

**Comment by qingxinhome** [comment]
https://github.com/matrixorigin/matrixone/issues/20194

**Comment by aptend** [comment]
pr https://github.com/matrixorigin/matrixone/pull/20145

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test

**Comment by qingxinhome** [comment]
2.0.1 QA升级演练时该问题再次出现：
<img width="1233" alt="企业微信截图_012ce980-5c43-49df-b29c-44aed7221378(1)" src="https://github.com/user-attachments/assets/f533461e-bcd2-401a-ae78-a46c5827a4a9" />
<img width="1208" alt="企业微信截图_34c415ab-2f17-443e-b3b3-cc29ab50c2d8(1)" src="https://github.com/user-attachments/assets/9a8d7527-92be-4dcc-9322-ae37665b4ec3" />

alter table 报错："SQL parser error: table \"__mo_index_secondary_0193b017-3039-759e-8505-f11f4e53838a\" does not exist",
日志链接：
https://grafana.cn-qa.matrixone.tech/explore?panes=%7B%22gKl%22:%7B%22datasource%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22freetier-01-s2-6475fc8dcb-cn-6m5nq%5C%22%7D%20%7C%3D%20%60ERROR%60%20%7C%3D%20%60does%20not%20exist%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733824800000%22,%22to%22:%221733835599000%22%7D%7D%7D&schemaVersion=1&orgId=1



https://grafana.cn-qa.matrixone.tech/explore?panes=%7B%22gKl%22:%7B%22datasource%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22freetier-01-s2-6475fc8dcb-cn-6m5nq%5C%22%7D%20%7C%3D%20%601cc219936ee29d71180fc63932de007f%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733824800000%22,%22to%22:%221733835599000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
问题原因发生在对目标表的索引表加锁时，无法获取索引表的relation造成：
![image](https://github.com/user-attachments/assets/71d4c7bf-389e-42b9-a5e3-663f22669725)

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @aressu1985 @heni02 @DanielZhangQD
