### ISSUE TITLE
[Bug]: create duplicate pitr duplicate can success

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19212]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8bb6702f139fbab46d8bbc81decd8a49448173ad

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create database abc;
create pitr pitr053 for database abc range 1 'y';
drop database abc;
create database abc;
create pitr pitr054 for database abc range 1 'd';

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/db2ea748-30e8-4208-9088-e93fd73e4534">

It is probabilistic occurrence

### Steps to Reproduce

```Markdown
create database abc;
create pitr pitr053 for database abc range 1 'y';
drop database abc;
create database abc;
create pitr pitr054 for database abc range 1 'd';
```

**Comment by YANGGMM** [comment]
fixed

**Comment by tom-csf** [comment]
验证已经bugfix
