### ISSUE TITLE
[Bug]: mo crashed after restore account acc01 to new account acc03.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19210]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

triump2020

### Commit ID

d1d27551afade12561a99188d008960b25b3ae7c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**执行恢复测试（现象看执行成功了，执行后mo退出，重新启动就报错panic了）：**
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/86fdf39f-b19e-4220-a156-83a505a9c5eb">

**重新启动mo，报错panic：**
ariznawl@AdeMacBook-Pro matrixone % ./mo-service -launch ./etc/launch/launch.toml > test.txt

panic: runtime error: slice bounds out of range [:923] with capacity 734

goroutine 1897 [running]:
github.com/matrixorigin/matrixone/pkg/objectio.GetColumnMeta(...)
	/Users/ariznawl/code/matrixone/pkg/objectio/column.go:42
github.com/matrixorigin/matrixone/pkg/objectio.BlockObject.ColumnMeta(...)
	/Users/ariznawl/code/matrixone/pkg/objectio/block.go:64
github.com/matrixorigin/matrixone/pkg/objectio.ReadOneBlockAllColumns({0x108c9b398, 0x14011b7b890}, 0x1401d259600, {0x14023051770, 0x2a}, 0x0, {0x1401d259a2c, 0x4, 0x1076a4fb9?}, 0xf, ...)
	/Users/ariznawl/code/matrixone/pkg/objectio/funcs.go:286 +0x55c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.LoadOneBlockWithIndex({0x108c9b398, 0x14011b7b890}, {0x108cf6f00, 0x1400c588f00}, {0x1401d259a2c, 0x4, 0x4}, {0x14002e7d514, 0x4f, 0x4f}, ...)
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/blockio/funcs.go:217 +0x12c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.BlockDataReadBackup({0x108c9b398, 0x14011b7b890}, 0x14002e7d500, {0x108cdb830, 0x140057ffd40}, {0x1401d259a2c?, 0x0?, 0x55?}, {0x0, 0x0, ...}, ...)
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/blockio/read.go:337 +0xbc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail.(*SnapshotMeta).GetPITR(0x1400fb03d50, {0x108c9b398, 0x14011b7b890}, {0x0?, 0x0?}, {0x0?, 0x0?, 0x10b55a520?}, {0x108cf6f00, 0x1400c588f00}, ...)
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/logtail/snapshot.go:754 +0x6dc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).GetPITRs(0x1400aa1edc0)
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:1076 +0x84
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).tryGC(0x1400aa1edc0, 0x1400c531f20, 0x1400d1ba8f0)
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:734 +0x148
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*checkpointCleaner).TryGC(0x1400aa1edc0)
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/db/gc/v2/checkpoint.go:706 +0x8c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/gc/v2.(*DiskCleaner).process(0x14022941840, {0x14022c32008?, 0x1, 0x1400650a6b0?})
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/db/gc/v2/diskcleaner.go:84 +0x7c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1a8
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 499
	/Users/ariznawl/code/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xec

mo-data数据：太大了，私发

日志：[test.txt](https://github.com/user-attachments/files/17324661/test.txt)

### Steps to Reproduce

```Markdown
步骤简单描述：
1. 创建account acc01 acc02;
2. sys租户为普通租户acc01创建pitr，range 4 'h';（创建时间为utc+8 "2024-10-10 11:48:33"）
3. acc01连接mo，向mo中导入测试数据；
4. 使用mo-backup工具将acc01租户的数据恢复新租户acc03，且时间戳为"2024-10-10 12:01:32.609469"
./mo_br pitr restore --host "127.0.0.1" --port 6001 --user "dump" --password "111" --pname "p01" --timestamp "2024-10-10 12:01:32.609469" --account "acc01" --new_account "acc03" --new_admin_name "test_account" --new_admin_password "111"

如需详细测试步骤，请联系我
```

**Comment by LeftHandCold** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing
