### ISSUE TITLE
[Bug]: ut failed in TestHandleKillZombie

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19214]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/df351b9d-1be8-4747-be1e-99bcef7e7a29)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11270496271/job/31341337202?pr=19197
```

**Comment by volgariver6** [comment]
fixed
