### ISSUE TITLE
[Bug]: restore acc01 to new account acc04，new account acc04 has no data.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19218]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7c6204dee68037c4803305a99cc591e51c83fe85

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

从打出来的日志看，底层执行的sql不对
<img width="987" alt="image" src="https://github.com/user-attachments/assets/a4d1c557-1e00-47e5-aa1d-29d5f3ca5d1b">

```
1. 创建租户acc01；
create account acc01 admin_name = 'test_account' identified by '111';
create account acc02 admin_name = 'test_account' identified by '111';

2. sys租户创建pitr for acc01;
create pitr p01 for account acc01 range 4 'h';

3. 向acc01租户中导入数据；

4. sys租户恢复acc01租户的数据到新租户
mo-backup工具中执行
./mo_br pitr restore --host "127.0.0.1" --port 6001 --user "dump" --password "111" --pname "p01" --timestamp "2024-10-10 17:45:00" --account "acc01" --new_account "acc04" --new_admin_name "test_account" --new_admin_password "111"  --log_level "debug"

5. acc04 connect mo
show databases;
```

### Steps to Reproduce

```Markdown
see actual behavior.
```

**Comment by YANGGMM** [comment]
drop account if exists acc01;
create account acc01 admin_name = 'test_account' identified by '111';
drop account if exists acc02;
create account acc02 admin_name = 'test_account' identified by '111';

create pitr pitr01 for account acc01 range 1 'h';

mysql -h127.0.0.1 -uacc01:test_account -P6001 -p111
drop database if exists db01;
create database db01;
use db01;
create table table01 (col1 int, col2 enum ('a','b','c'));
insert into table01 values(1,'a');
insert into table01 values(2, 'b');
create table table02 (col1 int, col2 enum ('a','b','c'));
insert into table02 values(1,'a');
insert into table02 values(2, 'b');
drop database if exists db02;
create database db02;
use db02;
create table index01(col1 int,key key1(col1));
insert into index01 values (1);
insert into index01 values (2);
show databases;

<img width="257" alt="image" src="https://github.com/user-attachments/assets/4679bd75-e737-47d6-bbc0-9aab6af6be42">

show pitr;
select now();
restore account acc02 from pitr pitr01 '2024-10-12 09:51:37.972647';

mysql -h127.0.0.1 -uacc02:test_account -P6001 -p111
show databases;

<img width="379" alt="image" src="https://github.com/user-attachments/assets/d07c0c00-6039-4c0e-abfa-fdfbe5d306f2">


restore success;

**Comment by YANGGMM** [comment]
pitr tool 验证：

<img width="970" alt="image" src="https://github.com/user-attachments/assets/8c33f610-8067-4b76-8ffe-694fd2beb12e">

➜  ~ mysql -h127.0.0.1 -uacc03:test_account -P6001 -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 25
Server version: 8.0.30-MatrixOne-v1.3.0 MatrixOne

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| db01               |
| db02               |
| information_schema |
| mo_catalog         |
| mysql              |
| system             |
| system_metrics     |
+--------------------+
7 rows in set (0.01 sec)

restore 成功，可以转测

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**测试环境：本地单机**
**commit：6359b6261**
**测试步骤**
```
sys租户下执行：

mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 6359b6261     |
+---------------+
1 row in set (0.00 sec)

drop account if eixsts acc01;
create account acc01 admin_name = 'test_account' identified by '111';
drop account if eixsts acc02;
create account acc02 admin_name = 'test_account' identified by '111';
create pitr p01 for account acc01 range 4 'h';

mysql> show pitr;
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
| PITR_NAME | CREATED_TIME        | MODIFIED_TIME       | PITR_LEVEL | ACCOUNT_NAME | DATABASE_NAME | TABLE_NAME | PITR_LENGTH | PITR_UNIT |
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
| p01       | 2024-10-12 10:28:38 | 2024-10-12 10:28:38 | account    | acc01        | *             | *          |           4 | h         |
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
1 row in set (0.02 sec)

acc01租户：
drop database if exists db04;
create database db04;
use db04;
create table table01(col1 int primary key );
insert into table01 values (1);
insert into table01 values (2);
drop database if exists db05;
create database db05;
use db05;
create table table01(col1 int primary key );
insert into table01 values (1);
insert into table01 values (2);
drop database if exists db06;
create database db06;
use db06;
create table table01(col1 int primary key );
insert into table01 values (1);
insert into table01 values (2);
select * from db04.table01;
select * from db05.table01;
select * from db06.table01;

sys租户，恢复acc01到新租户acc02
restore account acc02 from pitr p01 '2024-10-12 10:30:56.223707';
```
**恢复成功**
<img width="772" alt="image" src="https://github.com/user-attachments/assets/dab2e7f7-d919-48e1-9da1-1bcb0346dc7a">
<img width="907" alt="image" src="https://github.com/user-attachments/assets/846eb911-8266-4b17-8923-e5376aebda5e">

**恢复到acc02后，acc02中可以看到恢复数据，sql测试通过**

**Comment by Ariznawlll** [comment]
**工具测试：**
**测试环境：本地单机**
**commit：6359b6261**
**测试步骤**
```
sys租户下执行：

mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 6359b6261     |
+---------------+
1 row in set (0.00 sec)

drop account if eixsts acc01;
create account acc01 admin_name = 'test_account' identified by '111';
drop account if eixsts acc02;
create account acc02 admin_name = 'test_account' identified by '111';
mo-backup工具端创建pitr，执行命令：
 ./mo_br pitr create --host "127.0.0.1" --port 6001 --user "dump" --password "111" --pname "p02" --level "account" --account "acc01" --rangevalue 10 --rangeunit "h"

mysql> show pitr;
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
| PITR_NAME | CREATED_TIME        | MODIFIED_TIME       | PITR_LEVEL | ACCOUNT_NAME | DATABASE_NAME | TABLE_NAME | PITR_LENGTH | PITR_UNIT |
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
| p02       | 2024-10-12 11:16:26 | 2024-10-12 11:16:26 | account    | acc01        | *             | *          |          10 | h         |
+-----------+---------------------+---------------------+------------+--------------+---------------+------------+-------------+-----------+
1 row in set (0.01 sec)

acc01租户：
drop database if exists db04;
create database db04;
use db04;
create table table01(col1 int primary key );
insert into table01 values (1);
insert into table01 values (2);
drop database if exists db05;
create database db05;
use db05;
create table table01(col1 int primary key );
insert into table01 values (1);
insert into table01 values (2);
drop database if exists db06;
create database db06;
use db06;
create table table01(col1 int primary key );
insert into table01 values (1);
insert into table01 values (2);
select * from db04.table01;
select * from db05.table01;
select * from db06.table01;

sys租户，恢复acc01到新租户acc02
mo-backup工具端执行命令：
 ./mo_br pitr restore --host "127.0.0.1" --port 6001 --user "dump" --password "111" --pname "p02"  --timestamp "2024-10-12 11:17:33.994109"  --account "acc01" --new_account "acc02" --new_admin_name "test_account" --new_admin_password "111"  --log_level "debug"
```
**恢复成功**
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/5f6c242d-34ba-46c2-96bf-dcdd65527449">
使用acc02连接mo，查看数据：
<img width="957" alt="image" src="https://github.com/user-attachments/assets/2ab4d276-00fd-4688-bea5-2693934260c6">

**恢复成功，测试通过✅**
