### ISSUE TITLE
[Bug]: bvt fail in join order

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#19221]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/bd9f209b-c254-47c7-8958-ad08d1115933">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11271245720/job/31343694713?pr=19196
```

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11304161974/job/31442176577?pr=19273

**Comment by badboynt1** [comment]
still repro 
![image](https://github.com/user-attachments/assets/c2afef08-4f83-4531-b717-502d7f3229dc)

https://github.com/matrixorigin/matrixone/actions/runs/11320904735/job/31479176925?pr=19297

**Comment by zengyan1** [comment]
待观察

**Comment by badboynt1** [comment]
repro in https://github.com/matrixorigin/matrixone/actions/runs/11412994165/job/31759898572?pr=19433

**Comment by zengyan1** [comment]
下次复现后解决

**Comment by zengyan1** [comment]
未复现

**Comment by zengyan1** [comment]
未复现

**Comment by zengyan1** [comment]
长时间未复现，测试建议先关闭，若复现再开
