### ISSUE TITLE
[Bug]: cluster level snapshot should not restore db/table in nonsys account.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19229]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

78d12274a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="589" alt="企业微信截图_2e1874be-f655-42db-88a4-d0a1510d1633" src="https://github.com/user-attachments/assets/598ec7a0-53f0-4aba-98b4-3e250edbd3e1">

<img width="525" alt="image" src="https://github.com/user-attachments/assets/dd7907d9-bf10-49a2-9563-76cd125a2198">

### Expected Behavior

cluster级别的快照只能恢复cluster级别，或者account级别，不能恢复db/table级别

### Steps to Reproduce

```Markdown
create account acc01 admin_name = 'test_account' identified by '111';

acc01租户：
create database db1;
use db1;
create table table01(col1 int);
insert into table01 values(1);

sys租户下：
create snapshot cluster_sp for cluster;
restore account acc01 database db1 from snapshot cluster_sp; 
restore account acc01 database db1 table table01 from snapshot cluster_sp;
```

**Comment by YANGGMM** [comment]
等pr合入

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
已验证
