### ISSUE TITLE
[Bug]: ut failed in TestGlobalCheckpoint5

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19248]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/2a34c48a-ef9c-4288-8b38-c8794c77ce3f)

![image](https://github.com/user-attachments/assets/cac033d4-6454-4ad0-ac2a-c3bb752d87d5)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11289059940/job/31398221329?pr=19241
```

**Comment by XuPeng-SH** [comment]
<img width="1332" alt="image" src="https://github.com/user-attachments/assets/01560aeb-1a33-401e-8321-1dae0efaa870">

**Comment by XuPeng-SH** [comment]
fixed

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/11432442139/job/31802929792?pr=19481

**Comment by aptend** [comment]
> repro：https://github.com/matrixorigin/matrixone/actions/runs/11432442139/job/31802929792?pr=19481

checkpoint timeout

**Comment by XuPeng-SH** [comment]
fixed
