### ISSUE TITLE
[Bug]: chaos test tpcc verify failed

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19247]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d354fe67219ce3b82523fdc0023bb57c1081055c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Chaos test, every 5min kill one log,  tpcc test is continues ,after 1.5h   tpcc verify  failed
<img width="1062" alt="企业微信截图_d77607f4-9a19-4d7e-ab54-5e4d21c465ff" src="https://github.com/user-attachments/assets/cbdaa92f-6d9e-4972-be91-3bb6b7d0d1d1">
<img width="878" alt="企业微信截图_de403c2c-47c2-4387-8809-2a695e0a45cf" src="https://github.com/user-attachments/assets/2b624ad6-25fd-44da-8034-db67d9f7936e">
dn pod restart ,too

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-d354fe6-202410110956%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11284918759/job/31386877122
```

**Comment by LeftHandCold** [comment]
未投入

**Comment by LeftHandCold** [comment]
未投入

**Comment by tom-csf** [comment]
问题复现
<img width="1157" alt="企业微信截图_34da7a59-1983-4c69-b1f9-7f45ee27d741" src="https://github.com/user-attachments/assets/b35c7a08-fda4-4cf0-a799-bd9e2226decb">
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22DNM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-ef654a2-202410282210%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730124000000%22,%22to%22:%221730170800000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by LeftHandCold** [comment]
可能是操作引起的failed，后面复现过一次因为tpcc 任务没有关闭，但是tpcc数据重新load了，并且create table和load不是一个txn

**Comment by LeftHandCold** [comment]
本地使用launch-with-proxy启动5个进程可以复现这个问题
debug后结论如下：一个事务中有update两个表的操作，提交到tn这里，只有一个表的update的操作，所以一致性出现问题。
后续在cn中添加log，发现run的时候执行了两个update操作，但是写入workspace只有一个表的数据。
<img width="829" alt="image" src="https://github.com/user-attachments/assets/de5108ec-1599-40a0-bc99-9fd2d2a42dec">

**Comment by tom-csf** [comment]
在chaos环境构建kill DN+ tpcc 测试场景复现
<img width="1163" alt="企业微信截图_cdbf784a-67b7-4b90-b0d4-fdd9495a51a9" src="https://github.com/user-attachments/assets/79d42bf2-0634-45b9-9be2-5e71a66927f8">
<img width="1152" alt="企业微信截图_e71ff20c-8348-4a0f-a173-891474a45d06" src="https://github.com/user-attachments/assets/69e20ae4-ba12-4619-9ced-2e4246bb3711">

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22O2c%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-2212882-202410311802%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730368972000%22,%22to%22:%221730371972000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by XuPeng-SH** [comment]
As discussed with @ouyuanning offline, @ouyuanning will investigate this issue later.

**Comment by volgariver6** [comment]
fixed, please test again.

**Comment by tom-csf** [comment]
验证 ok
