### ISSUE TITLE
[Bug]: bvt failed in system_table.sql

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19259]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/b9db5da9-df8d-4075-ac80-7de935755797)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11302957039/job/31439512125?pr=19254
```

**Comment by ck89119** [comment]
合下最新的main就可以了
