### ISSUE TITLE
[Bug]: mo-data etl/profile need add CPU information

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19267]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

be64f3ef67e858a3e6df9e61843fc96b2abd7add

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

现在mo-data下无cpu相关的profile信息，为了方便定位问题，建议增加相关profile文件到mo-data/etl/profile/下

### Steps to Reproduce

```Markdown
无
```

**Comment by daviszhen** [comment]
做了第一版。

cpu profile的抓取周期是 profile-interval/2。打开了profile-interval就能定时抓cpu profile

**Comment by heni02** [comment]
confirm,closed
mo-data/etl/profile下已添加cpu metric information
<img width="1271" alt="企业微信截图_a181646c-f4f3-45c7-9098-b01dd8ae5dfc" src="https://github.com/user-attachments/assets/5c0ba2ce-7523-4534-833a-21e4a2251c05">
