### ISSUE TITLE
[Bug]: file 01927f8d-9bcf-7246-935a-07cc3fbf0cf2_00000 is not found when executing queries on standy mo

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19268]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6359b6261c16fe0fcc3a7f1aeac537bff52a50f4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After standy mo changed as active mo after transfering logtail data and executing queries, error occured:
mysql> select sum(k) from sbtest.sbtest1;
ERROR 20405 (HY000): file 01927f8d-9bcf-7246-935a-07cc3fbf0cf2_00000 is not found
mysql> select sum(k) from sbtest.sbtest2;
ERROR 20405 (HY000): file 01927f8d-9b93-7a86-8f21-28070a8a2f96_00000 is not found
mysql> select sum(k) from sbtest.sbtest3;
ERROR 20405 (HY000): file 01927f8d-9ca1-7837-b565-10455af9edea_00000 is not found
mysql> select sum(k) from sbtest.sbtest4;
ERROR 20405 (HY000): file 01927f8d-9c46-7641-9ea9-c7099a96ad82_00000 is not found
mysql> select sum(k) from sbtest.sbtest5;
ERROR 20405 (HY000): file 01927f8d-9c9a-7cdd-95e9-bc069153fa0f_00000 is not found
mysql> select sum(k) from sbtest.sbtest6;
ERROR 20405 (HY000): file 01927f8d-ab96-71af-8347-4c96ac6e431d_00000 is not found
mysql> select sum(k) from sbtest.sbtest7;
ERROR 20405 (HY000): file 01927f8d-abae-73bb-a64e-cc6870accbb2_00000 is not found
mysql> select sum(k) from sbtest.sbtest8;
ERROR 20405 (HY000): file 01927f8d-9d7d-7248-a72f-fdc6b5475d53_00000 is not found
mysql> select sum(k) from sbtest.sbtest9;
ERROR 20405 (HY000): file 01927f8d-9dbf-7c05-92f7-6d31890e949b_00000 is not found
mysql> select sum(k) from sbtest.sbtest10;
ERROR 20405 (HY000): file 01927f8d-ac42-75e9-9d74-27574569b6f1_00000 is not found

mysql> (Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);
ERROR 20405 (HY000): file 01927f8d-aae4-7ca7-a0c4-00c11e02a221_00000 is not found
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);
ERROR 20405 (HY000): file 01927f8d-aae4-7ca7-a0c4-00c11e02a221_00000 is not found
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);
ERROR 20405 (HY000): file 01927f8d-aae4-7ca7-a0c4-00c11e02a221_00000 is not found
mysql> select * from (select (count(no_o_id)-(max(no_o_id)-min(no_o_id)+1)) as diff from bmsql_new_order group by no_w_id, no_d_id) as temp where diff != 0;
Empty set (0.01 sec)

mysql> (select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
ERROR 20405 (HY000): file 01927f8d-ab39-7902-9550-113488613ffb_00000 is not found
mysql> (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
ERROR 20405 (HY000): file 01927f8d-aae4-7ca7-a0c4-00c11e02a221_00000 is not found
mysql> 
mysql> 
mysql> (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
ERROR 20405 (HY000): file 01927f8d-aae4-7ca7-a0c4-00c11e02a221_00000 is not found
mysql> (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
ERROR 20405 (HY000): file 01927f8d-aae4-7ca7-a0c4-00c11e02a221_00000 is not found

[mo-error-not-found.log](https://github.com/user-attachments/files/17349198/mo-error-not-found.log)

### Steps to Reproduce

```Markdown
1. start a mo with standlone mode on service1
2. run a no-voting logserivce on service2
3. create 3 accounts and load tpcc, tpch, tpch and run tpcc,sysbench test for 3 hours
4. stop active mo
5. transfer no-voting logservice data to standby logservice
6. start standby mo
```

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
