### ISSUE TITLE
[Bug]: TestClientRead failed

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#19265]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7a12cc05bee88e0caa8238917895071d8cb19cbc

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/11303193861/job/31440013640?pr=19244

### Steps to Reproduce

```Markdown
Matrixone CI / UT Test on Ubuntu/x86
```

**Comment by volgariver6** [comment]
fixe by #19233
