### ISSUE TITLE
[Bug]: restore db,MODIFIED TIME changed 

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19275]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1c32bd64c774a4d798bc87589a2d5829bf7a4910

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 ./mo_br pitr restore --host "10.222.4.14" --port 31429 --user "root" --password "111" --pname "pitr03" --timestamp "2024-10-12 08:22:45" --account "sys" --database "db02"
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/1d831b7f-bde2-4711-85be-af85718cab20">

### Steps to Reproduce

```Markdown
restore pitr db
```

**Comment by YANGGMM** [comment]
用database级别的pitr 恢复databse / 用table 级别的pitr 恢复table 都会出现这个情况
https://github.com/matrixorigin/matrixone/issues/18970 ，在重建db 的时候会更新modify time和 object id，这个是正常的，需要跟产品讨论

**Comment by tom-csf** [comment]
恢复database 场景除了pitr表 其他表是否也会有类似的情况 表里面的时间发生变化 这样是否会带来哪些影响

**Comment by YANGGMM** [comment]
fixed

**Comment by tom-csf** [comment]
验证已经bugfix
