### ISSUE TITLE
[Bug]: bvt occasionally failed during merge run caused by an incorrect query result from the statement_info table

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19287]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

38725e7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/11309271878/job/31453094915
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/68920297-fec1-447c-bbb5-8c4a5e58d107">

### Steps to Reproduce

```Markdown
start merge run bvt
```

**Comment by sukki37** [comment]
repro：https://github.com/matrixorigin/matrixone/actions/runs/11316410484/job/31468857221

**Comment by xzxiong** [comment]
root cause: 问题出在 statement这个字段的查询结果上。
1.  statement_info 的聚合行为： 9条聚合成一条记录;  或 3条聚合+6条聚合，共两条记录
     - 这两种情况，mo跑在默认情况下，bvt是ok的。
2. CI 这里打开参数，拼接所有被聚合 statement
     - 导致bvt查询时，聚合不了这两行： 3条聚合，6条聚合；

![f266e73419aabbe6cbe913be4b220321_compress](https://github.com/user-attachments/assets/472faa37-35ef-4e07-8116-acb796d5b255)
