### ISSUE TITLE
[Bug]: mo_cdc: update mo table, downstream mysql row count first decrease and then increase

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19280]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

dbced45

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

创建cdc任务，然后上游mo执行update长事务，下游观察mysql数据先变少，后变多
<img width="544" alt="企业微信截图_c5e70670-9582-450e-a6b3-28e490bd43f7" src="https://github.com/user-attachments/assets/cdb39ede-0e79-4d9a-95a9-b2e73d6c8791">
过几分钟后开始变多
<img width="555" alt="企业微信截图_e7c6c2e7-8783-44a3-ab44-dcb8a45c0323" src="https://github.com/user-attachments/assets/0959a01b-f8de-43a0-8a2d-0e402bf32f00">

暂时还不清楚暂停任务是否会有数据不一致的影响，后续暂停任务问题解决后补充测试结果

### Steps to Reproduce

```Markdown
CREATE TABLE ORDERS_15k(
O_ORDERKEY       BIGINT NOT NULL,
O_CUSTKEY        INTEGER NOT NULL,
O_ORDERSTATUS    CHAR(1) NOT NULL,
O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
O_ORDERDATE      DATE NOT NULL,
O_ORDERPRIORITY  CHAR(15) NOT NULL,
O_CLERK          CHAR(15) NOT NULL,
O_SHIPPRIORITY   INTEGER NOT NULL,
O_COMMENT        VARCHAR(79) NOT NULL,
PRIMARY KEY (O_ORDERKEY)
);
load data url s3option {'endpoint'='http://minio.minio-mo.svc.cluster.local','access_key_id'='xxx','secret_access_key'='xxx','bucket'='mo-load-data', 'filepath'='tpch_10/orders.tbl','provider'='minio'} into table orders_15k fields terminated by '|' lines terminated by '\n' parallel 'true';
update ORDERS_15k set O_COMMENT='124' where O_ORDERKEY>3874334;
./mo_cdc task create --task-name "cdc_15k_new" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mysql" --sink-uri="mysql://dump:111@10.222.1.129:3306"    --tables='test_db.orders_15k:test_cdc_db.ORDERS_15k' --level="account"  --account="sys"
```

**Comment by heni02** [comment]
回归验证下游还是存在先减少后增加的现象
commit:72b1061
<img width="465" alt="企业微信截图_85234070-916b-45e6-ae9f-0039a165d185" src="https://github.com/user-attachments/assets/733ecf69-55c8-4b98-bdad-0409a1f9472b">
<img width="664" alt="企业微信截图_d0d46d2b-e72b-4c23-899c-4ba4c1549c27" src="https://github.com/user-attachments/assets/6eaf5c41-163a-40f9-b64b-5d0beb3f741c">
<img width="1305" alt="企业微信截图_0faeeed8-7bb5-4fba-aaf2-dc0b929c18db" src="https://github.com/user-attachments/assets/c20832c1-71b5-4e27-bc01-499a4f159929">
mo log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22t-5%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60tableReader%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729665208959%22,%22to%22:%221729668808959%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ck89119** [comment]
找到问题，修改中

**Comment by ck89119** [comment]
待验证

**Comment by daviszhen** [comment]
已经解决

**Comment by heni02** [comment]
update同步验证没有先减少后增加的现象了，但是同步数据需要大改12分钟（1500w 1.7G），感觉有点慢
<img width="479" alt="企业微信截图_5891bcf2-0a75-4ab9-8d78-b16bc3f6a728" src="https://github.com/user-attachments/assets/e2bfa4ce-33df-4942-b75e-de988aa56674">
<img width="1192" alt="企业微信截图_8061641c-4597-458c-9f41-6b3eb7ef9d27" src="https://github.com/user-attachments/assets/e7c0b181-b79c-4444-bd78-b52f51756b16">

**Comment by heni02** [comment]
性能问题继续分析，该问题先closed
