### ISSUE TITLE
[Bug]: mo service is unnormal(cannot commit a orphan transaction), mo_br create pitr success but cannot show

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19293]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1c32bd64c774a4d798bc87589a2d5829bf7a4910

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1、mo service is not normal (https://github.com/matrixorigin/matrixone/issues/19130)
     In service cannot create pitr db
2、 ./mo_br pitr create --host "10.222.4.14" --port 31429 --user "root" --password "111" --pname "pitr01" --level "cluster" --rangevalue 10 --rangeunit "h" --log_level "debug"

3、./mo_br pitr show --host "10.222.4.14" --port 31429 --user "root" --password "111"

<img width="1511" alt="企业微信截图_6f7d22e0-abb4-4d17-b320-7a89daa5c854" src="https://github.com/user-attachments/assets/de664e77-781c-4014-9a72-cf5faa0bfb53">

### Steps to Reproduce

```Markdown
1、mo service is not normal (https://github.com/matrixorigin/matrixone/issues/19130)
     In service cannot create pitr db
2、 ./mo_br pitr create --host "10.222.4.14" --port 31429 --user "root" --password "111" --pname "pitr01" --level "cluster" --rangevalue 10 --rangeunit "h" --log_level "debug"

3、./mo_br pitr show --host "10.222.4.14" --port 31429 --user "root" --password "111"
```

**Comment by YANGGMM** [comment]
应该是create pitr过程中的事务问题

**Comment by tom-csf** [comment]
验证已经bugfix

**Comment by YANGGMM** [comment]
fixed

**Comment by tom-csf** [comment]
在测试过程降低pod cpu+网络故障场景下都未复现此问题 先关闭issue
