### ISSUE TITLE
[Bug]: mo_cdc: sink-type="mo" reported unsupported sink type: mo

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19298]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4944cacd9

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[root@mo-srv-128 mo-backup]# ./mo_cdc task create --task-name "cdc_6k_mo" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mo" --sink-uri="mysql://dump:111@127.0.0.1:6001"    --tables='test_db.lineitem:mo_db.lineitem' --level="account"  --account="sys"
Error: invalid configuration: create CDC task failed: Error 20101 (HY000): internal error: unsupported sink type: mo

[root@mo-srv-128 mo-backup]# ./mo_cdc task create --task-name "cdc_6k_mo" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="matrixone" --sink-uri="mysql://dump:111@127.0.0.1:6001"    --tables='test_db.lineitem:mo_db.lineitem' --level="account"  --account="sys"
Error: invalid configuration: Sink type must be mo or mysql

### Steps to Reproduce

```Markdown
./mo_cdc task create --task-name "cdc_6k_mo" --source-uri="mysql://dump:111@10.222.6.6:6001" --sink-type="mo" --sink-uri="mysql://dump:111@127.0.0.1:6001"    --tables='test_db.lineitem:mo_db.lineitem' --level="account"  --account="sys"
```

**Comment by ck89119** [comment]
mo-backup的问题， pr中

**Comment by heni02** [comment]
更新mo-backup工具后可以了
confirm,closed
