### ISSUE TITLE
[Bug]: TPCC test SQL parser time missing

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#19295]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

4944cacd9913493335a0b820686b1a2b2543db0d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1253" alt="企业微信截图_fa15d451-b8fa-4033-aaa5-6070a35b6322" src="https://github.com/user-attachments/assets/6a3013e3-6772-4f92-ae9b-fd90e407881c">

### Expected Behavior

The execution fruit contains valid SQL parser time

### Steps to Reproduce

```Markdown
tpcc test
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test

**Comment by aressu1985** [comment]
fixed
