### ISSUE TITLE
[Bug]: UT TestRouter_ConnectAndSelectBalanced Panic

### ISSUE THREAD

**Issue by zengyan1** [matrixorigin/matrixone#19302]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cb176c1545448009a27a3ec5bb23bcca02fa8836

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: missing free: address 0x7f96e0897000, size 1048576, allocated at github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate.func1
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:87
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ClosureDeallocatorPool[...]).Get2
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/closure_deallocator.go:76
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*CheckedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/checked_allocator.go:80
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*RandomAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/random_allocator.go:42
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ProfileAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/profile_allocator.go:141
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*MetricsAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/metrics_allocator.go:92
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*SizeBoundedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/size_bounded_allocator.go:78
	github.com/matrixorigin/matrixone/pkg/common/malloc.(*ManagedAllocator[...]).Allocate
		/home/runner/work/matrixone/matrixone/pkg/common/malloc/managed_allocator.go:48
	github.com/matrixorigin/matrixone/pkg/frontend.(*SessionAllocator).Alloc
		/home/runner/work/matrixone/matrixone/pkg/frontend/types.go:[44](https://github.com/matrixorigin/matrixone/actions/runs/11322291227/job/31482735077?pr=19246#step:9:45)7
	github.com/matrixorigin/matrixone/pkg/frontend.(*BufferAllocator).Alloc
		/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_buffer.go:61
	github.com/matrixorigin/matrixone/pkg/frontend.NewIOSession
		/home/runner/work/matrixone/matrixone/pkg/frontend/mysql_buffer.go:213
	github.com/matrixorigin/matrixone/pkg/proxy.newServerConn
		/home/runner/work/matrixone/matrixone/pkg/proxy/server_conn.go:120
	github.com/matrixorigin/matrixone/pkg/proxy.(*router).Connect
		/home/runner/work/matrixone/matrixone/pkg/proxy/router.go:230
	github.com/matrixorigin/matrixone/pkg/proxy.TestQuitEvent
		/home/runner/work/matrixone/matrixone/pkg/proxy/event_test.go:408
	testing.tRunner
		/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690
	runtime.goexit
		/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11322291227/job/31482735077?pr=19246
```

**Comment by volgariver6** [comment]
fixed
