### ISSUE TITLE
[Bug]: big-data: warning "Checkpoint is not working more than 30 mins".

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b6cb831d345a76c55d851f613384b49e9509148b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

namespace: mo-big-data-20241013

```
出现该条告警时正在执行的sql：
delete from big_data_test.table_with_pk_index_for_write_1B where id <= 10000000

告警信息：
MO-OB】 WARNING • NoCheckpoint • 告警中:1
 
2024-10-14T13:36:57+08:00
详请
当前全部告警
历史告警查询
 
🚨 触发中告警 [1]
 
告警处理人:  @aptend(韩枫) 
 告警名称 : NoCheckpoint
 告警级别 : WARNING
 命名空间 : mo-big-data-20241013
完整 Label 
alertOwner : HanFeng
alertTeam : DN Team
alertname : NoCheckpoint
clusterDetail : aliyun-new-dev-controlplane
namespace : mo-big-data-20241013
pod : mo-big-data-20241013
prometheus : mo-ob/mo-ob-opensource-tke-kube-prometheus
serviceScope : mo-cluster
severity : warning
 告警状态 : 🚨 FIRING
 开始时间 : 2024-10-14T13:36:47+08:00
 结束时间 : Not End
 告警描述 : CN pod nightly-regression-dis-dn-0 in mo-big-data-20241013 : Checkpoint is not working more than 30 mins
---

```

告警附近的日志：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22lxc%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241013%5C%22%7D%20%7C%3D%20%60Checkpoint%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728876647000%22,%22to%22:%221728877247000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big data regression on tke
```

**Comment by aptend** [comment]
Excessive data compaction tasks triggered by range deletions are clogging the task queue, which delays flush tasks and consequently leads to slow checkpoints.

**Comment by Ariznawlll** [comment]
verified
