### ISSUE TITLE
[Bug]: restore account with pub-sub table report 'table not exists'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c4fc6b3dde5d03c81e1657f8816f8ce4299b0f69

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="409" alt="企业微信截图_d234bcd2-6cff-4c89-95d6-6ca38d0c548e" src="https://github.com/user-attachments/assets/2e9436e4-f07c-4896-8130-f3fbe2e560a5">

### Expected Behavior

恢复的是account，应该恢复成功，如果恢复的时间戳对应的table不在，不做恢复就行，不应该报表不存在

### Steps to Reproduce

```Markdown
create account acc01 admin_name = 'test_account' identified by '111';
create account acc02 admin_name = 'test_account' identified by '111';

sys租户：
create pitr p01 range 2 'h';
drop database if exists test01;
create database test01;
use test01;
drop table if exists table01;
create table table01 (col1 int, col2 decimal(6), col3 varchar(30));
insert into table01 values (1, null, 'database');
insert into table01 values (2, 38291.32132, 'database');
insert into table01 values (3, null, 'database management system');
insert into table01 values (4, 10, null);
insert into table01 values (1, -321.321, null);
insert into table01 values (2, -1, null);

create publication pub01 database test01 table table01 account acc01;
select now();        —>标记点

create table table02 (col1 int, col3 decimal);
insert into table02 values(1, 2);
create publication pub02 database test01 table table02 account acc02;

acc01订阅：create database db01 from sys publication pub01;
acc02订阅：create database db01 from sys publication pub02;

restore from pitr p01 "2024-10-15 14:15:54.201941";    -->报错位置，该处的时间戳为标记点对应的时间戳
```

**Comment by YANGGMM** [comment]
mysql> restore from pitr p01 '2024-10-15 14:48:40.746748';
ERROR 20101 (HY000): internal error: table 'table01' not exists
mysql> 

复现成功

**Comment by YANGGMM** [comment]
restore pub 在restore table 之前导致找不到table
{"level":"INFO","time":"2024/10/15 14:50:13.404476 +0800","name":"cn-service","caller":"frontend/pitr.go:2097","msg":"[p01] create pub: create pub sql: CREATE PUBLICATION pub01 DATABASE test01 TABLE table01 ACCOUNT acc01","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"ERROR","time":"2024/10/15 14:50:13.406607 +0800","caller":"moerr/error.go:749","msg":"error: internal error: table 'table01' not exists","span":{"trace_id":"9bc6154d-b76b-ac06-35c6-eecce7a9d63d","span_id":"a073635aa5f7ebcf"}}

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
测试✅
