### ISSUE TITLE
[Bug]: Sysbench point selects negative CPU time issue

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#19324]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c4fc6b3dde5d03c81e1657f8816f8ce4299b0f69

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2024/10/15 10:46:02.369316 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7780-7651-b697-c48f21f8d93f, statement_type:Select, statement:execute __mo_stmt_id_8, statsInfo(802411 + 18170 + 3907 + 0 + 0 - 728923 - 725409) = -629844","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 168||account sys:dump|goRoutineId 7814|migrate-goRoutineId 0|01928e11-76f0-7e7f-bd3e-707a0ebf1a80","role":"moadmin","session_id":"01928e11-76f0-7e7f-bd3e-707a0ebf1a80","statement_id":"01928e11-7780-7651-b697-c48f21f8d93f","txn_id":"70f70f4866a9b62a17fe80147e14ff64","span":{"trace_id":"6821ff65-4654-e9e4-c7fb-ff09b741bf00","span_id":"7a05cab3ce0336ed"}}
{"level":"INFO","time":"2024/10/15 10:46:02.370312 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7780-785a-81fe-e8c7fe76f5ac, statement_type:Select, statement:execute __mo_stmt_id_5, statsInfo(1634861 + 21678 + 7214 + 0 + 0 - 1671801 - 199362) = -207410","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 178||account sys:dump|goRoutineId 7808|migrate-goRoutineId 0|01928e11-7706-76cf-b8d8-d1f25e6db7ce","role":"moadmin","session_id":"01928e11-7706-76cf-b8d8-d1f25e6db7ce","statement_id":"01928e11-7780-785a-81fe-e8c7fe76f5ac","txn_id":"70f70f4866a9b62a17fe80147e14ff65","span":{"trace_id":"2aad2536-0c66-617e-278a-dcb73675014b","span_id":"e1f88324b53aafa8"}}
{"level":"INFO","time":"2024/10/15 10:46:02.370506 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7780-703c-a99b-6ddc6cb9f5c1, statement_type:Select, statement:execute __mo_stmt_id_5, statsInfo(2357568 + 22728 + 4880 + 0 + 0 - 2320359 - 2316177) = -2251360","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 120||account sys:dump|goRoutineId 7729|migrate-goRoutineId 0|01928e11-76d2-72a0-a5b3-a83f7a8d7e32","role":"moadmin","session_id":"01928e11-76d2-72a0-a5b3-a83f7a8d7e32","statement_id":"01928e11-7780-703c-a99b-6ddc6cb9f5c1","txn_id":"70f70f4866a9b62a17fe80147e14ff62","span":{"trace_id":"5e8288de-e720-f38b-eaca-9d9dd8a130ba","span_id":"ead947ba1a4fd410"}}
{"level":"INFO","time":"2024/10/15 10:46:02.377385 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7787-7999-816a-7b91e63a5948, statement_type:Select, statement:execute __mo_stmt_id_1, statsInfo(1640615 + 21298 + 10492 + 0 + 0 - 1598464 - 1595266) = -1521325","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 158||account sys:dump|goRoutineId 7801|migrate-goRoutineId 0|01928e11-76e6-7464-bb33-1feb0978b2f1","role":"moadmin","session_id":"01928e11-76e6-7464-bb33-1feb0978b2f1","statement_id":"01928e11-7787-7999-816a-7b91e63a5948","txn_id":"70f70f4866a9b62a17fe80147e14ff79","span":{"trace_id":"35f135b1-bb31-3f4d-36af-7778dd4d30fb","span_id":"118cfd5c3a819899"}}
{"level":"INFO","time":"2024/10/15 10:46:02.380004 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7787-7b70-9c20-c2f1d5b28796, statement_type:Select, statement:execute __mo_stmt_id_6, statsInfo(4115400 + 18068 + 3808 + 0 + 0 - 4007318 - 1520614) = -1390656","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 214||account sys:dump|goRoutineId 7907|migrate-goRoutineId 0|01928e11-7768-75e3-9ea8-46c36c59bb6b","role":"moadmin","session_id":"01928e11-7768-75e3-9ea8-46c36c59bb6b","statement_id":"01928e11-7787-7b70-9c20-c2f1d5b28796","txn_id":"70f70f4866a9b62a17fe80147e14ff7a","span":{"trace_id":"a1efbbc4-f530-45dc-781f-31b3585ccfc7","span_id":"157eac985f5ebda1"}}
{"level":"INFO","time":"2024/10/15 10:46:02.380236 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7789-7f0f-b86d-bfb7be8f4d45, statement_type:Select, statement:execute __mo_stmt_id_6, statsInfo(2126311 + 18815 + 3862 + 0 + 0 - 2090513 - 2085477) = -2027002","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 189||account sys:dump|goRoutineId 7838|migrate-goRoutineId 0|01928e11-7736-7b29-8191-c61ca92d8e4e","role":"moadmin","session_id":"01928e11-7736-7b29-8191-c61ca92d8e4e","statement_id":"01928e11-7789-7f0f-b86d-bfb7be8f4d45","txn_id":"70f70f4866a9b62a17fe80147e14ff85","span":{"trace_id":"4a413168-22a0-3676-c642-1a3257748e45","span_id":"ea17119e83088eed"}}
{"level":"INFO","time":"2024/10/15 10:46:02.385033 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7780-7a86-989c-f7a05ff60611, statement_type:Select, statement:execute __mo_stmt_id_4, statsInfo(16234217 + 15639 + 8195 + 0 + 0 - 16193209 - 16189546) = -16124704","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 154||account sys:dump|goRoutineId 7798|migrate-goRoutineId 0|01928e11-76df-750f-ac97-ea28dc92e121","role":"moadmin","session_id":"01928e11-76df-750f-ac97-ea28dc92e121","statement_id":"01928e11-7780-7a86-989c-f7a05ff60611","txn_id":"70f70f4866a9b62a17fe80147e14ff66","span":{"trace_id":"2e517544-ed12-f385-0337-cadc06e1bf0a","span_id":"cfd81132b7897e33"}}
{"level":"INFO","time":"2024/10/15 10:46:02.385190 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7780-72c1-81fd-f0ab7aa15ae8, statement_type:Select, statement:execute __mo_stmt_id_4, statsInfo(16802540 + 22566 + 7507 + 0 + 0 - 16765140 - 16761957) = -16694484","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 148||account sys:dump|goRoutineId 7828|migrate-goRoutineId 0|01928e11-76dd-7a60-b5cd-b08da1f97f82","role":"moadmin","session_id":"01928e11-76dd-7a60-b5cd-b08da1f97f82","statement_id":"01928e11-7780-72c1-81fd-f0ab7aa15ae8","txn_id":"70f70f4866a9b62a17fe80147e14ff63","span":{"trace_id":"cfb42783-ad7c-b290-8f07-8e58df5fb57e","span_id":"0b837ce44092f7ef"}}
{"level":"INFO","time":"2024/10/15 10:46:02.393922 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7797-7e76-b0f2-000ea497b9b6, statement_type:Select, statement:execute __mo_stmt_id_5, statsInfo(1847065 + 30374 + 3524 + 0 + 0 - 1801613 - 1797867) = -1718517","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 172||account sys:dump|goRoutineId 7806|migrate-goRoutineId 0|01928e11-76fd-7446-a690-803fc0d34ec4","role":"moadmin","session_id":"01928e11-76fd-7446-a690-803fc0d34ec4","statement_id":"01928e11-7797-7e76-b0f2-000ea497b9b6","txn_id":"70f70f4866a9b62a17fe80147e14ffdf","span":{"trace_id":"0770573e-6442-cd45-a5d8-ac0021870377","span_id":"e5ffb2908425c808"}}
{"level":"INFO","time":"2024/10/15 10:46:02.399808 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7780-7c8d-964f-239ba1930125, statement_type:Select, statement:execute __mo_stmt_id_8, statsInfo(30888831 + 14372 + 4337 + 0 + 0 - 30841814 - 30837869) = -30772143","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 190||account sys:dump|goRoutineId 7837|migrate-goRoutineId 0|01928e11-7736-7cf8-ac5d-bab11929c6f8","role":"moadmin","session_id":"01928e11-7736-7cf8-ac5d-bab11929c6f8","statement_id":"01928e11-7780-7c8d-964f-239ba1930125","txn_id":"70f70f4866a9b62a17fe80147e14ff67","span":{"trace_id":"486c1060-ae59-0a32-8265-dd9cd45d8755","span_id":"e0bfcb0b546f62e2"}}
{"level":"INFO","time":"2024/10/15 10:46:02.400255 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-7782-7abf-817e-e7ebbc006982, statement_type:Select, statement:execute __mo_stmt_id_6, statsInfo(198615 + 29193760 + 4472 + 0 + 0 - 29098752 - 29093683) = -28795588","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 203||account sys:dump|goRoutineId 7854|migrate-goRoutineId 0|01928e11-7756-7f01-a9ab-d32ef5d68701","role":"moadmin","session_id":"01928e11-7756-7f01-a9ab-d32ef5d68701","statement_id":"01928e11-7782-7abf-817e-e7ebbc006982","txn_id":"70f70f4866a9b62a17fe80147e14ff6d","span":{"trace_id":"02b0bc10-9583-f2dd-3b1e-387c0ca4054d","span_id":"e51428d50a016562"}}
{"level":"INFO","time":"2024/10/15 10:46:02.404722 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-77a2-7b6b-9fd6-d4ae812ac821, statement_type:Select, statement:execute __mo_stmt_id_8, statsInfo(1857545 + 19143 + 3532 + 0 + 0 - 1792335 - 1788047) = -1700162","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 148||account sys:dump|goRoutineId 7828|migrate-goRoutineId 0|01928e11-76dd-7a60-b5cd-b08da1f97f82","role":"moadmin","session_id":"01928e11-76dd-7a60-b5cd-b08da1f97f82","statement_id":"01928e11-77a2-7b6b-9fd6-d4ae812ac821","txn_id":"70f70f4866a9b62a17fe80147e15003f","span":{"trace_id":"cfb42783-ad7c-b290-8f07-8e58df5fb57e","span_id":"0b837ce44092f7ef"}}
{"level":"INFO","time":"2024/10/15 10:46:02.408615 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-779d-7c0b-ac40-48aa0aa6d1c9, statement_type:Select, statement:execute __mo_stmt_id_8, statsInfo(10561208 + 39528 + 3969 + 0 + 0 - 10480209 - 10473930) = -10349434","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 149||account sys:dump|goRoutineId 7829|migrate-goRoutineId 0|01928e11-76dd-7b73-9b1a-43dd4457afd5","role":"moadmin","session_id":"01928e11-76dd-7b73-9b1a-43dd4457afd5","statement_id":"01928e11-779d-7c0b-ac40-48aa0aa6d1c9","txn_id":"70f70f4866a9b62a17fe80147e150014","span":{"trace_id":"5a65793d-cfba-224a-b456-f098d417e429","span_id":"b89327cd76e70ffc"}}
{"level":"INFO","time":"2024/10/15 10:46:02.418135 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-77ae-73bb-8b3f-f2eccf4a5f2d, statement_type:Select, statement:execute __mo_stmt_id_3, statsInfo(3677850 + 126587 + 3409 + 0 + 0 - 3641787 - 3638179) = -3472120","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 212||account sys:dump|goRoutineId 7825|migrate-goRoutineId 0|01928e11-7768-7081-9968-a45132f4dcda","role":"moadmin","session_id":"01928e11-7768-7081-9968-a45132f4dcda","statement_id":"01928e11-77ae-73bb-8b3f-f2eccf4a5f2d","txn_id":"70f70f4866a9b62a17fe80147e1500bc","span":{"trace_id":"153d65a2-3bc8-ecb8-7736-49a7a3835016","span_id":"14d9b6623246d5d0"}}
{"level":"INFO","time":"2024/10/15 10:46:02.443104 +0800","name":"cn-service","caller":"frontend/mysql_cmd_executor.go:3571","msg":"negative cpu statement_id:01928e11-77c2-7365-9016-426a7069bd35, statement_type:Select, statement:execute __mo_stmt_id_2, statsInfo(8797451 + 11761 + 2783 + 0 + 0 - 9157509 - 6237445) = -6582959","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 205||account sys:dump|goRoutineId 7856|migrate-goRoutineId 0|01928e11-7760-774f-8bc6-f83056f2ea1a","role":"moadmin","session_id":"01928e11-7760-774f-8bc6-f83056f2ea1a","statement_id":"01928e11-77c2-7365-9016-426a7069bd35","txn_id":"70f70f4866a9b62a17fe80147e1501c8","span":{"trace_id":"96a31d24-7f02-09aa-9e9d-8119f2ae7c9b","span_id":"1f96b5b54ee14e1d"}}

### Expected Behavior

Normal query statements do not have negative CPU time values

### Steps to Reproduce

```Markdown
1. Run sysbench test：
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=30 --report-interval=10    cleanup

sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=30 --report-interval=10    prepare

sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111   oltp_point_select.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=100 --time=300 --report-interval=10    --range_selects=off --point_selects=1 run

2. Then search for "negative cpu" string in the log
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test

**Comment by aressu1985** [comment]
fixed
