### ISSUE TITLE
[Bug]: restore db failed “invalid checkpoints duration”

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19326]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b4ea38bcd2f2c80462f42ab909dead60752e0080

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1256" alt="企业微信截图_4c40273a-9341-432b-a0ea-7f5e92265f0a" src="https://github.com/user-attachments/assets/1ade9f38-b470-426b-b573-da63b3ff9cbc">

### Steps to Reproduce

```Markdown
场景是：
1、创建db级别pitr
2、tab1 构造了23w条数据
3、选择最新时间点进行恢复 ./mo_br pitr restore --host "172.16.67.152" --port 6001 --user "root" --password "111" --pname "pitr01" --timestamp "2024-10-15 03:53:23" --database "db01" --account "sys"
```

### Additional information

<img width="796" alt="企业微信截图_bb2d1d23-67ef-4fdc-aaa5-fa308d846849" src="https://github.com/user-attachments/assets/1fc3d4e3-c7a2-4e10-a746-2bfef6de54bc">
<img width="942" alt="image" src="https://github.com/user-attachments/assets/fa29eb2d-22ed-4000-bd93-4c24b390add9">

**Comment by triump2020** [comment]
@tom-csf  Pls test!

**Comment by tom-csf** [comment]
验证已经bugfix
