### ISSUE TITLE
[Bug]: ut failed in TestReadCheckpoint

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19329]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

unexpected fault address 0x7f6acff5501d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6acff5501d pc=0x10a9210]

goroutine 6342 gp=0xc0006d9a40 m=6 mp=0xc000480008 [running]:
runtime.throw({0x5a744d3?, 0x48af16?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:1067 +0x48 fp=0xc002ae4868 sp=0xc002ae4838 pc=0x47eb08
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/signal_unix.go:914 +0x26c fp=0xc002ae48c8 sp=0xc002ae4868 pc=0x480c4c
github.com/matrixorigin/matrixone/pkg/container/types.(*Varlena).GetByteSlice(0x7f6acff5501d, {0x7f6acff55081, 0x14?, 0x17f})
	/home/runner/work/matrixone/matrixone/pkg/container/types/bytes.go:102 +0x30 fp=0xc002ae4918 sp=0xc002ae48c8 pc=0x10a9210
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetBytesAt(0xc002ad4880, 0x0)
	/home/runner/work/matrixone/matrixone/pkg/container/vector/vector.go:284 +0x194 fp=0xc002ae49a0 sp=0xc002ae4918 pc=0x13a9b54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.getNonNullValue(0xc002ad4880, 0x0)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/utils.go:247 +0x2d25 fp=0xc002ae4e20 sp=0xc002ae49a0 pc=0x21efce5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vectorWrapper).ShallowGet(...)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/vector.go:159
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vectorWrapper).Get(0xc002aa5020, 0x0)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/containers/vector.go:149 +0x112 fp=0xc002ae4ea8 sp=0xc002ae4e20 pc=0x21f4f72
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*CkpReplayer).ReadCkpFiles(0xc0005244d0)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/checkpoint/replay.go:214 +0x14a5 fp=0xc002ae52f0 sp=0xc002ae4ea8 pc=0x394a065
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0x62ce0a0, 0x94f0300}, {0xc0068e7080, 0x31}, 0xc000546b40)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/open.go:193 +0x320b fp=0xc002ae5bf0 sp=0xc002ae52f0 pc=0x49ab46b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/testutil.(*TestEngine).Restart(0xc0031fcb00, {0x62ce0a0, 0x94f0300})
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/testutil/engine.go:94 +0xed fp=0xc002ae5c80 sp=0xc002ae5bf0 pc=0x49bf70d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/test.TestReadCheckpoint(0xc000575ba0)
	/home/runner/work/matrixone/matrixone/pkg/vm/engine/tae/db/test/db_test.go:4534 +0xfe5 fp=0xc002ae5ee0 sp=0xc002ae5c80 pc=0x4a2b845
testing.tRunner(0xc000575ba0, 0x5b851d8)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227 fp=0xc002ae5fb0 sp=0xc002ae5ee0 pc=0x5f0247
testing.(*T).Run.gowrap1()
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x45 fp=0xc002ae5fe0 sp=0xc002ae5fb0 pc=0x5f1f65
runtime.goexit({})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc002ae5fe8 sp=0xc002ae5fe0 pc=0x487701
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x826

goroutine 1 gp=0xc0000061c0 m=nil [chan receive]:
runtime.gopark(0x7f6ad80fbcc0?, 0x18?, 0x30?, 0xe9?, 0x7f6b4402df18?)
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/proc.go:424 +0xce fp=0xc0013836e0 sp=0xc0013836c0 pc=0x47ec4e
runtime.chanrecv(0xc002fcb570, 0xc0013837c7, 0x1)
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/chan.go:639 +0x3bc fp=0xc001383758 sp=0xc0013836e0 pc=0x41061c
runtime.chanrecv1(0x856b460?, 0x528b5c0?)
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/chan.go:489 +0x12 fp=0xc001383780 sp=0xc001383758 pc=0x410232
testing.(*T).Run(0xc000575d40, {0x5a94b8b, 0x12}, 0x5b851d8)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1751 +0x851 fp=0xc0013838a0 sp=0xc001383780 pc=0x5f1cd1
testing.runTests.func1(0xc000575d40)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2168 +0x86 fp=0xc0013838f0 sp=0xc0013838a0 pc=0x5f61e6
testing.tRunner(0xc000575d40, 0xc00006fae0)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x227 fp=0xc0013839c0 sp=0xc0013838f0 pc=0x5f0247
testing.runTests(0xc000530330, {0x84f9ce0, 0xd1, 0xd1}, {0x7f6b4402df18?, 0xc00006fba8?, 0x85719c0?})
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2166 +0x8bf fp=0xc001383b10 sp=0xc0013839c0 pc=0x5f603f
testing.(*M).Run(0xc000772500)
	/opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:2034 +0xf18 fp=0xc001383e88 sp=0xc001383b10 pc=0x5f3658
main.main()
	_testmain.go:461 +0x165 fp=0xc001383f50 sp=0xc001383e88 pc=0x4af72a5
runtime.main()
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/proc.go:[272](https://github.com/matrixorigin/matrixone/actions/runs/11341111231/job/31538768007?pr=19316#step:9:273) +0x28b fp=0xc001383fe0 sp=0xc001383f50 pc=0x445ecb
runtime.goexit({})
	/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc001383fe8 sp=0xc001383fe0 pc=0x487701

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11341111231/job/31538768007?pr=19316
```

**Comment by XuPeng-SH** [comment]
@jiangxinmeng1

**Comment by XuPeng-SH** [comment]
@LeftHandCold 
<img width="1740" alt="image" src="https://github.com/user-attachments/assets/a53867dd-1f6d-475f-9054-31241d9ddabb">

`closeCB` should not be called here

**Comment by XuPeng-SH** [comment]
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/fbe44de7-888a-4eda-ad97-2cf32962b82e">

**Comment by LeftHandCold** [comment]
fixed
