### ISSUE TITLE
[Bug]: dn oom when running sql 'delete from t where a=1;';

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19353]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b4ea38bcd

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

分布式环境测试
<img width="927" alt="image" src="https://github.com/user-attachments/assets/822e2f8e-05da-4060-a5d2-0d07276df61f">

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/70e2ab25-8ddf-47d8-ad58-ff1136ff3217">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dU8%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-b4ea38bcd-20241014%5C%22%7D%20%7C%3D%20%60delete%20from%20t%20where%20a%3D1%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728985578000%22,%22to%22:%221728986418000%22%7D%7D%7D&schemaVersion=1&orgId=1

cpu memory使用：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22GlD%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-b4ea38bcd-20241014%5C%22,pod%3D%27nightly-regression-dis-dn-0%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221728985578000%22,%22to%22:%221728986418000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
分布式环境执行：

create database test;
use test;
create table t(a int);
insert into t values (1),(2);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
select count(*) from t;
delete from t where a=1;
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
测试了好几次没再出现dn oom的情况
