### ISSUE TITLE
[Bug]: restore from pitr report 'FATAL' error.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19357]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b6cb831d345a76c55d851f613384b49e9509148b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**tke测试环境，里面有数据大约2T**
**集群配置：** https://github.com/matrixorigin/mo-nightly-regression/blob/main/.github/workflows/big-data-test.yml

**pitr的创建信息**（时间是UTC时间，UTC+8时间为2024-10-13 20:23:28）：
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/05182ec4-97e9-46ef-b8da-8ab11f8e4720">

```
恢复执行的sql：（执行这条sql的时间大约在UTC+8时间2024-10-15 13:06:07）
restore from pitr p01 "2024-10-14 05:22:29";(UTC时间，对应utc+8时间为"2024-10-14 13:22:29")
```

**大约执行了5h+后报错**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/2412ad81-fdb9-4766-a44f-9e5e4638e18b">

**Lost connection时间点对应的日志里面有FATAL错误：**
<img width="1405" alt="企业微信截图_e3304c9e-1ad0-4f88-a3d0-2cd91df60aa0" src="https://github.com/user-attachments/assets/1bdaf027-38f2-44c8-852c-14aa84792d21">

**log：** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22iwM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241013%5C%22%7D%20%7C%3D%20%60FATAL%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221728988680000%22,%22to%22:%221728988800000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
create pitr p01 range 1 'd';

restore from pitr p01 "2024-10-14 05:22:29";
```

**Comment by sukki37** [comment]
similar to #19288, the result of the query based on the primary key returns 0 rows.

**Comment by aptend** [comment]
The log indicates:
 - The prolonged restore transaction `481c93f16e7a211117fe1ab03e64c04e` took over five hours before it failed, involving a large workspace.
 - Despite the insert SQL statement(`insert into mo_increment_columns(table_id, col_name, col_index, offset, step) values(272927, '__mo_fake_pk_col', 25, 0, 1)`) executing successfully less than 200ms earlier, the subsequent select SQL statement could not retrieve that record from the workspace.

This issue has not been reproduced locally. Let's see what the newly added log can tell upon reproduction in the big-data test

**Comment by aptend** [comment]
After conducting some tests, it seems that the issue is not related to S3 flushing. Instead, the txnOffset seems to be worthy of further investigation

**Comment by aptend** [comment]
No luck in reproducing the issue.

**Comment by Ariznawlll** [comment]
Same restore operation to repro this issue，but mo oom unfortunately,  details in issue #19511

**Comment by aptend** [comment]
No repro yet, consider downgrading its severity

**Comment by aressu1985** [comment]
一致复现不了，先降级处理

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
fixed
