### ISSUE TITLE
[Bug]: mo_cdc: mo show task reported file  is not found when resume cdc task 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19387]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b848638

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

测试场景： resume任务时，轮流模拟cn节点挂掉多次，下游数据同步若干数据后，show task报错
[root@mo-srv-128 mo-backup]# ./mo_cdc task show --task-name "cdc_orders" --source-uri="mysql://dump:111@10.222.6.6:6001"
Error: invalid configuration: connect mo failed: Error 20405 (HY000): file nightly-b848638/data/019294a7-aea5-7245-9aff-04b5b7beea1c_00000 is not found
执行多次还是报错
<img width="1391" alt="企业微信截图_e2c44505-4f21-4d77-86b4-b2bc34f22c0e" src="https://github.com/user-attachments/assets/2acd1fe9-09b0-4178-93e5-497db7bd7d87">

mo 日志：
http://10.222.6.1/explore?panes=%7B%22VCp%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-cdc-test%5C%22%7D%20%7C%3D%20%60tableReader%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729066230175%22,%22to%22:%221729073430175%22%7D%7D%7D&schemaVersion=1&orgId=1
resume开始时间：
<img width="1483" alt="企业微信截图_2e899f9e-4a63-49d6-a620-fb2a03f783af" src="https://github.com/user-attachments/assets/8788037e-2436-4abc-9bb0-a7a35f6deeb2">

### Steps to Reproduce

```Markdown
resume时模拟cn故障测试
```

**Comment by ck89119** [comment]
从log来看是stale read类型的err没抓住，先换一种写法试下；本地很难复现，测试中

**Comment by ck89119** [comment]
修改已merge，比较难复现，需要后续继续观察

**Comment by heni02** [comment]
以上测试场景运行15分钟，kill cn十几次，无出现该错误（不确定是否没有复现），同步数据一致，该先closed
commit:72b1061
<img width="543" alt="企业微信截图_8dc85635-971e-4c55-b528-04f1c2da6c37" src="https://github.com/user-attachments/assets/d09ea1c2-0b66-4793-b4b0-9b8807a61a2e">
<img width="461" alt="企业微信截图_a1c0fa11-c6fe-4965-b381-4a2d6864e35f" src="https://github.com/user-attachments/assets/99fe6b35-4ee2-4727-8019-d6e98990dd6e">

<img width="1321" alt="企业微信截图_7762e935-a899-4326-be00-e654a082ca55" src="https://github.com/user-attachments/assets/e96dc46c-676b-4154-a6a2-0a157f526e1c">
