### ISSUE TITLE
[Bug]: Time.MarshalBinary: unexpected zone offset

### ISSUE THREAD

**Issue by cpegeric** [matrixorigin/matrixone#19391]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

52dc562e8a61f7b722f494668d0b13c647418a08

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: macos
- Others:
```

### Actual Behavior

2024/10/16 13:56:48.200424 +0100 INFO tn-service.logtail-server service/session.go:524 send subscription response {"service": "12002-tn", "uuid": "12002-tn", "server-id": "01929566-bd34-7d75-95bd-f8288b0938e5", "stream-id": 1, "remote": "127.0.0.1:50081", "table": "db_id:272513 tb_id:272514 db_name:\"db_testupdateonnewcn_998320000\" tb_name:\"testupdateonnewcn\" ", "To": "PhysicalTime:1729083408199442000 "}
2024/10/16 13:56:48.200634 +0100 INFO disttae/logtail_consumer.go:1248 0-cn-12002 [logtail-consumer] subscribe tbl[db: 272513, tbl: 272514] resp received, 0x14049b6d800
2024/10/16 13:56:48.201187 +0100 INFO disttae/logtail_consumer.go:399 [logtail-consumer] subscribe tbl[db: 272513, tbl: 272514, testupdateonnewcn] succeed
2024/10/16 13:56:48.201332 +0100 ERROR compile/sql_executor.go:136 internal sql executor error: Time.MarshalBinary: unexpected zone offset
    test_utils.go:138: 
        	Error Trace:	/Users/eric/github/matrixone/pkg/tests/testutils/test_utils.go:138
        	            				/Users/eric/github/matrixone/pkg/tests/shard/partition_based_test.go:364
        	            				/Users/eric/github/matrixone/pkg/tests/shard/shard_test.go:108
        	            				/Users/eric/github/matrixone/pkg/tests/shard/partition_based_test.go:347
        	Error:      	Received unexpected error:
        	            	Time.MarshalBinary: unexpected zone offset
        	Test:       	TestUpdateOnNewCN
        	Messages:   	[insert into TestUpdateOnNewCN(id, value) values (1, 1)]
--- FAIL: TestUpdateOnNewCN (29.70s)
=== RUN   TestReplicaBalance
--- SKIP: TestReplicaBalance (0.00s)
=== RUN   TestPartitionBasedShardCanBeCreated
2024/10/16 13:56:48.231103 +0100 INFO malloc/config.go:92 malloc: set default config {"config": {"Allocator":null,"CheckFraction":null,"FullStackFraction":null,"EnableMetrics":null,"HashmapSoftLimit":null,"HashmapHardLimit":null}}

### Expected Behavior

UT test case should pass on MacOS.

### Steps to Reproduce

```Markdown
cd matrixone/pkg/tests/shard
go test .
```

**Comment by zhangxu19830126** [comment]
内部sql执行起内部的timezone序列化包错。

**Comment by qingxinhome** [comment]
目前没有复现

**Comment by qingxinhome** [comment]
造成该错误的原因是调用time.Time.MarshalBinary()函数时，其时区设置不正确
根据go语言标准库源码中MarshalBinary函数实现，Time.MarshalBinary: unexpected zone offset 错误会在时区偏移超出范围的情况下发生：
如果时间对象的时区偏移（以分钟为单位）不在 -32768 到 32767 之间，函数将返回错误。
这意味着，如果时间的时区设定极端（例如，如果使用了一个自定义的不标准时区，某些无效或过于偏移的时区），可能会导致偏移量计算错误，从而引发该错误。

经过验证TestUpdateOnNewCN单元测试中只有一处，会调用time.Time.MarshalBinary()函数，如下图所示
![image](https://github.com/user-attachments/assets/db5b3a02-64df-42c7-8435-019b60141119)

**Comment by qingxinhome** [comment]
该问题如果没有复现，建议关闭
