### ISSUE TITLE
[Bug]: long running occurred during merge run test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19394]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b91afa5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

lots of `long running` log printed.

https://grafana.ci.matrixorigin.cn/goto/afdtMoiHg?orgId=1

take one long running txn as example:

txn_id: eaf1aca1983a486417fed85b2cef8f1b
user: mo_logger
long running log:
```
2024/10/16 10:59:53.178545 +0000 ERROR cn-service found long running txn {"uuid": "", "txn-id": "eaf1aca1983a486417fed85b2cef8f1b", "create-at": "2024/10/16 10:19:54.034270 +0000", "options": "Features:33 CN:\"38636238-3161-6532-3562-666534326363\" SessionID:\"019294d7-49b3-76b9-a88c-3e2ab728ac8c\" ConnectionID:21288 UserName:\"mo_logger\" counter:\"commit: enter:0, exit:0 rollback: enter:0, exit:0 runSql: enter:1, exit:0 incrStmt: enter:1, exit:1 rollbackStmt: enter:0, exit:0 footPrints: [6: enter:1, exit:0] [7: enter:1, exit:0] [8: enter:1, exit:0] [13: enter:1, exit:0] [15: enter:1, exit:0] [16: enter:1, exit:0] \" sessionInfo:\"connectionId 21288||account sys:mo_logger|goRoutineId 11939108|migrate-goRoutineId 0|019294d7-49b3-76b9-a88c-3e2ab728ac8c\" inRunSql:true autocommit:true ", "profile": "ETL:/profile/CN_38636238-3161-6532-3562-666534326363_leakcheck_routine_019294fb-f4da-76e3-9c8d-58a2eea30a27.gz"}
```
goroutine stack: 
[CN_38636238-3161-6532-3562-666534326363_leakcheck_routine_019294fb-f4da-76e3-9c8d-58a2eea30a27.gz](https://github.com/user-attachments/files/17406136/CN_38636238-3161-6532-3562-666534326363_leakcheck_routine_019294fb-f4da-76e3-9c8d-58a2eea30a27.gz)

<img width="1199" alt="企业微信截图_92b7d188-7385-48c2-8751-5bb17b2fb08c" src="https://github.com/user-attachments/assets/42d79b86-ab80-49c6-8930-bae761c10cd6">

### Steps to Reproduce

```Markdown
no long running log
```

**Comment by zhangxu19830126** [comment]
fixed

**Comment by zhangxu19830126** [comment]
Consider the following timing:

logtail paused
cancel all active pipelines
reset logtail state to normal
When a pipeline in 2 is executing and a new transaction is opened in another goroutine to do something (e.g., update the cache of a auto-increment), the new transaction is blocked until the logtail state returns to normal. This creates a circular wait.

**Comment by sukki37** [comment]
@aressu1985 Please help check and verify, thank u.

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
检查了这几天的REGRESSION流程，没有在出现LONGRUNNING情况
