### ISSUE TITLE
[Bug]: Error `do not have privilege to execute the statement` is fired when altering cluster table

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#19395]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

v2.0.0-96d33c50b-2024-10-17

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Create a cluster table
```
CREATE CLUSTER TABLE IF NOT EXISTS `mo_catalog`.`document` (`id` VARCHAR(36) NOT NULL, `kb_id` BIGINT NOT NULL, `name` VARCHAR(100) NOT NULL, `user` VARCHAR(100) NOT NULL, `path` VARCHAR(256) NOT NULL, `reason` VARCHAR(256) NOT NULL, `size` BIGINT NOT NULL, `seg_count` BIGINT NOT NULL, `data_source` TINYINT NOT NULL, `doc_type` TINYINT NOT NULL, `status` TINYINT NOT NULL, `created_at` DATETIME(3) DEFAULT NULL, `updated_at` DATETIME(3) DEFAULT NULL,PRIMARY KEY (`id`, `account_id`));
```
- Add a column for it
```
mysql> ALTER TABLE document add meta longtext;
ERROR 20101 (HY000): internal error: do not have privilege to execute the statement
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

**Comment by daviszhen** [comment]
权限相关

**Comment by YANGGMM** [comment]
等pr合并

**Comment by heni02** [comment]
confirm,closed
commit:0a3d52f3f9b4c740744f8567e689fed784feffe5
mysql> CREATE CLUSTER TABLE IF NOT EXISTS `mo_catalog`.`document` (`id` VARCHAR(36) NOT NULL, `kb_id` BIGINT NOT NULL, `name` VARCHAR(100) NOT NULL, `user` VARCHAR(100) NOT NULL, `path` VARCHAR(256) NOT NULL, `reason` VARCHAR(256) NOT NULL, `size` BIGINT NOT NULL, `seg_count` BIGINT NOT NULL, `data_source` TINYINT NOT NULL, `doc_type` TINYINT NOT NULL, `status` TINYINT NOT NULL, `created_at` DATETIME(3) DEFAULT NULL, `updated_at` DATETIME(3) DEFAULT NULL,PRIMARY KEY (`id`, `account_id`));
mysql> ALTER TABLE `mo_catalog`.document add meta longtext;
Query OK, 0 rows affected (0.05 sec)
mysql> show create table `mo_catalog`.document;
+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table    | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| document | CREATE CLUSTER TABLE `document` (
  `id` varchar(36) NOT NULL,
  `kb_id` bigint NOT NULL,
  `name` varchar(100) NOT NULL,
  `user` varchar(100) NOT NULL,
  `path` varchar(256) NOT NULL,
  `reason` varchar(256) NOT NULL,
  `size` bigint NOT NULL,
  `seg_count` bigint NOT NULL,
  `data_source` tinyint NOT NULL,
  `doc_type` tinyint NOT NULL,
  `status` tinyint NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `meta` text DEFAULT NULL,
  `account_id` int unsigned NOT NULL COMMENT 'the account_id added by the mo',
  PRIMARY KEY (`id`,`account_id`)
) |
+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
