### ISSUE TITLE
[Bug]: TN keeps panic and restart

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19398]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b91afa5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://grafana.ci.matrixorigin.cn/goto/L1kNKoiNR?orgId=1

```
panic: delete table (0,db1,t) not found @ 1729057562706861428-0, start is 1729057521176973883-1, end is 1729057582434225897-0
```
![image](https://github.com/user-attachments/assets/e9107331-4d47-4917-9691-044bd4e4a714)

### Steps to Reproduce

```Markdown
no panic
```

**Comment by LeftHandCold** [comment]
还没复现

**Comment by LeftHandCold** [comment]
还没复现

**Comment by LeftHandCold** [comment]
还没复现

**Comment by LeftHandCold** [comment]
还没复现

**Comment by LeftHandCold** [comment]
同上

**Comment by LeftHandCold** [comment]
同上

**Comment by aressu1985** [comment]
目前一直没有复现过，持续观察，如果code FREEZE之前没有复现，考虑直接关闭

**Comment by LeftHandCold** [comment]
还是没出现

**Comment by LeftHandCold** [comment]
同上
