### ISSUE TITLE
[Bug]: restore 2T data from snapshot report 'table does not exist'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19408]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cf5296b

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

恢复了大约5h后报错 table does not exist

```
mysql> restore account sys from snapshot sp01;


ERROR 1064 (HY000): SQL parser error: table "table_with_pk_index_for_write_1b" does not exist
```

日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%223wf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241016%5C%22%7D%20%7C%3D%20%60sp01%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729137600000%22,%22to%22:%221729155600000%22%7D%7D%7D&schemaVersion=1&orgId=1

快照读能读到数据：
<img width="791" alt="image" src="https://github.com/user-attachments/assets/34a84a43-7736-42ed-afe3-75858b83f285">

### Steps to Reproduce

```Markdown
步骤：
create snapshot sp01 for account sys ;
drop database big_data_test;
restore account sys from snapshot sp01;

big_data_test中有28张表，数据量大约有2T，找不到的表table_with_pk_index_for_write_1b的schema：
create table if not exists big_data_test.table_with_pk_index_for_write_1B( id bigint primary key, col1 tinyint, col2 smallint, col3 int, col4 bigint, col5 tinyint unsigned, col6 smallint unsigned, col7 int unsigned, col8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(16,6), col17 text, col18 json, col19 blob, col20 binary(255), col21 varbinary(255), col22 vecf32(3), col23 vecf32(3), col24 vecf64(3), col25 vecf64(3));
```

**Comment by YANGGMM** [comment]
restore 的时候
create table 成功
{"level":"INFO","time":"2024/10/17 08:52:20.881042 +0000","name":"cn-service","caller":"frontend/snapshot.go:1054","msg":"[sp01] start to create table: table_with_pk_index_for_write_1b, create table sql: CREATE TABLE `table_with_pk_index_for_write_1b` (\n  `id` bigint NOT NULL,\n  `col1` tinyint DEFAULT NULL,\n  `col2` smallint DEFAULT NULL,\n  `col3` int DEFAULT NULL,\n  `col4` bigint DEFAULT NULL,\n  `col5` tinyint unsigned DEFAULT NULL,\n  `col6` smallint unsigned DEFAULT NULL,\n  `col7` int unsigned DEFAULT NULL,\n  `col8` bigint unsigned DEFAULT NULL,\n  `col9` float DEFAULT NULL,\n  `col10` double DEFAULT NULL,\n  `col11` varchar(255) DEFAULT NULL,\n  `col12` date DEFAULT NULL,\n  `col13` datetime DEFAULT NULL,\n  `col14` timestamp NULL DEFAULT NULL,\n  `col15` bool DEFAULT NULL,\n  `col16` decimal(16,6) DEFAULT NULL,\n  `col17` text DEFAULT NULL,\n  `col18` json DEFAULT NULL,\n  `col19` blob DEFAULT NULL,\n  `col20` binary(255) DEFAULT NULL,\n  `col21` varbinary(255) DEFAULT NULL,\n  `col22` vecf32(3) DEFAULT NULL,\n  `col23` vecf32(3) DEFAULT NULL,\n  `col24` vecf64(3) DEFAULT NULL,\n  `col25` vecf64(3) DEFAULT NULL,\n  PRIMARY KEY (`id`)\n)","service":"39373661-3432-6637-3266-323163303563","uuid":"39373661-3432-6637-3266-323163303563"}

{"level":"INFO","time":"2024/10/17 08:52:20.889182 +0000","name":"cn-service","caller":"frontend/snapshot.go:1067","msg":"[sp01] start to insert select table: table_with_pk_index_for_write_1b, insert sql: insert into `big_data_test`.`table_with_pk_index_for_write_1b` SELECT * FROM `big_data_test`.`table_with_pk_index_for_write_1b` {MO_TS = 1729132383153588488 }","service":"39373661-3432-6637-3266-323163303563","uuid":"39373661-3432-6637-3266-323163303563"}


然后insert的时候报table does not exist

**Comment by YANGGMM** [comment]
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/f3abd2cd-fc4e-4015-b51d-a2a0beeca09e">

**Comment by YANGGMM** [comment]
@triump2020 麻烦看一下

**Comment by triump2020** [comment]
原因已大致定位到.

**Comment by Ariznawlll** [comment]
今天恢复也有这个问题：步骤与issue中提到的基本一样

<img width="1257" alt="企业微信截图_31fc874c-78f7-469c-a56b-0ecef8a03476" src="https://github.com/user-attachments/assets/4304b917-ce27-4cb7-affb-b0aab95e3bf6">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22-Ur%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241017%5C%22%7D%20%7C%3D%20%60txn%20is%20stale%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729256400000%22,%22to%22:%221729260000000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by triump2020** [comment]
PR is on the way!

**Comment by triump2020** [comment]
PR 可能只解决了，导致这个问题的原因之一，但如果概率比较大，可能还有其他原因，需要加日志再复现下.

**Comment by Ariznawlll** [comment]
**下午根据pitr恢复2T数据也报该错误**
```
commit: 8d7e7b8
恢复执行的sql： restore from pitr p01 "2024-10-22 03:24:18.547701"
```
<img width="765" alt="image" src="https://github.com/user-attachments/assets/af3f91e1-ec9a-4a8e-a137-f46d636a4e9d">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22MBn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241021%5C%22%7D%20%7C%3D%20%60txn%20is%20stale%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729587600000%22,%22to%22:%221729591200000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by triump2020** [comment]
又完善了Log ， 线上，线下同时在复现。 应该是其他原因，导致了这个问题.

**Comment by triump2020** [comment]
复现步骤：
1.  修改 以下配置：
   [tn.Ckp]
 flush-interval = "5s"
  min-count = 1
 scan-interval = "5s"
 incremental-interval = "10s"
 global-min-count = 3

2. 修改程序: 
     gcPartitionStateTicker = 5 * time.Second
	gcPartitionStateTimer  = 90 * time.Second
   
![1729753427198](https://github.com/user-attachments/assets/daf04add-4144-48e6-93d7-287c2f4edcb7)

3.  运行mo-service 

4.  运行 sql: 
     1>create table tpcc_1000.bmsql_order_line

     2>load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='AKIDUtG3skpK1hK7BSoClmsDVegirATitKiD','secret_access_key'='pXGubPAxolknvyzsqEoRBteLzmbSH3pb','bucket'='mo-load-guangzhou-1308875761','filepath'='tpcc_1000/order-line.csv', 'compression'=''} into table tpcc_1000.bmsql_order_line fields terminated by ',' lines terminated by '\n' parallel 'true'; 

  3> create snapshot 1;
  4> drop database tpcc_1000;
  5> restore account sys from snapshot sp01;

**Comment by triump2020** [comment]
原因已定位，等待修复.

**Comment by triump2020** [comment]
> 又完善了Log ， 线上，线下同时在复现。 应该是其他原因，导致了这个问题.

 经过线下复现，原因就是第一个pr 所修复的，只是修复失败.

**Comment by triump2020** [comment]
由Txn is stale 导致的 table not found 问题应该修复了，线下测试过好多次了. @Ariznawlll 请测试.

**Comment by triump2020** [comment]
等待pr 合并

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
测试中

**Comment by Ariznawlll** [comment]
**用飞哥的复现方式没有出现，测试步骤

复现步骤：**

```
修改 以下配置：
[tn.Ckp]
flush-interval = "5s"
min-count = 1
scan-interval = "5s"
incremental-interval = "10s"
global-min-count = 3

修改程序:
gcPartitionStateTicker = 5 * time.Second
gcPartitionStateTimer = 90 * time.Second

mysql> create table bmsql_order_line (
    ->   ol_w_id         integer   not null,
    ->   ol_d_id         integer   not null,
    ->   ol_o_id         integer   not null,
    ->   ol_number       integer   not null,
    ->   ol_i_id         integer   not null,
    ->   ol_delivery_d   timestamp,
    ->   ol_amount       decimal(6,2),
    ->   ol_supply_w_id  integer,
    ->   ol_quantity     integer,
    ->   ol_dist_info    char(24),
    ->   primary key (ol_w_id, ol_d_id, ol_o_id, ol_number)
    -> ) ;
Query OK, 0 rows affected (0.07 sec)

mysql> load data url s3option {'endpoint'='http://cos.ap-guangzhou.myqcloud.com','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-guangzhou-1308875761','filepath'='tpcc_1000/order-line.csv', 'compression'=''} into table tpcc_1000.bmsql_order_line fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 300014864 rows affected (17 min 14.86 sec)

mysql> create snapshot sp01 for account sys;
Query OK, 0 rows affected (0.06 sec)

mysql> drop database tpcc_1000;
Query OK, 1 row affected (0.11 sec)

mysql> restore account sys from snapshot sp01;
Query OK, 0 rows affected (1 min 55.28 sec)
```

<img width="1675" alt="image" src="https://github.com/user-attachments/assets/3c0187d3-a657-41a8-8e36-9d3d9450a192">

**Comment by Ariznawlll** [comment]
**整个集群大约有2T数据，恢复集群测试：**

**main commit：967435e**

<img width="1159" alt="企业微信截图_e39c0d0d-35b9-4e25-8a29-d9bc6fe1fb30" src="https://github.com/user-attachments/assets/38932ff4-51ba-4b43-84be-33e3c8e8290d">


**恢复执行的sql**：restore cluster from snapshot cluster_sp;


log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22tFc%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-test-20241027%5C%22%7D%20%7C%3D%20%60table_with_pk_for_insert_100m%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730183598993%22,%22to%22:%221730183688383%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by Ariznawlll** [comment]
**恢复account级别，account的数据量大约2T**

mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 5c6909f       |
+---------------+
1 row in set (0.00 sec)

<img width="705" alt="企业微信截图_215120b5-f2a2-4cf1-be93-e63155772535" src="https://github.com/user-attachments/assets/9302b2a0-2675-4b90-9039-eb806d660b28">

恢复成功

**Comment by Ariznawlll** [comment]
**测试结论：**
1. 集群级别的恢复失败，整个集群的数据约2T；
2. account级别的恢复成功，account的数据约2T.

**Comment by triump2020** [comment]
@Ariznawlll   Pls test!

**Comment by Ariznawlll** [comment]
测试中

**Comment by Ariznawlll** [comment]
1.66T集群恢复成功

**Comment by Ariznawlll** [comment]
2.37T数据量集群恢复成功
