### ISSUE TITLE
[Bug]: statement cannot see the previous statements' operations within a txn.

### ISSUE THREAD

**Issue by gouhongshen** [matrixorigin/matrixone#19409]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

badboynt1:delayranges

### Commit ID

6f868849eb36466ebd00f5105839a64489a45405

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> select s_w_id, s_i_id,count(1) from bmsql_stock group by s_w_id, s_i_id having count(1) > 1 limit 10;
+--------+--------+----------+
| s_w_id | s_i_id | count(1) |
+--------+--------+----------+
|      1 |  98305 |        2 |
|      1 |  69565 |        2 |
|      1 |  81920 |        2 |
|      1 |  49152 |        2 |
+--------+--------+----------+
```

### Steps to Reproduce

```Markdown

run tpcc.

run SQL
select s_w_id, s_i_id,count(1) from bmsql_stock group by s_w_id, s_i_id having count(1) > 1 limit 10;

```

**Comment by qingxinhome** [comment]
原因： 物理计划Compile和各个Scope中都包含有TxnOffset属性，mo已经支持对prepare语句的物理计划进行缓存，编译完成物理计划可以重复使用， 但是当使用从缓存中取出的物理计划时，没有对Compile和各个Scope中都包含有TxnOffset属性进行更新
，导致事务内的的语句无法获取正确的TxnOffset, 最终导致读写结果错误
