### ISSUE TITLE
[Tech Request]: support observe cache hit, miss situation

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#19415]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

Export metric to observe the cache usage, including fs mem cache, disk cache, metadata cache.
metric list:
- current bytes
- max bytes
- count of cache hit
- count of cache access times
- count of cache evict from hot part to cold part.

### Why is this needed ?

The ability to observe cache usage helps gauge whether the cache needs to be scaled up or down.

**Comment by xzxiong** [comment]
metric list:
- [x] current bytes
- [x] max bytes
- [x] count of cache hit
- [x] count of cache access times
- [ ] count of cache evict from hot part to cold part.

**Comment by TangxingZhou** [comment]
验证通过
