### ISSUE TITLE
[Tech Request]: dynamic adjustment of metadata-cache-size via RPC

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#19414]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

An API that allows set/get `metadata-cache-size` at runtime, the change should take effect before the RPC returns.
- support setting and evict

### Why is this needed ?

Similar to https://github.com/matrixorigin/matrixone/issues/16475, it allows MO to dynamic optimize the fs metadata cache without restarting the service.

**Comment by reusee** [comment]
done

**Comment by TangxingZhou** [comment]
<img width="476" alt="image" src="https://github.com/user-attachments/assets/2e88f26c-6ceb-4abc-a2d9-0bf2a320edd1">
验证通过
