### ISSUE TITLE
[Tech Request]: dynamic adjustment of GCPercent via RPC

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#19416]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

An API that allows set/get GCPercent at runtime, the change should take effect before the RPC returns.

### Why is this needed ?

The ability to dynamically adjust the GCPercent parameter at runtime via RPC, instead of setting `GOMEMLIMIT` byte paramter. A better way to adjust gc trigger.

**Comment by reusee** [comment]
https://pkg.go.dev/runtime/debug#SetMemoryLimit

https://pkg.go.dev/runtime/debug#SetGCPercent

用这两个函数即可。

**Comment by TangxingZhou** [comment]
<img width="474" alt="image" src="https://github.com/user-attachments/assets/96e759a5-a0b9-4d74-aa59-673cf953fb7d">
测试通过
