### ISSUE TITLE
[Bug]: restore cluster pitr to account , error msg is incorrect

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19426]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f9b836823d139b6939582c6635ee28bbfe6294d2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR 20101 (HY000): internal error: account sys' does not exists at timestamp: 2024-10-18 03:30:30

### Steps to Reproduce

```Markdown
1、创建集群级别pitr21
2、time1
3、创建account a6
4、使用集群级别pitr21 恢复account a6 ，time =time1 报错，提示account "SYS"不存在，提示信息不合理
```

### Additional information

<img width="954" alt="企业微信截图_f613705f-8f94-48b2-9b91-703b871f69b1" src="https://github.com/user-attachments/assets/763f87cc-b598-4556-9b38-79844fd2c540">

**Comment by YANGGMM** [comment]
mysql> create pitr cluster_pitr for cluster range 1'd';
Query OK, 0 rows affected (0.03 sec)

mysql> select now();
+----------------------------+
| now()                      |
+----------------------------+
| 2024-10-18 11:59:09.285662 |
+----------------------------+
1 row in set (0.00 sec)

mysql> 
mysql> create account acc01 admin_name = 'test_account' identified by '111';
Query OK, 0 rows affected (0.41 sec)

mysql> 
mysql> 
mysql> restore account acc01 from pitr cluster_pitr '2024-10-18 11:59:09' acc01;
ERROR 20101 (HY000): internal error: account `sys` does not exists at timestamp: 2024-10-18 11:59:09

复现成功

**Comment by YANGGMM** [comment]
fixed

**Comment by tom-csf** [comment]
验证已经bugfix
