### ISSUE TITLE
[Bug]: create account, restore cluster from pitr, show accounts have no related account.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19438]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f9b836823

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="935" alt="image" src="https://github.com/user-attachments/assets/527583ed-f732-4552-8d1a-2763e8c71b62">

### Steps to Reproduce

```Markdown
create account acc01 admin_name = 'test_account' identified by '111';
create account acc02 admin_name = 'test_account' identified by '111';
create account acc03 admin_name = 'test_account' identified by '111';
show accounts;
create pitr p01 for cluster range 2 'h';
select now(); ----->标记点
drop account acc01;
restore cluster from pitr p01 "2024-10-18 16:22:44.006955";   -->恢复到标记点的时间戳
show accounts;
```

**Comment by YANGGMM** [comment]
<img width="279" alt="image" src="https://github.com/user-attachments/assets/319467d1-c6a3-4f9b-b883-992671ad25dd">

**Comment by Ariznawlll** [comment]
预期行为
