### ISSUE TITLE
[Bug]:  mo report 'object already has a pitr', actucally object does not have a pitr.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19436]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1e16834

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/c4d860e5-283b-430d-8c43-599ad53d8d6f">

以account/database/table为object，每个object都可以创建一个pitr

### Steps to Reproduce

```Markdown
create database test;
use test;
create table table01(col1 int);
create pitr p01 for database test table table01 range 10 'h';
create pitr p02 for database test range 20 'mo';
```

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
```
mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| 712a7e51b     |
+---------------+
1 row in set (0.00 sec)

```
<img width="877" alt="image" src="https://github.com/user-attachments/assets/55c9ff07-d5b4-45bc-998a-80d393b52407">
