### ISSUE TITLE
[Tech Request]: cleanup the cdc related table during drop the account

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19440]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
在删除租户时，清理cdc相关表中 与 此租户的数据。
```

### Why is this needed ?

现在cdc相关的表，被误判为集群表了。

**Comment by ck89119** [comment]
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/a0d6458a-9d83-48f0-ab53-57e7d888d73d">

**Comment by daviszhen** [comment]
done
