### ISSUE TITLE
[Bug]: TPMC of 1000w  is 20% lower than in mo 1.2.0

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19453]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

30195c00243879959f73c68b95db1bd24088a310

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
1*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

<img width="712" alt="image" src="https://github.com/user-attachments/assets/f2070a98-11c4-40ee-a102-333bcf1624f3">

main metrics:
https://grafana.ci.matrixorigin.cn/d/ee086o0rtlq0wc/txn-metrics?orgId=1&var-interval=1m&var-namespace=mo-main-nightly-30195c002-20241018&var-pod=All&from=1729281003000&to=1729283446000

mo-1.2 metrics:
https://grafana.ci.matrixorigin.cn/d/ee086o0rtlq0wc/txn-metrics?orgId=1&var-interval=1m&var-namespace=mo-branch-nightly-c3c1ce0f5-20241018&var-pod=All&from=1729281003000&to=1729284046000

### Steps to Reproduce

```Markdown
run tpcc 1000w test
```

**Comment by badboynt1** [comment]
tpcc 1000仓，数据量比较大，memcache不是完全命中，需要频繁进行替换。

观察main分支跑起来，tps稳定后，cpu利用率不到一半。应该是加锁等待的开销比较大。抓了fgprof以后看到，确实主要是memcache加锁开销大。需要优化

![image](https://github.com/user-attachments/assets/b1159296-e6e9-4810-9ea1-25f9167c57e3)

[prof_1.zip](https://github.com/user-attachments/files/17470279/prof_1.zip)

**Comment by reusee** [comment]
上面的fgprof profile有问题，需要更新到最新的版本。
从 cpu profile 看，内存缓存的锁开销并不大。

**Comment by reusee** [comment]
用更新后的fgprof观察，未发现fifocache锁问题：
[profile.pb.gz](https://github.com/user-attachments/files/17475683/profile.pb.gz)

table scan占耗时的67.2%
![Screenshot from 2024-10-22 19-58-18](https://github.com/user-attachments/assets/f38754cb-3aaf-48e4-8367-051a292dc46e)

fifocache只占2.4%
![Screenshot from 2024-10-22 19-56-53](https://github.com/user-attachments/assets/983e7185-7746-450a-aef0-0fc9d38ec38f)

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
继续优化

**Comment by reusee** [comment]
已优化

**Comment by aressu1985** [comment]
fixed
