### ISSUE TITLE
[Bug]: perf of  random_points and random ranges for 10w basis data is much lower than perf for 100w basis data on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19455]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

30195c00243879959f73c68b95db1bd24088a310

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11405564900/job/31737568554

<img width="714" alt="image" src="https://github.com/user-attachments/assets/6bcd183c-c844-4454-ace1-42d26356795b">

### Steps to Reproduce

```Markdown
run sysbench 10w random points test
```

**Comment by aressu1985** [comment]
update profile soon

**Comment by badboynt1** [comment]
因为10w的数据量太小，没有触发flush。 需要在load数据后强制flush一下

**Comment by aressu1985** [comment]
fixed_
