### ISSUE TITLE
[Bug]: tn oom during daily regression test on tke.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19456]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

30195c002

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url:**  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11405715387/job/31738744730

**namespace:**  mo-main-nightly-30195c002-20241018

<img width="1418" alt="image" src="https://github.com/user-attachments/assets/74fe46ef-fac7-4be3-b069-f1434d0feaf6">

**第一次重启时间（UTC时间2024-10-19 02:09:00）前后5min对应的log：** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22lKf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-30195c002-20241018%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729303500000%22,%22to%22:%221729304100000%22%7D%7D%7D&schemaVersion=1&orgId=1

**第二次重启时间（UTC时间2024-10-19 02:58:00）前后5min对应的log：** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22lKf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-30195c002-20241018%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729306380000%22,%22to%22:%221729306980000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
If you need more details，please contact me
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
fixed
