### ISSUE TITLE
[Bug]: lots of cannot commit a orphan transaction during sysbench write workflow on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19479]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

712a7e51b19118d75be62850113cb616964ef3ae

### Other Environment Information

```Markdown
- Hardware parameters:
3CN: 16C 64G
1DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11427162026/job/31796748557

log link:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22RVh%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-712a7e51b-20241020%5C%22%7D%20%7C%3D%20%60orphan%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

and during this period, the system is very busy
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/7d55d715-8d85-4cc7-bb4d-a3f2dc24e278">
link: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22RVh%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-712a7e51b-20241020%5C%22%7D%20%7C%3D%20%60system%20is%20busy%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

last valid commit: 09afaa9360964fd42ad4767b3ac2b0186e471cbc and comparing the profile between commit `712a7e` and `09afaa` , GC in commit `09afaa` occupy more cpu.

profile in `712a7e`:
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/19726db6-1e6b-48f5-ba6c-1147c767dbd5">
link:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22rzE%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%20%3D%20%5C%22nightly-regression-dis-tp-cn-d486z%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221729463263000%22,%22to%22:%221729465064000%22%7D%7D%7D&schemaVersion=1&orgId=1

profile in `09afaa`:
<img width="1420" alt="image" src="https://github.com/user-attachments/assets/5ff4ded0-8d53-447c-b862-160c7256aad4">
link:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%224L5%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%20%3D%20%5C%22nightly-regression-dis-tp-cn-67frh%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22%7D%5D,%22range%22:%7B%22from%22:%221729376632000%22,%22to%22:%221729378432000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run sysbench test
```

**Comment by volgariver6** [comment]
@iamlinjunhong please help to check this issue.

**Comment by aressu1985** [comment]
经过二分查找，从commit: 848b4d13878f7e1529b986a7549913d9359b4ab6
之后，开始出现GC占用CPU升高
