### ISSUE TITLE
[Bug]:  `txn leak` reported during merge run test maybe false positive

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19477]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

848b4d1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://grafana.ci.matrixorigin.cn/goto/aube8PmNR?orgId=1

<img width="1318" alt="image" src="https://github.com/user-attachments/assets/ae7f3898-c880-47c5-8d8f-f0f4dc5e72d5">

### Steps to Reproduce

```Markdown
no specific
```

**Comment by daviszhen** [comment]
应该是leak。
原因是client断开了连接。

mo进入资源清理阶段。

先关闭链接时，抛出了错误"read tcp 10.142.119.69:6001->10.142.119.62:41832: use of closed network connection"

导致剩余的资源清理阶段没有完成。


![image](https://github.com/user-attachments/assets/f88094ff-359a-4fd0-a85d-4c8c8a1cf26d)
