### ISSUE TITLE
[Bug]: [1020 big data regression] insert into select executed about 3h+. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19476]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e42ff9d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url（insert into select 10Y）:**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11417457953/job/31770041906

**sql执行超时时间设置为3h，如果超过3h，会报错"Execution timeout, continues to execute the next sql..."，并继续执行下一条sql** **(正常情况下执行90min左右)**

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/43cdd306-a366-4f9f-9487-747cb66be05a">

对应时间的longrunning日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22HU-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241019%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729358863000%22,%22to%22:%221729380463000%22%7D%7D%7D&schemaVersion=1&orgId=1

longrunning对应的profile：
[big_data_profile.tar.gz](https://github.com/user-attachments/files/17448227/big_data_profile.tar.gz)

### Steps to Reproduce

```Markdown
trigger big-data-regression

超时sql: insert into big_data_test.table_with_com_pk_index_for_insert_1B(id,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25)  select * from big_data_test.table_with_pk_for_load_1B where col4 != -7508478199581380391;
```

**Comment by sukki37** [comment]
[profile.zip](https://github.com/user-attachments/files/17449909/profile.zip)

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/pull/19467

如果是多cn下向一个带有主键或者唯一约束列的表insert大量数据的情况下，由于某些无法单独执行的pipeline被发送到了remote node，这部分逻辑无法正常运行，最终导致查询卡死。

这个pr修复了这个问题。可以在这两天的daily之类的进行验证。

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11438363504/job/31826943300

今天测试没出现

**Comment by Ariznawlll** [comment]
降级明天再观察一下

**Comment by Ariznawlll** [comment]
没再出现了
