### ISSUE TITLE
[Bug]:  CN OOM Without Workload, Suspected Memory Leak

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19488]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

712a7e5

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/4f11a7ea-2ae1-4504-b2b7-5acbf4d7d191">

https://grafana.ci.matrixorigin.cn/goto/HPWpfwmNg?orgId=1

https://grafana.ci.matrixorigin.cn/goto/FEdpBwiNR?orgId=1

<img width="1458" alt="image" src="https://github.com/user-attachments/assets/da197304-4d21-4b1a-a0d3-ef01f728b8ec">

### Steps to Reproduce

```Markdown
no specific steps
```

**Comment by sukki37** [comment]
https://grafana.ci.matrixorigin.cn/goto/lCTaBwmNg?orgId=1

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/4c3075e5-40a9-4f4b-b08a-67ecfbd5c708">

**Comment by reusee** [comment]
https://grafana.ci.matrixorigin.cn/goto/lCTaBwmNg?orgId=1
从调用栈看，是 LongRunETLMerge 任务里分配的

**Comment by reusee** [comment]
fixed

**Comment by sukki37** [comment]
Need to find out why the MinIO SDK is causing this issue.​⬤

**Comment by reusee** [comment]
原因已找到，传递的 marker 应为 result 的 NextMarker 字段，错用了 Marker 字段

会在这个pr一并修复：https://github.com/matrixorigin/matrixone/pull/19573

**Comment by reusee** [comment]
已修复
