### ISSUE TITLE
[Tech Request]:Merge all accounts' mo_pubs tables to sys

### ISSUE THREAD

**Issue by ck89119** [matrixorigin/matrixone#19495]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Combine all accounts' mo_pubs tables to sys
```

**Comment by Ariznawlll** [comment]
test done
