### ISSUE TITLE
[Bug]: transfer rowids failed, length mismatch, expect 1, got 0 during SYSBENCH write only case on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19505]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e1acf0abe

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11442477628/job/31860865189

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/4a72693b-4af5-4dc2-a027-fb883253da81">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Sfd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-e1acf0abe-20241021%5C%22%7D%20%7C%3D%20%60transfer%20rowids%20failed,%20length%20mismatch,%20expect%201,%20got%200%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729563710859%22,%22to%22:%221729564184038%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run daily regression on distributed
```

**Comment by XuPeng-SH** [comment]
@aptend

**Comment by aptend** [comment]
Not working on this

**Comment by aptend** [comment]
[txn log](https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Sfd%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-e1acf0abe-20241021%5C%22%7D%20%7C~%20%60%28%3Fi%29575f2032d26a45f3180083eaa60c9b25%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729563710000%22,%22to%22:%221729567784000%22%7D%7D%7D&schemaVersion=1&orgId=1)

<img width="1578" alt="image" src="https://github.com/user-attachments/assets/13126438-922c-4a05-a17a-06b6d7679e47">


The failed txn 575f2032d26a45f3180083eaa60c9b25 is an orphan txn, it may miss the pk row on the newly merged object if the row was deleted by another txn.
