### ISSUE TITLE
[Bug]: restore from pitr oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19511]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8d7e7b8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/6eaf7d0b-a4c8-49cb-a403-c010499a3969">

**恢复脚本中执行的sql**
mysql -h 172.16.63.58 -P 6001 -udump -p111 -e 'restore from pitr p01 "2024-10-22 03:24:18.547701";'

**报错 Lost connection**
<img width="872" alt="image" src="https://github.com/user-attachments/assets/f0ce988b-c5a2-41b5-8f12-2b4acad322fb">

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/71deeb08-cda5-4af7-a15d-b4bf9fa4e146">

oom前后10min的memory信息：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22C0G%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%27mo-big-data-20241021%27,pod%3D%27nightly-regression-dis-tp-cn-jrrcz%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221729567200000%22,%22to%22:%221729568400000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
create pitr p01 range 20 'h';

restore from pitr p01 "2024-10-22 03:24:18.547701";
```

**Comment by sukki37** [comment]
maybe dup with #19488

**Comment by Ariznawlll** [comment]
commit: 8415938

第一轮测试：500G的恢复没oom

正在执行1T的测试

**Comment by Ariznawlll** [comment]
今天再测试一下

**Comment by Ariznawlll** [comment]
commit: 89fb035f0f14b08b399c45b516f86509addd7300

今天测试没出现

**Comment by Ariznawlll** [comment]
今天再测试一下

**Comment by Ariznawlll** [comment]
今天测试也没出现了，先关闭
