### ISSUE TITLE
[Bug]: ci: panic delete table failed: query failed

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19524]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

rmSnapshotBvt

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/matrixone/actions/runs/11454226715/job/31868021748

2024-10-22 06:39:35 ERROR Executor:269 - [/home/runner/work/matrixone/matrixone/upstream/test/distributed/cases/zz_accesscontrol/drop_account.sql][row:82][DROP ACCOUNT IF EXISTS `ce46ba96_6c2f_4344_9b80_a1e9f03c600b`;] was executed failed, con[id=0, user=dump, ***
2024-10-22 06:39:35 ERROR Executor:271 - [EXPECT RESULT]:
null
2024-10-22 06:39:35 ERROR Executor:272 - [ACTUAL RESULT]:
internal error: panic delete table failed: query failed: 
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).deleteTable
	/home/runner/work/matrixone/matrixone/upstream/pkg/vm/engine/disttae/txn_database.go:242
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Delete
	/home/runner/work/matrixone/matrixone/upstream/pkg/vm/engine/disttae/txn_database.go:175
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).Delete
	/home/runner/work/matrixone/matrixone/upstream/pkg/vm/engine/disttae/engine.go:481
github.com/matrixorigin/matrixone/pkg/vm/engine.(*EntireEngine).Delete
	/home/runner/work/matrixone/matrixone/upstream/pkg/vm/engine/entire_engine.go:46
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).DropDatabase
	/home/runner/work/matrixone/matrixone/upstream/pkg/sql/compile/ddl.go:134
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
	/home/runner/work/matrixone/matrixone/upstream/pkg/sql/compile/compile.go:358
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce
	/home/runner/work/matrixone/matrixone/upstream/pkg/sql/compile/compile.go:472
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/home/runner/work/matrixone/matrixone/upstream/pkg/sql/compile/compile2.go:235
github.com/matrixorigin/matrixone/pkg/frontend.executeStatusStmtInBack
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/back_status_stmt.go:35
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtInBack
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/back_exec.go:457
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2610
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2577
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2537
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2429
github.com/matrixorigin/matrixone/pkg/frontend.doComQueryInBack
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/back_exec.go:367
github.com/matrixorigin/matrixone/pkg/frontend.(*backExec).Exec
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/back_exec.go:131
github.com/matrixorigin/matrixone/pkg/frontend.doDropAccount.func1
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/authenticate.go:3633
github.com/matrixorigin/matrixone/pkg/frontend.doDropAccount
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/authenticate.go:3769
github.com/matrixorigin/matrixone/pkg/frontend.handleDropAccount
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:1247
github.com/matrixorigin/matrixone/pkg/frontend.execInFrontend
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/self_handle.go:233
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2647
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2608
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2577
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2537
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2429
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:2393
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:3006
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/mysql_cmd_executor.go:3083
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/routine.go:287
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/routine_manager.go:385
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/server.go:511
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/home/runner/work/matrixone/matrixone/upstream/pkg/frontend/server.go:479

log: 太大我本地下载不下来
https://github.com/matrixorigin/matrixone/actions/runs/11454226715  （翻到最下面）
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/191ad900-fb62-4770-898d-2b8187dbcbcd">

### Steps to Reproduce

```Markdown
triggr ci test
```

**Comment by XuPeng-SH** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11488600820/job/31975661057?pr=19549

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11513173609/job/32049403903?pr=19541

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11513173609/job/32049403495?pr=19541

**Comment by XuPeng-SH** [comment]
should be fixed by #19644

**Comment by Ariznawlll** [comment]
观察一哈
