### ISSUE TITLE
[Bug]: Cast float32 to float64

### ISSUE THREAD

**Issue by zengyan1** [matrixorigin/matrixone#19537]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

1dbb5cb7c276256f64bb9c5f8a17f8a6d9f56764

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="375" alt="企业微信20241023-115453@2x" src="https://github.com/user-attachments/assets/9bd7dd82-7ffb-4141-8317-916ecb39e509">

### Steps to Reproduce

```Markdown
create table t(a float);
insert into t values(1.05);
select sum(a) from t;
```

**Comment by zengyan1** [comment]
与Mysql一致
Postgresql和Sqlserver的结果是1.05

**Comment by fengttt** [comment]
Not a bug.
