### ISSUE TITLE
[Bug]: perf of sysbench random_ranges 1000 threads on 10w  data decrease than before

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19534]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

8415938eea7fec24ae4446591207e3cbd6428c8b

### Other Environment Information

```Markdown
- Hardware parameters: Standlone
- OS type:
- Others:
```

### Actual Behavior

commit : 8415938eea7fec24ae4446591207e3cbd6428c8b
<img width="1385" alt="image" src="https://github.com/user-attachments/assets/554ccd8d-6f6d-4e82-a94f-fce2b0eb6d3a">

cpu profile:
[cpu_lower.gar.gz](https://github.com/user-attachments/files/17484534/cpu_lower.gar.gz)

commit: c23a51fdb54087fc945ce7d0cc82f4ecec0a045c
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/d025283f-4561-451f-bd49-a34d3f4416b7">

cpu profile:
[cpu_higher.gar.gz](https://github.com/user-attachments/files/17484590/cpu_higher.gar.gz)

after binsearch, the issue is caused by pr：
<img width="854" alt="image" src="https://github.com/user-attachments/assets/d8c87111-0fa9-46f3-8ead-97399f003a1b">

commit: ac76417fdad34c78f71ea72817b38a52177ebad9

### Steps to Reproduce

```Markdown
run sysbench random range test：
1、git clone mo-sysbench
2、sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_common.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10    cleanup
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 select_random_ranges.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10   prepare;
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 select_random_ranges.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --time=30 --report-interval=10    --range_selects=off --point_selects=1 --threads=1000 run
```

**Comment by badboynt1** [comment]
我今天在看1000仓1000并发 random ranges的问题， 从profile里看，93%的耗时在处理cast谓词上。但是据 @m-schen 所说，cast谓词执行一次以后应该会自动折叠掉。 麻烦 @ouyuanning 确认一下是不是折叠的逻辑改坏了？ 
![企业微信截图_17296498376334](https://github.com/user-attachments/assets/3981d68a-5f1b-40bc-80d9-19e5760a387a)

**Comment by zengyan1** [comment]
<img width="864" alt="企业微信20241025-160703@2x" src="https://github.com/user-attachments/assets/26706156-075e-4e3d-85db-449c10395ae4">

**Comment by zengyan1** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
