### ISSUE TITLE
[Bug]: bvt failed in create_user_default_role.sql

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19547]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-10-23 09:01:52 ERROR Executor:269 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/tenant/privilege/create_user_default_role.sql][row:147][grant select on table v.B to r1;] was executed failed, con[id=0, user=dump, ***
2024-10-23 09:01:52 ERROR Executor:271 - [EXPECT RESULT]:
null
2024-10-23 09:01:52 ERROR Executor:272 - [ACTUAL RESULT]:
internal error: there is no table "b" in database "v"

### Steps to Reproduce

```Markdown
https://github.com/badboynt1/matrixone/actions/runs/11476146405/job/31935532071?pr=368
```

**Comment by YANGGMM** [comment]
[Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64(LAUNCH,PROXY)-reports.zip](https://github.com/user-attachments/files/17516889/Standalone-Multi-CN-e2e-BVT-Test-on-Linux-x64.LAUNCH.PROXY.-reports.zip)


前后table 已经创建成功
然后back exec 
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/79265f96-6671-4d5b-8d7f-522cf16c5773">

<img width="1301" alt="image" src="https://github.com/user-attachments/assets/603b6612-c4b1-407f-a2cf-20e599dbce31">

报table 不存在

**Comment by YANGGMM** [comment]
麻烦 @XuPeng-SH  看一下

**Comment by XuPeng-SH** [comment]
@aptend

**Comment by aptend** [comment]
This issue shares the same root cause as #19524.
