### ISSUE TITLE
[Bug]: bvt failed in snapshot_restore_to_table_view.sql

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19548]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2024-10-23 08:59:37 INFO  Executor:37 - Start to execute the script file[/home/runner/work/matrixone/matrixone/test/distributed/cases/snapshot/snapshot_restore_to_table_view.sql] now, and it will take a few moment,pleas wait......
2024-10-23 08:59:44 ERROR Executor:269 - [/home/runner/work/matrixone/matrixone/test/distributed/cases/snapshot/snapshot_restore_to_table_view.sql][row:466][drop database University;] was executed failed, con[id=0, user=dump, ***
2024-10-23 08:59:44 ERROR Executor:271 - [EXPECT RESULT]:
null
2024-10-23 08:59:44 ERROR Executor:272 - [ACTUAL RESULT]:
internal error: panic delete table failed: query failed: 
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).deleteTable
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_database.go:242
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Delete
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_database.go:175
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).Delete
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:481
github.com/matrixorigin/matrixone/pkg/vm/engine.(*EntireEngine).Delete
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/entire_engine.go:46
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).DropDatabase
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/ddl.go:134
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:358
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:472
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile2.go:235
github.com/matrixorigin/matrixone/pkg/frontend.executeStatusStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/status_stmt.go:141
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2758
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2608
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2577
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2537
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2429
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2393
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3006
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:[3083](https://github.com/badboynt1/matrixone/actions/runs/11476146405/job/31935531518?pr=368#step:7:3084)
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:287
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:511
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:479
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:211
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:207
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700

### Steps to Reproduce

```Markdown
https://github.com/badboynt1/matrixone/actions/runs/11476146405/job/31935531518?pr=368
```

**Comment by aptend** [comment]
dup with #19524
