### ISSUE TITLE
[Bug]: Plan阶段出来的列表达式，存在RelPos < 0的情况。

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#19574]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

b951e492203ed7e953c84c4fa0417272a72c0a34

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

目前传给 NewExpressionExecutor 进行计算的表达式，
在count(*)情况下会出现 RelPos = -2的情况。（应该还有其他情况会出现这种问题，我记得plan阶段的bind ctx中有较多的特殊标记）。

我不能确定这个是不是符合预期的，
目前的代码是执行的时候将其指定为0进行计算的。我担心总是指定成0会出问题。

### Expected Behavior

1. 不需要在 NewExpressionExecutor 函数中判断 RelPos 是否 < 0。

### Steps to Reproduce

```Markdown
1. 搜索代码中 `[issue#19574]` 并移除判断 < 0的代码。
2. 执行bvt中join目录的case.
3. 步骤2会在计算projection时因为在data中取下标为-2的元素而panic.
```

### Additional information

其他case可能也有问题，我没有进行更多的尝试。
目前我会保留这个判断逻辑。

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/pull/19572

需要等到我这个pr合并后才能看到这部分代码和tag，
我先提了这个issue方便在代码中注释准确的issue号。

**Comment by m-schen** [comment]
pr暂时合不进去，还有点问题要解决，这个issue先挂到backlog.

**Comment by m-schen** [comment]
先合并了一部分pr，但已可以用于追踪该issue。因此调整到2.01

**Comment by aunjgr** [comment]
聚合函数的RelPos = -2是正常情况

**Comment by fengttt** [comment]
Close.
