### ISSUE TITLE
[Bug]: `internal error: wait notify message timeout` error is fired when running SQL

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#19592]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

v2.0.0-3bea8b810-2024-10-24

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Execute TPCH Q9 and the result is as below, the duration is more than 3 hours and it fails in the end:
```
mysql> select transaction_id,request_at,response_at,error,err_code,status from system.statement_info where statement_id = '0192b896-c5ba-723a-b2ee-d65b5fe7afe8' and request_at >= '2024-10-23 08:55:00' and request_at < '2024-10-23 08:56:00';
+----------------------------------+----------------------------+----------------------------+---------------------------------------------+----------+--------+
| transaction_id                   | request_at                 | response_at                | error                                       | err_code | status |
+----------------------------------+----------------------------+----------------------------+---------------------------------------------+----------+--------+
| 0095d0ac1da2293017ff1f8e22741215 | 2024-10-23 08:55:41.754064 | 2024-10-23 12:00:14.403071 | internal error: wait notify message timeout | 20101    | Failed |
+----------------------------------+----------------------------+----------------------------+---------------------------------------------+----------+--------+
1 row in set (0.04 sec)
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Cloud dev env
Refer to https://github.com/matrixorigin/MO-Cloud/issues/4305
Log: https://grafana.cn-dev.matrixone.tech/goto/Zv9U9WWNR?orgId=1

**Comment by m-schen** [comment]
runOnce的逻辑有点问题，
当多棵pipeline树之间相互存在依赖的时候，tree a报错无法及时关闭tree b导致了3小时报错 （这时候应该是session关闭了才导致错误可以抛出来，否则该issue的情况会永远卡住）。

报这个错误的逻辑暂时还不明确，
暂时认为是另一个cn挂掉重启之类的，但是旧的ip地址依旧可以tcp连上（以及连着的tcp并没有断开）。

**Comment by m-schen** [comment]
报这个错的原因应该是由于网络问题，导致“pipeline build succeed”的信号没有发过来，这里等待45秒没有收到通知，因此报错。
这个无法肯定。

**Comment by m-schen** [comment]
相关修改已合并，现在不会发生卡死很久的情况。

但是这个错误还是会因为网络波动等问题抛出，这个错误不会进行移除。
