### ISSUE TITLE
[Bug]:  lots of error"internal error: panic runtime error: makeslice: len out of range" during stability test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19609]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

3999057d7482b021a8ec6aea2567870837f6c64b

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

There were lots of error"internal error: panic runtime error: makeslice: len out of range" during stability test on distributed mode.
**[tpcc]**
2024-10-26 14:50:51 ERROR ConsistencyCheck:153 - SQL: select s_w_id, s_i_id,count(1) from bmsql_stock group by s_w_id, s_i_id having count(1) > 1 limit 10;
2024-10-26 14:51:25 ERROR ConsistencyCheck:152 - internal error: panic runtime error: makeslice: len out of range:
runtime.panicmakeslicelen
        /usr/local/go/src/runtime/slice.go:29
runtime.makeslice
        /usr/local/go/src/runtime/slice.go:111
github.com/matrixorigin/matrixone/pkg/container/pSpool.initSpoolBuffer
        /go/src/github.com/matrixorigin/matrixone/pkg/container/pSpool/buffer.go:41
github.com/matrixorigin/matrixone/pkg/container/pSpool.initCachedBatch
        /go/src/github.com/matrixorigin/matrixone/pkg/container/pSpool/copy.go:53
github.com/matrixorigin/matrixone/pkg/container/pSpool.InitMyPipelineSpool
        /go/src/github.com/matrixorigin/matrixone/pkg/container/pSpool/method.go:33
github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch.(*Dispatch).Prepare
        /go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/dispatch/dispatch.go:51
github.com/matrixorigin/matrixone/pkg/vm.Prepare.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:37
github.com/matrixorigin/matrixone/pkg/vm.doHandleAllOp
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:574
github.com/matrixorigin/matrixone/pkg/vm.HandleAllOp
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:578
github.com/matrixorigin/matrixone/pkg/vm.Prepare
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:36
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:59
[benchmarksql-error.log](https://github.com/user-attachments/files/17529338/benchmarksql-error.log)

**[tpch]**

2024-10-26 00:49:21 The query_id is: 0192c490-6199-7121-9e27-7a446603504b
2024-10-26 00:49:21 Now start to compare query result for [report/TPCH_10/q15.txt,golden/TPCH_10/q15.txt]
2024-10-26 00:49:21 The row count of two files does not equal to each other, [report/TPCH_10/q15.txt] and [golden/TPCH_10/q15.txt]
2024-10-26 00:49:21 The row count of file[report/TPCH_10/q15.txt] is 9, but the row count of file[golden/TPCH_10/q15.txt] is 1
2024-10-26 00:49:21The real result is:
ERROR 20101 (HY000) at line 1: internal error: panic runtime error: makeslice: len out of range:
runtime.panicmakeslicelen
        /usr/local/go/src/runtime/slice.go:29
runtime.makeslice
        /usr/local/go/src/runtime/slice.go:111
github.com/matrixorigin/matrixone/pkg/container/pSpool.initSpoolBuffer
        /go/src/github.com/matrixorigin/matrixone/pkg/container/pSpool/buffer.go:41
github.com/matrixorigin/matrixone/pkg/container/pSpool.initCachedBatch
        /go/src/github.com/matrixorigin/matrixone/pkg/container/pSpool/copy.go:53
github.com/matrixorigin/mat
[tpch.log](https://github.com/user-attachments/files/17529341/tpch.log)

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22egi%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-3999057-202410252351%5C%22%7D%20%7C%3D%20%60internal%20error:%20panic%20runtime%20error:%20makeslice:%20len%20out%20of%20range%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729895415000%22,%22to%22:%221729924815000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
it seems caused by https://github.com/matrixorigin/matrixone/pull/19497, please @m-schen help to check

**Comment by m-schen** [comment]
https://github.com/matrixorigin/matrixone/pull/19604

这个pr修了这个问题。

**Comment by aressu1985** [comment]
fixed
