### ISSUE TITLE
[Bug]: log tail subscriber is not ready

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#19608]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
2024-10-26 02:26:24 ERROR Executor:269 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/ddl/partition4.sql][row:80][select * from insert_ignore_06 order by sale_id;] was executed failed, con[id=0, user=dump, ***
2024-10-26 02:26:24 ERROR Executor:271 - [EXPECT RESULT]:
sale_id    product_id    sale_amount    sale_date
2024-10-26 02:26:24 ERROR Executor:272 - [ACTUAL RESULT]:
internal error: log tail subscriber is not ready
2024-10-26 02:26:24 INFO  Executor:291 - The script 

```

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11528084868/job/32094731215?pr=19541
```

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11528084868/job/32095610025?pr=19541

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11528613939/job/32095977444?pr=19603

**Comment by volgariver6** [comment]
二分跑了一下，应该是 cb5b3fe9bc50dd7b3c54824392b493b8873c3e9e 引入的问题，麻烦 @m-schen 看一下

**Comment by m-schen** [comment]
已经在main分支上进行了修复，当天跑过3次ci并没有出现该问题。
后续的pr没有反应这个问题，应该已经恢复了。

原因分析：
run once()方法中修改的代码导致部分查询出错时无法正常retry，
这应该导致了某个内部执行器所执行的sql语句的误判，在没执行成功前便返回了。
发生重连后，提前对外通知cn的服务恢复了。
当有客户端发来查询时，检测到了cn还没恢复成功，就报出了这个错误。

**Comment by aressu1985** [comment]
fixed
