### ISSUE TITLE
[Bug]: [date 10.25]standalone regression: vector lists=1000 query test mo hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19611]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0f04cc3ad86fd5a80f314a05c5c10308705c3954

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11520092574/job/32070848888
<img width="1421" alt="企业微信截图_d5905a9f-3161-4df3-8c60-8257675cea2e" src="https://github.com/user-attachments/assets/3b922ace-f08e-4a6f-bfa4-b7594639c48c">

客户端也无法登陆：
<img width="938" alt="企业微信截图_6c63ab6f-d0dc-4f0f-958d-568518bcd864" src="https://github.com/user-attachments/assets/c962d6a3-9c80-417e-bc25-9fb02143907d">

mo log：
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-0f04cc3a-20241025-222750.log%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221729921897206%22,%22to%22:%221729929097206%22%7D%7D%7D&schemaVersion=1&orgId=1

上一个回归没问题的commit：57098bef4e96af0b66655e8eba28a012bbad7566
<img width="740" alt="企业微信截图_268a89ad-83ef-4f5d-ad63-0bd995104809" src="https://github.com/user-attachments/assets/f465fe4e-732f-47f8-9509-6784afbca84a">

### Steps to Reproduce

```Markdown
standalone regression gist960 vector lists=1000 probe=5 k=10 test
```

**Comment by volgariver6** [comment]
<img width="1409" alt="WeChatWorkScreenshot_19647419-5240-48e6-9b1b-294b6e0c442b" src="https://github.com/user-attachments/assets/6516420b-8a3a-40e5-bc52-53a6a654468b">

麻烦岳声改一下unlock的逻辑，要不然锁不释放，导致很多goroutine卡死了

**Comment by aressu1985** [comment]
fixed
