### ISSUE TITLE
[Bug]: perf of tpcc 10-10 dereased about 10-20 percent on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19617]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

57098bef4e96af0b66655e8eba28a012bbad7566

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11501553064/job/32023695611

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/1b4ef90a-633c-455e-bf7b-3a24ce9da241">

after binsearched, this issue was from the commit:
ab0cdb8e24943f249b7cc3713cc50b02deba0f75

### Steps to Reproduce

```Markdown
run tpcc 10-10 test
```

**Comment by XuPeng-SH** [comment]
reverted

**Comment by aressu1985** [comment]
fixed
