### ISSUE TITLE
[Bug]: lots of error "cannot commit a orphan transaction" after stability test for about 14 hours on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19620]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f2b8a40

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

There were lots of error "cannot commit a orphan transaction" after stability test for about 14 hours on distributed mode
**[tpcc]**
2024-10-27 14:37:44 FATAL jTPCCTerminal:328 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20705, ErrorMessage : cannot commit a orphan transaction
2024-10-27 14:37:44 FATAL jTPCCTerminal:214 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20705, ErrorMessage : cannot commit a orphan transaction
2024-10-27 14:37:44 FATAL jTPCCTerminal:214 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20705, ErrorMessage : cannot commit a orphan transaction
2024-10-27 14:37:44 FATAL jTPCCTerminal:328 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20705, ErrorMessage : cannot commit a orphan transaction
2024-10-27 14:37:45 FATAL jTPCCTerminal:328 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20705, ErrorMessage : cannot commit a orphan transaction
2024-10-27 14:37:45 FATAL jTPCCTerminal:328 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20705, ErrorMessage : cannot commit a orphan transaction

**[sysbench]**

TxnName : update_pk
Statement : UPDATE sbtest2 SET k=k+100 WHERE id = 5878;
ErrorCode : 20705
ErrorMessage : cannot commit a orphan transaction
Expected : false

2024-10-27 14:37:40 ERROR TransExecutor:274 -
ErrorTime : 2024-10-27 14:37:40
RequestTime : 2024-10-27 14:36:59.180
TxnName : update_pk
Statement : UPDATE sbtest8 SET k=k+100 WHERE id = 6611;
ErrorCode : 20705
ErrorMessage : cannot commit a orphan transaction
Expected : false

2024-10-27 14:37:40 ERROR TransExecutor:274 -
ErrorTime : 2024-10-27 14:37:40
RequestTime : 2024-10-27 14:36:59.214
TxnName : update_pk
Statement : UPDATE sbtest2 SET k=k+100 WHERE id = 51961;
ErrorCode : 20705
ErrorMessage : cannot commit a orphan transaction
Expected : false

2024-10-27 14:37:40 ERROR TransExecutor:135 -
ErrorTime : 2024-10-27 14:37:40
RequestTime : 2024-10-27 14:37:40.831
TxnName : delete_insert
Statement : insert into sbtest3 values(57133,4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-914
ErrorCode : 20705
ErrorMessage : cannot commit a orphan transaction
Expected : false

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%220Qv%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-f2b8a40-202410262139%5C%22%7D%20%7C%3D%20%60cannot%20commit%20a%20orphan%20transaction%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730024495474%22,%22to%22:%221730028078168%22%7D%7D%7D&schemaVersion=1&orgId=1

resource dashboard:
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/07222f2b-e810-455d-96ef-6d0ade5b3d3c">

https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-job=kubernetes-service-endpoints&var-cluster=&var-namespace=mo-f2b8a40-202410262139&from=1730006711590&to=1730028311590

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by aressu1985** [comment]
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/6ace4fb6-ff02-45a0-bd90-da0486121b86">
这几个PR中间的一个PR导致的

**Comment by aylei** [comment]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/7980b019-d818-4e14-829b-dcc7ac22eee5">

中间有一个 CN OOM

**Comment by zhangxu19830126** [comment]
![Image](https://github.com/user-attachments/assets/dda48d14-8301-42a3-84fa-f79d7bf33c9b)
在日志给的时间段内，整个集群非常繁忙，1s的定时器，有的被延迟到5,6s才会被执行。延迟非常大。

**Comment by zhangxu19830126** [comment]
锁服务检测到很多事务，超过10秒没有联系，认为是孤儿事务了。

**Comment by zhangxu19830126** [comment]
![Image](https://github.com/user-attachments/assets/6da5dd1a-9f7b-4792-9c91-181b9539425b)
出问题的一个小时间段内，GC扫描占用的cpu非常高。

**Comment by zhangxu19830126** [comment]
@reusee 应该在 #19573 这个pr的fix了。这个fix没有进去之前，会导致etl的merge占用大量内存，导致gc扫描时间太长。导致系统繁忙，io拿不到cpu。

**Comment by aressu1985** [comment]
testing

**Comment by guguducken** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11591938392/job/32279170774

**Comment by aressu1985** [comment]
fixed
