### ISSUE TITLE
[Bug]: Duplicate entry '47652' for key 'id during sysbench read_write and write_only cases on distributed

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19628]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

967435ecc961c952fcd6faf5dd2c2fcac952d530

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PRXOY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11541331975/job/32129077656

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22PHL%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-967435ecc-20241027%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730067480857%22,%22to%22:%221730068232716%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
occassionally in sysbench read_write and write_only cases
```

**Comment by triump2020** [comment]
Duplicate with #18400

**Comment by aressu1985** [comment]
update on  10.31
commit: 
job link:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11596736880/job/32308601638
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/b609e0c7-2573-4218-b239-763a16795194">

0bbda669365e51df6d65fd33219f34f1515e8717

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22f0j%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-0bbda6693-20241030%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730331231787%22,%22to%22:%221730332327716%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by triump2020** [comment]
Being reproduce

**Comment by triump2020** [comment]
Being reproduce

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/19908

**Comment by aressu1985** [comment]
PR已经合入，当天REGRESSION没有在出现，转测试回归，继续观察

**Comment by heni02** [comment]
待观察一周

**Comment by LeftHandCold** [comment]
> main commit：f22612cd9 main分支sysbench100w read_write和write_only出现了dup job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11879712934/job/33107905635
> 
> log： https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22s-u%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-f22612cd9-20241117%5C%22%7D%20%7C%3D%20%60Duplicate%20entry%20%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731882204055%22,%22to%22:%221731882856355%22%7D%7D%7D&schemaVersion=1&orgId=1

这个case是因为read_write中对id 有一个delete和insert操作，当delete一个不存在的id就会出现。比如session1 delete key100，再insert 100，session 2 delete key100 再insert 100，虽然session1 锁住了这个key100，但是当commit后，session2 的delete应该没有retry，所以没有拿到session 1insert的 key 100，所以这个delete并没有执行，并insert key100 dup。

**Comment by LeftHandCold** [comment]
本地复现不了的原因是因为，本地跑sysbench 10w的时候，id 1～10w是全的，不会出现删除一个不存在的id。tke上由于自增列 cache的原因可能会出现id空洞，所以才会dup

**Comment by aressu1985** [comment]
fixed
