### ISSUE TITLE
[Bug]: 链接MO时卡住不动，然后报错ERROR 20101 (HY000): internal error: no available CN server

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#19640]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

3bea8b810

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
阿里云Dev环境
```

### Actual Behavior

mysql -h freetier-02.cn-hangzhou.cluster.cn-dev.matrixone.tech -P 6001 -u 0192d23c-d60c-7362-8833-e95bb92c4951:admin:accountadmin  -p
链接报错如上。
使用port-forward到本地直连CN，发现只有freetier-02-s2-668dbf7f57-cn-sp6ld这个Pod持续连不上，卡住不动。

### Expected Behavior

应该正常链接

### Steps to Reproduce

```Markdown
如上
```

**Comment by daviszhen** [comment]
从日志上看出问题期间，有long running 和 卡在commit的事务。

![image](https://github.com/user-attachments/assets/ea6399e5-de63-4c8b-a4ef-f6a11f359309)


https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22Lgj%22:%7B%22datasource%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22freetier-02%5C%22%7D%20%7C%3D%20%60found%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730104200000%22,%22to%22:%221730107800000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
停止执行器时，compile service 卡住。

```
goroutine 604 [chan receive, 350 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/compile.queryDoneWaiter.checkCompleted(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compileService.go:79
github.com/matrixorigin/matrixone/pkg/sql/compile.(*compileAdditionalInformation).kill(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compileService.go:65
github.com/matrixorigin/matrixone/pkg/sql/compile.(*ServiceOfCompile).KillAllQueriesWithError(0xc00119b660)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compileService.go:185 +0xf4
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnClient).AbortAllRunningTxn(0xc001ba65a0)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/client.go:645 +0x243
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).abortAllRunningTxn(0xc00080e488)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/engine.go:719 +0x5f
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*PushClient).connect(0xc00080e580, {0x59427f0, 0xc006feab90}, 0xc00080e488)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:838 +0x225
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*connector).run(0xc0048bd9c0, {0x59427f0, 0xc006feab90})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:261 +0x4b
created by github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).InitLogTailPushModel in goroutine 466
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail_consumer.go:1542 +0x252
```

**Comment by daviszhen** [comment]
与#4285 是同一个问题。 https://github.com/matrixorigin/MO-Cloud/issues/4285#issuecomment-2425817868

**Comment by xiaoshuwei** [comment]
好的，需要QA先验证下

**Comment by aressu1985** [comment]
已验证，问题关闭
