### ISSUE TITLE
[Bug]: insert into select executed about 3h.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19653]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5c6909f1d4830c24856083b42ba3bed2b197c856

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11552576940/job/32169247716

sql执行超时时间设置为3h，如果超过3h，会报错"Execution timeout, continues to execute the next sql..."，并继续执行下一条sql (正常情况下执行90min左右)
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/0aca3adc-3b35-4d61-b5df-4ee897e82c4f">

long running日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22tFc%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241028%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730140401000%22,%22to%22:%221730151201000%22%7D%7D%7D&schemaVersion=1&orgId=1

longrunning对应的profile：
[profile1029.zip](https://github.com/user-attachments/files/17550913/profile1029.zip)

### Steps to Reproduce

```Markdown
trigger big data test on tke
```

**Comment by jensenojs** [comment]
<img width="1523" alt="image" src="https://github.com/user-attachments/assets/59a1abb8-ef59-4e0f-9823-8d160522aeaa">

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%225RM%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241028%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221730149221000%22,%22to%22:%221730151201000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aptend** [comment]
<img width="654" alt="企业微信截图_b0e46546-e1f1-4886-919d-721318099eef" src="https://github.com/user-attachments/assets/44498e3a-b536-4ed5-8c78-f19b441ac740">

@volgariver6 PTAL

**Comment by volgariver6** [comment]
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/f59afb88-491b-4f1a-b6e6-84b18f2a7cab">

上图显示了执行SQL语句的时间和报错的时间（UTC时间）：
1. 执行 insert into 语句的时间是“18:33:21”，
2. 超时报错的时间是“21:33:21”，


https://grafana.ci.matrixorigin.cn/explore?panes=%7B%229W-%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-20241028%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%21%3D%20%60slow%20event%60%20%7C%3D%20%60272513%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730136600000%22,%22to%22:%221730152799000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1801" alt="image" src="https://github.com/user-attachments/assets/2d130b82-2612-4ba6-8b9e-9a9481b8487b">

上图和链接显示了测试的表订阅和取消订阅的时间：
1. 目标表 table_with_com_pk_index_for_insert_1b 订阅的时间是 18:33:21，取消订阅的时间是 19:41:43

<img width="1471" alt="image" src="https://github.com/user-attachments/assets/a89e95b9-57a8-4281-9d5d-d116eb73443c">

1. 而根据goroutines中分析出，func (gs *GlobalStats) Get() 被调用的时间大概是19:50:00之后

由次可以推断：
1. 目标表 table_with_com_pk_index_for_insert_1b订阅过，但是在调用 Get() 之前就被取消订阅了
2. 导致了在update stats的时候，等待表的订阅而卡住

**Comment by volgariver6** [comment]
所以猜测是表先被订阅，而在同一个请求中，订阅完成之后，在执行别的请求，一直没有获取 stats，而在获取stats的时候，该表已经被取消了订阅。

优化的方法是，在取消订阅之前，检查这个表是否被获取过stats了，如果没有，那么不能取消订阅这个表。

**Comment by volgariver6** [comment]
fixed

**Comment by Ariznawlll** [comment]
**今天测试没出现**

**commit：dbab6bbe1bc016121bb828a947d71af918ef5548**

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595070467

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/ec295478-14a5-4e30-a4a6-0684d028f8b2">
