### ISSUE TITLE
[Bug]: restore account from pitr report 'internal error: database 'mo_catalog' does not exists at timestamp: 2024-10-28 14:32:08'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19651]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

ef654a2188934e3cbee77e1f1a9b4ede8111c745

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11555527922/job/32161149982**

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/385523c6-f0ed-4245-904c-65912eab07e2">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22tFc%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-pitr-test-20241028%5C%22%7D%20%7C%3D%20%60internal%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730126241000%22,%22to%22:%221730127321000%22%7D%7D%7D&schemaVersion=1&orgId=1

**数据量：大约70G**

**恢复步骤：**
```
1. 创建pitr：
./mo_br pitr create --host 172.16.57.92 --port 6001 --user "dump" --password "111" --pname "pitr01" --level "account" --account "sys" --rangevalue 10 --rangeunit "h" --log_level "debug"
2. 创建db、表；
3. load TPCC数据；
4. 获取restore时间；
5. 执行tpcc测试；
6. 恢复
./mo_br pitr restore --host 172.16.57.92 --port 6001 --user "dump" --password "111" --pname "pitr01" --timestamp "2024-10-28 14:32:08" --account "sys" --log_level "debug"
```

### Steps to Reproduce

```Markdown
See detail in Actual Behavior.
```

**Comment by YANGGMM** [comment]
sys 租户在恢复系统租户的时候其他数据库都恢复完成了，然后在恢复 mo_catalog的时候先去检查mo_catalog是否存在，然后报错了，需要麻烦 @triump2020  看一下

**Comment by aptend** [comment]
This issue is caused by the incomplete initialization of the partition state for snapshot read.

**Comment by triump2020** [comment]
Partition State for snapshot read need to init : 

 
![企业微信截图_1730188854916](https://github.com/user-attachments/assets/01a990c5-90ab-48f4-9f63-a58c40a4f916)

**Comment by Ariznawlll** [comment]
**commit：0bbda669365e51df6d65fd33219f34f1515e8717**

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11605540863/job/32316616804

今天测试正常
