### ISSUE TITLE
[Bug]: Stand-alone Sysbench_1000w and tke Sysbench_100w performance decreased about 40% for insert and delete cases

### ISSUE THREAD

**Issue by x030911** [matrixorigin/matrixone#19664]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5bc27a6fa0a6767f2a3d6a1146a4943a550c731e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
单机Sysbench_1000w.delete_1000性能下降
tke Sysbench_100w.delete_1000性能下降
![image](https://github.com/user-attachments/assets/d9d43001-056f-47c2-9ddb-7afce23f7562)
![image](https://github.com/user-attachments/assets/61b754cb-b456-46e0-b868-67690c86db79)

### Steps to Reproduce

```Markdown
单机128 Sysbench_1000w test
tke Sysbench_100w test
```

**Comment by x030911** [comment]
单机Sysbench_1000w.delete_1000二分结果 @badboynt1 cc
![企业微信截图_17301937239583](https://github.com/user-attachments/assets/5c3bc1a7-6049-4f8e-930f-dff1bee71eb3)

**Comment by aressu1985** [comment]
fixed
