### ISSUE TITLE
[Feature Request]: Mathematical Built-in function sin()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1966]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Follow the syntax and behavior of mysql 8.0 

[SIN(X)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_sin)

Returns the sine of X, where X is given in radians.
```
mysql> SELECT SIN(PI());
        -> 1.2246063538224e-16
mysql> SELECT ROUND(SIN(PI()));
        -> 0
```
The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math sin() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by hiyoyolumi** [comment]
Can it be assigned to me, I want try it.

**Comment by dengn** [comment]
> Can it be assigned to me, I want try it.

Sure, Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by hiyoyolumi** [comment]
> > Can it be assigned to me, I want try it.
> 
> Sure, Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

Ok, I have done this.

**Comment by dengn** [comment]
> > > Can it be assigned to me, I want try it.
> > 
> > 
> > Sure, Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx
> 
> Ok, I have done this.

Issue assigned. Good luck！

**Comment by fansehep** [comment]
I have done the sin functions.

**Comment by dengn** [comment]
Well implemented.
