### ISSUE TITLE
[Bug]: sysbench100w delete 1000threads mo reported panic runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#19665]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

fc4b674b2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11570141997/job/32206186324
<img width="1349" alt="企业微信截图_dc2ef42e-84bf-4364-918a-bab1f6533842" src="https://github.com/user-attachments/assets/7998f7e9-a609-436b-bcf3-521efd4a3a07">

log： https://grafana.ci.matrixorigin.cn/goto/uCap62WHR?orgId=1

### Steps to Reproduce

```Markdown
sysbench100w delete threads test
```

**Comment by heni02** [comment]
二分结果：#19642有问题
<img width="1325" alt="企业微信截图_61223888-999f-40b3-9ba6-06ea6a6ce372" src="https://github.com/user-attachments/assets/a3a16ef2-f66b-46ec-93eb-2d1bc347e7c3">

**Comment by heni02** [comment]
#19642再次验证是否必现

**Comment by heni02** [comment]
#19642 重跑还是报错
<img width="1438" alt="企业微信截图_1e8b95d5-f37f-4198-8358-98f976495f92" src="https://github.com/user-attachments/assets/21ae34fd-a1f9-4c6d-b5b5-d125c72a09fb">
job:https://github.com/matrixorigin/mo-auto-test/actions/runs/11571159562/job/32210610539

**Comment by heni02** [comment]
#19634 再次跑5分钟没有报错
job:https://github.com/matrixorigin/mo-auto-test/actions/runs/11570827680/job/32211818576
<img width="1507" alt="企业微信截图_69bca3e3-4fb2-4b79-ab36-d9fbb0d35bd3" src="https://github.com/user-attachments/assets/b99157e2-acc3-4705-8b1f-c20106b35f4c">

**Comment by aressu1985** [comment]
log link:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gAD%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-search-nightly-fc4b674b2-20241029%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730191442109%22,%22to%22:%221730208182279%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by heni02** [comment]
sysbench update 也报panic error
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11577127333/job/32248633711
<img width="1480" alt="企业微信截图_24f89674-6795-4332-b272-ebd01114ab14" src="https://github.com/user-attachments/assets/d49089eb-e126-42fa-995e-e4f6130bd834">
	
{"level":"ERROR","time":"2024/10/29 23:25:21.104637 +0000","caller":"pipeline/pipeline.go:83","msg":"error: internal error: panic runtime error: index out of range [2] with length 2: \nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:115\ngithub.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetBytesAt\n\t/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/vector.go:284\ngithub.com/matrixorigin/matrixone/pkg/common/hashmap.fillStringGroupStr\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/hashmap/strhashmap.go:152\ngithub.com/matrixorigin/matrixone/pkg/common/hashmap.(*strHashmapIterator).encodeHashKeys\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/hashmap/strhashmap.go:93\ngithub.com/matrixorigin/matrixone/pkg/common/hashmap.(*strHashmapIterator).Insert\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/hashmap/iterator.go:58\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/hashmap_util.(*HashmapBuilder).BuildHashmap\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/hashmap_util/hashmap_util.go:282\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild.(*container).build\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild/build.go:136\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild.(*HashBuild).Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild/build.go:66\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:165\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:443\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:320\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:281\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1\n\t/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700","span":{"trace_id":"1a34fd6a-db89-f207-8e28-106df465bdcf","span_id":"d15df56dc60080e5"}}

mo log：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22gAD%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-c47d6c522-20241029%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730244176006%22,%22to%22:%221730245308410%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by m-schen** [comment]
可以先拿2.0分支测，main分支的ci还在跑。

**Comment by aressu1985** [comment]
fixed
