### ISSUE TITLE
[Feature Request]: Mathematical Built-in function cos()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1967]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Follow the syntax and behavior of mysql 8.0 

[COS(X)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_cos)

Returns the cosine of X, where X is given in radians.

mysql> SELECT COS(PI());
        -> -1
Returns the sine of X, where X is given in radians.

The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math cos() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by yclchuxue** [comment]
I want to do it

**Comment by dengn** [comment]
> I want to do it

Sure, Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by yclchuxue** [comment]
Ok, I've already done this.

**Comment by dengn** [comment]
> Ok, I've already done this.

Issue assigned. Good luck

**Comment by dengn** [comment]
Feature Implemented.
