### ISSUE TITLE
[Bug]: performance of primary key point select decreased to 0

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

跑zywl的主键点查case，tps从十万多下降到0
revert  ae770919b77355b89a94b2844cd15bc6e5a07ab8之后恢复

日志里有很多{"level":"WARN","time":"2024/10/30 09:41:09.642396 +0800","caller":"engine_util/expr_util.go:166","msg":"const folded val expr is not a fold expr: \nExpr_F(\n\tFunc[\"cast\"](nargs=2)\n\tExpr_P(12)\tExpr_Selectivity(0)\n\tExpr_Fold(id=4)\tExpr_Selectivity(0)\n)Expr_Selectivity(0)\n"}
告警，这些告警说明下推到存储的filter没有正确折叠

### Steps to Reproduce

```Markdown
跑zywl的主键点查case
```

**Comment by zengyan1** [comment]
fixed
