### ISSUE TITLE
[Feature Request]: Mathematical Built-in function tan()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1968]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Follow the syntax and behavior of mysql 8.0 

[TAN(X)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_tan)

Returns the tangent of X, where X is given in radians.

mysql> SELECT TAN(PI());
        -> -1.2246063538224e-16
mysql> SELECT TAN(PI()+1);
        -> 1.5574077246549

The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math tan() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by bxiiiiii** [comment]
I could do this.

**Comment by dengn** [comment]
> I could do this.

Issue assigned. Good luck！

**Comment by dengn** [comment]
Feature Implemented.
