### ISSUE TITLE
[Feature Request]: Mathematical Built-in function cot()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1969]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

The cotangent function.

Follow the syntax and behavior of mysql 8.0 

MySQL doesn't have cot() function, but you could implement it by cos()/sin() or 1-tan().

The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math tan() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by ZtXavier** [comment]
我可以做这个任务吗

**Comment by dengn** [comment]
> 我可以做这个任务吗

Sure. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by ZtXavier** [comment]
> > 我可以做这个任务吗
> 
> 当然。分配前请先报名参加活动：[https ://www.wjx.top/vm/Ys1rz1I.aspx](https://www.wjx.top/vm/Ys1rz1I.aspx)

我已经报名

**Comment by ZtXavier** [comment]
我已经完成

**Comment by dengn** [comment]
Feature implemented.
