### ISSUE TITLE
[Feature Request]: Mathematical Built-in function acos()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1971]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Follow the syntax and behavior of mysql 8.0 

[ACOS(X)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_acos)

Returns the arc cosine of X, that is, the value whose cosine is X. Returns NULL if X is not in the range -1 to 1.

```
mysql> SELECT ACOS(1);
        -> 0
mysql> SELECT ACOS(1.0001);
        -> NULL
mysql> SELECT ACOS(0);
        -> 1.5707963267949
```
The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math acos() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by JasonPeng1310** [comment]
I want to try to solve this problem

**Comment by dengn** [comment]
> I want to try to solve this problem

Sure, Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by dengn** [comment]
Feature implemented.
