### ISSUE TITLE
[Bug]: restore account from snapshot panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19713]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

400020c4212eb9e5f874e4d8a0254d0551a7b53c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32285900800**
(sys restore sys-> execute restore)

Error: Error 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
2024/10/30 21:17:08.39[63](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32286848147#step:23:64)55 +0000 ERROR snapshot/restore_snapshot.go:148 restore snapshot failed: Error 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:900
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.MoBatchToString
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common/print.go:270
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.checkTxnLastInsertRow
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:436
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).filterInMemUnCommittedInserts
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:519
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).iterateInMemData
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:360
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).Next
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:293
github.com/matrixorigin/matrixone/pkg/vm/engine/engine_util.(*reader).Read
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/engine_util/reader.go:409
github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan.(*TableScan).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan/table_scan.go:122
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/filter.(*Filter).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/filter/filter.go:72
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:68
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:55
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunWithReader
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:59
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:197
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:443
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:320
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:366
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:283
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/usr/local/go/src/runtime/asm_amd[64](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32286848147#step:23:65).s:1700
2024/10/30 21:17:08.396406 +0000 ERROR snapshot/restore_snapshot.go:97 restore snapshot failed: Error 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:900
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.MoBatchToString
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common/print.go:270
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.checkTxnLastInsertRow
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:436
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).filterInMemUnCommittedInserts
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:519
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).iterateInMemData
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:360
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).Next
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:293
github.com/matrixorigin/matrixone/pkg/vm/engine/engine_util.(*reader).Read
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/engine_util/reader.go:409
github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan.(*TableScan).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan/table_scan.go:122
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/filter.(*Filter).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/filter/filter.go:72
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:68
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:55
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunWithReader
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:59
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:197
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:443
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:320
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:3[66](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32286848147#step:23:67)
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:283
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:[67](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32286848147#step:23:68)
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
2024/10/30 21:17:08.396430 +0000 DEBUG snapshot/restore_snapshot.go:35 restore snapshot failed
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:900
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.MoBatchToString
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common/print.go:270
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.checkTxnLastInsertRow
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:436
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).filterInMemUnCommittedInserts
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:519
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).iterateInMemData
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:360
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*LocalDisttaeDataSource).Next
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/local_disttae_datasource.go:293
github.com/matrixorigin/matrixone/pkg/vm/engine/engine_util.(*reader).Read
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/engine_util/reader.go:409
github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan.(*TableScan).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/table_scan/table_scan.go:122
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/filter.(*Filter).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/filter/filter.go:72
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:[68](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32286848147#step:23:69)
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/connector/connector.go:55
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunWithReader
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:59
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:197
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:443
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:320
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:366
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:283
github.com/panjf2000/ants/v2.(*goWorker).run.func1
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1[70](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11595975090/job/32286848147#step:23:71)0

**log:** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22li2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-nightly-400020c-20241030%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730323028000%22,%22to%22:%221730323200000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger snapshot workflow.

数据量：1.2 T
```

**Comment by aptend** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/19736

**Comment by Ariznawlll** [comment]
fixed
