### ISSUE TITLE
[Feature Request]: Mathematical Built-in function atan()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1973]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Follow the syntax and behavior of mysql 8.0 

[ATAN(X)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_atan)

Returns the arc tangent of X, that is, the value whose tangent is X.

```
mysql> SELECT ATAN(2);
        -> 1.1071487177941
mysql> SELECT ATAN(-2);
        -> -1.1071487177941
```
The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math atan() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by whileskies** [comment]
I'd like to work on this issue

**Comment by dengn** [comment]
> I'd like to work on this issue

Issue assigned, good luck!

**Comment by dengn** [comment]
Implemented.
