### ISSUE TITLE
[Feature Request]: Datetime Built-in function date() 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1974]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0   
2. Function syntax
[DATE(expr)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date)

Extracts the date part of the date or datetime expression expr.

mysql> SELECT DATE('2003-12-31 01:02:03');
        -> '2003-12-31'

3. The function should take date or datetime type as input, and return date type.

### Describe implementation you've considered

We have already a `ToDate()` implementation in datetime datatype. 

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by CoderfishGzh** [comment]
Can I have this issue assigned to me?

**Comment by dengn** [comment]
> Can I have this issue assigned to me?

@CoderfishGzh Sure, please sign up for the event first. Please add the MatrixOne community assistant "MatrixOrigin001" as a WeChat friend and follow the sign up instructions.

**Comment by dengn** [comment]
> Can I have this issue assigned to me?

@CoderfishGzh Hi, please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx The questionnaire problem was fixed.

**Comment by Charlie17Li** [comment]
Umm, has this task been done ? if not, I'd like to try.  /assign

**Comment by dengn** [comment]
Feature implemented.
