### ISSUE TITLE
[Bug]: [1103 main tke regression] tpcc 100-1000 report 'w-w conflict'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19753]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7d5f3b3c7f06280e1e69267f449e4e62b9283aa7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11643525248/job/32426482413**

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/8c7e3236-5faf-4eb7-8ecd-8844ae4ce789">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%2257a%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-7d5f3b3c7-20241102%5C%22%7D%20%7C%3D%20%60w-w%20conflict%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730571464000%22,%22to%22:%221730573264000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke regression workflow
```

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
tpcc测试panic的修复还没进main，等进了观察一下

**Comment by Ariznawlll** [comment]
fixed
