### ISSUE TITLE
[Bug]:  [1103 main tke regression] tpcc 100-1000 report 'invalid state txn not found'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19754]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7d5f3b3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11643525248/job/32426482413**

<img width="1397" alt="image" src="https://github.com/user-attachments/assets/b7ea9770-6760-4027-ae46-27d6d8ded819">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%2257a%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-7d5f3b3c7-20241102%5C%22%7D%20%7C%3D%20%60invalid%20state%20txn%20not%20found%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730571464000%22,%22to%22:%221730573444000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke regression workflow
```

**Comment by zhangxu19830126** [comment]
#19750  的孤儿事务引起的。因为孤儿事务被提前结束了，所有会有找不到事务的错误发生。重复issue

**Comment by zhangxu19830126** [comment]
dup with #19750 。本质是一个问题
