### ISSUE TITLE
[Feature Request]: Datetime Built-in function utc_time()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1975]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Function syntax

UTC_TIME()

Returns the current UTC time as a value in 'hh:mm:ss'  format.

```sql
mysql> SELECT UTC_TIME();
        -> '18:07:53'
```
### Describe implementation you've considered

Hint: we have already some useful functions implemented at for [date](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/date.go) and [datetime](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/datetime.go) type. 

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by noneback** [comment]
Plz assign it to me.

**Comment by noneback** [comment]
Do we need to introduce a new type of Time like [Time in MySQL](https://dev.mysql.com/doc/refman/8.0/en/time.html)?

**Comment by noneback** [comment]
Any response?

**Comment by dengn** [comment]
> Do we need to introduce a new type of Time like [Time in MySQL](https://dev.mysql.com/doc/refman/8.0/en/time.html)? @m-schen

Yes, MatrixOne needs to have a Time type. If you are interested at implementing this feature, you can do some investigations with the syntax behaviors of MySQL Time type and make a [RFC](https://github.com/matrixorigin/matrixone/blob/main/docs/rfcs/00000000-template.md), after RFC is discussed in the community, you can implement it.

**Comment by noneback** [comment]
I am interested in that feature, but I don't consider it an easy task that I can finish during this camp. Cuz I am quite busy recently.
Maybe I can give it a shot at convenience or you can just assign it to others.

**Comment by noneback** [comment]
> > I am interested in that feature, but I don't consider it an easy task that I can finish during this camp. Cuz I am quite busy recently. Maybe I can give it a shot at convenience or you can just assign it to others.
> 
> Yes, you are right. this is not an easy task so we didn't make it as a good-first-issue. We may launch a discussion about it and you can join if you like.

Then, we may pause this built-in function development until `Time` is implemented.

**Comment by dengn** [comment]
> > For this camp task, you can just process it as String type.
> 
> I don't like to process it as string type. It is a little bit waste of time. I will unassign myself. Good luck.

Fair enough. We will close this issue for this camp.
