### ISSUE TITLE
[Bug]: Error reported join query: panic runtime error: index out of range [0] with length 0:

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#19756]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,2.0-dev

### Commit ID

7d5f3b3c7f06280e1e69267f449e4e62b9283aa7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from mo_catalog.mo_indexes where name = 'idx1' and table_id = (select rel_id from mo_catalog.mo_tables where relname = 'tx');
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:115
github.com/matrixorigin/matrixone/pkg/sql/colexec/loopjoin.(*LoopJoin).Call
	/home/yiming/workspace/performance/matrixone/pkg/sql/colexec/loopjoin/join.go:124
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
	/home/yiming/workspace/performance/matrixone/pkg/vm/types.go:498
github.com/matrixorigin/matrixone/pkg/sql/colexec/filter.(*Filter).Call
	/home/yiming/workspace

### Expected Behavior

mysql> select * from mo_catalog.mo_indexes where name = 'idx1' and table_id = (select rel_id from mo_catalog.mo_tables where relname = 'tx');
Empty set (0.01 sec)

### Steps to Reproduce

```Markdown
create database db1;
use db1;
select * from mo_catalog.mo_indexes where name = 'idx1' and table_id = (select rel_id from mo_catalog.mo_tables where relname = 't1');
-- 注意：不要创建表t1
```

**Comment by qingxinhome** [comment]
![image](https://github.com/user-attachments/assets/13d0d487-42b9-4645-beba-475a9fa8d91f)

**Comment by zengyan1** [comment]
还没看

**Comment by zengyan1** [comment]
fixed
