### ISSUE TITLE
[Bug]:  perf of point_select decrease more than 40% on daily regression TKE

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#19752]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

a597e9bc3c6f695917f647d043e58c075d0557be

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11630838813/job/32408242438

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/8d1432bb-3b09-499e-a0ce-2719f20d3441">

after bin searching , this was caused by commit: 
a597e9bc3c6f695917f647d043e58c075d0557be

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/57fd62ec-4091-4c3c-af37-c141f4e31079">

### Steps to Reproduce

```Markdown
run sysbench point select test
```

**Comment by qingxinhome** [comment]
我基于issue中提到的二分锁定的pr：https://github.com/matrixorigin/matrixone/pull/19654, 做了前后对比测试

一、我提交的pr(#19654)对应的commit：a597e9bc3c6f695917f647d043e58c075d0557be
对其进行TKE sysbench 10W Point Select Test 测试， 测试连接：
https://github.com/matrixorigin/mo-auto-test/actions/runs/11700556544/job/32585538911
测试结果如下: 

SQL statistics:
    queries performed:
        read:                            22197285
        write:                           0
        other:                           0
        total:                           22197285
    transactions:                        22197285 (73970.45 per sec.)
    queries:                             22197285 (73970.45 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          300.0828s
    total number of events:              22197285

Latency (ms):
         min:                                    0.46
         avg:                                    1.35
         max:                                 1104.22
         95th percentile:                        1.96
         sum:                             29992175.19

Threads fairness:
    events (avg/stddev):           221972.8500/29625.31
    execution time (avg/stddev):   299.9218/0.02


二、并基于目标pr的前面的commit：fb3d7e29295abf8be10ee2efbb0d7b4eebff15db
对其进行TKE sysbench 10W Point Select Test 测试，  测试连接：
https://github.com/matrixorigin/mo-auto-test/actions/runs/11701544491/job/32588653898
测试结果如下: 
 SQL statistics:
    queries performed:
        read:                            22334494
        write:                           0
        other:                           0
        total:                           22334494
    transactions:                        22334494 (74445.64 per sec.)
    queries:                             22334494 (74445.64 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          300.0104s
    total number of events:              22334494

Latency (ms):
         min:                                    0.49
         avg:                                    1.34
         max:                                 1225.68
         95th percentile:                        2.52
         sum:                             29989211.76

Threads fairness:
    events (avg/stddev):           223344.9400/52860.48
    execution time (avg/stddev):   299.8921/0.03
经过对比，transactions变化比值为0.63%， 并没有出现大的性能波动， @aressu1985 @heni @sukki37

**Comment by aressu1985** [comment]
fixed
