### ISSUE TITLE
[Bug]: [1102 main tke regression] tpcc 500-1000 report 'cannot commit a orphan transaction'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19750]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7faf76e882cbef0bc7e1365824428de4c6406ec7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11630838813/job/32398275649

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/58a11b2d-03ea-4dfe-b214-b9ea4a6fb11e">

tpcc 500-1000执行期间log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22uoa%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-7faf76e88-20241101%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730488184000%22,%22to%22:%221730490087000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger daily regression workflow
```

**Comment by sukki37** [comment]
https://grafana.ci.matrixorigin.cn/goto/IkioBCWNR?orgId=1 During the error period, the CPU usage of the CN is not high.

**Comment by zhangxu19830126** [comment]
https://grafana.ci.matrixorigin.cn/goto/yQwUm7GHg?orgId=1

大量的io timeout。几乎所有的组件都在i/o time

**Comment by zhangxu19830126** [comment]
goroutine的调度的延迟非常大，有100ms
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/3014dbfd-2e14-4450-be42-8003d79d87ba">

**Comment by zhangxu19830126** [comment]
goroutine 数量也很大
<img width="437" alt="image" src="https://github.com/user-attachments/assets/b2b963d7-7c26-4c45-8f8f-41713ad430d1">

**Comment by zhangxu19830126** [comment]
gc 占用cpu也很大
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/5adfd9e1-495d-47e5-8e90-9d3d2d575377">

**Comment by fengttt** [comment]
#19965 #19966 #199676

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/ci-test/actions/runs/11810386696/job/32903395595

**Comment by zhangxu19830126** [comment]
暂时无法解决，等田博士的那些issue被fix了再看看情况

**Comment by zhangxu19830126** [comment]
暂时无法解决，等田博士的那些 issue 被 fix 了再看看情况

**Comment by zhangxu19830126** [comment]
暂时无法解决，等田博士的那些 issue 被 fix 了再看看情况

**Comment by zhangxu19830126** [comment]
暂时无法解决，等田博士的那些 issue 被 fix 了再看看情况

**Comment by zhangxu19830126** [comment]
孤儿事务，暂时没法解决

**Comment by zhangxu19830126** [comment]
孤儿事务，暂时没法解决

**Comment by zhangxu19830126** [comment]
孤儿事务，暂时没法解决

**Comment by zhangxu19830126** [comment]
调整了孤儿事务的敏感度，增加了默认的超时时间，重新看看这个问题。

**Comment by Ariznawlll** [comment]
没再出现了
