### ISSUE TITLE
[Feature Request]: Datetime Built-in function utc_timestamp() 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1976]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Function syntax

UTC_TIMESTAMP()

Returns the current UTC date and time as a value in 'YYYY-MM-DD hh:mm:ss' format.

```sql
mysql> SELECT UTC_TIMESTAMP();
        -> '2003-08-14 18:08:04'
```
### Describe implementation you've considered

Hint: we have already some useful functions implemented at for [date](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/date.go) and [datetime](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/datetime.go) type. 

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by noneback** [comment]
Could you plz assign it to me? I am interested in db but have few experience. Hope get the chance to take part in matrix community.

**Comment by dengn** [comment]
> Could you plz assign it to me? I am interested in db but have few experience. Hope get the chance to take part in matrixorigin community.

Sure. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by noneback** [comment]
> 

Thx.  I have already signed up for it :)

**Comment by noneback** [comment]
> > Could you plz assign it to me? I am interested in db but have few experience. Hope get the chance to take part in matrixorigin community.
> 
> Sure. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

Thx. I have already signed up for it :)

**Comment by dengn** [comment]
> > > Could you plz assign it to me? I am interested in db but have few experience. Hope get the chance to take part in matrixorigin community.
> > 
> > 
> > Sure. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx
> 
> Thx. I have already signed up for it :)

Issue assigned.

**Comment by noneback** [comment]
Thx

**Comment by noneback** [comment]
I have finished Issue #2024

**Comment by dengn** [comment]
Feature implemented.
