### ISSUE TITLE
[Tech Request]: add projection support for some operators

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#19769]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
之前曾言有给部分算子增加了Projection的支持，但是存在一些问题又去掉了。
可以继续补回来。
1、应该绝大部分算子都可以有projection
2、以前的处理感觉可以优化：
    1. compile的地方，应该没必要那么多if。可能直接在CompilePrjection增加上一个算子的引用，然后统一处理即可
    2. 调用的地方，不知道是否参考 ChildrenCall 再封装一个 输出的函数，让所有的输出都用那一个函数。因为后面可能还会再增加filter
```

### Why is this needed ?

缩短pipeline的长度，减少算子间的调用链，提升性能

**Comment by aressu1985** [comment]
可以在2.0.1完成，只需要跑BVT和REGRESSION测试即可，对用户行为和性能均没有什么影响
