### ISSUE TITLE
[Bug]: [1104 main tke regression] tpcc 500-1000 report lots of 'Communications link failure'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19762]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

7d5f3b3c7f06280e1e69267f449e4e62b9283aa7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11652323735/job/32447954186

在报错Communication link failure之前，有cannot commit a orphan transaction报错，不确定两者是否存在影响，需定位
<img width="1842" alt="image" src="https://github.com/user-attachments/assets/57898ebb-dac6-40f4-a94d-db66d0344755">

在上面报错之后，执行load data测试以及sysbench测试，均卡住
<img width="1866" alt="image" src="https://github.com/user-attachments/assets/a48abc26-ae6c-454a-a1ab-a44cc19a25db">

TPCC 500-1000测试期间日志（UTC时间）：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22o3e%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-7d5f3b3c7-20241103%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730662892000%22,%22to%22:%221730665151000%22%7D%7D%7D&schemaVersion=1&orgId=1

goroutine：
[CN_61623035-3433-3539-3066-303062396161_leakcheck_routine_0192f3b8-dccb-7ef2-b7e0-1357056eb661.gz](https://github.com/user-attachments/files/17613486/CN_61623035-3433-3539-3066-303062396161_leakcheck_routine_0192f3b8-dccb-7ef2-b7e0-1357056eb661.gz)

<img width="1230" alt="WeChatWorkScreenshot_7a29bd71-5102-4be6-9c79-47e3bb44719b" src="https://github.com/user-attachments/assets/12197712-3e62-4193-b241-29f274e2dee3">

### Steps to Reproduce

```Markdown
trigger tke daily regression test
```

**Comment by sukki37** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22o3e%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-7d5f3b3c7-20241103%5C%22%7D%20%7C~%20%60long%20running%7Cpanic%7Cfound%20leak%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730662892000%22,%22to%22:%221730668751000%22%7D%7D%7D&schemaVersion=1&orgId=1

```
2024/11/03 20:30:31.628259 +0000 ERROR cn-service found long running txn {"uuid": "", "txn-id": "49232f5b9d2bfca118047df12d526633", "create-at": "2024/11/03 20:07:06.045294 +0000", "options": "Features:1 CN:\"61623035-3433-3539-3066-303062396161\" SessionID:\"0192f38b-eff0-713e-9fca-41e598388867\" ConnectionID:16503 UserName:\"dump\" counter:\"commit: enter:0, exit:0 rollback: enter:0, exit:0 runSql: enter:3, exit:2 incrStmt: enter:4, exit:4 rollbackStmt: enter:1, exit:1 footPrints: [0: enter:2, exit:2] [1: enter:2, exit:2] [2: enter:2, exit:2] [4: enter:2, exit:2] [6: enter:3, exit:2] [7: enter:3, exit:2] [8: enter:3, exit:2] [11: enter:2, exit:2] [12: enter:2, exit:2] [13: enter:3, exit:2] [14: enter:2, exit:2] [15: enter:3, exit:2] [16: enter:3, exit:2] [85: enter:2, exit:2] [86: enter:2, exit:2] [87: enter:2, exit:2] [99: enter:1, exit:1] [101: enter:1, exit:1] [102: enter:1, exit:1] [107: enter:1, exit:1] [110: enter:1, exit:1] \" sessionInfo:\"connectionId 16503|10.143.19.42:58718|account sys:dump|goRoutineId 2788509|migrate-goRoutineId 0|0192f38b-eff0-713e-9fca-41e598388867\" inRunSql:true ", "profile": "ETL:/profile/CN_61623035-3433-3539-3066-303062396161_leakcheck_routine_0192f3b8-dccb-7ef2-b7e0-1357056eb661.gz"}
```

goroutine 3098354 [select, 23 minutes]:
github.com/matrixorigin/matrixone/pkg/vm/process.(*PipelineSignalReceiver).listenToSingleEntry(0xc520301ce0)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/process/process_spoolr.go:262 +0xbd
github.com/matrixorigin/matrixone/pkg/vm/process.(*PipelineSignalReceiver).listenToAll(0x50?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/process/process_spoolr.go:219 +0x65
github.com/matrixorigin/matrixone/pkg/vm/process.(*PipelineSignalReceiver).GetNextBatch(0xc520301ce0, {0x57f21e0, 0xc05b289130})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/process/process_spoolr.go:164 +0x165
github.com/matrixorigin/matrixone/pkg/sql/colexec/merge.(*Merge).Call(0xc2f5c169a0, 0xc3fa0096c0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/merge/merge.go:62 +0xed
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x57a91d8, 0xc2f5c169a0}, 0xc41ccf7e40, {0x57f21e0, 0xc05b289180})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.(*Projection).Call(0xc2b43e1ea0, 0xc41ccf7e40)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/projection/projection.go:68 +0xef
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x57a8f00, 0xc2b43e1ea0}, 0xc41ccf7e40, {0x57f21e0, 0xc05b2891d0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/types.go:498 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Deletion).normalDelete(0xc3146b8870, 0xc41ccf7e40)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion/deletion.go:229 +0xef
github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion.(*Deletion).Call(0xc3146b8870, 0xc41ccf7e40)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/deletion/deletion.go:102 +0x55
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc093673c38, 0xc41ccf7e40)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:71 +0xfe
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc27799a0f0, 0xc2d5a916c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:165 +0x4ff
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc27799a0f0, 0xc2d5a916c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:443 +0x129
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc27799a0f0, 0xc2d5a916c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:320 +0x3f2
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc2d5a916c0, 0xc27799a0f0)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:331 +0x265
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func2()
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:497 +0x59
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 2790315
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:48 +0x5c

**Comment by zhangxu19830126** [comment]
fixed by #19772

**Comment by Ariznawlll** [comment]
Last night's test reported a panic error, after the repair, I will observe again

**Comment by Ariznawlll** [comment]
Last night's test reported a panic error, after the repair, I will observe again

**Comment by Ariznawlll** [comment]
fixed
