### ISSUE TITLE
[Bug]: tpcc 10000-10000 test report 'internal error: panic runtime error: invalid memory address or nil pointer dereference'. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19764]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

48c7e1698023b4321434bed194887e796213d836

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11652534431/job/32444130010

2024-11-03 20:00:47 FATAL jTPCCTerminal:328 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:900
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3170
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:287
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:515
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:483
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:212
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:208
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
2024-11-03 20:00:47 FATAL jTPCCTerminal:328 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:900
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3170
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:287
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:515
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:483
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:212
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:208
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
2024-11-03 20:00:47 FATAL jTPCCTerminal:214 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22o3e%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-ben-nightly-48c7e1698-20241103%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730663994000%22,%22to%22:%221730665151000%22%7D%7D%7D&schemaVersion=1&orgId=1

测试配置：
[<img width="1839" alt="image" src="https://github.com/user-attachments/assets/84c2c3ce-a4ba-47fc-97ee-6af6328f8a37">](https://github.com/matrixorigin/mo-nightly-regression/blob/main/mo-bench-tke.yaml)

### Steps to Reproduce

```Markdown
trigger workflow on tke.
```

**Comment by daviszhen** [comment]
fixed

**Comment by Ariznawlll** [comment]
panic问题没出现了
