### ISSUE TITLE
[Bug]: UT TestAppendAndGC failed

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#19786]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

c64026ac2962f074ec5ec454df57d584431d7c81

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[error.log](https://github.com/user-attachments/files/17625833/error.log)

https://github.com/matrixorigin/matrixone/actions/runs/11665808296/job/32479352639?pr=19751

### Expected Behavior

no failure

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11665808296/job/32479352639?pr=19751
```

**Comment by LeftHandCold** [comment]
fixed

**Comment by reusee** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11830112561/job/32963097462?pr=20068

**Comment by LeftHandCold** [comment]
fixed
