### ISSUE TITLE
[Bug]: [1105 main tke regression] sysbench1000w update-index test report 'r-w conflict'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19800]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5e4d0638a989e06c8bf207ba89d359fef4650795

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11666410553/job/32513551867

<img width="1829" alt="image" src="https://github.com/user-attachments/assets/cfd539e6-89ec-4e75-93f3-a43845020670">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%221u3%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-5e4d0638a-20241104%5C%22%7D%20%7C%3D%20%60r-w%20conflict%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730779855000%22,%22to%22:%221730780155000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke workflow
```

**Comment by jensenojs** [comment]
辛苦鹏哥帮看一下分给谁帮忙看一下, @XuPeng-SH

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
fixed
