### ISSUE TITLE
[Feature Request]: Datetime Built-in function dayofyear()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1980]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[DAYOFYEAR(date)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_dayofyear)

Returns the day of the year for date, in the range 1 to 366.
``` sql
mysql> SELECT DAYOFYEAR('2007-02-03');
        -> 34
```
The function should take date or datetime type as input, and return uint16 type.

### Describe implementation you've considered

Hint: we have already some useful functions implemented at for [date](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/date.go) and [datetime](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/datetime.go) type.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by noneback** [comment]
Assign it to me, plz.

**Comment by noneback** [comment]
I have finished this issue in #2051

**Comment by dengn** [comment]
Feature implemented.
