### ISSUE TITLE
[Bug]: UT TestBackupData2 failed in pr

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#19808]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TestBackupData2 failed
[ut-error.log](https://github.com/user-attachments/files/17630523/ut-error.log)

### Expected Behavior

TestBackupData2 success

### Steps to Reproduce

```Markdown
run pr in ci
```

**Comment by badboynt1** [comment]
repro in https://github.com/matrixorigin/matrixone/actions/runs/11697594458/job/32576592763?pr=19815

**Comment by reusee** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11680641691/job/32573966043?pr=19766

**Comment by sukki37** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/11698591186/job/32579131079?pr=19818

**Comment by ouyuanning** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/11718935022/job/32641220344?pr=19833

**Comment by guguducken** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11719016377/job/32641427965?pr=19857

**Comment by qingxinhome** [comment]
repro:https://github.com/matrixorigin/matrixone/actions/runs/11801039820/job/32873410574?pr=19909

**Comment by LeftHandCold** [comment]
fixed
