### ISSUE TITLE
[Bug]:  decimal case failed in the ARM BVT test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19811]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Branch Name

main

### Commit ID

8ad7a04

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/11679207975/job/32519914392

[mo-service.log.zip](https://github.com/user-attachments/files/17630690/mo-service.log.zip)

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/a9c7c0f4-6e55-49ba-bfa0-58767e4abba2">

### Steps to Reproduce

```Markdown
run bvt on mac(arm)
```

**Comment by Ariznawlll** [comment]
128机器：amd64

https://github.com/matrixorigin/matrixone/issues/19811

**Comment by zengyan1** [comment]
fixed
https://github.com/matrixorigin/matrixone/actions/runs/11721510331/job/32649078890

**Comment by aressu1985** [comment]
fixed
