### ISSUE TITLE
[Bug]: [1107 standalone regression test] bvt 'select cast(s1 as decimal(7, 2))' failed.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19847]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

173985a3818334e4c36c644f1b7e959838c9293f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11705565122/job/32600845593**

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/36f034d1-976f-453e-8eb7-39a39a4757a3">

**log**: https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-173985a3-20241106-222854.log%5C%22%7D%20%7C%3D%20%60select%20cast%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730904850000%22,%22to%22:%221730904971000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger 128 regression workflow
```

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/issues/19811

**Comment by zengyan1** [comment]
等待 https://github.com/matrixorigin/matrixone/pull/19812 合入

**Comment by zengyan1** [comment]
fixed
https://github.com/matrixorigin/matrixone/actions/runs/11721510331/job/32649078890

**Comment by Ariznawlll** [comment]
fixed
