### ISSUE TITLE
[Feature Request]: String function lpad()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1984]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[LPAD(str,len,padstr)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_lpad)

Returns the string str, left-padded with the string padstr to a length of len characters. If str is longer than len, the return value is shortened to len characters.

```sql
mysql> SELECT LPAD('hi',4,'??');
        -> '??hi'
mysql> SELECT LPAD('hi',1,'??');
        -> 'h'
```
### Describe implementation you've considered

An easy implementation could be using the official Golang function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by JackTan25** [comment]
This issue is for me now!!! hahahh!!
I'v got the permsiison from MatrixOrigin001

**Comment by dengn** [comment]
> 

Issue assigned. Good luck！

**Comment by dengn** [comment]
Feature implemented.
