### ISSUE TITLE
[Feature Request]: String function ltrim()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1985]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[LTRIM(str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ltrim)

Returns the string str with leading space characters removed.
```sql
mysql> SELECT LTRIM('  barbar');
        -> 'barbar'
```
### Describe implementation you've considered

An easy implementation could be using the official Golang function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by jiajunhuang** [comment]
Assign it to me, please :)

**Comment by dengn** [comment]
> 

Issue assigned Good luck！

**Comment by dengn** [comment]
Feature implemented.
