### ISSUE TITLE
[Bug]: ut test failed in Test_transfer

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#19858]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

==================
WARNING: DATA RACE
Write at 0x00c0032fb741 by goroutine 1657:
  github.com/matrixorigin/matrixone/pkg/proxy.Test_transfer()
      /home/runner/work/matrixone/matrixone/pkg/proxy/tunnel_test.go:823 +0x8b2
  testing.tRunner()
      /opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.23.0/x64/src/testing/testing.go:1743 +0x44

Previous write at 0x00c0032fb741 by goroutine 16[59](https://github.com/matrixorigin/matrixone/actions/runs/11718754035/job/32640653575?pr=19855#step:9:60):
  github.com/matrixorigin/matrixone/pkg/proxy.(*pipe).kickoff.func2()
      /home/runner/work/matrixone/matrixone/pkg/proxy/tunnel.go:591 +0xcf
  runtime.deferreturn()
      /opt/hostedtoolcache/go/1.23.0/x64/src/runtime/panic.go:[60](https://github.com/matrixorigin/matrixone/actions/runs/11718754035/job/32640653575?pr=19855#step:9:61)5 +0x5d
  github.com/matrixorigin/matrixone/pkg/proxy.(*tunnel).kickoff.func2()
      /home/runner/work/matrixone/matrixone/pkg/proxy/tunnel.go:265 +0x64

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/11718754035/job/32640653575?pr=19855
```

**Comment by volgariver6** [comment]
fixed
