### ISSUE TITLE
[Bug]: [1107 restore resgression] sys restore nonsys to newnonsys from pitr oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19860]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f0ee4d3eb611383de00b7ba452db1e9e3042cbe8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11717471728/job/32637656217
<img width="1856" alt="image" src="https://github.com/user-attachments/assets/37750030-7beb-43c8-98e3-b747762a7b5c">

<img width="1872" alt="image" src="https://github.com/user-attachments/assets/ef66f8f4-638f-4de1-a14b-85bbe0045c8f">

restore失败期间的日志:（UTC时间）https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22Nkc%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-f0ee4d3-20241107%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221730965800000%22,%22to%22:%221730966700000%22%7D%7D%7D&schemaVersion=1&orgId=1

heap profile: 
[restore1107.zip](https://github.com/user-attachments/files/17658727/restore1107.zip)

memory使用情况：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cMK%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-f0ee4d3-20241107%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221730965800000%22,%22to%22:%221730966700000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger restore workflow on tke.

上一个好的commit：173985a3818334e4c36c644f1b7e959838c9293f
```

**Comment by YANGGMM** [comment]
原因是在restore的时候oom了，然后工具会去执行drop account然后报invalid connection

**Comment by daviszhen** [comment]
profile

![image](https://github.com/user-attachments/assets/c9e9f0f7-8071-491c-b4d6-51212f1a4db3)


与 监控的profile结果不同

![image](https://github.com/user-attachments/assets/83c8b088-3ec0-4b75-be2b-cade68e13000)

https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22cMK%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-f0ee4d3-20241107%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221730965811503%22,%22to%22:%221730965821294%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
时间点上看16：05 oom.

![image](https://github.com/user-attachments/assets/3079c8f5-1860-40c7-a211-bd5baf56e7e4)

**Comment by daviszhen** [comment]
```
{"level":"INFO","time":"2024/11/07 08:05:28.103675 +0000","caller":"cnservice/server.go:980","msg":"get profile done. save profiles ","path":"ETL:/profile/CN_61363837-3533-6432-3330-633137613330_heap_019305a8-2a83-7b32-b693-d11cd912d9de.gz"}

```

**Comment by daviszhen** [comment]
issue 里面的profile 文件时间点 不对。

```
{"level":"INFO","time":"2024/11/07 08:00:27.919990 +0000","caller":"cnservice/server.go:980","msg":"get profile done. save profiles ","path":"ETL:/profile/CN_32616530-3164-3337-3533-346530366663_heap_019305a3-9883-75f4-a7d8-bdf599ab9837.gz"}
```

**Comment by Ariznawlll** [comment]
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/899a23ba-9ec9-4eda-b85b-97ac6ed425a2">

出问题的commit范围

**Comment by Ariznawlll** [comment]
**二分出错的commit：0ec2b30666e8c4a428bf1acbc31f06b96ee5186d**

<img width="1281" alt="企业微信截图_d5d70b35-3b54-4b57-8791-74b60a0b6405" src="https://github.com/user-attachments/assets/518957e8-1b44-4225-b88d-7d152ac7b707">

@aunjgr 龙冉哥，帮忙看一下

**Comment by Ariznawlll** [comment]
**最新一次测试：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11735227009
commit：0ec2b30666e8c4a428bf1acbc31f06b96ee5186d**

<img width="1856" alt="image" src="https://github.com/user-attachments/assets/86c4a2be-1970-44bc-8914-d63f6af7ed60">

<img width="1887" alt="image" src="https://github.com/user-attachments/assets/a602a134-9f5a-47a7-b1bb-eee0022e0bbc">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22XDq%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-0ec2b30-20241108%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731050779000%22,%22to%22:%221731051799000%22%7D%7D%7D&schemaVersion=1&orgId=1

memory:https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22NPr%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-0ec2b30-20241108%5C%22,pod%3D%27nightly-regression-dis-tp-cn-fq2rr%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221731051720000%22,%22to%22:%221731051780000%22%7D%7D%7D&schemaVersion=1&orgId=1

**oom时间为UTC时间07:42:19.477797**
**heap profile:** 
(UTC时间： 2024-11-08 15:42:03) 
[CN_35376666-3839-3835-6233-653730616236_heap_01930ab9-1aa4-71d8-ad2e-3d52513bea49.gz](https://github.com/user-attachments/files/17675812/CN_35376666-3839-3835-6233-653730616236_heap_01930ab9-1aa4-71d8-ad2e-3d52513bea49.gz)
(UTC时间： 2024-11-08 15:42:33) 
[CN_35376666-3839-3835-6233-653730616236_heap_01930ab9-8fd3-7503-ad92-de5e52135511.gz](https://github.com/user-attachments/files/17675807/CN_35376666-3839-3835-6233-653730616236_heap_01930ab9-8fd3-7503-ad92-de5e52135511.gz)

**Comment by aunjgr** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11740811206

已经跑过

**Comment by Ariznawlll** [comment]
fixed

**Comment by Ariznawlll** [comment]
没有合入2.0-dev @aunjgr
