### ISSUE TITLE
[Bug]:  restore_pubsub failed occasionally during merge run

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19869]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main 

### Commit ID

9e9638f

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/31b66d21-5627-433c-b50c-634db20e0cd8">

job link: https://github.com/matrixorigin/matrixone/actions/runs/11722239135/job/32652430737
log link: https://grafana.ci.matrixorigin.cn/goto/i-S4OVMNR?orgId=1

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by YANGGMM** [comment]
<img width="942" alt="image" src="https://github.com/user-attachments/assets/6099c58b-0d9c-494f-aecc-b9af7ec1650a">

**Comment by YANGGMM** [comment]
same #19867

**Comment by YANGGMM** [comment]
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/dbc063df-3425-490d-92ae-c23fe37b6819">

**Comment by YANGGMM** [comment]
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/8a4f2ae8-92ae-4649-91fb-6f64f78a981b">

根据快照读获取 db的时候没有获取到test02

**Comment by daviszhen** [comment]
走给存储

**Comment by aressu1985** [comment]
dup with [19867](https://github.com/matrixorigin/matrixone/issues/19867) ，已经加完日志，等复现后定位

**Comment by triump2020** [comment]
基本定位了，pls ref to #19867

**Comment by triump2020** [comment]
@aressu1985   Pls close it .
