### ISSUE TITLE
[Bug]: [1108 2.0-dev standalone regression] sysbench 10w delete report 'Duplicate entry '01930896-820d-7cbd-b4ee-6d14b7d550dd-0-0-906' for key '__mo_%1_delete_rowid''.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#19876]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

0eaca27334aec77616a96be682fccc4845fe4ed4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11725001875/job/32660518008

**sysbench 10w delete 1000 thread:**
<img width="1783" alt="image" src="https://github.com/user-attachments/assets/a0bc2823-fb9e-45ae-91b5-1358395fde40">

log: https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-0eaca273-20241107-222946.log%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731015900000%22,%22to%22:%221731015910000%22%7D%7D%7D&schemaVersion=1&orgId=1

**sysbench 10wRead-Write 1000 thread：**
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/0d14dbac-57f4-44de-9696-2176fd005a22">

log： https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-0eaca273-20241107-222946.log%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731018048000%22,%22to%22:%221731018083000%22%7D%7D%7D&schemaVersion=1&orgId=1

**sysbench 10w write-only 100 thread：**

<img width="1871" alt="image" src="https://github.com/user-attachments/assets/10d80307-8738-4bda-b727-e1979bdf3afb">

log：https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-0eaca273-20241107-222946.log%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731018083000%22,%22to%22:%221731018093000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger 128 regression workflow.
```

**Comment by daviszhen** [comment]
不确定是tn内部，还是cn给tn的rowid重复。


![image](https://github.com/user-attachments/assets/fe1a450c-0b3a-4407-8293-fa16d7a1f576)


https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-0eaca273-20241107-222946.log%5C%22%7D%20%7C%3D%20%60Duplicate%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731015900000%22,%22to%22:%221731015910000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
报错的是delete语句。不确定duplicate key的原因。

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/blob/2.0-dev/pkg/sql/colexec/multi_update/s3writer.go#L552

**Comment by XuPeng-SH** [comment]
Triggered by bug #19890 
Root cause and should be fixed by #19868

**Comment by XuPeng-SH** [comment]
@aptend

**Comment by aressu1985** [comment]
大量写Timestone s3的的时候，会出发该问题，目前暂时没有很好的解决方案，且会影响性能，而且DN如果不做增量去重，会影响正确性，这个2.0.1版本一定要修复

**Comment by aressu1985** [comment]
经多方沟通，该问题DELAY到下个版本解决

**Comment by aptend** [comment]
自测中

**Comment by XuPeng-SH** [comment]
fixed

**Comment by Ariznawlll** [comment]
观察下

**Comment by Ariznawlll** [comment]
fixed
