### ISSUE TITLE
[Feature Request]: String function rtrim()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1987]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[RTRIM(str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_rtrim)

Returns the string str with trailing space characters removed.
```sql
mysql> SELECT RTRIM('barbar   ');
        -> 'barbar'
```
### Describe implementation you've considered

An easy implementation could be using the official Golang function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by jiajunhuang** [comment]
Assign it to me, too, please, as the `ltrim` funtion :)

**Comment by dengn** [comment]
> Assign it to me, too, please, as the `ltrim` funtion :)

Sure, Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by dengn** [comment]
> Assign it to me, too, please, as the `ltrim` funtion :)

issue assigned. Good luck！

**Comment by dengn** [comment]
Feature implemented.
