### ISSUE TITLE
[Feature Request]: String function repeat()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1988]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[REPEAT(str,count)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_repeat)

Returns a string consisting of the string str repeated count times.   
If count is less than 1, returns an empty string. Returns NULL if str or count are NULL.
```sql
mysql> SELECT REPEAT('MySQL', 3);
        -> 'MySQLMySQLMySQL'
```

### Describe implementation you've considered

An easy implementation could be using the official Golang function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by jiajunhuang** [comment]
Assign it to me, please

**Comment by lucky-sinx** [comment]
I'd like to work on this issue

**Comment by jiajunhuang** [comment]
@dengn assign it to @lucky-sinx please, I'm busy these days.

**Comment by fengttt** [comment]
Why repeat function is gone?

**Comment by m-schen** [comment]
我会找时间做掉这个，顺便作为一个demo。

**Comment by m-schen** [comment]
已完成，可验证。

repeat (s varchar, n int64)
重复n次s作为结果返回，如果s和n有任意一个参数值为null，则结果为null
当n < 0 以及 结果的长度过长（目前的阈值与lpad, rpad相同，MaxTgtLen = int64(16 * 1024 * 1024)）时，结果为null。

**Comment by Ariznawlll** [comment]
test done!

**Comment by lacrimosaprinz** [comment]
doc edited:
https://github.com/matrixorigin/matrixorigin.io.cn/pull/644
https://github.com/matrixorigin/matrixorigin.io/pull/489

**Comment by Ariznawlll** [comment]
test done!
