### ISSUE TITLE
[Bug]: sysbench delete commit many tombstone s3 objects with only 1 row

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#19890]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

58572878fe7702be25fa4ccaff75e2abcc161c59

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-0eaca273-20241107-222946.log%5C%22%7D%20%7C~%20%60Duplicate%7CCN-COMMIT-S3-Tombstone%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731015840000%22,%22to%22:%221731015910000%22%7D%7D%7D&schemaVersion=1&orgId=1

<img width="1619" alt="image" src="https://github.com/user-attachments/assets/91dae237-8345-4524-9c2d-4716751aba13">

<img width="975" alt="image" src="https://github.com/user-attachments/assets/30e100c1-551c-4a26-9aae-65105e063785">

### Steps to Reproduce

```Markdown
Run sysbench 10w delete case
```

**Comment by XuPeng-SH** [comment]
create databases sysbench_db
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_delete.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=30 --report-interval=10    prepare;
sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111   oltp_delete.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1000 --time=300 --report-interval=10    --range_selects=off --point_selects=1 run

**Comment by ouyuanning** [comment]
根本原因有2个
1、在准备测试数据之后，如果立刻执行delete，这个时候的统计信息会使用默认值，而这个默认值较大，会编译为走s3的路径
2、目前multi_update中，对于delete s3是不判断剩余数据量大小的，无论多大都会刷s3

目前1的部分跟倪涛讨论了下，比较难处理。暂时先处理了2
