### ISSUE TITLE
[Feature Request]: String function reverse()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1989]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax
[REVERSE(str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_reverse)

Returns the string str with the order of the characters reversed.
```sql
mysql> SELECT REVERSE('abc');
        -> 'cba'
```
### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by noneback** [comment]
plz assign it to me. I want to give it a shot.

**Comment by dengn** [comment]
> plz assign it to me. I want to give it a shot.

Issue assigned. Good luck！

**Comment by noneback** [comment]
I have finished this issue in #2037
