### ISSUE TITLE
[Feature Request]: String function space()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1990]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax
[SPACE(N)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_space)

Returns a string consisting of N space characters.
```sql
mysql> SELECT SPACE(6);
        -> '      '
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by jiajunhuang** [comment]
Assign it to me, please

**Comment by lucky-sinx** [comment]
I'd like to work on this issue

**Comment by dengn** [comment]
Feature implemented.
