### ISSUE TITLE
[Bug]: Cluster manual upgrade error

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#19907]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

a0d4a3b56

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="542" alt="企业微信截图_17310639881941" src="https://github.com/user-attachments/assets/947456ab-114a-44d7-90a0-53585e2b98e3">
<img width="318" alt="企业微信截图_17310640159094" src="https://github.com/user-attachments/assets/a5f05305-a088-414c-9c6c-985b78a69d85">

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
upgrade account all;
```

**Comment by qingxinhome** [comment]
https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22rT0%22:%7B%22datasource%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_namespace%3D%5C%22freetier-02%5C%22%7D%20%7C%3D%20%60failed%20to%20connect%20to%20cn%20to%20handle%20event%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
https://grafana.cn-dev.matrixone.tech/explore?panes=%7B%22rT0%22:%7B%22datasource%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_namespace%3D%5C%22freetier-02%5C%22%7D%20%7C%3D%20%60failed%20to%20connect%20to%20cn%20to%20handle%20event%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22cbb7c841-137c-4165-b7c9-61d57c8ff571%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731042000000%22,%22to%22:%221731067200000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by qingxinhome** [comment]
<img width="965" alt="企业微信截图_17313154802528" src="https://github.com/user-attachments/assets/5840551e-f704-4604-8e39-91d3c3c38013">

经过代码分析， update account all， 语句到达proxy后， proxy与CNService进行握手通信时报错， 但是此时 update account all尚未下发至CN， 刘博帮忙分析一下

**Comment by volgariver6** [comment]
```
{"level":"ERROR","time":"2024/11/08 11:10:01.862122 +0000","name":"proxy-service","caller":"proxy/client_conn.go:359","msg":"failed to connect to cn to handle event","service":"36666531-3235-3835-6530-353162663539","uuid":"36666531-3235-3835-6530-353162663539","ConnID":26218417,"query":"UPGRADE ACCOUNT ALL","error":"<\u0000\u0000\u0001\ufffd(\u0004#HY000SQL parser error: table \"mo_account\" does not exist"}
```

proxy 连接cn的时候，报上面的错误，需要调查一下为什么mo_account不存在

**Comment by qingxinhome** [comment]
目前发现造成升级SQL报错了原因是：升级语句到达proxy后， proxy会与CN Serivice进行握手通信， 并进行权限校验，然后才会广播下发升级语句到CN节点， 但是proxy在与CN Serivice进行握手通信和进行权限校验过程中报错：parser error: table "mo_account" does not exist"，目前该问题尚未复现
