### ISSUE TITLE
[Bug]: Execute Update statement report internal error: invalid free, mp header corruption

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#19910]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main，2.0-dev

### Commit ID

11e338e5e2e7af1493a49514b3d93b59aa2e88b3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> update real_time_position set distance = 2000 WHERE time_stamp between 1694733800000 and 1694750000000;
ERROR 20101 (HY000): internal error: invalid free, mp header corruption

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
mysql> DROP TABLE IF EXISTS `real_time_position`;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `real_time_position` (
    -> `location_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '位置id',
    -> `vehicle_id` VARCHAR(255) DEFAULT null COMMENT '车辆id',
    -> `longitude` VARCHAR(64) DEFAULT null COMMENT '经度',
    -> `latitude` VARCHAR(64) DEFAULT null COMMENT '纬度',
    -> `time_stamp` BIGINT DEFAULT null COMMENT '记录位置信息的时间戳',
    -> `distance` DOUBLE DEFAULT null COMMENT '距离',
    -> `area` VARCHAR(64) DEFAULT null COMMENT '省份',
    -> UNIQUE KEY `location_id` (`location_id`),
    -> KEY `time_stamp_index` (`time_stamp`) COMMENT '时间戳索引',
    -> KEY `vehicle_id_index` (`vehicle_id`) COMMENT '车辆ID索引'
    -> ) COMMENT='车辆实时位置表';
iming/workspace/loadfile/real_time_position_500w.csv' into table real_time_position fields terminated by ',' lines terminated by '\n' parallel 'true';Query OK, 0 rows affected (0.02 sec)

mysql> load data infile '/home/yiming/workspace/loadfile/real_time_position_500w.csv' into table real_time_position fields terminated by ',' lines terminated by '\n' parallel 'true';
Query OK, 5000000 rows affected (6.18 sec)

mysql> update real_time_position set distance = 2000 WHERE time_stamp between 1694733800000 and 1694750000000;
ERROR 20101 (HY000): internal error: invalid free, mp header corruption
```

**Comment by sukki37** [comment]
maybe dup with https://github.com/matrixorigin/matrixone/issues/19758

**Comment by qingxinhome** [comment]
{"level":"INFO","time":"2024/11/09 19:27:36.985930 +0800","name":"tn-service.lockservice.lockservice.allocator","caller":"lockservice/lock_table_allocator.go:477","msg":"bind created","service":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","table":272514,"service":"1731151604030149582dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"INFO","time":"2024/11/09 19:27:36.986137 +0800","name":"cn-service.lockservice","caller":"lockservice/service.go:607","msg":"bind created","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","service":"1731151604030149582dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","remote":false,"bind":"0-272514(272514)-1731151604030149582dd1dccb4-4d3c-41f8-b482-5251dc7a41bf-1731151600000686416"}
{"level":"ERROR","time":"2024/11/09 19:27:37.351399 +0800","caller":"mpool/mpool.go:607","msg":"error: internal error: invalid free, mp header corruption"}
{"level":"ERROR","time":"2024/11/09 19:27:37.351445 +0800","caller":"pipeline/pipeline.go:84","msg":"panic in pipeline: internal error: invalid free, mp header corruption"}
{"level":"ERROR","time":"2024/11/09 19:27:37.356888 +0800","name":"cn-service","caller":"frontend/txn.go:64","msg":"internal error: invalid free, mp header corruption","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 5|127.0.0.1:46018|account sys:dump|goRoutineId 2279|migrate-goRoutineId 0|019310ad-67d6-78a1-ad67-130f53ff9ecb","role":"moadmin","session_id":"019310ad-67d6-78a1-ad67-130f53ff9ecb","statement_id":"019310ad-f811-7b11-9e92-15560e8569fd","txn_id":"70f70f4866a9b62a180649363aac40af","span":{"trace_id":"479c38c3-36d7-e217-1186-e1012c88ec67","span_id":"936cdd1e417cc791"}}
{"level":"ERROR","time":"2024/11/09 19:27:37.378873 +0800","name":"cn-service","caller":"frontend/util.go:515","msg":"query trace status","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"update real_time_position set distance = 2000 WHERE time_stamp between 1694733800000 and 1694750000000","status":"fail","error":"internal error: invalid free, mp header corruption","txn_info":"70f70f4866a9b62a180649363aac40af:1731151656975715151-1","session_info":"connectionId 5|127.0.0.1:46018|account sys:dump|goRoutineId 2279|migrate-goRoutineId 0|019310ad-67d6-78a1-ad67-130f53ff9ecb","role":"moadmin","session_id":"019310ad-67d6-78a1-ad67-130f53ff9ecb","statement_id":"019310ad-f811-7b11-9e92-15560e8569fd","span":{"trace_id":"479c38c3-36d7-e217-1186-e1012c88ec67","span_id":"936cdd1e417cc791"}}
{"level":"INFO","time":"2024/11/09 19:27:38.094872 +0800","caller":"dbutils/mem.go:108","msg":"HeapInfo:TotalAlloc:10636MB Sys:3113MB HeapAlloc:2049MB HeapSys:3077MB HeapIdle:1021MB HeapReleased:996MB HeapInuse:2056MB NextGC:2195MB NumGC:18 PauseNs:2511737"}

**Comment by qingxinhome** [comment]
{"level":"INFO","time":"2024/11/09 19:56:40.043591 +0800","name":"tn-service.lockservice.lockservice.allocator","caller":"lockservice/lock_table_allocator.go:477","msg":"bind created","service":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd4dccb4-4d3c-41f8-b482-5251dc7a41bf","table":272514,"service":"1731153368207450480dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
{"level":"INFO","time":"2024/11/09 19:56:40.043698 +0800","name":"cn-service.lockservice","caller":"lockservice/service.go:607","msg":"bind created","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","service":"1731153368207450480dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","remote":false,"bind":"0-272514(272514)-1731153368207450480dd1dccb4-4d3c-41f8-b482-5251dc7a41bf-1731153364181332791"}
{"level":"ERROR","time":"2024/11/09 19:56:40.655434 +0800","caller":"mpool/mpool.go:610","msg":"error: internal error: invalid free, mp header corruption"}
{"level":"ERROR","time":"2024/11/09 19:56:40.655485 +0800","caller":"mpool/mpool.go:610","msg":"internal error: invalid free, mp header corruption","Stack Trace":"goroutine 2593 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc02b07e380?, {0xc04f3cef18?, 0xc9a300?, 0xc02b07e3d8?})\n\t/home/yiming/workspace/matrixone/pkg/common/mpool/mpool.go:609 +0x3aa\ngithub.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).reAlloc(0xc02b07e380, {0xc04f3cef18, 0x8, 0x8}, 0x4800?, 0x28?)\n\t/home/yiming/workspace/matrixone/pkg/common/mpool/mpool.go:670 +0xaf\ngithub.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Grow(0xc02b07e380, {0xc04f3cef18, 0x8, 0x8}, 0x47d0, 0x0)\n\t/home/yiming/workspace/matrixone/pkg/common/mpool/mpool.go:712 +0x7e\ngithub.com/matrixorigin/matrixone/pkg/container/vector.extend(0xc04f3da780, 0x1b214d5?, 0x2000?)\n\t/home/yiming/workspace/matrixone/pkg/container/vector/tools.go:198 +0x55\ngithub.com/matrixorigin/matrixone/pkg/container/vector.appendMultiFixed[...](0xc04f3da780, 0x409f400000000000, 0x0, 0x554, 0xffffffff00000040)\n\t/home/yiming/workspace/matrixone/pkg/container/vector/vector.go:3154 +0x39\ngithub.com/matrixorigin/matrixone/pkg/container/vector.GetUnionAllFunction.func13(0xc04886a0c0?, 0x0?)\n\t/home/yiming/workspace/matrixone/pkg/container/vector/vector.go:1459 +0x107\ngithub.com/matrixorigin/matrixone/pkg/container/batch.(*CompactBatchs).fillData(0xc048844f00, 0xc02b07e380, 0xc048839a40)\n\t/home/yiming/workspace/matrixone/pkg/container/batch/compact_batchs.go:182 +0x311\ngithub.com/matrixorigin/matrixone/pkg/container/batch.(*CompactBatchs).Extend(0xac0a1d8be?, 0xc1c3f15e26521572?, 0x0?)\n\t/home/yiming/workspace/matrixone/pkg/container/batch/compact_batchs.go:114 +0xda\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*s3Writer).append(0xc023b6aea0, 0xc01e967bc0, 0xc048839a40)\n\t/home/yiming/workspace/matrixone/pkg/sql/colexec/multi_update/s3writer.go:169 +0x47\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*MultiUpdate).update_s3(0xc002ba5c20, 0xc01e967bc0, {0x58e9320, 0xc025d385a0})\n\t/home/yiming/workspace/matrixone/pkg/sql/colexec/multi_update/multi_update.go:183 +0x26f\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*MultiUpdate).Call(0xc002ba5c20, 0xc01e967bc0)\n\t/home/yiming/workspace/matrixone/pkg/sql/colexec/multi_update/multi_update.go:149 +0x15c\ngithub.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x58a05d0, 0xc002ba5c20}, 0xc01e967bc0, {0x58e9320, 0xc025d385f0})\n\t/home/yiming/workspace/matrixone/pkg/vm/types.go:499 +0x5a\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call(0xc0224d7c70, 0xc01e967bc0)\n\t/home/yiming/workspace/matrixone/pkg/sql/colexec/connector/connector.go:55 +0xec\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc048879e30, 0xc01e967bc0)\n\t/home/yiming/workspace/matrixone/pkg/vm/pipeline/pipeline.go:71 +0xfe\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunWithReader(0xc00f81ce30, {0x5854c40, 0xc04883f600}, 0x0, 0xc01e967bc0)\n\t/home/yiming/workspace/matrixone/pkg/vm/pipeline/pipeline.go:59 +0xd1\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc01f0aa410, 0xc02aa4cd00)\n\t/home/yiming/workspace/matrixone/pkg/sql/compile/scope.go:205 +0x3fe\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()\n\t/home/yiming/workspace/matrixone/pkg/sql/compile/scope.go:300 +0x56\ngithub.com/panjf2000/ants/v2.(*goWorker).run.func1()\n\t/home/yiming/workspace/matrixone/vendor/github.com/panjf2000/ants/v2/worker.go:67 +0x8a\ncreated by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 2452\n\t/home/yiming/workspace/matrixone/vendor/github.com/panjf2000/ants/v2/worker.go:48 +0x5c\n"}
{"level":"ERROR","time":"2024/11/09 19:56:40.655559 +0800","caller":"mpool/mpool.go:612","msg":"error: internal error: invalid free, mp header corruption"}
{"level":"ERROR","time":"2024/11/09 19:56:40.655573 +0800","caller":"pipeline/pipeline.go:84","msg":"panic in pipeline: internal error: invalid free, mp header corruption"}
{"level":"ERROR","time":"2024/11/09 19:56:40.663722 +0800","name":"cn-service","caller":"frontend/txn.go:64","msg":"internal error: invalid free, mp header corruption","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 4|127.0.0.1:46900|account sys:dump|goRoutineId 2259|migrate-goRoutineId 0|019310c8-500c-78d6-8c37-8dce2c966c52","role":"moadmin","session_id":"019310c8-500c-78d6-8c37-8dce2c966c52","statement_id":"019310c8-90b0-75d3-9e1d-0b0fe8dc5e81","txn_id":"70f70f4866a9b62a18064ad0fbe95eca","span":{"trace_id":"dbff8078-131e-5807-bb5c-9daab84b6f35","span_id":"9c0412e40963abe7"}}
{"level":"ERROR","time":"2024/11/09 19:56:40.688993 +0800","name":"cn-service","caller":"frontend/util.go:515","msg":"query trace status","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","statement":"update real_time_position set distance = 2000 WHERE time_stamp between 1694733800000 and 1694750000000","status":"fail","error":"internal error: invalid free, mp header corruption","txn_info":"70f70f4866a9b62a18064ad0fbe95eca:1731153399983581427-1","session_info":"connectionId 4|127.0.0.1:46900|account sys:dump|goRoutineId 2259|migrate-goRoutineId 0|019310c8-500c-78d6-8c37-8dce2c966c52","role":"moadmin","session_id":"019310c8-500c-78d6-8c37-8dce2c966c52","statement_id":"019310c8-90b0-75d3-9e1d-0b0fe8dc5e81","span":{"trace_id":"dbff8078-131e-5807-bb5c-9daab84b6f35","span_id":"9c0412e40963abe7"}}

**Comment by qingxinhome** [comment]
{"level":"ERROR","time":"2024/11/09 19:56:40.655485 +0800","caller":"mpool/mpool.go:610","msg":"internal error: invalid free, mp header corruption","Stack Trace":"goroutine 2593 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free(0xc02b07e380?, {0xc04f3cef18?, 0xc9a300?, 0xc02b07e3d8?})
/home/yiming/workspace/matrixone/pkg/common/mpool/mpool.go:609 +0x3aa
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).reAlloc(0xc02b07e380, {0xc04f3cef18, 0x8, 0x8}, 0x4800?, 0x28?)
/home/yiming/workspace/matrixone/pkg/common/mpool/mpool.go:670 +0xaf
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Grow(0xc02b07e380, {0xc04f3cef18, 0x8, 0x8}, 0x47d0, 0x0)
/home/yiming/workspace/matrixone/pkg/common/mpool/mpool.go:712 +0x7e
github.com/matrixorigin/matrixone/pkg/container/vector.extend(0xc04f3da780, 0x1b214d5?, 0x2000?)
/home/yiming/workspace/matrixone/pkg/container/vector/tools.go:198 +0x55
github.com/matrixorigin/matrixone/pkg/container/vector.appendMultiFixed[...](0xc04f3da780, 0x409f400000000000, 0x0, 0x554, 0xffffffff00000040)
/home/yiming/workspace/matrixone/pkg/container/vector/vector.go:3154 +0x39
github.com/matrixorigin/matrixone/pkg/container/vector.GetUnionAllFunction.func13(0xc04886a0c0?, 0x0?)
/home/yiming/workspace/matrixone/pkg/container/vector/vector.go:1459 +0x107
github.com/matrixorigin/matrixone/pkg/container/batch.(*CompactBatchs).fillData(0xc048844f00, 0xc02b07e380, 0xc048839a40)
/home/yiming/workspace/matrixone/pkg/container/batch/compact_batchs.go:182 +0x311
github.com/matrixorigin/matrixone/pkg/container/batch.(*CompactBatchs).Extend(0xac0a1d8be?, 0xc1c3f15e26521572?, 0x0?)
/home/yiming/workspace/matrixone/pkg/container/batch/compact_batchs.go:114 +0xda
github.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*s3Writer).append(0xc023b6aea0, 0xc01e967bc0, 0xc048839a40)
/home/yiming/workspace/matrixone/pkg/sql/colexec/multi_update/s3writer.go:169 +0x47
github.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*MultiUpdate).update_s3(0xc002ba5c20, 0xc01e967bc0, {0x58e9320, 0xc025d385a0})
/home/yiming/workspace/matrixone/pkg/sql/colexec/multi_update/multi_update.go:183 +0x26f
github.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*MultiUpdate).Call(0xc002ba5c20, 0xc01e967bc0)
/home/yiming/workspace/matrixone/pkg/sql/colexec/multi_update/multi_update.go:149 +0x15c
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall({0x58a05d0, 0xc002ba5c20}, 0xc01e967bc0, {0x58e9320, 0xc025d385f0})
/home/yiming/workspace/matrixone/pkg/vm/types.go:499 +0x5a
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call(0xc0224d7c70, 0xc01e967bc0)
/home/yiming/workspace/matrixone/pkg/sql/colexec/connector/connector.go:55 +0xec
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc048879e30, 0xc01e967bc0)
/home/yiming/workspace/matrixone/pkg/vm/pipeline/pipeline.go:71 +0xfe
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunWithReader(0xc00f81ce30, {0x5854c40, 0xc04883f600}, 0x0, 0xc01e967bc0)
/home/yiming/workspace/matrixone/pkg/vm/pipeline/pipeline.go:59 +0xd1
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc01f0aa410, 0xc02aa4cd00)
/home/yiming/workspace/matrixone/pkg/sql/compile/scope.go:205 +0x3fe
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1()
/home/yiming/workspace/matrixone/pkg/sql/compile/scope.go:300 +0x56
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
/home/yiming/workspace/matrixone/vendor/github.com/panjf2000/ants/v2/worker.go:67 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 2452
/home/yiming/workspace/matrixone/vendor/github.com/panjf2000/ants/v2/worker.go:48 +0x5c
"}

**Comment by reusee** [comment]
观察中

**Comment by reusee** [comment]
继续观察

**Comment by qingxinhome** [comment]
从报错堆栈看是和multi_update算子相关，从目前该问题仍然存在，请帮忙处理 @aunjgr

**Comment by aunjgr** [comment]
麻烦 @ouyuanning 先帮忙查一下multi_update算子

**Comment by ouyuanning** [comment]
根本原因是在cloneWindow的时候，vector需要extend的时候，free时候不支持原始vector是const vector的情况
目前修改为CompactBatchs在拿到batch进行extend的时候，先复制并且展开，保证cloneWindow拿到的vector肯定不会是constant类型
