### ISSUE TITLE
[Bug]: mo panic caused by `panic: missing free for type: *lockservice.waiter`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19913]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/11742766475/job/32714178617?pr=19887

log: [mo-service.log.zip](https://github.com/user-attachments/files/17686878/mo-service.log.zip)

```
{"level":"INFO","time":"2024/11/08 13:56:30.572409 +0000","name":"cn-service","caller":"incrservice/service.go:392","msg":"auto increment cache delete","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","table-id":355195,"txn":"70f70f4866a9b62a180601cfb6f30bdd"}
panic: missing free for type: *lockservice.waiter, 70f70f4866a9b62a180601cfb6f2eeea-0xc108f282c0(1) 
	 create by: <<<>>>
	

goroutine 18 [running]:
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0x5847c40, 0xc108f282c0)
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/checker.go:133 +0x1de
github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/sync_pool_based.go:48 +0x65
```

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by reusee** [comment]
lockservice相关

**Comment by aressu1985** [comment]
@zhangxu19830126 麻烦更新一下该issue的状态

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11810446409
[multi-cn-e2e-with-race-linux-x86-reports.zip](https://github.com/user-attachments/files/17727033/multi-cn-e2e-with-race-linux-x86-reports.zip)

**Comment by zhangxu19830126** [comment]
默认开关是关闭的，永远不会有这个错误。
在
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/56d30606-9fe2-484b-b81e-71af29ddef5c">
打开了

**Comment by iamlinjunhong** [comment]
加了日志，在复现

**Comment by jensenojs** [comment]
repro : https://github.com/matrixorigin/matrixone/actions/runs/11911285540/job/33192463867?pr=20179#logs

```
col_name = '__mo_fake_pk_col' and offset = 310000","txn-id":"70f70f4866a9b62a180959e5da79873a","duration":"433.665µs","BatchSize":0,"retry-times":0,"AffectedRows":1}
panic: missing free for type: *lockservice.waiter, 70f70f4866a9b62a180959e5da798658-0xc0b89b26e0(1) 
	 create by: <<<>>>
	
goroutine 18 [running]:
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0x5856780, 0xc0b89b26e0)
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/checker.go:133 +0x1de
github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/sync_pool_based.go:48 +0x65
```

[mo-service.zip](https://github.com/user-attachments/files/17823952/mo-service.zip)

**Comment by badboynt1** [comment]
repro in https://github.com/badboynt1/matrixone/actions/runs/11945658106/job/33298701075?pr=387

**Comment by iamlinjunhong** [comment]
> repro in https://github.com/badboynt1/matrixone/actions/runs/11945658106/job/33298701075?pr=387

拿不到日志

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/11988122041/job/33423046393?pr=20298

[mo-service.log.zip](https://github.com/user-attachments/files/17893268/mo-service.log.zip)

**Comment by XuPeng-SH** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/12010837669/attempts/1?pr=20356

**Comment by gouhongshen** [comment]
repo: https://github.com/matrixorigin/matrixone/actions/runs/12026248094/job/33528355168?pr=20222

**Comment by aressu1985** [comment]
fixed
