### ISSUE TITLE
[Bug]: `r-w` occurred during bvt test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#19912]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5af31a7

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="966" alt="image" src="https://github.com/user-attachments/assets/1a4f9f4b-8abd-43e0-b98e-bf596c36ec1e">

log: https://grafana.ci.matrixorigin.cn/goto/_0GUgKGHR?orgId=1
job link:https://github.com/matrixorigin/matrixone/actions/runs/11745257399/job/32722995712

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by w-zr** [comment]
pr merged.

**Comment by aressu1985** [comment]
fixed
