### ISSUE TITLE
[Bug]: add a new tn node cause: ERROR 20605 (HY000): dn shard uuid , id 3735928495 not found

### ISSUE THREAD

**Issue by loveRhythm1990** [matrixorigin/matrixone#19924]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9a8c0975d8b1baa8c43a35d355d2945a146062b3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create database <dbName>;
ERROR 20605 (HY000): dn shard uuid , id 3735928495 not found

### Expected Behavior

submit transaction success

### Steps to Reproduce

```Markdown
1. delete old tn node(include pvc storage data)
2. pull up a new tn node
```

**Comment by volgariver6** [comment]
fixed

**Comment by loveRhythm1990** [comment]
waiting to be tested

**Comment by loveRhythm1990** [comment]
close since fixed
