### ISSUE TITLE
[Feature Request]: Aggregate function any()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1992]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of  Clickhouse 22.3
2. [Function syntax](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/any/)

Selects the first encountered value.
The query can be executed in any order and even in a different order each time, so the result of this function is indeterminate.
To get a determinate result, you can use the `min()` or `max()` function instead of `any()`.

When a SELECT query has the GROUP BY clause or at least one aggregate function, ClickHouse (in contrast to MySQL) requires that all expressions in the SELECT, HAVING, and ORDER BY clauses be calculated from keys or from aggregate functions. In other words, each column selected from the table must be used either in keys or inside aggregate functions. To get behavior like in MySQL, you can put the other columns in the any aggregate function.

3. Example
```sql
> SELECT student_name, ANY(test_score)
       FROM student
       GROUP BY student_name;
```
### Describe implementation you've considered
It's similar to the function `max()` and `min()` without comparison.

### Documentation, Adoption, Use Case, Migration Strategy

* Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions/) about how to develop an aggregate function.

* Please specify your factorization formula as well as the performance result with the dataset in our tutorial. 

### Additional information

**Comment by supermario1990** [comment]
please assign it to me, i want try. thx

**Comment by dengn** [comment]
> please assign it to me, i want try. thx

Sure. Issue assigned, good luck!
