### ISSUE TITLE
[Bug]: create FULLTEXT INDEX on table(has many data) failed

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19923]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9a8c0975d8b1baa8c43a35d355d2945a146062b3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="908" alt="image" src="https://github.com/user-attachments/assets/cd0cd456-68e3-4fec-8d2c-3287708738cb">

### Steps to Reproduce

```Markdown
1、load tpch 10g data to mo
2、set experimental_fulltext_index=1;
CREATE FULLTEXT INDEX ftidx ON lineitem(l_comment);
```

### Additional information

<img width="546" alt="image" src="https://github.com/user-attachments/assets/b982f568-d4d1-4579-b845-a24c41256e69">

**Comment by tom-csf** [comment]
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22O2c%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-9a8c097-202411102210%5C%22%7D%20%7C%3D%20%60CREATE%20FULLTEXT%20INDEX%20ftidx%20ON%20lineitem%28l_comment%29%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731293422000%22,%22to%22:%221731293962000%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/4100a348-2b8c-45ae-b7d1-ec164944b701">

**Comment by tom-csf** [comment]
验证发现 还是失败：
单cn main分支出现 cn 重启
多cn 2.0-dev分支报错 无cn 重启
<img width="1289" alt="企业微信截图_9142b6d5-f759-42cf-8a58-d4d96639f3f2" src="https://github.com/user-attachments/assets/67655613-854e-4640-89a2-9ec5b96b823b">
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22njJ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-e9f6396df-20241112%5C%22%7D%20%7C%3D%20%60no%20such%20table%20tpch_10g.__mo_index_secondary_01932380-f024-7658-921f-10bb063ba019%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731467293000%22,%22to%22:%221731467593000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by ouyuanning** [comment]
多CN报错的复现方式
```
select mo_ctl('cn', 'task', 'disable');
drop database if exists db1;
create database db1;
use db1;

set experimental_fulltext_index=1;
drop table if exists t1;
create table t1(a int primary key, b varchar(200));
insert into t1 select result, "test create big fulltext index" from generate_series(3000000) g;  //如果把这里的数据量变小，后面的就不会报错，比如300000
create fulltext index ftidx on t1 (b); //这里会报错，
```

报错是这个地方
![image](https://github.com/user-attachments/assets/cd35604b-53f4-4132-86fc-1e286c3903a5)
直接原因是601行的判断，进不去。

**Comment by aptend** [comment]
报错的表 __mo_index_secondary_* 没有被创建过，Relation 接口返回找不到表是预期行为。需要关注索引表的创建逻辑

**Comment by qingxinhome** [comment]
执行创建索引语句时，会有一下步骤：
1. 检查索引表名是否已经存在，如果存在就报错， 如果不存在就执行步骤2
2. 调用txnDatabase.Create()接口方法，在当前事务中创建索引表对应的relation
3. 如果索引表有自增列，自增列表中插入自增列信息
4. 往索引表中填入数据， 构建insert into select * from语句，通过调用TxnExecutor内部执行器，执行该insert语句
以上步骤全部成功后，索引即可创建成功

通过日志分析，发现步骤1，步骤2，步骤3均已执行成功，但是执行步骤4时失败报错，也就是说，索引表的表结构创建成功了，但是
往索引表中insert数据时报错，
通过日志看到，内部执行器在运行insert into select的物理计划时， 执行preinsert算子报错了，
原因是在生成自增列值的过程中无法找到对应的表id， 如下图所示
![image](https://github.com/user-attachments/assets/1032e822-9c92-4882-b19f-eddc1cecdf35)

**Comment by aptend** [comment]
> 执行创建索引语句时，会有一下步骤：
> 
> 1. 检查索引表名是否已经存在，如果存在就报错， 如果不存在就执行步骤2
> 2. 调用txnDatabase.Create()接口方法，在当前事务中创建索引表对应的relation
> 3. 如果索引表有自增列，自增列表中插入目标表的自增列信息
> 4. 往索引表中填入数据， 构建insert into select * from语句，通过调用TxnExecutor内部执行器，执行该insert语句
>    以上步骤全部成功后，索引即可创建成功
> 
> 通过日志分析，发现步骤1，步骤2，步骤3均已执行成功，索引表创建成功后，也可以获取对应的relation，但是执行步骤4时失败报错， 也就是说，索引表的表结构创建成功了，但是往索引表中insert数据时报错， 通过日志看到，内部执行器TxnExecutor在运行insert into select的物理计划时， 执行到preinsert算子报错了， 原因是在生成自增列值的过程中无法找到对应的表id， 如下图所示 ![image](https://private-user-images.githubusercontent.com/70939751/386168651-1032e822-9c92-4882-b19f-eddc1cecdf35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzkwNDksIm5iZiI6MTczMTYzODc0OSwicGF0aCI6Ii83MDkzOTc1MS8zODYxNjg2NTEtMTAzMmU4MjItOWM5Mi00ODgyLWIxOWYtZWRkYzFjZWNkZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyNDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NjEyNjg0MjJiNWVmMzM4YTIzMDc3MGZiNzE2MGYzMmFjMmNkYmE0NGUyYzg4MjE4N2E4YmE5MzUzNjNkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8X240PRC6uqMroOGcuLaJuWLoHj7XPFUuEzB--qaPs0)

第三步插入自增列信息的 txnid 和第四步读取的 txnid 不同，属于不同事务。所以查不到

**Comment by jensenojs** [comment]
> 执行创建索引语句时，会有一下步骤：
> 
> 1. 检查索引表名是否已经存在，如果存在就报错， 如果不存在就执行步骤2
> 2. 调用txnDatabase.Create()接口方法，在当前事务中创建索引表对应的relation
> 3. 如果索引表有自增列，自增列表中插入目标表的自增列信息
> 4. 往索引表中填入数据， 构建insert into select * from语句，通过调用TxnExecutor内部执行器，执行该insert语句
>    以上步骤全部成功后，索引即可创建成功
> 
> 通过日志分析，发现步骤1，步骤2，步骤3均已执行成功，索引表创建成功后，也可以获取对应的relation，但是执行步骤4时失败报错， 也就是说，索引表的表结构创建成功了，但是往索引表中insert数据时报错， 通过日志看到，内部执行器TxnExecutor在运行insert into select的物理计划时， 执行到preinsert算子报错了， 原因是在生成自增列值的过程中无法找到对应的表id， 如下图所示 ![image](https://private-user-images.githubusercontent.com/70939751/386168651-1032e822-9c92-4882-b19f-eddc1cecdf35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODI1NzksIm5iZiI6MTczMTk4MjI3OSwicGF0aCI6Ii83MDkzOTc1MS8zODYxNjg2NTEtMTAzMmU4MjItOWM5Mi00ODgyLWIxOWYtZWRkYzFjZWNkZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAyMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YjQ3NTA1YzU0NWRiMDYxOTliYTI0OGJlMWI4NDY4NzAxOTUzNTQzZjdlZWMxZWU4YTgwNzA1OWFjZjQ2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HcBpLEtHxN5lKEK1WPl9O9B_QvrrPwyw2kBb4gkY1GE)
> 
> @ouyuanning @aptend

- CN1上执行到第三步 : 自增列表中插入目标表的自增列信息的时候
  - incr-service将其对应的tableID存在内部的一个map
  - 由于本事务还没有提交, 因此这个tableID(暂名为`xxx`)通过SQL去查是查不到的, 👇就是喜亮哥日志中显示的, 和原来create fulltext index不一样的事务. 
    ```sql
    select col_name, col_index, offset, step from mo_increment_columns where table_id = 272590 order by col_index
    ```
- 这个SQL是在CN2上执行的, 现在看原因是`insert into select`的数据量规模达到一定程度, 所以将一部分的insert的工作分到了CN2上
  - 但由于CN2上的incr-service的map中没有`xxx`, 所以它只能通过后台SQL去查
  - 且由于CN1上的事务还没有提交, 所以查不到

<img width="1844" alt="image" src="https://github.com/user-attachments/assets/6588dc4f-075a-43d2-b6d9-1e681d61eaf7">

**Comment by tom-csf** [comment]
多cn的事务的问题已经解决， 单个cn oom的问题另外在https://github.com/matrixorigin/matrixone/issues/20213跟踪
