### ISSUE TITLE
[Feature Request]: Aggregation function bit_and()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1993]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Similar to MySQL 8.0 in syntax.
2. Function syntax

[BIT_AND(expr)](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_bit-and)

Returns the bitwise AND of all bits in expr.

Both input parameters and output values are of type uint.  

```sql
mysql> SELECT  MAKER, BIT_AND(PRICE) AS BITS
          FROM CARS GROUP BY MAKER
+---------------------------------------------------------+
|MAKER           BITS                                     |
+---------------------------------------------------------+
|CHRYSLER        512                                      |
|FORD            12488                                    |
|HONDA           2144                                     |
+---------------------------------------------------------+
```

### Documentation, Adoption, Use Case, Migration Strategy

* Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions/) about how to develop an aggregate function.

* Please specify your factorization formula as well as the performance result with the dataset in our tutorial. 

### Additional information

**Comment by noneback** [comment]
Plz assign it to me. I will try my best in my spare time.

**Comment by dengn** [comment]
> Plz assign it to me. I will try my best in my spare time.

OK. Issue assigned.

**Comment by noneback** [comment]
Do we need to support `bit_and(str)`? I have noticed that like `SUM` agg function in original matrixone repository does not support string type as a parameter. So I like to **not** using string as an input in order to simplify my code.

**Comment by noneback** [comment]
Currently, I have supported all numeric types already.

**Comment by noneback** [comment]
I have finished this issue in #2092

**Comment by dengn** [comment]
Feature implemented.
