### ISSUE TITLE
[Bug]: fulltext index  select count+MATCH  AGAINST failed

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19939]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

9a8c0975d8b1baa8c43a35d355d2945a146062b3

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1174" alt="image" src="https://github.com/user-attachments/assets/3a621318-c653-4f4f-9f16-6c8b3f2cddf9">

### Steps to Reproduce

```Markdown
1、create table and fulltext index
2、select count(IF(MATCH(r_name) AGAINST('+MIDDLE' IN BOOLEAN MODE),1,NULL)) AS count from region;
```

**Comment by tom-csf** [comment]
join + MATCH AGAINST failed
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/cd951f75-55a6-4fa7-b9ef-8667cf070c01">

**Comment by cpegeric** [comment]
From the document,

mysql> SELECT
    -> COUNT(IF(MATCH (title,body) AGAINST ('database' IN NATURAL LANGUAGE MODE), 1, NULL))
    -> AS count
    -> FROM articles;

The second query is a full table scan which is not support for now.

The first query does some extra work (sorting the results by relevance) but also can use an index lookup based on the WHERE clause. The index lookup might make the first query faster if the search matches few rows. The second query performs a full table scan, which might be faster than the index lookup if the search term was present in most rows.

**Comment by cpegeric** [comment]
<img width="980" alt="image" src="https://github.com/user-attachments/assets/6741b45f-e6e1-4623-a270-ea1b7056532e">

Quite complicated to work with JOIN, I don't think we can support JOIN for this version as well.

**Comment by cpegeric** [comment]
but the error message is misleading... I will change the error message.

**Comment by tom-csf** [comment]
验证确认提示信息出现变化
