### ISSUE TITLE
[Feature Request]: Aggregate function bit_or()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1994]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Similar to MySQL 8.0 in syntax.
2. Function syntax

[BIT_OR(expr) [over_clause]](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_bit-or)

Returns the bitwise OR of all bits in expr.  
Both input parameters and output values are of type uint.  
```sql
mysql> SELECT  MAKER, BIT_OR(PRICE) BITS
          FROM CARS GROUP BY MAKER

+---------------------------------------------------------+
|MAKER           BITS                                     |
+---------------------------------------------------------+
|CHRYSLER        62293                                    |
|FORD            16127                                    |
|HONDA           32766                                    |
+---------------------------------------------------------+
```
### Documentation, Adoption, Use Case, Migration Strategy

* Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions/) about how to develop an aggregate function.

* Please specify your factorization formula as well as the performance result with the dataset in our tutorial. 

### Additional information

**Comment by dengn** [comment]
> /assign

ok. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by NTH19** [comment]
"I have finished Issue #1994"  https://github.com/matrixorigin/matrixone/pull/2123

**Comment by dengn** [comment]
Feature implemented.
