### ISSUE TITLE
[Feature Request]: Aggregate function bit_xor()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1995]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Similar to MySQL 8.0 in syntax.
2. Function syntax

[BIT_XOR(expr)](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_bit-xor)

Returns the bitwise [XOR](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_xor) of all bits in expr.

Both input parameters and output values are of type uint.  

### Documentation, Adoption, Use Case, Migration Strategy

* Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions/) about how to develop an aggregate function.

* Please specify your factorization formula as well as the performance result with the dataset in our tutorial. 

### Additional information

**Comment by BePPPower** [comment]
please assign it to me, i want try. thx

**Comment by dengn** [comment]
> please assign it to me, i want try. thx

ok. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by BePPPower** [comment]
> 

done!

**Comment by dengn** [comment]
Feature implemented.
