### ISSUE TITLE
[Bug]: Load CSV (actually maybe any format) consume too much resource, both CPU and memory (small objects).

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#19965]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e7771f6446519c3f0708d36aaaa85ab3f7d56e97

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The code is extremely bad -- see attached profiling.  
![Screenshot From 2024-11-09 10-31-39](https://github.com/user-attachments/assets/18832a33-1d59-4c36-9a8c-533f0f20a900)

### Steps to Reproduce

```Markdown
See profiling.
```

**Comment by YANGGMM** [comment]
@huby2358  麻烦看一下

**Comment by fengttt** [comment]
csv 和 external table 代码问题比较多。  看起来没什么本质的结构性的问题， 但代码细节差的比较远。  举几个例子。
[toLower
](https://github.com/matrixorigin/matrixone/blob/e7771f6446519c3f0708d36aaaa85ab3f7d56e97/pkg/sql/colexec/external/external.go#L1238)

我们对每个cell， 都会call `toLower(colName)`, 然后再 map 查找一下。  这个整个load 算一次就可以了。
[getNullFlag
](https://github.com/matrixorigin/matrixone/blob/e7771f6446519c3f0708d36aaaa85ab3f7d56e97/pkg/sql/colexec/external/external.go#L1221)

这个函数问题也很大。 首先这个里面的 `toLower(field)` 应该call吗？ 一般NULL string， 都是case sensitive 的。  第二， quote 处理了吗？  最后， 一般这个地方都是default，我们处理了。 如果不是， 一般也就是一个值。  这地方是否需要优化一个值的场景， 需要这么general的 `map[string][]string` 吗？   这个最后反而不全， 这地方应该handle 最常见场景，做到最好。  对于一般场景，是一个expression， 那在external 这个算子里加 projection list 就完了。

**Comment by huby2358** [comment]
暂时没投入

**Comment by huby2358** [comment]
> csv 和 external table 代码问题比较多。 看起来没什么本质的结构性的问题， 但代码细节差的比较远。 举几个例子。 [toLower ](https://github.com/matrixorigin/matrixone/blob/e7771f6446519c3f0708d36aaaa85ab3f7d56e97/pkg/sql/colexec/external/external.go#L1238)
> 
> 我们对每个cell， 都会call `toLower(colName)`, 然后再 map 查找一下。 这个整个load 算一次就可以了。 [getNullFlag ](https://github.com/matrixorigin/matrixone/blob/e7771f6446519c3f0708d36aaaa85ab3f7d56e97/pkg/sql/colexec/external/external.go#L1221)
> 
> 这个函数问题也很大。 首先这个里面的 `toLower(field)` 应该call吗？ 一般NULL string， 都是case sensitive 的。 第二， quote 处理了吗？ 最后， 一般这个地方都是default，我们处理了。 如果不是， 一般也就是一个值。 这地方是否需要优化一个值的场景， 需要这么general的 `map[string][]string` 吗？ 这个最后反而不全， 这地方应该handle 最常见场景，做到最好。 对于一般场景，是一个expression， 那在external 这个算子里加 projection list 就完了。

1. toLower(field),这里是针对每个field call，这里是对比field是否和set xx1 nullify(xx1, "xx2"), 对比filed是否和xx2相等（大小写不敏感），所以对每个field都要call一次

**Comment by huby2358** [comment]
<img width="497" alt="image" src="https://github.com/user-attachments/assets/0639e8a0-779d-4f0c-8406-e606cf48a152">
1. 在mo试了一下nullif函数，从上面截图可以看出，mo nullif是case sensitive的， 目前load 里面set nullif的表现是大小写不敏感，和nullif函数表现是不一致的，所以修改load这里的表现，与nullif函数保持一致，那么这里就不需要tolower调用了

**Comment by huby2358** [comment]
<img width="590" alt="image" src="https://github.com/user-attachments/assets/56f486c0-1a4e-41dc-9c7b-c89b501b2947">
试了mysql， nullif在普通使用和在load使用都是大小写不敏感，这一点和mo不一样
