### ISSUE TITLE
[Bug]: fulltext index not parsing the JSON value

### ISSUE THREAD

**Issue by cpegeric** [matrixorigin/matrixone#19963]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

895fb49772366a36851e3ce1fd674e7dc72478fa

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

json values are not parsed by tokenizer.

### Expected Behavior

json values should be parsed by tokenizer.

### Steps to Reproduce

```Markdown
create table src (id bigint primary key, json1 json, json2 json, FULLTEXT(json1, json2) with parser json);
insert into src values  (0, '{"a":1, "b":"red"}', '{"d": "happy birthday", "f":"winter"}'),
(1, '{"a":2, "b":"中文學習教材"}', '["apple", "orange", "banana", "指引"]'),
(2, '{"a":3, "b":"red blue"}', '{"d":"兒童中文"}');

select * from src where match(json1, json2) against('+happy +birthday' in boolean mode);
```

**Comment by tom-csf** [comment]
验证已经bugfix
