### ISSUE TITLE
Welcome to MatrixCamp 2022!

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#1997]
**Welcome! Voilà this is your phone booth entering Matrix world~~~**

> If you prefer reading Chinese, please check this event [briefing](https://github.com/matrixorigin/matrixone/blob/main/docs/cn/MatrixOne/MatrixCampEvent.md). 

## MatrixCamp 2022 Event 
> MatrixCamp is a collaborative development event launched and organized by the MatrixOne community. Developers interested in database technologies are welcome to sign up for this 2-week event to complete community development tasks of varied difficulties. The MatrixOne community will review the code quality and make different awards to contributors.

We prepared 56 tasks in 4 categories, assigned with different difficulties, including Challenging, Moderate, and Easy. You can pick the one that interests and fits you the most. Any developer who has some basic practice with Golang language, a little bit of knowledge of database and math is well qualified for these tasks. We also have detailed tutorials and patient mentors at your service. 

- Mathematical functions
- Date and time functions
- String functions
- Aggregate functions

## Registration procedure

Before you start, please kindly give MatrixOne a `Star`, `Fork` and `Watch`, thanks! 

1. Sign up for the event at [https://www.wjx.top/vm/Ys1rz1I.aspx](https://www.wjx.top/vm/Ys1rz1I.aspx), add the MatrixOne community assistant "MatrixOrigin001" as a WeChat friend and leave your GitHub ID.
2. Click the issue link to go to the issue details page, and leave a comment under the issue to claim your interest such as "I'd like to work on this issue”. 
3. The mentor will communicate with the participants who picked this issue and assign the task to the best match through communication.

> Please note: 1 person can choose multiple issues，1 issue will only be developed by 1 person

Let's pick!

### 1. Mathematical functions

- [x] ~~https://github.com/matrixorigin/matrixone/issues/1966~~ **[Easy]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1967~~ **[Easy]**Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1968~~ **[Easy]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1969~~ **[Easy]** Finished
- [x] https://github.com/matrixorigin/matrixone/issues/1970 **[Easy]** Assigned
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1971~~ **[Easy]** Assigned
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1973~~ **[Easy]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/2094~~ **[Easy]** Finished
- [ ] https://github.com/matrixorigin/matrixone/issues/2095 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2096 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2097 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2098 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2099 **[Moderate]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2100 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2101 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2102 **[Easy]** 
- [ ] https://github.com/matrixorigin/matrixone/issues/2103 **[Moderate]** 

### 2. Date and time functions

- [x]  ~~https://github.com/matrixorigin/matrixone/issues/1974~~ **[Easy]** Finished
- [x]  ~~https://github.com/matrixorigin/matrixone/issues/1976~~ **[Easy]** Finished
- [x]  https://github.com/matrixorigin/matrixone/issues/1977 **[Moderate]** Assigned
- [ ]  https://github.com/matrixorigin/matrixone/issues/1978 **[Moderate]**
- [ ]  https://github.com/matrixorigin/matrixone/issues/1979 **[Moderate]**
- [x]  ~~https://github.com/matrixorigin/matrixone/issues/1980~~ **[Moderate]** Finished
- [x]  ~~https://github.com/matrixorigin/matrixone/issues/2049~~ **[Moderate]** Finished
- [x]  ~~https://github.com/matrixorigin/matrixone/issues/2046~~ **[Moderate]** Finished
- [ ]  https://github.com/matrixorigin/matrixone/issues/2047 **[Moderate]**
- [ ]  https://github.com/matrixorigin/matrixone/issues/2048 **[Moderate]**
- [x]  https://github.com/matrixorigin/matrixone/issues/1830 **[Moderate]** Assigned
- [ ] https://github.com/matrixorigin/matrixone/issues/2104 **[Moderate]**
- [ ] https://github.com/matrixorigin/matrixone/issues/2105 **[Moderate]**  

### 3. String functions

- [x] ~~https://github.com/matrixorigin/matrixone/issues/1984~~ **[Moderate]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1985~~ **[Moderate]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1986~~ **[Moderate]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1987~~ **[Moderate]** Finished
- [x] https://github.com/matrixorigin/matrixone/issues/1988 **[Moderate]** Assigned
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1989~~ **[Moderate]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1990~~ **[Moderate]** Finished
- [x] https://github.com/matrixorigin/matrixone/issues/1991 **[Moderate]** Assigned
- [ ] https://github.com/matrixorigin/matrixone/issues/2106 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2107 **[Easy]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2108 **[Easy]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2109 **[Easy]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2110 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2111 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2112 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2113 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2114 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2115 **[Moderate]**  
- [ ] https://github.com/matrixorigin/matrixone/issues/2116 **[Moderate]**  
- [x] ~~https://github.com/matrixorigin/matrixone/issues/2117~~ **[Moderate]**  Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/2118~~ **[Moderate]**  Finished

### 4. Aggregate functions

- [x] https://github.com/matrixorigin/matrixone/issues/1992  **[Challenging]** Assigned
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1993~~  **[Challenging]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1994~~  **[Challenging]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1995~~  **[Challenging]** Finished
- [x] ~~https://github.com/matrixorigin/matrixone/issues/1996~~  **[Challenging]** Finished

## Before you start

1. Read the [contribution guide](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/make-your-first-contribution/) carefully, it describes how to contribute in MatrixOne.
3. To learn more about MatrixOne, read [MatrixOne documentation](https://docs.matrixorigin.io/).
4. Checkout our [**built-in function tutorial**](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) and [**aggregate function tutorial**](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions/) about how to work these functions out.

## Pull request requirements
1.  Please write a full unit test for your function before you make a Pull Request, otherwise your PR won't be accepted. 
2. After you complete coding, make a Pull Request to MatrixOne with: 
* PR title format: [MatrixCamp] + function name + PR title
* Label ：[MatrixCamp]
* PR content: follow [MatrixOne PR template] (https://github.com/matrixorigin/matrixone/blob/main/.github/PULL_REQUEST_TEMPLATE.md)  
3. After you submit your PR, comment on the status of your PR submission as requested under this page.
Comment format: "I have finished Issue #" + PR link id

## Frequently asked questions

**Q: Do we need to be assigned to start a task?**
A:  Yes, this is to avoid different developers to working on the same issue. So please comment under issue to claim your interest, and get assigned before you write code.

**Q: Why `select abs(-1);` or `select d, abs(-1) from t;` doesn't work?**
A:  Currently, MatrixOne doesn't support query without table and without argument. So `select abs(-1);` and `select abs(-1) from table1;` will both fail. The correct way to run this test is to create a table and insert some data, and run the builtin function.
```sql
select abs(a) from t; 
```

**Q: Why after submitting to MatrixOne, my repository is always ahead of MatrixOne?**
A: As MatrixOne complies with `Squash and Merge` rule for PR, the submitted repo will not be consistent with the MatrixOne main branch. In order to keep your local repo, remote repo and MatrixOne repo consistent, we recommend you to follow these git instructions:
```
1. Fork MatrixOne repo.
2. Clone your remote repo to local: git clone https://github.com/YOUR_NAME/matrixone.git
3. Add MatrixOne repo to a remote repo: git remote add upstream https://github.com/matrixorigin/matrixone.git
4. Write your code and fix conflict in the local.
5. Push to a new branch of your remote repo: git push origin main:NEW_BRANCH
6. Submit a pull request from your remote repo for review and merge.
7. After your pull request is merged, you can override the local repo: git pull --force upstream main:main
8.  Update your remote repo too: git push --force origin main:main
```

**Q: My PR failed the automatic Test of MatrixOne, why and what can I do?**
A：After each PR, MatrixOne will run automatic CI and BVT test. Developers can check the test progress and log, if it's related to your function implementation, you can review the log and modify your code. If it's other problems unrelated to your function, please comment in the PR, and the community will look at the test failing. Unrelated test failing will not affect the merge of your function implementation. Currently, CI test of MatrixOne is not very stable, some failure unrelated with your function might occur.

**Q: The printing message of MatrixOne is too much, how can I close it?**
A: The logger print level of `system_vars_config.toml` is set to default as `DEBUG`, which will print a lot of information for you. If you only care about what your built-in function will print, you can modify the `system_vars_config.toml` and set `cubeLogLevel` and `level` to `ERROR` level.
```
cubeLogLevel = "error"
level = "error"
```

**Q: If I have some questions about how to implement my task, who can I ask?**
A: If you encounter some problems regarding the wrong behavior or bug of MatrixOne, you can file an issue in Github and the community will look at it. If you have questions about how to develop the task, you can just comment under the issue you were assigned, our mentors of MatrixCamp will look at it and respond to you. 

**Q: My MatrixOne server is launched, and I connect to it with MySQL client, how do I know if it works?**
A: If your MySQL client prints the following result, you are well connected. 
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1002
Server version: 0.3.0 MatrixOne

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement. 
```

**Q: My MatrixOne server is launched, but I cann't connect to it with MySQL client, how can I solve it?**
A: There are various reasons for this, please check on the error log to locate the issue:
1. Port conflict: Sometimes a port is in use error at port 50000 will occur. You could checkout what process in occupying port 50000 by `lsof -i:50000`. This command helps you to get the PIDNAME of this process, then you can kill the process by `kill -9 PIDNAME`.
6. Incompatible storage: sometimes when you pull latest code from codebase, but with an some old storage of data, you may fail to connect with MySQL client. You may delete the `/Store` repository and restart.

**Q: Reviewer asks me to make indentation format consistent, how do I do that?**
A: You can use the official `gofmt` tool of Golang language, or make related settings with VS Code or Goland IDE tools.

**Q: I don't quite understand about the Vector structure. **
A: The vector struct is used to hold column data in the computation layer. It's a fundamental data structure in MatrixOne.
```
// Vector.Or: indicates whether this vector is the original vector read from the disk
// Link: the number of soft link this vector has
// Data: the raw data in memory
// Typ: this vector's type
// Col: the encoded data in memory, it shares the same memory location with Vector.Data field, but casted to a specific type, e.g., []int32
// Nsp: this is a bitmap storing all the NULL values in a column
```

**Comment by Charlie17Li** [comment]
Could you please update the todo list ? I find some tasks have been done or assigned

**Comment by dengn** [comment]
> Could you please update the todo list ? I find some tasks have been done or assigned

No problem. Issue list updated.
