### ISSUE TITLE
[Bug]: ERROR 20102 (HY000): load format '' is not yet implemented

### ISSUE THREAD

**Issue by xuoutput** [matrixorigin/matrixone#19981]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

8.0.30-MatrixOne-v2.0.1

### Commit ID

fb915b59d

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
Database changed
mysql> show tables
    -> ;
+---------------+
| Tables_in_hx1 |
+---------------+
| ht            |
| ht2           |
+---------------+
2 rows in set (0.05 sec)

mysql> LOAD DATA LOCAL INFILE {'filepath'='/Users/hengxu/Documents/t2.tar.gz', 'compression'='gzip','format'='jsonline','jsondata'='array'} into table hx1.ht2 ignore 1 lines;
ERROR 20102 (HY000): load format '' is not yet implemented
mysql> LOAD DATA LOCAL INFILE {'filepath'='/mo_data/data.jl.gz', 'compression'='gzip','format'='jsonline','jsondata'='array'} into table db1.a ignore 1 lines;
ERROR 1146 (HY000): no such table db1.a
mysql> LOAD DATA LOCAL INFILE {'filepath'='/mo_data/data.jl.gz', 'compression'='gzip','format'='jsonline','jsondata'='array'} into table hx1.ht2 ignore 1 lines;
ERROR 20102 (HY000): load format '' is not yet implemented
mysql> LOAD DATA LOCAL INFILE {'filepath'='/Users/hengxu/Documents/t1.json', 'compression'='gzip','format'='jsonline','jsondata'='array'} into table hx1.ht2 ignore 1 lines;
ERROR 20102 (HY000): load format '' is not yet implemented
mysql> LOAD DATA LOCAL INFILE {'filepath'='/Users/hengxu/Documents/t1.json', 'compression'='gzip','format'='jsonline','jsondata'='object'} into table hx1.ht2 ignore 1 lines;
ERROR 20102 (HY000): load format '' is not yet implemented
mysql> LOAD DATA LOCAL INFILE {'filepath'='/Users/hengxu/Documents/t1.json', 'compression'='','format'='jsonline','jsondata'='object'} into table hx1.ht2 ignore 1 lines;
ERROR 20102 (HY000): load format '' is not yet implemented
mysql> LOAD DATA LOCAL INFILE {'filepath'='/Users/hengxu/Documents/t2.tar.gz', 'compression'='','format'='jsonline','jsondata'='object'} into table hx1.ht2 ignore 1 lines;
ERROR 20102 (HY000): load format '' is not yet implemented
```

用的https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/Migrate-Data/Load-Local-Data/ 

```
{"name": "11"}
{"name": "22l"}
```

t2.tar.gz 是 tar -czvf t2.tar.gz t1.json 后的

### Steps to Reproduce

```Markdown
👆🏻
```

**Comment by YANGGMM** [comment]
@huby2358 麻烦看一下

**Comment by huby2358** [comment]
等https://github.com/matrixorigin/matrixone/issues/20002修复再关掉

**Comment by heni02** [comment]
confirm,closed
load data local infile 文件不存在验证
2.0-dev commit:167a50052b31926989e326ad0c37b90e57438dbf
json文件：
mysql> create table t1(col1 bool,col2 int,col3 varchar(100), col4 date,col5 datetime,col6 timestamp,col7 decimal,col8 float,col9 json,col10 text,col11 json,col12 bool);
Query OK, 0 rows affected (0.02 sec)
mysql> load data local infile {'filepath'='/load_data/jsonline_object.jl','format'='jsonline','jsondata'='object'} into table t1;
ERROR 2 (HY000): File '/load_data/jsonline_object.jl' not found (OS errno 2 - No such file or directory)

压缩文件：
mysql> create table t9(a varchar, b varchar, c varchar, d varchar);
Query OK, 0 rows affected (0.03 sec)
mysql> load data local infile {"filepath"="/Users/heni/load_data/parallel.txt.gz", "compression"="gzip"} into table t9 FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 2 (HY000): File '/Users/heni/load_data/parallel.txt.gz' not found (OS errno 2 - No such file or directory)

main commit:44f4d5b47ba00287973ecb8b06d12066d9519593
json文件：
mysql> create table t1(col1 bool,col2 int,col3 varchar(100), col4 date,col5 datetime,col6 timestamp,col7 decimal,col8 float,col9 json,col10 text,col11 json,col12 bool);
mysql>  load data local infile {'filepath'='/load_data/jsonline_object.jl','format'='jsonline','jsondata'='object'} into table t1;
ERROR 2 (HY000): File '/load_data/jsonline_object.jl' not found (OS errno 2 - No such file or directory)

压缩文件：
mysql> create table t9(a varchar, b varchar, c varchar, d varchar);
Query OK, 0 rows affected (0.04 sec)
mysql>  load data local infile {"filepath"="/Users/heni/load_data/parallel.txt.gz", "compression"="gzip"} into table t9 FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 2 (HY000): File '/Users/heni/load_data/parallel.txt.gz' not found (OS errno 2 - No such file or directory)
