### ISSUE TITLE
[Bug]: outer apply result is not correct

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#19988]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e39469a3031670cf763ceb0f09a56da138c35961

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1150" alt="企业微信截图_f5773f42-b5ef-4cef-8409-b29446e3c820" src="https://github.com/user-attachments/assets/5fb5d111-d58f-4f84-abd5-89bd38551bf5">

### Steps to Reproduce

```Markdown
drop table if exists t2;
create table t2(a int, b int);
insert into t2 values(1,2),(1,-1),(1,NULL),(NULL,NULL);

select * from t2 outer apply generate_series(t2.a, t2.b)g;
select * from generate_series(NULL,NULL)a;
```

**Comment by zengyan1** [comment]
fixed

**Comment by tom-csf** [comment]
验证已经bugfix
