### ISSUE TITLE
[Bug]: ut 'TestGlobalCheckpoint2' failed during ci test.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20008]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

adccbca9c12ee13247eff1b2b2846f2c6c7c02e1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/matrixone/actions/runs/11795227057/job/32854552746?pr=20007

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/ed03f89d-4ec8-4c6f-90e0-099b93ac3681">

log: [logs_30781101753 2.zip](https://github.com/user-attachments/files/17715803/logs_30781101753.2.zip)

### Steps to Reproduce

```Markdown
trigger ci test
```

**Comment by LeftHandCold** [comment]
fixed
