### ISSUE TITLE
[Bug]: restore report 'transaction error: workspace size is too large: 119702363'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2d913f39c358fc183110f5c246749273cf79308c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11796198755/job/32858307295

<img width="1387" alt="image" src="https://github.com/user-attachments/assets/ba5ee8d3-ecb0-4e42-bc95-a6444ac4ddaf">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22VQf%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-nightly-2d913f3-20241112%5C%22%7D%20%7C%3D%20%60transaction%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731418761000%22,%22to%22:%221731429601000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger snapshot restore workflow.

restore执行的sql：RESTORE ACCOUNT sys FROM SNAPSHOT sys_sp01

上一个正常的commit：6d2b6b7e207ce0f76ec8e09399bee26d5d469cfc
```

**Comment by YANGGMM** [comment]
@triump2020  麻烦看一下

**Comment by triump2020** [comment]
The restore transaction commits failed ,since the size of txn workspace size is larger than 100M ,then rollback.   

  It should be fixed by [PR](https://github.com/matrixorigin/matrixone/pull/20023)

**Comment by Ariznawlll** [comment]
今天会测试一下

**Comment by Ariznawlll** [comment]
main测试通过：

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11831233820

**Comment by Ariznawlll** [comment]
2.0-dev测试通过

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11849099548/job/33051440319
