### ISSUE TITLE
[Bug]: select * from table into outfile with stage oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20039]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

2f86fead2

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/e0d58b7e-518b-40d9-8644-cb0ee653f5d9">

heap profile: 
[CN_63633432-6432-3830-3966-616230623832_malloc_019324c0-ec5b-7d18-b5ab-e3e9b741bd32.gz](https://github.com/user-attachments/files/17729785/CN_63633432-6432-3830-3966-616230623832_malloc_019324c0-ec5b-7d18-b5ab-e3e9b741bd32.gz)
[CN_63633432-6432-3830-3966-616230623832_malloc_019324c0-7769-7b88-bb37-4125bfe94716.gz](https://github.com/user-attachments/files/17729790/CN_63633432-6432-3830-3966-616230623832_malloc_019324c0-7769-7b88-bb37-4125bfe94716.gz)

### Steps to Reproduce

```Markdown
基于分布式minio部署的mo

create stage stage01 url = 's3://mo-stagetest/test_stage' credentials = {"aws_key_id"='qa-admin',"aws_secret_key"='vFe5uNHbDTf3riZVZ4VeVNuE5GRGtOQeUhX6',"AWS_REGION"='us-east-2','PROVIDER'='minio', 'ENDPOINT'='http://10.222.6.6'};

drop database if exists tpch_10g;
use tpch_10g;

CREATE TABLE LINEITEM(
L_ORDERKEY    BIGINT NOT NULL,
L_PARTKEY     INTEGER NOT NULL,
L_SUPPKEY     INTEGER NOT NULL,
L_LINENUMBER  INTEGER NOT NULL,
L_QUANTITY    DECIMAL(15,2) NOT NULL,
L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
L_DISCOUNT    DECIMAL(15,2) NOT NULL,
L_TAX         DECIMAL(15,2) NOT NULL,
L_RETURNFLAG  VARCHAR(1) NOT NULL,
L_LINESTATUS  VARCHAR(1) NOT NULL,
L_SHIPDATE    DATE NOT NULL,
L_COMMITDATE  DATE NOT NULL,
L_RECEIPTDATE DATE NOT NULL,
L_SHIPINSTRUCT CHAR(25) NOT NULL,
L_SHIPMODE     CHAR(10) NOT NULL,
L_COMMENT      VARCHAR(44) NOT NULL,
PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

load data url s3option {'endpoint'='http://10.222.6.6','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-data', 'filepath'='tpch_10/lineitem.tbl', 'provider'='minio'} into table tpch_10g.lineitem fields terminated by '|' lines terminated by '\n' parallel 'true';

select * from lineitem into outfile 'stage://stage01/lineitem02.tbl';

ak and sk please contact me.
```

**Comment by reusee** [comment]
@Ariznawlll malloc只是堆外内存，看上去没什么异常，大部分是内存缓存。
还需要提供 heap profile，才能判断是哪里内存占用多

**Comment by Ariznawlll** [comment]
> @Ariznawlll malloc只是堆外内存，看上去没什么异常，大部分是内存缓存。 还需要提供 heap profile，才能判断是哪里内存占用多

ok, wait a minute

**Comment by Ariznawlll** [comment]
[CN_63633432-6432-3830-3966-616230623832_heap_0193250f-32c7-7ae3-8d02-3979bcec358b.gz](https://github.com/user-attachments/files/17730904/CN_63633432-6432-3830-3966-616230623832_heap_0193250f-32c7-7ae3-8d02-3979bcec358b.gz)
[CN_63633432-6432-3830-3966-616230623832_heap_0193250f-a7f8-7205-af0e-3736ef08155b.gz](https://github.com/user-attachments/files/17730907/CN_63633432-6432-3830-3966-616230623832_heap_0193250f-a7f8-7205-af0e-3736ef08155b.gz)

@reusee 飞哥，麻烦再帮忙看一下，谢谢

**Comment by cpegeric** [comment]
already changed the invalid alloc size message to a better one.  For OOM, please ask more relevant person to take a look. thanks

**Comment by reusee** [comment]
从heap profile看不出来什么，可能是分配速率忽然加快

**Comment by YANGGMM** [comment]
@Ariznawlll 麻烦再看看

**Comment by YANGGMM** [comment]
@ouyuanning 麻烦看一下

**Comment by aressu1985** [comment]
@reusee 请继续定位这个问题

**Comment by reusee** [comment]
进行中

**Comment by reusee** [comment]
fixed

**Comment by Ariznawlll** [comment]
```
测试步骤：

基于分布式minio部署的mo

create stage stage01 url = 's3://mo-stagetest/test_stage' credentials = {"aws_key_id"='qa-admin',"aws_secret_key"='vFe5uNHbDTf3riZVZ4VeVNuE5GRGtOQeUhX6',"AWS_REGION"='us-east-2','PROVIDER'='minio', 'ENDPOINT'='http://10.222.6.6'};

drop database if exists tpch_10g;
use tpch_10g;

CREATE TABLE LINEITEM(
L_ORDERKEY    BIGINT NOT NULL,
L_PARTKEY     INTEGER NOT NULL,
L_SUPPKEY     INTEGER NOT NULL,
L_LINENUMBER  INTEGER NOT NULL,
L_QUANTITY    DECIMAL(15,2) NOT NULL,
L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
L_DISCOUNT    DECIMAL(15,2) NOT NULL,
L_TAX         DECIMAL(15,2) NOT NULL,
L_RETURNFLAG  VARCHAR(1) NOT NULL,
L_LINESTATUS  VARCHAR(1) NOT NULL,
L_SHIPDATE    DATE NOT NULL,
L_COMMITDATE  DATE NOT NULL,
L_RECEIPTDATE DATE NOT NULL,
L_SHIPINSTRUCT CHAR(25) NOT NULL,
L_SHIPMODE     CHAR(10) NOT NULL,
L_COMMENT      VARCHAR(44) NOT NULL,
PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

load data url s3option {'endpoint'='http://10.222.6.6','access_key_id'='***','secret_access_key'='***','bucket'='mo-load-data', 'filepath'='tpch_10/lineitem.tbl', 'provider'='minio'} into table tpch_10g.lineitem fields terminated by '|' lines terminated by '\n' parallel 'true';

select * from lineitem into outfile 'stage://stage01/lineitem02.tbl';


```
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/a55fd0e0-1b57-4f9f-88f5-2440e52cf55b">

<img width="1651" alt="image" src="https://github.com/user-attachments/assets/361a7461-a20f-4bc2-99ce-958ca566ba67">


7.9G卸载测试通过
