### ISSUE TITLE
[Bug]: checkin regression bvt failed with sql 'select count(*) from t7 where i=2;'

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20045]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

25327d4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**job url: https://github.com/matrixorigin/matrixone/actions/runs/11813351017/job/32911018148**

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/6d6f4302-abd9-48e2-a242-7bcedd59823a">

执行bvt时的log：https://grafana.ci.matrixorigin.cn/goto/YyyIuYGHg?orgId=1

### Steps to Reproduce

```Markdown
trigger checkin regression.
```

**Comment by YANGGMM** [comment]
@zengyan1  麻烦看一下

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11829916077/job/32962625400?pr=20049

**Comment by daviszhen** [comment]
![image](https://github.com/user-attachments/assets/d445b78b-d707-4204-90eb-3305c20cbde0)

**Comment by LeftHandCold** [comment]
这个case流程 Merge start -> cn commit tombstone to tn -> LockMerge Bulk Delete -> Merge done -> LockMerge Bulk Delete Committed -> Merge commit.  这种你情况应该没有transfer

**Comment by daviszhen** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/11852156010/job/33029836876?pr=20114

**Comment by XuPeng-SH** [comment]
fixed
