### ISSUE TITLE
[Bug]: pitr+fulltext index, restore pitr  failed

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#20064]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

bd0368f0c140dc9eccc232adb28470467cd680e8

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1282" alt="企业微信截图_7d8a8d36-6129-4054-9de1-7a66365d3fd0" src="https://github.com/user-attachments/assets/b7088ab0-cfd3-4e7b-b4ca-a6c3c43c51ef">

### Steps to Reproduce

```Markdown
1、create  database test;
2、use test;
3、create pitr pitr01 for database test range 1 'y';
4、mysql> CREATE TABLE articles (
    -> id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    -> title VARCHAR(200),
    -> body TEXT,
    -> FULLTEXT (title,body));
5、insert into articles values (0,'hello world','Bill Gates');
6、select now()//time1
7、restore database test from pitr pitr01 'time1';
```

### Additional information

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22O2c%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-bd0368f-202411141029%5C%22%7D%20%7C%3D%20%60unclassified%20statement%20appears%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731552613000%22,%22to%22:%221731552913000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
```mysql
create  database test;
use test;
create pitr pitr01 for database test range 1 'y';
mysql> CREATE TABLE articles (
 id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
title VARCHAR(200),
body TEXT,
FULLTEXT (title,body));
insert into articles values (0,'hello world','Bill Gates');
select now();
```


```mysql
restore database test from pitr pitr01 'time1';
```

**Comment by YANGGMM** [comment]
related to #20036

**Comment by tom-csf** [comment]
验证ok
