### ISSUE TITLE
[Tech Request]: keep data sorted after load for tpch benchmark

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#20063]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
keep data sorted after load for tpch benchmark
```

**Comment by ouyuanning** [comment]
目前测试的情况看，当去掉 parallel 'true' 且写s3的时候，确实是会乱序的。
这个从生成的pipeline就已经决定了会乱序。

parallel 不是true的部分，我本地环境未复现
