### ISSUE TITLE
[Bug]: proxy crashed by panic: missing free: address 0x7f84c7848000, size 1048576 continuously during stability test on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20089]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

54abe24

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

 proxy crashed by panic: missing free: address 0x7f84c7848000, size 1048576 continuously during stability test on distributed mode

[github@mo-srv-128 stability-test]$ kubectl -n mo-54abe24-202411132335 get pod
NAME                                   READY   STATUS    RESTARTS      AGE
stability-regression-dis-dn-0          1/1     Running   0             22h
stability-regression-dis-log-0         1/1     Running   0             22h
stability-regression-dis-log-1         1/1     Running   0             22h
stability-regression-dis-log-2         1/1     Running   0             22h
stability-regression-dis-proxy-pbmj8   1/1     Running   6 (90m ago)   22h
stability-regression-dis-proxy-xsk58   1/1     Running   6 (81m ago)   22h
stability-regression-dis-tp-cn-c28fl   1/1     Running   0             22h
stability-regression-dis-tp-cn-fllrk   1/1     Running   0             22h
stability-regression-dis-tp-cn-j9v94   1/1     Running   0             22h

proxy log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GOe%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-54abe24-202411132335%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731572902834%22,%22to%22:%221731587861283%22%7D%7D%7D&schemaVersion=1&orgId=1

[proxy_panic.tar.gz](https://github.com/user-attachments/files/17749579/proxy_panic.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
没有复现出来问题，建议做一下二分

**Comment by daviszhen** [comment]
初步看Conn对象被gc时，Conn.Close方法没有被调用。

**Comment by daviszhen** [comment]
目前只能够分析出出问题的链接迁移过。在迁移时，分配了新iosession.

没找到具体的原因。

等proxy日志中增加goroutineid的pr合并进去后再跑。

复现后，看malloc panic的goroutineid 与 具体的transfer 的线程关联。

**Comment by daviszhen** [comment]
https://shanghai.idc.matrixorigin.cn:30001/d/cluster-detail-namespaced/cluster-detail-namespaced?orgId=1&var-namespace=mo-3d200c1-202411182331&var-account=All&var-interval=$__auto_interval_interval&var-cluster=.%2A&var-loki=loki&from=1731943800000&to=1731979800000

**Comment by daviszhen** [comment]
有些以前没出现过的panic。panic 的地方是txn client waiter 的引用计数 不对

1,restartTxn panic
2, commit panic
3, pipeline 里面的算子也会出现panic



https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22n3z%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-c93bbbdd1-20241119%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732046633167%22,%22to%22:%221732062261647%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
上次的panic是在transfer 时分配内存的。类似上面的这个图。

今天的malloc panic 跟上次 的还是 有区别的。 主要是新连接进proxy时，分配内存。


![Selection_266](https://github.com/user-attachments/assets/eef45f88-b3f3-4ed6-a4d7-2e6810ef93f5)

把proxy 建立连接后connid 与 goid 完整联系起来。
前几天的日志是 把tunnel和pipe goid 与 connid 联系起来了。只会在trasnfer会打印 tunnel和pipe goid

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
update on 11.23
[2.0-dev]
job link:  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11974614772
log link: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22E6f%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-c8b17ea96-20241122%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732328062040%22,%22to%22:%221732334293321%22%7D%7D%7D&schemaVersion=1&orgId=1

[main]
job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11974619880/job/33386837097
log link: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22E6f%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-c22bc3a09-20241122%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732330962683%22,%22to%22:%221732331708966%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
从2.0-dev的panic 日志中，初步分析 server conn handshake 失败后。没有完整清理server conn。

![image](https://github.com/user-attachments/assets/e8ff089c-3022-4726-8aab-35958095eb47)

![image](https://github.com/user-attachments/assets/897a92db-91fb-4136-b5c2-1daabeefe1f3)

![image](https://github.com/user-attachments/assets/3c8a7c06-90d2-4561-99c6-9630f8a92957)

![image](https://github.com/user-attachments/assets/a6dbf3ac-3362-4737-9567-0fbfebb41728)

![image](https://github.com/user-attachments/assets/03fd8330-56a4-4f44-a244-62fd9537371b)

![image](https://github.com/user-attachments/assets/7b7f1219-c685-4804-8ec1-723f2fa11309)

**Comment by aressu1985** [comment]
fixed
