### ISSUE TITLE
[Bug]: Fulltext search (composite primary key) with lineitem scale 1 data return empty result

### ISSUE THREAD

**Issue by cpegeric** [matrixorigin/matrixone#20092]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,2.0-dev

### Commit ID

895fb49772366a36851e3ce1fd674e7dc72478fa

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

I generate lineitem scale 1 data say lineitem_1g.tbl and cut the first 100 lines into lineitem_small.tbl.

both create the fulltext index and search the same phrase.   However, only lineitem_small table return non-zero results and scale 1 table result empty result

I also double check the number of answer return from fulltext_index_scan().  Both table return nonzero resutls. 

number of rows return from fulltext_index_scan():
lineitem_small return 2 rows
lineitem_1g result 10442 rows

<img width="1298" alt="image" src="https://github.com/user-attachments/assets/a3d26d88-227c-4672-b068-2b0ba1385a95">

It most likely have problem with composite primary in JOIN operation.  I tried using single primary key with bigint type and l_comment from lineitem_lg,  JOIN will work and return correct answer.  So, focus on the composite primary key for testing. 

<img width="836" alt="image" src="https://github.com/user-attachments/assets/22c46471-a43e-4739-91e5-0cad44cd3581">

### Expected Behavior

both lineitem_small and linitem_1g table should return non-zero results.

### Steps to Reproduce

```Markdown
CREATE TABLE `lineitem` (
  `l_orderkey` int NOT NULL,
  `l_partkey` int DEFAULT NULL,
  `l_suppkey` int DEFAULT NULL,
  `l_linenumber` int NOT NULL,
  `l_quantity` decimal(15,2) DEFAULT NULL,
  `l_extendedprice` decimal(15,2) DEFAULT NULL,
  `l_discount` decimal(15,2) DEFAULT NULL,
  `l_tax` decimal(15,2) DEFAULT NULL,
  `l_returnflag` char(1) DEFAULT NULL,
  `l_linestatus` char(1) DEFAULT NULL,
  `l_shipdate` date DEFAULT NULL,
  `l_commitdate` date DEFAULT NULL,
  `l_receiptdate` date DEFAULT NULL,
  `l_shipinstruct` char(25) DEFAULT NULL,
  `l_shipmode` char(10) DEFAULT NULL,
  `l_comment` varchar(44) DEFAULT NULL,
  `l_dummy` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`l_orderkey`,`l_linenumber`));

load data infile '/Users/eric/github/tpch-dbgen/lineitem-1g.tbl' into table lineitem_1g  FIELDS TERMINATED BY '|';

load data infile '/Users/eric/github/tpch-dbgen/lineitem-small.tbl' into table lineitem_small  FIELDS TERMINATED BY '|';

 create fulltext index ftidx on lineitem_small(l_comment);

 create fulltext index ftidx on lineitem_1g(l_comment);

select * from lineitem_1g where match(l_comment) against('"pending foxes"' in boolean mode);

select * from lineitem_small where match(l_comment) against('"pending foxes"' in boolean mode);
```

**Comment by badboynt1** [comment]
fixed

**Comment by tom-csf** [comment]
验证ok

**Comment by tom-csf** [comment]
验证已经bugfix @cpegeric 你那边关闭一下issue 我这边关闭不了
