### ISSUE TITLE
[Bug]: one cn crashed by oom after stability test on distributed mode about 6.5 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20128]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

51d8a25

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
2*PROXY: 3C 6G
- OS type:
- Others:
```

### Actual Behavior

one cn crashed by oom after stability test on distributed mode about 6.5 hours;
<img width="660" alt="image" src="https://github.com/user-attachments/assets/1c915101-7c59-4fda-8a31-0e75ce0332cb">

resource:
https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-51d8a25-202411160933&from=1731721296931&to=1731747363655
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/56947aa6-b9db-4efe-83cc-77cce87f72a4">

mo-log link:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22EKG%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-51d8a25-202411160933%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731743730324%22,%22to%22:%221731744154674%22%7D%7D%7D&schemaVersion=1&orgId=1

heap:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22EKG%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-51d8a25-202411160933%5C%22,%20pod%3D%5C%22stability-regression-dis-tp-cn-z56qv%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221731743730000%22,%22to%22:%221731744031000%22%7D%7D%7D&schemaVersion=1&orgId=1

[11-16-2024-17-42-41_files_list.zip](https://github.com/user-attachments/files/17784161/11-16-2024-17-42-41_files_list.zip)

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by sukki37** [comment]
<img width="1747" alt="image" src="https://github.com/user-attachments/assets/8927e82f-b8e8-4cf5-873a-2786d0503812">

**Comment by daviszhen** [comment]
profile显示是 ctx 没有被清理掉。

![image](https://github.com/user-attachments/assets/b128e14d-d3ca-44b3-ba81-3a20f326df58)

**Comment by aressu1985** [comment]
fixed
