### ISSUE TITLE
[Feature Request]: Implement MySQL CRC32() function

### ISSUE THREAD

**Issue by charleschile** [matrixorigin/matrixone#20121]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

CRC32() function is important in data migration and data comparison. It can be used to compare whether the data in two databases is the same: if the CRC32 sums are identical in both databases, the data in these columns is likely unchanged during data migration.

It can be used as below to check whether two columns from two databases are the same:
```sql
select (sum(crc32(concat_ws(',',`o_orderkey`,`o_custkey`,`o_orderstatus`,format( `o_totalprice`, 2),`o_orderdate`,`o_orderpriority`,`o_clerk`,`o_shippriority`,`o_comment`)) )) as `columns_md5__` from `tpch`.`orders` where 1=1        and ((`o_orderkey` >= 1)) and ((`o_orderkey` < 400001))
```

### Describe the feature you'd like

Follow https://www.w3resource.com/mysql/mathematical-functions/mysql-crc32-function.php

**Comment by Ariznawlll** [comment]
能转换为字符串类型的与高老师商量，先不考虑crc32函数对其的支持

**Comment by allengaoo** [comment]
this feature has been validated and online doc has been released.
