### ISSUE TITLE
[Bug]: table with fulltext index ,delete from table where xxx failed

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#20149]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

b574c1098839922efb290fdf48d203b6a35fe808

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="778" alt="image" src="https://github.com/user-attachments/assets/6705965f-bf54-44e4-a96d-ed34a683208e">

### Steps to Reproduce

```Markdown
load tpch 1g data to tpch_1g database
create table nation3 like nation;
insert into nation3 select * from nation;
set experimental_fulltext_index=1;
create fulltext index fdx9 on nation3(N_COMMENT);
delete from nation3 where n_nationkey = 10;
```

### Additional information

https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22O2c%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-b574c10-202411181405%5C%22%7D%20%7C%3D%20%60anic%20this%20error%20should%20not%20be%20logged%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731919813000%22,%22to%22:%221731919933000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by cpegeric** [comment]
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/8e67ea01-e9e0-4acb-9368-c4d42affd5ad">

**Comment by jiangxinmeng1** [comment]
The type of primary key vector in delete batch doesn't match the index table. The primary key is bigint unsign, while the pk in delete batch is int
<img width="512" alt="企业微信截图_17319834958753" src="https://github.com/user-attachments/assets/1a35562a-5208-46b8-ad5c-7a7522aeb8a0">

the Table Scan result is correct, primary key is bigint unsign
![屏幕截图 2024-11-19 150015](https://github.com/user-attachments/assets/43955faf-75ff-4c6d-9886-c6f777bae63e)

**Comment by XuPeng-SH** [comment]
@cpegeric It looks like the pk type used for the secondary index table deletion is incorrectly using the pk type of the original table.

**Comment by tom-csf** [comment]
2.0-dev分支验证ok

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
**2.0-dev: 4b6c0c1ee**

```
测试case：
load tpch 1g data to tpch_1g database
create table nation3 like nation;
insert into nation3 select * from nation;
set experimental_fulltext_index=1;
create fulltext index fdx9 on nation3(N_COMMENT);
delete from nation3 where n_nationkey = 10;
```

<img width="936" alt="image" src="https://github.com/user-attachments/assets/351db25d-c2e4-4eb4-9301-0f5eb33cfa5c">

**Comment by Ariznawlll** [comment]
<img width="228" alt="image" src="https://github.com/user-attachments/assets/08ee5e30-daa6-4bc5-9b9e-de2f06af1b5e">

main测试通过✅

**Comment by Ariznawlll** [comment]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/9f816288-12ec-4ea8-a5ac-b2e1f59d532e">
main测试通过
