### ISSUE TITLE
[Bug]: Restore from account1 to account2 failed

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#20144]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

v2.0.0-78f88591b-2024-11-17

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Restore from a snapshot of account1 to account 2 failed:
```
mysql> restore account `01929da4-89af-7ed8-8f32-8df9ed5ddd71` FROM snapshot metadb202411181350 TO account `0192fbbb-bfb0-7d54-a2fe-b7fd26dbdb14`;

ERROR 1105 (HY000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 25 near " lock";
```

### Expected Behavior

Restore succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
钊哥 @YANGGMM 帮忙描述一下root cause

**Comment by YANGGMM** [comment]
@Ariznawlll The reason is that the table name and database name are keywords, and then an error is reported when the recovery is performed, please add a test for the table name and database name keywords.

**Comment by Ariznawlll** [comment]
test done.

**Comment by Ariznawlll** [comment]
main与2.0-dev均验证通过
