### ISSUE TITLE
[Bug]: create index executed about 3h+.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20156]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

f22612cd96534605b8f351755e4777253c136f41

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11879559687/job/33108190793

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/a21f108c-3788-4e29-9057-b4db4bd989d3">

longrunning日志：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22_fY%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-nightly-f22612c-20241117%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221731883916000%22,%22to%22:%221731901189000%22%7D%7D%7D&schemaVersion=1&orgId=1

longrunning对应的profile：
[profile1118.zip](https://github.com/user-attachments/files/17810370/profile1118.zip)

### Steps to Reproduce

```Markdown
trigger big data regression on tke
```

**Comment by sukki37** [comment]
Please provide the goroutine stack related to long-running tasks. @Ariznawlll

**Comment by Ariznawlll** [comment]
下次出现再打开
