### ISSUE TITLE
[Bug]:select   src table (with  primary key load twice data) with duplicate data insert into dst table(with primary key and fulltext index ),dst primary key invalid

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#20152]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

b574c1098839922efb290fdf48d203b6a35fe808

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/c1da384c-4b56-4f80-9a53-85026ce32b1e">

### Steps to Reproduce

```Markdown
1、
CREATE TABLE `lineitem` (
  `L_ORDERKEY` bigint NOT NULL,
  `L_PARTKEY` int NOT NULL,
  `L_SUPPKEY` int NOT NULL,
  `L_LINENUMBER` int NOT NULL,
  `L_QUANTITY` decimal(15,2) NOT NULL,
  `L_EXTENDEDPRICE` decimal(15,2) NOT NULL,
  `L_DISCOUNT` decimal(15,2) NOT NULL,
  `L_TAX` decimal(15,2) NOT NULL,
  `L_RETURNFLAG` varchar(1) NOT NULL,
  `L_LINESTATUS` varchar(1) NOT NULL,
  `L_SHIPDATE` date NOT NULL,
  `L_COMMITDATE` date NOT NULL,
  `L_RECEIPTDATE` date NOT NULL,
  `L_SHIPINSTRUCT` char(25) NOT NULL,
  `L_SHIPMODE` char(10) NOT NULL,
  `L_COMMENT` varchar(44) NOT NULL,
  PRIMARY KEY (`L_ORDERKEY`,`L_LINENUMBER`)
)
2、load tpch 1g data to database lineitem table
3、create fulltext index fdx on lineitem(L_COMMENT) //create fulltext on lineitem
4、load tpch 1g data to database lineitem table
5、create lineitem11 with fulltext
     create lineitem12 without fulltext
6、insert into lineitem11 select * from lineitem where l_orderkey = 5318082 and l_linenumber = 1;//success （priamry key is invalid）
 insert into lineitem12 select * from lineitem where l_orderkey = 5318082 and l_linenumber = 1;
//failed
```

**Comment by cpegeric** [comment]
When Insert without index,  JOIN is performed.
<img width="1707" alt="image" src="https://github.com/user-attachments/assets/78511f02-a689-491b-b474-593e23a5abc0">


When Insert with index,  there is NO DEDUP JOIN

<img width="1865" alt="image" src="https://github.com/user-attachments/assets/b0915beb-8c04-4e16-a368-8736f953fd54">

**Comment by cpegeric** [comment]
<img width="640" alt="image" src="https://github.com/user-attachments/assets/4e8a1df8-b64d-469d-b66a-2a518b927e98">


so, I think this is not a bug for fulltext index... instead, it should be the bug in load data without dedup check....  and it seems to me load data without dedup check is a default behaviour.

**Comment by ouyuanning** [comment]
根因是：
1、目前新的DML重构的plan还不支持fulltext index的表的DML，所以走的是旧的plan
2、旧的plan的去重针对输入数据能保证唯一的时候，不对输入的数据进行去重。只比较输入数据与历史数据是否有重复.
      这里第一次执行：
      insert into lineitem12 select * from lineitem where l_orderkey = 5318082 and l_linenumber = 1;  
      因为 lineitem 表是有pk的，所以build plan的时候会认为输入的数据是满足约束的，所以不对输入数据进行去重。而lineitem12表是空表，所以没有数据跟输入数据进行去重比较，故这里没有报错。

       第二次的时候。fuzzy filter一样不会对输入数据进行检查。但是把输入数据作为runtime filter的数值传递给runtime filter。 最后从左表（lineitem12）经过runtime filter后拿数据的时候，拿不到数据（这里可能有bug）。于是这一次，fuzzy filter依然没有捕获到重复。进行了commit。TN在处理commit数据的时候，对新commit数据和旧数据进行去重时候发现了重复，于是报错。

**Comment by badboynt1** [comment]
runtime filter没有问题，问题出在fuzzyfilter地下的scan算子，没有能查出未落盘的数据 
@ouyuanning

**Comment by ouyuanning** [comment]
OOM的问题看heap应该是跟
https://github.com/matrixorigin/MO-Cloud/issues/4443  是一个问题

insert时fuzzy没有报错，tn报错的部分。目前来看在左表的table_scan就没有查出数据来。需要debug进reader继续看看。
等锦赛有时间，找锦赛帮忙看吧

**Comment by jensenojs** [comment]
基于有无index走是否是新plan的前提, 胜峰哥和国亮哥的sql我理解都是符合我现在对mo行为的理解的. 

- 对于没有fulltext index的表
  - 走新plan, 用join
    - 在空表insert into select的时候就报错, 因为select from的数据就是有重复的
      - 应该不是TN报错, TN对于主键的报错是没有反序列化的
- 对于有fulltext index的表
  - 走老plan, 用fuzzy
    - 对于select from 的表有pk, 跳过检测, 所以给它插进去了

> 根因是： 1、目前新的DML重构的plan还不支持fulltext index的表的DML，所以走的是旧的plan 2、旧的plan的去重针对输入数据能保证唯一的时候，不对输入的数据进行去重。只比较输入数据与历史数据是否有重复. 这里第一次执行： insert into lineitem12 select * from lineitem where l_orderkey = 5318082 and l_linenumber = 1; 因为 lineitem 表是有pk的，所以build plan的时候会认为输入的数据是满足约束的，所以不对输入数据进行去重。而lineitem12表是空表，所以没有数据跟输入数据进行去重比较，故这里没有报错。 第二次的时候。fuzzy filter一样不会对输入数据进行检查。但是把输入数据作为runtime filter的数值传递给runtime filter。 最后从左表（lineitem12）经过runtime filter后拿数据的时候，拿不到数据（这里可能有bug）。于是这一次，fuzzy filter依然没有捕获到重复。进行了commit。 TN在处理commit数据的时候，对新commit数据和旧数据进行去重时候发现了重复，于是报错。

**Comment by jensenojs** [comment]
更小的复现sql

```sql
select mo_ctl('cn', 'task', 'disable');
drop database if exists db1;
create database db1;
use db1;
create table t0 (
  a int,
  b int,
  c varchar(20),
  primary key(a, b)
);
insert into t0 select result, result, result || 'test' from generate_series(1, 100) g;
set experimental_fulltext_index=1;
create fulltext index ftidx on t0 (c);
create table t1 (
  a int,
  b int,
  c varchar(20),
  primary key(a, b)
);

set experimental_fulltext_index=1;
create fulltext index ftidx on t1 (c);
insert into t1 select * from t0 where a = 1 and b = 1;
```

在第二次执行`insert into t1 select * from t0 where a = 1 and b = 1;`的时候, 预期CN报错. 但TN报错

**Comment by ouyuanning** [comment]
如果有表t1, 和表t2。 他们的schema都类似：  create table t_x(a int primary key, b int);
那么对于  insert into t1 select * from t2
我是建议对于这个insert过程，是没有必要对 t2输出的数据做去重的。因为t2本身就保证了唯一性。而只需要比较 t1原数据跟新进来的t2数据做去重。

不应该因为load不做去重，引起的t2的pk重复这种问题而增加额外的消耗。

**Comment by ouyuanning** [comment]
@allengaoo 高老师确认一下吧

**Comment by allengaoo** [comment]
从产品的角度看，建议如下：
1.   insert into t1 as select * from t2  这种情况，如果t2 表中存在主键，那么在insert into 的时候就不需要在验证t2 中的数据重复了，而只需要验证t1 和 t2 的数据是否重复就可以了。

2. 对于load data 命令，建议默认情况下对源文件中的数据进行去重检查。并提供是否进行去重检查的开关。

**Comment by ouyuanning** [comment]
那建议在 https://github.com/matrixorigin/MO-Cloud/issues/3642  这里跟踪吧

**Comment by tom-csf** [comment]
ok
