### ISSUE TITLE
[Bug]: Func `cosine_similarity` won't work properly with parameterized query

### ISSUE THREAD

**Issue by LHQ-MO** [matrixorigin/matrixone#20181]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

v2.0.0

### Commit ID

0bbda66

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type: by Docker
- Others: image tag：matrixorigin/matrixone:2.0.0
```

### Actual Behavior

When using  vector with text format as a parameter
```go
db.Query(`SELECT id, cosine_similarity(vector, ?) FROM vector_test`, "[1,2,3]")
```
It returns with error like:
```
failed to query the database: Error 20203 (HY000): invalid argument function cosine_similarity, bad value [VECF32 TEXT]
```

### Expected Behavior

It's expected to work properly like
```mysql
SELECT id, cosine_similarity(vector, "[1,2,3]") FROM vector_test
```

### Steps to Reproduce

Create a table and insert data:

```mysql
CREATE TABLE `vector_test` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vector vecf32(3)
);
INSERT INTO `vector_test` VALUES(1,"[1,2,4]");
```

Then do a query with golang:
```go
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?&parseTime=true",
		"root",
		"111",
		"localhost",
		6001,
		"demo")
	db, _ := sql.Open("mysql", dsn)

	rows, err := db.Query(`SELECT id, cosine_similarity(vector, ?) FROM vector_test`, "[1,2,3]")
	if err != nil {
		log.Fatalf("failed to query the database: %v", err)
		return
	}
```

### Additional information

A walkaround for this issue is using `CAST` with the parameter like this:
``` go
db.Query(`SELECT id, cosine_similarity(vector, CAST(? AS VECF32)) FROM vector_test`, "[1,2,3]")
```

BTW variables in SQL also encounter this:
```mysql
SET @v = "[1,2,4]";
SELECT id, cosine_similarity(vector, @v) from vector_test;
```

**Comment by aronchanisme** [comment]
@aunjgr  vector related, pls kindly take a look, thx

**Comment by ouyuanning** [comment]
没有自动把 string（"[1,2,3]"） cast 成vecf32。应该加一下就好了

**Comment by zengyan1** [comment]
fixed

**Comment by Ariznawlll** [comment]
**测试步骤：**

**main**
```
mysql> select git_version();
+---------------+
| git_version() |
+---------------+
| e08cd95ce     |
+---------------+
1 row in set (0.00 sec)

mysql -h 127.0.0.1 -P 6001 -udump -p111
create database test;
use test;
CREATE TABLE `vector_test` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vector vecf32(3)
);
INSERT INTO `vector_test` VALUES(1,"[1,2,4]");
INSERT INTO `vector_test` VALUES(2,"[3,2,4]");
```

**运行脚本**
<img width="1752" alt="image" src="https://github.com/user-attachments/assets/1080cf89-1e8d-414a-bbe1-9360d5fea72b">
```
 SET @v = "[1,2,4]";
 SELECT id, cosine_similarity(vector, @v) from vector_test;
```
<img width="666" alt="image" src="https://github.com/user-attachments/assets/4e30cddc-0b80-4270-9b4c-af163692fa76">

**结论：main测试通过**


**2.0-dev**
```
mysql>  select git_version();
+---------------+
| git_version() |
+---------------+
| 31cdef2f9     |
+---------------+
1 row in set (0.00 sec)
```
**运行脚本：**
<img width="1694" alt="image" src="https://github.com/user-attachments/assets/fde56daa-93e8-4c6e-95fe-7c245396cdc8">
<img width="748" alt="image" src="https://github.com/user-attachments/assets/57bdf3e7-3106-44b2-9fb8-1990f0874023">


结论：2.0-dev测试通过
