### ISSUE TITLE
[Feature Request]: Math Function sin()

### ISSUE THREAD

**Issue by fansehep** [matrixorigin/matrixone#2018]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Similar to MySQL 8.0 in syntax.
Function syntax
sin(int) and sin(float)
Returns the sine of the argument

**Comment by dengn** [comment]
> ### Is there an existing issue for the same feature request?
> * [x]  I have checked the existing issues.
> 
> ### Is your feature request related to a problem?
> _No response_
> 
> ### Describe the feature you'd like
> Similar to MySQL 8.0 in syntax. Function syntax sin(int) and sin(float) Returns the sine of the argument
> 
> ### Describe implementation you've considered
> _No response_
> 
> ### Documentation, Adoption, Use Case, Migration Strategy
> _No response_
> 
> ### Additional information
> _No response_

Hi @fansehep , thanks for your interest for the event. Please choose another unassigned issue, as this sin() issue has been assigned to another developer.
