### ISSUE TITLE
[Bug]: chaos test kill dn，cn restart too

### ISSUE THREAD

**Issue by tom-csf** [matrixorigin/matrixone#20200]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

cc1b453d207bbac17bc83958cc3d25c9119e61f0

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cn is unnormal restart
<img width="1226" alt="企业微信截图_4f2c03a2-6f08-405c-9c50-34c9f568d432" src="https://github.com/user-attachments/assets/1383da82-239f-4d0f-8272-e06add596ca4">

### Steps to Reproduce

```Markdown
1、kill dn pod
2、kubectl get pod -n <ns>
```

**Comment by tom-csf** [comment]
<img width="905" alt="image" src="https://github.com/user-attachments/assets/9f5f489b-5260-4afe-9793-bddf7a6d8ef5">

**Comment by volgariver6** [comment]
fixed

**Comment by tom-csf** [comment]
验证ok
