### ISSUE TITLE
[Bug]: [1120 snapshot regression] snapshot restore account failed with 'failed: Error 20101 (HY000): internal error: panic this error should not be logged: EOF: '

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20206]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

bd3ee587535e8262810d424b5d0b25df3872ec42

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:

上一个跑的正常的commit：6177e47b86fc616919c83370344777ab303dd0bf
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11914987146/job/33233255950

2024/11/20 01:34:30.734802 +0000 DEBUG snapshot/restore_snapshot.go:32 run restore snapshot...
2024/11/20 01:34:30.734819 +0000 DEBUG connect/connect.go:33 dsn: dump:******@tcp(172.16.17.187:[60](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11914987146/job/33233255950#step:20:61)01)/?timeout=30s
2024/11/20 01:34:30.742230 +0000 DEBUG snapshot/restore_snapshot.go:109 check account exist or not, check account exist sql: SELECT ACCOUNT_NAME FROM MO_CATALOG.MO_ACCOUNT WHERE ACCOUNT_NAME = 'acc03'
2024/11/20 01:34:30.866813 +0000 DEBUG snapshot/restore_snapshot.go:123 create new account, create account sql: CREATE ACCOUNT IF NOT EXISTS acc03 ADMIN_NAME 'test_account' IDENTIFIED BY '111'
2024/11/20 01:34:31.378360 +0000 DEBUG snapshot/restore_snapshot.go:131 start restore to new account, restore snapshot sql: RESTORE ACCOUNT acc02 FROM SNAPSHOT acc02_sys TO ACCOUNT acc03
[mysql] 2024/11/20 03:37:38 connection.go:49: unexpected EOF
2024/11/20 03:37:38.413[61](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11914987146/job/33233255950#step:20:62)4 +0000 ERROR snapshot/restore_snapshot.go:134 restore snapshot failed: invalid connection
2024/11/20 03:37:38.413676 +0000 DEBUG snapshot/restore_snapshot.go:136 start to drop account, drop account sql: DROP ACCOUNT IF EXISTS acc03
Error: invalid connection
2024/11/20 03:37:55.157315 +0000 ERROR snapshot/restore_snapshot.go:139 drop account failed: Error 20101 (HY000): internal error: panic this error should not be logged: EOF: 
github.com/matrixorigin/matrixone/pkg/logutil.ErrorField
	/go/src/github.com/matrixorigin/matrixone/pkg/logutil/fields.go:43
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:515
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:494
github.com/matrixorigin/matrixone/pkg/frontend.rollbackTxnFunc
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:71
github.com/matrixorigin/matrixone/pkg/frontend.finishTxnFunc
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/txn.go:129
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2481
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2564
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2453
github.com/matrixorigin/matrixone/pkg/frontend.doComQueryInBack
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_exec.go:429
github.com/matrixorigin/matrixone/pkg/frontend.(*backExec).Exec
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/back_exec.go:159
github.com/matrixorigin/matrixone/pkg/frontend.doDropAccount.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:3656
github.com/matrixorigin/matrixone/pkg/frontend.doDropAccount
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:3846
github.com/matrixorigin/matrixone/pkg/frontend.handleDropAccount
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:1255
github.com/matrixorigin/matrixone/pkg/frontend.execInFrontend
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/self_handle.go:237
github.com/matrixorigin/matrixone/pkg/frontend.executeStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2688
github.com/matrixorigin/matrixone/pkg/frontend.dispatchStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2649
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithIncrStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2618
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithWorkspace
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:25[62](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11914987146/job/33233255950#step:20:63)
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithTxn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2453
github.com/matrixorigin/matrixone/pkg/frontend.executeStmtWithResponse
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2416
github.com/matrixorigin/matrixone/pkg/frontend.doComQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3050
github.com/matrixorigin/matrixone/pkg/frontend.ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3127
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:298
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:385
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:516
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleMessage
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:484
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleLoop
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:212
github.com/matrixorigin/matrixone/pkg/frontend.(*MOServer).handleConn
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/server.go:208
runtime.goexit
	/usr/local/go/src/runtime/asm_amd[64](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11914987146/job/33233255950#step:20:65).s:1700
2024/11/20 03:37:55.157397 +0000 ERROR snapshot/restore_snapshot.go:97 restore snapshot failed: invalid connection
2024/11/20 03:37:55.157521 +0000 DEBUG snapshot/restore_snapshot.go:35 restore snapshot failed
Error: Process completed with exit code 1.

log(UTC时间): https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22hXw%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-nightly-bd3ee58-20241119%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732066470000%22,%22to%22:%221732073875000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger snapshot restore workflow
```

**Comment by aronchanisme** [comment]
Snapshot issue. Hi @daviszhen , could you please kindly take a look? Thanks.

**Comment by xzxiong** [comment]
![image](https://github.com/user-attachments/assets/776ed812-98ee-4e0f-bfca-e6011bbb334f)

**Comment by daviszhen** [comment]
pr 已经merge

**Comment by Ariznawlll** [comment]
**commit： 3a92f10ccac09e302618568bd0184f10b80f1d51**

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11951964877/job/33356624135

今天测试没出现这个问题，先降级，后续再跑跑观察一下

**Comment by Ariznawlll** [comment]
测试通过

https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11974690576/job/33387127347
