### ISSUE TITLE
[Bug]: bvt  'create account acc01 admin_name = 'test_account' identified by '111'' failed with 'MO does not return result in 300000 ms.';

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20223]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

Ariznawlll

### Commit ID

6d2585f09977852892121918ec4ec9ca2d787702

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job :https://github.com/matrixorigin/matrixone/actions/runs/11931636600/job/33254904870?pr=20221

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/8de24786-b9ad-4aef-a061-07716dc1839d">

log: https://github.com/matrixorigin/matrixone/actions/runs/11931636600?pr=20221 
<img width="1420" alt="image" src="https://github.com/user-attachments/assets/2189af53-58ed-4cdb-afb0-a231223c743f">

The log is too huge, please scroll to the bottom to download it yourself.

### Steps to Reproduce

```Markdown
trigger ci test
```

**Comment by zengyan1** [comment]
repro
https://github.com/matrixorigin/matrixone/actions/runs/11930414384/job/33251155207?pr=20209

**Comment by YANGGMM** [comment]
<img width="893" alt="image" src="https://github.com/user-attachments/assets/59981646-45a0-4384-8e0c-5cb2e29b6941">

**Comment by YANGGMM** [comment]
{"level":"INFO","time":"2024/11/20 11:17:15.602606 +0000","name":"cn-service.lockservice","caller":"lockservice/service.go:607","msg":"bind created","service":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","uuid":"dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","service":"1732100634646590301dd1dccb4-4d3c-41f8-b482-5251dc7a41bf","remote":false,"bind":"10031-2357591721300748285(2357591721300748285)-1732100634646590301dd1dccb4-4d3c-41f8-b482-5251dc7a41bf-1732100634621988123"}
panic: missing free for type: *lockservice.waiter, 70f70f4866a9b62a1809a859a375d47b-0xc04a0ee8f0(1) 
	 create by: <<<>>>
	

goroutine 3 [running]:
github.com/matrixorigin/matrixone/pkg/common/reuse.(*checker[...]).gc(0x5857c20, 0xc04a0ee8f0)
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/checker.go:133 +0x1de
github.com/matrixorigin/matrixone/pkg/common/reuse.newSyncPoolBased[...].func1.1()
	/home/runner/work/matrixone/matrixone/head/pkg/common/reuse/sync_pool_based.go:48 +0x65

**Comment by YANGGMM** [comment]
@zhangxu19830126 麻烦看一下

**Comment by sukki37** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/19913
