### ISSUE TITLE
[Bug]: Error is reported for `SAVEPOINT`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#20273]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

v2.0.1-f1c26457b-2024-11-19

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
Error 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 9 near \"SAVEPOINT sp0x2573d40\";
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

Cloud dev env

**Comment by daviszhen** [comment]
增加savepoint,release savepoint,rollback to savepoint 语法支持。

按 @fengttt 的建议 rollback to savepoint 会报错处理。

实际功能要单独开发
