### ISSUE TITLE
[Tech Request]: analyzer 添加 memCache 、disk cache 读和命中统计

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#20278]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
目前 TableScan 耗时不明确，希望增加 cache 命中的情况
ref: https://github.com/matrixorigin/MO-Cloud/issues/4460#issuecomment-2492793787
```

### Why is this needed ?

> > yuesheng:
> > @武喜亮(qingxinhome)
> > https://github.com/matrixorigin/matrixone/blob/94f6175e081b8759b4411044cc569859f054515a/pkg/perfcounter/counter_set.go#L40 可以把perfcounter里的这些统计也加到analyzer里吗？内存缓存和磁盘缓存的读次数和命中次数
> 
> ref： [matrixorigin/matrixone#20278](https://github.com/matrixorigin/matrixone/issues/20278)

**Comment by qingxinhome** [comment]
This requirement has already been implemented

**Comment by aressu1985** [comment]
TEST DONE
