### ISSUE TITLE
[Bug]: [date 11.21] standalone regression: main branch gist960 dim create vector index performance  degradation

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20299]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

914d89b49830865bb71562fd346b9b642cdc1589

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

main 分支gist960 dim的vector create index lists=2000耗时57min+，2.0-dev分支耗时7min左右
main(commit: 914d89b49830865bb71562fd346b9b642cdc1589)：耗时57min+
<img width="1004" alt="企业微信截图_c2d8ce05-cea9-4d89-b545-f46ab066e8b4" src="https://github.com/user-attachments/assets/a4eaab83-3b40-4d72-b280-9f6c9c94800a">
job:https://github.com/matrixorigin/mo-auto-test/actions/runs/11955271110/job/33327583505

2.0-dev分支(commit: 4bcc5ade6bddb6ac7027af5928e866444a52ab0f):耗时7min左右
<img width="1079" alt="企业微信截图_3dbf115a-3063-4e03-89c7-01bdc94018f2" src="https://github.com/user-attachments/assets/b7148ff1-3a0b-4436-b19c-7b31091ecdc6">
job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11955253958/job/33327503978

create index sql: CREATE INDEX ivf_2000 USING ivfflat on items (embedding) op_type 'vector_l2_ops'  lists=2000;

main create vector index时profile：
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_0193522c-889e-703b-9c44-df555fdb7460.gz](https://github.com/user-attachments/files/17866866/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_0193522c-889e-703b-9c44-df555fdb7460.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_0193522c-81a4-7aa6-a6ee-a4a7fc9156c9.gz](https://github.com/user-attachments/files/17866903/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_0193522c-81a4-7aa6-a6ee-a4a7fc9156c9.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_0193522c-87fd-77f1-a181-d93084053fff.gz](https://github.com/user-attachments/files/17866904/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_0193522c-87fd-77f1-a181-d93084053fff.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_0193522c-c3f2-74d4-8636-a350b55be992.gz](https://github.com/user-attachments/files/17866909/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_0193522c-c3f2-74d4-8636-a350b55be992.gz)

### Steps to Reproduce

```Markdown
sql:
CREATE TABLE items (id int primary key, embedding vecf32(960));
source gist960.sql # contact me
SET @@experimental_ivf_index = 1;
CREATE INDEX ivf_2000 USING ivfflat on items (embedding) op_type 'vector_l2_ops'  lists=2000;
```

**Comment by heni02** [comment]
2.0-dev 分支测试时profile：
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_0193526b-9c84-78f6-87cb-2e1b71877fac.gz](https://github.com/user-attachments/files/17867209/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_0193526b-9c84-78f6-87cb-2e1b71877fac.gz)

**Comment by huby2358** [comment]
<img width="649" alt="企业微信截图_f6fcb4e8-1209-4ea7-8764-583677c20e4b" src="https://github.com/user-attachments/assets/6d0c9fc2-bed4-4872-83a8-396bcc46d350">
本地没有复现

**Comment by huby2358** [comment]
<img width="1667" alt="企业微信截图_ecdc21a7-5c48-4e2c-924b-d16bbcf11772" src="https://github.com/user-attachments/assets/00ce85f7-20d0-4ca7-be4c-bc9fa30cdae8">
这是环境上2.0-dev跑的快的抓的profile，
<img width="1659" alt="企业微信截图_6251d5cf-9e30-4b72-9037-393a421729b3" src="https://github.com/user-attachments/assets/a62cebeb-290e-4027-a5f0-6a7326d70391">
这是main分支跑的慢 抓的profile
两个cpu占比区别很大
明天打印一下pipeline看一下区别

**Comment by huby2358** [comment]
<img width="1399" alt="企业微信截图_69e1fbb7-c256-43a5-a4ee-14a84f13ea38" src="https://github.com/user-attachments/assets/0fdcb0af-b008-4603-97a9-24f24bf4c122">
这个是在深圳机器跑的快的版本的pipeline， mcpu是16
<img width="1098" alt="企业微信截图_8c296c1b-5676-42f2-a9ed-73d16c65ecfb" src="https://github.com/user-attachments/assets/0b821bb4-205c-4615-85c4-3a3b8c88dc7b">
这个是在129上跑的慢的版本，mcpu是1
还需要定位为啥129跑出来mcpu是1

**Comment by huby2358** [comment]
<img width="1184" alt="企业微信截图_9a4489bb-439d-4076-9426-f02f271a2080" src="https://github.com/user-attachments/assets/5410b1ed-54be-41d4-b349-ebdcac05e6fb">
<img width="790" alt="企业微信截图_9b7b9e74-d968-4348-8dbc-208935eb3de9" src="https://github.com/user-attachments/assets/be37cb3f-c771-4725-8988-98eaaf3107b3">
从上面两个截图，之前没发现，pipeline打印一个是tp一个是ap， tp mcpu返回是1

**Comment by huby2358** [comment]
<img width="1068" alt="企业微信截图_d860ac45-5604-4ad2-8a23-e2094fb07639" src="https://github.com/user-attachments/assets/d4923f81-1b08-453b-b4a9-08d35e6e8cec">
129跑的慢的， table scan node的block num
<img width="1022" alt="企业微信截图_0fd16b4c-9af9-4609-a670-6f35dc6b18f5" src="https://github.com/user-attachments/assets/2a1f7009-727a-4d5e-b694-09b466140025">
深圳机器跑的
table scan node上面的block num和cost不一样，导致GetExecType走的不同分支，一个是ap一个tp

**Comment by huby2358** [comment]
<img width="428" alt="企业微信截图_f07ea463-2a7b-4abe-bb97-986ac63609fe" src="https://github.com/user-attachments/assets/1718f278-b6fc-4615-a812-ea5f03d2cc9c">
在nitao修改的pr调整stats后，再跑时间正常

**Comment by heni02** [comment]
main create index性能已恢复
job：https://github.com/matrixorigin/mo-auto-test/actions/runs/12121416720/job/33792573065
![image](https://github.com/user-attachments/assets/c80e62c2-7551-44f3-87fc-c3f78352b7f2)
