### ISSUE TITLE
[Bug]: lots of txn timeout and "context deadline exceeded" error during tpcc 100-1000 on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20319]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

89ca354d6

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN : 16C 64G
1*DN : 16C 64G
3*LOG : 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/11984331868/job/33415285535
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/af192783-ae96-41b4-b23c-174fe3ec7a43">

mo-log:
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22E6f%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-89ca354d6-20241123%5C%22%7D%20%7C%3D%20%60context%20deadline%20exceeded%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732351177897%22,%22to%22:%221732351593067%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
run tpcc 100 1000 benchmark test
```

**Comment by ouyuanning** [comment]
有大量这个报错
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22E6f%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-89ca354d6-20241123%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732351177897%22,%22to%22:%221732351593067%22%7D%7D%7D&schemaVersion=1&orgId=1
![image](https://github.com/user-attachments/assets/cf8bd0c7-501a-40fb-9b5e-1856aa529f1d)

虽然不确定是否有关系，但是感觉至少可以优先处理掉这个问题。
怀疑这个PR引入：https://github.com/matrixorigin/matrixone/pull/20170
但是我本地10仓20线程单CN，100仓200线程多CN没有复现。可能得在对应环境上复现

**Comment by aressu1985** [comment]
问题已经解决，关闭
