### ISSUE TITLE
[Bug]: bvt failed in snapshot_restore_*: error: internal error: do not have privilege to execute the statement 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#20325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

during one pr

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/11993693337/job/33434922803?pr=20298

[mo-service.log.zip](https://github.com/user-attachments/files/17893444/mo-service.log.zip)

### Steps to Reproduce

```Markdown
run bvt
```

**Comment by YANGGMM** [comment]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/b617f784-859c-42b9-ba7b-8d989654d9a7">

<img width="673" alt="image" src="https://github.com/user-attachments/assets/46cd6550-cc61-4331-9530-dff10d7de3d0">

**Comment by YANGGMM** [comment]
2024/11/24 06:27:27.626954 +0000 INFO cn-service compile/compile2.go:302 insert into with snapshot {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "sql": "insert into `mo_catalog`.`mo_user_grant` SELECT * FROM `mo_catalog`.`mo_user_grant` {MO_TS = 1732429646593651097 }", "affectRows": 4}

2024/11/24 06:27:27.575347 +0000 INFO cn-service compile/compile2.go:302 insert into with snapshot {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "sql": "insert into `mo_catalog`.`mo_user` SELECT * FROM `mo_catalog`.`mo_user` {MO_TS = 1732429646593651097 }", "affectRows": 2}

2024/11/24 06:27:27.417762 +0000 INFO cn-service compile/compile2.go:302 insert into with snapshot {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "sql": "insert into `mo_catalog`.`mo_role_privs` SELECT * FROM `mo_catalog`.`mo_role_privs` {MO_TS = 1732429646593651097 }", **"affectRows": 0}**

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/b3f74761-708b-48f2-9d4b-fb2694cca257">


2024/11/24 06:27:27.285734 +0000 INFO cn-service compile/compile2.go:302 insert into with snapshot {"service": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "uuid": "dd1dccb0-4d3c-41f8-b482-5251dc7a41bf", "sql": "insert into `mo_catalog`.`mo_role_grant` SELECT * FROM `mo_catalog`.`mo_role_grant` {MO_TS = 1732429646593651097 }", "affectRows": 0}

**Comment by YANGGMM** [comment]
@triump2020 麻烦看一下

**Comment by triump2020** [comment]
Wait for pr , duplicate with #20384

**Comment by triump2020** [comment]
@sukki37   Fixed it.
