### ISSUE TITLE
[Bug]: use `char` to create a table but in `show columns` it changes to `varchar`

### ISSUE THREAD

**Issue by noneback** [matrixorigin/matrixone#2034]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:  Intel i5-8250U
- OS type: arch Linux
- Others: go version go1.17.8 linux/amd64
```

### Actual Behavior

`char` column shows `varchar` in `show columns`

### Expected Behavior

`char`

### Steps to Reproduce

```markdown
1. use db;
2. create table tab1(col char(10));
3. show columns from tab1;
```

**Comment by m-schen** [comment]
parser should diff char and varchar @iamlinjunhong
