### ISSUE TITLE
[Bug]: `execute ` recorded without sql and params

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#20342]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

v2.0.0-7852a2fdb-2024-11-22

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/c780deb6-e8cf-4b14-bfb3-76f26523e8c7)

### Expected Behavior

记录到statement info 里面的execute 带上 sql 和 参数。

### Steps to Reproduce

```Markdown
是在一个次事务卡死的情形下出现的。没有完整的复现过程。

`杀掉了 cn pod 之后 。再启动pod 再查 就已经记录了。`
```

**Comment by xzxiong** [comment]
当 执行的 Execute 是通过 mysql协议发送过来的，会提前解析掉 sql与 参数，
在 `doComQuery()`函数中 就拿不到对应的sql 或 参数。
![image](https://github.com/user-attachments/assets/757fd418-f627-477c-a69d-b0fbdb6f1c9a)

**Comment by daviszhen** [comment]
jdbc 改了

**Comment by heni02** [comment]
confirm,closed
2.0-dev commit:97eb84203  mocloud dev环境
<img width="1601" alt="企业微信截图_45f8b173-17ee-4e7d-835f-04dad821475d" src="https://github.com/user-attachments/assets/e633471f-6df8-49b5-8c3e-7f784b5fd24a">
<img width="387" alt="企业微信截图_3013d0e2-d3a5-4cd7-8c02-4bcb47851171" src="https://github.com/user-attachments/assets/357aa2bb-f3e1-4705-aa3b-27ef520f8072">
