### ISSUE TITLE
[Bug]: [1126 2.0-dev standalone regression] load data report 'sync /data1/runners/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/mo-data/s3/.tmp.1010028563: input/output error'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20374]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

57072e435e278885813786876b609b81ad1e883e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12012137877/job/33482956871

<img width="1869" alt="image" src="https://github.com/user-attachments/assets/ab3af4a9-8cdf-4708-ab3e-0331e17f6d99">

日志：https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-57072e435-20241125-222847.log%5C%22%7D%20%7C%3D%20%601010028563%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732584940000%22,%22to%22:%221732585540000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger 128 workflow
```

**Comment by LeftHandCold** [comment]
128 写文件失败，当时出现硬件error。
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]: Hardware error from APEI Generic Hardware Error Source: 4
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]: event severity: recoverable
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:  Error 0, type: recoverable
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:  fru_text: B2
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   section_type: memory error
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:    error_status: Storage error in DRAM memory (0x0000000000000400)
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   physical_address: 0x000000276aeb0180
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   physical_address_mask: 0xffffffffffffffc0
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   node:1 card:4 module:0 rank:0 bank:6 device:0 row:24237 column:24
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   error_type: 3, multi-bit ECC
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   DIMM location: not present. DMI handle: 0x0000
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:  Error 1, type: recoverable
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:  fru_text: B2
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   section_type: memory error
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:    error_status: Storage error in DRAM memory (0x0000000000000400)
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   physical_address: 0x000000276aeb2500
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   physical_address_mask: 0xffffffffffffffc0
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   node:1 card:4 module:0 rank:0 bank:6 device:0 row:24237 column:328
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   error_type: 3, multi-bit ECC
Nov 26 09:36:22 mo-srv-128 kernel: {7}[Hardware Error]:   DIMM location: not present. DMI handle: 0x0000
Nov 26 09:36:22 mo-srv-128 kernel: mce: [Hardware Error]: Machine check events logged
Nov 26 09:36:22 mo-srv-128 kernel: EDAC MC6: 1 UE memory read error on CPU_SrcID#1_MC#2_Chan#0_DIMM#0 (channel:0 slot:0 page:0x276aeb0 offset:0x180 grain:32 -  err_code:0x0000:0x009f  SystemAddress:0x276aeb0180 ProcessorSocketId:0x1 MemoryControllerId:0x2 ChannelAddress:0x1babac080 ChannelId:0x0 RankAddress:0xdd5d608
0 PhysicalRankId:0x0 DimmSlotId:0x0 Row:0x5ead Column:0x18 Bank:0x2 BankGroup:0x1 ChipSelect:0x0 ChipId:0x0)
Nov 26 09:36:22 mo-srv-128 kernel: mce: [Hardware Error]: Machine check events logged
Nov 26 09:36:22 mo-srv-128 kernel: EDAC MC6: 1 UE memory read error on CPU_SrcID#1_MC#2_Chan#0_DIMM#0 (channel:0 slot:0 page:0x276aeb2 offset:0x500 grain:32 -  err_code:0x0000:0x009f  SystemAddress:0x276aeb2500 ProcessorSocketId:0x1 MemoryControllerId:0x2 ChannelAddress:0x1babaca00 ChannelId:0x0 RankAddress:0xdd5d6a0
0 PhysicalRankId:0x0 DimmSlotId:0x0 Row:0x5ead Column:0x148 Bank:0x2 BankGroup:0x1 ChipSelect:0x0 ChipId:0x0)
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Hardware event. This is not a software error.
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCE 0
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: CPU 0 ACPI/APEI reported error
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MISC 8c ADDR 276aeb0180
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: TIME 1732584982 Tue Nov 26 09:36:22 2024
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCG status:
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCi status:
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Uncorrected error
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Error enabled
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCi_MISC register valid
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCi_ADDR register valid
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCA: MEMORY CONTROLLER RD_CHANNELunspecified_ERR
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Transaction: Memory read error
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: STATUS bc0000000000009f MCGSTATUS 0
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCGCAP f00081c APICID 0 SOCKETID 0
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: PPIN b4913efc729606e1
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MICROCODE d000311
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: CPUID Vendor Intel Family 6 Model 106 Step 6
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Hardware event. This is not a software error.
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCE 0
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: CPU 0 ACPI/APEI reported error
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MISC 8c ADDR 276aeb2500
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: TIME 1732584982 Tue Nov 26 09:36:22 2024
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCG status:
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCi status:
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Uncorrected error
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Error enabled
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCi_MISC register valid
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCi_ADDR register valid
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCA: MEMORY CONTROLLER RD_CHANNELunspecified_ERR
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: Transaction: Memory read error
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: STATUS bc0000000000009f MCGSTATUS 0
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MCGCAP f00081c APICID 0 SOCKETID 0
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: PPIN b4913efc729606e1
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: MICROCODE d000311
Nov 26 09:36:22 mo-srv-128 mcelog[1963]: CPUID Vendor Intel Family 6 Model 106 Step 6
Nov 26 09:36:22 mo-srv-128 kernel: Memory failure: 0x276aeb0: recovery action for dirty LRU page: Recovered
Nov 26 09:36:22 mo-srv-128 kernel: Memory failure: 0x276aeb2: recovery action for dirty LRU page: Recovered

**Comment by Ariznawlll** [comment]
等会重新跑一下试试

**Comment by Ariznawlll** [comment]
<img width="1876" alt="image" src="https://github.com/user-attachments/assets/07d4b40b-71c3-414a-a861-db1cf2cf180d">

原流程上重新load没问题
