### ISSUE TITLE
[Bug]: [date 11.25] 2.0-dev standalone regression: Gist960 dim vector index query mo oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20378]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

57072e435e278885813786876b609b81ad1e883e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12012137877/job/33482959284
<img width="1025" alt="企业微信截图_aa921243-0755-4f83-9cab-704c2d3fc1a4" src="https://github.com/user-attachments/assets/c3659d85-ae15-49ce-976d-549d45b75b94">
oom时间：Nov 26 14:08:28
<img width="1263" alt="企业微信截图_f8561352-688a-4f24-89c9-6d07ef4f2925" src="https://github.com/user-attachments/assets/c068ab35-5ace-4af2-99ec-6b855615fc7b">

mo log有panic error：
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-57072e435-20241125-222847.log%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732601309173%22,%22to%22:%221732601309176%22%7D%7D%7D&schemaVersion=1&orgId=1
runtime.sigpanic() |  

 /home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/panic.go:1067 +0x48 fp=0xc02d7b0a08 sp=0xc02d7b09d8 pc=0x50af48
2024-11-26 14:08:29.175 | runtime.gopark(0x0?, 0x52927f8?, 0x0?, 0x29?, 0x1000000010?) |  
 goroutine 18 gp=0xc000184700 m=nil [finalizer wait]: |  
 /home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/mgc.go:204 +0xa5 |  
 created by runtime.gcenable in goroutine 1 |  
/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc00013dfe8 sp=0xc00013dfe0 pc=0x513d41 |  
 runtime.goexit({}) |  
 /home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/mgc.go:204 +0x25 fp=0xc00013dfe0 sp=0xc00013dfc8 pc=0x4b0745 |  
runtime.gcenable.gowrap2() |  
 /home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc00013dfc8 sp=0xc00013dfa8 pc=0x4ba199 |  
runtime.bgscavenge(0xc00007e380) |  
 /home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00013dfa8 sp=0xc00013df78 pc=0x4b9c09 |  
 runtime.(*scavengerState).park(0x87fde60) |  
 /home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/proc.go:430 |  
runtime.goparkunlock(...) |  
/home/github/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/proc.go:424 +0xce fp=0xc00013df78 sp=0xc00013df58 pc=0x50b06e

Nov 26 14:07时间的profile:
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_01936714-8bf9-7cec-a242-698995f23bf1.gz](https://github.com/user-attachments/files/17914593/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_malloc_01936714-8bf9-7cec-a242-698995f23bf1.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01936714-f989-76a7-a258-d1b1a32ac629.gz](https://github.com/user-attachments/files/17914596/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_heap_01936714-f989-76a7-a258-d1b1a32ac629.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_01936715-0070-79cd-b9b5-87e932a4ee8a.gz](https://github.com/user-attachments/files/17914597/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_goroutine_01936715-0070-79cd-b9b5-87e932a4ee8a.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01936714-c707-77c1-8996-e4a9fbf4edf4.gz](https://github.com/user-attachments/files/17914598/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01936714-c707-77c1-8996-e4a9fbf4edf4.gz)

### Steps to Reproduce

```Markdown
gist960 vector index=2000 test，先使用以下简化步骤尝试复现，如果不行需要使用ann工具测试复现

1.source gist960.sql # contact me
2.SET @@experimental_ivf_index = 1;
3. CREATE INDEX ivf_2000 USING ivfflat on t5(b) op_type 'vector_l2_ops'  lists=2000;
4. SELECT id FROM items ORDER BY l2_distance(embedding, '[0.0359, 0.1996, 0.1546, 0.0431, 0.0369, 0.0551, 0.1195, 0.0312, 0.0437, 0.045, 0.1554, 0.0579, 0.1507, 0.123, 0.2055, 0.0904, 0.0462, 0.1447, 0.1211, 0.0313, 0.0396, 0.0781, 0.0914, 0.0328, 0.0389, 0.0586, 0.1396, 0.0581, 0.1236, 0.1033, 0.1694, 0.0566, 0.0395, 0.0835, 0.0582, 0.0426, 0.0386, 0.0483, 0.0618, 0.0552, 0.0316, 0.047, 0.1135, 0.0692, 0.0625, 0.0703, 0.0709, 0.0431, 0.0476, 0.0421, 0.0363, 0.1016, 0.0705, 0.0505, 0.0752, 0.0825, 0.0639, 0.0422, 0.0448, 0.0721, 0.0458, 0.078, 0.0339, 0.0531, 0.0712, 0.0456, 0.0495, 0.1095, 0.0903, 0.0585, 0.0788, 0.1065, 0.0791, 0.0569, 0.0782, 0.1202, 0.0395, 0.0977, 0.0523, 0.1109, 0.0561, 0.0463, 0.0443, 0.0442, 0.0723, 0.0588, 0.1034, 0.0638, 0.0489, 0.0486, 0.0598, 0.0504, 0.0388, 0.1109, 0.0567, 0.0679, 0.04, 0.0507, 0.0373, 0.0347, 0.043, 0.0503, 0.0909, 0.0338, 0.0375, 0.0461, 0.081, 0.0408, 0.0746, 0.1049, 0.0554, 0.06, 0.0232, 0.0997, 0.0622, 0.045, 0.045, 0.0468, 0.0993, 0.0314, 0.039, 0.0642, 0.1104, 0.0372, 0.1308, 0.0816, 0.0685, 0.0673, 0.0354, 0.0901, 0.0772, 0.0332, 0.033, 0.038, 0.0918, 0.0388, 0.0418, 0.0259, 0.116, 0.0572, 0.1345, 0.1491, 0.1698, 0.067, 0.031, 0.0846, 0.0777, 0.0236, 0.029, 0.08, 0.0848, 0.0248, 0.0453, 0.0512, 0.08, 0.031, 0.1246, 0.1445, 0.1569, 0.0573, 0.0523, 0.1126, 0.0578, 0.0305, 0.0387, 0.0436, 0.0538, 0.0393, 0.0432, 0.0367, 0.0553, 0.0238, 0.0924, 0.1069, 0.0628, 0.0256, 0.0347, 0.0555, 0.0485, 0.0753, 0.032, 0.0508, 0.1024, 0.0812, 0.0199, 0.0545, 0.0715, 0.0693, 0.0594, 0.0991, 0.0255, 0.0563, 0.0464, 0.0634, 0.0319, 0.09, 0.0406, 0.0477, 0.1133, 0.1006, 0.0228, 0.0851, 0.1339, 0.1377, 0.0526, 0.1277, 0.0597, 0.1053, 0.0412, 0.0539, 0.0522, 0.0439, 0.0597, 0.0437, 0.1044, 0.074, 0.0382, 0.0416, 0.0864, 0.0587, 0.0648, 0.1253, 0.0452, 0.0419, 0.0375, 0.0523, 0.0334, 0.0266, 0.0535, 0.032, 0.0673, 0.0302, 0.047, 0.0394, 0.055, 0.0328, 0.0992, 0.1088, 0.0395, 0.0564, 0.0262, 0.0471, 0.0566, 0.0278, 0.0333, 0.0316, 0.0863, 0.0296, 0.0439, 0.0706, 0.1029, 0.0412, 0.1181, 0.0586, 0.0456, 0.0504, 0.0578, 0.0857, 0.0397, 0.019, 0.0261, 0.0441, 0.0692, 0.0202, 0.0459, 0.0399, 0.04, 0.0235, 0.0747, 0.0822, 0.0687, 0.0245, 0.0274, 0.0482, 0.0317, 0.0284, 0.0324, 0.0235, 0.0377, 0.0376, 0.0304, 0.0355, 0.0474, 0.0396, 0.0641, 0.0635, 0.0901, 0.0348, 0.0383, 0.0416, 0.0143, 0.0236, 0.0563, 0.0411, 0.0435, 0.0418, 0.053, 0.0416, 0.0377, 0.0577, 0.0702, 0.0699, 0.0411, 0.0597, 0.0327, 0.048, 0.0361, 0.0173, 0.0231, 0.0296, 0.0717, 0.0333, 0.0354, 0.0224, 0.0256, 0.0251, 0.053, 0.0404, 0.0236, 0.0226, 0.0359, 0.1996, 0.1546, 0.0431, 0.0369, 0.0551, 0.1195, 0.0312, 0.0437, 0.045, 0.1554, 0.0579, 0.1507, 0.123, 0.2055, 0.0904, 0.0462, 0.1447, 0.1211, 0.0313, 0.0396, 0.0781, 0.0914, 0.0328, 0.0389, 0.0586, 0.1396, 0.0581, 0.1236, 0.1033, 0.1694, 0.0566, 0.0395, 0.0835, 0.0582, 0.0426, 0.0386, 0.0483, 0.0618, 0.0552, 0.0316, 0.047, 0.1135, 0.0692, 0.0625, 0.0703, 0.0709, 0.0431, 0.0476, 0.0421, 0.0363, 0.1016, 0.0705, 0.0505, 0.0752, 0.0825, 0.0639, 0.0422, 0.0448, 0.0721, 0.0458, 0.078, 0.0339, 0.0531, 0.0712, 0.0456, 0.0495, 0.1095, 0.0903, 0.0585, 0.0788, 0.1065, 0.0791, 0.0569, 0.0782, 0.1202, 0.0395, 0.0977, 0.0523, 0.1109, 0.0561, 0.0463, 0.0443, 0.0442, 0.0723, 0.0588, 0.1034, 0.0638, 0.0489, 0.0486, 0.0598, 0.0504, 0.0388, 0.1109, 0.0567, 0.0679, 0.04, 0.0507, 0.0373, 0.0347, 0.043, 0.0503, 0.0909, 0.0338, 0.0375, 0.0461, 0.081, 0.0408, 0.0746, 0.1049, 0.0554, 0.06, 0.0232, 0.0997, 0.0622, 0.045, 0.045, 0.0468, 0.0993, 0.0314, 0.039, 0.0642, 0.1104, 0.0372, 0.1308, 0.0816, 0.0685, 0.0673, 0.0354, 0.0901, 0.0772, 0.0332, 0.033, 0.038, 0.0918, 0.0388, 0.0418, 0.0259, 0.116, 0.0572, 0.1345, 0.1491, 0.1698, 0.067, 0.031, 0.0846, 0.0777, 0.0236, 0.029, 0.08, 0.0848, 0.0248, 0.0453, 0.0512, 0.08, 0.031, 0.1246, 0.1445, 0.1569, 0.0573, 0.0523, 0.1126, 0.0578, 0.0305, 0.0387, 0.0436, 0.0538, 0.0393, 0.0432, 0.0367, 0.0553, 0.0238, 0.0924, 0.1069, 0.0628, 0.0256, 0.0347, 0.0555, 0.0485, 0.0753, 0.032, 0.0508, 0.1024, 0.0812, 0.0199, 0.0545, 0.0715, 0.0693, 0.0594, 0.0991, 0.0255, 0.0563, 0.0464, 0.0634, 0.0319, 0.09, 0.0406, 0.0477, 0.1133, 0.1006, 0.0228, 0.0851, 0.1339, 0.1377, 0.0526, 0.1277, 0.0597, 0.1053, 0.0412, 0.0539, 0.0522, 0.0439, 0.0597, 0.0437, 0.1044, 0.074, 0.0382, 0.0416, 0.0864, 0.0587, 0.0648, 0.1253, 0.0452, 0.0419, 0.0375, 0.0523, 0.0334, 0.0266, 0.0535, 0.032, 0.0673, 0.0302, 0.047, 0.0394, 0.055, 0.0328, 0.0992, 0.1088, 0.0395, 0.0564, 0.0262, 0.0471, 0.0566, 0.0278, 0.0333, 0.0316, 0.0863, 0.0296, 0.0439, 0.0706, 0.1029, 0.0412, 0.1181, 0.0586, 0.0456, 0.0504, 0.0578, 0.0857, 0.0397, 0.019, 0.0261, 0.0441, 0.0692, 0.0202, 0.0459, 0.0399, 0.04, 0.0235, 0.0747, 0.0822, 0.0687, 0.0245, 0.0274, 0.0482, 0.0317, 0.0284, 0.0324, 0.0235, 0.0377, 0.0376, 0.0304, 0.0355, 0.0474, 0.0396, 0.0641, 0.0635, 0.0901, 0.0348, 0.0383, 0.0416, 0.0143, 0.0236, 0.0563, 0.0411, 0.0435, 0.0418, 0.053, 0.0416, 0.0377, 0.0577, 0.0702, 0.0699, 0.0411, 0.0597, 0.0327, 0.048, 0.0361, 0.0173, 0.0231, 0.0296, 0.0717, 0.0333, 0.0354, 0.0224, 0.0256, 0.0251, 0.053, 0.0404, 0.0236, 0.0226, 0.0359, 0.1996, 0.1546, 0.0431, 0.0369, 0.0551, 0.1195, 0.0312, 0.0437, 0.045, 0.1554, 0.0579, 0.1507, 0.123, 0.2055, 0.0904, 0.0462, 0.1447, 0.1211, 0.0313, 0.0396, 0.0781, 0.0914, 0.0328, 0.0389, 0.0586, 0.1396, 0.0581, 0.1236, 0.1033, 0.1694, 0.0566, 0.0395, 0.0835, 0.0582, 0.0426, 0.0386, 0.0483, 0.0618, 0.0552, 0.0316, 0.047, 0.1135, 0.0692, 0.0625, 0.0703, 0.0709, 0.0431, 0.0476, 0.0421, 0.0363, 0.1016, 0.0705, 0.0505, 0.0752, 0.0825, 0.0639, 0.0422, 0.0448, 0.0721, 0.0458, 0.078, 0.0339, 0.0531, 0.0712, 0.0456, 0.0495, 0.1095, 0.0903, 0.0585, 0.0788, 0.1065, 0.0791, 0.0569, 0.0782, 0.1202, 0.0395, 0.0977, 0.0523, 0.1109, 0.0561, 0.0463, 0.0443, 0.0442, 0.0723, 0.0588, 0.1034, 0.0638, 0.0489, 0.0486, 0.0598, 0.0504, 0.0388, 0.1109, 0.0567, 0.0679, 0.04, 0.0507, 0.0373, 0.0347, 0.043, 0.0503, 0.0909, 0.0338, 0.0375, 0.0461, 0.081, 0.0408, 0.0746, 0.1049, 0.0554, 0.06, 0.0232, 0.0997, 0.0622, 0.045, 0.045, 0.0468, 0.0993, 0.0314, 0.039, 0.0642, 0.1104, 0.0372, 0.1308, 0.0816, 0.0685, 0.0673, 0.0354, 0.0901, 0.0772, 0.0332, 0.033, 0.038, 0.0918, 0.0388, 0.0418, 0.0259, 0.116, 0.0572, 0.1345, 0.1491, 0.1698, 0.067, 0.031, 0.0846, 0.0777, 0.0236, 0.029, 0.08, 0.0848, 0.0248, 0.0453, 0.0512, 0.08, 0.031, 0.1246, 0.1445, 0.1569, 0.0573, 0.0523, 0.1126, 0.0578, 0.0305, 0.0387, 0.0436, 0.0538, 0.0393, 0.0432, 0.0367, 0.0553, 0.0238, 0.0924, 0.1069, 0.0628, 0.0256, 0.0347, 0.0555, 0.0485, 0.0753, 0.032, 0.0508, 0.1024, 0.0812, 0.0199, 0.0545, 0.0715, 0.0693, 0.0594, 0.0991, 0.0255, 0.0563, 0.0464, 0.0634, 0.0319, 0.09, 0.0406, 0.0477, 0.1133, 0.1006, 0.0228, 0.0851, 0.1339, 0.1377, 0.0526, 0.1277, 0.0597, 0.1053, 0.0412, 0.0539, 0.0522, 0.0439, 0.0597, 0.0437, 0.1044, 0.074, 0.0382, 0.0416, 0.0864, 0.0587, 0.0648, 0.1253, 0.0452, 0.0419, 0.0375, 0.0523, 0.0334, 0.0266, 0.0535, 0.032, 0.0673, 0.0302, 0.047, 0.0394, 0.055, 0.0328, 0.0992, 0.1088, 0.0395, 0.0564, 0.0262, 0.0471, 0.0566, 0.0278, 0.0333, 0.0316, 0.0863, 0.0296, 0.0439, 0.0706, 0.1029, 0.0412, 0.1181, 0.0586, 0.0456, 0.0504, 0.0578, 0.0857, 0.0397, 0.019, 0.0261, 0.0441, 0.0692, 0.0202, 0.0459, 0.0399, 0.04, 0.0235, 0.0747, 0.0822, 0.0687, 0.0245, 0.0274, 0.0482, 0.0317, 0.0284, 0.0324, 0.0235, 0.0377, 0.0376, 0.0304, 0.0355, 0.0474, 0.0396, 0.0641, 0.0635, 0.0901, 0.0348, 0.0383, 0.0416, 0.0143, 0.0236, 0.0563, 0.0411, 0.0435, 0.0418, 0.053, 0.0416, 0.0377, 0.0577, 0.0702, 0.0699, 0.0411, 0.0597, 0.0327, 0.048, 0.0361, 0.0173, 0.0231, 0.0296, 0.0717, 0.0333, 0.0354, 0.0224, 0.0256, 0.0251, 0.053, 0.0404, 0.0236, 0.0226]') LIMIT 10]
```

**Comment by cpegeric** [comment]
The profile you made is for CREATE INDEX but not SELECT.   Please help do another profile for SELECT

**Comment by cpegeric** [comment]
In case OOM on Create Index, here is the profile.

TableScan and hashmap probably the issue.

<img width="1809" alt="image" src="https://github.com/user-attachments/assets/ae723910-4de0-402f-a27e-04990aaae271">

<img width="2308" alt="image" src="https://github.com/user-attachments/assets/3bebfd20-5679-4826-94a6-a69315367b86">

<img width="736" alt="image" src="https://github.com/user-attachments/assets/9207e12f-7938-43c9-b306-432d2118d04f">

**Comment by cpegeric** [comment]
Are we running SQL Executor?  If so, it is likely that the batch read is not in stream mode.  

Please check out the PR https://github.com/matrixorigin/matrixone/pull/20230. for streaming usage.

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/425d2391-5ffe-4007-93b0-efe229b0c2a2">

**Comment by heni02** [comment]
26号的回归没有再出现oom了，2.0-dev commit：2fdf5b51f3557b2c1fe66cba6e9b723e8f2fb384
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12032684548/job/33545357748
<img width="1602" alt="企业微信截图_b6609701-7634-4777-80c9-4f7aada72387" src="https://github.com/user-attachments/assets/b165ae84-2d40-4754-9a5e-1242ebee3c37">

应该是偶现问题，待有环境单跑复现再抓profile

**Comment by heni02** [comment]
confirm，closed
