### ISSUE TITLE
[Bug]: Instance crashed during a query with builtin function 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2038]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c21241faad543459880662e6048922aaf85cfa9f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a double,b float);
insert into t1 values(3.14,3.14159);
insert into t1 values(3.141593,3.14159);
select a,pi() from t1;
ERROR 2013 (HY000): Lost connection to MySQL server during query

### Expected Behavior

panic: runtime error: index out of range [1] with length 1

goroutine 632 [running]:
github.com/matrixorigin/matrixone/pkg/frontend.getDataFromPipeline({0x57924e0, 0xc0220006c0}, 0xc01b1e4460)
	/var/root/matrixone/pkg/frontend/mysql_cmd_executor.go:372 +0x28b8
github.com/matrixorigin/matrixone/pkg/sql/colexec/output.Call(0xc01b368cf0, {0x569f8e0, 0xc02202ee10})
	/var/root/matrixone/pkg/sql/colexec/output/output.go:45 +0x15e
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0220540c0, 0x3, 0x18}, 0x74aba68)
	/var/root/matrixone/pkg/vm/vm.go:48 +0x9c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).RunMerge(0xc01af0d890, 0xc01b368cf0)
	/var/root/matrixone/pkg/vm/pipeline/pipeline.go:114 +0x126
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc022056000, {0x5ccaea0, 0xc0033d5100})
	/var/root/matrixone/pkg/sql/compile/scope.go:500 +0x4aa
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run(0xc021bf8e00, 0x40cfb17)
	/var/root/matrixone/pkg/sql/compile/exec.go:76 +0x91
github.com/matrixorigin/matrixone/pkg/frontend.(*ComputationWrapperImpl).Run(0xc003b6cd80, 0x5cde548)
	/var/root/matrixone/pkg/frontend/mysql_cmd_executor.go:901 +0x1c
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0xc01a911e00, {0xc002ba4f78, 0x15})
	/var/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1152 +0x282e
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0xc01a911e00, 0xc021bfe1c0)
	/var/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1281 +0x5b3
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0xc01a1d33e0)
	/var/root/matrixone/pkg/frontend/routine.go:100 +0x39c
created by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine
	/var/root/matrixone/pkg/frontend/routine.go:152 +0x1e7

**Comment by m-schen** [comment]
it's same to #2026.  And we will find a suitable way to fix it soon.
