### ISSUE TITLE
[Bug]: [2.0-dev standalone regression] bvt 'insert into t3 values (153.45, 1111122222.222223333344444)' failed with 'MO does not return result in 120000 ms'. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20392]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

2fdf5b51f3557b2c1fe66cba6e9b723e8f2fb384

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12032684548/job/33545127283

<img width="1494" alt="image" src="https://github.com/user-attachments/assets/d3732939-d232-459d-befc-11a60abcb955">

bvt测试期间的log: https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22GYP%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%2210-222-1-128%5C%22,%20filename%3D%5C%22%2Fdata1%2Frunners%2Faction-runner%2F_work%2Fmo-nightly-regression%2Fmo-nightly-regression%2Fhead%2Fmo-service-2fdf5b51f-20241126-224743.log%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732632200000%22,%22to%22:%221732633100000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger 128 workflow
```

**Comment by sukki37** [comment]
mo process was mistakenly killed by someone.
