### ISSUE TITLE
[Bug]: [1127 2.0-dev tke regression] tpch 1t 4cn test oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20404]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

2fdf5b51f3557b2c1fe66cba6e9b723e8f2fb384

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12032890926/job/33580949624

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/27bbcded-37bc-4454-95af-355ce4bcbd03">

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/98ef998f-98a0-47a7-854a-a72b630963ee">

heap profile: 
[heap_profile1127.zip](https://github.com/user-attachments/files/17931286/heap_profile1127.zip)
malloc profile:
[malloc_profile1127.zip](https://github.com/user-attachments/files/17931288/malloc_profile1127.zip)

### Steps to Reproduce

```Markdown
trigger tke workflow
```

**Comment by badboynt1** [comment]
https://grafana.ci.matrixorigin.cn/d/be3ttwuwuj5dsa/memory-metrics?orgId=1&var-interval=1m&var-namespace=mo-branch-nightly-2fdf5b51f-20241126&var-pod=nightly-regression-dis-tp-cn-z859n&from=1732686977629&to=1732688812549

![image](https://github.com/user-attachments/assets/c69b959d-75b1-4c3b-9f63-99e8b89a083b)

oom之前，正常的cn堆外内存占用如图所示，两个尖峰分别是q9和q18， 跑完以后可以正常释放

**Comment by badboynt1** [comment]
然而oom的这个qxtcc这个cn，堆外内存累积起来不释放，导致了oom
![image](https://github.com/user-attachments/assets/6d6f4fad-444c-4b37-a28b-0e554cc47c0b)

**Comment by badboynt1** [comment]
4个cn只有这一个cn出现了内存不释放的情况。  可以继续观察一下，看看是否稳定复现。

**Comment by sukki37** [comment]
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/2dda7234-88a1-47d7-a64a-60bc74f302d5">

**Comment by badboynt1** [comment]
> <img alt="image" width="1457" src="https://private-user-images.githubusercontent.com/77312370/390339478-2dda7234-88a1-47d7-a64a-60bc74f302d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTk5ODUsIm5iZiI6MTczMjY5OTY4NSwicGF0aCI6Ii83NzMxMjM3MC8zOTAzMzk0NzgtMmRkYTcyMzQtODhhMS00N2Q3LWE2NGEtNjBiYzc0ZjMwMmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA5MjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2E5ZDdlODk0NDg4MTY5NGQ4YjI2OWI5OWMxYTkxYmRlN2EwNGNjYWQ5YTkxM2M5OWE3YmUyYWNmODU2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1fUY_83ril9yXxtLRipivGgzKV0nn2w409gYDMrMOCg">

从这里看，好像可以解释的通了。 4cn只有一个cn出现了不释放的情况，因为mergeorder算子只会在一个cn上跑。
看占用比例也基本上符合。   麻烦 @m-schen 跟踪一下mergeorder算子的逻辑

**Comment by m-schen** [comment]
看了mergeOrder算子，dup出来的内存不会出现不释放的情况。我觉得这个profile只是单纯查询没跑完。

**Comment by m-schen** [comment]
看了2.0-dev上11月26号合并的pr，
没有发现会导致内存不释放，或者从堆外分配batch的代码。

**Comment by m-schen** [comment]
观察这两天的nigthly，似乎已经恢复了稳定。
主要没有通过的测试为sysbench oltp和tpch的10g性能波动>25%的问题。

感觉可以进行关闭。

**Comment by Ariznawlll** [comment]
最近回归没再出现，先关闭
