### ISSUE TITLE
[Bug]: [2.0-dev tke regression] load data report 'internal error: convert go error to mo error Put "https://mo-nightly-gz-1308875761.cos.ap-guangzhou.myqcloud.com/mo-benchmark-12052524993%2Fdata%2F01936f48-0523-76f0-95f6-b1d4550f89cf_00000": write tcp 10.142.203.195:35336->169.254.0.47:443: write: connection reset by peer'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20419]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

27515a8503e37aedd287efc957c7bd108400fe44

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12052325845/job/33605654870

<img width="1513" alt="image" src="https://github.com/user-attachments/assets/6aadf261-b6d6-4cce-b5b1-2505c9d014f8">

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22ZGT%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-27515a850-20241127%5C%22%7D%20%7C%3D%20%60internal%20error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732738667000%22,%22to%22:%221732739267000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke workflow
```

**Comment by reusee** [comment]
已增加写重试

**Comment by Ariznawlll** [comment]
最近没出现了
