### ISSUE TITLE
[Bug]:performance: insert ignore and insert on duplicate Distributed performance is about 10% of standalone

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20418]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

dd576d34779ca3fee6fc0c47a9b5e808dd22b600

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

测试结论：insert ignore /insert on duplicate 测试了以下单表四个场景，发现分布式tke测试环境性能比单机慢10倍
单机：
<img width="968" alt="企业微信截图_32c1938e-92f7-45e6-9d7e-f9dfa72e7339" src="https://github.com/user-attachments/assets/189bf268-277c-40f6-b099-38f86a97a0c7">

分布式tke：
<img width="1097" alt="企业微信截图_acb58dc6-3869-4f6d-afb9-ec30d46b09ed" src="https://github.com/user-attachments/assets/3bf3c4ee-0dce-4752-8afd-344897921338">

测试数据准备：
主键无自增列的ddl：
create table test01(a bigint primary key,b int);
insert into test01 select result ,500 from generate_series(1000000)g;

主键有自增列的ddl：
create table test01(a bigint auto_increment primary key,b int);
insert into test01 select result ,500 from generate_series(1000000)g;

主键带索引的ddl：
create table test01(a bigint auto_increment primary key,b int unique key);
insert into test01(b) select result from generate_series(1000000)g;

tke insert ignore/insert duplicate explain：
ddl:create table test01(a bigint primary key,b int);
mysql> explain insert ignore into test01 values (999999,999999);
+------------------------------------------------------+
| TP QUERY PLAN                                        |
+------------------------------------------------------+
| Multi Update                                         |
|   ->  Join                                           |
|         Join Type: DEDUP (IGNORE)                    |
|         Join Cond: (test01.a = #[1,0])               |
|         Runtime Filter Build: #[-1,0]                |
|         ->  Table Scan on testdb.test01 [ForceOneCN] |
|               Runtime Filter Probe: test01.a         |
|         ->  Lock                                     |
|               ->  Project                            |
|                     ->  Values Scan "*VALUES*"       |
+------------------------------------------------------+
10 rows in set (0.07 sec)

mysql> explain insert into test01 values (9999999,9999999) on duplicate key update b=999999+2;
+------------------------------------------------------------+
| TP QUERY PLAN                                              |
+------------------------------------------------------------+
| Multi Update                                               |
|   ->  Project                                              |
|         ->  Join                                           |
|               Join Type: DEDUP (UPDATE)                    |
|               Join Cond: (test01.a = #[1,0])               |
|               Runtime Filter Build: #[-1,0]                |
|               ->  Table Scan on testdb.test01 [ForceOneCN] |
|                     Runtime Filter Probe: test01.a         |
|               ->  Lock                                     |
|                     ->  Project                            |
|                           ->  Values Scan "*VALUES*"       |
+------------------------------------------------------------+
11 rows in set (0.00 sec)

insert values无冲突explain：
mysql> explain insert into test01 values(1000001,1000001);
+------------------------------------------------------+
| TP QUERY PLAN                                        |
+------------------------------------------------------+
| Multi Update                                         |
|   ->  Join                                           |
|         Join Type: DEDUP (FAIL)                      |
|         Join Cond: (test01.a = #[1,0])               |
|         Runtime Filter Build: #[-1,0]                |
|         ->  Table Scan on testdb.test01 [ForceOneCN] |
|               Runtime Filter Probe: test01.a         |
|         ->  Lock                                     |
|               ->  Project                            |
|                     ->  Values Scan "*VALUES*"       |
+------------------------------------------------------+
10 rows in set (0.00 sec)

### Steps to Reproduce

```Markdown
测试场景：主键非自增列单表100万行数据，insert ignore全部冲突值，并发100测试查看TPS值

1.100万行数据准备：
sql:
create table test01(a bigint primary key,b int);
insert into test01 select result ,500 from generate_series(1000000)g;
2.mo-load工具cases/ddl/run.yaml sql修改为sql: "insert ignore into test01 values ({tbx},{tbx});"，tbx随机取1-10000000数值，运行10分钟
3.cd mo-load && ./start.sh -c cases/ddl/
```

**Comment by aunjgr** [comment]
plan看上去都没有问题。原因待查明。

**Comment by heni02** [comment]
初步发现问题是mo-load测试时使用了短连接导致性能变慢，后续更新测试数据

**Comment by heni02** [comment]
改成长连接后性能和单机性能基本持平，没有该问题了，closed
![image](https://github.com/user-attachments/assets/3b59a65e-d0cb-425d-b9b5-dea77a01321b)
