### ISSUE TITLE
[Tech Request]: cannot build client code after upgrade mo dependency version

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#20422]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
Support import matrixone as a go package.
```

### Why is this needed ?

Allow programs operate MO via programatic interface like `HAKeeperClient` and `QueryServiceClient`.

### Additional information

Import mo and build directly would report:

```
ld: library 'mo' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The workaround is specify mo lib path explicitly:

```
CGO_OPTS=CGO_CFLAGS="-I/Users/aylei/repo/matrixorigin/matrixone/cgo " CGO_LDFLAGS="-L/Users/aylei/repo/matrixorigin/matrixone/cgo -lm -lmo" go build ...
```

which is tedious and error-prone.

**Comment by reusee** [comment]
fixed
