### ISSUE TITLE
[Bug]: Inner join query execution result error: stream closed

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#20450]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

96a0524287e30a4892c6f5365541a2d221ed4c37

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/matrixone/actions/runs/12068798792/job/33654698466?pr=20442
log:
[ERROR]
[SCRIPT   FILE]: /home/runner/work/matrixone/matrixone/test/distributed/cases/optimizer/shuffle.test
[ROW    NUMBER]: 17
[SQL STATEMENT]: select count(*) from t1,t2 where t1.c1=t2.c1;
[EXPECT RESULT]:
count(*)
9000000
[ACTUAL RESULT]:
stream closed

### Expected Behavior

[ERROR]
[SCRIPT   FILE]: /home/runner/work/matrixone/matrixone/test/distributed/cases/optimizer/shuffle.test
[ROW    NUMBER]: 17
[SQL STATEMENT]: select count(*) from t1,t2 where t1.c1=t2.c1;
[ACTUAL RESULT]:
count(*)
9000000

### Steps to Reproduce

```Markdown
ci test
```

**Comment by badboynt1** [comment]
原因是有个cn oom了。 bvt里没有自动抓取profile， 但是这个测试的数据量确实很大，有一定概率oom。 可能需要考虑缩小bvt里的数据量

**Comment by badboynt1** [comment]
fixed
