### ISSUE TITLE
[Bug]: insert will panic if it writes S3

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#20457]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

6386d149f53dcba1dd4ab09a92d1fbea518640eb

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MySQL [test]> create table insert_ignore_09(c1 int primary key, c2 int);
Query OK, 0 rows affected (0.010 sec)

MySQL [test]> insert into insert_ignore_09 values(20,45),(21,55),(1,45),(6,22),(5,1),(1000,222),(99999,19);
Query OK, 7 rows affected (0.006 sec)

MySQL [test]> insert ignore into insert_ignore_09 select result, result from generate_series(1,10000000) g;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0:
runtime.goPanicIndex
        /usr/lib/go/src/runtime/panic.go:115
github.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*s3Writer).append
        /home/aunjbr/codebase/work/matrixone/pkg/sql/colexec/multi_update/s3writer.go:159
github.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*MultiUpdate).update_s3
        /home/aunjbr/codebase/work/matrixone/pkg/sql/colexec/multi_update/multi_update.go:178
github.com/matrixorigin/matrixone/pkg/sql/colexec/multi_update.(*MultiUpdate).Call
        /home/aunjbr/codebase/work/matrixone/pkg/sql/colexec/multi_update/multi_update.go:144
github.com/matrixorigin/matrixone/pkg/vm.Exec
        /home/aunjbr/codebase/work/matrixone/pkg/vm/types.go:505
github.com/matrixorigin/matrixone/pkg/vm.ChildrenCall
        /home/aunjbr/codebase/work/matrixone/pkg/vm/types.go:516
github.com/matrixorigin/matrixone/pkg/sql/colexec/connector.(*Connector).Call
        /home/aunjbr/codebase/work/matrixone/pkg/sql/colexec/connector/connector.go:47
github.com/matrixorigin/matrixone/pkg/vm.Exec
        /home/aunjbr/codebase/work/matrixone/pkg/vm/types.go:505
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run
        /home/aunjbr/codebase/work/matrixone/pkg/vm/pipeline/pipeline.go:71
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /home/aunjbr/codebase/work/matrixone/pkg/sql/compile/scope.go:172
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun
        /home/aunjbr/codebase/work/matrixone/pkg/sql/compile/scope.go:491
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /home/aunjbr/codebase/work/matrixone/pkg/sql/compile/scope.go:348
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun
        /home/aunjbr/codebase/work/matrixone/pkg/sql/compile/scope.go:400
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /home/aunjbr/codebase/work/matrixone/pkg/sql/compile/scope.go:303
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /home/aunjbr/go/pkg/mod/github.com/panjf2000/ants/v2@v2.10.0/worker.go:71
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1700

### Steps to Reproduce

```Markdown
as above
```

**Comment by ouyuanning** [comment]
多CN可复现。可能原因是多CN时，Result属性没有传到远程节点
