### ISSUE TITLE
[Bug]: wait-active queue size does not match the actual number of goroutines

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#20468]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

1f3926e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="637" alt="image" src="https://github.com/user-attachments/assets/184cfe89-7c4e-4bbd-84fd-c57e59164397">

CN has over 100K wait active queue size.

But there are only 200 goroutines waiting in waitActive stack:

profile: [gorutines.txt](https://github.com/user-attachments/files/17955675/gorutines.txt)

Also, there is no explicit goroutine hold txn handler in the goroutine list.

### Expected Behavior

Wait active queue size should be correct.

### Steps to Reproduce

```Markdown
see https://grafana.cn-dev.matrixone.tech/goto/CTg6Gq7Ng?orgId=1
```

**Comment by daviszhen** [comment]
从goroutine文件看，`(*MOServer).handleConn(` 的个数 与 `(*waiter).wait(`的个数相同。大概100个。
初步看不是fe的线程导致的active queue size异常。

**Comment by zhangxu19830126** [comment]
fixed

**Comment by TangxingZhou** [comment]
升级后未再复现

**Comment by aylei** [comment]
verified
