### ISSUE TITLE
[Bug]: [1129 2.0-dev regression] load tpch 1t data report 'cannot commit a orphan transaction on invalid cn'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20467]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

1f3926e5bdf246018cf36fb08101334c473f7a12

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12070948646/job/33685078031

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/52d6e0d1-0a52-411d-bdf0-a744d19a7da9">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fF2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-1f3926e5b-20241128%5C%22%7D%20%7C%3D%20%60cannot%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732859581000%22,%22to%22:%221732859701000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke workflow
```

**Comment by badboynt1** [comment]
![image](https://github.com/user-attachments/assets/2b189dbe-6c88-4f70-9d23-7fd798b01b19)

从代码路径上看，可能和最近的改动有关，麻烦看一下 @zhangxu19830126

**Comment by zhangxu19830126** [comment]
和孤儿事物一个问题。

**Comment by zhangxu19830126** [comment]
重复问题
