### ISSUE TITLE
[Feature Request]: Datetime Built-in function weekday()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2046]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[WEEKDAY(date)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_weekday)

Returns the weekday index for date (0 = Monday, 1 = Tuesday, … 6 = Sunday).
```sql
mysql> SELECT WEEKDAY('2008-02-03 22:23:00');
        -> 6
mysql> SELECT WEEKDAY('2007-11-06');
        -> 1
```
The function should take date or datetime type as input, and return uint8 type.

### Describe implementation you've considered

Hint: we have already some useful functions implemented at for [date](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/date.go) and [datetime](https://github.com/matrixorigin/matrixone/blob/main/pkg/container/types/datetime.go) type. 

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by whileskies** [comment]
I want to try this issue, please

**Comment by whileskies** [comment]
I have finished Issue https://github.com/matrixorigin/matrixone/pull/2091

**Comment by dengn** [comment]
Feature implemented.
