### ISSUE TITLE
[Bug]: [1129 2.0-dev tke regression] sysbench1000w Non-pk index point select report many 'context deadline execeeded'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20470]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

1f3926e5bdf246018cf36fb08101334c473f7a12

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12070948646/job/33661665525

<img width="1396" alt="image" src="https://github.com/user-attachments/assets/915a129e-b536-4dac-b507-cec2f3d370d7">

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fF2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-1f3926e5b-20241128%5C%22%7D%20%7C%3D%20%60context%20deadline%20exceeded%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732855146000%22,%22to%22:%221732856883000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke workflow


注：单跑没出现这个问题
```

**Comment by daviszhen** [comment]
初步看是 proxy 链接cn handshake 超时。

cn 应该有问题了。

![image](https://github.com/user-attachments/assets/10587bec-582f-42df-940f-5981fc07eb5f)

**Comment by daviszhen** [comment]
从某次登录看。是验证租户，用户，密码阶段 一分钟超时。


![image](https://github.com/user-attachments/assets/4ac44634-70ab-4122-ad72-2ea7361e409a)


https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22fF2%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-branch-nightly-1f3926e5b-20241128%5C%22%7D%20%7C%3D%20%6010.143.119.147:50624%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221732855146000%22,%22to%22:%221732856883000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by daviszhen** [comment]
与 https://github.com/matrixorigin/matrixone/issues/20468 是一个问题。

![image](https://github.com/user-attachments/assets/c951472f-1583-4d05-9417-275a2dc0e861)

**Comment by Ariznawlll** [comment]
没再出现了
