### ISSUE TITLE
[Bug]:  perf of sysbench insert decrease about 20% percent on daily regression on distributed mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20476]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

13626b8

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY: 3C 7G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12095324030/job/33728431216
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12070773946/job/33686241324
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/aaccef1a-247d-4271-9de3-824f53b10877">

经过二分查询，结果如下：
<img width="804" alt="企业微信截图_4a12f4bc-6387-4b4e-9925-c5f6863728a3" src="https://github.com/user-attachments/assets/36e1780f-ab67-4793-bf49-0ddf18921f88">

开始下降的commit：13626b8

### Steps to Reproduce

```Markdown
run sysbench insert test
```

**Comment by gouhongshen** [comment]
根据 profile，log，似乎跟 mo_table stats 后台任务没有关系，要进一步排查。

**Comment by gouhongshen** [comment]
no progress

**Comment by gouhongshen** [comment]
no progress
