### ISSUE TITLE
[Bug]: After setting case sensitive, create database test, table TT,Tt, create snapshot, drop database test, after restore, the result of show tables is incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20484]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

ce18acaf4

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="413" alt="企业微信截图_0e6e5b22-33d9-4b3c-ad23-a6c644f46d90" src="https://github.com/user-attachments/assets/7a3a9b71-e1bc-4bf3-9ce1-3946fc8ff5eb">

if set global lower_case_table_names = 0, and create database test, create table TT and tt, then restore database test, after restore , the result is not correct.

```
set global lower_case_table_names = 0;

mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| Tt             |
| tt             |
+----------------+
2 rows in set (0.01 sec)

mysql> create snapshot sp02 for account sys;
Query OK, 0 rows affected (0.05 sec)

mysql> drop database test;
Query OK, 1 row affected (0.09 sec)

mysql> restore account sys from snapshot sp02;
Query OK, 0 rows affected (0.31 sec)

mysql> use test;
Database changed
mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| tt             |
+----------------+
1 row in set (0.00 sec)
```

### Steps to Reproduce

```Markdown
set global lower_case_table_names = 0;

create database test;
use test;
create table TT(col1 int);
create table Tt(col2 int);
create snapshot sp01 for account sys;

drop database test;
restore account sys from snapshot sp01;
use test;
show tables;
```

**Comment by YANGGMM** [comment]
fixed

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
main:
<img width="889" alt="image" src="https://github.com/user-attachments/assets/ef554715-8a79-4ad4-9658-ad83a93dd589">


2.0-dev:
<img width="819" alt="image" src="https://github.com/user-attachments/assets/1f0fd8c6-b5b9-4fa9-997f-0dbf83942dd2">
测试通过
