### ISSUE TITLE
[Tech Request]: optimize index plan to support sysbench random ranges benchmark

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#20486]
### Is there an existing issue for the same tech request?

- [X] I have checked the existing issues.

### Does this tech request not affect user experience?

- [X] This tech request doesn't affect user experience.

### What would you like to be added ?

```Markdown
optimize index plan to support sysbench random ranges benchmark
```

**Comment by badboynt1** [comment]
main分支已合并， sysbench random ranges场景有性能提升

**Comment by aressu1985** [comment]
fixed
