### ISSUE TITLE
[Bug]: Fill ProcessNext() and ProcessLinear() accumulate batches

### ISSUE THREAD

**Issue by cpegeric** [matrixorigin/matrixone#20491]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,2.0-dev

### Commit ID

5802c29aefcdb8b4d2551383ed6759956f6c3c87

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Fill ProcessNext() and ProcessLinear() accumulate the batches instead of process one by one.

### Expected Behavior

ProcessNext() and processLinear() should process batches one by one without accumulate.

### Steps to Reproduce

```Markdown
ProcessNext() and processLinear() should process batches one by one without accumulate.
```

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by iamlinjunhong** [comment]
暂未处理

**Comment by aressu1985** [comment]
@cpegeric pls confirm this issue
