### ISSUE TITLE
[Bug]: ut TestCdcTask_Restart data race

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#20501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="992" alt="image" src="https://github.com/user-attachments/assets/19993766-cb33-4893-afa5-2d203689b456">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/12121491668/job/33792544819?pr=20494
```

**Comment by ouyuanning** [comment]
repro https://github.com/matrixorigin/matrixone/actions/runs/12132195291/job/33825679921?pr=20505

**Comment by ck89119** [comment]
fixed
