### ISSUE TITLE
[Bug]: wrong values pass through runtime filter when insert after update

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#20528]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, 2.0-dev

### Commit ID

e2956601b4435ccbfdac37811d993b62dd0b69b1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

运行sysbench oltp_write_only.lua这个文件，
```
sysbench --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 --db-ps-mode=disable oltp_write_only.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=10 --time=300 --report-interval=2 --create_secondary=on --auto_inc=off --range_selects=off --point_selects=1 --db-ps-mode=disable run
```

调试时发现dedup join的左表经过runtime filter过滤之后，出来不应该通过runtime filter的一行。例如这样：
```
FATAL: mysql_drv_query() returned error 20101 (internal error: runtime filter not consistent with hashtable: id = 50425) for query 'INSERT INTO sbtest10 (id, k, c, pad) VALUES (50026, 50278, '31939533588-00754083266-24579697560-08752684309-01535048378-95413060360-61075795533-83882990952-57991883276-35067451242', '44440665326-61171275510-80461679009-47420131897-71711126357')'
```
给的值是50026，进哈希表是50026，runtime filter里也是id = 50026，然后左表出来的一行id = 50425进入了probe。正确情况是左表一行也不应该通过runtime filter。

oltp_write_only这个文件每个事务有4条语句，前两条是update，然后一条删除一条插入。两条update任意保留一条，就会出现上面的现象。如果都不保留就不出现。

### Steps to Reproduce

使用 #20529 分支，跑sysbench里oltp_write_only.lua

### Additional information

如果把 https://github.com/aunjgr/matrixone/blob/f39819449ec6bd7dcef8e74917b10bdefc6125d6/pkg/sql/compile/scope.go#L570-L573 这里的570和571行注释掉，相当于强制在Reader之后放一个filter算子，则问题跑不出来。这可以确定是Reader本身的过滤机制有bug，使错误的行被返回。

**Comment by gouhongshen** [comment]
inprogress

**Comment by gouhongshen** [comment]
in progress

**Comment by aunjgr** [comment]
@gouhongshen 麻烦也cherry-pick到2.0-dev一下
