### ISSUE TITLE
[Bug]: TestCdcTask_Restart failed

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#20534]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ut failed

### Steps to Reproduce

```Markdown
ut
```

**Comment by zhangxu19830126** [comment]
<img width="824" alt="image" src="https://github.com/user-attachments/assets/d135dba7-5cb1-47d6-b886-ece49125f89e">

**Comment by ck89119** [comment]
same as #20501, fixed
