### ISSUE TITLE
[Bug]: [1204 2.0-dev pitr regression] pitr restore report 'Error: Error 1105 (HY000): Put "***: write tcp 10.143.136.101:39070->169.254.0.47:443: write: broken pipe'.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20540]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

b8e9ba1bf4be8592daa411c70f3c489e72d60427

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12141083264/job/33855316936
 
<img width="989" alt="image" src="https://github.com/user-attachments/assets/601d2335-1dcd-4ce3-acab-77107dd01bcf">

log(utc+8): https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22WgK%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-b8e9ba1-20241203%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733238070000%22,%22to%22:%221733238147000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
上一个好的commit：ce18acaf42edb560caaf4e31abf2c63e17cba433

restore执行的sql：RESTORE ACCOUNT `acc01` FROM PITR `pitr02` '2024-12-03 14:55:54'
```

**Comment by XuPeng-SH** [comment]
@reusee please help to investigate this issue

**Comment by reusee** [comment]
和 #20419 是同类问题

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12161671141

昨天测试正常

**Comment by Ariznawlll** [comment]
最近测试没出现
