### ISSUE TITLE
[Bug]: perf of insert(1000w base data) fluctuate greatly in daily regression

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20570]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

7f462d9e42d9f1548d5dfaa71d95e799f1b3eb84

### Other Environment Information

```Markdown
- Hardware parameters: 64C 256G
- OS type:
- Others:
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12161915860/job/33917927314
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/3456f552-5817-4858-a52b-c25d8da97f01">

profile of low perf data:
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939325-8c10-7ade-8b55-42896df5edbf.gz]
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939327-619c-71b7-a0b6-bd46c340f3fd.gz](https://github.com/user-attachments/files/18016967/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939327-619c-71b7-a0b6-bd46c340f3fd.gz)
[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939326-0169-762f-b226-2b4d24bfb0d3.gz](https://github.com/user-attachments/files/18016970/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939326-0169-762f-b226-2b4d24bfb0d3.gz)

[LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939325-8c10-7ade-8b55-42896df5edbf.gz](https://github.com/user-attachments/files/18016971/LOG_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_cpu_01939325-8c10-7ade-8b55-42896df5edbf.gz)

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/096583f8-b834-4db4-9742-fec7d6df7d9d">

### Steps to Reproduce

```Markdown
DAILY REGRESSION
```

**Comment by gouhongshen** [comment]
dup with https://github.com/matrixorigin/matrixone/issues/20570

**Comment by gouhongshen** [comment]
无进展

**Comment by gouhongshen** [comment]
no progress
