### ISSUE TITLE
[Bug]: `show table status` reports error for subscription databases

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#20596]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

v2.0.0-7f462d9e4-2024-12-04

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Account A creates a new database without any tables and publishes database pub_db to account B
- Account B subscribes database pub_db
- Execute `show table status from pub_db` and get the following error:
```
"error":"Error 1105 (HY000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 66 near \") tmp\";","elapsed":"39.518486ms","rows":-1,"sql":"/* cloud_nonuser */ SHOW TABLE STATUS FROM `test`"
```

### Expected Behavior

SQL succeeds

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

**Comment by aressu1985** [comment]
fixed
