### ISSUE TITLE
[Bug]:Waiting too long for the mo_version table to lock when multiple CNs upgrade

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#20639]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

6c37ff09a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cn1: freetier-01-s2-6475fc8dcb-cn-26xr4
该CN率先开始升级

https://grafana.cn-qa.matrixone.tech/explore?panes=%7B%22TMq%22:%7B%22datasource%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60version%20upgrade%20added%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733560501536%22,%22to%22:%221733562822141%22%7D%7D%7D&schemaVersion=1&orgId=1
![image](https://github.com/user-attachments/assets/9a651ca9-6611-4549-aa12-6729bc17ee57)

cn2: freetier-01-s2-6475fc8dcb-cn-5z55n
CN2 升级SQL卡主，等锁

https://grafana.cn-qa.matrixone.tech/explore?panes=%7B%22TMq%22:%7B%22datasource%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D%5C%22freetier-01-s2-6475fc8dcb-cn-5z55n%5C%22%7D%20%7C%3D%20%60upgrade%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733560501536%22,%22to%22:%221733562822141%22%7D%7D%7D&schemaVersion=1&orgId=1
<img width="1246" alt="企业微信截图_17335670302935" src="https://github.com/user-attachments/assets/2a53d382-385f-42cc-ae6a-495d0ef92282">
另一个CN升级时，等mo_version表锁时间8分钟 

### Expected Behavior

The lock should return within a few seconds

### Steps to Reproduce

```Markdown
qa升级演练
```

**Comment by qingxinhome** [comment]
![image](https://github.com/user-attachments/assets/a0cf005e-8ff7-4907-8eea-faa12e43c167)

**Comment by qingxinhome** [comment]
![image](https://github.com/user-attachments/assets/578e14c7-d68e-48da-90dc-cf1d32742c91)

**Comment by qingxinhome** [comment]
mysql> select * from mo_version;
+---------+----------------+-------+---------------------+---------------------+
| version | version_offset | state | create_at           | update_at           |
+---------+----------------+-------+---------------------+---------------------+
| 1.1.0   |              0 |     2 | 2024-07-04 12:27:41 | 2024-07-04 12:27:41 |
| 1.2.1   |              6 |     2 | 2024-07-04 12:27:41 | 2024-07-04 12:54:38 |
| 1.2.3   |              2 |     2 | 2024-09-19 11:55:09 | 2024-09-19 11:59:29 |
| 2.0.1   |              9 |     2 | 2024-12-07 09:04:09 | 2024-12-07 09:18:18 |
+---------+----------------+-------+---------------------+---------------------+
4 rows in set (0.19 sec)

mysql> select * from mo_upgrade;
+-------+--------------+------------+---------------+----------------------+-------+-----------------+----------------+---------------+--------------+--------------+---------------------+---------------------+
| id    | from_version | to_version | final_version | final_version_offset | state | upgrade_cluster | upgrade_tenant | upgrade_order | total_tenant | ready_tenant | create_at           | update_at           |
+-------+--------------+------------+---------------+----------------------+-------+-----------------+----------------+---------------+--------------+--------------+---------------------+---------------------+
|     1 | 1.1.0        | 1.2.0      | 1.2.1         |                    6 |     2 |               1 |              1 |             0 |          202 |          202 | 2024-07-04 12:27:41 | 2024-07-04 12:53:01 |
|     2 | 1.2.0        | 1.2.1      | 1.2.1         |                    6 |     2 |               1 |              1 |             1 |          202 |          202 | 2024-07-04 12:27:41 | 2024-07-04 12:54:35 |
| 10001 | 1.2.1        | 1.2.2      | 1.2.3         |                    2 |     2 |               0 |              0 |             0 |            0 |            0 | 2024-09-19 11:55:09 | 2024-09-19 11:55:14 |
| 10002 | 1.2.2        | 1.2.3      | 1.2.3         |                    2 |     2 |               1 |              1 |             1 |          237 |          237 | 2024-09-19 11:55:09 | 2024-09-19 11:59:28 |
| 40001 | 1.2.3        | 2.0.0      | 2.0.1         |                    9 |     2 |               1 |              1 |             0 |          259 |          259 | 2024-12-07 09:04:09 | 2024-12-07 09:15:17 |
| 40002 | 2.0.0        | 2.0.1      | 2.0.1         |                    9 |     2 |               1 |              1 |             1 |          259 |          259 | 2024-12-07 09:04:09 | 2024-12-07 09:18:16 |
+-------+--------------+------------+---------------+----------------------+-------+-----------------+----------------+---------------+--------------+--------------+---------------------+---------------------+
6 rows in set (0.20 sec)

mysql> select * from mo_upgrade_tenant;
+-------+------------+----------------+-----------------+---------------+-------+---------------------+---------------------+
| id    | upgrade_id | target_version | from_account_id | to_account_id | ready | create_at           | update_at           |
+-------+------------+----------------+-----------------+---------------+-------+---------------------+---------------------+
|     1 |          1 | 1.2.0          |               0 |      33000005 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:32:21 |
|     2 |          1 | 1.2.0          |        33000006 |      78000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:30:25 |
|     3 |          1 | 1.2.0          |        81000001 |      96000002 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:36:13 |
|     4 |          1 | 1.2.0          |        99000001 |     129000002 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:34:16 |
|     5 |          1 | 1.2.0          |       132000001 |     159000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:38:12 |
|     6 |          1 | 1.2.0          |       159000002 |     207000006 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:40:06 |
|     7 |          1 | 1.2.0          |       207000008 |     255000002 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:42:01 |
|     8 |          1 | 1.2.0          |       255000003 |     288000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:44:00 |
|     9 |          1 | 1.2.0          |       297000001 |     351000003 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:45:56 |
|    10 |          1 | 1.2.0          |       360000001 |     435000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:47:52 |
|    11 |          1 | 1.2.0          |       438000001 |     531000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:49:48 |
|    12 |          1 | 1.2.0          |       534000001 |     642000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:51:52 |
|    13 |          1 | 1.2.0          |       645000001 |     690000001 |     1 | 2024-07-04 12:28:11 | 2024-07-04 12:53:01 |
|    14 |          2 | 1.2.1          |               0 |      33000005 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:17 |
|    15 |          2 | 1.2.1          |        33000006 |      78000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:24 |
|    16 |          2 | 1.2.1          |        81000001 |      96000002 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:31 |
|    17 |          2 | 1.2.1          |        99000001 |     129000002 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:37 |
|    18 |          2 | 1.2.1          |       132000001 |     159000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:43 |
|    19 |          2 | 1.2.1          |       159000002 |     207000006 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:50 |
|    20 |          2 | 1.2.1          |       207000008 |     255000002 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:53:57 |
|    21 |          2 | 1.2.1          |       255000003 |     288000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:54:04 |
|    22 |          2 | 1.2.1          |       297000001 |     351000003 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:54:10 |
|    23 |          2 | 1.2.1          |       360000001 |     435000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:54:17 |
|    24 |          2 | 1.2.1          |       438000001 |     531000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:54:25 |
|    25 |          2 | 1.2.1          |       534000001 |     642000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:54:31 |
|    26 |          2 | 1.2.1          |       645000001 |     690000001 |     1 | 2024-07-04 12:53:07 | 2024-07-04 12:54:35 |
| 10001 |      10002 | 1.2.3          |               0 |      33000005 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:56:35 |
| 10002 |      10002 | 1.2.3          |        33000006 |      78000001 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:55:35 |
| 10003 |      10002 | 1.2.3          |        81000001 |      96000002 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:56:22 |
| 10004 |      10002 | 1.2.3          |        99000001 |     132000001 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:56:00 |
| 10005 |      10002 | 1.2.3          |       132000002 |     159000002 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:56:51 |
| 10006 |      10002 | 1.2.3          |       162000001 |     207000008 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:57:05 |
| 10007 |      10002 | 1.2.3          |       216000002 |     255000003 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:57:19 |
| 10008 |      10002 | 1.2.3          |       258000001 |     297000001 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:57:32 |
| 10009 |      10002 | 1.2.3          |       303000001 |     363000001 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:57:46 |
| 10010 |      10002 | 1.2.3          |       369000001 |     447000001 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:58:22 |
| 10011 |      10002 | 1.2.3          |       453000002 |     591000002 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:58:04 |
| 10012 |      10002 | 1.2.3          |       591000003 |     681000001 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:58:37 |
| 10013 |      10002 | 1.2.3          |       687000001 |     690080003 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:58:54 |
| 10014 |      10002 | 1.2.3          |       690080005 |     690140005 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:59:12 |
| 10015 |      10002 | 1.2.3          |       690140008 |     690190002 |     1 | 2024-09-19 11:55:14 | 2024-09-19 11:59:28 |
| 40001 |      40001 | 2.0.0          |               0 |      33000005 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:12:54 |
| 40002 |      40001 | 2.0.0          |        33000006 |      78000001 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:11 |
| 40003 |      40001 | 2.0.0          |        81000001 |      96000002 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:19 |
| 40004 |      40001 | 2.0.0          |        99000001 |     132000001 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:02 |
| 40005 |      40001 | 2.0.0          |       132000002 |     159000002 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:28 |
| 40006 |      40001 | 2.0.0          |       162000001 |     207000008 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:39 |
| 40007 |      40001 | 2.0.0          |       216000002 |     255000003 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:49 |
| 40008 |      40001 | 2.0.0          |       258000001 |     297000001 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:14:10 |
| 40009 |      40001 | 2.0.0          |       303000001 |     375000001 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:13:59 |
| 40010 |      40001 | 2.0.0          |       381000002 |     456000005 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:14:22 |
| 40011 |      40001 | 2.0.0          |       480000001 |     633000004 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:14:33 |
| 40012 |      40001 | 2.0.0          |       645000001 |     690070003 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:14:41 |
| 40013 |      40001 | 2.0.0          |       690070004 |     690100006 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:14:49 |
| 40014 |      40001 | 2.0.0          |       690100007 |     690180003 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:14:58 |
| 40015 |      40001 | 2.0.0          |       690180004 |     690420008 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:15:06 |
| 40016 |      40001 | 2.0.0          |       690420009 |     690450003 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:15:16 |
| 40017 |      40001 | 2.0.0          |       690480002 |     690520002 |     1 | 2024-12-07 09:12:45 | 2024-12-07 09:15:17 |
| 50001 |      40002 | 2.0.1          |               0 |      33000005 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:15:54 |
| 50002 |      40002 | 2.0.1          |        33000006 |      78000001 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:16:10 |
| 50003 |      40002 | 2.0.1          |        81000001 |      96000002 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:16:19 |
| 50004 |      40002 | 2.0.1          |        99000001 |     132000001 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:16:36 |
| 50005 |      40002 | 2.0.1          |       132000002 |     159000002 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:16:28 |
| 50006 |      40002 | 2.0.1          |       162000001 |     207000008 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:16:45 |
| 50007 |      40002 | 2.0.1          |       216000002 |     255000003 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:16:54 |
| 50008 |      40002 | 2.0.1          |       258000001 |     297000001 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:12 |
| 50009 |      40002 | 2.0.1          |       303000001 |     375000001 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:03 |
| 50010 |      40002 | 2.0.1          |       381000002 |     456000005 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:22 |
| 50011 |      40002 | 2.0.1          |       480000001 |     633000004 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:32 |
| 50012 |      40002 | 2.0.1          |       645000001 |     690070003 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:41 |
| 50013 |      40002 | 2.0.1          |       690070004 |     690100006 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:49 |
| 50014 |      40002 | 2.0.1          |       690100007 |     690180003 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:18:06 |
| 50015 |      40002 | 2.0.1          |       690180004 |     690420008 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:17:58 |
| 50016 |      40002 | 2.0.1          |       690420009 |     690450003 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:18:14 |
| 50017 |      40002 | 2.0.1          |       690480002 |     690520002 |     1 | 2024-12-07 09:15:31 | 2024-12-07 09:18:16 |
+-------+------------+----------------+-----------------+---------------+-------+---------------------+---------------------+
75 rows in set (0.15 sec)

**Comment by qingxinhome** [comment]
每个CN在执行升级时，会先执行doCheckUpgrade函数， 用于确立版本升级的路由和升级任务， 期间需要对系统表mo_version加锁，如果是多CN都在执行schema升级，可能会出现抢锁的情况，在QA进行升级演练的过程中，出现了如下，
系统中一共有4个CN 参与升级，
参与升级的4个CN执行doCheckUpgrade函数的时间区间
cn-26xr4: [2024/12/07 09:04:09.288633, 2024/12/07 09:04:09.632979]
cn-5z55n: [2024/12/07 09:04:43.516338, 2024/12/07 09:12:46.649791]
cn-7cbgd: [2024/12/07 09:14:15.326013, ...]
cn-pj8zw: [2024/12/07 09:14:15.326013, ...]

其中cn-26xr4首先开始Schema升级，他执行doCheckUpgrade函数的时间区间是[2024/12/07 09:04:09.288633, 2024/12/07 09:04:09.632979]，在此期间cn-26xr4对系统表mo_version成功加锁， 并insert数据到mo_version表中
于此同时：cn-5z55n也开始升级，并执行doCheckUpgrade函数，其时间区间为[2024/12/07 09:04:43.516338, 2024/12/07 09:12:46.649791],  他的执行时间与cn-26xr4有交叉，因此，需要等mo_version表锁，
但是：cn-5z55n在cn-26xr4完成事务后，很长一段时间（8分钟左右）没有受到锁释放的信息，一直在等待
# @iamlinjunhong @zhangxu19830126

**Comment by iamlinjunhong** [comment]
cn-5z55n 上卡住的事务 9805ac86a823ef67180ed997d44ccd6c 一直在等 532c334254f18a08180ed997e4150fb1
<img width="2821" alt="截屏2024-12-09 16 00 27" src="https://github.com/user-attachments/assets/151f21df-1878-427e-a851-b94f94ec9fc0">

**Comment by iamlinjunhong** [comment]
事务 532c334254f18a08180ed997e4150fb1 一直在执行 sql 造成 9805ac86a823ef67180ed997d44ccd6c 等待七八分钟

<img width="2869" alt="截屏2024-12-09 16 02 44" src="https://github.com/user-attachments/assets/5e9a49b6-b464-4fcf-a8ac-74ad13b01043">

**Comment by qingxinhome** [comment]
问题原因如下：

1. mo在2.0.0版本针对发布订阅功能新增了mo_subs系统表，集群升级的时候会把之前版本的已经存在的订阅关系信息插入到这张mo_subs表中，
由于生产环境中存在的订阅关系较多，因此完成该项升级需要执行很多insert语句， 执行时间会很长。



2. 回到QA演练时遇到的：第二个cn-5z55n执行Schema升级命令时，长时间等待的问题

在cn-26xr4执行集群升级的时候，首先会在当前所在事务txn-532c334254f18a08180ed997e4150fb1中，使用select for update语句对mo_version表加锁， 然后在执行集群升级的其他操作，
其中当执行到mo_subs表中升级操作时，执行了较长时间，时间跨度大约为8分钟。
https://grafana.cn-qa.matrixone.tech/explore?panes=%7B%22TMq%22:%7B%22datasource%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60532c334254f18a08180ed997e4150fb1%60%20%21%3D%20%60wait%20too%20long%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22eb02ea9d-9b26-4289-89ed-4123679bdbe6%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733560431103%22,%22to%22:%221733562752103%22%7D%7D%7D&schemaVersion=1&orgId=1

于此同时：cn-5z55n执行升级指令Upgrade account all命令时，执行到doCheckUpgrade函数时，也需要对系统表mo_version加锁，但是cn-26xr4的txn-532c334254f18a08180ed997e4150fb1事务尚未提交， 因此导致CN2的Upgrade account all命令长时间等待,直到cn-26xr4的txn-532c334254f18a08180ed997e4150fb1事务提交
