### ISSUE TITLE
[Bug]: cube error "queue: disposed"

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#2065]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):54e592b74e7634c3c870a32821016aa807c18793
- Hardware parameters:mac
- OS type:mac
- Others:
```

### Actual Behavior

get a cube error "queue: disposed"

{"level":"DEBUG","time":"2022/03/29 14:15:14.312055 +0800","name":"cube.store","caller":"raftstore/replica_event_loop.go:195","msg":"skip handling events on stopped replica","store":"node0","store-id":1,"shard-id":47,"replica-id":48}
{"level":"INFO","time":"2022/03/29 14:15:14.312072 +0800","name":"cube.store","caller":"raftstore/replica_destroy.go:133","msg":"replica unloaded","store":"node0","store-id":1,"shard-id":47,"replica-id":48,"replica-id":47}
{"level":"DEBUG","time":"2022/03/29 14:15:14.312055 +0800","name":"cube.client","caller":"client/client.go:295","msg":"error response received","request-id":"465da51916854e1381fb90c7ee0aadcb","error":"queue: disposed"}
{"level":"WARN","time":"2022/03/29 14:15:14.312121 +0800","name":"cube.store","caller":"raftstore/replica_destroy.go:141","msg":"failed to delete shard key range","store":"node0"}
{"level":"INFO","time":"2022/03/29 14:15:14.331203 +0800","name":"cube.store","caller":"raftstore/replica_destroy.go:144","msg":"deleting shard data","store":"node0","store-id":1,"shard-id":47}
{"level":"ERROR","time":"2022/03/29 14:15:14.331194 +0800","caller":"logutil/api.go:63","msg":"DedupSetBatch cube error :queue: disposed","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tpe/tuplecodec.(*checkKeysExistedContext).callbackForCheckKeysExisted\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/vm/engine/tpe/tuplecodec/cubekv.go:464\ngithub.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).doAsyncExecWithGroup.func1\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/vm/driver/cube_driver.go:1050\ngithub.com/matrixorigin/matrixcube/util/stop.(*Stopper).doRunCancelableTask.func1\n\t/Users/pengzhen/go/src/github.com/matrixorigin/matrixcube@v0.3.1-0.20220325075741-a746a331dba0/util/stop/stopper.go:254"}
{"level":"ERROR","time":"2022/03/29 14:15:14.331249 +0800","caller":"logutil/api.go:63","msg":"write failed. err: queue: disposed","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.writeBatchToStorage\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1309\ngithub.com/matrixorigin/matrixone/pkg/frontend.rowToColumnAndSaveToStorage\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1248\ngithub.com/matrixorigin/matrixone/pkg/frontend.glob..func10.1\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1439"}
{"level":"DEBUG","time":"2022/03/29 14:15:14.331147 +0800","name":"cube.store.proxy","caller":"raftstore/proxy.go:218","msg":"dispatch request","store":"node0","store-id":1,"id":"6a034dfaad4b4560aa6c2c631a9d8e48","to-shard":47,"to-store":"localhost:20000","request":"id: 6a034dfaad4b4560aa6c2c631a9d8e48, key: , pid: 0, type: Read, custom-type: 11, cmd: 520002 bytes, to-shard: 47"}
{"level":"DEBUG","time":"2022/03/29 14:15:14.331488 +0800","name":"cube.store","caller":"raftstore/store.go:335","msg":"receive request","store":"node0","request-id":"6a034dfaad4b4560aa6c2c631a9d8e48","store-id":1}
{"level":"DEBUG","time":"2022/03/29 14:15:14.331662 +0800","name":"cube.client","caller":"client/client.go:295","msg":"error response received","request-id":"6a034dfaad4b4560aa6c2c631a9d8e48","error":"queue: disposed"}
{"level":"ERROR","time":"2022/03/29 14:15:14.331273 +0800","caller":"logutil/api.go:63","msg":"saveBatchToStorage failed. err:queue: disposed","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.rowToColumnAndSaveToStorage\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1263\ngithub.com/matrixorigin/matrixone/pkg/frontend.glob..func10.1\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1439"}
{"level":"ERROR","time":"2022/03/29 14:15:14.331693 +0800","caller":"logutil/api.go:63","msg":"DedupSetBatch cube error :queue: disposed","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tpe/tuplecodec.(*checkKeysExistedContext).callbackForCheckKeysExisted\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/vm/engine/tpe/tuplecodec/cubekv.go:464\ngithub.com/matrixorigin/matrixone/pkg/vm/driver.(*driver).doAsyncExecWithGroup.func1\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/vm/driver/cube_driver.go:1050\ngithub.com/matrixorigin/matrixcube/util/stop.(*Stopper).doRunCancelableTask.func1\n\t/Users/pengzhen/go/src/github.com/matrixorigin/matrixcube@v0.3.1-0.20220325075741-a746a331dba0/util/stop/stopper.go:254"}
{"level":"ERROR","time":"2022/03/29 14:15:14.331775 +0800","caller":"logutil/api.go:63","msg":"write failed. err: queue: disposed","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.writeBatchToStorage\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1309\ngithub.com/matrixorigin/matrixone/pkg/frontend.rowToColumnAndSaveToStorage\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1248\ngithub.com/matrixorigin/matrixone/pkg/frontend.glob..func10.1\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1439"}
{"level":"ERROR","time":"2022/03/29 14:15:14.331814 +0800","caller":"logutil/api.go:63","msg":"saveBatchToStorage failed. err:queue: disposed","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.rowToColumnAndSaveToStorage\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1263\ngithub.com/matrixorigin/matrixone/pkg/frontend.glob..func10.1\n\t/Users/pengzhen/Documents/GitHub/matrixone/pkg/frontend/load.go:1439"}
{"level":"INFO","time":"2022/03/29 14:15:14.350152 +0800","name":"cube.store","caller":"raftstore/replica_destroy.go:151","msg":"delete shard data returned","store":"node0","store-id":1,"shard-id":47}
{"level":"INFO","time":"2022/03/29 14:15:14.350216 +0800","name":"cube.store","caller":"raftstore/replica_destroy.go:184","msg":"going to mark replica as destroyed","store":"node0","store-id":1,"shard-id":47,"replica-id":48}
{"level":"INFO","time":"2022/03/29 14:15:14.350250 +0800","name":"cube.store","caller":"raftstore/replica_destroy.go:104","msg":"begin to destroy replica","store":"node0","store-id":1,"reason":"remove by pd","remove-data":true,"shard-id":47}

### Expected Behavior

no such error

### Steps to Reproduce

```markdown
load 1000w ssb test into the tpe.
```

**Comment by zhangxu19830126** [comment]
fixed by https://github.com/matrixorigin/matrixcube/pull/734
