### ISSUE TITLE
[Bug]: UT Test_CanTransferCnFaultInject fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#20665]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

newest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="916" alt="image" src="https://github.com/user-attachments/assets/fe21a299-3ab0-4480-9ef2-fe77af3af778">

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/12230712907/job/34112523445?pr=20661
```

**Comment by badboynt1** [comment]
repro in https://github.com/badboynt1/matrixone/actions/runs/12247707427/job/34166017589?pr=412

**Comment by Wenbin1002** [comment]
fixed
