### ISSUE TITLE
[Bug]: 能看到订阅库但订阅报错

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#20672]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

1.2-dev

### Commit ID

b15af21a1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
aliyun QA环境Restore集群
连接信息见：https://github.com/matrixorigin/MO-Cloud/issues/4597#issuecomment-2527564203
```

### Actual Behavior

```
show subscriptions all;
create database `1` from `bbbafa55_339e_4498_b2e4_ea2d4757f9e0` publication `pub_warehouse`;
```
报错：Error 20101 (HY000): internal error: the account 0193a9dd-2f0c-7502-b760-e9e8c2c8ab20 is not allowed to subscribe the publication pub_warehouse

### Expected Behavior

正常订阅

### Steps to Reproduce

```Markdown
如上
```

**Comment by heni02** [comment]
升级前2.0-dev commit ：0bbda669365e51df6d65fd33219f34f1515e8717
cn配置普通租户发布订阅
[cn.frontend]
pub-all-accounts = 'acc1,acc2'
ac1发布订阅到所有租户all
<img width="986" alt="企业微信截图_b383588e-7661-42ff-bb9f-3e79bd82b790" src="https://github.com/user-attachments/assets/6691ee18-1930-43d8-939f-098447ab388e">
场景a：ac2发布订阅
<img width="1440" alt="企业微信截图_b761d8d2-6134-484e-918e-4462f84089d7" src="https://github.com/user-attachments/assets/b81bb7e0-ade0-45f8-83c2-380d8ec7258b">
升级后2.0-dev 最新commit：25b06b2ca563296e52d0c85fcc0e50b3525db871
验证能看到发布订阅表
<img width="917" alt="企业微信截图_1c4da258-3b6a-4d8d-865d-cd11f513fcf6" src="https://github.com/user-attachments/assets/2a3ec230-7949-4b32-b862-ddd3d2bf0fae">

场景b: ac2未发布订阅
升级后2.0-dev 最新commit：25b06b2ca563296e52d0c85fcc0e50b3525db871
验证看不到发布订阅
<img width="847" alt="企业微信截图_fd5ada14-2728-4b41-8a84-a49d95ff9ff0" src="https://github.com/user-attachments/assets/39f8294f-05fd-4d96-b6db-c6f11e1d8963">

**Comment by heni02** [comment]
验证符合预期
