### ISSUE TITLE
[Bug]: aoe's metadata is not obtained correctly and can get stuck or get the wrong information

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2068]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The first time it will fetch the wrong metadata information, and after restarting it will get stuck fetching metadata

**Comment by daviszhen** [comment]
Some modification has been made. Just need to verify it again.
