### ISSUE TITLE
[Bug]: [date 12.09]tke regression: cn oom

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20692]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e1c3f504a

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12237889868/job/34167814008
<img width="1173" alt="企业微信截图_a4bc0ea8-793f-400a-b3ae-b85a26e69507" src="https://github.com/user-attachments/assets/ae7ccbb8-bd70-41af-a0aa-fde2856988f8">
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/86103c94-ba21-42f3-967d-885e1e6f48e0">

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/7f7faa89-73ee-4c3e-abeb-664b58702da2">
链接：https://grafana.ci.matrixorigin.cn/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=1733756180948&to=1733816290996&var-datasource=prometheus&var-cluster=&var-namespace=mo-main-nightly-e1c3f504a-20241209

heap：
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22yoP%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-e1c3f504a-20241209%5C%22,pod%3D%5C%22nightly-regression-dis-tp-cn-26bvh%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22%7D%5D,%22range%22:%7B%22from%22:%221733809023067%22,%22to%22:%221733810102317%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
tke regression
```

**Comment by LeftHandCold** [comment]
same as https://github.com/matrixorigin/matrixone/issues/20645

**Comment by heni02** [comment]
重复问题，closed
