### ISSUE TITLE
[Bug]: 删除数据时报错表不存在，实际上是存在的

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#20737]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0.1-hotfix

### Commit ID

44b376120

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
aliyun 线上环境
```

### Actual Behavior

偶现批量报错如下：
```
{"level":"ERROR","time":"2024/12/11 18:14:07.422546 +0000","caller":"worker/billing_aggr.go:203","msg":"trace","error":"Error 1146 (HY000): no such table billing.agg_billing_records_monthly_unit_name","elapsed":"41.797804ms","rows":0,"sql":"DELETE FROM `billing`.`agg_billing_records_monthly_unit_name` WHERE start_time >= '2024-11-30 16:00:00'  AND start_time < '2024-12-31 16:00:00'  AND organization_id = 'DAB-37987'  AND instance_id = '7605857e-707c-43c9-93ff-f4d5d563a309' AND unit_name = 'storage'"}
```
实际上这个表是存在的，并且报错一段时间以后，大约5min左右，又自动恢复。

### Expected Behavior

预期正常删除

### Steps to Reproduce

```Markdown
不稳定复现，只出现过一次。
```

### Additional information

Cloud日志：https://grafana.matrixonecloud.cn/explore?panes=%7B%22KrZ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22billingservice%5C%22%7D%20%7C%3D%20%60error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1
可以根据这个日志时间找一下对应MO日志

**Comment by sukki37** [comment]
这张表的创建时间在报错时间点之后，需要确认一下时序：
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/2fb2593c-85ae-4163-8e35-6cb8d8f0b5ad" />

https://grafana.matrixonecloud.cn/explore?panes=%7B%22KrZ%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22billingservice%5C%22%7D%20%7C%3D%20%60error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733940560307%22,%22to%22:%221733940920000%22%7D%7D,%22RFM%22:%7B%22datasource%22:%22fe9f0f46-57bd-4343-8755-8d67d0429b65%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bmatrixorigin_io_component%3D%5C%22DNSet%5C%22%7D%20%7C%3D%20%60agg_billing_records_monthly_unit_name%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22fe9f0f46-57bd-4343-8755-8d67d0429b65%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733940560307%22,%22to%22:%221733940920000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by aptend** [comment]
该表在 02:09:05 删除，02:14:07 重新创建

<img width="2195" alt="image" src="https://github.com/user-attachments/assets/7bac1575-dcf5-42c3-8831-3d94036a4bcd" />

https://grafana.matrixonecloud.cn/explore?panes=%7B%22u1M%22:%7B%22datasource%22:%22f6304562-93bb-4d76-9cc4-6429369fad8c%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22mysql%22,%22uid%22:%22f6304562-93bb-4d76-9cc4-6429369fad8c%22%7D,%22format%22:%22table%22,%22rawSql%22:%22select%20statement,%20transaction_id,%20query_type,%20request_at%20from%20system.statement_info%20where%20request_at%20%3E%20%5C%222024-12-11%2018:06:30.000%5C%22%20and%20request_at%20%3C%20%5C%222024-12-11%2018:15:30.000%5C%22%20and%20statement%20like%20%5C%22%25agg_billing_records_monthly_unit_name%25%5C%22%20and%20query_type%20%3D%20%5C%22DDL%5C%22;%22,%22editorMode%22:%22code%22,%22sql%22:%7B%22columns%22:%5B%7B%22type%22:%22function%22,%22parameters%22:%5B%5D%7D%5D,%22groupBy%22:%5B%7B%22type%22:%22groupBy%22,%22property%22:%7B%22type%22:%22string%22%7D%7D%5D,%22limit%22:50%7D,%22rawQuery%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by xiaoshuwei** [comment]
todo

**Comment by xiaoshuwei** [comment]
todo

**Comment by xiaoshuwei** [comment]
可能是误操作，Close了
