### ISSUE TITLE
[Bug]: [1212 main tke big-data regression] insert into select oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20733]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5d82985900d69743697807d3e57d3372c3f11fbf

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12279592467/job/34288048953 

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/eb9ee44d-c63a-4bb4-b81e-e37fada7be5b" />

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/08160559-2601-4305-aa19-51e0b5d67a44" />

malloc profile:
[malloc_profile1212.zip](https://github.com/user-attachments/files/18104812/malloc_profile1212.zip)
heap profile:
[heap_profile1212.zip](https://github.com/user-attachments/files/18104814/heap_profile1212.zip)

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22-sn%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-big-data-nightly-5d82985-20241211%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733940762000%22,%22to%22:%221733941122000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger big data workflow

第一次oom insert into select的数据量：10亿
```

**Comment by huby2358** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22-sn%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%5C%22mo-big-data-nightly-5d82985-20241211%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:inuse_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221733940762000%22,%22to%22:%221733941122000%22%7D%7D%7D&schemaVersion=1&orgId=1
这个堆栈看和#20734是同一个问题

**Comment by w-zr** [comment]
https://github.com/matrixorigin/matrixone/issues/20734 和此pr相同。

**Comment by Ariznawlll** [comment]
fixed
