### ISSUE TITLE
[Bug]:  [1212 main tke snapshot regression] load data oom.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20734]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5d82985900d69743697807d3e57d3372c3f11fbf

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12279577579/job/34265228479

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/a15b5a36-3c3f-4bb3-b1a6-2bc633b430c6" />

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/362eca68-eb7e-492b-bd08-61abd82213a0" />

heap profile:
[heap1212.zip](https://github.com/user-attachments/files/18104949/heap1212.zip)

malloc profile:
[malloc1212.zip](https://github.com/user-attachments/files/18104951/malloc1212.zip)

log：https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22SoM%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-snapshot-nightly-5d82985-20241211%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733937314000%22,%22to%22:%221733937614000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger snapshot workflow
```

**Comment by Ariznawlll** [comment]
不确定和 20733是不是一个问题，需要研发帮忙定位下

**Comment by huby2358** [comment]
<img width="1677" alt="企业微信截图_a68f2b96-a904-42fa-ad49-47ace6e27474" src="https://github.com/user-attachments/assets/db136d1c-e45f-459b-9899-4a6119f8a68d" />
mo_ctl的问题，inuse内存都在这里，超过了机器配置限制55G， @w-zr 帮忙看一下吧

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/issues/20733

**Comment by w-zr** [comment]
pr已经合并了，麻烦再测一下。谢谢

**Comment by Ariznawlll** [comment]
今天会再测试一下

**Comment by Ariznawlll** [comment]
fixed
