### ISSUE TITLE
[Bug]: [date 12.11] regression: ssb test performance down more than 3 times

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20742]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

110ab3be42d509c3c5f31337619bc366bfb29a81

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ssb 1/10/100G 单机和tke性能都有大幅下降
![image](https://github.com/user-attachments/assets/d1d16cd8-6963-4a84-96c5-55e8ff83cb59)
![image](https://github.com/user-attachments/assets/e01167e9-3a81-4398-a2cd-8b1c15d59889)

二分结果：
<img width="1388" alt="企业微信截图_672347fc-8df2-44bd-9642-dbb6031e72b2" src="https://github.com/user-attachments/assets/abdbcb54-5564-4f52-a3d3-c27b33e38000" />

main也有该问题，同步解决main和2.0分支

### Steps to Reproduce

```Markdown
ssb test
```

**Comment by badboynt1** [comment]
fixed

**Comment by heni02** [comment]
confirm,closed
性能已恢复
![image](https://github.com/user-attachments/assets/f5823ba1-6a85-4a7c-bee6-387b9362c645)
![image](https://github.com/user-attachments/assets/9169c37a-31d9-42e7-a0a4-9ccaafdf98c9)
