### ISSUE TITLE
[Bug]: `Alter table` reports error

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#20751]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

v2.0.1-64e4751dc-2024-12-12

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mocloud_meta:
<img width="1233" alt="企业微信截图_012ce980-5c43-49df-b29c-44aed7221378" src="https://github.com/user-attachments/assets/0f9647ba-6dcf-4d37-af40-57b519406dac" />

billing:
<img width="1208" alt="企业微信截图_34c415ab-2f17-443e-b3b3-cc29ab50c2d8" src="https://github.com/user-attachments/assets/8b7c3399-d968-4f14-89cf-3b7c77b2b36b" />

They succeed after retry several times.

### Expected Behavior

No error

### Steps to Reproduce

```Markdown
See detail in Actual Behavior
```

### Additional information

cloud

**Comment by qingxinhome** [comment]
https://github.com/matrixorigin/matrixone/issues/19206
