### ISSUE TITLE
[Bug]: [1216 main tke pitr regression] restore from pitr report 'internal error: find 0 snapshot records by name(cluster_pitr), expect only 1'

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20768]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

5d82985900d69743697807d3e57d3372c3f11fbf

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12292057401/job/34301937673

<img width="1864" alt="image" src="https://github.com/user-attachments/assets/7636b08e-263a-40ea-a86b-9c064e5620d2" />

log（utc+8）: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dmj%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-d34d2d8-20241215%5C%22%7D%20%7C%3D%20%60find%200%20snapshot%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221734283520000%22,%22to%22:%221734287120000%22%7D%7D%7D&schemaVersion=1&orgId=1

**注：（创建成功了，且通过show pitr可以看到记录）**
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/4b12592e-281e-4647-b683-6aec81495375" />

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/a0ef73e0-1e64-4599-bf8e-f3c92d56d70e" />

### Steps to Reproduce

```Markdown
trigger tke pitr workflow
```

**Comment by YANGGMM** [comment]
#https://github.com/matrixorigin/matrixone/pull/20789 已经合入，麻烦再测试下

**Comment by YANGGMM** [comment]
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dmj%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-pitr-nightly-e791f93-20241217%5C%22%7D%20%7C%3D%20%60%5Bcluster_pitr%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221734454752923%22,%22to%22:%221734459786256%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by YANGGMM** [comment]
集群级别恢复，租户恢复完以后去恢复pub info的时候用的是快照恢复的逻辑，需要改一下

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12395636340/job/34614559110

fixed
