### ISSUE TITLE
[Bug]: the size and row stats of the tables under mo_catalog db of the non-sys account are wrong

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#20762]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main,2.0-dev

### Commit ID

latest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the size and row stats of the tables under mo_catalog db of the non-sys account are wrong

### Steps to Reproduce

```Markdown
MOC qa and prod env.
```

**Comment by gouhongshen** [comment]
fixed
