### ISSUE TITLE
[Bug]: [1216 main tke regression] tpch 100g test panic.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20766]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d34d2d889c698a6a630881eab9c61ef793edf17e

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job url: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12339677001/job/34436749033

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/6c636d78-3b1f-4bef-a576-c433c40573f5" />

log: https://grafana.ci.matrixorigin.cn/explore?panes=%7B%22dmj%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-main-nightly-d34d2d889-20241215%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221734279797000%22,%22to%22:%221734279858000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger tke workflow
```

**Comment by Ariznawlll** [comment]
**出问题的commit： d34d2d889c698a6a630881eab9c61ef793edf17e**
<img width="1360" alt="image" src="https://github.com/user-attachments/assets/8fea728b-7e0a-4cde-9520-050619f1135e" />

**Comment by aunjgr** [comment]
PR已经合并

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12395187099

fixed
