### ISSUE TITLE
[Bug]: alter add and drop unique index concurrent test reported SQL parser error: table "__mo_index_unique_0193ce3e-b010-7f2a-9fd2-589f21018311" does not exist

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20775]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

d570bbdea

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

测试场景：alter add unique index和alter drop index 同时并发50测试（100个表）运行5分钟
测试结果：alter drop index 报错SQL parser error: table "__mo_index_unique_0193ce43-1fde-7bb4-af7d-216ee17065b8" does not exist（预期结果报错：internal error: Can't DROP 'index_65'; check that column/key exists）
测试复现步骤见Steps to Reproduce
<img width="1152" alt="企业微信截图_12bff27d-5c70-458b-9027-0f59b7739015" src="https://github.com/user-attachments/assets/90942d2c-d5d5-4a1f-bc57-3725c3049519" />

并发测试sql：
<img width="936" alt="企业微信截图_3832e612-2079-48d0-8590-4c6dc8f1f034" src="https://github.com/user-attachments/assets/0516a2bd-fb84-4ead-b9ae-504456326621" />

测试日志：
[test.log](https://github.com/user-attachments/files/18146542/test.log)

### Steps to Reproduce

```Markdown
1. git clone mo-load工具
2. 准备mo 100个表数据：
mysql -h 127.0.0.1 -udump -P6001 -p111 -e "drop database if exists concurrent_test;create database concurrent_test;"
for i in {1..100}; do mysql -h 127.0.0.1 -udump -P6001 -p111 -e "create table concurrent_test.index_$i(col1 bigint primary key auto_increment,col2 int);insert into concurrent_test.index_$i(col2) values(56),(222),(686),(9985)";done
4.执行测试：
cd mo-load
./start.sh -b concurrent_test -c cases/ddl/alter_add_drop_unique_index
```

**Comment by heni02** [comment]
此方法测试必现
相关issue：https://github.com/matrixorigin/matrixone/issues/19206

**Comment by heni02** [comment]
相同的并发测试场景，alter drop次级索引也是报错
<img width="1209" alt="企业微信截图_046f24ec-1242-41df-b617-4f91935143e0" src="https://github.com/user-attachments/assets/7ae5a786-b7c9-40d8-98f7-e9c3a55d47c7" />

测试sql:
<img width="843" alt="企业微信截图_09c32ca5-ec1d-4941-b879-a65448d8d5f2" src="https://github.com/user-attachments/assets/9480412a-ca22-4f03-a16e-c52f73ab2d62" />

ddl：
for i in {1..100}; do mysql -h 127.0.0.1 -udump -P6001 -p111 -e "create table concurrent_test.table_$i(col1 bigint primary key auto_increment,col2 int);insert into concurrent_test.table_$i(col2) values(56),(222),(686),(9985)";done

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test @aressu1985 @heni02 @DanielZhangQD

**Comment by heni02** [comment]
2.0-dev： 06354304c7daa5e4c104c84292559f431eaad942
confirm,closed
case已合入回归测试
<img width="1270" alt="企业微信截图_3d12f249-2678-4290-881a-1816c9a88620" src="https://github.com/user-attachments/assets/daeb43ba-5d8c-49b7-a64e-92e399ff44e9" />
