### ISSUE TITLE
[Bug]: lots of panic 'internal error: panic runtime error: index out of range [0] with length 0:" in cn during choas test (kill dn continously)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#20787]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

6a0b305

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 7C 28G
1*DN: 7C 28G
3*PROXY: 2C 5G
3*LOG: 1C 7G
- OS type:
- Others:
```

### Actual Behavior

test load:
1. run tpcc 10-10 
2. insert data to a table with 2 thread

and during the test, the chaos tool were continuously kill dn pod by interval 10 mins

then ,there were lots panic error "internal error: panic runtime error: index out of range [0] with length 0:"

<img width="1387" alt="image" src="https://github.com/user-attachments/assets/22b9c614-0b63-4e8b-876e-f776bdd06984" />

cn-log;
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22LqA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-6a0b305-202412162157%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60panic%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221734350400000%22,%22to%22:%221734364799000%22%7D%7D%7D&schemaVersion=1&orgId=1

dn-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%22LqA%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-chaos-6a0b305-202412162157%5C%22,%20matrixorigin_io_component%3D%5C%22CNSet%5C%22%7D%20%7C%3D%20%60long%20running%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221734350400000%22,%22to%22:%221734364799000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
test load:
1. run tpcc 10-10 
2. insert data to a table with 2 thread

and during the test, the chaos tool were continuously kill dn pod by interval 10 mins
```

**Comment by triump2020** [comment]
[PR](https://github.com/matrixorigin/matrixone/pull/20811)  had fixed the panic.

**Comment by triump2020** [comment]
@aressu1985  Pls test!

**Comment by aressu1985** [comment]
fixed
