### ISSUE TITLE
[Bug]: alter add foreign key concurrent 50 threads reported w-w conflict error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20783]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

d570bbdea6475b86f6f8f1531788a41adeb7a3d1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

测试场景：alter table add foreign key并发50执行5分钟
测试结果：sql报错w-w conflict
测试sql：alter table table_{id} add constraint fk_{id} foreign key(col2) references fk_01(col1);（100个表创建外键依赖fk_01 col1列）
![image](https://github.com/user-attachments/assets/d8e6eafb-7f51-4770-8857-616c1f8f70cf)

单独顺序执行是可以的
![image](https://github.com/user-attachments/assets/e891ef62-6a77-492a-9338-747387eaacc4)

ddl：
create table concurrent_test.fk_01(col1 int not null primary key,col2 int);insert into concurrent_test.fk_01 values (90,5983),(100,734),(190,50);
create table concurrent_test.table_$i(col1 bigint primary key auto_increment,col2 int)

另外同时并发alter add foreign和alter drop foreign key测试，两个sql也是会报w-w conflict
![image](https://github.com/user-attachments/assets/ea9c6863-c632-459c-922b-69f841afdf31)

### Steps to Reproduce

```Markdown
1. git clone mo-load工具
2. 准备mo 100个表数据：
 mysql -h 127.0.0.1 -udump -P6001 -p111 -e "drop database if exists concurrent_test;create database concurrent_test;create table concurrent_test.fk_01(col1 int not null primary key,col2 int);insert into concurrent_test.fk_01 values (90,5983),(100,734),(190,50);"

for i in {1..100}; do mysql -h 127.0.0.1 -udump -P6001 -p111 -e "create table concurrent_test.table_$i(col1 bigint primary key auto_increment,col2 int)";done
3.执行并发50测试
cd mo-load
./start.sh -h 127.0.0.1  -b concurrent_test -c cases/ddl/alter_add_drop_foreign_key/ （此命令是同时并发alter add和drop foreign key，如果只单独并发alter add，vim cases/ddl/alter_add_drop_foreign_key/run.yaml删除-name："alter_drop_fk"以下一段case，再执行该命令即可）

如果
```

**Comment by ouyuanning** [comment]
根本原因是当设计到外键的时候。是有更改外键表的schema的。而没有给外键表加锁造成的

**Comment by heni02** [comment]
待验证

**Comment by heni02** [comment]
2.0-dev:06354304c7daa5e4c104c84292559f431eaad942
confirm,closed
case已合入回归测试
<img width="1249" alt="企业微信截图_c650e125-4c80-4252-9d03-38dc71c4fcac" src="https://github.com/user-attachments/assets/6de7ff8c-ce65-4056-a51f-ebd5936c19fd" />
