### ISSUE TITLE
[Bug]: create fulltext index to varchar column panic. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20796]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

25b0a1806

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="790" alt="image" src="https://github.com/user-attachments/assets/a4929ae4-7549-4cad-9420-3a4281a3b480" />

### Expected Behavior

create fulltext index successfully.

### Steps to Reproduce

```Markdown
set experimental_fulltext_index=1;

create table fulltext_test(col1 bigint, col2 int, col3 varchar(200), col4 varchar(200));
alter table fulltext_test add primary key(col2);

load data local infile '/Users/ariznawl/Downloads/zhwiki-20241201-pages-articles-multistream-index.txt' into table test.fulltext_test fields terminated by ':' ESCAPED BY '\t' lines terminated by '\n';
create fulltext index full01 on fulltext_test(col3) with parser ngram;


hwiki-20241201-pages-articles-multistream-index.txt is large, please contact me
```

**Comment by cpegeric** [comment]
I think you can reproduce with the insert SQL below.   

insert into fulltext_test values (1000, 333, '安邁進國際影業股份有限公司', NULL);

or 

insert into fulltext_test values (1000, 333, 'a安邁進國際影業股份有限公司', NULL);
