### ISSUE TITLE
[Docs]: join mo in wechat

### ISSUE THREAD

**Issue by dengyunsheng250** [matrixorigin/matrixone#2080]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```markdown
第一步，登录github,在你选择的issue留下你的足迹，MO小助手会将相关issue分配给你
```

**Comment by dengn** [comment]
Hi @dengyunsheng250 , what help do you need? If you are not clear about the MatrixCamp event, please checkout this tutorial in both [chinese](https://github.com/matrixorigin/matrixone/blob/main/docs/cn/MatrixOne/MatrixCampEvent.md) and [english](https://github.com/matrixorigin/matrixone/issues/1997).
