### ISSUE TITLE
[Bug]: Concurrent test TAE reports panic, causing the service to crash

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#20833]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main, dev-2.0

### Commit ID

8e80c4479744f0c0304767566bbc9d6e4d9f549c

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="900" alt="1734578822943" src="https://github.com/user-attachments/assets/e23f40c5-0497-4edc-8250-33924029eb50" />

[yiming@matrixone matrixone]$ panic: todo

goroutine 1601 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*BaseTask).Cancel(...)
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/tasks/base.go:86
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*BaseTaskHandler).Enqueue(0xc00abcd5f0, {0x5979f48, 0xc0e4d82ea0})
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/tasks/handler.go:42 +0xf4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*BaseDispatcher).Dispatch(0xc00acfc7a0, {0x5979f48, 0xc0e4d82ea0})
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/tasks/dispatcher.go:57 +0x62
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*asyncJobDispatcher).TryDispatch(0xc00aeba360, {0x5979f48, 0xc0e4d82ea0})
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/dispatcher.go:83 +0x206
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*taskScheduler).Schedule(0xc00ae161c0, {0x5979f48, 0xc0e4d82ea0})
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/scheduler.go:164 +0x7a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*taskScheduler).ScheduleMultiScopedTxnTask(0xc00ae161c0, 0x0, 0x7, {0xc0d827c990, 0x1, 0x1}, 0xc0435dca40)
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/scheduler.go:104 +0xf7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).fireFlushTabletail(0xc000c94960, 0xc0342210e0, 0xc0ded42e00)
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:960 +0xab6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).checkFlushConditionAndFire(0xc000c94960, 0xc114b989c0, 0x0, 0x3faa038810000000)
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:1089 +0x851
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).scheduleFlush(0xc000c94960, 0xc114b989c0, 0x0)
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:1104 +0x53
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/checkpoint.(*runner).onDirtyEntries(0xc000c94960, {0xc00a1cdc08, 0x1, 0x0?})
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/db/checkpoint/runner.go:1119 +0x18e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:89 +0x1ea
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start in goroutine 726
	/home/yiming/workspace/performance/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:68 +0xe5

### Expected Behavior

The MO service is normal, without panic or crash

### Steps to Reproduce

```Markdown
1. 启动一个单cn的mo服务
 ./mo-service -launch ./etc/launch/launch.toml > out.log &
2. 运行测试组提供load并发测试：
2.1 准备mo 100个表数据：
mysql -h 127.0.0.1 -udump -P6001 -p111 -e "drop database if exists concurrent_test;create database concurrent_test;"
for i in {1..50}; do mysql -h 127.0.0.1 -udump -P6001 -p111 -e "create table concurrent_test.table_$i(col1 bigint primary key,col2 int, col3 varchar(20), index idx_col2(col2));insert into concurrent_test.table_$i(col1, col2, col3) values(1, 56, 'aa'),(2, 222, 'bb'),(3, 686, 'cc'),(4, 9985, 'dd')";done
2.2.执行测试：
cd mo-load
./start.sh -b concurrent_test -c cases/ddl/alter_modify_column > out.log
```

**Comment by w-zr** [comment]
Merged.

**Comment by heni02** [comment]
2.0-dev： 06354304c7daa5e4c104c84292559f431eaad942
confirm，closed
已合入回归case
<img width="1282" alt="企业微信截图_c0de8502-0e8b-4e3e-9ef6-0b390acc68d9" src="https://github.com/user-attachments/assets/0f6cee8a-ac24-430c-9f61-7145a1974b60" />
