### ISSUE TITLE
[Bug]: sysbench 100w insert 100 and 1000 threads running in the whole regression is different from running alone.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#20834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

d9b5330a2ccd9991365315bf86f529e7a2e331a1

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

**running alone job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12405885679/job/34633552504**

**insert 100 threads:**
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/5b7e2cf0-7b76-4052-ac43-78282ce64e9b" />
**insert 1000 threads:**
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/9e67bb89-1ea5-48aa-904f-02f8a3222718" />
**heap_profile:(utc+8  2024-12-19 08:56:50-2024-12-19 09:06:40)**
[heap_alone1219.zip](https://github.com/user-attachments/files/18192752/heap_alone1219.zip)
**malloc_profile:(utc+8  2024-12-19 08:56:50-2024-12-19 09:06:40)**
[malloc_alone1219.zip](https://github.com/user-attachments/files/18192755/malloc_alone1219.zip)
 **cpu profile:** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%221KO%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%27mo-search-nightly-d9b5330a2-20241219%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221734581890000%22,%22to%22:%221734582490000%22%7D%7D%7D&schemaVersion=1&orgId=1

**running in the whole regression job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12395187099**
**insert 100 threads:**
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/08d6608e-f6f4-4a9f-b6e0-0e4a97358981" />

**insert 1000 threads:**
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/abe4a437-1085-4a44-b91a-0002033b4cc8" />
**heap_profile:(utc+8   2024-12-19 12:18:10-2024-12-19 12:28:01)**
[heap_whole1219.zip](https://github.com/user-attachments/files/18192759/heap_whole1219.zip)
**malloc_profile:(utc+8  2024-12-19 12:18:10-2024-12-19 12:28:01)**
[malloc_whole1219.zip](https://github.com/user-attachments/files/18192761/malloc_whole1219.zip)
**cpu profile:** https://grafana.ci.matrixorigin.cn/explore?panes=%7B%221KO%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bnamespace%3D%27mo-main-nightly-d9b5330a2-20241218%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221734569810000%22,%22to%22:%221734570410000%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
trigger workflow
```

**Comment by XuPeng-SH** [comment]
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/490d6f3b-d4bb-4e11-8cb5-0153a9ea56a8" />
https://grafana.ci.matrixorigin.cn/explore?panes=%7B%221KO%22:%7B%22datasource%22:%22pyroscope%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bpod%3D%27nightly-regression-dis-tp-cn-kmvkf%27%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22pyroscope%22%7D%7D%5D,%22range%22:%7B%22from%22:%221734569810000%22,%22to%22:%221734570410000%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by Ariznawlll** [comment]
**in the whole regression：**
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/12536268321/job/34964426394

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/5662f7a2-5a35-4a7f-8a5d-a9b1f8f9fcd9" />
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/aeaf5631-0074-4bd4-a441-1aacfbf146f3" />

**running alone:**
