### ISSUE TITLE
[Bug]: blob length size less than max_allowed_packet ，but select blob reported ERROR  Got packet bigger than 'max_allowed_packet' bytes

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#20880]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

2.0-dev

### Commit ID

06354304c7daa5e4c104c84292559f431eaad942

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert 56.9MB大小压缩文件到blob类型，insert成功后select blob列报错Got packet bigger than 'max_allowed_packet' bytes
max_allowed_packet默认值为64M
```
mysql> create table table_blob(c1 int primary key,c2 blob);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into table_blob values(834,LOAD_FILE('/Users/heni/Downloads/blob_test_data/blob04.tar.gz'));
Query OK, 1 row affected (0.66 sec)

mysql> select length(c2) from table_blob;
+------------+
| length(c2) |
+------------+
|   56874074 |
+------------+
1 row in set (0.12 sec)

mysql> select * from table_blob;
ERROR 2020 (HY000): Got packet bigger than 'max_allowed_packet' bytes

mysql> SHOW VARIABLES like "%max_allowed_packet%";
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 67108864 |
+--------------------+----------+
1 row in set (0.00 sec)

```
mysql的客户端行为和mo不同，select blob返回NULL，也有max_allowed_packet的大小配置，参见mysql文档blob：
https://dev.mysql.com/doc/refman/8.4/en/blob.html
<img width="1439" alt="企业微信截图_d680dd76-6312-446b-9f2b-938e7d0b209a" src="https://github.com/user-attachments/assets/722b4a0a-8026-46f4-844f-db8846b02a24" />

### Steps to Reproduce

```Markdown
create table table_blob(c1 int primary key,c2 blob);
insert into table_blob values(834,LOAD_FILE('/Users/heni/Downloads/blob_test_data/blob04.tar.gz'));
select * from table_blob;
```

**Comment by qingxinhome** [comment]
该问题2.0.2估计来不及处理

**Comment by qingxinhome** [comment]
1. 在 MySQL 客户端中，--max-allowed-packet 选项是用来设置客户端与服务器之间允许的最大数据包大小。
这个选项影响客户端发送和接收数据包的最大大小。 如果你在执行 SQL 查询时遇到错误，比如查询返回的数据超出了 MySQL  客户端的默认包大小限制（例如：插入 BLOB 数据时），就会报错

你可以通过这个选项增加客户端的包大小限制。查看方式如下：
mysql --help | grep max-allowed-packet

![image](https://github.com/user-attachments/assets/20ccf87c-26df-436c-9b8b-91ce981d6894)
![image](https://github.com/user-attachments/assets/7cbdc64c-7b02-4355-94fc-3d830f3fa094)
但是注意：该配置项属于mysql客户端

2. mysql(或mo)服务器端也有相同的配置项 max_allowed_packet，需要确保客户端和服务器的设置都足够大，才能避免因包太大而导致的错误。如果你在客户端连接时指定了较大的包大小，但服务器端的设置较大，那么客户端仍然可能会拒绝请求。

**Comment by qingxinhome** [comment]
mo如何修改mysql客户端的max-allowed-packet配置：
[yiming@matrixone matrixone]$ mysql -h127.0.0.1 --max-allowed-packet=67108864 -P 6001 -udump -p111

**Comment by heni02** [comment]
2.0-dev commit:947a1258b5eede197a6ed7853ea117b34cd2f438
confirm,closed
<img width="1172" alt="企业微信截图_1c8a76d9-84cc-4409-9438-7eff16d8c417" src="https://github.com/user-attachments/assets/14da3271-6bdc-4a13-86c4-99d24a0aba35" />
<img width="1318" alt="企业微信截图_c02c73bd-acd7-4edf-850c-5f065828654f" src="https://github.com/user-attachments/assets/51234afb-31bb-4669-8108-78ecaeca9048" />
