### ISSUE TITLE
[Feature Request]: Mathematical Built-in function sinh()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2094]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

sinh(x)

[Hyperbolic sine](https://www.mathworks.com/help/matlab/ref/sinh.html).

* Syntax: sinh(x)
* Arguments: 
x — The angle, in radians. Values from the interval: -∞ < x < +∞. Type: Float64
* Returned value: 
Values from the interval: -∞ < sinh(x) < +∞. Type: Float64

Example

Query:

SELECT sinh(0);
Result:
```sql
mysql> SELECT sinh(0);
-> 0
```

The function should take different numeric kinds of input datatype as int, float, and return a float64.

### Describe implementation you've considered

An easy implementation could be use the Golang math sinh() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by xiw5** [comment]
I'd like to work on this issue

**Comment by dengn** [comment]
> I'd like to work on this issue

Sure. Please sign up for the event before being assigned: https://www.wjx.top/vm/Ys1rz1I.aspx

**Comment by xiw5** [comment]
Ok, I have done this

**Comment by dengn** [comment]
Feature implemented.
