### ISSUE TITLE
[Feature Request]: Mathematical Built-in function sqrt()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2097]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[SQRT(X)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_sqrt)

Returns the square root of a nonnegative number X.
```
mysql> SELECT SQRT(4);
        -> 2
mysql> SELECT SQRT(20);
        -> 4.4721359549996
mysql> SELECT SQRT(-16);
        -> NULL
```
**The function should take different numeric kinds of input datatype as int, float, and return a float64.**

### Describe implementation you've considered

An easy implementation could be using the Golang math sqrt() function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by caaatch22** [comment]
hi, I'd like to work on this issue.
