### ISSUE TITLE
[Feature Request]: Mathematical Built-in function rand() 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2099]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[RAND([N])](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_rand)

Returns a random floating-point value v in the range 0 <= v < 1.0.

One implication of this behavior is that for equal argument values, [RAND(N)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_rand) returns the same value each time, and thus produces a repeatable sequence of column values. In the following example, the sequence of values produced by RAND(3) is the same both places it occurs.

If an integer argument N is specified, it is used as the seed value:

* With a constant initializer argument, the seed is initialized once when the statement is prepared, prior to execution.

* With a nonconstant initializer argument (such as a column name), the seed is initialized with the value for each invocation of [RAND()](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_rand).
3. Example:

```
mysql> SELECT i, RAND() FROM t;
+------+------------------+
| i    | RAND()           |
+------+------------------+
|    1 | 0.61914388706828 |
|    2 | 0.93845168309142 |
|    3 | 0.83482678498591 |
+------+------------------+
3 rows in set (0.00 sec)

mysql> SELECT i, RAND(3) FROM t;
+------+------------------+
| i    | RAND(3)          |
+------+------------------+
|    1 | 0.90576975597606 |
|    2 | 0.37307905813035 |
|    3 | 0.14808605345719 |
+------+------------------+
3 rows in set (0.00 sec)

mysql> SELECT i, RAND() FROM t;
+------+------------------+
| i    | RAND()           |
+------+------------------+
|    1 | 0.35877890638893 |
|    2 | 0.28941420772058 |
|    3 | 0.37073435016976 |
+------+------------------+
3 rows in set (0.00 sec)

mysql> SELECT i, RAND(3) FROM t;
+------+------------------+
| i    | RAND(3)          |
+------+------------------+
|    1 | 0.90576975597606 |
|    2 | 0.37307905813035 |
|    3 | 0.14808605345719 |
+------+------------------+
3 rows in set (0.01 sec)
```

### Describe implementation you've considered

An feasible implementation could be using the Golang math rand library.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by YL1028K** [comment]
i'd like this one~

**Comment by dengn** [comment]
> i'd like this one~

Issue assigned. Please add the MatrixOne community assistant "MatrixOrigin001" as a WeChat friend if you haven't done so.
