### ISSUE TITLE
[Bug]: ut test failed in TestGlobalCheckpoint1

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#21010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

lastest

### Other Environment Information

```Markdown
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/user-attachments/assets/d328edf0-ff60-43b1-a15c-82d5e2d80aa6)

### Steps to Reproduce

```Markdown
https://github.com/matrixorigin/matrixone/actions/runs/12543056720/job/34973638340?pr=21007
```

**Comment by XuPeng-SH** [comment]
fixed
