### ISSUE TITLE
[Feature Request]: Mathematical Built-in function sign()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2102]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of clickhouse.  
2. Function syntax  

[sign(x) ](https://clickhouse.com/docs/en/sql-reference/functions/math-functions/#signx)
Returns the sign of a real number.  

Syntax
```
sign(x)
```
Arguments
```
x — Values from -∞ to +∞. Support all numeric types in ClickHouse.
```
Returned value
```
-1 for x < 0
0 for x = 0
1 for x > 0
```
3. Examples

Sign for the zero value:
```
SELECT sign(0);
Result:

┌─sign(0)─┐
│       0 │
└─────────┘
```
Sign for the positive value:
```
SELECT sign(1);
Result:

┌─sign(1)─┐
│       1 │
└─────────┘
```
Sign for the negative value:
```
SELECT sign(-1);
Result:

┌─sign(-1)─┐
│       -1 │
└──────────┘
```
### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by mooleetzi** [comment]
hi I'd like to work on this issue

**Comment by mooleetzi** [comment]
I finished this issue，but after my coding, the unit test output is below, could you please tell me how to fix them
<img width="922" alt="截屏2022-05-11 13 07 13" src="https://user-images.githubusercontent.com/42628885/167773167-935eb5a3-e208-43da-988e-221e6adefe43.png">

**Comment by mooleetzi** [comment]
> ### Is there an existing issue for the same feature request?
> * [x]  I have checked the existing issues.
> 
> ### Is your feature request related to a problem?
> _No response_
> 
> ### Describe the feature you'd like
> 1. Follow the syntax and behavior of clickhouse.
> 2. Function syntax
> 
> [sign(x) ](https://clickhouse.com/docs/en/sql-reference/functions/math-functions/#signx) Returns the sign of a real number.
> 
> Syntax
> 
> ```
> sign(x)
> ```
> 
> Arguments
> 
> ```
> x — Values from -∞ to +∞. Support all numeric types in ClickHouse.
> ```
> 
> Returned value
> 
> ```
> -1 for x < 0
> 0 for x = 0
> 1 for x > 0
> ```
> 
>  3. Examples
> 
> Sign for the zero value:
> 
> ```
> SELECT sign(0);
> Result:
> 
> ┌─sign(0)─┐
> │       0 │
> └─────────┘
> ```
> 
> Sign for the positive value:
> 
> ```
> SELECT sign(1);
> Result:
> 
> ┌─sign(1)─┐
> │       1 │
> └─────────┘
> ```
> 
> Sign for the negative value:
> 
> ```
> SELECT sign(-1);
> Result:
> 
> ┌─sign(-1)─┐
> │       -1 │
> └──────────┘
> ```
> 
> ### Describe implementation you've considered
> ### Documentation, Adoption, Use Case, Migration Strategy
> Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.
> 
> ### Additional information

I finished this issue，but after my coding, the unit test output is below, could you please tell me how to fix them
<img width="922" alt="截屏2022-05-11 13 07 13" src="https://user-images.githubusercontent.com/42628885/167773167-935eb5a3-e208-43da-988e-221e6adefe43.png">
