### ISSUE TITLE
[Feature Request]: String function ascii()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2106]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[ASCII(str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ascii)

Returns the numeric value of the leftmost character of the string str. Returns 0 if str is the empty string. Returns NULL if str is NULL. If the input is not in the ASCII range, return NULL. [ASCII()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ascii) works for 8-bit characters.
```sql
mysql> SELECT ASCII('2');
        -> 50
mysql> SELECT ASCII(2);
        -> 50
mysql> SELECT ASCII('dx');
        -> 100
```
The function should take string, int, float type as input, and returns uint8 type. And only the leftmost character of the string str works. 
### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by wuliuqii** [comment]
I'd like to work on this issue.

**Comment by wuliuqii** [comment]
I have a question. 

> If the input is not in the ASCII range, return NULL.

Does this mean that if the input is Chinese, , NULL will be returned, which is not the same as the return value of mysql

```
mysql> select ascii("你好");
+-----------------+
| ascii("你好")   |
+-----------------+
|             228 |
+-----------------+
1 row in set (0.00 sec)
```

**Comment by dengn** [comment]
> I have a question.
> 
> > If the input is not in the ASCII range, return NULL.
> 
> Does this mean that if the input is Chinese, , NULL will be returned, which is not the same as the return value of mysql
> 
> ```
> mysql> select ascii("你好");
> +-----------------+
> | ascii("你好")   |
> +-----------------+
> |             228 |
> +-----------------+
> 1 row in set (0.00 sec)
> ```

MySQL's ASCII function is supposed to work only with 8-bit characters. The result with Non-ASCII characters are wrong. To get the decimal value of Non-ASCII characters, [ORD()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ord) function is proposed.
So we should not follow this wrong behavior of MySQL, we could implement this function only with ASCII characters within 128.
