### ISSUE TITLE
[Feature Request]: String function bit_length()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2107]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[BIT_LENGTH(str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bit-length)

Returns the length of the string str in bits.

```sql
mysql> SELECT BIT_LENGTH('text');
        -> 32
```
The function should take date or datetime type as input, and return uin16 type.
### Describe implementation you've considered

You can implement this function based on the function `length()` we have finished.
### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by lyfer233** [comment]
I'd like to work on this issue.
