### ISSUE TITLE
[Feature Request]: String function empty()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2108]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Checks whether the input string is empty.

* Syntax: empty(x)
A string is considered non-empty if it contains at least one byte, even if this is a space or a null byte.

* Arguments: x — Input value. Type: String
* Returned value: Returns 1 for an empty string or 0 for a non-empty string. Type: uint8

```sql
mysql> SELECT empty('');
        -> 1
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by e11jah** [comment]
I'd like to work on this issue

**Comment by e11jah** [comment]
PTAL @dengn

**Comment by dengn** [comment]
> I'd like to work on this issue

Issue assigned. Please add the MatrixOne community assistant "MatrixOrigin001" as a WeChat friend if you haven't done so.

**Comment by dengn** [comment]
Feature implemented.
