### ISSUE TITLE
[Feature Request]: String function notEmpty()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2109]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Checks whether the input string is non-empty.

* Syntax: notEmpty(x)
A string is considered non-empty if it contains at least one byte, even if this is a space or a null byte.

* Arguments: x — Input value. Type: String
* Returned value: Returns 1 for a non-empty string or 0 for an empty string. Type: uint8

```sql
mysql> SELECT notEmpty('text');
        -> 1
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by chenlx0** [comment]
Hi, I would like to work on this issue :)
