### ISSUE TITLE
[Feature Request]: String function bin()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2110]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[BIN(N)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bin)

Returns a string representation of the binary value of N, where N is an integer number. This is equivalent to [CONV(N,10,2)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_conv). Returns NULL if N is NULL.
```sql
mysql> SELECT BIN(12);
        -> '1100'
```
The function should take int type as input, and return string type.
### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by e11jah** [comment]
I'd like to work on this issue

**Comment by e11jah** [comment]
I have implemented this feature in #2293 , PTAL @dengn

**Comment by dengn** [comment]
Feature implemented.
