### ISSUE TITLE
[Feature Request]: String function concat()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2111]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[CONCAT(str1,str2,...)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat)

Returns the string that results from concatenating the arguments. May have one or more arguments.   
If all arguments are nonbinary strings, the result is a nonbinary string. If the arguments include any binary strings, the result is a binary string. A numeric argument is converted to its equivalent nonbinary string form.

[CONCAT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat) returns NULL if any argument is NULL.
```sql
mysql> SELECT CONCAT('My', 'S', 'QL');
        -> 'MySQL'
mysql> SELECT CONCAT('My', NULL, 'QL');
        -> NULL
mysql> SELECT CONCAT(14.3);
        -> '14.3'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by lisirrx** [comment]
I'd like to work on this issue

**Comment by dengn** [comment]
Already implemented. @lisirrx
