### ISSUE TITLE
[Feature Request]: String function insert()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2113]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[INSERT(str,pos,len,newstr)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_insert)

* Returns the string str, with the substring beginning at position pos and len characters long replaced by the string newstr.   
* Returns the original string if pos is not within the length of the string. Replaces the rest of the string from position pos if len is not within the length of the rest of the string. Returns NULL if any argument is NULL.
```sql
mysql> SELECT INSERT('Quadratic', 3, 4, 'What');
        -> 'QuWhattic'
mysql> SELECT INSERT('Quadratic', -1, 4, 'What');
        -> 'Quadratic'
mysql> SELECT INSERT('Quadratic', 3, 100, 'What');
        -> 'QuWhat'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by azhsmesos** [comment]
I'd like to try it. Can I be assigned？
