### ISSUE TITLE
[Feature Request]: String function locate()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2114]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[LOCATE(substr,str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_locate), [LOCATE(substr,str,pos)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_locate)

* The first syntax returns the position of the first occurrence of substring substr in string str.   
* The second syntax returns the position of the first occurrence of substring substr in string str, starting at position pos. Returns 0 if substr is not in str. Returns NULL if any argument is NULL.
```sql
mysql> SELECT LOCATE('bar', 'foobarbar');
        -> 4
mysql> SELECT LOCATE('xbar', 'foobar');
        -> 0
mysql> SELECT LOCATE('bar', 'foobarbar', 5);
        -> 7
```

### Describe implementation you've considered

An easy implementation could be using the official Golang function.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by YANGGMM** [comment]
I'd like to work on this issue
