### ISSUE TITLE
[Feature Request]: String function oct()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2115]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Follow the syntax and behavior of mysql 8.0 
2. Function syntax

[OCT(N)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_oct)

Returns a string representation of the octal value of N, where N is an integer number. This is equivalent to [CONV(N,10,8)](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_conv). Returns NULL if N is NULL.
```sql
mysql> SELECT OCT(12);
        -> '14'
```

The function should take int type as input, and return string type.

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by lawrshen** [comment]
hi, I want to do this job.
