### ISSUE TITLE
[Feature Request]: String function lengthUTF8()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2116]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

`lengthUTF8()` with alias `char_length()`

Returns the length of a string in Unicode code points (not in characters), assuming that the string contains a set of bytes that make up UTF-8 encoded text. If this assumption is not met, it returns some result (it does not throw an exception).
The result type is UInt64.

```sql
mysql> SELECT lengthUTF8('你好');
        -> 2
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by coderzc** [comment]
I want to solve this problem

**Comment by dengn** [comment]
> I want to solve this problem

Issue assigned. Please add the MatrixOne community assistant "MatrixOrigin001" as a WeChat friend if you haven't done so.

**Comment by dengn** [comment]
Feature implemented.
