### ISSUE TITLE
[Feature Request]: String function startsWith()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2117]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

*Syntax: 
startsWith(str,prefix) 

*Behavior:
Returns 1 whether string starts with the specified prefix, otherwise it returns 0.This function is case sensitive.

`SELECT startsWith('Spider-Man', 'Spi');`

*Returned values:

1, if the string starts with the specified prefix.
0, if the string does not start with the specified prefix.

```sql
mysql> SELECT startsWith('Spider-Man', 'Spi');
        -> 1
mysql> SELECT startsWith('Spider-Man', 'spi');
        -> 0
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by whileskies** [comment]
I'd like to work on this issue.

**Comment by dengn** [comment]
Feature implemented.
