### ISSUE TITLE
[Feature Request]: String function endsWith()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2118]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

* Syntax: 
endsWith(str, suffix) 

* Behavior:
Returns whether to end with the specified suffix. Returns 1 if the string ends with the specified suffix, otherwise it returns 0. This function is case sensitive. 

`SELECT endsWith('Spider-Man', 'Man');`

* Returned values:

1, if the string ends with the specified suffix.
0, if the string does not end with the specified suffix.

```sql
mysql> SELECT endsWith('Spider-Man', 'Man');
        -> 1
mysql> SELECT endsWith('Spider-Man', 'man');
        -> 0
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.3.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

### Additional information

**Comment by chaixuqing** [comment]
I'd like to work on this issue

**Comment by dengn** [comment]
> I'd like to work on this issue

Issue assigned. Good luck!

**Comment by chaixuqing** [comment]
I got this error when testing endsWith()  function with some data，endsWith() function has returned successfully.
 I'd like to ask how to debug this error?

> mysql> select endswith(name,"y") from names;
ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [1] with length 1: goroutine 720 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2541f40?, 0xc00056e3d8})
        /home/xuqingchai/matrixone/pkg/common/moerr/error.go:76 +0x53
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run.func1()
        /home/xuqingchai/matrixone/pkg/sql/compile/exec.go:85 +0x31
panic({0x2541f40, 0xc00056e3d8})
        /us

**Comment by broccoliSpicy** [comment]
> I got this error when testing endsWith() function with some data，endsWith() function has returned successfully. I'd like to ask how to debug this error?
> 
> > mysql> select endswith(name,"y") from names;
> > ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [1] with length 1: goroutine 720 [running]:
> > runtime/debug.Stack()
> > /usr/local/go/src/runtime/debug/stack.go:24 +0x65
> > github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2541f40?, 0xc00056e3d8})
> > /home/xuqingchai/matrixone/pkg/common/moerr/error.go:76 +0x53
> > github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run.func1()
> > /home/xuqingchai/matrixone/pkg/sql/compile/exec.go:85 +0x31
> > panic({0x2541f40, 0xc00056e3d8})
> > /us

It's a enigma for me to diagnose the cause with this limited information, I may have some guesses but diffident to say it, could you push your code to your repo or maybe make a pull request, so that I can see your code

**Comment by chaixuqing** [comment]
> > I got this error when testing endsWith() function with some data，endsWith() function has returned successfully. I'd like to ask how to debug this error?
> > > mysql> select endswith(name,"y") from names;
> > > ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [1] with length 1: goroutine 720 [running]:
> > > runtime/debug.Stack()
> > > /usr/local/go/src/runtime/debug/stack.go:24 +0x65
> > > github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2541f40?, 0xc00056e3d8})
> > > /home/xuqingchai/matrixone/pkg/common/moerr/error.go:76 +0x53
> > > github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Run.func1()
> > > /home/xuqingchai/matrixone/pkg/sql/compile/exec.go:85 +0x31
> > > panic({0x2541f40, 0xc00056e3d8})
> > > /us
> 
> It's a enigma for me to diagnose the cause with this limited information, I may have some guesses but diffident to say it, could you push your code to your repo or maybe make a pull request, so that I can see your code

I'm sorry I didn't provide you with enough information. I have push my code to my repo now. https://github.com/chaixuqing/matrixone/commit/fbbddb5b721f4f2d7ba87d7f0649249c8ed9ce1f

**Comment by broccoliSpicy** [comment]
I think what happened in this error is possibly this:
you second argument here is a constant, whereas you only implemented the function in the situation where the second argument is also a attribute name, when you try to index the second vector, which has only length 1, boo, segmentation fault

perhaps you need to implement another function when the second argument is a constant, do we need special treatment when the first argument is also constant, huh, I am not familiar with the endsWith function's semantic...

I think the builtin power function may offer some neat examples on how to distinguish constant/(attribute name) arguments

**Comment by dengn** [comment]
Feature implemented.
