### ISSUE TITLE
[Enhancement]: commit specification

### ISSUE THREAD

**Issue by noneback** [matrixorigin/matrixone#2126]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

We need a commit specification to standardize our commit message format and limit the commit number in a pr

### Why is this needed ?

For further development.For beginners encountering matrixone

**Comment by JinHai-CN** [comment]
Thank you for your nice comments, we will improve incoming commit messages.

**Comment by noneback** [comment]
> 

It is a task that should be done as soon as possible for the reason that it is much harder when the project grows. There are some duplicated and meaningless commit messages. It is not tolerable if you wish more developers to join this community.

**Comment by yingfeng** [comment]
The PR is squashed into single commit before it's merge into the main repo. The number of commits within a PR is not limited, and might be chaotic, but they are refined when squashing.

**Comment by dengn** [comment]
> > Thank you for your nice comments, we will standardize the commits.
> 
> It is a task that should be done as soon as possible for the reason that it is much harder when the project grows. There are some duplicated and meaningless commit messages. It is not tolerable if you wish more developers to join this community.

Thanks for pointing this out. I'm starting a [discussion](https://github.com/matrixorigin/matrixone/discussions/2155) at for this topic, all proposals and comments are welcome.
