### ISSUE TITLE
[Refactoring]:  fix sca problems

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2133]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?
For now, several code files in our repo are undesirable from the perspective of static analysis tools, please fix these questions asap.

You can execute sca locally by following steps:
```markdown

1. `make install-static-check-tools`
2. `make static-check`
```

### Describe the solution you'd like

check every warning and fix it.

**Comment by sukki37** [comment]
An sca result in 20220331 is as follows:
[lint.result.zip](https://github.com/matrixorigin/matrixone/files/8401853/lint.result.zip)

**Comment by sukki37** [comment]
220506 Updated:
The following files still failed static check:
```
cmd/db-server/debug
cmd/db-server/main
pkg/compress/compress_test
pkg/container/batch/batch
pkg/container/nulls/nulls_test
pkg/container/ring/approxcd/approx
pkg/container/ring/approxcd/types
pkg/container/types/bytes_test
pkg/container/vector/vector_test
pkg/defines/type
pkg/errno/errcode
pkg/frontend/epochgc_test
pkg/frontend/mysql_cmd_executor
pkg/frontend/mysql_cmd_executor_test
pkg/frontend/mysql_protocol_test
pkg/rpcserver/codec
pkg/rpcserver/server
pkg/rpcserver/server_test
pkg/sort/asc/varchar/sort
pkg/sort/desc/varchar/sort
pkg/sql/colexec/connector/connector
pkg/sql/colexec/order/order
pkg/sql/parsers
pkg/sql/parsers/dialect/mysql/mysql_lexer
pkg/sql/parsers/scanner/scanner_test
pkg/sql/parsers/tree/precedence
pkg/sql/plan/create_table
pkg/sql/plan/name
pkg/sql/plan2/build_expr
pkg/sql/plan2/build_from
pkg/sql/plan2/build_select
pkg/sql/plan2/build_util
pkg/sql/plan2/function
pkg/sql/plan2/mock
pkg/sql/protocol/protocol
pkg/sql/protocol/protocol_test
pkg/vm/engine/format
pkg/vm/engine/memEngine/relation
pkg/vm/engine/tpe/descriptor/types
pkg/vm/engine/tpe/doc
pkg/vm/engine/tpe/engine/database
pkg/vm/engine/tpe/engine/relation
pkg/vm/engine/tpe/orderedcodec/constants
pkg/vm/engine/tpe/orderedcodec/types
pkg/vm/engine/tpe/tuplecodec/computationhandler_test
pkg/vm/engine/tpe/tuplecodec/cubekv
pkg/vm/engine/tpe/tuplecodec/cubekv_test
pkg/vm/engine/tpe/tuplecodec/decoder
pkg/vm/engine/tpe/tuplecodec/descriptorhandler
pkg/vm/engine/tpe/tuplecodec/encoder
pkg/vm/engine/tpe/tuplecodec/indexhandler
pkg/vm/engine/tpe/tuplecodec/memorykv
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter_test
pkg/vm/engine/tpe/tuplecodec/serialize
pkg/vm/engine/tpe/tuplecodec/util
pkg/vm/pipeline/pipeline
```

details refered to [lint-b2cfd19.txt](https://github.com/matrixorigin/matrixone/files/8637793/lint-b2cfd19.txt)

**Comment by cnutshell** [comment]
Linter `stylecheck` doesn't work now.
```bash
golangci-lint run --disable-all -E stylecheck
WARN [linters context] stylecheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
```

**Comment by cnutshell** [comment]
> Linter `stylecheck` doesn't work now.
> 
> ```shell
> golangci-lint run --disable-all -E stylecheck
> WARN [linters context] stylecheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
> ```

The same as linter `rowserrcheck`.

**Comment by cnutshell** [comment]
Now with `errcheck` disabled, it is likely that linter marked cases fade away, for those commits that is newer than `00b87be7` under branch main.

This could be verified via the following command:
```bash
golangci-lint run \
    -E misspell -E exportloopref -E rowserrcheck -E depguard \
    -D unconvert -E prealloc -E gofmt -E stylecheck -D errcheck
```

For cases marked by `errcheck`, I would make specific issues for people who take charge of relevant package.

**Comment by cnutshell** [comment]
Now all the cases marked via `errcheck` are covered.
