### ISSUE TITLE
[Bug]: several unit tests failed  under race 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2134]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):866518b334ff1c44d276ec52f08025141760ab92
- Hardware parameters:16c64g
- OS type:ubuntu
- Others:
```

### Actual Behavior

ut failed. Please refer to the details in the attachment.
[ut_with_race.log.zip](https://github.com/matrixorigin/matrixone/files/8401878/ut_with_race.log.zip)

### Steps to Reproduce

```markdown
execute `make ut SKIP_TEST=""`
```

**Comment by yingfeng** [comment]
# FAILED CASES:
--- FAIL: Test_PCI_stall (4.00s)
--- FAIL: Test_load (0.06s)
--- FAIL: TestDateComparison (0.05s)
--- FAIL: TestAOEStorage (24.38s)
--- FAIL: TestAOEEngine (35.33s)

**Comment by fengttt** [comment]
Let's rotate this bug to right people, fix the case that he/she owns and pass to the next, till all fixed.

**Comment by fengttt** [comment]
First, round, to @m-schen .   TestDateComparison etc are due to scope.MergeRun.   Please fix, and pass to next batch.   I cannot repro TestExpXXXX test races, but according to Yingfeng, can repro on mac.   If you can repro, pass it to right owner, otherwise, give it to Yingfeng and ask him to repro.

**Comment by cnutshell** [comment]
[2022-05-07 19:19:43 +0800] [run_tests] [INF] Refer to /home/cgk/scratch//20220507190931-UT-Report.out for details
#============================================================
# Post testing
#============================================================
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: ‘pkg/vm/engine/aoe/test/*’: No such file or directory
cover: open coverage.out: no such file or directory
#============================================================
# Total: 931; Passed: 927; Failed: 4; Unknown: 0
#
# FAILED CASES:
--- FAIL: TestDateComparison (0.02s)
--- FAIL: TestDateTimeToDate (0.00s)
--- FAIL: TestDatetimeToWeekday (0.00s)
--- FAIL: TestAOEEngine (39.12s)

# UNKNOWN CASES:


# BUILD FAILED in UT:
echo ""

# Code Coverage Summary:


#============================================================
[2022-05-07 19:19:43 +0800] [ut_summary] [INF] UNIT TESTING FAILED !!!

**Comment by cnutshell** [comment]
#2436

**Comment by cnutshell** [comment]
Failed unit tests includes:
- race condition
- code bug

**Comment by sukki37** [comment]
Closed. Enable race check by https://github.com/matrixorigin/matrixone/pull/2486
