### ISSUE TITLE
[Bug]: the result of bit_or is incorrect after merged into main

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2168]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (id CHAR(1), number INT);
INSERT INTO t1 VALUES('a',111),('a',110),('a',100), ('a',000),('b',001),('b',011);
select id, BIT_OR(number) FROM t1 GROUP BY id;
+------+----------------------+
| id   | bit_or(number)       |
+------+----------------------+
| a    | 18446744073709551615 |
| b    | 18446744073709551615 |
+------+----------------------+

### Expected Behavior

In original commit as following.
commit 350a811a4275c66f4a02c3019e156c836f1dd32b (HEAD -> aggfunfinish, origin/aggfunfinish)
Merge: 6b5119d3 470ed928
Author: NTH19 <3310288189@qq.com>
Date:   Sat Apr 2 10:35:59 2022 +0800

select id, BIT_OR(number) FROM t1 GROUP BY id;
+------+----------------+
| id   | bit_or(number) |
+------+----------------+
| a    |            111 |
| b    |             11 |
+------+----------------+
2 rows in set (0.01 sec)

**Comment by nnsgmsone** [comment]
The following code has a problem filling the initial value, which should be filled with 0.
``` 
// set all empty to ^uint64(0)
    for i := 0; i < size; i++ {
       r.Values[n+i] = ^uint64(0)                                                                                                                                                                             
    }
```

**Comment by domingozhang** [comment]
@NTH19 Please check

**Comment by NTH19** [comment]
> @NTH19 Please check
In bitoring.go 138lines Grows function 
    
  Change r.Values[n+i] = ^uint64(0)  to   r.Values[n+i] = 0                                                                                                                                                                       
I am so sorry that I forgot change it

**Comment by NTH19** [comment]
> > @NTH19 Please check
> 
> In bitoring.go 138lines Grows function 
> Change r.Values[n+i] = ^uint64(0)  to   r.Values[n+i] = 0                                                                                                                                                                       
> I am so sorry that I forgot change it
> @domingozhang 

Could you close this issue?@dominggozhang

**Comment by NTH19** [comment]
> > @NTH19 Please check
> 
> In bitoring.go 138lines Grows function 
> Change r.Values[n+i] = ^uint64(0)  to   r.Values[n+i] = 0                                                                                                                                                                       
> I am so sorry that I forgot change it
> @domingozhang 

Could you close this issue?@domingozhang
