### ISSUE TITLE
[Bug]: Type Error when loading data

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2181]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):62f941688c724db
- Hardware parameters: 8c16G
- OS type: darwin/m1
- Others:
```

### Actual Behavior

Somethin wrong when handling type conversion in loading data. An example is as follows:

```
create table test(a int(11));
load data infile 'test.csv' into table test FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
```
error is:

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/77312370/162675927-b6ce3a9b-ef96-46fe-9b88-85ff3fc443c5.png">

data in `test.csv` is as following:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/77312370/162675800-8895b656-407a-46d4-81af-99d12a63da2b.png">

BTW, I've checked that `insert` those data directly is ok.

**Comment by daviszhen** [comment]
13.0 is the float, but the `a` is the `int`。

**Comment by sukki37** [comment]
I think the `load` behavior should be the same as `insert` in this Implicit type conversion case.

**Comment by daviszhen** [comment]
The `load` is handled by the frontend directly. It bypasses the computation layer and writes the data through the cube driver. That leads to the difference. 
We can change it later. But, that needs the extra development.

**Comment by fengttt** [comment]
Frontend should just send the data file to backend.

**Comment by JinHai-CN** [comment]
Bug is fixed.
