### ISSUE TITLE
[Feature Request]: Support installation from AUR

### ISSUE THREAD

**Issue by Y7n05h** [matrixorigin/matrixone#2182]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
No
```

### Describe the feature you'd like

I have package MatrixOne and put the packaging script in [AUR](https://aur.archlinux.org/packages/matrixone). 
Therefore, ArchLinux users can obtain the packaging script through `AUR`, and let a tool called `makepkg` execute the script, download the source code from the github release, complete the build, and finally get the software package made for ArchLinux.
**`AUR` distributes neither compiled binaries nor source code.**
It only distributes scripts that instruct `makepkg` to "download the source, compile it, and package it in a format accepted by ArchLinux's package manager".

I will continue to maintain the packaging scripts in AUR in the future.

**Comment by dengn** [comment]
Thanks for this nice feature. Please help to update the installation doc.
