### ISSUE TITLE
[Bug]:  Wrong Result for `select`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2189]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8f1807de2af0059193cfed1d750dbfec8f1aecff
- Hardware parameters:32C64G
- OS type:Ubuntu
- Others:
```

### Actual Behavior

The test data & schema is the same with #2186 

The result set of mo and MySQL is different.

MO Result is an empty set which obviously incorrect:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/77312370/162785313-99f52c23-fd59-48ab-996b-0d373bf1bbfc.png">

And the resulte set of MySQL is as follows:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/77312370/162785424-f9f504f1-66c8-4f19-adbb-5e16bed9169a.png">

**Comment by nnsgmsone** [comment]
The grouping issue has been resolved, although avg(DepDelay > 10) is currently not supported for the time being.

**Comment by sukki37** [comment]
> The grouping issue has been resolved, although avg(DepDelay > 10) is currently not supported for the time being.

if avg(DepDelay > 10) is not supported now, should an error message be given instead of just returning emptyset？

**Comment by nnsgmsone** [comment]
yes
