### ISSUE TITLE
[Bug]: Wrong Result for `GROUP BY`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2190]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8f1807de2af0059193cfed1d750dbfec8f1aecff
- Hardware parameters:32C64G
- OS type:Ubuntu
- Others:
```

### Actual Behavior

The test data & schema are the same as #2186.

The same key is not grouped into the same bucket.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/77312370/162787357-3231a6d9-a766-437d-8ceb-2565f1c6a0a0.png">

**Comment by nnsgmsone** [comment]
fixed by #2194
