### ISSUE TITLE
[Bug]: storage_test.go wont compile

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#2192]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): v0.3.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

pkg/vm/driver/test/storage_test.go won't compile.   LogDBGetter not declared by package raftstore.

### Expected Behavior

Fix compilation, or remove dead test.

### Steps to Reproduce

```markdown
compilation error
```

### Additional information

This error is visible after a clean import into vscode.   Please fix.

**Comment by jiangxinmeng1** [comment]
To use and compile LogDBGetter, tag matrixone_test needs to be added. 
```
go test -tags matixone_test
```

**Comment by fengttt** [comment]
> To use and compile LogDBGetter, tag matrixone_test needs to be added.
> 
> ```
> go test -tags matixone_test
> ```

This is not a solution.  It is a go file that cannot be compiled, before test.

**Comment by sukki37** [comment]
this ut only can run with '-tags matrixone_test' for it will get some internal data from cube which cannot be access in any condition except ut.

**Comment by fengttt** [comment]
> this ut only can run with '-tags matrixone_test' for it will get some internal data from cube which cannot be access in any condition except ut.

Why does this matter?   I am seeing an error in default setup and why should I care what tags do?
