### ISSUE TITLE
[Bug]: MO killed by itself during a SSB query

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2195]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ebb2eca68e8712efe2dff34f26fcc025ed5dcf01
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select c_city, s_city, d_year, sum(lo_revenue) as lo_revenue from lineorder join dates on lo_orderdate = d_datekey join customer on lo_custkey = c_custkey join supplier on lo_suppkey = s_suppkey where (c_city='UNITED KI1' or c_city='UNITED KI5') and (s_city='UNITED KI1' or s_city='UNITED KI5') and year(d_datekey) between 1992 and 1997 group by c_city, s_city, d_year order by d_year asc, lo_revenue desc;
ERROR 2013 (HY000): Lost connection to MySQL server during query

[q3.3.txt](https://github.com/matrixorigin/matrixone/files/8469046/q3.3.txt)

**Comment by nnsgmsone** [comment]
fixed by #2212
