### ISSUE TITLE
[Bug]:the result of the sql  on 3-nodes with aoe and tpe storage is error. 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#2198]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bc237b2474b52d99cf4f54097f5c7297b90e6e10
- Hardware parameters:mac
- OS type:
- Others:
```

### Actual Behavior

The result is wrong.
![WechatIMG2102](https://user-images.githubusercontent.com/60595215/162893452-5574883f-c7b3-4652-824b-46c6304fb647.jpeg)

### Expected Behavior

the right result is :
![x](https://user-images.githubusercontent.com/60595215/162894163-1810698d-134a-41ca-88e7-822f5bfedb0b.jpg)
![x2](https://user-images.githubusercontent.com/60595215/162894223-cdd8c76b-7a69-4bbe-93b3-20f525b69602.jpg)

### Steps to Reproduce

```markdown
using AOE as the storage is almost the same.
1,boost 3 nodes cluster with aoe storage.
2,load data into the cluster. To make sure the data can be distributed in three aoe storages. Please use the load script and the data following. (Change the path of the data file before loading).
3,execute the sql.
`SELECT sum(LO_REVENUE),year(LO_ORDERDATE) AS year,P_BRAND,count(*) FROM lineorder_flat WHERE P_CATEGORY = 'MFGR#12' AND S_REGION = 'AMERICA' GROUP BY year(LO_ORDERDATE),P_BRAND ORDER BY year,P_BRAND;`
```

using TPE as the storage is almost the same.
1, change `enableTpe = true` in three config files.
2, remove the data directory `store`.
3, others are same as the those for AOE

### Additional information

[conf0.txt](https://github.com/matrixorigin/matrixone/files/8470095/conf0.txt)
[conf1.txt](https://github.com/matrixorigin/matrixone/files/8470102/conf1.txt)
[conf2.txt](https://github.com/matrixorigin/matrixone/files/8470111/conf2.txt)
[load-tpe1w-3aoe.sql.zip](https://github.com/matrixorigin/matrixone/files/8470123/load-tpe1w-3aoe.sql.zip)
[lineorder_flat_1w.csv](https://github.com/matrixorigin/matrixone/files/8470126/lineorder_flat_1w.csv)

**Comment by m-schen** [comment]
may since the lack of serialization functions for max.DateRing. the type of case's group by column is Date.

**Comment by daviszhen** [comment]
It disappeared at commit `18d59acb9ffd8e2737bf987fe6b0e3b4ef4e5090`.
