### ISSUE TITLE
[Docs]: Example code in builtin function guidance is confusing for external contributors

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#2224]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

During fixing #2138, I found that almost all of external contributors have misunderstood this example.

```go
package abs

var (
	absFloat32 func([]float32, []float32) []float32
	absFloat64 func([]float64, []float64) []float64
)

func init() {
	absFloat32 = absFloat32Pure
	absFloat64 = absFloat64Pure
}

func AbsFloat32(xs, rs []float32) []float32 {
	return absFloat32(xs, rs)
}

func absFloat32Pure(xs, rs []float32) []float32 {
}

func AbsFloat64(xs, rs []float64) []float64 {
	return absFloat64(xs, rs)
}

func absFloat64Pure(xs, rs []float64) []float64 {
}
```

An example of misuse: https://github.com/matrixorigin/matrixone/blob/8492f5d2358db70ece0588a545a2d3dfbaaf8962/pkg/vectorize/startsWith/startsWith.go#L31-L34

The capitalized `AbsFloat32`/`AbsFloat64` are exported functions, and `absFloat32Pure`/`absFloat64Pure` are actual implementations. In fact, we never need another dummy `absFloat32`/`absFloat64` to bridge them.

**Comment by broccoliSpicy** [comment]
fixed by @aunjgr
