### ISSUE TITLE
[Bug]: Error 1105: unknown error:unsupported command. 0x16 

### ISSUE THREAD

**Issue by kokizzu** [matrixorigin/matrixone#2227]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): matrixone:latest (0.3.0 MatrixOne)
- Hardware parameters: Ryzen 5950X, 128GB, 512GB NVMe
- OS type: PopOS! 21.10 64-bit
```

### Actual Behavior

```
2022-04-17 02:29:12.565 PanicIf ▶ dia/kyz/team512/go/src/hugedbbench/2021/matrixone/main_test.go:67:  command-line-arguments.TestDb.func2.1: failed insert to bar1
2022-04-17 02:29:12.565 PanicIf ▶ &mysql.MySQLError{Number:0x451, Message:"unknown error:unsupported command. 0x16 \n"}
    StackTrace: 
panic: Error 1105: unknown error:unsupported command. 0x16 

<br/>&mysql.MySQLError{Number:0x451, Message:"unknown error:unsupported command. 0x16 \n"}
<br/>    StackTrace: 
<br/>dia/kyz/team512/go/src/hugedbbench/2021/matrixone/main_test.go:67:  command-line-arguments.TestDb.func2.1: 
<br/>failed insert to bar1
```

### Expected Behavior

insert done successfully

### Steps to Reproduce

```markdown
git clone git@github.com:kokizzu/hugedbbench.git
cd hugedbbench/2021/matrixone
go mod tidy

docker-compose up -f docker-compose-single.yaml -d 

go test main_test.go
```

### Additional information

works with other database (mysql, last year's tidb)

**Comment by jianwan0214** [comment]
> 



> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Environment
> ```gfm
> - Version or commit-id (e.g. v0.1.0 or 8b23a93): matrixone:latest (0.3.0 MatrixOne)
> - Hardware parameters: Ryzen 5950X, 128GB, 512GB NVMe
> - OS type: PopOS! 21.10 64-bit
> ```
> 
> ### Actual Behavior
> ```
> 2022-04-17 02:29:12.565 PanicIf ▶ dia/kyz/team512/go/src/hugedbbench/2021/matrixone/main_test.go:67:  command-line-arguments.TestDb.func2.1: failed insert to bar1
> 2022-04-17 02:29:12.565 PanicIf ▶ &mysql.MySQLError{Number:0x451, Message:"unknown error:unsupported command. 0x16 \n"}
>     StackTrace: 
> panic: Error 1105: unknown error:unsupported command. 0x16 
> 
> <br/>&mysql.MySQLError{Number:0x451, Message:"unknown error:unsupported command. 0x16 \n"}
> <br/>    StackTrace: 
> <br/>dia/kyz/team512/go/src/hugedbbench/2021/matrixone/main_test.go:67:  command-line-arguments.TestDb.func2.1: 
> <br/>failed insert to bar1
> ```
> 
> ### Expected Behavior
> insert done successfully
> 
> ### Steps to Reproduce
> ```gfm
> git clone git@github.com:kokizzu/hugedbbench.git
> cd hugedbbench/2021/matrixone
> go mod tidy
> 
> docker-compose up -f docker-compose-single.yaml -d 
> 
> go test main_test.go
> ```
> 
> ### Additional information
> works with other database (mysql, last year's tidb)



> ### Is there an existing issue for the same bug?
> * [x]  I have checked the existing issues.
> 
> ### Environment
> ```gfm
> - Version or commit-id (e.g. v0.1.0 or 8b23a93): matrixone:latest (0.3.0 MatrixOne)
> - Hardware parameters: Ryzen 5950X, 128GB, 512GB NVMe
> - OS type: PopOS! 21.10 64-bit
> ```
> 
> ### Actual Behavior
> ```
> 2022-04-17 02:29:12.565 PanicIf ▶ dia/kyz/team512/go/src/hugedbbench/2021/matrixone/main_test.go:67:  command-line-arguments.TestDb.func2.1: failed insert to bar1
> 2022-04-17 02:29:12.565 PanicIf ▶ &mysql.MySQLError{Number:0x451, Message:"unknown error:unsupported command. 0x16 \n"}
>     StackTrace: 
> panic: Error 1105: unknown error:unsupported command. 0x16 
> 
> <br/>&mysql.MySQLError{Number:0x451, Message:"unknown error:unsupported command. 0x16 \n"}
> <br/>    StackTrace: 
> <br/>dia/kyz/team512/go/src/hugedbbench/2021/matrixone/main_test.go:67:  command-line-arguments.TestDb.func2.1: 
> <br/>failed insert to bar1
> ```
> 
> ### Expected Behavior
> insert done successfully
> 
> ### Steps to Reproduce
> ```gfm
> git clone git@github.com:kokizzu/hugedbbench.git
> cd hugedbbench/2021/matrixone
> go mod tidy
> 
> docker-compose up -f docker-compose-single.yaml -d 
> 
> go test main_test.go
> ```
> 
> ### Additional information
> works with other database (mysql, last year's tidb)

the mo db is not support the preprocessing statement now, so it does not work
