### ISSUE TITLE
[Refactoring]: Optimize some storage UTs 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2243]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
Currently, some storage failed occasionally because of unknown reasons. Better to optimize these UTs.
```

### Describe the solution you'd like

Make those UTs stable and clear.

**Comment by JinHai-CN** [comment]
Still valid

**Comment by fengttt** [comment]
Not actionable.   Unless you list the affected UT.
