### ISSUE TITLE
[Question]: How to build for arm64 when using cgo

### ISSUE THREAD

**Issue by NTH19** [matrixorigin/matrixone#2248]
### Describe your problem

Is there an existing issue for the same bug?

-  I have checked the existing issues.

I use arm neon to write some code for vectorize/add.But I use commad "CGOENABLE=1 CC=arm-linux-gnueabihf-gcc GOARCH=arm64 go build " to build,it doesn't work.
So I can't test my code.I want to ask how to build it?

**Comment by broccoliSpicy** [comment]
do you have a arm64 machine? if you do, you can wrap up the arm64 specific code in a add_arm64.go file, then run "go build" or run "make build" under the matrixone repo directory, no arguments needed

**Comment by aunjgr** [comment]
Besides, the target triplet for arm64 should be like `aarch64-linux-gnu`. `arm-linux-gnueabihf` is for 32-bit arm cpu. You are using a wrong cross compiler.

**Comment by NTH19** [comment]
> Besides, the target triplet for arm64 should be like `aarch64-linux-gnu`. `arm-linux-gnueabihf` is for 32-bit arm cpu. You are using a wrong cross compiler.

Thanks @aunjgr @broccoliSpicy
