### ISSUE TITLE
[Bug]: Unknown error need to be standardized.   In general, error handling framework redesign.

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2270]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t2 (
 siteid varchar(25) NOT NULL default '',
 rate_code varchar(10) NOT NULL default '',
base_rate float NOT NULL default 0
 );
INSERT INTO t2 VALUES ('rivercats','cust',20);
ERROR 1105 (HY000): unknown error:Internal error: panic interface conversion: interface {} is float32, not float64: goroutine 954 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x2589460?, 0xc00084b5c0})
	/data/zhangxiao/matrixone/pkg/common/moerr/error.go:77 +0x53
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Exec).Compile.func1()
	/data/zhangxiao/matrixone/pkg/sql/compile/exec.go:46 +0x31
panic({0x2589460, 0xc00084

**Comment by m-schen** [comment]
I Wii check what cause the panic and fix it soon

**Comment by domingozhang** [comment]
@JinHai-CN just like this issue. The unknown error need to be standardized in future release

**Comment by fengttt** [comment]
The insert bug itself is fixed.   However, per standardize error reporting mechanism is not done yet.

**Comment by JinHai-CN** [comment]
This issue is related to #3435

**Comment by sukki37** [comment]
@fengttt any updates?

**Comment by fengttt** [comment]
error handling framework is done.   with help from xzx and now owned by xzx.
