### ISSUE TITLE
[Bug]: epochgc corner case

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#2298]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):cc8b7c3f697266b9587216d0090aae8dceb2b0fe
- Hardware parameters:mac or linux
- OS type:
- Others:
```

### Actual Behavior

In an extreme case, the system may delete the table that is reading by a query.

### Expected Behavior

No data can be deleted when they are read.

**Comment by JinHai-CN** [comment]
In 0.6.0, EPOCH GC may not valid. close it firstly.
