### ISSUE TITLE
[Bug]: The decimal type does not support the insertion of  transferabled character

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id: 0.4.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table numtable(id int, dt decimal(10,5));
mysql> insert into numtable values(1,'123.45');
ERROR 1105 (HY000): unknown error:[42P18]unsupport value: "123.45"
mysql> 

### Expected Behavior

create table numtable(id int, dt decimal(10,5));
mysql> insert into numtable values(1,'123.45');
Query OK, 1 row affected (0.00 sec)

mysql> select * from numtable;
+------+-------------+
| id   | dt          |
+------+-------------+
|    1 |   123.45000 |
+------+-------------+
3 rows in set (0.00 sec)

mysql>

**Comment by broccoliSpicy** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
mysql> create table numtable(id int, dt decimal(10,5));
Query OK, 0 rows affected (0.01 sec)

mysql> -- test for insertion of type[transferabled char]
mysql> insert into numtable values(1,'123.45');
Query OK, 1 row affected (0.00 sec)

mysql> insert into numtable values(2,'99999.999985');
Query OK, 1 row affected (0.00 sec)

mysql> -- test for insertion of null
mysql> insert into numtable values(1,null);
Query OK, 1 row affected (0.01 sec)

mysql> -- test for insertion of illegal value
mysql> insert into numtable values(1,'abc');
ERROR 1105 (HY000): unknown error:invalid decimal string
mysql> select * from numtable;
+------+-------------+
| id   | dt          |
+------+-------------+
|    1 |   123.45000 |
|    2 | 99999.99998 |
|    1 |        NULL |
+------+-------------+
3 rows in set (0.01 sec)
