### ISSUE TITLE
[Bug]: The result of distinct for decimal type is not correct

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2301]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id : 0.4.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from dt_dis;
+------+-------------+
| id   | dt          |
+------+-------------+
|    1 |   100.00000 |
|    1 |   100.00000 |
|    1 | 99999.99999 |
|    1 | 99999.99999 |
|    1 | 99998.99999 |
|    1 | 99999.00000 |
|    1 | 99999.00000 |
|    2 |        NULL |
|    3 |        NULL |
+------+-------------+
9 rows in set (0.02 sec)

mysql> select distinct dt from dt_dis;
+-----------+
| dt        |
+-----------+
| 100.00000 |
+-----------+
1 row in set (0.01 sec)

**Comment by fengttt** [comment]
Done and verified.
