### ISSUE TITLE
[Enhancement]: The decimal type does not support round.

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2302]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
As a normal numberic type, the decimal should support numberic function operations like int，float..
```

**Comment by broccoliSpicy** [comment]
this is not part of the v0.4 plan

**Comment by broccoliSpicy** [comment]
we better solve this issue after v0.5, after generics are ready,

**Comment by JinHai-CN** [comment]
Also should include AVG function.

**Comment by broccoliSpicy** [comment]
round is not part of aggregate function

**Comment by fengttt** [comment]
min/max/avg are done.   Round is 0.6.

**Comment by dengn** [comment]
ok for 0.6

**Comment by aressu1985** [comment]
fxied
