### ISSUE TITLE
[Enhancement]: toDecimal func not implemented

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2304]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
toDecimal func should be planed to be implemented
```

**Comment by broccoliSpicy** [comment]
I can implement this function, no problem, but this function doesn't exist in mysql/postgres etc..

**Comment by dengn** [comment]
@domingozhang Please check if toDecimal function is supported by ANSI SQL. if not, we would go with the MySQL syntax with "CAST" to implement type conversion.

**Comment by domingozhang** [comment]
todecimal is only supported by several database system. If CAST can support, this function can be skipped.

**Comment by daviszhen** [comment]
replaced by CAST

**Comment by fengttt** [comment]
Use cast.
