### ISSUE TITLE
[Bug]: Instance crashed when input an incorrect date value

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2309]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

I input a date value '1997=12=31' instead of '1997-12-31'.

mysql> SELECT C_NATION, S_NATION, year(LO_ORDERDATE) AS year, sum(LO_REVENUE) AS revenue FROM lineorder_flat WHERE C_REGION = 'ASIA' AND S_REGION = 'ASIA' AND LO_ORDERDATE >= '1992-01-01' AND LO_ORDERDATE <= '1997=12=31' GROUP BY C_NATION, S_NATION, year(LO_ORDERDATE) ORDER BY year asc, revenue desc;
ERROR 2013 (HY000): Lost connection to MySQL server during query

### Additional information

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x23add18]

goroutine 1117 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.getVectorValue(0xc010b73b00?)
	/data/zhangxiao/matrixone/pkg/vm/engine/aoe/engine/relation.go:392 +0x18
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.cast(0xc010b73b00, 0x32)
	/data/zhangxiao/matrixone/pkg/vm/engine/aoe/engine/relation.go:388 +0x1b1
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.newFilterContext(0x4, 0xc00699bec0, 0xc02551d808)
	/data/zhangxiao/matrixone/pkg/vm/engine/aoe/engine/relation.go:359 +0x8a
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.getFilterContextFromExtend(0xc02551d808, {0x2c35290?, 0xc00699bec0})
	/data/zhangxiao/matrixone/pkg/vm/engine/aoe/engine/relation.go:350 +0x7a
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.getFilterContext({0x2c35290?, 0xc00699bef0?})
	/data/zhangxiao/matrixone/pkg/vm/engine/aoe/engine/relation.go:330 +0x10f
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.(*relation).NewReader(0xc024b73680, 0x40, {0x2c35290?, 0xc00699bef0?}, {0x4f?, 0x76?, 0x19cf880?})
	/data/zhangxiao/matrixone/pkg/vm/engine/aoe/engine/relation.go:274 +0x54
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RunAQ(0xc025c6ddd0, {0x2c2e200?, 0xc00ab17d30?})
	/data/zhangxiao/matrixone/pkg/sql/compile/scope.go:821 +0x1b4
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc025c6ddd0?, {0x2c2e200?, 0xc00ab17d30?})
	/data/zhangxiao/matrixone/pkg/sql/compile/scope.go:624 +0xe8
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc025c6ddd0, {0x2c2e200, 0xc00ab17d30})
	/data/zhangxiao/matrixone/pkg/sql/compile/scope.go:520 +0x70b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0x0?)
	/data/zhangxiao/matrixone/pkg/sql/compile/scope.go:496 +0x2a
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/data/zhangxiao/matrixone/pkg/sql/compile/scope.go:495 +0x4ad

**Comment by m-schen** [comment]
Aoe should return the error if error happens but not ignore at https://github.com/matrixorigin/matrixone/blob/ab3a78f31bcaa342a523095959477702dd876a1a/pkg/vm/engine/aoe/engine/relation.go#L377

**Comment by LeftHandCold** [comment]
How to deal with this kind of input error aoe? Ignore this filter?

**Comment by m-schen** [comment]
I think a wrong filter condition shouldn't push down may suitable, this error should be return before reading the data?
