### ISSUE TITLE
[Bug]: The result of group by from subquery not correct 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2313]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id : 0.4.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from t1;
+------+------+------+------+-----------+--------------+------+--------------+----------------+------------+---------------------+
| id   | ti   | si   | bi   | fl        | dl           | de   | ch           | vch            | dd         | dt                  |
+------+------+------+------+-----------+--------------+------+--------------+----------------+------------+---------------------+
|    1 |    1 |    4 |    3 | 1113.3199 |  111332.0000 | 1113 | hello        | subquery       | 2022-04-28 | 2022-04-28 22:40:11 |
|    2 |    2 |    5 |    2 | 2252.0500 |  225205.0000 | 2252 | bye          | sub query      | 2022-04-28 | 2022-04-28 22:40:11 |
|    3 |    6 |    6 |    3 | 3663.2100 |  366321.0000 | 3663 | hi           | subquery       | 2022-04-28 | 2022-04-28 22:40:11 |
|    4 |    7 |    1 |    5 | 4715.2202 |  471522.0000 | 4715 | good morning | my subquery    | 2022-04-28 | 2022-04-28 22:40:11 |
|    5 |    1 |    2 |    6 |   51.2600 |    5126.0000 |   51 | byebye       |  is subquery?  | 2022-04-28 | 2022-04-28 22:40:11 |
|    6 |    3 |    2 |    1 |  632.1000 |    6321.0000 |  632 | good night   | maybe subquery | 2022-04-28 | 2022-04-28 22:40:11 |
|    7 |    4 |    4 |    3 | 7443.1099 |  744311.0000 | 7443 | yes          | subquery       | 2022-04-28 | 2022-04-28 22:40:11 |
|    8 |    7 |    5 |    8 | 8758.0000 |  875800.0000 | 8758 | nice to meet | just subquery  | 2022-04-28 | 2022-04-28 22:40:11 |
|    9 |    8 |    4 |    9 | 9849.3115 | 9849312.0000 | 9849 | see you      | subquery       | 2022-04-28 | 2022-04-28 22:40:11 |
+------+------+------+------+-----------+--------------+------+--------------+----------------+------------+---------------------+
9 rows in set (0.08 sec)

mysql> select id,min(ti) from (select * from t1) sub group by id;
Empty set (0.02 sec)

### Expected Behavior

mysql> select id,min(ti) from (select * from t1) sub group by id;
+------+---------+
| id   | min(ti) |
+------+---------+
|    1 |       1 |
|    2 |       2 |
|    3 |       6 |
|    4 |       7 |
|    5 |       1 |
|    6 |       3 |
|    7 |       4 |
|    8 |       7 |
|    9 |       8 |
+------+---------+
9 rows in set (0.00 sec)

### Steps to Reproduce

```markdown
drop table if exists t1;
create table t1 (id int,ti tinyint unsigned,si smallint,bi bigint unsigned,fl float,dl double,de decimal,ch char(20),vch varchar(20),dd date,dt datetime);
insert into t1 values(1,1,4,3,1113.32,111332,1113.32,'hello','subquery','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(2,2,5,2,2252.05,225205,2252.05,'bye','sub query','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(3,6,6,3,3663.21,366321,3663.21,'hi','subquery','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(4,7,1,5,4715.22,471522,4715.22,'good morning','my subquery','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(5,1,2,6,51.26,5126,51.26,'byebye',' is subquery?','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(6,3,2,1,632.1,6321,632.11,'good night','maybe subquery','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(7,4,4,3,7443.11,744311,7443.11,'yes','subquery','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(8,7,5,8,8758.00,875800,8758.11,'nice to meet','just subquery','2022-04-28','2022-04-28 22:40:11');
insert into t1 values(9,8,4,9,9849.312,9849312,9849.312,'see you','subquery','2022-04-28','2022-04-28 22:40:11');


select id,min(ti) from (select * from t1) sub group by id;
```

**Comment by nnsgmsone** [comment]
fixed by 2344

**Comment by aressu1985** [comment]
fixed
