### ISSUE TITLE
[Bug]: The result of func space() not correct when there are negative numbers in column

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2314]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.4.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from t1;
+------+
| d    |
+------+
|    0 |
|   -1 |
|    2 |
|   10 |
+------+
4 rows in set (0.01 sec)

mysql> select space(d) from t1;
+----------+
| space(d) |
+----------+
|          |
+----------+
1 row in set (0.01 sec)

**Comment by broccoliSpicy** [comment]
can we assign this to the original author of this function?

**Comment by broccoliSpicy** [comment]
fixed
