### ISSUE TITLE
[Enhancement]: The math function does not support the decimal type

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2316]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.4.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select sin(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql> select abs(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql> select sinh(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql> select atan(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql> select acos(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql> select cot(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql> select tan(dt) from numtable;
ERROR 1105 (HY000): unknown error:'' not yet implemented for DECIMAL64
mysql>

**Comment by broccoliSpicy** [comment]
this is not part of our v0.4 plan,

**Comment by broccoliSpicy** [comment]
I think I will implement this in v0.5

**Comment by dengn** [comment]
@broccoliSpicy what's the current status here? can it still be implemented in 0.5?

**Comment by broccoliSpicy** [comment]
there are two solutions to these: 
    1. implicit cast decimal to float64
    2. drop decimal's support for all math functions

notice: it is impossible/stupid for us to implement all math functions using our decimal data type representation,

**Comment by aressu1985** [comment]
fixed
