### ISSUE TITLE
[Bug]: select into outfile unsuccessful

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2322]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Tried to export multi joined table into a single data file:

select
    lo_orderkey as lo_orderkey,
    lo_linenumber as lo_linenumber,
    lo_custkey as lo_custkey,
    lo_partkey as lo_partkey,
    lo_suppkey as lo_suppkey,
    lo_orderdate as lo_orderdate,
    lo_orderpriority as lo_orderpriority,
    lo_shippriority as lo_shippriority,
    lo_quantity as lo_quantity,
    lo_extendedprice as lo_extendedprice,
    lo_ordtotalprice as lo_ordtotalprice,
    lo_discount as lo_discount,
    lo_revenue as lo_revenue,
    lo_supplycost as lo_supplycost,
    lo_tax as lo_tax,
    lo_commitdate as lo_commitdate,
    lo_shipmode as lo_shipmode,
    c_name as c_name,
    c_address as c_address,
    c_city as c_city,
    c_nation as c_nation,
    c_region as c_region,
    c_phone as c_phone,
    c_mktsegment as c_mktsegment,
    s_name as s_name,
    s_address as s_address,
    s_city as s_city,
    s_nation as s_nation,
    s_region as s_region,
    s_phone as s_phone,
    p_name as p_name,
    p_mfgr as p_mfgr,
    p_category as p_category,
    p_brand as p_brand,
    p_color as p_color,
    p_type as p_type,
    p_size as p_size,
    p_container as p_container
from lineorder as l
inner join customer as c on c.c_custkey = l.lo_custkey
inner join supplier as s on s.s_suppkey = l.lo_suppkey
inner join part as p on p.p_partkey = l.lo_partkey
order by lo_orderdate
into outfile '/data/zhangxiao/lineorder_flat_mo.tbl' fields terminated by ',' lines terminated by '\n' header 'false';
Empty set (10.17 sec)

The exported file is only 97MB with 320,000 rows data.

-rw-r--r--  1 root root 97892532 Apr 29 15:46 lineorder_flat_mo.tbl

**Comment by domingozhang** [comment]
without order by clause, the exported action is normal.

**Comment by nnsgmsone** [comment]
fixed by 2368
