### ISSUE TITLE
[Refactoring]: Aggregate function COUNT()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2324]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
As MatrixOne is refactoring its execution plan, the aggregation function needs to adapt to this refactoring.
```

### Describe the solution you'd like

A new function registration process will be applied.

**Comment by dengn** [comment]
Please refer to the corresponding test cases: https://github.com/dengn/mo-tester/blob/main/cases/function/func_aggr_count.test

**Comment by nnsgmsone** [comment]
count(distinct) not supported
