### ISSUE TITLE
[Refactoring]: Single parameter builtin functions refactoring

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2329]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
As MatrixOne is refactoring its execution plan, the builtin function needs to adapt to this refactoring.

```

### Describe the solution you'd like

A new function registration process will be applied.
The unary function list:
abs, acos, atan,cos, cot, date, dayofyear, exp, length, ln, log, ltrim, month, reverse, rtrim, sin, sinh, space, tan, weekday, year

**Comment by m-schen** [comment]
#2349 #2350 work is similar to this issue. I will do all the work at the same time.

**Comment by m-schen** [comment]
I plan to do this work on 2 steps.

1. refactoring the register logic of all the built-in functions （and operators)
2. fix the code of functions and operators.

**Comment by m-schen** [comment]
adding  implicit cast rule for function's argument now.

**Comment by dengn** [comment]
Please refer to the corresponding test cases: https://github.com/dengn/mo-tester/tree/main/cases/function

**Comment by fengttt** [comment]
Covered by bvt.
