### ISSUE TITLE
[Feature Request]: Builtin function DATE_ADD()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2331]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
-- TPC-H Query 15 - Top Supplier Query
WITH REVENUE0 AS (
	SELECT 
		L_SUPPKEY AS SUPPLIER_NO,
		SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS TOTAL_REVENUE
	FROM
		LINEITEM
	WHERE
		L_SHIPDATE >= DATE '1996-01-01'
			AND L_SHIPDATE < DATE_ADD(DATE '1996-01-01',
			INTERVAL 3 MONTH)
	GROUP BY L_SUPPKEY
) 
SELECT  /*+ set_var(use_secondary_engine=forced) */  
    S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM
    SUPPLIER,
    REVENUE0
WHERE
    S_SUPPKEY = SUPPLIER_NO
        AND TOTAL_REVENUE = (SELECT 
            MAX(TOTAL_REVENUE)
        FROM
            REVENUE0)
ORDER BY S_SUPPKEY;
```

### Describe the feature you'd like

DATE_ADD()

Add time values (intervals) to a date value

Syntax:
Follow the syntax and behavior of mysql 8.0 

[DATE_ADD(date,INTERVAL expr unit)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add)

DATE_ADD() perform date arithmetic. The date argument specifies the starting date or datetime value. expr is an expression specifying the interval value to be added or subtracted from the starting date. expr is evaluated as a string; it may start with a - for negative intervals. unit is a keyword indicating the units in which the expression should be interpreted.

For more information about temporal interval syntax, including a full list of unit specifiers, the expected form of the expr argument for each unit value, and rules for operand interpretation in temporal arithmetic, see [Temporal Intervals](https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals).

```sql

mysql> SELECT DATE_ADD('2018-05-01',INTERVAL 1 DAY);
        -> '2018-05-02'
mysql> SELECT DATE_ADD('2020-12-31 23:59:59',
    ->                 INTERVAL 1 SECOND);
        -> '2021-01-01 00:00:00'
mysql> SELECT DATE_ADD('2018-12-31 23:59:59',
    ->                 INTERVAL 1 DAY);
        -> '2019-01-01 23:59:59'
mysql> SELECT DATE_ADD('2100-12-31 23:59:59',
    ->                 INTERVAL '1:1' MINUTE_SECOND);
        -> '2101-01-01 00:01:00'
mysql> SELECT DATE_ADD('1900-01-01 00:00:00',
    ->                 INTERVAL '-1 10' DAY_HOUR);
        -> '1899-12-30 14:00:00'
mysql> SELECT DATE_ADD('1992-12-31 23:59:59.000002',
    ->            INTERVAL '1.999999' SECOND_MICROSECOND);
        -> '1993-01-01 00:00:01.000001'
```

**Comment by dengn** [comment]
same as https://github.com/matrixorigin/matrixone/issues/2328, Microseconds and Time intervals need to be supported.

**Comment by dengn** [comment]
Test case reference: https://github.com/mysql/mysql-server/blob/6846e6b2f72931991cc9fd589dc9946ea2ab58c9/mysql-test/t/func_date_add.test
https://github.com/mysql/mysql-server/blob/8d8c986e5716e38cb776b627a8eee9e92241b4ce/mysql-test/t/func_time.test

**Comment by dengn** [comment]
Please refer to the corresponding test cases: https://github.com/dengn/mo-tester/blob/main/cases/function/func_datetime_date_add.test

**Comment by bbbearxyz** [comment]
I complete it
