### ISSUE TITLE
[Bug]: Inner join result is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2333]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select
    lo_orderkey as lo_orderkey,
    lo_linenumber as lo_linenumber,
    lo_custkey as lo_custkey,
    lo_partkey as lo_partkey,
    lo_suppkey as lo_suppkey,
    lo_orderdate as lo_orderdate,
    lo_orderpriority as lo_orderpriority,
    lo_shippriority as lo_shippriority,
    lo_quantity as lo_quantity,
    lo_extendedprice as lo_extendedprice,
    lo_ordtotalprice as lo_ordtotalprice,
    lo_discount as lo_discount,
    lo_revenue as lo_revenue,
    lo_supplycost as lo_supplycost,
    lo_tax as lo_tax,
    lo_commitdate as lo_commitdate,
    lo_shipmode as lo_shipmode,
    c_name as c_name,
    c_address as c_address,
    c_city as c_city,
    c_nation as c_nation,
    c_region as c_region,
    c_phone as c_phone,
    c_mktsegment as c_mktsegment,
    s_name as s_name,
    s_address as s_address,
    s_city as s_city,
    s_nation as s_nation,
    s_region as s_region,
    s_phone as s_phone,
    p_name as p_name,
    p_mfgr as p_mfgr,
    p_category as p_category,
    p_brand as p_brand,
    p_color as p_color,
    p_type as p_type,
    p_size as p_size,
    p_container as p_container
from lineorder as l
inner join customer as c on c_custkey = lo_custkey
inner join supplier as s on s_suppkey = lo_suppkey
inner join part as p on p_partkey = lo_partkey
order by lo_orderdate limit 1000000;

In the result, there is a value of date type '0001-01-01'. However there is not this date.

select lo_orderdate from lineorder where lo_orderdate='0001-01-01';
Empty set (0.13 sec)

**Comment by domingozhang** [comment]
without order by, the result is correct

**Comment by nnsgmsone** [comment]
fixed by 2347
