### ISSUE TITLE
[Bug]: SSB query result is different with same csv file

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2334]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. load data from the same lineorder-flat.tbl
2. Run ssb 1.1 get the result.
3.Drop table and load data but every time the result is different

**Comment by fengttt** [comment]
Can you post two example different results?    Was it really wrong results, or, difference due to rounding?

**Comment by LeftHandCold** [comment]
The result is really wrong, currently the parsing error is caused by the double type.

**Comment by sukki37** [comment]
I think something is wrong when double-column filtering with `>`.
<img width="920" alt="image" src="https://user-images.githubusercontent.com/77312370/166116112-2e111280-3efd-4760-b695-2c6f1021102f.png">

**Comment by LeftHandCold** [comment]
This case is caused by "Split". After "Split", there is an error in the filtering of ">" double type, and there are no errors in other filtering. It also works fine after "Disable Split".

**Comment by LeftHandCold** [comment]
https://github.com/matrixorigin/matrixone/blob/main/pkg/vm/engine/aoe/storage/layout/index/blkzonemap.go#L186

**Comment by LeftHandCold** [comment]
The root cause is at https://github.com/matrixorigin/matrixone/blob/main/pkg/vm/engine/aoe/storage/layout/index/blkzonemap.go#L186
@zzl200012 Please check if there are other exceptions。
