### ISSUE TITLE
[Enhancement]: Insert not support function in the values

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2338]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
It is very common that the values in the insert cmd contain the func expression,so,
this should be implemented
```

**Comment by ouyuanning** [comment]
same as #3202 #3355

both 3202 and 3355 are  in milestone 0.6.0.   so change this issue to 0.6.0

**Comment by aressu1985** [comment]
fixed
