### ISSUE TITLE
[Refactoring]: Multi-parameter builtin functions refactoring 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2350]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
As MatrixOne is refactoring its execution plan, the builtin function needs to adapt to this refactoring.
```

### Describe the solution you'd like

A new function registration process will be applied.
The multi function list:
ceil, floor, lpad, pi, round, rpad, utc_timestamp

**Comment by dengn** [comment]
Please refer to the corresponding test cases: https://github.com/dengn/mo-tester/tree/main/cases/function

**Comment by fengttt** [comment]
Covered by BVT
