### ISSUE TITLE
[Feature Request]: Builtin function Date_format()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2351]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
Several showcase SQL requires the support of this function:


select DATE_FORMAT(b.measurement_time,'%Y-%m-%d') 

select DATE_FORMAT(FROM_UNIXTIME(tm.create_time), %Y%m%d)
```

### Describe the feature you'd like

Follow the syntax of MySQL 8.0.

[DATE_FORMAT(date,format)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-format)
Formats the date value according to the format string.

The specifiers shown in the following table may be used in the format string. The % character is required before format specifier characters. 

Specifier | Description
-- | --
%a | Abbreviated weekday name (Sun..Sat)
%b | Abbreviated month name (Jan..Dec)
%c | Month, numeric (0..12)
%D | Day of the month with English suffix (0th, 1st, 2nd, 3rd, …)
%d | Day of the month, numeric (00..31)
%e | Day of the month, numeric (0..31)
%f | Microseconds (000000..999999)
%H | Hour (00..23)
%h | Hour (01..12)
%I | Hour (01..12)
%i | Minutes, numeric (00..59)
%j | Day of year (001..366)
%k | Hour (0..23)
%l | Hour (1..12)
%M | Month name (January..December)
%m | Month, numeric (00..12)
%p | AM or PM
%r | Time, 12-hour (hh:mm:ss followed by AM or PM)
%S | Seconds (00..59)
%s | Seconds (00..59)
%T | Time, 24-hour (hh:mm:ss)
%U | Week (00..53), where Sunday is the first day of the week; WEEK() mode 0
%u | Week (00..53), where Monday is the first day of the week; WEEK() mode 1
%V | Week (01..53), where Sunday is the first day of the week; WEEK() mode 2; used with %X
%v | Week (01..53), where Monday is the first day of the week; WEEK() mode 3; used with %x
%W | Weekday name (Sunday..Saturday)
%w | Day of the week (0=Sunday..6=Saturday)
%X | Year for the week where Sunday is the first day of the week, numeric, four digits; used with %V
%x | Year for the week, where Monday is the first day of the week, numeric, four digits; used with %v
%Y | Year, numeric, four digits
%y | Year, numeric (two digits)
%% | A literal % character
%x | x, for any “x” not listed above

[DATE_FORMAT()](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-format) returns a string with a character set and collation given by [character_set_connection](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_connection) and [collation_connection](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_collation_connection) so that it can return month and weekday names containing non-ASCII characters.

```sql
mysql> SELECT DATE_FORMAT('2009-10-04 22:23:00', '%W %M %Y');
        -> 'Sunday October 2009'
mysql> SELECT DATE_FORMAT('2007-10-04 22:23:00', '%H:%i:%s');
        -> '22:23:00'
mysql> SELECT DATE_FORMAT('1900-10-04 22:23:00',
    ->                 '%D %y %a %d %m %b %j');
        -> '4th 00 Thu 04 10 Oct 277'
mysql> SELECT DATE_FORMAT('1997-10-04 22:23:00',
    ->                 '%H %k %I %r %T %S %w');
        -> '22 22 10 10:23:00 PM 22:23:00 00 6'
mysql> SELECT DATE_FORMAT('1999-01-01', '%X %V');
        -> '1998 52'
mysql> SELECT DATE_FORMAT('2006-06-00', '%d');
        -> '00'
```

### Documentation, Adoption, Use Case, Migration Strategy

Please refer to the [tutorial](https://docs.matrixorigin.io/0.4.0/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions/) about how to develop a builtin function.

**Comment by broccoliSpicy** [comment]
this function seems a lot of work and I am not sure I can finish it before v0.5 release

**Comment by domingozhang** [comment]
First batch will support these format.
DATE_FORMAT(b.measurement_time,'%Y-%m-%d')
DATE_FORMAT(b.measurement_time,'%Y-%m')
DATE_FORMAT(b.measurement_time,'%Y-%m-%d %H:%i:%s')

**Comment by daviszhen** [comment]
> First batch will support these format. DATE_FORMAT(b.measurement_time,'%Y-%m-%d') DATE_FORMAT(b.measurement_time,'%Y-%m') DATE_FORMAT(b.measurement_time,'%Y-%m-%d %H:%i:%s')
> 
> As a p0 requirement, this function still needs to support more format in 0.6.0

We will implement these first then the rest.

**Comment by qingxinhome** [comment]
This feature request has been fixed, unit test and bvt test have been completed, and now request acceptance test, please know！ @fengttt @JinHai-CN @florashi181 @dengn @domingozhang @aressu1985 @daviszhen
