### ISSUE TITLE
[Feature Request]: Subqueries with EXISTS/NOT EXISTS 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2354]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
TPCH4 SQL requires Subquery with EXISTS/NOT EXISTS

-- TPC-H Query 4 - Order Priority Checking
SELECT /*+ set_var(use_secondary_engine=forced) */  
    O_ORDERPRIORITY, COUNT(*) AS ORDER_COUNT
FROM
    ORDERS
WHERE
    O_ORDERDATE >= DATE '1994-03-01'
        AND O_ORDERDATE < DATE '1994-03-01' + INTERVAL '3' MONTH
        AND EXISTS( SELECT 
            *
        FROM
            LINEITEM
        WHERE
            L_ORDERKEY = O_ORDERKEY
                AND L_COMMITDATE < L_RECEIPTDATE)
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY;
```

### Describe the feature you'd like

Follow MySQL8.0 behavior and syntax: https://dev.mysql.com/doc/refman/8.0/en/exists-and-not-exists-subqueries.html

If a subquery returns any rows at all, EXISTS subquery is TRUE, and NOT EXISTS subquery is FALSE. For example:

SELECT column1 FROM t1 WHERE EXISTS (SELECT * FROM t2);

**Comment by JinHai-CN** [comment]
Same as #2376

**Comment by florashi181** [comment]
Same as https://github.com/matrixorigin/matrixone/issues/2376，closed.
