### ISSUE TITLE
[Bug]: The result of month,weekday error when the value of char  or varchar type is null

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2366]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from t1 where id = 14;
+------+------+------+------+------+
| id   | d    | dt   | c    | vc   |
+------+------+------+------+------+
|   14 | NULL | NULL | NULL | NULL |
+------+------+------+------+------+
1 row in set (0.03 sec)

mysql> select month(c) from t1 where id =14;
ERROR 1105 (HY000): unknown error:[22000]Incorrect datetime value
mysql> select weekday(vc) from t1 where id =14;
ERROR 1105 (HY000): unknown error:[22000]Incorrect datetime value
mysql> 

### Expected Behavior

select weekday(vc) from t1 where id =14;

**Comment by broccoliSpicy** [comment]
fixed

**Comment by aressu1985** [comment]
fixed
mysql> select month(c),weekday(vc) from t1;
+----------+-------------+
| month(c) | weekday(vc) |
+----------+-------------+
|       12 |           3 |
|       12 |           3 |
|        2 |           0 |
|        2 |           0 |
|        2 |           0 |
|        3 |           2 |
|        4 |           3 |
|        5 |           2 |
|        6 |           3 |
|        7 |           6 |
|        8 |           6 |
|        9 |           3 |
|       10 |           6 |
|       11 |           6 |
|       12 |           6 |
|     NULL |        NULL |
+----------+-------------+
16 rows in set (0.00 sec)
