### ISSUE TITLE
[Feature Request]: Support DDL for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2370]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

**Create database**
_CREATE {DATABASE | SCHEMA} [IF NOT EXISTS] db_name
    [create_option] ..._

_create_option: [DEFAULT] {
    CHARACTER SET [=] charset_name
  | COLLATE [=] collation_name
  | ENCRYPTION [=] {'Y' | 'N'}
}_

**Drop database**
_DROP DATABASE [IF EXISTS] db_name_

**Create table**
_CREATE [TEMPORARY] TABLE [IF NOT EXISTS] tbl_name
    (create_definition,...)
    [table_options]_

_create_definition: {
    col_name column_definition
   | [CONSTRAINT [symbol]] PRIMARY KEY
}_

_column_definition: {
    data_type [NOT NULL | NULL] [DEFAULT {literal | (expr)} ]
       [AUTO_INCREMENT] [UNIQUE [KEY]] [[PRIMARY] KEY]
      [COMMENT 'string']
  | data_type
      [COLLATE collation_name]
      [UNIQUE [KEY]] [[PRIMARY] KEY]
      [COMMENT 'string']
      [check_constraint_definition]
}_

For better performance, I suggest involve **_partition clause_** in CREATE TABLE. If TAE supports partition, CREATE TABLE statement should support this in 0.5.

**Drop table**
_DROP [TEMPORARY] TABLE [IF EXISTS]
    tbl_name [, tbl_name] ...
    [RESTRICT | CASCADE]_

**Comment by JinHai-CN** [comment]
Now, MatrixOne will support following statements:

CREATE DATABASE [IF NOT EXISTS] db_name

DROP DATABASE [IF EXISTS] db_name

CREATE TABLE [IF NOT EXISTS] tbl_name
(create_definition,...)
[table_options]

create_definition: {
col_name column_definition
| [CONSTRAINT [symbol]] PRIMARY KEY
}

column_definition: {
data_type [NOT NULL | NULL] [PRIMARY KEY] | data_type
}

DROP TABLE [IF EXISTS] tbl_name [, tbl_name] ...

**Comment by domingozhang** [comment]
auto_increment will not be supported in 0.5.0. Will raise another feature request in future.

**Comment by domingozhang** [comment]
part of ddl supported for tpch has been completed. the legacy part will be implemented in 0.6.0
