### ISSUE TITLE
[Feature Request]: Support arithmetic operators for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2374]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

According to TPCH 22 queries, these operators are required. These should be used for all data types in #2369

_"%", Modulo operator
"+", Addition operator
"-", Minus operator
"/", Division operator
"DIV", Integer division_

**For different types of numeric values, these can be used between them.**
Such as 
A is a float while b is an integer, can be calculated for a*b.

**Comment by JinHai-CN** [comment]
Would you please check if all of them are supported currently ?

**Comment by daviszhen** [comment]
it was done
