### ISSUE TITLE
[Feature Request]: Comparison operators for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2375]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

TPCH needs these comparison operators for queries.
For different numeric types, they can be used to. 
Such as 1>0.999. Constant can be involved in their caculation such as "a between b+0.1 and b-0.1"

These should be used for all data types in https://github.com/matrixorigin/matrixone/issues/2369

 _">", Greater than operator
">=",  Greater than or equal operator
"<",   Less than operator
"<>", "!=",  Not equal operator
"<=",  Less than or equal operator
"= ",  Equal operator
"BETWEEN ... AND ...", Whether a value is within a range of values
"IN()",    Whether a value is within a set of values
"INTERVAL()",  Return the index of the argument that is less than the first argument
"IS",  Test a value against a boolean
"IS NOT",  Test a value against a boolean
"IS NOT NULL", NOT NULL value test
"IS NULL", NULL value test
"LIKE",  Simple pattern matching
"NOT BETWEEN ... AND ...", Whether a value is not within a range of values
"NOT IN()",    Whether a value is not within a set of values
"NOT LIKE",    Negation of simple pattern matching_

**Comment by domingozhang** [comment]
Currently, the following operators are not supported.

"INTERVAL()", Return the index of the argument that is less than the first argument
"IS", Test a value against a boolean
"IS NOT", Test a value against a boolean
"IS NOT NULL", NOT NULL value test
"IS NULL", NULL value test

**Comment by JinHai-CN** [comment]
#1880 related to this issue.

**Comment by ouyuanning** [comment]
rewrite in/not in expr is done
see #2814

**Comment by daviszhen** [comment]
"BETWEEN ... AND ...", Whether a value is within a range of values 

is done by @ouyuanning

**Comment by daviszhen** [comment]
"INTERVAL()", Return the index of the argument that is less than the first argument

is replaced by date_add / date_sub.
@bbbearxyz

**Comment by daviszhen** [comment]
Missing :

"IS", Test a value against a boolean
"IS NOT", Test a value against a boolean
"IS NOT NULL", NOT NULL value test
"IS NULL", NULL value test

they are in @broccoliSpicy 's plan
