### ISSUE TITLE
[Feature Request]: Subqueries with EXISTS or NOT EXISTS for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2376]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Exists or not exists subquery have to be supported for TPCH as following.

_SELECT column_exp FROM table_reference WHERE [NOT] EXISTS (**subquery**)_

A **subquery** is a SELECT statement by following #2372

**Comment by ouyuanning** [comment]
build basic subquery plan is ok.

**Comment by aressu1985** [comment]
fixed
