### ISSUE TITLE
[Feature Request]: CASE Statement for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2377]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CASE statement is used for TPCH in some queries. The syntax is as following.

_CASE case_value
    WHEN when_value THEN statement_list
    [WHEN when_value THEN statement_list] ...
    [ELSE statement_list]
END CASE_

OR

_CASE
    WHEN search_condition THEN statement_list
    [WHEN search_condition THEN statement_list] ...
    [ELSE statement_list]
END CASE_

For the first syntax, case_value is an expression. This value is compared to the when_value expression in each WHEN clause until one of them is equal. When an equal when_value is found, the corresponding THEN clause statement_list executes. If no when_value is equal, the ELSE clause statement_list executes, if there is one.

For the second syntax, each WHEN clause search_condition expression is evaluated until one is true, at which point its corresponding THEN clause statement_list executes. If no search_condition is equal, the ELSE clause statement_list executes, if there is one.

If no when_value or search_condition matches the value tested and the [CASE](https://dev.mysql.com/doc/refman/8.0/en/case.html) statement contains no ELSE clause, a Case not found for CASE statement error results.

Each statement_list consists of one or more SQL statements; an empty statement_list is not permitted.

**Comment by ouyuanning** [comment]
we can build CASE Statement in plan2 now.

**Comment by m-schen** [comment]
supported decimal, char, varchar now.

**Comment by aressu1985** [comment]
fixed
