### ISSUE TITLE
[Feature Request]: Subquery as Derived Tables in FROM clause for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2378]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

A derived table is an expression that generates a table within the scope of a query FROM clause. For example, a subquery in a SELECT statement FROM clause is a derived table:

_SELECT ... FROM (subquery) [AS] tbl_name ..._

The subquery is a SELECT statement by following #2372

**Comment by JinHai-CN** [comment]
TPCH will be supported in 0.5.0.
