### ISSUE TITLE
[Feature Request]: WITH (Common Table Expressions) for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2379]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Common table expression (CTE) is used in TPCH. The syntax is as following.

_with_clause:
    WITH [RECURSIVE]
        cte_name [(col_name [, col_name] ...)] AS (subquery)
        [, cte_name [(col_name [, col_name] ...)] AS (subquery)] ..._

**Example：**
_WITH
  cte1 AS (SELECT a, b FROM table1),
  cte2 AS (SELECT c, d FROM table2)
SELECT b, d FROM cte1 JOIN cte2
WHERE cte1.a = cte2.c;_

**Comment by JinHai-CN** [comment]
Recursive CTE will not be supported now.

**Comment by aressu1985** [comment]
fixed
