### ISSUE TITLE
[Feature Request]: Support Temporal Intervals for TPCH

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2381]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Temporal Intervals is used in TPCH and the syntax is as following.

_date + INTERVAL expr unit
date - INTERVAL expr unit_

The **_expr_** represents a quantity and **_unit_** represents the unit for interpreting the quantity; it is a specifier such as HOUR, DAY, or WEEK. The INTERVAL keyword and the unit specifier are not case-sensitive.

The unit contains these :
_YEAR
QUARTER
MONTH
WEEK
DAY
HOUR
MINUTE
SECOND_

**Comment by dengn** [comment]
As time intervals are used in many date functions such as https://github.com/matrixorigin/matrixone/issues/2328 and https://github.com/matrixorigin/matrixone/issues/2331, 
do MICROSECOND and combination expressions like "MINUTE_MICROSECOND" need to be supported as well?

**Comment by bbbearxyz** [comment]
support all unit: 	
        MicroSecond
	Second
	Minute
	Hour
	Day
	Week
	Month
	Quarter
	Year
	Second_MicroSecond
	Minute_MicroSecond
	Minute_Second
	Hour_MicroSecond
	Hour_Second
	Hour_Minute
	Day_MicroSecond
	Day_Second
	Day_Minute
	Day_Hour
	Year_Month

**Comment by aressu1985** [comment]
fixed
