### ISSUE TITLE
[Feature Request]: Support golang mysql driver for MO

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2387]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Go mysql driver supports go version more than 1.13 and can used to Mysql, MariaDB and other mysql branch databases.
Details are as following.
https://github.com/go-sql-driver/mysql

**Comment by daviszhen** [comment]
It has been supported now.

**Comment by daviszhen** [comment]
It has a close relationship with the catalog. The catalog should provide system variables, meta data tables,etc. It may also need features like SSL, role,user,privilige in 0.5.

**Comment by florashi181** [comment]
@domingozhang  same as #2386 ， pls confirm it.

**Comment by badboynt1** [comment]
write some cases to test go sql driver with MatrixOne, the code is in
https://github.com/badboynt1/testgosqldriver
all common apis are supported and works fine, the list is in https://github.com/badboynt1/matrixone/blob/main/docs/go_mysql_driver.md
