### ISSUE TITLE
[Feature Request]:  Support write batch rate limit

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2390]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

Yes, when executing concurrent loading, the mo server may crash  because of pebble panic, details can be referred to https://github.com/matrixorigin/matrixcube/issues/774

### Describe the feature you'd like

Support rate limit.

**Comment by daviszhen** [comment]
This parameter can control maximum writing speed of cube/pebble like  the`LimitRequestBytesPerShard` in the cube. In version 0.5.0, the distributed framework may be changed or replaced to the new stuff.  But, it is feasible for us to find a peer parameter in new stuff.

**Comment by jianwan0214** [comment]
this feature should be move to 0.0.6 version

**Comment by jianwan0214** [comment]
this feature is no longer needed because there is not cube.
