### ISSUE TITLE
[Question]: Do we need to support functionalities like SELECT @@global.time_zone; SET GLOBAL time_zone = '-6:00'; SET time_zone = '-6:00'; SELECT @@session.time_zone; now? what's our overall design for server timezone?

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#2398]
### Describe your problem

currently we get our localTimeZone by this
```go
func init() {
	startupTime = time.Now()
	_, offset := startupTime.Zone()
	localTZ = int64(offset)
}
```

Question 0: what's our timezone variable's granularity? session level(per connection)? server level(per server)? or both?

Question 1: what's our interface design?
        a variable in the system_vars_config.toml file?
        something like this: mo-server –e “SELECT @@global.time_zone;”?
        or using sql query: SELECT @@global.time_zone; SET GLOBAL time_zone = '-6:00'; SET time_zone = '-6:00'; SELECT @@session.time_zone;

**Comment by fengttt** [comment]
In general we should behave exactly the same as MySQL.    I think, server timezone is dubious at best, and the really (and only?) useful thing is the session time zone, but I could be wrong.   So can you please do some research on how MySQL handles timezone?   Does mysql has timestamp and timestamptz?   Are we supporting timestamp only at this moment?   In that case, there is simply no timezone and we should not adjust localTZ.

But I really don't know, the way to be sure, is check MySQL timezone related tests, and compare/confirm our result matching MySQL.

Also time zone should also support like 'US/Pacific'.

**Comment by broccoliSpicy** [comment]
mysql does not have timestamptz, postgres does.
from the description on tapd for timestamp, I think timezone is not part of the requirement.

but mysql does support queries like:
```sql
SET TIME_ZONE = '+00:00';
```
which changes the session timezone


I think we better support the modification of session timezone in order to fully support the usage of timestamp data type
