### ISSUE TITLE
[Bug]: parse 'select quarter' failed

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#2400]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select Quarter from ontime;
ERROR 1064 (42000): syntax error at position 20 near 'from'; You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use

**Comment by aressu1985** [comment]
fixed

mysql> select Quarter from ontime;
+------------+
| quarter    |
+------------+
| 2000-03-05 |
+------------+
1 row in set (0.00 sec)

mysql>
