### ISSUE TITLE
[Refactoring]: Fix sca for sql

### ISSUE THREAD

**Issue by yingfeng** [matrixorigin/matrixone#2406]
Sub task of https://github.com/matrixorigin/matrixone/issues/2133

plan: @m-schen 
plan2: @ouyuanning 
parsers/protocol: @iamlinjunhong 
container: @nnsgmsone 
rpcserver: @nnsgmsone 
sort: @nnsgmsone 
colexec: @m-schen 
vm/pipeline: @m-schen

**Comment by ouyuanning** [comment]
plan2 fixed
