### ISSUE TITLE
[Bug]: where clauses with built-in function do not work properly

### ISSUE THREAD

**Issue by chenlx0** [matrixorigin/matrixone#2415]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ae9595f
- Hardware parameters: x86_64, 2c4g
- OS type: Debian 11
- Others:
```

### Actual Behavior

How I create a test table and insert data:

```sql
create table t1(s varchar(64));
insert into t1 values('aaa');
insert into t1 values('');
```

Query:
```
MySQL [test]> select * from t1 where length(s);
Empty set (0.027 sec)
```
```
MySQL [test]> select * from t1 where empty(s);
Empty set (0.021 sec)
```

### Expected Behavior

```
mysql> select * from t1 where length(s);
+------+
| s    |
+------+
| aaa  |
+------+
1 row in set (0.00 sec)
```
```
mysql> select * from t1 where empty(s);
+------+
| s    |
+------+
|      |
+------+
1 row in set (0.00 sec)
```

### Additional information

MySQL consider the condition in such where clause as `true` if the built-in function return value greater than `0`.
But in martrixone, it seems that the condition would be `false` whatever the built-in function return.

**Comment by m-schen** [comment]
thanks for your issue. we will check the logic of length and empty function.

**Comment by m-schen** [comment]
we only support logic expression or something will return the boolean in where clause.

**Comment by fengttt** [comment]
not a bug.
