### ISSUE TITLE
[Feature Request]: Support bool datatype and related bool function

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#2419]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

The mo-db should support the bool datatype. And should support these expression like `select a<1 from t1;` to get bool datatype result. Also need to add some related bool functions like sum(), max(), min() and so on.

**Comment by daviszhen** [comment]
it was done on aoe. It should be checked on tae.
