### ISSUE TITLE
[Feature Request]: SHA256

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#2426]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

SHA256(varchar) returns the SHA256 digest of the string.

Others hash/digest function maybe useful as well, for example, BLAKE3

**Comment by lacrimosaprinz** [comment]
What is the affected user behavior? need me to provide document output?

**Comment by Morranto** [comment]
maybe its behavior is like this https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_sha2
