### ISSUE TITLE
[Question]: The code of this repository was not well formatted according to gofmt

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#2433]
### Describe your problem

There are many source code files which weren't well formatted according to `gofmt`.

If the changed files of a PR include these files, this PR would have very verbose diff, then the diff would lose clarity.

Please unify format for all the source code via `gofmt`:
```bash
# Recommendation
gofmt -s -w .
```

**Comment by m-schen** [comment]
yes, our code format has many problems now.

And we will fix the problem after lint-check-logic for PR has prepared.

If you create a new pull request now, you can just only
go fmt for files you  have changed now.

**Comment by fengttt** [comment]
What is -s?   Let's stick to default, if possible.

**Comment by cnutshell** [comment]
> What is -s? Let's stick to default, if possible.

-s	simplify code

For example, after applying `-s`, the diff would be:
```diff
- data: [][]string{[]string{"{-123450000 -1}"}, []string{"{-500000 -1}"}},
+ data: [][]string{{"{-123450000 -1}"}, {"{-500000 -1}"}},
```

**Comment by m-schen** [comment]
We have formatted the code by using `gofmt -s`
