### ISSUE TITLE
[Feature Request]: CAST support decimal conversion

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2448]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

As discussed in https://github.com/matrixorigin/matrixone/issues/2304, toDecimal will be supported by CAST function. 

```markdown

It's not supported for now. 

(dump@127.0.0.1) [abcl]>create table doubleTest(a double, b double);
(dump@127.0.0.1) [abcl]>insert into doubleTest values(123.4567, 123456.1234567891411241355);
(dump@127.0.0.1) [abcl]>select cast(a as decimal(10,5)) from doubleTest;
ERROR 1105 (HY000): unknown error:[42P18]'' is not support now
```

### Describe the feature you'd like

Follow the syntax of MySQL8.0.

With [CAST(expr AS type](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast) syntax, the CAST() function takes an expression of any type and produces a result value of the specified type. This operation may also be expressed as [CONVERT(expr, type)](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_convert), which is equivalent.

DECIMAL[(M[,D])]

When Decimal is specified as output type, it produces a [DECIMAL](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html) value. If the optional M and D values are given, they specify the maximum number of digits (the precision) and the number of digits following the decimal point (the scale). If D is omitted, 0 is assumed. If M is omitted, 10 is assumed.

**Comment by JackTan25** [comment]
#3042 it's solved
