### ISSUE TITLE
[Feature Request]: Case sensitive for MO

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2454]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In Mysql, table name can be set for both non case sensitive and case sensitive. Column name only supports non case sensitive.
![image](https://user-images.githubusercontent.com/88298673/167579034-cd693652-6e81-4116-a470-aa49630c30ae.png)

In current mo version, 0.4.0, both table name and column name are case sensitive as following.

mysql> create table t1(a int,b int);
Query OK, 0 rows affected (0.01 sec)

mysql> select * from T1;
ERROR 1105 (HY000): unknown error:[42000]table not exist
mysql> select a,B from t1;
ERROR 1105 (HY000): unknown error:[42000]Unknown column 'B'

Can we following the rules of MO as following:

- Table name can be set for either case sensitive or non case sensitive.
- Column name is non case sensitive by default and cannot be set to other values.

**Comment by florashi181** [comment]
@JinHai-CN please have a look about this issue.

**Comment by sukki37** [comment]
This is a repeat issue of https://github.com/matrixorigin/matrixone/issues/2208
