### ISSUE TITLE
[Question]: How to join two decimal?

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#2463]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

suppose we have two tables
create table t1(a decimal(10, 5));
create table t2(a decimal(20, 5));

t1.                           t2 

1.2                          1.2
int64(120000).        int128(120000)

if we hash join them, because this two 1.2 have different internal representation, their hash result are different, but these two should be equal

suppose we have another two tables
create table t1(a decimal(10, 3));
create table t2(a decimal(10, 5));

t1.                           t2 

1.2                          1.2
int64(1200).        int64(120000)

if we hash join them, because this two 1.2 have different internal representation, their hash result are different, but these two should be equal

**Comment by nnsgmsone** [comment]
Just provide a batch function to align,  decimal64 will need to be converted to decimal128 if required

**Comment by broccoliSpicy** [comment]
Solution:
    when join decimal64 and decimal128, cast decimal64 to decimal128 before join
    when join decimal64 with different scales, align them to the maximum scale
    when join decimal128 with different scales, align them to the maximum scale

**Comment by daviszhen** [comment]
it was fixed
