### ISSUE TITLE
[Bug]: Query on ARM failed when the table is large

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#2484]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.4.0
- Hardware parameters:arm
- OS type:centos8
- Others:
```

### Actual Behavior

When the size of the table is not very large,the query is ok.
mysql> select count(*) from dates;
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)
ERROR: 
Can't connect to the server

But when the size of the tale is larger than a certian value（i dont kown the value）,the query will fail and cause the mo panic.
mysql> select count(*) from dates;
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)
ERROR: 
Can't connect to the server

panic: invalid argument

goroutine 2197 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*Block).Prefetch(0x400bf44760, {0x400496c300, 0x1, 0x400d158730?})
        /mnt/matrixone/pkg/vm/engine/aoe/storage/db/blk.go:84 +0x160
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.(*worker).Start(0x400aac68a0, {0x4002b72f68, 0x1, 0x1}, {0x400496c300, 0x1, 0x1})
        /mnt/matrixone/pkg/vm/engine/aoe/engine/worker.go:64 +0x118
created by github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.(*store).ReadStart
        /mnt/matrixone/pkg/vm/engine/aoe/engine/store.go:128 +0x324
panic: invalid argument

goroutine 2195 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/storage/db.(*Block).Prefetch(0x400bf446e0, {0x400496c300, 0x1, 0x0?})
        /mnt/matrixone/pkg/vm/engine/aoe/storage/db/blk.go:84 +0x160
github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.(*worker).Start(0x400aac67e0, {0x4002b72f68, 0x1, 0x1}, {0x400496c300, 0x1, 0x1})
        /mnt/matrixone/pkg/vm/engine/aoe/engine/worker.go:64 +0x118
created by github.com/matrixorigin/matrixone/pkg/vm/engine/aoe/engine.(*store).ReadStart
        /mnt/matrixone/pkg/vm/engine/aoe/engine/store.go:128 +0x324

**Comment by dengn** [comment]
Which platform and hardware specification does this test work on?

**Comment by JinHai-CN** [comment]
Now the storage engine is TAE. Please re-run this case again.

**Comment by aressu1985** [comment]
fixed
