### ISSUE TITLE
[Feature Request]: Datetime function UNIX_TIMESTAMP()

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2488]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

https://github.com/matrixorigin/matrixone/issues/1871

### Describe the feature you'd like

Follow the behavior and syntax of MySQL 8.0.

[UNIX_TIMESTAMP([date])](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp)

If UNIX_TIMESTAMP() is called with no date argument, it returns a Unix timestamp representing seconds since '1970-01-01 00:00:00' UTC.

If [UNIX_TIMESTAMP()](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp) is called with a date argument, it returns the value of the argument as seconds since '1970-01-01 00:00:00' UTC. The server interprets date as a value in the session time zone and converts it to an internal Unix timestamp value in UTC.

The date argument may be a [DATE](https://dev.mysql.com/doc/refman/8.0/en/datetime.html), DATETIME, or TIMESTAMP string, or a number in YYMMDD, YYMMDDhhmmss, YYYYMMDD, or YYYYMMDDhhmmss format. If the argument includes a time part, it may optionally include a fractional seconds part.

The return value is an integer if no argument is given or the argument does not include a fractional seconds part, or [DECIMAL](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html) if an argument is given that includes a fractional seconds part.

When the date argument is a [TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) column, UNIX_TIMESTAMP() returns the internal timestamp value directly, with no implicit “string-to-Unix-timestamp” conversion.

Follow the behavior before 8.0.26, the timestamp ranges from '1970-01-01 00:00:01.000000' UTC to '2038-01-09 03:14:07.999999' UTC.

**Comment by dengn** [comment]
Please refer to the corresponding test cases: https://github.com/dengn/mo-tester/blob/main/cases/function/func_datetime_unixtime.test

**Comment by JackTan25** [comment]
#2985

**Comment by dengn** [comment]
UNIX_TIMESTAMP is implemented without set timestamp. need to be resolved in 0.6

**Comment by goodMan-code** [comment]
Summer Time has nothing to do with TIMESTAMP calculation, because TIMESTAMP calculation uses UTC time, which is a constant value. As long as we do not switch time zones when calculating TIMESTAMP, the TIMESTAMP obtained is constant and has no relation to Summer Time.

**Comment by goodMan-code** [comment]
This Feature Request has done, can be closed pls, It be tested manual
