### ISSUE TITLE
[Question]: for our ci/cd testing, do we only test it on x86 platform, or we test it on both x86/arm, are we planning to test it on both platform?

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#2505]
### Describe your problem

why test failures like issue#2497 are't caught by ci/cd testing

**Comment by sukki37** [comment]
multiple platforms ( not only the architecture but operating system ) testing preparation is in progress. @aressu1985

**Comment by fengttt** [comment]
done
