### ISSUE TITLE
[Feature Request]: Disable linter `ineffassign` for non-test code, just enable it for test code.

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#2508]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

In non-test code, some assignments would be marked as `to an existing but not used variable`.
Hence, some normal code would be rejected which is unexpected, for example variable `charSize`.

```go
func countUTF8CodePoints(s []byte) uint64 {
	var charSize uint8 = 0  // here, charSize is marked via ineffassign
	var count uint64 = 0
	length := len(s)

	for i := 0; i < length; {
		charSize = table[s[i]]
		count++
		i = i + int(charSize)
	}
	return count
}
```

### Describe the feature you'd like

So we should disable `ineffassign` for non-test code.
Still there is necessity to enable this linter for test code.
One can accomplish this via option `--skip-files` of `golangci-lint`.

**Comment by cnutshell** [comment]
Related with #2133

**Comment by cnutshell** [comment]
Or we could warn on non-test code, and error on test code.

**Comment by sukki37** [comment]
tracking by #3100
