### ISSUE TITLE
[Bug]: The value of "-0" is different from int and float

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2510]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In the int column, both +0 and -0 is 0.
However in the float one, it's different.

mysql> create table t1(a int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 values(+0),(-0);
Query OK, 2 rows affected (0.00 sec)

mysql> select * from t1;
+------+
| a    |
+------+
|    0 |
|    0 |
+------+

mysql> create table t2(a float);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t2 values(+0),(-0);
Query OK, 2 rows affected (0.00 sec)

mysql> select * from t2;
+---------+
| a       |
+---------+
|  0.0000 |
| -0.0000 |
+---------+
2 rows in set (0.00 sec)

**Comment by nnsgmsone** [comment]
Also nan and -nan should not be inserted.

**Comment by aressu1985** [comment]
fixed 

mysql> select count(*) from lineitem;
+----------+
| count(*) |
+----------+
|  6001215 |
+----------+
1 row in set (0.01 sec)

mysql> create table t2(a float);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t2 values(+0),(-0);
Query OK, 2 rows affected (0.01 sec)

mysql> select * from t2;
+------+
| a    |
+------+
|    0 |
|    0 |
+------+
2 rows in set (0.00 sec)

mysql>
