### ISSUE TITLE
[Refactoring]: fix cases marked by linter `errcheck` for package `github.com/matrixorigin/matrixone/pkg/sql/compile`

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#2526]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
We should check all the cases marked by linter errcheck.
Errcheck is a program for checking for unchecked errors in go programs. 
These unchecked errors can be critical bugs in some cases.
```

### Describe the solution you'd like

Check all the cases marked by linter errcheck and evaluate them.
If an unchecked error can be critical bugs in some cases, then fix it.

### Additional information

How to find all the cases via `errcheck` for package `github.com/matrixorigin/matrixone/pkg/sql/compile`:
```bash
git clone https://github.com/matrixorigin/matrixone.git
cd matrixone
## This will show all the cases for both normal code and test code
golangci-lint run --disable-all -E errcheck \
    --max-same-issues 10000 --max-issues-per-linter 10000 pkg/sql/compile/...
```

If you want to find cases for non-test code only, using option `--skip-files ".+_test.go"`:
```bash
golangci-lint run --disable-all -E errcheck \
    --max-same-issues 10000 --max-issues-per-linter 10000 --skip-files ".+_test.go" pkg/sql/compile/...
```

The output of this command would be:
```bash
pkg/sql/compile/scope.go:354:15: Error return value of `vector.Append` is not checked (errcheck)
	vector.Append(bat.Vecs[0], nameVector)         // field
	             ^
```

**Comment by cnutshell** [comment]
Related with issue #2133

**Comment by nnsgmsone** [comment]
fixed by 2541

**Comment by cnutshell** [comment]
Resolved, close this issue.
