### ISSUE TITLE
Function migrate  to plan2

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#2565]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
in order to execute the new plan structrue(plan2)
we need some method to execute the values of expression in the plan tree,
so we need to migrate built-in functions, aggregate functions and operators to plan2 architecture.
```

### Describe the solution you'd like

steps:
Summarize the built-in functions, aggregate functions and operators into the function registry data structure
Add semantic check according to the parameters of different functions
Migrating computational logic to functions

**Comment by m-schen** [comment]
it's same to #2329 and so on.
