### ISSUE TITLE
[Refactoring]:  unsafe recover() found

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2612]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
# github.com/matrixorigin/matrixone/pkg/sql/compile2
pkg/sql/compile2/compile.go:55:11: unsafe recover() found: in github.com/matrixorigin/matrixone/pkg/sql/compile2.compile.Compile()
pkg/sql/compile2/compile.go:68:11: unsafe recover() found: in github.com/matrixorigin/matrixone/pkg/sql/compile2.compile.Run()
```

### Describe the solution you'd like

fix those static check warnings

**Comment by lni** [comment]
Good to see the tool is actually working as expected. 

Those recover() calls should probably be whitelisted. I will double check with @nnsgmsone on Monday and update the tool.

**Comment by fengttt** [comment]
Recover for pipeline (and report meaningful error) to remote should be whitelisted.

**Comment by nnsgmsone** [comment]
> Recover for pipeline (and report meaningful error) to remote should be whitelisted.

yes

**Comment by lni** [comment]
https://github.com/matrixorigin/linter has been updated with the above recover() calls whitelisted.
