### ISSUE TITLE
[Feature Request]: Support TPCH queries on both TAE and AOE

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2619]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Because AOE and TASE will run in parallel for future several releases, TPCH needs to be supported on both TAE and AOE. The details are as following:

1. All the TPCH DDL contains CREATE DATABASE, CREATE TABLE, DROP DATABASE and DROP TABLE. 
2. The same datatype in TPCH as #2369 .
3. LOAD DATA needs to be supported for importing TPCH data from csv to data tables.
4. All 22 queries of TPCH will run on AOE. The query result needs to be the same as MySQL and TAE.
5. AOE with cluster nodes needs to be supported as well.

**Comment by florashi181** [comment]
we don't support AOE in MatrixOne  anymore since v0.5.
