### ISSUE TITLE
[Feature Request]: Support buildin function date_add date_sub

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#2622]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support buildin function date_add and date_sub like 
mysql> SELECT DATE_ADD('2018-05-01',INTERVAL 1 DAY);
        -> '2018-05-02'
mysql> SELECT DATE_SUB('2018-05-01',INTERVAL 1 YEAR);
        -> '2017-05-01'

**Comment by dengn** [comment]
Part duplicate to https://github.com/matrixorigin/matrixone/issues/2331

**Comment by bbbearxyz** [comment]
I complete it, pr is https://github.com/matrixorigin/matrixone/pull/2908

**Comment by aressu1985** [comment]
fixed
