### ISSUE TITLE
[Bug]:  strange errors when executing ddl

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2636]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d3293ca03ea563d7c17de549873f81070dd0780d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

maybe something is wrong with system_table handling...

<img width="663" alt="image" src="https://user-images.githubusercontent.com/77312370/169981296-438b5c85-1f49-40cd-ba52-73035dd3aac4.png">

**Comment by daviszhen** [comment]
I will check the problem "use T" and fix it in the next pr.
But, "show XXXX" are catalog operations and translated into select statements that have not been supported by the computation engine which is under development. It is better to deliver them to developer related.

**Comment by m-schen** [comment]
has supported now.
