### ISSUE TITLE
[Question]: Which one will be the result of plan2

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2674]
### Describe your problem

Regarding the computing between two date value, database acts differetly. Take this as example:
select cast('2022-02-01' as date)-cast('2022-01-01' as date);

In MySQL, the result is 100.
In PG, the result is 31.
In SQLServer and Oracle, the result is not supported directly. But using to_date function, the result is 31.

**Comment by m-schen** [comment]
31 is better

mysql maybe store the date as int (20220201) and (20220101), so it get the result 100.
