### ISSUE TITLE
[Bug]: The result of show table is incorrect

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2702]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> show tables;
+------------------+
| Tables_in_test01 |
+------------------+
| t1               |
| t2               |
+------------------+

### Expected Behavior

mysql> show tables;
+------------------+
| Tables |
+------------------+
| t1               |
| t2               |
+------------------+

### Steps to Reproduce

drop database if exists test01;
create database test01;
use test01;
create table t1 (id int not null, str char(10),name varchar(10));
create table t2 (a int);
show tables;

**Comment by daviszhen** [comment]
It is not a bug. It is same as mysql
