### ISSUE TITLE
[Bug]: The result of show column is incorrect

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2703]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

+-------+-------------+------+------+---------+---------+
| Field | Type        | Null | Key  | Default | Comment |
+-------+-------------+------+------+---------+---------+
| id    | INT         | YES  |      |         |         |
| str   | VARCHAR(10) | YES  |      |         |         |
| name  | VARCHAR(10) | YES  |      |         |         |
+-------+-------------+------+------+---------+---------+

### Expected Behavior

+-------+-------------+------+------+---------+---------+
| Field | Type        | Null | Key  | Default | Extra |
+-------+-------------+------+------+---------+---------+
| id    | INT         | YES  |      |         |         |
| str   | VARCHAR(10) | YES  |      |         |         |
| name  | VARCHAR(10) | YES  |      |         |         |
+-------+-------------+------+------+---------+---------+

### Steps to Reproduce

```markdown
drop database if exists test01;
create database test01;
use test01;
create table t1 (id int not null, str char(10),name varchar(10));
create table t2 (a int);
show columns from t1;
```

**Comment by daviszhen** [comment]
Is it not a bug. We do not support `Extra` in 0.5. The situation has been clarified in catalog survey doc.

**Comment by daviszhen** [comment]
It is not a bug. It is same as the design at the beginning of the 0.6.
