### ISSUE TITLE
[Bug]: the projection of agg node is incorrect

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2705]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[typ:{id:INT32 width:32} table_name:"t1" col_name:"userid" col:{rel_pos:-1} typ:{id:INT32 width:32} col_name:"userid" col:{rel_pos:-1} typ:{id:INT16} col_name:"min(score)" col:{rel_pos:-2}]

### Expected Behavior

[typ:{id:INT32 width:32} col_name:"userid" col:{rel_pos:-1} typ:{id:INT16} col_name:"min(score)" col:{rel_pos:-2}]

### Steps to Reproduce

```markdown
create table t1 (spID int,userID int,score smallint);
insert into t1 values (1,1,1);
insert into t1 values (2,2,2);
insert into t1 values (2,1,4);
insert into t1 values (3,3,3);
insert into t1 values (1,1,5);
insert into t1 values (4,6,10);
insert into t1 values (5,11,99);
select userID, MIN(score) from t1 group by userID order by userID desc;
```

**Comment by aressu1985** [comment]
fixed 

mysql> create table t1 (spID int,userID int,score smallint);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 values (1,1,1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (2,2,2);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t1 values (2,1,4);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (3,3,3);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (1,1,5);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (4,6,10);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (5,11,99);
Query OK, 1 row affected (0.00 sec)

mysql> select userID, MIN(score) from t1 group by userID order by userID desc;
+--------+------------+
| userid | min(score) |
+--------+------------+
|     11 |         99 |
|      6 |         10 |
|      3 |          3 |
|      2 |          2 |
|      1 |          1 |
+--------+------------+
5 rows in set (0.00 sec)

mysql>
