### ISSUE TITLE
[Bug]: Wrong position  when  alias exists

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2708]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: runtime error: index out of range [2] with length 2

projection of agg node is wrong:
```
typ:{id:INT32  width:32}  table_name:"t1"  col_name:"userid"  col:{rel_pos:-1} typ:{id:INT32  width:32}  col_name:"a"  col:{rel_pos:-1} typ:{id:INT32  width:32}  col_name:"a"  col:{rel_pos:-1} typ:{id:INT16}  col_name:"b"  col:{rel_pos:-2} typ:{id:INT16}  col_name:"b"  col:{rel_pos:-2}]
```
The pos's here are just pointers, they may refer to the same memory and if the optimiser or compile modifies one of the pos's it may lead to unintended consequences. A value should be used here instead of a pointer.

### Expected Behavior

a   b
1   1
2   2
3   3
6   10
11  99

### Steps to Reproduce

```markdown
create table t1 (spID int,userID int,score smallint);
insert into t1 values (1,1,1);
insert into t1 values (2,2,2);
insert into t1 values (2,1,4);
insert into t1 values (3,3,3);
insert into t1 values (1,1,5);
insert into t1 values (4,6,10);
insert into t1 values (5,11,99);
select userID as a, MIN(score) as b from t1 group by userID order by userID;
```

**Comment by aressu1985** [comment]
fixed

mysql> create table t1 (spID int,userID int,score smallint);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1,1,1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (2,2,2);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (2,1,4);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t1 values (3,3,3);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (1,1,5);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (4,6,10);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values (5,11,99);
Query OK, 1 row affected (0.00 sec)

mysql> select userID as a, MIN(score) as b from t1 group by userID order by userID;
+------+------+
| a    | b    |
+------+------+
|    1 |    1 |
|    2 |    2 |
|    3 |    3 |
|    6 |   10 |
|   11 |   99 |
+------+------+
5 rows in set (0.01 sec)
