### ISSUE TITLE
[Bug]:  unsupport select statement(DISTINCT with GROUP BY): *tree.SelectClause

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2709]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR 1105 (HY000): unknown error:[03000]unsupport select statement(DISTINCT with GROUP BY): *tree.SelectClause

### Steps to Reproduce

```markdown
select distinct userID, count(score) from t1 group by userID order by userID;
```

**Comment by aressu1985** [comment]
fixed

mysql> create table t1(userID int,score int);
Query OK, 0 rows affected (0.00 sec)

mysql> select distinct userID, count(score) from t1 group by userID order by userID;
Empty set (0.01 sec)

mysql>
