### ISSUE TITLE
[Bug]:  unknown error when executing `show tables` , tae, plan2

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2717]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): aeb1ce2a5ded5dae426c23ba9adb7e9724644f61
- Hardware parameters:
- OS type:
- Others: related to https://github.com/matrixorigin/matrixone/issues/2702
```

### Actual Behavior

1.  unhandled error msg is thrown to the MySQL client
2. no err log can be found in mo-server logs

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/77312370/171035104-7058e11d-bc54-4731-9003-5d17274596db.png">

### Steps to Reproduce

```markdown
drop database if exists test01;
create database test01;
use test01;
create table t1 (id int not null, str char(10),name varchar(10));
create table t2 (a int);
show tables;
```

**Comment by daviszhen** [comment]
On tae, `show xxx` should be rewritten into `select` first and executed. It has different behaviours from `show xxx` on aoe

**Comment by sukki37** [comment]
tracking by #2653
