### ISSUE TITLE
[Bug]:  data which inserted into a table successfully can not be selected, plan2, tae

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2718]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):aeb1ce2a5ded5dae426c23ba9adb7e9724644f61
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert five rows into a table, but nothing returned when `select *`
<img width="477" alt="image" src="https://user-images.githubusercontent.com/77312370/171035519-ca91896f-44f9-4222-9ec4-ab2c536d804c.png">

### Steps to Reproduce

```markdown
create table t1(a int,b int);
select * from t1;
insert into t1 values(5,-2),(10,3),(100,0),(4,3),(6,-3);
select * from t1;
```

**Comment by LeftHandCold** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/14086886/171077784-0192603b-9ab2-4b66-8a49-4dc09309b23b.png">
tae has returned data @nnsgmsone

**Comment by sukki37** [comment]
double-checked with 093b68c84585b2cc039756e66d97649382aed4e7
