### ISSUE TITLE
[Question]: The LOAD DATA action in TAE

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2742]
### Describe your problem

In AOE, the row number of target table of LOAD DATA is increasing during load action. 
mysql> select count(*) from lineorder;
32000000

In MySQL, the row number of it will be 0 before LOAD DATA command finishes.

mysql> select count(*) from lineorder;
+----------+
| count(*) |
+----------+
|        0 |
+----------+

Now TAE supports transactions in 0.5.0. Will the action will be as same as MySQL or AOE?

**Comment by nnsgmsone** [comment]
i think the action will be as same as mysql.

**Comment by XuPeng-SH** [comment]
As I know, right now, the load is implemented by multiple batch insert transactions. If you load 1G, it will be divided into various transactions. So you can see the row number is increasing during loading.

However, it is just a temporary solution. We'll support the real bulk load in the next release, that is, a load that belongs to only one transaction, before the load is committed, you can not see any rows.
