### ISSUE TITLE
[Bug]: EXPLAIN failed when aggregation function without GROUP BY

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2751]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select sum(ti) from t1 order by ti;
+---------+
| sum(ti) |
+---------+
|      39 |
+---------+
1 row in set (0.03 sec)

explain select sum(ti) from t1 order by ti;
ERROR 1105 (HY000): unknown error:[42803]'ti' must appear in the GROUP BY clause or be used in an aggregate function

**Comment by qingxinhome** [comment]
@domingozhang ，Sorry，Is there any table structure and data for this use case? The table I built cannot be reproduced

**Comment by qingxinhome** [comment]
For example, sql: ’ select sum (ti) from t1 order by ti; ‘
Currently, an error will be reported when building a plan in plan2. The explain function is based on plan2, so an error will also be reported.This SQL can be executed normally in Plan1. @domingozhang

**Comment by qingxinhome** [comment]
For functions that have aggregate functions and aggregate fields appear in the word order by, for example, 'select sum (ti) from T1 order by ti;', In Plan1, it is supported and can be executed. In plan2, buildplan reports an error. Please confirm.  @ouyuanning

**Comment by ouyuanning** [comment]
the Actual  Behavior is right, just like pg. 
we won't fix it

**Comment by gaoxinge** [comment]
@ouyuanning The command in mysql can be executed without any error:

![1657116184(1)](https://user-images.githubusercontent.com/16648345/177568708-1efc7849-6fb6-4d15-b781-1474ddc125dd.png)

**Comment by gaoxinge** [comment]
@ouyuanning 

I use the mysql 8.0.29:

![1657158720(1)](https://user-images.githubusercontent.com/16648345/177673093-01a4776d-07ee-4c2b-9ade-079e70a782d9.png)

**Comment by ouyuanning** [comment]
mo not same as mysql in this case.

follow these rule: https://github.com/matrixorigin/docs/blob/main/design/plan2/plan2_build_agg.md

**Comment by gaoxinge** [comment]
@ouyuanning Your link is 404.

**Comment by ouyuanning** [comment]
Sorry,  it's Private docs now。
In this test case, Mo follow rule like PgSQL.

**Comment by domingozhang** [comment]
fix
