### ISSUE TITLE
[Bug]: select query each time parameter is all columns.plan2/tae

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#2787]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9b13db9bfa1ac8ee46ad290df71d8c2084f870e8
- Hardware parameters:
- OS type:all
- Others:
```

### Actual Behavior

Execute sql: select count(LO_ORDERKEY) from lineorder_flat;
tae get attrs are all columns.

### Additional information

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/14086886/172010355-ae0b1d12-46fd-4f07-833d-964458178ce9.png">

**Comment by m-schen** [comment]
column cut not implement now. it's a normal performance

**Comment by m-schen** [comment]
verified that, when we get all columns, tae's memory meets our expectations.
and why we get all columns is that we didn't have column cut rule at v0.5
