### ISSUE TITLE
[Bug]: the same sql behaves inconsistently on tae

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2816]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b7f0035457c77c4360b56bcd38dbd92f591ec2c1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

We get inconsistent results from TAE when executing the same SQL.

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/77312370/172149682-b100f98f-6e01-4292-b03f-5b8b480ffca5.png">

**Comment by XuPeng-SH** [comment]
It is triggered by #2819 . But the root cause is #2821
