### ISSUE TITLE
[Bug]: incorrect behavior for handling write relation errors

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#2821]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Step 6 should be ok
**Step 7 should not be ok (duplicated key)
Step 8 should not be ok (duplicated key)**

### Expected Behavior

Step 6 is ok
**Step 7 is ok. ( It returns ok to MySQL client but then executes rollback)
Step 8 `ERROR 2013 (HY000): Lost connection to MySQL server during query**

After step 7, the session will always lose the connection to server during query.

### Steps to Reproduce

```markdown
1. Use the latest main branch
2. Start mo-server with useplan2="true" and engine="tae"
3. Start MySQL client
4. create database test; use test; 
5. create table t1 (a integer not null, primary key(a));
6. insert into t1 values (1);
7. insert into t1 values (1);
8. insert into t1 values (1);
```

**Comment by daviszhen** [comment]
I will fix it in the tomorrow.

**Comment by daviszhen** [comment]
I found the `handleInsertValues` implemented with a bug. It shoud first get an result from relation.write, then if the result is right , it responses ok. if the result is error, it returns the error.
