### ISSUE TITLE
[Bug]: parser bug of processing colName

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2826]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 265b4f0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="927" alt="image" src="https://user-images.githubusercontent.com/77312370/172315017-5c2881a5-4187-484c-8545-587dc1fd9bc1.png">

**Comment by daviszhen** [comment]
ltrim ut check

**Comment by ouyuanning** [comment]
follow MO's column name rule

**Comment by aressu1985** [comment]
fixed
