### ISSUE TITLE
[Bug]: DIV is not /

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2831]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

0.5

### Expected Behavior

0

### Steps to Reproduce

```markdown
select 1 div 2;
```

**Comment by aressu1985** [comment]
fixed

mysql> select 1 div 2;
+---------+
| 1 div 2 |
+---------+
|       0 |
+---------+
1 row in set (0.00 sec)

mysql> select 1 div 3;
+---------+
| 1 div 3 |
+---------+
|       0 |
+---------+
1 row in set (0.00 sec)

mysql> select 6  div 3;
+---------+
| 6 div 3 |
+---------+
|       2 |
+---------+
1 row in set (0.01 sec)
