### ISSUE TITLE
[Bug]: count(*) is not count(a)

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

count(a)
7

### Expected Behavior

count(*)
7

### Steps to Reproduce

```markdown
create table a(a int);
insert into a values(1),(2),(3),(4),(5),(6),(7),(8);  
select count(*) from a where a>=2 and a<=8;
```

**Comment by aressu1985** [comment]
fixed 

mysql> create table a(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into a values(1),(2),(3),(4),(5),(6),(7),(8);  
Query OK, 8 rows affected (0.06 sec)

mysql> select count(*) from a where a>=2 and a<=8;
+----------+
| count(*) |
+----------+
|        7 |
+----------+
1 row in set (0.01 sec)
