### ISSUE TITLE
[Feature Request]: support string cast to date/datetime in the date_add/date_sub function

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#2836]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

SELECT DATE_ADD('2018-05-01',INTERVAL 1 DAY);
in the function, '2018-05-01' should parse to date. '2018-05-01 00:00:00' should parse to datetime.

**Comment by bbbearxyz** [comment]
I complete it, pr is https://github.com/matrixorigin/matrixone/pull/2908

**Comment by aressu1985** [comment]
fixed
