### ISSUE TITLE
The precision of float is different from MySQL 8.0

### ISSUE THREAD

**Issue by MOOS2021** [matrixorigin/matrixone#284]
drop table numtable;
create table numtable(id int,fl float, dl double);
insert into numtable values(1,123456,123456);
insert into numtable values(2,123.456,123.456);
insert into numtable values(3,1.234567,1.234567);
insert into numtable values(4,1.234567891,1.234567891);
insert into numtable values(5,1.2345678912345678912,1.2345678912345678912);

mysql> select * from numtable order by id;
+------+-----------+-------------------+
| id   | fl        | dl                |
+------+-----------+-------------------+
|    1 |    123456 |            123456 |
|    2 |   123.456 |           123.456 |
|    3 |  1.234567 |          1.234567 |
|    4 | 1.2345679 |       1.234567891 |
|    5 | 1.2345679 | 1.234567891234568 |
+------+-----------+-------------------+
5 rows in set (0.00 sec)

**in MySQL 8.0, the result is as following.**

mysql> select * from numtable order by 1;
+------+---------+-------------------+
| id   | fl      | dl                |
+------+---------+-------------------+
|    1 |  123456 |            123456 |
|    2 | 123.456 |           123.456 |
|    3 | 1.23457 |          1.234567 |
|    4 | 1.23457 |       1.234567891 |
|    5 | 1.23457 | 1.234567891234568 |
+------+---------+-------------------+
5 rows in set (0.01 sec)

**Comment by yingfeng** [comment]
Duplicate with #894
