### ISSUE TITLE
[Docs]: matrixone's modulo operator

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#2846]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

excerpts from sql standard
 <modulus expression> operates on two exact numeric arguments with scale 0 (zero) and returns the mod- ulus (remainder) of the first argument divided by the second argument as an exact numeric with scale 0 (zero).

todo: scale 0 decimals should also support modulo operation
all combinations of integers and unsigned integers should support modulo operation

**Comment by dengn** [comment]
@aressu1985 please help close this issue.
