### ISSUE TITLE
[Bug]: Aggregate function return wrong values in plan2

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#2852]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
Use plan2 and aoe engine
```

### Actual Behavior

commit version <img width="866" alt="image" src="https://user-images.githubusercontent.com/32733096/172520776-1f80069b-0196-4bba-8045-27a82246f138.png">

mysql> create table t4(a int);
mysql> insert into t4 values(0), (1), (null);
mysql> select min(a) from t4;
+--------+
| min(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.01 sec)

mysql> select max(a) from t4;
+--------+
| max(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.02 sec)

mysql> select sum(a) from t4;
+--------+
| sum(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.02 sec)

mysql> select avg(a) from t4;
+--------+
| avg(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.01 sec)

mysql> select count(*) from t4;
+----------+
| count(a) |
+----------+
|        2 |
+----------+
1 row in set (0.01 sec)

### Expected Behavior

mysql> select min(a) from t4;
+--------+
| min(a) |
+--------+
|      0 |
+--------+
1 row in set (0.01 sec)

mysql> select max(a) from t4;
+--------+
| max(a) |
+--------+
|      1 |
+--------+
1 row in set (0.00 sec)

mysql> select sum(a) from t4;
+--------+
| sum(a) |
+--------+
|      1 |
+--------+
1 row in set (0.01 sec)

mysql> select avg(a) from t4;
+--------+
| avg(a) |
+--------+
| 0.5000 |
+--------+
1 row in set (0.00 sec)

mysql> select count(*) from t4;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.01 sec)

**Comment by nnsgmsone** [comment]
I can't reproduce this bug.

**Comment by ouyuanning** [comment]
select count() from t4.  -> syntax error

select count(*) from t4;
+----------+
| count(*) |
+----------+
|        3 |
+----------+

**Comment by ouyuanning** [comment]
select count() from t4.  -> syntax error

select count(*) from t4;
+----------+
| count(*) |
+----------+
|        3 |
+----------+

**Comment by aressu1985** [comment]
fixed

mysql> create table t4(a int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t4 values(0), (1), (null);
Query OK, 3 rows affected (0.00 sec)

mysql> select min(a) from t4;
+--------+
| min(a) |
+--------+
|      0 |
+--------+
1 row in set (0.01 sec)

mysql> select max(a) from t4;
+--------+
| max(a) |
+--------+
|      1 |
+--------+
1 row in set (0.01 sec)

mysql> select sum(a) from t4;
+--------+
| sum(a) |
+--------+
|      1 |
+--------+
1 row in set (0.00 sec)

mysql> select avg(a) from t4;
+--------+
| avg(a) |
+--------+
|    0.5 |
+--------+
1 row in set (0.01 sec)

mysql>  select count(*) from t4;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.01 sec)

mysql>
