### ISSUE TITLE
[Bug]: the having sentence run happens panic

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#2853]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t1;
create table t1 (spID int,userID int,score smallint);
insert into t1 values (1,1,1);
insert into t1 values (2,2,2);
insert into t1 values (2,1,4);
insert into t1 values (3,3,3);
insert into t1 values (1,1,5);
insert into t1 values (4,6,10);
insert into t1 values (5,11,99);
select userID,count(score) from t1 group by userID having count(score)>1 order by userID;
ERROR 1105 (HY000): unknown error:Internal error: panic interface conversion: interface {} is []int32, not []int64: goroutine 4715 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x1029c1f20?, 0x1400326e420})
	/Users/wangjian/test/matrixone/pkg/common/moerr/error.go:77 +0x50
github.com/matrixorigin/matrixone/pkg/vm/overload.Run.func1()
	/Users/wangjian/test/matrixone/pkg/vm/overload/run.go:50 +0x38
panic({0x1029c1f20, 0x14003

the compare count(score) is seems to be userID, so the col type is not consistent to the type int64.

### Expected Behavior

mysql> select userID,count(score) from t1 group by userID having count(score)>1 order by userID;
+--------+--------------+
| userID | count(score) |
+--------+--------------+
|      1 |            3 |
+--------+--------------+
1 row in set (0.01 sec)

**Comment by nnsgmsone** [comment]
The issue is same as 2827, which I closed.
