### ISSUE TITLE
[Bug]: round function panic runtime error: index out of range [2147483649]

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#2854]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select round(1.5, -2147483649) from t1;
ERROR 1105 (HY000): unknown error:Internal error: panic runtime error: index out of range [2147483649] with length 20:

### Expected Behavior

mysql> select round(1.5, -2147483649) from t1;
+-------------------------+
| round(1.5, -2147483649) |
+-------------------------+
|                       0 |
|                       0 |
|                       0 |
|                       0 |
|                       0 |
+-------------------------+

### Additional information

When the round function is executed, call func roundfloat64avx2 (XS []float64, RS []float64, digits Int64). If there is no corresponding judgment on the digits value, the value is used as the index of the sliced scaletable, resulting in the problem of 'index out of range'

**Comment by aressu1985** [comment]
fixed

mysql> select round(1.5, -2147483649);
+-------------------------+
| round(1.5, -2147483649) |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set (0.01 sec)

mysql>
