### ISSUE TITLE
[Bug]: result column name is wrong

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2855]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

t3.i
2

### Expected Behavior

i
2

### Steps to Reproduce

```markdown
create table t1 (i int);
create table t2 (i int);
create table t3 (i int);
insert into t1 values(1),(2);
insert into t2 values(2),(3);
insert into t3 values (2),(4);
select t3.i from t1 join t2 on t1.i=t2.i join t3 on t2.i=t3.i;
```

**Comment by aressu1985** [comment]
fxied

mysql> select t3.i from t1 join t2 on t1.i=t2.i join t3 on t2.i=t3.i;
+------+
| i    |
+------+
|    2 |
|    2 |
|    2 |
|    2 |
+------+
4 rows in set (0.00 sec)
