### ISSUE TITLE
[Bug]: errors related to parsers

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#2859]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

many errors like:

Field xxx doesn't have a default value;

You have an error in your SQL syntax;

### Additional information

from github aoe pipeline, https://github.com/matrixorigin/matrixone/pull/2792

**Comment by iamlinjunhong** [comment]
Field xxx doesn't have a default value. This problem need tae to support.

**Comment by iamlinjunhong** [comment]
There are four types of cases reporting syntax errors:
1.Currently unsupported features. 
​	e.g.
        1) Multiple-Table Delete/Update Syntax
        2) alter statement
        3) prepare/execute
2. parser's bugs
3. Spelling errors in BVT
       e.g.
       1) varvarchar
       2) insert into t1 value("你好"), ("再见"), ("今天"); 
4. Inconsistent error information with MySQL.

Fix 2 and support part of 3 now. Error reporting information is not compatible with MySQL about 4.

**Comment by daviszhen** [comment]
it was fixed few day ago.
