### ISSUE TITLE
[Bug]: The first argument of the lpad function can not be a constant (lpad,rpad）

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#2863]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 The first argument of the lpad function can not be a constant (lpad,rpad）

### Additional information

from github aoe pipeline, https://github.com/matrixorigin/matrixone/pull/2792

**Comment by qingxinhome** [comment]
This bug has been fixed
