### ISSUE TITLE
[Bug]: the error msg do not output when missing the table name

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#2868]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select rpad("1", 5, 1) from t4;
ERROR 1105 (HY000): unknown error:the first argument of the lpad function can not be a constant

mysql> select rpad("1", 5, 1);
Empty set (0.00 sec)

### Expected Behavior

mysql> select rpad("1", 5, 1) from t4;
ERROR 1105 (HY000): unknown error:the first argument of the lpad function can not be a constant

mysql> select rpad("1", 5, 1);
ERROR 1105 (HY000): unknown error:the first argument of the lpad function can not be a constant

**Comment by nnsgmsone** [comment]
fixed by 2869
