### ISSUE TITLE
[Feature Request]: IF flow control function 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#2881]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
IF function is required for show cases. 

Ex:
        	select round(coalesce(sum (if(district_fid = 111,tpi,0)),0),2) as allCityTpi,
	            round(coalesce(sum (if(district_fid = 1,tpi,0)),0),2) as targetDistrictTpi,
	            max(case when district_fid = 111 then fname end) as fstFname,
	            max(case when district_fid =1 then fname end) as secFname from (
	            select t.fdate,t.period ,district_fid,b.fname,tpi from tpi_index.t_tpi_district_tpi t
	            left join tpi_index.t_base_district b on t.district_fid = b.fid
	            where t.district_fid in (111,1)
	            and t.fdate = 20211214
            	and t.period = 128
        	)
```

### Describe the feature you'd like

Follow the syntax of MySQL8.0.

[IF(expr1,expr2,expr3)](https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_if)

If expr1 is TRUE (expr1 <> 0 and expr1 IS NOT NULL), [IF()](https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_if) returns expr2. Otherwise, it returns expr3.

If only one of expr2 or expr3 is explicitly NULL, the result type of the [IF()](https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_if) function is the type of the non-NULL expression.

The default return type of [IF()](https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_if) (which may matter when it is stored into a temporary table) is calculated as follows:

If expr2 or expr3 produce a string, the result is a string.

If expr2 and expr3 are both strings, the result is case-sensitive if either string is case-sensitive.

If expr2 or expr3 produce a floating-point value, the result is a floating-point value.

If expr2 or expr3 produce an integer, the result is an integer.

mysql> SELECT IF(1>2,2,3);
        -> 3
mysql> SELECT IF(1<2,'yes','no');
        -> 'yes'

**Comment by m-schen** [comment]
support it.
and the format of IF is

if(boolean, <value_expression_1>, <value_expression_2>)
value_expression_1 should have the same type with value_expression_2, or just scalar null.

**Comment by dengn** [comment]
Feature implemented.
