### ISSUE TITLE
[Bug]: Incorrect aggregate function calculation result type

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#2889]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): MO-plan2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(
   a1 char(3) primary key,
   a2 smallint,
   a3 char(3),
   a4 real,
   a5 date,
);

insert into t1 values('AME',0,'SEA',0.100,null);
insert into t1 values('HBR',1,'SEA',0.085,null);
insert into t1 values('BOT',2,'SEA',0.085,null);
insert into t1 values('BMC',3,'SEA',0.085,null);

mysql> select (min(a4)+max(a4))/2 from t1;
ERROR 1105 (HY000): unknown error:Internal error: panic interface conversion: interface {} is *types.Bytes, not []float64

When this SQL executes ‘min (A4) +max (A4)’, the parameter type received by the plus operator operator is incorrect, resulting in an exception when retrieving the value. Specifically, in the plus operator, the type type of the vector corresponding to min (A4) should be int16, but the actual varchar type,

**Comment by daviszhen** [comment]
plan2 in the case is wrong

**Comment by aressu1985** [comment]
mo support the dtype real???

**Comment by ouyuanning** [comment]
this sql:
select (min(a4)+max(a4))/2 from t1;

MO will return  0.0925 .  just like MySQL

**Comment by aressu1985** [comment]
fixed 

mysql> create table t1(
    -> a1 char(3) primary key,
    -> a2 smallint,
    -> a3 char(3),
    -> a4 real,
    -> a5 date
    -> );
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> insert into t1 values('AME',0,'SEA',0.100,null);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values('HBR',1,'SEA',0.085,null);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t1 values('BOT',2,'SEA',0.085,null);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values('BMC',3,'SEA',0.085,null);
Query OK, 1 row affected (0.00 sec)

mysql> select (min(a4)+max(a4))/2 from t1;
+-------------------------+
| (min(a4) + max(a4)) / 2 |
+-------------------------+
|                  0.0925 |
+-------------------------+
1 row in set (0.01 sec)
