### ISSUE TITLE
[Bug]: Dropping table for multi tables is unsupported

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#2899]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> drop table t1,t2;
ERROR 1105 (HY000): unknown error:[42000]support drop one table now

**Comment by fengttt** [comment]
Not a bug, drop more than one table is not supported and we have no plan to support it ever.
