### ISSUE TITLE
[Bug]: plus is wrong

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2906]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

3
0
0

### Expected Behavior

2
4
5

### Steps to Reproduce

```markdown
CREATE TABLE t2 (S1 INT);
INSERT INTO t2 VALUES (2),(4),(5);
select t2.S1+ 1 from t2;
```

**Comment by broccoliSpicy** [comment]
fixed
