### ISSUE TITLE
[Bug]: the type int64 should not parse to float64 in the load function

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#2921]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

in the https://github.com/matrixorigin/matrixone/blob/main/pkg/frontend/load.go#L744. when the type is int64, I think we should not use [d, err := strconv.ParseFloat(field, 64)] to parse it. because the scope is different.

**Comment by daviszhen** [comment]
it is not a bug. @jianwan0214 can explain.
