### ISSUE TITLE
[Bug]: Accuracy Loss

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#2923]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Now we make all types like float32,float64,int8,int64,etc as the same type float64, and then we start our computation,but there exists accuracy loss. Here is the ut example:
       //there exists accuracy loss when transform float32 into float64, so the result is different
	tanIntAndFloat[float32](t, types.T_float32, 0.001, 0.0010000003808309655)
	tanIntAndFloat[float32](t, types.T_float32, -0.001, -0.0010000003808309655)

	tanIntAndFloat[float64](t, types.T_float64, 0.001, 0.0010000003333334668)
	tanIntAndFloat[float64](t, types.T_float64, -0.001, -0.0010000003333334668)
Maybe it does matter or not?

**Comment by m-schen** [comment]
It doesn't matter.
tan function always return an approximate result.
but for other functions, for example, the plus (+),  we can't do that.
so
1. only implement the tan(float64) is ok
2. only implement the plus(float64, float64) is wrong.
@JackTan25

**Comment by fengttt** [comment]
In general, issue/bug is not the right place to ask questions.  Please provide a real case, such as a repro.
