### ISSUE TITLE
[Bug]: Wrong order by result for `TIMESTAMP`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#2924]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): caba15a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="378" alt="image" src="https://user-images.githubusercontent.com/77312370/173180325-ccc3bb58-cc3f-4b68-9dba-a36e59d997d9.png">

### Steps to Reproduce

```markdown
1. create table t3(c1 TIMESTAMP NOT NULL);
2. INSERT INTO t3 VALUES('2000-01-01');
3. INSERT INTO t3 VALUES('1999-12-31');
4. select * from t3 order by c1;  // returns wrong result
5. select * from t3 order by c1; asc; // returns wrong result
```

**Comment by broccoliSpicy** [comment]
fixed

**Comment by aressu1985** [comment]
fixed

mysql>  create table t3(c1 TIMESTAMP NOT NULL);
Query OK, 0 rows affected (0.00 sec)

mysql>  INSERT INTO t3 VALUES('2000-01-01');
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t3 VALUES('1999-12-31');
Query OK, 1 row affected (0.00 sec)

mysql> select * from t3 order by c1; 
+----------------------------+
| c1                         |
+----------------------------+
| 1999-12-31 00:00:00.000000 |
| 2000-01-01 00:00:00.000000 |
+----------------------------+
2 rows in set (0.01 sec)

mysql> select * from t3 order by c1 asc;
+----------------------------+
| c1                         |
+----------------------------+
| 1999-12-31 00:00:00.000000 |
| 2000-01-01 00:00:00.000000 |
+----------------------------+
2 rows in set (0.00 sec)

mysql> select * from t3 order by c1 desc;
+----------------------------+
| c1                         |
+----------------------------+
| 2000-01-01 00:00:00.000000 |
| 1999-12-31 00:00:00.000000 |
+----------------------------+
2 rows in set (0.00 sec)

mysql>
