### ISSUE TITLE
[Bug]: select value occur error when value over int64 but in uint64

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#2925]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In plan2, aoe, we meet

mysql> select 18446744073709551500;
+----------------------+
| 18446744073709551500 |
+----------------------+
|                 -116 |
+----------------------+
1 row in set (0.00 sec)

### Expected Behavior

mysql> select 18446744073709551500;
+----------------------+
| 18446744073709551500 |
+----------------------+
| 18446744073709551500 |
+----------------------+
1 row in set (0.00 sec)

**Comment by aressu1985** [comment]
fixed

mysql> select 18446744073709551500;
+----------------------+
| 18446744073709551500 |
+----------------------+
| 18446744073709551500 |
+----------------------+
1 row in set (0.00 sec)

mysql> select 18446744073709551500;
+----------------------+
| 18446744073709551500 |
+----------------------+
| 18446744073709551500 |
+----------------------+
1 row in set (0.00 sec)

mysql>
