### ISSUE TITLE
[Bug]: corruption of logstore task worker accidentally

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#2930]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a5dc3ffa2332b9d5d11afb0c7584e1d8e076b270
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2022/06/11 12:04:42.160379 +0000","caller":"tables/blocktasks.go:115","msg":"ABLK | [1,9191] | CNT=[5] | Checkpointed | [Appendable]BLOCK[Op=Create][ID=1712][9111=>0]<Index[3054:1/3]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.160393 +0000","caller":"tables/blocktasks.go:89","msg":"ABlkCheckpointWAL | [Appendable]BLOCK[<0:1838-1714-1714-0-0>] | [0/9191]"}
{"level":"INFO","time":"2022/06/11 12:04:42.160409 +0000","caller":"wal/driver.go:57","msg":"Checkpoint Index: <Index[3072:0/1]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.160419 +0000","caller":"wal/driver.go:57","msg":"Checkpoint Index: <Index[3071:0/1]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.160428 +0000","caller":"wal/driver.go:57","msg":"Checkpoint Index: <Index[3070:0/1]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.160436 +0000","caller":"wal/driver.go:57","msg":"Checkpoint Index: <Index[3069:0/1]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.160445 +0000","caller":"wal/driver.go:57","msg":"Checkpoint Index: <Index[3068:2/3]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.160458 +0000","caller":"tables/blocktasks.go:115","msg":"ABLK | [1,9191] | CNT=[5] | Checkpointed | [Appendable]BLOCK[Op=Create][ID=1714][9141=>0]<Index[3068:1/3]>"}
{"level":"INFO","time":"2022/06/11 12:04:42.162007 +0000","caller":"catalog/catalog.go:839","msg":"PrepareCheckpoint: 1.532449ms"}
{"level":"INFO","time":"2022/06/11 12:04:42.163089 +0000","caller":"catalog/catalog.go:848","msg":"MakeLogEntry: 1.057772ms"}
panic: MaxSize is 67108864, but 415236170 is received

goroutine 183 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).onEntries(0xc000892c00, {0xc00027c000, 0x1ed, 0x0?})
    /mnt/vdb/sjw/tae/matrixone/pkg/vm/engine/tae/logstore/store/store.go:377 +0x414
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).flushLoop(0xc000892c00)
    /mnt/vdb/sjw/tae/matrixone/pkg/vm/engine/tae/logstore/store/store.go:157 +0x7b2
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).start
    /mnt/vdb/sjw/tae/matrixone/pkg/vm/engine/tae/logstore/store/store.go:118 +0x70

### Steps to Reproduce

```markdown
Crash occurs when running bvt in docker
```

**Comment by jiangxinmeng1** [comment]
payload size

**Comment by LeftHandCold** [comment]
0.6 uses logservice, there is no such bug
