### ISSUE TITLE
[Feature Request]: HAKeeper liveness protection for DN nodes

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#2965]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
In our new architecture, there can be many DN nodes, we need mechanism to
protect the liveness of such DN nodes. Failed DN nodes should be detected
and replaced to ensure high availability of the system.
```

### Describe the feature you'd like

A module in the HAKeeper that will detect and repair failed DN nodes.

This issue only tracks the progress of the module used for protecting the liveness of DN nodes. 
HAKeeper itself that will own/use the above described module is detailed & tracked in  #2759. 

### Describe implementation you've considered

It is a pretty straight forward implementation, the concerned module just need to detect failed
DN nodes based on provided timestamps (ticks) and issue commands to get them replaced.

**Comment by cnutshell** [comment]
- How to select target `DNStore` for expired `DNShard`?
`DNStore` would launch `DNShard`, and A `DNStore` could launch multiple `DNShard`.
As a result, selecting proper `DNStore`  could be in a very direct way that the store with least shards would be chosen.
`The least shards, The first` has been confirmed. In a batch, all new `DNShard` scheduled to the same `DNStore` is also allowed. Limited complexity, wonderful.

- How to discover expired `DNShard`?
From the gathered state of all `DNStore` in cluster, there could be multiple shard information with the same shard ID.
If only one shard information was valid or not expired, take this shard information as the newest;
If multiple shard information were valid or not expired, take the shard with large replica ID as the newest;
So as to multiple expired shard information.

**Comment by lni** [comment]
Implementation is in repo, briefly tested with integration tests. pretty good unit test coverage.
