### ISSUE TITLE
[Feature Request]: HAKeeper liveness protection for Log Service nodes. 

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#2966]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
In our new architecture, there can be many Log Service shards and each of
them will have multiple replicas, we need mechanism to protect the liveness 
of such Log Service nodes. Failed Log Service nodes should be detected
and replaced to ensure high availability of the system. This has to be done
with the above mentioned multiple Log Service shards/replicas in mind as 
they are backed by the Raft protocol, special cares have to be taken to 
respect all requirements of the Raft protocol.
```

### Describe the feature you'd like

A module in the HAKeeper that will detect and repair failed Log Service nodes and replicas.

This issue only tracks the progress of the module used for protecting the liveness of Log
Service nodes and replicas. HAKeeper itself that will own/use the above described module
is detailed & tracked in #2759.

### Describe implementation you've considered

The implementation will closely follow what we did in the old PD, although changes have 
to be made to reflect changes in the underlying Raft layer. 

More details of the implementation are documented in
https://github.com/matrixorigin/docs/tree/main/api/logservice 

### Documentation, Adoption, Use Case, Migration Strategy

```markdown
https://github.com/matrixorigin/docs/tree/main/api/logservice
```

**Comment by w-zr** [comment]
Some simple tests are now able to run. We need more tests for corner cases.

**Comment by w-zr** [comment]
Coding is completed.
We are now working on tests.
