### ISSUE TITLE
[Bug]: Column name is wrong with distinct

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#2969]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

(ti)
1
2
6
7
3
4
8

### Expected Behavior

ti
1
2
6
7
3
4
8

### Steps to Reproduce

```markdown
select distinct(ti) from (select * from t1) sub;
```

**Comment by aressu1985** [comment]
fixed

mysql> create table t1(ti int );
Query OK, 0 rows affected (0.00 sec)

mysql> select distinct(ti) from (select * from t1) sub;
Empty set (0.00 sec)

mysql> insert into t1 values(1);
Query OK, 1 row affected (0.00 sec)

mysql> select distinct(ti) from (select * from t1) sub;
+------+
| ti   |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql>
