### ISSUE TITLE
[Feature Request]: Integrate HAKeeper (new PD) with other MO components

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#2972]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
Integrate HAKeeper (new PD) with other MO components, including Log Service, DN and CN nodes. The outcome of this new ability should allow all relevant MO nodes to be monitored & replaced by the HAKeeper, we should also be able to bootstrap the initial cluster with the help of the HAKeeper.
```

### Describe the feature you'd like

A fully integrated HAKeeper which becomes a part of the MO.

**Comment by cnutshell** [comment]
Waiting for DN node related work to be done.

**Comment by lni** [comment]
Done.
