### ISSUE TITLE
[Bug]: Explain string format error.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3002]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

my:dump@127.0.0.1:6001/foo=> explain select * from t;
                                 QUERY PLAN
----------------------------------------------------------------------------
 Project (cost=%.2f..%.2f rows=%.2f ndv=%.2f rowsize=%.f)
   ->  Table Scan on foo.t (cost=%.2f..%.2f rows=%.2f ndv=%.2f rowsize=%.f)
(2 rows)

### Expected Behavior

Set %.2f to right value, like rows=2.

**Comment by qingxinhome** [comment]
Since the cost estimation result of plan2 is empty, the temporary output of cost estimation in explain is 0. The effect is as follows:
