### ISSUE TITLE
[Bug]: The perf of point_select by primary key is very poor and occupy very much cpu,men

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3009]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

use sysbench to test the perf of the point select by primary key ,but the result is very poor,
1 threads,1 table,1000 rows,
the mo is :
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/47846308/173736933-e98760aa-cd03-4e5e-abfd-3d4b0342b578.png">

mysql is :
<img width="948" alt="image" src="https://user-images.githubusercontent.com/47846308/173737041-fb9767db-ba30-49ee-9ae8-55c2a2dc82f6.png">

and as increasing the thread count,the cpu and mem usage increase sync:
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/47846308/173737494-c384fb42-4f3c-43a8-99c7-0870f68b6415.png">

**Comment by yingfeng** [comment]
It require several adjustments:

Memory management of tae reader. the memory is frequently allocated whenever a block is read. The default block size contains 160k rows which requires around 1MB memory for fixed length columns.  The block size could be configured statically right now instead of dynamically,  TP oriented tables needs smaller block size.  On the other hand, after the block is loaded into corresponding memory chunk, the memory is passed to computation layer and will not be released until the end of the query, additionally, the memory is managed by golang runtime and keeps growing without GC in time. Perhaps a cgo based memory allocator is required for tae reader

**Comment by XuPeng-SH** [comment]
Point select should be cn-relevant behavior after v0.6.

**Comment by nnsgmsone** [comment]
现在性能已经好一些了，不过这是个需要持续优化的课题。。先从zonemap什么的开始

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
转成feature #379把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #379把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #379把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #379把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #379把 @aressu1985

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
can test

**Comment by nnsgmsone** [comment]
continue

**Comment by nnsgmsone** [comment]
Found that prepare did not work well and continued to track

**Comment by nnsgmsone** [comment]
now it is ok
