### ISSUE TITLE
[Bug]: Type conversions that should not occur in  small number

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#3071]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[42000]parameter types of cast function do not match

### Steps to Reproduce

```markdown
select IF(1=0, 1, 2/1);
```

### Additional information

They are all very small numbers, and in theory they should all resolve to int64, so why is there a type conversion? This doesn't make sense.

**Comment by m-schen** [comment]
the result of 2 / 1 is float64. and 2 div 1 is int64. @nnsgmsone 
I think it's normal to have a type conversion.

**Comment by m-schen** [comment]
mysql> select IF(1=0, 1, 2/1);
+---------------------+
| if(1 = 0, 1, 2 / 1) |
+---------------------+
|                   2 |
+---------------------+

**Comment by ouyuanning** [comment]
is that will be ok? if we do the cast in plan for the constant expr?

**Comment by ouyuanning** [comment]
After discussion with @nnsgmsone .   decide to close this issue
