### ISSUE TITLE
[Bug]: result is not consistent on the x86 and mac from some querys

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3078]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

X86:
mysql> select cast(10000002383263201056 as unsigned) mod 50 as result;
+--------+
| result |
+--------+
|      0 |
+--------+
1 row in set (0.00 sec)

MAC:
mysql> select cast(10000002383263201056 as unsigned) mod 50 as result;
+--------+
| result |
+--------+
|   -320 |
+--------+
1 row in set (0.01 sec

**Comment by m-schen** [comment]
the precision of golang's float is different in arm64 and amd64

**Comment by m-schen** [comment]
mysql> select cast(10000002383263201056 as unsigned) mod 50 as result;

ERROR 1105 (HY000): Can't cast '10000002383263201056' from BIGINT UNSIGNED type to BIGINT type. Reason: overflow

Now, the process is that:

10000002383263201056 cast as uint64
50 is recognized as int64
and follow our implicit type convert rule
uint64 mod int64    will convert to     int64 mod int64
so we return the overflow error.

**Comment by m-schen** [comment]
> the precision of golang's float is different in arm64 and amd64

This is an error in judgment, in our old code, uint64 mod int64 will convert to float64 mod float64

but now is int64 mod int64
