### ISSUE TITLE
[Refactoring]: utility.go and utils

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3092]
### Is there an existing issue for the refactoring request?

- [X] I have checked the existing issues.

### Is your refactoring request related to a problem?

```markdown
There are both utility.go and a dir named utils in hakeeper, both contain roughly the same code.
```

### Describe the solution you'd like

Get the above mentioned duplicated code cleaned up. It seems to me that a utils.go will be enough.

**Comment by cnutshell** [comment]
Issue resolved.
