### ISSUE TITLE
[Feature Request]: Distributed transaction client

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#3115]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```markdown
The Distributed transaction client runs on the CN node and provides Read/Write/Commit/Rollback operations to compute distributed transactions and is responsible for message interaction with the DN's transaction server.
```

### Describe the feature you'd like

Provide the correct client-side implementation of Read/Write/Commit/Rollback for transactions

**Comment by lni** [comment]
docs -
https://github.com/matrixorigin/docs/tree/main/design/transaction2

**Comment by zhangxu19830126** [comment]
Initial implementation is complete and tests are being written
