### ISSUE TITLE
[Bug]: COT(0) needs to be infinity number

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3133]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 9cc17cef85daa97a6ef533796ce80357bd5c852c
- Hardware parameters: Mac M1 ARM 16GB memory
- OS type:
- Others:
```

### Actual Behavior

cot(0)
1.6331239353195392E16

### Expected Behavior

In MySQL, cot(0) will give an error:

select cot(0);
Data truncation: DOUBLE value is out of range in 'cot(0)'

**Comment by fengttt** [comment]
Fixed, please close.

**Comment by aressu1985** [comment]
fixed
