### ISSUE TITLE
[Bug]: Wrong error message for DATE literal 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3139]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9cc17cef85daa97a6ef533796ce80357bd5c852c
- Hardware parameters: MAC M1 ARM 16GB
- OS type:OSX
- Others:
```

### Actual Behavior

Data truncation: Function expression in INSERT statement value list will be supported in future version. for column 'a5' at row 0

### Expected Behavior

This is not a function, it's a DATE and TIME literal.
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html

### Steps to Reproduce

```markdown
create table t1(a1 char(3) primary key,a2 smallint,a3 char(3),a4 real,a5 date);
insert into t1 values('AME',0,'SEA',0.100,date'1942-02-19');
```

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by JinHai-CN** [comment]
"date'1942-02-19'" in insert statement will be considered as function date('1942-02-19').

**Comment by dengn** [comment]
OK for resolving this in 0.6.

**Comment by aressu1985** [comment]
mysql> create table t1(a1 char(3) primary key,a2 smallint,a3 char(3),a4 real,a5 date);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values('AME',0,'SEA',0.100,date'1942-02-19');
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+------+------+------+------+------------+
| a1   | a2   | a3   | a4   | a5         |
+------+------+------+------+------------+
| AME  |    0 | SEA  |  0.1 | 1942-02-19 |
+------+------+------+------+------------+
1 row in set (0.00 sec)

mysql>
