### ISSUE TITLE
[Bug]: column of result is incorrect in the result of cast

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3142]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast(9223372036854775808 as unsigned)+1;
cast(9223372036854775808 as **unsigned unsigned**) + 1
9.223372036854776E18

### Expected Behavior

select cast(9223372036854775808 as unsigned)+1;
cast(9223372036854775808 as unsigned) + 1
9.223372036854776E18

**Comment by m-schen** [comment]
it looks like the same between actual and expected?

**Comment by ouyuanning** [comment]
this sql is #3345 in test case file

**Comment by aressu1985** [comment]
l> 
mysql> select cast(9223372036854775808 as unsigned)+1;
ERROR 1105 (HY000): overflow from bigint unsigned to bigint
