### ISSUE TITLE
[Bug]: DATE function with datetime bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3143]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9cc17cef85daa97a6ef533796ce80357bd5c852c
- Hardware parameters: MAC M1 ARM 16GB
- OS type:OSX
- Others:
```

### Actual Behavior

Incorrect date value

### Expected Behavior

DATE("2017-06-15 09:34:21")
2017-06-15

### Steps to Reproduce

```markdown
SELECT DATE("2017-06-15 09:34:21");
```

**Comment by aressu1985** [comment]
fixed

mysql> SELECT DATE("2017-06-15 09:34:21");
+---------------------------+
| date(2017-06-15 09:34:21) |
+---------------------------+
| 2017-06-15                |
+---------------------------+
1 row in set (0.00 sec)
