### ISSUE TITLE
[Enhancement]: adddate is a synonym of date_add 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3144]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
[SQL STATEMENT]: SELECT ADDDATE(DATE'2021-01-01', INTERVAL 1 DAY);
[EXPECT RESULT]:
ADDDATE(DATE'2021-01-01', INTERVAL 1 DAY)
2021-01-02
[ACTUAL RESULT]:
Function or operator 'adddate' will be implemented in future version.
```

### Why is this needed ?

ADDDATE is just a synonym of date_add, easy to implement. Check out https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_adddate

**Comment by aressu1985** [comment]
fixed

Database changed
mysql> SELECT ADDDATE(DATE'2021-01-01', INTERVAL 1 DAY);
+---------------------------------------------+
| adddate(date(2021-01-01), interval(1, day)) |
+---------------------------------------------+
| 2021-01-02                                  |
+---------------------------------------------+
1 row in set (0.00 sec)
