### ISSUE TITLE
[Bug]: CREATE TABLE WITH DATA TYPE AS COLUMN NAME

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3147]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9cc17cef85daa97a6ef533796ce80357bd5c852c
- Hardware parameters: MAC M1 ARM 16GB
- OS type:OSX
- Others:
```

### Actual Behavior

Creating table with column name of data type will generate error.

You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 46 near 'timestamp'; 

### Expected Behavior

In MySQL and PG, these DDLs are legal.

### Steps to Reproduce

```markdown
CREATE TABLE t1 (datetime datetime, timestamp timestamp, date date);
```

**Comment by iamlinjunhong** [comment]
fixed
