### ISSUE TITLE
[Bug]: microseconds disappeared 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3149]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9cc17cef85daa97a6ef533796ce80357bd5c852c
- Hardware parameters: MAC M1 ARM 16GB
- OS type:OSX
- Others:
```

### Actual Behavior

date_sub(a, interval(1 minute))
1000-01-01 00:59:00
1000-01-01 00:59:00
2000-12-31 23:59:00
2000-12-31 23:59:00
2001-01-01 00:59:00
2001-01-01 00:59:00

Microseconds disappeared.

### Expected Behavior

DATE_SUB(a, INTERVAL 1 MINUTE)
1000-01-01 00:59:00
1000-01-01 00:59:00.000001000
2000-12-31 23:59:00
2000-12-31 23:59:00.000001000
2001-01-01 00:59:00
2001-01-01 00:59:00.000001000

### Steps to Reproduce

```markdown
CREATE TABLE t1 (a DATETIME(6));
INSERT INTO t1 VALUES ('1000-01-01 01:00:00.000000');
INSERT INTO t1 VALUES ('1000-01-01 01:00:00.000001');
INSERT INTO t1 VALUES ('2001-01-01 00:00:00.000000');
INSERT INTO t1 VALUES ('2001-01-01 00:00:00.000001');
INSERT INTO t1 VALUES ('2001-01-01 01:00:00.000000');
INSERT INTO t1 VALUES ('2001-01-01 01:00:00.000001');
SELECT DATE_SUB(a, INTERVAL 1 MINUTE) FROM t1 ORDER BY a;
```

**Comment by aressu1985** [comment]
fixed

mysql> SELECT DATE_SUB(a, INTERVAL 1 MINUTE) FROM t1 ORDER BY a;
+----------------------------------+
| date_sub(a, interval(1, minute)) |
+----------------------------------+
| 1000-01-01 00:59:00.000000       |
| 1000-01-01 00:59:00.000001       |
| 2000-12-31 23:59:00.000000       |
| 2000-12-31 23:59:00.000001       |
| 2001-01-01 00:59:00.000000       |
| 2001-01-01 00:59:00.000001       |
+----------------------------------+
6 rows in set (0.00 sec)
