### ISSUE TITLE
[Bug]: long int is taken as varchar

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3155]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9cc17cef85daa97a6ef533796ce80357bd5c852c
- Hardware parameters: MAC M1 ARM 16GB
- OS type:OSX
- Others:
```

### Actual Behavior

Operator 'unary_minus' with parameters [VARCHAR] will be implemented in future version.

### Expected Behavior

lpad('hello', -18446744073709551616, '1')

### Steps to Reproduce

```markdown
select lpad('hello', -18446744073709551616, '1');
```

**Comment by JinHai-CN** [comment]
mysql> select lpad('hello', -18446744073709551616, '1');
ERROR 1105 (HY000): Operator 'cast' with parameters [DECIMAL128 BIGINT] will be implemented in future version.
