### ISSUE TITLE
[Bug]: multiple substring function result bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3169]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e1319c52cf87b17a98008ae0dda79b72237d9ed1
- Hardware parameters:Mac M1 ARM 16GB Memory
- OS type:OSX
- Others:
```

### Actual Behavior

substr(c1, -2147483647, 2147483648)
111
222

substring(hello, 1, 18446744073709551615)
hell

substring(hello, -18446744073709551615, -18446744073709551615)
h

### Expected Behavior

substr(c1, -2147483647, 2147483648) 
empty set

substring('hello', 1, 18446744073709551615)
hello

substring(hello, -18446744073709551615, -18446744073709551615)
empty set

### Steps to Reproduce

```markdown
CREATE TABLE t1(c1 CHAR(30));
INSERT INTO t1 VALUES('111'),('222');
SELECT DISTINCT substr(c1, -2147483647, 2147483648) FROM t1;


select substring('hello', 1, 18446744073709551615);

select substring('hello', -18446744073709551615, -18446744073709551615);
```

**Comment by dengn** [comment]
#3169 tag still remains in the test case.

**Comment by jianwan0214** [comment]
select substring('hello', -18446744073709551615, -18446744073709551615);
this error is tracked by issue #3155.
