### ISSUE TITLE
[Bug]: Column name with table name is considered different from column name

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3176]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e1319c52cf87b17a98008ae0dda79b72237d9ed1
- Hardware parameters:Mac M1 ARM 16GB Memory
- OS type:OSX
- Others:
```

### Actual Behavior

column "t1.b" must appear in the GROUP BY clause or be used in an aggregate function

### Expected Behavior

b
2017-06-15 09:34:21
2019-06-25 10:12:21
2019-06-25 18:20:49

### Steps to Reproduce

```markdown
drop table if exists t1;
create table t1(a INT,  b datetime);
insert into t1 values(1, "2017-06-15 09:34:21"),(1, "2019-06-25 10:12:21"),(2, "2019-06-25 18:20:49"),(3, "2019-06-25 18:20:49");
select b from t1 group by b having (date_add(t1.b, INTERVAL 1 day)-date_add(t1.b, INTERVAL 1 hour))>10;
drop table t1;
```

**Comment by aunjgr** [comment]
fixed by #3205

**Comment by fengttt** [comment]
Still has a tag in test.
```
ftian@DESKTOP-16FCU43:~/m/matrixone/test$ grep -r 3176 .| grep bvt
./cases/function/func_datetime_date_add.test:-- @bvt:issue#3176
```

Please check, update, and let testing team close.

**Comment by aunjgr** [comment]
Now the errmsg becomes

> Operator '-' with parameters [DATETIME DATETIME] will be implemented in future version.

**Comment by aressu1985** [comment]
#3176 has been fixed
