### ISSUE TITLE
[Bug]: the wrong resolve of the big integer 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3178]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a557ce33b49b007540c917b87ee1e1368d76ce27
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

abs(cast(-2 as unsigned))	abs(18446744073709551614)	abs(-2)
18446744073709551614	18446744073709551614	2
[ACTUAL RESULT]:
abs(cast(-2 as unsigned unsigned))	abs(18446744073709551614)	abs(-2)
18446744073709551614	2	2

select abs(9999999999999999999999);
select abs(-9999999999999999999999);
select abs(cast(-2 as unsigned)), abs(18446744073709551614), abs(-2);
select ceiling(cast(-2 as unsigned)), ceiling(18446744073709551614), ceiling(-2);
select floor(cast(-2 as unsigned)), floor(18446744073709551614), floor(-2);
SELECT floor(18446744073709551616);
SELECT floor(floor(18446744073709551616));
SELECT floor(floor(floor(18446744073709551616)));
select floor(9999999999999999999999);

select -(0-3),round(-(0-3)), round(9999999999999999999);
select -(0-3),round(-(0-3)), round(9999999999999999999);
select round(cast(-2 as unsigned), 1), round(18446744073709551614, 1), round(-2, 1);
select round(cast(-2 as unsigned), 1), round(18446744073709551614, 1), round(-2, 1);
select round(4, cast(-2 as unsigned)), round(4, 18446744073709551614), round(4, -2);

**Comment by ouyuanning** [comment]
-- @bvt:issue#3393
select abs(9999999999999999999999);
select abs(-9999999999999999999999);

**Comment by aressu1985** [comment]
punt to 0.6
