### ISSUE TITLE
[Bug]: the mismatch between actual results and expected results of functions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3179]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a557ce33b49b007540c917b87ee1e1368d76ce27
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[EXPECT RESULT]:
floor(ceil(12345678901234567890))
12345678901234567890
[ACTUAL RESULT]:
floor(ceil(12345678901234567890))
-6101065172474983726

SELECT any_value(floor(0.5413))-any_value(ceiling(0.553));
select * from t;

[SCRIPT   FILE]: cases/function/func_math_ceil.test
[ROW    NUMBER]: 23
[SQL STATEMENT]: SELECT * FROM t;

[SCRIPT   FILE]: cases/function/func_math_ceil.test
[ROW    NUMBER]: 28
[SQL STATEMENT]: SELECT * FROM t;

[SCRIPT   FILE]: cases/function/func_math_ceil.test
[ROW    NUMBER]: 33
[SQL STATEMENT]: SELECT * FROM t;

[SCRIPT   FILE]: cases/function/func_math_ceil.test
[ROW    NUMBER]: 38
[SQL STATEMENT]: SELECT * FROM t;

SELECT floor(ceil(12345678901234567890));

SELECT any_value(floor(0.5413));
SELECT any_value(floor(0.5413))-any_value(ceiling(0.553));
SELECT floor(ceil(12345678901234567890));
select floor(9.999999999999999999999);

select cot(a*pi()/180) as cota,cot(b*pi()/180) cotb from t1;
select cot(a*pi()/180)*cot(b*pi()/180) as cotab,cot(cot(a*pi()/180)) as c from t1;
select b from t1 where cot(a*pi()/180)<=cot(b*pi()/180)  order by a;
select tan(a*pi()/180) as tana,tan(b*pi()/180) tanb from t1;
select tan(a*pi()/180)*tan(b*pi()/180) as tanab,tan(tan(a*pi()/180)) as c from t1;
select round(-5000111000111000155,-1);
select round(15000111000111000155,-1);

select round(1.5, -4294967296), round(1.5, 4294967296);
select round(1.5, -9223372036854775808), round(1.5, 9223372036854775808);
select round(999999999.0, -9);
select round(999999999999999999.0, -18);
select round(10000000000000000000, -19);
select round(1e1,308);
select round(1e1, 2147483648);
select round(1.1e1, 4294967295);
select round(1.12e1, 4294967296);
select round(1.5, 2147483640);
select round(1.5, -2147483649), round(1.5, 2147483648);
select round(1.5, -4294967296), round(1.5, 4294967296);
select round(1.5, -9223372036854775808), round(1.5, 9223372036854775808);
select round(1.5, 18446744073709551615);
select round(18446744073709551614, -1);
SELECT a, ROUND(sin(100)*10) r2, SUM(1) r1 FROM t1 GROUP BY a;
select tan(a*pi()/180) as tana,tan(b*pi()/180) tanb from t1;
select tan(a*pi()/180)*tan(b*pi()/180) as tanab,tan(tan(a*pi()/180)) as c from t1;

case1:
[SQL STATEMENT]: SELECT a, ROUND(sin(100)*10) r2, SUM(1) r1 FROM t1 GROUP BY a;
[EXPECT RESULT]: [42803]column "r1" must appear in the GROUP BY clause or be used in an aggregate function

SELECT YEAR('2015-09.30') as year;
SELECT YEAR('2015-09.30 12') as year;
SELECT YEAR("2015-09-10")- YEAR("2016-04-24");
SELECT YEAR("2015-09-10")*YEAR("2016-04-24");
select count(*) from t1 where YEAR(col1) IS not NULL;

select sum(month(d)),sum(month(d)) from t1;
SELECT MONTH('2015-09.30') as MONTH;
SELECT MONTH('2015-09.30 12') as MONTH;

SELECT weekday(date('2007-02-03 03:42:24'));
[SQL STATEMENT]: SELECT dayofyear(date('2007-02-03 03:42:24'));

[SQL STATEMENT]: select date(date_sub("1998-01-01 00:00:00",INTERVAL 1 DAY));

[SQL STATEMENT]: select f1 from t1 where date(f1) between cast("2006-1-1" as date) and cast("2006.1.1" as date);

[SQL STATEMENT]: select f1 from t1 where cast("2006-1-1" as date) between date(f1) and date(f3);

[SQL STATEMENT]: SELECT DATE("2112123");

[SQL STATEMENT]: SELECT DATE("2017-06-15 09:34:21");

[SQL STATEMENT]: SELECT DATE("The date is 2017-06-15");

[SQL STATEMENT]: SELECT DATE('2008-05-17 11:31:31') as required_DATE;

[SQL STATEMENT]: select date("1997-12-31 23:59:59.000001");

[SQL STATEMENT]: select date("1997-13-31 23:59:59.000001");

[SQL STATEMENT]: SELECT date("2022-12-22 02:34:23") = date("2022-12-22 03:34:23");

[SQL STATEMENT]: SELECT dayofyear(date('2007-02-03 03:42:24'));

[SQL STATEMENT]: SELECT weekday(date('2007-02-03 03:42:24'));

[SQL STATEMENT]: SELECT CAST(to_date('nope','%d-%m-%Y') AS YEAR);

[SQL STATEMENT]: INSERT INTO t1 select( to_date('2019-12-31', '%Y-%m-%d') );

[SQL STATEMENT]: INSERT INTO t2 select( to_date('09:22', '%H:%i') );

[SQL STATEMENT]: INSERT INTO t2 select( to_date('09:22:23.33', '%H:%i:%s.%f') );

[SQL STATEMENT]: SELECT FROM_UNIXTIME(32536771199);

[SQL STATEMENT]: SELECT FROM_UNIXTIME(32536771199);

[SQL STATEMENT]: SELECT FROM_UNIXTIME(32536771199);

[SQL STATEMENT]: SELECT FROM_UNIXTIME(32536771199);

[SQL STATEMENT]: SELECT FROM_UNIXTIME(32536771199);

[SQL STATEMENT]: select from_unixtime(2147483647);

[SQL STATEMENT]: select from_unixtime(2147483648);

[SQL STATEMENT]: select from_unixtime(0);

[SQL STATEMENT]: select unix_timestamp('2039-01-20 01:00:00');

[SQL STATEMENT]: select unix_timestamp('2038-02-10 01:00:00');

[SQL STATEMENT]: select unix_timestamp('2038-01-20 01:00:00');

[SQL STATEMENT]: select unix_timestamp('2038-01-17 12:00:00');

[SQL STATEMENT]: select unix_timestamp('1970-01-01 03:00:01');

[SQL STATEMENT]: select unix_timestamp('2038-01-19 07:14:07');

[SQL STATEMENT]: select unix_timestamp('1970-01-01 01:00:00'),
unix_timestamp('1970-01-01 01:00:01'),
unix_timestamp('2038-01-19 04:14:07'),
unix_timestamp('2038-01-19 04:14:08');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-18 23:59:59');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-19 00:00:00');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-19 00:00:00');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-19 00:59:59');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-19 01:00:00');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-18 22:59:59');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-18 23:59:59');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-18 15:59:59');

[SQL STATEMENT]: SELECT UNIX_TIMESTAMP('3001-01-18 16:00:00');

[SQL STATEMENT]: select unix_timestamp(utc_timestamp());

case1
[SQL STATEMENT]: select char_length('\n\t\r\b\0\_\%\\');

case2
[SQL STATEMENT]: SELECT t1.t1_fld1, t2.t2_fld1, t3.t3_fld1 FROM t1 JOIN t2 JOIN t3 ON (length(t1.b) = length(t2.b));

case3
[SQL STATEMENT]: select length('\n\t\r\b\0\_\%\\');

case4
[SQL STATEMENT]: select length(space(1024*1024)) as a;

case5
[SQL STATEMENT]: select length(a) from t1;

case6
[SQL STATEMENT]: SELECT length(space(9223372036854775809));

case7
[SQL STATEMENT]: select lpad('hello', -18446744073709551615, '1');

case8
[SQL STATEMENT]: select rpad('hello', -18446744073709551615, '1');

case9
[SQL STATEMENT]: select rpad('hello', 18446744073709551616, '1');

case10
[SQL STATEMENT]: select rpad('hello', 18446744073709551617, '1');

case11
[SQL STATEMENT]: select rpad(c,'1','*') from t1;

case12
[SQL STATEMENT]: select rpad(c,'1','*') from t1;

case1:
[SQL STATEMENT]: SELECT 1 FROM t WHERE ltrim(a & NULL);

case2:
[SQL STATEMENT]: select ltrim(c),ltrim(vc) from t1;

case3
[SQL STATEMENT]: select cast(rtrim('  20.06 ') as decimal(19,2));

case4
[SQL STATEMENT]: SELECT 1 FROM t WHERE rtrim(a & NULL);

case5
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ１`;

case6
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ２`;

case7
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ３`;

case8
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ４`;

case9
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ５`;

case10
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ６`;

case11
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ７`;

case12
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ８`;

case13
[SQL STATEMENT]: SELECT RTRIM(`Ｃ１`) from `Ｔ９`;

case14
[SQL STATEMENT]: select substring(c,-11),substr(vc,-13) from t1 where id = 6 ;

case15 
[SQL STATEMENT]: select substring(c,1,-1),substr(vc,3,-2) from t1 where id = 4 ;

case16
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ１`;

case17
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ２`;

case18
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ３`;

case19
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ４`;

case20
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ５`;

case21
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ６`;

case22
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ７`;

case23
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ８`;

case24
[SQL STATEMENT]: SELECT REVERSE(`Ｃ１`) FROM `Ｔ９`;

case25
[SQL STATEMENT]: select length(space(1024*1024)) as a;

case26
[SQL STATEMENT]: select space(18446744073709551615);

case27
[SQL STATEMENT]: SELECT space(9223372036854775808);

case28
[SQL STATEMENT]: SELECT length(space(9223372036854775809));

case29
[SQL STATEMENT]: SELECT space(i) FROM t;

case30
[SQL STATEMENT]: select substring('hello', 2, -1);

case31
[SQL STATEMENT]: select substring('hello', -18446744073709551615, 1);

case32
[SQL STATEMENT]: select substring('hello', 18446744073709551615, 1);

case33
[SQL STATEMENT]: select substring('hello', 1, -1);

case34
[SQL STATEMENT]: select substring('hello', 1, -18446744073709551615);

case35
[SQL STATEMENT]: select substring('hello', 1, 18446744073709551615);

case36
[SQL STATEMENT]: select substring('hello', -1, -1);

case37
[SQL STATEMENT]: select substring('hello', -18446744073709551615, -18446744073709551615);

casae38
[SQL STATEMENT]: select substring('hello', 18446744073709551615, 18446744073709551615);

case39
[SQL STATEMENT]: select *,substring(b,1),substring(b,-1),substring(b,-2),substring(b,-3),substring(b,-4),substring(b,-5) from t1;

case40
[SQL STATEMENT]: select * from (select *,substring(b,1),substring(b,-1),substring(b,-2),substring(b,-3),substring(b,-4),substring(b,-5) from t1) t;

case41
[SQL STATEMENT]: select substring(a, 1, 1) from t1;

case42
[SQL STATEMENT]: select substring(c,-11),substr(vc,-13) from t1 where id = 6 ;

case43
[SQL STATEMENT]: select substring(c,2,-1),substr(vc,3,-1) from t1 where id = 4 ;

case44
[SQL STATEMENT]: select substring(c,1,-1),substr(vc,3,-2) from t1 where id = 4 ;

case45
[SQL STATEMENT]: SELECT a, OCT(BIT_AND(b)), OCT(BIT_OR(b)), OCT(BIT_XOR(b)) FROM t1 GROUP BY a;

case46
[SQL STATEMENT]: SELECT OCT(BIT_AND(b)), OCT(BIT_OR(b)), OCT(BIT_XOR(b)) FROM t1;

case47
[SQL STATEMENT]: SELECT a, OCT(BIT_AND(b)), OCT(BIT_OR(b)), OCT(BIT_XOR(b)) FROM t1 GROUP BY a;

case48
[SQL STATEMENT]: SELECT a, OCT(BIT_AND(b)), OCT(BIT_OR(b)), OCT(BIT_XOR(b)) FROM t1 GROUP BY a;

case49
[SQL STATEMENT]: SELECT a, OCT(BIT_AND(b)), OCT(BIT_OR(b)), OCT(BIT_XOR(b)) FROM t1 GROUP BY a;

### Steps to Reproduce

```markdown
Download bvt report
```

**Comment by daviszhen** [comment]
add functions related to time

**Comment by JackTan25** [comment]
the bugs with func year  have solved (just think about the result dismatch errors, that's said the expect not equals to result)

**Comment by JackTan25** [comment]
Now our func date responds when error exists, I think this below should be ok, it's just a cast error.
[SQL STATEMENT]: SELECT DATE("The date is 2017-06-15");
[EXPECT RESULT]:
DATE("The date is 2017-06-15")
null
[ACTUAL RESULT]:
Incorrect date value

**Comment by JackTan25** [comment]
Bug with sum, it will take the NULL value as 1 into account, need to fix the sum.
[ERROR]
[SCRIPT   FILE]: cases/function/func_date.sql
[ROW    NUMBER]: 48
[SQL STATEMENT]: select sum(month(d)),sum(month(d)) from t1;
[EXPECT RESULT]:
sum(month(d))	sum(month(d))
83	83
[ACTUAL RESULT]:
sum(month(d))	sum(month(d))
84	84

**Comment by JackTan25** [comment]
mysql> SELECT DATE("2112123");
ERROR 1105 (HY000): Incorrect date value

this one I think it's ok, because we support yyyymmdd,is't 8 digits

**Comment by JackTan25** [comment]
[ERROR]
[SCRIPT   FILE]: cases/function/func_datetime_date.test
[ROW    NUMBER]: 43
[SQL STATEMENT]: select date("1997-13-31 23:59:59.000001");
[EXPECT RESULT]:
date("1997-13-31 23:59:59.000001")
null
[ACTUAL RESULT]:
Incorrect date value

I think this is ok

**Comment by JackTan25** [comment]
After I fix bugs in Date(),here is the result of the sql statement:
mysql>  SELECT date("2022-12-22 02:34:23") = date("2022-12-22 03:34:23");
+-------------------------------------------------------+
| date(2022-12-22 02:34:23) = date(2022-12-22 03:34:23) |
+-------------------------------------------------------+
| true                                                  |
+-------------------------------------------------------+
1 row in set (0.00 sec)

And before in the bvt :
[ERROR]
[SCRIPT   FILE]: cases/function/func_datetime_date.test
[ROW    NUMBER]: 486
[SQL STATEMENT]: SELECT date("2022-12-22 02:34:23") = date("2022-12-22 03:34:23");
[EXPECT RESULT]:
date("2022-12-22 02:34:23") = date("2022-12-22 03:34:23")
1
[ACTUAL RESULT]:
Incorrect date value

I think it's ok

**Comment by daviszhen** [comment]
they has been tracked by some other concrete issues tagged by bvt
