### ISSUE TITLE
[Bug]: the numbers are resolved as varchar

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3180]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a557ce33b49b007540c917b87ee1e1368d76ce27
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Cases:

[ERROR]
[SCRIPT   FILE]: cases/function/func_math_floor.test
[ROW    NUMBER]: 10
[SQL STATEMENT]: SELECT floor(floor(18446744073709551616));
[EXPECT RESULT]:
floor(floor(18446744073709551616))
18446744073709551616
[ACTUAL RESULT]:
Function 'floor' with parameters [VARCHAR] will be implemented in future version.

SELECT SINH(0.745e5);
SELECT SINH(13413);
SELECT SINH(-3114);
select distinct a from t1;

[SQL STATEMENT]: SELECT FROM_UNIXTIME(99999999999999999999999999999999999999999999999999999999999999999);

### Steps to Reproduce

```markdown
download bvt report
```

**Comment by iamlinjunhong** [comment]
fixed
