### ISSUE TITLE
[Bug]: the mismatch between actual error messages and expected ones

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3182]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a557ce33b49b007540c917b87ee1e1368d76ce27
- Hardware parameters:
- OS 

- [ ] type:

- Others:
```

### Cases need to updated by tester.

- [ ] `select abs(10/0);`

- [ ] `SELECT ABS(i) AS a FROM t GROUP BY a ORDER BY a + 1;`

- [ ] `select cot(a*pi()/180) as cota,cot(b*pi()/180) cotb from t1`;

- [ ] `select cot(a*pi()/180)*cot(b*pi()/180) as cotab,cot(cot(a*pi()/180)) as c from t1;`

- [ ] `select b from t1 where cot(a*pi()/180)<=cot(b*pi()/180)  order by a;`

- [ ] `select cot(d),cot(fl) from t1;`

### Cases already fixed.

- [X] SELECT a, ROUND(sin(100)*10) r2, SUM(1) r1 FROM t1 GROUP BY a HAVING r1>0 AND r2<0 AND r2 > -10;

- [X] SELECT a, ROUND(sin(100)*10) r2, SUM(1) r1 FROM t1 GROUP BY a HAVING r1>=1 AND (SELECT r2>-100 AND r2 < 0 FROM t1 AS t2 LIMIT 1);

- [X] SELECT a, ROUND(sin(100)*10) r2, SUM(1) r1 FROM t1 WHERE a = 1 GROUP BY a HAVING r1>1 AND r2<=2;

- [X] SELECT a, ROUND(sin(100)*10) r2, SUM(1) r1 FROM t1 WHERE a = 1 GROUP BY a HAVING r1>1 AND r2<=2 ORDER BY a+r2+r1;

- [X] SELECT ROUND(sin(100)*10) r2 FROM t1 GROUP BY r2;

- [X] SELECT i, ROUND(SUM(d1), 2) AS a, ROUND(SUM(d2), 2) AS b FROM t1 GROUP BY i;

- [X] SELECT t1.c0, t2.c0 from t1 join t2 on abs(t1.c0) = abs(t2.c0) having abs(t1.c0)>100;

### Cases need to be fixed.

- [ ] **insert into t1 (a) select (FLOOR(0.13 * 100));**

- [ ] **SELECT DATE(FLOOR(20110512154559.616));**

- [ ] **select cot(0);**

- [ ] **SELECT MONTH(201509) as MONTH;**

- [ ] **SELECT MONTH(1340124) as MONTH;**

- [ ] **SELECT MONTH(0.45133) as MONTH;**

- [ ] **SELECT MONTH(10) as MONTH;**

- [ ] **SELECT MONTH(1=1) as MONTH;**

- [ ] **select weekday(a),weekday(b),weekday(c),weekday(d),weekday(e),weekday(f) from t1;**

- [ ] **select weekday(g),weekday(h),weekday(i),weekday(k),weekday(l),weekday(m),weekday(n) from t1;**

- [ ] **SELECT weekday(20150904) as weekday;**

- [ ] **SELECT weekday(1340124) as weekday;**

- [ ] **SELECT weekday(0.45133) as weekday;**

- [ ] **SELECT weekday(10) as weekday;**

- [ ] **SELECT weekday(1=1) as weekday;**

- [ ] **select dayofyear(a),dayofyear(b),dayofyear(c),dayofyear(d),dayofyear(e),dayofyear(f) from t1;**

- [ ] **select dayofyear(g),dayofyear(h),dayofyear(i),dayofyear(k),dayofyear(l),dayofyear(m),dayofyear(n) from t1;**

case1
[SQL STATEMENT]: SELECT a, CONCAT_WS(",",a,' ',a) AS c FROM t1
HAVING LENGTH(REVERSE(c)) >0;

case2
[SQL STATEMENT]: select substring(f1,1,1) from t1 group by 1;

case3
[SQL STATEMENT]: SELECT a FROM t1 HAVING bin(a) <>0;

case4
[SQL STATEMENT]: SELECT a, CONCAT_WS(",",a,' ',a) AS c FROM t1
HAVING find_in_set('a', c) =0;

case1
[SQL STATEMENT]: select substring(c,1,a),substr(vc,3,1) from t1 where id = 4 ;

case2
[SQL STATEMENT]: select substring(c,1,2),substr(vc,a,1) from t1 where id = 4 ;

### Steps to Reproduce

```markdown
download bvt report
```

**Comment by JinHai-CN** [comment]
All issues are tracked by BVT cases related issues.
