### ISSUE TITLE
[Bug]: meaningless functions with date,datetime,timestamp types as the actual parameters

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3184]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a557ce33b49b007540c917b87ee1e1368d76ce27
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Date in aggregate functions：

select min(big),avg(big),count(big)+1 from t1 group by big;
select avg(a),avg(b),avg(c),avg(d),avg(e),avg(f),avg(g),avg(h),avg(i),avg(k),avg(l),avg(m),avg(n) from t1;
select avg(a),avg(b),avg(c),avg(d),avg(e),avg(f),avg(g),avg(h),avg(i),avg(k),avg(l),avg(m),avg(n) from t1 limit 1;
SELECT sum(date(d1)) FROM t1;

Date math functions：
select sin(i), cos(i), tan(i),cot(i),acos(i),atan(i) from t1;
case6:
[SQL STATEMENT]: select sin(i), cos(i), tan(i),cot(i),acos(i),atan(i) from t1;
[ACTUAL RESULT]: Function 'sin' with parameters [DATE] will be implemented in future version.

case7:
[SQL STATEMENT]: select sin(k), cos(k), tan(k),cot(k),acos(k),atan(k) from t1;
[ACTUAL RESULT]: Function 'sin' with parameters [DATETIME] will be implemented in future version.

case8:
[SQL STATEMENT]: select sin(l), cos(l), tan(l),cot(l),acos(l),atan(l) from t1;
[ACTUAL RESULT]: Function 'sin' with parameters [TIMESTAMP] will be implemented in future version.

Date string functions：
select * from t1 where length(b)-8>0;
SELECT t1.a, t2.a FROM t1 JOIN t2 ON (rtrim(ltrim(t1.b)) = ltrim(rtrim(t2.b)));

### Steps to Reproduce

```markdown
download bvt report
```

**Comment by JinHai-CN** [comment]
All issues are tracked by BVT cases related issues.
