### ISSUE TITLE
[Bug]: other charset characters recognition

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3187]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e1319c52cf87b17a98008ae0dda79b72237d9ed1
- Hardware parameters:Mac M1 ARM 16GB Memory
- OS type:OSX
- Others:
```

### Actual Behavior

Error message: Data too long for column 'Ｃ１' at row 1

### Expected Behavior

this string is not long, it's simply other charset.

### Steps to Reproduce

```markdown
drop table if exists `Ｔ１`;
CREATE TABLE `Ｔ１` (`Ｃ１` char(8));
INSERT INTO `Ｔ１` VALUES ('ｱｲｳｴｵ');
```

**Comment by JinHai-CN** [comment]
In current charset setting, the inserted string is considered exceeding the char limit.

**Comment by JinHai-CN** [comment]
I can't find #3187 tag in the test cases. Would you please double check the cases?

**Comment by dengn** [comment]
OK for 0.6 to recognize this encoding.

**Comment by aressu1985** [comment]
mysql> drop table if exists `Ｔ１`;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `Ｔ１` (`Ｃ１` char(8));
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO `Ｔ１` VALUES ('ｱｲｳｴｵ');
Query OK, 1 row affected (0.00 sec)

mysql> 
mysql> select * from `Ｔ１`;
+-----------------+
| Ｃ１            |
+-----------------+
| ｱｲｳｴｵ           |
+-----------------+
1 row in set (0.01 sec)

mysql>
