### ISSUE TITLE
[Bug]: unsupported functions,operators,clauses in 0.5

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3200]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):082687ab181994a40ada97206e35ad2323aacb15
- Hardware parameters:
- OS type:
- Others:
```

### Fixed Cases

 with sales_by_month(month,total) as
(select month(day_of_sale), sum(amount) from sales_days
where year(day_of_sale)=2015
group by month(day_of_sale)),
best_month(month, total, award) as
(select month, total, "best" from sales_by_month
where total=(select max(total) from sales_by_month)),
worst_month(month, total, award) as
(select month, total, "worst" from sales_by_month
where total=(select min(total) from sales_by_month))
select * from best_month union all select * from worst_month;

case1: 
`[SQL STATEMENT]: select ltrim("a"),rtrim("a"),trim(BOTH "" from "a"),trim(BOTH " " from "a");`

case2
`[SQL STATEMENT]: insert into t2 (t2) select distinct substring(email, locate('@', email)+1) from t1;`

case3
[SQL STATEMENT]: select bin(12);

case4
[SQL STATEMENT]: SELECT bin(1314);

case5
[SQL STATEMENT]: select bin(2e5);

case6
[SQL STATEMENT]: SELECT bin(null);

case7
[SQL STATEMENT]: SELECT concat_ws(",", bin(1000), bin(2000));

case8
[SQL STATEMENT]: select bin(0);

case9
[SQL STATEMENT]: select bin(-1);

case10
[SQL STATEMENT]: select bin(10e50);

case11
[SQL STATEMENT]: select bin(-10e50);

case12
[SQL STATEMENT]: select bin(0.00000000000000000000000001);

case13
[SQL STATEMENT]: select bin(-0.00000000000000000000000001);

case14
[SQL STATEMENT]: select bin("你好");

case15
[SQL STATEMENT]: select bin(a) from t1;

case16
[SQL STATEMENT]: select bin(a),bin(b),bin(c),bin(d),bin(e),bin(f),bin(g),bin(h),bin(i),bin(k),bin(l),bin(m),bin(n) from t1;

case17
[SQL STATEMENT]: INSERT INTO t1 select bin(56), bin(234);

case18
[SQL STATEMENT]: INSERT INTO t1 select bin(100), bin(234);

case19
[SQL STATEMENT]: SELECT distinct bin(a), bin(b) FROM t1 ORDER BY bin(a);

case20
[SQL STATEMENT]: select bin(a)+bin(b) from t1 where bin(a)+bin(b)<>0;

case21
[SQL STATEMENT]: SELECT t1.a, t2.a FROM t1 JOIN t2 ON (bin(t1.a) = bin(t2.a));

case3
[SQL STATEMENT]: select bin(0b11111111);

bin(0b11111111)
11111111

### Cases need to fix
select oct(a)+oct(b) from t1 where oct(a)+oct(b)<>0;

[SQL STATEMENT]: select oct(0b11111111);

### Cases need to update
[SQL STATEMENT]: select * from t1 where find_in_set('-1', a);

[SQL STATEMENT]: select count(*) from t1 where STR_TO_DATE('2004.12.12 10:22:61','%Y.%m.%d %T') IS NULL;

[SQL STATEMENT]: SELECT ADDDATE(DATE'2021-01-01', INTERVAL 1 DAY);

[SQL STATEMENT]: SELECT ADDDATE(DATE'2021-01-01', INTERVAL 1 HOUR);

[SQL STATEMENT]: SELECT ADDDATE(TIMESTAMP'2021-01-01 00:00:00', INTERVAL 1 DAY);

[SQL STATEMENT]: SELECT ADDDATE(TIMESTAMP'2021-01-01 00:00:00', INTERVAL 1 HOUR);

[SQL STATEMENT]: SELECT ADDDATE(TIME'00:00:00', INTERVAL 1 HOUR);

[SQL STATEMENT]: SELECT ADDDATE('2021-01-01', INTERVAL 1 DAY);

[SQL STATEMENT]: SELECT ADDDATE('2021-01-01', INTERVAL 1 HOUR);

[SQL STATEMENT]: SELECT ADDDATE('2021-01-01 00:00:00', INTERVAL 1 DAY);

[SQL STATEMENT]: SELECT ADDDATE('2021-01-01 00:00:00', INTERVAL 1 HOUR);

[SQL STATEMENT]: SELECT ADDDATE('00:00:00', INTERVAL 1 DAY);

[SQL STATEMENT]: SELECT ADDDATE('00:00:00', INTERVAL 1 HOUR);

**Comment by dengn** [comment]
For ADDDATE, it's the same as DATE_ADD, check #3144.

**Comment by JinHai-CN** [comment]
All issues are tracked by BVT cases related issues.
