### ISSUE TITLE
[Feature Request]: insert values clause with functions and expressions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3202]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):082687ab181994a40ada97206e35ad2323aacb15
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[SQL STATEMENT]: insert into t1 values(DATE("2017-06-15 09:34:21")),(DATE("2019-06-25 10:12:21")),(DATE("2019-06-25 18:20:49"));

[SQL STATEMENT]: insert into t1 values(STR_TO_DATE('31.10.2004 15.30','%d.%m.%Y %H.%i'));

[SQL STATEMENT]: insert into t1 values(STR_TO_DATE('2004.12.12 11:22:33 AM','%Y.%m.%d %r'));

[SQL STATEMENT]: insert into t1 values(STR_TO_DATE('2004.12.12 10:22:59','%Y.%m.%d %T'));

[SQL STATEMENT]: INSERT INTO t1 VALUES ('2000-01-01', EXTRACT(WEEK FROM '2000-01-01'), YEARWEEK('2000-01-01'), WEEK('2000-01-01'), 1);

case1
[SQL STATEMENT]: insert into t1 values(21474836471, 12412490231412.124124124124, 124141231249124124.1241241243124123, 12421512141241241241241241849912840129402.1241124124241241, space(1000));

case2
[SQL STATEMENT]: insert into t1 values(21474836471, 12412490231412.124124124124, 124141231249124124.1241241243124123, 12421512141241241241241241849912840129402.1241124124241241, space(1000));

case3
[SQL STATEMENT]: insert t1 values (space(50000));

**Comment by dengn** [comment]
insert into ... functions and expression will be 0.6.0 feature.

**Comment by ouyuanning** [comment]
same as #2338

**Comment by iamlinjunhong** [comment]
process:
1. refactor default value for create table
2. refactor default value for insert select
3. refactor insert values

**Comment by goodMan-code** [comment]
This Feature Request has done, close it pls

**Comment by aressu1985** [comment]
fixed
