### ISSUE TITLE
[Bug]: to_date func invalid input value

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3203]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):082687ab181994a40ada97206e35ad2323aacb15
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[SQL STATEMENT]: SELECT DATE_ADD(to_date('9999-12-30 23:59:00','%Y-%m-%d %H:%i:%s'), INTERVAL 1 MINUTE);

[SQL STATEMENT]: SELECT to_date('01,5,2013','%d,%m,%Y');

[SQL STATEMENT]: SELECT to_date('May 1, 2013','%M %d,%Y');

[SQL STATEMENT]: SELECT to_date('a09:30:17','a%h:%i:%s');

[SQL STATEMENT]: SELECT to_date('a09:30:17','%h:%i:%s');

[SQL STATEMENT]: SELECT to_date('09:30:17a','%h:%i:%s');

[SQL STATEMENT]: SELECT to_date('abc','abc');

[SQL STATEMENT]: SELECT to_date('9','%m');

[SQL STATEMENT]: SELECT to_date('9','%s');

[SQL STATEMENT]: SELECT to_date('00/00/0000', '%m/%d/%Y');

[SQL STATEMENT]: SELECT to_date('04/31/2004', '%m/%d/%Y');

[SQL STATEMENT]: SELECT to_date('00/00/0000', '%m/%d/%Y');

[SQL STATEMENT]: SELECT to_date('200442 Monday', '%X%V %W');

[SQL STATEMENT]: select to_date(concat_ws(' ','15-01-2001'), ' 2:59:58.999');

[SQL STATEMENT]: select concat_ws('',to_date('8:11:2.123456 03-01-02','%H:%i:%S.%f %y-%m-%d'));

[SQL STATEMENT]: select to_date('04 /30/2004', '%m /%d/%Y');

[SQL STATEMENT]: select to_date('04/30 /2004', '%m /%d /%Y');

[SQL STATEMENT]: select to_date('04/30/2004 ', '%m/%d/%Y ');

[SQL STATEMENT]: SELECT DATE_SUB(to_date('9999-12-31 00:01:00','%Y-%m-%d %H:%i:%s'), INTERVAL 1 MINUTE);

[SQL STATEMENT]: SELECT DATE_ADD(to_date('9999-12-30 23:59:00','%Y-%m-%d %H:%i:%s'), INTERVAL 1 MINUTE);

[SQL STATEMENT]: select to_date('10:00 PM', '%h:%i %p') + INTERVAL 10 MINUTE;

[SQL STATEMENT]: select to_date('2007-10-09','%Y-%m-%d') > '2007/10/01 00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d') = '2007-10-1 00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d') = '2007-10-01 x00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d %H:%i:%s') = '2007-10-01 00:00:00 GMT-6';

[SQL STATEMENT]: select to_date('2007-10-01','%Y-%m-%d %H:%i:%s') = '2007-10-01 00:x00:00 GMT-6';

[SQL STATEMENT]: select to_date('1000-01-01','%Y-%m-%d') between NULL and NULL;

[SQL STATEMENT]: select to_date('2007-10-00','%Y-%m-%d') between '' and '2007/10/20';

[SQL STATEMENT]: select to_date('2007-10-00','%Y-%m-%d') between '2007/09/01'
and '2007/10/20';

[SQL STATEMENT]: select to_date('2007-10-09','%Y-%m-%d') between '2007/10/01 00:00:00 GMT'
and '2007/10/20 00:00:00 GMT';

[SQL STATEMENT]: SELECT to_date('09:22', '%H:%i');

[SQL STATEMENT]: SELECT to_date('09:22:23.33', '%H:%i:%s.%f');

[SQL STATEMENT]: INSERT INTO t1 select( to_date('09:22', '%H:%i') );

[SQL STATEMENT]: INSERT INTO t1 select( to_date('09:22:23.33', '%H:%i:%s.%f') );

[SQL STATEMENT]: SELECT TO_DATE(SPACE(2),'1');

case1
[SQL STATEMENT]: SELECT TO_DATE(SPACE(2),'1');

**Comment by daviszhen** [comment]
too many errors related to `to_date `

**Comment by broccoliSpicy** [comment]
these bvt test cases are funny
sure we say matrixone is mysql compatible, but we also need to be smart and don't fool ourselves, how much effort it needs to have the same behavior as mysql and how trivial the effect might be.
as a fledgling dbms with limited engineering resources, prioritize our tasks on essential dbms features would do us good.
I am not saying date format is not import, it is, in this world different date formats are used in different places.
I will do a survey and come up with a comprehensive definition on the date/datetime/timestamp formats we want to support in issue#3151.

**Comment by broccoliSpicy** [comment]
maybe just ISO8601?

**Comment by dengn** [comment]
ok for 0.6.

**Comment by qingxinhome** [comment]
The implementation of TO_Date() function has been reconstructed. To_DATE and STR_TO_DATE is a synonym. Please know that pr is submitted for consolidation。 @daviszhen @dengn @sukki37

**Comment by qingxinhome** [comment]
TO_ The implementation of Date() function has been reconstructed. To_ DATE and STR_ TO_ DATE is a synonym, STR_ TO_ The second parameter of the DATE (str, format) function is limited to a string constant.
Note: There are some test cases related to date type in the bvt corresponding to # 3203 that fail the test, but are related to to_ The date function is independent.  @daviszhen @dengn @sukki37 @dongdongyang33
