### ISSUE TITLE
[Bug]: mo crash when commit the txn that simultaneously have create table and drop table

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3221]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> 
mysql> drop table test_11;
ERROR 1105 (HY000): tae: DDL cannot drop created in a txn
mysql> select * from test_11;
ERROR 1105 (HY000): table "test_11" does not exist
mysql> 
mysql> commit
    -> ;
Query OK, 0 rows affected (0.02 sec)

mysql> select * from test_11;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (61)
ERROR: 
Can't connect to the server

mysql>

**Comment by iamlinjunhong** [comment]
if will happen when begin
<img width="1138" alt="截屏2022-06-23 上午11 26 12" src="https://user-images.githubusercontent.com/49111204/175202486-2eaff535-0341-4354-8588-accbfdb8424e.png">
.

**Comment by iamlinjunhong** [comment]
mo will crash when rm -rf store and restart mo Or first start mo.
<img width="1430" alt="截屏2022-06-23 上午11 45 35" src="https://user-images.githubusercontent.com/49111204/175204593-0c3dedb9-a6aa-4e0d-9000-13d6a4645885.png">
<img width="1485" alt="截屏2022-06-23 上午11 45 52" src="https://user-images.githubusercontent.com/49111204/175204612-d4e06e53-d80b-4734-afea-ba7536a2b539.png">
