### ISSUE TITLE
[Bug]: SHOW tables panic

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3223]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e086b4d
- Hardware parameters:Mac M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

ERROR 1105 (HY000): Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 298 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x10200a480?, 0x10338f9a0})
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/common/moerr/error.go:91 +0x50
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/Users/nandeng/Test/matrixone_new/matrixone/pkg/frontend/mysql_

### Expected Behavior

show tpch tables

### Steps to Reproduce

```markdown
run MO-Tester for TPCH benchmark with path: "cases/benchmark/tpch/"

then run
mysql> show tables;
```

**Comment by jianwan0214** [comment]
please rerun in the new version code, I find there is not exist this question now, please recheck this question. If it is ok now, please close this issue, thx.
