### ISSUE TITLE
[Bug]:  Bool cannot be converted to itself

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3244]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a bool, b bool);
insert into t1 values(true,null);
update t1 set a=false where b is null;
Operator 'cast' with parameters [BOOL BOOL] will be implemented in future version.

**Comment by aressu1985** [comment]
fixed

mysql> create table t1(a bool, b bool);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 values(true,null);
Query OK, 1 row affected (0.01 sec)

mysql> update t1 set a=false where b is null;
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+-------+------+
| a     | b    |
+-------+------+
| false | NULL |
+-------+------+
1 row in set (0.00 sec)
