### ISSUE TITLE
[Bug]: VARCHAR cannot be converted to itself

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3246]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a varchar(10));
update t1 set a=a+'101';
Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.

**Comment by JinHai-CN** [comment]
This case will not be supported.

**Comment by JinHai-CN** [comment]
Should prompt a proper error message and move to 0.6.

**Comment by domingozhang** [comment]
need an error code in 0.6

**Comment by domingozhang** [comment]
fixed
