### ISSUE TITLE
[Bug]: wrong result for rtrim&ltrim

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3248]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e086b4d
- Hardware parameters:Mac M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: SELECT 1 FROM t WHERE rtrim(a & NULL);
[EXPECT RESULT]:
1
[ACTUAL RESULT]:
1
1

[SQL STATEMENT]: SELECT 1 FROM t WHERE ltrim(a & NULL);
[EXPECT RESULT]:
1
[ACTUAL RESULT]:
1
1

### Steps to Reproduce

```markdown
CREATE TABLE t (a int NOT NULL);
INSERT INTO t values(21123);
SELECT 1 FROM t WHERE rtrim(a & NULL);
SELECT 1 FROM t WHERE ltrim(a & NULL);
DROP TABLE t;
```

**Comment by JinHai-CN** [comment]
1. & is not supported in 0.5. A proper error message is needed.
2. WHERE clause need bool expressions.

**Comment by dengn** [comment]
an issue dedicated to bit operation support is at #3549
