### ISSUE TITLE
[Bug]: Operator 'not' with parameters INT failed

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3250]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t2(a int,b int);
insert into t2 values(1,2),(3,4);
select * from t2 where a<1 AND NOT b order by b desc;
Operator 'not' with parameters [INT] will be implemented in future version.

**Comment by JinHai-CN** [comment]
This case will not be supported.

**Comment by JinHai-CN** [comment]
A proper error message should be given.

**Comment by domingozhang** [comment]
need an error code in 0.6

**Comment by domingozhang** [comment]
fxied

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.
