### ISSUE TITLE
[Bug]: Conversion failed from INT to CHAR in CAST

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3252]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast(Age as char) and Age as cAge from Demochar where Age>=50 order by cAge;
Operator 'and' with parameters [CHAR INT] will be implemented in future version.

**Comment by JinHai-CN** [comment]
Should provide a proper error message.

**Comment by domingozhang** [comment]
this conversation is in datatype table. Need  to be supported in 0.6

**Comment by domingozhang** [comment]
INT to CHAR in CAST has been supported now.

**Comment by fengttt** [comment]
Please check if this is already fixed, and close.
