### ISSUE TITLE
[Bug]:  Implicit conversion failed from VARCHAR to DATE

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3253]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from t4 where b>'20211213';
Operator '>' with parameters [DATE VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
mysql> select * from t4 where b>'20211213';
+------+------------+----------------------------+
| a    | b          | c                          |
+------+------------+----------------------------+
|    2 | 2021-12-14 | 2021-12-13 00:00:00.000000 |
|    3 | 2021-12-14 | 2021-12-14 00:00:00.000000 |
|    4 | 2021-12-15 | 2021-12-14 00:00:00.000000 |
+------+------------+----------------------------+
3 rows in set (0.00 sec)

**Comment by domingozhang** [comment]
fixed
