### ISSUE TITLE
[Bug]: rpad&lpad result error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3255]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e086b4d
- Hardware parameters:Mac M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: select rpad('hello', -18446744073709551615, '1');
[EXPECT RESULT]:
rpad('hello', -18446744073709551615, '1')
null
[ACTUAL RESULT]:
rpad(hello, -18446744073709551615, 1)
h

[SQL STATEMENT]: select rpad('hello', 18446744073709551616, '1');
[EXPECT RESULT]:
rpad('hello', 18446744073709551616, '1')
null
[ACTUAL RESULT]:
rpad(hello, 18446744073709551616, 1)

[SQL STATEMENT]: select rpad('hello', 18446744073709551617, '1');
[EXPECT RESULT]:
rpad('hello', 18446744073709551617, '1')
null
[ACTUAL RESULT]:
rpad(hello, 18446744073709551617, 1)

[SQL STATEMENT]: select lpad('hello', -18446744073709551615, '1');
[EXPECT RESULT]:
lpad('hello', -18446744073709551615, '1')
null
[ACTUAL RESULT]:
lpad(hello, -18446744073709551615, 1)
h

[SQL STATEMENT]: SELECT RPAD("",(55 - LENGTH(title)),".") from t1;
[EXPECT RESULT]:
RPAD("",(55 - LENGTH(title)),".")
null
..........................
[ACTUAL RESULT]:
rpad(, (55 - length(title)), .)
null

**Comment by JinHai-CN** [comment]
Let's give an upper limitation value(8000) to the second parameter of the two functions.

**Comment by JinHai-CN** [comment]
Let's give an upper limitation value(8000) to the second parameter of the two functions.

**Comment by dengn** [comment]
#3255 tag is not removed...
