### ISSUE TITLE
[Bug]: Implicit conversion failed from BIGINT to DATE

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3257]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast(cast(0x13488c5 as signed) as date);
Operator 'cast' with parameters [BIGINT DATE] will be implemented in future version.

**Comment by JinHai-CN** [comment]
Should provide a proper error message.

**Comment by domingozhang** [comment]
error code need be provided in 0.6

**Comment by daviszhen** [comment]
MO do not support the conversion  BIGINT=>DATE base on the doc : https://doc.weixin.qq.com/sheet/e3_AdIAkQb_AEYGT3QVZBJQXqJghCjYF?scode=AJsA6gc3AA840KbtsHAAgAkgYHABU&tab=s8bwcy

We can close the issue.
