### ISSUE TITLE
[Bug]: Implicit conversion failed from VARCHAR to TINYINT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3260]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 SELECT * from t_tinyint WHERE id BETWEEN '1.1e0' AND '1.9e0';
Operator '>=' with parameters [TINYINT VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
can't cast '1.1e0' from VARCHAR type to TINYINT type.

**Comment by domingozhang** [comment]
fixed with proper error code
