### ISSUE TITLE
[Question]: if GROUP BY alias nor aggregation function not supported, how do we support this kind of SQL?

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3265]
### Describe your problem

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 ( number INT NOT NULL, alpha CHAR(6) NOT NULL );
INSERT INTO t1 VALUES (1413006,'idlfmv'),
(1413065,'smpsfz'),(1413127,'sljrhx'),(1413304,'qerfnd');
SELECT number, any_value(alpha), CONCAT_WS('<---->',number,any_value(alpha)) AS new
FROM t1 GROUP BY number;
SELECT CONCAT_WS('<---->',number,alpha) AS new
FROM t1 GROUP BY CONCAT_WS('<---->',number,alpha) LIMIT 1;
SELECT any_value(number), any_value(alpha), CONCAT_WS('<->',any_value(number),any_value(alpha)) AS new
FROM t1 GROUP BY new LIMIT 1;
SELECT any_value(number), any_value(alpha), CONCAT_WS('-',any_value(number),any_value(alpha),any_value(alpha),any_value(alpha),any_value(alpha),any_value(alpha),any_value(alpha),any_value(alpha)) AS new
FROM t1 GROUP BY new LIMIT 1;
SELECT any_value(number), any_value(alpha), CONCAT_WS('<------------------>',any_value(number),any_value(alpha)) AS new
FROM t1 GROUP BY new LIMIT 1;
drop table t1;

We report "column "new" does not exist" for this sql now. If we replace alias 'new' by the original CONCAT_WS..., we report 'GROUP BY clause cannot contain aggregate functions!'.

**Comment by fengttt** [comment]
Both are correct behaviors and correct error messages.    @daviszhen please clean tags and hand off to test.

**Comment by Ariznawlll** [comment]
CREATE TABLE t1 (a int, b DOUBLE);
INSERT INTO t1 VALUES (NULL, 0), (NULL, 1);
SELECT IF(b, (SELECT a FROM t1 LIMIT 1), b) c FROM t1 GROUP BY c;
DROP TABLE t1;

<img width="1511" height="303" alt="Image" src="https://github.com/user-attachments/assets/ea16793b-2034-49c0-8ebd-7c4730247eef" />

没实现
