### ISSUE TITLE
[Bug]: Implicit conversion failed from VARCHAR to TINYINT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3267]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from t1 where tinyint_col='250';
Operator '=' with parameters [TINYINT UNSIGNED VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
I have fixed it now.
