### ISSUE TITLE
[Bug]: Implicit conversion failed from VARCHAR to TIMESTAMP

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3270]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

delete from t1 where a='2022-01-01';
Operator '=' with parameters [TIMESTAMP VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
mysql> delete from t1 where a='2022-01-01';
ERROR 1105 (HY000): Operator '=' with parameters [TIMESTAMP VARCHAR] will be implemented in future version.

**Comment by domingozhang** [comment]
fixed
