### ISSUE TITLE
[Bug]: Implicit conversion failed from DOUBLE to TIMESTAMP

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3271]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT * from t_timestamp WHERE id BETWEEN 2.0200101e7 and 2.0200102e7;
Operator '>=' with parameters [TIMESTAMP DOUBLE] will be implemented in future version.

**Comment by JinHai-CN** [comment]
Type of Timestamp and Double can't be compared. A proper error message should be given.

**Comment by domingozhang** [comment]
error message need to be provided in 0.6

**Comment by daviszhen** [comment]
MO do not support the conversion DOUBLE <=> TIMESTAMP base on the doc : https://doc.weixin.qq.com/sheet/e3_AdIAkQb_AEYGT3QVZBJQXqJghCjYF?scode=AJsA6gc3AA840KbtsHAAgAkgYHABU&tab=s8bwcy

We can close the issue.
