### ISSUE TITLE
[Bug]: Implicit conversion failed from TIMESTAMP to BIGINT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3272]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT id, 20200101 = id FROM t_timestamp;
Operator '=' with parameters [BIGINT TIMESTAMP] will be implemented in future version.

**Comment by m-schen** [comment]
mysql> SELECT id, 20200101 = id FROM t_timestamp;
ERROR 1105 (HY000): Operator '=' with parameters [BIGINT TIMESTAMP] will be implemented in future version.

I think I missed it at binary convert rule table.

**Comment by m-schen** [comment]
> mysql> SELECT id, 20200101 = id FROM t_timestamp; ERROR 1105 (HY000): Operator '=' with parameters [BIGINT TIMESTAMP] will be implemented in future version.
> 
> I think I missed it at binary convert rule table.

I seems that we will not support the bigint + - * / = <> timestamp

**Comment by m-schen** [comment]
we will implicit convert
timestamp <operator> bigint    ==> timestamp <operator> timestamp
bigint <operator> timestamp    ==> timestamp <operator> timestamp

but we don't have timestamp - timestamp now. I have refresh the issue tag to #3739.

**Comment by domingozhang** [comment]
closed
