### ISSUE TITLE
[Bug]: wrong round func result

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3273]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e086b4d
- Hardware parameters:Mac M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: select -(0-3),round(-(0-3)), round(9999999999999999999);
[EXPECT RESULT]:
-(0-3)	round(-(0-3))	round(9999999999999999999)
3	3	9999999999999999999
[ACTUAL RESULT]:
-(0 - 3)	round(-(0 - 3))	round(9999999999999999999)
3	3	-8446744073709551617

[SQL STATEMENT]: select round(15000111000111000155,-1);
[EXPECT RESULT]:
round(15000111000111000155,-1)
15000111000111000160
[ACTUAL RESULT]:
round(15000111000111000155, -1)
-3446633073598551680

[SQL STATEMENT]: select round(cast(-2 as unsigned), 1), round(18446744073709551614, 1), round(-2, 1);
[EXPECT RESULT]:
round(cast(-2 as unsigned), 1)	round(18446744073709551614, 1)	round(-2, 1)
18446744073709551614	18446744073709551614	-2
[ACTUAL RESULT]:
round(cast(-2 as unsigned unsigned), 1)	round(18446744073709551614, 1)	round(-2, 1)
18446744073709551614	-2	-2

[SQL STATEMENT]: select round(1.5, -4294967296), round(1.5, 4294967296);
[EXPECT RESULT]:
round(1.5, -4294967296)	round(1.5, 4294967296)
0	1.5
[ACTUAL RESULT]:
round(1.5, -4294967296)	round(1.5, 4294967296)
NaN	NaN

[SQL STATEMENT]: select round(1.5, -9223372036854775808), round(1.5, 9223372036854775808);
[EXPECT RESULT]:
round(1.5, -9223372036854775808)	round(1.5, 9223372036854775808)
0	1.5
[ACTUAL RESULT]:
round(1.5, -9223372036854775808)	round(1.5, 9223372036854775808)
NaN	NaN

[SQL STATEMENT]: select round(999999999.0, -9);
[EXPECT RESULT]:
round(999999999.0, -9)
1000000000
[ACTUAL RESULT]:
round(999999999.0, -9)
9.999999999999999E8

[SQL STATEMENT]: select round(999999999999999999.0, -18);
[EXPECT RESULT]:
round(999999999999999999.0, -18)
1000000000000000000
[ACTUAL RESULT]:
round(999999999999999999.0, -18)
9.9999999999999987E17

[SQL STATEMENT]: select round(cast(-2 as unsigned), 1), round(18446744073709551614, 1), round(-2, 1);
[EXPECT RESULT]:
round(cast(-2 as unsigned), 1)	round(18446744073709551614, 1)	round(-2, 1)
18446744073709551614	18446744073709551614	-2
[ACTUAL RESULT]:
round(cast(-2 as unsigned unsigned), 1)	round(18446744073709551614, 1)	round(-2, 1)
18446744073709551614	-2	-2

[SQL STATEMENT]: select round(10000000000000000000, -19);
[EXPECT RESULT]:
round(10000000000000000000, -19)
10000000000000000000
[ACTUAL RESULT]:
round(10000000000000000000, -19)
0

[SQL STATEMENT]: select round(1e1, 2147483648);
[EXPECT RESULT]:
round(1e1, 2147483648)
10.0
[ACTUAL RESULT]:
round(1e1, 2147483648)
NaN

[SQL STATEMENT]: select round(1.1e1, 4294967295);
[EXPECT RESULT]:
round(1.1e1, 4294967295)
11.0
[ACTUAL RESULT]:
round(1.1e1, 4294967295)
NaN

[SQL STATEMENT]: select round(1.12e1, 4294967296);
[EXPECT RESULT]:
round(1.12e1, 4294967296)
11.2
[ACTUAL RESULT]:
round(1.12e1, 4294967296)
NaN

[SQL STATEMENT]: select round(1.5, 2147483640);
[EXPECT RESULT]:
round(1.5, 2147483640)
1.5
[ACTUAL RESULT]:
round(1.5, 2147483640)
NaN

[SQL STATEMENT]: select round(1.5, -2147483649), round(1.5, 2147483648);
[EXPECT RESULT]:
round(1.5, -2147483649)	round(1.5, 2147483648)
0	1.5
[ACTUAL RESULT]:
round(1.5, -2147483649)	round(1.5, 2147483648)
NaN	NaN

[SQL STATEMENT]: select round(1.5, -4294967296), round(1.5, 4294967296);
[EXPECT RESULT]:
round(1.5, -4294967296)	round(1.5, 4294967296)
0	1.5
[ACTUAL RESULT]:
round(1.5, -4294967296)	round(1.5, 4294967296)
NaN	NaN

[SQL STATEMENT]: select round(1.5, -9223372036854775808), round(1.5, 9223372036854775808);
[EXPECT RESULT]:
round(1.5, -9223372036854775808)	round(1.5, 9223372036854775808)
0	1.5
[ACTUAL RESULT]:
round(1.5, -9223372036854775808)	round(1.5, 9223372036854775808)
NaN	NaN

[SQL STATEMENT]: select round(1.5, 18446744073709551615);
[EXPECT RESULT]:
round(1.5, 18446744073709551615)
1.5
[ACTUAL RESULT]:
round(1.5, 18446744073709551615)
0.0

[SQL STATEMENT]: select round(18446744073709551614, -1);
[EXPECT RESULT]:
round(18446744073709551614, -1)
18446744073709551610
[ACTUAL RESULT]:
round(18446744073709551614, -1)
0

**Comment by broccoliSpicy** [comment]
when using a general method to round, this is bound do happen, and these behavior is consistent with the definition of float-point number

**Comment by fengttt** [comment]
[ACTUAL RESULT]:
-(0 - 3) round(-(0 - 3)) round(9999999999999999999)
3 3 -8446744073709551617

This cannot possibly be the right result, right?

**Comment by broccoliSpicy** [comment]
> [ACTUAL RESULT]: -(0 - 3) round(-(0 - 3)) round(9999999999999999999) 3 3 -8446744073709551617
> 
> This cannot possibly be the right result, right?

fixed by other pull requests handling input literal value types

**Comment by dengn** [comment]
#3273 Tag is not removed yet.

**Comment by daviszhen** [comment]
it was fixed

**Comment by dengn** [comment]
Most of them are fixed. But we still have a #3747 bug to solve.
