### ISSUE TITLE
[Bug]: TIMESTAMP cannot be converted to itself 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3274]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from t1 join t2 on t1.dt=t2.dt where t1.value32<>t2.value32;
Operator '=' with parameters [TIMESTAMP TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
add timestamp op =.

**Comment by m-schen** [comment]
mysql> select * from t1 join t2 on t1.dt=t2.dt order by 1 desc, t2.dt asc;
ERROR 1105 (HY000): Operator '=' with parameters [TIMESTAMP TIMESTAMP] will be implemented in future version.
mysql> select * from t1 join t2 on t1.dt=t2.dt where t1.value32<>t2.value32;
ERROR 1105 (HY000): Operator '=' with parameters [TIMESTAMP TIMESTAMP] will be implemented in future version.

**Comment by domingozhang** [comment]
fixed
