### ISSUE TITLE
[Bug]: Implicit conversion failed from VARCHAR to SMALLINT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3275]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT * from t_smallint WHERE id BETWEEN '1.1e0' AND '1.9e0';
Operator '>=' with parameters [SMALLINT VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
mysql> SELECT * from t_smallint WHERE id BETWEEN '1.1' AND '1.9';
ERROR 1105 (HY000): strconv.ParseInt: parsing "1.1": invalid syntax
mysql> SELECT * from t_smallint WHERE id BETWEEN '1.1e0' AND '1.9e0';
ERROR 1105 (HY000): strconv.ParseInt: parsing "1.1e0": invalid syntax

**Comment by domingozhang** [comment]
fixed with proper error code
