### ISSUE TITLE
[Bug]:  Implicit conversion failed from VARCHAR to INT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3276]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 SELECT * from t_int WHERE id BETWEEN '1.1e0' AND '1.9e0';
Operator '>=' with parameters [INT VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
mysql> SELECT * from t_int WHERE id BETWEEN '1.1' AND '1.9';
ERROR 1105 (HY000): strconv.ParseInt: parsing "1.1": invalid syntax
mysql> SELECT * from t_int WHERE id BETWEEN '1.1e0' AND '1.9e0';
ERROR 1105 (HY000): strconv.ParseInt: parsing "1.1e0": invalid syntax
