### ISSUE TITLE
[Bug]:  Implicit conversion failed from DOUBLE to DECIMAL

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3280]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a decimal(10,5));
delete from t1 where  a=24.0000;
Operator '=' with parameters [DECIMAL64 DOUBLE] will be implemented in future version.

**Comment by daviszhen** [comment]
no cast decimal => double

**Comment by m-schen** [comment]
mysql> insert into t1 values (24.0000);
Query OK, 1 row affected (0.00 sec)

mysql> delete from t1 where a=24.0000;
Query OK, 1 row affected (0.00 sec)

**Comment by domingozhang** [comment]
fixed
