### ISSUE TITLE
[Bug]: Implicit conversion failed from VARCHAR to DECIMAL

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3281]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT * from t_decimal WHERE id BETWEEN '1.1' AND '1.9';
Operator '>=' with parameters [DECIMAL64 VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
refresh error message.

**Comment by m-schen** [comment]
[Result Now]
mysql> SELECT * from t_decimal WHERE id BETWEEN '1.1' AND '1.9';
Empty set (0.00 sec)

no error return, but result is wrong.

**Comment by domingozhang** [comment]
fixed
