### ISSUE TITLE
[Bug]: Implicit conversion failed from BIGINT to DECIMAL

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3283]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast(10000002383263201056 as decimal) mod 50 as result;
Operator '%' with parameters [DECIMAL64 BIGINT] will be implemented in future version.

**Comment by daviszhen** [comment]
int64 -> decimal.


problem:
1. decimal % decimal , no implementation in type analysis
2. cast error in execution 
==========

refresh error message.
move to 0.6 .

**Comment by daviszhen** [comment]
?????

-- @bvt:issue#3283
update t1 set a=a+101;
select a,b from t1 order by 1;
update t1 set a=27 where a=125;
select a,b from t1 order by 1;
update t1 set a=a-1 where 1 > 2;
select a,b from t1 order by 1;
update t1 set a=a-1 where 3 > 2;
select a,b from t1 order by 1;
-- @bvt:issue

**Comment by domingozhang** [comment]
will be provided error code in 0.6

**Comment by tianyahui-python** [comment]
<img width="874" alt="截屏2022-10-29 22 16 41" src="https://user-images.githubusercontent.com/39303074/198836404-763e90de-3fc4-4d0c-aecb-4fd63c2e239b.png">

**Comment by tianyahui-python** [comment]
@domingozhang can close issue.
