### ISSUE TITLE
[Bug]: fix interval bug

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#3285]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. INTERVAL "-1:1" HOUR_MINUTE
2. support more date/datetime input format
3. when date_add/sub arg is string, the return type will be datetime

example:
select date_add("1997-12-31 23:59:59",INTERVAL "-1:1" HOUR_MINUTE);
select date_add("1997-12-31 23:59:9",INTERVAL "-1:1" HOUR_MINUTE);
select weekday(date_sub("1998-01-01 00:00:00",INTERVAL 1 MINUTE));

**Comment by aressu1985** [comment]
fixed

mysql> select date_add("1997-12-31 23:59:59",INTERVAL "-1:1" HOUR_MINUTE);
+------------------------------------------------------------+
| date_add(1997-12-31 23:59:59, interval(-1:1, hour_minute)) |
+------------------------------------------------------------+
| 1997-12-31 22:58:59.000000                                 |
+------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select date_add("1997-12-31 23:59:9",INTERVAL "-1:1" HOUR_MINUTE);
+-----------------------------------------------------------+
| date_add(1997-12-31 23:59:9, interval(-1:1, hour_minute)) |
+-----------------------------------------------------------+
| 1997-12-31 22:58:09.000000                                |
+-----------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select weekday(date_sub("1998-01-01 00:00:00",INTERVAL 1 MINUTE));
+-------------------------------------------------------------+
| weekday(date_sub(1998-01-01 00:00:00, interval(1, minute))) |
+-------------------------------------------------------------+
|                                                           2 |
+-------------------------------------------------------------+
1 row in set (0.00 sec)
