### ISSUE TITLE
[Enhancement]: include target UUID in ScheduleCommand

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3287]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
When trying to add a replica, the ScheduleCommand generated by the HAKeeper should contains the target UUID value, which is the UUID of Log store on which the new replica will be running. 

A possible place to include this field is the ConfigChange struct.
```

**Comment by w-zr** [comment]
Currently, the store's UUID is already in `ScheduleCommand`.
See https://github.com/matrixorigin/matrixone/blob/main/proto/hakeeper.proto#L55
