### ISSUE TITLE
[Bug]: Implicit conversion failed from INT to BOOL

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3289]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select t1.a,t2.b from t1 join t2 on t1.a=t2.a order by t1.a desc;
Operator '=' with parameters [BOOL INT] will be implemented in future version.

**Comment by domingozhang** [comment]
If int -> bool was not supported, I suggest we modify the error notification, such as [BOOL BIGINT] is not supported in MO

**Comment by JinHai-CN** [comment]
A proper error message should be given.

**Comment by domingozhang** [comment]
need to be handled in 0.6

**Comment by ouyuanning** [comment]
create table t1(a int, b bool);
select * from t1 where a=b;

**Comment by aressu1985** [comment]
mysql> create table t1(a int, b bool);
Query OK, 0 rows affected (0.00 sec)

mysql> select * from t1 where a=b;
Empty set (0.00 sec)

mysql>
