### ISSUE TITLE
[Bug]: function doesn't implement its eval method

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3292]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast('2020-02-01' as date)+NULL;
function doesn't implement its eval method

**Comment by m-schen** [comment]
will return 
mysql> select a + null from cms;
ERROR 1105 (HY000): Operator '+' with parameters [DATE DATE] will be implemented in future version.

now.

**Comment by domingozhang** [comment]
will be supported in 0.6.0

**Comment by aressu1985** [comment]
mysql> select cast('2020-02-01' as date)+NULL;
+---------------------------------+
| cast(2020-02-01 as date) + null |
+---------------------------------+
|                            NULL |
+---------------------------------+
1 row in set (0.00 sec)
