### ISSUE TITLE
[Bug]: DATE cannot be converted to BIGINT in CAST

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3293]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast(cast(0x13488c5 as signed) as date);
Operator 'cast' with parameters [BIGINT DATE] will be implemented in future version.

**Comment by yingfeng** [comment]
Similar issue but with panic:

```
mysql> select cast('2020-02-01' as date) + NULL;
ERROR 1105 (HY000): function doesn't implement its eval method
mysql> select 1+NULL;
ERROR 1105 (HY000): Internal error: panic runtime error: index out of range [0] with length 0: goroutine 274 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x104186c00?, 0x14004db49a8})
	/Users/yingfeng/codebase/matrixorigin/matrixone/pkg/common/moerr/error.go:91 +0x50
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
```

**Comment by JinHai-CN** [comment]
A proper error message should be given.

**Comment by JinHai-CN** [comment]
> Similar issue but with panic:
> 
> ```
> mysql> select cast('2020-02-01' as date) + NULL;
> ERROR 1105 (HY000): function doesn't implement its eval method
> mysql> select 1+NULL;
> ERROR 1105 (HY000): Internal error: panic runtime error: index out of range [0] with length 0: goroutine 274 [running]:
> runtime/debug.Stack()
> 	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
> github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x104186c00?, 0x14004db49a8})
> 	/Users/yingfeng/codebase/matrixorigin/matrixone/pkg/common/moerr/error.go:91 +0x50
> github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
> ```

No, they are different. These two cases is about NULL handling.

And second statement is correct, now.

> mysql> select 1+NULL;
> +----------+
> | 1 + null |
> +----------+
> |     NULL |
> +----------+

**Comment by yingfeng** [comment]
panic has been fixed already

**Comment by domingozhang** [comment]
need an error code in 0.6

**Comment by sukki37** [comment]
@domingozhang can update the status

**Comment by domingozhang** [comment]
date to int will not be converted. error code will be normalized in future

**Comment by daviszhen** [comment]
MO do not support the conversion DATE => BIGINT base on the doc : https://doc.weixin.qq.com/sheet/e3_AdIAkQb_AEYGT3QVZBJQXqJghCjYF?scode=AJsA6gc3AA840KbtsHAAgAkgYHABU&tab=s8bwcy
