### ISSUE TITLE
[Bug]: not support "|" operation between case_when expression and int value

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3294]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/expression/case_when.sql
[ROW    NUMBER]: 12
[SQL STATEMENT]: select (CASE "two" when "one" then "1" WHEN "two" then "2" END) | 0;
[EXPECT RESULT]:
(CASE "two" when "one" then "1" WHEN "two" then "2" END) | 0
2
[ACTUAL RESULT]:
'' is not support now

[ERROR]
[SCRIPT   FILE]: cases/expression/case_when.sql
[ROW    NUMBER]: 16
[SQL STATEMENT]: select (case 1/0 when "a" then "true" END) | 0;
[EXPECT RESULT]:
(case 1/0 when "a" then "true" END) | 0
null
[ACTUAL RESULT]:

**Comment by JinHai-CN** [comment]
1. Proper error message is needed.
2. Case expression needs bool expression as the input parameter.

**Comment by daviszhen** [comment]
provide right error message

**Comment by m-schen** [comment]
we will return
'|' operator is not supported now
now.

**Comment by aressu1985** [comment]
mysql>  select (CASE "two" when "one" then "1" WHEN "two" then "2" END) | 0;
+----------------------------------------------------+
| (case two when one then 1 when two then 2 end) | 0 |
+----------------------------------------------------+
|                                                  2 |
+----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select (case 1/0 when "a" then "true" END) | 0;
ERROR 20200 (HY000): division by zero
mysql>
