### ISSUE TITLE
[Bug]: Function 'avg' with parameters DATE failed

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3295]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select min(big),avg(big),count(big)+1 from t1 group by big;
Function 'avg' with parameters [DATE] will be implemented in future version.

**Comment by JinHai-CN** [comment]
A proper error message should be given.

**Comment by domingozhang** [comment]
need an error code in 0.6

**Comment by domingozhang** [comment]
avg will not support date because int cannot be converted from date in mo.

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by daviszhen** [comment]
MO do not support the conversion DATE in the function AVG base on the doc : https://doc.weixin.qq.com/doc/w3_AAgAkgYHABUU6Y7hl0PQEuM6Tjv31?scode=AJsA6gc3AA8SOwl4g8AAgAkgYHABU

We can close the issue.
