### ISSUE TITLE
[Bug]: the result is error in some case_when expressions

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3298]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1、
drop table if exists  t1;
drop table if exists  t2;
create table t1 (a int, b bigint unsigned);
create table t2 (c int);
insert into t1 (a, b) values (1,4572794622775114594), (2,18196094287899841997),
  (3,11120436154190595086);
insert into t2 (c) values (1), (2), (3);
select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
  join t2 on t1.a=t2.c order by d;
select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
  join t2 on t1.a=t2.c where b=11120436154190595086 order by d;

[ERROR]
[SCRIPT   FILE]: cases/expression/case_when.sql
[ROW    NUMBER]: 86
[SQL STATEMENT]: select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
join t2 on t1.a=t2.c where b=11120436154190595086 order by d;
[EXPECT RESULT]:
a       d
3       11120436154190595086
[ACTUAL RESULT]:
a       d

2、
drop table t1;
CREATE TABLE t1(a int);
insert into t1 values(1),(1),(2),(1),(3),(2),(1);
SELECT 1 FROM t1 WHERE a=1 AND CASE 1 WHEN a THEN 1 ELSE 1 END;
DROP TABLE if exists t1;

[ERROR]
[SCRIPT   FILE]: cases/expression/case_when.sql
[ROW    NUMBER]: 86
[SQL STATEMENT]: select t1.a, (case t1.a when 0 then 0 else t1.b end) d from t1
join t2 on t1.a=t2.c where b=11120436154190595086 order by d;
[EXPECT RESULT]:
a       d
3       11120436154190595086
[ACTUAL RESULT]:
a       d

[ERROR]
[SCRIPT   FILE]: cases/expression/case_when.sql
[ROW    NUMBER]: 116
[SQL STATEMENT]: SELECT 1 FROM t1 WHERE a=1 AND CASE 1 WHEN a THEN 1 ELSE 1 END;
[EXPECT RESULT]:
1
1
1
1
1
[ACTUAL RESULT]:
1
1

**Comment by m-schen** [comment]
fixed now.

**Comment by aressu1985** [comment]
the tage did note be removed

[sudong@mo-srv-128 matrixone]$ grep -r "#3298" test/cases/
test/cases/expression/case_when.sql:-- @bvt:issue#3298
test/cases/expression/case_when.sql:-- @bvt:issue#3298
[sudong@mo-srv-128 matrixone]$ git pul

**Comment by aressu1985** [comment]
fixed
