### ISSUE TITLE
[Bug]:  Implicit conversion failed from DOUBLE to DATETIME

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select cast('2000-01-01' as datetime(0))*1.1;
Operator '*' with parameters [DATETIME DOUBLE] will be implemented in future version.

**Comment by JinHai-CN** [comment]
A proper error message should be given.

**Comment by JinHai-CN** [comment]
The test case should be:

select cast('2000-01-01' as datetime(0))*1.1;

**Comment by domingozhang** [comment]
double/float to datetime is out of conversation table. need an error code in 0.6

**Comment by domingozhang** [comment]
DOUBLE to DATETIME will not support

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by daviszhen** [comment]
MO do not support the conversion DATETIME <=> DOUBLE base on the doc : https://doc.weixin.qq.com/sheet/e3_AdIAkQb_AEYGT3QVZBJQXqJghCjYF?scode=AJsA6gc3AA840KbtsHAAgAkgYHABU&tab=s8bwcy

We can close the issue.
