### ISSUE TITLE
[Bug]:  DATETIME cannot be converted to BIGINT in CAST 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3301]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT CAST(20220101 AS datetime(0)) BETWEEN 20220101 AND -1;
Operator 'cast' with parameters [BIGINT DATETIME] will be implemented in future version.

**Comment by JinHai-CN** [comment]
A proper error message should be given.

**Comment by domingozhang** [comment]
int to datetime is out of conversation table. error message will be provided in 0.6

**Comment by domingozhang** [comment]
from int to datetime/date/timestamp, will be discussed in future release

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by daviszhen** [comment]
BIGINT 不能转 DATETIME

**Comment by daviszhen** [comment]
MO do not support the conversion BIGINT=>DATETIME base on the doc : https://doc.weixin.qq.com/sheet/e3_AdIAkQb_AEYGT3QVZBJQXqJghCjYF?scode=AJsA6gc3AA840KbtsHAAgAkgYHABU&tab=s8bwcy

We can close the issue.

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.
