### ISSUE TITLE
[Bug]: some cte query results are not correct.   Test tools/infra structure issue due to non-deterministic limit 2. 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3302]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1、
drop table if exists t1;
create table t1(a int, b int, c int);
insert into t1 values(null,null,null),(2,3,4);

with qne as (select a from t1),
     qnm as (select a from t1),
     qnea as (select a from t1),
     qnma as (select a from t1)
select qne.a,qnm.a,alias1.a,alias2.a
from qne, qnm, qnea as alias1, qnma as alias2 limit 2;

[ERROR]
[SCRIPT   FILE]: cases/expression/cte.sql
[ROW    NUMBER]: 29
[SQL STATEMENT]: with qne as (select a from t1),
qnm as (select a from t1),
qnea as (select a from t1),
qnma as (select a from t1)
select qne.a,qnm.a,alias1.a,alias2.a
from qne, qnm, qnea as alias1, qnma as alias2 limit 2;
[EXPECT RESULT]:
a       a       a       a
2       null    2       null
null    null    2       null
[ACTUAL RESULT]:
a       a       a       a
null    null    null    null
null    null    null    2

**Comment by fengttt** [comment]
The result is correct, but non-deterministic due to limit 2.

**Comment by aressu1985** [comment]
but I really don't know how the test-tool should handle this or the similar case that has non-deterministic result,
and it is strange that the result of this case seems like deterministic, because I have run it servral times ,but the result never change
anyway,I will update the result to what the mo return

**Comment by aressu1985** [comment]
fixed
