### ISSUE TITLE
[Bug]: correlated columns not in filters (WHERE/HAVING) not yet supported

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/operator/is_operator.sql
[ROW    NUMBER]: 258
[SQL STATEMENT]: SELECT * from t2 where topic IN (SELECT SUM(topic) FROM t1);
[EXPECT RESULT]:
mot     topic   dt      pseudo
[ACTUAL RESULT]:
correlated columns in aggregate function not yet supported

**Comment by domingozhang** [comment]
correlated columns not in filters can be not supported in MO.
