### ISSUE TITLE
[Bug]: Comparison of row constructor and subquery not yet supported

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3308]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 70
[SQL STATEMENT]: SELECT a FROM t1 WHERE (1,2) > ANY (SELECT a FROM t1 WHERE b = 2);
[EXPECT RESULT]:
Operand should contain 1 column(s)
[ACTUAL RESULT]:
row constructor in ANY subquery not yet supported

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 78
[SQL STATEMENT]: SELECT a FROM t1 WHERE (1,2) = ANY (SELECT a FROM t1 WHERE b = 2);
[EXPECT RESULT]:
Operand should contain 2 column(s)
[ACTUAL RESULT]:
row constructor in ANY subquery not yet supported

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 84
[SQL STATEMENT]: SELECT a FROM t1 WHERE (1,2) <> ALL (SELECT a FROM t1 WHERE b = 2);
[EXPECT RESULT]:
Operand should contain 2 column(s)
[ACTUAL RESULT]:
row constructor in ANY subquery not yet supported

**Comment by aunjgr** [comment]
The row constructor version of ANY/SOME/ALL subquery accept only comparison operators. Row comparisons respect lexicographic order.

https://www.postgresql.org/docs/current/functions-comparisons.html#ROW-WISE-COMPARISON
https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html

**Comment by domingozhang** [comment]
same as #3309 , will be fixed in 0.6.0

**Comment by aunjgr** [comment]
conversion rules:

* `(a1, a2, a3) = (b1, b2, b3)` -> `a1 = b1 and a2 = b2 and a3 = b3`
* `(a1, a2, a3) <> (b1, b2, b3)` -> `a1 <> b1 or a2 <> b2 or a3 <> b3`
* `(a1, a2, a3) < (b1, b2, b3)` -> `a1 < b1 or (a1 = b1 and (a2 < b2 or (a2 = b2 and a3 < b3)))`
* `(a1, a2, a3) <= (b1, b2, b3)` -> `a1 < b1 or (a1 = b1 and (a2 < b2 or (a2 = b2 and a3 <= b3)))`
* `(a1, a2, a3) > (b1, b2, b3)` -> `a1 > b1 or (a1 = b1 and (a2 > b2 or (a2 = b2 and a3 > b3)))`
* `(a1, a2, a3) >= (b1, b2, b3)` -> `a1 > b1 or (a1 = b1 and (a2 > b2 or (a2 = b2 and a3 >= b3)))`

**Comment by aunjgr** [comment]
All 3308 tags has been removed or retagged to other issues.

**Comment by aressu1985** [comment]
mysql> DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected (0.01 sec)

mysql> DROP TABLE IF EXISTS t2;
Query OK, 0 rows affected (0.00 sec)

mysql> DROP TABLE IF EXISTS t3;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE t1 ( a int, b int );
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (1,1),(2,2),(3,3);
Query OK, 3 rows affected (0.00 sec)

mysql> 
mysql> SELECT a FROM t1 WHERE (1,2) > ANY (SELECT a FROM t1 WHERE b = 2);
ERROR 20301 (HY000): invalid input: subquery should return 2 columns
mysql> SELECT a FROM t1 WHERE (1,2) = ANY (SELECT a FROM t1 WHERE b = 2);
ERROR 20301 (HY000): invalid input: subquery should return 2 columns
mysql> SELECT a FROM t1 WHERE (1,2) <> ALL (SELECT a FROM t1 WHERE b = 2);
ERROR 20301 (HY000): invalid input: subquery should return 2 columns
