### ISSUE TITLE
[Bug]:Non-scalar subquery in non-root expressions are not supported

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3309]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 86
[SQL STATEMENT]: SELECT a FROM t1 WHERE (a,1) = ANY (SELECT a,1 FROM t1 WHERE b = 2);
[EXPECT RESULT]:
column "a" must appear in the GROUP BY clause or be used in an aggregate function
[ACTUAL RESULT]:
subquery must return only one column

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 124
[SQL STATEMENT]: select * from t1 where not (s1 < any (select s1 from t1));
[EXPECT RESULT]:
s1
2
[ACTUAL RESULT]:
"ANY" subquery as non-root expression not yet supported

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 141
[SQL STATEMENT]: select (select * from t1) = (select 1,2);
[EXPECT RESULT]:
(select * from t1) = (select 1,2)
null
[ACTUAL RESULT]:
subquery must return only one column

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 142
[SQL STATEMENT]: select (select 1,2) = (select * from t1);
[EXPECT RESULT]:
(select 1,2) = (select * from t1)
null
[ACTUAL RESULT]:
subquery must return only one column

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 144
[SQL STATEMENT]: select  (1,2) = ANY (select * from t1);
[EXPECT RESULT]:
(1,2) = ANY (select * from t1)
0
[ACTUAL RESULT]:
subquery must return only one column

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 145
[SQL STATEMENT]: select  (1,2) != ALL (select * from t1);
[EXPECT RESULT]:
(1,2) != ALL (select * from t1)
1
[ACTUAL RESULT]:
subquery must return only one column

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 145
[SQL STATEMENT]: select  (1,2) != ALL (select * from t1);
[EXPECT RESULT]:
(1,2) != ALL (select * from t1)
1
[ACTUAL RESULT]:
subquery must return only one column

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-any.sql
[ROW    NUMBER]: 252
[SQL STATEMENT]: SELECT * FROM t1 WHERE (a,b) = ANY (SELECT a, max(b) FROM t1 GROUP BY a);
[EXPECT RESULT]:
a       b
BBB     4
CCC     7
AAA     8
[ACTUAL RESULT]:
subquery must return only one column

**Comment by domingozhang** [comment]
Non-scalar subquery in non-root expressions will be supported in 0.6.9

**Comment by aunjgr** [comment]
@aressu1985 Please close this issue because the error cases are covered by #3308 and #3312

**Comment by aunjgr** [comment]
The cases have been retagged to #3308 and #3312.

**Comment by aunjgr** [comment]
@aressu1985  All cases had been retagged to #3308 and #3312. Pls close this issue.

**Comment by tianyahui-python** [comment]
@aressu1985 can close issue.

**Comment by aressu1985** [comment]
fixed
