### ISSUE TITLE
[Bug]: in/any/exists can not allowed to having expression

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3310]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 196
[SQL STATEMENT]: SELECT a FROM t1 GROUP BY a
HAVING a IN (SELECT c FROM t2
WHERE  EXISTS(SELECT e FROM t3 WHERE MAX(b)=e AND e <= d));
[EXPECT RESULT]:
a
2
3
[ACTUAL RESULT]:
aggregate functions not allowed here

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 199
[SQL STATEMENT]: SELECT a FROM t1 GROUP BY a
HAVING a IN (SELECT c FROM t2
WHERE  EXISTS(SELECT e FROM t3 WHERE MAX(b)=e AND e < d));
[EXPECT RESULT]:
a
2
[ACTUAL RESULT]:
aggregate functions not allowed here

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 203
[SQL STATEMENT]: SELECT a FROM t1 GROUP BY a
HAVING a IN (SELECT c FROM t2
WHERE MIN(b) < d AND
EXISTS(SELECT e FROM t3 WHERE MAX(b)=e AND e <= d));
[EXPECT RESULT]:
a
2
[ACTUAL RESULT]:
aggregate functions not allowed here

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 226
[SQL STATEMENT]: SELECT t1.a FROM t1 GROUP BY t1.a
HAVING t1.a > ALL(SELECT t2.c FROM t2
WHERE EXISTS(SELECT t3.e FROM t3
WHERE SUM(t1.a+t2.c) < t3.e/4));
[EXPECT RESULT]:
Invalid use of group function
[ACTUAL RESULT]:
aggregate functions not allowed here

**Comment by fengttt** [comment]
This is not a bug, max(b) = e is illegal.   Update result file.
