### ISSUE TITLE
[Bug]: Non-scalar subquery as non-root expression not yet supported

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3312]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 274
[SQL STATEMENT]: SELECT EXISTS(SELECT a FROM t1 WHERE b = 2 and a.a > t1.a) IS NULL from t1 a;
[EXPECT RESULT]:
EXISTS(SELECT a FROM t1 WHERE b = 2 and a.a > t1.a) IS NULL
0
0
0
[ACTUAL RESULT]:
EXISTS subquery as non-root expression not yet supported

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 275
[SQL STATEMENT]: SELECT EXISTS(SELECT a FROM t1 WHERE b = 2 and a.a < t1.a) IS NOT NULL from t1 a;
[EXPECT RESULT]:
EXISTS(SELECT a FROM t1 WHERE b = 2 and a.a < t1.a) IS NOT NULL
1
1
1
[ACTUAL RESULT]:
EXISTS subquery as non-root expression not yet supported

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 276
[SQL STATEMENT]: SELECT EXISTS(SELECT a FROM t1 WHERE b = 2 and a.a = t1.a) IS NULL from t1 a;
[EXPECT RESULT]:
EXISTS(SELECT a FROM t1 WHERE b = 2 and a.a = t1.a) IS NULL
0
0
0
[ACTUAL RESULT]:
EXISTS subquery as non-root expression not yet supported

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-exists.sql
[ROW    NUMBER]: 286
[SQL STATEMENT]: select 1.1 * exists(select * from t1);
[EXPECT RESULT]:
1.1 * exists(select * from t1)
1.1
[ACTUAL RESULT]:
EXISTS subquery as non-root expression not yet supported

**Comment by aunjgr** [comment]
Should implement MARK join to handle this case.

**Comment by domingozhang** [comment]
same issue as #3309

**Comment by aunjgr** [comment]
depends on #4290

**Comment by aunjgr** [comment]
Can be done in 0.7

**Comment by aunjgr** [comment]
No progress on this issue yet.

**Comment by aunjgr** [comment]
No progress yet

**Comment by aunjgr** [comment]
No progress yet.

**Comment by aunjgr** [comment]
No progress yet.

**Comment by aunjgr** [comment]
No progress yet

**Comment by aunjgr** [comment]
No progress yet

**Comment by aunjgr** [comment]
Supposed to be done this week.

**Comment by aunjgr** [comment]
Working on it.

**Comment by aunjgr** [comment]
PR merged.

**Comment by aressu1985** [comment]
fixed
