### ISSUE TITLE
[Bug]: char_length bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3313]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: select char_length('\n\t\r\b\0\_\%\\');
[EXPECT RESULT]:
char_length('\n\t\r\b\0\_\%\\')
10
[ACTUAL RESULT]:
char_length(
	
_%\)
8

**Comment by fengttt** [comment]
You have to type
```
select char_length('foobar\'');
Notice we escape ' using \'

Then our result is correct, please update result and resolve.

**Comment by iamlinjunhong** [comment]
The Preview's exhibition is a wrong sql so that let people misunderstand. Actually, We should to watch the Write' exhibition to get a right sql.

**Comment by iamlinjunhong** [comment]
The sql of this issue should be following:
<img width="1017" alt="截屏2022-07-01 下午4 12 21" src="https://user-images.githubusercontent.com/49111204/176853693-3aff88ef-c4af-4f07-955c-afa47fabc6d3.png">
