### ISSUE TITLE
[Bug]: Wrong error message for log func type

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3314]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: select log(2, null);
[EXPECT RESULT]:
log(2, null)
null
[ACTUAL RESULT]:
Function 'log' with parameters [BIGINT unexpected type: 0] will be implemented in future version.

[SQL STATEMENT]: select log(null,2);
[EXPECT RESULT]:
log(null,2)
null
[ACTUAL RESULT]:
Function 'log' with parameters [unexpected type: 0 BIGINT] will be implemented in future version.

[SQL STATEMENT]: select log(null,null);
[EXPECT RESULT]:
log(null,null)
null
[ACTUAL RESULT]:
Function 'log' with parameters [unexpected type: 0 unexpected type: 0] will be implemented in future version.

**Comment by daviszhen** [comment]
refresh expect result and move to 0.6

**Comment by m-schen** [comment]
log with 2 parameters do not implement it now.
only support log(param)

**Comment by dengn** [comment]
Tag it with #3608.
