### ISSUE TITLE
[Bug]: Wrong error message for floor func

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3315]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/function/func_math_floor.test
[ROW    NUMBER]: 171
[SQL STATEMENT]: select floor(123.342, null);
[EXPECT RESULT]:
floor(123.342, null)
null
[ACTUAL RESULT]:
the second argument of the round function must be an int64 constant

[ERROR]
[SCRIPT   FILE]: cases/function/func_math_floor.test
[ROW    NUMBER]: 173
[SQL STATEMENT]: select floor(null, null);
[EXPECT RESULT]:
floor(null, null)
null
[ACTUAL RESULT]:
the second argument of the round function must be an int64 constant

**Comment by daviszhen** [comment]
refresh expect result as actual result

**Comment by m-schen** [comment]
it's the right performance
