### ISSUE TITLE
[Bug]: interval result bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3319]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

create table t1 (a int, b varchar(10));
insert into t1 values (1, '2001-01-01'),(2, '2002-02-02'); 
select '2007-01-01' + interval a day from t1;
select b + interval a day from t1;
drop table t1;

[SQL STATEMENT]: select '2007-01-01' + interval a day from t1;
[EXPECT RESULT]:
'2007-01-01' + interval a day
2007-01-02
2007-01-03
[ACTUAL RESULT]:
2007-01-01 + interval(a, day)
2007-01-02
2007-01-02

[SQL STATEMENT]: select b + interval a day from t1;
[EXPECT RESULT]:
b + interval a day
2001-01-02
2002-02-04
[ACTUAL RESULT]:
b + interval(a, day)
2001-01-02
2002-02-03

**Comment by aressu1985** [comment]
fixed 

mysql> create table t1 (a int, b varchar(10));
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 values (1, '2001-01-01'),(2, '2002-02-02');
Query OK, 2 rows affected (0.01 sec)

mysql> select '2007-01-01' + interval a day from t1;
+-------------------------------+
| 2007-01-01 + interval(a, day) |
+-------------------------------+
| 2007-01-02 00:00:00.000000    |
| 2007-01-03 00:00:00.000000    |
+-------------------------------+
2 rows in set (0.00 sec)

mysql> select b + interval a day from t1;
+----------------------------+
| b + interval(a, day)       |
+----------------------------+
| 2001-01-02 00:00:00.000000 |
| 2002-02-04 00:00:00.000000 |
+----------------------------+
2 rows in set (0.00 sec)

mysql> drop table t1;
Query OK, 0 rows affected (0.00 sec)
