### ISSUE TITLE
[Bug]: result is error of the in-subquery sql

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3320]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1、[ERROR] 
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 10
[SQL STATEMENT]: SELECT 1 FROM (SELECT 1 as a) b WHERE 1 not IN (SELECT (SELECT a));
[EXPECT RESULT]: 
1
[ACTUAL RESULT]: 
1
1

2、
drop table if exists t1;
drop table if exists t2;
drop table if exists t3;
CREATE TABLE t1 (a int);
CREATE TABLE t2 (a int, b int);
CREATE TABLE t3 (b int NOT NULL);
INSERT INTO t1 VALUES (1), (2), (3), (4);
INSERT INTO t2 VALUES (1,10), (3,30);
SELECT * FROM t1 WHERE t1.a NOT IN (SELECT a FROM t2 LEFT JOIN t3 ON t2.b=t3.b WHERE t3.b IS NOT NULL OR t2.a > 10);

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 79
[SQL STATEMENT]: SELECT * FROM t1 WHERE t1.a NOT IN (SELECT a FROM t2 LEFT JOIN t3 ON t2.b=t3.b WHERE t3.b IS NOT NULL OR t2.a > 10);
[EXPECT RESULT]:
a
1
2
3
4
[ACTUAL RESULT]:
a

3、
drop table if exists t1;
drop table if exists t2;
CREATE TABLE t1(c INT);
CREATE TABLE t2(a INT, b INT);
INSERT INTO t2 VALUES (1, 10), (2, NULL);
INSERT INTO t1 VALUES (1), (3);

SELECT * FROM t2 WHERE b NOT IN (SELECT max(t.c) FROM t1, t1 t WHERE t.c>10);

[ERROR]   
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 128
[SQL STATEMENT]: SELECT * FROM t2 WHERE b NOT IN (SELECT max(t.c) FROM t1, t1 t WHERE t.c>10);
[EXPECT RESULT]: 
a       b
[ACTUAL RESULT]:
a       b
1       10

4、
DROP TABLE IF EXISTS t1;
drop table if exists t2;
CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2),(3);
CREATE TABLE t2 (a INT);
INSERT INTO t1 VALUES (1),(2),(3);
SELECT 1 FROM t1 WHERE t1.a NOT IN (SELECT 1 FROM t1, t2 WHERE 0);

[ERROR] 
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 795
[SQL STATEMENT]: SELECT 1 FROM t1 WHERE t1.a NOT IN (SELECT 1 FROM t1, t2 WHERE 0);
[EXPECT RESULT]:
1
1
1
1
[ACTUAL RESULT]: 
1
1

5、
DROP TABLE IF EXISTS t1;
drop table if exists t2;
create table t1 (oref char(4), grp int, ie int);
insert into t1 (oref, grp, ie) values ('aa', 10, 2),('aa', 10, 1),('aa', 20, NULL),('bb', 10, 3),('cc', 10, 4),('cc', 20, NULL),('ee', 10, NULL),('ee', 10, NULL),('ff', 20, 2),('ff', 20, 1);
create table t2 (oref char(4), a int);
insert into t2 values('ee', NULL),('bb', 2),('ff', 2),('cc', 3),('aa', 1),('dd', NULL),('bb', NULL);
select oref, a from t2 where a not in (select ie from t1 where oref=t2.oref);
select oref, a from t2 where a not in (select min(ie) from t1 where oref=t2.oref group by grp);
update t1 set ie=3 where oref='ff' and ie=1;
select oref, a from t2 where a not in (select min(ie) from t1 where oref=t2.oref group by grp);
select oref, a from t2 where a not in (select min(ie) from t1 where oref=t2.oref group by grp having min(ie) > 1);

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 922
[SQL STATEMENT]: select oref, a from t2 where a not in (select ie from t1 where oref=t2.oref);
[EXPECT RESULT]:
oref    a
bb      2
dd      null
[ACTUAL RESULT]:
oref    a
bb      2
cc      3

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 927
[SQL STATEMENT]: select oref, a from t2 where a not in (select min(ie) from t1 where oref=t2.oref group by grp);
[EXPECT RESULT]:
oref    a
bb      2
ff      2
dd      null
[ACTUAL RESULT]:
oref    a
bb      2
ff      2
cc      3

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 934
[SQL STATEMENT]: select oref, a from t2 where a not in (select min(ie) from t1 where oref=t2.oref group by grp);
[EXPECT RESULT]:
oref    a
bb      2
dd      null
[ACTUAL RESULT]:
oref    a
bb      2
cc      3

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 939
[SQL STATEMENT]: select oref, a from t2 where a not in (select min(ie) from t1 where oref=t2.oref group by grp having min(ie) > 1);
[EXPECT RESULT]:
oref    a
ee      null
bb      2
cc      3
aa      1
dd      null
[ACTUAL RESULT]:
oref    a
bb      2
cc      3
aa      1

6、
DROP TABLE IF EXISTS t1;
drop table if exists t2;
CREATE TABLE t1 (a int);
CREATE TABLE t2 (b int, PRIMARY KEY(b));
INSERT INTO t1 VALUES (1), (NULL), (4);
INSERT INTO t2 VALUES (3), (1),(2), (5), (4), (7), (6);
SELECT a FROM t1, t2 WHERE a=b AND (b NOT IN (SELECT a FROM t1));
SELECT a FROM t1, t2 WHERE a=b AND (b NOT IN (SELECT a FROM t1 WHERE a > 4));

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 979
[SQL STATEMENT]: SELECT a FROM t1, t2 WHERE a=b AND (b NOT IN (SELECT a FROM t1 WHERE a > 4));
[EXPECT RESULT]:
a
1
4
[ACTUAL RESULT]:
a

7、
DROP TABLE IF EXISTS t1;
drop table if exists t2;
CREATE TABLE t1 (id int);
CREATE TABLE t2 (id int PRIMARY KEY);
CREATE TABLE t3 (id int PRIMARY KEY, name varchar(10));
INSERT INTO t1 VALUES (2), (NULL), (3), (1);
INSERT INTO t2 VALUES (234), (345), (457);
INSERT INTO t3 VALUES (222,'bbb'), (333,'ccc'), (111,'aaa');
SELECT * FROM t1 WHERE t1.id NOT IN (SELECT t2.id FROM t2,t3  WHERE t3.name='xxx' AND t2.id=t3.id);
[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 989
[SQL STATEMENT]: SELECT * FROM t1 WHERE t1.id NOT IN (SELECT t2.id FROM t2,t3  WHERE t3.name='xxx' AND t2.id=t3.id);
[EXPECT RESULT]:
id
2
null
3
1
[ACTUAL RESULT]:
id

8、
ROP TABLE IF EXISTS t1;
drop table if exists t2;
drop table if exists t3;
CREATE TABLE parent (id int);
INSERT INTO parent VALUES (1), (2);
CREATE TABLE child (parent_id int, other int);
INSERT INTO child VALUES (1,NULL);

SELECT    p.id, c.parent_id
FROM      parent p
LEFT JOIN child  c
ON        p.id = c.parent_id
WHERE     c.parent_id NOT IN (
              SELECT parent_id
              FROM   child
              WHERE  parent_id = 3
          );

SELECT    p.id, c.parent_id
FROM      parent p
LEFT JOIN child  c
ON        p.id = c.parent_id
WHERE     c.parent_id IN (
              SELECT parent_id
              FROM   child
              WHERE  parent_id = 3
          );

SELECT    p.id, c.parent_id
FROM      parent p
LEFT JOIN child  c
ON        p.id = c.parent_id
WHERE     c.parent_id IN (
              SELECT parent_id
              FROM   child
              WHERE  parent_id = 3
          );

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 1073
[SQL STATEMENT]: SELECT    p.id, c.parent_id
FROM      parent p
LEFT JOIN child  c
ON        p.id = c.parent_id
WHERE     c.parent_id NOT IN (
SELECT parent_id
FROM   child
WHERE  parent_id = 3
);
[EXPECT RESULT]:
id      parent_id
1       1
2       null
[ACTUAL RESULT]:
id      parent_id

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 1083
[SQL STATEMENT]: SELECT    p.id, c.parent_id
FROM      parent p
LEFT JOIN child  c
ON        p.id = c.parent_id
WHERE     c.parent_id IN (
SELECT parent_id
FROM   child
WHERE  parent_id = 3
);
[EXPECT RESULT]:
id      parent_id
1       1
2       null
[ACTUAL RESULT]:
id      parent_id

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 1093
[SQL STATEMENT]: SELECT    p.id, c.parent_id
FROM      parent p
LEFT JOIN child  c
ON        p.id = c.parent_id
WHERE     c.parent_id IN (
SELECT parent_id
FROM   child
WHERE  parent_id = 3
);
[EXPECT RESULT]:
id      parent_id
1       1
2       null
[ACTUAL RESULT]:
id      parent_id

**Comment by ouyuanning** [comment]
4、SELECT 1 FROM t1 WHERE t1.a NOT IN (SELECT 1 FROM t1, t2 WHERE 0)

**Comment by ouyuanning** [comment]
7、these two sql:

**Comment by ouyuanning** [comment]
1、error
SELECT 1 FROM (SELECT 1 as a) b WHERE 1 not IN (SELECT (SELECT a));
move to #3556

**Comment by ouyuanning** [comment]
select * from t2, t3
where
    t2.a < 10 and
    t3.a+1 = 2 and
    t3.a in (select t1.b from t1
                 where t1.a+1=t1.a+1 and
                       t1.a < (select t4.a+10
                                  from t4, t5 limit 2));

move to #3570

**Comment by aressu1985** [comment]
fixed
