### ISSUE TITLE
[Bug]: unsupported eval expr '&{rel_pos:1 depth:1 }'

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3323]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/subquery/subquery-with-in.sql
[ROW    NUMBER]: 120
[SQL STATEMENT]: SELECT * FROM c WHERE `int_key` IN (SELECT `int_nokey`);
[EXPECT RESULT]:
int_nokey       int_key
9       9
0       0
5       5
0       0
[ACTUAL RESULT]:
unsupported eval expr '&{rel_pos:1 depth:1 }'

**Comment by fengttt** [comment]
Need better error message
