### ISSUE TITLE
[Bug]: month func result wrong

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3326]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: SELECT MONTH('2015-09.30') as MONTH;
[EXPECT RESULT]:
MONTH
9
[ACTUAL RESULT]:
month
null

[SQL STATEMENT]: SELECT MONTH('2015-09.30 12') as MONTH;
[EXPECT RESULT]:
MONTH
9
[ACTUAL RESULT]:
month
null

**Comment by bbbearxyz** [comment]
I think we can only support date/datetime format string as arg, don't support other format

**Comment by aressu1985** [comment]
fixed


Database changed
mysql> SELECT MONTH('2015-09.30') as MONTH;
+-------+
| month |
+-------+
|     9 |
+-------+
1 row in set (0.00 sec)

mysql> SELECT MONTH('2015-09.30 12') as MONTH;
+-------+
| month |
+-------+
|     9 |
+-------+
1 row in set (0.00 sec)
