### ISSUE TITLE
[Enhancement]: utc_timestamp manual testing

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3329]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
utc_timestamp() is a constantly changing function, we cannot test it by fixing values. 

[SQL STATEMENT]: select unix_timestamp(utc_timestamp());
[EXPECT RESULT]:
unix_timestamp(utc_timestamp())
1655148590
[ACTUAL RESULT]:
unix_timestamp(utc_timestamp())
1656024560
```

**Comment by fengttt** [comment]
Timezone related.

**Comment by JinHai-CN** [comment]
I also can't find the issue in the case files. @dengn

**Comment by dengn** [comment]
#1871 timezone support as a 0.6 feature

**Comment by goodMan-code** [comment]
This Enhancement has done, can be closed pls

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by aressu1985** [comment]
need a pr to remove tag and remove this case

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by aressu1985** [comment]
done

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by sukki37** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.
