### ISSUE TITLE
[Bug]: select 1 gets wrong result 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3331]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

CREATE TABLE t1 (a TIMESTAMP);
INSERT INTO t1 select (utc_timestamp());
INSERT INTO t1 select (utc_timestamp());
SELECT 1 FROM t1 ORDER BY 1;
DROP TABLE t1;

### Expected Behavior

[SQL STATEMENT]: SELECT 1 FROM t1 ORDER BY 1;
[EXPECT RESULT]:
1
1
1
[ACTUAL RESULT]:
1
1

**Comment by fengttt** [comment]
What is wrong?      I cannot see anything :)

**Comment by dengn** [comment]
> no error:
> 
> ```
> mysql>  SELECT 1 FROM t1 ORDER BY 1;
> +------+
> | 1    |
> +------+
> |    1 |
> |    1 |
> +------+
> ```

MO test result in:

mysql> SELECT 1 FROM t1 ORDER BY 1;
+------+
| 1    |
+------+
|    1 |
+------+

**Comment by yingfeng** [comment]
> > no error:
> > ```
> > mysql>  SELECT 1 FROM t1 ORDER BY 1;
> > +------+
> > | 1    |
> > +------+
> > |    1 |
> > |    1 |
> > +------+
> > ```
> 
> MO test result is:
> 
> mysql> SELECT 1 FROM t1 ORDER BY 1; +------+ | 1 | +------+ | 1 | +------+

mo test result is what i listed above.

**Comment by dengn** [comment]
> > > no error:
> > > ```
> > > mysql>  SELECT 1 FROM t1 ORDER BY 1;
> > > +------+
> > > | 1    |
> > > +------+
> > > |    1 |
> > > |    1 |
> > > +------+
> > > ```
> > 
> > 
> > MO test result is:
> > mysql> SELECT 1 FROM t1 ORDER BY 1; +------+ | 1 | +------+ | 1 | +------+
> 
> mo test result is what i listed above.

OK. it looks like the latest version's result is correct now.
