### ISSUE TITLE
[Bug]: year function result error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3332]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: cases/function/func_datetime_year.test
[ROW    NUMBER]: 21
[SQL STATEMENT]: SELECT YEAR('2015-09.30') as year;
[EXPECT RESULT]:
year
2015
[ACTUAL RESULT]:
year
null

[ERROR]
[SCRIPT   FILE]: cases/function/func_datetime_year.test
[ROW    NUMBER]: 23
[SQL STATEMENT]: SELECT YEAR('2015-09.30 12') as year;
[EXPECT RESULT]:
year
2015
[ACTUAL RESULT]:
year
null

[ERROR]
[SCRIPT   FILE]: cases/function/func_datetime_year.test
[ROW    NUMBER]: 27
[SQL STATEMENT]: SELECT YEAR("2015-09-10")- YEAR("2016-04-24");
[EXPECT RESULT]:
YEAR("2015-09-10")- YEAR("2016-04-24")
-1
[ACTUAL RESULT]:
year(2015-09-10) - year(2016-04-24)
65535

[ERROR]
[SCRIPT   FILE]: cases/function/func_datetime_year.test
[ROW    NUMBER]: 29
[SQL STATEMENT]: SELECT YEAR("2015-09-10")*YEAR("2016-04-24");
[EXPECT RESULT]:
YEAR("2015-09-10")*YEAR("2016-04-24")
4062240
[ACTUAL RESULT]:
year(2015-09-10) * year(2016-04-24)
64544

**Comment by aressu1985** [comment]
fixed

mysql>  SELECT YEAR('2015-09.30') as year;
+------+
| year |
+------+
| 2015 |
+------+
1 row in set (0.00 sec)

mysql> SELECT YEAR('2015-09.30 12') as year;
+------+
| year |
+------+
| 2015 |
+------+
1 row in set (0.00 sec)

mysql> SELECT YEAR("2015-09-10")- YEAR("2016-04-24");
+-------------------------------------+
| year(2015-09-10) - year(2016-04-24) |
+-------------------------------------+
|                                  -1 |
+-------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT YEAR("2015-09-10")*YEAR("2016-04-24");
+-------------------------------------+
| year(2015-09-10) * year(2016-04-24) |
+-------------------------------------+
|                             4062240 |
+-------------------------------------+
1 row in set (0.00 sec)

mysql>
