### ISSUE TITLE
[Feature Request]: insert into with expression support 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3333]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

CREATE TABLE t (i1 INT,
d1 DOUBLE,
e2 DECIMAL(5,2));
INSERT INTO t VALUES ( 6,    6.0,  10.0/3),
( null, 9.0,  10.0/3),
( 1,    null, 10.0/3),
( 2,    2.0,  null  );

[SQL STATEMENT]: INSERT INTO t VALUES ( 6,    6.0,  10.0/3),
( null, 9.0,  10.0/3),
( 1,    null, 10.0/3),
( 2,    2.0,  null  );
[EXPECT RESULT]:

[ACTUAL RESULT]:
Data truncation: unexpected return type 'DECIMAL64' for binary expression '3' for column 'e2' at row 0

**Comment by fengttt** [comment]
Error message is more or less OK, punt to 0.6

**Comment by dengn** [comment]
rename to a feature request for 0.6

**Comment by ouyuanning** [comment]
same as #2338  #3202 #3355

**Comment by goodMan-code** [comment]
This Feature Request has done, close it pls

**Comment by aressu1985** [comment]
fixed
