### ISSUE TITLE
[Bug]: bit_and, bit_or and bit_xor result error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3343]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

CREATE TABLE t1 (a int, b int);
INSERT INTO t1 VALUES (1,null);
INSERT INTO t1 VALUES (1,null);
INSERT INTO t1 VALUES (2,null);
select a, BIT_AND(b), BIT_OR(b), BIT_XOR(b) from t1 group by a;

[SQL STATEMENT]: select a, BIT_AND(b), BIT_OR(b), BIT_XOR(b) from t1 group by a;
[EXPECT RESULT]:
a	BIT_AND(b)	BIT_OR(b)	BIT_XOR(b)
1	18446744073709551615	0	0
2	18446744073709551615	0	0
[ACTUAL RESULT]:
a	bit_and(b)	bit_or(b)	bit_xor(b)
1	null	null	null
2	null	null	null

CREATE TABLE t1 (a int, b int);
select count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1;
select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
insert into t1 values (1,null);
select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
insert into t1 values (1,null);
insert into t1 values (2,null);
select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
insert into t1 values (2,1);
select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
insert into t1 values (3,1);
select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
drop table t1;

[ERROR]
[SCRIPT   FILE]: cases/function/func_aggr_avg.test
[ROW    NUMBER]: 159
[SQL STATEMENT]: select count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1;
[EXPECT RESULT]:
count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
0	null	null	null	null	null	18446744073709551615	0
[ACTUAL RESULT]:
count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
0	null	null	null	null	null	null	null

[ERROR]
[SCRIPT   FILE]: cases/function/func_aggr_avg.test
[ROW    NUMBER]: 162
[SQL STATEMENT]: select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
[EXPECT RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	18446744073709551615	0
[ACTUAL RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	null	null

[ERROR]
[SCRIPT   FILE]: cases/function/func_aggr_avg.test
[ROW    NUMBER]: 165
[SQL STATEMENT]: select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
[EXPECT RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	18446744073709551615	0
2	0	null	null	null	null	null	18446744073709551615	0
[ACTUAL RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	null	null
2	0	null	null	null	null	null	null	null

[ERROR]
[SCRIPT   FILE]: cases/function/func_aggr_avg.test
[ROW    NUMBER]: 167
[SQL STATEMENT]: select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
[EXPECT RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	18446744073709551615	0
2	1	1	1.0000	0.0	1	1	1	1
[ACTUAL RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	null	null
2	1	1	1.0	0.0	0	1	0	1

[ERROR]
[SCRIPT   FILE]: cases/function/func_aggr_avg.test
[ROW    NUMBER]: 169
[SQL STATEMENT]: select a,count(b), sum(b), avg(b), std(b), min(b), max(b), bit_and(b), bit_or(b) from t1 group by a;
[EXPECT RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	18446744073709551615	0
2	1	1	1.0000	0.0	1	1	1	1
3	1	1	1.0000	0.0	1	1	1	1
[ACTUAL RESULT]:
a	count(b)	sum(b)	avg(b)	std(b)	min(b)	max(b)	bit_and(b)	bit_or(b)
1	0	null	null	null	null	null	null	null
2	1	1	1.0	0.0	0	1	0	1
3	1	1	1.0	0.0	1	1	1	1

**Comment by fengttt** [comment]
I think this is due to init value of agg function.   Even the expected file result seems wrong.

**Comment by nnsgmsone** [comment]
The behaviour is now the same as pgsql, mysql's behaviour is more peculiar and I can rewrite it to be compatible if I need to be.

**Comment by dengn** [comment]
> The behaviour is now the same as pgsql, mysql's behaviour is more peculiar and I can rewrite it to be compatible if I need to be.

We'll take the MO current results. Please update the #3343 case expected results before assigning back.
