### ISSUE TITLE
[Bug]: Result of number without table is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3345]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select +9999999999999999999,-9999999999999999999;
-8446744073709551617    8446744073709551617

**Comment by iamlinjunhong** [comment]
#2945
