### ISSUE TITLE
[Bug]: Range of bigint is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3349]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 (a bigint unsigned not null, primary key(a));
insert into t1 values (18446744073709551615), (0xFFFFFFFFFFFFFFFE), (18446744073709551613), (18446744073709551612);
select * from t1;
select * from t1 where a=18446744073709551615;
Empty set (0.00 sec)

### Expected Behavior

select * from t1 where a=18446744073709551615;
a
18446744073709551615

**Comment by yingfeng** [comment]
It seems the upper bound of unsigned bigint right now is `0x7FFFFFFFFFFFFFFF` which is really a bug
