### ISSUE TITLE
[Bug]: result of SHOW COLUMN is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3350]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 (id int not null, str **char**(10),name varchar(10));
show columns from t1;
Field   Type    Null    Key     Default Comment
id      INT     NO              NULL
str     **VARCHAR**    NO              NULL
name    VARCHAR NO              NULL

**Comment by aressu1985** [comment]
fixed
