### ISSUE TITLE
[Bug]: the result only contain one column when the para of func any_value is a tabel column

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3353]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

some examples are as followings:

[ERROR]
[SCRIPT   FILE]: cases/function/func_anyvalue.test
[ROW    NUMBER]: 56
[SQL STATEMENT]: select any_value(a) from t1;
[EXPECT RESULT]:
any_value(a)
1
71
1
1
[ACTUAL RESULT]:
any_value(a)
1

[ERROR]
[SCRIPT   FILE]: cases/function/func_anyvalue.test
[ROW    NUMBER]: 57
[SQL STATEMENT]: select any_value(b) from t1;
[EXPECT RESULT]:
any_value(b)
1
1
1
71
[ACTUAL RESULT]:
any_value(b)
1

[ERROR]
[SCRIPT   FILE]: cases/function/func_anyvalue.test
[ROW    NUMBER]: 58
[SQL STATEMENT]: select any_value(c) from t1;
[EXPECT RESULT]:
any_value(c)
2
2
21
2
[ACTUAL RESULT]:
any_value(c)
2

[ERROR]
[SCRIPT   FILE]: cases/function/func_anyvalue.test
[ROW    NUMBER]: 59
[SQL STATEMENT]: select any_value(d) from t1;
[EXPECT RESULT]:
any_value(d)
43
34
4
34
[ACTUAL RESULT]:
any_value(d)
43

[ERROR]
[SCRIPT   FILE]: cases/function/func_anyvalue.test
[ROW    NUMBER]: 60
[SQL STATEMENT]: select any_value(e) from t1;
[EXPECT RESULT]:
any_value(e)
5
5
54
5
[ACTUAL RESULT]:
any_value(e)
5

[ERROR]
[SCRIPT   FILE]: cases/function/func_anyvalue.test
[ROW    NUMBER]: 61
[SQL STATEMENT]: select any_value(f) from t1;
[EXPECT RESULT]:
any_value(f)
35.5
5.5
53.5
5.5
[ACTUAL RESULT]:
any_value(f)
35.5

**Comment by fengttt** [comment]
This seems not a bug -- 0.5 result is correct.   Please update result file and resolve.

**Comment by aressu1985** [comment]
fixed
