### ISSUE TITLE
[Question]: possible issues we may encounter when parsing literal value in sql queries directly to decimal

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#3354]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1: float number and decimal are essentially different domains, for example, "inf", "+inf", "NaN" are valid float numbers, whereas invalid in decimal
2: float number has a bigger range than decimal
3: by using Golang's ParseFloat standard library, hexadecimal notation is also supported whereas our decimal parser won't

**Comment by broccoliSpicy** [comment]
I guess question 1 is trivial since our parse doesn't tokenize "inf", "-inf", "nan" as float anyway

**Comment by fengttt** [comment]
done
