### ISSUE TITLE
[Bug]: Function expression in INSERT statement is not implemented

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3355]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert INTO t1 (id,a) VALUES
(1,0),  
(2,CAST(0x7FFFFFFFFFFFFFFF AS UNSIGNED)),
(3,CAST(0x8000000000000000 AS UNSIGNED)),
(4,CAST(0xFFFFFFFFFFFFFFFF AS UNSIGNED));
Data truncation: Function expression in INSERT statement value list will be supported in future version. for column 'a' at row 1

**Comment by JinHai-CN** [comment]
0.6 will support function expression in insert statement.

**Comment by domingozhang** [comment]
It will implemented in 0.6

**Comment by ouyuanning** [comment]
same as #2338

**Comment by tianyahui-python** [comment]
<img width="1037" alt="截屏2022-10-29 22 52 12" src="https://user-images.githubusercontent.com/39303074/198838149-cf8ce280-d797-40d7-9c3b-6200f0557698.png">

**Comment by tianyahui-python** [comment]
@domingozhang can close issue.
