### ISSUE TITLE
[Bug]: Only bool expression can be used as filter condition

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3356]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT * FROM t1 WHERE IF(a AND 1, 0, 1);
Only bool expression can be used as filter condition.

**Comment by JinHai-CN** [comment]
IF will not return bool value. So result need to update.

**Comment by daviszhen** [comment]
refresh the expect result as the actual result.

**Comment by m-schen** [comment]
we will try to do type convert when the filter condition is not the bool expression now.

**Comment by domingozhang** [comment]
fixed
