### ISSUE TITLE
[Bug]: ERROR like <strconv.ParseInt: parsing "10 ": invalid syntax> need to be optimized

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3360]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]   
[SCRIPT   FILE]: cases/function/func_cast.test
[ROW    NUMBER]: 3
[SQL STATEMENT]: select CAST('10 ' as unsigned integer);
[EXPECT RESULT]:
CAST('10 ' as unsigned integer)
10
[ACTUAL RESULT]:
strconv.ParseInt: parsing "10 ": invalid syntax

[ERROR]   
[SCRIPT   FILE]: cases/function/func_cast.test
[ROW    NUMBER]: 4
[SQL STATEMENT]: select CAST('10x' as unsigned integer);
[EXPECT RESULT]:
CAST('10x' as unsigned integer)
10
[ACTUAL RESULT]:
strconv.ParseInt: parsing "10x": invalid syntax

**Comment by JinHai-CN** [comment]
'10 ' can be trimmed as '10', '10x' will let to proper an error message.

**Comment by fengttt** [comment]
Both '10 ' and '10x' should be an error.   However, seems we return 0 rows.

**Comment by aressu1985** [comment]
fxed

mysql> select CAST('10 ' as unsigned integer);
+-------------------------------+
| cast(10  as integer unsigned) |
+-------------------------------+
|                            10 |
+-------------------------------+
1 row in set (0.00 sec)

mysql> select CAST('10x' as unsigned integer);
ERROR 1105 (HY000): Can't cast '10x' as type of unsigned integer
