### ISSUE TITLE
[Bug]: Data truncation failed for decimal

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3364]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t1;
create table t1 (a decimal(29,0) not null, primary key(a));
insert into t1 values (18446744073709551615), (0xFFFFFFFFFFFFFE), (18446744073709551613.0000000), (18446744073709551612.0000000001);
Data truncation: Incorrect DECIMAL128 value: '0xfffffffffffffe' for column 'a' at row 1

**Comment by iamlinjunhong** [comment]
Need to support Hexadecimal number convert into decimal

**Comment by broccoliSpicy** [comment]
decimal don't support hexadecimal notations
