### ISSUE TITLE
[Bug]: Precision of double is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3366]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t_double(id double(30,1));
INSERT INTO t_double VALUES (1.19),(1.11), (2);
SELECT id, id = 1.1 FROM t_double;
id      id = 1.1
1.19    false
1.11    false
2.0     false

### Expected Behavior

id      id = 1.1
1.2     false
1.1     true
2.0     false

**Comment by florashi181** [comment]
discuss more about this feature @domingozhang

**Comment by qingxinhome** [comment]
Wait for solution discussion results. @domingozhang

**Comment by qingxinhome** [comment]
Wait for solution discussion results.

**Comment by qingxinhome** [comment]
Not resolved yet

**Comment by qingxinhome** [comment]
Not resolved yet

**Comment by qingxinhome** [comment]
Not resolved yet

**Comment by qingxinhome** [comment]
Not resolved yet

**Comment by domingozhang** [comment]
try to fix in 0.7

**Comment by domingozhang** [comment]
fixed

SELECT id, id = 1.1 FROM t_double;
+------+----------+
| id   | id = 1.1 |
+------+----------+
|  1.2 | false    |
|  1.1 | false    |
|    2 | false    |
+------+----------+

**Comment by fengttt** [comment]
Check if it is really fixed, then close.

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by domingozhang** [comment]
with bvt label. will remove related cases in batch and close them

**Comment by matrix-meow** [comment]
Hello @domingozhang. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by domingozhang** [comment]
will remove bvt tag
