### ISSUE TITLE
[Bug]: Aggregate function AVG different data type support 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3370]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'avg' with parameters [DATE] will be implemented in future version.
Function 'avg' with parameters [DATETIME] will be implemented in future version.
Function 'avg' with parameters [TIMESTAMP] will be implemented in future version.
Function 'avg' with parameters [VARCHAR] will be implemented in future version.
Operator '=' with parameters [VARCHAR DOUBLE] will be implemented in future version.
Operator '=' with parameters [DECIMAL64 DOUBLE] will be implemented in future version.
Operator '+' with parameters [DOUBLE VARCHAR] will be implemented in future version.

[ERROR]
[SCRIPT   FILE]: cases/function/func_aggr_avg.test
[ROW    NUMBER]: 89
[SQL STATEMENT]: select if(1>2,any_value(a),avg(a)) from t1;
[EXPECT RESULT]:
if(1>2,any_value(a),avg(a))
1.5000
[ACTUAL RESULT]:
parameter types of cast function do not match

**Comment by JinHai-CN** [comment]
if this issue is only about AVG function, these four types won't be supported by AVG.

**Comment by daviszhen** [comment]
unroslved:
Function 'avg' with parameters [DATE] will be implemented in future version.
Function 'avg' with parameters [DATETIME] will be implemented in future version.
Function 'avg' with parameters [TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
Only solve:Operator '=' with parameters [VARCHAR DOUBLE] will be implemented in future version.
Operator '=' with parameters [DECIMAL64 DOUBLE] will be implemented in future version.
Operator '+' with parameters [DOUBLE VARCHAR] will be implemented in future version.

**Comment by m-schen** [comment]
Aggregate functions do not do type conversions and are entirely based on what type we support.

**Comment by fengttt** [comment]
@dengn I have verified that at this moment, all #3370 tags are agg functions.    Asking approval to move to 0.6.

**Comment by sukki37** [comment]
@m-schen any updates?

**Comment by m-schen** [comment]
‘=’ is ok. and 'avg(date), avg(datetime), avg(timestamp)' is lack.
I have check with @domingozhang that 
there is no relevant demand at present, and we will do it when necessary.

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @dengn. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by m-schen** [comment]
we removed the confused case.
after pr, it can be closed.

**Comment by m-schen** [comment]
你是真的🐮

**Comment by sukki37** [comment]
> 你是真的🐮

Assign the issue to who opened it if it has been fixed.
