### ISSUE TITLE
[Bug]: CONCAT_WS doesn't work properly

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3372]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SELECT CONCAT_WS('My', NULL, 'QL');
Function 'concat_ws' with parameters [VARCHAR unexpected type: 0 VARCHAR] will be implemented in future version.

### Expected Behavior

QL

**Comment by JinHai-CN** [comment]
mysql> SELECT CONCAT_WS('My', NULL, 'QL');
+-------------------------+
| concat_ws(My, null, QL) |
+-------------------------+
| QL                      |
+-------------------------+
1 row in set (0.00 sec)

**Comment by aressu1985** [comment]
mysql> -- @bvt:issue#3372
mysql> SELECT CONCAT_WS('My', 'S', 'QL');
+----------------------+
| concat_ws(My, S, QL) |
+----------------------+
| SMyQL                |
+----------------------+
1 row in set (0.00 sec)

mysql> SELECT CONCAT_WS('My', NULL, 'QL');
+-------------------------+
| concat_ws(My, null, QL) |
+-------------------------+
| QL                      |
+-------------------------+
1 row in set (0.00 sec)

mysql> -- @bvt:issue

**Comment by aressu1985** [comment]
fixed
