### ISSUE TITLE
[Bug]: Aggregate function Bit_And, Bit_Or, Bit_Xor data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3373]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

[SQL STATEMENT]: SELECT bit_and(null), bit_or(null), bit_xor(null);
[EXPECT RESULT]:
bit_and(null)	bit_or(null)	bit_xor(null)
18446744073709551615	0	0
[ACTUAL RESULT]:
Function 'bit_and' with parameters [unexpected type: 0] will be implemented in future version.

Function 'bit_and' with parameters [DECIMAL128] will be implemented in future version.
Function 'bit_and' with parameters [DATE] will be implemented in future version.
Function 'bit_and' with parameters [DATETIME] will be implemented in future version.
Function 'bit_and' with parameters [TIMESTAMP] will be implemented in future version.
Function 'bit_and' with parameters [VARCHAR] will be implemented in future version.

Function 'bit_or' with parameters [DECIMAL128] will be implemented in future version.
Function 'bit_or' with parameters [DATE] will be implemented in future version.
Function 'bit_or' with parameters [DATETIME] will be implemented in future version.
Function 'bit_or' with parameters [TIMESTAMP] will be implemented in future version.
Function 'bit_or' with parameters [VARCHAR] will be implemented in future version.

Function 'bit_xor' with parameters [DECIMAL128] will be implemented in future version.
Function 'bit_xor' with parameters [DATE] will be implemented in future version.
Function 'bit_xor' with parameters [DATETIME] will be implemented in future version.
Function 'bit_xor' with parameters [TIMESTAMP] will be implemented in future version.
Function 'bit_xor' with parameters [VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
should solve: null parameter
Function 'bit_and' with parameters [unexpected type: 0] will be implemented in future version.

decimal => bigint?
Function 'bit_or' with parameters [DECIMAL128] will be implemented in future version.
Function 'bit_and' with parameters [DECIMAL128] will be implemented in future version.
Function 'bit_xor' with parameters [DECIMAL128] will be implemented in future version
varchar => bigint?
Function 'bit_and' with parameters [VARCHAR] will be implemented in future version.
Function 'bit_or' with parameters [VARCHAR] will be implemented in future version.

Do not support date/datetime/timestamp in aggregation:

Function 'bit_and' with parameters [DATE] will be implemented in future version.
Function 'bit_and' with parameters [DATETIME] will be implemented in future version.
Function 'bit_and' with parameters [TIMESTAMP] will be implemented in future version.
Function 'bit_or' with parameters [DATE] will be implemented in future version.
Function 'bit_or' with parameters [DATETIME] will be implemented in future version.
Function 'bit_or' with parameters [TIMESTAMP] will be implemented in future version.
Function 'bit_xor' with parameters [DATE] will be implemented in future version.
Function 'bit_xor' with parameters [DATETIME] will be implemented in future version.
Function 'bit_xor' with parameters [TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
@m-schen says that the implicit conversion will not happen in the aggregation function.
