### ISSUE TITLE
[Bug]: Aggregate function count data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3374]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Operator '>=' with parameters [VARCHAR BIGINT] will be implemented in future version.
Operator '=' with parameters [VARCHAR BIGINT] will be implemented in future version.
Function 'std' with parameters [DECIMAL64] will be implemented in future version.
Function 'variance' with parameters [DECIMAL64] will be implemented in future version.

**Comment by daviszhen** [comment]
solved:
Operator '>=' with parameters [VARCHAR BIGINT] will be implemented in future version.
Operator '=' with parameters [VARCHAR BIGINT] will be implemented in future version.
Function 'std' with parameters [DECIMAL64] will be implemented in future version.
Function 'variance' with parameters [DECIMAL64] will be implemented in future version.
