### ISSUE TITLE
[Bug]: Aggregate function std data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3375]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'std' with parameters [unexpected type: 0] will be implemented in future version.
Function 'stddev_pop' with parameters [unexpected type: 0] will be implemented in future version.
Function 'std' with parameters [DECIMAL128] will be implemented in future version.
Function 'std' with parameters [DATE] will be implemented in future version.
Function 'std' with parameters [DATETIME] will be implemented in future version.
Function 'std' with parameters [TIMESTAMP] will be implemented in future version.
Function 'std' with parameters [VARCHAR] will be implemented in future version.
Function 'stddev_pop' with parameters [DECIMAL128] will be implemented in future version.
Function 'stddev_pop' with parameters [DATE] will be implemented in future version.
Function 'stddev_pop' with parameters [DATETIME] will be implemented in future version.
Function 'stddev_pop' with parameters [TIMESTAMP] will be implemented in future version.
Function 'stddev_pop' with parameters [VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
should solve: null parameter
Function 'std' with parameters [unexpected type: 0] will be implemented in future version.
Function 'stddev_pop' with parameters [unexpected type: 0] will be implemented in future version.
Function 'std' with parameters [VARCHAR] will be implemented in future version.      (implicit conversion varchar => float)

do not support implicit conversion decimal => double:
Function 'std' with parameters [DECIMAL128] will be implemented in future version.
Function 'stddev_pop' with parameters [DECIMAL128] will be implemented in future version.
Function 'stddev_pop' with parameters [VARCHAR] will be implemented in future version.

do not date/datetime/timestamp in aggregation:
Function 'std' with parameters [DATE] will be implemented in future version.
Function 'std' with parameters [DATETIME] will be implemented in future version.
Function 'std' with parameters [TIMESTAMP] will be implemented in future version.
Function 'stddev_pop' with parameters [DATE] will be implemented in future version.
Function 'stddev_pop' with parameters [DATETIME] will be implemented in future version.
Function 'stddev_pop' with parameters [TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
@m-schen says that the implicit conversion will not happen in the aggregation function.

**Comment by aressu1985** [comment]
mysql> create table t1(a tinyint, b SMALLINT, c BIGINT, d INT, e BIGINT, f FLOAT, g DOUBLE, h decimal(38,19), i DATE, k datetime, l TIMESTAMP, m char(255), n varchar(255));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values(1, 1, 2, 43, 5, 35.5, 31.133, 14.314, "2012-03-10", "2012-03-12 10:03:12", "2022-03-12 13:03:12", "ab23c", "d5cf");
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values(71, 1, 2, 34, 5, 5.5, 341.13, 15.314, "2012-03-22", "2013-03-12 10:03:12", "2032-03-12 13:04:12", "abr23c", "3dcf");
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values(1, 1, 21, 4, 54, 53.5, 431.13, 14.394, "2011-03-12", "2015-03-12 10:03:12", "2002-03-12 13:03:12", "afbc", "dct5f");
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1 values(1, 71, 2, 34, 5, 5.5, 31.313, 124.314, "2012-01-12", "2019-03-12 10:03:12", "2013-03-12 13:03:12", "3abd1c", "dcvf");
Query OK, 1 row affected (0.00 sec)

mysql> select std(a) from t1;
+-------------------+
| std(a)            |
+-------------------+
| 30.31088913245535 |
+-------------------+
1 row in set (0.00 sec)

mysql> select std(b) from t1;
+-------------------+
| std(b)            |
+-------------------+
| 30.31088913245535 |
+-------------------+
1 row in set (0.00 sec)

mysql> select std(c) from t1;
+-------------------+
| std(c)            |
+-------------------+
| 8.227241335952167 |
+-------------------+
1 row in set (0.00 sec)

mysql> select std(d) from t1;
+------------------+
| std(d)           |
+------------------+
| 14.7542366796795 |
+------------------+
1 row in set (0.00 sec)

mysql> select std(e) from t1;
+-------------------+
| std(e)            |
+-------------------+
| 21.21762239271875 |
+-------------------+
1 row in set (0.01 sec)

mysql> select std(f) from t1;
+--------------------+
| std(f)             |
+--------------------+
| 20.512191496766015 |
+--------------------+
1 row in set (0.00 sec)

mysql> select std(g) from t1;
+--------------------+
| std(g)             |
+--------------------+
| 180.28380047095192 |
+--------------------+
1 row in set (0.00 sec)
