### ISSUE TITLE
[Bug]: date function data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3378]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'weekday' with parameters [VARCHAR] will be implemented in future version.
Operator 'cast' with parameters [DOUBLE DATE] will be implemented in future version.
Operator 'cast' with parameters [DATE BIGINT] will be implemented in future version.
Function 'sum' with parameters [DATE] will be implemented in future version.
Function 'concat_ws' with parameters [VARCHAR BIGINT] will be implemented in future version.
Function 'dayofyear' with parameters [DATETIME] will be implemented in future version.
Function 'dayofyear' with parameters [TIMESTAMP] will be implemented in future version.
Function 'month' with parameters [TIMESTAMP] will be implemented in future version.
Function 'weekday' with parameters [TIMESTAMP] will be implemented in future version.
Function 'year' with parameters [TIMESTAMP] will be implemented in future version.
Operator '>' with parameters [DATE VARCHAR] will be implemented in future version.
Operator '<>' with parameters [DATE VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
solved:
Function 'weekday' with parameters [VARCHAR] will be implemented in future version.
Function 'dayofyear' with parameters [DATETIME] will be implemented in future version.
Function 'dayofyear' with parameters [TIMESTAMP] will be implemented in future version.
Function 'month' with parameters [TIMESTAMP] will be implemented in future version.
Function 'weekday' with parameters [TIMESTAMP] will be implemented in future version.
Function 'year' with parameters [TIMESTAMP] will be implemented in future version.
Operator '>' with parameters [DATE VARCHAR] will be implemented in future version.
Operator '<>' with parameters [DATE VARCHAR] will be implemented in future version.

do not support  conversion double => date,date=>bigint:
Operator 'cast' with parameters [DOUBLE DATE] will be implemented in future version.
Operator 'cast' with parameters [DATE BIGINT] will be implemented in future version.


do not support  date in sum:
Function 'sum' with parameters [DATE] will be implemented in future version.

should solve:
Function 'concat_ws' with parameters [VARCHAR BIGINT] will be implemented in future version.
