### ISSUE TITLE
[Bug]: date_add function data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3379]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'extract' with parameters [VARCHAR VARCHAR] will be implemented in future version.
Function 'date_add' with parameters [BIGINT BIGINT BIGINT] will be implemented in future version.
Operator '=' with parameters [DATE VARCHAR] will be implemented in future version.
Function 'oct' with parameters [VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
solved:
Function 'extract' with parameters [VARCHAR VARCHAR] will be implemented in future version.
Function 'date_add' with parameters [BIGINT BIGINT BIGINT] will be implemented in future version.
Operator '=' with parameters [DATE VARCHAR] will be implemented in future version.
Function 'oct' with parameters [VARCHAR] will be implemented in future version.
