### ISSUE TITLE
[Feature Request]: account

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3380]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Right now when we connect to mo, we connect to a database.   There need to be another level of namespace, let's call that account.     When we deploy the database, we will create two account -- one "mo", which will hold all mo internal data/database.   Another, "" is default account -- this is more or less for dev and test.   Cloud deployment, either public or private should not need the "" default account, each customer must be assigned an account.  

SQL connection string will need an account param.   Once connected, client can only perform transactions on databases of his/her own account.    For the same deployment we may later allow people to publish a database to another account.   These published database is readonly, at a reasonably fresh snapshot.

### Describe implementation you've considered

Works required at catalog, connection lib, and documentation.   May have impact at transaction scope level.

**Comment by daviszhen** [comment]
related to #3702

**Comment by daviszhen** [comment]
I think it was soleved in 0.6. Why do you return it back to me ? @aressu1985
