### ISSUE TITLE
[Bug]: dayofyear function data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3381]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'dayofyear' with parameters [TINYINT] will be implemented in future version.
Function 'dayofyear' with parameters [DOUBLE] will be implemented in future version.
Function 'dayofyear' with parameters [VARCHAR] will be implemented in future version.
Function 'dayofyear' with parameters [BIGINT] will be implemented in future version.
Function 'dayofyear' with parameters [DOUBLE] will be implemented in future version.
Function 'dayofyear' with parameters [BOOL] will be implemented in future version.
Function 'dayofyear' with parameters [DATETIME] will be implemented in future version.
Function 'dayofyear' with parameters [TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
Do not support implicit conversion integer,double,bool => date:
Function 'dayofyear' with parameters [TINYINT] will be implemented in future version.
Function 'dayofyear' with parameters [DOUBLE] will be implemented in future version.
Function 'dayofyear' with parameters [BIGINT] will be implemented in future version.
Function 'dayofyear' with parameters [DOUBLE] will be implemented in future version.
Function 'dayofyear' with parameters [BOOL] will be implemented in future version.

solved:
Function 'dayofyear' with parameters [VARCHAR] will be implemented in future version.
Function 'dayofyear' with parameters [DATETIME] will be implemented in future version.
Function 'dayofyear' with parameters [TIMESTAMP] will be implemented in future version.
