### ISSUE TITLE
[Feature Request]: Window functions without lead/lag, partition by order by

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3383]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Window functions, row_number, rank, dense_rank + partition by order by.   All agg functions are automatic window functions.

No lead/lag in 0.6.   No quantile in 0.6

**Comment by iamlinjunhong** [comment]
same as https://github.com/matrixorigin/matrixone/issues/8805

**Comment by aressu1985** [comment]
test done
