### ISSUE TITLE
[Bug]: string catenation || does not work.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3384]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

my:dump@127.0.0.1:6001/foo=> select 'foo' || 'bar';
(0 rows)

my:dump@127.0.0.1:6001/foo=> select 'foo' + 'bar';
error: mysql: 1105: Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.
my:dump@127.0.0.1:6001/foo=>

### Expected Behavior

select 'foo' || 'bar';
result should be 'foobar'

**Comment by iamlinjunhong** [comment]
In mysql, when set sqlmode = 'PIPES_AS_CONCAT'

Treat || as a string concatenation operator (same as CONCAT) rather than as a synonym for OR.

So it need parser to support sqlmode for configurable option

**Comment by iamlinjunhong** [comment]
Conclusion: Treat || as a string concatenation only

**Comment by aressu1985** [comment]
fixed

mysql>  select 'foo' || 'bar';
+------------------+
| concat(foo, bar) |
+------------------+
| foobar           |
+------------------+
1 row in set (0.00 sec)
