### ISSUE TITLE
[Bug]: if function data type error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3392]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Operator 'and' with parameters [INT BOOL] will be implemented in future version.
Operator 'and' with parameters [BOOL INT] will be implemented in future version.
Function 'if' with parameters [INT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Data truncation: unexpected return type 'DECIMAL64' for binary expression '3' for column 'e2' at row 0
Function 'if' with parameters [INT BIGINT INT] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR VARCHAR] will be implemented in future version.
Function 'from_unixtime' with parameters [INT VARCHAR] will be implemented in future version.
Function 'if' with parameters [INT DOUBLE DOUBLE] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT BIGINT] will be implemented in future version.
Function 'round' with parameters [DECIMAL64 BIGINT] will be implemented in future version.
Data truncation: Incorrect VARCHAR value: '1' for column 'c' at row 0
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR unexpected type: 0] will be implemented in future version.
Function 'if' with parameters [BIGINT unexpected type: 0 VARCHAR] will be implemented in future version.

[ERROR]
[SCRIPT   FILE]: cases/function/func_if.test
[ROW    NUMBER]: 192
[SQL STATEMENT]: SELECT g.calc_var, g.if_var, g.case_var
FROM
(
SELECT unq_id,
IF ( var_fld  > 5000, (     1 / var_fld ) , 5000 ) calc_var,
IF ( var_fld  > 5000, ( 00001 / var_fld ) , 5000 ) if_var,
CASE  var_fld  > 5000 WHEN TRUE THEN ( 1 / var_fld ) ELSE 5000 END case_var
FROM
test_grids_1
) g
JOIN
test_grid_dtl_1 d USING (unq_id)
ORDER BY 1
;
[EXPECT RESULT]:
calc_var	if_var	case_var
0.0002	0.0002	0.0002
5000.0000	5000.0000	5000.0000
5000.0000	5000.0000	5000.0000
[ACTUAL RESULT]:
parameter types of cast function do not match

**Comment by daviszhen** [comment]
Do not support implicit conversion int => bool:
Operator 'and' with parameters [INT BOOL] will be implemented in future version.
Operator 'and' with parameters [BOOL INT] will be implemented in future version.
Function 'if' with parameters [INT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Function 'if' with parameters [INT BIGINT INT] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR VARCHAR] will be implemented in future version.
Function 'if' with parameters [INT DOUBLE DOUBLE] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT BIGINT] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR unexpected type: 0] will be implemented in future version.
Function 'if' with parameters [BIGINT unexpected type: 0 VARCHAR] will be implemented in future version.

Do not support complicate expression in insert values clause:
Data truncation: unexpected return type 'DECIMAL64' for binary expression '3' for column 'e2' at row 0

Parser do not support conversion from int => varchar:
Data truncation: Incorrect VARCHAR value: '1' for column 'c' at row 0



May implement the decimal version for round in next version:
Function 'round' with parameters [DECIMAL64 BIGINT] will be implemented in future version.


Solved:

[ERROR]
[SCRIPT FILE]: cases/function/func_if.test
[ROW NUMBER]: 192
[SQL STATEMENT]: SELECT g.calc_var, g.if_var, g.case_var
FROM
(
SELECT unq_id,
IF ( var_fld > 5000, ( 1 / var_fld ) , 5000 ) calc_var,
IF ( var_fld > 5000, ( 00001 / var_fld ) , 5000 ) if_var,
CASE var_fld > 5000 WHEN TRUE THEN ( 1 / var_fld ) ELSE 5000 END case_var
FROM
test_grids_1
) g
JOIN
test_grid_dtl_1 d USING (unq_id)
ORDER BY 1
;
[EXPECT RESULT]:
calc_var if_var case_var
0.0002 0.0002 0.0002
5000.0000 5000.0000 5000.0000
5000.0000 5000.0000 5000.0000
[ACTUAL RESULT]:
parameter types of cast function do not match
