### ISSUE TITLE
[Bug]: ceil function data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3394]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'ceiling' with parameters [DECIMAL128] will be implemented in future version.
Function 'floor' with parameters [DECIMAL128] will be implemented in future version.
Function 'floor' with parameters [DECIMAL128] will be implemented in future version.
Function 'ceiling' with parameters [DECIMAL64] will be implemented in future version.
Function 'floor' with parameters [DECIMAL64] will be implemented in future version.

**Comment by daviszhen** [comment]
May implement decimal version in next version for ceiling,floor.
