### ISSUE TITLE
[Bug]: round function data types error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3401]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'round' with parameters [DECIMAL128 DECIMAL128] will be implemented in future version.
Function 'round' with parameters [DOUBLE DOUBLE] will be implemented in future version.
Function 'round' with parameters [DECIMAL64 BIGINT] will be implemented in future version.
Function 'round' with parameters [DECIMAL64 INT] will be implemented in future version.
Function 'round' with parameters [DECIMAL64 TINYINT] will be implemented in future version.

**Comment by daviszhen** [comment]
The second parameter is integer.
Do not support implicit conversion double => int.
Function 'round' with parameters [DOUBLE DOUBLE] will be implemented in future version.
