### ISSUE TITLE
[Bug]: Trigonometric functions data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3403]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'atan' with parameters [BIGINT BIGINT] will be implemented in future version.
Function 'sin' with parameters [VARCHAR] will be implemented in future version.
Function 'cos' with parameters [VARCHAR] will be implemented in future version.
Function 'tan' with parameters [VARCHAR] will be implemented in future version.
Function 'atan' with parameters [VARCHAR] will be implemented in future version.
Function 'sin' with parameters [DECIMAL128] will be implemented in future version.
Function 'sin' with parameters [DATE] will be implemented in future version.
Function 'sin' with parameters [DATETIME] will be implemented in future version.
Function 'sin' with parameters [TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
Unresolved:
Function 'atan' with parameters [BIGINT BIGINT] will be implemented in future version.
Function 'sin' with parameters [DECIMAL128] will be implemented in future version.
Function 'sin' with parameters [DATE] will be implemented in future version.
Function 'sin' with parameters [DATETIME] will be implemented in future version.
Function 'sin' with parameters [TIMESTAMP] will be implemented in future version.

**Comment by daviszhen** [comment]
only solve:
Function 'sin' with parameters [VARCHAR] will be implemented in future version.
Function 'cos' with parameters [VARCHAR] will be implemented in future version.
Function 'tan' with parameters [VARCHAR] will be implemented in future version.
Function 'atan' with parameters [VARCHAR] will be implemented in future version.
