### ISSUE TITLE
[Bug]: concat_ws function data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3405]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'concat_ws' with parameters [INT VARCHAR VARCHAR VARCHAR] will be implemented in future version.
Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.
Operator '-' with parameters [VARCHAR BIGINT] will be implemented in future version.
Function 'concat_ws' with parameters [BIGINT DOUBLE DOUBLE VARCHAR VARCHAR unexpected type: 0] will be implemented in future version.
Function 'concat_ws' with parameters [INT DATE] will be implemented in future version.
Function 'concat_ws' with parameters [VARCHAR INT CHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
Operator '-' with parameters [VARCHAR BIGINT] will be implemented in future version. 

has been solved

**Comment by daviszhen** [comment]
do not support 
Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.  it can be  replaced by #3500 


solved:
Operator '-' with parameters [VARCHAR BIGINT] will be implemented in future version.
