### ISSUE TITLE
[Bug]: length function data types error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3407]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'length' with parameters [INT] will be implemented in future version.
Function 'length' with parameters [BIGINT] will be implemented in future version.
Function 'length' with parameters [DOUBLE] will be implemented in future version.
Function 'length' with parameters [DATE] will be implemented in future version.

**Comment by daviszhen** [comment]
In pr #3514
Replace #3407 by #3498 for some cases
Remove #3407 for some cases.
