### ISSUE TITLE
[Bug]: rpad&lpad function data types error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3408]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'rpad' with parameters [BIGINT BIGINT BIGINT] will be implemented in future version.
Function 'lpad' with parameters [BIGINT BIGINT BIGINT] will be implemented in future version.
Function 'rpad' with parameters [BIGINT BIGINT VARCHAR] will be implemented in future version.
Function 'rpad' with parameters [DOUBLE BIGINT BIGINT] will be implemented in future version.
Function 'rpad' with parameters [DOUBLE DOUBLE DOUBLE] will be implemented in future version.
Function 'lpad' with parameters [VARCHAR BIGINT BIGINT] will be implemented in future version.
Function 'lpad' with parameters [VARCHAR BIGINT DOUBLE] will be implemented in future version.
Function 'lpad' with parameters [VARCHAR DOUBLE DOUBLE] will be implemented in future version.
Function 'lpad' with parameters [DOUBLE DOUBLE DOUBLE] will be implemented in future version.

**Comment by daviszhen** [comment]
In pr #3415 .
Remove #3408 for some cases.
