### ISSUE TITLE
[Bug]: ltrim&rtrim data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3411]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Function 'ltrim' with parameters [DATETIME] will be implemented in future version.
Function 'ltrim' with parameters [DATE] will be implemented in future version.
Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.
Function 'rtrim' with parameters [BIGINT] will be implemented in future version.
Function 'rtrim' with parameters [DOUBLE] will be implemented in future version.
Function 'ltrim' with parameters [BIGINT] will be implemented in future version.
Function 'ltrim' with parameters [DOUBLE] will be implemented in future version.

**Comment by daviszhen** [comment]
do not support Operator '+' with parameters [VARCHAR VARCHAR]

**Comment by dengn** [comment]
#3411 still remains in the test cases.

**Comment by jianwan0214** [comment]
Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.
this error is tracked by issue #3500, so this issue can be closed.
