### ISSUE TITLE
[Bug]: space function data type errors

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3412]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6dedae20180c9e7ad4159ef0c7ad0f8e8c358dee
- Hardware parameters: MAC M1 ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.
Function 'space' with parameters [VARCHAR] will be implemented in future version.

**Comment by daviszhen** [comment]
do not  support Operator '+' with parameters [VARCHAR VARCHAR]

**Comment by daviszhen** [comment]
in pr #3514 
Replace #3412 by #3500 for some cases
Remove #3412 for some cases
