### ISSUE TITLE
[Bug]: The result is different for the same cases in different platform(mac and x86)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3414]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MAC:
mysql> select cast(1.0e+300 as signed int);

+--------------------------+
| cast(1.0e+300 as signed) |
+--------------------------+
|      9223372036854775807 |
+--------------------------+
1 row in set (0.01 sec)

mysql> 

X86：
mysql> select cast(1.0e+300 as signed int);
+--------------------------+
| cast(1.0e+300 as signed) |
+--------------------------+
|     -9223372036854775808 |
+--------------------------+
1 row in set (0.00 sec)

mysql>

**Comment by fengttt** [comment]
Both should fail with out of range.

**Comment by aressu1985** [comment]
fixed
