### ISSUE TITLE
[Feature Request]: Composite primary key

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3415]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Create table with composite primary key.

Alter table.

**Comment by JinHai-CN** [comment]
Already involved in #3697

**Comment by XuPeng-SH** [comment]
It will be implemented in CN

**Comment by fengttt** [comment]
> 

It will be or it has already been?    Done?

**Comment by fengttt** [comment]
@daviszhen please verify it is completed, then we close.

**Comment by bbbearxyz** [comment]
I will support composite primary key in issue#4513
