### ISSUE TITLE
[Feature Request]: create table ddl to support partition by clause

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3416]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

create table ... partition by (a, b) 

### Describe implementation you've considered

MO has a rather different design from most other databases.   Here the partition by, is probably no more than a "hint" to storage optimizer to organize table.

**Comment by fengttt** [comment]
Due to our design, secondary index (index that is not primary key) is also a "hint".   I think partition by and secondary index should be the same thing for us.

**Comment by qingxinhome** [comment]
Mysql reference link：https://dev.mysql.com/doc/refman/5.6/en/create-table.html

**Comment by qingxinhome** [comment]
If the table has a primary key, the column used by the partition expression in the partition list must be from the primary key column.
If the table does not have a primary key, the expression in the partition list can be any column in the table.

**Comment by qingxinhome** [comment]
The construction of the partition sentence and the semantic check coding have been completed, but the partition information of DDL is not synchronized to the metadata table. Subsequently, the metadata table related to the partition will be added and the partition information will be displayed when show create table is supported.

**Comment by qingxinhome** [comment]
The support, coding and testing of MO database for partition clauses have been completed. The main function points are as follows:
1. Support MySQL partition syntax
2. Support semantic check and construction plan for partition clauses
3. Metadata table Mo_ Tables add a new column rel_ Partition, used to store the partition information of the partition table into the metadata table
4. Support the show create table statement to display its partition information
5. Add unit test and BVT test for table partition
These feature requests related to partition has been fixed, unit test and bvt test have been completed, and now request acceptance test, please know！ @fengttt @yingfeng @daviszhen @domingozhang @aressu1985
