### ISSUE TITLE
[Feature Request]: CLOB and BLOB type

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3418]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CLOB (text) and BLOB (varbinary/blob) type support.   Most likely it will have an upper size limit, we should set it to be large enough (1GB).

**Comment by JinHai-CN** [comment]
#3602

**Comment by nnsgmsone** [comment]
Does the blob need to support any functions? @fengttt  @dengn

**Comment by yjw1268** [comment]
Hi I'd like to work on this issue :smiley:

**Comment by domingozhang** [comment]
In 0.6.0, the scope of blob is as following:

function
load_file(filepath/filename), load data from file into a blob column
length ( bytea ) → integer,Returns the number of bytes in the binary string.
substr/substring ( bytes bytea [ FROM start integer ] [ FOR count integer ] ) ,Extracts the substring of bytes starting at the start'th byte if that is specified, and stopping after count bytes if that is specified. Provide at least one of start and count.
trim ( [ LEADING | TRAILING | BOTH ] bytesremoved bytea FROM bytes bytea ) → bytea,Removes the longest string containing only bytes appearing in bytesremoved from the start, end, or both ends (BOTH is the default) of bytes.


operator：
|| combine columns of blob, such as select a,b, a||b from t_blob;
\x123456 \x789a00bcde \x123456789a00bcde

**Comment by dengn** [comment]
Does our implementation recognize longblob?

**Comment by domingozhang** [comment]
because built-in function TRIM() is not supported for string, this function of blob will wait for string of TRIM in future.

**Comment by sukki37** [comment]
First, we need to understand what have done; next, we need to communicate with @domingozhang  to refine the next steps.

**Comment by domingozhang** [comment]
please close it
