### ISSUE TITLE
[Enhancement]: enum type support

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3426]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
User want enum type support.   There are a few things we should consider,
1. enum is not standard feature
2. Usually customer can easily rewrite the query.
2. enum can be easily simulated, with int and UDF

Thus we want to leave this feature out of 0.6.  Let's gather more customer feedback.
```

**Comment by aronchanisme** [comment]
Test done and test cases merged into bvt cases, back to @fengttt 
https://github.com/matrixorigin/matrixone/pull/11349
https://github.com/matrixorigin/matrixone/pull/11381
