### ISSUE TITLE
[Feature Request]: temp table

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3428]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

create temp table t ...

and use t later in transactions.    t is only visible to this connection/session.   when session ends, t is automatically dropped.

**Comment by jensenojs** [comment]
#7160

**Comment by JackTan25** [comment]
distributed temp table for persistence

**Comment by florashi181** [comment]
@domingozhang  to confirm whether distributed temp table is necessary in 0.8.

**Comment by fengttt** [comment]
Partially done.    Need to finish/complete.    Please close after all temp table problems are fixed.

**Comment by jensenojs** [comment]
The temporary table engine may need to switch from memoryengine to distae, and the distribution and persistence of temporary tables should be solved after the switch.

**Comment by jensenojs** [comment]
no process

**Comment by sukki37** [comment]
refactor needed?

**Comment by sukki37** [comment]
close this, another refactor issue #7889 has been created.
