### ISSUE TITLE
[Enhancement]: CN read cache

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3431]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
Design CN cache, row or column format.   S3 cache.   
Simple impl based on S3 file immunity.
Work out with Storage team on what does this mean for inserted data.
What about update/del chain.
```

**Comment by fengttt** [comment]
CN read cache should get a memory budget and ssd budget on startup.
1. The IO unit, as we is one vector (col group), target 8K.
2. Zonemap reading should also be cached.
3. The cached content does not need to be the same as on disk/s3 format, for example, if a vector is compressed, maybe we should cache the decompressed content.
4. Either a Pin/UnPin interface, or, an agreement with query executor, that executor should get vector from cache and operate on the vector.   There should be NO memory allocation/mem copy to use vector from cache.

**Comment by reusee** [comment]
https://github.com/reusee/matrixone/commit/52599b9cb9fb4d3682acb467d6e8f086555ab26b

**Comment by reusee** [comment]
https://github.com/reusee/matrixone/commit/52599b9cb9fb4d3682acb467d6e8f086555ab26b
I made a proposal for further discussion

**Comment by reusee** [comment]
This is fully implemented. 
Related changes:
https://github.com/matrixorigin/matrixone/commit/b2eefef95b79ddfd17e926ead185a312750f80d9
https://github.com/matrixorigin/matrixone/commit/670136a87fe71a519d748e0a5e31132061036be1
https://github.com/matrixorigin/matrixone/commit/730de8bee3a4e0277fce4d761fd53d4ef1670117
https://github.com/matrixorigin/matrixone/commit/3ffbdf3a171b7819a7db65bf21bfd692689fc47a
https://github.com/matrixorigin/matrixone/commit/0d89c5d454944802073f1a338965e16ccd493845
https://github.com/matrixorigin/matrixone/commit/610c908fea6ab125ca1c97fa650a414e6b616aea

**Comment by fengttt** [comment]
@reusee Now CN cache takes another new meaning and much more complex.   Do you want to reuse this issue, or have another issue tracking it?

**Comment by reusee** [comment]
@fengttt I think this one includes the remaining CN works: https://github.com/matrixorigin/matrixone/issues/3931

**Comment by reusee** [comment]
Done

**Comment by reusee** [comment]
@fengttt Please close this since it's done

**Comment by reusee** [comment]
Done in 0.6

**Comment by reusee** [comment]
fixed

**Comment by reusee** [comment]
already fixed.
