### ISSUE TITLE
Refactor error framework

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3435]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
Refactor error reporting framework, so when dev new an error, or panic, front end will get a consistent info and format.   

most likely we need an error code, severity, a well formed message.
```

**Comment by fengttt** [comment]
Integrate with trace/log/metrics.

**Comment by JinHai-CN** [comment]
@daviszhen We need to collect and refactor all error message and code.

**Comment by fengttt** [comment]
Done.
