### ISSUE TITLE
explain analyze a query

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3436]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

explain analyze actually runs the query.    process structure need to record real stats.    for example, number of vectors and rows processed by each operator, memory， io.     at the end of query we gather these from all pipelines.

**Comment by florashi181** [comment]
This is the same as #3921 , closed.

**Comment by yingfeng** [comment]
duplicate with #3921
