### ISSUE TITLE
[Enhancement]: Built type overflow/underflow detection.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3440]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```markdown
Rewrite underflow/overflow checking for builtin types (int/uint).   Most likely using CGO.
```

### Why is this needed ?

Performance.

**Comment by fengttt** [comment]
Let's take a look and try to get into 0.5 -- if we cannot, ok to leave this to 0.6.

**Comment by broccoliSpicy** [comment]
a primitive version of overflow/underflow detection has already implemented for integer plus, minus, multiplication and cast operation

**Comment by qingxinhome** [comment]
This Enhancement has been completed, PR has been merged, and now assign this issue to author(@fengttt ) , please know！
 @fengttt @JinHai-CN @florashi181 @domingozhang @aressu1985 @daviszhen

**Comment by qingxinhome** [comment]
This Enhancement has been completed, including overflow detection, arithmetic operation reconstruction, comparison operation reconstruction and logic operation reconstruction，PR has been merged, and now assign this issue to author(@fengttt ) , please know！
@fengttt @JinHai-CN @florashi181 @domingozhang @aressu1985 @daviszhen
