### ISSUE TITLE
[Enhancement]: refactor function framework

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3458]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Currently, any function needs to be implemented a few times/places, the one is plan2, in vectorize (for different types), etc.   

Now we have type cast work done in plan2, should we/can we reduce this to one place?  
And all the math functions, should really look the same.   All the boilerplate code are duped.  Not clear why we do that.
```

**Comment by JinHai-CN** [comment]
Some functions also need to refactor.

**Comment by fengttt** [comment]
I think this one may take long.   Let me refactor the functions, gradually ...

**Comment by fengttt** [comment]
Part of moving arithmatics and boolean functions refactor.     Fix overflow etc.   We will close this once overflow check work is done.

**Comment by qingxinhome** [comment]
Arithmetic, comparison and logic operations have been reconstructed, including the repair of overflow
