### ISSUE TITLE
[Bug]: the cast from datetime to timestamp doesn't handle out of range situation

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#3459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

..

**Comment by badboynt1** [comment]
MariaDB [mo]> select unix_timestamp('2038-01-19 03:14:20');
+---------------------------------------+
| unix_timestamp('2038-01-19 03:14:20') |
+---------------------------------------+
|                            2147454860 |
+---------------------------------------+
1 row in set (0.00 sec)

MariaDB [mo]> 
MariaDB [mo]> 
MariaDB [mo]> select unix_timestamp('2038-01-20 03:14:20');
+---------------------------------------+
| unix_timestamp('2038-01-20 03:14:20') |
+---------------------------------------+
|                                  NULL |
+---------------------------------------+
1 row in set (0.00 sec)

this is mysql behavior

**Comment by badboynt1** [comment]
MySQL [mo]> select unix_timestamp('2038-01-19 03:14:20');
+-------------------------------------+
| unix_timestamp(2038-01-19 03:14:20) |
+-------------------------------------+
|                          2147454860 |
+-------------------------------------+
1 row in set (0.00 sec)

MySQL [mo]> select unix_timestamp('2038-01-20 03:14:20');
+-------------------------------------+
| unix_timestamp(2038-01-20 03:14:20) |
+-------------------------------------+
|                          2147541260 |
+-------------------------------------+
1 row in set (0.00 sec)

this is mo behavior. expected to be the same

**Comment by goodMan-code** [comment]
fixed, I have recheck it, close it pls

**Comment by goodMan-code** [comment]
Recheck : MO commit id is : 638f863c480e51fffdbafe6b2fdddbdbce00206f

**Comment by daviszhen** [comment]
it was fixed.

**Comment by daviszhen** [comment]
@badboynt1 your pr bave been reverted.

**Comment by badboynt1** [comment]
confirmed with @domingozhang , we have a wider range than mysql, which is better.
this issue can be closed
