### ISSUE TITLE
[Discussion]: add original string in plan2's plan.Type

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#3465]
what kind of problem we want to solve here?

1. currently, our parse will recognize "1234.56789" as a float and parse it to a float64 using Golang's standard library function, precision may lose here.
2. 
[ERROR]
[SCRIPT   FILE]: cases/dtype/decimal.test
[ROW    NUMBER]: 110
[SQL STATEMENT]: SELECT id, id >= 1.1 FROM t_decimal;
[EXPECT RESULT]:
id  id >= 1.1
1.00000 false
2.00000 true
1.10000 true
2.20000 true
[ACTUAL RESULT]:
Operator '>=' with parameters [DECIMAL64 DOUBLE] will be implemented in future version.

**Comment by broccoliSpicy** [comment]
solution 1:
when we saw a float number token, parse it to decimal128

    a: our supported float number range would be narrow down significantly( from 10**308 to 10**38)

**Comment by broccoliSpicy** [comment]
solution 2:
refactor our plan execution: add a string field, determine plan's type when we saw column's type

**Comment by ouyuanning** [comment]
if we want cast constant as decimal.  then cast it in frontend is better.

**Comment by fengttt** [comment]
Solution 1 or 2.  Not 3.     I would do 1, but either way.   1 may cause trouble later when decimal -> int/uint/float cast but should be OK.

I think punt this to 0.6 is also OK.

**Comment by broccoliSpicy** [comment]
for operation between integers and decimals, integers will be cast to decimal and won't lose precision,

**Comment by broccoliSpicy** [comment]
// queries when literal value need to be interpreted as a decimal
// select decimal_column1 + 1 from table1;
// select decimal_column1 + 1.1 from table1;
// select decimal_column1 - 1 from table1;
// select decimal_column1 - 1.1 from table1;
// select decimal_column1 / 1 from table1;
// select decimal_column1 / 1.1 from table1;
// select decimal_column1 * 1 from table1;
// select decimal_column1 * 1.1 from table1;
// select decimal_column1 Div 1 from table1;
// select decimal_column1 Div 1.1 from table1;
// select decimal_column1 mod 1 from table1;
// select * from table1 where decimal_column1 = 1;
// select * from table1 where decimal_column1 = 1.1;
//                                         	  >
// 										      <
// 											  <=
// 										      >=
// for other comparison operations like IN, between And, will these operations be rewire to =, !=, >=, <=, <, > ???

**Comment by ouyuanning** [comment]
we use decimal constant expr for float  string now.
i think we can close this discussion
