### ISSUE TITLE
[Enhancement]: date_add/sub function don't support timestamp arg

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#3483]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
SELECT date_add(TIMESTAMP'2021-01-01 00:00:00', INTERVAL 1 DAY);
```

**Comment by aressu1985** [comment]
fixed
mysql> SELECT date_add(TIMESTAMP'2021-01-01 00:00:00', INTERVAL 1 DAY);
+------------------------------------------------------------+
| date_add(timestamp(2021-01-01 00:00:00), interval(1, day)) |
+------------------------------------------------------------+
| 2021-01-02 00:00:00.000000                                 |
+------------------------------------------------------------+
1 row in set (0.00 sec)
