### ISSUE TITLE
[BUG]: LOAD DATA needs to act as a transaction

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3497]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Currently, while loading data from csv file, another session can get the exact number of rows, such as:

mysql> select count(*) from lineorder;
+----------+
| count(*) |
+----------+
|   160000 |
+----------+
1 row in set (0.13 sec)

mysql> select count(*) from lineorder;
+----------+
| count(*) |
+----------+
|   320001 |
+----------+
1 row in set (0.13 sec)
```

**Comment by daviszhen** [comment]
tae does not support the single transaction for whole loading process.

**Comment by XuPeng-SH** [comment]
@daviszhen @domingozhang 
I don't think It is a bug, it is as expected for the v0.5.0 release. #2742 

To support atomic load, we have a lot of work to do and it will be supported in v0.6.0.
