### ISSUE TITLE
[Bug]: the precision of cast float

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3498]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):62eb9512badb37934a4acb6dbff394b27a359ed1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO:

CREATE TABLE t1 (s char(8), b CHAR(100), c VARCHAR(255), d int, e float, f datetime);
INSERT INTO t1 VALUES ('test', "hhhhhhh", "12jknfjniosdjcoijcpowef", 1234, 0.14123123, "2012-02-08 12:03:23");
select * from t1;
====
+------+---------+-------------------------+------+------------+----------------------------+
| s    | b       | c                       | d    | e          | f                          |
+------+---------+-------------------------+------+------------+----------------------------+
| test | hhhhhhh | 12jknfjniosdjcoijcpowef | 1234 | 0.14123122 | 2012-02-08 12:03:23.000000 |
+------+---------+-------------------------+------+------------+----------------------------+

the value of `e` is `0.14123122` different from `0.141231` in mysql.
the value of `f` is `2012-02-08 12:03:23.000000` different from `2012-02-08 12:03:23` in mysql.

### Expected Behavior

Mysql:

CREATE TABLE t1 (s char(8), b CHAR(100), c VARCHAR(255), d int, e float, f datetime);
INSERT INTO t1 VALUES ('test', "hhhhhhh", "12jknfjniosdjcoijcpowef", 1234, 0.14123123, "2012-02-08 12:03:23");
select * from t1;

======

+------+---------+-------------------------+------+----------+---------------------+
| s    | b       | c                       | d    | e        | f                   |
+------+---------+-------------------------+------+----------+---------------------+
| test | hhhhhhh | 12jknfjniosdjcoijcpowef | 1234 | 0.141231 | 2012-02-08 12:03:23 |
+------+---------+-------------------------+------+----------+---------------------+

**Comment by iamlinjunhong** [comment]
Mysql float will convert into golang float32 which precision is 6,  so it will loss precision. Actually, this problem is how many precision to output for mysql float.

**Comment by daviszhen** [comment]
the default precision of datetime in mo is 6 same as sql standard but it is 0 in mysql mentioned by @broccoliSpicy

**Comment by dengn** [comment]
Accept the result of MO. Solved.
