### ISSUE TITLE
[Bug]: Instance crashed while delete

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3499]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

delete from lineorder;
ERROR 2013 (HY000): Lost connection to MySQL server during query

### Additional information

{"level":"DEBUG","time":"2022/06/29 15:02:20.116604 +0800","caller":"db-server/debug.go:163","msg":"runtime metrics","/gc/heap/allocs:bytes":8196555280,"/gc/heap/frees:bytes":7936145808,"/gc/heap/goal:bytes":486250560,"/memory/classes/heap/free:bytes":19570688,"/memory/classes/heap/objects:bytes":260409472,"/memory/classes/heap/released:bytes":747970560,"/memory/classes/heap/unused:bytes":28063616,"/memory/classes/total:bytes":1120012536,"/sched/goroutines:goroutines":117}
{"level":"INFO","time":"2022/06/29 15:02:21.975884 +0800","caller":"frontend/mysql_cmd_executor.go:2356","msg":"cmd 3"}
{"level":"INFO","time":"2022/06/29 15:02:21.975898 +0800","caller":"frontend/mysql_cmd_executor.go:2379","msg":"query:delete from lineorder"}
{"level":"INFO","time":"2022/06/29 15:02:21.975973 +0800","caller":"frontend/session.go:434","msg":"start txn autocommit if needed"}
{"level":"INFO","time":"2022/06/29 15:02:21.975979 +0800","caller":"frontend/session.go:370","msg":"current txn state 0"}
{"level":"INFO","time":"2022/06/29 15:02:21.975984 +0800","caller":"frontend/session.go:439","msg":"need create new txn"}
{"level":"INFO","time":"2022/06/29 15:02:21.975989 +0800","caller":"frontend/session.go:420","msg":"start txn by autocommit"}
{"level":"INFO","time":"2022/06/29 15:02:21.975998 +0800","caller":"frontend/session.go:83","msg":"switch from 0 to 2"}
{"level":"INFO","time":"2022/06/29 15:02:21.976003 +0800","caller":"frontend/mysql_cmd_executor.go:1917","msg":"start autocommit txn in default"}
{"level":"INFO","time":"2022/06/29 15:02:21.976025 +0800","caller":"frontend/session.go:652","msg":"dbName ssb tableNames [dates lineorder part supplier customer lineorder_flat]"}
{"level":"DEBUG","time":"2022/06/29 15:02:21.976048 +0800","caller":"moengine/relation.go:114","msg":"GetHideKey: &{PADDR None DECIMAL128 {false <nil> false} false}"}
{"level":"INFO","time":"2022/06/29 15:02:21.976059 +0800","caller":"frontend/session.go:732","msg":"dbName ssb tableNames [dates lineorder part supplier customer lineorder_flat]"}
{"level":"INFO","time":"2022/06/29 15:02:21.976067 +0800","caller":"frontend/session.go:776","msg":"dbName ssb tableNames [dates lineorder part supplier customer lineorder_flat]"}
{"level":"DEBUG","time":"2022/06/29 15:02:21.976073 +0800","caller":"moengine/relation.go:114","msg":"GetHideKey: &{PADDR None DECIMAL128 {false <nil> false} false}"}
{"level":"INFO","time":"2022/06/29 15:02:21.976085 +0800","caller":"frontend/session.go:652","msg":"dbName ssb tableNames [dates lineorder part supplier customer lineorder_flat]"}
{"level":"DEBUG","time":"2022/06/29 15:02:21.976102 +0800","caller":"moengine/relation.go:114","msg":"GetHideKey: &{PADDR None DECIMAL128 {false <nil> false} false}"}
{"level":"INFO","time":"2022/06/29 15:02:21.976155 +0800","caller":"frontend/mysql_cmd_executor.go:2116","msg":"time of Exec.Build : 144.878µs"}
{"level":"DEBUG","time":"2022/06/29 15:02:21.982059 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.001911 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.002087 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.021933 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.041874 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.061788 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.081694 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.102004 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.122501 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.142860 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.163310 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
{"level":"DEBUG","time":"2022/06/29 15:02:22.184117 +0800","caller":"moengine/relation.go:184","msg":"Delete col: PADDR"}
panic: interface conversion: stl.MemNode is nil, not *common.MemNode

goroutine 9103 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl.(*simpleAllocator).Free(0xc024dee000?, {0x0?, 0x0?})
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/stl/allocator.go:42 +0x55
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).ReadFromFile(0xc0049a9b80, {0x7fb56c0913a0, 0xc008060230}, 0xc00e2672c0)
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/containers/vector.go:312 +0xa1c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).loadColumnData(0xc01d1f90e0, 0x0, 0x8?)
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/tables/block.go:712 +0x110
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).GetColumnDataById(0xc01d1f90e0, {0x36a5a90?, 0xc01f8c3290?}, 0x0, 0x20?, 0xb58f7484e8?)
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/tables/block.go:516 +0x8d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).GetColumnDataByName(0xc01d1f90e0, {0x36a5a90, 0xc01f8c3290}, {0xc001b93a21?, 0xc0001f9d00?}, 0x11180d2?, 0x90?)
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/tables/block.go:504 +0x97
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnBlock).GetColumnDataByName(0xc0001f9d50?, {0xc001b93a21?, 0xc0001f9d70?}, 0x260bd5e?, 0xc0207caa50?)
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/txn/txnimpl/block.go:198 +0xc8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnBlock).Read(0xc021e95e28, {0x7fb54c0f4868?, 0x0?, 0x7fb5e005ef18?}, {0xc0221927e0, 0x12, 0x12}, {0xc006100750, 0x12, 0x12}, ...)
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/moengine/block.go:37 +0x1e3
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnReader).Read(0xc0015f83f0, {0xc00580c510, 0x12, 0x12}, {0xc0221927e0, 0x12, 0x12})
	/data/zhangxiao/matrixone/pkg/vm/engine/tae/moengine/reader.go:56 +0x24a
github.com/matrixorigin/matrixone/pkg/vm/pipeline2.(*Pipeline).Run(0xc021e95f20, {0x364df40, 0xc0015f83f0}, 0xc004ef6dc0)
	/data/zhangxiao/matrixone/pkg/vm/pipeline2/pipeline.go:70 +0x1de
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).Run(0x13?, {0x10000c0001f9fa0?, 0x2601620?})
	/data/zhangxiao/matrixone/pkg/sql/compile2/scope.go:308 +0xc5
github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun.func1(0xc00028b110?)
	/data/zhangxiao/matrixone/pkg/sql/compile2/scope.go:326 +0x79
created by github.com/matrixorigin/matrixone/pkg/sql/compile2.(*Scope).MergeRun
	/data/zhangxiao/matrixone/pkg/sql/compile2/scope.go:321 +0x1ad

**Comment by jiangxinmeng1** [comment]
fixed by #3520
