### ISSUE TITLE
[Feature Request]: CN node deployment

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3505]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
In v0.6, when implementing distributed MO, most computation will be managed by the CN node. This issue is related to the problem of how such CN node should be designed and its implementation details.
```

### Describe the feature you'd like

CN nodes are stateless nodes for doing computation. It is launched as a single process on the selected node. 

A CN node should be able to query HAKeeper to get DN shards details, query both DN and S3 for accessing DB data. Multiple queries from the same user may execute multiple queries on the same CN node in parallel.

**Comment by JinHai-CN** [comment]
This issue is about node deployment.

**Comment by sukki37** [comment]
Subtask:
- [ ] https://github.com/matrixorigin/matrixone-operator/issues/138

**Comment by sukki37** [comment]
done
