### ISSUE TITLE
[Feature Request]: Use the new txn framework in CN

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3515]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In the new txn framework, an Operator instance will have to be passed to the Reader interface for various txn related Read/Write operations.  Update the CN side to use new txn framework. 

It has been agreed by the storage team that the storage team will look after the Reader integration work to use the above mentioned Operator to talk to the DN.

**Comment by reusee** [comment]
Done
