### ISSUE TITLE
[Bug]: mo-server crashes on replay

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#3519]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8e2d7a20c0ba55b483e9d9c760a56794d0c0025c
- Hardware parameters:
- OS type: centos macos
- Others:
```

### Actual Behavior

After repeatedly executing mo-tester & restarting mo-server repeatedly, mo-server crashes

### Steps to Reproduce

```Markdown
hard to reproduce
```

### Additional information

{"level":"INFO","time":"2022/06/29 13:55:02.653130 +0800","caller":"db/replay.go:213","msg":"","operation":"replay-cmd","operand":"CmdName=Append;Dest=BLK<0:1001-1281-1281>;TS=369844;MaxRow=930;CSN=0","index":"<Index[132731:0/1]>"}
{"level":"INFO","time":"2022/06/29 13:55:02.654417 +0800","caller":"db/replay.go:213","msg":"","operation":"replay-cmd","operand":"CmdName=Append;Dest=BLK<0:1000-1285-29308>;TS=369863;MaxRow=34948;CSN=0","index":"<Index[132737:0/1]>"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x25f87c5]

goroutine 1 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*Batch).Length(...)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/containers/batch.go:81
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).OnLoad(0xc0227cfce0)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/tables/node.go:156 +0x5c5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*Node).Load(0xc00025b600)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/buffer/node.go:124 +0x2f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*nodeManager).Pin(0xc00029faa0, {0x36915a0, 0xc00025b600})
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/buffer/nodemgr.go:172 +0x104
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*nodeManager).TryPin(0xc00029faa0, {0x36915a0, 0xc00025b600}, 0x3b9aca00)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/buffer/nodemgr.go:130 +0x71
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).TryPin(...)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/tables/node.go:71
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).DoWithPin(0x25f7ca0?, 0xc00e99d2f0)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/tables/node.go:75 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*blockAppender).OnReplayInsertNode(0xc016e04fe0?, 0x0?, 0xa06?, 0x0?, {0x0?, 0x0?})
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/tables/appender.go:70 +0x8a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*DB).onReplayAppendCmd(0xc000032000, 0xc0205feb00, {0x3655460, 0xc007426780})
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/replay.go:299 +0x2f1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayCmd(0xc007426780, {0x3681aa0?, 0xc0205feb00?}, 0x0)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/replay.go:236 +0x5bf
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayCmd(0xc007426780, {0x3681980?, 0xc0218d5cc0?}, 0xc007c83120)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/replay.go:226 +0x647
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).OnReplayEntry(0xc007426780, 0x0?, 0x20681, {0xc022580000, 0x30323, 0x30323}, 0x3e60?, {0xc0001febd0?, 0xc0001febd0?})
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/replay.go:195 +0x125
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*replayer).Apply(0xc006a6b360)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/logstore/store/replayer.go:132 +0x1d2
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).Replay(0xc0002ba000, 0xc0073f1960)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/logstore/store/store.go:522 +0x217
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.(*walDriver).Replay(0x10d7227?, 0x48?)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/wal/driver.go:52 +0x22
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*Replayer).Replay(0xc007426780)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/replay.go:90 +0x6d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*DB).Replay(0xc000032000, 0xc00036b440)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/db.go:100 +0x14b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0xc000050230, 0xb}, 0x0)
    /home/jiangxinmeng/go/github.com/matrixone/pkg/vm/engine/tae/db/open.go:79 +0x746
main.initTae()
    /home/jiangxinmeng/go/github.com/matrixone/cmd/db-server/main.go:258 +0x9c
main.main()
    /home/jiangxinmeng/go/github.com/matrixone/cmd/db-server/main.go:363 +0x92e

**Comment by fengttt** [comment]
The bug is still not fixed.   Happened again, lastest main.   Same stack.

**Comment by LeftHandCold** [comment]
#3707 fixes this bug
