### ISSUE TITLE
[Bug]: The results of the data are incorrect

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#3523]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

f1	f2	f3	f4
98	1998	1998-01-01	1998-01-01 00:00:00
NULL	NULL	NULL	NULL

### Expected Behavior

f1	f2	f3	f4
98	1998	1998-01-01	1998-01-01 00:00:00
0	2000	2000-01-01	2000-01-01 00:00:01
2	2002	2002-01-01	2002-01-01 23:59:59
60	2060	2060-01-01	2060-01-01 11:11:11
70	1970	1970-01-01	1970-11-11 22:22:22
NULL	NULL	NULL	NULL

### Steps to Reproduce

```Markdown
create table t1 (f1 int, f2 int, f3 date, f4 datetime);
insert into t1 values(98,1998,"1998-01-01","1998-01-01 00:00:00");
insert into t1 values('00',2000,20000101,"2000-01-01 00:00:01");
insert into t1 values(02,2002,20020101,"2002-01-01 23:59:59");
insert into t1 values(60,2060,20600101,"2060-01-01 11:11:11");
insert into t1 values(70,1970,19700101,"1970-11-11 22:22:22");
insert into t1 values(NULL,NULL,NULL,NULL);

select * from t1;
```

**Comment by iamlinjunhong** [comment]
Previous conclusion is that integer literal can't convert into date. Reference following:
<!DOCTYPE html>

plan type\parser type | int | float | string | bool | decimal
-- | -- | -- | -- | -- | --
int 8/16/32/64 | y | y | y | f | f
decimal 64/128 | y | y | y | f | y
uint 8/16/32/64 | y | y | y | f | f
float 32/64 | y | y | y | f | f
char/varchar | f | f | y | f | f
date | f | f | y | f | f
datetime | f | f | y | f | f
timestamp | y | f | y | f | f
bool | y | f | y | y | f

**Comment by nnsgmsone** [comment]
ok
