### ISSUE TITLE
[Feature Request]: add support for DN data sharding by hash

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3527]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Add support for DN data sharding by hash. As per our discussion, the hash function will be stored in the catalog. DN sharding details (e.g. how many DN shards) will be stored in HAKeeper. CN will use these to route request to relevant DN instance.

**Comment by XuPeng-SH** [comment]
It will be implemented in CN.
