### ISSUE TITLE
[Feature Request]: DN & txn framework integration

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3535]
### Is there an existing issue for the same feature request?

- [x] I have checked the existing issues.

### Describe the feature you'd like

DN & txn framework integration. DN needs to have interface to provide txn framework for Read/Write access. 

As per our discussion, this will probably be done by Luofei.

**Comment by XuPeng-SH** [comment]
Replaced by #3929

**Comment by triump2020** [comment]
Replaced by #3929
