### ISSUE TITLE
[Feature Request]: HAKeeper cluster availability check

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3536]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

When any Log Service shard is found to no longer has its majority quorum, we need to consider the system being unavailable.  As per our discussion, we need to shutdown all nodes in the cluster. 

Guo Ke has already implemented this in HAKeeper, it is waiting to be tested.

**Comment by cnutshell** [comment]
Check log shard state, if there was a log shard with more than half replicas expired, then consider the entire system as unhealthy, we would stop all stores in the cluster.
