### ISSUE TITLE
[Feature Request]: Cluster bootstrapping - tasks for HAKeeper

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3538]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

As per our discussion, a major part of the bootstrap procedure is to let HAKeeper to launch all initially defined DN and Log replicas. HAKeeper also need to keep monitoring the progress such bootstrapping procedure. 

In the extreme case when it fails to bootstrap the minimum system, the system will be marked as failed and manual intervention is required.

**Comment by w-zr** [comment]
Some simple tests are now able to run. We need more tests for corner cases.

**Comment by w-zr** [comment]
Completed and can be closed.
