### ISSUE TITLE
[Feature Request]: Cluster bootstrapping - tasks for the k8s/infra team

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3540]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Proposed bootstrapping procedure is described in 
https://github.com/matrixorigin/docs/blob/main/api/hakeeper/Bootstrap-MO%20v0.6.pptx

As per our discussion last week, the k8s/infra team will be in charge for the initial few steps of the bootstrapping procedure until all required stores are up and running, including - 

* prepare for all resources
* generating the bootstrap configuration file
* launch all stores, pick 3 or 5 log stores as HAKeeper nodes
* pass the above mentioned bootstrap configuration to the HAKeeper. 

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
https://github.com/matrixorigin/docs/blob/main/api/hakeeper/Bootstrap-MO%20v0.6.pptx
```

**Comment by sukki37** [comment]
subtask of #3685
