### ISSUE TITLE
[Feature Request]: Operator should handle DN failover correctly

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3541]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

As per our discussion, k8s will be monitoring the liveness of stores. Failed stores will be replaced whenever possible. 

we've agreed that - 

* when a store is launched for the first time, a new UUID value will be assigned to it by k8s
* on assigning such new UUID values, its mounted data disk/ebs should be empty
* on restart, when such assigned UUID is retained, its data disk/ebs must be retained as well. it would cause critical error if the UUID is retained with the content of its data disk/ebs wiped. See example below. 
* as long as a new UUID is assigned, it is fine to occasionally lose all content of the data disk/ebs. 

we've also agreed that - 

* it doesn't make sense to have two Log Service stores running on a single server/vm. 
* it is okay to have multiple DN stores running on a single sever/vm. 

  

### Additional information

The following is an concrete example on what MUST be avoided - 

let's say we have a Log Service store happily running on a random node and k8s assigned it an UUID of xyz, that node has tons of data generated/managed by the Log Service on its mounted disk/ebs. let's say the store got restarted by k8s for whatever reason, it would be a critical error for the system if the store retains its UUID of xyz while the content on its mounted disk/ebs is gone. however, it is ok if the content is gone *occasionally* (say a few times every 100 such restarts) when the store is restarted with a different UUID, say abc.

**Comment by sukki37** [comment]
Check List:
- [ ] https://github.com/matrixorigin/matrixone-operator/issues/136
