### ISSUE TITLE
[Feature Request]: bit operators &, |, ^, ~, <<, >> 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3549]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Name	Description
&	Bitwise AND
>>	Right shift
<<	Left shift
^	Bitwise XOR
|	Bitwise OR
~	Bitwise inversion

https://dev.mysql.com/doc/refman/8.0/en/bit-functions.html

**Comment by goodMan-code** [comment]
This Feature Request has done, can be closed pls
