### ISSUE TITLE
[Bug]: overflow from BIGINT to BIGINT unsigned

### ISSUE THREAD

**Issue by dongdongyang33** [matrixorigin/matrixone#3550]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[SQL STATEMENT]: select abs(cast(-2 as unsigned)), abs(18446744073709551614), abs(-2);
[EXPECT RESULT]:
abs(cast(-2 as unsigned))       abs(18446744073709551614)       abs(-2)
18446744073709551614    18446744073709551614    2
[ACTUAL RESULT]:
overflow from bigint to bigint unsigned

[SQL STATEMENT]: select ceiling(cast(-2 as unsigned)), ceiling(18446744073709551614), ceiling(-2);
[EXPECT RESULT]:
ceiling(cast(-2 as unsigned))   ceiling(18446744073709551614)   ceiling(-2)
18446744073709551614    18446744073709551614    -2
[ACTUAL RESULT]:
overflow from bigint to bigint unsigned 

[SQL STATEMENT]: select floor(cast(-2 as unsigned)), floor(18446744073709551614), floor(-2);
[EXPECT RESULT]:
floor(cast(-2 as unsigned))     floor(18446744073709551614)     floor(-2)
18446744073709551614    18446744073709551614    -2
[ACTUAL RESULT]: overflow from bigint to bigint unsigned

**Comment by fengttt** [comment]
Isn't this the correct result?   You cast -2 to unsigned, should be a failure.

**Comment by dongdongyang33** [comment]
> Isn't this the correct result? You cast -2 to unsigned, should be a failure.

Okay got it.
We need to modify these cases and I will close the issue then.
