### ISSUE TITLE
[Feature Request]: local cache support on CN & DN nodes

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3551]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

As per our discussion, in v0.6, we'd like to have local cache available on CN & DN. As suggested by @fengttt, the first step should be to figure out the minimum read unit of the storage engine.

**Comment by reusee** [comment]
This feature is being tracked in https://github.com/matrixorigin/matrixone/issues/3431
