### ISSUE TITLE
[Bug]: result is error of the in-subquery sql (correlated columns)

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#3556]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1、[ERROR]
[SCRIPT FILE]: cases/subquery/subquery-with-in.sql
[ROW NUMBER]: 10
[SQL STATEMENT]: SELECT 1 FROM (SELECT 1 as a) b WHERE 1 not IN (SELECT (SELECT a));

correlated subquery will support in future version.

### Expected Behavior

[EXPECT RESULT]:
1

### Additional information

from #3320

**Comment by fengttt** [comment]
in general panic bug cannot be 0.6.

**Comment by domingozhang** [comment]
this will be supported in 0.6.0

**Comment by ouyuanning** [comment]
this is a feature: support correlated subqueries in projection.
i think this issue should be suspended until the feature is finished.

**Comment by ouyuanning** [comment]
no progress

**Comment by ouyuanning** [comment]
no progress

**Comment by ouyuanning** [comment]
this is a feature: support correlated subqueries in projection.
i think this issue should be suspended until the feature is finished.

**Comment by ouyuanning** [comment]
this is a feature: support correlated subqueries in projection.
i think this issue should be suspended until the feature is finished.

**Comment by ouyuanning** [comment]
this is a feature: support correlated subqueries in projection.
i think this issue should be suspended until the feature is finished.

**Comment by ouyuanning** [comment]
this is a feature: support correlated subqueries in projection.
i think this issue should be suspended until the feature is finished.

**Comment by fengttt** [comment]
Convert to P0 dev task.

**Comment by ouyuanning** [comment]
fixed
