### ISSUE TITLE
[Bug]:  BVT Failed

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#3569]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters: BVT Test
- OS type:
- Others:
```

### Actual Behavior

fail log:  https://github.com/matrixorigin/matrixone/runs/7127693512?check_suite_focus=true

**Comment by fengttt** [comment]
Done.

**Comment by fengttt** [comment]
@sukki37 is this reopen auto?   why people cannot close a bug?
