### ISSUE TITLE
[Bug]: scalar subquery will not throw error

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#3570]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from t2, t3
where
t2.a < 10 and
t3.a+1 = 2 and
t3.a in (select t1.b from t1
where t1.a+1=t1.a+1 and
t1.a < (select t4.a+10
from t4, t5 limit 2));

+------+------+
| a    | a    |
+------+------+
|    0 |    1 |
|    1 |    1 |
+------+------+

### Expected Behavior

return error:

Subquery returns more than 1 row

**Comment by ouyuanning** [comment]
this issue is same as #3303

**Comment by aressu1985** [comment]
this issue is same as#3303, and the tag have set to 3303,fixed
