### ISSUE TITLE
[Bug]: non existent implicit conversion rules

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3588]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5bc46ebe8cb3ade55d562bcb68e00d3cfc5a7889
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

there are no such implicit conversion:  decimal,DATE,datetime,timestamp => double
Function 'from_unixtime' with parameters [DECIMAL128] will be implemented in future version.

Function 'sin' with parameters [TIMESTAMP] will be implemented in future version.
Function 'sin' with parameters [DATETIME] will be implemented in future version.
Function 'sin' with parameters [DATE] will be implemented in future version.
Function 'sin' with parameters [DECIMAL128] will be implemented in future version.
Function 'log' with parameters [DECIMAL128] will be implemented in future version.
Function 'log' with parameters [BIGINT BIGINT] will be implemented in future version.
Operator 'cast' with parameters [DOUBLE DATE] will be implemented in future version.
Function 'abs' with parameters [BOOL] will be implemented in future version.
Function 'if' with parameters [BIGINT unexpected type: 0 VARCHAR] will be implemented in future version.
Function 'if' with parameters [BIGINT unexpected type: 0 VARCHAR] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR unexpected type: 0] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR unexpected type: 0] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT UNSIGNED] will be implemented in future version.
Function 'if' with parameters [INT DOUBLE DOUBLE] will be implemented in future version.
Function 'if' with parameters [BIGINT VARCHAR VARCHAR] will be implemented in future version.
Function 'if' with parameters [INT BIGINT INT] will be implemented in future version.
Function 'if' with parameters [BIGINT BIGINT UNSIGNED BIGINT] will be implemented in future version.
Operator 'and' with parameters [BOOL INT] will be implemented in future version.
Operator 'and' with parameters [INT BOOL] will be implemented in future version.
Function 'weekday' with parameters [TINYINT] will be implemented in future version.
Function 'weekday' with parameters [DOUBLE] will be implemented in future version.
Function 'weekday' with parameters [BIGINT] will be implemented in future version.
Function 'weekday' with parameters [BIGINT] will be implemented in future version.
Function 'weekday' with parameters [DOUBLE] will be implemented in future version.
Function 'weekday' with parameters [BIGINT] will be implemented in future version.
Function 'weekday' with parameters [BOOL] will be implemented in future version.

Function 'weekday' with parameters [BOOL] will be implemented in future version.
Function 'weekday' with parameters [BIGINT] will be implemented in future version.
Function 'weekday' with parameters [DOUBLE] will be implemented in future version.
Function 'weekday' with parameters [BIGINT] will be implemented in future version.
Function 'weekday' with parameters [BIGINT] will be implemented in future version.
Function 'weekday' with parameters [DOUBLE] will be implemented in future version.
Function 'weekday' with parameters [TINYINT] will be implemented in future version.

**Comment by daviszhen** [comment]
same as #3614

**Comment by dengn** [comment]
ok for 0.6. Needs a consistent error message for those conversions we will never support.

**Comment by matrix-meow** [comment]
Hello @daviszhen. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by aressu1985** [comment]
need to confirm this issue next week
