### ISSUE TITLE
[Bug]: Operator '-' with parameters [DATETIME DATETIME] will be implemented in future version.

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3589]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5bc46ebe8cb3ade55d562bcb68e00d3cfc5a7889
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Operator '-' with parameters [DATETIME DATETIME] will be implemented in future version.

**Comment by dengn** [comment]
ok. for 0.6, with timediff implemented, date/datetime plus/minus will be supported.

**Comment by domingozhang** [comment]
ERROR 1105 (HY000): Operator '-' with parameters [DATE DATE] will be implemented in future version.
Same as DATE DATE

**Comment by domingozhang** [comment]
In 0.6, the result is the seconds between two values because of the lack of time type.

**Comment by goodMan-code** [comment]
I have rechecked this bug, It is available, close it pls.

**Comment by daviszhen** [comment]
it was fixed.
