### ISSUE TITLE
[Feature Request]: CN DN Interface (Reader) design and impl

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3591]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CN/DN interface need to be finalized really soon.

Reader, read DN key/value and metadata, predicate, etc.

Ins/Upd/Del, esp, update/del from t1, t2 where ...      The query part must scale out, therefore, we need to resolve how to do write and when/where commit happens.

**Comment by nnsgmsone** [comment]
Already done.
