### ISSUE TITLE
[Feature Request]:  text data type

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3602]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Text is a common data type.
```

### Describe the feature you'd like

MO supports a single TEXT data type instead of tinytext, mediumtext, text, longtext of MySQL 8.0.
It should cover the ranges of these four data types.

**Comment by domingozhang** [comment]
This data type will follow these rules:
1. The max length is 65536. Error will be notified when out of range.
2. DEFAULT in DDL and INDEX ON are not supported.
3. All existing data types can be converted into text, including bigint/int/smallint/tinyint, float/double, char/varchar, decimal, date, datetime, timestamp and bool.
4. Text can be castable to char/varchar,bigint/int/smallint/tinyint, float/double, char/varchar, date, datetime, timestamp and bool. When the length of text is longer than other types, errors will be notified.
5. Text can be coercible to char/varchar,bigint/int/smallint/tinyint, float/double, char/varchar, date, timestamp and bool. When the length of text is longer than other types, errors will be notified.
6. All functions of char and varchar need support TEXT data type as well.
7. Other behavior of text is the same as varchar, including order by, group by, subquery and join.

**Comment by bbbearxyz** [comment]
step1, we only support 1, 2, 3, 4, 5.
in the rule 2, text don't support default, primary key and index.

**Comment by domingozhang** [comment]
By following mysql, pg and oracle, there are some adjustment for char, varchar and text:
1. The max size of char, varchar and text is 1GB.
2. The function which text involved will convert text implicitly to varchar.

**Comment by bbbearxyz** [comment]
we already support full feature for type text in pr #4168

**Comment by bbbearxyz** [comment]
> Can we recognize longtext, mediumtext and tinytext with a current MySQL sql statement? @bbbearxyz

no, we just use text type

**Comment by heni02** [comment]
test done，bvt case done
