### ISSUE TITLE
[Feature Request]: Automatic Initialization and Updating for TIMESTAMP and DATETIME

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3603]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

[TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) and [DATETIME](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) columns can be automatically initializated and updated to the current date and time (that is, the current timestamp).

For any [TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) or [DATETIME](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) column in a table, you can assign the current timestamp as the default value, the auto-update value, or both:

An auto-initialized column is set to the current timestamp for inserted rows that specify no value for the column.

An auto-updated column is automatically updated to the current timestamp when the value of any other column in the row is changed from its current value. An auto-updated column remains unchanged if all other columns are set to their current values. To prevent an auto-updated column from updating when other columns change, explicitly set it to its current value. To update an auto-updated column even when other columns do not change, explicitly set it to the value it should have (for example, set it to [CURRENT_TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_current-timestamp)).

CREATE TABLE t1 (
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

**Comment by domingozhang** [comment]
Need a another synonym as following:

CREATE TABLE t1 (
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0),
dt DATETIME DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0)
);

**Comment by goodMan-code** [comment]
This Feature Request has done, can be closed pls
