### ISSUE TITLE
[Bug]: there is no log with two parameters

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3608]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Function 'log' with parameters [BIGINT BIGINT] will be implemented in future version.

**Comment by dengn** [comment]
move to 0.6 ok.

**Comment by dengn** [comment]
OK for 0.6

**Comment by aressu1985** [comment]
mysql> SELECT log(((((-2,2);
ERROR 20203 (HY000): invalid argument log input, bad value <= 0
mysql> SELECT log(1,2);
ERROR 20203 (HY000): invalid argument log base, bad value 1
mysql> SELECT log(2,2);
+-----------+
| log(2, 2) |
+-----------+
|         1 |
+-----------+
1 row in set (0.00 sec)

mysql> SELECT log(8,2);
+---------------------+
| log(8, 2)           |
+---------------------+
| 0.33333333333333337 |
+---------------------+
1 row in set (0.00 sec)

mysql>
