### ISSUE TITLE
[Bug]: function atan with two parameters

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3613]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_math_trig.test
[ROW    NUMBER]: 17
[SQL STATEMENT]: SELECT ATAN(-2,2);
[EXPECT RESULT]:
ATAN(-2,2)
-0.7853981633974483
[ACTUAL RESULT]:
Function 'atan' with parameters [BIGINT BIGINT] will be implemented in future version.

**Comment by daviszhen** [comment]
maybe move to 0.6

**Comment by dengn** [comment]
ok 

> maybe move to 0.6

**Comment by aressu1985** [comment]
mysql> SELECT ATAN(-2,2);
+---------------------+
| atan(-2, 2)         |
+---------------------+
| -0.7853981633974483 |
+---------------------+
1 row in set (0.00 sec)
