### ISSUE TITLE
[Bug]: Operator 'cast' with parameters [DECIMAL128 CHAR] will be implemented in future version.

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3614]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_char_length.test
[ROW    NUMBER]: 57
[SQL STATEMENT]: select char_length(a),char_length(b),char_length(c),char_length(d),char_length(e),char_length(f),char_length(g),char_length(h),char_length(i),char_length(k),char_length(l),char_length(m),char_length(n) from t1;
[EXPECT RESULT]:
char_length(a)	char_length(b)	char_length(c)	char_length(d)	char_length(e)	char_length(f)	char_length(g)	char_length(h)	char_length(i)	char_length(k)	char_length(l)	char_length(m)	char_length(n)
1	1	1	2	1	4	6	22	10	19	19	5	4
2	1	1	2	1	3	6	22	10	19	19	6	4
1	1	2	1	2	4	6	22	10	19	19	4	5
1	2	1	2	1	3	6	23	10	19	19	6	4
[ACTUAL RESULT]:
Operator 'cast' with parameters [DECIMAL128 CHAR] will be implemented in future version.

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_lpad_rpad.test
[ROW    NUMBER]: 93
[SQL STATEMENT]: SELECT (rpad(1.0,2048,1)) IS NOT FALSE;
[EXPECT RESULT]:
(rpad(1.0,2048,1)) IS NOT FALSE
1
[ACTUAL RESULT]:
Operator 'cast' with parameters [VARCHAR BOOL] will be implemented in future version.

**Comment by daviszhen** [comment]
split 

[ERROR]
[SCRIPT FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_lpad_rpad.test
[ROW NUMBER]: 93
[SQL STATEMENT]: SELECT (rpad(1.0,2048,1)) IS NOT FALSE;
[EXPECT RESULT]:
(rpad(1.0,2048,1)) IS NOT FALSE
1
[ACTUAL RESULT]:
Operator 'cast' with parameters [VARCHAR BOOL] will be implemented in future version.

**Comment by dengn** [comment]
The test of SELECT (rpad(1.0,2048,1)) IS NOT FALSE; doesn't give your error message, it's still the previous result.

mysql> SELECT (rpad(1.0,2048,1)) IS NOT FALSE;
+-------------------------------+
| (rpad(1.0, 2048, 1)) != false |
+-------------------------------+
| false                         |
+-------------------------------+
1 row in set (0.01 sec)

**Comment by aressu1985** [comment]
mysql> SELECT (rpad(1.0,2048,1)) IS NOT FALSE;
+-----------------------------------+
| (rpad(1.0, 2048, 1)) is not false |
+-----------------------------------+
| true                              |
+-----------------------------------+
1 row in set (0.00 sec)
