### ISSUE TITLE
[Feature Request]: String built-in function TRIM() 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3615]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Follow MySQL8.0 function syntax, https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim

[TRIM([{BOTH | LEADING | TRAILING} [remstr] FROM] str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim), [TRIM([remstr FROM] str)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim)

Returns the string str with all remstr prefixes or suffixes removed. If none of the specifiers BOTH, LEADING, or TRAILING is given, BOTH is assumed. remstr is optional and, if not specified, spaces are removed.

mysql> SELECT TRIM('  bar   ');
        -> 'bar'
mysql> SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx');
        -> 'barxxx'
mysql> SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx');
        -> 'bar'
mysql> SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz');
        -> 'barx'
This function is multibyte safe. It returns NULL if any of its arguments are NULL.

**Comment by mooleetzi** [comment]
@dengn
is header like below ok?
```
mysql> select trim('a');
+------------------+
| trim(both,  , a) |
+------------------+
| a                |
+------------------+
```

**Comment by mooleetzi** [comment]
pr merged, pls test.

**Comment by aressu1985** [comment]
test done
