### ISSUE TITLE
[Bug]: '^' operator is not supported now

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3619]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_lpad_rpad.test
[ROW    NUMBER]: 103
[SQL STATEMENT]: SELECT ((rpad(1.0,2048,1)) = ('4(') ^ (0.1));
[EXPECT RESULT]:
((rpad(1.0,2048,1)) = ('4(') ^ (0.1))
0
[ACTUAL RESULT]:
'^' operator is not supported now

**Comment by dengn** [comment]
Ok for 0.6. related to #3529

**Comment by tianyahui-python** [comment]
<img width="1247" alt="截屏2022-10-29 23 34 35" src="https://user-images.githubusercontent.com/39303074/198840272-bbed54f8-142d-4400-b58c-491c7838c484.png">

**Comment by tianyahui-python** [comment]
> <img alt="截屏2022-10-29 23 34 35" width="1247" src="https://user-
images.githubusercontent.com/39303074/198840272-bbed54f8-142d-4400-b58c-491c7838c484.png">

----

@daviszhen @ouyuanning   Expectations do not match requirements

**Comment by domingozhang** [comment]
('4(') ^ (0.1)) is an incorrect input so that both MO and PG notified failure.
MySQL is not notified failure but with warning. It's not correct. 
MO's result can be accepted.
