### ISSUE TITLE
[Bug]:wrong results of the function oct

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3620]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_oct.test
[ROW    NUMBER]: 10
[SQL STATEMENT]: select oct(2e5);
[EXPECT RESULT]:
oct(2e5)
606500
[ACTUAL RESULT]:
oct(2e5)
100

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_oct.test
[ROW    NUMBER]: 25
[SQL STATEMENT]: select oct(10e50);
[EXPECT RESULT]:
oct(10e50)
1
[ACTUAL RESULT]:
oct(10e50)
0

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_oct.test
[ROW    NUMBER]: 26
[SQL STATEMENT]: select oct(-10e50);
[EXPECT RESULT]:
oct(-10e50)
1777777777777777777777
[ACTUAL RESULT]:
oct(-10e50)
0

**Comment by aressu1985** [comment]
mysql> select oct(2e5);
+----------+
| oct(2e5) |
+----------+
| 606500   |
+----------+
1 row in set (0.00 sec)

mysql> 
mysql> 
mysql> select oct(10e50);
+------------+
| oct(10e50) |
+------------+
| 1          |
+------------+
1 row in set (0.00 sec)

mysql> select oct(-10e50);
+------------------------+
| oct(-10e50)            |
+------------------------+
| 1777777777777777777777 |
+------------------------+
1 row in set (0.00 sec)

mysql>
