### ISSUE TITLE
[Bug]: When the insert is executed with high concurrency, the result returned by the transaction will be incorrect

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3624]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DDL：
mysql> show create table sbtest1;
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                        |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| sbtest1 | CREATE TABLE `sbtest1` (
`id` INT DEFAULT NULL,
`k` INT DEFAULT NULL,
`c` CHAR(120) DEFAULT NULL,
`pad` CHAR(60) DEFAULT NULL,
PRIMARY KEY (`id`)
) |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
When the insert is executed with high concurrency, the result returned by the transaction will be incorrect
the insert sql is :
sql: "insert into sbtest1 values({id},4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');"

{id} is a random number from 10001 to 20000

as above ,in any situation, the success transaction number should not be more than 10000 because of PK confilict, but actually, nearly every time, the transaction success number is larger than 10000

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/47846308/176839778-384e73cd-1b1d-47fe-b7f8-28a76da1698d.png">

**Comment by LeftHandCold** [comment]
Is the result of executing the select query 10000 rows? @aressu1985
