### ISSUE TITLE
[Bug]: test cases isolation_1.sql fail

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3647]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

isolation_1.sql fail, on aws amd64 machine.

**Comment by fengttt** [comment]
[error.txt](https://github.com/matrixorigin/matrixone/files/9031910/error.txt)

**Comment by XuPeng-SH** [comment]
@jianwan0214 
It is an auto-commit bug and maybe it is introduced by #3637

**Comment by fengttt** [comment]
Fixed.
