### ISSUE TITLE
[Bug]: Function or operator 'bin' will be implemented in future version

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3657]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /Users/pengzhen/Documents/GitHub/matrixone/test/cases/function/func_string_findinset.test
[ROW    NUMBER]: 4
[SQL STATEMENT]: select bin(concat_ws(" ",find_in_set('b','a,b,c,d')));
[EXPECT RESULT]:
bin(concat_ws(" ",find_in_set('b','a,b,c,d')))
10
[ACTUAL RESULT]:
Function or operator 'bin' will be implemented in future version.

**Comment by daviszhen** [comment]
The function `bin` is wrong and contributed by an external author who have not fix it. So in migration plan, we decide to migrate it after it is fixed. Now, it is in plan1.

**Comment by dengn** [comment]
ok for 0.6

**Comment by aressu1985** [comment]
mysql> select bin(concat_ws(" ",find_in_set('b','a,b,c,d')));
+--------------------------------------------+
| bin(concat_ws( , find_in_set(b, a,b,c,d))) |
+--------------------------------------------+
| 10                                         |
+--------------------------------------------+
1 row in set (0.00 sec)

**Comment by aressu1985** [comment]
[sudong@mo-srv-128 test]$ grep -r "#3657" cases/
cases/function/func_string_findinset.test:-- @bvt:issue#3657

**Comment by tianyahui-python** [comment]
@daviszhen only issue owner is can  close an issue.

**Comment by daviszhen** [comment]
it was fixed.
