### ISSUE TITLE
[Bug]: precision lost when type implicit convert to Decimal64/128

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#3673]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

CREATE TABLE t1 (id INT PRIMARY KEY,
a decimal(20),
b VARCHAR(20));
-- @bvt:issue#3355
INSERT INTO t1 (id,a) VALUES
(1,0),
(2,CAST(0x7FFFFFFFFFFFFFFF AS UNSIGNED)),
(3,CAST(0x8000000000000000 AS UNSIGNED)),
(4,CAST(0xFFFFFFFFFFFFFFFF AS UNSIGNED));
UPDATE t1 SET b = a;

select distinct * from t1 where ((a = '2147483647') and (b = '2147483647'));
select a,count(a) from t1 group by a having count(a)>=2;
```

### Actual Behavior

id	a	b

a	count(a)

### Expected Behavior

id	a	b
3	2147483647	2147483647
5	2147483647	2147483647

a	count(a)
2147483647	2

**Comment by m-schen** [comment]
should consider type.Type(with width, precision and so on) but not only type.T_oid

**Comment by aressu1985** [comment]
mysql> drop table t1;
ERROR 1105 (HY000): tae catalog: not found
mysql> 
mysql> 
mysql> CREATE TABLE t1 (id INT PRIMARY KEY,
    -> a decimal(20),
    -> b VARCHAR(20));
Query OK, 0 rows affected (0.00 sec)

mysql> -- @bvt:issue#3355
mysql> INSERT INTO t1 (id,a) VALUES
    -> (1,0),
    -> (2,CAST(0x7FFFFFFFFFFFFFFF AS UNSIGNED)),
    -> (3,CAST(0x8000000000000000 AS UNSIGNED)),
    -> (4,CAST(0xFFFFFFFFFFFFFFFF AS UNSIGNED));
ERROR 1105 (HY000): Data truncation: Function expression in INSERT statement value list will be supported in future version. for column 'a' at row 1
mysql> UPDATE t1 SET b = a;
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> select distinct * from t1 where ((a = '2147483647') and (b = '2147483647'));
Empty set (0.01 sec)

mysql> select a,count(a) from t1 group by a having count(a)>=2;
Empty set (0.01 sec)

mysql>
