### ISSUE TITLE
[Feature]: INSERT TABLE VALUE sql should build plan too.

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#3678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

our insert sql like insert table values (a, b, c)
was implemented at front-end.
It's too hard to use the implicit-type-convert or cast rule,
It should have the same process as other insert statements
```

### Actual Behavior

just in front-end

### Expected Behavior

make plan and have the same process as other insert sql (insert select).

**Comment by iamlinjunhong** [comment]
This issue mainly say the problem of converting parser's type into plan's which has discuss before. But some cases didn't adjust completely.  Pr #3696 has merged, So this issue can validate and close.
There are issue #3333 about supporting insert expression.

**Comment by domingozhang** [comment]
pr merged
