### ISSUE TITLE
[Bug]: M of TIMESTAMP(M) no effect

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#3680]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

drop table if exists t1;
drop table if exists t2;
CREATE TABLE t_timestamp(id timestamp(6));
INSERT INTO t_timestamp VALUES ('2020-01-01 23:59:59.999999'), ('2022-01-02 00:00:00');
SELECT * from t_timestamp WHERE id BETWEEN '2022-01-01 00:00:00' AND '2022-01-02 00:00:00.000000';
```

### Actual Behavior

id
2022-01-02 00:00:00

### Expected Behavior

id
2022-01-02 00:00:00.000000

**Comment by dengn** [comment]
It looks like this bug has been fixed. Check commit: 1c0f565667b7e774f4fa57adfd36e42d28edb692 

mysql> drop table if exists t2;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE t_timestamp(id timestamp(6));
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t_timestamp VALUES ('2020-01-01 23:59:59.999999'), ('2022-01-02 00:00:00');
Query OK, 2 rows affected (0.03 sec)

mysql> SELECT * from t_timestamp WHERE id BETWEEN '2022-01-01 00:00:00' AND '2022-01-02 00:00:00.000000';
+----------------------------+
| id                         |
+----------------------------+
| 2022-01-02 00:00:00.000000 |
+----------------------------+
1 row in set (0.01 sec)

mysql> drop table t_timestamp;
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE TABLE t_timestamp(id timestamp(4));
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO t_timestamp VALUES ('2020-01-01 23:59:59.999999'), ('2022-01-02 00:00:00');
Query OK, 2 rows affected (0.02 sec)

mysql> SELECT * from t_timestamp WHERE id BETWEEN '2022-01-01 00:00:00' AND '2022-01-02 00:00:00.000000';
+--------------------------+
| id                       |
+--------------------------+
| 2022-01-02 00:00:00.0000 |
+--------------------------+
1 row in set (0.01 sec)

**Comment by m-schen** [comment]
#3673

**Comment by aressu1985** [comment]
fixed

mysql> SELECT * from t_timestamp WHERE id BETWEEN '2022-01-01 00:00:00' AND '2022-01-02 00:00:00.000000';
+----------------------------+
| id                         |
+----------------------------+
| 2022-01-02 00:00:00.000000 |
+----------------------------+
1 row in set (0.00 sec)
