### ISSUE TITLE
[Feature Request]: Support AUTOCOMMIT variable

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3688]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In MySQL, there is a variable named AUTOCOMMIT. 
If set to 1, all changes to a table take effect immediately. 
If set to 0, you must use COMMIT to accept a transaction or ROLLBACK to cancel it. 
If autocommit is 0 and you change it to 1, MySQL performs an automatic COMMIT of any open transaction. 
Another way to begin a transaction is to use a START TRANSACTION or BEGIN statement.

**Comment by daviszhen** [comment]
The Autocommit variable has been supported now.
