### ISSUE TITLE
[Feature Request]: LOAD DATA acts as transactions

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3690]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In 0.5.0, loaded data is commited batch by batch. To guarantee data consistency, LOAD DATA needs to act as transactions.

**Comment by XuPeng-SH** [comment]
It should be supported in cn workspace.

**Comment by reusee** [comment]
Will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
I think it's already in a single transaction in 0.6.
