### ISSUE TITLE
[Bug]: Rounding rule of datetime needs to be adjust

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3713]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Such as
select date_add("1997-12-31 23:59:59",INTERVAL 1.5 SECOND);    
the result need to be add 2 seconds

**Comment by aressu1985** [comment]
fixed

mysql> select date_add("1997-12-31 23:59:59",INTERVAL 1.5 SECOND);
+------------------------------------------------------+
| date_add(1997-12-31 23:59:59, interval(1.5, second)) |
+------------------------------------------------------+
| 1998-01-01 00:00:01.000000                           |
+------------------------------------------------------+
1 row in set (0.00 sec)
