### ISSUE TITLE
[Bug]: refine error messages for features that will never be implemented

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#3716]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Operator '+' with parameters [VARCHAR VARCHAR] will be implemented in future version.

**Comment by dengn** [comment]
move to 0.6

**Comment by aressu1985** [comment]
mysql> select 'a' + 'b';
+-------+
| a + b |
+-------+
| ab    |
+-------+
1 row in set (0.00 sec)

mysql> select NULL    + 'b';
+----------+
| null + b |
+----------+
|     NULL |
+----------+
1 row in set (0.00 sec)

mysql> create table bb(a char, b varchar(10));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into bb values('a','b'),('aa','cc');
Query OK, 2 rows affected (0.00 sec)

mysql> select a + b from bb;
ERROR 20203 (HY000): invalid argument operator +, bad value [CHAR CHAR]
mysql> select b  + b from bb;
+-------+
| b + b |
+-------+
| bb    |
| cccc  |
+-------+
2 rows in set (0.00 sec)
