### ISSUE TITLE
[Feature Request]: Support basic alerts of mo cluster 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3727]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In 0.6.0, MO cluster needs to support following base alerts and can be displayed in metrics.

- Cluster status, including started/starting/stopping/stopped
- Node status, including starting/normal/unreachable/stopped

**Comment by aptend** [comment]
Note: for version 0.6, HAKeepr will provide related status information, but it can only tell if a node's heartbeat is normal, which means only two kinds of node status can be displayed in metric dashboard: normal/unreachable.

**Comment by aptend** [comment]
@domingozhang When hakeeper was available in cn, it was already late in the release and there was not enough time to do new adaptations based on the new task service and hakeeper. At the same time, we are not exporting metric information to Prometheus by default, so alerting on Grafana is not a thing with the highest priority. We may redesign this feature in the next iteration based on the new infrastructure.

**Comment by domingozhang** [comment]
this is out of date. new tool is impletemented which including related features.
