### ISSUE TITLE
[Feature Request]: Basic cluster management support

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3728]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

To match basic cluster management, MO cluster needs these action as following 

- Start and stop the whole cluster with pod and k8s normally
- Dispatch resources to restart related service when any one of nodes is down, including dn, cn, logservice, fileservice 
- Stop whole cluster forcely after trying to fix failed node

**Comment by sukki37** [comment]
Subtask:
- [ ] https://github.com/matrixorigin/matrixone-operator/issues/139

**Comment by aylei** [comment]
closed via https://github.com/matrixorigin/matrixone-operator/issues/139

**Comment by aylei** [comment]
this has been done with mo-operator shipped, document: https://github.com/matrixorigin/docs/blob/main/tech-notes/cloud/intro/mo-operator/index.md
