### ISSUE TITLE
[Feature Request]: Support scale-in and scale-out for CN nodes

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3729]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In 0.6, MO cluster will support CN nodes' scale-in and scale-out action.

**Comment by sukki37** [comment]
Task List:

- [ ] https://github.com/matrixorigin/matrixone-operator/issues/138
