### ISSUE TITLE
[Bug]: bit_wise function result different in ARM and X86

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3734]
### Is there an existing issue for the same bug?

- [X] #6974

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

These cases succeed in local bvt test with Mac M1 ARM, but it failed in bvt case in github under CentOS with x86 chipset.
The expected result is in Mac, the actual result is from CentOS in github.

select BIT_AND(999999999999999933193939.99999),BIT_OR(999999999999999933193939.99999),BIT_XOR(999999999999999933193939.99999);

[EXPECT RESULT]:
bit_and(999999999999999933193939.99999)	bit_or(999999999999999933193939.99999)	bit_xor(999999999999999933193939.99999)
18446744073709551615	18446744073709551615	18446744073709551615

[ACTUAL RESULT]:
bit_and(999999999999999933193939.99999)	bit_or(999999999999999933193939.99999)	bit_xor(999999999999999933193939.99999)
9223372036854775808	9223372036854775808	9223372036854775808

select BIT_AND(9999999999999999999999999999999999.9999999999999),BIT_OR(9999999999999999999999999999999999.9999999999999),BIT_XOR(9999999999999999999999999999999999.9999999999999);

[EXPECT RESULT]:
bit_and(9999999999999999999999999999999999.9999999999999)	bit_or(9999999999999999999999999999999999.9999999999999)	bit_xor(9999999999999999999999999999999999.9999999999999)
18446744073709551615	18446744073709551615	18446744073709551615

[ACTUAL RESULT]:
bit_and(9999999999999999999999999999999999.9999999999999)	bit_or(9999999999999999999999999999999999.9999999999999)	bit_xor(9999999999999999999999999999999999.9999999999999)
9223372036854775808	9223372036854775808	9223372036854775808

select BIT_AND(-99999999999999999.99999),BIT_OR(-99999999999999999.99999),BIT_XOR(-99999999999999999.99999);
[EXPECT RESULT]:
bit_and(-99999999999999999.99999)	bit_or(-99999999999999999.99999)	bit_xor(-99999999999999999.99999)
0	0	0
[ACTUAL RESULT]:
bit_and(-99999999999999999.99999)	bit_or(-99999999999999999.99999)	bit_xor(-99999999999999999.99999)
18346744073709551616	18346744073709551616	18346744073709551616

select BIT_AND(-999999999999999933193939.99999),BIT_OR(-999999999999999933193939.99999),BIT_XOR(-999999999999999933193939.99999);
[EXPECT RESULT]:
bit_and(-999999999999999933193939.99999)	bit_or(-999999999999999933193939.99999)	bit_xor(-999999999999999933193939.99999)
0	0	0
[ACTUAL RESULT]:
bit_and(-999999999999999933193939.99999)	bit_or(-999999999999999933193939.99999)	bit_xor(-999999999999999933193939.99999)
9223372036854775808	9223372036854775808	9223372036854775808

**Comment by goodMan-code** [comment]
I have rechecked this bug, and add some cases to bvt, close it pls

**Comment by dengn** [comment]
Update your test status. @goodMan-code

**Comment by goodMan-code** [comment]
commit 8f715312b8e0e176565c5f9f20cf99c52705f7f6
Launch Method ：./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml &> mo.log &
Environment：CentOS-7
1. select BIT_AND(999999999999999933193939.99999),BIT_OR(999999999999999933193939.99999),BIT_XOR(999999999999999933193939.99999);
Result : 
+-----------------------------------------+----------------------------------------+-----------------------------------------+
| bit_and(999999999999999933193939.99999) | bit_or(999999999999999933193939.99999) | bit_xor(999999999999999933193939.99999) |
+-----------------------------------------+----------------------------------------+-----------------------------------------+
|                     9223372036854775808 |                    9223372036854775808 |                     9223372036854775808 |
+-----------------------------------------+----------------------------------------+-----------------------------------------+

2. select BIT_AND(9999999999999999999999999999999999.9999999999999),BIT_OR(9999999999999999999999999999999999.9999999999999),BIT_XOR(9999999999999999999999999999999999.9999999999999);
Result ：
9223372036854775808   9223372036854775808    9223372036854775808

3. select BIT_AND(-99999999999999999.99999),BIT_OR(-99999999999999999.99999),BIT_XOR(-99999999999999999.99999);
Result ：18346744073709551616    18346744073709551616    18346744073709551616

4. select BIT_AND(-999999999999999933193939.99999),BIT_OR(-999999999999999933193939.99999),BIT_XOR(-999999999999999933193939.99999);
Result：9223372036854775808    9223372036854775808    9223372036854775808

**Comment by goodMan-code** [comment]
should finish on different Chiplet

**Comment by qingxinhome** [comment]
Not resolved yet

**Comment by qingxinhome** [comment]
Not resolved yet

**Comment by qingxinhome** [comment]
The problem has been solved. PR has been merged. Please test. @dengn @aressu1985 @goodMan-code @daviszhen

**Comment by aressu1985** [comment]
fixed
