### ISSUE TITLE
[Bug]: rpad & lpad different behavior

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3738]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Related to #3255. 

select rpad('hello', -18446744073709551615, '1');
rpad('hello', -18446744073709551615, '1')
null
select rpad('hello', 18446744073709551615, '1');
rpad('hello', 18446744073709551615, '1')
null
select rpad('hello', -18446744073709551616, '1');
rpad('hello', -18446744073709551616, '1')
null
select rpad('hello', 18446744073709551616, '1');
rpad('hello', 18446744073709551616, '1')
null
select rpad('hello', -18446744073709551617, '1');
rpad('hello', -18446744073709551617, '1')
null
select rpad('hello', 18446744073709551617, '1');
rpad('hello', 18446744073709551617, '1')
null

select lpad('hello', -18446744073709551615, '1');
Operator 'cast' with parameters [DECIMAL128 BIGINT] will be implemented in future version.
select lpad('hello', 18446744073709551615, '1');
Can't cast '18446744073709551615' from BIGINT UNSIGNED type to BIGINT type. Reason: overflow
select lpad('hello', -18446744073709551616, '1');
Operator 'cast' with parameters [DECIMAL128 BIGINT] will be implemented in future version.
select lpad('hello', 18446744073709551616, '1');
Operator 'cast' with parameters [DECIMAL128 BIGINT] will be implemented in future version.
select lpad('hello', -18446744073709551617, '1');
Operator 'cast' with parameters [DECIMAL128 BIGINT] will be implemented in future version.
select lpad('hello', 18446744073709551617, '1');
Operator 'cast' with parameters [DECIMAL128 BIGINT] will be implemented in future version

RPAD and LPAD with the same arguments show different behaviors.

### Expected Behavior

select rpad('hello', -18446744073709551615, '1');
rpad('hello', -18446744073709551615, '1')
null
select rpad('hello', 18446744073709551615, '1');
rpad('hello', 18446744073709551615, '1')
null
select rpad('hello', -18446744073709551616, '1');
rpad('hello', -18446744073709551616, '1')
null
select rpad('hello', 18446744073709551616, '1');
rpad('hello', 18446744073709551616, '1')
null
select rpad('hello', -18446744073709551617, '1');
rpad('hello', -18446744073709551617, '1')
null
select rpad('hello', 18446744073709551617, '1');
rpad('hello', 18446744073709551617, '1')
null

select lpad('hello', -18446744073709551615, '1');
null
select lpad('hello', 18446744073709551615, '1');
null
select lpad('hello', -18446744073709551616, '1');
null
select lpad('hello', 18446744073709551616, '1');
null
select lpad('hello', -18446744073709551617, '1');
null
select lpad('hello', 18446744073709551617, '1');
null

**Comment by tianyahui-python** [comment]
@dengn can close issue.

**Comment by tianyahui-python** [comment]
@dengn only issue owner is can close an issue.

**Comment by tianyahui-python** [comment]
<img width="885" alt="截屏2022-11-07 10 33 19" src="https://user-images.githubusercontent.com/39303074/200214662-6a3259e0-5e0f-4c1d-af87-dd959768c6f9.png">

<img width="896" alt="截屏2022-11-07 10 34 08" src="https://user-images.githubusercontent.com/39303074/200214666-3d803628-ef6f-49c3-863c-b4f9a02f9b51.png">
