### ISSUE TITLE
[Bug]: operation imprecision when round with float numbers

### ISSUE THREAD

**Issue by broccoliSpicy** [matrixorigin/matrixone#3747]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select round(999999999.0, -9);
+------------------------+
| round(999999999.0, -9) |
+------------------------+
|      999999999.9999999 |
+------------------------+
1 row in set (0.00 sec)

mysql> select round(999999999999999999.0, -18);
+----------------------------------+
| round(999999999999999999.0, -18) |
+----------------------------------+
|               999999999999999900 |
+----------------------------------+
1 row in set (0.00 sec)

**Comment by broccoliSpicy** [comment]
[ERROR]
[SCRIPT   FILE]: ../july_4/test/cases/function/func_math_round.test
[ROW    NUMBER]: 67
[SQL STATEMENT]: select round(999999999999999999.0, -18);
[EXPECT RESULT]:
round(999999999999999999.0, -18)
1000000000000000000
[ACTUAL RESULT]:
round(999999999999999999.0, -18)
9.9999999999999987E17





[ERROR]
[SCRIPT   FILE]: ../july_4/test/cases/function/func_math_round.test
[ROW    NUMBER]: 63
[SQL STATEMENT]: select round(999999999.0, -9);
[EXPECT RESULT]:
round(999999999.0, -9)
1000000000
[ACTUAL RESULT]:
round(999999999.0, -9)
9.999999999999999E8

**Comment by broccoliSpicy** [comment]
I don't know how to solve problems like this, when dealing with float point numbers, this is kind of inevitable

**Comment by fengttt** [comment]
I think, our decision was that keep number of at max possible precision, in this case, 99999999999.0 should be parsed as decimal in the first place, not float.    cc @ouyuanning.

**Comment by dengn** [comment]
Not sure if this is precision issue, even at this level it's still wrong:

mysql> select round(99999.0, -5);
+--------------------+
| round(99999.0, -5) |
+--------------------+
|  99999.99999999999 |
+--------------------+
1 row in set (0.01 sec)

**Comment by broccoliSpicy** [comment]
we can implement round function using our decimal representation, but for most other math functions, I think it is simply impossible for us to implement one for our decimal, we have to cast it the float

**Comment by broccoliSpicy** [comment]
> Not sure if this is precision issue, even at this level it's still wrong:
> 
> mysql> select round(99999.0, -5); +--------------------+ | round(99999.0, -5) | +--------------------+ | 99999.99999999999 | +--------------------+ 1 row in set (0.01 sec)

during this operation, we first divide 99999.0 by 10**5, then call round operation in Golang standard library or simd instruction, then scale it up by 10**5, precision may lose during this operations

**Comment by broccoliSpicy** [comment]
> I think, our decision was that keep number of at max possible precision, in this case, 99999999999.0 should be parsed as decimal in the first place, not float. cc @ouyuanning.

for literal values that is out of range or other kind of error thrown by decimal parser, I think we can add a logic to parse it to float64, so we can support larger range of literal float token
