### ISSUE TITLE
[Feature Request]: improve data type conversion error message

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3752]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

MO have many data type conversion errors. We need to distinguish:
1. the conversions MO will never support.
2. the conversions will be supported but not in the current release.
3. something goes wrong in the process of conversion, such as overflow.

And every function should have its own data conversion rules.

**Comment by JinHai-CN** [comment]
Already involved in #3435
