### ISSUE TITLE
[Bug]: mo-server crash

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3759]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

panic: runtime error: index out of range [64] with length 64

goroutine 212 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*BitmapAllocator).Allocate(0xc003919b00, 0x200)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go:253 +0x436
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Log).Append(0xc00451adb0, 0xc0854d6480)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/log.go:290 +0x60c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Log).RemoveInode(0xc00451adb0, 0xc0854d6480)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/log.go:213 +0x2f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).ReleaseFile(0xc0004cc9a0, 0xc0854d6480)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:258 +0xd9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*DriverFile).Destroy(...)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/file.go:287
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*DriverFile).close(0x115800?)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/file.go:283 +0x25
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.(*RefHelper).Unref(0x0?)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/common/refs.go:50 +0x36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*dataFile).Destroy(0xc0004cd570)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/data.go:155 +0x94
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*columnBlock).Destroy(0xc0045207d0)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/colblk.go:169 +0x134
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*columnBlock).close(0x249cd88?)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/colblk.go:158 +0x19
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/common.(*RefHelper).Unref(0xc00192f260?)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/common/refs.go:50 +0x36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*blockFile).Destroy(0xc003919c80)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/dataio/segmentio/block.go:168 +0xdf
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).Destroy(0x3109e4e?)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/tables/block.go:172 +0x16f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*BlockEntry).DestroyData(...)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/catalog/block.go:222
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.gcBlockClosure.func1()
        /home/ftian/m/matrixone/pkg/vm/engine/tae/db/gcop.go:46 +0xf2
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*FnTask).Execute(0xc0004ae240?)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/tasks/types.go:122 +0x1b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc0057f76c0)
        /home/ftian/m/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x6f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0002fae70, {0x7ff528353c28, 0xc020beb090})
        /home/ftian/m/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:214 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start.func1()
        /home/ftian/m/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:144 +0xad
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).Start
        /home/ftian/m/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:136 +0xb6
ftian@DESKTOP-16FCU43:~/m/matrixone$

**Comment by LeftHandCold** [comment]
The block file for this segment has reached the upper limit of 4096. Please enter the schema of the table.What is the rows of the table?

**Comment by aressu1985** [comment]
fixed
