### ISSUE TITLE
[Question]: The IR generator has implemented？

### ISSUE THREAD

**Issue by Linary** [matrixorigin/matrixone#3764]
### Describe your problem

If it has been implemented, please tell me its position in the code. I am learning something related to llvm and want to refer to it.

**Comment by dengn** [comment]
> ### Describe your problem
> If it has been implemented, please tell me its position in the code. I am learning something related to llvm and want to refer to it.

Hi, this has not been implemented yet. It's kind of long term feature.

**Comment by Linary** [comment]
Thanks.
