### ISSUE TITLE
[Bug]: The size of mo store increase very horrible as the concurrent queries are runnning continuously

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3771]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.05
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The queries are:
"select c from sbtest{tbx} where id = {id};"
"insert into sbtest3 values({i_id},4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');"
 "delete from sbtest3 where id={i_id};"

the execution duration is more than 10 hours, then the size of the store is more than 35G
[sudong@mo-srv-128 matrixone]$ du -sh store/
35G	store/
[sudong@mo-srv-128 matrixone]$

**Comment by aptend** [comment]
Actually, there are about 10G table data in files with suffix `.seg`.  Given ~40 bytes per row and ~3 billion rows in table `sql_latency_seconds`, the raw data is ~120G, so it seems to be a reasonable compression ratio

**Comment by aressu1985** [comment]
fixed
