### ISSUE TITLE
[Bug]: TAE transaction bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3776]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6e20c2b69a253d9cd476f2fea506fb067904f288
- Hardware parameters: Mac M1, ARM 16GB
- OS type: OSX
- Others:
```

### Actual Behavior

Not sure what happened..but it looks like a bug...

mysql> drop table if exists test_11;
Query OK, 0 rows affected (0.04 sec)

mysql> begin;
Query OK, 0 rows affected (0.11 sec)

mysql> create table test_11 (c int primary key,d int);
Query OK, 0 rows affected (0.76 sec)

mysql> Insert into test_11 values(1,1);
Query OK, 1 row affected (0.02 sec)

mysql> Insert into test_11 values(2,2);
Query OK, 1 row affected (0.00 sec)

mysql> begin;
ERROR 1105 (HY000): begin txn in the began txn
mysql> select * from test_11;
ERROR 1105 (HY000): table "test_11" does not exist
mysql> rollback;
ERROR 1105 (HY000): the txn has not been began
mysql> rollback;
ERROR 1105 (HY000): the txn has not been began
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test_11;
ERROR 1105 (HY000): table "test_11" does not exist
mysql> drop table if exists test_11;
Query OK, 0 rows affected (0.01 sec)

mysql> begin;
ERROR 1105 (HY000): begin txn in the began txn
mysql> rollback;
ERROR 1105 (HY000): the txn has not been began
mysql> commit;
ERROR 1105 (HY000): the txn has not been began
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> create table test_11 (c int primary key,d int);
ERROR 1105 (HY000): tae txn: w-w conflict error

**Comment by daviszhen** [comment]
the behaviors of "begin...begin" is changed in pr #3784 .
But i have no idea about w-w conflict.

**Comment by jiangxinmeng1** [comment]
The last transaction conflicts with the first transaction. They both write table test_11.

**Comment by dengn** [comment]
Fixed.
