### ISSUE TITLE
[Bug]: the mo do not abort txn when error occured in the txn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3777]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> drop table if exists test_11;
Query OK, 0 rows affected (0.00 sec)

mysql> create table test_11 (c int primary key,d int);
Query OK, 0 rows affected (0.00 sec)

mysql> Insert into test_11 values(1,1);
Query OK, 1 row affected (0.00 sec)

mysql> Insert into test_11 values(2,2);
Query OK, 1 row affected (0.00 sec)

mysql> 
mysql> 
mysql> begin
    -> ;
Query OK, 0 rows affected (0.00 sec)

mysql> Insert into test_11 values(3,3);
Query OK, 1 row affected (0.00 sec)

mysql> Insert into test_11 values(2,2);
ERROR 1105 (HY000): tae data: duplicate
mysql> 
mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> select *         from test_11;
+------+------+
| c    | d    |
+------+------+
|    1 |    1 |
|    2 |    2 |
|    3 |    3 |
+------+------+
3 rows in set (0.00 sec)

this will cause the update before the error to be commited,and break the atomicity

**Comment by daviszhen** [comment]
The behavior is same as mysql

**Comment by aressu1985** [comment]
not a bug
