### ISSUE TITLE
[Bug]: The RT increase continuously when execute update statements with high concurrency

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3780]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When execute insert statements with high concurrency，the response time increase continuously

**Comment by XuPeng-SH** [comment]
performance issue. Marked as a 0.6 task

**Comment by XuPeng-SH** [comment]
Performance should be tracked after 0.6.

**Comment by XuPeng-SH** [comment]
0.7

**Comment by XuPeng-SH** [comment]
It was tested based on 0.5.
After checking with @aressu1985, assign it back

**Comment by aressu1985** [comment]
this will be re tested in 0.7.0, and can be closed
