### ISSUE TITLE
[Feature Request]: UNIQUE KEY support

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3783]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
we have showcase SQL using a lot of secondary index Key and Unique Key:


CREATE TABLE IF NOT EXISTS `t_code_rule` (
  `code_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code_no` varchar(50) NOT NULL,
  `org_no` varchar(50) NOT NULL,
  `org_name` varchar(50) NOT NULL,
  `ancestors` varchar(255) NOT NULL,
  `code_rule_no` varchar(50) NOT NULL,
  `code_rule_name` varchar(50) NOT NULL,
  `code_name` varchar(50) NOT NULL,
  `code_type` int(11) NOT NULL DEFAULT '0',
  `split` varchar(50) DEFAULT NULL,
  `remark` varchar(255),
  `create_time` datetime NOT NULL,
  `create_user` varchar(50) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `last_update_user` varchar(50) DEFAULT NULL,
  `is_system_code` varchar(2)  NOT NULL DEFAULT 'N',
  PRIMARY KEY (`code_id`),
  UNIQUE KEY `code_type` (`code_type`),
  KEY `code_no` (`code_no`),
  KEY `code_rule_no` (`code_rule_no`),
  KEY `org_no` (`org_no`)
);
```

### Describe the feature you'd like

For Unique Key, we need to support the SQL and guarantee the insert uniqueness. We may not have query acceleration related to key and unique key.

**Comment by fengttt** [comment]
These can be supported by encoding 2nd unique key (a hidden/2nd key table).   
@dengn please consider moving it to P2.

**Comment by domingozhang** [comment]
In DDL, we need a synonym as replacing KEY to INDEX as following

  UNIQUE INDEX `code_type` (`code_type`),
  INDEX`code_no` (`code_no`),
  INDEX `code_rule_no` (`code_rule_no`),
  INDEX `org_no` (`org_no`)

**Comment by bbbearxyz** [comment]
will support later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by florashi181** [comment]
@dengn close this one~

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
most of the code is complete, now do some test and fix bug.

**Comment by bbbearxyz** [comment]
will solve it after unique index pr is merge

**Comment by heni02** [comment]
test done except performace test ，pr merged
