### ISSUE TITLE
[Bug]: result of TPCH is different from other database

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3785]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select
  sum(l_extendedprice * l_discount) as revenue
from
  lineitem
where
  l_shipdate >= date '1994-01-01'
  and l_shipdate < date '1994-01-01' + interval '1' year
  and l_discount between .06 - 0.01 and .06 + 0.01
  and l_quantity < 24;

MO result is 
75207768.1855

other database is 
123141078.2283

**Comment by aressu1985** [comment]
fixed
