### ISSUE TITLE
[Feature Request]: Examination points for distributed cluster of MO

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3790]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In 0.6.0, MO will provide these features as following in distributed level:

- [ ] #3685 
- [ ] #3728 
- [ ] #3729 
- [ ] #3727 
- [ ] #3730 
- [x] #3115 
- [x] #3116  
- [x] #3940 

This issue will be broken down into several more sub-feature issues:
#3685 #3727 #3728 #3729 #3730 #3115 #3116 #3527 #2716 #2759 #2757 #2758 #3516 #3505 #3528 #3790

**Comment by fengttt** [comment]
@JinHai-CN I am not sure what is actionable on this.   Is this part of planning?
