### ISSUE TITLE
[Feature Request]: Support client-to-server encrypted communication

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#3791]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

client-to-server encryption(using TLS) for communication between clients and nodes when using CLIs, ORMs and etc.

**Comment by ouyuanning** [comment]
like #3337

**Comment by ouyuanning** [comment]
the work to add COALESCE function is not finished yet.
ssl support will delay one day.

**Comment by ouyuanning** [comment]
dependent on goetty to support TLS （this subtask will finish in 08-20）
so change the end time of this issue.

**Comment by aylei** [comment]
will mo support rotating certificates on the fly (without restart)?

**Comment by ouyuanning** [comment]
yes. just like MySQL
TLS upgrade process：
1、 server start (with no SSL)
2、client -> server  (tcp connect)
3、server -> client ( ask client if you can support ssl)
4、client -> server (response if client can support ssl)
5、（if client support ssl),     server do tlsUpgrade handshake in the connection.

**Comment by ouyuanning** [comment]
work fine in lots of ENV  but  ubuntu+golang1.19 in docker
I add an issue #4656 for that
