### ISSUE TITLE
[Bug]: some log error occure duration query with hight concurrency for long time 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3823]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2022/07/08 10:09:01.217743 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0x40005969c0 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/matrixone/pkg/frontend/routine.go:112"}
{"level":"ERROR","time":"2022/07/08 10:09:01.217811 +0800","caller":"logutil/api.go:63","msg":"routine send response failed &{1 0 3 0x40005969c0 0 0 0}. error:illegal state ","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/matrixone/pkg/frontend/routine.go:112"}

**Comment by daviszhen** [comment]
I think something happened in the connection between client and mo server. But I do not know the reason. As mentioned by @aressu1985 , the bvt worked well the situation happend. So, currently, it does not affect anything.

**Comment by aressu1985** [comment]
fixed
