### ISSUE TITLE
[Feature Request]: table function framework

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3840]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

select * from table_function(...);

Esp, the following case is extremely useful
-- return 1, 2, 3, 4, 5 ...
select * from generate_series(start, end, step);

-- system or table information
-- return zonemap info of the table
select * from zonemap_info(tablename, column);

-- system function
-- all current sessions (of this account).
select * from current_sessions();

### Describe implementation you've considered

Register system table functions, which can,
1. determine input param types.
2. check permission
3. report schema
4. impl, let's do generate_series first.

**Comment by daviszhen** [comment]
I think the table function framework has been done.
