### ISSUE TITLE
[Bug]: mo error and panic when run the bvt,tpch,tp simultaneously

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3856]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2022/07/10 23:05:43.365825 +0800","caller":"logutil/api.go:63","msg":"get table qn error tae catalog: not found","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation\n\t/root/matrixone/pkg/frontend/session.go:667\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve\n\t/root/matrixone/pkg/frontend/session.go:688\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1141\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1106\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder\n\t/root/matrixone/pkg/sql/plan/build.go:39\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan\n\t/root/matrixone/pkg/sql/plan/build.go:58\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize\n\t/root/matrixone/pkg/sql/plan/optimize.go:45\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1360\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1333\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1625\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/matrixone/pkg/frontend/routine.go:106"}
{"level":"ERROR","time":"2022/07/10 23:05:43.366462 +0800","caller":"logutil/api.go:63","msg":"get table qn2 error tae catalog: not found","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation\n\t/root/matrixone/pkg/frontend/session.go:667\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve\n\t/root/matrixone/pkg/frontend/session.go:688\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1141\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1106\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1106\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder\n\t/root/matrixone/pkg/sql/plan/build.go:39\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan\n\t/root/matrixone/pkg/sql/plan/build.go:58\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize\n\t/root/matrixone/pkg/sql/plan/optimize.go:45\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1360\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1333\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1625\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/matrixone/pkg/frontend/routine.go:106"}
{"level":"ERROR","time":"2022/07/10 23:05:43.366982 +0800","caller":"logutil/api.go:63","msg":"get table qn error tae catalog: not found","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation\n\t/root/matrixone/pkg/frontend/session.go:667\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve\n\t/root/matrixone/pkg/frontend/session.go:688\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1141\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1106\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1106\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1167\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder\n\t/root/matrixone/pkg/sql/plan/build.go:39\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan\n\t/root/matrixone/pkg/sql/plan/build.go:58\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize\n\t/root/matrixone/pkg/sql/plan/optimize.go:45\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1360\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1333\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1625\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/matrixone/pkg/frontend/routine.go:106"}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc0c4c]

goroutine 93 [running]:
os.(*File).Name(...)
        /usr/local/go/src/os/file.go:57
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Mount(0x4133475c80)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:171 +0x14c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Open(0x4133475c80, {0x4194d5d5a8, 0x13})
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:126 +0x310
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.openSegment({0x4194d5d5a8, 0x13}, 0x83cf)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:81 +0xe0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFactory).Build(0x401a9f5748?, {0x40001b3710, 0xb}, 0x50?)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:45 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.newSegment(0x4262bc04c0, {0x140e0f0?, 0x1d1d230?}, {0x1424cc0?, 0x4000110540}, {0x40001b3710?, 0x401a9f5800?})
        /root/matrixone/pkg/vm/engine/tae/tables/segment.go:41 +0x58
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*DataFactory).MakeSegmentFactory.func1(0x401a9f5918?)
        /root/matrixone/pkg/vm/engine/tae/tables/factory.go:52 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.NewSegmentEntry(0x42e7ca5b80, {0x1435f38?, 0x425ad7bd60}, 0x0, 0x425ad7bf40)
        /root/matrixone/pkg/vm/engine/tae/catalog/segment.go:59 +0x1d4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*TableEntry).CreateSegment(0x42e7ca5b80, {0x1435f38, 0x425ad7bd60}, 0x80?, 0x401a9f58c8?)
        /root/matrixone/pkg/vm/engine/tae/catalog/table.go:155 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).CreateSegment(0x40c5849d90)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:172 +0x68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).prepareApplyNode(0x4133475800, {0x14356c0?, 0x40e8be60e0})
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:141 +0x1e0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).PrepareApply(...)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:125
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PreCommit(0x401a9f5ae8?)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:668 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PreCommit(0x4253c47cc0)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:329 +0x104
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PreCommit(0x401a9f5c08?)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:366 +0x80
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PreCommit(0xffff9c070a68?)
        /root/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:242 +0x2c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreCommit(0x11fdc06?, {0x1435dc8, 0x426a00c9c0})
        /root/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:131 +0x4c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreparing(0x4000293180, {0x4000244000, 0x1, 0x0?})
        /root/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:156 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
        /root/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:83 +0x1b4
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
        /root/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:62 +0xf4
~

**Comment by daviszhen** [comment]
Errror message:
get table qn error tae catalog: not found

get table qn2 error tae catalog: not found",

It means plan does not find the table in tae.

TAE generates a crash report.

**Comment by LeftHandCold** [comment]
same as https://github.com/matrixorigin/matrixone/issues/3159

**Comment by aressu1985** [comment]
fixed
