### ISSUE TITLE
[Bug]: Instance hangs while loading big size csv

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#3858]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the size of csv is about 230GB.

mysql> load data infile '/data/zhangxiao/ssb600m/lineorder_flat_600m.tbl' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (111)
ERROR: 
Can't connect to the server

### Additional information

panic: logic err

goroutine 102 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*vFile).Sync(0xc786c00160)                                                                                          
        /data/zhangxiao/matrixone/pkg/vm/engine/tae/logstore/store/vfile.go:179 +0x3f8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*rotateFile).Sync(0x0?)
        /data/zhangxiao/matrixone/pkg/vm/engine/tae/logstore/store/file.go:372 +0x105
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).onSyncs(0xc0001aa240, {0xc656cae280, 0x1, 0xc78783f538?})                                               
        /data/zhangxiao/matrixone/pkg/vm/engine/tae/logstore/store/store.go:306 +0x3e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).syncLoop(0xc0001aa240)                                                                                  
        /data/zhangxiao/matrixone/pkg/vm/engine/tae/logstore/store/store.go:218 +0xdb
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.(*baseStore).start                                                                                        
        /data/zhangxiao/matrixone/pkg/vm/engine/tae/logstore/store/store.go:120 +0xad

**Comment by domingozhang** [comment]
60GB can be loaded successfully

**Comment by domingozhang** [comment]
/dev/mapper/vg01-lv01  879G  659G  176G  79% /data
When this volume  is about 79%, size of it doesn't increase any more.

**Comment by XuPeng-SH** [comment]
Stability-related problems, solve it @ 0.6.

**Comment by LeftHandCold** [comment]
This problem may be caused by the error caused by the disk being full

**Comment by jiangxinmeng1** [comment]
update panic info in #5372
