### ISSUE TITLE
[Bug]: EXPLAIN update bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3861]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):63279fddcaf86eb187942b5d9800ed678930cd5f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select * from t1;
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
4 rows in set (0.00 sec)

mysql> explain (verbose true) update t1 set a = 10 where a =1;
ERROR 1105 (HY000): Column 'PADDR' does not exist

**Comment by qingxinhome** [comment]
OK, I will fix the explain for dml bug and organize a document

**Comment by dengn** [comment]
Fixed.
