### ISSUE TITLE
[Bug]: some txn error when run mixed cases

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3868]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2022/07/10 14:48:53.616874 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:buffer: no space left txnError:buffer: no space left","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/home/sudong/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1467\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1773\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/home/sudong/matrixone/pkg/frontend/routine.go:106"}
{"level":"ERROR","time":"2022/07/10 14:48:53.624613 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/home/sudong/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1467\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1794\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/home/sudong/matrixone/pkg/frontend/routine.go:106"}
{"level":"ERROR","time":"2022/07/10 14:48:53.625181 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/home/sudong/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1467\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1794\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/home/sudong/matrixone/pkg/frontend/routine.go:106"}
{"level":"ERROR","time":"2022/07/10 14:48:53.625739 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/home/sudong/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1467\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1794\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/home/sudong/matrixone/pkg/frontend/routine.go:106"}
{"level":"ERROR","time":"2022/07/10 14:48:53.626516 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/home/sudong/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/home/sudong/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1467\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1794\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/home/sudong/matrixone/pkg/frontend/mysql_cmd_executor.go:1900\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/home/sudong/matrixone/pkg/frontend/routine.go:106"}

**Comment by daviszhen** [comment]
almost the same as #3843

**Comment by daviszhen** [comment]
sudong provided the related server log when the issue happened.
I think tae txn was wrong when issue happened. So the frontend reported the error.
[server.log.gz](https://github.com/matrixorigin/matrixone/files/9081122/server.log.gz)

**Comment by aressu1985** [comment]
{"level":"ERROR","time":"2022/07/13 11:30:21.366876 +0800","caller":"logutil/api.go:63","msg":"[Metric] insert error. sql: insert into system_metrics.process_open_fds values (\"2022-07-13 11:30:18\", 150.000000,0,\"monolithic\"); err: the txn is in the illegal state and needed to be cleaned before using again","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:218"}
{"level":"ERROR","time":"2022/07/13 11:30:21.366943 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/root/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1478\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1805\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*internalExecutor).Exec\n\t/root/matrixone/pkg/frontend/internal_executor.go:60\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:217"}
{"level":"ERROR","time":"2022/07/13 11:30:21.366981 +0800","caller":"logutil/api.go:63","msg":"[Metric] insert error. sql: insert into system_metrics.process_cpu_percent values (\"2022-07-13 11:30:18\", 187.634682,0,\"monolithic\"); err: the txn is in the illegal state and needed to be cleaned before using again","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:218"}
{"level":"ERROR","time":"2022/07/13 11:30:21.674507 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/root/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1478\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1805\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*internalExecutor).Exec\n\t/root/matrixone/pkg/frontend/internal_executor.go:60\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:217"}
{"level":"ERROR","time":"2022/07/13 11:30:21.674552 +0800","caller":"logutil/api.go:63","msg":"[Metric] insert error. sql: insert into system_metrics.sql_statement_total values (\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"0\",\"delete\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"0\",\"insert\"),(\"2022-07-13 11:30:18\", 4.199936,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"0\",\"select\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"0\",\"update\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"1\",\"delete\"),(\"2022-07-13 11:30:18\", 0.666656,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"1\",\"other\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"1\",\"select\"),(\"2022-07-13 11:30:18\", 0.000000,0,\"monolithic\",\"1\",\"update\"); err: the txn is in the illegal state and needed to be cleaned before using again","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:218"}
{"level":"ERROR","time":"2022/07/13 11:30:33.067664 +0800","caller":"logutil/api.go:63","msg":"clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again txnError:<nil>","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).CleanTxn\n\t/root/matrixone/pkg/frontend/session.go:592\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery.func1\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1478\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1805\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*internalExecutor).Exec\n\t/root/matrixone/pkg/frontend/internal_executor.go:60\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:217"}
{"level":"ERROR","time":"2022/07/13 11:30:33.067725 +0800","caller":"logutil/api.go:63","msg":"[Metric] insert error. sql: insert into system_metrics.sql_latency_seconds values (\"2022-07-13 11:30:05\", 0.000138,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:05\", 0.000137,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:05\", 0.000276,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:05\", 0.000408,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:06\", 0.000112,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:06\", 0.000315,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:06\", 0.000217,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:06\", 0.000275,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:06\", 0.000265,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:18\", 0.000302,0,\"monolithic\",\"1\",\"insert\"),(\"2022-07-13 11:30:12\", 0.000124,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000137,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000104,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000094,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000095,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000095,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000097,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000110,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000112,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000110,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000104,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000103,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000095,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000099,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000091,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000104,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000106,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000098,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000088,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000106,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000094,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000100,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000098,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000099,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000105,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000097,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000095,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000100,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000100,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000124,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000106,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000098,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000090,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000102,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000102,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000095,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000100,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000094,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000101,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000086,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000104,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000096,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000090,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000091,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000105,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000110,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000114,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000103,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000088,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000105,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000100,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000093,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000089,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000114,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000096,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000197,0,\"monolithic\",\"0\",\"other\"),(\"2022-07-13 11:30:13\", 0.000125,0,\"monolithic\",\"0\",\"other\"); err: the txn is in the illegal state and needed to be cleaned before using again","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/util/metric.(*metricCollector).sqlWorker\n\t/root/matrixone/pkg/util/metric/metric_collector.go:218"}

**Comment by daviszhen** [comment]
In pr https://github.com/matrixorigin/matrixone/pull/3948
We remove the error "clean txn. Get error:the txn is in the illegal state and needed to be cleaned before using again".
We replace it by "start tae txn error:XXX" or "commit tae txn error:XXX" or "rollback tae txn error:XXX" based on the situation when the error happens.

**Comment by aressu1985** [comment]
fixed
