### ISSUE TITLE
[Bug]: cast boolean to varchar gives syntax error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3869]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):408bd69dc8a4d869adf5cdad49d2d9eebd6e01d7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO supports explicit and implicit conversion from boolean to varchar. But only char works. 

mysql> select cast(false as char);
+---------------------+
| cast(false as char) |
+---------------------+
| 0                   |
+---------------------+
1 row in set (0.02 sec)

mysql> select cast(true as char);
+--------------------+
| cast(true as char) |
+--------------------+
| 1                  |
+--------------------+
1 row in set (0.01 sec)

mysql> select cast(true as varchar);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 28 near 'varchar';
mysql> select cast(false as varchar);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 29 near 'varchar';

**Comment by iamlinjunhong** [comment]
mysql doesn't support select cast(true as varchar)
