### ISSUE TITLE
[Bug]: cast from datetime to timestamp syntax error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3874]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 408bd69dc8a4d869adf5cdad49d2d9eebd6e01d7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO should support explicit and implicit conversion from datetime to timestamp. 

mysql> create table t2(b datetime);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t2 values("2022-01-01 01:23:34");
Query OK, 1 row affected (0.07 sec)

mysql> select cast(b as timestamp) from t2;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 27 near 'timestamp';

mysql> select from_unixtime(b) from t2;
ERROR 1105 (HY000): Function 'from_unixtime' with parameters [DATETIME] will be implemented in future version.

**Comment by aunjgr** [comment]
Casting from datetime to timestamp should be normal after applying #4502. Please confirm.

from_unixtime can only accept integer argument.

**Comment by sukki37** [comment]
@qingxinhome pls take a look at the `from_unixtime` problem, thank you.

**Comment by dengn** [comment]
Different behavior with MySQL. 

MySQL:
```
mysql> create table t2(b datetime);
Query OK, 0 rows affected (0.25 sec)

mysql> insert into t2 values("2022-01-01 01:23:34");
Query OK, 1 row affected (0.01 sec)

mysql> select cast(b as timestamp) from t2;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'timestamp) from t2' at line 1
mysql> select from_unixtime(b) from t2;
+------------------+
| from_unixtime(b) |
+------------------+
| NULL             |
+------------------+
1 row in set (0.00 sec)
```

MO:
```
mysql> create table t2(b datetime);
Query OK, 0 rows affected (0.04 sec)

mysql>  insert into t2 values("2022-01-01 01:23:34");
Query OK, 1 row affected (0.14 sec)

mysql> select cast(b as timestamp) from t2;
+--------------------------+
| cast(b as timestamp(26)) |
+--------------------------+
| 2022-01-01 01:23:34      |
+--------------------------+
1 row in set (0.04 sec)

mysql> select from_unixtime(b) from t2;
ERROR 20203 (HY000): invalid argument function from_unixtime, bad value [DATETIME]
```
