### ISSUE TITLE
[Bug]: cast float to varchar syntax error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3880]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 408bd69dc8a4d869adf5cdad49d2d9eebd6e01d7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select cast(1.111 as varchar);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 29 near 'varchar';
mysql> select cast(1.111 as char);
+---------------------+
| cast(1.111 as char) |
+---------------------+
| 1.111               |
+---------------------+
1 row in set (0.01 sec)

**Comment by fengttt** [comment]
This seems to be a real bug.

**Comment by dengn** [comment]
Fixed.

mysql> select cast(1.111 as varchar);
+------------------------+
| cast(1.111 as varchar) |
+------------------------+
| 1.111                  |
+------------------------+
1 row in set (0.00 sec)
