### ISSUE TITLE
[Bug]: cast int/decimal to timestamp syntax error 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#3881]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 408bd69dc8a4d869adf5cdad49d2d9eebd6e01d7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select cast(1000000 as timestamp);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 33 near 'timestamp';

mysql> create table t3(a decimal(38,19));
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t3 values (1004.14123), (1341321);
Query OK, 2 rows affected (0.03 sec)

mysql> select cast(a as timestamp) from t3;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at position 27 near 'timestamp';

**Comment by fengttt** [comment]
Whatever the big table says about cast number to timestamp :)

**Comment by aressu1985** [comment]
fixed

mysql> select cast(1000000 as timestamp);
+--------------------------------+
| cast(1000000 as timestamp(26)) |
+--------------------------------+
| 1970-01-12 21:46:40            |
+--------------------------------+
1 row in set (0.00 sec)

mysql>
