### ISSUE TITLE
[Feature Request]: data uploader

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#3924]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Upload data to remote object storage.
<img src="https://user-images.githubusercontent.com/39627130/177835047-100b73a3-7516-4cc0-a670-e84e3ec52f48.png" height="70%" width="70%" />

**Comment by LeftHandCold** [comment]
#4972
