### ISSUE TITLE
[Feature Request]: tae works as a participant in a distributed transaction - (DN)

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#3929]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. work as a coordinator or a normal participant
2. transaction state machine
3. prepare|flush|committing|commit pipeline
4. RPC handle
5. Replay
6. dn transaction workspace

**Comment by triump2020** [comment]
- [ ] 2PC replay
- [ ] Maybe need to log a 2PC Rollback.

**Comment by triump2020** [comment]
TODO::
- [ ] 2PC replay
- [ ] Maybe need to log a 2PC Rollback.

**Comment by triump2020** [comment]
pls ref to #6899
