### ISSUE TITLE
[Bug]: mo crash for invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3930]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

"level":"ERROR","time":"2022/07/12 21:44:48.747406 +0800","caller":"logutil/api.go:63","msg":"get table qn error tae catalog: not found","stacktrace":"github.com/matrixorigin/matrixone/pkg/logutil.Errorf\n\t/root/matrixone/pkg/logutil/api.go:63\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation\n\t/root/matrixone/pkg/frontend/session.go:667\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve\n\t/root/matrixone/pkg/frontend/session.go:688\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1126\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1152\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1091\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1152\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1091\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1152\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom\n\t/root/matrixone/pkg/sql/plan/query_builder.go:1017\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect\n\t/root/matrixone/pkg/sql/plan/query_builder.go:625\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder\n\t/root/matrixone/pkg/sql/plan/build.go:39\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan\n\t/root/matrixone/pkg/sql/plan/build.go:58\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize\n\t/root/matrixone/pkg/sql/plan/optimize.go:45\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1371\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1344\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1636\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/root/matrixone/pkg/frontend/mysql_cmd_executor.go:1911\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/root/matrixone/pkg/frontend/routine.go:106"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc4d9c]

goroutine 147 [running]:
os.(*File).Name(...)
        /usr/local/go/src/os/file.go:57
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Mount(0x40c99e1180)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:171 +0x14c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Op
en(0x40c99e1180, {0x40ae270c00, 0x13})

github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Mount(0x40c99e1180)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:171 +0x14c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*Driver).Open(0x40c99e1180, {0x40ae270c00, 0x13})
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/driver.go:126 +0x310
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.openSegment({0x40ae270c00, 0x13}, 0xa8d2)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:81 +0xe0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFactory).Build(0x40007c9748?, {0x40003aaec0, 0xb}, 0x50?)
        /root/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:45 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.newSegment(0x41c9ca6c80, {0x13efb50?, 0x1ced0c8?}, {0x14055e0?, 0x40001a6840}, {0x40003aaec0?, 0x40007c9800?})
        /root/matrixone/pkg/vm/engine/tae/tables/segment.go:41 +0x58
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*DataFactory).MakeSegmentFactory.func1(0x0?)
        /root/matrixone/pkg/vm/engine/tae/tables/factory.go:52 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.NewSegmentEntry(0x4001056980, {0x14172f8?, 0x41b0f95a90}, 0x0, 0x407df16080)
        /root/matrixone/pkg/vm/engine/tae/catalog/segment.go:59 +0x1d4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*TableEntry).CreateSegment(0x4001056980, {0x14172f8, 0x41b0f95a90}, 0x80?, 0x40007c98c8?)
        /root/matrixone/pkg/vm/engine/tae/catalog/table.go:155 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).CreateSegment(0x454b9066e0)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:172 +0x68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).prepareApplyNode(0x40c99e0c80, {0x1416a80?, 0x418d0d0cb0})
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:141 +0x1e0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).PrepareApply(...)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:125
        /root/matrixone/pkg/vm/engine/tae/tables/factory.go:52 +0x3c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.NewSegmentEntry(0x4001056980, {0x14172f8?, 0x41b0f95a90}, 0x0, 0x407df16080)
        /root/matrixone/pkg/vm/engine/tae/catalog/segment.go:59 +0x1d4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*TableEntry).CreateSegment(0x4001056980, {0x14172f8, 0x41b0f95a90}, 0x80?, 0x40007c98c8?)
        /root/matrixone/pkg/vm/engine/tae/catalog/table.go:155 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).CreateSegment(0x454b9066e0)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:172 +0x68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).prepareApplyNode(0x40c99e0c80, {0x1416a80?, 0x418d0d0cb0})
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:141 +0x1e0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).PrepareApply(...)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:125
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PreCommit(0x40007c9ae8?)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:668 +0x90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PreCommit(0x412cf6ba40)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:329 +0x104
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PreCommit(0x40007c9c08?)
        /root/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:366 +0x80
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PreCommit(0xffffb6fbad78?)
        /root/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:242 +0x2c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreCommit(0x11e16f3?, {0x1417188, 0x41cb8ef080})
        /root/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:131 +0x4c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreparing(0x40001540e0, {0x4002f1c000, 0x1, 0x0?})
        /root/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:156 +0xb4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
        /root/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:83 +0x1b4
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
        /root/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:62 +0xf4

**Comment by LeftHandCold** [comment]
same as #3159

**Comment by aressu1985** [comment]
fixed
