### ISSUE TITLE
[Bug]: ln(-1) currently returns null, should be error

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#3934]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

for functions like ln, atan, etc, MySQL return null when we see invalid args.    This is simply wrong.    We should fix, raise error.   

### Expected Behavior

error.

### Additional information

I will do this after vector bitmap work and error message framework.   Maybe this is a good candidate for error framework example.

**Comment by fengttt** [comment]
This is very much like the overflow work.

**Comment by qingxinhome** [comment]
ok， I see
