### ISSUE TITLE
[Bug]: mo panic because of buffer: no space left

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#3961]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2022/07/14 00:42:26.988268 +0800","caller":"frontend/session.go:83","msg":"switch from 0 to 2"}
{"level":"INFO","time":"2022/07/14 00:42:26.988276 +0800","caller":"frontend/mysql_cmd_executor.go:1531","msg":"start autocommit txn in default"}
{"level":"INFO","time":"2022/07/14 00:42:26.988436 +0800","caller":"frontend/session.go:522","msg":"commit autocommit only"}
{"level":"WARN","time":"2022/07/14 00:42:27.259959 +0800","caller":"buffer/nodemgr.go:159","msg":"DoRetry Pin Node <0:1027-1027-1062-0-0> Times 13110: buffer: no space left"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb1a0ac]

goroutine 1729410393 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/model.(*ColumnView).Close(0x42d0569d28?)
	/mnt/disk2/matrixone/pkg/vm/engine/tae/model/colview.go:95 +0x1c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnBlock).Read(0x4036591e08, {0x453690?, 0x40451776c0?, 0x42d0569d60?}, {0x432b2a1e80, 0x2, 0x2}, {0xfffd4a77bcb8?, 0xffff8b9e0008?, 0x10?}, ...)
	/mnt/disk2/matrixone/pkg/vm/engine/tae/moengine/block.go:40 +0x360
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnReader).Read(0x42aecd0be0, {0x4036918ec0, 0x2, 0x2}, {0x432b2a1e80, 0x2, 0x2})
	/mnt/disk2/matrixone/pkg/vm/engine/tae/moengine/reader.go:53 +0x18c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0x4036591f10, {0x1408dc0, 0x42aecd0be0}, 0x4362475440)
	/mnt/disk2/matrixone/pkg/vm/pipeline/pipeline.go:69 +0x16c
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x16?, {0x14?, 0xffffffffffffffff?})
	/mnt/disk2/matrixone/pkg/sql/compile/scope.go:311 +0xac
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x40054a58f0?)
	/mnt/disk2/matrixone/pkg/sql/compile/scope.go:329 +0x68
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/disk2/matrixone/pkg/sql/compile/scope.go:324 +0x184

### Steps to Reproduce

```Markdown
run the bvt+tpch+tp mixed cases for about 6 hours.
```

**Comment by LeftHandCold** [comment]
#3962 Fixed bug with panic

**Comment by XuPeng-SH** [comment]
Stability-related problems, solve it @ 0.6.

**Comment by aressu1985** [comment]
commited: 9130c990223a1d709051cff79b27ce3de65aad67

fixed
