### ISSUE TITLE
[Bug]: HAKeeper missed cases

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#3988]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When stopping a zombie replica, checking epoch value alone is not enough. HAKeeper should check whether the concerned replica ID is a key of the Replicas map (i.e., whether the replica is still a current member of the shard).

When trying to start a replica, always check whether the target store is still considered as up and running.  

When repairing replicas, HAKeeper should check all stores to see is there any failed store. From the UUID of the failed store, HAKeeper should be able to figure out a list of impacted replicas (i.e. replicas that are suppose to run on the failed store). Some of those replicas might never got chance to be started. All such replicas should be repaired.

**Comment by w-zr** [comment]
can be closed now
