### ISSUE TITLE
[Feature Request]: Integration Testing Framework Extensions

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#4003]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
No
```

### Describe the feature you'd like

Adding network partition isolation and the ability to independently start and stop individual nodes to the integrated test framework

**Comment by cnutshell** [comment]
Support the basic operation and awareness methods, then we could add more necessary convenient methods in order to support more flexible test purpose.

**Comment by cnutshell** [comment]
With PR #4311, we have found different bugs or flaws, which is the exact purpose of this service integration test framework. The related bug or flaw could be learned from PR #4324, PR #4318, and issue #4334. 

There should be another issue created, But I fixed that issue manually in this PR #4311 within commit [73decf2](https://github.com/matrixorigin/matrixone/pull/4311/commits/73decf23bd0816740411373da20fe0e4e7267539), as a result of the slow pace of `issue -> PR -> merge`.

In view of this, I've change the plan to accomplish this integration test framework. And the pre-defined timeline should be rectified also.

**Comment by cnutshell** [comment]
Now, I've implemented basic features for this test framework.
Next, I will continue on the simulation of network partition.

**Comment by cnutshell** [comment]
For network partition feature in this integration test framework,  we implement logic at the side of `morpc.Client` by taking its option `morpc.WithBackendFilter`.

**Comment by cnutshell** [comment]
All the basic features were completed.
There may be some necessary updates needed in order to cope with practical requirements in using.
