### ISSUE TITLE
[Bug]: Version of MO is still 0.4.0

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4004]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In 0.5.0 branch, the version of MO is still 0.4.0.

Server version: 0.4.0 MatrixOne

**Comment by daviszhen** [comment]
Now it was fixed on branch 0.5.0.
===============================
➜  mo-tester git:(main) ✗ mysql -h 127.0.0.1 -P 6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1001
Server version: 0.5.0 MatrixOne

Copyright (c) 2000, 2021, Oracle and/or its affiliates.
