### ISSUE TITLE
[Feature Request]: Support uuid function 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4019]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Such as MySQL, the uuid funciton will return column's uuid in storage level. 

create table t1(a varchar(20));
insert into t1 values('123123sdafsdf');

select uuid(),a from t1;
+--------------------------------------+---------------+
| uuid()                               | a             |
+--------------------------------------+---------------+
| 976efd08-041a-11ed-a36c-c48e7bbf4d43 | 123123sdafsdf |
+--------------------------------------+---------------+

**Comment by fengttt** [comment]
uuid() is just a new function.    It is arguably important enough so that we create a uuid type.

**Comment by qingxinhome** [comment]
mysql UUID: https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid

**Comment by qingxinhome** [comment]
This feature request of uuid function has been fixed, unit test and bvt test have been completed, and now request acceptance test, please know！ @fengttt @domingozhang @daviszhen @aressu1985

**Comment by fengttt** [comment]
Let me reactivate this one and repurpose it.

Can we add a UUID type?  [16]byte.   Just 3 functions on this, cast/parse string to uuid, cast uuid to string, and uuid1 equal uuid2.

**Comment by qingxinhome** [comment]
The feature requests related to uuid type and uuid function had been fixed, unit test and bvt test have been completed, and now request acceptance test, please know！ @fengttt @yingfeng @daviszhen @domingozhang @aressu1985t
