### ISSUE TITLE
[Bug]: ResizePayload can't work

### ISSUE THREAD

**Issue by jiangxinmeng1** [matrixorigin/matrixone#4023]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

LogRecord ResizePayload can't work.

**Comment by lni** [comment]
@jiangxinmeng1 please review the fix and close the issue if you are happy with it. thanks.
