### ISSUE TITLE
[Enhancement]: system_vars_config.toml needs to be updated

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4072]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
As MatrixCube is removed, system_vars_config.toml still has several settings related to MatrixCube. 
And TAE is already the only storage engine, no more setting of storageEngine needs to be kept.
```

### Why is this needed ?

Clean the setting and gets it to make more sense.

**Comment by daviszhen** [comment]
it was fixed.
