### ISSUE TITLE
[Bug]: there is a bug when the varchar size is 1 G

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#4081]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when the varchar insert value is 1G, there is a bug in the transmation, The computation layer can't get varchar.

**Comment by fengttt** [comment]
@bbbearxyz Never assign bug back to the meow cat.   @zhangxu19830126  If it is fixed, dev should close issues like this.
