### ISSUE TITLE
[Feature Request]: Export databases or tables into SQL

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4093]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Such as mysqldump, MO needs a tool or a statement to export databases or tables into a SQL file with both DDL and DML. Then user can run the exported SQL file to recreate these objects.
T1
a
1
2
3
4
5

The exported SQL will be 
create table t1 (a int);
insert into t1 values(1),(2),(3),(4),(5);

**Comment by domingozhang** [comment]
@jianwan0214 
Need a tool or a command to get these item:
1. the DDL of tables
2. CSV files of data

Then use these DDL and CSV can be loaded and users can make sure the data is the same as previously.

**Comment by mooleetzi** [comment]
doc: https://docs.matrixorigin.io/0.6.0/MatrixOne/Develop/export-data/modump/

**Comment by heni02** [comment]
test done
