### ISSUE TITLE
[Feature Request]: Support TRUNCATE statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4095]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

_TRUNCATE [TABLE] tbl_name_

This is a DDL. No commit or rollback.

**Comment by qingxinhome** [comment]
The feature requests related to truncate statement had been fixed, unit test and bvt test have been completed, and now request acceptance test, please know！ @fengttt @daviszhen @yingfeng @florashi181 @domingozhang @aressu1985

**Comment by heni02** [comment]
test done ,bvt case done
