### ISSUE TITLE
[Feature Request]: Support database actions log wrting

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4096]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

As current design, all the database action can be traced into tables. As an extended requirement, this action also needs to be written into a log file.
- The log file has to record import actions of MO and critical internal error with account name, event type, timestamp and what happens.
- All the important actions of MO need to be recorded, including all DDL, all user operations, all nodes operations, all parameter modifications.
- Critical internal errors including the event disturbs MO working normally, such as removing a datafile manually or one node down.

**Comment by xzxiong** [comment]
- [x] The log file has to record import actions of MO and critical internal error with account name, event type, timestamp and what happens.
- [x] All the important actions of MO need to be recorded, including all DDL, all user operations, all nodes operations, all parameter modifications.
- [ ] Critical internal errors including the event disturbs MO working normally, such as removing a datafile manually or one node down.

**Comment by w-zr** [comment]
HAkeeper can output MO working status and which nodes are down.
But these are not printed currently, I will add this.

**Comment by xzxiong** [comment]
> * [x]  The log file has to record import actions of MO and critical internal error with account name, event type, timestamp and what happens.
>   
>   * [x]  error
>   * [x]  with account
>   * [x]  event type
>   * [x]  timestamp
>   * [x]  what happen
> * [x]  All the important actions of MO need to be recorded, including all DDL, all user operations, all nodes operations, all parameter modifications.
> * [ ]  Critical internal errors including the event disturbs MO working normally, such as removing a datafile manually or one node down.
>   
>   * [x]  MO working normally
>   * [ ]  removing a datafile manually
>   * [x]  node down

**"removing a datafile manually"**
those file exception, fileservice will log and return `not found` message.
@LeftHandCold could improve those mesage with filepath or db.table info in following version.
