### ISSUE TITLE
[Feature Request]: Support regular expressions funtion

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4097]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support these regular expressions funtion
NOT REGEXP
REGEXP
REGEXP_INSTR()
REGEXP_LIKE()	
REGEXP_REPLACE()
REGEXP_SUBSTR()
RLIKE

More details can be followed as :
https://dev.mysql.com/doc/refman/8.0/en/regexp.html

**Comment by goodMan-code** [comment]
This Feature Request has done, It can be closed, pls
