### ISSUE TITLE
[Feature Request]: Support unique index and secondary index

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4098]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

_CREATE [UNIQUE] INDEX index_name
    ON tbl_name (key_part,...)
    COMMENT 'string'_

_DROP INDEX index_name_

The UNIQUE index needs to removing duplicates.  
key_part can be multi columns.

**Comment by bbbearxyz** [comment]
now unique index is completed, please test it.

**Comment by bbbearxyz** [comment]
this issue now only about unique index, secondary I will implement it in the #3609

**Comment by heni02** [comment]
The test finds that the function is only partially implemented, and  back to bbbearxyz

**Comment by bbbearxyz** [comment]
will support later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by daviszhen** [comment]
@iamlinjunhong  setups a subtask for connecting the index with delete,select,insert,udpate and create/drop index;
@qingxinhome setups a subtask for totally maintains the sematics and implementation of the index

**Comment by fengttt** [comment]
2nd key tracked by https://github.com/matrixorigin/matrixone/issues/3609
