### ISSUE TITLE
[Enhancement]: $ in documentation as bash commands needs to be out of the copy range 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4110]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
MatrixOne has many bash commands in documentation starting with a $. Normally this $ is not the content for copy, need to improve that. 
May investigate how CRDB has this working.
https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html
```

**Comment by lacrimosaprinz** [comment]
【调研与沟通情况】
1. 我们theme样式中代码块的基本形式：
    - mkdocs theme里的代码样式，是不带$的；
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/43231571/180154785-b1e05cb2-d280-4a4f-a28f-2e49739706d8.png">
2. cockroach源码调研查看：
    - cockroachcloud的theme跟我们的不是同一套，他们的theme可以用 {% include_cached copy-clipboard.html %}约束代码行里的$;
【两个方法去解决】：
1. 徐恒帮忙看看前端能不能跟cockroachclou的theme一样保持行为一致，保留$但是不被复制；
2. 我们从文档源码里删除$
【修改成本评估与最终结果】
从文档源码中删除代码块里的$
【下一步】
由wangzinan按照讨论的最终结果将文档源码中代码块里的$删除
