### ISSUE TITLE
[Bug]: set logFilename in system_vars_config.toml doesn't work

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4111]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):89ec9341cafb1a5a8c638165fbb54cf4ce757ded
- Hardware parameters: 4C 16G
- OS type: CentOS
- Others:
```

### Actual Behavior

Set logFilename record in system_vars_config.toml before starting mo-server:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/4965857/179884720-53e08eea-c987-4921-823d-672e75414466.png">

Starting mo-server gets an error:
[root@VM-0-8-centos matrixone]# 2022/07/20 10:41:38.311728 +0800 INFO db-server/main.go:163 Load config error:update parameter logFilename failed.error:setLogFilename,the value mo.log is not in set []

**Comment by jianwan0214** [comment]
this param is deleted in current code

**Comment by dengn** [comment]
0.6 doesn't have the same parameter system. closing.
