### ISSUE TITLE
[Bug]: desc table is broken

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#4115]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> desc t;
+------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                               |
+------------------------------------------------------------------------------------------+
| Project(cost=0.00..0.00 card=88.00 ndv=0.00 rowsize=0)                                   |
|   ->  Table Scan on mo_catalog.mo_columns(cost=0.00..0.00 card=88.00 ndv=0.00 rowsize=0) |
|         Filter Cond: (mo_columns.att_database = 'foo'), (mo_columns.att_relname = 't')   |
+------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)

mysql>

### Expected Behavior

Describe the table, instead of explaining some query.

**Comment by tianyahui-python** [comment]
@fengttt can close issue, only issue owner is can close  issue.
