### ISSUE TITLE
[Bug]: TestReplay7 case panics in CI

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#4127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):762931838c0bce866d68a18e1a3a00721dc079bf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022/07/20 06:06:51.953022 +0000 INFO tables/node.go:208 [Running] {"operation": "UnloadOp", "operand": "<0:1000-1000-1001-0-0>", "timestamp": 2}
--- FAIL: TestReplay7 (0.39s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 10182 [running]:
testing.tRunner.func1.2({0xedd9a0, 0xc00039d8d8})
	/opt/hostedtoolcache/go/1.18.4/arm64/src/testing/testing.go:1389 +0x278
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.4/arm64/src/testing/testing.go:1392 +0x430
panic({0xedd9a0, 0xc00039d8d8})
	/opt/hostedtoolcache/go/1.18.4/arm64/src/runtime/panic.go:844 +0x260
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*Batch).Length(...)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/containers/batch.go:81
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).OnLoad(0xc008ffd220)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/node.go:159 +0x8e8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*Node).Load(0xc000851290)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/buffer/node.go:124 +0x7c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*nodeManager).Pin(0xc0004272c0, {0x10bf1f0, 0xc000851290})
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/buffer/nodemgr.go:183 +0xfc
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/buffer.(*nodeManager).TryPin(0xc0004272c0, {0x10bf1f0, 0xc000851290}, 0x3b9aca00)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/buffer/nodemgr.go:141 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).TryPin(...)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/node.go:71
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*appendableNode).DoWithPin(0xc008ffd220, 0xc000479350)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/node.go:75 +0x7c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).ResolveABlkColumnMVCCData(0xc0003b52c0, 0x3e, 0x0, 0x0, 0x0)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/block.go:460 +0x214
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).GetColumnDataById(0xc0003b52c0, {0x10cab00, 0xc00b6a71d0}, 0xffffa05c0108?, 0x40?)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/block.go:408 +0x98
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnBlock).GetColumnDataById(0xc000dc8580, 0xc006d6c720?, 0xc0004a7580?)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/txn/txnimpl/block.go:191 +0x140
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc00035ecf0, {0xc000479784, 0xc, 0xc})
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:93 +0x334
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc00035ecf0)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:155 +0x50c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc000653dc0)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0xc4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.compactBlocks(0xc008412180?, 0xc00052af00, {0xf4afd1, 0x2}, 0xc008412180, 0x1)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/db/base_test.go:448 +0x310
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.TestReplay7(0x0?)
	/runner/_work/matrixone/matrixone/pkg/vm/engine/tae/db/replay_test.go:1044 +0x270
testing.tRunner(0xc0003ccd00, 0xf89ec8)
	/opt/hostedtoolcache/go/1.18.4/arm64/src/testing/testing.go:1439 +0x190
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.4/arm64/src/testing/testing.go:1486 +0x56c

**Comment by sukki37** [comment]
@LeftHandCold any status update?

**Comment by florashi181** [comment]
update the statue of this issue @LeftHandCold

**Comment by LeftHandCold** [comment]
This case is no longer needed now, because the process of 0.6replay has been modified, and this case will be deleted later
