### ISSUE TITLE
[Bug]: version number is still 0.4.0

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4134]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The latest MatrixOne main branch version number is still 0.4.0.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/4965857/179997162-bb08f769-678c-4bf6-bdbf-e0dc02b24ec2.png">

**Comment by yingfeng** [comment]
Fixed

**Comment by aressu1985** [comment]
fixed
