### ISSUE TITLE
[Bug]: mysql_cmd_executor.go line 918

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#4165]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

That code is quite strange, it looks like a real issue instead of unused variable.    Commented out anyway, but I think it need some care.

**Comment by daviszhen** [comment]
it was fixed.
