### ISSUE TITLE
[Feature Request]: Support MySQL sqlmode in MO

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4172]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In 0.6.0, mo needs another sqlmode which works as MySQL

- A parameter can switch MO sqlmode to MySQL sqlmode
- In MySQL sqlmode, there will be case sensitive in database name, table name and column name.

**Comment by fengttt** [comment]
Why is this p0.5?   Feels like a P20 issue.    We should stay with standard SQL Mode forever.     If you want/need case sensitive database names etc, use quote.

**Comment by fengttt** [comment]
@iamlinjunhong please raise this with product team and resolve before diving into implementation.

**Comment by iamlinjunhong** [comment]
Mo uses ` ` as case sensitivity, which is different from MySQL. MySQL sets the system variable lower_ case_ table_ names （ https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html ）to determine whether it is case sensitive. Whether to be compatible with MySQL and discard the current behavior of Mo ? @fengttt @domingozhang

**Comment by fengttt** [comment]
See #6606

**Comment by domingozhang** [comment]
As discussed, a configuration will be implemented to decide whether the object name is case sensitive or not during querying.

**Comment by iamlinjunhong** [comment]
The solution should be to set a variable before ddl, and then convert it to lowercase even if there is a `` in ddl
