### ISSUE TITLE
[Bug]: tae moengine: read only

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4176]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create database catalog;
use catalog;
create TABLE mo_tables (relid int,relname VARCHAR(100),reldatabase VARCHAR(100),reldatabase_id int,relpersistence CHAR(8),relkind CHAR(8),rel_comment VARCHAR(100),rel_createsql VARCHAR(100),owner int,acount_id int,object_id int);

insert into mo_tables values(2,'t1','test',1,NULL,NULL,NULL,NULL,3,1,2);
**ERROR 1105 (HY000): tae moengine: read only**

**Comment by XuPeng-SH** [comment]
We're not planning to support directly Create|Delete|Update on these  `mo_databases`, `mo_tables`, `mo_columns` tables, which are read-only views.

**Comment by XuPeng-SH** [comment]
moengine will not be used in v0.6
