### ISSUE TITLE
[Enhancement]: Decimal64 and Decimal128 in C

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#4241]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
We currently use (decDouble and decQuad) from decNumber library.   After vectorize, the decimal64 and decimal128 types are about 50-100 times slower than double in C.

We may want to implement our own decimal64/128, hopefully bring this to 5-10x slower than double.
```

**Comment by fengttt** [comment]
Right now I only did micro benchmark.   We need to benchmark against tpch and tpcds before design/code.

**Comment by goodMan-code** [comment]
test for TPCH-10G, query 14's result is different because of Decimal point, It usually appears in the 13th place after the decimal point. this txt for reference.
[TPCH-10G_result_of_query_14.txt](https://github.com/matrixorigin/matrixone/files/10032441/TPCH-10G_result_of_query_14.txt)

**Comment by zengyan1** [comment]
Done
