### ISSUE TITLE
[Bug]: MatrixOne with ruby on rails connector error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4242]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters: 4c16g
- OS type:centos 8.4
- Others: ruby 2.6.9, rails 5.2.8.1, mysql2 connector.
```

### Actual Behavior

I run a fully functional ruby on rails demo with mysql 8.0. 
The connection with MatrixOne 0.5 could work, run `rails db` can successfully connect to MatrixOne. But run anything like `create database ***` in ruby gives error on the MySQL version.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/4965857/181401648-1bf1edd9-0368-4e5e-b4cf-279c5db3f7d8.png">

**Comment by fengttt** [comment]
Ruby.   It is relative low priority, after JDBC, python, go, and ODBC.   Therefore P1 and backlog.   

Our hope is that once we fixed those mentioned above, ruby should be easy.

**Comment by dengn** [comment]
Will check on 0.7.0

**Comment by dengn** [comment]
fixed.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/4965857/212577173-6be9b5d4-0617-4ff0-ada9-78eca2e1be81.png">
