### ISSUE TITLE
[Enhancement]: Deduce and maintain expression nullable properties.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#4290]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

We have not done much to check if an expression is nullable.   For example, select * from S join T on S.a = T.b, this query really says   select * from (select * from S where a is not null) S1 join (select * from T where b is not null) T1 on S1.a = T1.b

S1.a = T1.b, at run time, we know both S1.a and T1.b are not nullable.   This saves one run time null bitmap.    But that is the smaller one.    @龙冉 you know better than anyone else, that if you know an expression is not null, there are optimizing opportunities, such as subquery.

**Comment by badboynt1** [comment]
fixed
