### ISSUE TITLE
[Bug]: change HAKeeper's default config would fail HAKeeper tests 

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#4294]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When I changed DefaultLogStoreTimeout to 10 * time.Second, it failed some HAKeeper tests. 

Tests should never assume any particular config or default const values.  

### Expected Behavior

Fix all HAKeeper tests to ensure that config and default values can be arbitrarily set without causing any issue.

**Comment by w-zr** [comment]
Completed and can be closed.
