### ISSUE TITLE
[Bug]: TestTCPProxyExample is flaky

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#4323]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

=== RUN   TestTCPProxyExample
{"level":"INFO","time":"2022/08/02 07:12:04.376542 +0000","caller":"morpc/backend.go:550","msg":"start connect to remote","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"error","ts":"2022-08-02 07:12:04.376","caller":"v2@v2.0.3-0.20220730091829-0a8222eaa708/application.go:302","msg":"handle session failed","listen-address":"/tmp/proxy.sock","error":"no upstream"}
{"level":"DEBUG","time":"2022/08/02 07:12:04.377065 +0000","caller":"v2@v2.0.3-0.20220730091829-0a8222eaa708/session.go:476","msg":"session init completed","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock","session-id":0}
{"level":"INFO","time":"2022/08/02 07:12:04.377209 +0000","caller":"morpc/backend.go:554","msg":"connect to remote succeed","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"INFO","time":"2022/08/02 07:12:04.377472 +0000","caller":"morpc/backend.go:438","msg":"read loop started","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"INFO","time":"2022/08/02 07:12:04.377621 +0000","caller":"morpc/backend.go:319","msg":"write loop started","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"error","ts":"2022-08-02 07:12:04.377","caller":"v2@v2.0.3-0.20220730091829-0a8222eaa708/session.go:462","msg":"conneciton disconnected","session-id":1}
{"level":"ERROR","time":"2022/08/02 07:12:04.377964 +0000","caller":"morpc/backend.go:450","msg":"read from backend failed","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock","error":"read unix @->/tmp/proxy.sock: read: connection reset by peer"}
{"level":"DEBUG","time":"2022/08/02 07:12:04.378092 +0000","caller":"morpc/backend.go:[615](https://github.com/matrixorigin/matrixone/runs/7626239174?check_suite_focus=true#step:5:616)","msg":"schedule reset remote connection","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"ERROR","time":"2022/08/02 07:12:04.378169 +0000","caller":"morpc/backend.go:455","msg":"read loop stopped","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"INFO","time":"2022/08/02 07:12:04.378254 +0000","caller":"morpc/backend.go:550","msg":"start connect to remote","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"ERROR","time":"2022/08/02 07:12:04.378353 +0000","caller":"v2@v2.0.3-0.20220730091829-0a8222eaa708/session.go:462","msg":"conneciton disconnected","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock","session-id":0}
{"level":"DEBUG","time":"2022/08/02 07:12:04.378494 +0000","caller":"v2@v2.0.3-0.20220730091829-0a8222eaa708/session.go:476","msg":"session init completed","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock","session-id":0}
{"level":"INFO","time":"2022/08/02 07:12:04.378569 +0000","caller":"morpc/backend.go:554","msg":"connect to remote succeed","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
{"level":"INFO","time":"2022/08/02 07:12:04.378712 +0000","caller":"morpc/backend.go:438","msg":"read loop started","testcase":"TestTCPProxyExample","remote":"unix:///tmp/proxy.sock"}
panic: Fail in goroutine after TestCloseWhileContinueSending has completed

goroutine 27 [running]:
testing.(*common).Fail(0xc00017aea0)
	/opt/hostedtoolcache/go/1.18.5/arm64/src/testing/testing.go:817 +0x130
testing.(*common).Errorf(0xc00017aea0, {0x7edbbb, 0x3}, {0xc0000366b0, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.18.5/arm64/src/testing/testing.go:934 +0x90
github.com/stretchr/testify/assert.Fail({0x8e4128, 0xc00017aea0}, {0xc000024580, 0x34}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.5/assert/assertions.go:262 +0x364
github.com/stretchr/testify/assert.NoError({0x8e4128, 0xc00017aea0}, {0x8e4208, 0xd12e40}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.5/assert/assertions.go:1335 +0xe8
github.com/matrixorigin/matrixone/pkg/common/morpc.TestCloseWhileContinueSending.func2.1.1()
	/runner/_work/matrixone/matrixone/pkg/common/morpc/backend_test.go:79 +0x170
github.com/matrixorigin/matrixone/pkg/common/morpc.TestCloseWhileContinueSending.func2.1()
	/runner/_work/matrixone/matrixone/pkg/common/morpc/backend_test.go:88 +0x74
created by github.com/matrixorigin/matrixone/pkg/common/morpc.TestCloseWhileContinueSending.func2
	/runner/_work/matrixone/matrixone/pkg/common/morpc/backend_test.go:67 +0x120
FAIL	github.com/matrixorigin/matrixone/pkg/common/morpc	10.045s

**Comment by zhangxu19830126** [comment]
fixed

**Comment by aressu1985** [comment]
@zhangxu19830126 this is ut issue, can you deal with this?

**Comment by aressu1985** [comment]
fixed
