### ISSUE TITLE
[Enhancement]: Refactor code layout

### ISSUE THREAD

**Issue by JinHai-CN** [matrixorigin/matrixone#4325]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
I want the current source code directory layout to be more logical so that I can set code owners for each directory.

Plan for the code owner settings:
- .github @JinHai-CN 
- .github/actions @sukki37 
- .github/ISSUE_TEMPLATE @JinHai-CN 
- .github/workflow @sukki37 

- cgo/ @fengttt
- cmd/ @daviszhen 
- docs/ @dengn 
- etc/ @zhangxu19830126 
- LICENSES/ @JinHai-CN 
- optools/ @sukki37 

- pkg/common
    - async @fengttt 
    - bitmap @nnsgmsone 
    - compare @nnsgmsone 
    - compress @nnsgmsone 
    - defines @daviszhen 
    - encoding @nnsgmsone 
    - errno @nnsgmsone 
    - hashmap @nnsgmsone 
    - moerr @fengttt 
    - morpc @zhangxu19830126 
    - partition @nnsgmsone 
    - sort @nnsgmsone 
    - stopper @zhangxu19830126 
- pkg/config @daviszhen 
- pkg/container @nnsgmsone 
- pkg/frontend @daviszhen 
- pkg/hakeeper @lni 
- pkg/pb @fengttt @yingfeng @JinHai-CN 
- pkg/storage @nnsgmsone 
- pkg/storage/memEngine @nnsgmsone 
- pkg/storage/tae @XuPeng-SH 
- pkg/storage/txn @reusee 
- pkg/txn @zhangxu19830126 
- pkg/util/internalExecutor @aptend 
- pkg/util/metric @aptend 
- pkg/util/logutil @daviszhen 
- pkg/util/toml @daviszhen 
- pkg/vm @nnsgmsone 

- proto @fengttt @yingfeng @JinHai-CN 
- test @aressu1985 
- / @JinHai-CN 

```

**Comment by daviszhen** [comment]
I have no idea about pkg/util/toml

**Comment by lni** [comment]
I'd like to recommend to postpone this change to a later date during the v0.6 cycle. This will give people working on various modules more time to think about what is the optimal layout of the project. 

There are several immediate issues that I can see from the above proposed layout - 

- it would be much better to have 2 people to be owners of most modules, think about people taking annual leave and couldn't immediately take required actions for his/her owned modules. 
- it is unclear what is the real difference between pkg/util and pkg/common
- it is unclear how different services should be placed. 
- it is unclear what is the role of the test folder - e.g. both pkg/storage/memEngine and pkg/storage/txn are for testing purposes only. 
- pkg/proto and pkg/pb are pretty much the same thing, they will have to be changed by certain team on weekly basis, if not almost on daily basis. 
- in pkg/common, hashmap, bitmap and sort are closely relate to the compute layer, but they are vastly different to stopper, morpc etc. 

I can easily name even more, thus I recommend not to merge the related PR #4329 and start a quick & meaningful discussion on this issue first.

**Comment by JinHai-CN** [comment]
> I'd like to recommend to postpone this change to a later date during the v0.6 cycle. This will give people working on various modules more time to think about what is the optimal layout of the project.
> 
> There are several immediate issues that I can see from the above proposed layout -
> 
> * it would be much better to have 2 people to be owners of most modules, think about people taking annual leave and couldn't immediately take required actions for his/her owned modules.

yes, 2 people will be better, but PR #4329 is not about the code owners, just directory layout.

> * it is unclear what is the real difference between pkg/util and pkg/common

yes, this is about detailed assignment. I would like to let pkg/util to have some utility modules like: metrics/tracing, etc. pkg/common will have data structres and algorithms which used by many modules. But, I don't insist on it. You can provide better schema.

> * it is unclear how different services should be placed.

I just place dnservice/cnservice/logservice/fileservice into one folder. If you think each one should be the first level directory, I am also OK. I can move them out. It's up to you guys.

> * it is unclear what is the role of the test folder - e.g. both pkg/storage/memEngine and pkg/storage/txn are for testing purposes only.

Yes, they are with pkg/vm/engine directory. I didn't change it. I just move the pkg/vm/engine to pkg/storage. we can adjust them later.

> * pkg/proto and pkg/pb are pretty much the same thing, they will have to be changed by certain team on weekly basis, if not almost on daily basis.

yes, I don't want to decide it now.

> * in pkg/common, hashmap, bitmap and sort are closely relate to the compute layer, but they are vastly different to stopper, morpc etc.

yes, you are right. But, you can't use one PR to solve all issues. We can adjust them in later PR.

> 
> I can easily name even more, thus I recommend not to merge the related PR #4329 and start a quick & meaningful discussion on this issue first.

I just give the whole picture of the refactoring:

compare/compress/container/encoding/defines/errno/partition/sort->pkg/common
vectorize/testutil->pkg/sql

fileservice/logservice/dnservice/cnservice -> pkg/service

vm/engine->storage
