### ISSUE TITLE
[Bug]: "fatal: No names found, cannot describe anything" when building mo-server

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixone#4407]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Actual Behavior

In CI, when building mo-server or mo-server, we got the following error

```
fatal: No names found, cannot describe anything.
```

e.g., see the build MatrixOne step in 
https://github.com/matrixorigin/matrixone/runs/7705247237?check_suite_focus=true

The error is caused by the following line in Makefile

```
MO_VERSION=$(shell git describe --tags $(shell git rev-list --tags --max-count=1))
```

**Comment by fengttt** [comment]
I believe this is github capacity issue?  @sukki37

**Comment by wanglei4687** [comment]
FYI, https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

**Comment by aressu1985** [comment]
fixed
