### ISSUE TITLE
[Bug]: Cannot repair log replicas if hakeeper's leader is closed

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#4418]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are lots of `illegal state` in logs.
```
{"level":"ERROR","time":"2022/08/08 18:11:39.934538 +0800","caller":"morpc/backend.go:401","msg":"write request failed","remote":"127.0.0.1:32001","request-id":17,"error":"illegal state"}
```
Complete log is here.
[log_2.txt](https://github.com/matrixorigin/matrixone/files/9280964/log_2.txt)

**Comment by lni** [comment]
@zhangxu19830126 it seems morpc is keep getting this illegal state error.

**Comment by zhangxu19830126** [comment]
fixed
