### ISSUE TITLE
[Bug]: ssb-test causes the MO to panic

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#4427]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (8f4f09031f990b3cf5febb1f28c1245fa5e366b7):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

按照文档中ssb 测试【多表查询--Q4.3】示例操作：（文档链接：https://docs.matrixorigin.io/cn/0.5.0/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone/#_3）

--Q4.3

select year(d_datekey) as year, s_city, p_brand, sum(lo_revenue) - sum(lo_supplycost) as profit,c_region , s_nation, p_category
from lineorder
join dates on lo_orderdate = d_datekey
join customer on lo_custkey = c_custkey
join supplier on lo_suppkey = s_suppkey
join part on lo_partkey = p_partkey
where
(year(d_datekey) = 1997 or year(d_datekey) = 1998)
and s_nation='ALGERIA'
group by year(d_datekey), s_city, p_brand, c_region , s_nation, p_category
order by year, s_city, p_brand;

ERROR 1105 (HY000): Internal error: panic runtime error: index out of range [84] with length 80: goroutine 48627 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x103635300?, 0x142ed944018})
        /Users/Prinz/02matrixone/matrixone/pkg/common/moerr/error.go:122 +0x50
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
        /Users/Prinz/02matrixone/matrixone/pkg/vm/vm.go:57 +0x34
panic({0x103635300, 0x142ed944018})
        /usr/local/go/src/

**Comment by sukki37** [comment]
@lacrimosaprinz please test and close this issue if it is fixed.
