### ISSUE TITLE
[Feature Request]: Decimal support operator of mod

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#4432]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

select cast(10000002383263201056 as decimal) mod 50 as result;

**Comment by aunjgr** [comment]
It's in the scope of #4241.

**Comment by aunjgr** [comment]
Will be resolved by #4241.

**Comment by aunjgr** [comment]
It's a duplicate of #4241. Can be closed.

**Comment by matrix-meow** [comment]
Hello @iamlinjunhong. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @iamlinjunhong. The bug issue in the BVT test code has not been removed,issues automatically open.
