### ISSUE TITLE
[Bug]: `BIGINT UNSIGNED` type,  insert can success, but select abnormal.It is unreasonable.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4482]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE numbers(pk INTEGER PRIMARY KEY,ui BIGINT UNSIGNED,si BIGINT);

INSERT INTO numbers VALUES
(0, 0, -9223372036854775808), (1, 18446744073709551615, 9223372036854775807);

SELECT * FROM numbers WHERE ui=0;
error: "Can't cast column from BIGINT UNSIGNED type to BIGINT type because of one or more values in that column. Reason: overflow"

### Expected Behavior

SELECT * FROM numbers WHERE ui=0;

mysql> SELECT * FROM numbers WHERE ui=0;
+----+------+----------------------+
| pk | ui   | si                   |
+----+------+----------------------+
|  0 |    0 | -9223372036854775808 |
+----+------+----------------------+

**Comment by tianyahui-python** [comment]
mysql> SELECT * FROM numbers WHERE ui=0;
ERROR 1105 (HY000): Can't cast column from BIGINT UNSIGNED type to BIGINT type because of one or more values in that column. Reason: overflow
mysql> update numbers set si=8  WHERE ui=0;
ERROR 1105 (HY000): Can't cast column from BIGINT UNSIGNED type to BIGINT type because of one or more values in that column. Reason: overflow
mysql> delete from numbers  WHERE ui=0;
ERROR 1105 (HY000): Can't cast column from BIGINT UNSIGNED type to BIGINT type because of one or more values in that column. Reason: overflow

**Comment by iamlinjunhong** [comment]
Conversion rules are already defined. uint64, int64 will cast as int64, int64. You can use:  SELECT * FROM numbers WHERE ui=cast(0 as unsigned);

**Comment by tianyahui-python** [comment]
<img width="1001" alt="截屏2022-10-24 16 41 46" src="https://user-images.githubusercontent.com/39303074/197485165-a9baad29-3a18-4905-afad-6925506a3305.png">

**Comment by domingozhang** [comment]
int64 cannot be converted implicitly to uint64 in parser. 
Can we adjust our plan to fix this issue? @fengttt @aunjgr

**Comment by badboynt1** [comment]
not working on this

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/6888
already fixed in this pr

**Comment by tianyahui-python** [comment]
<img width="1323" alt="截屏2022-12-15 22 09 26" src="https://user-images.githubusercontent.com/39303074/207882243-b41a23d9-a1a9-4da6-9689-5c04e8a49ceb.png">

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
bvt tag no remove. @badboynt1

**Comment by tianyahui-python** [comment]
<img width="1236" alt="截屏2022-12-21 09 44 15" src="https://user-images.githubusercontent.com/39303074/208800919-b70b4f4c-9097-4bad-9428-62afcf6f9800.png">

**Comment by tianyahui-python** [comment]
relation  issue: https://github.com/matrixorigin/matrixone/issues/7278
