### ISSUE TITLE
[Bug]: float type, select ... where col=flo; unmatch.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4487]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE `test_table` (`pk` INT DEFAULT NULL, `fl` FLOAT DEFAULT NULL,`dou` DOUBLE DEFAULT NULL, PRIMARY KEY (`pk`));

INSERT INTO test_table VALUES(0, 1.2345678, 1.223344556677889900), (1, 1.8765432, 1.223344556677889900);

mysql> select * from test_table;
+------+-----------+------------------+
| pk   | fl        | dou              |
+------+-----------+------------------+
|    0 | 1.2345678 | 1.22334455667789 |
|    1 | 1.8765432 | 1.22334455667789 |
+------+-----------+------------------+

mysql> select * from test_table where fl=1.2345678;
Empty set (0.00 sec)

### Expected Behavior

mysql> select * from test_table where fl=1.2345678;

+------+-----------+------------------+
| pk   | fl        | dou              |
+------+-----------+------------------+
|    0 | 1.2345678 | 1.22334455667789 |
+------+-----------+------------------+

**Comment by iamlinjunhong** [comment]
In mysql:
<img width="1570" alt="截屏2022-08-29 下午2 49 38" src="https://user-images.githubusercontent.com/49111204/187140363-dba97491-d043-4886-b558-c1085bb64c0f.png">
