### ISSUE TITLE
[Bug]: insert TIMESTAMP max value error;

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4510]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t2 (time1 Date,time2 DateTime,time3 TIMESTAMP);

insert into t2 values ('1000-01-01', '0001-01-01 00:00:00.000000', '2038-01-19 03:14:07.999999');

ERROR 1105 (HY000): Data truncation: Incorrect TIMESTAMP value: '2038-01-19 03:14:07.99999' for column 'time3' at row 0

related to: https://docs.matrixorigin.io/cn/0.5.0/MatrixOne/Reference/Data-Types/data-types/#_4

### Expected Behavior

mysql> insert into t2 values ('1000-01-01', '0001-01-01 00:00:00.000000', '2038-01-19 03:14:07.999999');
Query OK, 1 row affected (0.01 sec)

**Comment by aunjgr** [comment]
@tianyahui-python  It should be fixed by #4502. Please confirm.

**Comment by tianyahui-python** [comment]
<img width="1358" alt="截屏2022-10-24 16 52 49" src="https://user-images.githubusercontent.com/39303074/197487397-89ea5398-b271-4248-8683-ec21d44dd240.png">

**Comment by tianyahui-python** [comment]
@aunjgr  bvt tag no remove.

**Comment by aunjgr** [comment]
DATETIME/TIMESTAMP has a precision parameter which defaults to zero. So `2038-01-19 03:14:07.999999` is rounded up to `2038-01-19 03:14:08`.

If you want to keep the precision, you can use `timestamp(6)` in the DDL.
