### ISSUE TITLE
[Feature Request]: ignore X rows/lines

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4516]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Load data of a csv file,  if there is a header, a data type not fit error will definitely occur. 
`Ignore 1 rows` is easy to avoid this. 

LOAD DATA INFILE '/tmp/test.txt' INTO TABLE test IGNORE 1 LINES;

**Comment by jianwan0214** [comment]
you can use the Ignore 1 lines

**Comment by domingozhang** [comment]
In the syntax of load data, there will be a synonym of ignore rows/lines

**Comment by jianwan0214** [comment]
I add ignore X lines/rows in this pr. https://github.com/matrixorigin/matrixone/pull/4673

**Comment by dengn** [comment]
It looks like "ignore 1 rows" is not added yet. 
Commit id: e9686aed42d95af234e29db5463936f023cbaba8

mysql> load data infile '/mnt/vdb/dengnan/stock_pe.csv' into table pe2 fields terminated by ',' ENCLOSED BY '"' LINES TERMINATED BY "\r\n" ingore 1 rows;
ERROR 20303 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 138 near " ingore 1 rows";

**Comment by dengn** [comment]
Fixed.
