### ISSUE TITLE
[Bug]: Docker version load data problem

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4522]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.5.0
- Hardware parameters: Macbook m1 arm 4c16g
- OS type: OSX
- Others:
```

### Actual Behavior

With docker version running, the csv file in local file system cannot be found. 

1. launch MO0.5.0
docker run -d -p 6001:6001 --name matrixone matrixorigin/matrixone:0.5.0

2. connect to MO

3. create db and table. 
create database stock;
use stock;
CREATE TABLE pe (
ts_code VARCHAR(255) DEFAULT NULL,
trade_date VARCHAR(255) DEFAULT NULL,
pe FLOAT DEFAULT NULL,
pb FLOAT DEFAULT NULL
);

4. load csv

mysql> load data infile '/Users/nandeng/Test/stock_pe.csv' into table pe fields terminated by ',' lines terminated by '\n';
ERROR 1105 (HY000): file /Users/nandeng/Test/stock_pe.csv does exist. err:stat /Users/nandeng/Test/stock_pe.csv: no such file or directory

### Expected Behavior

Need a solution for docker load data.

**Comment by sukki37** [comment]
this is not a bug, you should mount volume first.

**Comment by dengn** [comment]
> this is not a bug, you should mount volume first.

Right. we need your help to build a tutorial here.

**Comment by dengn** [comment]
Tutorial added in documentation
