### ISSUE TITLE
[Bug]: Failed to Connect to MO using "MySQL Workbench"

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#4530]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v.latest):
- Hardware parameters: M1
```

### Actual Behavior

- Use "MySQL Workbench" to connect MO, occur error as below:

- 【Client pop-up window】：
Failed to Connect to MySQL at 127.0.0.1:6001 with user dump
Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 59 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x105fadac0?, 0x106c900e0})
/Users/Prinz/02matrixone/matrixone/pkg/common/moerr/error.go:123 +0x50
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
/Users/Prinz/02matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:21

- 【log】：
{"level":"INFO","time":"2022/08/16 14:36:50.762898 +0800","caller":"frontend/mysql_cmd_executor.go:2138","msg":"connection id 1001 query:show character set where charset = 'utf8mb4'"}
{"level":"ERROR","time":"2022/08/16 14:36:50.763775 +0800","caller":"frontend/routine.go:113","msg":"routine execute request failed. error:Internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 210 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x64\ngithub.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x103295ac0?, 0x103f780e0})\n\t/Users/Prinz/02matrixone/matrixone/pkg/common/moerr/error.go:123 +0x50\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:2118 +0x3c\npanic({0x103295ac0, 0x103f780e0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x204\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.buildPrepare({0x12c35e190?, 0x1400898cea0?}, {0x1034c9700?, 0x14008608720?})\n\t/Users/Prinz/02matrixone/matrixone/pkg/sql/plan/build_dcl.go:76 +0x1bc\ngithub.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan({0x1034c9700, 0x14008608720}, {0x10349a998?, 0x1400898cea0?})\n\t/Users/Prinz/02matrixone/matrixone/pkg/sql/plan/build.go:110 +0xef4\ngithub.com/matrixorigin/matrixone/pkg/frontend.buildPlan({0x1034c9700?, 0x14008608720?}, {0x10349a998?, 0x1400898cea0?})\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:1646 +0x300\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile(0x1400898ced0, {0x1400898cea0?, 0x1400656cb70?}, 0x2c?)\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:1557 +0x48\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery(0x140086ccee0, {0x1400656cb70, 0x2c})\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:1938 +0x1cfc\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest(0x140086ccee0, 0x14004ae9b20)\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/mysql_cmd_executor.go:2162 +0x638\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop(0x1400877a000)\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/routine.go:112 +0x150\ncreated by github.com/matrixorigin/matrixone/pkg/frontend.NewRoutine\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/routine.go:164 +0x1c8\n \n","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/Prinz/02matrixone/matrixone/pkg/frontend/routine.go:113"}

**Comment by aressu1985** [comment]
commitid: 9130c990223a1d709051cff79b27ce3de65aad67

fixed
