### ISSUE TITLE
[Feature Request]: Need to build installation binaries for linux/mac + x86/arm 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4532]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

MO0.6 is supposed to run on linux x86, linux arm, mac x86 and mac arm environment.

**Comment by fengttt** [comment]
release engineering,

**Comment by sukki37** [comment]
linux x86, mac x86 have been supported.

**Comment by dengn** [comment]
linux arm and mac arm need to be supported as well.

**Comment by sukki37** [comment]
@guguducken Please kindly add more package jobs in https://github.com/matrixorigin/matrixone/blob/main/.github/workflows/release.yml.

**Comment by guguducken** [comment]
finished. if the build of the releasefor mac/arm fails, please connect me.

**Comment by dengn** [comment]
will check at the moment of release.

**Comment by dengn** [comment]
0.8 release ok.
