### ISSUE TITLE
[Bug]: text type should not support default value，but ddl with default can be excuted normally

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#4538]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Database changed
mysql> create table t1 (
    -> a text not null,
    -> b text not null default '0'
    -> );
Query OK, 0 rows affected (0.03 sec)

mysql>

**Comment by bbbearxyz** [comment]
please close it, text need to support default

**Comment by aressu1985** [comment]
closed
