### ISSUE TITLE
[Bug]: Enable stealth transactions, No execute update or add or delete, can modify SET @@session.autocommit=1;

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4548]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> SET @@session.autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@session.autocommit;
+--------------+
| @@autocommit |
+--------------+
|            0 |
+--------------+
1 row in set (0.00 sec)

mysql> SET @@session.autocommit=OFF;
ERROR 1105 (HY000): Uncommitted transaction exists. Please commit or rollback first.

### Expected Behavior

mysql> SET @@session.autocommit= 0;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@session.autocommit;
+----------------------+
| @@session.autocommit |
+----------------------+
|                    0 |
+----------------------+
1 row in set (0.01 sec)

mysql> 
mysql> SET @@session.autocommit= OFF;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @@session.autocommit;
+----------------------+
| @@session.autocommit |
+----------------------+
|                    0 |
+----------------------+
1 row in set (0.00 sec)

**Comment by fengttt** [comment]
This is not about hidden transaction any more.   We have that done.   However, SET @autocommit is S0.
