### ISSUE TITLE
[Bug]: External Scan not use mheap to alloc 

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#4550]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

use mheap

**Comment by nnsgmsone** [comment]
scan should be able to maintain a constant memory and then reuse it all the time. This would improve performance quite a bit.

**Comment by jianwan0214** [comment]
> scan should be able to maintain a constant memory and then reuse it all the time. This would improve performance quite a bit.

now, Dr Tian use the prealloc function here, so it can not reuse a constant memory now.

**Comment by nnsgmsone** [comment]
> now, Dr Tian use the prealloc function here, so it can not reuse a constant memory now.

I think it's better to use the constant memory of the session. When I'm free, let's discuss this issue together.

**Comment by florashi181** [comment]
review this issue again and update the status @jianwan0214
