### ISSUE TITLE
[Feature Request]: SELECT * FROM information_schema.COLUMNS 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4563]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

#4509

### Describe the feature you'd like

SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='stock' AND TABLE_NAME='pe' ORDER BY ORDINAL_POSITION

Implement as MySQL

**Comment by qingxinhome** [comment]
This Feature Request has been implemented and submitted to PR, including bvt test. Please know. @dengn @daviszhen @aressu1985
