### ISSUE TITLE
[Bug]: Stealth transactions, SET AUTOCOMMIT value No change has occurred,Uncommitted transactions are not affected.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4568]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> set @@autocommit=0;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 values(10);
Query OK, 1 row affected (0.00 sec)

mysql> set @@autocommit=0;
ERROR 1105 (HY000): Uncommitted transaction exists. Please commit or rollback first.
mysql> 

### Expected Behavior

mysql> set @@autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values(10);
Query OK, 1 row affected (0.00 sec)

mysql> set @@autocommit=0;
Query OK, 0 rows affected (0.00 sec)

**Comment by daviszhen** [comment]
The behavior follows the definition in the document.
