### ISSUE TITLE
[Bug]: If there are uncommitted hidden transactions,Unable to start a new transaction.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4572]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> set @@autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values(10);
Query OK, 1 row affected (0.00 sec)

Should not be able to start a new transaction，But now it can.

mysql> begin;                                      
Query OK, 0 rows affected (0.00 sec)

**Comment by daviszhen** [comment]
What's the value of the autocommit in the session ?

**Comment by tianyahui-python** [comment]
> What's the value of the autocommit in the session ?

set @@autocommit=0;

**Comment by daviszhen** [comment]
The behavior follows the definition in the document.
