### ISSUE TITLE
[Bug]: Can't cast '%I:%m%y-%H-%V-%k-%k' from VARCHAR type to DATETIME type.

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#4573]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (
col_datetime_2_not_null_key datetime(2) NOT NULL,
col_datetime_5 datetime(5) DEFAULT NULL,
pk datetime(5) NOT NULL,
PRIMARY KEY (pk));
INSERT INTO t1 VALUES
('2001-10-20 00:00:00.00','2001-09-20 11:18:18.03630','2011-07-19 17:37:06.26725'),
('0001-01-01 00:00:00.00','0001-01-01 00:00:00.00000','2011-07-19 17:37:07.26725'),
('0001-01-01 00:00:00.00','0001-01-01 00:00:00.00000','2011-07-19 17:37:08.26725'),
('2000-01-14 17:55:57.03','0001-01-01 00:00:00.00000','2011-07-19 17:37:09.26725'),
('2006-12-27 07:25:14.04',NULL,'2011-07-19 17:37:10.26725'),
('2000-10-17 22:03:12.01','0001-01-01 00:00:00.00000','2011-07-19 17:37:11.26725'),
('0001-01-01 00:00:00.00','0001-01-01 00:00:00.00000','2011-07-19 17:37:12.26725'),
('0001-01-01 00:00:00.00','0001-01-01 00:00:00.00000','2011-07-19 17:37:13.26725'),
('0001-01-01 00:00:00.00','2008-06-04 23:05:50.03642','2011-07-19 17:37:14.26725'),
('2000-10-22 23:52:09.01',NULL,'2011-07-19 17:37:15.26725');
SELECT col_datetime_2_not_null_key AS c1, col_datetime_5 AS c2
FROM t1
WHERE
pk <> CONCAT_WS( ':','%I','%m' )+CONCAT_WS('-','%y','%H','%V','%k','%k' )
OR
year(col_datetime_5) < year(utc_timestamp())
ORDER BY 1;

Can't cast '%I:%m%y-%H-%V-%k-%k' from VARCHAR type to DATETIME type.

**Comment by aunjgr** [comment]
It's about cast precedence. We cast the invalid string to timestamp, then get an error.

We can rewrite cast error to NULL when it's in a predicate.

**Comment by aunjgr** [comment]
Need more thinking

**Comment by aunjgr** [comment]
It's an issue of casting constant to another type.

If it's in a predicate, and the casting failed, we should directly rewrite the predicate to TRUE/FALSE. Reporting error or return NULL is not correct.

Casting an overflew numeric literal to int/uint should be handled by the same logic of this issue.

**Comment by aunjgr** [comment]
No progress yet

**Comment by aunjgr** [comment]
No progress yet

**Comment by aunjgr** [comment]
No progress yet

**Comment by aunjgr** [comment]
No progress yet.

**Comment by aunjgr** [comment]
No progress yet.

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
No progress yet

**Comment by domingozhang** [comment]
suggest do not support until users have certain requirement.

**Comment by matrix-meow** [comment]
Hello @iamlinjunhong. The bug issue in the BVT test code has not been removed,issues automatically open.
