### ISSUE TITLE
Implement the String method of ast tree

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#463]
Provide a function to echo the detail incorrect sql statement in logs.

**Comment by iamlinjunhong** [comment]
Usage:
tree.String(stmt, dialect.Mysql)
stmt is a sql statement or a sub statement of a sql statement.

**Comment by iamlinjunhong** [comment]
e.g.
<img width="1502" alt="截屏2021-12-16 下午2 54 56" src="https://user-images.githubusercontent.com/49111204/146322739-59a22878-41c8-487b-b4f1-787dc7d62201.png">
