### ISSUE TITLE
[Bug]: MO query bug 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4631]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.5.1
- Hardware parameters: Macbook m1 arm 4c16g
- OS type:
- Others:
```

### Actual Behavior

Run a query: 
select pe1.ts_code, pe1.trade_date, pe1.pe from pe as pe1 inner join (select ts_code, min(pe) as min_pe from pe where pe>0 group by ts_code) as pe2 on pe1.ts_code = pe2.ts_code and pe1.pe = pe2.min_pe where trade_date = '20220428'

on 11 millions records. 

Get error log

**Comment by dengn** [comment]
[crash.log.zip](https://github.com/matrixorigin/matrixone/files/9398867/crash.log.zip)

**Comment by nnsgmsone** [comment]
Is your machine an amd64?

**Comment by nnsgmsone** [comment]
Please compile, rather than copy the binary file

**Comment by LeftHandCold** [comment]
This case is a mo-server compiled with x86 running on m1

**Comment by dengn** [comment]
> Is your machine an amd64?

My machine is Mac ARM, but i used a darwin x86 binary.

**Comment by dengn** [comment]
Another simple query will lead to this too: 
```
select ts_code, min(pe) from pe2 group by ts_code;
```

**Comment by dengn** [comment]
Crash is due to x86 compiled binary file running on Mac M1 ARM machine.
