### ISSUE TITLE
[Bug]: text cast as char(1), Not up to expectations.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4634]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t (col1 text);

insert into t values('aaaaaaaaaaaaaaaa');

select cast(col1 as char(1)) from t;

mysql> select cast(col1 as char(1)) from t;
+-----------------------+
| cast(col1 as char(1)) |
+-----------------------+
| aaaaaaaaaaaaaaaa      |
+-----------------------+

### Expected Behavior

Text can be castable to char/varchar,bigint/int/smallint/tinyint, float/double, char/varchar, date, datetime, timestamp and bool. When the length of text is longer than other types, errors will be notified.

**Comment by domingozhang** [comment]
If char/varchar/text, it follows these rules:
- If the value of it is 'true' or 'falses', it will be converted to bool as ture or false;
- If the value of it can be converted to double, such as  '0' or '2.123', it can be converted to bool. 0 to false, other to true.
- If the value of it is not the two, it cannot be converted to bool.

**Comment by tianyahui-python** [comment]
mysql> create table t (a varchar(1));
Query OK, 0 rows affected (0.02 sec)

mysql> 
mysql> insert into t values('aaaaabbbb');
Query OK, 1 row affected (0.03 sec)

It should be the same type of question.

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/4636  is about string cast to bool
this issue is about string cast to string. if src string length is larger than dest string length,
an error will be reported like this:

MySQL [mo]> select cast('aaaaaaa' as char(6));
ERROR 20101 (HY000): internal error: Can't cast 'aaaaaaa' from VARCHAR type to CHAR type. Src length 7 is larger than Dest length 6

**Comment by badboynt1** [comment]
in other cases, for example c1 char(5),
where c1='aaaaaaaaaaaaaaaaaa', do not report an error, return empty result.
insert into c1 values('aaaaaaaaaaaaa'), report an error.

**Comment by tianyahui-python** [comment]
mysql> create table t (col1 text);
Query OK, 0 rows affected (0.05 sec)

mysql> 
mysql> insert into t values('aaaaaaaaaaaaaaaa');
Query OK, 1 row affected (0.04 sec)

mysql> 
mysql> select cast(col1 as char(1)) from t;
ERROR 20101 (HY000): internal error: Can't cast column from TEXT type to CHAR type because of one or more values in that column. Src length 16 is larger than Dest length 1
mysql> delete from t;
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t values('a');
Query OK, 1 row affected (0.02 sec)

mysql> select cast(col1 as char(1)) from t;
+-----------------------+
| cast(col1 as char(1)) |
+-----------------------+
| a                     |
+-----------------------+
1 row in set (0.01 sec)
