### ISSUE TITLE
[Bug]: text type cast bool type, Not up to expectations.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4636]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t9(a text);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t9 values('hello');
Query OK, 1 row affected (0.02 sec)

mysql> select cast(a as bool) from t9;
+-----------------+
| cast(a as bool) |
+-----------------+
| false           |
+-----------------+
1 row in set (0.01 sec)

### Expected Behavior

mysql> create table t9(a text);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t9 values('hello');
Query OK, 1 row affected (0.02 sec)

mysql> select cast(a as bool) from t9;  cast failed

**Comment by badboynt1** [comment]
MySQL [mo]> select cast(a as bool) from t9;
+-----------------+
| cast(a as bool) |
+-----------------+
| false           |
+-----------------+
1 row in set (0.01 sec)

can not reproduce in latest version

**Comment by badboynt1** [comment]
confirmed with @domingozhang 

If char/varchar/text, it follows these rules:

If the value of it is 'true' or 'falses', it will be converted to bool as ture or false;
If the value of it can be converted to double, such as '0' or '2.123', it can be converted to bool. 0 to false, other to true.
If the value of it is not the two, it cannot be converted to bool.

**Comment by tianyahui-python** [comment]
commit id:1f47ed121938665a26925fcb243a2a005bc6c9f5
<img width="1042" alt="截屏2022-11-06 10 21 39" src="https://user-images.githubusercontent.com/39303074/200151004-63b6ac55-0a3f-4aee-9499-12dac508368d.png">
