### ISSUE TITLE
[Bug]: result failed when insert into view 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#4642]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> CREATE TABLE t1(c1 INT PRIMARY KEY, c2 INT);
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE VIEW v1 AS SELECT * FROM t1;
Query OK, 0 rows affected (0.02 sec)

mysql> -- error ER_CHECK_CONSTRAINT_VIOLATED
mysql> INSERT INTO v1 VALUES(1,20);
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO v1 VALUES(1,5);
Query OK, 1 row affected (0.02 sec)

mysql> SELECT * FROM t1;
Empty set (0.00 sec)

mysql> SELECT * FROM v1;
Empty set (0.00 sec)

mysql> DROP VIEW v1;
Query OK, 0 rows affected (0.02 sec)

mysql> DROP TABLE t1;
Query OK, 0 rows affected (0.02 sec)

**Comment by ouyuanning** [comment]
we will not support insert/update/delete for view in 0.6
this issue like #4643

**Comment by aressu1985** [comment]
fixed
