### ISSUE TITLE
[Bug]: TLS will timeout in Ubuntu+golang1.19 in docker

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#4656]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TLS will timeout in Ubuntu+golang1.9 in docker

**Comment by sukki37** [comment]
@ouyuanning can u update status on this issue?

**Comment by ouyuanning** [comment]
have no progress.  I try in go 1.19.1,   timeout will happen much less。
but didn't disappear.   i don't known why now.

**Comment by ouyuanning** [comment]
have no progress.

**Comment by ouyuanning** [comment]
no progress

**Comment by fengttt** [comment]
Should we close this one?   Is it still relavent/actionable?

**Comment by ouyuanning** [comment]
that's a Occasional bug only in unit test in Ubuntu+golang1.19 in docker.
can not reproduce in MO start with mo-service.

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/6567

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/6567.

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
proxy的部分也碰到了类似的问题。估计是go的bug
