### ISSUE TITLE
[Enhancement]: more text and blob type support

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4668]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Map all MySQL text(longtext, mediumtext, text, tinytext) to MO text type. 
and map all MySQL blob(longblob, mediumblob, blob, tinyblob) to MO blob type.

For MySQL users, they don't need to modify their DDL of these data types.
```

**Comment by domingozhang** [comment]
For these, I suggest we make synonyms of them.
- longtext, mediumtext, tinytext,clob -> text
- longblob, mediumblob, tinyblob -> blob
