### ISSUE TITLE
[Bug]: navicat query with comment -- syntax error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4669]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.5.1
- Hardware parameters: macbook m1 arm 4c16g
- OS type: osx
- Others:
```

### Actual Behavior

With Navicat, in MO, a sql file with a comment line will get syntax error. In MySQL, it works well.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/4965857/186424633-c3ca03b2-4bbe-4150-8112-4796c0e6db81.png">

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/4965857/186424798-d44ccd78-656b-4196-953f-9630463057de.png">

**Comment by iamlinjunhong** [comment]
your sql is wrong, without limit. 
<img width="303" alt="截屏2022-09-01 下午5 11 13" src="https://user-images.githubusercontent.com/49111204/187877924-7c8a7f5e-d8f3-44c8-8df3-1fff98726708.png">

**Comment by dengn** [comment]
regardless of that one, this bug is not fixed.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/4965857/193175682-54f751ae-2388-475f-bb17-40dd539a82fc.png">

**Comment by dengn** [comment]
fixed.
