### ISSUE TITLE
[Enhancement]: Commutative operations and SI

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#4679]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Commutative operations and SI. We may want to implement that, with only one optimization in mind (credit/debit)
```

**Comment by zhangxu19830126** [comment]
@fengttt This requirement is a bit lost on me, can you give a concrete example?

**Comment by fengttt** [comment]
set to constant as well.

**Comment by fengttt** [comment]
basically, for update queries,
```
update t set col = col + 1 where pk = 'foo';
```
or
```
update t set col = 5 where pk = 'xxx';
```

Update like this does not necessarily means it is a real conflict.   DN can resolve this by reading old value, reapply.

**Comment by fengttt** [comment]
May not need this if we move to pessimistic CC.
