### ISSUE TITLE
[Feature Request]: Support data type of time

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#4689]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

 create table t1 (a time(6));

**Comment by dongdongyang33** [comment]
#5944

**Comment by dongdongyang33** [comment]
more detail in issue #5704

**Comment by matrix-meow** [comment]
Hello @iamlinjunhong. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by YANGGMM** [comment]
have already removed the bvt tag, plz close it @iamlinjunhong
