### ISSUE TITLE
[Docs]: TPCH DOC ERROR

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#4706]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
`
cd ssb-dbgen
````

should be

````
cd tpch-dbgen
````
```


### Additional information

_No response_

**Comment by dengn** [comment]
thanks for pointing out.

**Comment by dengn** [comment]
Please close this issue, it's fixed. @aressu1985
