### ISSUE TITLE
[Bug]:  select  syntax bug

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#4716]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 13921832f3047cf51e57ac096bec69f562be2f77
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="812" alt="image" src="https://user-images.githubusercontent.com/77312370/186659768-f78a19c8-5d1a-4cfa-b0a1-fb04f5bfb1f9.png">

### Expected Behavior

`SELECT count(*) FROM account WHERE email = 'qinshuqi@matrixorigin.io';` executes successfully

### Steps to Reproduce

```Markdown
CREATE TABLE `account` (
  `uid` varchar(128) NOT NULL,
  `email` varchar(100) NOT NULL,
  `nickname` varchar(100) NOT NULL,
  `firstname` varchar(100) NOT NULL,
  `lastname` varchar(100) NOT NULL,
  `company` varchar(100) NOT NULL,
  `login_method` varchar(20) NOT NULL,
  `password` varchar(200) DEFAULT NULL,
  `register_method` varchar(20) NOT NULL,
  `activated` tinyint NOT NULL,
  `verified_at` datetime DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`uid`)
);
 SELECT count(*) FROM account WHERE email = 'xxx';
```

**Comment by heni02** [comment]
confirm,closed 
commit id :55398afae19b40f2e689994185a1d2b7dc07868c
<img width="588" alt="企业微信截图_eb3b2993-be02-487f-ac51-b277546a714d" src="https://user-images.githubusercontent.com/113406637/198807615-7daf425e-df5c-4931-bd4c-5029f3113156.png">

**Comment by aressu1985** [comment]
fixed
