### ISSUE TITLE
[Bug]: In add column comment,Escaping single quotes causes the mo-service to block.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4720]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
```
create table t1(
col1 int comment '这是第一列',
col2 float comment '"%$^&*()_+@!\'',
col3 varchar comment 'KNcR5P2ksILgsZD5lTndyuEzw49gxR2RlfU7nkNhAFOKIhig6roVYgS6yQDBkuzH790peOVKgTKUasKxuepzKqsYqQg3gDtgn',
col4 bool comment ''
);
```

abnormal phenomena: mo-server block;

**Comment by tianyahui-python** [comment]
<img width="1054" alt="截屏2022-08-26 11 04 08" src="https://user-images.githubusercontent.com/39303074/186844657-79e24a72-48dd-41ea-b360-50d1f42fa023.png">

**Comment by iamlinjunhong** [comment]
col2 float comment '"%$^&*()_+@!\\''  has \\' (Transfer character),  but the screenshot doesn't
