### ISSUE TITLE
[Bug]: insert text type more than 100M abnormal data, execute failed, other operations are affected.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4730]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 (a text);

source xxx/text.sql

test.sql fail size 110M.

error msg: ERROR 2020 (HY000): Got packet bigger than 'max_allowed_packet' bytes

<img width="917" alt="截屏2022-08-26 15 47 32" src="https://user-images.githubusercontent.com/39303074/186851989-23e810d3-d0af-409e-acc9-c8c67b4a93e0.png">

**Comment by tianyahui-python** [comment]
<img width="1143" alt="截屏2022-08-26 16 27 32" src="https://user-images.githubusercontent.com/39303074/186858663-5f1bb103-9fc5-4763-b0eb-f0e34d8918f1.png">

**Comment by tianyahui-python** [comment]
<img width="828" alt="截屏2022-08-26 16 32 33" src="https://user-images.githubusercontent.com/39303074/186859576-746b1a03-779d-4990-953c-44a5c7cf923f.png">

**Comment by tianyahui-python** [comment]
The Store directory must be deleted to restore normal conditions.

**Comment by badboynt1** [comment]
default max network packet is 100mb, so string larger than 100mb cause problem.
edit the conf like this, and then it can work.

cn.toml:  
[cn.rpc]
max-message-size = "300mb"

dn.toml:  
[dn.rpc]
max-message-size = "300mb"

log.toml:  
[logservice.rpc]
max-message-size = "300mb"

then restart MO, it works fine
MySQL [mo]> source /root/test/test.sql;
Query OK, 1 row affected (3.99 sec)

MySQL [mo]> 
MySQL [mo]> 
MySQL [mo]> 
MySQL [mo]> select length(a) from t1;
+-----------+
| length(a) |
+-----------+
| 145656000 |
+-----------+
1 row in set (0.33 sec)

**Comment by tianyahui-python** [comment]
<img width="1190" alt="截屏2022-11-08 15 12 43" src="https://user-images.githubusercontent.com/39303074/200498442-37204cea-a9fb-44b5-b731-3d60b844202e.png">
