### ISSUE TITLE
[Bug]: coalesce function, Inconsistent behavior bug.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4750]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t2 (a varchar);

mysql> explain verbose select coalesce(a,2) from t2;
+------------------------------------------------------------------------------+
| QUERY PLAN                                                                   |
+------------------------------------------------------------------------------+
| Project(cost=0.00..0.00 card=0.00 ndv=0.00 rowsize=0)                        |
|   Output: coalesce(CAST(t2.a AS BIGINT), 2)                                  |
|   ->  Table Scan on test_xx.t2(cost=0.00..0.00 card=0.00 ndv=0.00 rowsize=0) |
|         Output: t2.a                                                         |
|         Table: 't2' (0:'a')                                                  |
+------------------------------------------------------------------------------+
5 rows in set (0.00 sec)

select coalesce('aaa', 2);
ERROR 1105 (HY000): Can't cast 'aaa' from VARCHAR type to BIGINT type.

**Comment by ouyuanning** [comment]
that is executor throw error.

create table t2 (a varchar);
insert t2 values ("aaa") 
select coalesce(a,2) from t2;

then you can get error like :

select coalesce("aaa",2);


so that's no kind of bug
