### ISSUE TITLE
[Bug]: date_format function bug.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4764]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="871" alt="截屏2022-08-29 17 28 23" src="https://user-images.githubusercontent.com/39303074/187170994-682b03fc-ecff-468d-a1b4-a5071049d7f2.png">

**Comment by jianwan0214** [comment]
waiting for Dr tian to modify all the error msg. Now this err msg is maintained.

**Comment by tianyahui-python** [comment]
bvt tag not removed.

**Comment by tianyahui-python** [comment]
commit id: 9d7107e4d9541a1c91560d0e3de6566019ee734d

<img width="941" alt="截屏2022-10-31 10 27 13" src="https://user-images.githubusercontent.com/39303074/198918573-c5144e33-aaa1-4510-9b63-89895404ce09.png">
