### ISSUE TITLE
[Feature Request]: Support HEX function

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4773]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

HEX(str), HEX(N)

For a string argument str, HEX() returns a hexadecimal string representation of str where each byte of each character in str is converted to two hexadecimal digits. (Multibyte characters therefore become more than two digits.) The inverse of this operation is performed by the UNHEX() function.

For a numeric argument N, HEX() returns a hexadecimal string representation of the value of N treated as a longlong (BIGINT) number. This is equivalent to CONV(N,10,16). The inverse of this operation is performed by CONV(HEX(N),16,10).

For a NULL argument, this function returns NULL.

**Comment by yjw1268** [comment]
Hi I'd like to work on this issue 😀
