### ISSUE TITLE
[Bug]: Cannot get SQL resource from statement_info table

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4774]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In previous commit, user can get SQL source from statement_info, such as 
select statement from system.statement_info where statement like '%DBeaver%';

The result will include string as '/Application = DBeaver'. 

In the latest commit, there is no related information any more.
<img width="422" alt="image" src="https://user-images.githubusercontent.com/88298673/187365061-ae762304-0edd-46f6-aae5-ff155ddb659c.png">

**Comment by xzxiong** [comment]
@domingozhang how to recurrence？

**Comment by xzxiong** [comment]
sql `select * from information_schema.columns where table_schema = ...` in image is incomplete

**Comment by xzxiong** [comment]
use app `DBeaver` access mo, those statement will info like `/* ApplicationName=DBeaver 22.2.0 - Main */` as  image(1)
after `GetComputationWrapper(...)` got cws, seems lost notes info.

- image (1)
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/3927687/190943363-5f557fc6-5d52-4c1a-803b-1e83eff72120.png">

- image (2)
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/3927687/190943686-305b9305-b377-48e4-9dbd-c366a1d90041.png">

**Comment by xzxiong** [comment]
## why need `cws`
there may be multi statment in one sql. needs `cw` handle single statement.

## suggestion
1. save raw sql in `cw`
2. get `/*...*/` info from cw, save in table `statement_info` column `statement_tag`
3. (过渡方案) just use input `sql` as statement record, while `len(cw) == 1`

**Comment by xzxiong** [comment]
## Core needs
user can get all sql, and all sql come from which client

## What we have now.

目前可以从日志文件中查询到，所有sql的执行记录（如下图）
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/3927687/190974337-11fc1a2d-839f-4969-a0da-5ac5ccaeccef.png">

可通过关键字`connection id * query:` 查询，例如：

```
## 启动 mo-service
$ ./mo-service -cfg ./etc/cn-standalone-test.toml &>mo-service.log &

## 查询所有sql执行记录
$ grep "connection id .* query" mo-service.log
{"level":"INFO","time":"2022/09/19 10:59:39.157515 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1005 query:/* mysql-connector-java-8.0.29 (Revision: dd61577595edad45c398af508cf91ad26fc4144f) */SHOW VARIABLES"}
{"level":"INFO","time":"2022/09/19 10:59:39.158095 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1005 query:SET character_set_results = NULL"}
{"level":"INFO","time":"2022/09/19 10:59:39.158650 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1005 query:SET autocommit=1"}
{"level":"INFO","time":"2022/09/19 10:59:39.158974 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1005 query:/* ApplicationName=DBeaver 22.2.0 - Main */ SET autocommit=1"}
{"level":"INFO","time":"2022/09/19 10:59:39.159430 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1005 query:/* ApplicationName=DBeaver 22.2.0 - Main */ SELECT DATABASE()"}
{"level":"INFO","time":"2022/09/19 10:59:39.172428 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1006 query:/* mysql-connector-java-8.0.29 (Revision: dd61577595edad45c398af508cf91ad26fc4144f) */SHOW VARIABLES"}
{"level":"INFO","time":"2022/09/19 10:59:39.172913 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1006 query:SET character_set_results = NULL"}
{"level":"INFO","time":"2022/09/19 10:59:39.173084 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1006 query:SET autocommit=1"}
{"level":"INFO","time":"2022/09/19 10:59:39.173915 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1006 query:/* ApplicationName=DBeaver 22.2.0 - Metadata */ SET autocommit=1"}
{"level":"INFO","time":"2022/09/19 10:59:39.174504 +0800","caller":"frontend/mysql_cmd_executor.go:2201","msg":"connection id 1006 query:/* ApplicationName=DBeaver 22.2.0 - Metadata */ SELECT DATABASE()"}
```

**Comment by xzxiong** [comment]
## Conclusion Now

recommend user search sql from mo-service.log
