### ISSUE TITLE
[Docs]: PATH ERROR

### ISSUE THREAD

**Issue by Toms1999** [matrixorigin/matrixone#4777]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
PATH ERROR
```

### Additional information

![image](https://user-images.githubusercontent.com/94617906/187369902-d84faabe-8670-45bf-bec6-d1a190b84ef4.png)
![image](https://user-images.githubusercontent.com/94617906/187369968-2c0bf619-b68c-45d0-9f32-d00b65dcebe1.png)

**Comment by sukki37** [comment]
This issue has been inactive for a while. To help keep our backlog clear, I'm going to close this. If you feel this is still relevant, please comment or reopen. Thanks for understanding!
