### ISSUE TITLE
[Docs]: An error occurred when executing the document command

### ISSUE THREAD

**Issue by Toms1999** [matrixorigin/matrixone#4779]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
if i not configurate github id to linux,it will error,why not by http?
```

### Additional information

![image](https://user-images.githubusercontent.com/94617906/187372627-778c5c81-05a3-432c-b2c4-49614e617891.png)
![image](https://user-images.githubusercontent.com/94617906/187372664-f089b4cf-b5cc-406c-ab62-282f5a733902.png)

**Comment by dengn** [comment]
Please close this issue, it's fixed. @yingfeng
