### ISSUE TITLE
[Feature Request]: Distributed pipeline execution

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#4781]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

distributed pipeline

**Comment by m-schen** [comment]
contains three-part-work
1.  pipeline's serialization
2.  send and receive data with remote node.
3.  rebuild pipeline and process at remote node.

first work has done. PR is #4757

**Comment by m-schen** [comment]
the basic logic of step 2 and 3 is ok.
but found a bug in serialization work. we are fixing it now.

**Comment by m-schen** [comment]
need a more day or 2 days to fix the bug.

**Comment by m-schen** [comment]
pr is https://github.com/matrixorigin/matrixone/pull/5206

and I am trying to fix some small problems.

**Comment by m-schen** [comment]
the work is done.
