### ISSUE TITLE
[Bug]: panic bug in select and update

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4790]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.5.1
- Hardware parameters: Macbook m1 arm version 4c16g
- OS type: OSX
- Others:
```

### Actual Behavior

mysql> create table pe(ts_code varchar(255), trade_date varchar(255), pe float, pb float);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO `stock`.`pe` (`ts_code`) VALUES ('000001.SZ');
Query OK, 1 row affected (0.02 sec)

mysql> SELECT * FROM `stock`.`pe` WHERE `ts_code` = '000001.SZ' AND `trade_date` = 'NULL' AND `pe` = 'NULL' AND `pb` = 'NULL' LIMIT 1;
ERROR 1105 (HY000): Internal error: panic interface conversion: interface {} is []float32, not []uint64: goroutine 899 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x101327a20?, 0x1400a11a5a0})
	/Users/nandeng/Test/new_0.5.1/matrixone/pkg/common/moerr/error.go:110 +0x50
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
	/Users/nandeng/Test/new_0.5.1/matrixone/pkg/vm/vm.go:49 +0x38
panic({0x101327a20, 0x1400a11a5a0})
	/u
mysql> UPDATE `stock`.`pe` SET `trade_date` = '20220820' WHERE `ts_code` = '000001.SZ' AND `trade_date` = 'NULL' AND `pe` = 'NULL' AND `pb` = 'NULL' LIMIT 1;
ERROR 1105 (HY000): Internal error: panic interface conversion: interface {} is []float32, not []uint64: goroutine 983 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x101327a20?, 0x14002b4fe90})
	/Users/nandeng/Test/new_0.5.1/matrixone/pkg/common/moerr/error.go:110 +0x50
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
	/Users/nandeng/Test/new_0.5.1/matrixone/pkg/vm/vm.go:49 +0x38
panic({0x101327a20, 0x14002b4fe90})

**Comment by fengttt** [comment]
select for update is p0.   @daviszhen this need to involve both Mo Chen and Peng Zheng, even though may be a small task.

**Comment by dengn** [comment]
Not fixed yet.

Commit id: e9686aed42d95af234e29db5463936f023cbaba8

mysql> CREATE TABLE pe ( ts_code VARCHAR(255) DEFAULT NULL, trade_date VARCHAR(255) DEFAULT NULL, pe FLOAT DEFAULT NULL, pb FLOAT DEFAULT NULL );
Query OK, 0 rows affected (0.05 sec)

mysql>  INSERT INTO stock.pe (ts_code) VALUES ('000001.SZ');
Query OK, 1 row affected (0.05 sec)

mysql> SELECT * FROM stock.pe WHERE ts_code = '000001.SZ' AND trade_date = 'NULL' AND pe = 'NULL' AND pb = 'NULL' LIMIT 1;
ERROR 1105 (HY000): strconv.ParseFloat: parsing "NULL": invalid syntax

**Comment by iamlinjunhong** [comment]
wrong sql, modify as follow:
SELECT * FROM stock.pe WHERE ts_code = '000001.SZ' AND trade_date = NULL AND pe = NULL AND pb = NULL LIMIT 1;

UPDATE `stock`.`pe` SET `trade_date` = '20220820' WHERE `ts_code` = '000001.SZ' AND `trade_date` = NULL AND `pe` = NULL AND `pb` = NULL LIMIT 1;

**Comment by dengn** [comment]
This is Navicat behavior. By adding data manually. 

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/4965857/200222794-6a90900f-a79f-40cd-a22d-6d38b1a3c119.png">

**Comment by iamlinjunhong** [comment]
Mysql get some warnings for the kind of sql, so that Navicat will not report ERROR.
<img width="1187" alt="截屏2022-11-07 下午12 03 57" src="https://user-images.githubusercontent.com/49111204/200224112-4fe32f02-f617-4e13-b48a-a4a728962a99.png">

**Comment by dengn** [comment]
Acceptable for now. We may add a warning feature in the future.
