### ISSUE TITLE
[Bug]: Alias group by error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4797]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="793" alt="截屏2022-08-31 13 39 16" src="https://user-images.githubusercontent.com/39303074/187600626-2b47c212-d884-44ba-8c99-46496850c91d.png">

**Comment by domingozhang** [comment]
alias is not supported in group by. this issue can be closed
