### ISSUE TITLE
[Bug]: select count(*);  return result error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4798]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="995" alt="image" src="https://user-images.githubusercontent.com/39303074/187607939-41d74cfd-e2af-4d23-af12-1b8870a7b756.png">

### Expected Behavior

<img width="382" alt="截屏2022-08-31 14 23 06" src="https://user-images.githubusercontent.com/39303074/187608126-f4a8546c-4177-4891-9828-c1d187694197.png">

**Comment by fengttt** [comment]
Not a bug -- in fact I would prefer to error out select count(1).   You need a from clause for aggregate function.

**Comment by fengttt** [comment]
OK, took it back.   Seems you can select count(*) or select count(1); whatever that means.
