### ISSUE TITLE
[Performance]: LIKE is way too slow

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4810]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.5.1
- Hardware parameters: dev1
- OS type: CentOS
- Others:
```

### Details of Performance

600 millions records. 

each record is an output of a tcpdump result, such as

```
15:03:28.608152 IP 172.27.16.13.35080 > VM-0-12-centos.ssh: Flags [P.], seq 71916:71968, ack 520989, win 17630, options [nop,nop,TS val 3805462207 ecr 2532160890], length 52
15:03:28.599224 IP 172.27.16.13.35080 > VM-0-12-centos.ssh: Flags [P.], seq 71449:71501, ack 517992, win 17630, options [nop,nop,TS val 3805462198 ecr 2532160881], length 52
```

A query:

select tcp from tcp where tcp like '%172%';

takes about 8 mins to finish returning result. That's way too slow.

**Comment by daviszhen** [comment]
The LIKE's performance.

**Comment by fengttt** [comment]
like is important.

**Comment by aronchanisme** [comment]
Re-test on Feb 28th, 2023:
Summary:
1. Took around **0.145 seconds** to fetch **83514** rows from the table of **155,628** rows 
2. 

Steps:
1. Prepare metadata:
```
create database tcpdump;
create table tcp ( name varchar(255) );
```
2. run `tcpdump.py` for a while to generate

<img width="868" alt="image" src="https://user-images.githubusercontent.com/46433151/221800936-814c7caf-cfb6-4db6-a7ff-74cb2739b1e8.png">

Keep it running until the number of records reach **155,628**
<img width="869" alt="image" src="https://user-images.githubusercontent.com/46433151/221800899-0585340d-8b82-4304-a736-96ba60d3e84e.png">

Data looks like this
<img width="868" alt="image" src="https://user-images.githubusercontent.com/46433151/221802079-00127e27-c285-4bf9-89ac-ed2740226987.png">


4. Test performance running LIKE sql command:
```
select name from tcpdump.tcp where name like '%100%';

```

83514 rows in set (0.145 sec)

<img width="875" alt="image" src="https://user-images.githubusercontent.com/46433151/221802541-a4e739e7-5d9c-4260-babc-0d8c06dd22a4.png">

5. Keep inserting records into the table until the number reaches 671,179, then test again:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/46433151/221822295-16af0a4c-39a0-4677-adbb-53cae59bc5b7.png">

358561 rows in set (0.732 sec)


6. 600 millions (600,000,000), waiting for data to be inserted

**Comment by dengn** [comment]
fixed.
