### ISSUE TITLE
[Bug]: mo panic: open store/tae/46658.seg: too many open files

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#4820]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"INFO","time":"2022/09/01 11:06:43.557600 +0800","caller":"frontend/mysql_cmd_executor.go:2106","msg":"cmd 3"}
{"level":"INFO","time":"2022/09/01 11:06:43.557615 +0800","caller":"frontend/session.go:842","msg":"dbName sbtest tableNames [%!%mo_increment_columns sbtest1 sbtest2 sbtest3 sbtest4 sbtest5 sbtest6 sbtest7 sbtest8 sbtest9 sbtest10]"}
{"level":"INFO","time":"2022/09/01 11:06:43.556837 +0800","caller":"frontend/routine.go:137","msg":"connection id 1168 , the time of handling the request 242.006µs"}
{"level":"INFO","time":"2022/09/01 11:06:43.557682 +0800","caller":"frontend/mysql_cmd_executor.go:2106","msg":"cmd 3"}
panic: open store/tae/46658.seg: too many open files

goroutine 111 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.openSegment({0xcc55cd2228, 0x13}, 0xb642)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:85 +0x1bb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/segmentio.(*segmentFactory).Build(0x80?, {0xc000bf2040, 0xb}, 0x20f6b80?)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/dataio/segmentio/segment.go:47 +0xb0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.newSegment(0xc235b99dc0, {0x238d580?, 0x3477688?}, {0x23c8690?, 0xc000610240}, {0xc000bf2040?, 0xc360f90d80?})
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/tables/segment.go:41 +0x58
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*DataFactory).MakeSegmentFactory.func1(0xc75aa1ba00?)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/tables/factory.go:52 +0x34
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.NewSegmentEntry(0xc5eb205d60, {0x23e0c08, 0xc5f807d680}, 0x0, 0xca2909b350)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/catalog/segment.go:58 +0x1b0
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/catalog.(*TableEntry).CreateSegment(0xc5eb205d60, {0x23e0c08, 0xc5f807d680}, 0xf0?, 0x121c13b?)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/catalog/table.go:161 +0xbd
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).CreateSegment(0xc915a5c0b0)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:172 +0x74
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).prepareApplyNode(0xcb373f5b80, {0x23df618?, 0xc0eaad99d0})
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:133 +0x1f6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).PrepareApply(...)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:117
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PreCommitOr2PCPrepare(0xc9e6f47b10?)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:675 +0x86
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PreCommitOr2PCPrepare(0xcacbf17da0)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:364 +0x145
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PreCommitOr2PCPrepare(0x4ce8f7?)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:396 +0x9e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PreCommitOr2PCPrepare(0x416b4d?)
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:432 +0x25
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreCommitOr2PCPrepare(0xc0002a1a80?, {0x23e0a28, 0xcac4c282d0})
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:160 +0x66
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPreparing(0xc0002a1a80, {0xc0003b8000, 0x2, 0x0?})
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:201 +0xe5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:83 +0x1f4
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
 /data1/sudong/mo-regression/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:62 +0xea
[sudong@mo-srv-128 matrixone]$ ulimit

**Comment by LeftHandCold** [comment]
closed at #4785
