### ISSUE TITLE
[Bug]: auto_increment columns, delete from table. insert failed.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4836]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t3(
    -> a int primary key auto_increment,
    -> b varchar(10)
    -> );
Query OK, 0 rows affected (0.02 sec)

mysql> 
mysql> insert into t3 values (-19, 'aaa');
Query OK, 1 row affected (0.02 sec)

mysql> insert into t3(b) values ('bbb');
Query OK, 1 row affected (0.02 sec)

mysql> select * from t3 order by a;
+------+------+
| a    | b    |
+------+------+
|  -19 | aaa  |
|    1 | bbb  |
+------+------+
2 rows in set (0.01 sec)

mysql> delete from t3;
Query OK, 2 rows affected (0.02 sec)

mysql> insert into t3(b) values ('bbb');
ERROR 1105 (HY000): GetIndex from auto_increment table fail

<img width="723" alt="截屏2022-09-01 19 38 12" src="https://user-images.githubusercontent.com/39303074/187905088-d3e2dbb6-dd8d-4a54-acb8-8d9219806002.png">

**Comment by tianyahui-python** [comment]
<img width="738" alt="截屏2022-09-01 19 41 10" src="https://user-images.githubusercontent.com/39303074/187905536-cebd4da5-c14a-470a-aa7b-ea47e23548a4.png">

**Comment by tianyahui-python** [comment]
Load Data has the same problem.

**Comment by jianwan0214** [comment]
it will solved in later version. you can contact with zhangxiao.

**Comment by qingxinhome** [comment]
The feature requests related to deletetatement had been fixed, unit test and bvt test have been completed, and now request acceptance test, please know！ @tianyahui-python @jianwan0214 @daviszhen @aressu1985

**Comment by tianyahui-python** [comment]
commit id: 3a9e71b107a09edc2f8f0b0aadad0d25de44021b

<img width="1004" alt="截屏2022-10-31 16 15 11" src="https://user-images.githubusercontent.com/39303074/198962271-2b6e2d29-208e-447d-bc55-cd0619ec27a1.png">
