### ISSUE TITLE
[Bug]: load data null value and insert null value, inconsistent behavior.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4852]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1176" alt="截屏2022-09-02 16 49 49" src="https://user-images.githubusercontent.com/39303074/188102149-d45f287e-b26e-4a8a-9973-800eee5118ea.png">

<img width="605" alt="截屏2022-09-02 16 38 23" src="https://user-images.githubusercontent.com/39303074/188101121-8f5066ea-51b3-4258-9a84-fe1f89da76b4.png">

**Comment by jianwan0214** [comment]
in csv file, the null is represent as '\N'

**Comment by tianyahui-python** [comment]
<img width="1176" alt="截屏2022-09-02 17 04 43" src="https://user-images.githubusercontent.com/39303074/188105064-4cf4ddbd-c57e-411f-a35c-02787bad9d93.png">

<img width="299" alt="截屏2022-09-02 17 04 51" src="https://user-images.githubusercontent.com/39303074/188105092-596e4b0f-3906-4c89-be66-a39b2a914e27.png">

**Comment by tianyahui-python** [comment]
<img width="1183" alt="截屏2022-09-02 17 07 56" src="https://user-images.githubusercontent.com/39303074/188105640-cb42c98f-f2e4-4c23-adcd-7416910b18cf.png">

<img width="234" alt="截屏2022-09-02 17 08 19" src="https://user-images.githubusercontent.com/39303074/188105700-51dd9a12-ef62-456b-b963-5993f62f9285.png">

**Comment by tianyahui-python** [comment]
bvt tag not removed.

**Comment by tianyahui-python** [comment]
commit id:3a9e71b107a09edc2f8f0b0aadad0d25de44021b

<img width="1168" alt="截屏2022-10-31 16 37 50" src="https://user-images.githubusercontent.com/39303074/198966341-14407eff-31d0-4162-9a92-dda58563deae.png">

<img width="347" alt="截屏2022-10-31 16 38 20" src="https://user-images.githubusercontent.com/39303074/198966421-a3d7979c-ccf8-4455-bad3-69e3ebd346fb.png">
