### ISSUE TITLE
[Enhancement]: gcc build mod only allowed in C99

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#4867]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Change the default GCC buildstandard C89 to C99
```

### Why is this needed ?

Increases the fluency of buildedcode

**Comment by mklzl** [comment]
#4868

**Comment by Ariznawlll** [comment]
done
