### ISSUE TITLE
[Docs]: matrixone-architecture.png not found

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#4875]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
https://github.com/matrixorigin/artwork/blob/main/docs/overview/matrixone_new_arch.png?raw=true
this url is broken !
```

**Comment by dengn** [comment]
This url is ok, sometimes you've got to clean the cache of browser to show it.
