### ISSUE TITLE
[Bug]: desc table info error

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#4879]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):main
- Hardware parameters: 4C 4G 40G
- OS type:centos 7.6
- Others:
```

### steps:
    1.  CREATE TABLE Persons (
        ID int NOT NULL,
        LastName varchar(255) NOT NULL,
        FirstName varchar(255),
        Age int,
        PRIMARY KEY (ID)

     2. desc persons;
### Actual Behavior:

    +-----------+---------+------+------+---------+---------+
    | Field     | Type    | Null | Key  | Default | Comment |
    +-----------+---------+------+------+---------+---------+
    | id        | INT     | NO   | PRI  | NULL    |         |
    | lastname  | VARCHAR | YES  |      | NULL    |         |
    | firstname | VARCHAR | YES  |      | NULL    |         |
    | age       | INT     | YES  |      | NULL    |         |
    +-----------+---------+------+------+---------+---------+

### Expected Behavior:

    +-----------+---------+------+------+---------+---------+
    | Field     | Type    | Null | Key  | Default | Comment |
    +-----------+---------+------+------+---------+---------+
    | id        | INT     | NO   | PRI  | NULL    |         |
    | lastname  | VARCHAR | NO   |      | NULL    |         |
    | firstname | VARCHAR | YES  |      | NULL    |         |
    | age       | INT     | YES  |      | NULL    |         |
    +-----------+---------+------+------+---------+---------+

**Comment by aressu1985** [comment]
fix:fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

mysql> CREATE TABLE Persons (
    ->     ID int NOT NULL,
    ->     LastName varchar(255) NOT NULL,
    ->     FirstName varchar(255),
    ->     Age int,
    ->     PRIMARY KEY (ID)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> desc persons;
+-----------+---------+------+------+---------+-------+---------+
| Field     | Type    | Null | Key  | Default | Extra | Comment |
+-----------+---------+------+------+---------+-------+---------+
| id        | INT     | NO   | PRI  | NULL    |       |         |
| lastname  | VARCHAR | NO   |      | NULL    |       |         |
| firstname | VARCHAR | YES  |      | NULL    |       |         |
| age       | INT     | YES  |      | NULL    |       |         |
+-----------+---------+------+------+---------+-------+---------+
4 rows in set (0.02 sec)

mysql>
