### ISSUE TITLE
[Bug]: View cannot be involved in a join query

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4880]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

v1 is a view and t2 is a table.

select * from v1;
+------+------+
| b    | a    |
+------+------+
|    2 |    3 |
|    3 |   10 |
|    4 |   11 |
+------+------+

select * from t2;
+------+------+
| a    | b    |
+------+------+
|    3 | a    |
+------+------+
1 row in set (0.00 sec)

select * from v1,t2 where v1.a=t2.a;
ERROR 1105 (HY000): missing FROM-clause entry for table "v1"

In MySQL:

select * from v1,t2 where v1.a=t2.a;
+------+------+------+------+
| a    | b    | a    | b    |
+------+------+------+------+
|    3 |   10 |    3 | a    |
+------+------+------+------+
1 row in set (0.00 sec)

**Comment by aressu1985** [comment]
mysql> CREATE TABLE t2 (a INT);
ERROR 20415 (HY000): not connect to a database
mysql> use sudong;
Database changed
mysql> CREATE TABLE t2 (a INT);
Query OK, 0 rows affected (0.11 sec)
mysql> create view v1 as select * from t2;
Query OK, 0 rows affected (0.02 sec)

mysql> select * from v1,t2 where v1.a=t2.a;
Empty set (0.01 sec)

mysql> 
mysql>
