### ISSUE TITLE
[Docs]: Data-Manipulation-Statements/with-cte SQL format adjustment

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#4891]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
Strict definitions of single-row and multi-row SQL
```

**Comment by lacrimosaprinz** [comment]
@dengn already has been verified
https://github.com/matrixorigin/matrixone/pull/4892 can be merged
