### ISSUE TITLE
[Docs]: interval.md sql result error

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#4894]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
some query result error

select DATE_ADD('1900-01-01 00:00:00', INTERVAL '-1 10' DAY_HOUR)
```

**Comment by lacrimosaprinz** [comment]
@dengn  already has been verified
https://github.com/matrixorigin/matrixone/pull/4895  can be merged
