### ISSUE TITLE
[Bug]: select ... union select ..., execute error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4916]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> CREATE TABLE t1 (  id int(3) unsigned default '0');
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t1 (id) VALUES("1");
Query OK, 1 row affected (0.02 sec)

mysql> CREATE TABLE t2 ( id int(3) unsigned default '0',  id_master int(5) default '0',  text1 varchar(5) default NULL,  text2 varchar(5) default NULL);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t2 (id, id_master, text1, text2) VALUES("1", "1", "foo1", "bar1");
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t2 (id, id_master, text1, text2) VALUES("2", "1", "foo2", "bar2");
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t2 (id, id_master, text1, text2) VALUES("3", "1", NULL, "bar3");
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t2 (id, id_master, text1, text2) VALUES("4", "1", "foo4", "bar4");
Query OK, 1 row affected (0.02 sec)

mysql> SELECT 1 AS id_master, 1 AS id, NULL AS text1, 'ABCDE' AS text2 UNION SELECT id_master, t2.id, text1, text2 FROM t1 LEFT JOIN t2 ON t1.id = t2.id_master;
ERROR 1105 (HY000): panic runtime error: index out of range [0] with length 0: goroutine 20374 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x68
github.com/matrixorigin/matrixone/pkg/common/moerr.NewPanicError({0x10241e720?, 0x14001c8a1e0})
	/Users/tianyahui/work_code/go/matrixone/pkg/common/moerr/error.go:269 +0x5c
github.com/matrixorigin/matrixone/pkg/vm.Run.func1()
	/Users/tianyahui/work_code/go/matrixone/pkg/vm/vm.go:57 +0x38
panic({0x10241e720, 0x14001c8a1e0})
	/usr/local/go/src/runtime/
mysql> 
mysql>

**Comment by nnsgmsone** [comment]
This is because null corresponds to a vector length of 0, which is an undefined input.

**Comment by dongdongyang33** [comment]
These SQL have the same problem which cause by NULL:
1. SELECT 1 AS id_master, 1 AS id, NULL AS text1, 'ABCDE' AS text2 minus SELECT 10 AS id_master, 1 AS id, 'aa' AS text1, 'ABCDE' AS text2;
ERROR 1105 (HY000): panic unexpected parameter types were received: goroutine 1289 [running]

2. SELECT 1 AS id_master, 1 AS id, 'aa' AS text1, 'ABCDE' AS text2 UNION SELECT 10 AS id_master, 1 AS id, NULL AS text1, 'ABCDE' AS text2;
ERROR 1105 (HY000): panic reflect: call of reflect.Value.Len on zero Value: goroutine 1666

**Comment by dongdongyang33** [comment]
`NULL AS text1` has be parsed as `types.T_any` instead of `types.T_varchar`

**Comment by dongdongyang33** [comment]
Solution:
1. Correct the input type
2. Add ScalarNull handle flow
