### ISSUE TITLE
[Bug]: "set autocommit = on;" doesn't make sense. 

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#4920]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> show variables like 'autocommit';
+---------------+----------------+
| VARIABLE_NAME | VARIABLE_VALUE |
+---------------+----------------+
| autocommit    | off            |
+---------------+----------------+
1 row in set (0.00 sec)

mysql> set autocommit = on;
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like 'autocommit';
+---------------+----------------+
| VARIABLE_NAME | VARIABLE_VALUE |
+---------------+----------------+
| autocommit    | off            |
+---------------+----------------+
1 row in set (0.00 sec)

### Expected Behavior

mysql> show variables like 'autocommit';
+---------------+----------------+
| VARIABLE_NAME | VARIABLE_VALUE |
+---------------+----------------+
| autocommit    | off            |
+---------------+----------------+
1 row in set (0.00 sec)

mysql> set autocommit = on;
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like 'autocommit';
+---------------+----------------+
| VARIABLE_NAME | VARIABLE_VALUE |
+---------------+----------------+
| autocommit    | on          |
+---------------+----------------+
1 row in set (0.00 sec)

**Comment by aressu1985** [comment]
fixed:fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

mysql>  show variables like 'autocommit';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| autocommit    | on    |
+---------------+-------+
1 row in set (0.00 sec)



mysql> set autocommit = on;
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like 'autocommit';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| autocommit    | on    |
+---------------+-------+
1 row in set (0.00 sec)

mysql> set autocommit = off;
Query OK, 0 rows affected (0.00 sec)

mysql> show variables like 'autocommit';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| autocommit    | off   |
+---------------+-------+
1 row in set (0.00 sec)
