### ISSUE TITLE
[Bug]: pipeline hung

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#4929]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/blob/8bafc420cd4cacc2faa17227ec070f73d462cf40/pkg/sql/compile/compile_test.go#L78

If you uncomment the line
```
fault.Enable()
```

The test will hung, due to a panic.    Uncaught panic should be turned into error, not hung.   

### Steps to Reproduce

```Markdown
Turn on fault.Enable(), run unit test TestCompileWithFaults
```

**Comment by nnsgmsone** [comment]
Give cms a challenge

**Comment by nnsgmsone** [comment]
The reason for this is that cleanup improperly executes run in the defer function.

**Comment by nnsgmsone** [comment]
Good issue, just in time to exercise the youngsters. Let them solve this problem.

**Comment by m-schen** [comment]
get it. I will try to solve it after I finished my work at hand.

**Comment by fengttt** [comment]
@nnsgmsone I think, you need to remove all those "non error handling/release resource" defer()

defer should not be used as normal control flow -- I would rather use goto.

**Comment by m-schen** [comment]
I try to rewrite the pr. but can not start the Mo, I need time to handle that. probably delay.

**Comment by m-schen** [comment]
plz verify this bug. I uncomment the line and the test will repo error normally. @fengttt

**Comment by m-schen** [comment]
yeah. I have remerge the pr again. @fengttt 
hope it will not be reverted again. I have run the make ci 8 times. 😭

you can verify it now or after 0.6 release ( I think if nothing happens during this period, it can be proved to be a reliable pr)
