### ISSUE TITLE
[Bug]: Issues on current metric implement

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#4931]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d5f0dd95d40abbf9c53cf2c2463ec48cfa904ebb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. Document all metric/log table schema designs, the sampling rule, and the meaning of each attribute.

3. Some bugs need to be fixed:

- strange sampling points in `system_metrics.sql_latency_seconds`
- clarify the calculation rule for all statistical attributes, like `value` of `system_metrics.sql_latency_seconds`
- unify `tenant` and `account`, do not use them both in the definition 
- many attributes of tables in the `system` with incorrect or missing values
- implement span info collection for at least one key path of user query

**Comment by xzxiong** [comment]
1. Document all metric/log table schema designs, the sampling rule, and the meaning of each attribute.
   - [ ] designs
   - [x] sampling rule
   - [ ] meanning, 50%
   - [x] start version
2. Some bugs need to be fixed:
   - [x] (Removed) strange sampling points in `system_metrics.sql_latency_seconds`
   - [x] (Removed)clarify the calculation rule for all statistical attributes, like `value` of `system_metrics.sql_latency_seconds`
   - [x] ~~unify `tenant` and `account`, do not use them both in the definition~~, all used as `account` in metic/statement/error/log
   - [x] many attributes of tables in the `system` with incorrect or missing values
   - [ ] implement span info collection for at least one key path of user query

**Comment by sukki37** [comment]
@xzxiong update status pls

**Comment by xzxiong** [comment]
- [ ]  implement span info collection for at least one key path of user query
----
剩余这个span数据采集，我这周把它完结掉

**Comment by xzxiong** [comment]
- [x]  implement span info collection for at least one key path of user query

run mo with config
```
[observability]
enableTraceDebug = true
```
trace `create database` between CN and DN
we will get 1 statement_info record and 6 span_info records.

> PS: statement_info and span_info more detail in file https://github.com/matrixorigin/docs/blob/main/design/observability/how_to_use_trace_log_error.md

1 statement_info record
```
MySQL [system]> select * from statement_info where statement_id = '927bdb2f-63d2-11ed-8c62-dd1dccb44d3c'\G
*************************** 1. row ***************************
         statement_id: 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c
       transaction_id: 33d8e1d1-086e-426f-aafc-515df8186de0
           session_id: 8f31476f-63d2-11ed-8c62-dd1dccb44d3c
              account: sys
                 user: dump
                 host: 0.0.0.0
             database: system
            statement: create database test10
        statement_tag: 
statement_fingerprint: 
            node_uuid: 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf
            node_type: ALL
           request_at: 2022-11-14 12:12:37.022581
          response_at: 2022-11-14 12:12:37.037932
             duration: 15350602
               status: Success
             err_code: 0
                error: 
            exec_plan: {"code": 200, "message": "sql query no record execution plan", "steps": null, "success": false, "uuid": "927bdb2f-63d2-11ed-8c62-dd1dccb44d3c"}
            rows_read: 0
           bytes_scan: 0
1 row in set 
```

- 6 span_info records.
```
MySQL [system]> select trace_id, span_id, parent_span_id, span_name, start_time, end_time, duration from system.span_info where trace_id = '927bdb2f-63d2-11ed-8c62-dd1dccb44d3c' order by start_time;
+--------------------------------------+------------------+------------------+----------------------+----------------------------+----------------------------+----------+
| trace_id                             | span_id          | parent_span_id   | span_name            | start_time                 | end_time                   | duration |
+--------------------------------------+------------------+------------------+----------------------+----------------------------+----------------------------+----------+
| 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c | 6583b62a868dc755 | 0                | CreateDatabase       | 2022-11-14 12:12:37.030786 | 2022-11-14 12:12:37.034039 |  3252970 |
| 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c | 72bdf268addc1011 | 0                | sender.doSend        | 2022-11-14 12:12:37.034208 | 2022-11-14 12:12:37.034794 |   585774 |
| 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c | 39ab94d270a602cf | 72bdf268addc1011 | server.onMessage     | 2022-11-14 12:12:37.034276 | 2022-11-14 12:12:37.034722 |   445202 |
| 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c | 21415f7bc44774f2 | 0                | sender.doSend        | 2022-11-14 12:12:37.034809 | 2022-11-14 12:12:37.037900 |  3091174 |
| 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c | 0698f7a3d89bd91b | 21415f7bc44774f2 | server.onMessage     | 2022-11-14 12:12:37.034844 | 2022-11-14 12:12:37.037839 |  2994571 |
| 927bdb2f-63d2-11ed-8c62-dd1dccb44d3c | 553ef2966b1d3c16 | 0698f7a3d89bd91b | HandleCreateDatabase | 2022-11-14 12:12:37.034849 | 2022-11-14 12:12:37.034865 |    15758 |
+--------------------------------------+------------------+------------------+----------------------+----------------------------+----------------------------+----------+
6 rows in set
```
