### ISSUE TITLE
[Feature Request]: Support builtin function LEFT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#4938]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

[LEFT(str,len)](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_left)

Returns the leftmost len characters from the string str, or NULL if any argument is NULL.

Sample:
mysql> SELECT LEFT('foobarbar', 5);
        -> 'fooba'

**Comment by qingxinhome** [comment]
Support PR submission and merging of left system functions, including bvt test and unit test. Please know. @domingozhang @aressu1985 @daviszhen

**Comment by heni02** [comment]
@Ariznawlll test done，pr merged
