### ISSUE TITLE
[Bug]: select a from t3 union (select col2 from t4 order by col2); order by invalid.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4940]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t3;
create table t3(
a tinyint
);

insert into t3 values (20),(10),(30),(-10);

drop table if exists t4;
create table t4(
col1 smallint,
col2 smallint unsigned,
col3 float,
col4 bool
);

insert into t4 values(100, 65535, 127.0, 1);
insert into t4 values(300, 0, 1.0, 0);
insert into t4 values(500, 100, 0.0, 0);
insert into t4 values(200, 35, 127.0, 1);

(select a from t3) union  (select col2 from t4 order by col2);

<img width="886" alt="截屏2022-09-08 15 27 35" src="https://user-images.githubusercontent.com/39303074/189061431-e6efab1b-7115-45b0-9cf1-1669c696620b.png">

**Comment by nnsgmsone** [comment]
union must maintain type matching

**Comment by ouyuanning** [comment]
fixed by some PR
