### ISSUE TITLE
[Bug]: int type union bool type, should cast int type.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4942]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t3;
create table t3(
a tinyint
);

insert into t3 values (20),(10),(30),(-10);

drop table if exists t4;
create table t4(
col1 smallint,
col2 smallint unsigned,
col3 float,
col4 bool
);

insert into t4 values(100, 65535, 127.0, 1);
insert into t4 values(300, 0, 1.0, 0);
insert into t4 values(500, 100, 0.0, 0);
insert into t4 values(200, 35, 127.0, 1);

select a from t3 union select col4 from t4;

mysql> select a from t3 union select col4 from t4;
ERROR 1105 (HY000): Can't cast column from TINYINT type to BOOL type because of one or more values in that column.
mysql>

**Comment by nnsgmsone** [comment]
union must maintain type matching

**Comment by ouyuanning** [comment]
as confirm with @domingozhang 
we don't cast bool to int now.

**Comment by ouyuanning** [comment]
i don't know why,  but mo cast int (not 1,  not 0) as bool now.

**Comment by tianyahui-python** [comment]
commit id: 9a457bc5e8f956377739d67f9703828bd8b7e4f4

<img width="848" alt="截屏2022-10-29 15 58 48" src="https://user-images.githubusercontent.com/39303074/198820675-99c17e97-de4d-436a-bdea-6440945d1d0e.png">
