### ISSUE TITLE
[Bug]: should support SELECT 1, 2 UNION SELECT 'a', 'b'; 

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4944]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> SELECT 1, 2 UNION SELECT 'a', 'b';
ERROR 1105 (HY000): Can't cast 'a' from VARCHAR type to BIGINT type.

### Expected Behavior

<img width="560" alt="截屏2022-09-08 16 37 22" src="https://user-images.githubusercontent.com/39303074/189076176-29b08d45-422d-44bd-a3f5-0ad90fc2e29f.png">

**Comment by tianyahui-python** [comment]
<img width="1266" alt="截屏2022-09-09 10 31 24" src="https://user-images.githubusercontent.com/39303074/189260075-341fc510-0ac0-42fe-8b8e-e9c8deebc822.png">

**Comment by ouyuanning** [comment]
as confirm with @domingozhang 
we will follow Pg's rule.    String meet Integer,  we will cast String as integer,  If can not cast (like 'ab')， just throw error
