### ISSUE TITLE
[Bug]: need support union  intersect grammar.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4946]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

need support:
query1 UNION query2 INTERSECT query3

query1 UNION (query2 INTERSECT query3)

query1 UNION query2 minus query3

(query1 UNION query2 ) Minus query3

![image](https://user-images.githubusercontent.com/39303074/189104109-268de32e-68b3-48fd-9f67-284233d3588d.png)

**Comment by badboynt1** [comment]
already supported in latest version

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
bvt tag no remove.
