### ISSUE TITLE
[Bug]: (NULL) IS UNKNOWN

### ISSUE THREAD

**Issue by Dream95** [matrixorigin/matrixone#4949]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):v0.5.1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> SELECT  (NULL) IS UNKNOWN;
+-----------+
| (null) =  |
+-----------+
| NULL      |
+-----------+
1 row in set (0.01 sec)

### Expected Behavior

in mysql
(NULL) IS UNKNOWN
1

**Comment by aressu1985** [comment]
mysql>  SELECT (NULL) IS UNKNOWN;
+-------------------+
| (null) is unknown |
+-------------------+
| true              |
+-------------------+
1 row in set (0.00 sec)

mysql>
