### ISSUE TITLE
[Bug]: Primary key should not be null

### ISSUE THREAD

**Issue by Dream95** [matrixorigin/matrixone#4950]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):v0.5.1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t1(c1 int primary key);
Query OK, 0 rows affected (0.09 sec)
mysql> insert into t1 values(null);
Query OK, 1 row affected (0.08 sec)
mysql> select * from t1;
+------+
| c1   |
+------+
|    0 |
+------+
1 row in set (0.01 sec)

### Expected Behavior

mysql> insert into t1 values(null);
Column 'c1' cannot be null

**Comment by iamlinjunhong** [comment]
c1 values is 0, different from the follow case:
mysql> create table t2 (a int );
Query OK, 0 rows affected (0.04 sec)
mysql> insert into t2 values ( null );
Query OK, 1 row affected (4.00 sec)
mysql> select * from t2;
+------+
| a    |
+------+
| NULL |
+------+
1 row in set (0.00 sec)

**Comment by XuPeng-SH** [comment]
It should be fixed.

**Comment by sukki37** [comment]
Verified.
<img width="644" alt="image" src="https://user-images.githubusercontent.com/77312370/217717055-4033347c-ad06-4d4d-8bb6-766245f9943c.png">
