### ISSUE TITLE
[Bug]: select ... union ....select ...left join. The query causes the service to crash.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#4954]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t15;

CREATE TABLE t15 (
id int(3) unsigned default '0'
);

INSERT INTO t15 (id) VALUES("1");

drop table if exists t16;
CREATE TABLE t16 (
id int(3) unsigned default '0',
id_master int(5) default '0',
text15 varchar(5) default NULL,
text16 varchar(5) default NULL
);

INSERT INTO t16 (id, id_master, text15, text16) VALUES("1", "1", "foo1", "bar1");
INSERT INTO t16 (id, id_master, text15, text16) VALUES("2", "1", "foo2", "bar2");
INSERT INTO t16 (id, id_master, text15, text16) VALUES("3", "1", NULL, "bar3");
INSERT INTO t16 (id, id_master, text15, text16) VALUES("4", "1", "foo4", "bar4");

(SELECT 1 AS id_master, 1 AS id, NULL AS text15, 'ABCDE' AS text16) UNION all (SELECT id_master, t16.id, text15, text16 FROM t15 LEFT JOIN t16 ON t15.id = t16.id_master);

<img width="1371" alt="截屏2022-09-09 10 57 06" src="https://user-images.githubusercontent.com/39303074/189265040-ed75d168-2dc8-4081-8c27-bc1b506c41ef.png">

[mo.log](https://github.com/matrixorigin/matrixone/files/9532076/mo.log)

mo.log;

**Comment by dongdongyang33** [comment]
This issue has been fixed by @ouyuanning 's pr - #5023
