### ISSUE TITLE
[Feature Request]: Add query execution result and error messages to log record

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#4958]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

#4582 

### Describe the feature you'd like

We need to add query result and error messages in the log recording. 
For queries with syntax error or unsupported messages, we need to be able to query it.

**Comment by daviszhen** [comment]
It was done in lastest code.
