### ISSUE TITLE
[Bug]: The function of STARTSWITH() has a Prefix processing problem

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#4963]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The Question is : 
    The second parameter of the STARTSWITH() function represents the prefix, but it doesn't seem to handle the case of an empty string.

Ex : 
SELECT str1, STARTSWITH(str1,'') from char_test;

Result : 
str1 field has value, The result of SQL statement above is 1.

**Comment by fengttt** [comment]
Original behavior is correct.   The only question should be if return 1 is correct -- should be true?    

I will close as not a bug, unless people has a reason/doc to believe otherwise.
