### ISSUE TITLE
[Bug]: The function of ENDSWITH() has a suffix processing problem

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#4966]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The Question is :
    The second parameter of the ENDSWITH() function represents the suffix, but it doesn't seem to handle the case of an empty string.

Ex :
SELECT str1, ENDSWITH(str1,'') from char_test;

Result :
str1 field has value, The result of SQL statement above is 1.

**Comment by fengttt** [comment]
Orig behaviour is correct.  Not a bug.

**Comment by fengttt** [comment]
Unless supplying a doc link, I think we shoud close.
