### ISSUE TITLE
[Feature Request]: select for update

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#5004]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Need to support SELECT FOR UPDATE query.
```

### Describe the feature you'd like

SELECT FOR UPDATE should turn this select into a write action, adding a "write" no-op on this record.     TAE should perform conflict checking as if it is an ordinary write.

### Describe implementation you've considered

Other database may put a W or RIW lock on this record.    Up for TAE folks to evaluate if this lock is worthy, or possible to impl.

**Comment by heni02** [comment]
test done, 0.8 there are functional issues

**Comment by heni02** [comment]
test done
