### ISSUE TITLE
[Feature Request]: Support first batch error code 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5009]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

The first batch of error code:

ER_CANT_CREATE_DB uint16 = 1006
--
ER_DB_CREATE_EXISTS uint16 = 1007
ER_DB_DROP_EXISTS uint16 = 1008
ER_DUP_KEY uint16 = 1022
ER_OUTOFMEMORY uint16 = 1037
ER_CON_COUNT_ERROR uint16 = 1040
ER_ACCESS_DENIED_ERROR uint16 = 1045
ER_NO_DB_ERROR uint16 = 1046
ER_UNKNOWN_COM_ERROR uint16 = 1047
ER_BAD_NULL_ERROR uint16 = 1048
ER_TABLE_EXISTS_ERROR uint16 = 1050
ER_BAD_TABLE_ERROR uint16 = 1051
ER_WRONG_SUM_SELECT uint16 = 1057
ER_DUP_FIELDNAME uint16 = 1060
ER_DUP_KEYNAME uint16 = 1061
ER_DUP_ENTRY uint16 = 1062
ER_INVALID_DEFAULT uint16 = 1067
ER_BLOB_USED_AS_KEY uint16 = 1073
ER_WRONG_AUTO_KEY uint16 = 1075
ER_LOAD_INFO uint16 = 1087
ER_INSERT_INFO uint16 = 1092
ER_BLOB_CANT_HAVE_DEFAULT uint16 = 1101
ER_UNKNOWN_ERROR uint16 = 1105
ER_TABLE_MUST_HAVE_COLUMNS uint16 = 1113
ER_INVALID_USE_OF_NULL uint16 = 1138
ER_TABLEACCESS_DENIED_ERROR uint16 = 1142
ER_ILLEGAL_GRANT_FOR_TABLE uint16 = 1144
ER_GRANT_WRONG_HOST_OR_USER uint16 = 1145
ER_NO_SUCH_TABLE uint16 = 1146
ER_NONEXISTING_TABLE_GRANT uint16 = 1147
ER_SYNTAX_ERROR uint16 = 1149
ER_WRONG_COLUMN_NAME uint16 = 1166
ER_WRONG_KEY_COLUMN uint16 = 1167
ER_DUP_UNIQUE uint16 = 1169
ER_BLOB_KEY_WITHOUT_LENGTH uint16 = 1170
ER_PRIMARY_CANT_HAVE_NULL uint16 = 1171
ER_REQUIRES_PRIMARY_KEY uint16 = 1173
ER_CHECK_NO_SUCH_TABLE uint16 = 1177
ER_SUBQUERY_NO_1_ROW uint16 = 1242
ER_UNKNOWN_STMT_HANDLER uint16 = 1243
ER_AUTO_CONVERT uint16 = 1246
ER_DERIVED_MUST_HAVE_ALIAS uint16 = 1248
ER_REVOKE_GRANTS uint16 = 1269
ER_DUPLICATED_VALUE_IN_TYPE uint16 = 1291
ER_UNKNOWN_TIME_ZONE uint16 = 1298
ER_QUERY_INTERRUPTED uint16 = 1317
ER_VIEW_INVALID uint16 = 1356
ER_ILLEGAL_VALUE_FOR_TYPE uint16 = 1367
ER_WRONG_VALUE_FOR_TYPE uint16 = 1411
ER_NO_SUCH_USER uint16 = 1449
ER_WRONG_STRING_LENGTH uint16 = 1470
ER_AMBIGUOUS_FIELD_TERM uint16 = 1475
ER_ONLY_ON_RANGE_LIST_PARTITION uint16 = 1512
ER_TOO_LONG_TABLE_COMMENT uint16 = 1628
ER_TOO_LONG_FIELD_COMMENT uint16 = 1629
ER_DATABASE_NAME uint16 = 1631
ER_TABLE_NAME uint16 = 1632
ER_DATA_OUT_OF_RANGE uint16 = 1690
ER_ACCESS_DENIED_NO_PASSWORD_ERROR uint16 = 1698
ER_NOT_VALID_PASSWORD uint16 = 1819
ER_QUERY_TIMEOUT uint16 = 3024
ER_INVALID_JSON_DATA uint16 = 3069
ER_INVALID_JSON_TEXT uint16 = 3140
ER_INVALID_TYPE_FOR_JSON uint16 = 3146
ER_INVALID_CAST_TO_JSON uint16 = 3147
ER_USER_DOES_NOT_EXIST uint16 = 3162
ER_USER_ALREADY_EXISTS uint16 = 3163
ER_SESSION_WAS_KILLED uint16 = 3169
ER_CAPACITY_EXCEEDED uint16 = 3170
ER_NO_SUCH_DB uint16 = 3503
ER_FAILED_ROLE_GRANT uint16 = 3524
ER_FAILED_DEFAULT_ROLES uint16 = 3526
ER_ROLE_NOT_GRANTED uint16 = 3530
ER_FAILED_REVOKE_ROLE uint16 = 3531
ER_ILLEGAL_PRIVILEGE_LEVEL uint16 = 3619
ER_CANNOT_CONVERT_STRING uint16 = 3854
ER_DB_ACCESS_DENIED uint16 = 3879
ER_HOSTNAME_TOO_LONG uint16 = 3968
ER_STATEMENT_NOT_ALLOWED_AFTER_START_TRANSACTION uint16 = 3977
ER_NOT_ALLOWED_WITH_START_TRANSACTION uint16 = 3979
ER_INVALID_JSON_ATTRIBUTE uint16 = 3980
ER_IMPLICIT_COMPARISON_FOR_JSON uint16 = 3986
ER_IMPOSSIBLE_STRING_CONVERSION uint16 = 3988
ER_INVALID_CAST uint16 = 3998
ER_ROLE_GRANTED_TO_ITSELF uint16 = 4027

**Comment by fengttt** [comment]
Punt to 0.7

**Comment by fengttt** [comment]
We will not support so many.   Back to basics.   We resolve app by app.   This will be an on-going effort.
