### ISSUE TITLE
[Bug]: load data infile ..... float type and double type, the default precision should is four decimal places.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5039]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a float, b double);

load data infile 'float.csv' into table t1;

select * from t1;
+--------+-------------------+
| a      | b                 |
+--------+-------------------+
|   3.63 | 5.940000057220459 |
| 3.2099 | 4.509900093078613 |
| 1.4533 | 8.498800277709961 |
+--------+-------------------+

<img width="247" alt="截屏2022-09-15 18 10 16" src="https://user-images.githubusercontent.com/39303074/190378648-2eec1685-0334-4de6-872a-ee32693cdac0.png">

**Comment by tianyahui-python** [comment]
select * from t1;
+--------+-------------------+
| a | b |
+--------+-------------------+
| 3.6300 | 5.9400 |
| 3.2099 | 4.5099 |
| 1.4533 | 8.4988 |
+--------+-------------------+

**Comment by jianwan0214** [comment]
now we appear the float&double number with it's real value, not specify the number of digits

**Comment by tianyahui-python** [comment]
> now we appear the float&double number with it's real value, not specify the number of digits
----------------------
<img width="1164" alt="截屏2022-10-24 15 16 09" src="https://user-images.githubusercontent.com/39303074/197468842-7f228bc8-a5b0-49cd-acff-3f663722c473.png">
