### ISSUE TITLE
[Bug]: load data ... csv file, timestamp type query result abnormal .

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5046]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1213" alt="截屏2022-09-16 10 01 09" src="https://user-images.githubusercontent.com/39303074/190540285-1943ff1c-167c-44f2-b339-11ff7266344c.png">

<img width="423" alt="截屏2022-09-16 10 01 26" src="https://user-images.githubusercontent.com/39303074/190541783-b5464949-dbc9-4ce3-91cd-c10240105b67.png">

<img width="360" alt="截屏2022-09-16 10 01 31" src="https://user-images.githubusercontent.com/39303074/190540418-8394a4ea-971d-403a-b6fd-3cfabc7e0bf4.png">

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
bvt tag no remove.

**Comment by tianyahui-python** [comment]
commit id:3a9e71b107a09edc2f8f0b0aadad0d25de44021b

<img width="1107" alt="截屏2022-10-31 16 41 47" src="https://user-images.githubusercontent.com/39303074/198967053-94523e24-07d4-43ec-b74d-c4df666ca0e2.png">
