### ISSUE TITLE
[Bug]: When operator IN's list contains NULL, a error occurs

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5062]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The SQL statement is : 
      SELECT 'a' IN ('a','b','c'), 1 IN (2,3), NULL IN ('a','b'), 'a' IN ('a', NULL);

The result is (Running on MO) : 
      true    false    NULL    NULL

The result should be : 
      true    false    NULL    true

The result on MySQL is : 
      1    0    NULL    1

**Comment by qingxinhome** [comment]
This bug has been solved, tested and verified, and has been merged. Please know. @goodMan-code @daviszhen @jianwan0214 @yingfeng
