### ISSUE TITLE
[Feature Request]: Support SET clause in LOAD DATA to tell the NULL string

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5079]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

In LOAD DATA statement, there needs a clause of SET to tell the NULL string as following

SET
    col_name = nullif(col_name ,'NULL');

If use SET, the string NULL in CSV will be loaded as null value not a string NULL

**Comment by jianwan0214** [comment]
https://stackoverflow.com/questions/22300228/mysql-load-data-infile-null-string-in-csv-for-datetime

**Comment by domingozhang** [comment]
\N is still NULL
If the nullif(col_name , value) is true, it returns NULL value. 
Such as nullif(a, 'null')
