### ISSUE TITLE
[Bug]: load data string type, csv file exist multiple consecutive double quotation marks, the results did not meet expectations.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5087]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t2;
create table t2(
col1 char(225),
col2 varchar(225),
col3 text,
col4 varchar(225)
);

load data infile 'csv' into table t2;

<img width="536" alt="截屏2022-09-19 16 48 45" src="https://user-images.githubusercontent.com/39303074/190982376-e6c045cc-457b-4f73-be4c-4e9e8227ab97.png">

<img width="773" alt="截屏2022-09-19 16 13 59" src="https://user-images.githubusercontent.com/39303074/190982452-d1ef5bd3-58e9-433c-b617-75bd49bc0cdd.png">

**Comment by jianwan0214** [comment]
it will solved in 0.7

**Comment by daviszhen** [comment]
we do not focus on it today

**Comment by daviszhen** [comment]
rfc4180
