### ISSUE TITLE
[Bug]: blob type doesn't recognize _binary

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#5098]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table a(a blob);
Query OK, 0 rows affected (0.05 sec)

mysql> insert into a values (_binary'123');
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 29 near "_binary'123')";

**Comment by sukki37** [comment]
@JackTan25 pls update status

**Comment by heni02** [comment]
confirm,closed
commit id:cf3f6d220198efcc8ea900e2e6308d0367cb7dab
![image](https://user-images.githubusercontent.com/113406637/201036590-83310b1c-ee46-42ea-8f5c-c9260a28c436.png)
