### ISSUE TITLE
[Bug]: mo-service freezes on some query

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#5105]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters: Intel Xeon 16C32T + 256GiB
- OS type: linux amd64
- Others:
```

### Actual Behavior

On tpc-h 10g data(Sample Factor = 10), run below query will make mo-service frozen at 0% CPU and memory not exhausted:

```sql
select
  o_orderkey
from
  orders,
  lineitem
where
  o_orderkey in (
    select
      l_orderkey
    from
      lineitem
    group by
      l_orderkey having
        sum(l_quantity) > 314
  )
  and o_orderkey = l_orderkey
  limit 10
;
```

But when we add an ORDER BY clause it runs normally:

```sql
select
  o_orderkey
from
  orders,
  lineitem
where
  o_orderkey in (
    select
      l_orderkey
    from
      lineitem
    group by
      l_orderkey having
        sum(l_quantity) > 314
  )
  and o_orderkey = l_orderkey
  order by o_orderdate
  limit 10
;
```

o_orderkey
19628135
21213895
21213895
21213895
19628135
21213895
21213895
21213895
19628135
21213895

**Comment by nnsgmsone** [comment]
After collaborating with Ming Song, the code of cleanup was modified and it was ready to run. It should be fixed when cleanup is merged.

**Comment by aunjgr** [comment]
What I can tell is that it blocks at

https://github.com/matrixorigin/matrixone/blob/e1d7df5fa91606bd51d93717b61bbd0fabeabb8c/pkg/sql/colexec/merge/merge.go#L48

The merge operator waits for one child node each time. Should we try a mpsc channel instead?

@m-schen @nnsgmsone @fengttt

**Comment by nnsgmsone** [comment]
> What I can tell is that it blocks at
> 
> https://github.com/matrixorigin/matrixone/blob/e1d7df5fa91606bd51d93717b61bbd0fabeabb8c/pkg/sql/colexec/merge/merge.go#L48
> 
> The merge operator waits for one child node each time. Should we try a mpsc channel instead?
> 
> @m-schen @nnsgmsone @fengttt

For example, there are four pipelines A, B, C, D. I want the consumption data to be A.data, B.data,C.data,D.data, A.data, B.data, C.data, D.data. I don't want to have a consumption order of A.data, A.data, B.data, B.data, C.data, C.data, D.data, D.data. I think this will lead to low efficiency.

**Comment by aunjgr** [comment]
It is verified to be fixed by #6453.

**Comment by fengttt** [comment]
Wrong result.   So must stay open as S-1.

**Comment by aunjgr** [comment]
The problem is, `Dispatch` operator pushes data to it's children in a round-robin order, `Merge` operator pulls result from children in another round-robin order, while each children can hold only one batch at the same time. So, if `Dispatch` is waiting to push to Child 0, and `Merge` is waiting to pull from Child 1, and Child 0 is waiting to be pulled, it's a dead lock.

If `Merge` can listen on all children at the same time, this dead lock can be resolved.

https://stackoverflow.com/questions/19992334/how-to-listen-to-n-channels-dynamic-select-statement This thread may provide a solution. Need further study.

**Comment by fengttt** [comment]
I don't get it -- why Merge does not listen to only only one channel and children push into that channel?

**Comment by aunjgr** [comment]
Close since it's fixed.
