### ISSUE TITLE
[Bug]: sql create account name XXX error when account name is key word

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5108]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

default is key word and change to  default1 name  successfully
mysql> create account default ADMIN_NAME 'admin' IDENTIFIED BY '123456';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 22 near " default ADMIN_NAME 'admin' IDENTIFIED BY '123456'";
mysql> create account default1 ADMIN_NAME 'admin' IDENTIFIED BY '123456';
Query OK, 0 rows affected (0.08 sec)

**Comment by iamlinjunhong** [comment]
you need to learn about mysql. Keyword can not be name. Or you can use \`default\` to create

**Comment by heni02** [comment]
confrim,closed
