### ISSUE TITLE
[Bug]: less than date type min value, load data and insert execute success.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5115]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t4;
create table t4(
col1 date,
col2 datetime,
col3 timestamp,
col4 bool
);

load data infile 'csv' into table t4;    should execute failed.

csv data: 0999-01-01,0001-01-01,,0

insert into t4(col1) values ("0999-01-01");   should execute failed

**Comment by bbbearxyz** [comment]
now date type range is date[0001-01-01 to 9999-12-31], datetime range is // date[0001-01-01 00:00:00 to 9999-12-31 23:59:59]

**Comment by tianyahui-python** [comment]
<img width="873" alt="截屏2022-09-20 下午9 52 48" src="https://user-images.githubusercontent.com/39303074/191276376-f15abffc-e273-4724-a9df-ba8e85806cf7.png">


https://docs.matrixorigin.io/cn/0.5.1/MatrixOne/Reference/Data-Types/data-types/

**Comment by tianyahui-python** [comment]
> now date type range is date[0001-01-01 to 9999-12-31]

Where can I look this up？

**Comment by domingozhang** [comment]
As product design, the range of date should be the same as mysql  which is between 1000-01-01 and 9999-12-31

**Comment by tianyahui-python** [comment]
As product design, the range of date should be the same as mysql which is between 1000-01-01 and 9999-12-31
-----------------------------------------------------------
@bbbearxyz

**Comment by bbbearxyz** [comment]
pr #6245  all ready add date/datetime range check, if out of range, sys will report err. But in the extern table, only when select data from table, then the table parse data/datetime. this is designed by @jianwan0214.

**Comment by bbbearxyz** [comment]
now #6245 support timestamp range check

**Comment by fengttt** [comment]
Not a bug.
