### ISSUE TITLE
[Bug]: ERROR 1105 (HY000): no such file 'etl:system_metrics/process_max_fds_*.csv'

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5142]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ea4bcff9ac2b9147428f45021e12bfe9a73c31af
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

{"level":"ERROR","time":"2022/09/21 14:37:25.099189 +0800","caller":"frontend/mysql_cmd_executor.go:2166","msg":"no such file 'etl:system_metrics/process_max_fds_*.csv'"}
{"level":"ERROR","time":"2022/09/21 14:37:25.099277 +0800","caller":"frontend/util.go:456","msg":"Connection id: 1011 Status: fail Statement: select * from process_max_fds limit 10 Error: no such file 'etl:system_metrics/process_max_fds_*.csv'","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/Users/maomao/tmp/matrixone/pkg/frontend/util.go:456\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/Users/maomao/tmp/matrixone/pkg/frontend/util.go:448\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/maomao/tmp/matrixone/pkg/frontend/mysql_cmd_executor.go:2174\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/maomao/tmp/matrixone/pkg/frontend/mysql_cmd_executor.go:2243\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/maomao/tmp/matrixone/pkg/frontend/routine.go:122"}

### Expected Behavior

no error

### Steps to Reproduce

```Markdown
select * from process_max_fds limit 10;
```

### Additional information

I'd like to discuss whether to report an error or return an empty resultset if no files are found related to an external table. @fengttt

**Comment by xzxiong** [comment]
chould response like this: empty set, with warnings.
```
mysql> select * from process_max_fds limit 10;
Empty set, 1 Warnings  (0.01 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------+
| Level   | Code | Message                                                   |
+---------+------+-----------------------------------------------------------+
| Warning | 1105 | no such file 'etl:system_metrics/process_max_fds_*.csv'   |
+---------+------+-----------------------------------------------------------+
```

**Comment by aressu1985** [comment]
file ds metrics do not need to be supported in 0.6.0
