### ISSUE TITLE
[Bug]: panic info be output when left join

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5150]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The structure of t1 is : 
CREATE TABLE t1(
    id VARCHAR(20),
    name VARCHAR(20)
);

The structure of t2 is : 
CREATE TABLE t2(
    id VARCHAR(20),
    n1 INT,
    n2 FLOAT
);

The SQL statement is : 
SELECT t1.id, name, n1, n2
FROM t1 LEFT JOIN t2 ON t1.id = t2.id
WHERE id NOT BETWEEN '0' AND '2' AND n2 BETWEEN NULL AND NULL;

The output on MO is : 
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 239 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.ConvertPanicError({0x1fe7b00?, 0x35af400})
	/home/mo/matrixone/pkg/common/moerr/error.go:370 +0x65
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/home/mo/matrixone/pkg/frontend/mysql_cmd_executor.go:2379 +0xdc
panic({0x1fe7b00, 0x35

**Comment by aunjgr** [comment]
I can't reproduce this behavior. On my computer the output is:
```
ERROR 20301 (HY000): invalid input: ambiguouse column reference to 'id'
```
