### ISSUE TITLE
[Bug]: primary key allow null value

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#5162]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

primary key col don't support null value.

**Comment by aressu1985** [comment]
fixed:fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

mysql> drop table if exists t1;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t1(a int, b int, primary key(a));
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t1 values(null, 1);
ERROR 20304 (HY000): constraint violation: Column 'a' cannot be null
mysql>
