### ISSUE TITLE
[Feature Request]: REPLACE Statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5182]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

REPLACE works exactly like INSERT, except that if an old row in the table has the same value as a new row for a PRIMARY KEY or a UNIQUE index, the old row is deleted before the new row is inserted.

REPLACE 
    INTO tbl_name
    [(col_name [, col_name] ...)]
    { {VALUES | VALUE} (value_list) [, (value_list)] ...
      |
      VALUES row_constructor_list
    }

**Comment by TheR1sing3un** [comment]
Hi～Please assign it to me~
