### ISSUE TITLE
[Feature Request]: DO Statement and DECLARE Statement 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5184]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

DO executes the expressions but does not return any results. In most respects, DO is shorthand for SELECT expr, ..., but has the advantage that it is slightly faster when you do not care about the result.

DO expr [, expr] ...

This statement declares local variables within stored programs. To provide a default value for a variable, include a DEFAULT clause. The value can be specified as an expression; it need not be a constant. If the DEFAULT clause is missing, the initial value is NULL.

DECLARE var_name [, var_name] ... type [DEFAULT value]

**Comment by TszKitLo40** [comment]
In this issue, we only implement the parsing part, and the execution part will not be implemented.
