### ISSUE TITLE
[Feature Request]: HANDLER Statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5185]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

The HANDLER statement provides direct access to table storage engine interfaces. 

HANDLER tbl_name OPEN [ [AS] alias]
HANDLER tbl_name READ { FIRST | NEXT }
    [ WHERE where_condition ] [LIMIT ... ]
HANDLER tbl_name CLOSE

The HANDLER ... OPEN statement opens a table, making it accessible using subsequent HANDLER ... READ statements. This table object is not shared by other sessions and is not closed until the session calls HANDLER ... CLOSE or the session terminates.
The HANDLER ... READ syntax fetches a row from the table in natural row order that matches the WHERE condition. Natural row order is the order in which rows are stored in a TAE table data file.
Without a LIMIT clause, all forms of HANDLER ... READ fetch a single row if one is available. To return a specific number of rows, include a LIMIT clause. It has the same syntax as for the SELECT statement. 
HANDLER ... CLOSE closes a table that was opened with HANDLER ... OPEN.

**Comment by zevin02** [comment]
I would try to finish this.

**Comment by XiaoYaoheihei** [comment]
I would try to finish this.
