### ISSUE TITLE
[Feature Request]: CREATE TRIGGER/DROP TRIGGER

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5187]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

This statement creates a new trigger. A trigger is a named database object that is associated with a table, and that activates when a particular event occurs for the table. The trigger becomes associated with the table named tbl_name, which must refer to a permanent table. 

CREATE
    [DEFINER = user]
    TRIGGER [IF NOT EXISTS] trigger_name
    trigger_time trigger_event
    ON tbl_name FOR EACH ROW
    [trigger_order]
    trigger_body

trigger_time: { BEFORE | AFTER }

trigger_event: { INSERT | UPDATE | DELETE }

trigger_order: { FOLLOWS | PRECEDES } other_trigger_name

This statement drops a trigger. The schema (database) name is optional. If the schema is omitted, the trigger is dropped from the default schema. 

DROP TRIGGER [IF EXISTS] [schema_name.]trigger_name

**Comment by chenzhenxxx** [comment]
I will try to finish it.

**Comment by chenzhenxxx** [comment]
Is there a document or demo?

**Comment by JiangZhu-N** [comment]
I will try to finish it.

**Comment by yanyanran** [comment]
Hi! Please assign it to me
