### ISSUE TITLE
[Feature Request]: TRUNCATE TABLE and KILL Statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5189]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

TRUNCATE TABLE empties a table completely. Logically, TRUNCATE TABLE is similar to a DELETE statement that deletes all rows, or a sequence of DROP TABLE and CREATE TABLE statements.

TRUNCATE [TABLE] tbl_name

Each connection to mysqld runs in a separate thread. You can kill a thread with the KILL processlist_id statement.

KILL [CONNECTION | QUERY] processlist_id

**Comment by taofengliu** [comment]
How to participate in MatrixCamp?

**Comment by domingozhang** [comment]
> How to participate in MatrixCamp?

@taofengliu In preparation, focus on matrixorigin commuinty, such as WeCom group or Wechat official account ,please.

**Comment by gueFDF** [comment]
I will try to get it done.

**Comment by yanyanran** [comment]
I will try to get it done.
