### ISSUE TITLE
[Bug]: The function TO_DATE(str, format) cannot be used

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5204]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The SQL statement is : 
SELECT TO_DATE('2022-01-06 10:20:30','%Y-%m-%d %H:%i:%s') as result;
SELECT TO_DATE('2022-01-06','%Y-%m-%d') as result;

**Comment by qingxinhome** [comment]
The implementation of To_Date() function has been reconstructed. To_DATE and STR_TO_DATE is a synonym, The second parameter of the STR_TO_DATE (str, format) function is limited to a string constant. @goodMan-code @daviszhen @domingozhang

**Comment by goodMan-code** [comment]
Recheck it, done, can be closed.   commit ccfcd648ea670d1bbb62c6cf8967e16fb7cc2a4d
