### ISSUE TITLE
[Bug]: in mo_catalog, you can create table, but you can not drop the table

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#5211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):head
- Hardware parameters:mac pro
- OS type:mac 
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/60595215/191739755-4a47d0e3-8b7c-4c85-8272-a0160b3f5a8e.png)

### Expected Behavior

the table b will be dropped.

**Comment by iamlinjunhong** [comment]
@daviszhen  close this issue, both create and drop can not execute in mo_catalog
