### ISSUE TITLE
[Bug]: insert empty cause mo-server service crash.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5242]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1076" alt="截屏2022-09-26 11 41 43" src="https://user-images.githubusercontent.com/39303074/192189608-ef14d12b-7270-4100-9062-73825669ba01.png">

mo.log：
[mo.log](https://github.com/matrixorigin/matrixone/files/9642772/mo.log)

**Comment by tianyahui-python** [comment]
All sets the type(int type, varchar type ...etc) of primary key, insert empty cause mo-server service crash.

**Comment by badboynt1** [comment]
can not reproduce in latest version
