### ISSUE TITLE
[Bug]: index out of range [0] with length 0 during hash_value()

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5268]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select hash_value(12312);
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0: goroutine 81 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.ConvertPanicError({0x21f0660?, 0xc005c9e0d8})
	/root/matrixone/pkg/common/moerr/error.go:410 +0x65
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/root/matrixone/pkg/frontend/mysql_cmd_executor.go:2399 +0xdc
panic({0x21f0660, 0xc005c9e0d8})
	/us

When parameter is a column of a table, it is normal.
mysql> select hash_value(a),hash_value(b) from t1;
+----------------------+----------------------+
| hash_value(a)        | hash_value(b)        |
+----------------------+----------------------+
| 15391714062359731537 | 13899291911896986166 |
+----------------------+----------------------+
1 row in set (0.00 sec)

**Comment by dongdongyang33** [comment]
Vector stores values in both Col[] and data[], while const vector stores value in Col[] only
so it panic when trying to get the pointer from the nil data[]

**Comment by domingozhang** [comment]
fixed
