### ISSUE TITLE
[Bug]: User can create table in mo_catalog

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5275]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> use mo_catalog;

mysql> create table mo_test(a int,b text);
Query OK, 0 rows affected (0.05 sec)

mysql> show tables;
+----------------------+
| tables_in_mo_catalog |
+----------------------+
| mo_database          |
| mo_tables            |
| mo_columns           |
| mo_user              |
| mo_account           |
| mo_role              |
| mo_user_grant        |
| mo_role_grant        |
| mo_role_privs        |
| mo_test              |
+----------------------+
10 rows in set (0.04 sec)

**Comment by aressu1985** [comment]
fixed: fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

mysql> usre mo_catalog;
ERROR 20303 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 4 near "usre mo_catalog";
mysql> use mo_catalog;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> create table mo_test(a int,b text);
ERROR 20101 (HY000): internal error: do not have privilege to execute the statement
