### ISSUE TITLE
[Bug]: grant prvis to moadmin, table mo_role_privs can be updated

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5277]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

grant show tables,create table,drop table on database * to moadmin;
select * from mo_catalog.mo_role_privs where role_name='moadmin';
![image](https://user-images.githubusercontent.com/113406637/192459705-18223b73-0dcd-47de-be82-11bb2949492f.png)
![image](https://user-images.githubusercontent.com/113406637/192459733-123a264c-d657-403d-b54c-a93a95cc844b.png)

**Comment by daviszhen** [comment]
it was fixed. now, we can not grant privileges to the moadmin
