### ISSUE TITLE
[Bug]: grant ownership on database * to role error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5279]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/192462472-00b7139b-b9ad-467c-9528-5b6128133908.png)

**Comment by daviszhen** [comment]
same as #5253

**Comment by heni02** [comment]
same issue close
