### ISSUE TITLE
[Bug]: TIMESTAMP, panic info occurs when update it

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5289]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The Structure is : 
CREATE TABLE t1(
    id BIGINT UNSIGNED,
    curr_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    curr_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE TABLE t2(
    id BIGINT UNSIGNED,
    curr_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    curr_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

The DML statement is : 
INSERT INTO t1(id) VALUES (1);
INSERT INTO t1(id) VALUES (2);
INSERT INTO t2(id) VALUES (1);
INSERT INTO t2(id) VALUES (3);

When I update it : 
UPDATE t1 JOIN t2 ON t1.id = t2.id SET t1.curr_dt = '2022-07-01 08:08:08';

The result is : 
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 258 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/matrixorigin/matrixone/pkg/common/moerr.ConvertPanicError({0x203b840?, 0x3663420})
	/home/mo/matrixone/pkg/common/moerr/error.go:410 +0x65
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1()
	/home/mo/matrixone/pkg/frontend/mysql_cmd_executor.go:2410 +0xdc
panic({0x203b840, 0x36

**Comment by goodMan-code** [comment]
The same problem is : UPDATE t1,t2 SET t1.curr_dt = '2022-07-01 08:08:08', t2.curr_dt = '2022-06-01 08:08:08';

**Comment by badboynt1** [comment]
can not reproduce in new version
