### ISSUE TITLE
[Bug]: revoke not exists privs,role error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5290]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
![image](https://user-images.githubusercontent.com/113406637/192516998-53e1ae9a-39a3-4a34-bc38-99c518a2fda9.png)
revoke_role_3 don't have create role,drop role privs
![image](https://user-images.githubusercontent.com/113406637/192517026-a9ce7d64-9938-4e56-b96f-456b7764d760.png)

**Comment by daviszhen** [comment]
It was fixed at #5411.

the behavior of `revoke all on account * from revoke_role_1;` is same as design.

Now,
mysql> revoke create role,drop role on account * from revoke_role_1,revoke_role_3;
ERROR 20101 (HY000): internal error: there is no role revoke_role_3
