### ISSUE TITLE
[Bug]:drop role which grant role to role , mo_role table record not deleted

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5301]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
create role drop_role_1,drop_role_2;
create user drop_user_1 identified by '111',drop_user_2 identified by '111';
grant all on table *.* to drop_role_1 with grant option;
grant drop_role_1 to drop_user_1;
grant drop_role_2 to drop_user_2;
select role_name from mo_role where role_name in ('drop_role_1','drop_role_2');
grant drop_role_1 to drop_role_2;
drop role drop_role_1;
mo_role drop_role_2 not deleted
![image](https://user-images.githubusercontent.com/113406637/192685900-3e1d0336-b80a-463b-b59e-8f7016e4392f.png)
mo_user_grant drop_role_2 user_id not deleted
![image](https://user-images.githubusercontent.com/113406637/192704789-aa94b6db-2275-4986-8456-ffc8b5151f08.png)

**Comment by daviszhen** [comment]
It is not a bug, i think.

**Comment by heni02** [comment]
confirm ,closed
