### ISSUE TITLE
[Bug]: TIMESTAMP should be 0 when it's para is '19.70102'

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5309]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The SQL statement is : 
SELECT UNIX_TIMESTAMP('19.70102');

The result is : 
+--------------------------+
| unix_timestamp(19.70102) |
+--------------------------+
|              78166656000 |
+--------------------------+

However, when I execute this stmt : 
SELECT FROM_UNIXTIME(78166656000);

The result is : 
+----------------------------+
| from_unixtime(78166656000) |
+----------------------------+
| NULL                       |
+----------------------------+

The function UNIX_TIMESTAMP() should return 0 (null?) directly.

**Comment by goodMan-code** [comment]
Same problem is : SELECT UNIX_TIMESTAMP('990101xt120000');  This SQL stmt's result is : 250279819200

**Comment by badboynt1** [comment]
can not reproduce in latest version
