### ISSUE TITLE
[Bug]: Load data failed ,restart mo server exception

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#5310]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d0671ab6ff81e88d7a05400f7d130197e0d61d18
- Hardware parameters: linux 
- OS type:centos 7.9
- Others:
```

### Actual Behavior

```
restart mo-server success
```

### Expected Behavior

restart mo-server failed

**Comment by yingfeng** [comment]
close due to being lack of further information
