### ISSUE TITLE
[Bug]: #5199 causes particular tpch queries to return empty results

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#5322]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After pr #5199 being merged, q{2,9,11,16,20} of tpch(1G) return empty results on my Ryzen 5900X + 32G memory desktop.

**Comment by aressu1985** [comment]
@m-schen pls update status

**Comment by aunjgr** [comment]
Can't reproduce this issue now. Should close.
