### ISSUE TITLE
[Bug]: bug related to handling data startswith `0x` 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5346]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="781" alt="image" src="https://user-images.githubusercontent.com/77312370/192950219-99233bcd-b63e-465e-b06f-8c190135d6f4.png">

### Expected Behavior

Expect the same behavior as MySQL:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/77312370/192951358-fb94a4be-2dce-4e82-b2af-f938da4e87da.png">

### Steps to Reproduce

```Markdown
select hex( 0x01020304FFFFFFFF0000000CAACB0000);
create table test(a blob);
insert into test values( 0x01020304FFFFFFFF0000000CAACB0000);
select * from test;

```
```


### Additional information

if you want to test blob type, better to use this forked branch: https://github.com/nnsgmsone/matrixone/tree/blob

**Comment by domingozhang** [comment]
The inserted 0x values can be displayed now.

mysql> insert into t1 values(0x123456789);
Query OK, 1 row affected (0.01 sec)

mysql> select * from t1;
+--------------+
| a            |
+--------------+
| 0x0123456789 |
+--------------+
1 row in set (0.01 sec)

**Comment by JackTan25** [comment]
> 

please close this one
