### ISSUE TITLE
[Bug]: When you delete, you need to get the primary key information

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#5351]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

no primary key information

**Comment by ouyuanning** [comment]
get row_id now
