### ISSUE TITLE
[Bug]: Unexpected row merging when using UNION ALL

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5370]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Structure is : 
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
CREATE TABLE t1(
    id INT NOT NULL,
    name CHAR(20) NOT NULL,
    sex CHAR(4) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE t2(
    id VARCHAR(10) NOT NULL,
    name VARCHAR(20) NOT NULL,
    nation VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);

DML is : 
INSERT INTO t1() VALUES(1,'ronaldo','F'), (2,'kante','M'), (3,'noyer','F'),(4,'modrici','M');
INSERT INTO t2() VALUES(1,'ronaldo','American'), (2,'kante','Franch'), (3,'noyer','Germany'),(4,'modrici','UK');

SQL stmt is : 
(SELECT * FROM t1 WHERE id BETWEEN 1 AND 2 ORDER BY name)
UNION ALL
(SELECT * FROM t2 WHERE nation BETWEEN 'A' AND 'F' ORDER BY id DESC);

result on MO is : 
+------+---------+----------+
| id   | name    | sex      |
+------+---------+----------+
|    1 | ronaldo | F        |
|    1 | ronaldo | American |
+------+---------+----------+

result on MySQL is : 
+----+---------+----------+
| id | name    | sex      |
+----+---------+----------+
| 1  | ronaldo | F        |
| 2  | kante   | M        |
| 1  | ronaldo | American |
+----+---------+----------+

**Comment by nnsgmsone** [comment]
This looks like the problem of  `between and`

**Comment by goodMan-code** [comment]
We think it may be a primary key deduplication on the temporary table, for reference only

**Comment by dongdongyang33** [comment]
> This looks like the problem of `between and`

result of `SELECT * FROM t2 WHERE nation BETWEEN 'A' AND 'F' ORDER BY id DESC` is correct.
let me check.

**Comment by goodMan-code** [comment]
BVT tag has not remove, remote it pls. 
files location : /test/cases/dml/select/order_by_with_nulls.sql，line 158 -- 162
