### ISSUE TITLE
[Bug]: endswith() function bug.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5398]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="560" alt="截屏2022-10-05 18 55 33" src="https://user-images.githubusercontent.com/39303074/194045590-0c82da6d-ffdb-4f8d-ba6a-4ef0f734c3d7.png">

**Comment by qingxinhome** [comment]
The bug of the system function endsmith has been fixed, and the bvt test and unit test have passed. Please know. @tianyahui-python
