### ISSUE TITLE
[Bug]: set uuid() function default value, desc table error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5400]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="640" alt="截屏2022-10-05 21 10 03_副本" src="https://user-images.githubusercontent.com/39303074/194071028-505efc3c-639c-444c-a5ba-5455093f2bd1.png">

**Comment by qingxinhome** [comment]
As for the requirement of using functions as default values in the describe table structure, different types of mysq have different expressions and restrictions. It is recommended to investigate and treat them as featurs. @tianyahui-python @domingozhang

**Comment by tianyahui-python** [comment]
<img width="845" alt="截屏2022-10-28 10 42 20" src="https://user-images.githubusercontent.com/39303074/198476097-bcade134-9ba9-4db1-b7d0-dcee3edd5bf6.png">
