### ISSUE TITLE
[Bug]: CompositePrimaryKey not supported text type

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5401]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create  table  cpk_table_2(col1 tinyint,col2 smallint,col3 int,col4 bigint,col5 tinyint unsigned,col6 smallint unsigned,col7 int unsigned,col8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255),primary key(col1,col12,col17));
![image](https://user-images.githubusercontent.com/113406637/194208163-a307e7d8-87a1-4f22-b406-2910bdf86e0b.png)

**Comment by bbbearxyz** [comment]
text type don't support text https://github.com/matrixorigin/matrixone/issues/3602, so you need to close this issue
