### ISSUE TITLE
[Bug]: minus, prepare execute error

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5403]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t8 (
a int primary key,
b int
);

insert into t8 values (1,5),(2,4),(3,3);
set @a=1;

prepare s1 from '(select a from t8 where a>?) minus (select b from t8 where b>?)';

execute s1 using @a;

<img width="944" alt="截屏2022-10-06 15 32 34" src="https://user-images.githubusercontent.com/39303074/194245416-a040347d-be71-4f48-8cd2-5ab5a8bc94b1.png">

<img width="1209" alt="截屏2022-10-06 15 32 18" src="https://user-images.githubusercontent.com/39303074/194245382-6b879fcd-00ce-446f-a59c-c1a328a72c45.png">

**Comment by tianyahui-python** [comment]
<img width="998" alt="截屏2022-10-06 12 18 03" src="https://user-images.githubusercontent.com/39303074/194213146-3888d6d4-f21e-4bd5-8760-2f275dd2fa53.png">

**Comment by ouyuanning** [comment]
same bug as #5407

**Comment by tianyahui-python** [comment]
bvt tag no remove.

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.
