### ISSUE TITLE
[Bug]: ddl include CompositePrimaryKey load data internal error: panic runtime error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5405]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql：create table cpk_table_1000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255),primary key(col3, col19));
load data infile '/Users/heni/test_data/10000000_20_columns_load_data.csv' into table cpk_table_1000w fields terminated by ',' enclosed by '/"';
![image](https://user-images.githubusercontent.com/113406637/194226996-b1d86af8-0ac3-4d12-ac58-eadbee931106.png)
only four records data also error
![image](https://user-images.githubusercontent.com/113406637/194227334-dcff2c0a-f29f-4ebf-8cc5-0a1fdd967eff.png)

**Comment by bbbearxyz** [comment]
this problem, I need one line about 10000000_20_columns_load_data

**Comment by bbbearxyz** [comment]
the issue is same as issue #5464
