### ISSUE TITLE
[Bug]: minus, precision processing problem.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5406]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
drop table if exists t2;
create table t2(
col1 date,
col2 datetime,
col3 timestamp
);

insert into t2 values ();
insert into t2 values('2022-01-01', '2022-01-01', '2022-01-01');
insert into t2 values('2022-01-01', '2022-01-01 00:00:00', '2022-01-01 00:00:00.000000');
insert into t2 values('2022-01-01', '2022-01-01 00:00:00.000000', '2022-01-01 23:59:59.999999');
select * from t2;

<img width="933" alt="截屏2022-10-06 11 57 56" src="https://user-images.githubusercontent.com/39303074/194246862-a8607688-72c2-4e9b-b527-93b38210da50.png">
<img width="998" alt="截屏2022-10-06 12 18 03" src="https://user-images.githubusercontent.com/39303074/194246883-98b285a7-5d38-465a-bfdb-5b4038e4ab32.png">

**Comment by ouyuanning** [comment]
@YANGGMM need some discuss before fixed.

**Comment by domingozhang** [comment]
As discussed, the precision needs to be converted to higher one in column minus

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
bvt tag no remove.

**Comment by tianyahui-python** [comment]
drop table if exists t2;
create table t2(
col1 date,
col2 datetime,
col3 timestamp
);

insert into t2 values ();
insert into t2 values('2022-01-01', '2022-01-01', '2022-01-01');
insert into t2 values('2022-01-01', '2022-01-01 00:00:00', '2022-01-01 00:00:00.000000');
insert into t2 values('2022-01-01', '2022-01-01 00:00:00.000000', '2022-01-01 23:59:59.999999');
select * from t2;



>(select col3 from t2) minus (select col2 from t2 limit 0);
>(select col1 from t2) minus (select col2 from t2 limit 0);
> unsolved.

**Comment by tianyahui-python** [comment]
mysql> drop table if exists t2;
Query OK, 0 rows affected (0.15 sec)

mysql> create table t2(
    -> col1 date,
    -> col2 datetime,
    -> col3 timestamp
    -> );
Query OK, 0 rows affected (0.09 sec)

mysql> 
mysql> insert into t2 values ();
Query OK, 1 row affected (0.12 sec)

mysql> insert into t2 values('2022-01-01', '2022-01-01', '2022-01-01');
Query OK, 1 row affected (0.11 sec)

mysql> insert into t2 values('2022-01-01', '2022-01-01 00:00:00', '2022-01-01 00:00:00.000000');
Query OK, 1 row affected (0.22 sec)

mysql> insert into t2 values('2022-01-01', '2022-01-01 00:00:00.000000', '2022-01-01 23:59:59.999999');
Query OK, 1 row affected (0.16 sec)

mysql> select * from t2;
+------------+---------------------+---------------------+
| col1       | col2                | col3                |
+------------+---------------------+---------------------+
| NULL       | NULL                | NULL                |
| 2022-01-01 | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2022-01-01 | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2022-01-01 | 2022-01-01 00:00:00 | 2022-01-02 00:00:00 |
+------------+---------------------+---------------------+
4 rows in set (0.01 sec)

mysql> (select col1 from t2) minus (select col2 from t2 limit 0);
+---------------------+
| col1                |
+---------------------+
| NULL                |
| 2022-01-01 00:00:00 |
+---------------------+
2 rows in set (0.01 sec)

mysql> (select col1 from t2) minus (select col2 from t2 limit 1);
+---------------------+
| col1                |
+---------------------+
| 2022-01-01 00:00:00 |
+---------------------+
1 row in set (0.05 sec)

mysql> (select col1 from t2) minus (select col2 from t2 limit 2);
Empty set (0.01 sec)

mysql> (select col1 from t2) minus (select col2 from t2 limit 10);
Empty set (0.01 sec)

mysql> (select col1 from t2) minus (select col3 from t2 limit 0);
+---------------------+
| col1                |
+---------------------+
| NULL                |
| 2022-01-01 00:00:00 |
+---------------------+
2 rows in set (0.01 sec)

mysql> (select col1 from t2) minus (select col1 from t2 limit 0);
+------------+
| col1       |
+------------+
| NULL       |
| 2022-01-01 |
+------------+
2 rows in set (0.02 sec)

mysql> (select col3 from t2) minus (select col1 from t2 limit 0);
+---------------------+
| col3                |
+---------------------+
| NULL                |
| 2022-01-01 00:00:00 |
| 2022-01-02 00:00:00 |
+---------------------+
3 rows in set (0.04 sec)

mysql> (select col3 from t2) minus (select col2 from t2 limit 0);
+---------------------+
| col3                |
+---------------------+
| NULL                |
| 2022-01-01 00:00:00 |
| 2022-01-02 00:00:00 |
+---------------------+
3 rows in set (0.01 sec)

mysql> (select col3 from t2) minus (select col3 from t2 limit 0);
+---------------------+
| col3                |
+---------------------+
| NULL                |
| 2022-01-01 00:00:00 |
| 2022-01-02 00:00:00 |
+---------------------+
3 rows in set (0.03 sec)

mysql>
