### ISSUE TITLE
[Bug]: prepare, Incorrect number of execution parameters should be reported.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5407]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t8;
create table t8 (
a int primary key,
b int
);

insert into t8 values (1,5),(2,4),(3,3);
set @a=1;

prepare s2 from '(select a from t8 where a>?)';

execute s2 using @a, @a;

<img width="444" alt="截屏2022-10-06 15 49 25" src="https://user-images.githubusercontent.com/39303074/194248650-2385d2ad-cd4d-41c4-93ba-ff657d647604.png">

### Expected Behavior

<img width="814" alt="截屏2022-10-06 15 50 19" src="https://user-images.githubusercontent.com/39303074/194248901-bc67a4c2-49a6-4f05-b1f7-45ffa5083e0a.png">

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.
