### ISSUE TITLE
[Bug]: insert into values '' to CompositePrimaryKey no error reported

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5408]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/194242792-18d07143-99bc-4877-a4c8-6c60a1a3f3af.png)

### Steps to Reproduce

```Markdown
create table cpk_table_21(col1 int,col2 varchar(255),col3 timestamp, col4 double,col5 date,primary key(col1, col2,col5));
insert into cpk_table_21 values (3,'','2019-02-10 00:00:00',78.90,'2001-07-10');
```

**Comment by bbbearxyz** [comment]
i test this problem in mysql, mysql don't allow this, so I don't think this is a bug.

**Comment by heni02** [comment]
confirm,closed
![image](https://user-images.githubusercontent.com/113406637/196844976-b79a6ffe-0e1f-40fd-a16e-ed444931fffe.png)
