### ISSUE TITLE
[Bug]: create user daisy@192.168.1.10 identified by '123456';

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#5413]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dd2690603be6bbae10dc796a39ca08c673cbea2b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create user daisy@192.168.1.10 identified by '123456';

mo_user:

|      14 | localhost    | daisy@192.168.1.10 | 123456 

### Expected Behavior

userName: daisy
HostName: 192.168.1.10

**Comment by daviszhen** [comment]
it was fixed at #5869

**Comment by heni02** [comment]
confirm,closed
![image](https://user-images.githubusercontent.com/113406637/197668776-ee4030a9-9c39-4239-83a5-6f654d49b20e.png)

**Comment by aressu1985** [comment]
fixed
