### ISSUE TITLE
[Bug]: update table set ....., emergence of instability bug.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5428]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="830" alt="截屏2022-10-07 23 28 13" src="https://user-images.githubusercontent.com/39303074/194591800-d9628082-47ff-41c0-8c31-e6df36d206a2.png">

<img width="1337" alt="截屏2022-10-07 23 09 47" src="https://user-images.githubusercontent.com/39303074/194591822-625a0def-63d9-4225-9d65-8a8571710e6c.png">

**Comment by tianyahui-python** [comment]
mo.log： 
[mo-new.log.tar.gz](https://github.com/matrixorigin/matrixone/files/9735239/mo-new.log.tar.gz)

**Comment by tianyahui-python** [comment]
> A second encounter

mysql> select * from t1;
+--------------------------------------+------+
| a                                    | b    |
+--------------------------------------+------+
| dce48b34-4653-11ed-940e-f6efd850eccd |    1 |
| ddeb329e-4653-11ed-940e-f6efd850eccd |    2 |
| deec3a94-4653-11ed-940e-f6efd850eccd |    3 |
+--------------------------------------+------+
3 rows in set (0.01 sec)

mysql> 
mysql> 
mysql> 
mysql> create table t2(col1 uuid primary key, col2 int);
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t2 values(uuid(),1);
Query OK, 1 row affected (0.03 sec)

mysql> insert into t2 values(uuid(),0);
Query OK, 1 row affected (0.03 sec)

mysql> insert into t2 values(uuid(),10);
Query OK, 1 row affected (0.01 sec)

mysql> select * from t2;
+--------------------------------------+------+
| col1                                 | col2 |
+--------------------------------------+------+
| a3b23830-4657-11ed-940e-f6efd850eccd |    1 |
| a59e5552-4657-11ed-940e-f6efd850eccd |    0 |
| a6d6aa5a-4657-11ed-940e-f6efd850eccd |   10 |
+--------------------------------------+------+
3 rows in set (0.01 sec)

mysql> select a from t1 union select col1 from t2;
ERROR 20303 (HY000): SQL parser error: the 0 column cann't cast to a same type
mysql> 
mysql> (select a from t1) union (select col1 from t2);
ERROR 20303 (HY000): SQL parser error: the 0 column cann't cast to a same type
mysql> 
mysql> (select a from t1);
+--------------------------------------+
| a                                    |
+--------------------------------------+
| dce48b34-4653-11ed-940e-f6efd850eccd |
| ddeb329e-4653-11ed-940e-f6efd850eccd |
| deec3a94-4653-11ed-940e-f6efd850eccd |
+--------------------------------------+
3 rows in set (0.17 sec)

mysql> (select col1 from t2);
+--------------------------------------+
| col1                                 |
+--------------------------------------+
| a3b23830-4657-11ed-940e-f6efd850eccd |
| a59e5552-4657-11ed-940e-f6efd850eccd |
| a6d6aa5a-4657-11ed-940e-f6efd850eccd |
+--------------------------------------+
3 rows in set (0.01 sec)

mysql> update t2 set col2=-1 where col1='a59e5552-4657-11ed-940e-f6efd850eccd';
ERROR 20101 (HY000): internal error: panic unsupported type: 
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/compute.GetOffsetByVal
	/Users/tianyahui/work_code/go/matrixone/pkg/vm/engine/tae/compute/compute.go:251
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).BatchDedup.func1
	/Users/tianyahui/work_code/go/matrixone/pkg/vm/engine/tae/tables/block.go:837
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).forEachWindowWithBias
	/Users/tianyahui/work_code/go/matrixone/pkg
mysql>

**Comment by tianyahui-python** [comment]
[mo-new.log.tar.gz](https://github.com/matrixorigin/matrixone/files/9735408/mo-new.log.tar.gz)

**Comment by tianyahui-python** [comment]
mysql> select * from t2;
+--------------------------------------+------+
| col1                                 | col2 |
+--------------------------------------+------+
| a3b23830-4657-11ed-940e-f6efd850eccd |    1 |
| a59e5552-4657-11ed-940e-f6efd850eccd |    0 |
| a6d6aa5a-4657-11ed-940e-f6efd850eccd |   10 |
+--------------------------------------+------+
3 rows in set (0.01 sec)

mysql> delete from t2 where col1='a59e5552-4657-11ed-940e-f6efd850eccd';
ERROR 20101 (HY000): internal error: panic unsupported type: 
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/compute.GetOffsetByVal
	/Users/tianyahui/work_code/go/matrixone/pkg/vm/engine/tae/compute/compute.go:251
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).blkGetByFilter
	/Users/tianyahui/work_code/go/matrixone/pkg/vm/engine/tae/tables/block.go:718
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*dataBlock).GetByFilter
	/Users/tianyahui/work_code/go/matrixone/pkg/vm/engine/tae/tabl

**Comment by qingxinhome** [comment]
update t1 set b = 10 where a = '86fc24d5-540d-11ed-bfdf-000c29847904';

**Comment by qingxinhome** [comment]
update t1 set b = 10 where a = '86fc24d5-540d-11ed-bfdf-000c29847904';
The update statement follows the new column according to the uuid. No problem.

**Comment by qingxinhome** [comment]
This problem has been solved, please verify. @tianyahui-python
