### ISSUE TITLE
[Bug]: select a from t1 order by a; emergence of instability bug;

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#5429]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="698" alt="截屏2022-10-07 23 37 26" src="https://user-images.githubusercontent.com/39303074/194593953-cb2bd8b1-6cd6-43f2-9407-2b37501edfa1.png">

<img width="975" alt="截屏2022-10-07 23 38 04" src="https://user-images.githubusercontent.com/39303074/194593973-d74e9a63-8c3d-4d19-902e-7c345295f4ed.png">

<img width="975" alt="截屏2022-10-07 23 38 04" src="https://user-images.githubusercontent.com/39303074/194593987-d305569f-c2b1-42b5-9087-b367b694ec90.png">

<img width="757" alt="截屏2022-10-07 23 39 44" src="https://user-images.githubusercontent.com/39303074/194594059-5bc40492-e8f2-4dc5-b70e-749caf649032.png">

<img width="699" alt="截屏2022-10-07 23 40 02" src="https://user-images.githubusercontent.com/39303074/194594072-27c35a1b-1faf-4598-8331-cfabdc6e9d29.png">

<img width="1365" alt="截屏2022-10-07 23 40 26" src="https://user-images.githubusercontent.com/39303074/194594084-810e35de-52f7-4732-a4d8-a5a344f5c8ce.png">

**Comment by tianyahui-python** [comment]
[mo-new.log.tar.gz](https://github.com/matrixorigin/matrixone/files/9735307/mo-new.log.tar.gz)

**Comment by qingxinhome** [comment]
This problem has been solved, please verify. @tianyahui-python
