### ISSUE TITLE
[Bug]: HeidiSQL problem

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#5439]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/4965857/194685633-c2f8c31c-f46b-4873-96c6-419b8a665ff5.png)

**Comment by aressu1985** [comment]
mysql> show full columns from mo_catalog.mo_user;
+-----------------------+-----------+-----------+------+------+---------+-------+---------------------------------+---------+
| Field                 | Type      | Collation | Null | Key  | Default | Extra | Privileges                      | Comment |
+-----------------------+-----------+-----------+------+------+---------+-------+---------------------------------+---------+
| user_id               | INT       | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| user_host             | VARCHAR   | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| user_name             | VARCHAR   | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| authentication_string | VARCHAR   | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| status                | VARCHAR   | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| created_time          | TIMESTAMP | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| expired_time          | TIMESTAMP | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| login_type            | VARCHAR   | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| creator               | INT       | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| owner                 | INT       | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
| default_role          | INT       | NULL      | YES  |      | NULL    |       | select,insert,update,references |         |
+-----------------------+-----------+-----------+------+------+---------+-------+---------------------------------+---------+
11 rows in set (0.01 sec)

mysql>
