### ISSUE TITLE
[Bug]: Error is reported when reading the normal range values of timestamp and datetime in the external table. Values beyond the range can be read

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5442]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.Error is reported when reading the normal range values of timestamp and datetime in the external table.
![image](https://user-images.githubusercontent.com/113406637/194686547-e7a970df-a712-41af-94bd-f728a9e4481f.png)

2.Values beyond the range can be read
![image](https://user-images.githubusercontent.com/113406637/194686557-70b10f2c-d66a-4045-a635-b287f872c93e.png)

### Steps to Reproduce

```Markdown
create external table ex_table_3(char_1 char(20),char_2 varchar(10),date_1 date,date_2 datetime,date_3 timestamp)infile{"filepath"='/Users/heni/test_data/ex_table_char.csv'} fields terminated by ',' enclosed by '\"' lines terminated by '\n';

ex_table_char.csv：
"cat","yellow 芝士","2020-10-09","0001-01-01 00:00:00.000000","1970-01-01 00:00:01.0000"
"123木头人","zt@126.com","1000-01-01","9999-12-31 23:59:59.999999","2038-01-19 03:14:07.999999"
"abc$%*()#$","ttttt","9999-12-31","2019-10-23 23:00:08.9083","2030-01-01 03:14:07.999999"

create external table ex_table_3_4(char_1 char(20),char_2 varchar(10),date_1 date,date_2 datetime,date_3 timestamp)infile{"filepath"='/Users/heni/test_data/ex_table_3_4.csv'} fields terminated by ',' enclosed by '\"' lines terminated by '\n';

ex_table_3_4.csv：
"45","yellow 芝士","2020-10-09","0001-01-01 00:00:00.000000","2038-01-20 03:14:07.999999"
```

**Comment by heni02** [comment]
@bbbearxyz insert into values is correct, but reading external tables error
![image](https://user-images.githubusercontent.com/113406637/198870520-07ac3048-4d4c-4533-b3c3-d8a325784043.png)

**Comment by badboynt1** [comment]
confirmed with @domingozhang in https://github.com/matrixorigin/matrixone/issues/5305 , 
In mysql, With a single argument, timestamp function returns the date or datetime expression expr as a datetime value, so range check is removed to keep mo behaves like mysql

**Comment by bbbearxyz** [comment]
now #6245 support timestamp range check

**Comment by fengttt** [comment]
Not a bug.   Our data type has wider range, which is a good thing.

**Comment by bbbearxyz** [comment]
now @fengttt think date/datetime/timestamp is from 0001 to 9999 is ok

**Comment by heni02** [comment]
ok, i need to alter cases

**Comment by heni02** [comment]
confirm, question 1 now correct
<img width="1020" alt="企业微信截图_8e9e4851-e21c-40e7-966e-941d9efeedc0" src="https://user-images.githubusercontent.com/113406637/199954717-a89cf7f5-7ebf-4099-942c-787145b9a63d.png">

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
