### ISSUE TITLE
[Bug]: The key partition is a multi column error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5466]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1239" alt="企业微信截图_16652789109587" src="https://user-images.githubusercontent.com/113406637/194736268-5f9613c9-cc1a-4d9d-8d19-d6b5778d7a42.png">

### Steps to Reproduce
create table pt_table_25(col1 tinyint,col2 smallint,col3 int,clo4 bigint,col5 tinyint unsigned,col6 smallint unsigned,col7 int unsigned,col8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 text)partition by key(col2,col6,col18,col13,co19)partitions 100;
_No response_

**Comment by qingxinhome** [comment]
The sql case has syntax errors. It is confirmed that there are no bugs. It is recommended to close. @heni02

**Comment by heni02** [comment]
confirm,closed
![image](https://user-images.githubusercontent.com/113406637/197145519-7dcef49f-f5cf-4bd2-963e-7f205fec326e.png)
