### ISSUE TITLE
[Bug]: tae data: duplicate when run batch insert through prepared stmt many times

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5508]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022/10/10 15:26:38.687181 +0800 ERROR frontend/mysql_cmd_executor.go:2427 tae data: duplicate
2022/10/10 15:26:38.690020 +0800 ERROR frontend/util.go:454 Connection id: 1031 Status: fail Statement: insert into item (i_id, i_name, i_price, i_data, i_im_id) values (?, ?, ?, ?, ?) Error: tae data: duplicate
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:454
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:446
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2436
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2559
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:125

Whatever benchmarkSQL or benchBase, when load tpcc data into mo, the mo will return tae data: duplicate,
and all data is well-formed,  I have test with same tables without pk, it is ok, and all the data record in tables is unique
but for tables with muti pk, mo report tae data: duplicate

**Comment by bbbearxyz** [comment]
pair with Su Dong, now this is not problem about compisite primary key.
