### ISSUE TITLE
[Bug]: All show statements should add the limits of account, user, role, otherwise the output table may not be correct.

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#5534]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

return system table

**Comment by daviszhen** [comment]
it is not a bug.

**Comment by sukki37** [comment]
@nnsgmsone @domingozhang @daviszhen pls record a result and update the status of this issue, thank you.

**Comment by daviszhen** [comment]
It only has already known problems introduced by pr #5824 @nnsgmsone 
the database **system** of general account has the extra views or tables from **sys** account:
- rawlog           
- log_info         
- error_info       
- span_info        
- statement_info   

the database **system_metrics** of general account has the extra views or tables from **sys** account :
- views started by **process_**, **sys_**

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
in progress

**Comment by dongdongyang33** [comment]
add account limit for 
* `show databases`
* `show table`
* `show table status`
* `show index`
* `show columns`

**Comment by heni02** [comment]
working on tomorrow

**Comment by heni02** [comment]
confirm,closed
commit id:f78df23895c59bbe3f662ecbf5f5ae9d590bac03
sys and non sys account show commad results:
show databases
<img width="386" alt="企业微信截图_2f65229b-ce21-45a8-b345-44b2c8e3b14c" src="https://user-images.githubusercontent.com/113406637/209455381-de826444-0dfe-4c2f-bbb2-f8f2ffaf136b.png">
<img width="335" alt="企业微信截图_de70e5c3-1128-43df-94f8-88fe8d0a1fdd" src="https://user-images.githubusercontent.com/113406637/209455387-5248a3bf-64d0-499a-a625-d9a3f6745532.png">
show tables
<img width="348" alt="企业微信截图_16d309bf-7181-4e63-ab99-53ef0f1165ab" src="https://user-images.githubusercontent.com/113406637/209455502-6dc00100-8219-4a9c-9d66-43d1897ef538.png">
<img width="300" alt="企业微信截图_dab3940d-4d60-45b2-ad1c-e6053ab18e07" src="https://user-images.githubusercontent.com/113406637/209455507-aa0537a8-a750-4908-814e-7987b290d4a6.png">
show table status
<img width="999" alt="企业微信截图_fda57823-9838-42ef-b2e3-3827d2042bd9" src="https://user-images.githubusercontent.com/113406637/209455524-69bda5da-3302-4ee6-8fd8-062f55843e27.png">
<img width="1005" alt="企业微信截图_6b9cc686-0ad7-445f-9edc-e2a0fcb97e38" src="https://user-images.githubusercontent.com/113406637/209455532-ac06b77a-ed36-446b-afde-93cf57feb0a4.png">
show index
<img width="1005" alt="企业微信截图_057a53c6-7da8-439b-b9b6-3122e0c7134b" src="https://user-images.githubusercontent.com/113406637/209455561-3586e8eb-6c21-4d46-a16e-06cf61339ebf.png">
<img width="1004" alt="企业微信截图_3cd62c5b-8c5e-418e-930f-741e1b151d66" src="https://user-images.githubusercontent.com/113406637/209455566-5c1ea0ed-6002-454a-8466-f9e57b8a7705.png">
show columns
<img width="612" alt="企业微信截图_44bfda1e-c1d5-493a-adc6-55dd1184eeb6" src="https://user-images.githubusercontent.com/113406637/209455593-a366d73e-6411-4901-abf6-f2b4406bd513.png">
<img width="647" alt="企业微信截图_d039fbe9-ba7e-4cb4-b2fc-d8c5eaf2a5b3" src="https://user-images.githubusercontent.com/113406637/209455597-ec0c6cbc-49d0-4a94-9cc3-83c2d00543c9.png">

**Comment by heni02** [comment]
@dongdongyang33 plz remove bvt tag

**Comment by florashi181** [comment]
@dongdongyang33

**Comment by heni02** [comment]
@aressu1985 plz closed issue
