### ISSUE TITLE
[Bug]: REGEXP_LIKE() : The third parameter can't use correctly

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5537]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The problematic SQL stmt is : 
SELECT REGEXP_LIKE('abc', 'ABC', 'c');

It's return : 
ERROR 20203 (HY000): invalid argument function regexp_like, bad value [VARCHAR VARCHAR VARCHAR]

The result on MySQL : 
+--------------------------------+
| REGEXP_LIKE('abc', 'ABC', 'c') |
+--------------------------------+
|                              0 |
+--------------------------------+

**Comment by domingozhang** [comment]
the third parameter will be supported in future release

**Comment by iceTTTT** [comment]
pr merged

**Comment by aressu1985** [comment]
tracking

**Comment by aressu1985** [comment]
fixed
mysql> SELECT REGEXP_LIKE('abc', 'ABC', 'c');
+--------------------------+
| regexp_like(abc, ABC, c) |
+--------------------------+
| false                    |
+--------------------------+
1 row in set (1.09 sec)
