### ISSUE TITLE
[Subtask]: Tae solves the underlying implementation of truncate

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#5538]
### Parent Issue

#4095

### Detail of Subtask

1. The tae implements truncate without changing the tableid of the table
2. The truncate and drop statements can be executed as separate transactions

**Comment by XuPeng-SH** [comment]
It should be done in 0.7

**Comment by XuPeng-SH** [comment]
move to 0.8

**Comment by XuPeng-SH** [comment]
duplicate with #6602

**Comment by sukki37** [comment]
tracked by #6602
