### ISSUE TITLE
[Bug]: update json type partial not supported

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5551]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/195231448-f444596e-69c0-40eb-86bb-b7f49413a1ad.png)

**Comment by mooleetzi** [comment]
This may be supported in the future. I am not sure which version.

**Comment by sukki37** [comment]
@domingozhang @aressu1985 please take a look at this issue

**Comment by domingozhang** [comment]
In 0.6, only insert and select are implemented. Update will be developed in future.
