### ISSUE TITLE
[Bug]: json_extract Invalid JSON path expression no error reported

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5560]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO：
![image](https://user-images.githubusercontent.com/113406637/195244521-a9729c14-01d9-4784-a512-a6c68a79ed95.png)
mysql：
![image](https://user-images.githubusercontent.com/113406637/195244631-8a8deee4-74f0-4ee2-85a2-27172370ef25.png)

### Steps to Reproduce

```Markdown
select  json_extract('{"a":"a1","b":"b1"}','$.**');
```

**Comment by mooleetzi** [comment]
I need to rewrite jsonPathParser to handle this

**Comment by heni02** [comment]
confirm,closed
![image](https://user-images.githubusercontent.com/113406637/197666506-043ff2cc-9f4d-4870-90a3-b5937047df61.png)
