### ISSUE TITLE
[Bug]: load data to tpcc order_line table error when timestamp value is empty

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5571]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ERROR MESSAGE:
2022/10/12 14:13:00.134536 +0800 ERROR frontend/mysql_cmd_executor.go:2479 internal error: panic runtime error: index out of range [472] with length 472:
runtime.goPanicIndexU
        /usr/local/go/src/runtime/panic.go:119
github.com/matrixorigin/matrixone/pkg/common/bitmap.(*Bitmap).Contains
        /data1/sudong/mo-regression/matrixone/pkg/common/bitmap/bitmap.go:197
github.com/matrixorigin/matrixone/pkg/container/nulls.(*Nulls).Contains
        /data1/sudong/mo-regression/matrixone/pkg/container/nulls/nulls.go:252
github.com/matrixorigin/matrixone/pkg/vectorize/external.ParseTimeStamp
        /data1/sudong/mo-regression/matrixone/pkg/vectorize/external/external.go:351
github.com/matrixorigin/matrixone/pkg/sql/plan/function/builtin/multi.ParseTime[...]
        /data1/sudong/mo-regression/matrixone/pkg/sql/plan/function/builtin/multi/external.go:71
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.GetBatchData
        /data1/sudong/mo-regression/matrixone/pkg/sql/colexec/external/external.go:306
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.ScanFileData
        /data1/sudong/mo-regression/matrixone/pkg/sql/colexec/external/external.go:407
github.com/matrixorigin/matrixone/pkg/sql/colexec/external.Call
        /data1/sudong/mo-regression/matrixone/pkg/sql/colexec/external/external.go:94
github.com/matrixorigin/matrixone/pkg/vm.Run
        /data1/sudong/mo-regression/matrixone/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun
        /data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:100
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:51
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:2479
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest

        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:2557
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:125
2022/10/12 14:13:00.134653 +0800 ERROR frontend/util.go:454 query trace status {"connection_id": 1001, "statement": "load data infile /home/sudong/mo-tpcc/data/order-line.csv into table bmsql_order_line fields terminated by ,", "status": "fail", "error": "internal error: panic runtime error: index out of range [472] with length 472: \nruntime.goPanicIndexU\n\t/usr/local/go/src/runtime/panic.go:119\ngithub.com/matrixorigin/matrixone/pkg/common/bitmap.(*Bitmap).Contains\n\t/data1/sudong/mo-regression/matrixone/pkg/common/bitmap/bitmap.go:197\ngithub.com/matrixorigin/matrixone/pkg/container/nulls.(*Nulls).Contains\n\t/data1/sudong/mo-regression/matrixone/pkg/container/nulls/nulls.go:252\ngithub.com/matrixorigin/matrixone/pkg/vectorize/external.ParseTimeStamp\n\t/data1/sudong/mo-regression/matrixone/pkg/vectorize/external/external.go:351\ngithub.com/matrixorigin/matrixone/pkg/sql/plan/function/builtin/multi.ParseTime[...]\n\t/data1/sudong/mo-regression/matrixone/pkg/sql/plan/function/builtin/multi/external.go:71\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.GetBatchData\n\t/data1/sudong/mo-regression/matrixone/pkg/sql/colexec/external/external.go:306\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.ScanFileData\n\t/data1/sudong/mo-regression/matrixone/pkg/sql/colexec/external/external.go:407\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/external.Call\n\t/data1/sudong/mo-regression/matrixone/pkg/sql/colexec/external/external.go:94\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/data1/sudong/mo-regression/matrixone/pkg/vm/vm.go:61\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun\n\t/data1/sudong/mo-regression/matrixone/pkg/vm/pipeline/pipeline.go:100\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run\n\t/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:51\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1\n\t/data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:73\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"}
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus
        /data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:454
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus
        /data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:446
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:2488
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:2557
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:125

DDL:
create table bmsql_order_line (
  ol_w_id         integer   not null,
  ol_d_id         integer   not null,
  ol_o_id         integer   not null,
  ol_number       integer   not null,
  ol_i_id         integer   not null,
  ol_delivery_d   timestamp,
  ol_amount       decimal(6,2),
  ol_supply_w_id  integer,
  ol_quantity     integer,
  ol_dist_info    char(24),
  primary key (ol_w_id, ol_d_id, ol_o_id, ol_number)
) PARTITION BY KEY(ol_w_id);

DATA SAMPLE:

**Comment by heni02** [comment]
timestamp is NULL load data is failed，“”is succeed
![image](https://user-images.githubusercontent.com/113406637/198921949-279f6dd4-a5ee-4104-9804-dba09579c666.png)
insert into values succeed
![image](https://user-images.githubusercontent.com/113406637/198922645-37a6bca4-437d-49d8-b085-3f9b644571ad.png)

**Comment by mooleetzi** [comment]
plz give a load_data

**Comment by mooleetzi** [comment]
please see https://github.com/matrixorigin/matrixone/issues/5079, set a null map to recognize null string

**Comment by heni02** [comment]
confirm,closed
commit id :238f5a0f6f921b2e2414435c6d83ca949238bb22
![image](https://user-images.githubusercontent.com/113406637/199386020-78fb4d0e-61c1-4b02-a524-f7ae64499ed7.png)

**Comment by aressu1985** [comment]
fixed
