### ISSUE TITLE
[Bug]: mo panic when run tpcc benmark

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5578]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022-10-12 18:09:48 ERROR jTPCCTerminal:953 - Unexpected SQLException in PAYMENT
2022-10-12 18:09:48 ERROR jTPCCTerminal:953 - Unexpected SQLException in PAYMENT
2022-10-12 18:09:48 ERROR jTPCCTerminal:953 - Unexpected SQLException in PAYMENT
2022-10-12 18:09:48 ERROR jTPCCTerminal:955 - internal error: panic runtime error: index out of range [11] with length 11: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:316
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:199
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:162
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:55
github.com/matrixorigin/matrixone/pkg/sql/colexec/update.Call
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/colexec/update/update.go:145
github.com/matrixorigin/matrixone/pkg/vm.Run
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/vm/pipeline/pipeline.go:147
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/scope.go:110
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Update
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/dml.go:62
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/compile/compile.go:128
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2316
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2609
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
	/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:125
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1165

**Comment by tianyahui-python** [comment]
@aressu1985 pls update the performance on latest commit

**Comment by LeftHandCold** [comment]
fixed

**Comment by aressu1985** [comment]
do not be fixed 

the same as another issue #6280, this can be closed
