### ISSUE TITLE
[Bug]: Standardize the behavior of tableDef, Resolve, GetHidekey and their definitions

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#5590]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Confusion

**Comment by nnsgmsone** [comment]
The inteface of engine, TableDefs(), GetPrimaryKeys(), GetHideKeys() are unclear definition.Need to refactor its behavior, suggest adding TableColumns() to return the definition of all columns. Also show create table suggests using mo_tables.createSql directly instead of using the result construct returned by TableDefs().

**Comment by sukki37** [comment]
@nnsgmsone could u pls test it at the latest commit and update the issue status, thx

**Comment by florashi181** [comment]
start to do it this week @aunjgr

**Comment by aunjgr** [comment]
Has discussed this with @ouyuanning and decided to start it after v0.6 is finished. The refactorization will involve many parts, so too dangerous to touch it now.

**Comment by aunjgr** [comment]
Redesign of TableDef has been finished. Separate constraints will be migrated one by one, and should be tracked by separate issues.

This one can be closed.
