### ISSUE TITLE
[Bug]: Constraint of Composite Primary Key is stored in tae

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5604]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Currently, the Composite Primary Key is not stored as a Constraint yet

**Comment by bbbearxyz** [comment]
I think now cpkey is implmented in the compute layer, so Xu Peng please talk with Tian Feng, give a conclusion

**Comment by nnsgmsone** [comment]
> I think now cpkey is implmented in the compute layer, so Xu Peng please talk with Tian Feng, give a conclusion

must store @bbbearxyz

**Comment by bbbearxyz** [comment]
in the pr #6221, Primary Key Info is stored in tae by schema.SortKey and schema.Field, return the def by engine.PrimaryIndexDef

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by aunjgr** [comment]
It's a feature issue. And it is in the scope of #5590.

**Comment by aunjgr** [comment]
No effort until now.

**Comment by aunjgr** [comment]
No progress on this issue yet.

**Comment by aunjgr** [comment]
TableDef will be refactored after the design is finalized next week. All types of constraints will be put in a unified frame accordingly.

**Comment by aunjgr** [comment]
Working on #6616. TableDef is still in desigining.

**Comment by aunjgr** [comment]
track the progress at #5590

**Comment by aunjgr** [comment]
Refactor of TableDef has begun.

**Comment by aunjgr** [comment]
Primary key constraint will be refactored by @bbbearxyz

**Comment by aunjgr** [comment]
Has passed it on to @bbbearxyz

**Comment by bbbearxyz** [comment]
I will fix when i support all the secondary key feature.

**Comment by bbbearxyz** [comment]
I will fix when i support all the secondary key feature.

**Comment by bbbearxyz** [comment]
I will fix when i support all the secondary key feature.

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by qingxinhome** [comment]
It is being processed

**Comment by qingxinhome** [comment]
This function has been completed and pr has been submitted. Please accept and test. @nnsgmsone @domingozhang @daviszhen @aunjgr @bbbearxyz

**Comment by heni02** [comment]
composite primary key bvt case merged ,this issue closed
![image](https://user-images.githubusercontent.com/113406637/217173317-a8106f30-3e6a-4987-9e5b-5d6f941ad79f.png)
