### ISSUE TITLE
[Bug]: CN mysql connection hang when using CN-TAE-DN-MEM

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#5640]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6bef285c
```

### Actual Behavior

CN hangs on mysql connection after printing the following logs, so the client also hangs:

```
{"level":"INFO","time":"2022/10/14 13:09:13.929734 +0000","caller":"frontend/routine_manager.go:164","msg":"HANDLE HANDSHAKE"}
```

### Expected Behavior

Client should be able to connect to CN and execute SQLs.

### Steps to Reproduce

```Markdown
Start a cluster using CN-TAE-DN-MEM and run some workloads, this issue might be reproduced.
```

### Additional information

CN log:

[cn-log.tgz](https://github.com/matrixorigin/matrixone/files/9786936/cn-log.tgz)

**Comment by aylei** [comment]
cc @zhangxu19830126

**Comment by zhangxu19830126** [comment]
@reusee

**Comment by florashi181** [comment]
so who is the owner of this issue next？shall we close it? @reusee @aylei

**Comment by daviszhen** [comment]
now e2e configuration works well. I do not think we have such problem.

**Comment by fengttt** [comment]
Not relavent any more.

**Comment by florashi181** [comment]
maybe u can close this issue @aylei
