### ISSUE TITLE
[Bug]: mo-service boot failed

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#5661]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):07cd9795c6b98813539505ee8fccc7a20b0f27e9
- Hardware parameters:mac
- OS type:
- Others:
```

### Actual Behavior

the mo-service can not boot.

### Steps to Reproduce

./mo-service -launch etc/launch-tae-logservice/launch.toml

### Additional information

[log.txt.tar.gz](https://github.com/matrixorigin/matrixone/files/9793806/log.txt.tar.gz)

**Comment by yingfeng** [comment]
verify whether it will still happen right now

**Comment by daviszhen** [comment]
it was fixed in newest version.
