### ISSUE TITLE
[Bug]: column name conflicts with reserved keyword 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5673]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In table system.statement_info, there is a conflict as following:

select user,host from statement_info; -> correct
select database from statement_info; -> correct
select \`database\` from satement_info; ->error

**Comment by YANGGMM** [comment]
Actual behavior:
select user,host from statement_info; -> correct
select database from statement_info; -> error
select `database` from satement_info; ->correct
