### ISSUE TITLE
[Docs]: Built-in Streaming Engine

### ISSUE THREAD

**Issue by ChenpiDog** [matrixorigin/matrixone#5677]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
I did not find any content related to stream processing in the document.

Directory: Overview -> MatrixOne Introduction -> Key Features -> Hyperconverged Engine -> Built-in Streaming Engine

Does it mean that I can achieve real-time ETL without a third-party stream processing engine? The document needs to be improved to explain the incremental material view, what it can do and how to use it.
```

### Additional information

I hope that with MatrixOne alone, real-time ETL can be achieved through SQL.

**Comment by dengn** [comment]
Yes, that is a feature in MO roadmap but not fully implemented yet.

**Comment by sukki37** [comment]
This issue has been inactive for a while. To help keep our backlog clear, I'm going to close this. If you feel this is still relevant, please comment or reopen. Thanks for understanding!
