### ISSUE TITLE
[Bug]: Tae's rowid is Inefficient

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#5679]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tae use binary.BigEndian.PutUint64(rowid[:8], v), i think should use types.EncodeUint64。Otherwise cn delete row by blockid may be inefficient.

**Comment by fengttt** [comment]
There maybe reasons that tae want to use big endian.    They may need to memcmp the rowid.

**Comment by nnsgmsone** [comment]
> There maybe reasons that tae want to use big endian. They may need to memcmp the rowid.

Maybe so, but it would be a lot more overhead for cn to extract the blockid and offset from the rowid. cn is using index to handle this order problem.

**Comment by nnsgmsone** [comment]
For cn, it is a very frequent operation to extract the block id and offset according to the rowid, and then remove some rows corresponding to the block of s3 according to this information (merge read). Of course, this overhead can be ignored for now.
