### ISSUE TITLE
[Bug]: duration is different from client result in system.statement_info

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5700]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select statement,request_at,duration/1000000000 as duration_second from system.statement_info where statement like 'select%' and duration/1000000000>1  order by request_at desc;

<img width="914" alt="image" src="https://user-images.githubusercontent.com/88298673/196328370-c15ae1c2-9a6a-4c27-8d15-294dddefe841.png">

The actual result is as following. The second one is different.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/88298673/196328527-d410c9cc-783d-4a81-a804-9752fcfc96b8.png">
<img width="276" alt="image" src="https://user-images.githubusercontent.com/88298673/196328434-15a10065-315b-4d38-8f3d-3976fffb1428.png">

**Comment by domingozhang** [comment]
It seems the duration calculating the total time of a script
<img width="504" alt="image" src="https://user-images.githubusercontent.com/88298673/196329297-692b2c53-22a4-4980-9667-2000397ad6e3.png">

**Comment by xzxiong** [comment]
retry meet panic
```
use tpch ;
load data infile '/data/go/src/github.com/matrixorigin/1G_data/lineitem.tbl' into table LINEITEM FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
select now(); select count(*) from lineitem; select now();
```
see https://github.com/matrixorigin/matrixone/issues/5712

**Comment by xzxiong** [comment]
seams already fixed, not repro
