### ISSUE TITLE
[Feature Request]:  Add TIME type

### ISSUE THREAD

**Issue by dongdongyang33** [matrixorigin/matrixone#5704]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. displays TIME values in `hh:mm:ss` format (or `hhh:mm:ss` format for large hours values) and its range from '-838:59:59' to '838:59:59'. And the second can be decimal. eg. '00:00:00.1234'
2. **invalid time** handle
3. valid **outrange time** handle
4. **abbreviated time** handle
5. support **compare**
6. support time related function: time(), date_add(), date_sub() ... in future

**Comment by dongdongyang33** [comment]
PR #5944 just completed part of time-type-related job.
still missing:
* date_sub
* cast between timestamp and time
* cast between blob and time
* time diff
* interval
* more date_add/date_sub type (day/month/year)

**Comment by dongdongyang33** [comment]
A troublesome bug about time() function
`select time("11:22:33.4444");`

The expected result is "11:22:33.4444" but we can only output "11:22:33"

**Comment by dongdongyang33** [comment]
#6025 
fix an issue about  com_stmt_execute data binary protocol

**Comment by YANGGMM** [comment]
#6021 support timediff function

**Comment by heni02** [comment]
test done，bvt case done

**Comment by dongdongyang33** [comment]
remove the limit of time. current limit range: (-839:00:00, 839:00:00)
