### ISSUE TITLE
[Bug]: drop role if exists moadmin,public successed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5705]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

moadmin,public deleted
![image](https://user-images.githubusercontent.com/113406637/196359873-f291cd47-e07b-470d-84cc-6cbd35d90400.png)

drop account sys deleted
![image](https://user-images.githubusercontent.com/113406637/196609484-d58ce61f-3ae3-4c5a-9f00-1610db225395.png)

drop user root,dump deleted
![image](https://user-images.githubusercontent.com/113406637/196614716-8b496c42-80cb-4d43-a7e3-979b03a0c82c.png)

drop role if exists accountadmin deleted
![image](https://user-images.githubusercontent.com/113406637/196626049-947a6c78-e44c-4608-b648-6962d10fb8f2.png)

### Steps to Reproduce

```Markdown
drop role if exists moadmin,public;
```

**Comment by daviszhen** [comment]
it was fixed.

**Comment by heni02** [comment]
confirm,closed
![image](https://user-images.githubusercontent.com/113406637/197666220-5246e229-e123-427b-aca2-56bfce10d830.png)
