### ISSUE TITLE
[Bug]: update mo_tables set xxx internal error panic runtime error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5707]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/196584644-4cf75d21-ed92-43d4-a3d6-50c3aa6e0cd8.png)

delete from mo_catalog.mo_database;
![image](https://user-images.githubusercontent.com/113406637/196630805-f1e7dc13-c90c-46ca-ad60-0737704374b5.png)
delete from mo_catalog.mo_columns;
![image](https://user-images.githubusercontent.com/113406637/196631393-94ba3bce-c510-4097-ab03-7029daa569a6.png)

### Expected Behavior

do not have privilege to execute the statement

### Steps to Reproduce

```Markdown
update mo_catalog.mo_tables set relanme='mo_aaaa';
```

**Comment by daviszhen** [comment]
if the mo_tables does  not have the hide keys , it should just pitch an error instead of panic.

**Comment by aptend** [comment]
discussed with @daviszhen, GetHiddenKeys will return a `NotSupportedError` now

but the error msg is not `do not have privilege to execute the statement`, maybe some modifications are needed in frontend

Actual Behavior:

start: ./mo-service -launch etc/launch-tae-logservice/launch.toml

```sh
mysql>
mysql> update mo_tables set relanme='mo_aaaa';
ERROR 20101 (HY000): internal error: cannot find update table: mo_catalog.mo_tables
mysql> delete from mo_catalog.mo_columns;
ERROR 20301 (HY000): invalid input: delete has no table def
mysql> delete from mo_catalog.mo_databases;
ERROR 20301 (HY000): invalid input: delete has no table def
mysql>
```

**Comment by daviszhen** [comment]
I will verify the issue in this weekend.

**Comment by heni02** [comment]
confirm,closed
commit id:b7215088e856e7da62e67e80a96b6c3bc0d89eb1
![image](https://user-images.githubusercontent.com/113406637/205033117-3618d78a-7b2f-4c0d-b470-b7dcaeeada31.png)
