### ISSUE TITLE
[Bug]: panic runtime error during a two tables joined query

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5713]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

use system;
select si.request_at time_stamp,si.statement as SQL,el.err_code from statement_info si,error_info el where si.statement_id=el.statement_id;

ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/lib/golang/src/runtime/panic.go:260
runtime.sigpanic
	/usr/lib/golang/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).newMergeScope
	/data1/zhangxiao/matrixone/pkg/sql/compile/compile.go:920
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).newJoinScopeList
	/data1/zhangxiao/matrixone/pkg/sql/compile/compile.go:1001
github.com/matrixorigin/ma

**Comment by m-schen** [comment]
An error occurred while cloning the scope because lack of serialization method for the external operator.
I will add it.

**Comment by domingozhang** [comment]
fixed
