### ISSUE TITLE
[Bug]: result of SHOW GRANTS is abnormal

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5716]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="238" alt="image" src="https://user-images.githubusercontent.com/88298673/196382622-d5b8c142-e433-49e6-ae2d-c2f79e14a728.png">

There is no space between keywords;
The title of result is test@localhost;

If run 
show grants for \`test\`@\`localhost\`;
The result is 
Empty set (0.00 sec)

**Comment by heni02** [comment]
show grants for user results about  *.* is not correct
![image](https://user-images.githubusercontent.com/113406637/197708322-33254580-a35d-49ae-8fc2-567d475f3691.png)

**Comment by heni02** [comment]
confirm，closed
commit id:55398afae19b40f2e689994185a1d2b7dc07868c
<img width="716" alt="企业微信截图_1e361191-23ed-4522-9ad9-859fdfdc9464" src="https://user-images.githubusercontent.com/113406637/198805244-0f10c875-3d48-4c8a-bb84-80d663dab8f0.png">

**Comment by aressu1985** [comment]
fixed
