### ISSUE TITLE
[Bug]: MO somehow quits unexpectedly  

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5727]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 7e02622c30f3dea90862d3c95ddb48bbf88a81ae
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo will exit unexpectedly after running for a while

**Comment by zhangxu19830126** [comment]
tae-logservice ， 跑tae-cn-tae-dn也是一会儿就挂了

**Comment by DanielZhangQD** [comment]
The MO Pods are down (mainly logservice Pods) after running several hours on EKS.
The logs have been deleted and I will update the new logs when this is reproduced later.

```
NAME                                       READY   STATUS             RESTARTS          AGE                   
aws-us-west-2-serverless-dn-0              0/1     CrashLoopBackOff   176 (4m45s ago)   14h     
aws-us-west-2-serverless-log-0             0/1     Terminating        516 (20h ago)     2d20h   
aws-us-west-2-serverless-log-1             0/1     Terminating        0                 4d11h   
aws-us-west-2-serverless-log-2             0/1     CrashLoopBackOff   384 (2m51s ago)   36h     
aws-us-west-2-serverless-log-3             1/1     Running            0                 14h     
aws-us-west-2-serverless-log-4             0/1     CrashLoopBackOff   391 (53s ago)     36h     
aws-us-west-2-serverless-log-5             1/1     Running            0                 14h     
aws-us-west-2-serverless-log-6             1/1     Running            1 (14h ago)       14h     
aws-us-west-2-serverless-tp-cn-0           0/1     CrashLoopBackOff   418 (54s ago)     36h   
```

**Comment by fengttt** [comment]
@zhangxu19830126 what is the plan?   Starting from log?  Why do this not leave a line in our log?

**Comment by zhangxu19830126** [comment]
add some log first, and reproduce this bug.

**Comment by zhangxu19830126** [comment]
I use [gomonkey](https://github.com/agiledragon/gomonkey) to hack os.Exit with a panic func.  And distribute the binary to @dengn and @domingozhang.  Exhaust first whether it is mo calling os.Exit in certain scenarios to exit

**Comment by zhangxu19830126** [comment]
I saw one exit because the ssh session was closed and the mo process was killed by the system. I guess it has something to do with the way we start.

**Comment by fengttt** [comment]
you mean not daemonized?

**Comment by fengttt** [comment]
- Daemonize (nohup) solved kill caused by ssh disconnect.
- gomonkey is not catching kills (not repro).
- caught many panics, but those are fixed.

To do:
- If mysterious kill appears again, involve qinghui to get a core dump
- If new panics appear, post stack here and we will fix.

Downgrade S-1 to S0 as this is not immediately actionable.

**Comment by zhangxu19830126** [comment]
No abnormal exits occur

**Comment by fengttt** [comment]
Lower to S1, unless we see it again.

**Comment by zhangxu19830126** [comment]
So far there is no reproduction, I think it is the operation of the problem. It is recommended to close and encounter in reopen

**Comment by sukki37** [comment]
Not repro for a long time. close.
