### ISSUE TITLE
[Bug]: Instance crashed after relogin and querying in MO

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5737]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Step 1: Create tables
Step 2: Load data
Step 3: Quit mysql client and relogin
Step 4: select count(*) from tablename; --> lost connection

| [{"global":{"alloc": 73270,"free": 55637,"goalloc": 0,"allocBytes": 15016959513,"freeBytes": 10412940050,"currBytes": 4604019463,"highWaterMark": 5825907647}},{"mem_txn_storge": ""},{"zero_fixed_mp_for_test": ""},{"tae_cache": {"alloc": 7,"free": 0,"goalloc": 0,"allocBytes": 16760832,"freeBytes": 0,"currBytes": 16760832,"highWaterMark": 16760832}},{"session": {"alloc": 107,"free": 104,"goalloc": 0,"allocBytes": 38940,"freeBytes": 6156,"currBytes": 32784,"highWaterMark": 33200}},{"tae_immutable": {"alloc": 16122,"free": 13036,"goalloc": 0,"allocBytes": 4527715712,"freeBytes": 2193511888,"currBytes": 2334203824,"highWaterMark": 2336374192},
 "Fixed-0": {"alloc": 257,"free": 232,"goalloc": 0,"allocBytes": 10078,"freeBytes": 0,"currBytes": 10078,"highWaterMark": 10078},
 "Fixed-1": {"alloc": 1186,"free": 1172,"goalloc": 0,"allocBytes": 113110,"freeBytes": 0,"currBytes": 113110,"highWaterMark": 113110},
 "Fixed-2": {"alloc": 1178,"free": 1173,"goalloc": 0,"allocBytes": 224322,"freeBytes": 0,"currBytes": 224322,"highWaterMark": 224322},
 "Fixed-3": {"alloc": 1178,"free": 1174,"goalloc": 0,"allocBytes": 448647,"freeBytes": 0,"currBytes": 448647,"highWaterMark": 448647},
 "Fixed-4": {"alloc": 1175,"free": 1172,"goalloc": 0,"allocBytes": 895030,"freeBytes": 0,"currBytes": 895030,"highWaterMark": 895030},
 "Fixed-5": {"alloc": 1172,"free": 1167,"goalloc": 0,"allocBytes": 1785900,"freeBytes": 0,"currBytes": 1785900,"highWaterMark": 1785900},
 "Fixed-6": {"alloc": 1167,"free": 1167,"goalloc": 0,"allocBytes": 3555480,"freeBytes": 0,"currBytes": 3555480,"highWaterMark": 3555480}},{"tae_log": {"alloc": 7,"free": 0,"goalloc": 0,"allocBytes": 5963776,"freeBytes": 0,"currBytes": 5963776,"highWaterMark": 5963776}},{"fallback_proc_mp": {"alloc": 11,"free": 0,"goalloc": 0,"allocBytes": 60,"freeBytes": 0,"currBytes": 60,"highWaterMark": 60}},{"session": {"alloc": 42,"free": 39,"goalloc": 0,"allocBytes": 18985,"freeBytes": 18961,"currBytes": 24,"highWaterMark": 3248}},{"tae_default": {"alloc": 41236,"free": 26720,"goalloc": 0,"allocBytes": 5528636175,"freeBytes": 3281578012,"currBytes": 2247058163,"highWaterMark": 3611110243},
 "Fixed-0": {"alloc": 2698,"free": 2698,"goalloc": 0,"allocBytes": 146354,"freeBytes": 0,"currBytes": 146354,"highWaterMark": 146354},
 "Fixed-1": {"alloc": 2454,"free": 2454,"goalloc": 0,"allocBytes": 280854,"freeBytes": 0,"currBytes": 280854,"highWaterMark": 280854},
 "Fixed-2": {"alloc": 2480,"free": 2480,"goalloc": 0,"allocBytes": 565004,"freeBytes": 0,"currBytes": 565004,"highWaterMark": 565004},
 "Fixed-3": {"alloc": 2481,"free": 2480,"goalloc": 0,"allocBytes": 1129291,"freeBytes": 0,"currBytes": 1129291,"highWaterMark": 1129291},
 "Fixed-4": {"alloc": 2477,"free": 2477,"goalloc": 0,"allocBytes": 2255002,"freeBytes": 0,"currBytes": 2255002,"highWaterMark": 2255002},
 "Fixed-5": {"alloc": 2468,"free": 2467,"goalloc": 0,"allocBytes": 4496721,"freeBytes": 0,"currBytes": 4496721,"highWaterMark": 4496721},
 "Fixed-6": {"alloc": 2460,"free": 2460,"goalloc": 0,"allocBytes": 8967272,"freeBytes": 0,"currBytes": 8967272,"highWaterMark": 8967272}}] |

**Comment by domingozhang** [comment]
[server.log](https://github.com/matrixorigin/matrixone/files/9816459/server.log)

**Comment by fengttt** [comment]
It is TAE immutable and fallback-proc-mp.    Can we turn on details and see who exactly is leaking?
