### ISSUE TITLE
[Bug]: status gets internal error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#5738]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b862e463867bf1e09666482ca0c9e2ca8ba22d35
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

with mysql connect, type "status" to check connection status. It prints out internal error.

mysql> status

mysql  Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)

Connection id:		1003
Current database:
Current user:		dump@0.0.0.0
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		0.5.1 MatrixOne
Protocol version:	10
Connection:		127.0.0.1 via TCP/IP
ERROR 20101 (HY000): internal error: the system variable does not exist
ERROR 2014 (HY000): Commands out of sync; you can't run this command now
Client characterset:	utf8mb4
Server characterset:	utf8mb4
TCP port:		6002
Binary data as:		Hexadecimal

**Comment by aressu1985** [comment]
fxied:commit fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
mysql> 
mysql> 
mysql> status
--------------
mysql  Ver 8.0.31 for Linux on x86_64 (MySQL Community Server - GPL)

Connection id:		1075
Current database:	
Current user:		dump@0.0.0.0
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		0.5.1 MatrixOne
Protocol version:	10
Connection:		127.0.0.1 via TCP/IP
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
TCP port:		6001
Binary data as:		Hexadecimal
--------------

mysql>
