### ISSUE TITLE
[Bug]: Is this calculation result right? BIT_XOR()

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5743]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DDL : 
DROP TABLE IF EXISTS t;
DROP TABLE IF EXISTS t1;
CREATE TABLE t(
	id INT,
	str1 VARCHAR(50),
	str2 CHAR(50),
	PRIMARY KEY (id)
);
CREATE TABLE t1(
	id INT,
	str1 VARCHAR(50),
	str2 CHAR(50),
	PRIMARY KEY (id)
);

DML : 
INSERT INTO t VALUES (1,'12.3','9.00200001'), (2,'0','1'), (3,'0.000000000000111101010101','189'), (4,'456','1.001');
INSERT INTO t1 VALUES (1,'00000.01','3.001'), (2,'-1','99999999999999999'), (3,'1.0111','0.00001'), (4,'1.01','000.001');

The problematic SQL stmt is : 
SELECT BIT_XOR(CAST(t.str1 AS DOUBLE)), BIT_XOR(CAST(t1.str2 AS FLOAT)) FROM t RIGHT JOIN t1 ON t.id = t1.id;

It's return value on MO is : 
![mo](https://user-images.githubusercontent.com/74952516/196607753-8db9a2ef-055b-419a-95a6-af216e646ce1.jpg)

It's return value on MySQL is : 
![mysql](https://user-images.githubusercontent.com/74952516/196607801-2c041ed2-3a7d-49b6-bc56-703f8876b02a.jpg)

**Comment by domingozhang** [comment]
the individual result of bit_xor is the same in both mo and mysql. it is something wrong in mysql parser.
