### ISSUE TITLE
[Bug]: table exists when creating but drop table not found

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#5763]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t1 (id int primary key ,a int);
ERROR 20421 (HY000): table t1 already exists
mysql> drop table t1;
ERROR 20403 (HY000): no such table sudong.t1
mysql> create table t1 (id int primary key ,a int);
ERROR 20421 (HY000): table t1 already exists
mysql> drop table t1;
ERROR 20403 (HY000): no such table sudong.t1

{"level":"INFO","time":"2022/10/19 18:05:17.119286 +0800","caller":"frontend/util.go:463","msg":"query trace status","connection_id":4294967295,"statement":"select rp.privilege_id, rp.with_grant_option from mo_catalog.mo_role_privs as rp where rp.obj_id = 0 and rp.obj_type = \"database\" and rp.role_id = 0 and rp.privilege_id = 23 and rp.privilege_level = \"*\"","status":"success"}
{"level":"INFO","time":"2022/10/19 18:05:17.119387 +0800","caller":"frontend/util.go:463","msg":"query trace status","connection_id":4294967295,"statement":"commit","status":"success"}
{"level":"INFO","time":"2022/10/19 18:05:17.119406 +0800","caller":"frontend/mysql_cmd_executor.go:2812","msg":"----close mce"}
{"level":"INFO","time":"2022/10/19 18:05:17.119567 +0800","caller":"frontend/session.go:1301","msg":"dbName sudong tableNames [%!%mo_increment_columns v1 t2 t1]"}
{"level":"INFO","time":"2022/10/19 18:05:17.119683 +0800","caller":"plan/build_ddl.go:599","msg":"error: no such table sudong.t1","span":{}}
{"level":"ERROR","time":"2022/10/19 18:05:17.119707 +0800","caller":"frontend/mysql_cmd_executor.go:2600","msg":"no such table sudong.t1","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2600\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2677\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"ERROR","time":"2022/10/19 18:05:17.119754 +0800","caller":"frontend/util.go:465","msg":"query trace status","connection_id":1065,"statement":"drop table t1","status":"fail","error":"no such table sudong.t1","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:465\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:457\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2608\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2677\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"INFO","time":"2022/10/19 18:05:17.119850 +0800","caller":"frontend/routine.go:170","msg":"connection id 1065 , the time of handling the request 36.163917ms"}

{"level":"INFO","time":"2022/10/19 18:05:18.303174 +0800","caller":"frontend/util.go:463","msg":"query trace status","connection_id":4294967295,"statement":"select rp.privilege_id, rp.with_grant_option from mo_catalog.mo_role_privs as rp where rp.obj_id = 0 and rp.obj_type = \"database\" and rp.role_id = 0 and rp.privilege_id = 20 and rp.privilege_level = \"*\"","status":"success"}
{"level":"INFO","time":"2022/10/19 18:05:18.303240 +0800","caller":"frontend/util.go:463","msg":"query trace status","connection_id":4294967295,"statement":"commit","status":"success"}
{"level":"INFO","time":"2022/10/19 18:05:18.303261 +0800","caller":"frontend/mysql_cmd_executor.go:2812","msg":"----close mce"}
{"level":"INFO","time":"2022/10/19 18:05:18.303599 +0800","caller":"frontend/mysql_cmd_executor.go:2314","msg":"time of Exec.Build : 316.666µs"}
{"level":"INFO","time":"2022/10/19 18:05:18.303617 +0800","caller":"compile/scope.go:43","msg":":6 "}
{"level":"INFO","time":"2022/10/19 18:05:18.303696 +0800","caller":"compile/ddl.go:85","msg":"error: table t1 already exists","span":{}}
{"level":"ERROR","time":"2022/10/19 18:05:18.303713 +0800","caller":"frontend/mysql_cmd_executor.go:2600","msg":"table t1 already exists","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2600\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2677\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"ERROR","time":"2022/10/19 18:05:18.303745 +0800","caller":"frontend/util.go:465","msg":"query trace status","connection_id":1065,"statement":"create table t1 (id int primary key, a int)","status":"fail","error":"table t1 already exists","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:465\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:457\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2608\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2677\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:159"}

**Comment by badboynt1** [comment]
can not reproduce, keep watching

**Comment by badboynt1** [comment]
can not reproduce, keep watching

**Comment by badboynt1** [comment]
keep watching

**Comment by aressu1985** [comment]
can not reproduce, closed
