### ISSUE TITLE
[Bug]: [CN-DN BVT] unique key doesn't work

### ISSUE THREAD

**Issue by jiangxinmeng1** [matrixorigin/matrixone#5790]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="290" alt="1" src="https://user-images.githubusercontent.com/51114574/196913467-4aee76a2-89fb-4b4b-a2c1-5bd4ab00b25f.PNG">

### Steps to Reproduce

```Markdown
create database t;
use t
drop table if exists t1;
create table t1(a int, b varchar(20), unique key(a));
insert into t1 values(1, '1');
insert into t1 values(1, '1');
select * from t1;
```

**Comment by bbbearxyz** [comment]
I will disable the unique index bvt, and when the unique index is fixed, I will enable the bvt

**Comment by fengttt** [comment]
We will do the following,

1. disable all delete/udpate unique key in bvt test.  Let CN/DN bvt pass.
2. A real fix for delete and update.
3. Re-enable.

The real fix, roughly the idea is the following.   Suppose we have 
create table T(a int not null primary key, b int unique key);

delete from t where a > 100;
The plan will be
```
scan t --->   where ---->  join -----> delete t and delete uniqidx of t
                                        /|\
        scan t uniq key  -----| 
```

The delete can be one or two operators.
The join is subject to all reasonable optimization, including bloom filter pushdown and/or choosing index nest loop join

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
most of the code is complete, now do some test and fix bug.

**Comment by bbbearxyz** [comment]
The code is finish and wait the pr review.

**Comment by heni02** [comment]
still problems, waiting for verification after repair 
confirm commit id：60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e

**Comment by heni02** [comment]
confirm,closed
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210355637-253c2a0c-70b9-4f93-bf98-fd02e19e8595.png)

**Comment by heni02** [comment]
@aressu1985  plz closed this issue

**Comment by matrix-meow** [comment]
Hello @jiangxinmeng1. The bug issue in the BVT test code has not been removed,issues automatically open.
