### ISSUE TITLE
[Bug]: Secondary index Key not exists column reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5792]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/196922909-b23b1827-2692-46cd-ac64-f935398c6c4a.png)

### Steps to Reproduce

```Markdown
CREATE TABLE IF NOT EXISTS `t_code_rule` (
  `code_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code_no` varchar(50) NOT NULL,
  `org_no` varchar(50) NOT NULL,
  `org_name` varchar(50) NOT NULL,
  PRIMARY KEY (`code_id`),
  UNIQUE KEY `code_type` (`code_type`),
  KEY `code_no` (`code_no`),
  KEY `code_rule_no` (`code_rule_no`),
  KEY `org_no` (`org_no`)
);
```

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will solve it after unique index is complete

**Comment by bbbearxyz** [comment]
will solve it after unique index is complete

**Comment by bbbearxyz** [comment]
the secondary key will first support grammer, the index table is need or not will be discuss.

**Comment by bbbearxyz** [comment]
this bug is fixed.

**Comment by bbbearxyz** [comment]
<img width="925" alt="Screen Shot 2023-01-13 at 3 11 56 PM" src="https://user-images.githubusercontent.com/71327518/212259393-2592f003-0776-48a8-b416-e890e9a595a0.png">

**Comment by bbbearxyz** [comment]
please confrim it.

**Comment by heni02** [comment]
same as #7384 confirm,closed
