### ISSUE TITLE
[Bug]: Show create table has no secondary index information

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/196924124-24fb7001-fa53-47c6-a658-8a3dd971be3d.png)

### Steps to Reproduce

```Markdown
CREATE TABLE IF NOT EXISTS `t_code_rule_2` (
  `code_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code_no` varchar(50) NOT NULL,
  `org_no` varchar(50) NOT NULL,
  `org_name` varchar(50) NOT NULL,
  `code_type` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`code_id`),
  UNIQUE KEY `code_type` (`code_type`),
  KEY `code_no` (`code_no`),
  KEY `org_no` (`org_no`)
);
```

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will solve it after unique index is complete

**Comment by bbbearxyz** [comment]
will solve it after unique index is complete

**Comment by bbbearxyz** [comment]
the secondary key will first support grammer, the index table is need or not will be discuss.

**Comment by bbbearxyz** [comment]
the bug is fixed.

**Comment by bbbearxyz** [comment]
<img width="1792" alt="Screen Shot 2023-01-13 at 3 10 59 PM" src="https://user-images.githubusercontent.com/71327518/212259218-4496dc6b-63ec-4527-887a-f081fe30925f.png">

**Comment by bbbearxyz** [comment]
please confrim it.

**Comment by heni02** [comment]
same issue as #7581 closed
