### ISSUE TITLE
[Bug]: [CN-DN-BVT] Progress report.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#5807]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

BVT pass

**Comment by fengttt** [comment]
@XuPeng-SH 2022-10020 23:48:25     Pass rate 84%.

**Comment by fengttt** [comment]
https://github.com/XuPeng-SH/tae_design/blob/main/tae_v0_6/bvt/1020-memo.md

**Comment by fengttt** [comment]
2022/10/21  97%.    I cannot attached the error file, but here is from YingFeng,
一共700多没有通过的，看起来除了事务就是auto incre，这2个都弄掉，也就不到500
剩下的其实不少
比如null处理，乱码，各种小的

**Comment by fengttt** [comment]
[error (1).txt](https://github.com/matrixorigin/matrixone/files/9843195/error.1.txt)

**Comment by XuPeng-SH** [comment]
By 2022/10/22 08:00:00 AM，BeijingTime
Error report: [error.txt](https://github.com/matrixorigin/matrixone/files/9843194/error.txt)

**Comment by XuPeng-SH** [comment]
By 2022/10/22 20:00:00 AM，BeijingTime
Error report: [error.txt](https://github.com/matrixorigin/matrixone/files/9844238/error.txt)

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/39627130/197337148-4f48866b-b4cc-4524-88a4-8d4900793abd.png">

Pending Issues:
#5856 
#5841 
#5835 
#5834 
#5790 
#5772

**Comment by XuPeng-SH** [comment]
By 2022/10/24 10:00:00 AM, BeijingTime
Error report: [error.txt](https://github.com/matrixorigin/matrixone/files/9848265/error.txt)

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/39627130/197435770-778d0866-1c37-4516-aa3a-b59f9cf94255.png">

**Comment by XuPeng-SH** [comment]
By 2022/10/24 20:00:00 PM, Beijing Time

**100% PASS**

![image](https://user-images.githubusercontent.com/39627130/197523452-faa24d0c-f605-46b9-bad2-3d1a257c0118.png)

Commit id: 8d1a93ca980a020e6552ee3bd66bc963a678fd22

**Comment by fengttt** [comment]
CI e2e test now runs all test, but will timeout.   This is a blocking issue, see
https://github.com/matrixorigin/matrixone/issues/5910

**Comment by XuPeng-SH** [comment]
By 2022/10/26 11:00:00 AM, Beijing Time

*BVT WITH BLOCKLIST*

> Disable Tenant Cases
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/39627130/197928213-f6761c74-311e-43ae-ba3a-84619147127e.png">


Error report: [error.txt](https://github.com/matrixorigin/matrixone/files/9865779/error.txt)


Commit: cefc73a975734f1de66036a7d6064ced10591a23

**Comment by fengttt** [comment]
What is BVT WITH BLOCKLIST pass rate now?

**Comment by fengttt** [comment]
Close this one, moving on to blocklist
