### ISSUE TITLE
[Bug]: [CN-DN BVT] Transaction behavior change, need to update bvt results.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#5811]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CN/DB BVT fails due to transaction behavior.   

We believe we are still correct but there is a mismatch between TAE and CN/DN results.   Current proposal is to update bvt result.

**Comment by XuPeng-SH** [comment]
BVT test errors by date 2022/10/21 12:00 AM, Beijing Time

[error.txt](https://github.com/matrixorigin/matrixone/files/9836019/error.txt)

**Comment by fengttt** [comment]
Fixed by https://github.com/matrixorigin/matrixone/commit/5dc8267e3cc33ffa8c66e3f722ba65cf537027cb
