### ISSUE TITLE
[Bug]: LOAD DATA hangs with tae-CN-tae-DN config file

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5814]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):63ea9660098cea7bbcd557b8a35d932cc3d4054f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

csv file size : 24MB

{"level":"ERROR","time":"2022/10/21 10:27:21.422330 +0800","name":"cnservice","caller":"morpc/backend.go:502","msg":"read from backend failed","uuid":"cn1","remote":"127.0.0.1:22000","error":"too big body size 44469026, max is 10485760"}
{"level":"ERROR","time":"2022/10/21 10:27:21.422440 +0800","name":"cnservice","caller":"morpc/backend.go:507","msg":"read loop stopped","uuid":"cn1","remote":"127.0.0.1:22000"}
{"level":"ERROR","time":"2022/10/21 10:27:21.422550 +0800","name":"cnservice","caller":"v2@v2.0.3-0.20220926012906-f97d6dabbb6f/session.go:487","msg":"conneciton disconnected","uuid":"cn1","remote":"127.0.0.1:22000","session-id":0}
{"level":"ERROR","time":"2022/10/21 10:27:21.422554 +0800","name":"dn-service","caller":"morpc/server.go:276","msg":"write response failed","uuid":"42","dn-store":"42","name":"txn-server","request-id":0,"error":"write tcp4 127.0.0.1:22000->127.0.0.1:17056: write: connection reset by peer"}
{"level":"ERROR","time":"2022/10/21 10:27:21.422637 +0800","name":"dn-service","caller":"v2@v2.0.3-0.20220926012906-f97d6dabbb6f/session.go:487","msg":"conneciton disconnected","uuid":"42","dn-store":"42","name":"txn-server","session-id":1}

**Comment by tianyahui-python** [comment]
@domingozhang authenticated.can close issue.
