### ISSUE TITLE
[Bug]: context deadline exceeded during a query with tae-CN-tae-DN config file

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5816]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select count(*) from part;
ERROR 1105 (HY000): context deadline exceeded

**Comment by fengttt** [comment]
This is a very serious bug but I am not willing to tag it s-1.

**Comment by nnsgmsone** [comment]
same as #6240
