### ISSUE TITLE
[Bug]: unexpected end of JSON input with tae-CN-tae-DN 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#5817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select user,host,status,count(status) as count, date_sub(now(), interval 24 hour) as start_time, now() as end_time
from system.statement_info
where status in ('Success','Failed') and user <> 'internal'
 and request_at between date_sub(now(), interval 24 hour) and now()
group by status,user,host
order by user,status asc;

ERROR 1105 (HY000): unexpected end of JSON input

**Comment by jianwan0214** [comment]
the Createsql string is empty in Reslove() function  in cn_tae_dn mode

**Comment by domingozhang** [comment]
fxied
