### ISSUE TITLE
[Bug]: distributed transaction: show table returns two tables with the same name

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5835]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/197137595-9bd11f54-86cb-4fd2-8777-fdb0c34056d2.png)

**Comment by triump2020** [comment]
At now ,  this test case is completely success.   
![1666531536725](https://user-images.githubusercontent.com/63033222/197395000-c027a0d1-466f-4488-b9dd-99c957301bf8.png)

**Comment by heni02** [comment]
confirm,closed
