### ISSUE TITLE
[Bug]: distributed transaction:create table w-w confict error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5841]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/197162808-0eaeaaa7-d083-46e1-a634-066eac31ba44.png)
expected is create table success

**Comment by triump2020** [comment]
It should be caused by the difference of transaction confilct behavior from V0.5 to V0.6.   After @heni02  changing the test case , i will come back here for revisiting

**Comment by heni02** [comment]
confirm,closed
