### ISSUE TITLE
[Bug]: Load data successfully 0 rows

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#5844]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e1645777a0871f7463d84ff968f65939fd9bf258
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Running bvt with ./mo-service -launch etc/launch-tae-CN-tae-DN/launch.toml
The load data succeeded 0 rows

### Expected Behavior

mysql> create database bvt;
Query OK, 0 rows affected (0.07 sec)

mysql> use bvt;
Database changed
mysql> create table t1(
    -> col1 tinyint,
    -> col2 smallint,
    -> col3 int,
    -> col4 bigint,
    -> col5 tinyint unsigned,
    -> col6 smallint unsigned,
    -> col7 int unsigned,
    -> col8 bigint unsigned
    -> );
Query OK, 0 rows affected (0.06 sec)

mysql> load data infile '/Users/shenjiangwei/Work/code/view/matrixone/test/cases/load_data/integer_numbers_1.csv' into table t1
    -> ;
Query OK, 0 rows affected (0.04 sec)

mysql> select * from t1;
Empty set (0.03 sec)

**Comment by LeftHandCold** [comment]
Because the test data is not deleted

**Comment by LeftHandCold** [comment]
load requires an absolute path
./run.sh -n -g -p /Users/shenjiangwei/Work/code/view/matrixone/test/cases/load_data/

**Comment by fengttt** [comment]
@LeftHandCold Is this really a BVT issue?

**Comment by fengttt** [comment]
@LeftHandCold is this still an issue?   Or just test setup?   If it will not block bvt, we need to remove s-1 label.
