### ISSUE TITLE
[Bug]:  MO doesn't correctly boot 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#5850]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 48423319c6e763700fca15cfd69a37d2643476c7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO boot with this

./mo-service -launch etc/launch-tae-logservice/launch.toml, 

all data have been deleted in advance. 

MO keeps getting this in the log. cannot connect to MO. 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/4965857/197228304-6e2ac3b0-13a8-41e9-bf7b-04b5ac774ab9.png">

**Comment by xzxiong** [comment]
my startup is ok, MO is running ok with normally write and read. 
but log `no working dn stores` is keep comming.
