### ISSUE TITLE
[Bug]: cleanup cn-dn tenant bvt errors

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#5853]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

many fails

### Expected Behavior

100% pass

**Comment by aptend** [comment]
same problem in #5815

**Comment by XuPeng-SH** [comment]
done
