### ISSUE TITLE
[Bug]: table still exist event the database was dropped

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#5856]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create database db3; use db3;
create table t1 (a int);
drop database db3;
show tables;

<img width="505" alt="image" src="https://user-images.githubusercontent.com/39627130/197335177-1d20d77f-2226-42c4-9505-30348beb48ac.png">

### Expected Behavior

show tables return nothing

**Comment by nnsgmsone** [comment]
When a table t1 is created, follow logtail recived:
```
[__mo_rowid commit_time rel_id relname reldatabase reldatabase_id relpersistence relkind rel_comment rel_createsql created_time creator owner account_id partitioned viewdef]
	[0] = [54 40 4 0 0 0 0 0 0 0 0 0 0 0 0 0]
	[1] = [0 0 0 0 107 96 76 118 33 146 32 23]
	[2] = 272438
	[3] = [t1]
	[4] = [db3]
	[5] = 272436
	[6] = [p]
	[7] = []
	[8] = []
	[9] = []
	[10] = 2022-10-23 02:35:34.543211 UTC
	[11] = 1
	[12] = 0
	[13] = 0
	[14] = []
	[15] = []
```
when drop database db3, follow logtail recived:
```
 [__mo_rowid commit_time]
	[0] = [52 40 4 0 0 0 0 0 0 0 0 0 0 0 0 0]
	[1] = [0 0 0 0 193 103 19 86 54 146 32 23]
```

The reason is that after dropping databases, the tables in the database should be dropped together, but these logtail are not passed to cn. @aptend

**Comment by aptend** [comment]
yes, dn didn't send tables' deletes. When drop a database in dn, dn just set the db deleted, and won't iterate its all tables to set them deleted, otherwise it is so heavy to drop a database. So when cn polls mo_tables next time, it is hard for dn to find the deleted tables. After discussion, nnsgmsone is trying to handle this in cn

**Comment by fengttt** [comment]
> yes, dn didn't send tables' deletes. When drop a database in dn, dn just set the db deleted, and won't iterate its all tables to set them deleted, otherwise it is so heavy to drop a database. So when cn polls mo_tables next time, it is hard for dn to find the deleted tables. After discussion, nnsgmsone is trying to handle this in cn

What -- why not propagate drop database to all its objects?   This is not something we want to optimize.    We prefer a simple, correct solution for drop database.
