### ISSUE TITLE
[Bug]:  unexpected behavior when connect with custom account

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5859]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6c61cadf20d5a23821b8f5110f4011105d0e4018
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> create account test_ins admin_name 'maomao' identified by '1qazxsw2';
mysql> quit
mysql -h 127.0.0.1 -P 6001 -utest_ins:maomao -p1qazxsw2
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_catalog         |
| system             |
| system_metrics     |
| information_schema |
| mysql              |
| abc                |
+--------------------+
6 rows in set (0.00 sec)

mysql> use system;
ERROR 20402 (HY000): invalid database system
```

**Comment by daviszhen** [comment]
already known problems introduced by pr #5824 @nnsgmsone 
the database **system** of general account has the extra views or tables from **sys** account:
- rawlog           
- log_info         
- error_info       
- span_info        
- statement_info   

the database **system_metrics** of general account has the extra views or tables from **sys** account :
- views started by **process_**, **sys_**

**Comment by sukki37** [comment]
test with commit-id 92439b1d3f73552ca912de6180099821c39955fd, this problem still exists. When I try to execute some DML SQL on the `system` DB, MySQL-client loses connection.
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/77312370/200164583-082345d0-8f07-41c2-9ba9-7a4fe59710ce.png">

@daviszhen @nnsgmsone

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
cannot repro with commit-id `1f4d1bd14`
<img width="654" alt="image" src="https://user-images.githubusercontent.com/47596332/200823529-132440b7-eba9-4db1-85b7-eabcdb2c6917.png">

**Comment by sukki37** [comment]
@aressu1985 @heni02 Do we have some bvt cases on this.

**Comment by sukki37** [comment]
verified with 4666cc22b54fe7f441a7911eb2138e93ca0fd4e3
