### ISSUE TITLE
[Bug]: wrong select result

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5864]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a897eabcba3c371fed37a867bb49d352bbe3703b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/77312370/197377512-b5026ee3-996e-48c9-a277-477345e4562a.png">

### Steps to Reproduce

```SQL
use system;
select  duration, response_at, `user`, `account`, `database`, transaction_id, rows_read, bytes_scan from statement_info where request_at >= '2022-10-23 00:00:00' and request_at <= '2022-10-24 00:00:00' and account in ('test_ins') order by duration desc limit 0,10;
select  duration, response_at, `user`, `account`, `database`, transaction_id, rows_read, bytes_scan from statement_info where request_at >= '2022-10-23 00:00:00' and request_at <= '2022-10-24 00:00:00' and account in ('test_ins') order by duration,response_at desc limit 0,10;
```

**Comment by nnsgmsone** [comment]
Please confirm whether the built-in table will have this problem, if not, check whether there is a problem with the memory operation of the external table that will modify the data, if yes, please let wangjian fix it @dongdongyang33
