### ISSUE TITLE
[Bug]: [CN-DN BVT] Auto increment insert failure with ww conflict

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#5865]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /home/xupeng/workspace/github/matrixone/test/cases/auto_increment/auto_increment_columns.sql
[ROW    NUMBER]: 19
[SQL STATEMENT]: insert into t1 values (3, 'ccc');
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
w-w conflict

**Comment by nnsgmsone** [comment]
fixed by #5867
