### ISSUE TITLE
[Bug]: bvt unexpected error message

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#5878]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/39627130/197439469-bf346502-5226-43f6-9988-50b04055ea16.png">

**Comment by XuPeng-SH** [comment]
#5885

**Comment by xzxiong** [comment]
operate_catalog.sql fixed.
