### ISSUE TITLE
[Bug]: bvt show columns from "user" error

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#5884]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/39627130/197444594-c2744c6c-813e-4422-8dbc-6341aa7c2ddc.png">

**Comment by aptend** [comment]
root cause: bvt changes are not synced to distributed cases
