### ISSUE TITLE
[Bug]:  unexpected end of JSON input

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5886]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):7caa8f84a6557cf8f21c7f73386ac5860d7d7652
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/77312370/197450946-f2edf430-0aec-4047-bf66-9043204b26bc.png">

### Steps to Reproduce

```Markdown
./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
use system;
select * from statement_info limit 10;
```

**Comment by xzxiong** [comment]
access all `EXTERNAL TABLE` got ERROR: `ERROR 1105 (HY000): unexpected end of JSON input`. @jianwan0214 
- example csv file: 
[metric.csv](https://github.com/matrixorigin/matrixone/files/9849029/metric.csv)

- example schema:
```
CREATE EXTERNAL TABLE `metric_test` (
`metric_name` VARCHAR(128) DEFAULT "unknown" COMMENT 'metric name, like: sql_statement_total, server_connections, process_cpu_percent, sys_memory_used, ...',
`collecttime` DATETIME NOT NULL COMMENT 'metric data collect time',
`value` DOUBLE DEFAULT 0.0 COMMENT 'metric value',
`node` VARCHAR(36) DEFAULT "monolithic" COMMENT 'mo node uuid',
`role` VARCHAR(32) DEFAULT "monolithic" COMMENT 'mo node role, like: CN, DN, LOG',
`account` VARCHAR(128) DEFAULT "sys" COMMENT 'account name',
`type` VARCHAR(32) NOT NULL COMMENT 'sql type, like: insert, select, ...'
)  infile{"filepath"="etl:metric.csv"} fields terminated by ',' enclosed by '"' lines terminated by '\n'
```

**Comment by xzxiong** [comment]
看起来是任务参数初始化的问题？Scope 中的 Instructions 里面的 CreateSql 是空的。

**Comment by goodMan-code** [comment]
This problem has not been solved. Please use the tae-cn-tae-dn startup mode to confirm. My code is 3:30 p.m. on October 24
