### ISSUE TITLE
[Bug]: logservice should allow hostname change

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#5891]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 42b4ff74b499d76a5ab1f9f551a651c7dc620953
```

### Actual Behavior

LogService will record the hostname in data-dir and expect the hostname keeps the same. If the hostname changed, logservice would panic:

```
panic: hostname changed
``` 

### Expected Behavior

LogService should allow hostname to change, since in dynamic environment like public cloud, the compute unit (VM or container) is ephemeral while the storage (e.g. EBS) is persistent. Re-attaching the storage to another compute unit is an idiomatic way to failover in such environments, which may change the hostname and hostIP of the logservice process without compromising the data integrity. In extreme case, for example, AZ or region failure, it is possible that all VMs suffers and are replaced while the storage is still valid. LogService have to accept hostname change in such case in order to restart the cluster.

In order to check the data integrity without hostname, I propose we rely on the consistency of node-id. LogService can persist the node-id and check:

1. whether the persisted node-id is same with the node-id in config file;
2. whether the node-id conflicts with existing member in the cluster;

### Additional information

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/18556593/197471167-9bbeb650-5eba-48e6-a658-e71ff09f4722.png">

**Comment by aylei** [comment]
@zhangxu19830126 PTAL

**Comment by aylei** [comment]
It can be triaged as low priority since in Kubernetes we leverage statefulset to ensure the hostname will not be changed as long as the mounted storage is not changed.

**Comment by zhangxu19830126** [comment]
@volgariver6 I think we only need to check the cluster id, and panic if the cluster id changed.

**Comment by volgariver6** [comment]
fixed by #7321.

**Comment by fengttt** [comment]
please verify and close.

**Comment by aylei** [comment]
I will verify this fix ASAP

**Comment by aylei** [comment]
verifying this

**Comment by aylei** [comment]
completed, closing
