### ISSUE TITLE
[Bug]: system table, panic info occured

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#5892]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Query stmt is : 
show databases;
use system;
SELECT * FROM rawlog LIMIT 1;

It's return value on MO is : 
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [1] with length 1: 
runtime.goPanicIndexU
        /usr/local/go/src/runtime/panic.go:119
github.com/matrixorigin/matrixone/pkg/common/bitmap.(*Bitmap).RemoveRange
        /home/zxg/matrixone/pkg/common/bitmap/bitmap.go:227
github.com/matrixorigin/matrixone/pkg/container/nulls.RemoveRange
        /home/zxg/matrixone/pkg/container/nulls/nulls.go:202
github.com/matrixorigin/matrixone/pkg/container/vector.SetVectorLength
        /home/zxg/matrixone/pkg/container/vector/vector.go:856

**Comment by goodMan-code** [comment]
The Same Problem with :    SELECT * FROM log_info LIMIT 1;
It's also get the panic information.

**Comment by nnsgmsone** [comment]
the extern scan's batch is illegal

**Comment by goodMan-code** [comment]
I have Recheck it, can be closed. on commit commit 45c43c065b169c8dc00c9f8ed6964dac3e0a6ef8
