### ISSUE TITLE
[Bug]: mpool freed more bytes than alloc

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixone#5896]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):v0.5.1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022/10/24 03:38:15.774676 -0400 ERROR mpool/mpool.go:324 mp error:  allocations : 662
 frees : 1289
 go runtime allocations : 0
 alloc bytes : 220498172
 free bytes : 235783508
 current bytes : -15285336
 high water mark : 47122384

github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).destroy
        /home/go/go/matrixone/pkg/common/mpool/mpool.go:324
github.com/matrixorigin/matrixone/pkg/common/mpool.DeleteMPool
        /home/go/go/matrixone/pkg/common/mpool/mpool.go:428
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).Dispose
        /home/go/go/matrixone/pkg/frontend/session.go:131
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Quit.func1
        /home/go/go/matrixone/pkg/frontend/routine.go:149
sync.(*Once).doSlow
        /home/go/go/src/sync/once.go:74
sync.(*Once).Do
        /home/go/go/src/sync/once.go:65
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Quit
        /home/go/go/matrixone/pkg/frontend/routine.go:147
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed
        /home/go/go/matrixone/pkg/frontend/routine_manager.go:98
github.com/fagongzi/goetty/v2.(*baseIO).Close
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220926012906-f97d6dabbb6f/session.go:370
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220926012906-f97d6dabbb6f/application.go:296
github.com/fagongzi/goetty/v2.(*server).doStart.func2
        /root/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20220926012906-f97d6dabbb6f/application.go:304

**Comment by nnsgmsone** [comment]
@m-schen please take a look.

**Comment by m-schen** [comment]
@yinmh please check whether the new main branch has this bug or not.
and if bug exist, give me the sql case or other information

**Comment by m-schen** [comment]
Please test the code after the commit f985e56298de46ede21b76dde01f2bcbdf5161de

**Comment by aressu1985** [comment]
commit fc685762b89cd931bdac2c09b93f6bab4ceeb6d5

has no this problem after test
