### ISSUE TITLE
[Bug]: bvt load_data error

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#5917]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/39627130/197540438-5dafe2fc-afb2-45b6-a135-d45a07acc609.png">

### Steps to Reproduce

```Markdown
./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
```

**Comment by fengttt** [comment]
reverted.  now left to @tianyahui-python to find out the root cause and resubmit.

**Comment by tianyahui-python** [comment]
The problem has been solved. please close issue. @XuPeng-SH
