### ISSUE TITLE
[Bug]: CN/DN BVT with blocklist.   PROGRESS.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#5924]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/commit/1a37f19965fa2f3b08d74e1b34bd7e4eeb86b8a3
Has a launch setting.

Need to pass BVT on this one.

**Comment by nnsgmsone** [comment]
Please fix the bug of blockio.BlockRead first @aptend

**Comment by fengttt** [comment]
Please update this issue with current pass rate and blocking issue.

**Comment by XuPeng-SH** [comment]
By 2022/10/28 00:00:00 AM, Beijing Time
> Disable Tenant Cases
> 6-second flush interval

**100%**

#6044 will cause `tenant` cases panic, and it will be fixed in 2022/10/28.

**Comment by aptend** [comment]
By 2022/10/29 22:20:00 AM, Beijing Time
> 6-second flush interval

98%

[error.txt](https://github.com/matrixorigin/matrixone/files/9889117/error.txt)

issue: 
code causes #6044 has been disabled by #6055
#6068 is tracking errors in tpch directory, about cn data cache
#6050 is tracking errors in tenant directory, about auto increment column

**Comment by nnsgmsone** [comment]
Already done. @fengttt

**Comment by fengttt** [comment]
Already done 5 days ago :)   Is this already done again today after open blocklist?

**Comment by fengttt** [comment]
Did we turn on CI?

**Comment by fengttt** [comment]
Now CN/DN CI tested with flush.
