### ISSUE TITLE
[Bug]: BlockRead not use mpool

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#5937]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

blockio.Read not use mpool now?

**Comment by LeftHandCold** [comment]
After communicating with @nnsgmsone , it can be adjusted to s1

**Comment by LeftHandCold** [comment]
The root cause is that vector does not provide an interface for serialization and deserialization based on mpool

**Comment by LeftHandCold** [comment]
Should be implemented in 0.7

**Comment by LeftHandCold** [comment]
I didn't work on it today

**Comment by LeftHandCold** [comment]
@nnsgmsone @zengyan1 After the vector is refactored, it will be fixed
