### ISSUE TITLE
[Bug]: distributed transaction load data rollback  error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5941]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/197692765-3a89a94b-e3b2-44b8-8dff-4e6f870571bc.png)

### Steps to Reproduce

```Markdown
create table atomic_table_3(col1 tinyint,col2 smallint,col3 int,clo4 bigint,col5 tinyint unsigned,col6 smallint unsigned,col7 int unsigned,col8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 text,primary key(col1))partition by hash(col1)partitions 4;
begin;
load data infile '/Users/heni/test_data/pt_table_data.csv' into table  atomic_table_3;
select * from atomic_table_3;
update atomic_table_3 set col1=400;
rollback;
select * from atomic_table_3;


pt_table_data.csv：
-62,5807,-1889972806,7769629822818484334,154,8113,2658450361,14999475422109240954,3.4365,5.5590,"N?OPQR.STU-_+=Zabcdefghigklmnopqrstuvwxyz01234567",4149-04-30,5732-08-07 00:00:00,1975-09-09 23:59:59,true,602.53,"I,G;KL/MN?OPQR.STU-_+=Zabcdefghi","HI,G;KL/MN?OPQR.STU-_+=Za","+=Zab","G;KL/MN?OPQR.STU-_+=Zabcdefghigkl"
91,19514,-179559641,1234138289513302348,122,44115,625429347,6204822205090614210,7.2914,6.5836,"R.STU-_+=Zabcdefghigklmno",2865-02-22,9976-06-04 00:00:00,1985-01-12 23:59:59,false,878.09,"HI,G;KL/MN?OPQR.STU-_+=Zabcd","QR.STU-_+=Zabcdefghigklmnopqrstu","R.STU-_+=Zabcdefghigklmnopqrstuvw","-_+=Zabcdefghigklmnopqr"
```

**Comment by reusee** [comment]
I'll work on this later.

**Comment by reusee** [comment]
I think it's related to transaction auto commit/rollback in frontend

**Comment by reusee** [comment]
will check this later

**Comment by reusee** [comment]
will check this later

**Comment by reusee** [comment]
looking into it.

**Comment by reusee** [comment]
I don't know what's happening. Maybe some special treatment of auto commit/rollback in the frontend session management?

**Comment by reusee** [comment]
will investigate this later

**Comment by reusee** [comment]
I guess I found the root cause.
The load operator commits internally, discarding the following rollback statement: https://github.com/matrixorigin/matrixone/blob/c6d26e186a9b7e59282e3f846d448febec3ecf47/pkg/sql/colexec/insert/insert.go#L168
Re-assigning to @jianwan0214

**Comment by heni02** [comment]
confirm ,closed
commit id:0ea4925d5cfc6922c8c602c61aa28a83632ca0a7
![image](https://user-images.githubusercontent.com/113406637/217169449-ad9c1987-7e61-45da-8bbd-e43bef3f5157.png)
