### ISSUE TITLE
[Bug]: jdbc blob type should use charset(63)

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#5949]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a blob);
insert into t1 values('a');
mysql> select * from t1;
+------+
| a    |
+------+
| a    |
+------+
1 row in set (0.09 sec)

### Expected Behavior

create table t1(a blob);
insert into t1 values('a');
mysql> select * from t1;
+------+
| a    |
+------+
| 0x61    |
+------+
1 row in set (0.09 sec)

**Comment by tianyahui-python** [comment]
commit id: 9a457bc5e8f956377739d67f9703828bd8b7e4f4
<img width="639" alt="截屏2022-10-30 00 14 43" src="https://user-images.githubusercontent.com/39303074/198841983-514cf335-e114-4d88-b8b4-4d7772f2e586.png">

**Comment by tianyahui-python** [comment]
@JackTan25 issue can close, only issue owner is can close issue.

**Comment by JackTan25** [comment]
> @JackTan25 issue can close, only issue owner is can close issue.

ok. sorry for that
