### ISSUE TITLE
[Bug]: distributed transaction: insert into select duplicate data not reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5950]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cn-dn results failed:
![image](https://user-images.githubusercontent.com/113406637/197728818-ffcb8527-67c2-41a3-91e9-8b5f91ec93b3.png)

tae transaction results correct:
![image](https://user-images.githubusercontent.com/113406637/197728943-ee595049-e1d8-4ec5-a972-e2d1367b9dee.png)

### Steps to Reproduce

```Markdown
create table dis_table_02(a int not null auto_increment,b varchar(25),c datetime,primary key(a),key bstr (b),key cdate (c) );
insert into dis_table_02(b,c) values ('aaaa','2020-09-08');
insert into dis_table_02(b,c) values ('aaaa','2020-09-08');
create table dis_table_03(b varchar(25) primary key,c datetime);
begin ;
insert into dis_table_03 select b,c from dis_table_02;
select * from dis_table_03;
commit;
```

**Comment by fengttt** [comment]
@reusee Please make an assessment -- if CN primary key check can be done soon, resolve this together/after the work.   If CN primary check takes long, please disable this test case, and reenable after your work.

**Comment by reusee** [comment]
fixed in #6059

**Comment by reusee** [comment]
@heni02 Please re-check

**Comment by reusee** [comment]
@heni02 Please re-run the test and check if it's fixed. If fixed, please close this issue.

**Comment by heni02** [comment]
confirm,closed
commit id:b8300cd7c47af95626d64b3dea415d5d785c92a5
![image](https://user-images.githubusercontent.com/113406637/201814070-dc4a546b-9493-4ac4-b8b2-dd5d0fcb5ab6.png)

**Comment by heni02** [comment]
@reusee plz remove bvt issue tag

**Comment by reusee** [comment]
PR sent.
https://github.com/matrixorigin/matrixone/pull/6614

**Comment by reusee** [comment]
@aressu1985 Please review https://github.com/matrixorigin/matrixone/pull/6614

**Comment by reusee** [comment]
waiting for review

**Comment by reusee** [comment]
waiting for review

**Comment by florashi181** [comment]
@heni02  pls have a test

**Comment by heni02** [comment]
confirm,closed

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by heni02** [comment]
@reusee plz remove main bvt issue tag

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by heni02** [comment]
wait pr merge
