### ISSUE TITLE
[Bug]: unique Key at INSERT statement  error

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#5955]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In MO:
mysql> CREATE TABLE t3 (
    ->   pk INT PRIMARY KEY,
    ->   int_key INT,
    ->   varchar_key VARCHAR(5),
    ->   varchar_nokey VARCHAR(5),
    ->   UNIQUE KEY(varchar_key)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t3 VALUES (9, 7,NULL,NULL), (10,8,'p' ,'p');
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/sql/util.compactUniqueKeyBatch
        /home/yiming/workspace/matrixone/pkg/sql/util/index_util.go:92
github.com/matrixorigin/matrixone/pkg/sql/util.BuildUniqueKeyBatch
        /home/yiming/workspace/matrixone/pkg/

or as this : 
mysql> CREATE TABLE t1 (
    ->   pk INT PRIMARY KEY,
    ->   int_key INT,
    ->   varchar_key VARCHAR(5) UNIQUE,
    ->   varchar_nokey VARCHAR(5)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (9, 7,NULL,NULL), (10,8,'p' ,'p');
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/sql/util.compactUniqueKeyBatch
        /home/yiming/workspace/matrixone/pkg/sql/util/index_util.go:92
github.com/matrixorigin/matrixone/pkg/sql/util.BuildUniqueKeyBatch
        /home/yiming/workspace/matrixone/pkg/sql/util/index_util.go:80
github.com/matrixorigin/matrixone/pkg/

### Expected Behavior

mysql:

mysql> CREATE TABLE t3 (
    ->   pk INT PRIMARY KEY,
    ->   int_key INT,
    ->   varchar_key VARCHAR(5),
    ->   varchar_nokey VARCHAR(5),
    ->   UNIQUE KEY(varchar_key)
    -> );
mysql> INSERT INTO t3 VALUES (9, 7,NULL,NULL), (10,8,'p' ,'p');
Query OK, 2 rows affected (0.00 sec)

mysql> CREATE TABLE t1 (
    ->   pk INT PRIMARY KEY,
    ->   int_key INT,
    ->   varchar_key VARCHAR(5) UNIQUE,
    ->   varchar_nokey VARCHAR(5)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (9, 7,NULL,NULL), (10,8,'p' ,'p');
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select * from t1;
+----+---------+-------------+---------------+
| pk | int_key | varchar_key | varchar_nokey |
+----+---------+-------------+---------------+
|  9 |       7 | NULL        | NULL          |
| 10 |       8 | p           | p             |
+----+---------+-------------+---------------+
2 rows in set (0.00 sec)

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
most of the code is complete, now do some test and fix bug.

**Comment by bbbearxyz** [comment]
The code is finish and wait the pr review.

**Comment by heni02** [comment]
still problems, waiting for verification after repair
confirm commit id：60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e

**Comment by heni02** [comment]
confirm,closed
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210354492-b5dcc4d8-30e9-4a49-8d4a-e1cfe9ceb114.png)
![image](https://user-images.githubusercontent.com/113406637/210354549-63467eb4-dd31-42b8-a3b4-db4e9bf38b71.png)

**Comment by heni02** [comment]
@aressu1985 plz closed this issue
