### ISSUE TITLE
[Bug]: permission cache

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#5957]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

no cache for privilege check

### Expected Behavior

add cache for privilege check

**Comment by fengttt** [comment]
is this done?

**Comment by daviszhen** [comment]
> is this done?

No。做不到跨session的cache。

**Comment by florashi181** [comment]
@daviszhen u can close it.

**Comment by daviszhen** [comment]
0.8 不做
