### ISSUE TITLE
[Bug]: No such table for MemoryStorage

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#5969]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create database test;use test;
Query OK, 0 rows affected (0.11 sec)

Database changed
mysql> create table t1(a int);
Query OK, 0 rows affected (0.31 sec)

mysql> delete from t1;
ERROR 20403 (HY000): no such table test.t1

### Expected Behavior

mysql> create database test;use test;
Query OK, 0 rows affected (0.11 sec)

Database changed
mysql> create table t1(a int);
Query OK, 0 rows affected (0.31 sec)

mysql> delete from t1;
Query OK, 0 rows affected (0.23 sec)

**Comment by sukki37** [comment]
@JackTan25 any updates?

**Comment by JackTan25** [comment]
> @JackTan25 any updates?

has fixed
