### ISSUE TITLE
ERROR 1105 (HY000): unknown error:parser parse failed.error:line 1 column 18 near "show"

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#597]
#### Can be reproduced ?
Yes

#### Steps:
1. create database show;
2. drop database show;

#### Expected behavior:
drop db succeeded

#### Actual behavior:
failed to drop

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by iamlinjunhong** [comment]
Must not support, because 'show' is the reserved keyword in mysql syntax.

**Comment by lignay** [comment]
It works well if create table named "show" between backquotes.
