### ISSUE TITLE
[Bug]:  mybatis demo bug

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#5971]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ac617cc4ab25eb04573ba9690cc1480b5fa6ded8
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Connect to MO with a MyBatis spring boot project, create table failed with 
http://localhost:8080/test/create

<img width="502" alt="image" src="https://user-images.githubusercontent.com/4965857/197952488-73bdc5bd-78d7-4ad4-a295-cb5b9b60af08.png">

The MO log showed prepare, execute and deallocate are executed.

```
2022/10/26 14:25:13.668954 +0800 INFO frontend/mysql_cmd_executor.go:2775 query trace {"connection_id": 1129, "query": "prepare __mo_stmt_id_1 from DROP TABLE IF EXISTS user;\n        CREATE TABLE user (\n            `id` int(11) NOT NULL AUTO_INCREMENT,\n            `username` varchar(255) DEFAULT NULL,\n            `password` varchar(255) DEFAULT NULL,\n            `address` varchar(255) DEFAULT NULL,\n            PRIMARY KEY (`id`)\n        );"}
2022/10/26 14:25:13.713202 +0800 INFO frontend/mysql_cmd_executor.go:2849 query trace {"connection_id": 1129, "query": "execute __mo_stmt_id_1", "vars": ""}
2022/10/26 14:25:13.726732 +0800 INFO frontend/mysql_cmd_executor.go:2803 query trace {"connection_id": 1129, "qu
ery": "deallocate prepare __mo_stmt_id_1"}
```

[MyBatisDemo.zip](https://github.com/matrixorigin/matrixone/files/9866810/MyBatisDemo.zip)

**Comment by YANGGMM** [comment]
If a prepare statements constains more than one  sql stmts
in mo:
mysql>  prepare __mo_stmt_id_1 from "DROP TABLE IF EXISTS user; CREATE TABLE user (a int)";
ERROR 20301 (HY000): invalid input: cannot prepare multi statements

in mysql:prepare __mo_stmt_id_1 from "DROP TABLE IF EXISTS user; CREATE TABLE user (a int)";
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE user (a int)' at line 1
