### ISSUE TITLE
[Bug]: mo crashed during e2e test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5974]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/77312370/197960192-cda6b753-7d23-4fa6-a88d-7fe295d2ef86.png">

### Additional information

refer link: https://github.com/matrixorigin/matrixone/actions/runs/3326339207/jobs/5499961162

**Comment by nnsgmsone** [comment]
The reason for this is because frontend does not handle concurrency well, and this is looking forward @daviszhen  to solving it.

**Comment by fengttt** [comment]
I think this is initialization only.   after zhang xu serialized init code, this is not a problem any more.   Is this correct?

I plan to take this off S-1

**Comment by daviszhen** [comment]
> I think this is initialization only. after zhang xu serialized init code, this is not a problem any more. Is this correct?
> 
> I plan to take this off S-1

after the pr 5976, it does not appear again. it is fixed.

**Comment by sukki37** [comment]
observed the recent e2e, not reproduced
