### ISSUE TITLE
[Bug]: delete from table panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#5988]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

and another problem is that the error message is incorrect
![image](https://user-images.githubusercontent.com/113406637/198009221-d9a40daa-c394-4468-8f57-cc633a57dcde.png)

**Comment by iamlinjunhong** [comment]
@heni02 How to reproduce this situation, please describe clearly

**Comment by heni02** [comment]
delete from table can be reproduced

**Comment by iamlinjunhong** [comment]
why I can not reproduce ? what is dll? what is the configuration? please describe clearly!!! @aressu1985 @heni02 
<img width="1241" alt="截屏2022-10-28 下午3 58 35" src="https://user-images.githubusercontent.com/49111204/198535434-25e3e08a-de08-4fff-ba5b-15c7a8cd10c8.png">

**Comment by heni02** [comment]
I thought it was caused by not taking where. If you have any questions, you can contact me directly and communicate quickly！thx

commit id:55398afae19b40f2e689994185a1d2b7dc07868c
create table dis_table_02(a int not null auto_increment,b varchar(25) not null,c datetime,primary key(a),key bstr (b),key cdate (c) );
insert into dis_table_02(b,c) values ('aaaa','2020-09-08');
insert into dis_table_02(b,c) values ('aaaa','2020-09-08');
delete from dis_table_02;

**Comment by iamlinjunhong** [comment]
Solved in new code

**Comment by heni02** [comment]
comfirm,closed
commit id: e983be5ad02b14da54754be5e64410446819f421
<img width="1497" alt="企业微信截图_bb2b7280-9155-421d-85f6-fdaeddf4553f" src="https://user-images.githubusercontent.com/113406637/199950202-7b82d0f9-afd7-45d8-8983-52439655884f.png">
