### ISSUE TITLE
[Bug]: drop database not exists db report incorrect

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6019]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/198223918-bfed5b5a-8be6-40f7-8c16-c43aedececc1.png)

**Comment by iamlinjunhong** [comment]
@heni02  @aressu1985  How to reproduce? Please give a clear context

**Comment by heni02** [comment]
The title description is clear. Delete the non-existent db and modify the error message
commit id: 9d7107e4d9541a1c91560d0e3de6566019ee734d
Refer to MySQL error message：
<img width="728" alt="企业微信截图_06e622f8-9109-4cef-88b5-6f88537bae2a" src="https://user-images.githubusercontent.com/113406637/198868763-bf5c189c-ec04-419e-88ed-fe16e004e976.png">

**Comment by heni02** [comment]
comfirm,closed
commit id:249f56400184a0828afdc615c8b5d75e8c57cecc
![image](https://user-images.githubusercontent.com/113406637/199639664-4b8c1d52-5962-4845-8e2b-28f0538d9f21.png)
