### ISSUE TITLE
[Bug]: unique index key  can be insert duplicate value

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6028]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/198253630-24b30ba5-bab2-4ade-88bd-19fe3fe64827.png)

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
most of the code is complete, now do some test and fix bug.

**Comment by bbbearxyz** [comment]
will solve it after unique index pr is merge

**Comment by heni02** [comment]
still problems, waiting for verification after repair
![image](https://user-images.githubusercontent.com/113406637/209923570-79a929fa-6896-445f-90ce-a65dd1207a27.png)
confirm commit id：60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e

**Comment by heni02** [comment]
confirm,closed
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210353836-ee864d95-d1ce-4c32-b8ab-48d5457adb51.png)

**Comment by heni02** [comment]
@bbbearxyz plz remove bvt tag

**Comment by sukki37** [comment]
@bbbearxyz you should remove all tags like `-- @bvt:issue#6028` in bvt test case. like https://github.com/matrixorigin/matrixone/blob/816847fc5e48316cd246a36e9b38450ce70f9c73/test/distributed/cases/transaction/isolation_2.sql#L265

**Comment by bbbearxyz** [comment]
ok, i will remove all the tags.

**Comment by bbbearxyz** [comment]
i already move, please confrim it.
