### ISSUE TITLE
[Bug]: system table INFORMATION_SCHEMA.PROCESSLIST，can not desc or select

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#6036]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

use information_schema;
desc PROCESSLIST;
It's return value : 
ERROR 20303 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 16 near " PROCESSLIST";

select * from PROCESSLIST limit 2;
It's return value : 
ERROR 20303 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 25 near " PROCESSLIST limit 2";

**Comment by goodMan-code** [comment]
p0

**Comment by qingxinhome** [comment]
information_ For the PROCESSLIST table under the schema database, the table name of the table is a system keyword, so you need to add back quotes when referencing the table, for example:
desc `PROCESSLIST`;
select * from `PROCESSLIST` limit 2;
@goodMan-code @daviszhen

**Comment by goodMan-code** [comment]
Recheck it, done, can be closed. 2022-11-2  14:15   GMT + 8
