### ISSUE TITLE
[Bug]: distributed transaction:show database/table result have same results

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6041]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

/matrixone/test/distributed/cases/accesscontrol/create_account.sql row:102,104
![image](https://user-images.githubusercontent.com/113406637/198293682-a63217b1-3752-44d6-a563-632f32da49f5.png)

**Comment by nnsgmsone** [comment]
Please give me your test sql.  @heni02

**Comment by heni02** [comment]
confirm,closed
commit id:b8300cd7c47af95626d64b3dea415d5d785c92a5
![image](https://user-images.githubusercontent.com/113406637/201816030-f0457299-17bb-4201-a72e-4f61db1812a5.png)
![image](https://user-images.githubusercontent.com/113406637/201816464-a9896998-1aa0-4b8c-922f-ab5ecdae3042.png)
