### ISSUE TITLE
[Bug]: distributed transaction: after drop role or user system table system table can be queried 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6043]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/198297362-d3c5782f-a319-49e4-88d1-1443644c161a.png)

**Comment by nnsgmsone** [comment]
Please give me your test sql. @heni02

**Comment by heni02** [comment]
root or dump login:create account grant_account01 admin_name='admin' identified by '123456';

grant_account01 login: mysql -h 127.0.0.1 -u grant_account01:admin -P6001 -p123456
create user if not exists user_grant_2 identified by '123456';
create role if not exists 'role_account_priv_1';
grant  create user, drop user, alter user, create role, drop role, create database,drop database,show databases,connect,manage grants on account *  to role_account_priv_1 with grant option;

grant_account01 login: mysql -h 127.0.0.1 -u grant_account01:user_grant_2:role_account_priv_1 -P6001 -p123456
create role if not exists role_test_01;
create user user_test_2 identified by '123456';
drop role role_test_01;
select role_name from mo_catalog.mo_role where role_name='role_test_01';
drop user user_test_2;
select user_name,authentication_string from mo_catalog.mo_user where user_name='user_test_2';

**Comment by fengttt** [comment]
@nnsgmsone done?

**Comment by nnsgmsone** [comment]
I immediately asked yuanning to look at this question 。。。。

**Comment by nnsgmsone** [comment]
The problem that account information is lost due to wrong use of context.

**Comment by daviszhen** [comment]
the context.TODO has been remove at #6283

**Comment by heni02** [comment]
confirm,closed
commit id:6e725b584955c85eeb2cb4526779a4d4730df2ad

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
