### ISSUE TITLE
[Bug]: create account key name not reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6053]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/198482796-1de8aa74-49d4-415d-a48a-ddf72cc00ecf.png)

ci bvt log：https://github.com/matrixorigin/matrixone/actions/runs/3337833413/jobs/5524692516

**Comment by iamlinjunhong** [comment]
In mysql, 'account' is non reserved keyword:
<img width="898" alt="截屏2022-10-31 下午2 14 32" src="https://user-images.githubusercontent.com/49111204/198943327-0c752141-b7d3-4dae-9717-38a6fb4eed25.png">

**Comment by heni02** [comment]
@iamlinjunhong create account account admin_name 'root' identified by '123456'

**Comment by iamlinjunhong** [comment]
An error was reported because of a bug.

**Comment by heni02** [comment]
confirm,it is not bug, closed

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
