### ISSUE TITLE
[Bug]: accountadmin privs results incorrect

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6054]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/198486977-9c36afc1-09fd-4288-aa92-a6c43ffba6fb.png)
![image](https://user-images.githubusercontent.com/113406637/198487087-05947811-fea3-4cc1-89f3-3f2d0e4a3c9e.png)

### Steps to Reproduce
create account account ADMIN_NAME 'root' IDENTIFIED BY '123456';
account login
select role_name,obj_type,privilege_name,privilege_level from mo_role_privs;

**Comment by heni02** [comment]
ci bvt log:https://github.com/matrixorigin/matrixone/actions/runs/3337833413/jobs/5524692516

**Comment by daviszhen** [comment]
it was fixed.
