### ISSUE TITLE
[Bug]: modump only dumps DDL from a database

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6056]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d8df2a16a6751044cd8ccab91fd7903539f09c0b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

config file : etc/launch-tae-CN-tae-DN/launch.toml 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/88298673/198499038-cb327f1e-4a17-4a65-a294-8dbbd820b2d4.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/88298673/198498812-1ee99a40-fdce-4dac-a85b-92467176550f.png">

**Comment by mooleetzi** [comment]
fixed, please see https://github.com/mooleetzi/mo-docs/blob/main/dump.md.
modump statement will be removed soon.

**Comment by domingozhang** [comment]
fixed
