### ISSUE TITLE
[Bug]: Show database error after login  create an account

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6086]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
ci bvt tae start mode, system has two rows:
![image](https://user-images.githubusercontent.com/113406637/198821854-acc24a72-6e68-4f53-ac90-896c804339ae.png)

### Steps to Reproduce

```Markdown
commit id:9a457bc5e8f956377739d67f9703828bd8b7e4f4
https://github.com/matrixorigin/matrixone/actions/runs/3350345698/jobs/5551087761
```

**Comment by daviszhen** [comment]
`invalid database system` has been fixed.

But, it has already known problems introduced by pr #5824 @nnsgmsone 
the database **system** of general account has the extra views or tables from **sys** account:
- rawlog           
- log_info         
- error_info       
- span_info        
- statement_info   

the database **system_metrics** of general account has the extra views or tables from **sys** account :
- views started by **process_**, **sys_**

**Comment by heni02** [comment]
root or dump login execute sql:create account account1 ADMIN_NAME 'admin' IDENTIFIED BY '123456';
account_1 login:mysql -h 127.0.0.1 -u account1:admin -P6001 -p123456
show databases
