### ISSUE TITLE
[Bug]: show columns from mo_tables get wrong result

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#6088]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> use mo_catalog;
Database changed
mysql> show columns from mo_tables;
ERROR 1105 (HY000): EOF

**Comment by YANGGMM** [comment]
mysql> show columns from mo_tables;
+----------------+-----------------+------+------+---------+-------+---------+
| Field          | Type            | Null | Key  | Default | Extra | Comment |
+----------------+-----------------+------+------+---------+-------+---------+
| rel_id         | BIGINT UNSIGNED | NO   | PRI  | NULL    |       |         |
| relname        | VARCHAR         | YES  |      | NULL    |       |         |
| reldatabase    | VARCHAR         | YES  |      | NULL    |       |         |
| reldatabase_id | BIGINT UNSIGNED | YES  |      | NULL    |       |         |
| relpersistence | VARCHAR         | YES  |      | NULL    |       |         |
| relkind        | VARCHAR         | YES  |      | NULL    |       |         |
| rel_comment    | VARCHAR         | YES  |      | NULL    |       |         |
| rel_createsql  | VARCHAR         | YES  |      | NULL    |       |         |
| created_time   | TIMESTAMP       | YES  |      | NULL    |       |         |
| creator        | INT UNSIGNED    | YES  |      | NULL    |       |         |
| owner          | INT UNSIGNED    | YES  |      | NULL    |       |         |
| account_id     | INT UNSIGNED    | YES  |      | NULL    |       |         |
| partitioned    | BLOB            | YES  |      | NULL    |       |         |
| viewdef        | BLOB            | YES  |      | NULL    |       |         |
+----------------+-----------------+------+------+---------+-------+---------+
