### ISSUE TITLE
[Bug]: insert into t select * from t; stmt run failed.

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#6096]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

source source.sql
Query OK, 0 rows affected (0.02 sec)

Database changed
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.07 sec)

Query OK, 0 rows affected (0.07 sec)

mysql> select count(*) from t2;
+----------+
| count(*) |
+----------+
|      100 |
+----------+
1 row in set (0.01 sec)

mysql> insert into t2 select * from t2;
Query OK, 0 rows affected (0.06 sec)

mysql> insert into t2 select * from t2;
Query OK, 0 rows affected (0.06 sec)

mysql> insert into t2 select * from t2;
Query OK, 0 rows affected (0.07 sec)

mysql> select count(*) from t2;
+----------+
| count(*) |
+----------+
|      800 |
+----------+
1 row in set (0.00 sec)

mysql> insert into t2 select * from t2;
Query OK, 0 rows affected (0.06 sec)

mysql> select count(*) from t2;
+----------+
| count(*) |
+----------+
|     1600 |
+----------+
1 row in set (0.00 sec)

mysql> insert into t2 select * from t2;
Query OK, 0 rows affected (0.11 sec)

mysql> select count(*) from t2;
+----------+
| count(*) |
+----------+
|     3200 |
+----------+
1 row in set (0.00 sec)

mysql> insert into t2 select * from t2;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:6001' (61)
ERROR: 
Can't connect to the server

**Comment by volgariver6** [comment]
Problem is that data size is larger than RPC max body size. We should change the rpc body size.
