### ISSUE TITLE
[Bug]: Integration test failure

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#6101]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2022/10/30 16:37:02.563216 +0800 ERROR frontend/util.go:476 query trace status {"connection_id": 3228, "statement": "create table if not exists mo_task.sys_async_task (task_id int primary key auto_increment, task_metadata_id varchar(50) unique not null, task_metadata_executor int, task_metadata_context blob, task_metadata_option varchar(1000), task_parent_id varchar(50), task_status int, task_runner varchar(50), task_epoch int, last_heartbeat bigint, result_code int null, error_msg varchar(1000) null, create_at bigint, end_at bigint)", "status": "fail", "error": "ExpectedEOB"}

2022/10/30 16:39:59.917300 +0800 ERROR frontend/util.go:476 query trace status {"connection_id": 5272, "statement": "create database if not exists mo_task", "status": "fail", "error": "tae data: duplicate"}

### Steps to Reproduce

```Markdown
run Integration test in pkg/tests/service and pkg/tests/txn
```

**Comment by fengttt** [comment]
@zhangxu19830126 I think we can close this one.
