### ISSUE TITLE
[Bug]: show create external table error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6102]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):9d7107e4d9541a1c91560d0e3de6566019ee734d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

show create external table error:
![image](https://user-images.githubusercontent.com/113406637/198873018-d686aa03-1133-44b5-b3ce-422c7355fbfa.png)

### Steps to Reproduce

```Markdown
create external table ex_table_1(num_col1 tinyint,num_col2 smallint,num_col3 int,num_col4 bigint,num_col5 tinyint unsigned,num_col6 smallint unsigned,num_col7 int unsigned,num_col8 bigint unsigned ,num_col9 float(5,3),num_col10 double(6,5),num_col11 decimal(38,19)) infile{"filepath"='$resources/external_table_file/ex_table_number.csv'} fields terminated by ',' enclosed by '\"' lines terminated by '\n';
show create table ex_table_1;
```

**Comment by mooleetzi** [comment]
what is expected behavior

**Comment by heni02** [comment]
confirm,closed
commit id: 249f56400184a0828afdc615c8b5d75e8c57cecc
![image](https://user-images.githubusercontent.com/113406637/199637565-2b08e99a-06d3-468d-8489-9dcbe45e2f9b.png)
