### ISSUE TITLE
[Feature Request]: mo_debug('dn', 'flush', 'dbname.tablename')

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6107]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Add a few dn debug functions.  at least flush, compact, checkpoint functions.

select mo_debug('dn', 'flush', 'dbname.tablename');

**Comment by XuPeng-SH** [comment]
#6104

**Comment by fengttt** [comment]
wait for 'compact' and 'checkpoint'.    Lower this from S-1 to S0.

**Comment by LeftHandCold** [comment]
No time to do it now

**Comment by fengttt** [comment]
Make code debuggable and testable is top priority.

**Comment by LeftHandCold** [comment]
I'm sorry @fengttt , I didn't see your comment yesterday, so I assigned it to you. I thought it was done, but when I saw your comment later, I realized that there was still work to be done, so I wrote a comment saying that I have no time to do it yet. , but I forgot to reassign to me

**Comment by LeftHandCold** [comment]
Haven't had time to start this job these days

**Comment by XuPeng-SH** [comment]
we'll add more command in mo_ctl later

**Comment by XuPeng-SH** [comment]
I suggest closing this issue and creating a new issue to support more commands

**Comment by LeftHandCold** [comment]
I didn't work on it today

**Comment by LeftHandCold** [comment]
I didn't work on it today

**Comment by LeftHandCold** [comment]
I didn't work on it today

**Comment by LeftHandCold** [comment]
I didn't work on it today

**Comment by LeftHandCold** [comment]
I didn't work on it today
