### ISSUE TITLE
Cannot query anything in a table with some size of data when instance just start.

### ISSUE THREAD

**Issue by MOOS2021** [matrixorigin/matrixone#611]
#### Steps:
1. start instance and log in
2. Query a small table and the result is correct
MySQL [test]> select * from test;
+------+
| a    |
+------+
|    1 |
|    1 |
+------+
2 rows in set (0.006 sec)

3. Query a table with bigger size of data and cannot get any thing.
MySQL [test]> select count(*) from t2;
Empty set (9.983 sec)

MySQL [test]> select count(*) from t2;
Empty set (9.993 sec)

MySQL [test]> select count(*) from t2;
Empty set (9.962 sec)

4. Wait about 1 min and then the query result is corrent.
MySQL [test]> select count(*) from t2;
+----------+
| count(*) |
+----------+
|     1199 |
+----------+
1 row in set (0.007 sec)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 7c2d58874b57ed4f567015196121b6e2df8a889c
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
The refactoring of appliedIndex has been completed in version 0.2.0, so theoretically this problem no longer exists and can be closed when the test is over
