### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JinHai-CN** [matrixorigin/matrixone#613]
| Domain             | Sub-Domain               | Feature                                                      | Status | Release | Comments |
| ------------------ | ------------------------ | ------------------------------------------------------------ | ------ | ------- | -------- |
| SQL Engine         | Parser                   | Introduce new parser to support multiple SQL dialects        | Ongoing |         |          |
| SQL Engine         | Planner                  | AST rewriter                                                 | Planning |         |          |
| SQL Engine         | Planner                  | Rule based optimizer                                         | Planning |         |          |
| SQL Engine         | Planner                  | Cost based optimizer                                         | Planning |         |          |
| SQL Engine         | pipeline executor        | Enhance the execution pipeline                               | Planning |         |          |
| SQL Engine         | vectorized processor     | Incremental view maintenance                                 | Planning |         |          |
| SQL Engine         | vectorized processor     | Improve operations performance of HASH function                  | Ongoing |         |          |
| SQL Engine         | vectorized processor     | Advanced window function                                     |Planning|         |          |
| SQL Engine         | cache                    | Multiple version query data cache management                 |Planning|         |          |
| SQL Engine         | IR generator             | Translate Python function into IR.                           |Planning|         |          |
| Cluster Management | Prophet                  | Redesign prophet to resilience and lock-free.                |Planning|         |          |
| Cluster Management | Prophet                  | Support job / task orchestration and co-location.            |Planning|         |          |
| Cluster Management | Transaction Manager      | Support snapshot isolation level transaction for multiple engines and cross engines |Planning|         |          |
| Cluster Management | Replicated State Machine | Improve current multiple-RAFT store                          |Ongoing|         |          |
| Cluster Management | Replicated State Machine | Introducing cutting-edge replicated state machine protocol   |Planning|         |          |
| Storage            | Column Store             | Enhance data table management                                        |Planning|         |          |
| Storage            | Column Store             | Enhance local metadata management                                    |Planning|         |          |
| Storage            | Column Store             | Local transaction management                                 |Planning|         |          |
| Storage            | Column Store             | Fuzzy checkpoint                                             |Planning|         |          |
| Storage            | Column Store             | Enhance disk file storage                                            |Planning|         |          |
| Storage            | Column Store             | Enhance asynchronization garbage collection                          |Planning|         |          |
| Storage            | Column Store             | Tablet-group split                                           |Planning|         |          |
| Storage            | Column Store             | Data vacuum                                                  |Planning|         |          |
| Storage            | Column Store             | Buffer management                                            |Done|         |          |
| Storage            | Column Store             | Data compaction management                                   |Planning|         |          |
| Storage            | Column Store             | Support parquet and Arrow in-memory                          |Planning|         |          |
| Storage            | Column Store             | Asynchronized IO scheduling                                  |Planning|         |          |
| Storage            | Column Store             | Data recover from writing ahead log                          | Ongoing |         |          |
| Storage            | Column Store             | Support multiple column data model                           |Planning|         |          |
| Storage            | Column Store             | Mutiple version indexes management                           |Planning|         |          |
| Storage            | Row Store                | Local transaction management                                 |Planning|         |          |
| Storage            | Row Store                | Data recover from writing ahead log                          |Planning|         |          |
| Storage            | Row Store                | Secondary index supports                                     |Planning|         |          |
| Storage            | Row Store                | Support multiple row data model                              |Planning|         |          |
| DDL & Catalog      |                          | Support online schema change                                          |Planning|         |          |
| DDL & Catalog      |                          | Introduce query log table and metric table                  |Planning|         |          |
| DDL & Catalog      |                          | Support catalog cache                  |Planning|         |          |
| DDL & Catalog      |                          | Support permission control                  |Planning|         |          |

**Comment by dengn** [comment]
This roadmap is out of date.
