### ISSUE TITLE
[Bug]: double free

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6142]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

A bunch of double frees.   Repro, using https://github.com/matrixorigin/matrixone/pull/6141

bvt test will catch a few double frees.    For example, bigint.test.   A stand along repro.   limit 1 without offset wont' trigger double free.

```
mysql> create table t1 ( a int not null default 1, big bigint unsigned primary key);
mysql> insert into t1 (big) values (0),(18446744073709551615), (0xFFFFFFFFFFFFFFFE), (18446744073709551613), (18446744073709551612);
mysql> select * from t1 order by 1, 2 asc limit 1, 3;
```

**Comment by fengttt** [comment]
function FixedLengthShuffle, in vectorize/shuffle/shuffle.go:line54, 55.   What is it doing? 

It is kind of messed up really badly ...

**Comment by fengttt** [comment]
Is this fixed?  @m-schen

**Comment by m-schen** [comment]
> Is this fixed? @m-schen

fixed. source cause is the mpool queue bug
