### ISSUE TITLE
[Bug]: accesscontrol case performance is about twice as slow as before

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6146]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):6cc955dab80219c9112fa667822a69535ee5431d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

there are two problems about e2e ci：
1. accesscontrol case performance is about twice as slow as before, It takes about 4 minutes to close pr, but now it takes about 8 minutes
![image](https://user-images.githubusercontent.com/113406637/199152810-6244d044-b463-4ac3-abf0-3798a52ccc81.png)
case pr log：https://github.com/matrixorigin/matrixone/actions/runs/3351463516/jobs/5552929214
Or see the log file old50min, new50min（bvtlog.zip）
2. the execution time of e2e ci is from 30min to 50min ，compare  case time logs,  maymaybe accesscontrol case  join into bvt case causes other cases to slow down
![image](https://user-images.githubusercontent.com/113406637/199154860-a84658b1-0684-42b4-a41c-43e6be044838.png)
Or see the log file 25min，old50min, new50min（bvtlog.zip）

**Comment by heni02** [comment]
[bvtlog.zip](https://github.com/matrixorigin/matrixone/files/9906728/bvtlog.zip)

**Comment by heni02** [comment]
[bvtlog.zip](https://github.com/matrixorigin/matrixone/files/9907561/bvtlog.zip)

**Comment by florashi181** [comment]
can do some profiling @daviszhen

**Comment by daviszhen** [comment]
The performance will be  promoted at 0.7

**Comment by daviszhen** [comment]
i am not working on it

**Comment by florashi181** [comment]
@daviszhen

**Comment by heni02** [comment]
At present, ci has no such problem，closed
