### ISSUE TITLE
[Bug]:  MO doesn't recognize localhost

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6152]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO doesn't recognize localhost.

[dengnan@VM-0-12-centos ~]$ mysql -hlocalhost -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'dump'@'localhost' (using password: YES)
[dengnan@VM-0-12-centos ~]$ mysql -h127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1099
Server version: 0.5.1 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye

**Comment by aressu1985** [comment]
fix: 249f56400184a0828afdc615c8b5d75e8c57cecc

sudong@sudongdeMacBook-Pro aressu1985 % mysql -hlocalhost -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.29 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
sudong@sudongdeMacBook-Pro aressu1985 %

**Comment by dengn** [comment]
this is happening again:

Commit id: 8870ea87a96828862413e88f380c5bf5159fa5ad
<img width="663" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/e3aacc5c-d4d3-4c15-8ec5-460b586372bd">


```
nandeng-macbookpro:logs nandeng$ mysql -h127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8721
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
nandeng-macbookpro:logs nandeng$ mysql -hlocalhost -P6001 -uroot -p111       
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by aressu1985** [comment]
tracked by https://github.com/matrixorigin/matrixone/issues/10545
