### ISSUE TITLE
[Bug]: permission cache inconsistency

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#6153]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6cc955dab80219c9112fa667822a69535ee5431d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![10461667268553_ pic](https://user-images.githubusercontent.com/60595215/199173199-f41cdb0f-ad5b-4905-842b-76a9ee535409.jpg)

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by sukki37** [comment]
This issue has been inactive for a while. Based on the recent updates and changes in the project, this problem has been resolved or is no longer relevant.

I am going to close this issue. If anyone still experiences this problem or has further concerns, please feel free to reopen the issue or create a new one.
