### ISSUE TITLE
[Bug]: atomicity_1.result should report duplicate but have not.

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#6162]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):eff64a3434
- Hardware parameters:win11
- OS type:wsl2
- Others:
```

### Actual Behavior

in atomicity_1.result

...
create table atomic_table_1(a bigint not null,b varchar,c double,primary key(a,b)); // line 9
...
insert into atomic_table_1 select 10,"eeeeee",20.3; // line 35
...
insert into atomic_table_1 select 10,"eeeeee",20.3; // line 44

The second insertion violates the primary key constraint, but but the expectation indicates a successful insertion.

### Expected Behavior

[ERROR]
[SCRIPT   FILE]: /home/jensen/matrixorigin/matrixone/test/distributed/cases/transaction/atomicity_1.sql
[ROW    NUMBER]: 35
[SQL STATEMENT]: insert into atomic_table_1 select 10,"eeeeee",20.3;
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
tae data: duplicate

**Comment by heni02** [comment]
plz confirm startup mode，now ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml this case distributed transaction is correct

**Comment by jensenojs** [comment]
According to the response from the distributed team, . /mo-service-launch . The behavior of /etc/launtch/launtch.toml will be later compared to /mo-service -launch . /etc/launch-tae-CN-tae-DN/launch.toml to be consistent. So close this issue.
