### ISSUE TITLE
[Bug]: select timediff('20',NULL) , timediff('20','24:59:09.8453') error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6197]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):238f5a0f6f921b2e2414435c6d83ca949238bb22
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/199435696-02b6dafe-f0f7-4139-8186-c4681ddfed9a.png)
![image](https://user-images.githubusercontent.com/113406637/199435647-128e4fa3-569f-4d37-a1b5-4a6bffb03d41.png)
![image](https://user-images.githubusercontent.com/113406637/199436468-b6254fa4-e1a0-407f-ad93-00e8044ea599.png)

mysql:
![image](https://user-images.githubusercontent.com/113406637/199435791-12aa6e86-087e-472d-8986-2beed0ff4328.png)

### Steps to Reproduce

```Markdown
select timediff('20',NULL) , timediff('20','24:59:09.8453')
select timediff('12:00','24:59:09.8453'),timediff('-838:59:59.0000','-1122');
```

**Comment by YANGGMM** [comment]
now support timediff for input with varchar type, but the time precision have some bug to fix.

**Comment by heni02** [comment]
confirm,closed
commit id:6e725b584955c85eeb2cb4526779a4d4730df2ad
![image](https://user-images.githubusercontent.com/113406637/200218584-71d5ba2f-3117-4087-802a-a1f5f1929e06.png)
