### ISSUE TITLE
[Bug]: timediff(time,datatime)reported error,mysql result is null

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6198]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):238f5a0f6f921b2e2414435c6d83ca949238bb22
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo:
![image](https://user-images.githubusercontent.com/113406637/199437156-c47cc8ca-fb51-4a2f-9356-49f41e133306.png)

mysql:
![image](https://user-images.githubusercontent.com/113406637/199437389-b64fc24c-7ee4-4c77-b6ad-c676b63fa296.png)

### Steps to Reproduce

```Markdown
create table time_04 (t1 int,t2 time,t3 datetime,t4 timestamp);
insert into time_04 values (1,"344:59:09","2020-09-12","2021-09-22 10:01:23.903");
select * from time_04;
select timediff(t2,t3)from time_04;
```

**Comment by domingozhang** [comment]
datetime and time cannot be used in timediff as two parameters. This error is acceptable.

**Comment by heni02** [comment]
confirm，closed
