### ISSUE TITLE
[Bug]: timediff filter reported cast to int

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6199]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):238f5a0f6f921b2e2414435c6d83ca949238bb22
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="696" alt="企业微信截图_8230b1f5-d963-459e-a3d2-94a5160e8b68" src="https://user-images.githubusercontent.com/113406637/199438625-92e482df-92df-4ee0-82cd-5a0b936a9fef.png">

### Steps to Reproduce

```Markdown
create table time_01(t1 time,t2 time,t3 time);
insert into time_01 values("-838:59:59.0000","838:59:59.00","22:00:00");
insert into time_01 values("0:00:00.0000","0","0:00");
select * from time_01 where timediff(t1,t2) <0;
```

**Comment by YANGGMM** [comment]
have fix the return type to support compare, but need the feature that cast int type to time type  to accomplish

**Comment by YANGGMM** [comment]
need wait https://github.com/matrixorigin/matrixone/pull/6309 to merge

**Comment by YANGGMM** [comment]
need wait https://github.com/matrixorigin/matrixone/pull/6309 to merge

**Comment by YANGGMM** [comment]
#6309 have merged， but still have error message “invalid argument numeric less than, bad value “，so still need to fix.
