### ISSUE TITLE
[Bug]: MO-Cloud Use tae, update and delete can not be used

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#6219]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql -h a9e5e48c34f464ac69a93ea26f6ebb8a-bd7d5a53b14d8e21.elb.us-west-2.amazonaws.com -P 6001 -u ddf67c2e_f62f_494e_bd04_4cc89b3988fb:admin:accountadmin -p

DDL：
creatte database test;
use test;
create table t(a int);
insert into t values (1), (2), (3);

Problematic SQL is : 
update t set a = 9 where a = 1;
![1](https://user-images.githubusercontent.com/74952516/199651455-6c3da949-5aa8-4658-80e8-0ff8d010d545.png)

delete from t where a = 1; 
![2](https://user-images.githubusercontent.com/74952516/199651476-355d67d5-31db-415e-be6c-f6f8b0d2d238.png)

**Comment by florashi181** [comment]
test again and update this issue @goodMan-code

**Comment by goodMan-code** [comment]
I have Recheck it on my local machine, It is no problem.
