### ISSUE TITLE
[Docs]: description about standalone boot configuration and distributed boot configuration

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6226]
### Is there an existing issue about documentation?

- [X] I have checked the existing issues.

### Describe the issue

```Markdown
we need a doc about standalone and distributed configuration items. What are their purposes and what do they serve.
```

**Comment by zhangxu19830126** [comment]
https://github.com/matrixorigin/docs/blob/main/config/mo.md

**Comment by zhangxu19830126** [comment]
@nnsgmsone @daviszhen @w-zr @XuPeng-SH @volgariver6 please take a look.

**Comment by dengn** [comment]
already provided.
