### ISSUE TITLE
[Bug]: Memtable need gc

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#6232]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

need gc

**Comment by aressu1985** [comment]
@reusee how is this ISSUE Now？

**Comment by reusee** [comment]
Partial works are in this PR: https://github.com/matrixorigin/matrixone/pull/6463
But it's not going to be merged in 0.6.
So delay to 0.7

**Comment by reusee** [comment]
Waiting for 0.7 tree open

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
PR sent https://github.com/matrixorigin/matrixone/pull/6838

**Comment by reusee** [comment]
PR merged

**Comment by reusee** [comment]
fixed

**Comment by reusee** [comment]
@nnsgmsone Please close this.

**Comment by reusee** [comment]
waiting for reply from @nnsgmsone

**Comment by reusee** [comment]
will close after @nnsgmsone come back from vacation.

**Comment by reusee** [comment]
still waiting

**Comment by reusee** [comment]
waiting

**Comment by fengttt** [comment]
take it off s0 as it is fixed.   wait for @nnsgmsone to close.
