### ISSUE TITLE
[Bug]: mo panic if context timeout

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#6240]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): c1824a40
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[aws-us-west-2-serverless-tp-cn-0.p.log](https://github.com/matrixorigin/matrixone/files/9927566/aws-us-west-2-serverless-tp-cn-0.p.log)

**Comment by zhangxu19830126** [comment]
@sukki37 Reproduce steps?

**Comment by zhangxu19830126** [comment]
{"level":"ERROR","time":"2022/11/03 10:17:18.481661 +0000","name":"txn","caller":"util/log.go:89","msg":"txn send requests failed","requests":"[0: <9c0c3e153d2748cb91acbffec0768ffa/Active/S:1667470578376401630-0>/Read/F-0/<O:1000-D:427>/=><2-262148-0-aws-us-west-2-serverless-dn-0.aws-us-west-2-serverless-dn-headless.mo-serverless.svc:41010>]","error":"context deadline exceeded"}, it seems get logtail timeout. But dn's log is lost. Can't confirm if it's a network issue or DN processing logtail timeout. Need to keep DN logs next time

**Comment by zhangxu19830126** [comment]
@sukki37 DN's log is required, next time.

**Comment by daviszhen** [comment]
the panic will be removed at #6296 that is in the CI process

**Comment by fengttt** [comment]
@daviszhen @zhangxu19830126  should we remove this from S-1?

**Comment by zhangxu19830126** [comment]
After @daviszhen 's PR,  will not panic if context timeout. And default RPC's max message size is changed to 100MB. So this bug is fixed.
