### ISSUE TITLE
[Bug]: time type is  primary key, and insert mo service crash

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6272]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):8a205419cdc671a499c38bad6a7bfc0ce93d830f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/199920648-3d5f8637-7b8d-404f-885c-744eed97c683.png)

log:
2022/11/04 15:34:45.564062 +0800 INFO frontend/mysql_cmd_executor.go:3057 query trace {"connection_id": 1021, "query": "insert into time_03 values (30,\"101412\",\"yellow\")"}
2022/11/04 15:34:45.569866 +0800 INFO frontend/util.go:474 query trace status {"connection_id": 4294967295, "statement": "start transaction", "status": "success"}
2022/11/04 15:34:45.573456 +0800 INFO frontend/mysql_cmd_executor.go:2702 time of Exec.Build : 3.413875ms
2022/11/04 15:34:45.574609 +0800 INFO frontend/mysql_cmd_executor.go:2793 time of Exec.Run : 1.081875ms
2022/11/04 15:34:45.574666 +0800 INFO frontend/util.go:474 query trace status {"connection_id": 4294967295, "statement": "select rp.privilege_id, rp.with_grant_option from mo_catalog.mo_role_privs as rp where rp.obj_id = 0 and rp.obj_type = \"table\" and rp.role_id = 0 and rp.privilege_id = 31 and rp.privilege_level = \"*.*\"", "status": "success"}
2022/11/04 15:34:45.574728 +0800 INFO frontend/util.go:474 query trace status {"connection_id": 4294967295, "statement": "commit", "status": "success"}
2022/11/04 15:34:45.574753 +0800 INFO frontend/mysql_cmd_executor.go:2702 time of Exec.Build : 10.496ms
2022/11/04 15:34:45.576142 +0800 INFO frontend/mysql_cmd_executor.go:2842 time of Exec.Run : 1.364042ms
2022/11/04 15:34:45.576177 +0800 INFO frontend/mysql_cmd_executor.go:2848 time of SendResponse 83ns
2022/11/04 15:34:45.576600 +0800 INFO txnimpl/index.go:233 error: internal error: TIME not supported {"span": {}}
panic: internal error: TIME not supported

goroutine 1130 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*simpleTableIndex).BatchInsert(0x1400bc82d20, {0x140072f72f0, 0x2}, {0x1050f0d40, 0x1400ca0a780}, 0x0, 0x1, 0x0, 0x1)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/txn/txnimpl/index.go:233 +0x1034
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).DoBatchDedup(0x1400ba67040, {0x1050f0d40, 0x1400ca0a780})
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/txn/txnimpl/table.go:570 +0xd4
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0x1400ba67040, 0x1400d11f1c0)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/txn/txnimpl/table.go:316 +0x70
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0x1400c3b62d0?, 0x1400bc82d00?, 0x1400d819220?)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121 +0x50
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0x1400bd8fe50?, 0x1400ca0a8a0?, 0x2?, 0x1050f0070?)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/txn/txnimpl/store.go:167 +0x88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0x1400cb5aaa0, 0x1400d819220?)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/txn/txnimpl/relation.go:162 +0x78
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0x1400dd0be00, {0x11724516b?, 0x8?}, 0x1400be1f000)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/moengine/txn_relation.go:55 +0x2b8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(0x140089e5350, {_, _}, {{0x1400d818df0, 0x10, 0x10}, 0x0, {0x1724516bd239b938, 0x0, 0x8323, ...}, ...}, ...)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/rpc/handle.go:405 +0x1ac
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandlePreCommit(0x10e9a1c10?, {_, _}, {{0x1400d818df0, 0x10, 0x10}, 0x0, {0x1724516bd239b938, 0x0, 0x8323, ...}, ...}, ...)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/vm/engine/tae/rpc/handle.go:262 +0x21c
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.handleWrite[...]({_, _}, _, {{0x1400d818df0, 0x10, 0x10}, 0x0, {0x1724516bd239b938, 0x0, 0x8323, ...}, ...}, ...)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/txn/storage/tae/write.go:80 +0x1a4
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Write(0x140047217a0?, {_, _}, {{0x1400d818df0, 0x10, 0x10}, 0x0, {0x1724516bd239b938, 0x0, 0x8323, ...}, ...}, ...)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/txn/storage/tae/write.go:38 +0x8c
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Write(0x140047217a0, {0x10507df18, 0x1400dd0b4a0}, 0x1400780a580, 0x14007eee200)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/txn/service/service_cn_handler.go:157 +0x9f0
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).doWrite(0x140056eb578?, {0x10507df18, 0x1400dd0b4a0}, 0x1400780a580, 0x14007eee200)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/dnservice/store_rpc_handler.go:87 +0x94
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWithRetry(0x140056eb608?, {0x10507df18, 0x1400dd0b4a0}, 0x1400474d080?, 0x14007eee200, 0x140056eb608)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/dnservice/store_rpc_handler.go:184 +0xbc
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleWrite(0x1400470f448?, {0x10507df18?, 0x1400dd0b4a0?}, 0x104f9e120?, 0x1400ca0a4e0?)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/dnservice/store_rpc_handler.go:62 +0x3c
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0x1400470f400, {0x10507df18, 0x1400dd0b4a0}, {0x1050a1198?, 0x1400780a580?}, 0x2?, {0x10503e940, 0x14007b13780})
	/Users/heni/test-envir/matrixone-cn-dn/pkg/txn/rpc/server.go:140 +0x330
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0x140054e87e0, {0x1050c5500, 0x14006f0ad00}, {0x104e5b1c0?, 0x1400dd0b4d0}, 0x64b)
	/Users/heni/test-envir/matrixone-cn-dn/pkg/common/morpc/server.go:194 +0x3d4
github.com/fagongzi/goetty/v2.(*server).doConnection(0x140057a3360, {0x1050c5500, 0x14006f0ad00})
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:381 +0x2b8
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:344 +0x78
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:336 +0x3c4

### Steps to Reproduce

```Markdown
create table time_03 (t1 int,t2 time primary key,t3 varchar(25));
insert into time_03 values (30,"101412","yellow");
```

**Comment by dongdongyang33** [comment]
Waiting PR merge

**Comment by heni02** [comment]
confirm,closed
commit id:fdfe64fcc72bf988159de9d8239cbcf12ffd4401
![image](https://user-images.githubusercontent.com/113406637/201022338-169e7f41-0568-4705-b5d9-030407be705d.png)
