### ISSUE TITLE
[Bug]: statement_info table, displayed sql is inconsistent with the executed sql.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6288]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql_client：
desc table;

use system;
select statement from statement_info;

result:show columns from table;

<img width="1545" alt="截屏2022-11-04 18 22 46" src="https://user-images.githubusercontent.com/39303074/199950227-64c6d2d5-1f7e-4085-a496-a7f6039c7d74.png">

<img width="1893" alt="截屏2022-11-04 18 23 07" src="https://user-images.githubusercontent.com/39303074/199950367-6839bbfc-eaa7-4fc9-b68d-7be83030adba.png">

**Comment by xzxiong** [comment]
@iamlinjunhong 看下咯，现在这里的语句是通过 `fmtCtx` 格式化出来的~

**Comment by iamlinjunhong** [comment]
“show columns/fields from table” and "desc table" are equivalent. You can only chose one, when use parser format. I don't want to record the original sql. That's a waste of memory when the sql is so large.

**Comment by iamlinjunhong** [comment]
same #8133

**Comment by xzxiong** [comment]
re-check after #8113 fixed.

**Comment by xzxiong** [comment]
@tianyahui-python https://github.com/matrixorigin/matrixone/issues/8113 has been test. ptal
