### ISSUE TITLE
[Bug]: cannot query task data by primary key -- real problem, restart database may fail.

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#6294]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): reuse/matrixone:cf8c698ae23e3e084f9487533a6a153948133bbc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

logservice panic because of not task data is returned. We need to know why task data cannot be queried by primary key?

![image](https://user-images.githubusercontent.com/77312370/199972580-3c819b6f-57c6-4237-9240-f63762392cbc.png)

### Steps to Reproduce

```Markdown
keep on restart dn, cn, on eks deployment.    cannot restart.
many different errors.    
```

**Comment by volgariver6** [comment]
The code where panic happened: 

```go
func (s *taskService) Allocate(ctx context.Context, value task.Task, taskRunner string) error {
	exists, err := s.store.Query(ctx, WithTaskIDCond(EQ, value.ID))
	if err != nil {
		return nil
	}
	if len(exists) != 1 {
		panic(fmt.Sprintf("query task by primary key, return %d records", len(exists)))
	}

```

In my opinion, this panic is not necessary. It could just be error log. What do you think of it? @zhangxu19830126

**Comment by volgariver6** [comment]
After disscusion, the key question is why no data is queried by primary key.

@JasonPeng1310 plz help to investigte this issue, thx.

**Comment by daviszhen** [comment]
> After disscusion, the key question is why no data is queried by primary key.
> 
> @JasonPeng1310 plz help to investigte this issue, thx.

The Reader.Read() returns no data. It needs the CN and DN people to fix it.

**Comment by nnsgmsone** [comment]
No progress for now.

**Comment by nnsgmsone** [comment]
No progress for now.

**Comment by dongdongyang33** [comment]
No progress for now.

**Comment by fengttt** [comment]
Updated repro.   Now let's classify this as a restart bug.   To DN team.

**Comment by LeftHandCold** [comment]
> Updated repro. Now let's classify this as a restart bug. To DN team.

Why?I can restart on eks.

**Comment by LeftHandCold** [comment]
> > After disscusion, the key question is why no data is queried by primary key.
> > @JasonPeng1310 plz help to investigte this issue, thx.
> 
> The Reader.Read() returns no data. It needs the CN and DN people to fix it.

no log?

**Comment by aptend** [comment]
after https://github.com/matrixorigin/matrixone/commit/21e68b869f222b50ecf22c52a15a7ed23c28044c, anyone repros this and has a log?

**Comment by daviszhen** [comment]
> > > After disscusion, the key question is why no data is queried by primary key.
> > > @JasonPeng1310 plz help to investigte this issue, thx.
> > 
> > 
> > The Reader.Read() returns no data. It needs the CN and DN people to fix it.
> 
> no log?

In previous days and today, I am not working on these problems anymore.

**Comment by sukki37** [comment]
Not repro in recent commits， I think this issue can be downgraded.

**Comment by w-zr** [comment]
[log.tar.gz](https://github.com/matrixorigin/matrixone/files/10029794/log.tar.gz)

**Comment by aptend** [comment]
> [log.tar.gz](https://github.com/matrixorigin/matrixone/files/10029794/log.tar.gz)

this log has no debug log for dn and cn. @w-zr will try repro this with debug enabled

according to the log, **select from sys_async_task returns 1 row result, but task service still panics, saying receives no result**

```
2022/11/17 16:19:17.454740 +0800 INFO frontend/util.go:495 query trace {"connection_id": 1085, "query": "select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_id=7 order by task_id", "session_info": "connectionId 1085"}
...
2022/11/17 16:19:17.476416 +0800 INFO frontend/util.go:510 rowCount 1 
time of getDataFromPipeline : 53.4µs 
processBatchTime 45.4µs 
row2colTime 0s 
allocateOutBufferTime 800ns 
outputQueue.flushTime 0s 
processBatchTime - row2colTime - allocateOutbufferTime - flushTime 44.6µs 
restTime(=tTime - row2colTime - allocateOutBufferTime) 52.6µs 
protoStats flushCount 0 writeCount 1 
writeBytes 0 0 MB
connectionId 1085
...
2022/11/17 16:19:17.476536 +0800 INFO frontend/util.go:510 time of Exec.Run : 880.201µs connectionId 1085
```

meanwhile, connection has illegal state

```
2022/11/17 16:19:17.476302 +0800 ERROR v2@v2.0.3-0.20221112031939-24c732da4b95/application.go:345 handle session failed {"listen-addresses": "[0.0.0.0:10114]", "error": "read tcp4 127.0.0.1:10114->127.0.0.1:42160: use of closed network connection"}
...
2022/11/17 16:19:17.476638 +0800 ERROR frontend/util.go:505 illegal state {"session_info": "connectionId 1085"}
github.com/matrixorigin/matrixone/pkg/frontend.logError
	/home/wei/matrixone/pkg/frontend/util.go:505
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/home/wei/matrixone/pkg/frontend/mysql_cmd_executor.go:3656
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/home/wei/matrixone/pkg/frontend/mysql_cmd_executor.go:3811
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
	/home/wei/matrixone/pkg/frontend/routine.go:160
```

**Comment by aptend** [comment]
i ran mo cluster test for 50+ times, didn't repro. I keep running the test on 129 server

**Comment by aptend** [comment]
last night 129 server ran the test on the 0.6.0 branch 160+ times but didn't repro. keep running today

**Comment by aptend** [comment]
repro log with debug level.
[failed_201.tgz](https://github.com/matrixorigin/matrixone/files/10064589/failed_201.tgz)

but the panic can't provide detailed context like timestamp、testcase etc.

so modify `task_service.go` and try to repro again

<img width="2126" alt="image" src="https://user-images.githubusercontent.com/49832303/203254105-a539b16e-5367-47f8-b0b4-ce301abccfe0.png">

**Comment by aptend** [comment]
after analyzing source codes, i found Rows error didn't be checked after looping
 https://github.com/matrixorigin/matrixone/blob/9d10c1e8dc38139bd29d5d0e5d2575bcc3b8f9b8/pkg/taskservice/mysql_task_storage.go#L435

Rows.Next might read bytes from a connection, but if the connection is broken (for example read Unexpected EOF, as shown in log),  Next only returns false. that's why task Query gets an empty result and nil error

**Comment by sukki37** [comment]
no repro in recent commits; leave it to 0.7 for further observe
