### ISSUE TITLE
[Bug]: The unique key is not working

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#6299]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a30b90e26
- Hardware parameters: wsl2
- OS type: ubuntu
- Others: ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
```

### Actual Behavior

mysql> create table t0(a int, unique key(a));
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t0 values (1), (1);
Query OK, 2 rows affected (0.03 sec)

mysql> select * from t0;
+------+
| a    |
+------+
|    1 |
|    1 |
+------+
2 rows in set (0.02 sec)

mysql> 

### Expected Behavior

sth like

mysql> create table t0(a int, unique key(a));
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t0 values (1), (1);
ERROR 1062 (23000): Duplicate entry '1' for key 't0.a'
mysql>

**Comment by jensenojs** [comment]
will support later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by jensenojs** [comment]
unique key seems to need to do another refactoring, which tae doesn't support right now.

**Comment by jensenojs** [comment]
Anyway, I know this book by knowing that it is going to be translated into Chinese (but I don't know if it is true or not), because there is sample code so I think it is a very good book, I am surprised that there are not many stars in this repository. If it really has a Chinese version of the book I would highly recommend it to students behind me in College.

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will solve it after unique index pr is merge

**Comment by heni02** [comment]
still problems, waiting for verification after repair
confirm commit id：60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e

**Comment by heni02** [comment]
confirm,closed
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210352091-eac83ae6-9b82-460c-94aa-2b77a148dabd.png)

**Comment by heni02** [comment]
@bbbearxyz plz remove bvt tag

**Comment by heni02** [comment]
@aressu1985 plz closed this issue
