### ISSUE TITLE
[Bug]: blob load_file invalid path file reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6304]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):e983be5ad02b14da54754be5e64410446819f421
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/200112865-c659706e-84d8-414d-b51d-2e6429b38c31.png)

### Steps to Reproduce

```Markdown
select load_file('$resource/external_table_file/blobtest03.jpeg');
```

**Comment by jensenojs** [comment]
current state
![image](https://user-images.githubusercontent.com/56761542/201632073-4c5a2f3e-e7f4-4dc4-850e-d201672793f8.png)

**Comment by heni02** [comment]
waiting #6304 merge regression

**Comment by heni02** [comment]
confirm,closed
commit id:6436efdb8fa6093fbc543840d53a67b4f299cb23
![image](https://user-images.githubusercontent.com/113406637/202072571-1df877af-da17-4574-857f-ff9fa39366a3.png)
