### ISSUE TITLE
[Bug]: select tinytext,mediumtext,longtext values error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6306]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):e983be5ad02b14da54754be5e64410446819f421
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/200121784-4ca6c214-d249-46ef-8f49-d16ecc5526c5.png)
![image](https://user-images.githubusercontent.com/113406637/200122208-4dab09b4-0da1-49e8-bec0-397a3f4c0d6f.png)

### Steps to Reproduce

```Markdown
create table text_02(t1 text,t2 tinytext,t3 mediumtext,t4 longtext,t5 text);
insert into text_02 values("cat","yellow 芝士","2020-10-09","0001-01-01 00:00:00.000000","1970-01-01 00:00:01.0000");
select * from text_02;
```

**Comment by JackTan25** [comment]
working on

**Comment by heni02** [comment]
confirm,closed
commit id:0ca18fd72cf4d3eda0e03c30f9fa82725f804f90
![image](https://user-images.githubusercontent.com/113406637/202686022-840f7dea-786c-49ae-9335-1ff9bdb077fc.png)
