### ISSUE TITLE
[Bug]: load_file which not exists file reported  message is incorrect 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6313]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):e983be5ad02b14da54754be5e64410446819f421
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

reported file not exits better
![image](https://user-images.githubusercontent.com/113406637/200155618-6e998aa4-390e-452a-8591-c991a7e84a5c.png)

### Steps to Reproduce

```Markdown
create table blob_04(a int,b varchar);
insert into blob_04 values(1,load_file('$resources/blob_file/blob1.csv'));
```

**Comment by JackTan25** [comment]
working on

**Comment by jensenojs** [comment]
In fact, the file given in this example exists. But it still reports an error.
![image](https://user-images.githubusercontent.com/56761542/201305211-7ba8b65b-6dba-47f4-858f-bce6b22a0e4e.png)
so i will working on it firstly

**Comment by domingozhang** [comment]
if varchar length is not defined in Delhi, the default value is 1. 
this scenario is fine because the length of csv longer than 1

**Comment by jensenojs** [comment]
![image](https://user-images.githubusercontent.com/56761542/201315374-9da71509-12ed-4184-ac43-6097b5aa1653.png)

the reason why mo not report sth like “file not exits better” is because of this line. All error in fillBatch in dml.go use MakeInsertError to return.

**Comment by jensenojs** [comment]
Maybe the latter can be improved here,

**Comment by jensenojs** [comment]
![image](https://user-images.githubusercontent.com/56761542/201573918-b769aaa6-bee5-41d3-8e5e-6150d67bae64.png)

waitting merge

**Comment by heni02** [comment]
confirm.closed
commit id:b7215088e856e7da62e67e80a96b6c3bc0d89eb1
![image](https://user-images.githubusercontent.com/113406637/204995427-b595604c-b207-4cc1-860a-057e727a7870.png)
