### ISSUE TITLE
[Bug]: timediff results error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6321]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):6e725b584955c85eeb2cb4526779a4d4730df2ad
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo results is error:
![image](https://user-images.githubusercontent.com/113406637/200169446-c43dcb55-ac7c-4d36-bddb-908ec3a7cfc5.png)
mysql results:
![image](https://user-images.githubusercontent.com/113406637/200169496-2ad1decd-dded-4113-8965-9020266a0859.png)

### Steps to Reproduce

```Markdown
create table time_01(t1 time,t2 time,t3 time);
insert into time_01 values("-838:59:59.0000","838:59:59.00","22:00:00");
insert into time_01 values("0:00:00.0000","0","0:00");
insert into time_01 values(null,NULL,null);
insert into time_01 values("23","1122","-1122");
insert into time_01 values("101412","4","-101219");
insert into time_01 values("24:59:09.932823","24:02:00.93282332424","24:20:34.00000000");
insert into time_01 values("2022-09-08 12:00:01","019","23403");

select timediff(t1,t2) from time_01;
```

**Comment by heni02** [comment]
confirm,closed
commit id:91db699724193575ebfe6e75f36d25be9e927c27
![image](https://user-images.githubusercontent.com/113406637/200721142-ae766296-067a-4bf9-8f2e-608510f5b2a1.png)

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
