### ISSUE TITLE
[Bug]: TPCH Query is hung with scale 10G and cause the following connection is hung too

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6324]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):777b7ebbe34b8d1d3fe0733de2db588a4fc40c71
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

config: cn, dn, log max-message-size = "1gb"

TPCH 10G Queres Q1 Q10 are hung, the error message is as following:
2022/11/06 20:55:48.029046 +0800 INFO frontend/util.go:498 User 58a332ff-b3b5-44e8-9c2a-2c2d6463acc4 change database from [] to [mo_task] connectionId 1353
2022/11/06 20:55:48.029085 +0800 INFO frontend/util.go:483 query trace status {"connection_id": 1353, "statement": "use mo_task", "status": "success", "session_info": "connectionId 1353"}
2022/11/06 20:55:48.029128 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1353, "query": "select \n    \t\t\t\t\t\tcron_task_id,\n    \t\t\t\t\t\ttask_metadata_id,\n    \t\t\t\t\t\ttask_metadata_executor,\n    \t\t\t\t\t\ttask_metadata_context,\n    \t\t\t\t\t\ttask_metadata_option,\n    \t\t\t\t\t\tcron_expr,\n    \t\t\t\t\t\tnext_time,\n    \t\t\t\t\t\ttrigger_times,\n    \t\t\t\t\t\tcreate_at,\n    \t\t\t\t\t\tupdate_at\n\t\t\t\t\t\tfrom mo_task.sys_cron_task", "session_info": "connectionId 1353"}
2022/11/06 20:55:48.032261 +0800 INFO frontend/util.go:498 time of Exec.Build : 3.062685ms connectionId 1353
2022/11/06 20:55:50.001411 +0800 INFO db/db.go:131 [PrintStats][Caller=github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*garbageCollector).PostExecute]:{
  "WalStats": {
    "MaxLSN": 4475,
    "MaxCkped": 103,
    "PendingCnt": 4372
  }
}
[mysql] 2022/11/06 20:55:52 packets.go:37: read tcp 127.0.0.1:54876->127.0.0.1:6001: i/o timeout
2022/11/06 20:55:52.315994 +0800 INFO compile/cnserviceDriver.go:227 error: rpc timeout {"span": {}}
2022/11/06 20:55:52.316306 +0800 INFO frontend/util.go:498 check password succeeded connectionId 1354
2022/11/06 20:55:52.316398 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1354, "query": "use mo_task", "session_info": "connectionId 1354"}
2022/11/06 20:55:52.317714 +0800 INFO frontend/util.go:498 User 58a332ff-b3b5-44e8-9c2a-2c2d6463acc4 change database from [] to [mo_task] connectionId 1354
2022/11/06 20:55:52.317757 +0800 INFO frontend/util.go:483 query trace status {"connection_id": 1354, "statement": "use mo_task", "status": "success", "session_info": "connectionId 1354"}
2022/11/06 20:55:52.317799 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1354, "query": "select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_status=0 order by task_id", "session_info": "connectionId 1354"}
2022/11/06 20:55:52.321007 +0800 INFO frontend/util.go:498 time of Exec.Build : 3.143602ms connectionId 1354

[mysql] 2022/11/06 20:55:53 packets.go:37: read tcp 127.0.0.1:54892->127.0.0.1:6001: i/o timeout
2022/11/06 20:55:53.033134 +0800 INFO compile/cnserviceDriver.go:227 error: rpc timeout {"span": {}}
2022/11/06 20:55:53.033168 +0800 ERROR frontend/util.go:493 rpc timeout {"session_info": "connectionId 1353"}
github.com/matrixorigin/matrixone/pkg/frontend.logError
	/data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:493
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3026
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3103
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
	/data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:159
2022/11/06 20:55:53.033215 +0800 ERROR frontend/util.go:493 query trace status {"connection_id": 1353, "statement": "select cron_task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, cron_expr, next_time, trigger_times, create_at, update_at from mo_task.sys_cron_task", "status": "fail", "error": "rpc timeout", "session_info": "connectionId 1353"}
github.com/matrixorigin/matrixone/pkg/frontend.logError
	/data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:493
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus
	/data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:477
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus
	/data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:469
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3034
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/data1/sudong/mo-regression/matrixone/pkg/frontend/mysql_cmd_executor.go:3103
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
	/data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:159
2022/11/06 20:55:53.033265 +0800 ERROR frontend/util.go:508 routine send response failed &{1 0 3 0xc038d02720 0 0 0}. error:illegal state  connectionId 1353
github.com/matrixorigin/matrixone/pkg/frontend.logErrorf
	/data1/sudong/mo-regression/matrixone/pkg/frontend/util.go:508
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
	/data1/sudong/mo-regression/matrixone/pkg/frontend/routine.go:165

and cause the following connection is hung too.

**Comment by m-schen** [comment]
I found that we can run tpch without remoteRun.

and if run remote run. (it will use mo-rpc to send pipeline and receive back message).
the context for mo-rpc will be done due to unknown reason.
we will get error here:
https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/compile/cnserviceDriver.go#L227

I have check compute-layer code, and fix a bug may cause panic when clean pipeline. but I think it's not the root cause of the issue.

**Comment by m-schen** [comment]
I found that some pipeline remote run and send to cn-server, but didn't get the end message back.
may the internal sql frozen the pipeline. I am not sure. 
I am trying to merge commit about pipeline clean up (still some bvt not pass). hope it can fix the bug. but if not, the commit is still needed. so I am working that now.

**Comment by fengttt** [comment]
6324目前看是有的pipeline发送到远端执行后没有返回end message回来，已经验证过与rpc message的大小限制无关，让张旭帮忙看了rpc的日志，说可能与内部sql的执行出错有关系。我这里考虑pipeline没法回来message的原因可能和pipeline执行出错陷入死锁有关（不过tpch的pipeline如果执行出错也是一个不该出现的问题，现在还不清楚怎么回事），我在把我对pipeline清理的代码搬过来，看能不能解决这个问题，现在bvt还有点问题。

**Comment by nnsgmsone** [comment]
It was found that the packets sent by the stream of morpc may be lost, and is debug this problem with Zhang Xu.

**Comment by m-schen** [comment]
while the query hung, start a new mysql client to connect the MO will failed. and log is so less as follow.

```
2022/11/08 21:14:09.922668 +0800 INFO frontend/util.go:510 time of Exec.Build : 4.309459ms 
2022/11/08 21:14:09.922885 +0800 INFO moerr/error.go:420 error: unexpteded end of file EOF {"span": {}}
{"level":"DEBUG","time":"2022/11/08 21:14:09.922842 +0800","caller":"morpc/backend.go:445","msg":"write request","remote":"127.0.0.1:6002","request-id":37,"request":"sid: 0, cmd: 0, data: \u0008\u0002\"\ufffd\u0002\n\nmo_catalog\u0012\nmo_account\u001a\naccount_id\u001a\u000caccount_name:Q\n\u0004\u0008\n0\u00012I\n\u0005 \u000cB\u0001=\u0012/\n\u0010\u0008= dB\nmo_account*\u001b\u0010\u0001\u001a\u0017mo_account.account_name\u0012\u000f\n\u0006\u0008= \u00030\u0004\u0012\u0005Z\u0003sysB\ufffd\u0001\n\nmo_account\u0012\u001a\n\naccount_id\u001a\u0008\u0008\u0016\u0018\u0001  0\u0004\"\u0002\u0008\u0001\u0012\u001a\n\u000caccount_name\u001a\u0006\u0008= d0\u0018\"\u0002\u0008\u0001\u0012\u0014\n\u0006status\u001a\u0006\u0008= d0\u0018\"\u0002\u0008\u0001\u0012\u0018\n\u000ccreated_time\u001a\u0004\u000850\u0008\"\u0002\u0008\u0001\u0012\u0017\n\u0008comments\u001a\u0007\u0008= \ufffd\u00020\u0018\"\u0002\u0008\u00012\u000c\n\u0008comments\u0010\u00042\u0010\n\u000ccreated_time\u0010\u00032\n\n\u0006status\u0010\u00022\u0010\n\u000caccount_name\u0010\u00012\u000e\n\naccount_id\u0010\u0000J\u000e\u0008\ufffd\ufffd\ufffd̸\ufffd\ufffd\ufffd\u0017\u0018\ufffd\ufffd\u00022V\u0008\u000b\ufffd\u0001Q\n\u0004\u0008\n0\u00012I\n\u0005 \u000cB\u0001=\u0012/\n\u0010\u0008= dB\nmo_account*\u001b\u0010\u0001\u001a\u0017mo_account.account_name\u0012\u000f\n\u0006\u0008= \u00030\u0004\u0012\u0005Z\u0003sys2d\u0008\u000e\ufffd\u0001-\n\u0012\u0008\u0016\u0018\u0001  B\nmo_account*\u0017\u001a\u0015mo_account.account_id\ufffd\u0001/\n\u0010\u0008= dB\nmo_account*\u001b\u0010\u0001\u001a\u0017mo_account.account_name2f\u0008\u000e\u0010\u0001\ufffd\u0001-\n\u0012\u0008\u0016\u0018\u0001  B\nmo_account*\u0017\u001a\u0015mo_account.account_id\ufffd\u0001/\n\u0010\u0008= dB\nmo_account*\u001b\u0010\u0001\u001a\u0017mo_account.account_nameJ\ufffd\u0005\u0008\n\u0012$dd1dccb4-4d3c-41f8-b482-5251dc7a41bf\u001a\u000e127.0.0.1:6002\"\ufffd\u00057\ufffd\ufffd\u0003\u0001\u0001\tBlockMeta\u0001\ufffd\ufffd\u0000\u0001\u0003\u0001\u0004Rows\u0001\u0004\u0000\u0001\u0004Info\u0001\ufffd\ufffd\u0000\u0001\u0007Zonemap\u0001\ufffd\ufffd\u0000\u0000\u0000r\ufffd\ufffd\u0003\u0001\u0001\tBlockInfo\u0001\ufffd\ufffd\u0000\u0001\u0007\u0001\u0007BlockID\u0001\u0006\u0000\u0001\nEntryState\u0001\u0002\u0000\u0001\u0006Sorted\u0001\u0002\u0000\u0001\u0007MetaLoc\u0001\u000c\u0000\u0001\u0008DeltaLoc\u0001\u000c\u0000\u0001\u0008CommitTs\u0001\ufffd\ufffd\u0000\u0001\tSegmentID\u0001\u0006\u0000\u0000\u0000\u0012\ufffd\ufffd\u0001\u0001\u0001\u0002TS\u0001\ufffd\ufffd\u0000\u0001\u0006\u0001\u0018\u0000\u0000\u001a\ufffd\ufffd\u0002\u0001\u0001\u000b[][64]uint8\u0001\ufffd\ufffd\u0000\u0001\ufffd\ufffd\u0000\u0000\u000f\ufffd\ufffd\u0001\u0001\u0002\ufffd\ufffd\u0000\u0001\u0006\u0001\ufffd\ufffd\u0000\u0000\ufffd\u0001\ufffd\ufffd\ufffd\u0001\u0002\u0001\u0001\ufffd\u0005\ufffd\u00036b3aae74f-d1e6-4d0c-815a-5f1cb1c7798e:231_704_704:1:199\u0002\u000c\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0011,\ufffd\ufffd%\u0017\u0001\ufffd\u0003\ufffd\u0000\u0001\u0005@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000@sys\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffdsys\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000@open\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffdopen\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000@\ufffd\ufffd\ufffd\ufffd%\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd%\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000@system account\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffdsystem account\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000, err: "}

```

**Comment by m-schen** [comment]
The pipeline sent to cnservice itself did not go parallel run, but remote run. 
When multiple pipelines have dependencies，tcp buffer is full. some pipeline can't get its batch, so it blocks.

let local pipeline do not go the remote-run will solve this problem.

**Comment by fengttt** [comment]
Does not sound right to me -- if local pipeline go through remote, it can be a perf problem, but it should not block forever.   No?

**Comment by m-schen** [comment]
#6450 and  #6513 done, and every thing will be ok.
I will verify it soon.

**Comment by m-schen** [comment]
I have verified that. all the tpch 10g can be passed on CN-DN.

**Comment by aressu1985** [comment]
seems the hung is ok, but result has some problem, and tracked by issue  #6525
