### ISSUE TITLE
[Bug]: insert into varchar type size limit problem

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6327]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):6e725b584955c85eeb2cb4526779a4d4730df2ad
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The following two types of varchar type insertion behaviors are inconsistent and need to be unified
![image](https://user-images.githubusercontent.com/113406637/200175011-27b599b4-b4e0-46ed-8595-e822dde8e684.png)
![image](https://user-images.githubusercontent.com/113406637/200175014-30fabd7d-33c3-4fda-96cd-20ce83486863.png)

### Steps to Reproduce

```Markdown
create table blob_04(a int,b varchar(25));
insert into blob_04 values(1,load_file('/Users/heni/test_data/ex_table_2_1.csv'));
create table blob_04(a int,b varchar(25));
insert into blob_04 values(1,load_file('/Users/heni/test_data/ex_table_2_1.csv'));
create table blob_04(a int,b varchar(15));
insert into blob_04 values(1,'kskkfffkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
```

**Comment by JackTan25** [comment]
working on

**Comment by JackTan25** [comment]
Working on it now.

**Comment by heni02** [comment]
confirm,closed
commit id: f8b80ce16735031c25b7081b47d5ae8bb45da475
![image](https://user-images.githubusercontent.com/113406637/203781377-191e007b-fcb4-4c6f-bf55-df98ea429038.png)
