### ISSUE TITLE
[Bug]: SET @val = CAST("2022-10-10" AS date); execute failed.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6328]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> SET @val = CAST("2022-10-10" AS date);
ERROR 20203 (HY000): invalid argument variable type, bad value DATE
mysql> select CAST("2022-10-10" AS date);
+--------------------------+
| cast(2022-10-10 as date) |
+--------------------------+
| 2022-10-10               |
+--------------------------+
1 row in set (0.00 sec)

**Comment by tianyahui-python** [comment]
mysql> SET @val = CAST("2022-10-10" AS datetime);
ERROR 20203 (HY000): invalid argument variable type, bad value DATETIME

**Comment by tianyahui-python** [comment]
mysql> SET @val = CAST("2022-10-10" AS timestamp);
ERROR 20203 (HY000): invalid argument variable type, bad value TIMESTAMP

**Comment by tianyahui-python** [comment]
<img width="797" alt="截屏2022-11-14 10 24 00" src="https://user-images.githubusercontent.com/39303074/201562146-d826a4a2-1c7a-4a0c-9c23-a67ee6e015c4.png">

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
bvt tag no remove @iamlinjunhong
