### ISSUE TITLE
[Bug]: tpcc data consistency check failed when run test with 10-terminals-10-warehouse

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6335]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):777b7ebbe34b8d1d3fe0733de2db588a4fc40c71
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> use tpcc;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> (Select w_id, w_ytd from bmsql_warehouse) except (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id);
+------+-----------+
| w_id | w_ytd     |
+------+-----------+
|    1 | 519815.62 |
|    6 | 525330.37 |
|   10 | 468787.38 |
|    8 | 512739.29 |
|    2 | 589901.18 |
|    5 | 490551.94 |
|    9 | 489713.09 |
|    4 | 522321.67 |
|    3 | 519324.79 |
|    7 | 521698.00 |
+------+-----------+
10 rows in set (0.12 sec)

mysql> 
mysql> 
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);
+--------+------+-----------------+
| d_w_id | d_id | d_next_o_id - 1 |
+--------+------+-----------------+
|     10 |    7 |            3004 |
|      4 |   10 |            3003 |
|      9 |    4 |            3004 |
|      4 |    8 |            3005 |
|      2 |    7 |            3004 |
|      9 |    1 |            3004 |
|      7 |    8 |            3005 |
|      8 |    2 |            3005 |
|      9 |    5 |            3006 |
|      8 |   10 |            3005 |
|      3 |    5 |            3008 |
|     10 |    6 |            3005 |
|      6 |    3 |            3006 |
|      8 |    8 |            3006 |
|     10 |    8 |            3004 |
|      4 |    1 |            3007 |
|      1 |    6 |            3004 |
|      7 |    3 |            3006 |
|      1 |    7 |            3004 |
|      8 |    4 |            3004 |
|      8 |    5 |            3004 |
|      7 |    5 |            3006 |
|      2 |    6 |            3008 |
|      7 |   10 |            3003 |
|      1 |    5 |            3005 |
|      8 |    1 |            3005 |
|      7 |    9 |            3004 |
|      9 |   10 |            3005 |
|      6 |    4 |            3005 |
|      9 |    9 |            3004 |
|      2 |    1 |            3006 |
|      2 |    5 |            3004 |
|      4 |    5 |            3006 |
|      2 |    9 |            3005 |
|      2 |    3 |            3004 |
|      2 |    4 |            3005 |
|      5 |    2 |            3007 |
|     10 |    2 |            3005 |
|      7 |    7 |            3005 |
|      3 |    8 |            3005 |
|      9 |    8 |            3009 |
|      5 |    7 |            3003 |
|      3 |    4 |            3005 |
|      4 |    6 |            3004 |
|      5 |    6 |            3005 |
|      1 |    3 |            3005 |
|     10 |    3 |            3004 |
|      1 |    2 |            3006 |
|      6 |    9 |            3005 |
|      5 |    3 |            3004 |
|      6 |    5 |            3008 |
|      9 |    6 |            3003 |
|      3 |    6 |            3004 |
|      6 |    1 |            3003 |
|      3 |    7 |            3008 |
|      3 |   10 |            3005 |
|      4 |    4 |            3006 |
|      5 |    4 |            3010 |
|      2 |    2 |            3005 |
|      6 |    2 |            3005 |
|      4 |    7 |            3006 |
|     10 |    4 |            3006 |
|      7 |    1 |            3005 |
|      9 |    7 |            3003 |
|     10 |   10 |            3005 |
|      5 |    9 |            3004 |
|      6 |    6 |            3004 |
|      7 |    4 |            3006 |
|      1 |    8 |            3003 |
|      5 |    1 |            3004 |
|      8 |    6 |            3005 |
|      5 |    8 |            3005 |
|      3 |    1 |            3004 |
|     10 |    1 |            3004 |
|      4 |    9 |            3005 |
|      3 |    3 |            3005 |
|      6 |   10 |            3006 |
|      4 |    3 |            3005 |
|      1 |    1 |            3004 |
|      7 |    6 |            3005 |
|      6 |    8 |            3007 |
|     10 |    5 |            3004 |
|      8 |    9 |            3006 |
|      9 |    2 |            3007 |
|      9 |    3 |            3006 |
|      4 |    2 |            3008 |
|      1 |    4 |            3008 |
|      8 |    7 |            3006 |
|      5 |   10 |            3006 |
|      1 |   10 |            3006 |
|      1 |    9 |            3005 |
|      8 |    3 |            3007 |
|     10 |    9 |            3007 |
|      3 |    2 |            3006 |
|      5 |    5 |            3004 |
|      7 |    2 |            3006 |
|      3 |    9 |            3007 |
+--------+------+-----------------+
97 rows in set (0.33 sec)

mysql> 
mysql> 
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);
+--------+------+-----------------+
| d_w_id | d_id | d_next_o_id - 1 |
+--------+------+-----------------+
|     10 |    7 |            3004 |
|      4 |   10 |            3003 |
|      9 |    4 |            3004 |
|      4 |    8 |            3005 |
|      2 |    7 |            3004 |
|      9 |    1 |            3004 |
|      7 |    8 |            3005 |
|      8 |    2 |            3005 |
|      9 |    5 |            3006 |
|      8 |   10 |            3005 |
|      3 |    5 |            3008 |
|     10 |    6 |            3005 |
|      6 |    3 |            3006 |
|      8 |    8 |            3006 |
|     10 |    8 |            3004 |
|      4 |    1 |            3007 |
|      1 |    6 |            3004 |
|      7 |    3 |            3006 |
|      1 |    7 |            3004 |
|      8 |    4 |            3004 |
|      8 |    5 |            3004 |
|      7 |    5 |            3006 |
|      2 |    6 |            3008 |
|      7 |   10 |            3003 |
|      1 |    5 |            3005 |
|      8 |    1 |            3005 |
|      7 |    9 |            3004 |
|      9 |   10 |            3005 |
|      6 |    4 |            3005 |
|      9 |    9 |            3004 |
|      2 |    1 |            3006 |
|      2 |    5 |            3004 |
|      4 |    5 |            3006 |
|      2 |    9 |            3005 |
|      2 |    3 |            3004 |
|      2 |    4 |            3005 |
|      5 |    2 |            3007 |
|     10 |    2 |            3005 |
|      7 |    7 |            3005 |
|      3 |    8 |            3005 |
|      9 |    8 |            3009 |
|      5 |    7 |            3003 |
|      3 |    4 |            3005 |
|      4 |    6 |            3004 |
|      5 |    6 |            3005 |
|      1 |    3 |            3005 |
|     10 |    3 |            3004 |
|      1 |    2 |            3006 |
|      6 |    9 |            3005 |
|      5 |    3 |            3004 |
|      6 |    5 |            3008 |
|      9 |    6 |            3003 |
|      3 |    6 |            3004 |
|      6 |    1 |            3003 |
|      3 |    7 |            3008 |
|      3 |   10 |            3005 |
|      4 |    4 |            3006 |
|      5 |    4 |            3010 |
|      2 |    2 |            3005 |
|      6 |    2 |            3005 |
|      4 |    7 |            3006 |
|     10 |    4 |            3006 |
|      7 |    1 |            3005 |
|      9 |    7 |            3003 |
|     10 |   10 |            3005 |
|      5 |    9 |            3004 |
|      6 |    6 |            3004 |
|      7 |    4 |            3006 |
|      1 |    8 |            3003 |
|      5 |    1 |            3004 |
|      8 |    6 |            3005 |
|      5 |    8 |            3005 |
|      3 |    1 |            3004 |
|     10 |    1 |            3004 |
|      4 |    9 |            3005 |
|      3 |    3 |            3005 |
|      6 |   10 |            3006 |
|      4 |    3 |            3005 |
|      1 |    1 |            3004 |
|      7 |    6 |            3005 |
|      6 |    8 |            3007 |
|     10 |    5 |            3004 |
|      8 |    9 |            3006 |
|      9 |    2 |            3007 |
|      9 |    3 |            3006 |
|      4 |    2 |            3008 |
|      1 |    4 |            3008 |
|      8 |    7 |            3006 |
|      5 |   10 |            3006 |
|      1 |   10 |            3006 |
|      1 |    9 |            3005 |
|      8 |    3 |            3007 |
|     10 |    9 |            3007 |
|      3 |    2 |            3006 |
|      5 |    5 |            3004 |
|      7 |    2 |            3006 |
|      3 |    9 |            3007 |
+--------+------+-----------------+
97 rows in set (0.14 sec)

mysql> 
mysql> 
mysql> -- 执行语法报错
mysql> select * from (select (count(no_o_id)-(max(no_o_id)-min(no_o_id)+1)) as diff from bmsql_new_order group by no_w_id, no_d_id) as temp where diff != 0;
Empty set (0.08 sec)

mysql> 
mysql> 
mysql> (select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count
    -> (ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
+--------+--------+---------------+
| o_w_id | o_d_id | sum(o_ol_cnt) |
+--------+--------+---------------+
|      8 |     10 |         30358 |
|      4 |      5 |         30172 |
|      6 |      1 |         30032 |
|     10 |      3 |         30334 |
|      9 |      1 |         29952 |
|      1 |      2 |         29923 |
|      9 |     10 |         29954 |
|      1 |      5 |         30282 |
|      6 |      3 |         30489 |
|     10 |      1 |         29993 |
|      6 |      2 |         30037 |
|     10 |     10 |         30012 |
|      4 |      3 |         30192 |
|      9 |      3 |         29839 |
|      4 |      4 |         30072 |
+--------+--------+---------------+
15 rows in set (0.55 sec)

mysql> 
mysql> 
mysql> (select d_w_id, sum(d_ytd) from bmsql_district group by d_w_id)  except(Select w_id, w_ytd from bmsql_warehouse);
+--------+------------+
| d_w_id | sum(d_ytd) |
+--------+------------+
|      7 | 1043396.00 |
|      1 | 1039631.24 |
|      5 |  981103.88 |
|      6 | 1048106.29 |
|      4 | 1044643.34 |
|      3 | 1038649.58 |
|      2 | 1061996.07 |
|      8 | 1025478.58 |
|     10 |  937574.76 |
|      9 |  979426.18 |
+--------+------------+
10 rows in set (0.22 sec)

mysql>

**Comment by ouyuanning** [comment]
bug Recurrence in my env now.

after #6387 .  we will get consistency check pass in 10 warehouse/10 terminals/3 runMins if you run  the sql when tpcc finish for a while.
but if you run the check sql immediately， that will fail.   I think that will be another bug.

**Comment by ouyuanning** [comment]
The storage team has found the problem and is working on it。
thanks @aptend & @nnsgmsone

**Comment by fengttt** [comment]
@ouyuanning drive/owns this one.   Please ask @aptend for help.

**Comment by fengttt** [comment]
@ouyuanning call mo_ctl('dn', 'flush', '...') and let us know if it immediately solves the correctness problem.

**Comment by ouyuanning** [comment]
> @ouyuanning call mo_ctl('dn', 'flush', '...') and let us know if it immediately solves the correctness problem.

yes,  confirm that。it will immediately solves.

**Comment by ouyuanning** [comment]
if run MO config like:
[dn.Ckp]
flush-interval = "16000000s"
min-count = 1000000
scan-interval = "500000s"
incremental-interval = "16000000s"
global-interval = "16000000s"

means run all in mem, not flush to disk.   run 3 times , consistency check pass each time.

**Comment by aptend** [comment]
I have found the root cause, this problem can be fixed in next pr. DN logtail misses giving deletion data in memory in some corner cases

**Comment by aptend** [comment]
after https://github.com/matrixorigin/matrixone/pull/6462, i ran 2 warehouses 4 terminals multiple times, no repro

**Comment by ouyuanning** [comment]
seems fixed.  maybe in not so good way.
Keep tracking in #6469

**Comment by aressu1985** [comment]
tonight I will test it for a whole night

**Comment by aressu1985** [comment]
I have tested this issue for several days, not happened again, it can be fixed
