### ISSUE TITLE
[Bug]: desc/show columns failed

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6345]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d6b8c117d71f739f704c10b9694dc65003a5aca3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> desc mo_tables;
ERROR 1105 (HY000): EOF

mysql> show columns from mo_columns;
ERROR 1105 (HY000): EOF

**Comment by badboynt1** [comment]
can not reproduce. keep watching

**Comment by badboynt1** [comment]
can not reproduce. keep watching

**Comment by badboynt1** [comment]
can not reproduce
