### ISSUE TITLE
[Feature Request]: create index/unique index support

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6348]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create index hhh on log(a);
ERROR 20105 (HY000): not supported: statement: 'create index hhh on log (a)'
mysql> create unique index hhh on log(a);
ERROR 20105 (HY000): not supported: statement: 'create unique index hhh on log (a)'

### Expected Behavior

We need to support create index, same as MySQL.

**Comment by daviszhen** [comment]
It is not the bug.

**Comment by qingxinhome** [comment]
The secondary index will be developed

**Comment by bbbearxyz** [comment]
The secondary index is in process.

**Comment by bbbearxyz** [comment]
create index pr is in the review.

**Comment by bbbearxyz** [comment]
please confrim it.

**Comment by domingozhang** [comment]
completed

**Comment by domingozhang** [comment]
@dengn please close this feature. no impact to doc plan
