### ISSUE TITLE
[Bug]: Login hangs during a long-time query

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6357]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Session A: Query with 1 GB tpch data
Session B: Try to login with mysql client and hangs in 
mysql: [Warning] Using a password on the command line interface can be insecure.

[log.txt](https://github.com/matrixorigin/matrixone/files/9949288/log.txt)

**Comment by badboynt1** [comment]
MySQL [tpch]> source /root/matrixone/test/cases/benchmark/tpch/03_QUERIES/q3.sql
Database changed

q3 hanged when mo-service started with launch-tae-CN-tae-DN. 
if started with launch-tae-logservice, this query can finish in a short time.

MySQL [tpch]> source /root/matrixone/test/cases/benchmark/tpch/03_QUERIES/q3.sql
Database changed
+------------+-------------+-------------+----------------+
| l_orderkey | revenue     | o_orderdate | o_shippriority |
+------------+-------------+-------------+----------------+
|    2152675 | 431309.8065 | 1995-03-28  |              0 |
|    4994400 | 423834.7976 | 1995-03-09  |              0 |
|    2160291 | 401149.7805 | 1995-03-18  |              0 |
|    2845094 | 401094.1393 | 1995-03-06  |              0 |
|    1902471 | 400497.3847 | 1995-03-01  |              0 |
|    5624358 | 395710.6806 | 1995-03-20  |              0 |
|    2346242 | 392580.0394 | 1995-03-17  |              0 |
|    2529826 | 387365.1560 | 1995-02-17  |              0 |
|    5168933 | 385433.6198 | 1995-03-20  |              0 |
|    2839239 | 380503.7310 | 1995-03-22  |              0 |
+------------+-------------+-------------+----------------+
10 rows in set (0.40 sec)

**Comment by daviszhen** [comment]
Today I am working on the problem hanging the connection. I am try it to tomorrow.

**Comment by daviszhen** [comment]
It is almost the same as the #6330

**Comment by daviszhen** [comment]
I am not working on it today.

**Comment by daviszhen** [comment]
I do not reproduce it today

**Comment by daviszhen** [comment]
I am not working on it today
