### ISSUE TITLE
[Bug]: insert data w-w conflict after restart moservice several times 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6366]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):adefec5d7907027d66a46199c2d33185f121992d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select count(*) from sbtest1;
+----------+
| count(*) |
+----------+
|    13081 |
+----------+
1 row in set (0.01 sec)

mysql> select max(id) from sbtest1;
+---------+
| max(id) |
+---------+
|   19470 |
+---------+
1 row in set (0.00 sec)

mysql> select max(id) from sbtest1;
+---------+
| max(id) |
+---------+
|   19470 |
+---------+
1 row in set (0.00 sec)

mysql> insert sbtest1 values(20000,1232,'','');
ERROR 20619 (HY000): w-w conflict
mysql> insert sbtest1 values(20000,1232,'','');
ERROR 20620 (HY000): not found
mysql> insert sbtest1 values(20000,1232,'','');
ERROR 20619 (HY000): w-w conflict
mysql> insert sbtest1 values(20000,1232,'','');
ERROR 20619 (HY000): w-w conflict
mysql> insert sbtest1 values(20000,1232,'','');
ERROR 20619 (HY000): w-w conflict

### Steps to Reproduce

```Markdown
1. run mo with etc/launch-tae-CN-tae-DN/launch.toml
2. run sysbench insert test with 10 terminals
3. kill -9 XXXXX
4. run sysbench insert test with 10 terminals
5. kill -9 XXXXX
6. run sysbench insert test with 10 terminals

several times later, all insert operation in this table return w-w conflict or not found

how to run sysbench insert test:
1.git clone https://github.com/aressu1985/mo-load.git
2.modify mo addr in mo.yml
3.create database and table
  ./start.sh -m SYSBENCH -n 1 -s 1
4.run test
  ./start.sh -c cases/sysbench/simple_insert_10_10000
```

**Comment by XuPeng-SH** [comment]
We cannot reproduce this issue locally. 
We'll repro it using the data from sudong today.

**Comment by aressu1985** [comment]
it is a problem of stability test, and I trace this type of issue every daoy , when stability is OK , I will process all of these issues.

**Comment by XuPeng-SH** [comment]
I've found the root cause. It can be only reproduced with checkpoint replay. I'll fix it in the next PR

**Comment by aressu1985** [comment]
this need to be tested for more days,

**Comment by aressu1985** [comment]
fixed
