### ISSUE TITLE
[Bug]: connection fail with Navicat

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6367]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1b76a6319d51a3b9bcfc37a0ed209ed972a18218
- Hardware parameters:
- OS type:MAC OS12.2.1
- Others:Navicat Premium 16.1.3
```

### Actual Behavior

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/31049447/200311503-6875250d-41fb-47b6-8835-ede412bdeb0b.png">
can not get sys database

**Comment by qingxinhome** [comment]
It is verified that the error reported by the navicat connection mo is related to the MySQL version number. If the version number of the mo is changed back to 0.5.1, it can be used normally, and it will not be affected if it is below 3.6.
However, at the beginning of 8.0, both client tools need to find an SQL_ The database of the mode does not exist in MySQL. It is very strange here

**Comment by dengn** [comment]
I checked the log when Navicat access MatrixOne. MO has these 3 queries. 

2022/11/10 10:42:38.792603 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1207, "query": "SET NAMES utf8mb4", "session_info": "connectionId 1207"}
2022/11/10 10:42:38.829343 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1207, "query": "SHOW VARIABLES LIKE 'lower_case_%'; SHOW VARIABLES LIKE 'sql_mode'; SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'", "session_info": "connectionId 1207"}
2022/11/10 10:42:38.869095 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1207, "query": "SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA", "session_info": "connectionId 1207"}

The 3rd query SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA; returns nothing.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/4965857/200988375-4024a362-55c4-4cac-a48c-edba3e091764.png">

 while MySQL 8.0 will return a full database list, so I think that's the cause.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/4965857/200988341-51f582b1-57f6-433f-8a12-191e3b6594aa.png">

**Comment by qingxinhome** [comment]
I have implemented information_ The schema.SCHEMATA view ensures that there is valid data in it, and also provides search results, as shown in the following figure:
![image](https://user-images.githubusercontent.com/70939751/200994220-bcb1ccd0-d60e-44eb-b983-65eb829b1973.png)

However, errors will still be reported. @dengn @LiSong0214 @domingozhang

**Comment by qingxinhome** [comment]
After discussion, the solution is to add configuration parameters in the mo configuration file and modify the version value to adapt to different MySQL clients. @dengn @LiSong0214 @badboynt1 @domingozhang

**Comment by fengttt** [comment]
I don't understand this comment.

Add which config parameter?   What is the value?  For which clients?   This does not look like a viable solution.

**Comment by qingxinhome** [comment]
The thing is, Dr. Tian:
After investigation, it is found that when navicat connects to MySQL, different MySQL version numbers, navicat handles the connection differently, and the same is true for mo
When the version number of the mo is lower than 4.0, it can be successfully connected and used normally.
However, when the mod version number is greater than or equal to 4.0, the navicat will connect to a sql server by default_ mode, but there is no such database name in mysql,
At least we can't see it in the latest version, but it will affect the use of mo and report errors.
Because the mo needs to adapt to sqlalchemy, the version number of the mo must be greater than 5.7.20, otherwise some functions cannot be used
Therefore, after discussion, Ni Tao suggested that you put the version number of the mo in the configuration file, and configure different versions according to different MySQL clients to ensure that the clients can use it normally.
Deng Nan has agreed to this plan, and Ni Tao has realized it by. @fengttt @dengn @badboynt1

**Comment by fengttt** [comment]
NO.   You put out a version the server support.   You cannot do that in config.

Which database navicat will try to connect?   Is it a wellknown database after 5.7?    Should we just create a default database?

**Comment by badboynt1** [comment]
> NO. You put out a version the server support. You cannot do that in config.
> 
> Which database navicat will try to connect? Is it a wellknown database after 5.7? Should we just create a default database?

if the version is 5.7.0, navicat will fail.  if it is below 5.7, mysql workbench and sqlalchemy will fail.

**Comment by LiSong0214** [comment]
so we have no choice but config? @badboynt1  if so, pls supply how to config.
and how about you? @fengttt

**Comment by badboynt1** [comment]
you can edit config file like this:

[cn.frontend]
port = 6001
serverVersionPrefix = "8.0.30-MatrixOne-V"

here can be any string prefix, or at least a blank.
@LiSong0214

**Comment by dengn** [comment]
In 0.7.0, this issue remains. as we have set our version number to 8.0.30-MatrixOne-v0.6.0. 
<img width="361" alt="image" src="https://user-images.githubusercontent.com/4965857/204430693-9d806a43-3a88-4a2a-b70e-52a56fb8751e.png">

**Comment by daviszhen** [comment]
new problem of the compatibility in 8.0.30.

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
i am not working on it

**Comment by daviszhen** [comment]
I am not working on it.

**Comment by daviszhen** [comment]
I am not working on it.

**Comment by daviszhen** [comment]
I am not working on it.

**Comment by fengttt** [comment]
dup https://github.com/matrixorigin/matrixone/issues/6606

**Comment by daviszhen** [comment]
I am not working on it.

**Comment by daviszhen** [comment]
I am not working on it.

**Comment by daviszhen** [comment]
I am not working on it.

**Comment by daviszhen** [comment]
I am  not working on it today.

**Comment by daviszhen** [comment]
I am not working on it today.

**Comment by daviszhen** [comment]
I am not working on it today.

**Comment by daviszhen** [comment]
I am not working on it today.

**Comment by daviszhen** [comment]
i am not working on it.

**Comment by fengttt** [comment]
@daviszhen what is the plan though?

**Comment by daviszhen** [comment]
not in progress

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
have solved

**Comment by dengn** [comment]
fixed.
