### ISSUE TITLE
[Bug]: mo panic when run sysbench mixed cases(Occasional occurrence)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6370]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e23e00f1d01d43e33c509a6d239ccc38b5f93409
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the test step is described in Steps to Reproduce

the mixed case is as follows:
point_select
  - sql: "select c from sbtest{tbx} where id = {id};
  - 
insert_delete"
  - sql: "insert into sbtest{tbx} values({i_id},4993,'83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330','67847967377-48000963322-62604785301-91415491898-96926520291');"
  - sql: "delete from sbtest{tbx} where id = {i_id};"

update_pk
- sql: "UPDATE sbtest{tbx} SET k=k+100 WHERE id = {id};"

errorlog:
2022/11/08 00:49:05.500171 +0800 INFO frontend/util.go:498 time of Exec.Run : 27.042967ms connectionId 1157
2022/11/08 00:49:05.500275 +0800 INFO frontend/util.go:483 query trace status {"connection_id": 1157, "statement": "select c from sbtest3 where id = 4169", "status": "success", "session_info": "connectionId 1157"}
2022/11/08 00:49:05.500578 +0800 INFO frontend/util.go:483 query trace {"connection_id": 1157, "query": "select c from sbtest2 where id = 6275;", "session_info": "connectionId 1157"}
2022/11/08 00:49:05.501399 +0800 INFO frontend/util.go:498 time of Exec.Build : 11.215733ms
panic: interface conversion: interface {} is ^@^Ac^@^Ad^@^Ae^@^Af^@^Ag^@^Ah^@^Ai^@^Aj^@^Ak^@^Al^@^Am^@^An^@^Ao^@^Ap^@^Aq^@^Ar^@^As^@^At^@^Au^@^Av^@^Aw^@^Ax^@^Ay^@^Az^@^Bio^@^Bos^@^B.F^A^BAs^A^BAt^A^BBf^A^B, not chan struct {}

goroutine 147885 [running]:
context.(*cancelCtx).Done(0xc01777e980?)
        /usr/local/go/src/context/context.go:361 +0x1d4
context.propagateCancel({0x296a5a0, 0xc03d756000}, {0x293d558, 0xc01777e980})
        /usr/local/go/src/context/context.go:251 +0x35
context.WithCancel({0x296a5a0, 0xc03d756000})
        /usr/local/go/src/context/context.go:237 +0xc5
github.com/matrixorigin/matrixone/pkg/vm/process.NewFromProc(0xc0386e4d80, {0x296a5a0, 0xc03d756000}, 0x0)
        /data1/sudong/mo-regression/matrixone/pkg/vm/process/process.go:60 +0x4c
github.com/matrixorigin/matrixone/pkg/vm/process.NewWithAnalyze(...)
        /data1/sudong/mo-regression/matrixone/pkg/vm/process/process.go:51
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).ParallelRun(0xc041e119a0, 0xc00c530680, 0x60?)
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:182 +0x44d
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0x296a5d8?, 0xc0211a7701?)
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:127 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0xc03ea58500?)
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:89 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /data1/sudong/mo-regression/matrixone/pkg/sql/compile/scope.go:84 +0x58d

### Expected Behavior

1. run mo with etc/launch-tae-CN-tae-DN/launch.toml
2. run sysbench mixed case test just for several seconds

how to run sysbench insert test:
1.git clone https://github.com/aressu1985/mo-load.git
2.modify mo addr in mo.yml
3.create database 
   create database sbtest;
4. git clone https://github.com/aressu1985/mo-sysbench.git
5.generate data 
cd mo-sysbench & sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_common.lua  --tables=10 --table_size=10000 --threads=1 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off prepare

6.run test 
  ./start.sh -c cases/sysbench/mixed_10_10000/

### Additional information

[server.log.panic.sysbench.tar.gz](https://github.com/matrixorigin/matrixone/files/9953970/server.log.panic.sysbench.tar.gz)

**Comment by nnsgmsone** [comment]
No progress for now.

**Comment by m-schen** [comment]
it can run smoothly for a few minutes, but various transaction related errors will be thrown later （e.g. Rollback ctx time out, commit ctx time out and so on.）. and sysbench test will failed and stop.

log here:
[6370issue.log.zip](https://github.com/matrixorigin/matrixone/files/9959712/6370issue.log.zip)

**Comment by m-schen** [comment]
I can't not reproduce the error in issue.

**Comment by fengttt** [comment]
I am not sure if this has something to do with pipeline/proc cleanup.    after your cleanup pr, run this in a loop for a while, if still cannot repro, we lower to s0.

**Comment by m-schen** [comment]
There is no time to pay attention to this issue today

**Comment by m-schen** [comment]
sysbench instability, it's too hard to repro it.

depends on #6437 solved.

**Comment by aressu1985** [comment]
tonight I will test it for a whole night

**Comment by m-schen** [comment]
how is it going. if errors happen again, send it back.

**Comment by aressu1985** [comment]
I has tested this for several days, it did not happen agin, can be cloesed
fixe:c12eb45b1314e80f11fe8883055982c8ab0ca7fd
