### ISSUE TITLE
[Subtask]:  Design doc for user-defined function

### ISSUE THREAD

**Issue by chrisxu333** [matrixorigin/matrixone#6380]
### Parent Issue

Parent issue: 6377

### Detail of Subtask

Write design doc for user defined function support. It should contains the design for SQL syntax, where to store the information, what protocol to use to communicate to python server, etc.

Link:[ ]

**Comment by fengttt** [comment]
I merged first draft doc.    Python server, how to start it, how to communicate, where will we store python module/source code, directory layout etc, should be added to the design doc.

Then Implementation plan

Then Test plan.
