### ISSUE TITLE
[Bug]: query get empty results

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#6385]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Data: [log.txt](https://github.com/matrixorigin/matrixone/files/9957095/log.txt)

Query: `select * from log l1 where (select count(*) from log l2 where l1.device = l2.device and l1.day < l2.day) < 1`.
This query finds the latest date value for each device.

Attention: `day` is key word, use \`day\`.

Output 0 line.

### Expected Behavior

Output 1000 lines.

Output in Mysql:
![图片](https://user-images.githubusercontent.com/28624654/200460686-5c48ecff-f4e9-4899-9bec-547abc246645.png)

**Comment by aunjgr** [comment]
Predicate pull-up, the subquery flattening approach we are using, cannot handle correlated column in non-equi predicate in a scalar subquery. It won't be resolved until a refactor of query plan is done.

Anyway, we should report error instead of generating and running a wrong plan silently.

**Comment by badboynt1** [comment]
for this situation, we report an error now. will be supported in the future
