### ISSUE TITLE
[Bug]: PRIMARY KEY doesn't work

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6388]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a5bff6fc79f6a03ccfb0bd6aede7f36e80829813
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

config file:etc/launch-tae-CN-tae-DN/launch.toml

<img width="573" alt="image" src="https://user-images.githubusercontent.com/88298673/200476374-69128257-4f88-4944-80fc-9cf3e585f6b0.png">

**Comment by domingozhang** [comment]
mysql> update t1 set a=2 where a=3;
ERROR 20101 (HY000): internal error: panic unexpected parameter types were received: 
github.com/matrixorigin/matrixone/pkg/container/vector.MustTCols[...]
	/var/root/matrixone/pkg/container/vector/tools.go:55
github.com/matrixorigin/matrixone/pkg/sql/colexec/update.FilterBatch
	/var/root/matrixone/pkg/sql/colexec/update/update.go:211
github.com/matrixorigin/matrixone/pkg/sql/colexec/update.Call
	/var/root/matrixone/pkg/sql/colexec/update/update.go:73
github.com/matrixorigin/matrixone/pkg/vm.Run
	/var/root/matrixone/pkg/vm/vm.

**Comment by iamlinjunhong** [comment]
This needs to be discussed with the person who designed the transaction:
![Uploading 截屏2022-11-08 下午4.29.20.png…]()

**Comment by domingozhang** [comment]
It's an optimistic transaction related problem. In progress of investigation.

**Comment by iamlinjunhong** [comment]
> It's an optimistic transaction related problem. In progress of investigation.

I don't think the primary key constraint is related to the transaction

**Comment by fengttt** [comment]
Should be checked by CN

**Comment by reusee** [comment]
OK, I'm working on this issue.

**Comment by nnsgmsone** [comment]
cn really have to do strict primary key constraints？ (i.e. and all the data to do the testing)

**Comment by reusee** [comment]
The same as https://github.com/matrixorigin/matrixone/issues/6312#issuecomment-1306637110

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
This issue is tracked in https://github.com/matrixorigin/matrixone/issues/6949
