### ISSUE TITLE
[Bug]: cte bvt test No result for a long time

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#6398]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

./mo-service  -launch ./etc/launch-tae-CN-tae-DN/launch.toml 
在main分支上：

create table t1(a int);
insert into t1 values(1),(2);

with qn(a) as (select 1 from t1 limit 2)
select * from qn where qn.a=(select * from qn qn1 limit 1) union select 2;

Actual operation results：
mysql> with qn(a) as (select 1 from t1 limit 2)
    -> select * from qn where qn.a=(select * from qn qn1 limit 1) union select 2;
.......
Long running without results

Exception Log：
2022/11/08 15:49:09.251550 +0800 INFO moerr/error.go:420 error: unexpteded end of file EOF {"span": {}}
{"level":"DEBUG","time":"2022/11/08 15:49:09.251503 +0800","caller":"morpc/backend.go:573","msg":"read response","remote":"127.0.0.1:6002","request-id":652,"response":"sid: 0, cmd: 0, data: \n\ufffd\ufffd\u0006\u0001\u0002\ufffd\ufffd\u0000\u0000\u0000\u0016\ufffd\ufffd\u0002\u0001\u0001\u0008[]string\u0001\ufffd\ufffd\u0000\u0001\u000c\u0000\u0000\r\ufffd\ufffd\u0002\u0001\u0002\ufffd\ufffd\u0000\u0001\ufffd\ufffd\u0000\u0000\n\ufffd\ufffd\u0006\u0001\u0002\ufffd\ufffd\u0000\u0000\u0000Q\ufffd\ufffd\u0003\u0001\u0001\u0004Type\u0001\ufffd\ufffd\u0000\u0001\u0006\u0001\u0003Oid\u0001\u0006\u0000\u0001\u0007Charset\u0001\u0006\u0000\u0001\u0004Size\u0001\u0004\u0000\u0001\u0005Width\u0001\u0004\u0000\u0001\u0005Scale\u0001\u0004\u0000\u0001\tPrecision\u0001\u0004\u0000\u0000\u0000\u001b\ufffd\ufffd\u0003\u0001\u0001\u0005Nulls\u0001\ufffd\ufffd\u0000\u0001\u0001\u0001\u0002Np\u0001\ufffd\ufffd\u0000\u0000\u0000\n\ufffd\ufffd\u0006\u0001\u0002\ufffd\ufffd\u0000\u0000\u0000\u000c\ufffd\ufffd\u0002\u0001\u0002\ufffd\ufffd\u0000\u0001\u0004\u0000\u0000\r\ufffd\ufffd\u0002\u0001\u0002\ufffd\ufffd\u0000\u0001\ufffd\ufffd\u0000\u0000\u001d\ufffd\ufffd\u0006\u0001\u0001\u0011Agg[interface {}]\u0001\ufffd\ufffd\u0000\u0000\u0000\ufffd\u0007G\ufffd\ufffd\u0000\ufffd\u0007AD\ufffd\ufffd\u0003\u0001\u0001\u000bEncodeBatch\u0001\ufffd\ufffd\u0000\u0001\u0004\u0001\u0002Zs\u0001\ufffd\ufffd\u0000\u0001\u0004Vecs\u0001\ufffd\ufffd\u0000\u0001\u0005Attrs\u0001\ufffd\ufffd\u0000\u0001\u0008AggInfos\u0001\ufffd\ufffd\u0000\u0000\u0000\u000c\ufffd\ufffd\u0002\u0001\u0002\ufffd\ufffd\u0000\u0001\u0004\u0000\u0000\r\ufffd\ufffd\u0002\u0001\u0002\ufffd\ufffd\u0000\u0001\ufffd\ufffd\u0000\u0000\n\ufffd\ufffd\u0006\u0001\u0002\ufffd\ufffd\u0000\u0000\u0000Q\ufffd\ufffd\u0003\u0001\u0001\u0004Type\u0001\ufffd\ufffd\u0000\u0001\u0006\u0001\u0003Oid\u0001\u0006\u0000\u0001\u0007Charset\u0001\u0006\u0000\u0001\u0004Size\u0001\u0004\u0000\u0001\u0005Width\u0001\u0004\u0000\u0001\u0005Scale\u0001\u0004\u0000\u0001\tPrecision\u0001\u0004\u0000\u0000\u0000\u001b\ufffd\ufffd\u0003\u0001\u0001\u0005Nulls\u0001\ufffd\ufffd\u0000\u0001\u0001\u0001\u0002Np\u0001\ufffd\ufffd\u0000\u0000\u0000\n\ufffd\ufffd\u0006\u0001\u0002\ufffd\ufffd\u0000\u0000\u0000\u0016\ufffd\ufffd\u0002\u0001\u0001\u0008[]string\u0001\ufffd\ufffd\u0000\u0001\u000c\u0000\u0000\u001e\ufffd\ufffd\u0002\u0001\u0001\u000f[]batch.aggInfo\u0001\ufffd\ufffd\u0000\u0001\ufffd\ufffd\u0000\u0000\u0013\ufffd\ufffd\u0006\u0001\u0001\u0007aggInfo\u0001\ufffd\ufffd\u0000\u0000\u0000\u001d\ufffd\ufffd\u0006\u0001\u0001\u0011Agg[interface {}]\u0001\ufffd\ufffd\u0000\u0000\u0000\ufffd\u0005\ufffd\ufffd\ufffd\u0001\u0006\u0002\u0002\u0002\u0002\u0002\u0002\u0001\nA\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0016\u0000\u0000\u0000\u0004\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0018\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0003\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0001\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000=\u0000\u0000\u0000\u0018\u0000\u0000\u00002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\u0000\u0000\u0000\u0000$\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd$\u0000\u0000\u0000.\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffdR\u0000\u0000\u0000\u001c\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffdn\u0000\u0000\u0000&\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\ufffd\u0000\u0000\u0000$\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\ufffd\u0000\u0000\u0000.\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0000\u0000\u0000ETL_merge_task/system.statement_infoETL_merge_task/system.statement_info/yesterdayETL_merge_task/system.rawlogETL_merge_task/system.rawlog/yesterdayETL_merge_task/system_metrics.metricETL_merge_task/system_metrics.metric/yesterdayA\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0016\u0000\u0000\u0000\u0004\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0018\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000F\u0000\u0000\u0000\u0018\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0000\u0000\u0000\u0015system.statement_info\u0000\u0000\ufffd\ufffd\ufffd\ufffd\u0000\u0000\u0000\u0000\u001f\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\rsystem.rawlog\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017system.rawlog yesterday\u0015system_metrics.metric\u0000\u0000\ufffd\ufffd\ufffd\ufffd\u001f\u0000\u0000\u0000\u001f\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000>\u0000\u0000\u0000system.statement_info yesterdaysystem_metrics.metric yesterday\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000=\u0000\u0000\u0000\u0018\u0000\u0000\u0000\ufffd\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0000\u0000\u0000\u0002{}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002{}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002{}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002{}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002{}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002{}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000=\u0000\u0000\u0000\u0018\u0000\u0000\u0000d\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0000\u0000\u0000\u00160 0 4,8,12,16,20 * * *\u0000\u000b0 5 0 * * *\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00160 0 4,8,12,16,20 * * *\u0000\u000b0 5 0 * * *\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00160 0 4,8,12,16,20 * * *\u0000\u000b0 5 0 * * *\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000Y\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0000\u0000\u0000\u0008\u0000\u0000\u0000@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00000\u0000\u0000\u0000\u0000\ufffd@V\ufffd\u0001\u0000\u0000\ufffd\ufffd\ufffdW\ufffd\u0001\u0000\u0000\u0000\ufffd@V\ufffd\u0001\u0000\u0000\ufffd\ufffd\ufffdW\ufffd\u0001\u0000\u0000\u0000\ufffd@V\ufffd\u0001\u0000\u0000\ufffd\ufffd\ufffdW\ufffd\u0001\u0000\u0000\u0000\u0000\u0000\u0000A\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0016\u0000\u0000\u0000\u0004\u0000\u0000\u0000 \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0018\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000Y\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0000\u0000\u0000\u0008\u0000\u0000\u0000@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00000\u0000\u0000\u0000\ufffd\ufffd\u001aV\ufffd\u0001\u0000\u0000\ufffd\ufffd\u001aV\ufffd\u0001\u0000\u0000\ufffd\ufffd\u001aV\ufffd\u0001\u0000\u0000\u0004\ufffd\u001aV\ufffd\u0001\u0000\u0000G\ufffd\u001aV\ufffd\u0001\u0000\u0000{\ufffd\u001aV\ufffd\u0001\u0000\u0000\u0000\u0000\u0000\u0000Y\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0017\u0000\u0000\u0000\u0008\u0000\u0000\u0000@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00000\u0000\u0000\u0000\ufffd\ufffd\u001aV\ufffd\u0001\u0000\u0000\ufffd\ufffd\u001aV\ufffd\u0001\u0000\u0000\ufffd\ufffd\u001aV\ufffd\u0001\u0000\u0000\u0004\ufffd\u001aV\ufffd\u0001\u0000\u0000G\ufffd\u001aV\ufffd\u0001\u0000\u0000{\ufffd\u001aV\ufffd\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000, err: "}

**Comment by qingxinhome** [comment]
For cte sql running in a distributed environment for a long time without results, I mentioned issue. Please know.   @nnsgmsone 
 @domingozhang @tianyahui-python

**Comment by yingfeng** [comment]
Caused by #6378

**Comment by m-schen** [comment]
I have fixed the bug. plz verify it.

**Comment by aressu1985** [comment]
fixed:b9c225f4f44dcd62d6f577394d705b6aed55188e

mysql> create database test;
Query OK, 0 rows affected (0.01 sec)

mysql> use test;
Database changed
mysql> 
mysql> 
mysql> create table t1(a int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 values(1),(2);
Query OK, 2 rows affected (0.02 sec)

mysql> with qn(a) as (select 1 from t1 limit 2)
    -> select * from qn where qn.a=(select * from qn qn1 limit 1) union select 2;
+------+
| a    |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.03 sec)

mysql>
