### ISSUE TITLE
[Bug]: cn restart more than 120 times when mo run on eks with 1-cn-1dn-3log(s3)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6400]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e23e00f1d01d43e33c509a6d239ccc38b5f93409
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When MO run on EKS with 1-cn-1dn-3log(s3) for more than 12 hours, the cn pod restarts more 120times;

sudong@sudongdeMacBook-Pro expression % kubectl -n sudong get pod                       
NAME             READY   STATUS    RESTARTS        AGE
mo-dis-dn-0      1/1     Running   1 (15h ago)     15h
mo-dis-log-0     1/1     Running   0               15h
mo-dis-log-1     1/1     Running   0               15h
mo-dis-log-2     1/1     Running   0               15h
mo-dis-tp-cn-0   1/1     Running   124 (53s ago)   15h
test             1/1     Running   0               2d2h
sudong@sudongdeMacBook-Pro expression % kubectl -n sudong get pod
NAME             READY   STATUS    RESTARTS        AGE
mo-dis-dn-0      1/1     Running   1 (15h ago)     15h
mo-dis-log-0     1/1     Running   0               15h
mo-dis-log-1     1/1     Running   0               15h
mo-dis-log-2     1/1     Running   0               15h
mo-dis-tp-cn-0   1/1     Running   124 (68s ago)   15h
test             1/1     Running   0               2d2h

### Additional information

[Uploading temp.log…]()

**Comment by daviszhen** [comment]
I am working on the issue #6421 today

**Comment by daviszhen** [comment]
I do not focus on this case today.

**Comment by daviszhen** [comment]
I do not focus on this case today.

**Comment by daviszhen** [comment]
I am not working on it today.

**Comment by fengttt** [comment]
Not repro/actionable.    Maybe relates to the several other restart/reply bugs.

I think we should close.

**Comment by aressu1985** [comment]
fixed
