### ISSUE TITLE
[Bug]: select count external s3 1000w+ rows error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6410]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):81ea03dc2eb85ba4744ce142e66728ec037b8c25
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
three questions：
1.select count 1000w+reported context deadline exceeded
2.select 1000w+ limit no results back for long long time
3.The specified s3 file （1000w+）compression format does not match the file compression format，select  no error back for long long time
![image](https://user-images.githubusercontent.com/113406637/200719163-24ea28aa-3fab-4286-8bb0-452c1eff508f.png)

**Comment by heni02** [comment]
s3 file size：
![image](https://user-images.githubusercontent.com/113406637/200566704-4636e78b-5a0f-489f-888c-52b8aee6a76c.png)

**Comment by reusee** [comment]
> it cost almost 6 mins to get the result. <img alt="image" width="777" src="https://user-images.githubusercontent.com/32733096/200731016-068bb34f-9812-4dcd-877c-6ffc068f1afc.png"> And I find it is due to this code line
> 
> https://github.com/matrixorigin/matrixone/blob/91db699724193575ebfe6e75f36d25be9e927c27/pkg/sql/colexec/external/external.go#L228
> 
> this function cost 6min. So could you help to find the reason. @reusee

It seems to me that the slow network speed between S3 and the testing machine causes this.

**Comment by reusee** [comment]
@heni02 You could try re-running this test on Tencent S3 or a minio server to see whether it's still slow to load.

**Comment by heni02** [comment]
@reusee @jianwan0214 cos shanghai test results:
![image](https://user-images.githubusercontent.com/113406637/200757915-8a267b7a-3860-486a-bef6-c73af0c4494d.png)
![image](https://user-images.githubusercontent.com/113406637/200758018-c26df74b-1937-4ace-b604-edba81cd1e7b.png)
![image](https://user-images.githubusercontent.com/113406637/200758703-72418c38-f2a0-4279-803e-49c48b7b1c2b.png)

**Comment by heni02** [comment]
external table read local file：
![image](https://user-images.githubusercontent.com/113406637/200759804-cfb4c9a7-52f6-496b-97ce-3dbd11c2ea5c.png)
![image](https://user-images.githubusercontent.com/113406637/200760029-c3d56820-c2c9-4666-872e-4b7fe0ecc7ef.png)

**Comment by reusee** [comment]
> @reusee @jianwan0214 cos shanghai test results: ![image](https://user-images.githubusercontent.com/113406637/200757915-8a267b7a-3860-486a-bef6-c73af0c4494d.png) ![image](https://user-images.githubusercontent.com/113406637/200758018-c26df74b-1937-4ace-b604-edba81cd1e7b.png) ![image](https://user-images.githubusercontent.com/113406637/200758703-72418c38-f2a0-4279-803e-49c48b7b1c2b.png)

So it is working as expected. The most time cost is network transport.

**Comment by reusee** [comment]
I believe this result is working as expected. This issue should be marked as fixed.

**Comment by reusee** [comment]
waiting for reply from @heni02

**Comment by heni02** [comment]
confirm,closed
commit id:d62fb88678b851dacfa27471cd1a5813cf51346e
![image](https://user-images.githubusercontent.com/113406637/206686017-50817d76-9100-4b75-a3ce-3364198c085e.png)
