### ISSUE TITLE
[Bug]: "system_metrics" db "process_open_fds"  table no data.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6433]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

use system_metrics;
select * from process_open_fds;

<img width="1131" alt="截屏2022-11-09 15 40 02" src="https://user-images.githubusercontent.com/39303074/200768440-1fe83e2e-8f0c-42c6-8657-1c1960d68fc6.png">

**Comment by xzxiong** [comment]
@tianyahui-python note that  MAC not support.

**Comment by xzxiong** [comment]
in linux is ok.

**Comment by tianyahui-python** [comment]
When is mac support planned @xzxiong

**Comment by xzxiong** [comment]
@tianyahui-python currently, there is NO plan to implement this metric in macOS. 
> if want to collect this metic with Golang, we need to call cgo to call c-api.
