### ISSUE TITLE
[Bug]: expect total two transaction, actual four transaction.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6435]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

execute sql:
```
set @@autocommit=1;
drop database if exists test_2;
begin;
create database test_2;
use test_2;
create table t1(a int, b varchar);
desc t1;
insert into t1 values(1, 'a');
insert into t1 values(2, 'b');
insert into t1 values(3, 'c');
insert into t1 values(4, 'd');
insert into t1 values(5, 'e');
update t1 set a=10 where b='a';
update t1 set a=20 where b='b';
update t1 set a=30 where b='c';
update t1 set a=40 where b='d';
update t1 set a=50 where b='e';
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
delete from t1 where a=10;
delete from t1 where a=20;
delete from t1 where a=30;
delete from t1 where a=40;
delete from t1 where a=50;
commit;
```

"system_metrics" database "sql_transaction_total" table value total error.

use  system_metrics;
select * from sql_transaction_total order by collecttime desc limit 10;

**Comment by xzxiong** [comment]
with `autocommit=1`, `commit` statement will trigger 2 times commit in `Session::TxnCommit` and `Session::TxnCommitSingleStatement`

with `autocommit=0`, `commit` statement only trigger 1 time.

**Comment by xzxiong** [comment]
there are 4 txn
1. set @@auto

**Comment by tianyahui-python** [comment]
set @@autocommit=1; Should it be a separate transaction ?
@xzxiong

**Comment by xzxiong** [comment]
it is NOT.
