### ISSUE TITLE
[Enhancement]: Add a hidden column to external table output

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6436]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Let's assume an external table has three columns a, b, c
select * from exttable;     -- should have 3 columns.

Let's add a hidden column, __mo_filepath, so that 

select __mo_filepath, a, b, c from exttable can return the file path with data.
```

### Why is this needed ?

We want to prune, for example, the following query will read data from one day

select * from exttable where __mo_filepath like '%2022/11/11%'

For executor, if the file path does not match 2022/11/11, we should not even read the file.

**Comment by fengttt** [comment]
adding __mo_modified_ts as well.

**Comment by daviszhen** [comment]
> adding __mo_modified_ts as well.

The fileservice should provide the "__mo_modified_ts".

**Comment by daviszhen** [comment]
the filepath duplicate with 6612

**Comment by sukki37** [comment]
@aressu1985 This issue needs a comparative performance benchmark.
