### ISSUE TITLE
[Bug]: create database 'w-w conflict'.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6443]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
commit id : 8f0a8480d6d47efa22d5cdce3e4ee1f32f02e54b

./mo-service -launch ./etc/launch-tae-logservice/launch.toml > mo.log 2>&1 &

Reproducible Steps:

self.client_1_execute("set @@autocommit=1;")
self.client_2_execute("set @@autocommit=1;")
self.client_1_execute("drop database if exists test_1;")
self.client_1_execute("create database test_1;")
self.client_1_execute("use test_1;")
self.client_1_execute("create table t1(a int primary key, b varchar);")
self.client_1_execute("begin;")
self.client_1_execute("insert into t1 values (1,'a');")
self.client_2_execute("use test_1;")
self.client_2_execute("begin;")
self.client_2_execute("insert into t1 values (1,'a');")
self.client_2_execute("commit;")
self.client_1_execute("commit;")    execute failed, w-w conflict

self.client_1_execute("set @@autocommit=1;")
self.client_2_execute("set @@autocommit=1;")
self.client_1_execute("drop database if exists test_1;")
self.client_1_execute("create database test_1;")         execute failed, w-w conflict.

**Comment by triump2020** [comment]
It's not reproducible temporarily, using latest main branch.

**Comment by triump2020** [comment]
It  has not been reproduced so far  using the latest main branch , and the commit id  8f0a8480d6d47efa22d5cdce3e4ee1f32f02e54b had not been found .   @tianyahui-python

**Comment by XuPeng-SH** [comment]
Not reproduced. Downgrade it to s2

**Comment by triump2020** [comment]
Not reproduced!  Close it
