### ISSUE TITLE
[Bug]: OOM has occured when insert to MO with multi-thread

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#6459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit fcda32551ba7076fa24b8156b5d374da253220c1
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml &> mo.log &
run MO on my local machine. RAM is 8G.

mo.log information : 
2022/11/09 16:18:28.258643 +0800 INFO frontend/util.go:495 query trace {"connection_id": 1117, "query": "insert into t (title, author, write_date) values ('MySQL测试', 'MySQL测试', NOW());", "session_info": "connectionId 1117"}
2022/11/09 16:18:28.341519 +0800 INFO frontend/util.go:495 query trace status {"connection_id": 1113, "statement": "commit", "status": "success", "session_info": "connectionId 1113"}
2022/11/09 16:18:28.341931 +0800 INFO frontend/util.go:510 time of Exec.Run : 9.373117207s connectionId 1116
2022/11/09 16:18:28.341972 +0800 INFO frontend/util.go:510 time of SendResponse 271ns connectionId 1116
2022/11/09 16:18:28.342073 +0800 INFO frontend/util.go:495 query trace status {"connection_id": 1116, "statement": "insert into t (title, author, write_date) values (\"MySQL测试\", \"MySQL测试\", now())", "status": "success", "session_info": "connectionId 1116"}
2022/11/09 16:18:28.376471 +0800 INFO frontend/util.go:495 query trace {"connection_id": 1116, "query": "COMMIT", "session_info": "connectionId 1116"}
2022/11/09 16:18:28.376695 +0800 INFO frontend/util.go:495 query trace {"connection_id": 1113, "query": "insert into t (title, author, write_date) values ('MySQL测试', 'MySQL测试', NOW());", "session_info": "connectionId 1113"}
2022/11/09 16:18:28.434863 +0800 INFO frontend/util.go:495 query trace status {"connection_id": 4294967295, "statement": "start transaction", "status": "success", "session_info": ""}
2022/11/09 16:18:28.435586 +0800 INFO frontend/util.go:495 query trace status {"connection_id": 4294967295, "statement": "commit", "status": "success", "session_info": ""}
2022/11/09 16:18:28.436527 +0800 INFO frontend/util.go:510 time of Exec.Build : 12.953316493s connectionId 1069
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x2587af6?, 0x2030?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f1a9fffeca8 sp=0x7f1a9fffec78 pc=0x448dbd
runtime.sysMapOS(0xc07fc00000, 0x5400000?)
	/usr/local/go/src/runtime/mem_linux.go:187 +0x11b fp=0x7f1a9fffecf0 sp=0x7f1a9fffeca8 pc=0x429a5b
runtime.sysMap(0x3d25780?, 0x7f1ad0929000?, 0x43cec0?)
	/usr/local/go/src/runtime/mem.go:142 +0x35 fp=0x7f1a9fffed20 sp=0x7f1a9fffecf0 pc=0x429435
runtime.(*mheap).grow(0x3d25780, 0x286d?)
	/usr/local/go/src/runtime/mheap.go:1459 +0x23d fp=0x7f1a9fffed90 sp=0x7f1a9fffed20 pc=0x439f7d
runtime.(*mheap).allocSpan(0x3d25780, 0x286d, 0x0, 0x1)
	/usr/local/go/src/runtime/mheap.go:1191 +0x1be fp=0x7f1a9fffee28 sp=0x7f1a9fffed90 pc=0x4396de
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:910 +0x65 fp=0x7f1a9fffee70 sp=0x7f1a9fffee28 pc=0x439165
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x7f1a9fffee78 sp=0x7f1a9fffee70 pc=0x47af49

Reproduction Steps : 
1. launch MO
2. create database test;
3. use test;
4. DDL : 
create table t(
	title varchar(50),
	author varchar(50),
	write_date datetime
);
5. change multi-thread_insert.txt to multi-thread_insert.py ,  then execute this py script
[multi-thread_insert.txt](https://github.com/matrixorigin/matrixone/files/9976935/multi-thread_insert.txt)

**Comment by fengttt** [comment]
The repro script is not included properly.   Please retry, and if it still repros, assign it to @jianwan0214 for initial investigation, memory profiling of insert.

**Comment by goodMan-code** [comment]
I have Recheck it on commit d0a0684b53bc0b423a90361af3f483dc56860bf5, no problem, can be closed.
