### ISSUE TITLE
[Refactoring]: PR 6462 the fix is not good

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6469]
### Why do you want to refactor this code?

```Markdown
PR 6462 fixes newReader bug by making a copy of ModifyBlockMeta. 

https://github.com/matrixorigin/matrixone/pull/6462

If we did it correctly, we should have never modified this ModifyBlockMeta (because we are READER).
The copy could be a performance problem.
```

### Describe the solution you'd like

Need refactor and this copy should be avoided.

**Comment by ouyuanning** [comment]
After discussion with @nnsgmsone .
we agree with that should not have data race. but it really get race now.
we will check with some tool tomorrow to find why.

**Comment by ouyuanning** [comment]
we find that  scope.ParallelRun  will run muti(like 10) times in one query.
and they will use the same relation(for disttae, that will be a table)
table.NewReader will get lots of blockMergeReader to share one table.
blockMergeReader.Read will change reader.blks[x].deletes (these blks are ref of table.meta.modifedBlocks).   then data race happen.

now we need to find why scope.ParallelRun will call muti times in one query.
