### ISSUE TITLE
[Bug]: update delta location for blocks compacted by mergeblocks

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6477]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

update delta location for blocks compacted by mergeblocks.

**Comment by LeftHandCold** [comment]
I didn't work on it today

**Comment by LeftHandCold** [comment]
I didn't work on it today
