### ISSUE TITLE
[Feature Request]: make MO version configurable

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6479]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
https://github.com/matrixorigin/matrixone/issues/6367
https://github.com/matrixorigin/matrixone/issues/6478
```

### Describe the feature you'd like

Our upgrade of version to 8.0 fixed the issue of mysql workbench and sqlalchemy, but caused new problems of Navicat and Java ORM. 
We can make this version number configurable to adapt.

**Comment by fengttt** [comment]
Wait -- do we want to do that?   I don't think so, we report a version that says our server will support a protocol at that version and change it does not really help (we either support or not and there will be code in order to support).

**Comment by dengn** [comment]
this one is already implemented.  
But this is a temporary solution to adapt to different client tools and ORMs. The rightful way is to keep a 8.0.30 version compatibility and fix all blocking incampabilities.
