### ISSUE TITLE
[Bug]: panic for SELECT * FROM schemata order by catalog_name limit 5;

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#6483]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE VIEW SCHEMATA AS SELECT
dat_catalog_name AS CATALOG_NAME,
datname AS SCHEMA_NAME,
'utf8mb4' AS DEFAULT_CHARACTER_SET_NAME,
'utf8mb4_0900_ai_ci' AS DEFAULT_COLLATION_NAME,
NULL AS SQL_PATH,
'NO' AS DEFAULT_ENCRYPTION
FROM mo_catalog.mo_database;

SELECT * FROM schemata order by catalog_name limit 5;
The SQL query contains views and order by clauses, and the execution message is panic.

![image](https://user-images.githubusercontent.com/70939751/201078110-c278a801-203c-4bf0-841d-9350fb4d513e.png)

**Comment by heni02** [comment]
confirm,closed
commit id: 0ca18fd72cf4d3eda0e03c30f9fa82725f804f90
![image](https://user-images.githubusercontent.com/113406637/202685200-77684733-609d-4ec6-a65b-1e9bffb99116.png)
