### ISSUE TITLE
[Bug]: There exists a case where the obtained cn address is 0.0.0.0

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#6493]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

wrong address

**Comment by zhangxu19830126** [comment]
In the main branch, the configuration has been changed so that running multi-cn launch on ci does not get a 0.0.0.0 cn communication address
