### ISSUE TITLE
[Bug]: https://github.com/matrixorigin/matrixone/pull/6489 Not clear this is the right approach

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6501]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/pull/6489  We cache all writes in DN, before commit.   We have already did this in CN, and if CN combine write with commit, DN should not need to do this.

@reusee @nnsgmsone

**Comment by triump2020** [comment]
> @triump2020 how about
> 
> 1. combine 1PC CN->DN write and commit message.
> 2. on DN side, if we see a 1PC message with both write and commit, we do not need to cache writes.

As  per our discussion :   Get  #6489 in.
