### ISSUE TITLE
[Bug]:  The loaded memory is also not freed correctly.

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#6536]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The loaded memory is also not freed correctly. A very simple way to verify this is to replace the make of mpool with the malloc of c. This will block the gc of go, and the problem of unfree memory can be easily seen.

### Steps to Reproduce

```Markdown
run tpch step by step;
```

**Comment by fengttt** [comment]
Why you need the malloc hack?    Turn on mpool details you should see leak immediately.

mpool has a tag, so we should know by now which pool is leaking.    Is session pool destroyed properly when disconnect?

**Comment by daviszhen** [comment]
@iamlinjunhong  help to fix it.

**Comment by iamlinjunhong** [comment]
load 1G data. select mo_memory_usage(""):
[{
	"global": {
		"alloc": 707182,
		"free": 611307,
		"goalloc": 0,
		"allocBytes": 24416576105,
		"freeBytes": 22384057686,
		"currBytes": 2032518419,
		"highWaterMark": 2398761115
	}
}, {
	"tae_cache": {
		"alloc": 7,
		"free": 0,
		"goalloc": 0,
		"allocBytes": 16760832,
		"freeBytes": 0,
		"currBytes": 16760832,
		"highWaterMark": 16760832
	}
}, {
	"tae_immutable": {
		"alloc": 17360,
		"free": 17353,
		"goalloc": 0,
		"allocBytes": 4971428064,
		"freeBytes": 4965464288,
		"currBytes": 5963776,
		"highWaterMark": 517438464
	},
	"Fixed-0": {
		"alloc": 323,
		"free": 323,
		"goalloc": 0,
		"allocBytes": 12845,
		"freeBytes": 12845,
		"currBytes": 0,
		"highWaterMark": 1433
	},
	"Fixed-1": {
		"alloc": 1245,
		"free": 1245,
		"goalloc": 0,
		"allocBytes": 118986,
		"freeBytes": 118986,
		"currBytes": 0,
		"highWaterMark": 2432
	},
	"Fixed-2": {
		"alloc": 1229,
		"free": 1229,
		"goalloc": 0,
		"allocBytes": 234098,
		"freeBytes": 234098,
		"currBytes": 0,
		"highWaterMark": 1768
	},
	"Fixed-3": {
		"alloc": 1225,
		"free": 1225,
		"goalloc": 0,
		"allocBytes": 466332,
		"freeBytes": 466332,
		"currBytes": 0,
		"highWaterMark": 1516
	},
	"Fixed-4": {
		"alloc": 1220,
		"free": 1220,
		"goalloc": 0,
		"allocBytes": 928976,
		"freeBytes": 928976,
		"currBytes": 0,
		"highWaterMark": 3328
	},
	"Fixed-5": {
		"alloc": 1216,
		"free": 1216,
		"goalloc": 0,
		"allocBytes": 1852576,
		"freeBytes": 1852576,
		"currBytes": 0,
		"highWaterMark": 7680
	},
	"Fixed-6": {
		"alloc": 1212,
		"free": 1212,
		"goalloc": 0,
		"allocBytes": 3691820,
		"freeBytes": 3691820,
		"currBytes": 0,
		"highWaterMark": 7168
	}
}, {
	"fallback_proc_mp": {
		"alloc": 11791,
		"free": 5502,
		"goalloc": 0,
		"allocBytes": 176297,
		"freeBytes": 140340,
		"currBytes": 35957,
		"highWaterMark": 36197
	}
}, {
	"session": {
		"alloc": 12232,
		"free": 11894,
		"goalloc": 0,
		"allocBytes": 2898485,
		"freeBytes": 2894893,
		"currBytes": 3592,
		"highWaterMark": 8676
	}
}, {
	"tae_log": {
		"alloc": 7,
		"free": 0,
		"goalloc": 0,
		"allocBytes": 5963776,
		"freeBytes": 0,
		"currBytes": 5963776,
		"highWaterMark": 5963776
	}
}, {
	"distributed_tae": {
		"alloc": 461279,
		"free": 372102,
		"goalloc": 0,
		"allocBytes": 4931655805,
		"freeBytes": 2986569215,
		"currBytes": 1945086590,
		"highWaterMark": 1945088446
	}
}, {
	"zero_fixed_mp_for_test": ""
}, {
	"session": {
		"alloc": 13944,
		"free": 13944,
		"goalloc": 0,
		"allocBytes": 3294816,
		"freeBytes": 3294816,
		"currBytes": 0,
		"highWaterMark": 5092
	}
}, {
	"session": {
		"alloc": 17,
		"free": 14,
		"goalloc": 0,
		"allocBytes": 165,
		"freeBytes": 141,
		"currBytes": 24,
		"highWaterMark": 48
	}
}, {
	"tae_default": {
		"alloc": 59877,
		"free": 59830,
		"goalloc": 0,
		"allocBytes": 11418386798,
		"freeBytes": 11359682926,
		"currBytes": 58703872,
		"highWaterMark": 530263227
	},
	"Fixed-0": {
		"alloc": 8583,
		"free": 8541,
		"goalloc": 0,
		"allocBytes": 326716,
		"freeBytes": 326368,
		"currBytes": 348,
		"highWaterMark": 3498
	},
	"Fixed-1": {
		"alloc": 6319,
		"free": 6317,
		"goalloc": 0,
		"allocBytes": 680598,
		"freeBytes": 680406,
		"currBytes": 192,
		"highWaterMark": 5020
	},
	"Fixed-2": {
		"alloc": 5581,
		"free": 5581,
		"goalloc": 0,
		"allocBytes": 1210126,
		"freeBytes": 1210126,
		"currBytes": 0,
		"highWaterMark": 8888
	},
	"Fixed-3": {
		"alloc": 5395,
		"free": 5394,
		"goalloc": 0,
		"allocBytes": 2340375,
		"freeBytes": 2339971,
		"currBytes": 404,
		"highWaterMark": 11776
	},
	"Fixed-4": {
		"alloc": 5076,
		"free": 5075,
		"goalloc": 0,
		"allocBytes": 4438127,
		"freeBytes": 4437295,
		"currBytes": 832,
		"highWaterMark": 21352
	},
	"Fixed-5": {
		"alloc": 4807,
		"free": 4807,
		"goalloc": 0,
		"allocBytes": 8446038,
		"freeBytes": 8446038,
		"currBytes": 0,
		"highWaterMark": 39424
	},
	"Fixed-6": {
		"alloc": 4042,
		"free": 4042,
		"goalloc": 0,
		"allocBytes": 14536201,
		"freeBytes": 14536201,
		"currBytes": 0,
		"highWaterMark": 73728
	}
}]
[pprof.zip](https://github.com/matrixorigin/matrixone/files/10021352/pprof.zip)
