### ISSUE TITLE
The query result is incorrect while runnning show tables from test01 where tables_in_test01 like '%t2%';

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#654]
#### Steps:
Create table t1 and t2, then run
mysql> show tables from test01 where tables_in_test01 like '%t2%';
+-------+
| Table |
+-------+
| t1    |
| t2    |
+-------+
2 rows in set (0.00 sec)

#### Expected behavior:
+-------+
| Table |
+-------+
| t2   |
+-------+

#### Actual behavior:
The query result is incorrect

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by daviszhen** [comment]
it was supported now
