### ISSUE TITLE
[Bug]: eks bvt test dn,cn,logservice pod crash restart

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6542]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:related to #6209 
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/201524068-a1892e5b-2b9d-49e5-9679-fabe10cb2114.png)

dn log:
{"level":"INFO","time":"2022/11/13 13:09:20.478554 +0000","caller":"trace/trace.go:124","msg":"init trace span processor"}
{"level":"INFO","time":"2022/11/13 13:09:20.498226 +0000","caller":"logservice/hakeeper_client.go:381","msg":"isHAKeeper: true, err: <nil>"}
{"level":"INFO","time":"2022/11/13 13:09:20.499538 +0000","caller":"db/open.go:48","msg":"open-tae","operation":"Start","operand":"open"}
panic: timeout

goroutine 75 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.newClient(0xc003235100, 0x10?, 0x2320fe0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go:51 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*clientpool).newClientFactory.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go:103 +0x36
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.newClientPool(0x64, 0x64, 0xc0036ba030)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go:95 +0x11f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.NewLogServiceDriver(0xc0005cc000)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go:79 +0x8e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store.NewStoreWithLogserviceDriver(0xc003235100)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/store/store.go:51 +0xca
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal.NewDriverWithLogservice(0xc0001af620?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/wal/driver.go:55 +0x19
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.Open({0xc0006320a0, 0x50}, 0x0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/open.go:90 +0x765
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.openTAE({0xc00012eb40, 0x4c}, 0xc00063dbf8?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:589 +0x172
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.NewTAEHandle({0xc00012eb40?, 0xc000646060?}, 0xc00063dbf8?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:66 +0x39
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.NewTAEStorage({0xc00012eb40, 0x4c}, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, 0x40004, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:56 +0x1af
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).newTAEStorage(0xc0030f9cc0, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, 0x40004, {0xc003627c00, ...}, ...}, ...)
        /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/factory.go:145 +0x15f
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).createTxnStorage(0xc0030f9cc0, {{0x2, 0x1, {}, {0x0, 0x0, 0x0}, 0x0}, 0x40004, {0xc003627c00, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/factory.go:73 +0x1ff
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).createReplica.func1({0x29f9570, 0xc0036a2c00})
        /go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store.go:329 +0x105
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:258 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:253 +0x12c

logservice:
{"level":"WARN","time":"2022/11/13 13:04:59.714882 +0000","name":"gossip","caller":"registry/gossip_logger.go:35","msg":"memberlist: Refuting a dead message (from: 00000000-0000-0000-0000-000000000002)"}
{"level":"WARN","time":"2022/11/13 13:04:59.737119 +0000","name":"gossip","caller":"registry/gossip_logger.go:35","msg":"memberlist: Failed to resolve heni-mo-dis-log-1.heni-mo-dis-log-headless.heni-test-mo.svc:32002: lookup heni-mo-dis-log-1.heni-mo-dis-log-headless.heni-test-mo.svc on 172.20.0.10:53: no such host"}
{"level":"INFO","time":"2022/11/13 13:04:59.772896 +0000","name":"dragonboat","caller":"v4@v4.0.0-20221031100441-62f1755ca7ab/nodehost.go:366","msg":"filesystem error injection mode enabled: false"}
{"level":"INFO","time":"2022/11/13 13:04:59.773243 +0000","name":"transport","caller":"transport/transport.go:238","msg":"transport type: go-tcp-transport"}
{"level":"ERROR","time":"2022/11/13 13:04:59.777890 +0000","name":"transport","caller":"transport/transport.go:240","msg":"transport failed to start lookup heni-mo-dis-log-2.heni-mo-dis-log-headless.heni-test-mo.svc on 172.20.0.10:53: no such host","stacktrace":"github.com/lni/dragonboat/v4/internal/transport.NewTransport\n\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221031100441-62f1755ca7ab/internal/transport/transport.go:240\ngithub.com/lni/dragonboat/v4.(*NodeHost).createTransport\n\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221031100441-62f1755ca7ab/nodehost.go:1825\ngithub.com/lni/dragonboat/v4.NewNodeHost\n\t/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221031100441-62f1755ca7ab/nodehost.go:370\ngithub.com/matrixorigin/matrixone/pkg/logservice.newLogStore\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:145\ngithub.com/matrixorigin/matrixone/pkg/logservice.NewService\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service.go:104\nmain.startLogService\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:214\nmain.startService\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:135\nmain.main\n\t/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:88\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"ERROR","time":"2022/11/13 13:05:00.215812 +0000","name":"log-service","caller":"logservice/service.go:106","msg":"failed to create log store","uuid":"00000000-0000-0000-0000-000000000002","error":"lookup heni-mo-dis-log-2.heni-mo-dis-log-headless.heni-test-mo.svc on 172.20.0.10:53: no such host"}
panic: lookup heni-mo-dis-log-2.heni-mo-dis-log-headless.heni-test-mo.svc on 172.20.0.10:53: no such host

goroutine 1 [running]:
main.startLogService(0xc00325e000, 0xc000060030?, {0x2a08740, 0xc00061dba8})
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:217 +0x329
main.startService(0xc00325e000, 0x4?)
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:135 +0x155
main.main()
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:88 +0x287
~

**Comment by heni02** [comment]
[cn0.log](https://github.com/matrixorigin/matrixone/files/9997297/cn0.log)
[cn1.log](https://github.com/matrixorigin/matrixone/files/9997301/cn1.log)
[dn0.log](https://github.com/matrixorigin/matrixone/files/9997302/dn0.log)

**Comment by volgariver6** [comment]
same as #6526

**Comment by volgariver6** [comment]
fixed by #6701 in main branch and #6702 in 0.6.0 branch.

**Comment by heni02** [comment]
I need to know in what specific scenarios there is no need to restart，tomorrow confirm

**Comment by heni02** [comment]
today, run bvt case to confirm

**Comment by heni02** [comment]
date 11.20 bvt case test, dn,cn,logservice pod all normal
<img width="645" alt="企业微信截图_c3374227-298d-4843-89e5-820b4c35a706" src="https://user-images.githubusercontent.com/113406637/202937427-e9ff9de8-1ec1-48c2-8b9e-9de9f8e049b7.png">

**Comment by heni02** [comment]
date 11.21 bvt case test，dn,cn,logservice pod all normal
image tag：0.6.0-2f62c7d
![image](https://user-images.githubusercontent.com/113406637/203196332-25b48356-0499-4a94-84e4-303100086acc.png)
![image](https://user-images.githubusercontent.com/113406637/203196453-27f6141c-8a6f-42ae-80cf-3665e1840588.png)

**Comment by heni02** [comment]
no restart problem occurs again, closed this issue
