### ISSUE TITLE
[Bug]: eks bvt test:show columns for table error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6545]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):image：nightly-6c8783c7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
eks bvt test result ，related to #6209 yaml configue
[ERROR]
[SCRIPT   FILE]: /matrixone/test/distributed/cases/dml/select/select.test
[ROW    NUMBER]: 197
[SQL STATEMENT]: show columns from t1;
[EXPECT RESULT]:
Field    Type    Null    Key    Default    Comment
a    INT    YES        NULL
[ACTUAL RESULT]:
Field    Type    Null    Key    Default    Extra    Comment
a    INT    YES        NULL

**Comment by iamlinjunhong** [comment]
This Comment field is the product requirement

**Comment by heni02** [comment]
The eks bvt test result has extra, but our daily ci test result does not include extra, please confirm the reason

**Comment by iamlinjunhong** [comment]
EXPECT RESULT is wrong.  The right result include extra.

**Comment by heni02** [comment]
The ci did not check the column name. This is not a problem. Close
