### ISSUE TITLE
[Bug]: eks bvt test:tpch q9.sql error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6546]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):nightly-6c8783c7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[ERROR]
[SCRIPT   FILE]: /matrixone/test/distributed/cases/benchmark/tpch/03_QUERIES/q9.sql
[ROW    NUMBER]: 34
[SQL STATEMENT]: select
nation,
o_year,
sum(amount) as sum_profit
from
(
select
n_name as nation,
extract(year from o_orderdate) as o_year,
l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
from
part,
supplier,
lineitem,
partsupp,
orders,
nation
where
s_suppkey = l_suppkey
and ps_suppkey = l_suppkey
and ps_partkey = l_partkey
and p_partkey = l_partkey
and o_orderkey = l_orderkey
and s_nationkey = n_nationkey
and p_name like '%pink%'
) as profit
group by
nation,
o_year
order by
nation,
o_year desc
;
[EXPECT RESULT]:
nation    o_year    sum_profit
ARGENTINA    1997    6575.493399999996
ARGENTINA    1996    12913.1476
ARGENTINA    1995    109908.39969999998
ARGENTINA    1994    39271.140400000004
ARGENTINA    1993    39770.69730000001
ARGENTINA    1992    35740.0
ETHIOPIA    1998    24489.149599999986
ETHIOPIA    1997    39665.26440000001
ETHIOPIA    1996    113173.09559999994
ETHIOPIA    1995    25732.7452
ETHIOPIA    1994    93731.1008
ETHIOPIA    1993    147385.872
ETHIOPIA    1992    66636.96160000001
IRAN    1998    116681.1813
IRAN    1997    50964.25839999999
IRAN    1996    185552.56340000004
IRAN    1995    103479.6512
IRAN    1994    164106.868
IRAN    1993    100245.65900000001
IRAN    1992    73757.954
IRAQ    1998    21292.037699999997
IRAQ    1997    128533.3496
IRAQ    1996    141170.6272
IRAQ    1995    16607.1624
IRAQ    1994    16515.2008
IRAQ    1993    138752.8297
IRAQ    1992    71365.98860000001
KENYA    1997    47549.35940000001
KENYA    1996    1866.6023999999998
KENYA    1995    13480.573400000003
KENYA    1994    54826.00119999999
KENYA    1993    111983.0035
KENYA    1992    7651.586600000001
MOROCCO    1998    225961.30579999997
MOROCCO    1997    288732.1257
MOROCCO    1996    295243.10189999995
MOROCCO    1995    255208.95809999996
MOROCCO    1994    158194.0814
MOROCCO    1993    159196.25280000002
MOROCCO    1992    256151.42539999998
PERU    1998    35151.868200000004
PERU    1997    99779.31980000006
PERU    1996    53735.25659999999
PERU    1995    71954.3164
PERU    1994    73084.5552
PERU    1993    95623.4989
PERU    1992    38212.4187
UNITED KINGDOM    1998    176649.9065
UNITED KINGDOM    1997    74705.25979999999
UNITED KINGDOM    1996    62768.51290000001
UNITED KINGDOM    1995    93466.7552
UNITED KINGDOM    1994    89094.2599
UNITED KINGDOM    1993    112886.5742
UNITED KINGDOM    1992    142060.96900000004
UNITED STATES    1997    111352.3559
UNITED STATES    1996    78268.86379999999
UNITED STATES    1995    251.2274
UNITED STATES    1994    57303.149999999994
UNITED STATES    1993    70350.5923
UNITED STATES    1992    65369.76119999998
[ACTUAL RESULT]:
nation    o_year    sum_profit

**Comment by nnsgmsone** [comment]
same as #6525, Please turn off this issue so that it will not be called noise.

**Comment by heni02** [comment]
same as #6525 confirm,closed
