### ISSUE TITLE
[Bug]: syntax error with select database 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6550]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 51dea20168f11b38c748518d7d53055bf1e08fc5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

to get info from statement_info and filter with database field, we will get syntax error. 

select * from statement_info where database != 'system'; 
> 1064 - SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 46 near " != 'system'";
> Time: 0s

Only with quotes will work. 
select * from statement_info where `database` != 'system';

**Comment by iamlinjunhong** [comment]
\`database\`  is mysql keyword, so it need to quote with \`\`
