### ISSUE TITLE
[Bug]: select from system.log_info compare `json` column NEED `like` op 

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6551]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 2dd39113e
- Hardware parameters:
- OS type: macbook M1
- Others: 
`./mo-service -launch ./etc/launch-tae-logservice/launch.toml`
```

### Actual Behavior

1.  startup mo
2. exec `mysql> show databases`
3. wait about 15s
4. exec `mysql> select * from system.log_info where json_extract(extra, '$.query') = 'show databases'` got empty result.
  - but with `like` condition, it is ok.
> PS: normal table is same result.

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/3927687/201559380-f90499ca-6ddb-4468-92d4-42ead1d1eddc.png">

```
mysql> select * from log_info where json_extract(extra, '$.query') like '%show databases%';
+--------------+------------------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+
| statement_id | span_id          | node_uuid                            | node_type | timestamp                  | logger_name | level | caller               | message     | extra                                                                                   | stack |
+--------------+------------------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+
| 0            | ddd57f95a0d703de | 00000000-0000-0000-0000-200000000000 | CN        | 2022-11-11 07:06:17.036127 |             | info  | frontend/util.go:495 | query trace | {"connection_id": 1011, "query": "show databases", "session_info": "connectionId 1011"} |       |
| 0            | ddd57f95a0d703de | 00000000-0000-0000-0000-200000000000 | CN        | 2022-11-11 08:29:46.017124 |             | info  | frontend/util.go:495 | query trace | {"connection_id": 1300, "query": "show databases", "session_info": "connectionId 1300"} |       |
| 0            | ddd57f95a0d703de | 00000000-0000-0000-0000-200000000000 | CN        | 2022-11-11 07:28:50.319145 |             | info  | frontend/util.go:495 | query trace | {"connection_id": 1081, "query": "show databases", "session_info": "connectionId 1081"} |       |
| 0            | ddd57f95a0d703de | 00000000-0000-0000-0000-200000000000 | CN        | 2022-11-11 08:24:54.222362 |             | info  | frontend/util.go:495 | query trace | {"connection_id": 1278, "query": "show databases", "session_info": "connectionId 1278"} |       |
+--------------+------------------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+
4 rows in set (5.96 sec)

mysql> select * from log_info where json_extract(extra, '$.query') = 'show databases';
Empty set (5.73 sec)
```

**Comment by qingxinhome** [comment]
After locating the problem, it is found that the SQL statement is misspelled. The reasons for the pronunciation are as follows
The 'show databases' statement is stored in system.log_info after execution, the records in the table are:
+----------+------------------+-----------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+
| trace_id | span_id          | span_kind | node_uuid                            | node_type | timestamp                  | logger_name | level | caller               | message     | extra                                                                                   | stack |
+----------+------------------+-----------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+
| 0        | 7c4dccb44d3c41f8 | internal  | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | ALL       | 2022-11-15 11:47:00.917233 |             | info  | frontend/util.go:495 | query trace | {"connection_id": 1003, "query": "show databases", "session_info": "connectionId 1003"} |       |
+----------+------------------+-----------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+
1 row in set (0.05 sec)

And the return result of 'json_extract(extra, $.query)' for this record is:
+------------------------------+
| json_extract(extra, $.query) |
+------------------------------+
| "show databases"             |
+------------------------------+
1 row in set (0.08 sec)

Note that the returned string value contains double quotes around it,
Therefore, the correct SQL spelling should be:
select * from system.log_info where json_extract(extra, '$.query') = '"show databases"'

**Comment by xzxiong** [comment]
> 


> After locating the problem, it is found that the SQL statement is misspelled. The reasons for the pronunciation are as follows The 'show databases' statement is stored in system.log_info after execution, the records in the table are: +----------+------------------+-----------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+ | trace_id | span_id | span_kind | node_uuid | node_type | timestamp | logger_name | level | caller | message | extra | stack | +----------+------------------+-----------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+ | 0 | 7c4dccb44d3c41f8 | internal | 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf | ALL | 2022-11-15 11:47:00.917233 | | info | frontend/util.go:495 | query trace | {"connection_id": 1003, "query": "show databases", "session_info": "connectionId 1003"} | | +----------+------------------+-----------+--------------------------------------+-----------+----------------------------+-------------+-------+----------------------+-------------+-----------------------------------------------------------------------------------------+-------+ 1 row in set (0.05 sec)
> 
> And the return result of 'json_extract(extra, $.query)' for this record is: +------------------------------+ | json_extract(extra, $.query) | +------------------------------+ | "show databases" | +------------------------------+ 1 row in set (0.08 sec)
> 
> Note that the returned string value contains double quotes around it, Therefore, the correct SQL spelling should be: select * from system.log_info where json_extract(extra, '$.query') = '"show databases"' 


has plan to support `JSON_UNQUOTE()` function ?

**Comment by qingxinhome** [comment]
> 

Currently, JSON is not supported_ UNQUOTE() function, but can put forward requirements to the product
