### ISSUE TITLE
[Enhancement]: Transitivity of equalities

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#6561]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

Given equality predicates `a = b` and `b = c`, we should be able to infer `a = c` if necessary.

For example, in tpch q5, there is `c_nationkey = s_nationkey and s_nationkey = n_nationkey`, then `c_nationkey = n_nationkey` should be automatically inferred.

### Why is this needed ?

Sometimes this rule can help join order.

**Comment by badboynt1** [comment]
finished
