### ISSUE TITLE
[Feature Request]: INSERT ... ON DUPLICATE KEY UPDATE Statement

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6567]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
From customer demand and certification test.
```

### Describe the feature you'd like

INSERT
    [INTO] tbl_name
    [PARTITION (partition_name [, partition_name] ...)]
    [(col_name [, col_name] ...)]
    { {VALUES | VALUE} (value_list) [, (value_list)] ... }
    [AS row_alias[(col_alias [, col_alias] ...)]]
    [ON DUPLICATE KEY UPDATE assignment_list]
    
assignment:
    col_name = 
          value
        | [row_alias.]col_name
        | [tbl_name.]col_name
        | [row_alias.]col_alias

Follow MySQL 8.0 behavior. https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

If you specify an ON DUPLICATE KEY UPDATE clause and a row to be inserted would cause a duplicate value in a UNIQUE index or PRIMARY KEY, an [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html) of the old row occurs. For example, if column a is declared as UNIQUE and contains the value 1, the following two statements have similar effect:

 
INSERT INTO t1 (a,b,c) VALUES (1,2,3)
  ON DUPLICATE KEY UPDATE c=c+1;

UPDATE t1 SET c=c+1 WHERE a=1;

**Comment by domingozhang** [comment]
need to be discussed with yuanning

**Comment by ouyuanning** [comment]
after discuss with @nnsgmsone @domingozhang .
we will use one pipeline to do 'insert xxx on duplicate key xx'. 
because we need to known the update result of pre rows, if split to many pipeline, we can not get this runtime status.

that means this action can not use multi cores and have slow execution.

**Comment by heni02** [comment]
1.1.0新支持ddl包含唯一索引测试完成无问题，test done

**Comment by dengn** [comment]
feature implemented.
