### ISSUE TITLE
[Bug]: duplicate information_schema entries

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6570]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run bvt and then execute sql:
SELECT * FROM `information_schema`.`schemata` where schema_name = 'information_schema';

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/39627130/201603221-742f5b84-9b27-443d-9c96-b53af0ed6eac.png">

**Comment by qingxinhome** [comment]
This problem has been fixed and pr has been submitted. Please know  @XuPeng-SH

**Comment by XuPeng-SH** [comment]
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/39627130/201923689-644a249d-5cfa-40d1-88c8-f13b29af8ce5.png">

**Comment by daviszhen** [comment]
It was fixed at. #6759 #6757
