### ISSUE TITLE
[Feature Request]: zerofill 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6571]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

When numeric types and decimal types are used in conjunction with the optional (nonstandard) ZEROFILL attribute, the default padding of spaces is replaced with zeros. For example, for a column declared as INT(4) ZEROFILL, a value of 5 is retrieved as 0005.

This should apply for int, float，double, decimal(M,N)

**Comment by fengttt** [comment]
Why isn't this a function?   zerofill(number, 5) returns string.

**Comment by florashi181** [comment]
this solution is ok

**Comment by domingozhang** [comment]
decimal and int will be implemented first
float and double depends on users' feedback

**Comment by aunjgr** [comment]
There's actually no need to implement a new `zerofill` function. `lpad` can cover all cases. `zerofill(some_numeric_val, 5)` is identical to `lpad(some_numeric_val, 5, '0')`.

And according to mysql's [documentation](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html), `zerofill` should only support unsigned numeric types. So don't bother handling negative values with `lpad`.

**Comment by aunjgr** [comment]
Assigning this back to the author. Please let me know if you don't agree with my last comment.

**Comment by dengn** [comment]
Starting with the idea of developing it as a function instead of DDL statement, this feature has already a compatibility problem with MySQL. We haven't really encountered any application problem related to this zerofill behavior yet, so I will accept it for now.
