### ISSUE TITLE
[Feature Request]: HINT 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6573]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

{DELETE|INSERT|SELECT|UPDATE} /*+ hint [text] [hint[text]]... */ 

Expected behavior:
1. Choose full table scan or indexed scan by hint content.
2. Choose multi-table join order by hint content.

**Comment by daviszhen** [comment]
0.8语法通过，不起作用

**Comment by taofengliu** [comment]
Optimizer hints is treated as comments. They can pass parser successfully.

**Comment by Ariznawlll** [comment]
Grammar test pass！

**Comment by aressu1985** [comment]
test done
