### ISSUE TITLE
[Enhancement]: LOAD DATA enhancement

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6576]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
For cloud support. 

1. Extend the usage of SET statement, to support setting certain columns to default value or function.

LOAD DATA INFILE 'file.txt'
  INTO TABLE t1
  (column1, column2)
  SET column3 = CURRENT_TIMESTAMP;

LOAD DATA INFILE 'file.txt'
  INTO TABLE t1
  (column1, column2)
  SET column3 = 10;

```

2. Support the `IGNORE` statement. 
Ignore the uncompatible records, including duplicate record with unique index or primary key, record column doesn't fit. 

3. Support Load data from multiple source: from local file system, from an url of a public cloud object storage, from a network file url.
```


### Why is this needed ?

_No response_

### Additional information

_No response_

**Comment by daviszhen** [comment]
The second one, drop the batch
The third one need the support of fileservice.

**Comment by sukki37** [comment]
tracked by #7887
