### ISSUE TITLE
[Feature Request]: Built in-Function RAND()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6585]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of showing the values of a database/table in the platform, we want to add the built-in function RAND().
```

### Describe the feature you'd like

Returns a random floating-point value v in the range 0 <= v < 1.0. 
1.  Follow the syntax and behavior of mysql 8.0. 
2. Function syntax:

mysql> SELECT i, RAND() FROM t;
+------+------------------+
| i    | RAND()           |
+------+------------------+
|    1 | 0.61914388706828 |
|    2 | 0.93845168309142 |
|    3 | 0.83482678498591 |
+------+------------------+
3 rows in set (0.00 sec)

mysql> SELECT i, RAND(3) FROM t;
+------+------------------+
| i    | RAND(3)          |
+------+------------------+
|    1 | 0.90576975597606 |
|    2 | 0.37307905813035 |
|    3 | 0.14808605345719 |
+------+------------------+
3 rows in set (0.00 sec)

mysql> SELECT i, RAND() FROM t;
+------+------------------+
| i    | RAND()           |
+------+------------------+
|    1 | 0.35877890638893 |
|    2 | 0.28941420772058 |
|    3 | 0.37073435016976 |
+------+------------------+
3 rows in set (0.00 sec)

mysql> SELECT i, RAND(3) FROM t;
+------+------------------+
| i    | RAND(3)          |
+------+------------------+
|    1 | 0.90576975597606 |
|    2 | 0.37307905813035 |
|    3 | 0.14808605345719 |
+------+------------------+
3 rows in set (0.01 sec)

**Comment by m-schen** [comment]
it will be a demo for function framework refactor ( the issue is #6827

**Comment by m-schen** [comment]
I have finished this one but can not make a pr now. because the framework factor has met some problem.

**Comment by m-schen** [comment]
无法和6827一起合并，当数据分为多个batch时存在语义上的错误，需要先为函数的执行引入private structure

**Comment by m-schen** [comment]
实现了表达式重构后，需要plan处也相应打一个标签。使用函数上下文的函数不走并行。

**Comment by m-schen** [comment]
与7502一起做，大约会比那个issue迟1到2天

**Comment by dengn** [comment]
why didn't we finish implementing this rand(N)? @m-schen 

https://github.com/matrixorigin/matrixorigin.io.cn/pull/389/files

**Comment by sukki37** [comment]
This issue can be closed for the implementation of rand() has been successfully completed. Another issue should be created for `rand(seed)` when needed.
