### ISSUE TITLE
[Feature Request]: Support EVENT

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6587]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CREATE
    EVENT
    [IF NOT EXISTS]
    event_name
    ON SCHEDULE schedule
    [ON COMPLETION [NOT] PRESERVE]
    [COMMENT 'string']
    DO event_body;

schedule: {
    AT timestamp [+ INTERVAL interval] ...
  | EVERY interval
    [STARTS timestamp [+ INTERVAL interval] ...]
    [ENDS timestamp [+ INTERVAL interval] ...]
}

interval:
    quantity {YEAR | QUARTER | MONTH | DAY | HOUR | MINUTE |
              WEEK | SECOND | YEAR_MONTH | DAY_HOUR | DAY_MINUTE |
              DAY_SECOND | HOUR_MINUTE | HOUR_SECOND | MINUTE_SECOND}

DROP EVENT [IF EXISTS] event_name

- Support MySQL Syntax with event creation and dropping.
- Support provided inverval and schedule types

**Comment by fengttt** [comment]
The difficult part is the event body.   It requires stored proc support.

**Comment by fengttt** [comment]
@gavinyue please put this in the context of streaming.    Do we have this functionality?   If we can do this in context of streaming the syntax is not really important.
