### ISSUE TITLE
[Feature Request]: Support more accurate notification in parser

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6589]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Currently, the error notification of parser still needs to be enhanced to notify more accurate information as following:

- get the line number of incorrect SQL
create table t1(
a int1
);
--> notified failed at line 2

- get the exact object name in DDL
create table t1(
a int1
);
--> notified the table name t1

**Comment by fengttt** [comment]
This is open ended and will last forever.   We will make some improvements on the most important/bad messages, but won't complete.

**Comment by daviszhen** [comment]
I think it is hard to implement it 0.7.

**Comment by daviszhen** [comment]
第二个实现难度大，0.8 不做。
