### ISSUE TITLE
[Feature Request]: Support sequence 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6590]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CREATE [ { TEMPORARY | TEMP }] SEQUENCE [ IF NOT EXISTS ] name
    [ INCREMENT [ BY ] increment ]
    [ MINVALUE minvalue | NO MINVALUE ] [ MAXVALUE maxvalue | NO MAXVALUE ]
    [ START [ WITH ] start ] [ CACHE cache ] [ [ NO ] CYCLE ]
    [ OWNED BY { table_name.column_name | NONE } ]
    
ALTER SEQUENCE [ IF EXISTS ] name
    [ INCREMENT [ BY ] increment ]
    [ MINVALUE minvalue | NO MINVALUE ] [ MAXVALUE maxvalue | NO MAXVALUE ]
    [ START [ WITH ] start ]
    [ RESTART [ [ WITH ] restart ] ]
    [ CACHE cache ] [ [ NO ] CYCLE ]
    [ OWNED BY { table_name.column_name | NONE } ]

ALTER SEQUENCE [ IF EXISTS ] name OWNER TO { new_owner | CURRENT_ROLE | CURRENT_USER | SESSION_USER }
ALTER SEQUENCE [ IF EXISTS ] name RENAME TO new_name
ALTER SEQUENCE [ IF EXISTS ] name SET SCHEMA new_schema

feature list:
- Support sequence syntax by following PG
- Support create, alter and drop DDL

**Comment by iceTTTT** [comment]
CREATE SEQUENCE [ IF NOT EXISTS ] SEQUENCE_NAME
    [ AS data_type ]
    [ INCREMENT [ BY ] increment ]
    [ MINVALUE minvalue | NO MINVALUE ] [ MAXVALUE maxvalue | NO MAXVALUE ]
    [ START [ WITH ] start ] [ [ NO ] CYCLE ]

This is the supported `create sequence` syntax.

**Comment by heni02** [comment]
@iceTTTT  is this all 0.8 support level ？

**Comment by iceTTTT** [comment]
Comment edited @heni02

**Comment by heni02** [comment]
doc：https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACU1sWXrQHUQC2MUuw15d?scode=AJsA6gc3AA86fm67eeAYYAgwazACs

**Comment by heni02** [comment]
confirm with @iceTTTT  not support NO MINVALUE  and MAXVALUE

**Comment by heni02** [comment]
test done

**Comment by domingozhang** [comment]
left items will be implemented in next Release
