### ISSUE TITLE
[Feature Request]: Support query plan with partition

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6591]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

While querying data with a partitioned table, the plan of it can tell partition data and feed back to user.
Such as a table partitioned by columns year, the query with year filter will use partitioned data and display it into plan.

**Comment by fengttt** [comment]
this request is to enhance explain output.   details to be designed.

**Comment by daviszhen** [comment]
Maybe related to the #7717

**Comment by daviszhen** [comment]
it also is the subtask of #7717

**Comment by florashi181** [comment]
will track with https://github.com/matrixorigin/matrixone/issues/12927 in V1.2
