### ISSUE TITLE
[Feature Request]: Support windows function ability

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6595]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

by following the description of mysql's, make MO support window functions ability

https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html

**Comment by fengttt** [comment]
SQL feature,

**Comment by daviszhen** [comment]
Over window 做完。差测试和文档。

**Comment by iamlinjunhong** [comment]
same as https://github.com/matrixorigin/matrixone/issues/8805

**Comment by Ariznawlll** [comment]
test done!
