### ISSUE TITLE
[Feature Request]: Statistics on CPU, Memory and I/O consumption of SQL

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6596]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- When a query execution is completed, record the CPU, MEMORY and I/O, computing resource consumption for computing query.
CPU: core*time
Memory: Size*time
I/O: count

**Comment by qingxinhome** [comment]
Explain Fill in the statistical data of the total system resources used for SQL query execution, including time, memory, IO, network, data, etc

**Comment by dongdongyang33** [comment]
current status:
- [x] CPU time
- [x] memory 
- [ ] disk
- [x] s3 byte 
- [ ] s3 count
- [x] network

TODO:
1. s3 byte is not an accuracy statistic now. it will be separated into disk/s3 later.
2. add s3 query count info
3. refine the memory/network/CPU statistics

**Comment by LiSong0214** [comment]
Acceptance passed, unfinished part will be traced by https://github.com/matrixorigin/matrixone/issues/7900
