### ISSUE TITLE
[Feature Request]: Support foreign key

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6597]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

[CONSTRAINT [symbol]] FOREIGN KEY
    [index_name] (col_name, ...)
    REFERENCES tbl_name (col_name,...)
    [ON DELETE reference_option]
    [ON UPDATE reference_option]

reference_option:
    RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT

- Support the syntax of mysql in foreign key
- Support ON DELETE and ON UPDATE clause

**Comment by fengttt** [comment]
plan tricks.

**Comment by domingozhang** [comment]
needs a minimum limit

**Comment by domingozhang** [comment]
error code

**Comment by ouyuanning** [comment]
need wait tableDef refactor and need @nnsgmsone team's help.
so i change the finish time

**Comment by ouyuanning** [comment]
i will start 3 issues at the same time. i will guide new guy to finish 2 of them. 
so that will make this issue more delay.

**Comment by domingozhang** [comment]
multi columns foreign key will support in 0.8

**Comment by domingozhang** [comment]
multi columns foreign key will support in 0.8.0

**Comment by heni02** [comment]
test done，pr https://github.com/matrixorigin/matrixone/pull/7936

**Comment by heni02** [comment]
多层外键测试完毕

**Comment by domingozhang** [comment]
support on cascade in 1.0

**Comment by lacrimosaprinz** [comment]
doc edited:https://github.com/matrixorigin/matrixorigin.io.cn/pull/648
https://github.com/matrixorigin/matrixorigin.io/pull/492

**Comment by heni02** [comment]
和远宁沟通，1.0解决了0.8外键为主键之一，主键和索引交叉重复值检查情况

**Comment by heni02** [comment]
和远宁沟通，1.0解决了0.8外键为主键之一，主键和索引交叉重复值检查情况

**Comment by heni02** [comment]
补充的case test done 
目前有一个问题：外键为主键之一时delete空数据查询从表结果不一致，issue #11425

**Comment by heni02** [comment]
#11425 issue closed
