### ISSUE TITLE
[Feature Request]: Support more in auto_increment

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6598]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

CREATE [TEMPORARY] TABLE [IF NOT EXISTS] tbl_name
    (create_definition,...)
    [table_options]
    
table_option: {
   AUTO_INCREMENT [=] value
   }

Feature list:
- Support customized initial value by using AUTO_INCREMENT=n
- Support customized increated value by using parameters auto_increment_increment and auto_increment_offset

**Comment by domingozhang** [comment]
last_insert_id() —— return the last inserted value of auto_increment column in current session

**Comment by w-zr** [comment]
implemented in #10636

**Comment by w-zr** [comment]
Implemented `create table t1(a int) auto_increment=10;` to create a table with initial auto_increment value set to 10.
`alter table t1 auto_increment=10;` is not implemented.
To implement `alter table` way, `mo_tables` schema has to be modified to store the initial value.

**Comment by Ariznawlll** [comment]
test done!
