### ISSUE TITLE
[Feature Request]: Support alter table

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6599]
### Is there an existing issue for the same feature request?

- [x] I have checked the existing issues.

### Describe the feature you'd like

ALTER TABLE tbl_name
    [alter_option [, alter_option] ...]
    [partition_options]
    
    
partition_options:
    partition_option [partition_option] ...

partition_option: {
    ADD PARTITION (partition_definition)
  | DROP PARTITION partition_names
  | TRUNCATE PARTITION {partition_names | ALL}
  | COALESCE PARTITION number
  | REMOVE PARTITIONING
}

alter_option: {
    ADD [COLUMN] col_name column_definition
        [FIRST | AFTER col_name]
  | ADD [COLUMN] (col_name column_definition,...)
  | ADD {INDEX | KEY} [index_name]
        [index_type] (key_part,...) [index_option] ...
  | ADD [CONSTRAINT [symbol]] PRIMARY KEY
        [index_type] (key_part,...)
        [index_option] ...
  | ADD [CONSTRAINT [symbol]] UNIQUE [INDEX | KEY]
        [index_name] [index_type] (key_part,...)
        [index_option] ...
  | ADD [CONSTRAINT [symbol]] FOREIGN KEY
        [index_name] (col_name,...)
        reference_definition
  | ALTER [COLUMN] col_name {
        SET DEFAULT {expr}
      | DROP DEFAULT
      |  AUTO_INCREMENT [=] value
    }
  | CHANGE [COLUMN] old_col_name new_col_name column_definition
        [FIRST | AFTER col_name]
  | DROP [COLUMN] col_name
  | DROP {INDEX | KEY} index_name
  | DROP PRIMARY KEY
  | DROP FOREIGN KEY fk_symbol
  | MODIFY [COLUMN] col_name column_definition
        [FIRST | AFTER col_name]
  | RENAME COLUMN old_col_name TO new_col_name
  | RENAME {INDEX | KEY} old_index_name TO new_index_name
  | RENAME [TO | AS] new_tbl_name
}

index_option: {
   index_type
  | COMMENT 'string'
}

feature list:
- Support the modification of column data type and rename
- Support the modification of partitions as add and drop
- Support the modification of index/key/constraint
- Support the modification of auto_increment

**Comment by domingozhang** [comment]
close  https://github.com/matrixorigin/matrixone/issues/4020

**Comment by daviszhen** [comment]
After discussing with @XuPeng-SH, he may put the feature in the plan with low priority.

**Comment by fengttt** [comment]
Some are easy to do, like rename.    We should support.
We want to find out if we can efficiently do add column and remove column.

For the difficult ones, there is the option of simply recreate/rewrite the whole table.

**Comment by aressu1985** [comment]
the content of this issue in 0.8 has been tested. and the remain is tracked by this featuere in 1.0.
https://github.com/matrixorigin/matrixone/issues/10380

this issue can be done
