### ISSUE TITLE
[Feature Request]: Support alter view

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6600]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

ALTER
    VIEW view_name [(column_list)]
    AS select_statement
    [WITH [CASCADED | LOCAL] CHECK OPTION]

feature list:
- Support alter the query of a view
- Support WITH clause syntax

**Comment by domingozhang** [comment]
rename view first

**Comment by daviszhen** [comment]
just syntax support.

**Comment by ouyuanning** [comment]
I will be responsible for this issue.
and i will guide @iceTTTT  to complete it.

**Comment by domingozhang** [comment]
Support WITH clause syntax 
will support in future

**Comment by aressu1985** [comment]
test done
