### ISSUE TITLE
[Feature Request]: support nonaggregated name column in the select list which does not appear in the GROUP BY

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#6604]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Some client queries require to be compatible with MySQL 5.7 behavior with nonaggregated name column in the select list which does not appear in the GROUP BY.
```

### Describe the feature you'd like

Switch the behavior by setting SQL_MODE:

SET sql_mode = '';

drop table if exists t;
create table t(a bigint, b bigint, c bigint);
insert into t values(1, 2, 3), (2, 2, 3), (3, 2, 3);
select a, b, sum(c) from t group by a;
+------+------+--------+
| a    | b    | sum(c) |
+------+------+--------+
|    1 |    2 |      3 |
|    2 |    2 |      3 |
|    3 |    2 |      3 |
+------+------+--------+
3 rows in set (0.01 sec)

SET sql_mode = 'ONLY_FULL_GROUP_BY';
select a, b, sum(c) from t group by a;
ERROR 1055 (42000): Expression 2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'b' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by aunjgr** [comment]
Implemented in #6698

**Comment by domingozhang** [comment]
need to be verified

**Comment by dengn** [comment]
finished
