### ISSUE TITLE
[Feature Request]: Per Account and Per DB Configurations

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6606]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Some mysql behaviors are simply bugs.   An example is https://github.com/matrixorigin/matrixone/issues/6604

We want to have a unified framework to handle all these weird behaviors.
```

### Describe the feature you'd like

Propose the following solution.

1. Create a config variable, MYSQL_COMPATBILITY_MODE.  
2. This a new class of configs that should be per account, per db.  We can attach these configs 
   to cluster, and to each account and each db.   When client connect to a database, we read 
   this config value and apply to the session.   account value overwrites cluster value and 
   db value overwrites account value.
3. By default, this value is not set.   User can set this using a DDL,
       ` alter account/db xxx set MYSQL_COMPATBLITY_MODE ='buggy_this,totally_wrong_that,issue_6604';`
4. User can further get/set this as session variable.
       ` set @mysql_compatbility_mode = 'foo,bar,zoo' `
5. We do not promise that we will implement any of these MYSQL bugs.  It will be case by case 
   decision.
 

### Describe implementation you've considered

Cluster level this config should be empty.   For sanity.

This config must be per db because accounts may share cluster.   Cluster level config will contaminate other accounts.   
Account level will be default for all dbs within account.   We expect people want to fine tune at DB level, hopefully all
new db will be sane, and this config is a tool for legacy apps.

Session variable overwrite is desirable for test/debug and customer's own hot patch/fix.

**Comment by aressu1985** [comment]
so which modes will be supported in 0.7.0? only ONLY_FULL_GROUP_BY or more?

**Comment by fengttt** [comment]
Note that there is a type.   COMPATIBILITY, original issue missing an I.

As a test case, we should implement mysql_server_version, so that we can test it.

**Comment by YANGGMM** [comment]
兼容性模式名称：version_compatibility
影响参数：select version()结果
作用范围：account或database
启动默认值：0.7
开启该模式后：8.0.30-MatrixOne-v0.7.0
ALTER ACCOUNT CONFIG account_name MYSQL_COMPATBLITY_MODE='version_compatibility, mode2,...'
ALTER DATABASE database_name MYSQL_COMPATBLITY_MODE='version_compatibility, mode2,...'

**Comment by heni02** [comment]
version_compatibility test done
