### ISSUE TITLE
[Feature Request]: Support ENUM data type

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6613]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

An ENUM is a string object with a value chosen from a list of permitted values that are enumerated explicitly in the column specification at table creation time.

- Support MySQL syntax for enum
- the max size of enum number is 65535
- Support enum data used in aggregation function, order by, subquery, where clause and so on
- Support conversation of enum to string, int, time types

**Comment by lacrimosaprinz** [comment]
doc edited:
https://github.com/matrixorigin/matrixorigin.io/pull/490
https://github.com/matrixorigin/matrixorigin.io.cn/pull/646

**Comment by aronchanisme** [comment]
Wait for https://github.com/matrixorigin/MO-Cloud/issues/1181 to be resolved.

**Comment by domingozhang** [comment]
1.0 scope：
DDL: Only create table is available
DML: Insert, Update and Delete. No type conversation
Query: Join is not supported
other: prepare is not supported

**Comment by aronchanisme** [comment]
Test done and test cases merged into bvt cases, back to @domingozhang
