### ISSUE TITLE
[Feature Request]: Support binary and varbinary types

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6615]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

The BINARY and VARBINARY types are similar to CHAR and VARCHAR, except that they store binary strings rather than nonbinary strings. That is, they store byte strings rather than character strings. This means they have the binary character set and collation, and comparison and sorting are based on the numeric values of the bytes in the values.
The permissible maximum length is the same for BINARY and VARBINARY as it is for CHAR and VARCHAR, except that the length for BINARY and VARBINARY is measured in bytes rather than characters.

feature list:
- Compatible syntax with MySQL
- Support agg function, order by, where clause, subquery, joint query and so on
- Support type conversation with other types
- Support related builtin function with binary types

**Comment by daviszhen** [comment]
It is delayed to the future version.

**Comment by iceTTTT** [comment]
and/or/xor are not supported for binary type

**Comment by Ariznawlll** [comment]
test done!
