### ISSUE TITLE
[Feature Request]: Type conversion from time types to int

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6616]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support the type conversation from time types to int, including date, datetime, timestamp and time
such as 
create table t1(a datetime, b int);
create table t2(a date, b int);
select cast(a as int) from t1;
select a % 10 from t1;
select a / 1 from t2;

**Comment by aunjgr** [comment]
Typecast and mod has been finished. div depends on decimal rework.

**Comment by aunjgr** [comment]
The type coercion rules DATETIME/TIMESTAMP -> INT64 was temporary. Since our own DECIMAL is ready, we should change the target type to DECIMAL.

@zengyan1 Please work on this after you finish #8465

**Comment by zengyan1** [comment]
Done

**Comment by zengyan1** [comment]
date类型没有毫秒/微秒，保持date与int的互转，该issue不对date类型及相关行为做出改动
对time/datetime/timestamp三种类型新增显式cast成decimal，如: select cast( datatime(3) as decimal(10,3)) ... ;
新增在表达式中隐式转换成decimal64

现支持直接对time/datetime/timestamp类型与int/decimal进行运算，包括：
time/datetime/timestamp + int/decimal
time/datetime/timestamp - int/decimal
time/datetime/timestamp * int/decimal
time/datetime/timestamp / int/decimal
time/datetime/timestamp % int/decimal
运算前会先将两个参数都先转换成decimal然后再做decimal的对应计算
/ 是普通的除法，div是整数除法，暂不支持 time div int

time + time 由time类型内部定义并完成
time * time 无意义，暂不支持
其它类型同理

**Comment by Ariznawlll** [comment]
test done!
