### ISSUE TITLE
[Feature Request]: Built-in Function GROUP_CONCAT()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6624]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support the function GROUP_CONCAT().
```

### Describe the feature you'd like

This function returns a string result with the concatenated non-NULL values from a group. It returns NULL if there are no non-NULL values. 
Just Follow the syntax and behavior of mysql 8.0. The full syntax is as follows:

GROUP_CONCAT([DISTINCT] expr [,expr ...]
             [ORDER BY {unsigned_integer | col_name | expr}
                 [ASC | DESC] [,col_name ...]]
             [SEPARATOR str_val])

mysql> SELECT student_name,
         GROUP_CONCAT(test_score)
       FROM student
       GROUP BY student_name;

or:
mysql> SELECT student_name,
         GROUP_CONCAT(DISTINCT test_score
                      ORDER BY test_score DESC SEPARATOR ' ')
       FROM student
       GROUP BY student_name;

**Comment by JackTan25** [comment]
working on it now

**Comment by JackTan25** [comment]
order by will be supported later, I need to process the cn write s3 and distributed and persisted temp table  first

**Comment by JackTan25** [comment]
wait review, have implemented without order by

**Comment by JackTan25** [comment]
finish order by after cn-write-s3

**Comment by JackTan25** [comment]
order by will be implelented by @YANGGMM , I need to finish cn write s3 first

**Comment by domingozhang** [comment]
only support order by syntax
feature will be implemented in future

**Comment by Ariznawlll** [comment]
Verified!
