### ISSUE TITLE
[Feature Request]: Cluster management command

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6625]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

mo_ctl init[db] [-D datadir]
mo_ctl start [-D datadir][-o options]
mo_ctl stop [-D datadir] 
mo_ctl restart [-D datadir]
mo_ctl status [-D datadir]

Feature list:
- use mo_ctl to init cluster , including initial password, ip config, data directory
- use mo_ctl to start/stop/restart all nodes in cluster
- use mo_ctl to get status of cluster and nodes
- can be used in both distributed and standalone
- In operator environment, can provide similar function

**Comment by fengttt** [comment]
Don't we have these already?

**Comment by domingozhang** [comment]
no moup version but in k8s command related in 0.7

**Comment by domingozhang** [comment]
seperate another for password

**Comment by DanielZhangQD** [comment]
We also need to reset the account admin password.
