### ISSUE TITLE
[Feature Request]: Node management features online

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6626]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

feature list:
- Scale out cn, dn and ls online
- Scale in cn online
- Support multi cn, dn

**Comment by domingozhang** [comment]
Scale out cn online

**Comment by aylei** [comment]
Both scale in/out and scale up/down have been supported in mo-operator

document: https://github.com/matrixorigin/docs/blob/main/tech-notes/cloud/intro/mo-operator/scale-mo.md

**Comment by aylei** [comment]
As the feature has been shipped, shall we close this issue? @domingozhang

**Comment by aressu1985** [comment]
The test team need to test this again in 0.8
