### ISSUE TITLE
[Feature Request]: Upgrade management

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6627]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

feature list:
- Pre-check the compatibility of update for metadata and data
- Upgrade data with a certain command, either in linux cli or in mysql cli
- rolling upgrade without downtime (p1)

**Comment by fengttt** [comment]
Not 0.7.    This is a 1.1 problem, however, need to be designed out in 1.0

Assigned to @daviszhen , even though it is most likely a cloud and and DN problem, probably CN will be the driver.

**Comment by daviszhen** [comment]
> Not 0.7. This is a 1.1 problem, however, need to be designed out in 1.0
> 
> Assigned to @daviszhen , even though it is most likely a cloud and and DN problem, probably CN will be the driver.

Ok
