### ISSUE TITLE
[Feature Request]: Support backup and restore

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6629]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Feature list:
- Make physical backup in either linux cli or MO cli
- Restore from backed up files
- The backup feature can be backward compatible
- Incremental backup and restore to current time(P1)

**Comment by fengttt** [comment]
probably not applicable to us.

**Comment by fengttt** [comment]
@daviszhen please think about this -- what this need to be done other than dump database and load from dump?

**Comment by dengn** [comment]
doc side question:
1. what's the syntax for doing this?
2. does it support hot backup? 
3. does it support incremental backup?
4. what should be the best practice of using it?

**Comment by domingozhang** [comment]
mo_br is a standalone tool. It has its own tyntax:
$ mo_br -{backup|restore} {configfile}

parameters | comments
-- | --
host | target IP of MO
port | port number
user | username
password | password
backup_directory | backup path, a file path or a s3 option
restore_directory | backup path, a file path or a s3 option


s3option
Parameter | Description
-- | --
endpoint | A endpoint is a URL that can conncect to object storage service. For example: s3.us-west-2.amazonaws.com
access_key_id | Access key ID
secret_access_key | Secret access key
bucket | S3 Bucket to access
filepath | relative file path. regex expression is supported as /files/*.csv.
region | object storage service region
compression | Compressed format of S3 files. If empty or "none", it indicates uncompressed files. Supported fields or Compressed format are "auto", "none", "gzip", "bz2", and "lz4".

**Comment by domingozhang** [comment]
In 1.0 milestone, only hot backup with full cluster data is accepted.

**Comment by domingozhang** [comment]
Backup and restore methods supporting 
<img width="471" alt="1690533023444" src="https://github.com/matrixorigin/matrixone/assets/88298673/fab30d86-6ce8-4aa7-bd60-c62ce8509a9e">

**Comment by daviszhen** [comment]
转测试：
1, https://github.com/matrixorigin/mo-backup  
2, doc: https://github.com/matrixorigin/docs/blob/main/design/backup_restore.md

**Comment by aronchanisme** [comment]
testing in progress

**Comment by aronchanisme** [comment]
Currently 8 cases are tested, where only one case passed while the rest failed. Please refer to below docs for more info. @daviszhen  Please kindly help take a look at the errors
<img width="1694" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/104a3605-a92c-4397-a8b5-bce7fd84ce48">

1、测试过程记录：
https://doc.weixin.qq.com/doc/w3_AfsAgAbcAMItX9eKVMJRnuYIfOPg8?scode=AJsA6gc3AA8YzDW1dxAfsAgAbcAMI&is_precreate=1&isEnterEdit=1&dver=3.0.0
2、测试结果汇总：
https://doc.weixin.qq.com/sheet/e3_AfsAgAbcAMIRulJ0bChQ52mpiTQg1?scode=AJsA6gc3AA8whvL7IFAfsAgAbcAMI&is_precreate=1&dver=2.9.0&tab=BB08J2

**Comment by YANGGMM** [comment]
<img width="1006" alt="企业微信截图_d7bc839f-23fd-4d86-b5c5-803359d4f302" src="https://github.com/matrixorigin/matrixone/assets/26563383/b3dd6ac5-f14c-454e-be92-f1a3a60de773">
这两个可能是文件路径的原因，麻烦更改一下文件路径然后重新测试 @aronchanisme

**Comment by aronchanisme** [comment]
Currently there are still 3 issues needed to be resolved. As discussed,
1. Conf setting in MO standalone:  `hk_data` conf needs to be set as default value. Please sse https://github.com/matrixorigin/matrixone/issues/12437. Otherwise, a misconfiguration will lead to error like this:
```bash
2023/09/28 15:56:14.980421 +0800 ERROR backup/backup.go:94 post backup failed: file tae/tae_sum is not found
Error: file tae/tae_sum is not found

```
2. Conf setting in MO cluster: Will use mo operator api instead of mo_br directly to backup and restore mo data. Docs to be followed up. 
3. After restoring data in mo, mo_br backup is not working due to error:
````bash
Error: Error 20405 (HY000): file ba2f972a-7708-11ee-ac02-0800278dc04d_00000 is not found
```
This seems to be a bug which needs to be fixed.

**Comment by aronchanisme** [comment]
Please see: https://github.com/matrixorigin/matrixone/issues/12437#issuecomment-1822333754

Test is done.

**Comment by aronchanisme** [comment]
> For this issue, please see: [#12437 (comment)](https://github.com/matrixorigin/matrixone/issues/12437#issuecomment-1822333754)
> 
> There are 2 issues remained.
> 
> 1. [[Bug]: tenant sys is missing after mo is restored by mo_br #12894](https://github.com/matrixorigin/matrixone/issues/12894)
> 2. [[Bug]: mo table `mo_catalog.mo_indexes` is missing after restored by `mo_br` #12891](https://github.com/matrixorigin/matrixone/issues/12891)

Both issues are fixed now. Moving this feature to product team. @dengn

**Comment by florashi181** [comment]
this can be closed and with new issue  https://github.com/matrixorigin/matrixone/issues/11492 tracking
