### ISSUE TITLE
[Feature Request]: Support more system parameters for SHOW

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6632]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

SHOW FUNCTION STATUS [like_or_where]    
SHOW GRANTS FOR role    
SHOW INDEX FROM tbl_name [FROM db_name] 
SHOW TRIGGERS [FROM db_name] [like_or_where]    
SHOW NODE LIST  
SHOW LOCKS

**Comment by domingozhang** [comment]
SHOW GRANTS FOR role
SHOW INDEX FROM tbl_name [FROM db_name] in 0.7

**Comment by ouyuanning** [comment]
I will be responsible for this issue.
and i will guide @YANGGMM to complete it.

**Comment by aressu1985** [comment]
test done

**Comment by Ariznawlll** [comment]
SHOW FUNCTION STATUS [where]
SHOW TRIGGERS [FROM db_name] [like_or_where]
SHOW NODE LIST
SHOW LOCKS
未实现

**Comment by domingozhang** [comment]
part of items will be moved to 0.9

**Comment by YANGGMM** [comment]
have finished doc @domingozhang
