### ISSUE TITLE
[Feature Request]: More features about external table

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6633]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

feature list:
- Support data insert, update and delete 
- Support transfer external tables to internal tables

**Comment by fengttt** [comment]
We may never be able to support insert/upd/del to external table.

Why can't we do create table XXX as select * from external_table?

**Comment by gavinyue** [comment]
Still pending.  Need more research on the external table design.
