### ISSUE TITLE
[Feature Request]: Built-in Function SPLIT_PART()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6634]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support the function SPLIT_PART().
```

### Describe the feature you'd like

splits a [string] on a specified delimiter and returns the nth substring. We can follow the syntax and behavior of Postgresql. 

split_part ( expr, delimiter , unsigned_integer )

**Comment by aressu1985** [comment]
test done
