### ISSUE TITLE
[Feature Request]: Transaction enhancement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6635]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

feature list:
- All DDL can be used in transactions with start
- In non-autocommit mode, ddl can be used in a transaction
- select statement without table data  is not calculated into transaction (P1)

**Comment by fengttt** [comment]
not sure if these can be mapped to our transaction model.

**Comment by daviszhen** [comment]
pr #9224 已经合并。遗留set expr的特殊情况。

**Comment by heni02** [comment]
test done
