### ISSUE TITLE
[Feature Request]: Built-in Function FORMAT()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6637]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support the function FORMAT().
```

### Describe the feature you'd like

This function formats the number X to a format like '#,###,###.##', rounded to D decimal places, and returns the result as a string. If D is 0, the result has no decimal point or fractional part. If X or D is NULL, the function returns NULL.

Just Follow the syntax and behavior of mysql 8.0. The full syntax is as follows:

[FORMAT(X,D[,locale])]

mysql> SELECT FORMAT(12332.123456, 4);
        -> '12,332.1235'
mysql> SELECT FORMAT(12332.1,4);
        -> '12,332.1000'
mysql> SELECT FORMAT(12332.2,0);
        -> '12,332'
mysql> SELECT FORMAT(12332.2,2,'de_DE');
        -> '12.332,20'

**Comment by Ariznawlll** [comment]
test done, bvt case pr merged
