### ISSUE TITLE
[Feature Request]: FLUSH statement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6638]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

FLUSH  {
    flush_option [, flush_option] ...
  | tables_option
}

flush_option: {
    PRIVILEGES
  | STATUS
}

tables_option: {
    TABLES
  | TABLES tbl_name [, tbl_name] ...
}

- Use this statement to reload the metadata of table list or privileges list

**Comment by fengttt** [comment]
Probably not applicable.

**Comment by fengttt** [comment]
wont fix
