### ISSUE TITLE
[Feature Request]: Abort SQL in a short time

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6639]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

When user want to cancel a running SQL, MO can abort it in a short time, such as less than 3-5 seconds.

**Comment by fengttt** [comment]
We should be able to do this -- if we cannot, it is a bug.     We may simply close this one, and whenever we see a non-cancellable query, file a S0 bug.

**Comment by domingozhang** [comment]
more than 30s is bug

**Comment by domingozhang** [comment]
Make sure the start time and end time .

**Comment by nnsgmsone** [comment]
i think ctrl +c can be abort .
