### ISSUE TITLE
[Feature Request]: Memory management

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6640]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

feature list:
- Customerize total size of memory in every node of MO, including CN, DN, LS
- When the utilization of memory is nearly the max size of limitation, user's request will be cancelled and notified.

**Comment by fengttt** [comment]
We should do this.    Not necessarily anything we need to do though.

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by domingozhang** [comment]
1.cn,dn,ls can customerized cache
2.when out of memory, user will be notified oom but instance not crashed

**Comment by aressu1985** [comment]
tracked by another issue https://github.com/matrixorigin/MO-Cloud/issues/387
