### ISSUE TITLE
[Enhancement]: 1000w line data, select count(*) from statement_info; execute time 18s.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6641]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 Reproducible Steps:
mysql -h127.0.0.1 -udump -p111 -P6001
create account testaccount ADMIN_NAME 'test_1' IDENTIFIED BY '111';
exit

clone code: url https://github.com/aressu1985/mo-load.git
modfiy run.yml: 
vuer:100
- sql: "select 1;"
duration: 20
mo-load import data 1000w.

mysql -h127.0.0.1 -utestaccount:test_1 -p111 -P6001
```
Select count(*) from statement_info; (16.47 sec)
select request_at,statement from statement_info where request_at>'2022-11-13 16:00:53' and request_at<'2022-11-14 17:00:53' order by request_at desc limit 1000;  (17.45 sec)
select request_at,statement from statement_info where statement='select 1' and request_at>'2022-11-13 16:00:53' and request_at<'2022-11-14 17:00:53' order by request_at desc limit 1000; (17.87 sec)
select request_at,statement from statement_info where statement like '%el%' and request_at>'2022-11-13 16:00:53' and request_at<'2022-11-14 17:00:53' order by request_at desc limit 1000; (18.13 sec)
```

**Comment by xzxiong** [comment]
related work https://github.com/matrixorigin/matrixone/issues/6612, https://github.com/matrixorigin/matrixone/issues/6678

**Comment by xzxiong** [comment]
working on #6948

**Comment by xzxiong** [comment]
working on

**Comment by xzxiong** [comment]
almost done, now working on last read issue https://github.com/matrixorigin/matrixone/issues/7709

**Comment by xzxiong** [comment]
still working on

**Comment by xzxiong** [comment]
wait  https://github.com/matrixorigin/matrixone/pull/7604 be merged

**Comment by xzxiong** [comment]
could test it again.

**Comment by xzxiong** [comment]
after 0.7, those 4 statement will have improve

1. `Select count(*) from statement_info; (16.47 sec)`
    - still cost many time.

2. `select request_at,statement from statement_info where request_at>'2022-11-13 16:00:53' and request_at<'2022-11-14 17:00:53' order by request_at desc limit 1000;  (17.45 sec)`
    - use `mo_log_date(__mo_filepath)` will have better cost.

3. `select request_at,statement from statement_info where statement='select 1' and request_at>'2022-11-13 16:00:53' and request_at<'2022-11-14 17:00:53' order by request_at desc limit 1000; (17.87 sec)`
4. `select request_at,statement from statement_info where statement like '%el%' and request_at>'2022-11-13 16:00:53' and request_at<'2022-11-14 17:00:53' order by request_at desc limit 1000; (18.13 sec)`
    - will have some performance as above statement
