### ISSUE TITLE
[Feature Request]: Built-in Function CURDATE()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6643]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support the function CURDATE().
```

### Describe the feature you'd like

Returns the current date as a value in 'YYYY-MM-DD' or YYYYMMDD format, depending on whether the function is used in string or numeric context.

Just Follow the syntax and behavior of mysql 8.0. The full syntax is as follows:

mysql> SELECT CURDATE();
        -> '2008-06-13'
mysql> SELECT CURDATE() + 0;
        -> 20080613

**Comment by domingozhang** [comment]
SELECT CURDATE() + 0;

From 1970-01-01 days

**Comment by mooleetzi** [comment]
Now, date is in [0001-01-01,9999-12-31]. 
Add `+` operator for date and int to return `days from 1970-01-01` `+` `intNumber` ?
Or just hack function `curdate` with `+`.

**Comment by mooleetzi** [comment]
wait #7064 merged to continue

**Comment by aunjgr** [comment]
MO's current typecast rule is:

date -> int returns the number of days from 1970-01-01.

datetime -> int returns the number of seconds from 1970-01-01T00:00:00.

**Comment by heni02** [comment]
@Ariznawlll test done
