### ISSUE TITLE
[Feature Request]: Standardize configuration files

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6645]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Provide two types of config files, including standalone and distributed cluster
- Make sure every parameters meaning and range of it
- Provide certain steps to use them to start MO service

**Comment by sukki37** [comment]
Standalone：https://github.com/matrixorigin/matrixone/tree/main/etc/quickstart
Distributed：https://github.com/matrixorigin/matrixone-operator/blob/main/examples/mo-cluster.yaml
