### ISSUE TITLE
[Feature Request]: Built-in Function FIELD()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6646]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support the function GROUP_CONCAT().
```

### Describe the feature you'd like

[FIELD(str,str1,str2,str3,...)]

This function returns the index (position) of str in the str1, str2, str3, ... list. Returns 0 if str is not found.

If all arguments to [FIELD()] are strings, all arguments are compared as strings. If all arguments are numbers, they are compared as numbers. Otherwise, the arguments are compared as double.

If str is NULL, the return value is 0 because NULL fails equality comparison with any value. [FIELD()] is the complement of [ELT()].

Just Follow the syntax and behavior of mysql 8.0. The full syntax is as follows:

mysql> SELECT FIELD('Bb', 'Aa', 'Bb', 'Cc', 'Dd', 'Ff');
        -> 2
mysql> SELECT FIELD('Gg', 'Aa', 'Bb', 'Cc', 'Dd', 'Ff');
        -> 0

**Comment by Ariznawlll** [comment]
test done

**Comment by dengn** [comment]
implemented
