### ISSUE TITLE
[Feature Request]: Built-in Function SUBSTRING_INDEX()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6649]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support this function.
```

### Describe the feature you'd like

[SUBSTRING_INDEX(str,delim,count)]

Returns the substring from string str before count occurrences of the delimiter delim.
If count is positive, everything to the left of the final delimiter (counting from the left) is returned.
If count is negative, everything to the right of the final delimiter (counting from the right) is returned. 
[SUBSTRING_INDEX()] performs a case-sensitive match when searching for delim.

Just Follow the syntax and behavior of mysql 8.0. The full syntax is as follows:

mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);
        -> 'www.mysql'
mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', -2);
        -> 'mysql.com'

**Comment by aressu1985** [comment]
test done
