### ISSUE TITLE
[Feature Request]: CBO desgin

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6651]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Design MO's own CBO
- Based on cpu and memory as cost, collect the statistics
- Support all rows / first rows

**Comment by fengttt** [comment]
Too vague to act.    We will continue to enhance our optimizer and we will collect the stats.   However, not sure what can we do with this issue.

Long Ran and Ni Tao will own optimizer related work.

**Comment by fengttt** [comment]
Maybe close due to no action.
