### ISSUE TITLE
[Feature Request]: Built-in Function INSTR()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6652]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

[INSTR(str,substr)]

Returns the position of the first occurrence of substring substr in string str. This is the same as the two-argument form of [LOCATE()], w], except that the order of the arguments is reversed.

Just Follow the syntax and behavior of mysql 8.0. 

mysql> SELECT INSTR('foobarbar', 'bar');
        -> 4
mysql> SELECT INSTR('xbar', 'foobar');
        -> 0

**Comment by aressu1985** [comment]
test done
