### ISSUE TITLE
[Feature Request]: Built-in Function CONVERT()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6653]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support this function.
```

### Describe the feature you'd like

[CONVERT(expr,type)]
[CONVERT(expr USING transcoding_name) . It converts data between different character sets.

Follow the syntax and behavior of mysql 8.0.  In MySQL, transcoding names are the same as the corresponding character set names. For example, this statement converts the string 'abc' in the default character set to the corresponding string in the utf8mb4 character set:
SELECT CONVERT('abc' USING utf8mb4);

**Comment by fengttt** [comment]
This issue itself is not difficult but it depends on our charset/encoding support.
