### ISSUE TITLE
[Feature Request]: Built-in Function MID()

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/matrixone#6654]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
As the demand of many customers and users, we want to support this function.
```

### Describe the feature you'd like

[MID(str,pos,len)]

[MID(str,pos,len)] is a synonym for [SUBSTRING(str,pos,len)]. Follow the syntax and behavior of mysql 8.0.

**Comment by aressu1985** [comment]
test done
