### ISSUE TITLE
[Feature Request]: DELETE with parition

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6657]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

DELETE [LOW_PRIORITY] [QUICK] [IGNORE] FROM tbl_name [[AS] tbl_alias]
    [PARTITION (partition_name [, partition_name] ...)]
    [WHERE where_condition]
    [ORDER BY ...]
    [LIMIT row_count]

- Support partition clause and displayed in plan

**Comment by fengttt** [comment]
Probably not applicable to us.

**Comment by fengttt** [comment]
Not applicable/Invalid feature.   Wont fix
