### ISSUE TITLE
[Feature Request]: Support Invisible Index

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6658]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Support create invisible index with DDL directly
- Support alter index invisible

create index idx_1 on t1(emp_no) invisible;
alter index idx_2 invisible;

**Comment by fengttt** [comment]
probably not applicable.

**Comment by fengttt** [comment]
Wont fix
