### ISSUE TITLE
[Feature Request]: Support account service suspension and resumption

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6659]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Provides a switch that can be used to control whether the instance works or not

- When the service is suspended, all data cannot be accessed
- When the service is suspended, all business data cannot be lost
- Data needs to remain intact when service is restored
- Only the cluster administrator role can suspend and resume instances
- Instance pause and resume execution time should not exceed 60 seconds
- Only active instances can be paused and resumed, not upgraded or shut down instances.

**Comment by florashi181** [comment]
update this issue

**Comment by daviszhen** [comment]
After discussion, some conclusion:
1, account level
2, add new field "suspended_time timestamp", default is NULL;
3, reuse the field "status" with "open/suspended";
4, relax the restriction about 60 seconds.

**Comment by daviszhen** [comment]
After the discussion, the conclusion:
1, account level;
2, add new field "suspended_time timestamp",default is NULL;
3, reuse the status "open/suspended"
4, relax the restriction "60 seconds"
5, only the moadmin role can suspend or resume the account;
6, alter account statement(status_option) to suspend or resume the account;

**Comment by daviszhen** [comment]
Implementation Details:
1, When the account has been suspended, the new client with the user of the account can not access the mo.
2, A defect: When the account is suspended, but some users of the account are also online. These online users are not affected currently. It will be fixed in future.
3, When we reopen an already opened account or resuspend an already suspended account, there is no error.

**Comment by heni02** [comment]
test done ，bvt case pr merged

**Comment by heni02** [comment]
alter account testsuspend suspend;
alter account testsuspend OPEN;

**Comment by LiSong0214** [comment]
Acceptance passed
