### ISSUE TITLE
[Feature Request]: Implementing root permissions for mocloud

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6660]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

MOCloud need to run management SQLs, including manipulating account, write cloud specific information to tables that is readonly to user (e.g. region, instance name, AWS account ID), etc. MOCloud need proper permission to perform these operations.

### Describe the feature you'd like

Implementing root permission management for mo-cloud. There is a user, let's call it "root" (but the name does not matter), whose credential will be hold by MOCloud. "root" will have some default permissions one of the permission is that "root" has the privilege to grant or revoke permissions for itself, that is, the permission of "root" is dynamic and controlled by DCLs, rather than hardcoded.

**Comment by fengttt** [comment]
Not clear how to do this, need design.

**Comment by LiSong0214** [comment]
as discuss with @aylei , this request has been implement with other method. so  i will close it
