### ISSUE TITLE
[Feature Request]: Implement a session manager

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6661]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Allow the (mysql) session layer to be deployed independently with the execution layer. So that the session layer can be extended independently to add the following features: 

- IP Access Control (whitelist);
- Query routing in multi-tenant environment;
- Effective scale-out: production apps usually use connection pool, scale-out CN won't scale-out the performance in such scenarios since existing connections will not be recreated on the new CN instances if the app does not restart. With session manager, the session manager aware the new CN instances and load-balance txns to the new instances automatically;
- Graceful scale-in/rollling-update: scale-in/rolling-update CN is disruptive for mysql connection since mysql connection is stateful. With session manager, session manager can drain the txns on the CN instance before planned shutdown to avoid query failure when scale-in/rolling-update CNs.

**Comment by domingozhang** [comment]
need to be discussed

**Comment by fengttt** [comment]
Proxy?

**Comment by volgariver6** [comment]
relate to #8025

**Comment by volgariver6** [comment]
done with pr #8778 .

**Comment by heni02** [comment]
test done

**Comment by LiSong0214** [comment]
graceful scaling 还没做，继续开发

**Comment by volgariver6** [comment]
done

**Comment by aylei** [comment]
https://github.com/matrixorigin/matrixone/issues/11048 @volgariver6 这个要放进这个 issue 的 scope 吗？

**Comment by LiSong0214** [comment]
云平台使用基本没有问题，但 TPS 高时可能会一直找不到 session 迁移窗口，导致要等待很长时间才能迁走，并且当前这个时间没有上限，这个改进需求还蛮重要的，建议 1.1 P0 优先级做 #11048  @domingozhang

**Comment by volgariver6** [comment]
> 还有现在 CN hang 的情况下，proxy 的 failover 是怎么做的？ @volgariver6

这个问题已经处理了：https://github.com/matrixorigin/matrixone/pull/11366

**Comment by volgariver6** [comment]
> #11048 @volgariver6 这个要放进这个 issue 的 scope 吗？

这个问题再单独处理吧，我还没想好方案
