### ISSUE TITLE
[Feature Request]: Support to create system tables in sys account and read in other accounts

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6662]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Create a system table under sys account, which can be seen by other accounts
- Use the method with account id to insert the value, other accounts can only see the value that belongs only to their own account

**Comment by fengttt** [comment]
Not exactly clear to me what this means ...

**Comment by daviszhen** [comment]
1. sys创建表tableX
2. accA，accB 创建时就能看到 tableX（类似系统表）
3. accA，accB 只读表 tableX
4. sys 能read/write tableX
5. sys 不关心tableX具体实现
6. accA，accB 能看到 tableX的子集（类似statement_info，但不是外表）
7. accA，accB 看到 tableX的schema是相同的。但是区分accA，accB。
8. sys 写tableX时要指定，一定会指定accA,accB
9. accA，accB的admin角色可读，也可让其它用户可读
10. tableX的schema
    1. 运行时定义
        1. 一开始没有，运行一段时间后，sys创建tableX
        2. 如果accA，accB在tableX被创建前就存在，accA，accB也要能看到tableX
    2. 配置文件
        1. 指定schema

**Comment by domingozhang** [comment]
**DDL:**

CREATE CLUSTER TABLE [IF NOT EXISTS] [db.]table_name [comment = "comment of table"];
(
    name1 type1 [comment 'comment of column'] [AUTO_INCREMENT] [[PRIMARY] KEY],
    name2 type2 [comment 'comment of column'],
    ...
)
[partition_options];



1. CREATE CLUSTER TABLE means creating a table shared with different cluster.
2.The syntax of DROP and TRUNCATE will not be affected by CLUSTER table.

**DML：**

INSERT INTO [db.]table [(c1, c2, c3)] VALUES (v11, v12, v13), (v21, v22, v23), ...
  ACCOUNTS(account1,account2);

LOAD DATA
    INFILE 'file_name'
    INTO TABLE tbl_name
    [{FIELDS | COLUMNS}
        [TERMINATED BY 'string']
        [[OPTIONALLY] ENCLOSED BY 'char']
        [ESCAPED BY 'char']
    ]
    [LINES
        [STARTING BY 'string']
        [TERMINATED BY 'string']
    ]
    [IGNORE number {LINES | ROWS}]
    ACCOUNTS(account1,account2);

1. INSERT and LOAD will decide the account list, which the exact account can view inserted data.
2. The Syntax of UPDATE and DELETE will not be affected by CLUSTER table.

**Comment by daviszhen** [comment]
I has broken up the 6662 into 7231,7232,7233,7234,7235 and setup the schedule for them.

**Comment by daviszhen** [comment]
13日design。16日结束design并开始开发。预计23日能提PR。

**Comment by daviszhen** [comment]
it is almost done.

**Comment by LiSong0214** [comment]
acceptance passed
