### ISSUE TITLE
[Feature Request]: load S3 data supports bucket url & role arn & external_id

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6663]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

A SQL to import data from AWS S3 is as follows:
> load data url s3option {"endpoint"='s3.us-west-2.amazonaws.com', "access_key_id"='Axxxxxx', "secret_access_key"='rv/xxxxxx', "bucket"='test', "filepath"='a.txt', "region"='us-west-2', "compression"='none'} into table t1  FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n';

When the user enters the S3 bucket url, mo can parse the endpoint and region information from the S3 SDK. And support role arn for authorization authentication.Hope to support the following syntax

> load data url s3option {"bucket"='test', "filepath"='a.txt', "role_arn"='xxxx', "external_id"='yyy', "compression"='auto'} into table t1  FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n';

**Comment by heni02** [comment]
test done
