### ISSUE TITLE
[Feature Request]: Support load local file

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6665]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Load local files to MO using CLI tool

> LOAD DATA
    LOCAL
    INFILE 'file_name'
    INTO TABLE tbl_name
    [{FIELDS | COLUMNS}
        [TERMINATED BY 'string']
        [[OPTIONALLY] ENCLOSED BY 'char']
        [ESCAPED BY 'char']
    ]
    [LINES
        [STARTING BY 'string']
        [TERMINATED BY 'string']
    ]
    [IGNORE number {LINES | ROWS}]

**Comment by domingozhang** [comment]
local can be implemented

**Comment by daviszhen** [comment]
implement the related mysql protocol for local.

**Comment by mooleetzi** [comment]
under review

**Comment by heni02** [comment]
The mysql client side must add the -- local-infile parameter to execute load local file success

**Comment by heni02** [comment]
test done，case merged mo-load-data

**Comment by mooleetzi** [comment]
pls note that in mysql, if query aborted or inner error occurs, data transfer from client to server will not stop, as a result is that client will hang until data transfer done.

**Comment by LiSong0214** [comment]
acceptance passed

**Comment by LiSong0214** [comment]
mysql -h 127.0.0.1 -P 6001 -udump -p111 --local-infile
