### ISSUE TITLE
[Feature Request]: Support account-level storage statistics

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6668]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support data size statistics for each account
- can get all account name from CN
- CN may run cron task per day (or per hour), for calculating each account's total data size.

**Comment by daviszhen** [comment]
What the "total data size" includes?

**Comment by daviszhen** [comment]
按照讨论。6668就是让内核提供account的tae存储空间（不包括trace,metric和外表）。内核提供sql语句，输出这个tae的存储空间

**Comment by daviszhen** [comment]
After the discussion, the mo provides an sql to get the volume of the storage space of the TAE only. It does not include the trace, metric and the external tables.

**Comment by LiSong0214** [comment]
@iamlinjunhong How much S3 consumption is used to count storage usage?

**Comment by daviszhen** [comment]
it was done

**Comment by aressu1985** [comment]
test done

**Comment by LiSong0214** [comment]
acceptance passed
