### ISSUE TITLE
[Feature Request]: Support publish data to other accounts

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6669]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Any account can publish a database or table to other accounts in the cluster for reading
- who can publish：accountadmin
- who can read：publish_role:=accountadmin/public(default)

CREATE SUBSCRIPTION subscription_name
    CONNECT 'connect info'
    PUBLICATION publication_name [, ...]

DROP SUBSCRIPTION subscription_name

subscription_name: 
database name in current account

connect info:
account=account_name, user=user_name, password=password_string, database=database_name

publication_name: {ALL|table_name list}
table name list in remote account

### Additional information

Who can write data in sys account to share other account？ ACCOUNTADMIN of sys account
Who can read data in ordinary account？
1) if data in sysdbs,ACCOUNTADMIN first, or other role which granted privs.
2) if data in other db, public role

**Comment by domingozhang** [comment]
need be discussed

**Comment by florashi181** [comment]
update this issue and discuss again

**Comment by florashi181** [comment]
try a new solution and experiment about catalog @daviszhen

**Comment by florashi181** [comment]
update this issue @LiSong0214

**Comment by daviszhen** [comment]
需求的问题：
1，是否要提供发布，取消发布，订阅，取消订阅的语句？ 它们的语法是怎么样的?

场景：三个租户
accA:
    db1
    db2
    db3.t1 发布
    db3.t2
accC:
    db1

accB:

2，如果accB 中有db1了（db1可能是用create database创建的，也有可能是订阅accA.db1），accB订阅accC.db1会成功吗?
3，accB订阅accA.db3.t1时也会有同样的问题。db3可能会重名。t1一定不会重名。
4，订阅的数据库和表都是只读的。
5，取消订阅或取消发布后，订阅信息会同步删除。
6，租户删除时，订阅信息也会同步删除。
7，accB订阅accA.db3.t1后，看不见db3.t2。db3.t2没有被发布。
8，accB订阅accA.db1后。accA.db1中新增表tx时，accB.db1自动可见tx。
9，accA删除db1后，订阅信息会同步删除。accB看不到db1。
10，accA删除db3后，订阅信息会同步删除。accB看不到db3。
11，accA删除db3.t1后，订阅信息会同步删除。accB看不到db3.t1。

实现的问题：
1，accB要订阅accA.db1时，要在accB中create database db1，并标记出db1关联了accA.db1。
2，accB要订阅accA.db3.t1时，要在accB中create database db3，并标记出db3关联了accA.db3。并在其中创建t1的view关联accA.db3.t1。
3，accB中要不要记录对db1，db3，db3.t1的订阅信息。
4，accA中要不要记录被订阅的信息。

**Comment by mooleetzi** [comment]
doc https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUZ1xBszdwTJqoSDHOge?scode=AJsA6gc3AA8iCZswK5ARwAlwbUAK4

**Comment by tianyahui-python** [comment]
pass-test

**Comment by aressu1985** [comment]
test done
