### ISSUE TITLE
[Feature Request]: Add the mo permission to view and operate the cloud platform.

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6670]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

Currently, the display information of the cloud platform is stored in the system table, which makes it unreasonable that only the accountadmin role can view the information of the cloud platform by default. For example, the owner of a Database should be able to view the information of the database in the database details function.

### Describe the feature you'd like

- Set the usage and monitor permissions of some objects, so that users can see some database details in the database details
- Set the observation permission of the dashboard, so that ordinary users can also view the dashboard information
- Ordinary SQL users can view their query history and details in the query history list

**Comment by sukki37** [comment]
As talked with @LiSong0214, move to Backlog for now
