### ISSUE TITLE
[Feature Request]: Add some database statistics

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6671]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Number of tables in the database
- Number of columns in the table
- Number of rows in the table
- Size of the table
- The maximum and minimum values of the data in the table

**Comment by fengttt** [comment]
I am confused by this one -- is this just some SQL statement we need to run?

Some stats, like number of rows in table, could be 1. too expensive, 2. changing every second

**Comment by DanielZhangQD** [comment]
> I am confused by this one -- is this just some SQL statement we need to run?
> 
> Some stats, like number of rows in table, could be 1. too expensive, 2. changing every second


- Number of tables in the database
- Number of columns in the table
  - The above two items can be retrieved by simple SQLs, and it's a nice-to-have if we have stats for them
- Number of rows in the table
  - It's also expensive if we run `count(*)` for each table whenever the user checks this info
- Size of the table
  - This should be calculated and recorded by MO, right?
- The maximum and minimum values of the data in the table
  - This is similar to the `Number of rows in the table` case

**Comment by domingozhang** [comment]
provide the last three features in the list

**Comment by daviszhen** [comment]
1, put it into trace or metric?
2, provide a kind of sql to get the statistics?

**Comment by LiSong0214** [comment]
I prefer use a sql cause it can save cost. you can design what sql looks like.

**Comment by daviszhen** [comment]
> I prefer use a sql cause it can save cost. you can design what sql looks like.

Ok, we can design a suitable method.

**Comment by daviszhen** [comment]
currently, "Number of rows in the table" has been supported in 0.6. It is "show table status".

**Comment by ouyuanning** [comment]
I will be responsible for this issue.
and i will guide @YANGGMM to complete it.

**Comment by YANGGMM** [comment]
show table_values stmt have some error when the column type is json,  now have a issue https://github.com/matrixorigin/matrixone/issues/7516 to follow it.

**Comment by aressu1985** [comment]
test done

**Comment by LiSong0214** [comment]
@YANGGMM we can use sql like: 'show table_number', 'show column_number', 'show table_values', but 'show table_size' dose not work, instead of 'select mo_table_size();'. why?
@fengttt what do you think about this?

**Comment by YANGGMM** [comment]
Because we didn't have any interface to get accurate table_size, so we didn't achieve the show table_size stmt after we associated with @domingozhang , and the mo_table_size() function was achieved by @sukki37 , this function can get table_size with rows * row size which is not accurate. @LiSong0214

**Comment by LiSong0214** [comment]
pls give an issue to implement it in mo0.8. @YANGGMM
