### ISSUE TITLE
[Feature Request]: Support to modify account comment

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6673]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

alter account <account_name> comments ='<new comments>';

**Comment by LiSong0214** [comment]
In MO v0.7, remove this issue, add #7042

**Comment by daviszhen** [comment]
As mentioned above, it is not included in the version 0.7. But I also implement it by the way.

**Comment by heni02** [comment]
test done, pr merged

**Comment by LiSong0214** [comment]
acceptance passed
