### ISSUE TITLE
[Feature Request]: save query results

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6674]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- storage format: csv
- storage location: tae
- save time：24 hours. (If it exceeds, it will be automatically cleared)
- get result: select query_result(statement_id) limit 1000;
- who can select: execute role or granted role
- switch by account: save_query=on/off(default)

**Comment by domingozhang** [comment]
to be discussed

**Comment by iamlinjunhong** [comment]
document https://github.com/matrixorigin/docs/blob/main/design/save%20query%20result.md

**Comment by aressu1985** [comment]
test done
