### ISSUE TITLE
[Feature Request]: Categories that support queries

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6675]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Add query type to query history

- Add query type to query-related metrics monitoring

- Inquiry category and details
DQL（Data Query Language）：Select
DDL（Data Definition Language）：Create/Drop/Alter/Rename Database/Table/View/Index
DML（Data Manipulation Language）：Insert、Update、Delete
DCL（Data Control Language）：Grant、Revoke
TCL（Transaction Control Language）：Begin、Savepoint、Rollback、Commit

**Comment by fengttt** [comment]
@daviszhen , I would like to accept this one but want your voice.

**Comment by daviszhen** [comment]
Currently, wo do not support the statement "Savepoint".

**Comment by xzxiong** [comment]
all statement and query type info
https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIMdqhP68fTriN2n6CjD?scode=AJsA6gc3AA82XGeL0oAW0A-gb6AOI

**Comment by xzxiong** [comment]
for query history
- record In statement_info.query_type and statement_info.statement_type, all val declear in [doc](https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIMdqhP68fTriN2n6CjD?scode=AJsA6gc3AA82XGeL0oAW0A-gb6AOI)

for metric 
- related 2 metric: `sql_statement_total`, `sql_statement_errors`
- record in column `type`, more details in [doc](https://github.com/matrixorigin/docs/blob/main/design/observability/metrics.md)

**Comment by xzxiong** [comment]
update queryType in #7610, as [doc](https://doc.weixin.qq.com/sheet/e3_AW0A-gb6AOIMdqhP68fTriN2n6CjD?scode=AJsA6gc3AA82XGeL0oAW0A-gb6AOI) `Query Type (Final)` value

**Comment by LiSong0214** [comment]
acceptance passed
