### ISSUE TITLE
[Feature Request]: Metric/log table support Time Series engine feature

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6677]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

提升视图展示和告警查询时的性能

**Comment by fengttt** [comment]
More specific requirement needed.   @xzxiong please supply use case sql statments so that sql team will know what is needed.

**Comment by xzxiong** [comment]
cooperate with @gavinyue , use stream engine to store and calculate metric/logs data.
need fix following issues:
1.  update statement_info  record with same id(statement_id) can be merge in one record.
2. improve those metric/logs query performance, including tables in database `system_metrics` and `system`

**Comment by xzxiong** [comment]
the following statement is typical query from MOCloud 
raw record in here  [query.list.txt](https://github.com/matrixorigin/matrixone/files/11086551/query.list.txt) (1000 records)

usage | statement
-- | --
query sql_statement_total  in 30 minutes, agg data each minute | select stat_ts, sum(value) as value, type from (select concat(date_format(collecttime, "%Y-%m-%d %H"), ":", lpad(1 * floor(minute(collecttime) / 1), 2, 0), ":00") as stat_ts, avg(value) / 15 as value, node, type from sql_statement_total where mo_log_date(__mo_filepath) between "2023-03-28" and "2023-03-28" and collecttime >= "2023-03-28 02:11:14" and collecttime <= "2023-03-28 02:41:14" and type in ("DQL", "DDL", "DML", "DCL", "TCL", "Other") group by node, type, concat(date_format(collecttime, "%Y-%m-%d %H"), ":", lpad(1 * floor(minute(collecttime) / 1), 2, 0), ":00") order by concat(date_format(collecttime, "%Y-%m-%d %H"), ":", lpad(1 * floor(minute(collecttime) / 1), 2, 0), ":00") limit 100) as t group by stat_ts, type
count statement_info in time range | select count("*") from system.statement_info where mo_log_date(__mo_filepath) between "2023-03-28 01:08:53" and "2023-03-28 03:08:53" and request_at >= "2023-03-28 01:08:53" and request_at <= "2023-03-28 03:08:53" and sql_source_type in ("cloud_user_sql", "external_sql")
query statement_info where filter condition | select stats, duration, sql_source_type from system.statement_info where mo_log_date(__mo_filepath) between ? and ? and status != ? and account = ? and response_at >= ? and response_at < ?
insert cu calculation | insert into mo_cloud.cu (account, start_time, end_time, cu, type) values (?, ?, ?, ?, ?)

**Comment by xzxiong** [comment]
Follow on the window function implementation in  https://github.com/matrixorigin/matrixone/issues/8590.
Here will refactor those metric on database `system_metrics`, which sub system is `sql`

```
+-------------------------------+
| Tables_in_system_metrics      |
+-------------------------------+
| metric                        |
| sql_statement_total           | <-
| sql_statement_errors          | <-
| sql_transaction_total         | <-
| sql_transaction_errors        | <- 
| server_connections            |
| server_storage_usage          |
| process_cpu_percent           |
| process_resident_memory_bytes |
| process_open_fds              |
| sys_cpu_seconds_total         |
| sys_cpu_combined_percent      |
| sys_memory_used               |
| sys_memory_available          |
| sys_disk_read_bytes           |
| sys_disk_write_bytes          |
| sys_net_recv_bytes            |
| sys_net_sent_bytes            |
+-------------------------------+
18 rows in set (0.02 sec)
```

**Comment by xzxiong** [comment]
stale issue
