### ISSUE TITLE
[Feature Request]: improve point query performance on EXTERNAL table

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6678]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

缩短查询历史展示延迟
- needs query data with filepath (or/and timestamp) condition

**Comment by fengttt** [comment]
filepath need to happen in 0.7.     

our own format and mix our own format and csv read is highly desirable for 0.7

**Comment by daviszhen** [comment]
Need to be clear:
1, filepath need to be more specific.
2, format also need to be more specific.

**Comment by heni02** [comment]
test done
