### ISSUE TITLE
[Feature Request]: support cmd to delete metric/log with table or date args

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6679]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

删除 metric/log 的历史记录

**Comment by dengn** [comment]
Please explain if this is user feature or internal command?

**Comment by xzxiong** [comment]
pls trace in https://github.com/matrixorigin/matrixone/issues/5254
