### ISSUE TITLE
[Feature Request]: EXTERNAL table need support read from  zonemap datafile

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6680]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

EXTERNAL table needs to support read from zoommap datafile. 
log/metric data may write zonemap data file after async cron merge task.

**Comment by domingozhang** [comment]
merge a new issue for related external performance issues

**Comment by daviszhen** [comment]
Who provide the read/write interface of the zonemap data file? Also we provide this.

**Comment by heni02** [comment]
test done
