### ISSUE TITLE
[Feature Request]: improve simdcsv memory usage

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6681]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

降低 metric/log merge 的内存消耗

**Comment by fengttt** [comment]
Must control memory usage of input/output of csv parser.   Even though we may retire simdcsv

**Comment by daviszhen** [comment]
rfc4180

**Comment by xzxiong** [comment]
suggestion
--
simdcsv::Reader accept buffer 

Background
--
simdcsv:: Reader can NOT control mem alloc, or use buffer.
each `Read()` alloc all new string in `records`
![image](https://user-images.githubusercontent.com/3927687/223043513-0077e529-d529-470f-bac6-b7636ed6e102.png)

**Comment by xzxiong** [comment]
after https://github.com/matrixorigin/matrixone/pull/8360, already remove `simdcsv` in query external table.
