### ISSUE TITLE
[Feature Request]: Role and Privilege enhancement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6682]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

- Support Owner Logic and related privileges
- altering configuration needs check the privileges. if account level, must be moadmin role. if db level, must be db owner.
- alter user password

**Comment by fengttt** [comment]
@sukki37 please triage, to see if this is cloud feature or this need engine support.

**Comment by YANGGMM** [comment]
altering configuration will do in https://github.com/matrixorigin/matrixone/issues/9096

**Comment by heni02** [comment]
Support Owner Logic and related privileges 
alter user password
test done

**Comment by heni02** [comment]
altering configuration  not completed

**Comment by heni02** [comment]
altering configuration test done, current problems ：https://github.com/matrixorigin/matrixone/issues/11341

**Comment by heni02** [comment]
issue closed, all test done
