### ISSUE TITLE
[Bug]: The execution result is not as expected.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6714]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
commit id:bb9c3edb9ba7f69bcaa1c28d553ed6eeef87aecd

use information_schema;
show tables;
desc key_column_usage;
select table_name, column_name from key_column_usage limit 2;
desc columns;
select table_name, column_name from columns where table_schema = 'mo_catalog' limit 5;

expected result：
table_name    column_name
mo_database    dat_id
mo_database    datname
mo_database    dat_catalog_name
mo_database    dat_createsql
mo_database    owner

actual result:
empty

**Comment by nnsgmsone** [comment]
The mo_catalog field given by dn is not set. So it can't be query.

**Comment by ouyuanning** [comment]
PR is waiting for review

**Comment by tianyahui-python** [comment]
<img width="1362" alt="截屏2022-11-21 10 22 22" src="https://user-images.githubusercontent.com/39303074/202947880-f34f43ed-3798-45fb-83ef-7a31a846efce.png">
