### ISSUE TITLE
[Bug]: DATA RACE in logservicedriver

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#6745]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![图片](https://user-images.githubusercontent.com/28624654/202380613-6696789e-463f-42ea-b5db-ec3bb949be10.png)

**Comment by w-zr** [comment]
![图片](https://user-images.githubusercontent.com/28624654/202676937-cb34fc5d-e731-497a-913b-65254ec54ed0.png)

**Comment by w-zr** [comment]
![图片](https://user-images.githubusercontent.com/28624654/203209462-0b9f2a8d-4b7e-4bdb-b782-7a66ebbb171f.png)

**Comment by w-zr** [comment]
[current_service.zip](https://github.com/matrixorigin/matrixone/files/10063347/current_service.zip)

**Comment by jiangxinmeng1** [comment]
I print log before and after append.
<img width="394" alt="1" src="https://user-images.githubusercontent.com/51114574/203452519-4006f595-8015-4ce2-82bb-0f1c26a3c2d1.PNG">
Around data race, every append start after previous append end.
<img width="575" alt="3" src="https://user-images.githubusercontent.com/51114574/203452601-12cfc3fb-7659-42f0-9a85-6176c572f5f7.PNG">
[failed_29.zip](https://github.com/matrixorigin/matrixone/files/10072238/failed_29.zip)

**Comment by jiangxinmeng1** [comment]
Data race is at line 67193, the related append start at line 67306, at 23:58:15.141264. Previous append end at line 67133, at 23:58:15.129353.
<img width="1038" alt="1" src="https://user-images.githubusercontent.com/51114574/203453411-f87a1a3b-b380-4279-af74-3a7c47dee461.PNG">
<img width="929" alt="3" src="https://user-images.githubusercontent.com/51114574/203453423-5bec3a25-6fbd-40c0-8fa9-68cb9651a2ab.PNG">
<img width="922" alt="4" src="https://user-images.githubusercontent.com/51114574/203453448-0345d0f3-d435-4237-807b-1b7b1db2fd9a.PNG">

**Comment by zhangxu19830126** [comment]
#6933 may solve the problem, look at the test results. to verify our renewed understanding of DATA RACE

**Comment by zhangxu19830126** [comment]
fixed in https://github.com/matrixorigin/matrixone/pull/6933.  The data race here just means that it may occur, not that it has occurred, and the cases that may occur are more complex. Put in 0.7 to verify.
