### ISSUE TITLE
[Feature Request]: Distinguish internal SQL executed by non-users

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#6746]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Some non-user-executed SQL needs to be differentiated so that it can be used when the query history needs to be displayed to the user
- Differentiate the sql sent automatically by mo, like "select @@version_comment limit 1" when connect mo;
- Provide a way (such as parameters) to tell mo that this sql is a non-user when sending sql

**Comment by fengttt** [comment]
depends on query tag/flag.

**Comment by domingozhang** [comment]
Can we add a new columns in statement_info to distinguish the source of SQL?

**Comment by xzxiong** [comment]
see more detail on

**Comment by LiSong0214** [comment]
acceptance passed
