### ISSUE TITLE
[Bug]: eks test: load data s3 file 1000w rows reported context deadline exceeded and logservice crash

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6761]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):image 0.6.0-42725ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
load s3 l000w 100column rows report error:
![image](https://user-images.githubusercontent.com/113406637/202460999-fa1d94e5-9ba6-4af6-b9fd-2826bc06bb5e.png)

and other problem is logservice crash, releated logs is upload this issue
<img width="801" alt="企业微信截图_a7077662-2ea3-45a8-9eab-685c342dcfb6" src="https://user-images.githubusercontent.com/113406637/202461883-80ce9839-c3d4-47d3-9430-d35be6865be4.png">

### Steps to Reproduce

```Markdown
create table table_10000000_100_columns( clo1 tinyint, clo2 smallint, clo3 int, clo4 bigint, clo5 tinyint unsigned, clo6 smallint unsigned, clo7 int unsigned, clo8 bigint unsigned, col9 float, col10 double, col11 varchar(255), col12 Date, col13 DateTime, col14 timestamp, col15 bool, col16 decimal(5,2), col17 text, col18 varchar(255), col19 varchar(255), col20 varchar(255), col21 varchar(255), col22 varchar(255), col23
varchar(255), col24 varchar(255), col25 varchar(255), col26 varchar(255), col27 varchar(255), col28 varchar(255), col29 varchar(255), col30 varchar(255), col31 varchar(255), col32 varchar(255), col33 varchar(255), col34 varchar(255), col35 varchar(255), col36 varchar(255), col37 varchar(255), col38 varchar(255), col39 varchar(255), col40 varchar(255), col41 varchar(255), col42 varchar(255), col43 varchar(255), col44 varchar(255), col45 varchar(255), col46 varchar(255), col47 varchar(255), col48 varchar(255), col49 varchar(255), col50 varchar(255), col51 varchar(255), col52 varchar(255), col53 varchar(255), col54 varchar(255), col55 varchar(255), col56 varchar(255), col57 varchar(255), col58 varchar(255), col59 varchar(255), col60 varchar(255), col61 varchar(255), col62 varchar(255), col63 varchar(255), col64 varchar(255), col65 varchar(255), col66 varchar(255), col67 varchar(255), col68 varchar(255), col69 varchar(255), col70 varchar(255), col71 varchar(255), col72 varchar(255), col73 varchar(255), col74 varchar(255), col75 varchar(255), col76 varchar(255), col77 varchar(255), col78 varchar(255), col79 varchar(255), col80 varchar(255), col81 varchar(255), col82 varchar(255), col83 varchar(255), col84 varchar(255), col85 varchar(255), col86 varchar(255), col87 varchar(255), col88 varchar(255), col89 varchar(255), col90 varchar(255), col91 varchar(255), col92 varchar(255), col93 varchar(255), col94 varchar(255), col95 varchar(255), col96 varchar(255), col97 varchar(255), col98 varchar(255), col99 varchar(255), col100 varchar(255));

load data url s3option{"endpoint"='s3.us-west-2.amazonaws.com', "access_key_id"='xxxx', "secret_access_key"='xxxx', "bucket"='mo-load-data', "filepath"='load_data/100_columns/10000000_100_columns_load_data.csv', "region"='us-west-2'} into table test.table_10000000_100_columns FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
```

**Comment by heni02** [comment]
[date17_log.zip](https://github.com/matrixorigin/matrixone/files/10032105/date17_log.zip)

**Comment by heni02** [comment]
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: daily-mo-dis
  namespace: mo-dailybuild
spec:
  nodeSelector:
    # 使用专门的节点组，避免和 CI runner 混部
    role: mo
  dn:
    cacheVolume:
      size: 1Gi
    config: |
      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = 100
      scan-interval = "5s"
      incremental-interval = "60s"
      global-interval = "100000s"
    replicas: 1
    resources:
      requests:
        cpu: 2
        memory: 1Gi
  imageRepository: matrixorigin/mo-tester
  logService:
    replicas: 3
    sharedStorage:
      s3:
        path: heni-test/mo-data1/
        secretRef:
          name: awshn
    volume:
      size: 10Gi
    config: |
      [log]
      level = "info"
      format = "json"
      max-size = 512
    resources:
      requests:
        cpu: 2
        memory: 1Gi
  tp:
    cacheVolume:
      size: 1Gi
    config: |
      [cn.Engine]
      type = "distributed-tae"
      [log]
      level = "debug"
      format = "json"
      max-size = 512
    replicas: 2
    resources:
      requests:
        cpu: 4
        memory: 1Gi
  version: 0.6.0-42725ac

**Comment by daviszhen** [comment]
we do not focus on it today

**Comment by heni02** [comment]
regression commit id：2bfec0c2c713d15b518f74f9cd2e2ab0f5076214 image：nightly-2bfec0c
load s3 failed：
![image](https://user-images.githubusercontent.com/113406637/205193568-92eaebe1-4713-4ad3-b7f5-071228f70cbc.png)
after error report，the mo status is cn1 pod recreate status，this is abnormal，Please see the attached log file
![image](https://user-images.githubusercontent.com/113406637/205193734-e6eb0300-8177-4c2c-b074-3124b8fcb226.png)

**Comment by heni02** [comment]
[cn0.zip](https://github.com/matrixorigin/matrixone/files/10137379/cn0.zip)
cn1 log 368M can not upload，plz contact me

**Comment by heni02** [comment]
Latest image version :nightly-657e5c1b confirm, the result is dn crash
![image](https://user-images.githubusercontent.com/113406637/206684455-838f404f-f960-4f97-9486-6c974a4a2a44.png)
crash log:
{"level":"INFO","time":"2022/12/09 10:32:51.503753 +0000","caller":"rpc/handle.go:587","msg":"[precommit] handle write end txn: ctx[D974B4D56C554F988BBCF4E48F6C4292][1670581969269016556-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>\n"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x172fc68]

goroutine 5934 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*persistedNode).BatchDedup(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/pnode.go:88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseBlock).PersistedBatchDedup(0x400e3ca980, 0x400e3decf0, {0x0, 0x0, 0x0, 0x0, 0xec, 0xc7, 0x73, 0x2e, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/base.go:340 +0x48
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*block).BatchDedup(0x400e3c1030, {0x2836190, 0x4005ebd030}, {0x2829278, 0x40072b4d80}, 0x0?, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/blk.go:146 +0x188
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Dedup(0x4002f9a2d0, {0x2829278, 0x40072b4d80})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:782 +0x218
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).DoBatchDedup(0x4002f9a2d0, {0x2829278, 0x40072b4d80})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:879 +0x108
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0x4002f9a2d0, 0x4008616640)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:560 +0x70
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0x400757b220?, 0x400e55ee20?, 0x400de720ec?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:121 +0x50
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0x40072d5418?, 0x40072b4f00?, 0x2?, 0x282ac18?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:181 +0x88
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0x4005ebd480, 0x400de720ec?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl/relation.go:162 +0x78
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0x40054ad650, {0x1c?, 0x40072d55c8?}, 0x40082da100)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine/txn_relation.go:54 +0x2c8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(0x400e5908d0, {_, _}, {{0x400de0fbc0, 0x10, 0x10}, 0x0, {0x172f19732e73c7ec, 0x0, 0x38b2, ...}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:609 +0x330
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(0x400e5908d0, {_, _}, {{0x400de0fbc0, 0x10, 0x10}, 0x0, {0x172f19732e73c7ec, 0x0, 0x38b2, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc/handle.go:124 +0x5d8
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(0x400d7baea0?, {_, _}, {{0x400de0fbc0, 0x10, 0x10}, 0x0, {0x172f19732e73c7ec, 0x0, 0x38b2, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/storage/tae/storage.go:70 +0x5c
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0x4009b28120, {0x27adb58, 0x40054acd50}, 0x400fb42580, 0x40108f2b80)
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/service/service_cn_handler.go:231 +0xa14
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0x4002f9b5b0?, {0x27adb58, 0x40054acd50}, 0x400fb42580, 0x40108f2b80)
	/go/src/github.com/matrixorigin/matrixone/pkg/dnservice/store_rpc_handler.go:108 +0x8c
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0x4002f9b560, {0x27adb58?, 0x40054acd50?}, {0x27d45e0?, 0x400fb42580?}, 0x4860e0?, {0x276fdc0, 0x400e582080})
	/go/src/github.com/matrixorigin/matrixone/pkg/txn/rpc/server.go:161 +0x434
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0x4002f9b680, {0x27f9340, 0x40058c9100}, {0x220bac0?, 0x40054acdb0}, 0x66)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/server.go:194 +0x3e4
github.com/fagongzi/goetty/v2.(*server).doConnection(0x400351d9a0, {0x27f9340, 0x40058c9100})
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221121133015-81355a910e4a/application.go:381 +0x2b8
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221121133015-81355a910e4a/application.go:344 +0x78
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221121133015-81355a910e4a/application.go:336 +0x3a4

**Comment by heni02** [comment]
[dn_09.log](https://github.com/matrixorigin/matrixone/files/10193995/dn_09.log)

**Comment by aptend** [comment]
> Latest image version : nightly-29e7e61e confirm, the result is dn logservice crash <img alt="企业微信截图_67523c51-e3c4-4763-8076-c40386d4e6ca" width="1358" src="https://user-images.githubusercontent.com/113406637/207535006-86808b3f-d893-4676-8c73-10f5446838ed.png"> <img alt="企业微信截图_f7397cca-b9b8-410a-b21b-b033d6a6d52d" width="886" src="https://user-images.githubusercontent.com/113406637/207535173-251480c4-2ed8-4420-97a7-05e79ea0af18.png"> log: [ekslog.zip](https://github.com/matrixorigin/matrixone/files/10225424/ekslog.zip) @aptend


since 07:29:16.049362, dn can't connect to logservice, and 3 min later, timeout panic
<img width="2002" alt="image" src="https://user-images.githubusercontent.com/49832303/207539899-8941282e-9c15-4361-bfc0-82cde80e3bfe.png">
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/49832303/207539979-32002875-9278-4361-840a-28f3d7eeeaff.png">

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
![Image](https://user-images.githubusercontent.com/14086886/212711185-d4f0dd64-d681-4c9c-82c8-fd2a01098c07.png)

**Comment by LeftHandCold** [comment]
pls help to check it. @jianwan0214

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/14086886/213666238-a99a720b-e987-46b5-8cc3-31fdff36d1cf.png">
The reason for "context deadline exceeded" is that the ebs of logservice is full and 10g is not enough.

**Comment by LeftHandCold** [comment]
The memory consumption of dn has been 3~4G
<img width="670" alt="image" src="https://user-images.githubusercontent.com/14086886/213667287-fa2e69f5-319e-40e7-b471-f42fae7f76c4.png">

**Comment by LeftHandCold** [comment]
in process

**Comment by LeftHandCold** [comment]
<img width="2167" alt="image" src="https://user-images.githubusercontent.com/14086886/215936215-ae9a4bca-c68c-4a1d-97ca-9544e92c9d29.png">

**Comment by heni02** [comment]
comfirm,closed
