### ISSUE TITLE
[Enhancement]: tombstone block should be sorted by rowid

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6775]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
flush block deletes batch sorted by row.
if sorted, the deletes batch consumer can get the max deleted row easily.
```

**Comment by fengttt** [comment]
I don't understand the issue, but hope for a design doc.

**Comment by fengttt** [comment]
dup #11471
