### ISSUE TITLE
[Bug]: insert into table a select * from a execute stuck

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6780]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):0ca18fd72cf4d3eda0e03c30f9fa82725f804f90
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When the insert target table and source table are the same, the load is stuck，It is recommended to use large amount of data

sql: insert into table_100w select * from table_100w where clo1>10 ; 
![image](https://user-images.githubusercontent.com/113406637/202678810-6c72f865-f0a4-469f-b9b0-f1177a6325f2.png)

See the attachment for the complete log
part log:  
2022/11/18 18:10:45.837579 +0800 ERROR frontend/util.go:520 rollback the txn. connectionId 1047
github.com/matrixorigin/matrixone/pkg/frontend.logErrorf
        /Users/heni/test-envir/matrixone/pkg/frontend/util.go:520
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/heni/test-envir/matrixone/pkg/frontend/routine.go:180
2022/11/18 18:10:45.875855 +0800 INFO frontend/util.go:510 check password succeeded connectionId 1048
2022/11/18 18:10:48.839224 +0800 INFO frontend/util.go:510 check password succeeded connectionId 1050
2022/11/18 18:10:48.839618 +0800 INFO frontend/util.go:495 query trace {"connection_id": 1050, "query": "use mo_task", "session_info": "connectionId 1050"}
[mysql] 2022/11/18 18:10:50 packets.go:37: read tcp 127.0.0.1:50311->127.0.0.1:6001: i/o timeout
2022/11/18 18:10:50.894315 +0800 ERROR cn-service.txn util/log.go:130 txn send requests failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "requests": "[0: <bf9e84a626f44edfa06378cc6b2e8ca8/Active/S:1668766245893208000-0>/Read/F-0/=><2-262146-0-127.0.0.1:22000>]", "error": "context canceled"}
2022/11/18 18:10:50.894511 +0800 ERROR frontend/session.go:1432 GetTxn. error:context canceled
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).GetTxn
        /Users/heni/test-envir/matrixone/pkg/frontend/session.go:1432
github.com/matrixorigin/matrixone/pkg/frontend.doUse
        /Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:1000
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleChangeDB
        /Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:1018
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:3145
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:3813
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/heni/test-envir/matrixone/pkg/frontend/routine.go:160
2022/11/18 18:10:50.894637 +0800 ERROR frontend/util.go:505 context canceled {"session_info": "connectionId 1048"}
github.com/matrixorigin/matrixone/pkg/frontend.logError
        /Users/heni/test-envir/matrixone/pkg/frontend/util.go:505
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:3658
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:3813
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /Users/heni/test-envir/matrixone/pkg/frontend/routine.go:160
2022/11/18 18:10:50.895413 +0800 ERROR frontend/util.go:505 query trace status {"connection_id": 1048, "statement": "use mo_task", "status": "fail", "error": "context canceled", "session_info": "connectionId 1048"}
github.com/matrixorigin/matrixone/pkg/frontend.logError

**Comment by heni02** [comment]
[mo.log](https://github.com/matrixorigin/matrixone/files/10040408/mo.log)

**Comment by LeftHandCold** [comment]
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/14086886/202952894-f3013ff9-91ae-4e97-bea2-bbc1a652ae43.png">

**Comment by LeftHandCold** [comment]
same as #6753

**Comment by LeftHandCold** [comment]
The root cause is that the data sent by CN exceeds 100M, and DN failed to read.

**Comment by LeftHandCold** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/14086886/202968214-0e6a49f7-e39c-4690-b339-91f69390e144.png">

**Comment by reusee** [comment]
will do this in 0.7

**Comment by reusee** [comment]
will do this in 0.7

**Comment by reusee** [comment]
I think this issue should be closed since it's tracked in #6824

**Comment by reusee** [comment]
Same as above, waiting for a reply.

**Comment by reusee** [comment]
I'm going to re-assign this issue to @m-schen

**Comment by m-schen** [comment]
try to verify it after #6824 is done.

**Comment by m-schen** [comment]
wait the #6824

**Comment by m-schen** [comment]
> wait the #6824

the same to it.

**Comment by m-schen** [comment]
> > wait the #6824
> 
> the same to it.

等这个

**Comment by m-schen** [comment]
等6824后验证

**Comment by m-schen** [comment]
> try to verify it after #6824 is done.

the same to it. 😠

**Comment by m-schen** [comment]
wait for 6824.

**Comment by m-schen** [comment]
> wait for 6824.

the same to it.

**Comment by m-schen** [comment]
> wait for 6824.

the same to it.

**Comment by m-schen** [comment]
> wait for 6824.

same to 6824.

**Comment by nnsgmsone** [comment]
no process

**Comment by m-schen** [comment]
6824 is ok and I will do a simple check tomorrow. if ok, I will assign it back.

**Comment by m-schen** [comment]
6824 will write batch to s3 directly if batch is more than 20w rows.

Hackeeper needs to be configured. 
you can use ./etc/launch-tae-cn-tae-dn/launch.toml to verify it. @heni02

**Comment by heni02** [comment]
confirm, it loaded successfully ,table_1000w is 1050w rows @m-schen 
commit id:a19a7efb38c1c874018c978534fda07a7aa041b9
![image](https://user-images.githubusercontent.com/113406637/216313193-243f3fc3-1e95-4402-a821-2ee8009ca40c.png)

**Comment by heni02** [comment]
closed
