### ISSUE TITLE
[Bug]: loop execute load data, Cause mo service oom.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#6793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Reproducible Steps:

platform: 128 server

1.mo path: /data1/tianyahui/matrixone   (The failure log still exists)
2.load data script path: /data/mo-load-data
3.execute command: nohub bash loop.sh &
4.loop default setting: 127G size csv. (table_40000000_100_columns.yml)
5.mo-load-data log:
[mo-load-data.log](https://github.com/matrixorigin/matrixone/files/10048887/mo-load-data.log)
6.The seventh load data execution failed. (mo server oom, mo.log path: /data1/tianyahui/matrixone/mo.log )

**Comment by nnsgmsone** [comment]
The reason for this is because cn's memtable is not yet gc, and this @reusee   will be taken care of later.

**Comment by reusee** [comment]
It's #6232

**Comment by reusee** [comment]
@tianyahui-python Please re-run with this PR's branch: https://github.com/matrixorigin/matrixone/pull/6862

**Comment by reusee** [comment]
@tianyahui-python I don't have access to this 128 machine. And Sudong said the 128 machine is for testing only.
Or how can I get this data to run locally?

**Comment by reusee** [comment]
Mochen has some remaining work related to GC to be done.

**Comment by reusee** [comment]
Fixed with these commits:
https://github.com/matrixorigin/matrixone/commit/ec44102df1ad19c96a6e580bd9811fe5fdc8584c
https://github.com/matrixorigin/matrixone/commit/1e5aee46bd2f29ab1e338f098d0a726dc69e2233

**Comment by tianyahui-python** [comment]
commit 32ca2a6c033deab4878240045e96ae817a3e8dff

<img width="1617" alt="截屏2022-11-28 09 50 58" src="https://user-images.githubusercontent.com/39303074/204174952-22ad62f4-2717-4272-838f-904ac5c6e1c4.png">


log path: 128 server /data1/github/matrixone/mo.log

**Comment by tianyahui-python** [comment]
@jianwan0214

**Comment by reusee** [comment]
I'm fixing the memory table, which does not use mpool.
It may be somewhere using the global mpool but not releasing.
@jianwan0214 you can run mo-service with -debug-http :7890, then open HTTP://localhost:7890/debug/heap to check the heap allocations.

**Comment by reusee** [comment]
I'm adding unit tests to collect memory profiles.

**Comment by reusee** [comment]
In progress

**Comment by reusee** [comment]
TAE fixed some memory leak bugs.

**Comment by reusee** [comment]
Should I re-assign this to Hanfeng? He's optimizing TAE memory usage.

**Comment by reusee** [comment]
I think this is the same issue that Hanfeng is fixing. Re-assign to him.

**Comment by aptend** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/a248ad7b7809d5185bbbd50b41bb4c56932c5393, @tianyahui-python   please check

**Comment by tianyahui-python** [comment]
in the test .......

**Comment by tianyahui-python** [comment]
commit id: b2adc7c61dd2895d4e1601a7efe534b0bf499220

bug have been fixed.
