### ISSUE TITLE
[Feature Request]: Improve performance of External table

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6798]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Improve these related performance of external table:
EXTERNAL table need support read from zonemap datafile https://github.com/matrixorigin/matrixone/issues/6680
improve point query performance on EXTERNAL table https://github.com/matrixorigin/matrixone/issues/6678

**Comment by daviszhen** [comment]
It is the overall performance requirement includes 6680, 6678

**Comment by heni02** [comment]
test done
