### ISSUE TITLE
[Feature Request]: Initial password for dump and root

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6799]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

User can initial the password of root and dump in sys account during the first boot of MO

**Comment by domingozhang** [comment]
only initial password feature in 0.7 
change user password action will be implemented in future

**Comment by daviszhen** [comment]
After the discussion with @domingozhang, we provide a way to initialize the password of the root and dump user. For instance, "a environment variable" or "make build password = xxxx",etc

**Comment by daviszhen** [comment]
云平台不建议再make build 时，指定初始化密码。

DEFAULT_PASSWORD env 只在集群初始化时，用一次。如果DEFAULT_PASSWORD为空或不存在，密码还是111。集群初始化后，不会再用。之后，alter user 或 alter account 修改用户密码，不会用到DEFAULT_PASSWORD.

**Comment by mooleetzi** [comment]
before first run mo-service:
1. export DEFAULT_PASSWORD='${your password}'
2. run mo-service
3. use '${your password}' in mysql client to login
