### ISSUE TITLE
[Performance]: Improve Vector

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#6812]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

In some join workload, the interface{} operations in Vector is very time-consuming. It occupies more than 90% of the total time cost in profiling.

Assigning a slice to an interface{} variable in Go always allocates a slice header on heap. And the join operator has n_columns x n_rows times of interface{} assignments. That's a big pressure for GC.

We need to find a way to eliminate this kind of time cost.

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/matrixone/pull/7291#issue-1507246864

Similar issues，maybe it can be deleted after the refactoring is done.

**Comment by aunjgr** [comment]
The refactor has been done.

API change (cooperate with DN) and performance/memory improvement will be tracked in individual issues.
