### ISSUE TITLE
[Bug]: eks test：kill one of logservice pod  dn pod crash reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6816]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):image 0.6.0-15da6a8
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
Kill one of the logservicepods more than ten times within  the bvt test
dn logservice crach  ，and related log already upload this issue
![image](https://user-images.githubusercontent.com/113406637/203058373-bdeb7630-9cb2-4c2c-987d-2da85f974d64.png)
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/113406637/203219765-c68a5f8d-fe79-4c35-a20f-3b6995743b10.png">

**Comment by heni02** [comment]
[cn0log.zip](https://github.com/matrixorigin/matrixone/files/10056720/cn0log.zip)
[cn1log.zip](https://github.com/matrixorigin/matrixone/files/10056724/cn1log.zip)
[dnlog.zip](https://github.com/matrixorigin/matrixone/files/10056725/dnlog.zip)
[log0.zip](https://github.com/matrixorigin/matrixone/files/10056728/log0.zip)

**Comment by LeftHandCold** [comment]
I don't think DN should make any changes

**Comment by LeftHandCold** [comment]
duplicate  #6849
