### ISSUE TITLE
[Bug]: Cannot select or create column named "database"

### ISSUE THREAD

**Issue by TenGui** [matrixorigin/matrixone#6817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): git cloned main branch, last commit Nov 21 19:16:02 2022 +0800 554206cf9b5bf8cf0c64c17694594b4649a2bdd0
- Hardware parameters: Lenovo P53
- OS type: Windows WSL with Ubuntu
- Others:
Query using SQL Shell
matrixone: "./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml"
mo-tester: "./run.sh -p ../matrixone/test/cases -n -g"
```

### Actual Behavior

Whenever attempting select the "database" column in system, after running mo-tester, server returns "ERROR: 1064 (HY000): SQL parser error: ....". The select statement works if other columns are inputted into the select statement.

This also happens when attempting to create a table with a column named database.
1. Selecting column with/without "database" from system -> statement_info
![image](https://user-images.githubusercontent.com/84549255/203177244-ae333aa8-932d-4d9a-a5cc-e85bd891471f.png)
 
2. Creating table with/without "database"
![image](https://user-images.githubusercontent.com/84549255/203177068-7bf10de2-1996-401a-9778-ab7902981bf2.png)

### Expected Behavior

Select column or create table regardless of column name

### Steps to Reproduce

```Markdown
Run mo_tester and try selecting "database" column from "statement_info"
Alternatively, try creating table with column named "database"
```

**Comment by iamlinjunhong** [comment]
'database' is mysql keyword, you can use 'select \`database\` ...'

**Comment by TenGui** [comment]
@iamlinjunhong Thank you, I was unaware of that
