### ISSUE TITLE
[Bug]: using * with select does not work for system (mo-tester results) database

### ISSUE THREAD

**Issue by TenGui** [matrixorigin/matrixone#6818]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): git cloned main branch, last commit Nov 21 19:16:02 2022 +0800 554206cf9b5bf8cf0c64c17694594b4649a2bdd0
- Hardware parameters: Lenovo P53
- OS type: Windows WSL with Ubuntu
- Others:
Query using SQL Shell
matrixone: "./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml"
mo-tester: "./run.sh -p ../matrixone/test/cases -n -g"
```

### Actual Behavior

Whenever trying to select * from any tables in system (produced via mo-tester), returns Invalid Type, and returns "Invalid Type" for all future SQL statements until connection is broken. This seems to only happen when using the "*" variable, specifying columns works.
Select * works in other databases, just not system.

Demonstrating select * and other commands in system database
![image](https://user-images.githubusercontent.com/84549255/203179658-14cc449a-8202-4a9d-a082-fd6a5c3d05cb.png)

### Expected Behavior

Expected select * to work as in other databases

### Steps to Reproduce

```Markdown
Run mo-tester (see environment), query "select * from {any table in system};"
```

**Comment by daviszhen** [comment]
Can you provide the server log?

**Comment by fengttt** [comment]
@TenGui what is the client you are using?

I found that mysql client runs fine.    mycli (python client) is broken.   
```
MySQL dump@localhost:system> select * from log_info limit 10;
'ascii' codec can't decode byte 0xc2 in position 40: ordinal not in range(128)
MySQL dump@localhost:system>
```

**Comment by TenGui** [comment]
@fengttt I am using mySQL shell
https://dev.mysql.com/doc/mysql-shell/8.0/en/

**Comment by TenGui** [comment]
@daviszhen How would I find the server logs? Would they exist inside of the system db as well?
I am using "./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml" to launch my DB

**Comment by TenGui** [comment]
@fengttt Does restarting mean rebuilding and re-running mo-tester? I've closed the mo-service database and relaunched it many times, it seems to have the same behavior regardless of restarts.

**Comment by TenGui** [comment]
I found that this seems to happen only on columns that have the type TEXT, which select * falls under when there is a TEXT column in the database
![image](https://user-images.githubusercontent.com/84549255/203397453-af9061ae-968b-4b03-87db-dce8cf0d651c.png)
I ran select * on a span_info within system database, which has no TEXT fields, and it was successful.

**Comment by daviszhen** [comment]
> @daviszhen How would I find the server logs? Would they exist inside of the system db as well? I am using "./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml" to launch my DB

"./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml"  does not save the log. It prints the log into the console.

**Comment by daviszhen** [comment]
> I found that this seems to happen only on columns that have the type TEXT, which select * falls under when there is a TEXT column in the database ![image](https://user-images.githubusercontent.com/84549255/203397453-af9061ae-968b-4b03-87db-dce8cf0d651c.png) I ran select * on a span_info within system database, which has no TEXT fields, and it was successful.

Oh, It seems the problem of the TEXT type

**Comment by TenGui** [comment]
> > I found that this seems to happen only on columns that have the type TEXT, which select * falls under when there is a TEXT column in the database ![image](https://user-images.githubusercontent.com/84549255/203397453-af9061ae-968b-4b03-87db-dce8cf0d651c.png) I ran select * on a span_info within system database, which has no TEXT fields, and it was successful.
> 
> Oh, It seems the problem of the TEXT type

Is this a problem with my client? It seems like this doesn't happen for everybody.

**Comment by YANGGMM** [comment]
i don't konw how you conect the database @TenGui ,  i have some fix on text type, can you have a test now?

**Comment by TenGui** [comment]
@YANGGMM I pulled, cleaned, re-built the server. It seems to be working now Thanks!
