### ISSUE TITLE
[Feature Request]: Optimize CN cache

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#6825]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

improve the performance

**Comment by nnsgmsone** [comment]
First a catalog cache will be submitted to speed up access to the catalog

**Comment by sukki37** [comment]
Related bug issue：

- [ ] [[User Bug]: MO点查慢，比mysql慢20倍，比mongo慢三个数量级](https://github.com/matrixorigin/MO-Cloud/issues/257)
- [ ] [[Bug]: bad TPS performance in CN-DN deployment running sysbench with auto increment disabled](https://github.com/matrixorigin/matrixone/issues/7092)

**Comment by nnsgmsone** [comment]
The metadata  will next rely on fileservice's cache for acceleration.

**Comment by m-schen** [comment]
由metadata cache issue #8016 来跟踪
