### ISSUE TITLE
[Feature Request]: SLEEP function

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6843]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
mysql> select sleep(15);
+-----------+
| sleep(15) |
+-----------+
|         0 |
+-----------+
1 row in set (15.01 sec)
```

### Describe the feature you'd like

Support sleep function to make a certain time sleeping.

**Comment by goodMan-code** [comment]
this function is available, if not, when?

**Comment by mooleetzi** [comment]
under review

**Comment by mooleetzi** [comment]
pr merged, pls test.

**Comment by Ariznawlll** [comment]
test done, bvt case pr merged
