### ISSUE TITLE
[Bug]: eks test: kill one of logservice  cause  dn connect logservice retry time out

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6849]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):image 0.6.0-15da6a8
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Kill one of the logservicepods more than ten times within the bvt test，and end pod status is :
![image](https://user-images.githubusercontent.com/113406637/203311469-f485e9b9-b018-4589-892d-f54fa9ad7c8e.png)

this issue related to issue #6816 and after analysis, one of the logservices is killed which should not lead to dn retry timeout，dn crash  log is as follows：
panic: internal error: driver info: retry time out

goroutine 72322 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append(0xc00547b840, 0x9591e6?, 0x2540be400)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:69 +0x4f3
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*LogServiceDriver).onAppendQueue
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go:66 +0xf2
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/113406637/203310752-b41eedb5-e386-481d-968b-e168ecb2b7e8.png">

**Comment by heni02** [comment]
[dnlog.zip](https://github.com/matrixorigin/matrixone/files/10067351/dnlog.zip)

**Comment by volgariver6** [comment]
will call a meeting to deal with it.

**Comment by volgariver6** [comment]
Before, I thought a connection pool that supports liveness detection is needed, but now it seems that there is a bug. I will fix the bug first.

**Comment by volgariver6** [comment]
This issue only happens in this case:

1. delete a pod and wait for it to restart
2. delete another pod when the last pod become Running state immediately

Although the first deleted pod is in Running state, the raft state is not ready, which means raft node has not join the cluster yet. So if you delete another pod at this time, the whole log service cannot provide service and causes timeout panic in dn.

**Comment by heni02** [comment]
Communicate with @volgariver6  and retest. At present, it is consistent with the communication results. In the future, plan to  fault injection test ,it is easier to simulate the scene and cover fault scenarios .so this problem closed
