### ISSUE TITLE
[Bug]: The performance of 0.6 is quite slow compared to 0.4 and need to be fix

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#6863]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

ssb slow

### Additional information

Performance tests are here, https://doc.weixin.qq.com/sheet/e3_ALQAjwY-ACU3lDaEHvlS6idBu0kHY?scode=AJsA6gc3AA8D11lqojALQAjwY-ACU&tab=BB08J2

**Comment by aunjgr** [comment]
No progress on this issue yet.

**Comment by fengttt** [comment]
the query is so simple that I don;t believe it is plan issue.    we need to get a profiling first.   @badboynt1

**Comment by badboynt1** [comment]
not working on it

**Comment by badboynt1** [comment]
not working on this

**Comment by badboynt1** [comment]
keep working on this

**Comment by badboynt1** [comment]
keep working on this

**Comment by badboynt1** [comment]
keep working on this

**Comment by badboynt1** [comment]
keep working on this

**Comment by badboynt1** [comment]
keep working on this

**Comment by badboynt1** [comment]
working on cluster by multi column

**Comment by badboynt1** [comment]
working on cluster by multi column

**Comment by badboynt1** [comment]
clusterby multi column supported, waiting for vector refactoring

**Comment by badboynt1** [comment]
waiting for vector refactoring

**Comment by badboynt1** [comment]
waiting for vector refactoring

**Comment by badboynt1** [comment]
waiting for vector refactoring

**Comment by badboynt1** [comment]
waiting for vector refactoring

**Comment by badboynt1** [comment]
waiting for vector refactoring

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/7861 will help this

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/7933 will help this

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/8027
need to fix this issue

**Comment by badboynt1** [comment]
no progress

**Comment by badboynt1** [comment]
default fileservice memcache size is 512mb. change this to 16gb will improve the performance a lot

**Comment by badboynt1** [comment]
waiting for vector refactoring and block io optimization

**Comment by badboynt1** [comment]
0.4   0.8
1g   4.7s  1.6s
10g  8s    12.4s
100g 57s   140s

getting close to 0.4, waiting for vector refactoring and block io optimization

**Comment by badboynt1** [comment]
waiting for vector refactoring and block io optimization

**Comment by badboynt1** [comment]
1g 4.7s 1.4s
10g 8s 10.3s
100g 57s 106s

getting close to 0.4

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/8658
waiting for regression problem to be solved

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/8815
agg pushdown for ssb q1.1,1.2,1.3 done.  improvement is not that big,
the bottleneck is IO performance and memory issue.

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/issues/8658
waiting for regression problem to be solved

**Comment by badboynt1** [comment]
waiting for regression problem to be solved

**Comment by badboynt1** [comment]
waiting for regression problem to be solved

**Comment by badboynt1** [comment]
the performance of 0.8 is better than 0.4 now
