### ISSUE TITLE
[Bug]: mo's scan with predicate is slower than clickhouse

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#6870]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The difference in performance is basically one order of magnitude when there is no filtering, and one to two orders of magnitude when there is filtering.

**Comment by aunjgr** [comment]
No progress on this issue yet.

**Comment by fengttt** [comment]
It may be our zonemap is not efficient.   Maybe rows per block too big.   Maybe data arriving order is bad and we do not generate good order on disk.   Or cache.

But all these, should be very clear from our explain and/or out run stats.

**Comment by badboynt1** [comment]
not working on this

**Comment by badboynt1** [comment]
one reason the predicate has a bad performance is, when column compares constant, we cast both side.
for example, where lo_shipmode != 'air' , 
we got a filter:  Filter Cond: (CAST(lineorder.lo_shipmode AS CHAR) <> CAST('air' AS CHAR))

when the length of constant is shorter than the column, we could cast the constant only.
after test, performance of flat table in ssb improves a lot. 
in my local environment, q4.1 2150ms->1080ms

**Comment by badboynt1** [comment]
for char type column predicate, we can remove the mem copy when compare and improve the performace.
and also, when column width is smaller than valenaInlineSize, that means the data is stored inline and no need to judge in the for loop.

**Comment by badboynt1** [comment]
golang does not inline this function automaticly. after doing this, the performance improves a lot

**Comment by badboynt1** [comment]
fixed
