### ISSUE TITLE
[Feature Request]: Resource GC

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6893]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

	○ Stale persisted object files
	○ Stale in-memory data
		■ Logtail meta
		■ Stale block mvcc data
		■ Staged precommit requests

**Comment by LeftHandCold** [comment]
As I continue to have a high fever, I will review the implementation documents and comments of this feature as soon as I get better next week
