### ISSUE TITLE
[Enhancement]: Better cache in DN

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6895]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Better buffer manager
 Refactor index-related cache implementation
```

**Comment by fengttt** [comment]
dn is 0.7 should optimize for push mode and conflict checking on recent writes.    cn will check conflicts up to a snapshot and dn will check from that snapshot to now.

**Comment by XuPeng-SH** [comment]
dn performance is not on the critical path right now
