### ISSUE TITLE
[Feature Request]: Transaction performance tuning

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#6896]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Tuning mutable and immutable index
2. High-performance cache
3. Parallel committing
4. Incremental recommit dedup
5. Data structure optimization in the critical path

**Comment by fengttt** [comment]
This one is too generic and too broad.   can you split each to a subtask and individual issue?   thank u.
