### ISSUE TITLE
[Bug]: DATA RACE in `Batch`

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#6905]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![图片](https://user-images.githubusercontent.com/28624654/203684579-1a7a6129-3f18-4467-8de0-8f6ae329ba6b.png)

**Comment by m-schen** [comment]
I have fixed it. and plz verify it.
