### ISSUE TITLE
[Enhancement]: log or error record need to be associated with corresponding statement or span

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#6921]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
1. All function needs `context.Context` as 1st in-arg
2. All `moerr.NewXxxYyyy` needs `context.Context` as 1st in-args.
 - then error_info can be associated with trace_id, some case trace_id equals to statement_id.
 - the default log can be trace with trace_id.
```

### Why is this needed ?

We have already recording data `statement_info`, `log_info`, `error_info`, `span_info`. more details in https://github.com/matrixorigin/docs/blob/main/design/observability/how_to_use_trace_log_error.md

Then `log`, `error`, `span` all need to be associated with same `trace_id`, in some case trace_id equals to statement_id.

**Comment by fengttt** [comment]
@xzxiong this is a high priority item.   please work with @zhangxu19830126 to design/impl this in 0.7
