### ISSUE TITLE
[Bug]: MO_JDBC : metaData.getPrecision(), FLOAT's precision is not correct.

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#6928]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit 68177ba7729cba0dafbb7c9796170b9f755c9af4
mysql -h 127.0.0.1 -P 6001 -udump -p111
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml

The problem is : 
The type of FLOAT's precision is 23 bits, but I use this function ResultSetMetaData.getPrecision(),  get return value is 32.
![微信图片_20221125140001](https://user-images.githubusercontent.com/74952516/203911362-800c504d-0a02-4911-841d-6b3c9dc666e6.png)

Return value is : 
![微信图片_20221125140028](https://user-images.githubusercontent.com/74952516/203911385-8d609361-108a-4d55-9375-2ad9cb88ad1d.png)

Execute Steps : 
1. Download this project zip
2. launch it with fitness parameter on u computer.
3. you need not to create database or table, It has been embeded in Project.
[mo-test-jdbc.zip](https://github.com/matrixorigin/matrixone/files/10089041/mo-test-jdbc.zip)

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/231634096-4fcf9a16-bef3-4e7b-bb1f-4fb0ab783c64.png)

test done!
