### ISSUE TITLE
[Bug]: ParseDateCast function poor performance

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#6946]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="993" alt="image" src="https://user-images.githubusercontent.com/32733096/204124695-16d9502f-1a1f-494d-b534-8509d41a8fb7.png">
the ParseDateCast func run poor performance than ParseDate

**Comment by JackTan25** [comment]
Working on Now, the problem is because I use the regexp. I will fix that and try another way

**Comment by tianyahui-python** [comment]
https://github.com/matrixorigin/matrixone/issues/7051

**Comment by tianyahui-python** [comment]
issue can be closed @jianwan0214
