### ISSUE TITLE
[Feature Request]: Mixed mode external table reading

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6947]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

external table should be able to read different formats.   esp, we want external table to read both csv and our own native format.  for our native format, external table should apply zonemap filter.

### Describe the feature you'd like

errorlog/infolog performance.

**Comment by daviszhen** [comment]
duplicate with  #6947 ?

**Comment by heni02** [comment]
test done
