### ISSUE TITLE
[Feature Request]: log/trace merge into our native format

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6948]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
when log is written, lets write as csv file  -- actually how about a config, 
we may want to directly write our own format anyway.   
when merge, we should merge into our own storage format.   

directly write fileservice in our own format has been supported in cn.
```

### Describe the feature you'd like

much better perf and storage compression

**Comment by xzxiong** [comment]
trace/log has support write as tae files.
