### ISSUE TITLE
[Feature Request]: CN Detect conflicts up to its own snapshot

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6949]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
CN should detect conflicts of its own write against its own snapshot.   abort if there are conflicts.

Note that CN must detects if it writes S3 blocks directly (and mix s3/records/deletes)
```

### Describe the feature you'd like

cn resolve most conflicts up to its snapshot.   leaving dn to resolve only recent writes.

**Comment by reusee** [comment]
I'll discuss this with Mochen before working on.

**Comment by reusee** [comment]
After a discussion with Mochen, we believe more time is required to polish the workflow between multiple CNs on conflict detection. We may delay this to 0.8.

**Comment by domingozhang** [comment]
wait for yuanning

**Comment by w-zr** [comment]
This issue is now completed. @fengttt @nnsgmsone @ouyuanning
