### ISSUE TITLE
[Enhancement]: Add partition id to table id

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6951]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Add a partition id to table id.   I think 2 bytes is enough, maybe 1 byte.

CN/DN communication must understand this.  If a table is not partitioned, let's use -1.

Push/pull logtail, unit is table partition.   CN may register interest only in one or few partitions.
```

### Why is this needed ?

Limit CN data/memory size.

**Comment by reusee** [comment]
In progress

**Comment by reusee** [comment]
We're already pulling data from DN by shard/partition. I guess we don't need this?

**Comment by reusee** [comment]
We're already managing caches by partitions. This issue is done.

**Comment by daviszhen** [comment]
@reusee has finished something. What do I need to do in this issue?
