### ISSUE TITLE
[Enhancement]: Read from peer cache

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6953]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Assume #6951

When we read from either mem table or S3, if we read from a partition not managed by a CN, it should try to look from its peers that owns that partition.
```

### Why is this needed ?

Remote read from another CN is much faster than read S3.   Better hit ratio as well.

**Comment by reusee** [comment]
The early draft of the file service has a network wrapper that exposes another file service instance over the network. I can add that wrapper back to the package.

**Comment by arjunsk** [comment]
As proposed by @fengttt , we will be creating a central file_service, which acts as a giant s3 cache, instead of fetching it from peers. It helps in avoiding complexities associated with peer discovery, partitioning, routing, etc.

**Comment by fengttt** [comment]
@volgariver6 this is done?

**Comment by volgariver6** [comment]
yes, it is done.

**Comment by aressu1985** [comment]
test done
