### ISSUE TITLE
[Enhancement]: Plan cache

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6957]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
For prepared statement the plan should be cached/reused.
Unless there is a ddl change (or role/permission change).

For same query, esp those simple ones with ? param binding, if 
query text is exactly the same, only param diff, plan should
also be cached.
```

### Why is this needed ?

performance

**Comment by taofengliu** [comment]
# Implementation description
Plan cache is a map from sql to plan and ast. Use LRU to manage cached plans. 
Only cache DQL\DML stmts. Other stmts except SetVar stmt will delete all cached plans.
To avoid deepcopy, some operations that change the plan during compile and execution are moved to buildPlan.
Add a new field in Const to solve the RealTimeRelated function problem and avoid deleting all cached plans when execute setVar statement. 
This pr also fix some unrelated bugs, see https://github.com/matrixorigin/matrixone/pull/7294 for details.

# Performance compare

test tables:
```sql
create table test1 (id int, c11 int, c12 char(5));
create table test2 (id int, c21 int, c22 char(5));
create table test3 (id int, c31 int, c32 char(5));
```
test data:
(0~4999,100,"abcde")
5000 lines data for every table.

test sql:
```sql
select test1.id,test2.id,test3.id,c12,c22,c32,substring(substring(c22,1,3),1,3),c32,c11+c11-c31 from test1,test2,test3 where test1.id = test2.id and test2.id = test3.id and test1.id > 1000 order by test1.id limit 100;
```
how I tested:
execute the test sql for 5000 times.

average execution time：
48681ms with plan cache.
49776ms without plan cache.
