### ISSUE TITLE
[Feature Request]: Support a non-primary-key table with sorting key

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6959]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Create table table_name(column list) order by column_name;

When create a table without a primary key, then user can use order by clause in DDL as sorting key. After creating this table, data can be sorted by table automatically.
A table with primary key will not support sorting key clause.

In 0.8.0, the scope is clustered by an expression.

**Comment by domingozhang** [comment]
@fengttt please review this feature. thanks

**Comment by fengttt** [comment]
1. prefer cluster by
2. can we just reuse secondary index?    that is, if a table does not have primary key index, when you create 2nd index, it is a hint that the table should be clustered by the 2nd index.    we may create real data structure for 2nd index, so this may not be a good idea.

**Comment by aptend** [comment]
i've finished my part, @badboynt1 will do more work on this

**Comment by domingozhang** [comment]
in 0.8.0, add  cluster by expression
