### ISSUE TITLE
[Bug]: mo-server panic by concurrent map read and write

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#6965]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/2995754/204221613-e08e5e65-936f-4719-968c-3eb250a32d9d.png">

**Comment by nnsgmsone** [comment]
fixed by #6972
