### ISSUE TITLE
[Enhancement]: Unique key can define behind define of column

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#6967]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
create table t1 (a int unique key);
```

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will solve it after unique index is complete

**Comment by bbbearxyz** [comment]
The code is finish and wait the pr review.
