### ISSUE TITLE
[Feature Request]: Distributed deployment and tracing

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#6970]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Get these targets for distributed deployment in 0.7 release.
- Precheck the required software version for distributed MO cluster.
- One click deployment for MO cluster, including k8s, minIO and MO cluster.
- Use CLI can start, stop and get status of MO cluster
- Deploy on user's k8s cluster with one click (P1)

2. Get these targets for distributed MO tracing
- Get last query id with related function last_uuid
- Get the tracing information from query id, including log records, calling chain and time from CN to DN and LS and related error info.

**Comment by fengttt** [comment]
mostly deployment issue.   I will file a last_uuid issue.
