### ISSUE TITLE
[Bug]: current_timestamp returns different value in a sql

### ISSUE THREAD

**Issue by mooleetzi** [matrixorigin/matrixone#6977]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
select now(6),now(6);
+----------------------------+----------------------------+
| now(6)                     | now(6)                     |
+----------------------------+----------------------------+
| 2022-11-28 17:00:09.157484 | 2022-11-28 17:00:09.157490 |
+----------------------------+----------------------------+
1 row in set (0.00 sec)

```

### Expected Behavior

should be same

**Comment by fengttt** [comment]
Hmm, this may or may not be an issue.   the more important problem is that 
```
select current_timestamp from t
```
will return same value, which we do.

For the situation mentioned in this issue, I guess you can interprete current timestamp is different ways.    
does two current timetamp in one query means the same thing?   I am not sure.   It is a volatile functon
called twice.

**Comment by mooleetzi** [comment]
I tried same sql in MySQL, it gives same timestamp.

**Comment by mooleetzi** [comment]
And case
```
select current_timestamp from t
```
returns same ts.
