### ISSUE TITLE
[Feature Request]: last_uuid function

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6984]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
last_uuid() should return the latest uuid of the statement IN THIS SESSION.
```

### Describe the feature you'd like

return the uuid of last statement in current session.

**Comment by daviszhen** [comment]
It may be duplicate with #6744

**Comment by daviszhen** [comment]
It is duplicate with #6744 and can be closed.
