### ISSUE TITLE
[Feature Request]: debug scripts for log and trace

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#6994]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Suppose we have log/trace etc stored in S3.   For some reason, the mo database 
cannot restart, or, the data/node has been deleted/repurposed etc.

We want a script, in a new cluster, that create a database, then create a bunch of 
external tables and we can analyze log/trance of another database.


create database dbg;

create external table log_info ...;
create external table error_info ...;

select * from log_info where ...
```

### Describe the feature you'd like

let people query others log/trace for debugging/analysis

**Comment by xzxiong** [comment]
#7974 add a tool `mo-tool` to handle debug script logic, as #7024 review suggestions. But in 0.8 milestone, there is a new tool `mo-ctl`.
Should i migrate it to 0.8 `mo-ctl` ? @fengttt

**Comment by xzxiong** [comment]
in https://github.com/matrixorigin/MO-Cloud/issues/389 tool `mo-ctl` is proper way to give user to call. wait and adjust the tool implements

**Comment by xzxiong** [comment]
wait pr https://github.com/matrixone-cloud/mo-ctl/pull/2

**Comment by xzxiong** [comment]
feature already merged in mo-ctl tool, https://github.com/matrixone-cloud/mo-ctl/pull/3

**Comment by lacrimosaprinz** [comment]
@fengttt @dengn 
Need more operation details and overview, easy to write documentation;
Also need to explain clearly what the behavior of this function is? What is the user experience? How to operate？

**Comment by dengn** [comment]
@aronchanisme please update how to use this in the mo_ctl doc.
