### ISSUE TITLE
[Proposal]: A solution that minimizes modifications to existing code about TempEngine, one Client and two TxnOperators

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#7000]
### Describe your problem

# Abstract
To support TempTable, A new, session-level MemoryEngine will be created to act as a temporary engine when needed. However, things are getting slightly more subtle, as txn will now cross engines, The previous approach use an EntireClient to wrap the two engines' Clients together, EntireClient will create the txnOperators needed by both engines. Notice TempClient and tempOperator both session-level, They are all nil before creating temporary tables.

However, This implementation is not allowed, **and some of the existing schemes turned out to be infeasible in practice.**

# Previous implement

```go
// EntireClient is a wrapper to support txn for temp engine.
type EntireClient struct {
	txnClient  TxnClient
	TempClient TxnClient
}

// New returns a TxnOperator to handle read and write operation for a
// transaction.
func (ec *EntireClient) New(options ...TxnOption) (TxnOperator, error) {
	var txnOperator TxnOperator
	var tempOperator TxnOperator
	var err error
	if txnOperator, err = ec.txnClient.New(options...); err != nil {
		return nil, err
	}
	if ec.TempClient != nil {
		if tempOperator, err = ec.TempClient.New(options...); err != nil {
			return nil, err
		}
	}
        // wrapper
	return &EntireTxnOperator{
		txnOperator:  txnOperator,
		tempOperator: tempOperator,
	}, nil
}
```

# Proposal
If we don't allow certain clients to change but still need two Txnoperators, consider creating an existing txnClient and then manually constructing it as EntireOperator

```go
// TxnClientNew creates a new txn
func (th *TxnHandler) TxnClientNew() error {
	var err error
	th.mu.Lock()
	defer th.mu.Unlock()
	if th.txnClient == nil {
		panic("must set txn client")
	}
	th.txn, err = th.txnClient.New()

        // Create EntireTxnOperator manually, make th.txn become EntireOperator
        do sth.

	if err != nil {
		return err
	}
	if th.txn == nil {
		return moerr.NewInternalError("TxnClientNew: txnClient new a null txn")
	}
	return err
}
```

**Comment by jensenojs** [comment]
There is no essential difference between the two implementations.

The negation of the existing scheme actually needs to be discussed in meetings, and I want to emphasize that since both Client and Operator for temporary tables are session level and nil most of the time, I don't think it has any particular impression.

**Comment by JackTan25** [comment]
We use Memory Engine to design TempTable. This has spent too much time up to now. The reason is about transaction. If we go ahead with transaction framework, we will make that design very complicated. mochen think we should make it simple enough and correctness，that's the key, so we give this simple proposal to complete this pr.

**Comment by nnsgmsone** [comment]
After I talked to them, I think the current implementation is too complicated. I feel there is no need to continue on this complicated path

**Comment by jensenojs** [comment]
No need for this proposal, we have successfully used the existing txnClient and txnOperator to accomplish everything, as for the cross-engine transaction commits and then ask the relevant engineers to confirm the details can be done.
