### ISSUE TITLE
[Bug]: show create unique index table doesn't right

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#7002]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 (a int, b int, unique key (a));
show create table t1;

+-------+------------------------------------------------------------------+
| Table | Create Table                                                     |
+-------+------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
`a` INT DEFAULT NULL,
`b` INT DEFAULT NULL
) |
+-------+------------------------------------------------------------------+

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will solve it after unique index is complete

**Comment by bbbearxyz** [comment]
will solve it after unique index pr is merge

**Comment by bbbearxyz** [comment]
will solve it after unique index pr is merge

**Comment by bbbearxyz** [comment]
the pr is ok and wait to merge

**Comment by bbbearxyz** [comment]
the issue is fixed, so please close.
