### ISSUE TITLE
[Bug]: docker container mount data error

### ISSUE THREAD

**Issue by wanglei4687** [matrixorigin/matrixone#7004]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type: MacOS
- Others:
```

### Actual Behavior

2022/11/29 12:10:15.014090 +0000 INFO logutil/internal.go:36 MO logger init, level=info, log file=
2022/11/29 12:10:15.078864 +0000 INFO trace/trace.go:124 init GlobalBatchProcessor
2022/11/29 12:10:15.081918 +0000 INFO export/batch_processor.go:216 MOCollector Start
2022/11/29 12:10:15.082262 +0000 INFO trace/trace.go:132 init trace span processor
2022/11/29 12:10:15.082732 +0000 INFO trace/trace.go:94 trace with LongQueryTime: 0s
2022/11/29 12:10:15.083554 +0000 INFO metric/metric.go:129 metric with ExportInterval: 15s
2022/11/29 12:10:15.083747 +0000 INFO mo-service/config.go:195 hakeeper client cfg: { [127.0.0.1:32001] 0}
2022/11/29 12:10:15.083877 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2221 go version: go1.19.3, linux/amd64
2022/11/29 12:10:15.083923 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2223 dragonboat version: 4.0.0 (Dev)
2022/11/29 12:10:15.084166 +0000 WARN config config/config.go:534 mutual TLS disabled, communication is insecure
2022/11/29 12:10:15.084386 +0000 INFO config config/config.go:656 using default EngineConfig
2022/11/29 12:10:15.084732 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:349 DeploymentID set to 1
2022/11/29 12:10:15.159164 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1759 logdb memory limit: 48 MBytes
2022/11/29 12:10:15.164619 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:358 NodeHost ID: 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf
2022/11/29 12:10:15.164686 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1806 AddressByNodeHostID: true, use gossip based node registry
2022/11/29 12:10:15.165053 +0000 INFO registry registry/gossip.go:297 gossip probe interval set to 5s
2022/11/29 12:10:15.165644 +0000 INFO registry registry/gossip.go:307 gossip bind address 127.0.0.1 port 32002
2022/11/29 12:10:15.165917 +0000 INFO registry registry/gossip.go:315 gossip advertise address 127.0.0.1 port 32002
2022/11/29 12:10:15.168448 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:366 filesystem error injection mode enabled: false
2022/11/29 12:10:15.170277 +0000 INFO transport transport/transport.go:238 transport type: go-tcp-transport
2022/11/29 12:10:15.170693 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2010 transport type: go-tcp-transport
2022/11/29 12:10:15.170941 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2011 logdb type: Tan
2022/11/29 12:10:15.170987 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2012 nodehost address: 127.0.0.1:32000
2022/11/29 12:10:15.171011 +0000 INFO log-service logservice/store.go:151 HAKeeper Timeout Configs {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "LogStoreTimeout": 300000000000, "DNStoreTimeout": 10000000000, "CNStoreTimeout": 30000000000}
2022/11/29 12:10:15.172404 +0000 INFO log-service logservice/store.go:171 logservice truncation worker started {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2022/11/29 12:10:15.174513 +0000 INFO log-service logservice/service.go:160 logservice heartbeat worker started {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2022/11/29 12:10:15.174902 +0000 INFO mo-service/main.go:224 bootstrapping hakeeper...
2022/11/29 12:10:15.182085 +0000 INFO hakeeper-client-backend morpc/backend.go:649 start connect to remote {"remote": "127.0.0.1:32001"}
2022/11/29 12:10:15.182454 +0000 INFO hakeeper-client-backend morpc/backend.go:653 connect to remote succeed {"remote": "127.0.0.1:32001"}
2022/11/29 12:10:15.182600 +0000 INFO hakeeper-client-backend morpc/backend.go:513 read loop started {"remote": "127.0.0.1:32001"}
2022/11/29 12:10:15.182851 +0000 INFO rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:328 gc inactive backends task started
2022/11/29 12:10:15.182860 +0000 INFO hakeeper-client-backend morpc/backend.go:358 write loop started {"remote": "127.0.0.1:32001"}
2022/11/29 12:10:15.183905 +0000 INFO logservice/hakeeper_client.go:381 isHAKeeper: false, err: <nil>
2022/11/29 12:10:15.184411 +0000 ERROR hakeeper-client-backend morpc/backend.go:530 read from backend failed {"remote": "127.0.0.1:32001", "error": "read tcp4 127.0.0.1:40762->127.0.0.1:32001: use of closed network connection"}
2022/11/29 12:10:15.184739 +0000 ERROR hakeeper-client-backend morpc/backend.go:535 read loop stopped {"remote": "127.0.0.1:32001"}
2022/11/29 12:10:15.184475 +0000 INFO hakeeper-client-backend morpc/backend.go:361 write loop stopped {"remote": "127.0.0.1:32001"}
2022/11/29 12:10:15.191721 +0000 ERROR rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:334 gc inactive backends task stopped
2022/11/29 12:10:15.197492 +0000 ERROR logservice/hakeeper_client.go:393 error: cannot locate ha keeper
github.com/matrixorigin/matrixone/pkg/logservice.connectToHAKeeper
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:393
github.com/matrixorigin/matrixone/pkg/logservice.newHAKeeperClient
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:313
github.com/matrixorigin/matrixone/pkg/logservice.newManagedHAKeeperClient
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:110
github.com/matrixorigin/matrixone/pkg/logservice.NewCNHAKeeperClient
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:83
main.waitHAKeeperReady
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:136
main.waitClusterCondition
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:197
main.startDNService
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:185
main.startService
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:133
main.startDNServiceCluster
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:89
main.startCluster
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:48
main.main
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:250
2022/11/29 12:10:15.197781 +0000 INFO mo-service/launch.go:139 hakeeper not ready, retry
2022/11/29 12:10:15.206045 +0000 INFO tan tan/open.go:55 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/aad6294e7cb6/00000000000000000001/tandb/node-0-131072 creating a new tan db
2022/11/29 12:10:15.220933 +0000 INFO tan tan/open.go:76 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/aad6294e7cb6/00000000000000000001/tandb/node-0-131072 on disk files [CURRENT MANIFEST-000001]
2022/11/29 12:10:15.221151 +0000 INFO tan tan/open.go:132 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/aad6294e7cb6/00000000000000000001/tandb/node-0-131072 logFiles to rebuild: map[]
2022/11/29 12:10:15.221311 +0000 INFO tan tan/open.go:133 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/aad6294e7cb6/00000000000000000001/tandb/node-0-131072 indexFiles: []
2022/11/29 12:10:15.224482 +0000 PANIC dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2235 operation not supported
github.com/lni/dragonboat/v4.panicNow
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2235
github.com/lni/dragonboat/v4.(*NodeHost).startShard
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1654
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:508
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:215
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_bootstrap.go:35
main.startLogService.func1
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:225
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:258
panic: operation not supported

goroutine 208 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0006c8000, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc000638218, 0x4, {0x2632a25?, 0xc004796160?}, {0xc00273d020?, 0xc00027cb90?, 0xc0047c9108?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.21.0/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.21.0/sugar.go:159
github.com/matrixorigin/matrixone/pkg/logutil.DragonboatAdaptLogger.Panicf(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/logutil/dragonboat.go:65
github.com/lni/dragonboat/v4/logger.(*dragonboatLogger).Panicf(0xc000677f40?, {0x2632a25, 0x3}, {0xc00273d020, 0x1, 0x1})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/logger/logger.go:132 +0x57
github.com/lni/dragonboat/v4.panicNow(...)
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2235
github.com/lni/dragonboat/v4.(*NodeHost).startShard(0xc004794380, 0xc0006a81b0, 0x0, 0x41ee3f?, {0x20000, 0x0, 0x1, 0x1, 0xa, 0x1, ...}, ...)
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1654 +0xe53
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica(0x0?, 0xc0006c8000?, 0x24?, 0x2b?, {0x20000, 0x0, 0x1, 0x1, 0xa, 0x1, ...})
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:508 +0xe5
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica(0xc0001d4c80, 0x20000, 0xd0?, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:215 +0xc7
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper(_, {_, _}, {{0x0, 0x0}, 0x1, {0xc00063e870, 0x24}, 0x0, {0x0, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_bootstrap.go:35 +0x92
main.startLogService.func1({0x2a1caf0, 0xc000285940})
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:225 +0x11c
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:258 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:253 +0x12c

### Steps to Reproduce

```Markdown
docker run -it -p 6001:6001 -v $(pwd)/mo-data:/mo-data matrixorigin/matrixone:0.6.0
```

**Comment by dengn** [comment]
Retested again with a local empty folder /Users/nandeng/Test/0.6 in local mac computer. 

```
docker run -it -p 6001:6001 -v /Users/nandeng/Test/0.6:/mo-data matrixorigin/matrixone:0.6.0
```
 I've still got the same error:
nandeng-macbookpro:0.6 nandeng$ docker run -it -p 6001:6001 -v /Users/nandeng/Test/0.6:/mo-data matrixorigin/matrixone:0.6.0
Unable to find image 'matrixorigin/matrixone:0.6.0' locally
0.6.0: Pulling from matrixorigin/matrixone
0509fae36eb0: Pull complete 
3cb5cabedc85: Pull complete 
1dee533a1e02: Pull complete 
b7c3e0dbced0: Pull complete 
Digest: sha256:f8a3f44e7d7526d815c7b5d02eddac750cd7b54a7a7fbcf970ee346ff01e07b2
Status: Downloaded newer image for matrixorigin/matrixone:0.6.0
2022/12/01 07:31:28.971202 +0000 INFO logutil/internal.go:36 MO logger init, level=info, log file=
2022/12/01 07:31:29.101794 +0000 INFO trace/trace.go:124 init GlobalBatchProcessor
2022/12/01 07:31:29.103407 +0000 INFO export/batch_processor.go:216 MOCollector Start
2022/12/01 07:31:29.103540 +0000 INFO trace/trace.go:132 init trace span processor
2022/12/01 07:31:29.103586 +0000 INFO trace/trace.go:94 trace with LongQueryTime: 0s
2022/12/01 07:31:29.103798 +0000 INFO metric/metric.go:129 metric with ExportInterval: 15s
2022/12/01 07:31:29.103816 +0000 INFO mo-service/config.go:195 hakeeper client cfg: { [127.0.0.1:32001] 0}
2022/12/01 07:31:29.104120 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2221 go version: go1.19.3, linux/arm64
2022/12/01 07:31:29.104192 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2223 dragonboat version: 4.0.0 (Dev)
2022/12/01 07:31:29.104210 +0000 WARN config config/config.go:534 mutual TLS disabled, communication is insecure
2022/12/01 07:31:29.104292 +0000 INFO config config/config.go:656 using default EngineConfig
2022/12/01 07:31:29.104321 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:349 DeploymentID set to 1
2022/12/01 07:31:29.303420 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1759 logdb memory limit: 48 MBytes
2022/12/01 07:31:29.315910 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:358 NodeHost ID: 7c4dccb4-4d3c-41f8-b482-5251dc7a41bf
2022/12/01 07:31:29.316001 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1806 AddressByNodeHostID: true, use gossip based node registry
2022/12/01 07:31:29.316144 +0000 INFO registry registry/gossip.go:297 gossip probe interval set to 5s
2022/12/01 07:31:29.316195 +0000 INFO registry registry/gossip.go:307 gossip bind address 127.0.0.1 port 32002
2022/12/01 07:31:29.316209 +0000 INFO registry registry/gossip.go:315 gossip advertise address 127.0.0.1 port 32002
2022/12/01 07:31:29.318505 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:366 filesystem error injection mode enabled: false
2022/12/01 07:31:29.318754 +0000 INFO transport transport/transport.go:238 transport type: go-tcp-transport
2022/12/01 07:31:29.318812 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2010 transport type: go-tcp-transport
2022/12/01 07:31:29.318823 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2011 logdb type: Tan
2022/12/01 07:31:29.318828 +0000 INFO dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2012 nodehost address: 127.0.0.1:32000
2022/12/01 07:31:29.318832 +0000 INFO log-service logservice/store.go:151 HAKeeper Timeout Configs {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "LogStoreTimeout": 300000000000, "DNStoreTimeout": 10000000000, "CNStoreTimeout": 30000000000}
2022/12/01 07:31:29.319213 +0000 INFO log-service logservice/store.go:171 logservice truncation worker started {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2022/12/01 07:31:29.320394 +0000 INFO log-service logservice/service.go:160 logservice heartbeat worker started {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2022/12/01 07:31:29.320540 +0000 INFO mo-service/main.go:224 bootstrapping hakeeper...
2022/12/01 07:31:29.332019 +0000 INFO hakeeper-client-backend morpc/backend.go:649 start connect to remote {"remote": "127.0.0.1:32001"}
2022/12/01 07:31:29.344632 +0000 INFO hakeeper-client-backend morpc/backend.go:653 connect to remote succeed {"remote": "127.0.0.1:32001"}
2022/12/01 07:31:29.344961 +0000 INFO rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:328 gc inactive backends task started
2022/12/01 07:31:29.344999 +0000 INFO hakeeper-client-backend morpc/backend.go:358 write loop started {"remote": "127.0.0.1:32001"}
2022/12/01 07:31:29.345435 +0000 INFO hakeeper-client-backend morpc/backend.go:513 read loop started {"remote": "127.0.0.1:32001"}
2022/12/01 07:31:29.345470 +0000 INFO logservice/hakeeper_client.go:381 isHAKeeper: false, err: <nil>
2022/12/01 07:31:29.356460 +0000 ERROR hakeeper-client-backend morpc/backend.go:526 read loop stopped {"remote": "127.0.0.1:32001"}
2022/12/01 07:31:29.356804 +0000 INFO hakeeper-client-backend morpc/backend.go:361 write loop stopped {"remote": "127.0.0.1:32001"}
2022/12/01 07:31:29.364597 +0000 ERROR rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:334 gc inactive backends task stopped
2022/12/01 07:31:29.370661 +0000 ERROR logservice/hakeeper_client.go:393 error: cannot locate ha keeper
github.com/matrixorigin/matrixone/pkg/logservice.connectToHAKeeper
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:393
github.com/matrixorigin/matrixone/pkg/logservice.newHAKeeperClient
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:313
github.com/matrixorigin/matrixone/pkg/logservice.newManagedHAKeeperClient
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:110
github.com/matrixorigin/matrixone/pkg/logservice.NewCNHAKeeperClient
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/hakeeper_client.go:83
main.waitHAKeeperReady
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:136
main.waitClusterCondition
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:197
main.startDNService
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:185
main.startService
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:133
main.startDNServiceCluster
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:89
main.startCluster
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/launch.go:48
main.main
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:250
2022/12/01 07:31:29.373605 +0000 INFO mo-service/launch.go:139 hakeeper not ready, retry
2022/12/01 07:31:29.465529 +0000 INFO tan tan/open.go:55 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/780d04270cdb/00000000000000000001/tandb/node-0-131072 creating a new tan db
2022/12/01 07:31:29.492644 +0000 INFO tan tan/open.go:76 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/780d04270cdb/00000000000000000001/tandb/node-0-131072 on disk files [CURRENT MANIFEST-000001]
2022/12/01 07:31:29.492705 +0000 INFO tan tan/open.go:132 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/780d04270cdb/00000000000000000001/tandb/node-0-131072 logFiles to rebuild: map[]
2022/12/01 07:31:29.492722 +0000 INFO tan tan/open.go:133 /mo-data/logservice-data/7c4dccb4-4d3c-41f8-b482-5251dc7a41bf/780d04270cdb/00000000000000000001/tandb/node-0-131072 indexFiles: []
2022/12/01 07:31:29.498672 +0000 PANIC dragonboat v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2235 operation not supported
github.com/lni/dragonboat/v4.panicNow
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2235
github.com/lni/dragonboat/v4.(*NodeHost).startShard
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1654
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:508
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:215
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_bootstrap.go:35
main.startLogService.func1
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:225
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:258
panic: operation not supported

goroutine 208 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x400314a000, {0x0, 0x0, 0x0})
        /go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x31c
go.uber.org/zap.(*SugaredLogger).log(0x40002b0230, 0x4, {0x23a09a5?, 0x0?}, {0x40031386f0?, 0x279f628?, 0x40033761e0?}, {0x0, 0x0, 0x0})
        /go/pkg/mod/go.uber.org/zap@v1.21.0/sugar.go:227 +0xe8
go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /go/pkg/mod/go.uber.org/zap@v1.21.0/sugar.go:159
github.com/matrixorigin/matrixone/pkg/logutil.DragonboatAdaptLogger.Panicf(...)
        /go/src/github.com/matrixorigin/matrixone/pkg/logutil/dragonboat.go:65
github.com/lni/dragonboat/v4/logger.(*dragonboatLogger).Panicf(0x40002b3b30?, {0x23a09a5, 0x3}, {0x40031386f0, 0x1, 0x1})
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/logger/logger.go:132 +0x54
github.com/lni/dragonboat/v4.panicNow(...)
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:2235
github.com/lni/dragonboat/v4.(*NodeHost).startShard(0x4003378380, 0x400004fad0, 0x0, 0x40005a5958?, {0x20000, 0x0, 0x1, 0x1, 0xa, 0x1, ...}, ...)
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:1654 +0xb04
github.com/lni/dragonboat/v4.(*NodeHost).StartReplica(0x0?, 0x0?, 0x24?, 0x2b?, {0x20000, 0x0, 0x1, 0x1, 0xa, 0x1, ...})
        /go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20221116064434-34611fc96385/nodehost.go:508 +0xa0
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica(0x400318e780, 0x20000, 0x0?, 0x19?)
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:215 +0x90
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).BootstrapHAKeeper(_, {_, _}, {{0x0, 0x0}, 0x1, {0x40002c6870, 0x24}, 0x0, {0x0, ...}, ...})
        /go/src/github.com/matrixorigin/matrixone/pkg/logservice/service_bootstrap.go:35 +0x64
main.startLogService.func1({0x2777cf0, 0x4000050a00})
        /go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:225 +0xc0
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:258 +0x6c
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
        /go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:253 +0x160

**Comment by dengn** [comment]
> On Linux system, just add --privileged to make it work.
> 
> On Mac system, SIP need to be disabled to run docker container with --privileged. How to disable it: [Disabling and Enabling System Integrity Protection](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)

Can we have some simpler way to make mac work? this SIP disable is a big obstacle for user experience.

**Comment by dengn** [comment]
Linux works fine: 
sudo docker run -it --privileged -p 6001:6001 -v /mnt/vdb/dengnan/matrixone_cn/matrixone_0.6_20221124/docker_data:/mo-data matrixorigin/matrixone:0.6.0

**Comment by lacrimosaprinz** [comment]
linux：
Using docker can not mount the config file and mo-data file at the same time:
For more details ,see ：https://doc.weixin.qq.com/doc/w3_AVcAqAZJACcvfdiU10wRqKI1xN5n1?scode=AJsA6gc3AA8kU11ikmAVcAqAZJACc

**Comment by volgariver6** [comment]
> linux： Using docker can not mount the config file and mo-data file at the same time: For more details ,see ：https://doc.weixin.qq.com/doc/w3_AVcAqAZJACcvfdiU10wRqKI1xN5n1?scode=AJsA6gc3AA8kU11ikmAVcAqAZJACc

You have to prepare config files in etc directory and mount it onto the container.
