### ISSUE TITLE
[Bug]: doesn't drop unique index table

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#7010]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1225" alt="截屏2022-11-30 上午11 52 32" src="https://user-images.githubusercontent.com/49111204/204703635-bb045126-50c2-49f5-852a-3be808d31781.png">

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
The code is finish and wait the pr review.

**Comment by heni02** [comment]
working on tomorrow

**Comment by heni02** [comment]
confirm,closed
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210353299-7f4b74e6-9fd2-4744-b6fe-934f6f1aa662.png)

**Comment by heni02** [comment]
@bbbearxyz plz remove bvt tag

**Comment by heni02** [comment]
@aressu1985 plz closed this issue
