### ISSUE TITLE
[Bug]: there is no data in unique index table

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#7011]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1 (a int, b int, unique key(a));
insert into t1 values (1, 2), (2, 3);

mysql> select * from `__mo_cpkey_unique_0__999ed4e0-7062-11ed-9937-acde48001122`;
Empty set (0.00 sec)

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
most of the code is complete, now do some test and fix bug.

**Comment by bbbearxyz** [comment]
The code is finish and wait the pr review.

**Comment by heni02** [comment]
wait for pr merged

**Comment by heni02** [comment]
working on tomorrow

**Comment by heni02** [comment]
confirm,closed
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210352306-17d49ef1-a59a-489e-9992-17523e43a90b.png)

**Comment by heni02** [comment]
@bbbearxyz plz remove bvt tag

**Comment by heni02** [comment]
@aressu1985 plz closed this issue
