### ISSUE TITLE
[Feature Request]: need a doc for how to check code coverage in the local machine

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#7015]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

I need a doc for tell me how to run the ut/bvt in the local machine, so I can look my code coverage.

**Comment by sukki37** [comment]
https://doc.weixin.qq.com/doc/w3_AEkAzgYFABUUuvdrQu3TOm2cv3fAP?scode=AJsA6gc3AA8g7PKazIAEkAzgYFABU @bbbearxyz

**Comment by bbbearxyz** [comment]
> https://doc.weixin.qq.com/doc/w3_AEkAzgYFABUUuvdrQu3TOm2cv3fAP?scode=AJsA6gc3AA8g7PKazIAEkAzgYFABU @bbbearxyz

thank you
