### ISSUE TITLE
[Feature Request]: Handle  Kill Signals in mo-service

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7017]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Handle kill signals in the mo-service process, like `SIGINT`, `SIGTERM` and so on

**Comment by zhangxu19830126** [comment]
@sukki37 use mo-service to build a service test. And run all test case, and stopping the mo-service process with the sigint signal will Panic and prevent the coverage file from being generated.

```bash
 go test -c -tags service_test -cover -covermode=count -coverpkg=./pkg/... ./cmd/mo-service/ -o service_test

ctrl+c to stop
```

**Comment by zhangxu19830126** [comment]
But there is a panic:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/2995754/204955535-bf3014f8-b098-42cd-b407-891485f5e880.png">

**Comment by xzxiong** [comment]
@sukki37 panic issue, while mo receive `SIGINT`, or `SIGTERM` signal, has been fixed. pls check.

**Comment by sukki37** [comment]
checked
