### ISSUE TITLE
[Bug]: set variables=default doesn't work in 0.6.0 branch

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7022]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In this commit:
commit e4b5cf17b9407bc0d1c4542a1467c7322949a139 (HEAD -> 0.6.0, tag: v0.6.0, origin/0.6.0)
Author: maomao <77312370+sukki37@users.noreply.github.com>
Date:   Mon Nov 28 17:53:16 2022 +0800

mysql> set wait_timeout=3600;
Query OK, 0 rows affected (0.00 sec)

mysql> set wait_timeout=default;
ERROR 20102 (HY000): const expression &{true} is not yet implemented

However in this commit, it works.
commit 1940510ea1f6ba4b4d8295613da04b091a10dee9 (HEAD -> main, origin/main, origin/HEAD)
Author: qingxinhome <70939751+qingxinhome@users.noreply.github.com>
Date:   Mon Nov 21 17:20:57 2022 +0800

mysql> set wait_timeout=3600;
Query OK, 0 rows affected (0.00 sec)

mysql> set wait_timeout=default;
Query OK, 0 rows affected (0.00 sec)

**Comment by YANGGMM** [comment]
i have fixed it on main branch

**Comment by domingozhang** [comment]
fixed
