### ISSUE TITLE
[Bug]: dailybuild eks bvt test  error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7032]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93): 43e20b1b61956d1499308be08705b482ac147c74
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

dailybuild eks bvt case config ：

apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: daily-mo-dis
  namespace: mo-dailybuild
spec:
  nodeSelector:
    # 使用专门的节点组，避免和 CI runner 混部
    role: mo
  dn:
    cacheVolume:
      size: 1Gi
    config: |
      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = [10](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/3588862203/jobs/6040856760#step:8:11)0
      scan-interval = "5s"
      incremental-interval = "60s"
      global-interval = "100000s"
    replicas: 1
    resources:
      requests:
        cpu: 2
        memory: 2Gi
  imageRepository: matrixorigin/matrixone
  logService:
    replicas: 3
    sharedStorage:
      s3:
        path: heni-test/mo-data1/
        secretRef:
          name: awshn 
    volume:
      size: 10Gi
    config: |
      [log]
      level = "info"
      format = "json"
      max-size = 512
    resources:
      requests:
        cpu: 2
        memory: 2Gi  
  tp:
    cacheVolume:
      size: 1Gi
    config: |
      [cn.Engine]
      type = "distributed-tae"
      [log]
      level = "debug"
      format = "json"
      max-size = 512
    replicas: 2
    resources:
      requests:
        cpu: 4
        memory: 2Gi
  version: nightly-43e20b1

**Comment by heni02** [comment]
date 12.1  eks bvt case results：95%
failed case reason ：connect mo faild 
![image](https://user-images.githubusercontent.com/113406637/204961488-1f2b9d48-fa4f-410b-af83-919372abd820.png)
![image](https://user-images.githubusercontent.com/113406637/204961752-fa5e063e-c663-439a-9fd0-2f511996b792.png)
![image](https://user-images.githubusercontent.com/113406637/204961420-3e01fe10-a43e-44bf-8e29-103f86fb3ae1.png)

The mo log is in the aws s3 path：s3://heni-test/mo-data1/etl/sys/logs/2022/12/01/rawlog/
 You need to start the mo locally. Use  script to create an appearance on the new cluster and access the S3

**Comment by daviszhen** [comment]
@heni02 Do you complete server log instead of log files in rawlog in s3?

**Comment by heni02** [comment]
Later, we will consider downing the cn log

**Comment by heni02** [comment]
date 12.5 eks bvt case results：79%
failed case reason: connect mo failed
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/3619687048/jobs/6101691718
![image](https://user-images.githubusercontent.com/113406637/205641418-7b6b7881-b7dd-4efb-98a0-8d0b4f8e2ea4.png)
![image](https://user-images.githubusercontent.com/113406637/205641796-f4fa161e-4754-4ad1-8d51-bdf026838b39.png)
In this test, I recorded the log of cn0 and cn1 locally，and upload this issue for positioning problem
[cn0_eks.zip](https://github.com/matrixorigin/matrixone/files/10154298/cn0_eks.zip)
[cn1_eks.zip](https://github.com/matrixorigin/matrixone/files/10154299/cn1_eks.zip)

**Comment by heni02** [comment]
Another problem needs to be located tomorrow. The eks configuration is s3 path, but there is no newly generated directory on aws

**Comment by heni02** [comment]
The eks configuration is s3 path, but there is no newly generated directory on aws, this problem is found and is under repair

**Comment by heni02** [comment]
#7070

**Comment by heni02** [comment]
#7070

**Comment by heni02** [comment]
date 12.6 eks bvt case results：99%
fail reason :  only one case failed，column_stmt.sql does not return result in 60s
![image](https://user-images.githubusercontent.com/113406637/206072510-af52cd98-d581-4af9-aeba-2cf7974deb31.png)
s3 log path：s3://heni-test/mo-data1/etl/sys/logs/2022/12/06/

**Comment by heni02** [comment]
date 12.7 eks bvt case results：99%
fail reason : only one case failed，column_stmt.sql does not return result in 60s
![image](https://user-images.githubusercontent.com/113406637/206339369-1cd099e7-021f-46bb-9fd4-6a88209fcf41.png)
s3 log path：s3://heni-test/mo-data1/etl/sys/logs/2022/12/07/

**Comment by heni02** [comment]
[cn0.zip](https://github.com/matrixorigin/matrixone/files/10182588/cn0.zip)
[cn1.zip](https://github.com/matrixorigin/matrixone/files/10182589/cn1.zip)

**Comment by heni02** [comment]
date 12.8 eks bvt case results: 99% 
fail reason : only one case failed，column_stmt.sql does not return result in 60s，Same question as date 12.7 
![image](https://user-images.githubusercontent.com/113406637/206608269-3e72096e-3ca7-45cd-b9a7-757082947f91.png)
{"level":"ERROR","time":"2022/12/08 12:42:34.718849 +0000","caller":"frontend/util.go:509","msg":"illegal state","session_info":"connectionId 1026","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:509\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3711\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3867\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:172"}
{"level":"DEBUG","time":"2022/12/08 12:42:34.718916 +0000","caller":"frontend/util.go:519","msg":"RollbackTxn txnId:6bb4fc079d274fd890ca7ca1a7f7a4c8/Active/S:1670503201132928891-0 connectionId 1026"}
{"level":"DEBUG","time":"2022/12/08 12:42:34.718932 +0000","name":"cn-service","caller":"log/logger.go:123","msg":"txn rollback","uuid":"00000000-0000-0000-0000-200000000001","txn":"6bb4fc079d274fd890ca7ca1a7f7a4c8/Active/S:1670503201132928891-0"}
{"level":"DEBUG","time":"2022/12/08 12:42:34.718944 +0000","caller":"frontend/util.go:519","msg":"RollbackTxn exit txnId:6bb4fc079d274fd890ca7ca1a7f7a4c8/Active/S:1670503201132928891-0 connectionId 1026"}
{"level":"ERROR","time":"2022/12/08 12:42:34.718967 +0000","caller":"frontend/util.go:509","msg":"query trace status","connection_id":1026,"statement":"select statement_id, transaction_id, session_id, account, user, host, database, statement, statement_tag, statement_fingerprint, node_uuid, node_type, request_at, response_at, duration, status, err_code, error, exec_plan, rows_read, bytes_scan from system.statement_info where statement_id = \"\"","status":"fail","error":"illegal state","span":{"trace_id":"6e806dbb-76f5-11ed-8297-be74ca1895ac","kind":"statement"},"session_info":"connectionId 1026","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:509\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:483\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3719\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3867\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:172"}
{"level":"ERROR","time":"2022/12/08 12:42:34.719057 +0000","caller":"frontend/util.go:524","msg":"routine send response failed &{1 0 3 0xc000273e80 0 0 0}. error:illegal state  connectionId 1026","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logErrorf\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:524\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:178"}

**Comment by heni02** [comment]
log file exceeds the upload limit, you can contact me to ask for the log, or refer to date 12.7 log @daviszhen

**Comment by heni02** [comment]
date 12.12 eks bvt case results: 99%
same problem as date 12.8
![image](https://user-images.githubusercontent.com/113406637/207248284-ddba7a3f-fc61-41c9-bee0-75d66bec65d5.png)

**Comment by heni02** [comment]
#7184

**Comment by heni02** [comment]
date 12.14 eks bvt case results: 99%
same bugs as 12.13 @daviszhen @jianwan0214 
![image](https://user-images.githubusercontent.com/113406637/207802802-e2efeabe-7691-49f2-b067-9d04f9a6c487.png)

**Comment by heni02** [comment]
date 12.15 eks bvt case results: 100%
![image](https://user-images.githubusercontent.com/113406637/208005781-e849d086-4274-4a43-bafa-13444dcb830f.png)
After deleting the etl directory, neither of the two problems occurred date 12.14, which will be optimized later @jianwan0214

**Comment by heni02** [comment]
date 12.17 eks bvt case results: 99%
commit id: 558bd19d706ed9633fcb97ea38f03cb857d18b23 image:nightly-558bd19
fail case:
2022-12-17 12:37:56 ERROR Executor:193 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/transaction/autocommit_1.sql][row:271][create index index_table3 on tab1(a);] was executed failed, con[id=0, user=dump, ***
2022-12-17 12:37:56 ERROR Executor:195 - [EXPECT RESULT]:
no such table db.tab1
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2022-12-17 12:37:56 ERROR Executor:196 - [ACTUAL RESULT]:
not supported: statement: 'create index index_table3 on tab1 (a)'
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted

**Comment by heni02** [comment]
date 12.18 eks bvt case results: 100%
commit id : 6a0507ed73b350dd81f87b5a68d439d884d892d4
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/3724725731/jobs/6317178862

**Comment by heni02** [comment]
At present, the eks version is stable through 100%, and this issue is closed first
