### ISSUE TITLE
[func-sum()]ERROR 1105 (HY000): unknown error:[42000]unknown column 'c' in expr

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#704]
#### Can be reproduced ?
Yes

#### Steps:
create table tbl_01 (col1 int, a bigint unsigned, c char(10) not null);
insert into tbl_01 values (1,1,"a");
insert into tbl_01 values (2,2,"b");
insert into tbl_01 values (2,3,"c");
insert into tbl_01 values (3,4,"E");
insert into tbl_01 values (3,5,"C");
insert into tbl_01 values (3,6,"D");
select a,c,sum(a) from tbl_01 group by a;

#### Expected behavior:
Succcessfully execution

#### Actual behavior:
ERROR 1105 (HY000): unknown error:[42000]unknown column 'c' in expr

mo-server log snippet:
2021/09/14 16:42:50.069988 +0800 INFO cmd 3
2021/09/14 16:42:50.070082 +0800 INFO query:select a,c,sum(a) from tbl_01 group by a
2021/09/14 16:42:50.071684 +0800 INFO connection id 6 , the time of handling the request 1.705458ms
#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by nnsgmsone** [comment]
support now

**Comment by lignay** [comment]
Fixed and added the case to BVT
