### ISSUE TITLE
[Feature Request]: Support to modify password of account administaror

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#7042]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

ALTER ACCOUNT  [IF EXISTS]
account auth_option
[status_option] 

auth_option: {
    ADMIN_NAME [=] 'admin_name'
    IDENTIFIED BY 'auth_string'
}

status_option: {
 OPEN 
  | SUSPEND
}

**Comment by LiSong0214** [comment]
In MO v0.7, remove #6673 ，add this issue. @daviszhen

**Comment by LiSong0214** [comment]
It is possible to use the same sql statement to achieve: #6659

**Comment by DanielZhangQD** [comment]
If not too much extra effort, it's also reasonable to reset the password for root and dump.

**Comment by daviszhen** [comment]
After discussion, the conclusion:
1, the resetting password of the administrator of the account by the alter account;
2, the resetting password of the general user by the alter user;
3, the moadmin do the alter account;
4, the administrator or user itself do the alter user;

**Comment by heni02** [comment]
test done ,pr merged

**Comment by LiSong0214** [comment]
请注意: alter account <account_name> admin_name='<name>' identified by '<password>' 仅仅可以修改任意用户的密码，并不能更改account 管理员用户。 @lacrimosaprinz
