### ISSUE TITLE
[Subtask]: Rename the type of UUID

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7050]
### Parent Issue

https://github.com/matrixorigin/MO-Cloud/issues/276

### Detail of Subtask

The current name of uuid conflicts with users columns names. 
Can we rename this type to a new name, such as follwing:
uuids
uu_id
@bluearena can provide a suggestion.

**Comment by fengttt** [comment]
rename type is not a fix.   create table (uuid uuid) should succeed.  

This is a parser issue.

**Comment by iamlinjunhong** [comment]
<img width="805" alt="截屏2023-04-04 上午11 12 37" src="https://user-images.githubusercontent.com/49111204/229677474-bc496212-8bfc-4956-974b-5cf34cfa0f39.png">
create table t1 (uuid uuid) can work.
