### ISSUE TITLE
[Bug]: 编译mo-dump报错 make: *** 没有规则可制作目标“mo-dump”。 停止。

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixone#7058]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e4ab5e0e136c23a3824ac9ee82f9a19d2fa6cf28
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

编译mo-dump 报错 make: *** 没有规则可制作目标“mo-dump”。 停止。

go version go1.19.2 linux/amd64

gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

**Comment by mooleetzi** [comment]
pls try `make modump`

**Comment by mooleetzi** [comment]
@yinmh if last command works, pls close this issue ~

**Comment by fengttt** [comment]
If the binary is mo-dump, why makefile target is not mo-dump?

**Comment by mooleetzi** [comment]
`modump` can be typed easier, and `mo-dump` follows `mo-service`

**Comment by aressu1985** [comment]
fixed
