### ISSUE TITLE
[Enhancement]: Read Committed mode, Pessimistic CC on CN.

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7066]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Right now we are running at SI mode.

Once lock service is up, we can consider set default isolation level 
to Read Committed.  This will roughly make our conflict rate to match
postgres or oracle.
```

### Why is this needed ?

Reduce conflicts in high concurrency/high conflicts application/benchmarks.

### Additional information

Let's plan, potentially move this to 1.0

**Comment by zhangxu19830126** [comment]
I write a proposal in https://github.com/matrixorigin/docs/tree/main/design/transaction_rc_mode.

**Comment by zhangxu19830126** [comment]
The coexistence scheme of SI and RC has been determined, and the question left now is whether to run Lockservice on CN or DN

**Comment by zhangxu19830126** [comment]
pessimistic design: [here](https://github.com/matrixorigin/docs/blob/main/design/pessimistic_txn.md)

**Comment by zhangxu19830126** [comment]
Also integrate pessimistic transactions within cn, relying on @ouyuanning  delete of plan modifications. insert completed.

**Comment by sukki37** [comment]
The basic functions have been completed; subsequent optimizations or bugs will be tracked through separate issues.
