### ISSUE TITLE
[Bug]: function FIELD(), wrong return

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7074]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit 0a533c33772d8a5965b498cbc93c37673093af1f
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

Query statement : select field(1, '1', 1, 'true');
result : 
ERROR 1105 (HY000): strconv.ParseFloat: parsing "true": invalid syntax

**Comment by YANGGMM** [comment]
change error message

**Comment by goodMan-code** [comment]
this behavior is correct, does need fix
