### ISSUE TITLE
[Subtask]: Support more system parameters for SHOW in parser

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#7079]
### Parent Issue

#6632

### Detail of Subtask

SHOW FUNCTION STATUS [like_or_where]
SHOW GRANTS FOR role
SHOW INDEX FROM tbl_name [FROM db_name]
SHOW TRIGGERS [FROM db_name] [like_or_where]
SHOW NODE LIST
SHOW LOCKS
SHOW GRANTS FOR role
SHOW INDEX FROM tbl_name [FROM db_name]

**Comment by domingozhang** [comment]
SHOW GRANTS FOR ROLE role_name;
Get the granted privilges or roles list for role_name;

SHOW NODE LIST;
Get the node id and node type of MO cluster, such as 
00001   CN
00002  DN
00003  LS

SHOW LOCKS
Get the current existing locks and locked tables
lock_type    lock_time                            database         table
write            2022-01-01 12:00:00         test                  t1

**Comment by YANGGMM** [comment]
show node list  stmt has keyword conflict with some test content @domingozhang
