### ISSUE TITLE
LOAD DATA cannot work with relative path

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#708]
#### Can be reproduced ?
Yes

#### Steps:
Load data from a data file in current path but failed.

load data infile 'lineorder_flat_p' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 1105 (HY000): unknown error:file lineorder_flat_p does exist. err:stat lineorder_flat_p: no such file or directory

load data infile './lineorder_flat_p' into table lineorder_flat FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
ERROR 1105 (HY000): unknown error:file ./lineorder_flat_p does exist. err:stat ./lineorder_flat_p: no such file or directory

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b303dcfd17b76d6357ba81cfee3b8c23d32d5374
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by broccoliSpicy** [comment]
Here are some of my immature thoughts and guesses regarding this issue:
    In our implementation, a file is opened by the Golang standard library function os.Open, which can handle the relative file path itself(by calling the syscall). 
Since we didn’t use the LOCAL clause, when we give a relative file path to the mo-server, it is interpreted as a file path relative to the mo-server executable.
I think the real issue here is that your working directory isn't the same as the mo-server executable.

**Comment by daviszhen** [comment]
> Here are some of my immature thoughts and guesses regarding this issue: In our implementation, a file is opened by the Golang standard library function os.Open, which can handle the relative file path itself(by calling the syscall).
> 
> Since we didn’t use the LOCAL clause, when we give a relative file path to the mo-server, it is interpreted as a file path relative to the mo-server executable.
> 
> I think the real issue here is that your working directory isn't the same as the mo-server executable.

Thanks. It is inspiring. I will try it.
