### ISSUE TITLE
[Enhancement]: The result returned after exporting the data is not clear

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#7080]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
When the execution of select into outfile is successful, the returned sql command line result is "Empty set". I think it is better like this:"Query OK, 3 rows affected"

mysql> select * from user into outfile '/Users/songli/Desktop/export_datatable.txt';
Empty set (0.01 sec)
```

**Comment by daviszhen** [comment]
may print more clear infos

**Comment by taofengliu** [comment]
not working on it

**Comment by taofengliu** [comment]
not working on it

**Comment by taofengliu** [comment]
not working on it

**Comment by sukki37** [comment]
This issue has been inactive for a while. Based on the recent updates and changes in the project, this problem has been resolved or is no longer relevant.

I am going to close this issue. If anyone still experiences this problem or has further concerns, please feel free to reopen the issue or create a new one.
