### ISSUE TITLE
[Bug]: function field(), get different from mysql when use left join and right join

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7084]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit 0a533c33772d8a5965b498cbc93c37673093af1f
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

Table structure : 
create table t1(
    str1 varchar(50),
    str2 varchar(50)
);
create table t2(
    str1 varchar(50),
    str2 varchar(50)
);

data : 
insert into t1 values ('',' '), ('aa', 'Aa'), ('null',null);
insert into t2 values ('','\r'), ('aa', 'AA'), (null, 'null');

Query SQL : 
select field(t1.str1, t2.str1) from t1 left join t2 on t1.str1 = t2.str1;
result of mo : 
![2022-12-07 15-06-01屏幕截图](https://user-images.githubusercontent.com/74952516/206111358-1e9b72b5-d27a-41eb-ab9f-972332b3e786.png)
result of mysql : 
![2022-12-07 15-06-14屏幕截图](https://user-images.githubusercontent.com/74952516/206111454-48aa162a-b224-4958-88d3-ec29374a0dbf.png)

**Comment by YANGGMM** [comment]
select t1.str1, t2.str1 from t1 left join t2 on t1.str1 = t2.str1; have different result in mo and mysql：
in mo：
mysql> select t1.str1, t2.str1 from t1 left join t2 on t1.str1 = t2.str1;
+------+------+
| str1 | str1 |
+------+------+
|      |      |
| aa   | aa   |
| null | NULL |
+------+------+

in mysql：mysql> select t1.str1, t2.str1 from t1 left join t2 on t1.str1 = t2.str1;
+------+------+
| str1 | str1 |
+------+------+
|      | NULL |
|      |      |
| aa   | aa   |
| null | NULL |
+------+------+

it is not function‘s  error

**Comment by aunjgr** [comment]
It's a bug of MySQL 8.0. It falsely treats empty string and `null` as equal. Even on MySQL 5.7, the behavior is the same with MO, which is correct.

F*CK MYSQL.
