### ISSUE TITLE
[Bug]: function field(), get wrong result between mo and mysql

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7085]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit https://github.com/matrixorigin/matrixone/commit/0a533c33772d8a5965b498cbc93c37673093af1f
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

Table structure : 
create table t1(
    str1 char(50),
    str2 char(50),
    primary key (str1)
);
create table t2(
    str1 char(50),
    str2 char(50),
    primary key (str1)
);

data : 
insert into t1 values ('',' '), ('aa', 'Aa'), ('null',NULL);
insert into t2 values ('','\r'), ('aa', 'AA'), ('null', '');

Query Statement : 
select field(t1.str1, t2.str1) from t1 inner join t2 on t1.str1 = t2.str1;

result on mo : 
+-------------------------+
| field(t1.str2, t2.str2) |
+-------------------------+
|                       0 |
|                       0 |
|                       1 |
+-------------------------+

result on mysql : 
+-------------------------+
| field(t1.str2, t2.str2) |
+-------------------------+
|                       0 |
|                       1 |
|                       0 |
+-------------------------+

**Comment by YANGGMM** [comment]
i have found the bug， i will fix it.

**Comment by goodMan-code** [comment]
checked it, can be closed. the result is same as mysql
