### ISSUE TITLE
[Bug]: function field(), get wrong result between 0 and null

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7088]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit https://github.com/matrixorigin/matrixone/commit/0a533c33772d8a5965b498cbc93c37673093af1f
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

Table structure : 
create table t1(
    i double,
    f decimal(6,3),
    primary key (i)
);
create table t2(
    i double,
    f decimal(6,3),
    primary key (i)
);

data : 
insert into t1 values (0.01, 0.001), (0.0, -1), (-0.000000001, 1);
insert into t2 values (0.01, 0.01), (-1.0, -1), (0.000000001, -1);

Query statement : 
select t1.i, t2.f, field(t1.i, t2.f) from t1 left join t2 on t1.i = t2.i;

result on mo : 
+--------------+-------+-------------------+
| i            | f     | field(t1.i, t2.f) |
+--------------+-------+-------------------+
|         0.01 | 0.010 |                 1 |
|            0 |  NULL |                 1 |
| -0.000000001 |  NULL |                 0 |
+--------------+-------+-------------------+

result on mysql : 
+--------------+-------+-------------------+
| i            | f     | field(t1.i, t2.f) |
+--------------+-------+-------------------+
| -0.000000001 |  NULL |                 0 |
|            0 |  NULL |                 0 |
|         0.01 | 0.010 |                 1 |
+--------------+-------+-------------------+

**Comment by YANGGMM** [comment]
same error as #7085
