### ISSUE TITLE
[Bug]: bad TPS performance in CN-DN deployment running sysbench with auto increment disabled

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#7092]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Run sysbench with 100 concurrency and auto increment disabled

1. ./start.sh -m SYSBENCH -n 1 -s 1
2. change sysbench.yml
<img width="401" alt="image" src="https://user-images.githubusercontent.com/39627130/206142863-9b7c33bc-c66d-4dea-9ef2-a22ea333651e.png">

3. ./start.sh -t 100 -c cases/sysbench/simple_insert_10_10000

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/39627130/206143298-f1773992-1422-4299-9961-b7b4605fe139.png">

![profile042](https://user-images.githubusercontent.com/39627130/206143510-a449a92c-4abb-4c8c-89a9-e23c35b4a8ce.png)

**Comment by florashi181** [comment]
@aressu1985 could we have a test if this is solved?

**Comment by aressu1985** [comment]
from 1-18 till now , the insert for no-autoicnr table oltp result is as following:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/47846308/217707725-ecaa44ea-6e35-429e-ab6c-dd5c48f0cae0.png">

**Comment by aressu1985** [comment]
I will do it in 0.8

**Comment by aressu1985** [comment]
In 0.8.0, TP performence test will be executed daily ,and this issue can be closed
