### ISSUE TITLE
[Bug]: Result of aggregate function with group clause is not always the same

### ISSUE THREAD

**Issue by mooleetzi** [matrixorigin/matrixone#7095]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
select * from t1;
+------+------+
| a    | b    |
+------+------+
|    4 |    3 |
|    1 | NULL |
|    2 | NULL |
|    3 | NULL |
+------+------+
```

`select a,max(b) from t1 group by a;`
```
case a
+------+--------+
| a    | max(b) |
+------+--------+
|    1 |   NULL |
|    2 |   NULL |
|    3 |   NULL |
|    4 |      3 |
+------+--------+
case b
+------+--------+
| a    | max(b) |
+------+--------+
|    4 |      3 |
|    1 |   NULL |
|    2 |   NULL |
|    3 |   NULL |
+------+--------+
```

result a and b occur in one sql.

### Expected Behavior

tried in mysql, it's always same.

**Comment by m-schen** [comment]
it's not a bug.

Without order by, we cannot guarantee the order of the results because we run the query in parallel. and which result was sent to result-merge-process more early we will output it  more early.
@mooleetzi
