### ISSUE TITLE
[Bug]: create table 1k cols, error : data out of range: data type varchar/char

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7102]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit 216012400964ced41072bec7c3415255ea08a552

when I try to create a table that contain 1k cols, an error occurs : ERROR 1690 (HY000): data out of range: data type varchar/char ,

DDL : 
[mo_1k_cols.txt](https://github.com/matrixorigin/matrixone/files/10183827/mo_1k_cols.txt)

**Comment by florashi181** [comment]
@goodMan-code pls verify this one
