### ISSUE TITLE
[Bug]: function format(), mo panic, float type

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7105]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit https://github.com/matrixorigin/matrixone/commit/a7fef3dd396461eded16bc85263221b56fe44eda
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

Table structure :
create table t(
i double,
b float,
primary key (i)
);

data :
insert into t values (0.00000000000001, NULL), (-0.0000000000001, 9999999999999999999999999);
insert into t values ('0.0000000001', SIN(1)), (1., COS(0));

SQL : 
select b, format(b, 1) from t order by b desc;
select b, format(b, 0) from t order by b desc;
select b, format(b, -1) from t order by b desc;
select b, format(b, '1') from t order by b desc;
select b, format(b, '-1') from t order by b desc;
select b, format(b, '0') from t order by b desc;

**Comment by YANGGMM** [comment]
sorry， i did't consider no-string type in format();

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by goodMan-code** [comment]
trace #7356
