### ISSUE TITLE
[Bug]: function format(), mo panic, bigint type

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7106]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit https://github.com/matrixorigin/matrixone/commit/a7fef3dd396461eded16bc85263221b56fe44eda
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

table structure : 
create table t(
    i int,
    b bigint,
    primary key (i)
);

data : 
insert into t values (1, 9999999999999999999999999999), (0,0000000000000000);
insert into t values (-1, null), (0000000000000000, 1);

SQL : 
select b, format(b, 1) from t order by b desc;
select b, format(b, 0) from t order by b desc;
select b, format(b, -1) from t order by b desc;
select b, format(b, '1') from t order by b desc;
select b, format(b, '-1') from t order by b desc;
select b, format(b, '0') from t order by b desc;
select b, format(b, 'x') from t order by b desc;

**Comment by YANGGMM** [comment]
sorry， i did't consider no-string type in format();

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by goodMan-code** [comment]
commit 0bfcd472625148b22e274989c69e11ac98704590
Retest date : 2023-1-19 10 : 40 GMT+8, no panic info output, and the result is correct.
