### ISSUE TITLE
[Bug]: function format(), wrong result for DATE and DATETIME type

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7107]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit https://github.com/matrixorigin/matrixone/commit/a7fef3dd396461eded16bc85263221b56fe44eda
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

table structure : 
create table t(
    d date,
    dt datetime,
    primary key (d)
);

data : 
insert into t values ('2022-12-04', '2022-12-04 00:03:36');
insert into t values ('2023-11-11', '2023-11-11 03:00:48');

SQL : 
select d, format(d, 1) from t order by d desc;
select d, format(d, 0) from t order by d desc;
select d, format(d, -1) from t order by d desc;
select d, format(d, length("123456789")) from t order by d desc;
select dt, format(dt, 1) from t order by dt desc;
select dt, format(dt, 0) from t order by dt desc;
select dt, format(dt, -1) from t order by dt desc;
select dt, format(dt, length("123456789")) from t order by dt desc;

mo's result can not be accepted.

**Comment by domingozhang** [comment]
https://github.com/matrixorigin/matrixone/pull/7059 
this pr is under reviewing. after merged, let's check the result.

**Comment by goodMan-code** [comment]
commit 0bfcd472625148b22e274989c69e11ac98704590
Retest date : 2023-1-19 10 : 20 GMT+8, the behavior can be accepted.
