### ISSUE TITLE
[Bug]: function format(), mo panic when left join and right join

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7109]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit https://github.com/matrixorigin/matrixone/commit/a7fef3dd396461eded16bc85263221b56fe44eda
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

table structure : 
create table t1(
    c1 int,
    c2 bigint,
    primary key (c1)
);
create table t2(
    i int,
    b bigint,
    primary key (i)
);

data : 
insert into t1 values ('111', '222'), ('000', '111'), ('-111', null);
insert into t2 values (111, 999999), (0,0000000), (-1, null), (11111, 1);

SQL : 
select c1, format(c1,1), i, format(i,1) from t1 left join t2 on t1.c1 = t2.i order by c1 desc;
select c1, format(c1,1), i, format(i,1) from t1 right join t2 on t1.c1 = t2.i order by c1 desc;

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working on it

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by goodMan-code** [comment]
select c1, format(c1,1), i, format(i,1) from t1 left join t2 on t1.c1 = t2.i order by c1 desc;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vectorize/format.format
        /data/zuoxingguang/mo20230116/matrixone/pkg/vectorize/format/format.go:289
github.com/matrixorigin/matrixone/pkg/vectorize/format.formatENUS
        /data/zuoxingguang/mo20230116/matrixone/pkg/vectorize/format/format.go:249
github.com/matrixorigin/matrixone/pkg/vectorize/format.getNumberFormat
        /data/zuoxingguang/mo2



select c1, format(c1,1), i, format(i,1) from t1 right join t2 on t1.c1 = t2.i order by c1 desc;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vectorize/format.format
        /data/zuoxingguang/mo20230116/matrixone/pkg/vectorize/format/format.go:289
github.com/matrixorigin/matrixone/pkg/vectorize/format.formatENUS
        /data/zuoxingguang/mo20230116/matrixone/pkg/vectorize/format/format.go:249
github.com/matrixorigin/matrixone/pkg/vectorize/format.getNumberFormat
        /data/zuoxingguang/mo2

**Comment by goodMan-code** [comment]
commit 0bfcd472625148b22e274989c69e11ac98704590
Retest date : 2023-1-19 10 : 20  GMT+8, mo's behavior is same to mysql, and the result is correct
