### ISSUE TITLE
[Bug]: After execution mo-tpcc load 10 warehouse , the resources are not released. It seems that asynchronous tasks are still being executed. In addition, the connection through the MySQL client is always stuck.

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixone#7110]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e4ab5e0e136c23a3824ac9ee82f9a19d2fa6cf28
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

standalone mode 
After execution mo-tpcc load 10 warehouse , the resources are not released. It seems that asynchronous tasks are still being executed. In addition, the connection through the MySQL client is always stuck.

mo-tpcc-main report errors : 
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
java.sql.SQLException: internal error: message body 325361677 is too large, max is 104857600
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813)
        at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:765)
        at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
        at java.lang.Thread.run(Thread.java:750)
Worker 007: ERROR: internal error: message body 325361677 is too large, max is 104857600
java.sql.SQLException: internal error: message body 325124979 is too large, max is 104857600
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813)
        at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:765)
        at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
        at java.lang.Thread.run(Thread.java:750)
Worker 008: ERROR: internal error: message body 325124979 is too large, max is 104857600

mo-service.log : 2022/12/09 07:15:36.316528 +0800 ERROR frontend/util.go:509 query trace status {"connection_id": 1033, "statement": "commit", "status": "fail", "error": "internal error: message body 325124979 is too large, max is 104857600", "span": {"trace_id": "31a43ea5-774e-11ed-9020-525400b7e28c", "kind": "statement"}, "session_info": "connectionId 1033"}
github.com/matrixorigin/matrixone/pkg/frontend.logError
        /opt/module/src/matrixone/pkg/frontend/util.go:509
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus
        /opt/module/src/matrixone/pkg/frontend/util.go:493
github.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus
        /opt/module/src/matrixone/pkg/frontend/util.go:483
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /opt/module/src/matrixone/pkg/frontend/mysql_cmd_executor.go:3710
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /opt/module/src/matrixone/pkg/frontend/mysql_cmd_executor.go:3858
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /opt/module/src/matrixone/pkg/frontend/routine.go:172
2022/12/09 08:00:00.083002 +0800 ERROR memtable/physical_row.go:190 error: txn write conflict d1c874e6-9362-43e7-98d4-7f328f58cf5d bba541d9-3fa0-4af1-bcc0-bc7f75aa3b26
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*PhysicalRow[...]).Delete
        /opt/module/src/matrixone/pkg/txn/storage/memorystorage/memtable/physical_row.go:190
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Table[...]).Delete.func1
        /opt/module/src/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:281
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Table[...]).update
        /opt/module/src/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:669
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memtable.(*Table[...]).Delete
        /opt/module/src/matrixone/pkg/txn/storage/memorystorage/memtable/table.go:275
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Partition).DeleteByBlockID
        /opt/module/src/matrixone/pkg/vm/engine/disttae/partition.go:415
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeEntry
        /opt/module/src/matrixone/pkg/vm/engine/disttae/logtail.go:116
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.consumeLogTail
        /opt/module/src/matrixone/pkg/vm/engine/disttae/logtail.go:86
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartition
        /opt/module/src/matrixone/pkg/vm/engine/disttae/logtail.go:46
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*DB).Update
        /opt/module/src/matrixone/pkg/vm/engine/disttae/db.go:287
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*table).Ranges
        /opt/module/src/matrixone/pkg/vm/engine/disttae/table.go:117
github.com/matrixorigin/matrixone/pkg/sql/colexec.getCurrentIndex
        /opt/module/src/matrixone/pkg/sql/colexec/auto_incr.go:256
github.com/matrixorigin/matrixone/pkg/sql/colexec.getOneColRangeFromAutoIncrTable
        /opt/module/src/matrixone/pkg/sql/colexec/auto_incr.go:163
github.com/matrixorigin/matrixone/pkg/sql/colexec.getRangeFromAutoIncrTable
        /opt/module/src/matrixone/pkg/sql/colexec/auto_incr.go:111
github.com/matrixorigin/matrixone/pkg/sql/colexec.UpdateInsertBatch
        /opt/module/src/matrixone/pkg/sql/colexec/auto_incr.go:59
github.com/matrixorigin/matrixone/pkg/sql/colexec.UpdateInsertValueBatch
        /opt/module/src/matrixone/pkg/sql/colexec/auto_incr.go:81
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).InsertValues
        /opt/module/src/matrixone/pkg/sql/compile/dml.go:145
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
        /opt/module/src/matrixone/pkg/sql/compile/compile.go:140
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /opt/module/src/matrixone/pkg/frontend/mysql_cmd_executor.go:3514
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /opt/module/src/matrixone/pkg/frontend/mysql_cmd_executor.go:3912
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop
        /opt/module/src/matrixone/pkg/frontend/routine.go:172
2022/12/09 08:00:00.100987 +0800 ERROR dn-service log/logger.go:123 txn commit with 1 PC failed {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "dn-shard": "2-262146-1-127.0.0.1:22000", "txn": "4bb8a6ee94d04a2f80dfe7c916965ee0/Active/S:1670544000056457182-0/C:1670544000100895302-0", "error": "w-w conflict"}
2022/12/09 08:00:00.101237 +0800 ERROR dn-service log/logger.go:123 txn commit with 1 PC failed {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "dn-shard": "2-262146-1-127.0.0.1:22000", "txn": "aa861477935b4a52adca7254c970ec8d/Active/S:1670544000058801384-0/C:1670544000101177918-0", "error": "w-w conflict"}
2022/12/09 08:00:00.118442 +0800 ERROR dn-service log/logger.go:123 txn commit with 1 PC failed {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "dn-shard": "2-262146-1-127.0.0.1:22000", "txn": "8d4761c5a5024323b3dc1a3ecca7b4a3/Active/S:1670544000101497775-0/C:1670544000118377737-0", "error": "w-w conflict"}
2022/12/09 08:00:00.172560 +0800 ERROR dn-service log/logger.go:123 txn commit with 1 PC failed {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "dn-shard": "2-262146-1-127.0.0.1:22000", "txn": "8f354552ee954f209c4a38ca60fc5368/Active/S:1670544000149319883-0/C:1670544000172513716-0", "error": "w-w conflict"}

**Comment by yinmh** [comment]
Sorry, my problem, this problem should occur in version 0.6

**Comment by daviszhen** [comment]
the error:

internal error: message body 325124979 is too large, max is 104857600

**Comment by yinmh** [comment]
How to solve this problem by modifying the max ?

**Comment by yinmh** [comment]
ok
