### ISSUE TITLE
[Performance]: logservice performance enhancement

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#7115]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

The main goal is to increase throughput of logservice/tan.

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by zhangxu19830126** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/2995754/209743822-b564462c-33a8-4076-b23c-332a02c6da3e.png">
Test the performance of the logservice in these combinations and document them in an issue. @volgariver6

**Comment by volgariver6** [comment]
Close this parent issue as child issue is closed.
