### ISSUE TITLE
[Feature Request]: support efficient KV on memory

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#7121]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

we hope the KV can be used for cache to speed up TP query.
key is primary key,
and value is the row data.

**Comment by florashi181** [comment]
not necessary lockless

**Comment by aressu1985** [comment]
what status is this feature?

**Comment by zengyan1** [comment]
This feature is not needed now
