### ISSUE TITLE
[Bug]: explain analyze statement return wrong analyze info

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#7123]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MySQL [ssb]> explain analyze select count(*) from lineorder join dates on lo_orderdate = d_datekey;
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                     |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Project                                                                                                                                                        |
|   Analyze: timeConsumed=0us inputRows=1 outputRows=1 inputSize=8bytes outputSize=8bytes memorySize=0bytes                                                      |
|   ->  Aggregate                                                                                                                                                |
|         Analyze: timeConsumed=853075us inputRows=3 outputRows=2 inputSize=8bytes outputSize=16bytes memorySize=0bytes                                          |
|         Aggregate Functions: starcount(1)                                                                                                                      |
|         ->  Join                                                                                                                                               |
|               Analyze: timeConsumed=2824754us inputRows=12004986 outputRows=6001215 inputSize=48019944bytes outputSize=24004860bytes memorySize=48009720bytes  |
|               Join Type: INNER                                                                                                                                 |
|               Join Cond: (lineorder.lo_orderdate = dates.d_datekey)                                                                                            |
|               ->  Table Scan on ssb.dates                                                                                                                      |
|                     Analyze: timeConsumed=2667524us inputRows=30013746 outputRows=24012533 inputSize=120054980bytes outputSize=96050120bytes memorySize=0bytes |
|               ->  Table Scan on ssb.lineorder                                                                                                                  |
|                     Analyze: timeConsumed=378us inputRows=12002430 outputRows=12002430 inputSize=48009720bytes outputSize=48009720bytes memorySize=0bytes      |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
13 rows in set (0.94 sec)

when join order in wrong, lineorder on the right side , this bug is more obvious.

**Comment by dongdongyang33** [comment]
Because the same `Batch` will be re-calculated many times in a plan node.
fixing.

**Comment by tianyahui-python** [comment]
closed
