### ISSUE TITLE
[Bug]: wrong return when create database

### ISSUE THREAD

**Issue by goodMan-code** [matrixorigin/matrixone#7124]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

commit 657e5c1b5bf2a1dc13b181063c000bcad260586e
./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

mo behavior : 
create database ttt;
Query OK, 0 rows affected (0.01 sec)

mysql behavior : 
Query OK, 1 row affected (0.01 sec)

**Comment by aressu1985** [comment]
fixed:657e5c1b5bf2a1dc13b181063c000bcad260586e
mysql> create database ttt;
Query OK, 1 row affected (0.17 sec)

mysql>
