### ISSUE TITLE
[Subtask]: DML calculation execution of index

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#7134]
### Parent Issue

#4098

### Detail of Subtask

DML calculation execution of index

**Comment by bbbearxyz** [comment]
will fix later

**Comment by qingxinhome** [comment]
still work on it

**Comment by bbbearxyz** [comment]
will fix later

**Comment by bbbearxyz** [comment]
most of the code is complete, now do some test and fix bug.
