### ISSUE TITLE
[Subtask]: Support left table build in join operator(except inner join)

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7140]
### Parent Issue

#5121

### Detail of Subtask

Binary Operator add support left table build. Suggested Implement Order by @nnsgmsone :

- [x] 1. Left
- [x] 2. Anti
- [x] 3. Semi
- [ ] 4. Single
- [ ] 5. Minus
- [ ] 6. Intersect

Mark/Outer maybe leave to 0.8

**Comment by aunjgr** [comment]
right SEMI/ANTI join is finished

**Comment by aunjgr** [comment]
Minus/Intersect has no tpch/ssb cases. Won't do in 0.8.

This issue can be closed.

**Comment by sukki37** [comment]
Close.  Create new issues for Minus/Intersect/Mark/Outer when needed.
