### ISSUE TITLE
[Subtask]: Design Doc of `CN write S3 directly for large transaction`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7157]
### Parent Issue

#6824 

### Detail of Subtask

Write e2e dev design doc for `CN write S3 directly for large transaction`

**Comment by triump2020** [comment]
https://github.com/matrixorigin/docs/pull/70/commits/0430a81b94e4a473943a8343efc1b671fc3ade93

**Comment by triump2020** [comment]
https://github.com/matrixorigin/docs/pull/70/commits/0430a81b94e4a473943a8343efc1b671fc3ade93

**Comment by JackTan25** [comment]
working on it

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
The logic of the document has been checked with moChen, and the internal logic of CN and the connection with s3 still need more time.

**Comment by jensenojs** [comment]
技术评审中

**Comment by JackTan25** [comment]
finished
