### ISSUE TITLE
[Subtask]: Add direct s3 `insert` support for CN workspace

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7160]
### Parent Issue

#6824 

### Detail of Subtask

1. Add a direct insert to s3 support for CN workspace
2. Supports primary key de-duplication

### Additional information

dependent issue https://github.com/matrixorigin/matrixone/issues/7157 https://github.com/matrixorigin/matrixone/issues/7158

**Comment by jensenojs** [comment]
在测试

**Comment by jensenojs** [comment]
almost done

**Comment by JackTan25** [comment]
finished, need people to review

**Comment by sukki37** [comment]
Not finished in 0.7.0

**Comment by nnsgmsone** [comment]
你们的工作。主键去重。。 @w-zr  @ouyuanning  @triump2020

**Comment by domingozhang** [comment]
@ouyuanning can this issue be closed?

**Comment by ouyuanning** [comment]
CN去重已完成，可通过配置打开
