### ISSUE TITLE
[Bug]: The statement of creating a table does not match the query of show create table.

### ISSUE THREAD

**Issue by yinmh** [matrixorigin/matrixone#7186]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:k8s deploy  matrixone-operator-0.6.0-alpha.2.tgz
```

### Actual Behavior

Statement of table creation：
create table t1
(
    c1  int primary key auto_increment,
    c2  tinyint not null default 4,
    c3  smallint,
    c4  bigint,
    c5  tinyint unsigned,
    c6  smallint unsigned,
    c7  int unsigned,
    c8  bigint unsigned,
    c9  float,
    c10 double,
    c11 date,
    c12 datetime,
    c13 timestamp on update current_timestamp,
    c14 char,
    c15 varchar,
    c16 json,
    c17 decimal,
    c18 text,
    c19 blob,
    c20 uuid
);

show create table :

CREATE TABLE `t1` (
`c1` INT NOT NULL AUTO_INCREMENT,
`c2` TINYINT DEFAULT 4,
`c3` SMALLINT DEFAULT NULL,
`c4` BIGINT DEFAULT NULL,
`c5` TINYINT UNSIGNED DEFAULT NULL,
`c6` SMALLINT UNSIGNED DEFAULT NULL,
`c7` INT UNSIGNED DEFAULT NULL,
`c8` BIGINT UNSIGNED DEFAULT NULL,
`c9` FLOAT DEFAULT NULL,
`c10` DOUBLE DEFAULT NULL,
`c11` DATE DEFAULT NULL,
`c12` DATETIME DEFAULT NULL,
`c13` TIMESTAMP DEFAULT NULL,
`c14` CHAR(1) DEFAULT NULL,
`c15` VARCHAR(1) DEFAULT NULL,
`c16` JSON DEFAULT NULL,
`c17` DECIMAL128 DEFAULT NULL,
`c18` TEXT DEFAULT NULL,
`c19` TEXT DEFAULT NULL,
`c20` UUID DEFAULT NULL,
PRIMARY KEY (`c1`)
);

`c17` DECIMAL128 DEFAULT NULL,
It seems that it is not supported at present : DECIMAL128

**Comment by aressu1985** [comment]
fixed:46a417daf4b55b93a35682995033ed18b8f1d096

mysql> use test;
Database changed
mysql> create table t1
    -> (
    -> c1 int primary key auto_increment,
    -> c2 tinyint not null default 4,
    -> c3 smallint,
    -> c4 bigint,
    -> c5 tinyint unsigned,
    -> c6 smallint unsigned,
    -> c7 int unsigned,
    -> c8 bigint unsigned,
    -> c9 float,
    -> c10 double,
    -> c11 date,
    -> c12 datetime,
    -> c13 timestamp on update current_timestamp,
    -> c14 char,
    -> c15 varchar,
    -> c16 json,
    -> c17 decimal,
    -> c18 text,
    -> c19 blob,
    -> c20 uuid
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> show create table t1;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
`c1` INT NOT NULL AUTO_INCREMENT,
`c2` TINYINT DEFAULT 4,
`c3` SMALLINT DEFAULT NULL,
`c4` BIGINT DEFAULT NULL,
`c5` TINYINT UNSIGNED DEFAULT NULL,
`c6` SMALLINT UNSIGNED DEFAULT NULL,
`c7` INT UNSIGNED DEFAULT NULL,
`c8` BIGINT UNSIGNED DEFAULT NULL,
`c9` FLOAT DEFAULT NULL,
`c10` DOUBLE DEFAULT NULL,
`c11` DATE DEFAULT NULL,
`c12` DATETIME DEFAULT NULL,
`c13` TIMESTAMP DEFAULT NULL ON UPDATE current_timestamp(),
`c14` CHAR(1) DEFAULT NULL,
`c15` VARCHAR(65535) DEFAULT NULL,
`c16` JSON DEFAULT NULL,
`c17` DECIMAL(34,0) DEFAULT NULL,
`c18` TEXT DEFAULT NULL,
`c19` BLOB DEFAULT NULL,
`c20` UUID DEFAULT NULL,
PRIMARY KEY (`c1`)
) |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql>
