### ISSUE TITLE
[Bug]: mo execute tpch sql, log errors.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7196]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Reproducible Steps:

1. clone https://github.com/matrixorigin/mo-tpch

**Comment by fengttt** [comment]
What is the error?   How to repro?   There should be details.   I don't see how can dev act on this.

**Comment by tianyahui-python** [comment]
sorry, This is a misoperation issue
