### ISSUE TITLE
[Bug]: mo execute tpch query, mo log error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7197]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 Reproducible Steps:
1. https://github.com/matrixorigin/mo-tpch
2. ./run.sh -g -s 1
3. ./run.sh -c -s 1
4. ./run.sh -l-s 1
5. execute q2 sql

<img width="1575" alt="截屏2022-12-14 18 35 49" src="https://user-images.githubusercontent.com/39303074/207624262-90d8cc3b-984e-4d09-8bba-99621374da9f.png">

**Comment by ouyuanning** [comment]
only error message

**Comment by fengttt** [comment]
TPCH bind error is s-1

**Comment by ouyuanning** [comment]
@fengttt 
it's not an error.  it's an improve for logging message.
sometimes we new an error, but just discard it in some logic, but error message can not discard.

@xzxiong 
I will fix it when context with the option(do not add message first） was finished.

**Comment by xzxiong** [comment]
@ouyuanning I have commit here， https://github.com/matrixorigin/matrixone/pull/7212

**Comment by ouyuanning** [comment]
> @ouyuanning I have commit here， #7212

get it

**Comment by ouyuanning** [comment]
PR is waiting for review.

**Comment by tianyahui-python** [comment]
log error fixed.
