### ISSUE TITLE
[Bug]: mo_catalog.mo_tables have wrong column information

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#7200]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

SQL: use mo_catalog;
 desc mo_tables;

will get:
| rel_createsql  | **VARCHAR(100000000)** | YES  |      | NULL    |       |         |

**Comment by JackTan25** [comment]
Working on it
