### ISSUE TITLE
[Bug]: create new account  and query statement_ Info return 0 row

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7211]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):fdf6d0e33d744882b27b348200364db1cab4d465 image:nightly-fdf6d0e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This problem exists in the eks environment. It is not determined locally
New account login, query statement_ Info return 0 row
![image](https://user-images.githubusercontent.com/113406637/207822008-f943df5f-b877-4a42-8f99-ecc449e08d77.png)
![image](https://user-images.githubusercontent.com/113406637/207822373-79760f06-4ab1-4f03-b84f-d69aec8811c3.png)

sys account query statement_ Info about new account data also return 0 row
![image](https://user-images.githubusercontent.com/113406637/207822792-62dc0f2b-3b7d-4f14-b288-eba56eebada3.png)
about sys account return more rows
![image](https://user-images.githubusercontent.com/113406637/207822997-483a5ebd-1b3d-4150-8ff3-619dc4efcbb9.png)

### Steps to Reproduce
create account `test@123456` ADMIN_NAME 'admin' IDENTIFIED BY '123456';
select statement, statement_id, duration, status, request_at, response_at, `user`, `account`, `database`, transaction_id, session_id, rows_read, bytes_scan from system.statement_info where account in('test@123456') ;

**Comment by xzxiong** [comment]
fixed, pls check

**Comment by heni02** [comment]
<img width="822" alt="企业微信截图_d58755ce-aedd-44af-b5aa-323cb981824a" src="https://user-images.githubusercontent.com/113406637/208077037-db0f7fb1-a31d-4f49-8e21-af74fb24c266.png">
At present, account supports other special characters besides @, such as common_  can add something like that? @xzxiong

**Comment by xzxiong** [comment]
@heni02 do we have doc show all account support characters ?

**Comment by heni02** [comment]
All support except :  other support such as _ @ /%&* @xzxiong

**Comment by xzxiong** [comment]
- `_`, `@` is normal name,
- `%`, `&`, `*` is too strange, and not support yet
- `/` is problem.

**Comment by xzxiong** [comment]
> All support except : other support such as _ @ /%&*

After i verify on linux, mac, s3 filepath rule,  we can support those character, except `/` . 
- Character `/` is path seperator, so it could not be part of account name 

BUT !!!  Do we really need to support those character in account name ? 
@heni02 @LiSong0214

**Comment by xzxiong** [comment]
Background
---
1. current `account` name support all characters in utf8, except `:`
2.  etl data (like logs, metric, statement records) directlly write/read S3 file, which filepath including account name info. like: `{account}/logs/2022/12/22/statement_info/*.csv`
3. etl data directlly write/read S3 file by using `fileservice.FileService` interface, that was only support charactors like a-z, A-Z, 0-9, and little ascii symbols.

Conclusion
---
If create account like `账号@123`, then etl data could  NOT write down into S3 with `FileService` interface.

Proposal
---

**Proposal 1**
keep `account` support character set same as FileService's
 - limit account only support  letter, number, and little ascii symbols
 - make FileService support all utf8 charater set ( except `:`, '/' )

**Proposal 2**
replace `account` with `account_id` in etl data's filepath.
 - like: `{account}/logs/2022/12/22/statement_info/*.csv` -> `{account_id}/logs/2022/12/22/statement_info/*.csv`

In this case, MOCloud will need extra work. Each query to user's account metric, logs,  statement_info, NEEDs to get `account_id` first.

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
After discussion with @domingozhang @daviszhen @reusee , we have new conclusion:
`account` support limited character:
- 0-9
- a-z
- A-Z
- `-` and `_`

@mooleetzi will implement is in 0.8.

**Comment by mooleetzi** [comment]
account name limitation done, pls verify @xzxiong

**Comment by xzxiong** [comment]
@heni02 ptal

**Comment by heni02** [comment]
The @ character is not supported by the interception on the account side. This problem does not exist. Turn it off
