### ISSUE TITLE
[Bug]: alter account password is null no error reported

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7222]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):783b96f7ce88b88733b7d933c3e79f60b97cabb9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/208006933-6bd8ee8b-b474-47e1-8ca2-75f047930b52.png)

create account password is null correct
![image](https://user-images.githubusercontent.com/113406637/208006834-b62fb52c-c193-4118-a26e-8ae8e26c8cb9.png)

### Steps to Reproduce

```Markdown
create account if not exists test ADMIN_NAME '1WERDFT3YG' IDENTIFIED BY '123456';
alter account test admin_name='1WERDFT3YG'  IDENTIFIED BY '';
```

**Comment by daviszhen** [comment]
it was fixed

**Comment by heni02** [comment]
confirm,closed 
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210351661-09c79472-6c53-4cd3-b6b7-cf0d8d757d58.png)
