### ISSUE TITLE
[Bug]: MO return ExpectedEOB error when creating table by jdbc with invalid database

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7224]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):56c9590273867480f531aa0ee4c539d956e09c4e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when create table by jdbc, if the database in jdbc url does not exist , mo with return error:
2022-12-16 11:07:28 ERROR DBWorkload:411 - Unexpected error when creating benchmark database tables.
java.sql.SQLException: ExpectedEOB
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
	at com.oltpbenchmark.util.ScriptRunner.runScript(ScriptRunner.java:125)
	at com.oltpbenchmark.util.ScriptRunner.runScript(ScriptRunner.java:82)
	at com.oltpbenchmark.util.ScriptRunner.runScript(ScriptRunner.java:71)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:236)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:215)
	at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:627)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:407)

error log:
2022/12/16 10:45:18.005075 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 1177, "statement": "select @@auto_increment_increment as auto_increment_increment, @@character_set_client as character_set_client, @@character_set_connection as character_set_connection, @@character_set_results as character_set_results, @@character_set_server as character_set_server, @@collation_server as collation_server, @@collation_connection as collation_connection, @@init_connect as init_connect, @@interactive_timeout as interactive_timeout, @@license as license, @@lower_case_table_names as lower_case_table_names, @@max_allowed_packet as max_allowed_packet, @@net_write_timeout as net_write_timeout, @@sql_mode as sql_mode, @@system_time_zone as system_time_zone, @@time_zone as time_zone, @@transaction_isolation as transaction_isolation, @@wait_timeout as wait_timeout", "status": "success", "span": {"trace_id": "ad0110b2-7ceb-11ed-9ba4-ce1bdd7cf1e9", "kind": "statement"}, "session_info": "connectionId 1177"}
2022/12/16 10:45:18.009209 +0800 INFO frontend/util.go:499 query trace {"connection_id": 1177, "query": "SET character_set_results = utf8", "session_info": "connectionId 1177"}
2022/12/16 10:45:18.009538 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 1177, "statement": "set character_set_results = utf8", "status": "success", "span": {"trace_id": "ad01de70-7ceb-11ed-9ba4-ce1bdd7cf1e9", "kind": "statement"}, "session_info": "connectionId 1177"}
2022/12/16 10:45:18.014517 +0800 INFO frontend/util.go:499 query trace {"connection_id": 1177, "query": "DROP TABLE IF EXISTS supplier", "session_info": "connectionId 1177"}
2022/12/16 10:45:18.014985 +0800 INFO frontend/session.go:276 session uuid: acf4d798-7ceb-11ed-9ba4-ce1bdd7cf1e9 -> background session uuid: ad02bc00-7ceb-11ed-9ba4-ce1bdd7cf1e9
2022/12/16 10:45:18.016476 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 4294967295, "statement": "start transaction", "status": "success", "span": {"trace_id": "ad02ca92-7ceb-11ed-9ba4-ce1bdd7cf1e9", "kind": "statement"}, "session_info": ""}
2022/12/16 10:45:18.037141 +0800 INFO frontend/util.go:514 time of Exec.Build : 20.566583ms
2022/12/16 10:45:18.049746 +0800 INFO frontend/util.go:514 time of Exec.Run : 3.039ms
2022/12/16 10:45:18.064549 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 4294967295, "statement": "select rp.privilege_id, rp.with_grant_option from mo_catalog.mo_database as d cross join mo_catalog.mo_role_privs as rp where d.dat_id = rp.obj_id and rp.obj_type = \"database\" and rp.role_id = 0 and rp.privilege_id = 23 and rp.privilege_level = \"d\" and d.datname = \"benchbase\"", "status": "success", "span": {"trace_id": "ad02f9d6-7ceb-11ed-9ba4-ce1bdd7cf1e9", "kind": "statement"}, "session_info": ""}
2022/12/16 10:45:18.075272 +0800 INFO frontend/util.go:514 time of Exec.Build : 10.584542ms
2022/12/16 10:45:18.075666 +0800 INFO frontend/util.go:514 time of Exec.Run : 303.291µs
2022/12/16 10:45:18.075703 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 4294967295, "statement": "select rp.privilege_id, rp.with_grant_option from mo_catalog.mo_role_privs as rp where rp.obj_id = 0 and rp.obj_type = \"database\" and rp.role_id = 0 and rp.privilege_id = 23 and rp.privilege_level = \"*\"", "status": "success", "span": {"trace_id": "ad0a50be-7ceb-11ed-9ba4-ce1bdd7cf1e9", "kind": "statement"}, "session_info": ""}
2022/12/16 10:45:18.075760 +0800 INFO frontend/util.go:499 query trace status {"connection_id": 4294967295, "statement": "commit", "status": "success", "span": {"trace_id": "ad0c0198-7ceb-11ed-9ba4-ce1bdd7cf1e9", "kind": "statement"}, "session_info": ""}
2022/12/16 10:45:18.077407 +0800 ERROR frontend/util.go:524 get database benchbase error ExpectedEOB connectionId 1177
github.com/matrixorigin/matrixone/pkg/frontend.logErrorf
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/util.go:524
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/session.go:1620
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/session.go:1653
github.com/matrixorigin/matrixone/pkg/sql/plan.buildDropTable
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/plan/build_ddl.go:649
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/sql/plan/build.go:82
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2402
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2204
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3409
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3878
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine.go:165
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /Users/sudong/Program/MatrixOrigin/matrixone/pkg/frontend/routine_manager.go:290
github.com/fagongzi/goetty/v2.(*server).doConnection
        /Users/sudong/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /Users/sudong/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
2022/12/16 10:45:18.078439 +0800 INFO frontend/util.go:514 time of Exec.Build : 2.659708ms connectionId 1177
2022/12/16 10:45:18.078472 +0800 INFO frontend/util.go:514 time of Exec.Run : 12.583µs connectionId 1177
2022/12/16 10:45:18.078487 +0800 INFO frontend/util.go:514 time of SendResponse 250ns connectionId 1177
[server.eof.log](https://github.com/matrixorigin/matrixone/files/10242357/server.eof.log)

**Comment by daviszhen** [comment]
After discussion with @aressu1985, we get two points:
1, It is right for the mo to report the database "benchbase" is non-existent. Because the database 'benchbase' does not exist actually.
2, the "ExpectedEOB" is really unreadable and unacceptable.  CN and DN fellows should promote its readability in the future version.

**Comment by domingozhang** [comment]
@daviszhen Suggest use error message of mysql for invalid database:
ERROR 1049 (42000): Unknown database 'ssb'

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
未投入

**Comment by sukki37** [comment]
This issue has been inactive for a while. Based on the recent updates and changes in the project, this problem has been resolved or is no longer relevant.

I am going to close this issue. If anyone still experiences this problem or has further concerns, please feel free to reopen the issue or create a new one.
