### ISSUE TITLE
[Bug]: show grants result error

### ISSUE THREAD

**Issue by mklzl** [matrixorigin/matrixone#7229]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):638358 on k8s
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sql
mysql> create role role1;
Query OK, 0 rows affected (0.16 sec)

mysql> grant all on table *.* to role1;
Query OK, 0 rows affected (0.10 sec)

mysql> grant create table, drop table on database *.* to role1;
Query OK, 0 rows affected (0.16 sec)

mysql> create user user1 identified by 'pass1';
Query OK, 0 rows affected (0.22 sec)

mysql>  grant role1 to user1;
Query OK, 0 rows affected (0.28 sec)

mysql> show grants for 'user1'@'localhost';
+---------------------------------------+
| Grants for test@localhost             |
+---------------------------------------+
| GRANT*ONaccount`user1`@`localhost`    |
| GRANT*.*ONtable`user1`@`localhost`    |
| GRANT*.*ONdatabase`user1`@`localhost` |
| GRANT*.*ONdatabase`user1`@`localhost` |
+---------------------------------------+
4 rows in set (0.11 sec)

```

It looks like there's something wrong with the formatting of the results and results has error info

### Expected Behavior

```sql
> create role role1;
> grant all on table *.* to role1;
> grant create table, drop table on database *.* to role1;
> create user user1 identified by 'pass1';
> grant role1 to user1;
> show grants for 'user1'@'localhost';
+--------------------------------------------------------+
| Grants for user1@localhost                             |
+--------------------------------------------------------+
| GRANT connect ON account  `user1`@`localhost`          |
| GRANT table all ON table *.* `user1`@`localhost`       |
| GRANT create table ON database *.* `user1`@`localhost` |
| GRANT drop table ON database *.* `user1`@`localhost`   |
+--------------------------------------------------------+
4 rows in set (0.00 sec)
```

**Comment by YANGGMM** [comment]
can you check it now？ @mklzl
i get the answer in mo as following:
 mysql> show grants for 'user1'@'localhost';
+--------------------------------------------------------+
| Grants for user1@localhost                             |
+--------------------------------------------------------+
| GRANT connect ON account  `user1`@`localhost`          |
| GRANT table all ON table *.* `user1`@`localhost`       |
| GRANT create table ON database *.* `user1`@`localhost` |
| GRANT drop table ON database *.* `user1`@`localhost`   |

**Comment by YANGGMM** [comment]
can i ask which database do you use to get the Expected Behavior, i get syntax  erroe when i use mysql8.0 @mklzl

**Comment by mklzl** [comment]
sry , I have COVID-19，i used mysql5.7

**Comment by YANGGMM** [comment]
> sry , I have COVID-19，i used mysql5.7

i am sorry  to hear that, but i can get the correct answer using mo, can you recheck it when you get better?

**Comment by domingozhang** [comment]
@aressu1985 please close it
