### ISSUE TITLE
[Bug]: context deadline exceeded when batch insert tpcc data by preparestmt.executeBatch 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7238]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):56c9590273867480f531aa0ee4c539d956e09c4e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when load tpcc data into mo by CHbenchMark test tool,  operation is failed by context deadline exceeded.
because this issue is produced by test tool , here just pasted the core code  . And if want to reproduce, pls contact me
because this test toos has still be in debugging:

[TPCCLoader.java.tar.gz](https://github.com/matrixorigin/matrixone/files/10244476/TPCCLoader.java.tar.gz)

### Steps to Reproduce

```Markdown
pls contact me to get the code
because this test toos has still be in debugging
```

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
i will try to reproduce tomorrow

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
not working on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
not work on it today

**Comment by ouyuanning** [comment]
i think when incrCache was set. maybe this bug was fixed.

**Comment by iceTTTT** [comment]
Waiting the solve of bug #7767

**Comment by jensenojs** [comment]
Not working on

**Comment by jensenojs** [comment]
Not working on

**Comment by jensenojs** [comment]
Not working on

**Comment by jensenojs** [comment]
No process

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
On leave of absence

**Comment by nnsgmsone** [comment]
context问题等彭正的context重构结束后，然后再看是否还存在问题。

**Comment by nnsgmsone** [comment]
麻烦重构结束后再转给赛赛或者测试，让他测测是否还存在这个问题 @daviszhen

**Comment by daviszhen** [comment]
@nnsgmsone context 已经重构完成了。

**Comment by daviszhen** [comment]
@taofengliu 用最新的代码复现下看看

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
明天会跟陶峰讨论下计划，

**Comment by taofengliu** [comment]
work on it soon

**Comment by aressu1985** [comment]
repro steps:
1.git clone https://github.com/](https://github.com/aressu1985/mo-tpcc.git
2.run ./runLoader props.mo warehouse 1

**Comment by taofengliu** [comment]
work on it soon

**Comment by taofengliu** [comment]
context deadline exceeded then panic
![2023-04-12 15-34-29 的屏幕截图](https://user-images.githubusercontent.com/81315978/231389194-31145b49-4ff5-4a00-8a29-878a0d913bd3.png)
![2023-04-12 15-47-06 的屏幕截图](https://user-images.githubusercontent.com/81315978/231389206-ce03f091-9013-408e-88bd-01bf3a7bbec2.png)

**Comment by taofengliu** [comment]
Update code then run again.
context deadline exceeded but did not panic
![2023-04-12 17-34-43 的屏幕截图](https://user-images.githubusercontent.com/81315978/231418228-eb8947b5-6e66-4177-982a-282c495c924b.png)

**Comment by taofengliu** [comment]
working on it

**Comment by taofengliu** [comment]
working on it

**Comment by taofengliu** [comment]
working on it

**Comment by taofengliu** [comment]
working on it

**Comment by daviszhen** [comment]
跟#8042  类似的问题。

**Comment by daviszhen** [comment]
复现中

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
1，昨天白天，用runLoader没有复现出问题。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/ead61afc-5353-4185-90fb-ddecb2e57f34)

2，昨天晚上用runBenchmark.sh来复现。跑出一些"context deadline exceeded"问题。

有几大类
A，failed to query tasks
![Screenshot from 2023-05-22 10-51-32](https://github.com/matrixorigin/matrixone/assets/60595215/97baa9b7-d3ee-4270-a3b7-4dd4a95c9db4)

![Screenshot from 2023-05-22 11-07-46](https://github.com/matrixorigin/matrixone/assets/60595215/77f1223d-0df4-4d34-9827-873421a1a169)



B，failed to allocate task
![Screenshot from 2023-05-22 11-03-47](https://github.com/matrixorigin/matrixone/assets/60595215/ac42d864-9fa9-40f5-8770-5de430e88374)

hakeeper/task/task_scheduler.go

![Screenshot from 2023-05-22 11-01-23](https://github.com/matrixorigin/matrixone/assets/60595215/3be80476-7fe4-48ba-9363-1f4500d735eb)

**Comment by daviszhen** [comment]
A，B类问题跟issue #8042 。用pr #9371 延长超时时间。

**Comment by daviszhen** [comment]
D可能是frontend的ctx有问题。
会用pr #9220 ，#8520的修改，再测试。

**Comment by daviszhen** [comment]
昨天基于上面的分析。做了一些修改，见分支：https://github.com/daviszhen/matrixone/tree/0522-debug-7238
在此分支上，跑了tpcc 11小时。出现的所有"context deadline exceeded"的错误如下。

从结果看，A类和B类的问题已经没有出现了。但是延长超时时间只是大幅度降低频率。没有杜绝A类和B类问题的再出现。

C类问题还有。需要再延长超时时间。



![Screenshot from 2023-05-23 10-00-59](https://github.com/matrixorigin/matrixone/assets/60595215/dfbc1e94-77ba-4dc8-a09f-d30d05a95ee9)

**Comment by daviszhen** [comment]
今天上午，在昨天的基础上做了修改。见分支上最新的commit: https://github.com/daviszhen/matrixone/tree/0522-debug-7238

重新跑了tpcc测试。

结果mo卡住。卡住在初始化事务时，同步logtail。

![Screenshot from 2023-05-23 10-00-59](https://github.com/matrixorigin/matrixone/assets/60595215/72f937e1-a2bd-468a-b1bd-21fd329c8ae9)

**Comment by daviszhen** [comment]
此外，context deadline都修改并验证了。这些修改都是从main取的。不需要再合并到main了。
整体上这个issue就结束了。

**Comment by aressu1985** [comment]
fixed
