### ISSUE TITLE
[Bug]: loop execute load data, load data execute time elongate.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7240]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b2adc7c61dd2895d4e1601a7efe534b0bf499220
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="548" alt="截屏2022-12-16 18 01 30" src="https://user-images.githubusercontent.com/39303074/208073825-acd2e030-258b-4a4e-baf9-ae67d81f7a55.png">

**Comment by DanielZhangQD** [comment]
When I load data `partsupp.tbl` (about 1.1GB) generated from TPCH -s10, it takes about 18min to finish, even if I truncate the table before loading data, it still takes a very long time. @jianwan0214

**Comment by tianyahui-python** [comment]
Wait for server test......

**Comment by tianyahui-python** [comment]
in the test

**Comment by tianyahui-python** [comment]
in the test

**Comment by JackTan25** [comment]
the same with #7870

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
this week give the delete pr

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
need batch reuse

**Comment by JackTan25** [comment]
need mochen's batch reuse

**Comment by JackTan25** [comment]
need mochen's batch reuse

**Comment by domingozhang** [comment]
fixed , please verify

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/236118747-e00c6359-c437-4bc9-8cd9-617fd7e7ffb9.png)

**Comment by JackTan25** [comment]
wait pessmistic transaction

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
已经修复。可以测试  @Ariznawlll

**Comment by Ariznawlll** [comment]
testing

**Comment by Ariznawlll** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/108530700/ffab525e-e750-4126-9d07-81eb6da449a7)

tetest done!
