### ISSUE TITLE
[Bug]: load jsonline error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#7241]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.6.0 
- Hardware parameters:
- OS type: 
- Others: docker version
```

### Actual Behavior

A jsonline file with such structure:

```
["Name", "Session", "Score", "Completed"]
["Gilbert", "2013", 24, true]
["Alexa", "2013", 29, true]
["May", "2012B", 14, false]
["Deloise", "2012A", 19, true] 
```

```
mysql> create table t5(name varchar(100), session varchar(100), score int, completed bool);
mysql> load data infile {'filepath'='/ssb-dbgen-path/example_array.jsonl','format'='jsonline','jsondata'='array'} into table t5;      
ERROR 20101 (HY000): internal error: the input value 'Score' is not int32 type for column 2
mysql> load data infile {'filepath'='/ssb-dbgen-path/example_array.jsonl','format'='jsonline','jsondata'='array'} into table t5 IGNORE 1 LINES;;
Query OK, 4 rows affected (0.33 sec)

ERROR: 
No query specified

```

1. if we just load it with all 5 rows, it will report column type doesn't match. But jsonline doesn't always have each schema record aligned. how can we define a schema for that?
2. If we ignore the 1 row, and we load it with a schema for the four next rows, the load works but with a strange ERROR of "No query specified."

**Comment by mooleetzi** [comment]
1. I have no idea now.
2. the reasen for  `No query specified` is sql contains two semicolons.

**Comment by dengn** [comment]
we specified in the documentation that MatrixOne 0.6 only supports structured jsonlines with same data types and column numbers for each json.
