### ISSUE TITLE
[Bug]: create non sys tenant some bvt case errors

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7248]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):main:783b96f7ce88b88733b7d933c3e79f60b97cabb9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
In order to test more non sys tenant, run bvt case. bvt case rate 73%, Some errors are expected to be ignored,
Other error cases are problems , summarized as follows about :
1. insert delete and select cannot find the table after creating the table
2. drop table t3 internal error: Only CREATE of DDL is supported in transactions
3. not supported: function or operator 'median','curdate'
![image](https://user-images.githubusercontent.com/113406637/208279007-c7f4a613-a7d8-4cd9-bd6b-1528fd15750a.png)

The failure case error types are summarized as follows：
[ERROR]
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/auto_increment/auto_increment_columns.sql
[ROW    NUMBER]: 125
[SQL STATEMENT]: insert into t3(b) values ('bbb');
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
invalid input: insert table is invalid 't3'

[ERROR]
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/auto_increment/auto_increment_columns.sql
[ROW    NUMBER]: 126
[SQL STATEMENT]: select * from t3 order by a;
[EXPECT RESULT]:
a    b
11    bbb
[ACTUAL RESULT]:
SQL parser error: table "t3" does not exist

[ERROR]
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/database/system_table.sql
[ROW    NUMBER]: 6
[SQL STATEMENT]: SELECT * FROM `information_schema`.`schemata` where schema_name = 'information_schema';
[EXPECT RESULT]:
catalog_name    schema_name    default_character_set_name    default_collation_name    sql_path    default_encryption
def    information_schema    utf8mb4    utf8mb4_0900_ai_ci        NO
[ACTUAL RESULT]:
catalog_name    schema_name    default_character_set_name    default_collation_name    sql_path    default_encryption
def    information_schema    utf8mb4    utf8mb4_0900_ai_ci        NO
def    information_schema    utf8mb4    utf8mb4_0900_ai_ci        NO

[ERROR]
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/dtype/int.test
[ROW    NUMBER]: 243
[SQL STATEMENT]: delete from t2;
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
internal error: ExpectedDup: truncate 280160 error

[ERROR]
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/function/func_aggr_median.test
[ROW    NUMBER]: 1
[SQL STATEMENT]: select median(null);
[EXPECT RESULT]:
median(null)
null
[ACTUAL RESULT]:
not supported: function or operator 'median'

[ERROR]   
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/function/func_datetime_curdate.test
[ROW    NUMBER]: 4
[SQL STATEMENT]: select cast(now() as date)=curdate() q from t1;
[EXPECT RESULT]:
q
true
true
true
[ACTUAL RESULT]:
not supported: function or operator 'curdate'

[ERROR]
[SCRIPT   FILE]: /Users/heni/matrixone/test/distributed/cases/load_data/import_data.sql
[ROW    NUMBER]: 107
[SQL STATEMENT]: drop table t3;
[EXPECT RESULT]:
null
[ACTUAL RESULT]:
internal error: Only CREATE of DDL is supported in transactions

### Steps to Reproduce

```Markdown
create a new account ：
create account if not exists test ADMIN_NAME 'adminuser' IDENTIFIED BY '123456' comment 'account comment';
alter mo-tester mo.yaml user parameter such as test:adminuser and run 


```

**Comment by heni02** [comment]
[mo-tester-report.zip](https://github.com/matrixorigin/matrixone/files/10253147/mo-tester-report.zip)
mo-server log exceeds the upload size limit. It will be passed to you privately @daviszhen

**Comment by florashi181** [comment]
adjust cases first

**Comment by aressu1985** [comment]
test tomorrow

**Comment by aressu1985** [comment]
tracked by #7898，#7896，#7898
