### ISSUE TITLE
[Bug]: JSON_EXTRACT can't be used in WHERE clause with operators

### ISSUE THREAD

**Issue by EZ4BRUCE** [matrixorigin/matrixone#7253]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): commit-dabdae1
- Hardware parameters: default
- OS type: macOS Ventura 13.0.1
- Others: running on Docker Desktop 4.14.1 (docker engine 20.10.21)
```

### Actual Behavior

As you see, `labels` is a json field:
```sql
create database mo_ob;
create table mo_ob.metric (
   module_name  VARCHAR(1024),
   module_uuid  VARCHAR(36),
   matric_name  VARCHAR(1024),
   timstamp     DATETIME(6),
   labels       JSON,
   value        DOUBLE
);
```
add some data:
```sql
INSERT INTO mo_ob.metric 
VALUES 
('test0','id1','mem',now(),'{"lb1":2,"lb2":2.1,"lb3":"valxx"}',90.9),
('test0','id2','cpu',now(),'{"lb1":2,"lb2":2.1,"lb3":"val3"}',90.9),
('test0','id3','mem',now(),'{"lb1":4,"lb2":2.1,"lb3":"valyy"}',90.9);
select * from mo_ob.metric;
```
and when i try to select some metric with 
```sql
select  matric_name from mo_ob.metric where JSON_EXTRACT(labels, '$.lb3')="val3" ;
# or
select  matric_name from mo_ob.metric where JSON_EXTRACT(labels, '$.lb3') like "val3";
```
none of these sqls work, as i receive a problem from mo (with mysql client) says:
```bash
ERROR 20203 (HY000): invalid argument operator =, bad value [JSON VARCHAR]
# or
ERROR 20203 (HY000): invalid argument operator like, bad value [JSON VARCHAR]
```

### Expected Behavior

reutrn exactly columns which match the WHERE clause with JSON_EXTRACT.

in this example, which is: 
```
('test0','id2','cpu',now(),'{"lb1":2,"lb2":2.1,"lb3":"val3"}',90.9),
```

**Comment by mooleetzi** [comment]
json compare with other types need more time to implement, after 0.7 features done, I will handle it.
if #7273 merged, you can try select  matric_name from mo_ob.metric where JSON_EXTRACT(labels, '$.lb3')=json_quote("val3"); temporarily

**Comment by mooleetzi** [comment]
> @mooleetzi is that `json_unquote` a better way to fix ?

ah, yes. if json_unquote, both like and eq with string work. thx.

**Comment by xzxiong** [comment]
> > @mooleetzi is that `json_unquote` a better way to fix ?
> 
> ah, yes. if json_unquote, both like and eq with string work. thx.

i believe those int/bool/... value in json have the same error outcome. Is that will be work with calling `json_unquote` ?

**Comment by mooleetzi** [comment]
> > > @mooleetzi is that `json_unquote` a better way to fix ?
> > 
> > 
> > ah, yes. if json_unquote, both like and eq with string work. thx.
> 
> i believe those int/bool/... value in json have the same error outcome. Is that will be work with calling `json_unquote` ?

most of them should work fine since we have many cast case with string-like type. but it may not be the final solution because json_unquote returns string and there are much conversion in comparation with non-string type, slow if so i guess. json_unquote or cast to string is the last case if convert to other non-string type failed.

**Comment by xzxiong** [comment]
thx.
if go with `json_unquote`, when it would be fixed ?
we rely on it to implement MOCloud's feature in 0.7

**Comment by mooleetzi** [comment]
em, ok.  I will make json_unquote pr tomorrow.

**Comment by EZ4BRUCE** [comment]
> em, ok. I will make json_unquote pr tomorrow.

is there any use case or example of 'json_unquote' about your implement?

**Comment by EZ4BRUCE** [comment]
> em, ok. I will make json_unquote pr tomorrow.

@mooleetzi 
is there any use case or example of 'json_unquote' about your implement? thanks!

**Comment by mooleetzi** [comment]
@EZ4BRUCE pls take a look at https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-unquote

**Comment by EZ4BRUCE** [comment]
> @EZ4BRUCE pls take a look at https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-unquote

okay, thank you, that helps a lot
