### ISSUE TITLE
[Bug]: jsonline load GZIP/BZIP2 error

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#7260]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.6.0
- Hardware parameters:
- OS type:
- Others: docker
```

### Actual Behavior

mysql> create table t1(col1 bool,col2 int,col3 varchar, col4 date,col5 datetime,col6 timestamp,col7 decimal,col8 float);
mysql> load data infile {'filepath'='/ssb-dbgen-path/jsonline_array.jl.bz2','compression'='BZIP2','format'='jsonline','jsondata'='array'} into table t1;
ERROR 20101 (HY000): internal error: the compress type 'BZIP2' is not support now
mysql> load data infile {'filepath'='/ssb-dbgen-path/jsonline_array.jl.zip','compression'='GZIP','format'='jsonline','jsondata'='array'} into table t1;
ERROR 1105 (HY000): gzip: invalid header

[jsonline_array.jl.zip](https://github.com/matrixorigin/matrixone/files/10257878/jsonline_array.jl.zip)
[jsonline_array.jl.bz2.zip](https://github.com/matrixorigin/matrixone/files/10257881/jsonline_array.jl.bz2.zip)

The jsonline_array.jl.zip is compressed from macOS right click menu compression.
The jsonline_array.jl.bz2 is compressed with command:
```
bzip2 jsonline_array.jl
```

**Comment by dengn** [comment]
> <img alt="image" width="911" src="https://user-images.githubusercontent.com/32733096/210311234-3a49ec24-bcc7-4100-b6e8-7c856d971fc4.png">
> 
> we don' t support zip compression format file.

it's not about zip, but BZIP2 and GZIP.

**Comment by mooleetzi** [comment]
pr merged, pls test.

**Comment by dengn** [comment]
mysql>  load data infile {'filepath'='/root/mo20221229/a2.jsonl.bz2', 'compression'='BZIP2','format'='jsonline','jsondata'='array'} into table t1 ignore 1 lines;
Query OK, 4 rows affected (0.01 sec)
mysql>  load data infile {'filepath'='/root/mo20221229/a3.jsonl.gz', 'compression'='GZIP','format'='jsonline','jsondata'='array'} into table t1 ignore 1 lines; 
Query OK, 4 rows affected (0.01 sec)

fixed
