### ISSUE TITLE
[Enhancement]: use zonemap info to speed up aggregate 'Count'

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#7263]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
1. dn support null count info.
2. cn use zone map to speed up.

min, and max is also can be speed up, but we only consider the count at 0.7
```

**Comment by m-schen** [comment]
@XuPeng-SH dn need a teammate to trace that.
@nnsgmsone I'm not sure which mate of cn to do that. so I assign you and me.

**Comment by nnsgmsone** [comment]
Why is our count so slow. That's what we should need to focus on first. Instead of choosing a tricky way to get around it. We should face up to the problem of slow count.

**Comment by nnsgmsone** [comment]
I don't think that makes sense for this stage.

**Comment by fengttt** [comment]
If zonemap has enough data to answer the query, we should use.   It is simply a better access path.

**Comment by fengttt** [comment]
So most likely we need some planning work.   I think, we should have push down 1st stage aggregate into reader.   So we have new query node, AggRead or FusedRead.    Which does the following,

1. It may have a simple expression evaluation, a optional group by expression, and a list of first stage agg functions.
    - First version let's just push down simple expression, and group by must be a list of columns, no expression/function
    - limited number of agg functions (count/min/max/sum/avg), on a single column, no expression.
1. It use zonemap on the expression evaluation.    If disqualified a block, continue.
1. If 
    - the zonemap evaluated to 'ALL' (esp, if the expression is nil, it is true for ALL).    
    - AND If groupby expr is nil, or, the grouped by col is a constant (this can also be answered by zonemap)
    - AND If agg can be answered by zonemap
    - use zonemap only 
1. Else
    - Read columns, compute agg
   
Note that the *if* and *else* branch of the code, output schema is the same and we can *verify* if branch result by checking the else branch.

**Comment by aunjgr** [comment]
Don't do rewriting at the stage of binding. Add a new optimizing rule.

1. The original TableScan node should have no filter
2. The original Agg node should have no GroupBy

**Comment by zengyan1** [comment]
https://github.com/matrixorigin/matrixone/pull/11959，已合入，测试将由https://github.com/matrixorigin/MO-Cloud/issues/248跟进

**Comment by m-schen** [comment]
收到，可关闭。
