### ISSUE TITLE
[Feature Request]: parallel load with external table 

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7264]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
when we load a table, we will essentially do

insert into select * from exttable;

When ext table source has many files, we can run the process in parallel.  
However if we have one giant file, we cannot parallelize the load
```

### Describe the feature you'd like

For a well-formed large file, for example, jsonline or csv without newline in quote, we can 
parallelize the load:  seek to a position, for example 1G.   find first new line, then load
from the new line, till the first new line after 2G.    This way we can load 1G for every thread.

For CSV, only enable this optimization with an option.  RECORD_PER_LINE?   
For JsonLine, new line is record separator by spec.

**Comment by fengttt** [comment]
S-1 now because this blocks test and customer installation.

**Comment by aressu1985** [comment]
test done
