### ISSUE TITLE
[Enhancement]: use zonemap info to speed up 'ORDER BY ... LIMIT n'

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#7265]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
may the zonemap info can help us to reduce push some blocks.
```

**Comment by m-schen** [comment]
it's just a record for the things now. after mochen back and I will have a short discussion with him.

**Comment by nnsgmsone** [comment]
I don't think that makes sense for this stage.
