### ISSUE TITLE
[Bug]: bvt can't recognize the output of mo_ctl flush

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#7274]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
the generated result file is used, but error still happens

![a1949f93c1912726365d4c5a95a04b1](https://user-images.githubusercontent.com/49832303/208801634-c392d585-2c69-4564-8939-7fb33ccf26a0.png)

### Expected Behavior

mo-tester should compare the output of mo_ctl successfully

**Comment by fengttt** [comment]
eh, what is the error?   should this be handled by writing correct sql?

**Comment by aptend** [comment]
> eh, what is the error? should this be handled by writing correct sql?

The description is updated. And before opening this issue, it has been confirmed by @aressu1985

**Comment by aptend** [comment]
solution:
```
-- @separator:table
select mo_ctl('dn', 'flush', 'db1.t');
```
