### ISSUE TITLE
[Bug]: prepare execution result is not the same as before.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7278]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE numbers
(pk INTEGER PRIMARY KEY,
 ui BIGINT UNSIGNED,
 si BIGINT
);

INSERT INTO numbers VALUES
(0, 0, -9223372036854775808), (1, 18446744073709551615, 9223372036854775807);

SELECT * FROM numbers WHERE ui=-9223372036854775808;

SET @si_min = -9223372036854775808;
PREPARE s1 FROM 'SELECT * FROM numbers WHERE ui=?';
EXECUTE s1 USING @si_min;
DEALLOCATE PREPARE s1;

<img width="1236" alt="截屏2022-12-21 09 44 15" src="https://user-images.githubusercontent.com/39303074/208812490-12f370da-56fa-4926-b134-e9eb25505554.png">

**Comment by badboynt1** [comment]
the root cause is -9223372036854775808.  we cast 9223372036854775808 it to decimal 128, and then -9223372036854775808 is decimal 128.
-1 to -9223372036854775807 is int64.
hard to change this

**Comment by badboynt1** [comment]
no solution

**Comment by badboynt1** [comment]
no solution

**Comment by badboynt1** [comment]
no solution

**Comment by badboynt1** [comment]
no solution

**Comment by badboynt1** [comment]
no solution

**Comment by badboynt1** [comment]
no solution

**Comment by badboynt1** [comment]
no solution

**Comment by ouyuanning** [comment]
that seems: when get ? value (when execute prepare), we will get different value from excute 'ui=-9223372036854775808'

we should do that in same rule.

**Comment by ouyuanning** [comment]
pr is reviewing

**Comment by ouyuanning** [comment]
pr is reviewing

**Comment by tianyahui-python** [comment]
<img width="1425" alt="截屏2023-03-17 10 11 13" src="https://user-images.githubusercontent.com/39303074/225794274-e61a4693-66cc-4d29-9ae5-6e2f7b4c3943.png">
