### ISSUE TITLE
[Bug]: load jsonline doesn't support null

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#7295]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.6
- Hardware parameters:
- OS type:
- Others: docker
```

### Actual Behavior

mysql> load data infile {'filepath'='/ssb-dbgen-path/example_array3.jsonl','format'='jsonline','jsondata'='array'} into table t2 ignore 1 lines;
ERROR 20101 (HY000): internal error: the input value '<nil>' is not bool type for column 3

create table t2 (name varchar(100), session varchar(100), score int, completed bool);

example_array3.jsonl: 
["Name", "Session", "Score", "Completed"]
["Gilbert", "2013", 24, true]
["Alexa", "2013", 29, false]
["May", "2012B", 14, null]
["Deloise", "2012A", 19, true]

**Comment by mooleetzi** [comment]
fixed by #7254

**Comment by mooleetzi** [comment]
fixed, pls test

**Comment by dengn** [comment]
will test

**Comment by dengn** [comment]
fixed. 

```
mysql> create table t2(a varchar(20), b varchar(20), c int, d bool);
Query OK, 0 rows affected (0.02 sec)

mysql> load data infile {'filepath'='/root/mo20221229/a.jsonl','format'='jsonline','jsondata'='array'} into table t2 ignore 1 lines;
Query OK, 4 rows affected (0.01 sec)

mysql> select * from t2;
+---------+-------+------+-------+
| a       | b     | c    | d     |
+---------+-------+------+-------+
| Gilbert | 2013  |   24 | true  |
| Alexa   | 2013  |   29 | false |
| May     | 2012B |   14 | NULL  |
| Deloise | 2012A |   19 | true  |
+---------+-------+------+-------+
4 rows in set (0.00 sec)
```
