### ISSUE TITLE
[Feature Request]: Support a second login delimiter with MySQL client

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7300]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Use 'account.user.role' as the parameter of -u in mysql client. For example:

mysql -u 'default.root.admin' -h 127.0.0.1 -P 6001 -p

Then user will log in default account as root user with admin role.

**Comment by daviszhen** [comment]
'#' is provided.
