### ISSUE TITLE
[Feature Request]: Support REPLACE function

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7333]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

REPLACE(string, from_string, new_string)

Replace from_string in string with new_string 

Example:
mysql> SELECT REPLACE("XYZ FGH XYZ", "X", "M");
+----------------------------------+
| REPLACE("XYZ FGH XYZ", "X", "M") |
+----------------------------------+
| MYZ FGH MYZ                      |
+----------------------------------+
1 row in set (0.00 sec)

mysql> select * from t2;
+--------------+
| a            |
+--------------+
| Anewtestcase |
+--------------+
1 row in set (0.00 sec)

select replace(a,"test","user") from t2;
+--------------------------+
| replace(a,"test","user") |
+--------------------------+
| Anewusercase             |
+--------------------------+
1 row in set (0.00 sec)

**Comment by heni02** [comment]
@Ariznawlll  test done ,pr merged
