### ISSUE TITLE
[Bug]: load data with escape by has no effect

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#7341]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Two problems: 
1. ESCAPE BY seems not working.
2. The line with """· is different between MySQL and MO.

In MO, 

mysql> create table t1(col1 char(225), col2 varchar(225), col3 text, col4 varchar(225));
Query OK, 0 rows affected (0.11 sec)

mysql> load data infile '/ssb-dbgen-path/data/char_varchar_1.csv' into table t1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' LINES STARTING BY '';
Query OK, 21 rows affected (0.09 sec)

mysql> select * from t1;
+-----------+-----------+-----------+----------------+
| col1      | col2      | col3      | col4           |
+-----------+-----------+-----------+----------------+
| a         | b         | c         | d              |
| a         | b         | c         | d              |
| 'a'       | 'b'       | 'c'       | 'd'            |
| 'a'       | 'b'       | 'c'       | 'd'            |
| aa,aa     | bb,bb     | cc,cc     | dd,dd          |
| aa,       | bb,       | cc,       | dd,            |
| aa,,,aa   | bb,,,bb   | cc,,,cc   | dd,,,dd        |
| aa',',,aa | bb',',,bb | cc',',,cc | dd',',,dd      |
| aa"aa     | bb"bb     | cc"cc     | dd"dd          |
| aa"aa     | bb"bb     | cc"cc     | dd"dd          |
| aa"aa     | bb"bb     | cc"cc     | dd"dd          |
| aa""aa    | bb""bb    | cc""cc    | dd""dd         |
| aa""aa    | bb""bb    | cc""cc    | dd""dd         |
| aa",aa    | bb",bb    | cc",cc    | dd",dd         |
| aa"",aa   | bb"",bb   | cc"",cc   | dd"",dd        |
|           |           |           |                |
|           |           |           |                |
| NULL      | NULL      | NULL      | NULL           |
|           |           |           |                |
| "         | "         | "         | "              |
| ""        | ""        | ""        | """·
\,\,\,\
  |
+-----------+-----------+-----------+----------------+
21 rows in set (0.03 sec)

In MySQL:
mysql> load data infile '/Users/nandeng/Test/docker_loaddata_demo/data/char_varchar_1.csv' into table t1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' LINES STARTING BY '';               
Query OK, 21 rows affected (0.08 sec)
Records: 21  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from t1;
+-----------+-----------+-----------+-------------+
| col1      | col2      | col3      | col4        |
+-----------+-----------+-----------+-------------+
| a         | b         | c         | d           |
| a         | b         | c         | d           |
| 'a'       | 'b'       | 'c'       | 'd'         |
| 'a'       | 'b'       | 'c'       | 'd'         |
| aa,aa     | bb,bb     | cc,cc     | dd,dd       |
| aa,       | bb,       | cc,       | dd,         |
| aa,,,aa   | bb,,,bb   | cc,,,cc   | dd,,,dd     |
| aa',',,aa | bb',',,bb | cc',',,cc | dd',',,dd   |
| aa"aa     | bb"bb     | cc"cc     | dd"dd       |
| aa"aa     | bb"bb     | cc"cc     | dd"dd       |
| aa"aa     | bb"bb     | cc"cc     | dd"dd       |
| aa""aa    | bb""bb    | cc""cc    | dd""dd      |
| aa""aa    | bb""bb    | cc""cc    | dd""dd      |
| aa",aa    | bb",bb    | cc",cc    | dd",dd      |
| aa"",aa   | bb"",bb   | cc"",cc   | dd"",dd     |
|           |           |           |             |
|           |           |           |             |
| NULL      | NULL      | NULL      | NULL        |
|           |           |           |             |
| "         | "         | "         | "           |
| ""        | ""        | ""        | """"·
,,,
  |
+-----------+-----------+-----------+-------------+
21 rows in set (0.01 sec)

Data file:
[char_varchar_1.csv](https://github.com/matrixorigin/matrixone/files/10308052/char_varchar_1.csv)

**Comment by fengttt** [comment]
These are not essential features -- not standard csv.   But, if you support the option in sql, you better implement it correctly.   Or just fail with not supported yet.

**Comment by daviszhen** [comment]
直接报错

**Comment by dengn** [comment]
Verified. 

mysql> load data infile '/load-data/data/char_varchar_1.csv' into table t1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' LINES STARTING BY '';
ERROR 20300 (HY000): invalid configuration: load operation do not support EscapedBy field.
