### ISSUE TITLE
[Bug]: Fail to kill query

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#7349]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 53cdee6379b4a711f0600d7260e68088c9744b9a
- Hardware parameters:
- OS type: macos
- Others:
```

### Actual Behavior

Run the following query:
```
mysql> select connection_id();
+-----------------+
| connection_id() |
+-----------------+
|            1100 |
+-----------------+
1 row in set (0.01 sec)
mysql> use system_metrics;
mysql> select * from metric as s3 inner join sql_statement_total as s5 on s3.account = s5.account;
```
Kill the query in another session:
```
mysql> kill query 1100;
```

The query cannot be killed for more than 1 hour.

### Expected Behavior

The query is killed successfully.

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`.
```

### Additional information
```
mysql> select count(*) from metric;
+----------+
| count(*) |
+----------+
|    25401 |
+----------+
1 row in set (0.21 sec)

mysql> select count(*) from sql_statement_total;
+----------+
| count(*) |
+----------+
|    11039 |
+----------+
1 row in set (0.18 sec)
```

**Comment by daviszhen** [comment]
After the context has been cancelled,  the computation is also working.

**Comment by DanielZhangQD** [comment]
Another test:
Kill the query and get the following logs:
```
2023/02/06 14:32:47.271460 +0800 ERROR logging/api.go:59 execute query error: Error 20101 (HY000): internal error: pipeline closed unexpectedly
```

Check the statement info, it still shows `Running`:
```
mysql> select statement_id, statement, request_at, error,status from system.statement_info where statement_id = 'f1263e14-a5e7-11ed-8edf-1e00ea3e7481';
+--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+-------+---------+
| statement_id                         | statement                                                                                                                                                                                                                                                                 | request_at                 | error | status  |
+--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+-------+---------+
| f1263e14-a5e7-11ed-8edf-1e00ea3e7481 | select * from metric as s3 inner join metric as s5 inner join metric as s6 inner join metric as s7 inner join metric as s8 on s3.collecttime = s5.collecttime and s6.collecttime = s5.collecttime and s6.collecttime = s7.collecttime and s6.collecttime = s8.collecttime | 2023-02-06 14:31:52.023585 |       | Running |
```

**Comment by domingozhang** [comment]
A killed sql was 'success' in statement_info.status, but not failed.
![企业微信截图_16757488151284](https://user-images.githubusercontent.com/88298673/217160162-5c1ba905-1ac4-4824-b3e9-217c89e7c24b.png)

![企业微信截图_16757488237463](https://user-images.githubusercontent.com/88298673/217160077-31d2798b-2ba5-4cec-9a96-a93a43bf4372.png)

I suggest this modifed to failed .

@xzxiong

**Comment by xzxiong** [comment]
> A killed sql was 'success' in statement_info.status, but not failed. ![企业微信截图_16757488151284](https://user-images.githubusercontent.com/88298673/217160162-5c1ba905-1ac4-4824-b3e9-217c89e7c24b.png)
> 
> ![企业微信截图_16757488237463](https://user-images.githubusercontent.com/88298673/217160077-31d2798b-2ba5-4cec-9a96-a93a43bf4372.png)
> 
> I suggest this modifed to failed .
> 
> @xzxiong

in this case, it was exec `kill query <id>`, and the query `sleep(1000)` response ok and table statement_info record `status = SUCCESS`. that is correct.

if want to get `status=failed` record, then client should get response with error.

**Comment by nnsgmsone** [comment]
The kill doesn't actually kill the query, it needs to be modified by Peng Zheng

**Comment by xzxiong** [comment]
> Another test: Kill the query and get the following logs:
> 
> ```
> 2023/02/06 14:32:47.271460 +0800 ERROR logging/api.go:59 execute query error: Error 20101 (HY000): internal error: pipeline closed unexpectedly
> ```
> 
> Check the statement info, it still shows `Running`:
> 
> ```
> mysql> select statement_id, statement, request_at, error,status from system.statement_info where statement_id = 'f1263e14-a5e7-11ed-8edf-1e00ea3e7481';
> +--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+-------+---------+
> | statement_id                         | statement                                                                                                                                                                                                                                                                 | request_at                 | error | status  |
> +--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+-------+---------+
> | f1263e14-a5e7-11ed-8edf-1e00ea3e7481 | select * from metric as s3 inner join metric as s5 inner join metric as s6 inner join metric as s7 inner join metric as s8 on s3.collecttime = s5.collecttime and s6.collecttime = s5.collecttime and s6.collecttime = s7.collecttime and s6.collecttime = s8.collecttime | 2023-02-06 14:31:52.023585 |       | Running |
> ```


@DanielZhangQD  SQL status still RUNNING issue is fixed,  ptal.

**Comment by DanielZhangQD** [comment]
Verify with the latest commit aad547f1b079a979c8808335125bcbcafe5bbe8f and the query in the comment https://github.com/matrixorigin/matrixone/issues/7349#issuecomment-1418590986 cannot be killed:
```
➜  services mysql -h 127.0.0.1 -u dump -p111 -P6001
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1043
Server version: 8.0.30-MatrixOne-v0.6.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use system_metrics;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from metric as s3 inner join metric as s5 inner join metric as s6 inner join metric as s7 inner join metric as s8 on s3.collecttime = s5.collecttime and s6.collecttime = s5.collecttime and s6.collecttime = s7.collecttime and s6.collecttime = s8.collecttime;
```
Kill query in another session:
```
mysql> kill query 1043;
```
After more than 20mins, check the query status:
```
mysql> select statement, status, request_at from system.statement_info where statement_id = '7fdf6d62-ad02-11ed-8f24-1e00ea3e7482';

Connection id:    1007
Current database: system_metrics

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------+
| statement                                                                                                                                                                                                                                                                 | status  | request_at                 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------+
| select * from metric as s3 inner join metric as s5 inner join metric as s6 inner join metric as s7 inner join metric as s8 on s3.collecttime = s5.collecttime and s6.collecttime = s5.collecttime and s6.collecttime = s7.collecttime and s6.collecttime = s8.collecttime | Running | 2023-02-15 15:29:36.524049 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------+
1 row in set (0.22 sec)
```

**Comment by nnsgmsone** [comment]
ok

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by tianyahui-python** [comment]
control + c   cannot kill the sql that is being executed

![image](https://user-images.githubusercontent.com/39303074/224602281-e87608f0-e38d-4241-aa6f-a32b0599198d.png)

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等plan重构后处理这个问题

**Comment by nnsgmsone** [comment]
@DanielZhangQD please check

**Comment by DanielZhangQD** [comment]
Verified and passed with commit `nightly-84b8491c`:
```
| 5defadc2-ff62-11ed-9f14-6651be21afcd | kill query 366656                                                                                | Success | 2023-05-31 03:22:26.621907 |
| 5bdada9b-ff62-11ed-9f14-6651be21afcd | select * from metric as s3 inner join sql_statement_total as s5 on s3.account = s5.account       | Failed  | 2023-05-31 03:22:23.130058 |
```
