### ISSUE TITLE
[operators]ERROR 1105 (HY000): unknown error:[42000]* not yet implemented for DOUBLE, BIGINT

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#736]
#### Can be reproduced ?
Yes

#### Steps:
select sum(col_1d)+count(col_1d)-avg(col_1d)*min(col_1d)/max(col_1d)%min(col_1e)+max(col_1e) as sum from tbl1 group by col_1d;
also "+, -, /, %" operators does not support DOUBLE, BIGINT"

#### Expected behavior:
According to test scope of v0.1.0, they should support all defined Data Types.

#### Actual behavior:
Not support now

### Environment:
Commit-id : f2b85d3b024a04ebb3069aee8b92a110e66eba76
MySQL Client: mysql Ver 8.0.26 for macos11.4 on arm64 (Homebrew)

**Comment by m-schen** [comment]
Support plus, minus, mult, div, mod operators for each types now.
It will make type cast before the extend evaluates.
Type Cast Rule is that:
1. plus, minus, and mult.
we support basic compute function for same type family. (such as int16 + int64, float32 - float64).And the other cases will do type conversion.
 int + uint  will convert to int64 + int64
 int + float will convert to float64 + float64
 uint + float will convert to float64 + float64
2. div
 all div operator will convert to float64 / float64
3. mod
 int % int will convert to int64 % int64
 int % int will convert to int64 % int64
 uint % uint will convert to uint64 % uint64
 int % float will convert to float64 % float64
 uint % float will convert to float64 % float64
 float32 % float64 will convert to float64 % float64

**Comment by m-schen** [comment]
Also support comparison operators (=, !=, >, >=, <, <=) between each types.
Rules is that:
1.convert to int64 op int64 cases: 
 int op int, uint op int
2.convert to uint64 op uint64 cases:
 uint op uint
3.convert to float64 op float64 cases:
 int op float
 uint op float
 char op float
 float32 op float64

**Comment by m-schen** [comment]
And support NOT operator for each types.
But Not + char / varchar will do an implicit type conversion: char / varchar will convert to float first.
and not 0.0 = 1, not others = 0

**Comment by lignay** [comment]
In v0.2.0, % still not support for DOUBLE, VARCHAR. Others works well, close this issue.
