### ISSUE TITLE
[Bug]: SSB query cost with cache nearly equals to  executing in cold state 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7364]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):12752c4b04771afe89d2e28d074166b2cfc74243
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Normally,  query cost should decrease after first executing in so-called cold-state because the queries result will be cached and the following same qureries can get result just from cahce.

But for mo,   query cost after first executing do not decrease obviously, for examples , SSB Q 4.3:

first time（mo started, and do nothing）：
<img width="550" alt="image" src="https://user-images.githubusercontent.com/47846308/209897261-2304cc26-419e-41b1-837d-aee286821fd8.png">

second time:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/47846308/209897286-da7bb5c1-16b6-4c10-827f-6f5758e46a00.png">

third time:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/47846308/209897376-b34c1b1a-3bc1-43c0-b9b2-de91f656fab5.png">

**Comment by badboynt1** [comment]
i tested on 130 server
![image](https://user-images.githubusercontent.com/112734932/209901157-d9ff68de-4b4b-45bb-861b-f68fb62f8caa.png)
![image](https://user-images.githubusercontent.com/112734932/209901182-eb205248-bbba-476d-b134-51df87dc2ddf.png)

first time 18s, second time 15s, fileservice cache reduces 3s cost of reading blocks. 15s cost is on computation. we do not have result cache, so this is a expected result

**Comment by aressu1985** [comment]
#6943

**Comment by badboynt1** [comment]
not working on this

**Comment by aressu1985** [comment]
tracking it

**Comment by aressu1985** [comment]
fixed
