### ISSUE TITLE
[Bug]: sleep() function:The time when the query result is multiple

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#7367]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```
commit 60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e
launch method : ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

### Actual Behavior

SELECT name, province, sleep(2) FROM test;

mo result: 2s

### Expected Behavior

6s

### Steps to Reproduce
Table structure :
CREATE TABLE test (id int, name VARCHAR(10), province VARCHAR(100) NOT NULL, address VARCHAR(100));

SQL:
INSERT INTO test VALUES(1, '张三', '陕西', '大头村二组');
INSERT INTO test VALUES(2, '李四', '北京', '快乐村三组');
INSERT INTO test VALUES(3, '王五', '陕西', '美丽村四组');

**Comment by mooleetzi** [comment]
pls retest

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/217487279-0ed00aea-aa34-437b-a601-37f8519af515.png)
