### ISSUE TITLE
[Bug]: result is wrong of TPCH Q19 for decimal precision has been rounded

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7378]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

result of Q19 10G

MO:
revenue
38030749

SF:
REVENUE
38030748.8555

**Comment by fengttt** [comment]
not a regression/breaking daily run.    reduce to s0.

**Comment by aunjgr** [comment]
Supposed to be covered by decimal type rewriting.

**Comment by aunjgr** [comment]
No progress yet. Working on vector refactor.

**Comment by aunjgr** [comment]
No progress yet. Working on vector refactor.

**Comment by aunjgr** [comment]
Working on subquery issues

**Comment by aunjgr** [comment]
Wait for decimal rewriting

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
may be related to #7634

**Comment by aunjgr** [comment]
The type inference logic is still messy. Will get back to it after decimal rework.

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
wait for decimal rewrite

**Comment by aunjgr** [comment]
Wait for decimal pr

**Comment by aunjgr** [comment]
wait for decimal pr

**Comment by aunjgr** [comment]
It's a duplicate to #8465.

@aressu1985 Please close this one.

**Comment by aressu1985** [comment]
OK，this can be cloesed
