### ISSUE TITLE
[Bug]: The logtail after modifying the constraint is not correct.

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#7379]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After modifying the constraint, the dn is now given to cn to create a new create table (but the column information is missing).

**Comment by aptend** [comment]
working on it

**Comment by aptend** [comment]
fix pr is https://github.com/matrixorigin/matrixone/pull/7417

**Comment by aptend** [comment]
pr is merged
