### ISSUE TITLE
[Bug]: create not exists column as secondary index panic

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7384]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):a39641fb659a2c72721e53a2b66f77cc38b3fac3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table index_table_01 (col1 bigint auto_increment primary key,col2 varchar(25),col3 float default 87.01,col int,unique key num_phone(col2),key num_id(col4));
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/panic.go:260
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/sql/plan.buildTableDefs
	/Users/heni/test-envir/matrixone/pkg/sql/plan/build_ddl.go:619
github.com/matrixorigin/matrixone/pkg/sql/plan.buildCreateTable
	/Users/heni/test-envir/matrixone/pkg/sql/plan/build_ddl.go:14

![image](https://user-images.githubusercontent.com/113406637/210033042-dbbb4e64-6738-4fae-82d6-c6d7f731c70c.png)

### Steps to Reproduce

```Markdown
create table index_table_01 (col1 bigint auto_increment primary key,col2 varchar(25),col3 float default 87.01,col int,unique key num_phone(col2),key num_id(col4));
```

**Comment by bbbearxyz** [comment]
the secondary key will first support grammer, the index table is need or not will be discuss.

**Comment by bbbearxyz** [comment]
the pr is in the reviewing.

**Comment by bbbearxyz** [comment]
<img width="1791" alt="Screen Shot 2023-01-13 at 3 08 59 PM" src="https://user-images.githubusercontent.com/71327518/212258852-dc23dd6a-9787-462f-92ed-f4069774d92b.png">

**Comment by bbbearxyz** [comment]
please confirm it.

**Comment by heni02** [comment]
confirm,closed
commit id:44f1da2b5d4aa613cb66e78b8d6f33afe6151c54
![image](https://user-images.githubusercontent.com/113406637/212273025-5e470e16-6b83-487c-8461-9ee86526ebb0.png)
