### ISSUE TITLE
[Bug]: create unique index on table(col) panic

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7387]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):a39641fb659a2c72721e53a2b66f77cc38b3fac3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table create_index_01 (col1 bigint primary key,col2 varchar(25),col3 float,col4 varchar(50));
Query OK, 0 rows affected (0.03 sec)

mysql> create unique index varchar_index on create_index_01(col2) comment 'create varchar index';
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/panic.go:260
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).CreateIndex
	/Users/heni/test-envir/matrixone/pkg/sql/compile/ddl.go:317
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/Users/heni/test-envir/matrixone/pkg/sql/compile/compi

### Steps to Reproduce

```Markdown
create table create_index_01 (col1 bigint primary key,col2 varchar(25),col3 float,col4 varchar(50));
create unique index varchar_index on create_index_01(col2) comment 'create varchar index';
```

**Comment by qingxinhome** [comment]
This bug has been solved, please test！ @heni02 @bbbearxyz

**Comment by heni02** [comment]
confirm,closed
commit id:361d6bca2fc79806fc25735f8b39e03d64a455fb
![image](https://user-images.githubusercontent.com/113406637/211443216-38672b30-ae9f-4c18-81c5-7c0fb7194485.png)
