### ISSUE TITLE
[Bug]:new account after delete table, insert table reported invalid input: insert table is invalid

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7389]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):a39641fb659a2c72721e53a2b66f77cc38b3fac3
- Hardware parameters:
- OS type:
- Others:related issue #7248
```

### Actual Behavior

create a new account :create account account_1 admin_name='admin' identified by '123456'; then use account_1  login, execute delete from table, insert table reported : invalid input: insert table is invalid
![image](https://user-images.githubusercontent.com/113406637/210041616-7637598e-66d7-46a2-a13e-66f69ee9e93e.png)

### Steps to Reproduce

```Markdown
drop table if exists t3;
create table t3(
a int primary key auto_increment,
b varchar(10)
);

insert into t3 values (-19, 'aaa');
insert into t3(b) values ('bbb');
select * from t3 order by a;

delete from t3;
insert into t3(b) values ('bbb');
select * from t3 order by a;
```

**Comment by heni02** [comment]
#7248

**Comment by nnsgmsone** [comment]
The accountid given by logtail is not correct. Please contact dn colleagues to fix it.

**Comment by nnsgmsone** [comment]
logtail:
```
+++insert table: 
accountid: [0]
name: [t3]
databaseid: [272486]..
```
The accountid given after truncate is 0. So it can't be found, the accountid should be given as 1

**Comment by heni02** [comment]
comfirm,closed 
commit id:ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
![image](https://user-images.githubusercontent.com/113406637/210055684-ad638605-9642-47de-aaa3-c1f347ca35a8.png)
