### ISSUE TITLE
Support type conversion in expression evaluation

### ISSUE THREAD

**Issue by JinHai-CN** [matrixorigin/matrixone#740]
When an operator is used with operands of different types, type conversion occurs to make the operands compatible.

Following link provide the rule.
https://dev.mysql.com/doc/refman/8.0/en/type-conversion.html

**Comment by anitajjx** [comment]
Test results that are not compatible with MySQL:

1. '1' cannot be converted to numeric.
mysql> select * from t1 where '1'=1;
ERROR 1105 (HY000): unknown error:[42804] BIGINT cannot eq VARCHAR

2. The returned results differ from MySQL.
mysql> select * from t1 where cast('1' as unsigned)=1;
+------+--------+-------+
| spID | userID | score |
+------+--------+-------+
|    1 |      1 |     1 |
+------+--------+-------+
1 row in set (0.02 sec)

MySQL results:
mysql> select * from t1 where cast('1' as unsigned)=1;
+------+--------+-------+
| spID | userID | score |
+------+--------+-------+
|    1 |      1 |     1 |
|    2 |      2 |     2 |
|    2 |      1 |     4 |
|    3 |      3 |     3 |
|    1 |      1 |     5 |
|    4 |      6 |    10 |
|    5 |     11 |    99 |
+------+--------+-------+
7 rows in set (0.00 sec)

**Comment by m-schen** [comment]
Due to our cast rule is different to Mysql
It's not implicit type conversion problem. Implicit type Conversion use overload.Cast.
