### ISSUE TITLE
[Bug]:  Query occurs panic after adding unique constraints to the table

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#7401]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

./mo-service  -launch ./etc/launch-tae-CN-tae-DN/launch.toml
```

### Actual Behavior

create table t1(id int,name VARCHAR(255),age int);
insert into t1 values(1,"Abby", 24);
insert into t1 values(2,"Bob", 25);
insert into t1 values(3,"Carol", 23);
insert into t1 values(4,"Dora", 29);

mysql> select * from t1;
+------+-------+------+
| id   | name  | age  |
+------+-------+------+
|    1 | Abby  |   24 |
|    2 | Bob   |   25 |
|    3 | Carol |   23 |
|    4 | Dora  |   29 |
+------+-------+------+
4 rows in set (0.01 sec)

mysql> create unique index idx on t1(name);
Query OK, 0 rows affected (0.02 sec)

mysql> select * from t1;
ERROR 20101 (HY000): internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*database).Relation
	/home/yiming/workspace/matrixone/pkg/vm/engine/disttae/database.go:74
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation
	/home/yiming/workspace/matrixone/pkg/frontend/session.go:1655
github.com

### Expected Behavior

mysql> select * from t1;
+------+-------+------+
| id   | name  | age  |
+------+-------+------+
|    1 | Abby  |   24 |
|    2 | Bob   |   25 |
|    3 | Carol |   23 |
|    4 | Dora  |   29 |
+------+-------+------+
4 rows in set (0.01 sec

**Comment by nnsgmsone** [comment]
fixed by aptend
