### ISSUE TITLE
[Bug]: The result of TPCH Q16(1G) are different for different execution, especially for 1st query and the following query

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7402]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):62722889363357c124fc8c7b6e54639956171928
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 The result of TPCH Q16(1G) are different for different execution, especially for 1st query and the following query

frist time result:
[q16.1st.txt](https://github.com/matrixorigin/matrixone/files/10330063/q16.1st.txt)

second time result:
[q16.2nd.txt](https://github.com/matrixorigin/matrixone/files/10330064/q16.2nd.txt)

third time result:
[q16.3rd.txt](https://github.com/matrixorigin/matrixone/files/10330066/q16.3rd.txt)

### Steps to Reproduce

```Markdown
1. git clone https://github.com/matrixorigin/mo-tpch.git
2.
export LC_ALL="C.UTF-8"
./run.sh -c -s 1
./run.sh -l -s 1
./run.sh -q q16 -s 1
./run.sh -q q16 -s 1
./run.sh -q q16 -s 1
./run.sh -q q16 -s 1
```

**Comment by aunjgr** [comment]
This is a new bug introduced in `0.7`. In `0.6` q16 has consistant result.

**Comment by aunjgr** [comment]
`tae-logservice` still has no problem. Each run of q16 gets identical result.

In my test on `tae-CN-tae-DN`, first 11 runs of q16 get 11 different result. It becomes consistent since the 12th run.

**Comment by aunjgr** [comment]
If I run `select mo_ctl('dn', 'flush', 'tpch_1g.partsupp');` immediately after loading data, the result gets correct. `partsupp` is the biggest table in q16, which has 800k rows. The other two are `part` and `supplier`, with 200k/10k rows respectively.

So it is likely the matter that some data fails to be read without flush.

**Comment by aunjgr** [comment]
pass this issue on to @aptend

**Comment by nnsgmsone** [comment]
Positioning problems are the result of a strange usage of go 。。。。 Wait for qingxuan to fix it.

**Comment by dongdongyang33** [comment]
I will revert these change first and then find out the issue

**Comment by dongdongyang33** [comment]
this issue is not cause by #7344

**Comment by dongdongyang33** [comment]
cause by pr #7346

**Comment by dongdongyang33** [comment]
#7346 is not the root cause
this issue was introduced in more early PR

**Comment by aptend** [comment]
without flushing table when collecting logtail, there still errors in q16, so flushing is not the problem. commit is a483c1d84 log is 
[noflush&err.txt](https://github.com/matrixorigin/matrixone/files/10365365/noflush.err.txt)

and @LeftHandCold found that if make `generateCPUNumber` return 1, q16 has no problem
https://github.com/matrixorigin/matrixone/blob/013e23ec24daf48062741a2587b85d136d026a39/pkg/sql/compile/compile.go#L1356-L1366

**Comment by nnsgmsone** [comment]
This problem seems to be caused by some background merge block tasks, not very sure, continue to check.

**Comment by sukki37** [comment]
After trying several times, I found that the data error problem started with this commit:75140b7026c8e9b5d2227d1dd65c7b4890537a5c #7054 

My test env is c7g.2xlarge (2c14g)

How to repro:
1. run mo locally
``` shell
git clone https://github.com/matrixorigin/matrixone.git
git checkout 75140b7026c8e9b5d2227d1dd65c7b4890537a5c
#do some modifications to make it easier to repro
vim pkg/sql/compile/types.go
# change `Single_Core_Rows` to 10000
make build 
./mo-service  -launch ./etc/launch-tae-CN-tae-DN/launch.toml
```
2. prepare tpch data
``` shell
git clone https://github.com/matrixorigin/mo-tpch.git
cd mo-tpch/dbgen
apt-get -y install gcc automake autoconf libtool make
make
cd ../
./run.sh -g -s 1
# you can find data generated in `./data/1/`
```
3. test SQL: [test.sql.zip](https://github.com/matrixorigin/matrixone/files/10366461/test.sql.zip)
```
mysql -h 127.0.0.1 -P 6001 -udump -p111 -e"source test.sql"> result.1
```
**Tips:**
1. you should change the path used by `load` according to the actual situation
2. maybe need to run several times 
3. if you found `0` in the last column of the result, you reproduced this bug successfully.

**Comment by aressu1985** [comment]
will test today
