### ISSUE TITLE
[Feature Request]: CREATE ACCOUNT should support prepared statement

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#7408]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Create an account using prepared statement encounters the following error:


Error 20101 (HY000): internal error: statement: 'create account ? admin_name 'root' identified by '?''
```

Go code:

```
name := "test"
pwd := "test"
db.QueryContext(context.TODO(), "CREATE ACCOUNT `?` ADMIN_NAME root IDENTIFIED BY '?';", name, pwd)
```

### Describe the feature you'd like

CREATE ACCOUNT should support prepared statement, which is more secure and is not subject to SQL injection.

**Comment by daviszhen** [comment]
in 0.9

**Comment by heni02** [comment]
bvtcase已加，closed
