### ISSUE TITLE
[Feature Request]: Supported more datetime/timestamps  formats for auto detection

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7411]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Currently, we've supported the following formats for `datetime` and timestamp auto-detection:

1. datetime
    - [x] yyyy-mm-dd hh:mm:ss.ms
    - [x] yyyy-mm-dd
    - [x] yyyymmdd
    - [x] yyyy-mm-dd hh:mm:ss(.msec)
    - [x] mm/dd/hh/mm/ss
    - [x] yyyymmddhhmmss(.msec)

2. timestamp
    - [x] yyyy-mm-dd hh:mm:ss.ms
    - [x] yyyy-mm-dd
    - [x] yyyymmdd
    - [x] yyyy-mm-dd hh:mm:ss(.msec)
    - [x] yyyymmddhhmmss(.msec)

We need detect and processe more formats for `datetime` and timestamp input strings:

- [ ] Internet (RFC) Timestamp Formats, https://www.rfc-editor.org/rfc/rfc3339

**Comment by domingozhang** [comment]
adjust to p0.5
