### ISSUE TITLE
[Bug]: insert unique index select  duplicate data reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7413]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):60d1ea323be2a43f9c8c626e41f75ef6a6b7fa9e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert into index_table_04(col2,col3,col4)  select 'apple',2,'12'; not reported duplicate data 'apple','2'
![image](https://user-images.githubusercontent.com/113406637/210298722-d4a3d4b3-575e-4659-b3cd-f79490601f33.png)

mysql expect result:
![image](https://user-images.githubusercontent.com/113406637/210298928-72f0c212-2763-4924-af28-f2708c1c4a39.png)

### Steps to Reproduce

```Markdown
create table index_table_04 (col1 bigint not null auto_increment,col2 varchar(25),col3 int,col4 varchar(50),primary key (col1),unique key m1(col2,col3),key num_id(col4));
insert into index_table_04(col2,col3,col4)  select 'apple',1,'10';
insert into index_table_04(col2,col3,col4)  select 'apple',2,'11';
insert into index_table_04(col2,col3,col4)  select 'apple',2,'12';
```

**Comment by bbbearxyz** [comment]
I will fix when i support all the secondary key feature.

**Comment by bbbearxyz** [comment]
in the sys, the duplicate entry error is reported by the tae, error message is about the compound data like (xxxapplexxx2), but the tae don't know that and report to the compute layer. in the compute layer, we have two error report way, first is when the txn is not commit, distae find the data have conflict and report err, in this way, i can intercept this error and change this to `apple-2` . second is the txn commit, in this way, all the dml data is lost, so I can't intercept the error.
So in the sys, both compound primary key and unique key have this error, maybe include cluster by. So I think let tae know the compound data and de serial the data to `apple-2` is a good idea.

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by domingozhang** [comment]
need fix in 0.8

**Comment by bbbearxyz** [comment]
need fix in 0.8

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
The problem has been resolved in the Yuanning branch, as shown in the  @heni02 
![image](https://github.com/matrixorigin/matrixone/assets/70939751/79b2d587-b370-4e3c-9bb6-357608743510)

**Comment by qingxinhome** [comment]
The problem should has been resolved , please test it @heni02

**Comment by sukki37** [comment]
Verified in e245b8c80c42b9d4439ab03ee7a7c087c319cbb0. This issue has been resolved. Closing this issue now. If anyone encounters any related problems, please reopen or comment.
