### ISSUE TITLE
[Bug]: load data 5000w+ into table which include unique index ，loading failed for more than 1 and a half hours

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7429]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):ccb993590ec2c70995a3e4c1cfa95b67121bd3f0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

load data for more than one and a half hours. I took the initiative to terminate the program
It is  suspected that there is a problem with the unique performance. Please analyze the related logs

![image](https://user-images.githubusercontent.com/113406637/210348206-5aa90141-6042-4127-857d-288e6d4125c8.png)

not include unique index ddl ,load 5000w+ data cost 17min+
![image](https://user-images.githubusercontent.com/113406637/210352660-ee690d33-3bfd-466c-90f7-730fb3656224.png)

ddl：
create table table_5000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,
col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255),unique key uq_01(clo4),key key1(col11),key key2(col12));

### Steps to Reproduce

```Markdown
create table table_5000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,
col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255),unique key uq_01(clo4),key key1(col11),key key2(col12));
load data infile '/Users/heni/test_data/50000000_20_columns_load_data.csv' into table table_5000w;
```

**Comment by heni02** [comment]
[mo_log.zip](https://github.com/matrixorigin/matrixone/files/10336199/mo_log.zip)

**Comment by bbbearxyz** [comment]
I will fix when i support all the secondary key feature.

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by florashi181** [comment]
@heni02 could u have a test again?

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by w-zr** [comment]
I'm working on this issue.

**Comment by w-zr** [comment]
duplicate with https://github.com/matrixorigin/matrixone/issues/6949

**Comment by w-zr** [comment]
Now data can be loaded successfully with more memory usage.
With Unique Key:        11min22.97s
Without Unique Key:   5min30.44s

**Comment by w-zr** [comment]
According to @ouyuanning, CN unique key check in loading is now disabled.

**Comment by heni02** [comment]
confirm，closed
commit：1f7f26148d7d03827e208589c132db46379dae01
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4d61a7ab-26fa-447b-bedf-52f003b4d730)
