### ISSUE TITLE
[Feature Request]: Support more metadata in information_schema.tables

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7436]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support the following metadata columns :
TABLE_TYPE , including ('BASE TABLE','VIEW','SYSTEM VIEW')   
TABLE_TYPE, TAE
ROW_FORMAT: Dynamic
TABLE_ROWS: rows of table

**Comment by qingxinhome** [comment]
This Feature has been implemented, please test it @domingozhang
