### ISSUE TITLE
[Bug]: tpcc test was hung for maybe mo trace error

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7454]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b908fa0cf540b81cac22b82570542a7dace4ab34
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When run TPCC 10 warehourse test in nightly regression , The test was hung by nearly for 5 hours. The possible reason is describe as following.

The last tppc test log is at 2023-01-05 00:36:57 
2023-01-05 00:36:57 FATAL jTPCCTerminal:282 - TT_NEW_ORDER: Unexpected SQLException on transaction execution: w-w conflict

And on this moment，the mo write trace error for file already exists. log:

tmt_id_8 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4", "status": "success", "span": {"trace_id": "013230a9-8c4e-11ed-87d9-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1139"}
2023/01/05 00:36:57.408331 +0800 INFO frontend/session.go:278 session uuid: dec8f6ec-8c4d-11ed-87d9-b07b25f8b524 -> background session uuid: 013728ce-8c4e-11ed-87d9-b07b25f8b524
2023/01/05 00:36:57.408407 +0800 INFO frontend/util.go:499 query trace {"connection_id": 1139, "query": "execute __mo_stmt_id_8 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4", "vars": "68 , 9 , 0 , 2 , 12925", "session_info": "connectionId 1139"}
2023/01/05 00:36:57.408543 +0800 ERROR fileservice/local_etl_fs.go:73 error: file sys/logs/2023/01/05/rawlog/1672850217_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL.csv already exists
github.com/matrixorigin/matrixone/pkg/fileservice.(*LocalETLFS).Write
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/local_etl_fs.go:73
github.com/matrixorigin/matrixone/pkg/fileservice.(*FileServices).Write
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/fileservice/file_services.go:116
github.com/matrixorigin/matrixone/pkg/util/export.(*FSWriter).Write
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/fs_writer.go:134
github.com/matrixorigin/matrixone/pkg/util/export.(*FSWriter).WriteString
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/fs_writer.go:158
github.com/matrixorigin/matrixone/pkg/util/trace.batchCSVHandler.NewItemBatchHandler.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/trace/buffer_pipe.go:111
github.com/matrixorigin/matrixone/pkg/util/trace.batchCSVHandler.NewItemBatchHandler.func2
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/trace/buffer_pipe.go:125
github.com/matrixorigin/matrixone/pkg/util/export.(*bufferHolder).FlushAndReset

and the mo will write a very large error log very frequently；

2023/01/05 00:36:57.413792 +0800 INFO frontend/util.go:514 time of Exec.Run : 19.42468ms connectionId 1135
2023/01/05 00:36:57.419458 +0800 ERROR trace/buffer_pipe.go:112 [Trace] failed to write csv: span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,6487d166da33b3ab,fb6e6bca-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708584,2023-01-05 00:36:47.708593,9294,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,5065a7938e8f2340,fb6ed6f5-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708676,2023-01-05 00:36:47.708688,12040,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,350ff278ff69b5f6,fb6e6bca-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708682,2023-01-05 00:36:47.708691,8573,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,67824b52036c1abf,fb6cf1ee-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708684,2023-01-05 00:36:47.708693,9551,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,3c4d804de4db1f45,fb6ed6f5-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708693,2023-01-05 00:36:47.708699,6477,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,a12b635c4295b6ae,fb6cf1ee-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708698,2023-01-05 00:36:47.708705,6816,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,da50534483ce10aa,fb6e6bca-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708699,2023-01-05 00:36:47.708708,8606,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,ed06e256cfbcd8c8,fb6ed6f5-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708704,2023-01-05 00:36:47.708712,7737,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement
span_info,7c4dccb4-4d3c-41f8-b482-5251dc7a41bf,ALL,c6065e9ab72b6168,fb6e6bca-8c4d-11ed-87d9-b07b25f8b524,,,,,,{},0,,,MemCache.Read,0,2023-01-05 00:36:47.708714,2023-01-05 00:36:47.708722,8673,"{""Node"":{""node_uuid"":""7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"",""node_type"":""ALL""},""version"":""v0.6.0""}",statement  

### Steps to Reproduce

```Markdown
run TPCC 10 warehouse test
```

**Comment by xzxiong** [comment]
working on

**Comment by xzxiong** [comment]
add note, analyze at 2023-01-06 (Friday)

repro with start cmd like `./mo-service -debug-http 127.0.0.1:8123 -launch ./etc/launch-tae-CN-tae-DN/launch.toml`
1. run tpcc test
2. wait about 10min, found no output in result logs.
3. dump goroutine info by `wget -O -  http://localhost:8123/debug/pprof/goroutine&debug=2   > goroutine.txt`

[pprof.mo-service.goroutine.001.txt](https://github.com/matrixorigin/matrixone/files/10367958/pprof.mo-service.goroutine.001.txt)

**Comment by xzxiong** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/3862445015/jobs/6584051524

**Comment by aressu1985** [comment]
fixed:
695c2d52b2633f4a5bbb0710796ce8b563366fe3
