### ISSUE TITLE
[Enhancement]:  performance improvement on running on shared-storage

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7461]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

Compared to local launch mode, our performance on shared storage is heavily degraded.
We did some analysis and found that most(>99%) of the time was spent in logtail sync(After synchronizing the log, it takes a long time to read the block metadata according to the log.)

![企业微信截图_fc36e50c-af5f-4b2b-9c53-c141d950b23e](https://user-images.githubusercontent.com/77312370/210731703-b5cb8096-fad5-416d-988b-d212921c16dc.png)

![企业微信截图_be68d144-6d5c-41ec-83e8-002eaddcd26e](https://user-images.githubusercontent.com/77312370/210731684-788107cb-d727-4f83-815d-b877f813bfac.png)

[pprof.mo-service.samples.cpu.041.pb.gz](https://github.com/matrixorigin/matrixone/files/10350443/pprof.mo-service.samples.cpu.041.pb.gz)

**Comment by LiSong0214** [comment]
1、session 连接有时会很慢，但多发几条命令后，或者等一两分钟后，性能就很快了，此时如果一直操作则基本不会变慢，如果几分钟不操作，会经常回到很慢，然后又渐渐变快；
2、我发现开了两个session，一个性能ok，例如show databases 仅用了 0.3s，另一个要两分钟

**Comment by LeftHandCold** [comment]
The read operation of object‘s meta has been optimized in @7593
