### ISSUE TITLE
[Bug]: MO does not return result in 60s after run bvt test for about 12 times

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7462]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b908fa0cf540b81cac22b82570542a7dace4ab34
- Hardware parameters:
- OS type:Centos 8
- Others: 16core, 61G
```

### Actual Behavior

as the bvt test lasting, the cost of each test turn increased , as following:
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/47846308/210753501-59b0002e-9296-45c3-b3c3-cd5d933d1948.png">

and at last , the mo can not return result in 60s ：
[ERROR]
[SCRIPT   FILE]: /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/test/distributed/cases/table/system_table_cases.sql
[ROW    NUMBER]: 99
[SQL STATEMENT]: SELECT COUNT(0) FROM (SELECT * FROM sys_cpu_combined_percent LIMIT 10) AS temp;
[EXPECT RESULT]:
count(0)
10
[ACTUAL RESULT]:
MO does not return result in 60000 ms.

[ERROR]
[SCRIPT   FILE]: /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/test/distributed/cases/table/system_table_cases.sql
[ROW    NUMBER]: 100
[SQL STATEMENT]: SELECT COUNT('') FROM (SELECT * FROM sys_cpu_combined_percent LIMIT 10) AS temp;
[EXPECT RESULT]:
count()
10
[ACTUAL RESULT]:
SQL parser error: table "sys_cpu_combined_percent" does not exist

[ERROR]
[SCRIPT   FILE]: /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/test/distributed/cases/table/system_table_cases.sql
[ROW    NUMBER]: 101
[SQL STATEMENT]: SELECT COUNT(NULL) FROM (SELECT * FROM sys_cpu_combined_percent LIMIT 10) AS temp;
[EXPECT RESULT]:
count(null)
0
[ACTUAL RESULT]:
SQL parser error: table "sys_cpu_combined_percent" does not exist

### Steps to Reproduce

```Markdown
run bvt test circularly
```

**Comment by nnsgmsone** [comment]
I'll take a look.

**Comment by nnsgmsone** [comment]
After testing, I found that there was a very old transaction that never ended, causing cn's gc to never work.

**Comment by nnsgmsone** [comment]
Look at this issue after the transaction bug has been fixed.

**Comment by nnsgmsone** [comment]
No progress at the moment

**Comment by nnsgmsone** [comment]
After pr 7669 fixed some of cn's memory issues, there are still a lot of memory leaks in the system, but I think the test can try to run a daily run first

**Comment by aressu1985** [comment]
tracking for a more day

**Comment by aressu1985** [comment]
do not fixed in commitid:ce1aae5e38bfab63d644440fb8113c455f31e975

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/47846308/213106203-f637a85a-b58b-4d2e-8638-a46e8c915b5b.png">

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
wait for memory leak fix and memtable refactor

**Comment by aressu1985** [comment]
#8327

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
After running bvt x times, i get the following pprof:

![1](https://user-images.githubusercontent.com/31609524/232459818-d15fb09b-8d30-4200-8463-73e8a7188328.png)

after running bvt x+1 times, i get the following pprof:

![3](https://user-images.githubusercontent.com/31609524/232460177-096c5e25-bb49-4657-895b-7349f9c615ee.png)

**Comment by nnsgmsone** [comment]
The gc of memtable on cn looks like there are some problems

**Comment by jensenojs** [comment]
跟 #7601 应该是类似的，我一起跟一下

**Comment by jensenojs** [comment]
在跑完该issue的两个负载之后让mo进入空转，然后定时通过curl获取其trace信息。第一个trace距离跑完负载有一天左右的时间，目前commit的时间虽然有增长的情况，但并不能够区分出是趋势还是波动。还需要继续观测。

> https://github.com/matrixorigin/matrixone/issues/7462#issuecomment-1554587639

# trace1:

<img width="979" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/faad4ef1-3c96-4c04-8f1c-99ebf6b37443">
其实trace2，trace3的时延也是10ms

# trace4:
<img width="1030" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/4b26f015-5cbd-4c9c-916b-b71955d8fe07">

trace4的时延大一些，然后波动的情况似乎越来越大了

**Comment by jensenojs** [comment]
相关进展可以看步到 #11018 和 #7601

**Comment by sukki37** [comment]
traced by #7601, close this one
