### ISSUE TITLE
[Bug]: mo panic: runtime error: index out of range [1] with length 1 when run TPCH 10G Q11 query on mo with launch-tae-CN-tae-DN and MINIO

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7465]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d398bde3087060f33321fdf0d7a2005857b6773c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

this is occurred every times. the error log is :

2023/01/05 19:16:54.882431 +0800 INFO tasks/job.go:99 run-job {"id": "load-97937df5-5db5-4122-9cba-bed2c87467c2:494785_960_960:495745_1344_1344:497089_1088_1088:498177_320_320:498497_1344_1344:499841_2240_2240:502081_1600_1600:503681_320_320:504001_1600_1600:505601_3136_3136:508737_320_320:509057_704_704:509761_1344_1344:511105_320_320:511425_1344_1344:512769_1216_1216:513985_1728_1728:515713_320_320:516033_1728_1728:517761_1216_1216:518977_1728_1728:520705_320_320:521025_1728_1728:522753_1216_1216", "duration": "4.257719ms"}
2023/01/05 19:16:54.968775 +0800 INFO frontend/util.go:514 time of Exec.Build : 18.822704878s connectionId 1061
panic: runtime error: index out of range [1] with length 1

goroutine 820401 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.DecodeMetaLoc({0x0?, 0x4aaa6a?})
        /data1/sudong/matrixone/pkg/vm/engine/tae/dataio/blockio/types.go:88 +0x21c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.readColumnBatchByMetaloc({0x2b6a498, 0xc00da9ccc0}, 0xc0e4f45548, {0x0, 0x0, 0x0, 0x0, 0x57, 0xc3, 0xdb, ...}, ...)
        /data1/sudong/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:129 +0xb6
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockReadInner({0x2b6a498, 0xc00da9ccc0}, 0xc0e4f45548, 0x2e796c6b63697571?, {0xc044cb0340?, 0x656761676e652073?, 0x6c75666572616320?}, {0xc084012cc0, 0x4, 0x4}, ...)
        /data1/sudong/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:88 +0xf9
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead({0x2b6a498, 0xc00da9ccc0}, 0x6f7263612073746e?, {0xc044cb0340, 0x4, 0x4}, {0xc084012cc0, 0x4, 0x4}, {0xc03cccf4f0, ...}, ...)
        /data1/sudong/matrixone/pkg/vm/engine/tae/dataio/blockio/read.go:51 +0x2ae
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read(0xc0ed379180, {0x2b6a3f0?, 0xc05172a680?}, {0xc044cb0340?, 0x4?, 0x4?}, 0x2073736572707865?, 0x736567616b636170?)
        /data1/sudong/matrixone/pkg/vm/engine/disttae/reader.go:83 +0x399
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc00ba3bf28, {0x2b4b498, 0xc0ed379180}, 0xc0ed5316c0)
        /data1/sudong/matrixone/pkg/vm/pipeline/pipeline.go:64 +0x16a
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0x7361656469206c61?, 0x7566202e65726120?)
        /data1/sudong/matrixone/pkg/sql/compile/scope.go:61 +0xce
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x7566202e65726120?)
        /data1/sudong/matrixone/pkg/sql/compile/scope.go:79 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /data1/sudong/matrixone/pkg/sql/compile/scope.go:74 +0x18d

### Steps to Reproduce

```Markdown
1. run mo with launch-tae-CN-tae-DN and storage is MINIO 
2. run TPCH 10G Q11 queries
```

**Comment by LeftHandCold** [comment]
I can't reproduce it, it takes time to reproduce and debug, change it to s0

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
I can't reproduce it

**Comment by LeftHandCold** [comment]
downgrade observation

**Comment by LeftHandCold** [comment]
under observation

**Comment by LeftHandCold** [comment]
not reproduced yet

**Comment by LeftHandCold** [comment]
not reproduced yet

**Comment by LeftHandCold** [comment]
The read/write interface has been refactored, and this issue may be closed first @aressu1985

**Comment by aressu1985** [comment]
fixed
