### ISSUE TITLE
[Feature Request]: add information function for the account;

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#7470]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
mo cloud
```

### Describe the feature you'd like

1, select current_account(); 
print the account information:
column1:account_name;
column2:account_id;
column3:use_name;
column4:use_id;
column5:role_name;
column6:role_id;
2, select current_account_id();
3, select current_account_name();
4, select current_role_id();
5, select current_role_name();
6, select current_user_name();
7, select current_user_id();

**Comment by aressu1985** [comment]
test done
