### ISSUE TITLE
[Feature Request]: implement lower_case_table_names

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7488]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

This should be a DB level config as https://github.com/matrixorigin/matrixone/issues/6606

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/docs/blob/main/design/case%20sensitivity.md

**Comment by iamlinjunhong** [comment]
标识符除了不带''，"" 的字符串和关键字，比如数据库名、表名、列名、用户名、索引名、account名、role名、约束名等用户自定义名称

**Comment by Ariznawlll** [comment]
test done

**Comment by aressu1985** [comment]
test done
