### ISSUE TITLE
[Feature Request]: implement lower_case_result_names

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7489]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Same as lower_case_table_names as in #7488, but this time, we return column names in query result as is if user specifies a column alias.

**Comment by iamlinjunhong** [comment]
https://github.com/matrixorigin/docs/blob/main/design/case%20sensitivity.md

**Comment by Ariznawlll** [comment]
test done

**Comment by aressu1985** [comment]
test done
