### ISSUE TITLE
[Feature Request]: improve performance with secondary key

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7490]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

The performance can be imported with secondary index as following:
1. Queries based on columns with secondary index
2. Transactions based on columns with secondary index

**Comment by fengttt** [comment]
https://github.com/matrixorigin/matrixone/issues/3609

**Comment by sukki37** [comment]
tracked by #3609
