### ISSUE TITLE
[Feature Request]: Support DDL of secondary key

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7492]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support thest ddl syntax
1. CREATE INDEX
CREATE INDEX index_name
ON tbl_name (key_part,...)
COMMENT 'string'

2. DROP INDEX
DROP INDEX index_name

3. CREATE TABLE with KEY
KEY (key_part,...)

**Comment by bbbearxyz** [comment]
now pr#7525 only support create index, drop index, the third grammer and create index with comment is not support.

**Comment by domingozhang** [comment]
the third syntax can support in future release

**Comment by bbbearxyz** [comment]
@florashi181

**Comment by bbbearxyz** [comment]
the pr is merged, please test it.

**Comment by heni02** [comment]
test done，pr merged
