### ISSUE TITLE
[Refactoring]: Give function an execution context

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7502]
### Why do you want to refactor this code?

```Markdown
Give function a runtime execution context.   This context should be used for storing state or as a cache.
Both regular function and aggregate function need context
```

### Describe the solution you'd like

We can either add this context to all functions or only to the NewFn.  As NewFn is "new" so there won't be lots of changes and we migrate old Fn that need a context to new framework.

### Describe alternatives you've considered

Fix everything, probably change is too big.

**Comment by m-schen** [comment]
get it. 
but maybe it's hard to be finished at v0.7。

**Comment by m-schen** [comment]
I can not finish this feature at v0.7 and #6585 will base on this issue.
so I move them to v0.8

**Comment by fengttt** [comment]
This is a big problem and we should address sooner rather than later.

All vector are allocated and destroyed like they are free.   Take another example, func JoinFilterEvalExprInBucket(r, s *batch.Batch, rRow, sRow int, proc *process.Process, expr *plan.Expr) (*vector.Vector, error) 
Is this thing allocate a vector on every join filter eval?

This is CRAZY.

**Comment by m-schen** [comment]
该工作是表达式重构的一部分。

**Comment by m-schen** [comment]
design doc link: https://github.com/matrixorigin/docs/pull/165

**Comment by m-schen** [comment]
被s-1拖住的时间太长了，目前框架已经搭好，正在修改启动时所需要实现的函数，以及调试框架。
已经修改好的主要有cast + - * / mod > = like 等。

**Comment by m-schen** [comment]
相关branch:  https://github.com/m-schen/matrixone/tree/refactor-expr

**Comment by m-schen** [comment]
已完成。后续会继续优化。

**Comment by fengttt** [comment]
Congratulation on finish this one ...
