### ISSUE TITLE
[Bug]: unique index reported error message  of duplicate data 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7511]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):9f07f88fd5f7111954ef2c6ffbf818febcd2a8d9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

4 in the error message should be 2
![image](https://user-images.githubusercontent.com/113406637/211253727-c16cc94c-28f0-456d-9c9f-a8e420b85d96.png)

mysql：
![image](https://user-images.githubusercontent.com/113406637/211253878-2dc51454-6e85-4ffb-852c-748655636e07.png)

### Steps to Reproduce

```Markdown
create table index_04 (col1 bigint,col2 int primary key,col3 float,col4 bigint,unique key id1(col1),key id2(col4));
insert into index_04 values (1,2,20.23,4090),(2,4,100.00,4091),(NULL,3,0.01,NULL);
insert into index_04 values (3,2,20.23,4090),(2,4,100.00,4091),(4,4,100.00,4090);
```

**Comment by bbbearxyz** [comment]
we have a meeting talk about this question， this error is because there is a primary key conflict in the insert batch.  the docs is in the https://github.com/matrixorigin/docs/blob/main/tech-notes/sql/design/index/ContraintReportErr.md, I think the error is fine, so please close the issue.

**Comment by heni02** [comment]
confirm,closed
