### ISSUE TITLE
[Bug]: information_schema DB, table name should be in lower case.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7520]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):38d9138b244224d6db0ef26d19f6021de95944ab
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 PROCESSLIST  table name should be in lower case.

<img width="1256" alt="截屏2023-01-09 17 24 04" src="https://user-images.githubusercontent.com/39303074/211276936-d6456986-eb07-4311-b5c5-64b91d9bd688.png">

**Comment by qingxinhome** [comment]
PROCESSLIST table name is a keyword

**Comment by qingxinhome** [comment]
Deal with it soon

**Comment by qingxinhome** [comment]
The problem cannot be handled temporarily because 'PROCESSLIST' is a keyword

**Comment by fengttt** [comment]
non reserved keyword.

**Comment by tianyahui-python** [comment]
<img width="1487" alt="截屏2023-03-17 10 25 44" src="https://user-images.githubusercontent.com/39303074/225796446-cf668112-e074-473c-a8bf-58afba64ca2c.png">

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
bvt tag no remove @iamlinjunhong
