### ISSUE TITLE
[Bug]: explain analyze error

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7523]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a int);
explain analyze insert into t1 values(1);
ERROR 20101 (HY000): internal error: ins:<db_name:"tpch" tbl_name:"t1" explicit_cols:<col_id:1 name:"a" typ:<id:22 notNullable:true width:32 table:"t1" > default:<null_ability:true > > order_attrs:"a" columns:<column:<typ:<id:22 notNullable:true width:32 table:"t1" > f:<func:<obj:90194313216 obj_name:"cast" > args:<typ:<id:23 notNullable:true size:8 > c:<i64val:1 > > args:<typ:<id:22 notNullable:true width:32 table:"t1" > t:<typ:<id:22 notNullable:true width:32 table:"t1" > > > > > > cluster_table:<column_index_of_accountId:-1

**Comment by qingxinhome** [comment]
I will deal with it as soon as possible

**Comment by qingxinhome** [comment]
This problem has been solved, please test @domingozhang
