### ISSUE TITLE
[Bug]: use show table_values stmt got errror when the table has a json type column.

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#7527]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![261161682b31e4778e0563f1f6b05c0](https://user-images.githubusercontent.com/26563383/211300661-0ed74eea-b4e9-4161-9848-db569c1b0d6b.jpg)

**Comment by YANGGMM** [comment]
insertmysql> create table t2(col1 json);
Query OK, 0 rows affected (0.13 sec)

mysql> 
mysql> 
mysql> insert into t2 values('{"x":16}');
Query OK, 1 row affected (0.04 sec)

mysql> 
mysql> insert into t2 values('{"x":17}');
Query OK, 1 row affected (0.03 sec)

mysql> insert into t2 values('{"x":18}');
Query OK, 1 row affected (0.06 sec)

mysql> show table_values from t2;
+-----------+-----------+
| max(col1) | min(col1) |
+-----------+-----------+
| NULL      | NULL      |
| NULL      | NULL      |
| NULL      | NULL      |
+-----------+-----------+
3 rows in set (0.01 sec)

**Comment by YANGGMM** [comment]
still working

**Comment by tianyahui-python** [comment]
closed.
