### ISSUE TITLE
[Bug]: there is no "mo_catalog" in non-sys account

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#7529]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):650497a6dbe8245b7fd1c881da25899d7a7b1624
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

login with dump user.
there is no mo_catalog in the non-sys account.

```
mysql> select account_id,datname from mo_database order by account_id;
+------------+--------------------+
| account_id | datname            |
+------------+--------------------+
|          0 | mo_task            |
|          0 | mo_catalog         |
|          0 | information_schema |
|          0 | mysql              |
|          0 | system_metrics     |
|          0 | system             |
|          1 | system             |
|          1 | system_metrics     |
|          1 | information_schema |
|          1 | mysql              |
+------------+--------------------+
```

### Expected Behavior

the non-sys account_id also has the mo_catalog.

**Comment by daviszhen** [comment]
it is related to the issue https://github.com/matrixorigin/matrixone/issues/7383

**Comment by nnsgmsone** [comment]
This is not a bug, tenant 0 created this database, so the account id of this database is 0.

**Comment by daviszhen** [comment]
it is in progress.

**Comment by qingxinhome** [comment]
this question has been sloved by pr of https://github.com/matrixorigin/matrixone/pull/7567
@daviszhen

**Comment by daviszhen** [comment]
it was fixed.
