### ISSUE TITLE
[Bug]:The same table name join has no alias reported panic

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7533]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):361d6bca2fc79806fc25735f8b39e03d64a455fb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select * from a,a  reported panic
![image](https://user-images.githubusercontent.com/113406637/211443963-49e887e6-fc78-4884-af4f-dfe6e409f095.png)
2023/01/10 09:55:45.029042 +0800 ERROR frontend/mysql_cmd_executor.go:4021 error: internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/panic.go:260
runtime.sigpanic
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BindContext).mergeContexts
	/Users/heni/test-envir/matrixone/pkg/sql/plan/bind_context.go:86
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildJoinTable
	/Users/heni/test-envir/matrixone/pkg/sql/plan/query_builder.go:2075
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
	/Users/heni/test-envir/matrixone/pkg/sql/plan/query_builder.go:1859
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom
	/Users/heni/test-envir/matrixone/pkg/sql/plan/query_builder.go:1646
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect
	/Users/heni/test-envir/matrixone/pkg/sql/plan/query_builder.go:1240
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder
	/Users/heni/test-envir/matrixone/pkg/sql/plan/build.go:28
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan
	/Users/heni/test-envir/matrixone/pkg/sql/plan/build.go:56
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize
	/Users/heni/test-envir/matrixone/pkg/sql/plan/optimize.go:56
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:2510
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:2277
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:3562
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:4046
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/Users/heni/test-envir/matrixone/pkg/frontend/routine.go:165
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/Users/heni/test-envir/matrixone/pkg/frontend/routine_manager.go:290
github.com/fagongzi/goetty/v2.(*server).doConnection
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
runtime.goexit

select * from a as a1,a as a2 is correct
![image](https://user-images.githubusercontent.com/113406637/211444185-0c4d300a-73e9-42f7-89ac-7575b12ce7f5.png)

**Comment by daviszhen** [comment]
duplicate with https://github.com/matrixorigin/matrixone/issues/7858
It was fixed at pr https://github.com/matrixorigin/matrixone/pull/7868

**Comment by heni02** [comment]
confirm,closed
commit id:346277e3cb8e7aec9d68c043a3e9249e2c3cb842
![image](https://user-images.githubusercontent.com/113406637/218391815-62ecb5c8-b727-439a-9c26-155109267209.png)
