### ISSUE TITLE
[Bug]: show table_size from sys_async_task; execute error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7534]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):38d9138b244224d6db0ef26d19f6021de95944ab
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1275" alt="截屏2023-01-10 10 29 32" src="https://user-images.githubusercontent.com/39303074/211448302-fe26b155-6739-4ea1-86bf-853dc7429f25.png">

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by tianyahui-python** [comment]
<img width="1126" alt="截屏2023-01-30 17 25 50" src="https://user-images.githubusercontent.com/39303074/215438203-a7234686-8081-4cca-bf98-e11346a3cc23.png">
