### ISSUE TITLE
[Feature Request]: a builtin mo_log_date function

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7539]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Create a new function, mo_log_date(__mo_filepath) that returns date.  
so that people can write query like

select * from log_info where mo_log_date(__mo_filepath) between '2022/12/19' and '2023/01/19'
```

### Describe the feature you'd like

the builtin function.   make sure pruning on __mo_filepath still works on file level.

### Describe implementation you've considered

A SQL UDF, works too, but this one is so important let's just ship builtin.

One can completely hid mo_log_date and __mo_path by create a view.
create view log_info_v as select mo_log_date(__mo_path) as log_date, * from log_info;

After that user simply write select * from log_info_v where log_date > '2023/01/10'

**Comment by daviszhen** [comment]
table function

**Comment by gavinyue** [comment]
This feature is already implemented in pr: https://github.com/matrixorigin/matrixone/pull/7860

**Comment by Ariznawlll** [comment]
test done！

**Comment by gavinyue** [comment]
Close

**Comment by gavinyue** [comment]
Should be finished. Under verity.

**Comment by aressu1985** [comment]
test done
