### ISSUE TITLE
[Bug]: Insert auto-increment column concurrency 500 is much higher than 100 conflict

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7543]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):361d6bca2fc79806fc25735f8b39e03d64a455fb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The higher the number of concurrency, the greater the conflict of self-increasing columns

ddl：create table index_03 (col1 bigint auto_increment primary key,col2 int,unique key id1(col2));
insert into index_03(col2) values (parameters);

Concurrent 500 and 100 test results：
1.bingfa 500，execute 5min+，col2 values random 1-2000，insert success 48 rows
![image](https://user-images.githubusercontent.com/113406637/211464459-214ec8a1-4d81-4a07-a6d2-04f417b4c9ca.png)
![image](https://user-images.githubusercontent.com/113406637/211464501-ef0535b5-e5a9-4d35-b100-4a6902180442.png)
2.bingfa 100，execute 5min+，col2 values random 1-2000，insert success 1541 rows
![image](https://user-images.githubusercontent.com/113406637/211464673-7bdbc238-8631-4914-b3fe-1b602cbec399.png)
![image](https://user-images.githubusercontent.com/113406637/211464683-257f688f-1175-4ca5-8bd1-4f66d0633b11.png)

Concurrent 500 mo log about increment conflict：
2023/01/10 12:06:40.344922 +0800 ERROR dn-service util/log.go:349 txn commit with 1 PC failed {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "dn-shard": "2-262146-1-127.0.0.1:22000", "txn": "aee6588b6c2a4301b95dda54c7e98395/Active/S:1673323600068191000-0/C:1673323600344766000-0", "error": "w-w conflict"}
github.com/matrixorigin/matrixone/pkg/txn/util.LogTxnStart1PCCommitFailed
        /Users/heni/test-envir/matrixone/pkg/txn/util/log.go:349
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit
        /Users/heni/test-envir/matrixone/pkg/txn/service/service_cn_handler.go:232
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit
        /Users/heni/test-envir/matrixone/pkg/dnservice/store_rpc_handler.go:108
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage
        /Users/heni/test-envir/matrixone/pkg/txn/rpc/server.go:161
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage
        /Users/heni/test-envir/matrixone/pkg/common/morpc/server.go:204
github.com/fagongzi/goetty/v2.(*server).doConnection
        /Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
2023/01/10 12:06:40.344944 +0800 INFO rpc/handle.go:738 [precommit] handle write typ: 1, 272450-%!%mo_increment_columns, 272449-db

### Steps to Reproduce

use mo-load test

**Comment by heni02** [comment]
[molog_bingfa500.zip](https://github.com/matrixorigin/matrixone/files/10379631/molog_bingfa500.zip)
[molog_bingfa100.zip](https://github.com/matrixorigin/matrixone/files/10379632/molog_bingfa100.zip)

**Comment by heni02** [comment]
ddl only primary key bingfa 500 same results
![image](https://user-images.githubusercontent.com/113406637/211507780-20c2f266-16e3-4175-95cc-887164f3062b.png)
![image](https://user-images.githubusercontent.com/113406637/211507758-f081e019-d2c6-4373-8c26-e5e5842e7dc0.png)

**Comment by iceTTTT** [comment]
wait review

**Comment by heni02** [comment]
commit id:0ea4925d5cfc6922c8c602c61aa28a83632ca0a7
ddl:create table increment_01(col1 bigint auto_increment primary key,col2 int);
bingfa 500 ,run 5min+ results:
![image](https://user-images.githubusercontent.com/113406637/217180252-c885b780-6913-400a-82a5-a6ef9d96ae59.png)
![image](https://user-images.githubusercontent.com/113406637/217181242-88a1d6bc-dd28-4d57-a7dc-11a9c20610ba.png)

bingfa 100，run 5min+ results：

**Comment by ouyuanning** [comment]
@heni02 
you can try to change   pkg/frontend/types.go   
from
 cacheSize = 3000

to 

 cacheSize = 30000

**Comment by daviszhen** [comment]
> @heni02 you can try to change pkg/frontend/types.go from cacheSize = 3000
> 
> to
> 
> cacheSize = 30000

Previously, @fengttt  recommends the cacheSize 30000 is too large. Then the cacheSize is changed to the 3000.

**Comment by heni02** [comment]
Reproduce:
1.download tool [mo-load.zip](https://github.com/matrixorigin/matrixone/files/10681254/mo-load.zip) 
2.alter bingfa，file path：mo-load/cases/sysbench/auto_increment/run.yml
![image](https://user-images.githubusercontent.com/113406637/217417746-1aabc95a-0c6b-46ee-957f-e1544437d3bf.png)
3. mysql client execute sql:
create database db;
use db;
create table increment_01 (col1 bigint auto_increment primary key,col2 int);
4.run
./start.sh -c cases/sysbench/auto_increment

**Comment by iceTTTT** [comment]
![image](https://user-images.githubusercontent.com/74845916/217742687-ea2373e4-4199-4091-bd19-0565943a7017.png)

With 100 concurrency, In refined auto_incr cache.Got result showed in picture above.

**Comment by iceTTTT** [comment]
**With 500 concurrency**

In my machine(wsl), mo will be killed:

![image](https://user-images.githubusercontent.com/74845916/217746710-99fe2e21-3f43-4a49-ab35-f7598356d465.png)
It will take a lot memory:
![image](https://user-images.githubusercontent.com/74845916/217748752-5dcb8238-f0cc-46fe-bcb8-936ece4382bd.png)



And only 3927 values inserted successfully.
![image](https://user-images.githubusercontent.com/74845916/217746954-fc0b7950-d50b-473f-baf5-5e69f55558ce.png)

**Comment by iceTTTT** [comment]
[log.zip](https://github.com/matrixorigin/matrixone/files/10694672/log.zip)
Here's log, No ERROR like "insert query failed" or something.

**Comment by iceTTTT** [comment]
![image](https://user-images.githubusercontent.com/74845916/217764686-d891e86a-d7d7-4528-a177-2a9a363d542e.png)

 Run **Concurrency 500** with refined auto_incr_cache got result like above in the server of our company.

**Comment by heni02** [comment]
regression results :bingfa500 and 100 no conflicts
bingfa 100:
<img width="1219" alt="企业微信截图_de1c877f-d392-4b04-80a9-e1c764f4c631" src="https://user-images.githubusercontent.com/113406637/218245382-120b1bd8-c837-49d7-8c8b-ee628e8c8665.png">

bingfa500:
<img width="1112" alt="企业微信截图_552df4c0-9221-49ab-8a27-ab43d061b862" src="https://user-images.githubusercontent.com/113406637/218245757-16c565ef-650c-4b0f-9dae-d607a8b8d230.png">
