### ISSUE TITLE
[Bug]: In the case of “insert into t select * from t", a large amount of data will trigger the capacity of morpc to exceed

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#7546]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e5cc2c275cbc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1845" alt="9f48c156f85ebb397844fb8f0ba5e07" src="https://user-images.githubusercontent.com/56761542/211484215-003681d3-c09e-44cd-8294-a1b825637db9.png">

**Comment by jensenojs** [comment]
cn与cn之间走rpc的消息如果超过64m的话会进行拆分，得找一下是哪里的问题。

**Comment by jensenojs** [comment]
这个bug是在测试cn 2 s3的insert的时候发现的，通过在主库上随便创建一个表，然后反复`insert into t select * from t`的方式，在百万的数量级时就会触发，[message body too large](https://github.com/jensenojs/matrixone/blob/main/pkg/common/morpc/codec.go#L394)的问题，进一步会导致上面的driver info : retry time out的panic。往前追一两步发现可能是[a.client.record.Data](https://github.com/jensenojs/matrixone/blob/main/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go#L78)太大了，在送入morpc的时候没有拆，考虑到这个事情issue不见得跟#7160有多少关系，这个issue先挂着。

目前的顾虑是还不知道这里的Data是什么，反正不是batch，而batch是会拆分的（详情可以看 sendBackBatchToCnclient这个函数），也就是说#7160在实现之后仍然有可能会遇到logservice中的Data过大的问题，届时再看

**Comment by jiangxinmeng1** [comment]
应该是rowid导致的，dn给batch加上了rowid，如果列数很少，rowid占的比例会很大。等#7160实现之后，rowid会跟着其他数据一起先写到s3上，就能解决了。
我拿单列的表t(c varchar)做了实验，插入的时候，每行是6字节的varchar。不停`insert into t select * from t`之后报了`message body 168053418 is too large, max is 104857600`。
![微信图片_20220409181135](https://user-images.githubusercontent.com/51114574/212229730-787fe6e9-96ff-45f8-8d8d-163e3ad888cd.jpg)

里面基本是数据的batch占的，有327个400316的batch，92个400360的batch，一个172432的batch，总共167908884，占了99%以上。
![ckp1](https://user-images.githubusercontent.com/51114574/212229625-23ae914a-f6d0-4098-a190-40beb07954ff.jpg)
batch里只有两列，一列是原来是数据，一列是rowid。比原始数据多出来的应该就是rowid。
![屏幕截图 2023-01-13 111917](https://user-images.githubusercontent.com/51114574/212229587-34efd4ac-e2ae-485d-8899-f714b247d08e.jpg)

**Comment by jensenojs** [comment]
感谢

**Comment by domingozhang** [comment]
insert into t1 select * from t2 limit n;
n超过一定数值会报错，涉及到的数据量并不大
message body 109943332 is too large

**Comment by jensenojs** [comment]
> insert into t1 select * from t2 limit n; n超过一定数值会报错，涉及到的数据量并不大 message body 109943332 is too large

现在#7160 已经转测了，但由于统计信息中的cost并不反映数据的大小（而是行数）。所以目前大概在二十来万行的时候才会触发cn2s3的insert。@domingozhang说的这个场景是tpch的lineitem，在十来万行的时候就会有这个error导致insert的执行失败。需要进一步确认是卡在cn给dn的morpc还是卡在dn给logservice的morpc
