### ISSUE TITLE
[Bug]: create unique index blob/json/text not reported error message

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7549]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):361d6bca2fc79806fc25735f8b39e03d64a455fb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create unique index not reported about not supported: xxx type
![image](https://user-images.githubusercontent.com/113406637/211489243-22d34f58-e1ab-444d-9b8a-f1a27d720e88.png)
ddl create table sql include unique index reported not support is correct
![image](https://user-images.githubusercontent.com/113406637/211489691-16ecea26-acc1-4b22-a950-7b5f0b8f5988.png)

### Steps to Reproduce

```Markdown
create table create_index_16 (col1 bigint primary key,col2 blob,col3 blob);
create unique index blob_index on create_index_16(col2);
create table create_index_17 (col1 bigint primary key,col2 json,col3 json);
create unique index json_index on create_index_17(col2);
create table create_index_18 (col1 bigint primary key,col2 text,col3 text);
create unique index text_index on create_index_18(col2);
```

**Comment by bbbearxyz** [comment]
i already fixed the bug, please confrim it

**Comment by heni02** [comment]
confirm, closed
commit id:2f1e17764761fc8b0e279837bed65c611f44f9b5
![image](https://user-images.githubusercontent.com/113406637/215691643-f5a46c4e-1e93-4792-871b-cf1022de1ac7.png)
