### ISSUE TITLE
[Feature Request]: Support index meta data table

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7555]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

```
database: mo_catalog
table: mo_indexes
columns:
index_id, int unsigned
index_name, varchar
table_id, int unsigned
type, smallint unsigned
columns, varchar, for example 'column1,column2...' 
comments, varchar
```

use show indexes command can get following information, the format and data can follow mysql's

```
Table
Non_unique
Key_name
Seq_in_index
Column_name
Collation
Cardinality
Sub_part
Packed
Null
Index_type
Comment
Index_comment
Visible
Expression
```

**Comment by qingxinhome** [comment]
In mysql, Information about table indexes is also available from the INFORMATION_SCHEMA [STATISTICS](https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html) table. See [Section 26.3.34, “The INFORMATION_SCHEMA STATISTICS Table”](https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html). The extended information about hidden indexes is available only using SHOW EXTENDED INDEX; it cannot be obtained from the [STATISTICS](https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html) table.

**Comment by qingxinhome** [comment]
this Feature Request has been implement， please test @domingozhang @aressu1985

**Comment by Ariznawlll** [comment]
test done！
