### ISSUE TITLE
[Bug]: drop not exists index reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7557]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):361d6bca2fc79806fc25735f8b39e03d64a455fb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/211499588-b3afa25f-7c95-4885-9dbc-c19183d26e33.png)

### Steps to Reproduce

```Markdown
create table create_index_18 (col1 bigint not null auto_increment,col2 varchar(25),col3 int,col4 varchar(50),primary key (col1));
create unique index m1_index on create_index_18(col2,col3);
drop index m1_index on create_index_18;
drop index m1_index on create_index_18;
drop index m3_index on create_index_18;
```

**Comment by bbbearxyz** [comment]
<img width="1550" alt="Screen Shot 2023-01-13 at 3 05 38 PM" src="https://user-images.githubusercontent.com/71327518/212258287-533a36be-a886-4c1e-8393-5bdfa01a73a7.png">
this issue is solved now, please confirm it.

**Comment by heni02** [comment]
confirm, closed
commit id:44f1da2b5d4aa613cb66e78b8d6f33afe6151c54
![image](https://user-images.githubusercontent.com/113406637/212270308-642c0a1e-685e-4152-bce6-ae26975559a1.png)
