### ISSUE TITLE
[Bug]: decimal type, execute show table_values from table; return result error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7562]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f30f06a55e792e7f9a776702b326a670c99a59e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t3(
    -> col1 decimal
    -> );
Query OK, 0 rows affected (0.09 sec)

mysql> insert into t3 values(3.3);
Query OK, 1 row affected (0.05 sec)

mysql> show table_values from t3;
+-----------+-----------+
| max(col1) | min(col1) |
+-----------+-----------+
|         3 |         3 |
+-----------+-----------+
1 row in set (0.02 sec)

mysql> 
mysql> insert into t3 values(3.2);
Query OK, 1 row affected (0.02 sec)

mysql> show table_values from t3;
+-----------+-----------+
| max(col1) | min(col1) |
+-----------+-----------+
|         3 |         3 |
+-----------+-----------+
1 row in set (0.01 sec)

<img width="881" alt="截屏2023-01-10 18 53 47" src="https://user-images.githubusercontent.com/39303074/211533008-f0f40ae0-06d9-4774-ae0c-6dc3de17a58b.png">

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
![image](https://user-images.githubusercontent.com/26563383/212521131-634fbc1c-5068-491e-be94-c9e5f1c9bd5d.png)

**Comment by YANGGMM** [comment]
![image](https://user-images.githubusercontent.com/26563383/212521248-1292ec6a-3367-4671-836a-0b5896d1173e.png)

**Comment by tianyahui-python** [comment]
This is not a bug, decimal type is consistent with mysql.

![WechatIMG1587](https://user-images.githubusercontent.com/39303074/215437553-ff1a7779-b169-44cc-a03f-c28eec0ace9b.png)
