### ISSUE TITLE
[Bug]: show table_number from mo_catalog; result error;

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7564]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f30f06a55e792e7f9a776702b326a670c99a59e4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="955" alt="截屏2023-01-10 20 32 37" src="https://user-images.githubusercontent.com/39303074/211553623-eff33f6a-1bdb-4403-b53e-e6ef178446c2.png">

**Comment by tianyahui-python** [comment]
execute "show table_values", all the system tables are faulty.

**Comment by YANGGMM** [comment]
![image](https://user-images.githubusercontent.com/26563383/211939661-b00de615-c564-4936-8756-9131186c2388.png)

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
still working
