### ISSUE TITLE
[Bug]: TAE worker panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#7565]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): main
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023/01/10 21:47:35 worker exits from a panic: interface conversion: interface {} is types.Null, not []uint8
2023/01/10 21:47:35 worker exits from a panic: interface conversion: interface {} is types.Null, not int32
2023/01/10 21:47:35 worker exits from a panic: interface conversion: interface {} is types.Null, not []uint8
2023/01/10 21:47:35 worker exits from a panic: interface conversion: interface {} is types.Null, not int32
2023/01/10 21:47:35 worker exits from panic: goroutine 480180 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x247e600, 0xc04c3d4810})
        /opt/lib/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/numerics.Sort[...]({0x2c63c68, 0xc012ebc180}, {0xc01d783e70, 0x4, 0xc02372fa08})
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/numerics/func.go:27 +0x12e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc03fa97bc0, 0x2, 0x1?}, 0x1)
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:44 +0x1d1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc038dca360)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:118 +0x35f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc038dca360)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:138 +0x391
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03df03b20)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc049106060)
        /root/projects/matrixone/pkg/vm/engine/tae/db/task.go:62 +0xfb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03191d6c0)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0030b4d20, {0x7f4d9a771b68, 0xc049106060})
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:207 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x32
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

2023/01/10 21:47:35 worker exits from panic: goroutine 480181 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x247e600, 0xc04069b0b0})
        /opt/lib/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/numerics.Sort[...]({0x2c63c68, 0xc029b94240}, {0xc0258f30c0, 0x4, 0xc024815868})
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/numerics/func.go:27 +0x12e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc02ca02900, 0x2, 0x1?}, 0x0)
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:44 +0x1d1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc0413ad9e0)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:118 +0x35f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc0413ad9e0)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:138 +0x391
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc00dbe40e0)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc049106090)
        /root/projects/matrixone/pkg/vm/engine/tae/db/task.go:62 +0xfb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03191d7a0)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0030b4d20, {0x7f4d9a771b68, 0xc049106090})
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:207 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x32
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

2023/01/10 21:47:35 worker exits from panic: goroutine 480183 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x247e600, 0xc04c6e90e0})
        /opt/lib/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/varchar.Sort({0x2c62a78, 0xc028b78180}, {0xc0435cf140, 0x4, 0xc02a7416e8?})
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/varchar/func.go:26 +0x54e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc018342e00, 0x4, 0x17?}, 0x3)
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:78 +0x5e5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc00d7079e0)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:118 +0x35f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc00d7079e0)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:138 +0x391
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03aa73880)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc0491060f0)
        /root/projects/matrixone/pkg/vm/engine/tae/db/task.go:62 +0xfb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03191d960)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0030b4d20, {0x7f4d9a771b68, 0xc0491060f0})
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:207 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x32
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

2023/01/10 21:47:35 worker exits from panic: goroutine 480184 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x247e600, 0xc049106660})
        /opt/lib/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/varchar.Sort({0x2c62a78, 0xc0273d8660}, {0xc031158d80, 0x8, 0xc00c4496e8?})
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/varchar/func.go:26 +0x54e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc02fe6f000, 0x4, 0x17?}, 0x3)
        /root/projects/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:78 +0x5e5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc01cd7a240)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:118 +0x35f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc01cd7a240)
        /root/projects/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:138 +0x391
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03191db20)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc049106120)
        /root/projects/matrixone/pkg/vm/engine/tae/db/task.go:62 +0xfb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc03191da40)
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc0030b4d20, {0x7f4d9a771b68, 0xc049106120})
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:207 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
        /root/projects/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x32
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /opt/lib/go-path/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

### Steps to Reproduce

```Markdown
run bvt tests in local.
```

**Comment by aptend** [comment]
This will be fixed early in 0.8

**Comment by aptend** [comment]
This will be fixed early in 0.8

**Comment by XuPeng-SH** [comment]
0.8

**Comment by aptend** [comment]
almost ready

**Comment by aptend** [comment]
self testing

**Comment by aptend** [comment]
pr is under reviewing

**Comment by aptend** [comment]
pr has been merged
