### ISSUE TITLE
[Bug]: external table, show table_values from external_table; return result error;

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7568]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c8ff362791fe5755bd2e3e48fe1781f7a383ca5e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create external table external_table(
col1 int,
col2 float,
col3 varchar,
col4 blob,
col6 date,
col7 bool
)infile{"filepath"='xxx/external_table.csv'} fields terminated by ',' enclosed by '\"' lines terminated by '\n';

csv data：
null,null,null,null,null,null
100,10.34,你好,aaa,2011-10-10,0
10,1.34,你,aa,2011-10-11,1

<img width="1428" alt="截屏2023-01-11 14 07 52" src="https://user-images.githubusercontent.com/39303074/211730337-1eb1d6d3-85fa-4883-8782-e21d3d7dc7f3.png">

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
![image](https://user-images.githubusercontent.com/26563383/212520122-731051cb-c1c6-4d0b-9fd6-65db1129e6e3.png)

**Comment by YANGGMM** [comment]
plz give  me some case with external_table have data @tianyahui-python

**Comment by tianyahui-python** [comment]
bug unsolved.

**Comment by YANGGMM** [comment]
need wait https://github.com/matrixorigin/matrixone/issues/7736 to solve

**Comment by YANGGMM** [comment]
this is same as https://github.com/matrixorigin/matrixone/issues/7736
