### ISSUE TITLE
[Bug]: Trace  can lead to performance degradation

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#7569]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Open trace after qps from more than 6000 will be low to more than 3000

### Steps to Reproduce

```Markdown
use mo_load run sysbench point_select
```

**Comment by xzxiong** [comment]
env
---
dev: local pc
startup: ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
testcase:
```shell
git clone mo-load
cd mo-load
./start.sh -m SYSBENCH -n 1 -s 100000
./start.sh -c cases/sysbench/point_select_10_100000/
```

**Comment by xzxiong** [comment]
new info from xupeng, `doGenerate` cost 150s in cpu profile (300s trace)
test case
- sysbench case: 50 threads with all insert.
- mo args
```
turn-on-push-model = true

[cn.rpc]
send-queue-size = 2
busy-queue-size = 1

[log]
level = error / warn
```
![37d85133447dbcbd2f17a8be4e1b2ea5](https://user-images.githubusercontent.com/3927687/224630803-6c1c4b96-2d3f-4e29-947e-6f32b1231bd2.jpg)

**Comment by xzxiong** [comment]
后续在这里跟进  https://github.com/matrixorigin/matrixone/issues/9472
