### ISSUE TITLE
[Bug]: DN OOM when running init-task after restart

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#7574]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-ff9e1913
- Machine: AWS r5.xlarge, 4vCPU, 32Gi Mem
```

### Actual Behavior

DN consumes too much memory (near 30GiB) and being OOMKilled by the OS.

DN log (before OOMKilled):

[dn-init.log](https://github.com/matrixorigin/matrixone/files/10390090/dn-init.log)

### Expected Behavior

DN should not consume that much memory when running init-task on restart.

### Steps to Reproduce

```Markdown
N/A
```

**Comment by volgariver6** [comment]
in my local env, OOM is occurred too, but on CN:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/18366608/212010169-14c1e2cb-5ed5-41c8-bacb-65872910c09d.png">

**Comment by zhangxu19830126** [comment]
I'm working on this bug

**Comment by DanielZhangQD** [comment]
When this issue occurs, we're loading TPCH S10 data generated by `./dbgen -s 10` according to https://docs.matrixorigin.io/cn/0.6.0/MatrixOne/Test/performance-testing/TPCH-test-with-matrixone/#1-dbgen.

**Comment by volgariver6** [comment]
![profile001](https://user-images.githubusercontent.com/18366608/212877325-c810993c-e78d-4448-87eb-69f834029a92.svg)

**Comment by volgariver6** [comment]
![WeChatWorkScreenshot_429cbd40-e71b-411d-97cd-d006be8f981e](https://user-images.githubusercontent.com/18366608/212877395-281c56df-b0e6-4503-a5a0-5f715a16af26.png)

DN service consumed 8.2G memory when it restarts as the picture showed. but from the pprof, it only occupied 1.3G memory.

**Comment by volgariver6** [comment]
I have tried over 30 times but cannot repro it. Although DN consumed a little large memory sometimes, but no OOMKilled occurred. I think it has something to do with k8s scheduling.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by zhangxu19830126** [comment]
I'm working on this bug

**Comment by zhangxu19830126** [comment]
I'm working on this bug

**Comment by zhangxu19830126** [comment]
I'm working on this bug

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
will handle it later.

**Comment by volgariver6** [comment]
not happen again, maybe fixed by other pr.

**Comment by aressu1985** [comment]
I have test for more than 200G data, it dont happen again.
