### ISSUE TITLE
[Bug]: mo can't reboot, prompts unique key conflict

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#7578]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

cannot restart

### Steps to Reproduce

```Markdown
create database test;
use test;
create table t(a int);
insert into  t values(1);
insert into t values(1);

retart mo;
```

**Comment by bbbearxyz** [comment]
this is not influent reboot, it just a conflict. @fengttt , so I think it is not s-1.

**Comment by bbbearxyz** [comment]
i will fix it in the later

**Comment by qingxinhome** [comment]
The problem has been solved and pr has been submitted. Please test. @nnsgmsone @bbbearxyz @fengttt
