### ISSUE TITLE
[Bug]: table include secondary key show table error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7581]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):361d6bca2fc79806fc25735f8b39e03d64a455fb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/211777570-13f1922d-5906-4e68-bc48-41f5c1f7616d.png)
ddl:
CREATE TABLE IF NOT EXISTS `t_code_rule` (
  `code_id` bigint(20) NOT NULL ,
  `code_no` varchar(50) NOT NULL,
  `org_no` varchar(50) NOT NULL,
  `org_name` varchar(50) NOT NULL,
  `ancestors` varchar(255) NOT NULL,
  `code_rule_no` varchar(50) NOT NULL,
  `code_rule_name` varchar(50) NOT NULL,
  `code_name` varchar(50) NOT NULL,
  `code_type` int(11),
  `split` varchar(50) DEFAULT NULL,
  `remark` varchar(255),
  `create_time` datetime NOT NULL,
  `create_user` varchar(50) DEFAULT NULL,
  `last_update_time` datetime DEFAULT NULL,
  `last_update_user` varchar(50) DEFAULT NULL,
  `is_system_code` varchar(20)  NOT NULL DEFAULT 'N',
  PRIMARY KEY (`code_id`),
  UNIQUE KEY `code_type` (`code_type`),
  KEY `code_no` (`code_no`),
  KEY `code_rule_no` (`code_rule_no`),
  KEY `org_no` (`org_no`)
);

**Comment by bbbearxyz** [comment]
please confrim it, this is fixed.
