### ISSUE TITLE
[Bug]: create the same index after drop index ,insert unique key not work

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7596]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):99d3fa4232768ec577284e9992221fc0dce30d9e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create multiple unique indexes for one table, after drop index ,create same index, insert unique key not work
![image](https://user-images.githubusercontent.com/113406637/212004434-46a94ded-4a58-4ae0-a56c-2f92ebd47d11.png)
and try create one or two unique indexes for one table，it is work
![image](https://user-images.githubusercontent.com/113406637/212006475-325cd8ec-893d-4034-923b-b4239d8ef79e.png)

mysql:
![image](https://user-images.githubusercontent.com/113406637/212005787-1b1a681b-8487-41d7-829f-ca82fdce7f7d.png)

### Steps to Reproduce

```Markdown
create table create_index_18 (col1 bigint not null auto_increment,col2 varchar(25),col3 int,col4 varchar(50),primary key (col1));
create unique index m1_index on create_index_18(col2,col3);
create unique index m2_index on create_index_18(col2,col3,col4);
create unique index m3_index on create_index_18(col2);
create unique index m4_index on create_index_18(col3);
create unique index m5_index on create_index_18(col4);
insert into create_index_18(col2,col3,col4)  select 'apple',1,'10';
insert into create_index_18(col2,col3,col4)  select 'apple',2,'11';
insert into create_index_18(col2,col3,col4)  select 'apple',2,'12';
insert into create_index_18(col2,col3,col4)  select NULL,NULL,'13';
drop index m1_index on create_index_18;
create unique index m1_index on create_index_18(col2,col3);
insert into create_index_18(col2,col3,col4)  select 'apple',2,'11';
select * from create_index_18;
```

**Comment by bbbearxyz** [comment]
<img width="1057" alt="Screen Shot 2023-01-13 at 3 03 32 PM" src="https://user-images.githubusercontent.com/71327518/212257954-1d909e91-d855-48f4-8bd9-a1e48d27e80e.png">
i think this issue is solved now.

**Comment by bbbearxyz** [comment]
please confirm it.

**Comment by heni02** [comment]
confim,closed 
commit id:44f1da2b5d4aa613cb66e78b8d6f33afe6151c54
![image](https://user-images.githubusercontent.com/113406637/212269332-06c59723-9a6d-4a10-90f9-84c2d71612a0.png)
