### ISSUE TITLE
[Bug]: mo reject con after running oltp delete test with 100 threads for about 1 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7601]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0e269d14e151550195d36305a3afbc5b916d2c3e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

after running  oltp delete test with 100 threads for about 1 hours, all the connection was closed ,and new connection can not established.

tools log :
2023-01-12 14:34:49 ERROR TransExecutor:258 - Thread[id=80] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:49 ERROR TransExecutor:258 - Thread[id=61] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=26] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=64] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=63] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=85] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=28] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=30] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=7] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=86] can not get invalid connection after trying 3 times, and will exit
2023-01-12 14:34:50 ERROR TransExecutor:258 - Thread[id=1] can not get invalid connection after trying 3 times, and will exit

mo doulbful error log：
[oltp_delte_con_reject.txt](https://github.com/matrixorigin/matrixone/files/10399765/oltp_delte_con_reject.txt)
 

### Steps to Reproduce

```Markdown
1. mysql -h127.0.0.1 -udump -p111 -P6001 -e "create database if not exists sbtest;"
2. git clone https://github.com/matrixorigin/mo-sysbench.git
   sysbench  --mysql-host=127.0.0.1 --mysql-port=6001 --mysql-user=dump --mysql-password=111 oltp_common.lua  --mysql-db=sbtest --tables=10 --table_size=100000 --threads=1 --time=30 --report-interval=10 --create_secondary=off  --auto_inc=off prepare

3. git clone https://github.com/matrixorigin/mo-load.git
./start.sh -c cases/sysbench/delete_pk_10_100000 -t 100
```

**Comment by nnsgmsone** [comment]
let me look a see

**Comment by nnsgmsone** [comment]
No progress at the moment

**Comment by nnsgmsone** [comment]
This problem should be caused by a memory leak, and is trying to fix it (more trouble).

**Comment by nnsgmsone** [comment]
Note that sysbench can only support LuaJIT 2.1.0-beta2 at most

**Comment by nnsgmsone** [comment]
After pr 7669 fixed some of cn's memory issues, there are still a lot of memory leaks in the system, but I think the test can try to run a daily run first. @aressu1985 
![2023-01-17 15-44-38 的屏幕截图](https://user-images.githubusercontent.com/31609524/212838646-f4ea88cc-ddc3-4fb1-9299-446dae0c6fae.png)

**Comment by aressu1985** [comment]
do not fixed

**Comment by nnsgmsone** [comment]
This is some pprof information after a long run.
0:
![2023-01-19 13-28-52 的屏幕截图](https://user-images.githubusercontent.com/31609524/213362813-9b71c30a-bbd0-48e5-b44e-e127d9bcd451.png)

1:
![2023-01-19 13-29-52 的屏幕截图](https://user-images.githubusercontent.com/31609524/213362952-904507a4-ccb5-4396-af5b-8b47d669484e.png)

2: 
![2023-01-19 13-30-44 的屏幕截图](https://user-images.githubusercontent.com/31609524/213363076-54d4c010-bdfd-4d79-99b6-382b71370bd6.png)

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
I will give a plan to take care of the memory problem.

**Comment by fengttt** [comment]
taking off s-1, converted to a p0 dev task.

**Comment by aressu1985** [comment]
#8327

**Comment by nnsgmsone** [comment]
same to #8327

**Comment by nnsgmsone** [comment]
same to #8327

**Comment by nnsgmsone** [comment]
same to #8327

**Comment by jensenojs** [comment]
using  trace to track

**Comment by jensenojs** [comment]
在跑完该issue的两个负载之后让mo进入空转，然后定时通过curl获取其trace信息。第一个trace距离跑完负载有一天左右的时间，～～目前commit的时间虽然有增长的情况，但并不能够区分出是趋势还是波动。还需要继续观测。～～

不清楚plan重构前的commit时间越来越长是什么情况，但是就目前目前采集数据而言，似乎不存在这个问题。
> https://github.com/matrixorigin/matrixone/issues/7462#issuecomment-1554587639

# 数据

这里关注一下commit的耗时情况，空转到第三天的时候commit的耗时并没有明显增加，反而有所降低

## trace1:

<img width="979" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/faad4ef1-3c96-4c04-8f1c-99ebf6b37443">
其实trace2，trace3的时延也是10ms

## trace4:
<img width="1030" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/4b26f015-5cbd-4c9c-916b-b71955d8fe07">

trace4的时延稍微大一些，但似乎是因为这个commit触发了gc

<img width="1136" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/cb3ea5a5-2439-47b4-a3dc-a92a1ade7654">


## trace5：
<img width="1048" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/7bf02b7c-db87-4b59-a4bc-47f849aceb4e">

最新trace的数据commit，其时延比之前的trace都低

**Comment by jensenojs** [comment]
Task type | trace1(µs) | trace2 | trace3 | trace4 | trace5 | trace6 | trace7 | trace8
-- | -- | -- | -- | -- | -- | -- | -- | --
PartitionState.HandleMetadataDelete |   |   |   | 24.5 | 24.5 |   |   |  
PartitionState.HandleMetadataInsert |   |   |   | 500 | 550 |   |   |  
PartitionState.HandleRowsDelete | 35.5 | 41.5 | 35.5 | 50 | 50 | 128.5 | 143.25 | 119.75
PartitionState.HandleRowsInsert | 368 | 36.8 | 91.83 | 70.37 | 70.37 | 154 | 309.6364 | 163.714
WriteDataToClient | 10.25 | 17.37 | 13.91 | 16.868 | 16.868 | 17.1381 | 39.99048 | 40
compile.Compile | 418.2 | 748.76 | 848.03 | 2087.571 | 2087.571 | 2627.793 | 7176.396 | 4567.5
compile.Run | 4809.76 | 9574.29 | 8567.77 | 21843.93 | 21843.93 | 25258.03 | 94409.25 | 45262.8
parser.Parse | 43.1 | 36.73 | 34.7 | 206.7662 | 206.7662 | 64.91 | 95.447 | 60.11
plan.BuildPlan | 682.76 | 320.56 | 373.72 | 467.898 | 467.898 | 584.28 | 787.272 | 572.46
transaction.Commit | 1054.23 | 490.59 | 663.81 | 972.78 | 972.78 | 1750.755 | 2863.133 | 2526.83
transaction.New | 1571.2 | 2162.72 | 2022.929 | 2264.556 | 2264.559 | 1977.759 | 22580.947 | 2124.8276
transaction.Write | 157.5 | 251 | 382.5 | 506 | 506 | 934 | 1234.143 | 1676.4
  |   |   |   |   |   |   |   |  

<img width="621" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/446ed9b1-d4dc-4803-86ca-dd71adc53418">

trace1和trace7之间间隔了五天，在没有负载的情况下几乎所有任务的时延都在缓慢上升

**Comment by jensenojs** [comment]
> Task type	trace1(µs)	trace2	trace3	trace4	trace5	trace6	trace7	trace8
> PartitionState.HandleMetadataDelete	 	 	 	24.5	24.5	 	 	 
> PartitionState.HandleMetadataInsert	 	 	 	500	550	 	 	 
> PartitionState.HandleRowsDelete	35.5	41.5	35.5	50	50	128.5	143.25	119.75
> PartitionState.HandleRowsInsert	368	36.8	91.83	70.37	70.37	154	309.6364	163.714
> WriteDataToClient	10.25	17.37	13.91	16.868	16.868	17.1381	39.99048	40
> compile.Compile	418.2	748.76	848.03	2087.571	2087.571	2627.793	7176.396	4567.5
> compile.Run	4809.76	9574.29	8567.77	21843.93	21843.93	25258.03	94409.25	45262.8
> parser.Parse	43.1	36.73	34.7	206.7662	206.7662	64.91	95.447	60.11
> plan.BuildPlan	682.76	320.56	373.72	467.898	467.898	584.28	787.272	572.46
> transaction.Commit	1054.23	490.59	663.81	972.78	972.78	1750.755	2863.133	2526.83
> transaction.New	1571.2	2162.72	2022.929	2264.556	2264.559	1977.759	22580.947	2124.8276
> transaction.Write	157.5	251	382.5	506	506	934	1234.143	1676.4
>  	 	 	 	 	 	 	 	 
> <img alt="image" width="621" src="https://user-images.githubusercontent.com/56761542/257124772-446ed9b1-d4dc-4803-86ca-dd71adc53418.png">
> trace1和trace7之间间隔了五天，在没有负载的情况下几乎所有任务的时延都在缓慢上升

现在用bvt去跑一下

**Comment by jensenojs** [comment]
会在bvt跑完之后去进行trace的采集，采集完成之后会进行新一轮的bvt，bvt轮了35次后mo就被killed掉了，原因暂时还没有深入去看，下面的截图是mo-service.log最后的截图

<img width="1653" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/b7167fab-9234-404a-856b-870fcf39a466">

下面依次是跑了1次，5次，... 35次的bvt的测试结果，`compile.Run`的占用时间会比较明显地随着运行轮次而上涨，其他的task都没有明显的波动。

Task type | trace1(µs) | trace5 | trace10 | trace15 | trace20 | trace25 | trace30 | trace35
-- | -- | -- | -- | -- | -- | -- | -- | --
PartitionState.HandleMetadataDelete | 7.06481481 | 10.2538462 | 151.9318182 | 10.9344086 | 11.5962025 | 11.5145833 | 14.8813333 | 12.3192308
PartitionState.HandleMetadataInsert | 209.348624 | 469.48855 | 175.9772727 | 231.531915 | 76.2 | 816.350515 | 99.1184211 | 47.95
PartitionState.HandleRowsDelete | 50.125 | 30.875 | 35.95454545 | 27 | 16.875 | 25 | 22.3 | 21.4375
PartitionState.HandleRowsInsert | 343.35 | 413.955556 | 327.4269231 | 359.322222 | 493.011111 | 349.455556 | 356.8 | 301.083333
WriteDataToClient | 15.1033333 | 13.1734375 | 13.99066667 | 13.9507692 | 110.075758 | 11.0560606 | 9.27162162 | 8.2952381
compile.Compile | 112.529412 | 124.864662 | 121.7092199 | 138.333333 | 123.617647 | 111.94697 | 165.85 | 156.570313
compile.Run | 583.764706 | 739.879699 | 882.4680851 | 1125.69444 | 995.786765 | 1082.2197 | 1409.70714 | 1406.51563
parser.Parse | 66.8172414 | 58.6905063 | 63.28490099 | 49.936036 | 33.163253 | 37.4791289 | 39.1814465 | 25.5169184
plan.BuildPlan | 261.193229 | 253.024088 | 307.2587571 | 258.684328 | 134.317181 | 226.247929 | 247.197956 | 122.491613
transaction.Commit | 671.786047 | 609.251111 | 628.1299065 | 569.585227 | 573.904348 | 571.907778 | 598.264078 | 510.901136
transaction.New | 2227.47273 | 2188.10494 | 2296.012552 | 2203.51071 | 2294.31977 | 2216.06767 | 2458.91737 | 2372.40039
transaction.Write | 399.4375 | 371 | 414 | 326.642857 | 292.0625 | 312.428571 | 350.647059 | 236.3125

**Comment by jensenojs** [comment]
对于Compile.Run的时延需要更细粒度的Task去确认问题。目前怀疑是那三张特殊表的数据没有及时清理导致Reader相关的方法就越来越慢了，继续定位

**Comment by jensenojs** [comment]
单机cn的默认配置，采集是在跑完了bvt之后进行的，**可以看到`pipeline`从`engine`中读取block这个地方的调用频次越来越高**（具体见附录），这个事情是不应该的，一次`pipeline.Run`和一个`sql`就算不是1比1它的比例也不可能太夸张的，bvt的SQL总量是固定的，所以`pipeline.Run`的数量不应该这样的。

<img width="974" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/a0b1b0cf-0900-4f5b-993e-86644e6a5f13">

跑完28轮bvt后`pipeline.Run`运行了951次。

虽然占用的平均时间没有明显倾向，但是次数上升导致`mo`现在会越来越慢，#11018 也反映了这个问题。现在要找调用到`pipeline.Run`的来源是哪里，之前有个调研后台任务的 #10579 ，我会结合着一起看一下

# 附录
<img width="1333" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/ef2645a8-058f-4831-a1cf-a0fb0bfffd71">


> 对于Compile.Run的时延需要更细粒度的Task去确认问题。目前怀疑是那三张特殊表的数据没有及时清理导致Reader相关的方法就越来越慢了，继续定位

**Comment by aressu1985** [comment]
fixed
