### ISSUE TITLE
[Bug]: table broken

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#7605]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):https://hub.docker.com/r/matrixorigin/matrixone/tags?page=1&name=nightly-ff9e1913
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
problem on eks
step1: (may be the cause) truncate table partsupp;
step2: show tables;
step3: select count(*) from partsupp; ERROR 1064 (HY000): SQL parser error: table "partsupp" does not exist
step4: drop table partsupp; ERROR 1146 (HY000): no such table tpch.partsupp
step5: drop database tpch;
step6: show databases;
step7: create database tpch;
step8: use tpch;
step9: show tables;  partsupp
step10: select * from partsupp; ERROR 1064 (HY000): SQL parser error: table "partsupp" does not exist
<img width="495" alt="image" src="https://user-images.githubusercontent.com/31049447/212054963-01c7a21c-b227-4c0f-9c65-cac6940325b6.png">

**Comment by triump2020** [comment]
Setting up the cloud environment to repro.

**Comment by triump2020** [comment]
reproducing

**Comment by triump2020** [comment]
No progress

**Comment by triump2020** [comment]
It has not yet been reproduced when use the [newer version](https://hub.docker.com/layers/matrixorigin/matrixone/nightly-977d6045/images/sha256-e78c4d99d3d66fb6b58b1f48fcef1203265f0b50237fa4c6187a0f45f7150888?context=explore).
After fixing #7770 , i will come back.

**Comment by triump2020** [comment]
Reproducing

**Comment by florashi181** [comment]
@LiSong0214 have a test

**Comment by LiSong0214** [comment]
@triump2020  as we discussed, please try to reproduce the problem on eks, if it can not be reproduced using the latest version, you can close this issue.

**Comment by triump2020** [comment]
@LiSong0214  I had communicated with @aressu1985 , this issue can be closed .
