### ISSUE TITLE
[Bug]: SSB 1G QUERY is much slower than before

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7608]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 44f922071871a89ce50fddb69b0884a9653c8249
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

for commit 44f922071871a89ce50fddb69b0884a9653c8249(Date:   Thu Jan 12 17:32:06 2023 +0800):
SSB Q1.1 Q1.2 Q1.3 query costs are:
Q1.1 : 5.124 s
Q1.2 : 1.432 s
Q1.3 : 1.572 s

for commit 9d792b5adb4d29b9a9f3b321b1074939af7200e1(Tue Jan 10 20:15:24 2023 +0800)
Q1.1 : 0.29 s
Q1.2 : 0.158 s
Q1.3 : 0.163 s

**Comment by aressu1985** [comment]
It didn't have regression,  if execute query immediately after load finished, query will also slow down for version before

**Comment by aressu1985** [comment]
but the problem is that why need so long for merging or compacting only about 100M data?

**Comment by badboynt1** [comment]
no progress
