### ISSUE TITLE
[Bug]: kill sql about cross join failed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7612]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.7.0 or 8b23a93):99d3fa4232768ec577284e9992221fc0dce30d9e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql which is select count(*) from ex_table_100w,table_100w can not be killed，two table are 100w data rows
![image](https://user-images.githubusercontent.com/113406637/212220194-b24fb744-1a22-4ad7-bd7d-1c0005a64852.png)
![image](https://user-images.githubusercontent.com/113406637/212220188-725d3e8d-cea8-4670-ae0b-2a97dd81a19c.png)
but cross join like select count(*) from ex_table_100w as a,table_100w as b where a.clo1=b.clo1 can be killed，it is strange
![image](https://user-images.githubusercontent.com/113406637/212219100-92b7729f-f526-4261-9077-12e27f1f4b29.png)
![image](https://user-images.githubusercontent.com/113406637/212219218-32d19544-6a58-4a34-b125-96cdaa7c81b7.png)

### Steps to Reproduce

```Markdown
create external table ex_table_100w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,
col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255))infile{"filepath"='/Users/heni/test_data/1000000_20_columns_load_data.csv'} ;
create table table_100w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date, col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255));
insert into table_100w select * from  ex_table_100w;
select count(*) from ex_table_100w,table_100w;
select count(*) from ex_table_100w as a,table_100w as b where a.clo1=b.clo1;
```

**Comment by heni02** [comment]
mo log: [log_kill.txt](https://github.com/matrixorigin/matrixone/files/10407572/log_kill.txt)

**Comment by daviszhen** [comment]
the context.Conetxt has been canceled. the computation engine behaves abnormally. something is related to the https://github.com/matrixorigin/matrixone/issues/6639

**Comment by m-schen** [comment]
it's very same to #7615

**Comment by nnsgmsone** [comment]
it's very same to https://github.com/matrixorigin/matrixone/issues/7615

**Comment by heni02** [comment]
regression also have this problem @jianwan0214 plz check with kill connection not ctrl c
![image](https://user-images.githubusercontent.com/113406637/218297040-fbbc05eb-8f2c-43b9-8def-8f0721ca8183.png)
![image](https://user-images.githubusercontent.com/113406637/218297046-07834d9b-7c93-4e16-98fc-fa689b990092.png)

**Comment by heni02** [comment]
confirm，closed
