### ISSUE TITLE
[Bug]: mo crash by fatal error: runtime: out of memory during stability test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7613]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):65704d378bf8ad9c01b19ac6977da26b0a06a924
- Hardware parameters:16core 64G
- OS type:
- Others:
```

### Actual Behavior

2023/01/13 03:19:39.791966 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 1159, "statement": "update sbtest7 set k = k + 100 where id = 4085", "status": "success", "span": {"trace_id": "0e4238ad-92ae-11ed-9305-525400777c3a", "kind": "statement"}, "session_info": "connectionId 1159"}
2023/01/13 03:19:39.792114 +0800 INFO frontend/util.go:500 query trace {"connection_id": 1159, "query": "UPDATE sbtest6 SET k=k+100 WHERE id = 89636;", "session_info": "connectionId 1159"}
[mysql] 2023/01/13 03:19:47 packets.go:37: read tcp 127.0.0.1:53744->127.0.0.1:6001: i/o timeout
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x27fd900?, 0x2030?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f36ecff8800 sp=0x7f36ecff87d0 pc=0x448d9d
runtime.sysMapOS(0xce31000000, 0x400000?)
        /usr/local/go/src/runtime/mem_linux.go:187 +0x11b fp=0x7f36ecff8848 sp=0x7f36ecff8800 pc=0x429a1b
runtime.sysMap(0xc3ffffffff?, 0x7f374ef9a000?, 0x43cea0?)
        /usr/local/go/src/runtime/mem.go:142 +0x35 fp=0x7f36ecff8878 sp=0x7f36ecff8848 pc=0x4293f5
runtime.(*mheap).grow(0x416bd00, 0x4?)
        /usr/local/go/src/runtime/mheap.go:1468 +0x23d fp=0x7f36ecff88e8 sp=0x7f36ecff8878 pc=0x439f5d
runtime.(*mheap).allocSpan(0x416bd00, 0x4, 0x1, 0x0)
        /usr/local/go/src/runtime/mheap.go:1199 +0x1be fp=0x7f36ecff8980 sp=0x7f36ecff88e8 pc=0x43969e
runtime.(*mheap).allocManual(0x1e?, 0xe2e686a30?, 0xf8?)
        /usr/local/go/src/runtime/mheap.go:944 +0x1f fp=0x7f36ecff89a8 sp=0x7f36ecff8980 pc=0x43915f
runtime.stackpoolalloc(0x0)
        /usr/local/go/src/runtime/stack.go:207 +0x66 fp=0x7f36ecff89e8 sp=0x7f36ecff89a8 pc=0x4612e6
runtime.stackcacherefill(0x7f374efbcfe8, 0x0)
        /usr/local/go/src/runtime/stack.go:290 +0x65 fp=0x7f36ecff8a28 sp=0x7f36ecff89e8 pc=0x461625
runtime.stackalloc(0x800)
        /usr/local/go/src/runtime/stack.go:392 +0x245 fp=0x7f36ecff8aa0 sp=0x7f36ecff8a28 pc=0x461b65

        /usr/local/go/src/runtime/proc.go:4080 +0x25 fp=0x7f36ecff8ac0 sp=0x7f36ecff8aa0 pc=0x453be5
runtime.malg(0x800)
        /usr/local/go/src/runtime/proc.go:4079 +0x9e fp=0x7f36ecff8b00 sp=0x7f36ecff8ac0 pc=0x453b5e
runtime.newproc1(0xc9a9534db0, 0x7f36ecff8b88?, 0x49cbd2)
        /usr/local/go/src/runtime/proc.go:4123 +0x7e fp=0x7f36ecff8b50 sp=0x7f36ecff8b00 pc=0x453d9e
runtime.newproc.func1()
        /usr/local/go/src/runtime/proc.go:4098 +0x25 fp=0x7f36ecff8b78 sp=0x7f36ecff8b50 pc=0x453cc5
runtime.newproc(0x1068?)
        /usr/local/go/src/runtime/proc.go:4097 +0x51 fp=0x7f36ecff8bb0 sp=0x7f36ecff8b78 pc=0x453c71
time.goFunc({0x233ec80?, 0xc9a9534db0?}, 0x0?)
        /usr/local/go/src/time/sleep.go:176 +0x32 fp=0x7f36ecff8bd8 sp=0x7f36ecff8bb0 pc=0x49cbd2
runtime.runOneTimer(0xc000085400, 0xc17728d138, 0x0?)
        /usr/local/go/src/runtime/time.go:884 +0x159 fp=0x7f36ecff8c30 sp=0x7f36ecff8bd8 pc=0x46a079
runtime.runtimer(0xc000085400, 0x24fb0a220c170)
        /usr/local/go/src/runtime/time.go:791 +0x1fa fp=0x7f36ecff8c60 sp=0x7f36ecff8c30 pc=0x469eba
runtime.checkTimers(0xc000085400, 0x24fa9f4b02706?)
        /usr/local/go/src/runtime/proc.go:3313 +0x12c fp=0x7f36ecff8ca8 sp=0x7f36ecff8c60 pc=0x451f6c
runtime.findRunnable()
        /usr/local/go/src/runtime/proc.go:2582 +0x78 fp=0x7f36ecff8d98 sp=0x7f36ecff8ca8 pc=0x4504f8
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:3214 +0xbe fp=0x7f36ecff8dd0 sp=0x7f36ecff8d98 pc=0x451c9e
runtime.goschedImpl(0xce2d63cd00)
        /usr/local/go/src/runtime/proc.go:3378 +0xc5 fp=0x7f36ecff8e08 sp=0x7f36ecff8dd0 pc=0x4522c5
runtime.gopreempt_m(0xce2d63cd00?)
        /usr/local/go/src/runtime/proc.go:3406 +0x55 fp=0x7f36ecff8e48 sp=0x7f36ecff8e08 pc=0x4525b5
runtime.mcall()
        /usr/local/go/src/runtime/asm_amd64.s:448 +0x43 fp=0x7f36ecff8e58 sp=0x7f36ecff8e48 pc=0x47aec3

and the log is very large ,if want, please contact me

### Steps to Reproduce

```Markdown
run stability test:
1、bvt loop run:
  nohup ./run.sh -n -g -p  $GITHUB_WORKSPACE/head/test/distributed/cases -e ddl -t 60 > bvt.log &

2、TPCH 1G loop run:
  nohup ./run.sh -q all -s 1 -t 100 > tpch.log &

3、TPCC 10w-50termimals 10 hours run：
  nohup ./runBenchmark.sh props.mo > tpcc.log &

4、sysbench mixed cases 10 hours run:
  nohup ./start.sh -c cases/sysbench/mixed_10_100000/ > sysbench.log &
```

**Comment by reusee** [comment]
Looking into it.

Running BVT tests and watching the heap profile

<img width="1110" alt="截屏2023-01-13 12 06 24" src="https://user-images.githubusercontent.com/398457/212234990-c9f4867b-f17c-4ea6-be46-38c53b097129.png">

**Comment by reusee** [comment]
I'm going to re-implement the partition cache. This may reduce some memory costs.

**Comment by reusee** [comment]
in-progress

**Comment by nnsgmsone** [comment]
After pr 7669 fixed some of cn's memory issues, there are still a lot of memory leaks in the system, but I think the test can try to run a daily run first

**Comment by aressu1985** [comment]
tracking for a more day

**Comment by aressu1985** [comment]
fixed

**Comment by aressu1985** [comment]
this problen is happen again in commit: 15baa9727

2023/02/10 10:19:11.941214 +0800 INFO db/scannerop.go:370 Mergeblocks scan nseg {"seg": 1089}
2023/02/10 10:19:11.941309 +0800 INFO db/scannerop.go:370 Mergeblocks scan nseg {"seg": 1100}
2023/02/10 10:19:11.941498 +0800 INFO db/scannerop.go:370 Mergeblocks scan nseg {"seg": 1101}
2023/02/10 10:19:11.941533 +0800 ERROR rpc-client[log-heartbeat] morpc/client.go:349 gc inactive backends task stopped
2023/02/10 10:19:11.946634 +0800 ERROR log-service logservice/service_commands.go:166 failed to send log service heartbeat {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "context deadline exceeded"}
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).heartbeat
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/service_commands.go:166
github.com/matrixorigin/matrixone/pkg/logservice.(*Service).heartbeatWorker
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/service_commands.go:134
github.com/matrixorigin/matrixone/pkg/logservice.NewService.func5
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/service.go:179
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x2848d7b?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fdcd9bbec88 sp=0x7fdcd9bbec58 pc=0x448e5d
runtime.sysMapOS(0xce25c00000, 0x400000?)
        /usr/local/go/src/runtime/mem_linux.go:187 +0x11b fp=0x7fdcd9bbecd0 sp=0x7fdcd9bbec88 pc=0x429a1b
runtime.sysMap(0x43e7da?, 0x41e1790?, 0x1?)
        /usr/local/go/src/runtime/mem.go:142 +0x35 fp=0x7fdcd9bbed00 sp=0x7fdcd9bbecd0 pc=0x4293f5
runtime.(*mheap).grow(0x41e1780, 0x2000?)
        /usr/local/go/src/runtime/mheap.go:1468 +0x23d fp=0x7fdcd9bbed70 sp=0x7fdcd9bbed00 pc=0x439f5d
runtime.(*mheap).allocSpan(0x41e1780, 0x1, 0x0, 0x35)
        /usr/local/go/src/runtime/mheap.go:1199 +0x1be fp=0x7fdcd9bbee08 sp=0x7fdcd9bbed70 pc=0x43969e
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:918 +0x65 fp=0x7fdcd9bbee50 sp=0x7fdcd9bbee08 pc=0x439125
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:492 +0x49 fp=0x7fdcd9bbee58 sp=0x7fdcd9bbee50 pc=0x47b069
/out

**Comment by aressu1985** [comment]
2023-02-10 11:31:10 Now start to compare query result for [report/TPCH_10/q22.txt,golden/TPCH_10/q22.txt]
2023-02-10 11:31:10 The query q22  has be executed successfully,and cost: 3286

2023-02-10 11:31:10 Now start to execute the query queries/q2.sql,please wait.....
./run.sh: fork: Cannot allocate memory


it should be cuased by tpch 10 queries ,when I run tpch 10g queires for 10 times , the mo can not allocat memory:

2023-02-10 11:31:10 Now start to compare query result for [report/TPCH_10/q22.txt,golden/TPCH_10/q22.txt]
2023-02-10 11:31:10 The query q22  has be executed successfully,and cost: 3286

2023-02-10 11:31:10 Now start to execute the query queries/q2.sql,please wait.....
./run.sh: fork: Cannot allocate memory

**Comment by nnsgmsone** [comment]
Memory issues are dealt with uniformly and can be transferred to a function and then associated

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
转成feature #388把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #388把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #388把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #388把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #388把 @aressu1985

**Comment by nnsgmsone** [comment]
转成feature #388把 @aressu1985

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
等于https://github.com/matrixorigin/matrixone/issues/7891

**Comment by nnsgmsone** [comment]
pr 9096 has been submitted, although the memory problems are not all solved, but there should be a lot of improvements, you can retest to see. @aressu1985

**Comment by aressu1985** [comment]
testing

**Comment by nnsgmsone** [comment]
get it

**Comment by nnsgmsone** [comment]
continue

**Comment by nnsgmsone** [comment]
continue
