### ISSUE TITLE
[Bug]: UT tests failed 

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#7629]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

first failed:
![85cc07be0e47a1c8e36a33732f65900](https://user-images.githubusercontent.com/26563383/212326841-55b4d84d-a426-4e11-a220-f2fa4f07682c.png)

https://github.com/matrixorigin/matrixone/actions/runs/3909626144/jobs/6680911829

second failed:
![ff8c5026f6b787b802b312ff4b8163a](https://user-images.githubusercontent.com/26563383/212326918-e8a7a98d-95fe-4060-9614-aefbc68e225a.png)

https://github.com/matrixorigin/matrixone/actions/runs/3910164182/jobs/6682039015

thanks

**Comment by xzxiong** [comment]
case TestNewMOCollector has done,  while case TestBaseRemind2 not repro.
