### ISSUE TITLE
[Bug]: TPCH 10G Q1 result is not correct 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7634]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8051e3b3e28311b6a52b34fad9a62bc3727c88bf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023-01-14 06:54:02 Now start to compare query result for [report/TPCH_10/q1.txt,golden/TPCH_10/q1.txt]
2023-01-14 06:54:02 The column[5] value of row[3] does not equal to each other, [NaN] and [1083522615974.869816]

real:
l_returnflag    l_linestatus    sum_qty sum_base_price  sum_disc_price  sum_charge      avg_qty avg_price       avg_disc        count_order
A       F       377518399.00    566065727797.25 537759104278.065600000000       559276670892.1168190000000000000000     25.50   38237.15        0.05    14804077
N       F       9851614.00      14767438399.17  14028805792.211400000000        14590490998.3667370000000000000000      25.52   38257.81        0.05    385998
N       O       731368004.00    1096674315157.26        1041836574901.189200000000      NaN     25.50   38233.12        0.05    28683884
R       F       377732830.00    566431054976.00 538110922664.767700000000       559634780885.0862570000000000000000     25.51   38251.22        0.05    14808183

expected:
L_RETURNFLAG    L_LINESTATUS    SUM_QTY SUM_BASE_PRICE  SUM_DISC_PRICE  SUM_CHARGE      AVG_QTY AVG_PRICE       AVG_DISC        COUNT_ORDER
A       F       377518399       566065727797.25 537759104278.0656       559276670892.116819     25.5009751      38237.15100896  0.05000657      14804077
N       F       9851614 14767438399.17  14028805792.2114        14590490998.366737      25.5224483      38257.81066008  0.04997337      385998
N       O       731368004       1096674315157.26        1041836574901.1892      1083522615974.869816    25.49752342     38233.11777294  0.04999894      28683884
R       F       377732830       566431054976    538110922664.7677       559634780885.086257     25.50838479     38251.21927356  0.04999679      14808183

**Comment by nnsgmsone** [comment]
it may be ok.

**Comment by aunjgr** [comment]
TPC-H q1 involves division. The scale of division result is not specified in SQL standard, and each major database has its own rule. So it may not be a bug.

[TPC-H standard](https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v3.0.1.pdf) only uses 2 fractional digits.

**Comment by aunjgr** [comment]
Some examples of scale rule of decimal division:

* SQL server: https://learn.microsoft.com/en-us/sql/t-sql/data-types/precision-scale-and-length-transact-sql?view=sql-server-ver16
* Oracle: https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqlj36146.html
* Snowflake: https://docs.snowflake.com/en/sql-reference/operators-arithmetic.html#label-scale-and-precision-in-arithmetic-operations
* MySQL: https://dev.mysql.com/doc/refman/8.0/en/arithmetic-functions.html

**Comment by aunjgr** [comment]
We should define our own scale rules, and then consistently obey it.

**Comment by fengttt** [comment]
The result we got this time has a NaN.   This cannot be correct.

**Comment by fengttt** [comment]
What is the DDL?    data type of columns

**Comment by aunjgr** [comment]
I can't reproduce it. My result is always

```
l_returnflag    l_linestatus    sum_qty sum_base_price  sum_disc_price  sum_charge      avg_qty avg_price       avg_disc        count_order
A       F       377518399.00    566065727797.25 537759104278.0656       559276670892.116819     25.50   38237.15        0.05    14804077
N       F       9851614.00      14767438399.17  14028805792.2114        14590490998.366737      25.52   38257.81        0.05    385998
N       O       731368004.00    1096674315157.26        1041836574901.1892      1083522615974.869816    25.50   38233.12        0.05    28683884
R       F       377732830.00    566431054976.00 538110922664.7677       559634780885.086257     25.51   38251.22        0.05    14808183
```

The scale is consistent for q1 result.

**Comment by aunjgr** [comment]
Need to confirm

**Comment by nnsgmsone** [comment]
no process

**Comment by aunjgr** [comment]
No progress today

**Comment by aunjgr** [comment]
This is a type inference bug. `l_discount` has type `DECIMAL(15,2)`, so `1 - discount` should also has type `DECIMAL(15,2)`. But the actual result has scale 10.

**Comment by aunjgr** [comment]
working on it

**Comment by aressu1985** [comment]
fixed:
f94cc3a97ba6a7aa55af374655a2dd97fff53920
