### ISSUE TITLE
[Bug]: insert into t select null from t will fail in the second time.

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#7670]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):98e9c71b4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/56761542/212847694-3f679d27-2872-4ec4-b4a2-4b838ffd6430.png)

**Comment by daviszhen** [comment]
something related to the bath

**Comment by nnsgmsone** [comment]
the vector memory is wrong, wait for vector reafctor

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
fixed now
