### ISSUE TITLE
[Bug]: show cloumns from products result  is not accurate

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#7672]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table products (
    -> pid int not null,
    -> pname varchar(50) not null,
    -> description varchar(20) not null,
    -> price decimal(9,2) not null
    -> ) cluster by(pid,pname);
Query OK, 0 rows affected (0.07 sec)

mysql> 
mysql> desc products;
+---------------------------+----------------+------+------+---------+-------+---------+
| Field                     | Type           | Null | Key  | Default | Extra | Comment |
+---------------------------+----------------+------+------+---------+-------+---------+
| pid                       | INT            | NO   |      | NULL    |       |         |
| pname                     | VARCHAR(50)    | NO   |      | NULL    |       |         |
| price                     | DECIMAL(9,2)   | NO   |      | NULL    |       |         |
| __mo_cbkey_003pid005pname | VARCHAR(65535) | YES  |      | NULL    |       |         |
| description               | VARCHAR(20)    | NO   |      | NULL    |       |         |
+---------------------------+----------------+------+------+---------+-------+---------+
The column information of the display table is inconsistent with the actual definition order of the table

**Comment by YANGGMM** [comment]
@qingxinhome, have opened a pr, but still have some bug when the account is not sys account
