### ISSUE TITLE
[Bug]: The statement field in statement_info is formatted incorrectly

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#7673]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

step1: select * from system.statement_info where xxxxxx

while sql include '/n', such as "load data infile '/Users/songli/Documents/git/tpch-dbgen/s10/region.tbl' into table region FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';". The display of the statement column will treat '\n' as a newline character, making it very inconvenient for users to view.

trouble like this:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/31049447/212864494-ba67410c-ba2e-4c7c-9391-f0c4ba3739d1.png">
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/31049447/212864748-cd87e711-8d51-4bf9-9187-45360205f8a0.png">

wanna this:
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/31049447/212865793-1d2b4a78-0f0b-44be-9daa-ec225284e6b7.png">
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/31049447/212865870-2c3ed24d-42b2-4bcc-a222-f0722aba6095.png">

**Comment by daviszhen** [comment]
maybe need escape for the '\n'.

**Comment by xzxiong** [comment]
let me talk to junhong

**Comment by LiSong0214** [comment]
how is going？

**Comment by xzxiong** [comment]
let me fix with pr: adujst query type.

**Comment by xzxiong** [comment]
@LiSong0214 pls check

**Comment by xzxiong** [comment]
@LiSong0214 ptal

**Comment by LiSong0214** [comment]
test ok！
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/31049447/218449343-c2a11ba0-0047-4348-9af8-deb90b1ea740.png">

**Comment by tianyahui-python** [comment]
closed

**Comment by LiSong0214** [comment]
test ok
