### ISSUE TITLE
[Bug]: mo return backend closed after mo decreasing a cn pod 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7683]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-55b4d20b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

error log is :
{"level":"ERROR","time":"2023/01/18 02:50:45.776264 +0000","name":"cn-backend","caller":"morpc/backend.go:200","msg":"connect to remote failed","remote":"mo-ben-tp-cn-1.mo-ben-tp-cn-headless.sudong.svc:6002","backend-id":"8c0f4e6f-b64a-4ff7-842f-86b46f3137fd","error":"backend closed"}
{"level":"ERROR","time":"2023/01/18 02:50:45.776274 +0000","name":"rpc-client[cn-client]","caller":"morpc/client.go:442","msg":"create backend failed","backend":"mo-ben-tp-cn-1.mo-ben-tp-cn-headless.sudong.svc:6002","error":"backend closed"}

**Comment by zhangxu19830126** [comment]
According to the options discussed with @fengttt  yesterday, @w-zr  fixes the hakeeper problem,  @zhangxu19830126  provides the ping mechanism detection, and @nnsgmsone  handles the fault-tolerant handling of the pipeline

**Comment by nnsgmsone** [comment]
no process

**Comment by florashi181** [comment]
7683 issue

**Comment by florashi181** [comment]
@domingozhang  feature issue

**Comment by nnsgmsone** [comment]
This can be converted to a feature

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by JackTan25** [comment]
after finish delete and truncate

**Comment by JackTan25** [comment]
after finish delete and truncate

**Comment by JackTan25** [comment]
after finish delete and truncate

**Comment by JackTan25** [comment]
after finish delete and truncate

**Comment by JackTan25** [comment]
https://github.com/matrixorigin/matrixone/pull/8746

**Comment by JackTan25** [comment]
see #8746

**Comment by JackTan25** [comment]
#8746， I have no time, debuging delete s3

**Comment by JackTan25** [comment]
#9035 is merged

**Comment by aressu1985** [comment]
Test today

**Comment by aressu1985** [comment]
will test tomorrow

**Comment by aressu1985** [comment]
@JackTan25 please continue tracking this issue, it not fixed

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
It is not fixed. @JackTan25 Had you test this yourselft?
After scale-in a cn , mo can not work again

**Comment by m-schen** [comment]
这个错误是可能的。由于未能及时感应到cn的减少，还是将pipeline分配到了这个cn上。在开启用于发送pipeline的流时，由于远端cn已经下线，因此发生了该错误。

**Comment by m-schen** [comment]
今天没看

**Comment by fengttt** [comment]
If we decrease CN, we need to decide policy -- but if it is user/admin initiated number of CN changes, close/abort current query is perfectly fine.    Need further discussion.

Reduce to S1.

**Comment by m-schen** [comment]
今天请假了 没看

**Comment by fengttt** [comment]
Not sure why this is unassigned then reassigned to two people.   @m-schen please give an update that if we should close this one.

**Comment by m-schen** [comment]
该issue还不能关，与cn缩容后能否快速被其他cn感知到有关。
如果有其他feature与之相关的话可以关联。待解决后再关闭该bug。

**Comment by LiSong0214** [comment]
时间太久了，先关了，有新发现再重新开 @m-schen @aressu1985
