### ISSUE TITLE
[Bug]: There is a problem in TargetColDefs when things comes to composite primary key

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#7688]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):570bbb51e54
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
```sql
create table t(a int,b int,primary key(a,b));
insert into t values (3, 4);
insert into t select 3,4 from t;
```
![image](https://user-images.githubusercontent.com/56761542/213124015-f13e2cb8-caee-4480-b7ab-e569f7b17341.png)

### Expected Behavior

All values in a composite primary key should not be null, so NotNull should be true and NullAbility should be false

**Comment by JackTan25** [comment]
https://github.com/matrixorigin/matrixone/pull/7701 zijie is doing this

**Comment by bbbearxyz** [comment]
i will fix it in the later
