### ISSUE TITLE
[Bug]: There is a problem in TargetColDefs when things comes to not null constraint

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#7690]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):570bbb51e54
- Hardware parameters:
- OS type:
- Others: 
```

### Actual Behavior
```sql
create table t(a int not null);
insert into t values (2);
insert into t select 2 from t;
```
![image](https://user-images.githubusercontent.com/56761542/213125094-094540c2-8873-4194-b3a3-08569708c4bb.png)

### Expected Behavior
Similar to #7688

NotNull here should be true.

**Comment by bbbearxyz** [comment]
i will fix it in the later
