### ISSUE TITLE
[Bug]: query external table [tae files] with filters do not get all results.

### ISSUE THREAD

**Issue by mooleetzi** [matrixorigin/matrixone#7697]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

-

**Comment by mooleetzi** [comment]
1. the offset of tae file blocks don't re-init when read another tae files.
2. 1st tae file read completely return nil  cause pipeline stopped, then the 2nd tae file cannot be read.

**Comment by mooleetzi** [comment]
pr merged in zexiong repo, pls help to test @xzxiong .

**Comment by xzxiong** [comment]
checked.
