### ISSUE TITLE
[Bug]: the file does not exist in load flow in distributed MO

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7704]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

srv-129:
cd /data1/zhangxiao/clusterimage-play
vagrant ssh master0
sudo su -
mysql -h 192.168.56.252 -P32392 -uroot -p111
```

### Actual Behavior

MySQL [(none)]> use tpch;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [tpch]> load data local infile '/home/vagrant/lineitem.tbl' INTO TABLE lineitem FIELDS TERMINATED BY '|' lines TERMINATED BY '\n';
ERROR 20301 (HY000): invalid input: the file does not exist in load flow

**Comment by mooleetzi** [comment]
which commit occurs? @domingozhang
