### ISSUE TITLE
[Refactoring]: MemTable need major refactor

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7716]
### Why do you want to refactor this code?

```Markdown
There is a memtable, memorytable, very confusing.   Get rid of one.

Second, let's take a look at the disttae/partition.go Insert code.  There are lots of very inefficient code that has to go.
```

### Describe the solution you'd like

Revisit memtable, memorytable, and why we cannot use DN index.   
Reorg the code.
Redo the disttae partition code.

**Comment by reusee** [comment]
The remaining works in this issue are deletion of the `memtable` package.
Should be done after the CN partition cache refactoring.

**Comment by reusee** [comment]
Done in https://github.com/matrixorigin/matrixone/commit/ebc587b51c0c6d220f0647834a15c62e4fa8d0e6

**Comment by reusee** [comment]
All done, re-assinging.
