### ISSUE TITLE
[Feature Request]: Real Impl of table partition

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#7717]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
We dont have the full story yet.   There is no design.

How the partition is used, proxy, split insert stream?   Load?
```

### Describe the feature you'd like

Full design doc.

DDL/DML/Query Plan.   Insert/Load split into partitions.

CN/DN protocol.  

Proxy.

**Comment by daviszhen** [comment]
What is the complete representation of this feature? What do I need to do?

**Comment by daviszhen** [comment]
the overall design doc https://github.com/matrixorigin/docs/blob/main/design/partition.md

**Comment by daviszhen** [comment]
0.8 scope:
1, HASH，KEY两种分区。
2，DML。不跟外键结合。
3，提升性能方面。感觉0.8做不完了。

**Comment by qingxinhome** [comment]
The partition requirement has been implemented (excluding the partition system view), please test it @fengttt @heni02 @daviszhen

**Comment by heni02** [comment]
0.8 test done
