### ISSUE TITLE
[Bug]: after truncate table ,show table secondary key is error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7740]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2f1e17764761fc8b0e279837bed65c611f44f9b5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

show create table create_secondary_01;
Table    Create Table
create_secondary_01    CREATE TABLE `create_secondary_01` (\n`col1` BIGINT DEFAULT NULL,\n`col2` VARCHAR(25) DEFAULT NULL,\n`col3` FLOAT DEFAULT NULL,\n`col4` VARCHAR(50) DEFAULT NULL,\n`col5` INT DEFAULT NULL,\nPRIMARY KEY (`col1`),\nUNIQUE KEY `col2` (`col2`),\nKEY `secondary_key` (`col4`,`col5`)\n)
drop index secondary_key on create_secondary_01;
truncate table create_secondary_01;
show create table create_secondary_01;
Table    Create Table
create_secondary_01    CREATE TABLE `create_secondary_01` (\n`col1` BIGINT DEFAULT NULL,\n`col2` VARCHAR(25) DEFAULT NULL,\n`col3` FLOAT DEFAULT NULL,\n`col4` VARCHAR(50) DEFAULT NULL,\n`col5` INT DEFAULT NULL,\nPRIMARY KEY (`col1`),\nUNIQUE KEY `col2` (`col2`)\n)

**Comment by bbbearxyz** [comment]
this bug is because you drop index and then show create table, please confirm it and close the issue.

**Comment by heni02** [comment]
confirm,closed

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by heni02** [comment]
remove tag tomorrow

**Comment by heni02** [comment]
remove tag tomorrow
