### ISSUE TITLE
[Bug]: load data  key about starting by '' is not working

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7747]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2f1e17764761fc8b0e279837bed65c611f44f9b5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/215655465-69f73c7b-42cf-4d6c-a509-f9605c6a1a82.png)
The correct result should be
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/113406637/215656759-bb4d3546-67c2-4320-9d7e-47a03e1ccca0.png">

### Steps to Reproduce

```Markdown
sql:
create table table_a(col1 varchar(20),col2 char(10),col3 varchar(20));
load data infile '/Users/heni/test_data/string.csv' into table table_a lines starting by 'aaa' terminated by '\n';

string.csv
"aaa_this","aaa_yellow","aaa_poly"
"aaa123","345","aaa890"
```

**Comment by fengttt** [comment]
This feature is too random.   I would suggest not to impl it.    Make sure the sql load fail with good error message.

**Comment by heni02** [comment]
confirm,closed
commit id : 2d5a3ab3fb0c7ca944db799f3693d12c49ff2276
![image](https://user-images.githubusercontent.com/113406637/224661960-e9d27d1a-7ef3-40d9-a135-461f8da89aec.png)
