### ISSUE TITLE
[Bug]: Aggregation functions sometimes do not compute accurately

### ISSUE THREAD

**Issue by jensenojs** [matrixorigin/matrixone#7748]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):46a417daf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/56761542/215661537-250f6dea-543e-4158-85b4-65358575a1be.png)

**Comment by sukki37** [comment]
bvt link: https://github.com/matrixorigin/matrixone/actions/runs/4050589879

**Comment by fengttt** [comment]
At least you should provide a script that repros this bug.

**Comment by jensenojs** [comment]
This bug is not easy to reproduce, will try to insert random time delays inside agg for a stronger test tomorrow while checking the logic related to morpc more carefully.

**Comment by jensenojs** [comment]
In the multi-cn configuration, I tried to reduce the block size to reproduce the problem, but without success.
![image](https://user-images.githubusercontent.com/56761542/216221218-73a0e641-f0cf-4ab9-b261-288a74cfecca.png)

**Comment by jensenojs** [comment]
Still thinking about how to trigger this bug consistently, The idea is to allow morpc's memory to be used by other SQL with a higher probability, which might cause avg results to be incorrect.

What has been tried (and failed) so far, 
1.  Force go remoteRun, start under multi-cn
2. set DefaultBlockMaxRows and DefaultBlocksPerSegment as 2
3.  Batch and aggInfo's UnmarshalBinary add sleep time.
4. before AVG query, run a lot of other SQL

**Comment by jensenojs** [comment]
working on

**Comment by jensenojs** [comment]
Currently in the integration test framework also did not reproduce successfully, ready to introduce more intense competition

**Comment by jensenojs** [comment]
stable reproduction success
https://github.com/jensenojs/matrixone/tree/fix_7748

**Comment by nnsgmsone** [comment]
can't reproduce the bug, I'll add the message detection first to make sure the message is correct.

**Comment by heni02** [comment]
At present, bvt case is passed and can be closed @jensenojs

**Comment by jensenojs** [comment]
The question came up again
https://github.com/matrixorigin/matrixone/actions/runs/4142485427/jobs/7163210857 https://github.com/matrixorigin/matrixone/actions/runs/4142542020/jobs/7163330594 

Previously diagnosed in the wrong direction, may not be writing competition, and does not see the problem of morpc. Still need to continue to check

**Comment by jensenojs** [comment]
Previously the errors were focused on the multi-CN e2e BVT Test, but now two examples have been caught for the e2e BVT Test：
https://github.com/matrixorigin/matrixone/actions/runs/4161312772/jobs/7199144535
https://github.com/matrixorigin/matrixone/actions/runs/4142542020/jobs/7163330594

**Comment by jensenojs** [comment]
working on

**Comment by jensenojs** [comment]
working on

**Comment by jensenojs** [comment]
working on

**Comment by jensenojs** [comment]
working on it

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
Thore two reproduce try has more detail log. 

# [1](https://github.com/jensenojs/matrixone/actions/runs/4291001063/jobs/7475642735)
I printed out the actual execution of the Scopes Tree and recalculated avg in the following three places to confirm when the problem occurred.
1. before entering the Group arithmetic (i.e. after reading the data), and
2. after the Group operator, and
3. after the MergeGroup operator
![image](https://user-images.githubusercontent.com/56761542/221814477-27a0afe4-1098-48b6-a9f5-49ed7a1e270e.png)

The result is as follows, the log for place 1 is not printed under this replication (by mistake), **but it can be inferred that the read data is faulty before the group operator is entered**
![image](https://user-images.githubusercontent.com/56761542/221813796-451f68aa-e7ea-4b40-9510-cc0abc954a95.png)

# [2](https://github.com/JackTan25/matrixone/actions/runs/4290439754/jobs/7474458137)

It's hard to explain what these logs mean on github, it simply means that a block that shouldn't have been read up before entering the group was actually read up【8192，637538304】, causing avg to calculate the data incorrectly ( You will find that after removing the block, the calculation is correct)
![1677578368956](https://user-images.githubusercontent.com/56761542/221819406-6670d07f-c954-4989-99e3-f389eb64dcac.jpg)

# Conclusion
Perhaps there are still some corner cases in transaction visibility that have not been taken into account, and more log reproductions are still under way.

**Comment by jensenojs** [comment]
https://github.com/jensenojs/matrixone/actions/runs/4300446106/jobs/7496640097

1: append block 2: delte append block 3: block

目前怀疑是dn把appendable block 传递到cn过程中哪里出了问题。导致软刷的数据没有删除干净。所以读取了重复的数据。

**Comment by YANGGMM** [comment]
![61677740013_ pic](https://user-images.githubusercontent.com/26563383/222355624-1e3c7b28-9876-4b09-ae99-dbe2a202a851.jpg)

**Comment by jensenojs** [comment]
expected : 内存的行数- 软刷*8192 + 硬刷*8192 = 总行数n
https://github.com/jensenojs/matrixone/actions/runs/4312737017/jobs/7538867958
这个复现还是有一个log没有打，再等一次复现就可以了诊断是cn的问题还是dn的问题了。
![Uploading image.png…]()

**Comment by jensenojs** [comment]
dn有把软刷的blockid传递过来，同时Snapshot的时间戳也在blockId被删除的时间戳之后，因此有可能是memtable的实现有问题，也有可能是blockid是错的，暂时不考虑第二种可能，等相关逻辑重构完再复检一下吧。

<img width="1399" alt="3220e5211934c1da8d9161e6fafd754" src="https://user-images.githubusercontent.com/56761542/222664756-b0d78cf6-b3a6-4cac-94a3-3f61430c3474.png">


> https://github.com/jensenojs/matrixone/actions/runs/4300446106/jobs/7496640097
> 
> 1: append block 2: delte append block 3: block
> 
> 目前怀疑是dn把appendable block 传递到cn过程中哪里出了问题。导致软刷的数据没有删除干净。所以读取了重复的数据。

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/4290037359/jobs/7473645274

**Comment by nnsgmsone** [comment]
I will devote myself to dealing with this.

**Comment by nnsgmsone** [comment]
I reran a day with the latest code without recurrence.

**Comment by sukki37** [comment]
repro:

**Comment by m-schen** [comment]
发生错误时，t1读了5个block的数据（40960）行。

**Comment by m-schen** [comment]
目前只能确定刷盘是触发错误的必要条件。
最后一次
        insert into t select * from t本该写入32768行数据。
出过以下情况：
1.   内存3个块，刷盘1个块 ：写入40960
2.   内存0个块，刷盘4个块 ： 写入40960
3.  内存2个块，刷盘2个块  ： 写入16384

造不出稳定复现的用例。

**Comment by m-schen** [comment]
> 已确定出错的时候读取刷盘的块没有问题，读取memory table时存在多读和少读的现象。正在复现和确定读取出来的数据的时间戳

读memory table没问题，昨天的定位有误。发生错误时，读memory table数据正确，读flush后的block的id也对得上。目前打了insert算子的出入口，以及cn写batch，dn接收batch的日志，暂时没有复现。

**Comment by fengttt** [comment]
Repro steps on local machine using launch-tae-multi-CN-tae-DN. 

There are two scripts.   The first one

ftian@DESKTOP-16FCU43:~/tmp$ cat bug.sql
use ftian;

drop table if exists bugt;
create table bugt (i int, j int, k int, s varchar(100));

insert into bugt values (1, 1, 1, 'foobarzoo okok foo bar zoo');

insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
-- select mo_ctl('dn', 'checkpoint', '');
select mo_ctl('dn', 'flush', 'ftian.bugt');
select count(*) from bugt;

insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
-- select mo_ctl('dn', 'checkpoint', '');
select mo_ctl('dn', 'flush', 'ftian.bugt');
select count(*) from bugt;

insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
-- select mo_ctl('dn', 'checkpoint', '');
select mo_ctl('dn', 'flush', 'ftian.bugt');
select count(*) from bugt;

insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
-- select mo_ctl('dn', 'checkpoint', '');
select mo_ctl('dn', 'flush', 'ftian.bugt');
select count(*) from bugt;

insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
insert into bugt select * from bugt;
-- select mo_ctl('dn', 'checkpoint', '');
select mo_ctl('dn', 'flush', 'ftian.bugt');
select count(*) from bugt;
ftian@DESKTOP-16FCU43:~/tmp$

**Comment by fengttt** [comment]
So I just open two terminals, each running one scripts continuously.

The insert script should ends up with something like these, 
mo_ctl(dn, flush, ftian.bugt)
{\n  "method": "Flush",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
count(*)
33554432


However, if you keep the sleep script running, and repeat insert scripts for a few times you end up with 
ftian@DESKTOP-16FCU43:~/tmp$ mocli < bug.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
mo_ctl(dn, flush, ftian.bugt)
{\n  "method": "Flush",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
count(*)
32
mo_ctl(dn, flush, ftian.bugt)
{\n  "method": "Flush",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
count(*)
1536
mo_ctl(dn, flush, ftian.bugt)
{\n  "method": "Flush",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
count(*)
49152
mo_ctl(dn, flush, ftian.bugt)
{\n  "method": "Flush",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
count(*)
1572864
mo_ctl(dn, flush, ftian.bugt)
{\n  "method": "Flush",\n  "result": [\n    {\n      "returnStr": "OK"\n    }\n  ]\n}\n
count(*)
50331648

**Comment by m-schen** [comment]
the source cause is : 
CN missed the address when rewriting the cn list got from cluster info. This causes CN to mistakenly assume that there are multiple CN nodes when constructing logical pipelines. 
Multi logical pipeline run at one CN node may cause dirty data on workspace (pipeline1 wrote data to workspace, but pipeline2 which want to scan the workspace may just start to make a snapshot for workspace).

I have fixed this bug at pr 8540.

**Comment by m-schen** [comment]
昨天跑了个偶现错误，今天新修改了一些地方，不确定是否已经修复。pr待验证。

**Comment by m-schen** [comment]
已确定修复了insert select导致多数据的问题，似乎还存在少数据的情况，不确定和该issue是否类似。
目前加了日志，先合并。如果出现了情况再进行定位。

**Comment by sukki37** [comment]
> 这个issue可以先关了，后续如果发生了少数据的情况。麻烦用新的issue进行追踪该问题。

open #9117
