### ISSUE TITLE
[Bug]: time zone set impossible value gets through

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#7753]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):  0c816c0924038aa8baf5c6474e28ef68ff4e6b5c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

At the time of 2023-01-31  15:04 Beijing time. 

mysql> set @@time_zone = '+05:99';
Query OK, 0 rows affected (0.04 sec)

mysql> select now();
+----------------------------+
| now()                      |
+----------------------------+
| 2023-01-31 13:39:49.339506 |
+----------------------------+
1 row in set (0.04 sec)

**Comment by dengn** [comment]
mysql> set @@time_zone = '+05:99';
ERROR 20101 (HY000): internal error: incorrect timezone +05:99

Can we remove this internal error in the error message? just keep it as: ERROR 20101 (HY000): incorrect timezone +05:99

mysql> set @@time_zone = '+05:9';
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [5] with length 5: 
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/frontend.updateTimeZone
        /root/matrixone/pkg/frontend/variables.go:1290
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).SetSessionVar
        /root/matrixone/pkg/frontend/session.go:812
github.com/matrixorigin/matrixone/pkg/frontend.doSetVar.func1
        /root/matrixone/pkg/frontend/mysql_cmd_executor.go:598
github.com/matrixorigin/matri

gets a panic when i'm not setting a good value

**Comment by aunjgr** [comment]
#8692 fixes that panic.

For the error message, we should choose one error code from `pkg/common/moerr/error.go`. Maybe `internal error` is not suitable here. But we need to choose one. Let me know if you have a better choice.

**Comment by dengn** [comment]
commit id: 0b1c9988

the panic is fixed. 

mysql> set @@time_zone = '+05:99';
ERROR 20101 (HY000): internal error: incorrect timezone +05:99
mysql> set @@time_zone = '+05:9';
ERROR 20101 (HY000): internal error: incorrect timezone +05:9

Please take a loot at the error message.  @domingozhang

**Comment by domingozhang** [comment]
I suggest use this error code  of mysql

Error number: MY-010109; Symbol: [ER_WRONG_DATETIME_SPEC]; SQLSTATE: HY000

Message: Wrong date/time format specifier: %s

**Comment by dengn** [comment]
test ok

mysql> set @@time_zone = '+05:99';
ERROR 10109 (HY000): wrong date/time format specifier: +05:99
mysql> set @@time_zone = '+05:9';
ERROR 10109 (HY000): wrong date/time format specifier: +05:9
