### ISSUE TITLE
[Bug]: The cost of loading data for table with pk is much more than table without pk 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7754]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 46a417d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

for example:
load tpch 100G data to orders table

cost of table orders with pk is :889.126
cost of table table without pk is : 60.056

**Comment by reusee** [comment]
This may be done in 0.8

**Comment by reusee** [comment]
The root cause is the primary key de-duplication in DN.
CN will add more primary key de-duplication which will slow the process more, not relevant to this issue.

**Comment by XuPeng-SH** [comment]
Root cause:
1. The metadata is very scattered since each object only contains 1 block when `CN` loads data into the s3 object
2. When loading data, 'CN' doesn't do deduplication in a transaction, and 'DN' needs to load metadata and pk columns to do in-transaction deduplication
3. 'DN' does deduplication in a serial way, there is some room for improvement

**Comment by XuPeng-SH** [comment]
0.8 scope

**Comment by JackTan25** [comment]
yueshen is doing primary check

**Comment by domingozhang** [comment]
perfromance with primary key needs almost as good as it without pk, less than 10% gap can be acceptable

**Comment by XuPeng-SH** [comment]
cn will do dedup later

**Comment by JackTan25** [comment]
for yuesheng @reusee  do pk optimize

**Comment by JackTan25** [comment]
for yuesheng @reusee do pk optimize

**Comment by reusee** [comment]
@w-zr is responsible for primary key de-duplication checking in 0.8

**Comment by w-zr** [comment]
This issue is related with #6949.

**Comment by w-zr** [comment]
This issue is the same as #6949. will be fixed after primary key check in CN completed.

**Comment by w-zr** [comment]
Now refactoring insert.

**Comment by fengttt** [comment]
@w-zr please consider adding an option to load that explicit says skip primiry key/uniq key check.

**Comment by w-zr** [comment]
With CN primary key check enabled,  loading 1g tpch data with primary key costs 23.91s on my machine.
loading same data without primary key costs 12.09s on the same machine.
Compared with previous result, the load performance is improved.
@aressu1985

**Comment by aressu1985** [comment]
fixed
