### ISSUE TITLE
[Bug]: Poor Performance of LOAD DATA into table with primary key

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7760]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/88298673/215714290-ec739e76-ba2c-4ea5-be44-8fa3f9b10320.png)

Primary key check consumption  is higher than other phase

**Comment by domingozhang** [comment]
similar as https://github.com/matrixorigin/matrixone/issues/7754

**Comment by fengttt** [comment]
dup
