### ISSUE TITLE
[Bug]: statement_info table,Repeated collection of data.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7765]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):bc82be2b94c17915c6eef6ea412ace16dc2ec3ff
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

show procedure status;
show config;
show events;
show plugins;
show profiles;
show privileges;
show processlist;
show tables;
show collation;
show collation like '%';
show index from test_table;
values row(1,1), row(2,2), row(3,3) order by column_0 desc;
WITH cte1 AS (SELECT 1),cte2 AS (SELECT 2) SELECT * FROM cte1 join cte2;

select statement,query_type,sql_source_type from  statement_info where user="dump" and sql_source_type="external_sql" order by request_at desc limit 30;

<img width="1659" alt="截屏2023-01-31 19 19 25" src="https://user-images.githubusercontent.com/39303074/215746765-795dccb5-c01f-44e9-94c0-94dd9dd359c1.png">

**Comment by xzxiong** [comment]
pls update mo version.
already fixed in https://github.com/matrixorigin/matrixone/pull/7737, same issue as https://github.com/matrixone-cloud/mocloud-services/issues/259
