### ISSUE TITLE
[Bug]: tpcc batch insert data error:message body 325439679 is too large, max is 104857600 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7767]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2bbb0b7090957920d0bb3a776735bbb97e75b6c2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when batch inserting tpcc 1 warehouse data to mo, error occure:

[sudong@VM-16-14-centos mo-tpcc]$ ./runLoader.sh props.mo warehouse 1
Starting BenchmarkSQL LoadData

props.mo
driver=com.mysql.cj.jdbc.Driver
conn=jdbc:mysql://127.0.0.1:6001/tpcc?characterSetResults=utf8&continueBatchOnError=false&useServerPrepStmts=true&alwaysSendSetIsolation=false&useLocalSessionState=true&zeroDateTimeBehavior=CONVERT_TO_NULL&failoverReadOnly=false&serverTimezone=Asia/Shanghai&enabledTLSProtocols=TLSv1.2&useSSL=false
user=dump
password=***********
warehouses=1
loadWorkers=4
fileLocation (not defined)
csvNullValue (not defined - using default '')

Worker 000: Loading ITEM
Worker 001: Loading Warehouse      1
Worker 000: Loading ITEM done
java.sql.SQLException: internal error: message body 325439679 is too large, max is 104857600
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813)
	at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:765)
	at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
	at java.lang.Thread.run(Thread.java:748)
Worker 001: ERROR: internal error: message body 325439679 is too large, max is 104857600

mo error log:
2023/01/31 21:41:11.888260 +0800 INFO frontend/util.go:515 rowCount 6
time of getDataFromPipeline : 19.206µs
processBatchTime 17.653µs
row2colTime 0s
allocateOutBufferTime 281ns
outputQueue.flushTime 0s
processBatchTime - row2colTime - allocateOutbufferTime - flushTime 17.372µs
restTime(=tTime - row2colTime - allocateOutBufferTime) 18.925µs
protoStats flushCount 0 writeCount 1
writeBytes 0 0 MB
 connectionId 1097
2023/01/31 21:41:11.888289 +0800 INFO frontend/util.go:515 time of Exec.Run : 215.664µs connectionId 1097
2023/01/31 21:41:11.888345 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 1097, "statement": "select cron_task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, cron_expr, next_time, trigger_times, create_at, update_at from mo_task.sys_cron_task", "status": "success", "span": {"trace_id": "ecbf78a8-a16c-11ed-8d9f-525400777c3a", "kind": "statement"}, "session_info": "connectionId 1097"}
2023/01/31 21:41:13.133487 +0800 ERROR frontend/mysql_cmd_executor.go:4662 error: internal error: serialize plan to json error: json: unsupported value: NaN {"span": {"trace_id": "265edc09-8ac0-9206-d061-bd9e25bac576", "span_id": "73856164f3a208d4"}}
github.com/matrixorigin/matrixone/pkg/frontend.serializePlanToJson
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4662
github.com/matrixorigin/matrixone/pkg/frontend.glob..func17
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4698
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*StatementInfo).ExecPlan2Json
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/trace/impl/motrace/report_statement.go:169
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*StatementInfo).CsvFields
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/trace/impl/motrace/report_statement.go:137
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.genCsvData.func1
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/trace/impl/motrace/buffer_pipe.go:181
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.genCsvData
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/trace/impl/motrace/buffer_pipe.go:196
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doGenerate
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/batch_processor.go:343
2023/01/31 21:41:14.200180 +0800 INFO frontend/util.go:500 query trace {"connection_id": 1097, "query": "use mo_task", "session_info": "connectionId 1097"}
2023/01/31 21:41:14.201082 +0800 INFO frontend/util.go:515 User 9a4c0b8d-3f24-4c5e-84a2-cb73d0eeb36b change database from [mo_task] to [mo_task] connectionId 1097
2023/01/31 21:41:14.201137 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 1097, "statement": "use mo_task", "status": "success", "span": {"trace_id": "ee208610-a16c-11ed-8d9f-525400777c3a", "kind": "statement"}, "session_info": "connectionId 1097"}
2023/01/31 21:41:14.201170 +0800 INFO frontend/util.go:500 query trace {"connection_id": 1097, "query": "show tables", "session_info": "connectionId 1097"}
2023/01/31 21:41:14.202921 +0800 INFO frontend/util.go:515 time of Exec.Build : 1.723985ms connectionId 1097
2023/01/31 21:41:14.203247 +0800 INFO frontend/util.go:515 rowCount 2
time of getDataFromPipeline : 4.438µs
processBatchTime 3.166µs
row2colTime 0s
allocateOutBufferTime 240ns
outputQueue.flushTime 0s
processBatchTime - row2colTime - allocateOutbufferTime - flushTime 2.926µs
restTime(=tTime - row2colTime - allocateOutBufferTime) 4.198µs
protoStats flushCount 0 writeCount 1
writeBytes 0 0 MB
 connectionId 1097
2023/01/31 21:41:14.203268 +0800 INFO frontend/util.go:515 time of Exec.Run : 282.269µs connectionId 1097
2023/01/31 21:41:14.203324 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 1097, "statement": "show tables", "status": "success", "span": {"trace_id": "ee20ac09-a16c-11ed-8d9f-525400777c3a", "kind": "statement"}, "session_info": "connectionId 1097"}

### Steps to Reproduce

```Markdown
1. git clone https://github.com/matrixorigin/mo-tpcc.git
2. create database and table by sql/tableCreates.sql
3. ./runLoader.sh props.mo warehouse 1
```

**Comment by jensenojs** [comment]
> it is because large batch insert do not through the s3. so help to solve it. @jensenojs

Still looking for the exact problem

**Comment by jensenojs** [comment]
## Current Situation
- insert value do not go throught the s3, that is correct. But when it comes to inserting a particularly large number of data, it will automatically insert in batches (4096 rows in a batch), so it is not the reason for this issue
- however, the function commit in distae (genWriteReqs)  does write more than 200,000 lines (that is, it should trigger s3), and this serialization may cause morpc's package to be too large

## Conclusion
- This issue needs to wait for cn support to do update and delete directly to s3 after further testing.
- insert value go throught s3 may still needed considering the performance improvement

**Comment by jensenojs** [comment]
working on #7748

**Comment by aressu1985** [comment]
2023/02/07 11:33:30.257769 +0800 ERROR frontend/util.go:510 query trace status {"connection_id": 1016, "statement": "load data infile /data1/sudong/mo-load-data/data/tpch_100/lineitem.tbl into table tpch_100g.lineitem fields terminated by \"|\" lines terminated by \"\\n\"", "status": "fail", "error": "context deadline exceeded", "span": {"trace_id": "3c989dc0-a696-11ed-aca8-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1016"}

**Comment by jensenojs** [comment]
not process

**Comment by jensenojs** [comment]
working on

**Comment by jensenojs** [comment]
working on

**Comment by jensenojs** [comment]
reproduction successfully, later will fix it
![image](https://user-images.githubusercontent.com/56761542/220053392-b04ffae7-66b6-42ac-a31a-d1566af412f5.png)

**Comment by jensenojs** [comment]
No process

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
On leave of absence

**Comment by w-zr** [comment]
@JackTan25 is now working on this issue.

**Comment by JackTan25** [comment]
See #8325

**Comment by JackTan25** [comment]
#8325 is merged

**Comment by aressu1985** [comment]
test today

**Comment by aressu1985** [comment]
This operation still can not succeed, the error is :
[sudong@VM-16-14-centos sql]$ cd ..
[sudong@VM-16-14-centos mo-tpcc]$ ./runLoader.sh props.mo warehouse 1
Starting BenchmarkSQL LoadData

props.mo
driver=com.mysql.cj.jdbc.Driver
conn=jdbc:mysql://127.0.0.1:6001/tpcc?characterSetResults=utf8&continueBatchOnError=false&useServerPrepStmts=true&alwaysSendSetIsolation=false&useLocalSessionState=true&zeroDateTimeBehavior=CONVERT_TO_NULL&failoverReadOnly=false&serverTimezone=Asia/Shanghai&enabledTLSProtocols=TLSv1.2&useSSL=false
user=dump
password=***********
warehouses=1
loadWorkers=4
fileLocation (not defined)
csvNullValue (not defined - using default '')

Worker 000: Loading ITEM
Worker 001: Loading Warehouse      1
Worker 000: Loading ITEM done

java.sql.SQLException: context deadline exceeded
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:813)
	at io.mo.LoadDataWorker.loadWarehouse(LoadDataWorker.java:765)
	at io.mo.LoadDataWorker.run(LoadDataWorker.java:196)
	at java.lang.Thread.run(Thread.java:748)
Worker 001: ERROR: context deadline exceeded

@JackTan25 pls check again

**Comment by JackTan25** [comment]
working on s-1

**Comment by JackTan25** [comment]
ctx deadline bug ,will check next monday

**Comment by gavinyue** [comment]
[mysql] 2023/04/27 22:37:35 packets.go:37: read tcp 127.0.0.1:49839->127.0.0.1:16001: i/o timeout
[mysql] 2023/04/27 22:37:35 packets.go:37: read tcp 127.0.0.1:49840->127.0.0.1:16002: i/o timeout
[mysql] 2023/04/27 22:37:40 packets.go:37: read tcp 127.0.0.1:49844->127.0.0.1:16001: i/o timeout
[mysql] 2023/04/27 22:37:50 packets.go:37: read tcp 127.0.0.1:49862->127.0.0.1:16001: i/o timeout
[mysql] 2023/04/27 22:37:55 packets.go:37: read tcp 127.0.0.1:49871->127.0.0.1:16001: i/o timeout
[mysql] 2023/04/27 22:38:00 packets.go:37: read tcp 127.0.0.1:49898->127.0.0.1:16001: read: connection reset by peer
[mysql] 2023/04/27 22:38:00 packets.go:37: read tcp 127.0.0.1:49891->127.0.0.1:16001: read: connection reset by peer
[mysql] 2023/04/27 22:38:00 packets.go:122: closing bad idle connection: EOF
[mysql] 2023/04/27 22:38:00 packets.go:37: unexpected EOF
[mysql] 2023/04/27 22:38:00 packets.go:37: unexpected EOF
[mysql] 2023/04/27 22:38:00 packets.go:37: unexpected EOF

**Comment by gavinyue** [comment]
After running the tpcc for a few seconds, the connection starts to timeout.

**Comment by gavinyue** [comment]
The above error is from the task service. The reason is that the long running insert can prevent CN accepting new connections.

**Comment by gavinyue** [comment]
related https://github.com/matrixorigin/matrixone/issues/9647

**Comment by gavinyue** [comment]
Do not see this type of error anymore recently. Probably could close.

**Comment by fengttt** [comment]
@gavinyue please reassign to test.    thank you.

**Comment by gavinyue** [comment]
Reassgian to test. tpcc batch insert may have other issues, but do not see this one after few tries.

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/9866

Fix in this pr

**Comment by aressu1985** [comment]
fxied
