### ISSUE TITLE
[Bug]: mo killed by oom when run tpch 10 Q5 query with table without priamary key 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7768]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ea7c3fa906e3b6d15dca44cc387ad1113843b1f6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[Tue Jan 31 22:48:54 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=d07aae90e90516ae9556d5a31d183a67379211ebde317250dd253922120fa97d,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-0.slice/session-714.scope,task=mo-service,pid=1519467,uid=1030
[Tue Jan 31 22:48:54 2023] Out of memory: Killed process 1519467 (mo-service) total-vm:267661244kB, anon-rss:238800340kB, file-rss:0kB, shmem-rss:0kB, UID:1030 pgtables:482148kB oom_score_adj:0

### Steps to Reproduce

```Markdown
1. git clone https://github.com/matrixorigin/mo-tpch.git
2. modify mo.ddl, remove all the primary key
3. ./run.sh -g -s 10
   ./run.sh -c -s 10
   ./run.sh -l -s 10
   ./run.sh -q all -s 10
```

**Comment by nnsgmsone** [comment]
let me see see

**Comment by dongdongyang33** [comment]
10G q5 would not get the OOM now.
It becomes the same error as #7769

**Comment by dongdongyang33** [comment]
update info in 7769

**Comment by fengttt** [comment]
Taking off s-1.

**Comment by dongdongyang33** [comment]
wrong join order

**Comment by aunjgr** [comment]
@aressu1985 It should be fixed by #8398. Please try it again.

**Comment by aressu1985** [comment]
On testing

**Comment by aressu1985** [comment]
fixed:
98a464d9be26b092a041ed4a1d9346033b74736b
