### ISSUE TITLE
[Bug]: load data of tpch 100g  for lineitem table with primary key error and mo crash

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7770]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ea7c3fa906e3b6d15dca44cc387ad1113843b1f6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023/02/01 01:57:19.527274 +0800 ERROR mpool/mpool.go:506 error: internal error: Invalid alloc size 2147483648
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Alloc
        /data1/sudong/matrixone/pkg/common/mpool/mpool.go:506
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand
        /data1/sudong/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:75
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append
        /data1/sudong/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:162
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append
        /data1/sudong/matrixone/pkg/vm/engine/tae/containers/vecbase.go:78
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append
        /data1/sudong/matrixone/pkg/vm/engine/tae/containers/vector.go:177
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*simpleTableIndex).KeyToVector
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/index.go:105
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).GetPKColumn
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:437
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PrePrepareDedup
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:832
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PrePrepare
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:499
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PrePrepare
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:575
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PrePrepare
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:349
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrePrepare
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:210
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).dequeuePreparing
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:361
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1
        /data1/sudong/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:81
panic: internal error: Invalid alloc size 2147483648

goroutine 1778 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).tryExpand(0xc53fb83680?, 0x41e6ff)
        /data1/sudong/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:77 +0x1d1
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).Append(0xc53fb83680?, 0x33d8544)
        /data1/sudong/matrixone/pkg/vm/engine/tae/stl/containers/stdvec.go:162 +0x48
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).Append(0xc9a579a988?, {0x239d9a0?, 0xc0f3b49408?})
        /data1/sudong/matrixone/pkg/vm/engine/tae/containers/vecbase.go:78 +0x82
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).Append(0xccd19232f8?, {0x239d9a0?, 0xc0f3b49408?})
        /data1/sudong/matrixone/pkg/vm/engine/tae/containers/vector.go:177 +0x32
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*simpleTableIndex).KeyToVector(0xc1ff966dc0, {0x17, 0x0, 0x0, 0x0, 0x8, 0x40, 0x0, 0x0})
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/index.go:105 +0x164
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).GetPKColumn(0xc03311cbd8?)
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/localseg.go:437 +0x82
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).PrePrepareDedup(0xc19a9b06c0)
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/table.go:832 +0x69
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).PrePrepare(0xc5329025a0)
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/txndb.go:499 +0x226
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).PrePrepare(0xc413414320)
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnimpl/store.go:575 +0xef
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*Txn).PrePrepare(0xc03311cc28?)
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnbase/txn.go:349 +0x25
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).onPrePrepare(0xc000166d20?, 0xc2a2e8edb0)
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:210 +0x11f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnbase.(*TxnManager).dequeuePreparing(0xc000166d20, {0xc007380000, 0x1, 0x0?})
        /data1/sudong/matrixone/pkg/vm/engine/tae/txn/txnbase/txnmgr.go:361 +0x42b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start.func1()
        /data1/sudong/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:81 +0x1f1
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/sm.(*safeQueue).Start
        /data1/sudong/matrixone/pkg/vm/engine/tae/logstore/sm/safeq.go:60 +0xea
[tpch100g.ordererror.log.tar.gz](https://github.com/matrixorigin/matrixone/files/10549488/tpch100g.ordererror.log.tar.gz)

**Comment by daviszhen** [comment]
It maybe the tae's problem.

**Comment by JackTan25** [comment]
for now, don't use delete and update in begin transaction if you trigger the write-s3.

**Comment by triump2020** [comment]
@aressu1985  #7819 had fixed it , pls test.

**Comment by triump2020** [comment]
Maybe the deduplication or loading pks  caused "context timeout" by DN

**Comment by aressu1985** [comment]
fixed
