### ISSUE TITLE
[Bug]: Service crash caused by sql execution.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7772]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84db18673d85dc44eca69bba097c5c9fb25f6298
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

execute sql:
begin;
create database test_db;
use test_db;
create table test_table(
col1 int,
col2 varchar
);
create view test_view as select * from test_table;
show create database test_db;
show create table test_table;
show triggers;
show procedure status;
show config;
show events;
show plugins;
show profiles;
show privileges;
show processlist;
show tables;
show index from test_table;
values row(1,1), row(2,2), row(3,3) order by column_0 desc;
WITH cte1 AS (SELECT 1),cte2 AS (SELECT 2) SELECT * FROM cte1 join cte2;
load data infile 'xxx/test.csv' into table test_table;
insert into test_table values (1,'a'),(2,'b'),(3,'c');
update test_table set col2='xxx' where col1=1;
delete from test_table where col1=3;

test.csv data:
1,"a"

<img width="1552" alt="截屏2023-02-01 09 38 26" src="https://user-images.githubusercontent.com/39303074/215926094-0b947386-7657-47aa-a24e-336f5731fe52.png">
<img width="1583" alt="截屏2023-02-01 09 39 42" src="https://user-images.githubusercontent.com/39303074/215926105-b4ebd608-13bb-4184-a891-335f9bdc0d69.png">

log:
[mo.log.tar.gz](https://github.com/matrixorigin/matrixone/files/10552540/mo.log.tar.gz)

**Comment by JackTan25** [comment]
this will be fixed after cn-write-s3 delete

**Comment by JackTan25** [comment]
for now, don't use delete and update in begin transaction if you trigger the write-s3.

**Comment by florashi181** [comment]
relate to the feature issue in v0.8

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
will fix it after cn-write-s3 delete/update

**Comment by JackTan25** [comment]
this week give the delete pr

**Comment by JackTan25** [comment]
we have new requirement about lock

**Comment by JackTan25** [comment]
we have new requirement about lock

**Comment by JackTan25** [comment]
working on s-1

**Comment by JackTan25** [comment]
delete pr will be supported

**Comment by JackTan25** [comment]
#8911

**Comment by JackTan25** [comment]
@tianyahui-python please test it

**Comment by tianyahui-python** [comment]
<img width="782" alt="截屏2023-05-07 下午12 10 07" src="https://user-images.githubusercontent.com/39303074/236657176-72555b8c-b96e-41df-94f6-ea55d6f0e985.png">

**Comment by matrix-meow** [comment]
Hello @tianyahui-python. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by tianyahui-python** [comment]
@JackTan25 The bvt tag is not removed
