### ISSUE TITLE
[Bug]:  ctrl+c  mo can not success

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7777]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2f1e17764761fc8b0e279837bed65c611f44f9b5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023/02/01 09:54:47.253474 +0800 WARN cn-service.task-runner stopper/stopper.go:209 tasks still running in stopper {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "stopper": "task-runner", "continuous": "1h10m0.615049167s", "tasks": "undefined"}
2023/02/01 09:54:47.258556 +0800 WARN stopper/stopper.go:209 tasks still running in stopper {"stopper": "main", "continuous": "1h10m0.650078667s", "tasks": "cn-service"}
2023/02/01 09:55:00.793080 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302
2023/02/01 09:55:15.804501 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302

**Comment by heni02** [comment]
mo log:
[log.zip](https://github.com/matrixorigin/matrixone/files/10553975/log.zip)

**Comment by daviszhen** [comment]
```
2023/01/31 20:22:43.225848 +0800 INFO frontend/util.go:515 time of Exec.Run : 1.529542ms connectionId 28350
2023/01/31 20:22:43.225902 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 28350, "statement": "show tables", "status": "success", "span": {"trace_id": "f62a26da-a161-11ed-ab0a-96f0c1a980fe", "kind": "statement"}, "session_info": "connectionId 28350"}
2023/01/31 20:22:43.225933 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:484 task done failed, retry later {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "task": "StorageUsage:70/3", "error": "context canceled"}
2023/01/31 20:22:43.961952 +0800 INFO mo-service/main.go:110 Starting shutdown... {"signal": "interrupt"}
2023/01/31 20:22:43.979308 +0800 INFO log-service logservice/service_commands.go:122 heartbeat worker stopped {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:43.979360 +0800 INFO dn-service dnservice/store_heartbeat.go:31 dn heartbeat task stopped {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:43.979526 +0800 INFO cn-service logutil/action.go:35 start to close components {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "action": "close", "components": "cnservice"}
2023/01/31 20:22:43.979706 +0800 INFO cn-service cnservice/server_heartbeat.go:41 cn heartbeat task stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:43.979717 +0800 INFO cn-service logutil/action.go:52 async task exited {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "action": "run-async-task", "async-task": "cnservice/heartbeat-task", "cost": "7h46m47.546479667s"}
2023/01/31 20:22:43.984958 +0800 ERROR hakeeper-client-backend morpc/backend.go:482 read from backend failed {"remote": "127.0.0.1:32001", "backend-id": "82382f7d-6ae2-4e2d-a3f9-69eb8ee5e633", "error": "read tcp4 127.0.0.1:49664->127.0.0.1:32001: use of closed network connection"}
2023/01/31 20:22:43.984958 +0800 ERROR hakeeper-client-backend morpc/backend.go:482 read from backend failed {"remote": "127.0.0.1:32001", "backend-id": "a3279898-b562-477e-bef9-75ff26d4ca53", "error": "read tcp4 127.0.0.1:49660->127.0.0.1:32001: use of closed network connection"}
2023/01/31 20:22:43.997011 +0800 ERROR hakeeper-client-backend morpc/backend.go:487 read loop stopped {"remote": "127.0.0.1:32001", "backend-id": "82382f7d-6ae2-4e2d-a3f9-69eb8ee5e633"}
2023/01/31 20:22:43.997024 +0800 ERROR hakeeper-client-backend morpc/backend.go:487 read loop stopped {"remote": "127.0.0.1:32001", "backend-id": "a3279898-b562-477e-bef9-75ff26d4ca53"}
2023/01/31 20:22:43.986036 +0800 ERROR motrace/buffer_pipe.go:113 [Trace] failed to write. err: context canceled {"MOInternalFiledKeyNoopReport": true}
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.batchCSVHandler.NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/trace/impl/motrace/buffer_pipe.go:113
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.batchCSVHandler.NewItemBatchHandler.func2
	/Users/heni/test-envir/matrixone/pkg/util/trace/impl/motrace/buffer_pipe.go:125
github.com/matrixorigin/matrixone/pkg/util/export.(*bufferExportReq).handle
	/Users/heni/test-envir/matrixone/pkg/util/export/batch_processor.go:126
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Stop.func1
	/Users/heni/test-envir/matrixone/pkg/util/export/batch_processor.go:396
sync.(*Once).doSlow
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/sync/once.go:74
sync.(*Once).Do
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/sync/once.go:65
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Stop
	/Users/heni/test-envir/matrixone/pkg/util/export/batch_processor.go:380
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*batchSpanProcessor).Shutdown.func1.1
	/Users/heni/test-envir/matrixone/pkg/util/trace/impl/motrace/batch_span_processor.go:80
2023/01/31 20:22:44.000935 +0800 INFO cn-service logutil/action.go:35 start to close components {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "action": "close", "components": "cnservice/frontend"}
2023/01/31 20:22:44.000994 +0800 ERROR hakeeper-client-backend v2@v2.0.3-0.20221212132037-abf2d4c05484/session.go:496 close conneciton failed {"remote": "127.0.0.1:32001", "backend-id": "82382f7d-6ae2-4e2d-a3f9-69eb8ee5e633", "session-id": 0, "error": "close tcp4 127.0.0.1:49664->127.0.0.1:32001: use of closed network connection"}
2023/01/31 20:22:44.001094 +0800 INFO cn-service logutil/action.go:38 close components completed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "action": "close", "components": "cnservice/frontend", "cost": "158.584µs"}
2023/01/31 20:22:44.001110 +0800 INFO cn-service logutil/action.go:35 start to close components {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "action": "close", "components": "cnservice/task"}
2023/01/31 20:22:44.001209 +0800 INFO hakeeper-client-backend morpc/backend.go:374 write loop stopped {"remote": "127.0.0.1:32001", "backend-id": "82382f7d-6ae2-4e2d-a3f9-69eb8ee5e633"}
2023/01/31 20:22:44.001211 +0800 INFO v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:371 session read failed {"listen-addresses": "[0.0.0.0:6001]", "session-id": 27349, "addr": "127.0.0.1:50059", "error": "read tcp4 127.0.0.1:6001->127.0.0.1:50059: use of closed network connection"}
2023/01/31 20:22:44.001332 +0800 ERROR v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:345 handle session failed {"listen-addresses": "[0.0.0.0:6001]", "error": "read tcp4 127.0.0.1:6001->127.0.0.1:50059: use of closed network connection"}
2023/01/31 20:22:44.001039 +0800 INFO v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:371 session read failed {"listen-addresses": "[0.0.0.0:6001]", "session-id": 16268, "addr": "127.0.0.1:59894", "error": "read tcp4 127.0.0.1:6001->127.0.0.1:59894: use of closed network connection"}
2023/01/31 20:22:44.001353 +0800 ERROR v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:345 handle session failed {"listen-addresses": "[0.0.0.0:6001]", "error": "read tcp4 127.0.0.1:6001->127.0.0.1:59894: use of closed network connection"}
2023/01/31 20:22:44.000976 +0800 ERROR hakeeper-client-backend v2@v2.0.3-0.20221212132037-abf2d4c05484/session.go:496 close conneciton failed {"remote": "127.0.0.1:32001", "backend-id": "a3279898-b562-477e-bef9-75ff26d4ca53", "session-id": 0, "error": "close tcp4 127.0.0.1:49660->127.0.0.1:32001: use of closed network connection"}
2023/01/31 20:22:44.001365 +0800 INFO hakeeper-client-backend morpc/backend.go:374 write loop stopped {"remote": "127.0.0.1:32001", "backend-id": "a3279898-b562-477e-bef9-75ff26d4ca53"}
2023/01/31 20:22:44.001806 +0800 ERROR motrace/buffer_pipe.go:113 [Trace] failed to write. err: context canceled {"MOInternalFiledKeyNoopReport": true}
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.batchCSVHandler.NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/trace/impl/motrace/buffer_pipe.go:113
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.batchCSVHandler.NewItemBatchHandler.func2
	/Users/heni/test-envir/matrixone/pkg/util/trace/impl/motrace/buffer_pipe.go:125
github.com/matrixorigin/matrixone/pkg/util/export.(*bufferExportReq).handle
	/Users/heni/test-envir/matrixone/pkg/util/export/batch_processor.go:126
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Stop.func1
	/Users/heni/test-envir/matrixone/pkg/util/export/batch_processor.go:396
sync.(*Once).doSlow
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/sync/once.go:74
sync.(*Once).Do
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/sync/once.go:65
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Stop
	/Users/heni/test-envir/matrixone/pkg/util/export/batch_processor.go:380
github.com/matrixorigin/matrixone/pkg/util/trace/impl/motrace.(*batchSpanProcessor).Shutdown.func1.1
	/Users/heni/test-envir/matrixone/pkg/util/trace/impl/motrace/batch_span_processor.go:80
2023/01/31 20:22:44.006409 +0800 INFO cn-service.task-runner taskservice/task_runner.go:500 heartbeat task stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:44.006210 +0800 ERROR rpc-client[hakeeper-client([connectToHAKeeper])] morpc/client.go:349 gc inactive backends task stopped
2023/01/31 20:22:44.006280 +0800 ERROR rpc-client[log-heartbeat] morpc/client.go:349 gc inactive backends task stopped
2023/01/31 20:22:44.006543 +0800 INFO cn-service.task-runner taskservice/task_runner.go:319 dispatch task stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:44.008885 +0800 INFO cn-service.task-runner taskservice/task_runner.go:338 retry task stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:44.009011 +0800 INFO cn-service.task-runner taskservice/task_runner.go:260 fetch task stopped {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"}
2023/01/31 20:22:44.012011 +0800 ERROR dn-service.rpc-client[txn-rpc-sender] morpc/client.go:349 gc inactive backends task stopped {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).gcInactiveTask
	/Users/heni/test-envir/matrixone/pkg/common/morpc/client.go:349
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
	/Users/heni/test-envir/matrixone/pkg/common/stopper/stopper.go:259
2023/01/31 20:22:44.012031 +0800 INFO log-service v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:371 session read failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-rpc", "listen-addresses": "[127.0.0.1:32001]", "session-id": 58, "addr": "127.0.0.1:49729", "error": "read tcp4 127.0.0.1:32001->127.0.0.1:49729: use of closed network connection"}
2023/01/31 20:22:44.012050 +0800 ERROR log-service v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:345 handle session failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "name": "logservice-rpc", "listen-addresses": "[127.0.0.1:32001]", "error": "read tcp4 127.0.0.1:32001->127.0.0.1:49729: use of closed network connection"}

```

**Comment by daviszhen** [comment]
![image](https://user-images.githubusercontent.com/60595215/215978229-80803707-7827-481a-bc23-ef4621c8eb07.png)

**Comment by daviszhen** [comment]
There is a lot of strange error reporting in the log.

```
2023/02/01 07:01:43.202933 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302
2023/02/01 07:01:58.196219 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302
2023/02/01 07:01:59.860041 +0800 WARN stopper/stopper.go:209 tasks still running in stopper {"stopper": "main", "continuous": "55m30.522165959s", "tasks": "cn-service"}
2023/02/01 07:01:59.866131 +0800 WARN cn-service.task-runner stopper/stopper.go:209 tasks still running in stopper {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "stopper": "task-runner", "continuous": "55m30.49842575s", "tasks": "undefined"}
2023/02/01 07:02:13.204151 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302
2023/02/01 07:17:39.790223 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302
2023/02/01 07:17:41.449660 +0800 WARN stopper/stopper.go:209 tasks still running in stopper {"stopper": "main", "continuous": "56m0.529503417s", "tasks": "cn-service"}
2023/02/01 07:17:41.450076 +0800 WARN cn-service.task-runner stopper/stopper.go:209 tasks still running in stopper {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "stopper": "task-runner", "continuous": "56m0.499674292s", "tasks": "undefined"}
2023/02/01 07:17:54.803405 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
```

**Comment by xzxiong** [comment]
> There is a lot of strange error reporting in the log.
> 
> ```
> 2023/02/01 07:01:43.202933 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
> github.com/matrixorigin/matrixone/pkg/util/metric.(*metricFSCollector).NewItemBatchHandler.func1
> 	/Users/heni/test-envir/matrixone/pkg/util/metric/metric_collector.go:290
> github.com/matrixorigin/matrixone/pkg/util/batchpipe.(*BaseBatchPipe[...]).batchWorker
> 	/Users/heni/test-envir/matrixone/pkg/util/batchpipe/batch_pipe.go:302
> 2023/02/01 07:01:58.196219 +0800 ERROR metric/metric_collector.go:290 [Metric] failed to write csv, err: context canceled
> ....
> ```

those error log like `metric/metric_collector.go:290` has been fixed in following commit 8ccf65215 Fix issue 7715 (#7726)

**Comment by zhangxu19830126** [comment]
The logs show that the stopper for taskservice has been running and that the metric-related task has not exited. @xzxiong PTAL

**Comment by xzxiong** [comment]
while cn shutdown, taskservice will cancel task's context. let me check metric's task exit logic first.

**Comment by xzxiong** [comment]
there are two case:
1. in newest version of mo like 8df7021a3, it is context missing-issue. --- fix and wait next pr.
2. in current issue, metric's task exec internal query but wait long time for result ---  still working on.

**Comment by xzxiong** [comment]
after analysis log.
we found out:
1.  2023/01/31 10:55:25, mo-service startup at
2. 2023/01/31 11:44:46, metric's last task run query `show accounts`, but wait a long time and no return.
3. 2023/01/31 20:22:43, mo-service shutdown at 

metric's last task run query `show accounts`. it just exec  `2 / 4` statement with BackgroundSession. @daviszhen PTAL 
1. start transaction -- done.
2. select account_id as account_id ... from mo_catalog.mo_account. -- done 
3. select ... from mo_catalog.mo_tab as mt where .... -- no log info
4. commit; --  no log info

```
-- startup
2023/01/31 10:55:25.983389 +0800 INFO logutil/internal.go:37 MO logger init, level=info, log file=
...
-- in initMOServer
2023/01/31 10:55:28.144594 +0800 INFO cnservice/server.go:217 Shutdown The Server With Ctrl+C | Ctrl+\.
...
exec 'show accounts' meet exec error many times.
...
-- last time exec 'show accounts', and no further MetricStorage log.
2023/01/31 11:44:46.569073 +0800 INFO log-service.MetricStorage metric/cron_task.go:116 start next round {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "span": {"trace_id": "071fc20f-f0ce-1c45-0fb8-cb87940e7ee1", "span_id": "b4a3c368090cf10a"}}
2023/01/31 11:44:46.569388 +0800 INFO frontend/session.go:324 session uuid: 9b096704-a119-11ed-ab08-96f0c1a980fe -> background session uuid: 9b096c7c-a119-11ed-ab08-96f0c1a980fe
2023/01/31 11:44:46.571412 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 4294967295, "statement": "start transaction", "status": "success", "span": {"trace_id": "9b096f38-a119-11ed-ab08-96f0c1a980fe", "kind": "statement"}, "session_info": ""}
2023/01/31 11:44:46.573585 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 4294967295, "statement": "select account_id as account_id, account_name as account_name, created_time as created, status as status, suspended_time as suspended_time, comments as comment from mo_catalog.mo_account", "status": "success", "span": {"trace_id": "9b09c19a-a119-11ed-ab08-96f0c1a980fe", "kind": "statement"}, "session_info": ""}
...
... (no further sql in  connections_id: 4294967295)
...
...
-- receive init task
2023/01/31 20:22:43.961952 +0800 INFO mo-service/main.go:110 Starting shutdown... {"signal": "interrupt"}

```

**Comment by iceTTTT** [comment]
Tried several commits.  In following two commits : 

3ab9e3aa7c3728df7299c6911bd726afea994bb2
6496c3c16b4a602b91e33784ef90ff7fc2affccc

ctrl+c will not succeed without any sql queries,  and the service will stuck in stopper with still running task "trace".
Can not repro "show accounts hang" mentioned above.

**Comment by iceTTTT** [comment]
[log.zip](https://github.com/matrixorigin/matrixone/files/10672323/log.zip)
Here's the log at commit :3ab9e3aa7c3728df7299c6911bd726afea994bb2

**Comment by xzxiong** [comment]
> Tried several commits. In following two commits :
> 
> [3ab9e3a](https://github.com/matrixorigin/matrixone/commit/3ab9e3aa7c3728df7299c6911bd726afea994bb2) [6496c3c](https://github.com/matrixorigin/matrixone/commit/6496c3c16b4a602b91e33784ef90ff7fc2affccc)
> 
> ctrl+c will not succeed without any sql queries, and the service will stuck in stopper with still running task "trace". Can not repro "show accounts hang" mentioned above.

3ab9e3a and 6496c3c is between 8ccf65215 and  8f2993147, so it will have the 'tasks still running in stopper' issue.
 -  but all these 4 commit is after 2f1e17764, not cause this issue itself.

```
...
* 8f2993147 fix ctrl+c mo not shutdown with tasks running in stopper (#7812).  --- case 1 fixed here
...
* 3ab9e3aa7 cn-write-s3 insert, (#7498)
...
* 6496c3c16 revert udf execution pr (#7745)
...
* 8ccf65215 Fix issue 7715 (#7726).                      ---------   this version cause case 1 - 'tasks still running in stopper' issue
* faa7ed227 Support auto_incr per CN cache. (#7659)
* 24aeba4d2 Fix truncate (#7731)
* 5ec65ab10 make composite priamry key parts not null true (#7701)
* 405a91bc0 [Test]: add cluster table bvt case (#7734)
* 500e5959b disttae: remove index_Time (#7733)
* 2f1e17764 support delete cn info in hakeeper (#7699).   ----- current issue's mo version.
...
```

**Comment by iceTTTT** [comment]
> > Tried several commits. In following two commits :
> > [3ab9e3a](https://github.com/matrixorigin/matrixone/commit/3ab9e3aa7c3728df7299c6911bd726afea994bb2) [6496c3c](https://github.com/matrixorigin/matrixone/commit/6496c3c16b4a602b91e33784ef90ff7fc2affccc)
> > ctrl+c will not succeed without any sql queries, and the service will stuck in stopper with still running task "trace". Can not repro "show accounts hang" mentioned above.
> 
> [3ab9e3a](https://github.com/matrixorigin/matrixone/commit/3ab9e3aa7c3728df7299c6911bd726afea994bb2) and [6496c3c](https://github.com/matrixorigin/matrixone/commit/6496c3c16b4a602b91e33784ef90ff7fc2affccc) is between [8ccf652](https://github.com/matrixorigin/matrixone/commit/8ccf65215024c8d249e04c70c9a761f7680c8629) and [8f29931](https://github.com/matrixorigin/matrixone/commit/8f299314732f27c7c253b1294bdefdf118476f9c), so it will have the 'tasks still running in stopper' issue.
> 
> * but all these 4 commit is after [2f1e177](https://github.com/matrixorigin/matrixone/commit/2f1e17764761fc8b0e279837bed65c611f44f9b5), not cause this issue itself.
> 
> ```
> ...
> * 8f2993147 fix ctrl+c mo not shutdown with tasks running in stopper (#7812).  --- case 1 fixed here
> ...
> * 3ab9e3aa7 cn-write-s3 insert, (#7498)
> ...
> * 6496c3c16 revert udf execution pr (#7745)
> ...
> * 8ccf65215 Fix issue 7715 (#7726).                      ---------   this version cause case 1 - 'tasks still running in stopper' issue
> * faa7ed227 Support auto_incr per CN cache. (#7659)
> * 24aeba4d2 Fix truncate (#7731)
> * 5ec65ab10 make composite priamry key parts not null true (#7701)
> * 405a91bc0 [Test]: add cluster table bvt case (#7734)
> * 500e5959b disttae: remove index_Time (#7733)
> * 2f1e17764 support delete cn info in hakeeper (#7699).   ----- current issue's mo version.
> ...
> ```

Got.

**Comment by iceTTTT** [comment]
At commit of this issue:
2f1e17764761fc8b0e279837bed65c611f44f9b5

I can ctrl + c my mo, after i tried several random bvt cases:

![image](https://user-images.githubusercontent.com/74845916/218008394-43843367-3b80-4027-bd97-f171900cb230.png)

After Just after the execution of bvt case:      **create_table.sql**

It will report ERROR  and I can't not ctrl + c anymore:

This is the ERROR showed in terminal
**2023/02/10 13:28:52 worker exits from panic: goroutine 6171 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /home/wjc/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:58 +0x10c
panic({0x24b6520, 0xc00e146f60})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort/varchar.Sort({0x2c9f138, 0xc00e1624e0}, {0xc0111b0820, 0x8, 0xc0054d36e8?})
        /home/wjc/matrixone/pkg/vm/engine/tae/mergesort/varchar/func.go:26 +0x54e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/mergesort.SortBlockColumns({0xc00ee7a540, 0x4, 0x17?}, 0x3)
        /home/wjc/matrixone/pkg/vm/engine/tae/mergesort/mergesort.go:78 +0x5e5
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).PrepareData(0xc00ffb47e0)
        /home/wjc/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:118 +0x35f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute(0xc00ffb47e0)
        /home/wjc/matrixone/pkg/vm/engine/tae/tables/jobs/compactblk.go:138 +0x391
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc00fd1e8c0)
        /home/wjc/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute(0xc00e146a80)
        /home/wjc/matrixone/pkg/vm/engine/tae/db/task.go:62 +0xfb
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec(0xc00fd1e540)
        /home/wjc/matrixone/pkg/vm/engine/tae/tasks/ops/ops.go:90 +0x79
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp(0xc00311ca80, {0x7f56d05771c0, 0xc00e146a80})
        /home/wjc/matrixone/pkg/vm/engine/tae/tasks/worker/worker.go:207 +0x30
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1()
        /home/wjc/matrixone/pkg/vm/engine/tae/tasks/poolhandler.go:59 +0x32
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /home/wjc/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        /home/wjc/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65**

And then ctrl+c doesn't work:
![image](https://user-images.githubusercontent.com/74845916/218008946-66088bbc-70f5-4806-994f-be9ca6b8a847.png)

**Comment by iceTTTT** [comment]
This issue can be repro steadily after executing steps below:

step1: 
checkout to commit:  
  2f1e17764761fc8b0e279837bed65c611f44f9b5
step2: 
    run mo:    ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml > log.txt
step3: 
   run test:   ./run.sh -n -g -i create_table

**Comment by iceTTTT** [comment]
At commit of this issue, found that this error can be repro by following sql queries:

![4815daca7adaa9f7909a3b20434ed8f](https://user-images.githubusercontent.com/74845916/218043658-55e62d00-99ba-4cf4-afc4-26cd1513b766.png)

At current commit:

![image](https://user-images.githubusercontent.com/74845916/218043957-ce8d148f-763e-458c-b7e8-2a2bd2293af3.png)

**null value is not supported in cluster by columns now**.

**Comment by iceTTTT** [comment]
This bug is a dup of #7565

**Comment by iceTTTT** [comment]
The dup bug is fixed.

**Comment by heni02** [comment]
regression tomorrow

**Comment by heni02** [comment]
commit id:1524f46af44a1e5718b23f4d5aed6e895b61808e
There is no problem of modification at present
![image](https://user-images.githubusercontent.com/113406637/224218116-beb19e17-f09d-49bd-aa92-8bb55d1e17e8.png)
