### ISSUE TITLE
[Bug]: Can't use delete from t in begin transaction.

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#7779]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
create table t(a int);
begin;
insert into t values(1),(2),(3);
delete from t; 
select * from t;
a
1
2
3

### Expected Behavior
create table t(a int);
begin;
insert into t values(1),(2),(3);
delete from t; 
select * from t;
empty set
_No response_

**Comment by daviszhen** [comment]
I have reproduced the unbelievable behavior at 5706855a27c2da45242fc0d52ef4efe8de267df1:

```

mysql> create database db;
Query OK, 1 row affected (0.18 sec)

mysql> use db
Database changed
mysql> create table t(a int);
Query OK, 0 rows affected (0.03 sec)

mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values(1),(2),(3);
Query OK, 3 rows affected (0.01 sec)

mysql> select * from t;
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.04 sec)

mysql> delete from t;
Query OK, 3 rows affected (0.02 sec)

mysql> select * from t;
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.11 sec)

mysql> 

```

**Comment by JackTan25** [comment]
fixed
