### ISSUE TITLE
[Bug]: load s3 role_arn reported s3 https response error 400

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7783]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Configure role ID load s3 under the original account，reported error 

mysql> load data url s3option {'bucket'='mo-load-data', 'filepath'='load_data/20_columns/100000_20_columns_load_data.csv', 'role_arn'='arn:aws:iam::468413122983:role/cross-account-s3', 'external_id'=''} into table test.table_20_columns_10w;
ERROR 20101 (HY000): internal error: bad s3 config: operation error S3: HeadBucket, https response error StatusCode: 400, RequestID: FSZRQGBJEM7K8D3Z, HostID: fRGleoP9sKmi9MVHqNCQ4neLyKuXzr8kPt1UncLGtQRxKRVJQBumtHAsrAME8RTZSRiIiTHKCGAD+Y0ekIZBAA==, api error BadRequest: Bad Request
mysql> load data url s3option {'bucket'='mo-load-data', 'filepath'='load_data/20_columns/100000_20_columns_load_data.csv', 'role_arn'='arn:aws:iam::468413122983:role/cross-account-s3'} into table test.table_20_columns_10w;
ERROR 20101 (HY000): internal error: bad s3 config: operation error S3: HeadBucket, https response error StatusCode: 400, RequestID: 406GHAMNJ3RQ3JKS, HostID: wp33U1TAU+nTaQCLbg426ot8WQXVjOFUb1GtcVIYTOagR90Dl0Q8wl6Ll+3e3CAoYXfNYVUkzpw=, api error BadRequest: Bad Request

### Steps to Reproduce

```Markdown
create table table_20_columns_10w(
clo1 tinyint,
clo2 smallint,
clo3 int,
clo4 bigint,
clo5 tinyint unsigned,
clo6 smallint unsigned,
clo7 int unsigned,
clo8 bigint unsigned,
col9 float,
col10 double,
col11 varchar(255),
col12 Date,
col13 DateTime,
col14 timestamp,
col15 bool,
col16 decimal(5,2),
col17 text,
col18 varchar(255),
col19 varchar(255),
col20 varchar(255)
)
 load data url s3option {'bucket'='mo-load-data', 'filepath'='load_data/20_columns/100000_20_columns_load_data.csv', 'role_arn'='arn:aws:iam::468413122983:role/cross-account-s3'} into table test.table_20_columns_10w;
```

**Comment by heni02** [comment]
mo log:
[log2.txt](https://github.com/matrixorigin/matrixone/files/10555304/log2.txt)

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/5490d46b101048912732ca5059bb904f0f2b4ab0

**Comment by reusee** [comment]
re-assign to @heni02

**Comment by heni02** [comment]
commit id:6c16f387093d20da2498c5128416c977812d4151
ERROR 1105 (HY000): operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: 747bf04e-8204-4b0d-9d50-469d3ade3c7e, api error InvalidClientTokenId: The security token included in the request is invalid.
![image](https://user-images.githubusercontent.com/113406637/217528335-77197f88-622d-42a4-925a-9492615968fd.png)

**Comment by reusee** [comment]
I can't reproduce the above situation. I'll check the AWS docs to see if I can understand what's happening.

**Comment by reusee** [comment]
"The security token included in the request is invalid" means the Access Key ID is invalid.
This is a configuration issue on the user's machine, not in our codebase.

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/9fdc1d7c2ad7f76b4a2851ca430c37c42fcf30a7
re-assign to @heni02

**Comment by heni02** [comment]
confirm, closed
commit id:9fdc1d7c2ad7f76b4a2851ca430c37c42fcf30a7
![image](https://user-images.githubusercontent.com/113406637/218634661-c10a7e89-74ae-4caf-a0a8-8a68917a31ac.png)
![image](https://user-images.githubusercontent.com/113406637/218634676-9f45ea6f-7d5b-4a0d-a832-93dfd8e80655.png)
