### ISSUE TITLE
[Bug]: statement info table does not collect "desc table;" sql.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7785]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84db18673d85dc44eca69bba097c5c9fb25f6298
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

desc table;

select statement,query_type,sql_source_type from  statement_info where user="dump" and sql_source_type="external_sql" order by request_at desc limit 10;

return result no exists "desc table;" statement.

**Comment by xzxiong** [comment]
that was rewrite as `show columns from table`

- example
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/3927687/216045418-2284b386-7c8d-4365-8ca7-da18bd4a06c5.png">

**Comment by xzxiong** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/3927687/216047265-760cef95-a3d6-4bb9-ae79-6fa7f542e900.png">

**Comment by tianyahui-python** [comment]
Connect via jdbc.Unable to collect "desc table" data.

**Comment by xzxiong** [comment]
found out `sql_source_type` issue. `desc table` is ok. PTAL
