### ISSUE TITLE
[Bug]: Failed to execute the show statement in the transaction.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7789]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84db18673d85dc44eca69bba097c5c9fb25f6298
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> show create view test_view;
ERROR 20101 (HY000): internal error: unclassified statement appears in uncommitted transaction
mysql> show collation; 
ERROR 20101 (HY000): internal error: unclassified statement appears in uncommitted transaction
mysql> show collation like '%';  
ERROR 20101 (HY000): internal error: unclassified statement appears in uncommitted transaction

<img width="1248" alt="截屏2023-02-01 22 58 32" src="https://user-images.githubusercontent.com/39303074/216078353-5307e135-7539-4a64-9b45-8415ef36b50c.png">

**Comment by daviszhen** [comment]
it was fixed i think
