### ISSUE TITLE
[Bug]: insert performance is lower than without limit n

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7794]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> insert into lineitem select * from tpch.lineitem limit 10000000;
Query OK, 10000000 rows affected (54.29 sec)

mysql> insert into lineitem select * from tpch.lineitem;
Query OK, 59986052 rows affected (18.72 sec)

performance of 10M lines with limit is lower than 60M lines without limit

**Comment by m-schen** [comment]
I will check and fix it.

**Comment by m-schen** [comment]
pipeline构建导致的问题，insert limit会导致只有一个insert在工作，insert select会有多个insert算子在工作。

**Comment by m-schen** [comment]
<img width="854" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/1e800d29-2124-4164-badc-e90bf4c24880">
图为最新的main的测试结果，其中lintitem2 与 lineitem3的结构均与lineitem相同（包括主键约束）。

insert全表耗时 2min 25s
insert limit 1000w耗时 26 s，约为全表耗时的17%，与数据量成正比，已没有该问题。

**Comment by aressu1985** [comment]
fixed
