### ISSUE TITLE
[Bug]: mo load local big data  after more than 5hours ,can not connect mo

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7814]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):62d0edc085b2f775de5ae267fd4f73a381440432
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1280" alt="企业微信截图_2bc0d277-19a6-41a0-b5da-9c5cb1cc48bf" src="https://user-images.githubusercontent.com/113406637/216324561-803e90ea-0dc8-4cb2-8036-7e63513a4514.png">

log is too large,plz connect to me
2023/02/02 20:26:44.607858 +0800 ERROR log-service taskservice/task_service_cron.go:294 trigger cron task failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "cron-task": "StorageUsage", "error": "invalid connection"}
github.com/matrixorigin/matrixone/pkg/taskservice.(*cronJob).doRun
	/data1/heni/matrixone/pkg/taskservice/task_service_cron.go:294
github.com/matrixorigin/matrixone/pkg/taskservice.(*cronJob).retryRun
	/data1/heni/matrixone/pkg/taskservice/task_service_cron.go:260
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskService).retryScheduleCronTask.func1
	/data1/heni/matrixone/pkg/taskservice/task_service_cron.go:192
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
	/data1/heni/matrixone/pkg/common/stopper/stopper.go:259
2023/02/02 20:26:44.608866 +0800 INFO frontend/util.go:515 check password succeeded connectionId 5925
2023/02/02 20:26:44.609002 +0800 INFO frontend/util.go:500 query trace {"connection_id": 5925, "query": "use mo_task", "session_info": "connectionId 5925"}
[mysql] 2023/02/02 20:26:45 packets.go:37: read tcp 127.0.0.1:39194->127.0.0.1:6001: i/o timeout
2023/02/02 20:26:45.697690 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:525 task heartbeat failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "invalid connection"}
2023/02/02 20:26:45.698753 +0800 INFO frontend/util.go:515 check password succeeded connectionId 5926
2023/02/02 20:26:45.698867 +0800 INFO frontend/util.go:500 query trace {"connection_id": 5926, "query": "use mo_task", "session_info": "connectionId 5926"}
[mysql] 2023/02/02 20:26:49 packets.go:37: read tcp 127.0.0.1:39206->127.0.0.1:6001: i/o timeout
2023/02/02 20:26:49.611101 +0800 INFO frontend/util.go:515 check password succeeded connectionId 5927
2023/02/02 20:26:49.611262 +0800 INFO frontend/util.go:500 query trace {"connection_id": 5927, "query": "use mo_task", "session_info": "connectionId 5927"}

**Comment by mooleetzi** [comment]
in progress

**Comment by daviszhen** [comment]
Two things thould be done:
1, the routine of reading data from the client need to be released after the load statement is accomplished normally or abnormally.
2, reproduce the 100G locally.

**Comment by mooleetzi** [comment]
from Initial log log, `load local` is successful, but strange why no return and cannot connect, need repro.

**Comment by mooleetzi** [comment]
<img width="955" alt="Screen Shot 2023-02-09 at 15 53 56" src="https://user-images.githubusercontent.com/42628885/217750736-0249bb6e-82b4-4c96-a5c9-6f2ff1232af8.png">

load local done, it's ok in case `100_columns_1y`


and reconnect is fine.
```
mysql> load data local infile '/data1/heni/mo-load-data-main/data/100_columns/100000000_100_columns_load_data.csv' into table test.table_100_columns_1y fields terminated by "," lines terminated by "\n";
Query OK, 100000000 rows affected (3 hours 12 min 5.33 sec)

mysql> select count(1) from table_100_columns_1y;
+-----------+
| count(1)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (4.69 sec)

mysql> exit
Bye
[root@mo-srv-128]~# mysql -h 10.222.1.130 -u dump -P6001 -p111 --local-infile
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1127
Server version: 8.0.30-MatrixOne-v0.6.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use tes;
ERROR 1049 (HY000): invalid database tes
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select count(1) from table_100_columns_1y;
+-----------+
| count(1)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (2.96 sec)

mysql> exit
Bye
[root@mo-srv-128]~# mysql -h 10.222.1.130 -u dump -P6001 -p111 --local-infile
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1128
Server version: 8.0.30-MatrixOne-v0.6.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select count(1) from test.table_100_columns_1y;
+-----------+
| count(1)  |
+-----------+
| 100000000 |
+-----------+
1 row in set (2.78 sec)

mysql>

```

**Comment by mooleetzi** [comment]
wait #7922

**Comment by heni02** [comment]
regression is running ,later confirm

**Comment by heni02** [comment]
confirm, closed
commit id: 346277e3cb8e7aec9d68c043a3e9249e2c3cb842
<img width="888" alt="企业微信截图_64a1e437-53c5-440e-98b5-f5fd1fc812fc" src="https://user-images.githubusercontent.com/113406637/218353559-49a8836a-7b01-4b53-9d12-620219f9578e.png">
