### ISSUE TITLE
HAVING clause doesn't work

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#783]
#### Can be reproduced ?
Yes

#### Steps:
CREATE TABLE t2(
product VARCHAR(32),
country_id float,
year INTEGER,
profit double);

INSERT INTO t2  VALUES ( 'Computer', 2,2000, 1200),
( 'TV', 1, 1999, 150),
( 'Calculator', 1, 1999,50),
( 'Computer', 1, 1999,1500),
( 'Computer', 1, 2000,1500),
( 'TV', 1, 2000, 150),
( 'TV', 2, 2000, 100),
( 'TV', 2, 2000, 100),
( 'Calculator', 1, 2000,75),
( 'Calculator', 2, 2000,75),
( 'TV', 1, 1999, 100),
( 'Computer', 1, 1999,1200),
( 'Computer', 2, 2000,1500),
( 'Calculator', 2, 2000,75),
( 'Phone', 3, 2003,10)
;

SELECT product, country_id , year, SUM(profit) FROM t2
GROUP BY product, country_id, year HAVING country_id = 1;
![1631937352(1)](https://user-images.githubusercontent.com/88298673/133871742-1e9ac2c0-be59-46ac-866c-032ab2bb58ba.png)

SELECT product, country_id , year, SUM(profit) FROM t2
GROUP BY product, country_id, year HAVING SUM(profit) > 200;
![1631937392(1)](https://user-images.githubusercontent.com/88298673/133871758-680cca40-6586-4df9-8430-fbc9bf0f2612.png)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d88680afbb11720f57d88125888f432e89b04c24
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by nnsgmsone** [comment]
Solved

**Comment by daviszhen** [comment]
It was supported already.
