### ISSUE TITLE
[Bug]: Failed to create account

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#7831]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0.6.0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/31049447/216546405-326074db-b456-4fd7-b4ba-e5ee940ea298.png)

**Comment by daviszhen** [comment]
log was not saved.

**Comment by LeftHandCold** [comment]
0.6 version code is too old, please test with 0.7 code. @LiSong0214
