### ISSUE TITLE
[Bug]: update cluster by key reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a19a7efb38c1c874018c978534fda07a7aa041b9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/216571608-21550f72-5ee0-4306-84c1-3a13fe843e30.png)

### Steps to Reproduce

```Markdown
create table sort_key_15(col1 tinyint,col2 float)cluster by col2;
insert into sort_key_15 values(122,0.99);
insert into sort_key_15 values(NULL,4.99);
update sort_key_15 set col2=9.01 where col1 is null;
```

**Comment by badboynt1** [comment]
caused by https://github.com/matrixorigin/matrixone/pull/7720

**Comment by heni02** [comment]
confirm,closed
commit id:0ea4925d5cfc6922c8c602c61aa28a83632ca0a7
![image](https://user-images.githubusercontent.com/113406637/217139227-30e27572-28fd-47b4-926a-9e99f40c4e19.png)
