### ISSUE TITLE
[Bug]: “saveQueryResult” The global configuration does not take effect.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7841]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5c7ea0b214d824bad7bbf030a8403dd5a3b9e748
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

set  Global Configuration:
[cn.frontend]
saveQueryResult = "on" 

restart mo-server.

session1: set set global save_query_result = off;
session2: default global configuration lose efficacy.

sesson1:
<img width="589" alt="截屏2023-02-05 02 59 54" src="https://user-images.githubusercontent.com/39303074/216784850-e8703f6a-a2bb-4e17-a823-f96fda936958.png">

session2:
<img width="885" alt="截屏2023-02-05 03 00 40" src="https://user-images.githubusercontent.com/39303074/216784868-635412bc-d9a0-4f8b-8126-7e2e2831d0a7.png">

**Comment by iamlinjunhong** [comment]
save_query_result variable is config of cn level.
