### ISSUE TITLE
[Bug]: mo cn pod killed by sys oom when run tpch 10g query 21 on eks with m6a.4xl node

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7845]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5c7ea0b2
- Hardware parameters: aws m6a.4xl (16C 64G)
- OS type:
- Others:
```

### Actual Behavior

tools log:
2023-02-05 12:03:17 Now start to execute the query queries/q21.sql,please wait.....
2023-02-05 12:03:37 The query q21  has failed to  be executed.

ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query

dmesg :

[Sun Feb  5 12:03:33 2023] Tasks state (memory values in pages):
[Sun Feb  5 12:03:33 2023] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[Sun Feb  5 12:03:33 2023] [   5431] 65535  5431      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [   6366]     0  6366     2889      670    73728        0          -997 bash
[Sun Feb  5 12:03:33 2023] [   6411]     0  6411   191482    16179   253952        0          -997 aws-k8s-agent
[Sun Feb  5 12:03:33 2023] [   6412]     0  6412     1059      192    57344        0          -997 tee
[Sun Feb  5 12:03:33 2023] [   5430] 65535  5430      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [   5962]     0  5962   187887    12103   221184        0          -998 kube-proxy
[Sun Feb  5 12:03:33 2023] [   5571] 65535  5571      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [   6663]     0  6663   189153    12770   229376        0           999 kruise-daemon
[Sun Feb  5 12:03:33 2023] [   6847]     0  6847      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [   7094]     0  7094   190919     9498   208896        0          -997 aws-ebs-csi-dri
[Sun Feb  5 12:03:33 2023] [   7245]     0  7245   181409     3624   126976        0          -997 csi-node-driver
[Sun Feb  5 12:03:33 2023] [   7392]     0  7392   178889     4278   122880        0          -997 livenessprobe
[Sun Feb  5 12:03:33 2023] [  31543] 65535 31543      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [  14295]     0 14295 17738439 15323661 131747840        0           187 mo-service
[Sun Feb  5 12:03:33 2023] [   5434] 65534  5434      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [   5908] 65534  5908   180176     5501   163840        0          1000 node_exporter
[Sun Feb  5 12:03:33 2023] [  11510] 65535 11510      242        1    28672        0          -998 pause
[Sun Feb  5 12:03:33 2023] [  11823]     0 11823    92025     8250   204800        0          1000 fluent-bit
[Sun Feb  5 12:03:33 2023] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=49081264d79b989cefb78ec9c1650d8e3df871391c2bc08111ebf1a62b1b9856,mems_allowed=0,oom_memcg=/kubepods,task_memcg=/kubepods/burstable/pod6a19bc45-bfe7-408a-97b1-a41deedfa2d3/49081264d79b989cefb78ec9c1650d8e3df871391c2bc08111ebf1a62b1b9856,task=mo-service,pid=14295,uid=0
[Sun Feb  5 12:03:33 2023] Memory cgroup out of memory: Killed process 14295 (mo-service) total-vm:70953756kB, anon-rss:61245368kB, file-rss:49276kB, shmem-rss:0kB, UID:0 pgtables:128660kB oom_score_adj:187

### Steps to Reproduce

```Markdown
1.run a mo cluster on eks
2.run a tester pod in the same namespace
3.kubectl -n xxx exec -it <tester pod name> bash
  apt-get update
  apt-get install git vim net-tools mysql-client openjdk-8-jdk sysbench bc -y
  ln /usr/bin/python3 /usr/bin/python
4.git clone https://github.com/matrixorigin/mo-load-data.git
5.cd mo-load-data
6. ./load.sh -h <cn-svc.namespace> -c cases/00_from_s3/tpch_1 -m -r
7. ./run.sh -h nightly-regression-dis-tp-cn.mo-nightly-regression -q all -s 10
```

**Comment by m-schen** [comment]
[Sun Feb 5 12:03:33 2023] Memory cgroup out of memory: Killed process 14295 (mo-service) total-vm:70953756kB

7 gb oom.

**Comment by m-schen** [comment]
git clone git@github.com:matrixorigin/mo-load-data.git

**Comment by m-schen** [comment]
该问题还在排查，10g数据占用70g虚拟内存的现象是比本地严重的，本地单cn执行q21时虚拟内存峰值约为42g。明天会用今天的最新镜像在eks上进行定位。

**Comment by m-schen** [comment]
I have verify the new main branch on eks.
the query 21 will cost about 39g memory . it will not cause oom now.

and I will keep watching the q21 at local, to check which process cost the memory.

**Comment by m-schen** [comment]
[pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.031.pb.gz](https://github.com/matrixorigin/matrixone/files/10694709/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.031.pb.gz)

all memory cost in hash build. memory is normal now.

**Comment by m-schen** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/59043531/217752530-607c0f73-5e49-4545-b257-875e04fde878.png">

**Comment by aressu1985** [comment]
It is not reproduced in commit 4edde23d
