### ISSUE TITLE
Unable to retrieve rows when SELECT statement without reference to any table

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#785]
#### Can be reproduced ?
Yes

#### Steps:
Run SQL below:

select 1;
select 1 from dual;

#### Expected behavior:
Expect to retrieve row when SELECT statement without reference to any table or reference to a dummy table.

#### Actual behavior:

mysql> select 1;
ERROR 1105 (HY000): unknown error:[42000]invalid projection '{1 }'
mysql> select 1 from dual;
ERROR 1105 (HY000): unknown error:[42000]invalid projection '{1 }'
#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by dengn** [comment]
In the current 0.4.0 version, the function with no argument or with constant argument will both prompt this error. 
```sql
(dump@127.0.0.1) [abc]>select utc_timestamp() from test1;
ERROR 1105 (HY000): unknown error:[0A000]projection attributes is empty
(dump@127.0.0.1) [abc]>select log(10) from test1;
ERROR 1105 (HY000): unknown error:[0A000]projection attributes is empty
```

**Comment by fengttt** [comment]
Fixed.
