### ISSUE TITLE
[Bug]: the performance of load data in version 0.7 is degraded

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#7870]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TPCH -s10
In v0.7, the optimization of CN writing directly to S3 was done, but the performance improvement of load data is not consistent, some even declines
<img width="534" alt="image" src="https://user-images.githubusercontent.com/31049447/218041844-413a06cb-93a0-444b-97e6-603b9f672813.png">

**Comment by LiSong0214** [comment]
这个问题是我在 mac 上部署 mo 导入本地文件测的，跟 S3 没关系。

**Comment by JackTan25** [comment]
![3432fa56dee3c15911c7cbf54febad7](https://user-images.githubusercontent.com/60096118/218395426-5c1feec3-0a5b-437b-bbe6-ed488f4bd104.png)
![527701194474c0eb3f7c58acde22ae7](https://user-images.githubusercontent.com/60096118/218395446-709117c1-1dfc-4839-a8ab-5d40868d8133.png)
![b0984e8e7d55962a7e2d71437662e4a](https://user-images.githubusercontent.com/60096118/218395456-43dc97a9-2a9e-4751-8516-2a7282dc979a.png)

**Comment by JackTan25** [comment]
We have found out why the partsupp table's load is slower than 0.6. It has a very large string col, and see above, these funcs will result in the slow performance. So We need to use batch's reuse in 0.8, should not do this in 0.7

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by JackTan25** [comment]
batch reuse

**Comment by aressu1985** [comment]
fixed
