### ISSUE TITLE
[Bug]: kill connection connection_id mo service be stoped

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7876]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0ea4925d5cfc6922c8c602c61aa28a83632ca0a7
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/217141706-c6748424-da07-469f-9b91-32f3bd69e6a1.png)
![image](https://user-images.githubusercontent.com/113406637/217141501-2d8c259f-5aae-4970-85c9-c17f9cf5e476.png)
![image](https://user-images.githubusercontent.com/113406637/217141644-99fb67be-54bf-4303-b20d-e3a71d796675.png)

panic: internal error: mpool freemany freed more bytes than alloc

goroutine 15231 [running]:
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPoolStats).RecordManyFrees(0x10107213db6?, {0x1400d9cc3f0, 0x2d}, 0x107e48be8?, 0x14000777b88?)
	/Users/heni/test-envir/main/matrixone/pkg/common/mpool/mpool.go:108 +0x164
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).destroy(0x107e48be0?)
	/Users/heni/test-envir/main/matrixone/pkg/common/mpool/mpool.go:346 +0xc0
github.com/matrixorigin/matrixone/pkg/common/mpool.DeleteMPool(0x1400e31ae00)
	/Users/heni/test-envir/main/matrixone/pkg/common/mpool/mpool.go:442 +0x48
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).Dispose(0x14008eebb80)
	/Users/heni/test-envir/main/matrixone/pkg/frontend/session.go:306 +0x30
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).cleanup.func1()
	/Users/heni/test-envir/main/matrixone/pkg/frontend/routine.go:270 +0x2c
sync.(*Once).doSlow(0x1061b573f?, 0x140006508a0?)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/sync/once.go:65
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).cleanup(0x14000777d38?)
	/Users/heni/test-envir/main/matrixone/pkg/frontend/routine.go:266 +0x48
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Closed(0x14008f50980, {0x106bcb040, 0x1400e286300})
	/Users/heni/test-envir/main/matrixone/pkg/frontend/routine_manager.go:159 +0x228
github.com/fagongzi/goetty/v2.(*baseIO).Close(0x1400e286300)
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/session.go:383 +0x234
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1.1()
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:339 +0x4c
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:347 +0x164
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x3c4

### Steps to Reproduce

```Markdown
create table table_5000w_b(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255));
 load data infile {"filepath"='/Users/heni/test_data/50000000_20_columns_load_data.csv'} into table table_5000w_b;
kill connection conectionid;
```

**Comment by heni02** [comment]
mo log:
[log.txt](https://github.com/matrixorigin/matrixone/files/10671342/log.txt)

**Comment by daviszhen** [comment]
I have reproduced it. But i do not get the point about memory managemant of the pipeline.

**Comment by nnsgmsone** [comment]
It can't end because of the extern scan, but the implementation of the kill command should have some problems, it kills something wrong and doesn't kill the pipeline. You can try ctrl+c to see if this kills the pipeline correctly.  The kill command does not send the cancel message to the pipeline

**Comment by heni02** [comment]
confirm,closed
commit id :346277e3cb8e7aec9d68c043a3e9249e2c3cb842
![image](https://user-images.githubusercontent.com/113406637/218291102-761b9192-4447-4809-b7d7-a01a43166544.png)
