### ISSUE TITLE
[Feature Request]: Support more meta data tables in mo_catalog

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7884]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Support more meta data tables as following:
mo_indexes
mo_user_defined_function

Add columns of partition related in mo_tables

**Comment by fengttt** [comment]
Unless we have a customer/usecase that need such tables, let put them p1 now.

**Comment by domingozhang** [comment]
mo_triggers will be implemented in future release.
mo_functions  ->   mo_user_defined_function

**Comment by qingxinhome** [comment]
The `mo_indexes` metadata table has been implemented @daviszhen @domingozhang

**Comment by qingxinhome** [comment]
This feature has been implemented, please test it. @daviszhen @heni02 @aressu1985 @domingozhang

**Comment by Ariznawlll** [comment]
test done!

**Comment by qingxinhome** [comment]
The requirement has been implemented and tested @domingozhang
