### ISSUE TITLE
[Feature Request]: Support more data in the view of information_schema

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7885]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Adjust information of these views:

tables: table types, update time
processlist: existing session
triggers/views: created time

**Comment by fengttt** [comment]
p1 unless we have a customer/usecase.

**Comment by DanielZhangQD** [comment]
Please also cover the case in https://github.com/matrixorigin/matrixone/issues/7214.
