### ISSUE TITLE
[Feature Request]: SHOW statement enhancement

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7888]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Add these show statement:

show roles [LIKE pattern], show roles list [with filter]
show functions [LIKE pattern], show udf list  [with filter]
show triggers  [LIKE pattern], show udf  list [with filter]

**Comment by LiSong0214** [comment]
moc needs ‘show grants to user u1’
<img width="613" alt="image" src="https://user-images.githubusercontent.com/31049447/217193219-54784f0d-0e78-4c97-8362-5315d84be73c.png">

**Comment by domingozhang** [comment]
like and where filters need both support

**Comment by domingozhang** [comment]
show roles
show function status
show procedure status

**Comment by Ariznawlll** [comment]
show roles，show function status，show procedure status  test done！

**Comment by Ariznawlll** [comment]
show roles，show function status，show procedure status（only grammer）test done!
