### ISSUE TITLE
[Bug]: truncate table with foreign key error in no-sys account

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7896]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):d6e9798b8068f5b6358e7a26af1ef6d3b2e32f1a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table f1(b int, a int primary key);
Query OK, 0 rows affected (0.02 sec)

mysql> create table f2(b int, aa varchar primary key);
Query OK, 0 rows affected (0.03 sec)

mysql> create table c1 (a int, b int, foreign key f_a(a) references f1(c));
ERROR 20101 (HY000): internal error: column 'c' no exists in table 'f1'
mysql> create table c1 (a int, b int, foreign key f_a(a) references f1(b));
ERROR 20101 (HY000): internal error: reference column 'b' is not unique constraint(Unique index or Primary Key)
mysql> create table c1 (a int, b int, foreign key f_a(a) references f2(aa));
ERROR 20101 (HY000): internal error: type of reference column 'aa' is not match for column 'a'
mysql> create table c1 (a int, b int, foreign key f_a(a) references f1(a));
Query OK, 0 rows affected (0.01 sec)

mysql> select * from f1;
Empty set (0.02 sec)

mysql> select * from c1;
Empty set (0.00 sec)

mysql> drop table f1;
ERROR 20101 (HY000): internal error: can not drop table 'f1' referenced by some foreign key constraint
mysql> truncate f1;
ERROR 20101 (HY000): internal error: can not truncate table 'f1' referenced by some foreign key constraint
mysql> truncate c1;
**ERROR 20101 (HY000): internal error: can not find table by id 316764**

### Steps to Reproduce

```Markdown
create table f1(b int, a int primary key);
create table f2(b int, aa varchar primary key);
create table c1 (a int, b int, foreign key f_a(a) references f1(c));
create table c1 (a int, b int, foreign key f_a(a) references f1(b));
create table c1 (a int, b int, foreign key f_a(a) references f2(aa));
create table c1 (a int, b int, foreign key f_a(a) references f1(a));
select * from f1;
select * from c1;
drop table f1;
truncate f1;
truncate c1;
```

**Comment by ouyuanning** [comment]
PR is reviewing

**Comment by aressu1985** [comment]
fxied: a78a627bc
