### ISSUE TITLE
[Bug]: An error occurs when the show statement is executed on a common tenant.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#7910]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):1554f90b29d3b6bb2ce8d67c52b89fe48a87094b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Under common tenant:

execute sql:

drop database if exists test_db;
create database test_db;
use test_db;
drop table if exists test_table;
create table test_table(
col1 int,
col2 varchar
);

show index from test_table;

<img width="798" alt="截屏2023-02-08 17 17 12" src="https://user-images.githubusercontent.com/39303074/217487078-65e09e29-ee67-456a-a95a-352a52af5a6a.png">

**Comment by nnsgmsone** [comment]
same as 7890

**Comment by aressu1985** [comment]
it is the same aas #7890, this can be closed
