### ISSUE TITLE
[Bug]: Constraint definition is not displayed in show create table

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#7917]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a int primary key,b varchar(5));
create table t3( a int primary key, b int unique key, c int not null, d int,foreign key(d) references t1(a));

in mo :
<img width="383" alt="image" src="https://user-images.githubusercontent.com/88298673/217692491-78bb2fb7-600e-459e-b8a5-e4063237815f.png">

in mysql 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/88298673/217692889-8df901f4-4796-4299-89b0-602a192143e2.png">

**Comment by YANGGMM** [comment]
still on working

**Comment by ouyuanning** [comment]
same as https://github.com/matrixorigin/matrixone/issues/7934

**Comment by domingozhang** [comment]
fixed
