### ISSUE TITLE
[Bug]: point query  on external table no significant improvement over 0.6.0

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7919]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):fced41910b3d8f7ebcb6d50f364a1d51caad8ba6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The test results are recorded here ：https://github.com/matrixorigin/mo-nightly-regression/issues/46
![image](https://user-images.githubusercontent.com/113406637/217710157-ae80e5ee-5e0d-4791-80b3-ed02ebc6a46f.png)

**Comment by xzxiong** [comment]
建议对数据集进行2方面调整：
1. 构造多日的数据
2. 构造较大的数据文件

经过0.7.0版本迭代后，外表支持 如下新的特性：
1. 支持读取 tae格式文件，可使用 zoonmap 提升查询效率
    - 通过 zoonmap 可减少读取文件时执行的io 次数，理论上大文件的检索 会有更好的性能。
3. 支持隐藏列 __mo_filepath, 返回数据所在外表文件的真实路径。同时支持作为 字符串类型字段 进行过滤。
4. 支持 mo_log_date函数，可解析字符串中 `%Y/%m/%d`的日期字段。可作为 日期类型字段过滤
    - 可支持  mo_log_date(__mo_filepath)  between '2021-02-02' and '2023-02-02' 夸日期查询。

**Comment by heni02** [comment]
1.select count(*) from statement_info;
![image](https://user-images.githubusercontent.com/113406637/218719090-760285f0-8f08-46a3-ba5d-d3ae9bae1242.png)
2.select request_at,statement from statement_info where request_at>'2023-02-14 16:07:52' and request_at<'2023-02-14 16:09:52' order by request_at limit 5;
![image](https://user-images.githubusercontent.com/113406637/218722061-c3377706-137a-43f7-a48a-32d5d7cd06b0.png)
![image](https://user-images.githubusercontent.com/113406637/218722296-9b8efb0d-b8d7-4224-a5bb-251d7f3e8ef1.png)
3. select * from statement_info where statement_id='adafafe5-ac3e-11ed-ba14-b07b25f8aadc';
![image](https://user-images.githubusercontent.com/113406637/218725866-cadb29b3-24de-48b1-82c4-1455c4b8afee.png)
4.select request_at,statement  from statement_info where status='Failed' 
select request_at,statement  from statement_info where status='Failed' and statement='show accounts';
![image](https://user-images.githubusercontent.com/113406637/218727582-b474cf9f-732f-40dd-89cd-bb80c5e47ff9.png)
![image](https://user-images.githubusercontent.com/113406637/218727705-6dc7e4db-915a-4a02-a7c3-aa10cd0fc961.png)

**Comment by xzxiong** [comment]
metric/logs use ordinary table after https://github.com/matrixorigin/matrixone/issues/8196, retire exteranl table in tae file format

**Comment by heni02** [comment]
#8196 follow ,this issue closed
