### ISSUE TITLE
[Bug]: foreign key REFERENCES unique key reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7935]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6c16f387093d20da2498c5128416c977812d4151
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/217753028-c55ad954-2125-4577-9d07-b6bb3aedaa46.png)

### Steps to Reproduce

```Markdown
create table fk_01(col1 bigint unique key,col2 varchar(25),col3 tinyint);
create table fk_02(col1 bigint,col2 varchar(25),col3 tinyint,constraint ck foreign key(col1) REFERENCES fk_01(col1) on delete CASCADE on update CASCADE);
```

**Comment by ouyuanning** [comment]
waiting for new unique key def merge to tableDef

**Comment by qingxinhome** [comment]
The problem has been solved, please test. @heni02

**Comment by heni02** [comment]
confirm,closed
commit id:346277e3cb8e7aec9d68c043a3e9249e2c3cb842
![image](https://user-images.githubusercontent.com/113406637/218290699-12708ff7-eb0d-42a3-81fd-f057d53c5b21.png)
