### ISSUE TITLE
[Bug]: ctrl -c to abort query is not the same between arm[m1] and x64

### ISSUE THREAD

**Issue by mooleetzi** [matrixorigin/matrixone#7937]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

m1
<img width="837" alt="Screen Shot 2023-02-09 at 16 25 09" src="https://user-images.githubusercontent.com/42628885/217757046-3c8e3405-d443-4c0f-a47b-df4a67337b9f.png">

x64 linux 
<img width="948" alt="Screen Shot 2023-02-09 at 16 26 03" src="https://user-images.githubusercontent.com/42628885/217757228-d100d598-c9e3-424c-9e63-c2dea2b71808.png">

**Comment by daviszhen** [comment]
Try to find the context be cancelled or not when the ctrl+c happens.

**Comment by mooleetzi** [comment]
recheck, m1 need double ctrl+c while x64 only one.

**Comment by mooleetzi** [comment]
the first ctrl-c find there is no such connection which to be killed, then failed to kill target query.

**Comment by mooleetzi** [comment]
launch config in m1 is multi-cn.
`load data` exec in cn0, but first ctrl-c may send `kill query` to cn1, so cannot kill that `load`.
Thanks @daviszhen  for helping me figure it out.
