### ISSUE TITLE
[Bug]: TestNewMOCollector failed

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#7943]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TestNewMOCollector Failed

**Comment by xzxiong** [comment]
![image](https://user-images.githubusercontent.com/3927687/217810022-5a4aa055-215e-4b0f-9f5a-bf8b59ffb5ea.png)

**Comment by xzxiong** [comment]
from https://github.com/matrixorigin/matrixone/pull/7941

**Comment by xzxiong** [comment]
@nnsgmsone  fixed, ptal
