### ISSUE TITLE
[Bug]: Merge Dosen't take effect on system external tables

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7948]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):55e72cf26b1185dd3a95bb1a643b414809e2e6e3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

External files are not merged correctly.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/77312370/217823756-ef09dae9-d9d7-45dc-9c9f-7eba69ea3d74.png">

All files are small(kb-level)
<img width="996" alt="image" src="https://user-images.githubusercontent.com/77312370/217823982-357727c1-395c-4e87-ad5a-6b84a67fc05d.png">

**Comment by xzxiong** [comment]
trace merge task can run ok, 
after pr https://github.com/matrixorigin/matrixone/pull/7911 merged,  and config cn `TaskRunner.task-parallelism >= 2` like:

```toml
[cn.TaskRunner]
task-parallelism = 2
```

> TaskRunner.task-parallelism default value = CPUs / 16, in here https://github.com/matrixorigin/matrixone/blob/main/pkg/cnservice/types.go#L157

**Comment by xzxiong** [comment]
> trace merge task can run ok, after pr #7911 merged, and config cn `TaskRunner.task-parallelism >= 2` like:
> 
> ```toml
> [cn.TaskRunner]
> task-parallelism = 2
> ```
> 
> > TaskRunner.task-parallelism default value = CPUs / 16, in here https://github.com/matrixorigin/matrixone/blob/main/pkg/cnservice/types.go#L157

in pr https://github.com/matrixorigin/matrixone/pull/7964, modify cfg `task-parallelism` default val as `ReservedTasks + 1`
now `ReservedTasks = 2`
- 1 for metric StorageUsage
- 1 for trace ETLMerge

**Comment by sukki37** [comment]
Verified: 32a184fe
