### ISSUE TITLE
[Bug]: TPCC connection was hung on Nightly Regression Test 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#7951]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 15baa97
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TPCC 1 warehouse 10 terminals connection was hung on Nightly Regression Test with commit : 15baa97

The error log is as following:

023/02/10 04:21:25.451532 +0800 ERROR log-service util/log.go:133 txn send requests failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "requests": "[0: <4d98c3e0f5334d4a8a1ba121a8816790/Active/S:1675971685420501188-0>/Read/F-0/=><2-262146-0-127.0.0.1:22000>]", "error": "context deadline exceeded"}
github.com/matrixorigin/matrixone/pkg/txn/util.LogTxnSendRequestsFailed
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/util/log.go:133
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).doSend
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:491
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Read
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:252
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.getLogTail
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtail.go:58
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartition
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtail.go:42
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*DB).Update
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/db.go:322
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).New
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/engine.go:381
github.com/matrixorigin/matrixone/pkg/vm/engine.(*EntireEngine).New
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/entire_engine.go:33
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).NewTxn
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1542
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).TxnBegin
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1209
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3524
github.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:2453
github.com/matrixorigin/matrixone/pkg/frontend.determineUserHasPrivilegeSet
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/authenticate.go:4224
github.com/matrixorigin/matrixone/pkg/frontend.authenticateUserCanExecuteStatementWithObjectTypeDatabaseAndTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/authenticate.go:4659

the full log is very big ,if want, please contact me.

#8327 8327

**Comment by daviszhen** [comment]
I have not reproduced it .

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
明天会跟陶峰讨论下计划，

**Comment by daviszhen** [comment]
这个在复现

**Comment by daviszhen** [comment]
还未复现

**Comment by daviszhen** [comment]
这个在复现

**Comment by daviszhen** [comment]
今日在pc机上没有复现。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还在复现

**Comment by daviszhen** [comment]
还在复现

**Comment by gavinyue** [comment]
有可能需要docker 多cn才能复现

**Comment by daviszhen** [comment]
今天复现了一次。但是加打印后，就没复现了。我.....

**Comment by daviszhen** [comment]
无进展

**Comment by daviszhen** [comment]
还未看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
tpcc 10 仓 10 client 上跑出来下面的问题。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/5207eec4-ef17-4c85-8f06-8f440796c628)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/e9d78e59-dd3e-4f2b-adcd-8483b37336c2)

**Comment by daviszhen** [comment]
还跑出来了其它not found 问题。
![Screenshot from 2023-05-14 11-28-46](https://github.com/matrixorigin/matrixone/assets/60595215/0baa6eb0-0764-416a-92f7-bcf226c30e65)
![Screenshot from 2023-05-14 11-29-29](https://github.com/matrixorigin/matrixone/assets/60595215/79a9f3af-76cd-4357-ad86-d7e36cf81a89)

**Comment by LeftHandCold** [comment]
> 在另一台pc机上，与上一条同样tpcc。还跑出来了其它not found 问题。
> 
> 我这边有完整的日志。
> 
> ![Screenshot from 2023-05-14 11-28-46](https://user-images.githubusercontent.com/60595215/238166020-0baa6eb0-0764-416a-92f7-bcf226c30e65.png) ![Screenshot from 2023-05-14 11-29-29](https://user-images.githubusercontent.com/60595215/238166022-79a9f3af-76cd-4357-ad86-d7e36cf81a89.png)

This is the file that needs to be deleted during rollback. not found has no effect.

**Comment by xzxiong** [comment]
> tpcc 10 仓 50 client 上跑出来下面的问题。
> 
> commitId ： [5a56540](https://github.com/matrixorigin/matrixone/commit/5a565405ac02dd4ddcd86ffb2a6e3696edc4f224)
> 
> ![image](https://user-images.githubusercontent.com/60595215/238164189-5207eec4-ef17-4c85-8f06-8f440796c628.png)
> 
> ...

trace in https://github.com/matrixorigin/matrixone/issues/9424

**Comment by daviszhen** [comment]
今天tpcc 1仓 10 client。跑出来了oom。

![Screenshot from 2023-05-15 19-04-14](https://github.com/matrixorigin/matrixone/assets/60595215/4713c17d-e423-450a-8bc5-4ba79870e040)

**Comment by daviszhen** [comment]
锁住的问题还在复现中。

**Comment by daviszhen** [comment]
昨天在pc机上。10仓，50 clients。复现了卡住问题。

卡住的状态：

![Screenshot from 2023-05-16 11-08-38](https://github.com/matrixorigin/matrixone/assets/60595215/c1e71d15-06b2-40d3-ac30-838ba8f8b9b0)

![Screenshot from 2023-05-16 11-09-01](https://github.com/matrixorigin/matrixone/assets/60595215/e4c742c1-0a41-4942-b20b-e74e44076de5)

![Screenshot from 2023-05-16 11-09-58](https://github.com/matrixorigin/matrixone/assets/60595215/dd3da6d7-0b6c-4186-b6e5-dbd867472d3b)

![Screenshot from 2023-05-16 11-10-25](https://github.com/matrixorigin/matrixone/assets/60595215/760d99df-e7bd-4f6b-b8e3-aa8acdb785d5)

卡住的代码位置：
https://github.com/matrixorigin/matrixone/blob/15baa9727b116288c0eaec31aa815d4fd3510246/pkg/vm/engine/disttae/db.go#L311


![5901684207170_ pic](https://github.com/matrixorigin/matrixone/assets/60595215/c192da99-23b2-4c1f-98ab-714cbae76f56)

**Comment by cnutshell** [comment]
There are two goroutine that block on select.
<img width="1161" alt="WeChatWorkScreenshot_9e502b28-92d8-4b66-90d8-717047ae0800" src="https://github.com/matrixorigin/matrixone/assets/20291742/4331257d-b934-4a84-baea-01005d7a54bd">
<img width="818" alt="WeChatWorkScreenshot_015ddf85-8054-4a82-9235-5749b8d5ddfa" src="https://github.com/matrixorigin/matrixone/assets/20291742/c8021f8d-a31a-4f94-8aa1-533129960d6b">

**Comment by daviszhen** [comment]
打开debug日志，跑了一晚上。没有复现。
切换到main分支。今天晚上再跑。

**Comment by daviszhen** [comment]
昨天在main上 （commit 2e4ef52 )跑了11个小时tpcc。没有复现hung住的问题。
今天晚上再跑tpcc。

**Comment by daviszhen** [comment]
昨晚tpcc跑了一晚上。没有卡住。从20:58 ～ 07:58。

**Comment by daviszhen** [comment]
在 main commit 2e4ef52 上测了两天。没再复现。

**Comment by aressu1985** [comment]
fixed
