### ISSUE TITLE
[Bug]:result of a bvt case is unstable

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#7954]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5ba97125977db26f86a46488279d8d19e82d4e3a (on branch https://github.com/daviszhen/matrixone/tree/0209-debug-kills)
- Hardware parameters:
- OS type:
- Others:
- pr: https://github.com/matrixorigin/matrixone/pull/7947
```

### Actual Behavior

bvt case: https://github.com/matrixorigin/matrixone/actions/runs/4134531423/jobs/7145779028

Sometimes, the result of running bvt case is different from result file

![image](https://user-images.githubusercontent.com/60595215/217989394-f41794d6-b219-4dcf-a1d6-723daaa4feb6.png)

### Expected Behavior

stable bvt case

**Comment by xzxiong** [comment]
fixed, ptal

**Comment by daviszhen** [comment]
it was fixed by @xzxiong
