### ISSUE TITLE
[Bug]: performance：dump 5000w+ rows table into sql more than 3hours unsuccessful

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7962]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c66a33c480cf7a17c7a02533de960616931315ec
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/218048327-bf63ad4d-4f8e-40e3-92a5-1371c2122fdc.png)
![image](https://user-images.githubusercontent.com/113406637/218048467-8dbe8e1e-e58a-48c3-95d0-064739f46977.png)

### Steps to Reproduce

create table table_5000w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,
col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255));
load data infile {"filepath"='/Users/heni/test_data/50000000_20_columns_load_data.csv'} into table table_5000w;
./mo-dump -u dump -p 111 -db db >t1.sql

**Comment by mooleetzi** [comment]
after checking with @heni02 ,data is dumping with no error.
so maybe feature request to enhance modump.

**Comment by heni02** [comment]
about 10hours dump successfully
<img width="739" alt="企业微信截图_f1228a4c-de9e-4f65-856a-47a3334b372f" src="https://user-images.githubusercontent.com/113406637/218242113-c32fad9a-337f-4ab3-a431-0819167d6794.png">

**Comment by heni02** [comment]
plz connect me t1.sql to reproduce @mooleetzi

**Comment by mooleetzi** [comment]
perf I see, enhance it next week, but I guess `no such table` is not scope of `modump`.

**Comment by mooleetzi** [comment]
commitId: 32a184fe74eaca188da18a6ab9f903a957d0fcc1
same `7308789` rows data.
mysqldump
<img width="725" alt="Screen Shot 2023-02-13 at 13 44 03" src="https://user-images.githubusercontent.com/42628885/218380065-26ddd98d-61f2-4678-8a8b-5a3c6afd5a07.png">
mo-dump
<img width="649" alt="Screen Shot 2023-02-13 at 13 44 55" src="https://user-images.githubusercontent.com/42628885/218380190-e5c292ba-6e2d-4348-8988-7fcd3f4f5046.png">

**Comment by heni02** [comment]
muti-cn-dn-tae start up ,reported error SQL parser error: table "table_5000w" does not exist
<img width="1566" alt="企业微信截图_bb480cb0-4d10-4ea7-a4bf-6b976a244c4a" src="https://user-images.githubusercontent.com/113406637/218694162-b53cd9d3-9de7-4670-9fcf-be4d9ce778b1.png">

**Comment by mooleetzi** [comment]
#8004 merged, pls retest performance @heni02 
and, let me check pre out sql.

**Comment by heni02** [comment]
now dump 5200w+ rows table only about no more 1min, @mooleetzi but source sql  take a long time，Can insert values be executed in parallel to improve speed？

**Comment by mooleetzi** [comment]
`execution time` added in #8046.
@heni02 PTAL

**Comment by heni02** [comment]
confirm,closed
commit id: 0.7.0 6d4bd173514990032372310f7b3d9d803781074a
![image](https://user-images.githubusercontent.com/113406637/220003551-65492a50-7658-4227-b0fb-48c57881ddf2.png)
