### ISSUE TITLE
[Bug]: insert into table select from external table which 100w+ rows reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#7972]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):346277e3cb8e7aec9d68c043a3e9249e2c3cb842
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

select from external table is 100w+ rows
![image](https://user-images.githubusercontent.com/113406637/218291720-2c54b714-fabd-4cca-9b3e-62bf03861b8c.png)

### Steps to Reproduce

```Markdown
create external table ex_table_100w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,
col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255))infile{"filepath"='/Users/heni/test_data/1000000_20_columns_load_data.csv'} ;
create table table_100w(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date, col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255));
insert into table_100w select * from ex_table_100w;
```

**Comment by heni02** [comment]
plz connect me to get 1000000_20_columns_load_data.csv @JackTan25

**Comment by jensenojs** [comment]
the stat has some problem, cause didn't go through s3
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/56761542/218293179-56695c75-b082-4f17-9e01-e3eb9d8cfd3a.png">

**Comment by jensenojs** [comment]
I'll follow up this afternoon to see what the problem is

**Comment by heni02** [comment]
I try 20columns 1 yi rows ，reported error ERROR 1105 (HY000): gob: encoder: message too big
![image](https://user-images.githubusercontent.com/113406637/218301035-f0a56d8d-2736-49c4-ba60-eddf24a1206e.png)

**Comment by heni02** [comment]
insert select from external table 20columns 1000w+ data ，also reported internal error: message body 3539869968 is too large, max is 104857600
![image](https://user-images.githubusercontent.com/113406637/218301514-c25afb0e-0922-4d18-b114-339b2bd5fae6.png)

**Comment by badboynt1** [comment]
external table does not support stats

**Comment by nnsgmsone** [comment]
Now the logic relies on stats to write s3, the subsequent regardless of stats, as long as the amount of data will be enough to write s3

**Comment by jensenojs** [comment]
No process

**Comment by jensenojs** [comment]
No process

**Comment by jensenojs** [comment]
No process

**Comment by jensenojs** [comment]
No process

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
not working on it

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
On leave of absence

**Comment by jensenojs** [comment]
On leave of absence

**Comment by JackTan25** [comment]
see #8325

**Comment by heni02** [comment]
confirm,closed
commit id:93ca8a381ad2532e34cc83a935916e70cc9aef4d
![image](https://user-images.githubusercontent.com/113406637/227434013-8e88e298-e0ad-45b4-b060-5df982684d6a.png)
