### ISSUE TITLE
[Feature Request]: change composite primary key col name format

### ISSUE THREAD

**Issue by bbbearxyz** [matrixorigin/matrixone#7986]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

now composite primary key col name rely on the single col parts, the name should change to __mo_cpkey + uuid

**Comment by sukki37** [comment]
Could you optimize the test coverage of your code.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/77312370/220230802-3d2133cf-1a68-4505-9624-6ae885f9ebbb.png">

**Comment by sukki37** [comment]
outdated issue, closed.
