### ISSUE TITLE
[Subtask]: Add syntax and plan for the Lock/Unlock table statement

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#7988]
### Parent Issue

Lock/Unlock table. #4971

### Detail of Subtask

Add syntax and plan for the Lock/Unlock table statement

**Comment by YANGGMM** [comment]
LOCK TABLES
    tbl_name [[AS] alias] lock_type
    [, tbl_name [[AS] alias] lock_type] ...

lock_type: {
    READ [LOCAL]
  | [LOW_PRIORITY] WRITE
}

UNLOCK TABLES

**Comment by YANGGMM** [comment]
Now we only need to support READ and WRITE LOCK type

**Comment by YANGGMM** [comment]
![image](https://user-images.githubusercontent.com/26563383/219314695-be69e2e6-20a7-4a1e-a8a3-f198e871442e.png)

**Comment by daviszhen** [comment]
完成
