### ISSUE TITLE
[Subtask]: Alter indexes of the ALTER TABLE statement

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#7992]
### Parent Issue

https://github.com/matrixorigin/matrixone/issues/6599

### Detail of Subtask

Alter indexes of the ALTER TABLE statement

**Comment by qingxinhome** [comment]
Under development

**Comment by qingxinhome** [comment]
Pr has been submitted

**Comment by qingxinhome** [comment]
This requirement has been implemented, please test @daviszhen @domingozhang

**Comment by qingxinhome** [comment]
This function has been implemented, please close it @daviszhen @sukki37
