### ISSUE TITLE
[Bug]: Strange Performance on querying `system.statement_info` 

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#7997]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 55e72cf26b1185dd3a95bb1a643b414809e2e6e3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="454" alt="image" src="https://user-images.githubusercontent.com/77312370/218393369-39c1c1c5-036b-4516-ac4a-15d12593d4ef.png">

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/pull/8825

Very close to merge.  

The pending task is modify statement_info table query as mo_table, so other account/users can query the data.

**Comment by gavinyue** [comment]
Also a bvt test is required.

**Comment by gavinyue** [comment]
Still work on the PR to switch logging to internal table.  So this issue needs more time.

**Comment by gavinyue** [comment]
Same as above

**Comment by gavinyue** [comment]
Currently block on https://github.com/matrixorigin/matrixone/issues/7767

**Comment by fengttt** [comment]
Please resolve.

**Comment by gavinyue** [comment]
Resolve this issue since this table no longer an external table.

**Comment by gavinyue** [comment]
Pending.

**Comment by gavinyue** [comment]
Probably could close this one? @sukki37

**Comment by sukki37** [comment]
test pas
