### ISSUE TITLE
[Refactoring]: rectify the semantics of `morpc.WithCodecMaxBodySize`

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#7998]
### Why do you want to refactor this code?

When using morpc, application specifies its max message size via `morpc.WithCodecMaxBodySize`.
If the message size was larger than this specified max message size, say `MaxMessageSize`, then application should split the message into chunks. And if the size of the chunk equals to `MaxMessageSize`, it wouldn't be allowed to pass through because of morpc internal header.

### Describe the solution you'd like

Morpc internal header should be transparent to application. If application splits larger message according to its specified `MaxMessageSize`, the chunk should be allowed to pass through.

**Comment by zhangxu19830126** [comment]
done

**Comment by zhangxu19830126** [comment]
@cnutshell
