### ISSUE TITLE
[Bug]: use [db];select count(*) from [table] indicates table does not exist, but select count(*) from [db].[table] is ok

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#8021]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 4edde23d886b044ae5bb41477bd3e486ef8fe5e3
- Hardware parameters: 16 core, 64g
- OS type: CentOS Stream release 8
- Others:
```

### Actual Behavior

I found this issue accidentally when I test the performance of a load command. When the data is loaded from csv file into the table, I tried to select count(*) from this table, when MO returned me with the error indicating the table does not exist. However I can see the table is there when using show tables command. When I ran select count(*) from this table again, at first it looked like the command was running, but after hitting ctrl + c to abort the query, it threw me again the same error.

![image](https://user-images.githubusercontent.com/46433151/218485000-60b8f466-7884-4150-930f-fc19550d1481.png)

![image](https://user-images.githubusercontent.com/46433151/218485053-c2d02b98-f954-4e84-b746-c5355b48c547.png)

### Expected Behavior

The table does not exist error should not be thrown when I ran select count(*) form it, since the table is already created and data already loaded into the table.

### Steps to Reproduce

Markdown
1、Start MO：./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
2、Create the meta data of the database and table：
refer to https://github.com/matrixorigin/MO-Cloud/issues/396
3、Load data into table：
```
load data infile './mo_40y_data.csv' into table dtwin_sim_data_lake.sim_track_main_local FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
```
The data is illustrated in the URL above。
4、Check number of records：
```
select count(*) from dtwin_sim_data_lake.sim_track_main_local;
```

### Additional information

please check logs as attached in：
https://github.com/matrixorigin/MO-Cloud/issues/396

**Comment by daviszhen** [comment]
i am not focus on it today

**Comment by daviszhen** [comment]
I am not working on it

**Comment by aronchanisme** [comment]
The issue does not come back recently, hence I am closing it as for now.
