### ISSUE TITLE
[Bug]: High number of unnecessary S3 ListObjects requests by matrixone causing high cost

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#8023]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-32a184fe
```

### Actual Behavior

The matrixone process is generating a high number of S3 ListObjects requests which seems to be caused by the ETL module making multiple calls to the fileservice List function. These requests are causing a high cost overhead and we need to investigate if these requests are necessary, and whether we can reduce the frequency or combine requests to better control cost.

### Expected Behavior

Matrixone should make necessary requests to the fileservice List function with reasonable frequency to avoid high cost overhead.

### Steps to Reproduce

Steps to Reproduce:

1. Enable S3 logging and tracking
2. Run matrixone cluster on the target s3 bucket
3. Observe the high number of S3 ListObjects requests being made by running the following SQL in AWS Athena

```sql
SELECT COUNT(*), operation
FROM s3_access_logs_db.mybucket_logs
GROUP BY operation
```

4. Find samples that have request uri indicate the problem may occurs in ETL module (backed by external table)

```sql
SELECT *
FROM s3_access_logs_db.mybucket_logs 
WHERE operation='REST.GET.BUCKET' 
LIMIT 10;
```

the request URI returned would be something like this `	
"GET /?delimiter=%2F&list-type=2&prefix=freetier-1-htUD%2Fetl%2Ffc562e35_0036_465a_bfc8_ec710956bafd%2Fmerged%2F2023%2F02%2F HTTP/1.1"`

### Additional information

- AWS S3 region: us-west-2
- S3 bucket: mocloud-test
- Request path: ***etl***

**Comment by aylei** [comment]
Since the request URI indicates the problem may related to external table (the URI is under `etl` prefix, which is the data external table stored), could you please take a look @jianwan0214 ?

**Comment by reusee** [comment]
External tables are not cached. Maybe @jianwan0214 knows how to reduce the number of List calls.

**Comment by sukki37** [comment]
> External tables are not cached. Maybe @jianwan0214 knows how to reduce the number of List calls.

Is there no default cache for s3 call?

**Comment by fengttt** [comment]
Why not cached?   It is a S3 read, why not.

listobject, I don't know what can we do about it.   Is that due to too many objects, or, what ...    maybe we have to build list obj cache.   maybe we should move log into our database, or, at least we can move file names into the database.

**Comment by reusee** [comment]
There are two file services for S3 read/write.
One is for TAE or other internal systems that we can ensure no object will be modified after creation. This file service can be cached.
One is for ETL or external tables. We're not caching this because external systems may modify objects.

**Comment by reusee** [comment]
And LIST operations can never be cached.

**Comment by reusee** [comment]
I don't think the file service can do anything to reduce the number of LIST calls.
Callers should do this. Un-assigning myself.

**Comment by aylei** [comment]
I think the LIST request rate is abnormal since the rate is order of magnitude greater than other operations, the following athena query shows the request rate in last two days of an idle mo cluster on mo-cloud:

Query:
```
SELECT COUNT(*), operation
FROM s3_access_logs_db.mybucket_logs 
WHERE
parse_datetime(requestdatetime,'dd/MMM/yyyy:HH:mm:ss Z') 
BETWEEN parse_datetime('2023-02-18:00:00:00','yyyy-MM-dd:HH:mm:ss')
AND 
parse_datetime('2023-02-20:00:00:00','yyyy-MM-dd:HH:mm:ss') 
GROUP BY operation 
```

Result:
```
#	_col0	operation
1	451	REST.POST.MULTI_OBJECT_DELETE
2	1448303	REST.GET.OBJECT
3	33212004	REST.GET.BUCKET
4	315230	BATCH.DELETE.OBJECT
5	786056	REST.HEAD.OBJECT
6	857	REST.HEAD.BUCKET
7	786053	REST.PUT.OBJECT
8	58	REST.DELETE.OBJECT
```

`REST.GET.BUCKET` is corresponding to `ListObject` operation. The `Get` to`List` ratio is about 1:20, looks like we somehow rely on S3 as our object **index**, which is inappropriate IMHO.

**Comment by reusee** [comment]
I remember that the query result cache is generating a large number of objects in a single dir. That will require many LIST calls to iterate all objects.
I don't think it's a good idea to put too many objects in one dir.

**Comment by xzxiong** [comment]
query external table with condition `account = ?` STILL list all account's folder  @jianwan0214 

for example: in MO `mysql -hfreetier-1.cluster.dev.matrixone.tech -P6001 -udump -p***** --ssl-mode=DISABLED`
use s3 bucket `mocloud-test` and filepath `freetier-1-2uah`

query one time on table statement_info  cost  **62 S3FS.List**

- statemnt_id = `bdecaa13-b985-11ed-9469-02753491e79c`
    - query: ` select count(1) cnt, span_name, trace_id from system.span_info where mo_log_date(__mo_filepath) = '2023-03-03' and span_name = "S3FS.List" group by span_name, trace_id order by cnt;` 

![企业微信截图_e2e428e6-419b-46d4-bd95-edf4cbcd91f5](https://user-images.githubusercontent.com/3927687/222705558-37eaae50-ab3b-46bb-a957-b6f757dadb1d.png)

- statement `select * from system.statement_info where status != ? and account = ? order by response_at asc limit 1
`
( statement_info record )
![企业微信截图_0b3e7bb5-8740-43f3-a87f-cba881370059](https://user-images.githubusercontent.com/3927687/222705583-b9dbeb06-0375-4d47-a25f-0957dc0460a9.png)

- S3FS.List all between  `compileExternScan.ReadDir` and `filterByAccountAndFilename`
    - query: `select span_name, span_kind, start_time, span_id, parent_span_id from system.span_info where trace_id = 'bdecaa13-b985-11ed-9469-02753491e79c' order by start_time;`
![企业微信截图_973d0d75-d5de-40f6-a409-2d414edab1b4](https://user-images.githubusercontent.com/3927687/222705596-a996c756-eb2c-4d51-834e-8eaca8ef1252.png)

![image](https://user-images.githubusercontent.com/3927687/222706152-dc4db250-4af7-4a15-96b7-a6aadf2157a2.png)

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/issues/7997

related with this issue.

**Comment by gavinyue** [comment]
Will resolve this issue since converted into internal table.

**Comment by gavinyue** [comment]
Pending.

**Comment by gavinyue** [comment]
@aylei Is this still a problem after we switch to use the normal table? 

Thanks.

**Comment by aylei** [comment]
> @aylei Is this still a problem after we switch to use the normal table?
> 
> Thanks.

@gavinyue I will verify this soon

**Comment by aylei** [comment]
looking into it

**Comment by aylei** [comment]
```
#	_col0	operation
1	526	BATCH.DELETE.OBJECT
2	3642	REST.HEAD.OBJECT
3	1	REST.GET.OWNERSHIP_CONTROLS
4	2	REST.GET.VERSIONING
5	7	REST.POST.MULTI_OBJECT_DELETE
6	1	REST.GET.WEBSITE
7	1	REST.PUT.LOGGING_STATUS
8	1	REST.HEAD.BUCKET
9	7	REST.GET.BUCKET
10	3645	REST.PUT.OBJECT
11	1	REST.GET.ENCRYPTION
12	1	REST.GET.REQUEST_PAYMENT
13	122	REST.DELETE.OBJECT
14	4002	REST.GET.OBJECT
```

verified on EKS, the qps distribution looks reasonable and the requests of `REST.GET.BUCKET` is rare.
