### ISSUE TITLE
[Feature Request]: SQL Proxy module implement

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#8025]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

implement SQL proxy module.

related link:

https://github.com/matrixorigin/MO-Cloud/issues/385

https://github.com/matrixorigin/docs/tree/main/tech-notes/sql/design/proxy

**Comment by volgariver6** [comment]
done with pr #8778.

**Comment by heni02** [comment]
0.8 test done
