### ISSUE TITLE
query result is incorrect with some operator

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#804]
#### Can be reproduced ?
Yes

#### Steps:
drop table if exists t1;
CREATE TABLE t1 (spID int,userID int,score int);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

select userID,spID,score from t1 where spID<(userID+score)/2;
+------+--------+-------+
| spID | userID | score |
+------+--------+-------+
|    1 |      1 |     5 |
|    4 |      6 |    10 |
|    5 |     11 |    99 |
+------+--------+-------+
3 rows in set (0.00 sec)

In Mysql the result is
+--------+------+-------+
| userID | spID | score |
+--------+------+-------+
|      1 |    2 |     4 |
|      1 |    1 |     5 |
|      6 |    4 |    10 |
|     11 |    5 |    99 |
+--------+------+-------+
4 rows in set (0.00 sec)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):  02f4c25a501b015b19609bdc3b172d39df4ec8c8
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by anitajjx** [comment]
Verified and fixed with commit 693ab24c885ee26df6fe5ad467dd46c7cbdbe950
