### ISSUE TITLE
[Bug]: lots of txn context deadline exceeded error when running tpcc 10w test for about 2 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8042]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6ca6dc7bed252a2ef72d97f57e37342fccfeabf3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

error log:

2023/02/15 13:15:56.913432 +0800 ERROR log-service task/task_scheduler.go:118 failed to query tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "status": "Running", "error": "context deadline exceeded"}
github.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).queryTasks
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/hakeeper/task/task_scheduler.go:118
github.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).Schedule
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/hakeeper/task/task_scheduler.go:53
github.com/matrixorigin/matrixone/pkg/logservice.(*store).taskSchedule
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store_hakeeper_check.go:199
github.com/matrixorigin/matrixone/pkg/logservice.(*store).hakeeperCheck
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store_hakeeper_check.go:143
github.com/matrixorigin/matrixone/pkg/logservice.(*store).ticker
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store.go:671
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica.func1
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store.go:224
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
2023/02/15 13:15:56.913491 +0800 INFO frontend/util.go:500 query trace {"connection_id": 1002, "query": "deallocate prepare __mo_stmt_id_64", "session_info": "connectionId 1002"}

2023/02/15 15:13:27.352729 +0800 ERROR frontend/session.go:1704 GetTxn. error:context deadline exceeded
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).GetTxn
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1704
github.com/matrixorigin/matrixone/pkg/frontend.doUse
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1041
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleChangeDB
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1059
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3583
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4375
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
        /home/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by nnsgmsone** [comment]
I'll be at 0.8 fix.

**Comment by aressu1985** [comment]
#8327

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
I will deal with the memory issue first

**Comment by nnsgmsone** [comment]
context的问题等彭正重构后测试，如果还有这个问题再看

**Comment by aressu1985** [comment]
@daviszhen pls tracking this issue

**Comment by daviszhen** [comment]
@taofengliu  复现一下看看

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
明天会跟陶峰讨论下计划，

**Comment by taofengliu** [comment]
working on it soon

**Comment by taofengliu** [comment]
work on it soon

**Comment by taofengliu** [comment]
work on it soon

**Comment by taofengliu** [comment]
work on it soon

**Comment by taofengliu** [comment]
work on it soon

**Comment by taofengliu** [comment]
work on it soon

**Comment by daviszhen** [comment]
没进展

**Comment by daviszhen** [comment]
今天找到复现方法。复现了一次。

**Comment by daviszhen** [comment]
明确了初步原因，是有两方面的原因。明天给出详细的分析。

**Comment by daviszhen** [comment]
**第二种超时情况：建立连接+use mo_task+show tables 超时**

这里给出典型的case。

1，查询任务开始
2023/05/09 15:56:01.705104 +0800 INFO log-service task/task_scheduler.go:125 ts.QueryTask {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "scheduler.queryTasks": 1, "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:987ns farawayToDeadline:1.999979905s"}
2023/05/09 15:56:01.705137 +0800 INFO log-service taskservice/task_service_holder.go:241 refreshableTaskStorage.Query begin {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:35.438µs farawayToDeadline:1.999945388s"}
2023/05/09 15:56:01.705169 +0800 INFO log-service taskservice/mysql_task_storage.go:429 mysqlTaskStorage.Query begin {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:67.404µs farawayToDeadline:1.999913402s"}

2，发请求给mo。
[mysql] 2023/05/09 15:56:01 connection.go:459: ping127.0.0.1:55381 127.0.0.1:6001
[mysql] 2023/05/09 15:56:01 connection.go:519: ExecContext127.0.0.1:55381 127.0.0.1:6001use mo_task
[mysql] 2023/05/09 15:56:01 connection.go:298: Exec127.0.0.1:55381 127.0.0.1:6001use mo_task

//mo收到use mo_task
2023/05/09 15:56:01.734215 +0800 INFO frontend/util.go:500 query trace {"connection_id": 1113, "query": "use mo_task", "session_info": "connectionId 1113 client 127.0.0.1:55381"}
[mysql] 2023/05/09 15:56:02 connection.go:499: QueryContext127.0.0.1:55381 127.0.0.1:6001show tables
2023/05/09 15:56:02.578054 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 1113, "statement": "use mo_task", "status": "success", "span": {"trace_id": "f1048cde-ee3e-11ed-8fe6-aa665a28570d", "kind": "statement"}, "session_info": "connectionId 1113 client 127.0.0.1:55381"}

//mo接收show tables
2023/05/09 15:56:02.658053 +0800 INFO frontend/util.go:500 query trace {"connection_id": 1113, "query": "show tables", "session_info": "connectionId 1113 client 127.0.0.1:55381"}
2023/05/09 15:56:03.633887 +0800 INFO frontend/util.go:515 time of Exec.Build : 975.755577ms connectionId 1113 client 127.0.0.1:55381
2023/05/09 15:56:03.880185 +0800 INFO frontend/util.go:515 time of Exec.Run : 35.942242ms connectionId 1113 client 127.0.0.1:55381
2023/05/09 15:56:03.961038 +0800 INFO frontend/util.go:500 query trace status {"connection_id": 1113, "statement": "show tables", "status": "success", "span": {"trace_id": "f1918012-ee3e-11ed-8fe7-aa665a28570d", "kind": "statement"}, "session_info": "connectionId 1113 client 127.0.0.1:55381"}

//show tables正常响应。但此时已经超过deadline
2023/05/09 15:56:03.961611 +0800 INFO log-service taskservice/mysql_task_storage.go:438 mysqlTaskStorage.Query getDB ok {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:2.256450036s farawayToDeadline:-256.469221ms"}

//context已经超时
2023/05/09 15:56:04.098665 +0800 INFO log-service taskservice/mysql_task_storage.go:445 mysqlTaskStorage.Query Conn error {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:2.393475443s farawayToDeadline:-393.494877ms", "error": "context deadline exceeded"}
2023/05/09 15:56:04.137924 +0800 INFO log-service taskservice/mysql_task_storage.go:431 mysqlTaskStorage.Query end {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:2.432763892s farawayToDeadline:-432.783081ms"}
2023/05/09 15:56:05.142754 +0800 INFO log-service taskservice/task_service_holder.go:243 refreshableTaskStorage.Query end {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:3.437574548s farawayToDeadline:-1.437593875s"}
2023/05/09 15:56:05.142787 +0800 INFO log-service task/task_scheduler.go:129 ts.QueryTask {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "scheduler.queryTasks": 2, "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:3.437608965s farawayToDeadline:-1.43762823s"}
2023/05/09 15:56:05.142822 +0800 ERROR log-service task/task_scheduler.go:133 failed to query tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: d1da973c-60a1-4ba9-ab13-f07ea4e44436, Start: 2023-05-09 15:56:01.705097 +0800 CST m=+382.046677302 fromStart:3.437642934s farawayToDeadline:-1.437662276s", "status": "Created", "error": "context deadline exceeded"}

**Comment by daviszhen** [comment]
此外，下面这种情况，没有复现出来。

2023/02/15 15:13:27.352729 +0800 ERROR frontend/session.go:1704 GetTxn. error:context deadline exceeded
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).GetTxn
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1704
github.com/matrixorigin/matrixone/pkg/frontend.doUse
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1041
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleChangeDB
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1059
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3583
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4375
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
/home/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381

**Comment by daviszhen** [comment]
这个问题指定s-1不合理。

**Comment by daviszhen** [comment]
改进方法，要么mo查询性能提升，要么增大异步调度任务的超时阈值。

**Comment by daviszhen** [comment]
我实验了将超时时间改为10s，依然会有超时错误context deadline exceeded。但是超时的频率大幅下降。

典型的case：

1，查询任务开始

2023/05/10 11:15:40.481549 +0800 INFO log-service task/task_scheduler.go:125 ts.QueryTask {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "scheduler.queryTasks": 1, "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:1.218µs farawayToDeadline:9.999983462s"}
2023/05/10 11:15:40.481595 +0800 INFO log-service taskservice/task_service_holder.go:241 refreshableTaskStorage.Query begin {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:48.866µs farawayToDeadline:9.999935745s"}
2023/05/10 11:15:40.481675 +0800 INFO log-service taskservice/mysql_task_storage.go:434 mysqlTaskStorage.Query begin {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:123.305µs farawayToDeadline:9.999861222s"}

2，连接mo
[mysql] 2023/05/10 11:15:40 connection.go:459: ping127.0.0.1:53120 127.0.0.1:6001

3，发送use_task
[mysql] 2023/05/10 11:15:40 connection.go:519: ExecContext127.0.0.1:53120 127.0.0.1:6001use mo_task
[mysql] 2023/05/10 11:15:40 connection.go:298: Exec127.0.0.1:53120 127.0.0.1:6001use mo_task

//mo 收到use mo_task
2023/05/10 11:15:40.495404 +0800 INFO frontend/util.go:403 query trace {"connection_id": 70, "query": "use mo_task", "session_info": "connectionId 70|127.0.0.1:53120|{account sys:1b828b80-f7ec-4479-a72b-acb90dc4583b:moadmin -- 0:4294967295:0}|e4aeb822-eee0-11ed-88c8-aa665a28570d"}

4，发送show tables
[mysql] 2023/05/10 11:15:42 connection.go:499: QueryContext127.0.0.1:53120 127.0.0.1:6001show tables

5，mo use_task 执行完成。耗时2s
2023/05/10 11:15:42.369732 +0800 INFO frontend/util.go:403 query trace status {"connection_id": 70, "statement": "use mo_task", "status": "success", "span": {"trace_id": "f130f114-eee0-11ed-88d4-aa665a28570d", "kind": "statement"}, "session_info": "connectionId 70|127.0.0.1:53120|{account sys:1b828b80-f7ec-4479-a72b-acb90dc4583b:moadmin -- 0:4294967295:0}|e4aeb822-eee0-11ed-88c8-aa665a28570d"}

// mo 收到show tables
2023/05/10 11:15:42.409551 +0800 INFO frontend/util.go:403 query trace {"connection_id": 70, "query": "show tables", "session_info": "connectionId 70|127.0.0.1:53120|{account sys:1b828b80-f7ec-4479-a72b-acb90dc4583b:moadmin -- 0:4294967295:0}|e4aeb822-eee0-11ed-88c8-aa665a28570d"}

//show tables 构建计划耗时7.4s
2023/05/10 11:15:49.909764 +0800 INFO frontend/util.go:418 time of Exec.Build : 7.440988448s connectionId 70|127.0.0.1:53120|{account sys:1b828b80-f7ec-4479-a72b-acb90dc4583b:moadmin -- 0:4294967295:0}|e4aeb822-eee0-11ed-88c8-aa665a28570d

//show tables执行完成。总耗时7.5s
2023/05/10 11:15:49.965462 +0800 INFO frontend/util.go:403 query trace status {"connection_id": 70, "statement": "show tables", "status": "success", "span": {"trace_id": "f25e014e-eee0-11ed-88d5-aa665a28570d", "kind": "statement"}, "session_info": "connectionId 70|127.0.0.1:53120|{account sys:1b828b80-f7ec-4479-a72b-acb90dc4583b:moadmin -- 0:4294967295:0}|e4aeb822-eee0-11ed-88c8-aa665a28570d"}

//use mo_task; show tables 距离10s超时时间还有516ms。
2023/05/10 11:15:49.965569 +0800 INFO log-service taskservice/mysql_task_storage.go:443 mysqlTaskStorage.Query getDB ok {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:9.483726108s farawayToDeadline:516.258155ms"}
2023/05/10 11:15:49.967655 +0800 INFO log-service taskservice/mysql_task_storage.go:453 mysqlTaskStorage.Query Conn ok {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:9.485817603s farawayToDeadline:514.16685ms"}

//发送查询select
2023/05/10 11:15:49.967726 +0800 INFO log-service taskservice/mysql_task_storage.go:474 mysqlTaskStorage.Query send {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:9.485891218s farawayToDeadline:514.093249ms", "deadline": "2023-05-10 11:15:50.481526 +0800 CST m=+212.480818234", "query": "select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_status=0 order by task_id"}

//已经超时。
2023/05/10 11:15:50.482152 +0800 INFO log-service taskservice/mysql_task_storage.go:481 mysqlTaskStorage.Query get resp error {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "time": "514.302526ms", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:10.000293423s farawayToDeadline:-309.311µs", "query": "select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_status=0 order by task_id", "error": "context deadline exceeded"}
2023/05/10 11:15:50.491168 +0800 INFO log-service taskservice/mysql_task_storage.go:436 mysqlTaskStorage.Query end {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:10.009309683s farawayToDeadline:-9.325217ms"}
2023/05/10 11:15:51.853399 +0800 INFO log-service taskservice/task_service_holder.go:243 refreshableTaskStorage.Query end {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:11.371501927s farawayToDeadline:-1.371517737s"}
2023/05/10 11:15:51.875096 +0800 INFO log-service task/task_scheduler.go:129 ts.QueryTask {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "scheduler.queryTasks": 2, "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:11.39320107s farawayToDeadline:-1.393216525s"}
2023/05/10 11:15:51.916502 +0800 ERROR log-service task/task_scheduler.go:133 failed to query tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "ctxinfo": "from: scheduler, fromUuid: e05f826c-ee58-46ca-b728-251f6f4d6b00, Start: 2023-05-10 11:15:40.481541 +0800 CST m=+202.480833412 fromStart:11.434599542s farawayToDeadline:-1.43461503s", "status": "Created", "error": "context deadline exceeded"}

**Comment by daviszhen** [comment]
通过增加了超时时间。降低了出现频率。但是改不彻底。
主要是查询太慢了。

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
closed
