### ISSUE TITLE
[Bug]: dump bool type data with quotes mysql failed to insert

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8050]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e221e8a842e9010cfb5bbfd6b8f80f55ecb0a236
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo dump t.sql, bool type true/false with quotes 
![image](https://user-images.githubusercontent.com/113406637/219014536-842c93a0-8533-4d14-a96d-7531789321ab.png)

mysql insert values bool type with quotes failed ,It is recommended to have good compatibility with mysql：
![image](https://user-images.githubusercontent.com/113406637/218996111-fd7effc4-6b84-450e-a7df-e957c08f3fed.png)
![image](https://user-images.githubusercontent.com/113406637/218996215-7d044ecd-3da1-4665-80d2-6ca1a9b6986b.png)

**Comment by mooleetzi** [comment]
it's because our `bool` type is real bool, but in mysql `bool` is an alias of `tinyint`, the bool type cannot be recognized by   mysql driver, then field `type` may be empty string.  Thus I will use empty string to map bool type to fix it in #8046.

**Comment by mooleetzi** [comment]
done, pls retest @heni02

**Comment by heni02** [comment]
confim,closed
commit id:0.7.0 6d4bd173514990032372310f7b3d9d803781074a
![image](https://user-images.githubusercontent.com/113406637/220004595-2d675a26-763c-4c63-ad91-0a6f5fb16664.png)
mysql source sql file
![image](https://user-images.githubusercontent.com/113406637/220004626-4401c5f9-5856-4f6c-872b-2f122e6e1303.png)
