### ISSUE TITLE
[Bug]: rows of account in mo_catalog.tables are not clear after drop account 

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#8058]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):  bfcd3fbbfcff4d8ab0dfce43195c33a31d93d755
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> use mo_catalog;
Database changed
mysql> create account acc1 ADMIN_NAME 'root' IDENTIFIED BY '123456';
Query OK, 0 rows affected (0.33 sec)

mysql> select * from mo_account;
+------------+--------------+--------+---------------------+----------------+----------------+
| account_id | account_name | status | created_time        | comments       | suspended_time |
+------------+--------------+--------+---------------------+----------------+----------------+
|          0 | sys          | open   | 2023-02-16 06:14:53 | system account | NULL           |
|          1 | acc1         | open   | 2023-02-16 06:15:26 |                | NULL           |
+------------+--------------+--------+---------------------+----------------+----------------+
2 rows in set (0.01 sec)

mysql> drop account acc1;
Query OK, 0 rows affected (0.13 sec)

mysql> select * from mo_account;
+------------+--------------+--------+---------------------+----------------+----------------+
| account_id | account_name | status | created_time        | comments       | suspended_time |
+------------+--------------+--------+---------------------+----------------+----------------+
|          0 | sys          | open   | 2023-02-16 06:14:53 | system account | NULL           |
+------------+--------------+--------+---------------------+----------------+----------------+
1 row in set (0.01 sec)

mysql> select account_id,relname,relkind from mo_catalog.mo_tables where reldatabase = 'mo_catalog' order by relname;
+------------+----------------------------+---------+
| account_id | relname                    | relkind |
+------------+----------------------------+---------+
|          0 | %!%mo_increment_columns    | r       |
|          1 | %!%mo_increment_columns    | r       |
|          0 | mo_account                 | r       |
|          0 | mo_columns                 |         |
|          0 | mo_database                |         |
|          0 | mo_mysql_compatbility_mode | r       |
|          1 | mo_mysql_compatbility_mode | r       |
|          0 | mo_role                    | r       |
|          0 | mo_role_grant              | r       |
|          0 | mo_role_privs              | r       |
|          0 | mo_tables                  |         |
|          0 | mo_user                    | r       |
|          0 | mo_user_defined_function   | r       |
|          1 | mo_user_defined_function   | r       |
|          0 | mo_user_grant              | r       |
+------------+----------------------------+---------+
15 rows in set (0.00 sec)

**Comment by daviszhen** [comment]
@mooleetzi will take over the things related to the account.

**Comment by mooleetzi** [comment]
pr merged, pls verify @ouyuanning
