### ISSUE TITLE
[Feature Request]: support partition

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#8059]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

DN supports partition.

**Comment by triump2020** [comment]
According to [this desgin](https://github.com/matrixorigin/docs/blob/main/design/partition.md) ,  DN  now dose not need to change for this feature.

**Comment by triump2020** [comment]
Review of [this design](https://github.com/matrixorigin/docs/blob/main/design/partition.md) had been finished.
