### ISSUE TITLE
[Bug]: A problem with the results of show create table

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8066]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/219311209-8754fa74-cde2-46a5-a618-b81f4500e8e5.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/108530700/219311279-1387b194-a3ab-40b2-83cc-68c7576d7d0a.png)

### Steps to Reproduce

```Markdown
drop table if exists test01;
create database test01;
use test01;
create table tt(col2 float comment '"%$^&*()_+@!\'');
show create table tt;
```

**Comment by qingxinhome** [comment]
\' is an escape character of '. Two consecutive ' are used in the SQL string to represent one '
\' is equivalent to ''
therefore
create table tt(col2 float comment '"%$^&*()_+@!\'');
show create table tt;
The implementation result of is:
Table    Create Table
tt    CREATE TABLE `tt` (\n`col2` FLOAT DEFAULT NULL COMMENT '"%$^&*()_+@!'''\n)
Consistent with mysql.   @Ariznawlll
