### ISSUE TITLE
[Bug]: alter account MYSQL_COMPATBILITY_MODE sys execute error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8079]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6d4bd173514990032372310f7b3d9d803781074a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1.sys execute alter account reported error，It should be executable under sys
![image](https://user-images.githubusercontent.com/113406637/219997813-668b6e5a-3802-4772-a59d-97ed7d57085b.png)
2.Under a normal tenant, must create a db energy measurement alter account configuration，It should have no dependency on db
![image](https://user-images.githubusercontent.com/113406637/219997838-2befbacc-c4f7-4c7d-913a-99d2df272a5e.png)

### Steps to Reproduce
create account account_1 admin_name='admin' identified by '123456';
alter account config account_1  set MYSQL_COMPATBILITY_MODE = '{"version_compatibility": "MatrixOne-v0.7.0"}';
select version();

**Comment by YANGGMM** [comment]
have fixed some, but still have some actions to come true, may can be fixed in tomorrow.

**Comment by heni02** [comment]
commit id:5176c50884681936f63a967b373795f6592b12c3
sys account execute alter account reported Permission error @YANGGMM plz confirm whether it meets the requirements
<img width="1250" alt="企业微信截图_4e725b97-9c9e-44c1-83c7-bb61c87961d1" src="https://user-images.githubusercontent.com/113406637/222890425-76028c20-180d-4d63-afdb-0a5ba7e9afa5.png">

<img width="1227" alt="企业微信截图_b80e0db4-0f3b-4ce7-9184-b1ad53c1e9a4" src="https://user-images.githubusercontent.com/113406637/222891045-2ba62f9b-b79a-4143-a946-ad073397fd24.png">

**Comment by YANGGMM** [comment]
> commit id:5176c50884681936f63a967b373795f6592b12c3 sys account execute alter account reported Permission error @YANGGMM plz confirm whether it meets the requirements <img alt="企业微信截图_4e725b97-9c9e-44c1-83c7-bb61c87961d1" width="1250" src="https://user-images.githubusercontent.com/113406637/222890425-76028c20-180d-4d63-afdb-0a5ba7e9afa5.png">
> 
> <img alt="企业微信截图_b80e0db4-0f3b-4ce7-9184-b1ad53c1e9a4" width="1227" src="https://user-images.githubusercontent.com/113406637/222891045-2ba62f9b-b79a-4143-a946-ad073397fd24.png">

yes, I have talked with @domingozhang , only this account can alter it's config.

**Comment by heni02** [comment]
confirm,closed
