### ISSUE TITLE
[Bug]: performance: source sql file 5200w+ rows more than 1.5hours  

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8082]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6d4bd173514990032372310f7b3d9d803781074a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Preliminary analysis shows that the performance bottleneck lies in insert values
mo source sql：
![image](https://user-images.githubusercontent.com/113406637/220004320-101a2037-cb7f-427d-864a-2708c6981d5e.png)

mysql source sql, cost about 40min ：
![image](https://user-images.githubusercontent.com/113406637/220004253-1be21faf-c028-4b52-b906-5d572b6d3f81.png)

sql file:
insert value part data
![image](https://user-images.githubusercontent.com/113406637/222315631-0876530e-523c-421e-b149-b21fb8acd50d.png)

**Comment by jensenojs** [comment]
Now tracking #7748, please help with pprof @jianwan0214 to check if is insert operation problem.

**Comment by aressu1985** [comment]
@w-zr pls update this issue status

**Comment by w-zr** [comment]
does not have time to fix this issue in 0.8.

**Comment by w-zr** [comment]
now insertion is very slow.
Need optimizations on insertion.

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!
