### ISSUE TITLE
[Bug]: The real value shown by show function status does not match the expected value

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8086]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```
commit：6d4bd173514990032372310f7b3d9d803781074a
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/220026385-726fe807-1441-4069-a7a5-007fa6636b4f.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/108530700/220026464-a286c705-6983-4fc4-bb5d-76a6e7606a03.png)

### Steps to Reproduce

```Markdown
-- SHOW FUNCTION STATUS [like_or_where]
DROP DATABASE IF EXISTS show_03;
CREATE DATABASE show_03;
USE show_03;
create function hihi() returns int language sql as 'select id from test_table limit 1';

show FUNCTION status;
show FUNCTION status LIKE 'hihi';

DROP DATABASE show_03;
```

**Comment by YANGGMM** [comment]
This is due to the different time of each function generation, which causes the bvt test sample to fail @Ariznawlll
