### ISSUE TITLE
[Bug]: dn crash when one of logservice has been restart

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8110]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-4947c1a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For distributed topo, if one of logservice pod was crashed and restarted, the dn pod will be crashed. The reason is that the dn  still connect to the logservice which is crashed, and it cause dn connect timeout and panic.

the dn error message:
{"level":"INFO","time":"2023/02/21 16:32:10.160690 +0000","caller":"logservice/hakeeper_client.go:382","msg":"isHAKeeper: true, err: <nil>"}
{"level":"ERROR","time":"2023/02/21 16:32:10.162085 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:674","msg":"init remote connection failed, retry later","remote":"nightly-regression-dis-log-2.nightly-regression-dis-log-headless.mo-nightly-regression.svc:32001","backend-id":"e8c61485-fa56-495e-afc4-3b1118472ee4","error":"dial tcp4: lookup nightly-regression-dis-log-2.nightly-regression-dis-log-headless.mo-nightly-regression.svc on 172.20.0.10:53: no such host"}
{"level":"ERROR","time":"2023/02/21 16:32:11.165644 +0000","caller":"morpc/backend.go:682","msg":"error: backend closed","stacktrace":"github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).resetConn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:682\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.NewRemoteBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:202\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*goettyBasedBackendFactory).Create\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:770\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).doCreate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:456\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).createBackendLocked\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:444\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).maybeInitBackends\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:159\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.NewClient\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:116\ngithub.com/matrixorigin/matrixone/pkg/logservice.getRPCClient\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/client.go:554\ngithub.com/matrixorigin/matrixone/pkg/logservice.connectToLogService\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/client.go:317\ngithub.com/matrixorigin/matrixone/pkg/logservice.newClient\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/client.go:257\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*managedClient).prepareClient\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/client.go:240\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*managedClient).Append\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/client.go:131\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:67\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.RetryWithTimeout\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go:40\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:65"}
{"level":"ERROR","time":"2023/02/21 16:32:11.165696 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:203","msg":"connect to remote failed","remote":"nightly-regression-dis-log-2.nightly-regression-dis-log-headless.mo-nightly-regression.svc:32001","backend-id":"e8c61485-fa56-495e-afc4-3b1118472ee4","error":"backend closed"}
{"level":"ERROR","time":"2023/02/21 16:32:11.165706 +0000","name":"rpc-client[hakeeper-client([])]","caller":"morpc/client.go:458","msg":"create backend failed","backend":"nightly-regression-dis-log-2.nightly-regression-dis-log-headless.mo-nightly-regression.svc:32001","error":"backend closed"}
{"level":"ERROR","time":"2023/02/21 16:32:11.165717 +0000","caller":"logservicedriver/appender.go:70","msg":"append failed: backend closed","stacktrace":"github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:70\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.RetryWithTimeout\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go:40\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:65"}
{"level":"INFO","time":"2023/02/21 16:32:11.165733 +0000","caller":"logservicedriver/appender.go:77","msg":"size is 2704"}
{"level":"WARN","time":"2023/02/21 16:32:11.165741 +0000","caller":"logservicedriver/appender.go:100","msg":"append to logservice took 3m14.682653306s"}
panic: internal error: driver info: retry time out

goroutine 50182 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append(0xc0145c2d00, 0x95dba6?, 0x2540be400)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:78 +0x677
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*LogServiceDriver).onAppendQueue
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go:66 +0xf2
sudong@sudongdeMacBook-Pro mo-cloud % kubectl -n mo-nightly-regression get pod
No resources found in mo-nightly-regression namespace.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/47846308/220528173-a7dc6867-3fa3-4895-b444-aa5cf469a2f0.png">

[load_dealine.log](https://github.com/matrixorigin/matrixone/files/10800253/load_dealine.log)

**Comment by aressu1985** [comment]
It may be the same as #7573

**Comment by volgariver6** [comment]
There are many logs showing the DNS may not work well:

```
load_dealine.log:2408:{"level":"ERROR","time":"2023/02/21 16:32:02.961501 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:674","msg":"init remote connection failed, retry later","remote":"nightly-regression-dis-log-1.nightly-regression-dis-log-headless.mo-nightly-regression.svc:32001","backend-id":"0389db59-de88-401a-8d95-9a489a1eddce","error":"dial tcp4: lookup nightly-regression-dis-log-1.nightly-regression-dis-log-headless.mo-nightly-regression.svc on 172.20.0.10:53: no such host"}
load_dealine.log:2416:{"level":"ERROR","time":"2023/02/21 16:32:03.745094 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:674","msg":"init remote connection failed, retry later","remote":"nightly-regression-dis-log-2.nightly-regression-dis-log-headless.mo-nightly-regression.svc:32001","backend-id":"3a575501-6cd5-42a8-9395-a4e855a7f457","error":"dial tcp4: lookup nightly-regression-dis-log-2.nightly-regression-dis-log-headless.mo-nightly-regression.svc on 172.20.0.10:53: no such host"}
```

DN service cannot access log-1 and log-2 through DNS service.

**Comment by volgariver6** [comment]
@aylei will help check the DNS problem.

**Comment by volgariver6** [comment]
still working on it.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
will handle it later.

**Comment by volgariver6** [comment]
as discussed, ressign back to @aressu1985

**Comment by aressu1985** [comment]
fixed
