### ISSUE TITLE
[Feature Request]: Parser enhancement for cloud

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8113]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. SQL statements are saved as parsed statements through SQL Parser

Users need a second option to get original statements.

2. The access key of s3 option needs to be marked as other string such as random string.
![image](https://user-images.githubusercontent.com/88298673/220867514-ded2e990-1d15-4a66-8167-f5d49745cf4b.png)

**Comment by DanielZhangQD** [comment]
Please also help fix https://github.com/matrixorigin/matrixone/issues/8121

**Comment by DanielZhangQD** [comment]
To be fixed by end of 3.16

**Comment by daviszhen** [comment]
应该做了。

**Comment by Ariznawlll** [comment]
test done!
