### ISSUE TITLE
[Bug]: mo crash by [fatal error: found bad pointer in Go heap] when loading ssb 100G line_order table

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8125]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e694f8427663fbc5043674645f99b3ce8bcb937e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when loading ssb 100g lineorder table, about 3 min later ,the mo crash by folling error:

2023/02/23 00:13:42.429637 +0800 INFO frontend/util.go:418 time of Exec.Run : 753.261µs connectionId 1065
2023/02/23 00:13:42.429736 +0800 INFO frontend/util.go:403 query trace status {"connection_id": 1065, "statement": "select cron_task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, cron_expr, next_time, trigger_times, create_at, update_at from mo_task.sys_cron_task", "status": "success", "span": {"trace_id": "dffb1e14-b2cb-11ed-801f-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1065"}
2023/02/23 00:13:42.429903 +0800 INFO log-service taskservice/task_service_cron.go:108 new cron tasks fetched {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "current-count": 7, "fetch-count": 7}
runtime: pointer 0xc200001eb5 to unallocated span span.base()=0xc1fffda000 span.limit=0xc200010010 span.state=0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw({0x28ed39d?, 0x425e4f0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f49bdffad68 sp=0x7f49bdffad38 pc=0x448e5d
runtime.badPointer(0x7f4a3c4a0f78, 0xc14b332000?, 0x0, 0x2000?)
        /usr/local/go/src/runtime/mbitmap.go:373 +0x150 fp=0x7f49bdffadb8 sp=0x7f49bdffad68 pc=0x425710
runtime.findObject(0xc0000daf00?, 0xc0000dc178?, 0x439125?)
        /usr/local/go/src/runtime/mbitmap.go:416 +0xa6 fp=0x7f49bdffadf0 sp=0x7f49bdffadb8 pc=0x4258a6
runtime.wbBufFlush1(0xc0000daf00)
        /usr/local/go/src/runtime/mwbbuf.go:260 +0xe5 fp=0x7f49bdffae38 sp=0x7f49bdffadf0 pc=0x443e05
runtime.wbBufFlush.func1()
        /usr/local/go/src/runtime/mwbbuf.go:201 +0x25 fp=0x7f49bdffae50 sp=0x7f49bdffae38 pc=0x443c45
runtime.systemstack()
"mo-ssb.log" 97940L, 11071259C

[mo-bad-pointer.tar.gz](https://github.com/matrixorigin/matrixone/files/10809882/mo-bad-pointer.tar.gz)

**Comment by w-zr** [comment]
[mo-bad-pointer.tar.gz](https://github.com/matrixorigin/matrixone/files/10809882/mo-bad-pointer.tar.gz) is broken.

**Comment by w-zr** [comment]
What's the go version? How to repro?

**Comment by aressu1985** [comment]
[Uploading mo-bad-pointer.2.tar.gz…]()

**Comment by aressu1985** [comment]
at 2.24 , tpcc test in nigthly regression triggered this problme too.
error log is :
023/02/24 03:26:12.103146 +0800 INFO frontend/util.go:418 time of Exec.Run : 12.736468ms connectionId 1117
2023/02/24 03:26:12.103192 +0800 INFO frontend/util.go:418 time of SendResponse 619ns connectionId 1117
2023/02/24 03:26:12.103318 +0800 INFO frontend/util.go:403 query trace status {"connection_id": 1117, "statement": "execute __mo_stmt_id_28 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3", "status": "success", "span": {"trace_id": "ee875a41-b3af-11ed-aea8-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1117"}
2023/02/24 03:26:12.103535 +0800 INFO frontend/util.go:403 query trace {"connection_id": 1117, "query": "execute __mo_stmt_id_27 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2", "vars": "6 , 2 , 2125", "session_info": "connectionId 1117"}
2023/02/24 03:26:12.103822 +0800 INFO frontend/session.go:350 session uuid: c9d4bdf0-b3ae-11ed-aea8-b07b25f8b524 -> background session uuid: ee8a3911-b3af-11ed-aea8-b07b25f8b524
2023/02/24 03:26:12.103879 +0800 INFO rpc/handle.go:844 [precommit] handle write end txn: ctx[F777CF1604F3462FA15D71681E1FBD14][1677180370531459424-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

2023/02/24 03:26:12.103936 +0800 INFO rpc/handle.go:837 [precommit] handle write typ: 0, 272469-bmsql_new_order, 272462-tpcc_10
 txn: ctx[F777CF1604F3462FA15D71681E1FBD14][1677180370531459424-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

2023/02/24 03:26:12.104511 +0800 INFO rpc/handle.go:844 [precommit] handle write end txn: ctx[F777CF1604F3462FA15D71681E1FBD14][1677180370531459424-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

2023/02/24 03:26:12.104564 +0800 INFO rpc/handle.go:837 [precommit] handle write typ: 1, 272472-bmsql_stock, 272462-tpcc_10
 txn: ctx[F777CF1604F3462FA15D71681E1FBD14][1677180370531459424-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

2023/02/24 03:26:12.104624 +0800 INFO rpc/handle.go:844 [precommit] handle write end txn: ctx[F777CF1604F3462FA15D71681E1FBD14][1677180370531459424-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

2023/02/24 03:26:12.104648 +0800 INFO rpc/handle.go:837 [precommit] handle write typ: 0, 272472-bmsql_stock, 272462-tpcc_10
 txn: ctx[F777CF1604F3462FA15D71681E1FBD14][1677180370531459424-0->9223372036854775807-4294967295->9223372036854775807-4294967295][Active]: <nil>

runtime: pointer 0xc628296a00 to unused region of span span.base()=0xc1602e6000 span.limit=0xc1602e7f40 span.state=1
runtime: found in object at *(0xc00acb8a20+0x0)
object=0xc00acb8a20 s.base()=0xc00acb8000 s.limit=0xc00acba000 s.spanclass=4 s.elemsize=16 s.state=mSpanInUse
 *(object+0) = 0xc628296a00 <==
 *(object+8) = 0x73
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw({0x29096e0?, 0x6?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f276bffec80 sp=0x7f276bffec50 pc=0x448e5d
runtime.badPointer(0x7f257d4dac58, 0x0?, 0xc00acb8a20, 0xc4280?)
        /usr/local/go/src/runtime/mbitmap.go:373 +0x150 fp=0x7f276bffecd0 sp=0x7f276bffec80 pc=0x425710
runtime.findObject(0xc14e01b420?, 0x56?, 0x7f281cb00000?)
        /usr/local/go/src/runtime/mbitmap.go:416 +0xa6 fp=0x7f276bffed08 sp=0x7f276bffecd0 pc=0x4258a6
runtime.scanobject(0x19dc6e9?, 0xc000093c40)
        /usr/local/go/src/runtime/mgcmark.go:1338 +0x190 fp=0x7f276bffeda0 sp=0x7f276bffed08 pc=0x431430
runtime.gcDrain(0xc000093c40, 0x3)
        /usr/local/go/src/runtime/mgcmark.go:1103 +0x1d4 fp=0x7f276bffee00 sp=0x7f276bffeda0 pc=0x430c74
runtime.gcBgMarkWorker.func2()

the origin log is in dir /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/upload/2023.2.24/mo-tpcc.log on mo-srv-128 server

**Comment by w-zr** [comment]
According to [https://go.dev/src/runtime/mbitmap.go#L289](https://go.dev/src/runtime/mbitmap.go#L289), bad pointer indicates an incorrect use of unsafe or cgo.

This panic is throwed when GC finds a bad pointer.
To suppress this panic temporarily, change `GODEBUG` env variable and set `invalidptr=0`(see [https://pkg.go.dev/runtime](https://pkg.go.dev/runtime)). Run mo-server like `env GODEBUG=invalidptr=0 ./mo-service ...`

```
invalidptr: invalidptr=1 (the default) causes the garbage collector and stack
copier to crash the program if an invalid pointer value (for example, 1)
is found in a pointer-typed location. Setting invalidptr=0 disables this check.
This should only be used as a temporary workaround to diagnose buggy code.
The real fix is to not store integers in pointer-typed locations.
```

@aptend found that this issue is caused by incorrect use of mpool.
@nnsgmsone said he will work on this issue when he *空了*.

**Comment by w-zr** [comment]
Run with `-race` may report more info.

**Comment by aressu1985** [comment]
In regression test on 3.1，this bug did not happen. Downgrade the level to s1 and track it for more days

**Comment by aressu1985** [comment]
In regression test on 3.2，this bug did not happen, still tracking for a more day

**Comment by aressu1985** [comment]
In regression test on 3.2，this bug did not happen, closed
