### ISSUE TITLE
[Bug]: performance：eks bvt case test execute time about 25min+ 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8126]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2ffc978faddb81ce942e669e1d4043f368236761
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The previous eks bvtcase run time  about 10min, but now the log is not available. The comparison with the run time of muti cn in ci bvt case is as follows，I found that almost all cases have slowed down
![image](https://user-images.githubusercontent.com/113406637/220812573-a644bc46-aea9-4be4-8157-e76f483e99d4.png)
![image](https://user-images.githubusercontent.com/113406637/220812443-eb854def-0116-4785-9eef-d7f175bfc2b3.png)
eks job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4242521172/jobs/7374498569
The complete report time consuming log is on the issue
eks mo log:s3://heni-test/mo-data1/etl_20230109050735/

**Comment by heni02** [comment]
[report_cibvtcase.txt](https://github.com/matrixorigin/matrixone/files/10809916/report_cibvtcase.txt)
[report_eksbvt.txt](https://github.com/matrixorigin/matrixone/files/10809920/report_eksbvt.txt)

**Comment by daviszhen** [comment]
I am not working on it

**Comment by daviszhen** [comment]
I am not working on it

**Comment by heni02** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4901971749/jobs/8758209124
now execution time is around 15 minutes，closed
