### ISSUE TITLE
[Bug]: dn may crash by oom after loading lots of big data table 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-e694f84
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when runing load data test on eks, sometimes after loading lots of big data tables , the dn pod will be killed by oom .

[Wed Feb 22 23:34:21 2023] Tasks state (memory values in pages):
[Wed Feb 22 23:34:21 2023] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[Wed Feb 22 23:34:21 2023] [   5404] 65535  5404      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:21 2023] [   6541]     0  6541     2889      677    65536        0          -997 bash
[Wed Feb 22 23:34:21 2023] [   6631]     0  6631   191546    16123   249856        0          -997 aws-k8s-agent
[Wed Feb 22 23:34:21 2023] [   6632]     0  6632     1059      194    53248        0          -997 tee
[Wed Feb 22 23:34:21 2023] [   5485] 65535  5485      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:21 2023] [   6536]     0  6536   188897    13003   229376        0           999 kruise-daemon
[Wed Feb 22 23:34:21 2023] [   5554] 65535  5554      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:21 2023] [   5913]     0  5913   187503    11867   212992        0          -998 kube-proxy
[Wed Feb 22 23:34:21 2023] [   7708]     0  7708   187503    11867   212992        0          -998 kube-proxy
[Wed Feb 22 23:34:22 2023] [   6912]     0  6912      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:22 2023] [   7203]     0  7203   190983     9134   204800        0          -997 aws-ebs-csi-dri
[Wed Feb 22 23:34:22 2023] [   7481]     0  7481   181553     3573   131072        0          -997 csi-node-driver
[Wed Feb 22 23:34:22 2023] [   7629]     0  7629   178889     4100   118784        0          -997 livenessprobe
[Wed Feb 22 23:34:22 2023] [   8281] 65535  8281      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:22 2023] [   5400] 65534  5400      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:22 2023] [   5908] 65534  5908   180112     5090   159744        0          1000 node_exporter
[Wed Feb 22 23:34:22 2023] [   7228] 65535  7228      242        1    28672        0          -998 pause
[Wed Feb 22 23:34:22 2023] [   7953]     0  7953    91904     8427   196608        0          1000 fluent-bit
[Wed Feb 22 23:34:22 2023] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=418a6047e8bd3e706fedc09820e01d689ce9b397c7eddd60f041b086e089f30d,mems_allowed=0,oom_memcg=/kubepods,task_memcg=/kubepods/besteffort/pod28654d06-2032-408a-90db-8515f436da3d/0ebcddbb33cdb2e6775a2ad58b2aca847230456a2691ab8468d383fb96b299cb,task=fluent-bit,pid=7953,uid=0
[Wed Feb 22 23:34:22 2023] Memory cgroup out of memory: Killed process 7953 (fluent-bit) total-vm:367616kB, anon-rss:18648kB, file-rss:15060kB, shmem-rss:0kB, UID:0 pgtables:192kB oom_score_adj:1000

**Comment by aressu1985** [comment]
[mo-bad-pointer.tar.gz](https://github.com/matrixorigin/matrixone/files/10813127/mo-bad-pointer.tar.gz)

**Comment by aptend** [comment]
pr has been merged

**Comment by aptend** [comment]
@aressu1985 please check

**Comment by aressu1985** [comment]
will test at weekend

**Comment by aressu1985** [comment]
The DN still may crash by OOM，and this issue now is transfered to @triump2020 to deal with

**Comment by triump2020** [comment]
Cause : when DN  do primary key deduplication check ,  it would load all the primary keys of table into memory, resulting in OOM.

**Comment by triump2020** [comment]
I will add a mo_ctl to close the PK-unique check against txn's workspace when S3 loading. @aressu1985

**Comment by aressu1985** [comment]
fxied
