### ISSUE TITLE
[Bug]: `stats` field is missed for `load data` sql

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#8129]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-f9c20413
- Hardware parameters:
- OS type: ubuntu
- Others:
```

### Actual Behavior

- Load data
- Check the `stats` field in the `statement_info` table and no value is set

### Expected Behavior

`stats` field is set

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

**Comment by xzxiong** [comment]
as case run in bvt, `exec_plan` has error while call `serializePlanToJson`. @jianwan0214 
![image](https://user-images.githubusercontent.com/3927687/221469582-c4684416-6325-4892-9a30-cf4e697e07d0.png)

**Comment by DanielZhangQD** [comment]
Verified and passed with commit 845d784c7fa143fa8ac39eb5b1ded16ab96b2218
