### ISSUE TITLE
DISTINCT doesn't work in COUNT()

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#815]
#### Can be reproduced ?
Yes

#### Steps:

CREATE TABLE t2(product VARCHAR(32),country_id INTEGER NOT NULL,year INTEGER,profit INTEGER);
INSERT INTO t2 VALUES ( 'Computer', 2,2000, 1200),
( 'TV', 1, 1999, 150),
( 'Calculator', 1, 1999,50),
( 'Computer', 1, 1999,1500),
( 'Computer', 1, 2000,1500),
( 'TV', 1, 2000, 150),
( 'TV', 2, 2000, 100),
( 'TV', 2, 2000, 100),
( 'Calculator', 1, 2000,75),
( 'Calculator', 2, 2000,75),
( 'TV', 1, 1999, 100),
( 'Computer', 1, 1999,1200),
( 'Computer', 2, 2000,1500),
( 'Calculator', 2, 2000,75),
( 'Phone', 3, 2003,10);

SELECT product, country_id, COUNT(*), COUNT(distinct year) FROM t2 GROUP BY product, country_id order by product;
![image](https://user-images.githubusercontent.com/88298673/134450503-38d56f1d-35b0-4024-accb-e6671c447b90.png)

In MySQL the result is

![image](https://user-images.githubusercontent.com/88298673/134450465-aa94d263-8400-4de9-948f-4ebd1e463e4d.png)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3835f50655d37f4174b9bc4ef0d4a871a06f63e4
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by tianyahui-python** [comment]
commit id: 9a457bc5e8f956377739d67f9703828bd8b7e4f4

<img width="1061" alt="截屏2022-10-29 15 43 41" src="https://user-images.githubusercontent.com/39303074/198820140-e31002f4-b946-4cb8-855c-9d1b1164192f.png">

**Comment by tianyahui-python** [comment]
@domingozhang authenticated, can close issue.
