### ISSUE TITLE
[Bug]: view doesn't exist

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#8161]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): f0dba50a47ee63543120b0514f5466e8684723e2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="790" alt="image" src="https://user-images.githubusercontent.com/4965857/221515826-ed885cd1-d023-49a9-a241-9dd3c7dc5d6d.png">

connect to MatrixOne by navicat, and click on the views, it actually executes this sql

```
select table_name, check_option, is_updatable, security_type, definer from information_schema.views where table_schema = \"abc\" order by table_name asc;
```

it will get an error of "table \"views\" does not exist"

**Comment by qingxinhome** [comment]
The 'views' system view has been added into 'information_schema' . It can be used in the initial test on navicat. Please test

**Comment by qingxinhome** [comment]
![image](https://user-images.githubusercontent.com/70939751/222620384-6b85c21d-81d7-406b-885e-b474f03577c3.png)

**Comment by dengn** [comment]
Fixed. 

<img width="389" alt="image" src="https://user-images.githubusercontent.com/4965857/226240752-63cbad66-13a7-4343-aa29-8510f04c6e38.png">
