### ISSUE TITLE
[Enhancement]: Kill all connected session when account suspended

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8167]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Currently, user can till run sql with the connection to suspended account. 
Theses session need be killed when target account suspended.
```

**Comment by daviszhen** [comment]
may be solved in 0.8

**Comment by volgariver6** [comment]
done with #9338.

**Comment by florashi181** [comment]
@tianyahui-python how is this issue going ?

**Comment by tianyahui-python** [comment]
> @tianyahui-python how is this issue going ?

This feature is only partially implemented, this function takes effect only with a single proxy

**Comment by tianyahui-python** [comment]
test done
