### ISSUE TITLE
explain does not work

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#817]
#### Can be reproduced ?
Yes

#### Steps:
mysql> explain select username, first_name from user1;
+---------------------------------------------------------------------------------------------------------------------+
| Pipeline                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------+
| user1 -> π([username -> username, first_name -> first_name] -> π([username -> username, first_name -> first_name]   |
+---------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

#### Expected behavior:
According to v0.1.0 test scope, explain should works well.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3835f50655d37f4174b9bc4ef0d4a871a06f63e4
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by yingfeng** [comment]
duplicate with #2363
