### ISSUE TITLE
[Tech Request]: stats collector, periodical stats

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8172]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Some of the log/trace/span are in the perf critical path. 
For example, io read has a span.  Usually this is too expensive.
The span in io read can account for 30% of run time.
```

### Describe the feature you'd like

We need to remove trace/span in tight loops.  However
these are important stats.   We still gather these stats
but in the tight loop, we should just update a few counters.
In case of io cache, we probably update a count of I/O, size
and hit/miss count. 

Create a background service (one per node) that gather these
stats and generate a log/trace.  Each module that wants to 
generate periodical stats should register a call back.  For
example, for io cache, a call back to report a few metrics
metioned above.

**Comment by gavinyue** [comment]
Will implement this in streaming project

**Comment by gavinyue** [comment]
Corresponding project board:  https://github.com/orgs/matrixorigin/projects/17

**Comment by gavinyue** [comment]
Still pending not started
