### ISSUE TITLE
[Enhancement]: Better LRU

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8173]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Current LRU holds a global lock which could be a perf bottleneck.
```

### Why is this needed ?

Better algorithm that does not use a global lock.  Or, an approximation of LRU such as clock.

Maybe it is better to have a general cache replacement framework/template and let user plugin/experiment
with different algorithm and config.

**Comment by arjunsk** [comment]
Moving it to the backlog.

**Comment by nnsgmsone** [comment]
fixed by https://github.com/matrixorigin/matrixone/pull/13509

**Comment by nnsgmsone** [comment]
在这个pr合入后，sysbench点查1000w的性能提升了三四倍左右，有一些改善
