### ISSUE TITLE
Not support multi-table query

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#818]
#### Can be reproduced ?
Yes

#### Steps:
mysql> select username, first_name from user2, user1 where user2.id=user1.id;
ERROR 1105 (HY000): unknown error:[42000]unknown column 'id' in expr

#### Actual behavior:
Not support multi-table query in v0.1.0

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3835f50655d37f4174b9bc4ef0d4a871a06f63e4
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by daviszhen** [comment]
it was supported now.
