### ISSUE TITLE
[Bug]: MO does not recognize some words dumped by mysql

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#8182]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): e694f8427663fbc5043674645f99b3ce8bcb937e
- Hardware parameters: 8c 32g
- OS type: CentOS Linux release 8.3.2011, core: 4.18.0-348.7.1.el8_5.x86_64
- Others:
```

### Actual Behavior

MO does not recognize some words dumped by mysql, including:

1. `/* */ `（but `-- /* */` is ok) 
2. `ENGINE=xxx` (InnoDB, MyISAM, ...)
3. `DEFAULT CHARSET=xxx` (latin1, utf8, ...)
4. `CHARACTER SET xxx` (utf8, ...)
5. `USING xxx` (BTREE, HASH, ...)
6. `UNLOCK TABLES` and `LOCK TABLES`
7. `AUTO_INCREMENT=xxx`
8. `ROW_FORMAT=xxx` (COMPACT)
9. `SET @saved_cs_client = xxx`
10. `SET character_set_client  = xxx`

For example, 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/46433151/221771528-b2f65436-ec60-4593-a89d-f6022572bc38.png">

<img width="879" alt="image" src="https://user-images.githubusercontent.com/46433151/221774167-dcce2034-9a3c-4988-9a87-3517a8cde180.png">

### Expected Behavior

Can MO support these words? At lease comments should be supported

### Steps to Reproduce

```Markdown
1. prepare some ddl, for example, `test.sql`

/*!40101 -- SET @saved_cs_client     = @@character_set_client */;
/*!40101 -- SET character_set_client = utf8 */;

use test;

create table if not exists aron_test(id int, name varchar(255));
insert into aron_test values(1, 'aron'), (2, 'cindy');
```
2、load it into MO:
```
mysql -udump -p111 -h127.0.0.1 -P6001 < /path_to_file/test.sql
```
The error will be like this:

or
```
mysql -udump -p111 -h127.0.0.1 -P6001
source  /path_to_file/test.sql
```
```


### Additional information

none

**Comment by daviszhen** [comment]
@jianwan0214 will cover the compatibility of the mysql dump.

**Comment by aronchanisme** [comment]
Tested and all the above mentioned issues are gone now.
https://github.com/matrixorigin/matrixone/issues/4374#issuecomment-1680245688
