### ISSUE TITLE
[Feature Request]: event collector and log processing 

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#8196]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Use stream enging to refactor system tables in database `system_metrics` and `system`.
need to fix those problem:
1. improve query performance on table `system_metrics.meric`,  `system.statement_info`, `system.log_info`, `system.error_info` and `system.log_info`
2. treat multi update on table statement_info with same id(statement_id) as single one record or one event.
3. use windows function, or  time series feature to rewrite some metric collection logic. 

### Tasks

- [ ] Create subtasks

### Describe implementation you've considered

Here is the doc: https://doc.weixin.qq.com/doc/w3_AW0A-gb6AOInM1rKTLdS1G7q1Q6vl?scode=AJsA6gc3AA8Q0nH1P2AS0AvwapAOk

**Comment by dengn** [comment]
what's the reason for this refactor? is it for performance improvement? how much will it improve?

**Comment by DanielZhangQD** [comment]
@gavinyue 
This improvement covers all the tables in the `system` and `system_metrics`, right?

**Comment by gavinyue** [comment]
Tracked in sub tasks

**Comment by gavinyue** [comment]
Under working.
