### ISSUE TITLE
[Subtask]: check if we can do some improve in logutil

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#8206]
### Parent Issue

#5530

### Detail of Subtask

check if we can do some improve in logutil

**Comment by xzxiong** [comment]
record repro and trace step:

1. start mo-service with `-debug-http :6060`

2. access mo-service and exec：
```
select mo_ctl('cn', 'task', 'disable');
create database db1;
use db1;
create table t1(a int, b int);
```

3. run java program in `issue #5530`

4. do trace
`curl -o trace.out http://localhost:6060/debug/pprof/trace?seconds=50`

5. checkk trace info: `go tool trace trace.out`

**Comment by xzxiong** [comment]
dup as https://github.com/matrixorigin/matrixone/issues/7569
