### ISSUE TITLE
[Subtask]: improve performance of determineUserHasPrivilegeSet

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#8207]
### Parent Issue

#5530

### Detail of Subtask

improve performance of determineUserHasPrivilegeSet.
maybe add session cache to cache the privs.

**Comment by daviszhen** [comment]
在pr增加了cache。 https://github.com/matrixorigin/matrixone/pull/10151

pr的结果:
https://user-images.githubusercontent.com/60595215/247044368-6b2de1cf-982c-431b-b324-e0c4b35d9f8b.png

之前的结果:
https://user-images.githubusercontent.com/60595215/247044419-9b68c6e6-0497-4f21-8127-f44f0b4836ce.png
