### ISSUE TITLE
[Bug]: zonemap data finalization

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8216]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Zonemap metadata needs to be finalized, esp, 

1. at least the following info, rowcount, nullcount, min, max, ndv, rawsize, compression size.
2. per block zonemap data and per s3 object zonemap data (maybe per segment zonemap data)

Required for 0.8 plan of storage format fix.

**Comment by XuPeng-SH** [comment]
done
