### ISSUE TITLE
[Bug]: metadata does not need to be completely in logtail: DN side

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8217]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For any table, once open DN need to maintain log tail in an in mem data structure.    All it needs i

1. most recent checkpoint.
2. changes since checkpoint, both meta data and user data.   

only the TAIL must be in mem.   access to already checkpointed data should go through a cache, not the in mem index.

**Comment by XuPeng-SH** [comment]
The current metadata is already checkpoint + tail in memory. No changes are needed.
