### ISSUE TITLE
[Bug]: checkpointed metadata does not need to be in log tail: CN part

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8218]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When CN pull or subscribe, DN will ship a checkpioin + logtail.   For those already checkpointed metadata, it does not need to be added into in mem index.   Esp, adding to in mem index is in transaction  critical path.

Esp, if a checkpoint record in log tail, should tell CN index that some metadata entry can be released from in mem index.

Reading already checkpointed metadata should go through cache, not index.

### Additional information

See https://github.com/matrixorigin/matrixone/issues/8217

**Comment by reusee** [comment]
I guess we're already doing this. Handling a metadata logtail entry is just adding one row to the tree, and the corresponding rows will be deleted from the rows cache.
https://github.com/matrixorigin/matrixone/blob/845d784c7fa143fa8ac39eb5b1ded16ab96b2218/pkg/vm/engine/disttae/partition_state.go#L295
https://github.com/matrixorigin/matrixone/blob/845d784c7fa143fa8ac39eb5b1ded16ab96b2218/pkg/vm/engine/disttae/partition_state.go#L341

**Comment by reusee** [comment]
And we're caching the metadata

**Comment by reusee** [comment]
There may be a gap between a checkpoint and sent logtails. In this situation, what we can do is just drop the whole cache and rebuild from start.

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
本周无进展

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
This depends on reading checkpoint data, but we don't have that codes yet. We need to read the checkpoint data and replay it before reading. 
Another problem, a checkpoint may skip some middle states, and CN has to drop all cached data and replay from that checkpoint, instead of dropping some.

**Comment by reusee** [comment]
wait for implementation of reading from checkpoint.

**Comment by reusee** [comment]
wait for implementation of reading from checkpoint.

**Comment by reusee** [comment]
Since https://github.com/matrixorigin/matrixone/issues/8217 is closed, and discussed with teammates, we concluded that this is not required for now.

**Comment by reusee** [comment]
re-assigning to @fengttt to close
