### ISSUE TITLE
[Bug]: create table is not in the same order as desc table.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#8223]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="982" alt="WechatIMG68" src="https://user-images.githubusercontent.com/39303074/222354530-781a2ac0-9f87-421c-81ae-6dfdeb3f8624.png">

**Comment by xzxiong** [comment]
@tianyahui-python what is the commit id ? could you repro ?

**Comment by tianyahui-python** [comment]
commit id : b0e162b3103ed1320c11205235c53f987e590c64

**Comment by YANGGMM** [comment]
it was caused by https://github.com/matrixorigin/matrixone/pull/8153
