### ISSUE TITLE
[Enhancement]: Adjust the semantic and error message about decimal with incorrect precision

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8231]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
In current version of MO, casted decimal with incorrect precision is still printed as result, for example:
```

![企业微信截图_16777452444472](https://user-images.githubusercontent.com/88298673/222377582-29b86caa-38ce-4035-8d9b-5d013e8bb503.png)

Howerver, 11.12 is out of decimal(3,2). Need an error message "Out of range value for column 'xxx'"

**Comment by badboynt1** [comment]
zengyan will fix this issue

**Comment by zengyan1** [comment]
fixed

**Comment by Ariznawlll** [comment]
Verified, no problem
