### ISSUE TITLE
INSERT with operator is failed

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#825]
#### Can be reproduced ?
Yes

#### Steps:
create table t1(a int,b int,c int);
insert into t1 values(12,100+10/2,100*10/20);
ERROR 1105 (HY000): unknown error:[42000]'' is not support now

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):  3835f50655d37f4174b9bc4ef0d4a871a06f63e4
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by m-schen** [comment]
1. Support + - * / div mod for numeric types (int family, uint family, float family) in insert. Not Support for char and varchar.
For example:
`insert into tbl values (4 / 2);` is support
`insert into tbl values ('abc' + '123');` does not support.

2. Support insert float value into int or uint column. And .4 is ignored, .5 is accepted.
For example:
`insert into tbl values (1.501), (2.4);` is same to `insert into tbl values (2), (2);`
`insert into tbl values (-1.6);` is same to `insert into tbl values (-2);`
