### ISSUE TITLE
Unable to support data type DATE and DATETIME

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#827]
#### Can be reproduced ?
Yes

#### Steps:
CREATE TABLE t_date (d DATE, dt DATETIME(6));

#### Expected behavior:
According to the test scope of 0.1.0, data type DATE and DATETIME should be supported.
Expect that the ddl can run successfully, and the table can be created. 

#### Actual behavior:
mysql> CREATE TABLE t_date (d DATE, dt DATETIME(6));
ERROR 1105 (HY000): unknown error:[42P18]unsupport type: '&{{4 0 0 0 false false 0x6cf2f30 [] [] 10 <nil> false <nil> <nil> <nil>}}'

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 3835f50655d37f4174b9bc4ef0d4a871a06f63e4 
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by m-schen** [comment]
support create and insert for Type Date
And these constant value can be insert :
1. STRING
`yyyy-mm-dd`, `yy-mm-dd`, `yyyymmdd`, `yymmdd` 
2. INT
yyyymmdd, yymmdd

**Comment by m-schen** [comment]
Support create and insert for Type Datetime
And these constant value can be insert:

1. All Date type, and hour / minute / second for date time will be 0
2. STRING
`yyyy-mm-dd hh:mm:ss.nnnnn`
3. FLOAT
`yyyymmddhhmmss.nnnn`

**Comment by m-schen** [comment]
support select for date / datetime

**Comment by broccoliSpicy** [comment]
comparison operator has been added for date/datetime types

**Comment by domingozhang** [comment]
supported
