### ISSUE TITLE
[Bug]: execute load data local infile ...... parallel 'true'; error.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#8270]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Reproducible Steps:
1.git clone https://github.com/matrixorigin/mo-tpch
2.Generate data according to tpch prompts.
3.load data local infile ......... parallel 'true'（mysql -hxxx -uxxx -pxxx   --local-infile）

<img width="1648" alt="截屏2023-03-06 20 06 40" src="https://user-images.githubusercontent.com/39303074/223107867-0786fad2-fbb8-4ae9-aa20-258ef9fecfa3.png">

**Comment by mooleetzi** [comment]
load local does not support parallel now, feat request here https://github.com/matrixorigin/matrixone/issues/8142

**Comment by mooleetzi** [comment]
wait #8142

**Comment by mooleetzi** [comment]
wait #8142

**Comment by mooleetzi** [comment]
wait https://github.com/matrixorigin/matrixone/issues/8142

**Comment by mooleetzi** [comment]
wait https://github.com/matrixorigin/matrixone/issues/8142

**Comment by mooleetzi** [comment]
wait https://github.com/matrixorigin/matrixone/pull/8543

**Comment by mooleetzi** [comment]
wait https://github.com/matrixorigin/matrixone/pull/8543
