### ISSUE TITLE
[Bug]: `TestServerTimeoutCacheWillRemoved` failed on CI  sometimes

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#8278]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 845d784c7fa1
- Hardware parameters:
- OS type:
- Others: CI environment
```

### Actual Behavior

<img width="1891" alt="image" src="https://user-images.githubusercontent.com/20291742/223325905-d4b8cbe3-115e-457c-82d5-af9399790c94.png">
`TestServerTimeoutCacheWillRemoved` failed on CI  sometimes, not on each running.

UT Job Link: https://github.com/matrixorigin/matrixone/actions/runs/4350575733/jobs/7601415371

### Expected Behavior

Make test `TestServerTimeoutCacheWillRemoved` stable.

**Comment by zhangxu19830126** [comment]
fixed
