### ISSUE TITLE
[Bug]: `TestKeepaliveBind` failed on CI environment sometimes

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#8279]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 845d784c7fa143fa8ac39eb5b1ded16ab96b2218
- Hardware parameters:
- OS type:
- Others: CI environment
```

### Actual Behavior

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/20291742/223326665-dcd5d383-0d32-4df6-9269-857f4ff78e73.png">

`TestKeepaliveBind` failed on CI sometimes, not on each running.

UT Job Link: https://github.com/matrixorigin/matrixone/actions/runs/4344920998/jobs/7588918597

### Expected Behavior

Make test `TestKeepaliveBind` stable.

**Comment by zhangxu19830126** [comment]
fixed
