### ISSUE TITLE
[Subtask]: insert into unique table separately

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#8286]
### Parent Issue

https://github.com/matrixorigin/matrixone/issues/6949

### Detail of Subtask

Currently, one insert instruction inserts both data and unique tables.
We can separate them with multiple insert instructions. 
Keep insert instruction simple..

**Comment by triump2020** [comment]
Being refactor the S3Writer  for decomposing the insert operator.   i will push the pr tonight.

**Comment by triump2020** [comment]
Its ending time depends on @ouyuanning 's work

**Comment by triump2020** [comment]
It had been finished ,but wait for @ouyuanning 's branch merging into main.
