### ISSUE TITLE
[Bug]: The new connection was hung when mo run for about 6 hours without any load

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8291]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):845d784c7fa143fa8ac39eb5b1ded16ab96b2218
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The Suspicious error logs ares as following :

2023/03/07 15:28:51.007992 +0800 INFO frontend/util.go:419 check password succeeded connectionId 1209
2023/03/07 15:28:51.008130 +0800 INFO frontend/util.go:404 query trace {"connection_id": 1209, "query": "use mo_task", "session_info": "connectionId 1209"}
2023/03/07 15:28:55.057037 +0800 ERROR log-service util/log.go:133 txn send requests failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "requests": "[0: <89c71c9889ad400f9cb6a058549137c4/Active/S:1678174075056467467-0>/Read/F-0/=><2-262146-0-127.0.0.1:22000>]", "error": "context deadline exceeded"}
github.com/matrixorigin/matrixone/pkg/txn/util.LogTxnSendRequestsFailed
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/util/log.go:133
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).doSend
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:491
github.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).Read
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/txn/client/operator.go:252
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.getLogTail
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtailPullModel.go:68
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartitionOfPull
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtailPullModel.go:46
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).UpdateOfPull
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/db.go:305
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).New
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/engine.go:383
github.com/matrixorigin/matrixone/pkg/vm/engine.(*EntireEngine).New
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/entire_engine.go:33
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).NewTxn
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1550
github.com/matrixorigin/matrixone/pkg/frontend.(*Session).TxnStart
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1110
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).GetTxn
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1711
github.com/matrixorigin/matrixone/pkg/frontend.doUse
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:872
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleChangeDB
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:890
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3294
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4068
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
2023/03/07 15:28:55.057156 +0800 ERROR frontend/util.go:429 GetTxn. error:context deadline exceeded connectionId 1196
github.com/matrixorigin/matrixone/pkg/frontend.logErrorf
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/util.go:429
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnHandler).GetTxn
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1713
github.com/matrixorigin/matrixone/pkg/frontend.doUse
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:872
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleChangeDB
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:890
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3294
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4068
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
2023/03/07 15:28:55.057191 +0800 ERROR frontend/util.go:414 context deadline exceeded {"session_info": "connectionId 1196"}

[sever-hung.tar.gz](https://github.com/matrixorigin/matrixone/files/10907820/sever-hung.tar.gz)

**Comment by XuPeng-SH** [comment]
Seems it is the same with https://github.com/matrixorigin/MO-Cloud/issues/419

**Comment by nnsgmsone** [comment]
Same as 419, look at the log and logtail playback does not have any relationship, it is doSend when the upper layer transmission of the context timeout  @XuPeng-SH

**Comment by XuPeng-SH** [comment]
@LeftHandCold will try to reproduce this issue and reassign it to the owner after the investigation

**Comment by aressu1985** [comment]
#8327

**Comment by LeftHandCold** [comment]
Currently, cn-dn communication is serial in mo. When a txn of dn gets stuck, it will affect all txn sent by cn subsequently. At this time mo will hang.

**Comment by LeftHandCold** [comment]
After adding some logs, it cannot be reproduced.
In progress

**Comment by LeftHandCold** [comment]
Fixed

**Comment by LeftHandCold** [comment]
fixed

**Comment by aressu1985** [comment]
will test for some days

**Comment by aressu1985** [comment]
fixed
