### ISSUE TITLE
[Bug]: cn crashed by panic: unsupported type during runing daily  regression  on EKS with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8295]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-751c307
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The error log is :

{"level":"ERROR","time":"2023/03/07 23:54:34.878192 +0000","caller":"frontend/util.go:414","msg":"query trace status","connection_id":4294967295,"statement":"create table %!%mo_increment_columns (name varchar(770) primary key, offset bigint unsigned, step bigint unsigned)","status":"fail","error":"table %!%mo_increment_columns already exists","span":{"trace_id":"697f4078-bd43-11ed-9af5-06061fae3b9c","kind":"statement"},"session_info":"","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:414\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:398\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:388\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3923\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:2525\ngithub.com/matrixorigin/matrixone/pkg/frontend.InitSysTenant\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/authenticate.go:5180\ngithub.com/matrixorigin/matrixone/pkg/cnservice.(*service).registerExecutorsLocked.func2\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/server_task.go:225\ngithub.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).run.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/taskservice/task_runner.go:398\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}
{"level":"ERROR","time":"2023/03/07 23:54:34.878248 +0000","name":"cn-service.task-runner","caller":"taskservice/task_runner.go:404","msg":"run task failed","uuid":"00000000-0000-0000-0000-200000000000","runner-id":"00000000-0000-0000-0000-200000000000","task":"SystemInit/1","error":"table %!%mo_increment_columns already exists"}
{"level":"INFO","time":"2023/03/07 23:54:34.878392 +0000","caller":"frontend/util.go:404","msg":"query trace","connection_id":1001,"query":"use mo_task","session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.880104 +0000","caller":"frontend/util.go:419","msg":"User 21bac519-970a-40d8-bd3d-8bc444dcc286 change database from [mo_task] to [mo_task] connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.880155 +0000","caller":"frontend/util.go:404","msg":"query trace status","connection_id":1001,"statement":"use mo_task","status":"success","span":{"trace_id":"697fa30b-bd43-11ed-9af5-06061fae3b9c","kind":"statement"},"session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.880229 +0000","caller":"frontend/util.go:404","msg":"query trace","connection_id":1001,"query":"show tables","session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.882665 +0000","caller":"frontend/util.go:419","msg":"time of Exec.Build : 2.386456ms connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.882881 +0000","caller":"frontend/util.go:419","msg":"rowCount 2 \ntime of getDataFromPipeline : 3.241µs \nprocessBatchTime 1.85µs \nrow2colTime 0s \nrestTime(=totalTime - row2colTime) 3.241µs \nprotoStats flushCount 0 writeCount 1 \nwriteBytes 0 0 MB\n connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.882899 +0000","caller":"frontend/util.go:419","msg":"time of Exec.Run : 193.674µs connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.882943 +0000","caller":"frontend/util.go:404","msg":"query trace status","connection_id":1001,"statement":"show tables","status":"success","span":{"trace_id":"697feaa8-bd43-11ed-9af5-06061fae3b9c","kind":"statement"},"session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.883003 +0000","caller":"frontend/util.go:404","msg":"query trace","connection_id":1001,"query":"START TRANSACTION","session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.885079 +0000","caller":"frontend/util.go:404","msg":"query trace status","connection_id":1001,"statement":"start transaction","status":"success","span":{"trace_id":"69805691-bd43-11ed-9af5-06061fae3b9c","kind":"statement"},"session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:34.885141 +0000","caller":"frontend/util.go:404","msg":"query trace","connection_id":1001,"query":"prepare __mo_stmt_id_1 from update mo_task.sys_async_task set \n\t\t\t\t\t\t\ttask_metadata_executor=?,\n\t\t\t\t\t\t\ttask_metadata_context=?,\n\t\t\t\t\t\t\ttask_metadata_option=?,\n\t\t\t\t\t\t\ttask_parent_id=?,\n\t\t\t\t\t\t\ttask_status=?,\n\t\t\t\t\t\t\ttask_runner=?,\n\t\t\t\t\t\t\ttask_epoch=?,\n\t\t\t\t\t\t\tlast_heartbeat=?,\n\t\t\t\t\t\t\tresult_code=?,\n\t\t\t\t\t\t\terror_msg=?,\n\t\t\t\t\t\t\tcreate_at=?,\n\t\t\t\t\t\t\tend_at=? where task_id=? and task_runner='00000000-0000-0000-0000-200000000000' AND task_status=1 AND task_epoch=1","session_info":"connectionId 1001"}
{"level":"INFO","time":"2023/03/07 23:54:35.031118 +0000","name":"cn-service.ETLMerge","caller":"runtime/panic.go:884","msg":"done merge 'system_metrics.metric'","uuid":"00000000-0000-0000-0000-200000000000","span":{"trace_id":"9fbf3ad3-04f1-c3ca-dd86-5919858e539b","span_id":"f751f1d5c554c402"}}
panic: unsupported type

goroutine 21894 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/index.(*ZoneMap).Unmarshal(0x41f187?, {0xc007206d40?, 0x2624ac0?, 0xc014f50101?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/index/zonemap.go:417 +0x117a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.(*BlockIndex).Unmarshal(0xc000500800?, {0xc007206d40?, 0xc014f501e0?, 0x2dad500?})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/index.go:64 +0x25
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.LoadZoneMapFunc({0xc007206d40, 0x40, 0x40}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/reader.go:223 +0xa8
github.com/matrixorigin/matrixone/pkg/objectio.(*ZoneMap).Unmarshal(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/index.go:73
github.com/matrixorigin/matrixone/pkg/objectio.(*ColumnBlock).UnMarshalMate(0xc00712ef90, 0xc00d9b5320?)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/column.go:174 +0x267
github.com/matrixorigin/matrixone/pkg/objectio.(*Block).UnMarshalMeta(0xc00257c510, {0xc0141c5600, 0x3c0, 0x580}, 0x2a24dd8)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/block.go:163 +0x469
github.com/matrixorigin/matrixone/pkg/objectio.(*ObjectReader).ReadMeta.func1({0x2d3e120?, 0xc00d9b52f0?}, {0xc0141c5600?, 0x580?, 0xc7fc20?})
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/reader.go:90 +0x217
github.com/matrixorigin/matrixone/pkg/fileservice.(*IOEntry).setObjectFromData(0xc000a64468)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/io_entry.go:144 +0xc4
github.com/matrixorigin/matrixone/pkg/fileservice.(*S3FS).read(0xc000d47400, {0x2d7ee58?, 0xc00bd79dd0?}, 0xc007145440?)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/s3_fs.go:626 +0xbad
github.com/matrixorigin/matrixone/pkg/fileservice.(*S3FS).Read(0xc000d47400, {0x2d7edb0, 0xc007657c40}, 0xc007145440)
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/s3_fs.go:406 +0x2ed
github.com/matrixorigin/matrixone/pkg/objectio.(*ObjectReader).ReadMeta(0xc01586bf20, {0x2d7edb0, 0xc007657c40}, {0xc008de95e0, 0x1, 0x1}, 0xc000096800?, 0x2a24dd8)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/reader.go:103 +0x27a
github.com/matrixorigin/matrixone/pkg/objectio.(*ObjectReader).ReadAllMeta(0x2766a20?, {0x2d7edb0, 0xc007657c40}, 0x2139879?, 0x10?, 0xc00884eaf0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/objectio/reader.go:159 +0x78
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.(*BlockReader).LoadAllColumns(0xc004247140, {0x2d7edb0, 0xc007657c40}, {0xc00fa8cc42, 0x7, 0x7}, 0x400?, 0x2d05b50?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio/reader.go:108 +0x73
github.com/matrixorigin/matrixone/pkg/util/export/etl.(*TAEReader).ReadAll(0xc015f24f00, {0x2d7edb0?, 0xc007657c40?})
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/etl/tae.go:326 +0x4d
github.com/matrixorigin/matrixone/pkg/util/export.newETLReader({0x2d7edb0, 0xc007657c40}, 0xc009cd1b60?, {0x2da6580, 0xc000d47400}, {0xc0091d6000, 0x5b}, 0x47?, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/merge.go:503 +0x151
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).doMergeFiles(0xc010c985a0, {0x2d7ee58, 0xc009cd1b60}, {0xc000a10955, 0x3}, {0xc000a652c8, 0x3e8, 0x29426f3?}, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/merge.go:327 +0x865
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).Main(0xc010c985a0?, {0x2d7ee58, 0xc009cd1b60?}, {0xc0fa118eb418aa0f?, 0xca04fc320?, 0x418c940?})
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/merge.go:256 +0x474
github.com/matrixorigin/matrixone/pkg/util/export.MergeTaskExecutorFactory.func1({_, _}, {0xbb9, {{0xc009b0ebd0, 0x26}, 0x2, {0xc00aa82360, 0x15, 0x15}, {0x0, ...}, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/merge.go:721 +0x7db
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).run.func1({0x100000000000000?, 0xc00d5febd0?})
	/go/src/github.com/matrixorigin/matrixone/pkg/taskservice/task_runner.go:398 +0x595
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0x12c
[cn-crashbackoff.log](https://github.com/matrixorigin/matrixone/files/10915250/cn-crashbackoff.log)

**Comment by LeftHandCold** [comment]
The etl data also needs to be deleted. The type field has not been used before. It has been used in the “read/write refactors“ pr

**Comment by aressu1985** [comment]
closed
