### ISSUE TITLE
[Bug]: EKS test transaction  insert into select table reported panic 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8298]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):867dba572d9dd6e4253e781116ac8aea4ec58c43
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

eks test
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4353932927/jobs/7609041237
<img width="1473" alt="企业微信截图_cb25cd4d-d5c9-4d3b-87ea-81743971c8e8" src="https://user-images.githubusercontent.com/113406637/223604216-334fb310-7992-4791-9682-ce85c3ba9264.png">
case:
![image](https://user-images.githubusercontent.com/113406637/223604409-ada37607-df2f-40b8-a670-309449ba95d4.png)

**Comment by JackTan25** [comment]
create table t(a int);
insert into t values(1);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
begin;
insert into t select * from t;

**Comment by JackTan25** [comment]
![Uploading e9fb8fec4a5b942e509e79ca929d640.png…]()
context cancel error

**Comment by JackTan25** [comment]
revert 8316

**Comment by JackTan25** [comment]
I will resubmit my pr at https://github.com/matrixorigin/matrixone/pull/8325

**Comment by JackTan25** [comment]
I will resubmit my pr at https://github.com/matrixorigin/matrixone/pull/8325

**Comment by JackTan25** [comment]
I have revert my pr， main is safe, please test it again

**Comment by heni02** [comment]
comfirm, eks test pass 100%
![image](https://user-images.githubusercontent.com/113406637/225809958-689a8589-1952-4136-a571-cfd0bccd9add.png)
