### ISSUE TITLE
[Bug]: incorrect syntax sql is displayed in statement_info with sql label

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8304]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In SQL edit of mo-cloud, user input an incorrect syntax such as 'sdfsdfsd', the label of /* cloud_user */ is displayed as following. This label needs to be removed normally.

select statement from system.statement_info where statement_id='0646587e-e9ce-48c8-89ec-64a05e43bd4e';
+---------------------------+
| statement                 |
+---------------------------+
| /* cloud_user */sdfsdfsd; |
+---------------------------+
1 row in set (6 min 37.09 sec)

**Comment by tianyahui-python** [comment]
<img width="1609" alt="截屏2023-03-20 22 45 34" src="https://user-images.githubusercontent.com/39303074/226376202-c8681646-3c0c-4e2c-a604-e0282b85fd44.png">
<img width="1613" alt="截屏2023-03-20 22 46 49" src="https://user-images.githubusercontent.com/39303074/226376396-150b96f7-77ed-4684-967f-77fa735d9e0f.png">



The current bug has been resolved
