### ISSUE TITLE
[Bug]: The cost increased obviously of loading data with small size  

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8307]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):751c307e8ab4c25812de9250778d342ad1ffc5c2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/47846308/223648358-c83ef740-5eaf-4b21-9540-3ed5166c61a8.png">

**Comment by XuPeng-SH** [comment]
Seems it is https://github.com/matrixorigin/matrixone/pull/8258 related.

**Comment by JackTan25** [comment]
revert here https://github.com/matrixorigin/matrixone/pull/8316

**Comment by JackTan25** [comment]
This normal

**Comment by sukki37** [comment]
depends on context refactor #7502

**Comment by JackTan25** [comment]
This is normal

**Comment by aressu1985** [comment]
@JackTan25 What means that it it normal?

**Comment by aressu1985** [comment]
Has discussed with product manager and this can be closed
