### ISSUE TITLE
[Subtask]: add DDL creating the table with partitions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#8312]
### Parent Issue

#7717 

### Detail of Subtask

- add  four partiton methods.  LIST [COLUMNS],RANGE [COLUMNS], KEY(), HASH()
- verify the rationality of the partition expr for four partitions methods
- create main table with parition meta
- create partition table
- mo_tables changes
- mo_columns changes
- mo_table_size. the table size is equal to the sum of the partition tables.
- mo_table_rows. the table rows is equal to the sum of the partition tables.

**Comment by daviszhen** [comment]
list rang 没有完成。
第二个部分。
缺最后两个。

**Comment by qingxinhome** [comment]
This function has been implemented, please close it @daviszhen @sukki37
