### ISSUE TITLE
[Subtask]: add dropping/truncating the table with partitions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#8315]
### Parent Issue

#7717 

### Detail of Subtask

- truncate the table
- drop the table

### Additional information

we do not support the ALTER TABLE with add/drop the partitions

**Comment by daviszhen** [comment]
truncate 没有做

**Comment by qingxinhome** [comment]
Processing the feature

**Comment by qingxinhome** [comment]
The subtask has been completed, please confirm @daviszhen

**Comment by qingxinhome** [comment]
The subtask has been completed, please confirm @daviszhen

**Comment by daviszhen** [comment]
it was done.
