### ISSUE TITLE
[Subtask]: keep SHOW xxx consistent with the 0.7 version even the table has the partitions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#8318]
### Parent Issue

#7717

### Detail of Subtask

- show tables. filter the partition table.
- show columns. filter the columns from the partition table.
- show create table
- show table status
- show accounts
- information_schema.partitions view

**Comment by daviszhen** [comment]
show table status
show accounts
information_schema.partitions view

这几个还没检验

**Comment by daviszhen** [comment]
show table status
show accounts
已经做了。

information_schema.partitions view 还没做完。

**Comment by qingxinhome** [comment]
This function has been implemented @daviszhen @sukki37
