### ISSUE TITLE
[Bug]: The count of table data is not correct after running oltp insert test with 100 concurrency for 60 hours

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8332]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ae2641e67767d71eeaae50782551deeb5f6c06b4
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Before testing, there 10 tables, and each table has 100000 records. Then run the oltp insert hight concurrent test with 100 threads,  one transaction only has one insert statement which insert on record to a random table.

After about 66 hours, the mo was killed by system for oom.

From the test tools, the total num of successful txn is 29926669
<img width="534" alt="image" src="https://user-images.githubusercontent.com/47846308/223925410-18bf14de-42a0-4849-b5f2-b87e87c144cc.png">

and it means that the total size of these ten tables will be 10*100000+29926669 = 30026669

but the real total size of thes ten table is : **30826763, and is 900094 more than expected value(30026669)**

**Comment by aressu1985** [comment]
I run the same test again for about 2 hours, and the result is not correct either.

**Comment by LeftHandCold** [comment]
Today's focus is not here

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/224480768-c2ab0fff-e088-4a32-b604-87e5941bc0a3.png)
I can't reproduce it

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/224526693-d2f3a145-ead6-4ac2-b737-542841976602.png)
I can't reproduce it
May be a test exception

**Comment by fengttt** [comment]
@LeftHandCold did you run a select count to verify the number?

**Comment by fengttt** [comment]
> ![image](https://user-images.githubusercontent.com/14086886/224526693-d2f3a145-ead6-4ac2-b737-542841976602.png) I can't reproduce it May be a test exception

What is a test exception?  :)     There is no such thing ...  Try harder to repro :)

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/224720029-c055e013-3137-46ea-bab6-6f79cd106cd3.png)
I can't use select to query the total, only add up to get the total.

**Comment by LeftHandCold** [comment]
![image](https://user-images.githubusercontent.com/14086886/224721457-50274ca9-82a3-4a00-9080-77ea136713ba.png)
![image](https://user-images.githubusercontent.com/14086886/224721573-64d605db-4dd2-42a8-9681-da7eae26e061.png)
I still can't reproduce it. There is an extra row of data in the test result. I think it's normal because I killed mo first. This will happen if the txn of mo has been successfully executed, but it was killed when it was returned to the client. @daviszhen

**Comment by aressu1985** [comment]
Sorry, I had made a mistake.  @LeftHandCold is right, I use a wrong number to calculate the result.
