### ISSUE TITLE
High CPU usage (~450%) if create ~5000 tables with stand-alone mode

### ISSUE THREAD

**Issue by lignay** [matrixorigin/matrixone#834]
#### Can be reproduced ?
Yes

#### Steps:

1. Create ~5000 tables
2. Restart MO service
3. Monitor CPU usage

#### Actual behavior:
High CPU usage (~450%) 

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by JinHai-CN** [comment]
#1438 will track this kind of problem.
