### ISSUE TITLE
[Bug]: TPCH Q13 will cause cn crashed on ESK with 2*cn 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8352]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-751c307
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="711" alt="image" src="https://user-images.githubusercontent.com/47846308/224209942-adce5dd9-9432-4bd1-95a1-ed7bb514f95d.png">

**Comment by nnsgmsone** [comment]
你为啥不自己解决这个问题呢

**Comment by nnsgmsone** [comment]
直接revert

**Comment by dongdongyang33** [comment]
waiting pr merge

**Comment by nnsgmsone** [comment]
waiting for test

**Comment by nnsgmsone** [comment]
fixed

**Comment by dongdongyang33** [comment]
fix, please test with right join

**Comment by aunjgr** [comment]
@aressu1985 Please verify

**Comment by aressu1985** [comment]
fxied
