### ISSUE TITLE
[Bug]: MO was hung for more than 3 hours when running regression test on EKS with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8353]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-4a1f767
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After running oltp point select 100 terminals test for about 3 mintues , the mo could not deal with an request .
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/47846308/224213104-4a868243-bb7b-4193-8d9e-146f43702b8c.png">

and after 3 hours, the mo was recoveried
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/47846308/224213337-65668d3e-4b93-449e-8295-74126b094100.png">

and servals minutes later, mo was hung again

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/47846308/224213509-4bdc0463-62ca-4fad-b6e6-13199c5b775b.png">

and I really do not know how to provide triage information, all the logs and trace can be got from eks in namespace mo-nightly-regression

**Comment by aressu1985** [comment]
job:  https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4376371415/jobs/7661664967

**Comment by zengyan1** [comment]
在commit镜像nightly-cd7e8c9上没有复现成功

**Comment by zengyan1** [comment]
继续尝试复现中，使用每晚生成的最新镜像

**Comment by zengyan1** [comment]
继续复现中

**Comment by zengyan1** [comment]
继续复现中，3月21日commit镜像id:nightly-f292144

**Comment by zengyan1** [comment]
在nightly-f1598b3上复现失败，等待MO Nightly Regression On EKS的日志https://github.com/matrixorigin/mo-nightly-regression/actions

**Comment by zengyan1** [comment]
继续在commit ID: nightly-50039b3c尝试复现

**Comment by zengyan1** [comment]
尝试在此次测试的log中定位https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4502656740

**Comment by zengyan1** [comment]
正在mo-ares/mo-benchmark/etl_202303241512/sys/logs/2023/03/24/日志中定位问题

**Comment by zengyan1** [comment]
继续分析日志中

**Comment by zengyan1** [comment]
疑似logservice的leader挂掉后重新选取leader失败，导致CNDN都无法连接至logservice并一直在重新尝试连接，进而导致MO hung住

**Comment by zengyan1** [comment]
暂未复现

**Comment by fengttt** [comment]
Not repro, we think it is fixed by log service.   Please reopen if repro.

**Comment by aressu1985** [comment]
closed
