### ISSUE TITLE
[Bug]: no error returned for `morpc.ClientSession.Write` if morpc client side terminated

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#8382]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ff3f8922870905d9618963477fd12c291da8f324
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

With server side morpc stream, which is a `morpc.ClientSession` instance, the Write method wouldn't return error if the morpc client side was terminated.

### Expected Behavior

Return error when writing on closed `morpc.ClientSession`.

### Steps to Reproduce

1. launch `mo-service` with default port 32003 as logtail service listen address
2. running [subscriber](https://github.com/matrixorigin/subscriber)
> ./subscriber -address 127.0.0.1:32003
4. ctrl + c to cancel `subscriber`
5. no error returned when writing on morpc.ClientSession

**Comment by cnutshell** [comment]
goetty had detected the closed tcp connection when `subscriber` terminated:
`2023/03/12 12:45:45.236789 +0800 ERROR dn-service.logtail-push-rpc v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:345 handle session failed {"uuid": "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf", "server-id": "f9128353-578c-4fc6-a05b-fb2443b586c9", "name": "logtail-push-rpc", "listen-addresses": "[0.0.0.0:32003]", "error": "read tcp4 127.0.0.1:32003->127.0.0.1:58733: use of closed network connection"}`

**Comment by zhangxu19830126** [comment]
fixed
