### ISSUE TITLE
[Bug]: mo panic: runtime error: index out of range [0] with length 0 when run tpcc 10 warehourse 100 terminals test in push mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8390]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0129d792a1253bdf8c52afbd9ec8e239e77937d5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023/03/13 08:43:54.324775 +0800 INFO frontend/util.go:414 time of Exec.Run : 54.640215ms connectionId 1098
2023/03/13 08:43:54.324827 +0800 INFO frontend/util.go:414 time of SendResponse 629ns connectionId 1098
2023/03/13 08:43:54.324921 +0800 INFO frontend/util.go:399 query trace status {"connection_id": 1098, "statement": "execute __mo_stmt_id_8 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4", "status": "success", "span": {"trace_id": "217ebc1b-c138-11ed-a7cb-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1098"}
2023/03/13 08:43:54.325156 +0800 INFO frontend/util.go:399 query trace {"connection_id": 1098, "query": "execute __mo_stmt_id_8 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4", "vars": "90 , 5 , 0 , 1 , 79926", "session_info": "connectionId 1098"}
2023/03/13 08:43:54.325210 +0800 INFO blockio/read.go:90 blockread 7307 read delete 830: base 1678668234295051090-0 filter out 830

panic: runtime error: index out of range [0] with length 0

goroutine 65449264 [running]:
github.com/matrixorigin/matrixone/pkg/container/vector.DecodeFixedCol[...](0xc24b727a80?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:221 +0xe5
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).setupColFromData(0xc24b727a80)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/tools.go:175 +0x145
github.com/matrixorigin/matrixone/pkg/container/vector.FromDNVector({0x16, 0x0, 0x0, 0x0, 0x4, 0x20, 0xffffffff, 0x0}, {0x0, 0x0, ...}, ...)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/tools.go:142 +0x19f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.UnmarshalToMoVec({0x2e1ec78, 0xc1ba464b40})
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/containers/utils.go:82 +0x112
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/dataio/blockio.BlockRead({0x2d9ead8, 0xc1a2b7c780}, 0xc09e8ecd00?, {0xc0f4c71920, 0x3, 0x3}, {0xc24cb68380, 0x3, 0x3}, {0x174bd3dd78e38352, ...}, ...)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/dataio/blockio/read.go:59 +0x365
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockReader).Read(0xc126dcbea0, {0x2d9ead8?, 0xc21ee044b0?}, {0xc196733320?, 0x3?, 0xc072488000?}, 0xc003491ea8?, 0x41ea47?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/reader.go:83 +0x2f5
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc007b1bf28, {0x2d7d710, 0xc126dcbea0}, 0xc10b7d4c00)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:70 +0x18b
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc150e11040, 0xc1488920e0?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:70 +0x14e
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x43ed2c0?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:90 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:85 +0x20d

**Comment by LeftHandCold** [comment]
ablk filters according to ts, and there may be a vector with a length of 0

**Comment by aunjgr** [comment]
#8399 should have fixed it

**Comment by aressu1985** [comment]
fixed
