### ISSUE TITLE
[Bug]: Error displayed after index creation

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8392]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:0129d792a1253bdf8c52afbd9ec8e239e77937d5
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

mo结果：
![image](https://user-images.githubusercontent.com/108530700/224616878-83ac8930-ace8-46b8-96a9-fe9ed27cacbe.png)

### Expected Behavior

mysql结果：
![image](https://user-images.githubusercontent.com/108530700/224617490-bc275814-7578-4a5e-b291-0a47c23bc47e.png)

### Steps to Reproduce

```Markdown
mysql>create table student(name varchar(20),id int);
mysql>create index index1 on student(name);
mysql>show index from student;
```

**Comment by qingxinhome** [comment]
The problem has been resolved, please test @Ariznawlll @daviszhen @domingozhang

**Comment by Ariznawlll** [comment]
test done.
