### ISSUE TITLE
[Bug]: Data collection suddenly stops

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#8414]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1668" alt="截屏2023-03-13 20 16 11" src="https://user-images.githubusercontent.com/39303074/224699846-35dbfc39-a399-4c70-92b0-7928df654078.png">

env:
<img width="913" alt="截屏2023-03-13 20 17 28" src="https://user-images.githubusercontent.com/39303074/224699884-f5db107f-e40b-4b8b-abaa-2d318c17ef7a.png">

**Comment by xzxiong** [comment]
看到有持续更新，但就是有延迟 。
![image](https://user-images.githubusercontent.com/3927687/224931607-81d3adce-924d-4a76-8073-c96ad9e18c82.png)

**Comment by xzxiong** [comment]
> this issue may caused by #8473, let us check again after that issue fixed.

fixed, pls re-check
