### ISSUE TITLE
Parsers plan

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#842]
#### Parsers plan:
1.Figure out the code structure of the entire parser
2.Write rule files about create table statement for mysql and postgresql. The definition of various data types, ast structure, and rule files are initially formed. The grammar rules are estimated to account for a quarter of the entire rule file. 
3.Write a tokenizer
4.Add test code
5.Improve mysql rule files and test cases, it is estimated that 85% of mysql syntax will be supported
6.Performance testing and improvement
7.Add the parsers module to matrixone

#### Mysql SQL Statements
1.Data Definition Statements: 34
2.Data Manipulation Statements: 11
3.Transactional and Locking Statements: 7
4.Replication Statements: 3
5.Prepared Statements: 3
6.Compound Statements: 7
7.Database Administration Statements: 6
8.Utility Statements: 4

**Comment by JinHai-CN** [comment]
Data Definition Statements #997 
Data Manipulation Statements #998 
Transactional Statements #999 
Prepared Statements #1000 
Database Administration Statements #1001

**Comment by JinHai-CN** [comment]
#999 is needed in v0.3.0
#1000 isn't planned now.

**Comment by fengttt** [comment]
Fixed/resolved by plan2 work.
