### ISSUE TITLE
[Bug]: SSB 100G Q2.2 was hung on EKS with 2 cns

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8420]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): cd7e8c9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/47846308/224874677-dad9746b-c289-4dd3-b0ae-d4b589880fd1.png">

**Comment by zengyan1** [comment]
在commit镜像nightly-cd7e8c9上没有复现成功

**Comment by zengyan1** [comment]
继续尝试复现中

**Comment by zengyan1** [comment]
继续复现中，3月21日commit镜像id:nightly-f292144

**Comment by zengyan1** [comment]
在nightly-f1598b3上复现失败，等待MO Nightly Regression On EKS的日志https://github.com/matrixorigin/mo-nightly-regression/actions

**Comment by zengyan1** [comment]
继续在commit ID: nightly-50039b3c尝试复现

**Comment by zengyan1** [comment]
尝试在此次测试的log中定位https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4502656740

**Comment by zengyan1** [comment]
继续分析日志中

**Comment by zengyan1** [comment]
有可能已被修复，先观察一下daily run

**Comment by zengyan1** [comment]
继续观察中

**Comment by fengttt** [comment]
Dup #8353.   Not repro.

**Comment by aressu1985** [comment]
downgrade to s1 ,and tracking for more days.

**Comment by aressu1985** [comment]
not happen again.this can be closed
