### ISSUE TITLE
[Bug]: Logservice restarted serval times for fatal error: concurrent map writes during daily regression test on eks 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8421]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): cd7e8c9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

gin/matrixone/pkg/logservice/store.go:671\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:224\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}
{"level":"ERROR","time":"2023/03/13 21:17:42.543277 +0000","name":"log-service","caller":"task/task_scheduler.go:118","msg":"failed to query tasks","uuid":"00000000-0000-0000-0000-000000000001","status":"Created","error":"context deadline exceeded","stacktrace":"github.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).queryTasks\n\t/go/src/github.com/matrixorigin/matrixone/pkg/hakeeper/task/task_scheduler.go:118\ngithub.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).Schedule\n\t/go/src/github.com/matrixorigin/matrixone/pkg/hakeeper/task/task_scheduler.go:54\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).taskSchedule\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:199\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).hakeeperCheck\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:143\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).ticker\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:671\ngithub.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:224\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}
{"level":"INFO","time":"2023/03/13 21:17:42.545770 +0000","name":"log-service","caller":"logservice/check.go:30","msg":"node is expired","uuid":"00000000-0000-0000-0000-000000000001","uuid":"00000000-0000-0000-0000-000000000002"}
{"level":"INFO","time":"2023/03/13 21:17:42.545781 +0000","name":"log-service","caller":"logservice/check.go:30","msg":"node is expired","uuid":"00000000-0000-0000-0000-000000000001","uuid":"00000000-0000-0000-0000-000000000002"}
fatal error: concurrent map writes

goroutine 360 [running]:
github.com/matrixorigin/matrixone/pkg/hakeeper/operator.(*Controller).Dispatch(0xc000d20018, {0xc0077c0cc0, 0x1, 0x0?}, {0xc005669cb0, 0xc005669d70, {}, {0x0, 0x0, 0x0}, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/hakeeper/operator/controller.go:110 +0xeb
github.com/matrixorigin/matrixone/pkg/hakeeper/checkers.(*Coordinator).Check(_, {_, _}, {0x3076a, {{0xc005669950, 0x1, 0x1}, {0xc0081faf00, 0x2, 0x2}, ...}, ...})
	/go/src/github.com/matrixorigin/matrixone/pkg/hakeeper/checkers/coordinator.go:93 +0xf86
github.com/matrixorigin/matrixone/pkg/logservice.(*store).getScheduleCommand(0xc000cc82c0, 0x1, 0x4611f2?, 0xc0055fcdc0)
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:294 +0x3a3
github.com/matrixorigin/matrixone/pkg/logservice.(*store).healthCheck(0xc000cc82c0, 0x45b773?, 0x44c1d6?)
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:170 +0xaa
github.com/matrixorigin/matrixone/pkg/logservice.(*store).hakeeperCheck(0xc000cc82c0)
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store_hakeeper_check.go:142 +0x125
github.com/matrixorigin/matrixone/pkg/logservice.(*store).ticker(0xc000cc82c0, {0x2daea98, 0xc0004b48d0})
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:671 +0x3ac
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica.func1({0x2daea98, 0xc0004b48d0})
	/go/src/github.com/matrixorigin/matrixone/pkg/logservice/store.go:224 +0x6f
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259 +0x79
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:254 +0x12c

goroutine 1 [chan receive, 204 minutes]:
main.waitSignalToStop(0x7ffd8e2fd9a0?)
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:114 +0xba
main.main()
	/go/src/github.com/matrixorigin/matrixone/cmd/mo-service/main.go:107 +0x2f3

goroutine 25 [chan receive]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc00024abd0)
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:69 +0x8b
created by github.com/panjf2000/ants/v2.NewPool
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/pool.go:137 +0x365

goroutine 100 [chan receive, 204 minutes]:
github.com/matrixorigin/matrixone/pkg/fileservice.NewMemCache.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/mem_cache.go:35 +0x4a
created by github.com/matrixorigin/matrixone/pkg/fileservice.NewMemCache
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/mem_cache.go:34 +0x76

goroutine 120 [chan receive, 204 minutes]:
github.com/matrixorigin/matrixone/pkg/fileservice.NewMemCache.func1()
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/mem_cache.go:35 +0x4a
created by github.com/matrixorigin/matrixone/pkg/fileservice.NewMemCache
	/go/src/github.com/matrixorigin/matrixone/pkg/fileservice/mem_cache.go:34 +0x76

goroutine 359 [select, 203 minutes]:
github.com/lni/dragonboat/v4/internal/tan.(*db).deleteObsoleteWorkerMain(0xc005794240)
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230302063425-d44b237aabe8/internal/tan/compaction.go:154 +0x65
github.com/lni/dragonboat/v4/internal/tan.open.func2()
	/go/pkg/mod/github.com/matrixorigin/dragonboat/v4@v4.0.0-20230302063425-d44b237aabe8/internal/tan/open.go:160 +0x1d
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1()
	/go/pkg/mod/github.com/matrixorigin/goutils@v1.3.1-0.20220604063047-388d67b4dbc4/syncutil/stopper.go:79 +0xc5
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
	/go/pkg/mod/github.com/matrixorigin/goutils@v1.3.1-0.20220604063047-388d67b4dbc4/syncutil/stopper.go:74 +0xea

goroutine 109 [select]:
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doCollect(0xc00051e9c0, 0x1c?)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:376 +0x1be
created by github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:336 +0x13e

goroutine 108 [select]:
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doCollect(0xc00051e9c0, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:376 +0x1be
created by github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:336 +0x13e

goroutine 110 [select]:
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doCollect(0xc00051e9c0, 0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:376 +0x1be
created by github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).Start
	/go/src/github.com/matrixorigin/matrixone/pkg/util/export/batch_processor.go:336 +0x13e

goroutine 107 [select]:
github.com/matrixorigin/matrixone/pkg/util/export.(*MOCollector).doCollect(0xc00051e9c0, 0x0?)
[logservice.restart.log](https://github.com/matrixorigin/matrixone/files/10963538/logservice.restart.log)
[logservice3.restart.log](https://github.com/matrixorigin/matrixone/files/10963539/logservice3.restart.log)

**Comment by volgariver6** [comment]
will handle it later.

**Comment by volgariver6** [comment]
same as #8483 , fixed by #8617 .

**Comment by volgariver6** [comment]
this issue could be retest as it has been fixed.

**Comment by aressu1985** [comment]
@heni02 pls verify this

**Comment by heni02** [comment]
Not easy to reproduce,Unable to verify at this time, change the status to holding first

**Comment by aressu1985** [comment]
closed
