### ISSUE TITLE
[Bug]: udf execution hack engine read

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#8426]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/pull/7655, This pr introduces a hack of engine reads, and the normal practice would be to build a plan and then execute that plan to get the input you want.

**Comment by chrisxu333** [comment]
I think 7655 is already reverted. A newer version of udf execution has been merged already :)

**Comment by florashi181** [comment]
so is this issue accomplished? Pls note the circulation and update of issues. @chrisxu333

**Comment by chrisxu333** [comment]
Yes it's accomplished already :)
