### ISSUE TITLE
[Performance]: MOCollector consumes lots of cpu resource

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#8428]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

1. Change the config:
[cn.rpc]
send-queue-size = 2
busy-queue-size = 1

turn-on-push-model = true
Change the log level to "warn" or "error"

2. run sysbench insert with 50 concurrency

![37d85133447dbcbd2f17a8be4e1b2ea5](https://user-images.githubusercontent.com/39627130/224882989-09d37a29-3605-43cc-8f73-02230c602842.jpg)

### Additional information

For example: Have you compared MatrixOne with other databases? 
If yes, what's their difference?

**Comment by fengttt** [comment]
Can you please include the full picture?   Cropped.

so the motrace is not in transaction path.   It is a periodical background process but we believe it is causing perf problems.

Not sure if this is related to #8354.

I took a quick look at serializePlanToJson and I think it is scary -- esp for TP workload.

**Comment by fengttt** [comment]
But profiling shows the problem is parse json.   So I don't know.   But @xzxiong remember we said that log/trace etc must has a perf impact no more than ~5% or so.   We need to optimize motrace, or, not log/trace very simple TP queries.

**Comment by XuPeng-SH** [comment]
> Can you please include the full picture? Cropped.
> 
> so the motrace is not in transaction path. It is a periodical background process but we believe it is causing perf problems.
> 
> Not sure if this is related to #8354.
> 
> I took a quick look at serializePlanToJson and I think it is scary -- esp for TP workload.

![profile004](https://user-images.githubusercontent.com/39627130/224951152-a310f8d0-9656-4597-a5e5-b4e9f5061b34.png)

@fengttt

**Comment by fengttt** [comment]
https://github.com/matrixorigin/matrixone/issues/8080   Maybe we should also have a session variable that can turn up/down query/session log level.

**Comment by xzxiong** [comment]
> But profiling shows the problem is parse json. So I don't know. But @xzxiong remember we said that log/trace etc must has a perf impact no more than ~5% or so. We need to optimize motrace, or, not log/trace very simple TP queries.

no more than ~5 %, yes, i remenber that.
from motrace, core impact on the TP query key path should be the statement collection (in report_statement.go).
I should first evaluate the impact of  statement collection, after i fix #8354

**Comment by xzxiong** [comment]
Test Case
---
Env: MacBook Pro M1
mo commit id: 223956500, date: 2023-04-27
etc: etc/launch-tae-CN-tae-DN
cache: none
case: sysbench read-only with 10 concurrency
CPU limit: 800%

cpu profile
---
1. log write to files cost > 15%
2. etl write tae cost > 6 %

[cpu.profile.pb.gz](https://github.com/matrixorigin/matrixone/files/11403135/profile.pb.gz)



- overall, zap.Info cost very much
![image](https://user-images.githubusercontent.com/3927687/236375591-a86a7fac-786f-4172-b510-274a8198c4d7.png)



- in function `motrace.genETLData`,  `etl.(*TAEWriter).WriteRow` cost most cpu.
![image](https://user-images.githubusercontent.com/3927687/236373796-8d25a9fc-484b-4adb-a2f0-2e51bfe1d949.png)


- in function `motrace.genETLData`, cost little cpu, 0.44%
![image](https://user-images.githubusercontent.com/3927687/236376021-c0c0526b-1cc6-4633-9f94-f54055471e6f.png)



full svg
![profile001](https://user-images.githubusercontent.com/3927687/236375450-a7a390ce-5a72-4fc0-8876-b1e333925832.svg)

**Comment by xzxiong** [comment]
update: MOCollector cost cpu about 5.48 %.
commit: 0fc37ced9
date: 2023-05-25

> trace-on 与 trace-off性能差异的问题，在这继续跟踪 https://github.com/matrixorigin/matrixone/issues/9472

[profile.pb.gz](https://github.com/matrixorigin/matrixone/files/11572210/profile.pb.gz)

![image](https://github.com/matrixorigin/matrixone/assets/3927687/68b32fcd-3ea2-4a5e-ba7d-488d5c0162bb)

**Comment by xzxiong** [comment]
剩余性能问题，会在 https://github.com/matrixorigin/matrixone/issues/9472 继续跟进。

**Comment by xzxiong** [comment]
@XuPeng-SH ptal
