### ISSUE TITLE
[Feature Request]: add version functions

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#8436]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

select git_version() or select build_version(); 
that prints out build time, and git hash

**Comment by daviszhen** [comment]
@iceTTTT 其它的做完了后，把这个函数加一下。

**Comment by Ariznawlll** [comment]
Linux下：
![image](https://user-images.githubusercontent.com/108530700/232374346-31491f0b-b92f-409f-be82-d0cdac19e8c5.png)
macOS下：
![image](https://user-images.githubusercontent.com/108530700/232374197-01c603b7-3d77-4d1f-9f09-452e93cfa806.png)


test done!
