### ISSUE TITLE
[Bug]: TestHAKeeperCanBootstrapAndRepairShards failed

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#8438]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![e4805a81b78c89ccdd5b423ac86dc2f](https://user-images.githubusercontent.com/28624654/224918952-d94b39e0-d6f3-43b5-976c-2052e0675d66.png)

### Expected Behavior

UT should pass.

**Comment by volgariver6** [comment]
刚创建时的日志不全，跑ut时又发生了一次，上传日志
[fail.log](https://github.com/matrixorigin/matrixone/files/11188527/fail.log)

**Comment by gouhongshen** [comment]
the error seems caused by timeout(2s) when invoke `state, err := store1.getCheckerState()`. 

and the log detail shows that some communication problems exist between the raft nodes (and the gossip nodes). 

So I tried traffic control by execute shell command: 
```
tc qdisc add dev lo root netem delay 50ms 10ms
tc qdisc add dev lo root netem loss 10% 
```
or add some random sleep in dragonbaot/internal/raft/raft.go::handleHeartbeatMessage().

And I got a similar timeout error, but not totally the same, so I am not sure it must be the network issue.

**Comment by gouhongshen** [comment]
the `memberlist: ` errors may related these issue:
1. https://github.com/hashicorp/memberlist/issues/264
2. https://github.com/hashicorp/memberlist/issues/226

all mentioned k8s environment

**Comment by gouhongshen** [comment]
It's been a long time since it happened again, may close.

**Comment by YANGGMM** [comment]
又发现了
failed link:https://github.com/matrixorigin/matrixone/actions/runs/7027670848/job/19122446502?pr=13068

**Comment by gouhongshen** [comment]
[TestHAKeeperCanBootstrapAndRepairShards.txt](https://github.com/matrixorigin/matrixone/files/13544833/TestHAKeeperCanBootstrapAndRepairShards.txt)

**Comment by gouhongshen** [comment]
not working on it

**Comment by gouhongshen** [comment]
not working on it

**Comment by gouhongshen** [comment]
augment the `hakeeperDefaultTimeout` config may work.

**Comment by heni02** [comment]
最近CI UT没有失败，先关闭
<img width="1413" alt="企业微信截图_58ca39d2-ba6a-4c9d-a168-9e199d6ca783" src="https://github.com/matrixorigin/matrixone/assets/113406637/4322a473-7e37-401d-b494-fbe0ea626096">
https://github.com/matrixorigin/matrixone/actions/runs/7619951914/job/20753888415?pr=14324
