### ISSUE TITLE
[Bug]: bvt failed on launch 1-cn push mode

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/4416755653/jobs/7741488834

<img width="694" alt="企业微信截图_9c117021-753a-4dfe-85d0-d5481887c35d" src="https://user-images.githubusercontent.com/77312370/225219050-6ead02cd-1413-485c-85fe-f7521e0dc163.png">

**Comment by m-schen** [comment]
暂时不是很清楚这个问题，可能与push model本身没有关系。
可能与#7748的偶现错误类似，等我修复了7748的错误后可以验证一下。

**Comment by cnutshell** [comment]
Related with #7748.

**Comment by sukki37** [comment]
Not repro
