### ISSUE TITLE
[Bug]: Access denied for user dump  for table "mo_account" does not exist when running TPCH 10G  test in push mode (occasionally)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8461]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):21b670f4615165a90f853c40e0690154b533d139
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The test tools error log is :
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/47846308/225222697-0c1cf43a-3242-42d0-9ed5-bc76ded31f46.png">

in mo log ， the same time period，the error log is：
2023/03/15 11:54:38.165705 +0800 INFO blockio/writer.go:120 [WriteEnd] {"operation": "name: ETL:sys/logs/2023/03/15/metric/1678852478_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_165041136.tae, block count: 1, size: 1299"}
[mysql] 2023/03/15 11:54:38 packets.go:37: read tcp 127.0.0.1:55748->127.0.0.1:6001: i/o timeout
[mysql] 2023/03/15 11:54:38 packets.go:37: read tcp 127.0.0.1:56304->127.0.0.1:6001: i/o timeout
2023/03/15 11:54:38.166311 +0800 INFO blockio/writer.go:120 [WriteEnd] {"operation": "name: ETL:sys/logs/2023/03/15/statement_info/1678852478_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_165194449.tae, block count: 1, size: 5240"}
[mysql] 2023/03/15 11:54:38 packets.go:37: read tcp 127.0.0.1:44172->127.0.0.1:6001: i/o timeout
2023/03/15 11:54:38.167006 +0800 ERROR log-service taskservice/task_service_cron.go:97 query cron tasks failed {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "invalid connection"}
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskService).fetchCronTasks
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/taskservice/task_service_cron.go:97
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
2023/03/15 11:54:38.167170 +0800 ERROR log-service task/task_scheduler.go:118 failed to query tasks {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "status": "Running", "error": "invalid connection"}
github.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).queryTasks
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/hakeeper/task/task_scheduler.go:118
github.com/matrixorigin/matrixone/pkg/hakeeper/task.(*scheduler).Schedule
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/hakeeper/task/task_scheduler.go:53
github.com/matrixorigin/matrixone/pkg/logservice.(*store).taskSchedule
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store_hakeeper_check.go:199
github.com/matrixorigin/matrixone/pkg/logservice.(*store).hakeeperCheck
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store_hakeeper_check.go:143
github.com/matrixorigin/matrixone/pkg/logservice.(*store).ticker
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store.go:671
github.com/matrixorigin/matrixone/pkg/logservice.(*store).startHAKeeperReplica.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/logservice/store.go:224
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
2023/03/15 11:54:38.167744 +0800 INFO frontend/util.go:414 check password succeeded connectionId 1376
[mysql] 2023/03/15 11:54:38 packets.go:37: read tcp 127.0.0.1:44174->127.0.0.1:6001: i/o timeout
2023/03/15 11:54:38.167831 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:527 task heartbeat failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "invalid connection"}
[mo-tpch-push-error.tar.gz](https://github.com/matrixorigin/matrixone/files/10976593/mo-tpch-push-error.tar.gz)

**Comment by cnutshell** [comment]
<img width="1919" alt="WeChatWorkScreenshot_c012e258-2d45-45c0-a418-47e9a430aba8" src="https://user-images.githubusercontent.com/20291742/225232268-9a80bd19-08ca-4516-9c86-7e9a43ca997d.png">

logtail server side received error from `morpc stream`, then clean morpc stream. logtail client side should re-connect and re-subscribe tables.

There are some questions to figure out:
- why morpc stream returns timeout error
- whether cn receive morpc stream cleaned event
- whether cn handle re-connect properly

**Comment by cnutshell** [comment]
With commit `21b670f4`, there should be two kinds of response sent from logtail service:

- subscription response, whose timeout comes from logtail client and takes 2min as defaults
- incremental response, whose timeout comes from dn's configuration file and takes 10sec as defaults

So I've add more detailed log information in order to figure out why morpc stream returns timeout error.

**Comment by cnutshell** [comment]
PR #8466 would close morpc stream when post-cleaning logtail service session.

**Comment by cnutshell** [comment]
Test `tpch 10G` on my local environment repeatedly:
the `mo-service` would be killed by OOM under `q17` or `q16` as a result of total 16G memory on my local.
Before mo-service killed, all the test cases passed.
Need more observation and to be confirmed by @aressu1985, thanks.

**Comment by aressu1985** [comment]
more test

**Comment by aressu1985** [comment]
fixed
