### ISSUE TITLE
[Bug]: external table scan S3 may miss files

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#8473]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 21b670f46
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

in mocloud dev env (eks: aws-us-west-2)

can not find the target statement record with statement_id, or search target statement.
<img width="932" alt="企业微信截图_930b5255-6a4d-475d-a990-aad1d4de9725" src="https://user-images.githubusercontent.com/3927687/225313439-391767d8-ae45-484e-94b6-46da69f92a80.png">

findout all mo_filepath is not include the target file: `1678881857_37353333-3735-6435-3132-303763653436_CN_899374123.tae`
![image](https://user-images.githubusercontent.com/3927687/225313789-fb6f354f-3165-4d5a-ae58-a95fcb5c5220.png)

query all `__mo_filepath`, not including the target file.

![image](https://user-images.githubusercontent.com/3927687/225314604-20a01768-4fb7-4ace-ab38-ac74cdf9c66f.png)

### Expected Behavior

external file needs to scan all files in target path.

**Comment by reusee** [comment]
The Tencent cloud object storage does not support ListObjectsV2 of the aws s3 SDK.
I'll change the file service to use ListObjects instead.
