### ISSUE TITLE
[Bug]: mo panic by internal error: panic interface conversion: interface {} is []int8, not []uint16 when running loading 200 colums data

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8477]
### Is there an existing issue for the same bug?

- [X] #8486

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0a03c019f832c9656d7081bd4391b65a726d64ba
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023/03/16 02:32:22.313672 +0800 INFO rpc/handle.go:105 HandleCommit end : 0B7C6B87927443F09C4D7C429993848D

2023/03/16 02:32:22.313941 +0800 INFO frontend/util.go:396 query trace status {"connection_id": 1001, "statement": "commit", "status": "success", "span": {"trace_id": "b9b0ab0c-c35f-11ed-bc94-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1001"}
2023/03/16 02:32:22.348094 +0800 INFO blockio/writer.go:120 [WriteEnd] {"operation": "name: 80002c660000000000042845.seg, block count: 1, size: 14832759"}
2023/03/16 02:32:22.498483 +0800 ERROR log-service.lockservice lockservice/lock_table_keeper.go:187 all local lock table invalid {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
github.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).doKeepLockTableBind
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_keeper.go:187
github.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).keepLockTableBind
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_keeper.go:79
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
2023/03/16 02:32:22.612393 +0800 INFO blockio/writer.go:116 [WriteEnd] {"operation": "80002c670000000000042845.seg", "operand": "[Size=0]"}
2023/03/16 02:32:22.612394 +0800 INFO blockio/writer.go:116 [WriteEnd] {"operation": "80002c680000000000042845.seg", "operand": "[Size=0]"}
2023/03/16 02:32:22.613197 +0800 ERROR vm/vm.go:57 error: internal error: panic interface conversion: interface {} is []int8, not []uint16:
runtime.panicdottypeE
        /usr/local/go/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/tools.go:40
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeblock.(*Argument).Split
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergeblock/types.go:65
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeblock.Call
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/colexec/mergeblock/mergeblock.go:44
github.com/matrixorigin/matrixone/pkg/vm.Run
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/pipeline/pipeline.go:151
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/scope.go:132
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/compile/compile.go:149
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3311
github.com/matrixorigin/2023/03/16 02:32:36.592671 +0800 ERROR log-service.lockservice lockservice/lock_table_keeper.go:187 all local lock table invalid {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf"}
github.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).doKeepLockTableBind
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_keeper.go:187
github.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).keepLockTableBind
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/lockservice/lock_table_keeper.go:79
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
2023/03/16 02:32:36.649101 +0800 INFO frontend/util.go:396 query trace {"connection_id": 1010, "query": "use mo_task", "session_info": "connectionId 1010"}
2023/03/16 02:32:36.650421 +0800 INFO frontend/util.go:411 User 2a0493b8-3b36-4334-a91c-b053363d06b5 change database from [mo_task] to [mo_task] connectionId 1010
2023/03/16 02:32:36.650483 +0800 INFO frontend/util.go:396 query trace status {"connection_id": 1010, "statement": "use mo_task", "status": "success", "span": {"trace_id": "c23dc7f1-c35f-11ed-bc94-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 1010"}
2023/03/16 02:32:36.650528 +0800 INFO frontend/util.go:396 query trace {"connection_id": 1010, "query": "show tables", "session_info": "connectionId 1010"}
2023/03/16 02:32:36.652549 +0800 INFO frontend/util.go:411 time of Exec.Build : 1.978982ms connectionId 1010
2023/03/16 02:32:36.652911 +0800 INFO frontend/util.go:411 rowCount 2
time of getDataFromPipeline : 5.845µs
processBatchTime 4.37µs
row2colTime 0s
restTime(=totalTime - row2colTime) 5.845µs
protoStats flushCount 0 writeCount 1

**Comment by aressu1985** [comment]
[mo-load-data-panic.tar.gz](https://github.com/matrixorigin/matrixone/files/10986098/mo-load-data-panic.tar.gz)

**Comment by aressu1985** [comment]
This issue is caused by that the data disk has no space left, but need to optimize the panic information

**Comment by JackTan25** [comment]
I will check this later, please see my schedule

**Comment by JackTan25** [comment]
I will check this later, please see my schedule

**Comment by JackTan25** [comment]
I will check this later, please see my schedule

**Comment by JackTan25** [comment]
no time now

**Comment by JackTan25** [comment]
no time now

**Comment by JackTan25** [comment]
I will check next week

**Comment by aressu1985** [comment]
fixed
