### ISSUE TITLE
[Bug]: TestCloseLocalLockTableWithBlockedWaiter failed

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#8479]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CI failed https://github.com/matrixorigin/matrixone/actions/runs/4428984764

**Comment by XuPeng-SH** [comment]
CI failed https://github.com/matrixorigin/matrixone/actions/runs/4444192356/jobs/7802167548?pr=8506

**Comment by zhangxu19830126** [comment]
fixed
