### ISSUE TITLE
[Bug]: cn killed by oom during running tpch 10g all queries for 5 times on eks 2*cn 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8481]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0a03c01
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The cn crash :
<img width="574" alt="image" src="https://user-images.githubusercontent.com/47846308/225503114-bebf0bb2-04e5-49cf-987e-ba745dec15a5.png">

[Wed Mar 15 18:41:02 2023] pglazyfreed 0
[Wed Mar 15 18:41:02 2023] Tasks state (memory values in pages):
[Wed Mar 15 18:41:02 2023] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[Wed Mar 15 18:41:02 2023] [   5434] 65535  5434      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   6563]     0  6563     2889      684    73728        0          -997 bash
[Wed Mar 15 18:41:02 2023] [   6648]     0  6648   191482    15866   249856        0          -997 aws-k8s-agent
[Wed Mar 15 18:41:02 2023] [   6649]     0  6649     1059      193    53248        0          -997 tee
[Wed Mar 15 18:41:02 2023] [   5435] 65535  5435      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   5911]     0  5911   187695    12034   212992        0          -998 kube-proxy
[Wed Mar 15 18:41:02 2023] [   5581] 65535  5581      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   6566]     0  6566   189089    12727   221184        0           999 kruise-daemon
[Wed Mar 15 18:41:02 2023] [   6951]     0  6951      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   7235]     0  7235   190919     8814   204800        0          -997 aws-ebs-csi-dri
[Wed Mar 15 18:41:02 2023] [   7513]     0  7513   181345     3494   131072        0          -997 csi-node-driver
[Wed Mar 15 18:41:02 2023] [   7653]     0  7653   179017     4090   131072        0          -997 livenessprobe
[Wed Mar 15 18:41:02 2023] [   8332] 65535  8332      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   8592]     0  8592 16513882 15328664 123731968        0           187 mo-service
[Wed Mar 15 18:41:02 2023] [   5433] 65534  5433      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   5908] 65534  5908   180048     5474   143360        0          1000 node_exporter
[Wed Mar 15 18:41:02 2023] [   7313] 65535  7313      242        1    28672        0          -998 pause
[Wed Mar 15 18:41:02 2023] [   7894]     0  7894    92216     7802   196608        0          1000 fluent-bit
[Wed Mar 15 18:41:02 2023] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=8c4d9fedf1a0fef52499f36009e0d6a77d239a16654ef75b81a28287e0bfe8fd,mems_allowed=0,oom_memcg=/kubepods,task_memcg=/kubepods/burstable/pod54b9911f-271b-472f-84d6-d8b91e4b854a/8c4d9fedf1a0fef52499f36009e0d6a77d239a16654ef75b81a28287e0bfe8fd,task=mo-service,pid=8592,uid=0
[Wed Mar 15 18:41:02 2023] Memory cgroup out of memory: Killed process 8592 (mo-service) total-vm:66055528kB, anon-rss:61262636kB, file-rss:52020kB, shmem-rss:0kB, UID:0 pgtables:120832kB oom_score_adj:187
root@nightly-regression-dis-tp-cn-0:/# exitcommand terminated with exit code 137

The tpch test tools log:
2023-03-15 18:25:37 Now start to compare query result for [report/TPCH_10/q2.txt,golden/TPCH_10/q2.txt]
2023-03-15 18:25:37 The query q2  has be executed successfully,and cost: 4747

2023-03-15 18:25:37 Now start to execute the query queries/q20.sql,please wait.....

2023-03-15 18:25:47 Now start to compare query result for [report/TPCH_10/q20.txt,golden/TPCH_10/q20.txt]
2023-03-15 18:25:47 The query q20  has be executed successfully,and cost: 10566

2023-03-15 18:25:47 Now start to execute the query queries/q21.sql,please wait.....
2023-03-15 18:26:07 The query q21  has failed to  be executed.

ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query

2023-03-15 18:26:07 Now start to execute the query queries/q22.sql,please wait.....
2023-03-15 18:26:07 The query q22  has failed to  be executed.

ERROR 2003 (HY000): Can't connect to MySQL server on '1[72](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4428357658/jobs/7770219315#step:15:73).20.29.43:6001' (111)

2023-03-15 18:26:07 Now start to execute the query queries/q3.sql,please wait.....
2023-03-15 18:26:07 The query q3  has failed to  be executed.

ERROR 2003 (HY000): Can't connect to MySQL server on '172.20.29.43:6001' (111)

2023-03-15 18:26:07 Now start to execute the query queries/q4.sql,please wait.....

**Comment by LeftHandCold** [comment]
exec "tpch - q all". 
#8435  will cause 16g more memory to be allocated.

**Comment by LeftHandCold** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/14086886/225555015-1883cb5b-86f1-41a5-a64b-dcb033cfe940.png">

**Comment by LeftHandCold** [comment]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/14086886/225858855-d82fbc90-b7e3-40a8-b0a7-3995222e4f23.png">
run tpch on eks. goetty will not release memory

**Comment by LeftHandCold** [comment]
It may be due to incorrect operator configuration, resulting in frequent errors in lockservice

**Comment by zhangxu19830126** [comment]
According to the log and analysis, goetty takes up too much memory because the internal communication of lockservice is caused by configuration problems. Wait for @aylei  to solve the configuration modification of opeartor and check the situation.

**Comment by aylei** [comment]
> According to the log and analysis, goetty takes up too much memory because the internal communication of lockservice is caused by configuration problems. Wait for @aylei to solve the configuration modification of opeartor and check the situation.

Supported in https://github.com/matrixorigin/matrixone-operator/pull/305

**Comment by aylei** [comment]
Did we reproduce this after the fix was deployed? @zhangxu19830126 @aressu1985 

> > According to the log and analysis, goetty takes up too much memory because the internal communication of lockservice is caused by configuration problems. Wait for @aylei to solve the configuration modification of opeartor and check the situation.
> 
> Supported in [matrixorigin/matrixone-operator#305](https://github.com/matrixorigin/matrixone-operator/pull/305)

**Comment by zhangxu19830126** [comment]
cn There is a problem with using tcp to link the current node when running pipeline, which causes link leakage due to the maximum number of connections being 10W. @m-schen

**Comment by zhangxu19830126** [comment]
fixed

**Comment by zhangxu19830126** [comment]
@aressu1985

**Comment by aressu1985** [comment]
fxied
