### ISSUE TITLE
[Bug]: leader cannot be elected in logservice 

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#8483]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

leader cannot be elected because replcia ID and address are inconsist. 
[dn01.txt](https://github.com/matrixorigin/matrixone/files/10986296/dn01.txt)
[log10.log](https://github.com/matrixorigin/matrixone/files/10986297/log10.log)
[log20.log](https://github.com/matrixorigin/matrixone/files/10986298/log20.log)

**Comment by aylei** [comment]
[log0.txt](https://github.com/matrixorigin/matrixone/files/10997327/log0.txt)
[log1.txt](https://github.com/matrixorigin/matrixone/files/10997328/log1.txt)
[log2.txt](https://github.com/matrixorigin/matrixone/files/10997329/log2.txt)

**Comment by volgariver6** [comment]
I am working on it.

**Comment by domingozhang** [comment]
related bugs:
#8239 
#8421

**Comment by volgariver6** [comment]
fixed by #8617.

**Comment by volgariver6** [comment]
this issue is ok to test.

**Comment by aressu1985** [comment]
@heni02 pls verify this issue

**Comment by heni02** [comment]
Not easy to reproduce,Unable to verify at this time, change the status to holding first

**Comment by aressu1985** [comment]
closed
