### ISSUE TITLE
[Bug]: modump query result execute error

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#8484]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 190c3b0e5f0fbbd92ef469f9cf54e0b28ca84ffc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> desc t1;
+-------+---------+------+------+---------+-------+---------+
| Field | Type    | Null | Key  | Default | Extra | Comment |
+-------+---------+------+------+---------+-------+---------+
| a     | INT(32) | YES  |      | NULL    |       |         |
+-------+---------+------+------+---------+-------+---------+
1 row in set (0.04 sec)

mysql> select a from t1;
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.02 sec)

mysql> select last_query_id();
+--------------------------------------+
| last_query_id()                      |
+--------------------------------------+
| fcc4916c-c3ab-11ed-8d84-5ad2460dea4f |
+--------------------------------------+
1 row in set (0.02 sec)

mysql> MODUMP QUERY_RESULT 'fcc4916c-c3ab-11ed-8d84-5ad2460dea4f' INTO 'etl:/Users/Prinz/03testrepo/query_result';
ERROR 20101 (HY000): internal error: panic interface conversion: interface {} is nil, not []types.Varlena: 
runtime.panicdottypeE
        /usr/local/go/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).GetStringAt
        /Users/Prinz/02matrixone/matrixone/pkg/container/vector/vector.go:148
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).GetQueryResultMeta
        /Users/Prinz/02matrixone/matrixone/pkg/frontend/session.go:2426
github.com/matrixorigin/matrixone/pkg/frontend.getResultFiles

**Comment by tianyahui-python** [comment]
Find a new bug @taofengliu 

<img width="1609" alt="截屏2023-03-20 22 31 06" src="https://user-images.githubusercontent.com/39303074/226371723-490fdb7f-0d9d-4afa-81b4-57900180ca92.png">

**Comment by tianyahui-python** [comment]
bug unsolved @taofengliu 

<img width="1501" alt="截屏2023-03-20 22 34 46" src="https://user-images.githubusercontent.com/39303074/226372580-1e9de1bf-69cc-4ff1-948d-49ddb53d32b7.png">

**Comment by taofengliu** [comment]
I'm not working on this

**Comment by tianyahui-python** [comment]
mysql> set global save_query_result=on;
Query OK, 0 rows affected (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_task            |
| information_schema |
| mysql              |
| system_metrics     |
| system             |
| mo_catalog         |
+--------------------+
6 rows in set (0.10 sec)

mysql> select last_query_id();
+--------------------------------------+
| last_query_id()                      |
+--------------------------------------+
| 2f13fc18-cddc-11ed-a441-f6efd850eccf |
+--------------------------------------+
1 row in set (0.08 sec)

mysql> select * from meta_scan('2f13fc18-cddc-11ed-a441-f6efd850eccf') as u;
+--------------------------------------+----------------+------------+---------+---------------------------------------------------------------------+---------------------+--------------------+-------------+---------+---------------------+----------------------------------+
| query_id                             | statement      | account_id | role_id | result_path                                                         | create_time         | result_size        | tables      | user_id | expired_time        | ColumnMap                        |
+--------------------------------------+----------------+------------+---------+---------------------------------------------------------------------+---------------------+--------------------+-------------+---------+---------------------+----------------------------------+
| 2f13fc18-cddc-11ed-a441-f6efd850eccf | show databases |          0 |       0 | SHARED:/query_result/sys_2f13fc18-cddc-11ed-a441-f6efd850eccf_1.blk | 2023-03-29 10:48:28 | 0.0001373291015625 | mo_database |       1 | 2023-03-30 10:48:28 | mo_database.Database -> Database |
+--------------------------------------+----------------+------------+---------+---------------------------------------------------------------------+---------------------+--------------------+-------------+---------+---------------------+----------------------------------+
1 row in set (0.01 sec)

mysql> select * from meta_scan('2f13fc18-cddc-11ed-a441-f6efd850eccf') as u;
Empty set (0.02 sec)

mysql> select * from meta_scan('2f13fc18-cddc-11ed-a441-f6efd850eccf') as u;
Empty set (0.00 sec)

mysql>

**Comment by tianyahui-python** [comment]
commit id: 7120770b819ec6ec000c2e4ffc0af24fa4c9043e

**Comment by tianyahui-python** [comment]
@taofengliu bug unsolved

**Comment by taofengliu** [comment]
No repro now. Recheck, please. @tianyahui-python 
![2023-03-29 11-07-49 的屏幕截图](https://user-images.githubusercontent.com/81315978/228418186-41c258d7-232e-4304-b36e-0385ebee707b.png)

**Comment by tianyahui-python** [comment]
pass-test @lacrimosaprinz
