### ISSUE TITLE
[Bug]: unique index name and secondary index name are same not reported error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8488]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2d5a3ab3fb0c7ca944db799f3693d12c49ff2276
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The expected result is that the error should be reported Duplicate key name
MO：
![image](https://user-images.githubusercontent.com/113406637/225536520-91584dd4-245d-4d3a-adff-aed062ab723e.png)

mysql：
![image](https://user-images.githubusercontent.com/113406637/225537123-37c6b535-1cdc-4b44-b388-7acbccc5e345.png)

### Steps to Reproduce

```Markdown
CREATE TABLE  indup_04( `id` INT, `act_name` VARCHAR(20) NOT NULL, `spu_id` VARCHAR(30) NOT NULL, `uv`  BIGINT NOT NULL, `update_time` date default '2020-10-10' COMMENT 'lastest time', PRIMARY KEY ( `id`, `act_name`), unique key idx_spu_id (spu_id),  KEY idx_spu_id(uv) );
```

**Comment by qingxinhome** [comment]
This issue has been resolved, pr has been merged, please test @heni02 @daviszhen

**Comment by heni02** [comment]
confirm,closed
commit id:dc0b6d294203d9c2c271a55032ba98341868856e
![image](https://user-images.githubusercontent.com/113406637/227086964-0e3e49ad-6c29-4b86-a9ee-30d1313f0131.png)
