### ISSUE TITLE
[Bug]: insert into table select constant duplicate key result error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8494]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):114beff401214c1cd354f423690738075653c836
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql:insert into indup_02 select 1,'banana','lower',NULL on duplicate key update col1=col1*10;
mo:
![image](https://user-images.githubusercontent.com/113406637/225567217-80c6d706-f95e-4974-b494-7dbb0e82ac46.png)

mysql:
![image](https://user-images.githubusercontent.com/113406637/225566747-6aa037b0-534e-4845-91e0-cb11a50e1819.png)

### Expected Behavior

CREATE TABLE IF NOT EXISTS indup_02(
    col1 INT ,
    col2 VARCHAR(20) NOT NULL,
    col3 VARCHAR(30) NOT NULL,
    col4  BIGINT default 30,
    PRIMARY KEY ( col1 )
);
insert into indup_02 values (1,'apple','left',NULL),(2,'bear','right',1000);
select * from indup_02;
insert into indup_02 select 1,'banana','lower',NULL on duplicate key update col1=col1*10;
select * from indup_02;

**Comment by ouyuanning** [comment]
seems fixed by https://github.com/matrixorigin/matrixone/pull/8600

**Comment by heni02** [comment]
confirm，closed
commit ID：6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
![image](https://user-images.githubusercontent.com/113406637/227862674-4570a4b9-b922-428c-beff-85c5ec103843.png)
