### ISSUE TITLE
[Bug]: server crash

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8499]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters: 106.55.245.253
- OS type:
- Others:
```

### Actual Behavior

mysql> create table pkt(pk int not null auto_increment, i int, j int, k int, s varchar(200), primary key (pk));
mysql> insert into pkt values (null, 1, 2, 3, 'foobarzoo');
mysql> insert into pkt select null, i, j, k, s from pkt;
...  keep on doing this for a few times

mysql> insert into pkt select null, i, j, k, s from pkt;
Query OK, 65536 rows affected (0.35 sec)

mysql> insert into pkt select null, i, j, k, s from pkt;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '106.55.245.253:6001' (111)
ERROR:
Can't connect to the server

**Comment by triump2020** [comment]
Fixed.

**Comment by aressu1985** [comment]
on test

**Comment by aressu1985** [comment]
fixed
