### ISSUE TITLE
[Bug]: BVT panic

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#8525]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023-03-18 11:03:09 ERROR Executor:193 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/dml/insert/insert.test][row:251][insert into t select c,c from temp;] was executed failed, con[id=0, user=dump, ***
[202](https://github.com/matrixorigin/matrixone/actions/runs/4455022415/jobs/7824576583?pr=8518#step:9:203)3-03-18 11:03:09 ERROR Executor:195 - [EXPECT RESULT]:
null
2023-03-18 11:03:09 ERROR Executor:196 - [ACTUAL RESULT]:
internal error: panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex
	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memorytable.VectorAt
	/home/runner/work/matrixone/matrixone/head/pkg/txn/storage/memorystorage/memorytable/vector_utils.go:85
github.com/matrixorigin/matrixone/pkg/txn/storage/memorystorage/memorytable.NewBatchIter.func1
	/home/runner/work/matrixone/matrixone/head/pkg/txn/storage/memorystorage/memorytable/batch_utils.go:39
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).checkPrimaryKey
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/disttae/txn.go:168
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).WriteBatch
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/disttae/txn.go:139
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Write
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/disttae/txn_table.go:438
github.com/matrixorigin/matrixone/pkg/sql/colexec/insert.Call
	/home/runner/work/matrixone/matrixone/head/pkg/sql/colexec/insert/insert.go:74
github.com/matrixorigin/matrixone/pkg/vm.Run
	/home/runner/work/matrixone/matrixone/head/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/home/runner/work/matrixone/matrixone/head/pkg/vm/pipeline/pipeline.go:151
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/scope.go:132
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Insert
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/dml.go:77
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/home/runner/work/matrixone/matrixone/head/pkg/sql/compile/compile.go:201
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:3315
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/mysql_cmd_executor.go:3703
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/home/runner/work/matrixone/matrixone/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.2022121213[203](https://github.com/matrixorigin/matrixone/actions/runs/4455022415/jobs/7824576583?pr=8518#step:9:204)7-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.202[212](https://github.com/matrixorigin/matrixone/actions/runs/4455022415/jobs/7824576583?pr=8518#step:9:213)1[213](https://github.com/matrixorigin/matrixone/actions/runs/4455022415/jobs/7824576583?pr=8518#step:9:214)2037-abf2d4c05484/application.go:344
runtime.goexit
	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/asm_amd64.s:1594

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/6964ac856150ba1f9fb97feb8b4cfc9d6da48e98
