### ISSUE TITLE
[Bug]: tpcc 500warehouses1000terminals cn cash

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8527]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9f544a1 image：temp-nightly-9f544a1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc 500 warehouses 500terminals  executed successfully，but 1000terminals cn crashed
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4455211181/jobs/7824901946
<img width="1021" alt="企业微信截图_98f8a2b7-ba73-4c5a-b6fd-3b2fc0624f64" src="https://user-images.githubusercontent.com/113406637/226108896-94f1213d-8be4-4250-988e-fd7eeb593873.png">
<img width="796" alt="企业微信截图_33554a5b-dc52-4920-8c8f-e979e489a7aa" src="https://user-images.githubusercontent.com/113406637/226108911-5b698d9a-fb94-4c93-9a75-a2210f71006d.png">
cn part of log：the complete log see the file
{"level":"ERROR","time":"2023/03/18 12:11:24.561236 +0000","name":"cn-service.lockservice","caller":"lockservice/lock_table_keeper.go:179","msg":"failed to keep lock table bind","uuid":"00000000-0000-0000-0000-200000000000","service":"00000000-0000-0000-0000-200000000000","error":"can not connect to remote backend","stacktrace":"github.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).doKeepLockTableBind\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_keeper.go:179\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).keepLockTableBind\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_keeper.go:81\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}
{"level":"INFO","time":"2023/03/18 12:11:24.827909 +0000","caller":"frontend/util.go:411","msg":"check password succeeded connectionId 2074"}
{"level":"INFO","time":"2023/03/18 12:11:24.836115 +0000","caller":"frontend/util.go:396","msg":"query trace","connection_id":2074,"query":"use mo_task","session_info":"connectionId 2074"}
{"level":"INFO","time":"2023/03/18 12:11:25.561694 +0000","name":"cn-service.lockservice","caller":"morpc/backend.go:688","msg":"start connect to remote","uuid":"00000000-0000-0000-0000-200000000000","remote":"127.0.0.1:22002","backend-id":"87d5293a-3f83-4df2-b875-f519dd9943bd"}
{"level":"ERROR","time":"2023/03/18 12:11:25.564857 +0000","name":"cn-service.lockservice","caller":"morpc/backend.go:696","msg":"init remote connection failed, retry later","uuid":"00000000-0000-0000-0000-200000000000","remote":"127.0.0.1:22002","backend-id":"87d5293a-3f83-4df2-b875-f519dd9943bd","error":"dial tcp4 127.0.0.1:22002: connect: connection refused","stacktrace":"github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).resetConn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:696\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.NewRemoteBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:205\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*goettyBasedBackendFactory).Create\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:811\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).doCreate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:456\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).createBackendLocked\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:444\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).createBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:429\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).getBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:239\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).Send\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:170\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*client).AsyncSend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:121\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*client).Send\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/rpc.go:69\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).doKeepLockTableBind\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_keeper.go:177\ngithub.com/matrixorigin/matrixone/pkg/lockservice.(*lockTableKeeper).keepLockTableBind\n\t/go/src/github.com/matrixorigin/matrixone/pkg/lockservice/lock_table_keeper.go:81\ngithub.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/stopper/stopper.go:259"}

**Comment by heni02** [comment]
cn log: [tpcc_500w_1000t_cnlog.log](https://github.com/matrixorigin/matrixone/files/11008629/tpcc_500w_1000t_cnlog.log)

**Comment by nnsgmsone** [comment]
i will deal the memory first;

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
把fd limit调大一些。。

**Comment by heni02** [comment]
now ，it is not has this problem，closed
commit id: 3a8fe63b46921efaea47a0e90743d4d7c558a6cb
regression job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/6327848028/job/17184798072
<img width="1081" alt="企业微信截图_939c6586-4cf4-4cae-95fa-e42f8e134cda" src="https://github.com/matrixorigin/matrixone/assets/113406637/061679c0-8a21-4f0f-8be4-3804a999e007">
