### ISSUE TITLE
[Feature Request]: writing permission control for select into outfile 

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8544]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

Existing select into outfile has no writing permission control. User can wring in their know path in remote servers.
this needs a control policy:
1. add a parameter to restrict the file path
2. Use file path permission of OS level

either is fine

**Comment by daviszhen** [comment]
@jianwan0214 说暂时不做

**Comment by lacrimosaprinz** [comment]
doc edited:
https://github.com/matrixorigin/matrixorigin.io.cn/pull/653
https://github.com/matrixorigin/matrixorigin.io/pull/498

**Comment by lacrimosaprinz** [comment]
dev design doc refer to:https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUjaM2wf9yQTujG39e5V?scode=AJsA6gc3AA88f8FhmtALQAjwY-ACU

**Comment by tianyahui-python** [comment]
Only the local part is implemented, local part test done

**Comment by tianyahui-python** [comment]
link bug: https://github.com/matrixorigin/matrixone/issues/11350

**Comment by tianyahui-python** [comment]
test done
