### ISSUE TITLE
[Bug]: performance: tpcc 100warehouse1000terminals test tpmc9.89, tpmtotal231.84

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8550]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9f544a1 image:temp-nightly-9f544a1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc test on eks environment cn1 dn1 distribution，tpcc 100 warehouses 1000terminals tpmc9.89, tpmtotal231.84
job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4466165728/jobs/7844084283
![image](https://user-images.githubusercontent.com/113406637/226316164-15149eed-a296-4210-ad50-1991bbc34ac8.png)
![image](https://user-images.githubusercontent.com/113406637/226316343-38b6e4bb-4575-4113-83cc-60c3de92721d.png)

and  tpcc 500warehouse500terminals test tpmc：0.56 tpmtotal：66.0
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4466577943/jobs/7845426037
![image](https://user-images.githubusercontent.com/113406637/226317110-cf9d9994-097e-4687-94e0-4c5342b28bd2.png)

**Comment by nnsgmsone** [comment]
i will deal the memory first;

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个。

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891%E5%9C%A8%E5%A4%84%E7%90%86%E8%BF%99%E4%B8%AA%E3%80%82

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891在处理这个

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891%E5%9C%A8%E5%A4%84%E7%90%86%E8%BF%99%E4%B8%AA

**Comment by nnsgmsone** [comment]
等处理完https://github.com/matrixorigin/matrixone/issues/7891%E5%9C%A8%E5%A4%84%E7%90%86%E8%BF%99%E4%B8%AA

**Comment by nnsgmsone** [comment]
@heni02  tpmc达到多少是预期呢

**Comment by aressu1985** [comment]
@nnsgmsone pls see the objective of tp for 0.8 version

**Comment by nnsgmsone** [comment]
等plan重构后处理这个问题
