### ISSUE TITLE
[Bug]: Collecting sql is inconsistent with executing SQL

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#8555]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):  a3ebe26ea09128f01c2a5f38d557b176f854bdec
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1653" alt="截屏2023-03-20 22 40 17" src="https://user-images.githubusercontent.com/39303074/226377349-5cc0bbd0-771a-41a6-a4b1-15db5d2ab860.png">

**Comment by nnsgmsone** [comment]
请首先检测写入的sql对不对

**Comment by nnsgmsone** [comment]
泽雄先确认一下收到的sql对不对

**Comment by xzxiong** [comment]
@taofengliu  there is parsed error.
```
parsers.SplitSqlBySemicolon("abc") == "ab"
```
![image](https://user-images.githubusercontent.com/3927687/226815863-c5705e9f-76c1-461c-bb9a-fa0e68c85afe.png)

**Comment by aressu1985** [comment]
@tianyahui-python pls regret this issue and update the status

**Comment by tianyahui-python** [comment]
<img width="1316" alt="截屏2023-03-27 17 12 56" src="https://user-images.githubusercontent.com/39303074/227897238-a8ac6751-267e-4a96-8795-8f5161962a83.png">
