### ISSUE TITLE
Ambiguous error when 'DIV' and '/' operators divided by the same number

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#857]
#### Can be reproduced ?
Yes

#### Steps:
CREATE TABLE t1 (spID int,userID int,score smallint);
INSERT INTO t1 VALUES (1,1,1);
INSERT INTO t1 VALUES (2,2,2);
INSERT INTO t1 VALUES (2,1,4);
INSERT INTO t1 VALUES (3,3,3);
INSERT INTO t1 VALUES (1,1,5);
INSERT INTO t1 VALUES (4,6,10);
INSERT INTO t1 VALUES (5,11,99);

mysql> select  userID/2.3,  userID DIV 2.3 from t1  ;
mysql> select  userID/2,  userID DIV 2 from t1  ;

#### Expected behavior:
mysql> select  userID/2.3,  userID DIV 2.3 from t1  ;
+------------+----------------+
| userID/2.3 | userID DIV 2.3 |
+------------+----------------+
|     0.4348 |              0 |
|     0.8696 |              0 |
|     0.4348 |              0 |
|     1.3043 |              1 |
|     0.4348 |              0 |
|     2.6087 |              2 |
|     4.7826 |              4 |
+------------+----------------+
7 rows in set (0.00 sec)

#### Actual behavior:
mysql> select  userID/2.3,  userID DIV 2.3 from t1  ;
ERROR 1105 (HY000): unknown error:[42P09]alias 'userID / 2.3' is ambiguous
mysql> select  userID/2,  userID DIV 2 from t1  ;
ERROR 1105 (HY000): unknown error:[42P09]alias 'userID / 2' is ambiguous

FYI, the query can run successfully if the two operators with different divisors, such as:
mysql> select  userID/2,  userID DIV 2.3 from t1  ;
+------------+--------------+
| userID / 2 | userID / 2.3 |
+------------+--------------+
|          0 |            0 |
|          1 |            1 |
|          0 |            0 |
|          1 |            1 |
|          0 |            0 |
|          3 |            3 |
|          5 |            5 |
+------------+--------------+
7 rows in set (0.02 sec)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): commit 3aebaf54b5dac7cba3c27af6f12ac949dca6a95b
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by nnsgmsone** [comment]
solved

**Comment by lignay** [comment]
Retested on 0ca539490e8f5b8adce6210d19ef53d0f83d8a81
```
mysql> select userID/2.3, userID DIV 2.3 from t1 ;
+------------+----------------+
| userID / 2 | userID div 2.3 |
+------------+----------------+
|     0.5000 |              0 |
|     1.0000 |              0 |
|     0.5000 |              0 |
|     1.5000 |              1 |
|     0.5000 |              0 |
|     3.0000 |              2 |
|     5.5000 |              4 |
+------------+----------------+
7 rows in set (0.02 sec)

mysql> select userID/2, userID DIV 2 from t1 ;
+------------+--------------+
| userID / 2 | userID div 2 |
+------------+--------------+
|     0.5000 |            0 |
|     1.0000 |            1 |
|     0.5000 |            0 |
|     1.5000 |            1 |
|     0.5000 |            0 |
|     3.0000 |            3 |
|     5.5000 |            5 |
+------------+--------------+
7 rows in set (0.03 sec)
```

**Comment by m-schen** [comment]
verified at v0.4.0. it has been fixed.
