### ISSUE TITLE
[Subtask]: Expand the AllocateID function

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#8573]
### Parent Issue

issue #7884 

### Detail of Subtask

According to Mo Chen's suggestion, the function functions are as follows：

// key: The key parameter corresponds to different namespace categories, such as tables, indexes, databases, etc
// ctx: context.Context
func (c *managedHAKeeperClient) AllocateIDByKey(key string, ctx context.Context) (uint64, error);

**Comment by qingxinhome** [comment]
@nnsgmsone

**Comment by volgariver6** [comment]
pr has been merged.

**Comment by qingxinhome** [comment]
This requirement has been implemented, thank you very much. @zhangxu19830126  @volgariver6
