### ISSUE TITLE
[Feature Request]: Window Function

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#8590]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1. Count Window
    Over Window （传统数据库的标准开窗）
2. Time Window：filling
    Tumble Window（滚动窗口：固定大小、没有重叠）
    Sliding Window（滑动窗口：固定大小、有步数、可以重叠）
3. Session Window（会话窗口：按心跳划分会话，会话内计算）
4. Event Window（事件窗口：事件窗口根据开始条件和结束条件来划定窗口）
5. Status Window（状态窗口：使用整数（布尔值）或字符串来标识产生记录时候设备的状态量。产生的记录如果具有相同的状态量数值则归属于同一个状态窗口，数值改变后该窗口关闭。）

PRD：https://doc.weixin.qq.com/doc/w3_AZUAugYIAOcINf5bVCpQh0j52THBs?scode=AJsA6gc3AA8grqmatuAZUAugYIAOc

**Comment by lacrimosaprinz** [comment]
What new window functions will be added in version 1.1？

**Comment by iamlinjunhong** [comment]
doc: https://github.com/iamlinjunhong/docs/blob/tw/design/time%20window.md

**Comment by Ariznawlll** [comment]
Time Window：filling
Tumble Window（滚动窗口：固定大小、没有重叠）
Sliding Window（滑动窗口：固定大小、有步数、可以重叠）

test done.
