### ISSUE TITLE
[Bug]: Need to clean up the "data-dir" directory first when switching branches and launching MO

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#8603]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixorigin.io.cn/pull/289

When I switch branches and launch the MO server, I must first clean up the "data-dir" directory; otherwise, there will be panic during the build and launch.

**Comment by sukki37** [comment]
it's not a bug
