### ISSUE TITLE
Unable to refer to any column that was set earlier in a value list when INSERT

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#861]
#### Can be reproduced ?
Yes

#### Steps:
create table names(id int PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255) UNIQUE,age int);
insert into names value(1, 'Bob', id*3);
insert into names(id, name, age) values(1, 'Bob', id*3);

#### Expected behavior:
mysql> insert into names value(1, 'Bob', id*3);
Query OK, 1 row affected (0.01 sec)

#### Actual behavior:
mysql> insert into names value(1, 'Bob', id*3);
ERROR 1105 (HY000): unknown error:[42000]'' is not support now

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 3aebaf54b5dac7cba3c27af6f12ac949dca6a95b
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by JinHai-CN** [comment]
Won't fix in v0.2.0.
