### ISSUE TITLE
[Bug]: System db loss

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8614]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:017b6637fb4e5ae1032b12e18f0d4fcb914c9e44
sudo ./mo-service -launch ./etc/launch-tae-multi-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/226857376-f734f900-7213-4e1c-ae58-ef8a3689d52a.png)

### Expected Behavior

<img width="401" alt="企业微信截图_1982e9cf-a2d8-4813-8aa9-2e8c218a1db9" src="https://user-images.githubusercontent.com/108530700/226858078-6d64b7d0-2e20-4873-945f-e78fc5e20790.png">

### Steps to Reproduce

```Markdown
git clone https://github.com/matrixorigin/matrixone.git
cd matrixone/etc/launch-tae-multi-CN-tae-DN
vim cn1.toml 加入 [cn.frontend] lowerCaseTableNames = "0"
vim cn2.toml 加入 [cn.frontend] lowerCaseTableNames = "0"

make build
show databases;
```

**Comment by taofengliu** [comment]
Can not reproduce.
Another bug was found: initialization of system views fails when lowerCaseTableNames = "0".

**Comment by Ariznawlll** [comment]
test done！
