### ISSUE TITLE
[Bug]: Disk Cache sometimes can not take effect for tpch queries

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8616]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):017b6637fb4e5ae1032b12e18f0d4fcb914c9e44
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

On eks, sometimes the cost of the same tpch query is much more than cost of last time。
<img width="640" alt="image" src="https://user-images.githubusercontent.com/47846308/226866851-58c0d3d3-30e8-4151-bf02-a364a61e9f21.png">

the query plan of the most cost is as following:

{"code": 0, "message": "", "steps": [{"description": "", "graphData": {"edges": [{"dst": "4", "id": "E3", "output": 4, "src": "3", "unit": "count"}, {"dst": "3", "id": "E2", "output": 4, "src": "2", "unit": "count"}, {"dst": "2", "id": "E1", "output": 4, "src": "1", "unit": "count"}, {"dst": "1", "id": "E0", "output": 2941823, "src": "0", "unit": "count"}], "global": {"statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO Byte", "unit": "byte", "value": 252542976}, {"name": "S3 IO Input Count", "unit": "count", "value": 0}, {"name": "S3 IO Output Count", "unit": "count", "value": 367}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 384990068}], "Network": [{"name": "Network", "unit": "byte", "value": 192}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 5948299}, {"name": "Output Rows", "unit": "count", "value": 2941839}, {"name": "Input Size", "unit": "byte", "value": 487890640}, {"name": "Output Size", "unit": "byte", "value": 235348272}], "Time": [{"name": "Time Consumed", "unit": "ns", "value": 1987747802}, {"name": "Wait Time", "unit": "ns", "value": 159404269731}]}, "totalStats": {"name": "Time spent", "unit": "ns", "value": 1987747802}}, "labels": [], "nodes": [{"id": "4", "labels": [{"name": "List of expressions", "value": ["lineitem.l_returnflag", "lineitem.l_linestatus", "sum(lineitem.l_quantity)", "sum(lineitem.l_extendedprice)", "sum(lineitem.l_extendedprice * (1 - lineitem.l_discount))", "sum(lineitem.l_extendedprice * (1 - lineitem.l_discount) * (1 + lineitem.l_tax))", "avg(lineitem.l_quantity)", "avg(lineitem.l_extendedprice)", "avg(lineitem.l_discount)", "count(1)"]}], "name": "Project", "statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO Byte", "unit": "byte", "value": 0}, {"name": "S3 IO Input Count", "unit": "count", "value": 0}, {"name": "S3 IO Output Count", "unit": "count", "value": 367}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 0}], "Network": [{"name": "Network", "unit": "byte", "value": 0}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 4}, {"name": "Output Rows", "unit": "count", "value": 4}, {"name": "Input Size", "unit": "byte", "value": 608}, {"name": "Output Size", "unit": "byte", "value": 608}], "Time": [{"name": "Time Consumed", "unit": "ns", "value": 2277}, {"name": "Wait Time", "unit": "ns", "value": 31884706102}]}, "stats": {"blocknum": 0, "cost": 180036.45, "hashmapsize": 0, "outcnt": 180036.45, "rowsize": 0}, "title": "lineitem.l_returnflag, lineitem.l_linestatus, sum(lineitem.l_quantity), sum(lineitem.l_extendedprice), sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)), sum(lineitem.l_extendedprice * (1 - lineitem.l_discount) * (1 + lineitem.l_tax)), avg(lineitem.l_quantity), avg(lineitem.l_extendedprice), avg(lineitem.l_discount), count(1)", "totalStats": {"name": "Time spent", "unit": "ns", "value": 2277}}, {"id": "3", "labels": [{"name": "Sort keys", "value": ["lineitem.l_returnflag INTERNAL", "lineitem.l_linestatus INTERNAL"]}], "name": "Sort", "statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO Byte", "unit": "byte", "value": 0}, {"name": "S3 IO Input Count", "unit": "count", "value": 0}, {"name": "S3 IO Output Count", "unit": "count", "value": 0}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 0}], "Network": [{"name": "Network", "unit": "byte", "value": 0}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 4}, {"name": "Output Rows", "unit": "count", "value": 4}, {"name": "Input Size", "unit": "byte", "value": 608}, {"name": "Output Size", "unit": "byte", "value": 608}], "Time": [{"name": "Time Consumed", "unit": "ns", "value": 22911}, {"name": "Wait Time", "unit": "ns", "value": 63769340312}]}, "stats": {"blocknum": 0, "cost": 180036.45, "hashmapsize": 0, "outcnt": 180036.45, "rowsize": 0}, "title": "lineitem.l_returnflag INTERNAL, lineitem.l_linestatus INTERNAL", "totalStats": {"name": "Time spent", "unit": "ns", "value": 22911}}, {"id": "2", "labels": [{"name": "List of expressions", "value": ["lineitem.l_returnflag", "lineitem.l_linestatus", "sum(lineitem.l_quantity)", "sum(lineitem.l_extendedprice)", "sum(lineitem.l_extendedprice * (1 - lineitem.l_discount))", "sum(lineitem.l_extendedprice * (1 - lineitem.l_discount) * (1 + lineitem.l_tax))", "avg(lineitem.l_quantity)", "avg(lineitem.l_extendedprice)", "avg(lineitem.l_discount)", "count(1)"]}], "name": "Project", "statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO Byte", "unit": "byte", "value": 0}, {"name": "S3 IO Input Count", "unit": "count", "value": 0}, {"name": "S3 IO Output Count", "unit": "count", "value": 0}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 0}], "Network": [{"name": "Network", "unit": "byte", "value": 0}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 4}, {"name": "Output Rows", "unit": "count", "value": 4}, {"name": "Input Size", "unit": "byte", "value": 608}, {"name": "Output Size", "unit": "byte", "value": 608}], "Time": [{"name": "Time Consumed", "unit": "ns", "value": 1492}, {"name": "Wait Time", "unit": "ns", "value": 0}]}, "stats": {"blocknum": 0, "cost": 180036.45, "hashmapsize": 0, "outcnt": 180036.45, "rowsize": 0}, "title": "lineitem.l_returnflag, lineitem.l_linestatus, sum(lineitem.l_quantity), sum(lineitem.l_extendedprice), sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)), sum(lineitem.l_extendedprice * (1 - lineitem.l_discount) * (1 + lineitem.l_tax)), avg(lineitem.l_quantity), avg(lineitem.l_extendedprice), avg(lineitem.l_discount), count(1)", "totalStats": {"name": "Time spent", "unit": "ns", "value": 1492}}, {"id": "1", "labels": [{"name": "Grouping keys", "value": ["lineitem.l_returnflag", "lineitem.l_linestatus"]}, {"name": "Aggregate functions", "value": ["sum(lineitem.l_quantity)", "sum(lineitem.l_extendedprice)", "sum((CAST(lineitem.l_extendedprice AS DECIMAL128(38, 2)) * (CAST(1 AS DECIMAL128(2, 2)) - CAST(lineitem.l_discount AS DECIMAL128(15, 2)))))", "sum(((CAST(lineitem.l_extendedprice AS DECIMAL128(38, 2)) * (CAST(1 AS DECIMAL128(2, 2)) - CAST(lineitem.l_discount AS DECIMAL128(15, 2)))) * (CAST(1 AS DECIMAL128(2, 2)) + CAST(lineitem.l_tax AS DECIMAL128(15, 2)))))", "avg(lineitem.l_quantity)", "avg(lineitem.l_extendedprice)", "avg(lineitem.l_discount)", "starcount(1)"]}], "name": "Aggregate", "statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO Byte", "unit": "byte", "value": 0}, {"name": "S3 IO Input Count", "unit": "count", "value": 0}, {"name": "S3 IO Output Count", "unit": "count", "value": 0}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 117673336}], "Network": [{"name": "Network", "unit": "byte", "value": 0}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 2941823}, {"name": "Output Rows", "unit": "count", "value": 4}, {"name": "Input Size", "unit": "byte", "value": 235345840}, {"name": "Output Size", "unit": "byte", "value": 608}], "Time": [{"name": "Time Consumed", "unit": "ns", "value": 1922954467}, {"name": "Wait Time", "unit": "ns", "value": 63750223317}]}, "stats": {"blocknum": 0, "cost": 900182.25, "hashmapsize": 900182.25, "outcnt": 180036.45, "rowsize": 0}, "title": "sum(lineitem.l_quantity), sum(lineitem.l_extendedprice), sum((CAST(lineitem.l_extendedprice AS DECIMAL128(38, 2)) * (CAST(1 AS DECIMAL128(2, 2)) - CAST(lineitem.l_discount AS DECIMAL128(15, 2))))), sum(((CAST(lineitem.l_extendedprice AS DECIMAL128(38, 2)) * (CAST(1 AS DECIMAL128(2, 2)) - CAST(lineitem.l_discount AS DECIMAL128(15, 2)))) * (CAST(1 AS DECIMAL128(2, 2)) + CAST(lineitem.l_tax AS DECIMAL128(15, 2))))), avg(lineitem.l_quantity), avg(lineitem.l_extendedprice), avg(lineitem.l_discount), starcount(1)", "totalStats": {"name": "Time spent", "unit": "ns", "value": 1922954467}}, {"id": "0", "labels": [{"name": "Full table name", "value": "tpch_1g.lineitem"}, {"name": "Columns", "value": ["l_quantity", "l_extendedprice", "l_discount", "l_tax", "l_returnflag", "l_linestatus", "l_shipdate"]}, {"name": "Total columns", "value": 16}, {"name": "Scan columns", "value": 7}, {"name": "Filter conditions", "value": ["(lineitem.l_shipdate <= date_sub(date('1998-12-01'), 112, 5))"]}], "name": "Table Scan", "statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO Byte", "unit": "byte", "value": 252542976}, {"name": "S3 IO Input Count", "unit": "count", "value": 0}, {"name": "S3 IO Output Count", "unit": "count", "value": 0}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 267316732}], "Network": [{"name": "Network", "unit": "byte", "value": 192}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 3006464}, {"name": "Output Rows", "unit": "count", "value": 2941823}, {"name": "Input Size", "unit": "byte", "value": 252542976}, {"name": "Output Size", "unit": "byte", "value": 235345840}], "Time": [{"name": "Time Consumed", "unit": "ns", "value": 64766655}, {"name": "Wait Time", "unit": "ns", "value": 0}]}, "stats": {"blocknum": 733, "cost": 6001215, "hashmapsize": 0, "outcnt": 900182.25, "rowsize": 0}, "title": "tpch_1g.lineitem", "totalStats": {"name": "Time spent", "unit": "ns", "value": 64766655}}]}, "state": "success", "stats": {}, "step": 0}], "success": true, "uuid": "e6f26753-c891-11ed-b105-f6253439fecb"}

**Comment by nnsgmsone** [comment]
麻烦岳声查看一下cache的清理策略，看样子应该是存在误清理的情况（也可能是使用者误操作），麻烦确认一下

**Comment by reusee** [comment]
是根据什么判断是磁盘缓存的问题的？
现在磁盘缓存不会被清理

**Comment by reusee** [comment]
<img width="802" alt="截屏2023-03-24 01 27 33" src="https://user-images.githubusercontent.com/398457/227288051-c6d02dbf-cfbf-46ae-8dc8-c63fbc776a96.png">
这里S3的统计，input和output的意义不太明白。
Put, Delete, DeleteMulti 是写操作
List, Head, Get 是读操作

**Comment by reusee** [comment]
要判断 disk cache 的表现，可以启用 -debug-http 后，打开 `/debug/perfcounter` 路径，查看 Disk.Read/Hit 的数字。对比跑之前和跑之后的数字，就可以判断是不是磁盘缓存的问题

<img width="1036" alt="截屏2023-03-24 01 37 49" src="https://user-images.githubusercontent.com/398457/227292507-656c31df-907d-49a5-ab84-bc2cf7653887.png">

**Comment by reusee** [comment]
无进展

**Comment by reusee** [comment]
@aressu1985 如果有重现，请用上面方法提供更多信息，以判断是不是磁盘缓存的问题。我初步判断磁盘缓存不存在失效问题。

**Comment by reusee** [comment]
如上

**Comment by aressu1985** [comment]
@nnsgmsone this issue should be causeed by that the second query was routed to different cn , and it need to load data from s3 again.

**Comment by nnsgmsone** [comment]
好的，在算子重构后，我会处理一下这个问题

**Comment by nnsgmsone** [comment]
好的，在算子重构后，我会处理一下这个问题

**Comment by nnsgmsone** [comment]
好的，在算子重构后，我会处理一下这个问题

**Comment by nnsgmsone** [comment]
好的，在算子重构后，我会处理一下这个问题

**Comment by nnsgmsone** [comment]
好的，在算子重构后，我会处理一下这个问题

**Comment by nnsgmsone** [comment]
Now the prefetch is yours to pull. Teenager.

**Comment by badboynt1** [comment]
今天测试，3cn的环境， tpch10g q1第一次20秒， 经过大约10次以后可以收敛到2.2秒，并且不会再有波动。
应该是因为diskcache给到100g已经足够大，使得tpch10g已经在diskcache里可以完整覆盖了。

不过理论上当cache locality的问题解决后，应该第二次就立刻可以收敛到2.2秒

**Comment by badboynt1** [comment]
https://github.com/matrixorigin/matrixone/pull/9094  等这个pr合并后再验证一下

**Comment by badboynt1** [comment]
pr已经合并。 现在在多cn环境上，任何query的耗时应该从第二次就开始收敛，并且不会再出现大的波动。 请验证一下

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
