### ISSUE TITLE
[Bug]: create sequence name which include'@' etc success, select reported not exists

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8632]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dc0b6d294203d9c2c271a55032ba98341868856e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sequence name include ‘@’ ，number，chinese etc , need support or interception？
![image](https://user-images.githubusercontent.com/113406637/227125738-57ea1489-fced-4ca2-8552-088d4cb23c73.png)
![image](https://user-images.githubusercontent.com/113406637/227128281-6329dd1d-0388-4b5b-a33d-24ef0e4ccac9.png)
![image](https://user-images.githubusercontent.com/113406637/227131054-b49e7188-1c38-49e5-8c4d-23554a329eb1.png)
![image](https://user-images.githubusercontent.com/113406637/227131928-aec3ed0d-5dd1-4175-9436-6e9b9a0aec78.png)

### Steps to Reproduce
create sequence \`123\` start 30;
create sequence \`中文\` maxvalue 6899 cycle;
select nextval(\'中文\'),currval(\'中文\');
create sequence \`test@123456\`;
select nextval(\'test@123456\'),currval(\'test@1234506\');
create sequence \`ab.cd\`;
select nextval(\'ab.cd\');

**Comment by nnsgmsone** [comment]
iceTTT is already working on fixing this problem

**Comment by iceTTTT** [comment]
#8636 merged

**Comment by heni02** [comment]
All cases are verified to be correct, except for `test@123456`,plz confirm @iceTTTT 
commit id:6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
<img width="764" alt="企业微信截图_db011a74-3da0-42c1-980b-502f923483f9" src="https://user-images.githubusercontent.com/113406637/227713931-b67da6d9-cbcf-43ca-875b-e940cde69db5.png">

**Comment by heni02** [comment]
case problem,closed
<img width="652" alt="企业微信截图_74296049-7239-42f5-8e14-8b5a3ef055bb" src="https://user-images.githubusercontent.com/113406637/227716494-efe2b574-98e4-46d3-9380-e91102338a82.png">
