### ISSUE TITLE
[Bug]: insert into value nextval sequences report panic errror

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8638]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dc0b6d294203d9c2c271a55032ba98341868856e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/227160503-a58caf92-52a4-464d-b0a1-7c0b6a9d36b3.png)

### Steps to Reproduce

```Markdown
create sequence seq_05 start 10000;
select nextval('seq_05');
create table seq_table_01(col1 int);
insert into seq_table_01 values(nextval('seq_05'));
```

**Comment by iceTTTT** [comment]
#8636 merged

**Comment by heni02** [comment]
confirm,closed
commit id:6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
<img width="695" alt="企业微信截图_f12ff053-4a3d-4cbf-8f69-9943cb1f98a7" src="https://user-images.githubusercontent.com/113406637/227714117-d77a0bc2-e8ef-415b-9e31-57306b815c62.png">
