### ISSUE TITLE
[Bug]: select nextval,currval sequence together results error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8639]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dc0b6d294203d9c2c271a55032ba98341868856e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
sql: select nextval('seq_04'),currval('seq_04');
MO：
<img width="487" alt="企业微信截图_6e0d4d65-1b65-457e-9daa-01dfd0ebdc48" src="https://user-images.githubusercontent.com/113406637/227161831-482d8c88-8198-499c-a3e2-efce01ed8cd1.png">

postgres：
<img width="655" alt="企业微信截图_6f93dc25-e683-484b-9fa1-11c10be7031d" src="https://user-images.githubusercontent.com/113406637/227161861-9fe739dc-4e47-4276-bc1d-f402f6f6d751.png">

### Steps to Reproduce

```Markdown
create sequence seq_04 increment by -10;
select nextval('seq_04');
select nextval('seq_04');
select nextval('seq_04'),currval('seq_04');
```

**Comment by nnsgmsone** [comment]
iceTTT is already working on fixing this problem

**Comment by iceTTTT** [comment]
Pr #8636 merged

**Comment by heni02** [comment]
confirm,closed
commit id:6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
<img width="564" alt="企业微信截图_10d69ded-464b-466b-ba29-c0ab35073bf2" src="https://user-images.githubusercontent.com/113406637/227714172-6fc667f6-e6dd-4687-862a-104fcd36b313.png">
