### ISSUE TITLE
[Feature Request]: doc bot needs an update with issue’s subtask

### ISSUE THREAD

**Issue by lacrimosaprinz** [matrixorigin/matrixone#8640]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
The issue labeled with "doc influence" has been split into subtasks. The pull request submitted by the R&D team is related to the subtask issue, which does not have the "doc influence" label. Therefore, the robot will not provide notification.
```

### Describe the feature you'd like

The pull requests corresponding to the subtasks split from the "doc influence" labeled issue should also be automatically notified to the doc issue group.

**Comment by guguducken** [comment]
@lacrimosaprinz finished, please check and close it.
