### ISSUE TITLE
[Bug]: drop sequence which not exists reported no such table 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8642]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):dc0b6d294203d9c2c271a55032ba98341868856e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO:
![image](https://user-images.githubusercontent.com/113406637/227171673-8a167999-616e-4772-b803-33662d922484.png)
postgre:
![image](https://user-images.githubusercontent.com/113406637/227171816-eef8a187-92f0-4d16-b6e2-5cdb3272ac2a.png)

### Steps to Reproduce

```Markdown
drop sequence seq_non;
```

**Comment by iceTTTT** [comment]
Pr #8636 merged

**Comment by heni02** [comment]
confirm,closed
commit id:6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
<img width="546" alt="企业微信截图_c8b036a6-5e1a-4129-b338-b3a4e41b4b1a" src="https://user-images.githubusercontent.com/113406637/227714266-d3841d19-071e-496e-a8af-2c6dd333ca2f.png">
