### ISSUE TITLE
[Bug]: kill cn0，cn1 pod mem killed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8647]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
I use the method of rebooting a virtual machine to simulate a failure of cn. When rebooting a virtual machine of cn0, cn1 is killed by mem
<img width="640" alt="image" src="https://user-images.githubusercontent.com/113406637/227207212-6dfd746f-af8b-4da0-a8d5-d6d6988cefb1.png">

![image](https://user-images.githubusercontent.com/113406637/227206421-0561f34f-9345-40f4-99c4-4786c2b14526.png)

This  is not a stable recurrence

**Comment by aylei** [comment]
@heni02 can you provide full log of cn-0 and cn-1?

**Comment by heni02** [comment]
cn1 log:
[cn1_bug.log](https://github.com/matrixorigin/matrixone/files/11057802/cn1_bug.log)

**Comment by aylei** [comment]
As discussed with @nnsgmsone offline, we will evaluate the root cause soon

**Comment by nnsgmsone** [comment]
我会和张旭讨论一下，看一下cn刮掉的情况下，两个cn会发生什么。。

**Comment by zhangxu19830126** [comment]
我看日志，这个是几天之前的版本了，这个版本会造成一个lockservice的误判，因为悲观事务还没有启用，导致不停的刷error日志，会导致trace占用大量的内存。

**Comment by zhangxu19830126** [comment]
在这个 https://github.com/matrixorigin/matrixone/pull/8540 修复之后的版本看一下。我觉得已经被修复了

**Comment by heni02** [comment]
ok，I will verify after yidao environment update

**Comment by heni02** [comment]
I waiting for an upgraded version of the environment, which is undergoing daily testing. The upgraded version requires redeployment and import of data, affecting daily testing

**Comment by aressu1985** [comment]
test lots of this cases, not repro again
