### ISSUE TITLE
[Bug]: adjust columns  in mo_user_defined_function

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8697]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. the created_time of mo_user_defined_function is CTS tz, howerver, this column in other tables is local tz.
Please modify it to local time zone.
2. add column owner. just like the owner column of mo_tables, the role_id of creator

**Comment by YANGGMM** [comment]
have opend a pr

**Comment by YANGGMM** [comment]
have add one column, but the time can't change beacause of ci

**Comment by domingozhang** [comment]
column name should be owner. it's creator now
