### ISSUE TITLE
[Bug]: tpcc regression test reported panic error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8698]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):0b1c9988975f384ecc4fde6f49800ebf23ae77e5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

tpcc regression no matter how many warehouses, also reported this error
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4525437857/jobs/7969950434
![image](https://user-images.githubusercontent.com/113406637/227833613-db835f23-5dc3-4f59-9338-9cc6a1caae13.png)
mo log path ：128 /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/upload/mo-tpcc.log

2023-03-26 22:24:28 FATAL jTPCCTerminal:251 - DELIVERY_BG: Unexpected SQLException on transaction execution: internal error: panic interface conversion: interface {} is []types.Varlena, not []types.Rowid: 
runtime.panicdottypeE
	/usr/local/go/src/runtime/iface.go:262
github.com/matrixorigin/matrixone/pkg/container/vector.MustFixedCol[...]
	/go/src/github.com/matrixorigin/matrixone/pkg/container/vector/tools.go:40
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Transaction).deleteBatch
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn.go:256
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Delete
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:466
github.com/matrixorigin/matrixone/pkg/sql/colexec.FilterAndUpdateByRowId
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/constraint_util.go:107
github.com/matrixorigin/matrixone/pkg/sql/colexec/update.Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/update/update.go:95
github.com/matrixorigin/matrixone/pkg/vm.Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:151
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:134
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Update
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/dml.go:86
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:222
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2814
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3269
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:[175](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4525444775/jobs/7972160999#step:17:176)
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:321
github.com/fagongzi/goetty/v2.(*server).doConnection
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted

### Steps to Reproduce
git clone https://github.com/matrixorigin/mo-tpcc.git
cd mo-tpcc 
view README.md have specific operation steps

**Comment by nnsgmsone** [comment]
这个看着是update算子的输出有问题。我们的delete应该只能接受一列，并且类型只能是rowid.

**Comment by heni02** [comment]
commit id: f9a168aea147e632a7296ea2fe66381823f00b77 had this problem
commit id: ea57dad5fc0df382c96cb72c07c5e23e3ef93f1d had no this problem

**Comment by ouyuanning** [comment]
seems that this PR https://github.com/matrixorigin/matrixone/commit/6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f 
caused the problem

**Comment by JackTan25** [comment]
waiting yuesheng to improve speed

**Comment by ouyuanning** [comment]
waiting yuesheng's PR

**Comment by heni02** [comment]
confirm,closed
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4566498718/jobs/8063717937
