### ISSUE TITLE
[Bug]: statscache memory not free

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#8699]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):4322ac6b9603f76b0dac339feb3d61b0e209e8bd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

run sysbench mixed

<img width="942" alt="image" src="https://user-images.githubusercontent.com/14086886/227834720-e7e53cab-1f6c-4e94-99c5-b5bfe35dc938.png">

**Comment by badboynt1** [comment]
fixed
