### ISSUE TITLE
[Bug]: mo_catalog db create time inaccuracy.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#8708]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="836" alt="image" src="https://user-images.githubusercontent.com/39303074/227870314-b1061440-1c78-444b-b29e-8ea0f7f3df9f.png">

**Comment by tianyahui-python** [comment]
system, system_metrics, information_schema, mysql, mo_catalog create time should be consistent

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
can't repro in local. commit id `839525546b`
try with single/multi CN and root/user account

need more information about how to repro

**Comment by dongdongyang33** [comment]
related issue - https://github.com/matrixorigin/matrixone/issues/8620

**Comment by dongdongyang33** [comment]
waiting 8620

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by sukki37** [comment]
fixed.

verified version:0a5786af3da2735110732c94427e15221d365fe6

<img width="545" alt="image" src="https://github.com/user-attachments/assets/ba92fc44-bd54-4d39-9f89-1cc85d91d2a5">
