### ISSUE TITLE
[Bug]: insert into duplicate key  which is foreign key results error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8711]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sql: insert into indup_fk2 values(10,'food',1)on duplicate key update col1=50;
mo execute successed, mysql reported  error messages
![image](https://user-images.githubusercontent.com/113406637/227878541-2c33987a-afaa-4be9-977d-cfe42a48b168.png)

### Steps to Reproduce

```Markdown
create table indup_fk1(col1 int primary key,col2 varchar(25),col3 tinyint);
create table indup_fk2(col1 int,col2 varchar(25),col3 tinyint primary key,constraint ck foreign key(col1) REFERENCES indup_fk1(col1) on delete RESTRICT on update RESTRICT);
insert into indup_fk1 values (2,'yellow',20),(10,'apple',50),(11,'opppo',51);
insert into indup_fk2 values(2,'score',1),(2,'student',4),(10,'goods',2);
insert into indup_fk2 values(10,'food',1)on duplicate key update col1=50;
```

**Comment by dongdongyang33** [comment]
checking

**Comment by ouyuanning** [comment]
we need a solution to check fk after values update.

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066

**Comment by ouyuanning** [comment]
will fixed after plan refactor finished

**Comment by heni02** [comment]
confirm，closed
commit id：71e7151601635363e8c131484449abbfb3508715
<img width="1183" alt="企业微信截图_0903c173-9d90-4f01-8f9b-153bfa6760e5" src="https://github.com/matrixorigin/matrixone/assets/113406637/0b759102-60f5-450f-97c9-5f7c52ab0c21">
