### ISSUE TITLE
[Bug]: Error  occurred when casting binary to varchar and casting timestamp to binary

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8712]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id：0b1c9988975f384ecc4fde6f49800ebf23ae77e5
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/227880369-1f38eb46-1d6c-4e78-b917-5972c257d0e7.png)

![image](https://user-images.githubusercontent.com/108530700/227929334-aec245e0-9184-441a-9efb-0aa859fcaeec.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/108530700/227880393-bee9abd6-9a36-49fb-bcb3-4ed62b5c7a8e.png)

![image](https://user-images.githubusercontent.com/108530700/227929370-1a6cce8b-3de1-4a99-9c0f-c0b5d63fad51.png)

### Steps to Reproduce

```Markdown
DROP TABLE IF EXISTS t5;
CREATE TABLE t5(a int NOT NULL PRIMARY KEY, b float, c double, d VARCHAR(30));
INSERT INTO t5 VALUES(1, 3214321.213, -8392.3,'woshishei');
INSERT INTO t5 VALUES(2, 0, 38293.3332121,'12345@');
INSERT INTO t5 VALUES(3, -392.1, 8390232,'3***');
SELECT CAST(d AS binary) FROM t5;
```

SELECT CAST(TIMESTAMP "2004-01-22 21:45:33" AS BINARY(4));

**Comment by iceTTTT** [comment]
#pr 8790 merged.

**Comment by Ariznawlll** [comment]
test  done!
