### ISSUE TITLE
[Bug]: insert into duplicate key which is in Explicit transaction reported duplicate entry during the commit

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8713]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
Whether to check for duplicate values only during the commit phase, or whether the insert statement directly returns a duplicate value error
sql： insert into indup_07 values(22,'11','33',1), (23,'22','55',2),(33,'66','77',1) on duplicate key update col1=col1+1,col2='888';
![image](https://user-images.githubusercontent.com/113406637/227884060-07b0c529-5ca8-463d-89b8-552b8f87ad91.png)
![image](https://user-images.githubusercontent.com/113406637/227883929-e2152f14-91b3-4115-8940-178a9b92c70d.png)

### Steps to Reproduce

```Markdown
CREATE TABLE IF NOT EXISTS indup_07(
    col1 INT primary key,
    col2 VARCHAR(20) NOT NULL,
    col3 VARCHAR(30) NOT NULL,
    col4 BIGINT default 30
);
insert into indup_07 values(22,'11','33',1), (23,'22','55',2),(24,'66','77',1),(25,'99','88',1),(22,'11','33',1) on duplicate key update col1=col1+col2;
select * from indup_07;
start transaction ;
insert into indup_07 values(22,'11','33',1), (23,'22','55',2),(33,'66','77',1) on duplicate key update col1=col1+1,col2='888';
select * from indup_07;
commit;
```

**Comment by ouyuanning** [comment]
not similar to #6949
that's a bug of on duplicate key. but not easy to fixed. because we can not known if we get on duplicate in CN sometimes.
we need another query to check.
i think that's similar #8711.  if we have solution to  fixed 8751, then we can fixe this bug.

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066

**Comment by ouyuanning** [comment]
will fixed after plan refactor finished

**Comment by ouyuanning** [comment]
will fixed after plan refactor finished

**Comment by ouyuanning** [comment]
this will be fixed when check dup pk in CN was enable.

**Comment by ouyuanning** [comment]
应该已经好了。周一确认一下

**Comment by ouyuanning** [comment]
打开CN端的PK去重检查即可。

在cn的配置文件中加入：
[cn]
primary-key-check = true

如果没有打开的话，那么只能在commit的时候在DN进行pk的去重，就会如所提bug中的表现。

**Comment by heni02** [comment]
confirm,closed
commit id: 6c14bc30b09ef54c53f0fb7e992fb1343ecd0c76
![image](https://github.com/matrixorigin/matrixone/assets/113406637/dc5b9d83-b25c-40c4-9fd5-c4c8393055f5)

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by ouyuanning** [comment]
由于默认是没有打开cn的pk查重的。那个bvt tag还没法移除。
