### ISSUE TITLE
[Bug]: No results for `show accounts`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#8715]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0b1c9988
- Hardware parameters:
- OS type: ubuntu
- Others:
```

### Actual Behavior

- Run `show accounts`
- Check the query result and get the following error:
```
{"error": "Error 20440 (HY000): result file SHARED:/query_result_meta/b8583190_43a8_41cb_a837_b1757d05358e_2c185f8b-cc79-11ed-857a-76dcffb57911.blk not found", "elapsed": "24.633048ms", "rows": -1, "sql": "/* cloud_nonuser */ select * from result_scan('2c185f8b-cc79-11ed-857a-76dcffb57911') as t limit 0,1000"}
```

### Expected Behavior

Get query result successfully

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

**Comment by taofengliu** [comment]
```show accounts``` needs to be handled by pipeline but not frontend

**Comment by taofengliu** [comment]
resolve it soon

**Comment by taofengliu** [comment]
merge soon

**Comment by taofengliu** [comment]
working on it now...

**Comment by DanielZhangQD** [comment]
Verified and passed with commit nightly-0f1162f
