### ISSUE TITLE
[Bug]: insert into duplicate key results error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8716]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6eaad1db2aa3c41ec8416280dabc0f00d7b0b77f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert into indup_02 values(3,'aaa','bbb',30),(30,'abc','abc',10),(11,'a1','b1',300) on duplicate key update col1=col1*10,col4=0;
select * from  indup_02:
![image](https://user-images.githubusercontent.com/113406637/227887938-6492634d-c52b-41cf-af40-c3eebe2985df.png)

### Steps to Reproduce

```Markdown
CREATE TABLE IF NOT EXISTS indup_02(
    col1 INT ,
    col2 VARCHAR(20) NOT NULL,
    col3 VARCHAR(30) NOT NULL,
    col4  BIGINT default 30,
    PRIMARY KEY ( col1 )
);
insert into indup_02 values (1,'apple','left',NULL),(2,'bear','right',1000);
select * from indup_02;
insert into indup_02 select 1,'banana','lower',NULL on duplicate key update col1=col1*10;
select * from indup_02;
insert into indup_02(col1,col2,col3) values(2,'wechat','tower'),(3,'paper','up') on duplicate key update col1=col1+20,col3=values(col3);
select * from indup_02;
insert into indup_02 values(3,'aaa','bbb',30) on duplicate key update col1=col1+7;
select * from indup_02;
insert into indup_02 values(3,'aaa','bbb',30),(30,'abc','abc',10),(11,'a1','b1',300) on duplicate key update col1=col1*10,col4=0;
select * from indup_02;
```

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
seems that we have different semantics

<img width="949" alt="image" src="https://user-images.githubusercontent.com/47596332/227906454-2141160d-9d16-4963-af1e-25aab60d1567.png">

**Comment by heni02** [comment]
confirm,closed
commit id:7120770b819ec6ec000c2e4ffc0af24fa4c9043e
![image](https://user-images.githubusercontent.com/113406637/228411581-3ca4c73d-c2a0-4751-9603-94231eda7568.png)
