### ISSUE TITLE
[Bug]: casted string is printed as scientific notation

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8719]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![企业微信截图_16799090849768](https://user-images.githubusercontent.com/88298673/227904088-a7b88585-2b2f-4a04-a027-6d1c2d76dc49.png)

current rule is cast float to string as scientific notation.
However, both mysql and pg is casting float to its original value
<img width="342" alt="企业微信截图_a59498d0-bbcd-45aa-80c9-abc0d3c0cf6a" src="https://user-images.githubusercontent.com/88298673/227904251-6481deb1-76c7-472f-9f6b-bba1585f147e.png">

**Comment by iceTTTT** [comment]
Pr #8720 merged.
