### ISSUE TITLE
[Bug]: set @a_var=nextval reported panic error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8724]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a49d075ba87bf53ecc8d3101203967c9a99d80a0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

prepare stmt1 from 'insert into seq_table_01 values(?)';
set @a_var = nextval('seq15');
internal error: panic interface conversion: interface is nil, not engine.Engine: 
runtime.assertE2I
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/iface.go:451
github.com/matrixorigin/matrixone/pkg/sql/plan/function/builtin/seq.Nextval
	/Users/heni/test-envir/matrixone/pkg/sql/plan/function/builtin/seq/nextval.go:40
github.com/matrixorigin/matrixone/pkg/sql/plan/function.Function.VecFn
	/Users/heni/test-envir/matrixone/pkg/sql/plan/function/function.go:177
github.com/matrixorigin/matrixone/pkg/sql/colexec.evalFunction
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/expr_eval.go:484
github.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpr
	/Users/heni/test-envir/matrixone/pkg/sql/colexec/expr_eval.go:265
github.com/matrixorigin/matrixone/pkg/frontend.GetSimpleExprValue
	/Users/heni/test-envir/matrixone/pkg/frontend/util.go:286
github.com/matrixorigin/matrixone/pkg/frontend.doSetVar
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:640
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleSetVar
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:679
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:2472
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/Users/heni/test-envir/matrixone/pkg/frontend/mysql_cmd_executor.go:3247
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/Users/heni/test-envir/matrixone/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/Users/heni/test-envir/matrixone/pkg/frontend/routine_manager.go:321
github.com/fagongzi/goetty/v2.(*server).doConnection
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/Users/heni/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
runtime.goexit
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/runtime/asm_arm64.s:1172

### Steps to Reproduce

```Markdown
create table seq_table_01(col1 int);
create sequence seq15 increment 10 start with 20 no cycle;
prepare stmt1 from 'insert into seq_table_01 values(?)';
set @a_var = nextval('seq15');
execute stmt1 using @a_var;
```

**Comment by iceTTTT** [comment]
#8732 is merged.

**Comment by heni02** [comment]
confirm,closed
commit id:7120770b819ec6ec000c2e4ffc0af24fa4c9043e
![image](https://user-images.githubusercontent.com/113406637/228409721-848a869f-59d4-4c7c-aff3-1b24d806c06f.png)
![image](https://user-images.githubusercontent.com/113406637/228409824-525e566f-258a-46e1-98fc-087582d0422d.png)

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
