### ISSUE TITLE
[Bug]: push mode bvt test results error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8734]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):2d8424f56aaf68fb9fe4257805d0e1a2c43ae201
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
https://github.com/matrixorigin/matrixone/actions/runs/4532194180/jobs/7983274763?pr=8718
2023-03-27 12:43:25 ERROR Executor:136 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/function/func_aggr_count.test][row:233][SELECT a,COUNT(DISTINCT b) FROM t1 GROUP BY a HAVING COUNT(DISTINCT b) > 50;] was executed failed, con[id=0, user=dump, ***
2023-03-27 12:43:25 ERROR Executor:138 - [EXPECT RESULT]:
a    COUNT(DISTINCT b)
1    65536
2023-03-27 12:43:25 ERROR Executor:139 - [ACTUAL RESULT]:
a    count(distinct b)
1    16384

**Comment by m-schen** [comment]
try to fix it tomorrow.

**Comment by m-schen** [comment]
tracing.

**Comment by m-schen** [comment]
fix a unstable sort error will cause wrong result. and can verify it if the pr was merged.

**Comment by heni02** [comment]
Difficult to reproduce, code merge to observe if it still appears, if not, close

**Comment by m-schen** [comment]
还没找到原因

**Comment by m-schen** [comment]
no process today. can not repro.

**Comment by nnsgmsone** [comment]
thank you @reusee

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/c89b5ad3edc6a278995802e61312075f0c721e46

**Comment by m-schen** [comment]
root cause is a txn will try to get 2 snapshot of a table. (for sql `insert into t select * from t`)
and we will use the latest snapshot of memory table but first snapshot of block info.

if flush happens between 2 snapshot, it will cause memory table of 2th snapshot to be empty. so we lost the data of memory table.

c89b5ad3edc6a278995802e61312075f0c721e46 fixed this bug. a txn will get only one snapshot for a table.

**Comment by heni02** [comment]
@m-schen Is there any way to reproduce it？

**Comment by heni02** [comment]
Confirm tomorrow

**Comment by heni02** [comment]
confirm，closed
commit id:05e84d50c55f9b0d56b3c97231c6534d3c902f92
select from table
![image](https://user-images.githubusercontent.com/113406637/232018446-1486ed99-7af3-47a5-b62d-d4951bf5c939.png)
![image](https://user-images.githubusercontent.com/113406637/232018509-4a8db739-9fc1-4ca7-9b48-ba2d48055ee8.png)

insert t  select from t
![image](https://user-images.githubusercontent.com/113406637/232018832-797a63b1-47f8-4aa6-b403-5e6f3ea5780f.png)
![image](https://user-images.githubusercontent.com/113406637/232018978-d7476311-e73b-4078-91b6-f632103f97c7.png)
