### ISSUE TITLE
[Bug]: cast conversion varbinary can also be converted without specifying length

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8736]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:0b1c9988975f384ecc4fde6f49800ebf23ae77e5
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/228119069-9be16954-fd9c-47c3-9491-c93919f1a3cb.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/108530700/228119139-65f85169-5936-4f90-853a-bf556bf1de51.png)

### Steps to Reproduce

```Markdown
SELECT CAST("z" AS varbinary);
SELECT CAST("z" AS varbinary(100));
```

**Comment by iceTTTT** [comment]
Pr #8790 merged.

**Comment by Ariznawlll** [comment]
test done！

**Comment by fengttt** [comment]
This is not a bug.   Should revert.

**Comment by heni02** [comment]
mysql varbinary需要指定长度，否则报错，田博 @fengttt 现在要支持不指定长度还是和mysql一致？支持的话我们需要改文档
<img width="926" alt="企业微信截图_5e06bfaf-f12e-4415-b34e-35d2ee7c5751" src="https://github.com/matrixorigin/matrixone/assets/113406637/c00a7309-628a-43ba-adbb-2e541dcfd231">
mysql：
<img width="1016" alt="企业微信截图_3f6f6692-748a-4952-89cb-b5747a8241de" src="https://github.com/matrixorigin/matrixone/assets/113406637/bf18cdc2-d5b4-4091-b212-9a9a8ee9ce44">

**Comment by fengttt** [comment]
This is perfectly fine -- we are fully compatible, except we have an extension (do not need spec length).

**Comment by arjunsk** [comment]
CC: @yangj1211

**Comment by arjunsk** [comment]
Thank you Feng. Hi @heni02, kindly review this PR: https://github.com/matrixorigin/matrixone/pull/14281

**Comment by arjunsk** [comment]
Merged to master. Kindly verify.

**Comment by Ariznawlll** [comment]
<img width="544" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a366dee2-f49c-4577-97c9-19ac54923360">

verified.
