### ISSUE TITLE
[Bug]: syntax error for alter index invisible

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8739]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create table t1(a int, b int, c int, key(c));
alter table t1 alter index c invisible;
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 20 near " alter index c  invisible";

the invisible column of mo_indexes needs not be modified and the syntax needs be supported

**Comment by qingxinhome** [comment]
The issue has been resolved, please test. @domingozhang @Ariznawlll @daviszhen
