### ISSUE TITLE
[Bug]: push mode bvt mo crash 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8741]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3352409108d462964f211bfaadeb21362177accf
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
push mode e2e 1cn bvt test： 
https://github.com/matrixorigin/matrixone/actions/runs/4538406728/jobs/7997290975?pr=8726

2023/03/28 02:14:25.460810 +0000 INFO rpc/handle.go:751 [precommit] handle write typ: 0, 273389-t, 273358-insert
 txn: ctx[D3937243D491437BA1C27012C9E26E50][1679969663968124564-0->9223372036854775807-4294967295][Active]: <nil>

2023/03/28 02:14:25.460862 +0000 INFO rpc/handle.go:758 [precommit] handle write end txn: ctx[D3937243D491437BA1C27012C9E26E50][1679969663968124564-0->9223372036854775807-4294967295][Active]: <nil>

2023/03/28 02:14:25.460872 +0000 INFO rpc/handle.go:102 HandleCommit end : D3937243D491437BA1C27012C9E26E50

panic: runtime error: index out of range [0] with length 0

goroutine 1272 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/stl/containers.(*StdVector[...]).SlicePtr(0x2e5ab00?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/stl/containers/stdvec.go:121 +0x2d
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).SlicePtr(0x1?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/containers/vector.go:170 +0x24
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).extendData(0xc00b1503a8, {0x2eede38, 0xc037b2aff0}, 0x0, 0x19d0)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/containers/vecbase.go:107 +0xbe
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vecBase[...]).ExtendWithOffset(0x1288acd?, {0x2eede38?, 0xc037b2aff0?}, 0x11a84e7?, 0x1288acd?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/containers/vecbase.go:116 +0x8c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vector[...]).ExtendWithOffset(0x0?, {0x2eede38?, 0xc037b2aff0?}, 0xc0141ae000?, 0xc015996340?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/containers/vector.go:183 +0x3b
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*anode).Append(0xc00b150390, 0xc003cdfe00, 0x0)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnimpl/anode.go:112 +0x6c8
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*localSegment).Append(0xc00d0062d0, 0xc003cdfe00)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnimpl/localseg.go:300 +0xce
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnTable).Append(0xc0137d6800, 0xc003cdfe00)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnimpl/table.go:576 +0x1e7
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnDB).Append(0xc01394a790?, 0xc0196b3260?, 0xc03789efc0?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnimpl/txndb.go:114 +0x4f
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnStore).Append(0xc037b2b090?, 0x2?, 0x2eec998?, 0x28290c0?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnimpl/store.go:176 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/txn/txnimpl.(*txnRelation).Append(0xc00f67a8f0, 0xc03789efc0?)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/txn/txnimpl/relation.go:165 +0x68
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/moengine.(*txnRelation).Write(0xc037b29d10, {0x1c?, 0xc0197d54d0?}, 0xc0137d6480)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/moengine/txn_relation.go:56 +0x338
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(_, {_, _}, {{0xc03789ebc0, 0x10, 0x10}, 0x0, {0x175073822e409e94, 0x0, 0x8323, ...}, ...}, ...)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/rpc/handle.go:781 +0x58c
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(_, {_, _}, {{0xc03789ebc0, 0x10, 0x10}, 0x0, {0x175073822e409e94, 0x0, 0x8323, ...}, ...})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/rpc/handle.go:146 +0x8a5
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(_, {_, _}, {{0xc03789ebc0, 0x10, 0x10}, 0x0, {0x175073822e409e94, 0x0, 0x8323, ...}, ...})
	/home/runner/work/matrixone/matrixone/head/pkg/txn/storage/tae/storage.go:97 +0x95
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc0082cc360, {0x2e6d758, 0xc037b299b0}, 0xc0090ac900, 0xc00b073680)
	/home/runner/work/matrixone/matrixone/head/pkg/txn/service/service_cn_handler.go:235 +0xbc5
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc004cfca70?, {0x2e6d758, 0xc037b299b0}, 0xc0090ac900, 0xc00b073680)
	/home/runner/work/matrixone/matrixone/head/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0xc004cfca20, {0x2e6d758?, 0xc037b299b0?}, {0x2e94ad8?, 0xc0090ac900?}, 0x0?, {0x2e813a0, 0xc0044fc3c0})
	/home/runner/work/matrixone/matrixone/head/pkg/txn/rpc/server.go:163 +0x4f0
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc00477edc0, {0x2eba2e0, 0xc00529a000}, {0x28bc320?, 0xc003cdfb40}, 0x1b20)
	/home/runner/work/matrixone/matrixone/head/pkg/common/morpc/server.go:227 +0x66c
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc00477ee60, {0x2eba2e0, 0xc00529a000})
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5

**Comment by heni02** [comment]
mo and mo-tester log:
[e2e_linux_x86_reports.zip](https://github.com/matrixorigin/matrixone/files/11084989/e2e_linux_x86_reports.zip)

**Comment by aptend** [comment]
same error in https://github.com/aptend/matrixone/actions/runs/4530239057/jobs/7978913680

One possible reason for this error is that the input batch for writing has an empty vector while the first vector in the batch is not empty. Further check is needed.

**Comment by triump2020** [comment]
@JackTan25   You have the ball now.

**Comment by arjunsk** [comment]
I found a similar issue in my branch as well.

```log

panic: invalid vector: vector is empty

goroutine 12245 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleWrite(_, {_, _}, {{0xc03bc7fd50, 0x10, 0x10}, 0x0, {0x1750ce2cb54db9af, 0x0, 0x8323, ...}, ...}, ...)
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/rpc/handle.go:789 +0xb78
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/rpc.(*Handle).HandleCommit(_, {_, _}, {{0xc03bc7fd50, 0x10, 0x10}, 0x0, {0x1750ce2cb54db9af, 0x0, 0x8323, ...}, ...})
	/home/runner/work/matrixone/matrixone/head/pkg/vm/engine/tae/rpc/handle.go:146 +0x8a5
github.com/matrixorigin/matrixone/pkg/txn/storage/tae.(*taeStorage).Commit(_, {_, _}, {{0xc03bc7fd50, 0x10, 0x10}, 0x0, {0x1750ce2cb54db9af, 0x0, 0x8323, ...}, ...})
	/home/runner/work/matrixone/matrixone/head/pkg/txn/storage/tae/storage.go:97 +0x95
github.com/matrixorigin/matrixone/pkg/txn/service.(*service).Commit(0xc0051de000, {0x2c7c258, 0xc03ca30120}, 0xc00bedb800, 0xc012b9a180)
	/home/runner/work/matrixone/matrixone/head/pkg/txn/service/service_cn_handler.go:235 +0xbc5
github.com/matrixorigin/matrixone/pkg/dnservice.(*store).handleCommit(0xc004a816d0?, {0x2c7c258, 0xc03ca30120}, 0xc00bedb800, 0xc012b9a180)
	/home/runner/work/matrixone/matrixone/head/pkg/dnservice/store_rpc_handler.go:108 +0x96
github.com/matrixorigin/matrixone/pkg/txn/rpc.(*server).onMessage(0xc004a81680, {0x2c7c258?, 0xc03ca30120?}, {0x2ca2d18?, 0xc00bedb800?}, 0xc029809701?, {0x2c8fee0, 0xc003f05e00})
	/home/runner/work/matrixone/matrixone/head/pkg/txn/rpc/server.go:163 +0x4f0
github.com/matrixorigin/matrixone/pkg/common/morpc.(*server).onMessage(0xc0052a4280, {0x2cc4640, 0xc009cb0a00}, {0x27247a0?, 0xc03ca05e80}, 0x1a7c)
	/home/runner/work/matrixone/matrixone/head/pkg/common/morpc/server.go:227 +0x66c
github.com/fagongzi/goetty/v2.(*server).doConnection(0xc0052a4320, {0x2cc4640, 0xc009cb0a00})
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 +0x376
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1()
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 +0x90
created by github.com/fagongzi/goetty/v2.(*server).doStart.func2
	/home/runner/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:336 +0x4c5

```

Artifact [link](https://github.com/matrixorigin/matrixone/actions/runs/4550611139?pr=7879).

**Comment by JackTan25** [comment]
can't produce

**Comment by JackTan25** [comment]
continuing

**Comment by fengttt** [comment]
> continuing

what does this mean?

**Comment by JackTan25** [comment]
> > continuing
> 
> what does this mean?

I took a week off. I had some school work to do

**Comment by m-schen** [comment]
今天没找到原因

**Comment by triump2020** [comment]
@m-schen   Maybe there is  a suspicious ,  so i add the [debug info](https://github.com/matrixorigin/matrixone/pull/8895) .

**Comment by m-schen** [comment]
今天复现不出来。related pr: https://github.com/matrixorigin/matrixone/pull/8877

**Comment by m-schen** [comment]
```
2023/04/08 09:58:47.074025 +0000 INFO vector/vector.go:280 free vec 0xc00c8bc800

...

2023/04/08 09:58:47.281324 +0000 INFO preinsert/preinsert.go:48 pre-insert operator receive a batch, batch length is 8192
[vec 0[type is 22, 0xc00c8bc980] : len is 8192, data len is 65536, area len is 0]
[vec 1[type is 22, 0xc00c8bc800] : len is 0, data len is 0, area len is 0]
```

log shows that :  
we have received a vector with length 0 which can not match the batch Len. and we call the free method for this vector before.

**Comment by m-schen** [comment]
> ```
> 2023/04/08 09:58:47.074025 +0000 INFO vector/vector.go:280 free vec 0xc00c8bc800
> 
> ...
> 
> 2023/04/08 09:58:47.281324 +0000 INFO preinsert/preinsert.go:48 pre-insert operator receive a batch, batch length is 8192
> [vec 0[type is 22, 0xc00c8bc980] : len is 8192, data len is 65536, area len is 0]
> [vec 1[type is 22, 0xc00c8bc800] : len is 0, data len is 0, area len is 0]
> ```
> 
> 
>     
>   
> 
> log shows that :
> we have received a vector with length 0 which can not match the batch Len. and we call the free method for this vector before.

I will do a check that because it is so confused that I have got 3 free logs in file. and the time interval between multi logs is not short.

**Comment by m-schen** [comment]
![image](https://user-images.githubusercontent.com/59043531/230767465-97f3ee4c-2552-4e04-8085-583d3f1451ef.png)

If multiple vecs in the batch are the same pointer, the Free will cause an empty vector for next dup.

I have fixed this bug.

**Comment by m-schen** [comment]
the pr has merged.  plz verify it. @heni02

**Comment by heni02** [comment]
No appearance for two days, close this issue
