### ISSUE TITLE
[Bug]: table value function crash

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8769]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select e.* from rawlog, unnest(rawlog.extra, '$.*') e where caller like 'mometric%' limit 1;
ERROR 20101 (HY000): internal error: panic runtime error: index out of range [10] with length 1:
runtime.goPanicIndex
        /usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/sql/colexec.EvalExpr
        /home/ftian/m/matrixone/pkg/sql/colexec/expr_eval.go:237
github.com/matrixorigin/matrixone/pkg/sql/colexec/table_function.unnestCall
        /home/ftian/m/matrixone/pkg/sql/colexec/table_function/unnest.go:117
github.com/matrixorigin/matrixone/pkg/sql/colexec/table_function.Call
        /home/ftian/m/matrixone/pkg/sql/colexec
mysql>

### Expected Behavior

Run this against system database

### Steps to Reproduce

```Markdown
Run this against system database,

select e.* from rawlog, unnest(rawlog.extra, '$.*') e where caller like 'mometric%' limit 1;
```

**Comment by zhangxu19830126** [comment]
@m-schen in expr_eval.go:237,   vec := bat.Vecs[t.Col.ColPos]，index out of slice. Should check index first

**Comment by m-schen** [comment]
no, we shouldn't do any length check here.
may the plan give me a wrong index, or operator make a error to set a wrong index.
I will do check tomorrow.

**Comment by mooleetzi** [comment]
maybe my fault, let me check

**Comment by mooleetzi** [comment]
crash seems to be solved by #8892 , but table function join type maybe need change to lateral.
rewrite `select e.* from rawlog, unnest(rawlog.extra, '$.*') e where caller like 'mometric%' limit 1;`  to 
`with tt as (select * from rawlog where caller like 'mometric%' limit 1) select e.* from tt,unnest(tt.extra) e limit 1`  works faster.

**Comment by iceTTTT** [comment]
Waiting merge of pr #8892

**Comment by aressu1985** [comment]
fixed

mysql>  select e.* from rawlog, unnest(rawlog.extra, '$.*') e where caller like 'mometric%' limit 1;
Empty set (1 min 23.50 sec)

mysql>
