### ISSUE TITLE
[Bug]: error on `mo_table_col_max` func

### ISSUE THREAD

**Issue by FelixSeptem** [matrixorigin/matrixone#8772]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-7120770b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```shell
mysql> select mo_table_col_max('mo_catalog','mo_database','dat_id') as t;
ERROR 20203 (HY000): invalid argument mo_table_col_max has bad input table, bad value mo_database
```

### Expected Behavior

`mo_table_col_max` work as expect

**Comment by dongdongyang33** [comment]
checking

**Comment by YANGGMM** [comment]
mo_databases, mo_columns and mo_tables this system tables does't have block metadata, so we can't use this function for those table. @FelixSeptem
