### ISSUE TITLE
[Bug]: The cost of loading data on eks increase obviously 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8777]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 4c12525
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For daily regression on eks on 3.29 , commit: 

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/47846308/228465919-d1388e16-4f4a-418d-a306-1dff8fec730d.png">

the test run time is :
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/47846308/228466652-bf2a64aa-c6f8-445e-819f-af46daa63408.png">

the mo completely log is in s3: s3://mo-ares/mo-benchmark/etl

### Steps to Reproduce

```Markdown
1、run a mo cluster on eks
2、load data from s3, the data path is : s3://mo-load-data/100_columns/
```

**Comment by dongdongyang33** [comment]
checking

**Comment by aressu1985** [comment]
For daily regression on eks on 3.29，the cost increase again，the about 50%  rate
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/47846308/228720521-65185775-649d-4ccb-a173-74e9450b567b.png">

**Comment by dongdongyang33** [comment]
invastigating

**Comment by dongdongyang33** [comment]
bisect and then found the pr https://github.com/matrixorigin/matrixone/pull/8738 caused the performance regression

**Comment by aptend** [comment]
there is no more we can do about this

**Comment by aressu1985** [comment]
this can be closed temparily
