### ISSUE TITLE
[Bug]: plain text of the password is recorded in the `statement` field of the `statement_info` table

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#8791]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 7120770b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

- Create user with account admin
```
create user test identified by '111';
```
- Check the `statement` field of the `statement_info` table and the password is recorded in plain text

### Expected Behavior

The password is not in plain text.

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

**Comment by dongdongyang33** [comment]
checking

**Comment by DanielZhangQD** [comment]
Verified and passed with commit nightly-0e9def7a
