### ISSUE TITLE
[Bug]: show account exec 5 hours after cn restart

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#8792]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 79b9bc58
- Hardware parameters:
- OS type: eks dev env
- Others:
    - bucket: mocloud-test
    - path prefix: freetier-01-Crps
    - log date: 2023-03-26 06:25 ~ 11:41
```

### Actual Behavior

( more details in https://github.com/matrixone-cloud/mocloud-services/issues/551)

in metric cron_task.go, exec `show accounts` wait 5 hours + to get result

as i find this mark:
- `2023-03-26 06:25:47.150141`, wait next round (metric server_connection)
- `2023-03-26 06:30:53.754786`, shutdown 
- `2023-03-26 06:31:07.874288`, start next round (new task for metric server_connection)
- `2023-03-26 11:41:10.180993`, finish exec `show accounts`

![image](https://user-images.githubusercontent.com/3927687/228750476-aa12041f-b3fc-4b2a-bd22-85bca6b1a1bc.png)

![image](https://user-images.githubusercontent.com/3927687/228750532-57419165-e094-4d06-84b0-26b998f42703.png)

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
no progress today

**Comment by daviszhen** [comment]
这个要等存储把取表size的做得更高效后，才能做。

**Comment by daviszhen** [comment]
等存储的进展。

**Comment by daviszhen** [comment]
等meta issue 做完，看性能能否改进。 https://github.com/matrixorigin/matrixone/issues/8865

**Comment by daviszhen** [comment]
等#8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
等https://github.com/matrixorigin/matrixone/issues/8865 做完

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by xzxiong** [comment]
New version mo after `metadata_scan`, new perf https://github.com/matrixorigin/MO-Cloud/issues/921

**Comment by daviszhen** [comment]
等meta_scan

**Comment by daviszhen** [comment]
等meta_scan

**Comment by daviszhen** [comment]
等meta_scan

**Comment by daviszhen** [comment]
等meta_scan

**Comment by daviszhen** [comment]
meta_scan 沁璇好像做了。
提供新实现。

**Comment by daviszhen** [comment]
还没做。

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by sukki37** [comment]
longtime no progress, close it. trace by #11480
