### ISSUE TITLE
[Bug]: Performance degradation observed in recent longrunning test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#8799]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 7120770
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

During the recent cloud long-running test, we observed a significant decrease in performance over time. The long-running test had the following workload model:

4 users with different accounts, where one user ran `sysbench` tests (7 terminals, point_select/insert/delete/update_pk mix scenarios). The other 3 users ran `tpch` queries with a 1GB dataset.

To further analyze the performance degradation issue, I obtained a 10-minute profile during the workload execution, and the overall graph is as follows:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/77312370/228812774-21efdcd8-08ed-47f8-b111-5447170341bc.png">
<img width="1766" alt="image" src="https://user-images.githubusercontent.com/77312370/228813321-4ad0e134-9c57-4f39-8b17-aa02a4259bc4.png">

The profile file is available here. [0-cn1-pprof.mo-service.samples.cpu.005.pb.gz](https://github.com/matrixorigin/matrixone/files/11110593/0-cn1-pprof.mo-service.samples.cpu.005.pb.gz)

Based on the profile, some issues are observed:

1. gc costs 183s in total
<img width="913" alt="image" src="https://user-images.githubusercontent.com/77312370/228813989-8202d22d-acdc-46e6-90dc-d2a0bab2ccdb.png">
2. `like` operator costs 76s in total
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/77312370/228814562-1a6fb663-a436-4c3e-b515-2d054442ee7e.png">
3. `plan.Optimize` costs 72s in total
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/77312370/228814657-27740c86-b7b7-4278-9fcb-e88bfbfe9e42.png">
4. our `saveQuery` impl appears to be blocking the normal return of the query which seems that it will seriously affect the performance of the TP .  
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/77312370/228814604-65c853d4-cff3-4d70-8681-96c2aa930b3b.png">

There are still many issues in the profile results, and relevant colleagues need to pay attention to them.

**Comment by fengttt** [comment]
1. GC issue, wait for operator and expression
2. Like, wait for expression context and rewrite the like function.
3. Will ping Ni Tao.
4. saveQuery should only save queries that runs longer than ...

**Comment by sukki37** [comment]
Update 0331-0402
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/77312370/229397580-1e779589-7256-4d42-9e2c-5393e838d2eb.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/77312370/229398134-30f995b8-1b21-48f6-9f15-abd6865bf8c8.png">

**Comment by fengttt** [comment]
3. seems to be get table meta #8865

**Comment by sukki37** [comment]
GC Issues can be tracked in #9008

**Comment by fengttt** [comment]
like should be solved by mingsong's work.    this issue is largely solved/resolved by now.
