### ISSUE TITLE
[Subtask]: Tumble Window

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#8806]
### Parent Issue

#8590

### Detail of Subtask

SELECT
  user,
  TUMBLE_START(order_time, INTERVAL '1' DAY) AS wStart,
  SUM(amount) FROM Orders
GROUP BY
  TUMBLE(order_time, INTERVAL '1' DAY),
  user;

**Comment by iamlinjunhong** [comment]
doc: https://github.com/iamlinjunhong/docs/blob/tw/design/time%20window.md

**Comment by Ariznawlll** [comment]
test done.
