### ISSUE TITLE
[Subtask]: Sliding Window

### ISSUE THREAD

**Issue by iamlinjunhong** [matrixorigin/matrixone#8807]
### Parent Issue

#8590

### Detail of Subtask

SELECT
    HOP_START (ts, INTERVAL '30' SECOND, INTERVAL '1' MINUTE),
    HOP_END (ts, INTERVAL '30' SECOND, INTERVAL '1' MINUTE),
    username,
    COUNT (click_url)
FROM
    user_clicks
GROUP BY
    HOP (ts, INTERVAL '30' SECOND, INTERVAL '1' MINUTE),username;

**Comment by iamlinjunhong** [comment]
doc: https://github.com/iamlinjunhong/docs/blob/tw/design/time%20window.md

**Comment by Ariznawlll** [comment]
sliding window test done.
