### ISSUE TITLE
[Bug]:  inconsistent set system variable behavior

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#8808]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-ec092499
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

If i make some changes to the global sql_mode, it won't be effective in the current session:

mysql> select @@sql_mode;
+---------------------+
| @@sql_mode          |
+---------------------+
| ALLOW_INVALID_DATES |
+---------------------+
1 row in set (0.02 sec)

mysql> set global sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
Query OK, 0 rows affected (0.01 sec)

mysql> select @@sql_mode;
+---------------------+
| @@sql_mode          |
+---------------------+
| ALLOW_INVALID_DATES |
+---------------------+
1 row in set (0.00 sec)
mysql> exit
Bye
nandeng-macbookpro:~ nandeng$ mysql -h 127.0.0.1 -P6001 -udump -p111
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1045
Server version: 8.0.30-MatrixOne-v09249 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                         |
+----------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

Only until i close this connection and reconnect, this sql_mode modification shows up. 

But for lower_case_table_names, the modification for global variable is immediately effective.
mysql> select @@lower_case_table_names;
+--------------------------+
| @@lower_case_table_names |
+--------------------------+
|                        2 |
+--------------------------+
1 row in set (0.03 sec)
mysql> set global lower_case_table_names = 1;
Query OK, 0 rows affected (0.01 sec)

mysql> select @@lower_case_table_names;
+--------------------------+
| @@lower_case_table_names |
+--------------------------+
|                        1 |
+--------------------------+
1 row in set (0.00 sec)

### Expected Behavior

In MySQL, the behavior is that global setting doesn't affect the current session. I think we should follow MySQL behavior.

MySQL behavior:

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> set global sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
Query OK, 0 rows affected (0.04 sec)

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> exit
Bye
nandeng-macbookpro:airboot-web nandeng$ mysql -uroot -phelloworld
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 436
Server version: 8.0.29 MySQL Community Server - GPL

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                         |
+----------------------------------------------------------------------------------------------------+
| STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by YANGGMM** [comment]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/26563383/229394096-d5a2f18b-37d2-4289-adc2-8105c312f2c2.png">

**Comment by YANGGMM** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/26563383/229397964-fb0475e1-968d-4451-8d38-2bae19fe1b81.png">

**Comment by YANGGMM** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/26563383/229398209-00f1480c-02b6-415d-9809-6969b8446c6b.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/26563383/229398269-f47436d8-4145-47e1-8f56-3beb158a2edd.png">

**Comment by daviszhen** [comment]
与邓楠确认

**Comment by YANGGMM** [comment]
scope 为Global 的系统变量set 之后会在当前session生效
scope为Global和session的系统变量set之后会在重新连接后生效

**Comment by dengn** [comment]
sql_mode是Global和session的，lower_case_table_names是global的，跟mysql行为是一致的
