### ISSUE TITLE
[Bug]: Error involving binary conversion in Chinese

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8818]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:c770d291f10a985d42e586c1f81ac8d88b5a6ce9
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/229101124-d51f7bd9-dd5a-497e-9876-92c29782adb6.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/108530700/229101161-d9f69369-6228-47ff-9c21-b0f14d994cdc.png)

### Steps to Reproduce

```Markdown
select binary('hello你好呀！');
select binary('数据库');
```

**Comment by iceTTTT** [comment]
The result got from mo is utf-8 encoding, while that from mysql is GBK enocding.

**Comment by daviszhen** [comment]
@zengyan1 帮忙看下

**Comment by sukki37** [comment]
same with mysql8.0（utf-8）

**Comment by matrix-meow** [comment]
Hello @Ariznawlll. The bug issue in the BVT test code has not been removed,issues automatically open.
