### ISSUE TITLE
[Bug]: 100 sequences concurrent insert into the table, data error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8826]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6c9ec78c9844cf317084c09629661811dfb887cb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

execute bingfa 100 below sql which seq1 is sequence and then insert data with duplicate values, it is error because sequence is unique value
sql：insert into table_02 values (nextval('seq1'))
![image](https://user-images.githubusercontent.com/113406637/229400843-42bc24b3-1482-4874-9325-e0842f80cc4c.png)
![image](https://user-images.githubusercontent.com/113406637/229400904-0fcba536-5a3c-4e4b-9239-02a12c4a7be9.png)

### Steps to Reproduce

```Markdown
Reproduce:
1.download tool: git@github.com:matrixorigin/mo-load.git
2.alter bingfa like this,path: cases/ddl/:
![image](https://user-images.githubusercontent.com/113406637/229402220-8d09d3cd-af2f-44ad-bb9c-efa41557037e.png)

3. mysql client execute sql:
create database db;
use db;
create table table_02(col int);
create sequence seq1;
4.run
./start.sh -c cases/xxx
```

**Comment by heni02** [comment]
Reproduce step 2 failed image: 
![image](https://user-images.githubusercontent.com/113406637/229402444-066c0aa8-2c80-4d5b-b1fd-57ebdcd16f50.png)

**Comment by reusee** [comment]
Seems that calling `nextval` concurrently will return the same values.

A simple repro program

```go
//go:build ignore

package main

import (
	"database/sql"
	"sync"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "dump:111@tcp(127.0.0.1:6001)/db")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	exec := func(sql string) {
		_, err = db.Exec(sql)
		if err != nil {
			panic(err)
		}
	}

	exec(`drop database if exists db`)
	exec(`create database db`)
	exec(`use db`)
	exec(`create table t (i int primary key)`)
	exec(`create sequence seq1`)

	parallel := 100
	wg := new(sync.WaitGroup)
	wg.Add(parallel)
	for i := 0; i < parallel; i++ {
		go func() {
			defer wg.Done()
			for i := 0; i < 1024; i++ {
				exec(`insert into t values (nextval('seq1'))`)
			}
		}()
	}
	wg.Wait()

}

```

which reports write-write conflict incorrectly
```
panic: Error 20619: w-w conflict

goroutine 26 [running]:
main.main.func1({0x104dfcf77?, 0x0?})
	/Users/reus/mo/m/8826.go:22 +0xa4
main.main.func2()
	/Users/reus/mo/m/8826.go:39 +0x70
created by main.main in goroutine 1
	/Users/reus/mo/m/8826.go:36 +0x198
exit status 2
```

**Comment by reusee** [comment]
re-assigning to the author of sequence @iceTTTT

**Comment by aressu1985** [comment]
@jianwan0214 this issue is related about data correctness. update level to s-1, pls deal it wiht hight priority

**Comment by domingozhang** [comment]
may be the same as auto incremental column

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm,closed
commit id:83af67c7329ae911e793139670c8bb1a2f2249f8
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c62e9476-0cf2-4b20-8eff-c4e188af590f)
