### ISSUE TITLE
[Bug]:  invalid argument cast to int, bad value

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8834]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:0bb146b2d3e3a0d71872689995f6d6cb5a3549f5
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/229448502-c3e722e2-e5e5-481e-83d6-56302e9f6af8.png)

### Steps to Reproduce

```Markdown
use information_schema;
select * from tables limit 10;
```

**Comment by qingxinhome** [comment]
The problem has been resolved, please test. @Ariznawlll
