### ISSUE TITLE
[Bug]: table_type is not properly displayed

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#8847]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:f5e458d596b37ce62587bb876401f008010b1adb
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/229702759-23a50a45-26f6-4fe5-b9da-ec93388f30ef.png)

### Expected Behavior

Modify "Unknown table type" to "Internal Table". 

### Steps to Reproduce

```Markdown
use information_schema;
select * from tables;
```

**Comment by qingxinhome** [comment]
The issue has been resolved, please test. @Ariznawlll

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/230250459-c0baa305-3756-4f52-8d54-6e9e58d15492.png)
test done！
