### ISSUE TITLE
[Bug]: TestLockWithBindIsStable TestGetLockWithBindIsStable failed

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixone#8850]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/4604900101/jobs/8136304667

failed

**Comment by zhangxu19830126** [comment]
fixed
