### ISSUE TITLE
[Bug]: There are 3 MO docker images uploaded to dockerhub at the same time which is confusing

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#8859]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):N.A.
- Hardware parameters:N.A.
- OS type:N.A.
- Others:N.A.
```

### Actual Behavior

Currently it seems that there are 3 mo docker images uploaded to dockerhub at the same time, which makes it quite confusing for user to tell which one is the newest. 
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/46433151/229711933-d08c1fb0-8dd2-4537-a2ae-07438f851321.png">

### Expected Behavior

Is it possible that we carry some timestamp in tags that indicate when these commits are merged?

### Steps to Reproduce

```Markdown
1. Go to dockerhub
2. Search for matrixone
3. You see 3 docker images uploaded at the same time, all of which are named after format nightly-${commitid}, but no timestamps indicating when they are merged.
```

### Additional information

N.A.

**Comment by sukki37** [comment]
fixed

**Comment by aronchanisme** [comment]
confirmed issue's resolved
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/46433151/236434866-8f975be8-925f-48b1-aa2b-559dea567f79.png">
