### ISSUE TITLE
[Enhancement]: metadata performance

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#8865]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
metadata scan/access performance is way too slow.
```

**Comment by LeftHandCold** [comment]
I think https://github.com/matrixorigin/matrixone/pull/9203 and https://github.com/matrixorigin/matrixone/pull/9247 are done with this feature
