### ISSUE TITLE
[Bug]: the version number has been changed again

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#8872]
### Describe your problem

I've installed a distributed MO with version(nightly-91db3b73), and connect it with MySQL client. I get this version number:

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 1026
Server version: 8.0.30-MatrixOne-v9137 MatrixOne

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]>

What's the meaning of this v9137 and how is it linked with the deploy version?

**Comment by dengn** [comment]
another example is using nightly-f5e458d5 docker hub version. and gets 8.0.30-MatrixOne-v5458 MatrixOne version in MySQL connection.

**Comment by daviszhen** [comment]
@YANGGMM  看下

**Comment by sukki37** [comment]
fixed

**Comment by dengn** [comment]
so what's the new behavior now? keep the docker hub version number?

**Comment by dengn** [comment]
after test, the version number has been set to for all developed commits

Server version: 8.0.30-MatrixOne-v0.7.0 MatrixOne

**Comment by lacrimosaprinz** [comment]
Docs have been checked.

**Comment by dengn** [comment]
test with nightly-6362da2 image. We get this strange connection version again:

[root@master0 local-path-provisioner]# mysql -h $(kubectl get svc/mo-tp-cn -n mo-hn -o jsonpath='{.spec.clusterIP}') -P 6001 -udump -p111
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 35
Server version: 8.0.30-MatrixOne-v63622 MatrixOne

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]>

**Comment by arjunsk** [comment]
@sukki37 Kindly have a look at this issue.

**Comment by sukki37** [comment]
The unofficial image overrides the official image, I will handle this.

**Comment by dengn** [comment]
verified with nightly-5c2e40de. 

Server version: 8.0.30-MatrixOne-v0.7.0 MatrixOne.

**Comment by dengn** [comment]
it happens again:

version: nightly-54b5e8c

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 209
Server version: 8.0.30-MatrixOne-v5458 MatrixOne

**Comment by dengn** [comment]
in the latest version, it becomes normal again.

version: nightly-3e22243a

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 126
Server version: 8.0.30-MatrixOne-v0.7.0 MatrixOne
