### ISSUE TITLE
[Bug]: sequence cannot be found in explicit transactions

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#8890]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e9a9fb4564dd0518f11828c88ba8fddd5c6cc605
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/113406637/230343125-76989fb5-b6ce-40d9-984b-b6f3423012fd.png)

### Steps to Reproduce

```Markdown
begin;
create sequence seq_18 minvalue 1000;
select nextval('seq_18');
-- @session:id=2&user=sys:dump&password=111
select nextval('seq_18');
create sequence seq_18;
-- @session
select nextval('seq_18');
commit;
```

**Comment by aressu1985** [comment]
@jianwan0214 pls update this issue status

**Comment by heni02** [comment]
confirm，closed

**Comment by heni02** [comment]
confirm，closed
