### ISSUE TITLE
[Feature Request]: limited access mode on account level

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8937]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

use ALTER ACCOUNT statement to switch an account to a limited access mode:
ALTER ACCOUNT account_name restricted;

Only delete, show and select can be accepted
Only moadmin can use this clause

**Comment by dengn** [comment]
Doc side question:
Details about the syntax, role and privilege mechanism are required.

**Comment by domingozhang** [comment]
syntax:
alter account {account_name} restricted;

Only MOAdmin role in sys account can use this SQL and sys account cannot be set to restricted.

A resitricted account only accept these statements:
DELETE/SELECT/SHOW

A resitricted account can be set to open/suspend.

**Comment by YANGGMM** [comment]
plz test

**Comment by LiSong0214** [comment]
@heni02 请及时验证哈

**Comment by heni02** [comment]
test done
