### ISSUE TITLE
Behavior of Float type precision differs from MySQL

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#894]
#### Can be reproduced ?
Yes.

#### Steps:
create table t_float(a float, b float(54));
insert into t_float values (123456789, 12345678.123456789);
insert into t_float values (1.23456789, 1.23456789);
select * from t_float;

#### Expected behavior:
There are two different behaviors when comparing against MySQL:

1. According to MySQL doc, for FLOAT(p), the precision value 'p' is used only to determine storage size. A precision from 0 to 23 results in a 4-byte single-precision FLOAT column. A precision from 24 to 53 results in an 8-byte double-precision DOUBLE column.
Due to the above rule, if try to define a FLOAT type column with a precision value is 54, then MySQL will issue an error. Please see below:
mysql> create table t_float(a float, b float(54));
ERROR 1063 (42000): Incorrect column specifier for column 'b'

In contrast to that, Matrixone lets the same SQL run successfully. 

We need to decide if apply the same rule to the precision value as MySQL does.

2. The retrieved value is different. As in MySQL, the default precision is 6 bits. For example, assuming that 123456789 was inserted into MySQL, it returns 123457000 when query, whereas Matrixone returns 123456792.0000 instead.

#### Actual behavior:

mysql> create table t_float(a float, b float(54));
Query OK, 0 rows affected (0.28 sec)

mysql> insert into t_float values (123456789, 12345678.123456789);
Query OK, 0 rows affected (0.08 sec)

mysql> insert into t_float values (1.23456789, 1.23456789);
Query OK, 0 rows affected (0.04 sec)

mysql> select * from t_float;
+----------------+---------------+
| a              | b             |
+----------------+---------------+
| 123456792.0000 | 12345678.0000 |
|         1.2346 |        1.2346 |
+----------------+---------------+
2 rows in set (0.01 sec)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 06261a26e804acad91414ef9669aea9378bc7996
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by m-schen** [comment]
1. FOR QUESTION ONE
in mysql reference manual:
`For maximum portability, code requiring storage of approximate numeric data values should use FLOAT or DOUBLE PRECISION with no specification of precision or number of digits.`

May we just allow float and double is more suitable.
