### ISSUE TITLE
[Bug]: cn panic by invalid memory address or nil pointer dereference when run tpch 10 queries for about 10 times on eks with 2*cn 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8947]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 33dc8fc
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[cn-panic-by-remote-down.txt](https://github.com/matrixorigin/matrixone/files/11198091/cn-panic-by-remote-down.txt)
77f19a3d3:moadmin -- 0:4294967295:0}|38fc7847-d83c-11ed-b823-523c2f56cc7a"}
{"level":"INFO","time":"2023/04/11 07:41:08.421318 +0000","caller":"frontend/util.go:400","msg":"query trace status","connection_id":1002,"statement":"select task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, task_parent_id, task_status, task_runner, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_status = 2 and task_metadata_executor = 1 order by task_id","status":"success","span":{"trace_id":"38fd6e78-d83c-11ed-b823-523c2f56cc7a","kind":"statement"},"session_info":"connectionId 1002|10.0.175.92:33300|{account sys:38ad0124-1398-4e66-8338-19377f19a3d3:moadmin -- 0:4294967295:0}|38fc7847-d83c-11ed-b823-523c2f56cc7a"}
{"level":"INFO","time":"2023/04/11 07:41:08.450362 +0000","name":"cn-service","caller":"logutil/action.go:52","msg":"async task exited","uuid":"00000000-0000-0000-0000-200000000001","action":"run-async-task","async-task":"cnservice/wait-system-init-task","cost":"4.049043122s"}
{"level":"ERROR","time":"2023/04/11 07:41:10.712830 +0000","caller":"morpc/backend.go:704","msg":"error: can not connect to remote backend","stacktrace":"github.com/matrixorigin/matrixone/pkg/common/morpc.(*remoteBackend).resetConn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:704\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.NewRemoteBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:205\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*goettyBasedBackendFactory).Create\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/backend.go:811\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).doCreate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:456\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).createBackendLocked\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:444\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).createBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:429\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).getBackend\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:239\ngithub.com/matrixorigin/matrixone/pkg/common/morpc.(*client).NewStream\n\t/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:183\ngithub.com/matrixorigin/matrixone/pkg/cnservice/cnclient.(*CNClient).NewStream\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/cnclient/client.go:73\ngithub.com/matrixorigin/matrixone/pkg/cnservice/cnclient.GetStreamSender\n\t/go/src/github.com/matrixorigin/matrixone/pkg/cnservice/cnclient/client.go:41\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.newMessageSenderOnClient\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scopeRemoteRunTypes.go:80\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).remoteRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scopeRemoteRun.go:262\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:183\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:108"}
{"level":"ERROR","time":"2023/04/11 07:41:10.712910 +0000","name":"cn-backend","caller":"morpc/backend.go:206","msg":"connect to remote failed","remote":"nightly-regression-dis-tp-cn-0.nightly-regression-dis-tp-cn-headless.mo-nightly-regression.svc:6002","backend-id":"167e62a6-f8ac-41c2-88fb-8a562008cca2","error":"can not connect to remote backend"}
2023/04/11 07:41:10.712924 +0000 ERROR rpc-client[cn-client] morpc/client.go:458 create backend failed {"backend": "nightly-regression-dis-tp-cn-0.nightly-regression-dis-tp-cn-headless.mo-nightly-regression.svc:6002", "error": "can not connect to remote backend"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1f625db]

goroutine 271 [running]:
github.com/matrixorigin/matrixone/pkg/sql/compile.(*messageSenderOnClient).send(0xc0540bde08, {0xc00fa00000, 0x58aa54, 0x58aa54}, {0xc00d8b0790, 0xa6, 0xa6}, 0x7f04bc02113a?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scopeRemoteRunTypes.go:102 +0xbb
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).remoteRun(0xc00c032410, 0xc00c13b200)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scopeRemoteRun.go:266 +0x2b0
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).RemoteRun(0xc00c032410, 0xc00c13b200)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:183 +0x2ba
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func3(0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:108 +0x75
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:103 +0x645

### Steps to Reproduce

```Markdown
1. run a mo cluster on eks with (2*cn, 1*dn, 3*log)
2. load tpch 10g data 
3. run tpch 10g 22 queries about 10 times 

or 

1. git clone https://github.com/matrixorigin/mo-auto-test.git
2. modify .github/workflows/regression-on-distributed-mode.yml, 
  set JobName.default to tpch_benchmark_test
  set RunTimes to 10
3. make a pr to merge, and the job will automatically run the tpch 10g queries for 10 times on eks
```

**Comment by m-schen** [comment]
I have fixed this panic.

**Comment by aressu1985** [comment]
fixed
nightly-5ad2c34
