### ISSUE TITLE
[Bug]: TestForceRefreshLockTableBinds Error occurred in two consecutive CI run

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#8953]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="883" alt="image" src="https://user-images.githubusercontent.com/39627130/231164605-38ba269c-b2fe-4081-85fa-03e840c357d7.png">

https://github.com/matrixorigin/matrixone/actions/runs/4667225397/jobs/8262755697?pr=8950

**Comment by zhangxu19830126** [comment]
fixed
