### ISSUE TITLE
[Bug]: alter table can add constraint for secondary index

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#8958]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> create table t1(a int, b int);
Query OK, 0 rows affected (0.01 sec)

mysql> alter table t1 add CONSTRAINT index t1b(b);
Query OK, 0 rows affected (0.02 sec)

**Comment by qingxinhome** [comment]
Received, confirmed @domingozhang

**Comment by qingxinhome** [comment]
The issue has been resolved, please test @domingozhang @heni02
