### ISSUE TITLE
[Bug]: select query is very slow

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#8966]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8ceec3e0
- Hardware parameters:
- OS type: ubuntu
- Others:
```

### Actual Behavior

```
2023/04/12 06:20:56.780335 +0000 WARN sqlquery/query.go:216 trace {"elapsed": "49.29196906s", "rows": 1, "sql": "/* cloud_nonuser */ SELECT * FROM `mo_cloud`.`operation` WHERE `operation`.`id` = 'a60eac7e-39ca-4199-a4cd-130a3579bba8' AND `operation`.`id` = 'a60eac7e-39ca-4199-a4cd-130a3579bba8' ORDER BY `operation`.`id` LIMIT 1"}
2023/04/12 06:20:56.829349 +0000 WARN meta/meta.go:248 trace {"elapsed": "58.36322478s", "rows": 1, "sql": "/* cloud_nonuser */DESC `db`.`t1` ;"}
2023/04/12 06:20:57.175710 +0000 WARN meta/meta.go:210 trace {"elapsed": "57.31700786s", "rows": 1, "sql": "/* cloud_nonuser */ SHOW CREATE TABLE db.t1"}
2023/04/12 06:20:57.675467 +0000 WARN meta/meta.go:287 trace {"elapsed": "58.052677824s", "rows": 1, "sql": "/* cloud_nonuser */ SELECT attname AS name, mo_show_visible_bin(atttyp,3) AS data_type, replace(mo_table_col_max(att_database,att_relname,attname),'\\0', '') AS `maximum`,  mo_table_col_min(att_database,att_relname,attname) as minimum from mo_catalog.mo_columns where att_database='db' and att_relname='t1' and attname NOT IN  ('__mo_rowid', '__mo_cpkey_col') ORDER BY attnum;"}
```

### Expected Behavior

The queries should be done in ms.

### Steps to Reproduce

```Markdown
NA
```

### Additional information

The cluster has been running for about 48 hours.

**Comment by DanielZhangQD** [comment]
The CN was recreated due to a memory issue, after that, the queries are faster than previous ones.

**Comment by m-schen** [comment]
root cause is mo's speed slow down as running time increase (or maybe memory decrease).

**Comment by m-schen** [comment]
@nnsgmsone  
plz help to dispatch this issue to others of our group. 
I have no time to do that in current. or should wait my finishing my work on hands.

**Comment by DanielZhangQD** [comment]
The issue is hit again:
```
2023/04/14 03:45:00.562467 +0000 WARN instance/instance.go:431 trace {"elapsed": "21.956351867s", "rows": 1, "sql": "INSERT INTO `mo_cloud`.`mo_instance` (`id`,`name`,`account_name`,`provider`,`provider_id`,`region`,`plan_type`,`version`,`status`,`quota`,`network_policy`,`created_by`,`created_at`) VALUES ('74548461-ed82-4b5a-98bd-1884c64e6b9c','Instance_2','74548461_ed82_4b5a_98bd_1884c64e6b9c','aws','141549464311','us-west-2','serverless','nightly-0f1162f','','{\"cu\":10000000,\"storage\":5368709120}','{\"allow_list\":[\"0.0.0.0/0\"]}','2d257e10-de56-4e6e-8a1e-9684ebfb5c40','2023-04-14 03:43:57.182')"}
2023/04/14 03:46:08.244238 +0000 WARN gin@v1.8.2/context.go:173 trace {"elapsed": "45.869639931s", "rows": 0, "sql": "alter account `74548461_ed82_4b5a_98bd_1884c64e6b9c` admin_name 'admin' identified by 'Mo123456';"}
```

**Comment by DanielZhangQD** [comment]
<img width="1322" alt="企业微信截图_524c9cac-89ee-4887-be04-21b81c6771d0" src="https://user-images.githubusercontent.com/36026334/231996840-df3abc80-aea5-4d4f-b147-951a20fe1374.png">
Memory usage of CN, when it reaches a threshold, it will be killed.

**Comment by m-schen** [comment]
no process today.

**Comment by m-schen** [comment]
没有空进行该bug的追踪。

**Comment by m-schen** [comment]
没有空进行该bug的追踪。

**Comment by m-schen** [comment]
没有空进行该bug的追踪。

**Comment by nnsgmsone** [comment]
帮忙看看吧 @w-zr

**Comment by w-zr** [comment]
@DanielZhangQD  Please provide more information such as table definitions, data size, csv files and sql queries.

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD Please provide more information such as table definitions, data size, csv files and sql queries.

It does not matter for the detailed table definitions, data size, csv files or any sql queries, just keep running a normal workload like tpcc, tpch, and you should be able to reproduce this issue.

**Comment by sukki37** [comment]
@DanielZhangQD Any updates on this issue? It's been a while since the last comment.

**Comment by DanielZhangQD** [comment]
The above SQLs are not slow in commit `nightly-f5405008`
