### ISSUE TITLE
[Bug]: ctrl-C twice to kill a `select sleep` query

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#8980]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3d6c907ed
- Hardware parameters:
- OS type: linux/amd64
- Others:
```

### Actual Behavior

Need to press Ctrl-C twice to kill a `select sleep();` query.
![image](https://user-images.githubusercontent.com/28624654/231652691-595bac36-d74b-4c45-9c9a-e682c5026b5f.png)

If use `kill query <connection-id>;`,  it will report `Unknown connection id 1010`
![54a930cc77df725693b368a7494d7d0](https://user-images.githubusercontent.com/28624654/231653061-aefa398b-7ae1-439a-aabe-9c59365c080e.png)

### Expected Behavior

Kill query by one ctrl-C.

**Comment by m-schen** [comment]
same as #7349

**Comment by sukki37** [comment]
Verified in fca43b6d.The issue has been resolved. Closing this issue now. If anyone encounters any related problems, please reopen or comment.
