### ISSUE TITLE
[Bug]: tpcc warehouse table data are not correct after running tpcc 10w 10 terminals test on eks with 2*cn (Occasionally))

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8982]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 0f1162f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In Daily regression on EKS at 2023-04-12（UTC time）, when run TPCC 10w 10 terminals test on eks with 2*cn, the test was hung after several minutes. Then after about 3 hours, the data of tpcc table warehouse became not correct. As following:

1、the count of this table should be 10, but real count is 20. and the w_id is the primary key, but there are some duplicated value for the pk w_id.

mysql> Select w_id, w_ytd from bmsql_warehouse;
+------+-----------+
| w_id | w_ytd     |
+------+-----------+
|    9 | 336154.14 |
|    2 | 333994.50 |
|    3 | 317530.10 |
|    1 | 319224.16 |
|    4 | 340369.33 |
|    8 | 338079.77 |
|   10 | 353042.05 |
|    5 | 325200.22 |
|    6 | 323575.04 |
|    7 | 332742.21 |
|    1 | 483413.98 |
|    2 | 367210.78 |
|    3 | 354501.43 |
|    4 | 351648.86 |
|    5 | 360117.10 |
|    6 | 346958.10 |
|    7 | 365664.98 |
|    8 | 346684.31 |
|    9 | 369540.70 |
|   10 | 377461.14 |
+------+-----------+
20 rows in set (0.01 sec)

2、some table data file can not be found：
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select o_w_id, o_d_id, max(o_id) from bmsql_oorder group by  o_w_id, o_d_id);
ERROR 20405 (HY000): file mo-benchmark/data/8fce329f-d980-11ed-bcbd-d6ab0d3ac679_00019 is not found
mysql> 
mysql> 
mysql> (Select d_w_id, d_id, D_NEXT_O_ID - 1 from bmsql_district)  except (select no_w_id, no_d_id, max(no_o_id) from bmsql_new_order group by no_w_id, no_d_id);
ERROR 20405 (HY000): file mo-benchmark/data/1c509b49-d981-11ed-b1e9-ae086a34b676_00002 is not found
mysql> 
mysql> 
mysql> -- 
mysql> select * from (select (count(no_o_id)-(max(no_o_id)-min(no_o_id)+1)) as diff from bmsql_new_order group by no_w_id, no_d_id) as temp where diff != 0;
ERROR 20405 (HY000): file mo-benchmark/data/1c509b49-d981-11ed-b1e9-ae086a34b676_00008 is not found
mysql> 
mysql> 
mysql> (select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count
    -> (ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
ERROR 20405 (HY000): file mo-benchmark/data/8fce329f-d980-11ed-bcbd-d6ab0d3ac679_00008 is not found

the whole mo log is located in s3 path: s3://mo-ares/mo-benchmark/etl_202304131127

and the test time started from 2023-04-12 22:53:25 

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/47846308/231662547-1e325e39-ebea-467a-b28b-d1d4e88c02a3.png">

### Steps to Reproduce

```Markdown
hard to repro
```

**Comment by ouyuanning** [comment]
maybe like #8077

**Comment by nnsgmsone** [comment]
For pure pull mode, this issue may not be fixed. Only this issue will be fixed for pull in push mode again

**Comment by nnsgmsone** [comment]
For pure pull mode, this issue may not be fixed. Only this issue will be fixed for pull in push mode again

**Comment by nnsgmsone** [comment]
For pure pull mode, this issue may not be fixed. Only this issue will be fixed for pull in push mode again

**Comment by nnsgmsone** [comment]
For pure pull mode, this issue may not be fixed. Only this issue will be fixed for pull in push mode again

**Comment by nnsgmsone** [comment]
For pure pull mode, this issue may not be fixed. Only this issue will be fixed for pull in push mode again
