### ISSUE TITLE
[Bug]: push is about three times slower than pull mode on eks bvt test

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9001]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6b7eff1c3935b1b9de24f9448f287a07e6b960d4 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

push on eks bvt test ，pull mode 20min+，push mode 1h+
and almost all cases are about three times slower than pull mode
<img width="1238" alt="wecom-temp-3235800-be02082c4bf46563aaebc76501f94edb" src="https://user-images.githubusercontent.com/113406637/232011890-13fb03d0-6f12-4f0d-9b1f-967e01b70fb7.png">

push configuration is as follows：
<img width="489" alt="企业微信截图_d688d091-b1fc-43f4-803b-74eef4d6137b" src="https://user-images.githubusercontent.com/113406637/232012300-d78742e5-88a0-4d33-a24d-e7a98716d9ac.png">

I tested 2cn on/off no wait  and  1cn on/off no wait tests，the results are all about three times slower than the pull mode

### Steps to Reproduce
auto_increment_columns.sql push mode cost 90s+,pull mode cost 12s+, 
perhaps the following SQL which in auto_increment_columns.sql file can compare the performance of the two

create table t1(
a bigint primary key auto_increment,
b varchar(10)
);
show create table t1;
insert into t1(b) values ('bbb');
-- echo error msg: tae data: duplicate
insert into t1 values (1, 'ccc');
insert into t1 values (3, 'ccc');
insert into t1(b) values ('bbb1111');
select * from t1 order by a;

**Comment by sukki37** [comment]
@reusee please help debug on this, thank you.

**Comment by reusee** [comment]
investigating

**Comment by reusee** [comment]
sick leaving will continue tomorrow afternoon.

**Comment by sukki37** [comment]
I did some go profiling on push mode and seems that IO cost most of the time, but not sure where the io happened.

CN1 results are as follows: 
[cn1.cpu.pb.gz](https://github.com/matrixorigin/matrixone/files/11251298/cn1.cpu.pb.gz)

<img width="506" alt="image" src="https://user-images.githubusercontent.com/77312370/232516346-9b93bb70-e1b6-4f42-b38d-5beeab892352.png">

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/77312370/232516499-cff79ad8-e035-487e-8772-4a4faeb5722c.png">

<img width="1149" alt="企业微信截图_2b63c08d-b0f7-4a3c-92f3-658f082c67f9" src="https://user-images.githubusercontent.com/77312370/232516583-1ae62665-6927-4645-a6a2-a721fb5f7663.png">

**Comment by sukki37** [comment]
> I did some go profiling on push mode and seems that IO cost most of the time(much more io count than pull mode), but not sure where the io happened.
> 
> CN1 results are as follows: [cn1.cpu.pb.gz](https://github.com/matrixorigin/matrixone/files/11251298/cn1.cpu.pb.gz)
> 
> <img alt="image" width="506" src="https://user-images.githubusercontent.com/77312370/232516346-9b93bb70-e1b6-4f42-b38d-5beeab892352.png">
> 
> <img alt="image" width="1426" src="https://user-images.githubusercontent.com/77312370/232516499-cff79ad8-e035-487e-8772-4a4faeb5722c.png">
> 
> <img alt="企业微信截图_2b63c08d-b0f7-4a3c-92f3-658f082c67f9" width="1149" src="https://user-images.githubusercontent.com/77312370/232516583-1ae62665-6927-4645-a6a2-a721fb5f7663.png">
> 
> CN0: [cn0.cpu.pb.gz](https://github.com/matrixorigin/matrixone/files/11251342/cn0.cpu.pb.gz) <img alt="image" width="415" src="https://user-images.githubusercontent.com/77312370/232517434-6c9455a4-095a-4c2f-a82f-a6e4298e9737.png"> <img alt="image" width="1366" src="https://user-images.githubusercontent.com/77312370/232517505-943675bd-c92e-4f15-8916-4e2ed7fa0193.png"> <img alt="企业微信截图_ae9b9375-3120-4cc1-98f3-3e2438de90d3" width="1109" src="https://user-images.githubusercontent.com/77312370/232517634-06a05461-6345-4384-9fb8-e58f2eeba2e2.png">

Perfcounter of `pull` mode is as follows (same configuration and workload), which is far less than `push` mode.
![cn0-io-count-pull](https://user-images.githubusercontent.com/77312370/232542007-9287338b-ea07-4ea3-9a45-fa5baffb65ce.png)


![cn1-io-count-pull](https://user-images.githubusercontent.com/77312370/232541836-eb87fc1e-c9e0-4321-9d60-7be0cad2da45.png)

**Comment by sukki37** [comment]
please help with this, thank you. @LeftHandCold

**Comment by LeftHandCold** [comment]
The eks environment needs to modify the configuration
      [dn.LogtailServer]
      rpc-max-message-size = "16KiB"
      rpc-payload-copy-buffer-size = "16KiB"
      rpc-enable-checksum = true
      logtail-collect-interval = "2ms"
      logtail-response-send-timeout = "10s"
      max-logtail-fetch-failure = 5

**Comment by heni02** [comment]
confirm，closed
pull and push mode same cost
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4733390408/jobs/8401202799
![image](https://user-images.githubusercontent.com/113406637/232954244-be6ddea6-e847-4b9a-924e-73d0e261f1c2.png)
