### ISSUE TITLE
[Bug]: push mode：login account to view mo_ user password error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9022]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):985fc7c3c616218f55461dd4fdfbaa4cf913accb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/matrixone/actions/runs/4716536559/jobs/8364353359?pr=8891
![image](https://user-images.githubusercontent.com/113406637/232437955-50c1586f-10aa-4dec-92d5-f3c5edc78f51.png)
![image](https://user-images.githubusercontent.com/113406637/232438525-1eaf3236-5158-4101-b1eb-7061602b412b.png)
After reviewing the upper and lower cases, it was found that the data before and after the modification would be misread

**Comment by aunjgr** [comment]
@m-schen Please have a look first

**Comment by m-schen** [comment]
I think `no wait` may cause this bug.
the previous sql of the failed sql is 
`alter account and admin_name='admin' identified by 'yyyy_34lifel'`. 

if log tail of this sql hadn't push to cn node yet, and we start a new sql to query. the txn can start, and will get a wrong result. @zhangxu19830126

**Comment by zhangxu19830126** [comment]
fixed，use newest mo-tester

**Comment by heni02** [comment]
Occasional problems, observe the regression testing results for two days

**Comment by heni02** [comment]
yesterday bvt test do not found this issue ，Observe the results again tomorrow
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4804380836/jobs/8550007309

**Comment by heni02** [comment]
no this issue anymore
confirm，closed
