### ISSUE TITLE
[Bug]: Description Failed to publish the db to tenant all.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#9024]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b5e27c495847c08513755790e903611ea0e9ec4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
create account test_tenant_1 admin_name 'test_account' identified by '111';
create account test_tenant_2 admin_name 'test_account' identified by '111';
create account test_tenant_3 admin_name 'test_account' identified by '111';
create account test_tenant_4 admin_name 'test_account' identified by '111';
create database db4;
use db4;
create table t4(a int);
mysql> create publication pubname3 database db4 account all comment 'publication to all tenant';
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 52 near " all comment 'publication to all tenant'";
```

### Expected Behavior

tenant `all` should also support publication.

**Comment by YANGGMM** [comment]
dose this should support? @domingozhang , it doesn't appear in publish document.

**Comment by YANGGMM** [comment]
you can see the document @tianyahui-python , ACCOUNT，分享发布给目标租户的完整列表，创建时缺省则分享给所有租户，分享给所有租户时，新建的租户同样生效。而且也有相应的测试用例你可以看一下。

**Comment by tianyahui-python** [comment]
> you can see the document @tianyahui-python , ACCOUNT，分享发布给目标租户的完整列表，创建时缺省则分享给所有租户，分享给所有租户时，新建的租户同样生效。而且也有相应的测试用例你可以看一下

这个bug 描述的具体信息是: 是如何处理all关键字的, 这个跟潇哥确认过, 说把all当成正常的account name来处理, 这个跟缺省没关系

**Comment by domingozhang** [comment]
create publication pbname database db1 account all，其中account all这个部分会在0.9去实现

**Comment by tianyahui-python** [comment]
testing

**Comment by tianyahui-python** [comment]
> create publication pbname database db1 account all，其中account all这个部分会在0.9去实现

这个期望的行为应该是什么 @domingozhang  
这个现在是按照什么逻辑实现的 @YANGGMM

**Comment by tianyahui-python** [comment]
走到qa的issue, 尽可能的要说明具体的情况, 或者对应的链接文档 @YANGGMM

**Comment by YANGGMM** [comment]
目前，all是按所有的逻辑处理的 @tianyahui-python

**Comment by tianyahui-python** [comment]
sys tenant：
<img width="1331" alt="截屏2023-06-12 17 44 13" src="https://github.com/matrixorigin/matrixone/assets/39303074/580cf507-e47d-4699-95ea-594f5db08afe">

test_tenant_1:
<img width="1653" alt="截屏2023-06-12 17 44 25" src="https://github.com/matrixorigin/matrixone/assets/39303074/41c5aed7-53a9-45e0-9a14-c29c89936371">

**Comment by tianyahui-python** [comment]
bug not fixed

**Comment by YANGGMM** [comment]
because you not subscribe the publication, so you not get the database. @tianyahui-python
