### ISSUE TITLE
[Bug]: column precision is incorrect in DESC TABLE

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#9032]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="468" alt="1681788760846" src="https://user-images.githubusercontent.com/88298673/232664145-60ba18c3-8323-4ed0-a3a0-6f64d93338a2.png">

The precision is not the given value in DDL.

**Comment by YANGGMM** [comment]
create table test(a time(3), b datetime(4), c timestamp(5));

**Comment by Ariznawlll** [comment]
<img width="619" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/b03b665a-ec80-49cd-9cbb-9e2d216ddc70">

Verified!
