### ISSUE TITLE
[Bug]: precision of deciaml converted by time types is incorrect

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#9033]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/88298673/232664478-30358bdb-8fb0-4b18-89ff-735bfa2b2f2f.png)

The expected result should be 1640995262.123

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/232721898-92d57e3a-d71f-4f52-b629-0e27195c6d7f.png)

test done!
