### ISSUE TITLE
[Bug]: The db published by the current tenant should not be subscribed to by the current tenant.

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#9045]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b5e27c495847c08513755790e903611ea0e9ec4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create database db1;
mysql> create publication pubname4 database db1 comment 'publication to all tenant';
Query OK, 0 rows affected (0.03 sec)

mysql> create database sub_db4 from sys publication pubname4;
Query OK, 1 row affected (0.08 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_task            |
| information_schema |
| mysql              |
| system_metrics     |
| system             |
| db1                |
| sub_db4            |
| mo_catalog         |
+--------------------+
8 rows in set (0.01 sec)

**Comment by aunjgr** [comment]
What is the expected behavior?

**Comment by arjunsk** [comment]
I see all the details inside `mo_pubs`.
![image](https://user-images.githubusercontent.com/9638314/232921674-171c7bfc-e084-4554-9b19-4ece5d0cf783.png)

The publication info is visible using `SHOW PUBLICATIONS`
![image](https://user-images.githubusercontent.com/9638314/232921732-ee8807bf-62d8-433c-a6c5-5b611562fe22.png)

Could you please share the expected behavior?

**Comment by arjunsk** [comment]
@mooleetzi I see that this `Publication` feature was introduced in this PR: https://github.com/matrixorigin/matrixone/pull/8358

Please have a look. Apologies if you are not the right person to reach out.

**Comment by tianyahui-python** [comment]
<img width="888" alt="截屏2023-05-07 下午3 20 00" src="https://user-images.githubusercontent.com/39303074/236663680-6f7d5308-9b92-4bde-86b7-39fa2bd7da16.png">
