### ISSUE TITLE
[Bug]: The result of time conversion to decimal is incorrect

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9051]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:f82fb741ff87e5018098e4a4630f6e435c412d7f
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/232748011-2a485f53-0c0c-4b88-b393-db3b3d3fd5c6.png)

### Expected Behavior

159.0000000000
235959.0000000000
null

### Steps to Reproduce

```Markdown
drop table if exists test04;
create table test04(col1 time);
insert into test04 values('00:01:59');
insert into test04 values('23:59:59');
insert into test04 values(NULL);
select cast(col1 as decimal(20,10)) from test04;
```

**Comment by zengyan1** [comment]
fixed

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/233024015-c5f298e7-2d34-4553-8715-9c51abd294d9.png)

test done!
