### ISSUE TITLE
[Bug]: The dat_createsql field of the mo_database table lacks the mo_catalog table creation clause

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9066]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:a181a764b7a6d5ae2b9c27bb544b9d77fe9f520e
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/232961873-cc851670-7e16-4f4a-8c6f-cbead4552f70.png)

### Expected Behavior

dat_createsql displays the mo_catalog database creation statement.

### Steps to Reproduce

```Markdown
use mo_catalog;
select * from mo_database;
```

**Comment by daviszhen** [comment]
mo_catalog 这个数据库不是用create database 创建的。是存储内部提供的。没有create sql。
