### ISSUE TITLE
[Bug]: mo_database metadata table field value optimization

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9073]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:ba65ac49f21c1ed1cc532ef68df481f40f2d3dd0
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233047991-ca33d354-8ad1-4de2-a934-63d2dbac9f95.png)

### Expected Behavior

0

### Steps to Reproduce

```Markdown
use mo_catalog;
select * from mo_database;
```

**Comment by daviszhen** [comment]
> @daviszhen Could you kindly have a look? Please assign it to the appropriate person, if you are not the right person.

I will.

**Comment by YANGGMM** [comment]
this is normal behavior @Ariznawlll

**Comment by Ariznawlll** [comment]
test done!
