### ISSUE TITLE
[Bug]: Succeeded in publishing a non-existent database

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#9076]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b5e27c495847c08513755790e903611ea0e9ec4d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

This is an unstable recurring bug.

<img width="1618" alt="截屏2023-04-19 20 42 47_副本" src="https://user-images.githubusercontent.com/39303074/233080070-f8f849ce-fdee-4424-91db-d41f0cc18953.png">
<img width="1515" alt="截屏2023-04-19 20 45 08_副本" src="https://user-images.githubusercontent.com/39303074/233080333-4f176444-8e44-43af-90fb-c78e0d21d238.png">

### Expected Behavior

Publishing a database that does not exist should result in an error.

**Comment by tianyahui-python** [comment]
The specific cause has been identified, sys tenant publication test_tanant_1 tentan database.

<img width="963" alt="截屏2023-04-19 21 03 07" src="https://user-images.githubusercontent.com/39303074/233083225-e725a4ec-b2be-4c36-935f-20f712139ae8.png">

**Comment by YANGGMM** [comment]
@tianyahui-python  is there still has this problem?

**Comment by tianyahui-python** [comment]
test_tenant_1:
<img width="518" alt="截屏2023-05-07 下午2 48 13" src="https://user-images.githubusercontent.com/39303074/236662339-98304268-2f6a-4bac-9711-93bc5bdf0e58.png">


sys:
<img width="953" alt="截屏2023-05-07 下午2 48 21" src="https://user-images.githubusercontent.com/39303074/236662341-fbf1f5c5-a014-438d-bcda-87869b5fd991.png">
