### ISSUE TITLE
[Bug]: the createtime of mo_database is not consistent with the createtime of mo_account;

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9081]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id：b00ddf2f31cd7492d7e28504aad7b150a269ca0c
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233245849-272864d7-4044-4bf1-adb5-1b8b7364c2c1.png)

### Expected Behavior

the createtime of mo_database should be consistent with the createtime of mo_account;

### Steps to Reproduce

```Markdown
create account 123account admin_name = 'root' identified by '111' open comment 'abccomment';
use mo_catalog;
select * from mo_account;
select * from mo_database;
```

**Comment by aunjgr** [comment]
It's precisely a 7 hour difference.

@daviszhen You are the author of these `created_time`s. Please also have a look.

**Comment by Ariznawlll** [comment]
**the same question:**
drop database if exists test;
create database test;
use test;
create publication pub1 database test account sys comment 'ABC publish';
select * from mo_catalog.mo_pubs;

the create_time is not correct.

**Comment by jensenojs** [comment]
<img width="1310" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/4ff62478-51e5-4dd7-842d-e3fa4a39d762">

match now, as well as @Ariznawlll tested

<img width="1725" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/d23219da-93c2-47b3-8f1e-471458118448">

**Comment by Ariznawlll** [comment]
test done!
![image](https://github.com/matrixorigin/matrixone/assets/108530700/2417bdbc-7906-4150-acf2-41b8c24c3877)
time zone:Tue, 13 Jun 2023 10:52:51 +0800
