### ISSUE TITLE
[Feature Request]: Support setting sql_mode in toml config file

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9082]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
Mysql supports 3 ways to set sql_mode parameter:
1. `set session sql_mode='xxx';`, which is only effective in current session
2. `set global sql_mode='xxx';`, which is effective in all sessions until the next restart of the server, but a re-connect will be required
3. change my.cnf（linux/mac）or my.ini（windows）file by adding below content, and restart mysql server

[mysqld]
sql_mode='xxx'
# e.g. 
# sql_mode='only_full_group_by,no_auto_value_on_zero,strict_trans_tables,no_zero_in_date,no_zero_date,
error_for_division_by_zero,no_auto_create_user,pipes_as_concat,ansi_quotes'


Currently MO supports the first 2 ways above, but not yet supports the 3rd way.
```

### Describe the feature you'd like

Support allow setting sql_mode parameter in a config file(like cn.toml), and make this paramter to take effect after starting/restarting mo service.

### Describe implementation you've considered

see above

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
see:
https://github.com/matrixorigin/MO-Cloud/issues/558
```

### Additional information

none

**Comment by domingozhang** [comment]
parent task of https://github.com/matrixorigin/matrixone/issues/9096

**Comment by aronchanisme** [comment]
Wait until bug https://github.com/matrixorigin/matrixone/issues/9689 is resolved

**Comment by aronchanisme** [comment]
> Wait until bug #9689 is resolved

Wait until bug https://github.com/matrixorigin/matrixone/issues/9689 and #9696   is resolved

**Comment by aronchanisme** [comment]
全部测试点都通过了
1、不同租户之间，set global不能相互影响，通过
https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636709725

2、同一租户，set global后多CN也就是租户层面全局生效
同一用户：https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636709725
不同用户：https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636718869

3、同一租户之间，set global后，重启服务仍然生效（即类似mysql配置文件修改后，重启mysql进程仍生效）
https://github.com/matrixorigin/matrixone/issues/9689#issuecomment-1636710684
