### ISSUE TITLE
[Bug]: Pods in an MO Cluster does not have persist service activity logs into persistent layer like disks

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9091]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): all current versions
- Hardware parameters: an mo cluster env, based on linux servers like debian
- OS type: debian for example
- Others:
```

### Actual Behavior

Currently in an MO cluster environment, all MO pods including cn, dn, log service, does not persist logs into a persistent layer like local disk, nfs, or s3 obect storage. The only way to check logs is by `kubectl logs ${pod_name} -nmo-hn`.
This may not be a problem in a test environment, however it's probably a big issue when it comes to production. For example, when all of the pods are abnormal due to unknow reasons under some cercumstances, it will be impossible to check the logs to see what has happended to cause the issues.
<img width="829" alt="企业微信截图_5eac356a-0576-4bc4-88b2-a7db6d1ba2bb" src="https://user-images.githubusercontent.com/46433151/233330500-c249e53a-81c6-4579-bf06-5a962c1a7d20.png">

### Expected Behavior

Is it possible that we can persist the logs into a persistent layer? Like a local path of a local disk on which the pod is running. This can be done by using volumes and volumeMounts when defining the container's spec. Also we need to consider how to clean up old logs(like logs older than a month, which should be configurable) once they grow bigger and bigger as time goes by. This is particularly important when the log level is set to DEBUG, let's say. 

### Steps to Reproduce

```Markdown
1. Service activity logs can only be seen via `kubectl logs ${pod_name} -nmo-hn`
2. Something bad happends and all pods are not in running state
3. We are not able to check the logs anymore until all the pods are back in running state again, or it will only be possible if we check them in advanced via `kubectl logs -f ${pod_name} -nmo-hn > /tmp/${pod_name}.log`, for example.
```

### Additional information

none

**Comment by aunjgr** [comment]
As far as I can tell, MO supports a `filename` attribute in the `[log]` section. You can set it to save logs to disk file.

**Comment by DanielZhangQD** [comment]
@aronchanisme As a best practice in Kubernetes, you have to deploy a log collection solution in your Kubernetes cluster, not only for the logs of MO, but for all the applications in your Kubernetes cluster.
There are many log solutions for Kubernetes, and you can research and choose one.

**Comment by arjunsk** [comment]
Hi @aronchanisme , Please look into the suggested feedback and revert back if it doesn't work.

**Comment by aronchanisme** [comment]
As discussed in internal meeting, logs printed in stdout/stderr in k8s is a by design feature. Solution for observability should be discussed first. Thus I am holding this issue as for now.
