### ISSUE TITLE
[Bug]: auto incr panic after truncating the table

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#9095]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):e973bd0ab5bddfea1815a6c9fc94be4c68bf5f0f
- Hardware parameters:mac
- OS type:mac os
- Others:
```

### Actual Behavior

--session 1 start--
create database db;
use db;
create table t2(a int auto_increment,b int);
insert into t2(b) values (1);
select * from t2;
begin;
--session 2 start --
use db;
truncate t2;
--session 2 end--
insert into t2(b) values (1); // panic 
ERROR 20101 (HY000): internal error: panic unreachable: 
github.com/matrixorigin/matrixone/pkg/sql/colexec.getCurrentIndex
	/Users/pengzhen/Documents/GitHub/matrixone/pkg/sql/colexec/auto_incr.go:508
github.com/matrixorigin/matrixone/pkg/sql/colexec.getOneColRangeFromAutoIncrTable
	/Users/pengzhen/Documents/GitHub/matrixone/pkg/sql/colexec/auto_incr.go:348
github.com/matrixorigin/matrixone/pkg/sql/colexec.getNextOneCache
	/Users/pengzhen/Documents/GitHub/matrixone/pkg/sql/colexec/auto_incr.go:134
github.com/matrixorigin/matrix
--session 1 end--

### Expected Behavior

no panic

**Comment by daviszhen** [comment]
经过分析，是truncate t2导致t2的tableID 变化。old_tableid => new_tableid.
并且自增列表的记录old_tableid_a被删掉。增加了新纪录new_tableid_a。
但是session 1 还是拿old_tableid_a 从自增列表中去取。取不到任何值，最终panic。

**Comment by daviszhen** [comment]
自增列都被自增服务替换了

**Comment by sukki37** [comment]
Verified in e245b8c80c42b9d4439ab03ee7a7c087c319cbb0. This issue has been resolved. Closing this issue now. If anyone encounters any related problems, please reopen or comment.

**Comment by matrix-meow** [comment]
Hello @daviszhen. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @daviszhen. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by aressu1985** [comment]
有个BVTissue，需要提PR去掉，放到1.2

**Comment by daviszhen** [comment]
未投入
