### ISSUE TITLE
[Subtask]: Support synonyms for alter account config

### ISSUE THREAD

**Issue by domingozhang** [matrixorigin/matrixone#9096]
### Parent Issue

https://github.com/matrixorigin/matrixone/issues/6669
https://github.com/matrixorigin/matrixone/issues/9082

### Detail of Subtask

set global
set persist
alter account config current_account_name

make these as synonyms and modified values can be inserted into mo_mysql_compatbility_mode

In metadata table, add two id columns for account and database

**Comment by aronchanisme** [comment]
全部测试点都通过了
1、不同租户之间，set global不能相互影响，通过
https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636709725

2、同一租户，set global后多CN也就是租户层面全局生效
同一用户：https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636709725
不同用户：https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636718869

3、同一租户之间，set global后，重启服务仍然生效（即类似mysql配置文件修改后，重启mysql进程仍生效）
https://github.com/matrixorigin/matrixone/issues/9689#issuecomment-1636710684
