### ISSUE TITLE
[Bug]: panic when insert into partition sub table with auto_increment column directly.

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#9102]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): add hide key
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CREATE TABLE t1 (
col1 INT NOT NULL,
col2 DATE NOT NULL,
col3 INT NOT NULL UNIQUE
)
PARTITION BY KEY(col3)
PARTITIONS 4;
insert into `%!%p0%!%t1` values (1, '1980-12-17', 7369),(2, '1981-02-20', 7499),(3, '1981-02-22', 7521),(4, '1981-04-02', 7566),(5, '1981-09-28', 7654);

internal error: panic unreachable: 
github.com/matrixorigin/matrixone/pkg/sql/colexec.getCurrentIndex
	/Users/pengzhen/Documents/GitHub/customer/matrixone/pkg/sql/colexec/auto_incr.go:509
github.com/matrixorigin/matrixone/pkg/sql/colexec.getOneColRangeFromAutoIncrTable
	/Users/pengzhen/Documents/GitHub/customer/matrixone/pkg/sql/colexec/auto_incr.go:349
github.com/matrixorigin/matrixone/pkg/sql/colexec.getNextOneCache
	/Users/pengzhen/Documents/GitHub/customer/matrixone/pkg/sql/colexec/auto_incr.go:135

### Expected Behavior

no panic

**Comment by daviszhen** [comment]
原表的字段在自增列表中有字段。子表上面没有。要先思考下怎么改。

**Comment by qingxinhome** [comment]
Be aware of the issue and handle it in the future

**Comment by qingxinhome** [comment]
The solution to this bug depends on the partition branch and cannot be submitted temporarily

**Comment by qingxinhome** [comment]
The solution to this bug depends on the partition branch and cannot be submitted temporarily

**Comment by qingxinhome** [comment]
The issue has been resolved, please confirm @daviszhen

**Comment by daviszhen** [comment]
it was done
