### ISSUE TITLE
[Bug]: insert timeout when the has the auto_incement column 

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#9105]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):hide pk key
- Hardware parameters:mac
- OS type:
- Others:
```

### Actual Behavior

drop table if exists t;
create table t(a int);
insert into t values(1);
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;// 131072  rows. insert needs 2.9sec
select count(*) from t;
insert into t select * from t; // more than 131072 rows. may timeout for mo-tester 6s. same as following.
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;
insert into t select * from t;
select count(*) from t;

### Expected Behavior

insert success

**Comment by daviszhen** [comment]
表t自动加了隐藏主键，是自增列。当insert数据量增加一定阈值后，由于插入时间过长。导致mo-tester超时，bvt 挂掉。

**Comment by ouyuanning** [comment]
i think this was fixed in my branch(for split plan)

**Comment by daviszhen** [comment]
> i think this was fixed in my branch(for split plan)

ok, it is done
