### ISSUE TITLE
[Bug]: tpch query will be hung on eks with 2*cn when one cn is killed duaring test(push mode)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9107]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-d8f67c2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

For mo started on eks with 2*cn , duaring the tpch test, if one of cn pod was killed, the next query will be hung.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/47846308/233556747-57c63af4-33bd-4699-8e12-096cfaade2b6.png">

error log:
[tpch_hung.tar.gz](https://github.com/matrixorigin/matrixone/files/11292854/tpch_hung.tar.gz)

### Expected Behavior

One cn pod crashing should not affect any following queries 

### Steps to Reproduce

```Markdown
1. run mo cluster on eks with 2*cn.
2. run tpch 10G queries continuously
3. kill a cn pod duaring tpch test
```

**Comment by aressu1985** [comment]
the go routine proflie:

[mo-hung.txt](https://github.com/matrixorigin/matrixone/files/11303073/mo-hung.txt)

**Comment by aunjgr** [comment]
Only be observed on PUSH mode?

**Comment by aressu1985** [comment]
after discussed with @nnsgmsone and @zhangxu19830126 , this issue should assign to @dongdongyang33 or @m-schen

**Comment by m-schen** [comment]
可能是在pipeline.cleanup函数卡住了。
现在的清理流程可能会卡死在merge算子的free流程中。我需要确定一下。

**Comment by dongdongyang33** [comment]
fixing

**Comment by dongdongyang33** [comment]
waiting pr merge

**Comment by aressu1985** [comment]
fixed
