### ISSUE TITLE
[Bug]: hidden primary key column collides with the cluster by

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/matrixone#9109]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

--create_table.test

create table test01(a int, b int) cluster by a;
create table test02(a int, b int) cluster by b;

DN panic

### Expected Behavior

no panic.

**Comment by daviszhen** [comment]
不止这些case。

**Comment by XuPeng-SH** [comment]
should be implemented by #9140. @jiangxinmeng1 pls assign back to the assigner

**Comment by jiangxinmeng1** [comment]
implemented by https://github.com/matrixorigin/matrixone/pull/9140

**Comment by daviszhen** [comment]
it was done
