### ISSUE TITLE
[Bug]: The creation time in the mo_tables table was incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9110]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id: 3f9b25d3d8bc7e69a9de5ced1fe6f062e3532c7d
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233570619-68b17f88-3d19-4fd2-8ba0-6c32893c1858.png)

### Expected Behavior

The actual time of created_time is 2023-04-21 15: : .

### Steps to Reproduce

```Markdown
use mo_catalog;
select rel_id,relname,reldatabase,reldatabase_id,relpersistence,relkind,created_time from mo_tables;
```

**Comment by nnsgmsone** [comment]
这个可能需要查看调用传的值是什么了

**Comment by jensenojs** [comment]
<img width="1710" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/600f76ce-3c70-4818-bb82-5dcbc83da22c">

The creation time is now correct under the corresponding configuration

**Comment by Ariznawlll** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/108530700/37afc790-c897-409f-86c6-7b7ae34359f3)
time zone: Tue, 13 Jun 2023 10:52:51 +0800
test done!
