### ISSUE TITLE
[Bug]: The view definition statement shows garbled code.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9116]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id：3f9b25d3d8bc7e69a9de5ced1fe6f062e3532c7d
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233620830-ea1f3621-80e2-4afd-9b29-8a7c53234e3a.png)

### Expected Behavior

View definition statement

### Steps to Reproduce

```Markdown
use mo_catalog;
select select rel_id,relname,reldatabase,reldatabase_id,relpersistence,partitioned,partition_info,viewdef from mo_catalog.mo_tables limit 30;
```

**Comment by aunjgr** [comment]
Seems that the type of `viewdef` is `binary`.

@ouyuanning Is this behavior expected?

**Comment by Ariznawlll** [comment]
test done！
![image](https://user-images.githubusercontent.com/108530700/236616755-af7991c9-3452-416a-95d0-2d508792bcc8.png)
