### ISSUE TITLE
[Bug]: Incorrect avg results lead to occasional failures in bvt testing.

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9117]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): a fork branch
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/77312370/233756385-7764fa1a-d579-4069-b739-10a2412709a8.png">

https://github.com/matrixorigin/matrixone/actions/runs/4766807753/jobs/8474294370?pr=9106

[logs_115187.zip](https://github.com/matrixorigin/matrixone/files/11300050/logs_115187.zip)

### Expected Behavior

This issue may be caused by the following reasons: If a transaction takes multiple snapshots of the same table using cn, and disk flushing actions occur between the two snapshots, cn will mix these two snapshots, resulting in the recording of disk blocks taken during the first snapshot, as well as the memory table in the latest snapshot. As a result, data in the memory table is missed. 

Please kindly resolve this issue after your physical recovery @reusee. Thank you.

**Comment by sukki37** [comment]
I'll assign the issue to @reusee next Monday, assuming he's back in the office.

**Comment by cnutshell** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/20291742/233822752-2ca0498b-36da-454e-8483-07cd72adb0c6.png">

`multi-cn-e2e` bvt test was failed on linux x86.

[Link for bvt log](https://github.com/matrixorigin/matrixone/actions/runs/4776647958/jobs/8491930563?pr=9123)

**Comment by reusee** [comment]
Looking into it.

**Comment by reusee** [comment]
investigating

**Comment by sukki37** [comment]
> <img alt="image" width="813" src="https://user-images.githubusercontent.com/20291742/233822752-2ca0498b-36da-454e-8483-07cd72adb0c6.png">
> 
> `multi-cn-e2e` bvt test was failed on linux x86.
> 
> [Link for bvt log](https://github.com/matrixorigin/matrixone/actions/runs/4776647958/jobs/8491930563?pr=9123)

This one seems another issue, tracked by #9176

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/commit/2d41f673672f1ec5998b87a9d6572742319ddcaf

**Comment by reusee** [comment]
re-assigning

**Comment by sukki37** [comment]
testing
