### ISSUE TITLE
[Bug]:  The data type of the column in mo_calalog.mo_columns is displayed incorrectly.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9120]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:92da442292c00844394b47c34cd12daa22717c86
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233817375-7c9858fb-2246-4b06-81a8-b3e97f01a5f8.png)

### Expected Behavior

Correct type.

### Steps to Reproduce

```Markdown
use mo_catalog;
select att_uniq_name,atttyp from mo_catalog.mo_columns limit 10;
```

**Comment by nnsgmsone** [comment]
按照设计，这个应该是用display函数显示的 @Ariznawlll
