### ISSUE TITLE
[Bug]: The att_default column in the mo_columns table is incorrectly displayed

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9127]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:92da442292c00844394b47c34cd12daa22717c86
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233823076-f8e52eed-1438-4655-a928-d65448c9a427.png)

### Expected Behavior

The true value of the default expression

### Steps to Reproduce

```Markdown
use mo_catalog;
select att_uniq_name,account_id,att_database_id,att_default from mo_catalog.mo_columns where att_database_id=1 limit 1;
```

**Comment by nnsgmsone** [comment]
按照设计，这个应该是用display函数显示的 @Ariznawlll
