### ISSUE TITLE
[Bug]: The hidden column of the compound primary key is marked incorrectly

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9128]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:92da442292c00844394b47c34cd12daa22717c86
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233824084-bfa37c5c-4bfa-4a7a-a761-0607fa5b02a3.png)
![image](https://user-images.githubusercontent.com/108530700/233824098-b3c78dc7-f709-4214-9ebf-1ce42fcf5200.png)

### Expected Behavior

should be 1

### Steps to Reproduce

```Markdown
use mo_catalog;
select att_uniq_name,account_id,att_database_id,att_database,att_relname,att_relname_id, attname, attnum, attnotnull,atthasdef,attisdropped,att_is_hidden from mo_catalog.mo_columns;
```

**Comment by aunjgr** [comment]
For 1st case:

The compound key in index table should not be hidden. It's the primary key of that table.

For 2nd case:

I'm not sure why mo_catalog.mo_indexes has a compound primary key itself and what it comprises.

@qingxinhome Please have a look.

**Comment by qingxinhome** [comment]
Okay, I'll handle it

**Comment by qingxinhome** [comment]
The issue has been resolved, please test @Ariznawlll @aunjgr

**Comment by Ariznawlll** [comment]
![image](https://user-images.githubusercontent.com/108530700/234464761-b79ab5fd-7ed9-456e-ad97-2cc422534252.png)
test done!
