### ISSUE TITLE
[Bug]: The time of authenticate may be too long

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#9130]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The cost of permission validation should be close to 0 for cases where no changes in permissions have occurred

### Expected Behavior
zero cost

### Steps to Reproduce

see issue https://github.com/matrixorigin/matrixone/issues/5530
_No response_

**Comment by nnsgmsone** [comment]
thank you @daviszhen , i need your help

**Comment by daviszhen** [comment]
> thank you @daviszhen , i need your help

你为什么觉得能做到接近0？

**Comment by daviszhen** [comment]
还没看。

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
还没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by daviszhen** [comment]
没看

**Comment by fengttt** [comment]
> > thank you @daviszhen , i need your help
> 
> 你为什么觉得能做到接近0？

other than first access, should hit permission cache and cost should be near zero.

**Comment by daviszhen** [comment]
没看。

**Comment by daviszhen** [comment]
开发中

**Comment by daviszhen** [comment]
测试中。

**Comment by daviszhen** [comment]
接着观察

**Comment by daviszhen** [comment]
在pr增加了cache。 https://github.com/matrixorigin/matrixone/pull/10151

pr的结果:
https://user-images.githubusercontent.com/60595215/247044368-6b2de1cf-982c-431b-b324-e0c4b35d9f8b.png

之前的结果:
https://user-images.githubusercontent.com/60595215/247044419-9b68c6e6-0497-4f21-8127-f44f0b4836ce.png
