### ISSUE TITLE
[Bug]: Daily Regression can not be successful on eks with 2*cn in push mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9135]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-5c2e40d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/47846308/233838852-ba7ab8fb-f3bb-4d56-9a07-2ffd099ec5ce.png">

**Comment by aressu1985** [comment]
has discussed with @nnsgmsone ,he known everything of this issue

**Comment by nnsgmsone** [comment]
GOMEMLIMIT=10000MiB can be useful for you. i will fix the tp memory later. @aressu1985

**Comment by nnsgmsone** [comment]
wait for testing

**Comment by nnsgmsone** [comment]
wait for testing

**Comment by nnsgmsone** [comment]
wait for testing

**Comment by nnsgmsone** [comment]
wait for testing

**Comment by nnsgmsone** [comment]
Found that prepare did not work well and continued to track

**Comment by nnsgmsone** [comment]
memory profile:
![截图 2023-05-04 21-55-41](https://user-images.githubusercontent.com/31609524/236229220-9bb85994-9dfb-4fb3-8edf-463879c4bb62.png)
![截图 2023-05-04 21-56-02](https://user-images.githubusercontent.com/31609524/236229465-d22b5470-0692-42a1-a1d2-0f83c2f72699.png)

![截图 2023-05-04 21-57-08](https://user-images.githubusercontent.com/31609524/236229618-7892ff87-ea30-4b1f-8480-735c0f0ae25b.png)

**Comment by nnsgmsone** [comment]
continue work

**Comment by nnsgmsone** [comment]
now can test

**Comment by aressu1985** [comment]
fixed
