### ISSUE TITLE
[Bug]: the return value of mo_log_date function is abnormal. 

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9141]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
commit-id:352fa7db1643661ea83671af2088fda57a26418d
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -h 127.0.0.1 -P 6001 -uroot -p111
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/108530700/233893742-dd6c5cff-58d2-4a6b-8ecb-7bcd2dcf4e07.png)

### Expected Behavior

null

### Steps to Reproduce

```Markdown
select mo_log_date('数据库Database/table/2022/chuiwne/03/04/6^&(*)(');
```

**Comment by xzxiong** [comment]
as desc here https://github.com/matrixorigin/matrixone/pull/7860, it decode `%Y/%m/%d` as date val
here, it decode `03/04/6` as `2003-04-06` Date
