### ISSUE TITLE
[Bug]: mo crash when run tpcc benchmark test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9149]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):352fa7db1643661ea83671af2088fda57a26418d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

On Standlone push mode , when run tpcc test, the mo crash immediatedly.

error message:
writeBytes 0 0 MB
 connectionId 484|10.222.1.128:34418|{account sys:dump:moadmin -- 0:1:0}|fcd0cb9d-e27a-11ed-8ec4-b07b25f8b524
2023/04/24 16:35:48.092379 +0800 INFO rpc/handle.go:753 [precommit] handle write end txn: ctx[782A4AD45FEA43C0B5FFF8AA8FE1EBF0][1682325342123421026-1->9223372036854775807-4294967295][Active]: <nil>

2023/04/24 16:35:48.092409 +0800 INFO rpc/handle.go:103 HandleCommit end : 782A4AD45FEA43C0B5FFF8AA8FE1EBF0, 14.231374ms

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x197d72a]

goroutine 1484 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper.(*BfReader).MayContainsKey(0xc07c2b55c0, {0x2422e80, 0xc04f5b0a68})
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/indexwrapper/bfnode.go:72 +0x6a
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper.(*immutableIndex).Dedup(0xc05d0afc50, {0x2422e80, 0xc04f5b0a68}, 0x18f877e?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/indexwrapper/immutindex.go:49 +0x54
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/indexwrapper.(*immutableIndex).BatchDedup(0xc05d0afc50, {0x2d9c760, 0xc0b84acd00}, 0xc0045587e0?)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/indexwrapper/immutindex.go:70 +0x125
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*persistedNode).BatchDedup(...)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/pnode.go:94
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables.(*baseBlock).PersistedBatchDedup(0xc047ab2100, 0xc00a503b30, {0x7f90d8123928?, 0xc0045587e0}, 0x40?, {0x2d9c760, 0xc0b84acd00}, 0xc05cb40730, 0x0)
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/base.go:349 +0xa4
[mo-tpcc.log](https://github.com/matrixorigin/matrixone/files/11308477/mo-tpcc.log)

### Steps to Reproduce

```Markdown
1. run a mo with launch-cn-dn mode
2. git clone https://github.com/matrixorigin/mo-tpcc.git
3. modify props.mo, set warehouse to 1 and terminals to 10
4. ./runSQL.sh props.mo tableCreates
5. ./runLoader.sh props.mo warehouse 1 filelocation to data/
6. load data to mo, (can accord to sql/loadData.sql)
7. ./runBenchmark.sh props.mo
```

**Comment by LeftHandCold** [comment]
Bugs triggered by #8911

**Comment by LeftHandCold** [comment]
root cause
https://github.com/matrixorigin/matrixone/pull/8911/files#diff-df5f720cc405f3e54f67fa856d10f804d605ef16b99747db5a40b2406d8fc1d3L516

**Comment by nnsgmsone** [comment]
i will take it

**Comment by nnsgmsone** [comment]
thank you for lofi take it. @triump2020

**Comment by triump2020** [comment]
@aressu1985  Pls test.

**Comment by aressu1985** [comment]
fixed
