### ISSUE TITLE
[Bug]: test case TestDeadlockOnRemote report data race

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#9172]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/4797016567/jobs/8533471755?pr=9170

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/18366608/234280047-c3e1ea3f-bf0f-48aa-888c-884a433290d3.png">

### Expected Behavior

no error happens

**Comment by zhangxu19830126** [comment]
fixed

**Comment by zhangxu19830126** [comment]
close
