### ISSUE TITLE
[Bug]: mo was hung when rpc connection between cn and dn was closed by any exception(such as package missed)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9179]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):9ca72b63330023b3d1b9c6c8adf68d9fa5a0cd49
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In daily regression on standlone mode, the mo was hung duaring oltp hight concurrency.
After analyzing, there are some problems:
1. the morpc connection was closed by sequence error.
    
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/47846308/234468191-5f92be68-413e-4a0f-a477-2f7ac5aa1ca9.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/47846308/234468832-49bf0446-4a76-49ad-893c-7c313704eeff.png">

2. after morpc connection was closed, the cn has reconnected the morpc link, but dn can not push message.

the whole message will update in comments.

### Steps to Reproduce

```Markdown
It is very hard to repro, happened occassionally
```

**Comment by aressu1985** [comment]
log has been updated to s3:
s3://mo-ares/mo-sysbench_0426_hung.log

**Comment by aressu1985** [comment]
profile
[prof.tar.gz](https://github.com/matrixorigin/matrixone/files/11350492/prof.tar.gz)

**Comment by zhangxu19830126** [comment]
goroutine 3167422 [select, 4380 minutes]:
reflect.rselect({0xc05397e900, 0x1, 0x110000977459?})
	/usr/local/go/src/runtime/select.go:590 +0x23e
reflect.Select({0xc04515e540?, 0x1, 0x419adf?})
	/usr/local/go/src/reflect/value.go:2952 +0xd2
github.com/matrixorigin/matrixone/pkg/sql/colexec/merge.Call(0xd?, 0xc00d368900, {0x24e2e20?, 0xc0775d29e0}, 0x40?, 0xc4?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/merge/merge.go:60 +0x1cd
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0189465a0?, 0x2, 0x18?}, 0xc00d368900)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc05397eca0, 0xc00d368900)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc00513bad0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run(0xc004e6af00, 0xc00513bad0)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/compile.go:160 +0xbe
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run.func1(0xc004e6ac00?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/compile.go:244 +0x35
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/compile.go:243 +0x69

goroutine 3167462 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0x9?, 0xc0105b6900, {0x24e2a60?, 0xc005df4700}, 0x2?, 0xc?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:58 +0x205
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0292266e0?, 0x2, 0xc00ca92000?}, 0xc0105b6900)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc00264bf48, 0xc0105b6900)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc0064bfba0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x422a740?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167480 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*container).build(0xc01c5b69c0, 0x0?, 0xc00d369440, {0x2d5eb20, 0xc02baee0c0})
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:89 +0x72
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0xa?, 0xc00d369440, {0x24e2a60?, 0xc00b063030}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:51 +0x2c5
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0245f0f00?, 0x3, 0xc000680400?}, 0xc00d369440)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc03b0f4f48, 0xc00d369440)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc044d6c340, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167484 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*container).build(0xc00571f380, 0x0?, 0xc00d369d40, {0x2d5eb20, 0xc0229d83c0})
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:89 +0x72
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0xa?, 0xc00d369d40, {0x24e2a60?, 0xc00b063340}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:51 +0x2c5
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0245f1180?, 0x3, 0xc000e8a000?}, 0xc00d369d40)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc045c4bf48, 0xc00d369d40)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc044d6c8f0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167473 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0x9?, 0xc00532e240, {0x24e2a60?, 0xc005df5810}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:58 +0x205
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc029226a50?, 0x2, 0xc00a444000?}, 0xc00532e240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc0308c8f48, 0xc00532e240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc02b1668f0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x422a740?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167486 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*container).build(0xc01c5b6ae0, 0x0?, 0xc1c76d2240, {0x2d5eb20, 0xc02baee1e0})
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:89 +0x72
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0xa?, 0xc1c76d2240, {0x24e2a60?, 0xc00b063490}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:51 +0x2c5
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0245f12c0?, 0x3, 0xc000680400?}, 0xc1c76d2240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc055b42f48, 0xc1c76d2240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc044d6cb60, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x422a740?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167425 [select, 4380 minutes]:
reflect.rselect({0xc002663ba8, 0x1, 0x0?})
	/usr/local/go/src/runtime/select.go:590 +0x23e
reflect.Select({0xc04515e5c0?, 0x1, 0x20300b?})
	/usr/local/go/src/reflect/value.go:2952 +0xd2
github.com/matrixorigin/matrixone/pkg/sql/colexec/merge.Call(0xc?, 0xc00d368480, {0x24e2e20?, 0xc0775d2918}, 0x40?, 0xc4?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/merge/merge.go:60 +0x1cd
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0245f0b40?, 0x3, 0x18?}, 0xc00d368480)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc002663f48, 0xc00d368480)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc00513a4e0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 107704345 [chan receive]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/home/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:66 +0x7b
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/home/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.6/worker.go:48 +0x65

goroutine 3167467 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0x9?, 0xc0105b78c0, {0x24e2a60?, 0xc005df49a0}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:58 +0x205
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc029226870?, 0x2, 0xc00a444800?}, 0xc0105b78c0)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc045c4af48, 0xc0105b78c0)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc02b1661a0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167460 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0x9?, 0xc0105b6240, {0x24e2a60?, 0xc005df4620}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:58 +0x205
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc029226640?, 0x2, 0xc00a444000?}, 0xc0105b6240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc055b44f48, 0xc0105b6240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc0064bf860, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x422a740?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167424 [select, 4380 minutes]:
reflect.rselect({0xc0070bab60, 0x1, 0x45be72?})
	/usr/local/go/src/runtime/select.go:590 +0x23e
reflect.Select({0xc04515e580?, 0x1, 0x7f738416e100?})
	/usr/local/go/src/reflect/value.go:2952 +0xd2
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeorder.receiveBatch(0xc015b3fd70?, 0xc008664240)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/mergeorder/order.go:131 +0x45
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeorder.Call(0xc?, 0xc00d3686c0, {0x24e3060?, 0xc02cf1afa0}, 0x40?, 0xc4?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/mergeorder/order.go:76 +0x1a6
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0245f0be0?, 0x4, 0x18?}, 0xc00d3686c0)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc0070baf48, 0xc00d3686c0)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc00513b2b0, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x422a740?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167472 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0x9?, 0xc00532e000, {0x24e2a60?, 0xc005df57a0}, 0x0?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:58 +0x205
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc029226a00?, 0x2, 0xc00a444000?}, 0xc00532e000)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc00bf13f48, 0xc00532e000)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc02b166680, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x422a740?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167490 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.(*container).build(0xc01c5b6ba0, 0x0?, 0xc1c76d2d80, {0x2d5eb20, 0xc02baee300})
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:89 +0x72
github.com/matrixorigin/matrixone/pkg/sql/colexec/join.Call(0xa?, 0xc1c76d2d80, {0x24e2a60?, 0xc00b063650}, 0x1?, 0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/join/join.go:51 +0x2c5
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc0245f1540?, 0x3, 0xc000680400?}, 0xc1c76d2d80)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc045930f48, 0xc1c76d2d80)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc044d6d450, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

goroutine 3167495 [chan receive, 4380 minutes]:
github.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild.(*container).build(0xc0097d8680, 0xc00d88af60, 0xc1c76d3440, {0x2d5eb20, 0xc0198f0360?}, 0x40?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/hashbuild/build.go:96 +0xb4
github.com/matrixorigin/matrixone/pkg/sql/colexec/hashbuild.Call(0xa?, 0xc1c76d3440, {0x24e28e0?, 0xc00d88af60}, 0x80?, 0xa6?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/colexec/hashbuild/build.go:64 +0x1c6
github.com/matrixorigin/matrixone/pkg/vm.Run({0xc018946cd0?, 0x2, 0xc00a444000?}, 0xc1c76d3440)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/vm.go:61 +0x166
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun(0xc008a48f48, 0xc1c76d3440)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/pipeline/pipeline.go:150 +0x125
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun(0xc044d6da00, 0xc004e6af00)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:109 +0x649
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func2(0x0?)
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/sql/compile/scope.go:94 +0x2bf

**Comment by zhangxu19830126** [comment]
很多执行的协程卡住了, @m-schen

**Comment by dongdongyang33** [comment]
Check the stack log and find that there are no operator stuck in the cleanup step, so there are two possibilities:
1. The morpc closed info was not passed to the operator, causing the operator to wait
2. The morpc closed info was sent to the operator, but the error info transmission process between the operators was wrong

If it is case 2, I solved most of it pr https://github.com/matrixorigin/matrixone/pull/9195

I will continue to investigate according to Case 1

**Comment by dongdongyang33** [comment]
看起来像是有两个问题。

问题 1：
 @zhangxu19830126 提供的 stack 的部分是 pipeline 卡住的问题，从 stack log 中没发现有卡在 cn 需要读取数据的地方，因此判断和 cn/dn 断开连接又重连没有关系，应该和 #9107 是一个原因。
这个问题有后续 pr #9290 进一步修复了这个问题。

问题 2：
描述中有这个情况
> after morpc connection was closed, the cn has reconnected the morpc link, but dn can not push message.

这里应该是 dn 侧关于 rpc 的关闭情况处理有误。

**Comment by dongdongyang33** [comment]
waiting pr merge
