### ISSUE TITLE
[Bug]: when Connect to MatrixOne cluster,pod restarts

### ISSUE THREAD

**Issue by xuanyiLee** [matrixorigin/matrixone#9180]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when try to connect  MatrixOne cluster   
```
mysql -h 192.168.110.225 -udump -P6001 -p111
nohup kubectl port-forward --address 0.0.0.0 svc/mo-tp-cn 6001:6001 2>mo.out  &
```
the content of mo.out is as follow:
![image](https://user-images.githubusercontent.com/89380523/234484785-adb8e102-1178-4aad-a934-3fd7f19d6928.png)
the status of  MatrixOne cluster 
![image](https://user-images.githubusercontent.com/89380523/234484169-b4f09c3d-2bff-4f58-aa7f-49ff2d6f90be.png)
the log of  mo-dn-0
![image](https://user-images.githubusercontent.com/89380523/234484358-9e3fe911-c76f-4579-ab19-7f3f7b59fb97.png)

the yaml file of the MatrixOne cluster

```
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
  namespace: mo-hn
spec:
  dn:
    config: |
      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = 100
      scan-interval = "5s"
      incremental-interval = "60s"
      global-interval = "100000s"
      [log]
      level = "error"
      format = "json"
      max-size = 512
    replicas: 1
  logService:
    replicas: 3
    sharedStorage:
      s3:
        type: minio
        path: minio-mo/mo-test
        endpoint: http://192.168.110.225:9000
        secretRef:
          name: minio
    pvcRetentionPolicy: Retain
    volume:
      size: 1Gi
    config: |
      [log]
      level = "error"
      format = "json"
      max-size = 512
  tp:
    serviceType: NodePort
    config: |
      [cn.Engine]
      type = "distributed-tae"
      [log]
      level = "debug"
      format = "json"
      max-size = 512
    replicas: 1
  version: nightly-556de418
  imageRepository: matrixorigin/matrixone
  imagePullPolicy: Always
```

**Comment by aylei** [comment]
Could you provide more context @xuanyiLee ? Like CN log, etc. (you can get the cn log before last restart via `kubectl logs -p ${pod_name}`

**Comment by aylei** [comment]
Also, is the minio available? The DN log complains cannot find the specified minio bucket
