### ISSUE TITLE
[Bug]: load SSB 100G data cause mo crash

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9187]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/47846308/234744894-853ae710-9139-4a41-b79b-429a4b168947.png">

system log:
Apr 27 00:56:21 mo-srv-128 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-0.slice/session-2473.scope,task=mo-service,pid=4128249,uid=1035
Apr 27 00:56:21 mo-srv-128 kernel: Out of memory: Killed process 4128249 (mo-service) total-vm:276345388kB, anon-rss:247166404kB, file-rss:0kB, shmem-rss:0kB, UID:1035 pgtables:522740kB oom_score_adj:500

mo log:
[load-crash.tar.gz](https://github.com/matrixorigin/matrixone/files/11339026/load-crash.tar.gz)

profile:
[profile_crash.tar.gz](https://github.com/matrixorigin/matrixone/files/11339038/profile_crash.tar.gz)

### Expected Behavior

loading data can be succeed.

### Steps to Reproduce

```Markdown
1. run a mo in launch cn-dn mode
2. load ssb 100G data
```

**Comment by sukki37** [comment]
9164 has been reverted, pls kindly test.
