### ISSUE TITLE
[Bug]: Duplicate key case skipped due to temporary reasons

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9194]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Some PR needs to rely on on duplicate key refactoring. Skip this part of the case first and record the need to release this part of the case in the future

case path：dml/insert/on_duplicate_key.sql

**Comment by ouyuanning** [comment]
change tag id?

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066

**Comment by ouyuanning** [comment]
done in this branch
https://github.com/ouyuanning/matrixone/tree/refactor-iud

**Comment by ouyuanning** [comment]
done in this branch https://github.com/ouyuanning/matrixone/tree/refactor-iud
waiting for merge

**Comment by ouyuanning** [comment]
done in this branch https://github.com/ouyuanning/matrixone/tree/refactor-iud
waiting for merge

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by heni02** [comment]
case reback,confirm closed
