### ISSUE TITLE
[Bug]: foreign key case skipped due to temporary reasons 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9196]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The ci bvt test does not pass, skip it first, and locate the reason later @ouyuanning 

case path ：
cases/foreign_key/foreign_key.sql
cases/foreign_key/fk_base.sql

**Comment by ouyuanning** [comment]
change tag id?

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066

**Comment by ouyuanning** [comment]
working on #7066 
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by ouyuanning** [comment]
working on https://github.com/matrixorigin/matrixone/issues/7066
refactor new plan for insert/update/delete

**Comment by heni02** [comment]
case reback ,confirm ,closed
