### ISSUE TITLE
[Bug]: meaningless waste of cpu parsing json in motrace

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9206]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

motrace is writing data, via etl.getOneRowData, inside the function it will call ParseStringToByteJson -- seems this parsing's purpose is to validate the string is a valid json string.    All these json is actually generated by us so it is always valid and there is no point to do this parsing.

### Expected Behavior

Pass in a flag in context or somewhere else, indicate that there is no need for the validation.   Just use the string as valid json.

**Comment by zengyan1** [comment]
修复中

**Comment by fengttt** [comment]
no this is not done.   i think we crashed and reverted.

**Comment by zengyan1** [comment]
暂无进展，需要先修改json格式

**Comment by zengyan1** [comment]
等待json修改

**Comment by zengyan1** [comment]
等待json修改

**Comment by zengyan1** [comment]
等待json修改

**Comment by xzxiong** [comment]
> Is this fixed?

right now.
all JSON columns have been changed to TEXT column，except `statement_info.stats` column.

**Comment by xzxiong** [comment]
> > Is this fixed?
> 
> right now. all JSON columns have been changed to TEXT column，except `statement_info.stats` column.

fixed.
all tables in database `system` and `system_metrics` has NO Json type column.

[details part 1/2](https://github.com/matrixorigin/matrixone/pull/8825/files#diff-7b8fcb4fbf8730d6e06ce65654e526ccc6f02c5d2926fc626005235a13505ab3R62)
[details part 2/2](https://github.com/matrixorigin/matrixone/pull/9913/files#diff-7b8fcb4fbf8730d6e06ce65654e526ccc6f02c5d2926fc626005235a13505ab3R65)

**Comment by xzxiong** [comment]
@fengttt ptal
