### ISSUE TITLE
[Bug]: cn was killed by oom duaring sysbench oltp high concurrency test on eks with 2*cn and  mo hung after cn restart

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9209]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-4a5c042
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

in daily regression on eks with 2*cn , duaring running oltp test, the cn was killed by oom two times.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/47846308/235070514-934c659d-fa55-46d2-a04a-6c807eae46c3.png">

pod status:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/47846308/235070060-ccb28509-6670-4e03-8d7c-70487d1a9be9.png">

cn system log:
[Fri Apr 28 01:59:11 2023] xfs filesystem being remounted at /tmp supports timestamps until 2038 (0x7fffffff)
[Fri Apr 28 01:59:11 2023] xfs filesystem being remounted at /var/tmp supports timestamps until 2038 (0x7fffffff)
[Fri Apr 28 01:59:46 2023] bpfilter: Loaded bpfilter_umh pid 4716
[Fri Apr 28 01:59:46 2023] Started bpfilter
[Fri Apr 28 02:00:05 2023] cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation
[Fri Apr 28 02:00:09 2023] IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)
[Fri Apr 28 02:00:09 2023] IPVS: Connection hash table configured (size=4096, memory=32Kbytes)
[Fri Apr 28 02:00:09 2023] IPVS: ipvs loaded.
[Fri Apr 28 02:00:09 2023] IPVS: [rr] scheduler registered.
[Fri Apr 28 02:00:09 2023] IPVS: [wrr] scheduler registered.
[Fri Apr 28 02:00:09 2023] IPVS: [sh] scheduler registered.
[Fri Apr 28 02:00:25 2023] xfs filesystem being remounted at /var/lib/kubelet/pods/0b56c800-ec99-4b29-b6f9-f549c8cb505f/volume-subpaths/config/fluent-bit/0 supports timestamps until 2038 (0x7fffffff)
[Fri Apr 28 02:00:25 2023] xfs filesystem being remounted at /var/lib/kubelet/pods/0b56c800-ec99-4b29-b6f9-f549c8cb505f/volume-subpaths/config/fluent-bit/1 supports timestamps until 2038 (0x7fffffff)
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: [1d0f:ec20] type 00 class 0x020000
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: reg 0x10: [mem 0x00000000-0x00001fff]
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: reg 0x14: [mem 0x00000000-0x00001fff]
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: reg 0x18: [mem 0x00000000-0x000fffff pref]
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: enabling Extended Tags
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: BAR 2: assigned [mem 0xc0000000-0xc00fffff pref]
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: BAR 0: assigned [mem 0xc0100000-0xc0101fff]
[Fri Apr 28 02:00:27 2023] pci 0000:00:06.0: BAR 1: assigned [mem 0xc0102000-0xc0103fff]
[Fri Apr 28 02:00:27 2023] ena 0000:00:06.0: enabling device (0000 -> 0002)
[Fri Apr 28 02:00:27 2023] ena 0000:00:06.0: ENA device version: 0.10
[Fri Apr 28 02:00:27 2023] ena 0000:00:06.0: ENA controller version: 0.0.1 implementation version 1
[Fri Apr 28 02:00:27 2023] ena 0000:00:06.0: Elastic Network Adapter (ENA) found at mem c0100000, mac addr 02:61:9a:82:05:91
[Fri Apr 28 02:00:28 2023] ena 0000:00:06.0 eth1: Local page cache is disabled for less than 16 channels
[Fri Apr 28 02:00:28 2023] pci 0000:00:1f.0: [1d0f:8061] type 00 class 0x010802
[Fri Apr 28 02:00:28 2023] pci 0000:00:1f.0: reg 0x10: [mem 0x00000000-0x00003fff]

cn mem usage:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/47846308/235071497-84d78127-43ea-46f6-81a2-ec37fc8a82fb.png">

cn goroutine Profile：
[cn-hung.log](https://github.com/matrixorigin/matrixone/files/11350601/cn-hung.log)

### Steps to Reproduce

```Markdown
1. run a mo cluseter on eks with 2*cn
2. run oltp update hight concurrency test
```

**Comment by aressu1985** [comment]
cn mem prof updating soon

**Comment by aylei** [comment]
@aressu1985 is mem profiling updated?

> cn mem prof updating soon

**Comment by nnsgmsone** [comment]
Found that prepare did not work well and continued to track

**Comment by nnsgmsone** [comment]
continue work

**Comment by nnsgmsone** [comment]
now can fixed

**Comment by aressu1985** [comment]
fixed
