### ISSUE TITLE
[Bug]: The hash_value partition function has inconsistent calculation results across different CPU architectures

### ISSUE THREAD

**Issue by qingxinhome** [matrixorigin/matrixone#9210]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The calculation results of hash partition functions in different CPU architectures are inconsistent, resulting in unstable partition expression calculation results

At Intel Core:
![image](https://user-images.githubusercontent.com/70939751/235077915-d22eb7e7-65d6-4a89-9945-650d492911f2.png)

At Mac M1:
![image](https://user-images.githubusercontent.com/70939751/235077999-35eec6be-7873-4b98-9941-73f77b285067.png)

**Comment by nnsgmsone** [comment]
这不是个问题，你不应该假设a平台计算的hash值在b平台使用。如果你需要一个固定的hash值，请用crc32这类的函数

**Comment by aunjgr** [comment]
`hash_value` uses `BytesBatchGenHashStates` internally, which in turn uses `aesBytesBatchGenHashStates` on both amd64 and arm64 where AES intruction is presented. And the output on both platform were verified by `TestHashFn` to be identical.

So this issue seems strange. Is your M1 version compiled to arm64 arch?

**Comment by qingxinhome** [comment]
> So this issue seems strange. Is your M1 version compiled to arm64 arch?

I don't think it was caused by compilation. Let's try it out with Yuanning

**Comment by fengttt** [comment]
> arch

if it is not compiled for right arch it wont even start.   what if aes instruction is not available?

**Comment by qingxinhome** [comment]
How to Hash_ Compile the value code into the arm64 architecture? @aunjgr

**Comment by qingxinhome** [comment]
CREATE TABLE t1 (
	col1 INT NOT NULL,
	col2 DATE NOT NULL,
	col3 INT NOT NULL UNIQUE
);


insert into t1 values 
(1, '1980-12-17', 7369),
(2, '1981-02-20', 7499),
(3, '1981-02-22', 7521),
(4, '1981-04-02', 7566),
(5, '1981-09-28', 7654),
(6, '1981-05-01', 7698),
(7, '1981-06-09', 7782),
(8, '0087-07-13', 7788),
(9, '1981-11-17', 7839),
(10, '1981-09-08', 7844),
(11, '2007-07-13', 7876),
(12, '1981-12-03', 7900),
(13, '1987-07-13', 7980),
(14, '2001-11-17', 7981),
(15, '1951-11-08', 7982),
(16, '1927-10-13', 7983),
(17, '1671-12-09', 7984),
(18, '1981-11-06', 7985),
(19, '1771-12-06', 7986),
(20, '1985-10-06', 7987),
(21, '1771-10-06', 7988),
(22, '1981-10-05', 7989),
(23, '2001-12-04', 7990),
(24, '1999-08-01', 7991),
(25, '1951-11-08', 7992),
(26, '1927-10-13', 7993),
(27, '1971-12-09', 7994),
(28, '1981-12-09', 7995),
(29, '2001-11-17', 7996),
(30, '1981-12-09', 7997),
(31, '2001-11-17', 7998),
(32, '2001-11-17', 7999);

select col1, hash_value(col3) as partNum from t1 order by col1;

**Comment by aunjgr** [comment]
Both go1.20.4 and go1.19.9 can't set CPU flags properly. Don't know whether it's the bug of newest go or macos.

But I know how to workaround for this. Will submit a PR soon.

**Comment by qingxinhome** [comment]
After verification, the issue has been resolved by Long Ran . Thank you @aunjgr ，please be aware @fengttt @nnsgmsone @domingozhang @ouyuanning @daviszhen
