### ISSUE TITLE
[Performance]: Predicate transitivity and join order

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#9216]
### Is there an existing issue for performance?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Details of Performance

For some multi-table queries, we can infer new join predicates using transitive law, and then get better join order.

For example, in TPCH Q9, there are join predicates `s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey`. If we infer `s_suppkey = ps_suppkey and p_partkey = ps_partkey`, we can firstly join `part` and `partsupp`, reducing the total execution time by 30% (35s to 24s for TPCH 100G).

Another example is TPCH Q5. We should infer `c_nationkey = n_nationkey` out of `c_nationkey = s_nationkey and s_nationkey = n_nationkey`. Then we join `nation` to `customer` instead of `supplier`, and get another 30% execution time reduction (19s to 13s for TPCH 100G). However, Q5 needs further adjustment on join order algorithm, because `customer` is much bigger than `supplier`.

For 0.8, we just need to handle Q9.

**Comment by badboynt1** [comment]
fixed
