### ISSUE TITLE
[Bug]: Prepared statement should have almost zero cost for compilation, sysbench Profiling shows high query compilation cost

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9230]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sysbench profiling shows a significant amount of CPU is in compile plan.     Please check that 
1. if sysbench use prepared statement,
2. if yes, reuse the plan 
3. check primariy key predicate is correctly evaluated at run time for prepared statement.

Related, #4473.

**Comment by fengttt** [comment]
See related #9206 , also revealed by sysbench profiling.

**Comment by zengyan1** [comment]
主分支测试结果：
10w: (*Compile).Compile()占10.52%
100w: (*Compile).Compile()占29.96%
本次测试配置文件与上次不同

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by ouyuanning** [comment]
prepare所处理的内容，目前是：
1、 prepare阶段，把执行的plan记录下来
2、execute阶段。如果是二进制协议，用更高效的方式获取值。然后把这些值，和对应的plan抛给 Compile。

所以prepare+execute按照目前的实现方式，无论如何优化，都是跟Compile的性能消耗没有关系的。提升不了Compile的性能。
除非在prepare阶段，把compile的结果给存下来。但应该也只能存pipeline的一部分。
而今天从曾言跑的profile来看，ranges依然是大头，ranges是每次执行前获取元数据的，它更像是execute的一部分，而不是Compile的一部分。

**Comment by ouyuanning** [comment]
今天讨论，还需确认或处理
1、权限验证看execute的时候，现在是否还有做，确认一下要不要做。
2、execute的时候，如果存的plan中涉及到的表有变更了，现在是有bug的。要处理（比如：订阅表结构变更，变更后清理掉session中存的prepare statement。或者执行期检查表的版本）

**Comment by ouyuanning** [comment]
1的部分，跟彭振确认。目前如果是已有权限的情况。那么如果权限有被去掉，则不会被通知到。还要跟产品确认是否要变更

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
验证的部分还没时间看

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it. working on #10655

**Comment by ouyuanning** [comment]
not working on it.

**Comment by ouyuanning** [comment]
not working on it.

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
目前还差一个问题就是prepare的权限问题。
当前登录的session在prepare的时候如果有权限，但是期间管理员回收了权限，当前登录session在execute的时候目前无法感知。
@domingozhang 看是否暂时先这样

**Comment by domingozhang** [comment]
discussed with @fengttt previously, this need not be fixed

**Comment by fengttt** [comment]
According to YuanNing's study, most cost is in ranges.   Wait for ranges optimization in storage (per object) and move ranges into scanner (parallelization)
