### ISSUE TITLE
[Bug]: mo hung or stream closed duaring sysbench oltp upadte test on standlone

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9255]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c74710ac5e5360bdfe61f756b491e1e38fed3b43
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

In standlone mode, when runing oltp high concurrency test, the mo was hung, and all the new connection can not be established.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/47846308/236364437-401f8365-7525-41bb-a602-eca4eb90dcd8.png">

since mo was hung , the profiles of mem, cpu, goroutine are as follwings(interval 1 hour):

the key info is :

[profile_hung3.tar.gz](https://github.com/matrixorigin/matrixone/files/11402843/profile_hung3.tar.gz)

[profile_hung1.tar.gz](https://github.com/matrixorigin/matrixone/files/11402841/profile_hung1.tar.gz)
[profile_hung2.tar.gz](https://github.com/matrixorigin/matrixone/files/11402842/profile_hung2.tar.gz)

[profile_hung.tar.gz](https://github.com/matrixorigin/matrixone/files/11402840/profile_hung.tar.gz)

The mo log is in mo-srv-128:/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/upload/0505

### Steps to Reproduce

```Markdown
this issue is occasional, may run oltp update for a long time can reproduce it.
```

**Comment by m-schen** [comment]
hung on channel of push client. 
I don't know why,  should have a look.

Perhaps there was an issue during the consumption process of a logtail, which caused the consume-routine to exit

**Comment by m-schen** [comment]
今天没有看这个 哈哈

**Comment by m-schen** [comment]
暂无进度。待完成表达式重构后再追踪。

**Comment by aressu1985** [comment]
This problem happened again on daily regression 5.8

the profile is :
[profile_0508.tar.gz](https://github.com/matrixorigin/matrixone/files/11417136/profile_0508.tar.gz)

The mo log is in mo-srv-128:/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/upload/0508

**Comment by m-schen** [comment]
还在做表达式重构

**Comment by m-schen** [comment]
还在做表达式重构

**Comment by m-schen** [comment]
log tail消费协程的异常处理有bug，后面会解决该问题。

**Comment by aressu1985** [comment]
5.11号，Standlone MO 在Sysbench高并发执行过程中，再次出现hung住的问题，出现很多如下的错误响应：
<img width="839" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/2e60e134-dce4-4e94-b740-8e8aa0aaaef9">
<img width="889" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/46774498-e94f-428d-882c-853b1b47a568">

<img width="1035" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/18c8dace-c84e-4ade-9e0b-ab49ed5b6b72">

工具LOG：
[update_pk_10_100000.txt](https://github.com/matrixorigin/matrixone/files/11458514/update_pk_10_100000.txt)

MO  LOG:
The mo log is in mo-srv-128 on /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/upload/0512

**Comment by cnutshell** [comment]
"log tail client is not ready" is reported as a result of `logtail client initialization`.

> 5.11号，Standlone MO 在Sysbench高并发执行过程中，再次出现hung住的问题，出现很多如下的错误响应：

**Comment by nnsgmsone** [comment]
this may be fixed by #9430，继续最终是否还有其他bug

**Comment by nnsgmsone** [comment]
@aressu1985 ，#9430后这个问题还有吗

**Comment by aressu1985** [comment]
@nnsgmsone 这个问题依旧存在，现在每天都还有这个现象

**Comment by XuPeng-SH** [comment]
reassign to @cnutshell

**Comment by aressu1985** [comment]
5.17 日志中，存在RPC包丢失的情况
<img width="1316" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6c7dacbd-7cb9-4729-bbef-d9dfc0a4935c">

我先来通过测试，排除RPC丢包是否会造成HUNG的问题

**Comment by cnutshell** [comment]
5月17的日志中，`2023/05/17 09:05:59.309196` 至 `2023/05/17 09:06:00.000353` 出现 7 次 `morpc.Stream` 丢包：
<img width="1437" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/ac590439-158a-44e6-baf0-8ccfc169cd2a">

**Comment by cnutshell** [comment]
@aressu1985 在 `43.136.131.45` 复现了 `mo-service` hung 住的情况，通过分析，发现下面的日志，分析如下：
1. cn 在多个 goroutine 中发起对同一张表 `[db: 272448, tbl: 272452]` 的订阅；
2. 绿色框部分，为 dn 处理订阅请求，并返回订阅响应的日志，时间为 `2023/05/17 14:48:37.240856`；
3. 10s 后，`2023/05/17 14:48:47.155593`，cn 多个 goroutine 中输出未收到订阅响应的日志

考虑 `morpc.Stream` 原因，待进一步确认

<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/69632000-bdb0-44be-880a-23c08e90753f">

**Comment by cnutshell** [comment]
分析了跟 [db: 272448, tbl: 272452] 有关的日志，mo-service hung 住的原因是：
cn 重连后没有重新发起订阅请求。

大致的过程是这样的：morpc 丢包 -> morpc stream 关闭 -> cn 重连 -> 重连后 cn 未发出订阅请求

详细过程见文件：
[Issue 9255.pdf](https://github.com/matrixorigin/matrixone/files/11496912/20230517-Issue.9255.pdf)

**Comment by cnutshell** [comment]
mo-service 整个 hung 住的原因是因为 cn 重连后，tcp 连接再次断开，morpc 返回的错误未得到正确处理，分析如下：

首先，cn 重连过程是这样的：
1. cn 收到 morpc 报错，进入重连阶段；
2. 重连后，cn 订阅 3 张特殊的表，并等到这 3 张表的订阅响应；
3. cn 回归正常处理逻辑

cn 在重连收到 3 张表的订阅响应后，回归正常处理逻辑前，此时 morpc stream 对应的 tcp 连接再次断开，morpc stream 会向 cn 持有的 channel 发一个 nil 来通知 cn tcp 连接再次断开的情况。

在回归正常逻辑之前，cn 未处理这个用 nil 表示的报错，一直等待响应，但 morpc stream 已无法送回响应。
后续 mysql 连接，创建 txn 时，也因为响应一直没过来，时间戳未得到更新而 hung 住。

> 分析了跟 [db: 272448, tbl: 272452] 有关的日志，mo-service hung 住的原因是： cn 重连后没有重新发起订阅请求。
> 
> 大致的过程是这样的：morpc 丢包 -> morpc stream 关闭 -> cn 重连 -> 重连后 cn 未发出订阅请求
> 
> 详细过程见文件： [Issue 9255.pdf](https://github.com/matrixorigin/matrixone/files/11496912/20230517-Issue.9255.pdf)

**Comment by aressu1985** [comment]
has been tested ,and has been fixed . but I also need to trace this for more days.

**Comment by aressu1985** [comment]
closed
