### ISSUE TITLE
[Bug]: ut TestCollector fail in CI

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#9259]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/39627130/236371977-32c31c63-d431-4206-bfa5-def418663e8d.png">

https://github.com/matrixorigin/matrixone/actions/runs/4889598437/jobs/8728252508?pr=9253

**Comment by xzxiong** [comment]
the case is time-sensitive, runs not well in unstable env.

let me find another way to verify this feature.

**Comment by xzxiong** [comment]
how to fix: 通过检查cpu个数，限制UT的执行：当cpu>=4时，再执行该UT。

**Comment by YANGGMM** [comment]
test fail repo
link:https://github.com/matrixorigin/matrixone/actions/runs/6939960303/job/18878945929?pr=12855

**Comment by xzxiong** [comment]
原因分析
1. ut TestCollector 依然是一个时间敏感的
2. pr https://github.com/matrixorigin/matrixone/pull/12819 合并后, ut TestCollector 仅使用1 个goroutine worker，因调度不及时，影响运行结果

fix：
当 cpu >= 4 时，启动多个 goroutine worker 给ut TestCollector 使用

**Comment by xzxiong** [comment]
fixed. Ptal @YANGGMM

**Comment by YANGGMM** [comment]
plz closed it @XuPeng-SH
