### ISSUE TITLE
[Bug]: The metadata is slow

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#9260]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

zengyan know every thing about the bug

### Steps to Reproduce

use https://github.com/nnsgmsone/matrixone/tree/prepare

run ./start.sh -c cases/sysbench/point_select_10_100000_prepare/

**Comment by nnsgmsone** [comment]
pprof file.
[pprof.mo-service.samples.cpu.001.pb.gz](https://github.com/matrixorigin/matrixone/files/11403230/pprof.mo-service.samples.cpu.001.pb.gz)

**Comment by nnsgmsone** [comment]
对于sysbench 10w的数据量，prepare的情况下，一个表只有10个block，block的元数据应该都在内存，这个应该开销很低。5%可能最多了。

**Comment by zengyan1** [comment]
目前主分支测试结果：
10w：(*txntable).Ranges占6.05%
100w: (*txntable).Ranges占26.81%
此次测试配置文件与上次不同

**Comment by zengyan1** [comment]
暂无进展，最新主分支待测试

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展

**Comment by zengyan1** [comment]
暂无进展
