### ISSUE TITLE
[Bug]: UT TestLockWithBindIsStable fail

### ISSUE THREAD

**Issue by YANGGMM** [matrixorigin/matrixone#9265]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="341" alt="image" src="https://user-images.githubusercontent.com/26563383/236401051-29607d19-e5fa-4ccb-9dd9-7cffb32c1fee.png">

https://pipelines.actions.githubusercontent.com/serviceHosts/420d9c18-f10d-4e16-b77b-a3050f679cb1/_apis/pipelines/1/runs/120553/signedlogcontent/4?urlExpires=2023-05-05T07%3A34%3A21.3046896Z&urlSigningMethod=HMACV1&urlSignature=BU4mO23Iu8t0SVjaiP35rr7EAqLfnUezDvJ2VRd3HEc%3D

https://pipelines.actions.githubusercontent.com/serviceHosts/420d9c18-f10d-4e16-b77b-a3050f679cb1/_apis/pipelines/1/runs/120559/signedlogcontent/8?urlExpires=2023-05-05T07%3A34%3A15.9670813Z&urlSigningMethod=HMACV1&urlSignature=G%2FRJHa0SSuyF8xt22RYojKIz8Z0qQ9GyJzxU2QPdXlE%3D

**Comment by cnutshell** [comment]
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/7a28f077-0e0e-4cbb-9667-34c3684c0422">

https://github.com/matrixorigin/matrixone/actions/runs/4942689060/jobs/8836453139?pr=9384

**Comment by zhangxu19830126** [comment]
fixed
