### ISSUE TITLE
[Bug]: the perf dicreased from commit 5d7b108, proportion is more than 40%

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9270]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):a20543ba
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

data size: 34G

on commit id: 5d7b108af47b5888f0ffec1eae98f6570148bfa7
the cost is about 47.8s
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/47846308/236438902-740ffedb-d549-49c1-b85e-54ddddad5e0b.png">

on commit id: a20543bac15076802c6521461681a74422d6ec36
the cost is about 71.5s
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/47846308/236439280-9880c352-b34c-4a15-acda-828a5b270397.png">

the cpu profile of two commit during loading data are as following:
[normal.zip](https://github.com/matrixorigin/matrixone/files/11405513/normal.zip)
[decrease.zip](https://github.com/matrixorigin/matrixone/files/11405517/decrease.zip)

### Expected Behavior

The cost of loading same data should be almost equal.

### Steps to Reproduce

```Markdown
just loading data on standlone mode
```

**Comment by aronchanisme** [comment]
as per discussed, pls help take a look @jianwan0214

**Comment by aressu1985** [comment]
fixed
