### ISSUE TITLE
[Bug]: After updating cn groups information, show backend server labels not updated

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9275]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-c74710ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

show backend servers; labels which include acc2... is the configuration before the update
<img width="1439" alt="企业微信截图_38120346-e044-4cba-85bc-8b107b309462" src="https://user-images.githubusercontent.com/113406637/236596508-58462a8b-b329-4a95-88b9-052de8e1979f.png">
cn groups config:
<img width="418" alt="企业微信截图_48278199-1edb-4995-bd68-675b4aeecd0e" src="https://user-images.githubusercontent.com/113406637/236596513-77996f87-9d2b-4fa7-a82e-87ad8c2c7041.png">

and  label information here is null
![image](https://user-images.githubusercontent.com/113406637/236596608-ce4cf560-8507-4313-8a30-491df05de714.png)

### Steps to Reproduce

1.Create a new cluster and configure cn groups
2.alter cn groups key values information
3.show backend servers;

**Comment by volgariver6** [comment]
fixed by #9281.

**Comment by heni02** [comment]
regression tomorrow

**Comment by heni02** [comment]
comfirm，closed
image：nightly-365ecb68
![image](https://user-images.githubusercontent.com/113406637/236728599-5a243f96-bec4-451b-b617-030fed3158c2.png)
