### ISSUE TITLE
[Bug]: test case TestDiskCacheWriteAgain failed on ci

### ISSUE THREAD

**Issue by jiangxinmeng1** [matrixorigin/matrixone#9277]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/4899560883/jobs/8749722048?pr=9276
![image](https://user-images.githubusercontent.com/51114574/236599273-7d4467ee-ccf0-499e-a64d-96f1424ebad3.png)

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/7297057298/job/19885771884?pr=13727
@reusee  麻烦看一下
