### ISSUE TITLE
[Enhancement]: optimize fileservice disk cache eviction

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#9292]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

```Markdown
Optimize fileservice cache eviction so that the storage used by cache can be limited in the configured disk cache capacity.
```

### Why is this needed ?

As discussed in https://github.com/matrixorigin/matrixone/issues/9020, current the disk cache is evicted on a regular base (by default, once per 7 minutes). The disk cache size would grow infinitely between two eviction checks. We might need a storage size based eviction strategy to avoid cache size exceeding the configured capacity.

**Comment by reusee** [comment]
disk cache will be unified with the memory cache. tracking in https://github.com/matrixorigin/matrixone/issues/10450

**Comment by fengttt** [comment]
@reusee #10450 is closed, so what happens to this one?

**Comment by reusee** [comment]
We still need a memory structure to hold entry information.
Or read info from the memory cache if it exists.
I'll continue to do this.

**Comment by reusee** [comment]
Maybe a directory-based FIFO is OK for the eviction. Will investigate this approach.

**Comment by reusee** [comment]
done in https://github.com/matrixorigin/matrixone/pull/14019

**Comment by aressu1985** [comment]
test done
