### ISSUE TITLE
[Bug]: connect to proxy, sys login failed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9299]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-c74710ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="940" alt="企业微信截图_41b1dbda-0568-4bbe-b955-54ccd9c11b0b" src="https://user-images.githubusercontent.com/113406637/236656551-6ecfdb42-4775-4a4e-9f2c-7809d347c9dd.png">
<img width="875" alt="企业微信截图_f0787caa-27c8-4552-b92d-ce0827a3ef3e" src="https://user-images.githubusercontent.com/113406637/236656557-3736b2bf-408a-44f2-8768-82192e03809c.png">

**Comment by volgariver6** [comment]
fixed.

**Comment by heni02** [comment]
regression tomorrow

**Comment by heni02** [comment]
confirm,closed
image: nightly-365ecb68
![image](https://user-images.githubusercontent.com/113406637/236727879-fbbd0514-78b9-4f69-adcf-a3dcdec92c59.png)
