### ISSUE TITLE
Query failed when select list contain duplicate column names

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#930]
#### Can be reproduced ?
Yes

#### Steps:
select userID as spID, spID from t1;

#### Expected behavior:
mysql> select userID as spID, spID from t1;
+------+------+
| spID | spID |
+------+------+
|    1 |    1 |
|    2 |    2 |
|    1 |    2 |
|    3 |    3 |
|    1 |    1 |
|    6 |    4 |
|   11 |    5 |
+------+------+
7 rows in set (0.00 sec)

#### Actual behavior:
mysql> select userID as spID, spID from t1;
ERROR 1105 (HY000): unknown error:[42P09]alias 'spID' is ambiguous

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 281e2ce44655fe4085bc36f9a7a9eed4ba83655
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by m-schen** [comment]
will be solved after plan refactoring.

**Comment by daviszhen** [comment]
it was fixed
