### ISSUE TITLE
[Bug]: MultiCn Docker Delete is too slow

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#9304]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

delete.test:
Line:178 delete from t where a = 1;
over 60s

### Expected Behavior

delete.test:
Line:178 delete from t where a = 1;
less 60s

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
no progress

**Comment by LeftHandCold** [comment]
same as https://github.com/matrixorigin/matrixone/issues/9447

**Comment by sukki37** [comment]
This issue has been inactive for a while. To help keep our backlog clear, I'm going to close this. If you feel this is still relevant, please comment or reopen. Thanks!
