### ISSUE TITLE
[Subtask]: try to optimize `disttae.getBlockInfos`

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#9310]
### Parent Issue

Parent issue #9309

### Detail of Subtask

Try to replace `blocks` with `objects`.

**Comment by cnutshell** [comment]
logtail protocol need to be updated

**Comment by cnutshell** [comment]
There is an issue #9487  emerged during development.

**Comment by XuPeng-SH** [comment]
@aressu1985 please help to close this issue
