### ISSUE TITLE
[Bug]:Login cn group account ， show backend servers view empty group resources

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9321]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-365ecb68
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

account b1 is grouped in ap1, and ap2 is an empty label. Now login b1, and the resources of the empty group can also be displayed
<img width="1174" alt="企业微信截图_9dbb0e8c-6308-48e0-8b58-7b45068cf769" src="https://user-images.githubusercontent.com/113406637/236768346-b9418a3e-e15c-4991-a0aa-ad9a814afb9a.png">

all cn labels show
![image](https://user-images.githubusercontent.com/113406637/236766758-671a45f4-f267-4eb9-b142-ace1218f3798.png)

### Steps to Reproduce

```Markdown
1.config  mo.yaml 2cngroups:
cnLabels:
    - key: "account"
      values: ["b1","sys"]
cnLabels: []

2.apply mo.yaml after b1 login mo
mysql -h 127.0.0.1 -P6501 -ub1:admin -p111

3.show backend servers
```

**Comment by volgariver6** [comment]
fixed by #9465

**Comment by heni02** [comment]
set two cn groups , one tp and other empty. now, the dump user only sees one tp group, no empty groups,  dump or root should be able to see all the groups
image：nightly-6a65b65
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b4597578-0ad6-4a87-8503-5cf63bc8e9d9)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b1e3567b-be40-4500-8988-10224f97b584)

**Comment by volgariver6** [comment]
fixed by #9720

**Comment by heni02** [comment]
There is a problem with the CN startup #9610 , after resolve this issue confirm the problem 
![image](https://github.com/matrixorigin/matrixone/assets/113406637/12b0e323-28cf-4201-9911-06ab1bd4a932)

**Comment by heni02** [comment]
confirm,closed
commit id:1f7f26148d7d03827e208589c132db46379dae01
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d2ce3460-6cef-437b-a180-728aec5e652b)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/8fc15631-094e-480a-bb1e-bec11709521a)
