### ISSUE TITLE
[Bug]:root and dump users under the sys account do not resource isolation

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9323]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-365ecb68
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
we expect  when sys account in the cn group, root and dump users need resource isolation. otherwise， both users can connect anyone cn
<img width="1266" alt="企业微信截图_00a5b9a0-4efc-4aad-92a4-52d973fc1563" src="https://user-images.githubusercontent.com/113406637/236783820-f45f55f7-1eaa-4f3f-b5b4-ea590cf152dd.png">
<img width="1196" alt="企业微信截图_39500b96-a57d-4782-8fe9-ca6e480f2516" src="https://user-images.githubusercontent.com/113406637/236783845-6750dd18-2d5c-4d38-8833-cceab23dc324.png">

**Comment by volgariver6** [comment]
fixed by #9465

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm
1.
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0a2f47f4-2016-4585-aee2-4439d95e0e65)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ff37af3f-e9dc-44a9-9be2-b7561233be66)

2.
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7e2c75d3-ae26-4b22-a90c-e62bba03cc96)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f828c01a-388c-4f27-9bc3-0c453aabb90a)

3.
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0971b606-de30-4f8b-82ad-cc71022954d6)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/57d8533a-abb7-4a4b-8761-973a4a01f5fd)
