### ISSUE TITLE
[Bug]: after connection in killed, the connection is hung in mult-cn env.

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#9325]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 248d197b100f6919158768bf5f75f75ff616dab0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="429" alt="image" src="https://user-images.githubusercontent.com/18366608/236794078-e93ff8a4-5bfb-4480-a545-29cbd58fd27b.png">

### Expected Behavior

the connection could reconnect.

**Comment by daviszhen** [comment]
初步定位到原因了。还要进一步确认。

**Comment by daviszhen** [comment]
1，multi-cn连接。client连到6001后形成conn1。会在proxy.go 与 cn (port 16001)之间再建一条conn2。
conn1 与 conn2之间 用Copy 传数据。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/45ea8ce0-1ce7-495d-8a5e-170e645e75c5)

2，client 发送kill connection xxx时，cn 收到kill 语句，杀掉了conn2。
但是上述Copy函数在conn2被Close后，没有报错返回。conn1没有断开。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/ae968883-fb58-4799-a735-6651d38e20f1)


![1841683895601_ pic_hd](https://github.com/matrixorigin/matrixone/assets/60595215/1b1e859e-837d-4e72-b9e4-7d86df4a70da)

conn1没有断开。6001没有发送FIN包给client。
并且client 把select 1 发送给6001成功。因为6001 ACK了。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/eb36c08f-14ae-4b3d-a78f-ad6764654612)

这是抓的包。
[9325.pcapng.zip](https://github.com/matrixorigin/matrixone/files/11464142/9325.pcapng.zip)

**Comment by daviszhen** [comment]
经过讨论，要删除proxy.go。测试proxy再验证下。

**Comment by volgariver6** [comment]
该问题可以关闭，因为gotty中的proxy是临时测试使用的。
