### ISSUE TITLE
[Bug]: when cn label is empty，statement_info unable find account user information

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9326]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-365ecb68
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When cn groups label is empty, any account who is not in the group login mo, execute SQL, and statement_info not found the account user information 
![image](https://user-images.githubusercontent.com/113406637/236806911-8f01cb93-dfd3-4149-971b-90d55ba29a5d.png)
![image](https://user-images.githubusercontent.com/113406637/236806237-5368a214-c579-4a0f-a18d-bd4c741a2377.png)

### Steps to Reproduce

```Markdown
1. mo cn groups config:
cnLabels: []

2.mysql -h 127.0.0.1 -P6501 -uc2:admin -p111 
create table hhh(c1 int); 
3.select node_uuid,statement,user from system.statement_info where account='c2' ;
```

**Comment by volgariver6** [comment]
再操做一遍，无法复现该问题。

**Comment by gouhongshen** [comment]
according to the above statements and steps, tried：

1. single tenant did random queries
2. multiple tenants  did random queries

but can not repo.

**Comment by gouhongshen** [comment]
### 1. Reason: 
this is not a proxy problem. when an internal query with the prefix `__++__internal_cmd_field_list` has been executed, these codes will be invoked:
```golang
if tenant == nil || strings.HasPrefix(sql, cmdFieldListSql) {
    if tenant != nil {
        tenant.SetUser("")
    }
    ses.sqlSourceType = append(ses.sqlSourceType, intereSql)
    return
}
```
and the `tenant.user` will be cached and valid in sequence queries until re-establish SQL connection.

### 2. Steps to Repo:
```sql
0. open a terminal
1. mysql -h127.0.0.1 -udump -P6001 -p111
2. create account acc1 admin_name 'root' identified by '111';
3. open a new terminal
4. mysql -h127.0.0.1 -uacc1:root -P6009 -p111
5. launch some queries
6. select node_uuid,statement,account,user from system.statement_info where account='acc1' ;
//this will occur panic err, but it doesn't matter.
7. __++__internal_cmd_field_list 
8. launch some queries
9. select node_uuid,statement,account,user from system.statement_info where account='acc1' ;

then you will see that some statement records  have lost the user info
```

**Comment by gouhongshen** [comment]
put on hold, give priority to #10089

**Comment by gouhongshen** [comment]
> ### 1. Reason:
> this is not a proxy problem. when an internal query with the prefix `__++__internal_cmd_field_list` has been executed, these codes will be invoked (in `pkg/frotend/session.go::getSqlType`):
> 
> ```go
> if tenant == nil || strings.HasPrefix(sql, cmdFieldListSql) {
>     if tenant != nil {
>         tenant.SetUser("")
>     }
>     ses.sqlSourceType = append(ses.sqlSourceType, intereSql)
>     return
> }
> ```
> 
> and the `tenant.user` , which has been set to "", will be cached and valid in subsequent queries until re-establish SQL connection.
> 
> ### 2. Steps to Repo:
> ```sql
> 0. open a terminal
> 1. mysql -h127.0.0.1 -udump -P6001 -p111;
> 2. create account acc1 admin_name 'root' identified by '111';
> 3. open a new terminal
> 4. mysql -h127.0.0.1 -uacc1:root -P6009 -p111;
> 5. launch some queries
> 6. select node_uuid,statement,account,user from system.statement_info where account='acc1' ;
> 
> 7. __++__internal_cmd_field_list ; -- this will occur panic err, but it doesn't matter.
> 8. launch some queries
> 9. select node_uuid,statement,account,user from system.statement_info where account='acc1' ;
> 
> then you will see that some statement records  have lost the user info
> ```
> 
> but I have no idea about why and when this internal query will be executed yet.

发起 `cmdFieldList` query 是因为使用 `TAB` 键补全表名

**Comment by heni02** [comment]
@xzxiong confirmed ,it is same issue as #10542 ,so closed

**Comment by xzxiong** [comment]
> @xzxiong confirmed ,it is same issue as #10542 ,so closed

confirmed
