### ISSUE TITLE
[Bug]: CN Connection Lost while performing large amount of Insert and running BVT

### ISSUE THREAD

**Issue by gavinyue** [matrixorigin/matrixone#9330]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
4d826e8
- Hardware parameters:
- OS type:
Ubuntu
- Others:
```

### Actual Behavior

Running BVT while performing a large amount of Insert. 
Running MO service locally:  ./mo-service -launch ./etc/launch-tae-multi-CN-tae-DN/launch.toml >> ./tmp/log1

1. Running TPCC 
./runLoader.sh props.mo warehouse 1
and 
2. Running BVT
./run.sh -n -g -p ./matrixone/test/distributed/cases

The connection will start to get lost. 

Worker 000: ERROR: Communications link failure

The last packet successfully received from the server was 30,056 milliseconds ago.  The last packet sent successfully to the server was 30,044 milliseconds ago.

**Comment by xzxiong** [comment]
@nnsgmsone  pls update what you found.

**Comment by gavinyue** [comment]
写了个测试用于复现问题， 有两个问题

1. connection的并发度多了之后， CN会断开链接且无法响应。 
2. 写入并发高了之后每个并发写入的速度会变慢， 单链接情况下， 写入20M数据需要2.5s， 但是如果10个goroutines一起写，每个完成的时间会变长到10s+
3. 如果一边在insert into rawlog,  一边select from rawlog limit 10.  这样原来只需要100ms的select, 会变慢到几秒， 甚至更长。


最后一个问题是目前导致bvt compose不过的问题之一，  在bvt compose下，  cn0/cn1/dn/logservice 会各自产生一个db connection进行写入， 而在bvt测试用例里又会有同时selectom from statement_info的情况， 会导致查询的时间变长， 进而超时。 

另外就是四个如果写入的数据量太大，  同时写入，  四个并发一起， 基本上对应的cn就失去了响应。 
[main.zip](https://github.com/matrixorigin/matrixone/files/11482021/main.zip)

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
这两天和老哥一起看一下这个问题

**Comment by fengttt** [comment]
Blocking merge regression run and daily run.   Upgrade to S-1.

**Comment by nnsgmsone** [comment]
目前遇到表达式内存复用会导致无法重启的问题，还在查

**Comment by nnsgmsone** [comment]
继续处理，优化prepare

**Comment by nnsgmsone** [comment]
性能还有一些问题，还在处理

**Comment by nnsgmsone** [comment]
基本处理完毕，等daily run跑几次，如果没有问题，就提交pr

**Comment by nnsgmsone** [comment]
pr is merged. now may be it is ok.
