### ISSUE TITLE
[Bug]: one cn crash, the proxy cannot route to other cn in the same group

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9333]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-365ecb68
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are 2 replicas in the resource group of c1. While running the case, delete 1 CN. After all the cases are completed, it appears that only one CN is executing SQL, and the proxy cannot disconnect from another CN after the other CN is disconnected
<img width="1383" alt="企业微信截图_6a3d7e36-7a85-47ac-833e-bfc3d7b08575" src="https://user-images.githubusercontent.com/113406637/237008421-5b2cd3dc-ca86-49b2-8b42-49cb8e1ee2b2.png">

### Steps to Reproduce

```Markdown
1.cn groups config 
    replicas: 2
    cnLabels:
    - key: "account"
      values: ["c1","a1"]
2.run some cases
3.delete cn group pod
4.mysql -h 127.0.0.1 -P6501 -uc1:admin -p111
select count(node_uuid) from system.statement_info where account='c1' and node_uuid in("35346432-6533-3439-3739-363238613266");
select node_uuid,statement from system.statement_info where account='c1' and node_uuid in("33396635-3038-6563-3031-303763313466");
```

**Comment by heni02** [comment]
@domingozhang plz confirm if it is done at 0.8

**Comment by volgariver6** [comment]
may not be fixed in 0.8. It will be handled with cn group capacity reduction in next phase.

**Comment by volgariver6** [comment]
等CN缩容功能做完之后，再验证一下该问题。

**Comment by volgariver6** [comment]
已经修复，请使用新版本的MO和operator测试。

**Comment by heni02** [comment]
回归该问题，并发insert 50跑20分钟，删掉一个pod后，两个uuid的连接从各25到一个uuid50个，分析后发现这种情况是正常的，因为工具并发只有断开连接才能新建连接，拉起pod需要时间新建的连接会在唯一一个uuid上重新建立，所以这种场景无法验证删掉pod后立刻两个uuid实现各25个这种情况，只能验证拉起pod后链接迁移是否成功，以下是20分钟后，迁移结果，两个uuid链接数分别为11和40，符合预期
<img width="1228" alt="企业微信截图_bc1ef396-6c3b-4dda-a7b1-a11e1572214b" src="https://github.com/matrixorigin/matrixone/assets/113406637/86afc1d3-4726-4463-9242-c8a2369ca577">
