### ISSUE TITLE
[Bug]: [HA]oltp test was hung when dn restart on distribute mod  

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9343]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-210206b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Duaring oltp point select test, if kill dn pod , the test will hung even if the dn pod has restarted.

<img width="878" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/33361806-051d-4f1b-a511-e0df9baa6b86">

profile:
[cn0.hung.txt](https://github.com/matrixorigin/matrixone/files/11430179/cn0.hung.txt)
[cn1.hung.txt](https://github.com/matrixorigin/matrixone/files/11430180/cn1.hung.txt)

### Expected Behavior

When dn was restarted , the following queries can be normally.

### Steps to Reproduce

```Markdown
1.run a mo-cluster on eks with 2*CN
2.run sysbench point select test
3.kill dn pod
```

**Comment by badboynt1** [comment]
goroutine 4192340 [select]:
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).TryToSubscribeTable(0xc0028e07c8, {0x2dd68b8, 0xc005894cc0}, 0x428d3, 0x428d9)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:156 +0x2e5
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).UpdateOfPush(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/db.go:320
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).updateLogtail(0xc1284bfc00, {0x2dd68b8, 0xc005894cc0})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:1326 +0x212
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).updateBlockInfos(0xc1284bfc00, {0x2dd68b8, 0xc005894cc0}, 0xc1e6fa7a00?)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:1272 +0x12d
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Stats(0xc1284bfc00, {0x2dd68b8, 0xc005894cc0}, 0xc0644f487e?, {0x2589280?, 0xc1e6fa7a00})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:55 +0x185
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Stats(0x0?, 0xc06d26dae0, 0x0)
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/compiler_context.go:672 +0x1c4
github.com/matrixorigin/matrixone/pkg/sql/plan.ReCalcNodeStats(0x2797480?, 0xc065e25b40, 0x20?, 0x9c?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/stats.go:590 +0x455
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).appendNode(0xc065e25b40, 0xc059149c20?, 0xc00caeb680)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/plan/query_builder.go:1775 +0x167

从profile里看，应该是hang在这里了。看样子是TryToSubscribeTable函数需要处理这个错误？

**Comment by m-schen** [comment]
与mo cloud 700相似。待确定是否是卡住时没能从cluster info中及时拿到重启后的dn接口等。

**Comment by m-schen** [comment]
plan to work it tomorrow.

**Comment by m-schen** [comment]
明天可以开始跟踪该issue。

**Comment by m-schen** [comment]
没进展

**Comment by m-schen** [comment]
没进展

**Comment by m-schen** [comment]
今天在搞表达式pr

**Comment by m-schen** [comment]
有相关pr 不确定需不需要回复 所以回复一下

**Comment by m-schen** [comment]
明日可验证。

**Comment by m-schen** [comment]
还在验证，环境没搞好。

**Comment by aressu1985** [comment]
this issue has been fixed. But also has another problem tracked by #9654
