### ISSUE TITLE
[Bug]: cost of replay is more than 2 minutes for 261G data

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9347]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):65bdd570cb0580e82ef997e72c411ae7a1cd1b6c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

the size of mo-data is 261G , and restarting mo need more than 2 minuts

<img width="1403" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3ceeca01-b206-4c18-acd8-1b0b044d93d1">

[server.log](https://github.com/matrixorigin/matrixone/files/11431059/server.log)

**Comment by jiangxinmeng1** [comment]
#9482 apply and read TXN commands parallelly. I'll apply TXN commands with multiple workers.
