### ISSUE TITLE
[Bug]: mo print invalid input: invalid json type '123' log crazily and cause mo crash duaring oltp prepared insert high concurrency test on standlone

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9364]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):3e22243af7a4add4c219479d48616d6f72302df2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Duaring sysbench high concurrency test on standlone , the mo suddenly print the following error log Intermittently, and at last the mo stoped.

2023/05/10 13:12:49.799730 +0800 ERROR bytejson/bytejson.go:167 error: invalid input: invalid json type '123'
github.com/matrixorigin/matrixone/pkg/container/bytejson.ByteJson.to
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/bytejson/bytejson.go:167
github.com/matrixorigin/matrixone/pkg/container/bytejson.ByteJson.MarshalJSON
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/bytejson/bytejson.go:76
github.com/matrixorigin/matrixone/pkg/container/bytejson.ByteJson.String
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/bytejson/bytejson.go:30
github.com/matrixorigin/matrixone/pkg/util/export/etl.ValToString
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/etl/tae.go:417
github.com/matrixorigin/matrixone/pkg/util/export/etl.(*TAEReader).ReadLine
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/etl/tae.go:349
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).doMergeFiles
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/merge.go:352
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).Main
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/merge.go:255
github.com/matrixorigin/matrixone/pkg/util/export.MergeTaskExecutorFactory.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/merge.go:755
github.com/matrixorigin/matrixone/pkg/taskservice.(*taskRunner).run.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/taskservice/task_runner.go:399
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/stopper/stopper.go:259
2023/05/10 13:12:49.799798 +0800 ERROR bytejson/bytejson.go:167 error: invalid input: invalid json type '123'
github.com/matrixorigin/matrixone/pkg/container/bytejson.ByteJson.to
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/bytejson/bytejson.go:167
github.com/matrixorigin/matrixone/pkg/container/bytejson.ByteJson.MarshalJSON
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/bytejson/bytejson.go:76
github.com/matrixorigin/matrixone/pkg/container/bytejson.ByteJson.String
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/bytejson/bytejson.go:30
github.com/matrixorigin/matrixone/pkg/util/export/etl.ValToString
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/etl/tae.go:417
github.com/matrixorigin/matrixone/pkg/util/export/etl.(*TAEReader).ReadLine
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/etl/tae.go:349
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).doMergeFiles
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/merge.go:352
github.com/matrixorigin/matrixone/pkg/util/export.(*Merge).Main
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/merge.go:255
github.com/matrixorigin/matrixone/pkg/util/export.MergeTaskExecutorFactory.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/util/export/merge.go:755

the last 500000 rows in error log:
[error_json.tar.gz](https://github.com/matrixorigin/matrixone/files/11438474/error_json.tar.gz)

### Expected Behavior

The mo should be run stabily

### Steps to Reproduce

```Markdown
1、Maybe run oltp prepared insert high concurrency(1000 threads) test on standlone mode can repro this
```

**Comment by zengyan1** [comment]
该bug已被 #9341 修复

**Comment by aressu1985** [comment]
testing
