### ISSUE TITLE
[Bug]: [HA]mo hung when one of cn pod is abnormal in distributed mode(2*cn)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9368]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):210206b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The topo of mo is : 2*cn 1*log 3*log

when one of cn is abnormal, eg, always in creating state, or has been in some exceptional state, the following connections to mo can not be established.

such as the cn1 can not provide service for the following error:
<img width="1413" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/61918bbd-8565-4982-a643-a43551cc99d5">

the connection can not be established:
<img width="904" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/fedbb6aa-05d6-4247-8031-96f75fdde65e">

the reasion is that query user info was hung.
{"level":"DEBUG","time":"2023/05/10 07:01:31.037837 +0000","caller":"frontend/session.go:1488","msg":"background exec sql:select user_id,authentication_string,default_role from mo_catalog.mo_user where user_name = \"dump\";"}

the whole log is 
[cn0.tar.gz](https://github.com/matrixorigin/matrixone/files/11439009/cn0.tar.gz)

### Expected Behavior

Only one cn abnoral should not affect anything for the following request.

### Steps to Reproduce

```Markdown
1. run a distributed mo cluster with 2*cn 
2. kill one cn pod 
3. connect to mo cluster
```

**Comment by daviszhen** [comment]
登录卡住的原因是。CN发送mo_user的logtail 请求给DN。
但是一直没有收到DN的logtail.
![image](https://github.com/matrixorigin/matrixone/assets/60595215/c4630ca9-5367-433e-8a6a-9725cd01a749)

**Comment by cnutshell** [comment]
需要通过 dn 侧日志，确认是否有收到 cn 发来的订阅请求。
目前已知情况 dn 重启后，cn 需要重启才能正常提供服务

**Comment by aressu1985** [comment]
这个dn里面没有日志，是CN在等logtail，结果一直等不到，就不会把请求发过去，所以就没有放CN的日志

**Comment by cnutshell** [comment]
昨天同 @aressu1985 分析了 dn debug 级别日志，dn 通过 morpc stream 向 cn 持续送出 logtail 更新：
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/1da05723-dde3-4abf-8c92-714e36f0e6e8">

**Comment by cnutshell** [comment]
需要通过 cn 侧日志排查为何没有收到 dn 发出的增量 logtail

> 昨天同 @aressu1985 分析了 dn debug 级别日志，dn 通过 morpc stream 向 cn 持续送出 logtail 更新： <img alt="image" width="1439" src="https://user-images.githubusercontent.com/20291742/237552385-1da05723-dde3-4abf-8c92-714e36f0e6e8.png">

**Comment by xzxiong** [comment]
@m-schen 麻烦继续看看 CN 没收到 logtail的问题
目前发现）
1.   issue 9368, CN 在等待 mo_user 这张表的 logtail；  issue 9378，CN 则是在等 sbtest8 这张表的logtail
2.  issue 9368 从 DN的日志上看，DN 已经将 logtail 通过广播发送出去了，但是 CN 一直没有收到，或者是没等到最新版本的 logtail

**Comment by m-schen** [comment]
work it tomorrow.

**Comment by m-schen** [comment]
表达式基本可以合并main。明天下午或者晚上可以开始查hung问题。

**Comment by m-schen** [comment]
明天可以开始跟踪该issue。

**Comment by m-schen** [comment]
没进展

**Comment by m-schen** [comment]
没进展

**Comment by m-schen** [comment]
今天在搞表达式pr

**Comment by m-schen** [comment]
有相关pr 不确定需不需要回复 所以回复一下

**Comment by m-schen** [comment]
明日可验证，不过最好等tcp修复的那个pr也合并了一起验。

**Comment by m-schen** [comment]
还在验证，环境没搞好。

**Comment by m-schen** [comment]
这个今天来不及验证了，明天验证。

**Comment by m-schen** [comment]
未验证。

**Comment by aressu1985** [comment]
fixed
