### ISSUE TITLE
[Bug]: [HA]some sql was hung when logserver leader node was reboot on distributed mode with 3*logservice

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9378]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 210206b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Duaring running sysbench oltp update high concurrency test, reboot the vm where leader logservice pod is runing.
After the logservice recovery, some sql can never executed suceeded and was hung.

<img width="752" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/aecd7ebd-e5d2-40b3-9359-69aec0b3a6f3">

after checking the log , the cn did not send the update request to dn.
the log is :

[cn-dn-log.zip](https://github.com/matrixorigin/matrixone/files/11440272/cn-dn-log.zip)

the cn1 goroutine profile:
[cn1_hung_goroutin.log](https://github.com/matrixorigin/matrixone/files/11440279/cn1_hung_goroutin.log)

### Expected Behavior

after logservice recovery, the mo should became normal and can deal with all new request.

### Steps to Reproduce

```Markdown
as describe in actual behaviour
```

**Comment by daviszhen** [comment]
cn-dn-log 日志里面没有搜索到sbtest8的任何信息

**Comment by aressu1985** [comment]
我复现了这个流程，想重新拉去日志，但是发现一样的过程，登录不上了，请确认下，这个是不是#9368是不是类似的问题，等我可以抓日志的时候，我在update信息

**Comment by xzxiong** [comment]
same reason as https://github.com/matrixorigin/matrixone/issues/9368。待其解决后，再回归验证该issue

**Comment by m-schen** [comment]
这两天莫尘在帮忙追hung住的问题，还没定位到具体问题。

**Comment by m-schen** [comment]
work it tomorrow.

**Comment by m-schen** [comment]
表达式基本可以合并main。明天下午或者晚上可以开始查hung问题。

**Comment by m-schen** [comment]
明天可以开始跟踪该issue。

**Comment by m-schen** [comment]
没进展

**Comment by m-schen** [comment]
今天在搞表达式pr

**Comment by m-schen** [comment]
有相关pr 不确定需不需要回复 所以回复一下

**Comment by m-schen** [comment]
明日可验证，不过最好等tcp修复的那个pr也合并了一起验。因为tcp过多导致越来越慢的现象据说也跟假hung有关。

**Comment by m-schen** [comment]
还在验证，环境没搞好。

**Comment by m-schen** [comment]
<img width="1173" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/e99201cd-cb6b-46c9-928d-d06dfc590a13">
经验证，目前该问题已解决。我的验证流程是：
分别在eks上重启log0, log1, log2三个节点，其中log0是leader node。在log node恢复正常后mo均可以正常运行。

**Comment by aressu1985** [comment]
fixed
