### ISSUE TITLE
[Bug]: execPlan always allocation new objs while do serialize

### ISSUE THREAD

**Issue by xzxiong** [matrixorigin/matrixone#9379]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): eac20c657
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

as found in https://github.com/matrixorigin/matrixone/issues/9273

`frontend.serializePlanToJson` will alloc much obj here. in this case, it alloc 7.51% of all obj count.
- this may be one of the factors contributing to OOM

[profile.pb.gz](https://github.com/matrixorigin/matrixone/files/11440183/profile.pb.gz)

![image](https://github.com/matrixorigin/matrixone/assets/3927687/702097bc-4af2-44e4-b831-1e3b539d1909)

### Steps to Reproduce

```Markdown
1. startup mo-service

./mo-service -debug-http 127.0.0.1:8123 -allocs-profile ./allocs.profile -launch ./etc/launch-tae-multi-CN-tae-DN/launch.toml
```
2. run bvt test
3. run tpcc
```
cd .../mo-tpcc
./runSQL.sh props.mo tableCreates
./runLoader.sh props.mo warehouse 1
```
4. do profile
```
go tool pprof -inuse_objects http://127.0.0.1:8123/debug/pprof/heap
```

**Comment by qingxinhome** [comment]
Let me confirm the optimization plan

**Comment by qingxinhome** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/70939751/1646d614-dc63-4507-ab8d-522165229a2d)

**Comment by qingxinhome** [comment]
The issue has been resolved, please confirm and complete the subsequent optimization @xzxiong

**Comment by xzxiong** [comment]
[profile_ret.pb.gz](https://github.com/matrixorigin/matrixone/files/11469560/profile_ret.pb.gz)

verified, `frontend.serializePlanToJson` alloc obj count down to 0.75 % ~ 1.25 %.

![image](https://github.com/matrixorigin/matrixone/assets/3927687/70edb6e9-f276-44ff-aa17-f7f8efec0033)
