### ISSUE TITLE
[Bug]:  docker hub image with only amd64

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#9393]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Some of our dockerhub image only have amd64 version. Why is that?

<img width="1211" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/b0a5528e-314e-409e-98a9-26c5ac22196b">

**Comment by guguducken** [comment]
This is beacause the action in matrixorigin/mo-nightly-regression also push the created image to matrixorigin/matrixone in docker hub. I will talk with @heni02 to solve it.
