### ISSUE TITLE
[Bug]: eks bvt test：alter account reported table "mo_user" does not exist

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9400]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-4fca141
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4948707666/jobs/8849952012
error case reported ：SQL parser error: table "mo_user" does not exist
The mo-tester can not get valid connection to mo
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b121d8cd-0ec5-422e-a70c-ab7ba58a5b7d)
But there were no reboots or crashes in the Mo cluster
![image](https://github.com/matrixorigin/matrixone/assets/113406637/18ffccec-98f4-4ab5-9bb4-4450f1d91bd5)

mo log take here
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0f7e1171-a968-451a-b58c-0536456cf5df)

**Comment by heni02** [comment]
@daviszhen plz confirm this issue

**Comment by daviszhen** [comment]
事务没有读到mo_user表。但是mo_user 是一直存在的。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/98f3595d-f999-4ae8-8d2c-2cab8ffdd8f6)

代码上是catalog cache 没找到mo_user这个表。理论上不可能的。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/c6b8a97e-dab1-4da8-8f98-98bb3aaf166b)

大概是这个case的时候，系统不正常了。 之后case都不正常了。且报The mo-tester can not get valid connection to mo.

![Screenshot from 2023-05-12 15-12-34](https://github.com/matrixorigin/matrixone/assets/60595215/37b0de51-2eb2-43e7-8402-280915294f9a)

**Comment by nnsgmsone** [comment]
暂时没空处理这个，优先处理daily run的问题和plan分拆的问题

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by heni02** [comment]
Plz write reason for this problem, and we will try reproduce @nnsgmsone avoiding this problems in the future

**Comment by nnsgmsone** [comment]
The problem is caused by some changes to https://github.com/matrixorigin/matrixone/tree/main/pkg/vm/engine/disttae/cache, which has recently fixed some similar issues (e.g. #9476). This kind of issue has not been reproduced, it is recommended to close it if it cannot be reproduced. There are already more changes to this directory, so there is no need to go back a few weeks to the commit for this problem.

**Comment by nnsgmsone** [comment]
testing

**Comment by heni02** [comment]
Occasional occurrence of the problem, which has not been reproduced in the past 3 days in regression
In the future, we need to try to reproduce the scenario case
closed first
