### ISSUE TITLE
[Bug]: docker image boot unsuccessful

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#9409]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Pulled a latest docker version in a local Macbook machine. 

docker pull matrixorigin/matrixone:nightly-fad1eaea
docker run -d -p 6001:6001 --name matrixone matrixorigin/matrixone:nightly-fad1eaea

But it cannot boot, the bug log is:

<img width="645" alt="企业微信截图_b7ef7795-22c3-47d0-8525-fb481ec26602" src="https://github.com/matrixorigin/matrixone/assets/4965857/ffac7a15-708c-4ef1-a1c8-f91f905c8a17">

**Comment by xzxiong** [comment]
dockerfile wirte wrong startup args syntax

**Comment by xzxiong** [comment]
fixed.
@dengn you could test with  matrixorigin/matrixone:nightly-902ee2c7

**Comment by dengn** [comment]
this new one nightly-902ee2c7 works ok.
