### ISSUE TITLE
[Bug]: eks benchmark test: cn crash 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9428]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-0773713
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4970419876/jobs/8895194576
![image](https://github.com/matrixorigin/matrixone/assets/113406637/5d4c9cd3-2e2b-4b5a-91b2-e90d131b986a)

kubectl -n mo-nightly-regression logs -p nightly-regression-dis-tp-cn-0 >cn0.log
cn0.log see below

mo log s3 path：mo-ares/etl/etl_20230514161224/

**Comment by heni02** [comment]
cn0 crash log:
[cn0_crash_0514.log](https://github.com/matrixorigin/matrixone/files/11471334/cn0_crash_0514.log)

**Comment by daviszhen** [comment]
> cn0 crash log: [cn0_crash_0514.log](https://github.com/matrixorigin/matrixone/files/11471334/cn0_crash_0514.log)

日志里面有个Panic。但是不清楚是否是导致重启的原因。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/e1c3b297-c0db-4c0a-9880-648ed9443726)

**Comment by LeftHandCold** [comment]
"write loop failed",It looks like morpc reports an error @zhangxu19830126 PLZ.

**Comment by zhangxu19830126** [comment]
@m-schen 这个看上去是pushclient发送消息的时候,ctx给了nil

**Comment by m-schen** [comment]
我这边会先修改成先改成不并发再看看情况。

**Comment by m-schen** [comment]
目前在push model相关代码中没有发现给rpc传nil context参数的情况。

**Comment by heni02** [comment]
confirm, lastest commit has no this issue
commit id：nightly-a68d9da
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d3f6be6d-53ec-4eff-a4f5-ebd9b56a1e7e)
