### ISSUE TITLE
[Bug]: after drop table in explicit transactions, insert into table in new session reported error 

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9429]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):902ee2c70eaf0f64fb6adec545a51eafb5e11bad
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert reported error： the tableID can not find, maybe modify
![image](https://github.com/matrixorigin/matrixone/assets/113406637/aabab2b7-6977-4743-9b9c-ae7081828e38)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4c47e1c5-60f5-4139-9222-5c396023b4c8)

### Steps to Reproduce

```Markdown
drop table if exists atomic_table_11;
create table atomic_table_11(c1 int,c2 varchar(25));
insert into atomic_table_11 values (3,"a"),(4,"b"),(5,"c");
begin;
drop table atomic_table_11;
-- @session:id=2&user=sys:dump&password=111
insert into atomic_table_11 values (6,"a");
select * from atomic_table_11;
-- @session
select * from atomic_table_11;
commit;
select * from atomic_table_11;
```

**Comment by heni02** [comment]
confirm，closed
commit id：8c12fdb511a6dbc91b9fa989264ea48d26597379

**Comment by heni02** [comment]
#9502 revert ，this issue reopen

**Comment by heni02** [comment]
confirm,closed
commit id:67c4f656bb936eb1263bcd1c77e331d683cc6ed6
![image](https://github.com/matrixorigin/matrixone/assets/113406637/3d32e60a-589b-44fe-a770-10dc1893363c)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/bb9fcb67-bed0-44ff-af85-d6961abfa345)

**Comment by heni02** [comment]
maybe related #9914

**Comment by qingxinhome** [comment]
This issue has been verified and resolved. Please verify and test it @jianwan0214 @heni02 @daviszhen

**Comment by heni02** [comment]
now insert reported table not exists, should reported such as w-w confilct or no such table  during the commit ？This behavior requires confirmation
commit id:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/0c9a7c1a-435d-49c7-998e-ec2400757600)

**Comment by domingozhang** [comment]
after error 1146, the transaction in session 1 was forced to rollback. this needs to be switched to manual

**Comment by domingozhang** [comment]
only load data needs the error in the second line.
insert needs to keep on current transaction

**Comment by heni02** [comment]
This issue finally resolved to adjust behavior , downgraded to s1

**Comment by daviszhen** [comment]
未投入

**Comment by sukki37** [comment]
This issue has been inactive. Closing to keep the tracker clean. Reopen if still relevant. Thanks!

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
