### ISSUE TITLE
[Bug]: bvt case insert.test failed

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#9434]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 09ebd31398c1d0136a4718066cb48c7ec20bea0a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/1e000e60-d4c7-43d3-8ce5-c559ab9e8972">
[bvt.log](https://github.com/matrixorigin/matrixone/files/11471735/bvt.log)

测试文件：test/distributed/cases/dml/insert/insert.test

result文件中的 EXCPET RESULT 与 insert.result 中的不一样，导致bvt失败。

**Comment by aressu1985** [comment]
triaging

**Comment by aressu1985** [comment]
triaging

**Comment by aressu1985** [comment]
It is not a bug. because the default separator is four blacks. and the results contains it.
so need to designate table as separator by tag : -- @separator:table

**Comment by aressu1985** [comment]
fixed
