### ISSUE TITLE
[Bug]: bitmap emptyFlag race condition

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9442]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When calling bitmap methods, it many write to emptyFlag and create a w-w race condition.   It may cause UT failure
The [hack](https://github.com/matrixorigin/matrixone/blob/c015c23fb97d84249962506061c1b9699872a8df/pkg/container/nulls/nulls.go#LL262C1-L262C1) reduced the chance of race condition but does not really eliminate it.

In fact I dont know how we can possibly eliminate it from within nulls or bitmap.

Seems we need to ensure the vector is not used by two threads at the same time.   Unless for those that has been "frozen", that is, those are shared must be read only.    We should just call IsEmpty to set the flag and make the vector truly readonly before sharing.

While this is a race bug, it seems to be OK -- as long as we only share "frozen" vector.   

I am not sure what is the right thing.   Could be
1. atomic write to the flag,
2. Implement the "freeze" check.

**Comment by badboynt1** [comment]
emptyflag当时是为了解决一个性能问题加进去的，我在想是不是等0.8以后可以抽空看看这个数据结构是否还慢？ emptyflag是否可以移除掉？ 如果这里还是比较慢，是不是可以重构一下bitmap，例如使用roaring bitmap来应对这种稀疏的情况？

**Comment by badboynt1** [comment]
等0.8以后再看这个问题

**Comment by badboynt1** [comment]
already fixed in  https://github.com/matrixorigin/matrixone/pull/9711
