### ISSUE TITLE
[Bug]: TPCH QUERY Q7 can not succeed and TPCH test cause mo killed by oom

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9443]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):93f4fc584621d710dfb65b4f254512f31bc79c57
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1006" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/67511c1e-5dd4-4e7b-9a22-df7e288f7b64">

<img width="1023" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b1476c4d-adb0-4340-b722-3f05fa9b4195">

sys log:
May 15 05:17:12 mo-srv-128 kernel: [3420606]  1035 3420606     4381      142    61440       46           500 bash
May 15 05:17:12 mo-srv-128 kernel: [3420607]  1035 3420607    24186      226   208896        0           500 mysql
May 15 05:17:12 mo-srv-128 kernel: [3420653]     0 3420653     1829       18    65536        0             0 sleep
May 15 05:17:12 mo-srv-128 kernel: [3421296]     0 3421296     1829       19    65536        0             0 sleep
May 15 05:17:12 mo-srv-128 kernel: [3421303]  1035 3421303      114        2    36864        0           500 date
May 15 05:17:12 mo-srv-128 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-0.slice/session-2552.scope,task=mo-service,pid=3393601,uid=1035
May 15 05:17:12 mo-srv-128 kernel: Out of memory: Killed process 3393601 (mo-service) total-vm:285176888kB, anon-rss:245149352kB, file-rss:0kB, shmem-rss:0kB, UID:1035 pgtables:529588kB oom_score_adj:500
May 15 05:17:23 mo-srv-128 kernel: oom_reaper: reaped process 3393601 (mo-service), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
May 15 05:17:29 mo-srv-128 systemd[1]: clickhouse-server.service: Service RestartSec=30s expired, scheduling restart.
May 15 05:17:29 mo-srv-128 systemd[1]: clickhouse-server.service: Scheduled restart job, restart counter is at 508551.
May 15 05:17:29 mo-srv-128 systemd[1]: Stopped ClickHouse Server (analytic DBMS for big data).
May 15 05:17:29 mo-srv-128 systemd[1]: Started ClickHouse Server (analytic DBMS for big data).
May 15 05:17:30 mo-srv-128 clickhouse-server[3423141]: Processing configuration file '/etc/clickhouse-server/config.xml'.
May 15 05:17:30 mo-srv-128 clickhouse-server[3423141]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
May 15 05:17:30 mo-srv-128 clickhouse-server[3423141]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
May 15 05:17:31 mo-srv-128 systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=70/SOFTWARE
May 15 05:17:31 mo-srv-128 systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.

[mo-tpch.tar.gz](https://github.com/matrixorigin/matrixone/files/11473293/mo-tpch.tar.gz)

### Expected Behavior

TPCH TEST SHOULD NEVER FAIL

**Comment by aunjgr** [comment]
PR merged and verified. Please confirm.

**Comment by aressu1985** [comment]
fixed
