### ISSUE TITLE
[Bug]: pipeline context has done

### ISSUE THREAD

**Issue by badboynt1** [matrixorigin/matrixone#9459]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

there's a chance for this problem.

mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
Empty set (0.02 sec)

mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
ERROR 20101 (HY000): internal error: pipeline context has done.
mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
Empty set (0.07 sec)

mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
Empty set (0.02 sec)

mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
ERROR 20101 (HY000): internal error: pipeline context has done.
mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
Empty set (0.02 sec)

mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
Empty set (0.08 sec)

mysql> select * from lineorder right join supplier on lo_suppkey=s_suppkey where s_city='abcd';
Empty set (0.01 sec)

### Expected Behavior

return empty results

**Comment by tianyahui-python** [comment]
Q7 execution will be affected and the system will be upgraded to S-1

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
update some info in MO-Cloud#774

**Comment by tianyahui-python** [comment]
> 错误原因和 9459 不一样

> 9459 是因为有一边为空表之后有概率出现结束情况判断的错误 这个是因为中间构建 hashtable 的时候大小过大，构建 > > > > > > hashtable 所在的 pipeline 结束之后退出了，但是错误被污染了没有正确返回到上层 image
> 所以这个 issue 的根本错误原因是 plan 构造出现了问题，导致 build 端错误。 鉴于最新 main 都可以跑过 tpch，这个问题应该已> 经被修复

基于以上原因, 恢复为之前的s0级别

**Comment by dongdongyang33** [comment]
in process

**Comment by dongdongyang33** [comment]
in process

**Comment by dongdongyang33** [comment]
in process

**Comment by dongdongyang33** [comment]
in process

**Comment by dongdongyang33** [comment]
in process

**Comment by aressu1985** [comment]
fixed
