### ISSUE TITLE
[Bug]: the point_select perf on trace-on decrease for about 30% than trace-off

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9472]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):603c4daddcec079cf4680b1aa0a65dfe3f0025a1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1200" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/732a2e24-94d3-4c81-9f1f-fe9ed76e2251">

please assgin to @xzxiong , he will invole in this. and has discussed with him ,if wanted some moer information , he will contarct me .

**Comment by xzxiong** [comment]
doing https://github.com/matrixorigin/matrixone/issues/9439 now.

**Comment by xzxiong** [comment]
case
- log level: `FATAL`

performance
- trace on (qps):  28308 
- trade off (qps):  39038

 perfor down: 28308 / 39038 ~= 0.725

**Comment by xzxiong** [comment]
will analysis tomorrow

**Comment by xzxiong** [comment]
try repro on main (https://github.com/matrixorigin/matrixone/commit/3c8f42dffa08b05dcc412094c6368261e3d57167) today

- new result
1. trace on with qps: 5108.27
2. trace off with qps: 8749.58
3. (*) trace on BUT no record exec_plan: 7919.59.  ( code changed as following)

![image](https://github.com/matrixorigin/matrixone/assets/3927687/522476b4-8e7d-4c94-81fb-00dceffd41fa)

- why i try to ignore exec_plan ?
after diff cpu profile between [cpu.trace_on.pb.gz](https://github.com/matrixorigin/matrixone/files/11544016/cpu.trace_on.pb.gz)  and  [cpu.trace_on.pb.gz](https://github.com/matrixorigin/matrixone/files/11544018/cpu.trace_on.pb.gz),
I find `mpool.(*MPool).Alloc` cpu cost increased from **0.9 %** up to **14.32 %**.
and the mem diff is that execPlan hold by statement_info for BatchOp in 15s

![image](https://github.com/matrixorigin/matrixone/assets/3927687/8c49028e-9033-4596-a7c1-fa0ee5a52846)

**Comment by xzxiong** [comment]
date: 2023-05-26
progress:  主要由于 gc导致的时间消耗
commit: 0fc37ced9
qps
- trace on: 5338.89
- trace off: 13328.97
- trace on NoPlan: 11901.99

gc debug info, start cmd: `GODEBUG=gctrace=2 ./mo-service -debug-http :8123 -allocs-profile ./allocs.profile -launch ./etc/launch-tae-CN-tae-DN/launch.toml`
[gc.trace_on.log](https://github.com/matrixorigin/matrixone/files/11571337/gc.trace_on.log)
[gc.trace_off.log](https://github.com/matrixorigin/matrixone/files/11571338/gc.trace_off.log)
[gc.trace_on_NO_plan.log](https://github.com/matrixorigin/matrixone/files/11571339/gc.trace_on_NO_plan.log)

**Comment by xzxiong** [comment]
new progress:
trace on ~= 92% * trace off

more details later

**Comment by fengttt** [comment]
Point select should be less than "long query threshold" and should not record exec plan.

Also see [ ](https://github.com/matrixorigin/matrixone/issues/9834).   I think these are related.

**Comment by xzxiong** [comment]
re-check version: `commit id: b85dc029f`
dev: macbook pro M1
test case: mo-sysbench, point_select, 10 tables, 10w rows

Basic Situation
---
- trace-on has `33115.90 qps`, and trace-off has `39167.87 qps`
- perf on trace-on descrease about `15.5%`


mo-sysbench exec record, [mo-sysbench.cmp.trace_on.and.trace_off.txt](https://github.com/matrixorigin/matrixone/files/12365169/mo-sysbench.cmp.trace_on.and.trace_off.txt)

Go cpu pprof
---

In trace_on case, there is new cpu consumer, `MOSpan.End`, cost about 9.6% cpu time.
This should be next target for further analysis.

[cpu.profile.trace_on.pb.gz](https://github.com/matrixorigin/matrixone/files/12365178/cpu.profile.trace_on.pb.gz)
[cpu.profile.trace_off.pb.gz](https://github.com/matrixorigin/matrixone/files/12365196/cpu.profile.trace_off.pb.gz)

- cpu profile ( trace off)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/e2e8f4c6-f023-45a6-a794-7f95f48cbafa)

- cpu profile (trace on)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/06d83aff-dbee-43b6-b622-c562ff490029)
![image](https://github.com/matrixorigin/matrixone/assets/3927687/78ac1ad5-0e2a-4932-952e-a831f9cf072b)



> Go mem pprof, just in case
[mem.profile.trace_on.pb.gz](https://github.com/matrixorigin/matrixone/files/12365179/mem.profile.trace_on.pb.gz)
[mem.profile.trace_off.pb.gz](https://github.com/matrixorigin/matrixone/files/12365197/mem.profile.trace_off.pb.gz)

**Comment by xzxiong** [comment]
check newset status with new commit in branch main: ddf43cc2b
bref result is : perf on trace-on descrease about `3.9 % ~ 6.5 %`
- trace-on MO's  qps is : 35415 ~  38328
- trace-off MO's qps is : 37749 ~ 39822

sysbench case is same as before:
- dev: macbook pro M1
- test case: mo-sysbench, point_select, 10 tables, 10w rows

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fxied
