### ISSUE TITLE
[Bug]: eks bvt test：non sys account show database or table error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9479]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-e863427
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

jobs: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4981280157/jobs/8928953574
![image](https://github.com/matrixorigin/matrixone/assets/113406637/135794c7-22d0-4d90-9644-c40dc2598c67)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/8b80cb5f-93bf-4ece-a7ee-60acd641378e)

mo cn，dn log：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/5a55747b-b51f-4f67-8f91-756e40118030)

**Comment by heni02** [comment]
@daviszhen plz confirm this issue

**Comment by daviszhen** [comment]
观察到两个现象。
1，出问题的两个语句。show databases; show tables 的事务在dn.log里面没有。可能是dn日志不全。

2，两个语句之前，插入了2条 select mo_ctl('cn', 'synccommit', '')语句。但是bvt 里面没有这个语句。不确定是否与这个语句有关。

![Screenshot from 2023-05-16 16-12-40](https://github.com/matrixorigin/matrixone/assets/60595215/07827a4c-fa89-44c9-b361-cec436bfe66a)

![Screenshot from 2023-05-16 16-14-47](https://github.com/matrixorigin/matrixone/assets/60595215/b0648c86-6857-4f48-b001-d2a357812814)

**Comment by nnsgmsone** [comment]
这个是否和最近的catlog cache的一些修改有关系呢

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by heni02** [comment]
Plz write reason for this problem, and we will try reproduce @nnsgmsone avoiding this problems in the future

**Comment by nnsgmsone** [comment]
The problem is caused by some changes to https://github.com/matrixorigin/matrixone/tree/main/pkg/vm/engine/disttae/cache, which has recently fixed some similar issues (e.g. #9476). This kind of issue has not been reproduced, it is recommended to close it if it cannot be reproduced. There are already more changes to this directory, so there is no need to go back a few weeks to the commit for this problem.

**Comment by heni02** [comment]
Occasional occurrence of the problem, which has not been reproduced in the past 3 days in regression
In the future, we need to try to reproduce the scenario case
closed first
