### ISSUE TITLE
[Bug]: connection sometimes could be lost during TPCC 10 warehouse test on EKS with 2*cn (occationally)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9481]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-27c0e5e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

After TPCC 10 warehouse test(10 minutes), checking the run log, there are one connection lost .
<img width="1109" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/5e4eaf02-3445-4c54-bd5c-382ced2cd9ae">

<img width="1111" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/f277dccc-02c1-4a02-b19d-dfa1a3ed46a3">

this did not happen every time.

the log is on s3:
s3://mo-ares/etl/etl_20230515210736/

### Steps to Reproduce

```Markdown
1、RUN a mo cluster on EKS with 2*cn
2、run tpcc 10 warehouse 50 terminals for 10 mimutes，and run serval times

may can repro this
```

**Comment by xzxiong** [comment]
job MO Nightly Regression On EKS
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/4982564057/jobs/8922593658

**Comment by daviszhen** [comment]
@xzxiong @aressu1985 第一张图的s3 bucket是哪个？

**Comment by daviszhen** [comment]
还未找到error的日志行。。。。

**Comment by daviszhen** [comment]
发现日志里有些问题。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/6e4702c1-7c1f-4c6b-b565-3a7208a57684)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/7692c201-da0e-4b5b-9727-6c45e4b7a016)

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/5030940232/jobs/9023783546

**Comment by daviszhen** [comment]
5月15日的日志分析结果：
1，大量retry/middleware.go的报错。之前在issue群里说过。应该是一个依赖库问题。 不会造成client连接断开。
![Screenshot from 2023-05-20 19-38-11](https://github.com/matrixorigin/matrixone/assets/60595215/f8b036b9-9659-4db1-ae69-1195947fcf0c)

2，handle session failed 报错。这是正常的行为。frontend在收到client得COM_QUIT时，主动返回一个error，告诉goetty关闭连接。这是client的主动断开。

![Screenshot from 2023-05-20 19-36-10](https://github.com/matrixorigin/matrixone/assets/60595215/9e7c5789-3e10-40a5-b9d1-847c0b9cf62c)

3，w-w conflict。这类是tpcc场景下不可避免的。不会造成client连接断开。

4，read from backend failed. 这是CN与DN之间的rpc报错。不会造成client连接断开。

![Screenshot from 2023-05-20 19-41-48](https://github.com/matrixorigin/matrixone/assets/60595215/4766c5f7-7c77-447f-9268-3a0636a1f0fa)

**Comment by daviszhen** [comment]
> repro: https://github.com/matrixorigin/matrixone/actions/runs/5030940232/jobs/9023783546

这个明天接着分析。

**Comment by daviszhen** [comment]
> > repro: https://github.com/matrixorigin/matrixone/actions/runs/5030940232/jobs/9023783546
> 
> 这个明天接着分析。

日志已经分析了。也没找到关键的错误消息。没定位到出错行。

**Comment by daviszhen** [comment]
等苏动的测试结果。到下周一。

**Comment by daviszhen** [comment]
等苏动的测试结果。到下周一。

**Comment by daviszhen** [comment]
@aressu1985 工具延长超时时间后。没有再复现。

**Comment by aressu1985** [comment]
tracking for more days

**Comment by aressu1985** [comment]
this can be closed, tracking by #9867
