### ISSUE TITLE
[Bug]: Default conf turn-on-push-model is set to false

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9483]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):n.a.
- Hardware parameters:n.a.
- OS type:n.a.
- Others:n.a.
```

### Actual Behavior

Currently the default setting of `turn-on-push-model` in `cn.toml` to set to `false`, but it is said that it's recommended to set this conf to `true` to gain better performance. 

### Expected Behavior

Is it possible to set this parameter to `true` by default?

### Steps to Reproduce

```Markdown
1. `git clone` mo codes from github repository
2. `make build`
3. check `./matrixone/etc/launch-tae-CN-tae-DN/cn.toml` file for conf `turn-on-push-model`
```

### Additional information

n.a.

**Comment by m-schen** [comment]
可以

**Comment by m-schen** [comment]
明天提个pr默认打开。

**Comment by aronchanisme** [comment]
As per discussed, this parameter is set to true by default and on longer editable via conf file. Closing it now.
