### ISSUE TITLE
[Bug]: `/debug/perfcounter` doesn't exhibit some statistics counter

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#9487]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8c12fdb511a6d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="484" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/00d6a7da-e4df-424a-92fc-3bf8271b7279">

### Expected Behavior

`MetadataInsertEntries` should be seen.

### Steps to Reproduce

```Markdown
1. start mo-service under push model
2. launch tpcc load
3. check perfcounter with endpoint: `http://${SERVICE_IP}:${DEBUG_HTTP_PORT}/debug/perfcounter`
```

**Comment by xzxiong** [comment]
MetadataInsertEntries already in counter

**Comment by reusee** [comment]
done, re-assigning
