### ISSUE TITLE
[Bug]: insert into values in explicit transaction reported Column '__mo_fake_pk_col' cannot be null

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9491]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):8c12fdb511a6dbc91b9fa989264ea48d26597379
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
after drop table commit，insert into values in explicit transaction reported Column '__mo_fake_pk_col' cannot be null

![image](https://github.com/matrixorigin/matrixone/assets/113406637/5c78ee79-f822-46de-a4a9-f23df659e685)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ccb6fa95-d231-4d48-9fc0-96680507922b)

### Steps to Reproduce

```Markdown
create table t1(a int);
begin ;
-- @session:id=2&user=sys:dump&password=111
drop table t1;
-- @session
insert into t1 values (1);
commit;
```

**Comment by heni02** [comment]
@domingozhang plz confirm insert behavior

**Comment by w-zr** [comment]
should be fixed after https://github.com/matrixorigin/matrixone/pull/9502

**Comment by domingozhang** [comment]
here is the same scenario in previous commit :

session 1:
<img width="273" alt="1684291899168" src="https://github.com/matrixorigin/matrixone/assets/88298673/201808a9-23ec-46c1-a1f2-a81316f8e5f7">

session 2:
<img width="265" alt="1684291927007" src="https://github.com/matrixorigin/matrixone/assets/88298673/f773f252-e780-4765-b6fd-0dffa7d9e58a">

session 1:
<img width="461" alt="1684291961863" src="https://github.com/matrixorigin/matrixone/assets/88298673/6b56e12c-60da-4351-9728-c07756d4c20d">


after @jianwan0214  fixes the bug for table id not existing when commiting, there will be an error in commit phase but there is no error message before committing;

**Comment by heni02** [comment]
alter s1 first, and check after pr agin merge

**Comment by heni02** [comment]
After the PR revert, there is no longer this issue
confirm,closed
commit id:1ef0c1f9a647a808595295962cbe6e6f9aaf35b9
