### ISSUE TITLE
[Bug]: drop account reported no such table mo_catalog.mo_pubs

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9492]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8c12fdb511a6dbc91b9fa989264ea48d26597379
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/113406637/e16aff4c-cbba-4f64-b058-9eb7deb0f3b1)

### Steps to Reproduce

```Markdown
drop account if exists trans_acc1;
```

**Comment by daviszhen** [comment]
@heni02  创建租户的语句是啥样的？create account 成功了吗?

**Comment by YANGGMM** [comment]
<img width="506" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/20f482c9-6101-4bb1-a231-55ccf3205586">

**Comment by YANGGMM** [comment]
<img width="549" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/12ceac5a-5b28-4828-8897-2628f34cab6d">
<img width="598" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/ea9bcd99-721c-4f68-9514-97f601087d40">

**Comment by YANGGMM** [comment]
> @YANGGMM @daviszhen 看来是依赖上下case导致的，我明天再排查下复现步骤

好的

**Comment by heni02** [comment]
从case文件上下来看，初步判断是自增列pr合入导致的，#9491 和这个问题同一类，待pr revert后验证

**Comment by heni02** [comment]
After the PR revert, there is no longer this issue
confirm,closed
commit id:1ef0c1f9a647a808595295962cbe6e6f9aaf35b9
