### ISSUE TITLE
[Bug]: mo-service panic on startup

### ISSUE THREAD

**Issue by cnutshell** [matrixorigin/matrixone#9495]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 8c12fdb511a
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mo-service panic on startup within CI environment.

<img width="1437" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/91656d0b-5294-44ec-98eb-7ea32403c7af">

### Expected Behavior

no panic, mo-service should be runable

### Additional information

https://github.com/matrixorigin/matrixone/actions/runs/4990925121/jobs/8936739229?pr=9489

**Comment by zhangxu19830126** [comment]
pr reverted

**Comment by cnutshell** [comment]
closed as a result to PR reverted
