### ISSUE TITLE
[Bug]: mo can not work on eks for error 'table "mo_account" does not exist'

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9499]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The MO can start normally. But when connection to it，the mo can not work。
the error is:

<img width="1360" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e3f715d0-e37d-45d1-b8bf-f43393aed98c">

log :

s3://mo-ares/etl/etl_20230516170247/

### Steps to Reproduce

```Markdown
run a mo cluster on eks
```

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by m-schen** [comment]
这个应该mo本身的启动过程就出问题了，只是没有抛出错误。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
cannot be reproduced after pr #9711, should have been fixed @heni02

**Comment by aressu1985** [comment]
tracking

**Comment by aressu1985** [comment]
fixed
