### ISSUE TITLE
[Bug]: size unit suffix 'b' should be optional

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#9507]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3dfc8253f54c90c78de2985c01f26468c516657d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Configure `memory-capacity` to `10Gi`, and start the mo-service

```
error: invalid suffix 'gi'
```

This issue is introduced by upgrading `https://github.com/docker/go-units` from `v0.4.0` to `v0.5.0`, the commit https://github.com/docker/go-units/commit/737572633c434ce2d80ba3fbe2d8ea15d7d821ff change the unit parsing algorithm from regex to basic string parsing, which introduce a bug that the `b` or `B` suffix is now required.

xref: As documented in the package itself,  the `b` suffix is optional, which is also documented in https://en.wikipedia.org/wiki/Binary_prefix

### Expected Behavior

Both `10Gi` and `10GiB` should be valid unit.

**Comment by aylei** [comment]
@aunjgr can we simply downgrade `go-units`?

**Comment by aylei** [comment]
https://github.com/matrixorigin/matrixone-operator/pull/359 this would make operator compatible with both `go-units@v0.4.0` and `go-units@v0.5.0`

**Comment by sukki37** [comment]
@aylei Any updates on this issue? It's been a while since the last comment.

**Comment by aylei** [comment]
> @aylei Any updates on this issue? It's been a while since the last comment.

I'd close this since operator no longer need this compatibility change, we may reopen this if there is a customer request for this
