### ISSUE TITLE
[Bug]: [date 5.18 nightly-76dd6de]eks bvt test: drop table t1 reported backend closed

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9528]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-76dd6de
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5010051029/jobs/8979624478
1. drop table reported backend closed
![image](https://github.com/matrixorigin/matrixone/assets/113406637/2ff45488-e38b-4492-9761-fe00cff4b9ce)
2023-05-18 03:19:30 ERROR Executor:212 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/dml/insert/insert.test][row:34][drop table if exists t1;] was executed failed, con[id=0, user=dump, ***
2023-05-18 03:19:30 ERROR Executor:214 - [EXPECT RESULT]:
null
2023-05-18 03:19:30 ERROR Executor:215 - [ACTUAL RESULT]:
backend closed

2. insert into values（）,() reported invalid input: invalid default value for column 'a'
2023-05-18 03:19:30 ERROR Executor:212 - [/runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/test/distributed/cases/dml/insert/insert.test][row:36][insert into t1 values(), ();] was executed failed, con[id=0, user=dump, ***
2023-05-18 03:19:30 ERROR Executor:214 - [EXPECT RESULT]:
null
2023-05-18 03:19:30 ERROR Executor:215 - [ACTUAL RESULT]:
invalid input: invalid default value for column 'a'
mo cn,dn log:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/10f8c3ac-3cf7-4db4-abf2-3103078d7727)

**Comment by daviszhen** [comment]
cn0.log 里面有根rpc 失败相关的内容。


![image](https://github.com/matrixorigin/matrixone/assets/60595215/2ff12bf9-5937-4182-8ffb-1fe7fe8dace5)

**Comment by daviszhen** [comment]
请做logtail rpc相关的同事去看了

**Comment by XuPeng-SH** [comment]
@cnutshell Please have a look at this issue

**Comment by cnutshell** [comment]
cn 重连时，可能会出现 mo-service hung 的情况，这个问题已在 `commit: 245c861e63ea3ab`  中修复

**Comment by cnutshell** [comment]
`2023-05-18 03:19:10` 时，`delete from t where a > 1;` 执行超时：
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/f4f12417-e246-496f-a4b8-afa8d96fcbac">

原因为 cn1 执行 sql 时 panic 退出：
```json
{"level":"INFO","time":"2023/05/18 03:19:10.889789 +0000","caller":"frontend/util.go:405","msg":"query trace","connection_id":12,"query":"delete from t where a > 1;","session_info":"connectionId 12|10.0.125.14:59248|{account sys:dump:moadmin -- 0:1:0}|1d977750-f52a-11ed-a4d5-e2378c66821f"}
```
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/d76b1c73-423c-4575-9dce-f01197c8162e">

**Comment by cnutshell** [comment]
`backend closed` 需要继续分析

**Comment by cnutshell** [comment]
`2023/05/18 03:19:30.592680`, `cn0` 执行 `drop table if exists t1` 时报错: `backend closed`


下载 bvt 日志后，结合 cn0.log 和 dn.log 分析，大致过程如下：
`2023/05/18 03:19:30.560833`, `dn` 向 `cn0` 返回对表 `db_id:273682 tb_id:273690` 的订阅响应；
`2023/05/18 03:19:30.588429`, `cn0` 收到 morpc client 用 `nil` morpc message 代表的报错，判断 `stream closed`；
`2023/05/18 03:19:30.588477`, `cn0` 触发重连过程，连接 `dn`；
`2023/05/18 03:19:30.588580`, morpc client 读端因 tcp 连接关闭，报错并退出：`read tcp4 10.0.100.133:39296->10.0.105.168:32003: use of closed network connection`；
`2023/05/18 03:19:30.588704`, morpc client 写端退出；
`2023/05/18 03:19:30.590712`, `dn` 侧 morpc server 写 tcp 连接报错 `write tcp4 10.0.105.168:32003->10.0.100.133:39296: use of closed network connection"`；
`2023/05/18 03:19:30.592163`, morpc client 报错 `backend closed`；

从日志来看，morpc stream 对应的 tcp 连接关闭是由 cn 重连时触发的，这一点可以从随后 morpc client 和  morpc server 读写 tcp 时均报错 `use of closed network connection` 来确认。那么在 cn 重连之前，tcp 连接可以读写的情况下，morpc client 向 cn0 返回了代表 stream closed 的 nil morpc message，导致了 `backend closed` 的报错。

从 cn0 日志中，无法判断 morpc client 为何在 tcp 连接尚可读写的情况下原因，请 morpc 同事进一步分析。

**Comment by cnutshell** [comment]
> 从 cn0 日志中，无法判断 morpc client 为何在 tcp 连接尚可读写的情况下原因，请 morpc 同事进一步分析。

不论 morpc client 的实现是否存在 bug，tcp 连接断开的情况总是不可避免，客户端收到 `backend closed` 错误之后，重试即可。

**Comment by heni02** [comment]
如果因为rpc原因报错的话，需要报错信息格式为错误码：可读的报错原因信息

**Comment by cnutshell** [comment]
@zhangxu19830126 a better error message is always welcome,PTAL

**Comment by zhangxu19830126** [comment]
@cnutshell better needs to be generated outside in conjunction with the context, rather than modifying the rpc internal

**Comment by cnutshell** [comment]
@zhangxu19830126 Please provide more information to frontend guys to help them to generate better error message to user.

**Comment by cnutshell** [comment]
@heni02 Please check this issue after PR #9700 merged.

**Comment by heni02** [comment]
errmessage confirm，closed
