### ISSUE TITLE
[Bug]: [date 5.18 nightly-76dd6de]eks bvt test：some show related case results error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9531]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-76dd6de
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5010051029/jobs/8979624478
![image](https://github.com/matrixorigin/matrixone/assets/113406637/fed70399-bfb4-41a1-b5d9-b20a2e167e1c)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/51a22cfa-c9ee-4cf0-ad03-ab71a2e72e9e)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e9bfb209-2adf-4e25-b1d3-03370dd4cc47)

mo cn，dn log：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/986cb49e-da70-4a2f-8502-7eb94ed4e9c0)

**Comment by daviszhen** [comment]
三条show column_number from 执行期间没有报错。
不确定是计算还是logtail有问题。

![Screenshot from 2023-05-18 19-27-31](https://github.com/matrixorigin/matrixone/assets/60595215/a95b74b4-c2cd-4021-a289-341562945008)

![Screenshot from 2023-05-18 19-27-54](https://github.com/matrixorigin/matrixone/assets/60595215/bf144f7e-ada5-4f80-8c8e-36bf339de12d)

![Screenshot from 2023-05-18 19-28-14](https://github.com/matrixorigin/matrixone/assets/60595215/efa89a07-d995-447e-8785-1ec9b66cb8ef)

**Comment by daviszhen** [comment]
第3张截图上的结果都少了mo_catalog这个数据库。

![Screenshot from 2023-05-19 11-35-39](https://github.com/matrixorigin/matrixone/assets/60595215/351fd912-2446-4603-9ea9-25d3e4c7b29e)

此时cn已经不正常了。
show databases执行过程中，没有出任何错误。但是结果不正确。


上个例子对应的日志。

![Screenshot from 2023-05-19 11-39-49](https://github.com/matrixorigin/matrixone/assets/60595215/8343855d-3594-4fa8-b743-60d0bffda87d)


![Screenshot from 2023-05-19 11-40-36](https://github.com/matrixorigin/matrixone/assets/60595215/83cc9ccf-baad-4d79-b92f-9de3dcdb15d3)

**Comment by daviszhen** [comment]
@nnsgmsone PLZ

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
处理好plan分拆的问题后再处理这个。。

**Comment by nnsgmsone** [comment]
cannot be reproduced after pr #9711, should have been fixed @heni02

**Comment by heni02** [comment]
Plz write reason for this problem, and we will try reproduce @nnsgmsone avoiding this problems in the future

**Comment by nnsgmsone** [comment]
The problem is caused by some changes to https://github.com/matrixorigin/matrixone/tree/main/pkg/vm/engine/disttae/cache, which has recently fixed some similar issues (e.g. #9476). This kind of issue has not been reproduced, it is recommended to close it if it cannot be reproduced. There are already more changes to this directory, so there is no need to go back a few weeks to the commit for this problem.

**Comment by nnsgmsone** [comment]
testing

**Comment by heni02** [comment]
Occasional occurrence of the problem, which has not been reproduced in the past 3 days in regression
In the future, we need to try to reproduce the scenario case
closed first
