### ISSUE TITLE
[Bug]: bvt test can not succeed for error "no such table test.t" 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9543]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):245c861e63ea3abc66af5a8b2d531c98a553a99b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1169" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/98ee6e95-60ad-46e7-a5be-e6e22665cd97">

the mo log:
[mo-bvt.tar.gz](https://github.com/matrixorigin/matrixone/files/11512622/mo-bvt.tar.gz)

### Expected Behavior

All the bvt cases should succeed any time

**Comment by LeftHandCold** [comment]
same as #9447

**Comment by daviszhen** [comment]
这个问题很诡异。
出问题的是202行。但是202行前面的6个同样insert语句正确执行了。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/9ea89105-9c7c-4b8b-834e-9fc888218167)

出问题的位置在txn_database.go catalogCache 找不到数据库。
catalogCache应该一直是有的。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/25fa72ad-72b5-4c8b-a5f9-0704c700934b)

https://github.com/matrixorigin/matrixone/blob/245c861e63ea3abc66af5a8b2d531c98a553a99b/pkg/vm/engine/disttae/txn_database.go#L146

**Comment by aressu1985** [comment]
fixed
