### ISSUE TITLE
[Bug]: System internal table %!%mo_increment_columns is shown in every database

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9553]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): `b247d06`
- Hardware parameters:
- OS type:
- Others:

root@HOST-10-206-32-16:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@HOST-10-206-32-16:~# uname -a 
Linux HOST-10-206-32-16 5.10.0-0.deb10.19-amd64 #1 SMP Debian 5.10.149-2~deb10u1 (2022-10-28) x86_64 GNU/Linux
```

### Actual Behavior

When use `show tables in ${dbname}` in every database, it seems there is an internal table `%!%mo_increment_columns` in every one of them.
<img width="683" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/e8dac95c-9ce9-45c7-a3d3-0337785fd9c3">

### Expected Behavior

Don't show any internal table created by system when `show tables in ${dbname}`, but instead show all of the business tables that created by user.

### Steps to Reproduce

```Markdown
`show tables in ${dbname}`
```

### Additional information

none

**Comment by daviszhen** [comment]
@jianwan0214 看下

**Comment by aronchanisme** [comment]
好的，今天复测下

**Comment by aronchanisme** [comment]
It's gone now, thanks for the fix.

```bash
commit 70d41fc5e10c9b9dc12f8ed34f1a1798f763069f
Author: reusee <reusee@gmail.com>
Date:   Sat May 20 15:42:54 2023 +0800
```
<img width="693" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/ec50dd52-91ad-4828-a762-4726584f34fb">
