### ISSUE TITLE
[Bug]: DN panic during sysbench test

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9562]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/m-schen/matrixone/commit/84194deb38d5c8e135f28610931ba42e8083d7b1
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1263" alt="企业微信截图_1b84feb6-b297-4cb6-b318-30d656442571" src="https://github.com/matrixorigin/matrixone/assets/77312370/b7dc804c-c4e8-4e77-b3c0-2c1920ce3953">

[dn.log](https://github.com/matrixorigin/matrixone/files/11521421/dn.log)

**Comment by zhangxu19830126** [comment]
done

**Comment by sukki37** [comment]
After pr #9564, panic has been changed to an error log， but it still needs to be continuously followed up to determine the root cause. @zhangxu19830126
