### ISSUE TITLE
[Bug]: `load data local` hangs

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#9565]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): AWS: nightly-245c861e, aliyun: nightly-c015c23f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The `LOAD DATA local INFILE` hangs with the following operation:
```
mysql> create database test;
mysql> use test;
mysql> CREATE TABLE t1 (
    ->     c1 bigint,
    ->     c2 bigint,
    ->     c3 bigint,
    ->     c4 bigint,
    ->     c5 bigint,
    ->     c6 bigint,
    ->     c7 bigint,
    ->     c8 bigint,
    ->     c9 double,
    ->     c10 double,
    ->     c11 double
    -> );
mysql> LOAD DATA local INFILE '/Users/matrixorigin/dan/test/ex_table_dan_gzip.gz' INTO TABLE t1;
```

### Expected Behavior

Load data successfully

### Steps to Reproduce

```Markdown
See detail in `Actual Behavior`
```

### Additional information

It hangs on both AWS and aliyun clusters.

**Comment by volgariver6** [comment]
I will take this one.

**Comment by volgariver6** [comment]
fixed by #9720

**Comment by DanielZhangQD** [comment]
To be verified

**Comment by DanielZhangQD** [comment]
Verify with nightly-84b8491c and get the following error:
```
MySQL [test]> LOAD DATA local INFILE '/Users/matrixorigin/dan/test/ex_table_dan_gzip.gz' INTO TABLE t1;
ERROR 1105 (HY000): EOF
```

**Comment by DanielZhangQD** [comment]
The `LOAD DATA local INFILE` hangs when connecting to MO with NLB but works when connecting to MO with the service name.
Hang with:
```
mysql -h freetier-01.cluster.dev.matrixone.tech -P6001 -u bafc07cf_1079_44b3_90e7_d3496a05afd5:admin:accountadmin -p --local-infile
```
Work with:
```
mysql -h default-cn.freetier-01 -P6001 -u bafc07cf_1079_44b3_90e7_d3496a05afd5:admin:accountadmin -p --local-infile
```

**Comment by DanielZhangQD** [comment]
> LOAD DATA local INFILE '/ex_table_gzip' INTO TABLE t1;

This is caused by the stale version of proxy, after upgrading the proxy to the same version of the MO cluster, it works.
