### ISSUE TITLE
[Bug]: Many UT of lockservice failed: `TestLockWithBindIsStable``TestMultipleRowLocks``TestMultipleRangeLocks`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9583]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/actions/runs/5032226509/jobs/9025756523?pr=9572

<img width="697" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/99bac2b4-3a01-410a-b7a0-bfa70a9cf34b">
<img width="711" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/251744d7-85df-4e92-bc53-f64a1e5b2eaf">
<img width="984" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/36c3df57-434e-4c2e-b8c5-8ecd8893b7f1">

**Comment by zhangxu19830126** [comment]
TestLockWithBindIsStable fixed.

**Comment by zhangxu19830126** [comment]
剩余两个，还没有去分析

**Comment by zhangxu19830126** [comment]
maybe fixed.
