### ISSUE TITLE
[Bug]: bvt case failed with "table not exists"

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#9588]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1000" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/445cc246-d7a9-4f17-923f-4692b1d33a50">

https://github.com/matrixorigin/matrixone/actions/runs/5033217657/jobs/9027315793?pr=9465

### Expected Behavior

bvt case should pass.

**Comment by sukki37** [comment]
repro: https://github.com/matrixorigin/matrixone/actions/runs/5036172189/jobs/9032143903?pr=9572

**Comment by YANGGMM** [comment]
<img width="1258" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/00674e88-1be0-4e45-97ae-9f76a8dddc0d">

**Comment by YANGGMM** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/5036475007/jobs/9032647622?pr=9574

**Comment by YANGGMM** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/26563383/fdd82dcf-65ff-4ed4-a02b-10f101a2f6a1)

**Comment by YANGGMM** [comment]
<img width="698" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/8f9d0f09-2feb-4627-b285-32063226f48e">

**Comment by LeftHandCold** [comment]
<img width="1894" alt="image" src="https://github.com/matrixorigin/matrixone/assets/14086886/a9e4676d-8090-4abe-a53d-709ae325e889">
It looks like there is an exception in dbname, so there is an EOB error

**Comment by YANGGMM** [comment]
working on it

**Comment by YANGGMM** [comment]
<img width="956" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/b7ee3833-ebd9-49a9-9893-3334b19eaaa7">

**Comment by YANGGMM** [comment]
<img width="943" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/630b979a-48ee-486f-8159-946ecd02cbc4">

**Comment by YANGGMM** [comment]
<img width="1413" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/362e857d-7c5e-4c61-9d11-6123e6082f97">

**Comment by YANGGMM** [comment]
still in working

**Comment by YANGGMM** [comment]
still in working

**Comment by w-zr** [comment]
![image](https://github.com/matrixorigin/matrixone/assets/28624654/c27c797c-4652-4fb1-8a1d-fe094740c33e)
after https://github.com/matrixorigin/matrixone/pull/9641 merged, this bvt test may fail. need run many times.

**Comment by YANGGMM** [comment]
have fixd after https://github.com/matrixorigin/matrixone/pull/9598

**Comment by volgariver6** [comment]
@heni02 please help to test.

**Comment by aressu1985** [comment]
@heni02 pls test this again

**Comment by heni02** [comment]
Still don't know the cause of the problem，tomorrow confirm

**Comment by heni02** [comment]
Occasional occurrence of the problem, which has not been reproduced in the past 3 days in regression
In the future, we need to try to reproduce the scenario case
closed first
