### ISSUE TITLE
[Bug]:  CN panic when run the "delete from t where a = 1"

### ISSUE THREAD

**Issue by triump2020** [matrixorigin/matrixone#9602]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

   CN panic when run the below sql:
       
![1684681927061](https://github.com/matrixorigin/matrixone/assets/63033222/9665d705-e984-4d13-a83b-e20ec05fc4d9)

**Comment by JackTan25** [comment]
the compaction is modified by other people, please fix it back

**Comment by triump2020** [comment]
@aressu1985 pls test
