### ISSUE TITLE
[Bug]: CI encountered a problem of startup failure occasionally due to `panic: listen tcp4 0.0.0.0:39958: bind: address already in use`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9604]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/matrixorigin/matrixone/actions/runs/5040812401/jobs/9039928052
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mo init not completed
```

https://github.com/matrixorigin/matrixone/actions/runs/5040812401/jobs/9039928052

[mo-service.log](https://github.com/matrixorigin/matrixone/files/11526242/mo-service.log)

**Comment by w-zr** [comment]
39958 is the port for ctl service in `launch-tae-multi-CN-tae-DN`. Is there another service using this port?

**Comment by sukki37** [comment]
This issue hasn't been reproduced for a long time. I'll close it for now. If it reproduces, please feel free to reopen or comment.
