### ISSUE TITLE
[Bug]: All ddl operations and auto incrementing columns, sequences should be executed in sql instead

### ISSUE THREAD

**Issue by nnsgmsone** [matrixorigin/matrixone#9607]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

All of these operations are currently accomplished by writing directly to workspace, and they include the following operations:

1. create database 
2. drop database
3. create table
4. drop table
5. alter table
6. auto increment
7. sequenct
8.  etc...

Because after 0.8 dn will not be dealing with primary key constraints and pessimistic transactions in the case of not doing conflict detection, if the above operation does not use sql or internal manual processing constraints and locking, then the correctness will not be guaranteed.

**Comment by nnsgmsone** [comment]
thank you @ouyuanning

**Comment by ouyuanning** [comment]
PR is reviewing
