### ISSUE TITLE
[Bug]: tpmC decrease very very seriously in daily regression on commit:6f7a7f0

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9608]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):6f7a7f0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

TPCC test case is: 10 warehuouse  10 terminals and run 10 minutes

The last commit is :d9e192b
and the tpmC is **444.6**
<img width="640" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ba522d1c-32af-436a-9998-484e6aa3ace4">

and for the commit:6f7a7f0
the tpmC is **32.55**
<img width="640" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/3f74ee67-991b-496c-9d42-bfc95c386331">

the cpu ,mem, goroutine profile for commit:6f7a7f0 is : 
[6f7a7f0.tar.gz](https://github.com/matrixorigin/matrixone/files/11526971/6f7a7f0.tar.gz)

the cpu ,mem, goroutine profile for commit:d9e192b is : 
[d9e192b.tar.gz](https://github.com/matrixorigin/matrixone/files/11526975/d9e192b.tar.gz)

### Expected Behavior

The tpmC should not change for two commit.

### Steps to Reproduce

```Markdown
just run tpcc 10 warehouse 10 terminals test
```

**Comment by fengttt** [comment]
@m-schen please take a first look at this.  esp, if it is related to subscribe

**Comment by m-schen** [comment]
revert的pr已经提交 可以复测一下。

**Comment by zengyan1** [comment]
96c7647f683a34f91290db2accfd68a2d8ae084e tpmTotal = 1272, tpmC = 364 (revert commit)
fe57388fe1acc8dc6c21905ffa676fdc9a7e2182 tpmTotal = 407, tpmC = 128 (last commit before revert)

**Comment by zengyan1** [comment]
129服务器，10仓测试结果：
96c7647f683a34f91290db2accfd68a2d8ae084e tpmTotal = 1291, tpmC = 509

**Comment by aressu1985** [comment]
fixed
