### ISSUE TITLE
[Bug]: last_query_id() func report invalid input: index out of range: -1 on distributed mode(2*cn)

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9614]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b5d86d6
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

mysql> select last_query_id();
ERROR 20301 (HY000): invalid input: index out of range: -1
mysql> select last_query_id();
ERROR 20301 (HY000): invalid input: index out of range: -1
mysql> select last_query_id();
ERROR 20301 (HY000): invalid input: index out of range: -1
mysql> select last_query_id();
ERROR 20301 (HY000): invalid input: index out of range: -1
mysql> select last_query_id();
ERROR 20301 (HY000): invalid input: index out of range: -1
mysql> select last_query_id();
ERROR 20301 (HY000): invalid input: index out of range: -1
mysql> 

mo log:
[cn-0.log](https://github.com/matrixorigin/matrixone/files/11528427/cn-0.log)

### Expected Behavior

this func should be executed successfully.

### Steps to Reproduce

```Markdown
1.run a distributed mo cluster with 2*cn
2.run select last_query_id();
```

**Comment by daviszhen** [comment]
日志中发现。
每次报错前都可能要出pipeline的报错。
先要复现。

```
{"level":"ERROR","time":"2023/05/22 07:45:53.443317 +0000","caller":"colexec/receiver_operator.go:93","msg":"children pipeline closed unexpectedly","stacktrace":"github.com/matrixorigin/matrixone/pkg/sql/colexec.(*ReceiverOperator).ReceiveFromAllRegs\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/receiver_operator.go:93\ngithub.com/matrixorigin/matrixone/pkg/sql/colexec/merge.Call\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/merge/merge.go:41\ngithub.com/matrixorigin/matrixone/pkg/vm.Run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61\ngithub.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:151\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:121\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:168\ngithub.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run.func1\n\t/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:260"}
```

![image](https://github.com/matrixorigin/matrixone/assets/60595215/e95c193d-7a52-47a2-b352-f71dde94eefd)

**Comment by daviszhen** [comment]
还没看

**Comment by aressu1985** [comment]
fixed
