### ISSUE TITLE
[Bug]: fix nil panic 

### ISSUE THREAD

**Issue by JackTan25** [matrixorigin/matrixone#9616]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table if exists index04;
create table index04(col1 int, col2 char, col3 varchar(10),primary key(col1,col2));
show index from index04;
alter table index04 add index(col1);
alter table index04 alter index col1 invisible;
show index from index04;
alter table index04 alter index col1 visible;
show index from index04;
drop table index04;

the log will get nil panic in pkg/vm/engine/disttae/txn_table.go:compaction()

### Expected Behavior

drop table if exists index04;
create table index04(col1 int, col2 char, col3 varchar(10),primary key(col1,col2));
show index from index04;
alter table index04 add index(col1);
alter table index04 alter index col1 invisible;
show index from index04;
alter table index04 alter index col1 visible;
show index from index04;
drop table index04;

no panic bug

### Additional information

the reason is below:
drop table index04; is not finished, but the transaction is committed. strange!!!

**Comment by nnsgmsone** [comment]
thank you

**Comment by m-schen** [comment]
no fix today.

**Comment by fengttt** [comment]
@m-schen please take a look at #9617       All I want is to add this to bvt test.

**Comment by m-schen** [comment]
我来基于这个pr试试看。
