### ISSUE TITLE
[Bug]: SHOW ACCOUNTS error: ERROR 20405 (HY000): file "an-s3-file" is not found

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#9623]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): https://github.com/matrixorigin/matrixone/commit/6f7a7f02a27c9157d64893eee790ead3d4c5e7ae
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
mysql> show accounts;
ERROR 20405 (HY000): file freetier-01-POaJ/data/b639d196-f7f1-11ed-bdd9-6ed85eed1c35_00005 is not found

mysql> select * from mo_catalog.mo_account;
ERROR 20405 (HY000): file freetier-01-POaJ/data/b639d196-f7f1-11ed-bdd9-6ed85eed1c35_00005 is not found
```

### Expected Behavior

`SHOW ACCOUNTS` should succeed.

### Steps to Reproduce

Cannot reproduce this in a newly created cluster.

The existing cluster that has this problem can be accessed via `mysql -h freetier-01.cluster.dev.matrixone.tech -P 6001 -u dump -p`

Ask @aylei in person for the password.

**Comment by sukki37** [comment]
@aylei @daviszhen  Any updates on this issue? It's been a while since the last comment.

**Comment by aylei** [comment]
Not reproduced anymore. Closing.
