### ISSUE TITLE
[Bug]: alter table adds constraints shows incorrect.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9637]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
6abced61cd650215f52d97d93718d7cd01194118
sudo ./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml 2>&1 | tee wl.txt
mysql -h 127.0.0.1 -P 6001 -udump -p111
```

### Actual Behavior

![企业微信截图_16848305757715](https://github.com/matrixorigin/matrixone/assets/108530700/10401331-2b28-4384-bbdf-a5542ca99426)

### Expected Behavior

Show the correct sql.
![image](https://github.com/matrixorigin/matrixone/assets/108530700/8c71edf8-3637-43f7-9d08-eb94da6d798f)

### Steps to Reproduce

```Markdown
drop table if exists test01;
create table test01(a int);
alter table test01 add column col1 int unique key;
show create table test01;
```

**Comment by daviszhen** [comment]
@qingxinhome 跟alter table有关。

**Comment by qingxinhome** [comment]
目前，add column同时不支持对其添加唯一索引约束，建议把add column和add unique index分开执行，如：
mysql> create table test01(a int);
mysql> alter table test01 add column col1 int;
mysql> alter table test01 add unique key(col1);
mysql> show create table test01;

**Comment by qingxinhome** [comment]
The issue has been resolved, please verify and test。 @daviszhen @Ariznawlll @sukki37

**Comment by Ariznawlll** [comment]
<img width="1117" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/a5ce80e8-8712-4a9a-b538-8a70f8a000fe">

Verified!
