### ISSUE TITLE
[Bug]: abnormal CPU usage of DN when cluster is idle

### ISSUE THREAD

**Issue by aylei** [matrixorigin/matrixone#9640]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-2eeaf6fb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

DN consumes 100% CPU when the cluster is idle:

<img width="1865" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18556593/d8fc1e81-e88f-4b09-aadf-046061b59b92">

Profile:

<img width="1380" alt="WeChatWorkScreenshot_f8ee7b80-6354-46ca-a912-ac5ffc958a12" src="https://github.com/matrixorigin/matrixone/assets/18556593/fdaf7a5c-d254-4c2e-9184-ca8dd8c26465">

[profile.txt](https://github.com/matrixorigin/matrixone/files/11542232/profile.txt)

### Expected Behavior

DN should not consume that much CPU

**Comment by volgariver6** [comment]
fixed by #10536

**Comment by aylei** [comment]
deploy the latest version and observe

**Comment by aylei** [comment]
not observed anymore, closing
