### ISSUE TITLE
[Bug]: the NewStream method of RPC shouldn't get an closed tcp

### ISSUE THREAD

**Issue by m-schen** [matrixorigin/matrixone#9644]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 87c60a95eaeafcbc7551007e8cce33dea8c4e1c8
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/compile/scope.go#L686

the code here may get a closed tcp link when we are continuously executing queries that require using  rpc stream if we closed the tcp once we finished our stream.

the main branch cannot repro this bug because we did not correctly close the TCP link.

and if we want to repro this bug, should set the code here
https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/compile/scope.go#L694
 to be `true`.

**Comment by zhangxu19830126** [comment]
retry if backend closed encountered

**Comment by zhangxu19830126** [comment]
fixed
