### ISSUE TITLE
[Bug]: `internal error: an error has occurred about table subscription, please try again`

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#9654]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-6a65b65c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Get the following error with the query:
```
"Error 20101 (HY000): internal error: an error has occurred about table subscription, please try again.","elapsed":"32.718739416s","rows":-1,"sql":"SELECT sum(value) FROM `mo_cloud`.`storage_hour` WHERE collecttime >= '2023-05-24 01:00:00' AND collecttime < '2023-05-24 15:32:47' AND account = '15796f6f_bd25_4ef2_8e2f_26d76c61ab37'"
```

### Expected Behavior

Query succeeds

### Steps to Reproduce

```Markdown
NA
```

### Additional information

Refer to https://github.com/matrixorigin/MO-Cloud/issues/780

**Comment by m-schen** [comment]
修改了部分代码，正在环境上验证。没问题后会提pr。

**Comment by m-schen** [comment]
等9667解决后再验证一下该问题。目前原因不是很明朗。

**Comment by m-schen** [comment]
@DanielZhangQD 可以基于最新的main验证一下该问题。预计已经解决了。

**Comment by DanielZhangQD** [comment]
升级到 nightly-65c0f0d8 这个版本后，到现在没有再出现这个问题

**Comment by nnsgmsone** [comment]
Seems to have reproduced:  https://github.com/matrixorigin/matrixone/issues/9654

**Comment by m-schen** [comment]
这个错误是一定会出现的，只要在订阅一张表时发生了与dn的重连，都会报这个错误。

只能保证继续执行会成功。

**Comment by m-schen** [comment]
建议等 #9818 合并后多跑两天看看。

**Comment by heni02** [comment]
@m-schen yesterday eks regression appear again
job：https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5169993877/jobs/9314756843
image:  nightly-ae2c3fd 
![image](https://github.com/matrixorigin/matrixone/assets/113406637/d30de955-2ca3-44ca-bcef-62575e71ab93)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/cd5c3bce-6943-4818-9627-9d11c72e19c4)

**Comment by DanielZhangQD** [comment]
待升级 MO 验证

**Comment by DanielZhangQD** [comment]
待 MO 升级后验证

**Comment by DanielZhangQD** [comment]
Refer to the procedure in https://github.com/matrixorigin/matrixone/issues/9677#issuecomment-1583926763, this issue does not occur during the verification.
