### ISSUE TITLE
[Enhancement]: Rewrite COUNT/MIN/MAX with metadata_scan

### ISSUE THREAD

**Issue by aunjgr** [matrixorigin/matrixone#9660]
### Is there an existing issue for enhancement?

- [X] I have checked the existing issues.

### What would you like to be added ?

Queries like
```sql
select count(*), count(col) from tbl
```
can be rewritten as
```sql
select sum(rows_count), sum(rows_count) - sum(null_count) from metadata_scan('db.tbl', 'col')
```
to get a speed-up in some order of magnitude.

After min/max is complete for #8342, min(col)/max(col) can also be rewritten.

**Comment by zengyan1** [comment]
与 #7263 重复
