### ISSUE TITLE
[Bug]: mo was hung during sysbench oltp update prepared test 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9667]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 961aa4ec3
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

during sysbench oltp update prepared test , the mo was hung and can not response the request.

<img width="1307" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/0dc5b29a-7bc3-4feb-93de-eee3b574eb17">

the mo log:
[mo-sysbench-hung.tar.gz](https://github.com/matrixorigin/matrixone/files/11560374/mo-sysbench-hung.tar.gz)

profile(cpu, mem, goroutine, trace):
[prof.tar.gz](https://github.com/matrixorigin/matrixone/files/11560379/prof.tar.gz)

### Expected Behavior

The mo should not be hung anytime

### Steps to Reproduce

```Markdown
It is occasionally
```

**Comment by daviszhen** [comment]
经过分析。卡住在txnclient取时间戳的位置。

![Screenshot from 2023-05-25 10-44-55](https://github.com/matrixorigin/matrixone/assets/60595215/5d2f031e-58dc-41a4-8e92-175af83fe128)

看这四个卡住的情况。

![Screenshot from 2023-05-25 10-46-50](https://github.com/matrixorigin/matrixone/assets/60595215/93b33e86-9348-4930-b405-16def753ebe2)
![Screenshot from 2023-05-25 10-47-06](https://github.com/matrixorigin/matrixone/assets/60595215/8847aaea-394a-4500-a007-ef5726e6c029)
![Screenshot from 2023-05-25 10-47-21](https://github.com/matrixorigin/matrixone/assets/60595215/35dc4ff4-8d4b-4f81-834f-667d4ccd3268)
![Screenshot from 2023-05-25 10-47-28](https://github.com/matrixorigin/matrixone/assets/60595215/839c7784-fca7-42a1-879b-e0bbb2f7fc78)

**Comment by daviszhen** [comment]
正常的登录验证过程如下。（也是上面的日志中）
1. check password succeeded 密码验证成功
2. handle handshake end 握手成功。
3. handle handshake response ok 将握手成功的消息给client。




![image](https://github.com/matrixorigin/matrixone/assets/60595215/17242f27-4026-4ed1-a5db-038382b4a3ff)

**Comment by cnutshell** [comment]
Maybe related with [PR 9669](https://github.com/matrixorigin/matrixone/pull/9669)

**Comment by cnutshell** [comment]
`2023/05/25 02:45:15.538561`, logtail 服务端发送 logtail response 时，morpc 报错发送超时，超时时间为 10秒；
之后，cn 侧未输出重连的日志，dn 侧未收到新的订阅请求

<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/2c09bb9b-8a6e-4f6c-b9ad-b269fe88b8a4">

**Comment by cnutshell** [comment]
> `2023/05/25 02:45:15.538561`, logtail 服务端发送 logtail response 时，morpc 报错发送超时，超时时间为 10秒； 之后，cn 侧未输出重连的日志，dn 侧未收到新的订阅请求

mo-service 运行日志（上面也有）：[mo-sysbench-hung.tar.gz](https://github.com/matrixorigin/matrixone/files/11560374/mo-sysbench-hung.tar.gz)

**Comment by cnutshell** [comment]
看下面 goroutine 堆栈，cn 通过 morpc stream 发送订阅请求的时候死锁，导致 `unusedTableGCTicker` 调用无法返回，[该调用中持有的锁](https://github.com/matrixorigin/matrixone/blob/961aa4ec3be688c799b54fde43636f32a8318c2b/pkg/vm/engine/disttae/logtailPushModel.go#L346) 无法释放，进而卡住其他使用该锁的 goroutine

<img width="1438" alt="WeChatWorkScreenshot_2e727a47-ed23-4d07-9b12-e76c094b47a9" src="https://github.com/matrixorigin/matrixone/assets/20291742/2737966c-8d3c-4d95-9a1f-7d51adb289b4">

**Comment by m-schen** [comment]
rpc目前为处理并行send上了锁，这个锁会导致receive 和 send强关联。以上pr修复了会并行使用的错误，后续pr将会去掉这个锁。

**Comment by cnutshell** [comment]
Maybe PR #9697 fix the bug of morpc stream read blocking write.

**Comment by aressu1985** [comment]
update a another hung info happened on eks daily regression.

<img width="1396" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/cd681604-31fc-4b35-9c49-a67f35cb1103">


profile
[cn0-10.0.97.78.zip](https://github.com/matrixorigin/matrixone/files/11580958/cn0-10.0.97.78.zip)
[cn1-10.0.103.105.zip](https://github.com/matrixorigin/matrixone/files/11580959/cn1-10.0.103.105.zip)

**Comment by m-schen** [comment]
取消订阅导致的死锁问题已修复，可以验证或者看看今天的daily测试情况。

**Comment by aressu1985** [comment]
update a another hung info happened on eks daily regression.
commit: 52fc64d
<img width="1312" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/ee51c0c9-4e2c-46c1-856f-2db29da444e6">

profile:

[10.0.120.213.zip](https://github.com/matrixorigin/matrixone/files/11589059/10.0.120.213.zip)
[10.0.123.54.zip](https://github.com/matrixorigin/matrixone/files/11589062/10.0.123.54.zip)

**Comment by cnutshell** [comment]
> update a another hung info happened on eks daily regression. commit: [52fc64d]
> 
> profile:
> 
> [10.0.120.213.zip](https://github.com/matrixorigin/matrixone/files/11589059/10.0.120.213.zip) [10.0.123.54.zip](https://github.com/matrixorigin/matrixone/files/11589062/10.0.123.54.zip)

Block on cn reconnection, fixed by @m-schen's PR #9725 
<img width="1185" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/3a198c35-0836-47e7-bcfd-4aa4c9d8f97e">

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
fixed
