### ISSUE TITLE
[Feature Request]: Some improvements to publish-subscribe

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/matrixone#9675]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Describe the feature you'd like

1、Support viewing the list of DBs that can be subscribed
2、Support viewing more subscribed information, like publish db name, subscription time
3、View the meta information of the subscription db

PRD：https://doc.weixin.qq.com/doc/w3_AZUAugYIAOc93Z4c7KWSrqufIarFk?scode=AJsA6gc3AA8TceTlvcAZUAugYIAOc
Example: https://doc.weixin.qq.com/doc/w3_AZ0AxAYGAPwMg4A9ZCeT62yNPqjug?scode=AJsA6gc3AA8jmIFrvbAZ0AxAYGAPw

**Comment by daviszhen** [comment]
一些问题：
1、Support viewing the list of DBs that can be subscribed
谁能看？任何一租户都能看另一个租户发布的db吗？任何一个租户看所有的发布的db？

2、Support viewing more subscribed information, like publish db name, subscription time
谁需要看？发起订阅的租户？还是管理员看？

3、View the meta information of the subscription db
谁需要看？meta information的具体内容？

**Comment by dengn** [comment]
> 一些问题： 1、Support viewing the list of DBs that can be subscribed 谁能看？任何一租户都能看另一个租户发布的db吗？任何一个租户看所有的发布的db？
> 
> 2、Support viewing more subscribed information, like publish db name, subscription time 谁需要看？发起订阅的租户？还是管理员看？
> 
> 3、View the meta information of the subscription db 谁需要看？meta information的具体内容？

same questions for doc side. another key thing:

- what kind of syntax will support all these operations?

**Comment by dengn** [comment]
> > 一些问题： 1、Support viewing the list of DBs that can be subscribed 谁能看？任何一租户都能看另一个租户发布的db吗？任何一个租户看所有的发布的db？
> > 2、Support viewing more subscribed information, like publish db name, subscription time 谁需要看？发起订阅的租户？还是管理员看？
> > 3、View the meta information of the subscription db 谁需要看？meta information的具体内容？
> 
> same questions for doc side. another key thing:
> 
> * what kind of syntax will support all these operations?

**Comment by domingozhang** [comment]
`SHOW PUBLISHED Databases;`
Show published databases accounts names, pulications names and source databases names, such as
ACCOUNT | PUBLICATION | DATABASE
-- | -- | --
sys | pub1 | db1
acc1 | pub2 | db1

`SHOW SUBSCRIPTIONS;`
Show all SUBSCRIPTION databases names, source databases names, created time and source accounts' names, such as
Name     | From_Account | From_DB | Created_time
-- | -- | -- | --
| db1      | account1     | db0     | 2023-05-01 00:00:00 |
| db2      | account2     | db00    | 2023-05-02 00:00:00 |

**Comment by daviszhen** [comment]
早期的设计方案。

https://github.com/matrixorigin/docs/blob/main/tech-notes/sql/design/account_level.md

**Comment by daviszhen** [comment]
@ck89119  1.2开发这个feature

**Comment by daviszhen** [comment]
细节线下讨论.

**Comment by daviszhen** [comment]
这个发布和订阅早期的设计。https://github.com/matrixorigin/docs/blob/main/design/mo/sql/20230313-mooleetzi-pub-and-sub.md

**Comment by daviszhen** [comment]
早期的prd文档。

https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUZ1xBszdwTJqoSDHOge?scode=AJsA6gc3AA8Gk1ewV7AAgAkgYHABU

https://doc.weixin.qq.com/doc/w3_ALQAjwY-ACUxC47XWcNQge9rQUjbC?scode=AJsA6gc3AA8boPp1K7AAgAkgYHABU

**Comment by Ariznawlll** [comment]
test done.

**Comment by LiSong0214** [comment]
@xiaoshuwei 麻烦在云平台开发时顺便验收一下功能

**Comment by xiaoshuwei** [comment]
in testing

**Comment by xiaoshuwei** [comment]
done
