### ISSUE TITLE
[Bug]: Queries are becoming very slow after running several hours

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#9677]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-961aa4ec
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Queries are becoming very slow after running for several hours, check the following logs for the same SQL:
```
{"level":"WARN","time":"2023/05/25 10:30:16.264210 +0800","caller":"instance/instance.go:154","msg":"trace","elapsed":"787.18425ms","rows":1,"sql":"select sum(cu) from mo_cloud.cu where account = 'be9a9b71_ac6c_4d0d_b464_6da251eeb8c9' and start_time >= '2023-05-01 00:00:00' and start_time < '2023-05-25 10:30:11'"}
{"level":"WARN","time":"2023/05/25 10:30:17.315283 +0800","caller":"instance/instance.go:154","msg":"trace","elapsed":"2.517704125s","rows":1,"sql":"select sum(cu) from mo_cloud.cu where account = '3b0d290d_ee8f_40bf_9c5f_e536d155b5c6' and start_time >= '2023-05-01 00:00:00' and start_time < '2023-05-25 10:30:11'"}
{"level":"WARN","time":"2023/05/25 10:30:19.377248 +0800","caller":"instance/instance.go:154","msg":"trace","elapsed":"3.070792541s","rows":1,"sql":"select sum(cu) from mo_cloud.cu where account = 'bd09c9b0_5631_4821_a8a9_fc37a45397bd' and start_time >= '2023-05-01 00:00:00' and start_time < '2023-05-25 10:30:12'"}
{"level":"WARN","time":"2023/05/25 10:48:44.909442 +0800","caller":"instance/instance.go:154","msg":"trace","elapsed":"5.667601625s","rows":1,"sql":"select sum(cu) from mo_cloud.cu where account = '60c7f261_aebc_47af_b48d_2d0b529470f0' and start_time >= '2023-05-01 00:00:00' and start_time < '2023-05-25 10:48:39'"}
```

### Expected Behavior

The query finishes in a short time.

### Steps to Reproduce

```Markdown
Run MO for several hours
```

### Additional information

CPU profile
[cpu.txt](https://github.com/matrixorigin/matrixone/files/11562414/cpu.txt)

**Comment by m-schen** [comment]
@volgariver6 正在定位该bug。与logservice和dn间的网络连接不稳定有关。

**Comment by aptend** [comment]
log [202305261548.tar.gz](https://github.com/matrixorigin/matrixone/files/11575853/202305261548.tar.gz)

```
{"level":"INFO","time":"2023/05/26 06:25:43.747655 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:387","msg":"write loop stopped","remote":"default-log-2.default-log-headless.freetier-01.svc:32001","backend-id":"55a9dfb7-82e2-4af3-9618-7fdd2f77b920"}
{"level":"ERROR","time":"2023/05/26 06:25:43.767186 +0000","name":"rpc-client[hakeeper-client([connectToHAKeeper])]","caller":"morpc/client.go:349","msg":"gc inactive backends task stopped"}
{"level":"INFO","time":"2023/05/26 06:25:44.554594 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:710","msg":"start connect to remote","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04"}
{"level":"INFO","time":"2023/05/26 06:25:49.369150 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:714","msg":"connect to remote succeed","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04"}
{"level":"INFO","time":"2023/05/26 06:25:49.369407 +0000","caller":"logservice/hakeeper_client.go:494","msg":"isHAKeeper: false, err: context deadline exceeded"}
{"level":"INFO","time":"2023/05/26 06:25:50.156241 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:486","msg":"read loop started","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04"}
{"level":"INFO","time":"2023/05/26 06:25:50.156304 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:382","msg":"write loop started","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04"}
{"level":"ERROR","time":"2023/05/26 06:25:50.156349 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:511","msg":"read from backend failed","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04","error":"read tcp4 10.0.1.9:48894->10.0.1.28:32001: use of closed network connection"}
{"level":"ERROR","time":"2023/05/26 06:25:50.156390 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:516","msg":"read loop stopped","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04"}
{"level":"INFO","time":"2023/05/26 06:25:50.156404 +0000","name":"rpc-client[hakeeper-client([connectToHAKeeper])]","caller":"morpc/client.go:343","msg":"gc inactive backends task started"}
{"level":"ERROR","time":"2023/05/26 06:25:50.156426 +0000","name":"hakeeper-client-backend","caller":"v2@v2.0.3-0.20230520035916-bc1fed6f5e26/session.go:515","msg":"close conneciton failed","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04","session-id":0,"error":"close tcp4 10.0.1.9:48894->10.0.1.28:32001: use of closed network connection"}
{"level":"INFO","time":"2023/05/26 06:25:50.156451 +0000","name":"hakeeper-client-backend","caller":"morpc/backend.go:387","msg":"write loop stopped","remote":"default-log-0.default-log-headless.freetier-01.svc:32001","backend-id":"c3bae49d-a432-43a6-98aa-35742b538d04"}
{"level":"ERROR","time":"2023/05/26 06:25:50.176438 +0000","name":"rpc-client[hakeeper-client([connectToHAKeeper])]","caller":"morpc/client.go:349","msg":"gc inactive backends task stopped"}
```
One possible cause of this issue is that the connection between dn and logservice is repeatedly established and broken, and only when the connection is stable, dn can successfully commit and promptly push the latest timestamp to cn, allowing new transactions to be created

**Comment by cnutshell** [comment]
> Goroutines: [hang.txt](https://github.com/matrixorigin/matrixone/files/11562509/hang.txt)

从 goroutine 堆栈来看，cn 重连时会出现 goroutine 泄漏，1138 个因重连创建的 goroutine 中有 1109 个出现了分钟级的等待：
<img width="1014" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/b7f6e318-3d5a-4e95-a1c5-7f57ec3dd36b">

**Comment by m-schen** [comment]
我来检查一下协程泄漏的问题。

**Comment by volgariver6** [comment]
目前我这边没有什么进展，日志文件拿不下来，比较难分析。

如果是查询变的很慢的话，应该跟 dn 到logservice的链路不稳定没关系，查询是不会走到logservice的。

**Comment by LiSong0214** [comment]
https://github.com/matrixorigin/matrixone/issues/9474

**Comment by cnutshell** [comment]
基于 [mo-load](https://github.com/matrixorigin/mo-load) 运行 `simple_insert_10_100000`时, 对 sbtest.sbtest1 执行相同的 select，执行耗时会出现抖动

**Comment by aptend** [comment]
The `Exec.Build` phase takes up almost 95% of the time in slow queries. To verify if cn waited too much, a modified docker image that prints heartbeat ts was created. However, the environment has been running for more than 10 hours and there is no indication of slowing down.

**Comment by aptend** [comment]
> The `Exec.Build` phase takes up almost 95% of the time in slow queries. To verify if cn waited too much, a modified docker image that prints heartbeat ts was created. However, the environment has been running for more than 10 hours and there is no indication of slowing down.

Slow queries happened again today. Timestamps were pushed to cn in time. It is noticeable that `morpc.client.Ping` reported massive errors during compiling queries. More log about compiling has been added.

**Comment by aptend** [comment]
`"ping select sum(cu) from mo_cloud.cu where account = '18e30ed6_ffed_4118_8047_5f4b729c19fe' and start_time >= '2023-06-01 00:00:00' and start_time < '2023-06-02 06:44:40' end cost 42.161380594s"`

An experiment: spawn 2 new cn and kill them.  as the above log shows, the Ping can take 42s

related issue https://github.com/matrixorigin/MO-Cloud/issues/714
solution tracking issue #9822

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/9845 is merged

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/9876 is merged

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/9876 is merged

**Comment by DanielZhangQD** [comment]
待 MO 升级后验证

**Comment by DanielZhangQD** [comment]
待 MO 升级后验证

**Comment by DanielZhangQD** [comment]
Verified this bug and passed with the following procedure:
- Deploy MO with 1 CN with commit `nightly-8a01b00`
- Insert some data dumped from mo cloud into it
- Write a script to query the cu and storage in a loop infinitely
- Check the query time, all of them are finished in several hundred ms
- Scale out CN from 1 to 3, check the query time
- Scale in CN from 3 to 1, check the query time
- Repeat the above scaling operations
- Keep the script running for about 1 hour
