### ISSUE TITLE
[Feature Request]: forward read and write between cns

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#9704]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
forward read and write between cns. It is possible to forward read and write operations between cn to avoid some remote call overhead. For example, pessimistic locking, self-increasing column cache conflict problem.
```

### Describe the feature you'd like

Based on the information collected by clusterservice, such as which cn a particular table has been processed in and which cn holds the locktable for a particular table. Forward the operation to the corresponding cn.

**Comment by volgariver6** [comment]
feature is done. dup with #6953.

**Comment by aressu1985** [comment]
done
