### ISSUE TITLE
[Bug]: TPCC DELIVERY TXN of 10 warehouse report panic error:internal error: panic runtime error: index out of range [0] 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9717]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 52fc64d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

During TPCC Test on EKS, the txn delivery always report the following error:
2023-05-29 01:54:33 FATAL jTPCCTerminal:212 - [EXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20619, ErrorMessage : w-w conflict
2023-05-29 01:54:33 FATAL jTPCCTerminal:294 - [UNEXPECTED][DELIVERY_BG][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: index out of range [0] with length 0: 
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Write
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/txn_table.go:828
github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeblock.Call
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/colexec/mergeblock/mergeblock.go:92
github.com/matrixorigin/matrixone/pkg/vm.Run
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:151
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:127
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:182
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Run.func1
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:269
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted

the suspicious commit is as followings:
<img width="1312" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/9b7098d8-31e1-4158-b599-a1a0eb3e759d">

### Steps to Reproduce

```Markdown
1.run tpcc 10 warehouse 10 terminals benchmark test on eks with 2*cn
```

**Comment by m-schen** [comment]
9722 fix this bug.

**Comment by aressu1985** [comment]
fixed
