### ISSUE TITLE
[Bug]: drop/add partitions table column should report error

### ISSUE THREAD

**Issue by jianwan0214** [matrixorigin/matrixone#9719]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1532" alt="image" src="https://github.com/matrixorigin/matrixone/assets/32733096/e3b054a8-af4c-4a57-97a7-2f7db1eb1b1f">

**Comment by qingxinhome** [comment]
The issue has been resolved, please confirm @jianwan0214
