### ISSUE TITLE
[Bug]: sometimes node.Stats is incorrect in update statement

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#9724]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):13d4bbd657d4b9da0da624aded56108f6e7932de
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

when run tpcc with 10 warehouses & 50 terminals.  
sometimes node.Stats will very big then we will compile a pipeline to write s3.

**Comment by sukki37** [comment]
related to #9481
