### ISSUE TITLE
[Bug]: mo crash by internal error: mpool freed more bytes than alloc during sysbench oltp prepared insert 1000 threads test

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9732]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):84b8491ceaa0d54d6618cee207c4e8f158830fd0
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

The mo error log is:

2023/05/30 04:20:29.896302 +0800 INFO jobs/compactblk.go:287 [Done] {"txn-start-ts": "1685391629879731683-0", "operation": "[126116]compact", "compacted": "[A]BLK[<272670-272680-21-0>]", "created": "BLK<272670-272680-ebf9ee24-fe5d-11ed-b2ae-b07b25f8b524-25-0>", "duration": "16.475447ms"}
2023/05/30 04:20:29.896584 +0800 ERROR mpool/mpool.go:93 Mpool tae_default free bug, stats:      allocations : 1554941262
     frees : 1554975912
     alloc bytes : 6190391280116
     free bytes : 6190391302364
     current bytes : -22248
     high water mark : 222434616

github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPoolStats).RecordFree
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/mpool/mpool.go:93
github.com/matrixorigin/matrixone/pkg/common/mpool.(*MPool).Free
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/common/mpool/mpool.go:567
github.com/matrixorigin/matrixone/pkg/container/vector.(*Vector).Free
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/container/vector/vector.go:282
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vectorWrapper).releaseDownstream
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/containers/vector.go:257
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*vectorWrapper).Close
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/containers/vector.go:249
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/containers.(*Batch).Close
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/containers/batch.go:213
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tables/jobs.(*compactBlockTask).Execute
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tables/jobs/compactblk.go:293
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tasks/ops/ops.go:90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*ScheduledTxnTask).Execute
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/db/task.go:62
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/ops.(*Op).OnExec
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tasks/ops/ops.go:90
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks/worker.(*OpWorker).onOp
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tasks/worker/worker.go:207
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/tasks.(*poolHandler).doHandle.func1.1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/tasks/poolhandler.go:59
github.com/panjf2000/ants/v2.(*goWorker).run.func1
        /home/github/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.4/worker.go:67
2023/05/30 04:20:29.896693 +0800 ERROR mpool/mpool.go:94 error: internal error: mpool freed more bytes than alloc

[mo-sysbench-crash.tar.gz](https://github.com/matrixorigin/matrixone/files/11595192/mo-sysbench-crash.tar.gz)

### Expected Behavior

The mo should never crash.

### Steps to Reproduce

```Markdown
It is occassionally.
```

**Comment by m-schen** [comment]
@aressu1985 
这个是stand alone还是eks环境报出来的错误。

**Comment by aressu1985** [comment]
Standlone的

**Comment by m-schen** [comment]
thx mc @nnsgmsone

**Comment by nnsgmsone** [comment]
正在处理，发现存在double free的情况。具体情况还在分析

**Comment by nnsgmsone** [comment]
@XuPeng-SH 帮忙看一下，这个应该是tae内部的mpool的一些使用姿势有问题导致的，我后续会加一些检测函数让这个错误更快的暴露。

**Comment by LeftHandCold** [comment]
/start.sh -t 1000 -c cases/sysbench/simple_insert_10_100000_prepare 10分钟必现，由https://github.com/matrixorigin/matrixone/pull/9711 引入。https://github.com/matrixorigin/matrixone/pull/9812 合并后还是可以复现。

**Comment by nnsgmsone** [comment]
该问题本质是竞争调用引起的，可是mpool对于并发访问的保护并不是很严格，所以会导致alloc, free等统计信息出现不正确

**Comment by nnsgmsone** [comment]
fixed by #9846

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
最近1一周内稳定性测试没有再出现，先关闭
