### ISSUE TITLE
[Bug]: CN panic because of `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9751]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): bb1eedb4e426d35ffb20b2f46e14e3db6b1aafd5, d13b8dcfb32f1c9d55b6227d172fff2ecb74ae40
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1383" alt="企业微信截图_771fedf0-51cb-4023-a0b9-1f28ab3e19eb" src="https://github.com/matrixorigin/matrixone/assets/77312370/c9bf43ba-567b-476d-9df2-b1d9898e841a">

[mo-checkin-regression-tp-cn-1.9740.log](https://github.com/matrixorigin/matrixone/files/11600556/mo-checkin-regression-tp-cn-1.9740.log)
[mo-checkin-regression-tp-cn-1-9737.log](https://github.com/matrixorigin/matrixone/files/11600568/mo-checkin-regression-tp-cn-1-9737.log)

**Comment by zhangxu19830126** [comment]
fixed
