### ISSUE TITLE
[Bug]: DATA RACE and panic in TestCommitS3Blocks 

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixone#9754]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

[bug.tgz](https://github.com/matrixorigin/matrixone/files/11601303/bug.tgz)

**Comment by jiangxinmeng1** [comment]
fixed by #9880
