### ISSUE TITLE
[Bug]: mo_catalog database is not visible for the user account

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#9769]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-84b8491c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```
MySQL [(none)]> create account test1 admin_name 'admin' identified by 'admin';
[root@test /]# mysql -h default-cn.freetier-01 -P6001 -u test1:admin:accountadmin -padmin
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 8980
Server version: 8.0.30-MatrixOne-v0.7.0 MatrixOne

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| system             |
| system_metrics     |
| information_schema |
| mysql              |
+--------------------+
4 rows in set (0.11 sec)
```

### Expected Behavior

`mo_catalog` database is visible for the user account including its own data

### Steps to Reproduce

```Markdown
Check detail in `Actual Behavior`
```

**Comment by m-schen** [comment]
@daviszhen plz be the first person to check this issue.

**Comment by daviszhen** [comment]
`mo_catalog` is always in the CN.

**Comment by DanielZhangQD** [comment]
Sometimes it is visible, sometimes it's not:
```
MySQL [test]> show databases;
+--------------------+
| Database           |
+--------------------+
| mo_catalog         |
| test               |
| d1                 |
| system             |
| system_metrics     |
| information_schema |
| mysql              |
+--------------------+
7 rows in set (0.25 sec)
```
Exit and login again:
```
MySQL [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| test               |
| d1                 |
| system             |
| system_metrics     |
| information_schema |
| mysql              |
+--------------------+
6 rows in set (0.26 sec)
```

**Comment by nnsgmsone** [comment]
等出好后insert的问题后在处理这个问题

**Comment by nnsgmsone** [comment]
等出好后insert的问题后在处理这个问题

**Comment by jensenojs** [comment]
check third times and all visible, although i have no idea about "-h default-cn.freetier-01"
<img width="1801" alt="image" src="https://github.com/matrixorigin/matrixone/assets/56761542/22a0c790-2300-4544-83a2-3495e4d16be6">

**Comment by heni02** [comment]
@jensenojs not reproduce？ not found reason？

**Comment by DanielZhangQD** [comment]
Do not reproduce after upgrading to nightly-9de3c465

**Comment by DanielZhangQD** [comment]
Hit again with commit `nightly-9207b269`

**Comment by m-schen** [comment]
在修复pr上验证过，重连后可以查到该表了。

**Comment by m-schen** [comment]
pr已合并，可以进行验证。

**Comment by DanielZhangQD** [comment]
To be verified.

**Comment by DanielZhangQD** [comment]
Verified and passed with commit `[nightly-7ebfe11d](https://hub.docker.com/layers/matrixorigin/matrixone/nightly-7ebfe11d/images/sha256-61fcffe85311cd9f25744327fc45ff28224f9caa595aee1b2c136dc4151a417c?context=explore)`.
The procedure is as below:
Write a script to delete the CN and DN Pods continuously for about 1 hour, after that, connect to MO and check the result.
