### ISSUE TITLE
[Bug]: Load data time is almost the same using one CN vs three CNs.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#9785]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
on eks
version:temp-nightly-3fb4623
```

### Actual Behavior

![image](https://github.com/matrixorigin/matrixone/assets/108530700/8c7539c2-0401-4b27-b2e4-86bd37e6a16b)

### Steps to Reproduce

```Markdown
cd &github_workspace/mo-load-data
./load.sh -h ${{steps.get_mo_addr.outputs.mo_svc_ip}} -c cases/00_from_s3/ssb_100 -r -m -g
```

**Comment by Ariznawlll** [comment]
@ouyuanning There is no improvement in load data test in different CN，the test result are as follows:
1CN：3min
2CN：2.56min
3CN：2.93min
version：nightly-547ae62f

**Comment by ouyuanning** [comment]
先处理insert优化的部分

**Comment by ouyuanning** [comment]
先处理insert优化的部分

**Comment by ouyuanning** [comment]
先处理insert优化的部分

**Comment by ouyuanning** [comment]
先处理insert优化的部分

**Comment by ouyuanning** [comment]
先处理insert优化的部分

**Comment by ouyuanning** [comment]
改了一稿。待QA协助验证

**Comment by Ariznawlll** [comment]
1CN：2.94min， 3CN：2.79min
version: temp-nightly-1a3c427

**Comment by Ariznawlll** [comment]
version：auto-test-d9e40be
1CN：4.44min
![企业微信截图_16879211028233](https://github.com/matrixorigin/matrixone/assets/108530700/4047c0db-f51f-4f0c-939a-ca49f83d34aa)
3CN：2.56min
