### ISSUE TITLE
[LIKE] LIKE clause doesn't work in SHOW DATABASES

### ISSUE THREAD

**Issue by anitajjx** [matrixorigin/matrixone#979]
#### Can be reproduced?
Yes.

#### Steps:
show databases like 'abc%';
show databases where 1=0;

#### Expected behavior:
The output should match the filter condition given by the LIKE or WHERE clause.

#### Actual behavior:
mysql> show databases;
+----------+
| Database |
+----------+
| qadb1    |
+----------+
1 row in set (0.00 sec)

mysql> show databases like 'abc%';
+----------+
| Database |
+----------+
| qadb1    |
+----------+
1 row in set (0.00 sec)

mysql> show databases where 1=0;
+----------+
| Database |
+----------+
| qadb1    |
+----------+
1 row in set (0.01 sec)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):commit 3f29ff23d88b8455070211f2090bbaeadf202b3f
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by m-schen** [comment]
support LIKE now
where will support at next pull request

**Comment by m-schen** [comment]
`where` can not support this version 0.2
we need a system table stores metadata, so we can use function `buildWhere` that.
we can only make a fake relation structure to support where now,  but it does not make sense.

please only test LIKE operator and add case to BVT at v0.2.

**Comment by m-schen** [comment]
like operator can also used at SELECT sql.
For example:
select * from tbl where '123' like '_%'
select * from tbl where column1 like column2
select * from tbl where column1 like 'example'
select * from tbl where 'example' like column1

NOT LIKE doesn't support now.

**Comment by lignay** [comment]
"show databases like 'abc%'" works well， but "show databases where 1=0" will not support in v0.2.0.
