### ISSUE TITLE
[Bug]: dn crash 

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#9793]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-84b8491c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

A small MO cluster with 3*2c8g. 

dn crashed with some simple test. 

this is the crash log: 
[dn.error.log.202306011604.txt](https://github.com/matrixorigin/matrixone/files/11622695/dn.error.log.202306011604.txt)

**Comment by cnutshell** [comment]
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/fb95021a-2bb7-406b-b219-dd7f5cd865a2">

@matrix-meow please classify and reassign this issue.

**Comment by w-zr** [comment]
fixed by https://github.com/matrixorigin/matrixone/commit/ec5f5768c3d078f48cd574e75832eb3f16d45cf2

**Comment by dengn** [comment]
not happening any more. closing.
