### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: update should not reported duplicate key error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9813]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):71e7151601635363e8c131484449abbfb3508715
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

update sql should execute succeed
<img width="955" alt="企业微信截图_a88302d4-2c73-4333-8ce4-ed3d3b240561" src="https://github.com/matrixorigin/matrixone/assets/113406637/ccb5fc51-36cb-4163-ad6c-51819b35e67b">

### Steps to Reproduce

```Markdown
drop table if exists test_11;
create table test_11 (c int primary key,d int);
Insert into test_11 values(1,1);
Insert into test_11 values(2,2);
set autocommit=0;
select * from test_11;
Insert into test_11 values(50,50);
select * from test_11;
-- @session:id=1{
set autocommit=0;
select * from test_11;
-- @wait:0:commit
Insert into test_11 values(50,50);
select * from test_11;
-- @session}
select * from test_11;

-- @session:id=1{
select * from test_11;
update test_11 set c = 100 where d = 50;
select * from test_11;
-- @session}
select * from test_11;
Insert into test_11 values(100,50);

commit;
```

**Comment by zhangxu19830126** [comment]
由于CN目前没有开启主键去重，执行update的时候，有2个50的记录，然后就会出现这个问题。打开CN的主键去重就没有这个问题了。这个事务在commit的时候，也会失败。

**Comment by ouyuanning** [comment]
待CN去重打开后验证

**Comment by heni02** [comment]
confirm, closed
commit id:767517b81caf4a05b3c0885eaadb52d30700ce94
![image](https://github.com/matrixorigin/matrixone/assets/113406637/a6986082-f963-4372-9b6c-f004439556a5)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6dd1aa70-3691-49c6-a427-addd51d188c2)
