### ISSUE TITLE
[Bug]: foreign key doesn't appear in desc

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#9816]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

```sql
mysql> CREATE TABLE c1 (ca INT, cb INT);
Query OK, 0 rows affected (0.02 sec)

mysql> ALTER TABLE c1 ADD CONSTRAINT ffa FOREIGN KEY (ca) REFERENCES f1(fa);
Query OK, 0 rows affected (0.01 sec)

mysql> show create table c1;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                         |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| c1    | CREATE TABLE `c1` (
`ca` INT DEFAULT NULL,
`cb` INT DEFAULT NULL,
CONSTRAINT `ffa` FOREIGN KEY (`ca`) REFERENCES `f1` (`fa`) ON DELETE RESTRICT ON UPDATE RESTRICT
) |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> desc c1;
+-------+---------+------+------+---------+-------+---------+
| Field | Type    | Null | Key  | Default | Extra | Comment |
+-------+---------+------+------+---------+-------+---------+
| ca    | INT(32) | YES  |      | NULL    |       |         |
| cb    | INT(32) | YES  |      | NULL    |       |         |
+-------+---------+------+------+---------+-------+---------+
2 rows in set (0.01 sec)

```
Normally this desc should appear a 'MUL' in key.

![image](https://github.com/matrixorigin/matrixone/assets/4965857/c37d665b-4186-41e5-ba4c-7640ce3dba80)

**Comment by m-schen** [comment]
我不确定desc具体是谁负责开发的。需要 @daviszhen 进行分配。

**Comment by YANGGMM** [comment]
have fixed it

**Comment by dengn** [comment]
mysql> CREATE TABLE tb_dept1(
    ->     id INT(11) PRIMARY KEY,
    ->     name VARCHAR(22) NOT NULL,
    ->     location VARCHAR(50)
    ->     );
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE tb_emp6
    ->     (
    ->     id INT(11) PRIMARY KEY,
    ->     name VARCHAR(25),
    ->     deptId INT(11),
    ->     salary FLOAT,
    ->     CONSTRAINT fk_emp_dept1
    ->     FOREIGN KEY(deptId) REFERENCES tb_dept1(id)
    ->     );
Query OK, 0 rows affected (0.01 sec)

mysql> DESC tb_emp6;
+--------+-------------+------+------+---------+-------+---------+
| Field  | Type        | Null | Key  | Default | Extra | Comment |
+--------+-------------+------+------+---------+-------+---------+
| id     | INT(32)     | NO   | PRI  | NULL    |       |         |
| name   | VARCHAR(25) | YES  |      | NULL    |       |         |
| deptid | INT(32)     | YES  |      | NULL    |       |         |
| salary | FLOAT(0)    | YES  | MUL  | NULL    |       |         |
+--------+-------------+------+------+---------+-------+---------+
4 rows in set (0.01 sec)

fixed.
