### ISSUE TITLE
[Bug]: 统计表数据时，SQL报错table meta is nil

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#9817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:Apple M1 Pro,16 GB,Macintosh HD
- OS type: MACOS
- Others:
```

### Actual Behavior

1. create database test;
2. use test;
3. create table t1(
                   clo1 tinyint,
                   clo2 smallint,
                   clo3 int,
                   clo4 bigint,
                   clo5 tinyint unsigned,
                   clo6 smallint unsigned,
                   clo7 int unsigned,
                   clo8 bigint unsigned,
                   col9 float,
                   col10 double,
                   col11 varchar(255),
                   col12 Date,
                   col13 DateTime,
                   col14 timestamp,
                   col15 bool,
                   col16 decimal(5,2),
                   col17 text,
                   col18 json,
                   col19 blob,
                   col20 binary(255),
                   col21 varbinary(255)
);
4. insert into t1 (clo1, clo2, clo3, clo4, clo5, clo6, clo7, clo8, col9, col10, col11, col12, col13, col14, col15, col16, col17, col18, col19, col20, col21) VALUES
                                                                                                                                                              (1, 100, 1000, 10000, 1, 100, 1000, 10000, 1.23, 1.2345, 'Text 1', '2023-05-29', '2023-05-29 12:34:56', '2023-05-29 12:34:56', TRUE, 1.23, 'Text 1', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (2, 200, 2000, 20000, 2, 200, 2000, 20000, 2.34, 2.3456, 'Text 2', '2023-05-30', '2023-05-30 12:34:56', '2023-05-30 12:34:56', FALSE, 2.34, 'Text 2', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (3, 300, 3000, 30000, 3, 300, 3000, 30000, 3.45, 3.4567, 'Text 3', '2023-05-31', '2023-05-31 12:34:56', '2023-05-31 12:34:56', TRUE, 3.45, 'Text 3', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (4, 400, 4000, 40000, 4, 400, 4000, 40000, 4.56, 4.5678, 'Text 4', '2023-06-01', '2023-06-01 12:34:56', '2023-06-01 12:34:56', FALSE, 4.56, 'Text 4', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (5, 500, 5000, 50000, 5, 500, 5000, 50000, 5.67, 5.6789, 'Text 5', '2023-06-02', '2023-06-02 12:34:56', '2023-06-02 12:34:56', TRUE, 5.67, 'Text 5', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
                                                                                                                                                              (6, 600, 6000, 60000, 6, 600, 6000, 60000, 6.78, 6.7890, 'Text 6', '2023-06-03', '2023-06-03 12:34:56', '2023-06-03 12:34:56', FALSE, 6.78, 'Text 6', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data');
5. /* cloud_nonuser */ SELECT attname AS name,
                           mo_show_visible_bin(atttyp,3) AS data_type,
                           replace(mo_table_col_max(att_database,att_relname,attname),'\0', '') AS `maximum`,
                           mo_table_col_min(att_database,att_relname,attname) as minimum
                    from mo_catalog.mo_columns
                    where att_database='test' and att_relname='t1' and attname NOT IN  ('__mo_rowid', '__mo_cpkey_col', '__mo_fake_pk_col')
                    ORDER BY attnum;
Note: the Step 5 should be executing in short time. and after a few minutes, it can be Right Way.

### Expected Behavior

it will be return the statistic info.

### Steps to Reproduce

```Markdown
Check detail in `Actual Behavior`
```

### Additional information

the mo_columns table's data will return normally, but when use the function `mo_table_col_max` and `mo_table_col_min` . it  will return the error.
Bug Error:[HY000][20301] invalid input: table meta is nil

**Comment by m-schen** [comment]
这个问题我先来看看是不是函数导致的问题。

**Comment by m-schen** [comment]
貌似和函数本身没什么关系，函数的实现部分会去读meta，导致跑出了这个错误。
还需要看看。

**Comment by m-schen** [comment]
最新的main已经修复了该问题，比较大概率是由于原先的main存在丢失logtail的问题导致的。目前可以查出结果。

相关pr可能是 #9906 

```
| name  | data_type             | maximum                        | minimum                        |
+-------+-----------------------+--------------------------------+--------------------------------+
| clo1  | TINYINT(8)            | 6                              | 1                              |
| clo2  | SMALLINT(16)          | 600                            | 100                            |
| clo3  | INT(32)               | 6000                           | 1000                           |
| clo4  | BIGINT(64)            | 60000                          | 10000                          |
| clo5  | TINYINT UNSIGNED(8)   | 6                              | 1                              |
| clo6  | SMALLINT UNSIGNED(16) | 600                            | 100                            |
| clo7  | INT UNSIGNED(32)      | 6000                           | 1000                           |
| clo8  | BIGINT UNSIGNED(64)   | 60000                          | 10000                          |
| col9  | FLOAT(0)              | 6.78                           | 1.23                           |
| col10 | DOUBLE(0)             | 6.789                          | 1.2345                         |
| col11 | VARCHAR(255)          | Text 6                         | Text 1                         |
| col12 | DATE(0)               | 2023-06-03                     | 2023-05-29                     |
| col13 | DATETIME(0)           | 2023-06-03 12:34:56            | 2023-05-29 12:34:56            |
| col14 | TIMESTAMP(0)          | 2023-06-03 04:34:56.000000 UTC | 2023-05-29 04:34:56.000000 UTC |
| col15 | BOOL(0)               | false                          | false                          |
| col16 | DECIMAL64(5)          | 678                            | 123                            |
| col17 | TEXT(0)               | Text 6                         | Text 1                         |
| col18 | JSON(0)               | 
                                  keyvalue               |           
                                                                        keyvalue  |
| col19 | BLOB(0)               | Blob data                      | Blob data                      |
| col20 | BINARY(255)           | Binary data                   | Binary data                    |
| col21 | VARBINARY(255)        | Varbinary data                 | Varbinary data                 |
+-------+-----------------------+--------------------------------+--------------------------------+
```

**Comment by xiaoshuwei** [comment]
## 最新测试结果：
```

mysql> create database test;
Query OK, 1 row affected (0.07 sec)

mysql> use test;
Database changed
mysql> create table t1(
    -> clo1 tinyint,
    -> clo2 smallint,
    -> clo3 int,
    -> clo4 bigint,
    -> clo5 tinyint unsigned,
    -> clo6 smallint unsigned,
    -> clo7 int unsigned,
    -> clo8 bigint unsigned,
    -> col9 float,
    -> col10 double,
    -> col11 varchar(255),
    -> col12 Date,
    -> col13 DateTime,
    -> col14 timestamp,
    -> col15 bool,
    -> col16 decimal(5,2),
    -> col17 text,
    -> col18 json,
    -> col19 blob,
    -> col20 binary(255),
    -> col21 varbinary(255)
    -> );
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t1 (clo1, clo2, clo3, clo4, clo5, clo6, clo7, clo8, col9, col10, col11, col12, col13, col14, col15, col16, col17, col18, col19, col20, col21) VALUES
    -> (1, 100, 1000, 10000, 1, 100, 1000, 10000, 1.23, 1.2345, 'Text 1', '2023-05-29', '2023-05-29 12:34:56', '2023-05-29 12:34:56', TRUE, 1.23, 'Text 1', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
    -> (2, 200, 2000, 20000, 2, 200, 2000, 20000, 2.34, 2.3456, 'Text 2', '2023-05-30', '2023-05-30 12:34:56', '2023-05-30 12:34:56', FALSE, 2.34, 'Text 2', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
    -> (3, 300, 3000, 30000, 3, 300, 3000, 30000, 3.45, 3.4567, 'Text 3', '2023-05-31', '2023-05-31 12:34:56', '2023-05-31 12:34:56', TRUE, 3.45, 'Text 3', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
    -> (4, 400, 4000, 40000, 4, 400, 4000, 40000, 4.56, 4.5678, 'Text 4', '2023-06-01', '2023-06-01 12:34:56', '2023-06-01 12:34:56', FALSE, 4.56, 'Text 4', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
    -> (5, 500, 5000, 50000, 5, 500, 5000, 50000, 5.67, 5.6789, 'Text 5', '2023-06-02', '2023-06-02 12:34:56', '2023-06-02 12:34:56', TRUE, 5.67, 'Text 5', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data'),
    -> (6, 600, 6000, 60000, 6, 600, 6000, 60000, 6.78, 6.7890, 'Text 6', '2023-06-03', '2023-06-03 12:34:56', '2023-06-03 12:34:56', FALSE, 6.78, 'Text 6', '{"key": "value"}', 'Blob data', 'Binary data', 'Varbinary data');
Query OK, 6 rows affected (0.04 sec)

mysql> 
mysql> /* cloud_nonuser */ SELECT attname AS name,
    -> mo_show_visible_bin(atttyp,3) AS data_type,
    -> replace(mo_table_col_max(att_database,att_relname,attname),'\0', '') AS maximum,
    -> mo_table_col_min(att_database,att_relname,attname) as minimum
    -> from mo_catalog.mo_columns
    -> where att_database='test' and att_relname='t1' and attname NOT IN ('__mo_rowid', '__mo_cpkey_col', '__mo_fake_pk_col')
    -> ORDER BY attnum;
ERROR 20301 (HY000): invalid input: table meta is nil
```
仍然报这个错。

**Comment by m-schen** [comment]
今天没看这个。

**Comment by gouhongshen** [comment]
> 今天没看这个。

之前遇到这个错误，等待半分钟就能读到 meta 数据了。

**Comment by gouhongshen** [comment]
> 最新的main已经修复了该问题，比较大概率是由于原先的main存在丢失logtail的问题导致的。目前可以查出结果。
> 
> 相关pr可能是 #9906
> 
> @xiaoshuwei 可以验证一下该问题相关的用例。我尝试了`mo_table_col_max `和`mo_table_col_min`没有问题。
> 
> ```
> | name  | data_type             | maximum                        | minimum                        |
> +-------+-----------------------+--------------------------------+--------------------------------+
> | clo1  | TINYINT(8)            | 6                              | 1                              |
> | clo2  | SMALLINT(16)          | 600                            | 100                            |
> | clo3  | INT(32)               | 6000                           | 1000                           |
> | clo4  | BIGINT(64)            | 60000                          | 10000                          |
> | clo5  | TINYINT UNSIGNED(8)   | 6                              | 1                              |
> | clo6  | SMALLINT UNSIGNED(16) | 600                            | 100                            |
> | clo7  | INT UNSIGNED(32)      | 6000                           | 1000                           |
> | clo8  | BIGINT UNSIGNED(64)   | 60000                          | 10000                          |
> | col9  | FLOAT(0)              | 6.78                           | 1.23                           |
> | col10 | DOUBLE(0)             | 6.789                          | 1.2345                         |
> | col11 | VARCHAR(255)          | Text 6                         | Text 1                         |
> | col12 | DATE(0)               | 2023-06-03                     | 2023-05-29                     |
> | col13 | DATETIME(0)           | 2023-06-03 12:34:56            | 2023-05-29 12:34:56            |
> | col14 | TIMESTAMP(0)          | 2023-06-03 04:34:56.000000 UTC | 2023-05-29 04:34:56.000000 UTC |
> | col15 | BOOL(0)               | false                          | false                          |
> | col16 | DECIMAL64(5)          | 678                            | 123                            |
> | col17 | TEXT(0)               | Text 6                         | Text 1                         |
> | col18 | JSON(0)               | 
>                                   keyvalue               |           
>                                                                         keyvalue  |
> | col19 | BLOB(0)               | Blob data                      | Blob data                      |
> | col20 | BINARY(255)           | Binary data                   | Binary data                    |
> | col21 | VARBINARY(255)        | Varbinary data                 | Varbinary data                 |
> +-------+-----------------------+--------------------------------+--------------------------------+
> ```

之前遇到这个错误，等待半分钟就能读到 meta 数据了。

**Comment by m-schen** [comment]
应该不是数据同步的问题，数据同步应该更提早报出合理的错误。也有可能是之前初始化完成前查询没阻塞好的问题。
今日无进度。

**Comment by m-schen** [comment]
和我之前的定位有点区别，错误出现在了获取最大值和最小值处。
从relation结构中获取不到zonemap信息。
需要定位一下是数据同步问题，还是获取zonemap的方法写得有问题。

**Comment by m-schen** [comment]
这俩函数的实现不对，只考虑了zonemap。应该考虑max / min (zonemap, memory table)

**Comment by m-schen** [comment]
我不能肯定这个issue属不属于bug。
如果这俩函数的语义是获取table meta所统计的最大最小值的话，那么该函数目前的实现是满足需求的。发生该错误时，由于该表还没有落盘，不存在table meta信息，因此会返回错误不存在table meta。

但是这俩函数都是存在bug的，
如果在同一个事务中删除了最大值 / 最小值，或者在同一个事务中对表有增删改查，或者用同名列替换了该列，得到的结果都将是不准确的。

**Comment by m-schen** [comment]
今天需要确定一下是否是逻辑写得有问题，落盘后还没取到统计信息。

**Comment by domingozhang** [comment]
@xiaoshuwei 落盘问题已经排查之后，是否可以关闭
