### ISSUE TITLE
[Bug]: mo cloud hung

### ISSUE THREAD

**Issue by aptend** [matrixorigin/matrixone#9819]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 84b8491ce
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Can't connect to mo service. ERROR 1045 (28000): Access denied for user dump. SQL parser error: table "mo_account" does not exist

seems logtail receiving gorountine hung

goroutine 234 [select, 24 minutes]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailClient).Receive.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service/client.go:144 +0x7e
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailClient).Receive(0xc00ade9ca0?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service/client.go:163 +0x5b
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*logTailSubscriber).receiveResponse(0x2d4e990?)
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:607 +0x32
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*pushClient).receiveTableLogTailContinuously.func1()
        /go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtailPushModel.go:258 +0x2f3

**Comment by m-schen** [comment]
fixed.
