### ISSUE TITLE
[Bug]: AP queries should not ping CNs.

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/matrixone#9822]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

When CN processes an AP query, it will ping all other CNs.

### Expected Behavior

CN should fetch other CNs' info from hakeeper.

**Comment by m-schen** [comment]
需要集群信息更快地响应出某个cn的存活状态。虽然ping本身并不能解决什么问题。

**Comment by sukki37** [comment]
@w-zr @nnsgmsone Any updates on this issue? It's been a while since the last comment.
