### ISSUE TITLE
[Bug]: the return value of mo_table_rows doesn't equal the return of select count(*)

### ISSUE THREAD

**Issue by xiaoshuwei** [matrixorigin/matrixone#9825]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-84b8491c
- Hardware parameters:Apple M1 Pro,16 GB,Macintosh HD
- OS type: MacOS
- Others:
```

### Actual Behavior

 kubectl --kubeconfig=ali_dev -n freetier-01 port-forward svc/default-cn 6001:6001
1. login MO by the special account: mysql -h 127.0.0.1 -P 6001 -u 666e8cfb_6956_44a8_b821_d423a4705f71:admin -pAdmin123
2. Select mo_table_rows('mo_catalog', 'mo_database') AS `rows`; and return value is 67.
3. select count(*) from mo_catalog.mo_database; and return value is 7.

### Expected Behavior

the return value of mo_table_rows doesn't equal the return of select count(*)

### Steps to Reproduce

```Markdown
Check detail in `Actual Behavior`
```

### Additional information

account: 666e8cfb_6956_44a8_b821_d423a4705f71:admin
password: Admin123

**Comment by zhangxu19830126** [comment]
看上去是ddl操作表的时候，和mo_tables的操作不匹配。

**Comment by sukki37** [comment]
@dongdongyang33 Could you kindly look at this one?

**Comment by dongdongyang33** [comment]
i will check tomorrow

**Comment by fengttt** [comment]
Does mo_table_rows always promise accurate answer?   This is only used for stats/estimates, right?    If this is the case we can downgrade this one to s1.

**Comment by domingozhang** [comment]
mo_table_rows() means getting row numbers of all account. 
If you want to get current row number of account, use count(*) instead, please

**Comment by xiaoshuwei** [comment]
do we have a function to get sum of rows by account ?

**Comment by LiSong0214** [comment]
我们在手册中告知用户可以使用 MO_TABLE_ROWS({DATABASE_NAME},{TABLE_NAME}) 来获取表的总行数，然后在 account 中执行时又不是这个 account 的真实值，这就是 bug。不准确源自于两方面，一个是函数取得是元数据，同 count(*) 或许存在差异，另一个是没有按照 account 统计。试问，我们说租户间的数据是隔离的，但却可以在某一个租户内查到整个集群的用户数/表数/数据库数，这样真的 OK 吗？

**Comment by LiSong0214** [comment]
经沟通：
1、该函数属于内部函数，不对外，手册中也会下掉；
2、该函数在 mo_catalog 中的行为当前属于预期；

**Comment by aressu1985** [comment]
fixed
