### ISSUE TITLE
[Bug]: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#9827]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): b9283b37b4842f699db33b076d44d2520c9a02eb
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/18366608/2f2638ca-5550-43db-aa49-6b7490ad1ffc">

### Expected Behavior
no error

_No response_

**Comment by zhangxu19830126** [comment]
并发操作map

**Comment by daviszhen** [comment]
it was fixed.
