### ISSUE TITLE
[Subtask]: log insert should use prepared statement

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9833]
### Parent Issue

#8196

### Detail of Subtask

Use prepared statement.

First, it is know prepared statement is faster.

Second, people will fix tpcc batch insert, which uses prepared statement.   We want log insert simply work without any further complications such as non prepared statement leaking memory, slow, etc etc.    Those are bugs that must be fixed but should not delay/complicate this PR any more.

**Comment by gavinyue** [comment]
communicate with @ouyuanning on how to use this on prepared statements.   Better to have COM_STMT_SEND_LONG_DATA support to support the longer "insert into t values (???), (???)" string. 

But in the mean time, we will implement and test.

**Comment by gavinyue** [comment]
昨天已经在修改后的branch 测试，今天将修改insert的方法

**Comment by gavinyue** [comment]
https://github.com/ouyuanning/matrixone/pull/122

**Comment by fengttt** [comment]
Per discussion with @ouyuanning and @nnsgmsone , our impl of batch insert may not necessarily slower than prepare.
So if we use insert into ... values (row1), (row2), ...     this may not be an issue.

@gavinyue please consider downgrade or close.

**Comment by gavinyue** [comment]
> Per discussion with @ouyuanning and @nnsgmsone , our impl of batch insert may not necessarily slower than prepare. So if we use insert into ... values (row1), (row2), ... this may not be an issue.
> 
> @gavinyue please consider downgrade or close.

The implementation is already done and merged into @ouyuanning prepare improvement branch. Will test and compare to see which one to choose.  

Downgrade this to S0.

**Comment by fengttt** [comment]
#9955 

Maybe this is the right way.

**Comment by gavinyue** [comment]
Pending PR merge

**Comment by gavinyue** [comment]
Still wait for mochen's work

**Comment by gavinyue** [comment]
Should be done. Please close this. @fengttt
