### ISSUE TITLE
[Subtask]: Count number of log messages and warn/error if someone spitting out too many

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9835]
### Parent Issue

#8196

### Detail of Subtask

CN/DN should have a few metrics, that count how many log messages at DEBUG, INFO, ERROR+.   Report this number every minute as ordinary metrics.     Issue an error if there are too many INFO and ERROR+ logs, for example, error if we are logging more that 1000 info/error+ per second.

**Comment by xzxiong** [comment]
not start yet, try repro on https://github.com/matrixorigin/matrixone/issues/9891

**Comment by xzxiong** [comment]
not start yet

**Comment by xzxiong** [comment]
fcous on span trigger profile dump, now on ut case.

**Comment by xzxiong** [comment]
not start yet

**Comment by xzxiong** [comment]
not start yet

**Comment by xzxiong** [comment]
not start yet

**Comment by xzxiong** [comment]
not start yet

**Comment by xzxiong** [comment]
not start yet

**Comment by xzxiong** [comment]
plan to next week

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
pending

**Comment by xzxiong** [comment]
working on

**Comment by xzxiong** [comment]
Working on

**Comment by xzxiong** [comment]
after pr https://github.com/matrixorigin/matrixone/pull/11023, @fengttt  PTAL
- Add new metric `mo_log_message_count` show rows of log message ourput per Node, per minute.
- Add `Check Log Messages Count per second` CI Step to pre-check the val per second < threshold (default: 1000)
