### ISSUE TITLE
[Bug]: the size of mo log is too large that the regression test on standlone can not success for no space left

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9838]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):293734f87703577ee662a4f05e5e96e659019a0b
- Hardware parameters: CPU 64G MEM 256G  DISK 916G
- OS type:
- Others:
```

### Actual Behavior

as run sysbench oltp test for about 1 hours, the size of log and etl is as following:

<img width="810" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/fd72cd9e-e1c3-4d83-862e-2a0ae68918ec">

and It caused the server disk on space left ,and the test failed.

<img width="1209" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/2daab54f-8788-42f3-9e65-5e570e9cf63e">

**Comment by zhangxu19830126** [comment]
请zexiong先看一下

**Comment by xzxiong** [comment]
pr https://github.com/matrixorigin/matrixone/pull/8825 plan to merged today, it will change default log-level as info and change 99% info-log to debug-log.

**Comment by xzxiong** [comment]
wait insert perf improvement done.

**Comment by gavinyue** [comment]
But how do we have 582GB logs or statements?

**Comment by xzxiong** [comment]
> But how do we have 582GB logs or statements?

in `etl` folder, also have rawlog info, including log/span/error info. (this version still record)

**Comment by gavinyue** [comment]
Assign this to testing team. 

Is this still a problem?

**Comment by aressu1985** [comment]
testing

**Comment by aressu1985** [comment]
still exists

**Comment by gavinyue** [comment]
Pending for the stmt_aggr pr merge. Stuck on dn oom

**Comment by gavinyue** [comment]
stme_aggr merged. Start to verify this.

**Comment by aressu1985** [comment]
fixed
