### ISSUE TITLE
[Bug]: some 'constraint violation: Column 'hist_id' cannot be null' errors in tpcc payment txn on eks with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9840]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):293734f
- Hardware parameters: 
2*CN  AWS EC2 16C 64G
1*DN  AWS EC2 16C 64G
3*LOG  AWS EC2 16C 64G

- OS type:
- Others:
CN  DISKCACHE  : 100G
CN  MEMCACHE: 16G
```

### Actual Behavior

<img width="1395" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/7bcf7896-649a-44d1-bb8c-5bdeb7787a36">

but the column hist_id is auto_incremental, and should never report this error in the following sql:

   INSERT INTO bmsql_history (h_c_id, h_c_d_id, h_c_w_id, h_d_id, h_w_id, h_date, h_amount, h_data)  VALUES (?, ?, ?, ?, ?, ?, ?, ?)

the log is in s3 aws s3 ls s3://mo-ares/etl/etl_20230604001057/

**Comment by zhangxu19830126** [comment]
not woking on this

**Comment by zhangxu19830126** [comment]
找到一个可能的地方，并且修复了，不确定是否修复了。等pr合并后再跑跑看

**Comment by aressu1985** [comment]
viewing for a few day, it did not occured agian. closed
