### ISSUE TITLE
[Bug]: mo was hung on eks after running tpch regression and tpcc regression test 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9841]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 293734f
- Hardware parameters:
2*CN  AWS EC2 16C 64G
1*DN  AWS EC2 16C 64G
3*LOG  AWS EC2 16C 64G

- OS type:
- Others:
CN  DISKCACHE  : 100G
CN  MEMCACHE: 16G
```

### Actual Behavior

<img width="1405" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/041c6cbb-8e6b-458e-b8b7-bedfa5bd977d">
<img width="1404" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/45496984-ce0b-4097-a8fc-faed62ccb92f">

mo log is in s3, path s3://mo-ares/etl/etl_20230604001057/

**Comment by zhangxu19830126** [comment]
这个看上去是logtail hung住了，@aptend，请帮忙先看看

**Comment by aptend** [comment]
<img width="1656" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/e5a81fd9-1e15-459c-88a3-8c801ae57387">

早在 19:07:35 附近的第一次 tpcc 测试中就已经出现错误。其中一条向 history 表中做插入的 sql (__mo_stmt_id_19) 未能成功执行，执行日志：

`2023-06-03 19:07:44.277320,info,frontend/util.go:409,query trace,"{""connection_id"":559,""query"":""execute __mo_stmt_id_19 using @__mo_stmt_var_0,@__mo_stmt_var_1,@__mo_stmt_var_2,@__mo_stmt_var_3,@__mo_stmt_var_4,@__mo_stmt_var_5,@__mo_stmt_var_6,@__mo_stmt_var_7"",""vars"":""2428 , 1 , 1 , 1 , 1 , 2023-06-04 03:07:43.774000 , 2597.25 , Pkclpw    azdisOtQxF"",` 

并且注意到：
1. 日志中有大量 `table ""mo_increment_columns"" does not exist` 错误
2. history 表中的 `hist_id` 列为自增列
3. 仅在 cn0 上出现 `table ""mo_increment_columns"" does not exist` 

<img width="1640" alt="image" src="https://github.com/matrixorigin/matrixone/assets/49832303/bc87cf25-f987-46bd-b22a-84ade61048dd">

**Comment by zhangxu19830126** [comment]
根据hanfeng给的定位帮助，DN收到了cn1的自增表的订阅请求，有logtail。但是没有收到cn0的自增列的订阅请求，导致找不到自增列的表。@m-schen看一下

**Comment by m-schen** [comment]
push模型下一个查询的执行：

1. 看 mo_database有没有相应的db -> 没有就报错
2. 看 mo_tables油管有相应的table -> 没有就报错
3. 看 mo_columns有没有相应的列 -> 没有就报错
4. 看这张表有没有订阅，没有的话就订阅，然后轮询等待订阅成功

报找不到自增列对应的表的话是在步骤2就出错了。因此走不到订阅那一步。
出现该问题的原因可能是 auto-increase-table 对应在 mo_tables里的insert log没有被cn0收到或者没有发送，暂不确定。

**Comment by aressu1985** [comment]
现在EKS已经有各种hung的问题，无法确认该问题是否已经解决

**Comment by aressu1985** [comment]
Fixed
