### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode:  no data conflict, delete data wait for lock

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9851]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):71e7151601635363e8c131484449abbfb3508715
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

line 226：
No found before line 226 cases which about table dis_table_02  unsubmitted transactions，delete sql should not wait for lock,should execute succeed
![image](https://github.com/matrixorigin/matrixone/assets/113406637/01287b9b-9daa-419a-8f87-f89d383d67bf)

case file and result file:
[case.zip](https://github.com/matrixorigin/matrixone/files/11650130/case.zip)

### Steps to Reproduce

```Markdown
download case file and result file，use mo-tester run
```

**Comment by zhangxu19830126** [comment]
not woking on this

**Comment by zhangxu19830126** [comment]
not woking on this

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
不是bug，session 2的事务没有提交，所以被锁住。

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm，case problem，closed
