### ISSUE TITLE
[Bug]: Sometimes MO fails to start up.

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#9853]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 293734f87703577ee662a4f05e5e96e659019a0b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1103" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/af399caf-6ac5-4b1e-8b97-df29146ec761">
[mo-service.log.zip](https://github.com/matrixorigin/matrixone/files/11650333/mo-service.log.zip)

**Comment by zhangxu19830126** [comment]
还在继续分析，能够复现。logtail丢失了，还在找为什么

**Comment by cnutshell** [comment]
> * 1-mo_catalog:272386-mo_increment_columns

According to mo-service's log, cn didn't subscribe the two tables also:
- 1-mo_catalog:272385-mo_indexes
- 1-mo_catalog:272386-mo_increment_columns

Under push model, if `cn` didn't subscribe table A, then `logtail service` of `dn` side wouldn't push its `logtail`.

**Comment by m-schen** [comment]
试试看！

**Comment by sukki37** [comment]
Haven't reproduced for two weeks
