### ISSUE TITLE
[Bug]: improve insert mem reused

### ISSUE THREAD

**Issue by ouyuanning** [matrixorigin/matrixone#9859]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

 improve insert mem reused

**Comment by fengttt** [comment]
Raise to S-1 because it may block merge regression check and daily run, after Gavin's work.

**Comment by ouyuanning** [comment]
正在重构prepare的逻辑去掉了部分expr的生成和拷贝

**Comment by ouyuanning** [comment]
1、根据今天的方案。目前完成了把@,? 都转成string的vector部分。还有一些bvt过不了
2、正在实现 COM_STMT_SEND_LONG_DATA 协议，不然log这种大数据量无法使用二进制协议的prepare。完成30%

**Comment by ouyuanning** [comment]
COM_STMT_SEND_LONG_DATA 已实现。
切换成prepare后，gavin测试的结果。350万的sql。成功数从250W能提升到310W，但是依然有错误。
下周一我再看看

**Comment by ouyuanning** [comment]
修复了2个bug。bvt还剩一个没过。
有辛苦Gavin重新帮测一下350W的那个数据。明天确认下结果如何

**Comment by ouyuanning** [comment]
合并了莫尘的优化部分。今天处理了启动和部分panic问题。
bvt通过率还很低

**Comment by ouyuanning** [comment]
通过率99%了，不过按照目前都转string的方法。似乎存在无法解决的问题。比如  true， 转成string后是 true。  但是bool的true可以转int。 字符串"true“就不行了。可能还有其他特殊情况

**Comment by ouyuanning** [comment]
通过string转一手的方式总会有新的问题，改不完。
今天跟莫尘、张潇讨论了还是改为用实际类型。正在修改中

**Comment by ouyuanning** [comment]
insert的结果直接写入到列类型的vector部分。完成了部分类型的处理
还差：date/time/datetime/timestamp/uuid

**Comment by ouyuanning** [comment]
还差一个bug待处理

**Comment by ouyuanning** [comment]
处理了已知问题。但是合并main之后，目前还有个sysbench的问题，不确定是否main分支引入的。
还得再确认

**Comment by ouyuanning** [comment]
有个s3文件找不到的问题，罗飞在帮忙处理

**Comment by ouyuanning** [comment]
PR已合并
