### ISSUE TITLE
[Bug]: HA issue: MO failed to restore after 2 nodes shutdowned and restarted

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9871]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):ae2c3fd6
- Hardware parameters:
- OS type:
- Others:

root@HOST-10-206-134-2:~# k get mo mo -nmo-hn
NAME   LOG   DN    TP    AP    VERSION            PHASE   AGE
mo     3     1                 nightly-ae2c3fd6   Ready   24h
root@HOST-10-206-134-2:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@HOST-10-206-134-2:~# uname -a
Linux HOST-10-206-134-2 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
```

### Actual Behavior

We have a cluster of mo which has a topology like this:

**Env** 
3 nodes( host-10-206-134-11/host-10-206-134-2/host-10-206-134-15)  work as both k8s master and node, where minio and mo are deployed.

pods: mo and minio pods are distributed like this, with pvs using minio directpv csi
![image](https://github.com/matrixorigin/matrixone/assets/46433151/429d00ba-a5ea-44db-9295-3744b6cb550a)

**What's the problem**
Here's the steps of actions taken to the cluster:

1. Shutdown host host-10-206-134-2. Then this host became not ready as seen via `kubectl get node`
![image](https://github.com/matrixorigin/matrixone/assets/46433151/1dadd82a-fea9-4e87-a0b5-0055cd7f9f24)
![image](https://github.com/matrixorigin/matrixone/assets/46433151/f387644c-2678-4be5-97b9-2aa9a1cfe0c5)

In this case, pods affected are listed as below:
```bash
minio1-ss-0-2.minio-mo
mo-log-2.mo-hn
```

2. Check the availability of the cluster, for example, by connecting to cn/proxy, and making some queries. At this point, mo can still provide services to users, just as normal as no incidents occur.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/8d722795-83ed-4476-b159-0f92576a64b8)
![image](https://github.com/matrixorigin/matrixone/assets/46433151/68b3cd9b-b728-4b4a-b584-d3861e7675ba)

Also, data in minio can be accessed(read and write) normally.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/8015d702-3c9c-4d7e-9717-bf3e20fbee2a)

3. Shutdown host host-10-206-134-11. In this case, only host host-10-206-134-15 is alive. Try to use `kubectl` command to verify cluster status, but it seems apiserver is gone, and `kubectl` is no longer working.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/4dc6d039-2900-44fd-aef5-8eeaeab51ee0)
![image](https://github.com/matrixorigin/matrixone/assets/46433151/e19ed80a-0efd-4ed7-a110-887cc5be026c)
![image](https://github.com/matrixorigin/matrixone/assets/46433151/acefcf7e-b991-4fa5-ae31-214360a5c6d1)

4. Restore host host-10-206-134-2 first by restarting the host, but keep host host-10-206-134-11 unavailable for now. In this case, host host-10-206-134-2 became ready eventually, but dn was in error status.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/a0a5ca88-3b06-4dc4-8d56-3d8a4d203022)

Also there's no way to connect to mo, i.e. cns/proxies were not in normal status.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/040e31d5-6142-4e95-9406-0c602c9aeeab)
![image](https://github.com/matrixorigin/matrixone/assets/46433151/f63ea1fb-f7fb-4e2c-a163-640ece7b3fb5)

However, minio was back and seemed to work normally.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/0d8fe8bb-e3b7-4d7a-b6d3-0b13708dd306)

5. Fianally restore host host-10-206-134-11, and eventually all nodes are ready, also mo pods are in running status. 
![image](https://github.com/matrixorigin/matrixone/assets/46433151/8c0e6851-1687-41f3-afb2-9d1e332ab5b5)

However, mo was still not connectable, including all cns and proxies. 
![image](https://github.com/matrixorigin/matrixone/assets/46433151/5498e7db-7ff9-4cc3-9130-f155f462a99e)

From the logs of one of the cns, it seemed like logtails were corrupted? And cn was not able to open a new transaction for end user.
![image](https://github.com/matrixorigin/matrixone/assets/46433151/7d8d8e25-658f-4b8f-af9d-9cc5f570d2fe)

### Expected Behavior

Shutdown 2 nodes and restart them one by one after a while, then mo should return to work as normal as before the incident. This is a very commonly seen incident in a production environment, for example, powering down 2 nodes for maintenance.

### Steps to Reproduce

```Markdown
See above
```

### Additional information

See above

**Comment by aronchanisme** [comment]
After leaving the cluster for a very long time(from last night 6/5 to this morning 6/6), mo seems to be working now. But one the proxies is still not working. However since I didn't have it a check last night, I have no clude when it became available again.

<img width="1282" alt="企业微信截图_c18a61e9-b89c-416e-a3f7-b19660772b0d" src="https://github.com/matrixorigin/matrixone/assets/46433151/e88ab3f1-406b-44cd-a7f7-f587fedb6f61">

<img width="1354" alt="企业微信截图_59bc989e-f3da-44fb-8d59-7f691527d2f6" src="https://github.com/matrixorigin/matrixone/assets/46433151/94757e13-b5a8-43a2-b153-ba01b2db9dd2">

**Comment by aronchanisme** [comment]
Attaching the logs of mo and mo-operator
[mo-log-20230606-1155.tar.gz](https://github.com/matrixorigin/matrixone/files/11659762/mo-log-20230606-1155.tar.gz)

**Comment by volgariver6** [comment]
logservice长时间不能恢复的问题，等 #9775 合并再测试一下。

proxy的问题有另一个issue了，#9787，需要加一些日志再看。

**Comment by volgariver6** [comment]
#9775 已经合并，请重新测试 @aronchanisme

**Comment by aronchanisme** [comment]
scheduling test

**Comment by aronchanisme** [comment]
It's fixed as per my test. Shutdown host-10-206-134-11 and host-10-206-134-2 one by one and restart host-10-206-134-11 and host-10-206-134-11 one by one. MO can restore automaticlly, and data remains as still. Closing it now.

test commit id
```bash
root@HOST-10-206-134-11:~# k get mo mo -nmo-hn
NAME   LOG   DN    TP    AP    VERSION            PHASE   AGE
mo     3     1                 nightly-9de3c465   Ready   52m
```

After 2 nodes shutdown
![企业微信截图_1686754372611](https://github.com/matrixorigin/matrixone/assets/46433151/0691d309-0c2f-4033-9974-2ee9b2984c38)

![企业微信截图_16867545026195](https://github.com/matrixorigin/matrixone/assets/46433151/93204912-4243-4d33-9b5e-edc4648420b8)


After 2 nodes restored
![企业微信截图_16867548557037](https://github.com/matrixorigin/matrixone/assets/46433151/9446f8d4-f824-4d46-9e9e-91bd3869e2c2)
![企业微信截图_16867548882385](https://github.com/matrixorigin/matrixone/assets/46433151/c029772e-c8db-443d-bb16-10ce39ced2b9)
![企业微信截图_16867549155662](https://github.com/matrixorigin/matrixone/assets/46433151/eaea1b7b-0c1a-4b73-9466-ef747473960e)
