### ISSUE TITLE
[Bug]: suspend account, account can still login

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#9878]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):b209696954ac22e9c447db8cc103b0285964a9ac
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

sys tenant execute:
```
create account test_tenant_2  admin_name 'test_account' identified by '111';
select * from mo_account;
+------------+---------------+--------+---------------------+----------------+---------+----------------+
| account_id | account_name  | status | created_time        | comments       | version | suspended_time |
+------------+---------------+--------+---------------------+----------------+---------+----------------+
|      10003 | test_tenant_2 | open   | 2023-06-06 07:28:23 |                |   10005 | NULL           |
|          0 | sys           | open   | 2023-06-05 09:58:02 | system account |       1 | NULL           |
+------------+---------------+--------+---------------------+----------------+---------+----------------+
```
login in test_tenant_2 account:
```
mysql -h127.0.0.1 -utest_tenant_2:test_account -p111 -P6009
```

sys tenant execute:
```
alter account test_tenant_2 suspend;
```
test_tenant_2 account execute:
```
mysql> show databases;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user test_tenant_2:test_account. internal error: Account test_tenant_2 is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
Connection id:    597
Current database: *** NONE ***

+--------------------+
| Database           |
+--------------------+
| system             |
| system_metrics     |
| information_schema |
| mysql              |
| mo_catalog         |
+--------------------+
5 rows in set (0.02 sec)

```

连续多次尝试连接会成功连接 到 ssuspend 状态的account.

### Expected Behavior

No operation is allowed to successfully connect to an account in suspend state

**Comment by volgariver6** [comment]
@YANGGMM please check this one.

**Comment by tianyahui-python** [comment]
start commend: ./mo-service -launch etc/launch-with-proxy/launch.toml -with-proxy   connection port: 6009

**Comment by YANGGMM** [comment]
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 
mysql> 
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 
mysql> 
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 
mysql> 
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 
mysql> 
mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> show databases;
No connection. Trying to reconnect...
ERROR 1045 (28000): Access denied for user acc_idx:root. internal error: Account acc_idx is suspended
ERROR: 
Can't connect to the server

mysql> 


无法复现

**Comment by YANGGMM** [comment]
<img width="1156" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/34143b24-2cc6-4850-ad24-7b9c7597ebd8">

**Comment by YANGGMM** [comment]
<img width="753" alt="image" src="https://github.com/matrixorigin/matrixone/assets/26563383/0f982aff-1d25-4048-9522-c344f286698b">

**Comment by YANGGMM** [comment]
still have this problem

**Comment by YANGGMM** [comment]
still working

**Comment by YANGGMM** [comment]
can't repo in single cn

**Comment by YANGGMM** [comment]
can't repo in multi cn

**Comment by YANGGMM** [comment]
may have fixed it, @tianyahui-python

**Comment by tianyahui-python** [comment]
Please describe the root cause of the bug and comment on the solution. @YANGGMM

**Comment by YANGGMM** [comment]
it was caused by mutli cn, when kill a cn's connection, the server connected to another cn.
