### ISSUE TITLE
[Bug]: mo panic by internal error: driver info: retry time out during stability test on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9883]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):5e19c1a79941d731647076709e50abc1556ab2f9
- Hardware parameters: 16C 64G
- OS type:
- Others:
```

### Actual Behavior

the error log:
2023/06/06 18:08:47.337399 +0800 INFO catalog/database.go:477 [Catalog] {"operation": "remove", "operand": "TBL[282455][name=mo_stored_procedure][C@1686039836577783214-0,D@1686039836903454219-0]"}
2023/06/06 18:08:47.297326 +0800 WARN logservicedriver/appender.go:100 append to logservice took 6m38.034800002s
panic: internal error: driver info: retry time out

goroutine 58928427 [running]:
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*driverAppender).append(0xc02e57bd00, 0x1?, 0x2540be400)
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go:78 +0x677
created by github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver.(*LogServiceDriver).onAppendQueue
        /mnt/datadisk0/actions-runner/_work/mo-nightly-regression/mo-nightly-regression/matrixone/pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go:66 +0xf4

[mo-service.tar.gz](https://github.com/matrixorigin/matrixone/files/11664835/mo-service.tar.gz)

### Expected Behavior

mo should be never crash

### Steps to Reproduce

```Markdown
1. run a mo server on standlone mode 
2. run bvt test loop
3. run tpch_10 test loop
4. run sysbench mixed test 
5. run tpcc 10 warehouse 10 terminal
```

**Comment by volgariver6** [comment]
I will take this one.

**Comment by volgariver6** [comment]
对日志进做了过滤，把不相关的信息全部删掉。上传一下过滤后的日志文件：
[issue.log](https://github.com/matrixorigin/matrixone/files/11672359/issue.log)

**Comment by volgariver6** [comment]
### 问题分析

该问题是由dn向logservice写数据超时导致的panic，从日志来看，在panic之前就开始写入数据变慢：

```
2023/06/06 18:00:56.217488 +0800 WARN logservicedriver/appender.go:100 append to logservice took 1m32.260443588s
2023/06/06 18:00:56.216781 +0800 WARN logservicedriver/appender.go:100 append to logservice took 1m32.540563717s
2023/06/06 18:00:56.217630 +0800 WARN logservicedriver/appender.go:100 append to logservice took 1m32.119670334s
2023/06/06 18:00:56.135985 +0800 WARN logservicedriver/appender.go:100 append to logservice took 2.466380988s
2023/06/06 18:00:56.217258 +0800 WARN logservicedriver/appender.go:100 append to logservice took 1m32.278655261s
```

最后一次写数据超过6分钟没有完成，就panic了。

### 原因

应该是系统负载非常高，导致没有办法及时完成数据写入操作。

@aressu1985 麻烦打开profile再做一次测试，看一下cpu使用情况。

**Comment by aressu1985** [comment]
@volgariver6 
the profile of this time
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/11673526/profile.tar.gz)

**Comment by volgariver6** [comment]
等 @aressu1985 再跑一次拿到profile

**Comment by volgariver6** [comment]
加了一条日志，下次再出现时看看是否是因为包过大导致的。

**Comment by volgariver6** [comment]
```
2023/06/12 14:27:45.459939 +0800 INFO logservicedriver/appender.go:77 size is 8251
```
log size 是8251，不是因为包过大导致的。

还在找能够复现的方法。。。

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
no progress

**Comment by aressu1985** [comment]
has been reproed on stability test on 20 Jun.
and the profile is 6 minutes before the mo crash.
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/11795667/profile.tar.gz)

**Comment by volgariver6** [comment]
no progress.

**Comment by volgariver6** [comment]
加了trace，等再跑出来看看结果

**Comment by volgariver6** [comment]
dup with #9867 正在看

**Comment by volgariver6** [comment]
在本地环境尝试复现，以及在 @aressu1985 的环境上，问题都出现在读IO突然增大的时刻，今天早上7点多 @aressu1985 的环境上，当读IO突然增大时，还发生了OOM：

```
[Tue Jun 27 07:50:25 2023] Out of memory: Killed process 3641519 (mo-service) total-vm:82994440kB, anon-rss:61995328kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:135544kB oom_score_adj:500
```

OOM之前的IO监测：
<img width="1369" alt="WeChatWorkScreenshot_d114d57d-10c7-4245-8bfa-360440d47cdd" src="https://github.com/matrixorigin/matrixone/assets/18366608/0aba34a5-35a8-477e-bb16-1d83fca5bd6e">

目前的现象来看，是由于读IO增大，磁盘IO utility 达到100%，导致logservice写数据非常慢，整个系统工作不正常了。

还没有找到读IO突然增大的原因。

**Comment by volgariver6** [comment]
IO突增的原因还没找到。

**Comment by volgariver6** [comment]
目前的进展是有大量的通过fileservice的小块读请求，但是通过抓文件和抓goroutines都没有找到具体调用者。

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
目前分析得到的结果是，在standalone模式下做压力稳定性测试，由于是共享的磁盘，所以logservice会收到其他模块IO的影响出现写数据延迟高的问题。

建议在做standalone性能方面的测试时，将fileservice和logservice的磁盘分开。

@aressu1985

**Comment by fengttt** [comment]
> 目前分析得到的结果是，在standalone模式下做压力稳定性测试，由于是共享的磁盘，所以logservice会收到其他模块IO的影响出现写数据延迟高的问题。
> 
> 建议在做standalone性能方面的测试时，将fileservice和logservice的磁盘分开。
> 
> @aressu1985

Had a lengthy discussion with YueSheng.    So far I believe it is bad I/O pattern.     

"将fileservice和logservice的磁盘分开。" is NOT the solution.

**Comment by volgariver6** [comment]
最近standalone测试都没有复现，先降级s0，一边观察一边分析

**Comment by volgariver6** [comment]
set to holding because no progress recently.

**Comment by volgariver6** [comment]
assign back to @aressu1985 , because it does not happen again.

**Comment by aressu1985** [comment]
fixed

**Comment by volgariver6** [comment]
related with #12221
