### ISSUE TITLE
[Bug]: from 2cn to 1cn, cluster cannot be connected for a long time

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#9885]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-e033a55
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

with a distributed on-premise MO cluster, I started with a cluster of 2CN.
<img width="471" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/ba3eaa37-454d-4d5a-b00c-2d45f73b3b10">

I reduced the number of CN to 1 replica by modifying the yaml file. It took about half a minute to terminate the mo-tp-cn-1.

<img width="1027" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/b72f0108-8250-4447-8cda-bcea3aa32692">

MO cannot be connected afterwards, and the error message is always "ERROR 1045 (28000): Access denied for user dump. SQL parser error: table "mo_account" does not exist"
<img width="822" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/4a91f57b-9730-4cb4-b72e-9797bba3c215">

Neither of connect from cn/svc nor proxy works. 
<img width="723" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/b479fc7b-f389-41f0-8b50-d5e329f13a15">
<img width="834" alt="image" src="https://github.com/matrixorigin/matrixone/assets/4965857/33b81cbc-fcaa-44d1-938d-3d1eeadf8232">

below are the logs of cn0 and dn. 

[cn.log.202306062146.txt](https://github.com/matrixorigin/matrixone/files/11673436/cn.log.202306062146.txt)
[dn.log.202306062146.txt](https://github.com/matrixorigin/matrixone/files/11665436/dn.log.202306062146.txt)

**Comment by daviszhen** [comment]
找不到mo_account表。但是这个表是一直存在的。
原因是开启事务失败。

<img width="1529" alt="image" src="https://github.com/matrixorigin/matrixone/assets/60595215/b2638589-b19c-4d6f-ac2c-0c3f53825282">

![image](https://github.com/matrixorigin/matrixone/assets/60595215/638be6b8-896d-42fe-b685-0daeac5d62e4)

**Comment by nnsgmsone** [comment]
暂时没空处理，后续我转给其他的同事

**Comment by nnsgmsone** [comment]
暂时没空处理，后续我转给其他的同事

**Comment by nnsgmsone** [comment]
在旭哥的pr后，应该已经修复了。。可以确认一下 @dongdongyang33

**Comment by dongdongyang33** [comment]
verified, has been fixed

**Comment by dengn** [comment]
checked in the version nightly-7ebfe11d.

it still took about 2 minutes to connect. I don't think it's a good fix.

**Comment by dongdongyang33** [comment]
现在修改配置后直接重连不会出现最初描述的问题了
直接连接 cn 也可以连上
但是如果连接的是 proxy 需要 2min 左右才能连上

**Comment by volgariver6** [comment]
fixed

**Comment by dengn** [comment]
fixed.
