### ISSUE TITLE
[Subtask]: Keep external table for querying CSV logging

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9889]
### Parent Issue

#8196

### Detail of Subtask

When logging CN is not up, cannot connect etc, we will revert to write CSV.    Later a background thread will merge them into internal table.

We want to keep the external tables that can query those CSV files.   Under normal operations, there should be no CSV files -- should not be many and if there are any should be quickly picked up and merged (should be a few minutes?)

At the end of daily run/perf run/merge regression run, we should test select count(*) from ..., it should be a very small number, if not zero.

**Comment by gavinyue** [comment]
Will work on this after s-1 issue on statementinfo cleaning

**Comment by gavinyue** [comment]
https://github.com/matrixorigin/matrixone/issues/9834

**Comment by gavinyue** [comment]
Not working on this yet.

**Comment by gavinyue** [comment]
Probably do not need this feature if the csv can be consumed.  Downgrade to s1

**Comment by fengttt** [comment]
OK, let's go all in.    CSV to internal table WILL catch up.
