### ISSUE TITLE
[Bug]: eks bvt regression： the same sql and  statement_id log records  in statement_info are greater than 1

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9891]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-3ca7054
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5189483136/jobs/9354645167
![image](https://github.com/matrixorigin/matrixone/assets/113406637/e987ea68-d57f-47dd-a282-aeb83985ce07)

**Comment by volgariver6** [comment]
@xzxiong please check this issue.

**Comment by xzxiong** [comment]
very strange
the uuid, in bvt log, is NOT found in cn's log.

**Comment by xzxiong** [comment]
this was an  timeout issue like:

**Comment by xzxiong** [comment]
not sure how to fix, there is:
1. mo should sense the connection status
2. mo commit op should sucess in 3 sec.

**Comment by xzxiong** [comment]
another case:
https://github.com/matrixorigin/matrixone/actions/runs/5200832630/jobs/9380111760?pr=9916

![4531686191122_ pic](https://github.com/matrixorigin/matrixone/assets/3927687/ea62decb-f382-4c43-805b-3729aa9ed973)

**Comment by xzxiong** [comment]
> another case: https://github.com/matrixorigin/matrixone/actions/runs/5200832630/jobs/9380111760?pr=9916 ![企业微信截图_bc5d0dda-37d7-4707-8096-f853394a6261](https://user-images.githubusercontent.com/3927687/244250555-2500ebd2-bfea-45d2-8c08-7f57a9773919.png)
> 
> @gavinyue 这里表现为顺序插入了 2遍，更大可能是：
> 
> 1. collector buffer中插入了2次
> 2. sqlWriter 重复写了 2次
> 3. insert 语句在CN执行时，写了 2次。

this was ci action `[Multi-CN e2e BVT Compatibility Test on Linux/x64(LAUNCH, PUSH)]` 本身的问题，需要加上时间的参数。

**Comment by xzxiong** [comment]
important one CI result https://github.com/xzxiong/matrixone/actions/runs/5218093671
show there is NO op `commit` failed.

**Comment by xzxiong** [comment]
important CI job: https://github.com/xzxiong/matrixone/actions/runs/5239279033/jobs/9462419306
collect great infos.

**Comment by xzxiong** [comment]
@gavinyue ptal

**Comment by gavinyue** [comment]
Will fix this along with new insert change.

**Comment by gavinyue** [comment]
pending on https://github.com/matrixorigin/matrixone/issues/9834

**Comment by gavinyue** [comment]
#10090 一起处理

**Comment by gavinyue** [comment]
Looking into this today

**Comment by gavinyue** [comment]
pending on the stmt_aggr merge

**Comment by gavinyue** [comment]
Pending for the stmt_aggr pr merge. Stuck on dn oom

**Comment by gavinyue** [comment]
Merged the PR for stmt_aggr. Close this issue.

**Comment by xzxiong** [comment]
> important CI job: https://github.com/xzxiong/matrixone/actions/runs/5239279033/jobs/9462419306 collect great infos.
> 
> ![image](https://user-images.githubusercontent.com/3927687/245114406-a52a7a18-6504-4a47-b0fa-5abaa33d9d6a.png)

@gavinyue ptal 
in `db_holder.go`, there still has problem between `calling bulkInsert` and `context.Done()`
https://github.com/matrixorigin/matrixone/blob/dacfe86b80aba01df84e3c25ff3dce55aa27f26c/pkg/util/export/etl/db/db_holder.go#L187

**Comment by gavinyue** [comment]
Start coding this. ETA 27th

**Comment by gavinyue** [comment]
Pr draft is ready

**Comment by gavinyue** [comment]
PR is ready for review

**Comment by gavinyue** [comment]
Should be resolved after the https://github.com/matrixorigin/matrixone/pull/10302 merged

**Comment by heni02** [comment]
The problem is not easy to reproduce in the case. After reviewing the eks regression results for the past 3 days, no issues were found. Please close it first
he past 3 days eks bvt regression：
https://github.com/matrixorigin/matrixone/actions/runs/5434137867/jobs/9882428023
https://github.com/matrixorigin/matrixone/actions/runs/5439585269/jobs/9891842672
https://github.com/matrixorigin/matrixone/actions/runs/5430403710/jobs/9876190235
