### ISSUE TITLE
[Bug]: cn panic by   internal error: panic runtime error: invalid memory address or nil pointer dereference during tpcc 10-50 test on eks with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9896]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6e33e55
- Hardware parameters:
  2*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 16C 64G
- OS type:
- Others:
  DISKCACHE: 100G
  MEMCACHE: 16G
```

### Actual Behavior

the test tools error log:
20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).waitSendCompleted
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:97
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).Get
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:71
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).Ping
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:216
github.com/matrixorigin/matrixone/pkg/sql/compile.isAvailable
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:450
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).removeUnavailableCN
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:466
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:481
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:340
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:153
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/computation_wrapper.go:337
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2906
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3343
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3562
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:207
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:427
github.com/fagongzi/goetty/v2.(*server).doConnection
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20230520035916-bc1fed6f5e26/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20230520035916-bc1fed6f5e26/application.go:344
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-06-07 04:50:19 FATAL jTPCCTerminal:235 - [UNEXPECTED][STOCK_LEVEL][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).waitSendCompleted
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:97
github.com/matrixorigin/matrixone/pkg/common/morpc.(*Future).Get
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/future.go:71
github.com/matrixorigin/matrixone/pkg/common/morpc.(*client).Ping
	/go/src/github.com/matrixorigin/matrixone/pkg/common/morpc/client.go:216
github.com/matrixorigin/matrixone/pkg/sql/compile.isAvailable
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:450
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).removeUnavailableCN
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:466
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:481
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).compileScope
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:340
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).Compile
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/compile.go:153
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/computation_wrapper.go:337
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).executeStmt
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:2906
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3343
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3562
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:207
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
	/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:427
github.com/fagongzi/goetty/v2.(*server).doConnection
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20230520035916-bc1fed6f5e26/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
	/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20230520035916-bc1fed6f5e26/application.go:344
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-06-07 04:50:19 FATAL jTPCCTerminal:235 - [UNEXPECTED][STOCK_LEVEL][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: panic runtime error: invalid memory address or nil pointer dereference: 

the mo log is in s3. the path will update soon

### Expected Behavior

The CN should never crash

### Steps to Reproduce

```Markdown
1. run a cluster on eks with 2*cn using the same config
2. run tpcc 10 warehouse 50 terminals for about more than 20 minutes
```

**Comment by volgariver6** [comment]
@zhangxu19830126 please help to fix this issue.

**Comment by aressu1985** [comment]
log path: s3://mo-ares/etl/etl_20230607083208/

**Comment by w-zr** [comment]
Fixed

**Comment by aressu1985** [comment]
这个现象已经没有了，会存在其他问题，这个先关闭
