### ISSUE TITLE
[Bug]: cn panic by panic: runtime error: makeslice: len out of range during tpcc 10-10 test on eks with 2*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9897]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6e33e55
- Hardware parameters:
  2*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 16C 64G
- OS type:
- Others:
  DISKCACHE: 100G
  MEMCACHE: 16G
```

### Actual Behavior

<img width="1314" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6f112b05-59c8-4444-9c2c-ffafb1ac9bb5">

the mo panic log:
{"level":"ERROR","time":"2023/06/07 04:49:54.173735 +0000","caller":"frontend/util.go:429","msg":"w-w conflict","session_info":"connectionId 1320|10.0.124.103:45014|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 14902|aff4083b-04ee-11ee-ab71-9ec87a85f8a2"}
{"level":"ERROR","time":"2023/06/07 04:49:54.173771 +0000","caller":"frontend/util.go:429","msg":"query trace status","connection_id":1320,"statement":"commit","status":"fail","error":"w-w conflict","span":{"trace_id":"be9abccb-04ee-11ee-ab71-9ec87a85f8a2","kind":"statement"},"session_info":"connectionId 1320|10.0.124.103:45014|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 14902|aff4083b-04ee-11ee-ab71-9ec87a85f8a2"}
{"level":"ERROR","time":"2023/06/07 04:49:54.177119 +0000","caller":"frontend/util.go:447","msg":"CommitTxn: txn operator commit failed. txnId:ac268d10dff4496db72128c3275e2f17/Active/S:1686113394139517886-1 error:w-w conflict connectionId 1329|10.0.124.103:45050|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 15925|b1249be6-04ee-11ee-ab71-9ec87a85f8a2"}
{"level":"ERROR","time":"2023/06/07 04:49:54.177166 +0000","caller":"frontend/util.go:429","msg":"w-w conflict","session_info":"connectionId 1329|10.0.124.103:45050|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 15925|b1249be6-04ee-11ee-ab71-9ec87a85f8a2"}
{"level":"ERROR","time":"2023/06/07 04:49:54.177180 +0000","caller":"frontend/util.go:429","msg":"query trace status","connection_id":1329,"statement":"commit","status":"fail","error":"w-w conflict","span":{"trace_id":"be9be86d-04ee-11ee-ab71-9ec87a85f8a2","kind":"statement"},"session_info":"connectionId 1329|10.0.124.103:45050|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 15925|b1249be6-04ee-11ee-ab71-9ec87a85f8a2"}
panic: runtime error: makeslice: len out of range

goroutine 462199 [running]:
github.com/matrixorigin/matrixone/pkg/common/bitmap.(*Bitmap).TryExpandWithSize(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/common/bitmap/bitmap.go:335
github.com/matrixorigin/matrixone/pkg/container/nulls.TryExpand(...)
	/go/src/github.com/matrixorigin/matrixone/pkg/container/nulls/nulls.go:120
github.com/matrixorigin/matrixone/pkg/container/nulls.(*Nulls).Add(0xc0554af440?, {0xc0889bf6a8?, 0x1?, 0xc000271570?})
	/go/src/github.com/matrixorigin/matrixone/pkg/container/nulls/nulls.go:136 +0x97
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.BlockReadInner({0x2d9bb38, 0xc0580de780}, 0xc08b95ac00, {0xc08ba59400, 0x4c, 0xc0889bf8f0?}, {0xc0ddbdb000, 0x4, 0x4}, {0xc0eab35fc0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio/read.go:158 +0x569
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio.BlockRead({0x2d9bb38, 0xc0580de780}, 0xc08b95ac00, {0xc08ba59400, 0x4c, 0x80}, {0xc0ddbdb000, 0x4, 0x4}, {0xc0eab35fc0, ...}, ...)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/tae/blockio/read.go:55 +0x386
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*blockMergeReader).Read(0xc08b9564b0, {0x2d9bb38, 0xc0554af260}, {0xc08b92df80, 0x4, 0x4}, 0x2dc38c0?, 0xc0554af3e0?, {0x2d8a758, 0xc08b96c780})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/reader.go:416 +0x770
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read(0xc091747920, {0x2d9bb38, 0xc0554af260}, {0xc08b92df80, 0x4, 0x4}, 0xc08b967478?, 0x24f95a0?, {0x2d8a758, 0xc08b96c780})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/reader.go:455 +0x10c
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*mergeReader).Read(0xc0c65eff68, {0x2d9bb38, 0xc0554af260}, {0xc08b92df80, 0x4, 0x4}, 0x2607b80?, 0x7f8cf80373e8?, {0x2d8a758, 0xc08b96c780})
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/reader.go:455 +0x10c
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).Run(0xc0889bff10, {0x2d8a488, 0xc0c65eff68}, 0xc08b96c780)
	/go/src/github.com/matrixorigin/matrixone/pkg/vm/pipeline/pipeline.go:79 +0x2bd
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run(0xc08b923d40, 0xc08608bb00?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:83 +0x16e
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1(0x0?)
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:108 +0x26
created by github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
	/go/src/github.com/matrixorigin/matrixone/pkg/sql/compile/scope.go:108 +0x258

the whole log is in s3. and the path will update soon

[cn-crash-len_out_of_range.log](https://github.com/matrixorigin/matrixone/files/11673312/cn-crash-len_out_of_range.log)

### Expected Behavior

the cn should never crash 

### Steps to Reproduce

```Markdown
1. run a cluster on eks with 2*cn using the same config
2. run tpcc 10 warehouse 100 terminals for about more than 20 minutes
```

**Comment by volgariver6** [comment]
@triump2020 please check this issue.

**Comment by aressu1985** [comment]
log path: s3://mo-ares/etl/etl_20230607083208/

**Comment by triump2020** [comment]
@aressu1985   duplicate with #9862

**Comment by triump2020** [comment]
PR is on the way.

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/issues/9954

**Comment by triump2020** [comment]
I will push the PR at 6.14

**Comment by triump2020** [comment]
@aressu1985  after [PR](https://github.com/matrixorigin/matrixone/pull/10050) merged, pls test.

**Comment by aressu1985** [comment]
testing
