### ISSUE TITLE
[Bug]: mo cloud instance load s3 has no primary key column and the data speed is very slow

### ISSUE THREAD

**Issue by tianyahui-python** [matrixorigin/matrixone#9900]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

Instability reappears bug:

See Related Issues for a detailed description: https://github.com/matrixorigin/MO-Cloud/issues/819

**Comment by volgariver6** [comment]
An improvement has been done, so please retest with new binary, at least after commit f03f12ad0bdb8726fc42872e083adf5a5051600f.

**Comment by DanielZhangQD** [comment]
Verified with commit `nightly-922d082a` and MO hung with the following loading SQL:
```
MySQL [(none)]> load data url s3option {"bucket"='mocloud-sample-us-west-2', "filepath"='tpchs1/partsupp.tbl.gz', "compression"='gzip'} into table mo_sample_data_tpch_sf1.partsupp FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
```

**Comment by tianyahui-python** [comment]
Please test yourself and then turn to the qa team @jianwan0214 @volgariver6

**Comment by zhangxu19830126** [comment]
修改cn的如下配置测试：
[cn.auto-increment]
count-per-allocate = 100000

**Comment by tianyahui-python** [comment]
> 由于我们现在点更新的性能非常差，之前对于load的优化是针对core很多的时候，并啊大的时候，性能提升明显，但是mo-cloud的cn机器core只有8核心，性能提升不明显。目前只能依靠修改默认的自增列的缓存大小来解决。

感觉这个只是定位到了root cause, 而且提供了一种修改配置的解决方案, 并未真正的解决这个问题, 待讨论...

**Comment by aressu1985** [comment]
tracking

**Comment by aressu1985** [comment]
tracking

**Comment by aressu1985** [comment]
not working on it
