### ISSUE TITLE
[Bug]:  ci bvt failed：insert into table reported constraint violation: Column '__mo_fake_pk_col' cannot be null

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9914]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):de445f3bd38ffc45a8c6932ef192529bd398a94c
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job：https://github.com/matrixorigin/matrixone/actions/runs/5196971492/jobs/9371251074?pr=9461
![image](https://github.com/matrixorigin/matrixone/assets/113406637/87370b25-6fb4-4e8d-b85f-8d9d696490fb)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/4ecc1432-e526-4f56-9d1d-fd71b05c691b)

log：
[multi-cn-e2e-push-docker-compose-log.zip](https://github.com/matrixorigin/matrixone/files/11675895/multi-cn-e2e-push-docker-compose-log.zip)

**Comment by heni02** [comment]
related #9735

**Comment by volgariver6** [comment]
@ouyuanning please help to check this one.

**Comment by heni02** [comment]
local reproduce：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/c49684bb-5b23-445a-b9e1-dcf200543227)

![image](https://github.com/matrixorigin/matrixone/assets/113406637/2e159377-e75c-4f80-bcd0-852a0a49cc6d)

drop table if exists atomic_table_11;
create table atomic_table_11(c1 int,c2 varchar(25));
insert into atomic_table_11 values (3,"a"),(4,"b"),(5,"c");
begin;
drop table atomic_table_11;

-- @session:id=2&user=sys:dump&password=111
-- @wait:0:commit
insert into atomic_table_11 values (6,"a");
select * from atomic_table_11;
-- @session

commit;

**Comment by qingxinhome** [comment]
Positioning

**Comment by qingxinhome** [comment]
The problem has not recurred, continuing to locate

**Comment by qingxinhome** [comment]
The problem has not recurred, continuing to locate

**Comment by qingxinhome** [comment]
The problem has not recurred, continuing to locate

**Comment by qingxinhome** [comment]
The problem has not recurred, continuing to locate

**Comment by heni02** [comment]
Unable to locate the cause of the problem. there is no recurrence after regression,  close it first and label it as  need-review
