### ISSUE TITLE
[Bug]: mo was hung on eks with 3*cns during loading ssb data

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9935]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 3cdceab
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 8G
- OS type:
- Others:
  CN DISK CACHE: 100G
  CN MEM  CACHE: 16G
```

### Actual Behavior

<img width="1371" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/b621b596-469b-4c87-92d2-5121fa497b09">

log:
[hung-cn0.log](https://github.com/matrixorigin/matrixone/files/11685229/hung-cn0.log)
[hung-cn1.log](https://github.com/matrixorigin/matrixone/files/11685231/hung-cn1.log)
[hung-cn2.log](https://github.com/matrixorigin/matrixone/files/11685234/hung-cn2.log)
[hung-dn0.log](https://github.com/matrixorigin/matrixone/files/11685236/hung-dn0.log)

### Steps to Reproduce

```Markdown
1、run a mo cluster on eks with 3*cn
2、load ssb data
```

**Comment by guguducken** [comment]
comment from @jianwang0214: no progress~

**Comment by sukki37** [comment]
part of this issue is related to https://github.com/matrixorigin/matrixone/issues/9914

**Comment by guguducken** [comment]
no progress

**Comment by aressu1985** [comment]
fixed:nightly-d4d74e7

**Comment by aressu1985** [comment]
happen again in this job link:
https://github.com/matrixorigin/matrixone/actions/runs/5585142750/jobs/10207988275

**Comment by ouyuanning** [comment]
not working on this today

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
waiting for repro in daily run.

**Comment by aressu1985** [comment]
downgrade to s-1

**Comment by sukki37** [comment]
This issue has been inactive for a while. To help keep our backlog clear, I'm going to close this. If you feel this is still relevant, please comment or reopen.
