### ISSUE TITLE
[Feature Request]: set global command should only be effective within the current account

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9942]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
sql_mode is changed by acc_1:root on mo-tp-cn-0, however sql_mode is changed too when acc_2:root logins to mo-tp-cn-0. Normally speaking, acc_2 should not have access to the same cngroup as acc_1 does, but it is currently working, so that brings us an issue.
```

### Describe the feature you'd like

`set global` command should only be effective within the current account, that is, should not take any effect on users from another account, no matter if users from another account have access to the same cn group as users from current account do or not.

### Describe implementation you've considered

See above

### Documentation, Adoption, Use Case, Migration Strategy

```Markdown
See above
```

### Additional information

This feature is related to issue https://github.com/matrixorigin/matrixone/issues/9696

**Comment by dengn** [comment]
for doc side, there is nothing to document. Because this is supposed be the right behavior, it's more about bug fixing.

**Comment by aronchanisme** [comment]
Testing

**Comment by aronchanisme** [comment]
Fixed 
https://github.com/matrixorigin/matrixone/issues/9696#issuecomment-1636709725
