### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode:  unable to connect mo after running transaction cases

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9945]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):767517b81caf4a05b3c0885eaadb52d30700ce94
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

local start mode:./mo-service -launch ./etc/launch-tae-CN-tae-DN/launch.toml 
after running about transaction cases, mo can not login
![image](https://github.com/matrixorigin/matrixone/assets/113406637/47255577-4e8d-4daa-a619-9f20bc62a8f8)

log :
[mysql] 2023/06/08 17:58:09 packets.go:37: read tcp 127.0.0.1:65157->127.0.0.1:6001: i/o timeout
2023/06/08 17:58:09.575665 +0800 ERROR disttae/logtailPushModel.go:137 new txn failed because lack of enough log tail. txn time is [PhysicalTime:1686218229553728000 LogicalTime:1 ]
2023/06/08 17:58:09.575816 +0800 ERROR disttae/logtailPushModel.go:138 error: transaction error: new txn failed. please retry {"span": {"trace_id": "d55e4518-05e2-11ee-b65f-96f0c1a980fe", "kind": "statement"}}
2023/06/08 17:58:09.575867 +0800 ERROR frontend/util.go:434 GetTxn. error:transaction error: new txn failed. please retry connectionId 4294967295||{account sys:root:moadmin -- 0:0:0}|d55e40ae-05e2-11ee-b65f-96f0c1a980fe|d55e3730-05e2-11ee-b65f-96f0c1a980fe
2023/06/08 17:58:09.575915 +0800 ERROR plan/query_builder.go:2047 error: SQL parser error: table "mo_mysql_compatibility_mode" does not exist {"span": {"trace_id": "d55e4518-05e2-11ee-b65f-96f0c1a980fe", "kind": "statement"}}
2023/06/08 17:58:09.575949 +0800 ERROR frontend/util.go:419 SQL parser error: table "mo_mysql_compatibility_mode" does not exist {"session_info": "connectionId 4294967295||{account sys:root:moadmin -- 0:0:0}|d55e40ae-05e2-11ee-b65f-96f0c1a980fe|d55e3730-05e2-11ee-b65f-96f0c1a980fe"}
2023/06/08 17:58:09.576016 +0800 ERROR frontend/util.go:419 query trace status {"connection_id": 4294967295, "statement": "select variable_name, variable_value from mo_catalog.mo_mysql_compatibility_mode where account_id = 0 and system_variables = true", "status": "fail", "error": "SQL parser error: table \"mo_mysql_compatibility_mode\" does not exist", "span": {"trace_id": "d55e4518-05e2-11ee-b65f-96f0c1a980fe", "kind": "statement"}, "session_info": "connectionId 4294967295||{account sys:root:moadmin -- 0:0:0}|d55e40ae-05e2-11ee-b65f-96f0c1a980fe|d55e3730-05e2-11ee-b65f-96f0c1a980fe"}
2023/06/08 17:58:09.576254 +0800 INFO frontend/util.go:424 handle handshake end connectionId 915|127.0.0.1:65055
2023/06/08 17:58:09.576306 +0800 INFO frontend/util.go:424 handle handshake response ok connectionId 915|127.0.0.1:65055
2023/06/08 17:58:09.576372 +0800 ERROR frontend/mysql_cmd_executor.go:3501 error: internal error: client send quit {"span": {"trace_id": "d55e3730-05e2-11ee-b65f-96f0c1a980fe", "kind": "session"}}
2023/06/08 17:58:09.576394 +0800 ERROR frontend/util.go:434 rt execute request failed. error:internal error: client send quit
 connectionId 915|127.0.0.1:65055|{account sys:bcbd235b-41b3-49ad-8cb6-1d05774d28c6:moadmin -- 0:4294967295:0}|goRoutineId 1082634|d55e3730-05e2-11ee-b65f-96f0c1a980fe
2023/06/08 17:58:09.576413 +0800 ERROR frontend/util.go:434 error:internal error: client send quit connectionId 915|127.0.0.1:65055
2023/06/08 17:58:09.576428 +0800 ERROR v2@v2.0.3-0.20230520035916-bc1fed6f5e26/application.go:383 session handle failed, close this session {"listen-addresses": "[0.0.0.0:6001]", "session-id": 906, "addr": "127.0.0.1:65055", "error": "internal error: client send quit"}
2023/06/08 17:58:09.576444 +0800 ERROR v2@v2.0.3-0.20230520035916-bc1fed6f5e26/application.go:345 handle session failed {"listen-addresses": "[0.0.0.0:6001]", "error": "internal error: client send quit"}
[mysql] 2023/06/08 17:58:14 packets.go:37: read tcp 127.0.0.1:65168->127.0.0.1:6001: i/o timeout
2023/06/08 17:58:14.555911 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:487 task done failed, retry later {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "task": "StorageUsage:1/3", "error": "invalid state task store not ready"}
2023/06/08 17:58:14.555947 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:528 task heartbeat failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "invalid state task store not ready"}
2023/06/08 17:58:14.555939 +0800 ERROR cn-service.task-runner taskservice/task_runner.go:284 fetch task failed {"uuid": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "runner-id": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "error": "invalid state task store not ready"}

case:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/f44aec8a-31b2-4064-ba1a-be5e91fd2c0a)

log:
[log.zip](https://github.com/matrixorigin/matrixone/files/11687187/log.zip)

### Steps to Reproduce

case:
[trans_case.zip](https://github.com/matrixorigin/matrixone/files/11687243/trans_case.zip)

**Comment by m-schen** [comment]
今天请假了 没看

**Comment by m-schen** [comment]
暂时没有时间看。

**Comment by m-schen** [comment]
还没有跟踪该issue

**Comment by m-schen** [comment]
无进度。

**Comment by m-schen** [comment]
在最新的main (commit: 8e113619ff0f98d6e1efc083760bcafe575a49ce) 验证已经没有该问题了。
该bug应该与之前logtail重连的问题有关。
可以验证一下

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
Latest main commit :dad0e2cb083156805a29ac9287a837537637e710 ，There is no recurrence of this issue，closed
