### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode:  drop table reported error ExpectedEOB

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9948]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):767517b81caf4a05b3c0885eaadb52d30700ce94
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

drop table wait lock release ,after session1 commit,drop table reported ExpectedEOB, it should execute success 
![image](https://github.com/matrixorigin/matrixone/assets/113406637/9189c8b7-2a4f-4473-ba5b-53bd075488b8)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b026b61e-4ad5-4c12-9b5a-fd0cbc1aca85)

### Steps to Reproduce

```Markdown
create table atomic_table_15(c1 int,c2 varchar(25));
begin;
insert into atomic_table_15 values (6,"a"),(7,"b");
truncate table atomic_table_15;
-- @session:id=2&user=sys:dump&password=111
-- @wait:0:commit
drop table atomic_table_15;
-- @session
select * from atomic_table_15;
commit;
```

**Comment by volgariver6** [comment]
@nnsgmsone please help on this issue.

**Comment by volgariver6** [comment]
I will take this one.

**Comment by volgariver6** [comment]
fixed.
