### ISSUE TITLE
[Bug]: loading tpcc table bmsql_history_tpcc with 10 warhouse scale failed by w-w confilict on eks with 3*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9950]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-29f1e83
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 8G
- OS type:
- Others:
  DISK CACHE: 100G
  MEM CACHE: 12G
```

### Actual Behavior

2023-06-08 11:58:42 [s3_bmsql_history_tpcc_10w]
2023-06-08 11:58:42 Start to load data from file tpcc_10/cust-hist.csv into table tpcc_10.bmsql_history,please wait.....
2023-06-08 11:58:42 load data url s3option {'bucket'='mo-load-data', 'filepath'='tpcc_10/cust-hist.csv'} into table tpcc_10.bmsql_history fields terminated by ',' lines terminated by '
' parallel 'true';
Warning: 8 11:58:44 mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 20619 (HY000) at line 1: w-w conflict
2023-06-08 11:[58](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5209252954/jobs/9402001471#step:13:59):44 The data for table tpcc_10.bmsql_history has failed to be loaded.
2023-06-08 11:58:44 This test for [s3_bmsql_history_tpcc_10w] has been executed failed, more info, please see the log

the log is in s3. path:  **s3://mo-ares/mo-benchmark/etl/**

### Steps to Reproduce

```Markdown
1. run a mo cluster on eks with 3*cn 
2. laod data with sql:
   load data url s3option {'bucket'='mo-load-data', 'filepath'='tpcc_10/cust-hist.csv'} into table tpcc_10.bmsql_history fields terminated by ',' lines terminated by '
' parallel 'true';
```

**Comment by volgariver6** [comment]
@triump2020 will handle this one.

**Comment by triump2020** [comment]
https://github.com/matrixorigin/matrixone/pull/9973

**Comment by aressu1985** [comment]
@triump2020 this issue already exists. 
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5269447400/jobs/9529619132

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
need to know the logical for incrementing column

**Comment by triump2020** [comment]
being reproduce

**Comment by triump2020** [comment]
no progress

**Comment by triump2020** [comment]
on vacation

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
blocked

**Comment by triump2020** [comment]
It can't be reproduced , may be fixed .  @aressu1985 pls close it or downgrade.
 
![1690386614630](https://github.com/matrixorigin/matrixone/assets/63033222/30363658-7475-49ce-b00e-5e23d276128b)

![1690386659954](https://github.com/matrixorigin/matrixone/assets/63033222/95a7bae8-36d9-484e-a044-c4c1a5a04e02)

**Comment by aressu1985** [comment]
fixed
