### ISSUE TITLE
[Bug]: bvt case : select count(1) as cnt, statement_id, statement, status from xxx failed after mo restarted

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9951]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 6a29f4e
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

023-06-08 11:06:55 ERROR RSSet:140 - The row count does not equal with each other, one is 0, the other is 2313
2023-06-08 11:06:55 ERROR Executor:159 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/log/query_version.sql][row:11][select count(1) as cnt, statement_id, statement, status from system.statement_info group by statement_id, statement, status having count(1) > 1;] was executed failed, con[id=0, user=dump, ***
2023-06-08 11:06:55 ERROR Executor:161 - [EXPECT RESULT]:
cnt    statement_id    statement    status
2023-06-08 11:06:55 ERROR Executor:162 - [ACTUAL RESULT]:
cnt    statement_id    statement    status
2    0c760248-05eb-11ee-86ce-6045bde3b633    drop table if exists t1    Success
2    0c7607c7-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c762fc9-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c7667fe-05eb-11ee-86ce-6045bde3b633    CREATE TABLE t1 (a timestamp(6))    Success
2    0c766f3f-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7692e9-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "*"    Success
2    0c787ff1-05eb-11ee-86ce-6045bde3b633    INSERT INTO t1 VALUES ('2022-03-01 00:00:01.0001')    Success
2    0c788b1a-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 31\n					and rp.privilege_level = "*.*"    Success
2    0c78f785-05eb-11ee-86ce-6045bde3b633    drop table t1    Success
2    0c7905e8-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c793146-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c79f062-05eb-11ee-86ce-6045bde3b633    drop table if exists t1    Success
2    0c79f937-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7a2010-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c7aa4bb-05eb-11ee-86ce-6045bde3b633    drop table if exists t2    Success
2    0c7aaacb-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7ad122-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c7b0e99-05eb-11ee-86ce-6045bde3b633    drop table if exists t3    Success
2    0c7b15d1-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7b3c82-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c7b679b-05eb-11ee-86ce-6045bde3b633    drop table if exists t21    Success
2    0c7b6d76-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7c21f6-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c7c7bf2-05eb-11ee-86ce-6045bde3b633    drop table if exists t12    Success
2    0c7c833d-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7cae3e-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c7cff7b-05eb-11ee-86ce-6045bde3b633    CREATE TABLE t1 (a timestamp, b int primary key)    Success
2    0c7d05d1-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "d"\n					and d.datname = "timestamp"    Success
2    0c7d2b6a-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "*"    Success
2    0c7df0f9-05eb-11ee-86ce-6045bde3b633    INSERT INTO t1 VALUES ('2022-01-01 00:00:00',1),('2022-01-01 00:00:00',2)    Success
2    0c7dfc4f-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 31\n					and rp.privilege_level = "*.*"    Success
2    0c7e6a3c-05eb-11ee-86ce-6045bde3b633    update t1 set a='2022-01-02' where a='2022-01-01 00:00:00' limit 1    Success
2    0c7ebdf3-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 32\n					and rp.privilege_level = "*.*"    Success
2    0c7f3f1e-05eb-11ee-86ce-6045bde3b633    select * from t1    Success
2    0c7f4b46-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 30\n					and rp.privilege_level = "*.*"    Success
2    0c7f794f-05eb-11ee-86ce-6045bde3b633    INSERT INTO t1 VALUES ('2022-01-01 00:00:00',3)    Success
2    0c9d952b-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 34\n					and rp.privilege_level = "*.*"    Success
2    0c9e2a29-05eb-11ee-86ce-6045bde3b633    select * from t1 order by a asc    Success
2    0c9e50d6-05eb-11ee-86ce-6045bde3b633    drop table t1    Success
2    0c9e56d0-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "tinyint"    Success
2    0c9e7be1-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0c9f66ed-05eb-11ee-86ce-6045bde3b633    create table t1 ( a tinyint not null default 1, tinyint8 tinyint primary key)    Success
2    0c9f6d2a-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "d"\n					and d.datname = "tinyint"    Success
2    0c9f9745-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "*"    Success
2    0ca03d67-05eb-11ee-86ce-6045bde3b633    insert into t1 (tinyint8) values (-1),(127),(-128)    Success
2    0ca047fe-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 31\n					and rp.privilege_level = "*.*"    Success
2    0ca0df8c-05eb-11ee-86ce-6045bde3b633    select * from t1 order by a desc, 2 asc    Success
2    0ca12798-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 30\n					and rp.privilege_level = "*.*"    Success
2    0ca171cf-05eb-11ee-86ce-6045bde3b633    select min(tinyint8),max(tinyint8),max(tinyint8)-1 from t1    Success
2    0ca1f362-05eb-11ee-86ce-6045bde3b633    select min(tinyint8),max(tinyint8),max(tinyint8)-1 from t1 group by a order by 1    Success
2    0ca281b8-05eb-11ee-86ce-6045bde3b633    drop table t1    Success
2    0ca28c4c-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "tinyint"    Success
2    0ca30f1e-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0caa5b9e-05eb-11ee-86ce-6045bde3b633    create table t1 ( a tinyint not null default 1, tinyint8 tinyint unsigned primary key)    Success
2    0caa6714-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "d"\n					and d.datname = "tinyint"    Success
2    0cab2c24-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 20\n					and rp.privilege_level = "*"    Success
2    0cadde25-05eb-11ee-86ce-6045bde3b633    insert into t1 (tinyint8) values (0),(255), (0xFE), (253)    Success
2    0cae05d9-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 31\n					and rp.privilege_level = "*.*"    Success
2    0cb034d4-05eb-11ee-86ce-6045bde3b633    select * from t1 order by 2 asc    Success
2    0cb092b3-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "table"\n					and rp.role_id = 0\n					and rp.privilege_id = 30\n					and rp.privilege_level = "*.*"    Success
2    0cb1064e-05eb-11ee-86ce-6045bde3b633    select * from t1 order by tinyint8 limit 1,3    Success
2    0cb141c4-05eb-11ee-86ce-6045bde3b633    select * from t1 order by tinyint8 limit 3 offset 1    Success
2    0cb1a783-05eb-11ee-86ce-6045bde3b633    select min(tinyint8),max(tinyint8),max(tinyint8)-1 from t1    Success
2    0cb1dc00-05eb-11ee-86ce-6045bde3b633    select min(tinyint8),max(tinyint8),max(tinyint8)-1 from t1 group by a order by abs(1)    Success
2    0cb2441e-05eb-11ee-86ce-6045bde3b633    drop table t1    Success
2    0cb24d83-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_database d, mo_catalog.mo_role_privs rp\n				where d.dat_id = rp.obj_id\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "d"\n					and d.datname = "tinyint"    Success
2    0cb28c77-05eb-11ee-86ce-6045bde3b633    select rp.privilege_id,rp.with_grant_option\n				from mo_catalog.mo_role_privs rp\n				where rp.obj_id = 0\n					and rp.obj_type = "database"\n					and rp.role_id = 0\n					and rp.privilege_id = 23\n					and rp.privilege_level = "*"    Success
2    0cb614b8-05eb-11ee-86ce-6045bde3b633    create table t1 (id tinyint primary key, a tinyint)    Success

the log is on this link:
https://github.com/matrixorigin/matrixone/actions/runs/5210323989

**Comment by xzxiong** [comment]
same as https://github.com/matrixorigin/matrixone/issues/9891

**Comment by gavinyue** [comment]
Pending for the stmt_aggr pr merge. Stuck on dn oom

**Comment by aressu1985** [comment]
fixed
