### ISSUE TITLE
[Bug]: bvt case show grants; result error after mo restarted

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9952]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): d42c5c9
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

2023-06-08 10:49:56 ERROR RSRow:65 - The value of [row:32,column:0] does not equal with each other,one is [GRANT values ON table *.* `dump`@`localhost`],but the other is [GRANT values ON table t `dump`@`localhost`]
2023-06-08 10:49:56 ERROR Executor:159 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/dml/show/show.test][row:52][show grants;] was executed failed, con[id=0, user=dump, ***
2023-06-08 10:49:56 ERROR Executor:161 - [EXPECT RESULT]:
Grants for dump@localhost
GRANT create account ON account  `dump`@`localhost`
GRANT drop account ON account  `dump`@`localhost`
GRANT alter account ON account  `dump`@`localhost`
GRANT create user ON account  `dump`@`localhost`
GRANT drop user ON account  `dump`@`localhost`
GRANT alter user ON account  `dump`@`localhost`
GRANT create role ON account  `dump`@`localhost`
GRANT drop role ON account  `dump`@`localhost`
GRANT create database ON account  `dump`@`localhost`
GRANT drop database ON account  `dump`@`localhost`
GRANT show databases ON account  `dump`@`localhost`
GRANT connect ON account  `dump`@`localhost`
GRANT manage grants ON account  `dump`@`localhost`
GRANT account all ON account  `dump`@`localhost`
GRANT show tables ON database * `dump`@`localhost`
GRANT create table ON database * `dump`@`localhost`
GRANT drop table ON database * `dump`@`localhost`
GRANT alter table ON database * `dump`@`localhost`
GRANT create view ON database * `dump`@`localhost`
GRANT drop view ON database * `dump`@`localhost`
GRANT alter view ON database * `dump`@`localhost`
GRANT database all ON database * `dump`@`localhost`
GRANT database ownership ON database * `dump`@`localhost`
GRANT select ON table *.* `dump`@`localhost`
GRANT insert ON table *.* `dump`@`localhost`
GRANT update ON table *.* `dump`@`localhost`
GRANT truncate ON table *.* `dump`@`localhost`
GRANT delete ON table *.* `dump`@`localhost`
GRANT reference ON table *.* `dump`@`localhost`
GRANT index ON table *.* `dump`@`localhost`
GRANT table all ON table *.* `dump`@`localhost`
GRANT table ownership ON table *.* `dump`@`localhost`
GRANT values ON table *.* `dump`@`localhost`
GRANT connect ON account  `dump`@`localhost`
2023-06-08 10:49:56 ERROR Executor:162 - [ACTUAL RESULT]:
Grants for dump@localhost
GRANT create account ON account  `dump`@`localhost`
GRANT drop account ON account  `dump`@`localhost`
GRANT alter account ON account  `dump`@`localhost`
GRANT create user ON account  `dump`@`localhost`
GRANT drop user ON account  `dump`@`localhost`
GRANT alter user ON account  `dump`@`localhost`
GRANT create role ON account  `dump`@`localhost`
GRANT drop role ON account  `dump`@`localhost`
GRANT create database ON account  `dump`@`localhost`
GRANT drop database ON account  `dump`@`localhost`
GRANT show databases ON account  `dump`@`localhost`
GRANT connect ON account  `dump`@`localhost`
GRANT manage grants ON account  `dump`@`localhost`
GRANT account all ON account  `dump`@`localhost`
GRANT show tables ON database * `dump`@`localhost`
GRANT create table ON database * `dump`@`localhost`
GRANT create view ON database * `dump`@`localhost`
GRANT drop table ON database * `dump`@`localhost`
GRANT drop view ON database * `dump`@`localhost`
GRANT alter table ON database * `dump`@`localhost`
GRANT alter view ON database * `dump`@`localhost`
GRANT database all ON database * `dump`@`localhost`
GRANT database ownership ON database * `dump`@`localhost`
GRANT select ON table *.* `dump`@`localhost`
GRANT insert ON table *.* `dump`@`localhost`
GRANT update ON table *.* `dump`@`localhost`
GRANT truncate ON table *.* `dump`@`localhost`
GRANT delete ON table *.* `dump`@`localhost`
GRANT reference ON table *.* `dump`@`localhost`
GRANT index ON table *.* `dump`@`localhost`
GRANT table all ON table *.* `dump`@`localhost`
GRANT table ownership ON table *.* `dump`@`localhost`
GRANT values ON table t `dump`@`localhost`
GRANT connect ON account  `dump`@`localhost`
2023-06-08 10:49:56 ERROR RSRow:65 - The value of [row:32,column:0] does not equal with each other,one is [GRANT values ON table *.* `root`@`localhost`],but the other is [GRANT values ON table t `root`@`localhost`]
2023-06-08 10:49:56 ERROR Executor:159 - [/home/runner/work/matrixone/matrixone/head/test/distributed/cases/dml/show/show.test][row:53][show grants for 'root'@'localhost';] was executed failed, con[id=0, user=dump, ***
2023-06-08 10:49:56 ERROR Executor:161 - [EXPECT RESULT]:
Grants for root@localhost
GRANT create account ON account  `root`@`localhost`
GRANT drop account ON account  `root`@`localhost`
GRANT alter account ON account  `root`@`localhost`
GRANT create user ON account  `root`@`localhost`
GRANT drop user ON account  `root`@`localhost`
GRANT alter user ON account  `root`@`localhost`
GRANT create role ON account  `root`@`localhost`
GRANT drop role ON account  `root`@`localhost`
GRANT create database ON account  `root`@`localhost`
GRANT drop database ON account  `root`@`localhost`
GRANT show databases ON account  `root`@`localhost`
GRANT connect ON account  `root`@`localhost`
GRANT manage grants ON account  `root`@`localhost`
GRANT account all ON account  `root`@`localhost`
GRANT show tables ON database * `root`@`localhost`
GRANT create table ON database * `root`@`localhost`
GRANT drop table ON database * `root`@`localhost`
GRANT alter table ON database * `root`@`localhost`
GRANT create view ON database * `root`@`localhost`
GRANT drop view ON database * `root`@`localhost`
GRANT alter view ON database * `root`@`localhost`
GRANT database all ON database * `root`@`localhost`
GRANT database ownership ON database * `root`@`localhost`
GRANT select ON table *.* `root`@`localhost`
GRANT insert ON table *.* `root`@`localhost`
GRANT update ON table *.* `root`@`localhost`
GRANT truncate ON table *.* `root`@`localhost`
GRANT delete ON table *.* `root`@`localhost`
GRANT reference ON table *.* `root`@`localhost`
GRANT index ON table *.* `root`@`localhost`
GRANT table all ON table *.* `root`@`localhost`
GRANT table ownership ON table *.* `root`@`localhost`
GRANT values ON table *.* `root`@`localhost`
GRANT connect ON account  `root`@`localhost`
2023-06-08 10:49:56 ERROR Executor:162 - [ACTUAL RESULT]:
Grants for root@localhost
GRANT create account ON account  `root`@`localhost`
GRANT drop account ON account  `root`@`localhost`
GRANT alter account ON account  `root`@`localhost`
GRANT create user ON account  `root`@`localhost`
GRANT drop user ON account  `root`@`localhost`
GRANT alter user ON account  `root`@`localhost`
GRANT create role ON account  `root`@`localhost`
GRANT drop role ON account  `root`@`localhost`
GRANT create database ON account  `root`@`localhost`
GRANT drop database ON account  `root`@`localhost`
GRANT show databases ON account  `root`@`localhost`
GRANT connect ON account  `root`@`localhost`
GRANT manage grants ON account  `root`@`localhost`
GRANT account all ON account  `root`@`localhost`
GRANT show tables ON database * `root`@`localhost`
GRANT create table ON database * `root`@`localhost`
GRANT create view ON database * `root`@`localhost`
GRANT drop table ON database * `root`@`localhost`
GRANT drop view ON database * `root`@`localhost`
GRANT alter table ON database * `root`@`localhost`
GRANT alter view ON database * `root`@`localhost`
GRANT database all ON database * `root`@`localhost`
GRANT database ownership ON database * `root`@`localhost`
GRANT select ON table *.* `root`@`localhost`
GRANT insert ON table *.* `root`@`localhost`
GRANT update ON table *.* `root`@`localhost`
GRANT truncate ON table *.* `root`@`localhost`
GRANT delete ON table *.* `root`@`localhost`
GRANT reference ON table *.* `root`@`localhost`
GRANT index ON table *.* `root`@`localhost`
GRANT table all ON table *.* `root`@`localhost`
GRANT table ownership ON table *.* `root`@`localhost`
GRANT values ON table t `root`@`localhost`
GRANT connect ON account  `root`@`localhost`

the mo log is in this link:
https://github.com/matrixorigin/matrixone/actions/runs/5210230190/jobs/9401043320

**Comment by volgariver6** [comment]
@daviszhen please help to check this issue.

**Comment by daviszhen** [comment]
@aressu1985 这个pr还在合并过程中。还没merge。https://github.com/matrixorigin/matrixone/pull/9927
