### ISSUE TITLE
[Feature Request]: LOAD INTO VALUES

### ISSUE THREAD

**Issue by fengttt** [matrixorigin/matrixone#9955]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
SQL has the following syntax, insert into t with many rows.
insert into t values (1, 2), (3, 4), ...

Potentially we can extend sql with our own binary 
insert into t binary values [format] ['protocolbuffer', 'matrixone'] 0x'XXXXXXXX';

format matrixone, the 0x'XXXX' is simply a serialized matrixone batch.
format protocol buffer can use a simple protocol buffer format of batch.

It can be prepared, insert into t binary values format 'protocolbuffer' ?
then people serialize a protocol buffer and execute it.
```

### Describe the feature you'd like

We can either publish protocolbuffer definition and let user serialize it, or, we can publish our own client software and 
turn insert into ... values ... into insert into ... binary values ...

Our own client driver is definitely much less intrusive to customer but that means we need to fork/maintain jdbc, python client, etc.    And that is intrusive in a different way.

I think protocol buffer has enough language bindings that we can simply use that.    Or parquet/arrow.   Note that we may need to support parquet/arrow anyway as part of external table work.

But our internal use (logging) can simply use our own batch format

**Comment by dengn** [comment]
Doc related questions:
1. what's even the priority for this feature?
2. it seems to be such a big feature, needs specification about the real implementation.

**Comment by domingozhang** [comment]
USE new syntax  
LOAD INTO insert into t  values [format]

**Comment by fengttt** [comment]
Current load syntax,
```
load data infile 'path_to_file.csv' into table t;
```

We pretty much want an inline file -- that is, 
```
load data ...
inputdata = 'string values'
```

Or we can even overload current syntax
```
inputfile {path="inline", data="....", format="csv/json"}
```

**Comment by florashi181** [comment]
to clarify the syntax in this week. @domingozhang

**Comment by lacrimosaprinz** [comment]
related doc：

**Comment by nnsgmsone** [comment]
Completed by 11633
