### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode: alter table not wait for the lock release

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9959]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):767517b81caf4a05b3c0885eaadb52d30700ce94
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

alter table should wait for the lock  release 
<img width="852" alt="企业微信截图_29befe96-3c70-48fb-bd8d-59cd1801fd94" src="https://github.com/matrixorigin/matrixone/assets/113406637/da2deba4-7560-4765-93e2-15485606bbd7">

### Steps to Reproduce

```Markdown
drop table if exists atomic_table_17;
create table atomic_table_17(c1 int,c2 varchar(25));
begin;
insert into atomic_table_17 values (6,"a"),(7,"b");
drop table atomic_table_17;
-- @session:id=2&user=sys:dump&password=111
alter table atomic_table_17 add constraint unique key (c1);
update atomic_table_17 set c1=8 where c2="b";
-- @session
commit;
select * from atomic_table_17;
```

**Comment by volgariver6** [comment]
I will check it first.

**Comment by volgariver6** [comment]
@daviszhen maybe the alter table query need a lock operator, please help with it.

**Comment by daviszhen** [comment]
@jianwan0214  alter table 悲观锁。

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm, closed
commit id:2e13e0376571307fe0ea9f111ce4137fbcc1214d
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6b41b9d4-de4c-4fb4-9361-808c2b5aa0ab)
