### ISSUE TITLE
[Bug]: query timeout during "sysbench oltp update prepared" test on eks

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9982]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-29f1e83
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 16G
- OS type:
- Others:
  DISK CACHE: 100G
  MEM CACHE: 12G
```

### Actual Behavior

during sysbench oltp update prepared test on eks with 3*cn, the mo was hung.
<img width="1362" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/92f3bc21-a99a-4400-bce4-f8d63c20a493">

the log is in s3. path is **s3://mo-ares/etl/etl_20230611214431**

profile(cpu, heap, trace):

[10.0.161.78.zip](https://github.com/matrixorigin/matrixone/files/11716907/10.0.161.78.zip) cn
[10.0.184.117.zip](https://github.com/matrixorigin/matrixone/files/11716909/10.0.184.117.zip) cn
[10.0.190.64.zip](https://github.com/matrixorigin/matrixone/files/11716910/10.0.190.64.zip) dn

**Comment by aressu1985** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5236322354/jobs/9455565118

**Comment by LeftHandCold** [comment]
[goroutine.cn.tar.gz](https://github.com/matrixorigin/matrixone/files/11718764/goroutine.cn.tar.gz)

**Comment by sukki37** [comment]
@aptend, please help on identify the root cause of the issue, thank you.

**Comment by aptend** [comment]
> the log is in s3. path is s3://mo-ares/etl/etl_20230611214431

一些信息：
- 20:56 sysbench 出现卡住，但是之后并非完全卡死，21:26 有成功写入两个表的数据
- 20:58 之后 CN 不再有 csv 文件，21:03 之后 DN 不再有 csv 文件
- 20:55:12 DN 写 logtail 超时，链接断开，之后没有重连的日志
- `[10.0.161.78.zip]` 采样时间大概在 sysbench 连接断开前2、3分钟，从 `goroutine.log` 看 `bulkInsert` 的 goroutine 达到了 8000+，#9891 有跟踪该现象的原因，thanks @xzxiong 
- `sqlWriter WriteRowRecords failed above threshold` 日志总量有 1830 个，sqlDB 未被 close

**Comment by aptend** [comment]
今天在尝试复现重连问题

**Comment by aptend** [comment]
目前可供排查信息不足，暂时先降级

**Comment by aressu1985** [comment]
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5298998397/jobs/9593237022
this job has repro this issue, please check

**Comment by aressu1985** [comment]
repro
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5324816907/jobs/9654238888

**Comment by aptend** [comment]
https://github.com/matrixorigin/matrixone/pull/10174 之后未再出现

**Comment by aressu1985** [comment]
fixed
