### ISSUE TITLE
[Bug]: it will create a more than one reader of the same table in a tpcc txn statement

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#9983]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

CPU perf result:

[cpu.pb.gz](https://github.com/matrixorigin/matrixone/files/11716951/cpu.pb.gz)

Debug log clip: Same table, same txn and same statement. 

2023/06/12 02:20:25.184620 +0000 ERROR disttae/txn_table.go:1293 XXX %!%p0%!%bmsql_oorder NewReader Txn=ID:"\014\272\263\262\375LN\300\257y4\372\222_ \013" SnapshotTS:<PhysicalTime:1686536425180452708 LogicalTime:1 > PreparedTS:<> CommitTS:<> , StatementID=3, blks/mblk=0/15
2023/06/12 02:20:25.184632 +0000 ERROR disttae/txn_table.go:1293 XXX %!%p0%!%bmsql_oorder NewReader Txn=ID:"\014\272\263\262\375LN\300\257y4\372\222_ \013" SnapshotTS:<PhysicalTime:1686536425180452708 LogicalTime:1 > PreparedTS:<> CommitTS:<> , StatementID=3, blks/mblk=0/15

### Steps to Reproduce

```Markdown
Run tpcc with 10 warehouses 10 terminals
```

**Comment by dongdongyang33** [comment]
checking

**Comment by dongdongyang33** [comment]
it might have been fixed by Xiliang

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
This problem has been identified, but it has not been replicated. However, currently, Luo Fei has reconstructed the logic related to block reading on the CN side, and it is estimated that there will be no traces left. Can you close it first
