### ISSUE TITLE
[Bug]: cost of loading data increased very much on eks with 3*cn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9984]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): 922d082
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

<img width="1365" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/6d8df111-90bc-4c8d-95fe-7d89b6546292">

Because the regression test has been not succeed for several days ,so the cost data is compared to 6.7 or 6.7.
and during this time, another change is that the count of cn pod is from 2 to 3, but increaseing 1 cn , the cost of loading data should be decreased normally.

the mo log is in s3. path **s3://mo-ares/etl/etl_20230611214431**

### Expected Behavior

The cost of loading data should be decreased rather than increased as increasing a cn pod.

### Steps to Reproduce

```Markdown
1. run a mo cluster on eks with 3 CN using the same config
   the yaml file can view the repro:
   https://github.com/matrixorigin/mo-nightly-regression/blob/main/mo-bench.yaml
2. run loading data test using:
   load data url s3option {'bucket'='mo-load-data','filepath'='20_columns/100000000_20_columns_load_data.csv'} into table test.table_20_columns_1y fields terminated by ',' lines terminated by '\n' parallel 'true';
   load data url s3option {'bucket'='mo-load-data','filepath'='100_columns/100000000_100_columns_load_data.csv'} into table test.table_100_columns_1y fields terminated by ',' lines terminated by '\n' parallel 'true';
```

**Comment by sukki37** [comment]
Pls kindly follow up with this issue @jianwan0214

**Comment by guguducken** [comment]
no progress

**Comment by aressu1985** [comment]
fixed
