### ISSUE TITLE
[Bug]: improve delete handling in DN

### ISSUE THREAD

**Issue by XuPeng-SH** [matrixorigin/matrixone#9996]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

There are performance and memory problems with the current solution. We need to re-implement related logic.

**Comment by jiangxinmeng1** [comment]
it depends on #10241

**Comment by jiangxinmeng1** [comment]
it depends on #10418

**Comment by jiangxinmeng1** [comment]
it depends on https://github.com/matrixorigin/matrixone/issues/10418

**Comment by jiangxinmeng1** [comment]
it depends on https://github.com/matrixorigin/matrixone/issues/10418

**Comment by jiangxinmeng1** [comment]
it depends on https://github.com/matrixorigin/matrixone/issues/10418
