### ISSUE TITLE
[Bug]: pessimistic transaction and rc mode:  after deadlock  detected, truncate table was hung

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9997]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):c1e25e07ab82168ffd33ffc4f6e0c561ea472335
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

concurrent  100 update a table which include dead lock scene, some update sqls failed which can not connect mo, after test,mo can login succeed
sql :update r1 set  c1={tbx} where c1=20  ,tbx is random data
![image](https://github.com/matrixorigin/matrixone/assets/113406637/ac07f58b-733d-41e7-a32b-f4e9de04faf8)
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7f0bf430-8c79-4740-982d-155ba73c5435)

test error result:
[pessmatic transaction.log](https://github.com/matrixorigin/matrixone/files/11730273/pessmatic.transaction.log)

stack info:
[hung.log](https://github.com/matrixorigin/matrixone/files/11721680/hung.log)

### Steps to Reproduce

```Markdown
1cn mo, mysql login mo execute create table r1(c1 int)

use mo-load tool:
1.config case insert run.yaml,path : cases/ddl/run.yaml
vuser: 100
- sql: "insert into r1 values ({tbx});"
2. ./start.sh -c cases/ddl
3.config case update run.yaml,path:cases/ddl/run.yaml
vuser: 100
- sql: "update r1 set  c1={tbx} where c1=20;"
4. ./start.sh -c cases/ddl
```

**Comment by heni02** [comment]
@zhangxu19830126 plz confirm,  log is too large, I will send it to you

**Comment by zhangxu19830126** [comment]
it was fixed by #10001.

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
still has this problem
commit id： bd7b9730471b01d9f4197f1181b94b7fa1782f2e
cn config:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/743a238d-9bb2-403c-ab1d-e4f3820e4f92)
<img width="1489" alt="企业微信截图_1746f7c4-fa75-46c3-8139-fff467dadaac" src="https://github.com/matrixorigin/matrixone/assets/113406637/1040ea4c-54b0-4ba4-b864-4b363a5f8454">

**Comment by zhangxu19830126** [comment]
本地一直无法重现

**Comment by zhangxu19830126** [comment]
本地一直无法重现

**Comment by zhangxu19830126** [comment]
本地无法复现

**Comment by zhangxu19830126** [comment]
本地无法复现

**Comment by zhangxu19830126** [comment]
本地无法复现

**Comment by zhangxu19830126** [comment]
复现不了

**Comment by heni02** [comment]
commit :48a289863740d954b9e48fbc889fc100a1f85198 ，There is no recurrence of this issue
but one sql reported panic error
<img width="996" alt="企业微信截图_1829088c-2c6a-44a0-ac57-ec27903c7300" src="https://github.com/matrixorigin/matrixone/assets/113406637/70032215-2e0a-4b2a-8944-9f99bae40086">
DateTime : 2023-07-07 05:55:24
TxnName : pessmatic transaction
Statement : update r1 set  c1=858 where c1=20;
ErrorCode : 20101
ErrorMessage : internal error: panic put batch with zero cnt:
github.com/matrixorigin/matrixone/pkg/vm/process.(*Process).PutBatch
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/vm/process/process.go:239
github.com/matrixorigin/matrixone/pkg/sql/colexec/projection.Call
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/sql/colexec/projection/projection.go:81
github.com/matrixorigin/matrixone/pkg/vm.Run
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).MergeRun
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/vm/pipeline/pipeline.go:151
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/sql/compile/scope.go:146
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).run
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/sql/compile/compile.go:236
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Compile).runOnce.func1
        /Users/heni/test-envir/pessimic_mo/matrixone/pkg/sql/compile/compile.go:377
runtime.goexit
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172
Expected : false

log:
[log.txt](https://github.com/matrixorigin/matrixone/files/11980708/log.txt)

report:
[pessmatic transaction.txt](https://github.com/matrixorigin/matrixone/files/11980716/pessmatic.transaction.txt)

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
测了下。48a289863740d954b9e48fbc889fc100a1f85198 下。
RC+悲观。   10仓90线程，  开PK去重和不开PK去重都测试了2次。没有复现

**Comment by ouyuanning** [comment]
用本地，RC+悲观，mo-load 测了一下 单CN和多CN
没有复现。

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
the lastest version confirm, now reported panic: runtime error: invalid memory address or nil pointer dereference,plz confirm @zhangxu19830126 
commit id: 1c70e2f03c6577ce75bfe2119b09be7180f55ab5
<img width="1416" alt="企业微信截图_d5c2f667-ed3c-4611-ae38-61e2b3572729" src="https://github.com/matrixorigin/matrixone/assets/113406637/9861f4f0-a99a-4b2d-a230-ccda8377d902">
2023/08/02 15:13:46.039034 +0800 INFO compile/compile.go:926 delete of 'update r1 set  c1=32;' write s3

2023/08/02 15:13:46.045026 +0800 INFO log-service.lockservice runtime/panic.go:884 dead lock checker {"uuid": "7c4dccb4-4d3c-41f8-b482-5251dc7a41bf", "service": "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf", "cost": "48.066918458s"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1048f99b0]

goroutine 428 [running]:
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).fetchWhoWaitingMe.func2.1.1(0x40?)
	/Users/heni/test-envir/matrixone/pkg/lockservice/txn.go:246 +0x20
github.com/matrixorigin/matrixone/pkg/lockservice.(*sliceBasedWaiterQueue).iter(0x1400b209800, 0x14035450000)
	/Users/heni/test-envir/matrixone/pkg/lockservice/waiter_queue.go:99 +0xf8
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).fetchWhoWaitingMe.func2.1({{0x1403b28bec0, 0x10, 0x10}, 0xa, 0x1403f136000})
	/Users/heni/test-envir/matrixone/pkg/lockservice/txn.go:245 +0x110
github.com/matrixorigin/matrixone/pkg/lockservice.(*localLockTable).getLock(0x131a143d8?, {0x0?, 0x14023a056b8?, 0x104054f18?}, {0x1400c68b574?, 0x131a143d8?, 0x28?}, 0x1403542ffc0)
	/Users/heni/test-envir/matrixone/pkg/lockservice/lock_table_local.go:200 +0x140
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).fetchWhoWaitingMe.func2({0x1400c68b574, 0x3, 0x3})
	/Users/heni/test-envir/matrixone/pkg/lockservice/txn.go:241 +0x144
github.com/matrixorigin/matrixone/pkg/lockservice.(*fixedSlice).iter(0x14027dda570, 0x14023a05870)
	/Users/heni/test-envir/matrixone/pkg/lockservice/slice.go:159 +0x98
github.com/matrixorigin/matrixone/pkg/lockservice.(*activeTxn).fetchWhoWaitingMe(0x14017406f00, {0x14004a86b10, 0x24}, {0x1403b28bec0, 0x10, 0x10}, {0x1068c92a0, 0x1400ef396e0}, 0x14022932900, 0x14023a059d0)
	/Users/heni/test-envir/matrixone/pkg/lockservice/txn.go:240 +0x50c
github.com/matrixorigin/matrixone/pkg/lockservice.(*service).fetchTxnWaitingList(0x1400ec683c0, {{0x1403b28bec0, 0x10, 0x10}, {0x14039bc01e0, 0x24}, {}, {0x0, 0x0, 0x0}, ...}, ...)
	/Users/heni/test-envir/matrixone/pkg/lockservice/service.go:198 +0x1b0
github.com/matrixorigin/matrixone/pkg/lockservice.(*detector).checkDeadlock(0x1400028ff80, 0x1400f0288c0)
	/Users/heni/test-envir/matrixone/pkg/lockservice/deadlock.go:148 +0x158
github.com/matrixorigin/matrixone/pkg/lockservice.(*detector).doCheck(0x1400028ff80, {0x1068c8158, 0x14010932300})
	/Users/heni/test-envir/matrixone/pkg/lockservice/deadlock.go:127 +0x398
github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask.func1()
	/Users/heni/test-envir/matrixone/pkg/common/stopper/stopper.go:259 +0x6c
created by github.com/matrixorigin/matrixone/pkg/common/stopper.(*Stopper).doRunCancelableTask
	/Users/heni/test-envir/matrixone/pkg/common/stopper/stopper.go:254 +0xd8

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
fixed by #11033

**Comment by heni02** [comment]
回归该问题，发现update死锁后再truncate table 卡住一直不返回
<img width="674" alt="企业微信截图_8aaf921d-e32d-477f-b81e-2a28bb730f40" src="https://github.com/matrixorigin/matrixone/assets/113406637/d5de2cbc-3faf-42e4-9301-3b1a3b159c99">
具体复现步骤：
1cn mo, mysql login mo execute create table r1(c1 int)

use mo-load tool:
1.config case insert run.yaml,path : cases/ddl/run.yaml
vuser: 100
- sql: "insert into r1 values ({tbx});"
2. ./start.sh -c cases/ddl
3.config case update run.yaml,path:cases/ddl/run.yaml
vuser: 100
- sql: "update r1 set  c1={tbx};"
4. ./start.sh -c cases/ddl
5. truncate table r1;

**Comment by heni02** [comment]
试了"update r1 set c1={tbx} where c1=20;"这种情况有部分死锁情况出现，但也同样有truncate table卡住现象
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b9779c73-a02f-4f52-a660-870c4bd5b609)

**Comment by ouyuanning** [comment]
还没时间看。下周测

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
还没有处理

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
not working on this

**Comment by zhangxu19830126** [comment]
筛选block的逻辑引起数据没有读到，需要继续分析

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
not working on this issue

**Comment by zhangxu19830126** [comment]
现在跑不出来了，麻烦在测试下看看，最近修复了好几个悲观的问题。也可能修复掉了。

**Comment by heni02** [comment]
confirm tommorrow

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
confirm ,closed
it is no deadlock detected error,commit id: f43fcb6eca591b9e9ca70450a28d5f422cf7e29d
<img width="1402" alt="企业微信截图_9ac66157-c74e-4379-b30c-b9a074636e9e" src="https://github.com/matrixorigin/matrixone/assets/113406637/d53acb28-5b51-4af6-8f57-b291b99b6c96">
