### ISSUE TITLE
[Bug]: eks bvt regression: create table/role/user does not return result in 2min

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#9998]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-ded44d5
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5241028845/jobs/9462693608
<img width="1368" alt="企业微信截图_8c9b1cd0-aa18-47f3-bfcd-63f3b29e5817" src="https://github.com/matrixorigin/matrixone/assets/113406637/c4be2a49-d5b4-4423-9dd6-c20c9cb7decc">
<img width="1353" alt="企业微信截图_c59c2ee8-5b48-44e1-9a8f-6d1fd6521f32" src="https://github.com/matrixorigin/matrixone/assets/113406637/a66d56a9-4f15-4c7a-a0e4-279945489415">
<img width="1322" alt="企业微信截图_90c0849e-dbd5-4a4b-8bab-bc552b2e4c04" src="https://github.com/matrixorigin/matrixone/assets/113406637/d9e64321-5df8-4500-90fe-dac4f311217d">

mo log：
![image](https://github.com/matrixorigin/matrixone/assets/113406637/b15fe573-ddec-46fc-91f6-2a7ae590f634)

**Comment by sukki37** [comment]
@daviszhen please help identify the root cause of the issue, thank you.

**Comment by heni02** [comment]
pessimistic rc mode  bvt test also found this problem, multi 2cn 
job : https://github.com/matrixorigin/ci-test/actions/runs/5262845931/jobs/9512416689?pr=35
![image](https://github.com/matrixorigin/matrixone/assets/113406637/7ba23977-ba6f-4f32-bb60-ae2aabc069cf)

2023-06-14 03:54:46 ERROR Executor:169 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:14][create table index_03 (col1 bigint auto_increment primary key,col2 int,col3 float,col4 int,unique key id1(col2),key id2(col4));] MO does not return result in 120000 ms,con[id=0, user=dump, ***
2023-06-14 03:54:46 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:14][create table index_03 (col1 bigint auto_increment primary key,col2 int,col3 float,col4 int,unique key id1(col2),key id2(col4));] was executed failed, con[id=0, user=dump, ***
2023-06-14 03:54:46 ERROR Executor:181 - [EXPECT RESULT]:
null
2023-06-14 03:54:46 ERROR Executor:182 - [ACTUAL RESULT]:
MO does not return result in 120000 ms. 

2023-06-14 03:56:46 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:21][create table index_04 (col1 bigint,col2 int primary key,col3 float,col4 bigint,unique key id1(col1),key id2(col4));] was executed failed, con[id=0, user=dump, ***
2023-06-14 03:56:46 ERROR Executor:181 - [EXPECT RESULT]:
null
2023-06-14 03:56:46 ERROR Executor:182 - [ACTUAL RESULT]:
MO does not return result in 120000 ms. 

2023-06-14 03:58:46 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:57][create table index_12 (col1 bigint auto_increment primary key,col2 date,col3 date,unique key d1(col2),key d2(col3));] was executed failed, con[id=0, user=dump, ***
2023-06-14 03:58:46 ERROR Executor:181 - [EXPECT RESULT]:
null
2023-06-14 03:58:46 ERROR Executor:182 - [ACTUAL RESULT]:
MO does not return result in 120000 ms. 

2023-06-14 04:46:50 ERROR Executor:169 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:369][create account unique_test_account admin_name='admin' identified by '123456';] MO does not return result in 120000 ms,con[id=0, user=dump, ***
2023-06-14 04:46:50 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:369][create account unique_test_account admin_name='admin' identified by '123456';] was executed failed, con[id=0, user=dump, ***
2023-06-14 04:46:50 ERROR Executor:181 - [EXPECT RESULT]:
null
2023-06-14 04:46:50 ERROR Executor:182 - [ACTUAL RESULT]:
MO does not return result in 120000 ms. 

mo log and stack:
[multi-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/11742886/multi-cn-e2e-linux-x86-reports.zip)

**Comment by daviszhen** [comment]
> pessimistic rc mode bvt test also found this problem, multi 2cn @daviszhen job : https://github.com/matrixorigin/ci-test/actions/runs/5262845931/jobs/9512416689?pr=35 ![image](https://user-images.githubusercontent.com/113406637/245710368-7ba23977-ba6f-4f32-bb60-ae2aabc069cf.png)
> 
> 2023-06-14 03:54:46 ERROR Executor:169 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:14][create table index_03 (col1 bigint auto_increment primary key,col2 int,col3 float,col4 int,unique key id1(col2),key id2(col4));] MO does not return result in 120000 ms,con[id=0, user=dump, *** 2023-06-14 03:54:46 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:14][create table index_03 (col1 bigint auto_increment primary key,col2 int,col3 float,col4 int,unique key id1(col2),key id2(col4));] was executed failed, con[id=0, user=dump, *** 2023-06-14 03:54:46 ERROR Executor:181 - [EXPECT RESULT]: null 2023-06-14 03:54:46 ERROR Executor:182 - [ACTUAL RESULT]: MO does not return result in 120000 ms.
> 
> 2023-06-14 03:56:46 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:21][create table index_04 (col1 bigint,col2 int primary key,col3 float,col4 bigint,unique key id1(col1),key id2(col4));] was executed failed, con[id=0, user=dump, *** 2023-06-14 03:56:46 ERROR Executor:181 - [EXPECT RESULT]: null 2023-06-14 03:56:46 ERROR Executor:182 - [ACTUAL RESULT]: MO does not return result in 120000 ms.
> 
> 2023-06-14 03:58:46 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:57][create table index_12 (col1 bigint auto_increment primary key,col2 date,col3 date,unique key d1(col2),key d2(col3));] was executed failed, con[id=0, user=dump, *** 2023-06-14 03:58:46 ERROR Executor:181 - [EXPECT RESULT]: null 2023-06-14 03:58:46 ERROR Executor:182 - [ACTUAL RESULT]: MO does not return result in 120000 ms.
> 
> 2023-06-14 04:46:50 ERROR Executor:169 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:369][create account unique_test_account admin_name='admin' identified by '123456';] MO does not return result in 120000 ms,con[id=0, user=dump, *** 2023-06-14 04:46:50 ERROR Executor:179 - [/home/runner/work/ci-test/ci-test/head/test/distributed/cases/ddl/unique_secondary_index.sql][row:369][create account unique_test_account admin_name='admin' identified by '123456';] was executed failed, con[id=0, user=dump, *** 2023-06-14 04:46:50 ERROR Executor:181 - [EXPECT RESULT]: null 2023-06-14 04:46:50 ERROR Executor:182 - [ACTUAL RESULT]: MO does not return result in 120000 ms.
> 
> mo log and stack: [multi-cn-e2e-linux-x86-reports.zip](https://github.com/matrixorigin/matrixone/files/11742886/multi-cn-e2e-linux-x86-reports.zip)
> 
> cn config: service-type = "CN" data-dir = "./mo-data"
> 
> [log] level = "info" format = "console" max-size = 512
> 
> [hakeeper-client] service-addresses = [ "127.0.0.1:32001", ]
> 
> [[fileservice]] name = "LOCAL" backend = "DISK"
> 
> [[fileservice]] name = "SHARED" backend = "DISK" data-dir = "mo-data/s3"
> 
> [fileservice.cache] memory-capacity = "512MB" disk-capacity = "8GB" disk-path = "mo-data/file-service-cache" disk-min-evict-interval = "7m" disk-evict-target = 0.8
> 
> [[fileservice]] name = "ETL" backend = "DISK-ETL"
> 
> [observability] disableTrace = true disableMetric = true
> 
> [cn] primary-key-check = true uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf" listen-address = "0.0.0.0:7001" service-address = "127.0.0.1:7001"
> 
> [cn.Engine] type = "distributed-tae"
> 
> [cn.frontend] port = [16](https://github.com/matrixorigin/ci-test/actions/runs/5262845931/jobs/9512416689?pr=35#step:5:17)001
> 
> [cn.txn] mode = "Pessimistic" isolation = "RC" enable-sacrificing-freshness = true enable-cn-based-consistency = false

这个日志里面有好几类错误。
1，panic。20多个。
```
internal error: panic runtime error: index out of range [20] with length 20: 
runtime.goPanicIndex
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/panic.go:113
github.com/matrixorigin/matrixone/pkg/container/batch.(*Batch).GetVector
	/home/runner/work/ci-test/ci-test/head/pkg/container/batch/batch.go:208
github.com/matrixorigin/matrixone/pkg/sql/colexec/lockop.Call
	/home/runner/work/ci-test/ci-test/head/pkg/sql/colexec/lockop/lock_op.go:109
github.com/matrixorigin/matrixone/pkg/vm.Run
	/home/runner/work/ci-test/ci-test/head/pkg/vm/vm.go:61
github.com/matrixorigin/matrixone/pkg/vm/pipeline.(*Pipeline).ConstRun
	/home/runner/work/ci-test/ci-test/head/pkg/vm/pipeline/pipeline.go:123
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).Run
	/home/runner/work/ci-test/ci-test/head/pkg/sql/compile/scope.go:80
github.com/matrixorigin/matrixone/pkg/sql/compile.(*Scope).MergeRun.func1
	/home/runner/work/ci-test/ci-test/head/pkg/sql/compile/scope.go:112

```


2，

**Comment by daviszhen** [comment]
> issue 上的ci日志中的问题。job:https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5241028845/jobs/9462693608

panic 后，mo挂掉，导致bvt 报mo连不上。
![image](https://github.com/matrixorigin/matrixone/assets/60595215/a8646041-d1ac-47c6-b09e-c92e15ea2123)


![image](https://github.com/matrixorigin/matrixone/assets/60595215/fc801890-b1dd-477a-bebd-7b3a29bd1947)

**Comment by daviszhen** [comment]
@zhangxu19830126 @nnsgmsone PLZ

**Comment by daviszhen** [comment]
@heni02 傍晚又跑了一次。

mo挂掉。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/dd04ab2d-6813-4b63-ab1e-7fa530f8e8ab)

**Comment by zhangxu19830126** [comment]
1. lock range的问题，ziran在看

**Comment by zhangxu19830126** [comment]
@nnsgmsone 看一下engine里面txn的databaseMap是nil的问题

**Comment by nnsgmsone** [comment]
这个原因是因为一个事务已经调用了commit/rollback，然后又继续操作才会碰到这个问题。@dongdongyang3

**Comment by dongdongyang33** [comment]
in process

**Comment by heni02** [comment]
confirm tomorrow

**Comment by heni02** [comment]
eks bvt regression do not appear this problem

**Comment by heni02** [comment]
rc+pessimistc mode now start up failed ,wait confirm

**Comment by heni02** [comment]
confirm, rc+pessimistc mode 2cn did not have this problem
https://github.com/matrixorigin/ci-test/actions/runs/5442383563/jobs/9961888563
